### ISSUE TITLE
Gulp Serve Error: Error parsing file 'config.json', section [undefined]

### ISSUE THREAD

**Issue by vball525** [SharePoint/sp-dev-docs#10]
Windows Server 2012 R2. Patched today.
Running the command "gulp serve" produces the following error and output:

Build target: DEBUG
Error: Error parsing file 'config.json', section [undefined]:
(undefined) JSON_OBJECT_VALIDATION_FAILED

[21:23:42] Error - Unknown
Error: Error parsing file 'config.json', section [undefined]:
(undefined) JSON_OBJECT_VALIDATION_FAILED

[21:23:42] =========[ Finished ]===========
[21:23:43] Project helloworld-webpart version: 0.0.1
[21:23:43] Build tools version: 0.7.1
[21:23:43] Node version: v4.5.0
[21:23:43] Total duration: 2.1 min
[21:23:43] Task errors: 5

**Comment by vball525** [comment]
fixed by doing the following things:
npm update
reboot server
check the original web part but still got error
created new folder and started over
got the es6-module error again
installed that again
now working for second folder

**Comment by patmill** [comment]
Unclear what the original issue was here.  However as for bugs / improvements to make to understand or debug this, one thing that jumps out here is to actually state what the parse error is.

**Comment by vball525** [comment]
@patmill sorry for any confusion, what i typed in the first bug report was exactly what was shown in powershell, verbatim, when running the "gulp serve" command. There was no more info available.

**Comment by chakkaradeep** [comment]
To be honest, we have not tested in Windows Server and unclear what is needed. Can you make sure you have the NodeJS LTS installed along with other tools? I am also not clear on how much other dev tools support Windows Server.

**Comment by iclanton** [comment]
All of the tools should work fine in Windows Server. My primary dev environment is Windows Server 2012 R2 and all of our tools work fine there (because most of them were written there).

For the original issue - can you confirm you're running Node 4.X (we're running 4.4.7 internally) and NPM 3.10.X? My first guess would be that you're running either an incompatible version of Node or an incorrect version of Z-Schema got installed which is incorrectly validating the config files.

It's also possible that your config files are messed up. Is this a vanilla, yeoman-generated project?

**Comment by vball525** [comment]
node v4.5.0, npm 2.15.9, yeoman-generated project.

**Comment by patmill** [comment]
You'll want to be on npm3.  We've updated the setup docs to reflect this.  Run 

     npm -g install npm@next

**Comment by Bearshield** [comment]
@chakkaradeep  I just built a new Windows Server 2016 Technical Preview 5 server, fresh install of all the SPFx Tooling, VS Code, etc. Everything worked fine, including Workbench locally.  Loaded SPApp to Dev Tenant, and that presented too. My previous SPFx install was on Windows 10.

So far my experience is in alignment with what @iclanton stated.

**Comment by nickpape-msft** [comment]
Closing this issue as it appears to be an NPM2 problem. Documentation has been updated.
