### ISSUE TITLE
Button new in list does not redirect correctly to the form customizer associated to the contenttype

### ISSUE THREAD

**Issue by magonzalezm** [SharePoint/sp-dev-docs#10010]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We have a contenttype of a list associated with a form customizer.

Originally linked like this:
$contentType = Get-PnPContentType -List "THELIST" -Identity "THENAME"
$contentType.NewFormClientSideComponentId = "441750e7-a9af-4078-aa43-e58a86820d42";
$contentType.EditFormClientSideComponentId = "441750e7-a9af-4078-aa43-e58a86820d42";
$contentType.DisplayFormClientSideComponentId   = "441750e7-a9af-4078-aa43-e58a86820d42";
$contentType.Update($false)
$clientContext.ExecuteQuery()

When you press the button new, the "redirection" is made wrongly to:
Lists/THELIST/0x01005986E7EC085F7341966C853B9BDF132700D0BE7D34BB49BB4CBBC73F98460FE6EE?....

Instead of: 
_layouts/15/SPListForm.aspx?PageType=8 .... 

And it is not working since 23:30 09/11 Madrid time.

So form customizer in the New Form is broken, this is not happening for edit or display.

### Steps to reproduce

1. If you have the form customizer installed, you only have to press new item
2.
3.

### Expected behavior

You should be redirected to:
_layouts/15/SPListForm.aspx?PageType=8 ....

**Comment by EA12** [comment]
We are facing the same. ALL our Forms Customizers in production gets a 404 when hitting New item in the list.

Please fix this immediatly

**Comment by magonzalezm** [comment]
> We are facing the same. ALL our Forms Customizers in production gets a 404 when hitting New item in the list.
> 
> Please fix this immediatly

Just a quick fix / workaround. Create a link in the menu / or button anywhere with link to:
/lists/YOURLIST/newform.aspx

Curiously it's not happening in every list.

**Comment by EA12** [comment]
If we create a link to NewForm.aspx, we need to hit refresh that the form will be shown, otherwise we see just white on white.
Only after the refresh, the url will change to ..._layouts/15/SPListForm.aspx?PageType=8&List...

Too sad MS is not testing their updates..

**Comment by axl220** [comment]
How can we promote this as a higher issue, currently experiencing this on several client environments, is there a workaround?

**Comment by Mcmo7** [comment]
Are there list updates filtering through related to this?

Can see that site collections are switching between "old" and "new" list formatting and I'm assuming when they switch back to new, this is going to be included as I can see a number of sites already with this "redirection" causing the break.

Lists/THELIST/0x01005986E7EC085F7341966C853B9BDF132700D0BE7D34BB49BB4CBBC73F98460FE6EE?

Apart from the instability of the forms lists constantly switching for user experience over the past few months, I would note this as critical, as essentially you cannot raise new items under this re-direct condition applied without Quick Link workarounds etc. which cannot be suggested to implement and train for 1000's of users etc. last minute on a site by site basis when the issue suddenly appears without warning.

UAT and PRD site collection behaviour does not match so if there was an update required to meet the new "re-direct" functionality rolled out, need to take into account planning maintenance windows without awareness into Production sites, engaging clients, explaining what has happened, lining up resource etc.

**Comment by VesaJuvonen** [comment]
@reedpamsft - Seems to be an issue related on the SPFx in lists - I think the scenario difference here is the association of the form customizers to the content type - which we should check that it's handled correctly in the new lists.

**Comment by mnikitinaa** [comment]
I have the same issue for all new forms.

**Comment by ilyamokka** [comment]
This issue affected 30+ end users for us, please do something about this

**Comment by yur-st** [comment]
Today, it also started occurring on our tenants for lists with content types enabled, and it prevents adding new items to a list.
Content types have NewFormCleintSideComponentId="<guid>" and NewFormUrl="_layouts/15/SPListForm.aspx?PageType=8"
Please fix this.

**Comment by reedpamsft** [comment]
Is this still happening for anyone?  There was a configuration change made recently which should have fixed this, but if it's still happening for anyone then that would suggest it has a different root cause than the other issue.

**Comment by Mcmo7** [comment]
Logged in to a few sites reported and back to normal from what I can see on my end.
Will continue to monitor this week and follow up on our comms.
Appreciate the quick fix on this @reedpamsft / @VesaJuvonen.

Many thanks

**Comment by magonzalezm** [comment]
Thx a lot, @VesaJuvonen , @reedpamsft   it seems to work again!
I hope our early warning has helped others!
