### ISSUE TITLE
Run gulp serve with 'NODE_NO_HTTP2=1' when using SPFx on node v8

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1002]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Tip

When working with SPFx on Node.js v8 you have to run gulp serve, like:

```sh
NODE_NO_HTTP2=1 gulp serve
```

if you call `gulp serve` without the extra flag, you won't be able to open the workbench in the browser. This is caused by the experimental http/2 feature that is a part of Node v8.

**Comment by Mike-tech** [comment]
@waldekmastykarz i tried this command but getting: The term 'NODE_NO_HTTP2=1' is not recognised as the name of a cmdlet.

Also same thing when i try the command from Node.js command prompt: 'NODE_No_HTTP2' is not recognised as an internal or external command.

I am on Node v8.9.0

Thanks

**Comment by waldekmastykarz** [comment]
I assume you're on Windows. See the following article to see how to set an environment variable for Node on Windows: https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows

**Comment by Mike-tech** [comment]
Yes i am using Windows. My node js path is already in environment variable. I tried the commands 'set NODE_NO_HTTP2=1' but made no impact, even after restart. I tried different combination in that page but no avail. 
I've had downgraded to Node v6.11. Although it would be nice to know the exact command required to work with the latest version.

**Comment by waldekmastykarz** [comment]
@Mike-tech have you also tried the following:

> To set environment variables globally so they persist beyond just the single command prompt, you can find the tool from System in Control Panel (or by typing 'environment' into the search box in the start menu).

**Comment by waldekmastykarz** [comment]
Confirmed: above works. After adding the environment variable, I had to restart my terminal (cmder) for the change to work.

**Comment by Mike-tech** [comment]
Can please verify my settings - i did restart after setting this: is this right?

![image](https://user-images.githubusercontent.com/21954124/32365560-1d568fae-c072-11e7-984a-1716bb3076ca.png)

**Comment by iclanton** [comment]
Because Node 8 went into LTS on November 1st, we'll be working on supporting it soon. For now only Node 6 is officially supported.

However, setting the `NO_NODE_HTTP2` environment variable to `1` worked when I just tried it on Windows.

**Comment by waldekmastykarz** [comment]
@Mike-tech that's exactly the setting I have and it's working for me.

**Comment by Mike-tech** [comment]
@waldekmastykarz Many thanks for confirming that. Perhaps it's because i've now downgraded to node v6??? I will have to check this another time. I'm busy working on a SPFx project, so will stay with the stable v6. Cheers

**Comment by Ofer-Gal** [comment]
in package.json enter:
```
"scripts": {
    "dev" : "set NODE_NO_HTTP2=1&& gulp serve",

```
then npm run dev or yarn dev will work for you 
This is how you add evironament variable befor node command I guess

**Comment by casvaniersel** [comment]
Saved the day dude :) thanks!

**Comment by HeToC** [comment]
does not work for me on my mac

**Comment by lifayt** [comment]
Echoed - this does not solve the issue on Mac.

**Comment by lifayt** [comment]
Cheers, thank you!

**Comment by pankajsurti** [comment]
I tried all install and uninstall of Node, NPM, Gulp & SpX. I was thinking I was missing the step with the documentation. But this post helped me. I added NODE_NO_HTTP2=1 in the environment variable and it worked. Thanks. This should be mentioned in the documentation of the SPx

**Comment by andrewconnell** [comment]
@pankajsurti I don't think it should be addressed. The docs clearly state SPFx is supported with Node.js v6.*. 

This env variable is only required for Node.js v8+... since they don't support it, calling it out adds confusion IMHO. Plus, I think the team is working on their workbench to resolve this.

**Comment by andrewconnell** [comment]
Aaaaaaannnnd this is resolved in the Yeoman Generator v1.4.1. Upgrade to that version for no workaround to use Node.js v8 LTS.

**Comment by btastic** [comment]
I just tried the new yeoman generator 1.4.1 with Node.js 8.9.4 and it is still giving me ```ERR_SSL_PROTOCOL_ERROR``` in chrome and IE.

Workflow:
1. Downloaded and installed node.js 8.9.4 LTS
2. ```npm install -g yo gulp```
3. ```npm install -g @microsoft/generator-sharepoint```

4. ```yo @microsoft/sharepoint```
```
Entered a solution name
Sharepoint 2016 onwards, including Sharepoint Online
Use the current folder
MyProjectName
MyProjectName description
React
```

5. ```gulp trust-dev-cert```
Clicked OK at the prompt

6. ```gulp serve```

Did I miss something?

**Comment by fksontini** [comment]
thanks !

**Comment by Jonas-buriti** [comment]
I was facing the sam isse, and just a npm update solved it!

**Comment by jassimkhan** [comment]
I set the environment variable globally NODE_NO_HTTP2=1 and it worked for me.
![1](https://user-images.githubusercontent.com/37412919/37475149-61dd7d52-2848-11e8-8e2f-e82db81f6206.png)

**Comment by joelfmrodrigues** [comment]
All working well for me since 1.4.1 update

**Comment by saendu** [comment]
Confirming this working on OSX after upgrading my project to 1.4.1! No cert issues anymore.

**Comment by akupaka** [comment]
I have this issue on Ubuntu 18.04, with this package version

$ npm list -g -depth 0
/usr/local/lib
├── @microsoft/generator-sharepoint@1.5.1
├── gulp@3.9.1
├── npm@6.1.0
├── typescript@2.9.2
└── yo@2.0.3

NODE_NO_HTTP2=1 helped, but still.

**Comment by bforsyt4** [comment]
Adding Env. variable did not work for me. Downgraded Node to 6.14.3, with the following:

+-- @microsoft/generator-sharepoint@1.5.1
+-- gulp@3.9.1
+-- gulp-cli@2.0.1
+-- iisexpress-proxy@1.3.0
+-- npm@6.1.0
+-- typescript@2.6.1
`-- yo@2.0.4

workbench now displays

**Comment by andrewconnell** [comment]
Not sure that's the best advice. Node.js v8 works just fine with the latest versions of Yeoman (v2.0.5+), Gulp (v3.9.1) & the SPFx generator (v1.6.0. I suspect you ~may~ be having issues @fabianmadurai if you aren't on a current version of the SPFx generator. There were changes in one version that addressed issues with Node.js v8... if you are on an older version that would make sense.

**Comment by eosorioarmenta** [comment]
linux fedora 28, with nvm nodejs v8.12.0 does not work, out of the box examples sp-dev-fx-webparts, seems like a really messy dev environment or not really cross-platform framework

**Comment by martinpinto** [comment]
setting NODE_NO_HTTP2=1 didn't work out for me. I changed the port number on \config\serve.json and set "https" to false and then it worked out under Firefox. I am using Node v8.12.0

**Comment by andrewconnell** [comment]
@martinpinto you shouldn't need to set that flag... if you are using Node v8.* & a recent version of the SPFx generator (the current version is v1.6.0), you don't need this flag.

What problem are you having & what version of the generator are you running?

**Comment by vasavidurgaprasad** [comment]
I made NO_NODE_HTTP2 environment variable to 1. but it is not working.
I am using SPFx framework 1.8 and Node 10.16.2

**Comment by georgey58** [comment]
I am still getting **Can’t connect securely to this page** running the HelloWorld example
Node version: v10.16.3
I've had tried NODE_NO_HTTP2 = 1 and setting https=false in serve.json

**Comment by brudnak** [comment]
What a terrible experience.. SharePoint is the most maddening thing I've ever dealt with. And some people think React is hard lol...
