### ISSUE TITLE
localhost workbench cannot load

### ISSUE THREAD

**Issue by kenchengch** [SharePoint/sp-dev-docs#1003]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I follow hello world webpart but just firefox prompt for add exception for localhost. But still cannot reach localhost just keep loading. I can see the workbench request if i reload localhost page.
![2](https://user-images.githubusercontent.com/12043568/32267592-bacdf71a-bf26-11e7-8f0c-84f2ffb974b7.png)
![1](https://user-images.githubusercontent.com/12043568/32267604-c1ffa0d8-bf26-11e7-9372-48ba33c170ca.png)

**Comment by andrewconnell** [comment]
Seems you forgot this first step? https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part

**Comment by kenchengch** [comment]
fixed. I just remove nodejs 8 then reinstall nodejs 6 then work! Thank you @andrewconnell

**Comment by andrewconnell** [comment]
Oh sorry, that's not what I was pointing to. It looks like you didn't trust the dev cert... if it's fixed by downgrading Node, check this issue as it looks like there's an issue with HTTP/2 prelim support in recent Node.js v8.* builds:

https://github.com/SharePoint/sp-dev-docs/issues/1003

**Comment by waldekmastykarz** [comment]
I believe you wanted to mention #1002 @andrewconnell?

**Comment by andrewconnell** [comment]
Arg... thanks @waldekmastykarz . Yeah... guess GitHub issues don't check for cyclic references...
