### ISSUE TITLE
[$_CommentCount] returning zero or null

### ISSUE THREAD

**Issue by elsiegit** [SharePoint/sp-dev-docs#10045]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

[$_CommentCount] is returning null / zero even when a list item has comments. This was previously working. I have tried testing with "txtContent": "[$_CommentCount]" and also the comment count formatting in the repository.

### Steps to reproduce

1. Format a text column to display "txtContent": "[$_CommentCount]"
2. Add a comment to 1 or more items
3. Observe that the comment count remains as zero despite adding a comment

### Expected behavior

Comment count should be displayed

**Comment by tpodugu-ms** [comment]
@elsiegit Thanks for reporting this. I will check with the team and update.

**Comment by tpodugu-ms** [comment]
@elsiegit 
Does the issue still occur after reloading the page?

**Comment by elsiegit** [comment]
Seems ok now, thank you
