### ISSUE TITLE
Error creating web part named 'Web part' using generator v1.3.4

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1004]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to scaffold a web part no matter its name.

#### Observed Behavior
When creating web part named 'Web part', the generator scaffolds broken files. When you try to build the project, you get the following error:

```
Error - typescript - src/webparts/WebPart.ts(10,13): error TS1005: '=' expected.
```

This is caused by the following (invalid) file tree (notice missing file names in the SCSS and TSX files):
```
src/
|____webparts
| |____components
| | |____.module.scss
| | |____.tsx
| | |____IProps.ts
| |____loc
| | |____en-us.js
| | |____mystrings.d.ts
| |____test
| | |____WebPart.test.ts
| |____WebPart.manifest.json
| |____WebPart.ts
```

#### Steps to Reproduce
- create new project
- add web part
- name the web part `Web part`
- `gulp bundle`
- 💥

**Comment by manishgarg1** [comment]
@waldekmastykarz , thank you for reporting the issue. We are able to repro it and are trying to get it fixed quickly.
