### ISSUE TITLE
Words 'web part' removed from the web part folder, some filenames, title and description

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1005]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to scaffold web parts and its resources using the specified name. If some words are not allowed to be used, then they should be reported explicitly when providing the name, rather than being implicitly removed in some places but not in others. Also, the naming should be consistent across all files and source code.

#### Observed Behavior
When creating a web part named `My web part` you get the following file/folder structure:

```
.
|____webparts
| |____my
| | |____components
| | | |____IMyProps.ts
| | | |____My.module.scss
| | | |____My.module.scss.ts
| | | |____My.tsx
| | |____loc
| | | |____en-us.js
| | | |____mystrings.d.ts
| | |____MyWebPart.manifest.json
| | |____MyWebPart.ts
| | |____test
| | | |____MyWebPart.test.ts
```

Notice how the words `web part` are missing from the web part folder name (my), from the React component (My.tsx), interface (IMyProps.ts) and Sass file (My.module.scss), but how they are included in the main web part file (MyWebPart.ts) and the manifest (MyWebPart.manifest.json). Also, if you look at the contents of the generated manifest you will see:

```json
{
  "$schema": "https://dev.office.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
  "id": "9ed5c37e-4e7d-4a8e-9114-df00724129c6",
  "alias": "MyWebPart",
  "componentType": "WebPart",

  // The "*" signifies that the version should be taken from the package.json
  "version": "*",
  "manifestVersion": 2,

  // If true, the component can only be installed on sites where Custom Script is allowed.
  // Components that allow authors to embed arbitrary script code should set this to true.
  // https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f
  "requiresCustomScript": false,

  "preconfiguredEntries": [{
    "groupId": "5c03119e-3074-46fd-976b-c60198311f70", // Other
    "group": { "default": "Other" },
    "title": { "default": "My" },
    "description": { "default": "My web part description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "My"
    }
  }]
}
```

The words `web part` are included in the alias but removed from the web part title, description and properties.

#### Steps to Reproduce
- create new project using generator v1.3.4
- add new web part named `My web part`
- see the scaffolded folder/file structure and the contents of the generated web part manifest

**Comment by andrewconnell** [comment]
MSFT, PLEASE don't start adding coding pattern enforcement with files created by the generator... ESP with no insight into what's allowed or not allowed.

**Comment by nickpape-msft** [comment]
This logic has been reverted. Please open a new issue if you are still seeing this in the latest release.
