### ISSUE TITLE
ListView Command Set extension suddenly not loading in embedded list view (SitePage with list web part)

### ISSUE THREAD

**Issue by SPJS** [SharePoint/sp-dev-docs#10057]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Tested with Chrome Version 131.0.6778.140 (Official Build) (64-bit) and Edge Version 131.0.2903.99 (Official build) (64-bit)

### Describe the bug / error

When you add a list view command set extension to a site it works just fine in the default list views, but it has suddenly stopped working when you embed a list view in a SitePage. This worked earlier, but suddenly the list view command set is not even trying to load. The network tab shows no trace of the files associated with the command set and the console does not show any related errors.

There are no difference if I gulp serve the files or just load them from the app catalog - no trace of the files trying to load.

The view is configured with "Show command bar" and the command bar shows Edit in grid view, Share, Export to Excel, Copy link and Delete but no trace of the list view command set buttons.

This is tested with the command set extension hello-world example: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

My tenant is on "Targeted release".

### Steps to reproduce

1. Install a command set extension and ensure that it loads in a normal list view.
2. Embed a list view in a sitepage and observe that the list view command set does not load.

### Expected behavior

The ListView Command Set extension should load in an embedded list view.

**Comment by VesaJuvonen** [comment]
@reedpamsft  - seems to be related on the modern list changes.

**Comment by natalieethell** [comment]
Thanks @SPJS @VesaJuvonen , taking a look.

**Comment by reedpamsft** [comment]
As a note on this one, we made a configuration change that should have already taken effect which will fix this.  The unfortunate side effect of doing that is that the "customizers don't load on personal views" bug will be back, but a fix for that will roll out with new client builds in January.

**Comment by reedpamsft** [comment]
@SPJS  and @VesaJuvonen , sorry, do you mind validating my commenta bove and closing this if it's fixed?

**Comment by SPJS** [comment]
@reedpamsft I can confirm that the customizers now load in the embedded list view.

Thanks,
Alexander

**Comment by SPJS** [comment]
Sorry, forgot to mark it as closed.

Alexander
