### ISSUE TITLE
serve.json schema should include the serveConfigurations property

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1008]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The schema referenced in serve.json scaffolded using v1.3.4 should correctly document the `serveConfigurations` property.

#### Observed Behavior
The schema referenced in serve.json doesn't reference the `serveConfigurations` property, making it inconvenient for developers to change the entries to their specific needs.

#### Steps to Reproduce
View the contents of https://dev.office.com/json-schemas/core-build/serve.schema.json and see that it doesn't reference the `serveConfigurations` property.

**Comment by VesaJuvonen** [comment]
Thanks for reporting this. We have had some issues on getting the json schema file updated at the dev.office.com and are working on this right now. We should have this sorted out in a day or two.

**Comment by EA12** [comment]
Still not referenced. Any News about this one?

**Comment by dvm-2k1** [comment]
Is this Bug got fixed? asking it because we are also getting same issue which was reported by @waldekmastykarz

**Comment by anthonywhite** [comment]
I'm getting this warning
SPFx 1.8.2 which has schema URL https://developer.microsoft.com/json-schemas/core-build/serve.schema.json but dev.office.com appears identical
