### ISSUE TITLE
Gulp Serve not loading by default, even after installing gulp trust-dev-cert

### ISSUE THREAD

**Issue by Mike-tech** [SharePoint/sp-dev-docs#1010]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
After installing SPFx with React using yo @microsoft/sharepoint and installing gulp trust-dev-cert, when you run gulp serve the browser should open the workbench successfully, where you can add web part.

#### Observed Behavior
The browser opens but fails to display page with an error "Cannot securely connect to this page" on IE. The gulp in command line seems to hung at "Finish subtask 'reload' after.
Changing "https": false, and initial page to use http://localhost... in serve.json file seems to work fine. so there seems to be a problem with the certificate. This means unable to develop in O365. 

#### Steps to Reproduce
Install the SPFx webpart on a vanilla. Currently experiencing this on a VM. I've set this up in this environment before without any issue. 

Hope someone can help to identify if there is an issue.

**Comment by andrewconnell** [comment]
See #1003

**Comment by aakashrshah** [comment]
it can only happen with microsoft open source that even the most minimal bootstrap application will throw an error. It's the worst development environment ever.
\

**Comment by andrewconnell** [comment]
@aakashrshah Just because you can't get it working doesn't mean it's a bad environment. In this case that's almost a year old, the individual didn't follow the instructions for what things were and were not supported. When they followed the instructions, worked right away.
