### ISSUE TITLE
Update official statement support to Node v8 LTS

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1012]
Node v8 is now LTS. By default it ships with npm@5. Since SPFx is meant to work with Node LTS it would be good to update the official support statement at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment.

**Comment by iclanton** [comment]
We hope to support Node 8 soon, but there are currently a few issues that we're working through. We'll update the support statement as soon as we've dropped a release with those issues fixed.

I'll make sure that article gets updated to reflect that currently only Node 6 is officially supported. Thanks for pointing this out!

**Comment by VesaJuvonen** [comment]
Article is updated with the latest guidance few days back and we'll update that as we add Node v8 support. Thx @waldekmastykarz  for following up on the requirement to do so.

**Comment by qz2017** [comment]
Closing this ticket because the doc has been updated.

**Comment by russgove** [comment]
So if i upgrade to node 8 so i can user spfx 1.7,  can i still build older projects that we created in  and or upgraded to  spfx 1.4?

**Comment by waldekmastykarz** [comment]
Yes, you can, but they will require an older version of Node. To easily switch between the different versions of Node you can use nvm or Docker.
