### ISSUE TITLE
Latest Node.js LTS version (8.9.0) doesn't work in SharePoint Framework web part development

### ISSUE THREAD

**Issue by ollij** [SharePoint/sp-dev-docs#1013]
Updating to the latest Node.js LTS version 8.9.0 causes security error when creating new web part project and doing _gulp serve_.

#### Category
- Bug

#### Expected or Desired Behavior
After _gulp serve_ command browser opens and workbench loads correctly.

#### Observed Behavior
Edge: Can’t connect securely to this page - This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
Chrome: This site can’t provide a secure connection - localhost sent an invalid response. - ERR_SSL_PROTOCOL_ERROR

#### Steps to Reproduce
1. Uninstall current version of Node.Js
2. Install latest LTS version (8.9.0) of Node.js from https://nodejs.org/en/
3. Create new web part project with Yeoman using the default values
4. Execute _gulp serve_

**Comment by kimpihlstrom** [comment]
This behavior is also reproducible on all major browsers (Chrome, Firefox, IE, Egde, etc). 

Possible workaround is to uninstall the current LTS relase of NodeJS and download the previous LTS release, https://nodejs.org/download/release/v6.11.5/.

**Comment by waldekmastykarz** [comment]
Could it be the same as #1002?

**Comment by yogsodoth** [comment]
I had this issue, followed procedure for #1002 and it now works.

**Comment by adambu** [comment]
+1 from my customer.  Created a pull request for https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

**Comment by patrick-blanc** [comment]
Thanks @waldekmastykarz, it works fine. See #1002

**Comment by qz2017** [comment]
Closing this ticket as dupe of [1002](https://github.com/SharePoint/sp-dev-docs/issues/1002)
