### ISSUE TITLE
How to use office-ui-fabric-react with theming when following the latest guidance?

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1014]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
You have published new guidance around how to use office ui fabric react in spfx webparts: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration
When using the approach of adding the latest release of office-ui-fabric-react to the spfx solution, theming does not work anymore.
What is the correct and supported way to get theming back working again when using office-ui-fabric-react components?

**Comment by lahuey** [comment]
Hi @OliverZeiser,

I was unable to repro this issue. Please reopen if you are still seeing problems with theming.
