### ISSUE TITLE
Outdated Visual Studio topics in sp-add-ins

### ISSUE THREAD

**Issue by Linda-Editor** [SharePoint/sp-dev-docs#1021]
**The following topics in sp-add-ins (links are on STAGING site) appear to have outdated information about Visual Studio. I suggest that a writer or PM either updates these or removes them:**
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/publish-sharepoint-add-ins-by-using-visual-studio?branch=master
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=master _(this one contains outdated info about Windows Server and Hyper-V under "Install the operating system")_
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/what-s-new-in-office-developer-tools-for-visual-studio?branch=master _(no info on this page)_

**On the following topics, I updated the link to "Install Visual Studio" to the 2017 version; 1) please confirm that it is the correct one (links are on STAGING site); 2) also check "installer" links to make sure they're the right ones.**
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins?branch=master
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins?branch=master
- https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365?branch=master

**Comment by davidchesnut** [comment]
Do we know if it is just this one topic, or do we need to check others as well?

**Comment by Linda-Editor** [comment]
It’s the 6 topics that I listed in the bug…

I haven’t looked at the “Develop” section yet; there could be more there.

**Comment by Linda-Editor** [comment]
Hey @davidchesnut  and @VesaJuvonen, I'm about to edit the sp-add-in Develop topics and realized I never got an answer to this question: can you confirm that it's okay to link to Visual Studio 2017 (instead of 2013) on the pages listed above? If so, I can find and fix other instances. Thank you!

**Comment by davidchesnut** [comment]
Hi @Linda-Editor , to do this correctly you would need to verify that the steps and UI did not change between versions.
