### ISSUE TITLE
Adding web part using generator @1.3.4 to a project created using @1.0.2 modifies project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1029]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When adding a web part using a newer version of the generator than the version used to create the project, the generator should just add the web part without changing any of the project files. If some changes are necessary, it should prompt the user for confirmation first before applying them.

#### Observed Behavior
When you add a web part using generator @1.3.4 to a project created using generator @1.0.2, the generator updates dependencies in the package.json file and changes the config.json file to schema v2 without any additional confirmation.

#### Steps to Reproduce
- create project using SPFx generator @1.0.2 with a JavaScript web part
- using generator @1.3.4 add a new JavaScript web part to the project
- notice changes in the project files
  - some dependencies in project.json are updated to 1.3.4
  - config.json is updated to schema v2

**Comment by andrewconnell** [comment]
Is this still an issue, or is it even relevant? Seems outdated and even if it was a bug, not something that would get addressed due to it being so old and the times people would run into it would be minimal.
