### ISSUE TITLE
Adding React web part using generator @1.3.4 to a project created using generator @1.0.2 breaks the project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1030]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When you add a web part to a project using a newer version of the generator than the version used to create the project, the generator should just add the web part. If the web part format is not backwards compatible, the generator should warn about it without proceeding.

#### Observed Behavior
When you add a React web part using the generator @1.3.4 to a project created using generator @1.0.2, the project cannot be built anymore due to differences in how React web parts are implemented in the different versions of SPFx.

The following error is displayed:

```text
Error - typescript - src/webparts/toDo/ToDoWebPart.ts(18,6): error TS2345: Argument of type 'typeof ToDo' is not assignable to parameter of type 'ComponentClass<IToDoProps>'.
```

#### Steps to Reproduce
- using generator @1.0.2 create a new project with a React web part
- `gulp bundle` to verify that the project is building
- using generator @1.3.4 add a new React web part to the project
- `gulp bundle`
- 💥

**Comment by andrewconnell** [comment]
Is this still an issue, or is it even relevant? Seems outdated and even if it was a bug, not something that would get addressed due to it being so old and the times people would run into it would be minimal.
