### ISSUE TITLE
updating site classification value: Issue 859 raised from question to bug

### ISSUE THREAD

**Issue by kath561** [SharePoint/sp-dev-docs#1031]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behaviour
as video "working with tenant properties" [https://www.youtube.com/watch?v=SVIrtZ2nM6s](https://www.youtube.com/watch?v=SVIrtZ2nM6s)
when value is changed then this change should be persistent as normally expected.

#### Observed Behaviour
extensively detailed in issue 859 question.
[https://github.com/SharePoint/sp-dev-docs/issues/859](https://github.com/SharePoint/sp-dev-docs/issues/859)

#### Steps to Reproduce
on a modern team site, configure classification settings as per video guidance. create new modern team site with  classification.
ensure setting appears on site home page correct;y
follow video steps to update the setting via CSOM using site object and latest core module
confirm that a GET of value from CSOM shows desired value has been apparently set.
open site in browser and value will be correct and then change to being incorrect
wait in case of updates
some days later value is still incorrect

Connect-PnPOnline -Url $siteUrl -Credentials $cred
 $site = Get-PnPSite
 Get-PnPProperty -ClientObject $site -Property Classification
 $site.Classification
 $site.Classification = "Test"
 Execute-PnPQuery

=========================
 Sharing is caring.

**Comment by mmsharepoint** [comment]
I don't think this is a bug. When checking the source code for the new SetSiteClassification extension method in PnPCore, it is visible that only communication sites are set via the site property but team sites are set via the Groups object

**Comment by kath561** [comment]
I take your point but the bug is that the set command appears to work but actually fails to work for team sites. If the property cannot be Set successfully then it should be read-only on the object and handled by the more sophisticated commands that can accommodate different site types.

So the bug is not so much that the Set fails but that it offers the appearance of working but not the actuality.

**Comment by moyali** [comment]
@VesaJuvonen This is related to PnPCore and not SPFx. Please communicate the feedback. Thanks.
