### ISSUE TITLE
gulp trust-dev-cert command not working for SharePoint Framework project creation

### ISSUE THREAD

**Issue by LakshmiMurugavadivelu** [SharePoint/sp-dev-docs#1033]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
**- [ ] Bug -- It is a bug**
- [ ] Additional article idea

#### Expected or Desired Behavior
I am trying to execute 'gulp trust-dev-cert not' this command in the project folder and getting the below error please help.
I am following the instruction provided here in this page [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part ](url)
to create a startup project for SharePoint Framework
#### Observed Behavior
PS C:\dev\spframework\helloworldsolution> gulp trust-dev-cert
Build target: DEBUG
[22:15:27] Using gulpfile C:\dev\spframework\helloworldsolution\gulpfile.js
[22:15:27] Starting gulp
[22:15:27] Starting 'trust-dev-cert'...
[22:15:27] Starting subtask 'configure-sp-build-rig'...
[22:15:27] Finished subtask 'configure-sp-build-rig' after 8.35 ms
[22:15:27] Starting subtask 'trust-cert'...
**[22:15:29] Error - [trust-cert] TypeError: Cannot read property 'toString' of null
[22:15:29] Error - 'trust-cert' sub task errored after 2.42 s**
 **Cannot read property 'toString' of null**
[22:15:29] 'trust-dev-cert' errored after 2.43 s
[22:15:29]
[22:15:30] ==================[ Finished ]==================
**Error - [trust-cert] TypeError: Cannot read property 'toString' of null
Error - 'trust-cert' sub task errored after 2.42 s
 Cannot read property 'toString' of null**
[22:15:30] Project helloworldonline version: 0.0.1
[22:15:30] Build tools version: 3.0.5
[22:15:30] Node version: v8.9.1
[22:15:30] Total duration: 4.94 s
[22:15:30] Task errors: 2

Thanks for your contribution! Sharing is caring.

**Comment by craghavendra21** [comment]
Hi, I guess SPFx still not support Node version 8. If you downgrade Node version to 6.0 then it should work for you.

**Comment by iclanton** [comment]
Yeah this is a Node 8 issue. We don't support Node 8 yet.

**Comment by waldekmastykarz** [comment]
Are you sure it's Node v8? I'm running node v8.9.1 on macOS and the `trust-dev-cert` task works just fine.

**Comment by everydev** [comment]
Works fine in node v8.9.1 in Windows 7,  I got alert pop up to install the certificate.

**Comment by gogreen0417** [comment]
i am having the same issue even with node v6.0.0. Can someone please help me?

**Comment by Mixok** [comment]
Any news about this? 

I have tested node v8.8.1 and  v6.14.2 with the same result.

**Comment by Jontay005** [comment]
It worked for me after I downgraded node version to 6

**Comment by anantv10** [comment]
First You need to Downgrade the Node version to below 9.0.0
then when your scaffolding is completed you need to get inside that folder suppose you have created hello world then you need go inside that folder then hit below command for creating certificate
" gulp trust-dev-cert"  Then it will work
![gulp trust-dev-cert](https://user-images.githubusercontent.com/20799601/49568572-63678600-f957-11e8-9aed-7843519b97c6.PNG)

**Comment by andrewconnell** [comment]
Still having issues? Lots of things have changed since originally posted (SPFx updated & now supported on Node.s v8)...

**Comment by anthony-git** [comment]
am following the instructions from: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part
Error is thrown while executing gulp trust-dev-cert command.Tried with Node 8.11.4 as mentioned.
Even i tried .gcb-serve-data folder but still i get the same error.
