### ISSUE TITLE
Person column example does not work.

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-docs#1038]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior

In the *Display field values (basic)* section, the example to display a person column using the `"@currentField.Title"` format does not work.

#### Observed Behavior
Using the *Modified By* (Editor) column with `"debugMode": true`, this message displays in the column:
*Failure: Editor.Title was not found on the data object.*

#### Steps to Reproduce
See above.

**Comment by patrickabel** [comment]
@sympmarc this looks to be a casing issue. 

- "@currentField.title" : **works**
- "@currentField.Title" **does not work**

**Comment by mcmynn83** [comment]
I've closed this assuming that the article you were mentioning is the following article with the correct casing:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting

Thanks for the feedback!
