### ISSUE TITLE
Allow disabling of tslint gulp subtask

### ISSUE THREAD

**Issue by bpkennedy** [SharePoint/sp-dev-docs#1039]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
I expect to not have to use typescript in my build chain if I choose not to (for instance to use es2015 with webpack).  This was stated as being supported (even if Microsoft will not enhance towards using it)

#### Observed Behavior
`tslint` gulp subtask is being run from build.rig by default.  I found documentation on how to create a custom gulp task, but not how to turn off/overwrite an existing subtask.  How can I do this? 

#### Steps to Reproduce
Change back a generated web part project, No Javascript framework, to not be using typescript.  `gulp serve` will work correctly and it builds to the `/dist` folder correctly.  However, once you delete files like these, you see this error when trying to `gulp serve` (when `tslint` is run):
* tslint.json
* tslint-tsconfig.json
* tsconfig.json
* typings folder

**Comment by nickpape-msft** [comment]
If you would like to disable the tslint task, you should be able to just add:

```javascript
build.tslint.enabled = false;
```

to your gulpfile.js before the `build.initialize(gulp)` line.

**Comment by nickpape-msft** [comment]
We're working on improving the API surface around the tooling.

**Comment by bpkennedy** [comment]
Thank you!

**Comment by hafeez1042** [comment]
getting error 
```TypeError: Cannot set property 'enabled' of undefined```
SPFX v1.8.0

**Comment by LuisEnMarroquin** [comment]
Getting the same error

```shell
TypeError: Cannot set property 'enabled' of undefined
```

SPFX v1.9.1

**Comment by gbminnock** [comment]
@hafeez1042 @LuisEnMarroquin 
this worked for me in SPFX v 1.9.1

```
build.tslintCmd.enabled = false;
```
