### ISSUE TITLE
Documentation for webpackConfig outdated

### ISSUE THREAD

**Issue by bpkennedy** [SharePoint/sp-dev-docs#1040]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
Following webpackConfig docs should work correctly.

#### Observed Behavior
Adding this code shows that generatedConfiguration.module is undefined.

```
build.configureWebpack.mergeConfig({ 
  additionalConfiguration: (generatedConfiguration) => { 
    generatedConfiguration.module.loaders.push([ 
      { test: /\.md$/, loader: "html!markdown" } 
    ]); 

    return generatedConfiguration; 
  } 
});
```

Error when running `gulp test` is:
```
[22:45:34] Error - [configure-webpack] TypeError: Cannot read property 'push' of undefined
[22:45:34] Error - 'configure-webpack' sub task errored after 588 ms
 Cannot read property 'push' of undefined
[22:45:34] 'test' errored after 4.35 s
```

#### Steps to Reproduce
Update your gulpfile.js to use mergeConfig as described in the docs in a newly generated webpart spfx project.

**Comment by Rainson12** [comment]
im facing the same issue, is there a workaround?

**Comment by d-martins** [comment]
Looks like the structure of the `module `object has changed from what's in the docs.
The code should read like this now. 

```javascript
build.configureWebpack.mergeConfig({ 
    additionalConfiguration: (generatedConfiguration) => { 
      generatedConfiguration.module.rules.push({
          use:[{loader:"html!markdown"}],
          test:/\.md$/
      }); 

      return generatedConfiguration; 
    } 
});
```

**Comment by nickpape-msft** [comment]
Closing this issue for now as @d-martins fix should be correct.
