### ISSUE TITLE
some very basic 'best way' generic patterns for very simple actions would help newbies

### ISSUE THREAD

**Issue by kath561** [SharePoint/sp-dev-docs#1041]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

solutions are great but a few definitive, 1 only of each, 'best practice' patterns for
   a few generic operations that were labelled as such  in github would remove confusion between
   solutions where different authors have their own pet approach to the same operation or
   the practice changes over time but old solutions still exist. 
   Could  the guru's agree on a current 'best practice' (evolving) 
          for some few basic common atomic sharepoint snippets for content output.
          This would
          really really help newbies onboarding to the framework and make it easier to
          see when the 'best' approach changes and to stay aligned with the leading edge.

eg.  

- async fetch list items into an object array
-      async read taxonomy group for key and return members as object array
-      fetch current user profile into an object from graph
-      fetch current users role and group membership
-      restrict action based on users role
-      fetch current users recent documents from graph
-      fetch a tenant property
-      issue a search request and get results back into a renderable object
-      fetch any persons info-card using email address as a key
-      fetch a documents dynamic preview image 
     
     
make it competitive and give a "SNIP of the month" , "Best of Breed" in the SIG, for better refinements on the best way to do simple atomic building block operations. focus tightly in on a very few actions and apply the best thinking to them. that would educate us all.
The biggest problem as a community consumer is working out which way is the best way to do very simple actions when there are so many possible approaches. The solutions give a great wide-angle view of putting it all together but we need the tight focus zoom-in close-up as well for very common ops to raise the game level of all of us.

**Comment by dgaeta** [comment]
@kath561 Thanks for the feedback! Can you please request this on [SharePoint UserVoice](http://sharepoint.uservoice.com/), thanks!
