### ISSUE TITLE
Set Site Collection readonly using CSOM 

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#1043]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Ist there a way to set a site collection readonly in Office 365 using the SharePoint Client API as we know it from from Server API?

In the past we could just do:

```
public void SetReadOnlyState(string siteCollectionUrl, bool readOnly)
        {
            using (SPSite site = new SPSite(siteCollectionUrl))
            {
                site.ReadOnly = !readOnly;
            }
        }
```

This is not possible in CSOM. Furthermore Office 365 does not have a possibility to set a site collection read only at all. On premise we can use:

`Set-SPSite -Identity "<SiteCollection>" -LockState "<State>"
`
and set it to **Unlock, NoAdditions, ReadOnly and NoAccess**.

Office 365 only support **NoAccess** as LockState parameter. Afterwards the page can not be opened anymore (401). Therefore is not a feasible option.

Site Collection administrators can still use the interface to set a site collection readonly by activating [site policies](https://support.office.com/en-us/article/Use-policies-for-site-closure-and-deletion-a8280d82-27fd-48c5-9adf-8a5431208ba5). This method can not be used in csom because it is not possible to create site policies programmatically (https://social.msdn.microsoft.com/Forums/office/en-US/4ce27e31-9fab-459c-acb1-f2320bbbdc24/site-policy-creation-for-making-office-365-sites-read-only?forum=sharepointdevelopment).

So is there currently no possiblity to set a site to read only programmatically in O365?

**Comment by OliverZeiser** [comment]
You can define a sitepolicy on the contenttype hub. That way you only need to activate the policy on any other site, which is possible via csom

**Comment by MrTantum** [comment]
Oh thanks for this info. I didn't know you can publish site policies in the hub.

This is an improvement but you still need one manual step for this. Therefore this is not a solution for a multi-tenant solution.

**Comment by dgaeta** [comment]
@MrTantum Are you able to use the [REST Endpoint](https://msdn.microsoft.com/en-us/library/jj244899.aspx)?
