### ISSUE TITLE
Can not get two level lookup data

### ISSUE THREAD

**Issue by babkenmes** [SharePoint/sp-dev-docs#1049]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [x] Additional article idea

#### Expected or Desired Behavior

If we have a lookup on a source list which also has a lookup field, somehow we should be able to retrieve data of the second level lookup.

#### Steps to Reproduce
Suppose we have 3 lists named "AList", "BdList", "CList".
 "AList" has a lookup field named "ALookupField" which targets to "BList".
And "BList" has a lookup field named "BLookupField" which targets to "CList".

So we can get the respective BdList  data of Alist items but we can never get CList data.

> http://server/site/_api/web/lists/getByTitle('AList')/items?$select=Title,ALookupField/Name&amp;$expand=ALookupField/Name

The thing is that we can not even select the Id field so if we do another call and fetch all the CList items we could map them to corresponding data.

**Comment by chackman** [comment]
Unfortunately, queries that expand nested lookups (in your case, from AList to CList via BList) are not supported.

**Comment by babkenmes** [comment]
Yes it is obvious, but why we can not select the id field? This limitation makes a lot of situations, which are common and simple, just impossible to implement.
