### ISSUE TITLE
 Cannot find module '@microsoft/sp-build-web'

### ISSUE THREAD

**Issue by Rick-Kirkham** [SharePoint/sp-dev-docs#105]
When I try to preview either in the command prompt or in Visual Studio Code, I get this error: 
 Cannot find module '@microsoft/sp-build-web'

Rerunning >yo @microsoft/sharepoint does not help. And it does not error.

**Comment by waldekmastykarz** [comment]
Have you tried rerunning `npm i`? I had the same issue when couldn't install Phantom due to an error on their server.

**Comment by chakkaradeep** [comment]
You can also just run:

```
npm i @microsoft/sp-build-web --save-dev
```

**Comment by Rick-Kirkham** [comment]
In the end, I deleted everything and then reran yo @microsoft/sharepoint. It worked the second time around.
