### ISSUE TITLE
SPFX Extension - Subsite link override - Modern Experience 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#1050]
#### Category
- [ ] Question
 
In classic experience, we are redirecting the users to a provider hosted site request form instead of out of the box site request page(/_layouts/15/newsbweb.aspx) using custom action. We are trying to create a SPFX Application Customizer to replace this functionality by getting the Subsite button element by name and attaching a click event which will redirect the users to the provider hosted site request form. But the logic is not 100% working as there is delay in rendering the dropdown values on new button click.

What is the right way to execute the code within the onInit method after the complete page load so that we can access the commandbar with class name CommandBarItem-link?

**Comment by sprider** [comment]
@PaoloPia @waldekmastykarz - Any suggestions?

**Comment by waldekmastykarz** [comment]
I don't think there is. The whole idea behind SPFx is that we don't do DOM manipulation because it's unreliable. I'd suggest you submit a UserVoice entry (assuming there isn't one already) that clearly describes your use case.

**Comment by sprider** [comment]
Thank you @waldekmastykarz 

Done - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/32539840-sharepoint-framework-extension
