### ISSUE TITLE
All Property Pane Dropdown options are not visible and dropdown pane is not scrollable

### ISSUE THREAD

**Issue by Zytegeist** [SharePoint/sp-dev-docs#1052]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I was expecting that property pane dropdowns with many options would be scrollable to allow all options to show. I believe that this was the previous behavior I encountered in earlier versions of SharePoint Framework. I would also have expected to add a max height set and set scrollable y-axis overflow via css on the containing class of ms-Dropdown-callout in order to resolve this issue, but setting the css even as important does not change the dropdown layout or fix the issue.

#### Observed Behavior
Dropdown is expanding beyond the window layout and making it so that all options in the dropdown are not visible to users. Dropdown has a negative top value so that last dropdown option is visible at the bottom of the screen, but first / top options are not visible as they go up above the screen. Dropdowns with only a few options exhibit the expected dropdown behavior with no issues - only occurs when there are numerous option.

#### Steps to Reproduce
1. Open a SharePoint Framework webpart. 
2. Create a PropertyPaneDropdown field in getPropertyPaneConfiguration() and populate with an IPropertyPaneDropdownOption[] of length fifty (populated by adding array to options field of PropertyPaneDropdown). 
3. Run gulp serve, add webpart, and edit webpart.
4. Configure webpart and click on dropdown - list will expand above the screen and not be scrollable and all options will not be visible.

#### Submission Guidelines
Not sure if this is relevant, but I first noticed this error using the @microsoft/sp 1.3.2 modules, but have since upgraded to 1.3.4 and still see this issue. My package is completely up to date now verified with npm outdated. I'm currently using npm 3.10.10, but I've also tried npm 4@latest and still have the same issue. Attached picture (There are many more lists beyond top visible list of Construction Documents).
![sharepointframeworkissue](https://user-images.githubusercontent.com/4949654/32811233-77276762-c953-11e7-83ca-b3fe165c69fb.png)

**Comment by micahgodbolt** [comment]
I don't believe this is necessarily a Fabric bug. The dropdown is more than capable of displaying 50+ entries. I'm guessing there has been other CSS applied to this dropdown that is causing the problem? 

https://codepen.io/micahgodbolt/pen/BJaYZg

**Comment by mcmynn83** [comment]
@Zytegeist - Thank you for your feedback.  I have gone to try and reproduce this issue with a brand new vanilla project and it does not reproduce.  I added the following code to getPropertyPaneConfiguration():
protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                }),
                PropertyPaneDropdown('test2', {
                  label: 'Dropdown',
                  options: [
                    { key: '1', text: 'One'},
                    { key: '2', text: 'Two' },
                    { key: '3', text: 'Three' },
                    { key: '4', text: 'Four'},
                    { key: '5', text: 'Five' },
                    { key: '6', text: 'Six' },
                    { key: '7', text: 'Seven' },
                    { key: '8', text: 'Eight' },
                    { key: '9', text: 'Nine' },
                    { key: '10', text: 'Ten' },
                    { key: '11', text: '1One'},
                    { key: '12', text: '1Two' },
                    { key: '13', text: '1Three' },
                    { key: '14', text: '1Four'},
                    { key: '15', text: '1Five' },
                    { key: '16', text: '1Six' },
                    { key: '17', text: '1Seven' },
                    { key: '18', text: '1Eight' },
                    { key: '19', text: '1Nine' },
                    { key: '20', text: '2Ten' },
                    { key: '21', text: '2One'},
                    { key: '22', text: '2Two' },
                    { key: '23', text: '2Three' },
                    { key: '24', text: '2Four'},
                    { key: '25', text: '2Five' },
                    { key: '26', text: '2Six' },
                    { key: '27', text: '2Seven' },
                    { key: '28', text: '2Eight' },
                    { key: '29', text: '2Nine' },
                    { key: '30', text: '3Ten' },
                    { key: '31', text: '3One'},
                    { key: '32', text: '3Two' },
                    { key: '33', text: '3Three' },
                    { key: '34', text: '3Four'},
                    { key: '35', text: '3Five' },
                    { key: '36', text: '3Six' },
                    { key: '37', text: '3Seven' },
                    { key: '38', text: '3Eight' },
                    { key: '39', text: '3Nine' },
                    { key: '40', text: '4Ten' },
                    { key: '41', text: '4One'},
                    { key: '42', text: '4Two' },
                    { key: '43', text: '4Three' },
                    { key: '44', text: '4Four'},
                    { key: '45', text: '4Five' },
                    { key: '46', text: '4Six' },
                    { key: '47', text: '4Seven' },
                    { key: '48', text: '4Eight' },
                    { key: '49', text: '4Nine' },
                    { key: '50', text: '5Ten' },
                  ],
                  selectedKey: '4',
              })
              ]
            }
          ]
        }
      ]
    };
  }
}  

I then see the following experience:
![image](https://user-images.githubusercontent.com/16929083/33913562-2c1fd27e-df4f-11e7-87b9-ba50c0d32d5e.png)

The scroll bar exists.  Are you doing something else?  If you use the code sample above do you exhibit the same buggy behavior?

Thanks,
Graham

**Comment by Zytegeist** [comment]
Hi Graham,

I'm no longer seeing the issue after I upgraded to 1.40. The only issue I
see now is that when I move my mouse the list and cursor jump up to the top
of the dropdown. This only happens in IE (Using IE11), and I've verified
that this still occurs with a new scaffolded project. I realize that I
didn't mention that the previous error on 1.30 was only seen when using the
Chrome/Firefox browser and not IE. Since the original issue is resolved
please feel free to close/resolve the ticket. The current issue is a little
annoying, but not a showstopper for us.

Thanks,

J. Dave Zoland

**Comment by mcmynn83** [comment]
Thanks for your feedback.  If you would like the other issue to be investigate please open a new thread.  If you are fine with that experience, you don't have to do anything.
