### ISSUE TITLE
SP 2016 : react web part working in hosted workbench not in web part page

### ISSUE THREAD

**Issue by vivsunny10** [SharePoint/sp-dev-docs#1062]
Category :- Bug

I created a new client web part using react in SP 2016 and is working fine in hosted workbench (_layouts/15/workbench.aspx). My web part is making a web-api call using fetch method after user clicks on a button  and displaying results on the page.

Issue is that same web part after adding on a web part page is not working. Page refreshes after clicking on the button, it seems to be failing on the fetch() method. Any idea?

**Comment by vivsunny10** [comment]
It seems to be an issue with classic SharePoint page. There is already an issue which closed by the group few months back :- 
https://github.com/SharePoint/sp-dev-docs/issues/492

It worked for me after pasting following code at end of render method in react web part:-

 const buttons = this.domElement.getElementsByTagName('button');
    if (buttons && buttons.length) {
      for (let i: number = 0; i < buttons.length; i++) {
        if (buttons[i]) {
          /* tslint:disable */
          // Disable the button onclick postback
          buttons[i].onclick = function () { return false; };
          /* tslint:enable */
        }
      }
  //  }
    }

**Comment by manishgarg1** [comment]
Hi @vivsunny10, though not an elegant solution, good to know that you have a work around. In future we may ship an API that will not need you to write that code. For now, I am just resolving this issue.
