### ISSUE TITLE
Online Workbench doesn't reflect theme colours of parent web properly

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1064]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When workbench will be opened online I expect to see the same colours as used on the parent web. 

#### Observed Behavior
When I applied a theme to a web site, open the workbench under this web not all colours will be reflected properly. For example the background of the workbench doesn't change.

#### Steps to Reproduce
The following screenshot was take from a communication site where the theme is set to "Dark Yellow".

<img width="1600" alt="screen shot 2017-11-20 at 20 50 10" src="https://user-images.githubusercontent.com/5503835/33038963-acc5adba-ce36-11e7-9ca6-4637f24d3138.png">

The color chosen from theme picker:

<img width="342" alt="screen shot 2017-11-20 at 20 50 39" src="https://user-images.githubusercontent.com/5503835/33038984-c0c8cd56-ce36-11e7-8f0e-baea2eae3724.png">

When I now open the workbench beneath this web it looks as seen on the following screen shot.
<img width="1600" alt="screen shot 2017-11-20 at 20 58 03" src="https://user-images.githubusercontent.com/5503835/33039035-e9f1a374-ce36-11e7-882f-c9c3e59bd9c1.png">

I think this is currently an issue of the workbench. Would be great if these matches the same colours as parent.

**Comment by mcmynn83** [comment]
@StfBauer -This is a new feature request to make the workbench themeable.  It is not currently themeable as it is just a test area for SPFX webparts.  The best place to make a feature request is uservoice.

**Comment by StfBauer** [comment]
@mcmynn83 The information you provided are sadly not correct because the support for theming in the workbench is already there.
 
This issue doesn't even relate to the local workbench. I haven't raised an issue for the local one. It relates to the one available on Office 365. The problem and bug it has is also not a big one as I can tell.

The only issue I've found so far is that the correct background color won't get applied properly. I might haven't specified this explicitly in the issue but I expected that someone looks over this issue anyway properly. That might was my fault.

Based on the default provisioned web part in any new SPFX project the theme token the following result was recored to give you a better overview of this already existing feature.

To test the following behaviours the following needs to be done:
1. Open any modern experience web site
2. Open workbench under the same web
3. Change theme on parent web site
4. Reload workbench on other tab

This should end up in the following results:

**SharePoint Theme - Blue**
<img width="888" alt="screen shot 2017-12-05 at 20 01 08" src="https://user-images.githubusercontent.com/5503835/33625318-793f12f2-d9f7-11e7-8d82-91707ecb5e73.png">

**SharePoint Theme - Orange**
<img width="903" alt="screen shot 2017-12-05 at 20 02 47" src="https://user-images.githubusercontent.com/5503835/33625312-75657c02-d9f7-11e7-8f72-45ca1f91f72c.png">

**SharePoint Theme - Red**
<img width="909" alt="screen shot 2017-12-05 at 20 05 03" src="https://user-images.githubusercontent.com/5503835/33625389-af38bc3c-d9f7-11e7-8555-f4084c6a9719.png">

**SharePoint Theme - Purple**
<img width="912" alt="screen shot 2017-12-05 at 20 06 23" src="https://user-images.githubusercontent.com/5503835/33625421-cdfc58ae-d9f7-11e7-886f-7dbf47f1379b.png">

**SharePoint Theme - Green**
<img width="903" alt="screen shot 2017-12-05 at 20 07 28" src="https://user-images.githubusercontent.com/5503835/33625462-f47cb852-d9f7-11e7-8c60-68749179b558.png">

**SharePoint Theme - Gray**
<img width="893" alt="screen shot 2017-12-05 at 20 08 20" src="https://user-images.githubusercontent.com/5503835/33625490-116fb626-d9f8-11e7-8d2b-c31f46645e41.png">

**SharePoint Theme - Dark Yellow**
<img width="1920" alt="screen shot 2017-12-05 at 20 09 08" src="https://user-images.githubusercontent.com/5503835/33625535-3105bcba-d9f8-11e7-86db-d1dc0926a587.png">

* Background Color not gets applied
* Workbench Suite Bar gets correct colors
* Web part gets correct colors
* Web part zone menu gets correct colors

**SharePoint Theme - Dark Yellow**
<img width="1855" alt="screen shot 2017-12-05 at 20 11 28" src="https://user-images.githubusercontent.com/5503835/33625662-9362a08a-d9f8-11e7-9401-0147b1023e6c.png">

* Background Color not gets applied
* Workbench Suite Bar gets correct colors
* Web part gets correct colors
* Web part zone menu gets correct colors

What do you think? I guess this issue should re-opened as an bug and not go to the user voices as you recommended.
It might be a side effect but the bug is really marginal an should be easy to fix.
