### ISSUE TITLE
SharePoint 2016 - App Catalog Client_Component_Is_Client_SideSolution_Deployed isn't resolved.

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/sp-dev-docs#1074]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

![resourcenotresolved](https://user-images.githubusercontent.com/18352488/33133047-6b6ef9a8-cf93-11e7-96c6-0c6037f8060a.PNG)

#### Expected or Desired Behavior
Plain text rather than resource string

#### Observed Behavior

"$Resources:Client_Component_Is_Client_SideSolution_Deployed" appears in the app catalog.

#### Steps to Reproduce
N/A

**Comment by VesaJuvonen** [comment]
Hi @Pieter-Veenstra - that seems to be an issue in the patching of the farm. Has the farm being patched fully and there's no pending reboots or pending updates? What version are you specifically using (CU?)? Was that version upgraded directly from which version? Typically these kind of issues are caused by failures in upgrades or that only some servers in the farm have been successfully patched.

**Comment by Pieter-Veenstra** [comment]
I've got SharePoint 2016 (build number: 16.0.4615.1000)

There are no outstanding updates.

**Comment by VesaJuvonen** [comment]
@Pieter-Veenstra, can you check if the label is in the core.resx file located in c:\program files\common files\microsoft shared\web server extensions\.... \tempate 1033 folder. Just to see if the label exists in the server. Your UI would be indicating that it's not there due for example upgrade failures.

**Comment by Pieter-Veenstra** [comment]
Hi @VesaJuvonen ,

The only core.resx file within Web Server Extensions can be found in:
C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\Resources

The installation completed without any errors. It isn't too critical, but I've now see this in 3 separate farms that were all installed recently. This isn't too important. 

Looking at your responses, I'm assuming that you are not seeing this issue in your farms. My main reason to report this was to check that there is a general problem or not.

**Comment by getalex** [comment]
Just noticed I have this problem as well; does not seem to affect functionality. No errors in upgrades, applied latest December 2017 CU without trouble - resource for both Client_Component_Is_Client_SideSolution_Deployed AND Client_Component_Deploy_Ribbon_Button_Title are both missing from the UI, although they are present int he core.resx file.

**Comment by getalex** [comment]
Just FYI - it looks like all Client_Component* resources are missing, reading from localized core resource where they don't exist (had to copy from core.resx to core.en-US.resx for example).

<data name="Client_Component_Solution_Name">
    <value>Solution Name</value>
  </data>
  <data name="Client_Component_Solution_Id">
    <value>Solution Id</value>
  </data>
  <data name="Client_Component_Solution_Version">
    <value>Solution Version</value>
  </data>
  <data name="Client_Component_Feature_Name">
    <value>Feature Name</value>
  </data>
  <data name="Client_Component_Feature_Description">
    <value>Feature Description</value>
  </data>
  <data name="Client_Component_Feature_Id">
    <value>Feature Id</value>
  </data>
  <data name="Client_Component_Feature_Scope">
    <value>Feature Scope</value>
  </data>
  <data name="Client_Component_Component_Name">
    <value>Component Name</value>
  </data>
  <data name="Client_Component_Component_Type">
    <value>Component Type</value>
  </data>
  <data name="Client_Component_Client_Component_Id">
    <value>Component Id</value>
  </data>
  <data name="Client_Component_Component_Manifest">
    <value>Component Manifest</value>
  </data>
  <data name="Client_Component_Disabled">
    <value>Disabled</value>
  </data>
  <data name="Client_Component_Available_Site">
    <value>Available Site</value>
  </data>
  <data name="Client_Component_Template_Display_Name">
    <value>Component Manifest List Template</value>
  </data>
  <data name="Client_Component_Template_Description">
    <value>A list to store client component manifests</value>
  </data>
  <data name="Client_Component_Instance_Title">
    <value>Client Side Component Manifests</value>
  </data>
  <data name="Client_Component_Instance_Description">
    <value>A list to store client component manifests</value>
  </data>
  <data name="Client_Component_Content_Type_Title">
    <value>Client Side Component Manifest</value>
  </data>
  <data name="Client_Component_Content_Type_Description">
    <value>Content type for a Component Manifest</value>
  </data>
  <data name="Client_Component_All_Content_View">
    <value>All Component Manifests</value>
  </data>
  <data name="Client_Component_Is_Client_Side_Solution">
    <value>Client Side Solution</value>
  </data>
  <data name="Client_Component_Deploy_Ribbon_Button_Title">
    <value>Deploy</value>
  </data>
  <data name="Client_Component_Deploy_Ribbon_Button_Hover_Text">
    <value>Deploy the selected client-side solution to all sites.</value>
  </data>
  <data name="Client_Component_Is_Client_Side_Solution_Deployed">
    <value>Deployed</value>
  </data>

**Comment by frankchen76** [comment]
Not sure if you guys figured out the reasons. In my case, I found out the column showed correctly after I installed "SharePoint Server 2016 MUI/language patch". I forgot to install language CU after installing "SharePoint Server 2016" CU. 
Another problem I also had was that the SPFx web part wasn't able to find out from the site collection which I want to use the web part. After I install language CU and recreate the app catalog site collection, the web part was able to find out. 
I hope it helps.

**Comment by metinsevindik** [comment]
I take same error

**Comment by VesaJuvonen** [comment]
This was caused by a missing RESX file in some CUs, but it should be all sorted out now. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
