### ISSUE TITLE
How can I tell what is the latest stable version of packages in SPFx?

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#1075]
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

Hi, I read this great article and many like it explaining how to update my packages:
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/update-latest-packages.md

They all discuss technically how to update NPM packages, which is widely-shared knowledge already.

What I was looking for and couldn't find is a page that can tell me what is the current stable version number for each of the Microsoft versions I *should* use.

I mean, should I always get the latest? How often should I update? Are beta/pre-release features included in the latest builds? If so, how can I get the latest stable version without any beta features?

Please point me to that info if exists and I missed it, or perhaps consider adding this info to the documentation on how to update.

Thanks!

**Comment by VesaJuvonen** [comment]
Basically assumption is that you should always be able to use the latest version of the SPFx packages... currently being 1.3.4 and soon 1.4. These packages do also contain some preview capabilities, which is specifically called out in the communications... for example Graph Client is still in preview status. Update sequence really depends on what you are doing. If you are targeting on both on-premises and cloud, then you'd still be using 1.1 version... also, in general, you can keep on using older versions and they should be working without any issues also in future... if that's not the case, it's a bug on SP engineering side. 

We also updated following article to more specifically call this out - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages.  Other feedback also more than welcome. Will close up this after a while, unless there's other specifics around this topic.

**Comment by shaipetel** [comment]
Thanks @VesaJuvonen - thats exactly my point!
"If you are targeting on both on-premises and cloud, then you'd still be using 1.1 version"

How would a developer know that, for example? Is there a central place where I can see all versions and all these extra information about them? Like, what works in on-premise, what is preview, etc...

my point was that looking at version release updates for each version and trying to dig that information out is very hard, and many builds of the SPFx packages are not specifically called out in these communications. So, if I am following it day in day out for a while, I just know.
If I took 2 weeks off, or worked on a different project for a month or two I am "out of sync" and won't have a clue what these versions are and which version should I use.

So, the ask is simple: for a list of releases and whats new in each version per package in one location.
Alternatively, just include the highlights:
Package   -   On premise version  -  online version  -  pre-release APIs
Package A - 1.1.0 - 1.4.0 - Graph API, Field Customizers, etc... list of beta apis
...
...

like I said, unless this information exists somewhere that I didn't see... because going to each and every release notes is very hard.

**Comment by VesaJuvonen** [comment]
Hi @shaipetel - on how would dev's know about this question: We do document these dependencies and when we push out updates, we do share new documents cross our blog posts and social media channels. Version 1.1 dependency is explicitly called out in the SP2016 support statement at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support, but obviously, it might be hard to find all the documentation out there.

We have been talking about the requirement of doing a much better job around the version-by-version documentation, so feedback is absolutely understandable and appreciated. We are looking into addressing this messaging challenge with the upcoming releases.

**Comment by shaipetel** [comment]
Yeah I know it’s mentioned when you publish a version. But unless I was keeping up to date in real time it would be very difficult to gather this information from many different sources, articles, blog posts, wiki pages, check in comments - unless you live and breath it - it’s very hard to keep up. 

Many vendors opt to a simple sing page with version list that highlights the changes in a single page with links to read more. 

Thanks for considering.

**Comment by VesaJuvonen** [comment]
thx Shai for the input on the process improvements. We are looking into improving this process during the spring based on your input. Closing this issue as the actionable items and topics have been closed.
