### ISSUE TITLE
Module not found: Error: Can't resolve '@ms/sp-telemetry' when using SPHttpClient or GraphHttpClient

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#1076]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using SPHttpClient or GraphHttpClient, I expect `gulp bundle` to succeed.

#### Observed Behavior
When adding the following example code, the bundle task fails with the error below:
`new SPHttpClient(this.context.serviceScope).fetch("<url>", SPHttpClient.configurations.v1, {});`

```
Error - [webpack] 'dist':
./node_modules/@microsoft/sp-http/lib/spHttpClient/SPHttpClient.js
Module not found: Error: Can't resolve '@ms/sp-telemetry' in 'C:/Projects/_Testing/spfx-test-solution/node_modules/@microsoft/sp-http/lib/spHttpClient'
resolve '@ms/sp-telemetry' in 'C:/Projects/_Testing/spfx-test-solution/node_modules/@microsoft/sp-http/lib/spHttpClient'
```
I tried (re-)installing the latest version of the generator (1.3.4), but this didn't help.

Also, calling `GraphHttpClient` instead of `SPHttpClient` gave me some more errors coming from `@ms` modules.

#### Steps to Reproduce
- (Install SPFx generator `npm i -g @microsoft/generator-sharepoint`)
- Create a new SPFx project `yo @microsoft/sharepoint`
- Follow the wizard to create a new **webpart** (tested with both React and "no framework" - both gave the same result)
- Add a call to SPHttpClient or GraphHttpClient to the code: `new SPHttpClient(this.context.serviceScope).fetch("<url>", SPHttpClient.configurations.v1, {});`
- Run `gulp bundle`

**Comment by ab14jain** [comment]
Even i got the same error.

The correct usage is
import { SPHttpClient } from '@microsoft/sp-http';

this.context.spHttpClient.get('/_api/web', SPHttpClient.configurations.v1);
