### ISSUE TITLE
After change regional settings, pages with SPFx webparts gives unexpected error has occurred. 

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#1083]
_From @geogikk92 on November 17, 2017 7:29_

- [ ] Question
- [x] Bug
- [ ] Enhancement

After change regional settings in SharePoint 2016 On-Premise server to Bulgarian, Macedonian оr other Locale
![untitled](https://user-images.githubusercontent.com/14110861/32935570-6d0c397e-cb79-11e7-9359-305cc80f2610.png)

**I have following error:**
![untitled](https://user-images.githubusercontent.com/14110861/32935634-a60ea040-cb79-11e7-9d9e-194876a3a4c9.png)

**Error from log file is:**

> Message  : System.FormatException: String was not recognized as a valid DateTime.    at
>            System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetUpdateTimeFromAppCatalog(SPWebweb)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetDistributedUpdateTime(Guid tenantId, SPWeb web)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.EnsureCacheIsValid(SPWeb web, Guid tenantId)     at Microsoft.SharePoint.ClientSideComponent.SPClientSideCachedThirdPartyComponentProvider.GetNotFoundComponents(SPClientSideComponentQueryResultCollection requests, SPWeb web)     at Microsoft.SharePoint.ClientSideCom...
> 

Thanks for your contribution! Sharing is caring.

_Copied from original issue: SharePoint/sp-dev-fx-webparts#367_

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on November 20, 2017 11:33_

Did you customize the list's Add form and put a SharePoint Framework client-side web part on it?

**Comment by VesaJuvonen** [comment]
_From @geogikk92 on November 20, 2017 11:47_

Yes! I replace my default add listItem form with customized  SharePoint Framework client-side web part.

![asdf](https://user-images.githubusercontent.com/14110861/33016905-f0de9798-cdf8-11e7-9016-86f3581bd3fc.png)

My WebPart working with Locale(English(USA)), but others locale(Bulgarian, Macedonia and other) doesnt working, give above error in stacktrace.

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on November 20, 2017 11:57_

@VesaJuvonen do you have more information about if SPFx web parts are not meant to be used on list form pages and the behavior is by design or if this is a potential bug in SPFx that needs further investigation?

**Comment by VesaJuvonen** [comment]
_From @geogikk92 on November 20, 2017 12:5_

I have SPFx web parts In site classic pages and error is the same.

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on November 20, 2017 12:9_

Which version of the SharePoint Framework Yeoman generator did you use to scaffold the project?

**Comment by VesaJuvonen** [comment]
_From @geogikk92 on November 20, 2017 12:15_

The version of the SharePoint Framework Yeoman is:

![untitled](https://user-images.githubusercontent.com/14110861/33018005-4447ea70-cdfd-11e7-903d-92eb8e5e84af.png)

**.yo.rc.json** file contains:

> {
>   "@microsoft/generator-sharepoint": {
>     "version": "1.3.4",
>     "libraryName": "lirex-holidays",
>     "libraryId": "c715415a-9890-4a12-b72b-0dc8244f1bb3",
>     "environment": "onprem"
>   }
> }

**Comment by VesaJuvonen** [comment]
_From @darekjpro on November 23, 2017 11:32_

Having the same issue. 
Using the latest version of Yeoman (1.3.4). Solution targeted for SharePoint 2016 onwards. 
SPFx web part added to classic web part page working fine with English-US regional settings. Changing site regional settings to English-UK causes the same error in ULS (_String was not recognized as a valid DateTime._)
Thanks.

**Comment by geogikk92** [comment]
Did you find anything on my question? This is a blocker for my project. Thank you! :)

**Comment by VesaJuvonen** [comment]
This was an issue on the server side which has been now fixed. Since this is, however, on-premises fix, it will be rolled out as part of the on-premises CUs. In this case, it will be most likely either in January CU or in Feb CU.

**Comment by geogikk92** [comment]
Today, after upload my solution in app catalog an issue comes again.

**Comment by VesaJuvonen** [comment]
Hi @geogikk92, like mentioned in the last comment, this is a fix which will be part of the upcoming Cumulative Path for on-premises. To be able to get it fixed, there has to be a server-side fix to your on-premises environment.  This means that the issue will be resolved after the patch (January CU or February CU) is available and installed in your environment.

**Comment by LucasOvejero** [comment]
Hi @VesaJuvonen, some notice from this fix-update?

**Comment by christopher-walker** [comment]
Just been looking for the status on this also:
https://support.microsoft.com/en-us/help/4011642/descriptionofthesecurityupdateforsharepointenterpriseserver2016january
Looks like it was fixed in the January 2018 CU:

> The SharePoint Framework (SPFx) page crashes when the site’s regional setting is changed.

**Comment by andrewconnell** [comment]
Closing as fixed...
