### ISSUE TITLE
Column Formatting doc - Predefined classes 

### ISSUE THREAD

**Issue by aaronmi** [SharePoint/sp-dev-docs#1086]
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
 Predefined classes table is misleading. Predefined class only define background color. It does not include icon. But pictures shown in the table display both background color and icon. All pictures should be modified without icon. Or add a note to explain it clearly.

#### Observed Behavior
Predefined classes table not only show define background color but also icons. Predefined classes do not include icons. 

#### Steps to Reproduce
1) Open https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting
2) Scroll down to "Predefined classes" section. Look the table for predefined classes.

**Comment by thechriskent** [comment]
A note was recently added to the docs indicating that icons are NOT included in the predefined classes. Thanks!
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#style-guidelines
