### ISSUE TITLE
.sppkg support in App Catalog fails if App Catalog created after installing SP2016 FP2

### ISSUE THREAD

**Issue by KoenZomers** [SharePoint/sp-dev-docs#1088]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Installing a new SharePoint 2016 on premises farm, patching it directly with the September or October 2017 CU which includes Feature Pack 2 to add support for the SharePoint Framework sppkg packages to the App Catalog.

#### Observed Behavior
When installing a brand new SharePoint 2016 farm and directly after the installation bits patching it with either the September or October 2017 CU, the App Catalog created after this does NOT have support for .sppkg SharePoint Framework Packages. When patching an existing SharePoint 2016 on premises farm which already had an App Catalog by the time you patch it with the September or October 2017 CU, everything works fine and the support for .sppkg files is added successfully to the App Catalog.

#### Steps to Reproduce
1. Install a new SharePoint 2016 farm on a Windows Server 2016 machine using the normal installation bits
2. After installing the bits, run the September or October 2017 CU bits
3. Run psconfig to finalize the installation and create an App Catalog site collection
4. Drop any .sppkg file in the Apps for SharePoint document library in the App Catalog. It will seem to upload fine, but you won't get the dialog warning you about client side script. Furthermore if you modify the default document library view of the Apps for SharePoint document library in the App Catalog to also show the column "App Package Error Message", you will find out that it reports not knowing about the specifics of the SharePoint Framework in the sppkg file: "There were errors when validating the App manifest.: Xml Validation Exception: 'The 'isClientSideSolution' attribute is not declared.'"

**Comment by mcmynn83** [comment]
This has been fixed and addressed in the March CU.
