### ISSUE TITLE
After 'Sorry, something went wrong with adding the app' AppMonitoringDetails does not give any info

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#1089]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If I add a soloution to a site and the solution fails to deploy,  I get the message "Sorry, something went wrong with adding the app".  In the site contents, I then click the ellipses next to the app that failed and then select DETAILS.  AppMonitoringDetails then shows me  that I have 1 install errors, and the '1' iin the message is a hyperlink  (indicating I can click on it to see that there errors are. When I click on the '1' to show the errors, it should show me the errors.

#### Observed Behavior
 When I click on the '1' to show the errors, it shows a blank page.
#### Steps to Reproduce
This happens when I deploy an spfx Application cusomizer that includes a sharepoint feature (i.e. CAML) to provision a list , and there is something wrong with the CAML.

**Comment by mcmynn83** [comment]
Could you try installing this package again and turn on a network trace.  There is POST to AddAnApp.aspx which should have a 302, could you look at the response header SPRequestGuid and include that in this thread so we can look at what went wrong?  Unfortunately the information we normally need is on that page which you are getting a blank response for.

Thanks,

**Comment by mcmynn83** [comment]
If you are still having this problem please start a new thread and include the requested information so that we can investigate the issue.  I am closing this thread as we have not received a response.
