### ISSUE TITLE
SharePoint site theming: JSON schema colors seem off in last two tables

### ISSUE THREAD

**Issue by Linda-Editor** [SharePoint/sp-dev-docs#1094]
**Doc:** https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema

For all except the last two tables (Dark Blue and Dark Yellow), the colors go from dark to light, but in the last two tables, they go from light to dark. Not sure if this is by design or an error, but it seems funky that the white section is black, for example. 

Please take a look.

**Comment by StfBauer** [comment]
The last two site themes use a black or dark blue background. So the primary colors have to be lighter. The rest of the themes use a white background.

<img width="1920" alt="screen shot 2017-12-06 at 18 17 18" src="https://user-images.githubusercontent.com/5503835/33675122-d1fcbb6e-dab1-11e7-82c8-64a75383dbcd.png">
<img width="1919" alt="screen shot 2017-12-06 at 18 16 57" src="https://user-images.githubusercontent.com/5503835/33675123-d21fe7c4-dab1-11e7-91a9-76e64ea665de.png">

**Comment by dmahugh** [comment]
Thanks, Stefan. Linda, this is a bit confusing because those last two are "inverted" but the terminology for the color slots is the same across all themes. I'll close this issue, but have reached out to the PM team about how we may be able to clarify this going forward.

**Comment by Linda-Editor** [comment]
Thanks for looking into this. :-)
