### ISSUE TITLE
Use of the /_api/SP.Directory.DirectorySession endpoint in SharePoint

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#1095]
#### Category
- [x] Question

I'm working on an SPFx part listing Office 365 Groups, and wanted to provide information to the end-user about the Group if it's tied to Yammer or Teams. Fiddling around I discovered a group site calling `/_api/SP.Directory.DirectorySession` to get data for the Group, including Teams and Yammer endpoint data. This lead me to discover the `beta/groups/<id>/endpoints` call in the MS Graph which I assume you are calling as well.

So, I can get the data I need from the Graph, but having access to these utility calls from an SP context would be extremely useful. I understand the call is internal, but you are aggregating information in a nice way, so as a developer I'd rather piggy pack on your calls instead of rolling my own.

My question I guess is - do you have thought of exposing these internal services in a documented manner, letting 3rd party developers use them as well.

Reference to my research of getting Teams/Yammer info in the beta graph endpoint: http://www.techmikael.com/2017/11/retrieving-teams-and-yammer-endpoints.html

**Comment by wobba** [comment]
There are at least two pieces of useful information in this internal service to be retrieved from having the group id in SP context. One is the SharePoint URL, the other is the Group logo. Except the value returned for the PictureUrl points to outlook.office.com and require that the user has a valid auth cookie against that domain.

Having the site url we can use <site>/SiteAssets/__siteIcon__.jpg but this logo is 96x96, and there are more hi-res ones in the graph itself.

**Comment by lucaband** [comment]
Thanks for your feedback. you can use the beta/groups/<id>/endpoints by using the MSGraphClient we recently released for First Release customers. you can find related documentation here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph.
I'm closing this issue. For any other issue or if the information provided above is not sufficient please open a new issue.

**Comment by wobba** [comment]
@lucaband forgot about this one, and I'm using the graph endpoint. But using /beta in production is, well, not recommended - but I'm doing it :)
