### ISSUE TITLE
After deploying webpart to tenant it started throwing error.

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-docs#1096]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Webpart is should work fine in classic pages

#### Observed Behavior
Earlier was able to deploy the same solution and working fine but now the same solution is throwing below error on the page.

```
[SPWebPartErrorCode.IncorrectBoostrapModule]:
Bootstrap module for web part WebPart.PowerLinksWebPart.g_32239c64_e2c5_46fa_ae64_b9040049f2e0 not of the correct type. Make sure to export your web part as 'export default WebPartName'.

***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:201:20910)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:26738)
    at Function.t.createWithLogProperties (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:27319)
    at e._instantiateWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:44485)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:32598
    at <anonymous>
***LOGPROPERTIES:
{"actualType":"object","wp":{"config":{"_settings":{"keys":[],"values":[]}},"graph":{},"sp":{"_options":{},"_baseUrl":""},"storage":{"_local":null,"_session":null}}}
```

Please help with this ASAP need to deploy this to client live environment.

**Comment by waldekmastykarz** [comment]
Which version of the SharePoint Framework are you using in your solution?

**Comment by craghavendra21** [comment]
Hi below I have pasted my package json details.  have installed the latest version of gulp, yomen generator, and miceosoft sharepoint spfx template
```

{
  "name": "sp-fx-webparts",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.3.0",
    "@microsoft/sp-lodash-subset": "~1.3.0",
    "@microsoft/sp-webpart-base": "~1.3.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "angular": "^1.6.2",
    "jquery": "^3.2.1",
    "moment": "^2.19.1",
    "sp-pnp-js": "^3.0.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.3.0",
    "@microsoft/sp-module-interfaces": "~1.3.0",
    "@microsoft/sp-webpart-workbench": "~1.3.0",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0"
  }
}

```

**Comment by craghavendra21** [comment]
@waldekmastykarz  I have created this solution long back. It was working fine, to the same solution I added few new features and tried to deploy and it's started throwing the error. I had a backup of the old solution. So I went and build the old solution and deployed still throwing the same error. Earlier I was able to build and deploy the same solution and it was working now suddenly not getting why the same solution causing the error.

**Comment by waldekmastykarz** [comment]
If you created the solution long time ago, it could be that it was created using a pre-release version of the SharePoint Framework, which was working in the past, but got removed at some point, after SPFx reached general availability.
I would strongly recommend that you upgrade the solution to any of the supported versions.

**Comment by craghavendra21** [comment]
@waldekmastykarz this is tenant deployed the web part, just now I checked web part by adding it to another site collection and it worked. The issue is happening only in this site collection. Any idea why its like this?

**Comment by waldekmastykarz** [comment]
@craghavendra21 are both sites classic or modern (or is one modern and the other classic)?

**Comment by craghavendra21** [comment]
@waldekmastykarz  both are the classic site. one site all version of SPFx web parts are working another site I tested with old and new spfx web part versions but nothing is working.

**Comment by waldekmastykarz** [comment]
Could it be that there is something else present on the page that's colliding with SPFx/your web part? Have you checked the Developer Console in your browser for any errors?

**Comment by mcmynn83** [comment]
There has been no additional responses to this thread.  If this is still an issue we need more information to help with it.  Please open a new thread with more details about the issue if this is still occurring.

**Comment by craghavendra21** [comment]
@waldekmastykarz I checked the page. except SPFx webpart its not having anything else. Please reopen this issue and resolve.

**Comment by mcmynn83** [comment]
@craghavendra21 - please include a fiddler trace (or the correlation ID from SPRequestGuid in the response headers) as well as a screen shot of the developer console so we can get more info.  Currently we don't have enough information to investigate this issue.

**Comment by craghavendra21** [comment]
Hi I have pasted console window screen shot below

![image](https://user-images.githubusercontent.com/13235051/33922735-c4528ac0-dff2-11e7-8279-36216ce1af68.png)


![image](https://user-images.githubusercontent.com/13235051/33922759-f931f0c8-dff2-11e7-8497-4cbc65feafc0.png)

![image](https://user-images.githubusercontent.com/13235051/33922764-04dce3d8-dff3-11e7-8ad6-35ebf456acda.png)

**Comment by craghavendra21** [comment]
Hi I deleted this page and created page again. and it started working. I guess issue was with the page.
