### ISSUE TITLE
reuse default style for header in webpart

### ISSUE THREAD

**Issue by mdissel** [SharePoint/sp-dev-docs#1097]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When adding the out-of-the-box webparts like the People webpart, you can add a title to the webpart. This title is rendered as:
```
<div class="captionElement__title_9e74f49e captionElement__leftAlign_9e74f49e">
<span>Title</span>
</div>
```

#### Observed Behavior
When you add a Text webpart the default styles of H1/H2/H3 don't match the default header format of the other webparts. 
What css should be used to have the exact same (responsive) styles?

**Comment by waldekmastykarz** [comment]
Could it be that the web part you mentioned uses one of the Office UI Fabric typography styles mentioned at https://developer.microsoft.com/en-us/fabric#/styles/typography?

**Comment by mdissel** [comment]
Every out-of-the-box webpart uses this format. This is an example of the title from the default doc.lib webpart .
```
<div class="title_75e4abc7 titleLgMargin_75e4abc7 captionElement__title_9e74f49e captionElement__leftAlign_9e74f49e">
<span>Documenten</span>
</div>
```

Is there a way to reuse (not redefine) those styles in your own webpart and in the default text webpart?

**Comment by waldekmastykarz** [comment]
Unfortunately not: these styles are scoped to the different web parts and you should not take dependency on any of these classes as they might change in the future.

There are already ideas about building a similar control and make it available as a part of the [PnP SharePoint Framework React Controls](https://github.com/SharePoint/sp-dev-fx-controls-react) solution, which you could then easily use, assuming you're working with React. Stay tuned for updates from PnP when this control will be made available.
