### ISSUE TITLE
Cannot find module ".... \node_modules\@microsoft\npmx\lib\gulp2vs.js"

### ISSUE THREAD

**Issue by foconnor-DS** [SharePoint/sp-dev-docs#11]
Following hello world, using VS 2015 as editor. Opened njsproj just fine ( right click, open with VS chooser, it picked 2015). Followed instructions here: https://github.com/SharePoint/sp-dev-docs/wiki/Working-with-visual-studio

Hit F5, and get error in title. The file is definitely not in my node_modules.

**Comment by chakkaradeep** [comment]
Yes, this is a known issue we discovered at the last moment. Instead of using the included .njsproj file, import the project as described in the Working with VS doc. That way, you bypass the npmx error.

**Comment by pgonzal** [comment]
FYI we have publicly released @microsoft/npmx, and in the next framework update the Yeoman template will refer to it like this:

```xml
    <Exec Command="CMD.EXE /c node $(MSBuildThisFileDirectory)\node_modules\@microsoft\npmx-lib\lib\gulp2vs.js" />
```

If you want to use this feature, you will need to manually run "npm install @microsoft/npmx-lib".
