### ISSUE TITLE
Duplicate of issue #985: deployed web part says "Manifest not found", after updating from 1.1.0 to 1.3.4

### ISSUE THREAD

**Issue by lhoff** [SharePoint/sp-dev-docs#1100]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Web part which loads and runs fine under spfx 1.1.0 should continue to do so under 1.3.4.

#### Observed Behavior
A web part that loaded fine under 1.1.0 does not load under 1.3.4.

#### Steps to Reproduce
In a web part project, using v1.1.0 of the sp-* libraries, the following steps produce a successful installation, load and run of the clientside web part:
`gulp clean`
`gulp build --ship`
`gulp bundle --ship`
`gulp package-solution --ship`

* Deploy contents of temp/deploy to the designated CDN.
* Upload new .sppkg to the App Catalog. [SP 2016 on-prem]
* Refresh the page that uses the web part

After updating all of the sp-* packages to 1.3.4 and repeating the above steps, the final step produces this error message:
> ***ERROR MESSAGE:
> ***Failed to load component "c59ddb5a-5dab-4893-9416-8a92f5d8c290" (PerfectlyFineWebPart).
> Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.3.4".

> ***CALLSTACK:
> Error: ***Failed to load component "c59ddb5a-5dab-4893-9416-8a92f5d8c290" (PerfectlyFineWebPart).
> Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.3.4".
>     at http://contoso.com/_layouts/15/next/spfx/sp-classic-page-assembly_en-us.js?version=1:507:105711
    at <anonymous>

Searching the project for the 7263c7d0-1d6a-45ec-8d85-d4d1d234171b GUID reveals it in several generated files as being associated with SPCoreLibrary:

#### excerpt from temp/manifests.js
```
"@microsoft/sp-core-library": {
          "type": "component",
          "version": "1.3.4",
          "id": "7263c7d0-1d6a-45ec-8d85-d4d1d234171b"
        }
```

The author of issue #985 closed that issue, saying they were able to work around it by running the Yeoman generator to create a new project and copying their web part code into the new project. That doesn't work for me. (A good thing, as that is an unacceptable workaround, anyway.) So, this really needs to be looked into.

**Comment by VesaJuvonen** [comment]
Only v1.1 is supported with SharePoint 2016 Feature Pack 2, like stated in our documentation. We will update the documentation when there will be changes for this. You can expect 1.1 support to remain with SP2016 for now (due server side dependency) and then have newer version supported with SP2019, when that's out later 2018.

**Comment by lhoff** [comment]
"...As stated in our documentation..." Well, that's pretty vague. Got a link?

**Comment by VesaJuvonen** [comment]
Sorry for that. Docs related on the SP2016 support are at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support and referenced also in https://dev.office.com/blogs/now-available-deploy-sharepoint-framework-web-parts-to-sharepoint-server-2016-with-feature-pack-2 where this support was announced.
