### ISSUE TITLE
Shall we replace InfoPath with Access Application for SharePoint?

### ISSUE THREAD

**Issue by tsekityam** [SharePoint/sp-dev-docs#1106]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

[Migrate InfoPath forms to SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-infopath-forms-to-sharepoint) mentioned that we can replace our InfoPath forms with Access applications. However, I found that there is a [report](https://redmondmag.com/articles/2017/04/04/access-services-for-sharepoint-online.aspx) said that Access services will be end-of-life in next SharePoint release. Is this Access services equal to Access applications? If so, Shall we remove the recommending of replacing InfoPath forms with Access applications?

**Comment by lucaband** [comment]
Thanks for your feedback
this forum is primarily for development question and issues on SharePoint Ecosystem (SPFx, Rest, CSOM). 
the question you posted is super valid but outside of the control boundaries of this forum / issues list.
We recommend to follow up in UserVoice for this issue.
