### ISSUE TITLE
Multiple SPFX  webpart loading issue

### ISSUE THREAD

**Issue by Kaviyabk** [SharePoint/sp-dev-docs#1108]
Hi Everyone,

I've just created spfx webpart and getting the data from list. Some time I'm facing the below issue in chrome and mozilla  browsers when refreshing the page.

The same page I've multiple spfx webpart every webparts are separate bundles. am getting the same issue for every webparts.

Error: Multiple anonymous defines in module https://component-id.invalid/791ba9e4-3f0b-40fe-b381-95ede574fd1a_0.0.1/videosStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
e/</</</</<
https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
m
https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:70
Error: Multiple anonymous defines in module https://component-id.invalid/298d63dd-a337-4c74-b728-edd3901be7c6_0.0.1/linksStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
Error: Multiple anonymous defines in module https://component-id.invalid/3215c694-6695-407c-802b-1ce8d5f4198d_0.0.1/tilesStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
Error: Multiple anonymous defines in module https://component-id.invalid/e10ff5d0-f261-415e-8f91-fc77a04dc0cd_0.0.1/documentsStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
Error: Multiple anonymous defines in module https://component-id.invalid/2a25b6e9-c499-4b21-a135-26b2d82edbe1_0.0.1/contentHolderStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
Error: Multiple anonymous defines in module https://component-id.invalid/6bb0d237-1d63-4bae-9094-ecb83af7440f_0.0.1/highlightedVideosStrings
sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js%20line%20515%20%3E%20eval:5:14395
Error: Multiple anonymous defines in module https://component-id.invalid/298d63dd-a337-4c74-b728-edd3901be7c6_0.0.1/multilevelpushmenu

Note : Am using custom master page and page layout.

It would be great if i get the solution for this issue.

**Comment by iclanton** [comment]
What do your strings files look like? Can you post an example of one of them?

**Comment by Kaviyabk** [comment]
Here is the code in mystring.d.ts files,

declare interface ILinksStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  SiteURL:string;
  ListName:string;  
}

declare module 'linksStrings' {
  const strings: ILinksStrings;
  export = strings;
}

**Comment by iclanton** [comment]
What about the strings files that you're deploying/serving? This error looks like a problem with the strings JS files.

**Comment by Kaviyabk** [comment]
Here is my string js file,

define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",   
  }
});

**Comment by iclanton** [comment]
The `Error: Multiple anonymous defines in module https://component-id.invalid/791ba9e4-3f0b-40fe-b381-95ede574fd1a_0.0.1/videosStrings` error is saying that it's encountering multiple `define` function calls in the `videosStrings` file. Are you sure there aren't multiple `define` calls?

If there aren't, can you share a repro with us? Privately is fine.

**Comment by Kaviyabk** [comment]
We are not having the multiple define calls in videosStrings file, I've only one define call

**Comment by iclanton** [comment]
Just sent you an email.

**Comment by stevebeauge** [comment]
Hello,
I'm facing the same issue. Did you make any progress ?

thx

**Comment by ravinleague** [comment]
@VesaJuvonen Is there an update on this issue ? Multiple same Web Parts on the same page doesn't wok on version 1.1.1. 
**Multiple anonymous defines in module https://component-id.invalid/_0.0.1/WebPartStrings**

**Comment by clechner77** [comment]
Same issue here on SP2019.  It's a shame as it makes SPFx webparts basically unusable on classic pages.  If 25% of the time the web part doesn't load, that's a pretty big problem.  Note, this happens with a vanilla Hello World web part too.
