### ISSUE TITLE
SPFx loader is not present in the page

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-docs#1111]
I found a way to reproduce it - using Win10 IE11 with PowerShell, just ensure you run this as administrator. It is no every time, but common. I can reproduce the best on OOTB Communication site:
https://tenant.sharepoint.com/sites/Communication/_layouts/15/error.aspx?ErrorCorrelationId=508c339e-003c-4000-c6da-ab284e770c22&ErrorText=Can't%20load%20the%20application%20on%20this%20page.%20Use%20the%20browser%20Back%20button%20to%20retry.%20If%20the%20problem%20persists%2C%20contact%20the%20administrator%20of%20the%20site%20and%20give%20them%20the%20information%20in%20Technical%20Details.&ErrorDetails=Error%3A%20SPFx%20loader%20is%20not%20present%20in%20the%20page.&ErrorCategory=spfx

This script I'm also using for performance testing
PowerShell script: https://github.com/Saulius-Laurinaitis/performance-testing/blob/master/TestPerformance.ps1

#### Category
- [ x] Bug

Thanks 
Saulius

**Comment by iclanton** [comment]
@mpasarin FYI.

**Comment by iclanton** [comment]
Are you trying to run against a list view page? You might be missing the `?loadSPFX=true` query parameter.

**Comment by Saulius-Laurinaitis** [comment]
I'm just reloading home page without any debug mode - only as usual user. Site is totally OOTB without any customisations.

**Comment by mpasarin** [comment]
We are currently rolling out a fix for this. It's started to hit the tenants in production but won't be 100% for a few days. I'm going to close the issue, if in one week this still persists, please open a new issue and reference this one.
