### ISSUE TITLE
Design, UX and code patterns for SPFx Web Parts based on SASS and CSS

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1114]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

#### Design and UX section for SPFx Web Parts and SASS/CSS
There is a huge interest on how to develop web parts properly so that they can be used in various base containers aka columns provided by the Communication Site template and modern Team site experience. There are a lot of patterns that can be safely used but needs to documented first.

Another missing component is on how to deal with SASS. What are common recipes that I can use in web parts. How to make style definitions reusable and how to manage design customisation from an enterprise perspective.

All theses are currently not appropriate documented in the spf-dev-docs and needs to be enhanced more.

My recommendation is to create a seperate section that will cover those common scenarios.

Happy to pick this section because I will document them on my blog anyway. It think it can be beneficial for more than just my regular blog viewers. 
The latest blog on: [SASS/CSS scoping though CSS Modules](https://n8d.at/blog/how-to-better-control-css-class-naming-in-spfx/), which is an integral part of SPFx, draw a lot of attention recently.

**Comment by russgove** [comment]
I know nothing about Sass and am trying to pick it up as I go. Would be great to have a quick intro article about how to use it specifically with SPFX .
