### ISSUE TITLE
Issue when creating SPFx Project . yo @microsoft/generator - npm ERR! tar.unpack untar error

### ISSUE THREAD

**Issue by arjunumenon** [SharePoint/sp-dev-docs#1115]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Bug

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
When you try to create SharePoint Framework project after setting up the environment, we are getting an error, 
**npm ERR! tar.unpack untar error C:\Users\username\AppData\Roaming\npm-cache\node-forge\0.7.1\package.tgz**
Towards the end, we are getting the following in the error report.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--cache-min" "86400"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! path D:\blah\blah\SampleWP\RnD\node_modules\.staging\node-forge-dc10c1f7\flash\swf\SocketPool.swf
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat 'D:\blah\SpFx\SampleWP\RnD\node_modules\.staging\node-forge-dc10c1f7\flash\swf\SocketPool.swf'
npm ERR! enoent ENOENT: no such file or directory, lstat 'D:\blah\SpFx\SampleWP\RnD\node_modules\.staging\node-forge-dc10c1f7\flash\swf\SocketPool.swf'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.

When we try to use gulp serve, we are getting the below error.
gulp serve

λ gulp serve
[15:12:07] Local gulp not found in D:\blah\SpFx\SampleWP\RnD
[15:12:07] Try running: npm install gulp

We even tried to use the below commands (using administrator)
npm cache clear
npm cache clear

We also tried restarting the machine 

#### Observed Behavior
Ideally the Project has to be created and should be able to execute gulp serve

#### Steps to Reproduce
execute yo @microsoft/generator
Getting the error. 

Unable to use **gulp serve**

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

Regards,
Arjun

**Comment by waldekmastykarz** [comment]
Are you running cmder as admin?

**Comment by arjunumenon** [comment]
@waldekmastykarz Yes I am... Tried with "Running as an Admin" as well without admin privileges. Both are giving me the same result.

**Comment by waldekmastykarz** [comment]
Which version of the SharePoint Framework Yeoman generator are you using?

**Comment by arjunumenon** [comment]
I guess, it is 1.3.4. Not sure whether I am looking to the right version. I had taken the version from **package.json** which is there in the project folder.
If not, appreciate if you can let me know how can I know the version number

**Comment by waldekmastykarz** [comment]
**package.json** is a good source, but you can also check, by:
- checking the contents of the **.yo-rc.json** file in the root of your project to see which version of the generator was used to scaffold the project
- running `npm ls -g --depth=0` to see which version of the generator you have globally installed

what if you would:
- create new folder
- run `npm init --force`
- `npm i node-forge`

Does it work, or are you still getting the same error?

**Comment by arjunumenon** [comment]
Thanks for that. Version is similar when i execute **npm ls -g --depth=0** as well. Please find the details below for your kind reference for your above recommendation. Did not get any error when i execute neither `npm init --force` nor `npm i node-forge`

Giving the complete execution details below. Let me know for any more information

D:\blah\SpFx\SampleWP\RnD
λ npm ls -g --depth=0
C:\Users\blah\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.3.4
+-- gulp@3.9.1
+-- npm@3.10.10
`-- yo@2.0.0


D:\blah\SpFx\SampleWP\RnD
λ md Testers

D:\Arjun\SpFx\SampleWP\RnD
λ cd Testers\

D:\blah\SpFx\SampleWP\RnD\Testers
λ npm init --force
npm WARN using --force I sure hope you know what you are doing.
Wrote to D:\blah\SpFx\SampleWP\RnD\Testers\package.json:

{
  "name": "Testers",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



D:\blah\SpFx\SampleWP\RnD\Testers  (Testers@1.0.0)
λ npm i node-forge
Testers@1.0.0 D:\blah\SpFx\SampleWP\RnD\Testers
`-- node-forge@0.7.1

npm WARN Testers@1.0.0 No description
npm WARN Testers@1.0.0 No repository field.

D:\blah\SpFx\SampleWP\RnD\Testers  (Testers@1.0.0)

**Comment by waldekmastykarz** [comment]
OK, what if you try to scaffold a new SharePoint Framework project now? Are you still getting the same error?

**Comment by arjunumenon** [comment]
Had tried scaffolding the project inside the folder. But I am getting the same error as before.. I have scaffolded from the Admin cmder window.

**Comment by arjunumenon** [comment]
Hey @waldekmastykarz , Do you have any other recommendation for tackling this situation. Any insight to this will be totally appreciated.

Thanks,
Arjun

**Comment by arjunumenon** [comment]
Hey @waldekmastykarz , we have found the solution for the issue. After a bit of drilling down into the issue, we found the real issue.
There was a policy windows service which was running in our machine. And this was clearing off the file, **SocketPool.swf** since the service identifies it as a Video file. Once we have the service stopped and scaffold the needed files, the scaffolding gets completed with all the needed bindings attached. Post that we are able to do **gulp serve**.

Its a bit strange that if the node.js does not find the video file, the complete process gets terminated / get uncompleted rather than skipping that part? Is that an intended behavior of Node.js?

However Thanks again for all the help which you had given and appreciate the responses. I am going ahead and closing the issue.

**Comment by waldekmastykarz** [comment]
Great to hear you found the culprit!

Regarding your question about the behavior of node: it is expected. Imagine the contrary: some files in some dependencies are missing, but Node says all is fine and the moment you try to build your project it fails with some random errors. Now that would be impossible to debug. I'd prefer it to fail already during an install than on runtime, the way it does today.

**Comment by arjunumenon** [comment]
Thanks @waldekmastykarz  for the reply. And sorry for the late and untimely reply. 
Your comments do make sense. It is better to break the installation initially rather than taking it towards the end which would make the troubleshooting tedious. I should have foreseen that.
Thanks again for all the support and contributions in the SPFx universe. Totally appreciate it.

**Comment by SudarshanSaxena** [comment]
I'm still getting this issue and this is frustrating.
Please help.
![Screenshot 2019-11-17 at 12 06 24 AM](https://user-images.githubusercontent.com/33934789/68997584-31340780-08ce-11ea-813e-61200d585601.png)

**Comment by arjunumenon** [comment]
@SudarshanSaxena  - I would recommend you to open this as a new issue in Github from [THIS LINK](https://github.com/SharePoint/sp-dev-docs/issues/new).
Since this thread is closed and it is very old, there is a good chance that might not be there in the RADAR of  PnP team or any other team who looks into the issue. So please open a new issue. You can very well quote this thread in your new issue so that the person looking into this will know that you have already followed the steps mentioned in the thread here.

Hope I make sense. Let me know if you have any other questions on the same.
