### ISSUE TITLE
Broken link to "Microsoft EULA" on aka.ms/spfx

### ISSUE THREAD

**Issue by pbvansplunter** [SharePoint/sp-dev-docs#1116]
On aka.ms/spfx, the link "Microsoft EULA" is broken (it does not refer to any document).
At the time it referred to the license for SPFX preview: https://github.com/SharePoint/sp-dev-docs/blob/ca4ae9639fb5a86b00f51eb1fae12397ce0e51d0/Microsoft%20Sharepoint%20Framework%20Preview%20EULA.DOCX?raw=true

But this document does not exist in the master branch anymore and is possibly not up to date.

I'd suggest to either update the link to refer to the correct documentation or remove the section about the license.

**Comment by thechriskent** [comment]
Good catch!

Looks like this was corrected by Linda Caputo on January 9th: https://github.com/SharePoint/sp-dev-docs/commit/ebca6026c384ba8a0365fb8299105dd051a0f7e6#diff-13e78f8e60d89a3c5bda2f113b118701
