### ISSUE TITLE
Not able to group custom commands together under a header as in the OOB 'New' List Command

### ISSUE THREAD

**Issue by AsishP** [SharePoint/sp-dev-docs#1120]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [X] Additional article idea

#### Expected or Desired Behavior
An option to group multiple commands on Command Bar as done in the 'New' command. I can see an example here - https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-lists-and-libraries#user-custom-actions.

#### Observed Behavior
There is no documentation or options available to group command together

#### Steps to Reproduce
There is no option in manifest.json or elements.xml of the SPFx extension solution to do this. Please guide if there is such option available or upcoming in future.

Thanks for your contribution! Sharing is caring.

**Comment by mcmynn83** [comment]
@AsishP - this is a feature request.  It is currently not supported.  The best place to ask for new features is uservoice, and we will prioritize features based on community interest.
