### ISSUE TITLE
BaseDialog 'isBlocking' IDialogConfiguration override is not working.

### ISSUE THREAD

**Issue by AsishP** [SharePoint/sp-dev-docs#1121]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The opened dialog shouldn't close when clicked outside the dialog when isBlocking = true

#### Observed Behavior
The opened dialog closes.

#### Steps to Reproduce
1. Follow the steps to create a dialog as here - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx.
2. Override the getconfig() method in the basedialog as below
  public getConfig(): IDialogConfiguration {
    return {
      isBlocking: true
    };
  }
3. The sp-dialog version I have is  "@microsoft/sp-dialog": "~1.3.4"

**Comment by mcmynn83** [comment]
@AsishP - thank you for your feedback.  This looks like an issue that we will investigate.

**Comment by moyali** [comment]
Hi @AsishP,

This is an error in documentation. The configuration should be passed in as constructor parameter. This gives the developer more flexibility.

If you want the color picker to be configurable by instance, pass the config on instantiation:
```
const dialog: ColorPickerDialog = new ColorPickerDialog({isBlocking: true});
```

If you want the color picker to always be blocking, pass the config to its base class in the constructor:
```
constructor() {
   super({isBlocking: true});
}
```

You can check the API reference here: [https://docs.microsoft.com/en-us/javascript/api/sp-dialog/basedialog](https://docs.microsoft.com/en-us/javascript/api/sp-dialog/basedialog)

Thanks for pointing out the error. I will make sure the documentation is fixed.

**Comment by AsishP** [comment]
Thanks @moyali. Sorry for a delayed reply. Finally got a chance to test it today.
