### ISSUE TITLE
Error on addColumnAdapter for column: undefined, error: Error: ***Invalid GUID string: "undefined"

### ISSUE THREAD

**Issue by GrumpyWookie** [SharePoint/sp-dev-docs#1122]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
When implementing a SPField extension, I can run the SPField in debug mode - against LOCALHOST - but it doesn't work when deployed.

This is using an ELEMENTS.XML file.   And then adding the SPField to a Content Type - and then a Doc.Lib.

#### Observed Behavior
Field shows as 'blank' - but error shown in DEBUG CONSOLE.      Field is added to the SITE COLUMNS - and has the correct ClientSideComponentId value.

When viewing in browser, gets the following error :
_Error on addColumnAdapter for column: undefined, error: Error: ***Invalid GUID string: "undefined"_

#### Steps to Reproduce
Have defined a new solution - with new scaffolding - and added code in RENDER.   Deploy to AppCatalog and CDN for JS files.    And the field is added to SITE (when adding the APP).

But - doesn't work in the library.

Otherwise - gets the following : 

Fail to load customizer for column: **COLUMN**, componentId: 453adbab-9f2e-4c33-b6ce-6b68b38623a5, error: ***Manifest not found for componentId "453adbab-9f2e-4c33-b6ce-6b68b38623a5".

**Comment by mcmynn83** [comment]
@GrumpyWookie - In order to help you we will need more information.
1.  Could you include the package you have uploaded?
2.  What version of SPFX are you running?
3.  Could you include a screenshot of your app catalog showing that the package is both valid and has been deployed?
4.  Have you installed the app on the site collection having the issue?

Thanks,
Graham

**Comment by GrumpyWookie** [comment]
Thanks Graham,
Version of SPFX - is within SharePoint Online - I'd re-scaffolded the solution, with latest Yeoman generator...      Using v1.3.4

AppCatalog - yes, deployed and showing no errors.

Have installed the App within the site collection - and the FIELD is created, but, the new FieldCustomizer doesn't work.      (see screen #2 - the list + client component id)

![appcat](https://user-images.githubusercontent.com/6466057/33920359-a6eacf46-e011-11e7-8483-df694261500d.jpg)

![listfield](https://user-images.githubusercontent.com/6466057/33920424-fc1afb26-e011-11e7-8918-6e5ed69323c1.jpg)

<d:SchemaXml>&lt;Field ID="{811abe9a-5ff0-45e0-81a6-46cbbec20336}" StaticName="RelatedDocuments" Name="RelatedDocuments" DisplayName="Related Documents" Type="Note" Group="MMS Columns" NumLines="500" Hidden="FALSE" RichText="FALSE" Required="FALSE" UnlimitedLengthInDocumentLibrary="TRUE" ClientSideComponentId="453adbab-9f2e-4c33-b6ce-6b68b38623a5" SourceID="{ab0abc21-c509-4ec5-b009-20e594a51984}" CustomFormatter="" EnforceUniqueValues="FALSE" Indexed="FALSE" RestrictedMode="TRUE" RichTextMode="Compatible" IsolateStyles="FALSE" AppendOnly="FALSE" Version="1" AllowDeletion="TRUE" ColName="ntext8" RowOrdinal="0" /></d:SchemaXml>

**Comment by GrumpyWookie** [comment]
Have updated all packages to 1.4.0 - and same issue.
![consolelog](https://user-images.githubusercontent.com/6466057/33921334-3ebf3eba-e017-11e7-9190-054bd5432c56.jpg)

**Comment by GrumpyWookie** [comment]
Hello again - I reversed out the entire solution - and re-built, re-deployed - and it worked...!!    But now (today) it's no longer working.   I have changed NOTHING - but it's broken - after having been working.

_Error on addColumnAdapter for column: undefined, error: Error: ***Invalid GUID string: "undefined"_

_Fail to load customizer for column: RelatedDocuments, componentId: 2480cb1f-575f-4d64-89e2-94f176f37187, error: ***Manifest not found for componentId "2480cb1f-575f-4d64-89e2-94f176f37187"._

**Comment by mcmynn83** [comment]
@GrumpyWookie - sorry to ask 2 more questions.  
1. Could you load the dev console (ctrl-f12) and take screen shots of that
2.  Could you also send the SPRequestGuid from the response header for the request (also, if the site is not mcdgrouptest.sharepoint.com please let me know where the request is being made to)

Thanks!
Graham

**Comment by mcmynn83** [comment]
No response from the customer so closing the issue.
