### ISSUE TITLE
Sharepoint List Webbook callback includes Byte Order Marker (BOM)

### ISSUE THREAD

**Issue by wvanderdeijl** [SharePoint/sp-dev-docs#1123]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After registering a webhook to a sharepoint list I expect my endpoint to be invoked with a valid JSON payload to notify it of a change in the monitored sharepoint list.

#### Observed Behavior
Registering the webhook works fine, but when my endpoint is invoked it fails to parse the JSON. After some investigation I found out that the http request includes a Byte Order Marker (BOM). You can see this in the screenshot below. After the last header there are two newlines (as expected) and then the BOM marker EF BB BF. AFAIK this is not valid json and expressjs body-parser fails to parse the message. Unfortunately we are using a cloud functions backend and the parsing happens before our cloud function is even invoked so we can't fix it in our own code by removing the BOM.

This is with sharepoint online on an office 365 domain that was just created (december 2 2017)

![image](https://user-images.githubusercontent.com/7952432/33755567-ab76c0b6-dbf1-11e7-8fd3-e75a3ae3ac2b.png)

The error stack from our cloud function:

```
Error: invalid json
    at parse (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:79:15)
    at /var/tmp/worker/node_modules/body-parser/lib/read.js:102:18
    at IncomingMessage.onEnd (/var/tmp/worker/node_modules/raw-body/index.js:149:7)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by mcmynn83** [comment]
@wvanderdeijl - Thanks for your feedback, we will investigate what is going wrong here.

**Comment by CPritch** [comment]
Thanks so much, just dropping in to confirm that this is happening on my end. The main issue seems to be with various Node packages assuming that a header of 'Content-Type:Application/JSON' forces it to parse the entire body causing run-time errors. This would be a fantastic thing to fix as it allows for a final integration path for desktop, offline notifications from SharePoint to Chrome or Firefox.

**Comment by ocreeva** [comment]
@wvanderdeijl - This has been fixed for SharePoint Online webhook notifications. Please let me know if you continue seeing issues with the notification payload.

**Comment by andrewconnell** [comment]
Closing as reported fixed.
