### ISSUE TITLE
Build failed with property includeClientSideAssets

### ISSUE THREAD

**Issue by rupppat** [SharePoint/sp-dev-docs#1126]
Build failed with additional property in package-solution.json file: "includeClientSideAssets": true

Added the property as described: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn#project-directory](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn#project-directory)

Error message in Terminal:

ERROR: Error parsing file 'package-solution.json'
(#/solution) Additional properties not allowed: includeClientSideAssets

package.json : 
[package_json.txt](https://github.com/SharePoint/sp-dev-docs/files/1542541/package_json.txt)

**Comment by waldekmastykarz** [comment]
@rupppat the `includeClientSideAssets` property is available only in SharePoint Framework v1.4. Your solution is based on SharePoint Framework v1.1 which doesn't support it and which is why you're getting the error.

**Comment by rupppat** [comment]
thank you for the swift response. How do I update it for future web parts?

**Comment by rupppat** [comment]
guess I found an answere: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages

**Comment by ymihir** [comment]
@rupppat ,
Could you please tell me what package you have updated. I have updated below packages to 1.4.0 version but still getting build errors.
@microsoft/sp-core-library
@microsoft/sp-webpart-base
@microsoft/sp-webpart-workbench
@microsoft/sp-module-interfaces

**Comment by rupppat** [comment]
Did you update existing WebPart Project or start from scratch with updated Version?

**Comment by ymihir** [comment]
I have done both ways. But I have updated only for that project. Not for global. Means at global level my sharepoint framework still pointing to 1.2.0. 
The reason why i haven't updated global was I am afraid of existing working solutions may not work because of these updates.
Is this true?

**Comment by rupppat** [comment]
Updating globally shouldn't affect existing Projects and you still can get a previous Version in a local Directory. Try updating globally.

**Comment by ymihir** [comment]
Currently below are the versions that is listing when I checked with `npm outdated -g`
```
Package                                  Current           Wanted           Latest  Location
@microsoft/generator-sharepoint            1.2.0            1.4.0            1.4.0
angular-cli                      1.0.0-beta.28.3  1.0.0-beta.22-1  1.0.0-beta.28.3
npm                                        5.5.1            5.6.0            5.6.0
typescript                                 2.6.1            2.6.2            2.6.2
```

**Comment by rupppat** [comment]
try using npm Version 4: npm install npm@4

**Comment by ymihir** [comment]
I have updated all above mentioned to wanted versions. 
Now it started working. Thanks
