### ISSUE TITLE
1.4 - error installing node modules on Windows machine

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-docs#1127]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Update to 1.4
Delete node_modules folder on existing project
Install node_modules

#### Observed Behavior
Install failed with error
"EPERM: operation not permitted, scandir..."

#### Steps to Reproduce
Update to 1.4 using Yeoman interface (could this be the problem?)
Delete node_modules folder on existing project
Try to install node_modules again

I was able to quickly resolve this by running npm install as admin.

**Comment by iclanton** [comment]
Can you give some more information on your setup? What OS and which version are you running?

This sounds like an issue with the permissions on your filesystem, and specific to the SPFx generator.

**Comment by shaipetel** [comment]
In similar situation but i think I am getting a different error.

Perhaps it is our Node/NPM versions that are not up to date?

Can someone perhaps say what NPM/Node versions should be installed, I know latest NPM isn't supproted (right?)

@joelfmrodrigues - side note: try running this on an administrator shell (right click -> run as administrator)

**Comment by waldekmastykarz** [comment]
Node v6/npm@3 are the officially supported setup at the moment, though npm@4 on Node v6 should work as well.

**Comment by joelfmrodrigues** [comment]
Should have added this in the previous comment...
I was using Node 8.9.0 and NPM 5.5.1 (which is not officially supported)

**Comment by andrewconnell** [comment]
Still an issue? Since we're up to SPFx v1.7.1, maybe no longer an issue (*doing some issue house cleaning*)...
