### ISSUE TITLE
Error when bundling solution targeting on-prem

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1128]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to bundle newly created project. 

#### Observed Behavior
When running `gulp bundle` on a newly created project, scaffolded using generator v1.4.0, targeting on-prem, you get the following error:

```text
[13:04:59] Error - typescript - <undefined path>(0,0): error TS2688: Cannot find type definition file for 'es6-promise'.
```

#### Steps to Reproduce

- scaffold new project using generator v1.4.0
- baseline: _SharePoint 2016 onwards, including SharePoint Online_
- other options default values
- no JavaScript framework (the same error occurs when choosing React as framework)
- run `gulp bundle` 💥

**Comment by iclanton** [comment]
@nickpape-msft - can you take a look?

**Comment by joaoferreira** [comment]
Had the same issue, I was able to bundle the solution after installing the type definitions for es6-promise again.
`npm install --save @types/es6-promise`

**Comment by nickpape-msft** [comment]
Looks like we have a dependency that is missing for on-prem. @joaoferreira's workaround is the correct solution. We will update the generator with this missing package.

**Comment by nickpape-msft** [comment]
@waldekmastykarz , are you using NPM or a difference package manager to do installations? Which version of NPM are you using? Could you manually check the `node_modules/@types/` folder and see if `es6-promise` is there?

It looks like various framework packages (including `sp-webpart-base@1.1.1`) should be bringing `@types/es6-promise` as an indirect dependency, which should get resolved by your `tsconfig.json`. If you have a consistent repro, could you try just running another `npm install` after the generator is complete just to ensure all dependencies are installed?

Or even better, could you run `npm list @types/es6-promise` on a repro of this issue? Again, I wasn't able to repro this using `npm@3.10.10`

**Comment by waldekmastykarz** [comment]
I've just checked it and it seems like the issue occurs only on node v8 and npm v5. On node v6 with npm v4 everything works just fine. The odd thing is, that in both cases the output of the `npm ls @types/es6-promise` command is the same:

```text
├─┬ @microsoft/sp-build-web@1.1.0
│ ├─┬ @microsoft/sp-build-core-tasks@1.1.3
│ │ └── @types/es6-promise@0.0.32
│ └─┬ @microsoft/sp-polyfills@1.1.0
│   └── @types/es6-promise@0.0.32
├─┬ @microsoft/sp-webpart-base@1.1.1
│ ├─┬ @microsoft/sp-component-base@1.1.0
│ │ └── @types/es6-promise@0.0.32
│ ├─┬ @microsoft/sp-http@1.1.1
│ │ └── @types/es6-promise@0.0.32
│ ├─┬ @microsoft/sp-loader@1.1.1
│ │ └── @types/es6-promise@0.0.32
│ ├─┬ @microsoft/sp-page-context@1.1.0
│ │ └── @types/es6-promise@0.0.32
│ └── @types/es6-promise@0.0.32
└─┬ @microsoft/sp-webpart-workbench@1.1.0
  ├─┬ @microsoft/sp-application-base@1.1.1
  │ ├─┬ @microsoft/sp-extension-base@0.1.1
  │ │ └── @types/es6-promise@0.0.32
  │ └── @types/es6-promise@0.0.32
  ├─┬ @microsoft/sp-client-preview@1.1.1
  │ └── @types/es6-promise@0.0.32
  └── @types/es6-promise@0.0.32
```

Since node v8 is not officially supported at the moment, we could close this issue, but perhaps it would be helpful for you guys to track this internally when fixing support for node v8, which being LTS should be supported.

**Comment by nickpape-msft** [comment]
Thanks @waldekmastykarz , we will continue to track the issue internally.

**Comment by nickpape-msft** [comment]
@waldekmastykarz this should be working properly now.
