### ISSUE TITLE
SPFx 1.4 web part does no appear in the web part gallery 

### ISSUE THREAD

**Issue by joaoferreira** [SharePoint/sp-dev-docs#1131]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Being able to add the web part to the page after from the app catalog 

#### Observed Behavior
Updated the framework to version 1.4 to test the asset packaging and after it I can't see the web parts that I install in the web part gallery.
Tested with the default hello world, it runs fine on both workbenches but after being installed it does not appear in the web part gallery.
Used the global app catalog and the site collection app catalog and got the same behaviour, the app is deployed with **No Errors**
Tested the **skipFeatureDeployment** on and off and the got the same behaviour, even after adding the app manually on site contents.

#### Steps to Reproduce
1. Create the hello-world default SPFx web part
2. Make sure the **includeClientSideAssets** is set to true
3. Run the command gulp bundle --ship 
4. Run the command gulp package-solution --ship
5. Add the package to the app catalog (local or site collection)
6. Go to a modern page and check if your web part is available

**Comment by FranckyC** [comment]
Same here but with extensions. They are not loaded at all :(. Works fine in the workbench.

**Comment by FranckyC** [comment]
[Update] I've created a brand new solution from scratch and it works now. Make sure your `package-solution.json` file contains the following info (related to the `skipFeatureDeployment ` flag during the project generation):

```
"features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "07ebae29-c297-4d2e-b201-5b0a9e2b95e8",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml"
          ]
        }
      }
    ]
```

**Comment by VesaJuvonen** [comment]
includeClientSideAssets is not yet supported with site collection app catalog. Support for that is coming relatively soon. We'll push out docs on site collection app catalog later this week with the updated information on what's supported and what's not.

**Comment by VesaJuvonen** [comment]
Quick update - this capability is currently rolling out and is already available with a subset of tenants. It should be available worldwide within a week.

**Comment by hbgeorgian** [comment]
Having the same problem with includeClientSideAssets set to true, solution deployed at the tenant site catalog. Solution deploys, but web parts do not appear in the Add Web Parts dialog.
