### ISSUE TITLE
Intermittent Site Collection App Catalog allow list issue

### ISSUE THREAD

**Issue by alisalih1** [SharePoint/sp-dev-docs#1132]
I experienced an intermittent issue with **Add-SPOSiteCollectionAppCatalog** cmdlet while adding a site to tenant allow list for Site Collection App Catalog. Initially exception occurred, after a while, I was able to add to the allow list on the very same site it created an exception. 

![image](https://user-images.githubusercontent.com/21177498/33806511-4622b574-dd97-11e7-9cfc-dc9433047cdb.png)

- SPO Mgmt shell Microsoft.Online.SharePoint.PowerShell Version 16.0.7115.0
-Tenant: Microsoft Office 365 Development tenant with targeted release enabled for all users (https://salih01.sharepoint.com) 

#### Category
- [X ] Bug

#### Expected or Desired Behavior
Add-SPOSiteCollectionAppCatalog should add the site collection to allow list on the SPO tenant. Cmdlet should return nothing to shell. 

#### Observed Behavior
Add-SPOSiteCollectionAppCatalog stops with an exception. _"The site collection allowed list /sites/appcatalog/Lists/SiteCollectionAppCatalogs does not exist on the specified site 3b0297eb-2294-4c80-8e27-f39f632c58f0"_

#### Steps to Reproduce
Step 1: Connect-SPOService -Url "Enter tenant admin url"
Step 2: Add-SPOSiteCollectionAppCatalog -Site 'ENTER TARGET SITE COLLECTION URL HERE'

**Comment by VesaJuvonen** [comment]
thx @alisalih1 for submitting this based on chat on Twitter. One more question around this - was this one time issue with that site collection or are you seeing similar issues if you enable the site collection app catalog in other site collections as well? - Just trying to narrow down the possible issue and repro steps. Thx.

**Comment by alisalih1** [comment]
@VesaJuvonen - This happened two times in 3 test site collections I created. 

I may have an idea now what might be going on...  I checked the time stamp on the standard site assets when a site collection was created versus the **Apps for SharePoint** and it seems like on the occasions that I saw this exception, **Apps for SharePoint** got added to the site collection with a delay. In this case, it is 2hours of delay. 

![image](https://user-images.githubusercontent.com/21177498/33806667-9b56107a-dd99-11e7-8b5f-ed1fafec224d.png)

**Comment by JeremyKelley** [comment]
When the error occurs are you able to manually navigate to the list specified in the error?

**Comment by JeremyKelley** [comment]
It's a hidden list but should still be able to get there from the URL.  Just curious if it's an intermittent site access issue, or something in the commandlet / REST call itself.

**Comment by dgaeta** [comment]
@alisalih1 Are you still experiencing this issue?
I attempted to repro the issue but I was able to add the AppCatalog with no issues.

**Comment by dgaeta** [comment]
Closing this issue as it appears to no longer be a problem. Please reopen this issue if you are still experiencing the issue.
