### ISSUE TITLE
Update existing web parts to SPFx 1.4

### ISSUE THREAD

**Issue by lrolseth** [SharePoint/sp-dev-docs#1133]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi All,
I have an existing SPFx web part that I want to update to Framework 1.4.  I see how I can use npm to update the individual modules in my project, but is that process supposed also update the framework too?

I want to use the new functionality to package the assets in my deployment.  However, I got the error when I manually added includeClientSideAssets to the package-solution.json, and did gulp build.  Error:  "Additional properties not allowed: includeClientSideAssets"

My workaround was to update the Yeoman generator for  microsoft/sharepoint, create a brand new project, and copy my code files into it.  What should I do next time so I don't have to do this? Is this possible?

Thanks~
Laura

**Comment by joaoferreira** [comment]
You have to update the web part packages to the latest version. You can find the instructions here https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages

**Comment by mcmynn83** [comment]
That documentation looks correct.  If you require additional documentation or further questions please create a new thread so we see it.
