### ISSUE TITLE
Modern page publish error with Conent Approval turned in Site Pages library

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-docs#1138]
I'm getting: _Could not publish your page. We're sorry, we encountered an unexpected error. Please try again, if the problem persists please contact your Administrator._
You just need to turn Content Approval on Site Pages library, then create new page based on "News post" content type and save it. The on display mode click publish and see error message. It does not show error message when you publish from Edit mode. But in both scenarios page is not approved, which is expected and you need to go to Site Pages library and approve it manually. 
I would also suggest this working in similar way like publishing pages work - displaying different buttons depending on approval status, e.g. if content approval is turned on then instead of "Publish" it could show "Submit" for contributor, but for approver "Publish" should approve content as well.

#### Category
- [x] Suggestion
- [x] Bug

Thanks 
Saulius

**Comment by Saulius-Laurinaitis** [comment]
This error actually happens on any OOTB modern page with a process: 
1. create new page, save, but do not publish. 
2. edit page all properties from site pages
3. go to the news page and publish it

This is not nice when you have some additional metadata fields for your modern pages.

**Comment by Saulius-Laurinaitis** [comment]
Found much simpler way to reproduce:

1. Create and publish modern page
2. Edit page and see that URL finishes with ?Mode=Edit
3.  do not save page, just trim ?Mode=Edit and reload the page
4. click Publish on display mode

**Comment by e078108** [comment]
We are getting this error on modern pages.

@VesaJuvonen Can you please advise if there is a solution?

Thanks.

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
