### ISSUE TITLE
Reference external style names inside *.module.scss without them being re-written

### ISSUE THREAD

**Issue by nero120** [SharePoint/sp-dev-docs#1142]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When adding css rules in a *.module.scss file, I should be able to reference style names without them being re-written in order to target external component styles. For example, the button in a Command Bar react control has a .is-expanded class that is added when the sub-menu is displayed. If I try to reference .is-expanded inside my *.module.scss file, the style name gets rewritten (e.g. to is-expanded_628ea019) and therefore will not match the style in the Command Bar so will not apply the style.

I know I can create a *.scss file (without .module) and those styles won't be re-written, but I need to include my style rules inside my component styles so this is not a valid option.

#### Observed Behavior
All style names inside *.module.scss get re-written to ensure they are unique, but this should only occur for *my* styles, not for external styles that I am intending to reference.

**Comment by russgove** [comment]
you can create global classes in yours css and the names won't be rewritten.  https://n8d.at/blog/how-to-better-control-css-class-naming-in-spfx/

**Comment by nero120** [comment]
That'll do! Thanks @russgove :simple_smile:
