### ISSUE TITLE
ClientSideAssets missing

### ISSUE THREAD

**Issue by BigEaseGueldi** [SharePoint/sp-dev-docs#1143]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**When is the library "ClientSideAssets" being provisioned?**

I have ensured the following things:

- **Get-SPOTenantCdnOrigins -CdnType Public** shows */CLIENTSIDEASSETS
- I have set the **includeClientSideAssets** to true
- I'm on SPFx version **1.4**
- No problems running **gulp bundle --ship** and **gulp package-solution --ship**
(the sppkg contains the folder "ClientSideAssets" containing the correct files)
- No problems during upload to a Site Collection App Catalog (target "SharePoint Online")
- No problems during installation of the app

#### Problem
Once I want to embed my Web Part on a page, it will not find any resource:

_Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/xxx/ClientSideAssets/ef662331-3b85-4aba-9ba9-1095624c8d13/xxx_en-us_47306258fbcefb00a929ec44b120beab.js' for resource 'XXX' in component 'dc35a537-2de5-4463-806d-5a3972dd2817' (XXX). There was an error requesting the file._

Did I miss something here? Do I have to create the library on my own?

**Thanks for helping!**
Dirk

**Comment by russgove** [comment]
same issue here

**Comment by joaoferreira** [comment]
According to @VesaJuvonen the site collection app catalog does not support yet the asset packaging. This issue might be related with it. https://github.com/SharePoint/sp-dev-docs/issues/1131

**Comment by russgove** [comment]
Yes, I was trying to use it with site collection app catalog.

**Comment by VesaJuvonen** [comment]
Just to copy the status from the duplicate (#1131) . This capability is currently rolling out and is already available with a subset of tenants. It should be available worldwide within a week.
