### ISSUE TITLE
Logic issue in a sentence

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#1149]
The sentence "But later a user mistakenly changes the **Arrived** field of a shipment back to **No** and then fixes his mistake by setting it again to **Arrived**" does not make sense.

**Repro steps:**
1) Go to https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in
2) Search for "But later" which is the beginning of the sentence
3) The "then fixes his mistake by setting it again to **Arrived**" part of the sentence does not make sense

**Actual result:**
Word **Arrived** is used instead of **Yes**
**Expected result:**
Word **Arrived** is changed to **Yes**

**GH article:**
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in.md
**Proposed fix:**
Change **Arrived** near the end of the sentence to **Yes**
![mistake](https://user-images.githubusercontent.com/16706698/33994966-b5f1b0e2-e0dc-11e7-8cb2-0b91b2687027.png)

**Comment by Linda-Editor** [comment]
Updated the sentence to read:
"But later a user mistakenly changes the **Arrived** field of a shipment back to **No** and then fixes his mistake by setting it again to **Yes**."
