### ISSUE TITLE
SPFx 1.4 Online Workbench doesn't load local web parts

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#1156]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using gulp serve --nobrowser
I want to open the online workbench under ~site/_layouts/15/workbench.aspx

I have a production version of the current SPFx package installed on this tenant, but I expected the workbench to show me the current dev version of the web parts, just like it did in previous SPFx versions.

#### Observed Behavior
I can now visit the workbench even when gulp serve is not running, it shows all web parts there.
When gulp serve is running, if I add a web part from my package to the page sometimes it adds a web part that loads the bundle file from the current dev (served from local host by gulp serve) but most of the times it tries to load the bundle JS file from the CDN, where the production web part loads it.

This used to work perfectly fine before, the workbench would always serve my local dev version of the web part.

#### Steps to Reproduce
build SPFx web part in production, install the package and save the bundle in your CDN.
Now, run gulp serve. visit the online workbench on the same tenant you installed it on.
Add the web part to the workbench.
check your network where the bundle file is being loaded from - you will see between refreshes that it sometimes comes from local dev, and most times from the CDN.

It should never come from the CDN while we are in workbench.

This started happening after upgrading packages to 1.4.0

**Comment by shaipetel** [comment]
I can reproduce this every time now: First time the workbench loaded after gulp serve was started it will load the files from local dev, including the TS  source files.

When the workbench is refreshed - it will load the files from the CDN, production version.
From that point - it will never load the local dev files again.

Not sure if it is a new version of the online workbench that broke it, or the fact I just upgraded to 1.4.0

**Comment by shaipetel** [comment]
FYI, I deleted node_modules, reverted back to my old versions and ran npm install.

Now the workbench works perfectly loading from my local every time. So it seems to be related to upgrading to 1.4

**Comment by mcmynn83** [comment]
@shaipetel - It is an unsupported scenario to both have a webpart with the same component ID in your app catalog as well as serving it via gulp serve and try to use it in the workbench.  We do not have a way to determine which manifest should be loaded.  The fact that it worked prior to 1.4 was just good luck.  Please only use webparts not already in your app catalog.

**Comment by shaipetel** [comment]
@mcmynn83 where is this documented to be unsupported?

Also, not sure what you expect us to do as developers - one of the steps to release and test the web part is:
1. test in workbench
2. test in online workbench
3. deploy the package and test in modern/classic pages

so if this is an unsupported scenario, how should we go through the dev stages to production?
If i can't test the production package in my development environment, what - you expect me to test the final package directly on production?
Keeping 2 tenants for dev is an overkill.
Also keep deleting the package when I want to use workbench is a lot of trouble.

I have my dev sites set up with all my content and structure for testing and I need to test on that environment both in workbench and the final production package. That seems pretty reasonable something almost everyone should do, plus it worked before 1.4 so my guess is many people used it this way, and the more of them upgrade to 1.4 the more reports that this is broken you will get.

I strongly recommend you reconsider closing this issue and think about perhaps supporting it.

**Comment by shaipetel** [comment]
FYI: anyone who is experiencing this issue, we have found a workaround:
If you open the workbench under a site's URL where you never installed the SPFx app - it will load it from the local dev as expected.
So the issue seems to affect only sites where the product was installed and trying to load the same product from local dev into the workbench.

So the workaround was simply to create a new sub site only to host the workbench.

**Comment by russgove** [comment]
So how are we supposed to test  new versions of our  webparts ?

**Comment by shaipetel** [comment]
2 options:
1. if you build and put it on the CDN, you can install the package and test it on the site you installed it on.
2. if you want to test it on the online workbench, the workaround I found was to create a separate site that you never installed the package on (didn't add it to the site contents) and the online workbench still works there.

If @mcmynn83 is correct and this is something Microsoft thinks is not supported and shouldn't work, and if my workaround stops working in a later release - who knows... I have no clue how they expect us to test it or use the online workbench if it requires a whole new tenant... I'd expect them to have the workbench prioritize the local host over whats installed on the site, which is what they did in earlier releases.

**Comment by mcmynn83** [comment]
@shaipetel /@russgove - You also have the option of loading your new version via the site collection app catalog.  This will prioritize over the version stored in the tenant app catalog.  Hope that helps.

**Comment by shaipetel** [comment]
@mcmynn83 yeah, but not sure how is that streamlining the developer's work if he needs to upload it to the site collection catalog when he is debugging locally, then remove it when he wants to test the published build (with local or production DNS).

I'm sure you'll agree having the workbench always prefer local dev packages over what ever is installed would be much easier.

in any case - for me being able to use a sub site is good enough, even if not perfect. hope this stays in future updates.

**Comment by russgove** [comment]
Thanks GrahaMc,
Currently my apps are all site specific so I am always using the site
collection app catalog, so I am having no issues with this.

**Comment by zshane15** [comment]
@shaipetel you can also just temporarily adjust the manifest.json of the web part you wish to test. I updated the "id" property by appending "-123" and it then pulled my local dev version
