### ISSUE TITLE
Cannot specify bundle file name in V1.4.0

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#1164]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I would like to be able to specify the bundle file name (JS) to be used in my product.
In previous versions I would go to "config.json" file and set the "outputPath" parameter to the file name I wanted to get.
I used it to set the file name to [product].[version].js instead of [product].js

I expect an easy and simple way to specify the bundle file name within the config, like was possible in earlier releases.

#### Observed Behavior
The new config.json schema now does not allow to do that.
It let me set the bundle name under "bundles" to only letters, numbers and dash. No support for dots.
Also - changing it produces a package that points to that specific name. If i throw a web part on the page and in the future make a new package that have a different bundle name, it will not detect and update existing web parts on older pages since it treats it as a new different bundle - and not just as a different file name to the same module.

My request is simple: I want to bundle file name NOT to include the hash (thanks- you added this flag!) but to include the package version number instead of the hash.

**Comment by nickpape-msft** [comment]
Thanks for your feedback @shaipetel. We discussed this and will consider expanding the regular expression to allow dots.

**Comment by frnk01** [comment]
This would be great to get implemented. We have people running the same code on different versions, and to be able to push this to azure storage with appending the version number would be great.

@nickpape-msft Any news on this request?

**Comment by andrewconnell** [comment]
As this was a feature request, going to close this issue as these should be submitted to UserVoice: https://aka.ms/sp-dev-uservoice
