### ISSUE TITLE
SPFx Application Customizer extension is not triggered

### ISSUE THREAD

**Issue by IvanToronto** [SharePoint/sp-dev-docs#1166]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx extension that adds content to the page headers works in debug mode, but for shipped to CDN version - it does not work most of the time.
I am using per site manual installations, not using skipfeatureDeployment=true

#### Observed Behavior
I did some research, SPFx extension comes to the O365 website inside the default feature, and the feature references elements.xml file that specifies the ApplicationClientId from SPFx extension and the custom action exist to register this application Id for executing.
This ID is perfectly correct and sometimes it worked in O365 and then stopped.
No console errors are displayed.

Important observation:
On modern pages, I can see that HTML code has the custom action:
""customActions" : [{"title":"Top Navigation","location":"ClientSideExtension.ApplicationCustomizer","clientSideComponentId":"a4212e47-b76a-4e53-8985-625daedf5ec2","clientSideComponentProperties":"{\"Top\":\"Top area of the page\",\"Bottom\":\"Bottom area in the page\"}","sequence":65536,"rights":{}}],
"

**So since component with id a4212e47-b76a-4e53-8985-625daedf5ec2 exists and custom action exists on the page that triggers this component Id - it should work. But SharePoint does not even try to load my SPFX extension JS file from CDN.**

My guesses:
1)Javascript code in O365 that is responsible for processing registered custom actions - is not running correctly, but not showing any errors in console
2)SPFx extension with specified Id is not deployed correctly and cannot be found by SharePoint. However, there no errors are displayed during deployment.

**Comment by mpasarin** [comment]
Hello IvanToronto,
Could you go to the SPFx developer tools (pressing Ctrl+F12) and see if you have any errors in the Trace logs? Also, double check that you can find the manifest for your component id in the Manifests tab.
Both your guesses can be checked in there. With the actual error from SPFx we can look at what went wrong.

**Comment by mcmynn83** [comment]
Closing due to no response.
