### ISSUE TITLE
Field Customizer: event.fieldValue contains url only for Hyperlink column

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1167]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`event.fieldValue` contains both Url and link text
#### Observed Behavior
`event.fieldValue` contains Url only

#### Steps to Reproduce
- create Field Customizer
- apply Field Customizer to Hyperlink or Picture column
- check `event.fieldValue` value in `onRenderCell` event handler.

**Comment by patmill** [comment]
Tracked here - https://github.com/SharePoint/sp-dev-docs/discussions/7407
