### ISSUE TITLE
SPFx 1.4 Deploy assets to public CDN in tenant

### ISSUE THREAD

**Issue by AnitaBoerboom** [SharePoint/sp-dev-docs#1171]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When public CDN in tenant is enabled I expect the sources to be stored there and not in app_catalog/clientsideassets.

#### Steps to Reproduce
Public CDN in tenant was enabled and re-enabled
![image](https://user-images.githubusercontent.com/22956073/34259806-f03ec1c2-e663-11e7-8205-66c38dd836f8.png)

package-solution.json contains: "includeClientSideAssets": true,
write-manifests.json contains: "cdnBasePath": ""

Bundled en packaged the solution for shipping.
Solution package dropped in app catalog and deployed.
Added app to site.
Added web part to page.
Developer tools:
![image](https://user-images.githubusercontent.com/22956073/34259817-fd0fba28-e663-11e7-9b89-4b5a8f868903.png)

Result: Source points to app_catalog.
Expected: Source points to /sites/cdn/content

Did I miss a step?
Is my expectation not correct?

**Comment by russgove** [comment]
i think the tooling deploys the javascript to the client side assets library in the site the solution was deployed on. if the tenant has cdn enabled with the default settings then that client side assets library is cdn-enabled, and your code will be served from the cdn. if you enabled a custom site collection to be used as a cdn(like i did) the tooling has no way of knowing that. it just puts the code in the  site it was deployed on and if it's cdn enabled, your stuff is served from the cdn. if cdn is not enabled, stuff is seveed from the sites client side assets library.

**Comment by VesaJuvonen** [comment]
@AnitaBoerboom this might sound strange and we'll adjust this this still in our side, but even thought you have includeClientSideAssets set to true, you should not change the default value of cdnBasePath, which will need to be still as `"cdnBasePath": "<!-- PATH TO CDN -->"` to make things work.

**Comment by AnitaBoerboom** [comment]
@VesaJuvonen I changed the cdnbasePath as you suggested, but the behavior is the same.
Result: Source points to app_catalog.
**Expected**: Source points to /sites/cdn/content

To avoid mistakes I even copied the setting out of a newly generated project.

Is my **expectation** correct?

**Comment by waldekmastykarz** [comment]
Why are you expecting that files should be served from _/sites/cdn/content_ @AnitaBoerboom? You deployed a package with assets which SharePoint automatically extracted and deployed, and is serving from a CDN. Where SharePoint is deploying assets from packages is an internal implementation and not something you can influence or should be concerned with. 🙂

**Comment by AnitaBoerboom** [comment]
So if public CDN is enabled the files should be served from: https://publiccdn.sharepointonline.com/.../ClientSideAssets
if not enabled the files should be served from:
app catalog url where the package is stored

I configured both options and I see indeed the difference in url where the files are served from.

But @waldekmastykarz , what would be the reason(s) to use one over the other?

**Comment by waldekmastykarz** [comment]
You mean why SharePoint picks one CDN origin and not the other? The location where assets included in the package are deployed to is defined in SharePoint and not something you can control, so it will always use the _ClientSideAssets_ origin no matter what other origins are configured.

**Comment by AnitaBoerboom** [comment]
What should be the main reason(s) to enable public CDN or not?

**Comment by waldekmastykarz** [comment]
Here is a KB article explaining it briefly: https://support.office.com/en-us/article/use-the-office-365-content-delivery-network-with-sharepoint-online-bebb285f-1d54-4f79-90a5-94985afc6af8. Some additional information is included in the announcement article at https://dev.office.com/blogs/general-availability-of-office-365-cdn.

**Comment by AnitaBoerboom** [comment]
Thanks @waldekmastykarz
