### ISSUE TITLE
Error loading debug manifests - SPFx Extensions

### ISSUE THREAD

**Issue by bhanuchintha** [SharePoint/sp-dev-docs#1175]
Hello Team,

While trying the SPFx extensions below example, i am getting the attached error. 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

**Error loading debug manifests:**
![js error](https://user-images.githubusercontent.com/19674673/34308708-8e61449a-e774-11e7-97b3-8a2179a1921d.jpg)

Can you please help in this regard.

Thanks & Regards,
Bhanu

**Comment by andrewconnell** [comment]
Looks like the local webserver isn't running. If you did the `gulp serve` or `gulp serve --nobrowser` step, then I'm guessing you are running Node.js 8.x which SPFx no like ATM.

Current, MSFT's guidance is to use Node v6.

But you can use Node v8 by prefacing your command with `NODE_NO_HTTP2=1` like this:

`NODE_NO_HTTP2=1 gulp serve`

Ref #1002

**Comment by VesaJuvonen** [comment]
Hi @bhanuchintha, @andrewconnell already provide valuable input on this. Have you double checked that the localhost is running? - also ensure that you are using right versions. Could you come back and confirm the status, thx.

**Comment by Suresh-Meenakshisundaram** [comment]
i am still getting same error, even after adding the environment variable. i am using Node 6.x
![image](https://user-images.githubusercontent.com/17665731/34591013-445d3d90-f16f-11e7-8a2d-924df4497f25.png)

**Comment by Suresh-Meenakshisundaram** [comment]
Facing similar issue loading debug issues in Edge, Firefox, though added trust-dev-cert. But works fine in IE. any idea?

**Comment by ravinleague** [comment]
Guys,

Contributing my two cents.
I've deployed a custom 'Export to Excel' command action to SP Online. 
I have used SharePoint as the Content Delivery Network by changing the CDN path in the write-manifests.json file and ran gulp build --ship and gulp package-solution --ship.
I have uploaded the files from deploy folder to CDN folder and the .sppkg file to appcatalog further deploying the solution. I did get a debugmanifests error and then I found out that,
1 The. Proxy environment variable was removed from the OS list of env variables. May be system update did that but not too sure.
I then Added New User variable to the environment variables, 
              Variable name: https_proxy
              Variable value: https://yourproxyurl
2. I also noticed that the gulp serve --nobrowser was not running.
After re-running the gulp serve command, I am now able to load my command action.

Hope this helps someone or may direct them in the right direction.

Thank you
Ravi

**Comment by rkbhowmik** [comment]
@bhanuchintha I had also the same problem. Then I ran gulp trust-dev-cert & gulp serve --nobrowser and followed all the steps. It worked afterwards. You may try it.

**Comment by bhanuchintha** [comment]
Hello @andrewconnell @VesaJuvonen @rkbhowmik , Very sorry for responding lately on this discussion. Actually, the issue got resolved with the same approach that you have provided by running the local instalce gulp serve --nobrowser. Thanks for providing the details. 

Thanks a lot again for the followup & support that is provided here.


Thanks &Regards,
Bhanu

**Comment by jiovanniro** [comment]
Hi @andrewconnell I am running the local instance gulp serve --nobrowser and it works perfectly in Chrome and Edge but Internet Explorer 11. 

Do you have suggestions on what could be the issue with IE11?

**Comment by SimonRennocks** [comment]
Does not work in Edge only IE11 for me.

**Comment by jiovanniro** [comment]
Hi all, this problem was pretty frustrating so I want to share what worked for me and hopefully it’ll work for you too. 

I went to the Microsoft Docs and saw that you need to run “gulp trust-dev-cert” in your local dev environment. After doing this it loaded up in IE11 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

**Comment by AntyfrizZz** [comment]
Hello,

I have the same issue. I can run debug on and only in Chrome . When i try to do it on other browser, I get the error.
SPFx 1.7.0
Node - v8.9.4
I ran gulp trust-dev-cert

Nothing. Sad.

Best Regards,
Yavor

**Comment by VesaJuvonen** [comment]
@AntyfrizZz - please submit this as a new issue, so that your input does not get hidden or ignored in already closed issue. yes - it's sad if it does not work, but this seems like an environment issue related to some versions, as we cannot repro that with the given information. Can you please provide more details on the new issue, like which browsers you are referring to (not working) and which versions of those browsers you are using. Thx.

**Comment by AntyfrizZz** [comment]
@VesaJuvonen , here is the new issue with more detailed information https://github.com/SharePoint/sp-dev-docs/issues/3306

**Comment by ravinleague** [comment]
Gulp trust-dev-cert has fixed this for me in one instance!

**Comment by JeanBarros** [comment]
Gulp trust-dev-cert worked for me on Chrome. Not tested in other browsers
