### ISSUE TITLE
Field Customizer isn't initialized on new rows in a Document Library (possible other list types also)

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#1179]
_From @Megamannen on November 30, 2017 9:35_

#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When uploading a new file to a Document Librarary that uses SPFX Field Customizer Extension we expect the new item to also get the Field Customizer and that they are initialized.

#### Observed Behavior
Right now the default behaviour of the column is removed but the Field Customizer isn't added

#### Steps to Reproduce
1. Have a Document Library with some files and use a field customizer on a column.
2. Upload a new item
3. Observe

_Copied from original issue: SharePoint/sp-dev-fx-extensions#76_

**Comment by ahackettms** [comment]
Hello @Megamannen, are you still experiencing this issue?

**Comment by Megamannen** [comment]
My colleague tested this today and we still experience the problem

**Comment by ahackettms** [comment]
@Megamannen , could you please provide a screenshot or video ? Thanks

**Comment by Megamannen** [comment]
I'll see if I can get back to you about this during this week!

**Comment by AJIXuMuK** [comment]
The issues seems to be very old and currently couldn't be reproduced.
Closing this one. Please, feel free to create a new issue if the problem still exists.
