### ISSUE TITLE
Decouple HttpClient from Web Part

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#118]
Currently HttpClient is available through the Web Part context. To take React for example: if you wanted to communicate with SharePoint using the HttpClient, you would need to pass the whole Web Part context into React components which is excessive: it complicates testing and ties the particular component to Web Part, rather than having it reusable which will be important when new SPFx shapes become available.
Have you considered defining an interface for the HttpClient that we could use to pass the instance of HttpClient into components without coupling them with Web Parts?

**Comment by wobba** [comment]
A sample on how to pass the IWebPartContext to a component would also be useful.

**Comment by wictorwilen** [comment]
It works fine by passing the HttpClient. I use this pattern extensively:

    public constructor(client: HttpClient) {
      ...
    }

**Comment by wobba** [comment]
Wictor, how do you pass that a constructor arg with React when the component has:

`React.createElement(ComponentName, {prop1,prop2})`

..and I'm learning along the way here, being a React newbie :)

**Comment by waldekmastykarz** [comment]
@wictorwilen what if you wanted to test your component? How would you pass the mock instance?

**Comment by wictorwilen** [comment]
@waldekmastykarz - I've used different constructors for my mock objects and production objects. The above sample is the production constructor, where my mock constructor looks like `constructor()`.

**Comment by waldekmastykarz** [comment]
@wictorwilen does that mean that you have to have two code paths to support both mocked and production HttpClient, similarly to what we've seen in the samples?

**Comment by wictorwilen** [comment]
@waldekmastykarz - yes, I've done that. Since you can't define the constructor in the interface definition you can have different constructor signatures. Should you? It depends. If you want them to be exactly the same then you could just pass in the httpClient property of the context object and not use it...

**Comment by wictorwilen** [comment]
@wobba 

In your React component, first import the client
```
import { HttpClient } from '@microsoft/sp-client-base';
```

Then modify the props interface
```
export interface IReactDemoProps extends IReactDemoWebPartProps {
  httpClient: HttpClient;
}
```
And finally in your web part `render` method:

```
const element: React.ReactElement<IReactDemoProps> = React.createElement(ReactDemo, {
      description: this.properties.description,
      httpClient: this.context.httpClient
    });
```

**Comment by wobba** [comment]
@wictorwilen That's how I do it, and what @waldekmastykarz told be to do. Pass it via the Props interface declaration. I actually pass in the full context object, to be sure I have what I need :) But seems a bit dirty to mix data properties and utility properties in a way.

**Comment by wictorwilen** [comment]
@wobba - I'm not an expert on React, but that is how I pass parameters. And for web-parts it is designed in that way that you have two interfaces; one for the WP properties, and en extended interface for the React properties. 

An alternative would be to use the experimental [React context](https://facebook.github.io/react/docs/context.html).

(Personal thoughts) I think this is an example how React is focusing on building UX fast and efficient and does not have dependency injection and similar - which we are used to when building "proper" solutions :-)

**Comment by wobba** [comment]
@wictorwilen Exactly my thoughts as well.. where in the something is the DI :-D Just plug it baby.

**Comment by waldekmastykarz** [comment]
If HttpClient implemented an interface such as `IHttpClient` then in the Web Part you could pass the instance of `this.context.httpClient` and in your tests you could have a mock client that you could use to instantiate the component with. In theory that should also allow you to use the component with other shapes or maybe even outside of SharePoint as well 😄

**Comment by patmill** [comment]
@pgonzal - maybe a page describing ServiceScopes and HttpClient is in order.

**Comment by pgonzal** [comment]
The ServiceScope API is our solution for this type of problem, e.g. if you look at the (unreleased) Canvas constructor from **sp-client-preview**, it receives the httpClient via a ServiceScope and passes it down to the :
 
```typescript
/**
 * SharePoint Client-side Applications can use the SharePoint Canvas to enable rich content authoring
 * as part of their experience. The SharePoint canvas provides Rich Text Editing capabilities, SharePoint
 * Client-side WebPart aggregation and hosting, and a beautiful railed design experience.
 *
 * @unreleased
 * @public
 */
export default class Canvas {
    private _container;
    private _coreComponent;
    private _store;
    /**
     * Construct a new instance of the Canvas.
     *
     * @param serviceScope - A context object that will provide dependencies needed by the canvas and
     *   any web parts that it loads.
     * @param container - The host DOM container for the Canvas. When render() is invoked the Canvas will
     *   render into 'container'.
     * @param mode - The initial DisplayMode of the Canvas.
     * @param serializedCanvas - Optional. Used to initialize a Canvas' state when render() is invoked. The
     *   string must have been created by a previous instance of the Canvas. If absent, an empty Canvas will
     *   be rendered. If present, the Canvas will rehydrate to represent the state of the Canvas when
     *   serialized.
     * @param handleCanvasChanged - Optional. When text is editied or canvas controls are added/removed this
     *   callback will be invoked. Web parts will also invoke this call back when there is interaction with
     *   the web part.
     */
    constructor(serviceScope: ServiceScope, container: HTMLElement, mode: DisplayMode, serializedCanvas?: string, handleCanvasChanged?: () => void);
```
 I wrote up a full tech note here:

https://github.com/SharePoint/sp-dev-docs/wiki/Tech-Note:-ServiceScope-API

**Comment by pgonzal** [comment]
I am closing this bug; please reopen it if you have more questions.  Thanks!

**Comment by wobba** [comment]
@pgonzal  Just want to thank you for that tech note which was a very good read! So I'm guessing you will release some common service keys to be used, but passing HttpClient explicitly as you state for that case works out fine as well. Since you write in the comment that you yourself get HttpClient from a service scope, but the tech note says to pass it explicitly. Potatoe / Potato ;)
