### ISSUE TITLE
SPComponentLoader error in SPFx application extension

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#1180]
_From @mhintner on November 8, 2017 22:0_

#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

I'm using SPComponentLoader to load SP.js and other files in a SPFx application extension. This works fine, if the extension is loaded on the start page of a web. But as soon as the extension is loaded on e.g. a document library (/Shared Documents/Forms/AllItems.aspx), the SPComponentLoader produces an unknown error when loading module. 
This is the code  that is supposed to work on every page:

SPComponentLoader.loadScript('/_layouts/15/init.js', {
                globalExportsName: '$_global_init'
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
                    globalExportsName: 'Sys'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Taxonomy.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): Promise<{}> => {
                return SPComponentLoader.loadScript('/_layouts/15/SP.Search.js', {
                    globalExportsName: 'SP'
                });
            })
            .then((): void => { 
                //code here
            })
            .catch((reason: any) => {
                //...log error
            });

_Copied from original issue: SharePoint/sp-dev-fx-extensions#71_

**Comment by VesaJuvonen** [comment]
Hi @mhintner, could you provide more details on the "unknown error" which you are getting. Potentially share the package in the bug if possible for easy repro. Just trying to get this processed asap with our internal process. Thx.

**Comment by VesaJuvonen** [comment]
Hi @mhintner, any change getting additional details on the exception? - We can't really guess what's happening until we have the exception details for repro and investigation. Thx.

**Comment by mhintner** [comment]
Hi @VesaJuvonen, the error message is the following:
"No define call for /_layouts/15/init.js
http://requirejs.org/docs/errors.html#nodefine"

This error occurs when loading the extionsion on a document library, same code works fine on a modern page.

/Markus

**Comment by pkmelee337** [comment]
Hi @VesaJuvonen,

Today I did receive the exact same error when loading the init.js on a document library. (happens in the modern site document library too) On my overview page it is working fine.

require-951f856e.js:1 Uncaught (in promise) Error: No define call for https://{tenant}.sharepoint.com/sites/{sitecollection}/_layouts/15/init.js
http://requirejs.org/docs/errors.html#nodefine
    at makeError (require-951f856e.js:1)
    at Object.completeLoad (require-951f856e.js:1)
    at HTMLScriptElement.onScriptLoad (require-951f856e.js:1)

**Comment by mcmynn83** [comment]
@mhintner - Could you attach a package that is having this error as that is the easiest way for us to investigate the issue.  Or you can send the app pacakge that you upload to the app catalog to grahamc @ microsoft.com and just include the git hub issue number (1180).

**Comment by VesaJuvonen** [comment]
Potential duplicate of #1117.

**Comment by VesaJuvonen** [comment]
@mhintner - any change for getting repro as a package on this one. Would significantly help us in investigating things and would reduce the resolution time. Thx.

**Comment by mhintner** [comment]
Hi Vesa,

just sent the files to Graham.

/Markus


Von: Vesa Juvonen [mailto:notifications@github.com]
Gesendet: Donnerstag, 25. Januar 2018 18:43
An: SharePoint/sp-dev-docs <sp-dev-docs@noreply.github.com>
Cc: Markus Hintner <markus@hintner.cc>; Mention <mention@noreply.github.com>
Betreff: Re: [SharePoint/sp-dev-docs] SPComponentLoader error in SPFx application extension (#1180)


@mhintner<https://github.com/mhintner> - any change for getting repro as a package on this one. Would significantly help us in investigating things and would reduce the resolution time. Thx.

**Comment by VesaJuvonen** [comment]
thx Markus, appreciated.

**Comment by mpasarin** [comment]
A similar issue related to loadScript was fixed by end of January, and this one doesn't reproduce anymore with the current bits.
I am closing this issue, but feel free to re-open if that still happens to you.
