### ISSUE TITLE
Create a team site using the new site design is not working working

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#1182]
I have added the site script and site design using PowerShell to my tenant as stated in this documentation https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design. 

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expecting the site is created with Customer Tracking List and columns,

#### Observed Behavior
When i click finish on create a new team site using the new site design,  i didn't get any pane on the right hand site which indicate that your script is being applied. I also refresh the new site nothing happen, I have checked the site contents and no new list created,

#### Steps to Reproduce
1. Add the site script and site design using the guideline stated here https://docs.microsoft.com/en-s/sharepoint/dev/declarative-customization/get-started-create-site-design 
2. Create new team site
3. In the Choose a design drop down, select your site design "Contoso customer tracking"
4. Enter the site name and click Next
5. Click Finish

**Comment by VesaJuvonen** [comment]
thx @muges01 for reporting. We seem to be still missing some final go-live settings on this one which should happen in today / upcoming days.

**Comment by muges01** [comment]
Thank you @VesaJuvonen. I tried to create the site again today but it is still not working, Do i need to re-create the existing site script and site design? Or wait for another couple of days?

**Comment by VesaJuvonen** [comment]
This capability has still some challenges so it's not properly enabled world-wide. We should get the issue resolved by end of today, so you should see things working on following days. Sorry for the inconvenience. I'll update this issue or close it when things have been confirmed and working as expected.

**Comment by muges01** [comment]
Thank you @VesaJuvonen for the updates. i'll test again tomorrow. :)

**Comment by expiscornovus** [comment]
@VesaJuvonen, just a quick question. Does this also apply for the Site designs of Communication sites?

**Comment by VesaJuvonen** [comment]
This is currently an issue for both Group associated team sites and communication sites. We should get the capability fully functional in a matter of hours / few days, but don't have exact ETA currently.

**Comment by expiscornovus** [comment]
@VesaJuvonen good to know. Thanks for your quick reply 👍

**Comment by muges01** [comment]
Hi @VesaJuvonen,
Any updates on this?

**Comment by expiscornovus** [comment]
@muges01 it is working on my (targeted release) tenant. I get the pane for Team Sites as well as Communication sites.

**Comment by muges01** [comment]
Hi @expiscornovus, 
I just tested it again and it is working now. :)

**Comment by VesaJuvonen** [comment]
Closing based on the above chat. We just announced today that it's now 100% in the first release.

**Comment by muges01** [comment]
Thank you @VesaJuvonen .
