### ISSUE TITLE
Don't seem to have a generator with the name “@microsoft/sharepoint” installed.

### ISSUE THREAD

**Issue by polymer940c** [SharePoint/sp-dev-docs#1183]
Following the instruction Microsoft doc on setting up environment: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment: 

I come to the problem as title when I run ```yo @microsoft/sharepoint``` => ```Error @microsoft/sharepoint``` 

I am thinking maybe it is installed in another dir. But I guess that is not the case?
```
npm -g list --depth=0
/Users/MyUserName/.nvm/versions/node/v6.12.2/lib
├── @microsoft/generator-sharepoint@1.4.0
├── gulp@3.9.1
├── npm@3.10.10
└── yo@2.0.0
```
runing yo shows the follow: 
``` 
yo
? 'Allo USER! What would you like to do?
  Run a generator
  ──────────────
❯ Install a generator
  Find some help
  Get me out of here!
```
Try searching  @microsoft/sharepoint with yo, install a generator, ==> nothing; 
does  @microsoft/sharepoint generator no long exist?  (But I can see that I have it installed, wth)

**Comment by polymer940c** [comment]
Found solution. 
For anyone who might want to know: 
``` yo doctor```  => no errors 
```export NODE_PATH=$HOME/.node/lib/node_modules/``` then ``` yo doctor``` ==> Errors! 
enter suggested: ```export NODE_PATH=$NODE_PATH:/Users/slickstyles/.npm-global/lib/node_modules``` 
```yo``` ==> magic has appeared

**Comment by purtuga** [comment]
For anyone that might find this thread: As @polymer940c  indicated, ensure that your `NODE_PATH` is set to include the path to your global nodeJS `node_modules` folder.... that folder is under your nodeJS installation folder.
