### ISSUE TITLE
Known issues link gets 404 Error

### ISSUE THREAD

**Issue by StefanSchoof** [SharePoint/sp-dev-docs#1185]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Go to https://github.com/SharePoint/sp-dev-docs/wiki/Why-SPFx, click on the right menu on "Known issues". This should show a list of "Known issues"

#### Observed Behavior
I got an 404 page at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/known-issues

#### Steps to Reproduce
See above

**Comment by VesaJuvonen** [comment]
Wiki also updated to point to pages in https://docs.microsoft.com/en-us/sharepoint/dev. Thx for the issue reporting.
