### ISSUE TITLE
includeClientSideAssets in SharePoint On Prem

### ISSUE THREAD

**Issue by StefanSchoof** [SharePoint/sp-dev-docs#1192]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug (in documentation)
- [ ] Additional article idea

#### Expected or Desired Behavior
The [cdn documenation](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md) mentions the `includeClientSideAssets` property, but in the spfx Version for SharePoint 2016 (1.1) this does not exits:

```
ERROR: Error parsing file 'package-solution.json'
(#/solution) Additional properties not allowed: includeClientSideAssets
```

The documentation should mention how this should be done in the Version for SharePoint OnPrem or if not possible this should clearly documented.

**Comment by VesaJuvonen** [comment]
thx @StefanSchoof for the input. We have now added notes around `includeClientSideAssets` attribute to following articles. This should clarify the supported scenarios for on-premises. 

- https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn
- https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support#hosting-your-sharepoint-framework-solution-for-on-premises-deployment
