### ISSUE TITLE
es6-collections being removed and lodash working: should we stop using the subset?

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#1196]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
In version [1.4.0](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-for-SPFx-Package-Version-1.4), @types/es6-collections has been removed. The direct impact is that lodash seems to be working fine now in SPFX projects. (used it in a webpart today, haven't tried extensions)  
Since that's working, that brings a couple of questions:
- will the subset package be deprecated?
- should the doc and the generator be updated to avoid leverage the subset? (at least for online)

**Comment by iclanton** [comment]
We still recommend that you use the subset for performance reasons. Only one copy of the sp-lodash-subset package is loaded on the page, meaning that your bundle can be smaller by not including the lodash code. We have no plans to deprecated the sp-lodash-subset package.

The es6-collections @types package was removed in favor of the TypeScript compiler's version of the typings, but support for es6-collections remains the same.
