### ISSUE TITLE
.SPCanvas-canvas Width 100% 

### ISSUE THREAD

**Issue by halfice** [SharePoint/sp-dev-docs#1197]
I am trying to make width full when and remove quick launch from modern page. I am using web part to remove the quick launch but on the same time I want .SPCanvas-canvas to be width 100%.

 jQuery("nav[role='navigation']").hide();
        jQuery("div[class^='searchBox_']").hide();
        jQuery("div[class^='pageContainer_']").css("left", "0px");
        jQuery(".SPCanvas-canvas").css({ 'max-width': '100%!important' });
        jQuery(".SPCanvas-canvas").css("width", "100%!important");

above is the code to make .spcanvas to 100%. if someone can help.

**Comment by VesaJuvonen** [comment]
Hi @halfice, unfortunately, this scenario is not supported by modern experiences. If you need to do full width with SharePoint Online, you should be using classic experience. It's basically not supported to modify the styles dynamically in the modern UIs and there's no support for the 100% wide setup - except though in communication sites natively.

There might be future capabilities, but this is the current status.
