### ISSUE TITLE
SSL certificate warning in Chrome

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1199]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

When navigating to any page in SharePoint Online, Google Chrome shows the following warning in the dev console:

```
The SSL certificate used to load resources from https://spoprod-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```

The warning has been observed in Chrome Version 63.0.3239.108 (Official Build) (64-bit) on a macOS.

**Comment by gabbsmo** [comment]
Any ETA on this? Will users of legacy versions of UI fabric have to take any action? From my package.json:

```
{
  "dependencies": {
    "office-ui-fabric": "https://github.com/OfficeDev/office-ui-fabric-core.git#release/2.6.1",
    "office-ui-fabric-core": "~5.1.0"
  }
}
```

**Comment by braingu-matt** [comment]
Any update on this @VesaJuvonen ?

**Comment by andrewconnell** [comment]
Been a while since this has been opened, many Chrome & SPFx versions ago. Still an issue? Can't repo...
