### ISSUE TITLE
SharePoint Online won't run workbench.aspx

### ISSUE THREAD

**Issue by foconnor-DS** [SharePoint/sp-dev-docs#12]
Followed the instructions to upload Workbench.aspx to a document library. I've added the ClientSideApplicationId column as well. I get this error:

> Sorry, something went wrong
> The requested operation is part of an experimental feature that is not supported in the current environment.
> TECHNICAL DETAILS
> 
> 
> Troubleshoot issues with Microsoft SharePoint Foundation.
> Correlation ID: 06df9a9d-5054-2000-1604-1dcab5d4e85c
> 
> Date and Time: 8/17/2016 8:48:19 PM

Do I need to op into something? I'm already on bleeding o365 releases. Or perhaps roll-out will take a while?

**Comment by foconnor-DS** [comment]
Read previously closed issue about needing a pure Developer Tennant. Closing.

**Comment by mauricionr** [comment]
Exactly wich previous issue?

**Comment by panjkov** [comment]
@mauricionr This one https://github.com/SharePoint/sp-dev-docs/issues/3 
You need to create DEV tenant, and another DEV site collecition in it (or to enable scripting on default DEV site collection in DEV tenant as described here https://github.com/SharePoint/sp-dev-docs/issues/12)

**Comment by foconnor-DS** [comment]
@mauricionr The previous issue was #3. However, it seems that issue now references this issue. So we've achieved recursion. 

I'll just iterate for everyone else that runs into this issue, you have to create a recent "Developer Tenant". This is different than your standard ( possibly Partner ) Tenant.  You may even have to use a new E-mail address, or at the least do this process in an InCognito window. This will make you a completely new "something.onmicrosoft.com" tenancy. Once you do that, the new Site Collection will accept and run the Workbench.aspx.

**Comment by mauricionr** [comment]
@panjkov @foconnor-DS i did the setup again and got the same error :cry: 

![image](https://cloud.githubusercontent.com/assets/2263551/17864845/227170d0-6876-11e6-8451-9ac6a523f355.png)

**Comment by panjkov** [comment]
Are you 100% sure that you created new tenant using "Office 365 Developer" SKU?

Get Outlook for iOS




On Mon, Aug 22, 2016 at 7:39 PM +0200, "Mauricio nunes dos reis" <notifications@github.com> wrote:





@panjkov @foconnor-DS i did the setup again and got the same error :cry:

![image](https://cloud.githubusercontent.com/assets/2263551/17864845/227170d0-6876-11e6-8451-9ac6a523f355.png)

**Comment by mauricionr** [comment]
@panjkov now it works, i created a new Tenant with Office 365 Developer, i was trying with my partner subrscription and a subscription from my friend! 

really thanks!

:smiley:

**Comment by chakkaradeep** [comment]
@mauricionr Glad it is working for you! Let us know if you still have any trouble loading the workbench.

**Comment by mauricionr** [comment]
@chakkaradeep on windows 10 insider preview every thing works fine, but on ubuntu i got 404 after run gulp serve #9

**Comment by westerdaled** [comment]
Hi 

For some reason all I see when I try to run the workbench.aspx on my  Dev tenant in either Chrome or Edge: is a nice GIt hub document page! 


![image](https://cloud.githubusercontent.com/assets/937208/18870016/b88b9496-84a6-11e6-9e0e-b9726f7c1b77.png)

- No script warnings shown 
- tried also private browser sessions
- temporarily disabled antivirus
- I note in SP admin settings - Custom Script 
Prevent users from running custom script on personal sites
Prevent users from running custom script on self-service created sites
However, I am not using either. 

 I think there is some execution permissions issue going on but this the first time I have seen this?

**Comment by wictorwilen** [comment]
@westerdaled I think you downloaded the Github page and not the workbench. Make sure that you download the RAW page, and not just rightclick and save the workbench.aspx listing in Github.

**Comment by westerdaled** [comment]
@wictorwilen  Doh! Next time it will be quicker to read the instructions!  All good, now I do see the script errors. Thanks Daniel
