### ISSUE TITLE
PropertyPaneDropdown and disableReactivePropertyChanges

### ISSUE THREAD

**Issue by OlivierCC** [SharePoint/sp-dev-docs#120]
When I defined the web part properties as not reactive, the Apply button is not enabled on a change on a property of type DropDown. It's working with PropertyPaneSlider, PropertyPaneTextField or PropertyPaneToggle but not with a PropertyPaneDropdown.

**Comment by patmill** [comment]
Thanks @OlivierCC - this is a dupe of https://github.com/SharePoint/sp-dev-docs/issues/46
