### ISSUE TITLE
SharePoint – Refresh Form Digest Value using Angular 2 and REST

### ISSUE THREAD

**Issue by VidhiBartariya** [SharePoint/sp-dev-docs#1200]
#### Category
- [ ] Question

#### Expected or Desired Behavior
How can we refresh  Refresh Form Digest Value using Angular 2?
I have a post request like below:
  public getHeadersPUT() {
        var headers = new Headers();
        var digest = document.getElementById("__REQUESTDIGEST") as HTMLInputElement;
        headers.set('Accept', 'application/json;odata=verbose');
        headers.set('Content-Type', 'application/json;odata=verbose');
        headers.set('X-RequestDigest',digest.value);
                
        headers.set('X-HTTP-Method', 'POST');
        headers.set('Access-Control-Allow-Headers', 'Content-Type');
        headers.set('IF-MATCH', '*');
        headers.set('X-HTTP-METHOD', 'MERGE');
        return headers;
    }

But using this my page has expired after 20 mnts and i'm not able to submit my data i want  "Refresh Form Digest Value" as same as angular js in below URL:
http://blog.wombit.se/2014/06/12/refresh-form-digest-value-using-angularjs-and-rest/
Our client wants the same 
Can anybody help me out on this?

Thanks for your contribution! Sharing is caring.

**Comment by waldekmastykarz** [comment]
As you experienced yourself: using the request digest token stored in the page is unreliable as you can't tell how long the page has been open and if the token is still valid. You can always obtain a fresh token by issuing a POST request to `/_api/contextinfo`.
