### ISSUE TITLE
Is there a way to check if document has a preview?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1202]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a way to check if the file in the document library has a preview?
Let's say, I have a .doc file and .app file in my doc library.
.doc file will be opened in a popup and the `href` in the Name column will be similar to `#<current_query_string>&id=<path_to_doc>&parent=<parent_folder_path>`.
.app file will be downloaded and the `href` will be `<relative_path_to_the_file>`.

I want to know if I can call some REST API or something like that to check if a specific document has a preview (either by extension, or by document library/list item ids)...

**Comment by VesaJuvonen** [comment]
No easy answers here immediately. We'll put this to our backlog for engineering but would not expect super fast response due to priorities.

**Comment by AJIXuMuK** [comment]
@VesaJuvonen 
Not a blocker, so that's fine :)
`#<current_query_string>&id=<path_to_doc>&parent=<parent_folder_path>` will behave correctly even if there is no preview.

**Comment by russgove** [comment]
could you do something with getwopiframeurl?

**Comment by AJIXuMuK** [comment]
@russgove 
Not actually...
You can use `getwopiframeurl` and check if there is a url returned.
or you can use `window.g_listData.ListData.Row[item_index].ServerRedirectedEmbedUrl`.
But it works not for everything. For example, .cs file has a preview. But `getwopiframeurl` and `window.g_listData.ListData.Row[item_index].ServerRedirectedEmbedUrl` both will be empty
