### ISSUE TITLE
SuiteBar: Username of external user dissappears on modern pages

### ISSUE THREAD

**Issue by robinmeure** [SharePoint/sp-dev-docs#1206]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Username should be visible on all pages. 

#### Observed Behavior
Only on the library/list and viewlsts.aspx the username is shown. When navigating to a modern page, the username disappears from the SuiteBar

#### Steps to Reproduce
1. Create a communication or group site,
2. Add an external user
3. Logon as the external user
4. Notice that on the welcome page/home page of the site the username is no longer present (only the gear and question mark icons are visible)
5. When navigating to site contents or documents, the username appears again.

![username](https://user-images.githubusercontent.com/17588092/34610717-96cf9164-f222-11e7-9bc3-fa323cf0a9f6.png)

**Comment by mpasarin** [comment]
This is not really a developer issue, so this is not the best channel for this.
Your best option is to contact support, although this problem was not reproducible on our side.
