### ISSUE TITLE
Could not run 'sudo npm install -g @microsoft/generator-sharepoint'.

### ISSUE THREAD

**Issue by naveen9026** [SharePoint/sp-dev-docs#1209]
Below is the command which I am running in my mac.(I tried the same command without sudo as well. But response is same.)

sudo npm install -g (AT)microsoft/generator-sharepoint
(Instead of (AT) replace with @)
Below is the error or response:

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for timed-out

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Naveen/.npm/_logs/2018-01-06T19_21_52_530Z-debug.log

And eventually I am not allowed to run 'yo (AT)microsoft/sharepoint'. (Instead of (AT) replace with @)I am getting below error

"Error (AT)microsoft/sharepoint (Instead of (AT) replace with @)

You don't seem to have a generator with the name “(AT)microsoft/sharepoint” (Instead of (AT) replace with @) installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install (AT)microsoft/generator-sharepoint.
(Instead of (AT) replace with @)

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system."

Please help me in resolving this issue.

**Comment by joelfmrodrigues** [comment]
If you run only 'yo', so you see the generator installed?

**Comment by andrewconnell** [comment]
Still an issue?
