### ISSUE TITLE
How to change the spapp icon ?

### ISSUE THREAD

**Issue by OlivierCC** [SharePoint/sp-dev-docs#121]
Is it possible to change the default icon for the generated App SharePoint ? Is there an existing setting in the package-solution.json file ?

**Comment by patmill** [comment]
Yes - take a look at the officeFabricIconFontName property in your webpart.manifest.json file.

**Comment by weshackett** [comment]
Take a look at @waldekmastykarz article here for even more details https://blog.mastykarz.nl/specify-icon-sharepoint-framework-client-side-web-part/

**Comment by OlivierCC** [comment]
Thanks for your answer. I seen the excellent blog post from  @waldekmastykarz but in fact i'm looking for a method to change the icon of the SPAPP that appears on the "Site contents" screen or in the App catalog, as show in the following attached capture.
![spapp icon](https://cloud.githubusercontent.com/assets/16818544/18145382/514661c0-6fcb-11e6-8d11-b78a75bec38e.png)

**Comment by weshackett** [comment]
Those can normally be set be editing the entry in the app catalog apps for sharepoint list. Not tried for an spfx app package but it goes into the same place so might work.

**Comment by OlivierCC** [comment]
Hi Wes, yes you're right, I can change the icon of the App in the App Catalog. I tested with a SPFx App and it's working too (see the following screenshots).
![spappicon](https://cloud.githubusercontent.com/assets/16818544/18173588/7aa4f94c-706a-11e6-9606-1cf50eac1817.png)
![spappicon2](https://cloud.githubusercontent.com/assets/16818544/18173589/7aa84ad4-706a-11e6-8031-087319d664cb.png)

But the problem is that I can also built SPAPP to distribute it in the global App Catalog, and I don't want to have to ask to each SP Admin to modify the icon.

In the old SharePoint App built with Visual Studio, we have got a Icon property in the App Manifest (see following screenshot). 

![spappicon3](https://cloud.githubusercontent.com/assets/16818544/18173693/de9fb824-706a-11e6-9103-a28d63846780.jpg)


My suggestion is to integrate a icon property in the package-solution.json file, to integrate it the generated App manifest. Do you know if it's possible or plan in a next release ? Thanks

**Comment by manishgarg1** [comment]
VSO #243419

**Comment by mpasarin** [comment]
In order to change the icon on the tile, you should do the following:

On config/package-solution.json you can add:
`{
  "solution": {
    ...
    "iconPath": "a/path/to/the/icon.png",
   ...
  }
  ...
}`

The icon path is the relative path on the sppkg. You can drop the icon in /sharepoint/ folder for that (assume /sharepoint/ is the root folder, for all purposes).
Note that this affects only the tile in site contents, but not the icon of the web part in the toolbox.

**Comment by jusper-dk** [comment]
It does not work for me. An icon is included into a package but after uploading the app into AppCatalog, it is not recognized as an app: no errors, but SharePoint cannot find web parts, determine its version and does not allow to deploy it.

**Comment by shaipetel** [comment]
This needs to be documented here: https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/notes-on-solution-packaging

Also, anyone had any luck getting this working - or any luck pre-setting the app description text as well?

**Comment by shaipetel** [comment]
I'm at the same siguation as @jusper-dk . The image (a png file) is in the package, and referenced correctly it seems. If I mis-spell it or the file doesn't exist, the build fails.
So, it seems it is done correctly and the image went into the package.

However, SherePoint seems to keep loading the default icon.
Setting the icon and description is VERY important to my product manager...
