### ISSUE TITLE
How to access the new SharePoint Admin Center?

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#1210]
Hi everyone, 

How can i access the new SharePoint admin centre? 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Thanks for in advanced.
Muges

**Comment by SumitRAgrawal** [comment]
Hello Mugilan,

Valid admin center url is https://tenant-admin.sharepoint.com for SharePoint Online.

**Comment by muges01** [comment]
Hi @SumitRAgrawal,

I want to know how to access the new SharePoint admin centre not the old one.
Please refer to this article https://techcommunity.microsoft.com/t5/SharePoint-Blog/Introducing-the-new-SharePoint-Admin-Center/ba-p/70294 

Thank you

**Comment by VesaJuvonen** [comment]
There will be "preview admin" links in the Admin UIs when this capability is available. Your tenant has to be first in the preview mode and whenever the capability is enabled for preview tenants, it will be then available for you.

**Comment by muges01** [comment]
Hi @VesaJuvonen ,
Thank you for your reply. Yes, my tenant is in preview mode. Any idea when this capability will be available?
