### ISSUE TITLE
NPM version?

### ISSUE THREAD

**Issue by umairn** [SharePoint/sp-dev-docs#1211]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In following article it mentions to install version 3.0 of NPM 

https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md

#### Observed Behavior
When I run the following command: 

gulp bundle --ship

then i get following error:

Error: Additional properties not allowed: includeClientSideAssets

On the searching the solution for the error I found following link:

Solution: https://github.com/SharePoint/sp-dev-docs/issues/1126

Should the document be updated to use npm version 4 instead of 3.0?

**Comment by waldekmastykarz** [comment]
The error you're describing is not related to the npm version you're using. What version of the SharePoint Framework Yeoman generator are you using (check by running in the command line `npm ls -g --depth=0`)? Are you building a project for on-premises or online?

**Comment by nickpape-msft** [comment]
@umairn Are you still seeing this issue?
