### ISSUE TITLE
Field Customizer: call onRenderCell when user switches to another list view?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1218]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Now if the user switches to another list view using command bar the Field Customizer's `onRenderCell` won't be called.
But I'm pretty sure that there might be scenarios (and I have such a scenario in my practice) when the field should be rendered in different way in different views...

Do you plan this type of functionality? Is it a bug or should be reported as enhancement?

**Comment by mcmynn83** [comment]
Thanks for the feedback.  Unfortunately we do not do this today.  Could you please open a new issue on uservoice and give the scenario that you are interested in that needs render to be called on view change so we can understand the deficiency in the way it currently works.

**Comment by AJIXuMuK** [comment]
[https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/32972992-field-customizer-call-onrendercell-when-switching](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/32972992-field-customizer-call-onrendercell-when-switchingl)
