### ISSUE TITLE
HelloWord deploy to CDN tutorial improvement suggestion

### ISSUE THREAD

**Issue by OlivierCC** [SharePoint/sp-dev-docs#122]
In the excellent tutorial called "HelloWord, Deploy to CDN", you mention that we can define the cdnBasePath as following :

{
  "cdnBasePath": "http://spfxsamples.azureedge.net/helloworld-webpart/"
}

The problem is that with Office365, the https protocol is used and then the user has a warning error during the execution. I suggest to specify that or the define the path as follows (seems to work) :

{
  "cdnBasePath": "//spfxsamples.azureedge.net/helloworld-webpart/"
}

**Comment by manishgarg1** [comment]
VSO #243421

**Comment by nickpape-msft** [comment]
Fixed in the documentation!
