### ISSUE TITLE
Issue in AutoFill values for people picker 

### ISSUE THREAD

**Issue by RachaRatan** [SharePoint/sp-dev-docs#1221]
I have user people picker which was suggested on below link.

https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md

It is binding successfully and working fine. Am able to select users in it.

But now I want to auto fill the same people picker using user value which I get from SharePoint site.

I have check a lot of blogs nowhere I found to auto fill this.

Can anybody help me on this to autofill it or else suggest me any other approach.

my overall requirment to show a people picker control in provider hosted app and I want to use as the same sharepoint people picker.

Getting value from picker.
Autfilling the picker.
change event.
resolved event.
removed event.
 These everything I required.

Thanks.

**Comment by Ashikpaul** [comment]
To store the value to a list from custom people picker, we need to retrieve an id of that person. 
      - You can inspect on the people picker result and check your id.
You can use this id to auto populate.

I am not sure because I haven't tried. Just an idea.
Hope this helps.
