### ISSUE TITLE
Where do we store configuration for extensions

### ISSUE THREAD

**Issue by SamCrewdson** [SharePoint/sp-dev-docs#1222]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
This is a question about where we would store values for an extension.  Specifically, we have developed a redirect extension which will look up a list of values in a SharePoint list on every page load and we have performance concerns about this approach on a busy site.

#### Observed Behavior
-With SPFx we can store web part data in the page itself - good for performance.
-We can store re-usable web part information (i.e. license key or similar) at the tenant level.

What we seem to be missing is a middle option, a way to store site-level configuration in a way that lends itself to:

1) Straightforward updates and configuration (as with a redirect extension).
2) Caching for performance.  

Is there a way to do this that we aren't thinking of?  Or does this become more of a feature ask?

**Comment by andrewconnell** [comment]
Each one has properties you can persist with it similar to web parts, or you could store them as [tenant properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties)

**Comment by SamCrewdson** [comment]
Thanks Andrew.  Would that afford me the ability to edit the properties that I want to persist?  Giving a little background on our first use case:

We have just completed a web part extension that allows us to redirect from a source URL to a target URL either explicitly or by wildcard.  Good for reorgs, site splits, or entire site renames (until we get the site rename fature eventually).  Today we've built a UI that populates a list with this data and we are very pleased with its functionality.  The only thing that is making us hesitate at deployment time is the performance impact of querying the list every page load.

Because we want a site owner to be able to edit the list on the fly w/o IT intervention, we don't feel like the tenant-level properties is the right place for this.  What are your thoughts?

**Comment by russgove** [comment]
you could create a workflow that runs whenever an item in the list changes. the workflow  could  read ALL the items in the list, format them a jsom, and set them on the webs propertybag.

**Comment by luismanez** [comment]
Another option is to cache your query results in the browser Storage (localStorage or sessionStorage). The PnP JS library has support to cache when running a Query:

```js
pnp.sp.web.lists.getByTitle("Tasks").items.top(5).orderBy("Modified").usingCaching().get().then(r => {
    console.log(r)
});
```


https://github.com/SharePoint/PnP-JS-Core/wiki/Caching

**Comment by andrewconnell** [comment]
@SamCrewdson ...

> Thanks Andrew. Would that afford me the ability to edit the properties that I want to persist? 

As a tenant admin, yes... tenant admins can only edit the properties, making them a bit more protected. But your scenario sort of excludes these as you want site owners to do this.

> The only thing that is making us hesitate at deployment time is the performance impact of querying the list every page load.

I wouldn't be concerned at all about this. Just open the network tab on the dev tools and look at the XHR requests... one small call like this wouldn't concern me.

**Comment by mcmynn83** [comment]
@SamCrewdson - Are you satisfied with the answer?  If not please open an issue on github asking for site collection properties.
