### ISSUE TITLE
Assets not getting copied to ClientSideAssets

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#1223]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After deploying an app to app to a site collection app catalog, the assets should be copied to the clientSideAssets  library in a reasonable amount of time.
#### Steps to Reproduce
Sometimes it takes  over an hour to get copied. I have found that emptying the recycle bin, and then redeploying the app often times helps.  T

We need to know how to get apps fully deployed in a short timeframe when fixing critical production issues.

**Comment by russgove** [comment]
I deployed a sppkg  beofr i went home last night. Came in this morning and assests were still not copied. Deleted the app from the catalog and redpeloyed the exact same sppkg. The clientsideassests  were copied in seconds.

**Comment by mcmynn83** [comment]
@russgove  - Thank you for reporting the issue.  Assets should always get copied as part of the package being deployed (ie synchronously).  Could you send a correlation ID for a request made when you deploy the app (ie click OK on the trust dialog)?  To get this just turn on a network trace and the request made will have an SPRequestId in the response header.  If you send us that we can investigate what went  wrong.

**Comment by russgove** [comment]
Hi, It started happenning again the traceCorrellationId is TraceCorrelationId=a1c9419e-f03b-4000-b2a8-187192ce1ef4. The full response is 
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Set-Cookie: rtFa=sqFCPja1/7rXHglqdo974dEfostC8eAvj4xqg8BHA94mOUVFQzA3RTYtRjZGOC00RTI0LUI0QzctQzU4Njg1MDBCNDE3aoBevfLNH9GOP5WIiGBkRCAQIdqhFCUXNMbJYE3wiF8LPOKO1jb9HY/dxyGiY0h2mvLSs3cNMUypdSKzpE2VBAkhOV/kATbHlgJWhTNFsN9fBOx3PzZ9ZuJkGdNFY3be86VgbvpH4SNg8Zpp6M+ZUyNnrZFtuP1JXHRWPPY5f15CJezK/1NRGv49zTJvkoTbHT6RZmoxDGX/ddXzpkLrtqYoIgLtyesAqn5ANiWQQGURfG9kHZrBiMk0fMwxM2xpIjQjB1QY7FjM7IWgrj6RJd87ZuzX53Xx1AHXsc+pktAzZlg1Eil8WgpeB8+tU1rW4tUKwm6xL8aXQS09Ag8Rp0UAAAA=; domain=sharepoint.com; path=/; secure; HttpOnly
Set-Cookie: FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjMsMGguZnxtZW1iZXJzaGlwfDEwMDNiZmZkOGViNGYwMzRAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHJ1c3NlbGwuZ292ZUB0cm9ub3guY29tLDEzMTYwNzU1NzE5MDAwMDAwMCwxMzE1NjQzOTMxMzAwMDAwMDAsMTMxNjExODc3MjAzMTAyOTgzLDAuMC4wLjAsMiw5ZWVjMDdlNi1mNmY4LTRlMjQtYjRjNy1jNTg2ODUwMGI0MTcsLFYyITEwMDNCRkZEOEVCNEYwMzQhMTMxNjA3NTU3MTksMWViYTQxOWUtODAwMC00MDAwLWE1YWQtM2YxODY3NTY2ODYzLDFlYmE0MTllLTgwMDAtNDAwMC1hNWFkLTNmMTg2NzU2Njg2MywsMCxLdXM4TXRMdkRJWHgzR1JwLy8xdGlmS0ZYWEttMisvNEJOcUV3dTU4di9Zc0pNTWt1M2ZnZmYxeUtiRVdTRC9mZGtaTkp1aXR2Zlp2K1ovQVhveFhacFRvMWt5SGlUaU40VTd5QUNyOFl0amFuWVZQUFZZd3hJeDE3SC80QnM5Rm5XOHFmWUxSUFdSR2Q1VWtVb2E5Q3dIN3FwemlUV09FTUhqY1RmN3BVSllKRTR3Y1daUVV1c0hadVNiKzhHRldaTG5JelFVZ0lsSzNQWWMwdWVOMlRkUXFRaWF2S3c0T0ljVkQvZFdhdUNyWC93SFNldmNlaEloUkxrZTNLcW11c2ZzdUdRc2U3K0dWK2ptSXVRei9lQWt1NUMxZEtXZFVjZWZJd1pkRzJOS1VaNU9aazI4ZXNkTXhTaFptQ1crNzBtRW9BaVNUUzNXdk41NWRFZVYxUmc9PTwvU1A+; path=/; secure; HttpOnly
X-SharePointHealthScore: 4
X-SP-SERVERSTATE: ReadOnly=0
SPClientServiceRequestDuration: 2303
SPRequestDuration: 2379
X-AspNet-Version: 4.0.30319
SPRequestGuid: a1c9419e-f03b-4000-b2a8-187192ce1ef4
request-id: a1c9419e-f03b-4000-b2a8-187192ce1ef4
MS-CV: nkHJoTvwAECyqBhxks4e9A.0
X-RequestDigest: 0x500CB376DAE9B61BA0FA352E5D17F28D612026ACAFC3A5EB272230AB6055EC174B783F1D7493C6C2D95B8C9DAAB5D733BE863B53BE552C2F5CA7A67CC8D8784C,18 Jan 2018 17:59:46 -0000
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.7303
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 7937FB0592A94072AD14206BBDEB764F Ref B: BLUEDGE0513 Ref C: 2018-01-18T17:59:48Z
Date: Thu, 18 Jan 2018 17:59:47 GMT
Content-Length: 6100

[
{
"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.7303.1206","ErrorInfo":null,"TraceCorrelationId":"a1c9419e-f03b-4000-b2a8-187192ce1ef4"
},20,{
"_ObjectType_":"SP.ListItem","_ObjectIdentity_":"a1c9419e-f03b-4000-b2a8-187192ce1ef4|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:761d3777-0b2e-490d-ab74-2736980f0cf9:web:99cd2cc1-af2d-4770-b32d-621ee78bdaac:list:40b234b8-4663-482b-be1a-f4477b81204b:item:6,1","_ObjectVersion_":"3","FileSystemObjectType":0,"Id":6,"ServerRedirectedEmbedUri":null,"ServerRedirectedEmbedUrl":"","ID":6,"ContentTypeId":{
"_ObjectType_":"SP.ContentTypeId","StringValue":"0x01010C007A4B945F02AF74439EA28CF0F3A8751C"
},"Created":"\/Date(1516298374000)\/","Author":{
"_ObjectType_":"SP.FieldUserValue","LookupId":9,"LookupValue":"Gove, Russell","Email":"XXXXXXXX"
},"Modified":"\/Date(1516298387000)\/","Editor":{
"_ObjectType_":"SP.FieldUserValue","LookupId":9,"LookupValue":"Gove, Russell","Email":"@@@@"
},"_HasCopyDestinations":null,"_CopySource":null,"_ModerationStatus":0,"_ModerationComments":null,"FileRef":"\u002fsites\u002fTR2\u002fAppCatalog\u002ftr-app.sppkg","FileDirRef":"\u002fsites\u002fTR2\u002fAppCatalog","Last_x0020_Modified":"2018-01-18T17:59:47Z","Created_x0020_Date":"2018-01-18T17:59:34Z","File_x0020_Size":"6767","FSObjType":"0","SortBehavior":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":"0"
},"CheckedOutUserId":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":null
},"IsCheckedoutToLocal":"0","CheckoutUser":null,"FileLeafRef":"tr-app.sppkg","UniqueId":"\/Guid(6f9cc383-fea1-4c77-8cb1-3784a092bb69)\/","SyncClientId":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":null
},"ProgId":"","ScopeId":"{4E7BB633-F155-4062-8735-9D14DBDFED0D}","VirusStatus":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":"6767"
},"CheckedOutTitle":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":null
},"_CheckinComment":"","Modified_x0020_By":"i:0#.f|membership|russell.gove@tronox.com","Created_x0020_By":"i:0#.f|membership|russell.gove@tronox.com","File_x0020_Type":"sppkg","HTML_x0020_File_x0020_Type":null,"_SourceUrl":null,"_SharedFileIndex":null,"MetaInfo":"IsClientSideSolutionCurrentVersionDeployed:BW|true\r\nAppSubtypeID:IW|16\r\nvti_parserversion:SR|16.0.0.7303\r\nSkipFeatureDeployment:BW|true\r\nvti_author:SR|i:0#.f|membership|russell.gove@tronox.com\r\nAppTitleInfo:SW|{\"Default\":\"tr-app-client-side-solution\"}\r\nvti_dbschemaversion:SR|16.0.149.0\r\nvti_sprocsschemaversion:SR|16.0.269.0\r\nAppPackageErrorMessage:SW|No errors.\r\nvti_writevalidationtoken:SW|dT95U5o5a4jLLWkb2mEOknFe7QY=\r\nvti_modifiedby:SR|i:0#.f|membership|russell.gove@tronox.com\r\nIsClientSideSolution:BW|true\r\nAppProductID:SW|91fea9d9-dc10-4be7-8506-b86007adc605\r\nvti_foldersubfolderitemcount:IR|0\r\nContentTypeId:SW|0x01010C007A4B945F02AF74439EA28CF0F3A8751C\r\nvti_title:SW|tr-app-client-side-solution\r\nAppVersion:SW|1.14.0.0\r\nAppMetadataLocale:SW|1033\r\nPackageDefaultSkipFeatureDeployment:BW|true\r\nIsClientSideSolutionDeployed:BW|true\r\nAppSupportedLocales:SW|\r\nExternalContentDomains:SW|https:\u002f\u002flocalhost:4321\u002f ; https:\u002f\u002ftronoxglobal.sharepoint.com\r\nAppSupportURL:SW|\r\nAppPackageHash:SW|34+CLHuLF534hhDM234vqfnTknvDCpwi5Nlmn4V8ufTMpjI9AVE9nir4yaud3PoGvN6iz6G7udYXm3BUz0B1UQ==\r\nvti_folderitemcount:IR|0\r\nUniqueSolutionId:SW|91fea9d9-dc10-4be7-8506-b86007adc605\r\nIsValidAppPackage:BW|true\r\n","_Level":1,"_IsCurrentVersion":true,"ItemChildCount":"0","FolderChildCount":"0","Restricted":"","OriginatorId":"","NoExecute":"0","ContentVersion":"1","_ComplianceFlags":"","_ComplianceTag":"","_ComplianceTagWrittenTime":"","_ComplianceTagUserId":"","BSN":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":186,"LookupValue":""
},"_ListSchemaVersion":"","_Dirty":"0","_Parsable":"0","AccessPolicy":"","_VirusStatus":"","_VirusVendorID":"","_VirusInfo":"","_CommentFlags":"","_CommentCount":"","_LikeCount":"","AppAuthor":null,"AppEditor":null,"SMTotalSize":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":15004,"LookupValue":""
},"SMLastModifiedDate":"2018-01-18T17:59:47Z","SMTotalFileStreamSize":"6767","SMTotalFileCount":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":1,"LookupValue":""
},"owshiddenversion":3,"_UIVersion":1024,"_UIVersionString":"2.0","InstanceID":null,"Order":600,"GUID":"\/Guid(e745a129-02c7-4390-b8d1-f43b73f7216e)\/","WorkflowVersion":1,"WorkflowInstanceID":null,"ParentVersionString":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":null
},"ParentLeafName":{
"_ObjectType_":"SP.FieldLookupValue","LookupId":6,"LookupValue":null
},"DocConcurrencyNumber":"3","ParentUniqueId":"{BDBD38A8-92BA-408C-87C9-5E7487FDB938}","StreamHash":"0x02753F79539A396B88CB2D691BDA610E92715EED06","ComplianceAssetId":null,"Title":"tr-app-client-side-solution","AppProductID":"\/Guid(91fea9d9-dc10-4be7-8506-b86007adc605)\/","AssetID":null,"AppPublisher":null,"AppThumbnailURL":null,"AppDescription":null,"AppShortDescription":null,"AppVersion":"1.14.0.0","AppSupportURL":null,"AppVideoURL":null,"IsAppPackageEnabled":true,"SharePointAppCategory":null,"AppPrerequisitesXML":null,"IsFeaturedApp":null,"AppMetadataLocale":"1033","IsDefaultAppMetadataLocale":true,"AppImageURL1":null,"AppImageURL2":null,"AppImageURL3":null,"AppImageURL4":null,"AppImageURL5":null,"AppPackageHash":"34+CLHuLF534hhDM234vqfnTknvDCpwi5Nlmn4V8ufTMpjI9AVE9nir4yaud3PoGvN6iz6G7udYXm3BUz0B1UQ==","IsValidAppPackage":true,"AppPackageErrorMessage":"No errors.","AppPermissionXML":null,"AppSubtypeID":16,"IsAutoHostedApp":false,"AppTitleInfo":"{\"Default\":\"tr-app-client-side-solution\"}","AppSupportedLocales":null,"IsClientSideSolution":true,"IsClientSideSolutionDeployed":true,"ExternalContentDomains":"https:\u002f\u002flocalhost:4321\u002f ; https:\u002f\u002ftronoxglobal.sharepoint.com","IsClientSideSolutionCurrentVersionDeployed":true,"SkipFeatureDeployment":true,"PackageDefaultSkipFeatureDeployment":true,"UniqueSolutionId":"91fea9d9-dc10-4be7-8506-b86007adc605","WebApiPermissionRequests":null
}
]

**Comment by mcmynn83** [comment]
@russgove - we made some improvements around deployment reliability... are you still seeing these issues?  From the logs in the request I was not able to see what the issue was, I am adding new logging into the system in hopes of capturing more data when this fails.  However, I'm hoping the deployment reliability fixes that we added will have improved the situation already.  Please let me know.

**Comment by mcmynn83** [comment]
I'm going to close this issue, however, please feel free to respond and give a new correlation ID if this is still an issue for you.  Sorry for the problems this caused.
