### ISSUE TITLE
Features persistent after uninstall SPFx webpart in Feature page

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#1225]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
Hi,
After uninstalling a SPFX webpart in app catalog i have a feature always listed in features page (see screenshot).

![feature](https://user-images.githubusercontent.com/582733/34815651-63e33064-f6b2-11e7-92bd-832980cbe635.jpg)

I have clean site that used this webpart (content site/page ...), but, no change.

It's appear in double and i have no idea for delete this. Have you any idea for clean this ?

Thanks,
Richard

**Comment by mcmynn83** [comment]
@PooLP - Sorry that this is happening.  We are not able to repro this behavior on our test tenants.  Would it be possible to give us access to your tenant?  If so could you please send a test account that has access to both your app catalog and the site collection that is seeing the feature still available after deletion to grahamc at microsoft.com?

**Comment by PooLP** [comment]
Hi,
the issue can be closed. After deploy a new package builded from the scratch with the same name, but with new component GUID (manifest) and new GUID package (package-solution), the orphans features disappear.

Thanks,
Richard
