### ISSUE TITLE
.ControlZone <div>'s CSS transform causing fixed positioning issues (SPFx webpart | React)

### ISSUE THREAD

**Issue by stephen-oconnor** [SharePoint/sp-dev-docs#1227]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
To be able to use fixed positioning inside webparts/extensions and have the browser window as the context.

#### Observed Behavior
The .ControlZone <div> now has a transform applied to it which creates a context for positioned elements inside it, which now forces anything with fixed positioning to have a context of the .ControlZone <div> instead of the browser window.

#### Steps to Reproduce
Give any element inside a webpart/extension fixed positioning.

We have a spinner component that we have created that displays when our webpart is saving, very straightforward, just a spinner that is position: fixed with a message that displays until something has finished saving. The issue comes from the .ControlZone <div> now having a transform applied to it, which is creating the wrong context for our spinner: the .ControlZone <div> instead of the browser window. Is there a workaround for this to ensure fixed positioned elements inside webparts/extensions have the browser window as their context?

Thanks.

**Comment by mcmynn83** [comment]
@stephen-oconnor - It is by design that webparts should only affect the canvas within there given node.

**Comment by stephen-oconnor** [comment]
Thanks for the reply. I understand the logic behind this however I find it a little frustrating, I cannot be the only one who is looking to do something similar to this within webparts and if I use the Office Fabric UI components (Panel for example) they break this design pattern so it is a little frustrating that we cannot do something similar.

**Comment by sebastianvr** [comment]
I'm trying to create a webpart that serves as a fixed button on the page and encountered the same problem. Have there been any changes in the meanwhile?

**Comment by nikthequik** [comment]
I'm also looking to have a fixed bar that appears only when items in a react table have been selected.  It works in the workbench, but not when deployed to a site page.  Has anyone found a workaround?

**Comment by smchargue** [comment]
@stephen-oconnor - more than a little frustrating.  what does everything have to be so damn hard with sharepoint.
