### ISSUE TITLE
Timeout option on httpClient inside a SPFx web part

### ISSUE THREAD

**Issue by raymondlittle100** [SharePoint/sp-dev-docs#1228]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a SPFx web part which calls to a web API in azure and I have noticed that sometimes the connection drops or takes a long time.  When this happens the request doesn't seem to timeout it just keeps spinning. 

I have done some looking into the httpClient class and the various configuration options and settings but i can't see a timeout option. What should the timeout be for the httpClient request getting made and once that timeout is reached I assume the catch on the client call should be hit?

**Comment by mcmynn83** [comment]
@raymondlittle100  - there is no timoeut value in our API surface.  If you would like to make this feature request please add the ask to uservoice.  Thanks for the feedback, and sorry it's not there.
