### ISSUE TITLE
Speed of Yeoman scaffolding

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#123]
Creating a new Web Part takes very long time (3-15 mins) due to how npm works, network and the compilation of phantom and what not. Is there any way to speed up this process? Either tips and tricks using npm or optimization of the generator or processing?

**Comment by manishgarg1** [comment]
VSO #243681

**Comment by nickpape-msft** [comment]
Creating a new WebPart _project_ will be limited to the speed of the npm install, which is based on the dependency graph (we've had lots of discussions over making node_modules smaller, and having parts of the build system be opt-in to reduce the # of deps)..

However, you should be able to add a new WebPart to an existing WebPart project. Just run `yo` in the project.

Additionally, we are preparing to open-source a tool we use internally which allows multiple projects to use a common node_modules directory, saving time and disk space.

**Comment by wictorwilen** [comment]
@nickpape-msft - I know :-( Probably the only way is to run full speed into the npm source and make that more effective :-) 
Love the idea with a shared node_modules thing

**Comment by nickpape-msft** [comment]
@wictorwilen We ended up adding a `--no-install` flag. It will come in the next drop. We will keep you posted on the other things I pointed out.

**Comment by chakkaradeep** [comment]
@wictorwilen We have implemented --skip--install in the latest bits. However there is a small bug that it installs React when chosen framework as react even though it shouldn't. That will get fixed in the next drop.

Can you let us know if there is anything else that you are concerned about?

Thanks!

**Comment by patmill** [comment]
I think this immediate bug can now be closed.  We'll continue to try and optimize the load time / build time / etc.
