### ISSUE TITLE
Can't add a SPFx Web Part to a classic page in Chrome

### ISSUE THREAD

**Issue by matthong** [SharePoint/sp-dev-docs#1232]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
A user should be able to add a web part to a classic page in Chrome, even when you have many Web Parts in a same category.

#### Observed Behavior
In a certain scenario when you have a Category contains more than 12 Web Parts(classic and SPFx),  the Add and Cancel button are invisible on the ribbon of a classic page. The user can add any Web Part in that category to the page.

This only happens in Chrome, both IE and FF work.

#### Steps to Reproduce
1) create more than 12 Web Parts (in my case, I have 14, 7 classic and 7 SPFx) and put them in the same test category;
2) deploy all WPs to SP Online;
3) use Chrome to create a wiki page;
4) edit the page and display the Insert Web Part ribbon;
5) click the test category and try to add a Web Part;
You will find both Add and Cancel buttons disappear, so you have no way to add a Web Part from that test category.

When comparing with other categories, you can find that the toolbar which contains the add button is actually pushed down by the Web Part panel. Seems that the Web Part panel increases its height in order to display all Web Parts in two columns. In IE and FF, the panel arranges Web Parts in 3 columns and a scrollbar is displayed.

**Comment by matthong** [comment]
![missingaddbutton_chrome](https://user-images.githubusercontent.com/12601555/34851101-7255db2e-f720-11e7-94f9-b5130bd29d72.jpg)
Attached a screenshot for the issue

**Comment by matthong** [comment]
![missingaddbutton_chrome1](https://user-images.githubusercontent.com/12601555/34851195-de87956c-f720-11e7-971d-c9887a576c31.jpg)

Added a screenshot for the issue

**Comment by mcmynn83** [comment]
@matthong  - thank you for your feedback, we will investigate this issue.

**Comment by manishgarg1** [comment]
Hi @matthong, are you able to use the enter key after selecting the web part to add it to the page?

**Comment by matthong** [comment]
Hi @manishgarg1 , that's a good workaround. I can add the Web Part to the page by using the enter key. Thanks!

**Comment by manishgarg1** [comment]
Hi @matthong, good to know that you are not completely blocked.

**Comment by VesaJuvonen** [comment]
This issue seems to be fully already fixed long time ago, so closing this. Please open a new issue if there's any similar issues at the service, so that we can track the issue accordingly. Thanks for helping us on improving our services.
