### ISSUE TITLE
MS Grid doesnt seem to get picked up - all items show under each other

### ISSUE THREAD

**Issue by RichBurdes1** [SharePoint/sp-dev-docs#1233]
#### Category
- [ ] Question
- [ ] Typo
- [] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Went through **Tutorial - Migrating from UserCustomAction to SharePoint Framework Extensions**
Upgraded to SPFX v 1.4 and Node v6.11.2, build tools 3.2.7
Deployed to an azure cdn (which works for existing web parts in play)

Ran npm outdated and no items requiring an update (updated all yesterday) Here is what I see.

![verticalfooter](https://user-images.githubusercontent.com/31907811/34853808-a1a70cb6-f79a-11e7-9943-7be6fa8c0b2d.png)

No issues with the build and package, however installing on a dev tenant set to first release the footer elements are stacked vertically, not horizontally using the grid system.

#### Observed Behavior
No issues with the build and package, however installing on a dev tenant set to first release the footer elements are stacked vertically, not horizontally using the grid system.

Build ran ok  - but I did pick up a few undefined calls in the gulp bundle-package (ran after a gulp bundle --ship)

![undefined items](https://user-images.githubusercontent.com/31907811/34853868-097ca7d8-f79b-11e7-8476-7413c56e0bac.png)

Vanilla copy of all items and build and deploy to a tenant - with first release enabled.

Happy to try to work through my system to double check if I've missed any updates or am running anything out of date.

#### Steps to Reproduce

Vanilla copy of all items in the tutoral and build and deploy to a tenant - with first release enabled.

Hope this helps (first bug I've raised :))

**Comment by RichBurdes1** [comment]
update with screenshots - in chrome the display grid css looks to be overridden by display:block - if I tweak that I can get the footer to display in one row.. hope this helps.
![displayblock](https://user-images.githubusercontent.com/31907811/34854149-bbc02496-f79c-11e7-828c-4ca36a715ffa.png)

with the dev tools tweak forcing display as a grid with fractions.
![displaygrid](https://user-images.githubusercontent.com/31907811/34854166-d61ab6b2-f79c-11e7-891b-3d7fe21e6730.png)

**Comment by mcmynn83** [comment]
@RichBurdes1 - Could you please attach the package that trigger this issue for you so that we can investigate the problem.

**Comment by RichBurdes1** [comment]
Sure thing - loaded here - https://github.com/RichBurdes1/SharePointFrameWork-App-Footer-Test I've removed the cdn keys / account info to set back to generic. I should have just pushed what you need to this location, but if missing anything please advise.

**Comment by mcmynn83** [comment]
Thanks for sending that, we will schedule it for somebody to take a look.

**Comment by RichBurdes1** [comment]
Randomly looked at the same demo sites today to show someone and magically this bug appears to be resolved - same code base on our site, but not ms-grid operating as expected. Thanks product team.
