### ISSUE TITLE
Workbench wont even load

### ISSUE THREAD

**Issue by nigel-dewar** [SharePoint/sp-dev-docs#1241]
- [x] Bug

Windows 10 x64
npm v = 5.5.1
node v 6.12.3

Installed SPFX yeoman generator (today 15 / jan / 2018). Everything runs well, installed the dev-certificate, did gulp serve which loads the workbench page but then.... nothing!

Have tried node uninstall , restart, reinstall node, ensure proper versions, npm cache clean -force, restart computer, reinstall yoeman and gulp, start new spfx project, turn off https, remove 's' from initialPage, tried difference browsers, even tried another Windows 10 PC in my house, triple checked the instructions, you name it!!!!, No errors in console either!!!

https://localhost:5432/workbench    - displays nothing - Un - Freaking - Believable!
or 
http://localhost:5432/workbench  - with https turned off.

Had another crack, running as administrator - and again ... nothing.

Is this SPFX thing still in BETA? 

![image](https://user-images.githubusercontent.com/9402456/34922361-8f48f4a2-f9da-11e7-87c0-8a144d08fefb.png)

![image](https://user-images.githubusercontent.com/9402456/34922367-9d5748fa-f9da-11e7-8edc-b73c73a22e07.png)

**Comment by nigel-dewar** [comment]
6 hours later, still cant fix it!!!

**Comment by Cheshirefury** [comment]
I am also facing this issues on Windows 10 and OSX. I am also looking for a easy resolution to this

**Comment by nigel-dewar** [comment]
@Cheshirefury 

Hi There, This is a SUPER annoying issue. Here is what I have found. I have a Fresh Windows 10 Pro machine that I managed to install spfx and run the workbench fine on. This machine had not been used for development prior. 

Then I took a Windows 7 pro machine , which again had not been used for development on, and all went well.

So this leaves me to believe I had some prior software or settings on my normal Win 10 Pro dev machine that was casuing this issue.

I went as far as clearning on the NPM files in c:\ as well, untrusted the certificate, trusted again, you name it. I just cant figure it out.

Comparing the 2 machines vs my dev pc that wont run the workbench, all the software looks the same. Node version is good, npm version is good.

There is however one difference I notice when I run on the GOOD windows 7 and 10 machines which is the dialog on the gulp task runner is different, it seems to be running and getting files that it needs correctly, whereas on my dev machine (where workbench wont load), there is missing dialog. Please see images below for reference. You will see certain things arnt happening on the BAD machine.

Working GOOD
![image](https://user-images.githubusercontent.com/9402456/34930927-b2203c5a-fa17-11e7-9808-7cebacf3e94c.png)

NOT WORKING (GRRRR)
![image](https://user-images.githubusercontent.com/9402456/34930981-f3b86e76-fa17-11e7-9368-903ab3c09a25.png)

**Comment by HeToC** [comment]
it seems that you don't have proper version of nodejs installed.
i have the same issue running nodes 9.4 and got the same certificate trust problems
in the parallel thread someone said that " NODE_NO_HTTP2=1 gulp serve" could help
but it does nothing for 9.4 environment

**Comment by Cheshirefury** [comment]
I resolved the issue (on windows 10 not OSX) with uninstalling the newer version of node and installing the version: [https://nodejs.org/dist/latest-v6.x/](url)

**Comment by andrewconnell** [comment]
See details on the specific issue: 
https://github.com/sharepoint/sp-dev-docs/issues/1002

Also see the note in the official docs: 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-developer-tools

**Comment by nigel-dewar** [comment]
I have node v6 and npmv3 running. There is something specific to my dev machine that is causing this as like i said, i tested on fresh win 10 and win 7 and had no issues. When or if i figure our what specifically causes this, ill post here.

I did the whole node uninstall, reinstall, restart machine. Npm cache clean force, deleted the actual npm files under appdata/roaming/npm etc, restart again, reinstall yo and gulp, and the generator for spfx. Untrust cert, then trust, but to no avail.

There must be some insane thing i cant see as to why this is happening on this particular machine. Of course im not going to spend much more time on it, as ill just use my working win 7 vm. But it was and is super annoying not knocking what the hell was causing this. 

Anyways.... i thought i would give spfx a crack.

**Comment by andrewconnell** [comment]
I know you listed versions above, but for completeness... can you do the following: `npm list -g --depth=0`.

Also: 
- Is what you're testing an old / new project? 
- If old, can you create a new web part project with no JS framework, after doing `npm install`, just run `gulp serve` and see what happens?

We'll get this solved... I'm curious now :)

**Comment by nigel-dewar** [comment]
Hi @andrewconnell 

Thanks for your reply. In the end, I gave up as have some pressing projects on time, but, I did come to the conclusion that it is something specifically wrong with my PC. For example, I wanted to uninstall an older version of angular-cli, and install a newer version, but my PC simply wont allow me to do it!

So its just my PC that is munched up. The 2 other machines (fresh machines) that I have tried, there are no issues. So I believe this is not a bug at all, except for my crappy machine of course. Closing now

Thank you very much for taking a look at this. My advice for others whom may have issue of workbench loading is, try spfx on another machine first. If it works, then the issue is with your machine, and some config that is not right.

Cheers

**Comment by andrewconnell** [comment]
Hey @nigel-dewar - just dawned on me... did you run `gulp trust-dev-cert` after installing everything on your new PC?

The error you highlight in the screenshot above is on my install as well... so that's definitely not your root error. If you scroll up above that error, I wonder if you have a message about HTTPS and self-signed certs.

**Comment by nigel-dewar** [comment]
Hi @andrewconnell hmm, i cant remember on the new pc. But im sure i did. I have a fresh windows 7 x64 VM which i can go through the install/setup process fresh.

**Comment by andrewconnell** [comment]
If you get an error, screenshots don't help. Copy the output of what you see in the command prompt and paste it into a GH Gist, then link to it from the issue, or post the whole issue to the issue as a code entry.

The image you posted above isn't complete and thus it's really hard to help with incomplete data.

**Comment by lifayt** [comment]
https://gist.github.com/lifayt/4c7b01cba8c72da987586197feb9122d

Same issue, OSX, no solution found.

**Comment by andrewconnell** [comment]
@lifayt you're using [Node v9 according to your Gist](https://gist.github.com/lifayt/4c7b01cba8c72da987586197feb9122d#file-output-txt-L52). SPFx only supported on Node v6 ATM, although that [will change soon](https://twitter.com/andrewconnell/status/959379591281500165) per @VesaJuvonen 

Setting the env var `NODE_NO_HTTPS2=1` on the process, or as a perm env var in your profile, will fix it if you are running Node v8. 

For your situation, you should uninstall Node v9 and install Node v7, v8 OR Node v6 (if you want to follow MSFT's supportability guidelines explicitly.

There's an issue in Node v9 where this flag does not fix it.
REF: https://github.com/gruntjs/grunt-contrib-connect/issues/235
