### ISSUE TITLE
window.g_listData is not being updated after navigation occurred

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1243]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

This bug is partially related to [this one](https://github.com/SharePoint/sp-dev-docs/issues/1242)

#### Expected or Desired Behavior
`window.g_listData` is being updated when navigation occurred (Quick launch navigation, list view dropdown, lazy loading during scrolling down in the list)
#### Observed Behavior
`window.g_listData` is not being updated when navigation occurred (Quick launch navigation, list view dropdown)
#### Steps to Reproduce
1. open any list
2. open console and type `window.g_listData` - it contains information (`ListSchema`, `ListData`, etc) for current list/view
3. navigate to other list using Quick launch
4. type `window.g_listData` in console again - it contains information from previous list/view

#### Additional remarks
I know that potential answer here is "this is an internal variable, don't use it".
But the thing is that for now it is the only easy (and sometimes even the only) way to get missing data for the list items on the page.
For example,
1. If you have URL field and use Field Customizer, `event.fieldValue` contains url only, but not the text to be displayed. And here you can either get `URL.desc` from `window.g_listData` or make additional request to get the text which will lead to slower performance
2. There is no way at all to get FriendlyText for Date and Time fields - only `window.g_listData.ListData.Row`. Well, another way is private `_fields` property in `ListItemAccessor` but it is not public API.
3. `event.fieldValue` for Number, Currency fields in Field Customizer contains formatted text. Real value (in invariant culture that can be easily parsed to Number) is not presented in the API. Again, you can get it from `window.g_listData` or using additional request (**request per cell**)
... and so on.

**Comment by pgonzal** [comment]
> I know that potential answer here is "this is an internal variable, don't use it".

That's right.  :-)

> But the thing is that for now it is the only easy (and sometimes even the only) way to get missing data for the list items on the page.

Today, the recommended solution would be to perform a REST query to obtain the missing data.

However, given that the information is already preloaded on the page, ideally this information should be exposed via an SPFx TypeScript API.  For example, the [SPListItem](https://docs.microsoft.com/en-us/javascript/api/sp-page-context/splistitem) class from the page context could expose this data.

Since this is a feature request, could you open an issue on [SharePoint UserVoice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform)?  This will allow others to vote for your suggestion.  Thanks!

@VesaJuvonen @ahackettms FYI

**Comment by ahackettms** [comment]
Thank you for raising this question. 
1. Do not use window.g_listData. That is an internal variable and we don't guarantee it has the information you need.
2. Do use event.row.values for all the field values for the given list item, if event.fieldValue doesn't have all the value you need.
for complex field types such as Number, Currency, HyperLink, you can find in the event.row.values for additional values to store the 'raw' value. For example, 
Number field named 'foo', the value in [foo.] stores the number value
Currency field named 'foo', the value in [foo.] stores the currency value as a number
Hyperlink field named 'foo', the value in [foo] stores the link, and [foo.desc] stores the description

Hope this helps.
Thank you

**Comment by AJIXuMuK** [comment]
Hi @ahackettms ,
Are `foo.` and `foo.desc` available in `event.row.values`?
For now I'm using "private" `ListItemAccessor._values`.

**Comment by ahackettms** [comment]
@AJIXuMuK , yes foo. and foo.desc are available. 
Again, please use getValueForItem() instead of directly using ListItemAccessor._values.

**Comment by AJIXuMuK** [comment]
@ahackettms ,
I'd like to do so. But I can't find `getValueForItem` neither in `IFieldCustomizerCellEventParameters` nor in `ListItemAccessor`.
I've also looked into documentation and can't find such method there as well.

Could you please explain how exactly use the functionality in Field Customizer?
Thanks!

**Comment by AJIXuMuK** [comment]
As this one is referencing internal property, I will close it.
