### ISSUE TITLE
Error when displaying HelloWorld web part in (non developer site collection) of tenant workbench

### ISSUE THREAD

**Issue by tracy-zaact** [SharePoint/sp-dev-docs#1245]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
[Based on current documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant), tenant workbench should function within both developer and non-developer site collections. 
![ss1](https://user-images.githubusercontent.com/25020454/34965629-c810d8e4-fa12-11e7-944e-43899a78721e.png)

#### Observed Behavior
SPFx HelloWorld web part works fine within localhost workbench and tenant **developer site collection** workbench.  On a non-developer site collection, I can add it to my workbench, but then it displays the following error.
![ss2](https://user-images.githubusercontent.com/25020454/34965650-fc0faea4-fa12-11e7-8db6-b369136809de.png)

#### Steps to Reproduce
1. Run gulp serve within the context of HelloWorld SPFx sample
2. Confirm it functions correctly in localhost workbench.
3. Confirm it functions correctly within a developer site collection tenant workbench.
4. Try adding/viewing it on a non-developer site collection tenant workbench.
I am using node 6.12.3 and here is my solution without the node_modules directory: [HelloWorld.zip](https://github.com/SharePoint/sp-dev-docs/files/1635781/HelloWorld.zip)

**Comment by waldekmastykarz** [comment]
When on step 4), is your local web server still running? It seems like the workbench cannot load the bundle from your local machine.

**Comment by tracy-zaact** [comment]
Yes, it's still running.

**Comment by waldekmastykarz** [comment]
What do you see when you try to open in the browser `https://localhost:4321/dist/hello-world.bundle.js`?

**Comment by tracy-zaact** [comment]
@waldekmastykarz 
![ss1](https://user-images.githubusercontent.com/25020454/35070157-a5a431b0-fb99-11e7-9579-5b6bb5c55259.png)

**Comment by waldekmastykarz** [comment]
Which explains why the web part cannot be loaded in the workbench. Have you by any chance renamed the web part in the process or changed the name of its bundle?

What you could also try is running the following commands:

```sh
gulp clean
gulp serve
```

The first one will clear the output directory in case you have some stale files. The second one will rebuild and bundle your project and start local workbench, where you will be able to confirm that the web part is working. Once you confirm, that you can add it in the local workbench, you can navigate to the hosted workbench and should be able to add it there as well.

**Comment by tracy-zaact** [comment]
Thanks @waldekmastykarz.  Does it make sense that it would still work in the localhost workbench?  
I went ahead and created a brand new instance of the HelloWorld web part and that one does appear to work in the hosted workbench of a non-developer site collection.  I'm not sure what I did to the first one, but obviously something that 'broke' it.

**Comment by VesaJuvonen** [comment]
thx @tracy-zaact for following up and closing the issue. Also thx @waldekmastykarz for the support.
