### ISSUE TITLE
React WebPart need no escape

### ISSUE THREAD

**Issue by StefanSchoof** [SharePoint/sp-dev-docs#1246]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If creating a new React WebPart with SPFx 1.4 there should no unneeded escaping. If chaining the description `HelloWorld <>`, it should render `HelloWorld <>` in the webpart

#### Observed Behavior
In the `HelloWorld.tsx` is a line:
```
<p className={ styles.description }>{escape(this.props.description)}</p>
```
React does the escaping a extra Escaping. If chaining the description to `HelloWorld <>` it renders `HelloWorld &lt;&gt;`

![grafik](https://user-images.githubusercontent.com/4662023/34998934-a56f2f06-fae0-11e7-889c-80a78c51a127.png)

#### Steps to Reproduce
Create new webpart with default options. Run `gulp serve`, add the webpart to the workbench and change the description to `HelloWorld <>`

**Comment by jackpoz** [comment]
I just wondered about this after creating a new webpart using "yo @microsoft/sharepoint" v1.7.1, selecting Webpart and then React. The .tsx component has
```
<p className={ styles.description }>{escape(this.props.description)}</p>
```
which gives the wrong impression escaping is required, while JSX doesn't need escaping as explained at https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks.
This is an example:
![image](https://user-images.githubusercontent.com/1153754/54033974-0f6a7880-41b6-11e9-825f-57421f0cc20c.png)
and the resulting HTML
```html
<div class="column_e0aea165">
  <span class="title_e0aea165">Welcome to SharePoint!</span>
  <p class="subTitle_e0aea165">Customize SharePoint experiences using Web Parts.</p>
  <p>Escaped:</p>
  <p class="description_e0aea165">&amp;lt;p&amp;gt;test&amp;lt;/p&amp;gt;</p>
  <p>Unescaped:</p>
  <p class="description_e0aea165">&lt;p&gt;test&lt;/p&gt;</p>
  <a href="https://aka.ms/spfx" class="button_e0aea165">
    <span class="label_e0aea165">Learn more</span>
  </a>
</div>
```
