### ISSUE TITLE
Duplicate Web IDs in SharePoint Online Site Collections

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#1249]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

In all of our O365 Tenants some of the root webs of the site collections have duplicate web ids. 

Site ID | Web ID | Created
-- | -- | --
8f4841b0-e635-4278-9b5e-3c948eebd063 | aee98c90-66fa-4c97-9ee2-6e1cf157748d | 1.16.18 12:57
e7fed26b-c969-4774-b683-4f4b97032485 | 21ac3830-023c-45fb-a1dd-1f62d7890f7d | 1.16.18 12:08
d062fcd0-03d5-4fbf-abd8-9e845245cc97 | fc10068a-f335-4d5d-9fe8-8a1108c9e5fc | 1.15.18 15:51
2f1a5efb-3ed9-4c34-bbcf-304fbee9ff6d | 5d65edb0-4804-4360-9590-028314b4e2d5 | 1.11.18 17:01
03648121-6798-4437-9a62-b1806b7d9aee | 5d65edb0-4804-4360-9590-028314b4e2d5 | 12.18.17 12:53
29678787-c40a-46c4-b960-3c9ad5430791 | 5d65edb0-4804-4360-9590-028314b4e2d5 | 12.13.17 8:45
1b70ac76-ee44-4e07-beb3-8e659544f820 | 5d65edb0-4804-4360-9590-028314b4e2d5 | 12.7.17 13:45
ff77d193-a40b-4cbc-a628-b0070383e829 | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 12.6.17 8:25
e1e38630-5005-4857-ba54-800960ac2109 | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 12.5.17 7:49
40d1a4b1-adee-4e9f-b2ec-df35b23946e9 | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.30.17 17:44
30b99e25-8614-4732-a07a-6d7143d49825 | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.29.17 15:30
9b12cd36-0e96-4476-a833-85b432c7fae5 | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.27.17 6:48
4cdf70e0-3f00-40c2-969e-aea004a3c9ce | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.22.17 15:14
02494619-fced-429b-82ca-e10abf6400fa | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.21.17 8:11
57ef86b7-a36a-4a5f-ae64-3467099928aa | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.17.17 8:56
45354493-3e48-4482-aa2c-9d9ff86c494f | 5bf2cabc-35a4-4369-8438-d18c4d7683e7 | 11.17.17 8:53

Is this by design in O365? This is not the same behavior as in SharePoint On-Premise.

**So we have a unique Identifier which is not unique anymore!**

This breaks some parts of the system. E.g. search will find results from multiple site collections when you search for something like this:

contentclass:STS_ListItem_DocumentLibrary WebId:5d65edb0-4804-4360-9590-028314b4e2d5

#### Expected or Desired Behavior
All Office 365 Site Collections should have a unique web id for their root web.

#### Observed Behavior
Site Collections created in a short time period have the same root web id.

#### Steps to Reproduce
Create multiple site collections in a row in a short time period.

**Comment by mcmynn83** [comment]
@MrTantum - Site collection ID's are guaranteed to be unique.  However, WebId's can be duplicated on different site collections.  This is by design.
