### ISSUE TITLE
Update documentation code samples to reflect updates in HelloWorld sample generator

### ISSUE THREAD

**Issue by tracy-zaact** [SharePoint/sp-dev-docs#1257]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Tutorial code examples should work with the current Yeoman HelloWorld sample generator.  

#### Observed Behavior
[Starting on this page of the tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part), and continuing through the remainder of it - the code examples produce errors in the current version of HelloWorld.

[Here is another user's StackExchange posting indicating the same issue 9 months ago.](https://sharepoint.stackexchange.com/questions/211810/how-to-retrieve-pagecontext-in-spfx)  

#### Steps to Reproduce
1. Create a new HelloWorld web part by running the Yeoman SharePoint Generator.
2. Navigate [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part), and attempt to copy/paste the code samples as instructed in the documentation tutorials.  
3. Continue [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint), and attempt to copy/paste the code examples as instructed in the documentation tutorials.

**Comment by andrewconnell** [comment]
Just ran through the entire tutorial with zero issues so I think this is an old issue that was already resolved...
