### ISSUE TITLE
Safari not allowing Azure AD cookie set in iframe

### ISSUE THREAD

**Issue by lworkman** [SharePoint/sp-dev-docs#1258]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
An iframe opened within by my SharePoint Framework extension will set an AzureAD cookie.

#### Observed Behavior
When opening my SharePoint Framework extension in safari, the component hangs because it's waiting for the auth iframe to resolve. I set up the iframe following [this guide](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md), and the process works fine in Chrome, Firefox, and IE 11. 

My issue appears to be tied to Safari's stricter content policies regarding third party cookies being set in iframes. Is there a known workaround for AzureAD / Sharepoint regarding this bug? Or is there a better way to gather credentials not outlined in the above article?

#### Steps to Reproduce

1. Create a SharePoint extension that hits an AzureAD endpoint on load.
2. Put an iframe that resolves to that api in the extension in order to generate the cookie.
3. Open the extension in Safari and watch as the iframe does not resolve.

**Comment by mcmynn83** [comment]
This is a known issue in ADAL.js.  Please see the following thread:
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/380

Can you please check and report back if this fixes the issue?

**Comment by lworkman** [comment]
Hi,

That linked issue is related to a different Safari issue. The issue I'm dealing with is Safari's limitations on third party cookies.

**Comment by mcmynn83** [comment]
Ok we will investigate this issue.

**Comment by lworkman** [comment]
Hi @mcmynn83 has there been any movement on this?

**Comment by mcmynn83** [comment]
@lworkman - although the issue is tracked on our side we have not started the investigation on it as of yet.  I don't currently have an ETA when that investigation will start, sorry.

**Comment by andrewconnell** [comment]
Still a problem? Been a long time since posted and now that the AAD support for SPFx has rolled to GA, can't repro...

**Comment by lworkman** [comment]
Hey Andrew, I've switched my app to use `aadTokenProviderGenerator` for auth, so I'm not worried about this anymore.
