### ISSUE TITLE
Image web part ISSUE

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-docs#1259]
There is an issue with the latest modern image web part in the tenant without early release enabled. 
Steps: create a page, add image web part, select image from recent images and do not click on anywhere else but Publish. After publish image is not saved. 
Could this be checked immediately, I have this issue with multiple clients.
 
#### Category
- [ x] Bug

Thanks
Saulius

**Comment by miyasena** [comment]
I have also had this issue when using the image web part. If you click in to the image so you get the options to crop etc. before publishing the image will be visible once published. It is fine for me and my team to use this workaround, not so easy to expect our end users to do the same.

Also, when you publish the page under the circumstances above where it won't display, going back in to 'Edit' will show that the web part is still on the page, but it is not longer displaying the image. Lastly, this behaviour is not unique to selecting from recent images, selecting site and selecting an image from, for example, Site Assets, will also result in the issue when published. It's not perfect, but see .gif for a demo. 
![imagewperror](https://user-images.githubusercontent.com/29796236/35273590-f6fab8cc-0030-11e8-9249-dcdf18c7fbe4.gif)
