### ISSUE TITLE
Apply button is not getting enabled on drop down property change events 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#126]
Apply button is not getting enabled on drop down PropertyPaneDropdown change events. Is it a bug or specific to my system?

![image](https://cloud.githubusercontent.com/assets/21008316/18145777/2adc9b50-6f92-11e6-8b21-326e37d824bb.png)

**Comment by patmill** [comment]
Bug - https://github.com/SharePoint/sp-dev-docs/issues/46
