### ISSUE TITLE
Externals do not work (Failed to load path dependency)

### ISSUE THREAD

**Issue by Nasicus** [SharePoint/sp-dev-docs#1262]
#### Category
- [x] Question

#### Expected or Desired Behavior
I want to use my own npm module as an external (following [this guide](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library)).
I don't want to include all dependencies in my own bundle, but instead want to specify them also as externals in the `config.json`.

Now let's get to the code:
```
  "externals": {
      "styled-components": "node_modules/styled-components/dist/styled-components.js",
      "my-library": "node_modules/my-library/index.js"
  }
```

The content's of these files:
`styled-components` should be an UMD module (at least according to the [rollup config](https://github.com/styled-components/styled-components/blob/master/rollup.config.js)), it looks something like this:

```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react')) :
	typeof define === 'function' && define.amd ? define(['exports', 'react'], factory) :
	(factory((global.styled = global.styled || {}),global.React));
}(this, (function (exports,React) { 'use strict';
// code ....
exports['default'] = styled;
exports.css = css;
exports.keyframes = keyframes;
exports.injectGlobal = injectGlobal;
exports.ThemeProvider = ThemeProvider;
exports.withTheme = wrapWithTheme;
exports.ServerStyleSheet = ServerStyleSheet;
exports.StyleSheetManager = StyleSheetManager;

Object.defineProperty(exports, '__esModule', { value: true });

})));
```` 

`my-library` is an AMD module, built with webpack and looks something like this:
```
define(["react","styled-components","react-dom"], function(__WEBPACK_EXTERNAL_MODULE_4__, __WEBPACK_EXTERNAL_MODULE_512__, __WEBPACK_EXTERNAL_MODULE_516__) { return /******/ (function(modules) { // webpackBootstrap
// code...
/***/ })
/******/ ])});;
//# sourceMappingURL=index.js.map
```

When I run `gulp serve` I always get this:

```
sp-loader-assembly_en-us.js:9924 Uncaught (in promise) Error: ***Failed to load path dependency "my-library" from component "124b9c36-ae65-462d-a6fa-269b5aba0115" (MyWebPart) due to another dependency that failed to load.
  
VM46:5 GET https://component-id.invalid/124b9c36-ae65-462d-a6fa-269b5aba0115_0.0.1/styled-components net::ERR_NAME_NOT_RESOLVED
sp-loader-assembly_en-us.js:20165 [1516718671400][resolveAddress] Error: ***Resource "styled-components" not found in loader configuration of manifest for component "124b9c36-ae65-462d-a6fa-269b5aba0115" (MyWebPart).
```` 

I cannot get it to work. I'm trying it for like a day...

I also tried adding my 2 externals like this:
```
  "styled-components": {
	  "path": "node_modules/styled-components/dist/styled-components.js",
	  "globalName": "styled-components"
  },
  "my-library": {
	  "path": "node_modules/my-library/index.js",
	  "globalName": "myLibrary",
	  "globalDependencies": ["styled-components"]
  }
```
However this also doesn't work.

Also note that if I include everything into my own bundle via webpack it will work.
@waldekmastykarz maybe you know something, I know you have a lot of experience on this.

**Comment by waldekmastykarz** [comment]
Have you been testing the setup with a release or debug build? When release build, can you verify that in the `temp/deploy` folder you see next to your bundle styled-components and my-library? Their file names will include an ID, but you should see them included in the output.

**Comment by Nasicus** [comment]
`my-library_8e09a0a22a03c96dc9e15fb221559641.js` is there. However for `styled-components` there is no path. I just verified if the path to `styled-components` is incorrect, however that's not the case.

**Comment by waldekmastykarz** [comment]
Correct, if there are no references to a package, it won't be included in the build output.

**Comment by Nasicus** [comment]
Can this somehow be "simulated" / "faked"? I don't need references in my project, since only my library contains them.

**Comment by waldekmastykarz** [comment]
Is `styled-components` listed as a dependency in package.json of your library?

**Comment by Nasicus** [comment]
Yes, but  not of my spfx project.

**Comment by Nasicus** [comment]
Maybe a small addition:
Because of your comments I made a workaround.
Basicially I added `styled-components` also as a dependency on my SPFX project and made somewhere a dummy import of a class so it appears to be used.
When I do that a corresponding file is generated and it works.

**Comment by waldekmastykarz** [comment]
That shouldn't be necessary as far as I can tell, but at this point I can't say with full confidence if it's a bug in SPFx and it detecting chained dependencies or if the component should be referenced differently in your component. Do you happen to have a repro project that we could have a look at?

**Comment by Nasicus** [comment]
I created a new minimal project to reproduce it *:
https://github.com/Nasicus/my-spfx-project

Note the following:
This project has a dependency to `my-spfx-test-library` which I created specially for this project (if you run `npm install` you will have all the sources in the node_modules folder).
The library uses `styled-components`.

In the `my-spfx-project` the `MyComponent` is used and both the `my-spfx-test-library` and the `styled-components` I added as externals.

If you run `gulp serve` you will get the error:

```
[SPLoaderError.loadComponentError]:
***Failed to load component "050388df-94f6-4e85-a792-1c546cb35d50" (HelloWorldWebPart).
Original error: ***Failed to load path dependency "my-spfx-test-library" from component "050388df-94f6-4e85-a792-1c546cb35d50" (HelloWorldWebPart).
Original error: Error loading https://relative-path.invalid/styled-components as "styled-components" from https://component-id.invalid/050388df-94f6-4e85-a792-1c546cb35d50_0.0.1/my-spfx-test-library
	Unable to load script https://relative-path.invalid/styled-components
```
However if you comment in the 2 lines found in `HelloWorld.tsx` you'll get another error:

```
import styled from "styled-components";
const styledDiv = styled.div``;
```

Error - not sure if this is a timing issue, I don't understand whats happening here:

```
Original error: Error loading https://component-id.invalid/050388df-94f6-4e85-a792-1c546cb35d50_0.0.1/my-spfx-test-library
	Module not already loaded loading "react" as https://component-id.invalid/react.
    at SPLoaderError.SPError [as constructor] (sp-loader-assembly_en-us.js:sourcemap:10183)
    at new SPLoaderError (sp-loader-assembly_en-us.js:sourcemap:4211)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (sp-loader-assembly_en-us.js:sourcemap:3821)
    at Function.ErrorBuilder.buildLoadPathDependencyError (sp-loader-assembly_en-us.js:sourcemap:3768)
    at sp-loader-assembly_en-us.js:sourcemap:8052
    at sp-loader-assembly_en-us.js:sourcemap:8067
    at <anonymous>
```

I got this same error when I tried to add `rxjs` as an external (at my real project). Thought the problem was rxjs or something different (did you eve integrate rxjs?)

**Comment by waldekmastykarz** [comment]
As far as I can tell it has to do with the fact that while you marked `styled-components` as external in `config.json`, but because there are no references to it in your code, the external entry is not included in the generated web part manifest and as a result, SPFx doesn't know where to load it from when executing your library code. Resolving such an indirect dependency would work, if we had support for SharePoint Framework libraries, which currently isn't there. For the time being, the only solution I see is either to package external dependencies, such as `styled-components` with your `my-spfx-test-library` or by including the library dependencies as web part dependencies.

**Comment by Nasicus** [comment]
Yes that's the workaround I'm using.
However as I written sometimes this doesn't work (in my real project with `rxjs` and in the simple project no even with `styled-components`) and the exception from above appears. Maybe there is a timing issue / bug there.

**Comment by waldekmastykarz** [comment]
If all referenced scripts are modules, then it shouldn't be a problem because they should be able to resolve dependencies themselves correctly. The problems arise, where some of the scripts are modules, but some aren't. You can't load non-module as module, and for non-modules you have to specify correct dependencies. Have you checked if all scripts you're referencing are modules or if you have some modules and some non-modules?

**Comment by Nasicus** [comment]
I did not find a solution for this.
Funny enough it not worked in my real project with react when I tried again. I don't know why though and I hope it's not a timing problem and that it will stay like that.
I close this for now.
