### ISSUE TITLE
Local workbench assigns random property values

### ISSUE THREAD

**Issue by Rick-Kirkham** [SharePoint/sp-dev-docs#127]
I followed the Get Started articles. I found that the SharePoint-hosted workbench behaves as expected when no web part property value is chosen: Drop down lists default to “undefined”, on/off switches default to off, etc. . But the local workbench seems to just choose a random value from those available. E.g., the drop down defaulted to "2", the on/off button sometimes opened at ON.

**Comment by patmill** [comment]
The default should be the values in the .manifest.json
Note however that changes to the manifest don't get picked up right away in the local workbench.  You need to stop / restart gulp server to get the changes to be picked up.

**Comment by manishgarg1** [comment]
@Rick-Kirkham , does Pat's suggestion fix your issue ?

**Comment by Rick-Kirkham** [comment]
@manishgarg1 , The manifest.json is the same file whether the project is opened in the SharePoint-hosted workbench or the local workbench. But I got different values in some controls when I opened it at the same time in the two workbenches. The local workbench had the values in the manifest.json. The other workbench did not.

**Comment by nickpape-msft** [comment]
@manishgarg1 @srideshpande

**Comment by manishgarg1** [comment]
VSO #243757

**Comment by srideshpande** [comment]
I am able to reproduce this issue. I verified with the latest release. I am closing the issue. Please re-open if you still see the issue.
