### ISSUE TITLE
SPFx webpart apostrophe in webpart title

### ISSUE THREAD

**Issue by christopher-walker** [SharePoint/sp-dev-docs#1271]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

This issue arises when you add an SPFx webpart to a page and give it a title (in the general web part settings) containing an apostrophe for example if you give the webpart a title "Vesa's webpart" save the page and then try and use the SPFx webpart settings.

#### Expected or Desired Behavior
The SPFx webpart settings will open

#### Observed Behavior
Nothing happens, no error nothing

#### Steps to Reproduce
Add any SPFx webpart to the page. In the standard webpart settings set the webpart chrome title to "Vesa's webpart" then save the webpart and save the page.
Edit the page again and try and edit the SPFx settings

**Comment by christopher-walker** [comment]
Looking into the javascript on the button I see this is why it fails:

if (window.moduleLoaderPromise) {
	window.moduleLoaderPromise.then(function (application) {
		application.configureStart('g_a5df58b3_0c09_4ab9_8723_2588805ce6d3', 'Vesa' s blog ');                });                 }                 else {                   console.error(' Cannot configure start because client side application promise is not loaded.'); }


'Vesa**'** s blog '

**Comment by VesaJuvonen** [comment]
"Vesa's web part" - So I broke it then? :-) Thanks for reporting. Assigned forward to right people to engineering.

**Comment by christopher-walker** [comment]
Your always causing problems around these parts :)
Thanks for the help.

**Comment by mcmynn83** [comment]
@christopher-walker  - Thank you for your feedback.  This issue has been fixed (for a while now).  If you are still seeing the issue please let us know.

**Comment by mcmynn83** [comment]
This shouldn't be closed actually, just reproed the issue.  Looking into a fix now.

**Comment by mcmynn83** [comment]
This fix should be rolled out to production now.

**Comment by christopher-walker** [comment]
Thanks for the update, it would be nice to record which version CU for SharePoint 2016 includes this fix for completeness.
We still have this issue in the production environment and are looking to roll out the fix.
