### ISSUE TITLE
UI Fabric Icon Classes No Longer work in SPFx Extensions

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#1279]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Previously, we were able to add the ms-Icon and ms-Icon--IconName classes to have UI Fabric icons show within SPFx Extensions. Similar to the below HTML:

```html
`<i class="ms-Icon ms-Icon--Pin" aria-hidden="true"></i>`
```

A screenshot of this **previously** working in an [Application Customizer](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/jquery-application-toastr):
![Toastr](https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/jquery-application-toastr/assets/spfxToastr-Preview.PNG?raw=true)

A screenshot of this **previously** working in a [Field Customizer](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/jquery-field-itemorder)
![ItemOrder](https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/jquery-field-itemorder/assets/spfxItemOrder-Preview.png?raw=true)

> Neither of the above samples show Icons anymore.

#### Observed Behavior
The use of ms-Icon--IconName no longer shows a UI Fabric Icon in SPFx Extensions.

#### Steps to Reproduce
Create an extension and add the ms-Icon ms-Icon--IconName classes and see that they don't work. Or just run the linked samples above.

I believe this issue is related to the recent change (1.3.4) in how UI Fabric is included in SPFx. Now the SPFx Fabric Core Package is used and there is not yet support for Animations and Icons (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#spfx-fabric-core-package).

Unfortunately, this is a breaking change for existing solutions. Is there a way (perhaps a wrapper class, etc.) to enable this functionality again without having to include the Fabric React Components? Thanks!

**Comment by srideshpande** [comment]
@thechriskent - Thank you for reporting the issue. I will look into the extensions part of the issue. You also mentioned that it could happen with web parts. I don't think that is the case. Let me know if you see the icons missing in web parts.

**Comment by thechriskent** [comment]
You are correct, I've verified there is no problem with webparts

**Comment by andrewconnell** [comment]
Related #1287?

**Comment by StfBauer** [comment]
@thechriskent 
If the code for the icon is exactly the same way as you posted on this thread then This piece of code is malicious:

```css
<i class="ms-Icon ms-Icon--Pin aria-hidden="true"></i>
```

There is now ending quote for the class name.

```
<i class="ms-Icon ms-Icon--Pin" aria-hidden="true"></i>
```

Can you please verify this.

**Comment by srideshpande** [comment]
We have identified the issue with the extensions and will soon send out a fix for the same.

**Comment by thechriskent** [comment]
Not sure when this rolled out, but everything seems to be working with my extensions now! Thank you very much!

**Comment by srideshpande** [comment]
@thechriskent - I am glad its working for you now. It rolled out to public only yesterday i.e., 02/14. I was planning on updating this thread sometime today and you beat me to it :-)
