### ISSUE TITLE
No code in the latest @microsoft/load-themed-styles release

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1283]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When installing the latest modules for SPFx, the `@microsoft/load-themed-styles` dependency (v1.7.26) does not contain code. This breaks the Gulp process.

<img width="277" alt="screenshot 2018-01-26 13 32 33" src="https://user-images.githubusercontent.com/2900833/35443333-63f5df90-02b3-11e8-851e-6e784323321d.png">

<img width="256" alt="screenshot 2018-01-26 13 32 22" src="https://user-images.githubusercontent.com/2900833/35443339-6a6774c4-02b3-11e8-9021-4bb7a06b8b32.png">

When you run the build, you get the following error:

```
Cannot find module '@microsoft/load-themed-styles'
```

The previous version 1.7.25 contains the following folders:

<img width="256" alt="screenshot 2018-01-26 13 38 43" src="https://user-images.githubusercontent.com/2900833/35443358-7b547fca-02b3-11e8-99d7-c7a9ffbda059.png">

**Comment by VesaJuvonen** [comment]
Should be fixed now - latest version is 1.7.28 and that has the right packages now properly.
