### ISSUE TITLE
Modern SitePage un-anchor the heading in desktop mode

### ISSUE THREAD

**Issue by VelinGeorgiev** [SharePoint/sp-dev-docs#1284]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I can seamlessly scroll down leaving the chrome bar, application customizer and headings (title and logo) off the screen. Basically the green marked area should not be anchored and scroll-able.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/1049476/35446096-963028b0-02ab-11e8-98db-c669e8934402.png)

On smaller screen, the visible aria with content I am interested is only the red marked one. It is poor user experience and we should be able to disable the anchor of the header.

#### Steps to Reproduce
Have one application customizer extension installed and bring your browser to smaller resolution.

#### Submission Guidelines
Provide us with option to disable the anchor on the heading aria that includes the chrome bar, any application customizers, title and logo

**Comment by mcmynn83** [comment]
Thank you for your feedback.  This is by design as of now.  If you would like to have this changed please make a request in user voice.
