### ISSUE TITLE
Anonymous function in propertyPaneSettings does not work with imported modules

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#129]
Assigning an anonymous function to the onRender property of the PropertyPaneCustomField option does not allow jQuery calls. Not sure this is webpack issue or something else. I know the tutorial shows assigning a named function to the onRender property and this works. Here is the code using an anonymous function:

```
     groups: [
            {
              groupFields: [
                PropertyPaneCustomField('choices',{onRender:(elem) =>{
                   $(elem).kendoMultiSelect({
                      dataTextField: "text",
                      dataValueField: "key",
                      dataSource: {
                          data: searchSchema.getSchemaOptions(), sort: [{ 'field': 'text', 'dir': 'asc' }]
                      },
                      change: (e:kendo.ui.MultiSelectEvent) => {
                          this.properties.displayprops = JSON.stringify(e.sender.value());
                      },
                      value:JSON.parse(this.properties.displayprops)
                      });
                }})
              ]
            }
          ]

```
When accessing the $ alias for jQuery I receive a "Invalid character" error. 

"SyntaxError: Invalid character\n   at onRender (http://basesmc16:4321/dist/hyper-search.bundle.js:101:46)\n   at PropertyPaneCustomFieldHost.prototype.componentDidMount (http://basesmc16:4321/node_modules/@microsoft/sp-client-preview/dist/3.sp-client-preview-propertypane_53482bcda2fd60095a7c.js:610:10)\n   at notifyAll (http://basesmc16:4321/node_modules/react/dist/react.js:869:9)\n   at ON_DOM_READY_QUEUEING.close (http://basesmc16:4321/node_modules/react/dist/react.js:12870:5)\n   at Mixin.closeAll (http://basesmc16:4321/node_modules/react/dist/react.js:15699:11)\n   at Mixin.perform (http://basesmc16:4321/node_modules/react/dist/react.js:15646:11)\n   at Mixin.perform (http://basesmc16:4321/node_modules/react/dist/react.js:15633:7)\n   at perform (http://basesmc16:4321/node_modules/react/dist/react.js:13698:5)\n   at flushBatchedUpdates (http://basesmc16:4321/node_modules/react/dist/react.js:13759:7)\n   at wrapper (http://basesmc16:4321/node_modules/react/dist/react.js:12353:9)"

**Comment by waldekmastykarz** [comment]
Could it be that `this` in `this.properties` is mixed up with the function context? Have you tried creating a new variable for this and using that variable instead this in anonymous functions?

**Comment by SteveCurran** [comment]
Thanks Waldek. The stack trace led me in a bad direction. It was really just a null error. This fixed it, (STUPID)
value: this.properties.displayprops?JSON.parse(this.properties.displayprops):null

or just initialize the property in the manifest.

Typescript converts **this** into **_this** whenever the code is wrapped in an anonymous function

**Comment by waldekmastykarz** [comment]
It's confusing sometimes and checking the lib folder is the only way to tell if it's transpiled as expected. Glad to hear it's working! 😄
