### ISSUE TITLE
Property pane is not displaying the right value with multiple webparts

### ISSUE THREAD

**Issue by gbouveret** [SharePoint/sp-dev-docs#130]
When adding multiple webparts (for instance the default HelloWorld WebPart), if I open the properties pane directly for each webparts, it keeps the first value and does not refresh the real value of the other webparts.
Find attached the gif displaying the behavior (first webpart has a value equal "My Properties 1", second "My Properties 2", third "My Properties 3")

![spfxpropertiespaneissue](https://cloud.githubusercontent.com/assets/13414416/18160255/dd814f68-702c-11e6-9529-aacdfae2ec96.gif)

**Comment by manishgarg1** [comment]
VSO #244008

**Comment by srideshpande** [comment]
This is fixed.
