### ISSUE TITLE
Render method called many times

### ISSUE THREAD

**Issue by will101** [SharePoint/sp-dev-docs#1305]
Hi, I have an issue where the render method is called many times on a page that has an spfx webpart on it - this usually happens when navigating to a page from a hero webpart. 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When navigating to a page with a webpart on it from a hero , I expect the spfx webpart on a page to be rendered once.

#### Observed Behavior
The page I navigated to, will usually be rendered twice, if not more - the most I've seen is 4 times.This happens pretty consistently.

#### Steps to Reproduce
1. Make a new spfx webpart, select no JS framework, don't add any code into it 
2. Add a console.log to the render method: `console.log("Rendered!");`
3. Run gulp bundle, then gulp package-solution
4. Upload web part to your app catalog, install it on your site, then run gulp serve --nobrowser
5. Add a hero webpart to the home page, make another page with your web part on it
6. Add a link to the hero to your new page
7. Click the link in the hero web part and see how many times your console.log output is displayed

####Example code in render:
`
   ```
public render(): void {
 this.domElement.innerHTML = `
      <div class="${ styles.renderTest}">
        <div class="${ styles.container}">
          <div class="${ styles.row}">
            <div class="${ styles.column}">
              <span class="${ styles.title}">Welcome to SharePoint!</span>
              <p class="${ styles.subTitle}">Customize SharePoint experiences using Web Parts.</p>
              <p class="${ styles.description}">${escape(this.properties.description)}</p>
              <a href="https://aka.ms/spfx" class="${ styles.button}">
                <span class="${ styles.label}">Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>`;
   console.log("I rendered!");
  }
```

 `

####Example output in console:
![image](https://user-images.githubusercontent.com/10865627/35691871-971470ea-0771-11e8-9d84-4bf90a5c75d1.png)

It seems that if you navigate to the page the web part is on directly , it only renders once, if you go to the page from a link in the menu, it renders usually twice , and if you go there from a hero it will render usually 2 -4 times. Is this desired behaviour, or am I missing something?

**Comment by mcmynn83** [comment]
Unfortunately we do not guarantee that render will only get called once.  You should not rely on a single render.  However, we will look into this and try to understand why render is called multiple times, but please don't rely on that.

**Comment by will101** [comment]
Ok thanks, how do you reccomend on dealing with multiple renders and not duplicating output?
Thanks :)

**Comment by andrewconnell** [comment]
@will101 use the `BaseClientSideWebPart.renderedOnce` property on the base webpart:

```
  public render(): void {
    if (!this.renderedOnce) {
      this.domElement.innerHTML = `bla bla bla`;
    }
  }
```

**Comment by will101** [comment]
Ahhhh that's a really good idea, thank you sir!

**Comment by andrewconnell** [comment]
![image](https://user-images.githubusercontent.com/2068657/35705300-065b0880-0770-11e8-93f4-3a63c541506a.png)
