### ISSUE TITLE
[Documentation] Set up Machine Linux section

### ISSUE THREAD

**Issue by CalamityLorenzo** [SharePoint/sp-dev-docs#131]
I think you have a command wrong:
`sudo apt-get build-essential

should be
`sudo apt-get install build-essential

**Comment by patmill** [comment]
@chakkaradeep - Can you confirm and update the docs (and see if it applies to any of the other environments)?

**Comment by manishgarg1** [comment]
VSO #244029

**Comment by nickpape-msft** [comment]
This is the correct command. Docs have been updated.
