### ISSUE TITLE
apps missing  from app picker

### ISSUE THREAD

**Issue by telmocruz** [SharePoint/sp-dev-docs#1313]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have deployed an app to the App Catalog, i added the app to one site ecollection, and can select it on the homepage, however i can only do that in one site collection, in all off  the others i can add the app , but i cannot see it in the app picker, this is when adding it to a page
I am using the last SharePoint Framework version and using the setting "includeClientSideAssets": true, each time i deployed the app to the app catalog i incremented the version in the file package-solution.
I also called the rest service _api/web/GetClientSideWebParts and the web part is not returned

**Comment by tsekityam** [comment]
Perhaps this is another duplication of #775

**Comment by VesaJuvonen** [comment]
This should be now closed as part of the #775 fix. I'll close this for now as the issue should be fixed, but let's open a new one if you still have issues. Thx. 

--- --- -- -- - - - 

Fix - To be able to fully successfully fix this issue, you will need to perform following steps in your SharePoint Online tenants.

Remove all instances of existing SharePoint Framework solutions from site level
Remove SharePoint Framework solution from app catalog
Upload new SharePoint Framework solution built with 1.4.1 version to your app catalog
Install SharePoint Framework solutions back to sites.
