### ISSUE TITLE
Where to set the WebPart description and group name?

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#132]
I am setting the WebPart description in the below file but it is not appearing in the ribbon pane when i add a new WebPart? Am I configuring at the right file or is it a bug?

**Note**: WebPart Group name still shows Custom but i have configured with name "Productivity" in the MessageCenterWebPart.manifest.json file.  

![image](https://cloud.githubusercontent.com/assets/21008316/18176870/25e374b0-703d-11e6-9343-440b915f65aa.png)

![image](https://cloud.githubusercontent.com/assets/21008316/18176934/6f5e29e6-703d-11e6-99c9-b50da364a812.png)

**Comment by waldekmastykarz** [comment]
Check the contents in the **sharepoint/solution/debug** folder. In a folder named using a GUID there should be a .webpart file. If that file doesn't contain the values from the manifest then I would say it's a bug that should be fixed given that Client Side Web Part are supposed to work correctly both with modern and classic Team Sites.

**Comment by sprider** [comment]
.webpart file contains the right values

![image](https://cloud.githubusercontent.com/assets/21008316/18177243/f291d9ce-703e-11e6-9bcd-3594c0b1ff59.png)

**Comment by manishgarg1** [comment]
VSO #242882

**Comment by nickpape-msft** [comment]
Looks like a server-side bug. @chackman ?

**Comment by sayitfast** [comment]
Same exact issue here...

**Comment by sprider** [comment]
Is it fixed in the latest SPFX release?

**Comment by sayitfast** [comment]
Yes... I actually spent some time last night and it does work for me. I might have had an older build.

**Comment by chakkaradeep** [comment]
Just to update one little thing, we no longer deploy the .webpart file in the package. So, make sure the web part manifest contains the relevant details.

**Comment by sprider** [comment]
Can i close this issue ?
