### ISSUE TITLE
Running .app

### ISSUE THREAD

**Issue by freedumz** [SharePoint/sp-dev-docs#1324]
Hello Everyone, 
I finally succeeded to install my app on SharePoint online but I still have a problem

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Using apps which I install on my SharePoint server 

#### Observed Behavior
Once the apps are installed and I try to launch them, I get a loading screen which last forever 

#### Steps to Reproduce

So my apps are running on another server so I'm sure that they work

So wat I did:
.Install the apps on my SharePoint administration
-Going on my PWA project, and install the three apps
Until here, no error message, everything looks like good

But when I launch my app, I've the loading screen of the death

Any ideas of what I could do to resolve this problem?

Many thanks in advance

**Comment by VesaJuvonen** [comment]
Hi @freedumz - can you clarify the environment details on this, since your text mentioned also SharePoint Server. If that's your on-premises server, it seems to then have some misconfiguration around the apps/add-ins, which farm administrator should double check.

**Comment by VesaJuvonen** [comment]
@freedumz - any change getting more details on the question.

**Comment by VesaJuvonen** [comment]
Closing this for now due to no response. Let's reopen if the issue still is active.
