### ISSUE TITLE
Apps stuck at "We are removing your app"

### ISSUE THREAD

**Issue by submarines-and** [SharePoint/sp-dev-docs#1325]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Click an installed app, select remove. After a while the app will be removed and placed in the recycle bin.

#### Observed Behavior
The app get stuck at "We are removing your app", since 2 days back. I suspect this might be related to the previously reported: [app-issue](https://github.com/SharePoint/sp-dev-docs/issues/1318)

#### Steps to Reproduce
Try to remove an app following the steps above. Applies to apps removed 2 days ago, yesterday and today! :)

**Comment by MuellerEric** [comment]
I have the same kind of behavior while trying to update an app. SharePoint Online (Office 365) has been saying for 2 days that the app is beeing updated.

**Comment by Pieter-Veenstra** [comment]
There seems to be an issue in office 365 with the spfx app deployments. We're in a the middle of a major production update at the moment. First the deployment now the removal is stuck. Is there anything we can do to get this up and running?

**Comment by matmig** [comment]
We have the same issue on EU O365. I was trying to upgrade my App instance to newer version using update, but waiting hours, without success. Then I decided to remove this app and in next step upload newer version, but removing stucked with message "We're removing your app...". 
I will add only that yesterday we had also problem with [app-issue](https://github.com/SharePoint/sp-dev-docs/issues/1318), but it was fix today morning.

**Comment by submarines-and** [comment]
This was resolved for us during the night. Everything is now working properly again! Thank you.

**Comment by VesaJuvonen** [comment]
There were some issues with our timer jobs recently, but those should be now properly fixed. Will close this for now, but please open a new item, if you see these kinds of issues. Thx.

**Comment by AJIXuMuK** [comment]
Have that issue right now for SPFx solution.
<img width="642" alt="screen shot 2018-05-10 at 9 37 07 am" src="https://user-images.githubusercontent.com/17036219/39881431-ce40d37c-5435-11e8-8e0f-73b522f546f1.png">

**Comment by ravick4u** [comment]
I got the same issue today and its stuck on "We're removing your app..."

**Comment by ravick4u** [comment]
After sometime got this message
![temp](https://user-images.githubusercontent.com/11890407/43986890-bcf0d988-9ce6-11e8-9364-7b22da27916a.png)

**Comment by ravick4u** [comment]
Similar problem on adding app
![temp](https://user-images.githubusercontent.com/11890407/43986904-f872de8e-9ce6-11e8-9f63-9472d1c46575.png)

**Comment by dproietti412** [comment]
I have the same problem. The upgrade has been blocked for more than one hours; I tried to cancel the update and now the state of the app is in "UpgradeCanceling" from two hours.

**Comment by lovyjain** [comment]
I am getting this issue again from this morning
