### ISSUE TITLE
Application Extensions/placeholders not visible in SharePoint Mobile App

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1328]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When browsing a site using the SP Mobile App (iOS) I expect my headers/footers added in place holders using application extensions to be visible.

#### Observed Behavior

Headers and footers are not visible in the SharePoint Mobile app native experience, however if you go to certain pages in SharePoint, rendered in the embedded browser, they are visible. This gives a non-coherent experience for the end users.

#### Steps to Reproduce
Browse a site that has an application extension and adds HTML to any place holder on the SP Mobile app

**Comment by sparkitect** [comment]
We have this issue as well for a customer. On the pages where it does show, it floats at a random location on the screen and is randomly behind or in front of other content.

As a work-around, perhaps we need to add CSS that will hide it from smaller screens (with a media query or whatever it's called).

**Comment by wictorwilen** [comment]
Closing an old thread, this is working now.
