### ISSUE TITLE
SPFx - isRenderAsync + renderCompleted - How To?

### ISSUE THREAD

**Issue by everettcomstock** [SharePoint/sp-dev-docs#1332]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Overriding the BaseClientSideWebPart isRenderAsync property will lead to the calling of the renderCompleted method.

One note, I am unsure when the renderCompleted method will be called. My assumption is that it will be called after the Render method, but I have not found a concrete guide for the SPFx web part event lifecycle.

#### Observed Behavior
Overriding the isRenderAsync property using the following syntax seems to fail:

  get isRenderAsync() {
    return true;
  }

The renderCompleted method is not called.

#### Steps to Reproduce
Override the isRenderAsync property and the renderCompleted method:

  get isRenderAsync() {
    return true;
  }

  protected renderCompleted(): void {
    // Do stuff
  }

Any guidance or suggestions will be greatly appreciated. Thanks!

**Comment by DominicArchual** [comment]
+1 More documentation or an explanation would be helpful.

**Comment by luismanez** [comment]
Agreed it needs clarification. In the meantime, I´ve done a quick test, and seems is your responsibility to call that method when your async operation is done. Maybe this code makes not great sense, but it works as would be expected:

```js
public render(): void {
    this.domElement.innerHTML = `
      <div class="${ styles.helloWorld }">
        Loading...
      </div>`;

      this.context.httpClient.get("https://jsonplaceholder.typicode.com/posts/1", HttpClient.configurations.v1).then(data => {
        console.log(data);
        this.renderCompleted();
      });
  }

  protected renderCompleted(): void {
    console.log("renderCompleted");
    this.domElement.innerHTML = `
      <div class="${ styles.helloWorld }">
        Hello World Completed
      </div>`;
  }

  protected get isRenderAsync(): boolean {
    return true;
  }
```

As I see in the BaseClientSideWebPart.js, there´s no any explicit call to the renderCompleted method, so I´m pretty sure you have to call it explicitly. Also, if you don´t call it, after some seconds, you can see a Log message in the console saying so.

**Comment by luismanez** [comment]
Just realised I forgot to call the parent renderCompleted method: super.renderCompleted() (otherwise the Timeout is not killed and you will get the error in the console after 25 seconds)...

```js
protected renderCompleted(): void {
    super.renderCompleted();
    console.log("renderCompleted");
    this.domElement.innerHTML = `
      <div class="${ styles.helloWorld }">
        ${this._data}
      </div>`;
  }
```
