### ISSUE TITLE
JSON Formatting and Field Customizer can't be applied to the same view (DIFFERENT columns)

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1336]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
User/Developer can apply JSON formatting to one column and Field Customizer to another without issues.
#### Observed Behavior
If both JSON formatting and Field Customizer are applied to two columns in the same list view it will crash with something went wrong (see screenshot):
<img width="1497" alt="screen shot 2018-02-08 at 2 46 51 pm" src="https://user-images.githubusercontent.com/17036219/36002601-96cf6d7e-0cdf-11e8-83cf-a0e2dd133cdb.png">

#### Steps to Reproduce
1. Create simple list
2. Add column to the list (any type: Single line of text, Number, Choice, etc.)
3. Apply JSON Formatting to any of two columns in the view
4. Apply simple Field Customizer to another column (you can use the customizer that is created from Yeoman template without changes; also the issue is reproduced both in debug mode and if the package is deployed)
5. **List crashes**

**Comment by AJIXuMuK** [comment]
And while fixing this one, please, also check that list doesn't crash if for some reason user applied both JSON Formatting and Field Customize to the same column.

**Comment by ahackettms** [comment]
The bug has been fixed and should be available to customer in the next 2-3 weeks. Thank you for reporting the issue

**Comment by AJIXuMuK** [comment]
@ahackettms awesome! Thanks for the update!

**Comment by VesaJuvonen** [comment]
thx @ahackettms for confirming the status. Let's keep this open until we can confirm that things have been successfully fixed.

**Comment by mpasarin** [comment]
The fix has been rolled out and there's been feedback that this is still reproducing.
Closing the issue.
