### ISSUE TITLE
Is it possible to set the welcome / home page for a web/site?

### ISSUE THREAD

**Issue by Nasicus** [SharePoint/sp-dev-docs#1339]
#### Category
- [x] Question

I put some time into researching this and I already believe it's not possible, but just to be sure (and also for future "googlers") I'd like to ask this:

Is it possible to set the welcome page / home page of the web where an SPFx app is installed?
If so how? Somehow via the manifest or via a feature?

**Comment by Nasicus** [comment]
Found a solution myself :)

Basically you'll need a feature for it and add it there.

Example `package-solution.json`:
```
{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "MatchPoint O365 Core",
    "id": "416b9b7c-5b8d-417b-ac86-0ae6a9cf43d5",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "features": [
      {
        "title": "Whatever",
        "description": "Whatever",
        "id": "1410ae70-2ce9-426a-8686-471496449251",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml"
          ]
        }
      }
    ]
  },
  "paths": {
        "zippedPackage": "solution/Whatever.sppkg"
  }
}
```

`elements.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <PropertyBag Url="" ParentType="Folder" RootWebOnly="FALSE">
    <Property Name="vti_welcomepage"
              Type="string" Value="SitePages/matchpoint_hub.aspx" />
  </PropertyBag>
</Elements>
```

Source:
https://consultantpoint.wordpress.com/2015/02/02/set-a-web-templates-welcome-page-url-declaratively-without-using-the-publishing-feature/

**Comment by VesaJuvonen** [comment]
There are also few other ways to achieve this... with UI by selecting a page as a welcome page or by running REST APIs to set any page as a welcome page.

![image](https://user-images.githubusercontent.com/7446437/36195571-99fcbcfe-1176-11e8-9c17-7a736f0553c8.png)

or 

![image](https://user-images.githubusercontent.com/7446437/36195581-a2c1dd56-1176-11e8-967b-a91c2e5e87a7.png)
