### ISSUE TITLE
Public CDN SharePoint Online Get File Error 500

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#1340]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Observed Behavior
Hi,
I have a sharepoint library enabled as a CDN and when I try to reference for example a js file in my SPFx component, it gives me a 500 error.

Can it be a problem in the SharePoint Online CDN?

![1](https://user-images.githubusercontent.com/33054287/36020753-fbc857fa-0d83-11e8-9051-1add3377bc0d.png)

![3](https://user-images.githubusercontent.com/33054287/36087506-00697dc4-0fd3-11e8-9c28-4f9e144f4c44.PNG)

![2](https://user-images.githubusercontent.com/33054287/36020763-03be0482-0d84-11e8-8b6e-3c4b01f6fd74.png)

Thanks!

**Comment by VesaJuvonen** [comment]
Hi @sortegamartin, any change you could share your CDN settings and then for detailed investigation we would need to know your tenant URL, which you can send me an email / or a private message, for example, form the MS tech community. Thx.

**Comment by patmill** [comment]
Closing this down for now.
