### ISSUE TITLE
SPFX (SharePoint 2016) Typescript Version compatibility issue with Office-ui-fabric-react

### ISSUE THREAD

**Issue by avinash-sah24** [SharePoint/sp-dev-docs#1343]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
As Latest Office-ui-fabric support TS 2.4. and SPFX webpart ( SharePoint 2016 ) supports 2.2.x.
It is giving typescripts error when I am trying to use Office-ui-fabric components.
By When SPFX ( SharePoint 2016 version) Typescript will get upgraded to 2.4?? OR is there any work around ?

#### Steps to Reproduce
create SPFX webpart project using yeoman SharePoint Generator. select SharePoint 2016 with Online.
Now install Office-ui-fabric-react , then try to add any of office ui fabric component.

Note: SPFX for Only SharePoint Online everything is working fine.

**Comment by VesaJuvonen** [comment]
We are not planning to invest to increase the supported TypeScript version in on-premises for now. We do understand the ask, but also have to prioritize our resources on other tasks. This statement might though be changed if there's clear demand cross multiple customers on this topic.

**Comment by hohenp** [comment]
Hi Vesa, we do have a similar problem using the Telerik Kendo UI React Wrappers. We are in preparing to migrate our WSPs to SPFx OnPrem16 (and OnPrem19TAP) in the moment.

The telerik react wrappers are running with the SPFx SPO Version using typescript 2.4.2 but are not running with the OnPrem Version that uses typescript 2.2.2.

So for us it would be very helpful to understand in which timeframe you have plans to update the onprem spfx versions. As our target is SP2019 we are not really in a hurry yet, but would be nice to be informed about the rough plans for spfx onprem updates (maybe in one of the next calls...)

Thx a lot!

**Comment by AJIXuMuK** [comment]
@hohenp [this thread](https://github.com/SharePoint/PnP-JS-Core/issues/741#issuecomment-371637622) contains a workaround
