### ISSUE TITLE
successive renderError in StatusRenderer does not update error text

### ISSUE THREAD

**Issue by JohnMutters** [SharePoint/sp-dev-docs#1345]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The error text that was sent with the latest renderError call should be overriding text of previous calls.

#### Observed Behavior
A successive renderError call reuses the error div element if it is already present in the DOM by showing it again. It, however, does not update the error div html. A formerly generated error message div is shown without updating the error message text sent along with the latest renderError call.

Taken from the _renderError_ function (sp-webpart-base):

`var divErr = domElement.querySelector("div[data-sp-id='" + this._errorId + "']");
if (divErr) { 
    divErr.style.display = 'block';
}
else { <  error html div generated here >`
        
#### Steps to Reproduce
The easiest way to reproduce this behavior is by having two successive renderError calls executed:
`this.context.statusRenderer.renderError(this.domElement, "Msg 1.");`
`this.context.statusRenderer.renderError(this.domElement, "Msg 2.");`

This shows a _Msg 1_ text instead of _Msg 2_

**Comment by mpasarin** [comment]
Thanks for your feedback @JohnMutters 
We'll look into this issue shortly and will keep you updated.

**Comment by dgaeta** [comment]
@JohnMutters The fix has been made and it will be in the next release. Thanks for bringing this issue to light.
