### ISSUE TITLE
SPFX extensions (List view command set)

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-docs#1346]
SPFX extensions (List view command set)

#### Category
- [.] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
SPFX command set should be visible on all the command menu ? 

#### Steps to Reproduce

Wanted to edit the Command bar in site pages. Can anyone help me with the same. 

![image](https://user-images.githubusercontent.com/10346150/36094368-ed7aeefa-1013-11e8-8be2-d05eb34c9d1e.png)

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Having list view command sets is only supported in the list or library level. It is not yet supported on the page toolbar.

**Comment by ryanjonhealy** [comment]
Are they supported on the "SitePages" library?
