### ISSUE TITLE
The sharepoint folder is not excluded from the source control

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#135]
The sharepoint folder is not excluded from the source control. Given that its contents are generated during the build process, it should be excluded from the source control similarly to lib, dist and temp.

**Comment by manishgarg1** [comment]
VSO #244294

**Comment by nickpape-msft** [comment]
The sharepoint folder also contains the custom feature XML, which is why we haven't excluded it.

However, we did add `sharepoint/solution` and `*.spapp` to the gitignore. You should be seeing this in drop 2.
