### ISSUE TITLE
Is it possible to use SPFx extensions to customize command bar in modern page in communication site?

### ISSUE THREAD

**Issue by jayeshvg** [SharePoint/sp-dev-docs#1352]
Currently we can use SPFx extensions to customize command bar in List view, Site content page or Library. Is it possible to customize command bar of home/article page in communication site?

**Comment by VesaJuvonen** [comment]
Unfortunately, that's not supported currently. Technically you can have list view command set in pages library, but that's not yet visible in page view side.
