### ISSUE TITLE
Field Customizer extension is not applied after editing column settings

### ISSUE THREAD

**Issue by tkubatova** [SharePoint/sp-dev-docs#1354]
#### Category
- [ ] Question
- [ ] Typo
- [ x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Field Customizer is applied after editing the column settings by clicking on column header in list or library.

#### Steps to Reproduce & Observed Behavior
Steps to reproduce the bug:
1. Create new column with field customizer.
2. Add the column to your list or library.
3. Click on column header in your list or library.
4. Select "Column Settings" -> Edit
5. Click "Save".

Result: Field Customizer is not applied. See picture below.

![bug](https://user-images.githubusercontent.com/33957054/36200855-e0dd4a72-1175-11e8-8f99-d54fbf19f746.png)

BTW When you update the column in library settings or when you update column name by "quick edit" everything works as expected.

Thank you
Tatana Kubatova

**Comment by AJIXuMuK** [comment]
Sorry for the super long delay on this one.
The issue should be fixed by now. 
@tkubatova could you please check on your end?
Thank you!
