### ISSUE TITLE
Share button when viewing a message in Office Admin Center is not showing proper text for the message

### ISSUE THREAD

**Issue by kimhope** [SharePoint/sp-dev-docs#1356]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

![image](https://user-images.githubusercontent.com/29739513/36224659-1e721d5c-117d-11e8-9465-a386abc674aa.png)

#### Expected or Desired Behavior
I expect to see the text of the item I am planning to share.

#### Observed Behavior
Sometimes I see the text for the message I want to send and sometimes I see the text for a message I looked at a previously, in the first image it was about 4 items down and in the second image it was the message before.

#### Steps to Reproduce
I am not exactly sure.  I look at message center messages and opened some to read and then clicked share and sometimes the correct text showed up.  Then I closed that one opened a few others and finally choose one to share and observed that the message text was not for the one I wanted.  Some sequence of opening and closing and then sharing causes this to happen, here it is again in this image:

![image](https://user-images.githubusercontent.com/29739513/36224999-24349eda-117e-11e8-9e43-2c886275185c.png)

**Comment by VesaJuvonen** [comment]
Thanks for submitting the issue details. We have bypassed the issue description forward to the appropriate team. As this is not really about SharePoint dev topics, will close this from here, but the issue should be fixed sooner or later in the admin UIs.
