### ISSUE TITLE
Document the possibility to enable Office 365 CDN without origins

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1361]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

Using SPO PowerShell it's possible to enable the Office 365 CDN without provisioning the default origins. Document the purpose of this capability and its consequences on SharePoint Framework solutions.

**Comment by skaggej** [comment]
Does this article give enough detail? It provides the example, but not sure if it goes into enough detail on consequences on SPFx solutions.

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/office-365-cdn

**Comment by waldekmastykarz** [comment]
Yes, it does.
