### ISSUE TITLE
Provisioning complex Assets

### ISSUE THREAD

**Issue by marcelaopimenta** [SharePoint/sp-dev-docs#1362]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi Guys,

Currently in SPFX the assets that i can provision are:

Fields
Content types
List instances
List instances with custom schema

In PnP we can provision Pages, MasterPages, Pages Layouts, complex Content Types, etc.

In SPFX is possible? If not, it´s in Roadmap?

Best Regards

**Comment by VesaJuvonen** [comment]
Technically you could provision other assets also from SPFx solutions, but it does get a bit complicated. Given the direction with SharePoint Online, master pages or page layouts are also no longer used as such. We are not looking into investing more in here at least through SPFx solutions, rather through other areas.

**Comment by VesaJuvonen** [comment]
a
