### ISSUE TITLE
Adding additional properties

### ISSUE THREAD

**Issue by DeanGross** [SharePoint/sp-dev-docs#1363]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I see "Tenant Properties", I naturally think of the properties listed on the various pages in the SPO Admin Center, but when I look at this list, very few of those properties are listed. Are there any plans to provide the ability to work with all of the other properties?

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Thre's different meanings on both words - Tenant and Properties. SPFx tenant properties mean runtime support for storing tenant scoped values - properties... for custom code. If you are however looking for adjusting your tenant behavior, then you should be looking into SPO Management Shell and Tenant object in CSOM, which exposes all supported properties and methods.
