### ISSUE TITLE
Incorrect resource property reference in the schema for webApiPermissionRequests

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1364]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Following the tutorial to test out the new Graph and AAD clients (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial), it mentions adding the Microsoft Graph permission scope to `package-solution.json` file, but the schema validation shows an error on the `resource` property. 

<img width="325" alt="screenshot 2018-02-16 09 30 15" src="https://user-images.githubusercontent.com/2900833/36299153-0244a1e2-12fc-11e8-94e1-2d9d6dff3cd5.png">

It seems that in the current schema, the property has to be `resourceId`, but changing it results in a build error:

```
Error - Unknown
 JSON validation failed:
/v1.4.1/config/package-solution.json

Error: #/solution/webApiPermissionRequests/0
       Missing required property: resource
Error: #/solution/webApiPermissionRequests/0
       Additional properties not allowed: resourceId
```

Probably the schema has to get updated with the correct property name.

**Comment by wictorwilen** [comment]
The schema at `https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json` says `resourceId`, which is what VSCode uses for validation, but the `@microsoft/sp-build-core-tasks` version of the schema says `resource`.

**Comment by wictorwilen** [comment]
Some extra info; the generated `AppManifest.xml` in the `.sppkg` file uses `ResourceId`. (and no, if you change it to `resource` the upload will fail with an invalid manifest error)

**Comment by CloudDesignBox** [comment]
Same issue, are there any workarounds? resource causes error when uploaded to app catalog and ResourceId errors on build....

**Comment by patmill** [comment]
Looking into this.  Can you confirm that you are running in a FirstRelease tenant (not user, but tenant)?

**Comment by patmill** [comment]
OK.  Sorted this one out.  The bug got a bit confused, because it is looping in part of this bug (https://github.com/SharePoint/sp-dev-docs/issues/1365) as well.  The workaround for this is "ignore the squiggles".  We'll update the online json schema as soon as possible.  Unfortunately that might take a bit longer than we would like.

**Comment by wictorwilen** [comment]
Yes, it works perfectly if you ignore the squiggly warnings in VS Code. But as you said, #1365 is what's prohibiting this now. And yes, it's a targeted release tenant

**Comment by lucaband** [comment]
so, considering #1365 has been resolved, you guys think that this one can be closed as well?

**Comment by CloudDesignBox** [comment]
It now works fine for me, although the schema still is incorrect....and wiggly lines exist but app does work in app catalog without errors.

**Comment by wictorwilen** [comment]
@lucaband - keep this until you've fixed the schema error in VS Code

**Comment by VesaJuvonen** [comment]
Let's keep this indeed open until we get the schema updated. Work in progress.

**Comment by andrewconnell** [comment]
Schema appears fixed... can't repo.... closing as fixed.
