### ISSUE TITLE
Using webApiPermissionRequests in the solution configuration results in application error

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1365]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Following the tutorial about using the new Graph and AAD clients (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial). There seems to be an issue when deploying my solution to any of my tenants. When adding the solution, it returns `Error in the application.`.

Also tested it with a clean solution and just adding the `webApiPermissionRequests` property to the `package-solution.json` file. Which results in the same error.

<img width="1499" alt="screenshot 2018-02-16 11 34 09" src="https://user-images.githubusercontent.com/2900833/36303705-5280e25e-130d-11e8-858c-e80ef18b58b8.png">

Tested it in three tenants, all with first release feature turned on.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce

- Create a new project
- Add the following to the `package-solution.json` file

```
"webApiPermissionRequests": [
  {
    "resource": "Microsoft Graph",
    "scope": "User.ReadBasic.All"
  }
]
```

- Bundle and package the solution
- Upload the solution to the app catalog

**Comment by patmill** [comment]
Looking into this.  Can your confirm that you are running in a FirstRelease tenant (not user, but tenant)?

**Comment by wictorwilen** [comment]
Yes, targeted/first release tenants.

**Comment by patmill** [comment]
Hey folks - can you try the upload again?

**Comment by estruyf** [comment]
Seems to be working!

**Comment by patmill** [comment]
Perfect - thanks for the heads up.  Weirdness with how first release tenants were being calculated.

**Comment by papouuu** [comment]
Hi, I have same error, should I open a new issue?

**Comment by kristianbkjaer** [comment]
I have this error on a tenant not running "First release". It works fine on my "First release" tenant. Any clues on when it will be available in a prod release?
