### ISSUE TITLE
Remove mock data from Microsoft default web parts

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1367]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I expect small and efficient bundles from the default web parts

#### Observed Behavior
I can see mock data in the default web parts. For instance the *People* web part contains mock data for a bunch of Contoso people adding almost 2K of extra data.

#### Steps to Reproduce
Use your favorite network sniffer and look into the sp-people-webparts-bundle-*.js and search for `contoso`

**Comment by andrewconnell** [comment]
Ugh... good find. That's nasty & totally unnecessary!

**Comment by andrewconnell** [comment]
You still seeing this @wictorwilen ? Just looked and seems like the sample data has been removed...
