### ISSUE TITLE
Administrator awareness of present of non-NoScript sites

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1368]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Given the (awesome) new features with easier access to retrieving bearer tokens for secured resources, this is also potentially opening up huge security issues. Since anything on a page can access the consented permissions, script injections can be used to use on these sites in non-expected ways. 

SharePoint today has a feature to prevent some malicous scripts from being executed on a page through the **NoScript** setting, although this is only present on all sites for newer tenants or the *Modern* sites. There are many tenants and site collections out there that still are script enabled; either before the default behavior was changed or deliberatly changed to inject arbitrary JavaScripts, and this impose a security risk and an awareness situation, unless the admins roll their own scripts or similar to check for this.

I recommend that some kind of information is introduced in the new *API Management* page in the admin center to show that there are one or more non-NoScript sites and also the possibility to list them and eventually make them into NoScript sites.

**Comment by JeremyKelley** [comment]
This is a great suggestion, you probably want to add it on UserVoice so it can get votes there.  It's definitely something that's been talked about but no imminent plans to share.

**Comment by wictorwilen** [comment]
Done!

https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33358639-administrator-awareness-of-present-of-non-noscript

**Comment by VesaJuvonen** [comment]
Thx @wictorwilen, appreciate the entry in UserVoice.
