### ISSUE TITLE
Lost node_modules after upgrading to SPFx 1.4.1 and node 8.9.4

### ISSUE THREAD

**Issue by SPParseError** [SharePoint/sp-dev-docs#1369]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Just upgraded my stack for SPFx : 
- Node 8.9.4
- Latest generator for SPFx

I create a new SPFx project using yeoman, and I check the versions number of each package to update my existing project's package.json. Here is my new setup : 

![image](https://user-images.githubusercontent.com/12406819/36314151-343d3c1c-1334-11e8-8f92-103940b16cce.png)

To make sure I have a proper setup, I do rm -rf node_modules\ & npm install

I then can't compile my project because no module is found for microsoft/sp-loader, microsoft/sp-http, microsoft/sp-page-context and uifabric/utilities. Error showing in VSCode and on gulp build (error TS2307: Cannot find module 'uifabric/utilities' in each of my components using uifabric/utilities)

After searching those in my node_modules, I don't have them anymore directly in the folder

**Comment by SPParseError** [comment]
Note : manually installing each missing module threw npm install --save, I have new errors like "Argument of type 'SPPermission' is not assignable to parameter of type 'SPPermission'". I think I didn't get the same version.

**Comment by SPParseError** [comment]
Other note : I do have folders for uifabric and other modules in node_modules for a new generated project

**Comment by patmill** [comment]
So, a couple of questions.  1 - if you create a new project starting at the yeoman generator, do you encounter problems?  2 - Did you run gulp clean ?

**Comment by patmill** [comment]
One other question - what was your version office office-ui-fabric-react before you updated, and what version that actually got installed in your node_modules folder?

**Comment by patmill** [comment]
And one final question - can you paste the full sppermissions error

**Comment by SPParseError** [comment]
Here is the full sppermissions error : 
![image](https://user-images.githubusercontent.com/12406819/36356405-03dc1614-14f2-11e8-8e11-00b724a8d246.png)

The code firing this is this line : 

this.isNoScript = this.context.pageContext.web.permissions.hasPermission(SPPermission.addAndCustomizePages);

Similar error happens with object pageContext.

**Comment by SPParseError** [comment]
I didn't change the version of office-ui-fabric-react before and after updating my project

**Comment by SPParseError** [comment]
I imported one of the files throwing the error with SPPermission in HelloWorldWebPart from a complete new project : the project is building perfectly.

Yes I ran rm -rf node_modules before npm install, and gulp clean before gulp build or gulp bundle

The folders node_modules/@microsoft from my existing project with manual install on sp-http, sp-loader and sp-webpartbase don't have the same elements : 

In my existing project (didn't have sp-http, sp-loader and sp-webpart-base before manual install)
![image](https://user-images.githubusercontent.com/12406819/36356506-5960cab6-14f3-11e8-9604-347c05cf53ee.png)

In the new generated one
![image](https://user-images.githubusercontent.com/12406819/36356515-6df3ad9a-14f3-11e8-8f7b-f242a67b9c13.png)

**Comment by SPParseError** [comment]
Going back to node v6.12.1 using Docker, my existing project builds perfectly after rm -rf node_modules & npm install. 

Looks like a problem I have with node 8.9.4

**Comment by SPParseError** [comment]
Update : It works after replacing npm with yarn.  

Found some issues on the web with npm not installing all module dependencies, and some co workers had issues even with node 6.12.1. Used yarn and have no error...

**Comment by patmill** [comment]
Sorry for the delay, on vacation at the moment.  

Unfortunately, our experience is that npm 5 has not been the best package management software.  One suggestion is to use Yarn (as you have done), another is to revert back to npm 4 (but you can keep using Node 8).  Internally we use pnpm for our build system.

That said, I tried a repro with the following versions, and it compiled / built without issue:
OS - Windows 10
Node version -  8.9.4
npm version - 5.6.0

package.json - referencing 1.4.1

import { SPPermission } from '@microsoft/sp-page-context';
...
    this.isNoScript = this.context.pageContext.web.permissions.hasPermission(SPPermission.addAndCustomizePages);

It's possible that npm is messing up with some other package.json dependencies that I don't have.  It worked on my project, then npm failed to install react when I added all your package.json entries, then decided that it would fail to build at 
[17:14:27] Starting subtask 'sass'...
[17:14:29] Error - [sass] Error: ENOENT: no such file or directory, scandir 'c:\Users\patmill\code\teamspfx\node_modules\node-sass\vendor'
[17:14:29] Error - 'sass' sub task errored after 2.11 s
 ENOENT: no such file or directory, scandir 'c:\Users\patmill\code\teamspfx\node_modules\node-sass\vendor'
[17:14:29] 'build' errored after 2.33 s
then nuking node_modules and reinstalling (adding es2017 to the lib options in tsconfig to get Promise.resolve() to not barf), then after all that, another node_modules delete, npm install, build cycle worked.  So.... yeah.  npm?

**Comment by SPParseError** [comment]
Thanks for your answer and the time you took to test.

Closing the issue, it doesn't seem like an SPFx issue, but a npm one.

**Comment by waldekmastykarz** [comment]
Could it be that you didn't remove the lockfile which is why npm tried to install old packages from the previous version of SPFx?

**Comment by pedropablo** [comment]
@waldekmastykarz at least in my case that was it. Didn't noticed a teammate created a lockfile. Thanks!
