### ISSUE TITLE
Adding new Web Part using generator-sharepoint doesn't work after pulling the project from source control

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#137]
If you pull an existing project from source control and try to add a new Web Part using generator-sharepoint, the generator will try to scaffold the whole solution rather than only add a new Web Part. This is caused by the **.yo-rc.json** file, used for determining whether the folder contains an existing project or not, being excluded from source control in .gitignore.

**.yo-rc.json** should be included in source control to keep generator-sharepoint working as expected both with projects created locally as well as with projects pulled from source control.

**Comment by nickpape-msft** [comment]
This has been fixed, and you will see it in the next drop (Drop 3). I'll close the bug when we do that drop. Thanks!

**Comment by manishgarg1** [comment]
VSO #244603

**Comment by patmill** [comment]
Bit slow on closing bugs.  This has been fixed.
