### ISSUE TITLE
Dialog from sp-dialog library won't appear in either local or hosted Workbench

### ISSUE THREAD

**Issue by ypcode** [SharePoint/sp-dev-docs#1371]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I wanted to use a custom Dialog following the doc here (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx). While this documentation only refers to SPFx extension, I use it here in a SPFx WebPart

#### Observed Behavior
The dialog never appeared in either local or hosted workbench, while it did when trying the WebPart in a real Modern Page. However, I don't get any error message. and none of the code of the component or the promise result seems to be executed)
I realized the BaseDialog class refers to a domElement. I would think this element just cannot be found in the Workbench page

#### Steps to Reproduce
Here is my code for my custom dialog
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { DialogContent, DialogFooter, DefaultButton, PrimaryButton , autobind } from 'office-ui-fabric-react';
import { BaseDialog, IDialogConfiguration } from '@microsoft/sp-dialog';

export interface IConfirmBoxProps {
	title?: string;
	message?: string;
	onConfirm: () => void;
	onCancel?: () => void;
}

export class ConfirmBoxComponent extends React.Component<IConfirmBoxProps, {}> {
	public render(): React.ReactElement<IConfirmBoxProps> {
		return (
			<DialogContent
				title={this.props.title || 'Confirm'}
				subText={this.props.message || 'Are you sure ?'}
				onDismiss={this._onCancel}
				showCloseButton={true}
			>
				<DialogFooter>
					<PrimaryButton text="OK" title="OK" onClick={this._onConfirm} />
					<DefaultButton text="Cancel" title="Cancel" onClick={this._onCancel} />
				</DialogFooter>
			</DialogContent>
		);
	}

	@autobind
	private _onConfirm() {
		this.props.onConfirm();
	}

	@autobind
	private _onCancel() {
		if (this.props.onCancel) {
			this.props.onCancel();
		}
	}
}

export class ConfirmBox extends BaseDialog {
  public isConfirmed: boolean = false;
  public message: string;
  public title: string;

	public render(): void {
		ReactDOM.render(
			<ConfirmBoxComponent
				onConfirm={this._confirm}
				onCancel={this._cancel}
				title={this.title}
				message={this.message}
			/>,
			this.domElement
		);
	}

	public getConfig(): IDialogConfiguration {
		return {
			isBlocking: false
		};
	}

	@autobind
	private _confirm(): void {
		this.isConfirmed = true;
		this.close();
	}

	@autobind
	private _cancel(): void {
		this.isConfirmed = false;
		this.close();
	}
}

```
And the calling code snippet

```
    const confirm: ConfirmBox = new ConfirmBox();
		confirm.message = `Are you sure you want to delete this item ${id}`;

		confirm
			.show()
			.then(() => {
				if (confirm.isConfirmed) {
        }
      });
```

Hope I gave all the needed info, Please ask if you need more

Best regards,
Yannick

**Comment by ypcode** [comment]
I actually retested today after upgrading to SPFx v1.4.1,  It seems like it doesn't occur anymore !
Will keep an eye on it. I close the issue for now

**Comment by ypcode** [comment]
Hello again,

I will reopen this one since, the issue is still occuring on the hosted workbench of another tenant while it doesn't in my original tenant.
I can give the tenants' names in private messages if needed.

Best regards,
Yannick

**Comment by VesaJuvonen** [comment]
Partial duplicate with #1381 in the context of local workbench.

**Comment by thisismoather** [comment]
I'm having the same issue. is there any workaround for this ?

**Comment by cprothero** [comment]
Using vanilla javascript and I can also only see it on my local workbench.

**Comment by dgaeta** [comment]
@thisismoather  @ypcode can you provide trace logs or errors that you see on the developer console?
To see the trace logs press "Ctrl and F12" then click the Trace tab.

**Comment by ypcode** [comment]
Hi @dgaeta , I just tried right now in the workbenches of my two tenants, and dialog shows up properly now... I cannot reproduce this problem anymore...
Will ping you and save the trace log if I face it again...

**Comment by dgaeta** [comment]
@ypcode Sounds good. We did find a problem in the Hosted workbench with the dialogs not appearing and checked in a fix that will start rolling out next week. 
If you encounter the problem again before next week I have found this work around to solve the problem, append this query string to the url 
`http://your-url?debugManifestsFile=https://resourceseng.blob.core.windows.net/files/refs_heads_master/manifests.js`

I'll go ahead and close this issue. Feel free to reopen if the problem returns.

**Comment by ypcode** [comment]
Hi @dgaeta , The problem reappeard just now.

still nothing in the regular console but seems to be something interesting in the Ctrl+F12 trace
Here is the trace CSV file
[spfx_trace_logs.zip](https://github.com/SharePoint/sp-dev-docs/files/1887536/spfx_trace_logs.zip)

Cheers,
Yannick
