### ISSUE TITLE
can we create SharePoint Framework Extensions for SharePoint Server 2016?

### ISSUE THREAD

**Issue by HelloPnP** [SharePoint/sp-dev-docs#1372]
I've created a SPFx webpart and need to add it on custom master page but I'm unable to do that so i googled and found that we cannot add SPFx webpart to custom master page but we can add SharePoint Framework extensions on the master page. here is the [link](https://sharepoint.stackexchange.com/questions/231786/how-to-add-spfx-client-side-webpart-to-masterpage/236225#236225)

I'm creating webparts for SharePoint Server 2016 or SharePoint On Premises and there is no option available to create extensions when i select baseline package "Using SharePoint 2016, including SharePoint Online". i can see the extensions when i create solution for SharePoint ONLINE.

Please anyone can confirm
**"can we create SharePoint Framework Extensions for SharePoint Server 2016?"**

**Comment by joelfmrodrigues** [comment]
No, that's not possible.
SharePoint Framework extensions only work with modern pages, which are not available for on-prem.
For on-prem scenarios, you still have to use previous development models/approach

**Comment by HelloPnP** [comment]
Thanks for your reply

I've created Master Page using previous development approach i.e visual studio / Design Manager
i need to add SPFx webpart on master page how can i do?

**Comment by joelfmrodrigues** [comment]
Using a custom master page does not respect best practices for SharePoint
customisation. If you are starting your project, I would personally
recommend that you try to find alternative approaches.
If you are for example trying to run custom code on every page, an option
to achieve that can be to use a CustomAction element for ScriptLink that
refers your JavaScript file.
An extremely simple way to add the custom action is to use Google chrome
extension SP Editor. Or for a more managed way, use the apply template from
PnP and declare the custom action on your template.
Hope this helps

**Comment by VesaJuvonen** [comment]
As noted by Joel, we do not support SPFx extensions within SP2016 for now. You can use custom SPFx web parts on classic experiences with SP2016 FP2. SP2019 support will be announced later. Closing this for now, as the question has been addressed.

**Comment by peterremote1980** [comment]
will SharePoint 2019 supports it? thanks

**Comment by VesaJuvonen** [comment]
SharePoint 2019 will support modern SPFx experiences, like announced last week in Build. Other SharePoint related on news from build and roadmap updates are available from following resources - https://channel9.msdn.com/Events/Build/2018/BRK2409 (recording) and https://dev.office.com/blogs/live-from-build-updates-for-sharepoint-framework-coming-soon (blog post).
