### ISSUE TITLE
Graph Web Parts don't work unless pop-ups are not blocked

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#1374]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

When using a Graph consuming SharePoint web part, users have to unblock pop-ups for the authentication window to open and for the web part to work.
<img src="https://pbs.twimg.com/media/DWY3PI-W4AAYZMD.jpg:large" />
This isn't great for end users. Outside of SharePoint, I noticed that OneNote has stopped opening new windows for some O365 authentication so I wondered if this could be implemented for SPFx GA release?

**Comment by VesaJuvonen** [comment]
Thanks for your input. Right now this is by design, but we are potentially looking to replace it, if possible. Challenge is more about the adal.js support for doing this, but an investigation is on-going. We do understand the end-user impact of this and that it's not optimal.
