### ISSUE TITLE
Readonly Properties - Type is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<T>

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/sp-dev-docs#1376]
#### Category
- [X] Question
- [] Typo
- [] Bug
- [] Additional article idea

#### Expected or Desired Behavior
Following the article sp-dev-docs/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md  with the latest SPFx version updates (including TypeScript), I got an error that
`src\extensions\approvalFlow\PeoplePickerDialog.tsx(203,12): error TS2322: Type '{ message: string; spHttpClient: SPHttpClient; siteUrl: string; principalTypeUser: boolean; princ...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<PeoplePickerDialog> & Readonly<{ children?: ReactN...`

I have tried to build a custom people picker dialog for command set using the Fabric UI NormalPeoplePicker component.

#### Observed Behavior
The solution does not compile.

#### Steps to Reproduce

I have re-used the model from and the search method (_searchPeople):
https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-peoplepicker/src/webparts/officeUiFabricPeoplePicker/models/OfficeUiFabricPeoplePicker.ts

Use the following code for PeoplePickerDialog.tsx

`import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { BaseDialog, IDialogConfiguration } from '@microsoft/sp-dialog';
import {
    autobind,
    PrimaryButton,
    Button,
    DialogFooter,
    DialogContent
} from 'office-ui-fabric-react';
import { IPersonaProps } from 'office-ui-fabric-react/lib/Persona';
import {
    IBasePickerSuggestionsProps,
    NormalPeoplePicker
} from 'office-ui-fabric-react/lib/Pickers';
import {
    SPHttpClient,
    SPHttpClientBatch,
    SPHttpClientResponse
} from '@microsoft/sp-http';
import {
    Environment,
    EnvironmentType
} from '@microsoft/sp-core-library';
import { Promise } from 'es6-promise';
import * as lodash from 'lodash';
import {
    IClientPeoplePickerSearchUser,
    IEnsurableSharePointUser,
    IEnsureUser,
    IOfficeUiFabricPeoplePickerState,
    SharePointUserPersona
} from '../../models/OfficeUiFabricPeoplePicker';

const suggestionProps: IBasePickerSuggestionsProps = {
    suggestionsHeaderText: 'Suggested People',
    noResultsFoundText: 'No results found',
    loadingText: 'Loading'
};

interface PeoplePickerProps {
    message: string;
    spHttpClient: SPHttpClient;
    siteUrl: string;
    typePicker: string;
    principalTypeUser: boolean;
    principalTypeSharePointGroup: boolean;
    principalTypeSecurityGroup: boolean;
    principalTypeDistributionList: boolean;
    numberOfItems: number;
    onChange?: (items: SharePointUserPersona[]) => void;
    close: () => void;
    submit: (person: string) => void;
}

class PeoplePickerDialog extends React.Component<PeoplePickerProps, {}> {
    private _peopleList;
    private _selectedPeople;

    constructor(props) {
        super(props);

        this._peopleList = [];
        this._selectedPeople = props.selectedItems || [];
    }

    public render(): JSX.Element {
        return <DialogContent
            title='People Picker'
            subText={this.props.message}
            onDismiss={this.props.close}
            showCloseButton={true}
        >
            <NormalPeoplePicker
                onChange={this._onChange}
                onResolveSuggestions={this._onFilterChanged}
                getTextFromItem={(persona: IPersonaProps) => persona.primaryText}
                pickerSuggestionsProps={suggestionProps}
                className={'ms-PeoplePicker'}
                key={'normal'}
            />
            <DialogFooter>
                <Button text='Cancel' title='Cancel' onClick={this.props.close} />
                <PrimaryButton text='OK' title='OK' onClick={() => { this.props.submit(this._selectedPeople); }} />
            </DialogFooter>
        </DialogContent>;
    }

    @autobind
    private _onChange(items: any[]) {
        this.setState({
            selectedItems: items
        });
        if (this.props.onChange) {
            this.props.onChange(items);
        }
    }

    @autobind
    private _onFilterChanged(filterText: string, currentPersonas: IPersonaProps[], limitResults?: number) {
        if (filterText) {
            if (filterText.length > 2) {
                return this._searchPeople(filterText, this._peopleList);
            }
        } else {
            return [];
        }
    }

    /**
   * @function
   * Returns people results after a REST API call
   */
    private _searchPeople(terms: string, results: IPersonaProps[]): IPersonaProps[] | Promise<IPersonaProps[]> {

        if (DEBUG && Environment.type === EnvironmentType.Local) {
            // If the running environment is local, load the data from the mock
            //return this.searchPeopleFromMock();
        } else {
            const userRequestUrl: string = `${this.props.siteUrl}/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`;
            let principalType: number = 0;
            if (this.props.principalTypeUser === true) {
                principalType += 1;
            }
            if (this.props.principalTypeSharePointGroup === true) {
                principalType += 8;
            }
            if (this.props.principalTypeSecurityGroup === true) {
                principalType += 4;
            }
            if (this.props.principalTypeDistributionList === true) {
                principalType += 2;
            }
            const userQueryParams = {
                'queryParams': {
                    'AllowEmailAddresses': true,
                    'AllowMultipleEntities': false,
                    'AllUrlZones': false,
                    'MaximumEntitySuggestions': this.props.numberOfItems,
                    'PrincipalSource': 15,
                    // PrincipalType controls the type of entities that are returned in the results.
                    // Choices are All - 15, Distribution List - 2 , Security Groups - 4, SharePoint Groups - 8, User - 1.
                    // These values can be combined (example: 13 is security + SP groups + users)
                    'PrincipalType': principalType,
                    'QueryString': terms
                }
            };

            return new Promise<SharePointUserPersona[]>((resolve, reject) =>
                this.props.spHttpClient.post(userRequestUrl,
                    SPHttpClient.configurations.v1, { body: JSON.stringify(userQueryParams) })
                    .then((response: SPHttpClientResponse) => {
                        return response.json();
                    })
                    .then((response: { value: string }) => {
                        let userQueryResults: IClientPeoplePickerSearchUser[] = JSON.parse(response.value);
                        let persons = userQueryResults.map(p => new SharePointUserPersona(p as IEnsurableSharePointUser));
                        return persons;
                    })
                    .then((persons) => {
                        const batch = this.props.spHttpClient.beginBatch();
                        const ensureUserUrl = `${this.props.siteUrl}/_api/web/ensureUser`;
                        const batchPromises: Promise<IEnsureUser>[] = persons.map(p => {
                            var userQuery = JSON.stringify({ logonName: p.User.Key });
                            return batch.post(ensureUserUrl, SPHttpClientBatch.configurations.v1, {
                                body: userQuery
                            })
                                .then((response: SPHttpClientResponse) => response.json())
                                .then((json: IEnsureUser) => json);
                        });

                        var users = batch.execute().then(() => Promise.all(batchPromises).then(values => {
                            values.forEach(v => {
                                let userPersona = lodash.find(persons, o => o.User.Key == v.LoginName);
                                if (userPersona && userPersona.User) {
                                    let user = userPersona.User;
                                    lodash.assign(user, v);
                                    userPersona.User = user;
                                }
                            });

                            resolve(persons);
                        }));
                    }, (error: any): void => {
                        reject(this._peopleList = []);
                    }));
        }
    }
}

export default class PeoplePickerDialogContent extends BaseDialog {
    public message: string;
    public personCode: string;
    public spHttpClient: SPHttpClient;
    public siteUrl: string;
    public principalTypeUser: boolean;
    public principalTypeSharePointGroup: boolean;
    public principalTypeSecurityGroup: boolean;
    public principalTypeDistributionList: boolean;
    public numberOfItems: number;

    public render(): void {
        ReactDOM.render(<PeoplePickerDialog
            message={this.message}
            spHttpClient={this.spHttpClient}
            siteUrl={this.siteUrl}
            principalTypeUser={this.principalTypeUser}
            principalTypeSharePointGroup={this.principalTypeSharePointGroup}
            principalTypeSecurityGroup={this.principalTypeSecurityGroup}
            principalTypeDistributionList={this.principalTypeDistributionList}
            numberOfItems={this.numberOfItems}
        />, this.domElement);
    }

    public getConfig(): IDialogConfiguration {
        return {
            isBlocking: false
        };
    }

    @autobind
    private _submit(person: string): void {
        this.personCode = person;
        this.close();
    }

    @autobind
    private _close(): void {
        this.close();
    }
}`

**Comment by VesaJuvonen** [comment]
@mpasarin - can you have a look on this if it can be solved easily.

**Comment by mpasarin** [comment]
In order to get rid of the compile error I only made the properties that are not being passed as optional (appending `?` to its name).
In this case it was `typePicker`, `close`, and `submit`.
This issue is not about SPFx but TypeScript being picky about the props object not matching the interface.

After that the compile step for that file succeeded. I didn't do an end-to-end testing but I assume the rest of the code will just work after this.

I'm going to close the issue, if this doesn't solve your problem feel free to re-open.
