### ISSUE TITLE
Issue upgrading to SPFx 1.4.x

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/sp-dev-docs#1377]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
Upgrading from SPFx 1.3.x to version 1.4.x you will get the following compilation errors:

Error - typescript - node_modules/@microsoft/sp-lodash-subset/node_modules/@types/lodash/index.d.ts(19507,14): error TS2428: All declarations of 'WeakMap' must have identical type parameters.

Error - typescript - node_modules/@types/es6-collections/index.d.ts(76,10): error TS2428: All declarations of 'WeakMap' must have identical type parameters.

However, if you update the tsconfig.json file with the parameter:

"skipLibCheck": true

The compilation works properly. Thus, I'm wondering if there are any regression issues in version 1.4.x.

#### Steps to Reproduce
1) Create a SPFx solution with SPFx 1.3.0
2) Update to 1.4.1
3) Execute gulp build
4) You will see the errors above
5) Add the skipLibCheck parameter to tsconfig.json
6) Build again: it works

**Comment by wobba** [comment]
As there are no official upgrade paths from one version to another with SPFx we're on our own here :)

I've seen different config files change, and you have to diff with a fresh project to know what to change in order for something to build properly. Having an auto-upgrade to fix all config changes would be awesome.

**Comment by SPParseError** [comment]
Had the error too, solved it when I created a fresh new project and copied the new tsconfig. Would be cool to have a list of config changes to manually replicate when we upgrade the project

**Comment by VesaJuvonen** [comment]
As we nowadays have upgrade tooling as CLI for Microsoft 365, that is the one which should be used for these. Closing this one as it seems outdated. If issue is still relevant, please open an new issue.
