### ISSUE TITLE
Local Workbench SSL issue with node 9.0.0

### ISSUE THREAD

**Issue by erniebryant** [SharePoint/sp-dev-docs#1379]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After installing the SharePoint Framework dependencies, generating a Hello-World project with the react template, trusting the dev cert, and running gulp serve, the workbench should display at:

https://localhost:4321/temp/workbench.html

#### Observed Behavior

After installing the SharePoint Framework dependencies, generating a Hello-World project with the react template, trusting the dev cert, and running gulp serve, the workbench displays an SSL error.  The error returned in Chrome is "ERR_SSL_PROTOCOL_ERROR".  In Edge, I receive the message "Can't connect securely to this page.  This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website's owner."  

After seeing #1002, I then tried running "set NODE_NO_HTTP2=1" &  "gulp serve", but observed the same SSL error.  I verified that the env variable was set using the command "set NODE_NO_HTTP2", which produced a result of "NODE_NO_HTTP2=1".

#### Steps to Reproduce

**Environment:**
- Windows 10
- Node 9.0.0

After all dependencies have been installed (yo, gulp, ms yo generator, etc.),  run:

1. `yo @microsoft/sharepoint`  (select default values with the exception of selecting react as the framework.)
2. `gulp trust-dev-cert` (select yes when prompted to trust the cert)
3. `set NODE_NO_HTTP2=1`
4. `gulp serve`

**Comment by andrewconnell** [comment]
SPFx isn't supported on Node.js v9... only LTS ATM (v8). I've seen in a few places where that env variable has issues in some Node,js v9 versions.

**Comment by erniebryant** [comment]
Any ETA on when it will be supported?  For now, I'll give NVM a shot and roll back to v8.

**Comment by andrewconnell** [comment]
No... considering MSFT has always said they only support LTS, my assumption is that they'll just make sure it works with the next LTS version of Node.js: v10.* (which comes out in April but won't go into LTS until October 2018).
