### ISSUE TITLE
Invalid title set in the Web Part manifest

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#138]
The generator-sharepoint sets invalid title in the Web Part's manifest.
## Repro steps:

_? What is your webpart name?_ **To do list**

Expected in the manifest:

```
"title": { "default": "To do list" },
```

Actual:

```
"title": { "default": "ToDoList" },
```

**Comment by nickpape-msft** [comment]
This has been fixed in the generator, as well as the description field. You will see it in Drop 3.

I'll close this issue when we do Drop 3.

**Comment by manishgarg1** [comment]
VSO #244604

**Comment by patmill** [comment]
Closing old bugs

**Comment by patmill** [comment]
(it has been fixed)
