### ISSUE TITLE
Dialog.alert() not working with SPFx v1.4.1

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#1381]
#### Category
- [x] Bug

#### Expected or Desired Behavior
When using `Dialog.alert("foo")` I expect an alert to show on the page.

#### Observed Behavior
When adding `Dialog.alert("foo");` in a web part or extension nothing shows when hosted in SharePoint. When testing on the localhost workbench the dialog shows.

#### Steps to Reproduce
Create a new web part or extension and add `Dialog.alert("foo")`, and nothing will show.

**Comment by wobba** [comment]
Want to add that it works for my extension once it's deployed - just not in testing or on the workbench.

**Comment by VesaJuvonen** [comment]
Duplicate with #1371

**Comment by dgaeta** [comment]
@wobba 
- Do you see any errors in the console?
- Do you see any errors in the Trace Logs (press control F-12) to open the Trace logs.

**Comment by wobba** [comment]
@dgaeta No errors in the console and cannot really see anything weird in the trace either when doing verbose logging. I added the code below to make sure it was all listed at the end:

```
window.setTimeout( () =>{
      console.log('a');
      Dialog.alert('asdasd');
   }, 10000);
```

**Comment by dgaeta** [comment]
Hi @wobba, currently you can't use the local Workbench to test SharePoint Framework Extensions. You'll need to test and develop them directly against a live SharePoint Online site. You don't have to deploy your customization to the app catalog to do this, which makes the debugging experience simple and efficient. - This is from [the Extensions docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api).

Was your problem just with an extension or are you still not able to see the Dialog.alert() from a webpart deployed to Sharepoint?

**Comment by wobba** [comment]
@dgaeta I know how to test extensions :) And no dialog when debugging it. When testing localhost I did a web part, not extension. It’s very easy to reproduce. Create a new part, test in: local wb, sp wp, deploy - and see where it work/does not work.

**Comment by dgaeta** [comment]
@wobba It's working for me on local wb and sp wp deployed (screen shot below). 
Is your web part being hosted by Office 365 CDN or localhost? If it's localhost can you double check you have `gulp serve --nobrowser` running while you open it on a sharepoint page?

![dialog deployed](https://user-images.githubusercontent.com/1770329/37996082-528bf392-31cb-11e8-9b22-a99bbefc2448.png)

**Comment by wobba** [comment]
Re-tested.. and seems it's only in the SharePoint workbench where it's not working. Works in local wb and deployed.

Personally the SP workbench is where I dev/test the most, as I need data and context when developing. Deploying in order to test comes pretty late in the chain.

At least the severity of this one is not that big.

**Comment by dgaeta** [comment]
@wobba, thanks for the feedback. I'm working on the SP workbench bug and have a work around but I am working on the root problem... will post an update when I have one.

**Comment by dgaeta** [comment]
@wobba We have fixed the issue in the hosted workbench and checked in the code change to fix it, it will be in the next release (this should start rolling out next week). 

Until then you can work around the issue on the hosted workbench by appending this query param to your url
http://your-tenant-url-workbench?debugManifestsFile=https://resourceseng.blob.core.windows.net/files/refs_heads_master/manifests.js

I'll go ahead and close this issue. Feel free to reopen if you see the issue again.
