### ISSUE TITLE
Error in console with MS Graph client API

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#1383]
I am following the [Tutorial: Consuming APIs secured with Azure Active Directory within SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#DeploymentAndPermissionsGrant) to create a web part as same as in demo. I am able to create solution, build, package, upload solution to app catalog. Finally i have approved under tenant admin center for Graph API. 
I have added this web part to a page and I have selected MSGraphClient, which is giving below error in console.
```
SCRIPT5022: This instance of the MSGraphClient has not been initialized.
sp-webpart-workbench-assembly_en-us_f0d2645f371530ad8eac3fe9f26f854a.js (11148,24)
```

If I select AadHttpClient then popup is opening for authentication, but it is never closing. I am using edge browser to do this.

#### Category

- [x] Question
- [x] Bug

Edit: If i try in chrome browser AadClient is working fine. But MSGraphClient is still having same issue. In edge it is not returning the access token seems.

**Comment by dharmenb** [comment]
I am seeing the same issue, it works in Chrome but not in IE or Edge.

**Comment by kimrohdin** [comment]
Yes, also experience problems in IE/Edge when using the MSGraphClient

**Comment by ypcode** [comment]
Hi, 

I experience exactly the same issue as @bpringe  in Chrome.
It was working fine one week ago.

Regards
Yannick

**Comment by bpringe** [comment]
This may be an issue with the workbench. A coworker informed me it works when deployed to a site and the web part is added to a page on the site.

**Comment by bpringe** [comment]
Here are steps to reproduce this issue:

1) Create a new spfx webpart project with the yeoman generator
2) Follow steps 1 and 2 of this tutorial to add the MSGraphClient to your project and get an instance of it in the render method
3) Run `gulp serve --nobrowser`
4) Open the SharePoint workbench at https://<your SP site>/_layouts/15/workbench.aspx and add your webpart to the page
5) Open Developer Tools and view the error(s) in the console

**Comment by HJK6** [comment]
You need to deploy your app to sharepoint in order to test the MSGraphClient Queries.

**Comment by bpringe** [comment]
@HJK6 Yes, this works, but the queries should be working in the hosted workbench for development.

**Comment by andrewconnell** [comment]
Lot of stuff has changed with the AAD & MSGraph support since the last activity on this issue... specifically: it's GA and the API changed :). Appears these issues are either resolved / not applicable as the API changed... if not, please feel free to re-open the issue or submit a new one.
