### ISSUE TITLE
Bundled Office UI Fabric React version has major dropdown bug (IE11, Safari) that is resolved by recent Office UI Fabric React version.

### ISSUE THREAD

**Issue by jacobhummel** [SharePoint/sp-dev-docs#1385]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The current version of Office UI Fabric that's included in SPFx has a bug with Dropdown that prevents it from scrolling correctly in IE/Safari. [This is addressed/fixed in this office-ui-fabric-react issue.](https://github.com/OfficeDev/office-ui-fabric-react/issues/3405).

I have worked around this for now by installing the latest version of [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react) in my SharePoint Framework project. This solved my issue. However, I know this is [not recommended](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components#add-an-office-ui-fabric-component), so I would love to see the latest version of office-ui-fabric-react included with SharePoint Framework.

#### Observed Behavior
[The behavior shown in this issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/3405) is seen when using the SPFx bundled version of UI Fabric React.

#### Steps to Reproduce
1. Build a SharePoint Framework solution
2. Import Dropdown from office-ui-fabric-react with enough items to cause scrolling
3. Serve to local workbench and open in IE11 or Safari

**Comment by russgove** [comment]
hmmm. I've been updating the react fabric version in ALL my projects. I thought that was the recommended practice at some point. 
There are controls in newer versions of react fabric that we desperately need.

**Comment by mcmynn83** [comment]
Unfortunately you have to use the current version of Office UI Fabric React that is with the current version of SPFX.  It will be update with the next release of SPFX which at this time it is unknown.

**Comment by saulpreciado** [comment]
What release should we get to get this fix?

**Comment by gjerm** [comment]
For reference (we experienced this issue with a Sharepoint 2019 on-premise project): The 5.32.0 update of office-ui-fabric-react fixes this issue. Added this to dependencies in package.json:

`"office-ui-fabric-react": "5.32.0"`

And ran `npm i`. 

@saulpreciado Doubt that this is still relevant for you, but here you go.
