### ISSUE TITLE
Web API Permission Requests are shown twice in API Management

### ISSUE THREAD

**Issue by rbarten** [SharePoint/sp-dev-docs#1389]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When a SPFx solution is installed the Web API Permission Request should be showed once in the API management.

#### Observed Behavior
When I install a SPFx solution with 'webApiPermissionRequests', the API Management shows the same request twice in Pending Approval.
![2018-02-22 10_41_22-sharepoint admin center preview](https://user-images.githubusercontent.com/2169036/36531281-a8d0b4c2-17bd-11e8-9820-a656ea843976.png)

#### Steps to Reproduce
Install a SPFx solution with one webApiPermissionRequest. 
```
"webApiPermissionRequests": [
     {
        "resource": "**********.SPFx.API",
        "scope": "user_impersonation"
      }
    ],
```

Tried several different solutions, all have the same issue in our tenant.

**Comment by waldekmastykarz** [comment]
What are the exact steps that you're following? Every time you deploy the solution in the app catalog, a new permission request will be added to the list. Could it be, that you deployed your solution multiple times?

**Comment by rbarten** [comment]
I'm able to reproduce it by dragging and dropping a solution in the App Catalog and overwritting an existing solution. Next I check-in the file. 
After drag/dropping the package, it's checked out in the library and only one approval request is added. When I check-in the file, the second Approval Request is created for the same solution.

**Comment by waldekmastykarz** [comment]
Right, so the solution has been previously deployed and you're updating it, which triggers re-issuing the permission requests from the solution.

**Comment by patmill** [comment]
The UX here has a few issues.  Here's a (not complete) list of what we are addressing around here.  Errors will be reported in the UX (not as a red line saying 400 error), duplicates won't show up, and each permission for the same service scope will appear separately (so 4 permissions against graph will show up as 4 lines).

**Comment by tejyapranthi** [comment]
Web API Permission Request is not shown in my API Management

**Comment by waldekmastykarz** [comment]
Was the solution deployed without any errors?

**Comment by patmill** [comment]
The other thing to check is if it was deployed less than 20 minutes after you created the app catalog. If it was, redeploy and they will appear.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tejyapranthi** [comment]
no ,there were no errors when solution deployed.

**Comment by lworkman** [comment]
> 
> 
> Right, so the solution has been previously deployed and you're updating it, which triggers re-issuing the permission requests from the solution.

Is there any plan to address this? Or is there an alternate way to update a solution? Having to tell a user to delete requests anytime they update our app isn't an ideal solution.

**Comment by patmill** [comment]
Hey @lworkman - is your question "will the admin page stop showing requests for scopes that have already been granted"?  If so, the answer to that is yes.  It's a bug, and we will get it cleaned up.

**Comment by lworkman** [comment]
Thanks for the info @patmill - is there an github issue somewhere I can subscribe to?

**Comment by patmill** [comment]
Not that I am aware of.  I know we have our own "clean up the admin UX" work item on our backlog.

**Comment by NickSevens** [comment]
@patmill any progress on this?
During development this means getting **LOTS** of requests in the admin panel.
Also, it seems there is a limit of 100 items that are being shown in the list.

**Comment by dev-a11y** [comment]
'Also, it seems there is a limit of 100 items that are being shown in the list.' - indeed there is a limit in /PermissionRequests endpoint and those /Deny calls seem to be a workaround here (kind of server side cleanup driven by client side script) - each call 'abandons' single past deployment; so basically - (1) if you deploy new version of SPFx packages quite often and (2) you don't access 'API access' page in SP admin on daily basis (i.e. during morning cup of coffee) THEN you notice how messy (and funny) this design is;

what I can advice is to add an extension to your browser (there are many e.g. in Chrome Web Store) that reloads the page after specified delay - in this case 15 seconds was enough for us (you need to refresh page and wait few seconds for those 100 calls to complete - they are pretty quick though) - and leave it for some time (minutes/hours - depending i.e. on how early you realized about this design flaw) - after this you should be able to approve new permission requests (however I'm not sure how it looks if there are more than 100 permissions being used on single tenant in total - thankfully we have not reached this point on our environment so far);

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
