### ISSUE TITLE
Access denied for permission Group.ReadWrite.All for Graph API

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#1390]
I am working on SPFx web part of based on [Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial). I am able to follow the tutorial and make it possible the given solution. But now I want to add some toppings to it like I want to get all the groups that I am belongs to. I have given permission in package-solution.json file as `Group.ReadWrite.All`
```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.ReadWrite.All"
      }
    ]
```

While access the groups information with query 
```
graphClient
      .api("me/memberOf")
      .version("v1.0")
```
it is giving me error as below in console. 
```
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "e000630c-f19b-48b4-a29b-1871279a113e",
      "date": "2018-02-22T12:47:54"
    }
  }
}
```
I have uploaded app to app catalog and given permission to this request under API management in sharepoint tenant admin.
![image](https://user-images.githubusercontent.com/7568187/36539943-7901f026-17fe-11e8-89fc-ff4da10a16e5.png)
So what could be the issue here?

**Comment by vman** [comment]
Hi @ymihir , as per the [docs of memberOf](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_memberof), you need `Directory.ReadWrite.All` permissions and not `Group.ReadWrite.All`

**Comment by ymihir** [comment]
Yeah you are right. But I am trying as `/me/memberOf`. As per the docs `/users/{id | userPrincipalName}/memberOf`. Both are same?

**Comment by ymihir** [comment]
Thanks @vman , I have tested with Directory.ReadWrite.All permissions. It is working fine. 
But it is not showing whether I have marked group as favorite or not. Do you know how to retrieve favorite groups of current user?

**Comment by VesaJuvonen** [comment]
since @ymihir root issue is solved - the wrong scope, so closing this issue to avoid it to hang open in the engineering task list. Thanks, @vman for assisting with the question. Appreciated.
