### ISSUE TITLE
spHttpClient Batch not working in a dialog

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/sp-dev-docs#1394]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expecting executing Batch request in a dialog to work as expected. Instead its referrer URL has an undefined in the URL.

#### Observed Behavior
When executing a spHttpClient.batch from a context of a SPFx dialog, it creates a POST request with a wrong uri referrer.

#### Steps to Reproduce
Create a custom dialog SPFx command which processes a batch request. Pass to the custom dialog spHttpClient and current site absolute URL as properties.

On executing   batch.execute(), then observing the network tab, it generates a batch to the https://tenant.sharepoint.com/sites/sitecollection/Documents/Forms/undefined/_api/$batch request URL.

We have tried creating the batch with and without ISPHttpClientBatchCreationOptions.

Example stripped code:
`const userRequestUrl: string = "${this.props.siteUrl}/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser";
            let principalType: number = 1; // users only
            
            const userQueryParams = {
                'queryParams': {
                    'AllowEmailAddresses': true,
                    'AllowMultipleEntities': false,
                    'AllUrlZones': false,
                    'MaximumEntitySuggestions': this.props.numberOfItems,
                    'PrincipalSource': 15,
                    'PrincipalType': principalType,
                    'QueryString': terms
                }
            };
            return new Promise<SharePointUserPersona[]>((resolve, reject) =>
                this.props.spHttpClient.post(userRequestUrl,
                    SPHttpClient.configurations.v1, { body: JSON.stringify(userQueryParams) })
                    .then((response: SPHttpClientResponse) => {
                        return response.json();
                    })
                    .then((response: { value: string }) => {
                        let userQueryResults: IClientPeoplePickerSearchUser[] = JSON.parse(response.value);
                        let persons = userQueryResults.map(p => new SharePointUserPersona(p as IEnsurableSharePointUser));
                        return persons;
                    })
                    .then((persons) => {
                        const spBatchCreationOpts: ISPHttpClientBatchCreationOptions = { webUrl: this.props.siteUrl };
                        const batch = this.props.spHttpClient.beginBatch(spBatchCreationOpts);
                        const ensureUserUrl = `${this.props.siteUrl}/_api/web/ensureUser`;
                        const batchPromises: Promise<IEnsureUser>[] = persons.map(p => {
                            var userQuery = JSON.stringify({ logonName: p.User.Key });
                            return batch.post(ensureUserUrl, SPHttpClientBatch.configurations.v1, {
                                body: userQuery
                            })
                                .then((response: SPHttpClientResponse) => response.json())
                                .then((json: IEnsureUser) => json);
                        });

                        var users = batch.execute().then(() => Promise.all(batchPromises).then(values => {
                            values.forEach(v => {
                                let userPersona = lodash.find(persons, o => o.User.Key == v.LoginName);
                                if (userPersona && userPersona.User) {
                                    let user = userPersona.User;
                                    lodash.assign(user, v);
                                    userPersona.User = user;
                                }
                            });

                            resolve(persons);
                        }));
                    }, (error: any): void => {
                        reject(this._peopleList = []);
                    }));`

**Comment by tarcisiopqdt** [comment]
I have similar issue here...
"Module '"@microsoft/sp-http"' has no exported member 'SPHttpClientBatch'.ts(2305)"

I'm using SPFX 1.11.0v,

Anyone resolved that?

**Comment by ultrawide** [comment]
Similar issue with SPFX 1.12.1

**Comment by patmill** [comment]
For the no exported member issue - the batch API is only supported in beta builds of the framework.  For the former, we are looking into it.

**Comment by AJIXuMuK** [comment]
Hello @Sartor87 - sorry for the really long delay.
The issue seems to be fixed by now.
I'm attaching my test sample (based on your code).

Could you please check if the bug is resolved on your end? Thanks!
[spfx-detailslist-dialog-test.zip](https://github.com/SharePoint/sp-dev-docs/files/7506489/spfx-detailslist-dialog-test.zip)
