### ISSUE TITLE
Possible to get folder path from listview command?

### ISSUE THREAD

**Issue by frnk01** [SharePoint/sp-dev-docs#1395]
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to get the path of the current folder from a listview command? I've looked through the documentation and can't find anything related to this.

This is useful in many scenarios and if this isn't implemented I hope you can add it to the backlog.

**Comment by mpasarin** [comment]
Thank you for your feedback @frnk01 
As of today, there is no API to get the current folder. We are looking into it to add a way to access the folder information.

**Comment by frnk01** [comment]
I solved it in the mean time by using the UrlQueryParameterCollection and then checking the ID parameter.

**Comment by ahackettms** [comment]
This is similar to issue #1254 , the solution we will provide will solve this problem as well. Please follow #1254 for progress, closing this one
