### ISSUE TITLE
Invocation of Add-In OAuth cannot be restricted on external client trust

### ISSUE THREAD

**Issue by wvstrien** [SharePoint/sp-dev-docs#1398]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Current there is no control nor monitoring on the usage of OAuth Add-In logon credentials. If the client id + secrets credentials are known outside (human is the weakest chain in security issues), they can now be misused to access the SPO site with the authorizations that are granted to the Add-In from whatever device and location. 
Same as for human access, it is desired to require a 'trust' between the external client using the OAuth logon credentials and the consumed O365 SPO site. Suggestions are via exchange of certificates, or whitelisting of allowed external client ip-address.

#### Steps to Reproduce
1. Via AppRegNew.aspx; register a placeholder for OAuth entrance
2. Develop a simple Plain-old HTML/JS App, that uses the client id + secret to authenticate against the tenant, and use the access token to retrieve data from SharePoint Online
3. Deploy this to any external system; and try / demonstrate that whatever system, as long as internet connection, the external client-app can retrieve the data. No governance control at all, to restrict usage of the OAuth client credentials to only trusted external client apps / locations

**Comment by VesaJuvonen** [comment]
hi @wvstrien, not quite sure on the question here. This is indeed how it works. App id and the secret is basically user id and pwd. If you share those with someone, they can use them. Are we missing some context on the question?

**Comment by wvstrien** [comment]
Hi Vesa,
I hear what you say, but same argument holds for human accounts logon via username + password. Yet we have experienced this is not secure enough to proof the one using the credentials is really the rightful owner. Therefore we augment with additional security layers: multi-factor authentication, conditional access. Still not 100% safe, but made a lot more difficult to misuse leaked or stolen credentials. Also the OAuth credentials can get comprised (“there are 2 types of companies, those that know they’re hacked, and those that don’t know yet”), and then there is now ZERO option to prevent misuse, plus it is not even traceable. Examples of leakage are a bad-leave, code of external client with credentials lost on a stick or in mail. All not unimagable.
Regards, William.

**Comment by andrewconnell** [comment]
Seems like this might be more of a feature request, and thus a candidate for a User Voice submission as it's by design... http://aka.ms/sp-dev-uservoice
