### ISSUE TITLE
Non-AMD dependencies seem not to be working correctly

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#14]
I'm trying to use a non-AMD jQuery plugin loaded from CDN and once in a while I'm seeing an error, which seems like the plugin is being loaded before jQuery.

I have the following setup:

config.json (standard external omitted for brevity):
```json
  "externals": {
    "jquery": {
      "path": "https://code.jquery.com/jquery-2.1.1.min.js",
      "globalName": "jQuery"
    },
    "simpleWeather": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js",
      "globalName": "jQuery",
      "globalDependencies": ["jquery"]
    }
  }
```

WebPart:
```ts
import * as $ from 'jquery';
require('simpleWeather');
```

Both scripts load correctly (200 OK status), but once in a while I'm seeing the following error:
```
Error: Unable to load web part script resources due to: Error: ReferenceError: jQuery is not defined at eval (https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js:2:3490) Evaluating https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js Error loading https://spoppe-a.akamaihd.net/files/simpleWeather. at http://lt-wama.local:4321/node_modules/@microsoft/sp-client-preview/dist/sp-client-preview.js:19233:32
```

The network graph shows both scripts are loaded simultaneously despite the dependencies. Using the `ModuleLoader` similar setup works as expected.

**Comment by patmill** [comment]
@nickpape-msft - can you take a look at this and see if it is a documentation issue (here's how you do this) vs a product issue (you can't do this)?

**Comment by nickpape-msft** [comment]
This issue has been addressed. We'll update the issue again once it is included in an update. Thanks!

**Comment by nickpape-msft** [comment]
[This has been fixed in Drop2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2)
