### ISSUE TITLE
Microsoft.SharePoint.Client.WebParts.WebPartDefinition.ZoneId is never loaded on SharePoint 2016

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#1402]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using PnP PowerShell (and I guess this would also apply to more ways of connecting to a site including C#, etc.) on SharePoint 2016, the ZoneId of webparts should be loaded so I can use it to understand the context of my page. This works fine Online.

#### Observed Behavior
When loading a WebPart using Get-PnPWebPart, the ZoneId is always empty, even if I explicitly ask to load the property, it says that the ZoneId property does not exist. Is that a bug from the underlying CSOM? I gues...

#### Steps to Reproduce
I did the following:
`Connect-PnPOnline -Url https://myfarm.int`
`Get-PnPWebPart -ServerRelativePageUrl /Pages/default.aspx | Select ZoneId`

And got the following:

![image](https://user-images.githubusercontent.com/7620955/36647445-d142db86-1a53-11e8-8e16-3c9cbaa7e54b.png)

Then tried the following:
`Connect-PnPOnline -Url https://myfarm.int`
`$webPart = Get-PnPWebPart -ServerRelativePageUrl /Pages/default.aspx`
`Get-PnPProperty -ClientObject $webPart -Property ZoneId`

And got the following:

![image](https://user-images.githubusercontent.com/7620955/36647446-ded2fccc-1a53-11e8-8455-1dad34cbaa73.png)

I am very confused and would expect that this works... What am I doing wrong?

**Comment by dgaeta** [comment]
@sebastienlevert Thanks for the feedback. You aren't doing anything wrong, and we have made the fix. I just submitted the code change to make ZoneId property assessible. It will be availible in the next release. 

If you experience the same issue in the next release feel free to re-open this bug.

**Comment by VesaJuvonen** [comment]
Thx @dgaeta for following up on this after getting the backporting fixed. We had a real issue in the SP2016 CSOM where this property was not actually supported, even though it's supported with SP2013 and SPO. Daniel has now fixed this in the source code last night and it will be shipped as part of the upcoming CUs for SP2016. ETA should be in May 2017 CU.

**Comment by VesaJuvonen** [comment]
@sebastienlevert - you can consider this as a birthday present. :-)

**Comment by sebastienlevert** [comment]
Thanks guys, I will take a birthday beer to celebrate that!

**Comment by VesaJuvonen** [comment]
Just checked the release notes for May 2018 PU for SP2016 and this is included, so can confirm from 99.99% percent certain that the update/fix is included in the May 2018 PU release. Finally. Thanks for reporting as this was a nasty miss.

**Comment by samculver** [comment]
I am now seeing this issue on SharePoint 2013, could this fix for SP 2016 have caused a regression issue with SP 2013? Here is new issue I have opened: https://github.com/SharePoint/PnP-PowerShell/issues/2339
