### ISSUE TITLE
PropertyPaneSlider step is not working as expected

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/sp-dev-docs#1404]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

In an SPFx web part I'm using a slider to define the item limit with the following configuration:

`PropertyPaneSlider("itemLimit", {
                  label: strings.ItemLimitLabel,
                  min: 1,
                  max: 11,
                  step: 2
                })`

#### Expected or Desired Behavior
When sliding, the minimum value should be 1. Then while sliding the value should go up to 3, 5, 7, 9 until the maximum value which is 11.

#### Observed Behavior
The inital value is 1, while sliding it becomes 2, 4, 6, .. etc. I'm also unable to to put the value back to 1. 2 is now the minimum value that is selectable.

#### Steps to Reproduce
Use the PropertyPaneSlider in the web part properties with the given configuration. I'm using version 1.4.0.

**Comment by patmill** [comment]
Sorry for the very long delay - we're working on cleaning up old bugs.  As of the lastest release, this control is working correctly.
