### ISSUE TITLE
Consuming MSGraphClient. Cannot read property 'PROD_OAUTH_TOKEN_URL' of undefined

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1406]
#### Category
Question
Bug

#### Expected or Desired Behavior
I added code from this documentation https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-msgraph.md

#### Observed Behavior
When it hit line 
`const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);`
i get this exception 

> sp-client-preview.js:128 Uncaught (in promise) TypeError: Cannot read property 'PROD_OAUTH_TOKEN_URL' of undefined
>     at MSGraphClient._configureGraphSDK (sp-client-preview.js:128)
>     at sp-client-preview.js:94
>     at e._processPendingCallbacks (sp-webpart-workbench-assembly_en-us_c62a811b76aa07bcefefad77b22b5dde.js:283)
>     at e.consume (sp-webpart-workbench-assembly_en-us_c62a811b76aa07bcefefad77b22b5dde.js:283)
>     at e.consume (sp-webpart-workbench-assembly_en-us_c62a811b76aa07bcefefad77b22b5dde.js:283)
>     at e.consume (sp-webpart-workbench-assembly_en-us_c62a811b76aa07bcefefad77b22b5dde.js:283)

#### Steps to Reproduce
Create a new web part project with SharePoint Framework 1.4.1 and add MSGraphClient by this acrticle https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-msgraph.md

**Comment by rob-windsor** [comment]
I've been having the same issue with the documentation mentioned above and with this tutorial https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

**Comment by wictorwilen** [comment]
Have you tried deploying the solution and not running it in the workbench. That worked for me.

**Comment by rob-windsor** [comment]
That solved the problem. Thanks Wictor.

**Comment by aslanovsergey** [comment]
Now it works somehow even with workbench running. Don't know what was the case

**Comment by VesaJuvonen** [comment]
There's an unfortunately known issue that Online workbench does not work regardless of the given permission s in the AAD application. We are working on getting this resolved. We'll also check if we can clarify that in the tutorial doc.

**Comment by wobba** [comment]
@VesaJuvonen any progress on this? Developing without the workbench to test Graph calls is quite the pain. And no rush, we're in preview :)

**Comment by dgaeta** [comment]
@aslanovsergey  Thanks for bringing this issue to light. This issue has been fixed and will be made available in the next release.
