### ISSUE TITLE
Custom Document Set Content Type created by spfx app has no welcome page

### ISSUE THREAD

**Issue by Jmsfox11** [SharePoint/sp-dev-docs#1410]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I am trying to provision a custom document set content type in a document library created by an spfx app.  I was able to successfully create a document library and the custom content type.  When I go to create a new item everything works as expected until I hit save.  With a typical doc set I would be redirected to the correct document set welcome page but in this case I receive a 404 not found error instead.  If I navigate to the list content type page in the list settings I am able to click on the document set settings page but clicking on the Customize the Welcome Page link also takes me to a 404 not found page.

So it seems to me that the document set welcome page is not being created for the custom content type.  Has this problem been encountered before and is there a solution?

Here is the definition for my content type from the elements.xml file. The first three columns are the default Title, Name, and Description fields, the remaining five are custom fields I created.
`<ContentType ID="0x0120D5200963FA69A646AA916D2E41284FC9D1" 
        Name="CustomDocSet" 
        Group="CustomContentTypes" 
        Description="This is the Custom Content Type">
    <FieldRefs>
        <FieldRef ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Hidden="TRUE" /> 
        <FieldRef ID="{8553196d-ec8d-4564-9861-3dbe931050c8}" /> 
        <FieldRef ID="{cbb92da4-fd46-4c7d-af6c-3128c2a5576e}" />
        <FieldRef ID="{11ED4026-1C15-4636-80EF-C27C41DB90E0}" /> 
        <FieldRef ID="{1DA0BA30-F87A-4D1B-9303-729AA02BEE25}" />
        <FieldRef ID="{145B5D00-E3AE-48EB-BB75-9699922AF8D8}" /> 
        <FieldRef ID="{197F8587-C417-458D-885E-4FBC28D1F612}" />
        <FieldRef ID="{10E72105-7577-4E9E-A758-BBBE8FF4E9BA}" />
    </FieldRefs>
</ContentType>`

**Comment by Jmsfox11** [comment]
I was able to mostly resolve this issue by Adding the property Inherit="TRUE" to the content type definition.    It looks like I am not able to add fields to the Welcome Page for the doc set when Inherit is set to true however, so if there is a way to customize that I would appreciate the feedback.

**Comment by patmill** [comment]
Hi @Jmsfox11 - does this page help by any chance?  http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2010/11/29/how-to-provision-a-document-set-using-caml.aspx

Looking for documentation on your problem specifically.

**Comment by Jmsfox11** [comment]
@patmill I actually did try that, but adding the XML Document sections didn't seem to do anything for me.

**Comment by patmill** [comment]
Sorry - this bug got lost due to incorrect metadata.  Did you get this working / get a work around?  Have you considered using the PNP Provisioning engine?

**Comment by Jmsfox11** [comment]
@patmill  this was a while ago but I don't think I got further than the partial work around with Inherit="TRUE" that I mentioned above.  This was primarily an exploratory project to see what the capabilities of SPFx were, so I don't think I pursued it that much further.

**Comment by patmill** [comment]
OK, thanks @Jmsfox11 .  I'll close this down for now.
