### ISSUE TITLE
Hide a default list/library button in modern UI

### ISSUE THREAD

**Issue by rbarten** [SharePoint/sp-dev-docs#1411]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Is it currently possible to hide a default list/library Command Bar Button in the modern UI using a CustomAction?
Or should I add this request to UserVoice?

#### Observed Behavior
For example, we would like to  hide the default 'Export to Excel' button.

![2018-02-21 13_31_21-app development - documents - test view](https://user-images.githubusercontent.com/2169036/36692206-c46691b6-1b37-11e8-8f33-c37cee7f3c49.png)

In the Classic view this could be done by a Custom Action:
```
<CustomAction
        Id="RemoveRibbonButtonLibrary"
        Location="CommandUI.Ribbon"
        RegistrationId="101" 
        RegistrationType="List">>
        <CommandUIExtension>
            <CommandUIDefinitions>
                <CommandUIDefinition Location="Ribbon.Library.Actions.ExportToSpreadsheet" />
            </CommandUIDefinitions>
        </CommandUIExtension>
</CustomAction>
```
But this doens't work for the Modern button. When we try location 'ClientSideExtension.ListViewCommandSet.CommandBar'. We get error: "The specified properties CommandUIExtension are not supported for client-side custom action". 

We also cannot found anything related to hiding a button in the documentation:
[Customizing "modern" lists and libraries](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-lists-and-libraries)

**Comment by VesaJuvonen** [comment]
This is not currently supported, so we would request to open up a UserVoice entry for the new capability. Thx.

**Comment by himanjanpati** [comment]
Hi @VesaJuvonen , do we have any workaround for the same. Can we go creating an app customizer or any alternate css may be, but not supported in modern UI, I believe. 
Any workaround is much appreciated.

Thanks,
Himanjan

**Comment by ashu57** [comment]
+1 , This is important requirement
