### ISSUE TITLE
Lots of deprecation console warnings in default SPO JavaScripts

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1413]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect the console log of a browser of a standard, non-customized site to be essentially empty. 

#### Observed Behavior

I see tons of JavaScript console warnings, causing a lot of noise and clutter in the console window.

For instance
```
sp-pages-assembly_en-us_d76a7acf040f70ef2d89eee6cb588000.js:326
t(t){var o=e.call(this,t)||this;return o._getSubTextId=function(){var e=o.props,t=e.ariaDescribedById,n=e.modalProps,r=e.dialogContentProps,i=e.subText,a=t||n&&n.subtitleAriaId;return a||(a=(i||r&&r.subText)&&o._defaultSubTextId),a},
o._getTitleTextId=function(){var e=o.props,t=e.ariaLabelledById,n=e.modalProps,r=e.dialogContentProps,i=e.title,a=t||n&&n.titleAriaId;return a||(a=(i||r&&r.title)&&o._defaultTitleTextId),a},o._id=i.getId("Dialog"),
o._defaultTitleTextId=o._id+"-title",o._defaultSubTextId=o._id+"-subText",o._warn
Deprecations property 'isOpen' was used but has been deprecated. Use 'hidden' instead.
```

#### Steps to Reproduce

Create an empty Modern Team Site and open the console window and watch the flood of warnings and logs.

**Comment by patmill** [comment]
Hi @wictorwilen, thanks for the feedback.  While this is more core product (although obviously impacts developer happiness) and outside the scope of this list, we are working on cleaning up this sort of thing.
