### ISSUE TITLE
login.microsoftonline.com does not permit framing

### ISSUE THREAD

**Issue by R-kothari** [SharePoint/sp-dev-docs#1414]
Accessing the API by leveraging SharePoint Online authentication cookie is not working as we need to load the page login.microsoftonline.com in an iframe but the headers from this site do not permit framing.

Got the following error while implementing :
Load denied by X-Frame-Options: https://login.microsoftonline.com/ does not permit framing.

**Comment by wictorwilen** [comment]
Isn't this deliberate from a security perspective, so you can't in a hidden iframe silently log in a user and do stuff?

**Comment by waldekmastykarz** [comment]
What are you trying to accomplish @R-kothari?

**Comment by R-kothari** [comment]
I want to consume a azure hosted WCF service which is secured by Azure Active directory using AJAX call from Sharepoint Online.

**Comment by waldekmastykarz** [comment]
Are you using ADAL JS with OAuth implicit flow for the auth flow?

**Comment by wictorwilen** [comment]
Have you looked into using  the AAD HTTP Client in SPFX 1.4.1?

**Comment by waldekmastykarz** [comment]
That's also a good suggestion! While it's still based on ADAL JS, it significantly simplifies connecting to any resource secured with Azure AD comparing to implementing ADAL JS yourself.

**Comment by R-kothari** [comment]
I faced this error while following this blog 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad
here it said we could use Sharepoint Online Authentication cookie by using an iframe to open the Login page.

Now i am implementing the ADAL JS with OAuth implicit flow but i get the following error:

AADSTS90009: Application is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier

**Comment by R-kothari** [comment]
@wictorwilen  Actually our application is already built and now changing it to SPFX will be difficult.

**Comment by R-kothari** [comment]
I faced this error while following this blog
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad
here it said we could use Sharepoint Online Authentication cookie by using an iframe to open the Login page. So i thought this was a better choice but i guess not.

Now I am using ADAL JS with OAuth implicit flow for consuming the Web Service

**Comment by waldekmastykarz** [comment]
@R-kothari ah, so you're not using SPFx after all. Have you followed the instructions in the article closely? There are quite a few details that must be in place or you will get errors, like the one you mentioned.

**Comment by R-kothari** [comment]
@waldekmastykarz  I followed all the instructions as per the article, but for implementing ADAL JS the article seems a bit unclear.

So i followed https://blogs.msdn.microsoft.com/laleh/2016/12/20/85/

 Can you suggest some other article or blog which i can follow to fulfill my requirements. Thanks.

**Comment by waldekmastykarz** [comment]
@R-kothari what part do you find unclear?

**Comment by qz2017** [comment]
Close the ticket due to lacking of response. @R-kothari , feel free to open it and provide more details.

**Comment by maxali** [comment]
I have the same issue here @waldekmastykarz 

I created Azure Function secured by Azure AD and an IFrame in my SPFx webpart pointing to the Function app.

This is what I did as _qoute from_ [this documentation page ](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md#access-the-api-by-leveraging-sharepoint-online-authentication-cookie) explains

> you place a hidden iframe on the page pointing to a URL where the API is hosted and which is also secured with Azure AD

As mentioned in the documentation

> After the browser tries to load this URL, it gets redirected to the Azure AD sign-in page because anonymous access is not allowed.

But fails to redirect with 
```
Refused to display 'https://login.microsoftonline.com/...' in a frame because it set 'X-Frame-Options' to 'deny'.
```
full error
```
Refused to display 'https://login.microsoftonline.com/{tenantid}/oauth2/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fproxyauthtest.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=6017efef-d4f3-4a4e-8f3f-5345ec09a98d&scope=openid+profile+email&response_mode=form_post&nonce=30a1db43d76348b6a7f6ca4c3f742d73_20180404144658&state=redir%3D%252F' in a frame because it set 'X-Frame-Options' to 'deny'.
```
Would you check this again

**Comment by waldekmastykarz** [comment]
In which browser are you experiencing this issue @maxali?

**Comment by maxali** [comment]
Google Chrome @waldekmastykarz

**Comment by vasanthtt** [comment]
@wictorwilen any solution for this issue?

> I have the same issue here @waldekmastykarz
> 
> I created Azure Function secured by Azure AD and an IFrame in my SPFx webpart pointing to the Function app.
> 
> This is what I did as _qoute from_ [this documentation page ](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md#access-the-api-by-leveraging-sharepoint-online-authentication-cookie) explains
> 
> > you place a hidden iframe on the page pointing to a URL where the API is hosted and which is also secured with Azure AD
> 
> As mentioned in the documentation
> 
> > After the browser tries to load this URL, it gets redirected to the Azure AD sign-in page because anonymous access is not allowed.
> 
> But fails to redirect with
> 
> ```
> Refused to display 'https://login.microsoftonline.com/...' in a frame because it set 'X-Frame-Options' to 'deny'.
> ```
> full error
> 
> ```
> Refused to display 'https://login.microsoftonline.com/{tenantid}/oauth2/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fproxyauthtest.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=6017efef-d4f3-4a4e-8f3f-5345ec09a98d&scope=openid+profile+email&response_mode=form_post&nonce=30a1db43d76348b6a7f6ca4c3f742d73_20180404144658&state=redir%3D%252F' in a frame because it set 'X-Frame-Options' to 'deny'.
> ```
> Would you check this again

**Comment by leidegre** [comment]
I think I know why this is happening.

When you use the iframe trick to refresh tokens you must send the request in such a way that it doesn't prompt the user for more information.

For example, if the authorize request (iframe `src` URL) has the `prompt=select_account` or if for example the `login_hint` (the username of the currently logged in user) is not actually signed in this will cause `https://login.microsoftonline.com` to display a sign in form.

If this happens for whatever reason, it will be served with the ` X-Frame-Options: deny` header which is an indication that the authorize request is being made with incorrect parameters.

Now, I only ran across this thread trying to solve my problem. But by fixing the things I listed above the `iframe` does load with the correct response.

I hope this is helpful to anyone else coming across this problem.

**Comment by mbuckman10** [comment]
@leidegre what were the exact steps you did to fix this?

**Comment by leidegre** [comment]
@mbuckman10 like I said, I'm not using SharePoint, instead I was integrating the AAD 2.0 auth stuff into a typical SPA.

What I learned is that you will run into this issue if the sign-in prompt asks for more information. This could probably happen if you have multiples users signed in and the sign-in request to login.microsoftonline.com is made without a login_hint. You can look for this in the DOM, look for an iframe pointer to `https://login.microsoftonline.com` open that URL in a new tab, see what you get.

I'm quite sure the root cause here is how the OAuth implicit grant flow is set up. And you have to look at the implementation details to figure this out. And I'm guessing those are in the ADAL client library in this case. But I cannot offer any more information because I don't know anything specifically about SharePoint specifically.

**Comment by kaburkett** [comment]
I also was working with a SPA using this method and with @leidegre 's tip I opened the login url and noticed Microsoft was trying to prompt me to select which of two accounts I intended to login with. I had to select one from the list and click 'logout and forget'. When I reloaded the page after this, the login worked without any errors. This error seems to be exactly what @leidegre says, Microsoft is prompting for more information in one way or another from the user. Really unfriendly.

**Comment by nigel-dewar** [comment]
So I read all this but what is actually the fix?

**Comment by kaburkett** [comment]
@nigel-dewar Since this is just the SharePoint documentation repository there are no 'bugs' only requests to extend documentation or clarity. It seems like the request was closed because no one provided instructions on how the documentation could be clearer. 

If you are receiving this same error, the best thing you can do is to ensure Microsoft isn't prompting for more information during the login process. **leidegre** provides several scenarios that I found helpful when I encountered this error.
