### ISSUE TITLE
Modern Search not working on Modern pages

### ISSUE THREAD

**Issue by rbarten** [SharePoint/sp-dev-docs#1418]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Modern Search is working on Modern pages.

#### Observed Behavior
Modern Search doesn't work on Modern pages. We are able to reproduce this on all new sites we currently create. 
- When we start typing, no result are resolved.
- When we press Enter or click on the arrow, nothing is happening
- When we add '_/layouts/15/search.aspx to the url', the page stays blank. 
On sites which were created earlier this way this is working, so looks like a recent update is causing this.
The SharePoint files loaded have the following date in the filename ‘_2018-02-16.004’
![2018-02-28 09_19_42-test](https://user-images.githubusercontent.com/2169036/36777185-d47f383c-1c68-11e8-973d-5f11a7c60e97.png)

#### Steps to Reproduce
1.	Create a  new Site Collection in SharePoint Admin with ‘Team site (classic experience)’
2.	Enable the ‘Site Pages’ feature (B6917CB1-93A0-4B97-A84D-7CF49975D4EC)
3.	Create a new Modern Page and save it
4.	Try the search, it’s not working
5.	Add _/layouts/15/search.aspx to the url, the page keeps blank.

**Comment by rbarten** [comment]
Strange thing is that it starts working after some time for the sites we currently create. I don't know yet if it's after some minutes of maybe hours. But immediately after creating the site it doesn't work.
So is there some process which adds this functionality to the site later?

Altough we still have some sites, which were created earlier, where the modern search still doesn't work.. Question is how to fix it on those sites..

**Comment by VesaJuvonen** [comment]
We do apologize for the delay, but as this is NOT a developer issue, we would ask to open this using the SharePoint Online support channels available for you from our tenant admin pages.
