### ISSUE TITLE
Integrated the update utility with generator-sharepoint

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#142]
#### Category

[x] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea

The [release notes for Drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2) refer to a utility that could be used to upgrade existing projects to the newer version of the tools. Could such utility be integrated with the generator-sharepoint? That way we wouldn't need a separate download and you could manage dependencies/changes in a single place 😄

**Comment by patmill** [comment]
Yes, although we also want a typical gulp serve to say "hey, there is an update available you should fetch", etc.

**Comment by StfBauer** [comment]
Well normally this is something that yeoman generator tells you as well, when you create a new project ;)
In this case no update couldn't be found.

**Comment by patmill** [comment]
Yes - both.  We're in a bit of a strange place.  The majority of projects get to pick when they update, as the dev is in control of the entire end-to-end system.  In our case, we will roll bits to prod on a weekly basis.  There might be times where that roll doesn't make a material difference to developers, but there will be times when it does.  We'd like to be able to notify a dev that there is a change that they should be aware of.  It is our mandate that once we reach an official release, everything will be backwards compatible (except for stuff in sp-client-preview).  Our feeling was that waiting for someone to create a new project would be too infrequent, and that we should show that there is an update in gulp.

**Comment by nickpape-msft** [comment]
Related to #145

**Comment by manishgarg1** [comment]
VSO #244635

**Comment by patmill** [comment]
This has been shelved at this point.  If it is still important, please open up a user-voice request ( https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/ )
