### ISSUE TITLE
"Error during serialization or deserialization using the JSON JavaScriptSerializer" on the properties pane of a documentset in the modern list view.

### ISSUE THREAD

**Issue by frankdevliegher** [SharePoint/sp-dev-docs#1421]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The modern list properties panel pane on a DocumentSet showing the actual values of each of the defined columns.

At least for reading, the number of records in the destination lookup list should be of no relevance when viewing a documentset or document having such a value selected in one of the metadata fields.

PS. When using the classic style, we don't see that behavior.

#### Observed Behavior
The properties pane shows an 'Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property'

Via F12 in Chrome:
The 'RenderListDataAsSteam’  request is the call who's returning that exception. If the panel is shown correctly, the response of that call a big JSON ( 1.8MB was still ok, so we assume 2MB is the limit), including all possible values of lookup columns, so if the list has 1000 items, you get 1000 values in this json, not the single value that was selected. Hence the more lookup columns you define, the more items there are in the list and the longer the values are, the sooner you end up crossing that maxJsonLength exception.

#### Steps to Reproduce
Create a List with a 4K+ items in it, which values of 15+ chars length.
Customize a DocumentSetContentType to contain two lookup sitecolumns, both pointing to this same list.
Create a New DocumentSet in a library and open the properties pane.
=> you see the exception.

**Comment by bcworld3000** [comment]
I am seeing this same issue on a list which so far does not have much data in it, but does have many lookup columns. As well as seeing that error in the details pane I also observe that the entire page does not load correctly and has essentially rendered the modern view useless. The top bar does not contain any menu items (it is just a black bar, no settings cog etc.) and things like the link behind item title, and any items on the item context menu just don't work...nothing happens on click. Switching back to classic view and everything works as expected.

**Comment by rubenestrada** [comment]
I am also experiencing the exact same issue.  After some troubleshooting I have found my issue.  I am only allowed to add 55 custom content types.  On the addition of the 56th custom content type I get the same error with the black bar at the top.  Different scenario but produces the same error. 
![json error](https://user-images.githubusercontent.com/40501982/41795071-279bd81e-7627-11e8-9f77-7224e0b2b38a.jpg)

**Comment by TomDegler** [comment]
I have same problem. Custom List, with 2 Custom Content Types (defined and inherited from site Content Types). List contains 8 Lookup Columns as Content Types columns, and additional lookups as hidden columns (set up by WorkFlow on update). List contains 700 items. 
It was ok, then on some point it started to display the same error message instead of presenting information pane - new experience.
I am still able to work with this list in old experience, but this renders use of new experience impossible.

**Comment by thomasnuijttens** [comment]
What is the status of this bug?

**Comment by bcworld3000** [comment]
> What is the status of this bug?

I can tell you that I posted above in Jun 2018...a ticket was raised with Microsoft way back then...but still, this issue persists and we are unable to use modern experience in the list in question.

**Comment by andrewbackway** [comment]
Bump.

I'm seeing this on list with zero lookup columns, a number of term fields which reference large stores, 6 content types, with 7 fields. 

Seeing the same error on trace when it calls RenderListDataAsStream "Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property." 

Odd thing is, it suddenly stopped working.

**Comment by andrewbackway** [comment]
Figured out a workaround using column formatting and the classic form in dialog mode.

- Add a new single line text field, EditForm
- Format the column with the following JSON

{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "txtContent": "Edit Properties",
  "attributes": {
    "target": "_blank",
    "href": "='https://<<yoursite>.sharepoint.com/<listurl>/Forms/EditForm.aspx?ID=' + [$ID] + '&IsDlg=1'"
  }
}

**Comment by sparkitect** [comment]
I can confirm that this is still an issue, but there's been no new comment since November of last year. Has there been any more work done on this by the SharePoint team?

This is happening on the default modern view of an **empty** document library which has been configured with a Content Type based on Document Set which includes four lookup columns.

The item counts of the lookup lists are  369, 2746, 3046, and 7808 (large).

The RenderListDataAsStream post, which fires when the list view page is loaded, it attempting to return **all** of the items from each of the lookup lists.

Even worse, it is doing so _at least twice_ in the structure of the ClientForms objects, as the (redacted) screenshot shows:
![image](https://user-images.githubusercontent.com/9206808/84454508-85f2f300-ac0f-11ea-961a-07ed29b93a28.png)

This seems a bit silly to me, but perhaps there's a good reason for it that isn't clear to me :)

**Comment by jasonwusc** [comment]
Experiencing the same problem. About to implement the workaround that andrewbackway provided above. Thanks for this andrewbackway!

> Figured out a workaround using column formatting and the classic form in dialog mode.
> 
> * Add a new single line text field, EditForm
> * Format the column with the following JSON
> 
> {
> "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
> "elmType": "a",
> "txtContent": "Edit Properties",
> "attributes": {
> "target": "_blank",
> "href": "='https://<.sharepoint.com//Forms/EditForm.aspx?ID=' + [$ID] + '&IsDlg=1'"
> }
> }

**Comment by zylantha** [comment]
+1 this is a bad bug and an ongoing pain.

The workaround looks like it will only provide an alternate way of editing an item, however when you have a document library that has this issue, you are also prevented from creating new document sets within that list from within the modern view - the workaround is not going to fix this.  You can still create document sets from SP2010 workflows (if you still have them enabled), from REST (e.g. using Plumsail SP) or from the classic experience, however it fails with the modern experience.

**Comment by zylantha** [comment]
I would also add that there are other things that will contribute to this error.  For example, JSON column formatting appears to have a significant effect, and removing or simplifying some JSON column formatting can drop you below the limits.
