### ISSUE TITLE
Make the supportsFullBleed supported

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1425]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'd like to be able to use the full width of the page, that is use the `supportsFullBleed` attribute. This would make the SPO/SPFx experience way better and allow clients to do more customizations

#### Observed Behavior

`supportsFullBleed` is not documented and with that not supported.

**Comment by VesaJuvonen** [comment]
Hi Wictor, can confirm that this is supported. We will start working on official documentation on this one to avoid any confusion. Thanks for submitting this. Will close this one when the doc is available.

**Comment by wictorwilen** [comment]
Boom! Awesome! Will file a bug on this shortly...

**Comment by thechriskent** [comment]
The doc is here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column
