### ISSUE TITLE
How can I autonomously retrieve an OAuth 2.0 Access Token with SPFx v. 1.4.1?

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/sp-dev-docs#1429]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
While in a SPFx client-side Web Part with SPFx 1.4.1, I'd like to be able to retrieve the OAuth 2.0 Access Token to consume the Microsoft Graph or any 3rd party API, for which I have permissions at the tenant level. I see that internally you use the *AadTokenProvider* class to get the token, but I also see that the class is planned to be made internal and for your internal use only. However, there are use cases where I'd like to have the access token and use it directly for low level HTTP/REST requests, rather than having *MSGraphClient* or *AadHttpClient* retrieving it for me and internally using it.

Thus, the question is: can we autonomously retrieve the access token, or if not can you make it possible?
Thanks.

**Comment by patmill** [comment]
For the final release, there will be a way for developers to do this.
