### ISSUE TITLE
njsproj is still provisioned with a new project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#143]
#### Category
[ ] Question
[ ] Typo
[x] Mistake
[ ] Additional article idea

According to the [release notes of drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2) a new project shouldn't have the .njsproj file. After creating a new project that file is however still there.

**Comment by patmill** [comment]
I took the faster approach to solving that issue. :)
