### ISSUE TITLE
Support for ChakraCore

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1432]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'd like to be able to use [node-ChakraCore](https://github.com/nodejs/node-chakracore) to build SPFx solutions. Any plans for support of this?

#### Observed Behavior

When using node-ChakraCore the SPFx build toolchain fails 

#### Steps to Reproduce

Install and configure to use node-ChakraCore and run `gulp serve` and it will fail after a few Gulp tasks

**Comment by dgaeta** [comment]
@wictorwilen Can you make a request at [Sharepoint UserVoice](https://sharepoint.uservoice.com ) and include as much information as possible to help guide our direction. Thanks!
