### ISSUE TITLE
Sharepoint Server 2016 client component SDK for tenant admin?

### ISSUE THREAD

**Issue by khteh** [SharePoint/sp-dev-docs#1434]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

https://www.microsoft.com/en-us/download/details.aspx?id=51679 does NOT have tenant DLL for SharePoint 2016 on-prem. Where to get the library? Thanks!

**Comment by rgylesbedford** [comment]
Hi khteh,

Have a look at the following nuget package: https://www.nuget.org/packages/Microsoft.SharePoint2016.CSOM/
