### ISSUE TITLE
SharePoint Server 2016 Client Components SDK 16 is NOT available on NuGet repository?

### ISSUE THREAD

**Issue by khteh** [SharePoint/sp-dev-docs#1436]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

https://www.microsoft.com/en-us/download/details.aspx?id=51679 is NOT available from NuGet repository. Please advise. Thanks!

**Comment by rgylesbedford** [comment]
Hi khteh,

The following packages have been published by Microsoft for SP2013, SP2016, and SPOnline.
- https://www.nuget.org/packages/Microsoft.SharePoint2013.CSOM/
- https://www.nuget.org/packages/Microsoft.SharePoint2016.CSOM/ 
- https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM/

**Comment by mpasarin** [comment]
The links that @rgylesbedford provided should solve the problem.
Closing this issue.
