### ISSUE TITLE
SPFx Application Customizer extension is not triggered

### ISSUE THREAD

**Issue by mpowney** [SharePoint/sp-dev-docs#1437]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When adding an SPFx sppkg with "includeClientSideAssets": true in package-solution.json, and "cdnBasePath": "" in write-manifests.json, to a Site Collection App Catalog, and adding it to the root site which is a Communication site, the app customizer should execute as expected.

#### Observed Behavior

After adding the sppkg to the Site Collection app catalog, and the app to the site collection, viewing the source of a modern page in the root web shows the "customactions" array with the values from ./assets/elements.xml, but no code is executed.

#### Steps to Reproduce

1. Create a new app customizer project from the latest yo @microsoft/sharepoint template
2. Execute gulp bundle --ship and gulp package-solution --ship
3. Enable the Site Collection App Catalog for the destination site
4. Add the .sppkg file to the Site Collection App Catalog
5. Add the new app to the site collection via the Add an app cog menu option
6. Wait for the app to finish deploying
7. Browse to the home page of the site, open dev tools, observe the following JSON in near the top of the <body> element:

```javascript
"customActions" : [{"title":"HelloWorld","location":"ClientSideExtension.ApplicationCustomizer","clientSideComponentId":"1e8e52ad-7582-4a22-8c1a-e547cb691b78","clientSideComponentProperties":"{\"testMessage\":\"Test message\"}","sequence":65536,"rights":{}}],
```

As per comments in issue #1166 (closed due to lack of response), I have checked for errors in the dev console. There is one error and a bunch of warnings in Chrome's dev console.  These same errors and warnings exist when the app is deployed / customAction is registered, and when the app is not deployed.

Error:

```
GET https://<tenant>.sharepoint.com/sites/utastest02/SitePages/none 404 ()
```

Warnings are a variation of:

```
Ignored setting non-registered setting 'searchux.strings.RefinerPane.ariaRemoveRefinerLabel'.
```

and

```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

I've changed the same app to have a "includeClientSideAssets" value of false in package-solution.json, and "cdnBasePath": to an actual URL in write-manifests.json, and deployed the assets to the URL, re-deploying the app causes the customizer to come to life.

Thanks for your contribution! Sharing is caring.

**Comment by agamadrid** [comment]
Hi
I'm seeing this error when running **serve** in the default app customized that is created when creating the project without making any changes.
      https://<tenant>.sharepoint.com/sites/xxxx/SitePages/none 404 ()

The dialog is not shown, and it "fails" in the promise.resolve
Any idea?
Thanks in advance.

**Comment by srideshpande** [comment]
Thanks for the feedback! We will look into it.

**Comment by mpasarin** [comment]
There was an issue when using "includeClientSideAssets" and the CDN is enabled. That has been fixed and will be rolling out in the next week to 2 weeks.
Feel free to re-open the issue if it still happens after 2 weeks.

**Comment by MaheshakaMudli** [comment]
@mpasarin : We are facing this issue now. It is impacting the performance of the browser in edge and IE. Can you please let us know what causes this issue.

![image](https://user-images.githubusercontent.com/23700986/52769869-9d3fc180-3057-11e9-811d-5034fd2a2951.png)
