### ISSUE TITLE
Apps deploy but not listed in Modern view - Classic view shows reality

### ISSUE THREAD

**Issue by waltsully** [SharePoint/sp-dev-docs#1439]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Expect to see all apps deployed to the site from APPS CATALOG to be listed in Site Contents

#### Observed Behavior
Classic View = okay, Modern View shows only the first ever app added to site, two newer apps not listed

#### Steps to Reproduce

add multiple apps to a site; view site contents in Classic and Modern Views

#### Submission Guidelines

![site contents classic](https://user-images.githubusercontent.com/33215029/37040596-3df76e1a-2128-11e8-8c2e-dcf20c6b0f20.PNG)
![site contents modern](https://user-images.githubusercontent.com/33215029/37040597-3e068440-2128-11e8-9c51-dd5418ecfc32.PNG)

**Comment by waltsully** [comment]
![site contents classic](https://user-images.githubusercontent.com/33215029/37040805-af0c22ee-2128-11e8-862b-0980553aca49.PNG)
![site contents modern](https://user-images.githubusercontent.com/33215029/37040807-af19e1c2-2128-11e8-9dd2-31e480983e59.PNG)

**Comment by waltsully** [comment]
Apps deploy but not listed in Modern view - Classic view shows reality #1439

**Comment by waltsully** [comment]
Whoops. I was trying to delete attachments (screen shots). See below...
![2018-03-06 classic view site contents](https://user-images.githubusercontent.com/33215029/37041084-4ee1b9dc-2129-11e8-831b-b66e04deaf98.PNG)
![2018-03-06 modern view site contents](https://user-images.githubusercontent.com/33215029/37041085-4eefb5d2-2129-11e8-815f-de6519e22895.PNG)

**Comment by waltsully** [comment]
My 3 custom web parts are deployed and work (inserted into a page). The issue is simply that the Site Contents isn't lists them.

**Comment by patmill** [comment]
Hi @waltsully - that's partly expected, but not wholly.  The modern view doesn't show apps that are in an installing state, and there could be some minor timing differences.  Are you still seeing two different views?  If so, we could use a bit of help in tracking this down.  Do you know how to find correlation IDs of requests?  If so, can you send us the correlation ID of the modern and the classic site contents page requests? 
Thanks,
Pat.

**Comment by waltsully** [comment]
Hi @patmill@microsoft.com<mailto:patmill@microsoft.com>

The phenomenon continues. Modern view of site contents one App shown; classic shows all three I’ve added.

correlation IDs of requests? This is done with f12 traces? Or Fiddler?

walt

**Comment by patmill** [comment]
Hi Walt - yes.  F12 should work fine.  Look at the network request to the viewlsts.aspx page.  If you look at the response headers, there should be a header named something like SPRequestID, with a GUID as the value.

**Comment by waltsully** [comment]
@patmill@microsoft.com<mailto:patmill@microsoft.com>

From viewlsts.aspx headers

CLASSIC:  sprequestguid:  ee2b559e-40ae-5000-5313-8c4a11702bdc
MODERN: sprequestguid:  8c2b559e-101f-5000-6ef2-9fa54de2488

**Comment by patmill** [comment]
Thanks @waltsully - I've updated our bug with this information.

**Comment by waltsully** [comment]
Not sure if online SP updates have happened. I now have different but related symptoms:
   Classic View correctly showed three web-parts each with unique name
   Modern View show three web-parts all with same name & date.

**Comment by waltsully** [comment]
If this helps… when I deleted the web-part from the site contents (using classic view) the modern view then listed two apps both named and dated the same. The part name shown was of one of the remaining two (repeated).
