### ISSUE TITLE
gulp serve error after upgrading - OSX

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#144]
#### Category
[ ] Question
[x] Bug?
[ ] Typo
[ ] Mistake
[ ] Additional article idea

I tried to upgrade to the new version and got the following error messag when I tried to ```gulp serve```. I followed all steps to upgrade but without luck.
<img width="475" alt="screen shot 2016-09-02 at 18 28 10" src="https://cloud.githubusercontent.com/assets/5503835/18210962/71378164-713b-11e6-9940-32a0f30ab48c.png">

OSX / NodeJS / npm version:
<img width="591" alt="screen shot 2016-09-02 at 18 32 43" src="https://cloud.githubusercontent.com/assets/5503835/18211011/b0bfd9a8-713b-11e6-9241-9d4fe5f712e2.png">

Old version worked on NodeJS 5.x and even when I create a new version.

**Comment by patmill** [comment]
Did you happen to replace the tslint config file?  If you start from a new project, does the error persist?

I'll track down a dev with a mac and see what I can find out.

**Comment by StfBauer** [comment]
Got it running. Was the tslint.config file that caused the problem. You might add to the documentation to replace the tslist.config because it won't be automatically updated.

This files are outside of the packages. Once I replaced it the workbench launched without any problem. The info just says the files was completly updated but doesn't completly update automatically.
For people like me: "Update the file manually with the one from the [gist](https://gist.github.com/nickpape-msft/b3a0e0a4d64c029794eb4d2318d54308)"

Thanx @patmill

**Comment by patmill** [comment]
Updated the doc

**Comment by patmill** [comment]
Clarified the doc.  Hopefully that is clearer.  It also sheds light on this conversation (https://github.com/SharePoint/sp-dev-docs/issues/145), in that sometimes the update could be more than just changing the package.json file.

**Comment by StfBauer** [comment]
@patmill Great thanx.
