### ISSUE TITLE
Please remove the 'Make your browser wider overlay from workbench'

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1444]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The local and Office 365 Workbench should not display an overlay make your screen wider. This avoids the seamless responsive transition testing because the content in the Workbench will be hidden behind the overlay.

#### Observed Behavior
When I resize the workbench to be narrower and want to emulate the seamless responsive behaviour suddenly the following overlay appears.

<img width="359" alt="screen shot 2018-03-07 at 00 24 44" src="https://user-images.githubusercontent.com/5503835/37081568-acc6dd0a-219e-11e8-8af0-916f42657e62.png">

For a developer, it should be clear that actually the page cannot be edited anymore and for the end user it is not likely that they use the workbench anyway.
In addition, this also avoids the possibility to use native browser device testing as seen in the following screenshot.

<img width="1246" alt="screen shot 2018-03-07 at 00 32 06" src="https://user-images.githubusercontent.com/5503835/37081698-1fa98d5e-219f-11e8-8e1b-48006c6f5f46.png">

The screenshot was taken in Google Chrome with the responsive device testing set to iPhone 7.

#### Steps to Reproduce
**Step 1 - Browser Size Test**
- Open local or Office 365 Workbench
- Add a web part to the page
- Resize the Browser Window to be 375px or less

**Step 2 - Developer Tools Test**
- Open local or Office 365 Workbench
- Add a web part to the page
- Enable Developer Console in Google Chrome or any other browser that supports this
- Enable Responsive Device Tester - Blue Icon on Toolbar
<img width="478" alt="screen shot 2018-03-07 at 00 37 29" src="https://user-images.githubusercontent.com/5503835/37081885-c52e1876-219f-11e8-8179-59a00ed6ac03.png">
- Set the Device to any smaller screen size such as iPhone 7 for example

**Comment by mcmynn83** [comment]
Thank you for the feedback.  This is a new feature request that we will evaluate.

**Comment by StfBauer** [comment]
@mcmynn83 I would call it more a rollback request. Because this behaviour is pretty new.

**Comment by mcmynn83** [comment]
@StfBauer - I did not realize this, I will follow up internally.
