### ISSUE TITLE
Use DetailsList (from Office UI Fabric) as custom Property Pane control

### ISSUE THREAD

**Issue by OskarSol** [SharePoint/sp-dev-docs#1446]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Trying to implement a custom property pane control. In the first working version I used from the Office UI the "[List](https://developer.microsoft.com/en-us/fabric#/components/list)" component to display my options like this. 
![grafik](https://user-images.githubusercontent.com/37073408/37097903-d9a01d4a-221c-11e8-9bac-10a7be3121d3.png)

Instead of the List component I want to use the [DetailsList ](https://developer.microsoft.com/en-us/fabric#/components/detailslist)component from Office UI.

#### Observed Behavior

The DetailsList component will not render. I see nothing.
![grafik](https://user-images.githubusercontent.com/37073408/37098217-a5a1cc9a-221d-11e8-892b-eeb1488f0ec1.png)

 If I try to use the DetailList as a normal WebPart component (and not in the Property Pane) it works as expected. 

#### Steps to Reproduce

Implement the example from https://developer.microsoft.com/en-us/fabric#/components/detailslist And follow the guidline for custom controls from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-custom-property-pane-controls 
!OnPremise SharePoint 2016!

**Comment by mpasarin** [comment]
Thanks for your feedback @OskarSol 
We are going to look into this issue shortly and will keep you updated.

**Comment by jannovakcnx** [comment]
I have exactly the same issue.

**Comment by OskarSol** [comment]
On Premise Sharepoint 2016 or SharePoint Online?

**Comment by russgove** [comment]
FYI /The sample at
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-multilist-grid
uses details list in the property panel by openning up a modal/

**Comment by russgove** [comment]
disregard previous. I did not use the details list there.

**Comment by jannovakcnx** [comment]
In my case problem could be observed in SharePoint Online and my local development workbench too.

**Comment by OskarSol** [comment]
So the problem appears regardless if the solution is deployed in SharePoint Online (spfx-version 1.4) or 2016 (spfx-version v1.1) and if it's deployed in a modern or a classic page.

**Comment by OskarSol** [comment]
I'm now again reached the point where I need a details list in the property pane...
