### ISSUE TITLE
JSON Column Formatting in a List not flowing through when using the List SPFX Web Part

### ISSUE THREAD

**Issue by georgekhalil** [SharePoint/sp-dev-docs#1448]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I have applied some JSON column formatting which works quite nicely when viewing the List directly. However, the same formatting is NOT applied when adding the list to a SharePoint Modern Page utilising the List Spfx Web Part. #spfx @spfx-webpart

Thanks

**Comment by mcmynn83** [comment]
Could you please give more information to help us diagnose this issue?  What JSON column formatting are you adding specifically (or is this for any column formatting)?

**Comment by georgekhalil** [comment]
This is for any column formatting - For example, it works when I access the list direct

[cid:image001.png@01D3C038.D041C870]

But it doesn’t work when accessing the list via the list preview web part.

[cid:image002.png@01D3C038.D041C870]

**Comment by thechriskent** [comment]
This is now working with some minor style differences (with links):

On List:
![image](https://user-images.githubusercontent.com/8364109/42221463-1149402a-7ea0-11e8-8f35-a53f9e0ea6b3.png)

On Page:
![image](https://user-images.githubusercontent.com/8364109/42221482-1f357a82-7ea0-11e8-9822-5c64362decf6.png)
