### ISSUE TITLE
How to use GITHUB samples in sharepoint ?

### ISSUE THREAD

**Issue by rinu007** [SharePoint/sp-dev-docs#1450]
I have never used GITHUB samples before. I thought its a simple matter of downloading the code and editing it Visual studio to make it work. But it seems not the case. is there any step by step guide to use it.

I found this but couldnt understand how to go about it. https://github.com/SharePoint/sp-dev-fx-extensions#using-the-samples

**Comment by joelfmrodrigues** [comment]
Hi @rinu007 ,

Guidance will highly depend on the type of sample you are trying.
At an high level, that guide is correct for SPFx extensions as it starts with cloning the project to your machine up to the point where the project is running locally on your machine. You then need to add the extension to your site (you can find detailed info [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension))

Is there a specific problem you are facing?

**Comment by rinu007** [comment]
@joelfmrodrigues , 
Cloning? i got the option to download or clone . when i click on it i got a zip file. How do i clone it? I am trying to use it against  sharepoint online.

**Comment by patmill** [comment]
Sorry - I'm going to close this issue, as it isn't really a bug / issue / etc.
