### ISSUE TITLE
tabIndex type definition

### ISSUE THREAD

**Issue by smithywick** [SharePoint/sp-dev-docs#1451]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Expected tabIndex="0" to set the tab order for HTML elements on the page, and getting a type error.

#### Observed Behavior

When using tabIndex="0" I'm getting a type error for a string. When using tabIndex=0 I'm getting a type error for a boolean.

#### Steps to Reproduce

Inside of a div type tabIndex="0" to see the type error.

#### Submission Guidelines

Adjusting the type definition from tabIndex?: number; to tabIndex?: string; resolved the issue for me. Using spfx v 1.4.1.

Thank you

**Comment by dgaeta** [comment]
@smithywick This does look like a bug. 
Can you provide more info on what typing your updating? Is it the React typings that you updated to resolve the issue?

**Comment by VesaJuvonen** [comment]
Closing due no response on the question from @dgaeta. Let's re-open, if needed.

**Comment by smithywick** [comment]
@dgaeta it's in the DefinatelyTyped repo found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v15/index.d.ts#L2415).
