### ISSUE TITLE
Site Logo on modern sites contains unnecessary grey border

### ISSUE THREAD

**Issue by jonthenerd** [SharePoint/sp-dev-docs#1452]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The site logo area should show the selected site logo without modification, be consistent throughout the site (modern vs classic pages), and provide organizations with logos w/transparent or white backgrounds to brand their sites simply.

#### Observed Behavior

The site logo on a modern site contains a grey border. This grey border is not present on classic pages within the site. When using an image with a transparent or white background, this grey border is not visually appealing and presents an issue for adopters with company logos that fit this scenario.

Difference:
![site icon issue on modern sites](https://user-images.githubusercontent.com/3116033/37159040-65017a56-22b2-11e8-829a-a95b13780e69.png)

The CSS selector directly causing this is **.ms-siteLogoContainerOuter**, and while there are ways to override this from within an SPFx WebPart/Application Customizer, doing so has the following negative consequences:

- If Microsoft changes the page structure or CSS, this override will break, as SPFx components are not designed to be affecting page rendering in this manner.
- As the CSS override is loaded via JavaScript, there is a brief delay in which the grey border is visible and then disappears.

The expected behavior is for there to be no grey border, which would make it consistent with classic pages and not cause issue for sites using logos with solid color backgrounds.

#### Steps to Reproduce

1. Create modern site.
2. Add a logo with a transparent or white background
3. Note undesirable grey border

**Comment by patmill** [comment]
Thanks for the feedback @jonthenerd .  I've forwarded the request to the design team, but at the moment this is by design in modern experiences.  If you wish, you can open a feature request in user voice ( https://sharepoint.uservoice.com/ ). 
Pat.
