### ISSUE TITLE
Search Box on modern sites does not abide by Site Settings

### ISSUE THREAD

**Issue by jonthenerd** [SharePoint/sp-dev-docs#1454]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The search box on modern pages should be consistent in behavior with classic pages, abiding by search settings set on the site collection or site level (send to search center, send to specific page, etc.). This allows organizations to send users to more targeted search pages w/refiners, search broader scopes from a high-level landing site, etc.

An alternative desired behavior is to provide separate configuration settings for modern pages within a site to utilize. 

#### Observed Behavior
No matter the settings applied with search settings (/_layouts/15/enhancedSearch.aspx), modern pages will only search within the site. Users must perform the search, then on the modern search results page change the dropdown to "All Sites" to achieve any broader scope. This is not acceptable for creating corporate intranet landing pages that desire to have users search a broad scope by default.

#### Steps to Reproduce

1. Create Modern Site
2. Change search settings (/_layouts/15/enhancedSearch.aspx)
3. Note no changes in search box behavior

**Comment by rjesh-git** [comment]
I'm looking for vote button to push this issue to top of the list. 
This is **most wanted feature from most of our customers**.

**Comment by VesaJuvonen** [comment]
We do apologize for the delay, but as this is NOT a developer issue, we would ask to open this through the standard SharePoint Online support channel. You can open a case from your tenant administrative pages.
