### ISSUE TITLE
Can we please have a root level tslint.json?

### ISSUE THREAD

**Issue by gavinbarron** [SharePoint/sp-dev-docs#1455]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

It's really frustrating to have linting failures in the VSCode editor in freshly generated code. It can also be somewhat less productive to have linting issues arise and not be notified of them until the build pipeline executes the linting step.

#### Expected or Desired Behavior
When using VSCode and tslint with the [vscode-tslint](https://github.com/Microsoft/vscode-tslint) extension we should not get linting warnings with the default generated code.

![Sexy valid TypeScript](https://content.screencast.com/users/gavinbarron/folders/Snagit/media/d32a43e6-e2db-46c3-96d2-b283fa909be8/03.08.2018-14.10.png)

#### Observed Behavior
When using VSCode and tslint with the [vscode-tslint](https://github.com/Microsoft/vscode-tslint) extension we get linting warnings with the default generated code.

![Ugly Redsquigglies](https://content.screencast.com/users/gavinbarron/folders/Snagit/media/7e6d93ef-175b-4067-b60e-06a4cb049cfe/03.08.2018-14.06.png)

#### Steps to Reproduce
Install the tslint extension in VSCode
Generate a new webpart 
Open the the webpart.ts file and observe the linting failures

#### Suggested resolution
Add a tslint.json file to the root of the project with the below content:
```
{
    "rulesDirectory": "./config"
}
```

This is a simple fix to ensure that developers get informed of linting issues in the best editor

**Comment by joelfmrodrigues** [comment]
+1 to that. Wrote a blog post some time ago about that and also created a new thread on user voice, but only got a few votes...
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/32544955-make-spfx-projects-compatible-with-tslint-vscode-e 
That setup definitely increases productivity

**Comment by gavinbarron** [comment]
@joelfmrodrigues Thanks for that blog post, I saw the change that you made to the samples some time back. I finally got around to raising the issue here though.

**Comment by mpasarin** [comment]
Thanks for your feedback @gavinbarron 
We will consider adding this on the next version of SPFx Yeoman generator.

**Comment by gavinbarron** [comment]
Thanks Marc :)

**Comment by joelfmrodrigues** [comment]
@mpasarin that would be awesome! Once you try the TSLint extension on VS code while doing SPFx dev, you never go back :) Waiting for the command line to display errors is just not fast enough
