### ISSUE TITLE
How to delete a single webpart from project?

### ISSUE THREAD

**Issue by 4lexk** [SharePoint/sp-dev-docs#1456]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
I have a project containing multiple spfx Web Parts. Is there a function in yo to remove one single WebPart from project?
If not, how to proceed manually, i guess there are many files with references/dependencies?

**Comment by joelfmrodrigues** [comment]
Hi @4lexk ,

There isn't a command as far as I know...
You will need to delete the web part code, which should be under src/webparts/your_web_part **AND** remove the references for the web part inside config/config.json

**Comment by mcmynn83** [comment]
That is correct, there is no built in functionality in Yeoman to remove a webpart.  If you would like this feature added please make a request on uservoice and based on community interest we may or may not take the change.
