### ISSUE TITLE
SharePoint Online - Site closure and deletion not working

### ISSUE THREAD

**Issue by thunem** [SharePoint/sp-dev-docs#1457]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We have used PnP to provision sites and add policies. But when the date for deletion has passed the site collection do not get deleted.

This is standard SharePoint functionality.. so I have no idea what's going on.

![image](https://user-images.githubusercontent.com/8638891/37205595-972a69c8-2395-11e8-88e6-8b241e4b876a.png)

The picture shows a site that should have been deleted (+one week for the timer job / timezone) since 1. march. But we also have sites that should have been deleted aug 2017.

#### Observed Behavior
When you apply the policy to the site collection the site should be deleted based on the policy criteria. 

#### Steps to Reproduce
We've used PnP to provision sites. When the deletion date/time ticks in the site collection will not get deleted. The site is in "write protection" but not deleted. I've tried to apply new policy to the site collection without any luck.

**Comment by mcmynn83** [comment]
@thunem - Thank you for your feedback.  This issue seems specific to your tenancy and the team would need more information in order to diagnose the issue.  Could you please open up a support issue?

**Comment by BDBARB** [comment]
I have the same issue. I need to set this on over 300 subsites that were migrated that have not been used in over a year (up to a decade) and plan to implement this to push users to move their old data to OneDrive or Teams. So far no one gets any email warning of pending deletion, I have it set to notify daily. Any luck on your end?
