### ISSUE TITLE
Bug: Highlighted Content WebPart error on browser back button

### ISSUE THREAD

**Issue by rjesh-git** [SharePoint/sp-dev-docs#1458]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Highlighted Content webpart, configured to show only sites. Click on the card link open the site in the same window, hit back button to navigate back to the page where webpart was added.

#### Observed Behavior

Click on link (For cards layout, click on the link with smaller font), hit browser back button and see,

![screen shot 2018-03-09 at 9 20 02 am](https://user-images.githubusercontent.com/9443767/37220324-1c1eff7e-237b-11e8-820c-c20941230422.png)

------|-----------
**Something went wrong**
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS

ERROR:
***The value for "Duplicate web part id not allowed" is false

CALL STACK:
Error: ***The value for "Duplicate web part id not allowed" is false
    at Function.e.isTrue (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-23.006/sp-pages-assembly_en-us_ec564824dbf6a181d45720395d9a194e.js:294:1380)
------|-----------

#### Steps to Reproduce

1. Create new site page
2. Add Highlighted Content webpart
3. Configure below
4. Source: All sites
5. Document type: Any
6. Filter: Managed Property - WebTemplate Equals Group
7. Sort by: Most recent
8. Layout: List or Cards (For cards, click on the link with smaller font)

**Comment by briester1** [comment]
Running into the same error on my new SharePoint Communication sites.

**Comment by mcmynn83** [comment]
Thanks for the feedback, we will take a look at this issue.

**Comment by srideshpande** [comment]
Hello @rjesh-git & @briester1 - This issue is now fixed. Its in the build pipeline and you should be able to see it in the new release which will be no more than two weeks from now. Please let us know if you guys don't see it then. I am closing the issue for now. Feel free to re-open it if you don't see the fix.

Thanks,
Srikanth

**Comment by rjesh-git** [comment]
Thanks for looking into it Srikanth. Its fixed already in our tenant as well as in our customer.

--
Rajesh.

**Comment by briester1** [comment]
I'll keep checking our site collections. We were running into it on the header image for communication site. Thanks for the update.
