### ISSUE TITLE
Mismatch in SPFX ListviewCommandSet buttons visibility in modern Document Library

### ISSUE THREAD

**Issue by devoooo4u** [SharePoint/sp-dev-docs#1459]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When set the visibility of the the custom button, It should be applicable at both places (ContextMenu + CommandBar). 
I am having 2 buttons (Add Fav + Remove Fav). Based on few conditions, i am setting them up as visible = true / false.
So this visibility setting should be applied globally for both  (ContextMenu + CommandBar)  but shows otherwise behavior.
Note: this behavior is noticed if I do multiple Add/remove Favorite operation on single document.

#### Observed Behavior
Buttons are mismatched.. 
If "Add To Fav" is set to be visible "true" is should be at both the places (Context menu + Command Bar).. & vice versa for "Remove from Fav" button.

 refer SS,   
![image](https://user-images.githubusercontent.com/19596216/37328796-6f7b841e-26c1-11e8-8966-60ae00b35fb6.png)

#### Steps to Reproduce
Consecutive attempts to add and remove favorite button for an item leads to this button mismatch . This is my element.xml file structure::
```
 <CustomAction
        Title="FavouriteButton"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet"
        ClientSideComponentId="guid">
    </CustomAction>
```
and commandsetmanifest.json file::

```
  "items": {
    "AddFavourite": {
      "title": { "default": "Add to Favourites" },
      "iconImageUrl": "/Fav.png",
      "type": "command"
    },
    "RemoveFavourite": {
      "title": { "default": "Remove from Favourites" },
      "iconImageUrl": "/RemoveFav.png",
      "type": "command"
    }
  }
```
#### Submission Guidelines

**# EDIT 1:** 
We can set the the location of custom command buttons by  Location="ClientSideExtension.ListViewCommandSet".  Is there a way possible where I can capture the Events triggered by  ContextMenu & CommandBar buttons separately. ?? 

Thanks for your contribution! Sharing is caring.

**Comment by mpasarin** [comment]
Thanks for your feedback.
How do you track these conditions that cause one command or the other to be visible?
When you have a command set in both context menu and command bar those are 2 different instances of the command set. If you are relying on any variable from the object at runtime, that may cause this unexpected behavior.

**Comment by devoooo4u** [comment]
Thank you mpasarin fo the response, And yes I am relying on Object value calculated during runtime. I am managing the buttons visibility based on items retrieved from a List. 
Also, I observed that overridden method  @onListViewUpdated is triggered multiple times (6+ times) during single toggle of List Item selection, This can be optimized too.
so two buttons (Context menu and Command Ribbon) are slightly deviated from being duplicate buttons.
Thanks! Sharing is Caring !

**Comment by frnk01** [comment]
Any news on this issue? Visibility on command set buttons should be possible to update..

**Comment by patmill** [comment]
Hi, sorry for the long delay.  We are trying to clean up and make sure we haven't missed issues.  We are unable to repro this issue now.  Please feel free to create a new issue / reopen this one if the particular case is still a problem.
