### ISSUE TITLE
Requests to WasUpload.ashx are made after turning of CEIP

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#1461]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In a SharePoint 2016 on-premises server, when you turn off CEIP, requests to WasUpload.ashx are not made.

#### Observed Behavior

In a SharePoint 2016 on-premises server, when you turn off CEIP, requests to WasUpload.ashx are made.

#### Steps to Reproduce

Turn off CEIP on a SP 2016 on-premises server.
Create a hello world SPFx Web Part.
Deploy it to the SP 2016 on-premises farm.
Add it to a page.
Inspect the network traffic when the page loads and see the requests to WasUpload.ashx.

**Comment by VesaJuvonen** [comment]
Few clarifications for easily issue tracking and to get things moving. 

- CEIP - Customer Experience Improvement Program

**Comment by VesaJuvonen** [comment]
Hi Todd, disabling CEIP in the server does not mean that the wsaUpload.ashx is not called. It means that this information is not shared with Microsoft from the server. You might still see oob web parts and other elements calling this on the client side, as there's no check for CEIP in them one-by-one. 

If you inspect network traffic from the server - you should NOT see any information be sent to Microsoft. If you'd see however any traffic from the SP2016 farm towards Microsoft, then that would be a clear bug and an issue. 

Closing this for now, unless there are additional details which missed.

**Comment by TBag** [comment]
Roger that, thanks.

**Comment by marcelaopimenta** [comment]
Hi @VesaJuvonen!

Do you have any news? I Have the save problem as @TBag ...

And, my client wants a justification because it is so...

I know I have no communication with Microsoft servers, but the error in console is bringing me a big problem.

Thank you!

Best Regards

**Comment by ohiobobcat** [comment]
This has also become an issue for my client due to the console errors, minor performance issues, etc. Opened a ticket with Microsoft and was told that the product team deems this a non issue. I, as well as my client, disagree wholeheartedly.

**Comment by samculver** [comment]
Also an issue for my client on SP 2016; we get console errors which cause issues with performance testing. Seems like a bug with the SPFx framework where these calls can't be disabled. There is a global variable in the master page "g_wsaEnabled = false" that should disable this, but SPFx appears to ignore this. It would be great to get a definitive answer that this is or is not a defect with early version of SharePoint Framework for SP 2016.
