### ISSUE TITLE
Reply URL and Wildcards for AAD Secured API

### ISSUE THREAD

**Issue by akhileshnirapure** [SharePoint/sp-dev-docs#1462]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Explanation on why Wildcards can't be use in Reply URL. Also please clarify if wildcard can be used when working with AadHttpClient?

#### Observed Behavior
The Article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad talks about the restriction on Reply URL. The article http://paulryan.com.au/2016/azure-ad-app-wildcard-reply-url talks about using wildcard in Reply URL, is it okay to use wildcard approach with  @SPFx?

@waldekmastykarz @VesaJuvonen 

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Wildcards can be used as Reply URL. There are no limitations on that. Not quite understand why that would not be the case. This is Azure AD side of the story and not really SPFx specific implementation.
