### ISSUE TITLE
Used instructions from Hello World part 4 to deploy webpart from the next lesson - unsuccessfully

### ISSUE THREAD

**Issue by jlisham** [SharePoint/sp-dev-docs#1467]
After the next lesson (Add jQueryUI Accordion to your web part), I tried using the instructions from _**Host your client-side web part from Office 365 CDN**_ (Hello World part 4) to deploy jQueryUI web part and everything worked/appears as expected, except: I'm not able to add the webpart to a new page (doesn't appear as an option).

I'm not sure what I'm missing?

Really enjoying this series! Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4) | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by srideshpande** [comment]
@jlisham  - Thanks for reporting the issue. What SPFx version are you on? If not already, could you upgrade to 1.4.1 version and re-do the steps and let us know if you still see the issue?

Thanks,
Srikanth

**Comment by VesaJuvonen** [comment]
Closing due to no response for the Sri's question as unless we can reproduce the issue by knowing what exact versions are in use or having access to the solution, there's really no way to provide any support for the issue.
