### ISSUE TITLE
Disable Toaster notification on sucessful and failed builds

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#147]
#### Category
[x] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea

<img width="387" alt="screen shot 2016-09-02 at 22 23 17" src="https://cloud.githubusercontent.com/assets/5503835/18217340/884f83ee-715c-11e6-9714-2b53dada8376.png">

Is there some option available to disable this toaster notification? The reason is when you develop something it cause a lot of distraction whenever you save a file.

**Comment by nickpape-msft** [comment]
Yes. Add

```
build.setBuildProperties({
  showToast: false
});
```

to your `gulpfile.js` before the `build.initialize(gulp);` line. That should do the trick. For whatever reason I never see the toast on my PC, so I wasn't able to validate it, but that should work.

**Comment by waldekmastykarz** [comment]
In sp-build-web there is the `showToast` option defined. If showing toast is enabled by default isn't that option obsolete and shouldn't it be changed to `noToast` so that you can disable it using `gulp serve --noToast`?

**Comment by nickpape-msft** [comment]
Thanks for pointing that out Waldek. Yes, we did deprecate that option from the command line, as it seemed more like something the developer would want either always on or always off.. I've updated the help text.
