### ISSUE TITLE
Is there a way to avoid ADAL JS popup?

### ISSUE THREAD

**Issue by mcraiha** [SharePoint/sp-dev-docs#1471]
Because certain browsers, browser extensions and security tools will block those popups and that will cause the login process to stop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consuming APIs secured with Azure AD within the SharePoint Framework | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
Unfortunately, there is no way to avoid the pop up. The authentication process is a part of Azure AD and while usually handled automatically, in certain scenarios it might be interactive, requiring the user to respond.

**Comment by jonthenerd** [comment]
Avoiding the popup is sorely needed. If you have multiple data sources to hit on a single page to display data page load within SPFx webparts, the user will be bombarded by popups. Or if the page in question is a highly used landing page, immediately showing a popup is a deal-breaker for integration of third-party user-specific data...

**Comment by mcmynn83** [comment]
Thanks for the feedback.  Unfortunately at this time the pop up is necessary and there is no way to get around it.  However, internally we are looking at possible solutions to avoid this, but at this time there is no guarantee that it will change.  You could open up this issue in uservoice if you want, however, we are actively looking into solutions already.

**Comment by jcollinsks** [comment]
I agree let's get rid of the pop ups, if the user needs to interact this should load in place of the SPFx webpart, in place.
