### ISSUE TITLE
SharePoint native mobile app (iOS / Android) detection & deep linking

### ISSUE THREAD

**Issue by kmees** [SharePoint/sp-dev-docs#1472]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a way to detect if the user is using the native mobile app for SharePoint? My SPFx WebPart needs to behave slightly differently in a mobile app than in the browser. Also, is there a way to deep link directly to a user profile in the mobile app?

Thanks

**Comment by VesaJuvonen** [comment]
This should be possible with user-agent inspection, but we'll confirm the right model in a day or two if there's additional ways to do this.

**Comment by russgove** [comment]
hold on there.... I can use spfx webparts in the sharepoint mobile client? i don't need to use powerapps if i want mobile? I had no idea. doubt many others did!

**Comment by kmees** [comment]
@VesaJuvonen i had looked at the user agent already but it seemd a bit hacky.

Mobile App (iOS):
```
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D100
```

Safari (iOS)
```
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1
```

The only difference is the missing `Safari` part. Haven't tested Android yet.

**Comment by tidg** [comment]
Hi @VesaJuvonen,
Do you have any information about this case? 
Is the user agent the only way to detect that we are on the Sharepoint app?
I tried to watch the ribbon content with `document.getElementById('SuiteNavPlaceHolder').innerHTML === "",` but when it takes times to load on browser, we find ourselves in the same case that we are on the Sharepoint App or on the browser.
Waiting for your feedback.

**Comment by JosueRuiz89** [comment]
Hi,

I'm also using some elements in DOM as workaround but seems a little bit hacky, A JavaScript environment/context variable would be great, I have been trying to find a clean way to identify if user is using SharePoint App without success, I subscribed to the thread, hope this get answered some day.

**Comment by holylander** [comment]
Hi!
This may be a bit offtopic, however, does anyone knows if besides detecting if user is accessing the site from the Mobile App, is there any way to obtain certain phone context information, as current Wifi ESSID or stuff like that? thanks

**Comment by AJIXuMuK** [comment]
Currently `navigator.userAgent` for SharePoint iOS native app contains `SharePoint for iOS'

**Comment by VesaJuvonen** [comment]
Seems that @AJIXuMuK answered on this and looks like a proper way to deal with this. If question is still open, please submit a new issue. Closing this as anwered.
