### ISSUE TITLE
[LOC] - Link redirect to a non existing page

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#1474]
Link redirect to a non existing page.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-net-client-object
2. Search for "CanReply" click on the first hit

**Actual result:**
Link redirects a non existing page

**Expected result:**
Link redirects a existing page

**GH article:**
https://github.com/SharePoint/sp-dev-docs/blob/live/docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-net-client-object.md

![canreply](https://user-images.githubusercontent.com/16706698/37461859-2324cd24-2850-11e8-98ed-86ebe8a7c3f3.png)

**Comment by KevinTCoughlin** [comment]
Looks like this might be the updated URL -- https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.social.socialthreadattributes.aspx

Happy to make a PR if you'd like

**Comment by cakriwut** [comment]
@VesaJuvonen  the link is correct. I suggest to close this issue.
