### ISSUE TITLE
AADHttpClient: Sample for using WebApi ASP.NET Core 2.0

### ISSUE THREAD

**Issue by Nasicus** [SharePoint/sp-dev-docs#1476]
Is there any sample server side application which would work with the `AADHttpClient`?
I'm currently using the iframe-cookie [approach](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad#access-the-api-by-leveraging-sharepoint-online-authentication-cookie) which means that my authentication code looks like this https://github.com/aspnet/Security/issues/1583#issuecomment-354953746.
However it would be nice if I could get rid of the iframe and just use the AADHttpClient instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD secured APIs in SharePoint Framework solutions | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The `AADHttpClient` is intended for client-side use, not server side, for use in calling 3rd party endpoints. There are already a lot of different ways to call 3rd party APIs from the server using ADAL / MSAL that has nothing to do with SharePoint... I'd check this for more details: http://aka.ms/aaddev

**Comment by frankchen76** [comment]
Have you check [Secure the API using Azure App Service Authentication](https://github.com/SharePoint/sp-dev-docs/issues/1476#issuecomment-375656482) ? it actually used Azure App Service Authentication to secure your Web API. But if you need to implement authorization based on the role, JwtAuthentication would be better.

**Comment by tejyapranthi** [comment]
I am getting below error when I am using AADHTTPClient and running it in workbench.html
sp-http.js:1570 Uncaught (in promise) Error: This operation cannot be performed until the AadTokenProvider is initialized.
    at AadTokenProvider.getToken (sp-http.js:1570)
    at sp-http.js:2414
    at ServiceScope.whenFinished (sp-loader-assembly_en-us.js:9861)
    at sp-http.js:2410
    at new Promise (<anonymous>)
    at AadHttpClient.fetch (sp-http.js:2409)
    at AadHttpClient.get (sp-http.js:2433)
    at SpfxaadWebPart.ts:42
    at new Promise (<anonymous>)
    at SpfxaadWebPart.getData (SpfxaadWebPart.ts:41)

**Comment by tejyapranthi** [comment]
Web API Permission Request is not showing in my API Management.
The follwing are the steps followed by me.
1.Creating WedAPI in visual studio .
2.Creating app in azure.
3.Adding WebAPI in created app (appname:-AADApp).
4.Creating SPFX solution.
5.Adding WebAPIpermissionrequest as
"webApiPermissionRequests": [
{
"resource": "AADApp",
"scope": "User.ReadBasic.All"
}]
6.Deployed solution of an spfx in appcatalog.
7.Added int o sitecontents.
8.Here it's not showing any permissions to approve in apimanagement.

I am also getting error like"Uncaught (in promise) Error: This operation cannot be performed until the AadTokenProvider is initialized." in workbench.html.
when I am performing "gulp serve".

-> when i deployed solution in app catalog and with out approving permissions i am using the spfx web part .
But here it was showing error like

sp-pages-assembly_en-us_bbf1ba8e18797f770e10fb0068654369.js:602 Uncaught (in promise) Error: AADSTS50001: The application named "--application name is here--" was not found in the tenant named "--tenant name is here--". This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 55be378a-bf9e-47ef-847d-48067a170e00
Timestamp: 2018-03-30 07:35:02Z
at Array. (sp-pages-assembly_en-us_bbf1ba8e18797f770e10fb0068654369.js:602)
at _callBackMappedToRenewStates.(/sites/DLRDestination/SitePages/anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-16.021/0.sp-http-adal_4a41848c866052caa755.js:3:7561)
at AuthenticationContext.handleWindowCallback (adal.min.js:2)
at parseTokenFromUrl (spfxsinglesignon.aspx:23)
at onload (VM1413 spfxsinglesignon.aspx:30)

**Comment by tejyapranthi** [comment]
If there are more than 100 entries In APIManagement  means it won't show latest one.To have latest one either we have to approve or reject previously entered permissions.

**Comment by tejyapranthi** [comment]
In workbench.html it will show error like "Error: This operation cannot be performed until the AadTokenProvider is initialized." .but if we upload spfx app solution in app catalog and use it in webpart the above error will not come.

**Comment by Nasicus** [comment]
make an own issue for this, it has nothign to do with what I asked.

**Comment by frankchen76** [comment]
@tejyapranthi it seems like you didn't create a scope in your AAD App manifest from the steps you listed.
 `"webApiPermissionRequests": [
{
"resource": "AADApp",
"scope": "User.ReadBasic.All"
}]`
when you specified `User.ReadBasic.All` in your permission request, did you define this scope in your Web Api AAD App manifest?
BTW, it seems like your questions isn't associated with what @Nasicus asked. would you mind to create a separate thread?

**Comment by cythomli** [comment]
@tejyapranthi I'm getting the same error
