### ISSUE TITLE
Simple upgrade of generator (drop 1 to drop 2) not good enough. Had to reinstall generator and tooling

### ISSUE THREAD

**Issue by paulryan** [SharePoint/sp-dev-docs#148]
#### Category

[x ] Bug?
#### Expected or Desired Behavior

After successfully running drop 1 projects, upgrading the generator to drop 2 (npm i -g @microsoft/generator-sharepoint@latest) caused new projects to fail during gulp serve.
I resolved this issue by performing the following steps (I did them all at once so can't identify what specifically solved my issue:
- npm uninstall -g @microsoft/generator-sharepoint
- npm i -g @microsoft/generator-sharepoint
- npm install --global --production windows-build-tools
- npm install -g yo     (v1.8.4  => v1.8.5)
#### Observed Behavior

Gulp errors:
![image](https://cloud.githubusercontent.com/assets/3141243/18225994/7e83a9a2-71f8-11e6-805e-195bc19fddd7.png)
Resulting in workbench.html failing to reach local host:
![image](https://cloud.githubusercontent.com/assets/3141243/18226009/c65bb31e-71f8-11e6-852d-306194f54676.png)
#### Steps to Reproduce

Install drop 1 of the generator. Upgrade it to latest (drop 2).
Create new template using the generator (using React)
Run gulp serve

(Windows 10, Surface Book)

**Comment by parikshit-patel** [comment]
@paulryan: Is it working with "http"?
Url: http://localhost:5432/workbench

**Comment by parikshit-patel** [comment]
@paulryan: Is it working with "http"?
Url: http://localhost:5432/workbench

**Comment by patmill** [comment]
that sort of error normally means something else is already configured for the port.  Postgres SQL uses port 5432, while the workbench should be using 4321

**Comment by paulryan** [comment]
@parikshit-patel I couldn't get it working on http when I was receiving this error. However, having reinstalled the components it now works over https as well as http.
@patmill would reinstalling the generator, the windows build tools, or upgrading yeoman as described have modified my port configurations? (as the issue resolved itself after having done so)

**Comment by JasonDunbar** [comment]
In addition - If you keep Visual Studio Code open while trying to upgrade using npm update, then you might see a few EPERM errors (read: permission denied). 

I can't say that Visual Studio Code caused this (the files mentioned in the errors were not open), but after closing Visual Studio Code and trying again, all went well.

**Comment by patmill** [comment]
@paulryan - we don't currently do anything to existing projects, although new projects will modify the port.  Also - once you get the certs accepted on your localhost, your browser should remember those settings and no longer give issues on the local or the hosted workbench.

**Comment by iclanton** [comment]
Is this still happening? Have you had this issue recently?

**Comment by patmill** [comment]
I believe this is closed now.
