### ISSUE TITLE
Custom Actions not displayed in SharePoint Hosted add-in when deployed from site collection app catalog

### ISSUE THREAD

**Issue by smithderekm** [SharePoint/sp-dev-docs#1482]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We have a SharePoint Hosted Add-in that we have already deployed to the tenant app catalog and installed on multiple sites.  As part of the add in, both an Item Custom Action and Ribbon Custom action are added to document library views to provide an entry point to the add-in for a selected document.

In order to test a new build, we enabled a site collection app catalog (on a test site collection) and deployed the new add-in package to that location.  We removed the tenant app-catalog add-in from that site, then installed the new version from the site collection app catalog.  No errors occurred during installation.

Upon viewing a document library, the Custom Actions are not presented in either the item or ribbon/toolbar.  

I can click on the add-in directly (from Site Contents) and it loads successfully, so that portion is functional as expected.

#### Steps to Reproduce

1. Create SharePoint Hosted Add-in with included Custom Actions.
2. Enable site collection app catalog for a site collection.
3. Package and upload add-in to site collection app catalog.
4. Got to Site Contents.  Click Add an App.  Select add-in and install.
5. When installation is completed, browse to Document library.
6. Select an item.  Confirm that custom action is not displayed in ECB menu.

**Comment by dgaeta** [comment]
@smithderekm this does appear to be a bug. We are working on the issue.
Thanks for the feedback.
