### ISSUE TITLE
isRenderedByWebPart method on propertyPane does not return true the first time it's opened

### ISSUE THREAD

**Issue by devinprejean** [SharePoint/sp-dev-docs#1484]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When you call .open() on the propertyPane object the isRenderedByWebPart() should return true when a user opens it via code such as the .open() method and should return false when the user clicks the edit button of the webpart itself

#### Observed Behavior

The first time .open() is called it returns false. When you run .open() again it returns true. If you close the panel and run .open() again it returns true.

#### Steps to Reproduce

Create new webpart -> add button inside webpart to call this.context.propertyPane.open() -> override getPropertyPaneConfiguration() -> check for this.context.propertyPane.isRenderedByWebpart() -> click button used to call .open()

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by devinprejean** [comment]
Just noticed that if I click inside the webpart to give it focus THEN click the custom button it works correctly.

**Comment by mcmynn83** [comment]
Thanks for your feedback.  We will take a look at this issue.
