### ISSUE TITLE
QuickLaunchOption = QuickLaunchOptions.Off and list.OnQuickLaunch = false; not working

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#1488]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When creating a list using Client Object Model the parameter [QuickLaunchOption = QuickLaunchOptions.Off](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.quicklaunchoptions.aspx) should not add the new list to the "Recent" section of the quicklaunch as mentioned in the documentation:

> "Enumeration whose values specify that the list is not displayed on the Quick Launch of the site. The value = 0."

Furthermore the parameter [list.OnQuickLaunch = false;](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.list.onquicklaunch.aspx) should hide a list from the quicklaunch as mentioned in the documentation:

> Gets or sets a value that specifies whether the list appears on the Quick Launch of the site.

The problem exists in SharePoint Online and **SharePoint 2016**.

#### Observed Behavior
None of these settings hides the list from the quicklaunch in "recent" section.

#### Steps to Reproduce

Create a new console application and add the _Microsoft.SharePoint.Client_ and _Microsoft.SharePoint.Client.Runtime_ dlls.

Add the following code to the console application and start debugging:

```csharp
string siteCollectionUrl = "https://...";
using (var context = new ClientContext(siteCollectionUrl))
{
    var web = context.Web;
    context.Load(web,  l => l.QuickLaunchEnabled);
    context.ExecuteQuery();
    Console.WriteLine($"Quicklaunch enabled:{web.QuickLaunchEnabled}");

    var listCreationInfo = new ListCreationInformation
    {
        Title = "QuicklaunchTestList",
        TemplateType = (int)ListTemplateType.GenericList,
        QuickLaunchOption = QuickLaunchOptions.Off
    };
    var list = context.Web.Lists.Add(listCreationInfo);
    context.ExecuteQuery();
    //List is visible still visible in quicklaunch after this line

    list.OnQuickLaunch = false;
    list.Update();
    context.ExecuteQuery();
    //List is visible still visible in quicklaunch after this line
}
```

**Comment by srideshpande** [comment]
@MrTantum  - Thanks for reporting the issue. When I quickly looked at the code, this behavior seems to be expected. Anything above SP 2013 will keep it open and below that will respect the params which you are passing in.

I am still looking at it and trying to get in touch with the dev who coded it. I will get back to you as and when I receive an update.

Thanks for waiting!

**Comment by MrTantum** [comment]
No answer yet therefore I had to find another solution. The following script will delete the new entry from recent after creation of a list:

https://tantumpoint.wordpress.com/2018/03/20/csom-delete-list-from-quicklaunch-recent-node-after-creation/

```
var listCreationInfo = new ListCreationInformation
{
    Title = "TestList",
    TemplateType = (int)ListTemplateType.GenericList,
    QuickLaunchOption = QuickLaunchOptions.Off
};
list = context.Web.Lists.Add(listCreationInfo);
context.ExecuteQuery();
context.Load(list, l => l.DefaultViewUrl);
context.ExecuteQuery();                
 
//get the node which does not have a url set because the "Recent" node never has an url
var quickLaunchNodeColl = context.Web.Navigation.QuickLaunch.Where(l => l.Url == null || l.Url == string.Empty).Include(l => l.Children.IncludeWithDefaultProperties());
var results = context.LoadQuery(quickLaunchNodeColl);
context.ExecuteQuery(); 
foreach (var result in results)
{
    foreach (var child in result.Children)
    {
        //find the child which has the url of our new list
        if(child.Url.Equals(list.DefaultViewUrl))
        {
            result.DeleteObject();
            context.ExecuteQuery();
        }
    }
}
```
