### ISSUE TITLE
HREF Issue

### ISSUE THREAD

**Issue by Muxstang** [SharePoint/sp-dev-docs#1489]
I was trying to format a hyperlink column with the following JSON.  The goal was for the icon and link to only show if there was a link provided but for some reason i am always getting a Failure: FieldRenderer Error:invalidProtocol.  If I remove the HREF portion it shows the icon correctly.

{
    "$schema": "https://gist.githubusercontent.com/thechriskent/2e09be14a4b491cfae256220cfca6310/raw/eb9f675bf523208eb840c462d4f716fa92ce14c2/columnFormattingSchema.json",
    "debugMode": true,
    "elmType": "a",
    "attributes": {
        "target": "_blank",
        "iconName": {
            "operator": "?",
            "operands": [
                {
                    "operator": "!=",
                    "operands": [
                        "@currentField",
                        ""
                    ]
                },
                "ProjectCollection",
                ""
            ]
        },
        "href": {
            "operator": "?",
            "operands": [
                {
                    "operator": "!=",
                    "operands": [
                        "@currentField",
                        ""
                    ]
                },
                "@currentField",
                ""
            ]
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-clickable-actions)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
A couple of things with your format:

- `@currentField` is case sensitive ("@currentfield" will be treated as a string with that value - not a dynamic value)
- Only `http`, `https`, and `mailto` links are supported. So, if you're link values are using any other protocol they won't render and you'll see an error instead (the error only shows when `"debugMode": true`)

So here's your format with the case sensitivity adjusted and debugMode removed:

```
{
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
  "elmType": "a",
  "attributes": {
    "target": "_blank",
    "iconName": {
      "operator": "?",
      "operands": [
        {
          "operator": "!=",
          "operands": [
            "@currentField",
            ""
          ]
        },
        "ProjectCollection",
        ""
      ]
    },
    "href": {
      "operator": "?",
      "operands": [
        {
          "operator": "!=",
          "operands": [
            "@currentField",
            ""
          ]
        },
        "@currentField",
        ""
      ]
    }
  }
}

**Comment by Govind1boby** [comment]
This JSON script for hyperlink work only with modern UI, and when we navigate to Classic UI it is back to normal text. Anything can be done to fix this or this article applies only to Modern UI. If yes, please keep the note accordingly .
