### ISSUE TITLE
propertyPaneGroupHeader does not allow for long titles

### ISSUE THREAD

**Issue by tobiaswest83** [SharePoint/sp-dev-docs#149]
#### Category

[ ] Question
[ ] Typo
[x] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

Developers should be able to create webpart property group names of any length without formatting issues such as overlapping.
#### Observed Behavior

Typing a long group name (around forty chars or more) causes the text to appear behind the webpart properties

![image](https://cloud.githubusercontent.com/assets/13330650/18232663/89cf0354-72cc-11e6-940b-2a622c96f204.png)
#### Steps to Reproduce

When defining a `groupName` in `propertyPaneSettings`, use a long string, and edit the webpart to observe the issue. There appears to be a fixed `height` and `line-height` for the group name.

**Comment by manishgarg1** [comment]
VSO #245115

**Comment by manishgarg1** [comment]
Please re-activate if this is still and issue.
