### ISSUE TITLE
Mobile/Responsive Support for React Global Navigation SPFx Extension solution?

### ISSUE THREAD

**Issue by ynotlim** [SharePoint/sp-dev-docs#1495]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Observed Behavior

I am working with the [React Global Navigation SPFx Extension](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-application-tenant-global-navbar) in this repo. I've noticed that when on a mobile device or within a very narrow browser, the navigation disappears instead of being collapsed into a mobile-friendly UI.

Same issue reported here.  [https://github.com/SharePoint/sp-dev-fx-extensions/issues/88](https://github.com/SharePoint/sp-dev-fx-extensions/issues/88)

**Comment by patmill** [comment]
So at the moment there is no navigation extension.  The item you reference is an application extension that writes to a placeholder to display navigation elements, but it doesn't really change the notion of navigation from a data model perspective on the page.

Does that make sense?

**Comment by ynotlim** [comment]
I understand how the application extension works.  However , the issue still occurs when in Mobile view for that command bar.  Do you understand the issue ?  Thank you

**Comment by purvishce** [comment]
Any fix?
