### ISSUE TITLE
Details on ACS access

### ISSUE THREAD

**Issue by tomkcook** [SharePoint/sp-dev-docs#1497]
Step 2 of the detailed procedure here helpfully gives detail on how to request authorisation from SharePoint using an HTTP request.  Step 6, however, just assumes that you're using TokenHelper.cs to make the request to ACS.  Could you please add detail on how to request an access token from ACS when you are not using TokenHelper.cs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be50ae2-2435-480a-0c1e-efca679cd00e
* Version Independent ID: d3c81315-c73e-61c8-2287-dc6e6e5eec5c
* Content: [Authorization Code OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Are you asking about the scenario where you are still using an app that has been registered with SharePoint to get it's token to call the SharePoint REST API? The source to `TokenHelper.cs` is readily available... all it does is help you get a token for different scenarios... which scenario are you looking for? You could just look at the source of the method in question to implement it in your project.
