### ISSUE TITLE
ListViewCommandSet not showing anything in SPO

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#1498]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I already opened an issue [over there](https://github.com/SharePoint/sp-dev-fx-extensions/issues/116) but I am not sure how maintained it is, so I am posting here as recommended by the documentation [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension).

When building a **ListViewCommandSet** extension using the latest yeoman generator's default configurations with the following commands :

- gulp bundle --ship
- gulp package-solution --ship

And we deploy the resulting **.sppkg** file to the app catalog, and we install the app on a site, we should see the list command button appear as expected when navigating in a library.

It really is blocking for me right now because I developed a full extension ready to be deployed in production, but I can only make it work in debug...When deploying the .sppkg nothing works. I must do something wrong, I have a hard time believing it's a production bug in SPO as there would be much more issues like mine, but I can't figure out what I am doing wrong.

#### Observed Behavior

Nothing happens, both list command buttons do not appear, the script isn't even loaded in the Network tab of the browser. When debugging the extension using the URL query string and gulp serve, everything works perfectly, the load debug scripts modal appears, I can accept, then list extension is loaded and everything works.

However, when I deploy the official **.sppkg** to the app catalog, everything goes smoothly, I can install the app in my site collection, but once the app is finished installing nothing happens.

#### Steps to Reproduce

- Create a **ListViewCommandSet** using the latest yeoman generator like [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension).
- Leave everything as is
- Deploy the final sppkg to the app catalog (gulp bundle --ship / gulp package-solution --ship)
- Add the app to a modern site collection
- Once the app is installed, go in a library and notice the list buttons that aren't showing

**Comment by spplante** [comment]
Finally found the problem. The main issue was totally my fault : The **elements.xml** was configured the run on list templates **100** and not **101**, causing the extension to appear only on lists and **not** on document libraries.

Now the reason why it took me so long to realize this is because of what looks like a bug in my opinion : The whole time I was debugging the extension while developing it, the extension **was working** on document libraries even though the custom action is configured to run only on lists. The fact that it was running perfectly fine in debug is quite confusing because I automatically excluded the possibility of such a configuration error.

In my opinion the debug mode should reflect the .sppkg behavior, it should take into account the custom action's configuration to avoid confusion.

Closing this issue!

**Comment by patmill** [comment]
Thanks for the feedback @spplante .  I'm not sure if there is anything we can do here, in that the debug string basically says "load this assembly" - ignoring the package entirely.  I don't think we even have any reference to the config.  But we'll keep the confusion in mind and see if we can reduce the chance of this happening for others.
Pat.

**Comment by spplante** [comment]
I could imagine some kind of mechanism that could read the custom action's file before reading the assembly, and based on conditions generated from the custom action config (ie : if currentList.Type == customAction.type) if could load (or not) the assembly. Easier said then done but you get my point 👍
