### ISSUE TITLE
gulp error : Error: Cannot find module '@microsoft/sp-build-web'

### ISSUE THREAD

**Issue by ShlokChakankar** [SharePoint/sp-dev-docs#15]
E:\myfolder>gulp serve
module.js:327
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\shlok\helloworld-webpart\gulpfile.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by ssandu** [comment]
Same here

**Comment by wictorwilen** [comment]
Can you test running the following. Looks like there several similar issues with packages not loading properly.

    npm install

**Comment by SPDoctor** [comment]
There are a few things missing if you don't have python installed correctly - you will probably find error messages if you scroll far enough back but you can easily miss them. Having got to this stage it may be easier to fix the missing dependencies:

npm install --save-dev @microsoft/sp-build-web

Failing that, make sure you have everything mentioned under "Set up your machine", delete the old helloworld-webpart folder and then create a new one and use Yeoman to re-create everything.

**Comment by ShlokChakankar** [comment]
Thanks @SPDoctor. I have installed Python and again tried to run the package using YO. It worked perfectly.

**Comment by mauricionr** [comment]
same here on ubuntu

**Comment by NPrice99** [comment]
Hi

Have you tried the following :- 
    npm -g install npm@next 
    npm install --global --production windows-build-tools 

then try your command again.
Regards

Nigel

**Comment by pvnbharath** [comment]
I have got the same error while running the gulp trust-dev-cert
Run the command 
npm install --save-dev 

Solved the issue. That's @ SPDoctor.

**Comment by prabhu244** [comment]
Running this command solved the issue for me!
npm i

**Comment by DanSantoDomingo** [comment]
I have installed python but still recieving error after running npm i

**Comment by PrasantiKintali** [comment]
Hi,
We will get this error when the module 'sp-build-web' is missing in "node_modules\@microsoft" folder
install sp-build-web module to resolve this issue
command to install : npm install @microsoft/sp-build-web

![SP-Bulid-Web](https://user-images.githubusercontent.com/55188145/64690421-fe285e80-d4ad-11e9-847e-d6b5aa164d45.PNG)

Also for SPFX make sure that your node js version is  >=8.9.4 <9.0.0 || >=10.13.0 <11.0.0
