### ISSUE TITLE
ALM API install provider-host app from tenant app catalog site failed via AAD app-only token

### ISSUE THREAD

**Issue by AveAdam** [SharePoint/sp-dev-docs#1501]
I use AAD App to get SharePoint app-only token, and then install Provider Hosted app from tenant app catalog, the app status always be installing.

This is install error in app monitor detail page:

Version | 2.0.0.1
Installed by | SharePoint App
Installed date | Tuesday, March 20, 2018

Type | Component | Error | Correlation ID
Intermittent(Retry operation) | Common App Deployment | The operation took too long. | 46e0213b-fc62-43ce-a2e6-7216fa8706c1

It is very strange: The app shown in site contents is gray, and cannot be clicked. But on left quick launch of classic experience, I can click it, and redirect to app URL successfully. And the app parts in the app can be shown when inserting app part into page.

![install app error](https://user-images.githubusercontent.com/22903728/37693511-11fe6854-2cb8-11e8-9aff-a802ef411476.png)
![app always be installing](https://user-images.githubusercontent.com/22903728/37693531-46803760-2cb8-11e8-951c-fb603ae16b3b.png)

@VesaJuvonen

**Comment by AveAdam** [comment]
Any update?
Thanks!

**Comment by AveAdam** [comment]
Another issue:
Before I used AppRegNew.aspx to register app, and for new version I use Seller Dashboard to generate a new client id. When I upgrade the app via ALM upgrade API, it looks work, but when I check the AppPrincipalId of the app instance via SharePoint REST API, it doesn't change to new AppPrincipalId with new Client ID.

But it works when I upgrade it in SharePoint page manually. The AppPrincipalId was changed to new id. Now my solution is uninstall and install. But the app parts has been added in site pages will be lost.

Any help?

**Comment by SchauDK** [comment]
I have the same issue.
Also same issue when installing provider hosted app from Site Collection App Catalog.

Eventually you'll get the option to click Retry. If retry is clecked, the app is installed right away.

**Comment by andygjones-nz** [comment]
I am also still having issues using ALM to install a provider hosted app. Using an AAD application identity it fails but the exact same code using a user account contexts works fine. This is all via the tenant app catalog.

No errors are returned from PnP ALM itself, but in the SharePoint UI the app starts installing and seems to get stuck and eventually time out. Error reported in SharePoint is "The operation took too long". Presumably something to do with the apps permission request.

I'm using SharePointPnPCoreOnline v2.25.1804.1

**Comment by AveAdam** [comment]
@VesaJuvonen any update for this issue?
Thanks!

**Comment by jcharikofsky** [comment]
I was wondering if anyone had found a solution to this issue. I have a complex provisioning process that requires several custom apps to be installed on the site collection - completely unattended. It is operating under an AAD application identity. If I monitor the installation status for the add-in it goes from installing --> initializing and then hags. Eventually the UI display a failure message - clicking retry immediately corrects the issue (but requires human interaction which is not a solution).

Is there a way to mimic the retry functions being called in the UI, or has the root issue been corrected?

I am executing SharePointPnPCoreOnline 2.28.1807.

**Comment by AveAdam** [comment]
@jcharikofsky if you have username and password, you can call SharePoint CSOM to set this user as site admin first, and then use ADAL to get SharePoint access token of this user to call ALM API to install APP. 
If you don't have, there is no way right now.

**Comment by advdberg** [comment]
@VesaJuvonen @andrewconnell Any news on this? We (as an ISV) are also running into this issue, with SPFx app it works fine but Provider Hosted apps are failing when not having a user context. Our customers have the 'legacy auth context' disabled so we don't have any other options left than running our provisioning scripts with the app-only token. We don't want to redesign all of our provider hosted apps just because somewhere in a back-end job/process the lack of a user context in the token is throwing an error. 

As discussed above, the app runs totally fine while installing is in progress, it is just rolled back after a long period of time and set to a 'failed' mode which then disables the app.

At least there should be decent documentation around this, while this scenario is still a valid one in our opinion.

**Comment by andrewconnell** [comment]
Looking back at [Vesa's question in the comment](https://github.com/SharePoint/sp-dev-docs/issues/1144#issuecomment-374505350) that triggered you to open this issue, one thing hasn't been answered in this or any of the other referenced issues:

**How did you get app-only token? - appregnew or AAD?**

I'll add, what specific error response do you get back when you use the REST API (not PowerShell / Office 365 CLI)?
