### ISSUE TITLE
Request for the pdf document version for this documentation

### ISSUE THREAD

**Issue by vermavarun** [SharePoint/sp-dev-docs#1502]
Hi,

Requesting the pdf version of this documentation. Same as .Net core https://docs.microsoft.com/en-us/dotnet/opbuildpdf/toc.pdf?branch=live

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e47901-ca43-07be-ff29-a071b1843d61
* Version Independent ID: d5168991-88da-320e-1f1f-e032009a3593
* Content: [SharePoint development](https://docs.microsoft.com/en-us/sharepoint/dev/)
* Content Source: [docs/index.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/index.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by vermavarun** [comment]
That would be very helpful.

**Comment by jkuter** [comment]
It would also be helpful to be able to save or favorite documentation across doc.microsoft.com and have it sort nicely on a sidebar or something.  I am constantly in this system reading and its difficult to keep track, probably one of the reasons for the pdf request.

**Comment by VesaJuvonen** [comment]
Absolutely valid request and happy to share that we have not enabled the "Download PDF" capability for SharePoint Development Documentation. PDF is automatically updated as we make changes to the official documentation.

**Comment by vermavarun** [comment]
Thank you. Now we can download the pdf. Cheers !!
