### ISSUE TITLE
Empty Manifest errors

### ISSUE THREAD

**Issue by moonplanter** [SharePoint/sp-dev-docs#1506]
Run 'gulp bundle --ship' prior to 'gulp package-solution' to prevent these errors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10854d33-70e9-04ce-fd21-bb26eb55d267
* Version Independent ID: 181693b7-2dcb-332c-39e8-9bf74d13a68f
* Content: [Tutorial - Use GraphHttpClient to call Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/call-microsoft-graph-using-graphhttpclient)
* Content Source: [docs/spfx/call-microsoft-graph-using-graphhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/call-microsoft-graph-using-graphhttpclient.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
As this is more a guidance on how to avoid empty manifest errors, closing the issue. Thanks for sharing the comment, which could be helpful for others.
