### ISSUE TITLE
Open external URLs with SPFX Extension listview command set dialog

### ISSUE THREAD

**Issue by kspranesh** [SharePoint/sp-dev-docs#1509]
Question : How to enable  list view commandset to open an external URL when clicked.

Requirement : I have a need to open an external URL and pass list item properties to it as additional parameters. I have a command set extension developed and in the onExecute event i am capturing the item properties which i need to pass as parameter and open a modal dialog to an external URL. I am not finding direct way to call window.Showmodaldialog within the code. Do i have to create a seperate dialog object from BaseDialog and code there to open dialog ?

public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
      const filePath: string = event.selectedRows[0].getValueByName("ServerRedirectedEmbedUrl");
    **{Open showdialog here }**
       // Dialog.alert(`${this.properties.sampleTextOne}`);
        break;

**Comment by mulduni** [comment]
I am wanting to do something similar and open an existing dialog in SharePoint.  Anyone done this before?
