### ISSUE TITLE
gulp nuke deletes Gulpfile

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-docs#151]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
[ ] Question
[ ] Typo
[X ] Mistake
[ ] Additional article idea

#### Expected or Desired Behavior
When I type in gulp nuke it should clean up my web part directory.

#### Observed Behavior
When I type gulp nuke  I get cannot find module gulp-core-build.

C:\XXX\YYY\ZZZ\Documents\SPFx\Projects\SiteInfo-webpart>gulp nuke
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-core-build'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\XXX\YYY\ZZZ\Documents\SPFx\Projects\SiteInfo-webpart\node_modules\@microsoft\sp-build-web\lib\index.js:13:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

#### Steps to Reproduce
follow instructions which end with gulp build

**Comment by waldekmastykarz** [comment]
Hi Nigel, it seems like you're missing one of the dependencies. Could you try running in command line `npm install` to restore dependencies and try running `gulp nuke` after that?

**Comment by NPrice99** [comment]
Hi Waldek

I have run npm install and other than the usual suspect :-

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit..42.1\package\package.json written

Worked OK.

Then ran gulp nuke and got this error :-

[14:12:05] No gulpfile found

This has only started happening after implementing  SharePoint Framework SPFX drop 2 https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Waldek

I ran npm install again after my previous email and got a different error :-

C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart>npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open 'C:\XXX\YYYY\ZZZZ\Documents\SPFx\Projects\SiteInfo-webpart\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart\node_modules\@microsoft\gulp-core-build-karma\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart\node_modules\@microsoft\gulp-core-build-typescript\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart\node_modules\es6-templates\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart\node_modules\html-minifier\package.json'
npm WARN cldrjs@0.4.4 requires a peer of cldr-data@>=25 but none was installed.
npm WARN globalize@1.1.1 requires a peer of cldr-data@>=25 but none was installed.
npm WARN globalize-compiler@0.2.0 requires a peer of cldr-data@>=25 but none was installed.
npm WARN SiteInfo-webpart No description
npm WARN SiteInfo-webpart No repository field.
npm WARN SiteInfo-webpart No README data
npm WARN SiteInfo-webpart No license field.

C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart>dir
Volume in drive C has no label.
Volume Serial Number is 749F-CEC2

Directory of C:\ XXX\YYYY\ZZZZ \Documents\SPFx\Projects\SiteInfo-webpart

05/09/2016  00:42    <DIR>          .
05/09/2016  00:42    <DIR>          ..
05/09/2016  14:22    <DIR>          node_modules
04/09/2016  22:03    <DIR>          src
04/09/2016  22:03    <DIR>          typings
               0 File(s)              0 bytes
               5 Dir(s)  14,684,434,432 bytes free


I would seem that npm nuke has nuked a bit too much !


Regards

Nigel

**Comment by patmill** [comment]
Paging @nickpape-msft @iclanton

**Comment by patmill** [comment]
Chatted with Nick, and looking at the your output, it was that gulp nuke couldn't find gulp-core-build.

Can you double check what version of npm you are running?

**Comment by NPrice99** [comment]
Hi Pat

npm version = 3.10.7

Regards

Nigel

**Comment by iclanton** [comment]
Is this still an issue for you? Has this happened again?

**Comment by NPrice99** [comment]
I have not seen it since I installed drop 3.  That might just be co-incidence

**Comment by iclanton** [comment]
Okay I'm going to close this. Let us know if you see this again.

**Comment by NPrice99** [comment]
OK- will do
