### ISSUE TITLE
More of this type of doc

### ISSUE THREAD

**Issue by jkuter** [SharePoint/sp-dev-docs#1510]
I would love to see more architectural recommendations like this across the codebase.  This particular problem is one that we have been solving for years and its good to hear an official stance on it. Keep up the good work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c250b3d-fba0-02fb-5339-795bc0bfabb6
* Version Independent ID: e65c6e5f-95db-0d6f-ab01-5b3d76dbff6e
* Content: [Proven Practices for SharePoint Online Portals - Navigation Solutions](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation#feedback)
* Content Source: [docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-navigation.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mcmynn83** [comment]
@VesaJuvonen

**Comment by andrewconnell** [comment]
Feedback received... will take note of it. Closing this issue as it doesn't have a specific action to take.
