### ISSUE TITLE
Hello Team, I am facing issue with my SPFx solution package. Whenever I am adding "webApiPermissionRequests" in pacakge-solution.json file, app package is showing error when uploading to app catalog. Error message: "Error in application"

### ISSUE THREAD

**Issue by TNTRIPATHI** [SharePoint/sp-dev-docs#1511]

**Comment by waldekmastykarz** [comment]
Could you please share the contents of your `package-solution.json` file?

**Comment by TNTRIPATHI** [comment]
Hello Waldek,
Please find below the contents of package-solution.json

{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "sp-fx-graph-api-connect-client-side-solution",
    "id": "816dd2c9-e446-4ba1-9d7a-3a8153e76124",
    "version": "1.0.0.0",
    "includeClientSideAssets": true
  },
  "paths": {
    "zippedPackage": "solution/sp-fx-graph-api-connect.sppkg"
  }
}


Thank you...

**Comment by VesaJuvonen** [comment]
@TNTRIPATHI - can you provide the full text of the App Package Error Message from the solution, which is getting this exception. Key here would be to get the correlation ID, so that we can check what actually went wrong. Thanks for providing this advance.

**Comment by waldekmastykarz** [comment]
@TNTRIPATHI also, are you deploying the solution to SharePoint on-prem or on-line?

**Comment by TNTRIPATHI** [comment]
@VesaJuvonen: App Package error message says "Error in application".
@waldekmastykarz : I am deploying  the solution in SharePoint Online.

**Comment by papouuu** [comment]
I had same problem for several days until just now.

If it can help : 
- activated first release tenant (just have to wait arround 30 mins)
- packaged solution using --production

**Comment by waldekmastykarz** [comment]
@papouuu thanks for confirming it's working now

**Comment by VesaJuvonen** [comment]
@TNTRIPATHI - We would need to also get error description. You can potentially also share the sppkg file for us to have a look.

**Comment by bmarcos81** [comment]
@TNTRIPATHI - I am testing the [Consume the Microsoft Graph (tutorial)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial) and i faced this error. The webApiPermissionRequests is a preview functionality and you must [enable this in O365 Admin center](https://support.office.com/en-us/article/set-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47). It can take up to 30 minutes. When it is ready you can see the API management page in Sharepoint Admin Center preview. Upload sppkg now and go back there to approve the requested User.ReadBasic.All permission for Microsoft Graph.

**Comment by VesaJuvonen** [comment]
@bmarcos81 - that means that the "targeted / first release" tenant setting is not enabled in your tenant. Tenant administrator will need to enable this in your tenant admin UIs to enable this capability.

As @TNTRIPATHI did not come back on this after few months, closing for now. If anyone has similar issues, please do open a new issue in the issue list rather than adding new issues as comments. Thanks.

**Comment by pradiptanayak2007** [comment]
I am also getting same issue. I am using "@microsoft/sp-client-preview": "^1.8.0". In My CA Preview feature is enabled. When I deploy the solution I am getting error : Deployment failed.  Correlation ID: 5a99d29e-e0fb-8000-e61d-2ee54a3f2219. Frustrated just want to use the feature to use Graph API.

**Comment by pradiptanayak2007** [comment]
I changed "isDomainIsolated": true to false in package-solution.json and now  I am not getting error when I deploy the solution.
