### ISSUE TITLE
Using SharePoint Framework Extension to modify validation of New Item Form Fields

### ISSUE THREAD

**Issue by Mike-tech** [SharePoint/sp-dev-docs#1512]
#### Category
- [# ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello 

I have a quick question, can we use SharePoint Framework Extension, e.g. the Field Customizer tool, to manipulate validation for adding New item.

So i would like to disable FirstName field validation, see screenshot below, if Department Finance is selected or another specific value from another dropdown within the new item?

I know in classic site we could inject JavaScript in the Edit Form web part. But would like to know if this is feasible within modern. If not is there any alternative to solve this requirement in modern?

Thanks in advance as always.

![newitem](https://user-images.githubusercontent.com/21954124/37760819-b3d19cda-2daf-11e8-8ff7-fe985464c775.png)

**Comment by waldekmastykarz** [comment]
Unfortunately this isn't possible at the moment.

Have you checked if there is already an existing item describing similar functionality on UserVoice at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform which you could upvote? That way we could show the need for such functionality. If there is no existing item, you can create new one.

**Comment by Mike-tech** [comment]
Ok i thought as much. 

Ok, i will look into the UserVoice as this seems like a common need.

Can i be cheeky and sneak another question which is related to Framework Extension - is there any method within SPFx extension to colour a whole role based on field value. I know i can set a field background colour based on a field value, but can i apply the styling to the whole row? ;)

Cheers

**Comment by waldekmastykarz** [comment]
Again, not at the moment, no, and again, very valid requirement. UserVoice it! 🚀 😄

**Comment by Mike-tech** [comment]
As ever thanks @waldekmastykarz

**Comment by waldekmastykarz** [comment]
Pleasure to help!
