### ISSUE TITLE
Error loading debug manifest script

### ISSUE THREAD

**Issue by DavidFatena** [SharePoint/sp-dev-docs#152]
#### Category

[ ] Question
[ ] Typo
[X] Mistake
[ ] Additional article idea

A few days ago when I was trying to load my project using the workbench.aspx in SharePoint Online an alert appeared saying

> Error loading debug manifest script. (Error: http://localhost:4321/temp/manifests.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support. Error loading https://localhost:4321/temp/manifest.js)

Before that everything worked, I was using it daily. My project works fine on localhost, gulp serve throws no errors. I am almost 87% sure that the error has no connection with me updating my code, it just appeared by itself.

![image](https://cloud.githubusercontent.com/assets/21120594/18247178/45f62fa4-7371-11e6-88d4-f71abdf03173.png)

**Comment by Panoone** [comment]
I'm having the same issue in IE, Firefox and Chrome. No manner of browser settings seems to make a difference. Clicking "Show all content" in IE, "Disable protection for now" in Firefox and the Shield icon in Chrome have no effect.

Any fix for this please? I'm about to give up.

Perhaps deploying and referencing manifest.js would be a safer and better alternative??

**Comment by patmill** [comment]
I believe you are running into the issue with gulp serve running https, not http.  Try this:
First - run against your local server, making sure it is running https
Accept the warning about an unsafe certificate on localhost.  Make sure things are working correctly against https://localhost:4321
then hit the sharepoint hosted one.

**Comment by Panoone** [comment]
Hi Pat,

The local server is most definitely running under https and I accepted the
certificate warning.

Anything else I should try?

Regards,

Paul

**Comment by michaelvperry** [comment]
as per https://github.com/SharePoint/sp-dev-docs/issues/165 installing the certificate as well as accepting the warning seems to fix it. In my case I installed the cert after running the local version in IE and selecting it in the address bar. After that I ran it in Firefox. It complained about a mismatched name but adding it as an exception got it working.

**Comment by iclanton** [comment]
@Panoone - Make sure you accept the cert for both `https://localhost:4321/...` (i.e. - `https://localhost:4321/temp/manifests.js`) and for `https://<your-machine-name>:4321/...` (i.e. - `https://<your-machine-name>:4321/temp/manifests.js`).

@michaelvperry - Be careful installing that cert. It's distributed by `gulp-connect`, so if you have it installed on your machine and someone malicious is using the `gulp-connect` cert on their server, it'll look like a valid cert to your machine.

**Comment by Panoone** [comment]
@iclanton - Thank you, thank you, thank you! After loading both https://<machine-name>:4321/temp/workbench.html and https://localhost:4321/temp/workbench.html and accepting the risk, I can now load the workbench in Chrome.

I followed the same process in IE and am much closer to success. However, when adding the web part to the workbench, I'm now seeing "Unable to load web part script resources due to: Error." and it fails to load.

![image](https://cloud.githubusercontent.com/assets/9169734/18333932/b15f7ede-75b6-11e6-8f6d-70d2ba782fc5.png)

**Comment by iclanton** [comment]
After navigating away and back again, does it consistently work (i.e. - can you refresh the page and load your web part without having to do the navigate-away-and-back dance again)?

This is something we're going to improve in the next drop, so issues you're having now will hopefully be temporary.

**Comment by Panoone** [comment]
Yes it does. It's quite bizarre. Looking forward to the updates. This is
the platform we've all been dreaming of! 🙌🏼

Btw, is there any way to reference the CSS file containing all the ms-
classes so as to get intelligence when developing?

**Comment by patmill** [comment]
Other than an issue with Edge, these should be resolved.
