### ISSUE TITLE
News Webpart and number of lookup fields in Pages Library

### ISSUE THREAD

**Issue by jashwanthreddyn** [SharePoint/sp-dev-docs#1521]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

Can you please confirm if we have any limit on the number of lookup fields for 'Pages' library? Currently, we have 14 lookup fields and OOTB News WebPart isn't rolling up any content from pages library. Interestingly, if we bring down lookup fields count to <12, News WebPart works. 

With >12 lookup fields in pages library below the resultset 

![image](https://user-images.githubusercontent.com/33126513/37783007-bd617d4a-2dca-11e8-922a-d051b1907a34.png)

(Please correct me if I'm wrong, "_api/sitepages/pages/feed?promotedstate=2&published=true&$expand=CreatedBy,FirstPublishedRelativeTime" is live query for News Webpart ?)

Thanks!

**Comment by VesaJuvonen** [comment]
SharePoint Online has same list view lookup threshold as SP2016. 12 lookup limitation has been covered in the software boundaries documentation at https://technet.microsoft.com/en-us/library/mt493258%28v=office.16%29.aspx?f=255&MSPPError=-2147217396

*Specifies the maximum number of joins allowed per query, such as those based on lookup, person/group, or workflow status columns. If the query uses more than eight joins, the operation is blocked. This does not apply to single item operations. When using the maximal view via the object model (by not specifying any view fields), SharePoint will return up to the first 12 lookups.*
