### ISSUE TITLE
Filename column in Document Libraries has Format this column option, but is not supported and doesn't return @currentField

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#1524]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

According to the [documentation for Column Formatting](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#supported-column-types), the Filename (in Document Libraries) column is not supported.

However, the _Format this column_ option exists in the UI:

![image](https://user-images.githubusercontent.com/8364109/37808253-d286cfae-2e1f-11e8-946c-d38f2afc84f1.png)

And according to [this issue on the sp-dev-column-formatting repo](https://github.com/SharePoint/sp-dev-column-formatting/issues/28) it actually worked for some time.

The expectation is that it would either move to supported and work, or the option in the UI would not be available.

#### Observed Behavior

_Format this column_ option is available despite not supporting the `Name` column type. This results in nothing being evaluated for `@currentField`.

However, **you can totally get the value of the filename** by using a format like this:

```JSON
{
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
  "elmType": "div",
  "txtContent": {
    "operator": "+",
    "operands": [
      "[$FileName]",
      ".",
      "[$File_x0020_Type]"
    ]
  },
  "style": {
    "color": "orange"
  }
}
```

This looks like this:

![image](https://user-images.githubusercontent.com/8364109/37808827-df89d98c-2e22-11e8-9e2b-5d4ce34b984d.png)

#### Steps to Reproduce

Go to a modern document library and choose _Column settings_ > _Format this column_ for the Name column using the `@currentField` keyword and get no results.

**Comment by Wimki** [comment]
doesno't work in SharePoint Online …
format text is removed from column settings (cleared)

**Comment by aquanikus** [comment]
Hello,

Default column name for files in sharepoint online document library is "LinkFilename".
You can try to use it to get filename.

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
