### ISSUE TITLE
To stop a Yo error.....

### ISSUE THREAD

**Issue by pwyman** [SharePoint/sp-dev-docs#1525]
Between steps 2 and 3 I have to run npm "install @microsoft/generator-sharepoint" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
You will need to absolutely have indeed SharePoint Framework Yeoman generator installed. Set up your development environment article is a pre-requirement for this article as noted at the start of the page.
