### ISSUE TITLE
Is it possible to render Office UI fabric components into a no framework web part?

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/sp-dev-docs#1527]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have a question regarding "Use Office UI Fabric React components in your SharePoint client-side web part". Is there a way to use fabric UI components into a web part with no framework?

For example, I am trying to render a simple DatePicker as follows:

`
private myDate: Date | undefined;

public render(): void {

let datePicker: DatePicker = new DatePicker({
      placeholder: "Select date...",
      firstDayOfWeek: DayOfWeek.Monday,
      onSelectDate: (date: Date) => {
        self.myDate = date;
      },
      highlightCurrentMonth: true,
      isMonthPickerVisible: false,
      showGoToToday: true
    });
 self.domElement.innerHTML = "<div>${datePicker.render()}</div>"
}
`

When I debug the web part in the workbench, I get an error that the firstDayOfWeek was undefined - when debugging with dev tools, I see that the properties in the render method of the DatePicker.tsx are undefined

**Comment by VesaJuvonen** [comment]
Office UI Fabric React components only work with React, so they are not designed to work without any JavaScript framework or with other frameworks.
