### ISSUE TITLE
Yarn install React webpart for SP2016 Onprem fails

### ISSUE THREAD

**Issue by anro95** [SharePoint/sp-dev-docs#1528]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Install and run a React webpart for 'SharePoint 2016 onwards, including SharePoint Online' with Yarn v1.5.1 using Yeoman v2.0.1 with  generator @ microsoft/sharepoint v1.4.1 on windows .

#### Observed Behavior

After yarn install; webpart fails to run with gulp serve.

#### Steps to Reproduce

yo @ microsoft/sharepoint --skip-install
Select baseline package: SharePoint 2016 onwards, including SharePoint Online
Select framework: React
After scaffold is complete: yarn install
After install is complete: gulp serve
Build fails with errors, see attached file...

Attached file:
[Yarn Spfx React onprem issue.txt](https://github.com/SharePoint/sp-dev-docs/files/1840865/Yarn.Spfx.React.onprem.issue.txt)

**Comment by patmill** [comment]
Does the same issue repro if you use npm 4?

**Comment by anro95** [comment]
It works when using npm.

And by the way, when using Yarn:
Creating a Online/latest webpart using React works.
Creating a SharePoint 2016 onwards, including SharePoint Online webpart using No JS framework works.
Creating a SharePoint 2016 onwards, including SharePoint Online webpart using Knockout works.
Creating a SharePoint 2016 onwards, including SharePoint Online webpart using **React fails!**

**Comment by VesaJuvonen** [comment]
Technically we do not support Yarn usage and have not verified that process completely. There could be ways to get this work as it's being used by some community members, but we can't provide direct support on solving this issue.
