### ISSUE TITLE
Incorrect instruction to create custom style sheet for SharePoint

### ISSUE THREAD

**Issue by spSlaine** [SharePoint/sp-dev-docs#1529]
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-css-to-brand-pages#to-create-a-custom-style-sheet-for-sharepoint

Point 2 is not correct

2. Open **contosov15.css** and modify the CssRegistration line to point to contosov15.css from corev15.css, as shown in the following example.

corev15.css (and contosov15.css) does not contain CssRegistration elements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ceeb1-2e10-826b-4ca6-f1c335470e27
* Version Independent ID: 3110ac67-34ff-a07e-3973-ad9470f914dc
* Content: [Use CSS to brand SharePoint pages](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-css-to-brand-pages#to-create-a-custom-style-sheet-for-sharepoint)
* Content Source: [docs/solution-guidance/Use-CSS-to-brand-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Use-CSS-to-brand-pages.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sleenhardt** [comment]
right this is inside the master page and not in CSS file... That should be corrected to : Open oslo.master and modifiy....

**Comment by davidcfk** [comment]
I can't believe nobody has modified the document after 8 months...

**Comment by andrewconnell** [comment]
The doc was updated April 24, 2018 here: https://github.com/SharePoint/sp-dev-docs/commit/cece342577983c6514f1ba8c29075c547f7d4996#diff-6c624491e6e0e7a39c9b614a53ae9fa4

... this issue was just never closed... so closing now...
