### ISSUE TITLE
Page header not in sync with the page title metadata

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1531]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When updating a title of a page from the library itself or REST API, it doesn't update the title on the page.

This is what the page header web part renders:

<img width="709" alt="screenshot 2018-03-23 14 02 51" src="https://user-images.githubusercontent.com/2900833/37830593-e7a3b374-2ea2-11e8-8fbb-422968eca2f6.png">

This is what the actual page title is:

<img width="243" alt="screenshot 2018-03-23 14 06 50" src="https://user-images.githubusercontent.com/2900833/37830754-75c6c786-2ea3-11e8-951c-47e2040398cd.png">

#### Observed Behavior

When creating a page, putting in all content, saving it. All is good. Once the page gets updated from the site pages library itself, the title change does not flows through the header web part its contents. 

<img width="1219" alt="screenshot 2018-03-23 14 21 16" src="https://user-images.githubusercontent.com/2900833/37831425-bc6ec222-2ea5-11e8-8888-29065b8f173f.png">

When editing the page again, it overrides the title. It might be useful to keep these titles in sync, this could make migrations or automatic translations work better.

#### Steps to Reproduce

- Create a page
- Add a title and save the page (ex: "title a")
- Go to the site pages library, update the title of the page to "title b"
- Open the page and you will see "title a"
- Edit the page and save it without any other change
- Check the title of the page in the library, this is reset to "title a"

**Comment by patmill** [comment]
Going way way way back in time :)  The expected behavior here is that promo/demo will kick in and update specific page tags, but it does not operate on anything in a general content field.  I believe that is what you are seeing here.

(Sorry for the super long delay.  Working on making that better)
