### ISSUE TITLE
ISO SPFx API for interrogating SPFx components on the page?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#1534]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there an API (it’s fine if it isn’t documented / supported / internal) for interrogating SPFx client-side to see what SPFx components are on the page?
 
For instance, say I want to create a web part that simply lists all extensions & web parts that are on the page.

**Comment by patmill** [comment]
Hey Andrew, I believe this should work for you (and is all public as well)  Excuse the hasty coding

import { SPComponentLoader } from "@microsoft/sp-loader";
import { IClientSideComponentManifest } from '@microsoft/sp-module-interfaces';

...

    var manifests:IClientSideComponentManifest[] = SPComponentLoader.getManifests()

From there, you'll want to look at manifests that have isInternal not set to true.  That should be the full set of 3rd party components.  Additionally, you can look at the componentType property to determine if it is a WebPart or an Extension.

Let me know if that works for you,

**Comment by andrewconnell** [comment]
Thanks @patmill ... I'll start digging & follow up...

**Comment by andrewconnell** [comment]
That is exactly what I was looking for... thanks @patmill !
