### ISSUE TITLE
Kendo UI React.js version 16.2 with Sharepoint framework

### ISSUE THREAD

**Issue by JishaRajesh** [SharePoint/sp-dev-docs#1535]
#### Expected or Desired Behavior

CX wants to know how to use the latest version of react.js 16.2 with their SPfx web part.
#### Observed Behavior
When using the react.js 15.6.2  by default available with Sharpoint framework, cx is unable to use the latest features of kendo. So he would like to upgrade to 16.2. But he is unable to do it.

. If he does not use the latest version of react.js, he gets an error in gulp ,which says cannot find module “ @microsoft/sp-loader”. 

When using the newest version ,there is a 404 (f12 ) which says “ failed to load URL ‘/node_module/react/dist/react.js’” file not found SPloader error, as the folder structure mapped is different .

#### Steps to Reproduce
When generate SharePoint online web parts using yo @microsoft/sharepoint command and select React framework, similar to steps listed in this link on how to use office UI react components. After generating the web part the default package.json dependencies related to react are react 15.6.2, react-Dom 15.6.2, @types/react 15.6.6 and @types/react-Dom 15.5.6. 

To change react dependencies we run npm install –save react@latest and nmp install –save react-Dom@latest, finally after updating to latest react we see the error File not found SPloader error. 

#### Submission Guidelines

Please let us know the appropriate way to upgrade the version and use the spfx. we had suggested using https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library 
cx replied
We didn’t try the second solution you have suggested yet, which details on using external libraries. In the article it suggests how to load scrips using CDN. This could be one solution, but not ideal at all since we have to keep two versions of react, one through node_modules installed when generating SharePoint web parts and the other through CDN to latest react framework in config.js file. If this is the only solution available we will try to use it.
Any examples, or links to resources would help a lot.

**Comment by VesaJuvonen** [comment]
Right now we are not supporting so new version. Unfortunately, you will need to wait until SPFx is using the matching version of react before this works.

**Comment by JishaRajesh** [comment]
Hello Vesa,

Thank you for the response. So do you mean to say that this is not achievable. Cx cannot use React 16.2 version with SPfx.
Please confirm

Regards,
Jisha

**Comment by VesaJuvonen** [comment]
This is not currently doable in SharePoint Online until the natively used React is updated to a newer version.

**Comment by JishaRajesh** [comment]
Thank you Vesa, Are there any plans to upgrade or any expected timeline that we can share with customer.
