### ISSUE TITLE
ERROR: SPO permissions failing to validate Full Control since SPO version became vti_buildversion:SR|16.0.7507.1203

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#1539]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Site owner can no longer check permissions of other owners in SharePoint. This is a breaking change introduced within the past week or so.

This used to function correctly. Checking a user for Full Control used to return true. Approx 16th March 2018 a REST call returning 'true' began to return 'false' with no code changes in the orginal logic calling those endpoint calls. 

For the following the REST calls were performed within a 'Publishing' site in SharePoint Online. No modifications to the OOTB site Groups or Permission Levels were made.

Scenario:
Checking a user is a 'Full Control' user via REST.

#### Observed Behaviour

Finding the role definition 'Full Control' which is bound to the Owners Group for the site gives a High and Low value. The user who is listed in the Owners group fails the DoesUserHavePermissions check as their effective permissions return a lower High value than full control. Performing the check via the OOTB UX says the user has 'Full Control'.

No exceptions are returned, the endpoint now returns 'false' instead of the expected 'true'

#### Steps to Reproduce

- Confirm the tenant is the vti_buildversion:SR|16.0.7507.1203 version by calling /_vti_pvt/buildversion.cnf url within the SPO site

- Place a user in the Owner Group assuming the Owner Group is unchanged and is using the OOTB Full Control permissions (again unchanged)

- Check the current user permission high and low through effectivepermissions: https://<tenant>.sharepoint.com/sites/depta/_api/web/EffectiveBasePermissions 

- Get the ‘Full Control’ role from the site:
https://<tenant>.sharepoint.com/sites/<site>/_api/Web/RoleDefinitions 

- Check that the user has permissions using the High and Low values from the RoleDefinitions call result: https://<tenant>.sharepoint.com/sites/<site>/_api/web/doesuserhavepermissions(@v)?@v={%27High%27:%272147483647%27,%20%27Low%27:%274294967295%27}

**Comment by mcmynn83** [comment]
Can you include a correlation ID for the failed request and send the server name as well?  You will be able to find this in the http response headers under sprequestid.  Thanks!

**Comment by weshackett** [comment]
This doesn't return an exception or error. The REST call returns 'false' instead of what it should return 'true' it's the actual value SPo is sending back that is inaccurate. A user in the Owners Group should get a 'true' response when checking the permission level High and Low using the Full Control High and Low

**Comment by mcmynn83** [comment]
@weshackett  - sorry, could you still send me the correlation ID for the successful request (that returns false).  I want to take a look at what permissions are actually used.

**Comment by weshackett** [comment]
@mcmynn83 we have a support ticket number: [REG:118032017846010] SPO: incorrectly returning permission for the Intranet raised which an engineer has been also looking at. More details can be found in the ticket chain.

**Comment by VesaJuvonen** [comment]
Hi @weshackett - any change to actually get the correlation ID also in here so that we can get things moving on our side. Thx.

**Comment by weshackett** [comment]
Tricky as it's not a tenant i have direct access too. Premier support have replicated and a whole bunch of info. Who can i send the email too?

**Comment by VesaJuvonen** [comment]
Send it to me... yes - I know... :-)

**Comment by VesaJuvonen** [comment]
Issue resolved through Premier support. This is a known behavior currently in the API layer.
