### ISSUE TITLE
Server errors when running in Vagrant

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-docs#154]
I usually use [Vagrant](https://www.vagrantup.com/) to isolate my development environments from the rest of my machine. I'm going through the docs and got everything installed but when I run Gulp Server I get this: 

> [21:02:21] Error - Unknown 
>  listen EADDRINUSE :::5432

![screenshot from 2016-09-05 21 05 21](https://cloud.githubusercontent.com/assets/5871660/18258941/90db22aa-73ac-11e6-8243-b157f17864c9.png)

**Comment by waldekmastykarz** [comment]
Could it be that there is another process running on port 5432 or that it's somehow locked?

**Comment by simkessy** [comment]
You're right. I had tried yesterday to find what was running on that port but nothing came up but then I tried this command: `sudo netstat -peant | grep ":5432"` turns out my PostgresSQL server is running on that port.

I went into the `config folder` > `server.json` and changed the `api port` number there

**Comment by simkessy** [comment]
The server runs now in vagrant but I can't seem to access it on my localhost. I probably have to play around with vagrant though to setup up port forwarding properly.

**Comment by simkessy** [comment]
For anyone trying to run this in vagrant which I highly recommend:

in your vagrant file make sure that you're forwarding the ports that SharePoint is using in the Server.json file. 

```
config.vm.network :forwarded_port, guest: 4321, host: 4321
config.vm.network :forwarded_port, guest: 5433, host: 5433 <- Changed from 5432 to prevent issues with PostgresSQL using that port
```

Otherwise everything seems to be running well.
