### ISSUE TITLE
How to navigate to a page in SPFx component?

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1547]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

What is the recommended way of implementing navigation to modern pages in SPFx components? Regular `location.href` causes a full page reload which isn't consistent with the 1st party experience.

**Comment by VesaJuvonen** [comment]
Thanks for the feedback around this. There's no 3rd party API currently for this, but we are working on getting that available. Work is in progress, but can't provide an ETA at this point.

**Comment by waldekmastykarz** [comment]
For what it's worth, if your component outputs regular `<a href="">`, these links will be automatically augmented by SharePoint for partial loading of the target page. It's just programmatically redirecting to a different page that's currently not possible.

**Comment by nero120** [comment]
@waldekmastykarz this is exactly how I implemented page redirection, but recently have been experiencing issues with SPFX web parts on the target page being initialised multiple times after the partial redirection. Watch out for this.

**Comment by nero120** [comment]
> There's no 3rd party API currently for this, but we are working on getting that available.

@VesaJuvonen is there any update on this? Just been testing one of our custom SPFX web parts as a single part app page in v1.7.0 and discovered that our method of redirection does not work on the SingleWebPartAppPage layout - the page content is blank and does not load. The method we use to redirect in SPFX is:

```
  public static redirect(url: string, newTab?: boolean) {
    // Create a hyperlink element to redirect so that SharePoint uses modern redirection
    const link = document.createElement('a');
    link.href = url;
    link.className = globalStyles.hidden;
    link.target = newTab ? '_blank' : '';
    document.body.appendChild(link);
    link.click();
  }
```
