### ISSUE TITLE
Extension parameters

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1548]
Hey,
How to pass parameters(values for top and bottom frames) when an extension deployed in Office 365 CDN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d2c1cca-c6ef-9eb5-fcbb-78c7481b359e
* Version Independent ID: 66783ae9-b10e-5dc7-8a79-4d252ea8a9a7
* Content: [Host extension from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn)
* Content Source: [docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by peterremote1980** [comment]
How to made cdnBasePath dynamic? So i don't need to perform compilation for each customer with their own tenant ? thanks

**Comment by CollaborationJit** [comment]
You would need to host a CDN outside of Microsoft so that users would not need to authenticate to access it.

I would suggest against this though because it may be more of a headache for you but your clients are going to want to "own" any code you deploy to them. Otherwise, what is stopping you from discontinuing hosting the application and then they are left without the product

**Comment by waldekmastykarz** [comment]
@peterremote1980 When you create a new project using SharePoint Framework generator v1.4.x, by default it includes assets in the solution package (.sppkg). This is denoted by the `includeClientSideAssets: true` property in the `config/package-solution.json` file in your project.

When you deploy the project to SharePoint, it will automatically extract the assets from the package and deploy them to a designated document library. If the Office 365 Public CDN is enabled in your tenant, SharePoint will also automatically retrieve files from the CDN. All this is automated and allows you to deploy the same solution to different tenants without having to rebuild it.

**Comment by waldekmastykarz** [comment]
@aslanovsergey parameters are specified in the feature that enables the extension on the site collection where you install the solution. 

Following is a sample `elements.xml` file created for an extension:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="HelloWorld"
        Location="ClientSideExtension.ApplicationCustomizer"
        ClientSideComponentId="c0926bea-9179-4a90-a0e2-f8412eadfd9a"
        ClientSideComponentProperties="{&quot;testMessage&quot;:&quot;Test message&quot;}">
    </CustomAction>
</Elements>
```

The `ClientSideComponentProperties` attribute contains a JSON string with properties that will be passed on runtime to the extension.
