### ISSUE TITLE
Custom web part icon from file does not load

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#155]
#### Category

[x ] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea

> "iconImageUrl": "//contoso.sharepoint.com/SiteAssets/fonts/my-icon.png"

but it's still rendered as an undefined _officeFabricIconFontName_
`<span class="CanvasToolboxItem-icon ms-Icon ms-Icon--undefined" data-reactid=".1.2.0.$Non Featured.1.$88061aad-a304-4303-b1bf-c8f1ab227fae.0"></span>`

**Comment by manishgarg1** [comment]
VSO #245415

**Comment by manishgarg1** [comment]
Hi @wobba, this has been recently fixed. The fix should roll out to production soon.

**Comment by wobba** [comment]
Awesome, I was about to test it with my old part actually :)

**Comment by manishgarg1** [comment]
Hi @wobba, the fix for this was rolled out last month. I have good feeling that this is fixed. Please re-activate if it is not.
