### ISSUE TITLE
Please include the fully qualified assembly names in code samples.

### ISSUE THREAD

**Issue by satls** [SharePoint/sp-dev-docs#1550]
From the code sample it is difficult to use it in an application without knowing what namespace to include.

a using Microsoft.SharePoint.Client.Taxonomy; at the top of the code sample would be very helpful and would stop me having to google what library you are using and how to nuget it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d6f4e1-7169-4eff-a1dc-cb5a5f5a43bb
* Version Independent ID: d7ac04dc-19cc-63ef-521e-b70ffe8a5fca
* Content: [Taxonomy operations sample app for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/taxonomy-operations-sample-app-for-sharepoint)
* Content Source: [docs/solution-guidance/Taxonomy-operations-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Taxonomy-operations-sample-app-for-SharePoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Fair point... will keep this in mind in future docs. For this specific doc, a sample is provided with the working code sample with the fully qualified references to help.

Thanks!
