### ISSUE TITLE
Update to the last version of SPFx

### ISSUE THREAD

**Issue by esjimenezp** [SharePoint/sp-dev-docs#1551]
Please update this tutorial to the last version of SPFx 1.4.1 because when try to build this solution I found errors, for example, the document IGalleryWebPartProps.ts in the last version of SPFx is not included and only it shows in the GalleryWebPart.ts in export interface IGalleryWebPartProps, if you have any doubt please let me know, best regards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3043faa1-f278-c483-17f4-e1af81d9b097
* Version Independent ID: df4b13b3-4c12-0592-7f29-f54075807c3b
* Content: [Simplify adding web parts with preconfigured entries](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#main)
* Content Source: [docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Javapower77** [comment]
It is not necessary to have the IGalleryWebPart.ts, just include the props in the GalleryWebPart.ts and in IGalleryProps.ts.

The correct content for ./components/IGalleryProps.ts is:

export interface  IGalleryProps {
  listName: string;
  order: string;
  numberOfItems: number;
  style: string;
}

Also include those lines inside GalleryWebPart.ts just after 

import { IGalleryProps } from './components/IGalleryProps';

Another modification to make is in the file ./components/Gallery.tsx

export default class Gallery extends React.Component<IGalleryProps, {}> {

In the original documentation the second parameters is void, just replace with {}.

With this few updates you can deploy using SPFX 1.51.

Cheers!
Javier.

**Comment by timmoon7** [comment]
Thanks Javier! It works now.

**Comment by VesaJuvonen** [comment]
as the issue seems to be solved, closing this one. Thx @Javapower77 for the assistance, appreciated.
