### ISSUE TITLE
Multiple Application Customizer extensions on a site stack randomly

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/sp-dev-docs#1553]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When you have multiple SPFx Application Customizer extensions within a site, it would be great to be able to assign a position to each of them, in order to have a fixed stack ordinal position in the UI. It would be really useful for example to consider the Sequence property of the UserCustomAction element used to provision the extension.

#### Observed Behavior
When you have multiple SPFx Application Customizer extensions within a site, they stack randomly in the UI and their position can change, providing a misleading UX to the end users. The same happens for headers and footers.

#### Steps to Reproduce
Create two or more headers with SPFx Application Customizers. Register them in a site and refresh the home page multiple times or browse through the pages. You will see the headers will randomly move/change their position in the stack.

Thanks.

**Comment by VesaJuvonen** [comment]
Support for Sequence property in the UserCustomAction has been confirmed and it's working as expected. This most likely was a test failure or provisioning failure as we have explicitly added support for this. Closing this issue as feature works as planned.

**Comment by kpathan** [comment]
> Sequence

Is it for UserCustomAction or CustomAction? I tried to add sequence to CustomAction in elements.xml it does not reflect.
