### ISSUE TITLE
Unable to handle action addContentType. No action handler was registered for this action.

### ISSUE THREAD

**Issue by expiscornovus** [SharePoint/sp-dev-docs#1554]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect when I use the addContentType verb in a json schema I can add it to a site script.

#### Observed Behavior

When using the Add-SPOSiteScript or Add-PnPSiteScript cmdlets I am getting the "Unable to handle action addContentType" error. I am using SharePointPnPPowerShellOnline version 2.24.1803.0 and  Microsoft.Online.SharePoint.PowerShell version 16.0.7414.0 on a Targeted Release tenant.

#### Steps to Reproduce
1. Create a script for the addContentType action
```powershell
PS C:\> $script = @'
>> {
>>     "$schema": "schema.json",
>>         "actions": [
>> {
>>    "verb": "addContentType",
>>    "name": "MyFirstContentType"
>> }
>>         ],
>>         "bindata": { },
>>         "version": 1
>> };
>> '@
```
2. Add the json action to a site script via SPO PowerShell
```powershell
PS C:\> Add-SPOSiteScript -Title "Add Content Type Site Script" -Description 
"Content Type Script" -Content $script
```
The result of this script is the following error:
_Unable to handle action addContentType. No action handler was registered for this action._

![unabletohandleaction](https://user-images.githubusercontent.com/22542376/38041216-7b6ebbaa-32b1-11e8-9c52-2e801a61c450.png)

**Comment by expiscornovus** [comment]
It looks like this is a case of RTFM ;)

When using existing content types and using it as subaction in a list it works.

**Comment by seansquires** [comment]
That's correct - but we have some updates on content types that we'll share next week. Thanks!

**Comment by umaknow-alain** [comment]
Is the issue as been fixed ? I have the same error with the remove content type verb. 
Add-SPOSiteScript : Unable to handle action removeContentType. No action handler was registered for this action.
At line:1 char:51
+ ... teScriptFile -Raw | Add-SPOSiteScript -Title $siteScriptTitle) | Sele ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-SPOSiteScript], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.AddSPOSiteScript

Please let me know, Thanks.
