### ISSUE TITLE
MSDN Docs Missing from docs.microsoft.com

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-docs#1555]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It's my understanding that all MSDN technical documentation is supposed to have moved to docs.microsoft.com by now. I continue to find docs which are still on MSDN. Should they be moved here for community edits and feedback?

A few examples:
* [List.RenderListDataAsStream method](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.list.renderlistdataasstream.aspx) - This method has been [suggested as a replacement for the Lists endpoint](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/9065329-enable-support-for-lookup-columns-in-other-webs-in) in order to retrieve lookups in other Webs as well as Managed Metadata. The docs are very slim, at best, and they aren't in docs.microsoft.com.
* [Tenant members](https://msdn.microsoft.com/en-us/library/microsoft.online.sharepoint.tenantadministration.tenant_members.aspx)

Both of these docs (and their children and siblings need work. If they were in docs.microsoft.com, we might be able to help.

**Comment by tomresing** [comment]
Both of these example look like current APIs that are not covered fully on docs.microsoft.com to me. And, your desire to help improve the documentation is welcome. Thanks! 
In case you're looking for more reference on the first topic, RenderListDataAsStream does have some documentation at https://docs.microsoft.com/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest

**Comment by sympmarc** [comment]
The [doc you reference above](https://docs.microsoft.com/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest) which mentions RenderListDataAsStream, @tomresing, was my primary impetus for posting this issue. While that article does indeed exist and we can suggest improvements, the endpoint isn't documented in a useful way anywhere that I can find, so it's virtually impossible to figure out how the endpoint works in order to suggest improvements! That's how I landed on the [List.RenderListDataAsStream method](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.list.renderlistdataasstream.aspx) - trying to find clarity.

**Comment by tomresing** [comment]
I can see @VesaJuvonen is tracking this now. I take that to mean this is an acknowledged issue by the repository owners.

Just to be clear on my comment, I do want to acknowledge that the MSDN article List.RenderListDataAsStream is incomplete. I don't want to suggest that should not be addressed.
In the mean time, if you are looking for information about [how to retrieve items as a stream from REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream) please reference [this article on docs.microsoft.com](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream). There are 5 examples and a table defining the SPRenderListDataOptions which should help to understand that REST endpoint.

**Comment by sympmarc** [comment]
@tomresing, the examples in the article aren’t very real world.
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream

I’ve been using the endpoint in a couple of places now, so I have a better understanding of it – but only in using ViewXml, which is basically the same CAML I know from the SOAP days. AFAIK, NONE of the other  parameters are documented ANYWHERE. Some, one might be able to guess at, like PageFirstRow (probably a number representing the first row one wants?). Others, like FilterOp vs. FilterOp1-10 don’t seem to do anything which would be logical; maybe I’m just an idiot.

Yes, Vesa seems to be tracking this one, and I’m hoping the doc improves. It seems as though you (Microsoft) are telling us (the devs) that this endpoint is the answer to many of our issues. If that is the case, then we need better info. Since “first parties” are supposedly using it, I’d love to hear how!

I could probably add a new example or two, but haven’t gotten to it yet.
