### ISSUE TITLE
MSGraphClient - IE and EDGE issue

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1556]
It doesn't work from IE and Edge Browsers. Graph Client request is stuck and leave Authentication window open. I tried turn off Pop-Up Blocker and added site to trusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consuming APIs secured with Azure AD within the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Nasicus** [comment]
Same problem.

It works in other browser but not in their own browsers... a little sad tbh.
Is there any expected date / estimation when this will be addressed and fixed?

**Comment by Nasicus** [comment]
@VesaJuvonen is there any news / updates on this? We really need this, because our new solution depends on this new authentication, but if the IE issues are not resolved, we are force to go back and use the deprecated clients again.
Is there a roadmap and/or release ETA anywhere concerning this issues?
I also read in the linked issue that you plan (or already did) to get rid of the popups? Because it's highly user unfriendly and even practically unusable un mobile.

**Comment by vbartari** [comment]
Hi All,

MSGraphClient still not working in edge and IE.
Still working fine in chrome.
Is this issue resolved ?
And Do I need to add any specific code to run MSGraphClient in IE?

Please Update if for this issue.

**Comment by SanderSiep** [comment]
Hi @vbartari, you first need to set your tenant in first release mode or nowedays named Targeted mode.
When you do that you will have the WebApiPermissions list available and your package will be uploaded correctly.
More information how to set this mode and what are the consequences can be found here: https://support.office.com/en-us/article/set-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47

**Comment by SanderSiep** [comment]
Hi @vbartari, in Edge the Graph popup shows me an inlog dialog while in Chome this is just going automatically.
In IE it seems to work correctly.

**Comment by kannansgit** [comment]
Any updates on this?

**Comment by kannansgit** [comment]
Hi, it works for all browsers except IE 11 for us. We are using SPFx 1.6.

**Comment by enail131** [comment]
In order for me to fix this I had to add login.microsoftonline.com to the trusted sites list within the Internet Explorer options.

The MSGraphClient has an error parameter. Log or alert the error to get a better idea of what your specific error is.

**Comment by kannansgit** [comment]
Hi, we have added to Trusted sites security zone. Below is the error message we are getting.

AADSTS70002: Error validating credentials. AADSTS16000: Request is ambiguous: multiple user identities are available for the current request.

**Comment by enail131** [comment]
Sounds like you’re logged in to multiple office 365 accounts. Try logging out of all accounts and logging back in. A new session might help as well. Clearing cache and all cookies/tokens might not be a bad step either.

**Comment by kannansgit** [comment]
Thanks for you response @enail131 . As mentioned in my edit above, we have multiple O365 tenants and there are still users using IE11. Forgot to mention, it works in IE11 inprivate. But we can't ask all the users to use InPrivate mode. The issue I have realised is it is not sending login_hint with authorize request.

**Comment by andrewconnell** [comment]
*Reviewing old comments...*

Are you still experiencing this issue? It's been a while since this was posted and many updates have been applied to SPO + released for SPFx. If it is still present, please provide additional detail such as specific error messages. TIA

**Comment by kasgit** [comment]
Hi Andrew,

Now, we are getting a different issue, maybe after the said fixes were deployed. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/19492569/59816585-031ebb80-9360-11e9-9e63-2d06eb8f7b2f.png)

**Comment by andrewconnell** [comment]
@kasgit I'm aware of one fix that rolled out in the system that dealt with the issue of multiple identities on the page, but can't recall exactly what it was. It wasn't in the SPFx codebase, rather a SPO code rollout.

This issue is about Edge & IE11 not working... if there's a different issue, you should open another issue and provide details.

**Comment by kasgit** [comment]
@andrewconnell Thank you for your response. We used to get the same error(in IE). And realised that there was a fix deployed at SPO level(spfxsinglesignon.aspx). But now we are getting a popup error message(screen grab below). Hence, was wondering, whether upgrading spfx from version 1.6 to 1.8 would fix this issue. Nevertheless, will try to upgrade sometime today and will let you know.

![image](https://user-images.githubusercontent.com/19492569/59885512-dff71900-93fe-11e9-9ef3-b593799aff92.png)

![image](https://user-images.githubusercontent.com/19492569/59885520-e7b6bd80-93fe-11e9-9433-2ed4d3bd3b67.png)
