### ISSUE TITLE
Serve dev workbench using a domain other than localhost?

### ISSUE THREAD

**Issue by butchmarshall** [SharePoint/sp-dev-docs#1558]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Our company does development on VMs.  Each machine has its own subdomain that runs with HSTS.

I was able to add certPath and keyPath easily enough to config/serve.json to get around the HSTS issues, but when accessing the workbench `https://[DOMAIN]:4321/temp/workbench.html` everything points to localhost.

Is it possible to configure the domain that is used as well for all the resources?

Adding serveConfig.domain to `node_modules/@microsoft/sp-webpart-workbench/lib/api/workbenchPage.js` throws an error when I attempt to add the key and manually entering the domain throws further problems.

Is there something I'm missing in the initial setup?

Our workaround right now for anyone else with this problem is to port forward 4321 from the VM
e.g. `ssh -L 4321:localhost:4321[vm_host]`

**Comment by andrewconnell** [comment]
As this is by design, changing the behavior would fall into the category of a feature request that should be submitted to uservoice at https://aka.ms/spfx-dev-uservoice
