### ISSUE TITLE
Authentication methods needed

### ISSUE THREAD

**Issue by mores** [SharePoint/sp-dev-docs#1559]
How is one supposed to Authentication with these examples ?

context.Credentials = new SharePointOnlineCredentials(userName, securePassword);
will not work. It results in:
Message=Cannot contact web site 'https://xxxxxx.sharepoint.com/' or the web site does not support SharePoint Online credentials. The response status code is 'Unauthorized'. The response headers are 'X-SharePointHealthScore=0, X-MSDAVEXT_Error=917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically., SPRequestDuration=26, SPIisLatency=15, MicrosoftSharePointTeamServices=16.0.0.7507, X-Content-Type-Options=nosniff, X-MS-InvokeApp=1; RequireReadOnly, X-MSEdge-Ref=Ref A: 13B21AF6861A439993CEFAB936F7CA0D Ref B: CH1EDGE1211 Ref C: 2018-03-29T13:23:27Z, Content-Length=0, Content-Type=text/plain; charset=utf-8, Date=Thu, 29 Mar 2018 13:23:27 GMT, P3P=CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI", X-Powered-By=ASP.NET'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mores** [comment]
Is this an approved method: http://www.thesharepointguide.com/access-office-365-using-a-console-application/

**Comment by frankchen76** [comment]
@mores, I believe the AppId and Add-in permission approach you mentioned in your link is supported from MS. see [Register SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins) and [Add-in permissions in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint). Did that answer your questions?

**Comment by andrewconnell** [comment]
As @frankchen76 stated, that is the supported approach. Authentication with SharePoint Online requires Azure AD auth.
