### ISSUE TITLE
Different behavior on css loading workbench vs. classic page

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#156]
#### Category
[ x] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea

I have a component which uses the ReactJS SearchBox component from OfficeUIFabric. When testing using workbench **fabric.component.css** is loaded first, then all webpart styles are applied, which overrides some of them. Eg, default the box is 180px wide, the react component sets it to 100%.

When adding the webpart on a classic page, **fabric.component.css** is loaded after the overriding styles, making the component render wrongly.

![image](https://cloud.githubusercontent.com/assets/51104/18239568/5c32c7da-7346-11e6-8f75-03406b48c424.png)

vs. (image clipped but to show the point)

![image](https://cloud.githubusercontent.com/assets/51104/18239578/6b42c158-7346-11e6-9417-48220164f1c1.png)

By adding my own overrides in a separate .css file, I got it to look ok.

**Comment by manishgarg1** [comment]
VSO #245414

**Comment by manishgarg1** [comment]
fabric.component.css has been removed now. The change should make it to Prod this week or next. Please try this in a couple of weeks and if you still see issues, please do let us know.
