### ISSUE TITLE
🐞 Running `gulp bundle --ship` doesn't clean up previous build

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1562]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Files from the previous bundle get removed first.

#### Observed Behavior
This is basically the same bug that was already documented by @waldekmastykarz on #158 .

When you execute ```gulp bundle --ship``` the first time the files in the temp folder look normal.
<img width="493" alt="screen shot 2018-03-29 at 22 42 32" src="https://user-images.githubusercontent.com/5503835/38112567-a5a16854-33a2-11e8-909c-0df5aec1e3b7.png">

All the expected files end up in the temp folder.
When you change something in the web part code and execute ```gulp bundle --ship``` again some new files will be generated in the same folder.
<img width="584" alt="screen shot 2018-03-29 at 22 46 23" src="https://user-images.githubusercontent.com/5503835/38112706-12112a06-33a3-11e8-8f88-c6ed07fa2657.png">

When you then change again something in the code and execute ```gulp bundle --ship``` again another additional file gets generated.
<img width="574" alt="screen shot 2018-03-29 at 22 48 07" src="https://user-images.githubusercontent.com/5503835/38112795-5194c34a-33a3-11e8-8667-e71a4d96577c.png">

So whenever a gulp bundle gets executed a new file will be generated in the folder. All those files will be packaged in the solution.

The only workaround is to clean manually before.

**Comment by patmill** [comment]
Cleaning up old bugs.  This does not happen anymore.
