### ISSUE TITLE
App Redirect in Provider Hosted Apps is taking long time to load.

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#1563]
Hi @VesaJuvonen ,
Hope you are doing good!
I have been working with provider hosted apps for a while, i have found an issue while loading the app.
The actual app logic in the IFrame loads very fast , but the app redirect which says "Working On it " takes time(Approximately 8-10 seconds) to load.
Could you please give us a solution or any work around for this issue?

Many Thanks

**Comment by patmill** [comment]
Hey @sidjustsid - any chance you could get a correlation ID for a slow request?  That would help us sort out what might be going on.

**Comment by VesaJuvonen** [comment]
Closing as no response to the request for needed information.
