### ISSUE TITLE
Applicable Versions

### ISSUE THREAD

**Issue by DeanGross** [SharePoint/sp-dev-docs#1568]
Please identify which versions of Sharepoint this service description applies to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c4fef0e-c32e-4e2a-496d-516b3619161f
* Version Independent ID: 5e7a8d3c-be07-083c-231f-1791107d2199
* Content: [Machine Translation Services in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/machine-translation-services-in-sharepoint)
* Content Source: [docs/general-development/machine-translation-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/machine-translation-services-in-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
As defined in SharePoint Server docs here, https://docs.microsoft.com/en-us/sharepoint/technical-reference/machine-translation-service-in-sharepoint-server, it's available in SharePoint Server 2013-2019.
