### ISSUE TITLE
Request for Yeoman generator to reshow the framework prompt when adding a second web part

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#157]
#### Category

[ ] Question
[ ] Typo
[x] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

When adding another Web Part to an existing project, I would expect the Yeoman generator to prompt which framework I want to use. That way I can decide for each Web Part what the starting point should be.
#### Observed Behavior

When adding another Web Part the generator doesn't prompt to choose the framework.
#### Steps to Reproduce

Call `yo @microsoft/sharepoint` on an existing project.

**Comment by iclanton** [comment]
@chakkaradeep - You can speak to this.

**Comment by chakkaradeep** [comment]
We discussed this internally. We decided not to pursue with this - adding web parts built in different frameworks using yeoman for obvious performance and bundling optimizations. While the SharePoint Framework is framework agnostic, we recommend to choose a framework of your choice across your projects/web parts for the above mentioned reasons.

If your scenario is to build web parts in different frameworks, you should create a new client-side solution project. If you still wish to manage different frameworks within the same client-side solution project, then you can do so manually.

**Comment by waldekmastykarz** [comment]
In that case I would suggest that you clarify it in the generator that the framework you choose, applies to the whole project rather than to a single web part.

**Comment by chakkaradeep** [comment]
@waldekmastykarz Good point. Let me figure out the right text/experience :)

**Comment by lucaband** [comment]
We did some targeted work to change the experience and, although it might not be sufficient, we didn't receive further feedbacks on this area.

Waldek, I'm going to close this for now. As always, thanks a lot for your help here and please fell free to absolutely re-open this issue if you believe that we still have significant issues in this area.
