### ISSUE TITLE
In a React Sharepoint Framework webpart, the ComponentWillUnmount is not invoked when the webpart is deleted from the Page.

### ISSUE THREAD

**Issue by yoghcl** [SharePoint/sp-dev-docs#1570]
I'm facing issue with the React web part I have in my solution. The ComponentWillUnmount event is not invoked when I delete the web part from the page. 

To repro this issue, I have created a dummy webpart,  which writes some stuff to the console log when it is unmounted (I am assuming here that whenever we remove a SPFX React web part, it should call ComponentWillUnmount handler). In my case, it is not logging the stuff to the console window.

You can refer the code here https://github.com/yoghcl/reactUnMount

Please let me know if I am missing something.

**Comment by yoghcl** [comment]
Thanks Jon, it worked for me.

**Comment by patmill** [comment]
Sorry for leaving this open.  This additional onDispose method was included in the scaffolded projects a while ago.  Thanks.
