### ISSUE TITLE
CreateCopyJobs Endpoint don't work in SPFx

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1571]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Currently working on a new PnP sample that shows how to move/copy files cross-site collection using the Microsoft Graph and the new `/_api/site/CreateCopyJobs` Endpoint. The data submitted to this endpoint was correct but no valid result was returned to identify the Job ID and not data were moved.
The desired behaviour is to be able to use this endpoint in custom code because with the cross-site collection move I can accomplish a lot of business scenarios.

#### Observed Behavior
From a custom web part that uses a target and source path parameter to identify files, the cross-site collection move gets triggered.
<img width="919" alt="screen shot 2018-03-31 at 14 53 39" src="https://user-images.githubusercontent.com/5503835/38171988-5baa84e8-35a4-11e8-8b78-95b9deef5216.png">

The click on the button sends a regular POST request with proper data and the service all returns status code 200:

```js
this._context.spHttpClient
    .fetch(restEndPoint, SPHttpClient.configurations.v1, request)
    .then((response) => {
        console.log(response);
     }).then((result: any) => {
        console.log(result);
     })
```

The returned status in is the following:

<img width="921" alt="screen shot 2018-04-01 at 11 46 34" src="https://user-images.githubusercontent.com/5503835/38172033-2bfe5124-35a5-11e8-9ae2-a06869063b54.png">

The response by this endpoint only contains the following information:

```
{
    "@odata.context" : "https://tennantname.sharepoint.com/sites/SalesTeam/_api/$metadata#Collection(SP.CopyMigrationInfo)",
    "value":[]
}
```

The response give back by SharePoint using the UI is:

<img width="812" alt="screen shot 2018-04-01 at 12 12 05" src="https://user-images.githubusercontent.com/5503835/38172095-36ab0ca6-35a6-11e8-9f2c-b89ad8b16a74.png">

#### Steps to Reproduce

Send a POST request in the following format to the endpoint:

```
https://tenant.sharepoint.com/sites/SalesTeam/_api/site/CreateCopyJobs
```

The post request should contain the following format:

```js
{
  "destinationUri": "https://tenant.sharepoint.com/sites/SalesTeamInfo/Shared%20Documents",
  "exportObjectUris": [
      "https://tenant.sharepoint.com/sites/SalesTeam/Shared%2520Documents/CopyCopyCopy.png", 
      "https://tenant.sharepoint.com/sites/SalesTeam/Shared%2520Documents/CopyCopyCopy.jpg"],
  "options": {
    "IgnoreVersionHistory": true,
    "IsMoveMode": false
  }
}
```

If needed I can share the beta code in a repo.

**Comment by rdorrani** [comment]
Hi Vesa,

The createcopyjobs now sends response which also includes SourceListItemUniqueIds

{
	"copyJobInfo": {
		"EncryptionKey": "epqb0MWTFkHKm1XDjmv56ISK7aeflkCfn4NGZcc927Q=",
		"JobId": "4916f9f5-af72-4286-aa3a-7f8ee5e8b489",
		"JobQueueUri": "https://spobl1sn1m021pr.queue.core.windows.net:443/1201pq20180808-8b8d3be279b14bb593a34a26508fcbad?sv=2017-07-29&sig=ri4rc%2FHzITZGNdeYJPtzZ7Hn6XUOo%2BgVLTIHGSY6idM%3D&st=2018-08-07T07%3A00%3A00Z&se=2018-08-29T07%3A00%3A00Z&sp=rap",
		**"SourceListItemUniqueIds": ["41047376-6b16-4fc0-a483-86752e2a1e23"]**
	}
}

When I try and query getcopyjobprogess using the above job info it erros when i pass SourceListItemUniqueIds in the request body
But when i exclude SourceListItemUniqueIds it works as expected

I'm using this at a production tenant and although its working now after i have removed SourceListItemUniqueIds but I am getting worried about the constant changes

**Comment by svarukala** [comment]
There are multiple APIs to copy/move documents between site collections in SPO. Example:
a. Microsoft Graph
b. SPO REST API
c. SPO REST AP v2.0
d. [SPO Create Copy Jobs API](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt796381(v%3Doffice.15))

I know Microsoft Graph is the preferred option. I understand SPO rest api and the v2.0 endpoints too, as one exists for legacy support and the other is the backend for Graph. What is the context/story around the last (d) option: the SPO Create Copy Jobs API. The lack of documentation and usage samples on this API, makes me suspect if this is a supported endpoint. Can anyone shed some light on this?

Customer is seeing some issues using Microsoft Graph copy/move api, so considering the Create Copy Jobs API. I want to make sure they are heading in the right direction. 

PS: I am working internally to escalate the MS Graph issues.

**Comment by joelfmrodrigues** [comment]
Just leaving a note here to mention that PnPjs now has new methods (CopyByPath and MoveByPath) to copy/move files and folders that also work cross-site collection in case this helps someone

**Comment by kimrohdin** [comment]
@svarukala did you get any information regarding the story about the api? I'm been trying it out from spfx using sphttpclient and working really good, both CreateCopyJobs and getting progress from GetCopyJobProgress. Only documentation I've found is from using it with CSOM https://docs.microsoft.com/en-us/sharepoint/dev/apis/spod-copy-move-api

**Comment by svarukala** [comment]
@kimrohdin I didn't get any additional information on that API. Since there is some official documentation I think you should be fine using that endpoint.

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
