### ISSUE TITLE
sp-dialog error

### ISSUE THREAD

**Issue by sreejukg** [SharePoint/sp-dev-docs#1573]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a running tsx file that loads a ListView. The project loads fine. I ran the following command 
**npm install** **@ microsoft/sp-dialog**

Then in the tsx in added the following import statement. 
**import { SPHttpClient } from** '**@ microsoft/sp-http**';

When I use gulp build, I am getting the following error. 

**_Error - typescript - node_modules\@microsoft\sp-dialog\node_modules\@microsoft\sp-core-library\lib\deferredCl
ass\DeferredClass.d.ts(25,24): error TS1005: ';' expected._** 

I can see the error is pointing to the abstract keyword in the DeferredClass.ts file. How can I fix this?

**Comment by sreejukg** [comment]
Anybody else is facing the issue?

**Comment by sreejukg** [comment]
No response yet?

**Comment by andrewconnell** [comment]
Since the issue was posted many SPFx versions ago, can you confirm if this is still an issue or not with the latest SPFx release v1.7.1?
