### ISSUE TITLE
Get-SPOProvisioningTemplate is now Get-PnPProvisioningTemplate ??

### ISSUE THREAD

**Issue by mores** [SharePoint/sp-dev-docs#1576]
It looks like Get-SPOProvisioningTemplate has been replaced with: Get-PnPProvisioningTemplate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b8037-a569-40c1-86ad-cbf56c9c4b4b
* Version Independent ID: c9dfddaa-7f54-7194-db9e-cf5f6370cbb5
* Content: [Introducing the PnP Provisioning Engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yup, and the doc reflects that.
