### ISSUE TITLE
Great Article

### ISSUE THREAD

**Issue by harshdamania** [SharePoint/sp-dev-docs#1579]
This article really help me in customizimng webpart properties using REACT Framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08aa20fb-4cde-4ea6-8946-d67451e78e55
* Version Independent ID: 3c47f3e6-427a-681d-42c7-db0a821da0e9
* Content: [Validate web part property values](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values)
* Content Source: [docs/spfx/web-parts/guidance/validate-web-part-property-values.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/validate-web-part-property-values.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
Thank you! Great to hear you found it helpful.
