### ISSUE TITLE
Running `gulp bundle --ship` doesn't clean up previous build

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#158]
#### Category

[ ] Question
[ ] Typo
[x] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

When running `$ gulp bundle --ship` the previous contents of the **./temp/deploy** folder should be removed. 
#### Observed Behavior

New bundles are created next to old bundles. That way developers could end up deploying both old and new code.
#### Steps to Reproduce

This error occurs when something about the Web Part's code changes between the builds.
- create new project with an empty Web Part
- run `$ gulp bundle --ship`
- change something in Web Part's code
- run `$ gulp bundle --ship` again
- you end up with a new and an old main Web Part bundle file

**Comment by manishgarg1** [comment]
VSO #245429

**Comment by IntranetFactory** [comment]
@manishgarg1 What is "VSO #245429" ?

**Comment by patmill** [comment]
@IntranetFactory - It's the internal bug # tracking this issue.

**Comment by IntranetFactory** [comment]
Internal means that nobody outside from Microsoft can use that information? So does it make sense at all to post it here?

**Comment by webtechy** [comment]
I would have thought even just "gulp bundle" should effectively clean out the temp and dist folders first too and build from the manifest not what happens to be in those folders already.

**Comment by webtechy** [comment]
The workaround is as follows, run:

```
gulp clean
gulp build
gulp bundle --ship
gulp package-solution --ship
```

**Comment by patmill** [comment]
This should be fixed (back in August).
