### ISSUE TITLE
Should i use componentWillUpdate to refresh the webpart

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1580]
As soon as the value changes, I am referring it by using this.props.listName in my components tsx file. When value changes in webpart properties ComponentDidMount will not work . So Should i use componentWillUpdate for this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08aa20fb-4cde-4ea6-8946-d67451e78e55
* Version Independent ID: 3c47f3e6-427a-681d-42c7-db0a821da0e9
* Content: [Validate web part property values](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values)
* Content Source: [docs/spfx/web-parts/guidance/validate-web-part-property-values.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/validate-web-part-property-values.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not clear... the `componentDidMount` is a React lifecycle event that fires when the component is added to the page (think of it like the components `onLoad()` event). If SPFx didn't re-run `render()` and re-add the item to the page, then the component won't get added to the page and thus have that lifecycle event fire. Same applies to `componentWillUpdate()`
