### ISSUE TITLE
Pictures with includeClientSideAssets options not displayed in Internet Explorer

### ISSUE THREAD

**Issue by lucmoco** [SharePoint/sp-dev-docs#1581]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Pictures deployed with the `"includeClientSideAssets": true` option are displayed properly in all browsers.

#### Observed Behavior

As of April 03, 2018, in Internet Explorer only, such pictures are not displayed properly anymore.

![image](https://user-images.githubusercontent.com/31615157/38237742-4b63dfa0-3728-11e8-80f6-78956f2b98f8.png)

Expected URL, correct in Chrome and Edge:

> https://tenant.sharepoint.com/sites/addincatalog/ClientSideAssets/308960a1-2830-4d57-88e0-fb3ff11132a7/logosharepoint_dd109d6a09405eb4e6546c02e24a5595.svg

Actual (wrong) URL in Internet explorer, the GUID part is missing:

> https://tenant.sharepoint.com/sites/addincatalog/ClientSideAssets/logosharepoint_dd109d6a09405eb4e6546c02e24a5595.svg

This used to work last week (on March 28, 2018). The problem has been observed in two different tenants.

#### Steps to Reproduce

- Set-up an SPFx solution with the `"includeClientSideAssets": true` option.
- Add a picture under `src\webparts\myWebPart\assets`
- Display it in the web part as follows:

```TypeScript
const pictureUrl = String(require("../assets/myPicture.svg"));
...
<img src={pictureUrl} />
```

**Comment by michel-weber** [comment]
Same issue here

**Comment by VesaJuvonen** [comment]
We are looking into this, thx for submitting.

**Comment by Konradox** [comment]
Same here. I've just made copy of assets in ClientSideAssets library as a workaround but it has to be fixed. I'm waiting for fix.

**Comment by mcmynn83** [comment]
This issue has now been fixed and the change will start rolling out to production on May the 13th.   Thank you for notifying us of this issue.
