### ISSUE TITLE
Deploy sppkg to many sites using powershell

### ISSUE THREAD

**Issue by mores** [SharePoint/sp-dev-docs#1585]
PnP has Add-PnPWebPartToWebPartPage.....how can this sppkg be deployed to hundreds of sites using automated tools? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OmniFace** [comment]
We also need this information urgently.  Attempts to deploy an app-extension using Managed Paths through the app catalog are throwing errors.  Attempts to use some API's for deployment are also failing.  Any information on how to deploy en masse would be greatly appreciated.

**Comment by russgove** [comment]
have you looked at
https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins

**Comment by OmniFace** [comment]
Yes, we did.  They were not working for our App Extension according to my developer.  For example, after attempting to push the app-extension into the app catalog, no errors were reported, but the app-extension did not appear in the catalog.  We'll look at it again to be sure it wasn't a mistake on our part.

**Comment by VesaJuvonen** [comment]
Deployment of a web part or an extension to thousands of sites have few different options. The most convenient option is to use tenant scoped deployment, which means that just by adding your solution to app catalog, web parts inside of it are available in all of the related sites. This kind of solution cannot, however, be responsible for provisioning any assets to the site, like lists or columns. 

See more on tenant scoped deployment from following article - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-scoped-deployment. 

Web parts can be activated on sites with tenant scoped deployment as they have a picker for content editors. Extensions can be enabled on the sites, but they'd still need to be activated. This means that they have slightly different options for deployment. See https://www.youtube.com/watch?v=YMyZHtE5IbI.

Starting from SPFx v1.6 which will be related late August 2018, you can also enable SPFx extensions to be enabled in sites from app catalog using new tenant wide deployment option for SharePoint Framework extensions. This was demonstrated for example in following SharePoint Dev monhtly community call - https://youtu.be/sPogIORXWcA?t=3065.

**Comment by Alex-Ji** [comment]
I met a problem about package version control. Story is I have two site collections one is  for demo, another is for qa test. I build a package with an increasing version number and deploy it to app catalog. all sites be affected immediately, I confirm none of sites have upgrade app by 'Get it'.
