### ISSUE TITLE
can we get multiple propertyName GetUserProfileProperty

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1586]
/_api/SP.UserProfiles.PeopleManager/GetUserProfilePropertyFor(accountName=@v,propertyName='LastName')?@v='" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe84109-0e6f-eb1f-4b62-851b1a124624
* Version Independent ID: f105023f-9ea7-627d-0850-7b20afa063b0
* Content: [Work with user profiles in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint)
* Content Source: [docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/work-with-user-profiles-in-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shaipetel** [comment]
I second that. I only need 2-3 properties so my options are either to get everything or make 3 requests.
Allowing to get more than one property would be very helpful and help us reduce server load and traffic.

**Comment by shaipetel** [comment]
Actually, I just tested it and this API supports the $select REST query parameter that allows you to get multiple column.
Use "GetPropertiesFor" endpoint, and use $select to pass multiple properties that you would like to get.
Sadly, the "UserProfileProperties" is considered as 1 property that brings back all profile properties, but still greatly reduced my request size.
