### ISSUE TITLE
Remove creating user from office 365 member group

### ISSUE THREAD

**Issue by JonEOffice** [SharePoint/sp-dev-docs#1587]
I want to make it so that the person creating the site gets removed from the office 365 group so that they can create a site for another user. This is always the same user. I currently can only get the URL in the trigger flow, is there a way to get the ID of the office 365 group in the 'trigger a flow' section under the parameters? or are those always set value's?
{
    "verb": "triggerFlow",
    "url": "<A trigger URL of the Flow.>",
    "name": "Record and tweet site creation event",
    "parameters": {
        "event": "Microsoft Event",
        "product": "SharePoint"
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patrickabel** [comment]
Can you provide some guidance regarding what's expected for the "principal" value when adding users (principals) to SharePoint Groups via a Site Script? I have an AD Security Group named Site_Managers and the following is not working:
{
            "verb": "addPrincipalToSPGroup",
            "principal": "Site_Managers",
            "group": "Owners"
        }
