### ISSUE TITLE
Developer Videos Link

### ISSUE THREAD

**Issue by oozoo-solutions** [SharePoint/sp-dev-docs#1588]
The SharePoint Developer Videos link above always asks me to sign in the gives me access denied with any account but I'd assume I shouldn't have to login to see any of those videos? Thanks, Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f0bf18-5ece-8fac-f602-17500085ad26
* Version Independent ID: 087cf5a1-6c1e-1f19-b3c1-d1e661092fb3
* Content: [SharePoint Dev Community resources](https://docs.microsoft.com/en-us/sharepoint/dev/community/community)
* Content Source: [docs/community/community.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/community/community.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Thx for reporting. This was a mistake in the URL structure, which has been now updated accordingly. You can also use http://aka.ms/spdev-videos for landing on the SharePoint Dev video channel on YouTube.
