### ISSUE TITLE
Knockout Web Part incorrectly extends base class

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#159]
#### Category

[ ] Question
[ ] Typo
[ x] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

I was just testing out the Knockout template. When I started `gulp serve` it spits out the following error: `Class 'TestKnockoutWebPart' incorrectly extends base class 'BaseClientSideWebPart<ISearchWpKnockoutWebPartProps>'`.

The `_description` property is defined two times. In the **TestKnockoutWebPart** and **BaseClientSideWebPart**.
#### Steps to Reproduce

Start `yo @microsoft/sharepoint` and create a new project based on Knockout.

**Comment by manishgarg1** [comment]
VSO #245430

**Comment by manishgarg1** [comment]
Fixed.
