### ISSUE TITLE
Contradiction on two pages of the documentation

### ISSUE THREAD

**Issue by maciejmaksymo** [SharePoint/sp-dev-docs#1590]
On this page we read:
"Because the @microsoft/sp-office-ui-fabric-core package is already installed in your solution by the Yeoman generator, we recommend that you uninstall that package if you decide to use Fabric components and reduce your component bundle size."

and later:
"Fabric components in your solution are locked to the specific version of Fabric React that you installed. You need to update the Fabric React package to get any new components if they are available in a newer package version. Because the Fabric components are included in the component bundle, it may increase the size of your component bundle. However, this approach is the only approach that is officially supported when Office UI Fabric React is being used in SharePoint Framework solutions."

While on the page 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components
you can find the following:
"With the current release of the SharePoint Framework, we recommend that you use the Office UI Fabric and Fabric React that ships with the generator. We don't recommend that you update the Office UI Fabric and Fabric React packages independently because that might conflict with the already available version in SharePoint, and as a result, your web part may fail to function as expected."

Which is the supported way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dedd717-ec39-dcd9-3994-7bab3839df28
* Version Independent ID: 0eddf92b-1b20-650e-2432-83c530279815
* Content: [Using Office UI Fabric Core and Fabric React in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration)
* Content Source: [docs/spfx/office-ui-fabric-integration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/office-ui-fabric-integration.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jeremy-coleman** [comment]
The whole doc just talks about problems with css scoping , like people who are using this lib dont know that already. Replace with it with 1 example would be a win

**Comment by andrewconnell** [comment]
The former is correct... the docs were simply not in sync and the first one's last update date showed it was more current. Fixing the docs...
