### ISSUE TITLE
Does these API works with provider hosted apps also ?

### ISSUE THREAD

**Issue by arbarik** [SharePoint/sp-dev-docs#1591]
We are trying to install one provider hosted app to one of our SharePoint site with ALM API , but it is not getting installed, it throws error.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by AveAdam** [comment]
It works. But doesn't work with application permission access token of AAD app .

https://github.com/SharePoint/sp-dev-docs/issues/1501

**Comment by andygjones-nz** [comment]
I am also having issues using ALM to install a provider hosted app under an AAD application identity. The exact same code using a user account contexts works fine.

No errors are returned from PnP ALM itself, but in the SharePoint UI the app starts installing and seems to get stuck and eventually time out. Error reported in SharePoint is "The operation took too long".   Presumably something to do with the apps permission request.

I'm using SharePointPnPCoreOnline v2.25.1804.1

**Comment by jcharikofsky** [comment]
I was wondering if anyone had found a solution to this issue. I have a complex provisioning process that requires several custom apps to be installed on the site collection - completely unattended. It is operating under an AAD application identity. If I monitor the installation status for the add-in it goes from installing --> initializing and then hags. Eventually the UI display a failure message - clicking retry immediately corrects the issue (but requires human interaction which is not a solution).

Is there a way to mimic the retry functions being called in the UI, or has the root issue been corrected?

I am executing PnPCoreOnline 2.28.1807.

**Comment by ravick4u** [comment]
I am also facing the same issue.

I am giving below permissions to my app and ALM api does not throw any error.
- Tenant Full control
- Site Collection Full control”

After waiting for 10-20 mins got below error on UI

https://ibb.co/iJuNuK

**Comment by ppatalong** [comment]
it does work with provided hosted for me, although there is issue with permissions. Somehow `Install-PnPApp` ignores tentant wide permissions.

**Comment by andrewconnell** [comment]
There are a few different threads going on here... the OP asked if the ALM APIs work for provider hosted add-ins. Yes, they do... there's nothing special about what's in the `*.sppkg` file that's being deployed/installed WRT the ALM APIs.

There are other questions about the installation of an add-in that has app-only permissions. Instead of mixing the thread with different topics, can you open a separate issue for the add-in permission install? When you do, please verify if you are successfully installing the add-in via the browser UX but not the REST APIs. IOW, make it clear that it's an issue with the ALM APIs and not with deployment in general.

**Comment by ppatalong** [comment]
Yeah, someone already answered my question in different topic. Anyway, the
answer is "working as intended", therefore you should not use ALM API for
provided hosted stuff.
Thanks for answer anyway.

czw., 16 maj 2019 o 11:58 Andrew Connell <notifications@github.com>
napisał(a):
