### ISSUE TITLE
SPFx Extension

### ISSUE THREAD

**Issue by john88benson** [SharePoint/sp-dev-docs#1592]
To whom it may concern,

While the article clearly explains the process for Web Parts, I would advocate expanding upon the above with some of the extra steps for debugging a SPFx Extension.  Providing specifics on how once opened the workbench browser can be used test on different pages in a SharePoint site while still letting you step though your Extension code would be very useful.  I eventually figured it out myself, but having that extra info readily available in the article would be much more efficient.

Cheers,
-John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959a8968-baa1-e94c-10af-a52604aef21e
* Version Independent ID: cecd4be2-5717-d282-587e-7a93910a03a3
* Content: [Debug SharePoint Framework solutions in Visual Studio Code](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode)
* Content Source: [docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/debug-in-vscode.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mulduni** [comment]
I agree with John.  It would be nice to see example of extension debugging.

**Comment by parithon** [comment]
@john88benson maybe you could propose a pull request on the steps you took to accomplish this? I’m interested in the steps myself.

**Comment by andrewconnell** [comment]
@sparkitect nope... no reason why you can't just change the start URL. In this doc, the web part is used as an example as you just need to point to the start URL. Extensions are no different.

In fact, it's nothing special about SPFx... any web dev works like this when debugging with VSCode.

**Comment by andrewconnell** [comment]
This issue was never closed from merging PR #1884... closing now
