### ISSUE TITLE
Powershell access permissions

### ISSUE THREAD

**Issue by mayurnjoshi** [SharePoint/sp-dev-docs#1595]
Could you confirm if Global Administrator privilege is really required for PowerShell execution? Since this is SharePoint Online feature shouldn't SharePoint Online Admin access suffice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by tacklers** [comment]
As Microsoft persist in making this type of feature as difficult to disable as possible then I bet Global Admin is required!

**Comment by tacklers** [comment]
I used the Powershell to turn ON the Opt Out feature and it worked as described BUT the guide is misleading referring to both sites and site collections. I presume that it is now turned off for every site in the tenancy as no site collection was specified below the tenancy level.

**Comment by Okorsal** [comment]
How long did it take for you to opt out of the new themes? I ran the command but my site still looks the same.

**Comment by andrewconnell** [comment]
@mayurnjoshi said:
> Could you confirm if Global Administrator privilege is really required for PowerShell execution?

I _believe_ site collection own is all that's needed. Generally speaking, you don't need to be global admin when you connect to a specific site, only the tenant's admin site. Again... that's a general statement... always exceptions to that.

@tacklers said:
>  the guide is misleading referring to both sites and site collections

Generally site = site collection these days.
