### ISSUE TITLE
Cannot read property 'getManifests' of undefined in workbenchinit.js

### ISSUE THREAD

**Issue by anuvcse** [SharePoint/sp-dev-docs#1596]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
 

I follow all the steps given in https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part, still i get error saying manifest.js file not found in temp folder and Uncaught TypeError: Cannot read property 'getManifests' of undefined. please find the attached image.
I am new to sharepoint framework. Please guide me to resolve the issue as soon as possible

![err](https://user-images.githubusercontent.com/11072575/38341605-072acfb6-383f-11e8-873d-39d4cc2afdb1.png)

**Comment by anuvcse** [comment]
I dont find manifest file in temp folder.If i remove the reference in  workbench.html, first two issue will resolve. Still i have another two issue remaining uncaught type error getmanifests is undefined.

**Comment by patmill** [comment]
Sorry - clearing out super old issues that had been dropped.  The local host has been deprecated, and this wasn't reported by others as well.
