### ISSUE TITLE
Login Prompts for external user when people card is on page

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1599]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
This is not directly related to SPFX, but modern pages should work for external users without login prompts every time

#### Observed Behavior
Whenever there is a control that uses the new peoplecard, external users get login prompts on every page load.
![loginprompt](https://user-images.githubusercontent.com/8672900/38358925-48057848-38b6-11e8-89d0-32198db16af5.PNG)
E.g. when you have comments enabled on the page or when you are using the People webpart. Same happens on lists/libraries with a person column. So basically everywhere where a peoplecard is beeing used.

#### Steps to Reproduce

Create a site and share it with an external user. Add the people webpart to the homepage and add some people or just enable comments. Login as the external user and you will see prompts everywhere...

**Comment by patmill** [comment]
Sorry for leaving this open.  As you mention, this isn't related to spfx / development.  As such, I'm going to close this.
