### ISSUE TITLE
How to work with ServiceScopes and ServiceKeys?

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#160]
#### Category
[X ] Question

There are descriptions of the ServiceScope and ServiceKey classes in the API docs:
https://sharepoint.github.io/classes/_sp_client_base_.servicescope.html

It would be good to get some samples on how these classes are meant to be used with the SharePoint Framework.

**Comment by patmill** [comment]
Check out the article written by @pgonzal here - https://github.com/SharePoint/sp-dev-docs/wiki/Tech-Note:-ServiceScope-API

**Comment by vman** [comment]
Yes definitely. Thanks for that @pgonzal and @patmill!
