### ISSUE TITLE
Site scope clarification request: Tenancy, Site Collection or Site?

### ISSUE THREAD

**Issue by tacklers** [SharePoint/sp-dev-docs#1601]
When the OPT OUT is enabled as above does it affect every site collection in the tenancy OR does it have to be applied at every sub-site level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview#feedback)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The scope is the site collection, which includes the sites.
