### ISSUE TITLE
Feature Enabled but theme still visible

### ISSUE THREAD

**Issue by oberjc** [SharePoint/sp-dev-docs#1602]
I ran the PS script to enable the feature on the Site Collection.  When running the get command I received the anticipated result = ClientSideThemingOptOut with the correct DefinitionID.  It has been several hours and I can still see the option to Change the look on the site. How long does it take for the change the look option to disappear from the gear menu?  Is there any way to run this on the tenant?  I want to turn this off for all site collections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by oberjc** [comment]
Two days later the "change the look" is still visible and working on the site.  Confirmed the feature is still enabled.

**Comment by oberjc** [comment]
Tested on another site collection and not working even though feature is enabled.  Anyone from Microsoft???

**Comment by Okorsal** [comment]
Were you able to figure this out yet?

**Comment by Zerg00s** [comment]
I have the same question. I've enabled the feature **ClientSideThemingOptOut**, but "change the look" option still shows up. Maybe it's just my misunderstanding of what this feature does? 

![image](https://user-images.githubusercontent.com/2797648/58261752-eb471e00-7d46-11e9-91d9-650dbbc5968c.png)

**Comment by sparkitect** [comment]
I'm guessing the it doesn't completely remove "Change the look", it only removes the Modern version of what happens when you click on "Change the look".
