### ISSUE TITLE
Is it possible to deploy .spapp to a dev site collection instead of the tenant app catalog?

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#161]
#### Category
[ x] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea

Is there a way to enable uploading .spapp packages to a dev side collection instead of the tenant app catalog?

**Comment by patmill** [comment]
Not at this time, no.  We are considering allowing a site collection that does not have no-script enabled on it to have a local app catalog, but it is not definite.
