### ISSUE TITLE
Hosting SPFX solution using Office 365 has issues with particular tenant

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1610]
<img width="944" alt="capture" src="https://user-images.githubusercontent.com/11780473/38415873-6f49445c-39b0-11e8-9e6e-e1998fdc91aa.PNG">
Pls check the image for issues
I followed all steps in documentation of microsoft

**Comment by VesaJuvonen** [comment]
Hi @harshdamania, any change you could re-activate the CDN in this tenant and then share the outcome. This clearly seems to be related on the CDN settings, but there is not that much information here which would be actionable for us.

**Comment by harshdamania** [comment]
I tried deleting and recreating the cdn.. Still it doesn't work.
For now I am using sharepoint document library instead of cdn. 
It works in other tenant. 
I am sure there is something wrong in cdn.

**Comment by harshdamaniahd** [comment]
@VesaJuvonen  Thanks..
I have checked in my previous tenant where it was not working.
Now it works.
Similar issue https://github.com/SharePoint/sp-dev-docs/issues/1353

**Comment by VesaJuvonen** [comment]
Thx @harshdamaniahd for following up on this. Missed this one as there are quite a few duplicates on the CDN issue. Great to hear that this is now working also for you, sorry for the long lasting issue. This was a hard one to spot as it was only impacting a subset of the tenants.
