### ISSUE TITLE
Implement a solution architecture to use nested components with SPFx

### ISSUE THREAD

**Issue by ITConsultingAdAC** [SharePoint/sp-dev-docs#1611]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello guys, 

I'm just beginning to work with SharePoint Framework, using Office UI Fabric and React.js, for a professional project, deployed on SharePoint Online, which needs a standard solution architecture, containing multiple layers (such as services, models, etc….), reusable within all my web parts. But I'm facing some issues to implement my architecture.

As far as I know, it's not possible to implement such an architecture, because each project resource must be deployed to SharePoint within a webpart context. Which means that if I want to use the same service method, to load elements from a list for example, I have to duplicate the code in all my webparts, and so load my js file multiple times in my page.

I can face the same issue if I want to use an external API (PnP JS in my case) in several components on the same page: I have to load the PnP resources multiple times, which is quite bad for performances, and so provides a bad user experience.

I haven't found any documentation about this, but do you know a way to resolve this issue? 
Build multiple layers, push them to SharePoint, and load them one time only in my page, to be able to use the methods in all my nested components? 

Any help, links or tips would be greatly appreciated.

Thanks

**Comment by wictorwilen** [comment]
You can create a library component of your own (think jQuery or what not) and have it hosted in a public CDN or in SharePoint and then load it as an external library.

Or if @VesaJuvonen get enough of request we might get the Library component fully supported and working :-)

**Comment by patmill** [comment]
Sorry for leaving these issues open for so long.  We did in fact introduce Library components in version 1.9.1.
