### ISSUE TITLE
Calling a javascript before loading any SPFX webparts on modern page

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1616]
I have a requirement, where i want to fetch certain properties from user profile.For this i have created a file which fetches data from user profile and store in global variable.
I was able to add script to modern page and classic page ( Add-PnPJavaScriptLink )

Based on these user profile properties each of my webpart are getting loaded on modern page.

i dont want to call the userprofile js each time for each webpart.

I just want to call it once.Once present in global variable i should be able to access it for all other webparts

But the problem is the custom javascript is getting called after webpart is rendered

any suggestions ?

**Comment by wictorwilen** [comment]
You should look into implementing a custom SPFx Service - see #1419 for example and also when it doesn't  work.

@VesaJuvonen - once again a very valid example where we need the Service architecture to be singleton and/or have a library component.

**Comment by VesaJuvonen** [comment]
We are looking into building this support as part of the library model. No ETA at this point.

**Comment by russgove** [comment]
vesa,
we really need this badly. I am copying code  now in dozens of solutions. if something in the framework changes (not that that would ever happen) i'm going to need to go back and change each of those solutions.

**Comment by harshdamania** [comment]
Yes.. Waiting for this but for now may be we can register script through extension or pnp and store the value globally in window object and use it.
Does it make sense?

**Comment by Asad-Shah** [comment]
Any updates on this feature ?

**Comment by harshdamaniahd** [comment]
I think, this will never work, as each webpart is loading separately and on its own.
You cant decide on having a script called first and load other webparts.
Because you dont know which react component (extension or webpart) will load first
