### ISSUE TITLE
This document is outdated as the sharepoint hkey is not in specified location

### ISSUE THREAD

**Issue by xtianus79** [SharePoint/sp-dev-docs#1619]
nothing exists for either version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f90fd32e-4666-fe01-348c-14ae3f8e4dbe
* Version Independent ID: a561c546-6a45-441c-cbfb-1ba01abdbf9c
* Content: [Set up a development environment for SharePoint Add-ins on Office 365](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365)
* Content Source: [docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by byrongits** [comment]
I concur~

**Comment by andrewconnell** [comment]
To assist, can you provide more context... 
- Which version of Visual Studio are you using? 
- Have you ensured the SharePoint Development Tools are installed?

If so, can you provide a screenshot of the registry at the referenced location
