### ISSUE TITLE
Working With Visual Studio Instructions Incorrect

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#162]
#### Category

[ ] Question
[ ] Typo
[X] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

Th Modify Gulp.js section on the Working With Visual Studio page (https://github.com/SharePoint/sp-dev-docs/wiki/Working-with-visual-studio) say to change the gulpfile.js code from let to var.  I expect to see let in the code.
#### Observed Behavior

The code that is generated does not include let statements, it defines the values as constants.
#### Steps to Reproduce

Create a new SPFx Client Side WebPart with Yo.  Open gulpfile.js.

**Comment by patmill** [comment]
Re-titling this bug to track the overall "VS integration issue"

**Comment by patmill** [comment]
Note - make sure that https://github.com/SharePoint/sp-dev-docs/issues/163 and https://github.com/SharePoint/sp-dev-docs/issues/164 are covered by checking folders with and without spaces

**Comment by tomresing** [comment]
I ran into this, as well. Thanks for taking the time to submit the bug I didn't, Todd! :)

**Comment by chakkaradeep** [comment]
I am closing this issue as we no longer have the Visual Studio integration document published. Please follow this community project to [build SPFx solutions in Visual Studio](https://github.com/SharePoint/sp-dev-fx-vs-extension).
