### ISSUE TITLE
What are the version requirements for docker : SPFX

### ISSUE THREAD

**Issue by harshdamania** [SharePoint/sp-dev-docs#1620]
Are there specific version requirements for docker ?

![image](https://user-images.githubusercontent.com/11780473/38537944-286292b2-3caf-11e8-9504-aa18a9009e11.png)

**Comment by StfBauer** [comment]
What is Microsoft Windows version you on? It seems like you don't fulfil some of docker core requirements.

> The current version of Docker for Windows runs on 64bit 
> * **Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later).**
> * **Windows Server 2016 RTM**

Documented on [Install Docker for Windows](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows)

You can find this out running the command `winver` from the command prompt or PowerShell.

<img width="507" alt="screen shot 2018-04-12 at 06 31 45" src="https://user-images.githubusercontent.com/5503835/38656517-5c538cd0-3e1b-11e8-99a7-e74048828a6d.png">

**Comment by VesaJuvonen** [comment]
Requirements for the Docker in Windows are defined in the exception message from docker. Not sure we can really provide more details here.

**Comment by harshdamania** [comment]
Thanks.. Got my answer
