### ISSUE TITLE
Cannot unregister a HubSite if it's deleted

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#1621]
#### Category
- [x] Bug

Related issue: https://github.com/MicrosoftDocs/office-docs-powershell/issues/662

#### Expected or Desired Behavior

One of two:
* Either deletion of a site should be blocked if it's a hub site or has sites associated to the hub
* Deletion of a site should also unregister it as a hub site

#### Observed Behavior

I get "File not found" when running Unregsiter-SPOHub site on a deleted site.

#### Steps to Reproduce

* Create a new site
* Register it as hub site
* Delete the site
* (empty recycle bin)
* Try to run `Unregister-SPOHubSite`

**Comment by VesaJuvonen** [comment]
Thanks for reporting this. This is an unfortunate and known issue which is in the top of mind to get fixed within upcoming weeks. There are no workarounds for this for now.

**Comment by wobba** [comment]
Thank you and a good thing it's in preview and I can live with the dummy ones on my dev tenant :)

**Comment by O365Tycho** [comment]
Has this been fixed in the "May 2018 Intermediate Release 1"? If so, i couldn't find a way to remove the old/dummy ones. Did i miss something or isn't this possible yet?

**Comment by wobba** [comment]
No. We need to update the CSOM version first. In the mean time you can use the latest SPO cmdlets to unregister your hub site.

**Comment by gr79** [comment]
I have the same problem: I deleted a Hub site without un-registering as a such. Unfortunately I also deleted it from the recycle bin. Will creating a new site with the same URL as the deleted site replace the old Hub registration?

**Comment by wobba** [comment]
No, use the SPO cmdlet to unregistered it, or wait for the the June PnP release which has a fix.
