### ISSUE TITLE
Heavy load in debugging console and Network Tab of Online Workbench through 0.sp-client-telemetry-aria_0007b0d6eb81e3b09daa.js

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1622]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Make debugging messages better readable and reduce the noise of unuseful messages in Online Workbench or at least configurable.

#### Observed Behavior
During testing and developing a web part in the Online workbench I recognised that one client library include `0.sp-client-telemetry-aria_0007b0d6eb81e3b09daa.js`in the Online Workbench cause a pretty heavy load in the console cause by XHR request.

![heavy-load-on-console](https://user-images.githubusercontent.com/5503835/38548079-27b74a90-3cb1-11e8-8049-c629c2d1d2eb.gif)

This event can be filtered away in Chrome on the console but the request still appear in the network tab too. Which sometimes makes it hard to identify useful requests from those noise request.

#### Steps to Reproduce
Open Online Workbench in Browser and open the console or network tab.

**Comment by patmill** [comment]
Yes - this will happen, particularly on any page in edit mode.  The common case of the event is if the serialization of the canvas succeeded, and it triggers this every second in edit mode.  We'll see if that needs to happen as frequently as it does, but the calls to aria will happen.
