### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by m-neill** [SharePoint/sp-dev-docs#1625]
What licenses is this available to?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27643fd2-8059-f411-224b-bd0815aacc8f
* Version Independent ID: bd410f9a-a3f2-9222-7d4a-2271d7f6161d
* Content: [SharePoint ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification#feedback)
* Content Source: [docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-site-classification.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It's a SharePoint Online feature... I don't believe it's tied to specific license...
