### ISSUE TITLE
User Field disappear

### ISSUE THREAD

**Issue by Dangerous-Mind** [SharePoint/sp-dev-docs#1627]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

List view should show user fields.

#### Observed Behavior

In modern view, the fields "Modified By", "Created By" and any other user column existing on the list it shows for some seconds then disappear.

The JavaScript console return the following errors:
Error: AppContext not found.
    at Object.r [as throwError] (livepersonacard_full_56767498e5cd126d36c0.js:16)
    at Object.r [as getSingleton] (livepersonacard_full_56767498e5cd126d36c0.js:21)
    at n.get (livepersonacard_full_56767498e5cd126d36c0.js:29)
    at n.value (livepersonacard_full_56767498e5cd126d36c0.js:21)
    at n.render (livepersonacard_full_56767498e5cd126d36c0.js:29)
    at c (react-mini-fc23d3bb.js:1)
    at beginWork (react-mini-fc23d3bb.js:1)
    at t (react-mini-fc23d3bb.js:1)
    at i (react-mini-fc23d3bb.js:1)
    at o (react-mini-fc23d3bb.js:1)

#### Steps to Reproduce

Create a user on SharePoint Online **"without a subscription and without email**".
Create a list.
Add a item to the list with this new user.
In modern view the list view shows the people field for some seconds then they disappear.

I think this is connected with the previous problem:
In CSOM calls inside apps when getting this user values it returns a empty user property (FieldUserValue) (login and email are empty but ID is filled).
This problem started some weeks ago.

**Comment by Dangerous-Mind** [comment]
The workaround is assign a license to the user.
The email address will appear in the delve profile. 
Then you can remove the license and the problem will be solved for that user.

There are other problems that will happen related to this lack of email in the profile.

**Comment by russgove** [comment]
Hi, 
Related to this-- I have test accounts i used for on-prem testing wit no email accounts. They were migrated to O365.

If i have a list (lets say 'SOxControls")  with a user column ('SOxControlOwner')  the following query fails with a 500  if my test user is in the SOxControlOwner field:
https://tenant.sharepoint.com/sites/SOxTest/_api/web/Lists/getByTitle('SOxControls')/Items?$select=Title,SOxControlOwner/Title,SOxControlOwner/EMail&$expand=SOxControlOwner

It works if the test user is not in the SOxControlOwner field.  I would hope that the query return null or an empty string as the eMail .

Interestingly, If I add SOxControlOwner to a sharepoint group, and then request his email by querying the group and expanding it's users like this:

https://tenant.sharepoint.com/sites/SOxTest/_api/Web/SiteGroups/GetById(198)?$select=Title,Users/Title,Users/Email&$expand=Users

It returns an empty string as the email. So the behavior is inconsistent.
Russell
