### ISSUE TITLE
Visual Studio njsproj fails to build when there are spaces in the project path

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#163]
#### Category

[ ] Question
[ ] Typo
[X] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

Visual Studio Successfully Builds SPFx Client Side Web Part project if you have a space in any of the folders in the file path to the project.
#### Observed Behavior

If you have a space in any of the folders in the file path to the project you get an error when trying to build the project.  

Example file path that throws the error:  C:\vso\SPFx Hero Demos\src\mini-crm

Error 1:

Description: The command "CMD.EXE /c node C:\vso\SPFx Hero Demos\src\mini-crm\node_modules\@microsodr\npmx\lib\gulp2vs.js" exited with code 1.  
File: mini-crm.njsproj
Line: 25

Error 2:

Description: Cannot find module "c:\vso\SPFx'
File: EXEC
Line: 0

If you tell VS to continue and run the last build it runs gulp serve and the browser opens and you can work with the Web Part.
#### Steps to Reproduce

Create a directory with a space in the name.  Change to the directory.  Create SPFx Client Side Web Part with Yo.  Open in Visual Studio.  Press F5.

**Comment by patmill** [comment]
Given the next bug is "doesn't work when a space does not exist", I'm going to close these two and use the first bug to track.

**Comment by TBag** [comment]
@patmill Not sure if you noticed it or not, but the errors are slightly different when you have a space and when you do not.

**Comment by patmill** [comment]
I've made an explicit note in the other bug to make sure this is checked.  Thanks Todd.

**Comment by TBag** [comment]
@patmill Cool.  Sounds good.

**Comment by pgonzal** [comment]
I am reopening this bug because I believe the issue is unrelated to the other bug.  The problem is that the "cmd /c" is not properly quoting the path.  The workaround would be to change the line to this:

```xml
    <Exec Command="node.exe &quot;$(MSBuildThisFileDirectory)\node_modules\@microsoft\npmx-lib\lib\gulp2vs.js&quot;" />
```

I'll see if we can include this fix in the next release.  FYI the "gulp2vs.js" script has now been released; to use it, you need to run "npm install --save-dev @microsoft/npmx-lib" in your project folder.
