### ISSUE TITLE
Can we change language preferences  using Javascript , Pnp js  in SharePoint Online.

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1636]
Can we change language preferences  using Javascript , Pnp js  in SharePoint Online.
How much time does it take to reflect the changes

Basically i need to a dropdown where i can list the languages . User selects a language and then it will reflect on the page .

**Comment by koltyakov** [comment]
Hi @harshdamania, 

Could you please detail what kind of action are you going to achieve with the code on the page? Please just describe an equivalent of manual actions.

If you're are talking about browser language (settings) which affects on what localization should be shown, I'm afraid this is not possible via JavaScript due security limitations.

For variations, should not it be just as easy as changing the URL (window.location.href = `url for other lang`)?

**Comment by harshdamania** [comment]
We use to have this option in previous versions of SharePoint where when a user clicks on his profile , user has the option to change the display language based on the language packs available.Once the user changes the language, for example the default language was English and now user changed it to Danish.
So sharepoint default lables like List setting , webpart header changes and it gets reflected.
 
This option is not available in SharePoint Online, also just for changing display language user has to go through certain steps, this irritates the user : https://support.office.com/en-us/article/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7

As the user doesnt want to update the language in userprofile , just change the display language for that time.

I hope this explains the issue.

**Comment by koltyakov** [comment]
Yeah, make sense. Good question. Not sure, that there is another way than changing profile languages.

Those profile settings mentioned above can be changed with PnPjs though.

![image](https://user-images.githubusercontent.com/7816483/38659862-e7081eb4-3e33-11e8-9846-25fc3b070397.png)

```typescript
// Gets a user profile MUILanguages properties
pnp.sp.web.currentUser.select('LoginName').get()
  .then(user => {
   return pnp.sp.profiles
    .getUserProfilePropertyFor(user.LoginName, 'SPS-MUILanguages');
  })
  .then(console.log);
```

```typescript
// Updates a user profile MUILanguages properties
pnp.sp.web.currentUser.select('LoginName').get()
  .then(user => {
    return pnp.sp.profiles
      .setSingleValueProfileProperty(user.LoginName, 'SPS-MUILanguages', 'de-DE,en-US');
  })
  .then(console.log);
```

Unfortunately, updating `SPS-MUILanguages` doesn't immediately effects in the UI. For me, it takes a couple of minutes. Maybe somebody else knows the better approach?

**Comment by MartinLaplante** [comment]
It's possible, our product does it, but it can take several minutes for it to take effect.  I see Andrew Koltyakov has already answered the code for doing it. It is waiting for a low-priority timer job to synchronize the user profile setting with all the site collections.  Today it was quick, other times it was as long as 6 minutes.

I can't share how we do it instantly in code, but I can share a trick that power users can use to change their language instantly.  If your profile language is blank, then SharePoint will use the browser language to determine the UI language.
[Details here](http://blog.icefire.ca/post/sharepoint-online-language-settings-and-the-instant-toggle-trick)

**Comment by koltyakov** [comment]
@MartinLaplante, thank you for some insides and sharing the great article! How my following comment won't affect your product success.

So, yes, a timer job updates UIL in site collections for the settings to take place.
With corresponding permissions, we can update it instantly with the code. For site collection admin:

```typescript
// Gets a user profile MUILanguages properties
pnp.sp.web.siteUserInfoList.items
  .getById(_spPageContextInfo.userId)
  .select('MUILanguages')
  .get().then(console.log);

// Updates a user profile MUILanguages properties
pnp.sp.web.siteUserInfoList.items
  .getById(_spPageContextInfo.userId)
  .update({
  })
  .then(console.log);
```

Profile props probably should be updated to avoid syncing back with after timer job next run.

User information list can be updated with an account with corresponding permissions. With the desire and necessity, it can be an Azure Function method (with AAD auth validation) which updates users UIL's item instantly on demand.

Could be a more elegant way but secure Azure Function with elevated permissions was the first thing which came to me.

**Comment by harshdamania** [comment]
Can we access the service?
