### ISSUE TITLE
AadHttpClient and MSGraphClient using the token of the previous user when switching users 

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1639]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When you have a web part which makes use of the `AadHttpClient` or `MSGraphClient`, they both use the token of the previous user if you switched users in the same browser/session.

#### Observed Behavior

When I log in with my personal account and go to a page with a web part which uses the `AadHttpClient` or `MSGraphClient`, I get the following result:

<img width="739" alt="screenshot 2018-04-11 20 15 15" src="https://user-images.githubusercontent.com/2900833/38635284-2ab1099c-3dc5-11e8-9f2b-5bd61f34e9e9.png">

When I log out and use one of my test accounts, go back to the page, I see the following:

<img width="733" alt="screenshot 2018-04-11 20 17 58" src="https://user-images.githubusercontent.com/2900833/38635381-763a964e-3dc5-11e8-9fe2-dd5ea8cdecbe.png">

The call to the MS Graph uses the token which was fetched with my previous user. The token was not deleted because the session in my browser was still open and there is no ID check in adal.js it seems.

#### Steps to Reproduce

- Create a web part that makes use of the MS Graph, here is a sample of the component I've created:

```TypeScript
import * as React from 'react';
import styles from './AdalIssue.module.scss';
import { IAdalIssueProps } from './IAdalIssueProps';
import { escape } from '@microsoft/sp-lodash-subset';
import { MSGraphClient } from "@microsoft/sp-client-preview";

export interface IAdalIssueState {
  displayName: string;
}

export default class AdalIssue extends React.Component<IAdalIssueProps, IAdalIssueState> {
  constructor(props: IAdalIssueProps) {
    super(props);

    this.state = {
      displayName: null
    };
  }


  public componentDidMount(): void {
    const graphClient: MSGraphClient = this.props.context.serviceScope.consume(
      MSGraphClient.serviceKey
    );

    graphClient.api("me").version("v1.0").get((err, res) => {
      this.setState({
        displayName: res.displayName
      });
    });
  }

  public render(): React.ReactElement<IAdalIssueProps> {
    return (
      <div className={ styles.adalIssue }>
        <div className={ styles.container }>
          <div className={ styles.row }>
            <div className={ styles.column }>
              <p className={ styles.title }>SharePoint {this.props.context.pageContext.user.displayName}!</p>
              <p className={ styles.title }>MS Graph {this.state.displayName}!</p>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
```

- Load the web part with **user A**
- Sign out, and sign back in with **user B**
- Go to the same page and you will see two different names

**Comment by wictorwilen** [comment]
That's an MSAL issue right, since they store/cache everything in the application cache of the browser

**Comment by pheemery2** [comment]
I'm still having this issue, August 2019. I use the AadHttpClient to connect to my 'secure' web api from an SPFx web part. When logging out, logging in with a different user in the same tab, the ClaimsPrincipal server side is still the one of the previous user ! Clearing the sessionStorage in the browser is an ugly workaround, but works... I don't want to clear the sessionStorage in the componentDidMount of my web parts (which would also work).

Any update on this bug ? @VesaJuvonen @andrewconnell  :)

**Comment by applekajui6** [comment]
It is showing error for import { MSGraphClient } from "@microsoft/sp-client-preview"; statement

**Comment by andrewconnell** [comment]
That's because that library is no longer applicable. Please see the docs for correct usage.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph

**Comment by applekajui6** [comment]
I have used the code which you have provided in the link but while approving the permissions in API Management of SP Admin Center ... I am getting HTTP 400 Correlation ID error.. how can we resolve this?

**Comment by andrewconnell** [comment]
@applekajui6 What you describe is not related to this issue. Please open a new issue.

**Comment by patmill** [comment]
Missed closing this one previously.
