### ISSUE TITLE
Visual Studio Cannot Build Projects When A Space Does Not Exist In Project Folder File Path

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#164]
#### Category
[ ] Question
[ ] Typo
[X] Mistake
[ ] Additional article idea

#### Expected or Desired Behavior
Visual Studio Successfully Builds SPFx Client Side Web Part project if you do not have a space in any of the folders in the file path to the project.

#### Observed Behavior
If you do not have a space in any of the folders in the file path to the project you get an error when trying to build the project.  

Example file path that throws the error:  C:\vso\SPFx-Hero-Demos\src\mini-crm

Error 1:

Description: The command "CMD.EXE /c node C:\vso\SPFx-Hero-Demos\src\mini-crm\\node_modules\@microsodr\npmx\lib\gulp2vs.js" exited with code 1.  
File: mini-crm.njsproj
Line: 25

Error 2:

Description: Cannot find module 'C:\vso\SPFx-Hero-Demos\src\mini-crm\\node_modules\@microsodr\npmx\lib\gulp2vs.js'
File: EXEC
Line: 0

If you tell VS to continue and run the last build it runs gulp serve and the browser opens and you can work with the Web Part.

#### Steps to Reproduce
Create a directory without a space in the name.  Change to the directory.  Create SPFx Client Side Web Part with Yo.  Open in Visual Studio.  Press F5.

**Comment by patmill** [comment]
Closing these two.  There is an issue with VS that we are working with the VS team on.  I'll keep the first bug to track this.
