### ISSUE TITLE
When using AadHttpClient or MSGraphClient in multiple web parts on the same page it causes token fetch issues 

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#1640]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the `AadHttpClient` or `MSGraphClient` in multiple web part on the same page, it would be great if the token fetching works seamlessly.

#### Observed Behavior

When loading multiple web parts on the same page which make use of the `AadHttpClient` or `MSGraphClient`, it causes issues when fetching the access token on the first try. Here you see a sample of three web parts which are using the `MSGraphClient`. When I do an initial page load (token not yet in sessionStorage), only one will retrieve the token, the two others fail:

<img width="989" alt="screenshot 2018-04-11 20 35 34" src="https://user-images.githubusercontent.com/2900833/38636500-a7769552-3dc8-11e8-8ae9-310f6bc9f59b.png">

Above screenshot is in Chrome. When I load it in Firefox, all three web parts fail:

<img width="981" alt="screenshot 2018-04-11 20 43 45" src="https://user-images.githubusercontent.com/2900833/38636627-0d28b9ac-3dc9-11e8-93d5-315b11567c24.png">

When refreshing the page, all is good because the token is cached.

**Should be impossible**

```
Error: Should be impossible.
Stack trace:
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._loginUser/<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:36172
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._loginUser/</<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:35438
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._startLogin/this._displayCallHandler@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:34984
displayCall@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:34827
[6]/i</i.prototype.login@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/0.sp-http-adal_4a41848c866052caa755.js:3:3670
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._startLogin@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:35025
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._loginUser/<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:35405
```

<img width="1108" alt="screenshot 2018-04-11 20 29 08" src="https://user-images.githubusercontent.com/2900833/38636847-aef46f56-3dc9-11e8-9370-c43db0f04260.png">

**Window closed without authenticating**

```
Error: Login popup failed to redirect to the designated redirect uri.
Stack trace:
__WEBPACK_AMD_DEFINE_RESULT__</</ge</e.prototype._waitForWindowToClose/</s<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-23.011/sp-pages-assembly_en-us_325b8f8982f9db16bb747bf1b7651f15.js:688:36475
RecentlyUsedDocuments.tsx:50:10
```

<img width="1084" alt="screenshot 2018-04-11 20 49 13" src="https://user-images.githubusercontent.com/2900833/38636883-d060a902-3dc9-11e8-9b37-bc6af185b577.png">

#### Steps to Reproduce

- Add multiple web parts to a page which will do a call to fetch an access token.

**Comment by StefanWaalderbos** [comment]
Some news/progress on this for us important issue?

**Comment by lahuey** [comment]
The original issue has been fixed already. We're working on a fix to prevent issues with multiple token requests. I'll update this thread when the fix has been rolled out.

**Comment by StefanWaalderbos** [comment]
Thank you lahuey. We looking forward to this as it is a issue for our product in development at this time.

**Comment by BraunJonathan** [comment]
That's a good news !
We looking forward to this fix too, as we are using 4 or 5 custom webparts with MSGraphClient on the same page and having all working at the same time is a nightmare right now !!

**Comment by patmill** [comment]
Book keeping - this was fixed a long time ago.
