### ISSUE TITLE
yo generator should add dev dependency for onprem webpart

### ISSUE THREAD

**Issue by sabitertan** [SharePoint/sp-dev-docs#1641]
On-prem yo generators should set dev dependency for typescript@2.2.2 (which is bundled on-prem SPFx)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This article is around getting started with SPFx development with SharePoint Online, so not sure on the location of the comment. If you have a generic issue around SPFx usage in on-premises, please report the issue directly at https://github.com/SharePoint/sp-dev-docs/issues. Thanks.
