### ISSUE TITLE
Use cases and differences between web parts and extensions

### ISSUE THREAD

**Issue by mcraiha** [SharePoint/sp-dev-docs#1646]
Would it be possible to get short "in a nutshell" section to the documentation that explains what are the use cases for web parts and extensions? It could also explain what are the differences between those two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f02c78f-11e2-c9b9-ec7c-191e6e55caa8
* Version Independent ID: 4ed11eb8-a57e-d719-e0e5-95cdaa863b87
* Content: [Overview of the SharePoint Framework (SPFx)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)
* Content Source: [docs/spfx/sharepoint-framework-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-framework-overview.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Each already has their own section in the docs (see left-hand nav as each is in top-level node)... each one also explains what they do in just a paragraph or two. What's missing from there... what questions aren't answered?

I explain them as "Web Parts are for putting functionality on the main part of the page... Extensions are for extending the UI, like adding elements to menus, header/footer stuff & customizing an existing rendering (field controls)."
