### ISSUE TITLE
Mostly useful, but lacking spfx detail

### ISSUE THREAD

**Issue by tbithell** [SharePoint/sp-dev-docs#1650]
Please provide more detail as to how to get the spfx portion of this working.  Specifically, it is a few versions behind, so setting up the office 365 cdn and putting it there are not as straight forward as it should be.  I believe my issue is there, but I'm not sure.  Everything says it runs fine. I'd really like to confirm that this is all working properly.  Also, for this part, "The provisioning template adds a custom action to a solution. The ClientSideComponentId is associated with the Regions Footer Application Customizer that you provisioned earlier. If you run this demo with your own SPFx solution, change the ClientSideComponentId and optionally the ClientSideComponentProperties attribute values in the XML."  Please explain where to find that Id, I assumed that it was the app product ID, but I have no way to be sure.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Build a complete SharePoint site design using the PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
To your point about the CDN, you'll need to have this setup ahead of time. It's assumed that was already setup. More details on the O365 CDN can be found here: https://docs.microsoft.com/sharepoint/dev/general-development/office-365-cdn

To your question on the **ClientSideComponentId**, that's the ID of the component & found it the component manifest file (typically found next to the code file for the component named **.manifest.json**).
