### ISSUE TITLE
Back to Basics

### ISSUE THREAD

**Issue by jsarpkaya** [SharePoint/sp-dev-docs#1652]
It would be very helpful to have a link to the documentation for rolling back to default SharePoint/removing all customization in this document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20221104-c118-99fd-8a84-9704d6c51e53
* Version Independent ID: 4f60a86f-a539-c57c-c29e-3b7cd189af13
* Content: [Master pages, the Master Page Gallery, and page layouts in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/master-pages-the-master-page-gallery-and-page-layouts-in-sharepoint)
* Content Source: [docs/general-development/master-pages-the-master-page-gallery-and-page-layouts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/master-pages-the-master-page-gallery-and-page-layouts-in-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not clear... as in referencing an existing page? I'm not aware of an existing page that demonstrates this...

It's basically "undo the customizations you did"...
