### ISSUE TITLE
Web Part / Application Customizer content should automatically wrapped with style sheet class 

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1655]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I develop a web part I always have to specify a container class for the web part. Can we please move this container class one level higher on the web part.
This style sheet class should be autogenerated by SPFx and wrap all custom CSS too. It might solve problems.

#### Observed Behavior
**Observation 1 - Web Part**
I need to use a global scoped CSS class, which I actually shouldn't use, but I don't like to rewrite a third party component completely. To make sure it will be scoped only to the web part I have to do this:

```css
.myContainer{
    :global{
        .myCustomThirdPartyClass{
           background-color: lime;
        }
    }
}
```

The same thing happens with imports too. If SPFx automatically wraps the content in a web part specific class the code gets much cleaner and more issue safe.
The following method in SASS could be used to accomplish this:

```css
// class rendered by default on the web part
.spfxWebPartSpecificClass{
   @import 'src/webparts/mywebpart.module.css
}
```

The web part CSS file only needs to be the following:

```css
// DO NOT CSS MODULIZE MY WEB PART  
:global{
    .myCustomThirdPartyClass{
        background-color: lime;
    }
}
```

The resulting CSS will always be the following code:  
  
```
.spfxWebPartSpecificClass_adj3736 .myCustomThirdPartyClass{
    background-color: lime
}  

```

This way it is safe to inject 'global' CSS but the use of the CSS will be always limited only to the component. This way it would be thousand times safer to limit web parts limit CSS only to a component on the page.

**Observation 2: Extensions**
Basically, when you write an extension you can inject all global scoped CSS in there. You shouldn't but you can an nothing really blocks you.
The previously described pattern can also be applied for Application Customizers. When those components added to the page via DOM injection auto-wrap all the CSS and add a default surrounding CSS class. The change that style sheets injected doesn't have any effect on the overall page.

**Observation 3: CSS with just global style won't rendered until you have a dummy container
When your web part only has global styles include it won't get rendered the in observation described on 'Observation 1' will reduce the risk of global scope style and will always render the CSS. This is required if only third-party CSS will be used. For example image slider, custom media player, <insert component here>

**Observation 4: Classical CSS handling but not it should be component driven-handling**
The CSS handling in web parts and headers follows a more traditional CSS approach rather than component driven and from my perspective, the isolation of CSS is not there where it should be right now.
This might be solvable by the recommendations above. A look at the future and the use of web components all CSS injected by a web component is scoped only to the HTML snippet it provides and doesn't affect the overall CSS on the page.
Especially this will apply when other frameworks then react will be used such as Angular, Angular Elements, VueJS, <insert the next great framework here>

**Observation 5: type-safe CSS class names are not that important**
CSS modules provide a lot of benefits that are not under the control of a web developer at all. For example, generate truly unique class names. As a matter of fact to have type-safe CSS class names especially in SPFx is from my perspective a bit overrated. This is because CSS is NOT a programming language it is the definition of output styles. This means that you will never get an exception by CSS that blocks other code or maybe blocks the page from loading.
If a CSS class is not applied correctly it won't be rendered but you will never see an exception "Object is null or undefined".  
Personally, I think in future the landscape of foreign web components we want to include in our web parts will enlarge and at this time a generic way on how to deal with those Stylesheets should be found.
It is almost great but could even be better for more than just web parts but having a solution that extends to Application Customiser / Extensions.

I hope I haven't overlooked something here but this is anyway open to discussion. 😀 IMO

**Comment by VesaJuvonen** [comment]
Thanks @StfBauer for this one and sorry for the massive delay for more concreate acknowledgement. This is good input for our UX team and we'll absolutely bypass the model and suggestion. Super valuable input for future considerations. As we cannot really react on this directly from GitHub - We'll close this from here and keep on pushing things internally.
