### ISSUE TITLE
woff2 files for fonts not supported

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#1657]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
woff2 files to be bundled properly
#### Observed Behavior
Getting the following error message because woff2 files are not being bundled as part of the webpack transpiling sequence.
```
/node_modules/css-loader?{"minimize":true}!./lib/webparts/weather/components/Weather.module.css
Module not found: Error: Can't resolve '../fonts/WeatherIcons.woff2' in 'C:\sources\github\weather\lib\webparts\weather\components'
resolve '../fonts/WeatherIcons.woff2' in 'C:\sources\github\weather\lib\webparts\weather\components'
  using description file: C:\sources\github\weather\package.json (relative path: ./lib/webparts/weather/components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\sources\github\weather\package.json (relative path: ./lib/webparts/weather/components)
    using description file: C:\sources\github\weather\package.json (relative path: ./lib/webparts/weather/fonts/WeatherIcons.woff2)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\sources\github\weather\lib\webparts\weather\fonts\WeatherIcons.woff2 doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\sources\github\weather\lib\webparts\weather\fonts\WeatherIcons.woff2.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\sources\github\weather\lib\webparts\weather\fonts\WeatherIcons.woff2.json doesn't exist
      as directory
        C:\sources\github\weather\lib\webparts\weather\fonts\WeatherIcons.woff2 doesn't exist
```

#### Steps to Reproduce
Start a new webpart project with 1.4.1, online.
`npm i open-weather-icons -S`
copy the fonts folder front the npm module to webpart/webpartname/fonts  (they don't provide a variable to set the relative path)
add this line to the webpartname.module.scss file
` @import '../../../../node_modules/open-weather-icons/scss/open-weather-icons.scss';`
gulp serve, you'll get the error

**Comment by baywet** [comment]
I'd like to add to that that otf files are not supported as well...

**Comment by priteshmohanty** [comment]
I am also facing the same issue, and would like to know if there is a way to bundle woff2 files properly.

I was able to bundle and copy the woff2 file to the lib folder by adding the below configuation to the copy-static-assets.json file
{
  "includeExtensions": [
    "woff2"
  ]
}
(https://sharepoint.stackexchange.com/questions/244065/spfx-question-is-it-possible-to-include-a-custom-font-reference-by-extending-the)

However after that i get below error: -
./lib/webparts/fonts/instaquote-s/instaquote-sicks-and-stones.woff2
Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by MartinWhiteDAZN** [comment]
I too have the same experience as @priteshmohanty

**Comment by MartinWhiteDAZN** [comment]
@StfBauer to the rescue...
https://n8d.at/how-to-bundle-and-use-custom-web-fonts-in-spfx-projects/

Just adding to the gulpfile.js was enough to prevent the error.

**Comment by StfBauer** [comment]
@MartinWhiteDAZN thank you for pointing to my blog post. Out of the box workbench, for now, do not consider any custom font file in the package.

There are only two alternatives: 
- Load custom font from CDN
- Bundle in custom font as described in the blog post.
