### ISSUE TITLE
What is the purpose of --save when installation of any package

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1659]
My assumption is that --save is just for running locally in development case.
But when we package the solution, i.e deploy is to prod , the package which we installed using --save is not taken ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Nasicus** [comment]
No. `--save` comes from NPM and means that the package you're about to install well be added to the `package.json`. If you do it without it, the package will just be installed, but not be added to the `package.json`.

**Comment by harshdamania** [comment]
So if I add a package without - - save and now I move the solution to other environment and run npm install, so in that case the packages will not be installed right? 
Npm - - save helps me to install all packages

**Comment by waldekmastykarz** [comment]
That was the case indeed with older versions of npm. Starting from v5 (which is the default for the current version of Node - v8), npm automatically saves each package in the package.json file and the generated package-lock.json file.

**Comment by VesaJuvonen** [comment]
Docs updated accordingly, so closing this one as there's no mention of --save anymore as they have been updated to match npm v5 version.

**Comment by mikewaretena** [comment]
Hello there, not sure if the version Vesa mentioned hasn't made it's way to the public, but the section: "Install jQuery and jQuery UI NPM Packages", still has --save in most steps. Maybe worth checking.
