### ISSUE TITLE
Shipping the package

### ISSUE THREAD

**Issue by cveld** [SharePoint/sp-dev-docs#1663]
Please call out the commands that are required for creating a package for shipping, i.e.
gulp bundle --ship
gulp package-solution --ship

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bigpix2000** [comment]
There appears to be a missing step somewhere OR I have a bug on my Developer tenant site.  Following the "prep" to use the app Catalog, the most current push of the framework appears to deploy but never show up as an up to select in the "add an App" area.  Bug or missed step?  (at least a reference to the prep and "base requirements" need to be here in the docs. thanks

**Comment by bigpix2000** [comment]
Update ... I was missing */CLIENTSIDEASSETS from the CDN origin list ... docs should say to "make sure this is there."  somewhere ... Will look at the docs and recommend a spot for it as soon as I can unless you have a place thanks!

**Comment by VesaJuvonen** [comment]
This is the part 3 of the tutorial series and explains how to test the web part in a site from localhost. Step 4 in this tutorial series is then explaining how to get the package ready for production usage - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn. This also includes the requirements around the CDN origins. We will add notes on the CLIENTSIDEASSETS on that article. That's, unfortunately, missing from those tenants which used CDN before this capability was enabled.
