### ISSUE TITLE
How to package common code between multiple webparts to a separate bundle?

### ISSUE THREAD

**Issue by artokai** [SharePoint/sp-dev-docs#167]
#### Category

[X] Question
[ ] Typo
[ ] Mistake
[ ] Additional article idea
#### Expected or Desired Behavior

The Wiki contains instructions on how to [share a library among multiple webparts](https://github.com/SharePoint/sp-dev-docs/wiki/Add-an-external-library-to-a-web-part#sharing-a-library-among-multiple-webparts) in order to reduce the resulting bundle sizes. However this approach seems to work only for external libraries. 

Is it somehow possible to generate a separate bundle for code, that is shared among multiple webparts but which is not written as an external library?

If this is not currently possible, then could you consider supporting it in the future. Perhaps the yeoman generator could support adding "internal libraries" to the project in addition to adding just new webparts.
#### Example

Currently if a project has the following structure where both webparts import the `veryLargeModule`, then the end result is two large bundles (`webpartOne.bundle.js` and `webpartTwo.bundle.js`) because the common code is copied to both of those bundles.

If the `veryLargeModule` could somehow be bundled separately, the end result would be three separate bundles (`webpartOne.bundle.js`, `webpartTwo.bundle.js` and `veryLargeModule.bundle.js`) and the total size of those bundles would be smaller.

```
src/
|-- libraries/
|   +--veryLargeModule/
|       +--veryLargeModule.ts
+-- webparts/
     |--webpartOne/
     |  +--WebpartOneWebpart.ts
     +--webpartTwo/
       +--WebpartTwoWebpart.ts

```
#### Workaround

As a workaround the common code can of course be written as a separate npm module which is then added to the `externals` section of the `config.json`.  This approach will however require quite a bit of extra work as both of these projects (shared code and the webparts) need to built and packaged separately.

**Comment by patmill** [comment]
@artokai - have you gone down the path of a single bundle for the group of webparts?  Ie, one bundle contains the source code for a set of webparts.

You are correct though that you don't want to bundle the code into your webpart.  We have hit this issue as well internally, with webparts that have a file picker bundling that code into the webpart itself, causing them to all increase in size.  The easiest solution was to put the various webparts into a single bundle, but that might not be the right solution for you.  Your workaround is valid.

Digging into the actual enhacement / feature request, would it something along the lines of 
Add library sub project
contents of the subproject gets its own bundle
when you deploy, this bundle gets deployed separately, and is loaded as if it was an external library?

One slightly confusing thing here (in my mind), is the question of "how do I have multiple web parts leverage this"?  As soon as I create a new project and want to use the library, don't I need to consume it as if it was an external npm module?  (I could be missing something here)

**Comment by artokai** [comment]
Thanks for the suggestion @patmill! 

Packaging all of the related webparts in the same bundle might actually be a better way to handle this than extracting all shared code to a separate npm package. Does the spfx-tooling and its configuration files already support this or do you need to create custom build steps to do it?

And your understanding about the feature request is the same as I had in my mind. After the Library sub-project would have been added, it would then be compiled to a separate bundle. This would allow us to place code, that is shared between various webparts, to the library subproject where it would not bloat the size of all of those individual webpart bundles.

I confess that I did not think very much about how these internal libraries would then be referenced from the webpart side. From the developer perspective it would be nice if we could just import them using the relative path of the module. This would allow the IDE to find the module and for example Intellisense-features would just work.  Unfortunately I'm not sure how and if the webpack could be configured to bundle these "internal libraries" to separate bundles.

**Comment by patmill** [comment]
Yes - if you run the yo generator again in the same root folder, you can add an additional webpart, and it will create the webpart manifest, etc.

One caveat though - it doesn't let you chose a different framework for the additional webparts at the moment.

@waldekmastykarz has a blog post on this (although I think it is based on Drop 1.  The latest drop fixes the issues around mystrings) - https://blog.mastykarz.nl/add-second-web-part-sharepoint-framework-project/

**Comment by artokai** [comment]
I've actually already added two separate webparts to the same project, but this results in two separate JavaScript bundles (one for each webpart). I haven't yet figured out how to combine multiple webparts together in the same JavaScript bundle.

**Comment by waldekmastykarz** [comment]
@patmill I think there are two scenarios we could distinguish:

1. Multiple Web Parts in the same project reuse some code. A library bundle stored in the same project as Web Parts, that could be referenced as an external resource in the different Web Parts would be a great solution here.
1. Multiple Web Parts from multiple projects reuse some code. I guess that in this case the preferable way would be to have the shared code deployed to a central location and refer it from there as an external module. If we used it as an npm package then it would be included in the bundle by default, wouldn't it? Developers would need to take care of typings which they could install from a central location to their project.

How does that sound?

**Comment by artokai** [comment]
I see that @waldekmastykarz has solved this issue in his [blog post](https://blog.mastykarz.nl/dll-code-sharepoint-framework/). It would be great if the spfx would support this kind of thing natively by allowing users to add internal libraries to the project via yeoman.

Perhaps webpacks's CommonsChunkPlugin could also somehow be used to split the internal libraries to separate bundles. That might remove the need for generating and updating a separate typings-file for the internal library (as described in Waldek's blog post).

**Comment by patmill** [comment]
Today we allow a single solution to have multiple components / webparts.  This is the best way to have code shared.  If you need the idea of manifests, and not just a solution that shares all of your code, see this user voice entry - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/19224202-add-support-for-library-packages-in-the-sharepoint
