### ISSUE TITLE
Missing docs for RenderExtendedListFormData

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#1673]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x ] Additional article idea

When I doulble click an item in  a modern listview , I see that sharepoint calls the api at  https://temant.sharepoint.com/sites/SOxTest/_api/web/GetList(@v1)/RenderExtendedListFormData(itemId=1,formId='editform',mode='2',options=7)?@v1=%27%2Fsites%2FSOxTest%2FLists%2FSOxControls%27

I cannot find any documentation on that.

Please provide documentation

**Comment by semopz** [comment]
It now seems to default to options=15. Not quite sure why or for what purpose. Does anyone have any insight?

**Comment by Rafaelki** [comment]
I think it is a bitwise combination. 15 = ExcludeListSchema & IncludeAttachments & IncludeListViewData & IncludeAppendOnlyData.

https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt684056%28v%3doffice.15%29

**Comment by VesaJuvonen** [comment]
There are unfortunately no plans to provide further documentation and details on these APIs, so closing this issue for now. Not necessarily the best situation, but better to have clear answer for this.
