### ISSUE TITLE
Error with "Use custom dialog boxes with SharePoint Framework Extensions" tutorial

### ISSUE THREAD

**Issue by sfmp** [SharePoint/sp-dev-docs#1675]
When testing the dialog and clicking "Load debug scripts" as prompted am getting the below error.

***Error loading debug manifests.
***Error loading debug script. Ensure the server is running and the "debugManifestsFile" parameter URL is correct.
Error: Script error for "https://localhost:4321/temp/manifests.js" http://requirejs.org/docs/errors.html#scripterror

**Comment by VesaJuvonen** [comment]
That seems to imply that your localhost is not running and that your serve.json file is not correct, so would double check those. Can you share the content of those files as currently there's really not enough information to assist in the root cause?

**Comment by sfmp** [comment]
Thanks for the response.  There was an incorrect reference in the json file

**Comment by mubash7** [comment]
I am getting the same error. Could you please point out where was the incorrect reference?

**Comment by mubash7** [comment]
Further info - the error is occurring on Edge browser. Works fine on IE and chrome.

**Comment by sfmp** [comment]
In the serve.json file I had to remove the $schema reference at the top.

{
  **"$schema": "https://dev.office.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,**
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://abfoods.sharepoint.com/sites/ABMauri/publishingsite/Documents/Forms/AllItems.aspx",
      "customActions": {
        "7d00d36d-6d8b-4efa-b850-d597e7a05ad0": {
          "location": "ClientSideExtension.ListViewCommandSet.CommandBar",
          "properties": {
            "sampleTextOne": "One item is selected in the list",
            "sampleTextTwo": "This command is always visible."
          }
        }
      }
    }
  }
}

**Comment by abashutosh** [comment]
Hi,
I'm also getting this error when I use Gulp Serve which opens IE Edge browser as default one.
**However, when I copy the URL and try it on Firefox, it works perfectly fine.**
Something messing up in Edge only I believe.

**Comment by MeenaMakwana** [comment]
In order to resolve this issue, I have just opened the (https://localhost:4321/temp/manifests.js) in chrome and made it not secure for test. During this I have kept my command prompt open with build option i.e. gulp serve --nobrowser . You will able to see all the request made during this test in command prompt.

![test issue](https://user-images.githubusercontent.com/42757639/48163587-ec81a200-e344-11e8-8cf2-d6e392a04d8d.PNG)

**Comment by andrewconnell** [comment]
@abashutosh / @MeenaMakwana If you're still having an issue, can you open a new issue with additional detail? The issue that @sfmp originally posted is resolved according to his comment so your issue, if still present, is different and needs different context. Please make sure to include as much detail as possible (don't just reference this issue). Thanks!
