### ISSUE TITLE
Support of "read only" view in Edge (and other browsers)

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#1676]
#### Category
- [x] Question

#### Expected or Desired Behavior

On a modern page I would expect to be able to click the "Reading view" button in Edge to see just the article content. This is useful for screen readers and accessibility scenarios - as well as when reading a longer piece of text.

Same goes that headlines should use `<h1>` etc.

![image](https://user-images.githubusercontent.com/51104/38857804-747552b8-422a-11e8-9145-ed681911e535.png)

#### Observed Behavior

The option is disabled in the browser due to the lack of `<article>` tags, using HTML5 tags for proper content layout would be beneficial for a "Modern" page system.

Are there any plans to have the modern page layout use proper HTML tagging like `<article>` `<section>` etc.?

**Comment by StfBauer** [comment]
Please also make sure that the [Microsoft Edge Guidelines for Reading view support](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/browser-features/reading-view) get considered and the required meta-data get exposed on the page.

The reading view also helps in case of accessibilities of the modern pages.

**Comment by wobba** [comment]
@VesaJuvonen are you aware of any thoughts around this from the PG side to make modern more accessible and conform to standards like WCAG 2.0?
