### ISSUE TITLE
Office fabric React- TextField or any control

### ISSUE THREAD

**Issue by jayeshvg** [SharePoint/sp-dev-docs#1677]
Why is it not possible to refer to a control(Eg., TextField) using this in it's events? What are the alternatives. 

#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Example: 
 <TextField value='Testing events'
                        autoAdjustHeight
                        resizable={ false }
                        title='Testing events'
                        maxLength={150}
 onFocus={(newValue) => {
                            this.multiline = true; //Here, this refers to the component where TextField is place and //not the TextField itself
} }
                        />
#### Expected or Desired Behavior

This within control events, should refer to the current control and not the component where control/component is placed

#### Observed Behavior

This within control events, refers to the containing control/component where current control/component is placed

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Sorry for not responding, if you are using => notation, "this" points to your current class, not the TextField component.

**Comment by jayeshvg** [comment]
Thanks :)
