### ISSUE TITLE
SharPoint Framwork with Bootstrap CSS

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#168]
#### SharPoint Framwork with Bootstrap CSS

[ ] Question
#### Expected or Desired Behavior

WebPart Property Pane should load as shown below and WebPart Name should appear properly
![image](https://cloud.githubusercontent.com/assets/21008316/18336545/bd0a540c-754d-11e6-9132-67cdc1157c0b.png)
#### Observed Behavior

![image](https://cloud.githubusercontent.com/assets/21008316/18336560/d327510e-754d-11e6-817b-ef36229585c0.png)

Bootsrap css styles overlapping 
#### Steps to Reproduce

Add bootstrap.min.css in constructor 

public constructor(context: IWebPartContext) {
    super(context);
    ModuleLoader.loadCss('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css');
  }

**Comment by chakkaradeep** [comment]
While it is possible to load Bootstrap CSS with the SharePoint Framework, we highly recommend and support using Office UI Fabric to ensure the customizations customers build feel native to SharePoint. 

That said, can you test this with the latest build (Drop 5 is the latest at the time of this writing)? We use CSS namespaces and hence there shouldn't be conflicts.

**Comment by sprider** [comment]
@chakkaradeep 

Yes, it is working. closing this.
