### ISSUE TITLE
Auto Rewriting Does not seem to be working

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-docs#1680]
The automatic rewriting of assets does not seem to be working (tested on two tenants) for public or private. I have ensured that SharePoint Publishing is enabled at Site Collection and Site level. I can access the resources directly using the publiccdn.sharepointonline url.

Is my understanding correct in saying that if I have defined "*/masterpage" as a public cdn origin, then using a relative link to "masterpage/somefolder/asset.png" should cause the url to be updated to "https://publiccdn.sharepointonline.com/<tenant>.sharepoint.com/masterpage/somefolder/asset.png"? Will this work for instance on a classic wiki page? Even with the default origins, I don't see anything loading from the cdn at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad25ddeb-3ff0-d537-0e17-e3e47ce873e5
* Version Independent ID: 98bb8ce5-0825-a70c-c351-d1b9a7afd174
* Content: [Use the Office 365 content delivery network](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/office-365-cdn)
* Content Source: [docs/general-development/office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/office-365-cdn.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Automatic rewrite only works on publishing pages which are stored in the pages library. There's no automatic rewrite for classic wiki pages.
