### ISSUE TITLE
Get a checked out file after upload

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1687]
How to get a file which was just uploaded to a library where Require Check Out had been turned on
GetFileByServerRelativeUrl says file doesn't exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by aslanovsergey** [comment]
Now hesitant about this. Files were uploaded under an user account and GetFileByServerRelativeUrl request was called under Add-in authentication

**Comment by aslanovsergey** [comment]
I checked with REST and CSOM. No one can see a checked out file after initial upload except a user who did upload

**Comment by davehax** [comment]
Hi Aslan, the behaviour you've observed is expected when the user is required to check out documents to edit them and versioning is enabled (which is now the default in SharePoint Online).

In the Server Side Object Model there's a collection on the SPList object that has all these never-checked-in documents. However the name of the collection escapes me.
