### ISSUE TITLE
Modern experience APIs undocumented

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#1689]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
API's to come either under the SharePoint REST API or the Graph and to be documented, even if they are in beta.

#### Observed Behavior
As the modern experience is picking up, we have more and more customers that are asking us to build on top of it.
Things like "I'd like to see my saved for later news on my people-centric portal on the desktop", "I'd like the system to recommend me news I might be interested in", "I'd like to subscribe/follow sites, but from the news webpart..."
It appears the modern experience is leveraging 2 API's that are undocumented today:
- https://tenant.sharepoint.com/_vti_bin/homeapi.ashx/ (eg: sites/followed/add)
- https://eastus3-sphomep.svc.ms/api/v1/ (eg: sites/suggested?start=0&count=21&acronyms=true)

For the first one I can see it's under SharePoint (good'ol vti bin...), just not under the _api yet and not documented, so a bit of cleanup plus documentation would be required here. **Would it be possible to get at least a summary of what endpoints are available, payloads and supportability for this API fairly soon please?** (Dear Vesa...)

For the second one I can't see a valid point for it being on it's own:
- It's not under the SharePoint REST API or the Graph (yet another API I have to know about)
- It has a dynamic domain name that's discoverable only within a page context, the token for it is passed with the page context as well... makes it super closed

When Microsoft came out with the Graph and then with the SPFX, something was repeated many times: have a first/third party API and extensibility model that'd provide a consistant experience for developers from all sides.
**For this second api, if it's not "production ready" can you at least move it under the graph, beta and document it please?** (Dear Vesa...) I know this is a "big" request that involves engineering, documentation, and the Graph teams...

**Comment by luismanez** [comment]
Very interesting to know about it too. BTW, just pushed a new PR to the extensions repo showing how to use the "sphome.svc.ms/api/" API from code (which surely is not "supported").
https://github.com/SharePoint/sp-dev-fx-extensions/pull/126

Cheers.

PS: love your dear-vesa area @VesaJuvonen  !!! 😀

**Comment by baywet** [comment]
Here is a uservoice entry to upvote the request as request by Vesa on today's SIG call https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/34075903-api-support-for-followed-sties

**Comment by luismanez** [comment]
thanks @baywet ! voted up.

**Comment by patrickabel** [comment]
I'm using the followed-sites API currently on a few client web-parts and it, unfortunately, doesn't include modern team sites (with O365 Group) that have been followed. I would love to see the supported API include everything that we see with this undocumented endpoint.

@VesaJuvonen any updates incoming on this?

**Comment by mmsharepoint** [comment]
Vesa is on vacation but I am also curious on this.
I would also prefer this Api over the old Social.Following as it provides much better results/more attributes we might need.
@patrickabel I cannot confirm your findings. In my case the modern teamsites / Groups occur in the resukt once you follow them (on SharePoint site level) and occur as Type='Group' in the results while modern Coomunication sites occur as Type='Site' and WebTemplate='SITEPAGEPUBLISHING'

**Comment by berndverhofstadt** [comment]
There is also an API to Stop following sites:
`
/_vti_bin/homeapi.ashx/sites/followed/remove
`
as data you need to send `"https://<tenant>.sharepoint.com/sites/<site-to-unfollow>"`

**Comment by Jeeakooma** [comment]
@berndverhofstadt for the Stop call does the site address need to be assigned to a property in the body ie: body: { site: https://<tenant>.sharepoint.com/sites/<site-to-unfollow>}`?

**Comment by berndverhofstadt** [comment]
@jeeakooma no it’s just the site between quotes in the body and no curly bracesOr property name :-)

**Comment by mpowney** [comment]
FWIW, Vesa responded to the question re support for *-sphome.svc.ms API's in a tweet in December 2018 - it's something that's planned long term, but with no ETA.

https://twitter.com/vesajuvonen/status/1070233837958062080

**Comment by 2toLeadMike** [comment]
Note that `/_api/sphomeservice/context?$expand=Token` will provide both the token and the resource URL to target for working with many of these undocumented APIs.

**Comment by baywet** [comment]
Update: it seems that even though the SharePoint home experience is still pointing to exotic endpoints, the follow/unfollow stores the information at the same location as the SharePoint REST follow API now:
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/follow-content-in-sharepoint

Still a lot of endpoints are missing like suggested etc...

**Comment by justdevelopment** [comment]
As mentioned today in the SIG by Vesa, this is not looking good for official support. I've created a uservoice to get these functionalities added to an existing webservice such as Graph or the SharePoint REST Api. Please vote if you want to use these too :)

https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37531192-add-modern-webservice-api-functionality-to-support

**Comment by VesaJuvonen** [comment]
I'm closing this for now as this is more a feature request than actual issue. I do absolutely understand that we would need to have these documented, but that's not planned to happen for now until they are exposed through Microsoft Graph, which means that they will not be officially supported to be used by 3rd party developers.

Not an optimal situation, but let's ensure that we are asking them through the UserVoice and get some votes on them, so that they will be prioritized high on the internal engineering list.
