### ISSUE TITLE
Interactive properties, custom field type, saving properties

### ISSUE THREAD

**Issue by vvolodin** [SharePoint/sp-dev-docs#169]
I like the built-in property pane and we intend to use it for our app parts. However what's documented now looks very simplistic. How would I go about implementing interactive properties? A very simple example: have a drop down with all the SharePoint List names and then have another one showing the list of fields in the selected SP List.

Actually, our properties will be complicated enough to be written as a React component so having custom field with onRender solves the problem quite effortlessly, but it would be nice to have a more 'React'-like way of doing properties.

So far the saving mechanism for properties was dumping the json string to localStorage every 3 seconds which clearly has only been intended for demo purposes. What property saving mechanism should we expect to appear in the Framework?

**Comment by patmill** [comment]
So one thing to note is that each time a property is set, it refetches the property configuration.  For example, lets say you have a few properties.
1 - A "type" property that can switch between "name" and "number"
2 - A "name" property that is filled in if type == name
3 - A "number" property that is filled in if type == number

If Type is empty, you can have the property page configuration return only the type field.
When the user selects a type, the value will be stored in the webpart properties, and the configuration method will be called again.  You can now look at the type property, and either add the name or number property to the configuration.

Is that the sort of thing you are looking for?

**Comment by manishgarg1** [comment]
@vvolodin, about your last question. The web part framework does not intend to support any form of automatic saving of properties. That is really a function of the page on which the web part is inserted. The modern pages app we are building, autosaves the page at a regular interval and every time the property bag of any web part gets into a dirty state i.e. mutates. Does that answer your question?

**Comment by vvolodin** [comment]
@patmill You mean propertyPaneSettings is getting called on BaseClientSideWebPart each time any property value is changed? I don't think this is the case at the moment.

@manishgarg1 Hmmm, I'm a bit confused. What I need to do is give someone a way to add my web part to a page, change some settings and persist them so that the web part looks the same when viewed by other people in the organisation.
What purpose does saving into localStorage serves?

**Comment by manishgarg1** [comment]
@vvolodin, the sessionStorage is just a feature for the workbench during development of your web part. On real pages this feature will be owned by the page. Which as I explained above, will perform autosave. Can you please explain the scenario when you would like the webpart code to autosave to some database ?

**Comment by patmill** [comment]
@vvolodin - that's correct, propertyPaneSettings should be getting called on each property edit.  I just double checked, and that is what is happening for me.

For your other question though, persisting the webpart properties is the job of the host application.  On classic pages that will happen when you save the page, and on the (soon to be released) modern pages, it happens in the background via auto-save.  The webpart itself should never be responsible for persisting it's data - it only needs to make sure that the property bag is correct and up to data when the properties are edited.

**Comment by vvolodin** [comment]
@patmill What kind of saving mechanism will that be? How should my web part handle settings so that someone could set it up to look the same to different SharePoint users?

**Comment by patmill** [comment]
You shouldn't need to do anything (again - other than making sure that the property bag is correct).  Maybe I'm missing part of your concern though.  Are you seeing anything that makes you think serialization / deserialization is not working correctly?

**Comment by patmill** [comment]
I see.  The modern page infrastructure (rolling out now I believe, currently available to first release customers) and the classic page infrastructure handles the storage..  On classic pages it follows the previous flow where the properties are stored in a separate item (the webpart table, accessed via the LimitedWebPartManager).  On modern pages the properties are serialized as part of the page data, and stored in the current list items field (Canvas) .  You don't need to worry about anything.  In an ideal world, you wouldn't need to serialize your properties into a single value - you should be able to modify the webpart property interface for your webpart.

**Comment by manishgarg1** [comment]
Hi @vvolodin, are your questions answered ? Please let us know if there is still any confusion.
