### ISSUE TITLE
SPFx Web Part Manifest Points to 404 of Office UI Fabric Icons

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#1690]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The URL `http://o365icons.cloudapp.net` referenced on line 179 of the [client-side-web-part-manifest.schema.json](https://dev.office.com/json-schemas/spfx/client-side-web-part-manifest.schema.json) should point to: https://developer.microsoft.com/en-us/fabric#/styles/icons

#### Observed Behavior

IntelliSense documentation for the `preconfiguredEntries: [{... officeFabricIconFontName: '' }]` references a now-defunt URL: http://o365icons.cloudapp.net

**Comment by andrewconnell** [comment]
Confirmed still an issue in SPFx v1.8.0

**Comment by andikrueger** [comment]
Confirmed still an issue in SPFx v1.10.0

**Comment by andrewconnell** [comment]
Fixed in SPFx v1.11
