### ISSUE TITLE
Please have few videos links too related to access token

### ISSUE THREAD

**Issue by chintan6777** [SharePoint/sp-dev-docs#1695]
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e75f802-f01c-d319-5326-ce36804ad2be
* Version Independent ID: f5328b3d-41a7-9c98-0110-865ff4273bfc
* Content: [Create and use access tokens in provider-hosted high-trust SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm going to close this as it's not specific / actionable. Please feel free to submit a new issue with something more specific.

FWIW, access tokens aren't exclusive to SharePoint, they are used in the OAuth2 protocol which is implemented by Azure AD. You'll find a lot more details on access tokens in the Azure AD docs.
