### ISSUE TITLE
ProgressBar not working

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/sp-dev-docs#1697]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I render a Fabric ProgressIndicator without stating a percent completeness, I should get an indeterminate progress indicator with a bar running from left to right in a loop. See example on [https://developer.microsoft.com/en-us/fabric#/components/progressindicator](https://developer.microsoft.com/en-us/fabric#/components/progressindicator)

#### Observed Behavior

The moving bar is not visualized at all. Only the track that it should run in is shown.

#### Steps to Reproduce

    import * as React from "react";
    import { ProgressIndicator } from "office-ui-fabric-react/lib/ProgressIndicator";

    export class ProgressIndicatorIndeterminateExample extends React.Component<{}, {}> {
      constructor(props: {}) {
        super(props);
      }

      public render(): React.ReactElement<{}> {
        return (
          <ProgressIndicator   label="Example title"   description="Example description"   />
         );
      }
    }
![image](https://user-images.githubusercontent.com/25172917/38977589-162704cc-43b5-11e8-8a25-da698ccb0969.png)

**Comment by RoelVB** [comment]
I assume you're using an older version of the Office UI Fabric. I've observed this behavior in the past, but at has been working correctly from at least version 5.74.0.

**Comment by balle3201** [comment]
I am experience the exact same thing unfortunately... Really hope there will come a fix for this.

**Comment by RoelVB** [comment]
- What Office UI Fabric version?
- Which browser?
- On a modern of classic Sharepoint page?

**Comment by andrewconnell** [comment]
As I’m going through old open issues, I’m going to close this one, as this is related to Fabric React, it doesn’t appear to be specific to SharePoint.

Suggest if you still have this issue, post it to their repo: https://github.com/OfficeDev/office-ui-fabric-react/issues
