### ISSUE TITLE
Image Web Part in Sharepoint don't get rendered properly

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1698]
#### Category
- [x] Question

#### Expected or Desired Behavior

Images in SharePoint that was added via an Image Web Part should render like using ´figure` and `figcaption`. Right now, all images get rendered in a construct of multiple div elements, while there are semantical HTML elements available.
In case of Accessibility, the images should follow the [WAI Guidelines](https://www.w3.org/WAI/tutorials/images/complex/) provided by the W3C on complex images.

#### Observed Behavior

The following screenshot of the source code illustrates how the image will be rendered at the moment.
![screen shot 2018-04-19 at 11 33 19](https://user-images.githubusercontent.com/5503835/38983844-9fa564a4-43c5-11e8-8b7d-4901cd53b1c4.png)

**Comment by qianghuang94** [comment]
Hi @StfBauer The issue has been fixed and rolled out to PROD. thanks for contacting.

![image](https://user-images.githubusercontent.com/15025186/84878197-16bc4980-b0bc-11ea-83a9-f83a78fd9006.png)
