### ISSUE TITLE
 _spClientSidePageContext is not present on classic pages

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#170]
[X ] Question

Which means that the `(window as any)._spClientSidePageContext` workaround won't work on classic pages.

So if the SPFx webpart has to work on classic pages, the only option is to use the context object provided by the webpart which does not contain all the properties in the `_spClientSidePageContext` object yet. 

So is the idea that **all** properties in the `_spClientSidePageContext` object will be moved to the webpart context object?

![classic](https://cloud.githubusercontent.com/assets/173794/18358010/0b705e14-75eb-11e6-9a5f-6be59e3ab570.PNG)

**Comment by patmill** [comment]
Yes - that is the general approach @vman .  We're in the process of moving them over (as well as trying to standardize the context properties from the (unfortunately) different ways we generate them).  Is there a property or set of properties you are looking for in particular?  We can see what we can do in terms of prioritizing the changes.

**Comment by lahuey** [comment]
Hi vman,
_spClientSidePageContext shouldn't have been added to the modern pages and will be removed soon. However, we will give you the ability to access this information in a future API. 

Landis

**Comment by patmill** [comment]
Closing this one out.  The context should have the properties you are looking for (including full login name)
