### ISSUE TITLE
Provision sharepoint list without creating content type

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#1701]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package
In the documentation it specifically told us to create fields, add to content type, then add the content type into the list. How do I create a simple list without having to create content type first?

Also I noticed an issue with this sample, the Content Type within the provisioned list isn't actually inheriting/defaulting to the added content type (Cost Center is not exist within Content Type area in the list):
![image](https://user-images.githubusercontent.com/6864547/38989635-daacdd5c-441a-11e8-95d3-30cd88fd5588.png)

But the columns are displayed as if the column belongs locally to the list, not site column.
![image](https://user-images.githubusercontent.com/6864547/38989687-0a4e7656-441b-11e8-85a3-5597f43ed3bf.png)

Any thoughts?

**Comment by jonathanhotono** [comment]
Any answer to this question?
Thanks!

**Comment by khmlpa** [comment]
I agree. The content types created are unnecessary in most cases and don't appear to be able to be removed --- see --> #2750

**Comment by jonathanhotono** [comment]
@VesaJuvonen It also would be easier for us developer to have some sort of builder or full columns docs for this asset provisioning..
