### ISSUE TITLE
Chrome it is not working 

### ISSUE THREAD

**Issue by NavaneethaDev** [SharePoint/sp-dev-docs#1702]
This is working in IE but in chrome it is not working.
Also will this work for any pages apart from list/documents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by NavaneethaDev** [comment]
Verified it again and it is working. Closing this issue.

**Comment by Metroidaron** [comment]
I am experiencing this issue as well, I am unable to load this test extension in Chrome or Firefox (Mac user so I do not have IE/Edge).  When I use the URL Below (Tennant and sub site modified) the site does not even hit the local server.  I have verified I can load localhost:4321 in the browser and I see the request logs in the console.  I have not modified the boilerplate extension.  I am unable to prevent URL encoding, when I review the url in browser I see quotes and spaces, when I copy the url I get what you see below (Encoded with %22's and %20's)

Note: I have already installed dev cert by running gulp trust-dev-cert.

Url I get when I copy from the browser URL Field: (Encoded)
https://Tennant.sharepoint.com/Subsite/Lists/TestList/AllItems.aspx?loadSPFX=%22true%22&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={%2219ac98d4-405e-426b-9774-3fec0accf376%22:{%22location%22:%22ClientSideExtension.ApplicationCustomizer%22,%22properties%22:{%22testMessage%22:%22Hello%20as%20property!%22}}}

What url I am providing my browser: (Not Encoded)
https://Tennant.sharepoint.com/Subsite/Lists/TestList/AllItems.aspx?loadSPFX="true"&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"19ac98d4-405e-426b-9774-3fec0accf376":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"testMessage":"Hello as property!"}}}

**Comment by michalhainc** [comment]
you guys most probably have self signed ssl certs, open the https://localhost:4321/temp/manifests.js in new browser tab, you get warning about certificate, accept it, reload sharepoint page with the debugging url  and voila..

**Comment by en01** [comment]
FYI for others - my first mistake was not creating the myPage.aspx file in the target site.  The page referenced in the serve.json file needs to exist in order for the demo to work.

**Comment by blackheart01** [comment]
This still isn't working for me on Chrome or Firefox. When I run gulp serve, it opens the correct page with the debug query parameters all set, but I am never prompted to allow localhost debugging. No requests are made to localhost at all. I did what @michalhainc suggested, accepted the warning about the cert, and still nothing. Any help would be greatly appreciated! Thanks :)
