### ISSUE TITLE
Modern Yammer Web Part Posted from SharePoint Typo

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#1704]
#### Category
- [ ] Question
- [X] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When you use the 1st party Yammer app (Modern page) to post to Yammer, Yammer should say it was posted from the SharePoint Web Part (with a capital P).

#### Observed Behavior

Yammer shows that it was posted from the Share**p**oint Web Part:

![image](https://user-images.githubusercontent.com/8364109/39015912-a67abfe6-43ec-11e8-90b6-4cdad2792672.png)

#### Steps to Reproduce

Add the Yammer Web Part and post to a group then view it in Yammer.

Not totally sure this is a SharePoint issue, but it seems likely the issue is with the first party web part and how it is either registered with Yammer or the string it passes when it posts. If I should post this elsewhere, just let me know. Thanks!

**Comment by VesaJuvonen** [comment]
oh my.

**Comment by thechriskent** [comment]
This has been corrected!

![image](https://user-images.githubusercontent.com/8364109/40247666-2470fb9e-5a9b-11e8-868a-6996fc94723f.png)

Relevant Twitter thread with confirmation by team: https://twitter.com/theChrisKent/status/987060694305660928
