### ISSUE TITLE
Maybe broken deployment workflow in SharePoint using SPFx

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1705]
#### Category
- [x] Question

#### Expected or Desired Behavior
It should be possible to Re-add Apps once they have been removed from the site collection.

#### Observed Behavior
When I add an app to a modern experience website the app gets installed. In case I want to remove the app later this is in general possible. After a while, I maybe want to add it back. I get the error that the app already exists on the page and to remove the app I should make sure it doesn't exist still in recycle bin and not in the second stage recycle bin.

I remove the apps from both in hope to be able to add the application back. After that, the app I previously added is not listed anymore.
<img width="1082" alt="screen shot 2018-04-20 at 02 12 44" src="https://user-images.githubusercontent.com/5503835/39024324-6db54952-4440-11e8-8279-38de02779ec3.png">

The only chance is to navigate to "From your organisation" it says that the remove apps cannot be added back again.

<img width="939" alt="screen shot 2018-04-20 at 02 14 42" src="https://user-images.githubusercontent.com/5503835/39024376-b8807df8-4440-11e8-940c-0ceab13fe38f.png">

When I check the why I cannot add the app it says that it is already on the page still. Which is not true because it is removed from the site collection, recycle bin and second-stage recycle bin.

<img width="867" alt="screen shot 2018-04-20 at 02 15 58" src="https://user-images.githubusercontent.com/5503835/39024405-f43a0864-4440-11e8-9651-79b14d620b20.png">

Is it a bug or does this "hey it is already on the page" gets a reset at a time?

**Comment by patmill** [comment]
OK, I've repro'd this as well (although I saw slightly different, but also incorrect behavior).  It looks like there is a timing issue that is getting hit.  What I did find is that after clearing the 1st and 2nd stage recycle bins and waiting a short while, it will appear in the "add an app" page again (but I did get the page w/ my app not showing up on it at first).

**Comment by qz2017** [comment]
Please feel free to contact us if you have any further questions on this ticket.
