### ISSUE TITLE
What happens when ACS is retired this year?

### ISSUE THREAD

**Issue by piedpiperdev** [SharePoint/sp-dev-docs#1708]
ACS is supposed to be retired in November 2018. What is the path that we should follow to authenticate low trust add ins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f17b96d-562e-b80b-cd8f-4a89a4c3893d
* Version Independent ID: 877697bc-26a7-deb1-32d9-9c1d2247d9b1
* Content: [Creating SharePoint Add-ins that use low-trust authorization](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization)
* Content Source: [docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by flaviuc** [comment]
https://dev.office.com/blogs/impact-of-azure-access-control-deprecation-for-sharepoint-add-ins

**Comment by VesaJuvonen** [comment]
ACS is retired, no impact on the SharePoint add-in model as noted in the following articles.

- https://dev.office.com/blogs/impact-of-azure-access-control-deprecation-for-sharepoint-add-ins
- https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration#migration-strategies
