### ISSUE TITLE
Gulp serve can only watch a hardcoded list of fileextensions

### ISSUE THREAD

**Issue by zonique2k** [SharePoint/sp-dev-docs#1709]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It should be possible to configure the gulp serve task to watch other files than just ts, tsx, scss, resx, js, json, html. to allow us to ex. use Vue single file components, which has the extension .vue

#### Observed Behavior

The list of file extensions are hardcoded in the sp-build-web package (SPWebBuildRig.js), which makes it impossible to watch for other filetypes like .vue

#### Steps to Reproduce

1. Create a spfx project using the yeoman generator
2. Add a file with the extension .vue
3. Run gulp serve
4. Add/change the content of the .vue file and save it

The gulp tasks does not pick up the change

#### Our workaround

We're creating alot of spfx webparts in vue, and at the moment we manually change the SPWebBuildRig.js file to also include the .vue extension

**Comment by patmill** [comment]
Thanks for the feedback.  There is a workaround here that the pnp spfx generator project uses - https://pnp.github.io/generator-spfx/

We have this on the list of things to consider for future tooling.
