### ISSUE TITLE
Performance / Throtteling issues in SPO in combination with Beezy 

### ISSUE THREAD

**Issue by markusschmied** [SharePoint/sp-dev-docs#1711]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hi, as other users have reported during February/March, some of our Office 365 tenants suffer SharePoint CSOM throttling errors (HTTP 429) that apparently started to appear spontaneously.

As suggested we are opening separate tickets for every tenant so it helps to diagnose and collect data properly.

Tenant: gizonline.onmicrosoft.com

 When did it start: hard to say because we don't actively monitor the logs of this tenant but we noticed UI errors caused by throttling since 2 or 3 weeks ago, although we have traces corresponding to 2 months ago. So our perception is that these 429 responses are quickly growing in time.

These are just some timestamps when we got 429 responses (there are many, many more):
 02/13/2018 13:20:37.57
 03/12/2018 22:16:55.32
 04/09/2018 10:15:17.89
 04/12/2018 15:51:33.40
 04/17/2018 10:32:21.38
 04/20/2018 10:51:05.64
 04/20/2018 10:51:51.17
 04/20/2018 10:52:10.76
 04/20/2018 10:52:21.26
 04/20/2018 10:52:25.81
 04/20/2018 10:52:35.18
 04/20/2018 10:52:40.29
 04/20/2018 10:52:44.26
 04/20/2018 10:52:49.13
 04/20/2018 10:53:10.79
 04/20/2018 10:53:15.86

What is our code performing: hard to summarize in one line. The most frequent in our traces is querying properties from a Web object, which is a pretty basic operation that happens before performing any other one in our application. These operations occur in real-time, which means, they are triggered by a user request.

We use UserAgent and the incremental backoff retry method as instructed by https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online

If you can provide any guidance with this, it would be much appreciated. Thanks!

Thanks for your contribution! Sharing is caring.

**Comment by markusschmied** [comment]
@enriccarrion

**Comment by enriccarrion** [comment]
Just to clarify, I'm working together with the responsible of this tenant. This is a productive tenant of a customer which currently is not usable, because HTTP 429 responses occur 90% of the times approx. at certain times.

**Comment by akrijnen** [comment]
I have the same issues as @markusschmied mentioned:

04/25/2018 14:44:10.82
04/25/2018 14:44:06.24
04/25/2018 14:03:44.39
04/25/2018 14:03:36.74
04/25/2018 14:03:30.58
04/25/2018 14:03:23.42
04/25/2018 14:03:17.84
04/25/2018 14:03:10.55
04/25/2018 14:02:58.57 
04/25/2018 14:02:51.63
04/25/2018 14:02:34.17
04/25/2018 11:24:20.55
04/25/2018 11:17:12.12
04/25/2018 11:02:10.94
04/25/2018 10:57:21.49
04/25/2018 10:57:16.89
04/25/2018 10:55:28.33
04/25/2018 10:52:01.31
04/25/2018 10:51:55.41

And this is keeps on going. We are working only with 5 or 10 users currently. And we see those happening a lot.
