### ISSUE TITLE
Getting error 'A task was canceled' when calling the PnP PowerShell function New-PnPSite

### ISSUE THREAD

**Issue by SanderSiep** [SharePoint/sp-dev-docs#1712]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When calling this PnP PowerShell function (v 2.25.1804.1) I would expect to have a Team created within the Office365 environment.

#### Observed Behavior
When calling this function in approximately 50% I get an error: A task was canceled.
or in Dutch: Een taak is geannuleerd.
In the other cases it works like expected.
We have 2 Office365 environments and we only have these problems at one of these environments in the other environment it works like expected.

#### Steps to Reproduce

Execute the following code to reproduce the issue:
```
$groupTitle = "My Group Title 015"
$groupNameClean = "MyGroup015"
$groupDescription = "My Group Description 015"
$rootSiteUrl = "https://tenant.sharepoint.com/"

$credentials = Get-Credential
Connect-PnPOnline -Url $rootSiteUrl -Credentials $credentials

$newSiteUrl = New-PnPSite -Type TeamSite -Title $groupTitle -Alias $groupNameClean -Description $groupDescription -ErrorAction Stop
```

**Comment by SanderSiep** [comment]
unfortunately this issue is seen again today at our test environment. The test environment is also really slow today, even opening page takes ages.

**Comment by spcrux** [comment]
Hello, I'm also seeing this behaviour in my tenant. When I try to create a site using New-PnPSite, I get error - A task was canceled.

**Comment by SanderSiep** [comment]
We are also still having these issues on one of our O365 environments but only at certain periods. Looks like some performance issue at the O365 tenant or something like that.

**Comment by AndersRask** [comment]
We are also seeing this issue on a teanant when creating sites+groups using New-PnPSite
As said by others, the site are created fine, but the error makes it very difficult to create a reliable script that does further processing after site is created (such as applying Site Designs, or setting UnifiedGroupLinks)
@VesaJuvonen have you had opportunity to investigate why this error occurs?
