### ISSUE TITLE
Need a cmdlet to list out all the sites that link to a given hub

### ISSUE THREAD

**Issue by michaelblumenthal** [SharePoint/sp-dev-docs#1716]
See https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/34017007-need-a-powershell-cmdlet-that-lists-all-sites-conn . Please vote this up!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a5cf97-23a6-c406-b480-6b9130aaa1f8
* Version Independent ID: 94e5f95f-cdf1-16b5-0664-a8b23ce81de4
* Content: [PowerShell cmdlets for SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/hub-site-powershell)
* Content Source: [docs/features/hub-site/hub-site-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/hub-site/hub-site-powershell.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by silambarasanpandiyan** [comment]
Hi,

The new SPFX Sites web part is actually doing the job. I have inspected the network traces for that web part and it seems they are returning the values using feed request. But the feed Url is dynamic based on the region and I didn't find a way to construct that Url. 

Is there any workaround or a way to get all the associated sites?
