### ISSUE TITLE
How can you programmatically add feedback/comments to modern pages?

### ISSUE THREAD

**Issue by Shankar82** [SharePoint/sp-dev-docs#1717]
Hi,
How to add comments programmatically in modern site pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926ab97b-0406-116a-9b44-59df02beee7d
* Version Independent ID: 3094c3cf-cd16-518e-48fc-095fb14036dd
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-pages.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shabarishsanju** [comment]
Hi @Shankar,

Did you get solution for adding  comments pro grammatically in modern site pages?

**Comment by SarwarRana** [comment]
Hi all,

How do I post the page as News programatically once created?

Any help is greatly appreciated.
Thanks

**Comment by andrewconnell** [comment]
ATM, there is no supported API to do this. However, the PnPJS project run by the community does leverage an unpublished API, so YMMV:
https://github.com/pnp/pnpjs/blob/master/packages/sp/src/comments.ts
