### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mag210** [SharePoint/sp-dev-docs#1721]
Hi all, I have implemented this in a SPFX webpart. I have an ishtmlstring property which adds text to the web part. Despite following the instructions here the text in the web part does not seem to be searchable. When i search on the site, words on the SharePoint pages are picked up but anything within my web part is not. 
Has anyone else, seen this problem?
-Max

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0478b851-e0d2-0a30-3afa-34ca66bcb60b
* Version Independent ID: abc88d15-32c6-f019-1613-9c67630941d9
* Content: [Integrate web part properties with SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint)
* Content Source: [docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jeslas** [comment]
I'm seeing some strange behavior with this feature as well

My webpart property "title" is searchable
`protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      'title': { isSearchablePlainText: true },
      'intro': { isHtmlString: true },
      'image': { isImageSource: true },
      'url': { isLink: true }
    };
  }`

Webpart placed on one page with property "title" set to: "Juventus and Milan"
Placed on another page with "title" set to: "Razor Blade"

I get correct search result (1 hit) on "Milan" and "Blade", but no results on "Juventus" or "Razor"

**Comment by andrewconnell** [comment]
Are you still seeing this?

Did you give search enough time to index the page? It won't show up immediately in the search results.

As always, standard follow up on questions like this:
> Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:
>
> 	- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
> 	- If SharePoint Online, is tenant configured for standard / targeted release
> 	- Browser(s) tested
> 	- SPFx version
> 	- If applicable, version of Office UI Fabric React
>
> As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.
