### ISSUE TITLE
SharePoint Online Powershell - Root element missing error when run Connect-SPOService command

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#1723]
Hi Everyone,

I have newly installed SharePoint Online Management Shell (SharePointOnlineManagementShell_7521-1200_x64_en-us) on a windows 10 machine.

When i tried to run the 'Connect-SPOService -Url $adminUrl -Credential $credentials' I'm getting 'Root element is missing' error.

![image](https://user-images.githubusercontent.com/22563887/39080558-e73e7738-4528-11e8-93c3-7a59fb8f7c4f.png)

#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I ran the following command, I expect to connect to my SharePoint online tenant.

#### Steps to Reproduce

1. Install the SharePointOnlineManagementShell_7521-1200_x64_en-us
2. Open the SharePoint Online Managemnet Shell as administrator
3. Run the following commands
`$adminUrl = "https://{domain}-admin.sharepoint.com"
$userName = "admin@{domain}.onmicrosoft.com"
$password = Read-Host "Please enter the password for $($userName)" –AsSecureString
$credentials = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $userName, $password
Connect-SPOService -Url $adminUrl -Credential $credentials`

What am I missing? Any guidance to resolve this issue is appreciated. 

Thank you In advance

**Comment by VesaJuvonen** [comment]
As this is around SharePoint Online PowerShell, we would appreciate if you'd create this to the right repository, since this is not really about the development topics. The right location would be https://github.com/microsoftDocs/office-docs-powershell. Thx.

**Comment by muges01** [comment]
Thank you Vesa. I have moved created new issue under the link you have provided.
Reference: https://github.com/MicrosoftDocs/office-docs-powershell/issues/919
