### ISSUE TITLE
how to create my own group

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#1725]
how to create my own group rather than using group "other" with id "5c03119e-3074-46fd-976b-c60198311f70" ? thanks

**Comment by hugoabernier** [comment]
You're probably referring to the preconfiguredEntries groupId. That's reserved for pre-defined group ids.

If you want your own group, use "group", see below the example from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries 

...json
"preconfiguredEntries": [{
    "groupId": "1edbd9a8-0bfb-4aa2-9afd-14b8c45dd489", // Discover
    "group": { "default": "Under Development" },
...
  }]
...

**Comment by raymondlittle100** [comment]
Just to clarify the groupId has to be one in the existing list from the article linked and these groups map to the headings in the screen shot below. The group attribute is for classic pages only.

Is there any plan to provide people with a way to get a custom group in modern pages in the future?

![image](https://user-images.githubusercontent.com/23637375/40326714-3270831e-5d38-11e8-9e07-35006500161d.png)

**Comment by harshdamaniahd** [comment]
Yes, I also indeed need this functionality and it seems not working in modern experience

**Comment by peterremote1980** [comment]
a very wanted feature

**Comment by h3nn3** [comment]
Any update for this ?

**Comment by Vochomurka** [comment]
Still no option for create our own web parts group in modern enviroment? Any update please? Thanks...

**Comment by patmill** [comment]
No - at this point there is no option for creating your own groups.  As this isn't really a "bug", I'm going to close this.
