### ISSUE TITLE
1.4.1 wrong version in package.json

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#1726]
have:

/Users/peter/workspace/quantr-express>npm list -g @microsoft/generator-sharepoint
/usr/local/lib
└── @microsoft/generator-sharepoint@1.4.1

When i yo @microsoft/sharepoint to add one more webpart to existing project, in my package.json:

"@microsoft/sp-core-library": "~1.1.0",

but it should be 1.4.1 but not 1.1.0

**Comment by waldekmastykarz** [comment]
Could it be, that when creating the project, you selected that it should work with SharePoint on-prem instead of online?

**Comment by VesaJuvonen** [comment]
Coming back on following - "_When i yo to add one more webpart to existing project_". We do NOT updated package.json when we add a new web part to **an existing** project, so depending on how your solution was created, this is as expected. 1.1 version would imply that the solution was created for onpremises where we only support 1.1 or that solution was created earlier before 1.4.1 getting installed on your machine. Closing this as "answered", but happy to reopen if needed.
