### ISSUE TITLE
PropertyPaneToggle styles. When button toggled on - circle is on the left

### ISSUE THREAD

**Issue by Konradox** [SharePoint/sp-dev-docs#1728]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Toggle button circle should be placed on the right side of the button

#### Observed Behavior

After a click on the toggle button, the button changes colour but the circle doesn't move.
![image](https://user-images.githubusercontent.com/9269007/39115462-025714fc-46e2-11e8-8c23-dacb7adf5029.png)

#### Steps to Reproduce

1. Add a new property to web part (manifest & properties interface),
2. Add PropertyPane field in getPropertyPaneConfiguration() method. Example: 
`PropertyPaneToggle('test', {
   label: 'test'
 })`
3. Run the solution, add the web part, edit it,
4. Click on the toggle button.

#### Submission Guidelines

Tested on a new project. SPFx 1.4.1. Browsers tested: Chrome 66, IE 11

**Comment by patmill** [comment]
Sorry for not staying on top of these - this has been fixed for a while.
