### ISSUE TITLE
Sharepoint Framework Property Pane - building a dynamic property

### ISSUE THREAD

**Issue by SKempin** [SharePoint/sp-dev-docs#1730]
I'm attempting to build a dynamic property in the Property Pane of a React based Sharepoint Online Web Part.

In order to achieve this I wish to iterate through an array of data in the PP, to create multiple drop down fields. Currently I can only create drop down fields through individual variables, not arrays or objects (as these can not be iterated through in the PP render method). This means that I can only render a predefined number of drop down fields in the PP.

Microsoft have already achieved this functionality on their 'Highlighted Content' Web Part, but haven't published the source code for this, so I cannot see how they have achieved it. On this Web Part the user can add multiple PP drop down fields and remove these individually too, without limit (i.e. they are rendered fully dynamically).

Is this possible to do or am I taking the wrong approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b669b5-e0bf-5e0c-0811-10c6254742a6
* Version Independent ID: ee0aa417-37e0-3cb3-179b-dbb47f8534a5
* Content: [Make your SharePoint client-side web part configurable](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/integrate-with-property-pane)
* Content Source: [docs/spfx/web-parts/basics/integrate-with-property-pane.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/integrate-with-property-pane.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by SKempin** [comment]
@aplantard I haven't found a solution no, it's quite frustrating. My only suggestion is to contact via the SP monthly call - https://github.com/SharePoint/PnP/wiki/Community-call

**Comment by SKempin** [comment]
@aplantard https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev may also be of help. I am going to post this question in there too.

**Comment by russgove** [comment]
Hey, not sure if this still an issue for you, but,,,
I did something  like this in the spfx samples webpart  at  https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-multilist-grid

User selects lists and them custom panels are shown to let the user configure settings for each column in the list,. Be forewarned... it worked in older versions of spfx (i think 1.2) but not sure about later versions.

**Comment by andrewconnell** [comment]
You might want to check this out as well: 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties

A few solutions have been posted here... seems like we can close this issue. Feel free to submit a comment/issue if you have additional questions.
