### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by SiggeSeb** [SharePoint/sp-dev-docs#1732]
on page
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints
this is a dead link
https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-BasicDataOperations.md 
somewhere in the top 20 rows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047ea71c-e866-b2dd-5530-8451de27ba4a
* Version Independent ID: 3b886e81-c3b7-d5c1-136f-4cb827b4952f
* Content: [Complete basic operations using SharePoint REST endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints#feedback)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for catching this!
