### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by jonathan88n** [SharePoint/sp-dev-docs#1738]
With Design Manager, you can convert an.html file into a SharePoint master page

The above should have a space between "an" and ".html file".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20fd888e-c513-1964-9709-0bf3c3f8d2f6
* Version Independent ID: 09c3ba13-b641-5a81-3882-3bc5d5c0b851
* Content: [Convert an HTML file into a master page in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint#feedback)
* Content Source: [docs/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for catching this!
