### ISSUE TITLE
The workbench doesnt open up after the certificate installation

### ISSUE THREAD

**Issue by kspranesh** [SharePoint/sp-dev-docs#174]
After the Drop 2, i am facing multiple issues with the certificate.

1) On Windows 10 machine, even after multiple attempts of installing the certificate i still get the warning and error with the webpart

![image](https://cloud.githubusercontent.com/assets/12847736/18362486/b4ff6bae-75ba-11e6-8e57-b372db13ee40.png)

2) I tried on a different machine (Windows 7) and installed the certificate, even after that i see the attached browser window 
![image](https://cloud.githubusercontent.com/assets/12847736/18362385/5ea23caa-75ba-11e6-9553-62ba674ab481.png)

Please help!

**Comment by patmill** [comment]
You can ignore the error in the toolbox.  It's a bug in the platform code, and doesn't actually affect anything.

**Comment by iclanton** [comment]
For your second issue, it looks like gulp serve isn't running. You should get some response.

**Comment by iclanton** [comment]
@kspranesh - are you still seeing your second issue? Otherwise, we'll close this.

**Comment by StfBauer** [comment]
@iclanton have the same issue on Mac since Drop 4. 
The host name in the URL seems to be broken with gulp-connect. Accessing the workbench through localhost works well. IMO should be the default url to open the workbench.

**Comment by iclanton** [comment]
There is a specific issue on Macs when they're on WiFi. However, it will be fixed in the next drop.

**Comment by iclanton** [comment]
I believe this is resolved.

@StfBauer, @kspranesh - if you're still seeing this, can you re-open this issue?
