### ISSUE TITLE
Default site design customization

### ISSUE THREAD

**Issue by bmarcos81** [SharePoint/sp-dev-docs#1742]
When a new default site design is established, the configured title and description are not displayed. Instead, it continues to show the title and description of the original design of the site. I suppose it also affects the preview image and the alternative text. I tested it with a new default team site design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f32aba9c-798d-263b-27fa-b5e0e23b456c
* Version Independent ID: 554c3429-6bb3-3c0e-3cf9-6365f5b83881
* Content: [Customize default site designs in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design)
* Content Source: [docs/declarative-customization/customize-default-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/customize-default-site-design.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by seansquires** [comment]
Apologies for the slow reply here. Thank you for the feedback - this is currently by design. We allow associating a site design to the default template (both group-connected team and communication), but we don't allow editing the label, description, or preview image at this time. I'll amend the documentation to make these setting restrictions clearer. Thanks!

**Comment by spsguru** [comment]
Asking for clarification: so if we have a site design that we apply as a default (using the method above), and then have other site designs that we have deployed as alternate designs from the default ones (Topic, Showcase, blank & Team), and so they are listed as choices in the drop-down for site creation, does the site creation process create a default site (with our custom default alterations) and then apply the alternate design if we select the alternate design in the drop down?

To ask this differently, if I have a specific action to apply a theme, and I deploy that as a default site design customization, do I also need to include that action to apply a theme in any other alternate site designs (say, a Project site design, or a Support Team site design)?

**Comment by seansquires** [comment]
Great question - and the answer is, yes. If you have a site design with an action to set theme to green attached to the default communication template, that would only be executed when one of the default comm site templates are selected. If you also had an alternate site design - "Project" - that you also wanted to set site theme to green, you'd have to add that action to that site design script. Does that make sense?

BTW, we are looking to make the isDefault setting more granular - so you could set to Blank or Showcase or Topic (as we've gotten f/b that it's confusing w/ three out-of-the-box "default templates" for communication and only one for team)...would that help?

**Comment by seansquires** [comment]
Thanks John - a global design - interesting. You could sort of do that now by just applying the same design to all available templates (communication, group-connected team, and team). Very soon we'll also be shipping an option to apply a site design when a site is joined to a hub; that could be helpful in your scenario, esp. if those "global" configurations differ by department. In any case, thank you for the feedback!
