### ISSUE TITLE
List Delete Code Not working

### ISSUE THREAD

**Issue by ViswanathUppu** [SharePoint/sp-dev-docs#1748]
Hi Team,

I am using REST API in an ASP.net application with C#. While deleting list from SharePoint online site, i am receiving 500 internal server error.

Please find my code below.

HttpWebRequest request = HttpWebRequest.CreateHttp(String.Format("{0}/_api/web/lists/GetByTitle('ListName')", spHostURL));

           
            request.ContentLength = 0;
            request.Headers.Add("X-FORMS_BASED_AUTH_ACCEPTED", "f");
            request.Headers.Add("X-RequestDigest", formDigest);
            request.Headers.Add("IF-MATCH", "*");
            request.Headers.Add("X-HTTP-Method", "DELETE");
            request.Credentials = credentials;
            request.Method = "POST";
HttpWebResponse endpointResponse = (HttpWebResponse)request.GetResponse();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#using-etag-values-to-determine-document-and-list-item-versioning)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by AlainCote** [comment]
Hi,
I have tried many times to build a url to extract a file from SharePoint online using the following syntax:

https://site url/_api/web/lists/GetByTitle('Test')/items. 

Unfortunately, nothing seems to be working, maybe i don't understand the way your rest API works or the api itself does not work with the GetByTitle method ? This is the last url i tried: https://umaknowdev.sharepoint.com/sites/devalain/_api/web/TestPowerPointBNC/GetByTitle('cool'). The end point is good i am able to query some info out of this but i cannot get any files on my collection site (devalain). If you can tell where i am making a mistake or guide me to a documentation that can explain to me in a simple way how to build a request. it would be much appreciate.

Thank you.

**Comment by andrewconnell** [comment]
Seems like you're doing this from a server-side app outside of the SharePoint context... correct?

Couple things... you need to authenticate as an app and obtain an access token from Azure AD to talk to the SharePoint REST API. You're missing the `Authorization` header in your request.

Further, you don't need the following headers:
- ContentLength
- X-FORMS_BASED_AUTH_ACCEPTED
- IF-MATCH
- X-RequestDigest *(this will only apply if you're doing the update from the page and not using the OAuth model)

Please elaborate on this line `request.Credentials = credentials;` ... what is `credentials`? I'm guessing you're trying to do forms auth... that won't work. Look at the last paragraph before the first code snippet in the "Reading..." section of this doc for more details on the auth requirements for REST API: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints#reading-data-with-the-sharepoint-rest-interface
