### ISSUE TITLE
is it mandatory to Make,  this available on all site collection?

### ISSUE THREAD

**Issue by rohit404404** [SharePoint/sp-dev-docs#1749]
is it alright if i leave that unchecked and just install on single site? At which moment does request come in admin center for approval? I left the box unchecked and have manually installed on one of the site colelction. I still dont see request in admin center and hence the error on webpart that, "AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXXXX' named 'SharePoint Online Client Extensibility'. Send an interactive authorization request for this user and resource"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi#feedback)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by semekhlouf** [comment]
Hi, I've followed all the steps, but when I add the package to the app catalog i got this error: App Package Error Message: Error in the application.

the azure function is correctly responding, any help ?
