### ISSUE TITLE
this.context.pageContext.site.id undefined in classic pages only

### ISSUE THREAD

**Issue by paulryan** [SharePoint/sp-dev-docs#175]
#### Category

[ X] Bug
#### Expected or Desired Behavior

Using the Reactjs template:
this.context.pageContext.site.id is defined when testing against in a modern page using workbench.**aspx** but is undefined in a classic page.
#### Observed Behavior

this.context.pageContext.site.id should not be undefined in classic pages
#### Steps to Reproduce

Create a React web part that prints the value of this.context.pageContext.site.id to the console. Check that it works when the web part is hosted workbench.aspx. Bundle it as app to **ship**. Add the web part to a classic page. See that the property is null.

**Comment by patmill** [comment]
Thanks Paul - you are absolutely correct.

**Comment by manishgarg1** [comment]
This is a known issue and should be fixed soon.

**Comment by lahuey** [comment]
The issue has been resolved. The property will now contain the expected value.

**Comment by manishgarg1** [comment]
Hi @paulryan, please let us know if this is still and issue.
