### ISSUE TITLE
Errors reported from new content-security-policy-report-only

### ISSUE THREAD

**Issue by nero120** [SharePoint/sp-dev-docs#1750]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

In one of our tenants we've just started seeing browser errors in the console when running SPFX web parts such as the below:

```
[Report Only] Refused to load the script 'https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-04-13.002/sp-pages-assembly_en-us_ea66f8f8711fabe4ca8c47ac09c3d6d3.js' because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'unsafe-eval' 'nonce-579d1bac-3fdb-4d81-b5bd-092846b8edb5' ". 'strict-dynamic' is present, so host-based whitelisting is disabled.
```

The errors stem from a new `content-security-policy-report-only` header which looks like it's been added on or after version `16.0.0.7612`, as it's not present on our tenant running `16.0.0.7611` but is present on our tenant running `16.0.0.7618`. The new header is:

```
content-security-policy-report-only: script-src 'strict-dynamic' 'unsafe-eval' 'nonce-579d1bac-3fdb-4d81-b5bd-092846b8edb5' ; report-uri https://[siteurl]/_layouts/15/CSPReporting.aspx
```

I realise that this is a report only and is not being enforced (though who knows if you'll suddenly change it to be enforced without warning), but it's causing errors to appear in the browser and what's even more concerning is that it's strict enough to cause the browser to refuse to load spfx scripts from Microsoft's own CDN as well as all of the library scripts we are loading from public CDNs that our SPFX web parts rely on. I'm also very concerned that these issues are being rolled out to production tenants without being caught in testing.

Also could you tell me why our non-first release tenant has a later version of SharePoint (16.0.0.7618) than our first release tenant (16.0.0.7611)?

**Comment by VesaJuvonen** [comment]
On the tenant version question - first release setting is not really controlling what is the tenant version. First release setting controls which capabilities will be enabled where first and this is not dependent on the version of the tenant. We'll also investigate the actual issue related to the security policy.

**Comment by patmill** [comment]
Hi @nero120 , we'll be releasing guidance around this shortly.  As you mention, this is reporting only, so we can see what the impact would be and refine the policy (as well as make sure we are handling it correctly ourselves).

Can you tell me how you got your page to have the sp-pages js code to not be loaded correctly?  Does this appear if you navigate directly to a modern page (sites/yoursite/sitepages/home.aspx) or did you navigate from the _layouts/15/SharePoint.aspx page, or a document library first?

Thanks,
Pat.

**Comment by nero120** [comment]
Ok thanks @patmill, well in any case the warnings have gone away so feel free to close this issue.

However my question to @VesaJuvonen still stands. Does Microsoft have any recommendations or best practice regarding implementing an ALM process on SharePoint Online/O365/Azure if updates/patches could be rolled out to production tenants/subscriptions at any time with no way to test them beforehand?

**Comment by nero120** [comment]
Absolutely @luismanez! Btw it's been a while since I last spoke to you dude, hope you're doing well! 😃

**Comment by BeccaAtAcumen** [comment]
I realize this is an old stream but we have SharePoint Server 2019 and I want to remove the CSP-ReportOnly header as it's throwing dozens of exceptions in the console due to the anonymous users not having access to _layouts/15/CSPReporting.aspx
