### ISSUE TITLE
Please delete this

### ISSUE THREAD

**Issue by thunem** [SharePoint/sp-dev-docs#1751]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expect the desciption on the web

#### Observed Behavior
When setting the web description with New-PnPWeb or Set-PnPWeb I assume that I can get the description by getting the web and ask for the description.

#### Steps to Reproduce
`New-PnPWeb -Title 1 -Url "1" -Description "1" -Locale 1044 -Template "STS#0"`
`$web = Get-PnPWeb -Identity 1`
`$web.Description #do not return anything`
`Set-PnPWeb -Description "11" -Web 1`
`$web.Description #do not return anything`

**Comment by VesaJuvonen** [comment]
Closing based on delete request.
