### ISSUE TITLE
Cross origin issue.

### ISSUE THREAD

**Issue by rohit404404** [SharePoint/sp-dev-docs#1753]
I followed exact steps and after approving app from admin center, i am getting Cros origin issue in browser console.  I did add site url under CoRs in azure function. Do I need any other changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi#feedback)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
What error are you getting exactly?

**Comment by rohit404404** [comment]
Thank you for your response Waldek, It was stupid mistake, apologies
