### ISSUE TITLE
Tenant Class in CSOM

### ISSUE THREAD

**Issue by gitakhilesh** [SharePoint/sp-dev-docs#1754]
Is this document still relevant? As I can see 
Microsoft.Online.SharePoint.Client.Tenant (in Microsoft.Online.SharePoint.Client.Tenant.dll)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79010e96-c26f-6d27-8ddc-a6ac79c2935e
* Version Independent ID: 4860a3a9-ab1a-da03-f50c-221dd2049aca
* Content: [Get a quick overview of the SharePoint object model](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model#feedback)
* Content Source: [docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yes... but not sure what you're asking. Is there an error you're seeing?
