### ISSUE TITLE
SPHttpClientBatch Still in Preview since SPFx v1.0!? GA ETA?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#1756]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Even though it's been there since GA (unless I'm misremembering it), `SPHttpClientBatch` is still in preview... what's the story moving forward?

#### Observed Behavior

`SPHttpClientBatch` is [currently doc'd as being in preview](https://docs.microsoft.com/en-us/javascript/api/sp-http/sphttpclientbatch?view=sp-typescript-latest)...

**Comment by VesaJuvonen** [comment]
yikes - we're on it...

**Comment by VesaJuvonen** [comment]
This is still in progress, currently planned to get released with 1.8.

**Comment by VesaJuvonen** [comment]
Closing as answered.
