### ISSUE TITLE
"propertyPane" and "DisplayMode" in application customizer ?

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#1758]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Desired Behavior

A "propertyPane" and "DisplayMode" and other edit mode function in microsoft/sp-application-base

#### Question

Are there any plans or a possibility to use propertyPane (option panel) and the edition mode (DisplayMode) support in application customizer ?

Thanks.

**Comment by garrytrinder** [comment]
+1 for adding DisplayMode

**Comment by PooLP** [comment]
Hi,
Any news for this ?

**Comment by PooLP** [comment]
Any news for this ? (For not close issue automatically. ^^)

**Comment by toblum** [comment]
Same here: Need to find out if the page is in edit mode from the application customizer. Found no solution so far.

**Comment by patmill** [comment]
We won't support showing a property pane for configuring application customizers (they aren't really end-user configurable).  The request to know the page state makes sense, and we've added it to the list of future features.  Sorry for the long delay here.
