### ISSUE TITLE
Multiline Enhanced Rich Text Field in Document Library

### ISSUE THREAD

**Issue by nadeemy** [SharePoint/sp-dev-docs#1759]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Edit pop up should open on clicking of Pen (Edit button) 

#### Observed Behavior

404 NOT FOUND error 

#### Steps to Reproduce

Added Multiline Enhanced Rich Text field to a SharePointOnline Document Library using JSOM. The field appears properly in classic mode but gives 404 NOT FOUND error when clicking on the Pen (edit button) in modern experience.

```
var fieldSchema = '<Field Type="Note" DisplayName="Feedback" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" NumLines="6" UnlimitedLengthInDocumentLibrary="TRUE" RichText="TRUE" RichTextMode="FullHtml" IsolateStyles="TRUE" Sortable="FALSE" ID="{450158A2-AD0C-46A5-9108-BB1D3FA3649B}" StaticName="Feedback" Name="Feedback" ColName="ntext2" RowOrdinal="0" />'
var clientContext = new SP.ClientContext();
var targetList = clientContext.get_web().get_lists().getByTitle('Documents');
var fieldCollection = targetList.get_fields();
fieldCollection.addFieldAsXml(fieldSchema, true, SP.AddFieldOptions.addToDefaultContentType);
clientContext.load(fieldCollection);
clientContext.executeQueryAsync(function () {console.log('success');}, function() {console.log('failure');});
```

**Comment by VesaJuvonen** [comment]
This could potentially be also in the xml structure. We'll have a look at some point but might take a while. I would do the field adding first from UI and then see the value in the field to mimic that in your code.

**Comment by nadeemy** [comment]
Thanks @VesaJuvonen. Same XML when added to a List (not library) works in modern experence as well.

**Comment by nadeemy** [comment]
@ahackettms Multiline Enhanced Rich Text field cannot be added to a SharePointOnline Document Library from the UI.

**Comment by VesaJuvonen** [comment]
A generic rich-text multiline text field is not supported in the document library currently, which is why it's not visible in the UI. Underlying API has not been changed to block this, which is how you were able to get it in, even though it's not yet supported. We have a backlog item for adding rich-text multi-line support for the modern document library, but there's no ETA at this time.

**Comment by nadeemy** [comment]
Thanks for the update @VesaJuvonen
