### ISSUE TITLE
Support "disableReactivePropertyChanges" at the page level

### ISSUE THREAD

**Issue by paulryan** [SharePoint/sp-dev-docs#176]
#### Category

[ x] Enhancement / Suggestion
#### Expected or Desired Behavior

I'd like to be able to set "disableReactivePropertyChanges" at the page level. 

I have an app where I have page of properties which need to be non-reactive as they trigger fetching and processing data, and then a second page of visual properties which would really benefit from the reactive model.
#### Observed Behavior

The entire properties panel must either be reactive or non-reactive.

**Comment by manishgarg1** [comment]
@paulryan, we believe this can cause some confusion with the user experience. As the user sees different behaviors on different PropertyPane pages. We have already gone through a few iterations and user stuies with this design and this one seemed to be simple enough for the users. 

You can achieve what you want with rendering different pages in different states of the web part. And disableReactivePropertyChanges can be derived from a private field in the web part whose value can change in different states of the web part. But please remember, even though this is doable it could cause potential confusion with the end users.

**Comment by paulryan** [comment]
Sure, I can appreciate how this could create an awkward UX.

**Comment by manishgarg1** [comment]
Hi @paulryan, after some more discussion we have decided that this feature could perhaps cause more confusion than simplify things. Hence, we will not be supporting this at the current time. Please reopen the issue if you really feel that we need to support this.
