### ISSUE TITLE
Content Types Inheriting from Site Page in Modern Sites Inconsistent Behavior

### ISSUE THREAD

**Issue by pdemro** [SharePoint/sp-dev-docs#1760]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Create a content type inheriting from Site Page.  Add this content type to the "Site Pages" library in a modern site.  Select the new content type from the **+ New** button in the library.  Update the page and publish.  

Expected behavior - after selecting the alternate content type from the +New dropdown and saving, that page should be saved as the new content type

#### Observed Behavior

The page is always saved as the "Site Page" content type, regardless of what content type you select from the +New button

#### Steps to Reproduce

1. Create a content type inheriting from Site Page.  
2. Add this content type to the "Site Pages" library in a modern site.  
3. Select the new content type from the **+ New** button in the library.  
4. Update the page and publish.  

The page is created as the Site Page content type regardless of content type chosen from the drop down

**Comment by patmill** [comment]
Currently you can not create a site page as a different content type.  You'll want to add this as a feature request to User Voice.

**Comment by pdemro** [comment]
I can see this is fixed in one of my tenants.  Thanks again @patmill
