### ISSUE TITLE
Security exception in Firefox through self-signed certificate

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1765]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
Firefox 59 on OSX raises a security exception because of the self-signed certificate. To get the workbench running special steps are required to trust the self-signed certificate.

<img width="934" alt="screen shot 2018-04-29 at 21 06 18" src="https://user-images.githubusercontent.com/5503835/39410029-5006c666-4bf1-11e8-903b-ec2decdde331.png">

In addition, the following information in FireFox is available.

<img width="772" alt="screen shot 2018-04-29 at 21 07 39" src="https://user-images.githubusercontent.com/5503835/39410034-76209bf6-4bf1-11e8-8fe7-88344fde1747.png">

In general this I guess not a big deal but might should be somewhere documented. The development certificate is trusted on my machine.

#### Steps to Reproduce
Open workbench in FireFox on Windows, Linux or OSX. I guess the exception gets shown everywhere.

**Comment by VesaJuvonen** [comment]
Thanks Stefan, we absolutely need to document this for FireFox.
