### ISSUE TITLE
My/Followed documentation on types

### ISSUE THREAD

**Issue by raymondlittle100** [SharePoint/sp-dev-docs#1767]
The documentation tells you to supply a parameter to target the query and supplies param 15. There are some examples below this but only a select few are covered and 15 isn't. 

There is nothing to indicate what the possible values are/should be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6241b0c-5fed-5dc2-63c8-b84232d1bd89
* Version Independent ID: 9b6bb121-3908-ea83-3621-85f1528600fd
* Content: [Following people and content REST API reference for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/following-people-and-content-rest-api-reference-for-sharepoint#myfollowed)
* Content Source: [docs/general-development/following-people-and-content-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/following-people-and-content-rest-api-reference-for-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The doc says:
> Bitwise combinations are allowed.

15 is bitwise for all types
