### ISSUE TITLE
HttpClient always makes requests with respect to the root site collection and not the current web

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#177]
#### Category
[ X] Question
[ X] Enhancement

#### Expected or Desired Behavior
The HttpClient should always make requests with respect to the current web i.e. the web on which the SPFx webpart is running. 
`this.context.httpClient`

#### Observed Behavior
My tenant url is `https://vrdmn.sharepoint.com` and I am working on a site collection `https://vrdmn.sharepoint.com/sites/dev `

If I use the context.httpClient to make a GET request to bring in all the lists, it brings all the lists of the root web of the root site collection and not my current web. 

Here is my code:

The IListService.ts interface:

```
export interface IListService {
  getLists: () => Promise<JSON>;
}
```

The ListService class which implements the interface:

```
import { IListService } from "../interfaces/IListService";
import { ServiceScope, HttpClient } from '@microsoft/sp-client-base';

export class ListService implements IListService {

  private httpClient: HttpClient;

 constructor(serviceScope: ServiceScope) {
    serviceScope.whenFinished(() => {
      this.httpClient = serviceScope.consume(httpClientServiceKey);
    });
  }

  public getLists(): Promise<JSON> {

    //This returns the lists of the root site collection and not the current web
    return this.httpClient.get(`/_api/web/lists`)
    .then((response: Response) => {
      return response.json();
    });

    // This works as expected if I have passed in the absoluteurl of the web into the class from the constructor.
   // but this should not be necessary as the service scope should be aware of the currrent web. 
   // In addition, that would clutter the constructor as well. 
    // return this.httpClient.get(`${absolute-url-of-web-passed-from-constructor}/_api/web/lists`)
    // .then((response: Response) => {
    //   return response.json();
    // });
  }
}
```

And finally, the calling code which runs in the render method of the webpart:

```
    const serviceScope: ServiceScope = this.props.serviceScope;
    const listServiceKey: ServiceKey<IListService> = ServiceKey.create<IListService>("listservicekey", ListService);

    const listServiceInstance: IListService = serviceScope.consume(listServiceKey);

    listServiceInstance.getLists().then((response: JSON) => {
      console.log(response);
    });
```

When this code is executed, you can see that the HttpClient brings back the lists of the root site collection and not the current web.
![servicescope](https://cloud.githubusercontent.com/assets/173794/18412575/c66e0ae6-7789-11e6-8800-5ea06f7692b0.PNG)

**Comment by vman** [comment]
I have edited this issue/request based on @pgonzal's answer here https://github.com/SharePoint/sp-dev-docs/issues/179#issuecomment-246837334

**Comment by pgonzal** [comment]
This code is providing an **server-relative** URL:

```typescript
    //This returns the lists of the root site collection and not the current web
    return this.httpClient.get(`/_api/web/lists`)
    .then((response: Response) => {
      return response.json();
    });
```

That is, according to the HTTP protocol "/_api/web/lists" is a shorthand for "https://vrdmn.sharepoint.com/_api/web/lists".  If you want the **web-relative** URL, you should do something like this:

```typescript
    import { UrlUtilities } from '@microsoft/sp-client-base';

    const webUrl: string = UrlUtilities.removeEndSlash(
      this.context.pageContext.web.serverRelativeUrl);

    return this.httpClient.get(webUrl+ '/_api/web/lists')
    .then((response: Response) => {
      return response.json();
    });
```

**Comment by pgonzal** [comment]
I'm marking this as "answered"; please reopen the bug if you have more questions.

**Comment by pgonzal** [comment]
I am closing this issue; please reopen it if you have more questions.  Thanks!
