### ISSUE TITLE
SPFx Dialog Framework + Office UI Fabric DetailsList: potential rendering bug

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/sp-dev-docs#1772]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When you define a dialog window, using the SharePoint Framework Dialog Framework (@microsoft/sp-dialog) and you add a control of type _DetailsList_ to the content of the dialog, you would expect to see the _DetailsList_ properly rendering in the dialog.

#### Observed Behavior
The _DetailsList_ control of Office UI Fabric does not render unless you make a resize of the browser's screen area. You can even force the resize by code (via `window.dispatchEvent(new Event('resize'));`), for example within the _componentDidMount_ event, but it should work without this workaround.

#### Steps to Reproduce
Attached to this issue you can find a sample solution to reproduce the described behavior. You can simply run the solution (`gulp serve --nobrowser` after having done an `npm i`), start the SharePoint Workbench and add the Web Part with name DialogTest. Press the _Test_ button and see that there is a small delay rendering the _DetailsList_ control. Now, to see the real issue in action, just comment the _componentDidMount_ event in the _DetailsListDialogContent_ component, refresh the page (CTRL+F5) and run the Web Part again: the _DetailsList_ control will not show up until you slightly resize the browser window.

Thanks for any feedback.
[spfx-detailslist-dialog-test.zip](https://github.com/SharePoint/sp-dev-docs/files/1962354/spfx-detailslist-dialog-test.zip)

**Comment by gszdev** [comment]
Workaround for IE:
if(navigator.userAgent.indexOf("MSIE") !== -1 
      || navigator.appVersion.indexOf('Trident/') > 0){
        var evt = document.createEvent('UIEvents');
        evt.initUIEvent('resize', true, false, window, 0);
        window.dispatchEvent(evt);
    } else {
      window.dispatchEvent(new Event('resize'));
    }

**Comment by AJIXuMuK** [comment]
Hi @PaoloPia,
Sorry for really long delay...
We've just tested the behavior and seems like on the latest version of SPFx and OUIFR v7 everything works correctly.

Let us know if you still experience this issue on your tenant.

Thanks!
