### ISSUE TITLE
SharePoint List Item create in folders using  AddValidateUpdateItemUsingPath does not return item id ?

### ISSUE THREAD

**Issue by ahsanranjha** [SharePoint/sp-dev-docs#1775]
Item is successfully created in folder but it does not bring item code in response???

![image](https://user-images.githubusercontent.com/9005752/39465966-6b877fce-4d37-11e8-8d8c-c694c7dbf809.png)

is there any way to create items inside folder and get item as response?

**Comment by matrixgoh** [comment]
Any difference ItemId attribute with FieldValue with FieldName is "ID"
![image](https://user-images.githubusercontent.com/8360966/63224976-4b424900-c1fe-11e9-8358-33f3fb1db2b6.png)

**Comment by mgoto-git** [comment]
We have the same issue.
Do you have any update?

**Comment by Leif-Frederiksen** [comment]
How do you obtain the ID of the just created item when using addValidateUpdateItemUsingPath?

Alternatively - how do you move an exisiting item to a specific folder?
