### ISSUE TITLE
app doesn't show upgrade

### ISSUE THREAD

**Issue by erikstagg** [SharePoint/sp-dev-docs#1777]
2 issues im having. Main issue is that when i go to the app details, it is still showing version 1.0.0.0 (while the current version in the app catalog is 2.0.0.0) but it's not saying there is a  new version. In the app catalog, enabled, valid app package, and deployed all say yes, no errors, and i have even tried using the --ship flag on bundle and package-solution. The other issue which may or may not be related is that my app only shows in the Site Contents when I'm in classic mode. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by erikstagg** [comment]
I guess this is just a difference between classic mode and the new mode, but I had to click about, not details, to upgrade to the new version. Still doesn't explain why the update isn't showing up under the app name in site contents, or why the new mode isn't displaying my apps correctly. i just noticed that there are other apps that aren't listed, and one app is listed 6 times

**Comment by qz2017** [comment]
@erikstagg , I cannot repro the app details issue when I tried. Can you please provide me with your app? Feel free to ping me internally.

**Comment by qz2017** [comment]
Closing the ticket due to no response. Feel free to reopen it if it repros for you.

**Comment by jordivmslc** [comment]
In my case, upgrade wasn't showing because .sppkg file had been left checked out after drag&dropping it in the App Catalog. After checking it back in, "GET IT" button was enabled.
