### ISSUE TITLE
Web part does not load until you scroll 20px

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#1779]
I noticed the full width SPFX web part does not load until I scroll the page down 20px. The zone has this HTML to set opacity to 0 and translatey(20px)
div style="visibility: hidden;; visibility: visible;  -webkit-transform: translateY(20px) scale(1); opacity: 0;transform: translateY(20px) scale(1); opacity: 0;" data-sr-id="2"

How can I prevent this from happening?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4825eeab-f123-c0fb-0d30-6d634c821bd2
* Version Independent ID: 55d7e710-4faa-4cfa-772d-f83962d9fe52
* Content: [Use web parts with the full-width column](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column)
* Content Source: [docs/spfx/web-parts/basics/use-web-parts-full-width-column.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/use-web-parts-full-width-column.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by eschrader** [comment]
Similar bug posted here https://github.com/SharePoint/sp-dev-docs/issues/1428

**Comment by eschrader** [comment]
I posted how I built my web part a few months ago incase that helps. https://eschrader.com/2018/03/02/create-a-spfx-web-part-to-display-sharepoint-list-data-based-on-locale-and-graph-api-data/

**Comment by VesaJuvonen** [comment]
and... was corrected - re-open to do additional investigation.

**Comment by patmill** [comment]
Let's stick with Vesa's original close :).  Looking into this as part of the other full-bleed issue reported.
