### ISSUE TITLE
SharePoint Admin Center banner should respect IsDlg=1

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#1781]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

When opening a dialog in the classic SharePoint Admin Center the banner encouraging you to try the new SharePoint Admin Center shouldn't show up:

![image](https://user-images.githubusercontent.com/8364109/39537055-63d4131c-4e06-11e8-843a-8c604ca4dd23.png)

The Feedback button hovering over the Cancel button isn't great either.

#### Steps to Reproduce

- Navigate to the SharePoint Admin Center
- Click user profiles
- Find a user profile and choose to edit
- Click the Upload picture button

I'd think they could just add the `s4-notdlg` class to the `newTenantAdminBanner` div and this should take care of it, but... that's their call of course.

Thanks!

**Comment by VesaJuvonen** [comment]
Given the updates on the modern experiences in the admin UX, this should have been already sorted out, so closing the issue.
