### ISSUE TITLE
Unable to sign up to Office 365 tenant for Developers

### ISSUE THREAD

**Issue by Maplin83** [SharePoint/sp-dev-docs#1782]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello Guys,

Apologies for bringing this question here but I am genuinely stuck and need help. I am a novice developer wishing to learn the new SharePoint Framework. I have signed up to the Office 365 for Developers program to take advantage of the free Office 365 tenant you can utilise for twelve months. Sadly, each time I attempt to create my Office 365 tenant after adding my details (desired username, domain name, etc) I am met with an Operation Failed message. I have attached two screenshots showing what I mean.

![capture1](https://user-images.githubusercontent.com/38925849/39550671-0362382a-4e5a-11e8-8433-3741e6ce13ef.PNG)
![capture2](https://user-images.githubusercontent.com/38925849/39550673-04c6dc66-4e5a-11e8-9bf1-7b7b48380052.PNG)

I followed the link to Microsoft Support but the nice lady I spoke to had no idea what I was talking about! Eventually she pointed me to the MSDN forums although nobody has responded to my issue there. I have also e-mailed the Microsoft address to report broken features but have yet to receive a response. I've even tried tweeting the @OfficeDev but have been ignored! My last hope is that someone here may be able to offer advice or be in a position to get me in contact with the right people at Microsoft. Surely I cannot be the only person suffering from this issue!

I have been trying to get this running for over a week now and its holding up my personal progress. 

Many thanks.

**Comment by VesaJuvonen** [comment]
thx @Maplin83 for reporting. I'll route this internally to the right people so that you can proceed and getting valid Office 365 dev tenant. Sorry for the inconvenience and you should be expecting additional information here within 24 hours.

**Comment by mikeald** [comment]
@maplin83 Thanks for your report. I'm the senior program manager for the O365 Developer Program and I want you to know the team is working on investigating this right now. Sorry for the inconvenience.  I'd like to offer to work with you directly to troubleshoot this issue. What is the best way for me to contact you?

**Comment by mikeald** [comment]
@Maplin83 good news and thanks so much for including the screen shot of your error message that was super helpful to track down your case. Based on our investigation it looks like your profile you used is lacking a last name which is causing us to reject you in the sign up process. Got your email so you can remove that if you want.

Can you please add your first and last name to your Microsoft Account at https://account.microsoft.com/profile and try again later. It might take a few hours for the change to appear in the system. Then go through the process again.  If you still have issues let us know. I reach out to you in email so you know how to follow up with me.

**Comment by Maplin83** [comment]
Hello @mikeald, many thanks for that information. After updating my profile to include my surname, I was able to sign up to the Office 365 tenant. Many, many thanks to you and your team for looking into this issue and for getting back to me with a solution ASAP. I'm very impressed and hope that I may call upon you again if I need to. You guys are a credit to Microsoft!

**Comment by Maplin83** [comment]
Many thanks to @VesaJuvonen too for the support. This has been a successful first post :-)
