### ISSUE TITLE
Create a List fails

### ISSUE THREAD

**Issue by jonasbjor** [SharePoint/sp-dev-docs#1784]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I tried to create both a "TasksWithTimelineAndHierarchy" (ListTemplateType enumeration value = 171) and a "Task List" (ListTemplateType enumeration value = 107), both blank. Both attempts gave an error and the script failed.

#### Observed Behavior
![image](https://user-images.githubusercontent.com/32199921/39568457-a0b4d106-4ec2-11e8-8ab9-639d759ddc43.png)

Gave an error - unsupported
#### Steps to Reproduce
 {
      "verb": "createSPList",
      "listName": "ghfghfgh",
      "templateType": 107,
      "subactions": []
    }
 {
      "verb": "createSPList",
      "listName": "ghfghfgh",
      "templateType": 171,
      "subactions": []
    }

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Sorry for sounding ignorant here.  What method are you using to create the lists?

**Comment by seansquires** [comment]
Thanks for filing. We do support template 107, but not 171 currently. I'm not sure why you are seeing the bug for the base task list. Try removing the creation reference for 171 and let us know if you're still seeing the issue. Thanks.
