### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by siegfriedcw** [SharePoint/sp-dev-docs#1785]
"Branding out of the box navigation controls" link gives 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c4101b-5a36-e908-121f-8da71810f221
* Version Independent ID: 0938eb09-77e5-2ed6-2178-06541bd51898
* Content: [Proven Practices for SharePoint Online portal branding](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-branding)
* Content Source: [docs/solution-guidance/portal-branding.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-branding.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Appears fixed in commit 09a2b7d8a583c8f05525ab3b7aff768ce22d113b & just pending merge
