### ISSUE TITLE
Sample Links go nowhere

### ISSUE THREAD

**Issue by kenhansen01** [SharePoint/sp-dev-docs#1787]
Sample links all say the resource is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c011c50-a54c-872e-d687-846fdc80a7d4
* Version Independent ID: a373e7c8-a2cb-95e7-adf4-19327b223a47
* Content: [SharePoint workflow samples](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-workflow-samples)
* Content Source: [docs/general-development/sharepoint-workflow-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-workflow-samples.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
@kenhansen01 thanks for catching this!
