### ISSUE TITLE
SPFs applications stay constrained within the connected user permisions

### ISSUE THREAD

**Issue by gbordier** [SharePoint/sp-dev-docs#1789]
If my understanding is correct,  whatever permissions are granted to the SPF app, they will still be limited to the scope of what the connected user has permission for. So this is not a way for an app to do privileges elevation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
To clarify a bit: you don't grant any permissions to SharePoint Framework solutions. The solution works in the context of the current user and whatever the current user can do, the code inside the solution can do as well. Also, you can't elevate permissions in the SharePoint Framework solution's code, but you could call an external API and have it perform the additional operations with app-only context which could allow you to perform operations the current user is not allowed to do.

**Comment by andrewconnell** [comment]
@gbordier correct & @waldekmastykarz's comment adds additional context.
