### ISSUE TITLE
Column Formatting - SharePoint Online

### ISSUE THREAD

**Issue by tejasthite** [SharePoint/sp-dev-docs#1790]
Hi Team I am trying to add colors to cell as per the choice based column

3 types of choices 
Critical - Red 
Major - Orange
Minor - Green

I found the below script on the internet which i tried which does help but the colors are very light i need a darker background
{
    "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
    "elmType": "div",
	"font-weight":"bold"
    "attributes": {
        "class": {
            "operator": "?",
            "operands": [
                {
                    "operator": "==",
                    "operands": [
                        {
                            "operator": "toString()",
                            "operands": [
                                "@currentField"
                            ]
                        },
                        "Minor"
                    ]
                },
                "sp-field-severity--good",
                {
                    "operator": "?",
                    "operands": [
                        {
                            "operator": "==",
                            "operands": [
                                {
                                    "operator": "toString()",
                                    "operands": [
                                        "@currentField"
                                    ]
                                },
                                "Major"
                            ]
                        },
                        "sp-field-severity--blocked",
                        {
                            "operator": "?",
                            "operands": [
                                {
                                    "operator": "==",
                                    "operands": [
                                        {
                                            "operator": "toString()",
                                            "operands": [
                                                "@currentField"
                                            ]
                                        },
                                        "Critical"
                                    ]
                                },
                                "sp-field-severity--severeWarning",
                                {
                                    "operator": "?",
                                    "operands": [
                                        {
                                            "operator": "==",
                                            "operands": [
                                                {
                                                    "operator": "toString()",
                                                    "operands": [
                                                        "@currentField"
                                                    ]
                                                },
                                                "Blocked"
                                            ]
                                        },
                                        "sp-field-severity--severeWarning",
                                        "sp-field-severity--blocked"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    },
    "children": [
        {
            "elmType": "span",
            "style": {
                "padding": "0 4px"
            },
            "attributes": {
                "iconName": {
                    "operator": "?",
                    "operands": [
                        {
                            "operator": "==",
                            "operands": [
                                {
                                    "operator": "toString()",
                                    "operands": [
                                        "@currentField"
                                    ]
                                },
                                "Done"
                            ]
                        },
                        "CheckMark",
                        {
                            "operator": "?",
                            "operands": [
                                {
                                    "operator": "==",
                                    "operands": [
                                        {
                                            "operator": "toString()",
                                            "operands": [
                                                "@currentField"
                                            ]
                                        },
                                        "In progress"
                                    ]
                                },
                                "Forward",
                                {
                                    "operator": "?",
                                    "operands": [
                                        {
                                            "operator": "==",
                                            "operands": [
                                                {
                                                    "operator": "toString()",
                                                    "operands": [
                                                        "@currentField"
                                                    ]
                                                },
                                                "In review"
                                            ]
                                        },
                                        "Error",
                                        {
                                            "operator": "?",
                                            "operands": [
                                                {
                                                    "operator": "==",
                                                    "operands": [
                                                        {
                                                            "operator": "toString()",
                                                            "operands": [
                                                                "@currentField"
                                                            ]
                                                        },
                                                        "Has issues"
                                                    ]
                                                },
                                                "Warning",
                                                "ErrorBadge"
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
        {
            "elmType": "span",
            "txtContent": "@currentField"
        }
    ]
}

Please can some one help. Thank you

**Comment by thechriskent** [comment]
Thanks for your question! The format you are using above is very similar to the [Conditional Format](https://github.com/SharePoint/sp-dev-column-formatting/tree/master/samples/text-conditional-format) sample and relies on the sp-severity predefined classes. You are unable to adjust the colors used in the predefined classes.

A better sample to consult in your case would be the [Project Management Formats](https://github.com/SharePoint/sp-dev-column-formatting/tree/master/samples/generic-project-management) - specifically the [ryg-status.json](https://github.com/SharePoint/sp-dev-column-formatting/blob/master/samples/generic-project-management/ryg-status.json). This sample demonstrates setting a color value directly in the `background-color` style attribute based on the field's value. You can then easily change these colors to whatever specific color you need.

**Comment by tejasthite** [comment]
Excellent! That worked.

Thank you.

Tejas Thite
IS Support Consultant
tejas.thite@instem.com | +91 20 6792 9314 | +91 7507266487 |  instem.com
[cid:image003.png@01D3E6BB.D72ADE20]
[cid:image004.png@01D3E6BB.D72ADE20]302, Lalani Quantum, S. No. 322/A, PUNE Bavdhan (Budruk) 411021 INDIA
