### ISSUE TITLE
MSGraphClient still in preview?

### ISSUE THREAD

**Issue by jonthenerd** [SharePoint/sp-dev-docs#1791]
If MSGraphClient is in preview and should not be used in a production environment, and the "GraphHttpClient has been deprecated and should no longer be used" ... which should be used given SPFx v1.4.1? Is the MSGraphClient really still in preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2381d26e-96c9-44de-8e4e-f70edc2db498
* Version Independent ID: f81cacee-a1cd-89dd-ee53-c84689c03917
* Content: [Use the MSGraphClient to connect to Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph#feedback)
* Content Source: [docs/spfx/use-msgraph.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-msgraph.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Deprecation means that we are not investing in it anymore, but it's still supported. It's true that we are in transition to a new model and we openly want to communicate this direction in the documentation to avoid any surprises. **MSGraphClient is still in preview** and we'll talk about the updated timelines on that one in Build 2018 and in SPC 2018. We will absolutely update this documentation when the situation changes.

**Comment by anil-cyclotron** [comment]
MSGraphClient is officially launched now in November 2018
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph
