### ISSUE TITLE
Wrong design of local and online Workbench in mobile device preview

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1792]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Workbench in Mobile mode should fill the complete page and have only the required border.

#### Observed Behavior
When the workbench will be opened in mobile device tester or mobile device there is a border attached to the web part.

![wb-bug](https://user-images.githubusercontent.com/5503835/39603233-f0f31258-4f27-11e8-8a81-f3d8b00b9ffd.png)

When web part get opened on a regular page the border / margin is narrower.

<img width="392" alt="screen shot 2018-05-03 at 22 39 33" src="https://user-images.githubusercontent.com/5503835/39603286-1753bb3c-4f28-11e8-9ffd-09bf3db478d9.png">

From my opinion pages in SharePoint and the page used for the workbench should look similar in a mobile preview.

**Comment by patmill** [comment]
I'm going to close this, and let's open a discussion on hosted workbench futures.  It's clear that this feature is old and needs to be revamped or removed.  (iPhone 6?)  There is a lot of normal support in the browser tooling to do this as well.
