### ISSUE TITLE
How to with third party applications like Boomi

### ISSUE THREAD

**Issue by mdittakavi** [SharePoint/sp-dev-docs#1794]
Hi Team
we are using a iPAAS platform called  Dell Boomi where it has to pull the data using REST API from sharepoint list which has rich text columns.  The Boomi prccess runs on premesis and the IDE designer is cloud hosted.  we are using SharePoint 2016 Server On-prem with hybrid search and user profile configured.  
Do we need to setup OAuth with Low trust or with 'High Trust system.
we could not find the right article on how to configure ACS token server for SharePoint 2016 on prem. could you clarify above and provide me valuable link to setup ACS or low or high trust systems.
Does Azure ACS retirement on 1st November 2018 will impact this. what is the alternative instead of using Azure ACS for Boomi application to authorize to SharePoint REST end points

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b127c0-79c5-d7db-704d-c810f076024c
* Version Independent ID: a7386f53-5555-3785-a501-3b1c42cbd037
* Content: [Authorization and authentication of SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-and-authentication-of-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/authorization-and-authentication-of-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/authorization-and-authentication-of-sharepoint-add-ins.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mdittakavi** [comment]
Does Azure ACS retirement on 1st November 2018 will impact us. what is the alternative instead of using Azure ACS for my Boomi application to authorize to SharePoint REST end points

**Comment by frankchen76** [comment]
have you checked [Migrate from the Azure Access Control service - SharePoint Customers](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration#sharepoint-customers)? it has a specific section to mention about SharePoint use cases.

**Comment by andrewconnell** [comment]
The retirement of ACS will not impact SharePoint in this case... all the ACS "stuff" that SharePoint leverages is still in place and can be used. Ref: https://developer.microsoft.com/en-us/office/blogs/impact-of-azure-access-control-deprecation-for-sharepoint-add-ins

You don't configure ACS. SharePoint Server 2016 needs to be configured to support apps. You will then register an app in SharePoint as shown in this doc. Not familiar with the tool you reference, but it will need to authenticate with SharePoint (as the registered app) to obtain an access token to use in the HTTP GET request to the SharePoint REST API.

If there's no user involvement, you're likely looking at the high trust path.
