### ISSUE TITLE
The most allowing way to load external js library in web part

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1795]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a js app which is quite big and has many dependencies and the loading is complicated, it injects dependencies into head tag.

#### Observed Behavior

The library itself non-AMD and i checked it here https://rencore.com/sharepoint-framework/script-check/
I tried to follow this article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library
which also didn't help much
Is there any way to add this script and let it to do the job without getting into its way?

**Comment by waldekmastykarz** [comment]
What isn't working exactly?

**Comment by aslanovsergey** [comment]
On a ordinary web page library injects multiple dependencies scripts in head tag. When it's on a SPFx WebPart it breaks while doing this.

**Comment by waldekmastykarz** [comment]
How are you trying to add scripts to the head tag exactly and what errors are you getting?

**Comment by VesaJuvonen** [comment]
Closing due to no response.

**Comment by aslanovsergey** [comment]
@waldekmastykarz the script wants to interact with the script tag, developer of that script built some logic inside based on that there is <script type="text/javascript" src="//abc.com/customScript.js"></script> on the page. Loading script this wayhttps://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries doesn't seem to add script as script tag.

**Comment by waldekmastykarz** [comment]
Have you tried adding the script tag to the page yourself?

**Comment by aslanovsergey** [comment]
Yes, finally I've injected the into the page and waited until it's loaded. Worry was about it could be unsupported way.

**Comment by waldekmastykarz** [comment]
It's not recommended. Depending on what your script does, it might not work correctly when navigating between pages. Modern SharePoint UI uses partial page loading which might not work as expected with your script, so it's definitely something you should double check.
