### ISSUE TITLE
Error while associating site to hub site

### ISSUE THREAD

**Issue by Narendra91** [SharePoint/sp-dev-docs#1796]
While running Add-SPOHubSiteAssociation command in Powershell it is triggering error " the term Add-SPOHubSiteAssociation is not recognized as the name of cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2d3278-d6e5-9604-7905-23437b2f1f0e
* Version Independent ID: 936b2abc-f151-73ec-a95f-0d20c68c5c37
* Content: [Create SharePoint hub sites using PowerShell](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/create-hub-site-with-powershell)
* Content Source: [docs/features/hub-site/create-hub-site-with-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/hub-site/create-hub-site-with-powershell.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
That indicates that you do not have the latest version of the SharePoint Online PowerShell installed on your computer. You can download the latest version from https://www.microsoft.com/en-us/download/details.aspx?id=35588.
