### ISSUE TITLE
Error while installing SPFX solution using site scripts

### ISSUE THREAD

**Issue by Narendra91** [SharePoint/sp-dev-docs#1797]
While executing Install SPFX solution action using site scripts it is throwing an error
"Unable to handle action installSPFXsolution . No action handler is not registered for this action"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by falkin** [comment]
Same error unable to run action installSPFXSolution.

**Comment by cristina-pru** [comment]
Same error here. I'm working for a migration and I'd like to ask if there it is a timeline for this issue? It was working 3 or 4 weeks ago.

**Comment by christianteh** [comment]
you need to use installSolution instead of installSPFXsolution
