### ISSUE TITLE
SPFx List view command buttons on OneDrive page

### ISSUE THREAD

**Issue by ManiKum** [SharePoint/sp-dev-docs#1798]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The SPFx list view command buttons show up on OneDrive page

#### Observed Behavior

The command buttons show up on any normal list page (ending with allitems.aspx). But not on OneDrive page. 

#### Steps to Reproduce

I’m able to reproduce the behaviour following the sample here https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api
(running in debug mode)

List page shows the Command One and Command Two buttons from the SPFx app:
![working](https://user-images.githubusercontent.com/28635362/39629800-61b447f2-4f7b-11e8-84ab-57a1621092de.jpg)

OneDrive page doesn’t show the Command buttons:
![non-working](https://user-images.githubusercontent.com/28635362/39629780-546fb8b0-4f7b-11e8-871f-2c52998e6f4f.jpg)

This looks like expected behavior as OneDrive is using its own style of displaying the list through system page (OneDrive.aspx) while a normal list page is using AllItems.aspx page for display. Is that understanding correct? 
Is there a way to show command buttons on a OneDrive page through SPFx app?

**Comment by VesaJuvonen** [comment]
SharePoint Framework is not supported within OneDrive for Business. This is through a good feature ask, so would suggest submitting an entry to the UserVoice at http://aka.ms/spdev-uservoice
