### ISSUE TITLE
SPFX OnPremise Illegal Rule Inserted

### ISSUE THREAD

**Issue by johnfabian** [SharePoint/sp-dev-docs#1799]
When I deploy my SPFX web part OnPremise my console is flooded full of 

sp-classic-page-assembly_en-us.js?version=1:385 whoops, illegal rule inserted @-o-keyframes animation_tply6e{from{-webkit-transform:rotateZ(0deg);transform:rotateZ(0deg);}to{-webkit-transform:rotateZ(-90deg);transform:rotateZ(-90deg);}}

and a big huge message WARNING 

Use of this tool exposes you to potential security threats which can result in others gaining access to your personal Office 365 data (documents, emails, conversations and more). Make sure you trust the person or organization that asked you to access this tool before proceeding.

Is there a way to remove this? I'm getting this even when I deploy to Production and the other developers are thinking it is something with my code as well as our cyber security is freaking out.

**Comment by VesaJuvonen** [comment]
There's no way to remove these. The warning is aligned for example on what Facebook and others do to ensure that inexperienced end users would not follow random messages from the Internet.
