### ISSUE TITLE
`gulp serve` always opens a new tab in browser

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#180]
#### Category

[ ] Question
[ ] Typo
[x] Bug
[x] Enhancement / Suggestion
[ ] Additional article idea
#### Expected or Desired Behavior

When `gulp serve` will be executed no new browser tab should be open when there is already a browser tab that contains the workbench. Please make sure that only on instance of that windows runs.
#### Observed Behavior

When ever `gulp serve` will be exectued a new browser tab open even if workbench is already launched in another tab.

**Comment by iclanton** [comment]
To prevent `gulp serve` from opening a new browser instance, you should run `gulp serve --nobrowser`.

**Comment by StfBauer** [comment]
@iclanton This doesn't solve the problem neither is it a workaround. If those window issues cannot be handled by gulp-connect it might be better to have --no-browser as default open and --browser as optional.

Most yeoman generators I've seen supports to open in the same browser window once gulp serve or similar task have been restarted. The mostly use more advanced development web server.

**Comment by patmill** [comment]
Hey Stefan - at this point we're going to lean towards making it easy for devs less familiar with the client type tools.  If you feel strongly, let us know.  Perhaps we can make it easy for you to specify options for your scenario (ie, you state that for your project, gulp server has --no-browser as a default param.
