### ISSUE TITLE
Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by schurlinga** [SharePoint/sp-dev-docs#1801]
Instead of: _renewStates = _renewStates.split(';');
use: _renewStates = _renewStates.split(',');

This can cause the error: Token renewal failed due to timeout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc6b567-0762-fb88-e9f6-11482e81a5b2
* Version Independent ID: c64e977e-5adf-e31d-955b-1bafae3e9006
* Content: [Call the Microsoft Graph API using OAuth from your web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part)
* Content Source: [docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by adaddeo** [comment]
This does seem to be an issue and the suggested fix worked for me.
