### ISSUE TITLE
403 Forbidden: For Post Requets : Call Secured Azure aPI from SPO

### ISSUE THREAD

**Issue by ashokswain27** [SharePoint/sp-dev-docs#1802]
#### Category

- [ Bug]: When we are making POST request using SPO auth cookie approach, getting a 403 Forbidden response. HTTP "GET" request is working fine. I have follwed the below blog to make it work for "GET" methods. Any insight for this issue?
https://stephaneeyskens.wordpress.com/2015/05/18/consuming-azure-hosted-web-api-from-sharepoint-online-using-javascript-and-office-365-identities/
>
#### Steps to Reproduce
Followed the same steps as explained in this artcile. GET method is returning the correct result.
POST method is retruning 403 error.
https://stephaneeyskens.wordpress.com/2015/05/18/consuming-azure-hosted-web-api-from-sharepoint-online-using-javascript-and-office-365-identities/
$.ajax({
 url: "API URL",
                type: 'POST',
                dataType: 'json',
                contentType: "application/json; charset=utf-8",              
                crossDomain: true,
                xhrFields: {
                    'withCredentials': true
                }
 
>

**Comment by VesaJuvonen** [comment]
That article is from 2015 and there have been some changes to the model. We would recommend following the updated guidance from following article - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi. This shows the recommended pattern with SharePoint Framework.
