### ISSUE TITLE
Are these instructions correct?

### ISSUE THREAD

**Issue by AndyWDev** [SharePoint/sp-dev-docs#1807]
The instuctions for downloading a site template to a file do not seem to be correct.  Step 4 suggests activating the solution before downloading it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5f465-6d87-5a7d-9b0a-7807da51d30b
* Version Independent ID: bc4f4c42-d5ba-a36a-1578-70103e14cde8
* Content: [Save, download, and upload a SharePoint site as a template](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template)
* Content Source: [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Saving a site as a template is STRONGLY discouraged... this is old documentation and I'm checking if it should be removed from the site. Too many things have changed over time where this is no longer recommended.

The proper way to provision new sites is not to use web templates, but to provision using the PnP provisioning or via site designs/site scripts

**Comment by andrewconnell** [comment]
To clarify...

- supported in SharePoint on-premises including
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 201 *classic sites only*
- not supported & not recommended in SharePoint Online
- not supported & not recommended for modern sites in SharePoint Server 2019

I'll get the doc updated to reflect this.
