### ISSUE TITLE
Will SPFx extension automatically added to the newly created subsite?

### ISSUE THREAD

**Issue by Wayne-Shen** [SharePoint/sp-dev-docs#1809]
Will SPFx extension automatically added to the newly created subsite? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c136778d-54ad-5155-3ce7-ed40f9a1ba2b
* Version Independent ID: 65021293-571f-fac6-d5f1-6190e27b1331
* Content: [Tenant-scoped solution deployment for SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-scoped-deployment)
* Content Source: [docs/spfx/tenant-scoped-deployment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tenant-scoped-deployment.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This slightly depends on exactly content of the extension. Technically you would get the sub-sites to render any application customizer extension as long as you associate that to the site collection level, which we do not do in the default tutorials. This would mean that as the extension is associated with Site.UserCustomAction collection, any sub-site would render that automatically. Also - in Build 2018 we announced an upcoming availability of global deployment support for extensions, which will give you an opportunity to configure extensions to be rendered globally on all sites - regardless if they are root or sub-sites.

**Comment by siddharth-vaghasia** [comment]
@VesaJuvonen .... 

"This would mean that as the extension is associated with Site.UserCustomAction collection, any sub-site would render that automatically."

Do we need any special configuration in extension manifest file to associate it with subsites... I noticed that extensions are not running on already created subsites under SC.... App was deploye in app catalog and installed on SC...extension runs on SC pages but not on subsites.... 

Sorry to comment on an old issue, but it seems related to original question... so putting it here...

**Comment by VesaJuvonen** [comment]
This issue has been closed and would not recommend to add any comments on already closed issues as it's highly unlikely that nobody will notice your question... this is now an exception. Please submit new issues always.

There's no way to define extension to be deployed in site collection level using existing xml files. You'd need to do this using APIs.
