### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by expo8282** [SharePoint/sp-dev-docs#1811]
The 'Capacity planning and load testing SharePoint Online' link is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
thx @expo8282, link fixed now.
