### ISSUE TITLE
Is it possible to provide layouts, pages on site designs !? 

### ISSUE THREAD

**Issue by valentinbourqui** [SharePoint/sp-dev-docs#1812]
On your documentation you say that you can create site designs to provide layouts, pages. But i see nothing about this somewhere. 

Not enough available ? Error doc ?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a433bf-b243-03ff-f733-484dca2be753
* Version Independent ID: 7a173ed3-1700-b24f-ee78-417dd494ce16
* Content: [Get started creating SharePoint site designs and site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design)
* Content Source: [docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/get-started-create-site-design.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jagKakarlapudi** [comment]
Good point ymihir 

I would like to know how to provision a reusable modern page and set it as a homepage.

@vesa - Is this supported yet (as per the documentation) or is this in the dev roadmap? Alternately please suggest us what is the current recommended path to achieve this use case. 

Thank You. 
Jag

**Comment by iamguptarishi** [comment]
I have raised an issue on Github. https://github.com/SharePoint/sp-dev-docs/issues/3038
It seems that schema has option to create a page using verbs but, framework is throwing error when setting ClientSideApplicationId. The verb used in site scripts for creating page is "createPage". This might be addressed in future.

**Comment by andrewconnell** [comment]
A comment from MSFT in the referenced issue #3038 states this is not currently supported at this time.
