### ISSUE TITLE
SPFX workbench, button to apply layouts from team or communication sites

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#1813]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Enhancement

#### Expected or Desired Behavior
I'd like to have a button in the workbenches (local, online) to allow me to apply the "layout" (different boxes sizes, flowing behavior, etc) of a team site or a communication site so I can double check rendering of my webpart works well with production dimensions, flowing behavior etc...

#### Observed Behavior
Today the only way to try to mimic that is the tablet mode in the workbench, the browser debug tools or just resizing the window. This offers a poor experience and doesn't guaranty me my webpart is in the same rendering context.

#### Steps to Reproduce
N/A

**Comment by VesaJuvonen** [comment]
Thx @baywet, but as this is an enhancement, we would ask it to be created to the UserVoice, so that it falls on the right process. You can find the right location from http://aka.ms/spdev-uservoice.

**Comment by baywet** [comment]
right, sorry about that. Here is the post @nickvdheuvel if you want to upvote https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/34211683-workbench-allow-to-change-size-of-the-canvas-to-m
