### ISSUE TITLE
Previously working C# code stopped working with 403 Unauthorized when accessing REST api in SharePoint Online

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#1814]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We used the following code for more than a year, without any problem.
```
private const string BaseUrl = "https://contoso.sharepoint.com/sites/teamsite/";
private const string UserName = "user@contoso.onmicrosoft.com";
private const string Password = "";

var encoded = new SecureString();
foreach (var c in Password)
{
   encoded.AppendChar(c);
}

var credentials = new SharePointOnlineCredentials(UserName, encoded);
using (var client = new WebClient { BaseAddress = BaseUrl, Credentials = credentials, Encoding = Encoding.UTF8 })
{
   client.Headers.Add(HttpRequestHeader.Accept, "application/json");
   client.Headers.Add(HttpRequestHeader.ContentType, "application/json");

   var json = client.UploadString("_api/contextInfo", "POST");

   var token = JToken.Parse(json);
   var tokenValue = token["FormDigestValue"].ToString();
}
```
I had this issue reproduced with HttpClient as well.

#### Observed Behavior
Today, and on two separate SharePoint Online tenants, this code started returning `403 (Unauthorized)`

Adding the following line in the code fixes it:
```
client.Headers.Add(HttpRequestHeader.Cookie, credentials.GetAuthenticationCookie(new Uri(baseAddress)));
```

How comes this suddenly changed? What is supposed to be the correct way of working (old code vs current 'fix')?

**Comment by chackman** [comment]
Could you please provide a correlation ID and time from the request that returned a 403?

**Comment by chackman** [comment]
Check the response headers for a SPRequestGuid header

**Comment by YannickRe** [comment]
Aha, helpfully named, I see. Thank you, now I could find it.
Correlation Id: 1f33669e-1054-5000-e739-3c066e360e66
Date header: Fri, 11 May 2018 21:04:38 GMT

**Comment by chackman** [comment]
Note: OAuth is a much better way to go if you are writing an external application, provider-hosted add-in, etc., that accesses SharePoint REST API's.  OAuth is mentioned in samples including [Authorization and authentication of SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-and-authentication-of-sharepoint-add-ins) and [Complete basic operations using SharePoint REST endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints).


The original code, as-is, would be unlikely to work.  You might see examples online that set an X-FORMS_BASED_AUTH_ACCEPTED header, and others that get a cookie like you're doing now.
