### ISSUE TITLE
Fetch term set id , when mapping it to userprofile property

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1819]
I have a termstore where i have termsets example Department.
Now i have mapped this department to user profile property.
I am only able to fetch string i.e value but how can i fetch the guid of term set ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab4dee5e-5144-cc2f-8bcf-1a240040ad02
* Version Independent ID: 82eb8cb1-43f2-11cb-053b-94acfde8e84e
* Content: [Retrieve user profile properties by using the JavaScript object model in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-javascript-object-model-in)
* Content Source: [docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-javascript-object-model-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-javascript-object-model-in.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by luismanez** [comment]
Pretty sure you can´t. Unfortunately, the Taxonomy fields are only stored as Plain Text in the User profile, so if you want the ID, you have to query the TermStore service by Name (which obviously is not great)

**Comment by harshdamaniahd** [comment]
Yes, Even if i fetch it using Name , the problem is the term name is repeated
like
Department - Termset
      Accounting - Termname
            HR - subterm
     Marketing - Termname
           HR - subterm


So if i search for "HR" then it will result in two values which is another problem.

Is there any way of doing it using .Net CSOM ?

**Comment by luismanez** [comment]
CSOM is not helping either, as the problem is that the value is always store as plain text by SP User profile service (in the past and on premises, I even remember to search it in the SQL DB, and there´s no GUID)
Anyway, Don´t you have the entire term name stored? i.e: "HR - SubTerm 1". If you do a search in the specific TermSet with that full name, you should get only one Term, right?

**Comment by harshdamaniahd** [comment]
Thanks for quick reply @luismanez 
the problem is that, the data is stored in such format : 
![image](https://user-images.githubusercontent.com/11780473/39806866-8ec146c0-5398-11e8-970a-ea663cc974c9.png)
Now assume that in user profile the value is stored as "**HR**", now in order to get the **guid** if i search in **taxonomy (by name)** , I will get **two** results.

So i guess one solution is to make name unique :

![image](https://user-images.githubusercontent.com/11780473/39807075-12da968c-5399-11e8-88af-a52682f9c214.png)

**Comment by luismanez** [comment]
I see. Yeah, I´m afraid there´s no other solution that set a "unique" name in the TermSet (at least I´m not aware of any other one)

**Comment by Rafaelki** [comment]
I know this is an old question but, is this affirmation (still) true?

> Unfortunately, the Taxonomy fields are only stored as Plain Text in the User profile

If so, how is it possible that in the Search we can write a query using, for example, {User.SPS-Department.ID} or {User.SPS-Department.IDWithChildren}? I can see in the QueryModification that the IDs are correct, even when the same label exists on different parents.

**Comment by andrewconnell** [comment]
FYI - [Issue List - Our approach to closed issues](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#our-approach-to-closed-issues)
