### ISSUE TITLE
Native mobile app prompting login - browser is fine?

### ISSUE THREAD

**Issue by butchmarshall** [SharePoint/sp-dev-docs#1820]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The user should not need to log in again using the native mobile app

#### Observed Behavior

The user is prompted with a login screen.

#### Steps to Reproduce

1. Use adal-angulars implicit oauth to fetch a JWT token
2. Rather than being redirected back to the the app screen the user is prompted to log in again

This is not the same behaviour observed when accessing the app while logged into the SharePoint website (only redirects, no login prompt).

![screenshot_20180509-084852](https://user-images.githubusercontent.com/339763/39815754-1a09eaa2-5367-11e8-8262-e6213d1371fd.png)

**Comment by butchmarshall** [comment]
Any official response on this?  We're close to our launch date and this is a show stopper for us.

**Comment by patmill** [comment]
Sorry - going through old issues.  We're not really sure what this is referring to.  Given that it is 3+ years old, we're going to close this.  Feel free to create a new issue if you are having problems with SPFx solutions.
