### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by MercerK** [SharePoint/sp-dev-docs#1822]
"92% of Branding SharePoint is CSS, So Why Are You Living in a Master Page?" takes you to a 404.

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-branding

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c4101b-5a36-e908-121f-8da71810f221
* Version Independent ID: 0938eb09-77e5-2ed6-2178-06541bd51898
* Content: [Proven Practices for SharePoint Online portal branding](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-branding)
* Content Source: [docs/solution-guidance/portal-branding.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-branding.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I don't see the text referenced in this doc... maybe it was updated after you left this comment? If you can provide more detail, we can get the link fixed, but looks good to me right now...
