### ISSUE TITLE
targetUser issue

### ISSUE THREAD

**Issue by ng-react-mohit** [SharePoint/sp-dev-docs#1824]
const string targetUser = "domainName\\\\userName";  should be in the format 
 const string targetUser = "domainName\\userName";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56dda6a-30c8-14dc-1123-bb939b525caf
* Version Independent ID: 52f82d49-4302-ee01-df31-66b299adbeaf
* Content: [Retrieve user profile properties by using the .NET client object model in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in)
* Content Source: [docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ng-react-mohit** [comment]
Instead of having 4 \ it should have 2 \

**Comment by VesaJuvonen** [comment]
Thanks for the heads up. Fixed to md doc and will be fixed in the real site within next 15 min.
