### ISSUE TITLE
NPM 6 - Security audit and possible issues getting now reported

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#1826]
## Category

- [x] Question
- [x] Bug
- [x] Enhancement

## Observed Behavior
I know that this will not a short time fix but recently I upgraded to NPM version 6.x.x. I created today a new SPFx project and got the following report of security issues.

<img width="648" alt="screen shot 2018-05-09 at 21 58 16" src="https://user-images.githubusercontent.com/5503835/39837456-dcdb10e6-53d6-11e8-91ff-688b63327ad4.png">

I also know that this has no impact on SPFx deployed solution and has only on the build pipe but I guess some people are not aware of this.

## Steps to Reproduce
Install NPM 6.0 create new project or run:

```
npm audit
```

**Comment by VesaJuvonen** [comment]
Thanks, Stefan, noted and acknowledge with the right people. Closing this one as there's really nothing precisely to be done right now as 6.0 is not yet supported. This helps though with heads-up on things to double check. Thanks for that.

**Comment by StfBauer** [comment]
Thank you @vesa. Blogged about it yesterday https://n8d.at/blog/npm-6-0-and-sharepoint-framework-security-reporting/
Will add a remark that it is not officially supported yet.

**Comment by guillaume-kizilian** [comment]
It isn't clear to me :

Are you saying that there is no security issues using these packages the way spfx does or it is unsure if there is security issues?

Thx.

**Comment by waldekmastykarz** [comment]
The reported issues change regularly as packages are being updated new issues are being discovered so if you want to be sure that none of them affects your organization, you would have to evaluate your solution at the given point in time and lock its dependencies.
