### ISSUE TITLE
webApiPermissionRequests error to deploy in appCatalog

### ISSUE THREAD

**Issue by m4rt1ncr** [SharePoint/sp-dev-docs#1827]
I tried to deploy a spfx webpart to test MSGraphClient but i get an error when upload the sppkg file

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

The image
![image](https://user-images.githubusercontent.com/13367591/39843128-50660106-53af-11e8-9d79-8375f9dda0dd.png)

My package-solution file is the next:

{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "test-graph-client-side-solution",
    "id": "5d9ec4ea-875e-4389-a19d-d74605f9d9f8",
    "version": "1.0.0.14",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.Read"
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/test-graph.sppkg"
  }
}

Regards

**Comment by VesaJuvonen** [comment]
Unfortunately, we can't reproduce this with the provided details. Can you check if there are more details on the error by hovering on the column etc... as I think there should be, so that we can try a repro.

**Comment by VesaJuvonen** [comment]
Closed due no response.
