### ISSUE TITLE
Make webpack loader available for configuration

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#183]
#### Category

[ ] Question
[ ] Typo
[x] Bug
[x] Enhancement / Suggestion
[ ] Additional article idea
#### Expected or Desired Behavior

Currently the use of the new SharePoint Framwork has only limited use. When a custom web pack loader is required I can define my own web pack configuration. In this case all needs to be handled manual.

**Comment by patmill** [comment]
It is on the roadmap.  We'll comment soon in more detail.

**Comment by patmill** [comment]
Posted a while ago on how to do this.  Marking as resolved.  (https://github.com/SharePoint/sp-dev-docs/wiki/Extending-Webpack)
