### ISSUE TITLE
wrong API URI

### ISSUE THREAD

**Issue by agcunha** [SharePoint/sp-dev-docs#1830]
The api uri for query suggestion is _api, not api

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e106f28c-4a06-f54c-d965-3b8ff2ff77da
* Version Independent ID: f576ccc9-59c0-6e38-bf66-e0a579f01583
* Content: [Recuperando as sugestões de consulta usando o serviço de pesquisa restante](https://docs.microsoft.com/pt-br/sharepoint/dev/general-development/retrieving-query-suggestions-using-the-search-rest-service)
* Content Source: [docs/general-development/retrieving-query-suggestions-using-the-search-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/live/docs/general-development/retrieving-query-suggestions-using-the-search-rest-service.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Don't believe this is correct... the doc is correct in saying the endpoint is `_api`.
