### ISSUE TITLE
Unable to add links to blank Hub Site navigation

### ISSUE THREAD

**Issue by 365Iain** [SharePoint/sp-dev-docs#1831]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When clicking 'Add Link' in a Hub Site Navigation bar that has no links you should be able enter a URL and Title for the link in the dialog that appears. You should then be able to save and see the link in the Nav bar.

#### Observed Behavior

When adding a link from the dialog the navigation side bar is blank and therefore no link is added to the Hub Nav. To workaround you need to cancel the dialog and then click the + in the side bar to get a new dialog which allows links to be added correctly.

#### Steps to Reproduce

Go to any Hub Site that doesn't have any links in the Hub Nav and click 'Add Link'. Add a URL and title in the box that appears and click OK.

The Hub nav has an 'Add Link' option as there are no existing links. The default dialog shown does not add a link to the sidebar, and by extension Hub nav, after clicking OK.

![image](https://user-images.githubusercontent.com/29796236/39874815-cda39144-5466-11e8-8bed-af53f863238b.png)

This works fine as there is an existing link and 'Edit' does not trigger a dialog to add a link automatically.
![image](https://user-images.githubusercontent.com/29796236/39874644-4fa747ea-5466-11e8-95c6-fcfac56e824e.png)

**Comment by ecraig12345** [comment]
Thanks for reporting this! I've checked in a fix, which should roll out in the first week of June.

@VesaJuvonen FYI

**Comment by RichBurdes1** [comment]
As of writing 2 x Hub sites created on 13/09/2018 exhibit the same issue - cannot add links to the navigation - the option exists, you get a pop up click save, then links dont update. 
Cheers

**Comment by docwisdom** [comment]
Same issue here

**Comment by baskb** [comment]
Me too.

**Comment by pbowens** [comment]
I was having this issue too. Try adding a link from a document library page or a list page (not a normal page). It opens up the add link in a slightly different spot, but worked for me.

**Comment by fchopo** [comment]
Same issue here too!

**Comment by diver7** [comment]
Same issue here too. We need this fixed ASAP!

**Comment by docwisdom** [comment]
@diver7 I can confirm that @pbowens workaround does in fact work!

**Comment by baskb** [comment]
Yes, workaround worked for me too.

Op ma 17 sep. 2018 om 06:19 schreef maruthigadde <notifications@github.com>:

**Comment by mmohamedbasith** [comment]
> Thanks for reporting this! I've checked in a fix, which should roll out in the first week of June.
> 
> @VesaJuvonen FYI

I See that same issue again in my tenant (dec 2018). Unable to add blank link . @VesaJuvonen @ecraig12345

**Comment by rdnllc** [comment]
Trading the workaround (thanks for those that found and posted it), or the intire hub global nav interface for the richness of term store navigation interface borders on byzantine torture!  The concept of hub site global navigation is laudable, but the interface is deplorable!

**Comment by KSteenis** [comment]
Experiencing this same issue in our tenant. Link to /search.aspx not responsive from homepage, but responsive from other site elements.
