### ISSUE TITLE
Javascript error on SharePoint Framework webparts in classic pages

### ISSUE THREAD

**Issue by JohnnyKapps** [SharePoint/sp-dev-docs#1832]
#### Category

[x] Bug

#### Observed Behavior
Since yesterday, multiple javascript errors are ocurring in all classic pages that contains SPFx webparts on my tenant. 

![image](https://user-images.githubusercontent.com/976613/39882820-4ef92850-545b-11e8-93cc-3f77ed059b4e.png)

These errors occurs in a file called "https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-04-27.028/sp-classic-page-assembly_pt-br_2b70de5aeec66500455fe2dbb40e063f.js" and only happens on classic pages. The same webparts works well on modern pages...

Anyone know how to solve it? Thanks!

**Comment by patmill** [comment]
Sorry for the long delay - I'm assuming that this has been addressed for a long time.  If you are still running into issues, please open a new issue.
