### ISSUE TITLE
Apps stuck in "we are adding your app", "we are updating your app", "we are deleting your app"

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1833]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Adding/Updating/Removing apps from the site takes too long.
It's not very consistent.
So, for example, today around 9:30 AM PST I was waiting around an hour to remove the app.
Then, a bit later, the adding/removing worked as expected - few seconds.

Now (11:00 AM) it is hanging again.

Maybe it is related to timer jobs schedule or something...

Similar issue that has been closed in Feb: [#1325](https://github.com/SharePoint/sp-dev-docs/issues/1325)

#### Expected or Desired Behavior

Apps are added/updated/deleted relatively in real-time

#### Observed Behavior
Apps hang in adding/updating/removing state for a while (could take about an hour)

#### Steps to Reproduce

- add any .sppkg package to app catalog
- on the site collection "Add an app"

**Comment by VesaJuvonen** [comment]
Closed due to no response for now. Let's re-open if needed.
