### ISSUE TITLE
Docs for PnP-Powershell out of date

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#1839]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Are the docs up to date, for this article:
https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps

This is showing as 28/11/2017 on the article date.

**Comment by VesaJuvonen** [comment]
PowerShell md documentation is updated once a month based on the code (md files are generated directly from code). So - yes - they are up to date. The latest update was merged earlier today at https://github.com/MicrosoftDocs/office-docs-powershell/pull/970.
