### ISSUE TITLE
why i can't deploy to doc lib? Buttons still show up in custom list

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#1841]
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="HelloWorldCommandSet"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet"
        ClientSideComponentId="422de19f-6007-474b-9d4d-b880595b0291"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
</Elements>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jemsjose** [comment]
To add the Buttons to Document Libraries, change RegistrationId="101" in the Elements File located at "sharepoint\assets\elements.xml". Hope this helps.

**Comment by pavogel** [comment]
@VesaJuvonen - The article elements.xml snippet uses RegistrationId="100" which seems to indicate a List, yet the example CommandSet screenshot shows a Document Library.  While this works for testing on localhost, it will not work for Document Libraries when deployed to the AppCatalog and added on a child site for some strange reason.  The only way we could get our CommandSet to work for both Lists and Document Libraries simultaniously was to put two <CustomAction/> containers in our elements.xml with RegistrationId attribute values 100 and 101.  e.g. 

<CustomAction
...
	RegistrationId="100"
...
</CustomAction>
<CustomAction
...
	RegistrationId="101"
...
</CustomAction>

Thanks @jemsjose, without your comment, we may never have realized that RegistrationId 101 signified Document Libraries.

**Comment by jayminpatel81** [comment]
Is instructions complete? I am creating all instructions and I do not see command bar in view. Any idea?

**Comment by andrewconnell** [comment]
Seems the question was answered...

@jayminpatel81 there were issues with extensions loading for a time being, but they should be resolved. If you are still having an issue, please open a new issue.
