### ISSUE TITLE
Doesn't work when sppkg file is deployed to site collection app catalog

### ISSUE THREAD

**Issue by mpowney** [SharePoint/sp-dev-docs#1842]
During my experimentation today (May 13th 2018) on a targeted release dev tenant, I've found the custom web part only appears in the full-width column web part picker if I've uploaded the SPFx package with includeClientSideAssets equal to "false" in ./config/package-solution.json.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4825eeab-f123-c0fb-0d30-6d634c821bd2
* Version Independent ID: 55d7e710-4faa-4cfa-772d-f83962d9fe52
* Content: [Use web parts with the full-width column](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column)
* Content Source: [docs/spfx/web-parts/basics/use-web-parts-full-width-column.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/use-web-parts-full-width-column.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mpowney** [comment]
The above seems to be true for the SPFx package being uploaded to both the tenant's app catalog, and also to a Site Collection app catalog

**Comment by mpowney** [comment]
It was a webpart created from the latest yo generator 4 days ago.  Here's a gist of the important files:
https://gist.github.com/mpowney/3c0d8285208b11dc9cd388d600c60d06

I'll try building the ColumnFormatter solution later today and let you know what I find

**Comment by mpowney** [comment]
Following up on this - I've tried with SPFx 1.5.1 - I think the problem I've found occurs when I deploy the full bleed web part in a solution added to a site collection app catalog instead of the tenant app catalog.  The steps to reproduce this behaviour are as follows:

1. Use the latest yo generator to generate an SPFx 1.5.1 solution with a React based web part, auto deploy to tenant remains as default value (no)
2. Update the web part's manifest file - add the "supportsFullBleed" property below "requiresCustomScript"  and specify as true
3. Ensure the package-solution.json file has "includeClientSideAssets" set to true
4. Create a new modern site (Blank communications site)
5. Use the office365-cli or PnP PowerShell cmdlets to enable an app catalog on the new comms site
6. Wait a minute or two for the app catalog to complete its provisioning
6. Load the SPFx solution in to the site's app catalog - drag and drop in to App Catalog library, trust the solution
7. Add the app to the site collection's root web
8. Edit the site's home page
9. Add a full width section to the page

Observations
1. At this point, the icon for the new web part displays in the page's edit mode in the full width column
2. Clicking on the web part's icon to add it to the page results in a "Loading" spinner, but nothing further happens
3. Performing a browser refresh of the page and going back in to Edit mode, the web part is no longer shown as an option in the full width section

If I perform the same steps above and deploy the same sppkg file to the tenant app catalog, the full bleed web part behaves as expected.

Can anyone else confirm this behaviour?

**Comment by phatmike11** [comment]
When you include includeClientSideAssets="true" in the documentation it says 

> If you would not have CDN enabled in your tenant, and the includeClientSideAssets setting would be truein the package-solution.json, the loading URL for the assets would be dynamically updated and **pointing directly to the ClientSideAssets folder located in the app catalog site collection**. In this example case, the URL would be https://sppnp.microsoft.com/sites/apps/ClientSideAssets/. This change is automatic depending on your tenant settings and it does not require any changes in the actual solution package. 

However, if you look at that URL that is the application catalog for the tenant not the app catalog for the site collection.  So maybe this settings is not supported for site collection app catalog?  If I find out anything else I will let you know.

[https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn](url)

**Comment by andrewconnell** [comment]
Is this issue still present? I saw where a fix was rolled out in a recent version of SPFx / SPO that may have addressed this...

**Comment by mpowney** [comment]
I haven't been paying a lot of attention lately, but in an sppkg we use across a number of tenants (including first release tenants), I've found our full bleed web parts to intermittently show or not show. My general perception is the full bleed web part selection, in page edit mode, is still a bit buggy. 

Can you provide a specific reference to the fix @andrewconnell? 

I'll see if I can be more specific about the circumstances it doesn't show...

**Comment by andrewconnell** [comment]
@mpowney said:
> Can you provide a specific reference to the fix @andrewconnell?

Sorry, I can't... I don't have a reference to point to.

I have seen two other issues that might be related... can you review and see if they are related? #1779 & #1428
