### ISSUE TITLE
Modern site page content type is still sealed on existing sites

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1843]
#### Category
- [X] Question
- [X] Bug

#### Expected or Desired Behavior
In new sites the modern site page content type is not sealed anymore which is good for adding metadata to site pages and building custom solutions around this capability.

#### Observed Behavior
In existing sites though it is still sealed and thus you can not really build solution that work on existing as well on new sites.

Are there any plans to change this? Is there a way to manually or programatically change this on existing sites?

**Comment by AlexRademeyer** [comment]
any news on this?
I think I am experiencing the same problem.
I cannot add a column to the default "site page" content type on my new site- this is a modern site but it is a sub-site of an old, existing, classic-style site.
