### ISSUE TITLE
Tutorial 1, step 6

### ISSUE THREAD

**Issue by dmcrock** [SharePoint/sp-dev-docs#185]
In Tutorial one step six, it says this:
Step 6: Preview web part in SharePoint

So far, we have previewed the web part in the Web Part Workbench hosted locally in your machine.

SharePoint Workbench is also hosted in SharePoint to preview and test your local web parts in development. The key advantage is that now you are running in SharePoint context and that you will be able to interact with SharePoint data.

Navigate to the following URL: https://your-sharepoint-site/Shared%20Documents/workbench.aspx

By default, your browser is configured to not load scripts from localhost. Workbench will notify you if that is the case:

I just re-made a new developer tenant and it says that this file "URL: https://your-sharepoint-site/Shared%20Documents/workbench.aspx" does not exist. Are we supposed to copy the workbench.html and rename to workbench.aspx and upload it? if so there are zero instructions on this.

Should workbench already be in the tenant?
Thank you
Doug Clelland

**Comment by patmill** [comment]
Yes, at the end of this page (https://github.com/SharePoint/sp-dev-docs/wiki/Setup-SharePoint-Tenant) it goes over setting up the workbench in SharePoint.

**Comment by dmcrock** [comment]
@patmill  Thank you Pat, i must have missed that piece.

**Comment by dmcrock** [comment]
@patmill Pat, I followed the instructions (and using chrome) eve after clicking the 'load unsafe scripts' i am getting this error
![image](https://cloud.githubusercontent.com/assets/547769/18527918/fb27d2f6-7a83-11e6-906c-a1d74deacb27.png)

**Comment by dmcrock** [comment]
and i looked and manifests.js is in the temp directory

**Comment by patmill** [comment]
You need to run the workbench locally first, accept the cert (twice), then you can launch from SharePoint

**Comment by dmcrock** [comment]
10-4 i am sure I did that, but will re-do to test

**Comment by dmcrock** [comment]
So its a no go. I cleared all cookies/cache and temp internet files and restarted. When running gulp serve opens Chrome and no certificates to accept

**Comment by patmill** [comment]
If you check your serve.json file in your config folder, what is your https and port settings?

**Comment by dmcrock** [comment]
this is what I have:
{
port: 4321,
initial page: http://localhost:5432/workbench
api:
port: 5432
entryPath: node_modules/@microsoft/sp-webpart-workbench/lib/api
}

**Comment by patmill** [comment]
Hmn, was that made with Drop 1?  Can you try this:

{
  "port": 4321,
  "initialPage": "https://localhost:5432/workbench",
  "https": true,
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}

**Comment by dmcrock** [comment]
10-4, let me try

**Comment by dmcrock** [comment]
@patmill Hi Pat, just wanted to tell you i rebuilt the project again with drop 3, everything seems to be working. Thanks for your time and help

**Comment by manishgarg1** [comment]
Should we close this issue? Is it resolved?

**Comment by patmill** [comment]
Closing
