### ISSUE TITLE
Scroll to Top of Web Part

### ISSUE THREAD

**Issue by boydcster** [SharePoint/sp-dev-docs#1850]
I have a web part with a UI larger than the screen size of a large viewport (1400 X 690px). When users scroll down to see the content toward the bottom of the screen and click a button to see a detail screen, they only see the bottom of the screen and have to scroll up to see the top of the content. I would like to scroll to the top of the web part whenever users click the button to see the details screen. However, all of the usual methods such as scrollIntoView or scrollTo don't seem to work. Instead I've had to implement a crude and disruptive solution which is to reload the page. This would seem to be a fairly simple issue, but I've spent many hours trying to implement it without success, 
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Here is a typical example of the code I've tried to use for the above purpose:

 var details = document.getElementById("#details");
 details.scrollIntoView();

details is a div tag at the top of the web part.

This seems like a common use case, but it's possible that I'm overlooking some obvious reason why it can't work. Any guidance is appreciated.

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
I've had some success with using a ref instead.

In your component, declare a ref element:
private _topElement: HTMLElement;

When rendering the element, create a ref to it:
<div ref={(topElement) => this._topElement = topElement!} />

And when ready to scroll, use:
this._topElement.scrollIntoView()

I hope this helps?

**Comment by boydcster** [comment]
Thanks much for your help, Hugo. I defined the _topElement reference as a private member of the class. I place the <div> in the HTML rendered for the web part at the top:

<div ref={(topElement) => this._topElement = topElement!} />

Actually, creating a reference in this way is new to me and I didn't find much about it by googling.

and execute this code in the button event handler: 
this._topElement.scrollIntoView()

What happened was that the _topElement threw an "element not found" exception.

**Comment by hugoabernier** [comment]
Here's my version of HelloWorld with scrollIntoView. Give it a try and see (rename to TSX)
[HelloWorld.txt](https://github.com/SharePoint/sp-dev-docs/files/2011441/HelloWorld.txt)

I hope it does the trick for you!
