### ISSUE TITLE
Edit panel multi line column in modern doc lib gives 404

### ISSUE THREAD

**Issue by thomyg** [SharePoint/sp-dev-docs#1854]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Click on document
Click on property pane on the left
Click on edit at the multi-line text field
Being able to edit the column

#### Observed Behavior

Click on document
Click on property pane on the left
Click on edit at the multi-line text field
404 in the panel 
Happend on two tenants today, screenshot is from mine, ready for you to investigate: https://thomy.sharepoint.com/sites/ModernTeam/Freigegebene%20Dokumente/Forms/AllItems.aspx 

![image](https://user-images.githubusercontent.com/10920072/40059936-a738a178-5855-11e8-95f9-cce1dfa5a850.png)

#### Steps to Reproduce

Create modern team site
Click on Documents
Add a multi line text column
try editing this via the modern property pane

 Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi Thomas, any change to include a network trace and the call which is getting the 404, so that we can route this to right team internally. Network trace should have the SP.Request.ID which we can use for tracing internally. Thx.

**Comment by thomyg** [comment]
Sure thing. Fiddler trace attached. If you need something else just let me know. 
[404_MultiLineColumnEditAtDocLib.zip](https://github.com/SharePoint/sp-dev-docs/files/2006118/404_MultiLineColumnEditAtDocLib.zip)

**Comment by chadn1003** [comment]
Hi Thomas, 
  I believe that your issue requires additional review and this forum isn't a great mechanism for troubleshooting this type of issue.  I would encourage you to open a ticket via the tenant admin portal to have a support agent assist you with your issue.
- Chad
