### ISSUE TITLE
Enterprise Keywords support in modern pages?

### ISSUE THREAD

**Issue by otravers** [SharePoint/sp-dev-docs#1856]
Is there a way to display enterprise keywords on a modern SP page, like you see tags/categories posted at the bottom of many blogs? I know how to assign the enterprise keywords to pages but not how to display them on pages (not just on lists).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926ab97b-0406-116a-9b44-59df02beee7d
* Version Independent ID: 3094c3cf-cd16-518e-48fc-095fb14036dd
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-pages.md)
* Service: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by luismanez** [comment]
There´s no OOB support to do that as of today. However, in April they announced that capacity into the roadmap, as you can see in the update of this article from @estruyf 
https://www.eliostruyf.com/custom-metadata-for-sharepoint-modern-pages/
