### ISSUE TITLE
Cross Site search from Hub site not working

### ISSUE THREAD

**Issue by briester1** [SharePoint/sp-dev-docs#1857]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When searching from the hubsite documents located on associated sites should also show up in search. 

#### Observed Behavior

Cross site search only produces results on the results page for documents located on the immediate site, not associated sites. 

#### Steps to Reproduce

1. Create a site
2. Register as a hub site
3. Associate a site to it
4. Search from hub site for a document on the associated site
5. See no results from associated sites, only those on the hub site where the search originated.

**Comment by briester1** [comment]
The documents are showing up in Search now, but not in the "all category" of the results page.

**Comment by briester1** [comment]
We didn't do anything to get it working. The functionality was off again today. Not sure what happened.

**Comment by PeterHamiltonTO** [comment]
This hasn't been working for me for about one month.  Then, this morning, it just started working (I didn't change anything either).  This is very unpredictable, but it is now working as it should.

**Comment by VesaJuvonen** [comment]
As this seems to be an issue for specific tenant and it's not specific on actual SharePoint developer platform (APIs or so), would suggest opening actual SPO support case from the tenant administration tool, so that this issue is processed using proper channels.
