### ISSUE TITLE
--no-install doesn't seem to work

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#186]
#### Category

[ ] Question
[ ] Typo
[ x] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea
#### Expected or Desired Behavior

With the latest drop 3, you should be able to skip the installation at the end with the `--no-install` flag. 
#### Observed Behavior

Just tried out running `yo @microsoft/sharepoint --no-install`, but it keeps installing the modules like it did without the flag.

![snip_20160914212402](https://cloud.githubusercontent.com/assets/2900833/18526726/fc12eb54-7ac1-11e6-8cb8-b163c7b6c836.png)

Yeoman generator version is `"version": "0.1.2"`. So generator is up to date.

**Comment by patmill** [comment]
@nickpape-msft - any idea on what is going on here?  (I've removed the entry from the drop 3 notes for now)

**Comment by gavinbarron** [comment]
Looks like this is still an issue with generator version 0.2.0

**Comment by chakkaradeep** [comment]
Is this same as #235 ?

**Comment by estruyf** [comment]
@chakkaradeep yes, indeed.

**Comment by patmill** [comment]
Works now
