### ISSUE TITLE
SP16 On-prem// Spfx - Pkg Add Webpart Step Issue

### ISSUE THREAD

**Issue by mhijazi** [SharePoint/sp-dev-docs#1861]
Hi All,

Whenever I try to add the app "Hello Webpart" it says "Sorry, something went wrong".
Although it says deployed with no errors.

- Create a new webpart using "yo ".
- Gulp serve--> working fine.
- after that try to deploy on your dev site like below:
- Change CDN path with you :
- "cdnBasePath": "your sharepointsite/SiteAssets/test/"
- gulp bundle --ship
- gulp package-solution --ship
- Upload contents of "temp\deploy" to CDN site path
- deploy on AppCatalog
- **Add app in your site** **I cannot add it says Something went wrong but all above went fine**

Any Ideas???

**Comment by hugoabernier** [comment]
I had a similar issue (which is still not resolved) deploying to on-prem. Try the following:

1. Launch the page where you want to add the web part
2. Launch the Developer tools (Chrome, IE, Edge, whatever you prefer)
3. Select the network tab (or whatever it is called on your browser of choice).
4. Add the web part (or refresh the page)
5. When you get "Something went wrong", look on the network tab to see what file it tries to call when loading your JS bundle.

I found that it looks for a hashed file (i.e.: your bundle name with a bunch of extra random-looking characters .js) but if you look at the file you deployed in the CDN, your bundle file doesn't have the hash characters (i.e.: yourbundlename.js).

If that's the case, try renaming the file in your CDN to match what SharePoint is looking for and reload your web part. It should work.

It isn't a fix, but it is a good workaround until (I hope) someone can help us resolve the real issue (which must happen somewhere during bundling).

If you're experiencing the same problem, you may want to link to issue #1815.

I hope it helps?

**Comment by mhijazi** [comment]
It not yet appearing under Page Edit -> Insert Webpart ... Currently it is only appearing under Site Contents when I click add it says "Somwething went wrong"

**Comment by youranupama** [comment]
Facing same issue, though the webaprt is available to add to the page, the app itself is neither added properly or can be removed. It keeps on saying "something went wrong" or "could not remove the app". Its kind of stuck. I tried removing the App instance using powershell but it is not going.
