### ISSUE TITLE
Deploy the HelloWorld package to app catalog

### ISSUE THREAD

**Issue by rahul-mi** [SharePoint/sp-dev-docs#1867]
For this to succeed, I needed to keep the gulp serve running. 

And it was not mentioned in the docs. And I continued to get the App deployment failure error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Deployment of the solution to app catalog or adding it there, does not require the gulp serve to be running. This is also not required when you install the solution to a site, rather only when you want to place the web part on a page as the URLs are still pointing to the localhost. Thanks for the input, we'll adjust the text accordingly to avoid confusion.
