### ISSUE TITLE
sp-client-preview doesn't include the changes mentioned in Drop 3

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#187]
#### Category
[ ] Question
[ ] Typo
[ x] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

#### Expected or Desired Behavior
Just updated the generator and created a new project. I noticed that the API changes which are mentioned in the [release notes of drop 3](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-3) are not available in the corresponding version (`"@microsoft/sp-client-preview": "~0.3.0"`).

#### Observed Behavior
To be sure I installed the `@microsoft/sp-client-preview` module to a separate folder and this gave the same result. 

The version in the package states it is version 0.3.0: 

![snip_20160914213644](https://cloud.githubusercontent.com/assets/2900833/18527036/5bd1c2ee-7ac3-11e6-8445-3a961b3a779c.png)
![snip_20160914213632](https://cloud.githubusercontent.com/assets/2900833/18527045/641db750-7ac3-11e6-8a1f-1e7f9d404123.png)

But if I check the BaseClientSideWebPart.d.ts or IPropertyPane.d.ts I don't see any of these changes.

**Comment by patmill** [comment]
Hmn, let me see what went on there...

**Comment by patmill** [comment]
OK, so our bad when we wrote up the release notes.  I was looking at the daily build ts files, and the build we released on that day was from a few days previous with cherry picked changes.  Most of those changes reported will be in the next drop.  I'm just tracking down the official changes, and I'll update the drop notes.

**Comment by estruyf** [comment]
@patmill good to know what's coming 👍

**Comment by pgonzal** [comment]
Closing this bug since the issue was resolved.
