### ISSUE TITLE
Event for this.context.application.navigatedEvent fires twice, event args are empty

### ISSUE THREAD

**Issue by westleyMS** [SharePoint/sp-dev-docs#1871]
I have code something like in the repro.
This code is registered as a application extension to run on all pages. The dialog comes up twice each time, once on navigation away, and the other on navigation to I believe, but the event args don't have anything in them, so I can't distinguish in the code if I should fire the dialog. I only want it to fire when the page is navigated to, not away from.

#### Category
- [X] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I would expect that the event args would have an identifier if the event was away from or to the page.

#### Observed Behavior

event fires twice and no event args

#### Steps to Reproduce
1. Create a application extension for running script on all pages-
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md

2. In the extension, place code something like this-

/** A Custom Action which can be run during execution of a Client Side Application */
export default class HelloWorldApplicationCustomizer
  extends BaseApplicationCustomizer<IHelloWorldApplicationCustomizerProperties> {

  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    let message: string = this.properties.testMessage;
    if (!message) {
      message = "(No properties were provided.)";
    }

    this.context.application.navigatedEvent.add(this, this.showAlert);
    return Promise.resolve();
  }

  public showAlert(args1:EventArgs):void {
    let message: string = this.properties.testMessage;
    if (!message) {
      message = "(No properties were provided.)";
    }
        // args1 doesn't have any data to distinguish
        Dialog.alert("test");
  }
}

Try the extension and note after a few navigations between modern pages (as=json) it starts showing the dialog twice.

I did notice if I switched to a simple js alert("test") statement, you can tell it fires once on the page leaving, and the second time on page entering. The Dialog doesn't, but I think that is due to some async code in that class.

**Comment by sortegamartin** [comment]
I have the same problem!

**Comment by BraunJonathan** [comment]
I have the problem too !!
I noticed that if i arrive on a site through the home page, i get events when leaving the page and when enering the new one and if i rrive on the site through another page, i only get an event when leaving the page...
@VesaJuvonen : could you provide a reliable documentation explaining how navigatedEvent are supposed to work ? When are they triggered ? What are the eventArgs supposed to be ?

We would like to change the content of the top placeholder based on the page we're on and change it when the user scrolls into the page but right know, we can't manage to do that because depending on the situation, we do not have the same navigatedEvents fired...

**Comment by WickedTheToy** [comment]
Hello,

I have the same problem, did you find a solution ?

**Comment by westleyMS** [comment]
This is under investigation currently by the product team and they have some idea of what may be causing the issue. I should hear back soon.

**Comment by jonthenerd** [comment]
We've got the same issue and have a workaround in place to limit what we're doing on navigated to once per navigation. If there's interest I'll post our workaround.

**Comment by orty** [comment]
Hi @jonthenerd,
I am really interested in your workaround to narrow navigatedEvents to only one occurrence. can you share it with us please ?

Many thanks

**Comment by ThomasGranheim** [comment]
Hi,

The issue is still present in SPFx 1.6. Have you guys found a solution/workaround?

**Comment by wobba** [comment]
@patmill any ideas?

**Comment by jonthenerd** [comment]
I’ll try and post my workaround by end of week. It’s working for 1.4.1 but I don’t see why it wouldn’t work for higher.


________________________________

**Comment by jonthenerd** [comment]
Here's the workaround code. This is working in 1.4.1. Using this code, if you have something you need to run on initialPageLoad you'll need to plumb it yourself. The second firing on navigating away is mitigated by just keeping track of the last known page location. 

```typescript
export default class YourCustomizer {
  private currentPage = "";
  private isInitialLoad = true;

  private getFreshCurrentPage(): string {
    return window.location.pathname + window.location.search;
  }
  private updateCurrentPage(): void {
    this.currentPage = this.getFreshCurrentPage();
  }

  private navigatedEvent(): void {
    const navigatedPage = this.getFreshCurrentPage();
    if (!this.isInitialLoad && (navigatedPage !== this.currentPage)) {
      this.realNavigatedEvent();
      this.updateCurrentPage();
    }
    this.isInitialLoad = false;
  }

  private realNavigatedEvent(): void {
    // TODO: Your work that depends upon the page changing
  }
}
```

**Comment by NickSevens** [comment]
I noticed indeed that the `navigatedEvent` is being called twice when coming from an "internal" url, so basically when the _partial loading_ kicks in.

I think a better solution would be if there was a navigat**ing**Event and a navigat**ed**Event, being fired when leaving and entering a page respectively.

**Comment by dsimoes** [comment]
Same problem. SPEventArgs contains no info about the type of event.

**Comment by patrickabel** [comment]
I'm seeing this problem as well, any update from the product team on this issue? @VesaJuvonen?

**Comment by patmill** [comment]
Yes - it's a bug and a fix is being made.

**Comment by joelfmrodrigues** [comment]
@patmill can we expect this to be fixed "behind the scenes", or will it be part of a new SPFx release?

**Comment by westleyMS** [comment]
The fix is rolling out, and should be turned on soon.

**Comment by dg2000r** [comment]
Is there anywhere to track this fix, and see when it's likely to arrive? We're getting desperate for this one! Thanks

**Comment by mirkori** [comment]
This is active now on my developer tenant

**Comment by westleyMS** [comment]
The fix hit my tenant today, it appears to be working as expected now.

**Comment by dg2000r** [comment]
This in on my tenant now, which has fixed the firing twice issue. Now does anyone know how to delay the firing until after the navigated page has loaded? At the moment it seems to happen first, so document.location.pathname returns the previous page url where the link was clicked, rather than the one that has just been navigated to.

**Comment by joelfmrodrigues** [comment]
Seems fixed on my Dev tenant now

**Comment by mirkori** [comment]
@dg2000r yes I noticed that aswell and I find this is very unfortunate.
Don't know if this is the right thing to do, but as a workaround I am now passing the serverRequestPath from the sp context as prop to my react components.

**Comment by dg2000r** [comment]
@mirkori Thanks, serverRequestPath at least solves part of issue so I can see which page has been navigated to. The rest of my problem is that I then need to access the DOM of that page but I don't have a workaround for that yet.

**Comment by rganser** [comment]
Does anyone have any recommendations or updates on this? We're experiencing the same issue.

**Comment by westleyMS** [comment]
These are not the original issue which was fixed and confirmed (double event firing). Please file a new issue if you have other issues you are running into.
