### ISSUE TITLE
Where to save data for a web part

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1872]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi, I would like to know where I can save data for SPFx WebPart but don't want to use lists or any other 3-rd party services. For example there is out of the box web part Quick links which stores somewhere data about links

**Comment by waldekmastykarz** [comment]
If the data is to be used by a single instance of the web part only, you could store it in web part's properties. If you need to share the data across multiple instances of the web part, you won't have much choice than to use a list or a custom API.
