### ISSUE TITLE
Login checking with ADSL JS causes multiple page redirects....

### ISSUE THREAD

**Issue by 2P2-Anthony** [SharePoint/sp-dev-docs#1875]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When a user is already logged in, the ADSL JS getCachedUser object should be populated, or if needed to be built should be created after one visit to the SPO Login Page. However, we are seeing 3 different round trips to the SPO Login Page in rapid succession which finally builds the getCachedUser object.

#### Observed Behavior

If a user is already logged in, the getCachedUser is empty, and it takes 3 round trips through the SPO Login Page to build the correct object. These redirects are not under user control, and are visible via the browser page flashing multiple times as the redirects are processed.

#### Steps to Reproduce

Build a minimum SPFx web part, we folllowing these instructions 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-angular
https://blog.mastykarz.nl/building-office-365-web-applications-react/

 but are hooking into Azure AD, not MS Graph.

More info here:

https://stackoverflow.com/questions/50146519/adal-spfx-getcacheduser-is-always-null

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
This is definitely a known behavior.. and one that I discussed in a series of blog posts.  I think it becomes moot, v1.4.1 and later of the SharePoint framework has the MSGraphClient which negates the need to bundle the ADAL.js library into your solution.  In essence the SPFx now handles the graph authentication for you.  See documentation here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph
