### ISSUE TITLE
You cant use office-ui-fabric-react with SPFx due to different TS versions required

### ISSUE THREAD

**Issue by HeToC** [SharePoint/sp-dev-docs#1877]
project does not ever compiles

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 0dedd717-ec39-dcd9-3994-7bab3839df28
* Version Independent ID: 0eddf92b-1b20-650e-2432-83c530279815
* Content: [Использование Office UI Fabric Core и Fabric React в SharePoint Framework](https://docs.microsoft.com/ru-ru/sharepoint/dev/spfx/office-ui-fabric-integration)
* Content Source: [docs/spfx/office-ui-fabric-integration.md](https://github.com/SharePoint/sp-dev-docs.ru-ru/blob/live/docs/spfx/office-ui-fabric-integration.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by HeToC** [comment]
oh that was created from ms web site duplicated

**Comment by andrewconnell** [comment]
This is an old issue and there were conflicts between the Office UI Fabric React v6 & SPFx for a while due to different TypeScript versions that were used, but this has been addressed in the latest version of SPFx (1.8.x) as you can now change the version of TypeScript.
