### ISSUE TITLE
Unable to use ActivityItem from ui fabric react

### ISSUE THREAD

**Issue by HeToC** [SharePoint/sp-dev-docs#1878]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Importing and using components from the latest ui fabric work correctly

#### Observed Behavior

Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(10,30): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,56): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,58): error TS1005: '>' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,60): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,70): error TS1109: Expression expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(22,62): error TS1109: Expression expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(22,63): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(28,48): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(29,19): error TS1005: ':' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(30,20): error TS1005: ':' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(31,25): error TS1005: ':' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(32,22): error TS1005: ':' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(33,23): error TS1005: ':' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(43,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(47,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(51,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(55,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(55,30): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(59,50): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(66,36): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(73,42): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(84,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(91,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(97,4): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(105,4): error TS1005: ',' expected.
Error - typescript - src\webparts\projectJournal\components\ProjectJournal.tsx(60,8): error TS2605: JSX element type 'ActivityItem' is not a constructor function for JSX elements.
Error - typescript - src\webparts\projectJournal\components\ProjectJournal.tsx(60,8): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
Error - 'typescript' sub task errored after 2.35 s
 "TypeScript error(s) occurred."

#### Steps to Reproduce

Create spfx OnPrem HelloWorld app with yo
reference "office-ui-fabric-react":"~5.106.1"
add ActivityItem component to your webpart

#### Submission Guidelines

**Comment by dzearing** [comment]
This is due to spfx not being compatible with TypeScript 2.6.

**Comment by dzearing** [comment]
https://unpkg.com/@uifabric/utilities@5.34.1/lib/BaseComponent.d.ts

The specific requirement is that in 2.6, generics support default values:

```tsx
export declare class BaseComponent<P extends IBaseProps = {}, S = {}> extends React.Component<P, S> {
```
