### ISSUE TITLE
Site Contents shows all SPFx apps with the same name and install date

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#1881]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

I have been following the tutorials for the SharePoint framework webparts and extensions.

I am finding that every time I follow a tutorial that involves packaging a solution and deploying it to a site, my site's Site Contents show all of the SPFx solutions I have deployed so far with the name and deployment time of the most recently deployed solution:

![image](https://user-images.githubusercontent.com/6964029/40300027-0f71c9be-5d23-11e8-8af5-eff2ef18d914.png)

It seems to display them in alphabetical order of their actual names, but the names and dates displayed are all the same.

Additionally, when installing a new solution or uninstalling one, they _all_ show as installing or uninstalling.

If I open the Details for any of them, I am shown the Details page for the app whose name is displayed (i.e., they all open to the same Details page).

Is this a behavior that has been seen before? Is it some kind of ID conflict where SharePoint is somehow getting all of the SPFx apps jumbled up with each other? I have tried this on two different sites in my tenant and am experiencing the same issue in both of them.

This appears to only happen in the Modern Site Contents view. In the Classic Site Contents, the apps display as expected.

![image](https://user-images.githubusercontent.com/6964029/40300227-99cd7310-5d23-11e8-9922-98f460958d3b.png)

#### Steps to Reproduce

1. Follow two or more SPFx tutorials that involve creating a new webpart or extension and deploying it to a site.
2. Look at the Site Contents page in Modern mode.
3. Observe that all of the deployed solutions show with the same name.

**Comment by andrew-blubase** [comment]
I logged this very same issue with Microsoft today. I experience it on multiple tenants in any site collection using modern ui.

**Comment by PooLP** [comment]
@VesaJuvonen : i'm not sure, but i think this bug is resolved, on my tenant, i have different name for each SPFx component).

**Comment by ayushjs** [comment]
Hi, I am also facing this issue in my SP 2019 on-premise environment. Is there any fix available?

**Comment by h3nn3** [comment]
Is there any update / fix for this bug?
