### ISSUE TITLE
OOB News Web Part missing Titles for certain users

### ISSUE THREAD

**Issue by john88benson** [SharePoint/sp-dev-docs#1882]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

OOB News Web Part to display event titles in all cases.

#### Observed Behavior

The client has reported that for two users the OOB News Web Part does not display news titles.  When using Dev Tools the title code does not appear to be rendering in the DOM.  

Without Titles:
![announcements screen shot - adem](https://user-images.githubusercontent.com/28630591/40314833-b17b0ba8-5ce7-11e8-9f2e-7fab2af3628f.png)

With Titles:
![announcements screen shot - titles png](https://user-images.githubusercontent.com/28630591/40314853-c178dfe4-5ce7-11e8-8a83-79f8b0a9978f.jpg)

#### Steps to Reproduce

Since this is occurring with specific users it is difficult to give steps to reproduce.  It was replicated in both Chrome and IE.  Elevating the users' permissions did not have an effect.

**Comment by MayraJaimes** [comment]
I am experiencing the same problem. I am using the news web part in the main page of our new intranet page but I am experiencing this problem were the titles are missing. In the carousel they sometimes show just in the first slide then they go away. Can this please be looked at as this is something that I need to display in the main page?
