### ISSUE TITLE
upgrade is success but packages still old

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#1883]
I followed this https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages to upgrade my packages, command is successfully ran. But when i create yo@microsoft/sharepoint webpart project, the package in package.json still outdate, such as:

    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",

They should be 1.4.1, please help and thanks
Peter

**Comment by StfBauer** [comment]
What does the following command output?

```
npm -g list @microsoft/generator-sharepoint --depth=0
```

It basically queries your global installed packages and shows the currently used version number.

**Comment by peterremote1980** [comment]
/usr/local/lib
└── @microsoft/generator-sharepoint@1.4.1

When i create the project by "yo @microsoft/sharepoint", in package.json i got:

{
  "name": "subscription-webpart",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "@types/react": "0.14.46",
    "@types/react-dom": "0.14.18",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-update": "0.14.14",
    "@types/react-addons-test-utils": "0.14.15",
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@types/webpack-env": ">=1.12.1 <1.14.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  }
}

**Comment by StfBauer** [comment]
Can you also please try to execute `yo doctor` and share the output?

**Comment by peterremote1980** [comment]
Here you go, thanks

`/Users/peter/workspace/quantr-express>yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!`

**Comment by peterremote1980** [comment]
i understand now, it probably a bug, if i choose "sharepoint online" instead of "on-premies', it give me 1.5.0, please followup

**Comment by waldekmastykarz** [comment]
it's by design: SharePoint Online uses the latest set of SharePoint Framework packages (1.5.1 at this moment), while SharePoint Server (on-prem) uses v1.1.0, so if you choose to create a project that will work with SharePoint on-prem, you will get a project based on SPFx v1.1.0.
