### ISSUE TITLE
How can I apply theme using Rest API SharePoint online

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1885]
Do we have any API available?

**Comment by harshdamaniahd** [comment]
@waldekmastykarz  thanks..
so using this code i can change theme of a modern site ?

**Comment by waldekmastykarz** [comment]
Correct

**Comment by harshdamaniahd** [comment]
When will this be released officially with documentation,facing issues in implementation.

My problem is that  based on user profile properties i have to change the theme. ?

Currently what I am doing 
1. Using Application Customizer.
2.In the Init Property I have fetching user profile info and based on that overriding the css which is not a correct approach instead have to change them

**Comment by jcosta33** [comment]
Hi everyone!

So this is available: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api#applytheme

But I don't seem to be able to use it. I was able to get all the other endpoints working properly using the spHttpClient object in an appcustomizer. The documentation is a little copypasty, one of the endpoints (GetTenantThemingOptions) which only works as a get request is documented to require a post request. When I make the request to the ApplyTheme endpoint I get a success message but no actual effect. I can't get my head around how I could implement what @waldekmastykarz suggested there. Any ideas?

**Comment by PopWarner** [comment]
Hi @jcosta33! :)

Great question. I'm not sure if this will completely help you, but there is a sample web part that allows you to use all the endpoints, including the ApplyTheme. Perhaps taking a look at it and seeing how it applies the theme to a site directly will help? :)

https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/js-theme-manager

**Comment by jcosta33** [comment]
Oh! Thank you @PopWarner, I had almost verbatim what is in that WP except I forgot to pass in the url of my site collection... One of those mistakes that makes one feel silly!

**Comment by harshdamaniahd** [comment]
closing
