### ISSUE TITLE
can't install spfx from VS2017

### ISSUE THREAD

**Issue by dariuszbz** [SharePoint/sp-dev-docs#1886]
22/05/2018 13:44:53 - Skipping 'C:\Users\abcdfgfh\AppData\Local\Microsoft SDKs' as it doesn't exist
22/05/2018 13:44:53 - The extension with ID 'SharePoint.Framework.VSIX.94e9564e-67da-422c-b02b-501e2f45147a' is not installed to Microsoft Visual Studio Enterprise 2017.
22/05/2018 13:44:59 - Extension cannot be installed to the following products due to missing prerequisites:
22/05/2018 13:44:59 - 	Microsoft Visual Studio Enterprise 2017
22/05/2018 13:44:59 - 		-------------------------------------------------------
22/05/2018 13:44:59 - 		Identifier   : Microsoft.VisualStudio.Shell.14
22/05/2018 13:44:59 - 		Name         : Visual Studio Shell
22/05/2018 13:44:59 - 		Version      : [14.0]
22/05/2018 13:44:59 - 		Error        : The prerequisite specified does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
On which step this exception was provided? - What command was executed? - SPFx does not require VS2017 to be installed on the development machine.

**Comment by dariuszbz** [comment]
Hello,




6/5/2018 11:29:45 AM - Capping recursion at 5 directories in each extension
root due to 'default limit'.
6/5/2018 11:29:45 AM - Skipping 'C:\Program Files (x86)\Common
Files\Microsoft\ExtensionManager\Extensions' as it doesn't exist
6/5/2018 11:29:45 AM - Skipping
'C:\Users\supervisor\AppData\Local\Microsoft SDKs' as it doesn't exist
6/5/2018 11:29:45 AM - The extension with ID
'SharePoint.Framework.VSIX.94e9564e-67da-422c-b02b-501e2f45147a' is not
installed to Microsoft Visual Studio Enterprise 2017.
6/5/2018 11:29:50 AM - Extension cannot be installed to the following
products due to missing prerequisites:
6/5/2018 11:29:50 AM - Microsoft Visual Studio Enterprise 2017
6/5/2018 11:29:50 AM -
-------------------------------------------------------
6/5/2018 11:29:50 AM - Identifier   : Microsoft.VisualStudio.Shell.14
6/5/2018 11:29:50 AM - Name         : Visual Studio Shell
6/5/2018 11:29:50 AM - Version      : [14.0]
6/5/2018 11:29:50 AM - Error        : The prerequisite specified does not
exist
6/5/2018 11:29:50 AM -
6/5/2018 11:29:50 AM - System.InvalidOperationException: No modifications
could be applied.
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass11_1.<OnLoaded>b__2()

**Comment by VesaJuvonen** [comment]
I do not understand where this message is from, so would need input on what that string is? What was installed, what is the command which was executed, where is that string from? Thx.

**Comment by wictorwilen** [comment]
@dariuszbz  - are you using the PnP VS 2017 extension? https://marketplace.visualstudio.com/items?itemName=SharePointPnP.SPFxProjectTemplate

**Comment by dariuszbz** [comment]
Hello,

Wictor, i downloaded using the url from you.

Now it looks like:



and this is my VS2017 (brand new after last update)




I don't want to mess around. I'm using SPFx on antoher VM with VSCode, but
it would be greate to integrate with VS - and i was expecting the extnetion
to be working fine .... i'm suprised it won't :(.

**Comment by VesaJuvonen** [comment]
Hi @dariuszbz - unfortunately you got me confused on having this comment in the official SharePoint developer documentation addressing "Setting up your development environment" as we do not mention this open-source Visual Studio extension in that page at all. 

We do recommend using VS Code as they de-facto industry standard model for building SPFx extensions and web parts - this is the officially reported and supported story for SharePoint Framework development like noted in this page.

VS2017/VS2015 extension is an open-source add-on for the VS2017 and it has it's own support channels in GitHub at https://github.com/SharePoint/sp-dev-fx-vs-extension. This has been tested with different environments and I have also used that with my own VS2017 without any issues. 

To be able to understand what goes wrong within your case, we would need to understand more on your environment and what exactly has been installed, so that we can try to mimic the setup. It might be that you are running into the same issue as reported in the following issue at the VS extension repository - https://github.com/SharePoint/sp-dev-fx-vs-extension/issues/34, which potentially will get you unblocked.

**Comment by dariuszbz** [comment]
Hi Vesa,

i just installed the latest VS2017, and i have try to install the
extension. The installation faild. I reported. If you have resorces to
resolve this issue we can continue. I don't need VS2017 to work with SPFx.
As i said: it would be greate to integrate SPFx with VS2017. For some
reason it won't work. At least to me.

**Comment by dariuszbz** [comment]
Hello,

VM:  <meta http-equiv='refresh' content='0;
URL=/Error/UE_JavaScriptDisabled'/> Dashboard - Microsoft Azure Standard
DS3 v2 Promo (4 vcpus, 14 GB memory)

OS: Microsoft Windows [Version 10.0.16299.431]

VS2017:
Microsoft Visual Studio Enterprise 2017
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40522.0
ASP.NET and Web Tools 2017

ASP.NET Core Blazor Language Services   0.3.0-rtm-10274

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.8.3-beta6-62923-07. Commit Hash:
7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings,
a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft
Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.1
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and
continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP
compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target
environment. F5 your application directly into a container with debugging,
or CTRL + F5 to edit & refresh your app without having to rebuild the
container.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet,
visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.27612.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash:
7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and
settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash:
2527e6829ecdc8281ee60d83be8cfd0fa720a648.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components
for Workflow Manager.



What other details do you need ?

Cheers,

**Comment by VesaJuvonen** [comment]
thx @dariuszbz, this should be now sufficient to be able to understand your environment details and to test the issue in a similar environment.

**Comment by sagar4u** [comment]
Unrecognized token in source text. for command npm install -g @microsoft/generator-sharepoint

Resolution:-
use double quotes:-
npm install -g "@microsoft/generator-sharepoint"

**Comment by andrewconnell** [comment]
As this isn't related to official SharePoint documentation, I'm going to recommend you post this to the issue list in the repo for the extension you are trying to use: https://github.com/SharePoint/sp-dev-fx-vs-extension
