### ISSUE TITLE
Hello World, Deploy to CDN

### ISSUE THREAD

**Issue by Panoone** [SharePoint/sp-dev-docs#189]
[x] Question
[ ] Typo
[ ] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

In the Tutorial Overview it states that "...you can manually upload the files to your favourite CDN provider or **SharePoint** as well."

When deploying minified assets to SharePoint, is it as simple as providing the site URL for the `cdnBasePath` property, running `gulp --ship` and manually uploading the files?

If so, what would be the best location for the files so that they're accessible across all tenant sites?

Thank you @nickpape-msft  for this wonderful introductory series!

**Comment by patmill** [comment]
Just to confirm @Panoone - are you looking for a suggestion on where you could host the files so they are accessible across all sites in a single tenant (you're an enterprise developer who has created a solution for your company) or across all tenants that are using your solution (you're an ISV who has developed a webpart that lots of companies are using)?

**Comment by Panoone** [comment]
Either or both. Just not sure what best practice is or how to achieve it.

**Comment by waldekmastykarz** [comment]
At this moment the only way to upload your assets to SharePoint is either by doing it manually or by using or a custom Gulp task such as https://github.com/wictorwilen/gulp-spsync.

**Comment by Panoone** [comment]
Hi @waldekmastykarz! And thanks very much for that.

But what it the **manual** approaching and the steps for including and referencing these files in my webpart project? I'm struggling with the precise code requirements.

**Comment by waldekmastykarz** [comment]
Before you build your project with the `--ship` flag, indicating that it's a release build, you have to specify the `cdnBasePath` as you mentioned in your initial question. When building the project, SharePoint Framework uses that URL and automatically includes it in the generated files. Once the build completes, the only thing that you have to do is to upload your files to the URL specified in the project. All references are already correct and no additional steps are required at that point. Are you seeing any errors?

**Comment by Panoone** [comment]
Hi @waldekmastykarz , no errors. I hadn't tried yet as I was seeking confirmation as `cdnBasePath` didn't seem like the right variable for bundling files into the same site.

Is there a site token and/or relative path I can provide or does it need to be explicit?

**Comment by waldekmastykarz** [comment]
Web Parts are generally speaking (although not a requirement) hosted outside of SharePoint. This is why the URL must be absolute, so that SharePoint Framework can properly support external locations. The value of the `cdnBasePath` property is included in the generated Web Part manifest so it must be explicitly defined before the build.

**Comment by pgonzal** [comment]
It sounds like @Panoone's original question was answered, so I am closing this issue.  Feel free to reopen the bug if that is not the case.
