### ISSUE TITLE
[Question] Is there a way custom field rendering in New/Edit form by using spfx (extension) ?

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-docs#1891]
As far as I know that spfx does not support custom field rendering in the forms (new/edit and quick edit mode), just custom rendering in the list view.
Do you guys know if there is a way to work around? Or this will be supported later by spfx?

**Comment by frankchen76** [comment]
Last time I heard from MS was that Power App is a recommended way to customize the new/edit form. I am not sure if that's changed.
