### ISSUE TITLE
Fetching a list item by id returns XML instead of JSON

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#1892]
#### Category
- [x] Bug

#### Expected or Desired Behavior

When issuing a REST request to fetch a list item by id, accept header of JSON, I expect JSON to be returned and not XML. Bug experienced in two different SPO tenants.

#### Observed Behavior

Issuing a request like below will return XML and not JSON. If you add `?$select=Title` then JSON is returned as expected. Also if you filter by id it works `/_api/web/lists/getbytitle('MyList')/items?$filter=ID eq 1`.

```javascript
        var siteurl = _spPageContextInfo.webAbsoluteUrl;
        jQuery.ajax({
                   url: siteurl + "/_api/web/lists/getbytitle('MyList')/items(1)",
                   method: "GET",
                   headers: { "Accept": "application/json; odata=nometadata" },
                   success: function (data) {
                        console.log(data);       
                  },
                  error: function (data) {
                      alert("Error: "+ data);
                 }
          });
```

#### Steps to Reproduce

* Create a list with one item
* Execute a REST GET request to fetch the item and inspect the returned data.

**Comment by AhmedKandeel** [comment]
I have the same issue and it fixed after clear the cache 
https://github.com/SharePoint/sp-dev-docs/issues/764

**Comment by wobba** [comment]
Not relevant for me any more.
