### ISSUE TITLE
Repetetive "Sorry, something went wrong with adding the app" when trying to deploy assets via SPFx-solution(s)

### ISSUE THREAD

**Issue by balle3201** [SharePoint/sp-dev-docs#1893]
I'm facing repetitive issues when trying to deploy SharePoint-assets via PSPFx-solution(s). It seems that provisioning Fields and Content Types works fairly stable, but as soon as a List Instance is added, and especially when specifying a "CustomSchema", the App-Installation ends up with an indescribable error-message.: "Sorry, something went wrong with adding the app".  I have tried both in SPFx Application Customizer(s) and Client Side Web Parts but to no avail.

Have someone else been experiencing the same issues, and could perhaps share some experiences regarding this matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by UX-Gav** [comment]
I hace the exact same issue! This doesnt work... double checked all code. Also tried --ship. Nothing. Get the same error.

**Comment by UX-Gav** [comment]
Ok... so here's what I've found. I got it all working nicely with my own fields etc with and without --ship.

Once working though was a very painful excercise to try and reproduce the error again. I made minor adjustments until I found the culprit.

Elements.xml
This works: <Field ID="{060E50AC-E9C1-4D3C-B1F9-DE0BCAC300F6}"
This breaks it: <Field ID="{9ec8e698-591d-4103-9f3b-b8f877b33df8}"

i.e. For me specifically, lowercase field ID's in the Elements.xml file cause the error.

For reference I uploaded my files here: https://drive.google.com/open?id=1rACV9Ckyw4QnQZ9cIqXl2sO0goOOtjC-

Includes a publishing hyperlink field, choice field and number field.

**Comment by balle3201** [comment]
Thanx for the feedback @UX-Gav :-)

This was not the cause of the error in my case I'm afraid... 
For some reason an unintentionally character had sneaked its way in the schema.xml definition. It took a lot of effort to find the culprit, and I'm kind of surprised that VS Code did not identify this character as an invalid attribute in the XML, and give me a warning at least.

I'm closing this issue as it regrettable was my own fault :-(

Still facing the issues related to #1518 regarding getting the correct Content Type to appear in the New Menu for the list/library. The fields and Content Type are provisioned correctly to the site, but seem to be improperly connected to the list.

**Comment by merly-cortez** [comment]
Thank you @ux-gav, it has fixed the issue for me
