### ISSUE TITLE
Optional permissions strategy

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#1896]
Some products might support several data sources, for example: SharePoint List OR Microsoft Graph.
In these cases, we might ask for a Microsoft Graph permission and would require it only if the user chooses to configure the product to use that data source, but it is optional and the product could work without this permission.

So, I think this comment should be removed: "Rejecting a permission request issued by a solution deployed in the app catalog doesn't affect that solution, and it remains deployed in the app catalog. Because the requested permissions have been denied, the solution won't be working as expected and you should remove it from the app catalog immediately after rejecting the permission request."

See - the developer can check for that permission and fail gracefully, saying "Sorry, you cannot use this data source until your administrator grants this product permissions to access that resource" and can provide a help link on how to do that.

Hope that makes sense...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Closing as comment has been updated in doc, per @waldekmastykarz's comment.
