### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by smjltd** [SharePoint/sp-dev-docs#1897]
{"error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"en-US","value":"Value does not fall within the expected range."}}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10e358f-545c-9ff3-89ae-a77643da6dc2
* Version Independent ID: 6c76adbc-bd78-d96e-3cc3-4a67af1afb5a
* Content: [Upload a file by using the REST API and jQuery](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery#RunTheExamples)
* Content Source: [docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by SekThang** [comment]
error is here... 
var serverRelativeUrlToFolder = '/shared documents';
After I replaced like below format it started working. Try this
var serverRelativeUrlToFolder = '/sites/sitecollectionname/shared documents';

**Comment by santosh1110** [comment]
I try to run above code and my user have all the permission but still i get "Access denied. You do not have permission to perform this action or access this resource." error when uploading the file.

**Comment by santosh1110** [comment]
I try to run above code and my user have all the permission but still i get "Access denied. You do not have permission to perform this action or access this resource." error when uploading the file.

**Comment by mark-conner** [comment]
Two things with this article that need to be updated:
1) Do not try to set the "content-length": arrayBuffer.byteLength in the ajax headers
2) Do not use '\' at the beginning of your serverRelativeUrlToFolder string, just 'shared documents'

Fix these two things and it all works great!

**Comment by andrewconnell** [comment]
There's not enough information here to understand what's going on. 

If you are getting an error "access denied", then you don't have permission to the resource which can also mean what you are providing for authorization is not valid. 

Please provide more detail... to better assist.

> Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:
>
> 	- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
> 	- If SharePoint Online, is tenant configured for standard / targeted release
> 	- Browser(s) tested
> 	- If applicable, SPFx version
> 	- If applicable, version of Office UI Fabric React
>
> As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.

**Comment by DixitSoni0206** [comment]
I am facing this same issue when I am trying to Upload a document in a library. I have used POSTMAN, REST API, CSOM still no success. Still getting 403 Access denied. I tried to do a GET call on the site using POSTMAN and it's working fine. The credential I am using is SCA on Site, Access token I am generating using an app registered in SPO with FullControl.
I have used the same code on one different site and it's working fine on that Online site. i am lost now.

**Comment by DixitSoni0206** [comment]
> There's not enough information here to understand what's going on.
> 
> If you are getting an error "access denied", then you don't have permission to the resource which can also mean what you are providing for authorization is not valid.
> 
> Please provide more detail... to better assist.
> 
> > Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:
> > 
> > * SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
> > * If SharePoint Online, is tenant configured for standard / targeted release
> > * Browser(s) tested
> > * If applicable, SPFx version
> > * If applicable, version of Office UI Fabric React
> > 
> > As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.


Do you have any solution for this, I have seen one solution to Enable, Set-SPOTenant -LegacyAuthProtocolsEnabled $True using Powershell, But then again Connect SPO isn't working.

**Comment by DixitSoni0206** [comment]
I am now facing a new issue. I have created one different library on same SiteCollection and tried to add documents in that library and it's working fine.
But in my previous Library(DocumentUpload) I am facing this issue of Access Denied.
"code": "-2147024891, System.UnauthorizedAccessException",
        "message": {
            "lang": "en-US",
            "value": "Access denied. You do not have permission to perform this action or access this resource."
