### ISSUE TITLE
Deprecation process for Classic Experience

### ISSUE THREAD

**Issue by bilal-fazli-confiz** [SharePoint/sp-dev-docs#1898]
Hi MS, is there a road map or plan which can guide us as to when the classic experience will be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0589135-7828-0e78-2368-a2ce7d24837d
* Version Independent ID: fba97516-ac39-df40-b1cd-71b509eec7c0
* Content: [Customizing the ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations)
* Content Source: [docs/solution-guidance/modern-experience-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
There is currently no plans to deprecate or remove the support of classic experiences. We do not have any dates or schedules set for this. It will certainly happen at some point, but only when the majority of the usage is in the modern experiences and even then with proper heads up.
