### ISSUE TITLE
AddTenantTheme public method doest work

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1899]
I tried implementing this using CSOM , and it seems not to be working
Tenant tenant = new Tenant(clientContext);
 ClientResult<bool> themeCreate = tenant.AddTenantTheme("ThemeName", "JSONstring");                   
                    if (themeCreate.Value)
                    {
                     //This is always false
                    }
JSON String is taken from theme generator
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c301c98f-72b3-3bfb-ca5e-f030ae5378aa
* Version Independent ID: 757e2a57-a74c-4e75-435c-5b3c6ad39295
* Content: [SharePoint site theming - CSOM development](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-csom)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
> Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:
>
> 	- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
> 	- If SharePoint Online, is tenant configured for standard / targeted release
> 	- Browser(s) tested
> 	- SPFx version
> 	- If applicable, version of Office UI Fabric React
>
> As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.

**Comment by harshdamaniahd** [comment]
Dont have this issue
