### ISSUE TITLE
Extension is not working with CDN

### ISSUE THREAD

**Issue by LWesterfeld** [SharePoint/sp-dev-docs#1903]
I was trying to host this extension from a Office 365 CDN.
The extension itself was working properly with the local host running, but this this changes to the cdnBasePath made them not Rendering anymore. I'm getting this Errors in the console: (german) (
SCRIPT5022: No define call for as http://requirejs.org/docs/errors.html#nodefinerequire-951f856e.js (1,1661)
HTTP500: SERVERFEHLER: Es ist ein unerwarteter Zustand aufgetreten, sodass der Server die Anforderung nicht erfüllen kann.
GET - https://publiccdn.sharepointonline.com/xxxxxxxxxxx.sharepoint.com/sites/new/CDN/helloworld/app-extension-helloworldapplicationcustomizerstrings_en-us_7949d2dd8f4ed55ec12a8877766f5523.js
2 SEC7120: Der Ursprung https://xxxxxxxxxxx.sharepoint.com wurde im Access-Control-Allow-Origin-Header nicht gefunden.
The icon "custom" was used but not registered. See http://aka.ms/fabric-icon-usage for more information. spofiles-mini-c025e308.js(1,88278)
SEC7120: Der Ursprung https://xxxxxxxxx.sharepoint.com wurde im Access-Control-Allow-Origin-Header nicht gefunden.
HTTP500: SERVERFEHLER: Es ist ein unerwarteter Zustand aufgetreten, sodass der Server die Anforderung nicht erfüllen kann.
GET - https://publiccdn.sharepointonline.com/xxxxxxxxxxx.sharepoint.com/sites/new/CDN/helloworld/app-extension-helloworldapplicationcustomizerstrings_en-us_7949d2dd8f4ed55ec12a8877766f5523.js
SEC7120: Der Ursprung https://xxxxxxxxxxx.sharepoint.com wurde im Access-Control-Allow-Origin-Header nicht gefunden.
(translated to english)
HTTP500: SERVERERROR: There was a unexpected condition, so the server could not solve the request.
GET - https://publiccdn.sharepointonline.com/xxxxxxxxxxx.sharepoint.com/sites/new/CDN/helloworld/app-extension-helloworldapplicationcustomizerstrings_en-us_7949d2dd8f4ed55ec12a8877766f5523.js
SEC7120: The source https://xxxxxxxxxxx.sharepoint.com was not found in the Access-Control-Allow-Origin-Header

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d2c1cca-c6ef-9eb5-fcbb-78c7481b359e
* Version Independent ID: 66783ae9-b10e-5dc7-8a79-4d252ea8a9a7
* Content: [Host extension from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn)
* Content Source: [docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Is this issue still present? I’m unable to repro... as it’s over a year old, it’s likely been fixed if it was broken...
