### ISSUE TITLE
SiteStatus details needed

### ISSUE THREAD

**Issue by jbhoward** [SharePoint/sp-dev-docs#1904]
Please include all the SiteStatus responses and their meaning.

0: Not found
1: 
2: Site found / site created
3: (site not created, but why?)
…
n: ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d1ea72-8ceb-201c-e2a5-ce75033d246b
* Version Independent ID: 61532d1f-45ab-1100-0fc4-4db441b4c949
* Content: [Create SharePoint Communication site using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/communication-site-creation-rest)
* Content Source: [docs/apis/communication-site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/communication-site-creation-rest.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jbhoward** [comment]
Actually, 2: Site found.

IOW, there is no error if the site already exists, and is therefore not created as requested.

**Comment by romanSlivinskyi** [comment]
SiteStatus 1 ?

**Comment by guillaume-kizilian** [comment]
Still getting some Site Status 3 error when trying to create communication site : 
- A website with same URL is in the delete sites bin (might be a logic behavior)
- Somehow a site with the same URL was deleted (and site bin was cleaned) but SP haven't clean everything. (Definitely an issue). In this case, most of the time, you can still see the site with Get-PnPTenantSite cmdlet but cannot delete it.

Looks like this status code means "Something went wrong" with no additional precisions.

**Comment by pconnell99** [comment]
Has ANYTHING been done about documenting this?  At the present time we are hitting this call with the PNP JS libraries and it's returning a 200 WITH a Site Status = 3 and not creating anything.  Sites we are trying to create are unique.

This kind of thing is unacceptable for these API documents.

**Comment by patmill** [comment]
I've pushed an update to the doc.

The full set of values for SiteStatus are as follows:

+ `0` - Not Found. The site doesn't exist.
+ `1` - Provisioning. The site is currently being provisioned.
+ `2` - Ready. The site has been created.
+ `3` - Error. An error occurred while provisioning the site.

I've also reached out to the owning team to see about getting more information when the status is 3.
