### ISSUE TITLE
Frequent 409 errors in SharePoint REST API's

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#1905]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In our SPFx solution, when adding a user to a SiteGroup through the PnPJS library we expect the user is added to the specified sitegroup without any error

#### Observed Behavior
We see the user added to the sitegroup, but an error appears as response of the 
**api call:**
_https://ctbxrmtst.sharepoint.com/sites/p365_AVDB220518a/_api/web/sitegroups(23)/users_
**error:**
_{"odata.error":{"code":"-2130246326, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Save Conflict\n\nYour changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes."}}}_

#### Steps to Reproduce

In our SPFx Solution we perform a query to add a user to add a user to a sitegroup (where sp is imported from @pnp/sp)
`sp.web.siteGroups.getById(group.Id).users.add(user.accountName).then((siteuser) => {
                                resolve(siteuser);
                            }).catch((error) => {
                                reject(error);
                            });`

**Comment by vikbehal** [comment]
Is there any update on this issue? I noticed the issue while performing bulk delete with REST.
