### ISSUE TITLE
Wrong attribute

### ISSUE THREAD

**Issue by bbronisz** [SharePoint/sp-dev-docs#1908]
The attribute class name/namespace is broken. It's Microsoft.SharePoint.WebControlssCompliantAttribute but it should be Microsoft.SharePoint.WebControls.MdsCompliantAttribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c429a-cc75-2ac2-e21b-615fa5c8373d
* Version Independent ID: c64bee64-1ef0-7745-026c-5efaba3839e7
* Content: [Modify SharePoint components for MDS](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/modify-sharepoint-components-for-mds)
* Content Source: [docs/general-development/modify-sharepoint-components-for-mds.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/modify-sharepoint-components-for-mds.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for catching this! I've submitted a PR to get it addressed.

**Comment by bbronisz** [comment]
The fix is still not correct. Instead of WebControlsCompliantAttribute it should be WebControls.MdsCompliantAttribute :).

**Comment by thechriskent** [comment]
@bbronisz you're absolutely correct! Thanks again!
