### ISSUE TITLE
Creating a group and site collection trough Graph with app-only context, doesn't create the site collection immediately anymore

### ISSUE THREAD

**Issue by Renevdo** [SharePoint/sp-dev-docs#1911]
In the last couple of months, creating a group generated the corresponding sitecollection instantly. Since 2 weeks or so, it stopped working again. The group is created, but the sitecollection is not. When browsing to files in the group, the sitecollection is generated in a couple of seconds, and the user will be redirected to the sitecollection.

We create the group with an app-only context, on behalve of the user, so we can do provisioning also in the generated sitecollection.

Any thoughts or directions on this? We need the sitecollection to continue provisioning.

Microsoft's statement is that creating a group and sitecollection trough app-only context is a supported scenario: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly

Creating modern team sites does not support app-only when you use the SharePoint API for it. When modern team sites are created using Microsoft Graph to create the group then app-only is a supported scenario

Also, see this issue on GitHub on this: https://github.com/microsoftgraph/microsoft-graph-docs/issues/970

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e8fb5e-6609-837a-d446-22e21a15c7bd
* Version Independent ID: d884aca7-6a6e-3046-a892-2e8cf9b47665
* Content: [Accessing SharePoint using an application context, also known as app-only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly#feedback)
* Content Source: [docs/solution-guidance/security-apponly.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by charlesmln** [comment]
Also facing this here. Overall team site provisioning for an Office 365 Group has been a nightmare since the beginning, with unreliable results of New-PnPUnifiedGroup.

**Comment by BrianTJackett** [comment]
SPO site is created when specifying Owners for the O365 Group. See examples from MS Graph PR 2998 https://github.com/microsoftgraph/microsoft-graph-docs/pull/2998 (v1 endpoint) and PR 3034 https://github.com/microsoftgraph/microsoft-graph-docs/pull/3043 (beta endpoint) that are now merged into master branch.

**Comment by kumawatiitk** [comment]
We are facing similar issue. We are creating group in app context and GET DRIVE via MS Graph return Not Found after 2 hours. 
What should be owner if we are running in app context where no user id available ?

**Comment by BrianTJackett** [comment]
In the scenario of my customer they used a service / generic account as the owner of the site rather than a normal user.  That would be one option.

**Comment by andrewconnell** [comment]
This question seems answered, but also seems not specific to SharePoint, rather to the Microsoft Graph API.
