### ISSUE TITLE
Why does the example "jQueryUI Accordion" does not work with includeclientsiteassets:  true?

### ISSUE THREAD

**Issue by Hausi91** [SharePoint/sp-dev-docs#1912]
Today ive tried the Example https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part and it worked fine on the Workbench. 
When i deployed the example it wanted to load ressources from "<-- PATH TO CDN -->"
But i wanted to NOT put jQuery and jQueryUI in the Externals and set the parameter includeclientsiteassets: true.
I ran into serveral errors and i found out that the only way to make this example work on real sharepoint is to use the task "gulp deploy-azure-storage". is there a possibility to bundle jquery within the webpart and deploy it on SharepointCDN?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by cslecours** [comment]
`externals` and `includeclientsideassets` are mutually exclusive. Remove the externals section from the json and includeclientsideassets will work.

**Comment by Hausi91** [comment]
Thanks. Seems that ive some Problem with the File Mapping when trying this. After resolving this its working fine thank you!
