### ISSUE TITLE
Broken link in enterprise guidance

### ISSUE THREAD

**Issue by biste5** [SharePoint/sp-dev-docs#1913]
Under header [Current status of SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#current-status-of-sharepoint-framework) , link [General Available (GA) milestone](https://blogs.office.com/2017/02/23/sharepoint-framework-reaches-general-availability-build-and-deploy-engaging-web-parts-today/) sends to a 404

Probably it can be removed, as not vital, and the same is reported in the same article later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f553eaa8-5792-3bdf-d9a8-dcbfc92e53ab
* Version Independent ID: e16322c4-8793-4f20-bc6a-984b78c1b403
* Content: [SharePoint Framework (SPFx) enterprise guidance](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#current-status-of-sharepoint-framework)
* Content Source: [docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/enterprise-guidance.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by rohit404404** [comment]
this is still broken after 5 months :)

**Comment by ronaldborman** [comment]
Looks like this issue is already resolved in #3011. The link mentioned now points to the right target.
