### ISSUE TITLE
Error message when attempting to make react external

### ISSUE THREAD

**Issue by guapo832** [SharePoint/sp-dev-docs#1914]
When I specify React and React-dom in the externals section of the config.js and try to run gulp bundle -- ship, I receive an error that react and react-dom are already referenced in the node_modules dependencies, and so I cannot make react a global library.  This seems very important to not have react bundled in all of our webparts. If you could provide me the steps in doing so that would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666b65a6-e4e7-3dcc-e572-589fd403976c
* Version Independent ID: 356d18cd-3ec6-e95d-73b2-049eadf6c2b8
* Content: [Use existing JavaScript libraries in SharePoint Framework client-side web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries#feedback)
* Content Source: [docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You don't need to include them as external references... they are added by default. You can see this if you run `gulp bundle` and inspect the generated manifest.
