### ISSUE TITLE
Do you have to use a CDN?

### ISSUE THREAD

**Issue by mangumr** [SharePoint/sp-dev-docs#1915]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Could you host the extension in a document library or similar?

We're using Azure Express Route single entry point, so using a CDN would not be supported for internal traffic.

**Comment by luismanez** [comment]
According to this article seems possible, only that you won´t benefit from CDN advantages:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn

"There are multiple different hosting options for your web part assets. This tutorial concentrates on showing the Azure CDN option, but you could also use the Office 365 CDN or simply host your assets from SharePoint library from your tenant. In the latter case, you would not benefit from the CDN performance improvements, but that would also work from the functionality perspective. Any location that end users can access by using HTTP would be technically suitable for hosting the assets for end users."

**Comment by OliverZeiser** [comment]
If you do not enable the CDN for the ClientSideAssets library, it will not get served from CDN but instead directly from the ClientSideAssets library in SharePoint Online. I would still test the performance because reading files from a document library might still be slower, even with Azure Express Route....

**Comment by VesaJuvonen** [comment]
Like noted by @OliverZeiser, CDN is NOT required, but it will have a positive impact on the performance. If you do not have CDN enabled, assets (js files etc) are served automatically from the app catalog URLs, which would work in the scenario. This automatic hosting is available if you use 1.4 or later version and include assets in the spppkg file. Closing as answered.
