### ISSUE TITLE
Instructions incomplete?

### ISSUE THREAD

**Issue by sfkhooper** [SharePoint/sp-dev-docs#1916]
Underneath the heading "Enhance the ListView Command Set rendering" there are a couple of steps that seem to be missing required instructions. Step 1, "Return to the console, and execute the following command to include the Dialog API in our solution", is missing the command to execute. Step 4, "Add the following import statement for the Dialog class from @microsoft/sp-dialog after the existing import statements", is missing the required import statement.

Otherwise, thanks for this great article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That's a typo... I'll get that fixed. You used to have to install the library with for the dialog framework, but no more.
