### ISSUE TITLE
How to import babel-polyfill in config and webpart

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-docs#1918]
I have this **[CASE]( https://github.com/react-tools/react-table/issues/340)** who needs to use b**abel-polyfill**. How to import babel-polyfill into my web part?

**I did this**
**1)** npm install --save babel-polyfill
**2)** import "babel-polyfill"; in my entry point class of webPart

Before import **polyfill** conponent doesnt render into a page and has no errors(Only in IE, in others browsers works): 
![untitled](https://user-images.githubusercontent.com/14110861/40780506-42299bf0-64e1-11e8-89be-979f3a7c91c7.png)

After import **polyfill** into my entry point class i have following error(Only in IE, in others browsers works) 

![untitled1](https://user-images.githubusercontent.com/14110861/40780517-4c23a010-64e1-11e8-93ff-a1f5ca3142c8.png)

**Comment by neerender** [comment]
Has the issue bee resolved for you?
Even i'm facing the same issue, as you stated in the above.

**Comment by neerender** [comment]
Issues resolved for SharePoint framework webpart.
Importing polyfill would be giving an error.
No need to import polyfill,  importing  below ones's would resolve the issue.
It worked for me.

import 'core-js/es6/number';
import 'core-js/es6/array';

**Comment by Ranjan131** [comment]
This one is not worked for me. can you please provide the steps to reproduce in detail
