### ISSUE TITLE
How do we know which token color is applied to what section of page in sharepoint

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1919]
for eg token themePrimary is applied to buttons , so what  about rest of the tokens ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-theme-colors-in-your-customizations.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You can apply the tokens to any element, not just buttons. Is that what you're asking?
