### ISSUE TITLE
"npm rebuild node-sass" required whenever SPFx is updated

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-docs#192]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category

[ ] Question
[ ] Typo
[X ] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea
#### Expected or Desired Behavior

gulp serve should just work at the end of the V3 upgrade. 
#### Observed Behavior

After Gulp serve I got this error - Error - [sass] Error: Missing binding C:\XXX\YYYY/Documents\SPFx\Projects\documentcardexample-webpart\node_modules\node-sass\vendor\win32-x64-46\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 4.x

Found bindings for the following environments:
- Windows 32-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
Error - 'sass' sub task errored after 7.54 s
Missing binding C:\XXX\YYYY/\Documents\SPFx\Projects\documentcardexample-webpart\node_modules\node-sass\vendor\win32-x64-46\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 4.x

Found bindings for the following environments:
- Windows 32-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
#### Steps to Reproduce

update the CardExample and then gulp serve

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Thanks @NPrice99 .  Just to clarify - does this only happen when you upgrade from one drop to another?  If you were to create the CardExample from scratch on the latest drop, does everything work correctly?

**Comment by NPrice99** [comment]
Hi Pat

This only happens when you upgrade from one drop to another.

I have successfully created the CardExample from scratch using the latest drop and everything works correctly without any extra steps.

Regards

Nigel

**Comment by StfBauer** [comment]
Hi @NPrice99,
this is an expectable behaviour because the binary dll's you created with older drop are no longer referenced correctly. This thing happens from my experience in many other cases too.
Even when you upgrade NodeJS to the next minor version.

In SPFX there are more binary components involved then just node-sass. In this case ```npm rebuild``` without specifing the module works best.

Another thing that works in most cases is to remove the node_modules folder and execute ```npm install```this will refresh all the existing node_modules, the source code for binary components will be downloaded and compiled again.

**Comment by patmill** [comment]
Unsure if there is any work for us here.  Marking as closed.  Feel free to reopen or create a new issue to track a specific issue.
