### ISSUE TITLE
Quick Launch causes flickering on Modern Pages when it contains no items

### ISSUE THREAD

**Issue by Rainson12** [SharePoint/sp-dev-docs#1925]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When having no items in the quick launch of a sharepoint modern site the navigation should be hidden by default. It should not cause any flickering on the page. 

#### Observed Behavior

When using a modern page as the starting page of a sitecollection / intranet portal it can be very anoying that the quicklaunch first shows up and is then (if there are no quicklaunch items available) hidden client sided. There is currently no way to hide the quick launch by default as customizations are loaded too late so the quick launch first takes the space of like 100 pixels from the left and is then hidden as soon as navigation items are loaded (if there are no items present). This causes the whole page content to move/flick to the left. Our users are complaining as they sometimes already starting to read the news in the page content when suddenly the content moves 100 pixels to the left. Propobly the navigation needs to be displayed/hidden serversided instead of first loading it up and then hide it.

#### Steps to Reproduce

1. Create a new Site Page in Modern experience.
2. Remove all items of the Quick launch
3. Save / Publish
4. Load Page / Refresh Page
5. See Navigation shows up initally but then hides after a second

Ps: @VesaJuvonen requested me to post this as a bug here at the ECS as a 'reminder'. Thanks for the nice conference!

**Comment by AJIXuMuK** [comment]
Have the same issues. Customers are unhappy :)
