### ISSUE TITLE
Detect if we on in the Modern Communication Site or Modern Team Site

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#1929]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,

For this moment, we have in Environment/EnvironmentType from "microsoft/sp-core-library" a return for detect if we am on Modern or Classic Site.

Do you have a solution to detect if we on in the Modern Communication Site or Modern Team Site?

We could improve Environment/EnvironmentType from "microsoft/sp-core-library" for this detection ?

Thanks

**Comment by gautamdsheth** [comment]
The web template for Modern Communication site is 68 and for modern team site is 64.

So, in your SPFx code, you can detect it using the `pageContext` object as below:

```
if(this.context.pageContext.web.templateName == 68){
	// modern communication	site
	// do stuff here
}
else if(this.context.pageContext.web.templateName == 64){
	// modern team site
	// do stuff here
}
else{
	// not a modern team/communication site
	// do stuff here
}
```

**Comment by PooLP** [comment]
Thanks !!!

**Comment by VesaJuvonen** [comment]
Closing as @gautamdsheth's answer is 100% matching on the question. It's all about detecting the site template which is in use.
