### ISSUE TITLE
1.4.1 @types/react @types/react-dom @types/webpack-env in dependencies when they should be in devDependencies

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#1930]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`@types/react @types/react-dom @types/webpack-env` to be in devDependencies 

#### Observed Behavior

`@types/react @types/react-dom @types/webpack-env` are in the dependencies. However this is not code required at runtime but rather for build time. It should be in devDependencies 

#### Steps to Reproduce
```
yo @microsoft/SharePoint
name
SharePoint online
folder
yes
webpart
helloworld
helloworld description
React
```
then open the package.json

**Comment by andrewconnell** [comment]
Closing as issue #2249 addresses same thing, but has follow-up and commitment from engineering to address it as a tracked issue in their system.
