### ISSUE TITLE
Seryi.04.02.1976

### ISSUE THREAD

**Issue by Seryi476** [SharePoint/sp-dev-docs#1932]
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 9811970;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 12c62637-2703-f62e-4e05-47ce19b769ca
* Version Independent ID: 6a3f3f74-d4cc-c7ff-1179-2fd5487065bd
* Content: [Веб-перехватчики для списков SharePoint](https://docs.microsoft.com/ru-ru/sharepoint/dev/apis/webhooks/lists/overview-sharepoint-list-webhooks)
* Content Source: [docs/apis/webhooks/lists/overview-sharepoint-list-webhooks.md](https://github.com/SharePoint/sp-dev-docs.ru-ru/blob/live/docs/apis/webhooks/lists/overview-sharepoint-list-webhooks.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Not quite sure what this is for, except potential HTML/Script injection testing, so closing it.
