### ISSUE TITLE
Misspelled

### ISSUE THREAD

**Issue by DanishIslam07** [SharePoint/sp-dev-docs#1933]
SharePoint misspelled as "SharePoing".

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#add-users-principals-to-sharepoing-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Service: **unspecified**
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Typo fixed now. Updated accordingly in 10-15 min from this comment.
