### ISSUE TITLE
Field customizer using react does not deploy correctly

### ISSUE THREAD

**Issue by gunna025** [SharePoint/sp-dev-docs#1935]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I have created a field customizer by following the tutorial [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer). However, when scaffolding the project with Yeoman, I chose React instead of No JavaScript framework. Everything works perfectly fine when running from localhost using query parameters. However, once uploaded to the app catalog and installed on a site, I fail to see the newly created column in the SPFx columns group as expected. It is possible I am missing a configuration or a critical deployment step. I can confirm that the js bundle is on my CDN because I can request it via Postman just fine. 

#### Expected or Desired Behavior

Once the .sppkg file is uploaded to the app catalog and installed on a site, the new column should be available to add as an existing site column for lists and libraries under the SPFx Columns group or whatever group is specified in the elements.xml

#### Observed Behavior

Once .sppkg file is uploaded to app catalog and installed on a site, the column is not made available under the SPFx Columns group. I also gave it an adequate amount of time to fully deploy and become available as is common with most things in SharePoint. 

#### Steps to Reproduce

1) Run the Yeoman generator for SharePoint, yo @microsoft/sharepoint in new directory.
        yo@2.0.2
        @microsoft/generator-sharepoint@1.4.1
2) Answer the questions as follows: Accept default solution name, SharePoint Online only (latest), Use current folder, N, Extension, Field Customizer, default name, default description, React
3) Make any sort of rendering changes you would like, I simply changed the scss to make the text red.
4) gulp bundle --ship
5) gulp package-solution --ship
6) Upload .sppkg file to app catalog
7) Install as new app on site
8) Go to list or library on site
9) Go to list or library settings
10) Select Add from existing site columns
11) Select SPFx Columns group from drop down
12) No new available site column

**Comment by patmill** [comment]
OK, so there is a misunderstanding here.  The column formatter doesn't create the column, it is used to change the rendering of an existing column - similar to the jslink property on classic lists/libraries.

Just double-checking, did you follow the steps in this part (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#add-the-field-definition-to-the-solution-package-for-deployment) and create the element.xml file / rebuild/package/deploy the solution, etc?

**Comment by gunna025** [comment]
@patmill Thanks for the response. Here is the elements.xml:

`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <Field ID="{5ab7b573-15a7-4f0c-8162-6bef4b7564f5}"
            Name="SPFxWorkflowSummary"
            DisplayName="Workflow Summary"
            Type="Text"
            ReadOnly="TRUE"
            Required="FALSE"
            Group="SPFx Columns"
            ClientSideComponentId="cf9513f9-105c-434e-937f-d57f4d7f7cf6">
    </Field>
</Elements>`

This was in the solution at the time of creating the sppkg, the sppkg was uploaded to the app catalog, and installed on a site. It was my impression that a new column gets created based on these properties, but above you mentioned it needs to target an existing site column. This seems logical to me, but how do I go about targeting an existing site column? In the previously mentioned tutorial, I do not see where they are targeting an existing site column. I don't believe that 'Percentage' is a default site column, yet it worked for me when I followed the tutorial and did not use react, thus my suspicion that it is the culprit.

**Comment by CPritch** [comment]
I was fighting this inside and out. If there's any issue with your Elements XML it will silently fail to deploy and the Site Column will not be created. A site column should be created if successfully added to a site.

Is the solution tenant deployed? If not you will need to add the app to a site before the site column is created.

From what I can see it looks like the Elements XML is correct, I'm not sure if ClientSideComponentProperties are required though but if they are this could be the issue.

I'd try changing your Elements.xml to this and redeploying:
```XML
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <Field ID="{5ab7b573-15a7-4f0c-8162-6bef4b7564f5}" Name="SPFxWorkflowSummary" DisplayName="Workflow Summary" Type="Text" ReadOnly="TRUE" Required="FALSE" Group="SPFx Columns" ClientSideComponentId="cf9513f9-105c-434e-937f-d57f4d7f7cf6" ClientSideComponentProperties="{}"></Field>
</Elements>
```

**Comment by Harshagracy** [comment]
@CPritch : I have to run the below PowerShell script to bind the solution with the existing column. 

```
$siteUrl =  "https://abc.sharepoint.com/sites/abc/"  
$listTitle = "listname"
$fieldTitle= "Country"
Connect-PnPOnline -Url $siteUrl
$list = Get-PnPList -Identity $listTitle  
$fld = Get-PnPField -List $list -Identity $fieldTitle  
$fld.ClientSideComponentId = "b44de226-b2d2-44a4-b75f-b69be27e4202"  
$fld.Update()  
Invoke-PnPQuery 
```
