### ISSUE TITLE
Yeoman generator does not correctly implement the update-notifier API

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#194]
#### Category

[ ] Question
[ ] Typo
[x] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea
#### Expected or Desired Behavior

In general yeoman generator notifies when new version is avaiable right before a new project will be started. In generator-sharepoint it is the other way round.

I create a project last night and it fully provisioned after I got the following notification.
<img width="470" alt="screen shot 2016-09-15 at 23 34 02" src="https://cloud.githubusercontent.com/assets/5503835/18579705/a0fc265e-7bf7-11e6-9d76-71c24e1f44c1.png">

Please put yeomans default [update-notifier](https://github.com/yeoman/update-notifier) in right order. Thank you.

**Comment by estruyf** [comment]
@StfBauer that seems to be the default behaviour of the update-notifier. 

> Whenever you initiate the update notifier and it's not within the interval threshold, it will asynchronously check with npm in the background for available updates, then persist the result. The next time the notifier is initiated the result will be loaded into the `.update` property. This prevents any impact on your package startup performance. The check process is done in a unref'ed child process. This means that if you call process.exit, the check will still be performed in its own process.

So it will notify you the next time you run the generator.

**Comment by patmill** [comment]
We are working on an environment validator.  Making sure this is covered as well.

**Comment by StfBauer** [comment]
@estruyf yes that's true but it should be placed before the generator start working not at the end. Because i create a project that I have to delete because it's the old version.

@patmill The only thing that needs to be done in the index.js of the generator is to move line 13:

```
updateNotifier({ pkg }).notify();
```

inside the initializing or constructor to disable the defautl defer to the end of the thread:

```
    var update = updateNotifier({ pkg });
    update.notify({defer: false}); // turns defer to false
```

Especially with this generator it's important that the message comes at the beginning becaue when you update the generator and run it again you will create a new web part maybe.

**Comment by nickpape-msft** [comment]
This has been fixed.
