### ISSUE TITLE
Provide SPFx Webparts with an site template

### ISSUE THREAD

**Issue by 4lexk** [SharePoint/sp-dev-docs#1942]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Provide SPFx Webparts within a site template:
1. Put Webparts on a page
2. use /_layouts/15/savetmpl.aspx to save site as a template
3. create a new site from it
--> Webparts are in place and ready to use

#### Observed Behavior

Provide SPFx Webparts within a site template:
1. Put Webparts on a page
2. use /_layouts/15/savetmpl.aspx to save site as a template
3. create a new site from it
--> Webparts are not in place, but visible with the **?contents=1** parameter
--> I'm also able to add Webparts manually on the new created site

#### Steps to Reproduce

1. Put Webparts on a page within (e.g.) a team site
2. use /_layouts/15/savetmpl.aspx to save site as a template
3. create a new site from it

Please advise how to provide Client Side Webparts with an site template.

**Comment by patmill** [comment]
You are likely running into an issue where the solution/package isn't installed on the target site.  My guess would be that marking the webpart as available globally would solve this issue.

**Comment by 4lexk** [comment]
@patmill  what do you mean by making them globally available?

I'm able to add all SPFx WebParts manually on all sites created from this template. I've checked the box "Make this solution available to all sites in the organization" during the deployment.
Is there anything else to be considered?
