### ISSUE TITLE
Is it okay to use @microsoft/office-ui-fabric-react-bundle ?

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1943]
#### Category
- [X] Question

#### Expected or Desired Behavior
We would like to use the` @microsoft/office-ui-fabric-react-bundle` npm package in our solution. Since this is loaded by MS on the page already, this would dramatically reduce the bundle size of our sharepoint framework bundles.

**Comment by patmill** [comment]
You currently need to bundle fabric react internally to your solution.  You can't use the version that is included in the page itself.  You should also only include the individual components you want via path, rather than the entire package.
