### ISSUE TITLE
Private groups are not showing up in my/followed

### ISSUE THREAD

**Issue by btastic** [SharePoint/sp-dev-docs#1944]
A private group created via Microsoft Teams will not show up when querying the my/followed endpoint.

Is there anything we can do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6241b0c-5fed-5dc2-63c8-b84232d1bd89
* Version Independent ID: 9b6bb121-3908-ea83-3621-85f1528600fd
* Content: [Following people and content REST API reference for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/following-people-and-content-rest-api-reference-for-sharepoint)
* Content Source: [docs/general-development/following-people-and-content-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/following-people-and-content-rest-api-reference-for-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unclear as to the question... can you provide more context / detail?

**Comment by andrewconnell** [comment]
ok... so... this can be closed?
