### ISSUE TITLE
Adding ui-fabric to asp.net core

### ISSUE THREAD

**Issue by B-Esmaili** [SharePoint/sp-dev-docs#1945]
How about adding ui-fabric to asp.net core? why docs are lacking for adding ui-fabric to asp.net core app? i couldn't find any doc-sample to get ui-fabric working with asp.net core react template.any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dedd717-ec39-dcd9-3994-7bab3839df28
* Version Independent ID: 0eddf92b-1b20-650e-2432-83c530279815
* Content: [Using Office UI Fabric Core and Fabric React in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration)
* Content Source: [docs/spfx/office-ui-fabric-integration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/office-ui-fabric-integration.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by srfconsultores** [comment]
This problem has been fixed in update asp.net core 2.1 and visual studio 15.7

**Comment by andrewconnell** [comment]
That's more of a question for the Office UI Fabric project/team rather than in the SharePoint docs... best to post your question here https://github.com/OfficeDev/office-ui-fabric-core or here https://github.com/OfficeDev/office-ui-fabric-react
