### ISSUE TITLE
Azure Functions or Azure Automation

### ISSUE THREAD

**Issue by bcaauwe** [SharePoint/sp-dev-docs#1948]
Since using PowerShell with Azure Functions is only an "experimental" feature and will not be continued with the next version as stated here: https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages.  Is there a reason the guidance isn't to use an Azure Automation runbook with a webhook instead using the same pattern?  Also the ability to import the PnP PowerShell modules into Azure Automation is significantly easier and gives you a centralized secured credential, certificate and variable management for runbooks associated with an automation account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by umaknow-francis** [comment]
I have the same question!

**Comment by Maher256** [comment]
Azure Functions now only allow you to select 2.x languages, so you cannot select PowerShell anymore. I guess its time to look into Azure Automation or the .Net version of the PnP Provisioning engine.

**Comment by andrewconnell** [comment]
PowerShell is an option with Azure Functions v2... the page you linked to in your post lists it as being in preview in v2 as of August 2018, and confirmed here: https://azure.microsoft.com/en-us/blog/serverless-automation-using-powershell-preview-in-azure-functions

There's nothing discouraging you from using Azure Automation... it just wasn't shown in this doc.

**Comment by PzKfWg** [comment]
Not so fast! It is Powershell "Core" which provides little to no support to SharePoint PowerShell modules like PnP or official SPO shell, as far as I know...

**Comment by PzKfWg** [comment]
Again, today, I would clearly recommend using Automation instead of Function in the context of a site provisioning based on site scripts!

**Comment by andrewconnell** [comment]
@PzKfWg said:
> It is Powershell "Core" which provides little to no support to SharePoint PowerShell modules like PnP or official SPO shell, as far as I know...

Good point. I know that's a focus of PnP POSH, but not sure what the current state is. I have it installed and running on my machine (macOS):

![image](https://user-images.githubusercontent.com/2068657/59800611-145ebe00-92b5-11e9-88af-cfa1c05513c5.png)

With that being said, it's still an option that works with v1. If you have a suggestion to update the doc to use Azure Automation, I'd run it by @erwinvanhunen who would own this part of the doc and see if that's the recommended guidance by PnP / MSFT. If so, this would be a great op for a community contribution!
