### ISSUE TITLE
Stale Content?

### ISSUE THREAD

**Issue by MikeBass13** [SharePoint/sp-dev-docs#1949]
In the "What not to do" section the document says not to have "Have too many top-level parent portal site collections". Isn't this what MS now recommends? And the solution is to manage some of those Site Collections with Hub Sites?
I am worried that this page may be confusing to new SP Architects. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8babdc28-eedd-9d34-076d-1a7bf3aed73a
* Version Independent ID: 0e50151b-2d9c-1838-7c2b-6cc01723222c
* Content: [Information architecture guidance for SharePoint Online portals](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-information-architecture)
* Content Source: [docs/solution-guidance/portal-information-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-information-architecture.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... I think it's best to follow this guidance for now: https://docs.microsoft.com/en-us/sharepoint/information-architecture-modern-experience

I'll raise this internally to see if we need to retire this page... as it seems like a stale dupe...
