### ISSUE TITLE
Deploy to Azure CDN Documentation bug

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#195]
This looks like a documentation but, but I might be wrong, on this page:
http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn

#### Category
[ ] Question
[X] Typo
[ ] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

Issue:
1. On the section
Configuring web part to load from CDN, it says that we need to replace the url with that one from the CDN, the page shows something like this:

{
  "cdnBasePath": "https://spfxsamples.azureedge.net/helloworld-webpart/"
}

However, when testing this my self, I noticed that url ( of course replacing with my storage account and container) does not resolve to any of my files after a gulp deploy to azure.

I had to change it to something like this and it worked perfectly fine.
{
  "cdnBasePath": "https://spfazurecdn.blob.core.windows.net/spfazurecdn2/"
}

**Comment by wobba** [comment]
You need to set up an Azure CDN which lies on top of your blob to make this work. If you follow the docs closely it references how to do this as well. The easy way is like you do to reference the blob directly, but often it's better to hide that blob URL behind a caching system.

So the docs are correct, but could possibly point out both ways.

**Comment by levalencia** [comment]
I did created the Azure CDN, and the endpoint as well,  I will read again and try, and I will let you know, probably I missed something.

**Comment by levalencia** [comment]
I already removed my sample from azure, but I guess my error  is due to this note on azure documentation:

Note:
The endpoint will not immediately be available for use. It can take up to 90 minutes for the registration to propagate through the CDN network. Users who try to use the CDN domain name immediately may receive status code 404 until the content is available via the CDN.

I will proceed to close this bug.
