### ISSUE TITLE
When will these be ready for General Availability?

### ISSUE THREAD

**Issue by tom-daly** [SharePoint/sp-dev-docs#1950]
Customers are asking when these will become ready? i've heard/read spring but it's now summer. Is there any updated timeline? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There's been no public statement from MSFT on when things will reach GA. Listening to the bi-weekly SIG calls sounds like maybe sometime over the mid-year, but likely by Ignite in September 2018.
