### ISSUE TITLE
How to consume this Add In?

### ISSUE THREAD

**Issue by sfkhooper** [SharePoint/sp-dev-docs#1951]
Having followed this tutorial and successfully published to the app catalog, and then adding it via Site Contents - Add an App to my site, just how do you consume it? The Draft Documents and Published Documents libraries didn't just appear of course, but when I created them both and then added a document to Draft Documents, I couldn't see any way of invoking the new workflow. How is this achieved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d5ab1b-cedf-6722-13cf-3fa51efb619e
* Version Independent ID: cfa1b40a-c3c1-0bd1-3211-e2a92029ffbc
* Content: [Create a SharePoint workflow app using Visual Studio 2012](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-sharepoint-workflow-app-using-visual-studio-2012)
* Content Source: [docs/general-development/create-a-sharepoint-workflow-app-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/create-a-sharepoint-workflow-app-using-visual-studio-2012.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Once the workflow has been deployed, you need to associate it to the list. The lists you selected in the workflow when creating it were just used during development. When a workflow is deployed, it doesn't automatically associate it with existing lists. Think about it like this: you just created the program and deployed it... now you need to create an association with a list.

Do this by going to the list's settings, select **Workflow Settings** and adding an association. If the workflow is available for the list in question, you can select it and add any necessary configuration settings.
