### ISSUE TITLE
TimeZoneInfo in 1.5 release is missing!

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1953]
#### Category
- [X] Question
- [X] Bug

#### Expected or Desired Behavior
Up to SPFX 1.4.1 there was a timeZoneInfo property on SPUser and SPWeb in the pagecontext, which was now removed. This was one of the most useful properties. Why did you remove this? What should we use instead to get the current timezone settings of the user in order to display date and time correctly in our webparts?

#### Observed Behavior
In the d.ts file it states: "Excluded from this release type: timeZoneInfo" ...without further explanation.

**Comment by patmill** [comment]
Looking into this one, it appears that it was switched from public to alpha.  Total hack, but for now you could likely cast the object to any and then access the property (it's there, it's just no in the d.ts file).  

Thanks for pointing these out.

Pat.

**Comment by OliverZeiser** [comment]
Thx @patmill this helps. If it is okay and supported to cast the object as any, I am happy with that. As long as the property stays there and has an actual value ;)

**Comment by VesaJuvonen** [comment]
Just to follow up on this. We will be addressing this in the 1.5.1 release, which is coming soon.

**Comment by VesaJuvonen** [comment]
This should be now addressed with the 1.5.1 release, so would request to validate the situation with following. Here are short release notes for 1.5.1 release - https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-for-SPFx-Package-Version-1.5.1.

**Comment by OliverZeiser** [comment]
This issue happend again in 1.6. timeZoneInfo is missing again. Please add this back again :)

**Comment by patmill** [comment]
Well crap....  Let me see what happened.

**Comment by patmill** [comment]
Hey @OliverZeiser - From the code / interfaces, it should be present in the -beta packages.  1 - do you see the timezone APIs there and 2 - were they in the public 1.5.1 release, or the -withbeta 1.5.1 release?

**Comment by OliverZeiser** [comment]
Hey pat, thanks for clarifying this and sorry.... You are right, they were part of the -plusbeta and now I upgraded my solution to 1.6 but not the plusbeta version of it this time. I think I got confused by the 1.6.0-dk.3 release from devktichen that had this included.
Well, but maybe you can take that as a feedback and move it to GA in 1.7 as I do not see any reason to keep it in the -plusbeta. It has been working just fine so far ;)
