### ISSUE TITLE
Question about the 'p_ID'

### ISSUE THREAD

**Issue by Yuanyingbo102** [SharePoint/sp-dev-docs#1954]
Sorry but I have another question : Column 'ID' is default column created by Sharepoint , when I delete an item 'A' , the 'ID' of 'A' will still exist , so in this situation how can I exactly skip the right p_ID , thx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#query-for-single-value-lookup-fields)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm not clear on what you're asking... can you provide a bit more information?
