### ISSUE TITLE
Disable mangling by default in `ship` mode

### ISSUE THREAD

**Issue by nero120** [SharePoint/sp-dev-docs#1955]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Having deployed a number of SPFX solutions to production, by far our biggest support issue is the difficulty in investigating client errors. We are using Azure Application Insights to track user sessions and log client errors that are caught and handled gracefully, but when an issue occurs the following stack trace is not very helpful:

```
TypeError: Cannot read property 'preferredName' of undefined
    at https://xxx.sharepoint.com/sites/xxx/ClientSideAssets/063b99d1-2b82-4948-b777-c4d8f7f47c2e/home-page-web-part_2414fd410ecad3ec78fb91eeb3debc75.js:42:95917
    at Array.map (<anonymous>)
    at e.<anonymous> (https://xxx.sharepoint.com/sites/xxx/ClientSideAssets/063b99d1-2b82-4948-b777-c4d8f7f47c2e/home-page-web-part_2414fd410ecad3ec78fb91eeb3debc75.js:42:95765)
    at r (https://xxx.sharepoint.com/sites/xxx/ClientSideAssets/063b99d1-2b82-4948-b777-c4d8f7f47c2e/home-page-web-part_2414fd410ecad3ec78fb91eeb3debc75.js:42:73269)
    at Object.next (https://xxx.sharepoint.com/sites/xxx/ClientSideAssets/063b99d1-2b82-4948-b777-c4d8f7f47c2e/home-page-web-part_2414fd410ecad3ec78fb91eeb3debc75.js:42:72604)
    at a (https://xxx.sharepoint.com/sites/xxx/ClientSideAssets/063b99d1-2b82-4948-b777-c4d8f7f47c2e/home-page-web-part_2414fd410ecad3ec78fb91eeb3debc75.js:42:72346)
```

We really need (at the very least) to see method names in a stack trace in order to investigate issues, otherwise the stack trace is pointless (and by extension there's not much point paying for Insights to log a useless stack trace). Ideally we'd get correct source (TypeScript) file references and line numbers as well but that seems too much to hope for for the time being (that's progress I guess!).

As a very significant proportion (if not the majority) of SPFX solutions will be for internal enterprise applications that are not accessible by the public I'd question the benefit of mangling packaged source code by default. At the very least we should have an option to disable it.

I understand that reducing package size is a consideration, but dependencies will be by far the bigger culprit and saving a few hundred kbs by mangling your own source code will not make a difference to the end user experience, when losing the ability to adequately support your solutions is a far bigger concern.

**Comment by nero120** [comment]
This is still a big issue for us, is there any updates or news that might resolve it?

**Comment by waldekmastykarz** [comment]
@nero120 you might find this helpful: https://blog.mastykarz.nl/inconvenient-logging-exceptions-sharepoint-framework-production-bundles/

**Comment by nero120** [comment]
@waldekmastykarz many thanks for that blog post, just what I was looking for!

Note, I was originally getting the following error when attempting to add the resulting sppkg file to the site collection App Catalog:

```
Invalid SharePoint App package. Error: Unrecognized tag found in Relationships XML. Line 1, position 7997.
```

This was due to a comma appearing between the two map file elements. I resolved this by updating the line in the gulp task to:

```
const mapsRels = mapFiles.map(m => `<Relationship Type="http://schemas.microsoft.com/sharepoint/2012/app/relationships/clientsideasset" Target="/ClientSideAssets/${m}" Id="r${++relId}"></Relationship>`).join('');
```

(adding the `.join('')` at the end).

**Comment by waldekmastykarz** [comment]
Thanks for sharing!

**Comment by nero120** [comment]
@waldekmastykarz looks like this has been broken by upgrading to spfx v1.9.1, I'm getting the following error when running `gulp serve`:

```
webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

Do you have an updated approach for v1.9.1+?
