### ISSUE TITLE
What is the replacement for spHttpClient.beginBatch in spfx 1.5?

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1956]
#### Category
- [X] Question

#### Expected or Desired Behavior
We would like to make batch requests using spHttpClient. This was working as preview functionality in spfx 1.4.1

#### Observed Behavior

spHttpClient.beginBatch was removed with 1.5 build. What is the idea behind this and what is the recommended way if we want to do batching within the sharepoint framework?

**Comment by vman** [comment]
Hi @OliverZeiser 

`spHttpClient.beginBatch` is still in preview so it has now been moved to the `plusbeta` channel in SPFx.

To generate a project with preview components, use the --plusbeta flag:

`yo @microsoft/sharepoint --plusbeta`

**Comment by OliverZeiser** [comment]
Thx, that makes sense....

**Comment by jashwanthreddyn** [comment]
Hi @vman : I'm on spfx 1.7, spHttpClient.beginBatch is still in preview ?
