### ISSUE TITLE
UrlUtilities from @microsoft/sp-core-library was removed in SPFX 1.5

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#1957]
#### Category
- [X] Question

#### Expected or Desired Behavior
There was a nice Utility up until 1.4.1 in `@microsoft/sp-core-library` that we would like to have back.

#### Observed Behavior
Why was this removed and is there a replacement for this?

**Comment by patmill** [comment]
So it looks like that class was never marked as public or beta, and was stripped out during the --plusbeta work to remove non public (or non-beta) APIs.  I will add that to the list of things that people would like public.

In the meantime, there is a file called UrlUtilities.js in the sp-core-library node modules folder...
