### ISSUE TITLE
Are the ALM Apis available within CSOM or PnP Core ?

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#1958]
Are the ALM Apis available within CSOM or PnP Core ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by luismanez** [comment]
Seems so according to this namespace:
_OfficeDevPnP.Core.ALM_

Have a look to this Test class from PnPCore lib:
https://github.com/SharePoint/PnP-Sites-Core/blob/3a24b0c270d3086513f08778a72524272c9c3cfd/Core/OfficeDevPnP.Core.Tests/ALM/ALMTests.cs
