### ISSUE TITLE
SP Website contexte/sealing is broken since partial reloading

### ISSUE THREAD

**Issue by guillaume-kizilian** [SharePoint/sp-dev-docs#1959]
#### Category
- [X] Bug

#### Env
- [x] SharePoint Online

#### Expected Behavior
- I expected SharePoint sites content not to impact other SharePoint sites.

#### Observed Behavior
Recently an update appeared to have been applied so that different SharePoint com sites on same tenant are not fully reloaded. (and not fully destroyed either). A bug have been introduced in this update since we're able to add to a page webpart that aren't installed on a specific site but on the previous site we were. (stylesheets have impacts too)

#### Steps to Reproduce

1. Install a webpart on com site A but not on com site B
2. Visit a page on A with a link on site B. (if a blue on white loading bar appears at the top of your screen then your page is not fully reloaded).
3. Click modify the page on B.
4. Look for your webpart in the list (it s there).

If you have a webpart or extension that overload SP Style on site A it will also on site B. (since the code stay in the html somewhere).

Regards,

**Comment by patmill** [comment]
Interesting - thanks for the report.  Let me follow up with the team.

**Comment by guillaume-kizilian** [comment]
Yes,  it is indeed an inappropriate "doing it cause no other solution where provided and the client is still asking"...

Thanks.

**Comment by patmill** [comment]
ok.  So the webpart showing is a bug, and we are fixing that.  No change needed by you.  For the style part, are you trying to do customized themes or something?

**Comment by tdwhite0** [comment]
@patmill Could this be related https://github.com/SharePoint/sp-dev-docs/issues/2023 ? I see webparts running their onInit and render methods multiple times when navigating.

**Comment by patmill** [comment]
@tdwhite0 - no, this is a separate issue.  The manifest for the webpart that is installed in site collection 1 remains in memory, and in site collection 2, it is added to the list of available webparts in the toolbox.  The solution is to remove the manifests for webparts that are not applicable when doing an in-place navigation.  The lifecycle calls are a different issue that needs to be looked into.

**Comment by guillaume-kizilian** [comment]
@patmill We were trying to hide Sharepoint header (Logo, QuickLink, Search,...) on Home.aspx
