### ISSUE TITLE
Footer Documentation on Office Dev website

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#196]
Not sure, if this is the right place, but the office dev website:
http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn

In the footer, there is a link to the old yammer IT Pro network URL, but that changed on the 15th to techcommunity.
#### Category

[ ] Question
[X ] Typo
[ ] Bug
[ ] Enhancement / Suggestion
[ ] Additional article idea

**Comment by chakkaradeep** [comment]
Thanks! We will be updating the Office Dev Center soon with the proper links.

**Comment by keyur32** [comment]
Hi, I was a bit delayed in responding to this issue, but we updated the links below a month ago. Let me know if you still see any issues.

**Comment by DanKline** [comment]
I'm trying to build a powershell script to automate all the steps on https://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment and then run the yo scafolding from 
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part
I've created the PowerShell Script and It appears to work perfectly until it runs the "yo @microsoft/sharepoint" command.  It then seems to hang forever.  I've tested the command from a command prompt and Yeoman builds the project perfectly, so I know everything except the way I'm launching yeoman worked.

Here's the powershell script.  Can you provide any guidance?  I'd like to use the script to lead a usergroup orientation on the framework.

...write-host "Installing Windows Build Tools"
npm install -g --production windows-build-tools
write-host "Installing Yeoman and Gulp"
npm install -g yo gulp
write-host "Installing generator-sharepoint"
npm install -g @microsoft/generator-sharepoint
$ProjectRootDir = Read-Host 'Enter the Root Directory path to install project folder'
If(!(test-path $ProjectRootDir))
{
    New-Item -ItemType Directory -Force -Path $ProjectRootDir
}
cd $ProjectRootDir
$ProjectName =  Read-Host 'Enter a name for your project'
If(!(test-path $ProjectName))
{
    New-Item -ItemType Directory -Force -Path $ProjectName
}
cd $ProjectName
write-host "Running Yeoman generator"
& cmd /c 'yo 2>&1' @microsoft/sharepoint ...

**Comment by levalencia** [comment]
the issue is closed and your commend has nothing to do with the issue
