### ISSUE TITLE
Addins name are all the same on modern experience

### ISSUE THREAD

**Issue by guillaume-kizilian** [SharePoint/sp-dev-docs#1960]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Different names for each webpart

#### Observed Behavior

- Same names on modern UI but not on classic experience (gif)
![ezgif-5-e23b61d75f](https://user-images.githubusercontent.com/6792560/41050315-4e367ad6-69b3-11e8-97db-b24142585832.gif)

#### Steps to Reproduce

I installed all my webparts on office public cdn with includeclidesideassets = true.

Regards,

**Comment by Nasicus** [comment]
Same problem for us didn't find out yet what the cause of this is... checked if our two apps have the same id somewhere or the same now, but they haven't...

**Comment by patmill** [comment]
I'm clearly getting old, and can't see very well (or pause gif's).  Can you update this with two screenshots, one on modern and one on classic, that show the problem?

Also, did you install 2 solutions?  4 solutions?

Thanks.

**Comment by guillaume-kizilian** [comment]
@patmill 
There is not much to see except that my 4 addins have the same names on the modern ui and their real name on the classic experience. 
![image](https://user-images.githubusercontent.com/6792560/41085038-1315dbf8-6a36-11e8-89d5-39acce628b76.png)
![image](https://user-images.githubusercontent.com/6792560/41085144-6314ccae-6a36-11e8-9a3a-8afab29d3c4f.png)

In this particular example i have 4 differents addins (2 extensions and 2 webparts solutions) with the name of one of my addins on every solutions.

It happens on every tenant we have no matter how many solution there is and never change.

Thanks.

**Comment by tdwhite0** [comment]
See #1773

**Comment by guillaume-kizilian** [comment]
This issue has been fixed.
Topic can be closed. :+1:
