### ISSUE TITLE
SiteDesignId = null gives error

### ISSUE THREAD

**Issue by jbhoward** [SharePoint/sp-dev-docs#1962]
Specifically, I get the error: A null value was found for the property named 'SiteDesignId', which has the expected type 'Edm.Guid[Nullable=False]'. The expected type 'Edm.Guid[Nullable=False]' does not allow null values."} 

…when "SiteDesignId":null

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d1ea72-8ceb-201c-e2a5-ce75033d246b
* Version Independent ID: 61532d1f-45ab-1100-0fc4-4db441b4c949
* Content: [Create SharePoint Communication site using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/communication-site-creation-rest)
* Content Source: [docs/apis/communication-site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/communication-site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like the doc this question was left on has been deleted / renamed. I'm not clear on what you're saying without the doc as there's no context as all that's provided is just an error message.
