### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by Alex-Ji** [SharePoint/sp-dev-docs#1963]
The first story：
One modern page is as landing page. 
A SharePoint framework client side webpart (recent documents) which reading documents from library.

I recognize that recent documents webpart have a bug, it will keep requesting data again and again when library name is wrong. 

Actual Result: It still keep requesting data when i remove webpart from page. it never stop when i remove webpart and 
refresh browser.
Expected Result:Webpart should be removed completely(never send request) when i refresh browser.

The second story:
One modern page is as landing page. 
A SharePoint framework client site webpart (change layout) which will change modern page layout, for example hidden left navigation, change 
left and right margin and so on.

When modern page have a link which will open another modern page in current tab. 

Actual Result: The css style still work for the new opening modern page. Opening page in other tab works well.
Expected Result: Css style don't affect the new opening morden page because it did not deploy the change layout webpart yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8a9569-88ea-1ea8-82dd-3ddb0b9f89f9
* Version Independent ID: b3b2948f-6e74-a06a-8ef5-4661b7f5e5b7
* Content: [Modernize customizations](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations)
* Content Source: [docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-customizations.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Please submit a single issue in each submission to better track & help with the issue.

For the second item, it sounds like you're doing DOM manipulation with CSS by hiding the left & right navigation & elements. That's not supported. Further, the CSS you're adding to the page is not added to all pages so it won't be present for the second (opening) page.
