### ISSUE TITLE
Placeholders do not render on mobile

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-docs#1965]
Hi,

It would be great if the placeholders would render on mobile. I think leaving it up to the dev building the placeholders content to make it responsive is reasonable.  It would also make the experience between desktop and mobile even more consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Thanks @HTEredrock for the input. We absolutely get this request and are working on making it happen. I'll close this comment as acknowledged as there's not that much more I can provide right now. Thanks for your input.
