### ISSUE TITLE
Version 1.5.0-plusbeta Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'

### ISSUE THREAD

**Issue by sid1260** [SharePoint/sp-dev-docs#1966]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I wanted to use the dynamicDataSourceManager ( based on the example https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data ). This required a version 1.5.0-plusbeta. I ended up upgrading to the beta version, but I am facing the following issue
**Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'**

I tried to delete the node module and run "npm  i". But facing the same error.

#### Steps to Reproduce

I ran the following 
npm i `@microsoft/decorators@1.5.0-plusbeta`
npm i `@microsoft/sp-application-base@1.5.0-plusbeta`
npm i `@microsoft/sp-core-library@1.5.0-plusbeta`
npm i `@microsoft/sp-dialog@1.5.0-plusbeta`
npm i `@microsoft/sp-dynamic-data@1.5.0-plusbeta`
npm i `@microsoft/sp-lodash-subset@1.5.0-plusbeta`
npm i `@microsoft/sp-office-ui-fabric-core@1.5.0-plusbeta`
npm i `@microsoft/sp-webpart-base@1.5.0-plusbeta`
npm i `@microsoft/sp-build-web@1.5.0-plusbeta`
npm i `@microsoft/sp-http@1.5.0-plusbeta`

Error in the line spHttpClient.post
let options: ISPHttpClientOptions = { headers: { 'odata-version': '3.0' }, body: JSON.stringify(data) };
        const spConfig: ISPHttpClientConfiguration = {
            defaultODataVersion: ODataVersion.v3
          };
          const clientConfigODataV3: SPHttpClientConfiguration = SPHttpClient.configurations.v1.overrideWith(spConfig);
       
        return this._context.spHttpClient.post(endpoint, clientConfigODataV3, options)

Exact error:
Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.

My package.config is the following:
{
  "name": "digital-workplace",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "`@microsoft/decorators`": "^1.5.0-plusbeta",
    "`@microsoft/sp-application-base`": "^1.5.0-plusbeta",
    "`@microsoft/sp-core-library`": "^1.5.0-plusbeta",
    "`@microsoft/sp-dialog`": "^1.5.0-plusbeta",
    "`@microsoft/sp-dynamic-data`": "^1.5.0-plusbeta",
    "`@microsoft/sp-http`": "^1.5.0-plusbeta",
    "`@microsoft/sp-lodash-subset`": "^1.5.0-plusbeta",
    "`@microsoft/sp-office-ui-fabric-core`": "^1.5.0-plusbeta",
    "`@microsoft/sp-webpart-base`": "^1.5.0-plusbeta",
    "`@pnp/common`": "^1.1.0",
    "`@pnp/logging`": "^1.1.0",
    "`@pnp/odata`": "^1.1.0",
    "`@pnp/sp`": "^1.1.0",
    "`@types/react`": "15.6.6",
    "`@types/react-dom`": "15.5.6",
    "`@types/webpack-env`": ">=1.12.1 <1.14.0",
    "gulp-spsync-creds": "^2.3.8",
    "jquery": "^3.3.1",
    "npm-check-updates": "^2.14.2",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-flip-move": "^3.0.2",
    "react-iframe": "^1.1.0",
    "run-sequence": "^2.2.1",
    "sp-client-custom-fields": "^1.3.7"
  },
  "devDependencies": {
    "`@microsoft/sp-build-web`": "^1.5.0-plusbeta",
    "`@microsoft/sp-module-interfaces`": "^1.5.0-plusbeta",
    "`@microsoft/sp-module-loader`": "^0.5.1",
    "`@microsoft/sp-webpart-workbench`": "^1.5.0-plusbeta",
    "`@types/chai`": ">=3.4.34 <3.6.0",
    "`@types/mocha`": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2",
    "css-loader": "^0.28.11",
    "gulp": "~3.9.1",
    "style-loader": "^0.21.0"
  }
}

**Comment by guillaume-kizilian** [comment]
Can't you list your imports too?

**Comment by sid1260** [comment]
Sure..

import { AadHttpClient, 
    HttpClientResponse, 
    ISPHttpClientConfiguration,
    ODataVersion,
    SPHttpClientConfiguration, 
    ISPHttpClientOptions, 
    SPHttpClientResponse,
    SPHttpClient } from '@microsoft/sp-http';
import { Text } from '@microsoft/sp-core-library';
import {
    WebPartContext
} from '@microsoft/sp-webpart-base';
import {
    sp,
    Web,
    Item,
    ListEnsureResult,
    SPConfiguration
} from "@pnp/sp";

**Comment by patmill** [comment]
In the past what I've noticed with npm is that you need to delete the package lock file when you delete node_modules.  The error you see normally means that there are multiple copies of a package.  Alternately, I've found that using pnpm gets rid of the mistakes that npm typically generates.

**Comment by sid1260** [comment]
I had tried the the deletion of the package-lock.json file , but still facing this issue. I ended up using Redux to connect two webparts. Probably will wait for a stabler release to implement the event notification feature. 

I have not tried pnpm. But thanks for the pointer.

**Comment by countvm** [comment]
Had the same issue, installed Yarn solved it.
