### ISSUE TITLE
Missing CLIENTSIDEASSETS | Error with loading webpart

### ISSUE THREAD

**Issue by gosiaborzecka** [SharePoint/sp-dev-docs#1967]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I wanted to host a webpart on Office 365 CDN. I've checked that I have everything enabled:
![image](https://user-images.githubusercontent.com/2411260/41090520-5d396c76-6a3c-11e8-9161-8d4510bad157.png)

Unfortunately, when I deploy the app I've got information:
`Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]: ***Failed to load component "609c73ff-c257-4730-a497-ba49346f3490" (ConflictCheckWebPart). Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/apps/ClientSideAssets/02e6e9a7-85b6-436c-bcf1-ca7e9e75c1b9/test-conflictcheckwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'ConflictCheckWebPartStrings' in component '609c73ff-c257-4730-a497-ba49346f3490' (ConflictCheckWebPart). There was a problem in the server. ***INNERERROR: ***Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/apps/ClientSideAssets/02e6e9a7-85b6-436c-bcf1-ca7e9e75c1b9/test-conflictcheckwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'ConflictCheckWebPartStrings' in component '609c73ff-c257-4730-a497-ba49346f3490' (ConflictCheckWebPart). There was a problem in the server. ***CALLSTACK: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-25.007/sp-pages-assembly_en-us_90c92a4c8b183a618b34edd6f0cb7536.js:320:15770) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-25.007/sp-pages-assembly_en-us_90c92a4c8b183a618b34edd6f0cb7536.js:1077:22396) at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-25.007/sp-pages-assembly_en-us_90c92a4c8b183a618b34edd6f0cb7536.js:1077:14508) at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-25.007/sp-pages-assembly_en-us_90c92a4c8b183a618b34edd6f0cb7536.js:1077:10707) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-05-25.007/sp-pages-assembly_en-us_90c92a4c8b183a618b34edd6f0cb7536.js:1077:64480
`

When I deploy app using azure cdn - everything works fine.
I've tried to access https://xxx.sharepoint.com/sites/apps/AppCatalog/ClientSideAssets and I found that this library not exists - and I think this is an issue with loading my webpart.

What is the best practice in this case when SharePointShell telling that */CLIENTSIDEASSETS are exists but I cannot access it?

**Comment by vman** [comment]
The path to the ClientSideAssets should be `https://xxx.sharepoint.com/sites/apps/ClientSideAssets ` (without the AppCatalog bit) so I don't think that's your problem.

A similar issue was reported here: https://github.com/SharePoint/sp-dev-docs/issues/1353 you can check if any of the suggestions works for you.

**Comment by gosiaborzecka** [comment]
Thanks for update @vman. I double check and on your url I found files. I thought that this is an issue as on another tenant when I go into my url - there where I can my files. 
I'll look into #1353 issue.
