### ISSUE TITLE
Issue upgrading to SPFx 1.5.0

### ISSUE THREAD

**Issue by petkir** [SharePoint/sp-dev-docs#1969]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

after package upgrade to 1.5.0 i got errors like this
`Error - typescript - node_modules/@microsoft/sp-application-base/dist/index-internal.d.ts(xx,yy): error TS2307: Cannot find module '@ms/odsp-utilities-bundle'.
`
`
Error - typescript - node_modules/@microsoft/sp-extension-base/dist/index-internal.d.ts(59,31): error TS2304: Cannot find name 'GraphHttpClient'.
Error - typescript - node_modules/@microsoft/sp-http/dist/index-internal.d.ts(180,22): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
Error - typescript - node_modules/@microsoft/sp-page-context/dist/index-internal.d.ts(134,23): error TS2304: Cannot find name 'AzureActiveDirectoryInfo'.
Error - typescript - node_modules/@microsoft/sp-page-context/dist/index-internal.d.ts(536,21): error TS2304: Cannot find name 'O365GroupAssociation'.
`

i changed my **tsconfig.json** file to this, and it worked as expected 
`{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection"
    ]
  }
}
`

>Hope this helps more

**Comment by napkin92** [comment]
Had the same problem and compilation works again. Thanks!

**Comment by havivi** [comment]
Works! Thx!

**Comment by bastianjohn** [comment]
Helped me a lot! Thanks!

**Comment by andrewconnell** [comment]
Closing as issue appears resolved. If not, please let us know with additional details so we can reopen.
