### ISSUE TITLE
fabric.components.min.css no longer included by default?

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#197]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Just loaded up my reactjs based webpart which are using the office ui fabric components. Previously it rendered fine, but now the components css is no longer loaded (happens on workbench and classic pages)

Do we need to bundle/load this ourselves, or a bug?

**Comment by manishgarg1** [comment]
Fabric component css file will no longer be loaded with the framework. The reason is that the Fabric compoent css was for the older components. The new components (https://github.com/OfficeDev/office-ui-fabric-react) are loaded by default with the Sharepoint framework.

**Comment by wobba** [comment]
Ok, so by adding/updating the office ui fabric package via npm it should "just work"? Any pointer to which version I need to verify it all working correctly?

**Comment by manishgarg1** [comment]
Can you please point me which Fabric react components you are using in your webpart?

**Comment by wobba** [comment]
From my package.json:
`    "office-ui-fabric": "^2.6.1",
    "office-ui-fabric-react": "^0.52.2",`

And config.json lists office-ui-fabric-react as an external. No mention of office-ui-fabric itself.

Let me know if you need more information.

**Comment by manishgarg1** [comment]
Hi Michael, I am still a bit confused. I would like to know what styles are you using from the fabric.component.css. If you are just loading the inbuilt react web part, could you re-install the @Microsoft/generator-sharepoint and get the React web part again. At that point, it should just work. Please let me know if it is still giving a problem.

**Comment by wobba** [comment]
Let's close this.. and I'll re-file if I see it again with drop 5 testing :)
