### ISSUE TITLE
I had a few issues trying to follow this

### ISSUE THREAD

**Issue by nnennaude** [SharePoint/sp-dev-docs#1970]
To get it to work I had to 
1) install gulp locally:
npm install gulp --save-dev

2) fix missing dependencies: 

npm install --save-dev

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You shouldn't have to do this if follow the instructions to install gulp globally. 

Feel free to reopen this issue if it's closed prematurely, but you do not need to install gulp locally for SPFx. It's added as part of the scaffolding when you create a new project using the SPFx generator
