### ISSUE TITLE
WebPack  issue after upgrading to SPFX 1.5

### ISSUE THREAD

**Issue by bva999** [SharePoint/sp-dev-docs#1972]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

After upgrading  SPFX to version 1.5,  when I build my solution I get next webpack **error:** 

<--- Last few GCs --->

[4544:000001DA67907F70]   112554 ms: Mark-sweep 1418.3 (1655.1) -> 1418.2 (1655.1) MB, 451.4 / 0.0 ms  allocation failure
scavenge might not succeed
[4544:000001DA67907F70]   113014 ms: Mark-sweep 1418.2 (1655.1) -> 1418.3 (1632.1) MB, 459.5 / 0.0 ms  last resort GC in old space requested
[4544:000001DA67907F70]   113489 ms: Mark-sweep 1418.3 (1632.1) -> 1418.2 (1623.6) MB, 474.9 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000016ACE125EE1 <JSObject>
    1: DoJoin(aka DoJoin) [native array.js:~95] [pc=0000012CC5DEB1B9](this=0000001EDBB02311 <undefined>,p=000001164777FC69 <JSArray[376]>,q,q=376,E=0000001EDBB023B1 <true>,A=0000016ACE16F121 <String[1]:  >,z=0000001EDBB02421 <false>)
    2: Join(aka Join) [native array.js:~120] [pc=0000012CC565ACE9](this=0000001EDBB02311 <undefined>,p=000001164777FC69 <JSArray[376]>,q=37376,A=0000016ACE16F121 <Str...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::compiler::Pipeline::AllocateRegistersForTesting
 6: 0000012CC55047A1_

#### Steps to Reproduce
1) Update `@microsoft/sharepoint-generator`  `npm update @microsoft/sharepoint-generator -g`
2) Delete node_modules folder from my solution
3) Change package.json , replace all 1.4.1 versions to 1.5.0 
4) Run npm install 
5) Run gulp serve --nobrowser
6) Get an error 

If I downgrade to 1.4.1  the error disappears! 

![error](https://user-images.githubusercontent.com/12149939/41145972-d97a586e-6b12-11e8-95bc-b7872ce9a08e.PNG)

**Comment by guillaume-kizilian** [comment]
Seems there is a new dependency :
     @"types/es6-promise": "0.0.33"
And this one changed a little
     @"types/webpack-env": "1.13.1"

And tsconfig.json also changed.

Not tested.

**Comment by bva999** [comment]
Perhaps, there is a guide how to update the solution to a version 1.5 ?

**Comment by patmill** [comment]
I'll update the release notes to mention the changes in tsconfig.  @bva999 - can you confirm that updating the package.json file and making sure that the types in your tsconfig file contain
  
  "types": [
      "es6-promise",
      "webpack-env"
    ],

**Comment by bva999** [comment]
Unfortunately, it doesn't helps me....

**Comment by andrewconnell** [comment]
Since this issue is fairly dated & we're now at SPFx v1.7.1, can you please verify if the issue is still present when upgrading to latest and if so, provide additional details with your config to troubleshoot?

**Comment by bva999** [comment]
I upgraded to 1.7.1 and I had not any problem. Thank you.

**Comment by jpalo** [comment]
Upgraded from 1.7.1 to 1.8.0 and started seeing this in my project. Occurs every 3-4th time I modify file & save, which triggers build.
