### ISSUE TITLE
Unable to add an array of tasks using the addBuildTasks function

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#199]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

In sync with the specification, passing an array of tasks to the `addBuildTasks` function, should add all of them to the `additionalBuildTasks` array.
#### Observed Behavior

After passing an array of tasks as an argument of the `addBuildTasks` function, the `additionalBuildTasks` remains empty.
#### Steps to Reproduce

``` js
const build = require('@microsoft/sp-build-web');
var task1 = { execute: (config) => { return Promise.resolve(); }, name: 'task1' };
var task2 = { execute: (config) => { return Promise.resolve(); }, name: 'task2' };
build.addBuildTasks([setBaseUrl, copytemplates]);
// none of the tasks is being executed when running gulp build
```

**Comment by iclanton** [comment]
@nickpape-msft Believes he knows what the issue is.

**Comment by nickpape-msft** [comment]
The [gulp-core-build](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build/README.md#microsoftgulp-core-build) system uses the [IExecutable](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build/src/IExecutable.ts) interface when registering tasks. This interface requires the `isEnabled: () => boolean` function to be implemented. 

Advice is to use the [subTask(name, fn)](https://github.com/Microsoft/web-build-tools/tree/master/gulp-core-build#subtaskname-string-fn-icustomgulptask) function.

Example:
```typescript
var task1 = build.subTask('task1', (gulp, buildConfig, done) => {
  return Promise.resolve(); /* can be Promise<Object> | NodeJS.ReadWriteStream | void; */
}

build.addBuildTasks([task1]);
```

**Comment by waldekmastykarz** [comment]
Unfortunately the error is still there:

If you do this:

```js
'use strict';

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');

var task1 = build.subTask('task1', (gulp, buildConfig, done) => {
  return Promise.resolve(); /* can be Promise<Object> | NodeJS.ReadWriteStream | void; */
});

build.addBuildTasks([task1]);
build.initialize(gulp);
```

You won't see task1 mentioned in the output of `gulp build`.

If you use instead:

```js
'use strict';

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');

var task1 = build.subTask('task1', (gulp, buildConfig, done) => {
  return Promise.resolve(); /* can be Promise<Object> | NodeJS.ReadWriteStream | void; */
});

build.addBuildTasks(task1);
build.initialize(gulp);
```

you will see task1 in the output.

**Comment by iclanton** [comment]
This isn't reproducing anymore with the latest version of gulp-core-build, so it looks like it was fixed.
