### ISSUE TITLE
Unable to add multiple different components to the same project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#1991]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Be able to add multiple different components (web parts, extensions) to the same project.

#### Observed Behavior

When you run the Yeoman generator to add another component, you are not being prompted for the component type. Instead, the generator directly prompts you for the component name assuming the type of the initially selected component.

#### Steps to Reproduce

- scaffold new project using generator 1.5.0
- use the latest set of packages (SPO only)
- create web part with default values
- run the generator to add another component
- you are prompted directly to provide the web part name instead of choosing first the type of component you want to add

**Comment by VesaJuvonen** [comment]
We will be releasing updated 1.5.1 version early this week with few additional fixes. Sorry for the inconvenience.

**Comment by waldekmastykarz** [comment]
No problem. Great to hear you guys were able to fix it so quickly.

**Comment by patmill** [comment]
This should have been closed a long time ago.
