### ISSUE TITLE
Flat Hierarchy?

### ISSUE THREAD

**Issue by kliemohn** [SharePoint/sp-dev-docs#1993]
By recommending against "too many top-level parent portal site collections" this seems to be arguing against a flat hierarchy, but everything I am hearing is arguing for a flat hierarchy.  Can you reconcile this for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8babdc28-eedd-9d34-076d-1a7bf3aed73a
* Version Independent ID: 0e50151b-2d9c-1838-7c2b-6cc01723222c
* Content: [Information architecture guidance for SharePoint Online portals](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-information-architecture)
* Content Source: [docs/solution-guidance/portal-information-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-information-architecture.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by dremillard** [comment]
I was wondering the same thing.

**Comment by ichkoj** [comment]
Mee to...

**Comment by lschoenaers** [comment]
You can read about it here: https://docs.microsoft.com/en-us/sharepoint/information-architecture-modern-experience
