### ISSUE TITLE
"Add a Page" opens dialog

### ISSUE THREAD

**Issue by nnennaude** [SharePoint/sp-dev-docs#1995]
Selecting "Add a page" makes a dialog display where it asks for a "New page name". It does not take me to workbench as is shown in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
In the tutorial, you are redirected to a new modern page, not to the workbench. If you are being shown a dialog when you click "add a page", that means that you are using old experience and classic pages. This will have a completely different scenario. Would recommend on creating a new modern team site and use that for testing the web part in the SharePoint Online site, so that the experience is guaranteed to be same as shown in the video and in the written tutorial.

**Comment by nnennaude** [comment]
I am using Office 360, so I thought that everything was automatically upgraded. I have been creating new sites and I still get the same result. How do I make sure I create a "new modern team site"?

**Comment by VesaJuvonen** [comment]
This really depends on HOW you are creating those site collections. If you go to the SharePoint Home (select SharePoint from the launch menu) and then create a new site from there, you would be creating a new modern team site - https://support.office.com/en-us/article/create-a-team-site-in-sharepoint-online-ef10c1e7-15f3-42a3-98aa-b5972711777d

**Comment by nnennaude** [comment]
Okay thank you. You've been very helpful. It's confusing because the directions start out telling you to add the app to your " developer site collection."- which was created earlier according to the "Getting Started" instructions via the SharePoint Admin Center. Then it says to add the app to the same site where the app was installed- which would have been the developer site which is not a modern site.
