### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by HeToC** [SharePoint/sp-dev-docs#1996]
Why create your own framework (itd be buggy as hell i guess) instead of using RX, Redux, etc ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79444829-20bc-3b07-8820-29b55798761a
* Version Independent ID: 546cff82-d871-917e-10ba-55df6f18e5eb
* Content: [Connect SharePoint Framework components using dynamic data](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data)
* Content Source: [docs/spfx/dynamic-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/dynamic-data.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
The actual framework is needed as it will be the baseline also for the upcoming UI layer, which will let end-users to associate web parts between each other. Certainly, the underlying connections could have been using Rx, Redux etc... but the framework and design are there to enable 1st party experience for end-users.
