### ISSUE TITLE
sharepoint generator is updated to 1.5.0, but generate package.json still using 1.1.0

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#1998]
sharepoint generator is updated to 1.5.0, but generate package.json still using 1.1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2345258-f135-178a-a5af-9705ebafa081
* Version Independent ID: 90ee54a0-1409-6f4d-5018-c9f3e26e46ef
* Content: [Scaffold projects by using Yeoman SharePoint generator](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator)
* Content Source: [docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by peterremote1980** [comment]
i understand now, it probably a bug, if i choose "sharepoint online" instead of "on-premies', it give me 1.5.0, please followup

**Comment by VesaJuvonen** [comment]
Not a bug, as designed. If you chose on-premises, packages will reference SharePoint Framework v1.1 as that's the supported version in SharePoint 2016 Feature Pack 2. Solutions using 1.5 version would not work in the on-premises as there are also server-side dependencies on the packages.
