### ISSUE TITLE
GuidHelpers returns string object instead of Guid objects

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#200]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When creating a Guid using `GuidHelpers` a `Guid` object should be returned instead of a `string`.

#### Observed Behavior
The `GuidHelpers` class returns `string` objects for its methods.

#### Steps to Reproduce
This is how you create a Guid today:
```
var g: string = GuidHelpers.generateGuid();
```
And to create it in a Guid object style you need to do:;
```
var g: Guid = new Guid(GuidHelpers.generateGuid());
```

**Comment by pgonzal** [comment]
GuidHelpers is marked as **@internal**. It is not intended to be used in your code.  Use the [Guid](https://sharepoint.github.io/classes/_sp_client_base_.guid.html) class instead.  GuidHelpers  will be removed soon.
