### ISSUE TITLE
React 16 supported in plusbeta? or on regular release

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2000]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
I create a new project without plusbeta and the package.json still references to React Version 15.6.2 and not 16.x.x

Does support mean you can use it but have to upgrade manually or is it just available in plusbeta?
What possible implication may I expect when the Online Workbench for example only supports an older version?

**Comment by VesaJuvonen** [comment]
React 16 support is planned to come out in SharePoint Framework 1.6. It is not currently available from either of the available versions. We will need to do some server-side dependency updates to make this work for 1st party components and this is now planned to be in 1.6.
