### ISSUE TITLE
Nuget package OfficeDevPnP.Core doesn't exist anymore

### ISSUE THREAD

**Issue by repton-infinity** [SharePoint/sp-dev-docs#2003]
The docs refer to a nuget package "OfficeDevPnP.Core" but that package doesn't exist. I believe it should be SharePointPnPCoreOnline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d6b91d-fc0a-b7af-bd9b-4f24b1686209
* Version Independent ID: 70f46d41-582f-9ec7-7149-878a7f321068
* Content: [Create remote timer jobs in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/create-remote-timer-jobs-in-sharepoint)
* Content Source: [docs/solution-guidance/create-remote-timer-jobs-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/create-remote-timer-jobs-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Michaelvsk** [comment]
It seems that the Nuget package has been renamed. [SharePointPnPCoreOnline](https://www.nuget.org/packages/SharePointPnPCoreOnline/) has all the methods which are part of this [Project at GitHub](https://github.com/SharePoint/PnP-Sites-Core/tree/master/Core). And the docs of the project still link to OfficeDevPnP.Core, too.

And these seem to be the On-Premise versions:
- https://www.nuget.org/packages/SharePointPnPCore2013/
- https://www.nuget.org/packages/SharePointPnPCore2016/
