### ISSUE TITLE
Documentation for Description property seems to be incorrect

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2008]
_From @tomcastiglia on May 14, 2018 7:40_

In the documentation for TeamSiteCollectionCreationInformation it states that the "Description" property is:
**_> The Guid of the site design to be used. If specified will override the SiteDesign property_**

However, I believe this property is used only to set the site's description, correct?  So this documentation appears to be incorrect here.  

That being said, I really am looking for a way to set the SiteDesign for new team sites to use a custom SiteDesign that is already deployed to my tenant.  So I was actually hoping that TeamSiteCollectionCreationInformation would allow me to specify a SiteDesign (by name or ID) as we can for Communication sites.

_Copied from original issue: SharePoint/PnP-Guidance#197_

**Comment by erwinvanhunen** [comment]
Thank you @tomcastiglia. I fixed it through PR https://github.com/SharePoint/PnP-Sites-Core/pull/1815 and it will be available in the next monthly release.
