### ISSUE TITLE
Guid.isValid and GuidHelpers.isValid does not validate the same

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#201]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When using Guid.isValid and GuidHelpers.isValid on a Guid string I expect the to validate the same

#### Observed Behavior
```
Guid.isValid('60273aae-b14d-4301-9651-cb10fc22a261') //returns true
GuidHelpers.isValid('60273aae-b14d-4301-9651-cb10fc22a261') //returns true

Guid.isValid('{60273aae-b14d-4301-9651-cb10fc22a261}') //returns true
GuidHelpers.isValid('{60273aae-b14d-4301-9651-cb10fc22a261}') //returns false
```
#### Steps to Reproduce
See above

**Comment by pgonzal** [comment]
GuidHelpers is marked as **@internal**. It is not intended to be used in your code.  Use the [Guid](https://sharepoint.github.io/classes/_sp_client_base_.guid.html) class instead.  GuidHelpers  will be removed soon.
