### ISSUE TITLE
Object doesn't support property or method 'setAttribute' IE 11

### ISSUE THREAD

**Issue by vocaris** [SharePoint/sp-dev-docs#2010]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We are using der AadHttpClient to read user data from the AzureAD. After a while we were able to use the component as described in the issue [#1810](https://github.com/SharePoint/sp-dev-docs/issues/1810) but till today (today the first one reported the new error) we get an error in Internet explorer 11:
`TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "setAttribute" nicht`
in english (own translation:
`TypeError: The objekt does not support the property or method "setAttribute"`

The error did not occur in Forefox, Chrome and Edge.

#### Steps to Reproduce

We extracted the AzureAD related functions into a seperate TypeScript-Class. The error occurs inside the following method:

> private  _singleSearchCallWithAad(url:string):Promise<any>{
    return new Promise<any>((resolve: (result: any) => void, reject: (error: any) => void) : void => {
console.log("url " + url)
      this._aadClient
        .get(url, AadHttpClient.configurations.v1)
        .then(response => {
console.log("success")
          resolve(response.json());
        })
        .catch(error => {
console.log("error")
          console.error(error);
        });
    });
  }

The console.log(url) works fine but after that we get the console.log(error).

Please help us it's a very important functionality for us.

**Comment by Nasicus** [comment]
We have the very same problem.
IE 11 not working.
Safari not working.

Worked perfectly before.

**Comment by ItsANameToo** [comment]
I'm also experiencing this issue. Would be great if someone could take a look into it

**Comment by pToker** [comment]
Same here...
Leaving comment to be updated when a fix is provided or workaround suggested.

**Comment by Nasicus** [comment]
@VesaJuvonen  any news on this? Is this at least known to the devs?

**Comment by VesaJuvonen** [comment]
The root cause of this issue is in the Adal.js side and we have provided that team now the instructions to get this resolved. We in SharePoint engineering have also done the needed fix for our used adal.js implementation, which will be rolling out to the production within upcoming few weeks as it's server side fix which is getting pushed out to address this as a hotfix. Let's keep this open until we can confirm the issue is properly resolved.

**Comment by Nasicus** [comment]
Thanks for the explanation! I will give feedback once it works.

**Comment by patmill** [comment]
sorry - this should have been closed a long time ago.
