### ISSUE TITLE
Cannot find module "@ms/sp-telemetry" on SPFx unittest

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/sp-dev-docs#2011]

**Comment by VesaJuvonen** [comment]
Unfortunately not enough information for repro. We would need to understand used versions, what unit test framework is used etc. Closing as not actionable for our side.

**Comment by veeramanx** [comment]
I am writing unit test for SPFx web part. when i run gulp test command i am getting the following error "Cannot find module """. i am using '' in the react component.

I have the following versions
"dependencies": {
"": "^1.5.0",
"": "^1.5.0",
"": "^1.5.0",
"": "^1.5.0",
"": "^1.5.0",
"": "^1.5.0",
"": "~1.4.1",
"": "^1.5.0",

"devDependencies": {
"": "^1.5.0",
"": "^1.5.0",
"": "^1.5.0",
"": ">=3.4.34 <3.6.0",
"": "^2.8.12",
"": ">=2.2.33 <2.6.0",
"": "^1.16.36",

Please do let me know if any additional information required.

**Comment by devinprejean** [comment]
basically same problem as this. Still not fixed after nearly a year. https://github.com/SharePoint/sp-dev-docs/issues/526
