### ISSUE TITLE
Store and/or licensing mechanism for SPFx WebParts?

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2013]
_From @spplante on June 6, 2018 17:10_

## Category

- [x] Question
- [ ] Bug
- [ ] Enhancement

## Question

Is there any kind of road-map in regards to a licensing mechanism for validating licenses of custom SPFx WebParts kinda like the old app/add-in model? Is there any plans for a "store" where consumers could download/buy custom SPFx WebParts just like the current add-in store?

Creating custom WebParts and solutions for free is great, but as a developer, it would be really interesting to be able to get rewarded for our time/efforts, and SPFx being 100% client side, I just don't see an effective way to have a secure licensing mechanism unless there is some built-in server side logic involved.

I could for example have my own azure function HTTP endpoint responsible for validating the license of the caller, and then I could make sure my WebPart calls the said endpoint before rendering anything, but this could easily be bypassed by commenting the client side code responsible for calling the azure endpoint...I don't see how we could securely do this without having some backend built-in into SharePoint.

Anything planned for this? Maybe @VesaJuvonen has some insider info about this? 👍  

Thanks!

_Copied from original issue: SharePoint/sp-dev-fx-webparts#527_

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue and NOT related on any sample in this repository, moving to the sp-dev-docs issue list at http://aka.ms/spdev-issues.

**Comment by seanix99** [comment]
I'm also interested.

**Comment by DominicArchual** [comment]
Any update on this?  This seems like a fundamental feature.  For instance, for SharePoint Add-Ins, you can verify the license as described in this doc:  https://docs.microsoft.com/en-us/office/dev/store/add-license-checks-to-office-and-sharepoint-add-ins

Is there a similar mechanism or recommended approach for SPFx Apps?

**Comment by spplante** [comment]
Anyone with some information on this? I am not specifically asking for a solution, I would just like to know if it's on the road map or not.

**Comment by DominicArchual** [comment]
@spplante It looks like there is a feature suggestion which they've responded to and plan to implement; however, there doesn't seem to be a publicly known timeframe.  If someone from Microsoft could share a timeframe with us that would be fantastic!  

Add support of SharePoint Framework solution packages to the AppSource Store - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33426859-add-support-of-sharepoint-framework-solution-packa

**Comment by shahramvafadar** [comment]
Any update?

**Comment by spplante** [comment]
They [recently announced](https://techcommunity.microsoft.com/t5/Teams-Developer/Charging-Money-for-Apps-in-the-Teams-App-Store-Announced-at/td-p/548702) that we will be able to monetize apps for Microsoft Teams through a new Partners portal.

It is not mentioning SPFx anywhere, but since SPFx apps can be packaged for Teams, I have hope they might have figured something out in order to sell SPFx components through the same monetizing model. We will have to wait to see!

**Comment by spplante** [comment]
@VesaJuvonen just added the following "Working on it" notice this [uservoice ](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33426859-add-support-of-sharepoint-framework-solution-packa?tracking_code=f6ea1648436b46f94592232c99d67a34#{toggle_previous_statuses}):

> Just to update the status. We are actively now working on having support for the SharePoint Framework in our store patterns. Can’t provide an exact ETA for this yet, but it’s being actively developed and worked on.

As I wrote in the uservoice's comments, I am curious on whether  it will be part of the newly announced "Microsoft Partners Center" update which will offer a new monetizing model for Teams apps or if this is going straight in the existing AppSource offering, nonetheless this is still great news 👍

**Comment by andrewconnell** [comment]
As this is more of a uservoice topic, I tagged it as such which will close this issue. Uservoice is where feature requests/changes and that's the place engineering follows.
