### ISSUE TITLE
developer tenant  Public CDN issue 

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2014]
_From @krmoanh on May 26, 2018 8:15_

Hi, I have problem with CDN in my developer tenant. I made webpart and I already enable the cdn public and I check everything its look fine. but when I save the sppkg to sharepoint site appcatalog and then in the team site I try to use the webpart its give me error about loading from public cdn. and the when I try same way but different tenant I mean not my own developer tenant and it work fine, no any issue. I really don't know why its just only in my developer tenant. this issue also recently happen with some developers . my problem same this https://github.com/SharePoint/sp-dev-docs/issues/1353 

_Copied from original issue: SharePoint/sp-dev-fx-webparts#519_

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue and NOT related on any sample in this repository, moving to the sp-dev-docs issue list at http://aka.ms/spdev-issues.

**Comment by andrewconnell** [comment]
Looks like this issue is fixed... I’m unable to dupe it and the referenced issue has been closed. Closing but can reopen if necessary...
