### ISSUE TITLE
Office 365 Public CDN not working

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2015]
_From @harshdamaniahd on April 25, 2018 10:25_

I have a site  tenant.sharepoint.com
In this site in "SiteAssets" Library , I have created a folder called webpart where I am hosting all files from SPFX temp folder
here are my cdn defined.
Get-SPOPublicCDNOrigins
![image](https://user-images.githubusercontent.com/11780473/39240151-a6f3cfea-48a0-11e8-8ac3-3c05c93eca05.png)

This is my cdn path : "cdnBasePath": "https://publiccdn.sharepointonline.com/tenantname.sharepoint.com/SiteAssets/Webpart/"

When i build and upload my webpart , I see the it is not able to get these files.
Can you pls tell me what I am missing

_Copied from original issue: SharePoint/sp-dev-fx-webparts#491_

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 25, 2018 10:39_

Is there any reason why you are setting it all up manually, rather than having the SharePoint Framework package the scripts inside the .sppkg file and deploy them to the Office 365 CDN for you? This is by the way the default behavior, if you're using SharePoint Framework v1.4.1. Which version are you using?

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on April 25, 2018 12:42_

Yes I am using v1. 4.1.. No specific reason.I was trying the approach of making document library as cdn

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 25, 2018 13:29_

The challenge with doing it manually is, that in case the admin would turn off the Office 365 CDN, your web part wouldn't work anymore. When doing it automatically, SharePoint will automatically fallback to the document library URL when the CDN is disabled.

You could try to see if you could achieve the same result, by pointing to the document library URL rather than the CDN URL. Still, if you're deploying files to SharePoint, you could better follow the default behavior and have the SPFx toolchain include them in the package and have SharePoint deploy them automatically for you.

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 25, 2018 18:20_

You're using the Office 365 Public CDN URL: `https://publiccdn.sharepointonline.com/...`. Could you try using `https://tenantname.sharepoint.com/SiteAssets/Webpart/` instead?

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on April 26, 2018 4:1_

Normal document library works..But i was trying to make document library as cdn and it didnot work
I followed this article 
https://blog.mastykarz.nl/publish-sharepoint-framework-client-side-web-parts-office-365-public-cdn/

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 26, 2018 6:48_

@harshdamaniahd the steps outlined in my article were necessary in the past, when SharePoint didn't offer native support for deploying assets to the Office 365 CDN. Today however it does, so there is no true need to set it all up manually anymore.

Still, a manually setup CDN should work. Can you verify that your files stored in the webpart folder are accessible through the public CDN using the `publiccdn.ashx` handler as described in my article?

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 27, 2018 17:29_

What if you set `https://tenantname.sharepoint.com/SiteAssets/Webpart/` as the base URL in your project: can you see SharePoint loading your web part files? If so, does it use the URL you specified or does it automatically replace it with the CDN URL?

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on April 28, 2018 14:4_

Yes if i use https://tenantname.sharepoint.com/SiteAssets/Webpart/ as my baseurl , it loads file from the baseurl location.
It does not use cdn url .
Also i checked  in postman and tried to fetch file from cdn it gives me the error
![image](https://user-images.githubusercontent.com/11780473/39397318-00e9a8c2-4b1b-11e8-9ac9-f0e66ac4438c.png)

**Comment by VesaJuvonen** [comment]
_From @waldekmastykarz on April 28, 2018 17:47_

This seems to be similar to https://github.com/SharePoint/sp-dev-docs/issues/1731

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on April 29, 2018 3:43_

I guess there is no solution as of now, the issue is tenant specific.

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on May 17, 2018 5:48_

In my new tenant when i try to access json file from document library , i get the below error
![image](https://user-images.githubusercontent.com/11780473/40158763-d79c104c-59c3-11e8-87d3-b59c83821f18.png)


CDN is enabled
![image](https://user-images.githubusercontent.com/11780473/40158784-f6c1e55a-59c3-11e8-8546-9d6fdfca7451.png)

**Comment by VesaJuvonen** [comment]
_From @hbgeorgian on May 17, 2018 9:14_

The CDN is restricted to accept requests coming from SharePoint.com only. It won't work from postman unless you tweak the origin

**Comment by VesaJuvonen** [comment]
_From @harshdamaniahd on May 17, 2018 16:4_

This is working for files with extension css,txt
![image](https://user-images.githubusercontent.com/11780473/40189336-d2853c5e-5a19-11e8-98ff-cac4ff902f2e.png)


but not with json it gives error "403 FORBIDDEN"

**Comment by VesaJuvonen** [comment]
Since this seems to be a generic issue and NOT related on any sample in this repository, moving to the sp-dev-docs issue list at http://aka.ms/spdev-issues.

**Comment by OliverZeiser** [comment]
We are also seeing a tenant where the public CDN for ClientSideAssets is not working. Looking at the Developer Toolbar, the response from the CDN is 406 for GET and 405 for HEAD. Without CDN enabled, everything is working fine. Disabling CDN and enabling it again does not help. Removing Origins and adding them back again, does not help either... The same spfx package on other tenants works just fine..

**Comment by OliverZeiser** [comment]
To add some more info... On the Tenant where it is not working, the Content-Type is specified as application/json for javascript files, and on tenants where the cdn is working, the Content-Type is specified correctly as  application/javascript

**Comment by andrewconnell** [comment]
This CDN issue has shown up a few times in different issues (#864, #1731, #3238)... consolidating to the most recent one with lots of detail, #3238, as this issue hasn't had much activity and a fix in late 2018 resolved issue for many reports.
