### ISSUE TITLE
Cannot find module "@ms/sp-telemetry" on SPFx unittest

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/sp-dev-docs#2019]
I am writing unit test for SPFx web part. when i run gulp test command i am getting the following error Cannot find module `"@ms/sp-telemetry"`. i am using '`@microsoft/sp-http'` in the react component.

I have the following versions
```
 "dependencies": {
 "@microsoft/decorators": "^1.5.0",
    "@microsoft/sp-application-base": "^1.5.0",
    "@microsoft/sp-client-preview": "^1.5.0",
    "@microsoft/sp-core-library": "^1.5.0",
    "@microsoft/sp-http": "^1.5.0",
    "@microsoft/sp-lodash-subset": "^1.5.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.1",
    "@microsoft/sp-webpart-base": "^1.5.0",

```

```
"devDependencies": {
    "@microsoft/sp-build-web": "^1.5.0",
    "@microsoft/sp-module-interfaces": "^1.5.0",
    "@microsoft/sp-webpart-workbench": "^1.5.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/enzyme": "^2.8.12",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "@types/sinon": "^1.16.36",

```
Please do let me know if any additional information required. 
Thanks,

**Comment by muradaliyev** [comment]
Which node.js version you are using? Can you try with  8.11.2?

**Comment by veeramanx** [comment]
Hi,
I am using Node version:v8.9.4 . let me try with 8.11.2 and keep you updated.

**Comment by veeramanx** [comment]
@muradaliyev that didn't help.

**Comment by muradaliyev** [comment]
Sorry, have nothing to add. It's now tagged as bug by Vesa

**Comment by pmeripe** [comment]
I used this import { SPHttpClient } from '@microsoft/sp-http'; on no-javascript web part and it worked.

Error for me: import { SPHttpClient } from '@microsoft/sp-http/lib/spHttpClient/SPHttpClient';

**Comment by devinprejean** [comment]
similar issues about this in the issues list for a while now. https://github.com/SharePoint/sp-dev-docs/issues/526 is one

**Comment by devinprejean** [comment]
I had the same issue but i found a fix!
Seems I was referencing imports from the same folder, however one group was listed in my index, the other was referenced all the way. For example:

import { ModuleName } From "./provider/module
import { SecondModule } from "./provider" 
once i changed the second module to reference all the way instead of using the index.ts file inside the folder my issue went away.
Hope this helps someone.
