### ISSUE TITLE
Is there a way to deploy the pages with Site Designs?

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#2022]
Is there a way to deploy pages with site design? 
No where it was mentioned the limitations of site designs as not possible to deploy pages, not possible to deploy look up columns, not possible to add web parts to the pages etc.

Is there any documentation available for the limitations of the site design?

- [X] Question

**Comment by VesaJuvonen** [comment]
This is not currently supported, so you'd need to do this with extension hosted in Azure and then using remote provisioning techniques, like PnP provisioning engine.
