### ISSUE TITLE
Upload fails empty alert. 

### ISSUE THREAD

**Issue by cyberjetx** [SharePoint/sp-dev-docs#2029]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Upload a document in the same domain.

#### Observed Behavior

Using the code provided as is with the addition of setting the the following vars and adding the console.log below:

    function uploadFile() {

    appWebUrl = "https://joetest.com/sites/crdev/fred/rot/applications/AMF";
    hostWebUrl = "https://joetest.com/sites/crdev/fred/rot";

and 

    console.log(appWebUrl, serverRelativeUrlToFolder, fileName, hostWebUrl);

        // Construct the endpoint.
        var fileCollectionEndpoint = String.format(

When running the code there are no errors in the console. There is an empty alert message box. And there is no uploaded file.  

#### Steps to Reproduce
*SP2013 on prem

- Create a new web part page in a doclib
- Add a CEWP
- link CEWP to the html file containing

-    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>Testing Only</title>
        <script  type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/JoeTest.js"></script>
    </head>
    <body>
    
    <input id="getFile" type="file"/><br />
    <input id="displayName" type="text" value="ABC123" /><br />
    <input id="addFileButton" type="button" value="Upload" onclick="uploadFile()"/>
    
    </body>
    </html>

- Run code selecting a txt file and click upload
- Observe Empty "Message from Website" alert
- Observe no errors in the console/debugger

**Comment by VesaJuvonen** [comment]
@cyberjetx - unless we can build the repro, we can't really act on this issue. Challenge here is that even though you define in the high level what was there, we can't really know exactly how your code is looking. Also, the SharePoint 2013 version might have an impact on this and it's important for testing. We would need more details before we can move forward with this.

**Comment by cyberjetx** [comment]
Could we, perhaps, set up a skype screenshare? The shoulder surf might reveal something to you. 

I don't know how to explain this better and I understand that every environment is different.

**Comment by VesaJuvonen** [comment]
Hi @cyberjetx, we do not, unfortunately, scale for one-to-one Skype calls as there are tens of thousands on hundreds of thousands of SharePoint developers out there. What I'd ask is the actual source code for reproducing this in our environment and also the exact version of the SP2013 server. What CUs or patches has been installed on that environment?

**Comment by VesaJuvonen** [comment]
Just to follow up on this. We would need more details on the exact version which you are using to be able to proceed with the trouble shooting.

**Comment by cyberjetx** [comment]
MicrosoftSharePointTeamServices: 15.0.0.4569 per the response headers.

**Comment by mcmynn83** [comment]
Please engage support for this on premises issue.  This bug is not currently actionable by us.
