### ISSUE TITLE
Web parts for list views and highlighted content are not responsive

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2033]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The web part for document libraries should not show scrollbars because all of the content fits the parent container.
The overlapping columns should get removed, hidden or optimised in some other way dependent of the out web part zone.
Since there no way to hide columns  or show the content differently (except Highlighted Content) in some designs the should be maybe a possibility to make sure only e.g. the title gets displayed.

#### Observed Behavior
By default, a document web part gets provisioned on the right side of the home page of a team site.
The empty document library aligns perfectly with the parent container. 

After files were added to the document library the user gets a scrollbar and the content is to wide to fit the zone.

<img width="510" alt="screen shot 2018-06-13 at 17 34 30" src="https://user-images.githubusercontent.com/5503835/41361748-151b57f8-6f30-11e8-8d74-0a43437fdf2e.png">

The same thing happens when for an example a content highlighted web part gets added to the same zone.

<img width="1514" alt="screen shot 2018-06-13 at 17 27 58" src="https://user-images.githubusercontent.com/5503835/41361837-47524b28-6f30-11e8-91a9-9e82971ea111.png">

#### Steps to Reproduce
Add documents to default document web part on a team site. Embed content highlighter in list form to the web part.

**Comment by VesaJuvonen** [comment]
Thanks, Stefan, this is unfortunately actually by design. Transforming these to be responsive is in the roadmap, but they are not there yet. We do not have a public ETA for these updates.
