### ISSUE TITLE
Api Management not work

### ISSUE THREAD

**Issue by kezack** [SharePoint/sp-dev-docs#2038]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

![image](https://user-images.githubusercontent.com/2874315/41386011-6ffcefac-6f7f-11e8-986b-372e490b28c2.png)

The requested operation is part of an experimental feature that is not supported in the current environment.

I'm first release.

thank you

**Comment by VesaJuvonen** [comment]
"I'm first release." - This capability works ONLY if the whole tenant is in first release / targeted release tenant. Can you double check this setting from the tenant admin UIs.

**Comment by kezack** [comment]
After verification, I was in the targeted user, I went targeted for everyone.

Is there any documentation that explains that ?

**Comment by VesaJuvonen** [comment]
Good that there's a clear explanation for the behavior. Here's more information on the targeted tenant vs user difference - https://support.office.com/en-us/article/set-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47.

**Comment by kezack** [comment]
Thanks for the explanation
