### ISSUE TITLE
SharePoint Framework components - are they really licensed under the Attribution-NonCommercial-NoDerivs 3.0 license?

### ISSUE THREAD

**Issue by mpowney** [SharePoint/sp-dev-docs#2039]
This document explains that SharePoint Framework components license - which presumably includes things like the SPFx gulp build tasks, web part, customizers, etc components.

It links to the [sp-dev-docs LICENSE.md](https://github.com/SharePoint/sp-dev-docs/blob/master/LICENSE.md), which in turn links to the [Creative Commons Attribution-NonCommercial-NoDerivs 3.0 United States](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) license.  This Creative Commons license doesn't permit use for commercial purposes. 

It seems reasonable that documentation published out of the sp-dev-docs can't be used for commercial purposes, but surely SPFx code and libraries published by MSFT for use in SPFx solutions would almost always be for commercial purposes.

Is this document pointing to the right license with regards to SPFx components?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f02c78f-11e2-c9b9-ec7c-191e6e55caa8
* Version Independent ID: 4ed11eb8-a57e-d719-e0e5-95cdaa863b87
* Content: [Overview of the SharePoint Framework (SPFx)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)
* Content Source: [docs/spfx/sharepoint-framework-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-framework-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nickpape** [comment]
The license/EULA is here:

https://unpkg.com/@microsoft/sp-core-library@1.8.0/EULA/Microsoft%20Sharepoint%20Framework%20-%20Standalone%20(free)%20Use%20Terms.docx
