### ISSUE TITLE
Is it possible to adjust the width of the property pane?

### ISSUE THREAD

**Issue by twgolds** [SharePoint/sp-dev-docs#204]
Is it possible to adjust the width of the property pane?  I have a web part with a custom property and I could do with the web part panel being around 25% wider than the default.

#### Category
- [ ] Question

**Comment by vvolodin** [comment]
Also, any particular reason why the workbench main area has the max-width of 924px?

**Comment by getsetbro** [comment]
You could add css to set it's width wider:
`[aria-labelledby="propertyPaneTitleId"] {`
`width: 888px;`
`}`

**Comment by twgolds** [comment]
Thanks.  I added the rule : 

:global {
    [aria-labelledby="propertyPaneTitleId"] {
        width: 888px !important;
    }
}

To the scss file for the web part.  And it does make the panel wider.

Unfortunately though the panel does not close correctly.  It only "closes" by the original size.  Leaving the majority of the panel showing.

What did I do wrong?

**Comment by getsetbro** [comment]
`[class^="spPropertyPaneContainer spPageContentTransition showPane"] [aria-labelledby="propertyPaneTitleId"] {`
`  width: 500px;`
`}`

**Comment by twgolds** [comment]
That's.   That worked a treat.

**Comment by manishgarg1** [comment]
For the following reasons we do not want to allow this. Of course, once achieve this in many ways, but we believe that can cause problems and is not a recommended idea.

Reasons
---------
1. We are designing our modern SharePoint pages with great care. Mobile first, look great and performant. There is a full design team desgining these pages. And they have picked the current width multiple customer reviews. We believe, changing the width can cause many problems (either functional or visual) (in desktop or mobile).

2. For the first party web parts that we have built within Microsoft, we find that the current width has proven to be sufficient.

If you still feel that there is reason for a wider PropertyPane, please explain the need in greater detail, possibly with snapshots and re-activate the issue.

Hope you understand our reasoning.
