### ISSUE TITLE
Looking for guidelines on how to avoid security/deprecated warnings while using Yeoman template

### ISSUE THREAD

**Issue by sprj-git** [SharePoint/sp-dev-docs#2042]
Hi Team,

First of all a big THANK YOU for the awesome work!!!  

I'm looking for guidance on how to avoid the security vulnerability/deprecated issues of a SPFx web part. 
I'm following the exact steps to create a hello world web part as per instructions (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) & it works fine. 

But it also throws few security vulnerability warnings on few packages (during npm install). One of the security vulnerability is related to gulp js and when I upgrade it's package to latest version (ex: gulp 4.0.0), the gulp tasks are failing. Do we have any specific guidelines on how to avoid these security issues while using Yeoman template to create a SPFx web part?

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
You don't... it's really on the responsibility of the package owners who are triggering these security vulnerabilities. 

Specifically, to the point you called out in your issue, Gulp v4 is not officially released... jumping to v4 is a bug jump as there are breaking changes from 3.x as mentioned here: https://github.com/gulpjs/gulp/issues/1486 ... disappointing this issue hasn't progressed...

Generally, for dependencies I ignore all those warnings... but the *"good open source citizen"* in me should really head over to those projects, find the issue, fix it and submit a PR.

**Comment by VesaJuvonen** [comment]
Nothing that much to add on top of @andrewconnell. This is an unfortunate side-effect of the open-source world and we are trying to minimize these in our oob packages, but they can happen still.  Closing as answered.

**Comment by sprj-git** [comment]
Thanks @andrewconnell  & @VesaJuvonen !!

**Comment by andrewconnell** [comment]
To pile on, sadly this is one of those things that trips up people new to the Node.js toolchain... seeing warnings in the build, people freak and think there are problems. 

Warnings != errors :)
