### ISSUE TITLE
Adding a 3rd party library with woff icon font fails

### ISSUE THREAD

**Issue by zolem** [SharePoint/sp-dev-docs#2044]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I included the DevExtreme library in my project with the css. I would expect WebPack to properly load all files including fonts and icon fonts referenced in the css.

#### Observed Behavior
Webpack fails to properly load woff and woff2 files. There is an error thrown about babel-loader encountering an invalid character. I am not sure why babel-loader is being used for woff or woff2 files.

#### Steps to Reproduce
Create a new spfx project with yeoman. Install devextreme and devextreme react. Include the css files you need. (I used the material blue version but it shouldn't matter).

Run gulp serve and see the error.

#### Actions taken towards resolving the issue
I added file-loader to webpack and targeted all font types eot,svg,woff,woff2,ttf etc..

This appeared to work fine in chrome which is great but the fonts would not show up at all in internet explorer 11. The reason it did not work in ie11 is because the file that ie11 was grabbing was a file that had this inside:
```
module.exports = __webpack_public_path__ + "acbedcbe962874cfc350a945bf6d2a19.woff";
```

After further investigation I was able to solve the issue by removing all font extensions except woff and woff2.

I think all I did was create an issue to fix an issue so this is probably not the best way to fix the problem. When I was looking up solutions for this I found out that when babel-loader runs AND file-loader runs on a file then you get the above result. It would seem that somewhere in the webpack configuration there should be and exclusion for babel-loader to ignore font extensions and a specific configuration to use file-loader or url-loader to load font extensions.

I am curious if anyone else has run into this issue or has a different solution. I have not found any other solution myself, I just happened to get it to work through dumb luck.

**Comment by mcmynn83** [comment]
Sounds like this was resolved.
