### ISSUE TITLE
SharePoint - filter by person field

### ISSUE THREAD

**Issue by repton-infinity** [SharePoint/sp-dev-docs#2046]
The documentation says: "In the SharePoint REST service, users are represented by the user's friendly (display) name, and not their alias or domain\alias combination. Therefore, you must construct user queries against users' friendly names."

Is this right? I was trying to use Flow to query a list and only return list items with a particular person. I tried a filter like this:

PersonField eq 'Joe Smith'

but nothing was returned. This SharePoint stackoverflow post says I need to use the ID of the user instead:
https://sharepoint.stackexchange.com/questions/73398/how-can-i-filter-a-list-with-odata-for-person-or-group-field

So I went to group 0 in my site, found the id of the user, and then altered by Flow query to this:

PersonField eq 1221

And then it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Arcalight** [comment]
I'm still running into this issue. I'm trying to use Flow to find SharePoint list items with a user. The list column name is TeamMember and it's a people field that shows the user's Display Name (created automatically with another Flow). When I use the SharePoint Get Items connector with the Filter Query of TeamMember eq 'Display Name' (the display name is dynamic data from the Get User Profile V2), nothing is returned.

**Comment by andrewconnell** [comment]
Yes, the docs are correct. As the SO post you reference states, People fields are actually implemented as lookup fields. These point back to the UserInfoList, a special hidden list in the root of the site collection. The value saved in the People field is the ID of the person in that list. 

So you have two options in your REST query:
- either expand the Person lookup field and filter on the person's display name in the UserInfoList
- or obtain the ID of the person in the UserInfoList and apply the filter with that ID on the Person lookup field
