### ISSUE TITLE
SPFx webpart is not working if the classic page contains OOTB webpart

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2048]
_From @bhanuprakash857 on June 14, 2018 6:50_

I have ~1.1.0 SPFx framework webpart with Angular1.x framework.
  
This webpart is working fine if the page does not contain the OOTB Webaprt. The moment i added the OOTB webpart, it stops working. Below is the Error

![image](https://user-images.githubusercontent.com/12428545/41395885-df69ebea-6fcc-11e8-8171-fae76b973019.png)

> Note: I have obsereved this behavior only in chrome

_Copied from original issue: SharePoint/sp-dev-fx-webparts#534_

**Comment by VesaJuvonen** [comment]
As this is NOT around any samples in the this repository, moving this discussion to the sp-dev-docs repository like noted in the issue template.

"Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at https://github.com/SharePoint/sp-dev-docs/issues/new. This will help us respond to your issue faster."

**Comment by patmill** [comment]
@bhanuprakash857 - Can you provide a bit more information?  What OOTB webpart are you adding?  Is there any additional information in the console?

**Comment by bhanuprakash857** [comment]
@patmill - Adding List View web part. In console i'm getting below error.
![image](https://user-images.githubusercontent.com/12428545/41578958-664fe194-73b2-11e8-8c43-e3e715151464.png)

**Comment by bhanuprakash857** [comment]
I found another SPFx webpart also having the Same problem.

**Comment by VesaJuvonen** [comment]
The problem here is that unless we can repro this, we can't really investigate the root cause. This means that in the best case scenario, we would have access on the solution for repro, if that's possible.

**Comment by mcmynn83** [comment]
No response from customer, closing the issue.
