### ISSUE TITLE
WebPart with knockout build failing after update to Drop 3

### ISSUE THREAD

**Issue by arnabchat90** [SharePoint/sp-dev-docs#205]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

After updating to Drop 3 the my web part does not build anymore.
#### Observed Behavior

The following error is coming while building the webpart with knockout - 

Error - typescript - src\webparts\helloWorld\HelloWorldWebPart.ts(15,22): error TS2415: Class 'HelloWorldWebPart' incorrectly extends base class 'BaseClientSideWebPart<IHelloWorldWebPartProps>'.

They have a seperate of declaration a private property '_description'.
Please note that the my webpart was created earlier, and the _description property in my webpart is defined as a knockout observable - private _description: KnockoutObservable<string> = ko.observable('');

Am I missing something here?

**Comment by patmill** [comment]
Nope - that's a bug.  The easiest way to fix this is to rename the _description variable in your webpart code to something like _koDescription .

**Comment by manishgarg1** [comment]
Hi @arnabchat90, this bug should be fixed at the current time. Please let us know if this is still and issue.
