### ISSUE TITLE
Error on FC.EventObject

### ISSUE THREAD

**Issue by techbvdinesh** [SharePoint/sp-dev-docs#2050]
Would like know where "FC" object is declared, throwing a error during build javascript to Typescript conversion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ecd027-f5ca-48c0-d60c-1883fa24ab96
* Version Independent ID: 9f38cbc9-464a-a2a4-0eeb-4deb6b2eb339
* Content: [Migrate jQuery and FullCalendar solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by unowiz** [comment]
I came across this same issue. FullCalendar provides its own type definitions, so you don't need @types/fullcalendar installed as if you notice the `@types\fullcalendar folder under node_modules`, its empty. 
I have noticed that there are some types available under `node_modules\fullcalendar\dist` and I have used the following types
`import { EventObjectInput } from 'fullcalendar/src/types/input-types';
import { Default as View } from 'fullcalendar/View';`

And then I have tried using EventObjectInput  instead of FC.EventObject and View instead of FC.ViewObject.

Hope this helps.

**Comment by msekkappan** [comment]
What did you do with the FC on line 311?    const calendarOptions:FC.Options

**Comment by NaveenAhuja** [comment]
I got the same issue - "Cannot find namespace 'FC'."

How do i proceed to resolve this ?

**Comment by andrewconnell** [comment]
Looks like there are quite a few things that could be updated in this article to clean it up and modernize it. I'll add that as a task to the backlog...

But, the `FC` namespace is added when you install the TypeScript type declarations to the project in the step **Add type definitions for used libraries**. 

However, it appears that the type declarations have changed quite a bit for the FullCalendar package. It appears `EventObject` has been renamed to `EventObjectInput` and `ViewObject` has been renamed to `View`. You need to import these into the file where this code is present.

In the doc, add this:

```ts
import {EventObjectInput, View} from "fullcalendar";
```

Then in the code, where you see this line:

```ts
eventClick: (calEvent: FC.EventObject, jsEvent: MouseEvent, view: FC.ViewObject): void => {
```

update it to:

```ts
eventClick: (calEvent: FC.EventObjectInput, jsEvent: MouseEvent, view: FC.View): void => {
```

I haven't fully tested this, but on a quick inspection that appears to be the resolution to this comment. Like I said though, I'll add to the backlog to get this doc refreshed to current.
