### ISSUE TITLE
Error while importing GraphHttpClient, HttpClientResponse, IGraphHttpClientOptions

### ISSUE THREAD

**Issue by licypala** [SharePoint/sp-dev-docs#2051]
import { GraphHttpClient, HttpClientResponse, IGraphHttpClientOptions } from '@microsoft/sp-http';
Giving error: "c:/_/hellograph-webpart/node_modules/@microsoft/sp-http/dist/index-internal"' has no exported member 'GraphHttpClient'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10854d33-70e9-04ce-fd21-bb26eb55d267
* Version Independent ID: 181693b7-2dcb-332c-39e8-9bf74d13a68f
* Content: [Tutorial - Use GraphHttpClient to call Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/call-microsoft-graph-using-graphhttpclient)
* Content Source: [docs/spfx/call-microsoft-graph-using-graphhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/call-microsoft-graph-using-graphhttpclient.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This is unfortunately known issue with 1.5 release which will be addressed in a matter of days with 1.5.1 release.

**Comment by licythom** [comment]
Here is the code I tested:

import { AadHttpClient } from "@microsoft/sp-http";
import { MSGraphClient } from "@microsoft/sp-client-preview";

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
 public render(): void {
   const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
   client
     .api('/v1.0/groups')
     .get((error, response: any, rawResponse?: any) => {
       console.log(response.json());
   });
}

Please let me know if the code is right.

**Comment by VesaJuvonen** [comment]
The code is right, but due to the mentioned known issue, your code will not work properly with 1.5. You will currently need to go back to 1.4.1 version until 1.5.1 is out.

**Comment by licythom** [comment]
Tried with 1.4.1. But, it gives the following error:

![image](https://user-images.githubusercontent.com/6519992/41552513-cef78884-72e3-11e8-8454-2dc967ad68e0.png)

**Comment by tioger** [comment]
this error seems to be a Type error on your footer.tsx on line 13, can you check if its not a just a type  error in your code ?

**Comment by cythomli** [comment]
@tioger Line 13 has the following code:

const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
    client
     .api('/me')
     .get((error, response: any, rawResponse?: any) => {
       console.log("THIS IS THE RESPONSE");
   });
I followed this link https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph. Please let me know if the code is wrong. Thanks!

**Comment by lahuey** [comment]
Hi @cythomli ,

The GraphClient and MSGraphClient are both beta APIs. To use these APIs in the 1.5 release, please uses the --plusbeta flag. See more details here ->
[](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-for-SharePoint-Framework-Package-v1.5)

**Comment by cythomli** [comment]
@lahuey  I don't see a link to get more details. Please share the link. Thanks!

**Comment by tioger** [comment]
@cythomli  your code seems to be goob and its maybe  because graph api doesn't work with 1.5 but i have an other idea :
you call this.context on your footer but on webpart the context is only accessible on the entry component find it in src/webpart/nameOfYourWebpart 
If you want to use the context inside a child component you need pass this.context from entry component to child component using props.
Share your code if you can.

**Comment by cythomli** [comment]
@tioger Here is how my file structure looks like:

![code structure](https://user-images.githubusercontent.com/6519992/41878706-0ab78a98-788b-11e8-9c6d-a345c0615c4d.PNG)

Earlier I was using the above code in a file inside containers. Where should I move the code to? Thank you!

**Comment by devinprejean** [comment]
I thought the MSGraphClient and GraphHttpClient were different. I upgraded from 1.41. to 1.5.1 today and got this error. I don't want to move to the preview MSGraphClient. Is it not possible to fix this for GraphHttpClient?

**Comment by cythomli** [comment]
@lahuey @VesaJuvonen 

Thanks for your reply. So, I upgraded spfx to 1.5.1 and installed the following package version:
"@microsoft/sp-client-preview": "1.5.1-plusbeta",

I now see the following error:
![error](https://user-images.githubusercontent.com/6519992/42335597-b7d9a010-8035-11e8-8dff-ecdd01e0a6ca.jpg)

Please let me know your thoughts on this issue. Thanks!

@lahuey Please reopen this issue as it hasn't resolved yet. Thanks!

**Comment by lahuey** [comment]
@devinprejean  GraphHttpClient is a beta API. As of SPFx 1.5, developers will need to use the --plusbeta flag to gain access to APIs that are marked as beta. 

@cythomli Are you using "1.5.1-plusbeta" for all of your SPFx packages? 

I've verified that this works with a clean project that was generated using the --plusbeta flag. I would delete the node_modules folder and run npm install after verifying that all SPFx packages have the same version.

**Comment by cythomli** [comment]
@lahuey I tried using 1.5.1-plusbeta for "@microsoft/sp-client-preview" and 1.5.1 for other packages. Should I use 1.5.1-plusbeta for all dependencies?

"dependencies": {
    "@microsoft/sp-core-library": "1.5.1",
    "@microsoft/sp-client-preview": "1.5.1-plusbeta",
    "@microsoft/sp-lodash-subset": "1.5.1",
    "@microsoft/sp-office-ui-fabric-core": "1.5.1",
    "@microsoft/sp-webpart-base": "1.5.1",
    "@types/adal": "1.0.27",
    "@types/angular": "1.6.32",
    "@types/es6-collections": "0.5.31",
    "@types/jest": "20.0.8",
    "@types/nock": "8.2.1",
    "@types/prop-types": "15.5.2",
    "@types/react": "15.6.6",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "15.5.6",
    "@types/react-redux": "5.0.9",
    "@types/redux-logger": "3.0.4",
    "@types/request": "2.0.3",
    "@types/webpack-env": "1.13.0",
    "@uifabric/styling": "0.24.2",
    "@uifabric/utilities": "4.16.0",
    "adal-angular": "=1.0.12",
    "applicationinsights-js": "1.0.13",
    "immutable": "3.8.1",
    "jest": "20.0.4",
    "npm": "5.8.0",
    "office-ui-fabric-react": "4.43.1",
    "react": "15.6.2",
    "react-appinsights": "1.0.2",
    "react-dom": "15.6.2",
    "react-redux": "=5.0.4",
    "redux": "3.7.2",
    "tslint-react": "3.2.0"
  },

**Comment by lahuey** [comment]
Yes. Mixing --plusbeta packages with normal packages is unsupported. Can you update these packages and let me know if you're unblocked? Thanks!

"@microsoft/sp-core-library": "1.5.1-plusbeta",
"@microsoft/sp-client-preview": "1.5.1-plusbeta",
"@microsoft/sp-lodash-subset": "1.5.1-plusbeta",
"@microsoft/sp-office-ui-fabric-core": "1.5.1-plusbeta",
"@microsoft/sp-webpart-base": "1.5.1-plusbeta",

**Comment by devinprejean** [comment]
@lahuey I see here they don’t talk about using the plus beta flag. Could we get that document updated?

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph

**Comment by cythomli** [comment]
@lahuey Thanks for your response. So, I updated the packages you mentioned to 1.5.1-plusbeta, deleted node_modules folder, ran npm install. When I run the app, I don't see any error now but I get a null response:

![image](https://user-images.githubusercontent.com/6519992/42354708-865df0fc-807d-11e8-94e3-47ed70201440.png)

![image](https://user-images.githubusercontent.com/6519992/42354721-9c548114-807d-11e8-9cb0-606f983b43a9.png)

Please let me know why it is returning a null response. Appreciate your help. Thanks!

**Comment by lahuey** [comment]
Could you check the value of the error object?

**Comment by cythomli** [comment]
@lahuey Here is the value of error object:

![image](https://user-images.githubusercontent.com/6519992/42403934-e05e6c28-8139-11e8-8a97-466d4d2d62f0.png)
