### ISSUE TITLE
API to set/manage SPO Tenant properties?

### ISSUE THREAD

**Issue by matthong** [SharePoint/sp-dev-docs#2052]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The introduce of SharePoint Online Tenant properties is great, now we can have a centralized data storage for SPFx WebParts to use.  However, it seems that the only way to manage the properties is thorough Office 365 CLI or Powershell. 

Is there any REST API (or CSOM/JSON) to allow developers to manage tenant properties programmatically? If not, is there a plan for that? 

Thanks!

#### Observed Behavior

Don't see any documentation about managing tenant properties with API.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by vman** [comment]
Hi @matthong, I knew it was possible to manage tenant properties with CSOM but just like you, could not find any direct documentation for it. So I have written a quick blog post: https://www.vrdmn.com/2018/06/getset-sharepoint-online-tenant.html 

Hope you find it useful.

**Comment by matthong** [comment]
Thank you @vman for sharing your blog post, it is useful. Also, base on your post, I found the web class in @pnp.sp library does have the method to manage the tenant properties. https://pnp.github.io/pnpjs/sp/tenant-properties.html.
