### ISSUE TITLE
Modify fields in a library view

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#2053]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I am trying to update the fields on an existing library view
lastModifiedView.fields.removeAll()
.then(function(){
	lastModifiedView.fields.add("DocIcon");
})
.then(function(){
	lastModifiedView.fields.add("LinkFilename");
})
.then(function(){
	lastModifiedView.fields.add("Modified");
})
.then(function(){
	lastModifiedView.fields.add("Editor");
})
.then(function(){
	lastModifiedView.fields.add("Author");
}); 

#### Expected or Desired Behavior
The view should display 5 columns.

#### Observed Behavior
Only some of the columns get created.

#### Steps to Reproduce
See above code. I am using pnp-js-core version 3.0.8.

**Comment by patmill** [comment]
You should post your issue / question in the pnp-js-core repo - https://github.com/SharePoint/PnP-JS-Core/issues
