### ISSUE TITLE
Using AppOnly tokens from non .NET applications

### ISSUE THREAD

**Issue by superglue777** [SharePoint/sp-dev-docs#2056]
Please explain protocol of exchanging certificate to a token without using .NET AuthenticationManager. Besides it is not clear, does this method applies to SharePoint Online only or to any other on-line resources, like Graph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by aaronmi** [comment]
Adding a REST API code sample would be greatly helpful here.

**Comment by NelsonLamprecht** [comment]
After a conversation with product support writing to user profile data with an Azure AD App only token is not supported. This should be more clear, especially since the application permission is called "Read and write user profiles"

**Comment by silmer** [comment]
I think it might depend on how you want to connect. E.g. with SharePoint-PNP Powershell you can use the .PFX directly: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps#examples

**Comment by andrewconnell** [comment]
This question isn't specific to SharePoint... you can use any platform to do this. Azure AD offers multiple SDKs that cover all their scenarios, including this. I'd refer to their docs & samples as they will have many more examples than something SharePoint-specific. SharePoint is just an endpoint in this scenario.

To answer the question, the protocol is best explained in the Azure AD docs. The following links should get you started.

- https://docs.microsoft.com/azure/active-directory/develop/active-directory-authentication-libraries
- https://docs.microsoft.com/azure/active-directory/develop/reference-v2-libraries
- https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token

**Comment by abbodh** [comment]
Is there any Rest API sample to perform search operation using SharePoint APIs with AAD tokens?
