### ISSUE TITLE
Hosting Webpart from O365 CDN unsuccessfull

### ISSUE THREAD

**Issue by caelistic** [SharePoint/sp-dev-docs#2063]
Hi there!
I followed the instructions to publish my webpart to the O365 CDN.
Everything worked fine, activated the CDN, bundled and packed the solution and uploaded it to the appcatalog, but when I am trying to add the webpart to a site i get the following errors:

In Google Chrome Browser: 
[SPLoaderError.loadComponentError]:
***Failed to load component "86113633-af30-48de-86b4-672a9d39f8ac" (xxxxWebPart).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/xxxxxx/sites/apps/ClientSideAssets/656be2fa-23ca-4725-8b0c-d12d12430922/xxxx-web-part_47d8dbfc137ae36ba64e68c30e3466dc.js' for resource 'xxxxxx-web-part' in component '86113633-af30-48de-86b4-672a9d39f8ac' (xxxxxWebPart). There was a problem in the server.

In Edge Browser:
[SPLoaderError.loadComponentError]:
***Failed to load component "86113633-af30-48de-86b4-672a9d39f8ac" (xxxxWebPart).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/xxxxx/sites/apps/ClientSideAssets/656be2fa-23ca-4725-8b0c-d12d12430922/xxxxxx_47d8dbfc137ae36ba64e68c30e3466dc.js' for resource 'xxxxx-web-part' in component '86113633-af30-48de-86b4-672a9d39f8ac' (xxxxWebPart). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

SPFx Version 1.5.0

What am I doing wrong?
Thanks for the help.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Hosten clientseitiger Webparts in Office 365 CDN (Hello Word, Teil 4)](https://docs.microsoft.com/de-de/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs.de-de/blob/live/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This is an unfortunate known issue which should be now getting resolved within a matter of days. If that's not the case, please let us know within a week.
