### ISSUE TITLE
Unable to reference PnP JS in SPFx webpart using External Section

### ISSUE THREAD

**Issue by PriyaranjanKS** [SharePoint/sp-dev-docs#2064]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
 
#### Expected or Desired Behavior
You can add a module to the SPFx Webpart solution, in this case PnP JS using the External Sections in the config.json file as : 

 "externals": {
    "sp-pnp-js": "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/3.0.9/pnp.min.js"
  },
 
Later you can refer the PnP JS in the TS file by importing it as : 

import * as pnp  from "sp-pnp-js";

This does not require the bundling of the PnP JS which happens during the usage of :  
npm install sp-pnp-js --save (which is not used in this bug reporting)

#### Observed Behavior

Config.json reference : 
![image](https://user-images.githubusercontent.com/29351010/41589272-b8fad010-73d1-11e8-8f55-cae7f756af86.png)

TS file import : 
![image](https://user-images.githubusercontent.com/29351010/41589303-d1977042-73d1-11e8-82fe-4be1658cb00e.png)

On running Gulp Bundle --ship , error "Cannot find module sp-pnp-js " is generate in Node Command Prompt. 
![image](https://user-images.githubusercontent.com/29351010/41589234-96468b72-73d1-11e8-8be8-ddbe05133593.png)

However if i dont use external section reference and use npm to install PnP JS using the below command does not throw any build errors.
npm install sp-pnp-js --save

However as I am particular in using externals sections to reference the JS File, Is there something i am missing in the workflow like adding a typing for PnP JS ?

**Comment by StfBauer** [comment]
In order to get the proper typings you always have to install the ```sp-pnp-js``` package to your project.

The CDN reference on the external section adds the library to your project and reference it on CDN later. The local typings you only get with the local installation of this library.

**Comment by PriyaranjanKS** [comment]
@StfBauer : So in that case, we would be forced to bundle the PnP JS file along with the project which i dont think is a good option. Is there a way we can explicitly install just the typings like we do for angular as in : 
npm install @types/angular --save-dev

**Comment by StfBauer** [comment]
No. You don't bundle anything you just use it for the typings.

If you would have referenced in your external section to the node_modules folder you would bundle it.
You have a reference to the CND so it won't get bundled and locally installed npm package will only be used for the type definition.

I asked the exact same question on [pnpjs](https://github.com/pnp/pnpjs/issues/81). You will find the discussion there.

**Comment by patrick-rodgers** [comment]
Hi @PriyaranjanKS -

To expand on what @StfBauer says: externals is a bundling time concept. Meaning you install the library in your project, us it as you would normally without externals and then at bundle time the packager (in this case webpack) will leave our that library's code from the bundle, instead ref'ing the external link. So your bundle ends up without the code included. In this scenario the package itself is acting as the types for you to reference. This allows us to maintain a single thing and you to get the latest typing information with each package.

-----
_Thank you for your interest in the sp-pnp-js library. We want to mention that this library is being deprecated in July, 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible, or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_
