### ISSUE TITLE
Unclear NPM message during SPFx project provision

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2065]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
More information what it means the specific npm version was found.

#### Observed Behavior
When I create a new project using SPFx I see the following message during the configuration or installation. I don't get any clue out of it what it actually means.

<img width="668" alt="screen shot 2018-06-19 at 12 18 12" src="https://user-images.githubusercontent.com/5503835/41592140-fc868fb0-73bb-11e8-92c2-59c83c6b90d3.png">

Is it good? Is it bad? Is it just an information like we found npm in a specific version? Does it mean this will be used for the installation of all NPM packages?

#### Steps to Reproduce
Create a new SPFx project using version 1.5.0.

**Comment by lucabandMSFT** [comment]
@StfBauer , thanks. That's indeed an information we provide as part of the flow that can help us in the investigation in case of potential issues.
If you believe that is confusing we can definitively think about removing it in the future versions or move it somewhere else.

**Comment by StfBauer** [comment]
@lucabandMSFT What do you think about having this information more at the beginning. Similar what I did in the PnP generator.

<img width="733" alt="yo-running" src="https://user-images.githubusercontent.com/5503835/57572909-46147780-7421-11e9-9fec-7d68ceee24bf.png">

Something like this. Right somewhere in the generator, it is definitely confusing:

----------------------
**SPFX:**     1.8.2
**Installer:** npm 6.1.0
----------------------

**Comment by patmill** [comment]
This is spat out by Yeoman by default, but it's not something we're going to remove at this point.
