### ISSUE TITLE
NuGet references outdated: update OfficeDevPnP => SharePointPnPCore[Online|2013|2016|2019]

### ISSUE THREAD

**Issue by bexkelleher** [SharePoint/sp-dev-docs#2070]
I can't find the NuGet packages for OfficeDevPnP.Core, have they been replaced by SharePointPnPCoreOnline and SharePointPnPCore2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e581d3f-a187-b893-70e3-4c3ab5d45936
* Version Independent ID: d2316e36-fa51-f00e-26eb-5a1efaa0213d
* Content: [Provisioning console application sample](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample)
* Content Source: [docs/solution-guidance/provisioning-console-application-sample.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/provisioning-console-application-sample.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by umaknow-alain** [comment]
You can use this one instead SharePointPnPCoreOnline. but there seems to be a problem with this line ApplyProvisioningTemplate(defaultForeground, targetWebUrl, userName, pwd, template); seems it c'ant be use like this. Tying to find out, if i fund something, i let you know.

**Comment by andrewconnell** [comment]
Yes... it appears the names have changed and the doc needs to get updated.

**Comment by ravick4u** [comment]
I also see now there is 2019 version as well whereas the document only mentions about 3 versions (Online/2013/2016)

**Comment by ravick4u** [comment]
Also "ptci.PersistBrandingFiles = true;" should be used instade of "ptci.PersistComposedLookFiles = true;"
