### ISSUE TITLE
SPfx Web Part on Classic Page giving error occasionally on page load

### ISSUE THREAD

**Issue by Masood10** [SharePoint/sp-dev-docs#2071]
Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Expected or Desired Behavior**
Web Part will load correctly on classic page as it happens on modern page

**Observed Behavior**

I get the following error occasionally on every 4th,5th reload. It doesn't happen on every page load and I cannot find the reason for this. 

It seems to work fine on a Modern Webpage.

```
[SPWebPartErrorCode.IncorrectBoostrapModule]:

Bootstrap module for web part WebPart.CsTaskBoardWebPart.g_656d59f0_956e_4b3e_bd11_436dc174b79f not of the correct type. Make sure to export your web part as 'export default WebPartName'.

***CALLSTACK:

t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-classic-page-assembly_en-us_5e2272d7fd70b712d190a24d11e25780.js:201:15770
t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-08.007/sp-classic-page-assembly_en-us_5e2272d7fd70b712d190a24d11e25780.js:301:8449
```
@mozillalives @waldekmastykarz @wobba @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Unless this happens with out of the box web part from Yeoman, we would need more details to be able to investigate this in the engineering side. Having a sample solution would be helpful, if possible.

**Comment by wobba** [comment]
@VesaJuvonen Small repro at https://github.com/wobba/spfx4fun/tree/master/linkfoo

Basically, new webpart, no framework, and have the following render function. Clicking the link opens the link in the same tab/window instead of opening a new one.

```typescript
public render(): void {
        this.domElement.innerHTML = `
              <a target="_blank" href="/">Root site</a>
        `;
    }
```

**Comment by johnguy0** [comment]
Is this issue still occuring? A correlation id with date/time would be useful for us to pull logs. A consistent repro would be even better.
