### ISSUE TITLE
Task List Modern Experience - Opening Tasks Does not work

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-docs#2072]
I'd like to direct your attention to an issue that seems to be happening with Task Lists in the modern experience. 

When you click on the title of the task, which in classic opens the display form, it attempts to download the task as a file. This seems to be an issue with the rendering of the actual Task Name field in the Modern Experience. 

There is a tech community post here by another user experiencing the same thing: https://techcommunity.microsoft.com/t5/SharePoint/Unable-to-open-task-item-in-new-experience-000/m-p/195116/highlight/false#M17750

It would be great if we could get some official comms on what is causing this issue and if a fix is being worked on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c41e533-8210-890c-05f9-a11a2c98306c
* Version Independent ID: 919463a5-d2a8-5048-dc8c-b457f4cf1c19
* Content: [Modernize the user interface](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface)
* Content Source: [docs/transform/modernize-userinterface.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ashley72788** [comment]
I'm also having this issue

**Comment by chrriedel** [comment]
me too

**Comment by itsknob** [comment]
For people still having this issue, it looks like setting the Item Limit in the view settings to the maximum value, 2147483647, is a workaround for this issue.

**Comment by jarellm** [comment]
> For people still having this issue, it looks like setting the Item Limit in the view settings to the maximum value, 2147483647, is a workaround for this issue.

This did not work for me.

**Comment by beebul** [comment]
Doesn't work for me either. Very disappointed, this is a major bug.

**Comment by allexb** [comment]
The same issue

**Comment by andrewconnell** [comment]
This issue list is primarily for developer related issues and questions. This falls more into the UX experience for OOTB capabilities and therefore, the best place to report this is in the recommended support channels such as your tenant admin UI.
