### ISSUE TITLE
const didnt work

### ISSUE THREAD

**Issue by vreezy** [SharePoint/sp-dev-docs#2073]
had to remove the type. didnt work for me
original:
const accordionOptions: JQueryUI.AccordionOptions = {
workaround:
const accordionOptions = {

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Hinzufügen von jQueryUI Accordion zu Ihrem clientseitigen SharePoint-Webpart](https://docs.microsoft.com/de-de/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs.de-de/blob/live/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Just tested this with the latest recommended versions and had no issues with the const type. That's though good note if someone else is having any issues. Closing this for now as it's not a really actionable issue as such, rather a comment. Appreciate the input.
