### ISSUE TITLE
[LOC] Invalid links in an article

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#2074]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Current:** 2 links goes to 404 error page
**Expected:** links should go to valid page or be removed from the article

**Repro steps:**
1. go to: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/localization-sharepoint-add-in (or GH: https://github.com/SharePoint/sp-dev-docs/blob/live/docs/solution-guidance/localization-sharepoint-add-in.md)
2. search for "_Localize the add-in web, host web, and remote components of an add-in  (Office Dev GitHub sample)_" and "_VariationsExtensions.cs class (O365 PnP Sample)_"
3. click the links --> 404 error

![spdevdocs_pnp](https://user-images.githubusercontent.com/16706698/41657803-0bf2acfe-7484-11e8-87b6-4ad64bbfd9ea.PNG)

**Comment by thechriskent** [comment]
Thanks! I've submitted a fix for these.
