### ISSUE TITLE
SharePoint 365 Search Outage At Tenant

### ISSUE THREAD

**Issue by pdemro** [SharePoint/sp-dev-docs#2081]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Add a modern page to a modern site.  Modern page is indexed within 5-60 minutes and available for search.

#### Observed Behavior

Modern page is added with some text and a header image.  Header image is indexed from the Site Assets library.  ASPX page is not searchable after 24+ hours.

[Following steps here](https://blogs.msdn.microsoft.com/svarukala/2017/08/09/how-to-download-or-view-sharepoint-online-search-crawl-logs-using-security-compliance-center/) I was able to download the crawl log for the site in question from the security & compliance center and can confirm new pages are not being indexed from our site pages library. 

Have checked and double-checked the regular failure points and not so common failure points and can't seem to find an explanation

* Page is published
* Library Settings -> Advanced Settings -> Allow items to appear in search
* SC Settings -> Search & Offline Availability -> Allow this site to appear in search
* Library Settings -> Advanced -> Reindex
* SC Settings -> Search & Offline Availability -> Reindex

This is a tenant on targeted release for all users

#### Steps to Reproduce

* Add a page to the site pages library for a modern communication site
* Wait 24+ hours
* Attempt a search using out-of-box search.  Page does not appear (but page assets from site assets library do appear in search)

Other pages created several weeks ago appear as expected in search

**Comment by PooLP** [comment]
Hi,
Microsoft have declared a incident for this problem :
SP141856 - Problem searching new pages within SharePoint Online
https://admin.microsoft.com/AdminPortal/Home#/servicehealth?tabid=1

**Comment by pdemro** [comment]
Seems resolved now.  Thanks @PooLP for the heads up on the service bulletin
