### ISSUE TITLE
Runtime Error on running hosted workbench after upgrading to 1.4.1

### ISSUE THREAD

**Issue by licypal** [SharePoint/sp-dev-docs#2082]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Run gulp serve --nobrowser
Run Hosted workbench
App should run fine

#### Observed Behavior

Run gulp serve --nobrowser
Run Hosted workbench
Page shows the error below:

<img width="780" alt="error" src="https://user-images.githubusercontent.com/6519992/41686664-bc06cdc2-7499-11e8-97f7-6741f3843aeb.PNG">

#### Steps to Reproduce

Run gulp serve --nobrowser
Run Hosted workbench
On logging out and logging into the hosted workbench, it is working fine.

**Comment by VesaJuvonen** [comment]
We can't, unfortunately, do repro with the given information so we would need to understand more on your environment as this works for other developers. What versions of the npm you are using, what about node? - Is this a PC or Mac? - How was the project created?

**Comment by cythomli** [comment]
Node: 6.12.0
Npm: 5.8.0
PC
Upgraded to 1.4.1, created hello world project

**Comment by mcmynn83** [comment]
We don't see this behavior which means it is most likely specific to your package.  You should include your package so that somebody can take a look at the specific problem.
