### ISSUE TITLE
Error - gulp package-solution

### ISSUE THREAD

**Issue by vreezy** [SharePoint/sp-dev-docs#2086]
schema.xml must be in the same folder as element.xml.
Or "gulp package-solution" crashs with error.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Bereitstellen von SharePoint-Ressourcen aus Ihrem clientseitigen SharePoint-Webpart](https://docs.microsoft.com/de-de/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs.de-de/blob/live/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
That's indeed correct. The packaging does assume that the schema.xml file is located next to the elements.xml file.
