### ISSUE TITLE
Add Valid js Reference in Default.aspx

### ISSUE THREAD

**Issue by ArthurEzenwanne** [SharePoint/sp-dev-docs#2087]
In section "Create the JavaScript and a button to invoke it", Step 2, please take note that when you change the name of your js file from "App.js" to "Add-in.js" also remember to change the js call reference in the default.aspx page asp section "Content ContentPlaceHolderID="PlaceHolderAdditionalPageHead" 

For example:
    &lt;script type="text/javascript" src="../Scripts/Add-in.js"&gt;&lt;/script&gt;
instead of:
    &lt;script type="text/javascript" src="../Scripts/App.js"&gt;&lt;/script&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e34316f-77a6-e149-4b2e-a1750d0dda6b
* Version Independent ID: dab2b2ca-c529-e970-f6ab-9dc214c81e7f
* Content: [Use the SharePoint JavaScript APIs to work with SharePoint data](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data#create-the-javascript-and-a-button-to-invoke-it)
* Content Source: [docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... will get the doc updated.
