### ISSUE TITLE
Error: File not found

### ISSUE THREAD

**Issue by ArthurEzenwanne** [SharePoint/sp-dev-docs#2090]
1. Followed the series and all cod has checked thus far. This lesson "Work with host web data from JavaScript in the add-in web" keeps generating the File not found error. The failure callback function "onGetScheduledItemsFail" is always called.
2. I'm using VS2015 Enterprise on a Win10 Pro version 1803 build 17134.112. The AppManifest.xml permissions page and permissions tab doesn't save the edited List permission properties dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e361acb6-1eef-2a78-3a51-3dff82b7a239
* Version Independent ID: 4d7e6841-8a09-2ece-76fe-7edf901d15c9
* Content: [Work with host web data from JavaScript in the add-in web](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web)
* Content Source: [docs/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by antoniomoyaramos** [comment]
1. 
2. For the permission, edit the appmanifest via xml like in this file in the line 20.
 <Property Name="BaseTemplateId" Value="106" /> 
the url: 
https://github.com/OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials/blob/master/10_BeforeExternalData/EmployeeOrientation/AppManifest.xml

**Comment by JamesPOrton** [comment]
Just for reference, the "file not found" error is because the code snippet

function getQueryStringParameter(paramToRetrieve) {
     var params = document.URL.split("?")[1].split("&amp;");

Should read
function getQueryStringParameter(paramToRetrieve) {
     var params = document.URL.split("?")[1].split("&");

This is because the call to getQueryStringParameter is a parameter to decodeURIComponent and therefore the URL has all ready been URL decoded.

James

**Comment by ArthurEzenwanne** [comment]
@JamesPOrton, I don't see any difference in the two code snippets you shared above. I believe you meant ```var params = document.URL.split("?")[1].split("&amp;");``` in the first snippet should be changed.

> 
> 
> Just for reference, the "file not found" error is because the code snippet
> 
> function getQueryStringParameter(paramToRetrieve) {
> var params = document.URL.split("?")[1].split("&");
> 
> Should read
> function getQueryStringParameter(paramToRetrieve) {
> var params = document.URL.split("?")[1].split("&");
> 
> This is because the call to getQueryStringParameter is a parameter to decodeURIComponent and therefore the URL has all ready been URL decoded.
> 
> James

**Comment by JamesPOrton** [comment]
Many thanks you were correct.

James

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
