### ISSUE TITLE
SPFx 1.5.0 - Impossible to build an extension project with --ship

### ISSUE THREAD

**Issue by val0o** [SharePoint/sp-dev-docs#2096]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> The solution should build correctly but it doesn't, even with a vanilla project.

#### Observed Behavior

> 
![image](https://user-images.githubusercontent.com/22765276/41763694-2f2a57ea-75ff-11e8-90d9-e4a3443857c6.png)

#### Steps to Reproduce

> - Create a vanilla SPFx 1.5.0 project ApplicationCustomizer extension (did not try with other kinds).
> - Build/bundle/package your project in production mode (--ship)

Thanks for your contribution! Sharing is caring.

**Comment by val0o** [comment]
@waldekmastykarz  Thank you for follow-up, here is a new topic which is more generic than the previous one

**Comment by val0o** [comment]
yes it does with `gulp package-solution --ship` but I notice that there are missing steps in the build that generates incomplete package

**Comment by waldekmastykarz** [comment]
I noticed that you're running SPFx in Docker. Could you check if you get the same result if you ran it on your host, just to eliminate Docker as the possible culprit?

**Comment by val0o** [comment]
Yes actually I tested without docker at first

**Comment by GwSoJ** [comment]
Some further information: I took the helloworld webpart and added some connection to the SharePoint lists as per the tutorial. It still gives the error when running gulp bundle --ship however if you then run gulp package-solution --ship it generates no error and works fine if you publish it to the app catalog.

**Comment by val0o** [comment]
I close this issue since the error message is not blocking
