### ISSUE TITLE
SPFX field customizer should also work in the list webpart

### ISSUE THREAD

**Issue by SvenLauterbach** [SharePoint/sp-dev-docs#2105]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When adding the "List (preview)" webpart to a modern page, i expect that field customizer do also work in this webpart.

#### Observed Behavior

Field customizer do not work in a "List (preview)" webpart, while they work as expected in the list view.

#### Steps to Reproduce

Create a field customizer and add it to a list. The customizer should work as expected in the normal list view. Add a "List (preview)" webpart to a modern page and select the list with the field customizer. When rendering the webpart, the field customizer does not work. 

I know that the List webpart is in preview, but it would be great if the field customizer would also work in this webpart (using formatted columns could be a workaround for some use cases)

Thank you and greetings
Sven

**Comment by babaibhat** [comment]
Same here. Only works on actual list.
