### ISSUE TITLE
jquery@3.3.4  invalid

### ISSUE THREAD

**Issue by shahprashant1990** [SharePoint/sp-dev-docs#2107]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

When I execute "npm install --save @types/jquery" command in my SPFx Web Part I am getting below issue.

`-- @types/jquery@3.3.4  invalid

**Comment by waldekmastykarz** [comment]
Do you call just `npm install` or are you trying to install a specific package? If you're calling `npm install`, there is no need to include `--save`.

**Comment by shahprashant1990** [comment]
Ok. solved.
