### ISSUE TITLE
sp-office-ui-fabric-core marquee selection on details list triggers multiple times

### ISSUE THREAD

**Issue by jirivaneyck** [SharePoint/sp-dev-docs#2108]
When implementing marquee selection on a ui farbic details list in spfx
the onSelectionChanged event is fired mulitple times.
The initial event returns  a selected item but the second event returns an empty result
current version of "sp-office-ui-fabric-core" being used is 1.4.1.

updating to version 1.5.0 results in the event being fired 4 times.
with the follwing results:
1. selected item
2. empty result
3. selected item
4. empty result

the same components (marueeselection and details list)
work as expected in a non-spfx environment

**Comment by johnguy0** [comment]
Does this issue still repro using the latest packages?
