### ISSUE TITLE
Safari does not load webpart using MSGraphClient 

### ISSUE THREAD

**Issue by RobinBreman** [SharePoint/sp-dev-docs#2110]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When adding a webpart that uses the MSGraphClient the webpart won't render in Safari on first load.

#### Steps to Reproduce

For this scenario we used this demo webpart:
https://github.com/RobinBreman/SPFxDemo

1. Open a modern page in safari.
2. Add the webpart, publish and reload, the webpart won't run.

*Strange behaviour*
- Add another instance of the same webpart to the page, publish and reload
- Both webparts don't run.
- Refresh the page
- The second webpart runs !!
- Refresh the page
- Now both webparts run ??

Clearing cache, reproduces the scario above (fist no webpart loads, refresh, only one webpart loads, refresh, they both load).

_The issue above does not occur when using Chrome on IOS, only Safari seems to have this issue_

#### Observed Behavior
We see a lot of erros in safari on first loading the webpart page. Errors start decreasing on every refresh.
![chromevssafari](https://user-images.githubusercontent.com/25765614/41854416-791574dc-7890-11e8-8bf2-14b12e3a6c3b.png)

**Comment by StefanWaalderbos** [comment]
Any updates on this bug?

**Comment by lahuey** [comment]
@RobinBreman @StefanWaalderbos Are you still seeing issues with this?

**Comment by MRuimerman** [comment]
This is working for us now.

**Comment by RobinBreman** [comment]
@lahuey as my colleague @MRuimerman just confirmed this is now working. This issue can be closed
