### ISSUE TITLE
Office UI Fabric Ract Command Giving an error UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by shahprashant1990** [SharePoint/sp-dev-docs#2114]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Issue while adding command "npm --save install office-ui-fabric-react"
![fabric issue](https://user-images.githubusercontent.com/40460701/41907818-9f952330-795f-11e8-9d1a-c547af020c4d.png)

NPM Version:

@microsoft/generator-sharepoint@1.0.2

gulp@3.9.1

yo@2.0.2

It gives Warning: office-ui-fabric-react@6.20.0 requires a peer of react@>=16.3.2-0 <17.0.0 but none was installed.
How to solve this issue?

**Comment by Toonshorty** [comment]
The office-ui-fabric-react package moved to React 16 as of version 6.0.0, but SPFX doesn't currently support this as far as I know.

I resolved the issue by installing the latest release of version 5.x.x (5.112.0) instead.

**Comment by shahprashant1990** [comment]
Which product have you installed for 5.112.0? How to know my React is 16?

**Comment by shahprashant1990** [comment]
I have used below command and downgrade my "type/react" and it was causing an issue:

npm install --save @types/react@0.14.46
