### ISSUE TITLE
Cannot find module ../AdalConfig

### ISSUE THREAD

**Issue by aaronhawryluk** [SharePoint/sp-dev-docs#2116]
This page contains a reference to adalConfig that is never resolved.
This code:
import adalConfig from '../AdalConfig';

The module AdalConfig has not been defined anywhere in the page. There is an interface defined, IAdalConfig, but no AdalConfig.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc6b567-0762-fb88-e9f6-11482e81a5b2
* Version Independent ID: c64e977e-5adf-e31d-955b-1bafae3e9006
* Content: [Call the Microsoft Graph API using OAuth from your web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part)
* Content Source: [docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Check the note at the top of this doc... it was added after you left this comment. It's much easier and recommended to use the `MSGraphClient` / `AadHttpClient` to call the Microsoft Graph / obtain an access token to call the Microsoft Graph.
