### ISSUE TITLE
Why do you have to re-approve SPFx package for MSGraph use?

### ISSUE THREAD

**Issue by devinprejean** [SharePoint/sp-dev-docs#2119]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have a SPFx package that I'm working on. Using the graph client in preview right now. When I replace the same package with the same package, or even a new "version" of the package by changing the number but not the permissions in the package-solution.json file I get another approval in the admin panel. My question, is why? If I have already approved the request before and no additional permissions are being requested why is this happening?

Lastly, if this is just how things are what does MSFT advise we do? re-approve it? reject it? revoke the old and approve the new?

I've already tried to just re-approve it and I get this error:
`An OAuth permission with the resource Microsoft Graph and scope User.ReadBasic.All already exists.`

#### Expected or Desired Behavior

I expect there to be no new record to approve permissions for

#### Observed Behavior

Every time I deploy package a new record is created for approval even though one is already approved from a previous deployment.

#### Steps to Reproduce

1. Build a SPFx package that has MSGraph access permissions in the package-solution.json
2. Deploy the package to the app catalog
3. approve in the admin page of your SharePoint tenant
4. repeat steps 1-2

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by mcmynn83** [comment]
This issue will be resolved by the time we release for GA.  It is currently a preview feature and we are aware of the issue.

**Comment by devinprejean** [comment]
Is it common for an account, that is over 2 years old, to only have one post.... This one ^ in two years with the authority to close my issue with no proof of this being fixed for GA? Not saying you're lying at all, just have doubts to the authenticity of your claim. Anyone else more reputable than a 1 time poster can confirm this?

**Comment by mcmynn83** [comment]
@devinprejean - FYI I'm on the SPFX dev team at Microsoft.
