### ISSUE TITLE
Error when working in the workbench in Safari in private

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#212]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

No exceptions.
#### Observed Behavior

After loading workbench in Safari in private on macOS every ~3sec you get the following exception:

```
QuotaExceededError (DOM Exception 22): The quota has been exceeded.
setItem - PageStore.ts:81
savePageState - PageStore.ts:81
```

This seems to be related to how Safari handles local storage when run in private. More information incl. possible solutions are available at http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an.
#### Steps to Reproduce

Open workbench in Safari in private on macOS. Open Console to see the errors.

**Comment by StfBauer** [comment]
@waldekmastykarz from my experience Safari in private mode always have session storage and local storage disabled somewhere. When I try to access azure portal and Office 365 from a private safari session I get an error message that I have to enable the web storage api.

It's probably a pseudo security feature to avoid being redetected by applications.

**Comment by waldekmastykarz** [comment]
Sure thing, and it would be good if the workbench could handle it gracefully rather than throwing an error.

**Comment by patmill** [comment]
Moving this to 'won't fix'.  If this is really required, let us know and we can look into it.
