### ISSUE TITLE
ListView Command Order

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#2120]
Hi ,
Is it possible to change list view order for eg can i move command two before export to excel.
![image](https://user-images.githubusercontent.com/11780473/41955097-3af5200e-79fc-11e8-9a31-311c1fde41b9.png)

**Comment by mcmynn83** [comment]
No, this is not possible today.  Please leave this feedback in uservoice if you would like this feature.
