### ISSUE TITLE
MSGraphClient does not get approved scopes as permissions

### ISSUE THREAD

**Issue by frnk01** [SharePoint/sp-dev-docs#2121]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Get all O365 groups where user is member.

#### Observed Behavior
/me/joinedGroups is not working with the MSGraphClient. When running the SPFX in localhost I get the following error message in the console.

![image](https://user-images.githubusercontent.com/2760702/41960382-e33b2018-79ef-11e8-9a3a-51dd767b838e.png)

![image](https://user-images.githubusercontent.com/2760702/41960422-feb418b8-79ef-11e8-9186-d6e4bae2691c.png)

If I try the exact same in the Graph Explorer everything seems to be ok.

#### Steps to Reproduce
```
const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);

client
  .api('/me/joinedGroups')
  .get((error, res: any) => {
    console.log(res.value);
  });

```

API request:
`"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      }
    ]`

**Comment by frnk01** [comment]
Have now tried adding the following permissions:

```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Sites.All"
      }
    ]

```
And approved API access in admin center. Still recieving 400 BadRequest. If I change the call to just /me everything works as expected.

**Comment by VesaJuvonen** [comment]
Getting also direct emails on this (which is not preferred option), so others are also seeing this issue. We have started our investigation and will be working on a fix asap.

**Comment by VesaJuvonen** [comment]
Changed also title to be more descriptive on the exact issue.

**Comment by andrewconnell** [comment]
Confirmed... getting similar errors. Trying to get permissions to access **Calendars.Read** & **Tasks.Read** and getting 403's even though the permissions are granted in the SPO Admin Portal's API Management page.

**Comment by cythomli** [comment]
@frnk01 Please let me know where you added the following code into:

"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Sites.All"
      }
    ]

I tried with the following code and I am getting a 404 Not Found error. Could you please share the documentation you followed? Appreciate your help. Thanks!

import { AadHttpClient } from "@microsoft/sp-http";
import { MSGraphClient } from "@microsoft/sp-client-preview";
const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
client
.api('/me')
.get((error, response: any, rawResponse?: any) => {
console.log(response);
});

**Comment by frnk01** [comment]
@VesaJuvonen As a side note, not sure if it matters, when publishing the app once more with additional scopes I get a lot of duplicate pending requests in the admin center. When marking all requests and clicking approve, a lot of them fails due to duplicates. Want me to create a separate issue for this?

**Comment by qz2017** [comment]
Do you get 400 when you access other Graph APIs? joinedGroups is that is considered “hidden” schema, and is on deprecation path. It was kept open for apps that were using it in past. Newer apps don’t get it.

**Comment by frnk01** [comment]
@qz2017 Tried using the /me/memberOf now with the same four permission scopes as before and got the following:
![image](https://user-images.githubusercontent.com/2760702/42054876-d9a56ee2-7b15-11e8-90c3-e8726eaabe33.png)

**Comment by licypala** [comment]
@frnk01 

I followed this tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

and I don't see any of the following on my SharePoint Admin Center:

![image](https://user-images.githubusercontent.com/6519992/42849758-87e1b9bc-89d9-11e8-838c-8ba0716a4daa.png)


What I see on my SharePoint Admin Center is:

![image](https://user-images.githubusercontent.com/6519992/42850546-0064a86a-89dd-11e8-83c2-283a9b3e9eb2.png)


**SPFx version: 1.4.1**

Please let me know if you did something different in order to see the API management on SharePoint Admin Center. Thanks!

**Comment by waldekmastykarz** [comment]
@licypal is your tenant on the targeted release for all users?

**Comment by licypal** [comment]
@waldekmastykarz Thanks for your suggestion. It was standard release earlier. I updated it to targeted release for all users and now I am able see approval page. After approval, I ran gulp serve --nobrowser, I get this error: 

![error](https://user-images.githubusercontent.com/6519992/42895136-cc38765c-8a6d-11e8-9c02-a4d268cd37e7.jpg)

On selecting cancel, I get an additional error:

![error 1](https://user-images.githubusercontent.com/6519992/42895162-e5106162-8a6d-11e8-9a09-5647ccffd8b4.JPG)

On selecting OK, the app crashes and refreshes. Please let me know if there are any addtional settings I need to do. Thanks!

**Comment by licypal** [comment]
@waldekmastykarz. Will do, Thanks!

**Comment by licypal** [comment]
@waldekmastykarz I still see the error while running on hosted workbench.

**Comment by waldekmastykarz** [comment]
@licypal thanks for double checking. I suspect we'd need help of someone from the engineering to have a closer look at the issue. @patmill are you around?

**Comment by licypal** [comment]
An update: I tried opening the browser in incognito window. Now, I don't see any error in the console. I see the following:

![aadhttpclient](https://user-images.githubusercontent.com/6519992/43025195-a9a249d8-8c25-11e8-9496-349b37d21e9f.JPG)

![msgraphclient](https://user-images.githubusercontent.com/6519992/43025196-a9c3af56-8c25-11e8-950a-c4121d2e687f.JPG)

**Comment by waldekmastykarz** [comment]
Is it working as expected in private?

**Comment by licypal** [comment]
@waldekmastykarz Any suggestions to resolve this please?

**Comment by VesaJuvonen** [comment]
Hi @licypal, seems that your issue is separate from the issue around permissions/scopes around accessing Microsoft Graph APIs... which means that your issue should be created as a new issue, as we cannot combine issues - makes it hard to assign the issue for specific people as there are different areas. Thanks for submitting your issue as a new one.

**Comment by VesaJuvonen** [comment]
Hi @frnk01, we are looking into to differences and trying to get the scope/permission issue solved asap. Thanks for reporting.

**Comment by frnk01** [comment]
@VesaJuvonen Does this issue mean that there are a problem with every single spfx solution using graph api with the new permission scopes? I'm not sure I understand when this issue occurs. Is there a fundamental issue with the api approval?

**Comment by licypal** [comment]
@VesaJuvonen Created a new issue: https://github.com/SharePoint/sp-dev-docs/issues/2243

Thanks!

**Comment by lahuey** [comment]
There doesn't seem to be an active issue with this thread. Please reopen if you're still facing issues

**Comment by petersgiles** [comment]
I'm facing this issue

**Comment by VesaJuvonen** [comment]
@peterjkrebs - this issue has been closed, so if you have any similar issues, please do open a new issue with the requested details, so that we can help you with it. Thx.
