### ISSUE TITLE
Can't map an array of graph types to a MSGraphClient collection response.

### ISSUE THREAD

**Issue by Toonshorty** [SharePoint/sp-dev-docs#2133]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When mapping a collection response from MSGraphClient ('/groups' for example), you should be able to map the response to a collection/array of the same type.

`.get((error, groups: MicrosoftGraph.Group[]) => { ... });`

#### Observed Behavior

The response from the MSGraphClient wraps the collection inside the 'value' key of an object, rendering the type collection invalid.

You can work around this fairly simply with `const groups: MicrosoftGraph.Group[] = res.value;` but it would be nice to have this working natively either with collection types or having MSGraphClient return the collection directly without an object wrapper.

#### Steps to Reproduce

Make an MSGraphClient call to an endpoint that returns a collection and try to map the response to an array of the type.

**Comment by VesaJuvonen** [comment]
As this is actually in the Graph JS library and not in the SPFx side, we cannot really work for this item in SharePoint side. This means that would recommend opening up an item in the StackOverflow, which Microsoft Graph engineering is looking closely. Here's the right location for that - https://stackoverflow.com/questions/tagged/microsoft-graph. Our MSGraphClient uses the oob Graph JS SDK under the hood for getting arrays. Thanks for your input.
