### ISSUE TITLE
1.5.0/1.5.1 - Sass issue - not compiled to CSS in final package

### ISSUE THREAD

**Issue by val0o** [SharePoint/sp-dev-docs#2136]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a project with a mix of webparts and extensions.
I can build and deploy the solution package.
The package should be correct and apply the styling to my components.

#### Observed Behavior

The Sass classes are not compiled to CSS and my extension does not get its styling applied

#### Steps to Reproduce

I don't know if it's related to the mix of components or only with extensions but:
Have a working extension component with associated Sass class
Deploy with SPFx 1.4.1 ==> OK
Deploy with SPFx 1.5.0 ==>KO

**Comment by val0o** [comment]
poke @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Thanks @val0o, noted and we'll get this triaged soon. Thanks for spitting it to avoid things getting hidden in comments.

**Comment by val0o** [comment]
UP

**Comment by VesaJuvonen** [comment]
@val0o - sorry for the delay. Now - CSS compiling works with normal 1.5 project, so without having access to your solution, we can't really investigate what goes wrong, as the issue seems to be in your solution. Any chance you can share that and also confirm that things work for you if you create a new solution with 1.5.1. Thx.

**Comment by val0o** [comment]
Hi @VesaJuvonen 
Thanks for the follow-up, this is actually a project derived from the tenant global nav sample provided [here](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-application-tenant-global-navbar)
What's specific is only the styling of the nav bar and links, and the fact that this is a project with a mix of webparts and extensions.
Please let me know if these details are not enough.
Thanks for your help

**Comment by val0o** [comment]
Closing the issue... I eventually discovered that the office react fabric used in SPFx >1.4.1 had changed so the generated DOM was not the same for some components and the CSS styles were not applied.
Sorry for the time spent, I hate how office ui fabric does not advise the developers about the updates on their components though 👎

**Comment by VesaJuvonen** [comment]
Thanks, @val0o for following up. We are working with the Fabric team to see if we can change this and provide more structural versioning. No promises at this point, but the challenge is understood and it should be addressed.
