### ISSUE TITLE
Older fabric css linked from workbench

### ISSUE THREAD

**Issue by vvolodin** [SharePoint/sp-dev-docs#214]
Workbench.html links to an old fabric css file - https://appsforoffice.microsoft.com/fabric/2.0.1/fabric.components.min.css

In drop 4 this breaks my ChoiceGroups since some of the newer styles fail to override old fabric CSS.

**Comment by patmill** [comment]
Just to confirm - do you see this in the SharePoint hosted workbench as well, or just the local one?

**Comment by patmill** [comment]
@manishgarg1 , @iclanton - Is there any reason to have the reference to appsforoffice...fabric.components.min.css on the local workbench at all?  Seems like we should be able to just remove it from the workbench.html file.

**Comment by iclanton** [comment]
That reference is there for mobile preview. We can get rid of it as soon as someone fixes the outstanding CSS issues on mobile preview.

**Comment by manishgarg1** [comment]
Yeah, it should get removed.
