### ISSUE TITLE
Calendar Invites For Community Calls Overlap

### ISSUE THREAD

**Issue by polpro** [SharePoint/sp-dev-docs#2149]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

The invites for Dev discussion overlaps with the community call found here:
https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Both show up on Tuesday July 10th at 9am MST.

Edit: I realized I should have logged into the docs website to post this, sorry about that! Don't know how to change it at this point so I don't want to delete it.

![image](https://user-images.githubusercontent.com/39682172/42097685-fbca0158-7b75-11e8-8434-3ecfcc378721.png)

**Comment by VesaJuvonen** [comment]
That first one in your list had a recurrently until June and is no longer valid. Monthly community call which is valid is the one linked from https://aka.ms/sppnp-call. This is again valid until the end of June 2019.

**Comment by polpro** [comment]
Thanks, seemed to be a bug in my outlook, wasn't deleting it properly so I thought it was duplicate. Cleared them all out and readded, works now.
