### ISSUE TITLE
Webpart suddenly disappeared from the modern page and toolbox

### ISSUE THREAD

**Issue by pyranha-ch** [SharePoint/sp-dev-docs#2150]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Weppart shoud be loaded on page and also be available in the toolbox.

#### Observed Behavior
Last week our client side webpart just disappeared from the customers homepage and also from the toolbox (it can't be readded). We didn't change anything in the weppart, it was running like this for a few months.

We updated all dependencies now and build a new package. It is running in the workbench and also on the target page using "?loadSPFX=true&debugManifestsFile=http://localhost:4321/temp/manifests.js"

We successfully uploaded it to the app gallery and deployed it. We could add it to the target site as app in the background. But we cannot add it to the modern page, it does not show up in the toolbox.

**Comment by VesaJuvonen** [comment]
Is there any chance you could share the package for troubleshooting as we can't reproduce the issue and with the given details, we cannot really move forward on troubleshooting this. You can send it using, for example, private messages in MS Tech Community (one option), if you don't want to share that here.

**Comment by pyranha-ch** [comment]
I sent you a private message in the Tech Community containing a link to download the package.

**Comment by pyranha-ch** [comment]
I could solve the issue when i found this issue #775 . Completely removed the package (incl. recycle bin, and site) and reinstalled it. And then it worked.

**Comment by VesaJuvonen** [comment]
Sorry for the delay on this and thanks for following up on the fix.
