### ISSUE TITLE
SPFx app extension - Menu from SharePoint list - Users need permission to see the app

### ISSUE THREAD

**Issue by jtcooper1224** [SharePoint/sp-dev-docs#2151]
Using SPFx App Customizer I'm using a _fetchFromSPList() call to populate a MegaMenu (MM) from a SharePoint list onto modern pages. Site Owner permissions can see the MM from any modern page, list, or library, so no problem there, but users with Member (contribute) permissions and Visitor (read-only) can not see the MM on modern pages, but can see the MM list in Site Contents. 

I created a new permission level and assign it to a test user aiming for only Read access to the MM list. But specifically, the "Manage Lists" checkbox must be selected for this user to see the MM on modern pages.

Within the user's permission level, I've cut off most everything including Add, Edit, and Delete Items, so when visiting the list in Site Contents the user can see the items without editing them, but the 'Manage Lists" permissions gives the user access to the MM List Settings, with access to create new columns and even delete the list.

Why would a user need Manage List permissions to view a SPFx application customizer? 

Troubleshooting Ideas:
On MS docs: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint I've tried placing the &lt;AppPermissionRequests&gt; elements in for scoping rights to the specific web and the specific list, but all of the documentation points to an AppManifest.xml file, which does not exist in my SPFx solution. 

The most similar file in my solution is the package-solution.json file which states the package version and just so happens to have a "webApiPermissionRequests" attribute, but intelecense gives me no options to scope the permissions specifically. Anyone have examples to target my specific list with a permission level to Read access without List Management permission?

Another suspicion is in the Node Modules &gt; sp-pnp-js &gt; lib &gt; sharepoint &gt; lists.d.ts file there's a  ListEnsureResult boolean that being used when I call for my list data using _fetchFromSPList(). I suspect there could be something here that's relying on a permission level not given to all users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33f3f8e-5aaf-4366-a347-a6debe2695f0
* Version Independent ID: 5eb82e36-3b71-b4de-d8d7-58a75b3cd7cc
* Content: [Add-in permissions in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint)
* Content Source: [docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-in-permissions-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by rmillener** [comment]
@jtcooper1224 we have an equivalent menu using spfx 1.4.1/sp-pnp-js 3.0.6 and its working ok. What versions are you using?

Ignoring getting the list items. Does the customiser render at all?

**Comment by VesaJuvonen** [comment]
Can you share the response with the 404 calls when the calls are failing, so that we can investigate what goes wrong? Can you also record a Fiddler trace and share that with us, as that would be really helpful for troubleshooting... or alternatively provide correlation ID and tenant name.

**Comment by VesaJuvonen** [comment]
Closing due to no response, so we can't investigate the root cause.
