### ISSUE TITLE
The standard Top and Bottom placeholders are not available on the Events.aspx page.  

### ISSUE THREAD

**Issue by adambu** [SharePoint/sp-dev-docs#2153]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Customer would like the "modern" Events.aspx page (which seems only to be available on Communication sites) to be able to host an Application Extension footer like other "modern" pages.

#### Observed Behavior
This code does not return an object on the Events.aspx page:
this.context.placeholderProvider.tryCreateContent(PlaceholderName.Bottom);
...but it works on any other Modern page with the exact same code.

#### Steps to Reproduce
Create the HelloWorld tutorial example with top and bottom placeholder content.
Note that it works on every modern page in a Communication site.
Now go to the home page and create an even using the Events web part.
Click to go to the Event details.
Note that the top and bottom placeholder do NOT show up on this page.

Please confirm this is true and comment on whether or not this is something that will be available in future builds.

Thanks for your contribution! Sharing is caring.

**Comment by PooLP** [comment]
Hi,
I don't have this problem on event.aspx page (first release tenant), my header appear, but i have this problem on search page and I still have no answer (https://github.com/SharePoint/sp-dev-docs/issues/1922)

**Comment by qianghuang94** [comment]
Hi @adambu ,
I am sorry that you have run into this problem. However, I couldn't repro the problem with your repro steps. 
With the helloworld project. I successfully customized the events.aspx. as the following screenshot:
![image](https://user-images.githubusercontent.com/15025186/43580245-588a1f1e-9687-11e8-983c-68e09a82c426.png)

![image](https://user-images.githubusercontent.com/15025186/43580316-99c8e2f8-9687-11e8-8595-7044a8aa0dad.png)

If you still have this problem, could you please provide the helloworld project and the debug link you used?

BTW, we do have events.apsx in team sites! Please try it! : )

Thanks.

**Comment by adambu** [comment]
Please don’t close this issue until I can look into this (ASAP).  I am very certain of my results and repro’d with the same specifics on both the hello world and the customer project.  I’ll send you my project, but it’s the same one as the reference project.

I was aware that Events.aspx existed in “modern” Team sites, but I didn’t specifically try that.  Did you try it in a Communication site?

Best regards,
Adam Burns
Sr. Support Escalation Engineer - SharePoint Development
Email: adambu@microsoft.com
Phone: 425-707-2428
Hours: 10:00am-7:00pm Pacific M - F
________________________________

**Comment by AJIXuMuK** [comment]
Sorry for the long delay.
I tested out both Comm and Team sites. `Events.aspx` as well as `Event.aspx` work correctly on both.

**Comment by PooLP** [comment]
Hi, 
We have an expression in France "Better late than never" (I will try to translate it)

I tested and it's ok for me.
