### ISSUE TITLE
Unable to get property 'get_current' of undefined or null reference

### ISSUE THREAD

**Issue by jccastellanos144** [SharePoint/sp-dev-docs#2156]
Unhandled exception at line 3, column 1 in https://&lt;O365INSTANCE&gt;/sites/DevSite/EmployeeOrientation/Scripts/Add-In.js

0x800a138f - JavaScript runtime error: Unable to get property 'get_current' of undefined or null reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e34316f-77a6-e149-4b2e-a1750d0dda6b
* Version Independent ID: dab2b2ca-c529-e970-f6ab-9dc214c81e7f
* Content: [Use the SharePoint JavaScript APIs to work with SharePoint data](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data)
* Content Source: [docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by alecaceaes** [comment]
the sp.js and SP.ClientContext needs to load first. You can do it using SP.SOD.executeFunc.
