### ISSUE TITLE
Reuse Child Component Method to Parent Component Fabric React - SPFx

### ISSUE THREAD

**Issue by shahprashant1990** [SharePoint/sp-dev-docs#2157]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I am using Fabric React with SPFx. I want to use one component public method to another component. **How can be possible to reuse method?**

My Parent Component:

```
export class PanelSmallRightExample2 extends React.Component<
{
...
  public _onShowPanel1()
  {
    alert("other");
  }; 
}
```

Accessing parent method into child:
```
import { PanelSmallRightExample2 } from './PanelExample_1';

let panelExample = React.createElement(PanelSmallRightExample2);
```

**now, by "panelExample" object not accessible my child method.** 

Please help me.

**Comment by rmillener** [comment]
@shahprashant1990 you would normally pass down a callback function via props. 

The [react documentation](https://reactjs.org/docs/faq-functions.html) does a great job of explaining this.
