### ISSUE TITLE
Content search web part converts PublishingImage Url to uppercase, CDN fails

### ISSUE THREAD

**Issue by bjdekker** [SharePoint/sp-dev-docs#2158]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using a content search webpart combined with a Public CDN, I would expect the URL of the image to keep the same casing and to be loaded from the CDN

#### Observed Behavior
When an image is extracted from the PublishingImage field, it is converted to uppercase. It seems that uppercase URL's cannot be loaded from the Public CDN, you get a 504 error.
#### Steps to Reproduce
1. Add an article page to a publishing site collection. 
2. Set the publishing image of the page to an image from a location that is exposed as a public CDN resource
3. Publish the page
4. Add a Content Search Web Part to (another) page and search for the page
5. Select the Picture with 3 lines display template
6. Notice that the images are not showing, the page take ages to load and in the dev tool you get a 504 error on the uppercase image URL's

The conversion to uppercase happens in the Srch.ValueInfo.Renderers.imageSourceRendering function in search.clientcontrols.js
![image](https://user-images.githubusercontent.com/12426259/42172373-147d7f92-7e1c-11e8-9061-c40d5c37475a.png)
Ultimately, the request fails after 4.3 minutes with a 504 error
![image](https://user-images.githubusercontent.com/12426259/42172892-b4893958-7e1d-11e8-9433-fb68ace96805.png)

**Comment by callmedhh** [comment]
Hi, I would like to know that by saying publishing image, do you mean rollup image in article page?

**Comment by qianghuang94** [comment]
We fixed this bug, if everything goes well, it will go to PROD after two weeks. Thanks for reporting.
