### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by elephant-33** [SharePoint/sp-dev-docs#2159]
I followed the directions listed above, but I can't help but wonder if I'm missing something. I notice when I put in the _api/lists/getbytitle('Customer')/items?$select=BdcIdentity,CustomerID,ContactName behind the site and add on name it says "List 'Customer' does not exist at site with URL ..." I created a list on my dev site but that didn't seem to work as well. What am I missing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096828ce-2c2a-d5d1-067a-fb3e3ccb780d
* Version Independent ID: 5225dddd-6c50-b24f-d75e-0ad9a6467a16
* Content: [Access external data by using REST in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint)
* Content Source: [docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This REST query is looking for a list named **Customer** specifically. If you created it using a different name, you need to make sure you use that name.

You see all lists created on the site by entering this query in the browser (once you've logged into the site) to verify you are using the correct list: `_api/lists?$select=Title`
