### ISSUE TITLE
Max expiration date incorrect

### ISSUE THREAD

**Issue by TheJeffer** [SharePoint/sp-dev-docs#2164]
After noticing some unexpected errors, I've discovered that the max expiration date that you can set is actually 180 days from the current date, not 6 months. Trying to set the expiration date to DateTime.Now.AddMonths(6).AddDays(-1) will fail if a couple of the upcoming months have 31 days (i.e., if current date is July 1st).

Works Consistently: DateTime.Now.AddDays(180)
Fails Consistently: DateTime.Now.AddDays(180).AddHours(1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6393d95-8c1d-2341-0cbd-282cd7016204
* Version Independent ID: b7506441-6d16-1689-91aa-e9f45a2bb9e0
* Content: [Overview of SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks)
* Content Source: [docs/apis/webhooks/overview-sharepoint-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/overview-sharepoint-webhooks.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
@TheJeffer I think you've got a good point! I've submitted a fix for this to make it more explicit that it is a 180 days expiration. Thanks!

**Comment by TheJeffer** [comment]
Appreciated, Chris!
