### ISSUE TITLE
404 Not Found Error on calling Graph APIs

### ISSUE THREAD

**Issue by licypala** [SharePoint/sp-dev-docs#2165]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Return all groups in my organization

#### Observed Behavior

![image](https://user-images.githubusercontent.com/6519992/42232213-9516b6b0-7ea2-11e8-8e09-3e0d40118451.png)

#### Steps to Reproduce

- scaffold new project using generator v1.5.1 with a React web part
- import:

```
import { AadHttpClient } from "@microsoft/sp-http";
import { MSGraphClient } from "@microsoft/sp-client-preview";
```

- to the render method add:

```
const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
client
.api('/groups')
.get((error, response: any, rawResponse?: any) => {
console.log(response);
});
```

run gulp bundle and gulp package-solution
deploy the generated package to the app catalog
run gulp serve --nobrowser to start the local web server
add the web part to the hosted (remote) workbench

(These steps are based on a solution from #1774)

- in the console you get the aforementioned error

**Comment by Good-Kamalpandey** [comment]
We have the same issue, I was talking to Microsoft support team and they said Activity.json and Graph APIs path has been deprecated

**Comment by cythomli** [comment]
@Good-Kamalpandey What version of spfx are you using?
