### ISSUE TITLE
SPfx 1.5.1 has no AadHttpClient

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#2166]
import { AadHttpClient, HttpClientResponse } from '@microsoft/sp-http';

[01:31:06] Error - typescript - src/webparts/shk/components/NoticeBoard.tsx(7,10): error TS2305: Module '"/Users/peter/workspace/shk-demo/node_modules/@microsoft/sp-http/dist/index-internal"'has no exported member 'AadHttpClient'.

**Comment by waldekmastykarz** [comment]
AadHttpClient is in preview. If you want to use it, you should use SPFx v1.5.1-plusbeta rather than the regular version. Also, keep in mind, that plusbeta is meant for evaluation purposes and is not supported in production.

**Comment by peterremote1980** [comment]
thank you Sir

**Comment by kannansgit** [comment]
Is this still in Preview?

**Comment by waldekmastykarz** [comment]
It's generally available since v1.6

**Comment by kannansgit** [comment]
Hi, Thanks. Yes, we have upgraded to v1.6. But the aadclient documentation still says it is in preview.

https://docs.microsoft.com/en-us/javascript/api/sp-http/aadhttpclient?view=sp-typescript-latest

**Comment by waldekmastykarz** [comment]
Good catch. It seems like not all of the documentation has been updated. AadHttpClient is publicly available and supported for using in production. See the official announcement at https://developer.microsoft.com/en-us/sharepoint/blogs/announcing-the-release-of-sharepoint-framework-v1-6/

**Comment by kannansgit** [comment]
Thanks Waldek. I had gone through that. 

Also, thank you so much for all the awesome work that you guys do for the sp dev community.

**Comment by waldekmastykarz** [comment]
Thank you for the kind words @kannansgit
