### ISSUE TITLE
SVG base64-encoded image does not work

### ISSUE THREAD

**Issue by vincepunkrock** [SharePoint/sp-dev-docs#2169]
When I use a base64-encoded image, a url is somehow always added before the base64 string. For example "https://publiccdn.sharepointonline.com/XXXXXX/sites/app/ClientSideAssets/10171f51-d1aa-4860-a59c-6f47b47d14f1/data:image/svg+xml;base64,..."
I put the base64 string in "iconImageUrl" just as explained above. Why does it add the url in front of it? When I go in the browser and remove the added url, it shows correctly. Is there something I still do wrong? Any help would be appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ba7b1f-b77a-0076-ed6c-dd84bbc104ea
* Version Independent ID: d7cc472b-1c5b-fd7b-f7dc-6add54dd0886
* Content: [Configure extension icon in SharePoint Framework (SPFx) Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/configure-extension-icon)
* Content Source: [docs/spfx/extensions/basics/configure-extension-icon.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/configure-extension-icon.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Zhephyr54** [comment]
You're doing nothing wrong. This is a bug currently reported : #1909 and #1834.

**Comment by harshdamaniahd** [comment]
@vincepunkrock Pls use png image , it works for me.

**Comment by vincepunkrock** [comment]
@harshdamaniahd You are right it works with a png. However, it would be nice if it would also work with an svg, as stated here: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/configure-extension-icon](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/configure-extension-icon)

Either add the support for svg or correct the documentation. This is currently misleading.

**Comment by harshdamaniahd** [comment]
Done ..voted from my end.
This will help in maintaining consistency across site.

**Comment by PooLP** [comment]
Yes and we will finally have icons compatible with the color themes but as it is on users voice, it will not be before ~3 years :smiling_imp:

**Comment by mcmynn83** [comment]
@vincepunkrock  - I tested an icon as a base 64 encoded image and it works without a prepended internal base url.  Please let me know if you are still experiencing this issue, and if so can you send me your solution.  Thanks!

**Comment by vincepunkrock** [comment]
@mcmynn83 I ended up using a png instead of an svg. But others are still having problems with svg as I can read up here.
Last time I checked, this worked: 
`"iconImageUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEU...`
and this didn't:
`"iconImageUrl": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj...`
A clear answer and or solution would be appreciated :)

**Comment by harshdamaniahd** [comment]
I can confirm that png works, i have no idea about svg.

**Comment by mcmynn83** [comment]
Sorry, not sure how I missed that.  I just validated a icon that happened to be a png.  You are correct, SVG does not work.  I will look into a fix.  Thanks for your patience.

**Comment by mcmynn83** [comment]
A fix will rollout near the start of June for this (we don't roll updates during SharePoint conference).  Thanks!

**Comment by mcmynn83** [comment]
Closing this as it is tracked by #1834.
