### ISSUE TITLE
SharePoint Framework PropertyPane Toggle not working in ie11

### ISSUE THREAD

**Issue by ishanisuchak** [SharePoint/sp-dev-docs#2170]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug

#### Expected or Desired Behavior

The PropertyPaneToggle should show the toggle behavior on all browsers. 

#### Observed Behavior

The PropertyPaneToggle doesn't show the on/off behavior on ie11, but works fine on Chrome and Firefox

#### Steps to Reproduce

Add a PropertyPane toggle in your SPFx solution. 
Create it inside a group that has other PropertyPane controls as well, like sliders and dropdowns.
Check if it shows the toggle behavior in ie11

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Have you reviewed the recently published supported browsers docs here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Pay special attention to the IE11 node for the modern experience & IE's document mode.

If you continue to have the issue, please comment back with some additional context. Thanks!

**Comment by srideshpande** [comment]
@ishanisuchak - Thanks for reporting this issue. Sorry couldn't get back to you earlier. This should have been already fixed. I just tested the toggle control on the property pane and it works.

Please check again. Please feel free to open a new issue, if you still see the same behavior.
