### ISSUE TITLE
Cannot read property 'consume' of undefined when trying to debug a web part using MSGraphClient in the hosted workbench

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-docs#2173]
Hi Team, 

I am going through the issue mentioned here : https://github.com/SharePoint/sp-dev-docs/issues/2045

![image](https://user-images.githubusercontent.com/10346150/42307980-d36c5b3a-8051-11e8-912a-be822ab53462.png)

Could you please let us know if it has been fixed or to be fixed. 

Regards, 
Pavan.

**Comment by srideshpande** [comment]
@pavan2920  - This should have been fixed already. Please re-check. I'm closing this issue. Feel free to open a new one, if you still see this issue.
