### ISSUE TITLE
Content revision required

### ISSUE THREAD

**Issue by jagKakarlapudi** [SharePoint/sp-dev-docs#2174]
you need to update this text under SharePoint Online section above. 

"Includes one team site and the public website. Does not include publishing site functionality. The public website capabilities were designed with small business in mind."

Public sites are not supported in SharePoint Online and are long gone. Unless you have plans to bring them back :-) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28dce46b-a552-800a-621a-efcd6ee41d4e
* Version Independent ID: ea865148-7860-c247-6ae5-454ddb9c60c6
* Content: [Branding and site provisioning solutions for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint)
* Content Source: [docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Markdown formatting issues and doc update required... adding this to my backlog and will get the doc updated. Thanks!
