### ISSUE TITLE
Use Material UI core in SPFx projects

### ISSUE THREAD

**Issue by anupJag** [SharePoint/sp-dev-docs#2175]
I wanted to build webparts using material UI core (which is now available in react). While building (gulp serve) my solution I came across the below errors:
![image](https://user-images.githubusercontent.com/38972668/42320130-dd6bc7ea-8071-11e8-9037-f77c0f178d5b.png)
After searching on the internet for a solution, I came across various blogs pointing to typescript version as the main culprit [refer here](https://github.com/mui-org/material-ui/issues/11496).
Now when I checked the version of typescript which was scaffolded by yeoman builder which is set at 
"@microsoft/gulp-core-build-typescript" > "package.json"
"typescript": "~2.4.1"  

Do I need to do anything from my end to overcome this or should we wait for further release of SPFx versions ?
PS: Since this is something to do with internal settings so not going to touch or modify right now.
#### Category
- [x]Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

You help is much appreciated

**Comment by thechriskent** [comment]
You are correct that the issue of TypeScript is the issue. For the current version of Material UI, ["A minimum version of TypeScript 2.8 is required."](https://material-ui.com/guides/typescript/)

You may be able to use an older version of Material UI Core, but you would need to consult the documentation of that library to find which version may support TypeScript 2.4.1.
