### ISSUE TITLE
.spapp file produced from tutorial `gulp package-solution` is not valid

### ISSUE THREAD

**Issue by bpkennedy** [SharePoint/sp-dev-docs#219]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
After following the steps up to [this tutorial doc](http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page), I expect that the uploaded .spapp file to the App Catalog is valid and able to be deployed.

#### Observed Behavior
 This is not the case, following the tutorial.

#### Steps to Reproduce
Follow tutorial.

**Comment by bpkennedy** [comment]
I've tried multiple ways.  When doing `grunt package-solution` I get no errors in terminal and the files are created.   My package-solution.json shows:

```
{
    "solution": {
        "name": "helloworld-webpart-client-side-solution",
        "id": "ed83e452-2286-4ea0-8f98-c79d257acea5",
        "version": "1.10.2034.2"
    },
    "paths": {
        "zippedPackage": "helloworld-webpart.spapp"
    }
}
```

I tried bumping the version, as well, and every time I `grunt package-solution` it still says it is 0.0.1 and then on upload to the library it is 1.0.0.0.  Still not valid.  What am I missing?  What is not valid?

**Comment by patmill** [comment]
What is the error, and just to double check, are you running this on a developer tenant (not a developer site collection, but a developer tenant).

**Comment by bpkennedy** [comment]
There is no error that I can see.  Gulp package-solution works without an issue.  It's only after uploading to the app catalog that it shows as not valid in the list column.  However no error ever happens that I can see.

I am not sure if it is a developer tenant, but it is a developer template site collection.

**Comment by patmill** [comment]
You currently need to make sure it is a developer tenancy, or the package will be invalid. I suspect that is what you are running into, as this is the first we have heard. We will be expanding the preview in the upcoming weeks, but not quite yet.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by bpkennedy** [comment]
Ah, yes, makes sense.  I also see it here in the first doc, d'oh.  Thought I could skip to the site collection thing.  :)

Out of curiosity, what is the relevant difference here between those types of tenants that the sp app works in one and not the other?

**Comment by patmill** [comment]
So there is currently a block in non-dev tenants that will block the new packages based on their contents.  The reason for this is that we don't want tenants to start rolling out solutions based on a platform that we know is going to be breaking.  

Once the block is removed, you'll be able to install the same .spapp into other tenancy times.  We'll likely start with tenants that have opted in to first release, and we'll make it obvious when the solution is activated that this is pre-release, not supported for production work, highly probable that the solution will break occasionally, etc.

**Comment by bpkennedy** [comment]
Gotcha, makes sense.  Thanks for the context, and can be closed whenever!

**Comment by arutjothi** [comment]
@patmill I'm running into the same problem as @bpkennedy ... I did not sign up specifically for Office Developer program... Roughly before year & half, I had created a provided hosted app and deployed it to the app catalog; also, I do already have a Developer site... Hence, I do believe that mine is a developer tenant... However, I'm unable to find any documentation to validate it ...

**Comment by patmill** [comment]
Chances are it's not a developer tenancy - just a developer site collection - particularly if it is 1.5 years old.  What you'll want to do is make sure you are signed up for first release (it's a setting in tenant admin).  The changes should get their in the next few days.

**Comment by arutjothi** [comment]
@patmill Thought so...Also, I noticed in a random blog that that the developer tenancy is released only for tenants who have signed-up for first release... We did not sign-up for first release because of company policy restrictions... Do you know if signing up for first release would turn on Developer tenancy instantaneously and automatically??

**Comment by arutjothi** [comment]
@patmill Just noticed that we are already signed-up for "First release for selected users"...

**Comment by patmill** [comment]
No, that blog would be incorrect.  First release and Developer tenancy are two different things.  Developer tenancies had limitations on the features and users, etc, and I think expired after a 30 days to 1 year.  

You can go here to get a developer tenant if your company policy prohibits first release - https://profile.microsoft.com/RegSysProfileCenter/wizardnp.aspx?wizid=14b845d0-938c-45af-b061-f798fbb4d170&lcid=1033

**Comment by arutjothi** [comment]
@patmill Just noticed that we are already signed-up for "First release for selected users"... I believe someone from my team might have done this before few months... That means we should have Developer tenancy??
