### ISSUE TITLE
what about lookup fields?

### ISSUE THREAD

**Issue by poloniga** [SharePoint/sp-dev-docs#2190]
Hi. I am trying to add lookup fields into content type, but lookup fields need to specify list id. Ho i can get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Also refer to the `Field` element type docs that has some detail on working with Lookup columns: https://docs.microsoft.com/en-us/sharepoint/dev/schema/field-element-field
