### ISSUE TITLE
npm install fails for sample projects (node-sass)

### ISSUE THREAD

**Issue by rob-windsor** [SharePoint/sp-dev-docs#2194]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

I downloaded a few sample projects from https://github.com/SharePoint/sp-dev-fx-webparts and I'm getting the same error with each of them when I run `npm install`: Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win
32-x64-57_binding.node":

![Error screen capture](https://user-images.githubusercontent.com/5740654/42415037-ff739250-8210-11e8-8a61-9c4caedf821c.JPG)

The sample projects I tried were: jquery-cdn, js-display-list, and knockout-sp-pnp-js.

I got the errors on a machine with node version 8.9.1 and version 1.5.1 of the generator. I'd done very little SPFx development in this machine previously.

I also tried on machine where I had done quite a bit of SPFx development. It has node version 6.10.3 and version 1.4.1 of the generator. In this case the install script found a cached version of the node-sass package so it completed successfully.

![Success screen capture](https://user-images.githubusercontent.com/5740654/42415143-739e814c-8213-11e8-945d-e17379fbf278.JPG)

#### Steps to Reproduce

Clone the jquery-cdn sample project and run `npm install`.

**Comment by StfBauer** [comment]
You miss something essential for your SPFx development. The so-called windows build tools. To verify this is missing execute the following command:

```sh
npm list --dempth=0 windows-build-tools
```

If the result looks like this you know it is missing
```sh
PS C:\tmp\jquery-cdn> npm list --dempth=0 windows-build-tools
jquery-cdn@1.0.0 C:\tmp\jquery-cdn
`-- (empty)
```

Before you can run npm install and install SASS you have to first install 'windows-build-tools' through:

```
npm install -g windows-build-tools
```

Make sure your PowerShell is running as Administrator. Once this installation has been completed you can run the regular npm install.
The root cause is you cannot compile the SASS library yourself because they are not available as a binary download for Windows anymore.
The sample you mentioned is currently sadly a bit outdated but should still work when you apply the code in the sample to the latest generator.

**Comment by DOUGLASMENDES** [comment]
same error but after installing windows-build-tools as mentioned, error persists:

```
PS C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage> npm install --global windows-build-tools

> windows-build-tools@5.2.2 postinstall C:\Programs\Node\v10.16.2-win-x64\node_modules\windows-build-tools
> node ./dist/index.js



Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\CONS248\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.2.2
updated 1 package in 14.103s
PS C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage> npm install
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3

> node-sass@3.13.1 install C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass
> node scripts/build.js

Building: C:\Programs\Node\v10.16.2-win-x64\node.exe C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Programs\\Node\\v10.16.2-win-x64\\node.exe',
gyp verb cli   'C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\which\\which.js:80:29)\n    at C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\which\\which.js:89:16\n    at C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\isexe\\index.js:42:5\n    at C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Programs\Python\2.7.15\python.EXE
gyp verb check python version `C:\Programs\Python\2.7.15\python.EXE -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.2
gyp verb command install [ '10.16.2' ]
gyp verb install input version string "10.16.2"
gyp verb install installing version: 10.16.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.2
gyp verb build dir attempting to create "build" dir: C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Programs\Python\2.7.15\python.EXE
gyp info spawn args [ 'C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\@microsoft\\gulp-core-build-sass\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\CONS248\\.node-gyp\\10.16.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\CONS248\\.node-gyp\\10.16.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\CONS248\\.node-gyp\\10.16.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\@microsoft\\gulp-core-build-sass\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\@microsoft\\gulp-core-build-sass\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\CONS248\.node-gyp\10.16.2
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Programs\\Node\\v10.16.2-win-x64\\node.exe" "C:\\Temp\\Fontes\\sp-dev-fx-webparts-master\\samples\\angular-multipage\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage\node_modules\@microsoft\gulp-core-build-sass\node_modules\node-sass
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CONS248\AppData\Roaming\npm-cache\_logs\2019-08-12T14_26_52_394Z-debug.log
PS C:\Temp\Fontes\sp-dev-fx-webparts-master\samples\angular-multipage>
```

**Comment by manishkaushal2015** [comment]
[Node version 10.19.0]
SP FX version generator-sharepoint@1.10.0

@DOUGLASMENDES  are you able to resolve this issue? 
@StfBauer  I am getting the same issue when installing REACT-CONTENT-QUERY-WEBPART
Any help is extremely appreciated. Below is detailed error log:

`npm install -g windows-build-tools npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> windows-build-tools@5.2.2 postinstall C:\Users\manis\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js
Downloading python-2.7.15.amd64.msi
[>                                    ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\manis\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\manis\.windows-build-tools\vs_BuildTools.exe.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Status from the installers:
---------- Visual Studio Build Tools ----------
2020-04-02T16:06:37 : Verbose : [InstallerImpl]: Rpc connection was closed.
2020-04-02T16:06:37 : Verbose : [InstallerImpl]: Stream was closed
2020-04-02T16:06:37 : Verbose : [SetupUpdaterImpl]: Rpc connection was closed.
2020-04-02T16:06:37 : Verbose : [SetupUpdaterImpl]: Stream was closed
2020-04-02T16:06:38 : Verbose : Restarting the system after an installation operation.
------------------- Python --------------------
Still waiting for installer log file...
Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\manis\.windows-build-tools
Now configuring Python...
All done!
+windows-build-tools@5.2.2
added 144 packages from 98 contributors in 35.408s
PS C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart> npm list --dempth=0 windows-build-tools                                                                                                                    react-content-query-webpart@1.0.11 C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart
-- (empty)
PS C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart> npm clean-install
npm WARN prepare removing existing node_modules/ before installation
[           .......] | extractTree: sill extract string_decoder@1.0.3 extracted to C:\Sample webparts\sp-dev-fx-webparts[           .......] | extractTree: sill extract string_decoder@1.0.3 extr
> phantomjs-prebuilt@2.1.16 install C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt
> node install.js
PhantomJS not found on PATH
Download already available at C:\Users\manis\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\manis\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1586333024608\phantomjs-2.1.1-windows -> C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
> deasync@0.1.11 install C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync
> node ./build.js
C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at findVisualStudio2015 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14)
gyp ERR! stack     at regSearchKeys (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Sample webparts\sp-dev-fx-webparts-master\samples\react-content-query-webpart\node_modules\deasync
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.11 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\manis\AppData\Roaming\npm-cache\_logs\2020-04-08T08_03_53_981Z-debug.log`

**Comment by StfBauer** [comment]
@manishkaushal2015 If you referring to this [web part](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-content-query-webpart/) - First you need to upgrade to the current version or downgrade your version of NodeJS.

This web part was built using SPFx 1.1 which is not supported on NodeJS 10.

Office 365 CLI helps you with this upgrade process to the[ most current SPFx version](https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/).
