### ISSUE TITLE
Confused with the resource name.

### ISSUE THREAD

**Issue by jarkaos** [SharePoint/sp-dev-docs#2195]
Hi,
When it comes to grant permission to the app in the API Administration page I can see the name of the resource (Microsoft Graph) and I can accept or reject the app, great! 
 But what happens if I have two apps using the same resource name for two different purposes, i.ex. one app shows user information and another show calendar events. 
I did a test and both apps works but in the API Administration I just see one resource name (Microsoft Graph) with granted permission for user.read.all and calendar.read . Here is the question: How remove the permission to the app using the calendar.read? I have no way to just disable one permission. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#see-also)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
Unfortunately this is not possible at the moment, at least not using the UI. In the UI, the only option you have, is to remove all permissions and then grant all permissions which you need again. An alternative approach is to use the Office 365 CLI which allows you modify the existing grants to add or remove permissions. More information at https://blog.mastykarz.nl/grant-api-permissions-office-365-without-sharepoint-framework-packages/.
