### ISSUE TITLE
Top and Bottom Placeholders not available on Events.aspx page

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2198]
_From @adambu on July 2, 2018 16:39_

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Sorry, this is a dupe of issue listed under sharepoint/sp-dev-docs, but I couldn't find a way to move the issue.  If one is to be l closed as a dupe, please close the other one, as it seems to belong here.

I need to confirm what I've noticed by debugging, which is that the top and bottom content placeholder is not available on the Events.aspx page.  End user needs the "modern" Events.aspx page (which seems only to be available on Communication sites) to be able to host an Application Extension footer like other "modern" pages.  In many respects this page looks like a "modern" page, but not doesn't seem to allow access to the modern content placeholders.
If this is confirmed, a comment about if and when we think this customization entry point might become available would be most appreciated.

#### Observed Behavior
This code does not return an object on the Events.aspx page:
this.context.placeholderProvider.tryCreateContent(PlaceholderName.Bottom);
...but it works on any other Modern page with the exact same code.

#### Steps to Reproduce
Create the HelloWorld tutorial example with top and bottom placeholder content.
Note that it works on every modern page in a Communication site.
Now go to the home page and create an even using the Events web part.
Click to go to the Event details.
Note that the top and bottom placeholder do NOT show up on this page.

Please confirm this is true and comment on whether or not this is something that will be available in future builds.

Thanks for your contribution! Sharing is caring.

_Copied from original issue: SharePoint/sp-dev-fx-extensions#141_

**Comment by PooLP** [comment]
Same issue on search page result : https://github.com/SharePoint/sp-dev-docs/issues/1922

**Comment by VesaJuvonen** [comment]
This is a duplicate of #2153, so let's close this one...
