### ISSUE TITLE
webApiPermissionRequests : Microsoft Graph Error

### ISSUE THREAD

**Issue by Rani86** [SharePoint/sp-dev-docs#2199]
Bug

Hi Team,

I am not able to deploy successfully when I add webapiPermissionRequest in my manifest .
Could you please help me on this . I need to use  Calendar events in  my application using Microsoft Graph API .

Thanks,
Rani

**Comment by waldekmastykarz** [comment]
What error are you getting? Could you share the exact permission scope snippet?

**Comment by Rani86** [comment]
"webApiPermissionRequests": [{  
            "resource": "Microsoft Graph",  
            "scope": "Calendar.Read"  
        }
When I deploy the code I get "Error in the application"

**Comment by waldekmastykarz** [comment]
Is your tenant on the targeted release?

**Comment by VesaJuvonen** [comment]
If the Error in the application" comes when you add the package to app-catalog, then this indicates that your tenant is not marked to be in Targeted Release. Please confirm that it's case. Notice that the setting has to be on tenant level.
