### ISSUE TITLE
Tutorial 5: cannot find JQuery.module.scss

### ISSUE THREAD

**Issue by dmcrock** [SharePoint/sp-dev-docs#22]
Hello!
Staring Tutorial 5, after building the project and opening in Visual Studio Code, JQuery.WebPart.ts line 8 says "import styles from './JQuery.module.scss';" when hovering over the red squiggles it says [ts] Cannot find module './JQuery.module.scss. Even though I see the JQuery.module.scss file sitting in the src->webparts->jQuery directory. Possible bug?

and just for being thorough..i ran gulp serve (i now there is an error) and this :+1: 
"Error - tslint - src\webparts\jQuery\JQueryWebPart.ts(8,8): error no-unused-variable: unused variable: 'styles''

**Comment by patmill** [comment]
So the tslint error is a warning, and shouldn't affect your build. We need to remove it from the list of rules though. The other issue is a bit strange. Vscode thinks it is an issue, but the build succeeds. 
Bottom line you should be ok to run, but we should clean up the tooling.

**Comment by wictorwilen** [comment]
This is how VS Code works, the `import` statement assumes your file ends with `ts`/`js` and your `scss` file is not yet compiled into a `ts` file. Build the project once and you should be all set.
Also this is a very common issue in VS Code with imports and require - what I regularly do to fix this is *Ctrl-Shift-P > Reload Window* and most of these issues are fixed.

**Comment by dmcrock** [comment]
@patmill @wictorwilen Thank you both!

**Comment by NPrice99** [comment]
Hi
I have had the above errors.  I thought I had fixed them but when I load the workbench I get the following error message :- 

Unable to load web part script resources due to: Error

Any ideas why I am getting this error message ?

**Comment by patmill** [comment]
@NPrice99 - where are you loading the workbench - SharePoint hosted or local hosted?  Which browser are you using?  If you look in the console in the debugging tools, does anything show up there?

Totally agree that "Error" isn't particularly helpful in trouble shooting.

**Comment by NPrice99** [comment]
Hi Pat
I am using gulp serve so local hosted port http://windows:4321/temp/workbench.html.  I am using IE11 fully up to date with patches etc.

In debug console I get :-
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
sp-client-preview.js (18872,18)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
sp-client-preview.js (18872,18)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)
SCRIPT5007: Unable to get property 'htmlProperties' of undefined or null reference
CanvasStore.ts (408,9)


Regards

Nigel

**Comment by nickpape-msft** [comment]
@manishgarg1 @srideshpande  any updates here?

**Comment by nickpape-msft** [comment]
@NPrice99 were you able to get this working properly?

**Comment by NPrice99** [comment]
Hi nickpape

Yes I did get this working properly.

I followed wictor's suggestion and entered gulp serve and it worked.

Regards

Nigel

**Comment by manishgarg1** [comment]
Looks like this is working, Please re-open if there are still pending issues.
