### ISSUE TITLE
PropertyPaneSlider does not work properly

### ISSUE THREAD

**Issue by sudarsanan** [SharePoint/sp-dev-docs#220]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Bug

#### Expected or Desired Behavior
When I add Slider control to the property pane the slider has design issue. Some part of the Slider is hidden.

  groupFields:[
                PropertyPaneTextField('ListName',{label:'ListName',value:'Custom List',description:'Provide the list name'}),
                PropertyPaneSlider('Size',{label:'Size',min:10,max:14}),
                PropertyPaneTextField('Sample',{label:'Sample'})
              ]

#### Observed Behavior
This was created without any JavaScript framework.
![slider](https://cloud.githubusercontent.com/assets/3463983/18999462/bf8243dc-870b-11e6-97a3-2aaabcb6f0a7.png)

#### Steps to Reproduce
Attached the screenshot of the Issue.

**Comment by patmill** [comment]
Not sure if this is Framework, or React Fabric controls.  @srideshpande ?

**Comment by jtlivio** [comment]
```
export interface IStarterWpWebPartPropspropertiesStarter {
  maxitems: string;
}

protected get propertyPaneSettings(): IPropertyPaneSettings {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                 PropertyPaneSlider('maxitems', {
                    label: strings.MaxItemsFieldLabel,
                    max: 5000,
                    min: 100,
                    step: 100,
                    showValue: true
                })
              ]
            }
          ]
        }
      ]
    };
  }

```  
See Interface [here](https://sharepoint.github.io/interfaces/_sp_client_preview_.ipropertypanesliderprops.html)
  
What about if you change to Non Reative? any change?
  
  ```
 protected get disableReactivePropertyChanges(): boolean {
		return true;
	}
```

**Comment by sudarsanan** [comment]
The issue is only with IE, it renders properly in Chrome.

**Comment by srideshpande** [comment]
This is fixed in the existing build. I am closing the issue. Please re-open it if you still can reproduce the issue.
