### ISSUE TITLE
Incorrect DLL and namespace in the example

### ISSUE THREAD

**Issue by alarkvell** [SharePoint/sp-dev-docs#2203]
In "Query using the .NET client object model" chapter:
* "Microsoft.SharePoint.Search.Client.dll" should be "Microsoft.SharePoint.Client.Search.dll".
* "Microsoft.SharePoint.Search.Client.Query" should be "Microsoft.SharePoint.Client.Search.Query".

Taking these changes into account, the example code works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5b1842-4a68-fa28-4caa-aeea30461c08
* Version Independent ID: cbb8a6ea-0766-199b-c328-5a8a8689f2f9
* Content: [Using the SharePoint search Query APIs](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/using-the-sharepoint-search-query-apis)
* Content Source: [docs/general-development/using-the-sharepoint-search-query-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/using-the-sharepoint-search-query-apis.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
PR with a fix merged, so closing this one.
