### ISSUE TITLE
Update Site Script and Site Design Limitations with more detail

### ISSUE THREAD

**Issue by itsknob** [SharePoint/sp-dev-docs#2205]
While the limitations are stated on this page, I don't believe they are thorough enough to allow users to understand the full limitations of Site Designs and Site Scripts.

Current Blurb:
> Also, please note that site scripts are limited to 30 cumulative actions (across one or more scripts that may be called in a site design). This includes subactions.

The below is taken from a comment by @seansquires on the blog post [SharePoint Site Scripts and Site Designs - April 2018 release](https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-Site-Scripts-and-Site-Designs-April-2018-release/ba-p/181254)

> The current limits are as follows: 
> Site Scripts: each script has a 20K character limit. We currently only allow 30 site scripts / tenant, but based on feedback are looking at adjusting this.
> Site Designs: each site design is limited to 30 cumulative actions (this is inclusive of sub-actions). We currently only allow 20 site designs / tenant. We are looking to increase these limits, esp. as the awesome new set of actions requires a higher ceiling.

I also think there should be an indication of what will happen if these limits are surpassed. I've found that exceeding these limits will still allow you to use the template on site creation, but will hang on the Initializing dialog that comes up after creating the site. I do not know, however, if this is always the case. There are no error messages available to the user stating that the Site Script or Site Design will not function properly due to exceeding the limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by rkore85** [comment]
Hi,
This is really sad part to know that we can not add more than 30 cumulative actions and this is why when I was using my site design containing more than 30 actions in single script and it was just showing "Initializing..." nothing else, it does not even give any warnings or errors.

**Comment by iancaro** [comment]
Hi, 
I'm trying to follow this article and was able to do so except for one thing.  The Site Script.  This is my 1st time editing this portion.  I would like to ask your kind assistance to show or tell me how or where I can edit or do this.  I am following this article https://github.com/SharePoint/sp-dev-list-formatting/tree/master/view-samples/document-library

Thanks,
Ian

**Comment by chloegilbert** [comment]
Absolutely agree - the documentation here makes no sense and the section on site scripts actually doesnt contain enough information to get us going.

**Comment by melitoSP** [comment]
The documentation has been updated to reflect the limits for both site scripts and site designs.
