### ISSUE TITLE
SharePoint Native App - deep linking hash/query string parameter?

### ISSUE THREAD

**Issue by butchmarshall** [SharePoint/sp-dev-docs#2206]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Our SPFX webpart reads redirect data from the URL (in the form of either a queryString or hash parameter - doesn't matter) to determine what to display.

We can deeplink in the mobile app to the page our webpart is published on, our webpart properly displays, but window.location.href / window.location.hash both have their parameters stripped by the time our code is finally loaded.

Is it possible to get the queryString/hash data into the native mobile app?

**Comment by VesaJuvonen** [comment]
This is not currently supported, but you can absolutely submit a UserVoice entry for requesting this.
