### ISSUE TITLE
Exclusion test files

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2211]
Which of the following I should you to exclude tests files from build?

build.rig.addPreBuildTask();
build.rig.addPostTypescriptTask();
build.rig.addPostBuildTask();

Also will be the next enough to exclude test files?

let excludeTests = build.subTask('exclude-tests-subtask', function (gulp, buildOptions, done) {
  return gulp.src(['*', '!*.test.*']);
});

let excludeTestsTask = build.task('exclude-tests', excludeTests);
build.rig.addPreBuildTask(excludeTestsTask);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ea7187-d184-a7d7-bee8-eafffc5b2b47
* Version Independent ID: e34bb8a6-c90d-275d-57d9-840534ec46e4
* Content: [Integrate gulp tasks in SharePoint Framework toolchain](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline)
* Content Source: [docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
If you want to exclude tests in a normal build, you should do that within the **tsconfig.json** file, specifically using the `include` and `exclude` properties. Don't think you can do this with gulp tasks or by hooking into the build process as the TypeScript project isn't exposed the way the webpack config is exposed, giving you a chance to customize it prior to running a build.
