### ISSUE TITLE
helloWorld built from microsoft modules @1.1.0 works on local and remote, on-prem workbenches, breaks on remote when upgraded to @1.4.1 OR @1.5.1 - gives error: Failed to load component... Manifest not found for component id...

### ISSUE THREAD

**Issue by Debbledon** [SharePoint/sp-dev-docs#2215]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Please help. 
The traditional helloWorld built from microsoft modules @1.1.0 works on local and remote, on-prem workbenches, breaks on remote when upgraded to @1.4.1 OR @1.5.1 - gives error: Failed to load component... Manifest not found for component id...

I have a new development environment where I have no administrative control and must work through the help desk to troubleshoot anything.  (Just getting NPM to work (for VS Code) on my desktop required an act of congress).  That said, I was finally able to develop a simple web part working well from the (gulp serve) workbench for IE, Chrome, and Firefox.  But I couldn't get it working from our (on-prem) PRE-PROD SharePoint server. 

So, I went back to the basics and (carefully) followed the instructions for building the hello world app with VS Code (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part).  In doing so, I realized I how to get the app running on a remote, on-premise SharePoint workbench. 

When I build it using the ole version (v1.1.0), it will run on both the local (gulp serve) workbench and on the remote (on-prem) workbench. 
THIS WORKS:
PS C:\CODE\helloWorld> npm list --depth=0
hello-world@0.0.1 C:\code\helloWorld
+-- @microsoft/sp-build-web@1.1.0
+-- @microsoft/sp-core-library@1.1.0
+-- @microsoft/sp-lodash-subset@1.1.0
+-- @microsoft/sp-module-interfaces@1.1.1
+-- @microsoft/sp-office-ui-fabric-core@1.4.1
+-- @microsoft/sp-webpart-base@1.1.1
+-- @microsoft/sp-webpart-workbench@1.1.0
+-- @types/chai@3.4.34
+-- @types/es6-promise@0.0.33
+-- @types/mocha@2.2.38
+-- @types/webpack-env@1.13.1
+-- ajv@5.2.5
`-- gulp@3.9.1

I the upgrade the versions of the modules to the latest versions:
after updating versions : 
THIS BREAKS IT:
PS C:\CODE\helloWorld> npm list --depth=0
hello-world@0.0.1 C:\code\helloWorld
+-- @microsoft/generator-sharepoint@1.5.1
+-- @microsoft/sp-core-library@1.5.1
+-- @microsoft/sp-build-web@1.5.1
+-- @microsoft/sp-lodash-subset@1.5.1
+-- @microsoft/sp-module-interfaces@1.5.1
+-- @microsoft/sp-office-ui-fabric-core@1.5.1
+-- @microsoft/sp-webpart-base@1.5.1
+-- @microsoft/sp-webpart-workbench@1.5.1
+-- @types/chai@4.1.4
+-- @types/es6-promise@3.3.0
+-- @types/webpack-env@1.13.6
+-- @types/mocha@5.2.4
+-- @types/es6-promise@0.0.33
+-- ajv@6.5.2
+-- gulp@3.9.1

I actually get the same error from the remote ON-PREM workbench: It is described in: https://github.com/SharePoint/sp-dev-docs/issues/632   There it says it is a server-side error, but does not explain what is needed to be done to fix it. 

THIS IS THE ERROR I AM GETTING FROM THE REMOTE, ON-PREM WORKBENCH:
Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details
***ERROR MESSAGE: ***Failed to load component "3187f7bb-d509-43ba-8c9b-fdf138f56354" (HelloWorldWebPart). Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.5.1". ***CALLSTACK: Error: ***Failed to load component "3187f7bb-d509-43ba-8c9b-fdf138f56354" (HelloWorldWebPart). Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.5.1". at Anonymous function (http://OnPremServer.OurDomain.local/_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:675:105789) at q (http://OnPremServer.OurDomain.local/_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:8:2379) at B (http://OnPremServer.OurDomain.local/_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:8:2467) at Anonymous function (http://OnPremServer.OurDomain.local/_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:8:868) at y (http://OnPremServer.OurDomain.local/_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:8:570)

Issue 632 indicated this was a server-side error (and was already resolved). Since it was over a year ago, I suspect the fix would be included in a fix or Service Pack.  Unfortunately, the issue doesn't go into how it was resolved. Can anyone please tell me? I believe it was referring to the Microsoft-Hosted (Azure) environment. The environment I am in is on-prem and if I'm going to have to ask the server admins to change anything, I will need to be very specific. 

Unfortunately, I have no information about the server and will not be able to get any unless I go to the Admins with something specific. 

Any advise in how I can get this working would be greatly appreciated.
-Like how was https://github.com/SharePoint/sp-dev-docs/issues/632 resolved?

Thank you for your time and consideration!

And thanks for your contribution! Sharing is caring.

**Comment by Debbledon** [comment]
I found a similar, unanswered issue at: Something went wrong in SPFX web part after deployment on SharePoint  https://github.com/SharePoint/sp-dev-docs/issues/1879  it was submitted two months ago and never responded to. I suspect this is probably a simple fix on the server-side. I just don't know what the fix is yet...

**Comment by Debbledon** [comment]
OKAY. I'm going to make this as resolved even though the issue is nto fixed...

"On-premises only supports v1.1" (@VesaJuvonen, 2017). There should be a on-prem update late in 2018 or early 2019, but it has not been released yet. For now, use v1.1.

Related: 

On-Prem: 
* https://github.com/SharePoint/sp-dev-docs/issues/1879
* https://github.com/SharePoint/sp-dev-docs/issues/2215
* https://github.com/SharePoint/sp-dev-docs/issues/1100
* https://github.com/SharePoint/sp-dev-docs/issues/1102
* https://github.com/SharePoint/sp-dev-docs/issues/1075

Similar via SharePoint Online: 
* https://github.com/SharePoint/sp-dev-docs/issues/632
* https://github.com/SharePoint/sp-dev-docs/issues/1920

Same error, but not sure if related:
https://github.com/SharePoint/sp-dev-docs/issues/985


References: 
#1100, #1102, #1075

Per @VesaJuvonen  on Dec 2 2017 
* That is correct, on-premises only supports v1.1 simply release logistics and this is also why there's a separate question on online/on-prem in the Yeoman flow.

* Only v1.1 is supported with SharePoint 2016 Feature Pack 2, like stated in our documentation. We will update the documentation when there will be changes for this. You can expect 1.1 support to remain with SP2016 for now (due server side dependency) and then have newer version supported with SP2019, when that's out later 2018.

Per @VesaJuvonen  on Dec 5 2017 
* Docs related on the SP2016 support are at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support and referenced also in https://dev.office.com/blogs/now-available-deploy-sharepoint-framework-web-parts-to-sharepoint-server-2016-with-feature-pack-2 where this support was announced.

**Comment by cbirts** [comment]
How do I downgrade my current on-prem project from 1.5 to 1.1 to get it to work.

**Comment by Grimnebulin42** [comment]
Is it possible to downgrade the project or do I have to start from scratch? Will 1.4 be supported with SharePoint 2016 at all?

**Comment by katika666** [comment]
Hi all, 
"On-premises only supports v1.1" (@VesaJuvonen, 2017). There should be a on-prem update late in 2018 or early 2019, but it has not been released yet. For now, use v1.1.
as I see nothing change for  SharePoint 19 ?
