### ISSUE TITLE
First block of code to get inventory doesn't work

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/sp-dev-docs#2216]
It looks incomplete: the date field is using get-date, not the date from the credential. I updated something like this:

$applist = Get-MsolServicePrincipal -all  |Where-Object -FilterScript { ($_.DisplayName -notlike "*Microsoft*") -and ($_.DisplayName -notlike "autohost*") -and  ($_.ServicePrincipalNames -notlike "*localhost*") }

"'Name','ID','Address','StartDate','EndDate'" | Out-File c:\temp\appsec.csv

foreach ($appentry in $applist)
{
   $principalId = $appentry.AppPrincipalId
   $principalName = $appentry.DisplayName

   $cred = Get-MsolServicePrincipalCredential -AppPrincipalId $principalId -ReturnKeyValues $false | Where-Object { ($_.Type -ne "Other") -and ($_.Type -ne "Asymmetric") }

   $address = ""
   if($appentry.Addresses.Count -gt 0){
    $address = $appentry.Addresses[0].Address
   }

   $startDate = ""
   $endDate = ""
   if($cred.Count -gt 0){
    $startDate = $cred[0].StartDate
    $endDate = $cred[0].EndDate
   }

   "'$principalName','$principalId','$address','$startDate','$endDate'" | Out-File c:\temp\appsec.csv -append
}

Write-Host "Done!"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not sure what's incorrect in the doc here... you just created a sliding date expiration, where the code in the article uses the current date. Are you saying there's something wrong with that? Seems to me it's just a different approach and not an issue with the doc... correct?
