### ISSUE TITLE
This block doesn't work either

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/sp-dev-docs#2217]
Unsure what this is supposed to do?

$clientId = "27c5b286-62a6-45c7-beda-abbaea6eecf2"
 $keys = Get-MsolServicePrincipalCredential -AppPrincipalId $clientId
 Remove-MsolServicePrincipalCredential -KeyIds @("KeyId1"," KeyId2"," KeyId3") -AppPrincipalId $clientId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Appears it first gets a list of all the keys for the client ID, then removes them one by one (you're supposed to replace `KeyId#` as the previous step specifies.
