### ISSUE TITLE
Unable to close PropertyPane in SharePoint Framework.

### ISSUE THREAD

**Issue by Loevbo** [SharePoint/sp-dev-docs#2218]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question:

In SharePoint Framework I'm able to open the propertyPane by using `this.context.propertyPane.open();`
But it seems there is no way of closing it or is there? Something like `this.context.propertyPane.close();`

I'm sorry if this might be either the wrong place to ask or the wrong way of asking for clarification.

**Comment by srideshpande** [comment]
@Loevbo - Thank you for raising the issue. Yes, this is definitely the place for any SPFx related concerns or issues. 

I just looked at the api and its runtime behavior. I did not see any problems with it. Can you please re-check?

I'm closing the issue. Please feel free to open a new one, if you still see the issue.
