### ISSUE TITLE
Multiple calender?

### ISSUE THREAD

**Issue by americo2015** [SharePoint/sp-dev-docs#2219]
Can this solution show events from multiple calendars? I know that the fullcalendar.js can do that but I can't figure out how to do it in this version? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ecd027-f5ca-48c0-d60c-1883fa24ab96
* Version Independent ID: 9f38cbc9-464a-a2a4-0eeb-4deb6b2eb339
* Content: [Migrate jQuery and FullCalendar solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx#transform-the-plain-javascript-code-to-typescript)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by juliemturner** [comment]
@americo2015 -- Yes sure.  The way you would do that is to collect the information from multiple calendars and then merge them into one data set that you then pass to fullcalendar.js. You could do that in various ways.  If you had a fixed set of calendars you could certainly hard code them.  It might also be really nice to create a property pane that allows the user of the web part to paste in the calendars they want shown. You could also use search api to get calendar events. @sympmarc has a good blog post on this idea [SharePoint Online Search Isn’t Displaying What I Expect – Part 1 – Trimmed Duplicates](https://sympmarc.com/2017/01/09/sharepoint-online-search-isnt-displaying-what-i-expect-part-1-trimmed-duplicates/)  

In the example they're color coding based on person, instead you might color code based on calendar source, thereby making a custom rollup calendar.
