### ISSUE TITLE
API Management is not visible.

### ISSUE THREAD

**Issue by Jonathanval** [SharePoint/sp-dev-docs#2222]
**#### Category
- [X] Question**
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**#### Expected or Desired Behavior**

Hi, I'm trying to install SharePoint Started Kit, the situation is I'm not able to see the the API Management in order to approve the API.

I'm the SharePoint Administrator in Office 365, What type of permissions do I need, to have visibility for the API Management.  

**#### Observed Behavior**

I was following the instructions on 
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/api-management.md

I realize I can't see the API Management option.

**#### Steps to Reproduce**

SharePoint -> SharePoint Admin center -> Try the Preview - "API Management"

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
This means that your tenant is not in the Targeted release mode. You will need to enable this in the tenant admin settings. Notice that change can take up to 24 hours to be visible.
