### ISSUE TITLE
Command line switch missing for diagnostic prompt at end of Yeoman Generator execution

### ISSUE THREAD

**Issue by eshupps** [SharePoint/sp-dev-docs#2226]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Each of the prompts in the Yeoman Generator has a corresponding command line switch, recently updated to use the "--" prefix syntax, as documented at: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.

These command line switches allow for automated execution of the generator, such as that performed by the Visual Studio Extension for SharePoint Framework. With the v1.5.1 release, a new diagnostic feedback message was added at the end of generator execution. This message has no corresponding command line parameter (or such a parameter has not been documented). Inclusion of such a switch would be consistent with existing behavior and allow for continued generator automation.

#### Observed Behavior

Lack of a diagnostic feedback parameter breaks generator automation (refer to Issue 36 in the Visual Studio Extension for SharePoint Framework repo [here](https://github.com/SharePoint/sp-dev-fx-vs-extension/issues/36#issuecomment-403801692)).

#### Steps to Reproduce

Create a new project using v1.5.1 or higher of the Yeoman Generator and preempt the prompts with command line switches. An additional prompt will be displayed at the end of generator execution asking the user if they want to include diagnostic information. There is no corresponding command line parameter for this prompt.   

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by mcmynn83** [comment]
@eshupps  - Sorry, I'm not sure what the prompt for diagnostics information is.  Could you include a screen capture of what you're talking about?

**Comment by VesaJuvonen** [comment]
@eshupps - any change for additional details on this, so that we can solve this. Can you get us a screenshot to understand what's wrong and how that's causing an issue? Thx.
