### ISSUE TITLE
Can't get user image using MSGraphClient

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#2228]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Using MSGraphClient to get user image like so:
```
let graphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
graphClient.api('/me/photo/$value').get().then(response => {
 //response is null
});
```

or using:
```
graphClient.api('/me/photo/$value').getStream((error, response, rawResponse) => {
    //error and response are both undefined
});
```

> The request in the network tab of devtools show it was OK and got the picture. I can see it in the preview.

When using "getSteam" I can see my caller has this code which is wrong:
```
t.prototype.getStream = function(t) {
  var e = this;
  this.config.authProvider((function(r, o) {
    if (null === r && null !== o) {
      var i = e.buildFullUrl();
      t(null, e.configureRequest(n.get(i), o))
     } else
        t(r, null)
  }))
}
```
>the bug is here 'null === r '
>r is undefied, not null.
>Since the check uses === and not == it doesn't go in the first if. If you change the code to == it works well.

#### Observed Behavior

There is no working way to get the image content

#### Steps to Reproduce

try making a request to path 'me/photo/$value' or '/users/xxx/photo/$value'

**Comment by shaipetel** [comment]
I have hacked a workaround to fix this code, making it send null instead of undefined.

here it is in case anyone needs to use getSteam, but this bug should definitely be fixed in the library itself:

```
if (typeof ((<any>request.config).authProvider_org) === 'undefined') {
    (<any>request.config).authProvider_org = request.config.authProvider;
    let newAuthProvider = (callback) => {
        (<any>request.config).authProvider_org.call(request.config, (error, token) => {
            callback(error || null, token);//send null if null or undefined <-- this is the fix.
        });
    };
    request.config.authProvider = newAuthProvider.bind(request.config);
}
```

Not beautiful, but it works well enough so that I can continue testing my code... :)

**Comment by shaipetel** [comment]
...also ... you have to set responseType to blob if you want to get the file content:
```request.responseType('blob');```
and then get it from the xhr.response object:
```
request.responseType('blob');
request.getStream((error, steamPromise) => {
    (<Promise<any>>steamPromise).then((res) => {
        resolve(res.xhr.response);
    }).catch(() => { resolve(null); });
});
```
if you want to get the file data

**Comment by cythomli** [comment]
What SPFx version are you using? Do you have any examples to call other Graph APIs and get a response (not null response)? Thanks!

**Comment by shaipetel** [comment]
@mmsharepoint Yeah, I didn't see that example.

I will try using the raw param from "get" but still - this doesn't change the fact that there is a bug in "getStream".

It does help me for now (provided it works), so thanks!

**Comment by bpringe** [comment]
I'm having a similar issue. I can see the image in the network tab of Chrome dev tools. However, in my msGraphClient request callback, the body stream on the raw response is locked, so I can't get the blob data.
```javascript
this.props.msGraphClient
  .api('me/photo/$value')
  .version('v1.0')
  .responseType('blob')
  .get(async (err, response, rawResponse) => {
    const blob = await rawResponse.blob();
    const blobUrl = window.URL.createObjectURL(blob);
    console.log(blobUrl);
  });

**Comment by pk091990** [comment]
Hi @bpringe 
Could you please help me how to get the Bearer token in the request header of the request made by the msGraphClient or share any link for the reference. Thanks !

**Comment by bpringe** [comment]
@pk091990 You should be able to look at the headers of the request after it's made in the Network tab of Chrome dev tools. There you should find the token. However what I did above was, if I remember correctly, just for demonstration purposes of the issue. It's not a fix.

**Comment by pk091990** [comment]
Hi @bpringe , your solution I've checked by hardcoded (get from console only) that token in my fetch request, but I want was to retrieve that token run time in my solution. Although for that i need to hit 2 calls but I'm not able to create the url and format it using one get call only.

**Comment by bpringe** [comment]
@pk091990 Sorry, I've been out of the SharePoint world for quite some time now so I can't easily try things to help you out. Hope you manage to find something that works for you, though!

**Comment by PiWiBardy** [comment]
Hello, 

Dunno if it help but i was able to achieve to get the photo by this way : 

`this.graphClient.api(['users', upn, 'photo/$value'].join('/')).responseType('blob').get().then(data => { res(data); })`

where data is your blob object.

Regards,
