### ISSUE TITLE
Cognitive Services

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#223]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#spfx, #spfx-webparts

Typing (npm Official) for use Cognitive Services.

Thanks

**Comment by pgonzal** [comment]
It is generally not SPFx's responsibility to provide typings for various services.  Please work with the support team for the service to implement TypeScript typings.  (Alternatively, you could implement them yourself and contribute them to http://definitelytyped.org/. :-) )

**Comment by jtlivio** [comment]
Thanks for the info and link
