### ISSUE TITLE
Is there a TypeScript type (.d.ts) for the window.__themeState__.theme property?

### ISSUE THREAD

**Issue by pschaeflein** [SharePoint/sp-dev-docs#2231]
I need to specify color codes in my code (not CSS) and the window.__themeState__.theme property has exactly what I need.

Is that object described in a TypeScript file (.d.ts)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations?view=sp-typescript-latest)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-theme-colors-in-your-customizations.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
No, there's no type declaration for this property AFAIK...
