### ISSUE TITLE
The IsDefault switch on Add-SPOSiteDesign does not work

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#2236]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
As documented [here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design), it should be possible to add site scripts to a `default` site design (team site/communication site) by providing the `IsDefault` switch to the `Add-SPOSiteDesign` command.

#### Observed Behavior
No matter how I try to use the **Add-SPOSiteDesign** command with the `IsDefault` switch, a new site design always appears in the UI instead of being applied to the default site design. When clicking on the `+Create site` button in the UI and then on the `Team Site` tile,  I get a dropdown asking me to choose a design between **Team Site** and whatever the design I just created 

#### Steps to Reproduce
- Make sure you have a site script in a $script variable
- Run the following command
  ```powershell
  Add-SPOSiteDesign -Title "Default" -Description "Default" -WebTemplate "64" -SiteScripts $script -IsDefault
  ```
- Go in the UI and see that the Team Site definition has not changed, a new one has been created instead.

My **SharePoint Online Management Shell** is currently at version **16.0.7813.1200** (although the PowerShell module does display 16.0.7813.0)

EDIT : After some further testing, it turns out that the site script DOES work on the out of the box `Team Site` site design. The issue seems like a display issue that makes the site design appear in the dropdown even if it has it's `IsDefault` property flagged to true.

I am pretty confident that this is not a normal behavior, I don't see why `Add-SPOSiteDesign` applied with the `IsDefault` switch should make available a NEW site design choice through the UI, on top of modifying the original one.

**Comment by mcmynn83** [comment]
This is not an issue with the developer framework.  You are asking for a bug in a powershell script to be fixed.  Please open up a support ticket through the Office 365 admin center.

**Comment by pdl5p** [comment]
This isn't just a Powershell issue. It also happens when registering site designs using the REST api.

**Comment by spplante** [comment]
Yeah the PowerShell does what it intends to do, so is the REST api. All it is is a display bug from the create site interface, because even thought it displays a new design, your scripts will still be applied to the default design if tou try it, so « it works ».

Their dropdown from the **Create Site** UI shouldn’t show site designs with **IsDefault = true** that’s all.

**Comment by pdl5p** [comment]
Yes I agree. As of this morning, it looks like it has been fixed!

**Comment by spplante** [comment]
Just looked in my tenant and it looks like it is indeed fixed, great news :)
