### ISSUE TITLE
Site Designs : How to retrieve sites created with a specific site design?

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#2237]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question

I was wondering if there was any way to get all SPO sites that have been created using a specific site design? The process in order to update a site design is well documented, the steps required to invoke an updated site design is also documented, but I didn't find any documentation on  how to find the sites that have been created from a specific site design in order to retrofit them with the update site design. This is the step that I am missing : 

[x] Create a site design
[x] Create a site using the site design
[x] Update the site design with another action
[ ] Find all sites created with the site design
[x] Invoke the update site design on each site

Any undocumented info about this?

Thanks!

**Comment by vman** [comment]
I don't believe this is possible with OOB Site Designs right now. A possible workaround is to use the `triggerFlow` action and pass the name of the Site Design as a custom parameter to the Flow as I have done here: https://github.com/vman/Site-Designs/blob/master/Office365.SiteDesigns.Deployment/SiteScripts/site-script-triggerFlow.json#L11 

Then you can either maintain the list of sites and their respective Site Designs, or use the Flow to call an Azure Function which stamps the Site Design into the site property bag.

**Comment by spplante** [comment]
@vman this is exactly what I was thinking about, but for now since we only have site designs applied the default designs (Team Site / Communication Site) I decided to code the retrofit part by looking up get "Template" property of the SPO site.

But yeah as soon we will have custom site designs we will have to store the design in the property bag if nothing has been planned for this.

Thanks!
