### ISSUE TITLE
SP Field Customizer Does not Load on View Change

### ISSUE THREAD

**Issue by j3rowan** [SharePoint/sp-dev-docs#2244]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SP Field Customizer loads on demand when switching to a view that contains the field and the view renders/displays.

#### Observed Behavior

If the initial view loaded contains the custom field then all views that have the custom field render correctly.  However, if the initial view does not contain the custom field then when trying to switch to a view that contains the custom column the view does not load. The view id in the query string changes.  Views without the custom column will load without a problem.

The following console log is written when clicking the view from the drop down:
sp-client module loader promise does not exist

#### Steps to Reproduce

1) Build a field customizer based on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer
2) Deploy solution via Office 365 CDN based on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn
3) Add app to site
4) Add custom column to library, do not add it to the default view
5) Add custom column to a non default view
6) Navigate to default view in modern ui
7) Attempt to switch to the view that contains the custom field

#### Submission Guidelines

None

**Comment by ahackettms** [comment]
We are working on a fix for this issue.

**Comment by RowanAdvisors** [comment]
This appears to have been fixed.

**Comment by AJIXuMuK** [comment]
Sorry for the long delay on the reply here. 
The issue has been fixed.
Feel free to open a new issue if the problem still exists in your environment.
