### ISSUE TITLE
Application customizer extension is not loading intermittently

### ISSUE THREAD

**Issue by amalabey** [SharePoint/sp-dev-docs#2246]
Hi Guys,

We have developed an Application Customizer extension to add a mega-menu to our site (Communications Site). The package is set to "includeClientSideAssets": true and  "skipFeatureDeployment": true. It's then deployed to the Site Collection level app-catalog using Office Dev PnP PowerShell commands. Then, we have registered "Web" level custom action to load the extension. Note that the package contains two extensions (1. Mega Menu, 2. Adds some CSS to the page). We notice the extension is not loaded intermittently. I can't find anything related on the Console log as well. So, I believe SharePoint is not loading the extension intermittently. What could be the cause?

#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Application customizer extension should load consistently on every page load.

#### Observed Behavior
SharePoint does not load the extension intermittently.

#### Steps to Reproduce
1. Created an application customizer extension with below package-solution.json
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "bts-intranet-spfx-solution",
    "id": "c8909876-478d-462b-821f-7baf517681f9",
    "version": "9.0.0.0",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true
  },
  "paths": {
    "zippedPackage": "solution/bts-intranet-spfx-solution.sppkg"
  }
}
```
2. Bundle the JS -> gulp bundle
3. Package the solution -> gulp package-solution
4. Add-PnPApp -Path <path> -SkipFeatureDeployment -Scope Site -Overwrite -Publish
5. Add-PnPCustomAction -Title <extension name> `
            -Name <extension name> `
            -Location "ClientSideExtension.ApplicationCustomizer" `
            -ClientSideComponentId <extension id from manifest>`
            -Scope Web
6. Server js from local -> gulp serve --nobrowser

** Note**: _I have also raised a ticket with Microsoft support but first level support says they don't support SharePoint customisations. I requested to escalate._

**Comment by mcmynn83** [comment]
Please include a correlation ID for the page that loads with and without your extension.  Also, please include the URL of the site that this is from.  At this time is not currently actionable.

**Comment by mcmynn83** [comment]
PS: To get the correlation id look at the response headers and the SPRequestGuid header in the response is the correlation ID.

**Comment by amalabey** [comment]
I've been trying to reproduce this issue. But it doesn't happen anymore. You can close this issue. I will keep an eye and re-open with correlation-id, if I notice it again.
