### ISSUE TITLE
Register CustomAction link to site settings from Element.xml from sppkg

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#2247]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to register CustomAction link to site settings from Element.xml from SPFx package (SPPKG) in **SharePoint Online**?

I am able to create following using Element xml file using SPPKG;

1. Custom Lists with schema
2. Content Types
3. File provisioning to library 

However, when I try adding a link to site settings using following code;

`<CustomActionGroup
		Id="CustomGroup"
		Location="Microsoft.SharePoint.SiteSettings"
		Title="Group"
		Sequence="100"
		Description=""
		 />
<CustomAction
		Id="CustomLinkActionId"
		GroupId="CustomGroup"
		Location="Microsoft.SharePoint.SiteSettings"
		Sequence="1"
		Title="Dashboard"
		Description="Dashboard">
			<UrlAction Url="~appWebUrl/_layouts/15/viewlsts.aspx" />
</CustomAction>`

Above code doesn't execute at all. The new app to be added is just stucks at adding state for a long time and finally breaks with error.

my questions above;

1. Is it possible to add
2. anything is wrong in above code?

**Comment by mcmynn83** [comment]
No this is not currently possible.  The locations are scoped and SiteSettings are not supported.  If you feel this should be in the product please make a feature request in UserVoice.
