### ISSUE TITLE
🐞TS type declaration packages should be in devDependencies, not dependencies

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#2249]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

NPM packages that are not needed for production & only for development, such as TypeScript type declaration files, should only be in the `devDependencies` section of **package.json** within a Node.js project. This means the following two packages should be in `devDependencies`:

- @types/webpack-env
- @types/es6-promise

#### Observed Behavior

The two packages listed above are in the `dependencies` section of **package.json**

#### Steps to Reproduce

Create a SPFx project with v1.5.1 and look at the **package.json** file

**Comment by mcmynn83** [comment]
Thanks for the feedback.  This is not urgent but we have added it to our backlog.

**Comment by andrewconnell** [comment]
Yup... not urgent as it doesn't impact anything, just making things more correct. Accept PR's to the generator and I'll submit the fix ;)

BTW... same comment for React-based projects too. The two React `@types/*` packages should also be moved => `devDependencies`

**Comment by kemesfun** [comment]
Fixed #364075

**Comment by kemesfun** [comment]
This issue has been fixed and will be part of the next update.

**Comment by johnguy0** [comment]
The fix will be included into the next `@microsoft/generator-sharepoint` version.
