### ISSUE TITLE
Custom Field Formatters - Internet Explorer 11 Compatibility Issue

### ISSUE THREAD

**Issue by jonthenerd** [SharePoint/sp-dev-docs#2250]
When using a column formatter, it is expected behavior that the contents of the "cell" will be vertically centered. Looking at the rendered HTML, this is done using CSS flex box. However, in Internet Explorer 11 (a supported browser for SharePoint Online), custom column formatters appear at the top of the "cell" instead of the expected middle positioning.

This can be reproduced using the following syntax within IE11:
`
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/sp/column-formatting.schema.json",
    "elmType": "span",
    "txtContent": "Centered?"
}
`

I believe this is an issue with IE11 and flexbox, but have been unable to work around it with css flexbox alone (got close, but justify-content is not a supported style property in custom column formatters). This is the workaround I'm currently using:

`
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/sp/column-formatting.schema.json",
    "elmType": "div",
    "style": {
        "display": "table"
    },
    "children": [
        {
            "elmType": "div",
            "style": {
                "display": "table-cell",
                "vertical-align": "middle"
            },
            "children": [
                {
                    "elmType": "span",
                    "txtContent": "Centered."
                }
            ]
        }
    ]
}
`

While the above does work, it's definitely not desired/conventional and likely something that the product team could address within the product with some IE specific conditional styles to help the css flexbox properties work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Have you looked at the recently published supported browsers doc here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Specifically, look at the IE11 supported configuration... if your issue is still present after verifying you are using IE11 in a supported config, please update this comment.
