### ISSUE TITLE
missing includeClientSideAssets setting in the package-solution.json file

### ISSUE THREAD

**Issue by bforsyt4** [SharePoint/sp-dev-docs#2251]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

The tutorial (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn) states I should have this setting, but it's missing. If I add it, then gulp bundle --ship errors out and cannot build to deploy to SPO.

If I just leave it as is, I can build and ship, deploy the package to app catalog, but the prompt to trust the app shows the CDN path is missing, although I can still trust it. After, when displaying the web part, get the following exception:

[SPLoaderError.loadComponentError]:
***Failed to load component "98824b2a-8e93-4f79-9221-aec1f7fc3250" (HelloWorldWebPart).
Original error: ***Failed to load path dependency "HelloWorldWebPartStrings" from component "98824b2a-8e93-4f79-9221-aec1f7fc3250" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/98824b2a-8e93-4f79-9221-aec1f7fc3250_0.0.1/HelloWorldWebPartStrings
	Unable to load script -- PATH TO CDN -- /helloworld-webpart-helloworldwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js

I have enabled CDN:
Public CDN enabled locations:
*/MASTERPAGE
*/STYLE LIBRARY
*/CLIENTSIDEASSETS

PS C:\WINDOWS\system32> Get-SPOTenantCdnOrigins -CdnType Public
*/MASTERPAGE
*/STYLE LIBRARY
*/CLIENTSIDEASSETS
PS C:\WINDOWS\system32> Get-SPOTenantCdnEnabled -CdnType Public

Value True

Any thoughts?

Here's my Dev setup:
node v6.14.3
+-- @microsoft/generator-sharepoint@1.5.1
+-- gulp@3.9.1
+-- gulp-cli@2.0.1
+-- iisexpress-proxy@1.3.0
+-- npm@6.1.0
+-- typescript@2.6.1
`-- yo@2.0.4

**Comment by bforsyt4** [comment]
Looks like this is a repeat of Issue #2041

**Comment by bforsyt4** [comment]
Error(s) when running gulp command:

ERROR: Error parsing file 'package-solution.json'
(#/solution) Additional properties not allowed: includeClientSideAssets


[13:38:55] Error - Unknown
 undefined
[13:38:55] ==================[ Finished ]==================
Error - Unknown
 undefined
[13:38:56] Project helloworld-webpart version: 0.0.1
[13:38:56] Build tools version: 2.5.3
[13:38:56] Node version: v6.14.3
[13:38:56] Total duration: 3.2 s
[13:38:56] Task errors: 2

**Comment by bforsyt4** [comment]
re-scaffolded web part in new directory to push to SPO, but still getting original error:

[SPLoaderError.loadComponentError]:
***Failed to load component "6c1ebe8c-e272-4478-a578-fb7f901529cd" (HelloWorldWebPart).
Original error: ***Failed to load path dependency "HelloWorldWebPartStrings" from component "6c1ebe8c-e272-4478-a578-fb7f901529cd" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/6c1ebe8c-e272-4478-a578-fb7f901529cd_0.0.1/HelloWorldWebPartStrings
	Unable to load script /helloworld-webpart-helloworldwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js

**Comment by nikskhubani** [comment]
I too am facing something similar error and logged here: https://github.com/SharePoint/sp-dev-docs/issues/2126 

If we cant load the component, nothing will work :(

**Comment by waldekmastykarz** [comment]
@bforsyt4 could it be that you're trying to deploy the debug version of the solution? What commands are you executing exactly?

**Comment by bforsyt4** [comment]
I am following the steps from here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page

Step 4 states you should see "includeClientSideAssets": true in the package-solution.json file, which I don’t see.

At this step, I have not even packaged the solution.

Thanks!

Brian

**Comment by waldekmastykarz** [comment]
What version of the SharePoint Framework are you using? Are you trying to build a solution for on-prem or online?

**Comment by mcmynn83** [comment]
If you are using on-prem CDN and the include client side assets is not supported.
