### ISSUE TITLE
Paste _renderList() method code first, then _renderListAsync()

### ISSUE THREAD

**Issue by bforsyt4** [SharePoint/sp-dev-docs#2252]
Change steps above to first paste  _renderList() so it's available before _renderListAsync() step - some may hit 'save' and the build fails if you paste in _renderListAsync() first

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
thx bfors, good suggestion and we have changed the order to avoid unnecessary exception in console.
