### ISSUE TITLE
Second extension added to solution not loading

### ISSUE THREAD

**Issue by steevinBradlee** [SharePoint/sp-dev-docs#2254]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I created two extensions in the same solution using the Sharepoint yeoman generator and expected to see both loaded on my SharePoint site

#### Observed Behavior

Only the first extension is being loaded. The second extension is in the dist folder on my local host, but it isn't being requested.

#### Steps to Reproduce

- Create an extension using the yeoman generator.
- Bundle and add your solution to your sharepoint site.
- Create a second extension in the same directory (it will be created in the same solution as the first).
- Run gulp serve and load the site with the solution added to it. Notice that only the first extension is called.

I've obviously missed a step somewhere. Any help would be great :)

**Comment by waldekmastykarz** [comment]
Have you increased the package version number before deploying it to the app catalog?

**Comment by steevinBradlee** [comment]
I don't think so. How do you do that? Do just repackage using gulp package-solution ?

**Comment by steevinBradlee** [comment]
I just updated the version number in package-solution.json to 2.0.0.0, and the version in package.json to 2.0.0, ran gulp package-solution, and uploaded the sppkg file to the file catalog. The second extension is still not being loaded.

**Comment by steevinBradlee** [comment]
config.json

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "branding-application-customizer": {
      "components": [
        {
          "entrypoint": "./lib/extensions/branding/BrandingApplicationCustomizer.js",
          "manifest": "./src/extensions/branding/BrandingApplicationCustomizer.manifest.json"
        }
      ]
    },
    "taco-tray-application-customizer": {
      "components": [
        {
          "entrypoint": "./lib/extensions/tacoTray/TacoTrayApplicationCustomizer.js",
          "manifest": "./src/extensions/tacoTray/TacoTrayApplicationCustomizer.manifest.json"
        }
      ]
    }
  },
  "externals": {},
  "localizedResources": {
    "BrandingApplicationCustomizerStrings": "lib/extensions/branding/loc/{locale}.js",
    "TacoTrayApplicationCustomizerStrings": "lib/extensions/tacoTray/loc/{locale}.js"
  }
}

package-solution.json

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "modern-intranet-client-side-solution",
    "id": "40d09470-6d39-4e0a-a350-1e0ed1ffbe68",
    "version": "2.0.0.0",
    "includeClientSideAssets": true,
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "cc199cee-ba19-436a-9391-5a19d46a1780",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml"
          ]
        }
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/modern-intranet.sppkg"
  }
}


package.json

{
  "name": "modern-intranet",
  "version": "2.0.0",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.5.1",
    "@microsoft/decorators": "1.5.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33",
    "@microsoft/sp-dialog": "1.5.1",
    "@microsoft/sp-application-base": "1.5.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.5.1",
    "@microsoft/sp-module-interfaces": "1.5.1",
    "@microsoft/sp-webpart-workbench": "1.5.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by VesaJuvonen** [comment]
Hi @steevinBradlee - please note that by default we do not add additional provisioning entry to the element.xml files when you add more extensions on the same solution. This would explain that you only see one extension in a site when the solution is being installed. You can, however, edit the xml files manually to add the needed entry in. This behavior is by design to avoid us overriding any edits which you might have done in complex solutions Can you confirm that you got this to work after manual edit?

**Comment by VesaJuvonen** [comment]
Closed due to no response within 14 days of asking.
