### ISSUE TITLE
Extension not always working as expected

### ISSUE THREAD

**Issue by anasnakawa** [SharePoint/sp-dev-docs#2255]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The extensions inside SPFx solution should be registered on each of the SharePoint Modern Experience pages from CDN where CORS is already enabled. 

#### Observed Behavior
We are facing strange issues with the extensions. When we try to load the extensions we get following error in console;

[Logs.txt](https://github.com/SharePoint/sp-dev-docs/files/2209868/Logs.txt)

Here is an image for it;

![spfx extension not loading](https://user-images.githubusercontent.com/29400321/42932512-18088a84-8b60-11e8-9290-fbb803860408.gif)

One more point to note here is the extensions are loaded in site content page (Modern Experience) always but on all rest pages, they are not loaded.

#### Steps to Reproduce

* Create an extension using the yeoman generator.
* Register it in `package-solution.json`
* Deploy the files to CDN (specifically Amazon S3 bucket)
* Ensure the CORS is enabled for get request
* Bundle and add your solution to your sharepoint site.
* As soon as you add the solution you will notice the extensions are ONLY loading on Site content and not to other pages.

**Comment by waldekmastykarz** [comment]
Are you sure that CORS is correctly configured? Looking at the headers, it doesn't seem to be present in the response.

**Comment by anasnakawa** [comment]
Thanks @waldekmastykarz appreciate your response,
Updating our CORS settings did solve the issue.

**Comment by waldekmastykarz** [comment]
Thanks for confirming! Good to hear it's working!
