### ISSUE TITLE
Visual Studio Code error

### ISSUE THREAD

**Issue by apruzzr** [SharePoint/sp-dev-docs#2256]
Unable to load schema from 'https://developer.microsoft.com/en-us/json-schemas/sp/column-formatting.schema.json': &lt;!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"&gt; 
&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt; 
&lt;head&gt; 
&lt;title&gt;IIS 10.0 Detailed Error - 404.0 - Not Found&lt;/title&gt; 
&lt;style type="text/css"&gt; 
&lt;!-- 
body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} 
code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} 
.config_source code{font-size:.8em;color:#000000;} 
pre{margin:0;font-size:1.4em;word-wrap:break-word;} 
ul,ol{margin:10px 0 10px 5px;} 
ul.first,ol.first{margin-top:5px;} 
fieldset{padding:0 15px 10px 15px;word-break:break-all;} 
.summary-container fieldset{padding-bottom:5px;margin-top:4px;} 
legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} 
legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; 
font-weight:bold;font-size:1em;} 
a:link,a:visited{color:#007EFF;font-weight:bold;} 
a:hover{text-decoration:none;} 
h1{font-size:2.4em;margin:0;color:#FFF;} 
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} 
h4{font-size:1.2em;margin:10px 0 5px 0; 
}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif; 
 color:#FFF;background-color:#5C87B2; 
}#content{margin:0 0 0 2%;position:relative;} 
.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} 
.content-container p{margin:0 0 10px 0; 
}#details-left{width:35%;float:left;margin-right:2%; 
}#details-right{width:63%;float:left;overflow:hidden; 
}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; 
 background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; 
 font-size:1em;color:#FFF;text-align:right; 
}#server_version p{margin:5px 0;} 
table{margin:4px 0 4px 0;width:100%;border:none;} 
td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} 
th{width:30%;text-align:right;padding-right:2%;font-weight:bold;} 
thead th{background-color:#ebebeb;width:25%; 
}#details-right th{width:20%;} 
table tr.alt td,table tr.alt th{} 
.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} 
.clear{clear:both;} 
.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} 
--&gt; 
&lt;/style&gt; 
 
&lt;/head&gt; 
&lt;body&gt; 
&lt;div id="content"&gt; 
&lt;div class="content-container"&gt; 
  &lt;h3&gt;HTTP Error 404.0 - Not Found&lt;/h3&gt; 
  &lt;h4&gt;The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.&lt;/h4&gt; 
&lt;/div&gt; 
&lt;div class="content-container"&gt; 
 &lt;fieldset&gt;&lt;h4&gt;Most likely causes:&lt;/h4&gt; 
  &lt;ul&gt; 	&lt;li&gt;The directory or file specified does not exist on the Web server.&lt;/li&gt; 	&lt;li&gt;The URL contains a typographical error.&lt;/li&gt; 	&lt;li&gt;A custom filter or module, such as URLScan, restricts access to the file.&lt;/li&gt; &lt;/ul&gt; 
 &lt;/fieldset&gt; 
&lt;/div&gt; 
&lt;div class="content-container"&gt; 
 &lt;fieldset&gt;&lt;h4&gt;Things you can try:&lt;/h4&gt; 
  &lt;ul&gt; 	&lt;li&gt;Create the content on the Web server.&lt;/li&gt; 	&lt;li&gt;Review the browser URL.&lt;/li&gt; 	&lt;li&gt;Create a tracing rule to track failed requests for this HTTP status code and see which module is calling SetStatus. For more information about creating a tracing rule for failed requests, click &lt;a href="http://go.microsoft.com/fwlink/?LinkID=66439"&gt;here&lt;/a&gt;. &lt;/li&gt; &lt;/ul&gt; 
 &lt;/fieldset&gt; 
&lt;/div&gt; 
 
&lt;div class="content-container"&gt; 
 &lt;fieldset&gt;&lt;h4&gt;Detailed Error Information:&lt;/h4&gt; 
  &lt;div id="details-left"&gt; 
   &lt;table border="0" cellpadding="0" cellspacing="0"&gt; 
    &lt;tr class="alt"&gt;&lt;th&gt;Module&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;IIS Web Core&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr&gt;&lt;th&gt;Notification&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;MapRequestHandler&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr class="alt"&gt;&lt;th&gt;Handler&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;StaticFile&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr&gt;&lt;th&gt;Error Code&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;0x80070002&lt;/td&gt;&lt;/tr&gt; 
     
   &lt;/table&gt; 
  &lt;/div&gt; 
  &lt;div id="details-right"&gt; 
   &lt;table border="0" cellpadding="0" cellspacing="0"&gt; 
    &lt;tr class="alt"&gt;&lt;th&gt;Requested URL&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;http://localhost:80/json-schemas/sp/column-formatting.schema.json&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr&gt;&lt;th&gt;Physical Path&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;C:\inetpub\wwwroot\json-schemas\sp\column-formatting.schema.json&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr class="alt"&gt;&lt;th&gt;Logon Method&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;Anonymous&lt;/td&gt;&lt;/tr&gt; 
    &lt;tr&gt;&lt;th&gt;Logon User&lt;/th&gt;&lt;td&gt;&nbsp;&nbsp;&nbsp;Anonymous&lt;/td&gt;&lt;/tr&gt; 
     
   &lt;/table&gt; 
   &lt;div class="clear"&gt;&lt;/div&gt; 
  &lt;/div&gt; 
 &lt;/fieldset&gt; 
&lt;/div&gt; 
 
&lt;div class="content-container"&gt; 
 &lt;fieldset&gt;&lt;h4&gt;More Information:&lt;/h4&gt; 
  This error means that the file or directory does not exist on the server. Create the file or directory and try the request again. 
  &lt;p&gt;&lt;a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,0,0x80070002,14393"&gt;View more information &raquo;&lt;/a&gt;&lt;/p&gt; 
   
 &lt;/fieldset&gt; 
&lt;/div&gt; 
&lt;/div&gt; 
&lt;/body&gt; 
&lt;/html&gt; 

That's the error message I get when I follow your instructions to the letter: I made a new file, saved it with a .json ending, and pasted exactly this:
{
 "$schema": "https://developer.microsoft.com/en-us/json-schemas/sp/column-formatting.schema.json"
 }

Visual Studio Code is up to date - installed TODAY. Made 0 deviations from your prescribed instructions. Fix it now, please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#creating-custom-json)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Looks like the schema link we provide in the documentation is pointing to a localized version (en-us), but that link now redirects to a more universal schema address (as makes sense).

Here is the schema link you should use within VS Code:
```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json"
}
```

I've submitted a pull request on the documentation to get this updated. Thanks for catching this!

As a side note, there is a webpart from PnP that is far easier to write column formatting in than VS Code available here: https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ColumnFormatter
