### ISSUE TITLE
Deploy extension on Site Collection level

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/sp-dev-docs#2260]
I have created an extension & want to deploy on site collection level. I mean after adding this extension to site collection, this extension should be added in all sub sites and new sub sites.

Please help me to achieve this goal.

Thanks & Regards,
Gaurav Goyal

**Comment by VesaJuvonen** [comment]
You can do this by adding an entry to the UserCustomAction collection of the site collection. This cannot be done with the feature xml inside of the solution, but it can be done using APIs. After 1.6 release, you can also target extension to be available based on site types from the app catalog.
