### ISSUE TITLE
Logging API does not work in ListView Command set

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#2261]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In a list view command set, the Log methods should write information to the console.
#### Observed Behavior
In a list view command set, the Log methods do not write information to the console.

#### Steps to Reproduce
import { Log } from '@microsoft/sp-core-library';
Create a list view command set and add this to the onInit method (or any other method)
Log.error("HelloWorld", new Error("Oh No!  Error!  Ahhhhhh!!!!"), this.context.serviceScope);
   
SPFX Version is 1.4.1,
Nothing us written to the log.  It seems that no handlers are registered

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
@russgove - Sorry for the delay on this. Can you also test this with the 1.6 version as we have been fixing things on this area. This should work now properly.  Logging class logs does not add anything on Console, but it's adding things to the Ctrl+12 console - see following - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-developer-dashboard.

Are we good or can we close this or?

**Comment by VesaJuvonen** [comment]
Closing due no response.
