### ISSUE TITLE
NPM dependancies disappeared (?)

### ISSUE THREAD

**Issue by nyannios** [SharePoint/sp-dev-docs#2263]
#### Category
- [ ] Question
- [ ] Typo
- [?] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I created a SharePoint Framework (SPFX) project using the Visual Studio 2017 SPFX extension.   
Initially npm list showed all [dependencies](url) but now a number of them are showing up as missing

#### Observed Behavior

NPM list shows these dependencies missing

TMXL7283BFP::C:\Users\nyannios\source\repos\MySPFxProject1\MySPFxProject1> npm list --depth=1
my-sp-fx-project-1@0.0.1 C:\Users\nyannios\source\repos\MySPFxProject1\MySPFxProject1
+-- @microsoft/sp-build-web@1.5.1
| +-- @microsoft/gulp-core-build@3.7.4
| +-- @microsoft/gulp-core-build-karma@4.5.0
| +-- @microsoft/gulp-core-build-sass@4.3.14
| +-- @microsoft/gulp-core-build-serve@3.2.26
| +-- @microsoft/gulp-core-build-typescript@4.9.7
| +-- @microsoft/gulp-core-build-webpack@3.4.0
| +-- @microsoft/sp-build-common@1.5.1
| +-- @microsoft/sp-build-core-tasks@1.5.1
| +-- @microsoft/sp-polyfills@1.5.1
| +-- @types/karma@0.13.33
| +-- @types/tapable@0.2.4
| +-- @types/webpack@3.0.11
| +-- gulp@3.9.1 deduped
| +-- webpack@3.6.0
| `-- yargs@4.6.0
+-- @microsoft/sp-core-library@1.5.1
| +-- @microsoft/sp-lodash-subset@1.5.1
| +-- @microsoft/sp-module-interfaces@1.5.1 deduped
| +-- @types/es6-promise@0.0.33
| `-- @types/webpack-env@1.13.1
+-- @microsoft/sp-lodash-subset@1.5.1
| +-- @types/lodash@4.14.74
| +-- @types/webpack-env@1.13.1
| `-- tslib@1.8.1
+-- @microsoft/sp-module-interfaces@1.5.1
| +-- @types/node@8.5.8
| +-- @types/z-schema@3.16.31
| `-- z-schema@3.18.4
+-- @microsoft/sp-office-ui-fabric-core@1.5.1
| +-- @types/webpack-env@1.13.1
| +-- office-ui-fabric-core@9.1.0
| `-- tslib@1.8.1 deduped
+-- @microsoft/sp-webpart-base@1.5.1
| +-- @microsoft/decorators@1.5.1
| +-- @microsoft/load-themed-styles@1.7.53
| +-- @microsoft/office-ui-fabric-react-bundle@1.5.1
| +-- @microsoft/sp-component-base@1.5.1
| +-- @microsoft/sp-core-library@1.5.1 deduped
| +-- @microsoft/sp-diagnostics@1.5.1
| +-- @microsoft/sp-dynamic-data@1.5.1
| +-- @microsoft/sp-http@1.5.1
| +-- @microsoft/sp-loader@1.5.1
| +-- @microsoft/sp-lodash-subset@1.5.1 deduped
| +-- @microsoft/sp-module-interfaces@1.5.1 deduped
| +-- @microsoft/sp-page-context@1.5.1
| +-- @types/es6-promise@0.0.33
| +-- @types/react@15.6.6
| +-- @types/react-dom@15.5.6
| +-- @types/webpack-env@1.13.1
| +-- office-ui-fabric@2.6.1
| +-- office-ui-fabric-react@5.83.0
| +-- react@15.6.2
| +-- react-dom@15.6.2
| `-- tslib@1.8.1 deduped
+-- @microsoft/sp-webpart-workbench@1.5.1
| +-- @microsoft/gulp-core-build-serve@3.2.26 deduped
| +-- @microsoft/node-core-library@1.2.0
| +-- @microsoft/office-ui-fabric-react-bundle@1.5.1 deduped
| +-- @microsoft/sp-application-base@1.5.1
| +-- @microsoft/sp-build-core-tasks@1.5.1 deduped
| +-- @microsoft/sp-client-preview@1.5.1
| +-- @microsoft/sp-core-library@1.5.1 deduped
| +-- @microsoft/sp-loader@1.5.1 deduped
| +-- @microsoft/sp-lodash-subset@1.5.1 deduped
| +-- @microsoft/sp-module-interfaces@1.5.1 deduped
| +-- @microsoft/sp-webpart-base@1.5.1 deduped
| +-- @types/es6-promise@0.0.33 deduped
| +-- @types/fs-extra@0.0.37
| +-- @types/react@15.6.6 deduped
| +-- @types/react-dom@15.5.6 deduped
| +-- @types/webpack-env@1.13.1 deduped
| +-- fs-extra@0.26.7
| +-- office-ui-fabric-react@5.83.0 deduped
| +-- prop-types@15.5.7
| +-- react@15.6.2 deduped
| +-- react-dom@15.6.2 deduped
| `-- tslib@1.8.1 deduped
+-- @types/chai@3.4.34
+-- @types/es6-promise@0.0.33
+-- @types/mocha@2.2.38
+-- @types/webpack-env@1.13.1
+-- ajv@6.5.2
| +-- fast-deep-equal@2.0.1
| +-- fast-json-stable-stringify@2.0.0
| +-- json-schema-traverse@0.4.1
| `-- uri-js@4.2.2
+-- brace-expansion@1.1.11
| +-- balanced-match@1.0.0
| `-- concat-map@0.0.1
+-- gulp@3.9.1
| +-- archy@1.0.0
| +-- chalk@1.1.3
| +-- deprecated@0.0.1
| +-- gulp-util@3.0.8
| +-- interpret@1.1.0
| +-- liftoff@2.5.0
| +-- minimist@1.2.0
| +-- orchestrator@0.3.8
| +-- pretty-hrtime@1.0.3
| +-- semver@4.3.6
| +-- tildify@1.2.0
| +-- v8flags@2.1.1
| `-- vinyl-fs@0.3.14
+-- gup@1.1.1
| `-- shelljs@0.3.0
+-- minimatch@3.0.4
| `-- brace-expansion@1.1.11 deduped
+-- minimist@0.0.8
+-- mkdirp@0.5.1
| `-- minimist@0.0.8
`-- safe-buffer@5.1.2

**npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0**

#### Steps to Reproduce

I am not sure what introduced this issue.    It had previously shown all dependencies with no errors

Thank you
Nikos

**Comment by VesaJuvonen** [comment]
We would need more details on the exact SPFx VS extension version which you have installed so that we can potentially reproduce this issue. VS extension uses also oob Yeoman under the hood, so unless we can reproduce this natively with Yeoman version, we can't really fix this. Would recommend using Yeoman for scaffolding to see if that reproduces and provide more environment details with us. Which node, npm and VS extension version you have?

**Comment by VesaJuvonen** [comment]
Closed due to no response on the request for additional details.
