### ISSUE TITLE
Using one variable for all task outcomes

### ISSUE THREAD

**Issue by distinctapp** [SharePoint/sp-dev-docs#2265]
Is it advisable to use just one variable (for example "Outcome") to store all task outcomes in a workflow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d439d3ec-72bc-56de-c384-ffbb786ca408
* Version Independent ID: 2b4f5a2e-397b-1c43-5e6f-30dd6252bd8e
* Content: [Understanding Task Actions in SharePoint Designer 2013](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-task-actions-in-sharepoint-designer)
* Content Source: [docs/general-development/understanding-task-actions-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/understanding-task-actions-in-sharepoint-designer.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Generally speaking, workflows only have one result and that's what's returned as the result of the workflow task. If you have multiple _output_ (not outcomes) from your workflow, you can put those in different fields in the associated list. Typically people only have one outcome though...
