### ISSUE TITLE
How to work with Jest and AMD Modules?

### ISSUE THREAD

**Issue by christianbueschi** [SharePoint/sp-dev-docs#2269]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Problem: 
Jest doesn't officially support requirejs.

#### Question
How should we test a Webpart which has a dependency to an amd module (i.e. [PeoplePicker](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/)) with Jest framework? 

[Test Reference Example](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-jest-testing) 

#### Use Case
Webpart which imports the React PeoplePicker. Test fails with error `Cannot find module 'ControlStrings' from 'PeoplePickerComponent.js'`

##### JestTestWebPart.ts
```
import * as React from 'react';
import { PeoplePicker } from "@pnp/spfx-controls-react/lib/PeoplePicker";

export default class JestTest extends React.Component<any, any> {
	public render(): React.ReactElement<any> {
		return (
      		<div>
			<h1>People Picker</h1>
			<PeoplePicker context={null} titleText="Title" />
      		</div>
    	);
  }
}
```

##### jestTest.test.ts
```
/// <reference types="jest" />

import * as React from 'react';
import { configure, mount, ReactWrapper } from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-15';
import JestTest from '../components/JestTest';

configure({ adapter: new Adapter() });

describe('Enzyme basics', () => {
    let reactComponent: ReactWrapper<any, any>;
    
   beforeEach(() => {
        reactComponent = mount(React.createElement(JestTest));
    });

    it('should has the correct title', () => {
        let cssSelector: string = 'h1';
        
        const text = reactComponent.find(cssSelector).text();
        
        expect(text).toBe("People Picker");
    });
});
```

**Comment by christianbueschi** [comment]
So, I'm going to answer my question by myself: 
As a workaround we mock components which can not be handled by jest.

Example: Mock PeoplePicker
```
jest.mock('@pnp/spfx-controls-react/lib/PeoplePicker', () => 'PeoplePicker');
```

And then use the ShallowWrapper from enzyme:
```
let reactComponent: ShallowWrapper<any, any>;
...
reactComponent = shallow(<JestTest/>);
```

This leads to a bunch of mocks but works in our case. 
Hopefully Jest would support AMD Modules soon and spfx react 16 ;-)

**Comment by VesaJuvonen** [comment]
thanks, @christianbueschi for following up with the answer as well, so closing this one.
