### ISSUE TITLE
Cannot POST to web api secured with Azure AD

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#2271]
Hi, I have a web-api hosted in azure and secured with azure AD as described here. GET commands work fine, but POST commands return a 403.  chenking the logs for the web-api site I see the error :
Cross-site request forgery detected for user '' from referer 'somesite.sharepoint.com

This was also noted at https://www.reddit.com/r/sharepoint/comments/8dam9w/cant_post_to_web_api_secured_with_azure_ad_from/ 
and at 
https://stackoverflow.com/questions/49909192/azure-web-api-is-throwing-cross-site-request-forgery-detected-for-user-for-pos

In both cases the OP said it was resolved by moving the authentication code into their web-api code and trurning off the azure Authentication, bit i cannot find documentation on how to do that.

Can we get that included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064cdc5a-e118-ceab-c42b-ae06ae3297c6
* Version Independent ID: 95afcc6d-fd0b-90a0-5775-4871869abc83
* Content: [Connect to API secured with Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad)
* Content Source: [docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That doesn't seem to be an issue with SPFx though... so seems out of scope for the SPFx docs IMHO...
