### ISSUE TITLE
Changes to lookup field persisting order in modern experience

### ISSUE THREAD

**Issue by tarjeieo** [SharePoint/sp-dev-docs#2272]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a lookup field to another list. The order i pick the lookup items in is important, I use this order in a module in my site. In both classic view and up until recently in modern, the order the lookoup items are persisted in, matches the order they are selected. 

#### Observed Behavior

Today I observed that in modern list experience, in the edit form, the order I select the lookup items in is ignored upon save, and saved alphabetically always. While this might make sense in some cases, the behavior in SharePoint has always been that the order that is persisted reflects the order of selection.

I can actually see a short glimpse of the reordering happen as soon as I save the form.

#### Steps to Reproduce

Create two lists, list A and list B. In list B, create a lookup column to point to list A. Observe that when selecting items from list A, the order the items are saved in is alphabetical, and not the order they are selected in.

Before saving the form:
![image](https://user-images.githubusercontent.com/1837390/43123862-c3c517a2-8f25-11e8-9967-ed7fc4d09deb.png)

After saving the form:
![image](https://user-images.githubusercontent.com/1837390/43123884-d44e8414-8f25-11e8-8967-86f15b55a3f5.png)

**Comment by VesaJuvonen** [comment]
As this is not a development issue, we cannot really fix this in our side. Sure - this is inconvenient and it would make sense not always do alphabetical order, but its more a feature request or an end users issue, which can be reported through the normal SharePoint Online support channels. We cannot, unfortunately, route this comment to the right people from here, so closing it.
