### ISSUE TITLE
Slight addition to the setup notes

### ISSUE THREAD

**Issue by HuwSy** [SharePoint/sp-dev-docs#2273]
If using node portable the %PATH% must be  setup for the npm installs to work, i.e. set PATH=%PATH%&lt;...&gt;;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This isn't specific to SPFx, it's more of a specific aspect to running / installing Node in a way that differs from the supported approach provided in the docs. I'm going to close this as there's no real action to take in the docs here.
