### ISSUE TITLE
Unable to Debug in Chrome or Edge

### ISSUE THREAD

**Issue by iamscottm** [SharePoint/sp-dev-docs#2276]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Setup environment as described by the documentation and followed tutorial for generating helloworld webpart….  Expect to be able to configure debug through Edge using the extension and documented setup....  After much trial/error and research on this site I am posting an issue.

#### Observed Behavior
Depending on how gulp serve is started I get one of two outcomes:

Debugger Output: Error handling message from target: Invalid message: {"id":0,"result":{}}

#### Steps to Reproduce
Setup your dev environment per the documentation;  Isntall Edge Debugger or Chrome Debugger extensions.
Create a Basic HelloWorld webpart using latest Yeoman generator. 
Add workspace config for debug.
Ensure all NPM packages are updated/installed
Set a break point
Run set NODE_NO_HTTP2=1&& gulp serve --nobrowser

Try launching from debug menu or
MicrosoftEdge.exe --devtools-server-port 9222 https://localhost:4321/temp/workbench.html
Either fails to attach to the browser/node server....

Here is the launch.json part:
 {
    "name": "Local workbench",
    "type": "edge",
    "request": "launch",
    "url": "https://localhost:4321/temp/workbench.html",
    "webRoot": "${workspaceRoot}",
    "sourceMaps": true,
    "sourceMapPathOverrides": {
      "webpack:///../../../src/*": "${webRoot}/src/*",
      "webpack:///../../../../src/*": "${webRoot}/src/*",
      "webpack:///../../../../../src/*": "${webRoot}/src/*"
    }

**Comment by iamscottm** [comment]
The other outcome is browser pop-up message: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:2015).

**Comment by andrewconnell** [comment]
Since this issue is fairly dated, can you verify if you are still having the issue in the latest version of SPFx, v1.7.1? There were a few fixes since this was posted that addressed issues related to debugging SPFx solutions with VSCode.
