### ISSUE TITLE
Are you able to set the URL as well as the list name using Site Scripts?

### ISSUE THREAD

**Issue by kevmcdonk** [SharePoint/sp-dev-docs#2278]
Loving the Site Scripts but would be great if you can create a separate URL for the list to the name, especially with the aim to not have spaces in the URL that you would want in the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#see-also)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This would be considered a feature request/change to the current schema which is going to fall into a uservoice submission.
