### ISSUE TITLE
Color of links

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/sp-dev-docs#2279]
How do I control the color of links - including their hover color?

Regards
Leif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by DylanWE** [comment]
if you mean a HTML link you can use CSS to style it:
### CSS
the following code changes all link colors
```
a {
color: hotpink;
}
```

**Comment by Leif-Frederiksen** [comment]
No, this question is in the context of the Modern Theming: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview
What entry in the palette is used for the links on a page?

**Comment by andrewconnell** [comment]
@StfBauer by chance do you know?

**Comment by StfBauer** [comment]
@Leif-Frederiksen TLDR: You cannot control the link color or hover state for hyperlinks in modern themes. 

These are automatically generated by the theming engine and use the "Primary Color" as the link color and a slightly darkened color for the hover effect.

You also need to consider with the colored background sections on Office 365 these link colors need to be adopted there automatically to have high contrast with the background.

In case your display in Windows is set to High Contrast the theme again automatically adapts itself to recalibrate to the correct color for accessibility reasons.

From a branding perspective, most companies use the same primary branding colors for links too so in this case theming does a good job.

If you like to see what theme slots are in general in use I created a [reference chart](https://n8design.github.io/spfx-uifabric-themes/sass/ouif.theme/) based on the default blue theme provided by Microsoft. 

**Color code:** #0078d4
**Theme slot name:** #0078d4

If you want to see all the colors used for a particular theme I created a web part named [Panthema](https://github.com/n8design/panthema) that you can add to any of your sites on Office 365.

**Comment by Leif-Frederiksen** [comment]
Hi Stefan,

Thanks for the info - and for the greate reference chart. Nice work :-)

Regards
Leif

Den ons. 2. okt. 2019 kl. 00.15 skrev Stefan Bauer <notifications@github.com
