### ISSUE TITLE
A spinning wheel should be shown while onInit waits for the promise

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#228]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When I override onInit and return Promise I would like SPFx to show a spinning wheel until that promise is fulfilled. 

#### Observed Behavior
If it takes long time to fulfil the promise in onInit, nothing is shown where the web part is supposed to be.

#### Steps to Reproduce
Add this to a WP

```
public onInit<T>(): Promise<T> {
  return new Promise<T>((resolve: (args: T) => void, reject: (error: Error) => void) => {
    setTimeout(() => {
        resolve(undefined);
      }, 5000);
  });
}
```

**Comment by manishgarg1** [comment]
This is fixed in the code. Should be available in the next drop. Please let us know if you still find the issue after the next drop.

**Comment by wictorwilen** [comment]
Works as expected now. Thanks for the awesome job!
