### ISSUE TITLE
The documentation on this page has html embedded throughout

### ISSUE THREAD

**Issue by ChosenSilver** [SharePoint/sp-dev-docs#2281]
The doc is a bit difficult to read as the code samples contain html (i.e. &amp;&amp; instead of &&)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d27ed41-9099-d053-9465-95b45267947a
* Version Independent ID: e03e1c60-2e3e-f09c-9976-afddb9bbc8de
* Content: [DocumentIdProvider Class (Microsoft.Office.DocumentManagement)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.documentmanagement.documentidprovider?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.Office.DocumentManagement/DocumentIdProvider.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.Office.DocumentManagement/DocumentIdProvider.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Looks like it was fixed...
