### ISSUE TITLE
Cannot pul my list information into this calendar web part

### ISSUE THREAD

**Issue by jazzny116** [SharePoint/sp-dev-docs#2283]
I have followed the tutorial to a T and the calendar loads in my workbench empty every time.  I've explicitly set my API url to ensure it's not the dynamic url, created a list that contained events and the fields shown in the tutorial.  How can I get help on this?  I'd love to implement it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ecd027-f5ca-48c0-d60c-1883fa24ab96
* Version Independent ID: 9f38cbc9-464a-a2a4-0eeb-4deb6b2eb339
* Content: [Migrate jQuery and FullCalendar solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx#feedback)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The tutorial is old and is slated to get refreshed (see #4240). 

If you have a specific question about a problem/error you're seeing, please post that as it's not possible to assist with the provided detail.
