### ISSUE TITLE
Tenant & Site Collection App Catalog - Permission Requirements?

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#2286]
Please consider adding a 'Required Permissions' section to the document. I found that I needed to be a Site Collection Administrator on both the target Site Collection AND the tenant-level App Catalog (I am not a Global Admin, merely a SharePoint Administrator).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb134fd8-6880-360a-faea-7eb0eedca2d9
* Version Independent ID: 16f799b7-deff-b125-ceed-343933bcbe79
* Content: [Use the site collection app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)
* Content Source: [docs/general-development/site-collection-app-catalog.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/site-collection-app-catalog.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kmsrajan** [comment]
It is very good improvement on reducing Tenant Admin's app approval and decentralization on app which are specific to a site collection. Please clarify below queries.

1. As understood, no need to specify a scope(Site collection or Tenant ) during app/add-ins development. If that is the case what happen when same package deployed in Site collection level and Tenant level?

2. If I downgrade any existing app from Tenant level to Site collection level,  how that specific site collection behave(will it work without any interrupt) and how renaming site collection in the tenant will behave?

**Comment by in8sausa** [comment]
We need to be Site Collection Admin to Tenant app catalog site also

**Comment by a2life** [comment]
I am a bit puzzled.  In the production tenant, I am a site collection admin of the target site collection but do not have Site Collection Admin rights to the tenant level app catalog.  Yet I am able to upload and deploy apps in the target site collection AppCatalog

**Comment by JBoman32768** [comment]
> I am a bit puzzled. In the production tenant, I am a site collection admin of the target site collection but do not have Site Collection Admin rights to the tenant level app catalog. Yet I am able to upload and deploy apps in the target site collection AppCatalog

Were you using Add-PnPApp or doing it manually?

**Comment by a2life** [comment]
I am doing it manually.
