### ISSUE TITLE
SharePoint Server API Documentation Rendered Incorrectly

### ISSUE THREAD

**Issue by Powerhelmsman** [SharePoint/sp-dev-docs#2287]
This issue was created by @bloudraak from https://github.com/MicrosoftDocs/feedback/issues/559
Describe the bug
Many of the SharePoint Server API documentation is rendered incorrectly. The bug report is for one page, but they are too numerous to create one for each page.
To Reproduce
Go to https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termstore?view=sharepoint-server
Observe that content is rendered incorrectly.
Expected behavior
Expecting the source code to be rendered as source code, and other contents are rendered as HTML
Screenshots

Desktop (please complete the following information):
OS: Windows 10 Version 1803
Browser: Firefox
Version: 61.0.1 (64-bit)
Additional context
Many of the SharePoint API sites seems to be rendered incorrectly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5012458b-5250-b08e-3a23-363b8b6a7d3f
* Version Independent ID: ba33da32-64e2-7932-1c5e-7305ee89e3a5
* Content: [TermStore Class (Microsoft.SharePoint.Taxonomy)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termstore?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/TermStore.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/TermStore.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
This page appears to have been fixed. As we find pages that have an issue in the HTML => Markdown conversion, we're fixing them.
