### ISSUE TITLE
Workbench.aspx error

### ISSUE THREAD

**Issue by Mustachoman** [SharePoint/sp-dev-docs#229]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

I am trying to use the new Workbench feature for our online SharePoint on our own server. Locally I get everything working however when I want to test the webpart on the online SharePoint by going to 
'https://your-sharepoint-site/Shared%20Documents/workbench.aspx' (with our own site of course) it gives me the error:

> Sorry, something went wrong
> Could not load type 'Microsoft.SharePoint.WebControls.ClientSidePage' from assembly 'Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.

I've done some research and it's not that the Site Collection is not made by a Developer Account because then I would get another error. 

I've downloaded the workbench.aspx [here](https://github.com/SharePoint/sp-dev-docs/blob/master/workbench.aspx) and uploaded it to the modified Documents Library as per the tutorial.

So how can I fix this?

**Comment by wictorwilen** [comment]
As per the instructions at http://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant you MUST have a Developer tenant in Office 365; not just a Developer Site Collection. And not on your own SharePoint server.

**Comment by Mustachoman** [comment]
Can't believe I missed the first line haha.
I am now creating one and going to follow the tutorial again. 

Thanks for the fast reply! Will come back with results!

**Comment by Mustachoman** [comment]
So the problem is fixed thanks to @wictorwilen!
