### ISSUE TITLE
Add more info about Dev Dashboard

### ISSUE THREAD

**Issue by mcraiha** [SharePoint/sp-dev-docs#2291]
Document has following text _"This default solution writes a log to the Dev Dashboard,"_ but there isn't a link or an explanation that tells developer what _"Dev Dashboard"_ is or how to access it. And it in Log class (in sp-core-library) it is called _"developer dashboard"_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Thanks @mcraiha for the input. We will be releasing a new specific article addressing this request in upcoming days. Thanks for your input.
