### ISSUE TITLE
Migration API Introduction

### ISSUE THREAD

**Issue by sganta** [SharePoint/sp-dev-docs#2292]
I am just surfing through the documentation and found the page on Migration API. It is full of technical details but just not exactly what it is and where it is used. Lacking this context can cause confusion and frustration.  Please introduce all the topics in Sharepoint Framework documentation properly because most of it is new.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3bfe80-38e3-e49a-dd94-c2851264dfce
* Version Independent ID: 8796c402-cd21-a86b-99f0-d0bd035ceb5f
* Content: [SharePoint Online Migration API Overview](https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview)
* Content Source: [docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/migration-api-overview.md)
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by andrewconnell** [comment]
This API has nothing to do with the SharePoint Framework... as the navigation shows, this is part of the SharePoint API and applies to the CSOM.
