### ISSUE TITLE
Change the license of Microsoft.SharePointOnline.CSOM nuget package

### ISSUE THREAD

**Issue by nddipiazza** [SharePoint/sp-dev-docs#2293]
I noticed an overly-restrictive license on this library:

https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM

License: http://go.microsoft.com/fwlink/?LinkId=280198

Which restricts the usage on Non-windows platforms. 

But the overall direction of this is to allow .NET core  and cross-platform usage for CSOM. This keeps people from having to use the REST api and instead can use the awesome CSOM SDK. 

How can we get this license changed to something more appropriate?

**Comment by VesaJuvonen** [comment]
As this NuGet CSOM is targeted for .NET and NOT .NET Core, the license is correct. Whenever we release the .NET Core version of CSOM (work in progress), it will be a separate NuGet package with updated license matching the use cases. Thanks for the reminder on updating the license accordingly.

**Comment by nddipiazza** [comment]
why would a client SDK library have a restrictive license like that? *sigh* oh well I guess that's microsoft for ya.

**Comment by VesaJuvonen** [comment]
We... it's tested and supported currently only for Windows and as we provide support for these libraries, we also need to ensure that the licenses are valid. We will support also other platforms when the .NET Core version is out.

**Comment by akoeplinger** [comment]
@VesaJuvonen are you working on a .NET Core version or a .NET Standard one? the latter could be used on other platforms like Xamarin.

**Comment by VesaJuvonen** [comment]
It will be .NET Standard... just to be precise.

**Comment by Zhephyr54** [comment]
@VesaJuvonen is there any ETA yet ?

**Comment by VesaJuvonen** [comment]
Work is currently scheduled to happen after Ignite, but we cannot provide exact ETA at this point.
