### ISSUE TITLE
Bundle commands under single menu - Commandset Extension 

### ISSUE THREAD

**Issue by dhanabalramesh** [SharePoint/sp-dev-docs#2294]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Scenario:
> We have created 3 List view command sets "Mark as complete", "Create reminder" and "Update as Pending" based on a client requirement and we managed to make it work in a single package. Challenge came when customer asked to group the commands under single main menu called "Record Operations"

#### Client expectation:
![image](https://user-images.githubusercontent.com/20179657/43480762-d38a1f6e-9521-11e8-8880-7f15cc2e5624.png)

#### Question:
Is it possible to group those command sets under single menu item say "Record Operations". Same behavior as "New", "Upload", "Flow" etc.. which has sub menu items (Files, Folders) inside main menu item (Upload). I'm not able to find any help from web site so far. Examples or keyword to search on how approach this functionality will be highly helpful.

Thanks in advance experts!
Sharing is caring.

**Comment by lijunle** [comment]
As a workaround, the button can pop up a [`Callout`](https://developer.microsoft.com/en-us/fabric#/components/callout) component to simulate the submenu behavior.

**Comment by dhanabalramesh** [comment]
@lijunle , thanks for your suggestion. 
Is call out option available in list view commandset extension?

**Comment by lijunle** [comment]
It is a fabric-react component. You can integrate it with extension.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components
