### ISSUE TITLE
one picture is worth of 1000 words

### ISSUE THREAD

**Issue by mganeshphani** [SharePoint/sp-dev-docs#2296]
Please make this article more readable and understandable with pictures :).. toomuch of text to read

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fda841a-d06a-a222-ab01-60466afcd2ca
* Version Independent ID: 0f8e9d94-7009-7d9f-32b7-47d24623c55c
* Content: [Create external content types for SQL Server in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint#create-a-connection-to-the-external-data)
* Content Source: [docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks for the suggestion, but at this time the article is correct & is part of a bigger section on BCS. The high-level overview articles in this section contain pictures. The point of this article was to explain step by step how to create ECT's in steps.
