### ISSUE TITLE
An article on AD integrated SQL PaaS would be great in this context

### ISSUE THREAD

**Issue by mganeshphani** [SharePoint/sp-dev-docs#2297]
There are no articles pinpointed towards connecting Azure AD integrated SQL PaaS with external content types.. please write some documentation on this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fda841a-d06a-a222-ab01-60466afcd2ca
* Version Independent ID: 0f8e9d94-7009-7d9f-32b7-47d24623c55c
* Content: [Create external content types for SQL Server in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint#create-a-connection-to-the-external-data)
* Content Source: [docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks for the request... as this is more of a feature request, best to submit this as a user voice request like all feature requests, even if a doc request.
