### ISSUE TITLE
Microsoft promotes Logic Apps as the officially supported workflow designer - what about external content like this?

### ISSUE THREAD

**Issue by mganeshphani** [SharePoint/sp-dev-docs#2298]
Is Designer going to be only 2013 version going forward for this activity or any other alternative way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fda841a-d06a-a222-ab01-60466afcd2ca
* Version Independent ID: 0f8e9d94-7009-7d9f-32b7-47d24623c55c
* Content: [Create external content types for SQL Server in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint#create-a-connection-to-the-external-data)
* Content Source: [docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-create-external-content-types-for-sql-server-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
SharePoint Designer 2013 was the last version of SPD. The recommended workflow solution in SharePoint is now Microsoft Flow. If you need more control, you can leverage Azure Logic Apps.
