### ISSUE TITLE
Tutorial 2: step 7 includes reference to a property called "Test2", will result in a failed built

### ISSUE THREAD

**Issue by hippolascage** [SharePoint/sp-dev-docs#23]
Tutorial 2, step 7 code for render()

`<p class="ms-font-l ms-fontColor-white">Customize SharePoint experiences using Web Parts.</p>`
`<p class="ms-font-l ms-fontColor-white">${this.properties.description}</p>`
`<p class="ms-font-l ms-fontColor-white">${this.properties.test2}</p>`
`<p class='ms-font-l ms-fontColor-white'>Loading from ${this.context.pageContext.web.title}</p>`

`${this.properties.test2}` is going to throw build errors:

> Property 'test2' does not exist on type 'SPWeb'

Should this be removed from the example? Happy to submit a PR if the above makes sense.

**Comment by pmizuno** [comment]
Did you at test2 to the interface IHelloWorldWebPartProps.ts?

**Comment by hippolascage** [comment]
No, I didn't. I understand I could do this, but I thought I would raise it as it's not mentioned in the exercise. Would it make sense to add a note about this?

**Comment by pmizuno** [comment]
I think it does says that it's continuing from Tutorial 1 at the top.

**Comment by hippolascage** [comment]
Yeah, you're right. It looks like those changes including adding the property were made in a revision to Tutorial 1 yesterday. My issue is I did tutorial 1 yesterday, before that revision, so when I started tutorial 2 I was out of sync. Thanks.

**Comment by hippolascage** [comment]
No turns out I just can't read.
