### ISSUE TITLE
Conditional Formatting based on number range is broken from 01/08/2018

### ISSUE THREAD

**Issue by shaheenak28** [SharePoint/sp-dev-docs#2302]
Hello Team,

Something has changed based on a possible recent update at Sharepoint (was working till yesterday) as the conditional formatting based on number is now broken even if I apply the same code on this website (number 70 example). Issue replicated in both Chrome and Edge.

The output value is now showing as blank (for calculated columns).  If the formatting is removed, the output number is then visible.

Kind Regards
Shaheen

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-gb/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nikkiwong** [comment]
I have the same issue. Have you managed to solve it?

**Comment by shaheenak28** [comment]
@nikkiwong the code has now been changed in [https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting] but the error is still there.

**Comment by nikkiwong** [comment]
Ah, thanks shaheenak. Any idea of how we can fix this? or even get Microsoft to fix it?

**Comment by shaheenak28** [comment]
Until @VesaJuvonen gets someone to work on this I believe we are stuck. I have removed the formatting from the columns as I cannot see the values. I believe with the number of issues reported being resolved in this bug tracker, I believe it will take a while before we will see the light.

**Comment by shaheenak28** [comment]
@VesaJuvonen could you please provide us an ETA for this?

**Comment by Yusha813** [comment]
@shaheenak28 I found something weird. If you don't have a value for the field, the JSON column formatting will NOT work. I'm sure it has something to do with the value being NULL or Blank and they aren't dealing with that case by default. Since you say this just stopped working recently, I would make sure no fields are blank, if one is I would make sure that field has a value and double check to see if it is still not working.

**Comment by shaheenak28** [comment]
@Yusha813  thanks for your reply. the JSON now worked after this many days but has now brought in a new challenge where the values/output is showing the decimal places eventhough the column is created with 0 decimal places. Any idea on what could be the reason?

**Comment by shaheenak28** [comment]
@Yusha813 - fixed it by changing the column with =TEXT(yournumber, "0")
