### ISSUE TITLE
Regional settings sortOrder documentation is insufficient

### ISSUE THREAD

**Issue by pettersh** [SharePoint/sp-dev-docs#2304]
sortOrder is a required parameter and the link specified doesn't reference a page that provides information about available options and their meaning. Example shows sortOrder 6, whatever that means

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#see-also)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by pettersh** [comment]
BTW, found what I was looking for by looking at the HTML of /_layouts/15/regionalsetng.aspx in dev tools. General is 25.

**Comment by andrewconnell** [comment]
Since you left this comment, I'm guessing the doc was updated as it references what the sort order is and points to the collation documentation. A comment in the code mentions 6=croation
