### ISSUE TITLE
Register an extension: How to specify Rights for the custom action/extension?

### ISSUE THREAD

**Issue by pettersh** [SharePoint/sp-dev-docs#2305]
I have an extension that only should be run by Owners. If I register the extension using other existing API's I can specify the Rights. Can the same be done with the associateExtension action? Please update docs with examples or links to relevant info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#register-an-extension)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
According to the schema, it does not appear specifying the rights is someting that's currently supported. Would make for a good feature request via uservoice.
