### ISSUE TITLE
Microsoft.Azure.AgregatorService could not be found

### ISSUE THREAD

**Issue by grahampasmurf** [SharePoint/sp-dev-docs#2311]
I followed steps to resolve Microsoft Graph API issue. I switched reference and re-packaged and get error,

“[HTTP]:400 – Bad Request [CorrelationId]:153a819e-d09f-0000-08ac-5fb83e23e391 [Version]:16.0.0.7925 – A service principal with the name Microsoft.Azure.AgregatorService could not be found.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
What do you mean exactly when you say you switched the reference... where did you do that? If you're referring to the scopes you're defining, the graph is "Microsoft Graph"

**Comment by grahampasmurf** [comment]
When I say that I switched the reference, I am referring to the workaround mentioned in this bug document -
https://github.com/SharePoint/sp-dev-docs/issues/1401

where the bug/error is "[HTTP]:400 - [CorrelationId] when trying to approve a MS Graph permission request in a SPFx package"

and the workaround mentioned by Vesa is
"The workaround is to use the following configuration in the package-solution.json for those tenants where the Principal Name for Microsoft Graph is using old value. Basically use the "Microsoft.Azure.AgregatorService" as the value for the resource entry."

**Comment by andrewconnell** [comment]
Ah... that was a temp workaround. The feature that went GA wants the name of the service as the resource. In this case, it's "Microsoft Graph"
