### ISSUE TITLE
What is the latest version of npm and node which is compatible with SPFX version 1.5.1?

### ISSUE THREAD

**Issue by nehaj910** [SharePoint/sp-dev-docs#2312]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

What is the latest version of npm and node which is compatible with SPFX version 1.5.1?

**Comment by nehaj910** [comment]
Thank you @gautamdsheth  for your quick response. So does this [document](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) get updated with the latest compatible node version every time a new SPFX version is released?

**Comment by waldekmastykarz** [comment]
@nehaj910 correct

**Comment by nehaj910** [comment]
Thanks @waldekmastykarz  👍

**Comment by Isabeletta** [comment]
I have SPFx version 1.5.1, Node 8.11.3 and npm 5.6.0. But when I do "yo @microsoft/sharepoint" the options for baseline packages are "SharePoint Online only" and "SharePoint 2016 onwards, including SharePoint Online" but not SharePoint 2019. Why? What am I doing wrong?

**Comment by waldekmastykarz** [comment]
Support for SharePoint 2019 has been introduced in SharePoint Framework v1.7.0 @Isabeletta

**Comment by Isabeletta** [comment]
@waldekmastykarz I try with SharePoint Framework v1.7.1
When I do gulp serve works ok but when generating the package it does not generate any errors but when I upload .sppkg file to the App Catalog library it gives me errors.
