### ISSUE TITLE
Can't run Jest tests when component uses Dialog

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2325]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I use @microsoft/sp-dialog 1.5.1 and SPFx 1.5.1

#### Expected or Desired Behavior

When I test my component with Jest I get the next error

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Code\SPFx\mywepart\node_modules\@microsoft\sp-dialog\lib\Dialog.js:7
    import { sealed } from '@microsoft/decorators';
    ^^^^^^

    SyntaxError: Unexpected token import

    > 12 | import Dialog from "@microsoft/sp-dialog/lib/Dialog";
```

**Comment by aslanovsergey** [comment]
Very similar thing happens with Guid class

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Code\SPFx\***\node_modules\@microsoft\sp-core-library\lib\index.js:11
    export { default as _BrowserDetection } from './BrowserDetection';
    ^^^^^^

    SyntaxError: Unexpected token export

       7 | import { connect, Dispatch } from "react-redux";
    >  9 | import { Guid } from "@microsoft/sp-core-library";
```

**Comment by petecuttriss** [comment]
Hi Sergei,  I just wanted to confirm that I'm seeing the same issue also.  Likewise I'm using v1.5.1.

In my case I've added an import for the DisplayMode from the sp-core-library `import { DisplayMode } from '@microsoft/sp-core-library';`  As soon as I do this my tests being failing with the same error:

`C:\Projects\UserGroupsViewer\node_modules\@microsoft\sp-core-library\lib\index.js:11
    export { default as _BrowserDetection } from './BrowserDetection';
    ^^^^^^`
Pete

**Comment by aslanovsergey** [comment]
Tried to wite transformIgnorePatterns but didn't help

**Comment by crsanghani** [comment]
@aslanovsergey Did you come up with a solution to this?

**Comment by gosiaborzecka** [comment]
I have the same error with jest testing on `'@microsoft/sp-core-library'`:
`\node_modules\@microsoft\sp-core-library\lib\index.js:11
    export { default as _BrowserDetection } from './BrowserDetection';
    ^^^^^^`

**Comment by aslanovsergey** [comment]
@crsanghani Unfortunately no and @microsoft/sp-dialog 1.6.0 doesn't change the situation

**Comment by ottwell** [comment]
@aslanovsergey any progress? i have the same issue

**Comment by fourthgenz28** [comment]
I'm also encountering the same error as @gosiaborzecka even after removing all references to Dialog.  SPFx v1.5.0

**Comment by petecuttriss** [comment]
Hi everyone, @aslanovsergey 

I did some further research on this and have managed to get my jest tests working but I'm not quite sure yet at what cost.

I took a copy of Velin Georgiev's jest testing sample: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-jest-testing.  This sample is using SFPX v1.6.0.

I did an initial build and ran "npm test" successfully.    I then took the "IceCreamShop.tsx" component and added a reference to the Guid class e.g. import { Guid } from '@microsoft/sp-core-library';   I also added a var which generated a new guid in the main render method e.g. var guid: Guid = Guid.newGuid();.

After this change I ran "npm test" once again and got it to fail with the "Unexpected token export" error.

To get the tests running again I then did the following:

1. In the package.json file I changed the "transform" configuration from:
`"^.+\\.(ts|tsx)$": "ts-jest"` to 
`"^.+\\.(js|ts|tsx)$": "ts-jest".` 

Note the addition of "js".

2. In the pacakge.json file I added a "transformIgnorePatterns" configuration value: e.g. 
`"transformIgnorePatterns": [
      "node_modules/(?!(@microsoft/sp-core-library))"
    ],`

3. In the tsconfig.json file, I removed the "declaration" configuration and added an "allowJs" configuration with it's value set to "true".
`"allowJs": true,`

Following these changes I was able to run "npm test" again and the tests all ran successfully.

I've been able to replicate these steps using a new project also built using SPFx v1.7.0 with the same results.

I can't say I fully understand the implications of the changes I've made but building, running and testing of my components is now working.   Hopefully these changes might further help in figuring out this issue.   I need to do some more research to further understand the implications of these changes.

**Comment by aslanovsergey** [comment]
I had opened an issue in jest project and got an answer.
https://github.com/facebook/jest/issues/6975#issuecomment-435588381

@VesaJuvonen who can look at this issue from SPFx team side?

**Comment by Krak86** [comment]
> Hi everyone, @aslanovsergey
> 
> I did some further research on this and have managed to get my jest tests working but I'm not quite sure yet at what cost.
> 
> I took a copy of Velin Georgiev's jest testing sample: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-jest-testing. This sample is using SFPX v1.6.0.
> 
> I did an initial build and ran "npm test" successfully. I then took the "IceCreamShop.tsx" component and added a reference to the Guid class e.g. import { Guid } from '@microsoft/sp-core-library'; I also added a var which generated a new guid in the main render method e.g. var guid: Guid = Guid.newGuid();.
> 
> After this change I ran "npm test" once again and got it to fail with the "Unexpected token export" error.
> 
> To get the tests running again I then did the following:
> 
> 1. In the package.json file I changed the "transform" configuration from:
>    `"^.+\\.(ts|tsx)$": "ts-jest"` to
>    `"^.+\\.(js|ts|tsx)$": "ts-jest".`
> 
> Note the addition of "js".
> 
> 1. In the pacakge.json file I added a "transformIgnorePatterns" configuration value: e.g.
>    `"transformIgnorePatterns": [ "node_modules/(?!(@microsoft/sp-core-library))" ],`
> 2. In the tsconfig.json file, I removed the "declaration" configuration and added an "allowJs" configuration with it's value set to "true".
>    `"allowJs": true,`
> 
> Following these changes I was able to run "npm test" again and the tests all ran successfully.
> 
> I've been able to replicate these steps using a new project also built using SPFx v1.7.0 with the same results.
> 
> I can't say I fully understand the implications of the changes I've made but building, running and testing of my components is now working. Hopefully these changes might further help in figuring out this issue. I need to do some more research to further understand the implications of these changes.

For me it works, thanks!

**Comment by spvjebaraj** [comment]
Hi @petecuttriss 
It is not working for me what ever you have shared. Still I am getting the error like "export { default as _BrowserDetection } from './BrowserDetection'".
Please help me on this.
