### ISSUE TITLE
No Debugging Mechanism and No Logs for the deployed Site Design

### ISSUE THREAD

**Issue by rkore85** [SharePoint/sp-dev-docs#2326]
When I am creating site with deployed site design it is just showing Initializing for hours but not doing anything , we don't have even know what is going wrong. Also when ps script is deployed at that time no errors and no warnings.

Please give the documentation on debugging mechanism or logs to check for deployed site design and site script.
Also addNavLinks is not working for external sites when isWebRelative: "false". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a433bf-b243-03ff-f733-484dca2be753
* Version Independent ID: 7a173ed3-1700-b24f-ee78-417dd494ce16
* Content: [Get started creating SharePoint site designs and site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design)
* Content Source: [docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/get-started-create-site-design.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ravick4u** [comment]
Its been a while and would like to know if this is still true.

**Comment by melitoSP** [comment]
@ravick4u, thanks for the feedback. We are working on making improvements in this area. 

For the addNavLinks not working, we validated that it works. Can you try again?
