### ISSUE TITLE
AadHttpClient - observations and questions

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#2331]
#### Category
- [x] Questions

1. AadHttpClient uses special application called SharePoint Online Client Extensibility. If I just want to protect my API with Azure AD authentication, can I use SharePoint Online CE's Application Id - `c58637bb-e2e1-4312-8a00-04b5ffcd3403` in AadHttpClient?    

For example:   

```typescript
this.context.aadHttpClientFactory
     .getClient('c58637bb-e2e1-4312-8a00-04b5ffcd3403')
     .then((client: AadHttpClient): void => {
       client.get('https://remote/api/clients').then(...)
     });
```
   This approach has some benefits, that you don't have to register new application and add `webApiPermissionRequests` node in your web part. As a result admin don't have to go and approve anything.    

I have tested this scenario and it works just fine. The question is, is it supported?     
    
2. `webApiPermissionRequests` is used to propagate permissions for custom or Microsoft APIs to SharePoint CE application. As soon as permission request is approved by admin, corresponding permissions will be admin consented and can be used by AadHttpClient and token generation.   
However we can do exactly the same thing by using custom code with help of Windows Graph or MS Graph (endpoints for managing `OAuth2PermissionGrant` are in preview). I've created a code sample [here](https://github.com/spblog/Diving-into-AadHttpClient-with-hacking) which does exactly that. This approach might be useful, if you want to automate approval, or for hot fixes, when full web part re-deployment or upgrade is not desirable.   
  
Is such flow supported?    

3. Imagine that your organization added a lot of MS Graph endpoints via `webApiPermissionRequests` while developing web parts. Later on organization installs third-party SPFx web parts. Third party web parts immediately gain an access to all approved API. Third party code doesn't know which exact APIs are available, however they can use try-catch approach to find if, for example, it is possible to read user's mail through MS Graph.    
How to deal with it?

**Comment by s-KaiNet** [comment]
I will try to answer my own questions because things have changed a bit after 1.6 and 1.7 SPFx releases.     

1. SharePoint Online CE's Application Id isn't "hardcoded" anymore, instead, it's created automatically as soon as you have `webApiPermissionRequests` in your SPFx package schema. Once created, all spfx solutions will use this Azure AD application. You can find app id using `_spPageContextInfo.spfx3rdPartyServicePrincipalId`. It's different for different tenants because as said it's created automatically and you can't predict id. Can you use it for your third party API as an authentication point? I think yes, you can because that's just an Azure AD app registration in the end. However, I believe you shouldn't use it because that's something created automatically and out of your control. Who knows, maybe once a day Microsoft decides to re-create it with new id or something. In that case, approach, when you have your own Azure AD, is much safer.     
2. You can do that via custom code or [PowerShell](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#manage-permissions-with-powershell) or [o365 cli](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#manage-permissions-using-the-office-365-cli). You can assign permissions directly (as I did in the sample code), but why should you do that, if you have other supported options.
3. If you worry about security, you should use [domain isolated web parts (in the preview as of now)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts). They run in an iframe in a separate domain, all API permission requests are bound to each isolated web part individually. It doesn't answer the question completely, yet gives additional options for spfx APIs security.

**Comment by winperec** [comment]
Thanks Sergey,
about 1 and 2 questions answers are clear. 
About question 3: The key "issue" that all solutions reuse single service principal... So I would say this approach is OK when you need just authenticate users. but when ISV (especially if service the ISV provides is multi-tenant) requires permissions to customers' Azure AD better create own Azure AD application. this will be more transparent and clear for customer's what application what permissions use. It also gives ability to disable some permissions without any impact on applications of other ISVs.

**Comment by s-KaiNet** [comment]
If you use domain isolated feature, it creates separate Azure AD registration for every spfx package and don't use shared one. That might be a solution for ISVs. Your own Azure AD app in customer's AD is also a good option if you have permissions to do it.

**Comment by andrewconnell** [comment]
Seems like this issue of questions was answered so I'll go ahead and close it. If you think otherwise, we can reopen.
