### ISSUE TITLE
People Picker field using SPFX

### ISSUE THREAD

**Issue by Shyammi** [SharePoint/sp-dev-docs#2337]
I have a requirement where I need to build a form that take input from users. I'm struggling to get people picker field designed in the custom form using spfx. I tried to design a people picker column "clientpeoplepicker.js" but getting the following error when get deployed to the page.

*****Failed to load component "12aa0e59-386d-4a4e-8025-6a56eff5b805" (PeoplePickerWebPart).
Original error: ***Failed to load path dependency "clienttemplates" from component "12aa0e59-386d-4a4e-8025-6a56eff5b805" (PeoplePickerWebPart).
Original error: Error loading https://component-id.invalid/12aa0e59-386d-4a4e-8025-6a56eff5b805_0.0.1/clienttemplates
	Evaluating https://azsponline.sharepoint.com/sites/QMS/_layouts/15/clienttemplates.js
	clienttemplates is not defined

***INNERERROR:
***Failed to load path dependency "clienttemplates" from component "12aa0e59-386d-4a4e-8025-6a56eff5b805" (PeoplePickerWebPart).
Original error: Error loading https://component-id.invalid/12aa0e59-386d-4a4e-8025-6a56eff5b805_0.0.1/clienttemplates
	Evaluating https://azsponline.sharepoint.com/sites/QMS/_layouts/15/clienttemplates.js
	clienttemplates is not defined**

I have referenced all the necessary js files but still getting file is not defined for all js related to peoplepicker.

Any help is much appreciated.

**Comment by thechriskent** [comment]
Not sure what's wrong with your approach without seeing how you're referencing the file. Are you doing this in the config as an external?

Alternatively, did you know there is a free people picker control available from PnP for use in SPFx that might make your life a lot easier? https://sharepoint.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/

If nothing else, you should be able to look at the code to see how it's done there.

**Comment by Shyammi** [comment]
I have the form already developed in spfx with no javascript framework selected. So, I'm trying to bring people picker field using clientpeoplepicker.js. Below is the reference in config.json - 

"externals": {
    "sp-init": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/init.js",
      "globalName": "$_global_init"
    },
    "microsoft-ajax": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/MicrosoftAjax.js",
      "globalName": "microsoft-ajax",
      "globalDependencies": [
        "sp-init"
      ]
    },
    "sp-runtime": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/SP.Runtime.js",
      "globalName": "sp-runtime",
      "globalDependencies": [
        "microsoft-ajax"
      ]
    },
    "sharepoint": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/SP.js",
      "globalName": "sharepoint",
      "globalDependencies": [
        "sp-runtime"
      ]
    },
    "sp-core": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/SP.js",
      "globalName": "sp-core",
      "globalDependencies": [
        "sp-runtime"
      ]
    },
    "clienttemplates": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/clienttemplates.js",
      "globalName": "clienttemplates",
      "globalDependencies": [
        "sharepoint"
      ]
    },
    "clientforms": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/clientforms.js",
      "globalName": "clientforms",
      "globalDependencies": [
        "sharepoint"
      ]
    },
    "clientpeoplepicker": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/clientpeoplepicker.js",
      "globalName": "clientpeoplepicker",
      "globalDependencies": [
        "sharepoint"
      ]
    },
    "autofill": {
      "path": "https://azsponline.sharepoint.com/sites/QMS/_layouts/15/autofill.js",
      "globalName": "autofill",
      "globalDependencies": [
        "sharepoint"
      ]
    },
},
