### ISSUE TITLE
Knockout web part disappears when running in SharePoint workbench

### ISSUE THREAD

**Issue by davros85** [SharePoint/sp-dev-docs#234]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

When running a web part using the knockout template in the SharePoint workbench, it renders the web part.
#### Observed Behavior

When stepping through the code on init, the web part renders initially, below the loading spinner. Then in the _internalFirstTimeRender method, when this.context.statusRenderer.clearLoadingIndicator(this.domElement) is called, the web part disappears - it is cleaned from the DOM. 

I have noticed a difference between the local workbench and SharePoint workbench - 'this.domElement' in the SP workbench contains a '.placeholder' element, whereas in the local workbench it does not.
#### Steps to Reproduce

Yo a new knockout webpart, (fix the _description bug, and remove all custom properties). Run the web part in the workbench in SharePoint.

**Comment by manishgarg1** [comment]
I know of this problem. Looking at fixing soon.

**Comment by davros85** [comment]
Workaround presented as part of #233

**Comment by manishgarg1** [comment]
This is fixed now.
