### ISSUE TITLE
UI Fabric color classes loading tenant theme colors instead of site theme colors

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2340]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I would expect the use of `ms-bgColor-themePrimary` to apply a style with the background-color set to the _site's_ primary theme color.

#### Observed Behavior

The `ms-bgColor-themePrimary` is applying a background-color equivalent to the O365 tenant theme color and ignoring the site theme altogether:

![image](https://user-images.githubusercontent.com/8364109/43936506-c9c7cf88-9c26-11e8-8945-225c4dd62239.png)

Switched Theme:
![image](https://user-images.githubusercontent.com/8364109/43936766-198e15ee-9c28-11e8-8db9-5049348c9b53.png)

#### Steps to Reproduce

Apply any of the UI Fabric color theme classes to an element on a page. The example above is in an SPFx webpart, but you can use the dev tools to apply to any element on the page with the same result.

>Note, using the `$ms-color-themePrimary` variable in an SPFx web part's Sass file for an element's background-color causes it to resolve correctly. So the issue doesn't appear to be with the theme, but with the UI Fabric classes being generated.

**Comment by thechriskent** [comment]
Just noticed these classes are working fine on a modern listview page when used with Column Formatting:
![image](https://user-images.githubusercontent.com/8364109/43936933-ffedeb22-9c28-11e8-88cc-a9dd191fb5d0.png)

However, putting that list on a page results in this:
![image](https://user-images.githubusercontent.com/8364109/43936952-14c560f2-9c29-11e8-8148-a358ef91d232.png)

**Comment by thespooler** [comment]
I can also confirm this bug. 
For some reason, the min-heigth on .sp-field-customFormatter doesn't behave correctly in the page version.
The parent DetailsRowCell gets a CSS style with min-height: 42px and the actual cell is wrapped in an un-classed div. This seems to have for effect to stop propagation of the min-height: inherit style.
Adding a min-height: 42px on the cell, or adding min-height: inherit to the unmarked div fixes it.

Something like  { "style": {"min-height": "42px"} } in the column formatter.

Of course, that's not as good as correctly propagating the min-height: inherit, but it's the best I could think of (without being in MS).

**Comment by dexteerz** [comment]
I think it has something to do with it. I've had the same problem since April 27th.
Even with the formatting applied in the list view, columns are being displayed in webparts on pages.
Webpart Page:

![image](https://user-images.githubusercontent.com/11621793/57054674-81b68100-6c6c-11e9-9772-4028a1500bc4.png)

List:
![image](https://user-images.githubusercontent.com/11621793/57054705-9eeb4f80-6c6c-11e9-822e-0af84f9f447d.png)

**Comment by LHMinu** [comment]
Hello! There seems to be an issue with how Column Formatting and View Formatting are being displayed in Web Parts.
There is an official thread going on in this link:
https://techcommunity.microsoft.com/t5/SharePoint-Developer/Column-formatting-not-showing-when-view-shown-in-a-List-Web-Part/m-p/161460/highlight/false#M4381

Hope you find the information useful!
