### ISSUE TITLE
Exit classic experience showing

### ISSUE THREAD

**Issue by alecaceaes** [SharePoint/sp-dev-docs#2341]
I tried recreating the steps above but I got a different output. There is a div above the list that has an anchor link that says Exit classic experience and it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7795f659-9cc4-310b-1ea6-9842a6a2930a
* Version Independent ID: cfc98572-f913-6f48-cfe4-1b9dd526d7fc
* Content: [Get started creating SharePoint-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by alecaceaes** [comment]
![image](https://user-images.githubusercontent.com/16571466/43952412-77893c64-9cc8-11e8-92ee-229c7f13f721.png)

**Comment by andrewconnell** [comment]
@alecaceaes Appears that was a temporary rendering issue that's since been resolved in SPO.

@babaneko30 If you have a different issue, can you please open a separate issue as what you describe is unrelated to the OP. Thanks!
