### ISSUE TITLE
How to apply theme tokens to border-bottom

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2344]
This doesn't work
border-bottom: 1px solid "[theme: listItemBackgroundHovered, default: #f4f4f4]";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-theme-colors-in-your-customizations.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
You can do this by setting those properties separately rather than using the shorthand `border-bottom` attribute. So, this should take care of the issue:

```css
border-bottom-width: 1px;
border-bottom-style: solid;
border-bottom-color: "[theme: listItemBackgroundHovered, default: #f4f4f4]";
```
