### ISSUE TITLE
Connecting to an excel 

### ISSUE THREAD

**Issue by Minuntomb** [SharePoint/sp-dev-docs#2351]
Is it possible to connect a web part to excel, using this method? I wanted to create a web part that has a design similar to this that uses connection to excel. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
That really depends on what exactly "connecting" to Excel means in this context. You can certainly use Excel REST APIs from SPFx web part - https://docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-rest-api, but not sure if that's the objective here.
