### ISSUE TITLE
can we check if the same package loaded twice on the page?

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2354]
_From @veeramanx on August 10, 2018 12:1_

we are using private module (equivalent to dll) for logging the issue in SPFx to list. i am not sure if the private module is been downloaded multiple time or one time on the modern page.

we are using the same private module in different web part on the page. Please let me know how does module load at run time.

_Copied from original issue: SharePoint/sp-dev-fx-webparts#593_

**Comment by veeramanx** [comment]
can anyone give any update on this please? i just wanted to know how the modules are loaded at runtime in spfx
