### ISSUE TITLE
How to get App Catalog Site URL from a SPFx Web Part

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2355]
_From @matthong on July 31, 2018 19:56_

From a SPFx Web Part, is there a way to get the tenant's app catalog site URL programmatically? 

## Category

- [x] Question
- [ ] Bug
- [] Enhancement

## Expected or Desired Behavior
Need a way to find the App Catalog site of the tenant programmatically from a Web Part.

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

_Copied from original issue: SharePoint/sp-dev-fx-webparts#584_

**Comment by VesaJuvonen** [comment]
See following blog post from @waldekmastykarz  for the details.

**Comment by andikrueger** [comment]
[Get the tenant app catalog URL using the REST API](https://blog.mastykarz.nl/get-sharepoint-tenant-app-catalog-url-rest-api/) by @waldekmastykarz

**Comment by matthong** [comment]
Thank you Andi and Vesa. The REST API works.
