### ISSUE TITLE
Group Commands in commandset extension

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#2356]
_From @dhanabalramesh on August 3, 2018 12:20_

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Scenario:
> We have created 3 List view command sets "Mark as complete", "Create reminder" and "Update as Pending" based on a client requirement and we managed to make it work in a single package. Challenge came when customer asked to group the commands under single main menu called "Record Operations"

#### Client expectation:
![image](https://user-images.githubusercontent.com/20179657/43480762-d38a1f6e-9521-11e8-8880-7f15cc2e5624.png)

#### Question:
Is it possible to group those command sets under single menu item say "Record Operations". Same behavior as "New", "Upload", "Flow" etc.. which has sub menu items (Files, Folders) inside main menu item (Upload). I'm not able to find any help from web site so far. Examples or keyword to search on how approach this functionality will be highly helpful.

Thanks in advance experts!
Sharing is caring.

_Copied from original issue: SharePoint/sp-dev-fx-extensions#149_

**Comment by lijunle** [comment]
This is a dup of https://github.com/SharePoint/sp-dev-docs/issues/2294

**Comment by andikrueger** [comment]
Are there any new information available? This is a real blocker in creating List View Command Sets. Even the workaround in using a Drop-Down-Control is not the way to go. This really should be native.
