### ISSUE TITLE
Run provider-hosted low-trust SharePoint addin from provider side

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [SharePoint/sp-dev-docs#2359]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello. Is it possible to run provider-hosted low-trust SharePoint addin from provider side? I already have installed my SharePoint provider-hosted addin on my site. And I want to run this addin from my side. How can I do it?

**Comment by VesaJuvonen** [comment]
Not sure what exactly this actually means... as not understanding the "running addin from your side". You can absolutely have server-side or client-side code in your provided hosted add-in which can or not connect to SharePoint Online. If you explain your objective and scenario, we can most likely help you more easily as that would clarify what you are trying to achieve. Thx.

**Comment by ZaMaZaN4iK** [comment]
@VesaJuvonen Ok, I will try to explain, what I want to do. I am trying to get access to OneDrive and Sharepoint files from provider-hosted addin (in case of some limitations I can't do it with MS Graph API). What I want to do exactly: write some addin, deploy it to a tenant. Then from provider side run my program and e.g. list all files in OneDrive, which is hosted on a tenant, on which I deployed my addin. Is it possible?

As far as I understand, it's not possible, because Sharepoint addin should initiate process: Sharepoint addin goes to Azure, get token, goes to provider-hosted code with this token. Then provider-hosted code goes to Azure with token from Sharepoint addin, get another access token. And with this access token we can work with a tenant. Correct me please, if I am wrong.

**Comment by andrewconnell** [comment]
@ZaMaZaN4iK Yes, you can do that. You create a provider-hosted add-in that is granted the necessary permissions to access OneDrive with delegated permissions (ie: the user grants the app permissions to do this). By definition, provider hosted add-ins are hosted by YOU, the provider of the add-in. One common option: host it in Azure (web app / azure function / etc).

From your [last response](https://github.com/SharePoint/sp-dev-docs/issues/2359#issuecomment-414740146), specifically, the part where you say *Sharepoint addin goes to Azure, get token, goes to provider-hosted code with this token...Then provider-hosted code goes to Azure with token from Sharepoint addin*... SharePoint doesn't do anything with provider hosted add-ins. When it is installed in SharePoint, it's simply *registered*... you deploy & manage the add-in. 

The add-in authenticates with SharePoint to obtain an access token that can then be used to talk to the SharePoint REST API, or used to talk to the Microsoft Graph REST API's endpoint that exposes OneDrive.

Refer to the [docs on how to create a provider hosted add-in](https://docs.microsoft.com/sharepoint/dev/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins).
