### ISSUE TITLE
Sharepoint Online change log questions

### ISSUE THREAD

**Issue by nozhT** [SharePoint/sp-dev-docs#2361]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello, I have a few questions about Sharepoint Online sites' change logs:

1. In Sharepoint Online, can users modify the change log retention period, or is it always fixed to 60 days?
2. Is a site's audit log based on / the same as its change log, or are they totally unrelated?
3. Is the change log guaranteed to reflect all changes in a site, or are there some changes that are by design not included in the change log? For example, I tried editing a .docx file in a document library with Word Online and then querying the web's change log with its REST API, but there was no corresponding ChangeFile event.

**Comment by MarinoValentino** [comment]
Hi @nozhT 

Did you find out anything about point 1?

Thanks

**Comment by JBPuzzled** [comment]
Hi @nozhT & @MarinoValentino,

I'm curious about point 1 as well. I was not able to find the answer yet.

Kind regards

**Comment by nozhT** [comment]
Me neither.
