### ISSUE TITLE
This "documentation" lacks nearly everything

### ISSUE THREAD

**Issue by TheShihan** [SharePoint/sp-dev-docs#2362]
What does the property do? Does it simply stop crawling, does it also remove (existing/already crawled) results from appearing in the search? We don't know, well we have to search the web because it is not here in the official documentation but maybe some user has this secret knowledge... lets ask the elders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a196759c-ca0e-95c2-f18c-14c9719faa26
* Version Independent ID: e6282097-8955-a5cc-863e-ae95bc2957d0
* Content: [SPList.NoCrawl Property (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.splist.nocrawl?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_SPList_NoCrawl)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPList.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPList.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
MSFT is aware of this... see this comment for more info... unfortunately I don't have any additional details or updates to share.

https://github.com/SharePoint/sp-dev-docs/issues/2364#issuecomment-414684429
