### ISSUE TITLE
All server API documentation gone ?!

### ISSUE THREAD

**Issue by D4NT3-CH** [SharePoint/sp-dev-docs#2364]
I was checking few classes and methods and I see that we've lost all the explanations on methods and classes with the migration from msdn to docs !
As we still have on-prem solutions, it is still useful for us to know what happens if we call this or that method on an object.

Would it be possible to recover at least the last version of the summaries, remarks and samples which were available on the previous platform (msdn)? 
I can understand that you will spend effort to maintain the documentation on the client API, but the server API doc as it is now, is totally useless!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d97ce3e-615b-24da-7c4f-3de70886aba7
* Version Independent ID: 7de7634d-bb56-6f1d-7e72-f195d6bf408d
* Content: [Microsoft.SharePoint Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/ns-Microsoft.SharePoint.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/ns-Microsoft.SharePoint.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by zplume** [comment]
Lots of the CSOM API documentation has vanished as well. @VesaJuvonen mentioned that the migration from MSDN to docs.microsoft.com was taking a little longer than expected, so hopefully they will reappear in their new home before too long.

**Comment by VesaJuvonen** [comment]
This is, unfortunately, work in progress due to migration challenges with the MSDN and docs systems. We are working on a solution for this as soon as possible and absolutely understand the urgency for this.

**Comment by D4NT3-CH** [comment]
Thank you both for your comments.

**Comment by TomGroeneboer** [comment]
So any updates on this? The missing CSOM documentation is getting really annoying.

**Comment by nils-a** [comment]
Is there any progress?
