### ISSUE TITLE
Blog site (classic) Posts, Comments, Categories and Photos lists contentclass has changed to STS_View

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-docs#2367]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Using search box (in browser), contentclass:STS_List_Posts or  contentclass:STS_List_Categories, contentclass:STS_List_Comments, you should get a list desired lists in the search results

#### Observed Behavior

contentclass:STS_List_Post does not return anything, but when using contentclass:STS_View you get posts, comments, categories and photos lists on Blog sites.

For some reason the contentclass property has changed to STS_View in all these lists.

#### Steps to Reproduce

No idea, this has behaviour appeared in 3 different tenants.

Thanks for your contribution! Sharing is caring.

**Comment by tavikukko** [comment]
Updated repro steps:

1) create new sitecollection using Blog template
2) when site is ready, use the search in the front page: contentclass:STS_List_Posts (no results)
3) change the search to contentclass:STS_View (you should get some results)

![screen shot 2018-08-15 at 16 47 20](https://user-images.githubusercontent.com/2223355/44152515-6c08e292-a0ae-11e8-9a89-8b041a145548.png)
![screen shot 2018-08-15 at 16 47 03](https://user-images.githubusercontent.com/2223355/44152516-6c23d714-a0ae-11e8-9996-540fe09ce4b5.png)

**Comment by juan-salas** [comment]
We are experiencing this issue with the content class STS_List_Events as well.

**Comment by tavikukko** [comment]
Opened ticket with MS support and they fixed the issue in our tenant (took +2 months and 5 screen sharing sessions). Didn't get any reason why this happened and what the fix was... closing.
