### ISSUE TITLE
Removed methods from SPComponentLoader in 1.5+

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#2376]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect the methods, specifically `getManifests` and `loadComponentById` to still be available in `SPComponentLoader` in SPFx 1.5 and later. These methods are super important if you need to build dynamic and performant solutions. Why have these methods been removed/deprecated? Or do you suggest alternatives to dynamically load SPFx components?

#### Observed Behavior

Aforementioned methods does no longer exist and is marked with *Excluded from this release type:*

#### Steps to Reproduce

Look at the  `.d.ts` files and compare 1.4 and 1.5 for `sp-loader`

**Comment by wictorwilen** [comment]
Bumping this for attention @patmill & @lucaband

**Comment by patmill** [comment]
Sorry - didn't see this the first time round.  So those two methods are marked as Alpha/internal, and we we removed in the great API scrub of '1.5.  Let me see what we can do to move them at least to beta.

Pat.

**Comment by wictorwilen** [comment]
Thanks @patmill  - I can attest that they perfectly and have been for quite a few versions, so feel free to move directly to GA :-)
