### ISSUE TITLE
Bug in Upload the SharePoint workbench instructions

### ISSUE THREAD

**Issue by tomresing** [SharePoint/sp-dev-docs#238]
[X ] Bug
#### Expected or Desired Behavior

Instructions should result in Workbench with no errors
#### Observed Behavior

Error message on workbench.aspx

> Error loading debug manifest script (Error: Unable to load script http://localhost:4321/temp/manifests.js
> Error loading http://localhost:4321/temp/manifests.js
> 
> Ensure loading unsafe scripts is allowed.

![workbencherror](https://cloud.githubusercontent.com/assets/2660081/19425404/d9011080-93e6-11e6-9625-cc29bd0d7b9c.png)
#### Steps to Reproduce

Download the workbench.aspx file to your local computer. To do this:
Open the context menu (right-click) on the "raw" link in the middle of the page and choose Save Target As or Save Link As (depending on your browser) to save the file as workbench.aspx to your local computer.
Upload the file to the Documents library in the dev site collection.
Click on workbench.asps

http://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant

**Comment by waldekmastykarz** [comment]
When navigating to the workbench do you have `gulp serve` running locally as well?

**Comment by tomresing** [comment]
No. Doing the walk through in order, I have not gotten to that step yet. I have gulp installed from a previous run through at the dev kitchen 3, but I didn't have it running. 

------
Tom Resing 
210-264-1263

**Comment by chakkaradeep** [comment]
Can you update your project to current release? We are in [Drop 5 today](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-5), which is way past the devkitchen builds. We moved to HTTPS and have a cert as well to trust, which obviously will not work with devkitchen builds. 

Easiest way to test this would be to update the yeoman SharePoint generator and then create a new project. You can then update your existing devktichen project to Drop 5 by following the instructions [here](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-5#updating-your-existing-projects).

**Comment by Hikmer** [comment]
Can you explain the HTTPS part better?

**Comment by tomresing** [comment]
Is gulp serve required for the workbench running in SharePoint Online? If so, it may just be a matter of reorganizing the steps for getting started. At this point in the tutorial, gulp is not even downloaded yet. 
I'm less worried about getting me unblocked than fixing the documentation for everyone else who comes through later.

**Comment by patmill** [comment]
So a bit of history.  We started off serving the files using http, but this caused the developer to need to allow "mixed" scripts (the page is https and your scripts are http), which is off by default in browsers.  Some browsers give you a small icon saying "allow unsafe script" that you can click on, and others don't.  To ease that problem, we switched to https as the default.  However that prompts up a new unsafe script scenario, where you are downloading https from an unsafe https server.  Iteration 3 is to have a local certificate installed via the `gulp trust-dev-cert` command.

However, the point about the documentation not being clear is a fair point that we can refine.  Additionally, the workbench can be more intelligent about displaying messages on how to proceed.

**Comment by tomresing** [comment]
Would it make sense to remove the step for uploading the workbench.aspx to the dev site library alltogether? It's in one of the earliest set up pages, [Set up your O365 Dev Tenant](http://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant) page. And, when you finally get around to using workbench in [Build your first web part](http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part), it uses the local server, instead.

**Comment by Hikmer** [comment]
Also, mention you need to enable custom scripts in our tenant and WAIT 24 hours.  And show a screen shot of the permissions warning if you don't have it enabled.  That is how I knew when the 24 hour wait was done (I'm impatient) or share the PowerShell to trigger the job (I think that is an option as well).

**Comment by chakkaradeep** [comment]
Workbench as such does not work unless it can interact with your local development environment. The Set up your O365 Dev Tenant is all about setting up and not testing workbench or web parts. This is evident with the local workbench as well, as you need to run _gulp serve_ for the workbench to work. It is the same even if the workbench is running in the server. 

For this preview, developers will need to upload the workbench to a document library so they can complete the [Build your first web part](http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part) tutorial as the tutorial does cover workbench in the server version. 

Now, as we move to GA, we will have workbench available in the service so developers need not upload the workbench separately. Once this is available, the documentation will be updated and will be more of a streamlined experience.

**Comment by tomresing** [comment]
Removing this step once workbench is available in the service will address the issue, in the long run. For now, I would suggest adding a note about the gulp serve dependency in the setup article. With the troubleshooting section next to the upload section, it might imply to some that you should be ready to troubleshoot at that point in the walk-through. It did for me.

**Comment by VesaJuvonen** [comment]
We are planning to do another rounds of tutorial refresh and video re-recordings next week and will accommodate these needed changes in as well.

**Comment by tomresing** [comment]
Good work!

**Comment by chakkaradeep** [comment]
You can now access the workbench from your SharePoint site by browsing to:

```
https://your-sharepoint-site/_layouts/workbench.aspx
```

The [docs](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md) and tutorials are updated to reflect this. However, it will take ~24hrs for the changes to go live in dev.office.com.

**Comment by andrewconnell** [comment]
Any plans to update dev.office.com to point the current NodeJs LTS version (v6) as right now it points to v4 which is no longer LTS (in maintenance mode)?

FWIW, Node stable (v7) seems to work just fine for me

**Comment by Hikmer** [comment]
Does this still require an Office 365 Development Tenant?   Or is this now
available in existing tenants using the Development Site Template?  Would
much rather develop in our own Azure AD tenant than an extra superfluous
environment that causes lots of authentication confusion.

Thanks!

**Comment by patmill** [comment]
@Hikmer - It should be in first release tenants (if not, it is getting rolled out across the farms).  The workbench in _layouts is available everywhere, but you won't be able to deploy / upload / etc. any package on a non-first release / non-dev tenant until it is released wider.

**Comment by Hikmer** [comment]
So we have a First Release group setup for select users.  Does the whole
tenant need to be enabled for first release?  Or will my inclusion in the
group suffice? This part of Office 365 is very confusing

**Comment by andrewconnell** [comment]
@Hikmer First Release is a tenant-wide setting... not for specific parts of O365 / users

**Comment by tomresing** [comment]
@andrew I think you are referring to the "first release for everyone"
option and @Hikmer is referring to "First release for selected users"
https://support.office.com/en-us/article/Set-up-the-Standard-or-First-Release-options-in-Office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47?ui=en-US&rs=en-US&ad=US

**Comment by Hikmer** [comment]
That doesn't answer my question, if I am a member of a first release group
in my tenant, is that enough?

Thanks

**Comment by andrewconnell** [comment]
Wasn’t aware that it changed where you could select specific users for first release. My bad.

**Comment by patmill** [comment]
It is the tenant switch, not the user one, that we should be checking.

**Comment by VesaJuvonen** [comment]
Looking on the original issue and the pointers in the discussion, we should have covered this all. All labs have been also updated to drop 6 level, so closing up this issue. Original issue was around missing the cert setup in the lab. This is clearly now covered in the tutorials.
