### ISSUE TITLE
App Catalog doesn't prompt for Permission Approval for an App that consumes MS Graph and shows an error in application 

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-docs#2384]
Hello,

Thank you for this [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#consume-microsoft-graph), while I was following the steps, I stuck at deployment of the solution. The App UI works fine on local workbench, however to make it functional, I was deploying the package as suggested where it didn't ask me to approve the permissions and app package error message says : Error in Application !

**To create a solution, I have ran following commands:**

npm install @microsoft/generator-sharepoint@latest -g

yo @microsoft/sharepoint --plusbeta

And, My package file looks like as follows:

![image](https://user-images.githubusercontent.com/13658386/44340915-fdd4b400-a4a3-11e8-9034-a045a827d462.png)

And to build and deploy the package, I ran following commands:
gulp build
gulp bundle --ship
gulp package-solution --ship

However, while uploading the package it doesnt ask for the permission approval and I can see the package without Title in App catalogue as follows with App package error message : Error in Application !

![image](https://user-images.githubusercontent.com/13658386/44341674-38d7e700-a4a6-11e8-8b62-67385d4461b4.png)

Would you please address why it's behaving this way ? What am I missing to follow ?

Thanks and Best Regards,
Dipti Chhatrapati

**Comment by nikskhubani** [comment]
Hi Dipti, 

can you share what does the **App package error message** says as pointed in this screenshot:

https://content.screencast.com/users/AshaKhubani/folders/Jing/media/eecb485e-4760-4d13-b534-ab43ba776d98/2018-08-20_1753.png

**Comment by gautamdsheth** [comment]
Most likely your tenant doesnt have the required capabilities available.

The `AadHttpClient` and `MSGraphClient` are currently in preview. So, they only work on Microsoft Demo tenants created via [this link](https://demos.microsoft.com/Login) or if you have enabled Targeted release capabilities for all users in your tenant. If you have recently enabled Targeted release (all users) in your tenant, then you need to wait upto 24 hours for them to be available.

To enable Targeted release, 

1) Go to your Office 365 admin center
2) Navigate to Settings > Organisation Profile
3) Next to Release preferences, click Edit
4) Select **Targeted release for everyone** and then Yes
5) After that wait for upto 24 hours.

![download](https://user-images.githubusercontent.com/8832018/44346464-9888bf00-a4b3-11e8-9e41-218679dddcfb.png)

**Comment by dips23** [comment]
Much helpful ! Thanks, I have updated the settings in O365 admin center as
suggested and I will check after 24 hours whether app is working as
expected !

Best,
Dipti Chhatrapati

**Comment by dips23** [comment]
AWESOME and It worked so smoothly before 24 hours ;) - Thank you for addressing the missing point !

![image](https://user-images.githubusercontent.com/13658386/44382003-b811fd00-a530-11e8-8fbd-159b26051e5f.png)

**Comment by gautamdsheth** [comment]
Super ! Happy to help, you can now close this issue.

**Comment by VesaJuvonen** [comment]
Thanks, @dips23 for confirming and @gautamdsheth for the assistance around the question. These capabilities will go GA with upcoming 1.6, but until then they only work with targeted release tenants, as noted here. That 24 hour wait time with the status change in tenant level is also slightly confusing, but it's what's needed at least for now. Great to see that you got this solved and thanks for sharing your input.
