### ISSUE TITLE
"requested range does not exist in the sheet" when trying to open a spreadsheet in Office365

### ISSUE THREAD

**Issue by htlwb** [SharePoint/sp-dev-docs#2386]
"The requested range does not exist in the sheet" when trying to open a spreadsheet in Office365; the problem is that I did not specify a range when trying to open the workbook (is such a request even possible), and now I cannot open the workbook in Office365 no matter what I try. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6776e238-9b67-10d0-f0b6-6d1a3727bc70
* Version Independent ID: 87557f26-216b-6e63-bd79-57b1753255cb
* Content: [Excel Services Error Codes](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-error-codes)
* Content Source: [docs/general-development/excel-services-error-codes.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/excel-services-error-codes.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Chaz6** [comment]
I have this problem when trying to share a *.xlsb with macros on Sharepoint/OneDrive with Office365. I would like to be able to send a direct link to download the file, but instead Office Online tried to open it with an error.

**Comment by Jamalc0m** [comment]
Any solution for this ?

**Comment by patmill** [comment]
Sorry - this is outside the scope of this list.  Is it possible to open a support ticket with the product?

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. Unfortunately, as your issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.

**Comment by htlwb** [comment]
Nope. Don't care enough about it to take the time to make sure Microsoft's
mistakes get fixed. They don't care, then I don't care.

Regards,

Larry Bradley
281-216-5460

**Comment by Chaz6** [comment]
This affects *every* tenant, there is no point in having every admin report it individually. @andrewconnell surely you can raise it internally through the appropriate channel?

**Comment by htlwb** [comment]
The appropriate channel would be?
Regards,

Larry Bradley
281-216-5460

**Comment by andrewconnell** [comment]
Within the Office 365 tenant admin portal, there's a place to submit a support request. This issue list is for developer-related issues. I know it seems weird, but there's no way in their system to escalate non-developer issues to product support. Product support (via the way I describe above) is how I'd have to submit it as well. 

You see the issue so it's best if YOU submit the support request and have support work directly with you...

I don't have the ability to raise the issue internally... I have the same access you have.

**Comment by htlwb** [comment]
This is not an enterprise edition problem. I personally subscribe to
Office365. I suppose you would call it the "Home" or "Personal" edition? (I
think mine is "HOME" edition). Does HOME edition have an "Office 365 tenant
admin portal?" Or are you telling me there is no support for my problem for
the HOME edition? Or maybe I just need to Google the solution? Sorry, but I
am really trying to figure out how to solve my issue the best way I can.

Regards,

Larry Bradley
281-216-5460

**Comment by andrewconnell** [comment]
When you go to https://portal.microsoft.com, you don't have a support option?

![image](https://user-images.githubusercontent.com/2068657/61185358-772e4580-a626-11e9-8662-2bf4a5e07abe.png)

**Comment by htlwb** [comment]
No. I am a little surprised that you don't know that Personal/Home accounts
do not have access to this portal.
[image: image.png]
Regards,

Larry Bradley
281-216-5460

**Comment by andrewconnell** [comment]
One can't know _everything_ about Office 365 / SharePoint... it's huge! :) Let me look into it and follow up...

**Comment by htlwb** [comment]
Nothing personal. I am certain you have expertise in enterprise, maybe
there is another group that handles Personal/Home? At any rate, much thanks
for your help and tenacity.

Regards,

Larry Bradley
281-216-5460

**Comment by andrewconnell** [comment]
Looks like this is the correct location to post personal support requests:
https://support.microsoft.com/contactus

_BTW, when you're replying by email to these threads, your phone number is included in each post as part of your signature for all to see. You can edit your previous comments via the site if you don't want that._

**Comment by htlwb** [comment]
Great. Thanks. Will do on the signature thing.
Regards,
