### ISSUE TITLE
Modern sites(Teams & communications) not inheriting Content types from Content type Hub

### ISSUE THREAD

**Issue by AjeshKakkoprath** [SharePoint/sp-dev-docs#2387]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When a new site collection is created,  custom site columns and content types are automactically inhertied to the new site collection from Content type hub. 

#### Observed Behavior

For Modern site templates ( Teams and communications) custom site columns and content types are not inherited from the CT Hub.

#### Steps to Reproduce

- Create custom site columns and content types in CT Hub and publish it
- Create a Modern Teams or Communications site .
- Check for the custom site columns and content types in the newly created site. This will be missing there.

**Comment by dscherry15** [comment]
Any update on this?  We have the same problem.

**Comment by westerdaled** [comment]
1), I am assuming you are (both) using the content type hub for your tenant, as this gets created on your behalf with all site features enabled 
`https://[tenant].sharepoint.com/sites/contenttypehub`
2) Each time you change one of your content types you will need to publish or republish it - I am assuming you doing this anyway
3) On each of the Team or Communication Sites, I believe that you need an additional step in the settings: click on Content Type Publishing (/sites/yoursite/_layouts/15/contenttypesyndicationhubs.aspx)
and check the checkbox: _[ ] Refresh all published content types on next update_  ,then click OK.
You may notice a list of subscribed content types, below the Term Store name.

Each time I check this box in my FR dev tenant I get **Sorry, you don't have access**.  So I end up requesting access, even though I created every site, I am site collection admin , Site Owner and Global Admin. (go figure!) . Please feedback if you get the same issue.
I am able to use all published content types in any of my Team and Communication sites after the timer job delay.

**Comment by dscherry15** [comment]
Ours finally propagated without any additional changes.  It took Modern
Team Site and Communication Sites much longer than classic sites for some
reason.

**Comment by westerdaled** [comment]
Good news. I does beg the questions: when and why, we have to use the Content Type Publishing option in any of the Modern Team Site and Communication Sites? Also is the list of subscribed content types updated automatically?

**Comment by dscherry15** [comment]
I kept content type publishing off and it still propagated (albeit much
later).  So that is not required.  With "Hub Sites" and a host of changes
coming, I wonder if the content type hub model for the tenant (where you
have to publish globally) is going away.  Perhaps in the new model you can
create content types at the hub site and publish to associated sites?  Just
a guess.  Maybe we'll see after ignite.

**Comment by westerdaled** [comment]
Hi

I think you may be right: Each hub site able to publish content types to any of the associated sites.  Vesa did say that Content Type Hubs _weren't getting my love within Microsoft._  I am with him as there are so unreliable - waited all day for Expiry Date field  to propagate to my comm site.

**Comment by schoier** [comment]
Is there any alternative to using Content Type Hub when having templates associated with the content types (document content types with word file templates)?
I have been using PnP to creata new sites with the same content types declared in the PnP-xml file, but I haven't found any way to provision content types with associated templates this way.

**Comment by saulpreciado** [comment]
@VesaJuvonen any chance there's a light at the end of the tunnel for this one? Or, any direction we should be taking now to avoid redos in the near future?

**Comment by praveenbattula** [comment]
Any update to this thread? I am seeing this since quite some time but its not getting any better. We have site designs, flows in different solutions which is part of our site creation process. Upon site creation we have to provision artifacts like libraries, lists and pages. As the content types from content type hub are taking hell lot of time like between 2-3 hrs before they appear in new sites we cannot create lists/libraries (We can theoretically but without content types - no use) as they need content types. We have no solution how to automate this site provisioning process fully. Hate these incomplete solutions. 

We cannot run the Azure automation runbooks every 30 mins as they just run and no use for most of their running time. It is waste of azure billing to my company. Any ideas?

**Comment by jklevel** [comment]
This is still a problem. 
Should we forget the ContentTypeHub ?
Anybody know?

**Comment by gabbsmo** [comment]
I just tested to created a modern team site and communication site and found that the Content Type Publishing link is no longer in Site Settings. Opening url manually (/_layouts/15/contenttypesyndicationhubs.aspx) takes you to the generic "Something went wrong" page. Something is happening here but we do not know what.

Some update from Microsoft about what is happening to the content type hub in relation to modern pages would be helpful.

**Comment by kinsl4yer** [comment]
@gabbsmo This particular thing is sorted by activating the "SharePoint Server Publishing Infrastructure" feature in "Site collection features".
The option "Content Type Publishing" appeared, despite of activation error.

**Comment by ravick4u** [comment]
> Any update to this thread? I am seeing this since quite some time but its not getting any better. We have site designs, flows in different solutions which is part of our site creation process. Upon site creation we have to provision artifacts like libraries, lists and pages. As the content types from content type hub are taking hell lot of time like between 2-3 hrs before they appear in new sites we cannot create lists/libraries (We can theoretically but without content types - no use) as they need content types. We have no solution how to automate this site provisioning process fully. Hate these incomplete solutions.
> 
> We cannot run the Azure automation runbooks every 30 mins as they just run and no use for most of their running time. It is waste of azure billing to my company. Any ideas?

we are in the same situation

**Comment by StevieBleeds** [comment]
The only way I've been able to workaround it is to build a script that provisions a SharePoint team site using a Classic template, so the Content Types are provisioned via the CT Hub. 

Once that's completed, the script then creates an Office 365 Group and then it creates the Teams channel (using the MS Teams cmdlets). Teams then uses the newly created SharePoint site as it's default SharePoint site.

**Comment by westerdaled** [comment]
@StevieBleeds  I agree with your approach re the CT hub. Indeed, we have made an informed decision to keep using the CT Hub until there is an obvious migration path to the this mythical "Hub site syndicates the content types to associated sites or whatever it ends up being" .  Replacing  the CThub with site designs and,  or provisioning scripts has no business value, I could sell to our various stakeholders.

**Comment by ravick4u** [comment]
@StevieBleeds Are you using Modern Team Site without Group Template? Does your content type come immediately with the template you are using?

**Comment by StevieBleeds** [comment]
I’m using the Classic Team Site template to provision the site, which then provisions the content types via the CT Hub. Once that’s been done, an associated O365 group is spun up which provides the in-place modernisation of the site.

**Comment by ravick4u** [comment]
@StevieBleeds When you create a modern site it does publish content type via content type hub but the problem is it takes time. What I would like to know when you create site with Classic Team Site does it publish content type immediately or it takes 2-3 hours for the content type to be available.

**Comment by StevieBleeds** [comment]
Yes, it publishes it within minutes when used in conjunction with the -Wait parameter.

Create-PnPTenantSite -Title $title -Url $url -Template STS#0 -Wait

**Comment by ravick4u** [comment]
@StevieBleeds We are using STS#3 template to create the site which creates Modern Team Site but without groups. I might have to try "-wait" parameter to see if that does the trick for me. I highly doubt but will give it a try.

Thanks again.
