### ISSUE TITLE
Thoughts around Knockout and WebParts

### ISSUE THREAD

**Issue by patmill** [SharePoint/sp-dev-docs#239]
Posting on behalf of @davros85

Is this a simpler and more effective way of integrating Knockout?
https://codeforcloud.com/2016/10/17/sharepoint-framework-knockoutjs-simplifying-properties-with-an-event-bus/

@manishgarg1

**Comment by davros85** [comment]
...ps agree that <any> is ugly... Just thought this approach feels cleaner?

**Comment by davros85** [comment]
Should say "< any >" is ugly above...

**Comment by patmill** [comment]
Closing for now.
