### ISSUE TITLE
Issue with the documentation example

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#2390]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I followed this tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

#### Expected or Desired Behavior

On clicking search, see the following:

![image](https://user-images.githubusercontent.com/6519992/44418208-99aa0280-a52c-11e8-936b-99b3e7ca3858.png)

#### Observed Behavior

On clicking search, see no matches

#### Steps to Reproduce

On running gulp serve --nobrowser and clicking search, I see no matches:

https://user-images.githubusercontent.com/6519992/43025195-a9a249d8-8c25-11e8-9496-349b37d21e9f.JPG

https://user-images.githubusercontent.com/6519992/43025196-a9c3af56-8c25-11e8-950a-c4121d2e687f.JPG

**Comment by andrewconnell** [comment]
Can you confirm this is still an issue? Since posting this, the Microsoft Graph & Azure AD support in SPFx was updated and released to GA.
