### ISSUE TITLE
View formatting schema references incorrect column formatting schema URL

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2391]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The view formatting schema (https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json) should have the correct references.

#### Observed Behavior

The view formatting schema references the column formatting schema using an invalid url. It is currently referencing `https://developer.microsoft.com/en-us/json-schemas/sp/column-formatting.schema.json` in 2 spots. Both of these should point to `https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json`.

#### Steps to Reproduce

Create a new .json file in VS Code and set the schema to https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json. Here are the errors:

![image](https://user-images.githubusercontent.com/8364109/44423722-d1c53b80-a554-11e8-844d-30c35234add3.png)

**Comment by ldemaris** [comment]
Thanks for reporting.  We will update the schema soon.

**Comment by VesaJuvonen** [comment]
Schema files have been now updated, which should resolve this issue. Can you @thechriskent confirm that it's the case and we'll close this one. Thx.

**Comment by thechriskent** [comment]
Looks great! Thanks!
