### ISSUE TITLE
View Formatting schema - hideColumnHeaders should be hideListHeader

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2392]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The view formatting schema (https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json) should have a property called `hideListHeader`.

#### Observed Behavior

The view formatting schema has a property called `hideColumnHeaders`. This property is actually `hideListHeader`.

**`hideColumnHeaders`**
![image](https://user-images.githubusercontent.com/8364109/44423959-82cbd600-a555-11e8-874b-78e55bf88e09.png)

**`hideListHeadder`**
![image](https://user-images.githubusercontent.com/8364109/44423972-8d866b00-a555-11e8-928d-7e16bbc6dddd.png)

#### Steps to Reproduce

Create a view format and set `hideColumnHeaders` to true and see nothing happen when applied to a view. Change that to `hideListHeader` still with a value of true and watch the list header disappear when applied to a view.

**Comment by ldemaris** [comment]
Thanks for reporting.  We will update the schema soon.  "hideColumnHeader" is what the schema should contain.  "HideListHeader" also works but won't be in the schema.

**Comment by VesaJuvonen** [comment]
Schema files have been now updated, which should resolve this issue. Can you @thechriskent confirm that it's the case and we'll close this one. Thx.

**Comment by thechriskent** [comment]
Everything looks great, thanks!
