### ISSUE TITLE
Column Formatting schema still missing Title attribute (despite being allowed)

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2393]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The title property under element attributes should be in the Column Formatting schema (https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json). Something like:

```JSON
"title": {
  "description": "Specifies the title attribute",
  "anyOf": [
      {
        "$ref": "#/definitions/expression"
      },
      {
        "type": "string"
      }
  ]
}
```

#### Observed Behavior

The title property under element attributes is not listed in the schema (despite being whitelisted and allowed by column formatting). This causes this field to be flagged in VS Code as invalid.

#### Steps to Reproduce

Open the [person-roundimage-format](https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/person-roundimage-format) sample in VS Code and observe this error:

![image](https://user-images.githubusercontent.com/8364109/44424402-05a16080-a557-11e8-99b7-b664c643f278.png)

Now apply it to a person field and see that the title attribute is successfully added anyway.

**Comment by ldemaris** [comment]
Thanks for reporting.  We will update the schema soon.

**Comment by VesaJuvonen** [comment]
Thx @thechriskent, it does help if you merge stuff to the right branch to get it out... well - that was stupid of me, but not the first time. Files are now out. Notice also that we moving to versioned URLs - old ones will work for now, but will be soon removed. New URLs are as follows. We will be updating docs etc asap.

• SP2019 supported one - https://developer.microsoft.com/en-us/json-schemas/sp/v1/column-formatting.schema.json
• SPO supported one - https://developer.microsoft.com/en-us/json-schemas/sp/v2/column-formatting.schema.json 

View formatting under v2. Can you please also confirm these changes, so that we can close this. Thx.

**Comment by thechriskent** [comment]
I see the changes to the standard and can see v1 (without the changes). However, v2 isn't resolving just yet.

In the meantime, I am all for versioning! I think it's a great idea, but I'm a little confused by the proposed versions and perhaps I'm just missing something:

- Moving View Formatting to v2 with no v1 seems confusing and inaccurate
- If adding `title` to Column Formatting were a feature change, then I think a v2 of the schema would make sense. However, `title` has been working for a long time it just wasn't in the schema so really this is just a bug fix as there isn't a version of CF that doesn't include `title` (including the SP2019 version). So, I don't think moving to v2 makes sense just yet
- The main difference between SPO Column Formatting and SP2019 Column Formatting is the use of Excel-style expressions (which aren't reflected in the schema)

Here are my conclusions:

- Schema versioning only needs to increment when there are changes that require you to target different versions
  - List Formatting doesn't look at the schema at all (as far as I can tell) and there isn't a way in SPO to target previous versions
  - So only Column Formatting for SP2019 needs to have a fixed schema version (which is currently the same for SPO since both support `title`)

Here are the schema URLs I would propose
- https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json
- https://developer.microsoft.com/json-schemas/sp/column-formatting-2019.schema.json
- https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json

> Note the removal of `en-us`
> The 2 column-formatting schemas would be identical for now, but all the AST versions in the samples library could be updated to use the 2019 schema to make it more obvious why they exist and isolate them from future enhancements/changes in SPO

---

As a side note, I think these schema files could be FAR more useful than they are. It's slightly outdated now, but please take a look at this extended schema I put together: https://gist.github.com/thechriskent/2e09be14a4b491cfae256220cfca6310

By providing the actually supported values for things like style properties (since these WILL be different between SP2019 and SPO) you can indicate far more to users. Right now, unless you crack open the code, there is no way to know a style property isn't supported until it isn't applied since these are whitelisted.
