### ISSUE TITLE
Column Formatting includes unusable box-pack style but not justify-content

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2396]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Column Formatting allows most flex-box related style attributes including `flex`, `flex-direction`, `flex-wrap`, `align-items`, etc. It should also allow `justify-content`

#### Observed Behavior

`justify-content` is NOT included, but the deprecated and unsupported `box-pack` is allowed ([browser-compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack#See_also#Browser_compatibility)).

In addition, the following attributes are allowed, but are also deprecated members of the original CSS Flexible Box layout Module draft:
- `box-orient`
- `box-direction`
- `box-align`

- `blox-flex`
- `box-flex-group`
- `box-lines`
- `box-ordinal-group`

This attribute is not deprecated, but is not supported in either IE or Edge:
- `box-decoration-break`

#### Steps to Reproduce

Try and use `justify-content` in a format and see it isn't applied

**Comment by thechriskent** [comment]
A similar example to add to this issue is that `overflow-style` is allowed despite having no major browser support, but `text-overflow` is not allowed. This makes me sad.

**Comment by ldemaris** [comment]
We will include justify-content soon.

**Comment by ldemaris** [comment]
Oh, and text-overflow as well.

**Comment by thechriskent** [comment]
`justify-content` is now allowed, yay!

But still not seeing `text-overflow` so leaving this open for now
