### ISSUE TITLE
Unable to upload workbench.aspx to an old created developer Site Collection

### ISSUE THREAD

**Issue by rgarita** [SharePoint/sp-dev-docs#24]
Hello

I have an old Developer Tenant. **About 2 years old**. I was trying to use the originally provisioned Developer Site Collection, but when I was trying to upload the **workbench.aspx** file, I got many issues. I got a lot of access denied errors. Even on SP Designer

What I did to make it work was, spin up a new fresh developer site collection. On the new one, I was able to upload the workbench.aspx file successfully

**I was wondering, if may help put something on the documentation suggesting create a new developer site col.**

<img width="238" alt="2016-08-19_0-09-52" src="https://cloud.githubusercontent.com/assets/161268/17800544/5257c614-65a1-11e6-8114-d953395180af.png">

**Comment by VesaJuvonen** [comment]
thx Raul,
added note on this to the guidance. Issue what you see is pretty strange, since that would imply that you can't upload any files to that site collection. workbench.aspx is just normal file to upload. Have though added a short note on the wiki at https://github.com/SharePoint/sp-dev-docs/wiki/Setup-SharePoint-Tenant.

**Comment by SPDoctor** [comment]
Yes, you need to create a developer site collection per the instructions - if you use the default root site collection you get access denied uploading the workbench.aspx. You can upload other file types - I think aspx is blocked but I didn't really dig any deeper.

**Comment by nyn3x** [comment]
@SPDoctor you can't upload aspx-pages to the root-site-col because of the deactivated scripting (see https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f)

I activated scripting in the root site using powershell like this:

```
Connect-SPOService -Url https://[tenant]-admin.sharepoint.com -Credential [user]@[tenant].onmicrosoft.com
Set-SPOsite https://[tenant].sharepoint.com -DenyAddAndCustomizePages 0
```

**Comment by SPDoctor** [comment]
Thanks @nyn3x for pinpointing the reason.
