### ISSUE TITLE
Drop 5 not available and Documentation issue.

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#240]
I still get only version 0.2.1 but not version 0.3.0 because it is not a valid version.

The npm registry also shows the [wrong version](https://www.npmjs.com/package/@microsoft/generator-sharepoint)

In additon there is a bug on the [drop 5 release note](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-5).
"@microsoft/sp-webpart-base": "~0.1.0",
As far as i've seen not part of previous versions so this entry needs to be newly added and the version number cannot be updated.

**Comment by patmill** [comment]
Unclear why we wound up at 2.1 rather than 3.  I believe it is the current version though (when I tried it on my home machine).  

I've updated the drop notes accordingly.  Thanks for the heads up.

**Comment by StfBauer** [comment]
Great!

**Comment by patmill** [comment]
:(  What did I forget this time?

**Comment by StfBauer** [comment]
Sorry @patmill. :( I'm on version 0.2.1 but the package json doesn't contain @micrsoft/sp-webpart-base

```
{
  "name": "spfx-test-2",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@microsoft/sp-client-base": "~0.4.0",
    "@microsoft/sp-client-preview": "~0.5.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~0.7.0",
    "@microsoft/sp-module-interfaces": "~0.4.0",
    "@microsoft/sp-webpart-workbench": "~0.5.0",
    "gulp": "~3.9.1"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp nuke",
    "test": "gulp test"
  }
}
```

**Comment by patmill** [comment]
Ah, yes.

So the new code that will be getting updated will be in sp-webpart-base.  There was some concern that because some of the properties had changed, we shouldn't default to using it in this drop, but we will switch in the next one.  I'll add some additional comments around this.  Thanks.

**Comment by StfBauer** [comment]
Nice thanks!

**Comment by StfBauer** [comment]
@patmill sorry but soon you gonna hate me ;)

Is "@microsoft/sp-webpart-base": "~0.1.0" a devDependencie or a dependencie?

**Comment by kmees** [comment]
Dependency

**Comment by patmill** [comment]
Hopefully it is much more clear now.  Sorry for the confusion, and thanks for the feedback.
