### ISSUE TITLE
Documentation chapters

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-docs#2400]
Hi,

Could this documentation about how to deploy SPFX be under SPFX menu and also specify how to deploy SPPKG the simplest way ?
Let's think about developers or simple sharepoint administrator trying to deploy an .sppkg file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by LarryAngama** [comment]
Sure ! It would be great !

**Comment by andrewconnell** [comment]
Respectfully, it doesn't make sense for them to be under the SPFx topic in the TOC because the ALM APIs are not specific to SPFx... they can be used for deployment of `*.sppkg` packages which can also include add-ins. They make more sense as a general API reference where the other APIs are listed.
