### ISSUE TITLE
gulp trust-dev-cert must be run from the project folder, otherwise you get an error

### ISSUE THREAD

**Issue by samboustani** [SharePoint/sp-dev-docs#2401]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x ] Additional article idea

#### Expected or Desired Behavior

Install and trust certificate

#### Observed Behavior

Error: "No gulpfile found"

#### Steps to Reproduce

Follow setup instructions and install the developer certificate without changing folders (no instructions to change folders in the article).  Going into a newly created project folder where you generated a new project using yo and running gulp trust-dev-cert returns a successful status.

**Comment by TheMiao** [comment]
Hi @samboustani 
It should be a easy fix, I presume you have navigated to wrong path. 
You should use CD to navigate the specific project folder. Once you have navigated to correct project folder, you will find gulpfile.js if you use DIR to check your project folder
Than, you can install and trust certificate.

**Comment by andrewconnell** [comment]
The [instructions in creating your first web part tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) do say to run this command from within the project directory. I'll add some additional information on the dev environment setup that addresses this as well.
