### ISSUE TITLE
Samples in column-formatting.md should be updated to new schema location

### ISSUE THREAD

**Issue by aaronmi** [SharePoint/sp-dev-docs#2402]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Samples in the article are using correct schema location:
"$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",

#### Observed Behavior
Samples in the article are using incorrect schema location:
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
  
#### Steps to Reproduce
See each samples in the article:
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Merged and published now with the PR #2382. Thanks @thechriskent for taking care of this.
