### ISSUE TITLE
List Formatting style whitelisting typo: flex-basic instead of flex-basis

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2403]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It is expected that list formatting would allow the `flex-basis` style attribute.

#### Observed Behavior

There is a typo in the style attribute whitelisting. `flex-basic` is allowed despite NOT being a CSS property and `flex-basis` is therefore blocked:

![image](https://user-images.githubusercontent.com/8364109/44481795-b6216a00-a614-11e8-98d6-e1daffa777c7.png)

#### Steps to Reproduce

Try and use `flex-basis` and nothing will be applied. Use `flex-basic` and it will get applied despite not being a valid property.

**Comment by shagra-ms** [comment]
Thanks for reporting this @thechriskent. This has been fixed and would be rolled out in upcoming updates.

**Comment by shagra-ms** [comment]
The fix has been rolled out. Let me know if this is still broken for you. Thanks!
