### ISSUE TITLE
Please add some documentation

### ISSUE THREAD

**Issue by nils-a** [SharePoint/sp-dev-docs#2404]
The old Docs had more descriptions of parameters and return-values. Please add those descriptions here. 
I.e. Explain what is returned? StaticName, InternalName?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1226606-b6eb-a7ec-3f96-c36d89818941
* Version Independent ID: 1c3e4993-800a-eef2-7fd9-766412074697
* Content: [SPFieldCollection.AddLookup Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spfieldcollection.addlookup?redirectedfrom=MSDN&view=sharepoint-server#overloads)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPFieldCollection.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPFieldCollection.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Microsoft is aware of this... some docs didn't port across in the migration from MSDN => docs... unfortunately I don't have an update on the status of this. See this comment for more details:

https://github.com/SharePoint/sp-dev-docs/issues/2364#issuecomment-414684429
