### ISSUE TITLE
Issue with Node LTS 8.xxx

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-docs#2405]
Please document this quick fix ?
https://github.com/sharepoint/sp-dev-docs/issues/1002

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This should not be necessary if you are running the latest version of the Yeoman generator for each supported version of SPFx. This setting was only necessary for a short time between two releases of SPFx.

IOW...

- SharePoint Server 2016 FP2 (SPFx v1.0.1) is only supported on Node.js v6
- SharePoint Server 2019 (SPFx v1.4.1) is only supported on Node.js v8
- SharePoint Online (SPFx v1.7.1) is only supported on Node.js v8
