### ISSUE TITLE
out-of-date content

### ISSUE THREAD

**Issue by tristian2** [SharePoint/sp-dev-docs#2406]
hi,
some folks are getting confused about public websites and anonymous access in sharepoint online.  thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68dc2cd4-72a3-5ce6-37bd-0b2eb4fb7e2e
* Version Independent ID: f231f242-0207-557a-9c04-4aadecec6bf8
* Content: [Create SharePoint Add-ins that can be used by anonymous users](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-sharepoint-add-ins-that-can-be-used-by-anonymous-users)
* Content Source: [docs/sp-add-ins/create-sharepoint-add-ins-that-can-be-used-by-anonymous-users.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-sharepoint-add-ins-that-can-be-used-by-anonymous-users.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
I'm sorry to hear about the confusion. Public websites from Office 365 are no longer possible. Did you have a specific question or concern with this document? Thanks!
