### ISSUE TITLE
Error while calling sphttpclient SPFX extension

### ISSUE THREAD

**Issue by Shamrh** [SharePoint/sp-dev-docs#2408]
Just following the SP starter kit code for adding the footer menu. This error is occurring in SPTaxonomyService and SPUserProfileService. 

#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

[21:27:31] Error - typescript - src\services\SPTaxonomyService.ts(46,13): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((url: string, configuration: SPHttpClientConfiguration, options: ISPHttpClientOptions) => Promis...' has no compatible call signatures.

Package.json

{
  "name": "footer",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "build:dev": "gulp clean && gulp bundle && gulp package-solution",
    "build:prod": "gulp clean && gulp bundle --ship && gulp package-solution --ship",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.5.0",
    "@microsoft/sp-application-base": "1.5.0",
    "@microsoft/sp-core-library": "1.5.0",
    "@microsoft/sp-dialog": "1.5.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.5.1",
    "@microsoft/sp-webpart-base": "~1.4.1",
    "@pnp/common": "^1.0.4-4",
    "@pnp/logging": "^1.0.4-4",
    "@pnp/odata": "^1.0.4-4",
    "@pnp/sp": "^1.1.4",
    "@pnp/spfx-controls-react": "1.4.0",
    "@pnp/spfx-property-controls": "1.7.0",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-core": "^9.6.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "@microsoft/sp-listview-extensibility": "~1.4.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.5.0",
    "@microsoft/sp-module-interfaces": "1.5.0",
    "@microsoft/sp-webpart-workbench": "1.5.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by wictorwilen** [comment]
First, ensure that all your `@microsoft/sp-???` dependencies are on the same version. You have a mix of 1.4.1, 1.5.0 and 1.5.1. Then remove the node_modules folder and package-lock.json and run `npm install`.

**Comment by Shamrh** [comment]
Wictor,

Will do the changes and let you know

**Comment by Shamrh** [comment]
I have updated the to correct versions now I am getting a different error.

**here is my package.json**

{
  "name": "share-point-portal-showcase",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "build:dev": "gulp clean && gulp bundle && gulp package-solution",
    "build:prod": "gulp clean && gulp bundle --ship && gulp package-solution --ship",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "~1.4.1",
    "@microsoft/sp-application-base": "~1.4.1",
    "@microsoft/sp-core-library": "~1.4.1",
    "@microsoft/sp-dialog": "~1.4.1",
    "@microsoft/sp-lodash-subset": "~1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.1",
    "@microsoft/sp-webpart-base": "~1.4.1",
    "@pnp/common": "^1.0.4-4",
    "@pnp/logging": "^1.0.4-4",
    "@pnp/odata": "^1.0.4-4",
    "@pnp/sp": "^1.0.4-4",
    "@pnp/spfx-controls-react": "1.4.0",
    "@pnp/spfx-property-controls": "1.7.0",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "@microsoft/sp-listview-extensibility": "~1.4.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

**tsconfig.json**

{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection"
    ]
  }
}



![image](https://user-images.githubusercontent.com/32353229/44566795-1d622a00-a78d-11e8-9415-6e7ebe3dfd26.png)

**Comment by Shamrh** [comment]
Yes I did.

**Comment by waldekmastykarz** [comment]
If you create a new project and move your code there, can you reproduce the error?

**Comment by joelfmrodrigues** [comment]
Just to provide some feedback as I got this error yesterday and resolved it using the same steps as suggested on this thread.
@Shamrh  did you try the steps above to update your dependencies and re-install the entire node_modules folder?

**Comment by waldekmastykarz** [comment]
What also helps is to run `npm dedupe` which prevents you from having to remove the `node_modules` folder and the lock file.

**Comment by andrewconnell** [comment]
Added labels to prompt for follow up, or to close stale issue.
