### ISSUE TITLE
Blog for more information

### ISSUE THREAD

**Issue by paulewert** [SharePoint/sp-dev-docs#2409]
As the documentation here is quite lacking, I submit that you check out Martin Hatch's two-part blog series explaining the problem with large numbers of unique permissions and how to use this method (SPRoleAssignmentCollection.AddToCurrentScopeOnly) to resolve the issue: https://www.martinhatch.com/2011/10/scaling-to-10000-unique-permissions.html.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d1696d-8154-6c37-0094-abfe4682dac5
* Version Independent ID: 5869e4da-1fea-54c2-7209-a1e7f09008e0
* Content: [SPRoleAssignmentCollection.AddToCurrentScopeOnly(SPRoleAssignment) Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.sproleassignmentcollection.addtocurrentscopeonly?view=sharepoint-server#Microsoft_SharePoint_SPRoleAssignmentCollection_AddToCurrentScopeOnly_Microsoft_SharePoint_SPRoleAssignment_)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRoleAssignmentCollection.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRoleAssignmentCollection.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by thechriskent** [comment]
I will close this issue for now since this more of a comment than an active issue, thanks!
