### ISSUE TITLE
setState has problem

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#2411]
Hi
   I got this:

Error - typescript - src/webparts/annualLeaveForm/components/AnnualLeaveForm.tsx(242,22): error TS2345: Argument of type '{ leaveType: any; }' is not assignable to parameter of type '{ leaveType: any; vacationRequest: any; }'.

export default class AnnualLeaveForm extends React.Component<IAnnualLeaveFormProps, { leaveType: any, vacationRequest: any }> {

this.setState({ vacationRequest: value[item] });

**If i have two variables in state, i can't set only one? i am using node v8.11.4.**

thanks
Peter

**Comment by Seiyasu** [comment]
Has nothing to do with the Node version, we think you need to use the setState as official docus

**Comment by peterremote1980** [comment]
in windows, compile is ok, but in mac fail. I solved it by adding ? after variable name. Now it can be compile in both windows and mac. thanks
