### ISSUE TITLE
UserProfile.BatchUpdate.API is not working anymore 

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#2414]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

I am using the UserProfile.BatchUpdate.API for like 2 years without any problem. I have accidentally noticed that the API is not working anymore. It is not important, if i trigger the sync job with one user or multiple in the JSON file or if i try to sync multiple attributes or one attribute, i am just getting an internal error like this one:

Job ID: 07bb3ef9-60a2-46d0-a467-396b9428abf5
Job State: Error
Error State: InternalError
Logged errors: Failed to import the custom properties due to an unexpected error.

**Comment by diver7** [comment]
I can't get it to work either. I get an "InvalidDataFile" error every time. It also does not create the log file in the SP doc library so I can't even see if there is a more specific error.

**Comment by jslhcl** [comment]
Hi, @canturan , @diver7 

Do you mind sharing the json file you are using to bulk import the user properties so we can have a check whether there is anything wrong with this input file?

Thanks
Lei

**Comment by canturan** [comment]
> Hi, @canturan , @diver7
> 
> Do you mind sharing the json file you are using to bulk import the user properties so we can have a check whether there is anything wrong with this input file?
> 
> Thanks
> Lei

You can find a copy of the JSON here: 
[JSON_Sync - Copy.txt](https://github.com/SharePoint/sp-dev-docs/files/3034532/JSON_Sync.-.Copy.txt)

**Comment by jslhcl** [comment]
Thanks, canturan. the format of the json file looks good. we will investigate whether the import fails due to some other reason.

**Comment by jslhcl** [comment]
Hi, @canturan 

Have you ever changed the JSON file name before or after you uploaded this file to the document library of  SPO?

**Comment by canturan** [comment]
I am always uploading the JSON as a .txt file to the document library as JSON_Sync.txt.
