### ISSUE TITLE
SharePoint Framework for newbeginners

### ISSUE THREAD

**Issue by Nagarajan1605** [SharePoint/sp-dev-docs#2417]
Hi,

Can anyone tell is SharePoint framework suits for beginners. And person who has experience in CSOM doesnt have knowledge in html, jquery can this be good for them to learn. 

Will it be easy to learn and work. 

Kindly assist me. nagarajan.x.elumalai@gmail.com

**Comment by bcameron1231** [comment]
The framework is a bit different than what you may be used to in the past. SPFx utilizes a new modern toolchain (gulp, webpack, typescript, etc...). It may not be easy to pick up at first, but there are a lot of great resources out there. I would suggest checking out Voitanos if you want to learn some SPFx. 

In terms of "Can this be good for them to learn" - I will say, everyone will want to learn it. SharePoint Framework is the new development platform for SharePoint and it's not going away any time soon :) So anyone who works with SharePoint, will need to learn it.

**Comment by TheMiao** [comment]
I'd recommend you read MSFT documents at beginning. (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)
SPFx is bit complex. You need have O365 environment in order to do some tests.

**Comment by VesaJuvonen** [comment]
Closing as "answered". Thanks for the input.
