### ISSUE TITLE
Communication Sites Readability Issue at Full width

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#2419]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Improve readability on communication sites for pages with text content.

#### Observed Behavior

When Communication site is in full width breakpoint text on the page renders with a font-weight of 300, when the breakpoints change when making page smaller the font-weight changes to 400.

At 300 this makes the text on a page harder to ready with the default font and is not as clear.

I know this may seem super minor but its bugging me!

#### Steps to Reproduce

- Create a communication site
- Create a page with text content

- Reduce the width of the browser until it hits the next breakpoint, the text becomes easier to read.

This is strongly noticeable on a screen with 1920x1080 with a scaling of 100%. Browser: Chrome.
Sorry cannot submit screenshots to organisation security restrictions.

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi @pkbullock - as this is not really a dev issue, we can't route this internally to the right people. It should be reported using the SPO admin support tooling to get routed as non-dev issue. Closing this from here due this.
