### ISSUE TITLE
sp-dev-docs landing page doesn't mention drop 4 and 5

### ISSUE THREAD

**Issue by hbgeorgian** [SharePoint/sp-dev-docs#242]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

Visiting https://github.com/SharePoint/sp-dev-docs should list Drop 4 and 5 along with Drop 1-3.
#### Observed Behavior

Developer Preview Releases shows drop 1, 2, and 3 only
#### Steps to Reproduce

Go to https://github.com/SharePoint/sp-dev-docs and look at Developer Preview Releases section

Keep up the good work!

**Comment by chakkaradeep** [comment]
Thanks! I have a PR #250 to address this.
