### ISSUE TITLE
Type icon is cropped in the Site Contents header

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2420]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The icon is displayed correctly

#### Observed Behavior

see the screenshot:
<img width="230" alt="screen shot 2018-08-24 at 2 01 35 pm" src="https://user-images.githubusercontent.com/17036219/44607874-a20d7200-a7a6-11e8-9877-5c297b04f80c.png">

#### Steps to Reproduce

Open Site Contents

**Comment by Seiyasu** [comment]
I have not been able to reproduce the issue in my machines, so please try to provide more information(your Browser version, OS configure and so on) so we can repro and fix it.

**Comment by AJIXuMuK** [comment]
Hmm, it looks like it works fine now...
