### ISSUE TITLE
Parameter descriptions are wrong!

### ISSUE THREAD

**Issue by ikarstein** [SharePoint/sp-dev-docs#2422]
Parameter descriptions are wrong!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495b1f66-58de-0018-b964-49193fb47f58
* Version Independent ID: f7f2fbd7-df84-2013-b47b-af010135a51b
* Content: [TaxonomyInternalService.GetMatches(String, Int32, String, String, Guid, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean) Method (Microsoft.SharePoint.Taxonomy.WebServices)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.webservices.taxonomyinternalservice.getmatches?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Taxonomy.WebServices/TaxonomyInternalService.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Taxonomy.WebServices/TaxonomyInternalService.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by thechriskent** [comment]
This is an internal method that is not intended to be used from your code. However, if you have additional details about how the parameters are incorrect please provide those here. Thanks!
