### ISSUE TITLE
SharePoint Framework Environment Setup having issues with installing the trust-dev-cert

### ISSUE THREAD

**Issue by linsera1809** [SharePoint/sp-dev-docs#2423]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.

In the SharePoint documentation ("Set up your SharePoint Framework development environment" at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment), I was unable to download the developers certificate following the given steps. 

#### Observed Behavior

After running the 'gulp trust-dev-cert' command, I received the error:
'gulp' is not recognized as an internal or external command,
operable program or batch file.

Was there a command that's needed to add gulp or yo to the path? If so, what is it?

#### Steps to Reproduce

Run the steps listed on the site.
- installed npm lts using the msi installer
- npm install -g yo gulp
- npm install -g @microsoft/generator-sharepoint
- gulp trust-dev-cert

Versions:
+ gulp@3.9.1
+ yo@2.0.5

C:\Users\linser1\SPO-Webpart-Tut>node -v
v8.11.4

C:\Users\linser1\SPO-Webpart-Tut>npm -v
5.6.0

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Notice that `gulp trust-dev-cert` can be exected in a solution folder, so you will first need to scaffold a solution and then be in a folder to execute it. Not optimal, but a one-time thing for an individual computer.
