### ISSUE TITLE
Unable to debug exceptions in production due to lack of information

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#2424]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After logging an exception in production, be able to debug it using the logged error information.

#### Observed Behavior

Because production builds are optimized, the information about exceptions you can get logged is something like:

```text
TypeError: Cannot read property 'getData' of undefined
    at e._loadData (https://localhost:4321/dist/log-exception-web-part.js:1:11564)
    at e.loadData (https://localhost:4321/dist/log-exception-web-part.js:1:11498)
    at HTMLAnchorElement.<anonymous> (https://localhost:4321/dist/log-exception-web-part.js:1:13237)
```

With a minified bundle, this is hardly useful. If it was possible to include source maps in production builds, we could log more accurate stack traces like:

```text
Error: Cannot read property 'getData' of undefined
    at constructor (webpack:///src/webparts/logException/MeetingsService.ts:10:24)
    at constructor (webpack:///src/webparts/logException/MeetingsService.ts:6:16)
    at loadData (webpack:///src/webparts/logException/LogExceptionWebPart.ts:64:21)
```

The latter gives us the exact location of where the error occurred.

Currently there are the following blockers, preventing us from deploying source maps to production:

- by default no source maps are generated for production builds. We can solve this by adjusting the settings of the uglify webpack plugin
- generated source maps are explicitly excluded from the packaging process. There is no easy workaround for this because the configuration isn't exposed outside of the package task, other than after the package was generated, break it open and include the missing pieces

Ideally, we'd have a switch that we can toggle to control if we want to include source maps in the production build or not. Being able to troubleshoot issues in production is a must-have for every enterprise organization, who already owns the code of the solution and is not concerned about securing its IP from others.

**Comment by tsekityam** [comment]
Did you try following [Debug SharePoint Framework web parts on modern SharePoint pages](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages#debug-sharepoint-framework-web-parts-on-modern-sharepoint-pages) to debug your code in production environment?

We can load the web part from localhost instead of the one in the server. The web part in localhost comes with source maps, such that we can debug it with VS code.

**Comment by waldekmastykarz** [comment]
It's not about debugging the web part in production myself. It's about logging errors that occur on end-user computers using the code base that is in production.

**Comment by VesaJuvonen** [comment]
We are looking into addressing this in future builds. Thanks for your input @waldekmastykarz.

**Comment by patmill** [comment]
Since this is not an active issue, but a request for change, closing this down.  Thanks Waldek.
