### ISSUE TITLE
SPFX + ANGULARJS Package-Solution --ship breaks application

### ISSUE THREAD

**Issue by danielcostaext** [SharePoint/sp-dev-docs#2426]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a custom web part with a angularjs controller. If I'm testing doing a simple gulp serve --nobrowser, it will work just fine. 

When I bundle and package the solution for deploy, after adding the web part on the page, it breaks:

My app module:
const enrApp: angular.IModule = angular.module('enrApp', ['ui.bootstrap', 'toastr']);

enrApp.controller({ 'AddPositionToFavoriteCtrl': AddPositionToFavoriteCtrl, 'DocUploaderCtrl': DocUploaderCtrl })
    .service({
        'positionService': PositionDataService, 'documentService': DocumentDataService,
        'dealService': DealDataService, 'managedMetadataService': ManagedMetadataService
    })
    .directive({ 'onDropDirective': OnDropDirective.Factory() })
    .directive({ 'mmsAutoComplete': MngMetadataAutoCompleteDirective.Factory() });

My web part:
private $injector: angular.auto.IInjectorService;

  public render(): void {
    if (this.renderedOnce === false) {
      require('./../../app/app.module');
      this.domElement.innerHTML = DocUploaderCtrlTemplate.templateHtml;

      this.$injector = angular.bootstrap(this.domElement, ['enrApp']);
    }
}

Can anyone give me a help here?
@sprider & @waldekmastykarz  , can you help me? I saw that you guys discussed about a similar problem

#### Observed Behavior

Error: [$injector:unpr] Unknown provider: eProvider <- e <- DocUploaderCtrl
http://errors.angularjs.org/1.6.6/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20DocUploaderCtrl
    at drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:14313
    at drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15609
    at Object.r [as get] (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15543)
    at drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15613
    at r (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15543)
    at o (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15557)
    at Object.a [as invoke] (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:15571)
    at p.instance (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:17133)
    at f (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:16413)
    at a (drag-drop-upload-web-part_93e46a9bace072b33323cf7889c8cc7a.js:formatted:16219)

**Comment by waldekmastykarz** [comment]
Did you fix it @danielcostaext?

**Comment by danielcostaext** [comment]
Hi @waldekmastykarz , I found a solution (not sure if it is the best one):

-Bootstraping angular on strict DI mode;
-moved the injections to the module declaration;

Now it is working. I probably might have had some misspelling, I'll try to revert back to see if it works.

Anyway, thanks for the reply!

**Comment by waldekmastykarz** [comment]
In ship mode SPFx uglifies variable names, so without strict DI your controller injections might have been mangled preventing AngularJS from bootstrapping them correctly.
