### ISSUE TITLE
AppForSharePointWebToolkit vs AppForSharePointOnlineWebToolkit

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#2427]
Step#2 of "Build the WebJob using Visual Studio" is to download NuGet package "AppForSharePointWebToolkit". If we are working with SharePoint online then don't we have to use "AppForSharePointOnlineWebToolkit". Or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98dd366d-739b-923d-fc61-4e2c6d02e428
* Version Independent ID: d1013707-fc8e-cf75-be68-91a5f9bb8263
* Content: [Get started with Azure WebJobs (timer jobs) for Office 365 sites](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/getting-started-with-building-azure-webjobs-for-your-office365-sites#build-the-webjob-using-visual-studio)
* Content Source: [docs/solution-guidance/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ravick4u** [comment]
And when I tried to add "AppForSharePointWebToolkit" got below error message,

Failed to add reference. The package 'AppForSharePointWebToolkit' tried to add a framework reference to 'Microsoft.SharePoint.Client, Version=15.0.0.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by yuanzheng** [comment]
I was able to solve this by installing the SharePoint Client Components SDK from the following site: https://www.microsoft.com/en-us/download/confirmation.aspx?id=35585

**Comment by andrewconnell** [comment]
Yes, for this article, it should be using **AppForSharePointOnlineToolkit** as it's specifying Office 365. Doc needs to be updated...

- AppForSharePointWebToolkit = SharePoint Server 2013
- AppForSharePointOnlineToolkit = SharePoint Online
