### ISSUE TITLE
MSGraphClient randomly prompting user with alert popup

### ISSUE THREAD

**Issue by maps05** [SharePoint/sp-dev-docs#2428]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Make Graph requests using the MSGraphClient with seamless experience for end-users.

#### Observed Behavior

Users are getting from time to time a popup saying that "Additional credentials are required to show this page correctly." in their normal navigation. No credentials asked, just a OK or Cancel button. I see that the user navigation is correctly collecting data but then suddenly on a random page navigation the popup shows. The user clicks OK and everything works as expected again.

#### Steps to Reproduce

I've developed the extension in a Microsoft free demo tenant, tested it with users with different roles and didn't had this issue. I'm now having the issue in my company tenant where I've deployed the extension

Relevant details of my implementation:

- Tenant in targeted release for everyone
- Application extension with SPFx version 1.4.1
- Invoking the following graph endpoint: "/me?$select=companyName,country,department,jobTitle"
- Not using the "webApiPermissionRequests" property since I'm consuming just properties of the signed user. It is my understanding from the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests) that the token will have the user_impersonation permission, which is enough.
- Saw it happening with users in Chrome and Safari at least

Any idea of what may be the cause is appreciated.

**Comment by VesaJuvonen** [comment]
We have made significant updates with the 1.6 release of SharePoint Framework when this capability also was released for general availability. If you are still seeing this issue with the latest version, please open a new item. Thx.
