### ISSUE TITLE
Spfx WebPart with list on same page redirect to wrong Url on clicking sorting list button   

### ISSUE THREAD

**Issue by Masood10** [SharePoint/sp-dev-docs#2430]
- [X] Question
- [X] Bug

I have a Spfx webpart Which works fine in all conditions. Recently I put this webpart on a project site page.
The page has a webpart and a list with different views. 
Whenever I click on the list elements to sort it the page automatically redirects to the wrong URL
For example 
If I have the following URL
https://test.com/sites/demoe/Hybrid%20template%20test%202/Lists/Product%20Backlog/test.aspx

on Sorting the list by clicking the element(default) it adds the following Url at the end of my existing url
#/InplviewHashxxxx=CascDelWarnMessage=1-SortField=DueDate-SortDir=Asc-WebPartID={xxxx}#InplviewHashxxxx=CascDelWarnMessage=1-WebPartID={xxxx}

then after a split second, it redirects me to error 404 page not found with the URL

https://test.com#/InplviewHashxxxx=CascDelWarnMessage=1-SortField=DueDate-SortDir=Asc-WebPartID={xxxx}#InplviewHashxxxx=CascDelWarnMessage=1-WebPartID={xxxx} 

I noticed that "sites/demoe/Hybrid%20template%20test%202/Lists/Product%20Backlog/test.aspx" is removed from the Url automatically. In debugging I noticed that the function which makes the URL after # is being called twice and on the 2nd call the URL is removed.
  
FIX
Ironically if I disable the Minimal Download Strategy from the Site Settings. Everything works fine. So I feel there is a bug here in SharePoint.

Any solution how can I make it work with keeping the Minimal Download Strategy enabled?

@VesaJuvonen

**Comment by srideshpande** [comment]
@Masood10 - Thanks for raising the issue. I just checked with a list web part and a regular web part on the same page, and tried to sort the elements on the list web part. I did not notice any issue there.
Can you please re-check now and let us know?

I'm closing the issue, as it is been inactive for a very long time and cannot repro in-house. Please feel free to open a new issue, if you still see the issue.
