### ISSUE TITLE
Content updated needed since ACS is now retired

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#2431]
Since ACS is now retired, could you update this article on how to achieve the same goal today, or mention if this is not affected by ACS retirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58462e32-ad55-2351-ee7d-67c047fa4157
* Version Independent ID: 0cba1f85-d95c-6b4e-583d-608a6743e15f
* Content: [Use an Office 365 SharePoint site to authorize provider-hosted add-ins on an on-premises SharePoint site](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on)
* Content Source: [docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There's no impact to SharePoint with the retirement of ACS:
https://developer.microsoft.com/office/blogs/impact-of-azure-access-control-deprecation-for-sharepoint-add-ins

I'll update this doc to include a note about this [like we did in another doc](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins).
