### ISSUE TITLE
Deleted hub sites still visible in the Hub picker list

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-docs#2437]
For our testing purposes, we have created multiple hub sites. We have created couple other modern team and communication sites as well which are now associated with these hub sites.

As part of the cleanup process, we deleted these sites. However, we noticed that the deleted hub sites are still visible in Hub picker list. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

![Deleted hub sites - still in the picker list](https://i.stack.imgur.com/c66e8.png)

#### Expected or Desired Behavior

Once the hub site is deleted, they should not be available for association. They should not be visible in the hub picker list.

#### Observed Behavior

Currently, deleted hub sites are visible in the picker. 
When we try to associate a newly created site to the deleted hub site, we get `File not found` error . 
The error should be more meaningful, something along the line of , `Hub site has been deleted, you cant associate this site to the deleted site`

#### Steps to Reproduce

1) Create a comm site
2) Set it as Hub site 
3) Create another comm site or modern team site
4) Associate it to the hub site
5) Delete all these sites
6) Create a new comm site or modern team site
7) Try to associate it to a hub. The deleted hub site is available in the hub picker list

Current work around is to manually run a PS command as below:

`Unregister-SPOHubSite <SiteId>`

or

`Unregister-SPOHubSite <SiteUrl>`

**Comment by VesaJuvonen** [comment]
As this is not really developer issue, rather happening apparently constantly in the pages with IE, we cannot, unfortunately, process this through this channel. Please report this from the Office 365 Admin support channels as we can only concentrate on pure developer topics. Sorry for the inconvenience and slow response time, but closing this for now as we can't handle this. Please do report these in Tenant admin process. Thx.
