### ISSUE TITLE
Updating Site Information Panel from page other than homepage doesnt work 

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-docs#2438]
Updating the site information  via Site information Panel of a modern site , both team (backed by O365 group) and communication sites,  only works from the home page of that site.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Updating site information should work regardless of where you are in the site.

#### Observed Behavior

Currently, while trying to update the site information we are only able to update it from the home page.
In communication site - 
While trying to update it from the Site contents page, ( `/_layouts/viewlsts.aspx` ), it clears out the data. We can only insert data from the home page or the settings page (`/_layouts/settings.aspx`) page
 
In modern team site (backed by O365 group) -
The data doesn't get cleared, but when we try to save it we get a generic error as below:

![not able to save data](https://i.stack.imgur.com/P9HMU.png)

#### Steps to Reproduce

Try to update the site properties in the Site Information panel from a page other than homepage or settings page in Modern team (backed by O365 group) and communication sites.

**Comment by VesaJuvonen** [comment]
As this is not really developer issue, rather happening apparently with any tenant using oob capabilities, we cannot, unfortunately, process this through this channel. Please report this from the Office 365 Admin support channels as we can only concentrate on pure developer topics. Sorry for the inconvenience and slow response time, but closing this for now as we can't handle this. Please do report these in Tenant admin process. Thx.
