### ISSUE TITLE
Where can I find the description of all the available properties of @currentField when that holds a person? 

### ISSUE THREAD

**Issue by SantiagoIglesiasLucas** [SharePoint/sp-dev-docs#2445]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,
I am building a list [of actions] in Share Point Online. One of the fields is the "Owner" of the action, which is a person. I managed to add conditional format/actions based on the name and email thanks to the @currentField.title or @currentField.email properties. 

Is there something like a 'department' property? In general, what other properties are there that could be used? Is there available documentation for this?

Thanks in advance, 
Santiago.

**Comment by thechriskent** [comment]
This is documented here: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference under the **People fields** section.

They are:
- `@currentField.id`
- `@currentField.title`
- `@currentField.email`
- `@currentField.sip`
- `@currentField.picture`

> Keep in mind that `@currentField.title` generally returns the name, but if the Show As property has been adjusted for the field it might return something else. For instance, setting to Department will return the person's department in the title field

**Comment by SantiagoIglesiasLucas** [comment]
Thanks. Since 'Department' is not in the list of People fields, how can I find the department that a given person works in? I assume the information can be extracted from the following URL: _catalogs/users/detail.aspx

So, if I have the 'Name', how can I retrieve the 'Department' using JSON to format the column depending on the value of the Department?
