### ISSUE TITLE
Adding List Views withe SiteScript not possible

### ISSUE THREAD

**Issue by corily18** [SharePoint/sp-dev-docs#2446]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I tried to add a new list view to a site script
i have used following code snippet:
`{
    "verb": "addSPView",
    "name": "Erfassung nach Name",
    "viewFields": 
    [
        "Gebucht von", 
        "Beginn",
        "Ende",
        "Tätigkeitsbeschreibung"
    ],
    "query": "<Where><Eq><FieldRef Name='Gebucht von' /><Value Type='Integer'><UserID Type='Integer'/></Value></Eq></Where>",
    "rowLimit": 100,
    "isPaged": true,
    "makeDefault": false
}`

Expected: Code snippet with list view can be added to a site script and added to the tenant by the SharePoint Online Management Shell.

Info: When i remove the snippet, the site script is added to my tenant

#### Observed Behavior
Following PowerShell error was reported:
`Add-SPOSiteScript : Unable to handle action addSPView. No action handler was registered for this action.`

#### Steps to Reproduce
1. Create new site script
2. Add site script: 
`Get-Content 'FILE_URL.json'-Raw | Add-SPOSiteScript -Title "Demo Collaboration Site"`
3. Script is added and ID is generated

**Comment by Seiyasu** [comment]
Reproduced and researching on it
