### ISSUE TITLE
Is there a way to format a column  based on the value of another column?

### ISSUE THREAD

**Issue by SantiagoIglesiasLucas** [SharePoint/sp-dev-docs#2447]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,
I am building a list [of actions] in Share Point Online. 

Is there a way to format a column (let's assume it is called "Action Item" ) based on the value of another column (let's assume is called "Owner")? For example, is there a way to format in bold characters the content of the "Action Item" column is the value of the "Owner" is @me? (or another string).

Thanks in advance,
Santiago.

**Comment by thechriskent** [comment]
Yes! This is covered in the documentation here: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference under the **"[$FieldName]"** section.

There are also several samples of doing this:
- Example of using the `@me`: [Highlight the current user](https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/person-currentuser-format)
- Example of formatting based on another column: [Date Range Format](https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/date-range-format)

**Comment by SantiagoIglesiasLucas** [comment]
Fantastic. Many thanks.
