### ISSUE TITLE
spfx webpart does not work on ie11 

### ISSUE THREAD

**Issue by NishaJose** [SharePoint/sp-dev-docs#2450]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Works correctly in Chrome, firefox and edge. I am using Windows and ie11. I have tried this with different machines.
Even basic helloworld webpart does not show up on IE.

If you are opening workbench, it shows. But after deploying the solution it does not show up on the page in ie.

On IE it shows below error 
Sorry, something went wrong 
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details. 
Technical Details 

Error details: TypeError: Object doesn't support property or method 'requestAnimationFrame' 

Troubleshoot issues with Microsoft SharePoint Foundation. 

Correlation ID: 82068a9e-005d-6000-4d9d-561130b56fbd 

Date and Time: 8/30/2018 9:26:15 PM

**Comment by Alex-Ji** [comment]
I think the method 'requestAnimationFrame' is from a JS or component. You must refer it through by following ways. The first one is bundle the JS or component code to your code. the second way is refering it from CDN. it is difficut to debug this problem using IE Browser, because any js error will stop code running, chrome will be helpful to debug it.

**Comment by NishaJose** [comment]
Thanks Alex for the reply.

There is no error showing up in chrome or other browsers.

I have tried using CDN and without referring CDN. Also tried bundling the JS but nothing worked.

Even a simple helloworld webpart without any JS does not show up on ie.

I am using ie 11.

**Comment by mag210** [comment]
@NishaJose  I have the same problem with a webpart I've built using spfx 1.6. An older webpart (using 1.3) does not have this issues. The webpart works fine on all other browsers I have tested (chrome, FF, Edge) but on IE 11 it will not fetch data (pnp call). Also when you try and edit the web part in the property pane, you find that many of the options just do not work.

**Comment by russgove** [comment]
Hi, I upgraded  a webpart from 1.4. to 1.6. Works fine in chrome, but in IE 11 it wont even load in the workbench. Is anyone working on this, or should I revert to 1.4?

**Comment by mag210** [comment]
You need to use Pollyfills for the web part to work in IE11. This is down to the newer pnp libraries which use JS functions not supported by IE11. If you add the below imports to your main .ts file it should correct the issue on IE. 
//Polyfills to fix IE11 compatibility issues

import "core-js/es6/array";

import "es6-map/implement";

import "core-js/modules/es6.array.find";

**Comment by ErnstWolthaus** [comment]
Workbench won't load in IE11. In developertools, it shows an error on handleFailure (object does not exist).
Importing the mentioned polyfills won't work because those are specifically for pnpjs. 
Newly generated SPFx without added code is just broken for IE11.

**Comment by zakbelmaachi** [comment]
A customer of mine was having this exact issue when loading their SPFx webpart in IE11. 

When looking at the MDN browser compatibility table for 'window.requestAnimationFrame', it shows full support for IE10+. 

**My customer was running IE11 with the document mode set to 8. This was their issue.** You can check your document mode in the IE dev tools under the emulation tab. Additionally, you can type 'window.requestAnimationFrame' in the console to see if the Function is returned. If it's not returned, that's an indicator that your DocMode is below 10.

Going further, these IE settings are generally set at an organization level to provide backwards compatibility for legacy web tech. Leveraging the Enterprise Mode Site List in IE11 will let IE know that it always needs to render pages in Document Mode 11 for SharePoint, if configured correctly.

**Comment by amolkhedekar01** [comment]
> You need to use Pollyfills for the web part to work in IE11. This is down to the newer pnp libraries which use JS functions not supported by IE11. If you add the below imports to your main .ts file it should correct the issue on IE.
> //Polyfills to fix IE11 compatibility issues
> 
> import "core-js/es6/array";
> 
> import "es6-map/implement";
> 
> import "core-js/modules/es6.array.find";

This is worked for me. Thank you

**Comment by jduboi** [comment]
> > You need to use Pollyfills for the web part to work in IE11. This is down to the newer pnp libraries which use JS functions not supported by IE11. If you add the below imports to your main .ts file it should correct the issue on IE.
> > //Polyfills to fix IE11 compatibility issues
> > import "core-js/es6/array";
> > import "es6-map/implement";
> > import "core-js/modules/es6.array.find";
> 
> This is worked for me. Thank you

Where is the .ts file?

**Comment by holylander** [comment]
> 
> 
> > > You need to use Pollyfills for the web part to work in IE11. This is down to the newer pnp libraries which use JS functions not supported by IE11. If you add the below imports to your main .ts file it should correct the issue on IE.
> > > //Polyfills to fix IE11 compatibility issues
> > > import "core-js/es6/array";
> > > import "es6-map/implement";
> > > import "core-js/modules/es6.array.find";
> > 
> > 
> > This is worked for me. Thank you
> 
> Where is the .ts file?

You can just add that to the main webpart .ts file.
On the other hand, I had the same issue. You can just following the [official polyfill described ](https://pnp.github.io/pnpjs/documentation/polyfill/)here. It should work and fix the >IE11 compatibility issue.

**Comment by andrewconnell** [comment]
First, please refer to the recently published browsers supported doc for IE11 here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

After reviewing, if you are still having an issue, seems it's an issue with how IE11 implements the RAF function. There are lots of posts about this not specific to SPO/SPFx, and as mentioned in this thread, a polyfill may be needed.
