### ISSUE TITLE
AAD errors due to conditional policy in on-behalf flow aren't detected by aadClient

### ISSUE THREAD

**Issue by ekapic** [SharePoint/sp-dev-docs#2453]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm using the preview aadClient capability in SPFx 1.5.1-plusbeta. I have a custom AAD-secured web API that calls Graph API using on-behalf flow. 

The AAD has conditional access for Office 365 applications so that only the authorized devices or multifactor authentication can access the company resources. The device is authorized. Our backend application is excluded from the policy. 

#### Observed Behavior
The SPFx webpart sucessfully connects to AAD-secured web API. The web application that hosts the API gets an exception when trying to exchange that token. For some users it fires the "device not in compliant state" AAD error and for some users it fires the "multi-factor auth required due to location or policy change".  It raises an error in the backend. 

If we follow the AAD developer policy that says to return a 403 with claims parameter, nothing happens. It looks like that the aadClient only honors that error if it's returned by the AAD on the initial token issue.

**Comment by Seiyasu** [comment]
We will contact with the PG and sync up to you while have any update.

**Comment by VesaJuvonen** [comment]
Hi @ekapic  - any change you could update to 1.6 as that's the GA version to check if the things are the same still. Technically this feels like an aad issue as we use native adal.js under the covers with no special things...but would test things first with 1.6 to ensure that you are using GA version.

**Comment by VesaJuvonen** [comment]
Closing due to no response.
