### ISSUE TITLE
SPFx web part On Premise (SharePoint 2016) - App for the Web part shows in Site Contents. if user clicks icon. Error 'Sorry, something went wrong'

### ISSUE THREAD

**Issue by JCol79** [SharePoint/sp-dev-docs#2454]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

On-Premise (SharePoint 2016 FP2): After installing the SPFx app in Site Collection, clicking on the App icon in the Site Contents page should not error but either be disabled or provide property in the SPFx project's package-solution.json to set the desired launchUrl.  

Comparing to a SharePoint App development, you are able to control that within the App Project or by registering the app using /_layouts/15/appregnew.aspx.

#### Observed Behavior

On-Premise: After installing the SPFx app in Site Collection, clicking on the App icon in the Site Contents page throws error: 'Sorry, something went wrong'

#### Steps to Reproduce

1. Deploy you production ready SPFx app to App Catalog (assuming your CDN is already properly configured)
2. Navigate to a Site Collection's Site Contents page, click Add an App, and select your SPFx App
3. Once App is deployed, click on its icon (the Tile).

Thanks in advance for your response and guidance. I'm very much looking foward to leveraging SPFx on our Large Enterprise SharePoint Farms to meet and exceed our customers needs.

**Comment by bcameron1231** [comment]
Could you provide some information?

- SharePoint 2016 FP2?

- What version of SPFx are you using?

-

**Comment by JCol79** [comment]
Yes - SharePoint @016 FP2
@microsoft/generator-sharepoint": { "isCreatingSolution": true, "environment": "onprem", "version": "1.5.1",.. (Not 100% how to tell SPFx Version) 
I just installed the yo template 5 days ago. Selecting the On-prem option.

The solution deploys and works. its just that I am concerned with the above behavior as I can see users installing the app, clicking on the icon, and then complaining / submitting support tickets.

**Comment by VesaJuvonen** [comment]
Sure - this can cause confusion for the end user, but it's actually technically by designs... or in the SPO this link for the SPFx solution is removed as a pretty recent fix. It's hygiene issue no doubt, but if that's something which truly needs to get fixed also in SP2016 platform, we would recommend opening a Premier support case, if needed. Right now we can't really process this request from this process.
