### ISSUE TITLE
Switch it back

### ISSUE THREAD

**Issue by eyebelieve** [SharePoint/sp-dev-docs#2455]
Can you please list the PowerShell command to reverse this (add back the feature/opt in)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
We will contact this with PG and sync up to you while have any update.

**Comment by andrewconnell** [comment]
It would just be the inverse of **Enable-PnPFeature**: [Disable-PnPFeature](https://docs.microsoft.com/powershell/module/sharepoint-pnp/disable-pnpfeature?view=sharepoint-ps)
