### ISSUE TITLE
Is this available for SP 2016 Server?

### ISSUE THREAD

**Issue by samculver** [SharePoint/sp-dev-docs#2456]
On prem also or just O365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c136778d-54ad-5155-3ce7-ed40f9a1ba2b
* Version Independent ID: 65021293-571f-fac6-d5f1-6190e27b1331
* Content: [Tenant-scoped solution deployment for SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-scoped-deployment)
* Content Source: [docs/spfx/tenant-scoped-deployment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tenant-scoped-deployment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
We don't have tenant definition for on premise, so the document is for O365 currently.

**Comment by VesaJuvonen** [comment]
Tenant scope deployment is in SharePoint Online and in SharePoint 2019, but not in SharePoint 2016.
