### ISSUE TITLE
Beta Get Preview Link Permission Documentation Issue

### ISSUE THREAD

**Issue by lenyt** [SharePoint/sp-dev-docs#2457]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Fix documentation. On the documentation for Get preview link:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driveitem_preview

It says in Permission:

Delegated (work or school account) Files.Read, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All
Delegated (personal Microsoft account) Files.Read, Files.ReadWrite, Files.ReadWrite.All
Application n/a

#### Observed Behavior

I was able to make this call with only Application permission Files.ReadWrite.All and get a successful result.

Either the documentation is not correct or if the documentation is correct then this call should have failed since I only had Application permission and didn't have any Delegated permissions when I made the call.

#### Steps to Reproduce

1) For an application that has Application permission Files.ReadWrite.All, get an access token with client credential flow using shared secret.
2) use the token to call preview url:
POST /drives/xxxx/items/yyyy/preview
3) preview url is returned even though in the documentation it says for Application: n/a

LT

**Comment by Seiyasu** [comment]
This is a Microsoft Graph related issue, please asked it at https://stackoverflow.com/questions/tagged/microsoft-graph.

**Comment by lenyt** [comment]
I did report it at stackoverflow first:
https://stackoverflow.com/questions/52106257/beta-embeddable-file-previews-questions

And I believe that it was actually you that told me to report it in github.

LT

**Comment by lenyt** [comment]
@Seiyasu Please see my previous post. Can you re-open this or do I need to file a new issue?

LT
