### ISSUE TITLE
Restore/opt back into site theming after removing/opting out

### ISSUE THREAD

**Issue by eyebelieve** [SharePoint/sp-dev-docs#2459]
I used the below which removed/opted the site out of the new theming experience by disabling the feature and I need to restore it/opt back in. How can I do that?

To opt out of the site, you need to enable a feature:

Enter “Get-PnPFeature -Scope Site -Identity 5138468E-3D76-4F72-9DE4-E029F1245A7B”
Verify that nothing is returned from the previous command (this confirms the feature isn’t enabled yet)
Enter “Enable-PnPFeature -Scope Site -Identity 5138468E-3D76-4F72-9DE4-E029F1245A7B”
Enter “Get-PnPFeature -Scope Site -Identity 5138468E-3D76-4F72-9DE4-E029F1245A7B”
Verify that the following is returned:

ClientSideThemingOptOut - 5138468e-3d76-4f72-9de4-e029f1245a7b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff514d24-111a-d79e-396f-feb65a1fb7d7
* Version Independent ID: 20540d08-e747-3395-29df-e266919bfc36
* Content: [SharePoint site theming - PowerShell cmdlets](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-powershell)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Do you have try "Disable-PnPFeature  -Scope Site -Identity 5138468E-3D76-4F72-9DE4-E029F1245A7B", it should be work for you.
