### ISSUE TITLE
launch.json URL does not work for Local Workbench debug configuration

### ISSUE THREAD

**Issue by TedPattison** [SharePoint/sp-dev-docs#2460]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

I found what seems like a bug when running gulp serve with the --nobrowser switch and then launching the Local Workbench debug configuration which is defined in a new project inside launch.json. When I click the green arrow button to launch the Local workbench debu configuration, the browser appears with a blank page. If I update the URL in the Local workbench debug configuration of launch.json to the initialPage value I found in serve.json, then launching a debug session works correctly.

"name": "Local workbench",
"url": "https://localhost:5432/workbench",

It seems like hitting that initial page at https://localhost:5432/workbench is essential to hit first to make the local workbench work. But when you run gulp serve with the --nobrowser switch and then try to launch the Local Workbench it fails.

**Comment by VesaJuvonen** [comment]
thx @TedPattison for reporting... now just to prioritize things... this seems to be a training topic on saying, please don't add --nobrowser on the call, unless mistaking something. Sure that will then open a new tab, but that's it. Am I missing something.

**Comment by TedPattison** [comment]
It also seems like there is one more issue. When you start project with the gulp serve command without using the --nobrowser parameter, it starts up fine and runs inside the local workbench. But after that then when you try to debug by setting breakpoint and pressing the green arrow on the debug tab to begin a local debug session, the Visual Studio Code IDE is not able to break at a breakpoint.  This is not a big issue but not as smooth to single step through code as it was with API v1.4.

**Comment by TedPattison** [comment]
In a new projected created with 1.6, I can fix the problem by updating launch.json by switching the url of the Local workbench configuration from...

"url": "https://localhost:4321/temp/workbench.html",

to 

"url": "https://localhost:5432/workbench/",
