### ISSUE TITLE
May Updates on Provisoning Schema for Site Designs & Scripts

### ISSUE THREAD

**Issue by Mayramth** [SharePoint/sp-dev-docs#2461]
The PnP Provisioning Schema has been updated in May with Site designs and Scripts so I would suggest that this could be mentioned somewhere in the Site Designs doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm not clear on what you're suggesting... could you elaborate. 

If you have a suggestion to enhance this page, please feel free to submit a pull request by clicking the **edit** link in the top right of the page to start to the process.
