### ISSUE TITLE
AzureCdn webpart has connection type issue => certificate problem??

### ISSUE THREAD

**Issue by DevelopMR** [SharePoint/sp-dev-docs#2462]
[SPLoaderError.loadComponentError]:

***Failed to load component "573a6871-ec95-4df6-9a6d-ff04a72b27fa" (AzureCdnWebPart).

Original error: ***Failed to load URL 'https://darkmatter.azureedge.net/azurehosted-webpart/azurehosted-webpart-azurecdnwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'AzureCdnWebPartStrings' in component '573a6871-ec95-4df6-9a6d-ff04a72b27fa' (AzureCdnWebPart). There was a network problem.

This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:

***Failed to load URL 'https://darkmatter.azureedge.net/azurehosted-webpart/azurehosted-webpart-azurecdnwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'AzureCdnWebPartStrings' in component '573a6871-ec95-4df6-9a6d-ff04a72b27fa' (AzureCdnWebPart). There was a network problem.

This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***CALLSTACK:

Error
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.005/sp-pages-assembly_en-us_17e63878d420c1c6f86f59035e36bcf6.js:729:15844)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.005/sp-pages-assembly_en-us_17e63878d420c1c6f86f59035e36bcf6.js:1589:21631)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.005/sp-pages-assembly_en-us_17e63878d420c1c6f86f59035e36bcf6.js:1589:15588)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.005/sp-pages-assembly_en-us_17e63878d420c1c6f86f59035e36bcf6.js:1589:11613)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.005/sp-pages-assembly_en-us_17e63878d420c1c6f86f59035e36bcf6.js:1589:69915)

--------------------

I know the assets have been deployed to Azure, because I tested the URL:
 https://darkmattr.blob.core.windows.net/azurehosted-webpart/573a6871-ec95-4df6-9a6d-ff04a72b27fa.json

and a JSON file was there.

There was the "The build failed because a task wrote output to stderr." on gulp bundle --ship, but I have read comments that this isn't necessarily a show stopper.

New to this kind of development, any help would be welcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e46a7b-157b-0974-fced-df23d1536bb4
* Version Independent ID: 14b1a252-149f-356c-b19b-ffd312615c1c
* Content: [Deploy your SharePoint client-side web part to Azure CDN](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn)
* Content Source: [docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
We are working on setting the test environment, will sync up to you while we have any update

**Comment by magnusdanielson** [comment]
We have the same issue. It works fine with Chrome and Edge, but breaks in IE11.

**Comment by magnusdanielson** [comment]
I just noted that i actually works in on customer tenant but not in another for IE.

I checked the versions on the tenants and they differ.
Working tenant: vti_extenderversion:SR|16.0.0.8203
Broken tenant: vti_extenderversion:SR|16.0.0.8126

We are using azure websites as our CDN.

![image](https://user-images.githubusercontent.com/12081481/46795443-76d8e500-cd4a-11e8-81cf-4a3dd4ac2d63.png)

**Comment by andrewconnell** [comment]
@DevelopMR - Are you still having a problem? I'm working to follow up on old issues. 

If so, can you provide some additional context like SPFx version, SharePoint envrionment, etc?
