### ISSUE TITLE
Modern pages: page content not shown on iPad

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#2463]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We are noticing issues where iPad (iOS 10) is not rendering the page content on modern OOTB communication sites.

The following page is how it looks like on a desktop browser:

![screenshot 2018-09-04 11 08 48](https://user-images.githubusercontent.com/2900833/45021946-3ee7cf00-b033-11e8-9c96-28e1c1f9fc86.png)

When opening the page on an iPad, the page content is gone and the social bar is positioned at the top:

![img_0232](https://user-images.githubusercontent.com/2900833/45021985-5757e980-b033-11e8-9cf2-9c5ebcda8b45.PNG)

#### Steps to Reproduce

- Create a new communication site
- Create a new page
- Add some content
- Publish the page
- Open the page on an iPad

**Comment by Seiyasu** [comment]
Do you have tried several times? I cannot reproduce it on my side.

**Comment by TheMiao** [comment]
Hi @estruyf , could  you pls provide more information about reproduce steps:

iPad version:
iOS version:
Browser type & version:

Many thanks,
Chris

**Comment by estruyf** [comment]
@Seiyasu two different iPads and tested on different SP tenants. 

iPad version: iPad Pro and iPad gen. 4
iOS version: iPad Pro (10.3.3) - iPad gen. 4 (10.3.3)
Browser type & version: mobile Safari (the one that comes with iOS) and Chrome (latest)

Updated my personal iPad to iOS 11 which solves the issue. The other one is still on 10.3.3 and issue is still present.

**Comment by VesaJuvonen** [comment]
Unfortunately, as this is not a developer issue, we cannot use this process/route to report this to the right feature crew. Please open the issue from the Tenant admin support pages to route it using correct channels. Sorry for the inconvenience.
