### ISSUE TITLE
Cannot update to React ^16.0.0

### ISSUE THREAD

**Issue by amarmechai** [SharePoint/sp-dev-docs#2464]
Cannot update to React ^16.0.0
Steps to Reproduce
Create a new SPFx project
Update React by changing versions in package.json to ^16.0.0 and running npm update
Execute the SPFx project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f89fed-848e-50b9-6be4-657824ad262e
* Version Independent ID: 3d3c5227-7281-ef49-a2d1-686c0a049497
* Content: [Use Office UI Fabric React components in your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components)
* Content Source: [docs/spfx/web-parts/get-started/use-fabric-react-components.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/use-fabric-react-components.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
We cannot just upgrade the React but to upgrade all modules at the same time. Best to keep all default module version. All module version must be synchronized.
