### ISSUE TITLE
Referenced known bug - details?

### ISSUE THREAD

**Issue by darrenparkinson** [SharePoint/sp-dev-docs#2465]
There is a known bug referenced on this page.  Are there any further details for this bug?  Perhaps a bug id / link we could follow?  This page was last updated 14 March so I'm wondering if there has been any progress on this bug since then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6b53f5b-4768-4c84-9aa0-d42bbb104c99
* Version Independent ID: 753fbae2-135f-f254-0183-6debf2bd7376
* Content: [Overview of SharePoint Framework (SPFx) Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions)
* Content Source: [docs/spfx/extensions/overview-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/overview-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Hi darrenparkinson,
Sorry for the late update. We are checking with production team for more detail information about this list and library extension bug in classic experiences. According to Docs, it seems has been fixed. But there is not detail info to prove that. We will keep you updated as soon as we hear back from PT. Sorry for inconvenience.

**Comment by darrenparkinson** [comment]
Thanks.  Any update so far?  I can confirm that it is not working in my environment, so if it's fixed, I'm not seeing it.  Thanks again.

**Comment by VesaJuvonen** [comment]
Documentation issue, which has been now fixed by removing it note.
