### ISSUE TITLE
Is there a way to truncate the string that is displayed via "txtContent": "@currentField"?

### ISSUE THREAD

**Issue by SantiagoIglesiasLucas** [SharePoint/sp-dev-docs#2467]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,
Is there a way to truncate the string that is displayed via "txtContent": "@currentField"?
In concrete terms, I need to display whatever is found in @currentField without the last 5 characters. The column in question holds a single line of text. 

Many thanks, 
Santiago. 

Thanks for your contribution! Sharing is caring.

**Comment by Seiyasu** [comment]
1. Make a new column which is the copy of the @currentField, and apply column-formatting to it.
2. Use the SPFx field Customizers.

**Comment by SantiagoIglesiasLucas** [comment]
Thanks. 
Since (and I've probably should've said this before) my dev skills are very, very basic, I am only capable -so far- to learn from examples. Is there some sample code available anywhere that could be easily adaptable to my needs? Ideally some JSON code like in https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples that is adapted to my basic skills and that I was able to copy and modify for my site.

**Comment by Seiyasu** [comment]
You can learn the basic TypeScript use 5 mins.
Then, you can follow the document to implement the Field customizer: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

Finnally, replace the text binding with:
${(event.fieldValue.substr(0,event.fieldValue.length-5))}
