### ISSUE TITLE
Is there a way to populate a column of a given list with information present in another list?

### ISSUE THREAD

**Issue by SantiagoIglesiasLucas** [SharePoint/sp-dev-docs#2468]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,
I've built a list in SPO to hold information concerning action items. One of the columns is the 'Owner' of the action item (a user). Another column is the 'Department' that the 'Owner' belongs to.  The 'Department' column allows us to easily group and filter items. 

I'd like to avoid having to type the Department that a given Owner belongs to, since this information is already in SPO; concretely, it is in  _catalogs/users/detail.aspx  (where for each Owner=Name, I can fetch his/her Department name).
 
Therefore, I'd like to automate (either when a new item is input or modified, or when the list is displayed) the population of the 'Department' column based on the value of the 'Owner' column based on _catalogs/users/detail.aspx

Is there a way to achieve this level of automation?

Many thanks,
Santiago.

**Comment by Seiyasu** [comment]
Some Implementation ideas: inject some JavaScript code to the page. In the JavaScript code, monitor the Owner column in the Popup, and then set the corresponding Department by calling _catalogs/users/detail.aspx.

**Comment by SantiagoIglesiasLucas** [comment]
Thanks. 
Since (and I've probably should've said this before) my dev skills are very, very basic, I am only capable -so far- to learn from examples. Is there some sample code available anywhere that could be easily adaptable to my needs? Ideally some JSON code like in https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples that is adapted to my basic skills and that I was able to copy and modify for my site.

**Comment by Seiyasu** [comment]
You can learn the basic [TypeScript](http://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) use 5 mins.
Then, you can follow the document to implement the Field customizer: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

Finnally, replace the text binding with:
 ${(event.fieldValue.substr(0,event.fieldValue.length-5))}
