### ISSUE TITLE
SPFx The user or administrator has not consented to use the application with ID '<guid>' named 'SharePoint Online Client Extensibility Web Application Principal'

### ISSUE THREAD

**Issue by pbjorklund** [SharePoint/sp-dev-docs#2473]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
AadHttpClient should work according to previous (1.5 plus version)

#### Observed Behavior

Deployed and trusted webApiPermissions requested by app onto a production environment with no targeted release.

Ran o365$ ```spo serviceprincipal set -e true```

SharePoint Online Client Extensibility Web Application Principal exists in https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps with matching <guid> from above. Redeployed solutions and re-trusted API.

Recieve console message below from SPFx solution

```
Uncaught (in promise) Error: AADSTS65001: The user or administrator has not consented to use the application with ID '1565f76c-d88e-4586-9d23-9ef27af612c3' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
Trace ID: 0b113a29-86da-4039-96c6-01880a440100
Correlation ID: 8fac6554-c3a2-40d4-9cfd-ba99f5a89408
Timestamp: 2018-09-06 08:06:29Z
    at Array.<anonymous> (sp-pages-assembly_en-us_2fd01d9d9722e6b700aca2046e1c70ae.js:988)
    at _callBackMappedToRenewStates.(anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-27.007/1.sp-http-adal_58855c41adb591deebd1.js:3:7561)
    at AuthenticationContext.handleWindowCallback (VM96 adal.min.js:2)
    at parseTokenFromUrl (spfxsinglesignon.aspx:20)
    at onload (VM160 spfxsinglesignon.aspx:31)
```

Response from: /_forms/spfxsinglesignon.aspx#error=interaction_required&error_description=AADSTS65001%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID

**Comment by pbjorklund** [comment]
Giving the app the delegated permission "Sign in and read user profile" in AAD seems to have resolved this.

**Comment by pbjorklund** [comment]
The APIs trusted from https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement ends up correctly in the "SharePoint Online Client Extensibility Web Application Principal" in AAD under Permissions as it should.

I guess that the "SharePoint Online Client Extensibility Web Application Principal" is supposed to handle SPFx signins and therefor needs permissions to Sign in users from AAD granted globally and that this one lacks the grant that was previously globally deployed from Microsoft. Perhaps it was cleared when 1.6 was deployed and the grants were cleared?

Can't debug since I don't have global admin (but have Application Admin and Cloud Application Admin) roles.

**Comment by eoverfield** [comment]
I believe this is the expected output based on the update to spfx 1.6. All granted permissions to AAD in SPO had to be re-granted per 1.6 release notes: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes

**Comment by eoverfield** [comment]
@Nasicus It looks as though there are found issues and I am sure Microsoft will solve this. @VesaJuvonen provided more guidance here: https://github.com/SharePoint/sp-dev-docs/issues/2472#issuecomment-419208756. Once this has been fixed, I am sure we will get instructions if anything needs to be done.

**Comment by Nasicus** [comment]
@eoverfield  I know they did I saw it. I just think these 2 are not directly related.
I migrated quite a few tenants today.
My approach was always the same (see my post above). This worked for almost all tenants, expect where I had this exception (which they are indeed investigating right now). But having to give permission to the  SPFx principal app seems like another issue to me, that's why I wanted to show it to them :)

**Comment by patmill** [comment]
I think this is the answer you are looking for.  With the move to GA, the new service principal that we create has 0 permissions.  You will need to explicitly ask for the permissions you need.  We did this so that over time, if the 1st party permissions change (say we add something, then remove it), you're code will continue to work as expected.

Does that answer your question?

**Comment by vman** [comment]
This worked for me by adding the required permissions in the `package-solution.json` and then re-uploading the solution to the App Catalog and then granting the permissions again from the API Management page:

```JSON
"webApiPermissionRequests": [
      {
        "resource": "User Details Custom API for SPFx",
        "scope": "user_impersonation"
      },
      {
        "resource": "Windows Azure Active Directory",
        "scope": "User.Read"
      }
    ]
```

(I am calling a custom Azure Function on behalf of the current user)

**Comment by qz2017** [comment]
For now, you have to add User.Read to enable sign-in. By default, there is no permission granted for you. 

https://msdn.microsoft.com/Library/Azure/Ad/Graph/howto/azure-ad-graph-api-permission-scopes#PermissionScopeDetails

**Comment by Nasicus** [comment]
@patmill 

If we really have to ALWAYS add the permission
```
      {
        "resource": "Windows Azure Active Directory",
        "scope": "User.Read"
      }
```
to the `webApiPermissionRequests`, then this really has to be added to the documentation:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient

**Comment by vman** [comment]
Can I suggest to go forward a step and add the permission to the `package-solution.json` through the SPFx generator itself? If it is going to be needed in all cases, makes sense to have it in the default scaffolding.

**Comment by eoverfield** [comment]
@vman for my tenants that did not have any issues with the migration to 1.6, that included aad calls, I did not have to manually add user.read to the new service principal. I am trying to get us clarification if the requirement a few of us are having with the new service principal is actually a bug.

**Comment by patmill** [comment]
Let me check around and I will follow up on this thread.

**Comment by Nasicus** [comment]
@eoverfield didn't you say (https://github.com/SharePoint/sp-dev-docs/issues/2472#issuecomment-419228769) that you followed my steps to make it work?
Because then you did the same thing,but instead of via the manifest you did it via the App directly (which  I think is probably the "wrong" way).

**Comment by baywet** [comment]
@Nasicus 's solution worked for us, thanks!

**Comment by eoverfield** [comment]
@Nasicus I did use your process on two of my tenants and that did fix final issues I ran into. On a few other tenants, I never ran into issues with the recent updates, and I didn't have to follow your steps, the legacy solutions that utilized AAD continued to work. Very interesting.

**Comment by s-KaiNet** [comment]
I have below error in my SharePoint admin center, under API mng page:  
![image](https://user-images.githubusercontent.com/10658276/45258096-6683c200-b3ba-11e8-92d8-5444539e03a4.png)

Does it mean, that I haven't received new functionality yet?

**Comment by s-KaiNet** [comment]
Solution by @Nasicus worked for me as well. It also was a combination of two issues - a user is not an admin, and "Windows Azure Active Directory" permission problem

**Comment by Nasicus** [comment]
@patmill

This post shows the exact message I had, and why I even figured out to requiere this additional permission: https://github.com/SharePoint/sp-dev-docs/issues/2480#issuecomment-419827762

**Comment by s-KaiNet** [comment]
@olemp  If you go to azure portal -> azure active directory -> enterprise applications -> switch drop down to Application Type - All -> search for "SharePoint Online Client Extensibility Web Application Principal" -> select it -> permissions -> does permission list contain `Group.ReadWrite.All` permission, which should be admin consented?

**Comment by olemp** [comment]
@s-KaiNet My bad. An old access token was cached. Clearing localStorage and sessionStorage solved it for me (not sure which of them the client uses).

**Comment by DnsSrinath** [comment]
Any idea why "SharePoint Online Client Extensibility web application" not available in my tenant?

![image](https://user-images.githubusercontent.com/30183504/45451904-7812e580-b6aa-11e8-857f-15f47abe2a6b.png)

Is there a way to re-create it?

![image](https://user-images.githubusercontent.com/30183504/45451951-9bd62b80-b6aa-11e8-8999-a90791b32ede.png)

I am not able to remove the existing permissions in the API management I am getting "UnKnow Error."

Even from the Powershell command to disable the "SharePoint Online Client Extensibility" I get same "UnKnow Error"

**Comment by VesaJuvonen** [comment]
Original issue has been fixed and you need to re-approve your permissions. This is either related on the #2472 or related on the missing approvals of the permissions.

@DnsSrinath - your issue seems same as #2522, if that's not the case, please open a new issue and provide needed details. Thx.

**Comment by mwiedemeyer** [comment]
I just want to add, that I had the same issues and the solution was quiet simple:
The "resource" in webApiPermissionRequests element allows only names, not IDs.
In our tenant we had 2 different apps in "Enterprise Apps" with the same name and the API Permissions in the new SharePoint Admin Center added the wrong app to the permissions.
Solution: Delete the "wrong" app and re-approve the API permissions.
