### ISSUE TITLE
SPFx 1.6 MSGraphClient consent doesn't work

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2475]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

After updating web part to SPFx 1.6 iI can't make Graph requests.
`Error: AADSTS90008: The user or administrator has not consented to use the application with ID '9e5e7121-9347-4301-9f9b-b353f92b80ff'. This happened because application is misconfigured: it must require access to Windows Azure Active Directory by specifying at least 'Sign in and read user profile' permission. 
`

Although I did published new WebPart and approved permissions and I see new Azure AD Application
![image](https://user-images.githubusercontent.com/22150933/45148243-84d99a00-b1cf-11e8-95e5-2dd78b9514c8.png)
and permission is there
![image](https://user-images.githubusercontent.com/22150933/45148305-a89ce000-b1cf-11e8-8d58-9bed010e43aa.png)

**Comment by patmill** [comment]
Please see https://github.com/SharePoint/sp-dev-docs/issues/2472 .  This is probably a duplicate.  If not, feel free to reopen.

Note that in the move from Beta -> GA, we create a new AAD app that you need to reapprove your permissions on.

**Comment by 2toLeadMike** [comment]
I've had the same issue. See #2473, #2472 is something else it appears.
