### ISSUE TITLE
Unable to install gulp

### ISSUE THREAD

**Issue by AmolM27** [SharePoint/sp-dev-docs#2477]
#### Category
- [ x] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Expect yo command to work after: npm i -g yo gulp 

This is on Windows 7 Enterprise (Build 7601:SP1). Can someone tell me if Windows 7 is supported for SPFx development? Is this the below error normal?

#### Observed Behavior

When running: npm i -g yo gulp on Windows 7 Enterprise (Build 7601:SP1). 

I get error:
"
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
x yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

√ npm version

Found potential issues on your machine :(
+ yo@2.0.5
updated 1 package in 9.391s"

Tried to do npm install -g yo@latest as suggested but get same error.

**Comment by Seiyasu** [comment]
This is not the SPFx but the NPM/NodeJs issue.  [](https://github.com/yeoman/yo/issues/591)
