### ISSUE TITLE
Localization using Site Scripts and Designs

### ISSUE THREAD

**Issue by RajputDeepak** [SharePoint/sp-dev-docs#2478]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We work for a client which has presence in more than one country.Hence localization is must for us.
We know that localization can be achieved using PnPProvisioningTemplate by referencing resource files in <pnp:Localizations> attribute.

We dont see any option in Site Scripts and Site Designs to achieve localization of Site Columns and List Instance etc.This stops us to use the UI option to create multilingual site.

is there any way where we can reference reource files in site script>

**Comment by Seiyasu** [comment]
We are working on this and will sync up to you the update
