### ISSUE TITLE
ApplicationCustomizer bug on case-sensitive file systems

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2481]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Affected Version of @microsoft/sharepoint:  1.6.0

#### Expected or Desired Behavior
Make filenames matching to the references in ```package-solution.json``` or the other way round.

#### Observed Behavior
For an ApplicationCustomizer some files will be provisioned to the folder ```sharepoint/assets/```. For example the `ClientSideInstance.xml` and the `elements.xml`.
On filename is Camel-case the other is just lowercase. This per se is not a problem when the file system is case-insensitive and wouldn't be a problem if the reference in the `package-solution.json` file would match the file name on the disk.

In my case, the filesystem is case-sensitive that causes the following error on `gulp package-solution`.

![screen shot 2018-09-06 at 14 47 07](https://user-images.githubusercontent.com/5503835/45158701-10a9f100-b1e5-11e8-8594-ba4411776782.png)

The content of ```package-solution.json```:
<img width="516" alt="package-solution" src="https://user-images.githubusercontent.com/5503835/45158788-5bc40400-b1e5-11e8-8535-8c57244f0a58.png">

On the file system:
<img width="435" alt="screen shot 2018-09-06 at 14 59 05" src="https://user-images.githubusercontent.com/5503835/45158862-9037c000-b1e5-11e8-91a3-23aa8f32bd86.png">

#### Steps to Reproduce
Create Application customizer and package it on a case-sensitive file system

**Comment by Laul0** [comment]
Same problem here during the `package-solution` stage !
The build works locally but not on my CI 😕 (fix temporary the issue by renaming the `ClientSideInstance.xml` with no uppercases) :

<img width="547" alt="screenshot 2019-02-08 at 09 19 51" src="https://user-images.githubusercontent.com/15279205/52466578-0e2c3880-2b83-11e9-8c27-4b222af07f51.png">

**Comment by kemesfun** [comment]
@StfBauer I am not able to reproduce this issue, I am using yeoman generator v1.10. Can you verify whether or not this issue still occurs?

**Comment by Laul0** [comment]
Hi @kemesfun it is not linked to the version of your generator... It is linked with your operating system if it is case sensitive.
On Windows and MAC OS you will don't have the issue, because this OS are not case sensitive... But if you use a Linux (Ubuntu, Debian, etc.), this kind of OS are case sensitive so when the build is launched, it try to find `ClientSideInstance.xml` while it is `clientsideinstance.xml`.

I met this issue recently on one of mine CI (1.9.1 or 1.10 I not remember).

**Comment by StfBauer** [comment]
@kemesfun You can verify issues like this on Windows too. It is not only limited to MacOS and Linux.

The easiest way is to use on Windows WSL(Windows SubSystem for Linux) or [enable case-sensitivity](https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10#enable_case_sensitivity_ntfs_windows10).

Docker container run in this issue too.

1.10.0 seems to have this fixed. I ran a sample project and it worked.
