### ISSUE TITLE
Delve People Suggestions Api in custom implementation 

### ISSUE THREAD

**Issue by jashwanthreddyn** [SharePoint/sp-dev-docs#2482]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
Hello - We are working on a requirement to add a people search with typeahead functionality on our sharepoint intranet home page (similar to people/document lookup on delve home page, but just people) 

I see delve is using below end points for people suggestions: 
https://nam.delve.office.com/mt/v3/search/peoplesuggestions?queryText=&personType=Person
https://nam.delve.office.com/mt/v3/search/people?queryText=jim&top=5

Can you please provide documentation on these end points ? Also, can we use these end points for our custom people lookup implementation.  
 
Thank you !

**Comment by KingKangMSFT** [comment]
Hi @jashwanthreddyn 

The users in the delve are actually are users in the tenant. 
You can use graph API to retrieve all users. 
https://graph.microsoft.com/v1.0/users/

If you want to check specific user's skill
https://graph.microsoft.com/v1.0/users/{user_id}/skills

Here is the Microsoft graph API docs you can read, and all properties are list in the doc.
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/user

**Comment by VesaJuvonen** [comment]
You can mimic the implementation by using the Graph REST APIs, which is where the information is available. All information in the Graph APIs is automatically security trimmed.
