### ISSUE TITLE
Experimental feature that is not supported in the current environment.

### ISSUE THREAD

**Issue by SteveClements** [SharePoint/sp-dev-docs#2486]
As well as not being able to access the API Management page listed in other issues. #2485.  In the console I am getting this error ...

Error: The requested operation is part of an experimental feature that is not supported in the current environment.

Reading https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad it states that AadHttpClient is in general release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by eoverfield** [comment]
Once https://github.com/SharePoint/sp-dev-docs/issues/2472 is addressed, I believe this issue will be resolved as well.
