### ISSUE TITLE
SharePoint notification stops working when adding NotificationHandlerAssembly and NotificationHandlerClassName .

### ISSUE THREAD

**Issue by kaykamel** [SharePoint/sp-dev-docs#2488]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After adding the following tags inside the alerttemplates.xml file the notification event should be accessed by the new class provided.

#### Observed Behavior

It suddently stops sending notification alerts

#### Steps to Reproduce

create a class inhertis from IAlertNotifyHandler
deploy it to the gac
add < NotificationHandlerAssembly >
    Handler assembly strong name
  </ NotificationHandlerAssembly >
  < NotificationHandlerClassName >
    Fully qualified class name
  </ NotificationHandlerClassName > 
 to the alerttemplates.xml under 16/template/xml folder

**Comment by VesaJuvonen** [comment]
Hi @kaykamel, can you provide more details on the SharePoint server which you used for testing this so that we can build a repro. Thanks.

**Comment by kaykamel** [comment]
I applied the IAlertNotifier similiar which was done to 2010 and 2013 however in 2016 it stopped working. After a i changed my approach i moticed that there was another application server which had the timer job running on it. This might be the issue, frankly I am not sure

**Comment by VesaJuvonen** [comment]
Thanks @kaykamel - so the issue is in the SharePoint 2016 side, which helps to narrow down work on our side.
