### ISSUE TITLE
SharePoint Workbench stopped working as it is not loading client side web part but local workbench is working

### ISSUE THREAD

**Issue by rahulsuryawanshi** [SharePoint/sp-dev-docs#249]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Observed Behavior

The SharePoint workbench was working earlier. Now its not working though local workbench is working as expected. 

Below is message I see in the chrome developer console.

Unable to resolve config for module: https://localhost:4321/temp/manifests.js

**Comment by visualcrystal** [comment]
I am also experiencing the same error when I upload the workbench file and try to load it and edit it.
![load error](https://cloud.githubusercontent.com/assets/5444463/19521671/045c4e72-9647-11e6-933f-9d192b55b239.png)

**Comment by patmill** [comment]
Three quick questions
1 - Can you try running the `gulp trust-dev-cert` task?
2 - Can you double check that gulp serve is running on your dev box
3 - Can you paste your config/serve.json file?

**Comment by rahulsuryawanshi** [comment]
Thanks

1.  I don't see there is gulp task with name 'trust-dev-cert' in the gulp file generated by yoman template for SharePoint.

**gulpfile.js**

'use strict';

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');

build.initialize(gulp);

2.  Yes "gulp serve" is running on dev box when confirming that the SharePoint Workbench is not loading the web part.

3.  **config/serve.json** file content

{
  "port": 4321,
  "initialPage": "https://localhost:5432/workbench",
  "https": true,
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}

**Comment by patmill** [comment]
Are you on drop 5?

**Comment by rahulsuryawanshi** [comment]
Hi Pat,
I am sorry about my little knowledge on this but I am not sure how do I check which drop I am using?

**Comment by patmill** [comment]
The drop notes are here - https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-5

One easy check is to see your package.json file and see what version you see on
    "@microsoft/sp-client-preview": "~0.5.0",

One other thing that might help, if you are familiar with the developer tools in your browser, can you open up the dev tools and see what network calls are being made to your local machine?

**Comment by rahulsuryawanshi** [comment]
Hi Pat,
I followed release note as you provided and now that I can see my web part in SharePoint workbench. Also because of running the gulp trust-dev-cert which installed the certificate, I don't see the certificate security error either in IE or Chrome.

Thank you very much.

**Comment by patmill** [comment]
OK, cool.  We've got some work planned both in the build tools and the workbench to make this easier to self-diagnose and fix in the future.

**Comment by rahulsuryawanshi** [comment]
Great. Looking forward to those enhancements.

**Comment by patmill** [comment]
Closing...
