### ISSUE TITLE
New admin center API management webapipermissionrequest Error

### ISSUE THREAD

**Issue by VinodhNarayanan** [SharePoint/sp-dev-docs#2491]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

After uploading my sharepoint frame package to my app catalog. then trying to view the API approval
in the tenant admin center it shows like below 

![image](https://user-images.githubusercontent.com/38123307/45212962-c4fb5400-b285-11e8-9ec8-385049178bab.png)

User is a Global administrator.

Thanks for your contribution! Sharing is caring.

**Comment by vman** [comment]
Hi @VinodhNarayanan, this is a known issue and the workaround for now is posted here: https://github.com/SharePoint/sp-dev-docs/issues/2472#issuecomment-419213781
