### ISSUE TITLE
Issues with leveraging Logging API with SharePoint Framework extensions version 1.5.2

### ISSUE THREAD

**Issue by mohababu009** [SharePoint/sp-dev-docs#2492]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [  ] Bug
- [ ] Additional article idea

With Sharepoint Framework 1.4.1 the logging api seems to be working as expected but after upgrading to 1.5.2 it stopped working and I tried different ways but couldn't make it work. Could you please provide the instructions on how to leverage Logging API with SharePoint Framework extensions 1.5.2

#### Steps to Reproduce
=>Imported the Log as mentioned below
import { Log } from '@microsoft/sp-core-library';

=> Here is how its been leveraged
export default class LoggerTestingCommandSet extends BaseListViewCommandSet<ILoggerTestingCommandSetProperties> {

  @override
  public onInit(): Promise<void> {
    
    Log.info(LOG_SOURCE, 'Initialized LoggerTestingCommandSet');
    return Promise.resolve();
  }

I would appreciate quick response as our project is reaching the final phase.

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
W\I don't believe we have a version 1.5.2.  However I'm not seeing any issue in 1.6.0
