### ISSUE TITLE
How to throubleshoot GetSharePointContext in CheckRedirectionStatus (SharePoint addin)

### ISSUE THREAD

**Issue by samusaran** [SharePoint/sp-dev-docs#2494]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Issue

My SharePoint Online Provider-Hosted addin keeps getting me the error page (the Error.cshtml view) because it fails to get a SharePointContext. I don't know where to look.

The addin works in development, but not in production, I've checked Client ID and Client Secrets and they match, the only issue I can see is when I'm getting redirected from the SharePoint site to the Addin:

`You are being redirected to the following url that was not registered as the app launch url`

Everyone suggest that I register the app, but I never did that, I got Client ID and User Secrets from the client and I've uploaded the `.app` package.

May the launch URL be responsible to the "missing" SharePoint context?
I know the question may be vague, but I really don't know where to look to solve an issue like that.

I just want to underline that all my MVC methods have SharePointContextFilterAttribute, the missing context happens in CheckRedirectionStatus method.

**Comment by Seiyasu** [comment]
You need to make sure the values you are entering in the "site collection url>/_layouts/15/AppRegNew.aspx"  are matching with the AppManifest.xml in your solution.

**Comment by samusaran** [comment]
Thank you. The registration had the wrong App Domain set.
