### ISSUE TITLE
ts. d.ts, js, js.map in same folder after upgrading spfx to 1.6.0

### ISSUE THREAD

**Issue by licypal** [SharePoint/sp-dev-docs#2495]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

After upgrading to SPFx 1.6.0, I see ts, d.ts, js, js.map files in the same folder which wasn't happening in previous versions. Please let me know if that is supposed to happen.

![image](https://user-images.githubusercontent.com/6519992/45330840-33f1da80-b51c-11e8-874d-0e51c200301c.png)

On running gulp build and gulp serve --nobrowser, I see a lot of changes being added because of that.

![image](https://user-images.githubusercontent.com/6519992/45330858-4704aa80-b51c-11e8-844e-5537ad6ab0a3.png)

Should I be checking in those changes into my code to complete spfx version upgrade to 1.6.0?

#### Steps to Reproduce

Followed this video and SharePoint Framework v1.6 release notes to upgrade:
https://www.youtube.com/watch?v=dWmuXjXlZV8

**Comment by licypal** [comment]
Thank you @vman. Copying tsconconfig.json to my project fixed the issue. Appreciate your help!

**Comment by licypal** [comment]
Thanks @waldekmastykarz.

I ran the command **npm i -g @pnp/office365-cli@next**
I get the following error on running **spfx project upgrade** in the folder where the project is located:

![image](https://user-images.githubusercontent.com/6519992/45371239-f5513400-b59e-11e8-991f-0ec87edf91fd.png)

Please let me know if I am missing any steps. Thanks!

**Comment by waldekmastykarz** [comment]
prepend the command with `o365`, so `o365 spfx project upgrade --output md > report.md` (the last part will create a Markdown report and save it to the report.md file in the current directory).

**Comment by licypal** [comment]
Thank you @waldekmastykarz

**Comment by licypal** [comment]
@waldekmastykarz 

After running **o365 spfx project upgrade --output md > report.md**, I followed steps from report.md and on running **npm install**, it showed following error with npm WARN : invalid config loglevel="notice":

![error](https://user-images.githubusercontent.com/6519992/45393726-1e46e880-b5e2-11e8-830c-0b8ba0a33c43.png)

After deleting npm and npm-cache folders from \AppData\Roaming and node_modules folder from the project, **npm install** ran succesfully. Could you please let me know the cause for this issue and a better way to fix this issue? Thanks!

**Comment by waldekmastykarz** [comment]
I haven't seen this error before so unfortunately can't tell what went wrong. What often helps in odd cases like the one you mentioned is to remove the node_modules folder and re-run `npm install` to restore all dependencies.

**Comment by xyz92** [comment]
@vman Could you please share the steps you followed to upgrade to SPFx 1.6.0?
