### ISSUE TITLE
Add tsconfig changes to the 1.6 release notes

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#2496]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The "Build and tooling changes in 1.6.0" section should have an additional point mentioning that the `tsconfig` file has been changed since the previous versions. 

#### Observed Behavior
The 1.6 release notes are missing the updates to the `tsconfig.json` file at the root which leads to issues like this one https://github.com/SharePoint/sp-dev-docs/issues/2495

(I looked at submitting a PR but seems GitHub does not allow forks and PRs to wikis)

#### Steps to Reproduce

Update any SPFx project from a previous version to 1.6 as per the release notes.

**Comment by patmill** [comment]
Thank @vman - I've updated the wiki page.  Let me know if it is unclear or incorrect.

Pat.
