### ISSUE TITLE
Loading JS files in <head> tag using SPFx. Similar to SiteCustomActions !

### ISSUE THREAD

**Issue by dmahendranme** [SharePoint/sp-dev-docs#2498]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question

[This](https://github.com/SharePoint/sp-dev-docs/issues/626#issuecomment-311209688) is the exact scenario we are in. @PopWarner have asked right questions but no acceptable responses :( 
Any update on this? 

We want to load our JS before the <body> tag renders. Any solution on that? Tried ApplicationCustomizer but it is not we want because it is just inserting the reference on head tag after body tag renders. 

Do you have any solution on new SPFx v1.6?

**Use Case:** Some analytics scripts wants to be rendered before the body tag. 

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
No, at this moment we do not have a way to inject pure script onto the page above the head element (assuming that is what you mean by "before the tag renders").

What analytics are you looking to do?

**Comment by dmahendranme** [comment]
@patmill I think there is an issue with GitHub. I mentioned that "before the body tag renders" but it is displaying as "before the tag renders". Sorry for the confusion. 

On the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension), it is mentioned that;

_The logic for your Application Customizer is contained in the onInit method, which is called when the client-side extension is first activated on the page. This event occurs after this.context and this.properties are assigned. As with web parts, onInit()returns a promise that you can use to perform asynchronous operations._

I assume that this code is executed after the body content is loaded (like document.ready). 
We wanted to have a solution like ScriptLink on classic SharePoint. 

The analytics we are using is Riverbed's AppInternals. One of their instruction is to have the code on head tag (i.e., we should not add it to the head tag after the dom elements are loaded). 

Here is the snapshot of the existing setup we use on classic SharePoint. It loads as part of the page load. 
![image](https://user-images.githubusercontent.com/22429151/45372354-c3e66180-b5ba-11e8-88d6-d8ce047e70dd.png)

**Comment by VesaJuvonen** [comment]
As this is a new feature request, we would ask you to vote for following - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/19536304-extensions-application-customizer-loading-js-fi.
