### ISSUE TITLE
Docs on AadTokenProvider don't say anything about webApiPermissionRequests

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#2499]
AadTokenProvider doesn't work without corresponding `webApiPermissionRequests` provided under `package-solution.json`.   
AadTokenProvider uses the same "SharePoint Online CE Web application" for token generation, that's why to make token generation work, your third-party API should be added to `webApiPermissionRequests` and approved by an administrator.   
This doc doesn't contain information about this important step, making it difficult to guess for newcomers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064cdc5a-e118-ceab-c42b-ae06ae3297c6
* Version Independent ID: 95afcc6d-fd0b-90a0-5775-4871869abc83
* Content: [Connect to API secured with Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad)
* Content Source: [docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
Good point @s-KaiNet! Care to submit a PR? 🙂

**Comment by s-KaiNet** [comment]
Will do :)    
I have some doubts about actual wording, but you guys will correct me if I'm wrong :)
