### ISSUE TITLE
Question on SharePoint Online modern pages OOTB Social bar Page view count feature

### ISSUE THREAD

**Issue by gurubn** [SharePoint/sp-dev-docs#2503]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Could you please throw some light on "Modern pages Social bar  Page view statistics".
 How does page view count works ? is it based on the search service (like using "ViewsLifeTime" managed property)? or is it based on some other technology like  Graph ?

We have custom news SPFx web part which uses Search KQL query to fetch Site pages (as News articles) and uses "ViewsLifeTime" managed property to show Page view count, but Search based Page view count is always differs from Social bar Page view count on actual modern site page (difference is more than 100 or 500 most of the time)

#### Expected or Desired Behavior

I assumed Social bar Page view count uses Search service in behind. Considering that, Page view count should be same or at least near by.

#### Observed Behavior

Search based Page view count always less or more than Social bar Page view count

Apologize if this is not the right place to raise this question. Please redirect me to right location if I am on wrong location.

**Comment by ypcode** [comment]
Hi,

I have some requirements for a custom development, and I need to fetch this count of views in my WebPart. I did some search but haven't found anything relevant so far...
Does anyone know if there is any official API to fetch this value, or at least can anyone tell where (or how) it should be fetch (maybe using the search API ?)

Best regards,
Yannick

**Comment by gurubn** [comment]
User voice entry : https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/35822527-official-documented-api-needed-to-fetch-modern-pag

**Comment by VelinGeorgiev** [comment]
This is a closed API. Probably, only Microsoft can explain how the page view counts work.
