### ISSUE TITLE
Release notes typo

### ISSUE THREAD

**Issue by SPDoctor** [SharePoint/sp-dev-docs#2504]
#### Category
- [ ] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We want developers to use MSGraphClient instead of the old GraphHttpClient. 

URL: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes

#### Observed Behavior

SharePoint Framework v1.6 release notes encourages developers to use the **MSGraphHttpClient**, which does not exist. Typo is repeated in third bullet point also.

Sharing is caring :-)

**Comment by VesaJuvonen** [comment]
Thx Bill, fixed now. soooooooooooooooooooooooo many things.
