### ISSUE TITLE
Incorrect step mentioned

### ISSUE THREAD

**Issue by dmahendranme** [SharePoint/sp-dev-docs#2506]
Generator did not ask this below question when creating extension. 

"For the next question Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites...., ensure you select No (N) , and select Enter. If you select Yes (y), the scaffolding will not generate the Elements.xml feature deployment file."

I believe this is applicable only when creating webparts. 
Correct me if I'm wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
You're wrong, but that's a good thing :)

One of the new features in 1.6.0 is tenant wide deployment of extensions (application customizers and command sets - not field customizers).

**Comment by dmahendranme** [comment]
@patmill I'm using new version and it did not ask me that question. That's where I got confused.
