### ISSUE TITLE
Not able to run app in local workbench after upgrading spfx to 1.6.0 

### ISSUE THREAD

**Issue by licypal** [SharePoint/sp-dev-docs#2507]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After upgrading to SPFx 1.6.0, app should run in both local and hosted workbenches without any issues. 

#### Observed Behavior

App runs in hosted workbench. However, I see the following error while running the app in local workbench:

![image](https://user-images.githubusercontent.com/6519992/45308529-84464980-b4d6-11e8-9e53-db7e84e316be.png)

#### Steps to Reproduce

npm i -g @microsoft/generator-sharepoint@latest
Create a new project with 1.6
Copy over the tsconfig.json from new project to existing project.
Make the 2 changes listed in the "Build and tooling changes in 1.6.0" section in the release notes:
https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes#build-and-tooling-changes-in-160
Delete node_modules folder
Run npm install
gulp serve --nobrowser

Followed this video to upgrade:
https://www.youtube.com/watch?v=dWmuXjXlZV8

Am I missing any steps which would cause the local workbench to not work? Thanks!

**Comment by licypal** [comment]
@vman Please let me know if you have suggestions to fix this issue. Thanks!

**Comment by licypal** [comment]
Based on https://github.com/SharePoint/sp-dev-docs/issues/2062, the issue is that something broke in a recent SPFx update with a dependency. When running gulp serve --nobrowser, none of the necessary packages to run the workbench are copied into the ./temp/workbench-packages. A workaround on this issue is to copy the files from the above folder when running gulp serve to a safe location, then when running gulp serve --nobrowser, copy that folder back in, replacing the empty ./temp/workbench-packages folder. Would there be a better fix for this issue soon? Thanks!

**Comment by patmill** [comment]
Looking into this.  Thanks for the heads up.

**Comment by patmill** [comment]
OK, so there was a change in how some of the code is laid down.  To get this to work properly with --nobrowser, navigate to https://localhost:5432/workbench .  It copies all of the packages, and redirects to :4321/temp/workbench.html

Looking into when this change was made, and if we need to do anything specific, or just document what steps need to be followed.

**Comment by waldekmastykarz** [comment]
@licypal are you trying to set the breakpoint in the browser or in the code editor?

**Comment by licypal** [comment]
@waldekmastykarz In the code editor.

**Comment by licypal** [comment]
@patmill Thank you!

**Comment by waldekmastykarz** [comment]
@licypal are you following the steps as described in the docs at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?
