### ISSUE TITLE
Provisioning list generates an invalid list

### ISSUE THREAD

**Issue by zolem** [SharePoint/sp-dev-docs#2509]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When provisioning a list with custom content type and fields(columns) I should be able to go to the list and it not give an error about being invalid

#### Observed Behavior
For some reason I get the below every time I visit the list. (aa748d9e-60fd-6000-c901-a303b607dbc6)
![image](https://user-images.githubusercontent.com/7129911/45321938-039e4200-b504-11e8-84a9-63f77ee6630f.png)
Clicking "Go to the list" just sends me to the same page over again.
#### Steps to Reproduce
- I have a site collection I have created with its own app catalog so I can test the provisioning of my app.
- I created an SPFX webpart and have added assets to be provisioned.
#### elements.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <Field ID="{38217009-AD2C-45CF-8530-420DB4A2B353}"
        Name="SC_RecurrenceRule"
        DisplayName="Recurrence Rule"
        Type="Text"
        Required="TRUE"
        Group="SC Columns"/>
    <ContentType ID="0x0100D27A03B46CA643D2AF679429D2B7A70E"
        Name="SCEvents_v4"
        Group="SC Content Types"
        Description="Super calendar event content type for building new lists">
        <FieldRefs>
            <FieldRef ID="{38217009-AD2C-45CF-8530-420DB4A2B353}" Required="TRUE" />
        </FieldRefs>
    </ContentType>
    <ListInstance
        CustomSchema="SuperCalendarEventsSchema.xml"
        FeatureId="00bfea71-de22-43b2-a848-c05709900100"
        Title="Super Calendar Events"
        Description="Example event list for a super calendar"
        TemplateType="100"
        Url="List/SuperCalendarEvents">
        <Data>
            <Rows>
                <Row>
                    <Field Name="Title">Sample Event</Field>
                    <Field Name="SC_RecurrenceRule">Test Recurrence Rule</Field>
                </Row>
                <Row>
                    <Field Name="Title">Sample Event 2</Field>
                    <Field Name="SC_RecurrenceRule">Test Recurrence Rule 2</Field>
                </Row>
            </Rows>
        </Data>
    </ListInstance>
</Elements>
```
#### SuperCalendarEventsSchema.xml
```xml
<List xmlns:ows="Microsoft SharePoint" Title="Super Calendar Events Schema" Name="SuperCalendarEventsSchema" Direction="$Resources:Direction;" Url="Lists/SuperCalendarEventsSchema" BaseType="0" EnableContentTypes="TRUE" FolderCreation="FALSE" VersioningEnabled="TRUE" MajorVersionLimit="100" EnableMinorVersions="FALSE" MajorWithMinorVersionsLimit="0" DisableAttachments="FALSE"
  xmlns="http://schemas.microsoft.com/sharepoint/" RootWebOnly="FALSE">
  <MetaData>
    <ContentTypes>
      <ContentType ID="0x0100D27A03B46CA643D2AF679429D2B7A70E"
        Name="SCEvents_v4"
        Group="SC Content Types"
        Description="Super calendar event content type for building new lists">
        <FieldRefs>
          <FieldRef ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Required="TRUE"/>
          <FieldRef ID="{38217009-AD2C-45CF-8530-420DB4A2B353}" Required="TRUE"/>
        </FieldRefs>
      </ContentType>
    </ContentTypes>
    <Fields/>
    <Views>
      <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/images/generic.png" Url="AllItems.aspx">
        <XslLink Default="TRUE">main.xsl</XslLink>
        <JSLink>clienttemplates.js</JSLink>
        <RowLimit Paged="TRUE">30</RowLimit>
        <Toolbar Type="Standard" />
        <ViewFields>
          <FieldRef Name="LinkTitle"/>
          <FieldRef name="SC_RecurrenceRule"/>
        </ViewFields>
        <Query>
          <OrderBy>
            <FieldRef Name="ID" />
          </OrderBy>
        </Query>
      </View>
    </Views>
    <Forms>
      <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
    </Forms>
  </MetaData>
</List>
```
- I uploaded to my app catalog and everything appears to provision fine with no errors at all. If I go to the list settings all the columns are correctly provisioned.
- Visit the actual list and notice that it just gives you an error no matter what.

**Comment by patmill** [comment]
Hi @zolem - any chance you could share the tenant?  Otherwise, if you look at a network trace, is there an error present?

**Comment by zolem** [comment]
@patmill Any ideas on this? I still can't figure out what could possibly be going wrong. I wish there was an error log or something.

**Comment by VesaJuvonen** [comment]
Hi @zolem, can you rename the schema file as schema.xml, as that might actually be the root cause. If that is not the case, can you share the correlation ID which is visible when you access the list, so that we can have a look on the root issue? Thx.

**Comment by zolem** [comment]
@VesaJuvonen I tried re-running everything after changing the the file to schema.xml but I still have the same result. The correlation id for the list is: 2f73969e-2003-6000-c902-107c7dfbe6f7
![image](https://user-images.githubusercontent.com/7129911/46627910-346c9980-caf9-11e8-8a6d-27a3954b007a.png)

Luckily all the other provisioning is working fine. My plan is for now to not provision the list at all until this is fixed. I will just have to force them to create their own list and apply that content type. Ideally I would have a list provisioned that they can use from the start but I can't do that currently.

**Comment by zolem** [comment]
Everytime I visit the list I get a new correlation id:
6f73969e-9069-6000-c925-b9d99c5925af
7273969e-105a-6000-eade-88f2543eb218

**Comment by zolem** [comment]
As an fyi, the list appears to be functional in every way except being able to be displayed on the page. I can send rest queries to it for creating and modifying list items. I just can't actually visit the list using Sharepoint's interface.

**Comment by jxnx888** [comment]
Hi @zolem , Do you have any observation you would like to share? Until now, I have tested on my end, the issue may occur on elements.xml file. I will keep testing it. Please let me know if you have any question.

**Comment by zolem** [comment]
Essentially for now we have resigned to not provisioning a list. I provision the content type and columns I need. Then I am just telling users to create their own lists with this content type. This is not ideal of course because you know how users can be.

My one big observation is that I think the list is being provisioned properly with one strange thing that forces it to throw an error when rendered in SharePoint. As I said I can still make rest api calls, and the list functions normally.

If you look at [my comment](https://github.com/SharePoint/sp-dev-docs/issues/2509#issuecomment-420332407) it show the errors that are being thrown. If you guys can figure out why those errors would be thrown from a newly provisioned list, then we will probably be good.

At the moment I am slightly afraid to change my asset files because it is so fragile that anything could send me into hours of time trying to debug something with no error messages lol.

Also because of [this issue](https://github.com/SharePoint/sp-dev-docs/issues/2750#issue-369207943) I would have to try this on a new site, since the current guid for the content type I am using is kind of broken.

This one and the deletion of content types are really my only 2 issues preventing me from having a truly seamless user experience.
