### ISSUE TITLE
Using mobx in a webpart throws an error in Workbench

### ISSUE THREAD

**Issue by kmees** [SharePoint/sp-dev-docs#251]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Using [mobx](https://github.com/mobxjs/mobx) for state management in a webpart should work.

#### Observed Behavior
An error is thrown because the Workbench uses an old version of mobx (mobservable)
<img width="847" alt="screen shot 2016-10-20 at 17 56 34" src="https://cloud.githubusercontent.com/assets/649769/19568055/56de4688-96f0-11e6-91aa-c4d59f955207.png">

#### Steps to Reproduce
https://github.com/kmees/spfx-react-mobx-webpart-starter

**Comment by manishgarg1** [comment]
We already have a version of mobx loaded on the workbench. It is an old version before it was called mobx. You can look at the node modules folder for the exact version. Can you try to use the shipped version to achieve your goal? We plan to update or remove mobx but that will happen only later.

**Comment by manishgarg1** [comment]
This implies that we do not need to fix anything on our side. Is that interpretation correct?

**Comment by kmees** [comment]
It will work with the next minor mobx release but it still might be a good idea to migrate the workbench from mobservable to mobx.

**Comment by mweststrate** [comment]
correct, maybe document the minimum required Mobx version once it is
available

Op ma 24 okt. 2016 03:04 schreef Manish Garg <notifications@github.com>:
