### ISSUE TITLE
Error -  Update SPFX Assets

### ISSUE THREAD

**Issue by mahdyahmed85** [SharePoint/sp-dev-docs#2510]
Hi,
I used SPFX to create SharePoint List, then I faced the following issue when I am trying to update the app.
I only can add fields to the list content types, I can't remove or rename any fields using SPFX feature update. I also can't remove the CT from the list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Please provide the code you use and any other dev config.

**Comment by LukasNespor** [comment]
Here is [article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package#define-upgrade-actions-for-new-version) that describes how to use upgrade actions. There is also one Tip, that says that SPFX uses almost the same update proces as Add-Ins.

And [here is list](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/update-add-in-web-components-in-sharepoint#what-can-and-cannot-be-done-declaratively) of what cannot be done declaratively. The important one is "Lists, list instances, **content types**, or fields cannot be deleted in the update markup."

**Comment by mahdyahmed85** [comment]
> Here is [article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package#define-upgrade-actions-for-new-version) that describes how to use upgrade actions. There is also one Tip, that says that SPFX uses almost the same update proces as Add-Ins.
> 
> And [here is list](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/update-add-in-web-components-in-sharepoint#what-can-and-cannot-be-done-declaratively) of what cannot be done declaratively. The important one is "Lists, list instances, **content types**, or fields cannot be deleted in the update markup."
