### ISSUE TITLE
Spfx AadHttpClient with Azure AD B2B users, error from spfxsinglesignon.aspx - AADSTS70002: Error validating credentials. AADSTS50132: Session unusable due to expired or revoked external refresh token.

### ISSUE THREAD

**Issue by colinrippeyfinarne** [SharePoint/sp-dev-docs#2514]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Any type of Azure AD B2B user can successfully call an Azure Function secured with Azure AD using the AadHttpClient.

#### Observed Behavior

A specific type of Azure AD B2B user is unable to call the Azure Function, an Azure AD B2B user who's email address is user@gmail.com is met with the following error stack when executing the function call:

Uncaught (in promise) Error: AADSTS70002: Error validating credentials. AADSTS50132: Session unusable due to expired or revoked external refresh token.
Trace ID: f24ff438-dcf0-46a4-884d-33143fbd3300
Correlation ID: 1cc00bbc-bdba-460c-a195-962238092fc9
Timestamp: 2018-09-11 10:32:59Z
    at Array.<anonymous> (sp-webpart-workbench-assembly_en-us_f8a0e7244f4ad150f9e12d48ce35aa75.js:981)
    at _callBackMappedToRenewStates.(anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-31.007/1.sp-http-adal_58855c41adb591deebd1.js:3:7561)
    at AuthenticationContext.handleWindowCallback (VM418 adal.min.js:2)
    at parseTokenFromUrl (VM419 spfxsinglesignon.aspx:20)
    at onload (VM429 spfxsinglesignon.aspx:31)

#### Steps to Reproduce

I have used the following article to create a simple webpart to test the spfx AadHttpClient:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

I have created an Azure Function and secured it using Azure AD by following the steps on this article (note only the function, I have used the spfx webpart from the docs.microsoft.com article):

https://www.vrdmn.com/2018/02/sharepoint-framework-calling-aad.html

In my webpart code I have the following:

`private _searchWithAad(): void {
    // Log the current operation
    console.log("Using _searchWithAad() method");
    this.props.context.aadHttpClientFactory
      .getClient('09fd7687-d9a4-4dcc-a883-f8cc26451f72')
      .then((client: AadHttpClient) => {
        return client
          .get(`https://sqanowdev01funcscratch.azurewebsites.net/api/GetUserDetails?name=${escape(this.state.searchFor)}`,
          AadHttpClient.configurations.v1
          );
      })
      .then(response => {
        return response.json();
      })
      .then(json => {
        console.log(json);        
      });

    this.props.context.aadHttpClientFactory
      .getClient('https://graph.microsoft.com')
      .then((client: AadHttpClient) => {
        // Search for the users with givenName, surname, or displayName equal to the searchFor value
        return client
          .get(
            `https://graph.microsoft.com/v1.0/users?$select=displayName,mail,userPrincipalName&$filter=(givenName%20eq%20'${escape(this.state.searchFor)}')%20or%20(surname%20eq%20'${escape(this.state.searchFor)}')%20or%20(displayName%20eq%20'${escape(this.state.searchFor)}')`,
            AadHttpClient.configurations.v1
          );
      })
      .then(response => {
        return response.json();
      })
      .then(json => {

        // Prepare the output array
        var users: Array<IUserItem> = new Array<IUserItem>();

        // Log the result in the console for testing purposes
        console.log(json);

        // Map the JSON response to the output array
        json.value.map((item: any) => {
          users.push( {
            displayName: item.displayName,
            mail: item.mail,
            userPrincipalName: item.userPrincipalName,
          });
        });

        // Update the component state accordingly to the result
        this.setState(
          {
            users: users,
          }
        );
      })
      .catch(error => {
        console.error(error);
      });
  }
`
My Azure Function code looks like this:

`using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Security.Claims;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");
    
    string result = "";

    var claimsList = new Dictionary<string, string>();

    //Current user claims
    foreach (Claim claim in ClaimsPrincipal.Current.Claims)
    {
        string claimType = claim.Type;
        string claimValue = claim.Value;
        result = result + "-" + "Type " + claimType + " Value " + claimValue;
        claimsList.Add(claimType, claimValue);
    }

    var claimsFound = ClaimsPrincipal.Current.Claims;
    var didWeFind = claimsFound.GetType().Name;

    return req.CreateResponse(HttpStatusCode.OK, claimsList, JsonMediaTypeFormatter.DefaultMediaType);}
`
When I test this code using the https://<tenant>.sharepoint.com/sites/<site>/_layouts/15/workbench.aspx  I see the following output in the browser console with the following users:

1. An admin user of the home tenant:
I can see the list of claims returned by the function in the console output.

2. An organisational account from another tenant who has been added as a Guest user (Azure AD B2B user)
I can see the list of claims returned by the function in the console output.

3. A user with an email address of user@outlook.com who has been added as a Guest user (Azure AD B2B user)
I can see the list of claims returned by the function in the console output.

4. A user with an email address of user@gmail.com who has been added as a Guest user (Azure AD B2B user, via their Microsoft Account user@gmail.com and NOT via google federation)
I see the following error:
Uncaught (in promise) Error: AADSTS70002: Error validating credentials. AADSTS50132: Session unusable due to expired or revoked external refresh token.
Trace ID: f24ff438-dcf0-46a4-884d-33143fbd3300
Correlation ID: 1cc00bbc-bdba-460c-a195-962238092fc9
Timestamp: 2018-09-11 10:32:59Z
    at Array.<anonymous> (sp-webpart-workbench-assembly_en-us_f8a0e7244f4ad150f9e12d48ce35aa75.js:981)
    at _callBackMappedToRenewStates.(anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-08-31.007/1.sp-http-adal_58855c41adb591deebd1.js:3:7561)
    at AuthenticationContext.handleWindowCallback (VM418 adal.min.js:2)
    at parseTokenFromUrl (VM419 spfxsinglesignon.aspx:20)
    at onload (VM429 spfxsinglesignon.aspx:31)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
As this falls directly under the Azure Active Directory auth topics, we in the SharePoint engineering cannot, unfortunately, solve this and would request to add an entry to AAD StackOverflow which is their location for reported issues. This is clearly not due SPFx, it's around auth structure - https://stackoverflow.com/questions/tagged/azure-active-directory.
