### ISSUE TITLE
Dynamic Data: Not working on classic page

### ISSUE THREAD

**Issue by nhadro** [SharePoint/sp-dev-docs#2515]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The below code should work fine on classic pages as well as modern
this.context.dynamicDataSourceManager.initializeSource(this);

#### Observed Behavior

When we add a webpart to a classic page that is a IDynamicDataController, the spinner stays there and a console error is thrown that says:
Uncaught Error: Source id contains invalid characters, like "_". Id: "WebPart.00000000-b799-43d5-8529-63f7caf2bd7c.g_cf8229db_8dfa_4a94_a622_ad12393f9c7d".

#### Steps to Reproduce

Build a SPFX webpart that implements IDynamicDataController and on Init calls "this.context.dynamicDataSourceManager.initializeSource(this);".  
Once built deploy to a SharePoint and add to a classic page.

@VesaJuvonen 
Thanks for your contribution! Sharing is caring.

**Comment by Seiyasu** [comment]
What is your SPFx version and the library versions in package.json?

**Comment by nhadro** [comment]
Dynamic Data is only available in the "1.5.1-plusbeta" packages

![image](https://user-images.githubusercontent.com/6069834/45432785-51d05400-b670-11e8-8752-bcd55c01d232.png)

**Comment by VesaJuvonen** [comment]
Lack of dynamic data support in the classic is by design and we are not currently planning to support this with the GA version of the dynamic data. Notice that there are also other ways to bypass the content between the components if needed for the classic experience.
