### ISSUE TITLE
Timeout error on running from local/hosted workbench in Chrome

### ISSUE THREAD

**Issue by liricy** [SharePoint/sp-dev-docs#2517]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

App runs from local/hosted workbench in chrome without any timeout error even if other chrome instances are running.

#### Observed Behavior

If I have a chrome browser open, on running app from local/hosted workbench, chrome opens and I get following errors: 

![image](https://user-images.githubusercontent.com/6519992/45378289-e162fd80-b5b1-11e8-8833-a75cc8d2cc2b.png)

![image](https://user-images.githubusercontent.com/6519992/45378303-e9bb3880-b5b1-11e8-8a7f-ccba327d59dd.png)

On closing all chrome instances and run the app again, it will work fine.

#### Steps to Reproduce

- Open multiple chrome browsers
- Run gulp serve --nobrowser
- Select local/hosted workbench

Any suggestions to fix this issue? Thanks!

**Comment by Seiyasu** [comment]
Researching on this to check the cause, will update the latest news here.

**Comment by licypal** [comment]
Any updates on this please?

**Comment by licypal** [comment]
I'm hitting the same url:

![image](https://user-images.githubusercontent.com/6519992/45516788-1e212700-b761-11e8-9843-130e34c2e293.png)

**Comment by patmill** [comment]
Hmn.  If you look at the network trace in Chrome, can you see where it is stalling out?  Does :5432/workbench redirect you to :4321/...

What happens if you run it without --nobrowser , does it serve correctly?

**Comment by licypal** [comment]
Surprisingly, I don't see this timeout error with other chrome instances open since today afternoon. I'm pretty sure I didn't make any changes to fix this. If I can repro the issue, I will check and let you know. Thanks!

**Comment by licypal** [comment]
I started seeing timeout error again. Network trace doesn't show anything:

![image](https://user-images.githubusercontent.com/6519992/45562274-d05afc00-b7fe-11e8-970a-1fa6e2c174ac.png)

When I run without --nobrowser, I don't see :5432/workbench redirect you to :4321/. I only see https://localhost:4321/temp/workbench.html

**Comment by patmill** [comment]
Note that when you run with --nobrowser, you need to hit the 5432/workbench URL in order to successfully use the local workbench.

**Comment by licypal** [comment]
Ok, thanks. What about the timeout error in hosted workbench?
