### ISSUE TITLE
AddTenantTheme example does not work

### ISSUE THREAD

**Issue by pschaeflein** [SharePoint/sp-dev-docs#2518]
The specified script results in a payload that does not work.

{
	"name":"Sounders Rave Green",
 	"themeJson": {
 		"palette": {
 			"themePrimary":"#1BF242",
 			"themeLighterAlt":"#0d0b00",
 			"themeLighter":"#0b35bc",
 			"themeLight":"#322d00",
 			"themeTertiary":"#6a5f00",
 			"themeSecondary":"#1B22F2",
 			"themeDarkAlt":"#ffe817",
 			"themeDark":"#ffed4b",
 			"themeDarker":"#fff171",
 			"neutralLighterAlt":"#252525",
 			"neutralLighter":"#282828",
 			"neutralLight":"#313131",
 			"neutralQuaternaryAlt":"#3f3f3f",
 			"neutralQuaternary":"#484848",
 			"neutralTertiaryAlt":"#4f4f4f",
 			"neutralTertiary":"#c8c8c8",
 			"neutralSecondaryAlt":"#d0d0d0",
 			"neutralSecondary":"#dadada",
 			"neutralPrimary":"#ffffff",
 			"neutralDark":"#eaeaea",
 			"black":"#f8f8f8",
 			"white":"#1f1f1f",
 			"primaryBackground":"#1f1f1f",
 			"primaryText":"#ffffff",
 			"error":"#ff5f5f"
 		}
 	}
}

{
    "error": {
        "code": "-1, Microsoft.OData.Core.ODataException",
        "message": "An unexpected 'StartObject' node was found for property named 'themeJson' when reading from the JSON reader. A 'PrimitiveValue' node was expected."
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d43002-eb85-711b-a441-6fc772614e6b
* Version Independent ID: 6ef38943-3cb1-ff5f-0fbb-1498b63f6cc9
* Content: [SharePoint site theming - REST API](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by pschaeflein** [comment]
Turns out that the proper payload is as follows:

{"name":"Sounders Rave Green","themeJson":"{\"palette\":{\"themePrimary\":\"#1BF242\",\"themeLighterAlt\":\"#0d0b00\",\"themeLighter\":\"#0b35bc\",\"themeLight\":\"#322d00\",\"themeTertiary\":\"#6a5f00\",\"themeSecondary\":\"#1B22F2\",\"themeDarkAlt\":\"#ffe817\",\"themeDark\":\"#ffed4b\",\"themeDarker\":\"#fff171\",\"neutralLighterAlt\":\"#252525\",\"neutralLighter\":\"#282828\",\"neutralLight\":\"#313131\",\"neutralQuaternaryAlt\":\"#3f3f3f\",\"neutralQuaternary\":\"#484848\",\"neutralTertiaryAlt\":\"#4f4f4f\",\"neutralTertiary\":\"#c8c8c8\",\"neutralSecondaryAlt\":\"#d0d0d0\",\"neutralSecondary\":\"#dadada\",\"neutralPrimary\":\"#ffffff\",\"neutralDark\":\"#eaeaea\",\"black\":\"#f8f8f8\",\"white\":\"#1f1f1f\",\"primaryBackground\":\"#1f1f1f\",\"primaryText\":\"#ffffff\",\"error\":\"#ff5f5f\"}}"}

**Comment by Seiyasu** [comment]
Hi,  @pschaeflein , it seems you have resolve this issue. If not, feel free to reopen the issue.
