### ISSUE TITLE
Deleted SharePoint Online Client Extensibility App in AzureAD. How to get it back?

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#2522]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,
I've accidentally deleted the SharePoint Online Client Extensibility application in AzureAD.
Is there any way to get this back?

Thanks

**Comment by NickSevens** [comment]
@Seiyasu could you point me to where I can find the Recycle Bin? Just can't find it anywhere :$

**Comment by justdevelopment** [comment]
Have you tried to redeploy your package? When you accept the permissions in Central Admin it should recreate the app registration in your tenant. You might have to redo all previous permissions manually through the Azure portal if you don't want to reinstall all packages if you have multiple.

**Comment by justdevelopment** [comment]
It it the Enterprise App registration that's missing or the 'regular' App registration that's missing? The first one you might be able to find using search in the catalog? I can't test this as mine is already added there. For the App registration the above worked for me, so no other ideas there sorry. You might be able to add it manually and then past in the manifest but I have no idea what else is happening behind the scenes for this App registration that you'd then be missing.

**Comment by DnsSrinath** [comment]
Same issue with me.
"SharePoint Online Client Extensibility web application principal" is missing.
Powershell (SPOTenantServicePrincipal) gives me the error: Unknown Error
Is it possible to Enable the "SharePoint Online Client Extensibility web application principal" back?

**Comment by patmill** [comment]
@lahuey - is there a workaround for people in this state at the moment?

**Comment by NickSevens** [comment]
In the meantime I have restored the App through azure powershell.
It would however be nice if there was some sort of "reset" functionality to ensure the correct settings are set to the app (e.g. the empty app url, single/multi-tenant, ...)

**Comment by DnsSrinath** [comment]
> In the meantime I have restored the App through azure powershell.
> It would however be nice if there was some sort of "reset" functionality to ensure the correct settings are set to the app (e.g. the empty app url, single/multi-tenant, ...)

Can you please send me the steps to restore the APP through azure powershell

**Comment by NickSevens** [comment]
@DnsSrinath sure:
```
Connect-AzureAD
Get-AzureADDeletedApplication
Restore-AzureADDeletedApplication -ObjectId <your_object_id>
```

**Comment by DnsSrinath** [comment]
It worked thank you so much.. 
This saved my day bro :) thanks once again.
