### ISSUE TITLE
yo @microsoft/sharepoint Ends with an error "SyntaxError: Unexpected end of JSON input while parsing near '...ependencies":{"@octok'"

### ISSUE THREAD

**Issue by dodancs** [SharePoint/sp-dev-docs#2524]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Issuing `yo @microsoft/sharepoint` should set up a project for SharePoint Online WebPart.

#### Observed Behavior
I was following the tutorial for making a SharePoint Online WebPart from in this [link](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part).

I set up my enviroment according to the tutorial, and when I used the command `yo @microsoft/sharepoint` it went through, but npm spit out an error:

```
SyntaxError: Unexpected end of JSON input while parsing near '...ependencies":{"@octok'
```

with no information from where it got this error, I can't find the file to fix the issue manually, I'm stuck with a broken project.

The same error pops up when I do `npm install`.

#### Error log file
[2018-09-12T09_49_36_263Z-debug.log](https://github.com/SharePoint/sp-dev-docs/files/2374623/2018-09-12T09_49_36_263Z-debug.log)

#### Steps to Reproduce
- Install NodeJs (fresh install)
- `npm install -g yo gulp`
- `npm install -g @microsoft/generator-sharepoint`
- `md helloworld-webpart`
- `cd helloworld-webpart`
- `yo @microsoft/sharepoint`
- Solution name `[Enter]` (helloworld-webpart)
- Baseline packages `[Enter]` (SPO latest)
- Where to place files `[Enter]` (current folder)
- Allow deployment to all sites `[Enter]` (No)
- Which type `[Enter]` (WebPart)
- Part name `HelloWorld`
- Description `Description`
- Framework `[Enter]` (No framework)

#### Submission Guidelines
Used SW and documentation:

- NodeJs v8.12.0
- Enviroment setup - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
- SPO WebPart creation tutorial - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

#### Update 1
I switched platforms from Windows 10 Pro x64 to Ubuntu 18.10 x64 and the issue is not present on Linux platform.

**Comment by waldekmastykarz** [comment]
It seems like there was a problem downloading the typescript package, which might be corrupted in your cache. You could try clearing the npm cache and trying again.

**Comment by VesaJuvonen** [comment]
Hi @dodancs, can you provide input on the Waldek's suggestion. Did that fix the issue? By default, you certainly should not see this exception.

**Comment by dodancs** [comment]
Hello. Thanks for the suggestion, I'll try it later this week, maybe today and will provide feedback. @VesaJuvonen

**Comment by VesaJuvonen** [comment]
Closing due to no response within 2 weeks. Hopefully worked out right.
