### ISSUE TITLE
News Web Part - filters do not work properly

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#2525]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behaviour

Expected: News Items are filtered when set. Page refreshing does not influence the filtered content.

#### Observed Behaviour

On load, both web parts show all news regardless of the filters set.  (Refer to scenario below)
Web Part A - If you refresh the page, the news web parts then load the news items filtered properly.
Web Part B - Filters do not work regardless refreshing, all articles - top 4 load.

#### Steps to Reproduce

Scenario:

Communication Site is not a hub site. Tenant is set to Targeted Release.

In SitePages, News Pages contain column called "NewsType" choice field with 2 options "News A", "News B" for example. 

Add a few news articles (7), set 4 articles to "News A", set 3 articles "News B"
Then on the homepage - add two News web parts:
- News Web Part A - filtered to NewsType with value equals "News A", Layout is set to Top Story
- News Web Part B - filtered to NewsType with value equals "News B", Layout is set to Side-by-Side

All items are published and marked as News.

#### Submission Guidelines

btw - link https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev generates certificate errors. - Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID

Paul

**Comment by VesaJuvonen** [comment]
As this is out-of-the-box functionality, we can't route this through the dev process. Please submit this through the SharePoint Online admin support channels from the tenant admin tool. We can only support dev topics through this issue list. Sorry for the inconvenience.
