### ISSUE TITLE
BUG: Renaming xxxWebPart.ts to xxxWebPart.tsx throws error during gulp bundle/serve

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#2526]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

SPFX 1.6

#### Expected or Desired Behavior

Renaming entry webpart file from .ts to .tsx should not throws an error (this is fine on spfx 1.4.1)

#### Observed Behavior

Throws error: `Entry module not found: Error: Can't resolve '../..xxxWebPart.js' `

#### Steps to Reproduce

Simply rename ./src/webparts/xxxWebpart/**xxxWebPart.ts** to **xxxWebPart.tsx** and run `gulp serve`

**Comment by jonathanhotono** [comment]
@Seiyasu I uninstalled the generator-sharepoint and reinstalled it, created a helloWorldWebPart and still shows the same issue.
![image](https://user-images.githubusercontent.com/6864547/45472686-48caaa00-b778-11e8-8f64-1f4b661bb5de.png)

![image](https://user-images.githubusercontent.com/6864547/45472661-3cdee800-b778-11e8-8aea-8ef5336f59e0.png)
![image](https://user-images.githubusercontent.com/6864547/45472729-67c93c00-b778-11e8-9b66-1d7ef06a1aad.png)
helloWorldWebPart.js seems to be missing from ./lib/webparts/helloWorld/components folder
![image](https://user-images.githubusercontent.com/6864547/45472769-83ccdd80-b778-11e8-87ba-5ba4b1bcb32b.png)

**Comment by chiragshahklc** [comment]
As much as i know. you are not suppose to rename `HelloWorldWebPart.ts` file to `.tsx` file
Every file in the component folder can have .tsx file which indicates that .tsx file has react component inside it. `HelloWorldWebPart.ts` file is webpart file which has class which extends BaseClientSideWebPart so you can't rename it to .tsx file

**Comment by jonathanhotono** [comment]
@chiragshahklc 
This feature was supported on previous spfx versions and `HelloWorldWebPart.ts` imports React, so it is natural for the tooling to supports .tsx extension as well. Also in certain project we are using React Router to render the routing on the WebPart level therefore a bit of code update is required to use normal JS instead of JSX. 

Definitely not a showstopper as I can just use normal React.createElement in contrast to jsx to render which adds small inconvenience. But I definitely won't update any existing project yet until 1.6.1 released as usual.
