### ISSUE TITLE
Getting the home.aspx in a new teamsite via rest, missing sections and webparts

### ISSUE THREAD

**Issue by simonagren** [SharePoint/sp-dev-docs#2527]
#### Category
- [ ] Question
- [ ] Typo
- [  X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When a new teamsite has been created in SharePoint online, and you haven't edited the Home.aspx manually before this.
If  you want to get the welcome page (Home.aspx) via rest or PnPJS.
/_api/web/getFileByServerRelativeUrl('/sites/url/home.aspx')/listItemAllFields?$select=CanvasContent1,CommentsDisabled

You expect to get the sections and webparts of the page.

So if you try to save it and publish, all webparts is removed (since you never got any)

#### Observed Behavior

Instead you get the page with no sections etc.

![45406156-cc47a680-b665-11e8-91db-1f2328fbfcec](https://user-images.githubusercontent.com/16558321/45424779-d2567b00-b697-11e8-8250-8084a3ec575d.png)

Only after a Manual edit and publish, the same rest call gets the sections and webparts for the page.

![45406189-f5683700-b665-11e8-9261-9717d3db127a](https://user-images.githubusercontent.com/16558321/45424826-f74aee00-b697-11e8-8596-36ceb683bcfa.png)

So if you try to save it and publish, all webparts is removed (since you never got any)

#### Steps to Reproduce

In a SharePoint Online teamsite.

Use this in the browser:
 ```
https://<tenant>.sharepoint.com/sites/test2/_api/web/getFileByServerRelativeUrl('/sites/test2/home.aspx')/listItemAllFields?$select=CanvasContent1,CommentsDisabled
```

With PnPJS in SPEditor Chrome extension:
```
import { sp, ClientSidePage } from "@pnp/sp";

(async () => {
const welcomePageData = await sp.web.rootFolder.select('welcomepage').get();
const file = sp.web.getFileByServerRelativeUrl(`/sites/test2/${welcomePageData.WelcomePage}`);
const page = await ClientSidePage.fromFile(file);

await page.save();
await page.publish();
})().then(_ => console.log('Yay')).catch(console.log);
```

**Comment by patmill** [comment]
So this is interesting.  I believe the logic for the homepage is along the lines of "if the content hasn't been updated, use the default content as defined in the app".  In this way, as the default teamsites change over time (webpart X is rarely used, so let's use webpart Y instead) people that haven't explicitly changed their site will get the updates.  Unfortunately, you're working at cross-purposes.  There is no default content, so your canvas is empty.   However you save the item, which then states "the canvas is empty, but I meant it to be empty, not simply unchanged". 

Dealing with that is going to be challenging.  One possibility would be to have the PNP code have a way to generate the current default canvas content, or for your own code to have it.

**Comment by simonagren** [comment]
@patmill I'm not sure I follow you, it might be my lacking English skills :)

If I want to access the content of a newly created page programatically, For instance Home.aspx in a team site or a communications site, I am not able before a manual edit/publish?

And for me to generate the default canvas content, I do believe we need to access the default canvas content from somewhere, right? Or it won't be dynamically.

**Comment by VesaJuvonen** [comment]
Technically Pat is saying that content is generated first time when you edit that, which means that your conclusion is correct. How you could do this is doing once manual edit, store that value in the code and then add that value for newly created pages. Not really a bug which we can solve as by design.

**Comment by patrick-rodgers** [comment]
To close the loop on this we are fixing it in PnPjs page creation then edit will work as expected.
