### ISSUE TITLE
Unable to add Navigation Node to TopNavigationBar (hubsite navigation)

### ISSUE THREAD

**Issue by faisal-ijaz** [SharePoint/sp-dev-docs#2529]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Adding a navigation node via GUI or PNP should add the link to the navigation. 

#### Observed Behavior

Adding a navigation node via GUI or PNP PowerShell doesn't error out, the node seems to be added (checking via Powershell) but it is not visible

#### Steps to Reproduce

Sharepoint web interface/GUI: Click edit on the hub site nav and add try to add a link. It will save, but the link doesn't appear on the navigation bar.

Powershell:  Add-PnPNavigationNode -Location TopNavigationBar -Title test -Url /sit
es/test
- adds the navigation successfully as per PowerShell. The link doesn't show up on the web interface/GUI
- Tried to add a child link under a parent and same experience
- Tried adding a full link instead of a relative link, still same issue

#### Submission Guidelines
Thanks for your contribution! Sharing is caring.

**Comment by Toonshorty** [comment]
I am experiencing the exact same problem. I've not tried PowerShell but the GUI isn't working for me, at least on one of our customer sites.

Looking at the XHR request to the SaveMenuState endpoint, the nodes array includes a number of objects and they all have a 'Key' property except for the one I am trying to create.

![Response](https://i.imgur.com/SLI6qD9.png)

Not sure if this is related?

**Comment by faisal-ijaz** [comment]
I just checked 5 other tenants and this issue seems to be replicated across all tenants on multiple site collection. Is there a workaround to add navigation nodes? If not, when can we expect a fix deployed. Sorry a bit new here, so not sure what the process is.

Thanks.

**Comment by mpaukkon** [comment]
You can edit hub navigation links on classic site settings page. Just navigate to Site information and View all site settings or type in /_layouts/15/settings.aspx after your site Url.
There you can edit site's top navigation, which affects also to hub navigation.
![image](https://user-images.githubusercontent.com/11973653/45531316-e87b4d00-b7f7-11e8-9432-05aca4ea46d1.png)

I hope this is just a temporary workaround.

**Comment by faisal-ijaz** [comment]
@mpaukkon Thank you for the workaround. The link does get added in the settings page as you have mentioned, however when we go to modern page view, the link is not visible.

**Comment by faisal-ijaz** [comment]
I just learned that, once you add the navigation node via mpaukkon's method, you can force replication on the hub nav by editting the navigation in the modern view and try to move the node up or down. It doesnt really move the node, but it forces it to become visibile. Hope this helps other folks with the same issue

**Comment by chriswharton22** [comment]
Should this issue be closed?  I have just found the same conclusions as faisal-ijaz where you need to edit the nav menu and then close it to refresh.  If we are programming the menu, this is a good work around however in my mind, this should refresh automatically

**Comment by robbe4711** [comment]
For me it is still a problem when you add navigation items by script. If this affects many pages there is no one clicking on edit to make the new items appear. How can you refresh the navigation with powershell to make that happen?

**Comment by robbe4711** [comment]
Maybe there you can call the udpate routing that is triggered, when you click on "edit"?
