### ISSUE TITLE
Should propertyPaneSettings API really be a get property?

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#253]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

A property should be something that generically isn't computationally complex or produce side effects or do calculations. The `propertyPaneSettings`  is currently a get method, but in every single instance there is computation going on here and given the recommendations in https://github.com/SharePoint/sp-dev-docs/wiki/Async-data-fetch-in-the-property-pane it very much do calculations. I would expect this to be a method instead. What's your thoughts on this?
#### Observed Behavior

It's currently a property..

**Comment by manishgarg1** [comment]
Hi Wictor, I have wondered that myself sometimes. Any suggestsions on name? "getPropertyPaneSettings" ?

**Comment by wictorwilen** [comment]
`getPropertyPaneSettings` would be the easy way out, but works. But is it really "settings", settings refer to something you can change imo? You don't change the actual *property pane* in this case. An option would be `getPropertyPaneConfiguration`  or even `getPropertyPaneProperties`. Or why not just `getPropertyPane`?

**Comment by manishgarg1** [comment]
getPropertyPaneConfiguration could work but the other two I am wary of. Specially, getProperytPane denotes that you are getting a control and not its metadata. There were also suggestions that it be called getPropertyPaneLayout. But I believe that would be wrong. There is no notion of layout in the metadata. We decide how controls get layed out.

**Comment by manishgarg1** [comment]
The new API is called "sp-webpart-base::BaseClientSideWebPart.getPropertyPaneConfiguration"

**Comment by manishgarg1** [comment]
Drop6 is now available. Hence closing the issue.
