### ISSUE TITLE
Re-Enabling and Re-Installing the same SharePoint Framework (UserCustom Action) causes the SPO Site to have multiple instances of it.  

### ISSUE THREAD

**Issue by binijustin** [SharePoint/sp-dev-docs#2534]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I uploaded a sharepoint framework extension in my app catalog, it's a solution that automatically deploy in all sites after adding it in the app catalog. When i delete the installed app and re-install or Disable and Re-Enable it in the app catalog it i should only have 1 instance of the solution.

#### Observed Behavior

When i have changes in the solution and i tried to re-upload or delete and re-upload or disable and enable the .sppkg file in the app catalog, the previous version of the app is still there with the new version. now whenever i load my website there are 6 instances of modal that is called(because i already have 5 changes upon the first installation).

![image](https://user-images.githubusercontent.com/31793709/45470552-ca164280-b760-11e8-8e51-18c8a1fc9310.png)

#### Steps to Reproduce

-Configuration of the app
I created a Sharepoint Framework Extension following [this](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions#test-the-solution-in-debug-mode) tutorial. and i added 
![image](https://user-images.githubusercontent.com/31793709/45470649-29745280-b761-11e8-92f3-cc7fa0c4da62.png)
 in the package-solution.json so when you upload the app it will automatically deploy it to all sites.

-Installing The App
When you upload the .sppkg file in the app catalog tick the checkbox that will appear.
![image](https://user-images.githubusercontent.com/31793709/45470836-c505c300-b761-11e8-9c40-1e55a66dc7a9.png)

After the installation confirm that the UserCustom Action is reflected in and "modern" sharepoint site. and try to delete the app from the app catalog and re upload it or just simply Disable and Enable it.

**Comment by patmill** [comment]
For now, you should go to the app catalog, there is a list there called "Tenant wide extensions".  This will contain an instance of each extension configuration.  Delete the ones you don't wish.

**Comment by binijustin** [comment]
> For now, you should go to the app catalog, there is a list there called "Tenant wide extensions". This will contain an instance of each extension configuration. Delete the ones you don't wish.

Thank you for this!
