### ISSUE TITLE
After upgrading to 1.6 I am having issues with js, js.map files listed as changes in VS Code. 

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2536]
Shoud I change something in gitignore or workspace settings?

#### Category
- [x ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Comment by chiragshahklc** [comment]
Try gulp clean.
and put index.ts file in src
`src/index.ts`

try running your project after that

**Comment by nikolayyordanov** [comment]
Can you please paste the recommended workspace settings for files.exclude.

**Comment by OliverZeiser** [comment]
You have to do the upgrade again. But this time also copy over the tsconfig.json from a newly created 1.6 project. This should fix your issue...

**Comment by nikolayyordanov** [comment]
Copy/pasting index.ts + tsconfig.json from newly created project have resolved the issue.
