### ISSUE TITLE
AadHttpClient CORS error "origin 'null' is not allowed"

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#2537]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Calling a AAD secured API running on localhost should work with AadHttpClient

#### Observed Behavior

When calling my remote endpoint (`https://localhost:44305/api/secured`) I receive the following CORS error:

> Failed to load https://login.microsoftonline.com/4bd4ff55-e72f-42e5-9cb5-f43aff2b2431/oauth2/authorize?client_id=412a1971-dada-434e-b230-c6f46ade0003&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dEo7JqExfzJJaqy8G2wOZOr9QOWtV7gNbgVVEc6ah9ex9N4pvlkiWjNdZhgbNByJbk_SzcUkpPAECyLJkCLZ6Q1r-EF_D6qdvhUv7FjKgVFXsgKtZxcm_jhvZPd7dwRj4Yh-8NIv-bOPdJm6BtJvBVA&nonce=636724208806787290.ZTJiNjU5ZmYtNGMxNS00MDE1LWIyOTEtNjc0MDBlMTUyZjM0MzdjMjUyNTMtNzU1OS00ZmU1LTk4ZjItNGFlZWU3NzgxZDI0&x-client-SKU=ID_NET&x-client-ver=1.0.40306.1554: **Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access**. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I followed the steps outlined at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi#consume-the-enterprise-api-secured-with-azure-ad-from-the-sharepoint-framework, except I created a new AAD application manually, and use that as authentication app for my web api running on localhost.

(I don't have an Azure subscription on my SP tenant subscription, so I couldn't create a Function app there to fully test the tutorial)

Also, when opening the https://login.microsoftonlint.com/4bd4....... url in a new tab, I'm successfully redirected to my API, without a login screen popping up or anything - so the security itself does seem to work.

Any help or ideas to fix this would be greatly appreciacted

**Comment by waldekmastykarz** [comment]
Have you implemented CORS support in your API?

**Comment by NickSevens** [comment]
Yes I have, using the following in `WebApiConfig.cs`
```
var cors = new EnableCorsAttribute($"https://<tenant>.sharepoint.com", "*", "*") { SupportsCredentials = true };
config.EnableCors(cors);
```
I've used this same API before without issue in a custom scenario, but also on a modern SharePoint page.

What I'm mostly confused by is the **origin 'null'** part of the error message I guess...

**Comment by NickSevens** [comment]
@waldekmastykarz I did get that, yes. That's what resulted in a 302 response redirecting to the login.microsoftonline.com.... url.
Now, I haven't changed anything to code/settings at all, and I see it's working now. I'm not sure why?
Perhaps some sort of permission propagation that needed to be done overnight?

**Comment by waldekmastykarz** [comment]
Great to hear it's working now. Is it a new tenant or one that you've had for a while?

**Comment by NickSevens** [comment]
It’s a new development tenant. I created it 3 days ago to test the aadhttpclient :)

Op 14 sep. 2018 om 19:40 heeft Waldek Mastykarz <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Great to hear it's working now. Is it a new tenant or one that you've had for a while?

**Comment by waldekmastykarz** [comment]
Maybe it indeed takes a moment for all resources to be propagated. Weird though that it was the CORS request failing. You haven't by any chance examined the access token in the failing request, have you?

**Comment by Hmoulvad** [comment]
I have the same problem here with my WebApplication trying to access my endpoint. So the solution to this problem is to wait a bit or?

**Comment by sharpost** [comment]
Following the same procedure, which authentication mechanism as API works with aadhttps client. I have tried UseOpenIdConnectAuthentication but its not working

**Comment by TanmayDharmaraj** [comment]
I am facing the same issue. Gave it almost a day thinking it will get resolved magically. No luck yet.

- using `app.UseCors(CorsOptions.AllowAll);` in Startup.cs (OWIN). 
- I do see a successful preflight request that results in a 302 to login.microsoftonline.com.

Does anyone know how long should i wait ?

**Comment by westleyMS** [comment]
Make sure that in the O365 API Management there are no waiting requests for authorization, and on the azure side too.
