### ISSUE TITLE
Is SPHttpClientBatch still in beta as of SPFx 1.6?

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#2540]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is `SPHttpClientBatch` still in beta as of SPFx 1.6 and is it expected to go GA in 1.7?

#### Observed Behavior

The `SPHttpClientBatch` class along with `ISPHttpClientBatchOptions` and `ISPHttpClientBatchCreationOptions` are only available when an SPFx 1.6 project is created with the `--plusbeta` flag

#### Steps to Reproduce

Install/Update to the SPFx 1.6 generator

- Create a new project with `yo @microsoft/sharepoint`
- Observe that SPHttpClientBatch and other batching classes are not available from the `@microsoft/sp-http` package
- Now create a new project with `yo @microsoft/sharepoint --plusbeta`
- Observe that SPHttpClientBatch and other batching classes are available.

**Comment by kchiragowni** [comment]
+1

**Comment by mmsharepoint** [comment]
Yes, experienced the same and was wondering as some sources (AC's blog, SIG call) said it would be GA already with 1.6.0

**Comment by levalencia** [comment]
+1

**Comment by andrewconnell** [comment]
My understanding is that batch support, according to the docs & from chat during the bi-weekly JS/SPFx SIG call, is GA, not preview. However, as of v1.6.0 you need to include the `-plusbeta` version of the packages... so... it's not clear.

**Comment by VesaJuvonen** [comment]
Batch options are still in preview also with 1.7 and not GA'd. We are working a long-term solution. We will be covering few options on upcoming community calls for the right solution to get your input.
