### ISSUE TITLE
Webpack warning prevents gulp bundle -ship from working. 

### ISSUE THREAD

**Issue by danielsegan** [SharePoint/sp-dev-docs#2542]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
running gulp bundle -ship should succeed. Running gulp serve should (hopefully) produce clean output without warning. 

#### Observed Behavior
I created a new SPFx web part project from the 1.6 yeomen generator. I added my components. The web part appears to be working fine, however when I run gulp bundle or gulp serve I see the following warning which prevents bundling with the -ship option

Warning - [webpack] 'dist':
./node_modules/fbjs/lib/setImmediate.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/source-map-loader/index.js!C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/fbjs/lib/setImmediate.js
    Used by 1 module(s), i. e.
    C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/source-map-loader/index.js!C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/draft-js/lib/editOnBeforeInput.js
* C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/source-map-loader/index.js!C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/fbjs/lib/setimmediate.js
    Used by 2 module(s), i. e.
    C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/source-map-loader/index.js!C:/Users/ds/src/vsts/XSharepointModern/mht-nd-webpart/node_modules/fbjs/lib/setImmediate.js

#### Steps to Reproduce
In my case, just creating a solution from the 1.6 generator and executing gulp serve, or gulp bundle will display the above warning. Using bundle -ship fails as it will not complete if there is any output detected on stderr.

**Comment by waldekmastykarz** [comment]
Could you try doing the following:
- delete node_modules
- delete package-lock.json
- execute `npm install`
- execute `gulp serve --ship`

**Comment by danielsegan** [comment]
Thanks. I tried those steps, and I'm still running into the same things.

**Comment by waldekmastykarz** [comment]
Are you building the project locally or via a build (VSTS)?

**Comment by danielsegan** [comment]
This is a local build. It's occurring on two different local environments.

**Comment by waldekmastykarz** [comment]
Can you reproduce the behavior on a standard v1.6 project without any additions?

**Comment by danielsegan** [comment]
OK. I just tried that, and it looks like it builds cleanly for an empty "HelloWorld" project. 

Which means that it's something I added no doubt.

**Comment by patmill** [comment]
Maybe give yarn a try?  Often when I've seen errors like this, it's inevitably that npm installed a couple of versions of the same package in different locations, and the compiler gets confused.

**Comment by danielsegan** [comment]
Will do. Thanks.

**Comment by danielsegan** [comment]
Sorry, you can close this. It's not a framework issue. It was due to the antd UI components that I was using. They have a huge dependency tree, and the conflicting package was related to that. I swapped it out with something else, and it's all good.
