### ISSUE TITLE
[ts] Cannot find namespace 'JQueryUI'.

### ISSUE THREAD

**Issue by amtrived1** [SharePoint/sp-dev-docs#2543]
When i tried the example as mentioned in the page. I got [ts] Cannot find namespace 'JQueryUI' error while building the app using "gulp serve".

if i change the import module as 'import * as JQueryUI from "jqueryui";' i was able to build successfully but got issue with Accordion as in workbench got console error of 'jQuery(...).accordion is not a function'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Hi, @amtrived1 . Please provide the version information on your side, such as NodeJS/SPFx/React/JQueryUI and so on.

**Comment by amtrived1** [comment]
> Could you upgrade your SPFx version first and retry it?

updated to
`"dependencies": {
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-lodash-subset": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-base": "1.6.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "jquery": "^2.2.4",
    "jqueryui": "^1.11.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.6.0",
    "@microsoft/sp-module-interfaces": "1.6.0",
    "@microsoft/sp-webpart-workbench": "1.6.0",
    "tslint-microsoft-contrib": "~5.0.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }`

But still facing same issue

**Comment by waldekmastykarz** [comment]
Could it be that you're missing TypeScript type definitions for jQuery and jQueryUI? They are listed in the tutorial, but not in your package.json. Run in the command line:

```sh
npm i @types/jquery@2 @types/jqueryui --save-dev
```

**Comment by amtrived1** [comment]
Thanks @waldekmastykarz . That was the missing point.
