### ISSUE TITLE
Number of Hub Sites

### ISSUE THREAD

**Issue by alisalih1** [SharePoint/sp-dev-docs#2550]
The number of hub sites has been increased to 100 per this announcement. https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-hub-sites-updates-plus-new-page-and-web-part/ba-p/234574

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a08d140-05fb-f0b3-ac8f-64acf63d0195
* Version Independent ID: 2b27f059-dfbf-7cc1-4f18-220d068056a6
* Content: [SharePoint hub sites overview](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/hub-site-overview)
* Content Source: [docs/features/hub-site/hub-site-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/hub-site/hub-site-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by joegasper** [comment]
Docs page pointing to 2000 limit: https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites
