### ISSUE TITLE
Feature deployment at site collection level

### ISSUE THREAD

**Issue by lsky3998** [SharePoint/sp-dev-docs#2552]
Can you also provide steps on how to include site collection level feature in provider-hosted addins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f40d5604-9298-5e6f-7b86-6ad239a93047
* Version Independent ID: 41c25901-4acb-ee80-295f-f1ee01e3f1cf
* Content: [Create a provider-hosted add-in that includes a custom SharePoint list and content type](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte#troubleshooting)
* Content Source: [docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Hi, Isky3998. Thanks for the advise, we will research on this and contact with the product team/docs team. If possible, appropriate documentation will be updated later.

**Comment by andrewconnell** [comment]
Not possible... you can't deploy to the site collection level with add-ins.
