### ISSUE TITLE
IS it possible add office 365 group to sharepoint site group using pnpjs

### ISSUE THREAD

**Issue by VinodhNarayanan** [SharePoint/sp-dev-docs#2555]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Thanks for your contribution! Sharing is caring.

**Comment by KingKangMSFT** [comment]
Could you provide more information on what environment you would like to to add office 365 group?

**Comment by VinodhNarayanan** [comment]
> Could you provide more information on what environment you would like to to add office 365 group?

Am creating subsite using sharepoint  PNP Js, When creating a subsite we are creating Office 365 group using pnp/graph. I need to set this office 365 group permission to the subsite..
