### ISSUE TITLE
missing a word/phrase?

### ISSUE THREAD

**Issue by ttplaya** [SharePoint/sp-dev-docs#2557]
Under the Authoring, design, and branding in SharePoint section, I think there is something missing after the word "any" in the following sentence:

The content-creation workflow is revised so that you can create content using any —and author great content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0058942b-7257-da9b-e294-70966abed977
* Version Independent ID: df4bb886-a309-ec22-3e80-840bfe3ee5d7
* Content: [Build sites for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/build-sites-for-sharepoint)
* Content Source: [docs/general-development/build-sites-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/build-sites-for-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Hi,ttplaya. Thanks for your post. Relevant guys will research this and update the docs later.
