### ISSUE TITLE
If validation promise is rejected, nothing is displayed to the user

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#256]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

When the validation (for web part properties) promise fails, nothing is shown to the user. Displaying something like "the data validation failed" could help the user knowing something is wrong. This technical error should be displayed in a different way than when the data is invalid to let the user know something went wrong.
#### Observed Behavior

No error message when validation promise is rejected.
#### Steps to Reproduce

Implement a webpart property validation and reject the promise.

**Comment by patmill** [comment]
@manishgarg1 , @srideshpande

**Comment by srideshpande** [comment]
Hello @baywet,

I apologize that I could not get to it before. Thanks for raising your concern.

Here are the instructions for the `onGetErrorMessage` from the `IPropertyPaneTextField`.

    The method is used to get the validation error message and determine whether the input value is valid or not.
   
    * When it returns string:
       * If valid, it returns empty string.
       * If invalid, it returns the error message string and an error message is displayed below the text field.
   
    * When it returns Promise<string>:
         * The resolved value is display as error message.
         * The rejected, the value is thrown away.
    
    onGetErrorMessage?: (value: string) => string | Promise<string>;

Today the text field is designed to say that either the validation is successful or failed. In your case, if the promise is to be rejected and you want to show it as a different message other than red colored error message, then you cannot do this.

Feel free to send it as part of a new feature request, we will look into it. However, this will not be considered as something we would fix on the property pane front.

I am closing this issue now. Please feel free to re-open if you think necessary or as said earlier create a new feature request.

Thanks!

**Comment by baywet** [comment]
Thanks for getting back on that subject @srideshpande it clarifies the point. However a question still stands: what happens if the onGetErrorMessage raises an exception?
