### ISSUE TITLE
Q2 or later?

### ISSUE THREAD

**Issue by rmanjoney** [SharePoint/sp-dev-docs#2560]
"The option to connect an Office 365 group to an existing site is not yet available and will be released during Q2 of calendar year 2018" - this article doesn't clarify whether that refers to the ability to do it via PowerShell or via the GUI - we're nearly into Q4 and the feature isn't in the GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60de4a4c-bcb7-7bd4-5a11-2aa014d0a93b
* Version Independent ID: 2a477349-3aa5-8718-17ea-661b9aa089d7
* Content: [Overview of the Connect to new Office 365 group feature](https://docs.microsoft.com/en-us/sharepoint/dev/features/groupify/groupify-overview)
* Content Source: [docs/features/groupify/groupify-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/groupify/groupify-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It's documented in the "see also" section of this doc.
