### ISSUE TITLE
JSON Schema more detailed documentaion required

### ISSUE THREAD

**Issue by Justin-Nash** [SharePoint/sp-dev-docs#2562]
Please confirm that this documentation is related to this: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema

If so can you please update this documentation or the parent documentation to reflect how to use the theme JSON as part of the JSON Schema. 

Also there is typos in the documentation all JSON keys are meant to be wrapped in quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4c91be-dca2-6411-b707-a023ad26306c
* Version Independent ID: 29ba4619-814e-784a-04a8-84b4d56933dd
* Content: [SharePoint site theming - JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
If the theme has been applied, then it can be referenced from the site design schema.
