### ISSUE TITLE
Provide corresponding classes from CSOM and JSOM

### ISSUE THREAD

**Issue by Rohitwghela** [SharePoint/sp-dev-docs#2563]
It will be good if you start showing the information about corresponding classes from CSOM and JSOM in the same article. This will save lot of time of developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b04ffce-fb2d-75fe-4694-b15a65d0f186
* Version Independent ID: 50e54a96-3942-f847-6220-8c61e1f275d6
* Content: [SPEmailMessage Class (Microsoft.SharePoint.Utilities)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.utilities.spemailmessage?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Utilities/SPEmailMessage.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Utilities/SPEmailMessage.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Thanks for the feedback, but at this time, this is not currently planned for the docs.
