### ISSUE TITLE
[LOC] Unfunctional link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#2566]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/schema/parameter-element-in-parameters-bdcmetadata-schema
2. Search for "TypeDescriptor"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects to an existing page

**GH article**:
https://github.com/SharePoint/sp-dev-docs/blob/live/docs/schema/parameter-element-in-parameters-bdcmetadata-schema.md

![image](https://user-images.githubusercontent.com/16706698/45686656-3c19cd80-bb4d-11e8-9094-11f8a42c9ce7.png)

**Comment by thechriskent** [comment]
Thanks!
