### ISSUE TITLE
Looks Like Firefox is not supported anymore

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2594]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Modern SharePoint pages render normally if Firefox

#### Observed Behavior
Something really weird.
![screen shot 2018-09-18 at 2 01 16 pm](https://user-images.githubusercontent.com/17036219/45716392-9a45b100-bb4b-11e8-8a9c-377e91b4166d.png)

#### Steps to Reproduce
Open Site Contents page in Firefox

**Comment by KingKangMSFT** [comment]
Hi, AJIXumuK. Thanks for your post. I have tried the reproduce steps but it works well on my machine. And we can only support dev topics through this issue list. Sorry for the inconvenience.

**Comment by VesaJuvonen** [comment]
@AJIXuMuK - still an issue? We can't see this in our side, so assuming that it was a momentary exception on your side. 

![image](https://user-images.githubusercontent.com/7446437/47521337-6b81cf80-d89b-11e8-9bc3-0b1bf9fc50a1.png)

Closing as FireFox is fine in general. If still an issue, let's reopen.

**Comment by AJIXuMuK** [comment]
Yep, it looks fine now. Probably was some temp issue.
And sorry for not reporting it as resolved here.
I thought that

> And we can only support dev topics through this issue list

automatically leads to closing of the issue :)
