### ISSUE TITLE
Typo in first paragraph

### ISSUE THREAD

**Issue by CrackerboxOnline** [SharePoint/sp-dev-docs#2595]
'apartment' instead of 'department'.  Keep up the great work.  Loving all the new dev functionality in SPO!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340d6888-f691-be04-6d18-61af54845564
* Version Independent ID: 81c35293-f9fa-f961-c82a-116b8a268efe
* Content: [Scoping access to SharePoint site designs](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-scoping)
* Content Source: [docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-scoping.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
fixed
