### ISSUE TITLE
No command to set a custom message for access request page

### ISSUE THREAD

**Issue by rom-1** [SharePoint/sp-dev-docs#2597]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
####

Since about March 2018 it is possible to set a custom message at the access request page GUI in Sharepoint Online. See [Screenshot here](https://i.imgur.com/CQac2LE.png).

Since we are setting up our Sharepoint Webs using PnPPowershell, we want to add a message here using powershell. Since March I am monitoring the [changelog](https://github.com/SharePoint/PnP-PowerShell/blob/master/CHANGELOG.md) and the Documentation of [Set-PNPRequestaccessmails](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnprequestaccessemails?view=sharepoint-ps), but there does not seem to be any change or addition here.

Am I missing something? Is there a pnp powershell command available to change the custom message for access request page? Is it on the roadmap?

**Comment by TheMiao** [comment]
@rom-1  Could you provide me the link for the doc you read and also reproduce steps?

I would like to test it from my end.

**Comment by rom-1** [comment]
@TheMiao thank you for taking a look at this issue.

I am sorry, I do not understand which kind of doc you are requesting from me. I just wanted to point out that Microsoft introduced a new feature in Sharepoint Online in beginning of 2018 ("[access request settings -> custom message](https://support.office.com/en-us/article/set-up-and-manage-access-requests-94b26e0b-2822-49d4-929a-8455698654b3#bk_enableallow)") which I seem to not be able to setup using [Set-PNPRequestaccessmails](Set-PNPRequestaccessmails) or any similar command.

Either this feature is not implemented in SharepointPnP yet, or I am missing the documentation for it. In the first case I wonder if this missing option is going to be implemented soon....

Sorry, I am not sure how you can reproduce steps of a missing command/argument.

**Comment by rom-1** [comment]
Also, quoting a [technet support reply dated May 23th 2018](https://social.technet.microsoft.com/Forums/en-US/d3bfc18e-fbba-418a-bbed-88a73098550c/include-a-custom-message-to-users-who-see-access-request-page-for-sharepoint-online?forum=onlineservicessharepoint), telling us sth. about the SharepointOnline.CSOM... maybe thats why it is not possible yet for SharepointPnP to implement?

> I check the latest version(16.1.7618.1200) of the Microsoft.SharePointOnline.CSOM package, unfortunately ,it can't provide a web property to set the "Include a custom message to users who see access request page" for Access Requests Settings currently

**Comment by TheMiao** [comment]
I've found the solution provided by other developers
It may help you how to Set up and manage access requests 

https://www.c-sharpcorner.com/blogs/allow-access-requests-email-settings-in-sharepoint-site-using-pnp-powershell

https://skodvinhvammen.wordpress.com/2018/08/08/configure-settings-for-access-requests-and-sharing-using-microsoft-flow-and-rest/

**Comment by TheMiao** [comment]
Thanks for the information. 

Unfortunately I haven't found any docs or reference either from SP  PnP Cmdlets list below. 
https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps#webs

I guess the the Cmdlets will add soon but still not yet.

**Comment by rom-1** [comment]
Yes, thats exactly what I figured out in my original posting, quote:
> Is there a pnp powershell command available to change the custom message for access request page? Is it on the roadmap?

So, thats why I just wanted to report back that this is a missing feature....

**Comment by rom-1** [comment]
As there seem to be no progress in this topic, can sombody please label this as uservoice-request? I mean, this is obviously a missing parameter of the cmdlet **Set-PNPRequestaccessmails**

**Comment by DeanGross** [comment]
I have the same request
