### ISSUE TITLE
Missing works/phrases?

### ISSUE THREAD

**Issue by ttplaya** [SharePoint/sp-dev-docs#2599]
In the "Determine where the styles for a page layout should go" section, both the 4th and 5th paragraphs seem to be missing a phrase:

4th paragraph: "For example, you can have a ____ with id="xyz" in one page layout that appears on the left..."
5th paragraph: "This way, for example, a ____ with id="abc" can display large text in one channel..."

I think there should be something in the ____?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53944252-7624-4b1c-970d-398b69b9fee1
* Version Independent ID: 7aede32f-6ba1-3875-cb1d-7fa9570a7674
* Content: [Create a page layout in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-page-layout-in-sharepoint)
* Content Source: [docs/general-development/how-to-create-a-page-layout-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-create-a-page-layout-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for you post. I have confirm the issue, and will contact the content team to revise the content.

**Comment by bcameron1231** [comment]
I noticed the documentation had duplicate content and the 2nd paragraph had the phrasing. I submitted a PR for this #2616

**Comment by thechriskent** [comment]
The issue was with how `<div>` was being escaped (that's the missing part in your). I've submitted a change to get this fixed. Thanks!
