### ISSUE TITLE
Various issues with yo @microsoft/sharepoint

### ISSUE THREAD

**Issue by robhasos** [SharePoint/sp-dev-docs#26]
A number of issues appear when running the yo @microsoft/sharepoint command.

- Several deprecated warnings...
- Failure to download MS packages from https://registry.npmjs.org/tslint-microsoft-contrib

npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[      ............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/tslint-microsoft-contrib[      ............] | fetchMetadata: sill mapToRegistryTerminate batch job (Y/N)? yMetadata: sill mapToRegistry uri https://registry.npmjs.org/tslint-microsoft-contrib

**Comment by StfBauer** [comment]
Windows, Linux, Mac or 'Bash On Windows'?
Which node version you use.

**Comment by robhasos** [comment]
Windows 10. Node v4.5.0.

________________________________

**Comment by VesaJuvonen** [comment]
These are various dependencies cross the open source packages in similar ways as NuGet packages could have dependencies on specific versions in managed code. They are warnings and we are absolutely looking into checking if the warning messages can be reduced, as in we can use different dependent versions. These do not cause however issues with the Developer Preview. It's good to remember that deprecation means that particular package is no longer updated - but it still works. It does not mean that the capability is gone. Closing for now, but feel free to re-open as needed.

**Comment by wictorwilen** [comment]
Just to add some more context to this. Given the way npm works it is impossible for Microsoft to control this. SPFx has taken dependencies on other packages that has dependencies on other packages and so forth. Some of these packages might not be updated (or even maintained). The best way to solve this is to contact the package authors, or even fix it yourself with pull requests to those packages.

**Comment by VesaJuvonen** [comment]
@stact - package is updated as part of each release (latest now from November v1.7.1) and that time we always also address deprecations. If you are seeing deprecation warnings with the 1.7.1, those have been updated after our latest release. When 1.8 goes out, we will be again addressing the deprecated packages, but as we do not own them, we do not control their lifecycle.
