### ISSUE TITLE
Allow Alternate Workbench Loading

### ISSUE THREAD

**Issue by cpoteet** [SharePoint/sp-dev-docs#260]
Using Gulp to interact with the Workbench locks you into only one way, and there should be alternate ways of loading it. For example, I am a UI designer and loathe command lines so I used Codekit or Prepos for all my task running and complication. It would be nice to support tools like that without the Node dependency.

**Comment by cpoteet** [comment]
Sorry for not utilizing the suggested format for the request. Doing this on an iPhone is awful.

**Comment by patmill** [comment]
Does hosting the workbench in your SharePoint tenancy address this issue?  There are also tools (like webstorm) where it will use gulp / node / etc. behind the scenes but not require the command line.

**Comment by cpoteet** [comment]
Webstorm locks you into an IDE, and it still requires installing Node/Gulp, so that's a no-go.

I'm not sure what hosting in the tenancy involves, but here is the desired state:

1) I can use my preferred task GUI (Codekit/Prepos) for SASS compilation/JS handling.
2) I can use the workbench with my local files and not require pushing to a remote location.

If I could pull from Github a version of the workbench where I can run locally on a local server that would be the desired end game.

**Comment by patmill** [comment]
I see - that's not going to be possible for the most part.  not because of the workbench though.  You need some sort of web host, but that could be IIS or any other server.  However, you need gulp / node / etc. to run the build tools, create the app package, etc.

**Comment by cpoteet** [comment]
I'm not concerned with creating the app packages in this workflow--just development, and I have a GUI for my own build tools. I also run MAMP/WAMP that can provide a server (Codekit and Prepos also have internal servers). I don't see why, in that scenario, it couldn't work.

**Comment by patmill** [comment]
Not sure how to close this out.  There is a hosted workbench now that doesn't require you to load from gulp (https://yourtenant.sharepoint.com/sites/foo/_layouts/15/workbench.aspx)

Additionally, you can create a webpart, have it point to localhost (or any other location), and deploy it.  From that point, you can update the files and they should get picked up.

Does this solve the issue (if it is still an issue)?  

Closing this out now.  Feel free to reopen / open a new issue.
