### ISSUE TITLE
Web part deployed to tenant + site collection app catalog

### ISSUE THREAD

**Issue by jpalo** [SharePoint/sp-dev-docs#2600]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If web part .sspkg is deployed via tenant, I could "override" the deployment by deploying updated package to site collection app catalog for testing and QA purposes before tenant wide deployment.

#### Observed Behavior
If you deploy web part .sspkg to tenant app catalog and to site collection app catalog, viewing the web part in the site collection sometimes renders the tenant app catalog version of the web part.

#### Steps to Reproduce

1. Deploy web part .sspkg to tenant app catalog
2. Enable site collection app catalog in site collection X
3. Deploy updated version (don't modify web part IDs or other configuration values, just make UI modification for testing purposes) of the web part .sspkg to app catalog of site collection X
4. Testing the web part in the site collection X, and sometimes the tenant wide web part is rendered, usually and almost always after CTRL+F5 type of refresh the site collection app catalog .sspkg version is rendered. 

Users have reported this same on IE11 and Firefox, so it is not browser dependent issue.

Using 1.6.0.

**Comment by nikskhubani** [comment]
The surprising part is not many are raising this issue. Does that mean, everybody is still in development phase? Or no one has reached to a stage where upgrade is required? @VesaJuvonen @waldekmastykarz guys please can you have a look at it?

**Comment by waldekmastykarz** [comment]
It just might be the case that no one is testing their solution in the production environment along the previous version.

**Comment by jpalo** [comment]
Let's not assume things. SP shouldn't randomly (or so it seems) pick the sspkg to use in the scenario described no matter what the actual use case is.

**Comment by waldekmastykarz** [comment]
I guess the real question is whether this scenario is supported or not. Any details @VesaJuvonen?

**Comment by bcameron1231** [comment]
From this documentation [Managed Site Collection App Catalog](https://support.office.com/en-us/article/Manage-the-Site-Collection-App-Catalog-928b9b61-a9de-4563-a7d1-6231aa9d4d19) , it says "When a component exists in both the tenant's app catalog and the Site Collection App Catalog the version in the Site Collection App Catalog will take precedence whether it is an older or newer version."  So if this is true, it sounds like a bug.
