### ISSUE TITLE
aadHttpClient not working on developer tenant

### ISSUE THREAD

**Issue by Crispify** [SharePoint/sp-dev-docs#2601]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Created a new SPFx 1.6.0 webpart. In the render function I added
```

this.context.aadHttpClientFactory.getClient("[appplication-id-guid]").then((client: AadHttpClient) => {
      client.get("https://[company].api.crm4.dynamics.com/api/data/v9.0/accounts?$select=name&$top=3", AadHttpClient.configurations.v1).then((value) => {
        
      });
    });

```
Expected the built-in aadclient to authenticate on my developer tenant. 

#### Observed Behavior

Uncaught (in promise) Error: The requested operation is part of an experimental feature that is not supported in the current environment.
    at MockAadTokenProvider.getToken (sp-loader-assembly_default.js:13770)
    at AadHttpClient.fetch (sp-loader-assembly_default.js:14264)
    at AadHttpClient.get (sp-loader-assembly_default.js:14275)
    at ContactInfoWebPart.ts:25

#### Steps to Reproduce

I got a new developer tenant just yesterday via http://dev.office.com/ after reading https://sharepoint.stackexchange.com/questions/191154/sharepoint-framework-workbench-error-the-requested-operation-is-part-of-an-exp

The subscription in my admin portal says Office 365 Enterprise E3 Developer Trial.
I create a new Modern Team Site and configured it as the hosted workbench.

**Comment by waldekmastykarz** [comment]
When calling `this.context.aadHttpClientFactory.getClient("")` you have to specify with which resource you want to communicate. If you specify an empty string, like in your example above, the AadHttpClient won't be able to obtain a valid access token to authenticate the web request.

**Comment by Crispify** [comment]
Sorry, I deleted the Guid from the example, but I'm using a App Registration following this documentation. https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/walkthrough-register-dynamics-365-app-azure-active-directory

**Comment by Crispify** [comment]
Also, I've got all this working in Postman using the app registration to retrieve a bearer token and getting data from the Dynamics CRM endpoint.

**Comment by waldekmastykarz** [comment]
Could you check if the workarounds described at http://spblog.net/post/2018/09/19/You-might-experience-errors-when-first-trying-new-SPFx-16-features help you fix the issue?

**Comment by Crispify** [comment]
Thanks for pointing me in some direction. Let's close this one. It was a hell of a fight, and I mixed up a lot of documentation that was outdated or incomplete or not what I tried to do here.

In the end I gave the SharePoint Online Client Extensibility Web Application Principal in Azure AD the permission to access Dynamics CRM. The permission request in my SPFx webpart looks like this now:

`    "webApiPermissionRequests": [
      {
         "resource": "Windows Azure Active Directory",
         "scope": "User.Read"
      },        
      {
        "resource": "AtWorkCRM",
        "scope": "user_impersonation"
      }
    ]
`

The code that is getting a client to access Dynamics API looks like:
`this.context.aadHttpClientFactory.getClient('https://debbel.crm4.dynamics.com').then...`

I still have to find out why (or if) I need that separate AtWorkCRM app registration that also has the CRM permissions, because the login url that is retrieving the token for the request uses the client-id of the SharePoint Online Client Extensibility Web Application Principal, not of the AtWorkCRM app registration.

**Comment by waldekmastykarz** [comment]
Great to hear it's working. If you communicate directly with Dynamics CRM, then you shouldn't need a separate AAD app and should be able to grant the SharePoint principal access to Dynamics CRM directly.

**Comment by Crispify** [comment]
Thanks Waldek, can you point to documentation that describes the part where you have to grant permissions on the different levels, like what to put in the package manifest, the permissions that have to be granted throught the SharePoint admin portal and the permissions in Azure on the app registration?

**Comment by waldekmastykarz** [comment]
The page you mentioned is the page to go to. There is no need to approve anything separately in the Azure Portal. All permissions requested from the solution packaged, can be managed via the SharePoint admin center, which is mentioned in the article.

**Comment by waldekmastykarz** [comment]
Such information should be provided in the documentation of Dynamics CRM as it's not specific to the SharePoint Framework but rather a generic request of permissions for an Azure AD app.

**Comment by wictorwilen** [comment]
You can either go into the manifest and get the Guids or hover your mouse over the permissions: 
![image](https://user-images.githubusercontent.com/5854279/46033429-316eb380-c0cc-11e8-896f-780b4c300c11.png)

**Comment by Crispify** [comment]
Awesome trick! Thanks!

Lennert
