### ISSUE TITLE
Problem with SPFx and the compostability model in Yeoman Generator

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2603]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx generator should call its own sub-generators in compose with install try to evaluate global installed SPFx generator. 

#### Observed Behavior
The SPFx community generator that comes with a dependency to SPFx 1.6 that should work independently from the installed generator. This dependency gets called correctly in the community generator if a lower version lets say 1.4.0 is installed on the client it always uses 1.4.0 instead of 1.6.0.

The problematical code was identified in the utility `@microsoft/generator-sharepoint/lib/common/utilities.js` JavaScript that composes with global generators instead of sub-generators.

```
// tslint:disable-next-line
function compose(generator, base, options) {
    base.composeWith(`@microsoft/sharepoint:${generator}`, options);
}
```

The code needs to be adapted to the following line to make a proper `composeWith` call.

```
// tslint:disable-next-line
function compose(generator, base, options) {
    base.composeWith(path.resolve(path.join(__dirname, '../generators/', generator)), options);
}
```

The changed code leed to another problem because the generator folder search folders for the generator are not defined in the [Yeoman Documentation](http://yeoman.io/authoring/index.html) under ```folder tree``` is not referenced in the ```package.json```.

The files entry should at least point to the following folder: `lib/generators`.

#### Steps to Reproduce
It is not that easy to have two generators installed on one machine so to reproduce this is recommended to install the community generator 1.0.2.

```
npm install -g @pnp/generator-spfx@1.0.2
```

Run community generator with a different version installed as the main generator 1.5.0 at least for example.

```
npm install -g @microsoft/generator-sharepoint@1.5.0
```

Run a new project using the community generator and check the installed dependencies. This should all reference to 1.5.0 instead of 1.6.0.

**Comment by VesaJuvonen** [comment]
FYI for others tracking this. We will have a one-to-one meeting with Stefan on checking the pending Yeoman issues he has found.

**Comment by patmill** [comment]
We've added this to the feedback.  Thanks,
