### ISSUE TITLE
Is it possible to customize the Edit/Disp/New Forms in the classic experience and get the provisioning template

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2604]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I saw that the provisioning schema has the pnp:pages element. But I am not sure how can I generate a provisioning template for example for a List/Tasks/AllItems.aspx.

**Comment by Seiyasu** [comment]
We can generate teamplate for List/Tasks/AllItems page. But as you may know, the provisioning is mainly for modern pages.

**https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/Samples/WebPartPage.xml**
> http://sharepoint.handsontek.net/2018/02/04/create-a-modern-sharepoint-site-template-with-multiple-pages-using-the-pnp-provisioning-engine/

`pushd (Split-Path -Path $MyInvocation.MyCommand.Definition -Parent)
$saveDir = (Resolve-path ".\")
$siteURL = Read-Host "Please enter your site URL"
 
Write-Host "Connecting to: $siteURL"
Connect-PnPOnline -Url $siteURL; 
Write-Host "Connected!"
 
$web = Get-PnPWeb
$sourceSite = $web.ServerRelativeUrl
$library = "Site Pages"
 
#get all pages in the site pages library
$pages = Get-PnPListItem -List $library
 
#save current homepage
$currentHomePage = Get-PnPHomePage
 
$pagesList = New-Object System.Collections.Generic.List[System.Object]
 
$pageNumber = 1
 
foreach($page in $pages){
	if($page.FileSystemObjectType -eq "File"){
		$pagePath = $page.FieldValues["FileRef"]
	    $pageFile = $pagePath -replace $sourceSite, ""
		$pageTemplate = $pageFile -replace "/SitePages/","" -replace ".aspx",".xml"
	    $pagesList.Add($($pageTemplate -replace "./TemplateWithPages",""))	
		
		#set current page as home page
		Set-PnPHomePage -RootFolderRelativeUrl ($pagePath -replace ($sourceSite+"/"), "")
		
		Write-Host ("Saving page #" + $pageNumber + " - " + $pageTemplate)
		
		if($pageNumber -eq 1){
			Get-PnPProvisioningTemplate -Out $($saveDir.Path + "\" + $pageTemplate)
		}else{
			Get-PnPProvisioningTemplate -Out $($saveDir.Path + "\" + $pageTemplate) -Handlers PageContents
		}
		
		$pageNumber++
	}
}
 
$pagesList.ToArray()
 
#apply default default homepage
Set-PnPHomePage -RootFolderRelativeUrl $currentHomePage
 
#copy base template 
Copy-item -path ($saveDir.Path + "\" + $pagesList[0]) -destination ($saveDir.Path + "\Template.xml")
 
#open main xml
$mainFile = [xml][io.File]::ReadAllText($($saveDir.Path + $("\Template.xml")))
$clientSidePages = $mainFile.Provisioning.Templates.ProvisioningTemplate.ClientSidePages
 
#remove pages to avoid duplicates 
$clientSidePages.RemoveChild($mainFile.Provisioning.Templates.ProvisioningTemplate.ClientSidePages.ClientSidePage)
 
foreach( $page in $pagesList ){
	#open page template xml
	$xmlContents = [xml][io.File]::ReadAllText($saveDir.Path + "\" + $page)
	foreach($node in $xmlContents.Provisioning.Templates.ProvisioningTemplate.ClientSidePages.ClientSidePage)
	{
			
		#copy nodes from page xml
		$importNode = $clientSidePages.OwnerDocument.ImportNode($node, $true);
		$clientSidePages.AppendChild($importNode) | Out-Null
		
		#save final tempate
		$mainFile.Save($($saveDir.Path + $("\Template.xml")))
	
	}
}`
