### ISSUE TITLE
It cannot show the "Allow debug scripts",Not the reason for browser, the reason for..

### ISSUE THREAD

**Issue by jxnx888** [SharePoint/sp-dev-docs#2606]
There is  “Update pageURL to match your own tenant, which you want to use for testing. You can use any URL with modern experience. “ under “Debug your Application Customizer”.
I spent half day to find why I cannot popup the “Allow debug scripts”! The URL should be a page in your site. Home page does not work(the video tutorial and the figure is a page called home.aspx, that’s the reason why my url did not work)!

**Comment by KingKangMSFT** [comment]
Thanks for your post, could you please submit more detail to describe your issue

**Comment by VesaJuvonen** [comment]
Unfortunately, the issue content does not provide enough information to determine what's wrong and what we can fix, so closing this one as there was no further input given.
