### ISSUE TITLE
MSGraphClient and External Users

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2607]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We are using MSGraphClient to get the user profile photo.  

#### Observed Behavior

401 errors occur when the user is an external one and trying to request https://graph.microsoft.com/v1.0/me/photo/$value. What permissions should be given to the user?

**Comment by Seiyasu** [comment]
Please submit this through the StackOverflow. We can only support dev topics through this issue list. Sorry for the inconvenience.
