### ISSUE TITLE
AddValidateUpdateItemUsingPath not available on SP OnPrem

### ISSUE THREAD

**Issue by UeliSchwarz** [SharePoint/sp-dev-docs#2608]
The Endpoint is not available on SP OnPrem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thank you for your posted, could you please provide more information about the response of the endpoint?

**Comment by janis-veinbergs** [comment]
@KingKangMSFT The response is:
```
HTTP/1.1 404 Not Found
...
MicrosoftSharePointTeamServices: 15.0.0.4927
...

{"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request AddValidateUpdateItemUsingPath."}}}
```

Well, obviously not supported in SharePoint 2013. But the tip says: SharePoint 2013 or later.

**Comment by andrewconnell** [comment]
The SharePoint REST API is available in SharePoint Server 2013 & higher.

**Comment by MarcHochleutner-Koellisch** [comment]
The endpoint "AddValidateUpdateItemUsingPath" is on premise 2013 and 2016 not available. I tested it on several servers and patch levels.
