### ISSUE TITLE
Installed App Catalog Web Parts no Longer Available

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#261]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Using "gulp bundle --ship" and "gulp package-solution --ship" then installing and deploying the generated "webpart.spapp" into the Apps for SharePoint Catalog. The app should be available for use by sites using the new modern toolbox on modern pages or the web part custom section on classic pages. There should be no need for localhost assets.

#### Observed Behavior
Since yesterday (10/26/2016) new --ship "webpart.spapp" app installations are not available in the web part toolbox on modern pages or in the custom web part picker on Classic pages. When loaded in the SharePoint Workbench.aspx they require localhost assets.

#### Steps to Reproduce
This was not the case prior to 10/26. This can be recreated with the Drop 5 Hello World web part. Build using the --ship flag and install and deploy the web part into SharePoint. Is it available for use in sites?

**Comment by patmill** [comment]
So we fixed an issue recently where webparts were visible in site collections that had not installed them.  Could that be the issue?  If you go to the site collection and add an app, choosing the package you just uploaded / deployed, does it fix the issue?

As an aside, we have an item in our backlog for a webpart developer to be able to say that a specific webpart doesn't need to be installed.

**Comment by jaredbuttars** [comment]
This can be marked as resolved. I forgot an important step. My bad. :/

The backlog item sound interesting. It would be awesome if apps that were specified to not require installation would simply be available to all sites on the tenant. That would have simplified things in this case for sure and would be very useful to our organization.

Thank you.
