### ISSUE TITLE
Display the version of SPFx in the Yeoman Splash Screen

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-docs#2613]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the Yeoman generator to scaffold a new SPFx project, it would be really useful to see the SPFx version we'll end up with in the generator splash screen. Unless I'm missing something, we can only figure that out by peeking into the package.json file after installation. Since installation takes a good, long while, it would be great to know what we're doing up front just to have an escape point to upgrade, as needed.

![2018-09-21_10-44-00](https://user-images.githubusercontent.com/1295627/45889539-b8e7ba00-bd8e-11e8-9dae-79032550b4ec.jpg)

Thanks for your contribution! Sharing is caring.

**Comment by StfBauer** [comment]
For more advanced use you can even be more specific with:

```
npm -g ls @microsoft/generator-spfx --depth=0
```

This will list you only the generator.

**Comment by VesaJuvonen** [comment]
thx Marc, we have added this to the backlog and hopefully will get it there in future. Obviously not as a critical priority.
