### ISSUE TITLE
SPFx Enterprise Guidance: about making an app "available for use in the site collection“

### ISSUE THREAD

**Issue by samculver** [SharePoint/sp-dev-docs#2625]
#### Category

- [x] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In the article about “Enterprise Guidance” for SPFx it says: “To enable a SharePoint Framework solution on a site collection, the site collection administrator must add it to the site collection. This is done in the same way as for SharePoint Add-ins, by selecting to Add a new app on the site collection, and then choosing the solution from the list of apps. Once the app is added, it is available for use in the site collection.”

https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/enterprise-guidance.md

I’m not sure if this paragraph is intended to mean you can make the app available anywhere in a Site Collection by adding it to one place in the Site Collection. I could be wrong, but I understand that SPFx apps need to be added to each individual subsite unless you were using “tenant scoped” deployment which is only available in SP 2019 and SPO. I am working in SharePoint 2016 and would love to know if there is a way I can avoid adding the SPFx app to each subsite in an environment that has hundreds of subsites.

Thanks.

**Comment by TheMiao** [comment]
Hi @samculver 
For your last question (avoid add SPFx web part/extension multiple times), you can try deployment option to select which sites you want to add for your app.

This [blog ](https://blogs.msdn.microsoft.com/richard_dizeregas_blog/2013/03/04/sharepoint-2013-app-deployment-through-app-stapling/)talks about how to deploy apps in multiple sites.
