### ISSUE TITLE
Events web part

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#2628]
Great writeup, but I am trying to build the Events web part using React. It looks like its a document card, but not sure how to get the datebox and other classes without recreating them manually. Any tips on how to browse the namespaces/css if its not listed on the Fabric or React UI websites? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f89fed-848e-50b9-6be4-657824ad262e
* Version Independent ID: 3d3c5227-7281-ef49-a2d1-686c0a049497
* Content: [Use Office UI Fabric React components in your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components)
* Content Source: [docs/spfx/web-parts/get-started/use-fabric-react-components.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/use-fabric-react-components.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
You can try to retrieve the namespace/css from https://github.com/OfficeDev/office-ui-fabric-react/wiki or see the source code.
