### ISSUE TITLE
getFileByServerRelativeUrl with # in file name

### ISSUE THREAD

**Issue by jpalo** [SharePoint/sp-dev-docs#2630]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'd be able to fetch file using `getFileByServerRelativeUrl` even if file name contains hash (#).

#### Observed Behavior
`https://tenant.sharepoint.com/sites/mysc/_api/web/getFileByServerRelativeUrl('%2Fsites%mysc%mydoclib%2Ffolder1%2Ffolder2%2Ffolder3%2F6Doc%23%3B%20Project%20Name.XLS')/$value` returns SPException _The file /sites/mysc/mydoclib/folder1/folder2/folder3/6Doc#; Project Name.XLS does not exist_.

#### Steps to Reproduce
I have file in `/sites/mysc/mydoclib/folder1/folder2/folder3/6Doc#; Project Name.XLS`. I need to get hold of the file (in order to copy it to another site collection), so in my SPFx web part I do

```
let file = sourceWeb.getFileByServerRelativeUrl(f.Path);
file.getBlob().then(blob => {
   // deal with the file
});
```
where `f.Path` is `encodeURIComponent`'ed path of the file, so in the end it makes REST call to 

`https://tenant.sharepoint.com/sites/mysc/_api/web/getFileByServerRelativeUrl('%2Fsites%mysc%mydoclib%2Ffolder1%2Ffolder2%2Ffolder3%2F6Doc%23%3B%20Project%20Name.XLS')/$value`

Not doing `encodeURIComponent` to the path results same error. If I simply rename the file and remove #,  `getFileByServerRelativeUrl` works without issues.

**Comment by Seiyasu** [comment]
Why do you must use the # in file name, it is a bad naming conventions/UX. https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa

**Comment by jpalo** [comment]
I agree, but # is valid in SharePoint Online, so I need to ensure my implementation doesn't break if/when someone has that in file name.

**Comment by Seiyasu** [comment]
Although the file name have support # in name, but getFileByServerRelativeUrl is old service, it may not have fully adjusted to suit the latest naming rules. You can provide an feature request in UserVocie and wait the Product Group handle it later. Sorry for any inconvenience.

**Comment by jpalo** [comment]
Added it in UserVoice at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/35586262-getfilebyserverrelativeurl-with-in-file-name.

**Comment by jxnx888** [comment]
Hi @jpalo  If it is possible, could you please give me a full sample code in order to reproduce your issue?

**Comment by jpalo** [comment]
Can confirm @gautamdsheth solution works great, thank you.
