### ISSUE TITLE
Missing infomation about deleting

### ISSUE THREAD

**Issue by SvenJedeck** [SharePoint/sp-dev-docs#2631]
Hi, 
I think the information about kind of deleting is missing. 
Is it a permanent delete or are the lists in recycle bin ?
Regards - Sven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266835c-a885-dd32-3b74-b655576e92d8
* Version Independent ID: ea136a91-6225-547e-5c8c-19aa47eb7515
* Content: [SPList.Delete Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.splist.delete?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPList.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPList.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by Seiyasu** [comment]
It is a permanent delete. Due to use can use a temp list to test it, so the information is optional.

**Comment by SvenJedeck** [comment]
Honestly ? 
Yor prefer to let the people doing a test deleting instead of write three words ?? 
Wow, that's what I would call client-friendly...
