### ISSUE TITLE
Web part: Firefox and IE cause errors with sp-pages-assembly in Standard release tenant

### ISSUE THREAD

**Issue by mcraiha** [SharePoint/sp-dev-docs#2633]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web part should work both in Targeted release and Standard release tenants. 

#### Observed Behavior

Web part works correctly in Targeted release tenant with Chrome, IE and Firefox, but in Standard release tenant it does not work with Firefox/IE. Also works correctly with **gulp serve**

Following error comes from Firefox

> Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20o%20is%20undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:9439
> r
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:9439
> o
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:60742
> o
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:60462
> i
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:60872
> instantiateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:49354
> _reconcilerInstantiateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:46760
> mountChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:46964
> _createInitialChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:19480
> mountComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:17694
> mountComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:33126
> updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:49643
> _reconcilerUpdateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:46864
> _updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:47610
> updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:47508
> _updateDOMChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:21901
> updateComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:20078
> receiveComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:19631
> receiveComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:33520
> updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:49524
> _reconcilerUpdateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:46864
> _updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:47610
> updateChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:47508
> _updateDOMChildren
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:21901
> updateComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:20078
> receiveComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:19631
> receiveComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:33520
> _updateRenderedComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:57221
> _performComponentUpdate
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:56975
> updateComponent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:56253
> performUpdateIfNecessary
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:55586
> performUpdateIfNecessary
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:33702
> s
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:30138
> perform
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:35382
> perform
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:35382
> perform
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:31281
> k
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:31458
> k self-hosted:986:17 closeAll
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:35964
> perform
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:35462
> batchedUpdates
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:68041
> i
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:662:29725
> dispatchEvent
> https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-09-07.021/sp-pages-assembly_fi-fi_799f646acf1a3e2ba4db23330fa6b9c7.js:676:69379
> dispatchEvent self-hosted:1030:17 

#### Steps to Reproduce

Issue might be related to logic that adds event listener
`document.addEventListener("mousedown", this.handleClick, false)`
and removes it with
`document.removeEventListener("mousedown", this.handleClick, false)`

**Comment by vmiy** [comment]
Are you building a HelloWorld webpart project? 
Could you provide your sample code?

**Comment by vmiy** [comment]
Are you building a HelloWorld webpart project?
Could you provide your project sample code?
Where are you hosting your webpart? Localhost or SharePoint Online?

**Comment by mcraiha** [comment]
Unfortunately I do not work with that project anymore. So I cannot provide the project source code nor .sppkg package. Non-working version was in SharePoint Online on a tenant that was in standard release track.

**Comment by VesaJuvonen** [comment]
As we cannot access the non-working version of the code, there's really no way we can proceed with this, so closing.
