### ISSUE TITLE
Additional scrollbar appears when using MSGraphClient

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/sp-dev-docs#2635]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Using MSGraphClient to request purely data should not alter the view.

#### Observed Behavior

A second scroll bar is being added to the page

![image](https://user-images.githubusercontent.com/10858619/46024694-56a3f780-c0b5-11e8-8ee8-483887b53983.png)

Upon investigation there is an adal related iframe causing this to appear if the browser does not have a token to provide (i.e. first load/cache reset)

`<iframe id="adalRenewFramehttps://graph.microsoft.com" aria-hidden="true" sandbox="allow-same-origin allow-scripts allow-forms allow-pointer-lock"............`

The iframe is set with visibility hidden, when I temporarily set this to display: none the scrollbar disappears

#### Steps to Reproduce

Within chrome clear the application cache, and include an SPFX extension or webpart that utilizes the MSGraphClient

```
import { override } from '@microsoft/decorators';
import { BaseApplicationCustomizer } from '@microsoft/sp-application-base';
export default class Header extends BaseApplicationCustomizer<any> {
  @override
  public async onInit(): Promise<void> {
    await super.onInit();
    const extensionsDataResult = (await this.context.msGraphClientFactory.getClient()).api('/me/extensions').get();
  }
}
```

**Comment by 2toLeadMike** [comment]
Note that this may be a duplicate of #1514 but I am unable to determine this without more information

**Comment by patmill** [comment]
@lahuey - any ideas?

**Comment by OliverZeiser** [comment]
The issue is related to the user agent stylesheet of chrome. It applies the following style to all iframes: `border-width: 2px;`
If SPFx would add `border:0;` to the inline style of the adal iframes, things should be good.

**Comment by lahuey** [comment]
Are you still seeing this issue? I believe we fixed this issue in the past @2toLeadMike  @OliverZeiser

**Comment by 2toLeadMike** [comment]
@lahuey No longer an issue! Thanks
