### ISSUE TITLE
Highlighted Content Web Part: Filter by Managed Property is broken

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2636]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In the Highlighted Content Web Part you can select 'Filter by Managed Property', select the property's name and filter content by it.
#### Observed Behavior

Managed properties list is empty.

Most probably, it is related to the changes in Search APIs.
The post request:
<img width="789" alt="screen shot 2018-09-25 at 9 23 25 am" src="https://user-images.githubusercontent.com/17036219/46028156-af1ec900-c0a4-11e8-86b5-2acd314b37d5.png">
doesn't return results anymore.

#### Steps to Reproduce

1. Add Highlighted Content Web Part to the page
2. In 'Filter and Sort' section select "Managed Property'
3. **The list of managed properties is empty and disabled**
4. Try to enter 'ows' in 'Find a managed property'
5. **The list is still empty and disabled**

**Comment by Seiyasu** [comment]
As this is out-of-the-box functionality, we can't route this through the dev process. Please submit this through the SharePoint Online admin support channels from the tenant admin tool. We can only support dev topics through this issue list. Sorry for the inconvenience.

**Comment by AJIXuMuK** [comment]
Why is it not a dev topic? The issue here is obviously related to some changes made in search functionality. Search is not dev topic?

**Comment by AJIXuMuK** [comment]
BTW, I checked on 3 different tenants - and can reproduce the issue on all of them.
