### ISSUE TITLE
Indented SASS syntax (`.sass` vs. `scss`)

### ISSUE THREAD

**Issue by jareha** [SharePoint/sp-dev-docs#2637]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
My team intends to use [indented SASS syntax](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax_selection) instead of bracketed syntax.

Our expectation was that naming files `.sass` instead of `.scss` would allow for this functionality, but we have found that when we do name files `.sass`, our builds fail.

**Comment by jareha** [comment]
Is it possible, then, to use a different preprocesser with SPFx? Thanks for the quick—and detailed!—response.

**Comment by StfBauer** [comment]
There is no supported other pre-processor in SPFx available. Sorry.

The SASS/CSS configuration is currently set up to support a special component approach to make all style of a web part unique to the web part. So the web part styles do not bleed to the rest of the page. and stay in context of the component.

May I ask you what your concerns against SASS and the SCSS Syntax are?

**Comment by jareha** [comment]
It is our team’s code style standard for all other projects (up to this point, all non-SharePoint) within our company to use indented syntax. As we bring devs. from these other projects on to our SharePoint project—we’re ramping up—our intention is to keep these standards in place, as best we can.

**Comment by aminimalanimal** [comment]
Hi @StfBauer. Thanks for your help so far.

> SPFx uses a preprocessing library named libsass. This library is written in C++ and is better optimised for performance.
> This library does not support the indent based syntax because of its rare use.

It looks like libsass does support the indentation-based syntax, by parsing it with [sass2scss](https://github.com/mgreter/sass2scss) first. sass2scss's intro says that it's been included in libsass since version 2. I checked to make sure it's still in the current version here: [libsass v3.5.4](https://github.com/sass/libsass/tree/3.5.4) and it looks like it is.

**Comment by aminimalanimal** [comment]
`@microsoft/gulp-core-build-sass` sets `sassMatch` to only look for sass files with the `src/**/*.scss` glob by default. It's readme confirms this, and also notes that it's a configurable option. However, `@microsoft/sp-build-web` doesn't set it to anything different, and doesn't seem to offer this configuration option to the end user.

I changed this to `src/**/*.sass` locally, reran the build, and it worked. It looks like the only change needed to support the indented syntax is to add the `.sass` extension to `@microsoft/gulp-core-build-sass`.

**Comment by StfBauer** [comment]
> It looks like libsass does support the indentation-based syntax, by parsing it with sass2scss first. sass2scss's intro says that it's been included in libsass since version 2. I checked to make sure it's still in the current version here: libsass v3.5.4 and it looks like it is.

@aminimalanimal Nice finding wasn't aware of that or haven't found it when I was looking it up.
Nice finding in the ```gulp-core-build-sass``` too.

The problem when you change the internal gulp task is that you have to do it for every project and won't be able to update to a newer version without modifying this gulp task again.

Probably the fastest way to get this running as a feature request is to open a new issue an file it as a bug and describe your scenario.

**Comment by jareha** [comment]
As referenced above, I’ve created https://github.com/Microsoft/web-build-tools/pull/852 to address the issue of indented SASS not working as expected. That pull request now awaits review.

**Comment by VesaJuvonen** [comment]
Closing this one for now as we cannot fix this in our side due the dependency on the web-build-tools.
