### ISSUE TITLE
When should we start using AADHttp client in production? any eta?

### ISSUE THREAD

**Issue by NewJ123** [SharePoint/sp-dev-docs#2638]
When should we start using AADHttp client in production? any eta?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mmsharepoint** [comment]
This is GA since start of September (3rd?). In the beginning there were some issues but they should be fixed now #2473 #2472 
Nevertheless I face one like #1477 and try to narrow it down right now.

**Comment by VesaJuvonen** [comment]
Documentation has been updated. It's ready for production usage.
