### ISSUE TITLE
TS errors while trying to build solution from within VS Ctrl+shift+b

### ISSUE THREAD

**Issue by HeToC** [SharePoint/sp-dev-docs#264]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Observed Behavior

I'm using the guide https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/use-visual-studio 
to import generated solution (react) with visual studio
and i've got problems on the step 'Build and debug the project
i'm pressing F5 and VS asks me to rebuild project... ok and then i've got dozens of TS2300 Error messages in the Error List window.
I've tried to exclude all typings from vs solution but it does not helps

**Comment by johnje** [comment]
I'm having the same TS-error issue. At first I had 1910 errors, after switching my environment from using TypeScript 1.4 to 1.8, I'm down to only 292 errors. My environment, or at least the parts I think matter:
VS Enterprise 14.0.25431.01 Update 3
Office Dev Tools 14.0.23928
TypeScript 1.8.36.0

On the good side, in PS I can kick off 'gulp serve' and everything seems to run just fine.

**Comment by johnje** [comment]
Following up... I just updated to TypeScript 2.0.6.0 and my compile errors went away. Thanks to the wiki, and sorry for those of us who fail to read them.
HeToC, you might wanna take a peek at the latest wiki (https://github.com/SharePoint/sp-dev-docs/wiki) and make sure you're up to date on everything. Hopefully will fix your problems too!

**Comment by mpasarin** [comment]
As there's been no news since Nov 2016, I guess that's already solved, just updating the TypeScript version. Closing the issue.
