### ISSUE TITLE
SPFX ListView Extension should also work in the list(preview) webpart

### ISSUE THREAD

**Issue by ashu57** [SharePoint/sp-dev-docs#2641]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Expected or Desired Behavior
When adding the "List (preview)" webpart to a modern page, i expect that ListView Extension do also work in this webpart.

Observed Behavior
ListView Extension do not work in a "List (preview)" webpart, while they work as expected in the list view.

Steps to Reproduce
Create a ListView Extension and add it to a list. The extension command should work as expected in the normal list view. Add a "List (preview)" webpart to a modern page and select the list with the ListView Extension. When rendering the webpart, the ListView Extension does not work.

I don't see any work around or way to get it working with spfx

Thanks, Cheers

**Comment by Seiyasu** [comment]
1. No official docs state List webpart support the SPFx ListView Extension.
2. The List webpart is preview, still in developing, so no-support to ListView extension is normal now. You can submit feature request in the UserVoice.

**Comment by ashu57** [comment]
Thanks, i created voice for support of the list view extension in the List(preview) web part.
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/35656771-spfx-listview-extension-should-also-work-in-the-li
