### ISSUE TITLE
App Package isn't detected correctly when uploaded to App Catalog

### ISSUE THREAD

**Issue by PzYon** [SharePoint/sp-dev-docs#2642]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I upload an `.spkkg` to the App Catalog. I expect the Title, App Version, etc. to be displayed and the status of the app to be "Deployed".

#### Observed Behavior

![image](https://user-images.githubusercontent.com/9199378/46076508-02207b00-c18e-11e8-9e12-b2c267f8ec21.png)

The second line is good, everything is detected, etc. This is with a simple app that requests no permissions, etc. 

However the first row is not good. Seems like that specific package cannot be parsed. And the status is not "Deployed". However I do not get any error message or additional information.

#### Additional Information

- I can't say, since when it happens - as today is the first time I deployed the app since a couple of days.
- However I can say that 
  - this behavior occurs on **different, new** (demo) tenants...
  - ...with the **exact same app package** that used to work a couple of days.
- Updating the app on a tenant where it is already deployed doesn't work either.
- So something must have changed, but I can't figure out, what it is.
- I created a new app using the newest yo generator, and that one works too.

#### AppManifest.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" Name="XXX" ProductID="416b9b7c-5b8d-417b-ac86-0ae6a9cf43d5" Version="3.0.2.0" SharePointMinVersion="16.0.0.0" IsClientSideSolution="true">
  <Properties>
    <Title>XXX</Title>
  </Properties>
  <WebApiPermissionRequests>
    <WebApiPermissionRequest ResourceId="Microsoft Graph" Scope="People.Read"/>
    <WebApiPermissionRequest ResourceId="Microsoft Graph" Scope="Mail.Read"/>
    <WebApiPermissionRequest ResourceId="Microsoft Graph" Scope="Calendars.Read"/>
    <WebApiPermissionRequest ResourceId="Microsoft Graph" Scope="Sites.Read.All"/>
    <WebApiPermissionRequest ResourceId="Microsoft Graph" Scope="Group.Read.All"/>
    <WebApiPermissionRequest ResourceId="XXX" Scope="user_impersonation"/>
    <WebApiPermissionRequest ResourceId="Office 365 Exchange Online" Scope="Tasks.Read"/>
  </WebApiPermissionRequests>
</App>
```

**Comment by PzYon** [comment]
In the meanwhile I found out that it is related to this `WebApiPermissionRequest`:
```<WebApiPermissionRequest ResourceId="Office 365 Exchange Online" Scope="Tasks.Read"/>```

If I remove that, then the app can successfully be added/updated again. This used to work however.

**Comment by PzYon** [comment]
Next update: The `WebApiPermissionRequest` added thanks to #2473 breaks the app too:
`<WebApiPermissionRequest ResourceId="Windows Azure Active Directory" Scope="User.Read"/>`

In other words, I see it as follows: Any entry in the `AppManifest.xml` that for some reason is not valid (or supported, or what ever this means), leads to the app in general being invalid.

Is this correct? But something must have changed on SharePoint side, as the exact same app (with the above two mentioned permission requests) was still valid as of last week.

**Comment by araneus-pl** [comment]
We are experiencing the same issue in our 4 tenants. It affects both standard and targeted release tenants.

**Comment by PzYon** [comment]
Might not be a duplicate of #2624 but is going in the same direction. However, there the length of `WebApiPermissionRequest` seems to be the problem. And in my case here it stopped working, without any changes in the manifest.

**Comment by PzYon** [comment]
I'm closing this issue, as it's the same problem as in #2624. In other words, it's not the specific scopes that matter, but instead the length of the `WebApiPermissionScopes`-field.
