### ISSUE TITLE
Flicker Issue when loading Branding Artifacts (css, js etc.) using SPFx Extension in Modern SharePoint Site

### ISSUE THREAD

**Issue by nipuneth** [SharePoint/sp-dev-docs#2645]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Observed Behavior

Need help for the following scenario wherein any modern page that gets displayed shows a flicker of the default SharePoint page for 1-2 seconds before the actual page with branding is displayed. 
 
Details:
We are facing an issue regarding the user experience in SharePoint Modern sites. For Branding, we have used SPFx Application customizer aka extensions to inject custom styles. With this implementation, we are facing a flicker because extension takes fractions of seconds to load itself. In the meantime, OOB page appears first and then extension starts loading.
 
Is there any way to load SPFx extension before SharePoint page starts loading? Or any way to inject custom styles on modern pages without SPFx extension?

**Comment by Seiyasu** [comment]
> Is there any way to load SPFx extension before SharePoint page starts loading? 
 No.
> Or any way to inject custom styles on modern pages without SPFx extension?
No, there's no way to do this on SPO modern experience other than creating SharePoint framework solutions 
With SharePoint, you should always colour within the lines. Don’t do anything that isn’t supported, ever. If you do, and you run into issues, you’re on your own.
