### ISSUE TITLE
Required option in addSPLookupFieldXml/ CAML bloc does not work. 

### ISSUE THREAD

**Issue by umaknow-alain** [SharePoint/sp-dev-docs#2646]
Hi i have tried many ways to add the required option for the column but nothing seems to be working. i have tried adding the IsRequired option  like this 
schemaXml": "&lt;Field Type=\"Lookup\" DisplayName=\"Customer\" Required=\"TRUE\" ShowField=\"Title\" Name =\"CreaOppClient\"/&gt;",
            "addToDefaultView": true,
            "isRequired": true,
            "verb": "addSPLookupFieldXml",
            "targetListName":"Custom Library"

But that did not work, I delete the entire column and recreate, not working either. Any help would be appreciate.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by narulasrinivas** [comment]
@umaknow-alain -

Do you get this issue while creating site from new site design or when you use an update site design?

Please share the scripts. I'll try to run in my Dev tenant.

**Comment by umaknow-alain** [comment]
It was an update site design. When we were trying to invoke the site design via powershell, the required filed was never updated. I finally decided to delete the list and recreate it, then required icon appear. Also one thing important to mention is that when you are using the verb addSPLookupFieldXml, only the caml bloc is taken in consideration.

Thanks you can close the case.
