### ISSUE TITLE
Not able to get expiry date using powershell script

### ISSUE THREAD

**Issue by rajendrasingh2121** [SharePoint/sp-dev-docs#2650]
$date = get-date 
it return the current date of system not the expiry date in the Find out the expiration dates of the SharePoint Add-ins installed to the Office 365 tenancy section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by paulewert** [comment]
I use the following to get the start date and end (expiration) date of the app secrets. The code above should be corrected.

$applist = Get-MsolServicePrincipal -all  |Where-Object -FilterScript { ($_.DisplayName -notlike "*Microsoft*") -and ($_.DisplayName -notlike "autohost*") -and  ($_.ServicePrincipalNames -notlike "*localhost*") }

foreach ($appentry in $applist) {
    $principalId = $appentry.AppPrincipalId
    $principalName = $appentry.DisplayName
    
    Get-MsolServicePrincipalCredential -AppPrincipalId $principalId -ReturnKeyValues $false | ? { $_.Type -eq "Password" } | % { "$principalName;$principalId;" + $_.KeyId.ToString() +";" + $_.StartDate.ToString() + ";" + $_.EndDate.ToString() } | out-file -FilePath c:\temp\appsec.txt -append
}

**Comment by jxnx888** [comment]
Hi @rajendrasingh2121 , Could you please provide a sample scenario? How did you occur this issue?

**Comment by rajendrasingh2121** [comment]
I ran below command in  


$applist = Get-MsolServicePrincipal -all  |Where-Object -FilterScript { ($_.DisplayName -notlike "*Microsoft*") -and ($_.DisplayName -notlike "autohost*") -and  ($_.ServicePrincipalNames -notlike "*localhost*") }

foreach ($appentry in $applist)
{
   $principalId = $appentry.AppPrincipalId
   $principalName = $appentry.DisplayName

   Get-MsolServicePrincipalCredential -AppPrincipalId $principalId -ReturnKeyValues $false | Where-Object { ($_.Type -ne "Other") -and ($_.Type -ne "Asymmetric") }

   **$date = get-date**
   Write-Host "$principalName;$principalId;$appentry.KeyId;$appentry.type;$date;$appentry.Usage"

}  > c:\temp\appsec.txt

here you can see  $date = get-date will always return the same date.
[https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in#find-out-the-expiration-dates-of-the-sharepoint-add-ins-installed-to-the-office-365-tenancy](url)

So it would be great if anyone can update the powershell command

**Comment by VesaJuvonen** [comment]
Documentation updated based on PR from @paulewert in #2826. Thanks, everyone for your contribution.
