### ISSUE TITLE
"Copy Link" does not work in libraries with more than 30 documents

### ISSUE THREAD

**Issue by despingu** [SharePoint/sp-dev-docs#2653]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When selecting "copy link" the link should be copied to clipboard by hitting ctrl + c, click "copy" or automatically

#### Observed Behavior

In a library with multiple subfolders and 50+ items in one of these folders a strange behavior occurs when trying to use the copy link functionality.

For document 1-~30 it works just fine. If we try to copy the link of the 31st item, it shortly shows the expected dialog, but then refreshes the list items, resulting in a deselection of the item and closing of the "copy link" dialog.

#### Steps to Reproduce

Create a library, add ~50 items 
Try to copy the link of an item beyond number 30 with a user who has full control. Contribute might also be sufficient. You need to be able to set permissions to the item.

**Comment by Seiyasu** [comment]
As this is out-of-the-box functionality, we can't route this through the dev process. Please submit this through the SharePoint Online admin support channels from the tenant admin tool. We can only support dev topics through this issue list. Sorry for the inconvenience.
