### ISSUE TITLE
Is it possible to get the list of people following sharepoint site

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-docs#2654]
Hi All, 

**/_api/social.following** will give following status of people(document/person). But is there any way to get the list of people following SharePoint site?

Thanks & Regards, 
Pavan.

**Comment by KingKangMSFT** [comment]
Could you please provide more information about your issue, such as the project configuration? Did you use the sharepoint Framework or Sharepoint Add-ins?

**Comment by pavan2920** [comment]
Hi @KingKangMSFT 

Yes its SharePoint Framework with React. 

Thanks & Regards, 
Pavan.
