### ISSUE TITLE
RenderListDataAsStream Not Working with Workflow Tasks List

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2655]
When we try to use the RenderListDataAsStream with WorkFlow Tasks List we get the error
"You can only query for the HierarchyQueryInterface after hierarchy has been reserved"

**Comment by Seiyasu** [comment]
What is your key code and config? The RenderListDataAsStream should works well.

My worked code:
//   const listId = this.context.pageContext.list.id;
//const itemId = this.context.pageContext.listItem.id;
//const restAPI = `${this.context.pageContext.web.absoluteUrl}/_api/web/Lists(guid'${listId}')/RenderListDataAsStream`;

    const listId = "my Task lit guid";
const itemId = 2;
const restAPI = `${this.context.pageContext.web.absoluteUrl}/_api/web/Lists('${listId}')/RenderListDataAsStream`;
this.context.spHttpClient.post(restAPI, SPHttpClient.configurations.v1, {
  body: JSON.stringify({
    parameters: {
      RenderOptions: 2,
      ViewXml: `<View>
                  <ViewFields>
                    <FieldRef Name="ValoNavigation"/>
                  </ViewFields>
                  <Query>
                    <Where>
                      <Eq>
                        <FieldRef Name="ID"/>
                        <Value Type="Number">${itemId}</Value>
                      </Eq>
                    </Where>
                  </Query>
                  <RowLimit Paged="TRUE">1</RowLimit>
                </View>`
    }
  })
})
.then((data: SPHttpClientResponse) => data.json())
.then((data: any) => {
  if (data && data.Row && data.Row.length > 0) {
    // Start writing your code here
     this.domElement.innerHTML = `
      <div>${data.Row[0]["FSObjType"}
               
        
      </div>`;
  }
});

**Comment by nikolayyordanov** [comment]
Thanks. This worked. May be the ViewFields is a requirement. Without it we got the error I have mentions.
