### ISSUE TITLE
error in getQueryStringParameter

### ISSUE THREAD

**Issue by FranckGarcia** [SharePoint/sp-dev-docs#2656]
I get an error with the provided code, the hostWebContext is empty. That meant that the computed hostWebURL was wrong. I have checked the URL called by the add-in and there is no "\&amp;" separator, just "&". Replacing "\&amp;" by "&" in the getQueryStringParameter function did solve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e361acb6-1eef-2a78-3a51-3dff82b7a239
* Version Independent ID: 4d7e6841-8a09-2ece-76fe-7edf901d15c9
* Content: [Work with host web data from JavaScript in the add-in web](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web)
* Content Source: [docs/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Could you please modify your description, `I have checked the URL called by the add-in and there is no "&" separator, just "&". Replacing "&" by "&" in the getQueryStringParameter function did solve the issue.` I think the second `&` should change by other character

**Comment by FranckGarcia** [comment]
> Could you please modify your description, `I have checked the URL called by the add-in and there is no "&" separator, just "&". Replacing "&" by "&" in the getQueryStringParameter function did solve the issue.` I think the second `&` should change by other character

>> The 2 characters were different but were looking identical. Adding a backslash before "\&amp;" has fixed the issue. Without a backslash, "\&amp;" is displayed as "&".

**Comment by andrewconnell** [comment]
I believe the code in the doc was updated... correct? If not, can you clarify where you had to make a fix so we can get it updated?

**Comment by FranckGarcia** [comment]
I can still see \&amp; in the first line of the function getQueryStringParameter(paramToRetrieve): 
 var params = document.URL.split("?")[1].split("\&amp;");

the right formula should be:
 var params = document.URL.split("?")[1].split("&");

**Comment by andrewconnell** [comment]
Yup... we'll get this fixed. Doc bug...
