### ISSUE TITLE
Cannot reference @microsoft/sp-http outside SPFx project - @ms/sp-client-shared etc not found

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#2661]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Referencing `@microsoft/sp-http` should be possible outside the "main" SPFx package. This would be useful in large projects when creating a "service" layer package which uses the SPFx context classes.

#### Observed Behavior

When referencing SPFx packages (`@microsoft/sp-...`) outside the main SPFx package an exception is thrown by webpack:

> C:/Projects/wod-inside-modern/inside-js/common/temp/node_modules/@microsoft/sp-http/lib/oauthTokenProvider/OAuthTokenProvider.js
> Module not found: Error: Can't resolve '@ms/sp-client-shared' in 'C:\Projects\wod-inside-modern\inside-js\common\temp\node_modules\@microsoft\sp-http\lib\oauthTokenProvider'
> resolve '@ms/sp-client-shared' in 'C:\Projects\wod-inside-modern\inside-js\common\temp\node_modules\@microsoft\sp-http\lib\oauthTokenProvider'
>   Parsed request is a module
>   using description file: C:\Projects\wod-inside-modern\inside-js\common\temp\node_modules\@microsoft\sp-http\package.json (relative path: ./lib/oauthTokenProvider)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: C:\Projects\wod-inside-modern\inside-js\common\temp\node_modules\@microsoft\sp-http\package.json (relative path: ./lib/oauthTokenProvider)
>     resolve as module

Declaring `@microsoft/sp-http` etc as external in webpack.config.js for the _service_ package made the build succeed, but results in browser exceptions when loading the webpart.

#### Steps to Reproduce

- Create a separate node project which references `@microsoft/sp-http`
- Import an object - for example `import { SPHttpClient } from "@microsoft/sp-http";` 
- Try to bundle the project

#### Additional Information
For building an bundling my separate project, I use `@microsoft/gulp-core-build`, `@microsoft/gulp-core-build-typescript` and `@microsoft/gulp-core-build-webpack` - with the same versions as `sp-build-web`.

If needed I'm able to provide a sample project.

**Comment by patmill** [comment]
Right - sp-http is really part of the SPFX framework, and won't work as a stand-alone package at the moment.

For feature requests, uservoice is the best place to ask for this.

**Comment by NickSevens** [comment]
@patmill I don’t mean to use sp-http in a completely stand-alone package. What I’m trying to do is use sp-http classes (HttpClient etc) in a package which is referenced in my SPFx project; more as a reusable service layer for multiple SPFx projects.

**Comment by patmill** [comment]
I see.  Your best bet would likely be to include the other SPFX components as well (at least sp-core-library, maybe sp-application-base but I don't think so)

**Comment by NickSevens** [comment]
@patmill this doesn't work either. The error messages stay the same.
the issue seems related or the same as https://github.com/SharePoint/sp-dev-docs/issues/1292 which doesn't seem to have a fix yet either?

**Comment by wictorwilen** [comment]
We import the '`SPHttpClient` and other SPFx classes in our custom npm projects, which works flawlessly.
Here's an example of one solution and the package.json:
```
"@microsoft/decorators": "^1.6.0",
"@microsoft/sp-application-base": "^1.6.0",
"@microsoft/sp-webpart-base": "^1.6.0",
```
We do not however use any of the SPFx Gulp build tasks, but rather use standard Webpack with the `@microsoft/*` libraries marked as external

**Comment by NickSevens** [comment]
Hi @wictorwilen thanks for the update. Could you share your externals config perhaps?
Or is it simply
```
externals: [
  "@microsoft/sp-http",
  "@microsoft/sp-application-base"
  "..."
]
```
?

Thank you.

**Comment by wictorwilen** [comment]
Exactly.
this is from the same solution:
```
externals: [
    "@microsoft/sp-core-library",
    "@microsoft/sp-loader",
    "@microsoft/sp-webpart-base",
    "@microsoft/sp-page-context",
    "@microsoft/sp-http"
  ]
```
You're milage may vary, depending on how you use it. Some modules are imported by others, and some only contains or your solution might only use interface definitions in them.

**Comment by NickSevens** [comment]
Great, this works like a charm :)
I previously tried putting the "missing" @ms/client-shared in externals but that didn't help, so I kinda forfeited that path :)
Thanks for the help!
