### ISSUE TITLE
SPFx Installation Preparation and Instructions

### ISSUE THREAD

**Issue by Dodge1350** [SharePoint/sp-dev-docs#2665]
Three very large issues with this documentation:

1.  The documentation here does not match the corresponding video.  There is documentation on this page that is not addressed in the video (ubunto or fedora compilers) and is not identified as to why it would even be necessary.  Can you provide a step by step well documented routine for a Windows 10 environment that end users could perform without fail?

2.  The installation video does not go so far as to creating an actual 'Hello World' web part or extension.  Instead, the videographer states that the next video in this sequence will be devoted to that effort.  Problem is, no reference to the next video is provided.  The end user is left to search around all the videos on the SharePoint framework site to try to find the next video. Since the end user never actually sees this setup in a successful debugging operation, there is no guarantee that this setup routine actually works as intended.  Without that evidence, it is up to the end user to take the leap of faith and proceed on to the next undocumented video.  Please provide the link to the next video to get the whole thing functional and in a debug state for a 'Hello World' type solution. 

3.  What sort of issues can an end user expect from a failed installation of all these third party tools?  What steps should be taken in the event that a failure does occur?  Where does an end user go to get a list of errors and resulting solutions that will get them back on track?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
For your question:
1. The docs should ok, if you want to any improvement, you can send the feedback. If the recommendations are valuable and some one from content team or from community will follow up it. 

2. Current docs is just for setup env. Helloworld demo is in the following topic: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part. 

3. 3rd tool installation issue need to ask on the corresponding forum but not here. Here is for SharePoint dev issue.
