### ISSUE TITLE
Additional instructions for SPServiceInstance.Provision Method

### ISSUE THREAD

**Issue by lindalu-MSFT** [SharePoint/sp-dev-docs#2674]
Note: You should run this command only from the server on which you would like to Provision the service instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c916bf49-bbb1-8afe-9769-7e75dc159d5c
* Version Independent ID: b9c88795-4fc0-0725-a728-0292046a0647
* Content: [SPServiceInstance.Provision Method (Microsoft.SharePoint.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.spserviceinstance.provision?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_Administration_SPServiceInstance_Provision)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Administration/SPServiceInstance.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Administration/SPServiceInstance.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by thechriskent** [comment]
Good note, but closing as an issue. Thanks!
