### ISSUE TITLE
Additional instructions for SPWebServiceInstance.Provision Method

### ISSUE THREAD

**Issue by lindalu-MSFT** [SharePoint/sp-dev-docs#2676]
Note: You should run this command only from the server on which you would like to Provision the service instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1209f814-bddd-3af9-2af8-0e0dbb7448c8
* Version Independent ID: b1084dd1-65b1-62fc-4467-d2d3dc40ecf7
* Content: [SPWebServiceInstance.Provision Method (Microsoft.SharePoint.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.spwebserviceinstance.provision?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_Administration_SPWebServiceInstance_Provision)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Administration/SPWebServiceInstance.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Administration/SPWebServiceInstance.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by thechriskent** [comment]
Good note, but closing as an issue. Thanks!
