### ISSUE TITLE
Additional instructions for SPWebServiceInstance.Unprovision Method

### ISSUE THREAD

**Issue by lindalu-MSFT** [SharePoint/sp-dev-docs#2677]
“Note: You should run this command only from the server on which you would like to unprovision the service instance.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650e5c8b-80db-e956-4bc8-bc9a82667a61
* Version Independent ID: 539b373e-93a4-3c0f-2a00-66463a2cdd9c
* Content: [SPWebServiceInstance.Unprovision Method (Microsoft.SharePoint.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.spwebserviceinstance.unprovision?redirectedfrom=MSDN&view=sharepoint-server#feedback)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Administration/SPWebServiceInstance.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Administration/SPWebServiceInstance.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by thechriskent** [comment]
Good note, but closing as an issue. Thanks!
