### ISSUE TITLE
[LOC] Invalid links in an article (tenant-properties.md)

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#2678]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties (or GH https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tenant-properties.md)
2. Search for links listed below, e.g. _spo storageentity remove_ (https://sharepoint.github.io/office365-cli/cmd/spo/storageentity/storageentity-remove/?utm_source=msft_docs&amp;utm_medium=page&amp;utm_campaign=Use+SharePoint+Online+tenant+properties)
3. Click the links --> 404 error page

**List of broken links:**

LinkText | Link URL
-- | --
spo   storageentity remove | https://sharepoint.github.io/office365-cli/cmd/spo/storageentity/storageentity-remove/?utm_source=msft_docs&amp;utm_medium=page&amp;utm_campaign=Use+SharePoint+Online+tenant+properties
spo   storageentity list | https://sharepoint.github.io/office365-cli/cmd/spo/storageentity/storageentity-list/?utm_source=msft_docs&amp;utm_medium=page&amp;utm_campaign=Use+SharePoint+Online+tenant+properties
spo   storageentity set | https://sharepoint.github.io/office365-cli/cmd/spo/storageentity/storageentity-set/?utm_source=msft_docs&amp;utm_medium=page&amp;utm_campaign=Use+SharePoint+Online+tenant+properties
spo   storageentity get | https://sharepoint.github.io/office365-cli/cmd/spo/storageentity/storageentity-get/?utm_source=msft_docs&amp;utm_medium=page&amp;utm_campaign=Use+SharePoint+Online+tenant+properties

**Comment by thechriskent** [comment]
Thanks for catching this! Looks like the move from the SharePoint org to the PnP org within GitHub broke links to individual pages. I've submitted a fix for this article. @waldekmastykarz this might be a larger issue with other articles.

**Comment by waldekmastykarz** [comment]
Good call @thechriskent. Let's see if we can spot any other broken links pointing to the old CLI docs.
