### ISSUE TITLE
[LOC] Invalid link in an article (integrate-gulp-tasks-in-build-pipeline.md)

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#2679]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline (or GH https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md)
2. Search for "_build.subTask_" link text (https://github.com/Microsoft/gulp-core-build#defining-a-custom-task)
3. Click the link --> 404 error page

![image](https://user-images.githubusercontent.com/16706698/46354316-9a22d680-c65e-11e8-9767-36370b6b95e1.png)

**Comment by thechriskent** [comment]
Good catch, thanks! I've submitted a change.
