### ISSUE TITLE
Update .vscode/settings.json to always point to local typescript instance installed with the project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#268]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Given that SPFx project has its own version of TypeScript installed, it would be better if the .vscode/settings.json file contained a reference to it by default.

#### Observed Behavior
When opening Visual Studio Code developer is prompted about the difference in version of TypeScript provided with VSCode and used by the project.

#### Steps to Reproduce
- create new SPFx project
- open project in VSCode

**Comment by patmill** [comment]
@nickpape-msft  - Is this something you can handle?

**Comment by nickpape-msft** [comment]
We added a reference to the version of Typescript at the root of the node_modules folder. This will be included in the next release.
