### ISSUE TITLE
Unable to save Web Part on Page when Fabric DetailsList control is present in Web Part

### ISSUE THREAD

**Issue by MaartenSundman** [SharePoint/sp-dev-docs#2682]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'd like my web part to save :(

#### Observed Behavior

When using a web part with a DetailsList fabric control on it, the web part works while editing the page. But does not save. So after publishing and refreshing the page, the web part is gone. Additionally, when the DetailsList control is present, the ECB menu for the web part to edit web part properties also does not work. However, manually opening the web part property pane via this.context.propertyPane.open() does work. Of course, no web part properties are saved.

#### Steps to Reproduce

Create a new SPFX WebPart Project using React
Add a DetailsList to the render method of the web part
Preview in Workbench to verify web part looks how you expect
Deploy to SharePoint Online
Add web part to a page - it will look like its working here
Use the pencil to try and edit the web part - nothing happens
Publish page
Refresh the page - web part disappears!

Here is a SPFX 1.6 web part demonstrating the issue with the detailslist control, and it fetches items from a list/library on the current site. List is configurable from web part properties, defaults to Documents.

[listview16.zip](https://github.com/SharePoint/sp-dev-docs/files/2439732/listview16.zip)

[StackExchange - SPFX Web Part Disappears on Save](https://sharepoint.stackexchange.com/questions/250051/spfx-web-part-disappears-on-save)

#### Steps Taken to Try and Remediate
-Logging, lots of logging. After save, no console.log's are hit, even inside of BaseClientSideWebPart
-Isolated web part
-Removed all other web parts from test pages
-Removed all application extensions from test site
-Attempted to load sample web parts with details list - Save behavior observed!
--[SPFX React DetailsList Sample](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-documents-detailslist)
-Attempted to edit web part properties from the web part
-Removing DetailsList from render method allows the rest of the web part to work

**Comment by MaartenSundman** [comment]
Side note, I wrote my own detailslist control, and the web part works now. So definitely something not playing nice inside of DetailsList.

**Comment by bolyutay** [comment]
Hello! I have same problem with DetailsList. 
Is there any solution?

My package.json:
![package_json](https://user-images.githubusercontent.com/47863885/53230762-12cb1380-3690-11e9-9b62-8558f2a2a3f6.JPG)

**Comment by patmill** [comment]
Sorry - we lost track of this issue due to metadata.  Is this still a problem?  Lots of changes to a lot of this code over the past 2 years.
