### ISSUE TITLE
Custom Command Set Customizer in Document Library Web Part

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2684]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Today I found custom Command Set in Document Library Web Part.
It was displayed incorrectly - instead of title I see alias from `manifest` file.

I know that the web part in in preview and we can expect it to work incorrectly.
But I'm just letting you know and additionally asking if you have any specific thought on when and what to expect.

Thanks!

#### Steps to Reproduce

1. apply custom command set customizer to doc library
2. display doc library in Document Library Web Part.

<img width="333" alt="screen shot 2018-10-02 at 9 06 30 pm" src="https://user-images.githubusercontent.com/17036219/46389509-0fa29d00-c687-11e8-8aa6-71d2fde74659.png">

**Comment by vmiy** [comment]
Can you provide the manifest.json file and your commandset TS file sample code?

**Comment by AJIXuMuK** [comment]
OK, so here is a full picture.
Initial description was a bit incorrect: Document Library Web Part uses not alias from `manifest` but the Title of `CustomAction` from `elements.xml`.
It's easy to reproduce:
1. Scaffold OOTB Command Set with `yo @microsoft/sharepoint`
2. Add `CustomAction` declaration into `elements.xml` to display command set in Document Library:
```xml
<CustomAction
        Title="DocLibTest"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="30d0a9a4-f3a6-4aef-9954-89a9034d22f5"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
```
3. After that you'll see `DocLibTest` button in Command Bar of Doc Library Web Part.
Even more, in OOTB Command Set there are 2 commands, but only one button is added to the Command Bar.

Please, let me know if you need more details.

**Comment by VesaJuvonen** [comment]
Thx @AJIXuMuK, that's a strange implementation indeed and have been routed finally to right people. Sorry for the delay on the triage.

**Comment by AJIXuMuK** [comment]
Thanks @VesaJuvonen!

**Comment by ahackettms** [comment]
we are looking into this issue and will provide update as soon as we can. Thank you

**Comment by ahackettms** [comment]
The work to enable ListViewCommandSet in webpart is done and will be available to customer in mid-late January 2019.

**Comment by AJIXuMuK** [comment]
Will there be ability to check if the command set is displayed in web part or in regular list?
Also will there be an API to get `viewId` in the web part? Currently I can get it from qouery string and/or `pageContext`. What about web part? There could be multiple web parts on the page.

**Comment by ahackettms** [comment]
This feature should be enabled for customer now. Please give it a try. Thank you

**Comment by AJIXuMuK** [comment]
Hi @ahackettms!
Thanks for the update!
I quickly looked at the functionality and it looks like there are still issues.
For example, icon for custom command set is not displayed.
`iconImageUrl` in Command Set manifest is set to display an icon from Azure CDN. It works fine in Document library itself, but in the web part I'm getting 
```
<img src="" class="ms-Image-image ms-Image-image--contain ms-Image-image--portrait is-notLoaded is-fadeIn is-error image-666">
```
`src` is not set.

**Comment by AJIXuMuK** [comment]
When the web part is added to a small zone command part is rendered with overlap
<img width="721" alt="screen shot 2019-02-04 at 9 38 58 am" src="https://user-images.githubusercontent.com/17036219/52226091-dd858f80-2860-11e9-9463-d292e368e73a.png">

**Comment by AJIXuMuK** [comment]
And, as I previously mentioned, it looks like there is no way to get `viewId` for the web part.

**Comment by ahackettms** [comment]
@AJIXuMuK the icon issue was just fixed recently. Please allow another 1-2 weeks and try again. 
For the commandbar overlap issue in small webpart, @VesaJuvonen  could you file a new issue for us to track that? it most likely a generic commandbar issue which is not related to client-side extensions. 

For the ViewID issue, I don't think we have API supporting that. @VesaJuvonen feel free to Chime in

**Comment by vlad-nvs** [comment]
Hi. Seems issue with icons steel exists. Currently I get this in both cases: if iconImageUrl has value and whet it's empty

`<img src(unknown) class="ms-Image-image ms-Image-image--contain ms-Image-image--portrait is-notLoaded is-fadeIn is-error image-333">`

Any suggestions?

**Comment by AJIXuMuK** [comment]
Checked current behavior - seems to be fixed.
