### ISSUE TITLE
config/tslint.json should be valid tslint configuration

### ISSUE THREAD

**Issue by kmees** [SharePoint/sp-dev-docs#269]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
the provided tslint config should work with the tslint-cli / editor plugins and not only with the gulp tslint task

#### Observed Behavior
The current tslint config in (`config/tslint.json`) is not a valid tslint config because it nests the rules in an extra `lintConfig` property which makes it unusable outside of the gulp task

#### Steps to Reproduce
scaffold new project with yeoman, try to use tslint cli with the provided tslint config

**Comment by patmill** [comment]
Seems reasonable as a way to play nicely with other tools.  @nickpape-msft ?

**Comment by nickpape-msft** [comment]
The `config/tslint.json` is not the same as a typical tslint file (it has extra configuration options, as well as it may not contain the full list of active lint rules). However, in the next release of SPFx, the tools create a `temp/tslint.json` which *is* a valid tslint file that your editor can use.
