### ISSUE TITLE
SP Admins not affected by Grant-SPOSiteDesignRights

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/sp-dev-docs#2690]
It may be worthwhile to call this out. It looks like SP Admins will always be able to see all site designs within the SP UI regardlesss of Grant-SPOSiteDesignRights parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340d6888-f691-be04-6d18-61af54845564
* Version Independent ID: 81c35293-f9fa-f961-c82a-116b8a268efe
* Content: [Scoping access to SharePoint site designs](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-scoping)
* Content Source: [docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-scoping.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Nomarlly, we use admin role(executor) to run the  Grant-SPOSiteDesignRights cmdlet or the GrantSiteDesignRights REST API , so they should always have the permission. The access we grant to means the specific user/group not admin itself.
