### ISSUE TITLE
I could not run the site script for flows-formatters-pages-siteScripts

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#2695]
Hi everyone,

I try to create a team site using the provided site script 'UberSiteDesign.json' but the site script stuck on the initialising. I awaited for few minutes and it is still stick on that screen.

![site-script](https://user-images.githubusercontent.com/22563887/46478922-d92f6400-c7e5-11e8-9298-4ecf9b2f398b.png)

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expected to see the site script run successfully. 

#### Observed Behavior
I have done some testing and and i found out that if i remove some of the lines in the scripts than it successfully created. I have tested by removing some chuck from different sections. This shows that the site script has some line, or character or size limits. Can some one clarify on this?

#### Steps to Reproduce
1. Get the 'UberSiteDesign.json' from https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/flows-formatters-pages-siteScripts/site-designs.
2. $siteScript = Get-Content '[[pathToYourSiteScriptJsonFile]]' -Raw
3. $mySiteScript = Add-SPOSiteScript -Title "Classroom Site Script" -Description "Classroom Site Script" -Content $siteScript
4. Add-SPOSiteDesign -Title "Classroom site designs" -WebTemplate "64" -SiteScripts $mySiteScript -Description "classroom site design"

I hope someone could guide me on this issue.

Thank you in advanced.

**Comment by Seiyasu** [comment]
1. Open the UberSiteDesign.json from Browser or download the full solutions to get the file. Not to download it by **SaveLinkAs**. If you download it by SaveLinkAs, the content is HTML but not valid JSON.
You can create an local file named UberSiteDesign.json first. Navigate to the [UberSiteDesign](https://github.com/SharePoint/sp-dev-solutions/blob/master/solutions/flows-formatters-pages-siteScripts/site-designs/UberSiteDesign.json).json page  and click the Raw, then copy the content to local file too.
2. Then run the PowerShell Script you have provided. Then the UberSiteDesign.json works well.

**Comment by muges01** [comment]
Hi @Seiyasu,

Thank you for your reply. Just to be clear, I did download the whole solution and then point the path to the file to the location i downloaded. The only changes I made is to delete all flow section. 

I have tested without delete anything in the file but It still not working. As i mention, i have done few testing and i only manage to get this file to work if, i delete some of the contents.

Can you please clarify this.

Thank you

**Comment by muges01** [comment]
Hi @Seiyasu ,

Can you please reopen this. Can you also please clarify the issue?

Thank you

**Comment by Seiyasu** [comment]
Sorry for not reopen for the first time due to jet lag.  I have test the script again and again. All works well. I am not sure what is missing on your side.

**Comment by muges01** [comment]
I'm sorry @Seiyasu, i tried to reopen it but i couldn't find a way to do so. 
Can you please advice me what is the process on creating an issue and closing them? 
I have add comment to your reply on the other tread, please check them. I really wish that we can find some resolution for this issue.

**Comment by muges01** [comment]
Hi @Seiyasu, any updates regarding this?

**Comment by muges01** [comment]
hi @Seiyasu ,

This is an issue which has been highlighted in this issue item #2205. I guess your environment is different compare to use that is why you haven't get any error. Anyway, thank you for the help.
