### ISSUE TITLE
Which version of SPFx are the docs valid for?

### ISSUE THREAD

**Issue by DanielHabenicht** [SharePoint/sp-dev-docs#2696]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The old documentation clearly stated which version the guide/document was valid for, right under the title of the document. Like this: 
![snipaste_2018-10-04_17-51-52](https://user-images.githubusercontent.com/13590797/46486662-8c0bbc00-c7fe-11e8-88db-a3aa397d7ba3.png)

#### Observed Behavior
The new Documentation sites do not provide information about the versions they are valid for.
There is also no remark on the main page. 

Is it possible to write it down somewhere? 
Especially for people still working with older Sharepoint versions, it should be clearly communicated which guide is valid for which version.

**Comment by Seiyasu** [comment]
Thanks for you post. In most case the docs contains "SharePoint 2013/Apps for SharePoint" works well for SPFx too. And the screenshot you provided is base class, it should works well for all version.  For user who use older version, the only suggestion for them now is just try it. 

Even if the content team adds a version number in the Future. But there are inevitably/omissions, so the best choice for programmers is still need to learn to verify their own. You can't trust a document, or you can't completely believe it(docs is just for Reference). If you have verified that there is a problem in the docs, please submit a issue in github for it, so some one can fix it. Thanks.
