### ISSUE TITLE
Warning was Really Helpful

### ISSUE THREAD

**Issue by kavitajoshi** [SharePoint/sp-dev-docs#2698]
Your warning of "There are no placeholders in the Scope value. It is a literal value. Enter it exactly as it appears here." really helped for my add-in to use in flow that I was facing for many days. Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d171ce8-1c4b-a300-68bb-cacfffb24aba
* Version Independent ID: 63cd3866-4682-2492-4108-477a878df918
* Content: [Create a workflow with elevated permissions by using the SharePoint Workflow platform](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo)
* Content Source: [docs/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Hi, kavitajoshi. Thanks for your post. It seems you don't have issue on this, so I close the thread first. Fell free to reopen it if you have any question on this.
