### ISSUE TITLE
Field Formatter JSON and [$field] reference

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/sp-dev-docs#2699]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the [$field] notation in my field formatter JSON, I would expect the value of the referenced field to be available for use in the txtContent part of the JSON - whether or not the referenced field is part of the current view.

This is important for two reasons:
  * I use the field formatter to aggregate information from several fields into one visualization. Example: I have a progress bar that shows "spent money so far in relation to budget". The user needs to see the actual values from "Spent money" and "Budget" columns inside the column. The percent value is not important to see as a numerical value, since the width of the bar shows that in itself. 
  * The setup of the views is something the users themselves do on a very dynamic and day-to-day basis, and whether or not they include specific fields should not influence how other fields are shown.

#### Observed Behavior

If the referenced field is part of the current view everything works fine. 
If the referenced field is NOT part of the current view, then the field formatting just returns nothing.

#### Steps to Reproduce

  * Create a new list.
  * Add a text field
  * Add the new field to the default view.
  * Create a new item. Put some value into the Title field.
  * Configure the new text field with the following field formatter JSON:
   {
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "span",
			"txtContent": "=[$Title]"
    }
  ]
}
 * Observe that the new field shows the value of the Title field.
 * Create a new View - and de-select "Title".
 * Go to the new view and refresh the page.
 * Observe that the new text field is empty and does NOT show the value of Title.

Thanks for your contribution! Sharing is caring.

**Comment by Seiyasu** [comment]
For arbitrary data visualizations, please use **Field Customizer.** Your reason  beyond the **column formatting.**
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#how-is-column-formatting-different-than-the-field-customizer
