### ISSUE TITLE
Ability to notify Property Pane that Custom Field value was changed (Reactive and non-Reactive modes)

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#270]
#### Category
- Enhancement / Suggestion

#### Expected or Desired Behavior
For now there is now way to fire Property Group's (and Property Pane's) onChange handler from Custom Property Pane Field. In 'Reactive' mode I can use Web Part's onChanged handler, pass it to my Field and change something in Web Part's UI (similar behavior is described [here](https://github.com/SharePoint/sp-dev-docs/issues/169)). But in a 'Non-reactive' mode I can't enable 'Apply' button when something happened in my Field.
So my proposal is either have reference to onChange in the Custom Field or to have reference to Property Pane's group\Property Pane and API to mark it as 'changed' or 'dirty'.

**Comment by srideshpande** [comment]
We have an item tracked around this requirement. We will intimate once the functionality is ready.

**Comment by AJIXuMuK** [comment]
Hello guys,

Do you have any updates on that?

**Comment by srideshpande** [comment]
Hello @AJIXuMuK 

Sorry for the delay. The change is made to resolve this issue. You will be getting it in the next release. The change we have made is, the `onRender` prop on the custom field will now have a `changeCallback` method passed in from the framework. This should be invoked if you want the framework to know that something has changed within the custom field. This will trigger the regular property pane field change flow.

Please let me know if you still need any more details in this regard.

Thanks,
Srikanth

**Comment by AJIXuMuK** [comment]
Hello @srideshpande,

That's great!
Thanks for such change. Looking forward to new release.

**Comment by srideshpande** [comment]
@AJIXuMuK - Anytime. Appreciate your waiting. 

I am closing the issue for now, but please feel free to re-open it if you still see the issue after the next drop.

Thanks,
Srikanth
