### ISSUE TITLE
Error when approving api requests / Permissions show as both approved and pending

### ISSUE THREAD

**Issue by ksdaniel** [SharePoint/sp-dev-docs#2701]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When an api is approved - it should appear in the Approved category (and it should work).

#### Observed Behavior

These are actually two different problems: 

1. When I try to approve the requested api requests I get an error message: 

[HTTP]:403 -  [CorrelationId]:9259959e-5069-7000-fbd1-9befc367cde8 [Version]:16.0.0.8126 - Access denied. You do not have permission to perform this action or access this resource.

2. If i refresh the page the API appears as both approved and requested. 

![image](https://user-images.githubusercontent.com/17772784/46525941-9f1d9b00-c895-11e8-9ee5-ba04f38944a4.png)

Note: 

1. Graph calls from SPFX solutions to do not work when this happens.
2. I already made sure the tenant admin site has the correct permissions. 
3. There is only one app deployed.

#### Steps to Reproduce

Upload a SPFX solution with the following webApiPermissionRequests: 

>     "webApiPermissionRequests": [
>       {
>       "resource" : "Microsoft Graph",
>       "scope": "User.ReadBasic.All"
>       }

Go to webApiPermissionManagement and try to approve it.

**Comment by Seiyasu** [comment]
I cannot repro your issue on my side. Just a little issue on my side, the page won't refresh automatic.

**Comment by VesaJuvonen** [comment]
hi @ksdaniel, thanks for reporting this. This would imply that the removal of the permission request caused an exception, which would then imply that you do not have site collection administrative permissions in the app catalog. Can you confirm your permissions in the tenant app catalog? Thx.

**Comment by harshdamaniahd** [comment]
I too have the same issue
