### ISSUE TITLE
More CSS properties now available?

### ISSUE THREAD

**Issue by owenpt** [SharePoint/sp-dev-docs#2705]
'Detailed syntax reference &gt; style' list may need updating. I was trying to center to content, and only succeeded by using 'justify-content' which isn't listed in the available CSS properties. I imagine this means there may be other available CSS properties available, but not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#supported-column-types)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
[**justify-content**]( http://www.runoob.com/cssref/css3-pr-justify-content.html) is CSS properties not from Microsoft. The list normal just list the SharePoint provided CSS properties not include all from community.
