### ISSUE TITLE
Good explanation however it is not complete

### ISSUE THREAD

**Issue by CharlPels** [SharePoint/sp-dev-docs#2707]
This site tells how to enable, update and disable the classifications.
However there is no link on how to configure the policies, following the steps you get a drop down list HBI, MBI, LBI, GDPR
Then what :-)
In https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/implement-a-sharepoint-site-classification-solution
you can get information how to configure the policies you define, is this still needed for modern websites, if yes the point to that document, if not point to the place where there is an explanation on what you can do with the classifications you just set and how you can configure/see that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27643fd2-8059-f411-224b-bd0815aacc8f
* Version Independent ID: bd410f9a-a3f2-9222-7d4a-2271d7f6161d
* Content: [SharePoint ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification)
* Content Source: [docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-site-classification.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Follow the following to configure the policy:
https://docs.microsoft.com/en-us/office365/securitycompliance/secure-sharepoint-online-sites-and-files

**Comment by CharlPels** [comment]
Thanks but what is the relation between 
https://docs.microsoft.com/en-us/office365/securitycompliance/secure-sharepoint-online-sites-and-files
and 
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification

I can even create classifications that do not exist in labels.
So is my assumption correct that this solution for now is doing nothing more then showing a tag on the site?

I think my biggest issue is with this text

_The goal of site classification is to allow managing clusters of sites based on their classification from a governance and compliance perspective, as well as to automate governance processes based on site classification._

What do we manage here, what do we group or where can we see this grouping, where/what is the automation. in short there is a lot of text but it says nothing :-)

**Comment by umaknow-francis** [comment]
I too would like to understand how we can leverage this in a governance perspective.

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
