### ISSUE TITLE
SPFx package deployment fails if package-solution.json has more than 4 webApiPermissionRequests

### ISSUE THREAD

**Issue by rchivert** [SharePoint/sp-dev-docs#2708]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

package will deploy if there are more than 4 webApiPermissionRequest items

#### Observed Behavior

.sppkg package will not deploy if there are more than 4 items

#### Steps to Reproduce
package-solution.json:

{
  :
    "webApiPermissionRequests": [
    {
      "resource": "resource-01",
      "scope": "user_impersonation"
    },
    {
      "resource": "resource-02",
      "scope": "user_impersonation"
    },
    {
      "resource": "resource-03",
      "scope": "user_impersonation"
    },
    {
      "resource": "resource-04",
      "scope": "user_impersonation"
    },
    {
      "resource": "resource-05",
      "scope": "user_impersonation"
    }
  ]
  },
  "paths": {
    "zippedPackage": "solution/test.sppkg"
  }
}

if you remove the last item the package will successfully deploy 
 {
      "resource": "resource-05",
      "scope": "user_impersonation"
    } 

but if you include it (or in general, have more than 4 items)... it will not deploy.

**Comment by rchivert** [comment]
I've created an mp4 video that demonstrates the issue... can you send me a link where I can upload it (or send it) for you?  It's 20 MB.

**Comment by rchivert** [comment]
> I have tried this, and it works. Could you please more information. Such as the resource
I've created an mp4 video that demonstrates the issue... can you send me a link where I can upload it (or send it) for you? It's 20 MB

**Comment by KingKangMSFT** [comment]
You can upload it on your github repository, and share the link. Thanks

**Comment by rchivert** [comment]
Here's a [link](https://chiverton365dev-my.sharepoint.com/:v:/g/personal/bob_chiverton_chiverton365dev_us/EbWgJ-Ra64lCmOoeNUVdGRUB8QHKxDCgNv7tXdMnE0jOUQ?e=lXDkZu) to the video

**Comment by CharlesLiuMSFT** [comment]
Hi rchivert,

Could you share your link of your mp4 file one more time for us to test it since the link is expired? 

Thanks.

**Comment by VesaJuvonen** [comment]
This is a known issue related to having "too many" permissions in the solution package related to the permissions requests. Too many in this case mean that the list where permission requests are temporarily stored has a size limit per request. We are working on a solution for this, but there's no ETA. Right now the easiest way to tackle this is to reduce the permissions in the package-solution.json and grant permissions using PowerShell. 

Notice that with the October release of SharePoint Online PowerShell, tenant admin can directly grant permissions using Approve-SPOTenantServicePrincipalPermissionGrant - documentation at https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/approve-spotenantserviceprincipalpermissiongrant?view=sharepoint-ps.

**Comment by rchivert** [comment]
Thanks Vesa. Yes... I was able to get all the permissions by doing it 4 at a time. Next time I’ll use PowerShell.

By the way... I’ve admired your hard work for a few years now... please keep up the wonderful PnP gifts.

Also... I’ve just published a new article using SPFx & AadHttpClient - feel free to check it out at

https://bobchiverton.com/

Bob Chiverton

On Nov 8, 2018, at 3:33 AM, Vesa Juvonen <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a known issue related to having "too many" permissions in the solution package related to the permissions requests. Too many in this case mean that the list where permission requests are temporarily stored has a size limit per request. We are working on a solution for this, but there's no ETA. Right now the easiest way to tackle this is to reduce the permissions in the package-solution.json and grant permissions using PowerShell.

Notice that with the October release of SharePoint Online PowerShell, tenant admin can directly grant permissions using Approve-SPOTenantServicePrincipalPermissionGrant - documentation at https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/approve-spotenantserviceprincipalpermissiongrant?view=sharepoint-ps<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fsharepoint-online%2Fapprove-spotenantserviceprincipalpermissiongrant%3Fview%3Dsharepoint-ps&data=02%7C01%7C%7C120f83267a274d37707608d64554df43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636772628150288052&sdata=FEWT%2FTGUQZxdLhfi8KxOAdWdigeFlELsSRwsh6rs6vs%3D&reserved=0>.

**Comment by VesaJuvonen** [comment]
thx @rchivert for the feedback, appreciated. Closing this as fixed.
