### ISSUE TITLE
Exceptions not logged in console when bubbling to OnInit

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/sp-dev-docs#2709]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Any exceptions that fall down into SPFx should generate some kind of debugging output

#### Observed Behavior

Exceptions that occur in a web part render() method are bubbled up to the console. However we leverage the OnInit() to do handle the data gathering. We've found that any exceptions that make way back to the OnInit() are never shown in the console. 

Have not tested with other overrides, however this puts us under the impression that most method entry points must have try catch and our own logging to capture any issues that fall through.

#### Steps to Reproduce

1. Create 1.6.0 Project with Webpart
2. Add error to webpart render method (i.e.  throw Error('something');
3. Run _-> Error shows_
4. Add error to onInit()
5. Run _-> Webpart spins indefinitely, no error in console_

**Comment by Seiyasu** [comment]
@2toLeadMike , thanks for your post. This is on engineering team's work list.

**Comment by kemesfun** [comment]
@2toLeadMike I am not able to repro this issue. I see the error on the console when I add the error to  onInit(). Can you verify that this issue is still occurring?

**Comment by 2toLeadMike** [comment]
@kemesfun tried using spfx 1.10.0 and it now logs the error. It does not react the same way render() works (it will show endless shimmer whereas render shows error message to end user) however the important piece was being able to get exception info. Thanks for heads up
