### ISSUE TITLE
Please include Aurelia on the scaffolding options when generating code.

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#271]
Pretty self explanatory:
Please include Aurelia on the scaffolding options when generating code.

I know Aurelia is not RTM yet, but certainly a good framework that is being talked about in the JS space, so maybe for next version if you could include it Id appreciate it and I guess other developers as well.

www.aurelia.io

**Comment by manishgarg1** [comment]
Please look at issue [272](https://github.com/SharePoint/sp-dev-docs/issues/272). The response to should should be a bit similar. We should make it easy to add sub generators and custom generators.

**Comment by chakkaradeep** [comment]
@levalencia we do not have plans to include Aurelia JS right now. 

As mentioned in #272 We have this item in backlog. That said, we are planning to bring a model where 3rd parties can extend the generator to add their own support for frameworks that Microsoft does not provide in the generator.

In that regards, i am closing this issue. Please open a new issue if you find any specific issue with Aurelia JS and SPFx. Thanks!
