### ISSUE TITLE
I could not run the site script for flows-formatters-pages-siteScripts

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#2710]
Hi everyone,

I tried to reopen my issue(#2695) but i'm not sure how to reopen it, so i'm recreating this issue. 

I try to create a team site using the provided site script 'UberSiteDesign.json' but the site script stuck on the initialising. I awaited for few minutes and it is still stick on that screen.

![site-script](https://user-images.githubusercontent.com/22563887/46478922-d92f6400-c7e5-11e8-9298-4ecf9b2f398b.png)

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expected to see the site script run successfully. 

#### Observed Behavior
I have done some testing and and i found out that if i remove some of the lines in the scripts than it successfully created. I have tested by removing some chuck from different sections. This shows that the site script has some line, or character or size limits. Can some one clarify on this?

#### Steps to Reproduce
1. Get the 'UberSiteDesign.json' from https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/flows-formatters-pages-siteScripts/site-designs. (**To be clear that i have downloaded the whole solution.** 
2. $siteScript = Get-Content '[[pathToYourSiteScriptJsonFile]]' -Raw
3. $mySiteScript = Add-SPOSiteScript -Title "Classroom Site Script" -Description "Classroom Site Script" -Content $siteScript
4. Add-SPOSiteDesign -Title "Classroom site designs" -WebTemplate "64" -SiteScripts $mySiteScript -Description "classroom site design"

I hope someone could guide me on this issue.

Thank you in advanced.

**Comment by Seiyasu** [comment]
Do not delete content except replace some text to yours.
If you save the UberSiteDesign.json to local, the file size is about 46kb.

**Comment by Seiyasu** [comment]
And now it is more close IT pro issue not a developer issue, we cannot use this process/route to report this to the right feature crew. Please open the issue from the Tenant admin support pages to route it using correct channels. Sorry for the inconvenience. The script still works well on my side by following your repro steps. I am not sure what you have missed.

**Comment by Seiyasu** [comment]
![sitedesign](https://user-images.githubusercontent.com/42561668/46599575-47439600-cb1a-11e8-8c56-e3dcdce8ceee.PNG)
![image](https://user-images.githubusercontent.com/42561668/46599684-87a31400-cb1a-11e8-8496-57ad6e85d085.png)

**Comment by Seiyasu** [comment]
Try to clear your RECYCLER/Cache before submit request to the O365 admin team. The UberSiteDesign is OK.

**Comment by muges01** [comment]
Hi Seiyasu,

From the image that you added, the classroom test doesn't show the correct side design been applied. You should see couple of list added to the site and some new links at the right hand side navigation. 

I also have tested without deleting anything and still the site script never run successfully on the new site. **Can you please share your screenshot where all the list been created successfully and left navigation been created successfully in your tenant.**

> Try to clear your RECYCLER/Cache before submit request to the O365 admin team. The UberSiteDesign is OK.

What do you mean by 'RECYCLER/Cache'? Can you tell me how to do this? 
I did tried to clear my browser cache before creating new site using this site design.

> And now it is more close IT pro issue not a developer issue, we cannot use this process/route to report this to the right feature crew. Please open the issue from the Tenant admin support pages to route it using correct channels. Sorry for the inconvenience. The script still works well on my side by following your repro steps. I am not sure what you have missed.

You also mention that this is not developer issue, can you please clarify to me what do you mean by this and where is the right please to raise this type issue.

@Seiyasu why are you keep closing the issue when it's not been clear yet? 
Can you please advice me what is the process on creating an issue and closing them?

**Comment by muges01** [comment]
Hi @Seiyasu ,
any updates regarding this?
