### ISSUE TITLE
Dynamic data released as part of 1.5.1-plusbeta version is not available in 1.5.1 or 1.6

### ISSUE THREAD

**Issue by ashishshukla1183** [SharePoint/sp-dev-docs#2711]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

1. Used dynamic data to connect application customizer to a webpart using 1.5.1-plusbeta
2. Upgraded/changed framework to 1.5.1 and then 1.6.0. This is to implement the functionality in production. 

#### Observed Behavior
While trying to import IDynamicDatasource throws error that sp-dynamic-data has not exported member of this name.

If I understand correctly, dynamic data has not been deprecated or dropped after dev only release. Please let me know if it will be part of any upcoming releases?

**Comment by BraunJonathan** [comment]
Looks like Dynamic data are still in beta !
You have to use 1.5.1-plusbeta or 1.6.0-plusbeta.
It "works" is production that way, you juste have to compile your webpart using the beta version of the framework.

**Comment by ashishshukla1183** [comment]
> Looks like Dynamic data are still in beta !
> You have to use 1.5.1-plusbeta or 1.6.0-plusbeta.
> It "works" in production that way, you juste have to compile your webpart using the beta version of the framework.

But Microsoft advises to not use anything in beta release for production. They clearly say that its not supported, unless in exceptions where they know that such feature is there in next release.

**Comment by BraunJonathan** [comment]
Of course, but the only choice you have here is to use the beta version or not to use Dynamic Data at all...

Obviously, if you have a production problem, you're on your own...

**Comment by VesaJuvonen** [comment]
Dynamic data is not yet GA, so it's not available for production usage. It is planned to go GA in 1.7 later this year and until that happens, it will be only available from plusbeta packages. As this is answered, closing the issue.
