### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ken-harris** [SharePoint/sp-dev-docs#2719]
At the end of this tutorial it says that it's supposed to pull in the theme that you selected from Sharepoint, but I'm still only seeing the default blue color.

Also when I refresh the page the CSS doesn't load immediately, which causes the page to flicker from the old non-Sharepoint CSS to the sharepoint CSS which is very jarring. Is this normal behavior since we're at the beginning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14641c6-8ce6-8838-ab9a-8e6ea90aed50
* Version Independent ID: 9b7fcbf8-4fc6-ade9-62ef-a1d4345827f8
* Content: [Give your provider-hosted add-in the SharePoint look-and-feel](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel)
* Content Source: [docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thx @ken-harris ，I have submit it for helper

**Comment by garima2510** [comment]
Any update on this? If we change the look of host web, it does not reflect in app. It used to work before. Has anything changed?
