### ISSUE TITLE
Please include VueJS on the scaffolding options when generating code.

### ISSUE THREAD

**Issue by mauricionr** [SharePoint/sp-dev-docs#272]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
VueJS as option in yo generator

#### Observed Behavior
No VueJS

Thanks!

**Comment by Jonas-buriti** [comment]
I totally agree! This would be a great enhacement

**Comment by wictorwilen** [comment]
This is how I see it. Please do not add anymore options/frameworks to the current generator. Instead make it easy (document and/or use the community) to create either sub generators or separate generators for these things.

**Comment by patmill** [comment]
I like the approach from @wictorwilen .  It would be good to allow the community to create and install generators.  I'd be nervous of having 250 frameworks to chose from, but at the same time it seems totally reasonable to say "we use X, and we'd like to have X for our devs" or even "we have our own base classes, let's use them".

Will think about it further.

**Comment by mauricionr** [comment]
@patmill great demo today in bi-weelky call and i could figure out how to use vue.js with spfx, this issue could be closed or you guys have plans to include an scaffolding for include vue.js?

thanks Sergei Sergeev (@sergeev_srg) for the demo, here is the link for the code i mentioned!
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/vuejs-todo-single-file-component

Thanks guys! :smile:

**Comment by chakkaradeep** [comment]
@mauricionr we do not have any plans to include Vue JS right now. We have this item in backlog along with other requests like #271. That said, we are planning to bring a model where 3rd parties can extend the generator to add their own support for frameworks that Microsoft does not provide in the generator.

**Comment by chakkaradeep** [comment]
Closing this issue. @mauricionr Please open a new issue if you find any specific issue working with Vue JS and SPFx. Thanks!

**Comment by mauricionr** [comment]
Thanks @chakkaradeep

**Comment by s-KaiNet** [comment]
@chakkaradeep is there an issue to track the state of this task (or is there a timeline?): 

> we are planning to bring a model where 3rd parties can extend the generator to add their own support for frameworks that Microsoft does not provide in the generator.
