### ISSUE TITLE
Can I use a [sp-dev-fx-controls-react] for SP16 On-Premise

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-docs#2724]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Can I use a [sp-dev-fx-controls-reac] for SP16 On-Premise ??

After install **sp-dev-fx-controls-reac**t with **npm install @pnp/spfx-controls-react --save --save-exact** i have following errors:
![untitled](https://user-images.githubusercontent.com/14110861/46650638-f1b4cb00-cba5-11e8-9475-551c3edf692f.png)

This is content of my .yo-rc.json file is:

`{ "@microsoft/generator-sharepoint": { "version": "1.4.0", "libraryName": "travels", "libraryId": "10340777-f8eb-4423-ba85-3fb5794a7bf1", "environment": "onprem" } }`

**Version of TS** is: 2.2.2

**Comment by Seiyasu** [comment]
What is your SharePoint 2016 On-Premise version? Is it (Feature Pack 2) or above?

**Comment by geogikk92** [comment]
My SharePoint 2016 On-Premise version is **Feature Pack 2**

**Comment by VesaJuvonen** [comment]
Replied and answerd at SharePoint/sp-dev-fx-controls-react#149, so closing from here.
