### ISSUE TITLE
Add-PnPCustomAction : A parameter cannot be found that matches parameter name ‘ClientSideComponentId’.

### ISSUE THREAD

**Issue by ramisn** [SharePoint/sp-dev-docs#2733]
I have faced the issue with:

“Add-PnPCustomAction : A parameter cannot be found that matches parameter name ‘ClientSideComponentId’.”

I have tried both created own .sppkg file and run this cmd,
Add-PnPCustomAction -ClientSideComponentId “xxxxxxxxxxxx” -Name “Analytics” -Title “Analytics” -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: ‘{“trackingID”:”UA-my-own-id”}’ -Scope site.

Please give me a suggestion.

Thanks and Regards,

**Comment by KingKangMSFT** [comment]
Could you please make sure the `ClientSideComponentId ` is correct. If so, please try to remove the quotation marks. For example, Add-PnPCustomAction -ClientSideComponentId xxxx

**Comment by ramisn** [comment]
Worked for me. Thanks for the support
