### ISSUE TITLE
The section "Provision a "modern" team site programmatically via SharePoint Online REST API" could use some details

### ISSUE THREAD

**Issue by thomasberman** [SharePoint/sp-dev-docs#2734]
It would be nice to see the actual endpoints to call to create modern team/communication sites in this section. Documentation on creating modern sites via REST seems to be relatively sparse in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites#provision-a-modern-team-site-programmatically-via-sharepoint-online-rest-api)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
What is your mean of actual endpoints? For data protection, the sensitive information will be hidden or disposed.

**Comment by thomasberman** [comment]
@Seiyasu, I mean the REST endpoint to call in SharePoint or Office 365 to create a new Modern Team Site. Something like: https://graph.office.com/beta/groups/ (no idea if it can be done via graph API or not) or similar.

I think it would be useful to have the information in this section on how you actually create modern Communication and Team sites via REST.

**Comment by thomasberman** [comment]
Further to my comment above, I see that the Graph API is officially documented with examples and so is the SitePages API. I'll add those to the documentation section on creating modern sites via REST and create a pull request.
