### ISSUE TITLE
ListView Command Set extension Not loaded  in Document Library (preview) WebPart

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2736]
#### Category
- [ x] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When creating a ListView command set extension we expected that it will work with the List / Document Library webparts too.

#### Observed Behavior

The extension is loaded (we can see the js file loaded and the new command shown) when we access the library directly. But when we use Document Library web part the script is not loaded and the commands are not visible. 
#### Steps to Reproduce

Create an extension as defined here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api 
Create a Page and add the Document Library WebPart. Configure it to use some document library.

**Comment by Seiyasu** [comment]
1. No official docs state Document  webpart support the SPFx ListView Extension.
 2. The Document  webpart is preview, still in developing, so no-support to ListView extension is normal now. You can submit feature request in the UserVoice.
