### ISSUE TITLE
REST API Documentatinon missing SPSiteManager endpoints

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#2739]
There are a least two undocumented endpoints https://tenant.sharepoint.com/_api/SPSiteManager/Create and https://baywet.sharepoint.com/_api/SPSiteManager/Delete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94956608-25b4-0605-f43d-d161ebdde905
* Version Independent ID: 5a5b71db-be77-2ac8-7b9f-82f13961d4fa
* Content: [SharePoint .NET Server, CSOM, JSOM, and REST API index](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index)
* Content Source: [docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by baywet** [comment]
The Create endpoint allows you to create site collections, example payload:
```JSON
{"request":{"__metadata":{"type":"Microsoft.SharePoint.Portal.SPSiteCreationRequest"},"WebTemplate":"SITEPAGEPUBLISHING#0","Title":"testcreationapi","Url":"https://tenant.sharepoint.com/sites/testcreationapi","Description":"","Classification":"","Lcid":1033,"ShareByEmailEnabled":false,"WebTemplateExtensionId":"00000000-0000-0000-0000-000000000000"}}
```

**Comment by KingKangMSFT** [comment]
Thanks @baywet , I have submit it.

**Comment by DRamalho92** [comment]
Hi @baywet,

You can find the documentation of this REST API on the link below: 
https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest

**Comment by baywet** [comment]
Thanks for the follow up @DRamalho92 !
Thanks for documenting the endpoints @mbratukha @bcameron1231 @erwinvanhunen !
Closing.
