### ISSUE TITLE
how can i change deploy from localhost:5000 to myip:5000 

### ISSUE THREAD

**Issue by Sherif-Mostafa** [SharePoint/sp-dev-docs#274]
after i run gulp serve it runs https://localhost:5000/ and i need to make it by my ip 

any help..

**Comment by patmill** [comment]
What is it you are trying to achieve?  Do you want someone on a different computer hitting a sharepoint page to get your local code?

**Comment by Sherif-Mostafa** [comment]
yes exactly can you help

**Comment by iclanton** [comment]
Sorry this hasn't gotten attention recently.

We actually do have a built-in tool to do exactly what you're trying to do. It's called `dev-deploy` and we use it internally extremely heavily. It's also present in the tools you receive. However, it only works with Azure.

To provide an unfortunately short answer to your question, it looks like we made a mistake and this isn't a configurable `@microsoft/sp-build-web` task. However, I'm going to try to release a patch next week to fix that problem.

@nickpape-msft , @patmill, sound good?

**Comment by iclanton** [comment]
As of the latest drop, we've added an additional property in the `serve.json` file called [`hostname`](https://github.com/Microsoft/web-build-tools/blob/master/core-build/gulp-core-build-serve/src/ServeTask.ts#L46) which can be configured to the hostname that shows up in your debug manifests.

We also now have a `gulp dev-deploy` task that will deploy your code to an Azure Storage instance. You just need to drop a `config/dev-deploy.json` file with these contents:

```json
{
  "account": "<your Azure storage account name>",
  "accessKey": "<an access key for your Azure storage account",
  "container": "<container name, something like 'files'>",
  "containerDirectoryName": "<directory name under your container, something unique so you don't clobber others' work>"
}
```

This task will upload all of your files and print out a debug querystring that you can share with colleagues.
