### ISSUE TITLE
Missing description.

### ISSUE THREAD

**Issue by LuigiBruno** [SharePoint/sp-dev-docs#2740]
This object represents a SharePoint Foundation website, but such a description is missing: where can this information be added in the underlying markup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762ba236-0cb6-1290-0a57-d7783fc9fe6e
* Version Independent ID: 55b04e3b-f9e7-9e80-9e58-714e1848f5e1
* Content: [SPWeb Class (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spweb?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPWeb.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPWeb.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by Seiyasu** [comment]
We can reference to this [docs](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb_members.aspx?f=255&MSPPError=-2147217396).

**Comment by LuigiBruno** [comment]
@Seiyasu 
Thanks. I was wondering whether it could be useful to have at least a small description: if you click any of the links in the page you're redirected to a more detailed page under docs.microsoft.com, but there is no description.
I've seen a <summary> markup block: could it be the right place for a brief description?

**Comment by andrewconnell** [comment]
Microsoft is aware of this... there was an issue when porting docs from MSDN => Docs. Unfortunately, I don't have any additional updates on this. See this comment for more info:

https://github.com/SharePoint/sp-dev-docs/issues/2364#issuecomment-414684429

**Comment by LuigiBruno** [comment]
> Microsoft is aware of this... there was an issue when porting docs from MSDN => Docs. Unfortunately, I don't have any additional updates on this. See this comment for more info:
> #2364 (comment)

Thank you @andrewconnell.
