### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by LuigiBruno** [SharePoint/sp-dev-docs#2741]
This object represents a collection of sites in a Web application, including a top-level web site and all its subsites, but such a description is missing: where can this information be added in the underlying markup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d83491f-fe3e-ef02-a187-8d3f63607fd6
* Version Independent ID: 38525b06-0fd7-7f3e-227f-702fb183074c
* Content: [SPSite Class (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spsite?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPSite.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPSite.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by KingKangMSFT** [comment]
Thanks @LuigiBruno , I think we can refer to [this document](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spsite_members.aspx) for the detail information

**Comment by KingKangMSFT** [comment]
We have contact the content team. Any updates will sync up to you

**Comment by LuigiBruno** [comment]
Thank you.
