### ISSUE TITLE
Column formatting percentage progress bar 

### ISSUE THREAD

**Issue by dquez325** [SharePoint/sp-dev-docs#2742]
#### Category
- [ ] Question
How can I use JSON to create a percentage progress bar as a column with a need to assign 10 choice columns with a calulated value? For instance, 10 - "yes or no" choice columns that present a value of 10% each when yes is chosen.

#### Expected or Desired Behavior

Progress bar (calulated from other columns) choice yes or no.

#### Observed Behavior
 
Unable to assign 10 to each choice colomn therefore my progress bar column   (calulated column) will only show #value as an error result.

thanks ahead of time for any type of advise or tips to make this work.

Dan

**Comment by Seiyasu** [comment]
For Complex custom, please try to use Field Customizer.
