### ISSUE TITLE
Placeholders in SPFX extension stopped working

### ISSUE THREAD

**Issue by IvanToronto** [SharePoint/sp-dev-docs#2744]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

Few minutes ago, on all of my O365 tenants this code stopped working:

In SPFX Extension:
var _topPlaceholder =  this.context.placeholderProvider.tryCreateContent(PlaceholderName.Top, { onDispose: this._onDispose }); 

It now returns undefined.

I guess it is a global O365 issue. Fully documented and supported feature is not working at the moment.

**Comment by IvanToronto** [comment]
Update: working again now. 

Microsoft breaks some stuff and restores it without any notifications to business users.

**Comment by jareha** [comment]
I’ve had this same issue for the past week. For a brief period this morning, `this.topPlaceholder` returned what we expected it to. And then began returning `undefined` again.

**Comment by jareha** [comment]
@IvanToronto, could you reopen this issue? I’ve found `Placeholders` to be very inconsistent. They’ve worked and not worked at least three times each for my team over the last week.

**Comment by IvanToronto** [comment]
jareha, no problem.
I guess the feature is supported, but Microsoft constantly updates O365 without attention to SLA:)

**Comment by VesaJuvonen** [comment]
We understand the inconvenience. There was an issue on this capability, but it has been now fixed. Please open a new issue if you still see this. Sorry for the lack of communications on this.
