### ISSUE TITLE
hub sites

### ISSUE THREAD

**Issue by seal-tm** [SharePoint/sp-dev-docs#2748]
How do Site Collection App Catalogs correspond to Hub sites?
Can I add a SC App Catalog to the Hub Site and access it in the linked Sites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb134fd8-6880-360a-faea-7eb0eedca2d9
* Version Independent ID: 16f799b7-deff-b125-ceed-343933bcbe79
* Content: [Use the site collection app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)
* Content Source: [docs/general-development/site-collection-app-catalog.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/site-collection-app-catalog.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
There is no linking between site collection app catalog and hub sites currently. We are potentially looking into having hub site app catalog in the future, but this has not yet been implemented.
