### ISSUE TITLE
AadHttpClient Connect to Dynamics 365 - Business Central

### ISSUE THREAD

**Issue by johncondron** [SharePoint/sp-dev-docs#2749]
Hi I'm having some issues with getting data from my Azure AD Secured API. I have done the App Registration in Azure AD and I can get the response as expected when I use Postman. Which, I'm led to believe should mean that I should be able to get the data using the AadhttpClient class.

I've followed the guide here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient to try and connect from my SPFx WebPart but when I add it to a page I get a 401 error.

I've attached my .ts file and my package-solution.json file as they're the only files I've edited.

I'm new to this, so please be kind. But if anyone can kick me in the right direction as to where I'm going wrong that would be wonderful.  Apologies if there's anything else I should have included.

Thanks...

John

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

[BusinessCentralWebPart.ts.txt](https://github.com/SharePoint/sp-dev-docs/files/2469578/BusinessCentralWebPart.ts.txt)
[package-solution.json.txt](https://github.com/SharePoint/sp-dev-docs/files/2469579/package-solution.json.txt)

**Comment by waldekmastykarz** [comment]
If you look at the request headers in the browser's dev tools, can you see an access token attached to the request? If you inspect its contents using a tool like https://jwt.io, can you see the audience and permission scopes matching the API you're calling?

**Comment by wictorwilen** [comment]
Is `Business Central` the name of your Azure AD Secured API?

**Comment by johncondron** [comment]
Hi Waldek, I'll give that a go now.  Thanks...

wictorwilen, yes it is.  Thanks.

John

**Comment by johncondron** [comment]
Hi @waldekmastykarz I did as you suggested and got the following.

![payload_data](https://user-images.githubusercontent.com/37665763/46857891-dfcf6400-ce01-11e8-92ec-9564a3842774.png)

To be honest, that doesn't make things any clearer for me.  Any help would be great.

Thanks...

John

**Comment by waldekmastykarz** [comment]
What permissions did you grant to the Business Central AAD app in Azure AD?

**Comment by johncondron** [comment]
Hi @waldekmastykarz 

This is what I have.  As I said I can get a new Access Token and get the data when using postman, so I figured that things were ok on that side.

![access](https://user-images.githubusercontent.com/37665763/46866015-9a1d9600-ce17-11e8-9246-8c5cf0dfbf7e.png)

**Comment by johncondron** [comment]
Ok, it seems I didn't have any permissions granted for the SharePoint Online Client Extensibility Web Application Principal App.  I've added permissions to the Windows Azure Active Directory API but now I'm getting a prompt saying "Additional Credentionals are required to show this page correctly" if I log in it redirects me to my top level root site.

**Comment by waldekmastykarz** [comment]
Have you opened the API management page in the SharePoint Tenant admin center at least once? It could be, that the app hasn't been setup in your tenant yet.

**Comment by johncondron** [comment]
Hi @waldekmastykarz 

Yes, I've gone in to the AP Management page and approved everything in there.

**Comment by waldekmastykarz** [comment]
Is it still failing?

**Comment by johncondron** [comment]
Hi Waldek, 

Yea I'm still getting the prompt saying "Additional Credentials are Required".  I've obviously done something wrong, but I'm really not sure where to look.  I guess the problem is not properly understanding how things *should* work so maybe that's where I should be focusing.

Thanks again for all your help, it really is appreciated.

Cheers...

John

**Comment by waldekmastykarz** [comment]
No problem. What browser are you using and which version of SPFx?

**Comment by johncondron** [comment]
I'm using Chrome and SPFx 1.6

**Comment by johncondron** [comment]
So, I add my webpart to my page and I get this prompt

![prompt](https://user-images.githubusercontent.com/37665763/47037682-7049d380-d177-11e8-999f-5e3a8de8273d.png)

If I enter my credentials, it redirects to the root of my SharePoint tenant.  If I cancel, I get this in the console:

![error](https://user-images.githubusercontent.com/37665763/47037770-be5ed700-d177-11e8-9df8-0c36656b2179.png)

Hope that helps, don't know how many ways to say thanks lol

**Comment by waldekmastykarz** [comment]
Have you seen this thread https://github.com/SharePoint/sp-dev-docs/issues/2473#issuecomment-419267563?

**Comment by waldekmastykarz** [comment]
Is it working now?

**Comment by johncondron** [comment]
Sorry Waldek, I was away for a few days.  Still not working.  I think that maybe I should take a few steps back and get a better basic understanding of SPFx and then maybe come back to this.  It's been pretty frustrating.  Thanks for all your help.
