### ISSUE TITLE
Delete Provisioned Content Type

### ISSUE THREAD

**Issue by zolem** [SharePoint/sp-dev-docs#2750]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Provisioned content types should allow deletion

#### Observed Behavior
Attempting to delete a content type that has been provisioned by an spfx webpart will give you an error.
It usually says something like: This content is associated with a feature so it can't be deleted.
To get around this I have created a horde of content types:
![image](https://user-images.githubusercontent.com/7129911/46819314-a682ef80-cd40-11e8-9bb4-f5880befe5f2.png)

Now it gives me errors about duplicate content types when I try to delete them which may actually be true for some, but at some point I started using a new unique guid every time.

#### Question
Is there a way to delete content types provisioned from an SPFX webpart? Would be nice to clean this up and not have to create a new one every time I screw up and have to try again.

#### Steps to Reproduce
Just provision a content type with an SPFX webpart. Remove everything associated with it and then try to delete it. It will give you an error of one of the following:
- Duplicate content type sometimes (after doing my workaround above, even when trying to delete one with a unique guid)
- Associated with a feature so can't be deleted (not sure if you can delete a feature if deleting the app doesn't do it)

**Comment by KingKangMSFT** [comment]
Please try to empty the secondary recycle bin in the admin site after you’ve deleted everything that associated with your content type. Then delete this content type.

**Comment by zolem** [comment]
@KingKangMSFT I have done that many times. Still no dice.

**Comment by khmlpa** [comment]
I am having the same experience

From the tutorial here
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package

### Observed Behavior
Fields get added to the content type
Fields get added to list
The content type does not get added to the list.
New content type is unable to be removed.
Tried manually through the browser and Remove-PNPContentType  and even "-Force"
Error message received "The content type "Cost Center" is part of an application feature"
Removed the "asset-development-client-side..." App from the site.
Clear-PnPRecycleBinItem
Tried to delete again.
Got the same error.
Removed the app from the tenant app catalog.
Clear-PnPRecycleBinItem on the app catalog site
Tried to delete again.
Got the same error.

**Comment by VesaJuvonen** [comment]
This is unfortunately currently by design. There's no way to delete a content type, which had some content at some point and which was created using a Feature Framework feature, which has been already de-activated. This is by design since SP2007 unfortunately.

**Comment by mohitcreative** [comment]
Are there any workarounds to accomplish this? Its been suggested that "If you don't have the feature anymore, create dummy feature, with fake CT - put the right content type ID and Name, other attributes doesn't matter, even the FieldRefs node doesn't matter."

**Comment by VesaJuvonen** [comment]
@mohitcreative - those are indeed valid workarounds on cleaning things up, if needed.
