### ISSUE TITLE
Can I execute UserProfile.BatchUpdate.API using app-only?

### ISSUE THREAD

**Issue by AussieDavo** [SharePoint/sp-dev-docs#2751]
Apparently this works but is there any example PowerShell code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0dffd-d314-6e01-be9a-f72d852227e3
* Version Independent ID: e48220e4-412d-aee0-ce37-86400efb6cc3
* Content: [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online)
* Content Source: [docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The powershell demo code is in the same project.
https://github.com/SharePoint/PnP/blob/master/Samples/UserProfile.BatchUpdate.API/CreateImportJob.ps1

**Comment by riswan90** [comment]
I have managed to run the script using PowerShell. But how can we run script using csv file ?

**Comment by ChangeAdvocate** [comment]
According to the article on https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online this can be accomplished using the App-Only model.  And also on your article on https://developer.microsoft.com/en-us/office/blogs/introducing-bulk-upa-custom-profile-properties-update-api/ says in can be done using App-Only.  But yet we get access denied when calling the API. 

Did you mean to say that the App-Only model works just to import the file, but in order to call the API we need to use the user/password model?

**Comment by AussieDavo** [comment]
So I managed to get the import working using the New-PnPUPABulkImportJob from SharePoint/PNP-PowerShell available from https://github.com/SharePoint/PnP-PowerShell . I put this in Azure Runbooks so it all runs up in Azure. Here is some example code:

`$PortalUrl = get-automationvariable -name 'PortalURL'`
`$AppID = get-automationvariable -name 'AppID'`
`$AppSecret = get-automationvariable -name 'Key'`
`$importFileUrl = "Shared Documents"`
`$ImportSiteCollection = "https://tenant.sharepoint.com/sites/sync/"`
`$ImportFileLocation = "Shared Documents/import.json"`

`Connect-PnPOnline -AppId $AppID -AppSecret $AppSecret -Url $ImportSiteCollection -Verbose`
`Get-PnPFile -Url $ImportFileLocation -Path $env:temp -FileName "import.json" -AsFile -force -Verbose`

`$tempfile = $env:temp + "\import.json"`

`Connect-PnPOnline -AppId $AppID -AppSecret $AppSecret -Url $PortalUrl -Verbose`

`# JSON on the left, SharePoint on the right (CASE SENSITIVE!!!!!!!!)`
`$propertyMap = New-Object -type 'System.Collections.Generic.Dictionary[String,String]'`
`$propertyMap.Add("employeeType", "employeeType")`
`$propertyMap.Add("extensionAttribute1", "extensionAttribute1")`
`$propertyMap.Add("extensionAttribute2", "extensionAttribute2")`
`$propertyMap.Add("extensionAttribute3", "extensionAttribute3")`
`$propertyMap.Add("extensionAttribute4", "extensionAttribute4")`    
`$propertyMap.Add("msDS-cloudExtensionAttribute1", "msDS-cloudExtensionAttribute1")`
`$propertyMap.Add("msDS-cloudExtensionAttribute2", "msDS-cloudExtensionAttribute2")`
`$propertyMap.Add("msDS-cloudExtensionAttribute7", "msDS-cloudExtensionAttribute7")`
`$propertyMap.Add("msDS-cloudExtensionAttribute12", "msDS-cloudExtensionAttribute12")`
`$propertyMap.Add("msDS-cloudExtensionAttribute3", "msDS-cloudExtensionAttribute3")`
`$propertyMap.Add("msDS-cloudExtensionAttribute9", "msDS-cloudExtensionAttribute9")`
`$propertyMap.Add("otherTelephone", "otherTelephone")`
`$propertyMap.Add("streetAddress", "streetAddress")`
`$propertyMap.Add("l", "l")`
`$propertyMap.Add("st", "st")`
`$propertyMap.Add("postalCode", "postalCode")`
`$propertyMap.Add("facsimileTelephoneNumber", "facsimileTelephoneNumber")`
`$propertyMap.Add("mobile", "CellPhone")`
`$propertyMap.Add("msDS-cloudExtensionAttribute6", "msds-cloudExtensionAttribute6")`
`$propertyMap.Add("msDS-cloudExtensionAttribute14", "msds-cloudExtensionAttribute14")`

`New-PnPUPABulkImportJob -Path $tempfile -Folder $importFileUrl -IdProperty "IdName" -UserProfilePropertyMapping $propertyMap -verbose`

**Comment by AussieDavo** [comment]
Also if anyone is interested, here is how I exported the attributes from AzureAD and created the JSON file in the SharePoint Online Site collection using an Azure Runbook:

`$AppID = get-automationvariable -name 'AppID'`
`$AppSecret = get-automationvariable -name 'Key'`
`$ImportSiteCollection = "https://tenant.sharepoint.com/sites/sync/"`

`# Get Tenant Detail`
`$AADtenantid = get-automationvariable -name 'AADtenantID'`
`$AADappid = get-automationvariable -name 'AADAppID'`
`$AADthumb = get-automationvariable -name 'AADthumb'`

`# Now you can login to Azure PowerShell with your Service Principal and Certificate`
`Connect-AzureAD -TenantId $AADtenantid -ApplicationId  $AADappid -CertificateThumbprint $AADthumb -Verbose`

`$users = Get-AzureADUser -All $true | Where-Object {$_.usertype -like "member" -and $_.accountenabled -eq $true -and $_.AssignedLicenses -ne $null}`

`$grandpayload = @()`

`foreach ($user in $users) {`

`$Exts = $user.ExtensionProperty`

`if ($user.UserPrincipalName) {`

`        $payload = New-Object -TypeName PSObject`
`        $payload | Add-Member -Name 'IdName' -MemberType Noteproperty -Value $user.UserPrincipalName`

`        $payload | Add-Member -Name 'employeeType' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'extensionAttribute1' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'extensionAttribute2' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'extensionAttribute3' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'extensionAttribute4' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute1' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute2' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute3' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute6' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute7' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute9' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute12' -MemberType Noteproperty -Value ""`
`        $payload | Add-Member -Name 'msDS-cloudExtensionAttribute14' -MemberType Noteproperty -Value ""`

`        if ($Null -ne $user.streetAddress) {`
`            $payload | Add-Member -Name 'streetAddress' -MemberType Noteproperty -Value $user.streetAddress`
`        }`
`        else {`
`            $payload | Add-Member -Name 'streetAddress' -MemberType Noteproperty -Value ""`
`        }`
        
`        if ($Null -ne $user.City) {`
`            $payload | Add-Member -Name 'l' -MemberType Noteproperty -Value $user.City`
`        }`
`        else {`
`            $payload | Add-Member -Name 'l' -MemberType Noteproperty -Value ""`
`        }`
        
`        if ($Null -ne $user.State) {`
`            $payload | Add-Member -Name 'st' -MemberType Noteproperty -Value $user.State`
`        }`
`        else {`
`            $payload | Add-Member -Name 'st' -MemberType Noteproperty -Value ""`
`        }`

`        if ($Null -ne $user.PostalCode) {`
`            $payload | Add-Member -Name 'postalCode' -MemberType Noteproperty -Value $user.PostalCode`
`        }`
`        else {`
`            $payload | Add-Member -Name 'postalCode' -MemberType Noteproperty -Value ""`
`        }`

`        if ($Null -ne $user.FacsimileTelephoneNumber) {`
`            $payload | Add-Member -Name 'facsimileTelephoneNumber' -MemberType Noteproperty -Value $user.FacsimileTelephoneNumber`
`        }`
`        else {`
`            $payload | Add-Member -Name 'facsimileTelephoneNumber' -MemberType Noteproperty -Value ""`
`        }`

`        if ($Null -ne $user.Mobile) {`
`            $payload | Add-Member -Name 'mobile' -MemberType Noteproperty -Value $user.Mobile`
`        }`
`        else {`
`            $payload | Add-Member -Name 'mobile' -MemberType Noteproperty -Value ""`
`        }`

`        foreach ($Ext in ($Exts).keys) {`
`            if ($Ext -like "extension_GUID_employeeType") {`
`                $payload.employeeType = $user.ExtensionProperty.extension_GUID_employeeType`
`            }`

`            if ($Ext -like "extension_GUID_extensionAttribute1") {`
`                $payload.extensionAttribute1 = $user.ExtensionProperty.extension_GUID_extensionAttribute1`
`            }`

`            if ($Ext -like "extension_GUID_extensionAttribute2") {`
`                $payload.extensionAttribute2 = $user.ExtensionProperty.extension_GUID_extensionAttribute2`
`            }`

`            if ($Ext -like "extension_GUID_extensionAttribute3") {`
`                $payload.extensionAttribute3 = $user.ExtensionProperty.extension_GUID_extensionAttribute3`
`            }`

`            if ($Ext -like "extension_GUID_extensionAttribute4") {`
`                $payload.extensionAttribute4 = $user.ExtensionProperty.extension_GUID_extensionAttribute4`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute1") {`
`                $payload."msDS-cloudExtensionAttribute1" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute1`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute2") {`
`                $payload."msDS-cloudExtensionAttribute2" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute2`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute3") {`
`                $payload."msDS-cloudExtensionAttribute3" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute3`
`            }`
 
`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute6") {`
`                $payload."msDS-cloudExtensionAttribute6" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute6`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute7") {`
`                $payload."msDS-cloudExtensionAttribute7" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute7`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute9") {`
`                $payload."msDS-cloudExtensionAttribute9" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute9`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute12") {`
`                $payload."msDS-cloudExtensionAttribute12" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute12`
`            }`

`            if ($Ext -like "extension_GUID_msDS_cloudExtensionAttribute14") {`
`                $payload."msDS-cloudExtensionAttribute14" = $user.ExtensionProperty.extension_GUID_msDS_cloudExtensionAttribute14`
`            }`
`        }`
`        $grandpayload += $payload`
`    }`
`}`

`$squig = @{"value" = $grandpayload}`
`$json = ConvertTo-Json -InputObject $squig`
`$exportfile = $env:temp + "\import.json"`
`$json > $exportfile`


`$Connection = Connect-PnPOnline -AppId $AppID -AppSecret $AppSecret -Url $ImportSiteCollection -Verbose`

`try {`
`    $Upload = Add-PnPFile -Path $exportfile -Folder "Shared Documents" -Verbose -Connection $Connection`
`}`
`catch {`
`    Write-Output "Couldn't add file"`
`    Write-Output $error[0].Exception.Stacktrace`
`}`
