### ISSUE TITLE
Error when loading custom JS files in SPFX webparts 

### ISSUE THREAD

**Issue by reenash027** [SharePoint/sp-dev-docs#2753]
I've given external js path which is sharepoint online application path, still I'm getting load error in SPFx webpart, can anyone suggest

**Comment by Seiyasu** [comment]
Where do you store the external JS? Please provide all your config information. It's better you can provide the reproduce demo code too, so we can further assist you.

**Comment by VesaJuvonen** [comment]
Closed as no response on to @Seiyasu's question.
