### ISSUE TITLE
Hosting ClientSide Webpart from CDN error

### ISSUE THREAD

**Issue by Taerarenai** [SharePoint/sp-dev-docs#2754]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Upload webpart to sharepoint Apps for SharePoint (site collection app catalogue) with `includeClientSideAssets: true
`
The webpart should work.
#### Observed Behavior

Tested on 2 new site collections and i'm getting an error that it cannot load files from ClientSideAssets.
Files do exist. The webpart works fine on a site collection created a while ago.

`Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/`

The console seems to be having Response Headers set as `application/json` and failing to load the file. On the site collection without problems the headers are `application/javascript`.
#### Steps to Reproduce

Create a clean SPFX project, include client side assets, upload to Apps for Sharepoint, install and see the error.

Both site collections are under the same tenant (the one that works & the one that doesnt).

Edit: the error is the same as #1353 , but that one was closed.

**Comment by KingKangMSFT** [comment]
Did you have tried the solution in the comment?

**Comment by Taerarenai** [comment]
Yep, tried everything i could find online till now. (so basically everything in that topic)

**Comment by CharlesLiuMSFT** [comment]
Hi Taerarenai,

Have you review [this](https://github.com/SharePoint/sp-dev-docs/issues/1610)?

If you tried above method and still not able to fix your problem, please let us know.

Thanks

**Comment by VesaJuvonen** [comment]
Closing due to no response. If you see this again, please open a new issue.
