### ISSUE TITLE
Can SP.MoveCopyUtil.MoveFileByPath calls be batched using SPHttpClientBatch?

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#2756]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SP.MoveCopyUtil.MoveFileByPath method should work with the SPHttpClientBatch. I'm able to do a single move using spHttpClient but I've found that I need to set odata-version to 3.0. If I was to try the same using the Batch client, the call would fail.

#### Observed Behavior

I can see that the $batch session returns code 200 but the files don't move. The responses read

> The property '__metadata' does not exist on type 'SP.ResourcePath'. Make sure to only use property names that are defined by the type.

> [HTTP]:400 - Bad Request [CorrelationId]: [Version]:

The modern UI view Move To command batch call looks very similar to the call I get from running my code below. One thing that stands out for me is that my $batch session has this parameter

> accept: application/json

Whereas the SharePoint Move To header has this:

> application/json;odata=verbose

I can set the headers for the calls nested inside the batch call but not on the batch call's own header.

Finally, if I set the odata version to 3.0 (which works with SPHttpClient and I can achieve a single file move), I get the following error.

> The value '3.0' of the OData-Version HTTP header is invalid. Only '4.0' is supported as values for the OData-Version header.

#### Steps to Reproduce

I'm running the code below in the onExecute method of a ListView Command Set extension
```JS
const currentWebUrl: string = this.context.pageContext.web.absoluteUrl;
const spBatchCreationOpts: ISPHttpClientBatchCreationOptions = { webUrl: currentWebUrl };
const spBatch: SPHttpClientBatch = spHttpClient.beginBatch(spBatchCreationOpts);

let bodyOptions0 = {
  "srcPath": {
    "__metadata": {
      "type": "SP.ResourcePath"
    },
    "DecodedUrl": srcFileUrl0
  },
  "destPath": {
    "__metadata": {
      "type": "SP.ResourcePath"
    },
    "DecodedUrl": dstFileUrl0
  }
};

let bodyOptions1 = {
  "srcPath": {
    "__metadata": {
      "type": "SP.ResourcePath"
    },
    "DecodedUrl": srcFileUrl1
  },
  "destPath": {
    "__metadata": {
      "type": "SP.ResourcePath"
    },
    "DecodedUrl": dstFileUrl1
  }
};
const opt0: ISPHttpClientBatchOptions = {
  headers: {
    "Content-Type": "application/json;odata=verbose"
  },
  body: JSON.stringify(bodyOptions0)
};

const opt1: ISPHttpClientBatchOptions = {
  headers: {
    "Content-Type": "application/json;odata=verbose"
  },
  body: JSON.stringify(bodyOptions1)
};
const moveDoc0 = spBatch
  .post(
    `${currentWebUrl}/_api/SP.MoveCopyUtil.MoveFileByPath()`,
    SPHttpClientBatch.configurations.v1,
    opt0
  );

const moveDoc1 = spBatch
  .post(
    `${currentWebUrl}/_api/SP.MoveCopyUtil.MoveFileByPath()`,
    SPHttpClientBatch.configurations.v1,
    opt1
  );

spBatch
  .execute()
  .then(() => {
    moveDoc0
      .then((response: SPHttpClientResponse) => {
        console.log('response0: ', response);

        response.json()
          .then((props: any) => {
            console.log('props0: ', props);
          });
      });

    moveDoc1
      .then((response: SPHttpClientResponse) => {
        console.log('response1: ', response);

        response.json()
          .then((props: any) => {
            console.log('props1: ', props);
          });
      });
  });
```

**Comment by Seiyasu** [comment]
What is the response header/body and what is the output of console log?

**Comment by semopz** [comment]
There's no errors shown on the console but I've included a screenshot of the console logs from the code snippet in my OP. I assume you need both response and request headers? I've truncated what I think is unnecessary for brevity.

> Response header/body as requested
> ### Request Header

> :authority: <snip>.sharepoint.com
> :method: POST
> :path: /sites/<snip>/_api/$batch
> :scheme: https
> accept: application/json
> accept-encoding: gzip, deflate, br
> accept-language: en-US,en;q=0.9
> cache-control: max-age=0
> content-length: 1171
> content-type: multipart/mixed; boundary=batch_aab9d10b-56c8-46ee-8f69-8c140ff7285d
> cookie: databaseBtnText=0; databaseBtnDesc=0; stsSyncAppName=Client; stsSyncIconPath=; MicrosoftApplicationsTelemetryDeviceId=e5106212-a131-4aa4-9a45-39015cd01626; MicrosoftApplicationsTelemetryFirstLaunchTime=2018-10-16T10:56:59.268Z; rtFa=<snip>; odbn=1; WSS_FullScreenMode=false; FedAuth=<snip>; SPWorkLoadAttribution=Url=https://<snip>.sharepoint.com/sites/<snip>/_api/web/GetList(@listUrl)/RenderListDataAsStream&AppId=E0D3C05D-9133-40D1-8413-1C4522A4E7C2
> odata-version: 4.0
> origin: https://<snip>.sharepoint.com
> referer: https://<snip>.sharepoint.com/sites/<snip>/Folders/Forms/AllItems.aspx?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests%2Ejs&loadSPFX=true&customActions=%7B%22411396f4%2D7237%2D4fbc%2D986a%2D636586e983cf%22%3A%7B%22location%22%3A%22ClientSideExtension%2EListViewCommandSet%22%2C%22properties%22%3A%7B%22sampleTextOne%22%3A%22One%20item%20is%20selected%20in%20the%20list%22%2C%22sampleTextTwo%22%3A%22This%20command%20is%20always%20visible%2E%22%7D%7D%7D&sortField=LinkFilename&isAscending=false
> user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
> x-requestdigest: <snip>,16 Oct 2018 13:38:13 -0000

> ### Response Header

> cache-control: private, max-age=0
> content-disposition: attachment
> content-type: multipart/mixed; boundary=batchresponse_7143ff7b-6b24-45a6-ae49-344a575ddb96
> date: Tue, 16 Oct 2018 13:40:42 GMT
> expires: Mon, 01 Oct 2018 13:40:42 GMT
> last-modified: Tue, 16 Oct 2018 13:40:42 GMT
> microsoftsharepointteamservices: 16.0.0.8203
> ms-cv: npj0hIOgAHAa82X7t6h6hw.0
> odata-version: 4.0
> p3p: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
> request-id: 84f4989e-a083-7000-1af3-65fbb7a87a87
> set-cookie: FedAuth=<snip>; expires=Sun, 21-Oct-2018 13:24:49 GMT; path=/; secure; HttpOnly
> set-cookie: SPWorkLoadAttribution=Url=https://<snip>.sharepoint.com/sites/<snip>/_api/$batch&AppId=E0D3C05D-9133-40D1-8413-1C4522A4E7C2; expires=Tue, 16-Oct-2018 13:41:12 GMT; path=/
> set-cookie: SPWorkLoadAttribution=Url=https://<snip>.sharepoint.com/sites/<snip>/_api/$batch&AppId=E0D3C05D-9133-40D1-8413-1C4522A4E7C2; expires=Tue, 16-Oct-2018 13:41:12 GMT; path=/
> set-cookie: rtFa=<snip>; domain=sharepoint.com; expires=Sun, 21-Oct-2018 13:24:49 GMT; path=/; secure; HttpOnly
> spclientservicerequestduration: 23
> sprequestduration: 53
> sprequestguid: 84f4989e-a083-7000-1af3-65fbb7a87a87
> status: 200
> strict-transport-security: max-age=31536000
> x-aspnet-version: 4.0.30319
> x-content-type-options: nosniff
> x-download-options: noopen
> x-frame-options: SAMEORIGIN
> x-ms-invokeapp: 1; RequireReadOnly
> x-msedge-ref: Ref A: 0F9A479C1575444FA6EF7182AF94958C Ref B: LON21EDGE0121 Ref C: 2018-10-16T13:40:42Z
> x-powered-by: ASP.NET
> x-requestdigest: <snip>,16 Oct 2018 13:40:42 -0000
> x-sharepointhealthscore: 1
> x-sp-serverstate: ReadOnly=0

> ### Response Body
> --batch_aab9d10b-56c8-46ee-8f69-8c140ff7285d
> Content-type: application/http
> Content-Transfer-Encoding: binary
> 
> POST https://<snip>.sharepoint.com/sites/<snip>/_api/SP.MoveCopyUtil.MoveFileByPath() HTTP/1.1
> accept: application/json;odata=verbose
> content-type: application/json;oodata=verbose
> 
> {"srcPath":{"__metadata":{"type":"SP.ResourcePath"},"DecodedUrl":"https://<snip>.sharepoint.com/sites/<snip>/Folders/F2.txt"},"destPath":{"__metadata":{"type":"SP.ResourcePath"},"DecodedUrl":"https://<snip>.sharepoint.com/sites/<snip>/Folders/Dest folder/F2.txt"}}
> 
> --batch_aab9d10b-56c8-46ee-8f69-8c140ff7285d
> Content-type: application/http
> Content-Transfer-Encoding: binary
> 
> POST https://<snip>.sharepoint.com/sites/<snip>/_api/SP.MoveCopyUtil.MoveFileByPath() HTTP/1.1
> accept: application/json;odata.metadata=full
> content-type: application/json;oodata.metadata=full
> 
> {"srcPath":{"__metadata":
> {"type":"SP.ResourcePath"},"DecodedUrl":"https://<snip>.sharepoint.com/sites/<snip>/Folders/F1.txt"},"destPath":{"__metadata":{"type":"SP.ResourcePath"},"DecodedUrl":"https://<snip>.sharepoint.com/sites/<snip>/Folders/Dest folder/F1.txt"}}
> 
> --batch_aab9d10b-56c8-46ee-8f69-8c140ff7285d--
> 
> 

[https://i.imgur.com/KF1Ho5T.png](console log screenshot)

**Comment by Seiyasu** [comment]
Please change the bodyOptions0 and bodyOptions1 to the following code, it works well on my side: 
let bodyOptions0 = {
        srcPath: {
               DecodedUrl: srcFileUrl0
        },
       destPath: {
              DecodedUrl: dstFileUrl0
       }
}; 
let bodyOptions1 = {
       srcPath: {
              DecodedUrl: srcFileUrl1
       },
      destPath: {
             DecodedUrl: dstFileUrl1
};

**Comment by semopz** [comment]
Ok that kind of works but I get an error on the execute method.
This is what I get a in the catch

> TypeError: Failed to construct 'Response': Response with null body status cannot have body
>     at e._parseResponsesFromBody (listview-host-assembly_default_35738d0f0518e801c91a02fcc1966538.js:563)
>     at listview-host-assembly_default_35738d0f0518e801c91a02fcc1966538.js:563

This is what I get in the console
2 times this:

> Uncaught (in promise) TypeError: This request was part of an SPHttpClientBatch that failed
>     at listview-host-assembly_default_35738d0f0518e801c91a02fcc1966538.js:563


The documents move fine though but 
```javascript
.execute().then(() => {// nothing in here runs}).catch(error => {// this runs instead})
```
I had a typo in my headers so now I'm just using "Content-Type": "application/json;odata=verbose" (doesn't make a difference either way).

BTW, the OOTB MoveTo modern experience uses the {"__metadata":{"type":"SP.ResourcePath"} information when I look at the request batch body so that's why I was trying to do it that way as well.

**Comment by Seiyasu** [comment]
The execute works well with response id 204 and without response body. You are try to convert the value, so you get the exception.  

 **Response with null body status cannot have body**

**Comment by semopz** [comment]
I'm sorry I don't understand how to avoid getting the exception? What value do I need to convert and how do I convert it?

**Comment by Seiyasu** [comment]
moveDoc1
      .then((response: SPHttpClientResponse) => {
        // The reponse is null. So you should not do any logic on it. Instead, you need to put your own logic here. Such as   console.log('response0: ', "Success");
   
  });

And handle the exception on the exception.

**Comment by semopz** [comment]
I'm currently trying to just do a console log just after .execute().then(() => { and nothing gets logged, goes straight to catch. Also, I'm getting a 200, not 204 (unless I'm looking in the wrong place)
![](https://i.imgur.com/Ax1w1ew.png)

**Comment by Seiyasu** [comment]
No matter 200 or 204, all means success. I get the 204 on my side. If you get 200, you can see what is the content in the response body. And you need to handle both 200 and 204 in your code.

**Comment by semopz** [comment]
Not sure how to handle it. Could you paste in the code that gives you the 204 so I can try it as well?
```javascript
spBatch
  .execute()
  .then(() => {
     console.log('it worked'); //does not get logged
  })
  .catch((responseError) => {
    console.log('did not work'); //this gets logged
  });

```

**Comment by Seiyasu** [comment]
I just use the code you provided.

**Comment by semopz** [comment]
I've tried my original code and as well but I just can't get a 204 and none of the console log commands run that I've inserted _before_ opening up the individual responses. The exception happens at execute(). The exception for me does not happen in 'my' code i.e. execute().then(() => //nothing happens here). Yet the batch operation returns 200...

**Comment by semopz** [comment]
Ok I've simplified this as much as I can. I've just pasted the below code in the render method of a HellowWorld webpart in HelloWorldWebPart.ts. So as soon as you drop the webpart on a page, it fires off the action.
```typescript
    const currentWebUrl: string = this.context.pageContext.web.absoluteUrl;
    const spBatchCreationOpts: ISPHttpClientBatchCreationOptions = { webUrl: currentWebUrl };
    const spBatch: SPHttpClientBatch = this.context.spHttpClient.beginBatch(spBatchCreationOpts);
    let srcFileUrl0 = `<Old File Path>`;
    let dstFileUrl0 = `<New File Path>`;
    let bodyOptions0 = {
      "srcPath": {
        "DecodedUrl": srcFileUrl0
      },
      "destPath": {
        "DecodedUrl": dstFileUrl0
      }
    };

    const opt0: ISPHttpClientBatchOptions = {
      headers: {
        "Content-Type": "application/json;odata=verbose"
      },
      body: JSON.stringify(bodyOptions0)
    };

    const moveDoc0 = spBatch
      .post(
        `${currentWebUrl}/_api/SP.MoveCopyUtil.MoveFileByPath()`,
        SPHttpClientBatch.configurations.v1,
        opt0
      );

    spBatch
      .execute()
      .then(() => {
        console.log(`Yay, it worked`);
      })
      .catch(batchError => console.log(`Batch Error: `, batchError));
```

My batch session returns a response of 200 (not 204) and on the console I see this:
[](https://i.imgur.com/OyLHk5r.png)
Whatever I'm doing wrong, I just can't spot it.

**Comment by Seiyasu** [comment]
> Can SP.MoveCopyUtil.MoveFileByPath calls be batched using SPHttpClientBatch? 
Your initial question have been fix. 

Your latest question is not related to the original, it'd better you submit new issue, so any one else can help you and retrieved it easier for other people

**Comment by semopz** [comment]
Done
https://github.com/SharePoint/sp-dev-docs/issues/2857
