### ISSUE TITLE
SharePoint PnP JavaScript Core library URL

### ISSUE THREAD

**Issue by YardGnomeNinja** [SharePoint/sp-dev-docs#2757]
The current URL points to a deprecated repository (https://github.com/SharePoint/PnP-JS-Core), please update to the new repository https://github.com/pnp/pnpjs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142aa03b-97e7-1755-bf21-dcda38a6fe24
* Version Independent ID: 5516201f-4576-16c9-b5bb-39fee234506a
* Content: [SharePoint Framework development tools and libraries](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tools-and-libraries)
* Content Source: [docs/spfx/tools-and-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tools-and-libraries.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post.
