### ISSUE TITLE
Is it possible to add comments to modern list item

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#2759]
Hi Everyone, 

Is it possible to add comments to modern list item like modern page comments? 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Thank you

**Comment by Seiyasu** [comment]
You can add one column in the List to store the comment and use the Field Customizer to show the comment. It should not have directly and official support on this.

**Comment by muges01** [comment]
Hi @Seiyasu ,

Thank you for your suggestion, but this will not shows how many comments i have and also to enable the user to enter the comments similar as the page comments. 

Is there any way that i can implement a custom solution same as page comments on a list using custom SPFx solution or using REST API calls?

**Comment by Seiyasu** [comment]
There are no directly way on the List page. But a possible workaround, add your list as webpart in a Page, and add custom SPFx which handle comments and views in the page too

**Comment by muges01** [comment]
Ok thank you @Seiyasu...
