### ISSUE TITLE
Invalid App Packages?

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#276]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Upload a packaged .spapp file to the SharePoint App Catalog and get a valid app package.

#### Observed Behavior
As of recently, uploading previously valid .spapp packages built with Drop 5 to the app catalog results in an invalid app package. 

#### Steps to Reproduce
Using drop 5, use Yoeman to generate the Hello World app. Build with gulp package-solution and upload the .spapp to the app catalog. The catalog indicates that the package is invalid.

**Comment by patmill** [comment]
Hi Jared - can you go to the app catalog list and add the column that shows what the error is?  The column is "App Package Error Message".  What does the error say?

**Comment by jaredbuttars** [comment]
The error is "No errors."

**Comment by jaredbuttars** [comment]
Here's a screenshot. Two apps uploaded today are not valid. The one at the base was a replaced app, the hello world at the top was new. Any apps installed a while back, using the same build process, are valid.

![packages](https://cloud.githubusercontent.com/assets/3818517/20283331/c6ad5628-aa75-11e6-977e-6cea3d009114.png)

**Comment by mcmynn83** [comment]
Can you let us know what your site collection URL is so we can verify that the feature should be enabled?

**Comment by jaredbuttars** [comment]
Tenant from Dev Kitchen.

a830edad9050849spdk3024.sharepoint.com/sites/sj/

**Comment by jaredbuttars** [comment]
Running into the same problem on our production O365 that is set for First Release and supposedly has SPFx since Nov. 11 according to our notifications.

**Comment by mcmynn83** [comment]
The change is still rolling out to production tenants for First Release so that is expected that it is not working at this time... The reason your other tenant is no longer working is some changes were made to the flights included as part of the rollout to First Release.  I am re-enabling it for that farm and will respond once has been reverted.

**Comment by mcmynn83** [comment]
Hi Jared, Please let me know if you are still experiencing the issue on your dev kitchen tenant.  The changes that were made to start the rollout of first release that affected your tenant have been fixed now.

**Comment by GaryLStewart** [comment]
I'm running into the same issue as Jared.  I'm working through the Hello World tutorial for SPFx, and when I upload the app to my App Catalog, it shows that it is not a valid app package, but provides no app package error message.  I'm on O365 set up for First Release.

**Comment by mcmynn83** [comment]
Hi Gary,
It is still in the process of rolling out to First Release so it is not expected yet to be enabled for all tenants on First Release.

**Comment by GaryLStewart** [comment]
Thanks - any idea on when it will enabled?

**Comment by mcmynn83** [comment]
My best guess is about 2-4 days.

**Comment by arutjothi** [comment]
I'm running into the same problem...We are signed up for "First release for selected users"...

**Comment by clechner77** [comment]
Same here.  I could have sworn it worked in production yesterday... but today, no dice.  Guess there's still some wrinkles to iron out.

**Comment by patmill** [comment]
Trying to track down the issue here.  @clechner77 - did you have a developer tenancy that stopped working?  A dev-kitchen tenancy?  Just wondering what you had previously, and when it was working and when it stopped.  Some first release tenants have it, and other farms are still pending the update.
Thanks.

**Comment by jaredbuttars** [comment]
@mcmynn83 I can confirm that the fix you did for the dev kitchen tenant worked.

Thank you!

**Comment by jaredbuttars** [comment]
@mcmynn83 I'm still having some trouble. Now the app package installs fine in the catalog but when I add the app to a site it tells me the version of the app is already installed and to remove it from the site and the site recycle bin. I do that but still get the error.

**Screenshots from the Dev Kitchen site**

![problem-step-1](https://cloud.githubusercontent.com/assets/3818517/20407162/5f50a6ec-accd-11e6-99ea-8352e74b638a.png)
![problem-step-2](https://cloud.githubusercontent.com/assets/3818517/20407169/676b8202-accd-11e6-986a-1dc27343f270.png)

Also, the same app package now installs fine into the app store of our First Release tenant, but when trying to add the app to any of the First Release Sites I get a different error but still an error.

**Screenshots from the First Release site**

![problem-step-1-firstrelease](https://cloud.githubusercontent.com/assets/3818517/20407233/af6963bc-accd-11e6-8b22-4b1d625555f8.png)
![problem-step-2-firstrelease](https://cloud.githubusercontent.com/assets/3818517/20407236/b2c0d98c-accd-11e6-95d9-d9b955bd8719.png)

**Comment by mcmynn83** [comment]
Hi Jared,
I'm sorry you are having problems.  Could you please click the technical details and send a screen shot back (or just give me the correlation ID you get when you click the technical details button)?

As for the 1st error you saw, when you said you deleted the app from the recycle bin, there are 2 stages to the recycle bin. First you would have to go and delete from the recycle bin, then you would have to go to site settings -> Site Collection Administration -> Recycle bin -> "Check the second-stage recycle bin" and remove your app from there (or shortcut the process by going to this URL: _layouts/5/AdminRecycleBin.aspx?View=2).  If you actually removed from both places I will need the correlation ID (ie click the technical details and include that correlation ID).

Thanks,
Graham

**Comment by clechner77** [comment]
@patmill -- Sorry, got caught up.  My dev tenant is still functional.  I was referring to prod/first release that mysteriously went back in time.

**Comment by patmill** [comment]
@clechner77 - were you previously able to activate it on the first release tenant, or were you just accessing the hosted workbench pointing at your local gulp serve (ie, no package deployment)?

**Comment by clechner77** [comment]
@patmill -- I was speaking with another guy on our team and he didn't see it working on our prod tenant and thinks I might have been been on the dev tenant instead.  Like I said, I could have sworn it was the prod tenant but now I'm second guessing myself.  I know.... not very helpful.

**Comment by jaredbuttars** [comment]
@mcmynn83 I went through and cleared all apps from the app store site including from both recycle bins. I then removed all apps from a test site on the same tenant including removal from both recycle bins. I then created a fresh "yo @microsoft/sharepoint" and built an spapp with "gulp bundle --ship" and "gulp package-solution --ship". A CDN container was created and assets were deployed to Azure. The installation on the app site went smoothly. I was also able to add the app to the test site. Everything seemed to work without a problem.... until

**Modern pages**
"There was an error fetching the web parts. Not all web parts may be available."
The hello world web part is not available in the list.
![01-notallparts](https://cloud.githubusercontent.com/assets/3818517/20457471/724cf14c-ae49-11e6-9a56-5e5524a731ed.png)

**Classic Pages**
All of the web parts that were _completely removed_ from the site are still listed in the ribbon web part selector.
![02-oldparts](https://cloud.githubusercontent.com/assets/3818517/20457477/bca1704c-ae49-11e6-9c4f-7de35c2b30d8.png)

After adding the new Hello World web part to a classic page I get an error.
"The value for 'webpart context configureStart' must not be undefined"
![03-classichello](https://cloud.githubusercontent.com/assets/3818517/20457498/093f4ee2-ae4a-11e6-9462-6b781519ca01.png)

**Comment by clechner77** [comment]
So from what I gather, "There were errors when validating the App Package" when adding it to a site is due to not everything being pushed to my tenant yet.

**Comment by clechner77** [comment]
@mcmynn83 Is "there were errors when validating the app package" still a waiting game for the completion of the rollout or are there potentially other issues?  Same package works fine in dev tenant but not on First Release when adding to a site.

**Comment by mcmynn83** [comment]
@jaredbuttars - the apps showing up in classic even after deleting has been fixed but not rolled out.  It probably will not make it to customers environments until early December.  The issue with webparts not showing up in modern pages has been fixed and should already not be reproing for you.  If you still see that issue please let me know.  The issue with configureStart must not be undefined is new to me.  By any chance could you send me your app package?  My alias at Microsoft is GrahaMc.

@clechner77 - If you send me your tenant info I can tell you whether it is a waiting game or another issue.  Without any further info I can only guess.  GrahaMc is my alias at Microsoft if you don't want to post your tenant info on this forum.

**Comment by clechner77** [comment]
@mcmynn83 -- no issues, our tenant is mlmins

**Comment by jaredbuttars** [comment]
@mcmynn83 -- The changes that were made to allow web parts to show up on modern pages seems to have also fixed the context configureStart error I was getting on classic pages. All seems well in our dev tenant. Thank you!

I continue to have an issue on our first release tenant. The app package uploads to the app store and deploys fine. The trouble comes during install to a site. I click "Trust It" then I get an error page with the following message:

```
Sorry, something went wrong
There were errors when validating the App Package.
TECHNICAL DETAILS

Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: 72ecb99d-2036-3000-d4a9-97dc149b19e4

Date and Time: 11/22/2016 7:14:32 AM
```
This error is on the site at:
https://office365lds.sharepoint.com/sites/jbuttars/

**Comment by mcmynn83** [comment]
Hi Clint,
So the good news is it is not a waiting game.  The patches have rolled out to the farm you are on.  However, that leaves the question of why is your package not validating.  If you go into the view on the app catalog you can modify the fields in the view to include App Package Error Message.  That should hopefully  give you more detail into what is going wrong.  Let me know if that helps at all.

Thanks,
Graham

**Comment by mcmynn83** [comment]
@jaredbuttars - Thank you for reporting this and giving me the information I needed to investigate the issue.  It looks like we may be having further issues with the First Release tenants roll out (a different problem this time).  I am looking into it now and will keep this thread updated.

**Comment by mcmynn83** [comment]
I need to make  a change to how First Release tenants are checked so that again will take a few days to roll out to all of the production farms.  Until then I have to disable the feature, so everybody will start seeing invalid app package on First Release tenants when uploading a client side solution (dev tenants will continue to work).  The current ETA for it being enabled (and actually working this time) for FirstRelease tenants is 4-5 days (basically as farms get patched it will start working).

Sorry about the delays and thank you for reporting the problem.

**Comment by NickSevens** [comment]
Hello, I am experiencing the same (?) issue at a customer right now.
What exactly can I do to check everything is setup correctly at tenant-side?
Uploading a package to my DEV tenant works, but not on the customer's.

**Comment by Bhavya-Chhabra** [comment]
Hi mcmynn83,

I am facing the same issue while uploading the app package for our SPFx client side webpart to our customer tenant. The app package shows as valid when we upload to dev tenants but not when we upload to our customer tenant which has first release set to selected users only. I got my account added to the list of these selected users as well and tried uploading the app , but the same issue still occurs. The 'App Package Errors' column is also empty. Please let us know if there us any ETA for this fix as we are running against timelines for delivering this functionality.

Thanks,
Bhavya

**Comment by patmill** [comment]
Select users in first release is not sufficient. It needs to be tenant wide first release.

________________________________

**Comment by MaheshakaMudli** [comment]
I am facing the same issue. What needs to be done in existing tenant for the SharePoint Framework .spapp file to get deployed in AppCatalog. it is showing Invalid in existing Tenant and working properly in new tenant? My existing tenant has First Release for selected users as enabled. Any help would be really appreciated.

**Comment by mcmynn83** [comment]
@MaheshakaMudli - as per stated in the last response to this thread:
Select users in first release is not sufficient. It needs to be tenant wide first release.

That means either you will have to wait for the feature to be release everywhere or enable tenant wide first release.  Please let me know if you determine that your new tenant is in the user only First Release but it actually works for them.  That would be unexpected.

Thanks,
Graham

**Comment by Bhavya-Chhabra** [comment]
Hi @mcmynn83,

Thanks for your response earlier. As per the latest update from Microsoft , we got to know that the General availability release of SharePoint Framework is available now which has fixed this problem. Microsoft has started rolling it out to all tenants now. I just wanted to ask if there is any date/timeline by when this GA release will be deployed to all tenants worldwide? We checked our tenant and the SharePoint framework app packages are still showing as invalid which means that the GA release is not applied on our tenant till now.

Thanks,
Bhavya

**Comment by jonathanhotono** [comment]
![image](https://cloud.githubusercontent.com/assets/6864547/23649078/2bd1e01a-0371-11e7-8aa9-d8191e002be8.png)
I am still experiencing the same issue on my tenant. Tried to upload it on another tenant and it works well. I contacted MS support and the support guy said they don't have any solution guide for SPFX yet.

**Comment by sprider** [comment]
We are facing the same issue in our development tenant. But everything works fine in test tenant.

**Comment by patmill** [comment]
We should be at 50% of tenants this week, and 100% next week.  Appreciate your patience.

**Comment by sprider** [comment]
Sure, Thank you

**Comment by sprider** [comment]
@patmill 

Is it done on all the tenants?

**Comment by Antonio-Bacar** [comment]
Hello,
When I deploy SPFx package to SharePoint 2016 on premise, I get an error of faulty package with a message: There were errors when validating the App manifest.: Xml Validation Exception: 'The 'SkipFeatureDeployment' attribute is not declared.' on line '1', position '276'.

In the debug folder ( files generated in the package put separately ) I find AppliationManifest.XML with following content:
<?xml version="1.0" encoding="utf-8"?>
<App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" 
 Name="helloworld-client-side-solution" 
 ProductID="4e89d531-dc9d-4342-ab77-48a202684f0a" Version="1.0.0.0" 
 SharePointMinVersion="16.0.0.0" 
 IsClientSideSolution="true" 
 SkipFeatureDeployment="true">
  <Properties>
   <Title>helloworld-client-side-solution</Title>
  </Properties>
</App>

As you can see, and I checked in config/package-solution.json and the property is initialized as shown in ApplicationManifest.xml.

What is the solution to this problem? Thank you in advance,

Antonio.

**Comment by mcmynn83** [comment]
@Antonio-Bacar - Could you please open a new thread with this request.  That being said, did you choose an on-prem package from Yeoman?  Skip Feature Deployment is not supported on the on prem release at this time.  The on prem yeoman generator should not be including that attribute.
