### ISSUE TITLE
Couldn't edit page properties for a modern page in a folder 

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#2760]
Hi everyone,

I'm getting an error when I'm trying to edit a page property for a modern page inside a folder.

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm expecting that i can edit the page property using the top navigation bar on the page when it is in edit mode.

#### Observed Behavior
I'm getting the following error when I try to edit the page property using the top navigation bar when it is in edit mode.

![image](https://user-images.githubusercontent.com/22563887/46909021-ae4eb980-cf23-11e8-8509-43c346dab23c.png)

but when i'm not getting any error when edit page property from the context menu

![image](https://user-images.githubusercontent.com/22563887/46909101-00440f00-cf25-11e8-95da-ddfab6efa6b2.png)

#### Steps to Reproduce

1. Add a folder inside the site pages library
2. Add a page inside the folder
3. Edit the page and edit the page property from page context menu
![image](https://user-images.githubusercontent.com/22563887/46909074-962b6a00-cf24-11e8-8d0c-bd27459057b1.png)

Thank you

**Comment by KingKangMSFT** [comment]
As this is out-of-the-box functionality, we can't route this through the dev process. 
Please submit this through the SharePoint Online admin support channels from the tenant admin tool. 
We can only support dev topics through this issue list. Sorry for the inconvenience.
