### ISSUE TITLE
*.tsx files are not listed in tsconfig.json

### ISSUE THREAD

**Issue by muradaliyev** [SharePoint/sp-dev-docs#2762]
Looks like *.tsx files are not listed in include clause of tsconfig.json (SPFX 1.6 default "React" project). Because of that, these files appear as not part of the project and any objects referenced in them are not picked up by intellisense and not shown in the list of fixes. 
Addin *.tsx into "include" clause seems to fix the problem.

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Classes/vars referenced in *.tsx files should be picked up by intellisense and appear in the list of "fixes" in VS Code

#### Observed Behavior

Newly-created *.tsx files are not part of project. Any class or var created in these files will not be shown in the list of"fixes"

#### Steps to Reproduce

- Create new SPFX 1.6 React Library project
- Create new *.tsx file and create new class
- Reference this class in other module without adding it to "import" statement. Normally VS code should pick it up and show a "fix" bulb, but it does not do it

**Comment by Seiyasu** [comment]
I can repro this.

**Comment by patmill** [comment]
Sorry for not updating this.  This issue has been fixed a while ago.
