### ISSUE TITLE
i got "File Not Found"

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#2763]
i got "File Not Found", any hints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac83aaa-403c-bbb5-1381-9e1e39913e41
* Version Independent ID: 6cb358f2-72b2-aa3d-6ac4-48352f199eda
* Content: [Add a web part to a page in a SharePoint-hosted SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thanks @peterremote1980 , could you please provide more information about your issue? such as what did you do and what is the problem.

**Comment by VesaJuvonen** [comment]
Closing due to no response.
