### ISSUE TITLE
on keydown 'Tab' event key not being detected when page is published

### ISSUE THREAD

**Issue by paigeflourin** [SharePoint/sp-dev-docs#2766]
#### Category
- [x ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

the Tab event should be fired perfectly fine.

#### Observed Behavior

it is working on the site workbench, and on the edit page of the site page where the app is deployed. but when i publish it, the tab event is not being captured and nothing happens. i have tried

#### Steps to Reproduce

> https://github.com/paigeflourin/test

i created an spfx app and i have a form that inputs multiple items like so: 

![screen shot 2018-10-15 at 8 30 45 am](https://user-images.githubusercontent.com/6951524/46924915-7c407300-d05b-11e8-8561-6cc141bd7dc7.png)

i am capturing the keydown press through:
```

 switch (event.key) {
        case 'Enter':
          this.setState({
            inputValue: ''
          });
          this.props.onChange([...value,createOption(inputValue)]);
          event.preventDefault();
          break;
        case 'Tab':
          this.setState({
            inputValue: '',
          });
          this.props.onChange([...value,createOption(inputValue)]);
          event.preventDefault();
          break;
        default:
            return null;
      }
```
it is working on the site workbench, and on the edit page of the site page where the app is deployed. but when i publish it, the tab event is not being captured and nothing happens. i have tried

```
if (e.keyCode === 9) {
    e.preventDefault();
    // code here
  }
```
but still it is not working, i am not sure why it's only not working when the page is published. this is the rendered code of the deployed app:

```
t.handleKeyDown = function(e) {
                    var n = t.state.inputValue
                      , r = t.props.value;
                    switch (e.key) {
                    case "Enter":
                    case "Tab":
                        t.setState({
                            inputValue: ""
                        }),
                        t.props.onChange(r.concat([We(n)])),
                        e.preventDefault();
                        break;
                    default:
                        return null
                    }
                }

```

is there a conflict with the Tab key on spfx when published?

**Comment by Seiyasu** [comment]
What is the data structure in your api service? I think it should be better convert it to Mock data and add the data to the demo project.

**Comment by paigeflourin** [comment]
Hi @Seiyasu the table where i am using this component is not being affected by the api service. apologies, i am not sure i am getting the last part of what you said

**Comment by Seiyasu** [comment]
So it should better you can provide an minimized reproduce project. In your current project, "API Service Endpoint URL" must be set, but due to invalid endpoint, the data will always in loading. People who want to assist you have to modify the logic by ourselves and try to reproduce.

**Comment by paigeflourin** [comment]
Hi @seiyasu apologies. Will update the code for the service url

**Comment by jxnx888** [comment]
Hello @paigeflourin , if it's possible, could you please provide a Mock information for "QnA Master List Name", "QnA List Tracking List Name", "API Service Endpoint URL" and "QnAMaker Knowledge Base Id" ASAP?

**Comment by jxnx888** [comment]
Hi @paigeflourin, I followed your reproduction steps, I still cannot run the sample, if it is possible, could you please tell me what are the columns under the QnA Master List Name, or any other notice?
I have to achieve the form that inputs multiple items in your step1, in order to test the Tab.
