### ISSUE TITLE
Loading indicators are always hidden for SPFx client side web part 

### ISSUE THREAD

**Issue by araLT** [SharePoint/sp-dev-docs#2771]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

If calling the following method from inside SPFx client side web partm it must render loading indicator inside given DOM element (first parameter):
this.context.statusRenderer.displayLoadingIndicator(domElement, "Some text", 1);

#### Observed Behavior

Today I noticed, that the mentioned call does not render display loading indicator anymore (at least several days ago it works as expected). Also I noticed, that SPFx client side web part loading indicator (displayed before web part is ready to be rendered) also does not show. Actually loading indicator is rendered, but it remains hidden (css display style of loading indicator div remains "none").

#### Steps to Reproduce

Just create simplest SPFx client side web part and inside web part render method write the following code (it creates empty div element and tries to render loading indicator inside that div):

let domElement = document.createElement("div");
this.domElement.appendChild(domElement);
this.context.statusRenderer.displayLoadingIndicator(domElement, "Some text", 1);

**Comment by KingKangMSFT** [comment]
I have tried this, and my code like this:
`    let domElement = document.createElement("div");
    this.domElement.appendChild(domElement);
    this.context.statusRenderer.displayLoadingIndicator(domElement,"Loading Text...",900);`

and the result like this:
![image](https://user-images.githubusercontent.com/42561755/47056603-c5293080-d1ef-11e8-86b1-20feda48d112.png)

Could you please provide the version of SPFx ? And did you debug the webpart?

**Comment by araLT** [comment]
I have again checked and it starts working again!
