### ISSUE TITLE
Placeholders not appearing on page intermittently

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#2773]
This is happening in one out of several tenancies and doesn't seem to be an issue across the board yet.

Our application customizers are not loading each time because the placeholders do not exist.

The following code:
console.log('Available placeholders: '+
      this.context.placeholderProvider.placeholderNames.map(name => PlaceholderName[name]).join(', '));

Returns nothing after a page refresh. However it does work again after a hard refresh (sometimes). Usually the returns the Top and Bottom placeholders every time.

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

**Comment by CloudDesignBox** [comment]
Now getting this for more tenants this afternoon....maybe a bug has been introduced??

**Comment by dgusoff** [comment]
Also seeing this on multiple tenants. A resize event causes the placeholders to come back.

**Comment by MaartenSundman** [comment]
I noticed this first around 11:30am PST today. Hopefully my workaround can get people going while a real fix is done :)

**Comment by tdwhite0** [comment]
This is definitely spreading, taking down tons of tenants for me. The promise of Placeholders being a place where you could always rely on being there is not true. Between stuff like this and buggy in place navigation you are better off injecting your own div. Really disappointing to have to have fire drills like this and explain to clients that SPFX can break underneath you at any time.

**Comment by patmill** [comment]
Chatting with some folks internally - There is some code rolling out that can cause things to behave slightly different (or slightly slower) in some cases.  The correct / best-practice in dealing with the PlaceHolders is code that looks like this:

**Comment by AronHowarth** [comment]
This issue for us anyway is present for modern pages, strange thing is that the add in works on the Contents page of the sites.  started at around 10:00 NZDT

**Comment by AronHowarth** [comment]
This issue for us anyway is present for modern pages, strange thing is that the add in works on the Contents page of the sites.  started at around 10:00 NZDT

**Comment by CloudDesignBox** [comment]
@patmill thank you for the update and your quick feedback. I guess we have all been  basing our code using the samples on the SPFx documentation site which has since changed to include event code. I'll give that a go tomorrow. Thanks again!

**Comment by patmill** [comment]
This should also set you up for future improvements in app customizers, where we can start executing code earlier (like before the page has rendered).

**Comment by CloudDesignBox** [comment]
Great, looking forward to all the new stuff we can do in the new versions in 1.6 and 1.7! I'll close this issue now and reopen if the fix doesn't resolve.

**Comment by mpowney** [comment]
We observed this same problem with a number of clients at start of business today (~3 hours ago). We raised a couple of support tickets (one per customer), and the issue is now no longer coming up. 

We're now looking at changing code for active customers to use the new changedEvent pattern for app customizers, but to do this retrospectively for all customers is a bit of a stretch support-wise.

We also noticed, with some customers using SPFx web parts on classic pages, web parts using specific react related libraries were failing load on classic pages - the fix there was to update to newer versions of the libraries. But, I reckon something's been rolled back on the platform because those web parts have fixed themselves with no code changes on our part.

**Comment by dgusoff** [comment]
@mpowney : _We're now looking at changing code for active customers to use the new changedEvent pattern for app customizers, but to do this retrospectively for all customers is a bit of a stretch support-wise._

Well stated and I agree completely. That said I also see functionality restored. Looks like somebody scrambled to roll back an update.

**Comment by patmill** [comment]
Hey Marc - is it possible to share what react libraries you are using in classic, and how they are getting loaded?  We are trying to roll out support for react 16, and found some strange errors in some classic scenarios. It looks like people are using a weird mix of react 15 and 16 that we can't repro. For now we are including some react 15 functionality in the 16 code, which "fixes" the errors, but seems wrong.
________________________________

**Comment by mpowney** [comment]
The library was [react-slick](https://www.npmjs.com/package/react-slick) - it was loaded in a .tsx React.Component with ```var Slider: any = require('react-slick');```

We found a fix prior to the platform rollback involved three things:

* upgrading to the latest react-slick library (0.14.5 > 0.23.1)
* upgrading the dependency library [slick-carousel](https://www.npmjs.com/package/slick-carousel) (1.6.0 > 1.8.1)
* changing from require to import in the .tsx component: ```import Slider from 'react-slick';```

Not sure if its relevant, but the same component has a reference to office-ui-fabric: ```import { MessageBar, MessageBarType } from 'office-ui-fabric-react/lib/MessageBar';```

This particular project deployed to the classic site is quite old - SPFx 1.1

package.json dependencies:
```
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.1",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "axios": "^0.16.1",
    "crypto-js": "^3.1.9-1",
    "es6-map": "^0.1.5",
    "es6-promise": "^4.0.5",
    "es6-set": "^0.1.5",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "jqueryui": "^1.11.1",
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "office-ui-fabric": "^2.6.2",
    "office-ui-fabric-core": "^5.1.0",
    "office-ui-fabric-react": "^1.14.3",
    "react": "15.4.2",
    "react-ace": "^5.10.0",
    "react-dom": "15.4.2",
    "react-slick": "^0.23.1",
    "slick-carousel": "^1.8.1",
    "sp-pnp-js": "^3.0.4"
```

**Comment by BraunJonathan** [comment]
> Chatting with some folks internally - There is some code rolling out that can cause things to behave slightly different order in some cases. The correct / best-practice in dealing with the PlaceHolders is code that looks like this:
> 
> `this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);`
> 
> And then in your renderPlaceHolders, you'll want to check for the existence:
> `if (!this._topPlaceholder) { this._topPlaceholder = this.context.placeholderProvider.tryCreateContent( PlaceholderName.Top, { onDispose: this._onDispose } );`
> By doing this, you will get notified when the placeholders have been created and are ready to be used.
> 
> You might be doing the tryCreateContent() call directly in your onInit() method. That's not particularly safe.

Thanks for the workaround Patrick, you saved my day !
Is there any channel where that kind of information is released to devs in order to discover things like that before it is released into production ?
Our entire navigation system is based on extensions so this broke everythink for all users...
Maybe we do not monitor the right channels of information so if they are some, which are they ?
