### ISSUE TITLE
removeContentType error 

### ISSUE THREAD

**Issue by umaknow-alain** [SharePoint/sp-dev-docs#2774]
Hi i have an issue regarding the removeContentType verb. when i am trying to remove the Document content type (id 0x0101) and replace it with my own content type, i have the following error in powershell when trying to add a script to the site design:
"Add-SPOSiteScript : Unable to handle action removeContentType. No action handler was registered for this action.
At line:1 char:51
+ ... teScriptFile -Raw | Add-SPOSiteScript -Title $siteScriptTitle) | Sele ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-SPOSiteScript], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.AddSPOSiteScript  "
I reed in this article that there is something wrong with the verb. Can you tell me if a fix will be available soon ? 
https://github.com/SharePoint/sp-dev-docs/issues/1554

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#removecontenttype)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by iamguptarishi** [comment]
Does your library have documents from which you are trying to remove the content type? I tried it on a library which had Document content type and library had a document in it. the PS script gave failure message, but content type was removed from the library and new content type was added. Then I tried to remove the document and run the same script again. It worked like charm. Can you please share your site script?

**Comment by umaknow-alain** [comment]
Hi Rishi,

I can see that m. Juvonen reassign this has a site design issue and he is probably right. I am going to close this and retest. If i still have problems, i will reopen another one with proper documentation. 

Thanks.
