### ISSUE TITLE
Bulk Uploading with CSV file.

### ISSUE THREAD

**Issue by riswan90** [SharePoint/sp-dev-docs#2776]
Hi All,

I am newbie to SharePoint Online and Power shell. I used information from below link to do the bulk upload of custom properties and managed to do the test for one user.

https://github.com/SharePoint/PnP/tree/master/Samples/UserProfile.BatchUpdate.API

Can anyone advise how i can run the script using CSV file. I want to update data of 1500 users, using txt file is not convenient here.

Thanks in Advance.

**Comment by Seiyasu** [comment]
The key point in the sample code mock data is JSON, not the txt suffix. You can use online tool or custom tool to convert the csv to json. Then just use the converted data file.

**Comment by riswan90** [comment]
Thanks for your feedback. I figured it out yesterday.
