### ISSUE TITLE
Adding multiple web parts in the same project solution

### ISSUE THREAD

**Issue by Mike-tech** [SharePoint/sp-dev-docs#2777]
Hi there

Not sure if i'm missing something but in previous SPFx versions i have been able to add multiple web parts within one solution without any problem.

I'm using the latest SPFx framework and when i add a new web part to an existing solution and then run gulp build or any gulp command, i get errors: JSON validation failed. See screen shot:

Please advice accordingly, is this no longer supported or perhaps even an node update issue:

My node version is 8.12.0

![spfxerror](https://user-images.githubusercontent.com/21954124/47032555-8ac98000-d16a-11e8-969d-0721a0aa28fe.png)

**Comment by Mike-tech** [comment]
@waldekmastykarz i will confirm this tomorrow morning when i'm back at client's office.

This does sound plausible because i move machine this week and installed SPFx with latest version. The existing project was created from a previous machine that probably had older versions.

**Comment by KingKangMSFT** [comment]
Did you have tried using the older version in your new machine? And did it works?

**Comment by waldekmastykarz** [comment]
Yes, when you upgrade your project, the issue should be solved because the installed SharePoint Framework Yeoman generator and the version of SPFx used in the project will be the same.

**Comment by Mike-tech** [comment]
@waldekmastykarz Do you know if there is a special settings to run npm i -g @pnp/office365-cli@next in a proxy environment?

I have the general npm proxy in place and can install yeoman generator, SPFx packages without problem but this one seems to error:

 Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/pnp/vorpal.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128

I've tries C:\Program Files\Cit\cmd\git.exe config --global http.proxy [Proxy address], but none of them seems to be working.

**Comment by waldekmastykarz** [comment]
I've just opened a PR which should fix this issue and which should be merged in the next couple of days. Meanwhile what you could try as a workaround:
- clone https://github.com/waldekmastykarz/office365-cli
- switch to the fit-vorpalfork-dep branch
- run `npm i`
- run `npm link`
That should get you up and running for now. When a new beta is available, you will then be able to remove this version by running `npm unlink` and the installing the beta.

Sorry for the inconvenience.

**Comment by Mike-tech** [comment]
@waldekmastykarz thanks for this. Unfortunately the npm link failed and generated the error in the screen shot: 

![erroroffice365cli](https://user-images.githubusercontent.com/21954124/47174326-33611680-d308-11e8-933c-5eed05ab8645.png)

Due to time, i did the update operation on a different machine where there is no proxy issue. I had the luxury to do this. But i have kept a copy of the mixed version for further testing when your update is done or live.

I will close this issue for now.

As ever many thanks.

**Comment by waldekmastykarz** [comment]
The reason you had the error, because CLI hasn't been built first. Before executing `npm link` you should have run `npm run build`. Sorry I missed that. Meanwhile, the fix is released and you should be able to install the beta version of the CLI using `npm i -g @pnp/office365-cli@next`.
