### ISSUE TITLE
PnP library in SpFx Webpart is not reading data from user profile after deploying to SP online

### ISSUE THREAD

**Issue by tshaikh2019** [SharePoint/sp-dev-docs#2778]
Hi I have created a web part in SharePoint framework to read data from user profile using pnp library. User profile is displayed correctly from hosted workbench in VS Code. When I deploy the project with all correct packaging it does not show user profile in SharePoint online. Please help me on this

**Comment by Seiyasu** [comment]
It should better you can provide an minimized reproduce project, so more guy can further assist you.

**Comment by tshaikh2019** [comment]
> minimized reproduce project
I did not get what you mean by "minimized reproduce project". Please explain little bit more specific so I can provide required info.

Thanks.

**Comment by thomasberman** [comment]
> > minimized reproduce project
> > I did not get what you mean by "minimized reproduce project". Please explain little bit more specific so I can provide required info.
> 
> Thanks.

Post some more details including code needed to reproduce your issue so people will be able to help you better.

**Comment by gautamdsheth** [comment]
Most likely you are missing the initial setup necessary for PnP JS.

You need to add the below code block in your webpart's typescript (`.ts`) file and after that package your solution:

```
import { setup as pnpSetup } from "@pnp/common";

// ...

public onInit(): Promise<void> {

  return super.onInit().then(_ => {

    // other init code may be present

    pnpSetup({
      spfxContext: this.context
    });
  });
}
```

More reference - [Getting started with PnP js](https://pnp.github.io/pnpjs/documentation/getting-started/)
