### ISSUE TITLE
Branding Application Extension sometimes loads before Placeholder's are in DOM

### ISSUE THREAD

**Issue by MaartenSundman** [SharePoint/sp-dev-docs#2779]
#### Category
- [ ] Question
- [ ] Typo
- [*] Bug
- [ ] Additional article idea

#### Observed Behavior
Occasionally we are seeing our branding extension fail to load due to the Top/Bottom placeholders not being present in the DOM yet. Not sure why this happens, I would expect these to always be present by the time the extension is loaded.

#### Steps to Reproduce

This doesn't happen regularly, and we have worked around it by adding this (its dirty but maybe something similar can be integrated in to future releases in to tryCreateContent):
`if(document.querySelectorAll("[data-sp-placeholder='Top']").length == 0)
    {
      window.setTimeout(() => this.onInit(),50);
      return;
    }`

**Comment by dgusoff** [comment]
https://github.com/SharePoint/sp-dev-docs/issues/2773

**Comment by KingKangMSFT** [comment]
Did you have tried the solution that @dgusoff  commented?

**Comment by patmill** [comment]
The correct solution to this is to hook onto the placeholders in your placeholderProvider.changedEvent handler.  This even will fire when the placeholders are created, and any time they change.  The sample code in this tutorial (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions) does the right thing (as well as the wrong thing.  Pull request made to clarify it)
