### ISSUE TITLE
"this.configureStart is not a function error" when running on Sharepoint Online workbench.aspx

### ISSUE THREAD

**Issue by wcarson** [SharePoint/sp-dev-docs#278]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I can successfully run the [react-todo-basic](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-todo-basic) sample application on my local workbench.html file. I expect it would work similarly when using workbench.aspx on Sharepoint Online.

#### Observed Behavior
When running the webpart on Sharepoint Online/workbench.aspx, the initial webpart view is displayed, but when I click the webpart's "Configure" button to open the property pane, I get a "this.configureStart is not a function" error in the _openPropertyPane method of the TodoWebPart.ts class. 

#### Steps to Reproduce

1. Start with the [react-todo-basic](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-todo-basic) sample application.
2. Make modifications as described in the "New BaseClientSideWebPart package location" section of the Drop 5 Release Notes (this is required or you get the error described [here](http://sharepoint.stackexchange.com/questions/199426/the-value-for-webpart-context-configurestart-must-not-be-undefined/199517))
3. Run npm install
4. Run gulp serve
5. Add the Todo webpart to the Sharepoint Online workbench.aspx
6. Click the "Configure" button in the webpart. Nothing happens on the screen, but the error is visible in console on every click of the "Configure" button.

**Comment by manishgarg1** [comment]
We apologize for the inconvenience. We know about the issue and we are working on fixing it soon.

**Comment by subgressive** [comment]
Is there any workaround ? this is also happening on a brand new helloworld. Nothing will run on my Developer Site Collection workbench since last Weekend. Works locally. To reiterate this is React **and** plain javascript sample web-parts. My learning has effectively ceased. Is there any config I can do manually, I have followed the Drop 5 instructions but not helping. Should I go back to an earlier version ?

**Comment by subgressive** [comment]
for anyon with same problem i went back to an old copy of the workbench.aspx and seems to work again

**Comment by frankchen76** [comment]
I tried the latest Drop 6 and changed to refreshPropertyPane(). It seems working well on SPO.
