### ISSUE TITLE
@microsoft/sp-http AadTokenProvider typings in dist/index-internal.d.ts do not match with the typings in the lib/oauthTokenProvider folder

### ISSUE THREAD

**Issue by pkmelee337** [SharePoint/sp-dev-docs#2781]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Because of [this issue](https://github.com/SharePoint/sp-dev-docs/issues/2331) I wanted to use our own azure ad app registration. To do this we created a new AadHttpClient (instead of using aadHttpClientFactory.getClient) with our own servicePrincipalId. Therefore we also needed to create our own AadTokenProvider. This is were the bug occurs.

```typescript
let configuration: IAadTokenProviderConfiguration = {
    aadInstanceUrl: "https://login.windows.net",
    aadTenantId: "<tenant id>",
    aadUserId: "<user id>",
    redirectUri: "https://<our tenant>.sharepoint.com/_forms/spfxsinglesignon.aspx",
    servicePrincipalId: "<own id>"
};
let options: IAadHttpClientOptions = {
    tokenProvider: new MyAadTokenProvider(configuration),
    configuration: configuration
};
let serviceScope = this.props.context.serviceScope.getParent();
let client: AadHttpClient = new AadHttpClient(serviceScope, "https://graph.microsoft.com", options);
```

```typescript
export class MyAadTokenProvider extends AadTokenProvider {
    constructor(configuration: IAadTokenProviderConfiguration) {
        super(configuration);
    }

    public getToken(resourceEndpoint: string, configuration?: IAadTokenProviderConfiguration): Promise<string> {
        console.log(resourceEndpoint, configuration);
        return super.getToken(resourceEndpoint);
    }
}
```

#### Observed Behavior

The constructor of the the AadTokenProvider used in @microsoft/sp-http lib folder (which is also used in the browser) needs the IAadTokenProviderConfiguration as an mandatory parameter, while the AadTokenProvider described in the @microsoft/sp-http dest/index-internal.d.ts file does not. The code breaks in the browser when I use the index-internal typings and it won't compile when I use the typings from the lib folder.

That said, when I correct the typings in the index-internal.d.ts myself, the code is working perfectly.

#### Steps to Reproduce

install the latest 1.6.0 spfx packages (including the @microsoft/sp-http package)

**Comment by Seiyasu** [comment]
Do you have other config except the default template?

**Comment by pkmelee337** [comment]
Yes, I am overriding the default configuration this way, because I want to use another "servicePrincipalId".

**Comment by huey253** [comment]
Hi @pkmelee337,

I'm afraid that this is by design. Using a custom configuration isn't supported, so this behavior was removed from the typings.

**Comment by lahuey** [comment]
Hi @pkmelee337,

I'm afraid that this is by design. Using a custom configuration isn't supported, so this behavior was removed from the typings.
