### ISSUE TITLE
How to provision modern sites without a Group?

### ISSUE THREAD

**Issue by robinmeure** [SharePoint/sp-dev-docs#2783]
I'm missing the way how to provision a modern teamsites without a (connected) Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
> Every "modern" team site has a backing Office 365 group to improve the overall collaboration experience

Why do you want to provision modern sites without a Group? Have a special meaning? If you don't want to the group, you should better create the classic site and the just add modern page.

**Comment by robinmeure** [comment]
The question 'why' is not relevant in this case. It is possible using the user interface and thus it would be helpful to also have this available in the form of a script.
