### ISSUE TITLE
I'm missing the way to provision Modern teamsites using SharePoint Online Management Shell cmdlets

### ISSUE THREAD

**Issue by robinmeure** [SharePoint/sp-dev-docs#2784]
And to add on that, it would be nice to see the difference between the vanilla and PnP cmdlets to create both connected and non-connected modern teamsites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Did you want to find a way to provision Modern teamsite?

Maybe the following Shell will be helpful for you:

`//Connect to your SharePoint admin center, credentials will be asked
Connect-PnPOnline -Url https://contoso-admin.sharepoint.com

//Create a new modern team site
New-PnPSite -Type Team -Title "Awesome Group" -Description "Awesome Group" -Alias "awesome-group"`

**Comment by robinmeure** [comment]
$title = "ModernTeamSite"
$url = "https://contoso.sharepoint.com/sites/modernteamsite" 
$owner = "denisd@contoso.com"

// SharePoint Online Management Shell
New-SPOSite -Title $_title -Url $_url -Owner $owner  -StorageQuota 512 -Template "STS#3"

// PnP
New-PnPTenantSite -Url $_url -Description $_title -Title $_title -Template STS#3 -Owner $owner
