### ISSUE TITLE
ListViewCommandSet buttons are not appearing from 16/10/2018

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-docs#2785]
Hi Everyone,

Is it just my tenancy or more you you get this as well, but since 16/10/2018 all my custom ListViewCommandSet buttons are gone because of internal code JavaScript error.

![im1](https://user-images.githubusercontent.com/30652251/47099878-253ec780-d22e-11e8-894a-9ec4d0d44af3.png)

#### Category
- [ x] Bug

Thanks 
Saulius

**Comment by Seiyasu** [comment]
Do you have made any change or the extension do not work suddenly?

**Comment by Saulius-Laurinaitis** [comment]
No, no change in last couple of weeks. I was working just fine on Monday 15/10/2018

**Comment by Saulius-Laurinaitis** [comment]
It is actually not only mine are gone, other apps as well, such as Nintex.

**Comment by Seiyasu** [comment]
It sound like a bug, but i haven't reproduce it on my dev env.

**Comment by Saulius-Laurinaitis** [comment]
on my dev all is ok as well, but I have there targeted release enabled, on production it is failing with targeted release disabled.

**Comment by qrown** [comment]
We are also seing this in several solutions.

**Comment by semopz** [comment]
Do you remember if you have ever removed the app associated with the Command Set buttons and then reinstalled it at a later time? Does your solution deploy automatically or do you have to install it on a site by site basis?

I am seeing some strange behaviour if I remove the solution and then redeploy it again on a site with no app catalog (e.g., while installing, it shows up as two apps in Site Contents but then goes back to one once installed).

**Comment by Saulius-Laurinaitis** [comment]
No, my app is already deployed for couple of months, and was working just fine, just started to fail with that JS exception in OOTB libs.

**Comment by Saulius-Laurinaitis** [comment]
@VesaJuvonen any ideas what could be happening. It fails on production environment, and is blocking users for using any apps that have custom actions on library.

**Comment by Saulius-Laurinaitis** [comment]
I actually found a defect - the problem is when there are custom actions that has no ClientSideComponentId, see attached image. Could you please make an improvement in code here to handle such situations and I will also try to get app providers to fix it.

![im2](https://user-images.githubusercontent.com/30652251/47341108-1164ec80-d698-11e8-9832-9f9993d39285.png)

**Comment by VesaJuvonen** [comment]
We do not actually support custom actions in modern experiences without them being deployed SharePoint Framework - This is by design from day one with SharePoint Framework and modern experiences. Your screenshot seems from the modern experience. Could it be that on 16th of Oct, you environment moved from classic to modern and that then caused this?

**Comment by Saulius-Laurinaitis** [comment]
no, we started with modern framework from early days :) I actually by debugging the other day found that custom action was deployed through App Catalog by one of the Store apps. Once I removed it, the problem was gone, just I'm worried that this area is not isolated, I mean that some custom component could break number of other things. Simple "if" could resolve the problem for the future, but you can also close this for now.

Thanks
Saulius
