### ISSUE TITLE
No Header Emphasis Option Available

### ISSUE THREAD

**Issue by Blaksey** [SharePoint/sp-dev-docs#2787]
There is no header emphasis option available in the site theme when applying a custom theme via Powershell. When doing it through the interface you can use "None, Neutral, Soft, or Strong" as options when Changing the look but have no way to replicate this with custom colors used in custom themes!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview#feedback)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Maybe you should submit an feature request.

**Comment by KennySchoute** [comment]
How do I feature a request?

**Comment by andrewconnell** [comment]
@KennySchoute Good question :) We have since added a description to the label with instructions on how to do this: Submit to https://aka.ms/sp-dev-uservoice
