### ISSUE TITLE
Integration with PowerApps

### ISSUE THREAD

**Issue by FranckGarcia** [SharePoint/sp-dev-docs#2789]
Thank you for this calendar which is working fine. However I have tried to change the standard form of my Task list with PowerApps. How to edit the tasks with this form?
Actually the URL ....DispForm.aspx?ID=${calEvent.id} opens the old form, not the PowerApps one.
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ecd027-f5ca-48c0-d60c-1883fa24ab96
* Version Independent ID: 9f38cbc9-464a-a2a4-0eeb-4deb6b2eb339
* Content: [Migrate jQuery and FullCalendar solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The old form is still the suggest way. If you want to use the PowerApps's, you need to test it by yourself now. Why do you want to use the PowerApps's? Meanwhile you can submit an feature request in the UserVoice.

**Comment by FranckGarcia** [comment]
With the modern UI, PowerApps is now the recommended tool to get more sophisticated forms in Sharepoint online (replacing Infopath which is deprecated). I would expect to have it integrated within the framework.
