### ISSUE TITLE
Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by poikjo** [SharePoint/sp-dev-docs#279]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Load SPFx webpart on Dev tenant. Works fine on local but gives this generic error on First release tenant. 

#### Observed Behavior
When loading webpart the loading hangs and Chrome console shows error 
`Uncaught (in promise) undefined 
(anonymous function) @ sp-webpart-base_5656ff0….js:1
Promise.resolve (async)...`

Error comes from file: 
https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-07.006/sp-webpart-base_5656ff0d19b7ef6845f21b237684a031.js

#### Steps to Reproduce
Build SPFx spapp package
Start local workbench (gulp serve --nobrowser)
Deploy package to tenant
Add webpart to page
Load page

**Comment by patmill** [comment]
Hi @poikjo - have you made your own webpart, or is this coming from the base part?  Can you follow these instructions to see if it clears up your issue?  
look at the section "New BaseClientSideWebPart package location" here - https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-5

**Comment by manishgarg1** [comment]
Is there a way to share the web part code ? Is this one of our sample web parts ?

**Comment by poikjo** [comment]
At first I created own webpart which worked fine, but suddenly broke on next day. Then I tried sample/tutorial "hello-world" -webpart with same error.

I first had Drop 4 which was updated to Drop 5.

**Comment by poikjo** [comment]
As a response to myself the problem was updating Drop versions. I think I just misconfigured the webpart import reference on update and that caused the error. Now it works fine after re-updating to Drop 6 more carefully.
