### ISSUE TITLE
Date Time functions

### ISSUE THREAD

**Issue by csteelatgburg** [SharePoint/sp-dev-docs#2791]
I'm working in Microsoft Flow and trying to filter items from an Events based Sharepoint list. The Get Items from a SharePoint list task does not accept the Date and Time functions. I believe this is because the Flow task access the REST API, where those functions are not recognized. They are only valid when using the _vti_bin/listdata.svc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Just to confirm your conclusion. Those date functions are only available in the old REST API surface with listdata.svc, which would no longer be used.
