### ISSUE TITLE
samples are outdated?

### ISSUE THREAD

**Issue by braegelno5** [SharePoint/sp-dev-docs#2793]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

#### Expected or Desired Behavior

it seems most of the spfx webpart and extension samples are outdated

#### Observed Behavior

only samples with an update to the actual spfx 1.6 are working

#### Steps to Reproduce

setup a fresh dev box [like a newbie will do]
follow all steps to install vs code and node-lts etc.pp.
build a first spfx helloworld webpart on this dev box - it works on local workbench fine
clone the repositories on dev box
open vs code and open from there an older updated sample folder 
follow the readme with **npm i** - you get errors - **gulp serve** ends also with errors
now a newbie will stop more investigation 

#### Submission

- is there anywhere a general step by step documentation to solve this?
i have found this: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages](url) and [https://n8d.at/blog/keep-your-spfx-and-npm-packages-up-to-date/](url) and at least the best: [https://blog.mastykarz.nl/upgrade-sharepoint-framework-project-office-365-cli/](url)

- if there exists a general documentation to solve this also for an newbie, we should link this from readme
may be for a newbie which has seen all five starter videos for the hello world spfx web part it's to less documentation for this stoping fact

Thanks! Sharing is caring.

**Comment by jakemannion** [comment]
I am new to SPFX (about 10 yrs SP experience) and was able to progress through the tutorials over the last week or so. There were some struggles, but I don't know if it was the _toolset_ the _documentation_ or simply me being unfamiliar. I succeeded getting one of the example projects running on my dev tenant, and was able to customize it from there. I have been working on a second one without success, yet.

Thank you for keeping the newcomers perspective in mind @braegelno5

**Comment by vmiy** [comment]
Are you cloning from the spfx helloworld webpart which hosted in your local computer? That is already installed all dependencies (inside node_modules).
If you have a project structure like below figure: 
![hellowordproject02](https://user-images.githubusercontent.com/44593598/48330278-f548df80-e686-11e8-998d-6ea5b7dda854.JPG)
There is no dist/ tempt/ lib/  and other folders that you can use the npm i command to install the dependencies and then gulp serve command to run the code.

There are many SPFx sample codes that you can learn. Refer to https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples.

If you find some samples are not working, provide the sample code URL address, and also the errors log.
