### ISSUE TITLE
File not found error when Adding template to "_cts/{Content Type Name}" folder

### ISSUE THREAD

**Issue by shashank2490** [SharePoint/sp-dev-docs#2796]
When trying to use this code and uploading template to "_cts/{Content Type Name}" folder, following lines gives error "File not Found"
Microsoft.SharePoint.Client.File uploadedFile = ctFolder.Files.Add(newFile);
                cc.Load(uploadedFile);
                cc.ExecuteQuery();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ed07d3-4bc0-71c4-d8d2-2edd8ba95927
* Version Independent ID: 8bd4af28-95b7-3823-6b89-53ede1610085
* Content: [Create SharePoint content types by using CSOM](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/create-sharepoint-content-types-by-using-csom)
* Content Source: [docs/solution-guidance/create-sharepoint-content-types-by-using-csom.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/create-sharepoint-content-types-by-using-csom.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Could you please check if this file exists?

**Comment by KingKangMSFT** [comment]
Could you please check if this file exists?

**Comment by shashank2490** [comment]
The file is actually created but still it gives file not found error

**Comment by KingKangMSFT** [comment]
My apologies, I mean that, we should check that is the `newFile` is exists in the code: `Microsoft.SharePoint.Client.File uploadedFile = ctFolder.Files.Add(newFile);`

**Comment by shashank2490** [comment]
But how can a File pre-exist if it has never been created before? 
The file is being associated with the content type at the time of creation of Content Type. 
I did not get your point of checking if the file exists. Can you please elaborate on this?

**Comment by KingKangMSFT** [comment]
I have used the following code, and it works
`Web web = context.Site.RootWeb;
                CreateContentTypeIfDoesNotExist(context, web);
                ContentType ct = web.ContentTypes.GetById("0x0101009189AB5D3D2647B580F011DA2F356FB2");                     // create by reference                                         context.Load(ct);                     context.ExecuteQuery();  
                string ctFolderServerRelativeURL = "_cts/" + ct.Name;
                Folder ctFolder = web.GetFolderByServerRelativeUrl(ctFolderServerRelativeURL);
                context.Load(ctFolder);
                context.ExecuteQuery();
                string path = @"D:\TestDocs\test1.docx";
                string fileName = System.IO.Path.GetFileName(path);
                byte[] filecontent = System.IO.File.ReadAllBytes(path);
                using (System.IO.FileStream fs = new System.IO.FileStream(path, System.IO.FileMode.Open))
                {
                    FileCreationInformation newFile = new FileCreationInformation();
                    newFile.Content = filecontent;
                    newFile.Url = ctFolderServerRelativeURL + "/" + fileName;
                    Microsoft.SharePoint.Client.File uploadedFile = ctFolder.Files.Add(newFile);
                    context.Load(uploadedFile);
                    context.ExecuteQuery();                         //Microsoft.SharePoint.Client.File.SaveBinaryDirect(clientContext, ctFolderServerRelativeURL + "/" + fileName, fs, true);
                    context.Load(ct);
                    context.ExecuteQuery();
                    ct.DocumentTemplate = fileName;
                    ct.Update(false);
                    context.Load(ct);
                    context.ExecuteQuery();
                    Console.WriteLine("Content type updates");
                }`

Could you please provide some code for this?
