### ISSUE TITLE
RER for OneDrive

### ISSUE THREAD

**Issue by bastyuchenko** [SharePoint/sp-dev-docs#2800]
Hello.
I have wide experience with RER in SharePoint but now I have to develop RER for OneDrive for Business. Theoretically, it should work as same as in SharePoint but I have found no proof from microsoft documentation or any developer on the internet that it is possible. Could you confirm that remote event receivers work for OneDrive for Business? What restriction are there? :
- Could I register RER just for a specific folder, not only for a root of OneDrive for Business?
- Could I register just FileUpdated event?
- Will event fire every time when user changes a cell's value in an excel document and loses focus from this cell?(auto-save when you edit an excel document online)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e75925-b939-1b47-cca8-5a4aaa452e90
* Version Independent ID: 3d6e85ec-30bc-6c69-7cd3-ca07081ea79b
* Content: [Create a remote event receiver in SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-remote-event-receiver-in-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/create-a-remote-event-receiver-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-a-remote-event-receiver-in-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jxnx888** [comment]
Hi @bastyuchenko Do you have any observation you would like to share? I am working on this case, if you have any observation, please let me know

**Comment by bastyuchenko** [comment]
Hi @KingKangMSFT Eventually I selected [OneDrive delta](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online). This approach has some constraints - [The delta action is only available on the root item of a drive e.g. /drive/root.](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/release-notes?view=odsp-graph-online) and I need to check just a specific folder in OneDrive - so I decided to filter just files from a specific folder in my code. By the way, [OneDrive delta](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online) works fast enough and this approach acceptable for my solution.
Also, I received a recommendation in [another thread](https://github.com/OneDrive/onedrive-api-docs/issues/930) but I haven't check this approach

**Comment by VesaJuvonen** [comment]
As @chackman answered this question on the other thread, closing this one. Reply copied also below: 

-- -- -- 

_We recommend using webhooks instead of Remote Event Receivers. More information about webhooks can be found here:_

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/webhooks
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-webhooks?view=odsp-graph-online
