### ISSUE TITLE
Access to page/item properties from the context object

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#2801]
#### Category
- [x] Question

If I view the HTML source of a modern page I see page context info for properties as `user` and `item` assigned to an internal variable `spClientSidePageContext` which is passed into SPFx bootstrapping. This object also has a property `spPageContextInfo` which is made available via `this.context.pageContext` in SPFx.

Are there plans or any chance we can access the `user` and `item` property as well, to avoid executing an extra HTTP call to fetch this information? Seems a waste of resources to re-fetch something which is already present on the page :) #lazyprogrammer

**Comment by patmill** [comment]
Hey Mikael - it's unlikely that we'll expose the user, as pretty much all of the user information is available in the page context.  Let me know if there is a property that isn't.

We're thinking about the item, and how to handle it.  Getting into more detail than you probably want to hear - the spClientSidePageContext is something delivered to the app, and then the app surfaces some of that data through the API.  The spPageContextInfo is something that everything in SharePoint understands and can produce, and so we can expose it in a general way through all the scenarios (classic, modern, modern-list, workbench, etc.).  The item is trickier to handle.  In an ideal world, I would want to see a similar schema / API / etc. between the current item when you are on a page, and the current item you have selected from a doclib webpart (via the dynamic data API).  The DD json format is still being worked on though.

Please post this to uservoice though, which is where the general set of Feature Requests go.
