### ISSUE TITLE
SPS Column Formatting, class for clickable action is wrong in MS docs example

### ISSUE THREAD

**Issue by AntGut** [SharePoint/sp-dev-docs#2804]
In trying to learn column formatting for SPO, attempted to use the samples on MS docs, specifically the "advanced" section on clickable actions (https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#add-an-action-button-to-a-field-advanced). Using the sample "as-is" would not render the icon as expected, but produce "empty space" which still had viable link data (on-hover shows the correct URL).

Finally, after looking at other samples/examples (e.g., https://github.com/SharePoint/sp-dev-docs) I realized that the class for the clickable action is actually wrong on the MS docs page.

#### Category
- [ ] Question
- [X] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The line for the class in the JSON for the advanced sample should be the following (note the plural). When used, the icon specified by "iconName" is displayed and clickable.

                "class": "sp-field-quickActions",

#### Observed Behavior
The line for the class in the JSON for the advanced sample presented on MS docs is wrong (note the class is singular). When used, the icon does NOT render.

                "class": "sp-field-quickAction",

#### Steps to Reproduce
-- Follow the steps on the MS docs page for adding clickable action (advanced),
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#add-an-action-button-to-a-field-advanced
-- The expected icon does not display.
-- Change the class as indicated above (make plural) and the icon appears and is a live link.

Please correct this to prevent confusion and numerous hours of frustration!

Thx... AntGut

**Comment by Seiyasu** [comment]
Thanks for your post, have fix it.

**Comment by AntGut** [comment]
Could you please recheck. The changes have not been merged yet.
