### ISSUE TITLE
The API Weather is not enable the cors

### ISSUE THREAD

**Issue by AdrianDiaz81** [SharePoint/sp-dev-docs#2807]
The example API does not have CORS enabled and therefore when you test the example it gives you an error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b84eaa-9fbf-6d45-fda6-0f59ea10ac30
* Version Independent ID: 46395b70-89c3-b77b-0fc1-e8a86ff093ad
* Content: [Connect to anonymous APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-anonymous-apis#feedback)
* Content Source: [docs/spfx/connect-to-anonymous-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/connect-to-anonymous-apis.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
You are right. Thank you for reporting this. We will update it with a sample that does work. Sorry for the trouble.
