### ISSUE TITLE
What is _spPageContextInfo

### ISSUE THREAD

**Issue by RupenAnjaria** [SharePoint/sp-dev-docs#2809]
#### Category
- [x ] Question

Referring to your code https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery#RunTheExamples
Specifically Code 2. function uploadFile()  Line :

`    // Get the server URL.`
 `  var serverUrl = _spPageContextInfo.webAbsoluteUrl;`

Where have you declare `_spPAgeContextInfo`?

**Comment by wictorwilen** [comment]
That is a global (legacy) property existing on all pages in _classic_ SharePoint mode.

**Comment by RupenAnjaria** [comment]
Thank you, however, I am creating a web component (ascx), is there any way I can this example? Do we have to change ascx to SharePoint mode? how?

**Comment by waldekmastykarz** [comment]
@RupenAnjaria how do you intend to use the User Control (ascx) that you're building? Will you embed it in a web part or put it directly on a Master Page or a Page Layout? Either way, the `_spPageContextInfo` should be already available to you as @wictorwilen mentioned.

**Comment by RupenAnjaria** [comment]
I will be using the control in Page Layout.

**Comment by RupenAnjaria** [comment]
Just to be clear, it's a web application (so I have to refer code Sample 1), right?

**Comment by KingKangMSFT** [comment]
The hostWebUrl will be `https://myCompany.sharepoint.com/MyApplication/`
