### ISSUE TITLE
I cannot add "hello world" SPFX client side webpart on Modern Page on Dev tenant

### ISSUE THREAD

**Issue by OvidiuSt** [SharePoint/sp-dev-docs#281]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I am creating a new hello world webpart with yo @microsoft/sharepoint
I am building the solution with gulp serve - and it appears correctly on wokbench
I am packaging the solution with gulp package-solution - and HelloWorld.spapp is created
I am adding the .sppapp to the AppCatalog and it deploys fine
I am adding the app to https://ininadev.sharepoint.com/sites/SummitRomania and it appears in Site Contents
I am creating a new modern page and I try to add the client side web part -> but it does not appear in the list - only the message "There was an error fetching the web parts. Not all web parts may be available"

#### Observed Behavior
Hello World client side webparts cannot be added to Modern Pages.
They still appear for the classic pages but give error when trying to add them.

#### Steps to Reproduce
I am creating a new hello world webpart with yo @microsoft/sharepoint
I am building the solution with gulp serve - and it appears correctly on wokbench
I am packaging the solution with gulp package-solution - and HelloWorld.spapp is created
I am adding the .sppapp to the AppCatalog and it deploys fine
I am adding the app to https://ininadev.sharepoint.com/sites/SummitRomania and it appears in Site Contents
I am creating a new modern page and I try to add the client side web part -> but it does not appear in the list - only the message "There was an error fetching the web parts. Not all web parts may be available"

The same behavior seems described here https://github.com/SharePoint/sp-dev-docs/issues/276 in the post from 2 days ago.

**Comment by mcmynn83** [comment]
Hi OvidiuSt,
This problem should be resolved, could you let me know if you are still experiencing this symptom?

If for some reason it is still happening please let me know.  In the meantime, you could use your webpart on a classic page to unblock yourself if it is still happening, however, it should now be resolved.

Sorry for the inconvenience,
Graham

**Comment by OvidiuSt** [comment]
Hello,

now I am able to see the webpart in the list and no error shows when clicking on the adding menu.

However when I am trying to add the webpart to the page I get the below message:

![webparterror](https://cloud.githubusercontent.com/assets/21057396/20523481/e02d046a-b0bd-11e6-938c-702c4c87c5ae.png)

**Comment by manishgarg1** [comment]
Sorry for the inconvenience. Can you please add the following like in the web part json file just below the like that contains the "id". And then recompile and try ?

"alias": "HelloWorldWebPart",

**Comment by OvidiuSt** [comment]
I added "alias":"WebPartName", in the manifest.json, in webpart folder and recompiled, 

I get this message when compiling

Error - [writemanifests] Manifest validation error (./src/webparts/graphSpfx/Gra
phSpfxWebPart.manifest.json):
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/componentType) No enum match for: WebPart
(#/) Additional properties not allowed: alias

Anyway, still does not work 

![webparterror2](https://cloud.githubusercontent.com/assets/21057396/20554798/e24d2226-b166-11e6-889f-6a81e6f7d8c2.png)

**Comment by patmill** [comment]
The alias is part of Drop 6.  Which drop are you running?

**Comment by manishgarg1** [comment]
Hi, I am trying to repro the issue. In the meantime, could you please post any errors that you see in your console?

**Comment by OvidiuSt** [comment]
Not sure what drop I was but I ran  npm i -g @microsoft/generator-sharepoint@latest so I should be in 6 now. I no longer see errors in console when doing gulp serve.

and this "alias": "GraphSpfxWebPart", - already in the *.manifest.json.

I still receive the same spinning when trying to add webpart to the modern page and the same error message.

**Comment by OvidiuSt** [comment]
node --version v6.9.1
gulp --version
CLI version 1.2.2
Local version 3.9.1

**Comment by manishgarg1** [comment]
Hi @OvidiuSt, thank you for reporting the issue. This issue has been there for a while and lots of bugs have been fixed since then. Do you still notice the issue in the latest Yeoman generated web parts?
