### ISSUE TITLE
Argument is not assignable to parameter (SPHttpClientConfiguration)

### ISSUE THREAD

**Issue by runmotion** [SharePoint/sp-dev-docs#2812]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Observed Behavior

error TS2345: Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.

#### Steps to Reproduce

I use the following code:

WebPart.ts

`import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http'; `

`this.context.spHttpClient.get(this.context.pageContext.web.absoluteUrl + '/_api/web/lists?$filter=Hidden eq false', SPHttpClient.configurations.v1)
   .then((response: SPHttpClientResponse) => {
     return response.json();
   });`

Package.json

`{
  "name": "robeco-list-web-part",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.5.1",
    "@microsoft/sp-webpart-base": "1.5.1",
    "@microsoft/sp-lodash-subset": "1.5.1",
    "@microsoft/sp-office-ui-fabric-core": "1.5.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.5.1",
    "@microsoft/sp-module-interfaces": "1.5.1",
    "@microsoft/sp-webpart-workbench": "1.5.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
`
Offcourse I started a new SPFx Project.
Ran NPM outdate and updated the SharePoint elements to 1.6.

How can I solve this error?

Read these previous issue but got no clue what to do:
[https://github.com/SharePoint/sp-dev-docs/issues/365](url)
[https://github.com/SharePoint/sp-dev-docs/issues/911](url)

**Comment by Seiyasu** [comment]
You need to change Response to **SPHttpClientResponse**. This is the correct way as the response will be in the type SPHttpClientResponse. JSON data will then be extracted from the response using the methods available.

Demo method:
`private _getListData(): Promise<ISPLists> { 

    var queryUrl = this.context.pageContext.web.absoluteUrl + "/_api/web/lists/GetByTitle('${this.sharepointLists[this.prop‌​erties.SharepointLis‌​t]/items";

    return this.context.spHttpClient.get(queryUrl, SPHttpClient.configurations.v1)
               .then((response: SPHttpClientResponse) => {
                        return response.json();
    });
}`

**Comment by VesaJuvonen** [comment]
Answered, so closing this. Thx @Seiyasu.
