### ISSUE TITLE
Upload Large File with % and #

### ISSUE THREAD

**Issue by KVolodymyrABTO** [SharePoint/sp-dev-docs#2813]
How can I upload large file (about 3GB) with % character in name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8869da6e-b785-abff-937e-a1d95bcd8314
* Version Independent ID: d77fd4c4-5149-f4ac-da03-f0803091dc1c
* Content: [Upload large files sample SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-large-files-sample-app-for-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
We can refer to[ this document](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api) for more information. Based on this document say：

> Support for % and # in files and folders is being deployed within SharePoint Online. Unfortunately, due to existing API structures and calling patterns, working with these file names can sometimes become ambiguous.

**Comment by KVolodymyrABTO** [comment]
Thanks for answer. I was read [this document](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api) before. It works great for small files but not for large, and in my case I need upload large files(about 3GB), is there a way to do this? [This documentation](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-large-files-sample-app-for-sharepoint) recommends to use **StartUpload**, **ContinueUpload**, and **FinishUpload** methods when file is larger than 10MB, but they doesn't work for files with % in name. Anyway new API based on ResourcePath can't upload large files.

**Comment by andrewconnell** [comment]
When was the last time you tried this? Which SharePoint environment are you trying it with?

This page lists the allowed & invalid characters that can be used in file names:
https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters

Those two characters, `%` &  `#`, are explicitly called out in some environments.
