### ISSUE TITLE
🐞 Tenant Wide Extensions list not present in App Catalog's Site Contents page

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#2814]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The list **Tenant Wide Extensions** should appear in the **Site Contents** page of an app catalog.

#### Observed Behavior

The list **Tenant Wide Extensions** is not present in the **Site Contents** page of an app catalog. This is for a very old tenant (created around the introduction of SPO). Tried both modern & classic experience. 

![image](https://user-images.githubusercontent.com/2068657/47433765-0a5cdd80-d76f-11e8-8f73-11bf5f74ef77.png)

I can access the list directly via the URL...

![image](https://user-images.githubusercontent.com/2068657/47433706-ed280f00-d76e-11e8-8c34-3e49469cb127.png)

I can provide the specific tenant privately if it helps troubleshoot.

#### Steps to Reproduce

Explained above in the *Observed Behavior* section.

**Comment by VesaJuvonen** [comment]
Thanks, @andrewconnell for reporting. List should be indeed visible in the Site Contents as administrators can access that for editing the entries as needed. We'll check the situation on this. This seems to indicate that the list settings are getting for some reason unghosted in your case (old tenant), which explains why it would not be visible, but it's clearly a bug.

**Comment by VesaJuvonen** [comment]
This is an unfortunate situation, but most likely what happened is that before the feature was released, the list got unghosted with UI operations. When we then got the final schema.xml files out, they did not have any impact as the list was already unghosted. Technically by design. Inconvenient and should only happen for those scenarios where user knew about this list BEFORE it was released and visible. So - the cost for fixing is too high vs assumed impact to assign resources for this.

**Comment by andrewconnell** [comment]
:-/ 

In my case that's not what happened... I never tried going to the list prior to the GA of the feature.

**Comment by VesaJuvonen** [comment]
thanks for coming back on this. This would be also an extremely costly thing to fix 100% reliably cross the world and as it's not really blocking issue as such and only in one random tenant, we can't justify the resource ask. Now - if we see this more widely, we'll absolutely need to jump on it.

**Comment by andrewconnell** [comment]
Np... was just clarifying the situation. Understand risk/reward. Thanks for follow up.
