### ISSUE TITLE
 Create an SPFX extension that calls a CSS file by enabling it to add design to my SharePoint Online site

### ISSUE THREAD

**Issue by naouel21** [SharePoint/sp-dev-docs#2815]
- Question :

Hello,

I would like to know if it is possible to call a CSS file that I add in my library of the document on sharepoint online and apply this CSS on my site while using a SharePoint Framework Extension.

So, i want to create a sharepoint framework extension, and when it is deployed on a sharepoint online site, it calls an existing CSS file in the document library and applies this CSS on this site.

Is it possible to do that please ?

Thank you in advance for your answers.

**Comment by StfBauer** [comment]
This scenario is not supported and can cause problems with the overall experience of SharePoint Online.
In SPFx framework included are mechanisms that allow you to scope the CSS to web parts and extensions that use CSS Modules to make sure that the CSS changes only our component.

If you put the style sheet in a library you have a blank CSS and a use can add whatever he likes to add there. For example, define a global background for all pages, changes the overall font and do a lot more unsupported things.

Please see: [Work with CSS in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/css-recommendations)

**Comment by naouel21** [comment]
Merci beaucoup pour votre réponse.

**Comment by naouel21** [comment]
Bonjour, 

C'est possible en fait, en utilisant SPComponentLoader, j'ai réussi a créer un fichier css que j'ai mis dans mes documents sur sharepoint online, j'ai réalisé une extension qui charge la css à partir d'une url, tout en respectant les mêmes classes existantes déjà sur le site.

Veuillez voir : https://docs.microsoft.com/fr-fr/sharepoint/dev/spfx/web-parts/guidance/reference-third-party-css-styles
