### ISSUE TITLE
Modern page top placeholder renders on the page itself when viewed in SharePoint mobile app and disappears when scroll

### ISSUE THREAD

**Issue by BrianBusby** [SharePoint/sp-dev-docs#2817]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expected content in the top page placeholder to appear at the top of the screen in the mobile app and not be scrollable.

#### Observed Behavior

The content appears inside the page and disappears when scrolling.

#### Steps to Reproduce

    if (!this._topPlaceholder) {
      this._topPlaceholder = this.context.placeholderProvider.tryCreateContent(
          PlaceholderName.Top,
          { onDispose: this._onDispose });
    }
    if (this._topPlaceholder.domElement) {
      this._topPlaceholder.domElement.innerHTML = `
      <div id="GlobalNavDiv">THIS WILL BE GLOBAL NAV
      </div>`;  
    }

Here is the rendered content on my laptop

![globalnav](https://user-images.githubusercontent.com/22009414/47457827-28920000-d7a6-11e8-9220-2d9d8a8c6069.PNG)

Here is the rendered content on my iPhone

![iphone](https://user-images.githubusercontent.com/22009414/47457866-3d6e9380-d7a6-11e8-9674-a3dfc83dd379.PNG)

Are there any plans to address this? It removes our ability to create widgets that live at the top of a site when viewed in mobile. 

Thanks

**Comment by patmill** [comment]
Sorry for the super long delay.  Thank you for your feedback - we will consider this for future refinements in the mobile app?
