### ISSUE TITLE
Cannot Approve api AadHttpClient

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#2818]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hi , I have an Azure function secured by azure AD and I am calling it from an spfx  webpart.

The Azure AD registratcion  looks like this:
![image](https://user-images.githubusercontent.com/2412956/47457856-3a73a300-d7a6-11e8-9eb6-5b0b6afbca60.png)

My  Package solution contains:
    "webApiPermissionRequests": [
      {
        "resource": "0ead6d45-9fba-4ee7-b2ca-32c7fa96f168",
        "scope": "user_impersonation"
      }
    ]

When a tenant admin tried to approve the request from the new portal, he got the following error:

![error](https://user-images.githubusercontent.com/2412956/47458063-b1a93700-d7a6-11e8-9e71-f489be4c99d3.PNG)

How do I get this approved?

**Comment by Seiyasu** [comment]
Your webApiPermissionRequests configuration is incorrect. Please follow the following docs to configure.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi

**Comment by russgove** [comment]
OK So I changed my package.config to use the app name rather than ID.:
   "webApiPermissionRequests": [
      {
        "resource": "GRCRoleToTransactionAzureFunction",
        "scope": "user_impersonation"
      }
    ]

now I get a different error : An OAuth permission with the scope user_impersonation could not be found.
Parameter name: scope
 
![error](https://user-images.githubusercontent.com/2412956/47676102-0c210980-db92-11e8-8982-20661bf2ae10.png)

**Comment by russgove** [comment]
Hi Any update on this?

**Comment by VesaJuvonen** [comment]
Closed due to no response in 2 weeks.
