### ISSUE TITLE
Errors have started appearing in our production app

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#2819]
Hi,

I've had an app in production for almost a year. No changes have been made,other than I deployed to a test site collection a few days ago(we use site collection app catalogs). The prodiuction site-catalog was unchanged,   I just got reports that it is now not working on the production site.  The dropdowns are not showing any values to select, The dropdowns are usinng the react-dropdown control.

When I view the page I see this in the logs:

![image](https://user-images.githubusercontent.com/2412956/47471393-05804400-d7d8-11e8-95c5-52b80fda77fd.png)

I checked the dev site and get the same  issue,

The webpart uses these packages:
 "dependencies": {
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-listview-extensibility": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/spfx-controls-react": "^1.1.3",
    "@types/microsoft-ajax": "0.0.33",
    "@types/react": "15.6.6",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "15.5.6",
    "@types/react-tabs": "^0.5.22",
    "@types/sharepoint": "^2016.1.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "ckeditor": "^4.6.2",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "office-ui-fabric-react": "^4.21.2",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-dropzone": "^4.2.5",
    "sp-pnp-js": "3.0.10",
    "tsutils": "1.6.0"
  },

**Comment by KingKangMSFT** [comment]
Did the app works in the test site collection? Could you please provide the code about the dropdowns?

**Comment by russgove** [comment]
Hi,
I was updatiing the props in my react component after my initial render as documented at https://wordpress.com/post/yetanothersharepointblog.wordpress.com/585.

This seems to have stopped working recently. I changed the code so that I do update the props in my react component after my initial render to avert the issue.
