### ISSUE TITLE
SharePoint Online PRIME API how handle sharing

### ISSUE THREAD

**Issue by LeoJiang1988** [SharePoint/sp-dev-docs#2820]
I have find a document https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-shared
But look like this does not work.
I have add the fields and properties element and roleassigment. The roleassigment set correct but shared with me not showing.

**Comment by Seiyasu** [comment]
This docs is for ShareWithUser but not the ShareWithMe.
