### ISSUE TITLE
Site Design PnP Provisioning Guidance needs updates due Azure Function 2.0 support changes

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#2822]
Hi,
This documentation is outdated, the PowerShell support doesn't exist anymore in 2.x of Azure function. Please update this documentation !!!
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. The content team will add this to their work list, but won't update the docs immediately. If you have plan on how to update the docs, feel free modify it and submit an pull request.

**Comment by PooLP** [comment]
I have tested this : http://www.avtex.com/2018/06/azure-automation-provisioning/
It's works and is a good start for Azure Automation.

**Comment by VesaJuvonen** [comment]
thx @PooLP - if you want this to get updated asap, we do welcome also pull requests. You can simply click Edit button on the top of the page and submit your content suggestion. There are unfortunately quite a lot of outdated pages as we rely on the updates coming to the docs also from the community. Thanks for your input advance.

**Comment by andrewconnell** [comment]
That's not correct at the present time (it might have been correct when this comment was posted though)... PowerShell is available in Azure Functions v2:

https://azure.microsoft.com/blog/serverless-automation-using-powershell-preview-in-azure-functions
