### ISSUE TITLE
Where's the documentation to subscribe to webhooks programmatically?

### ISSUE THREAD

**Issue by sshresthareach** [SharePoint/sp-dev-docs#2827]
[Enter feedback here]
The Postman example is great but where's the documentation to achieve this using proper Oauth flow programmatically?
Adding resource to the token endpoint gives this:
AADSTS90100: The 'resource' request parameter is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4f4088-693d-ba29-ddbf-797f9499389e
* Version Independent ID: aa0efa43-034a-8b34-593b-04c5109526ec
* Content: [Get started with SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/get-started-webhooks)
* Content Source: [docs/apis/webhooks/get-started-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/get-started-webhooks.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sshresthareach** [comment]
I am probably wrong about this, but are webhooks only meant for intranet sites? The subscription api does not seem to be calling the Graph API in the documentation.

**Comment by Seiyasu** [comment]
>but are webhooks only meant for intranet sites? 

No. The webhooks works well for internet too. 
You can see the (**personal Microsoft account**) in https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions?view=odsp-graph-online

**Comment by Daedalus72** [comment]
How to modify the controller method when using .Net Core Web Api? It doesn't work on .net core no calls to the method are performed.

**Comment by andrewconnell** [comment]
@sshresthareach This article uses PostMan to show the webhook. There's another article int his same section that has a full reference implementation you can explore: https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation
