### ISSUE TITLE
Incorrect signature of the onPropertyPaneFieldChanged in the docs

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#283]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
The correct signature of the `onPropertyPaneFieldChanged` method is:

```ts
protected onPropertyPaneFieldChanged(propertyPath: string, oldValue: any, newValue: any): void;
```

#### Observed Behavior
According to the [drop 6 release notes](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-6#interface-ipropertypanedata) the signature is:

```ts
onPropertyPaneFieldChanged: (propertyName: string, newValue: any) => void
```

#### Steps to Reproduce
n/a

**Comment by frankchen76** [comment]
I think we need to update to latest signature as the following: 
`protected onPropertyPaneFieldChanged(propertyPath: string, oldValue: any, newValue: any): void`
I also raised a issue on [SharePoint StackExchange](http://sharepoint.stackexchange.com/questions/200721/spfx-webpart-onpropertychanged-didnt-fire-after-controls-content-was-changed)

**Comment by patmill** [comment]
Official docs are correct (https://dev.office.com/sharepoint/reference/spfx/sp-webpart-base/onpropertypanefieldchanged-baseclientsidewebpart).  Closing...
