### ISSUE TITLE
You lost me during 'Create the Azure Function'

### ISSUE THREAD

**Issue by bengtmoss** [SharePoint/sp-dev-docs#2835]
...in step 4, where it says "From the Language drop-down box, select PowerShell".
There is no such box. I have no clue how to continue from here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The docs is based on Azure Function 1.x. The latest Azure Function is 2.0 and it haven't support PowerShell. So you need try to change the Azure Function version in the Azure portal.

**Comment by bengtmoss** [comment]
Yes, _and_ change a few settings to get over a bug that prevents the _Experimental Language Support_ from being shown, see [](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/99f53950-97cd-419a-9090-93ffc004bcf3/azure-functions-powershell-language-support?forum=AzureFunctions&prof=required)
