### ISSUE TITLE
ZH-CN document is not up to date

### ISSUE THREAD

**Issue by foxdave** [SharePoint/sp-dev-docs#2837]
Hi
I notice that many zh-cn docs are not up to date. Could you open the edit permission for SharePoint related zh-cn docs so that we can contribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49973150-1704-97fb-c59c-8b528f98b318
* Version Independent ID: edc03e3d-5bde-22d5-cb71-6a7a7fb523ba
* Content: [SharePoint Server 2019 development platform](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-2019-development-platform)
* Content Source: [docs/general-development/sharepoint-2019-development-platform.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-2019-development-platform.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thank you for your post. I have submit your question to the content teams. And any update will sync you.

**Comment by foxdave** [comment]
So what is going on? 2 month passed..
