### ISSUE TITLE
Incorrect behavior of the Dropdown Office UI Fabric React component (drop-6)

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#284]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
After changing the value of the `isDisabled` property the component should be disabled if the value is set to `true` and enabled if the value is set to `false`.

#### Observed Behavior
When the component is initiated with `isDisabled=false` and then changed to `isDisabled=true` the component remains enabled. When it then gets switched to `isDisabled=false` it becomes enabled.

It seems like this behavior is caused by incorrect implementation of the component. In the Dropdown.tsx file on line 50 the `componentWillReceiveProps` method incorrectly uses `this.properties` rather than `newProps` to determine the current state of the component. While the current state is correctly passed in the `newProps` argument, the code uses the previous state from `this.properties`.

#### Steps to Reproduce
Build new SPFx project with a default web part. Replace the code with:

```ts
import * as React from 'react';
import { css, Button, Dropdown } from 'office-ui-fabric-react';

import styles from '../HelloWorld.module.scss';
import { IHelloWorldWebPartProps } from '../IHelloWorldWebPartProps';

export interface IHelloWorldProps extends IHelloWorldWebPartProps {
}

export interface IHelloWorldState {
  disabled: boolean;
}

export default class HelloWorld extends React.Component<IHelloWorldProps, IHelloWorldState> {
  constructor(props: IHelloWorldProps) {
    super(props);

    this.state = {
      disabled: false
    };

    this.toggleDropdown = this.toggleDropdown.bind(this);
  }

  public render(): JSX.Element {
    return (
      <div className={styles.helloWorld}>
        Disabled: {this.state.disabled.toString()}
        <Dropdown
          isDisabled={this.state.disabled}
          label={'Dropdown'}
          options={[
            {
              text: 'Option 1',
              index: 1,
              key: 1
            },
            {
              text: 'Option 2',
              index: 2,
              key: 2
            }
          ]} />
        <Button onClick={this.toggleDropdown}>Toggle</Button>
      </div>
    );
  }

  private toggleDropdown(): void {
    this.setState({
      disabled: !this.state.disabled
    });
  }
}
```

Click the button to toggle the dropdown disabled state. Notice how the value of the disabled property doesn't match the state of the dropdown.

**Comment by srideshpande** [comment]
Hello @waldekmastykarz - Thanks for reporting it to us. Sorry for the delayed response. If you are still seeing this issue, here is what you are doing wrong. The property `disabled` is all lower cased.

Please check and let me know if you still see this issue. I am closing the issue now. Please feel free to re-open it if you think you need our attention here.

Thanks!

**Comment by waldekmastykarz** [comment]
The issue wasn't related to me using `isDisabled` instead of `disabled`. Instead it was a bug in the component at the time of submitting this issue.

At this moment, both `isDisabled` and `disabled` are defined and work as expected. The `isDisabled` property is marked as deprecated in the future versions.
