### ISSUE TITLE
Multiple fields creation in single request hit

### ISSUE THREAD

**Issue by shailesh-sangekar** [SharePoint/sp-dev-docs#2842]
We have some requirement where we need to create list dynamically. We tried to use createFieldAsXml for multiple fields creation with xml schema. 

`var fieldXML = "<  Field Type='Text' Required='FALSE' StaticName='myTechName' Name='myTechName' DisplayName='My name to displayed' />";
 
$pnp.sp.web.lists.getByTitle('My List').fields.createFieldAsXml(fieldXML).then(function(result) {
	console.log(result); 
});`

This work with single field, but what about multiple fields in single request hit. I tried it with multiple fields taking reference of element file but facing following issue. 

{"odata.error":{"code":"-1, System.Xml.XmlException","message":{"lang":"en-US","value":"Unexpected end of file has occurred. The following elements are not closed: Fields. Line 1, position 232."}}}

Please suggest the correct way to add multiple fields while list creation or later. 
Note : We have different type of fields to add.

**Comment by Seiyasu** [comment]
What you've done on creating multiple fields, such as the reproduce steps or script/code?

**Comment by shailesh-sangekar** [comment]
Thank you Seiyasu for your suggestion, The baching worked for me. 
But I think we can enhance operation and add option to create a list with fields.
