### ISSUE TITLE
Wrong header name

### ISSUE THREAD

**Issue by DanishIslam07** [SharePoint/sp-dev-docs#2847]
Under "Detailed Syntax reference", "hideListHeader" is written which should be "hideColumnHeader".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for pointing this out! both `hideListHeader` and `hideColumnHeader` work within view formatting (they do the same thing), but you are correct that the standard/supported property is `hideColumnHeader`. I've submitted an update to correct this.

**Comment by Jaycee75** [comment]
Neither appear to now work - I cant seem to get rid of column headers using examples above
