### ISSUE TITLE
Cannot open a modern (hub) site [ErrorCategory=spfx&Workload=SPPages&Name=SpfxLoad]

### ISSUE THREAD

**Issue by RobinBreman** [SharePoint/sp-dev-docs#2848]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

Cannot open certain modern sites any more, by putting in the url, it redirects to error.aspx with a reference to `ErrorDetails=Error%3A%20GetClientSideComponents%20failed%20with%20HTTP%20status%20403&ErrorCategory=spfx&Workload=SPPages&Name=SpfxLoad`

No spfx components are added to these sites.

#### Expected or Desired Behavior

Open a site by directly putting in the url in the address window e.g.  https://tenant.sharepoint.com/sites/HubSite1

#### Observed Behavior

The page redirects to `https://tenant.sharepoint.com/sites/HubSite1/_layouts/15/error.aspx?ErrorCorrelationId=c36a9d9e-f042-7000-5f31-ae0294adac0d&ErrorText=De%20toepassing%20kan%20niet%20worden%20geladen%20op%20deze%20pagina.%20Gebruik%20de%20knop%20Terug%20van%20de%20browser%20om%20het%20opnieuw%20te%20proberen.%20Stuur%20de%20beheerder%20van%20de%20site%20de%20informatie%20in%20Technische%20details%20als%20het%20probleem%20zich%20blijft%20voordoen.&ErrorDetails=Error%3A%20GetClientSideComponents%20failed%20with%20HTTP%20status%20403&ErrorCategory=spfx&Workload=SPPages&Name=SpfxLoad`

The page is not loaded.
console.log:
`Navigated to https://tenant.sharepoint.com/sites/HubSite1/
VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673 
Waarschuwing!Als u dit hulpprogramma gebruikt, wordt u blootgesteld aan potentiële beveiligingsrisico's die ertoe kunnen leiden dat anderen toegang krijgen tot uw persoonlijke Office 365-gegevens (documenten, e-mailberichten, gesprekken en meer). Zorg ervoor dat u de persoon of organisatie vertrouwt die toegang tot dit hulpprogramma vraagt, voordat u doorgaat.Meer informatie: https://technet.microsoft.com/en-us/library/bb794823.aspx
VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073 POST https://tenant.sharepoint.com/sites/HubSite1/_api/web/GetClientSideComponents 403
e.fetch @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.fetchCore @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e._fetchWithInstrumentation @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
Promise.then (async)
e.fetch @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.post @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.tryGetManifests @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
e.requestManifests @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
e._startApplication @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
e._startApplication @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
Promise.then (async)
e.start @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
startSpfx @ (index):59
(anonymous) @ (index):67
(anonymous) @ (index):84
VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073 POST https://tenant.sharepoint.com/sites/HubSite1/_api/web/GetClientSideComponents 403
e.fetch @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.fetchCore @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e._fetchWithInstrumentation @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
Promise.then (async)
e.fetch @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.post @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1073
e.tryGetManifests @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
e.requestManifests @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
Promise.catch (async)
e._startApplication @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
e._startApplication @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
(anonymous) @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
Promise.then (async)
e.start @ VM188 sp-pages-assembly_nl-nl_60c78269ec95580dd76ce392843b746e.js:1673
startSpfx @ (index):59
(anonymous) @ (index):67
(anonymous) @ (index):84
Navigated to https://tenant.sharepoint.com/sites/HubSite1/_layouts/15/error.aspx?ErrorCorrelationId=a76c9d9e-10c8-7000-5f31-a3f692198036&ErrorText=De%20toepassing%20kan%20niet%20worden%20geladen%20op%20deze%20pagina.%20Gebruik%20de%20knop%20Terug%20van%20de%20browser%20om%20het%20opnieuw%20te%20proberen.%20Stuur%20de%20beheerder%20van%20de%20site%20de%20informatie%20in%20Technische%20details%20als%20het%20probleem%20zich%20blijft%20voordoen.&ErrorDetails=Error%3A%20GetClientSideComponents%20failed%20with%20HTTP%20status%20403&ErrorCategory=spfx&Workload=SPPages&Name=SpfxLoad`

When using the link from the hubsite navigation, on a site joined to this hub the site is opened correctly.

The https://tenant.sharepoint.com/sites/HubSite1/_layouts/15/viewlsts.aspx?view=14 page keeps reloading it selve.. or when it does show, it won't show any content.

Also the following error is shown very often https://tenant.sharepoint.com/sites/HubSite1/_layouts/15/AccessDenied.aspx?Source=https%3A%2F%2Ftenant.sharepoint.com%2Fsites%2FHubSite1%2F_layouts%2F15%2Fviewlsts.aspx%3Fview%3D15&Type=list&correlation=736c9d9e-20b8-7000-5f31-a561e08e3ada

#### Steps to Reproduce

Open site by pasting url in the browsers location bar - > error
Follow link from site joined to hub (to the same location) - > success

**Comment by VesaJuvonen** [comment]
If these are oob sites without any customizations, you should be reporting this issue using the support channels from the Tenant administrative UIs as we can only support development topics through this channel. You will also get more efficient support if you open the issue using standard channel from your tenant admin UI, so closing this one.
