### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JoelFerreira1984** [SharePoint/sp-dev-docs#2849]
My path is not created, powershell is running as administrator, error bellow, in the logs i dint find any clue

All the automatic steps are now completed!
Please proceed with the manual steps documented on the Setup Guide!
Get-Item : Cannot find path 'C:\sp-dev-gdpr-activity-hub-master\sp-dev-gdpr-activity-hub-master\GDPRStarterKit\sharepoint\solution\gdpr-starter-kit.sppkg' because it does not exist.
At C:\sp-dev-gdpr-activity-hub-master\sp-dev-gdpr-activity-hub-master\Scripts\Provision-GDPRActivityHub.ps1:148 char:23
+ ... ppkgPath = (Get-Item -Path "..\GDPRStarterKit\sharepoint\solution\gdp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\sp-dev-gdpr-...arter-kit.sppkg:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

You can find the .SPPKG file at the following path:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Hi @JoelFerreira1984 - exception tells that the sppkg file does not exist in the provided folder which you used. I'm also not quite sure how this relates on the document which this was added as a comment as that is around setting up the SharePoint Framework dev environment and not around the GDPR solution from https://github.com/SharePoint/sp-dev-gdpr-activity-hub.

We would need to understand what you are doing before we can solve the issue with the paths you use etc. Can you provide more details - thx.

**Comment by JoelFerreira1984** [comment]
Hi @VesaJuvonen 

Thanks for the quick reply

I am following your guide here ->https://github.com/SharePoint/sp-dev-gdpr-activity-hub/blob/master/Documentation/Setup-Guide.md

I am stuck on this step with warnings and errors and the SPFx package that i need to upload on sharepoint is not created i dont know why 

Please look the script output below, hopefully you can tell me whats missing or doing wrong

.\Provision-GDPRActivityHub.ps1 -GroupSiteUrl "https://<your-tenant-name>.sharepoint.com/sites/<your-group-site-URL>" `
                                -Credentials $credentials `
                                -ConfigureCDN `
                                -CDNSiteName "CDN" `
                                -CDNLibraryName "CDNFiles"

I am running this script on Powershell in the scripts folder

Here is the full script output results

Creating artifacts on target site https://x.sharepoint.com/sites/GDPR2
Apply-PnPProvisioningTemplate : Microsoft.Workflow.Client.ActivityValidationException: Workflow XAML failed validation due to the following errors:
Character '0' was unexpected in string '0'.  Invalid XAML type name.
 HTTP headers received from the server - ActivityId: 837a14e5-937f-47d4-9507-93c847f2daf8. NodeId: . Scope: . Client ActivityId : b77d9d9e-40a6-7000-3362-eaf9e782dec8. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.Workflow.Common.AsyncResult.End[TAsyncResult
At C:\GDPR\Scripts\Provision-GDPRActivityHub.ps1:73 char:9
+         Apply-PnPProvisioningTemplate -Path .\GDPR-Activity-Hub-Workf ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Configuring the Office 365 CDN Settings
WARNING: Execute-PnPQuery has been deprecated. Use Invoke-PnPQuery instead.
Creating CDN Site Collection
.............Building SPFx package and bundling

> node-sass@3.13.1 install C:\GDPR\GDPRStarterKit\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\GDPR\GDPRStarterKit\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\GDPR\GDPRStarterKit\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\\GDPR\\GDPRStarterKit\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\GDPR\GDPRStarterKit\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\GDPR\GDPRStarterKit\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:13:12)\n    at F (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:68:19)\n    at E (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:80:29)\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:89:16\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\isexe\\index.js:42:5\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\\GDPR\GDPRStarterKit\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:13:12)\n    at F (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:68:19)\n    at E (C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:80:29)\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\which\\which.js:89:16\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\isexe\\index.js:42:5\n    at C:\\\\GDPR\\GDPRStarterKit\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
gyp verb command install [ '10.13.0' ]
gyp verb install input version string "10.13.0"
gyp verb install installing version: 10.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.13.0
gyp verb build dir attempting to create "build" dir: C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\\GDPR\GDPRStarterKit\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\\GDPR\GDPRStarterKit\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\joel.ferreira\\.node-gyp\\10.13.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\joel.ferreira\\.node-gyp\\10.13.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\joel.ferreira\\.node-gyp\\10.13.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\joel.ferreira\.node-gyp\10.13.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 30/10/2018 15:58:38.
Project "C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\
\GDPR\GDPRStarterKit\node_modules\node-sass\build\binding.sln]
Done Building Project "C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"C:\\GDPR\GDPRStarterKit\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\cp
as\GDPR\GDPRStarterKit\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.51
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\GDPR\GDPRStarterKit\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\\\GDPR\\GDPRStarterKit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\\GDPR\GDPRStarterKit\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN react-star-rating-component@1.4.1 requires a peer of react@^16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joel.ferreira\AppData\Roaming\npm-cache\_logs\2018-10-30T15_58_40_295Z-debug.log
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\\GDPR\GDPRStarterKit\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\\GDPR\GDPRStarterKit\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\\GDPR\GDPRStarterKit\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\\GDPR\GDPRStarterKit\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Uploading SPFx assets to the CDN
WARNING: Execute-PnPQuery has been deprecated. Use Invoke-PnPQuery instead.
dir : Cannot find path 'C:\\GDPR\GDPRStarterKit\temp\deploy' because it does not exist.
At C:\\GDPR\Scripts\Provision-GDPRActivityHub.ps1:133 char:32
+ ...          foreach ($file in (dir ..\GDPRStarterKit\temp\deploy -File))
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\\GDPR\GDPRStarterKit\temp\deploy:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


WARNING: This is a feature built on a 3rd party application with privacy and compliance standards that differ from the commitments outlined by the Microsoft Office365 Trust Center. Any data cached through this service does not conform to the Microsoft Data Processing
Terms (DPT) and is outside of the Microsoft Office365 Trust Center compliance boundaries.

WARNING: Files of type CSS,EOT,GIF,ICO,JPEG,JPG,JS,MAP,PNG,SVG,TTF,WOFF stored in the locations configured to serve as Public CDN origins will now also be served and cached in Content Delivery Network (CDN). Such content will then be accessible by everyone anonymously
not monitored nor governed by Microsoft content policies.

Public CDN enabled locations:
*/MASTERPAGE
*/STYLE LIBRARY
*/CLIENTSIDEASSETS
SITES/CDN/CDNFILES
SITES/CDN1/CDNFILES1
SITES/CDN2/CDNFILES2
SITES/CDN3/CDNFILES3
SITES/CDN4/CDNFILES4
SITES/CDN5/CDNFILES5
SITES/CDN6/CDNFILES6
SITES/CDN7/CDNFILES7
SITES/CDN8/CDNFILES8


Public CDN enabled locations:
*/MASTERPAGE
*/STYLE LIBRARY
*/CLIENTSIDEASSETS
SITES/CDN/CDNFILES
SITES/CDN1/CDNFILES1
SITES/CDN2/CDNFILES2
SITES/CDN3/CDNFILES3
SITES/CDN4/CDNFILES4
SITES/CDN5/CDNFILES5
SITES/CDN6/CDNFILES6
SITES/CDN7/CDNFILES7
SITES/CDN8/CDNFILES8
SITES/CDN1/CDNFILES (configuration pending)

All the automatic steps are now completed!
Please proceed with the manual steps documented on the Setup Guide!
Get-Item : Cannot find path 'C:\\GDPR\GDPRStarterKit\sharepoint\solution\gdpr-starter-kit.sppkg' because it does not exist.
At C:\\GDPR\Scripts\Provision-GDPRActivityHub.ps1:148 char:23
+ ... ppkgPath = (Get-Item -Path "..\GDPRStarterKit\sharepoint\solution\gdp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\\GDPR\GD...arter-kit.sppkg:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

You can find the .SPPKG file at the following path:

**Comment by JoelFerreira1984** [comment]
Configuring the Office 365 CDN Settings
WARNING: Execute-PnPQuery has been deprecated. Use Invoke-PnPQuery instead.
Creating CDN Site Collection

Are these warnings a reason for failing?
