### ISSUE TITLE
Hero Selection Box Never Dies (and covers stuff up)

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#2852]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Clicking on a Hero web part link shows a highlighted border to indicate selection. Clicking anywhere else should remove this border. Even when the border is showing, it should be beneath the search suggestions drop down.

#### Observed Behavior

Clicking on a Hero web part link shows the highlighted border to indicate selection. However, it only goes away when you select another hero web part link.

Additionally, this highlighted border shows above the search suggestions dropdown and also the Feedback buttons on the bottom-right. This is ugly.

![Hero Highlighting Issue](https://thechriskent.files.wordpress.com/2018/10/heroselectionborder1.gif)

Seems like a z-index problem with the Hero web part and also an issue that the selection never goes away when the web part loses focus.

#### Steps to Reproduce

- Create a communication site using the Topic design (anything with the hero webpart).
- Click on a link.
- Close the new window.
- Notice the highlighted border.
- Try and click anywhere else to have it go away.
- Open the search suggestions and see that the highlighted border covers the drop down as well as the feedback buttons.
- Shed a tear.

**Comment by Seiyasu** [comment]
The main cause should be selection never reset after loses focus.

**Comment by thechriskent** [comment]
@Seiyasu that is the main problem, but the z-index is also an issue since it covers up the Feedback buttons (even if it went away once it lost focus).

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we cannot route this properly using this process. This is clearly inconvenient UI issue, but it would need to get reported either using UserVoice or normal support channels.
