### ISSUE TITLE
SPFx Solutions Versioning doesn't work as expected

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2854]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

For packages with disabled Tenant-wide deployment new version should be applied only when the app is updated for the specific site.

#### Observed Behavior

The latest version of the code is automatically available, even if the app has not been updated.

#### Steps to Reproduce

1. create simple web part project with `yo @microsoft/sharepoint`
2. Select default N option for Tenant-wide deployment
3. build the package (`gulp bundle --ship`, `gulp package-solution --ship`).
4. Add package to the App Catalog
5. Install the App on some site
6. Add Web part to a page.
7. Update web part code with some changes. For example, change the header from default one to any other text.
8. Change the version in `package-solution.json`
9. `gulp clean`, `gulp bundle --ship`, `gulp package-solution --ship`
10. Add new version of the package to App Catalog
11. **Go directly to the page with the web part and refresh it**
12. New text has appeared.

In that scenario we still should see the old text as the app has not been updated for the site. But new code has been applied automatically.

**Comment by semopz** [comment]
I can confirm. I thought this was a feature!

What if you desired this behaviour though? Say you found a serious issue and wanted to patch it wherever your app was installed available. Would you have to walk your webs to find where the app was installed. SPO is so slow these days that a script will probably take about a day to finish on the tenant I'm managing.

**Comment by AJIXuMuK** [comment]
I've received a response from @VesaJuvonen in Twitter that it's by design.
Closing this one.

**Comment by AJIXuMuK** [comment]
@semopz so, as you can see, it's confusing :)
That's why I was asking that here, to be completely on the same page.

**Comment by guillaume-kizilian** [comment]
So...
Are SPFx Solutions Versioning pointless then ?
Is it useful in some cases ?

Are SPFx Librairies working in the same way. Meaning you have to maintain every webpart that use it at each evolution ?

**Comment by AJIXuMuK** [comment]
Technically yes. As soon as you deploy any SPFx solution to App Catalog, you’ll have the latest version across tenant.

**Comment by PopWarner** [comment]
@guillaume-kizilian also, last I checked, if you have complex feature framework changes in the solution, such as creating a new site column, content type, etc, that will be delayed until you upgrade the solution and that can be useful. :)

**Comment by a2life** [comment]
I was also confused but now I understand the versioning is for asset provisionings and not for the code deployment.   I had to think about this.  Lets say if I provision a new list in version 2 of the solution.  The list will not be created until the upgrade is done in the target site.   As soon as a new version is uploaded to the AppCatalog though, the new code may try to acccess the  list that is yet to exist.  So its either I need to protect a code for non existent list (Ok, I should do it anyway haha)  or forget about bundling code and assets,  just create a solution for assets deployment and ensure everyone upgrade and have needed asset installed and then deploy the updated code in the scenario like this.

**Comment by AJIXuMuK** [comment]
@a2life I agree with you that it is confusing.
The most popular response on that would be "Feature Framework is bad. Use some other options".
But anyway, your code should be always backward compatible as you can't control your customers to actually upgrade...

**Comment by guillaume-kizilian** [comment]
@PopWarner I had higher expectations than a SP Site ressources versioner

@AJIXuMuK & @a2life  I agree you can't force your "client" to upgrade. And that is why i want nothing to move until they do. You can still handle it in your code but it's not a good enough security, and you don't use frameworks to code everything yourself.

I have 18 webparts + 1 common library and if I move my library to SPFx library i'll have to test regressions on each of them every time the library moves (since SP and front is not great for U.T.). So for now every webparts package the library and I have no other choice to let those 18 copies like this :+1:

Thank you for your answers though.
