### ISSUE TITLE
SP.MoveCopyUtil.MoveFileByPath null response exception using SPHttpClientBatch

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#2857]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using SPHttpClientBatch, MoveFileByPath sessions should not fail on the execute() method if the documents have actually moved.

Maybe there is an option to specify that empty body responses are 'ok' but documentation about this should be provided for SPHttpClientBatch.

#### Observed Behavior
It looks like MoveFileByPath sessions batched using SPHttpClientBatch respond with an empty body. The batch session throws an exception which means I don't get resolve the batched promises. The batch job looks like it is returning 200 HTTP response so all the more reason for the batch session to succeed 
rather than fail.

My batch session returns a response of 200 and on the console I see this:
![](https://i.imgur.com/OyLHk5r.png)

#### Steps to Reproduce
This is a continuation from https://github.com/SharePoint/sp-dev-docs/issues/2756.

1. Create a 1.60 SPFx webpart using the --plusbeta switch (else the SPHttpClientBatch won't be available for import)
2. paste the code below into the render method inside HelloWorldWebPart.ts (assuming you kept to the default answers)
3. Create a library and upload a single file and a folder
4. Assign the file absolute file path of your file to srcFileUrl0
5. Specify the new file path in dstFileUrl0
6. Add more files if desired, the result will be the same
6. gulp serve
7. add webpart to hosted workbench
8. Observe error message in console
9. Inspect traffic for $batch with response code status of 200

```typescript
    const currentWebUrl: string = this.context.pageContext.web.absoluteUrl;
    const spBatchCreationOpts: ISPHttpClientBatchCreationOptions = { webUrl: currentWebUrl };
    const spBatch: SPHttpClientBatch = this.context.spHttpClient.beginBatch(spBatchCreationOpts);
    let srcFileUrl0 = `<Old File Path>`;
    let dstFileUrl0 = `<New File Path>`;
    let bodyOptions0 = {
      "srcPath": {
        "DecodedUrl": srcFileUrl0
      },
      "destPath": {
        "DecodedUrl": dstFileUrl0
      }
    };

    const opt0: ISPHttpClientBatchOptions = {
      headers: {
        "Content-Type": "application/json;odata=verbose"
      },
      body: JSON.stringify(bodyOptions0)
    };

    const moveDoc0 = spBatch
      .post(
        `${currentWebUrl}/_api/SP.MoveCopyUtil.MoveFileByPath()`,
        SPHttpClientBatch.configurations.v1,
        opt0
      );

    spBatch
      .execute()
      .then(() => {
        console.log(`Yay, it worked`);
      })
      .catch(batchError => console.log(`Batch Error: `, batchError));
```

**Comment by Seiyasu** [comment]
I still think the no body exception is OK, we need to handle the response state by our self.

**Comment by semopz** [comment]
But the $batch session status code is 200. So why does .execute() throw an exception? Are you saying I should just write all my logic in the catch block (referring to my code above)
