### ISSUE TITLE
Link to current LTS points to 10.x

### ISSUE THREAD

**Issue by thlbrg** [SharePoint/sp-dev-docs#2863]
As of 2018-10-30 the latest LTS for NodeJS is 10.x, but as stated 10.x is not supported for SharePoint Framework development, link needs to be updated to point to 8.x until SharePoint framework supports 10.x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. We can just change the text order but not the actual link. And you can submit pull request for the article too.

**Comment by s-KaiNet** [comment]
Any news on nodejs 10.x support? 10.13 is current LTS version:
![image](https://user-images.githubusercontent.com/10658276/48313100-c1a78000-e5c8-11e8-9443-c2d79a187521.png)

**Comment by Seiyasu** [comment]
@thlbrg Link have been updated. Thanks. 
@s-KaiNet No any official news for that.
