### ISSUE TITLE
AADHttpClient-An OAuth permission with the scope user_impersonation could not be found.

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#2866]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
Hi , I have an Azure function secured by azure AD and I am calling it from an spfx webpart using the docs at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi. 

The Azure AD registratcion looks like this:

![image](https://user-images.githubusercontent.com/2412956/47874499-5ef4fe00-ddea-11e8-835e-439a87dab0fa.png)

My Package solution contains:

"webApiPermissionRequests": [
{
"resource": "GRCRoleToTransactionAzureFunction",
"scope": "user_impersonation"
}
]

When a tenant admin tried to approve the request from the new portal, he got the following error:
![image](https://user-images.githubusercontent.com/2412956/47874584-9663aa80-ddea-11e8-9622-04e118689d81.png)

How do I get this approved?

**Comment by Seiyasu** [comment]
The exception mean you doesn't set the user_impersonation correctly. It is not SharePoint dev issue but configure issue. 
You can reference this [issue](https://github.com/SharePoint/sp-dev-docs/issues/2601).

**Comment by waldekmastykarz** [comment]
In Azure AD, open the Azure AD app's manifest and verify is `user_impersonation` is among OAuth permissions defined in the app.

**Comment by russgove** [comment]
It's in there:
...
"logoutUrl": null,
  "oauth2AllowImplicitFlow": false,
  "oauth2AllowUrlPathMatching": false,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access GRCRoleToTransactionAzureFunction on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access GRCRoleToTransactionAzureFunction",
      "id": "4938f370-a6f8-4794-ae1f-ec93b251d256",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access GRCRoleToTransactionAzureFunction on your behalf.",
      "userConsentDisplayName": "Access GRCRoleToTransactionAzureFunction",
      "value": "user_impersonation"
    }
  ],
  "oauth2RequirePostResponse": false,
  "objectId": "25dfbd81-9218-471d-851d-ad90386cf600",
...

**Comment by waldekmastykarz** [comment]
Ah, could it be that the other pending permission, where the resource is denoted with a GUID is causing trouble? Could you please remove it and see if you can approve the pending permission request then?

**Comment by russgove** [comment]
I rejected the one  with the guid and still got the same issue
![image](https://user-images.githubusercontent.com/2412956/47952638-e6f11a00-df48-11e8-9dca-1190569a9bb5.png)

**Comment by waldekmastykarz** [comment]
Is the app in the same AAD as your Office 365 tenant?

**Comment by russgove** [comment]
It is. I am a corporate dev. Only have access to one tenant.

**Comment by waldekmastykarz** [comment]
Could you remove the pending permission request and see if you can directly add a grant using PowerShell: https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/approve-spotenantserviceprincipalpermissiongrant?view=sharepoint-ps

**Comment by russgove** [comment]
Not sure that i have the parameters correct, but i get this:
![image](https://user-images.githubusercontent.com/2412956/48008364-83e9b980-e0e7-11e8-9e5e-89df1a3ca31e.png)

**Comment by russgove** [comment]
@VesaJuvonen any ideas on this?

**Comment by russgove** [comment]
Anybody? I am blocked here!

**Comment by waldekmastykarz** [comment]
I stumbled upon it just recently. In my case, this exact error was caused by another Azure AD app with the same name already present in the Azure AD. You can solve it either by removing the old app or renaming the new one.

**Comment by russgove** [comment]
I went into Azure App Registrations and there is only one app shown.

**Comment by AJIXuMuK** [comment]
Could it be the case thst your app is named as some of ootb apps provided by Microsoft? Just a coincidence...

**Comment by waldekmastykarz** [comment]
Is the Azure AD app registered in the same AAD as used by O365?

**Comment by waldekmastykarz** [comment]
Btw, I stand corrected: you sholdn't be looking at the app name but the App ID URI, which you can see through app's properties. Is it possible that you have an app with a different name but the same App ID URI?

**Comment by russgove** [comment]
You're a genious waldek!  I renamed the app registrationn  and now instead of the previous error I get '[HTTP]:500 -  [CorrelationId]:3e56a39e-9067-7000-9a0c-e11cf680f643 [Version]:16.0.0.8307 - Insufficient privileges to complete the operation.' 

I'm not a tenant admin, so I expect that. Will have a tenant admin approve on Monday.  and close  this issue,

It is strange that I only saw one app registration though.  are there some kind of 'hidden' app registrations?

**Comment by russgove** [comment]
btw, i see no duplicate app-ids when i go to app registrations 
![image](https://user-images.githubusercontent.com/2412956/48665216-d4aeca00-ea78-11e8-959a-a86743057733.png)
Renaming  from GRCRoleToTransactionAzureFunction to GRCRoleToTransactionAzureFunctionTWO seems to have fixed the issue

**Comment by waldekmastykarz** [comment]
It wouldn't be the App ID, but the App ID URI that would be duplicate. Either way, good to hear you're unblocked.

**Comment by waldekmastykarz** [comment]
In the second case it says that the API permission has already been granted. is that the case, or is the API permission still not granted despite the error message?

**Comment by russgove** [comment]
Hi,  I switched to a powerapps solution to avoid this issue, so am i am closing this ticket for now.

If the powerapps doesn't fly , I'll re-open,
