### ISSUE TITLE
Workbench.html is blank in IE with js errors in dev tools

### ISSUE THREAD

**Issue by rrtoland** [SharePoint/sp-dev-docs#2872]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hey gang. started a fresh machine configuration today and was building a new webpart when I hit a snag.  I thought it was maybe my code but I went all the way back to basics and noticed an issue in IE (working on Chrome and Edge). 
#### Expected or Desired Behavior
On gulp serve the default browser should open up to the workbench and I should see the ability to add my hello world webpart.  This appears to work on Chrome and Edge.
![image](https://user-images.githubusercontent.com/15697243/47933392-1137ce80-de9a-11e8-8d1b-1d399c6bf7f6.png)

![image](https://user-images.githubusercontent.com/15697243/47933366-03824900-de9a-11e8-93b9-29f2fb8c793c.png)

#### Observed Behavior
On the other hand, IE comes up blank and as I suspected the console logged two issues.  

![image](https://user-images.githubusercontent.com/15697243/47933330-ec435b80-de99-11e8-8aa0-25e89f7d0590.png)

Here is my version info: 

![image](https://user-images.githubusercontent.com/15697243/47933464-404e4000-de9a-11e8-8fa7-eb7c18be42d6.png)

node @ v8.11.4
+ yo@2.0.5
+ gulp@3.9.1

Is it me or my machine?  Again, only appears to be a problem on IE

**Comment by KingKangMSFT** [comment]
Thanks @rrtoland . I have tried to create a webpart. And it works fine on IE, could you please provide the version of the sharepoint generator

**Comment by rrtoland** [comment]
Sure thing!

![image](https://user-images.githubusercontent.com/15697243/48006125-5e9e8080-e0d2-11e8-87f7-a391e12a0a8d.png)

PS C:\> npm view @microsoft/generator-sharepoint version
1.6.0

Hope this helps!

**Comment by AlexanderShapoval** [comment]
Greetings,

I've experienced the same issue.
Currently, I have installed next package versions (theoretically, they should be supported):
![image](https://user-images.githubusercontent.com/3214797/48122807-1b364480-e281-11e8-9baf-9261db25df7e.png)

I've created react project and it's working fine for Chrome but nothing renders for IT:
![image](https://user-images.githubusercontent.com/3214797/48122909-5fc1e000-e281-11e8-8a69-179a8b8a0f2a.png)

**Comment by abhishek-raj** [comment]
Still facing this on IE11 on Windows 10 v1903 - Build version: 18362.356 with SPFx 1.8.2.
![image](https://user-images.githubusercontent.com/8985497/65013659-95236980-d939-11e9-9327-a8e2560be26b.png)

SPFx version - 1.8.2
![image](https://user-images.githubusercontent.com/8985497/65013780-1bd84680-d93a-11e9-9e32-60d147546223.png)

**Comment by abhishek-raj** [comment]
Checked on SPFx 1.9.1 too. Doesn't work there too.
![image](https://user-images.githubusercontent.com/8985497/65014386-30b5d980-d93c-11e9-9f21-ab1f08c53dae.png)

SPFx version - 1.9.1:
![image](https://user-images.githubusercontent.com/8985497/65014419-4d521180-d93c-11e9-9514-04b28c35b2ac.png)

**Comment by srideshpande** [comment]
@rrtoland - Thanks for raising the concern. Yes, we're aware of this issue. It is a browser compatibility issue and the fix will take more effort than required. Also, this is developer only scenario and not a end user scenario. Here are some of the workarounds you can try:

1. Use any other browser for this scenario? 
2. Use hosted workbench

I'm closing the issue. 

Thanks for understanding,
Sri
