### ISSUE TITLE
Graph api not working from sharepoint mobile app.

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#2876]
Hi,
I am using Graph api to access group information. For this I have created and SPFX webpart.
The webpart works fine in chrome and mobile chrome , edge . But when I open the webpart in SharePoint Mobile app, it does not work.
I got this error message.
If required , i can paste the code.
AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: 95ead92c-638f-4cb5-96ae-653e9e244a00
Correlation ID: d906395b-65a0-4fa7-873b-5e458719c1a1
Timestamp: 2018-11-04 17:51:12Z

**Comment by Seiyasu** [comment]
It is duplication issues. You can follow the same issue: #2521 

This is a known issue that we currently have across all rich clients. SPFx graph calls require that the cookie from the browser which contains the access token already exists. PG are working on a generic solution that will work across all non browser clients (teams/android/ios etc).
