### ISSUE TITLE
Create operation need error state

### ISSUE THREAD

**Issue by TonyLi2013** [SharePoint/sp-dev-docs#2878]
if failed, what response will be return?
1. site already exist.
2. site template can not found.
etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d1ea72-8ceb-201c-e2a5-ce75033d246b
* Version Independent ID: 61532d1f-45ab-1100-0fc4-4db441b4c949
* Content: [Create SharePoint Communication site using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/communication-site-creation-rest)
* Content Source: [docs/apis/communication-site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/communication-site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jxnx888** [comment]
@TonyLi2013 Are you able to create a site with the API? Could you please provide the sample code?

**Comment by KingKangMSFT** [comment]
Close the issue for long time no response, Feel free contact us to reopen this issue

**Comment by findyoucef** [comment]
I'm getting a create error with the api returning a 3 every time. How do I resolve this problem. everything else works properly with the api as my GET requests are working properly.
