### ISSUE TITLE
Invalid urls? 

### ISSUE THREAD

**Issue by michalhainc** [SharePoint/sp-dev-docs#2880]
In the code samples, this will produce invalid urls with the doubled '&amp' wont it? 

```
<CommandUIHandler Command="Invoke_RibbonCustomAction1ButtonRequest"
                        CommandAction="~remoteAppUrl/CustomActionTarget.aspx?{StandardTokens}&amp;amp;SPListItemId={SelectedItemId}&amp;amp;SPListId={SelectedListId}"/>
    </CommandUIHandlers>

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49da607-a0ef-c893-7690-a1db560edf54
* Version Independent ID: 89067497-86f2-a301-95d6-d051b8360c98
* Content: [Create custom actions to deploy with SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-custom-actions-to-deploy-with-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/create-custom-actions-to-deploy-with-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-custom-actions-to-deploy-with-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. You can submit an pull request for the content by editing the Content Source.

**Comment by michalhainc** [comment]
Hi I'm sorry, I dont have time to fiddle around and be fixing microsoft's documentation... have enough to do on my own...
