### ISSUE TITLE
EACCES error when gulp serve extension

### ISSUE THREAD

**Issue by michaelmaillot** [SharePoint/sp-dev-docs#2881]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Get extension working in tenant with local debug

#### Observed Behavior

During gulp serve, below the stack trace:

{ Error: listen EACCES 127.0.0.1:4321
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 4321 }
[11:24:23] Error - Unknown
 listen EACCES 127.0.0.1:4321

#### Steps to Reproduce

- Set up new spfx extension project with yo
- initialize environment with "npm i" command
- debug with "gulp serve" command

#### Submission Guidelines

I have upgraded to 1.6 version of the yo template for spfx, as the @microsoft packages dependencies. If I "downgrade" the "@microsoft/sp-build-web" package to 1.4.1 (as it was "1.5.1") in my package.json, I don't have the error.

Thank you in advance for your help ! 😃

**Comment by Seiyasu** [comment]
After you upgrade the SPFx to 1.6 global and retry the reproduce steps, the exception still exist? Or just create project on 1.5 and then upgrade the project to 1.6 will get the exception?

**Comment by Seiyasu** [comment]
Close for long time no response. Feel free to contact with us to reopen it.
