### ISSUE TITLE
3.2.1810.0 App Package upload via Apply-PnPProvisioningTemplate fails with RootSiteUrl error

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/sp-dev-docs#2884]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I should be able to upload an app package to the tenant app catalog via provisioning template like so:

`<pnp:Tenant>
    <pnp:AppCatalog>
      <pnp:Package Src="..\..\sharepoint\solution\mypkg.sppkg" Action="UploadAndPublish" SkipFeatureDeployment="false" Overwrite="true" />
    </pnp:AppCatalog>
    <pnp:StorageEntities>
      <pnp:StorageEntity Key="CONFIG_LIST" Value="My Title" />
    </pnp:StorageEntities>
  </pnp:Tenant>`

#### Observed Behavior

With 3.2.1810.0 the following error occurs:

Apply-PnPProvisioningTemplate : The property or field 'RootSiteUrl' has not been initialized. It has not been requested or the request has not been executed. it may need to be explicitly requested.

Switching back to 3.1.X works.

#### Steps to Reproduce

Apply a template on 3.2.1810.0 targeting Tenant and uploading an app.

**Comment by Seiyasu** [comment]
Due to the PnP is mainly maintained by the community, so the best report place for this issue maybe https://github.com/SharePoint/PnP-PowerShell/issues.

**Comment by 2toLeadMike** [comment]
Thanks, added bug report in correct location

https://github.com/SharePoint/PnP-PowerShell/issues/1762
