### ISSUE TITLE
write-manifest task slow down the build performance

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2885]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Improved build performance

#### Observed Behavior
Whenever a new build gets triggered in SPFx during development the "write-manifest" task try to access several locations in the node_modules folder. These access to the file system can be identified when the gulp gets started through `gulp serve --verbose`.

Following screenshot shows this behaviour in more detail.

![screenshot 2018-11-06 at 16 37 37](https://user-images.githubusercontent.com/5503835/48075141-d065ef80-e1e2-11e8-80b7-a88001a0efc8.png)

Since the files during development can be seen as mostly static this task does not need to get executed each time during a build. Depending on the client's performance this task takes from 1s to 5 seconds.

The questions now do these partial non-existing manifests be accessed all the time during a build or can the be cached or temporary stored when there is no change to the manifest?

This would improve the overall performance at least by one second.

#### Steps to Reproduce

Execute: `gulp serve --verbose`

**Comment by StfBauer** [comment]
On the other hand `gulp build` does not execute the write manifest file at all because the output states that it already exists.

<img width="859" alt="screenshot 2019-01-15 at 00 58 02" src="https://user-images.githubusercontent.com/5503835/51149030-a2df9700-1860-11e9-93de-f06ea152f450.png">

The execution time on this task varies from 350ms in the best case and sometimes up to 1.5 seconds.
On Windows, the performance is slower.

The issue is caused by the file: `node_modules/@microsoft/sp-build-core-tasks/lib/cumulativeManifestProcessor/index.js` on line 151 and ongoing:
It always loops over the files but none of the requested files could be found:
Again this does not look in project files per se, this code looks only in node_modules.

Later in the same code file on the next if statement:
```js
if (!linkedProjectManifests) {
```
Only some manifest.json files can be found all in the Microsoft node_modules folder. So this code is also less selective and does synchronous directory reads even if the file hasn't been changed after installation of node_modules. The same method is called not only in "write-manifest" but also in the "configure-webpart" task.

Following the description of this `generateCumulativeManifest`method the following steps are documented what it actually should do:

```js
 /**
     * Ths function:
     *  1. discovers all packages referenced in package.json
     *  2a. looks for a file in each discovered project's temp folder called manifests.json
     *  2b. looks for <id>.manifest.json files in the dist folder
     *  3. keeps a record of all of the manifests discovered in the referenced projects and resolves duplicates by
     *      taking the newest file
     *  4. generates new base URLs for each of the referenced projects' manifests to make them valid when "gulp serve."
     *      is run from this current project's directory
     *  5. collects all of these discovered manifests and the debugManifests parameter and generates an array of all
     *      manifests
     *  6. filters this array by the ignoreOutputManifestIds options
     *  7. drops a JSON file in the temp directory called manifests.json containing this array
     *  9. drops an initialization script in the temp directory called manifests.js that
     *      exports two functions. One that returns the array with the manifests' base URLs as fully-qualified, and the
     *      other with manifests' base URLs as relative to the page root.
     */
```
In 6 the problem is that the ignoreOutputManifestIds option cannot be filtered because they might haven't been set.
The problem then is in 7 and 8 that the manifest.js file will never be written during the start of `gulp serve` to any general temp directory or caching directory. Instead, those files get written to the dist folder of node_modules at least what I have discovered in my observations. Shouldn't be there a global cache directory instead of writing to packages that can be installed and uninstalled. A thing a folder in the node_modules is no the right place to go.

During my tests I also tried to re-root those folders but failed and stop these experiments for now:

![screenshot 2019-01-15 at 10 51 35](https://user-images.githubusercontent.com/5503835/51172488-9fc1c680-18b3-11e9-8572-1e502c170629.png)

Another thing I discovered in that code was that the `tempFolderName` instead a "real path" was used to save files to the hard drive.

**Comment by quantrpeter** [comment]
so is there any way to make it runs faster? i hit this problem too

**Comment by patmill** [comment]
We will keep this top of mind as we improve build and tooling.  In the meantime, you (and others) can check out the spfx-fast-serve project https://www.npmjs.com/package/spfx-fast-serve
