### ISSUE TITLE
In the modern SharePoint Column Formatting, how can you get the List ID or List Name?

### ISSUE THREAD

**Issue by burgessm83** [SharePoint/sp-dev-docs#2886]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by Seiyasu** [comment]
Do you mean get the list-id/list-name by coding? If not, you can use SharePoint Designer to get the id/name. If not, you can try to get it from spConetxt

**Comment by burgessm83** [comment]
> Do you mean get the list-id/list-name by coding? If not, you can use SharePoint Designer to get the id/name. If not, you can try to get it from spConetxt

I'm specifically looking to do it in the json attached to column formatting in the new SharePoint medern lists

**Comment by Seiyasu** [comment]
[$Id] may get the item id but not the list id. Due to you use JSON column formatting, you cannot get the list id/name. The suggested way is to use [SharePoint Field  Customizer](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer).

**Comment by Seiyasu** [comment]
It seems you should have resolved this issue, so close it now. Feel free let me know if you need to reopen it.
