### ISSUE TITLE
Code Samples for Java/Javascript?

### ISSUE THREAD

**Issue by ViswanathUppu** [SharePoint/sp-dev-docs#2887]
Can we have any code samples for JavaScript/java. If i want to call SharePoint REST API from a web application developed in Java. How can i authenticate SharePoint against user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be50ae2-2435-480a-0c1e-efca679cd00e
* Version Independent ID: d3c81315-c73e-61c8-2287-dc6e6e5eec5c
* Content: [Authorization Code OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
For JavaScript code sample is available:link(https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint). 
For Java code sample, you can reference C # example, a simple conversion can be done.

**Comment by VesaJuvonen** [comment]
As replied and no additional comments, considering that the information was sufficient and closing.
