### ISSUE TITLE
MSGraphClient in an Application Customizer extension returns Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by patrikhellgren** [SharePoint/sp-dev-docs#2888]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
MSGraphClient should be able to renew the token if it has expired.

#### Observed Behavior
I have an Application Customizer extension that uses MSGraphClient which is working as expected but after having been using the VS Code/Chrome debugger for a while while refreshing the page MSGraphClient starts returning an error "Token renewal operation failed due to timeout". After this I can only get it running again by clearing browsing data in Chrome or by logging on as another user.

#### Steps to Reproduce

**1.** Create a new SPFx 1.6 project for SharePoint Online and select to create an ApplicationCustomizer extension and call it GraphTest.
**2.** Replace the application customizer class file with the following code:
````typescript
import { override } from '@microsoft/decorators';
import { Log } from '@microsoft/sp-core-library';
import {
  BaseApplicationCustomizer
} from '@microsoft/sp-application-base';
import { Dialog } from '@microsoft/sp-dialog';
import { MSGraphClient, AadHttpClient, HttpClientResponse } from "@microsoft/sp-http";
import * as strings from 'GraphTestApplicationCustomizerStrings';
const LOG_SOURCE: string = 'GraphTestApplicationCustomizer';
export interface IGraphTestApplicationCustomizerProperties {
  testMessage: string;
}
export default class GraphTestApplicationCustomizer
  extends BaseApplicationCustomizer<IGraphTestApplicationCustomizerProperties> {
  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, "Initialized extension");
    let message: string = this.properties.testMessage;
    if (!message) {
      message = "(No properties were provided.)";
    }
    this.context.msGraphClientFactory.getClient().then((graphClient) => {
      graphClient.api("users").version("v1.0").get((error, users, rawResponse) => {
        if (error) {
          message = error.message;
        }
        else {
          message = "Success";
        }
        Dialog.alert(`Hello from extension:\n\n${message}`);
      });
    });

    return Promise.resolve();
  }
}
````

**3.** Start debugging using VS Code and Chrome and after the page loads you will see a dialog with a "Success" message. You will have to have approved at least User.ReadBasic.All permissions for Microsoft Graph to the SharePoint Online Client Extensibility Web Application Principal service principal first to be able to get this running.

**4.** Wait for an hour and then refresh the page and this time you will see a "Token renewal operation failed due to timeout" message. This message will not go away until you clear the browsing data. This one hour wait is just my estimate and it most likely has to do with the token lifetime, it seems to be very intermittent but as soon as I get the error it seems to stick almost always until I clear the browsing data. I also see this after some time with multiple stopping and starting debugging so I don't have to have the browser running all the time.

**Comment by andrewbackway** [comment]
Hi there, any update on this?
I'm also seeing this across spfx web parts. Tokens appear to expire after an hour, closing and reopening the browser temporarily resolves the issue. Thanks

**Comment by lahuey** [comment]
@patrikhellgren @andrewbackway Are you still seeing issues around this?

**Comment by patrikhellgren** [comment]
I have been trying this back and forth for a couple of days now and cannot seem to be able to reproduce it anymore.

**Comment by andrewbackway** [comment]
Since upgrading to spfx 1.8 (from 1.7.1), we're no longer seeing this issue, thanks all.
