### ISSUE TITLE
this is only available for sharepoint online in office 365 ?

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-docs#2889]
hello, as this is only available for sharepoint online in office 365 ? could you specify it ?
Is it available in SharePoint 2019 yet ?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
>  as this is only available for sharepoint online in office 365 ? 
There is no special explanation, current it should only available for sharepoint online in office 365. 

> could you specify it ?
This don't need special specify. If SharePoint On-premise support it too, the end user can see '**Format view**' menu in the list/document page. If user cannot find it, of course the environment have not support it.
![default](https://user-images.githubusercontent.com/42561668/48174086-73348000-e341-11e8-9248-c963a74bc31f.PNG)


> Is it available in SharePoint 2019 yet ?
The same answer to above one.

**Comment by MaartenSundman** [comment]
There are versions of SPFX that work for SharePoint 2019 on-premise. When you are scaffolding your project make sure to pick SharePoint 2019 and not SharePoint Online.
