### ISSUE TITLE
How to use AppClientContextFromSPAzureToken received from SPFx to open current SP online

### ISSUE THREAD

**Issue by bpasolutions61** [SharePoint/sp-dev-docs#2890]
#### Category
- [x] Question

We developped a SPFx program with

this.context.aadHttpClientFactory.getClient("*myclientid*").then((client:AadHttpClient):void=>{
    client.get('*MyWebAPIUrl*?x=1&spsite='+this.context.pageContext.web.absoluteUrl,AadHttpClient.configurations.v1)
     .then((response:HttpClientResponse):Promise<any>=>{
       return response.json();
     })
});
Then, I drop this spfx webpart on a SP site. In the Azure Web API, I get the token from the client in Request.Headers.Authorization.Parameter :-) but when I do

context = authManager.GetAzureADAccessTokenAuthenticatedContext(wSiteUrl, Request.Headers.Authorization.Parameter);
                context.Load(context.Web);
                context.ExecuteQuery();
I get a 401 error.

if I do a

context = authManager.GetAppOnlyAuthenticatedContext(wSiteUrl,System.Configuration.ConfigurationManager.AppSettings["ClientId"],System.Configuration.ConfigurationManager.AppSettings["ClientSecret"]);
            context.Load(context.Web);
            context.ExecuteQuery();
it works.

So, what's wrong with the token passed by the SPFx client ?

Thanks for any help

Gilbert

**Comment by Seiyasu** [comment]
AppOnly means you register the App in _layouts/15/appregnew.aspx but not the Azure AD. They return different token.

**Comment by bpasolutions61** [comment]
Thanks Seiyasu,
I know that. The second will get a clientcontext with the App rights. This is fine for some operations.
What I'm asking here is how to get a clientcontext with the current user authentication, I get a token from the SPFx app which should contain the user in some way (I hope so), then, I was hoping to get the clientcontext with GetAzureADAccessTokenAuthenticatedContext to the site with this user credentials so that e.g. if I do a read, I'll only get the items he can read and if I write items, they will be "modified" by the user and not the App.
Thanks for any help on that.

**Comment by bpasolutions61** [comment]
News on my question last week.
Finally, with a huge help from a post from Kirk Evans (Thanks so much Kirk for https://blogs.msdn.microsoft.com/kaevans/2014/04/15/calling-o365-apis-from-your-web-api-on-behalf-of-a-user/ ), it seems I was able to have a WEB API c# code connected to SP with SPFx current user authentication/rights.

I did it with
this.context.aadHttpClientFactory.getClient("xxxxxxxxxx").then((client:AadHttpClient):void=>{
  client.post('https://API.BPA-Solutions.net/BPAPI01/api/Values?x=1&spsite='+this.context.pageContext.web.absoluteUrl,AadHttpClient.configurations.v1
  ,postOptions
  )
  .then((response:HttpClientResponse):Promise<any>=>{
    return response.json();
  });

And then something like

ClientCredential clientCred = new ClientCredential(CFG_Audience, CFG_AppKey);
UserAssertion userAssertion = new UserAssertion(CFG_AADToken);
AuthenticationContext authContext = new AuthenticationContext("https://login.windows.net/" + CFG_TenantAuth);
AuthenticationResult result = await authContext.AcquireTokenAsync("https://" + CFG_TenantName, clientCred, userAssertion);
SPToken = result.AccessToken;
OfficeDevPnP.Core.AuthenticationManager wauthManager = new OfficeDevPnP.Core.AuthenticationManager();
oClientContextUser = wauthManager.GetAzureADAccessTokenAuthenticatedContext(SPSiteURL, SPToken);


Is that the proper/best way to do it ?
