### ISSUE TITLE
Product scope not stated

### ISSUE THREAD

**Issue by sqlsolver** [SharePoint/sp-dev-docs#2894]
Please add the products guidance applies to in the subheading of every article, so that it doesn't have to be deciphered from the content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 258a0bb2-ca3a-bac6-c7d4-8cb3299523e2
* Version Independent ID: ad60bb89-2832-321f-f6ba-9fe725fc79c2
* Content: [URLs and tokens in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/urls-and-tokens-in-sharepoint)
* Content Source: [docs/general-development/urls-and-tokens-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/urls-and-tokens-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thank you for your post. The documents are maintained by the community. So we can submit a pull request to make perfect
