### ISSUE TITLE
What is the latest version of npm and node which is compatible with SPFX version 1.6.0?

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#2895]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

What is the latest version of npm and node which is compatible with SPFX version 1.6.0?

**Comment by phawrylak** [comment]
Officially supported versions are Node.js v8.x LTS (currently v8.12.0) and npm v6.4.1 that is installed with it.

Source: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

However personally I use Node.js v10.x LTS and it works without problems for me.

**Comment by xyz92** [comment]
Thanks @phawrylak
