### ISSUE TITLE
Relevance for Project Online (Office 365)

### ISSUE THREAD

**Issue by jlundstocholm** [SharePoint/sp-dev-docs#2896]
The first Note-section says:

Certain APIs require a user context and can't be executed with an add-in-only policy. These include many APIs for interacting with Project Server 2013 and for performing search queries.

We experience the same limitation for accessing Project Online - not being able to use the app-only principal to access the Project Online APIs at e.g. https://&lt;tenant&gt;.sharepoint.com/sites/&lt;pwa&gt;/_api/Resources

Could you please augment the note section by including reference to Project Online limitations as well (apart from just listing Project Server 2013)?

Thank you :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c272e61-7b5f-b670-d715-ecd77201a874
* Version Independent ID: 0975a72b-f331-51f5-0677-b229bc83ff60
* Content: [Add-in authorization policy types in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-authorization-policy-types-in-sharepoint)
* Content Source: [docs/sp-add-ins/add-in-authorization-policy-types-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-in-authorization-policy-types-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Hi, @jlundstocholm , thanks for your post. If you have tried and confirmed the limitation, you can modify the Content Source and submit an pull request for it.

**Comment by jlundstocholm** [comment]
> 
> 
> Hi, @jlundstocholm , thanks for your post. If you have tried and confirmed the limitation, you can modify the Content Source and submit an pull request for it.

Thank you - pull request has been created!

https://github.com/SharePoint/sp-dev-docs/pull/2906

:-)
