### ISSUE TITLE
Error - [spfx-serve] Error: Invalid glob argument:

### ISSUE THREAD

**Issue by Nagarajan1605** [SharePoint/sp-dev-docs#2897]
Hi

Am getting the error while running gulp serve. I reinstalled it with latest version gulp 4.0.0. But still the error occurs. 
![gulp error](https://user-images.githubusercontent.com/21313599/48190713-662b8700-e369-11e8-9a4a-05b61c6d201d.png)

Could you please help me to resolve this. .

**Comment by patmill** [comment]
Does it repro with the latest stable gulp (3.9.1)?

**Comment by KingKangMSFT** [comment]
Close this issue for long time no response. Feel free to contact us to reopen it.
