### ISSUE TITLE
SPFX pnp sp get list item failing in Edge and IE11.

### ISSUE THREAD

**Issue by paigeflourin** [SharePoint/sp-dev-docs#2898]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

I am having issues with running my SPFX app on Edge. I have a functionality that gets a certain list item and check if it is locked by a user. this is my code:

```
 public lockList (currentUser: any, division: string, qnaListTrackingListName: string) : Promise<any>{
        //let res; 
        let d = new Date();
        return sp.web.lists.getByTitle(qnaListTrackingListName).items.top(1).filter("Division eq '" + division + "'").get().then((items: any[]) => {
            // see if we got something
            if (items.length > 0) {
                return  sp.web.lists.getByTitle(qnaListTrackingListName).items.getById(items[0].Id).update({
                    LockedById: currentUser.Id,
                    LastUpdated: d.toLocaleDateString()
                }).then(result => {
                    console.log(result);
                    return result;
                }).catch(error => {
                    console.log();
                    return error;
                });
            }
        });
```

#### Expected or Desired Behavior

this should check if the item is currently locked by another user. 

#### Observed Behavior

It gets the list item i have logged it in console but it then have the error once i updated the item that i have retrieved. 

it is working in Chrome perfectly but it is not working in Edge i get this error in Edge:

>  HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
> (Fetch)POST - https://siteURL/_api/web/lists/getByTitle('QnA List Tracking')/items(1)

#### Steps to Reproduce

https://github.com/paigeflourin/test

* i would have to email you the configuration for the spfx webpart in order to run this one.

**Comment by paigeflourin** [comment]
I have tried following this: 
https://sharepoint.stackexchange.com/questions/248991/promise-is-undefined-for-pnp-js-core-sharepoint-ie-edge-browser?rq=1 

and still no success.

**Comment by Seiyasu** [comment]
I still cannot use your code directly to reproduce the issue. You need to provide the definition of the List and so on.

![image](https://user-images.githubusercontent.com/42561668/48462098-c317b900-e811-11e8-83a1-cc4baff9af0d.png)

**Comment by paigeflourin** [comment]
Hi @Seiyasu , i have fixed this issue already (date related issue ) but now I have checked IE again and i got errors: 

> 
> but now when i was working on the project suddeny it doesnt load in IE again. i have this error:
> [SPLoaderError.loadComponentError]:
> ***Failed to load component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: ***Failed to load entry point from component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: Error loading https://component-id.invalid/7616bc1f-6a77-48e6-a550-c41c9fca3c37_0.0.1
> Out of stack space
> 
> ***INNERERROR:
> ***Failed to load entry point from component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: Error loading https://component-id.invalid/7616bc1f-6a77-48e6-a550-c41c9fca3c37_0.0.1
> Out of stack space
> ***CALLSTACK:
> Error
> at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:271:16308)
> at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:271:15844)
> at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:22277)
> at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:16597)
> at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:12622)
> at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:71700)
> at s (https://localhost:4321/dist/qn-a-list-web-part.js:32220:8680)
> at Anonymous function (https://localhost:4321/dist/qn-a-list-web-part.js:32220:8827)
> at a (https://localhost:4321/dist/qn-a-list-web-part.js:32220:27451)
>
