### ISSUE TITLE
Documentation error under  "Get Started/Setup your Office 365 Developer Tenant/Setup document library/Create the new column"

### ISSUE THREAD

**Issue by khudsonjd** [SharePoint/sp-dev-docs#29]
The section titled "Create the new column" currently reads: 

Follow the steps below to add the new field to the Documents library:

    Click the gears icon on the top right and the click on Site settings to open the settings page.
    Click on Site libraries and lists under the Site Administration category.
    Click on Customize Documents
    Now, click on Create column under Columns:
        Type ClientSideApplicationId as the column name and leave other fields as they are.
        Click OK button to create the column.

I believe it should read: 

Click the gears icon on the top right and click on Site Contents.
Click the three dot icon next to the Document library you have created/chosen.
Choose Settings. 
Now, click on Create column under Columns:
        Type ClientSideApplicationId as the column name and leave other fields as they are.
        Click OK button to create the column.

**Comment by VesaJuvonen** [comment]
Actually both routes end on the same page. You can access Documents library settings also from site libraries and lists. It's matter of an opinion.

**Comment by khudsonjd** [comment]
I don't have Site libraries and lists under the Site Administration category in my tenant.  It seems to me alternate instructions would be helpful for others in the same situaton.
