### ISSUE TITLE
Trying to use SP.Taxonomy JSOM functions

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#290]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Since there is no RestAPI available for querying Term sets etc, I was trying to incorporate SP.Taxonomy.js.
I tried following the steps described here: https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/add-an-external-library#loading-sharepoint-jsom and additionaly added this external entry in config.json:
```
    "sp-taxonomy": {
      "path": "https://sevensn.sharepoint.com/sites/dev-schreder/_layouts/15/SP.Taxonomy.js",
      "globalName": "SP",
      "globalDependencies": [
        "sharepoint"
      ]
    }
```
However, when executing the SP.Taxonomy related code, I _almost_ always receive the error

> Uncaught ReferenceError: NotifyScriptLoadedAndExecuteWaitingJobs is not defined

_Note: sometimes it does seem to work! It seems that some library (init.js?) is loaded too slow, which results in the necessary scripts not being loaded. Apparently the require() calls are not synchronous enough? Is that a possibility?

(_Copy of issue https://github.com/SharePoint/sp-dev-fx-webparts/issues/73_)

**Comment by NickSevens** [comment]
Got it working now by using SP.SOD to wait for SP.Taxonomy. Still would like to make it work using externals config though :(

**Comment by brspnnggrt** [comment]
Should work if you map the globalName propertry to SP.Taxonomy. 
The namespace exposed by SP.Taxonomy.JS isn't SP, but SP.Taxonomy.

"sp-taxonomy": {
      "path": "https://groepvanroeydev.sharepoint.com/_layouts/15/SP.Taxonomy.js",
      "globalName": "SP.Taxonomy",
      "globalDependencies": [
        "sharepoint"
      ]
    }

**Comment by jquintozamora** [comment]
Hi @NickSevens ,
Maybe you can solve the problem using SOD but you should be doing a workaround because SP.Utilities.Utility.getLayoutsPageUrl function is not working on SPFx
```ts
// Utils.getLayoutsPageUrl replaces SP.Utilities.Utility.getLayoutsPageUrl
SP.SOD.registerSod("sp.taxonomy.js", Utils.getLayoutsPageUrl("sp.taxonomy.js"));
```
The workaround:
```ts
  /*
   * Function to get Layout Page Url
   * Replacement in SPFx for SP.Utilities.Utility.getLayoutsPageUrl('sp.js')
   * Samples:
   *      getLayoutsPageUrl('sp.js')
   *      "/sites/intranet/_layouts/15/sp.js"
   */
  public static getLayoutsPageUrl(libraryName: string): string {
    if (window
      && window.hasOwnProperty("location")
      && window.location.hasOwnProperty("pathname")
      && libraryName !== "") {
      return  window.location.pathname.replace(/\/$/, "") + "/_layouts/15/" + libraryName;
    }
    return null;
  }
```
You can see the full example here:
https://github.com/jquintozamora/react-taxonomypicker/blob/master/app/src/utils/API/SP.Taxonomy.ts#L24

Furthermore, in order to load JSOM scripts, maybe it worth it to consider using @microsoft/sp-loader, you have an example here:
https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-taxonomypicker/src/controls/PropertyPaneTaxonomyPicker/components/TaxonomyPickerLoader.tsx#L47

**Comment by JayakumarB** [comment]
Thank you @jquintozamora  The solution from this link https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-taxonomypicker/src/controls/PropertyPaneTaxonomyPicker/components/TaxonomyPickerLoader.tsx#L47 fixed my problem.
