### ISSUE TITLE
Absolute hyperlink automatically converted to relative links

### ISSUE THREAD

**Issue by SweloMyli** [SharePoint/sp-dev-docs#2901]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We use a Sharepoint application for communication about IT operations.
Users subscribe to the applications for which they want to receive communication.

In the developed communication models, we display a logo at the bottom of the page allowing them to go to the site to modify their subscriptions.

We wish that by clicking on them, they reach the Sharepoint list which contains their subscriptions.

#### Observed Behavior

When I save the link in my communication model, it is automatically converted to a relative format.
e.g.
- Before registration : http: //spprojets/infosi/Lists/Abonnements/MesAbonnements.aspx
- After registration : infosi/Lists/Abonnements/MesAbonnements.aspx

#### Steps to Reproduce

All you have to do is specify an absolute link in a multi-line field, allowing access to the Sharepoint site, to see that it is automatically converted into a relative link.

Thanks for your contribution! Sharing is caring.

**Comment by phawrylak** [comment]
Unfortunately this is intended. If you use value from this field in your code, you can convert this URL to absolute there. Another way is to change field to plain text and write HTML directly.

**Comment by patmill** [comment]
Yes, in order to support certain features, links are converted to relative URLs.  That's something far beyond the scope of this issues list.
