### ISSUE TITLE
Example explaining how to load values does not work

### ISSUE THREAD

**Issue by tommypage777** [SharePoint/sp-dev-docs#2902]
The example used (in section: Do not use value objects returned from methods or properties in the same query
) does not work, you have also to load description (w =&gt; w.Description):

ClientContext context = new ClientContext("http://SiteUrl"); 
Web web = context.Web; 
context.Load(web, w =&gt; w.Title); 
context.ExecuteQuery(); 
ListCreationInformation creationInfo = new ListCreationInformation(); 
creationInfo.Description = web.Description; 
creationInfo.Title = web.Title; 
SP.List newList = web.Lists.Add(creationInfo); 
context.ExecuteQuery(); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. You can modify the Content Source directly and submit an pull request.

**Comment by Seiyasu** [comment]
Close by #2907
