### ISSUE TITLE
I can't load a SharePoint project with gulp serve

### ISSUE THREAD

**Issue by aagbarcelona** [SharePoint/sp-dev-docs#2905]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. 
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
Hello, I am getting started with SharePoint Framework and setting up the development environment so I have installed node 10, PowerShell, Chocolate, Boxstarter and VisualStudio. I also have installed **Yeoman** with **npm install –g yo gulp** and **the generator SharePoint** with **npm install –g @microsoft/generator-sharepoint**. I have created my Project with SharePoint Online only latest, component webpart and no JavaScript Framework.
Then, I have certificated gulp trust-dev-cert and I have launched gulp serve. 
The error is the next: 
![image](https://user-images.githubusercontent.com/44876074/48216884-3474e900-e386-11e8-9331-b496e13e7f5b.png)
I am working in Windows 10. What is wrong there?

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>

Thanks for your contribution! Sharing is caring.

**Comment by aagbarcelona** [comment]
Please help

**Comment by patmill** [comment]
Interesting.  But yes, ideally use a straight forward path.  If you move your solution to c:\code\... does everything work?

**Comment by Seiyasu** [comment]
> Current LTS version of NodeJS is 10.x. Notice that 9.x or 10.x versions are currently not supported with SharePoint Framework development.

@aagbarcelona Do you have tried Node 8?

**Comment by aagbarcelona** [comment]
It seems is working all. Thanks

**Comment by patmill** [comment]
Glad to hear.
