### ISSUE TITLE
Opening solution in Visual Studio 2015 with NodeJS Tools breaks TS build

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#291]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior
I tried opening and running a new project (Drop 6) in Visual Studio with NodeJS Tools installed.
When running the `gulp serve` command however, I receive lots and lots of Typescript errors.

I tried investigating the issue myself, and I noticed that when opening the project in Visual Studio, an `index.d.ts` file is generated in the `typings` directory, with the following content, along with the `globals` directory and its content:
```
/// <reference path="globals/gulp/index.d.ts" />
/// <reference path="globals/node/index.d.ts" />
/// <reference path="globals/react-dom/index.d.ts" />
/// <reference path="globals/react/index.d.ts" />
```
Is this something I can disable? Removing the `index.d.ts` file fixes the `gulp` command, but I can't be expected to do this everytime I (or someone else) open the project...

Executing with `gulp serve --verbose` produces the following output:

http://pastebin.com/SkggPTPN

#### Steps to Reproduce

1. Create a new project with yo generator
2. Open the project in Visual Studio 2015 with NodeJS tools installed
3. Run `gulp serve` either from VS Task Runner Explorer or command line

(_Copy of issue https://github.com/SharePoint/sp-dev-fx-webparts/issues/72_)

**Comment by chakkaradeep** [comment]
@Trickass There seems to be some issues with Visual Studio and TypeScript. Visual Studio by default is looking for the TypeScript installed by Visual Studio and not what the web project is using. So, this is creating issues within Visual Studio. 

At this point, I think this is an issue with Visual Studio and discuss with the [Visual Studio Community](https://developercommunity.visualstudio.com/index.html).

**Comment by Trickass** [comment]
Thank you @chakkaradeep I'll see if I can post an issue there. Doesn't sound like an easy fix then? :)

**Comment by chakkaradeep** [comment]
@Trickass I tried working through them and I was not able to. On the other hand, open it in VS Code and everything works! ;)

**Comment by andrewconnell** [comment]
@Trickass This is a royal PITA when it comes to NodeJS & Visual Studio. VS's Node tools installs it's own version of Node so when it runs from VS, it uses that one. Drives me nuts. When you use VSCode, it's using the one on your system... so effectively you have two node installs.

You can see where your global node modules are from each environment. In a normal command prompt & in a VS Dev Command prompt run `npm help`. The last line shows the location of NPM... one folder up is the path of the globally installed packages. I bet you get two different experiences.

You can also check the TypeScript version in each command prompt. Run `tsc -v` in each command prompt to check. I bet the VS Command Prompt shows something <v2. Once you know where you are, you can verify which one you need to upgrade.

Thank help?

**Comment by frankchen76** [comment]
[Visual Studio 2015 – How to update NodeJS and/or NPM to their latest version](http://www.ryadel.com/en/visual-studio-2015-update-nodejs-andor-npm-latest-version/) mentioned how to use the latest node.js from your VS. By following those steps, you can make sure your VS are using a consistent node.js.  
what I figured out was that I had to use VS for code editing and rely on the browser's debug feature to debug code because the auto generated SPfx code somehow were broken when you simply pressed F5 in VS even though you followed the import project as node.js project from [dev.office.com](https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/use-visual-studio).

**Comment by NickSevens** [comment]
@chakkaradeep VS Code indeed works well. Only issue I have with using it, is that we use TFS instead of GIT in our team at the moment. For now I simply check in using VS, and develop using VS Code, but would be easier if I either make VS work, or VSCode has TFS support :)
@frankchen76 I'll check out the links you provided!

**Comment by chakkaradeep** [comment]
@NickSevens there seems to be a [TFS extension for VS Code](https://blogs.msdn.microsoft.com/visualstudioalm/2016/07/11/the-team-services-extension-for-visual-studio-code-now-supports-team-foundation-server-2015-update-2-and-later/). May be that could work?

Let us know if the suggestions in this thread works. If you have already started a discussion on the VS forum, then please add a link reference to that discussion here and feel free to close this issue.

Thanks!

**Comment by NickSevens** [comment]
It appears the `index.d.ts` file is not generated when importing the project (as described in the link of @frankchen76), which allows me to run the project.
For me this is resolved :)
