### ISSUE TITLE
Issuer Url field, or not?

### ISSUE THREAD

**Issue by TracyGH** [SharePoint/sp-dev-docs#2912]
I'm curious why the following documentation for securing a multi-tenant app service API instructs to provide the Issuer Url field but the instructions above say to delete it.  Is this a difference between an Azure function API vs Azure app-service API? 
https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication#a-namesecrets-aadd-azure-active-directory-information-to-your-app-service-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbbb69a-f2dd-ed42-d887-14a72494000f
* Version Independent ID: 7e5c254a-fd12-0fc6-fc7d-61f4ef009226
* Content: [Consume multi-tenant enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant#consume-enterprise-api-secured-with-azure-ad-from-the-sharepoint-framework)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
If you want to allow sign ins from only the particular Azure AD, then yes, you should specify the Issuer URL that points to that Azure AD. If you want to allow multiple Azure ADs, then the Issuer URL needs to be empty and you would validate the token in the code. The documentation could be clearer about it. Thank you for bringing it up.
