### ISSUE TITLE
i got "Invalid page layout"

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#2913]
in the browser, it popup "Invalid page layout" after i set the page layout to "SingleWebPartAppPage". any hints? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42d2d41-61bb-e281-3dac-328292b7b192
* Version Independent ID: 05b12512-7aa9-3ac7-e23e-0d5ae2209a59
* Content: [Using single part app pages in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages)
* Content Source: [docs/spfx/web-parts/single-part-app-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/single-part-app-pages.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Yes, we've had to disable this.  It should be back up later on today.  Sorry for that.

**Comment by patmill** [comment]
OK, this should be good to go now.  Sorry about that.  Can you give it a try?

**Comment by clechner77** [comment]
As of today, the Office CLI example didn't work, as I still received "Invalid Page Layout",  however, running the javascript example within dev tools worked just fine.

**Comment by VesaJuvonen** [comment]
This should be already out in production and based on the confirmation that it's working... closing this one.
