### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#2914]
Can we get some screenshots of an example of what this new feature looks like? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42d2d41-61bb-e281-3dac-328292b7b192
* Version Independent ID: 05b12512-7aa9-3ac7-e23e-0d5ae2209a59
* Content: [Using single part app pages in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages)
* Content Source: [docs/spfx/web-parts/single-part-app-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/single-part-app-pages.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
That really depends on the web part or Teams application you use for this page. We have though covered this in our community calls, so you can see how things look like from the following recording - https://developer.microsoft.com/en-us/sharepoint/blogs/sharepoint-dev-community-pnp-general-sp-dev-sig-recording-1st-of-november-2018/.
