### ISSUE TITLE
Security: script injection via property! (drop-6)

### ISSUE THREAD

**Issue by tortoise386** [SharePoint/sp-dev-docs#292]
#### Category
- [ ] Question
- [ ] Typo
- [x] **Bug**
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
The Yeoman-Template "No javaScript web framework" should build a secure by default web-part (no html/script injection). If you input HTML-/JavaScript-code it should be displayed but not interpreted.

#### Observed Behavior
If you edit the description-property, you can insert HTML-/JavaScript-code and it is interpreted/displayed in the WebPart.

#### Steps to Reproduce
This only occurs if you choose the Template "No javaScript web framework".
The React/Knockout-Templates do not have this problem.

I use the current drop (SharePoint Framework Developer Preview Drop 6).
I have not tested this on a developer tenant in the cloud (only local workbench).

1) Create a new HelloWorld-Project (Template: "No javaScript web framework")
2) Run it (gulp serve)
3) Local Workbench: Edit web-part properties
4) Change description to:
```html
<button onclick="alert('script injection possible')">Try it now</button>
```
5) Click the button "Try it now" (on the web-part)

#### Thoughts
I haven't tested this in the cloud (developer tenant) as i don't have an account. It could be that this only happens if you run it in the local workshop.

If you are using knockout/react you don't have this problem. 
This could be by design by the spfx team, but it should at least be documented in the generated source code that this vulnerability exists (if you do not use any js web framework) - and some hints how to handle this if you do it on your own.

**Comment by patmill** [comment]
Yup - completely correct.  We need to take a global pass through everything (samples, labs, templates, etc.) to handle this.  We're doing this as part of some additional work around persisting rich content (HTML) that has the same server support for scrubbing HTML, since you can't really html encode your html.

**Comment by tortoise386** [comment]
Tested it on a developer tenant with a debug release (spapp upload - code running on my machine).
When I am editing the property the html/js is interpreted.

It does get scrubbed when I view it on the page (normal mode).

**Comment by tortoise386** [comment]
Seems to be fixed with RC0 👍

**Comment by chakkaradeep** [comment]
@tortoise386 Excellent! In that case, can you close the issue! Thanks!

**Comment by tortoise386** [comment]
Only tested it in the local workbench. Closing the issue.
