### ISSUE TITLE
yo @microsoft/sharepoint --plusbeta runtime error

### ISSUE THREAD

**Issue by MrNigel** [SharePoint/sp-dev-docs#2922]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I am following the video/instructions [HERE](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab) to create my first Teams Tab.  

#### Observed Behavior

When I run the command `yo @microsoft/sharepoint --plusbeta` I get this error:

yo : 
At line:1 char:1
+ yo @microsoft/sharepoint --plusbeta
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

#### Steps to Reproduce

I am running ISE as Administrator.  I am not a programmer so realize I may be doing something stupid.  **This is my first ever post on GitHub**

**Comment by KingKangMSFT** [comment]
Could you please provide the version of the sharepoint framework?

**Comment by patmill** [comment]
Not exactly sure what is going on here.  I would make sure that you follow all the of set-up steps here - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

I haven't had any problems running the 1.7.0 generator (required for teams integration) with the --plusbeta flag.

**Comment by VesaJuvonen** [comment]
No comments after Pat's comment, so closing as stale.
