### ISSUE TITLE
'Page environment' builtin data source

### ISSUE THREAD

**Issue by FranckyC** [SharePoint/sp-dev-docs#2923]
Great documentation, very useful! However, would it be possible to get more information about the builtin data source like "Page environment" especially the "Query String/*** Query Parameters" and  "Query String/*** URL fragment" properties? What I see for now is these properties are only retrieved on the first page load and not dynamically. It is useful of course, but a dynamic behavior would be even better. More explanations on the behavior would be appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79444829-20bc-3b07-8820-29b55798761a
* Version Independent ID: 546cff82-d871-917e-10ba-55df6f18e5eb
* Content: [Connect SharePoint Framework components using dynamic data](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data#considerations)
* Content Source: [docs/spfx/dynamic-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/dynamic-data.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. Due to many docs and maintained by the community, if possible, feel free to submit any pull request for contribution.

**Comment by patmill** [comment]
What scenario are you seeing the query string get updated but not the dynamic property?  They should be getting updated (and a change triggered) along with the other properties like item id, etc.

**Comment by FranckyC** [comment]
@patmill The value is only retrieved during the initial page load. If I try to change this value dynamically (just by adding a '#' in URL or manipulaing browser history), the data source value is not updated. I use this [sample](https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/react-search-refiners) for my test  where I connect the Search Box WP component to a query string or a URL fragment value from 'Page environment' source, for instance, to get and execute a query coming from another page. It works well during the first page load for this specific scenario and the value is retrieved as expected.

However, I was thinking about a scenario where the user could update the query afterwards, for instance by clicking on predefined links from another component (i.e. prebuilt search queries in a 'verticals' WP) without refreshing the whole page every time.

I did similar feature for one of my clients using an SPFx extension as data source and by manipulating the browser history but I think it is quite overkill since the value is already provided by the default 'Page environment' source so my question.

Maybe also you would know a better way to implement this scenario.

**Comment by FranckyC** [comment]
**Update**: subscribing to the '_hashchange_' event manually when the source property is set '_PageContext:UrlData:fragment_' does the job for my use case.

```
private _bindHashChange() {

    if (this.properties.defaultQueryKeywords.tryGetSource()) {
        if (this.properties.defaultQueryKeywords.reference.localeCompare('PageContext:UrlData:fragment') === 0) {
            // Manually subscribe to hash change since the default property doesn't
            window.addEventListener('hashchange', this.render);
        } else {
            window.removeEventListener('hashchange', this.render); 
        }
    }
  }
```
