### ISSUE TITLE
Update SPFx modules to newer typescript version

### ISSUE THREAD

**Issue by nmnikolov** [SharePoint/sp-dev-docs#2924]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I want to install office-ui-fabric-react 6 in SPFx 1.7 solution since the framework supports react 16 with the latest release.

#### Observed Behavior
The solution can't build because office-ui-fabric-react needs higher typescript version from the one coming with SPFx 1.7. Are you going to increase the typescript version in the coming releases. Fabric have plans to release a new major version 7 and you still can't catch up with version 6.

**Comment by patmill** [comment]
Fabric 6 (and TS 2.8 or later) is not yet supported in the toolchain.  We are working on it.
