### ISSUE TITLE
Correct versions of @types/ramda and @types/bluebird

### ISSUE THREAD

**Issue by thaddeusferber** [SharePoint/sp-dev-docs#2925]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
tsc index shouldn't return any errors

#### Observed Behavior
tsc index causes around 100 errors like these:
node_modules/@types/bluebird/index.d.ts(39,26): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(824,3): error TS1128: Declaration or statement expected.

#### Steps to Reproduce

Following these instructions: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part 

and then typing tsc index

These can all be solved by the following two commands:
npm install @types/bluebird@ts2.4
npm install @types/ramda@ts2.4

Should that step be added into the Hello World tutorial instructions? And/or included in the next SPFx build?

#### Submission Guidelines
#spfx #spfx-tooling

**Comment by patmill** [comment]
Hmn...  What doe your environment look like?  What version of node / SPFX / npm etc. are you using?

**Comment by VesaJuvonen** [comment]
Closing as no response.
