### ISSUE TITLE
Lookup multi value

### ISSUE THREAD

**Issue by letsdothis-roguethink** [SharePoint/sp-dev-docs#2928]
Is there some way to do for-each?

For each item in a multi value lookup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
No. JSON formatting is for simple field. For your requirement, you need to try the [Field Customizer](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer). 

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#how-is-column-formatting-different-than-the-field-customizer
> Column formatting is more easily and broadly applied. However, it is less flexible, because it does not allow for custom code; it only allows for certain predefined elements and attributes.
