### ISSUE TITLE
Error while reading manifest.json

### ISSUE THREAD

**Issue by johnthen** [SharePoint/sp-dev-docs#2929]
Hi,

I follow exactly the same steps to try to build a Teams tab web part. There is no issue to deploy the web part to app catalog, no issue to add the web part to SharePoint Online page. Unfortunately, when I try to upload the Team manifest file, I got this error message "Error while reading manifest.json". 

Please advise.

Thanks.

The manifest content as below:
`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.2/MicrosoftTeams.schema.json",
  "manifestVersion": "1.2",
  "packageName": "MyFirstTeamsTab",
  "id": "caae6a54-6b2d-40f6-a2d3-a1d137d7350e",
  "version": "0.1",
  "developer": {
    "name": "SPFx + Teams Dev",
    "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
    "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
  },
  "name": {
    "short": "MyFirstTeamsTab"
  },
  "description": {
    "short": "My first Teams tab",
    "full": "My first Teams tab"
  },
  "icons": {
    "outline": "tab20x20.png",
    "color": "tab96x96.png"
  },
  "accentColor": "#004578",
  "configurableTabs": [
    {
      "configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=caae6a54-6b2d-40f6-a2d3-a1d137d7350e",
      "canUpdateConfiguration": false,
      "scopes": [
        "team"
      ]
    }
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ydogandjiev** [comment]
Can you please share the zip package that you are trying to upload.

**Comment by johnthen** [comment]
[MtFirstTeamsWebPart.zip](https://github.com/SharePoint/sp-dev-docs/files/2578841/MtFirstTeamsWebPart.zip)
Hi ydogandjiev,

Please find attached zip package.

**Comment by ydogandjiev** [comment]
@johnthen, I'm sorry but I cannot reproduce the issue you are describing with the app package you provided. I am able to upload the package without any issues:
![image](https://user-images.githubusercontent.com/3357245/48468266-3b459680-e7a0-11e8-8e2b-414550a03041.png)

Can you please try re-loading your Teams client in an in-private session and verifying that the issue still persists? Also, have you opted in for the Teams developer preview?
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview

Do you see any errors in the console when the app package upload fails?

**Comment by johnthen** [comment]
Hi ydogandjiev,

Sorry for the late reply. Currently was busy with something else.

Thanks for the highlighted on MS Teams developer preview. After turn on the developer preview, I am able to upload the package without any issues. It's working smoothly like a butter.

Thanks again.

**Comment by rahulsuryawanshi** [comment]
#Error while uploading .zip file

I followed all the steps as mentioned, created .zip file which contains manifest.json and other two image files at root of .zip file. While uploading .zip file to target Team, I get below error

*Error while extracting package: Please ensure there are no folders in your app package and that your app package contains only the manifest.json and the two required icon files at its root level. For an easier experience creating your app package, install <a href="https://teams.microsoft.com/l/app/0c5cfdbb-596f-4d39-b557-5d9516c94107" target="_blank">App Studio</a> from the Teams Store.*

**Comment by ydogandjiev** [comment]
@rahulsuryawanshi, @umaknow-alain, the original issue discussed on this thread has been resolved. Can you please open new issues for the problems you’re encountering. Also, please share your ZIP packages when you do that and screenshot(s) of the errors you’re seeing so that we can better investigate the problems. Thanks!

**Comment by syedshazab** [comment]
Greetings!
I have developed a small sample app to test on Microsoft Teams, when I try to upload the package through the app studio, it shows the error saying: "Manifest.json" file is missing from archive and the (Correct/parsed) file is there on the route directory. I wonder if anyone can help me!

**Comment by ydogandjiev** [comment]
@syedshazab, there should be no root directory within the ZIP. The manifest.json file and icons should be at the root of the ZIP file without any parent directory. Consider using App Studio to generate the Teams app package since that will ensure it's in the correct format:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview
