### ISSUE TITLE
removeNavLink doesn't work

### ISSUE THREAD

**Issue by zuboje** [SharePoint/sp-dev-docs#2930]
I create script with following two actions:

{
        "verb": "removeNavLink",
        "displayName": "Site contents",
        "isWebRelative": true
      },
      {
        "verb": "removeNavLink",
        "displayName": "Pages",
        "isWebRelative": true
      }

And, right now there are no specific permissions to scripts, I have associated this with hub site and applied new hub settings, but when creating new sites this does not get applied, nav links still have "Pages" and "Site contents"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Not all displays are support, you need to test it one by one. Just as the docs states:

> This action can be used to remove site links added by the collaboration and communication site templates (for example, "home", "documents", "pages", "conversations", etc.). 

You can try just remove one type and then other type. Finally, combine the worked types.
