### ISSUE TITLE
ADAL is depracticed, change documentation to MSAL

### ISSUE THREAD

**Issue by hkusulja** [SharePoint/sp-dev-docs#2931]
Please change documentation and examples to using MSAL library and not ADAL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc6b567-0762-fb88-e9f6-11482e81a5b2
* Version Independent ID: c64e977e-5adf-e31d-955b-1bafae3e9006
* Content: [Call the Microsoft Graph API using OAuth from your web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part)
* Content Source: [docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thanks for your post, some SharePoint docs and examples are maintained by the community, so they will not be updated in real time. Welcome to submit any pull request for contribution.

**Comment by patmill** [comment]
If you want to access the graph / AAD protected end points, we've made it significantly easier.  Follow these two tutorials:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph
