### ISSUE TITLE
Plans for releasing (open source | source open) the SPFx generator?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#294]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

A lot of the things used by the generator can be traced back (thru their `package.json` files) where the original codebase lives. However the generator doesn't list it's parent repo nor is it shared on the NPMJS page for the generator.

While you can view the generated source that's installed in the global NPM package library, still not the main repo. A few questions:

1. Do you plan to mark the repo as public that contains the generator?
1. Will it be open source | source open? _IOW... will you accept PR's and issues?_
1. When? :)

**Comment by chakkaradeep** [comment]
Currently, the SharePoint generator is not open source/source open. We are working on a plan with the key feature being able to add sub generators so folks can contribute more templates. However, we also don't want to end up in a situation that when you install the generator you get 10+ templates. There needs to be a balance of officially supported templates vs. community contributed templates. 

So, it is a work in progress. We don't have a timeline for it yet.

**Comment by waldekmastykarz** [comment]
Opening the generator would be beneficial not only for additional subgenerators but also for new capabilities such as tests or build tasks that should be available after scaffolding a project. Additionally it would allow organizations to tailor the generator to their specific needs without necessarily contributing it back to the community (think organization-specific project templates, build tasks, etc.).

**Comment by andrewconnell** [comment]
@chakkaradeep Makes sense... having to vet tons of template submissions would be a challenge. At a minimum having the repo published lets organizations / community fork & add their own. For instance, I could fork & add my own and if others wanted to use my version, then all good... just the disclaimer that it might not be current to what MSFT provides. Then again, the template doesn't matter, it's what you build.

But then, if there are popular ones you want to absorb into the master one, you could work with those people to submit a PR, yet the stated policy would be "source open", not open source. IOW, you can see & get our source, but won't officially accept PR's. Down the road you can soften that stance up if you want community templates.

IMHO, I doubt you'll see many PR submissions other than bug fixes / typo fixes. That was our experience with the https://github.com/officedev/generator-office at least.

**Comment by chakkaradeep** [comment]
@waldekmastykarz @andrewconnell  Valid points. Organization specific generators by itself is another big area. I believe there is lot to be thought about that in regards to expectations, versioning, support etc.,. At the same time, we don't want to limit that ability as well. 

This is in our backlog and expect to talk about it post GA release.

**Comment by andrewconnell** [comment]
Fair enough @chakkaradeep ... will the generator source repo be made public (even if no PR's are accepted) before / at GA?

**Comment by chakkaradeep** [comment]
@andrewconnell I don't believe so.

**Comment by andrewconnell** [comment]
Thanks for the responses @chakkaradeep ... I'll consider this issue closed. Bummer the source won't be made available.

@frankchen76 It's more than that honestly. While I do prefer Angular MUCH more than React... there are a TON of opportunities to have a fork where someone who's learning SPFx could benefit from a lot more inline docs in what's generated as well as demonstrating some good practices (like removing the wildcards from the `package.json` package references). We'll just have to wait for MSFT to make the repo public.
