### ISSUE TITLE
Invalid Folder handling in Office 365

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#2940]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In Office 365 a folder cannot start with a "." as the first character. When a folder gets created with a dot at the end of the folder name the following error message appears.

<img width="415" alt="screenshot 2018-11-13 at 12 04 22" src="https://user-images.githubusercontent.com/5503835/48409671-c2612300-e73c-11e8-8e37-e61ffbca4c11.png">
.
Which is not valid because a dot is not listed in the illegal characters. The appropriate error message should be that a folder cannot have a dot at the end of the folder name.

When someone tries to rename a folder with a dot at the end the error message "Cannot find file or folder" appears which is also wrong.

When a folder get generated through PnP Powershell the "dot" at the end of the folder gets replaced.

it would be great if this edge cases and be identified correctly.

**Comment by VesaJuvonen** [comment]
This is in the out-of-the-box APIs and is by design.
