### ISSUE TITLE
Pages with PageLayoutType set to SingleWebPartAppPage don't show up as single web part app page for users in the site members role

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-docs#2942]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A user who's just a basic member of the site should also see the page as single page app page when the page's PageLayoutType is set to SingleWebPartAppPage.

#### Observed Behavior

Site collection admin loads the page correctly as single web part app page, however the same page loaded by a regular site member shows the page as being of type Article. Page is functional but the page header and comments are visible.

#### Steps to Reproduce

Create single web part app page as admin, put web part and test. Page will show correct. Now logon with a user having limited permissions and the page will show incorrect.

**Comment by patmill** [comment]
Is there a chance that you have a checked-out version (or minor version) that the admin sees, and another version that the reader sees?

**Comment by jansenbe** [comment]
I should have known that...thx for reminding me @patmill :-)  

Used PS to update the pagelayouttype which caused the checkout...Would be good to add this to our docs as it's not very visible from PS that the page got checked out. Closing this issue now as it's resolved.
