### ISSUE TITLE
ListTemplateType - Where does it come from?

### ISSUE THREAD

**Issue by kylejrp** [SharePoint/sp-dev-docs#2943]
The code block under `To provide the custom rendering logic in a JavaScript file` has the following line:
`overrideCtx.ListTemplateType = 10057;`

Where does this value come from? Is this ID something automatically generated, or something that we are able to define in our solution? I don't see the number `10057` defined anywhere else in our solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e6fd40-ded3-ceb1-56db-82de96ea3afa
* Version Independent ID: 06e39488-641a-a724-68d7-35150d3bd39b
* Content: [Customize a list view in SharePoint Add-ins using client-side rendering](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/customize-a-list-view-in-sharepoint-add-ins-using-client-side-rendering#to-provide-the-custom-rendering-logic-in-a-javascript-file)
* Content Source: [docs/sp-add-ins/customize-a-list-view-in-sharepoint-add-ins-using-client-side-rendering.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/customize-a-list-view-in-sharepoint-add-ins-using-client-side-rendering.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
It is custom list template id. 100 means **GenericList**. And the 57 is owned by the code writer( In your project, it is you).
https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.listtemplatetype.aspx
http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2009/03/31/how-to-create-a-scope-for-a-custom-list-template-type.aspx
