### ISSUE TITLE
Error  gettin token from AadTokenProvider

### ISSUE THREAD

**Issue by sefaburak** [SharePoint/sp-dev-docs#2945]
There is an error in build time ;

> error TS2345: Argument of type '(value: AadTokenProvider) => string | PromiseLike<string>' is not assignable to parameter of type '(value: AadTokenProvider) => string | PromiseLike<string>'

The code is below ;

```
this.context.aadTokenProviderFactory
      .getTokenProvider()
      .then((value: AadTokenProvider): string | PromiseLike<string> => {
        return value.getToken('****');
      })
      .then((accessToken: string): void => {
        
      });
```

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064cdc5a-e118-ceab-c42b-ae06ae3297c6
* Version Independent ID: 95afcc6d-fd0b-90a0-5775-4871869abc83
* Content: [Connect to API secured with Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad)
* Content Source: [docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
For error “Argument of type '(value: xxx) => Promise<void>' is not assignable to parameter of type '(value: xxx) => void | PromiseLike<void>'”, just change the **void** to **any**.

**Comment by sefaburak** [comment]
> For error “Argument of type '(value: xxx) => Promise' is not assignable to parameter of type '(value: xxx) => void | PromiseLike'”, just change the **void** to **any**.

Sory i was copied the wrong error text, the correct one is in updated comment. Thank you.

**Comment by VesaJuvonen** [comment]
No response since Nov, so closing.
