### ISSUE TITLE
Roadmap update

### ISSUE THREAD

**Issue by Forket** [SharePoint/sp-dev-docs#2947]
I believe that after MS Ignite 2018 roadmap should be updated, as lot of things already changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9812a06-9d08-b754-5c2e-d63d038f4dbd
* Version Independent ID: e3fc3e85-2821-cfb6-2cd8-80c68420ac99
* Content: [SharePoint Framework roadmap](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/roadmap)
* Content Source: [docs/spfx/roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/roadmap.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for your post. You can contribute for it by submitting any pull request based on the MS Ignite 2018. Otherwise, the content team still need more time on this issue.

**Comment by andrewconnell** [comment]
Outdated... the had been updated.
