### ISSUE TITLE
React-Redux Provider reloading store after property change

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#295]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
When using **react-redux** I receive an error in console when updating properties (and so re-calling render()):

<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.

Do you know of any way to fix this issue? The link provided in the error message doesn't make me much wiser :(

**Comment by kmees** [comment]
Do you create a new store in every render? The store should be created once when the webpart is created. 
Here's a working react/redux sample: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-redux

**Comment by NickSevens** [comment]
Thank you @kmees ! Great solution and example. Works perfectly!
