### ISSUE TITLE
Type -- Missing quotation mark

### ISSUE THREAD

**Issue by nbahmanyar** [SharePoint/sp-dev-docs#2950]
At the top of this document there's an XML sample with a  missing quotation mark: 

&lt;Value
  Type = "Text"
  IncludeTimeValue = "TRUE" | "FALSE&gt;
&lt;/Value&gt;

FALSE is missing a quotation mark at its right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a37aea-a0eb-5ad1-8837-4a92e1d99219
* Version Independent ID: 8c1c12ff-58c7-95e3-9da8-24434614895d
* Content: [Value element (Query)](https://docs.microsoft.com/en-us/sharepoint/dev/schema/value-element-query)
* Content Source: [docs/schema/value-element-query.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/value-element-query.md)
* Product: **office-online-server**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Fix.
