### ISSUE TITLE
refused to connect tutorial: Deploy your client-side web part to a SharePoint page (Hello World part 3 and part 4)

### ISSUE THREAD

**Issue by FernandoSolano2015** [SharePoint/sp-dev-docs#2953]
Hi! I am working with sharepoint Framework and I can develop everything but when I add this webpart in my shrepoint site this give me this error: refused to connect. 

![spcap](https://user-images.githubusercontent.com/19756469/48530413-3f83b980-e85d-11e8-90aa-9956a79168fe.PNG)
This image is in my new page

![cppsp](https://user-images.githubusercontent.com/19756469/48531264-34328d00-e861-11e8-8a9f-f09fbb06f407.PNG)
This image is the workbench

And now I see my console, it shows me this: Refused to display 'https://cedesdonbosco-app07194eb5227e41518ab005bd6b6a6c98.sharepoint.com/sites/cedespractica/_layouts/15/webpart.aspx?list=%7B5b766603-12d4-4a88-857e-d22e1ebc2f2d%7D&id=6&webPartInstanceId=d6a14078-99c5-4b9b-85d0-e027c5591c8e&parentWindowOrigin=https://cedesdonbosco.sharepoint.com&componentId=1db87a5a-edfb-445d-991c-e2deeaef14ba&hostedInCanvas' in a frame because it set 'X-Frame-Options' to 'sameorigin'

Thanks.

**Comment by patmill** [comment]
Are you trying the domain-isolated feature that was just released?

**Comment by FernandoSolano2015** [comment]
I don't khow if I am using, I only followed the steps of the tutorial, but how I know if I using the domain-isolated?

**Comment by patmill** [comment]
OK.  My guess is that you answered "yes" to the question around 

Go to the config/package-solution.json file and remove the line that reads 
`
    "isDomainIsolated": true' `

You'll need to remove the comma on the line above.

rebuild / bundle / package / deploy.

**Comment by FernandoSolano2015** [comment]
Thanks, now everything works fine
