### ISSUE TITLE
Shrinkwrap too early

### ISSUE THREAD

**Issue by tyrfing666** [SharePoint/sp-dev-docs#2957]
Reverse order of "npm shrinkwrap" and "npm install @types/angular --save-dev" - the install tries to add to package.json and can't find it (renamed by shrinkwrap).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcd8ec2-d21c-05b6-082a-8d8c889abbf2
* Version Independent ID: 77bc840c-d335-01d2-bbed-8bfd4774139b
* Content: [Tutorial - Build SharePoint Framework client-side web parts with AngularJS](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x)
* Content Source: [docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
We use "npm shrinkwrap" to lock down the version of the project dependencies. Lock @types/angular is optional now, if user need have the requirement in the future, they can reverse the order case by case.
