### ISSUE TITLE
When approving the API permissions -> Permission entry already exists.

### ISSUE THREAD

**Issue by arheom** [SharePoint/sp-dev-docs#2958]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I created one SPFx extension which should save some extension data to Microsoft Graph, using extensions. Following tutorials to do so, but I cannot give permissions from the API management to my SPFx.

#### Observed Behavior

When I try to approve my API permissions requests, I am getting following error:
[HTTP]:500 - Internal Server Error [CorrelationId]:50a7a29e-80e5-0000-381b-6e7483603dfa [Version]:16.0.0.8307 - Permission entry already exists.

#### Steps to Reproduce
1. I created a SPFx extension to show one panel with an editor for the current Group extensions.
2. I can read info from the Graph, but I cannot add an extension to the current group, through Graph extensions. I am receiving the following error:
{
  "error": {
    "code": "AccessDenied",
    "message": "Access Denied",
    "innerError": {
      "request-id": "27fa25a7-88ec-4a64-a696-ff3723323de5",
      "date": "2018-11-15T16:55:00"
    }
  }
}
3. I added the permissions to the webApiPermissionRequests, bundle the spfx, package-solution, add to SharePoint and next want to approve the ReadWrite permissions
4. Navigate to the SharePoint Admin, API Management, found there my requests and try to approve them. Getting the following error:

[HTTP]:500 - Internal Server Error [CorrelationId]:50a7a29e-80e5-0000-381b-6e7483603dfa [Version]:16.0.0.8307 - Permission entry already exists.

5. Tried to approve them using powershell, getting same exception. I am trying to approve any request from any application (have around 30 from different third party or developed ones). Same issue.

Any idea what I can do to be able to approve the permissions to be able to save data from a spfx extension to the Graph?

Thanks!

**Comment by waldekmastykarz** [comment]
Is the permission that you're trying to approve already approved or not?

**Comment by arheom** [comment]
It is not approved. I created 2 more SPFx apps from scratch with different IDs and other permissions, but always got the same message back. And if there were approved, I assume I could have saved info in the Graph, but I got AccessDenied back.

**Comment by waldekmastykarz** [comment]
Are you sure you have the right MS Graph permission?

**Comment by arheom** [comment]
Yes. Should have. I am also an Office 365 and SharePoint admin. I also created one demo environment from Microsoft and did the same there and all worked well. So, something is for sure wrong with our environment, but hard to tell what. I probably need to open a ticket as well, cos one of the environment is productive and we cannot approve api requests there.

**Comment by VesaJuvonen** [comment]
Closing based on the ticket opening comment. Please let us know with a new issue, if there are any problems still with this. Thx.

**Comment by 5erban** [comment]
@arheom do you have any input on how this issue can be solved? I am having the exact same problem: cannot approve pending permission requests with error: Permission entry already exists. However, I cannot see the permission in either the UI or using PowerShell Get-SPOTenantServicePrincipalPermissionGrants.

I'm requesting access to Microsoft Graph - Directory.Read.All

**Comment by JohnnyKapps** [comment]
I'm facing the same problem on my tenant, any updates about this issue?
