### ISSUE TITLE
The list of TimeZones from the SharePoint 2010 docs

### ISSUE THREAD

**Issue by colinrippeyfinarne** [SharePoint/sp-dev-docs#2960]
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms453853(v=office.14)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac08219-6183-0904-50e6-682d748946fb
* Version Independent ID: 549cb147-3696-9a9a-f22e-ee76decf6e59
* Content: [SPRegionalSettings.TimeZones Property (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spregionalsettings.timezones?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_SPRegionalSettings_TimeZones)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by Seiyasu** [comment]
Thanks for post.

**Comment by andrewconnell** [comment]
Not sure what's wrong here... the link works, but there's nothing in the issue that's actionable.
