### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by RobChambers1982** [SharePoint/sp-dev-docs#2961]
Hi,
in the date formating code you have missed a ")", the line reads:

"color": "=if([$DueDate] &lt;= @now, '#ff0000', ''"

but I believe it should be:

"color": "=if([$DueDate] &lt;= @now, '#ff0000', '')"

its in the section called:
Formatting an item when a date column is before or after today's date (advanced)
in the first JSON example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#apply-formatting-based-on-date-ranges)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thanks for @RobChambers1982 's post.
