### ISSUE TITLE
User not logged on

### ISSUE THREAD

**Issue by Nils-Berghs** [SharePoint/sp-dev-docs#2962]
The most basic error is simply ignored by this troubleshooting guide (an all other documentation about high trust add-ins). What if the users is not logged on to SharePoint? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35eded91-1d16-b750-46b1-acb409dd0cb2
* Version Independent ID: c7ddfad7-3382-3bf9-384a-c30aa4e68779
* Content: [Troubleshooting high-trust SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/troubleshooting-high-trust-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/troubleshooting-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/troubleshooting-high-trust-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
If the user is not logged on to SharePoint, they don't have the permission to access the resource. Developer need to handle the authentication logic.
