### ISSUE TITLE
User do not normally!!!

### ISSUE THREAD

**Issue by Nils-Berghs** [SharePoint/sp-dev-docs#2963]
The first scentence is wrong!!!!!!!!! Never think you know what your users will normally do! The will never ever do !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543ba777-5c67-9fec-4716-c506af4c9e38
* Version Independent ID: 8d7c92ec-aeef-d5c7-e59b-e0e43417c70c
* Content: [Authorize provider-hosted add-in users at run time by using OAuth](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth)
* Content Source: [docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Below the article, the article provides a solution for users to log in abnormally. Please review this document

**Comment by VesaJuvonen** [comment]
Actually, our telemetry shows that this is the most common way for people to access SharePoint add-ins. We do not assume, we have telemetry typically to back up these kinds of statements. I do however agree that the whole sentence is pretty much meaningless, so adjusting this slightly.
