### ISSUE TITLE
All links in https://github.com/SharePoint/sp-dev-docs/blob/master/docs/index.md broken

### ISSUE THREAD

**Issue by EvolutionOnGitHub** [SharePoint/sp-dev-docs#2965]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Links should take you to the appropriate .md file

#### Observed Behavior
Instead every link is a 404 error.

#### Steps to Reproduce
Navigate to https://github.com/SharePoint/sp-dev-docs/blob/master/docs/index.md
Click on any linked paragraph
Observer 404 error is result

**Comment by VesaJuvonen** [comment]
That page is at https://docs.microsoft.com/en-us/sharepoint/dev/ and works properly. This is due to the publishing process in the docs.microsoft.com... this page is not intended to be viewed within GitHub.
