### ISSUE TITLE
Conditional formatting based on the value in a text or choice field (advanced)

### ISSUE THREAD

**Issue by markgable** [SharePoint/sp-dev-docs#2968]
Why isn't there a complete example provided for this?

What is the "sp-field-severity--" code for orange ("Has Issues")?
What is the code for the circled X ("Blocked")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#conditional-formatting-based-on-the-value-in-a-text-or-choice-field-advanced)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
You can use the free tool which has been pointed out in the docs: https://github.com/SharePoint/sp-dev-solutions/blob/master/solutions/ColumnFormatter/docs/documentation/docs/getting-started.md. So it is required little to provide pure get-started sample now. Of course, you can submit some sample for contribution and link to the docs.Thanks.

**Comment by thechriskent** [comment]
The background colors are set with the `sp-field-severity--` classes. The icons are set using the `iconName` attribute.

You can find additional details about the classes available in column formatting in the [Style guidelines](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#style-guidelines) section. For instance, you'll see the orange, "Has issues" example is using the `sp-field-severity--severeWarning` class to achieve that color and the "Blocked" example is using the `sp-field-severity--blocked` class.

Additionally, this is provided as one of the many open source samples here: https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/text-conditional-format

However, I believe I see the issue in that the code sample provided in the documentation is not currently complete (unlike the linked sample above) and would not be able to produce the sample image shown. I have submitted a change to the documentation to address this gap. Thank you very much for bringing it to our attention!
