### ISSUE TITLE
Endpoint microsoft.online.sharepoint.tenantadministration.tenant.getsiteproperties limitation

### ISSUE THREAD

**Issue by ashuetawah** [SharePoint/sp-dev-docs#2970]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The CSOM end point microsoft.online.sharepoint.tenantadministration.tenant.getsiteproperties should list all site collection properties whether the experience is classic or modern.

#### Observed Behavior
The CSOM end point microsoft.online.sharepoint.tenantadministration.tenant.getsiteproperties does not list modern team site even though it is not associated with a group.

**Comment by VesaJuvonen** [comment]
We will not be implementing the requested feature as defined in this GitHub issue, but are working on a long term solution in this area. As we do not have specific ETA for that at this point, we cannot provide further details for now. Please stay tuned on the updated announcements. We understand the ask, but closing this for now as we cannot provide more specific response right now.
