### ISSUE TITLE
Custom web parts don't always appear in editor on page load

### ISSUE THREAD

**Issue by Toonshorty** [SharePoint/sp-dev-docs#2973]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When opening and editing a page with a full-width column, all the custom web parts that support full bleed should appear in the list.

#### Observed Behavior

In some instances, only the first one or two web parts are showing in the list on the full-width column. Removing the column and then re-adding it will sometimes show all the web parts.

#### Steps to Reproduce

Create a new page and add a full width column, save and refresh the page. You may only see one or two custom full-width web parts, although this is somewhat intermittent.

**Comment by Seiyasu** [comment]
As this is out-of-the-box functionality, we can't route this through the dev process. Please submit this through the SharePoint Online admin support channels from the tenant admin tool. We can only support dev topics through this issue list. Sorry for the inconvenience.
