### ISSUE TITLE
SPFx for Disp- or NewForm

### ISSUE THREAD

**Issue by hohenp** [SharePoint/sp-dev-docs#2975]
Hello,

is there an option in modern ui to overwrite the NewForm or DispForm URL as it was possible in classic ui? We need to link an SPFx UI (Webpart, as there are no other Options in the Moment) to a New- or DispFrom, and wont use PowerApps.

The idea is to Redirect the New- or DispForm to a normal modernpage and place the SPFx WebPart on there.

So what are the supported ways to do this in SPO and SP2019?

Thanks very much for your help!

#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by AJIXuMuK** [comment]
As far as I know there is no such option for now.

**Comment by tsekityam** [comment]
I implemented  my own SharePoint List web part. The New and the Edit button of that web part opens my custom form in a panel. It is not cool but it works.

**Comment by peterremote1980** [comment]
@tsekityam  how you did it?

**Comment by jonathaneckman** [comment]
+1 We need this.
