### ISSUE TITLE
Referring SP private CDN relative urls with RequireJs

### ISSUE THREAD

**Issue by AnkitGirgas** [SharePoint/sp-dev-docs#2981]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

As with Private CDN the urls are dynamic, so one has to provide relative paths to static resource in SP library.
However, I'm using RequireJS for loading AMD modules and have a require.config.js defined as below,

requirejs.config({
    baseUrl: "/",
    paths: { 
        'myJS': ['/sites/cdn/style%20library/test.js']
               }
});

Usage:
        require(['myJS'], function () {
                  // do something after test.js has loaded
          });
         
The code works as expected but test.js isnt loaded from private cdn but from the library itself. The cdn is setup up properly and if I try to load that js using script tags having relative url in src, then the js is loaded from private cdn.

I'd like to stick with Private cdn and requirejs. 
Any ideas on how to get it working ?

**Comment by patmill** [comment]
SPFx doesn't work with a private CDN.  You'll either need to use a public CDN, or serve the code directly out of a library.

**Comment by AnkitGirgas** [comment]
SPFx isnt being used here. Its just a client side webpart using RequireJs
