### ISSUE TITLE
FieldCustomizer doesn't receive any notifications when List View has been changed

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2987]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
A bit of background...
As I understand Dev Team made a huge work to increase performance of lists and doc libraries rendering.
And one of optimizations is minimizing re-rendering of list contents and firing additional events.
As a result when a user switch from one list view to another columns that are presented in both view are not re-rendered. And `onRenderCell` method of `FieldCustomizer` is never called.

I think it's incorrect. `FieldCustomizer` should know the correct "context".
Especially if you provide `tryGetListView` API that returns information about current view.

What do you think about that?
Maybe it's just a bug?

**Comment by Seiyasu** [comment]
What is your SPFx version and SharePoint env version?

**Comment by AJIXuMuK** [comment]
Couldn't find any specific steps, so closing it...
