### ISSUE TITLE
How to get view id in Command Set Customizer

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#2991]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
What is the right way to get current View ID in command set customizer?
Currently I'm using the code below:

```typescript
const urlParams: URLSearchParams = new URLSearchParams(location.search);
let viewIdQueryParam: string = urlParams.get('viewid');
if (viewIdQueryParam && viewIdQueryParam.indexOf('{') !== 0) {
  viewIdQueryParam = `{${viewIdQueryParam}}`;
}
const viewId = viewIdQueryParam || this.context.pageContext.legacyPageContext.viewId;
```

It works fine except one scenario (probably a bug): when you resize a column, `this.context.pageContext.legacyPageContext.viewId` becomes empty string. And if you don't have `viewid` there is no way to get it from API.

Another thing to mention here that the only way to revert client-side view modification (sorting, resize) is to clear cookie. Before that user alway sees a start `*` near list view name, meaning that there are changes. And can't get rid of it.

**Comment by AJIXuMuK** [comment]
Similar thing happens when you reorder columns.

Simple way to reproduce: use the code above in `onListViewUpdated` method.

**Comment by AJIXuMuK** [comment]
Following up...

**Comment by patmill** [comment]
Hi @AJIXuMuK - The underlying logic for the listview was changed a bunch recently, and we can't repro this issue any more with it.
