### ISSUE TITLE
addContentType and Enterprise Content Types

### ISSUE THREAD

**Issue by Aschlender** [SharePoint/sp-dev-docs#2992]
This does seem to be supported now. I did add a content type that was promoted from the content type hub sucessfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thanks @Aschlender ,  could you please describe your problem in detail?

**Comment by VesaJuvonen** [comment]
Enterprise content types with hub publishing is not currently supported.

**Comment by markgort86** [comment]
@VesaJuvonen it's possible to use a site design to add a content type published by the hub to a new or existing list. When using a site design directly when creating a new sitecollection the site design goes stuck. If you wait until the content type is published from the hub on that sitecollection, the site design adds this content type without any problem to the list.
