### ISSUE TITLE
Failed to render client side SPFx web parts

### ISSUE THREAD

**Issue by ari20089** [SharePoint/sp-dev-docs#2994]
Expected or Desired Behavior
As of today a SPFx webpart stopped working because of a manifest file not found.

Observed Behavior
This webparts were working from last 6 months, but now it is showing the below error for all the SPFx webparts in all the environment and at the same time.

Failed to render client side web part. Id: [3cb727fb-917a-4b56-bf89-ae8d431dac31], Manifest: [<NULL>], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part 3cb727fb-917a-4b56-bf89-ae8d431dac31 failed to render as manifest is not found at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.GetManifest

This occurs in Sharepoint online and version 1.4.1

**Comment by VesaJuvonen** [comment]
Have you double checked that the solution still exists in the app catalog of the tenant? Just to ensure that there has not been any changes there, which would explain this. 

That error message basically means that the components are no longer available in the Client Side Components Manifest list located in the app catalog... you might want to double check that as well for the component ID mentioned in the exception. That list is roughly in following location (update app catalog and tenant URL): https://contoso.sharepoint.com/sites/appCatalog/Lists/ComponentManifests/AllItems.aspx

**Comment by ari20089** [comment]
Yeah the solutions are still there in the app catalog. And also verified the manifest list as well. 
One strange observation... Although SPFx Add-ins are available in site contents but all those Apps are showing as removed by the administrator while cliking on the App Profile.

FYI... all these apps were working for last 6 months and there were no changes/deployments recently.

**Comment by VesaJuvonen** [comment]
So - these solutions are site installed and not using tenant-scoped deployment? I'm not quite sure what you mean with App Profile in this context - any change you could get a screenshot for that? That could mean that someone has uninstalled them from the site, but just guessing now as don't have sufficient details for a more educated conclusion.

**Comment by patmill** [comment]
Can you make sure that the URL of the app catalog where the solution is installed is the same as the URL of the app catalog as shown in tenant admin?  Are you doing migration testing, using multi-geo features, etc?
