### ISSUE TITLE
Schema doesn't match documentation and has a broken link to the icon picker

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-dev-docs#2995]
The current schema for webpart.manifest.json files contains a broken link, that does not match the documentation:

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
}
```

will return this information for officeFabricIconFontName, that is not valid:

```json
{
"officeFabricIconFontName": {
                "title": "Office Fabric Icon Name",
                "description": " The icon for the Web Part, to be displayed in the toolbox, represented as a character name in the Office 365 icon font file. The icon font is specified here: http://o365icons.cloudapp.net/. If this field has a value, the 'iconImageUrl' field will be ignored.",
                "type": "string",
                "minLength": 1
              }
}
```

The link in the description is not valid: http://o365icons.cloudapp.net/ 

There are the following resource available to pick Office UI Fabric Icons
- https://aka.ms/uifabric-icons (Wich shows way more icons, than are currently usabe in SPFx Webparts)
- https://developer.microsoft.com/en-us/fabric#/styles/icons (Mentioned in the documentation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e7009-0cb3-76ed-fdac-848af3d396b0
* Version Independent ID: 6e219143-e4b8-4fa0-0a1e-ea8fc3a7b4bd
* Content: [Configure web part icon](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/configure-web-part-icon)
* Content Source: [docs/spfx/web-parts/basics/configure-web-part-icon.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/configure-web-part-icon.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
@andikrueger Thanks for your post, of course, Office UI Fabric have more icons than the MS docs states, because not all icon are supported. But we may not update the docs to latest in time. So you are welcomed to submit any pull request for the docs after confirm any new supported Icons. Thanks for contribution.

**Comment by andikrueger** [comment]
@VesaJuvonen What is the right place to post issues about the manifest.json schema?

**Comment by andrewconnell** [comment]
Correct... it's been bugged & tracked: #1690
