### ISSUE TITLE
Flow Launch Panel always displayed

### ISSUE THREAD

**Issue by ACPriebe** [SharePoint/sp-dev-docs#2997]
In the documentation above it states: "If the Flow is configured to gather data from the end user before running, the Flow Launch Panel will be displayed after choosing the button. Otherwise, the Flow will just run."  However this is not the case, as the Flow Launch Panel is always displayed, if only with 'Run Flow' button.  It would be great to make the documentation match the functionality, or vs versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by elenanakhmanson** [comment]
I would like to know the same thing, does it supposed to display the flow launch panel or not? According to reply here https://powerusers.microsoft.com/t5/Building-Flows/How-to-skip-quot-Run-flow-quot-in-sharepoint/m-p/241114#M23779 it is not possible to bypass the flow launch panel.
