### ISSUE TITLE
Provide needed permissions for your add-in registration

### ISSUE THREAD

**Issue by err-unknown-username** [SharePoint/sp-dev-docs#2998]
Would be great to have a link here to an article that explains the requirements of this xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fa174b-1d60-cbd8-3362-63d257e085f8
* Version Independent ID: 579ca069-6fa3-4a74-ef4b-ec7c37509912
* Content: [How to provide add-in app only tenant administrative permissions in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online)
* Content Source: [docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The article exists. 
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint
