### ISSUE TITLE
Workbench not working on First Release tenant

### ISSUE THREAD

**Issue by panjkov** [SharePoint/sp-dev-docs#3]
Hi,
I have First Release tenant subscription. When I setup my existing DEV site collection as specified in documentation and try to open workbench, I receive error "The requested operation is part of an experimental feature that is not supported in the current environment. "

It is not noted in the setup docs that specific version of SharePoint tenant is required. Please clarify in documentation.

**Comment by patmill** [comment]
Added some additional clarification.  Thanks.

**Comment by patmill** [comment]
(I should have clarified though - are you getting your setup steps from https://github.com/SharePoint/sp-dev-docs/wiki/Setup-SharePoint-Tenant or from a different page?  I've updated the Setup-SharePoint-Tenant page.

**Comment by panjkov** [comment]
That is the page I was using too, yes.

**Comment by mauricionr** [comment]
@patmill i created a new sharepoint dev site, create the specified column but i'm still getting this error

![image](https://cloud.githubusercontent.com/assets/2263551/17824036/037b890a-6636-11e6-9a33-69b9a1458f24.png)


:cry:

**Comment by panjkov** [comment]
@mauricionr having only a DEV site collection is not enough. You need full DEVELOPMENT tenant that you can create from the link above https://github.com/SharePoint/sp-dev-docs/wiki/Setup-SharePoint-Tenant
