### ISSUE TITLE
Documentation/Samples for ClientSideApplication or too soon?

### ISSUE THREAD

**Issue by wcarson** [SharePoint/sp-dev-docs#300]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Are there any samples/tutorials/documentation available for "full-page apps" (`ClientSideApplication`)? I got a sample app working by looking at the source code for the Workbench, but I'm sure I'm missing a lot of the features. I understand that this is a preview and web parts are the focus, so maybe formalizing the client side app model is further down the road?

**Comment by chakkaradeep** [comment]
This is out of scope for the current iteration and have it in the backlog. We will look into this after we ship web parts and SPFx GA. Thanks!

**Comment by chakkaradeep** [comment]
@wcarson I am closing this issue for now (as per my comment above) as we don't have official support for this yet.

Thanks!
