### ISSUE TITLE
SPfx react 15.6v web parts are not loaded in Chrome and firefox intermittently from tuesday

### ISSUE THREAD

**Issue by JishaRajesh** [SharePoint/sp-dev-docs#3002]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

>

#### Expected or Desired Behavior

> The react web parts on the page were working fine till Tuesday. Now in the chrome and the firefox browsers, it fails to load with error "Failed to load resource". they work fine with IE and edge. This issue is intermittent  and seen only with react webparts . the web parts using angular js on the page are loading fine.

Also, the jquery reference in master page jquery-2.2.4.min.js when commented the issue is not seen in chrome. Customer wants to know if this is known issue or if there are any changes that happened recently is causing this issue.
>

#### Steps to Reproduce

Not seen in hello world web part.

sample web part can be shared based customer's confirmation

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
So, does this happen with a hello world webpart based on the react template?  What is the actual text in the "Failed to load resource error"?  Is there anything in the dev tools console?

**Comment by JishaRajesh** [comment]
Hi Pat,

No this does not replicate with hello world. Looks like there is a jQuery version conflict, as customer is able to overcome the error , if they comment out a jQuery reference made in the master page.
Dev tool also does  not capture any useful logs. I could see close to 63 errors in chrome, most of them referring to failed to load resource.

Regards,
Jisha

**Comment by patmill** [comment]
Is it safe to assume at this point that this is something that the customer will resolve (the conflicting jquery libraries)?  Feel free to reopen if you feel differently.  Thanks,

**Comment by jonathanhotono** [comment]
@patmill i can also can replicate this. Had a few spfx webparts with external jss and css (not necessarily jquery) on sharepoint classic page. And it is causing the rest of the webparts within the page to stop loading without any console errors or network errors. Only console errors I got is the cssRules error which is also showing when the webparts are correctly loaded. I am using spfx 1.7.1
![image](https://user-images.githubusercontent.com/6864547/54001038-09689d80-419e-11e9-9b1b-a0fb522cd26e.png)
