### ISSUE TITLE
SPFx: 1.7.0 - tslint.json in config folder

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#3009]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Here is my tslint.json in config folder:
[tslint.txt](https://github.com/SharePoint/sp-dev-docs/files/2617555/tslint.txt)

Steps to upgrade SPFx to 1.7.0 involve removing the above file and create a new tslint.json at the root level with the following content:

{
  "extends": "@microsoft/sp-tslint-rules/base-tslint.json",
  "rules": {
    "class-name": false,
    "export-name": false,
    "forin": false,
    "label-position": false,
    "member-access": true,
    "no-arg": false,
    "no-console": false,
    "no-construct": false,
    "no-duplicate-variable": true,
    "no-eval": false,
    "no-function-expression": true,
    "no-internal-module": true,
    "no-shadowed-variable": true,
    "no-switch-case-fall-through": true,
    "no-unnecessary-semicolons": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-with-statement": true,
    "semicolon": true,
    "trailing-comma": false,
    "typedef": false,
    "typedef-whitespace": false,
    "use-named-parameter": true,
    "variable-name": false,
    "whitespace": false
  }
}

Is it allowed to add the content from the file removed to this new file?

**Comment by patmill** [comment]
Some of the tslint rules have changed, but it should be OK as a starting point.  I expect tslint will generate errors on rules it doesn't understand.
