### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by dipalbhavsar** [SharePoint/sp-dev-docs#3011]
The link provided in the section of "Current status of SharePoint Framework" does not work - following is the content of the link: 
"General Available (GA) milestone" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f553eaa8-5792-3bdf-d9a8-dcbfc92e53ab
* Version Independent ID: e16322c4-8793-4f20-bc6a-984b78c1b403
* Content: [SharePoint Framework (SPFx) enterprise guidance](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance)
* Content Source: [docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/enterprise-guidance.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Fix
