### ISSUE TITLE
Type for adding data

### ISSUE THREAD

**Issue by amirdelfan** [SharePoint/sp-dev-docs#3012]
The sample data is a little confusing. 'listname'.ListItem ; there should be no dot between listname and ListItem. For example: '__metadata':{'type': SP.Data.MyListNameListItem}.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa0c9cd-d807-8d1b-1eb0-66373fa254b9
* Version Independent ID: 409a88a8-7ae9-afde-d66c-81529ad15669
* Content: [Get to know the SharePoint REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service)
* Content Source: [docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi @amirdelfan , @VesaJuvonen 
Fixed this issue in pull request https://github.com/SharePoint/sp-dev-docs/pull/4138
Please review. Thank you.

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
Submitted new PR https://github.com/SharePoint/sp-dev-docs/pull/4183 based on your suggestions at https://github.com/SharePoint/sp-dev-docs/pull/4138#pullrequestreview-251884108
Please review and let me know, if any changes needed.
Thank you.

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
Submitted new PR https://github.com/SharePoint/sp-dev-docs/pull/4185 based on your suggestions at https://github.com/SharePoint/sp-dev-docs/pull/4138#pullrequestreview-251884108

Please review and let me know, if any changes needed.
Thank you.
