### ISSUE TITLE
msGraph cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by Mario-Brnada** [SharePoint/sp-dev-docs#3013]
Hi,
in my react component i  use msgraph but i get the message "cannot read property 'context' of undefined"
My code:
` this.context.msGraphClientFactory
        .getClient()
        .then((client: MSGraphClient): void => {        
          client
            .api('/me')
            .get((error, response: any, rawResponse?: any) => {
            console.log(response);
            });
        })`
I tried to pass the context from my webpart to the component but then i get the error "Cannot read property 'context' of undefined"

Any idea?
Thanks

**Comment by patmill** [comment]
My guess is that the call above this is made to a function without a proper binding.  Ie, if this code is in a function makeGraphCall, you should have some code like this.makeGraphCall.bind(this)

**Comment by VesaJuvonen** [comment]
@Mario-Brnada - You should either provide more code which others can repro or there's nothing really we can do with this.

**Comment by semekhlouf** [comment]
I've the same error using this code:
import * as React from 'react';
import styles from './Graph1.module.scss';
import { IGraph1Props } from './IGraph1Props';
import { escape } from '@microsoft/sp-lodash-subset';
//import {MSGraph} from './MSGraph';
import MSGraph from 'msgraph-helper';
import { MSGraphClient } from '@microsoft/sp-http';


export default class Graph1 extends React.Component<IGraph1Props, {}> {


  public   componentDidMount():void{
     // await MSGraph.Init(this.context.msGraphClientFactory);

     // let memberOf = await MSGraph.Get('/me/memberOf');

    
  }

  public render(): React.ReactElement<IGraph1Props> {
    
    this.context.msGraphClientFactory
      .getClient()
      .then((client: MSGraphClient): void => {
        // get information about the current user from the Microsoft Graph
        client
          .api('/me')
          .get((error, response: any, rawResponse?: any) => {
            // handle the response
            let R = response;
            
        });
      });
  

    return (
      <div className={ styles.graph1 }>
        <div className={ styles.container }>
          <div className={ styles.row }>
            <div className={ styles.column }>
              <span className={ styles.title }>Welcome to Graph TESTER!</span>
              
            </div>
          </div>
        </div>
      </div>
    );
  }
}
