### ISSUE TITLE
gulp deploy-azure-storage does not accept parameters

### ISSUE THREAD

**Issue by TobiasWollmann** [SharePoint/sp-dev-docs#3019]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

In order to setup a VSTS Build/Release Pipeline for a multi staged environment i want to be able to pass different parameters to the "gulp deploy-azure-storage" task which overrides existing values in the deploy-azure-storage.json file. 
Sample: "gulp deploy-azure-storage --container devenvone --account devaccount --accessKey verysecret" 
Is this possible or handled differently? 

Background: My goal is that i want to store the accessKey in azure key vault for example. Beside of that we use seperate cdns per stage which means container and account is changing as well.
Is there maybe another best practice that i overlooked? 
I could build a gulp task that performs all of this but it seems hacky and britle to me. Others wrote the azure upload themself and this would work as well but all of this adds fuzz to the process which is not needed in my eyes.

Thanks in advance for your help.

**Comment by Seiyasu** [comment]
As this falls directly under the gulp-azure-storage, we in the SharePoint engineering cannot, unfortunately, solve this and would request to add an entry to [here ](https://github.com/joaomoreno/gulp-azure-storage)which is their location for reported issues. This is clearly not due SharePoint.
