### ISSUE TITLE
SharePoint Framework Yeoman generator replaces the existing package.json file

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#302]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
If the folder where a new SPFx project is being scaffolded into already contains a **package.json** file then I would expect the generator to merge its contents with the existing file. This is desired in scenarios where you want to install Yeoman and the SPFx generator locally rather than globally and include them in the list of devDependencies. In the current setup they are removed from the list of dependencies and have to be reinstalled after scaffolding the project.

#### Observed Behavior
During scaffolding the SPFx Yeoman generator replaces the existing package.json file with its own.

#### Steps to Reproduce
- `$ npm init --force`
- `$ npm i yo @microsoft/generator-sharepoint -D`
- `$ cat package.json`
  - **yo** and **@microsoft/generator-sharepoint** are both listed as **devDependencies**
- `$ ./node_modules/.bin/yo @microsoft/sharepoint`
- `$ cat package.json`
  - both **yo** and **@microsoft/generator-sharepoint** are removed from the list of **devDependencies**

**Comment by chakkaradeep** [comment]
Hi @waldekmastykarz,

While we understand the scenario of installing and managing the yeoman generator locally within a project, we are focusing on the global installation for GA. For now, we would recommend taking a copy and then updating that with the generated package.json for this issue. Post GA, we will look into this specific scenario. 

Thanks,
Chaks

**Comment by patmill** [comment]
As mentioned, the standard flow is to use yeoman in a global scope.  If there is still a feature request here, can you open up a user voice please?  https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/
