### ISSUE TITLE
🐞SPFx v1.7.0 generated launch.json breaks VSCode+Chrome Debugging (with workaround)

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#3020]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When following instructions in the docs (*[Debug SharePoint Framework solutions in Visual Studio Code](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)*), debugging projects in VSCode with Chrome should work.

#### Observed Behavior

Breakpoints aren't hit.

**Reason**: hint path for `sourceMapPathOverrides` in **launch.config** is no longer correct for latest recent SPFx projects (v1.5.* => current [1.7]).

#### Steps to Reproduce

- Create new project with SPFx v1.7 with a web part
- Set a breakpoint on the `[..]WebPart.render()` method's `return ..` line
- Start web server: `gulp serve`

  > *NOTE: Can't use `gulp serve --nobrowser` as the runtime packages aren't added to load the local API server / local workbench. This is a somewhat related, but not directly related issue*

- Close & quit all instances of Chrome
- Start the debugging process in VSCode
- Use the opened instance of Chrome, navigate to local workbench, add web part of the page
- Observe breakpoint not hit

#### THE FIX: Steps for Workaround

After step 1 above, after creating the project...
- open **config/launch.json**
- Add this line to the `sourceMapPathOverrides` array:

```json
"webpack:///.././src/*": "${webRoot}/src/*",
```

- Continue with step 2 above... except replace the last step: *"Observe breakpoint **is** hit"*

Consider removing the other options... not sure if they are still possibilities...

The problem is a change to the project structure in the generated files by the SPFx Yeoman generator change the path where webpack thinks the files are located.

#### Related issues:

These can be closed when this bug is fixed: #2062, #2267, #2831

**Comment by patmill** [comment]
Thanks.

**Comment by MarianoPrz** [comment]
I've the same issue, and even with the workarounds I can't debug... is there any update? it's quite critical, thanks in advance

**Comment by andrewconnell** [comment]
@MarianoPrz ... you modified the `launch.json` config & the breakpoint isn't getting hit? Can you describe exactly what's happening?

> I can't debug

Need a bit more info to understand what's not working & what you're doing.
