### ISSUE TITLE
npm install fails since flatmap-stream removed from npm

### ISSUE THREAD

**Issue by nero120** [SharePoint/sp-dev-docs#3021]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Using v1.7.0, npm install no longer works since [flatmap-stream was removed from npm after being discovered it was maliciously added as a dependency to event-stream](https://www.theregister.co.uk/2018/11/26/npm_repo_bitcoin_stealer/).

The dependency chain for event-stream starts at [@microsoft/gulp-core-build-serve](https://github.com/Microsoft/web-build-tools/tree/master/core-build/gulp-core-build-serve) and an [issue has been raised](https://github.com/Microsoft/web-build-tools/issues/961) in that repo.

Once that has been released can you please expedite a v1.7.1 release including the updated dependency?

**Comment by patmill** [comment]
OK, that's weird.  I ran through this this morning explicitly to double check this, and didn't hit an issue (and explicitly removed any local .npmrc file that would intercept installs).  Are you using rush in your toolchain by any chance?

At any rate - looking into this.

**Comment by patmill** [comment]
Also, if you run `npm list flatmap-stream` what is the path that is shown?

**Comment by patmill** [comment]
Is there a chance that your shrinkwrap file is referencing the older version?  Can you delete your shrinkwrap file and rerun npm install?

Here is what a clean project from this morning gave me - 

npm list flatmap-stream


    `-- (empty)

npm list event-stream

    `-- @microsoft/sp-build-web@1.7.0
      +-- @microsoft/gulp-core-build-karma@4.6.30
      | `-- gulp-karma@0.0.5
      |   `-- event-stream@3.0.20
      `-- @microsoft/gulp-core-build-serve@3.2.65
        `-- gulp-connect@5.5.0
          `-- event-stream@3.3.5

**Comment by ronaldborman** [comment]
@patmill This is related to a security breach regarding the event-stream npm package. The specific version of the package was compromized after a owner transfer and was removed by the npm organization.

**Comment by nero120** [comment]
No, after deleting the `package-lock.json` file I'm still experiencing the issue, and the newly generated `package-lock.json` contains:

```
"flatmap-stream": {
  "version": "0.1.2",
  "resolved": "https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.2.tgz",
  "integrity": "sha512-ucyr6WkLXjyMuHPtOUq4l+nSAxgWi7v4QO508eQ9resnGj+lSup26oIsUI5aH8k4Qfpjsxa8dDf9UCKkS2KHzQ==",
  "dev": true
},
```

Note that this is not a fresh v1.7.0 project, it has been upgraded using the o365 cli. Perhaps there is an issue with the upgrade steps generated by the cli?

**Comment by nero120** [comment]
@patmill so essentially yes you were correct. The reason I was encountering an issue was due to the fact that event-stream@3.3.6 was removed from npm but in order to force npm to get event-stream@3.3.5 I had to both delete my package lock (shrinkwrap) file and remove `node_modules`. Once I did both of this then the project successfully installs.

Thanks for your assistance!
