### ISSUE TITLE
Can you please elaborate if we need to match the User-Agent's values to an Office 365 application?

### ISSUE THREAD

**Issue by nddipiazza** [SharePoint/sp-dev-docs#3022]
#### Category
- [x] Question

You say to decorate your web requests with the UserAgent string:

> Enterprise application
> `NONISV|CompanyName|AppName/Version`
> Identify as NONISV and include Company Name, App Name separated by a pipe character and then adding Version number separated with a slash character

But you never mention whether or not the values in the User-Agent need to match an active Office 365 app key or not.

Does CompanyName, AppName and Version need to map to a valid Office365 application values? 

Can someone provide an example / steps / a useful link to the steps we would follow to create such an office365 application with valid values? 

ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
Content: Avoid getting throttled or blocked in SharePoint Online
Content Source: docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Service: sharepoint
GitHub Login: @spdevdocs
Microsoft Alias: spdevdocs

**Comment by Seiyasu** [comment]
The above docs is for mainly for add-in but not the SPFx( There is no need to map to the other O365 application).
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins

**Comment by nddipiazza** [comment]
@Seiyasu so you are saying this user agent can be any string in the format like `NONISV|RandomCompanyName|RandomAppName/123.0.456` and it will help prevent rate limiting?

**Comment by nddipiazza** [comment]
Hi. Pinging you again @Seiyasu to see if you have a chance to look at my follow up questions.

**Comment by sbellan** [comment]
"If you have created an application, the recommendation is to register and use AppID and AppTitle – This will ensure the best overall experience and best path for any future issue resolution"

Not clear what the above means. What is AppID? is it the same as Client ID. And if we are already registering our app with ClientID/Secret, then there is nothing else to do which invoking the REST API's.

**Comment by nddipiazza** [comment]
Is this the steps to follow to create this app? 

First create an app-only principal, see:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

Here are the steps that I followed with our tenant:

Go to the sharepoint admin registration area:

https://xxxxxxxxxxx-admin.sharepoint.com/_layouts/15/appregnew.aspx

Click create on both Client ID and Client Secret and create a Title, etc.

Click create.

So is this then the app title ? What is the version? Why is this so hard!?
