### ISSUE TITLE
Issue Hosting WP - Fix

### ISSUE THREAD

**Issue by Cutulus** [SharePoint/sp-dev-docs#3024]
I had the same issue that seems to have been closed without anyone knowing what went wrong. Just like in older versions of SharePoint if your web part or solution does not work as expected, uninstall it and reinstall it. I got the client side assets error and deleted the web part from the page, then uninstalled the app, deleted from the recycle bin (and second stage recycle bin) and then added the app back to the site and added the WP back to the page.

At least I don't have to recycle SharePoint to retract or uninstall the solution now. So a lot better still.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Cutulus** [comment]
Look at the closed issues and you will see what I am referring to. When you switch from Local to CDN the web part fails. This is because you are still hosting the old solution. If you follow all the steps laid out to this point and gulp serve is not running you will see the error. This is corrected by following the steps I laid out.

**Comment by VesaJuvonen** [comment]
Thanks, @Cutulus on providing input on this. We'll close this for now as answered.
