### ISSUE TITLE
 Single command to perform delete node-modules folder and run npm install

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#3028]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a single command to perform both 1) delete node-modules folder and 2) run npm install?

I upgraded SPFx version to 1.7.0 and submitted a PR with these changes. On pulling those changes from my PR, my teammates had to first delete node-modules folder and do an npm install to get upgraded to 1.7.0. I am just curious to know if there is command to do both so that I can just add that command as preinstall command in package.json?

**Comment by patmill** [comment]
You shouldn't need to do that.  Updating package.json and rerunning npm install should (in general) work.  Occasionally npm gets confused, and you need to nuke node_modules, but it shouldn't need to be a constant.

As for deleting node_modules, I typically do it in two phases.  1st, move it out of the working directory so I can npm install, then delete it following this long and informative thread - https://stackoverflow.com/questions/186737/whats-the-fastest-way-to-delete-a-large-folder-in-windows

**Comment by xyz92** [comment]
Thank you!
