### ISSUE TITLE
Include flag on generator to skip NPM install post scaffolding

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#303]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

Every time the generator runs, it calls `npm install` to download all package dependencies. Please consider adding a flag when running the generator to bypass this and not download all dependencies.

Currently you have to always cancel the download of packages if you just want to scaffold the project up.

Suggest:

```shell
$ yo @microsoft/sharepoint --skip-install
```

**Comment by waldekmastykarz** [comment]
Is this the same issue as #235 @andrewconnell?

**Comment by andrewconnell** [comment]
Yup... didn't see it before. Thanks.
