### ISSUE TITLE
addPrincipalToGroup should be addPrincipalToSPGroup  

### ISSUE THREAD

**Issue by rishiuiit** [SharePoint/sp-dev-docs#3030]
The description says "Use the addPrincipalToGroup action to manage addition of users and groups to select default SharePoint groups. For more information, see Understanding SharePoint Groups. This action can be used for licensed users, security groups, and Office 365 Groups" 
The actual verb is addPrincipalToSPGroup. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Fix

**Comment by rishiuiit** [comment]
I still see addPrincipalToGroup in the content. Is this not published yet?

**Comment by Seiyasu** [comment]
Yes, the code merge is a phased, not in real time
