### ISSUE TITLE
Upon deleting site is it possible to redirect to any other page ??

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-docs#3032]
Hi, 

Once a site is deleted we will be taken to "_layouts/15/sharepoint.aspx" page. Is it possible to redirect user to any other page ??? 

Thanks, 
Pavan.

**Comment by Seiyasu** [comment]
I am not sure you use the sitesetting or admin portal or other way, but the answer should always be no.
From site setting, the redirect url will be https://xxx.sharepoint.com/sites/xxx/_layouts/15/webdeleted.aspx?c=1033&ui=2052&uiv=15 on my side.
From admin portal, the redirect url will be https://xxx-admin.sharepoint.com/_layouts/15/online/SiteCollections.aspx

You can submit one feature request in the [UserVoice](https://officespdev.uservoice.com/). Although you want is moot.
