### ISSUE TITLE
Port conflict - PostgreSQL

### ISSUE THREAD

**Issue by Bluezen** [SharePoint/sp-dev-docs#3033]
I just wanted to give a quick heads-up about the port conflict if you have PostgreSQL installed. You must open the *serve.json* file and update the the port to something else than *5432*:
```
"initialPage": "https://localhost:8083/workbench",
  "api": {
    "port": 8083,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KingKangMSFT** [comment]
Thanks @Bluezen ， the default port of PostgreSQL is 5432 that will conflict the webpart’s default port
