### ISSUE TITLE
Quota logic has suddenly changed from GB to TB

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#3034]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

It seems that the logic of setting a quota for a site collection in SPO has been suddenly changed:

We have noticed that all new sites have a quota / StorageMaximumLevel of **27 TB**. It seems that at some point Microsoft secretly switched the quota entry from GB to TB. Even in the Tenant Administration new sites have a default quota of more than 25000 GB:

![image](https://user-images.githubusercontent.com/31658807/49229958-e4220180-f3ee-11e8-96ee-9719f56cb767.png)

This also means all examples in PNP Documentation are now incorrect e.g. [this one](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantSite.md):

`Set-PnPTenantSite -Url https://contoso.sharepoint.com -Title "Contoso Website" -StorageWarningLevel 8000 -StorageMaximumLevel 10000`

> This will set the title of the site collection with the URL 'https://contoso.sharepoint.com' to 'Contoso Website', set the storage warning level to 8GB and set the storage maximum level to 10GB.

This will now set a quota of 10TB and not 10GB.

**Is this a bug? If not it would have been nice to have some sort of news so we could have changed our provisioning logic and other processes dealing with quotas and site size...**

**Comment by VesaJuvonen** [comment]
As this is not related on developer API or extensibility, we cannot handle this through this issue list.
