### ISSUE TITLE
DefaultClientSideWebParts: Recent document missing from list in PnP Core

### ISSUE THREAD

**Issue by Mike-tech** [SharePoint/sp-dev-docs#3035]
Hello

From the UI I can add out-of-the-box Recent documents web part. But i can't see this as part of the list when using the PnP Core csom code DefaultClientSideWebParts.

I need to add this programmatically to a client side page, any idea where i can find this web part?

Thanks

**Comment by Seiyasu** [comment]
The suggestion for you is submit an feature in the UserVoice or create an new issue in the https://github.com/SharePoint/PnP-Sites-Core. It exceeded this library's support

**Comment by Mike-tech** [comment]
Oh ok. I've used a workaround. I have a template site where the recentDocuments web part has already been added to a page. So i copy the client page object and got the copy of the web part from the Sections:

```
public static void SetupHomePageContent(ClientContext context, ClientSidePage holdCopyPage) {
ClientSidePage page = ClientSidePage.Load(context, "Home1.aspx");
if (page != null) {
  page.Sections.Clear();
  page.Sections.AddRange(holdCopyPage.Sections);
  page.Save();
}
}
```
