### ISSUE TITLE
Date as Condition for Formatting

### ISSUE THREAD

**Issue by KEW1984** [SharePoint/sp-dev-docs#3036]
I'm using the following JSON schema to color code rows in a Microsoft SharePoint list:

{ "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json", "additionalRowClass": "=if([$Termination_x0020_Date] &lt;= @now, 'sp-field-severity--blocked', if([$Termination_x0020_Date] &lt;= @now+180, 'sp-field-severity--warning' ,if([$Termination_x0020_Date] &gt;= @now+180,'sp-field-severity--good', if([$Termination_x0020_Date] == '','', ''))))" }

- If the date in the Termination Date column is today or older, the row is red.
- If the date in the Termination Date column is greater than or equal to 180 days from today, the row is green.
- If the date in the Termination Date column is less than or equal to 180 days from today, I want the row to be yellow.
- If the date in the Termination Date column is blank, I want the row to have no color.

The red and green color works. Blank rows are showing up as red and yellow doesn't work at all. I feel like there's a problem with how I'm formatting the date. I need the following:

- less than or equal to 180 days from @now
- blank row

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#feedback)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by iamguptarishi** [comment]
The Date datatype has default value in any programming language. Here in SharePoint also if you save a blank date the default date is saved in back end. In your case its reading the default value like "12/30/1899" and applying the formatting.  That's the reason its displaying the row as red.

It seems that IsBlank function which is available in Excel is not supported in JSON format. It seems that all excel formulas will not work.

**Comment by VesaJuvonen** [comment]
Closing as seems to be answered by @iamguptarishi.
