### ISSUE TITLE
Issue while activating Site collection feature

### ISSUE THREAD

**Issue by iamguptarishi** [SharePoint/sp-dev-docs#3037]
I was trying to activate the site collection feature using site scripts. The verb I used is 
 {
        "verb" : "activateSPFeature",
        "featureId":"7094bd89-2cfe-490a-8c7e-fbace37b4a34" //Reporting feature to be activated at site collection level
 }
The activation works fine with web features, but failed at site collection level features. Is there a way to activate site collection level features using site scripts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by pratyushasushma** [comment]
I was facing the same issue, could you please let me know if this issue is resolved

**Comment by anisiaalexandra** [comment]
Same question here: Is there a way to activate site scoped features? I understand that this are actions that normally are applied to the current web, but as long as we can create Site columns, shouldn't it be logic to be able to activate site scoped features as well? 
When will we have a full pallete of actions that will allow us to do most of the needed stuff without extra cost (Flow) something like executing a PS script?
Thank you in advance for your response.

**Comment by alirobe** [comment]
Facing same issue here. Client wants to activate "Open Documents in Client Applications by Default" (8a4b8de2-6fd8-41e9-923c-c7c3c00f8295) tenant-wide, and cannot find a way to do it. Thought this was the answer, but alas, it's half-assed.

**Comment by alirobe** [comment]
Was actually able to resolve this using an undocumented feature I found in the JSON schema. There's a "scope": "site|web" option, which lets you activate either. Confirmed this worked for my use case.
