### ISSUE TITLE
How to create a page using site scripts?

### ISSUE THREAD

**Issue by iamguptarishi** [SharePoint/sp-dev-docs#3038]
As per the JSON schema you can create a page using site scripts, but it doesn't seems to be working. I tried below verbs.

{
    "$schema": "schema.json",
    "actions" : [
    {
     "verb": "createPage",
        "fileName": "WelcomePage.aspx",
        "pageData": 
     {
         "Title":"Welcome to your site",
       "BannerImageUrl":"https://tenantURL.sharepoint.com/:i:/s/SiteDesignTeams/EezSIpu9gJRPmhTm4HUJXOwBc7cmUHsDDE5pJyLdqqlIlQ?e=sXuLHE",
         "CanvasContent1":"&lt;div&gt;/div&gt;",
         "LayoutWebpartsContent":"{\"id\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"instanceId\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"title\":\"Title Region\",\"description\":\"Title Region Description\",\"serverProcessedContent\":{\"htmlStrings\":{},\"searchablePlainTexts\":{},\"imageSources\":{},\"links\":{}},\"dataVersion\":\"1.4\",\"properties\":{\"title\":\"\",\"imageSourceType\":4,\"layoutType\":\"FullWidthImage\",\"textAlignment\":\"Left\",\"showKicker\":false,\"showPublishDate\":false,\"kicker\":\"\"}}"
     },
        "setAsHomePage": true
    },
    {
        "verb" : "activateSPFeature",
        "featureId":"15a572c6-e545-4d32-897a-bab6f5846e18"
    },
 ],
 "version": 1
 
 }

The page is created but when I click on the page it throws an error stating NoComponentId. The site script does show the status of failure after executing site script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
I believe this error comes not not setting the ClientSideApplicationId to 'b6917cb1-93a0-4b97-a84d-7cf49975d4ec' . It doesn't look like the schema supports this, so I'm hoping the framework will be doing it for us when creating a new page.

**Comment by trillian74** [comment]
@bcameron1231 @iamguptarishi @VesaJuvonen  Did you get this to work? It kinda gets more and more interesting to do page generation thru site-scripts since our templates have default pages that needs to be created with content.

or is it just added as teaser by the sharepoint team? :)

It goes without saying that i'm experiencing the same scenario as @iamguptarishi

**Comment by VesaJuvonen** [comment]
Creating pages through the Site Scripts are not yet supported. We will be providing updates on the documentation when this capability will be enabled, but there is no point to test this as it's not yet enabled.

**Comment by annajhaveri** [comment]
Is creating pages supported now?

**Comment by bcameron1231** [comment]
@annajhaveri Nope. Creating pages is not supported.

**Comment by rrtoland** [comment]
Getting closer?  .... 
![image](https://user-images.githubusercontent.com/15697243/57957343-2ebe0a00-78b9-11e9-9785-33120a32f597.png)

**Comment by Lee-Myhre** [comment]
Is this available in dev tenants maybe? Our company doesn't have one yet, but our secondary tenant we made originally to function as a "dev" tenant is First Release and I get the same "experimental feature" error as @rrtoland showed above, both in PowerShell and in the browser when creating a new site with a design containing the action.

Screenshot of the behaviour in Browser is below (ignore the colour scheme, I was using an early theme I made to test the theming system)
![image](https://user-images.githubusercontent.com/22507239/61755742-ce8e8d00-ad6d-11e9-8137-4cb2296a6fc2.png)

**Comment by bcameron1231** [comment]
Not available yet. Still experimental.

**Comment by DmitryVorobyov** [comment]
According to this it should be launched by now: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=page%2Csite%2Cdesigns 

Any ETA on the general availability?

**Comment by VesaJuvonen** [comment]
This feature is not yet supported. No ETA. No idea how the road map page would claim that it's out, but it's not there. You will need to use PnP API for the modern page creation either PnPjs or PnP Sites Core.

**Comment by rrtoland** [comment]
Thanks for clarifying, Vesa!
