### ISSUE TITLE
Spfx Extension Field Customizer default fallback support

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#3039]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

As discussed https://github.com/SharePoint/sp-dev-docs/issues/906#issuecomment-431658330

It would be great to have default support on spfx extension to return the default element as a fallback option instead of setting the column blank. 

Update:
Sample could be:
1. DocIcon
2. Title with edit menu
3. Taxonomy/Managed metadata column ? (not sure if supported)

**Comment by VesaJuvonen** [comment]
Can you clarify what exactly is the ask here and how even as a pseudo code this could work? Why wouldn't you write the needed default value when you override the onRenderCell method?

**Comment by matthong** [comment]
There is a feature request in UserVoice. 
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/31530607-field-customizer-ability-to-call-ootb-render-meth
