### ISSUE TITLE
Web parts not installed when adding the SPFx add-in in a subsite

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#304]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When installing the SPFx add-in in a subsite, web parts can be added to pages in that site.

#### Observed Behavior
When installing the SPFx add-in in a subsite, web parts are not provisioned to the web part gallery and it's not possible to add web parts to pages. This has to do with the fact that the feature provisioning .webpart files is web-scoped while the web part gallery exists only on the root web of the site collection. As a result the `_catalogs/wp` URL points to a URL that doesn't exists in the subsite.

#### Steps to Reproduce
- create site collection
- add subsite
- in the subsite add the SPFx add-in
- edit the page to add the web parts from the SPFx add-in
  - web parts are not included in the list of available web parts
  - check the web part gallery in the site collection
    - web parts from the SPFx package are not present in the gallery

**Comment by chakkaradeep** [comment]
In the next drop or so, we are changing this behavior to load the web parts from the tenant catalog just like it happens in modern pages. That should resolve this issue.

Thanks!

**Comment by waldekmastykarz** [comment]
Does that mean that it would be no longer necessary to install the SPFx add-in in the site?

**Comment by chakkaradeep** [comment]
If you have items to provision, such as list or library, along with your web part, then you will have to install the SPFx solution in the site. If not, you don't.

**Comment by dcu-sharepoint** [comment]
@waldekmastykarz @chakkaradeep : a couple of questions.
1) I assume when you say "create a site/sub-site" you mean in the O365 developer account, right?
2) in the segment 
**in the subsite add the SPFx add-in
edit the page to add the web parts from the SPFx add-in
web parts are not included in the list of available web parts
check the web part gallery in the site collection
web parts from the SPFx package are not present in the gallery**

**how do you add the web parts from the SPFx add-in?**

for example: I've created the **hello-world-sp** example from the tutorials, have built it and run the gulp serve and the webpart works as expected on the localhost:4321/workbench.html.
so my question here is how do I load this helloWorld webpart into my office 365 site.
or at least can you point me to the docs where I can read and learn the process?

Thanks for your help.

**Comment by waldekmastykarz** [comment]
@dcu-sharepoint here is more information about how you can deploy SPFx web parts to SharePoint: https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page

**Comment by dcu-sharepoint** [comment]
@Waldek

that's exactly what I was looking for. I had posted on a forum and was sent to another forum and then to stackoverflow where the question just died about a week ago....

now I can get going. thanks again. may the gods of wealth keep healthy rich and famous.... [😳]


________________________________

**Comment by mpasarin** [comment]
Web parts on classic pages don't use .webpart files anymore, so this issue is non-existent with the new architecture. Closing it.

**Comment by RaspeR87** [comment]
If you want to install spfx web parts for on-prem too please take a look at my blog post -> [https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/](https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/)
