### ISSUE TITLE
On close of Site set-up status panel (which appears during new site creation using custom site design) site updates are not displayed until manual browser refresh

### ISSUE THREAD

**Issue by Chaitra1006** [SharePoint/sp-dev-docs#3040]
#### Category
- [#] Question
- [ ] Typo
- [#] Bug
- [ ] Additional article idea

When creating a new site using a custom site design(with action to add webpart to landing page etc), a panel with close option(at top right corner of the panel) will open up on the right showing the set-up status for the new site. If the user click on close of the panel during the site updation process or after the site updation process completion the site does NOT show custom site design updates. 

![image](https://user-images.githubusercontent.com/38909384/49271195-a2e32d80-f492-11e8-8812-7c6c8a889dde.png)

![image](https://user-images.githubusercontent.com/38909384/49271265-dcb43400-f492-11e8-8cd3-67539a031aff.png)

#### Expected or Desired Behavior
Even on close of the set-up status panel, site should refresh to show the custom site design updates.

#### Observed Behavior
Only on manual browser refresh custom site design updates is displayed.

#### Steps to Reproduce
1. Go to Sharepoint.aspx page
2. Click on + Create Site 
3. Select custom Site Design option
4. Enter new site details and click on Next button
5. Click on Finish
6. New site will be displayed with a overlay panel opened up on the right showing the set-up status for the new site
7. Click on Close (top right of the panel)
Default site template without custom site design updates is displayed.

**Comment by Seiyasu** [comment]
I guess you want to add some SPFx to the custom site design.
The SPFx relay on the Dom element, so it not add the page directly without initializing. So the site need manual to refresh.

Some enhancement are needed but maybe it should not be treated as bug.

**Comment by Chaitra1006** [comment]
Agree. Would be glad if it is addressed as enhancement.
