### ISSUE TITLE
SPFX extension stopped working in one of the tenants.

### ISSUE THREAD

**Issue by spoman007** [SharePoint/sp-dev-docs#3041]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a list command set extension in spfx app. SPFX version is 1.4.1
The app is working in 2 out of 3 tenants.

#### Observed Behavior

This is the message I get in the console.
**Failed to loadCommandSet, id: xxxx-xxxx-xxxx, error: Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.**

**Comment by patmill** [comment]
Can you share any additional information?  What version or React are you using?  Command sets generally don't have a UI element or DOM, and the error is stating "_registerComponent(...): Target container is not a DOM element".  Are you modifying a DOM element on the page somewhere?

**Comment by spoman007** [comment]
@patmill It started working today without making any change.
I believe it had something to do with the way command sets are rendered.

Not sure what changed, if error had been little more clear it would have helped.

Thanks!!

**Comment by SharePickle** [comment]
@spoman007 got similar message today [](https://reactjs.org/docs/error-decoder.html/?invariant=38) 
I had to update SPFx solution to version 1.7.0 and React to 16.3.2 and it worked. Looks like MS React update for Office 365 has finally arrived to all tenants including those with Standard release.
What's your React version and SPFx version?

**Comment by spoman007** [comment]
@SharePickle My SPFX version is 1.4.1 and react version is 15.6.6.
Its bit old, but it worked seamless until friday and then stopped suddenly(Only in one of my tenants).

But on monday everything seems to work fine.

**Comment by patmill** [comment]
@spoman007 - how are you referencing the fabric react package?

**Comment by spoman007** [comment]
I guess you mean, the sp-office-ui-fabric-core.
Here is the version
**"@microsoft/sp-office-ui-fabric-core": "~1.4.0",**

And this is how I am referencing it
**import { Dialog } from '@microsoft/sp-dialog';**

@patmill , hope this is what you were asking?

**Comment by patmill** [comment]
Sorry, not exactly.  You might not be using fabric-react all, which is fine.

if you search package.json for "fabric-react" do you get anything?  If so, what are the lines?

**Comment by spoman007** [comment]
You are right then, I am not using fabric-react.

My package.json does not have it.

**Comment by patmill** [comment]
OK, SharedPickle has a separate bug open, so I'm going to close this one.

**Comment by spoman007** [comment]
![image](https://user-images.githubusercontent.com/8514338/49438364-709d3d00-f7be-11e8-974b-bcb82acca7e0.png)

@patmill I started receiving the error again.
I am attaching the screenshot of console error.
Not sure what is causing this.

@SharePickle Were you able to get any ideas about issue you were having?

**Comment by SharePickle** [comment]
@spoman007 yes,  I used library which seems like no more compatible with spfx 1.6.0. Moving code to 1.7.0 resolved the issue. Also removing incompatible lib helped too.

**Comment by spoman007** [comment]
So I did some digging and found that issue is where I am trying to render component

`ReactDom.render(<MyComponent />, document.getElementsByClassName('ms-compositeHeader-peopleInfo')[0])`

Somehow, item with class name **ms-compositeHeader-peopleInfo** does not render in one of the tenants, which caused the failure.
So I used `document.getElementsByClassName('od-Resize')` instead and it worked.

It would be great if I could figure it out easily based on error.

Thanks @patmill and @SharePickle

**Comment by SharePickle** [comment]
Seems unreliable, this items are not part of placeholders spfx provides I think, you should not use custom classes and ids unless absolutely sure markup won't change in future or might not be present in some cases.

**Comment by spoman007** [comment]
@SharePickle You are right, never gave it a thought but I will change to use placeholders provided by spfx

Something like this
`placeholder = this.context.placeholderProvider.tryCreateContent(PlaceholderName.Top);`
`ReactDOM.render(MyComponent, placeholder.domElement);`

**Comment by patmill** [comment]
Yes, you never want to look for a dom element and replace it.  That is not supported (because it will occasionally break, like this).  Always use the DOM element that SPFx gives you, either in the placeholder or in the webpart.
