### ISSUE TITLE
Automate SPFx version upgrade

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#3044]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a way to automate SPFx version uppgrade on a sharepoint project? Thank you!

**Comment by xyz92** [comment]
Isn't Office 365 CLI to automatically detect necessary changes for upgrading SPFx version? It generates a report with steps of commands to run for upgrade. Please let me know if I am wrong. I am curious to know if there is a command which on running would automatically upgrade sharepoint project to a newer version.

**Comment by waldekmastykarz** [comment]
You are correct: Office 365 CLI generates a report with the list of steps that need to be applied manually to upgrade the project to a newer version. You could of course automate this process yourself, by executing the suggested commands and applying the recommended changes, but it's not trivial and you should ensure you have a backup of your project in case you need to revert the changes.

**Comment by xyz92** [comment]
Thank you @waldekmastykarz

**Comment by waldekmastykarz** [comment]
You're welcome!
