### ISSUE TITLE
Adding Owners to Modern Team Site

### ISSUE THREAD

**Issue by mkeysae2** [SharePoint/sp-dev-docs#3047]
I can provision a modern team site using both the SharePoint CSOM API and UnifiedGroupsUtility API.  The issue is that I cannot update owners.  UnifiedGroupsUtility.CreateUnifiedGroup has optional parameters to set owners and members.  The API accepts owners, but provisions the users as members.  Likewise, UnifiedGroupsUtility.UpdateUnifiedGroup as well as the native owners GRAPH/REST API (https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-beta) all result in the same behavior.  It seems the API is setup to accept both owners and members since there are separate endpoints, but all result in adding members not owners.  

UPDATE - Through further testing, it seems the API is working correctly but SharePoint is displaying the wrong information when viewing the members from the site directly.  The office 365 group in the admin center seems to be displaying the user information correctly, but the site is not.  The permissions however on the site seem correct, as I can administer a site from an owner added through code.  

Additional Update - I have determined this issue is a caching problem.  The SharePoint site will update eventually update to show the correct permissions, but this takes several hours.  This is a problem because the owners added through the API do not have an option to invite additional members until the synchronization takes place.  Is there an API to force a synchronization update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by MrTantum** [comment]
Updating owners and members of a MS Group will always take some time until these changes are visible in SharePoint. There seems to be some kind of caching mechnism on SharePoint site.

If you are using a custom method to update the users you should display some kind of message like:

"The permissions have been changed. It can take up to 10 minutes for the changes to become visible in the system."

**Comment by mkeysae2** [comment]
As you mentioned, it appears that there is a caching issue on the SharePoint side.  It seemed to take longer than 10 minutes, but after coming back over the weekend I can see the correct permissions on the SharePoint side.

**Comment by salesky** [comment]
If you add new owner via Tenant Administrator it is almost immediately updated in SharePoint but when using powershell it takes a lot of time and until then owner cannot add new users to the site...Also this problem is mentioned here https://github.com/SharePoint/PnP-PowerShell/issues/1421 and here https://github.com/SharePoint/PnP-PowerShell/issues/1661

**Comment by advdberg** [comment]
Maybe slightly off-topic but the same kind of issue also appears in Teams when adding users and owners with Graph API to an O365 Group. It can take up to 24 hours before become visible in Teams. We did saw some significant improvements when calling the beta Graph API instead of the v1.0... it now takes only 5 minutes max.

**Comment by mkeysae2** [comment]
advdberg - That's an interesting observation with Teams.  It sounds like it is related.  I think I tested using the beta Graph API, but don't recall an improvement.  I will try again when I have some more time.
