### ISSUE TITLE
Error with RecentDocumentsWebpart

### ISSUE THREAD

**Issue by cassandradanger** [SharePoint/sp-dev-docs#3048]
getting the error:
Error - [tsc] src/webparts/recentDocuments/RecentDocumentsWebPart.ts(81,7): error TS2345: Argument of type 'typeof RecentDocuments' is not assignable to parameter of type 'string | ComponentClass&lt;IRecentDocumentsProps&gt; | StatelessComponent&lt;IRecentDocumentsProps&gt;'.

I'm new to React and Sharepoint, so I'm having a tough time figuring this out. Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32dd282d-6215-df1d-c666-98faf2450bfa
* Version Independent ID: ee0881ae-6660-5d2d-eb3e-cd7ff4fd8b98
* Content: [Share data between web parts by using a global variable (tutorial)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable)
* Content Source: [docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Modify RecentDocuments tsx file:
s React.Component<IRecentDocumentsProps, void>=》s React.Component<IRecentDocumentsProps, any>
