### ISSUE TITLE
SPFX only available in Dev Tenants?

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#305]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Question
Just a quick question, but I can't seem to find a definite answer...
Is SPFX currently (still) only available in Developer Tenants? Or also on "normal" O365 tenants?

Thanks

**Comment by chakkaradeep** [comment]
@NickSevens It is available for First Release tenants. You will need to have enabled the First Release options for your tenant.

**Comment by NickSevens** [comment]
@chakkaradeep when uploading my app it sais the app package is not valid. Uploading the same package in my own dev tenant does work. Dorst release is turned on, but only for selected users. Can that be the reason?
Thanks for the help!

**Comment by clechner77** [comment]
Specifically it needs to be first release for selected users and your user account needs to be one of them. First released for every 1 will not work

**Comment by NickSevens** [comment]
Okay. I added myself to first release group today. I assume there is some propagation delay perhaps?

**Comment by clechner77** [comment]
It took a couple hours for me. You will need to re-upload the app package too.  Keep trying to upload it until you see Yes for valid app package.

**Comment by NickSevens** [comment]
@clechner77 I uploaded the package again, something like 20hrs after adding myself to first-release, but still no luck.
Are you sure "First release for selected users" should work? I tried in 2 non-dev tenants now but can't make it work.

**Comment by chakkaradeep** [comment]
@patmill anyway we could help @NickSevens to see what's going on with his tenants? Thanks!

**Comment by patmill** [comment]
To answer the question "Are you sure "First release for selected users" should work?" - No - this explicitly does not work.  

You need to be first release for the tenant, not select users.

**Comment by NickSevens** [comment]
Glad to have some official confirmation for this. :) we'll have to decide on that first then. Thanks for the clear yes/no ;)
