### ISSUE TITLE
Parameter for passing specific Site Design in Modern Team site Creation

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [SharePoint/sp-dev-docs#3050]
While creating the Modern communication site programmatically through Rest API/ Graph API there is a parameter available to choose the site design.

Title = "title 
Description = "description 
AllowFileSharingForGuestUsers = false 
Classification = "classification" 
SiteDesign = CommunicationSiteDesign.Topic

But while creating the modern team site programmatically there is no option to choose the Site Design, by default it is picking up the default Site Design. Even though we can create multiple site script and site design for Teams site, we are not able to specify a site design at the time of provisioning the Group. 
Is there any possibility to choose a Site Design for Team site while creating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
If the REST API doesn't include it, then not at this time. That would fall under the category of a feature request on User Voice...
