### ISSUE TITLE
How to select SiteGroups using sp pnp peoplePicker

### ISSUE THREAD

**Issue by allanmacritchie** [SharePoint/sp-dev-docs#3052]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I am trying to use the React PeoplePicker control in a web part to allow users to select a SiteGroup and document to add an item with both these to a SharePoint list, no matter what options or configuration I try I cannot get the PeoplePicker to return either of my two site groups as results, how can I fix this?

**Comment by patmill** [comment]
You should ask this in the pnp issues list - https://github.com/SharePoint/PnP/issues
