### ISSUE TITLE
GUID for client ID vs asterisk

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#3055]
I have seen some people are giving asterisk instead of GUID for ClientID. Can you please share the difference here. Also, There is a space at the end. Is that a typo?

&lt;RemoteWebApplication ClientId="a044e184-7de2-4d05-aacf-52118008c44e "/&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be8c8d6-7ed2-1907-3038-49d8e1c92e8a
* Version Independent ID: a2adbe13-e625-3995-fded-fce6c4a701ac
* Content: [Register SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/register-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
The space should be a typo.

In demo project, some guys may use asterisk to  obfuscated code. I have yet to see real - world scenarios using an asterisk.

**Comment by andrewconnell** [comment]
The asterisk is not valid... see the docs for this element. It should be a GUID.

https://docs.microsoft.com/en-us/sharepoint/dev/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in
