### ISSUE TITLE
Deployment failed.  Correlation ID: b7a4a89e-f040-0000-497d-8c8867d761e5

### ISSUE THREAD

**Issue by TomasNielsen** [SharePoint/sp-dev-docs#3058]
#### Category
- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Uploading a .sppkg file to app catalog should accept the web part.
It worked the first time. But after making a small change to a CSS all new attempts to upload the web part fails with above error.
No hint to what is wrong. The correlation ID is a new ID every time and might help Microsoft but us useless for a developer.

#### Observed Behavior
Deployment failed.  Correlation ID: b7a4a89e-f040-0000-497d-8c8867d761e5
It is a valid package (according to app catalog)
It is not possible to use the web part. It appears with an error:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "6dd6fca4-dcb9-446b-b233-3e0c5c04fd04"

Accessing the .js file where the component should be returns this:
{
"HttpStatus": "NotAcceptable",
"ErrorMessage": "Requested asset is not found or is not located in the Public CDN enabled location",
"ErrorCode": 406012
}

#### Steps to Reproduce

Create a React web part using latest of everything. Upload it once and then upload it again.

The first time it worked I had not enabled CDN. After it failed I enabled CDN but it still keeps on failing.

**Comment by SharePickle** [comment]
Had exactly the same issue a few weeks ago. Try removing app from catalog and uploading it again with new version. Don't forget to remove app from site if you haven't selected tenant wide deployment.
We could not figure out why this happening and moved assets to our own cdn. Since then it works fine.

**Comment by patmill** [comment]
Can you look at the network trace and see what the URL that is failing is?  Can you then double check that a corresponding file exists in the assets folder located at /{appcatalogsitename}/clientsideassets/{solutionId}/ .  Finally, if it isn't in clientsideassets, can you double check that it is in the .sppkg zip itself?

**Comment by TomasNielsen** [comment]
**Update**: There seems to be something wrong with that tenant. The same .sppkg file work flawlessly at another tenant I got access to today. I can upload it several times there without even changing the version numbers and changes to it can be seen instantly.

Does Microsoft have a warranty for tenants? Or how do I get it corrected? I'm really happy it is not a production tenant (yet).

@patmill I think it is a tenant issue. The failing files point to https://publiccdn.sharepointonline.com and the URL look correct with what is in the debug folder when I build. But I think the files never end up there on the CDN. It also complains about CORS so those settings has probably also failed to be set when importing the .sppkg file fails.

**Comment by patmill** [comment]
I've seen issues where the public CDN somehow gets out of sync.  I'm not totally familiar with the underpinnings of the feature though.  I'll see if I can get some more info.  At the same time, can you expand around the CORS issue?  Who complains, what's the URL, etc.

**Comment by VesaJuvonen** [comment]
Hi @TomasNielsen - can provide your tenant name, so that we can check the correlation ID details. The error message is absolutely horrible, but we first need to check the root cause of the issue. If you do not want to share the tenant name here, please share that using private messages in the Microsoft Tech Community and confirm that you shared it from there. Thanks for the additional details advance.

**Comment by anhvoduy** [comment]
![error](https://user-images.githubusercontent.com/21326032/61537906-76504600-aa62-11e9-829a-a1b2669787fe.png)

Error happens with me, in case (2) below:
- have a site app catalogs created from sp tenant in 4 years ago => deploy spfx-app01, it works success
- have a site app catalogs created from sp tenant recently => deploy spfx-app01, it's got error, but luckily, sharepoint page contains webpart (from spfx) still work success.
