### ISSUE TITLE
Issue regarding multi-geo support.

### ISSUE THREAD

**Issue by MarkyDeParky** [SharePoint/sp-dev-docs#3064]
If I'm correct, this isn't exactly true for multi-geo environments:

"Because there are no remote APIs for creating custom properties in the user profile service, this step must be performed manually for each of the tenants where custom user profile properties are needed (this only needs to be done once per tenant)."

In a multi-geo environment, you need to do this for each of your geo locations in your tenant.

Please correct me if I'm wrong or update the content to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0dffd-d314-6e01-be9a-f72d852227e3
* Version Independent ID: e48220e4-412d-aee0-ce37-86400efb6cc3
* Content: [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online)
* Content Source: [docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Correct, this would need to be done in each tenant for multi-geo.
