### ISSUE TITLE
GroupUserAdded,GroupUserDeleted are unreliable in SharePoint Online

### ISSUE THREAD

**Issue by winperec** [SharePoint/sp-dev-docs#3069]
#### Category
- [x] Bug

We are using Remote Event Receivers for events `GroupUserAdded` and `GroupUserDeleted` in SharePoint Online tenants and recently noticed strange behavior: They works for some time ~several hours then stop working, then after some time we can see them working again... 

#### Expected or Desired Behavior
Receivers should work well or it should be some way to get logs/traces about why them were not called.

#### Observed Behavior
So remote receivers for events `GroupUserAdded` and `GroupUserRemoved` are unreliable, 
Some period of time we can see requests in Application Insights. events come everything is alright.
Then after several hours we can't see it in Application Insights (the deployed code, of course, the same, nothing new deployed and no web app restarts). 
And there is no logs/traces what happened and how to deal with it. 

May be some throttling is applied or response from our backed is slow that after some time SharePoint is turned them off?

in SharePoint on-prem it is not recommended to register receivers for UserInfo list, may be this case is also related to this recommendation somehow?

#### Steps to Reproduce
Create SharePoint modern/classic site
Register event receivers using CSOM and PnP extension `Web.AddRemoteEventReceiver`
Monitor calls within several hours

**Comment by sylvainfraissenet** [comment]
Hi any update on this point ?
