### ISSUE TITLE
Technical Error

### ISSUE THREAD

**Issue by marcusgohsh** [SharePoint/sp-dev-docs#3071]
Hi,

I tried using the web part on Sharepoint 2019 page and received a technical error.

[SPLoaderError.loadComponentError]:
***Failed to load component "f499ce90-3e01-4360-b131-1c5862b444fe" (HelloWorldWebPart).
Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.7.0".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by pkbullock** [comment]
Hi Marcus

You need to use SPFX version 1.4.1 for SharePoint 2019. 

In Part one of the guide (assuming your following each part), Under the question in the generator "Which baseline packages do you want to target for your component(s)?" - did you select SharePoint 2019...?

Paul

**Comment by marcusgohsh** [comment]
Hi pkbullock,

Yes I selected Sharepoint 2019 baseline package.
I was able to view the webpart from localhost but not after deploying to another platform.

**Comment by patmill** [comment]
The fact that it says "1.7.0" indicates that somewhere along the way your package.json file was updated to point to the 1.7.0 packages.  You'll need to have them be 1.4.1.

Pat.

**Comment by marcusgohsh** [comment]
Hi Patmill,

Did npm uninstall @microsoft/generator-sharepoint and npm install @microsoft generator-sharepoint@1.4.1
Still reflects as 1.7.0, am I doing something wrong?

Thanks

**Comment by marcusgohsh** [comment]
Hi @VesaJuvonen , I have tried this method and it works during gulp serve, however, I'm unable to host to client-side and received this error, should I open another case instead? Please advice.

[SPLoaderError.loadComponentError]:
***Failed to load component "0f5db352-d360-406e-8aa1-38e3f25d6d8c" (HelloWorldWebPart).
Original error: ***Failed to load path dependency "HelloWorldWebPartStrings" from component "0f5db352-d360-406e-8aa1-38e3f25d6d8c" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/0f5db352-d360-406e-8aa1-38e3f25d6d8c_0.0.1/HelloWorldWebPartStrings
	https://component-id.invalid/0f5db352-d360-406e-8aa1-38e3f25d6d8c_0.0.1/HelloWorldWebPartStrings did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

**Comment by patmill** [comment]
2019 needs to use react 15, not 16.

Sent from Outlook
________________________________

**Comment by frnk01** [comment]
@patmill Ok, I guess I can manually downgrade, but then there is some kind of issue in 1.7.0, right?

**Comment by marcusgohsh** [comment]
i settled my issue. Thanks. Please close this case.

**Comment by jcschmidt31** [comment]
I recently created a new project (HelloWorld) for SharePoint 2019 or later using 1.7.1 and react projects error out in my SharePoint workbench.  They display properly in the local workbench but error out in the SharePoint workbench.  I see in the package-lock file that most of the react packages are listed as 15.6.2 but I'm also seeing a few listed as 16.3.2 so I think there may still be an issue.

**Comment by andrewconnell** [comment]
@frnk01 @jcschmidt31 This should have been flagged as a dupe issue as it's already being tracked... see #3145 as the dupe

**Comment by rogercodes1** [comment]
> Hi Marcus
> 
> You need to use SPFX version 1.4.1 for SharePoint 2019.
> 
> In Part one of the guide (assuming your following each part), Under the question in the generator "Which baseline packages do you want to target for your component(s)?" - did you select SharePoint 2019...?
> 
> Paul

How do I upgrade/update it to that version?

**Comment by VesaJuvonen** [comment]
@rogercodes1  - closed issues are closed issues, so not recommended to add questions and comments in these. In short - install latest SharePoint Framework version and choose SP2019 as your target environment when getting asked about that - that will create the solution structure with the right setup for SP2019.

Locking the issue to avoid further comments on this. If there's any other questions, please open a new issue, so your question does not get buried on old issues.
