### ISSUE TITLE
SPFx webpart development issue in MS Teams

### ISSUE THREAD

**Issue by himanshuchuriwala** [SharePoint/sp-dev-docs#3073]
SPFx webpart for MS Teams
- [Cannot find module '@microsoft/sp-build-web' error ] Question

While developing spfx solution for ms teams, I am receiving error related to sp-build-web module. I followed the msdn article but still the issue is bothering.

I tried to install the dependencies but still no luck.

**Comment by patmill** [comment]
Can you add a bit more here?  Where do you get the error, when you run npm install?  How did you get your solution code?  (I assume running the 1.7 sharepoint yeoman generator with the --plusbeta flag), etc.  What does your package.json file look like?

**Comment by himanshuchuriwala** [comment]
When i run gulp  bundle --ship, i get error Cannot find module '@microsoft/sp-build-web' error. i checked the packages under node_modules , and it was existing.

is the code sample present at https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md specific to node and npm versions ?

**Comment by VesaJuvonen** [comment]
@himanshuchuriwala - that tutorial is dependent on the same matching versions as SPFx in general and you should be using Node v8.x and npm v5.x. Can you confirm your environment details around the versions? Thx.

**Comment by himanshuchuriwala** [comment]
I did install the correct versions and worked for me !! thnx
