### ISSUE TITLE
Not able to format Rich Text Fields in View Formatting; output comes as HTML

### ISSUE THREAD

**Issue by rahulbabarit** [SharePoint/sp-dev-docs#3075]
Hi,

Just wanted to confirm if we will be able to use Rich/Enhanced rich text fields in SharePoint Online view formatting. When I tried to do that, it comes out as plain HTML.

Appreciate your help.

Thanks,
Rahul Babar

**Comment by Seiyasu** [comment]
JSON format for Column Formatting and View Formatting should be just for simple scence. For rich text fields and so on, you need to use the SPFx Field Customizer.
