### ISSUE TITLE
Dynamic Data Page Environment double Query String entry

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#3078]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When polling the properties of the Page Environment Dynamic Source, the UserData property definition should have a title of User Data

#### Observed Behavior

When pulling from the Page Environment Dynamic Source there are 3 property definitions that get returned:
```json
[
  {
    id: "SiteData",
    title: "Site properties"
  },
  {
    id: "UserData",
    title: "Query string"
  },
  {
    id: "UrlData",
    title: "Query string"
  }
]
```

Looks like the title of the 2nd one (UserData) is incorrect - at least in en-us.

#### Steps to Reproduce

Get the property definitions for the Page Environment source and check out the title entries. I'm seeing this in both the local and online workbench.

**Comment by patmill** [comment]
Oh, that's embarrassing.  Yup - The UserData property title should be "Current user information".  Thanks for the heads up.  We'll get that fixed.

**Comment by thechriskent** [comment]
This is fixed. Thanks!
