### ISSUE TITLE
SPFx app loads random versions when it has been upgraded multiple times

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#3079]
We are creating updated versions of SPFx components and testing them in tenant app catalogs. We find that the versions of SPFx extension is randomly loading older version extension properties or javascripts

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Observed Behavior

When we update the version of the SPPKG app from **package-solution.json** we sometimes see older version of extension JS loaded

Page some times load older version JS and sometime it loads newer version JS. Atleast 1 out of each 5 refresh you see older version of JS is loaded.

#### Steps to Reproduce

1. Create a new SPFx extension and deploy it to the tenant app catalog
2. Add the app to your site collection
3. Change the "version": "x.x.x.x" to new higher number in package-solution.json file
4. Build the bundle and package and deploy to the tenant app catalog
5. upgrade app in your site content
6. Refresh any of the page in site multiple times 

#### Expected or Desired Behavior

The page must always load the extension JS version as mentioned in package-solution.json and not randomly

**Comment by nikskhubani** [comment]
@VesaJuvonen we also tried to create tickets with Microsoft Level 1 but since this is kind of product level issue they said they cant help on it so I have to come back here. 

I have been asking about this issue since almost 2-3 months in below tickets but this issue is still reproducible easily

https://github.com/SharePoint/sp-dev-docs/issues/2600
https://github.com/SharePoint/sp-dev-docs/issues/2329

**Comment by nikskhubani** [comment]
Thank you @patmill for quick response

Here are the answers please:

1. So, have you also installed the extension in a site-collection app catalog?
No, simply added app first time to tenant app catalog and then upgraded that app with newer version
2. Does the js file name change from build-to-build?
No, We made sure it remains same always (**_short-point-custom-actions-application-customizer.js_**)
3. Where is your js script being loaded from?
Amazon CDN 

so from your comments, it looks like having same file name each time is causing the issue? However the URL of the entire JS is different as shown below

"cdnBasePath":"https://<path to our hostname>/spfx/**<version which changes every time for example 6.0.2.2>**/spfx/deploy/"

so should it not be enough to make sure the URL is unique and it should not load from cache?

**Comment by patmill** [comment]
What is the full path to your js file?  That's all the browser is going to care about.  In general it's not a great idea to keep the file name the same, as it can result in issues like this.

**Comment by nikskhubani** [comment]
Here is an example of the extension URL
https://d2zzvnmppezkx.cloudfront.net/spfx/6.2.0.20/spfx/deploy/short-point-custom-actions-application-customizer.js
so sometimes it loads older version like
https://d2zzvnmppezkx.cloudfront.net/spfx/**_6.2.0.16_**/spfx/deploy/short-point-custom-actions-application-customizer.js
or 
https://d2zzvnmppezkx.cloudfront.net/spfx/**_6.2.0.17_**/spfx/deploy/short-point-custom-actions-application-customizer.js

See this animation, sorry its a big long because its random issue. Now in the animation below you will see that till the end the extension is loaded from 6.2.0.15 version while the installed version is NOT 6.2.0.15, its 6.2.0.20. If you see towards end of this animation (nearly after 2 minutes and 10 seconds), the extension is loaded from 6.2.0.20 version which is correct version. 

All I am doing in below animation is refresh page!

![old extension loading](https://user-images.githubusercontent.com/29400321/49600275-486b3500-f99c-11e8-9a24-605e84640629.gif)

**Comment by nikskhubani** [comment]
Here you go

`{
  "extensionType": 2,
  "version": "0.0.1",
  "alias": "ShortPointCustomActionsApplicationCustom",
  "loaderConfig": {
    "internalModuleBaseUrls": [
      "https://d2zzvnmppezkx.cloudfront.net/spfx/6.2.0.20/spfx/deploy/"
    ],
    "entryModuleId": "short-point-custom-actions-application-customizer",
    "scriptResources": {
      "short-point-custom-actions-application-customizer": {
        "type": "path",
        "path": "short-point-custom-actions-application-customizer.js"
      },
      "@microsoft/sp-core-library": {
        "type": "component",
        "id": "7263c7d0-1d6a-45ec-8d85-d4d1d234171b",
        "version": "1.4.1"
      },
      "@microsoft/sp-loader": {
        "type": "component",
        "id": "1c6c9123-7aac-41f3-a376-3caea41ed83f",
        "version": "1.4.1"
      },
      "@microsoft/sp-http": {
        "type": "component",
        "id": "c07208f0-ea3b-4c1a-9965-ac1b825211a6",
        "version": "1.4.1"
      },
      "@microsoft/decorators": {
        "type": "component",
        "id": "f97266fb-ccb7-430e-9384-4124d05295d3",
        "version": "1.4.1"
      },
      "@microsoft/sp-application-base": {
        "type": "component",
        "id": "4df9bb86-ab0a-4aab-ab5f-48bf167048fb",
        "version": "1.4.1"
      }
    }
  },
  "manifestVersion": 2,
  "id": "f5673854-e363-428c-8ab4-5095faec34db",
  "componentType": "Extension"
}`

**Comment by patmill** [comment]
Just to confirm again - on a page that loads the wrong version, the manifest points to the right one?

If that is the case, when you look at the normal developer tools in the browser and find the network call to load the incorrect js version, what does the callstack of the call look like?

**Comment by patmill** [comment]
OK, that's really really weird.  Should the version #s have changed between those two manifests?  Ie, they currently both say "version": "0.0.1", "alias": "ShortPointCustomActionsApplicationCustom"

A couple of other things to look at.  Is there any chance that you have multiple solutions uploaded to the apps list?  If you go to the component manifest lists ( /sites/{appcatalogname}/Lists/ComponentManifests/ ) do you see multiple entries for your component ID "f5673854-e363-428c-8ab4-5095faec34db" ?


If you feel comfortable, you can mail me at my account @ microsoft.com with a debug account and we can try looking in further.

**Comment by nikskhubani** [comment]
Yes, Yes, Yes!

I see two extension entries in given component manifests list.  Do you see this is the issue? 

![](https://content.screencast.com/users/AshaKhubani/folders/Jing/media/225bb88a-de99-4cd9-a445-ec80b2d16bc3/2018-12-07_1116.png)

**Comment by patmill** [comment]
Well, it's certainly not correct.  OK, next step.  In that same table, there should be a column (maybe not displayed by default, but you can add it) that states the solution that the component came from.  Hopefully they are different IDs.  Next, check and see what else is referencing that solution (you should be able to filter the component manifest list on that solution).  Make sure that it's OK to delete those, because that's what we're going to do.  Next, go to the solution library (the one you upload your packages to) and find the one that the 6.2.0.15 solution pointed to.  Delete it.  That should remove the entries from the client side component manifests.

**Comment by nikskhubani** [comment]
Just to summarize, you are asking to remove these entries right?

![](https://content.screencast.com/users/AshaKhubani/folders/Jing/media/2a825b86-9e85-471c-ba83-9691bf6d4775/2018-12-07_2321.png)

So all 4 entries belong to our SPFx package and the highlighted ones are of older apps which I believe should not be there.

Now the second point of yours, solution library has only 1 solution which is latest (6.2.0.20) as the steps we followed is:

1. First created a version called 6.2.0.17
2. added to app catalog and site
3. all working
4. Now, we have some changes so we created a new package with same code but version changed to 6.2.0.20

![](https://content.screencast.com/users/AshaKhubani/folders/Jing/media/6ba1cf76-314e-45d2-bc64-d54b365be050/2018-12-07_2328.png)

5. Uploaded the package again to app catalog, now it will ask you to overwrite since there is already 6.1.0.17 installed. So overwrite and deploy.

That's it. So solution gallery would have only 1 app.

**Comment by patmill** [comment]
OK, took a look at the solution you sent me and checked out the tenant.  The biggest issue is that your package is weird.  Really really weird.  You have multiple instances of the same components in it, as well as mixing older SharePoint Add-in and SPFx solutions in the same package.  How did you wind up with this package?

So, bug in our code to not flat out fail to process your package, but the solution for you will be to create a clean package.  SharePoint add-ins need to be separate from SPFX solutions, and your spfx solution should only have 1 copy of each component in it.

**Comment by coreyroth** [comment]
Ok, so I am absolutely having this same issue.  It used to only affect one tenant and now it's affecting others.  I've been chasing this issue for weeks and I have an open ticket with Premier #12352688.  I'll check the steps in this article in detail to see how mine compare.

**Comment by nikskhubani** [comment]
There were few mail chain between @patmill and myself, so happy to help you if above doesnt help. Just mail me at nitin@shortpoint.com

**Comment by bostonmusicdave** [comment]
@coreyroth we had the same issue when using site collection app catalogs and found that old versions seemed to exist in the recycle bin each time i'd upgraded the solution in the site collection app catalog.  It's worth checking the recycle bin to see if you see old versions in there and try clearing them out
