### ISSUE TITLE
Problem when deploying assets to sharepoint app 

### ISSUE THREAD

**Issue by zbart3i** [SharePoint/sp-dev-docs#3084]
I'm trying to deploy assets to my sharepoint Site, but it always says something went wrong during the app setup
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

i've made two XML File: one for elements and the other for the schema.

Elements.xml:
`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
   <Field ID="{a3596ed5-625b-4bf4-abf5-37be33dfcaa6}"
      Name="LBP_Fields_Communication_Date"
      DisplayName="Date"
      Type="DateTime"
      Required="FALSE"
      Group="LBP_CDR" />
   <Field ID="{2f7d98b9-05d0-4521-97fc-e0e8e7e60c37}"
      Name="LBP_Fields_Communication_OrdreDuJour"
      DisplayName="Ordre du jour"
      Type="Text"
      Required="FALSE"
      Group="LBP_CDR" />
   <Field ID="{64870503-038a-4eb1-b14e-238897571521}"
      Name="LBP_Fields_Communication_Presentateur"
      DisplayName="Présentateur"
      Type="User"
      Required="FALSE"
      Group="LBP_CDR" />
   <Field ID="{7e5babbf-9e6f-4006-aac0-685904c588a7}"
      Name="LBP_Fields_Communication_Categorie"
      DisplayName="Catégorie"
      Type="Choice"
      Required="FALSE"
      Group="LBP_CDR">
      <CHOICES>
         <CHOICE>ComCA</CHOICE>
         <CHOICE>ComTR</CHOICE>
      </CHOICES>
   </Field>
   <ContentType ID="0x010042D0C1C200A14B6887742B6344675C20"
      Name="Communication"
      Group="LBP_CDR"
      Description="Type de contenu Communication">
      <FieldRefs>
         <FieldRef ID="{a3596ed5-625b-4bf4-abf5-37be33dfcaa6}" />
         <FieldRef ID="{2f7d98b9-05d0-4521-97fc-e0e8e7e60c37}" />
         <FieldRef ID="{64870503-038a-4eb1-b14e-238897571521}" />
         <FieldRef ID="{7e5babbf-9e6f-4006-aac0-685904c588a7}" />
      </FieldRefs>
   </ContentType>
   <ListInstance
      CustomSchema="CommunicationSchema.xml"
      FeatureId="00bfea71-de22-43b2-a848-c05709900100"
      Title="Communication"
      Description="Liste Communication"
      TemplateType="100"
      Url="Lists/Communication">
   </ListInstance>
</Elements>
`
and this is my Schema.xml

`<List xmlns:ows="Microsoft SharePoint" Title="Communication" EnableContentTypes="TRUE" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Communication" BaseType="0" xmlns="http://schemas.microsoft.com/sharepoint/">
  <MetaData>
    <ContentTypes>
      <ContentType Name="Communication" ID="0x010042D0C1C200A14B6887742B6344675C20" Group="LBP_CDR" Inherits="FALSE">
        <FieldRefs>
          <FieldRef ID="{a3596ed5-625b-4bf4-abf5-37be33dfcaa6}" />
          <FieldRef ID="{2f7d98b9-05d0-4521-97fc-e0e8e7e60c37}" />
          <FieldRef ID="{64870503-038a-4eb1-b14e-238897571521}" />
          <FieldRef ID="{7e5babbf-9e6f-4006-aac0-685904c588a7}" />
        </FieldRefs>
      </ContentType>
    </ContentTypes>
    <Fields/>
    <Views>
      <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/images/generic.png" Url="AllItems.aspx">
        <XslLink Default="TRUE">main.xsl</XslLink>
        <JSLink>clienttemplates.js</JSLink>
        <RowLimit Paged="TRUE">30</RowLimit>
        <Toolbar Type="Standard" />
        <ViewFields>
          <FieldRef Name="LBP_Fields_Communication_Date"/>
          <FieldRef Name="LBP_Fields_Communication_OrdreDuJour"/>
          <FieldRef Name="LBP_Fields_Communication_Presentateur"/>
          <FieldRef Name="LBP_Fields_Communication_Categorie"/>
        </ViewFields>
        <Query>
          <OrderBy>
            <FieldRef Name="ID" />
          </OrderBy>
        </Query>
      </View>
    </Views>
    <Forms>
      <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages/Communication/form.aspx" WebPartZoneID="Main" />
      <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages/Communication/form.aspx" WebPartZoneID="Main" />
      <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages/Communication/form.aspx" WebPartZoneID="Main" />
    </Forms>
  </MetaData>
</List>`

Deplying the content types Works fine, but the problem happens when i try to deploy it with a list.

here is my package-solution.json file: 

```

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "lbp-cdr-client-side-solution",
    "id": "******-3a***-***-ae1d-e0f94a9c52f8",
    "version": "1.0.0.3",
    "includeClientSideAssets": true,
    "features": [{
      "title": "ContentTypes-Lists-lp-cdr-client-side-solution",
      "description": "ContentTypes-Lists-lp-cdr-client-side-solution",
      "id": "f715b3dc-1c44-40ed-90c4-1fd39c6cc5fd",
      "version": "1.0.0.0",
      "assets": {
        "elementManifests": [
          "Communication/CommunicationElements.xml"
         
        ],
        "elementFiles": [
          "Communication/CommunicationSchema.xml"
        ]
        
      }
    }]
  },
  "paths": {
    "zippedPackage": "solution/lbp-cdr.sppkg"
  }
}
`
Please advise thank you,

**Comment by patmill** [comment]
If you add the "error" field to the app catalog view, what is the error listed?

**Comment by zbart3i** [comment]
The App Package Error Message displays no error

**Comment by andrewconnell** [comment]
*These are very hard to troubleshoot...*

You said the field deployed just fine, so you can see in the list of site columns? What happens when you add the column to a list using the web UI? Does that work ok?

In the `<ListInstance CustomSchema="">` property, you say the file is named `CustomSchema.xml` but in the issue you say the file is `schema.xml`... name mismatch.
