### ISSUE TITLE
[LOC] Multiple links goes to 404 error page (migration-api-overview.md)

### ISSUE THREAD

**Issue by OfficeGSX** [SharePoint/sp-dev-docs#3085]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview (or GH: https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/migration-api-overview.md)
2. Search for links listed below
3. Click the link --> 404 error page

**List of affected links**

Link Text | Link URL
-- | --
So you want to   programmatically provision personal sites in OneDrive for Business in Office   365 | http://blogs.msdn.com/b/frank_marasco/archive/2014/03/25/so-you-want-to-programmatically-provision-personal-sites-one-drive-for-business-in-office-365.aspx
Restrictions and limitations   when you sync SharePoint libraries to your computer through OneDrive for   Business | http://support.microsoft.com/kb/2933738

![image](https://user-images.githubusercontent.com/16706698/49731310-2fec6a80-fc7b-11e8-8433-744d22c5e8cc.png)

**Comment by Seiyasu** [comment]
Fix, waiting for merging.
