### ISSUE TITLE
Problem making 3rd party API calls using SPFx

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-docs#3086]
#### Category
- [x] Question

#### Expected or Desired Behavior
Hey, I was able to make Slack API calls using the class way (CEWP) plus jQuery and $.ajax.
Now I'm trying to learn SPFx and figure out how to make REST calls to 3rd party apis but I'm getting the error below. 

#### Observed Behavior

> Access to fetch at 'https://slack.com/api/users.list?token=<MYTOKEN>&channel=<MYCHANNEL>' from origin 'https://localhost:4321' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

On the Left side I have my webpart running in the Local workbench, the Right side is the classic example
![image](https://user-images.githubusercontent.com/5871660/49756225-a20a8280-fc6e-11e8-8885-3832e0484351.png)

This is my code: 

![image](https://user-images.githubusercontent.com/5871660/49756334-c2d2d800-fc6e-11e8-8069-c71be4056253.png)

```
    private makeRequest(): Promise<HttpClientResponse> {
        const token =
            "";
        const channel = "";

        const url = `https://slack.com/api/users.list?token=${token}&channel=${channel}`;

        const requestHeaders: Headers = new Headers();

        requestHeaders.append("Content-type", "application/json");
        requestHeaders.append("accept", "application/json");

        const httpClientOptions: IHttpClientOptions = {
            headers: requestHeaders,
            method: "GET"
        };

        return this.context.httpClient
            .get(url, HttpClient.configurations.v1, httpClientOptions)
            .then(response => {
                console.log(response);
                return response.json();
            });
    }
```
Any help would be appreciated.

**Comment by patmill** [comment]
As a first step in diagnosing, what happens when you run this from the hosted workbench?  With gulp serve running, just navigate to https://yourtenant.sharepoint.com/_layouts/15/workbench.aspx

**Comment by simkessy** [comment]
Hey @patmill the same error occurs

**Comment by simkessy** [comment]
The screenshot of the network traces as is the current status. I've added the latest code to the OP where it uses `GET`.

**Comment by patmill** [comment]
So, the next difference is that you are setting the content type in modern, but not in classic (and that content type is saying it's violating the CORS rules).

Can you start from a point where the requests headers / etc. are the same?

**Comment by bcameron1231** [comment]
Agreed with @patmill . Setting the content-type in the header is forcing the pre-flight options request. Which means the response from Slack would have to return the access-control-allow-headers response header containing this content type -- This isn't a part of the slack response, so you'd get this CORS error.

**Comment by simkessy** [comment]
You're both correct in that setting the header was causing the problem. However, when I try to make a post request like this: 

       const url = `https://slack.com/api/chat.postMessage?token=${
            this.token
        }&channel=${this.channel}`;

        const body = JSON.stringify({
            token: this.token,
            channel: channel,
            text: msg
        });

        const requestHeaders: Headers = new Headers();
        // requestHeaders.append("Content-type", "application/json");
        // //For an OAuth token
        // requestHeaders.append("Authorization", `Bearer ${this.token}`);

        const httpClientOptions: IHttpClientOptions = {
            headers: requestHeaders,
            mode: "cors",
            body: body
        };

        await this.context.httpClient
            .post(url, HttpClient.configurations.v1, httpClientOptions)
            .then(response => {
                console.log(response);
                return response.json();
            });

I get: 
![image](https://user-images.githubusercontent.com/5871660/49793634-8d6bd000-fcea-11e8-8cbb-3b99245415d4.png)

![image](https://user-images.githubusercontent.com/5871660/49793411-00c11200-fcea-11e8-8ec3-dd8c975b355a.png)

Then I look at Slacks docs and they say I need to set headers with my request: https://api.slack.com/changelog/2017-10-keeping-up-with-the-jsons

Soo I'm a bit lost here. I can get it working with Axios (which is a XHR request, not using Fetch.api like HttpcClient): 

        axios({
            method: "post",
            url: "https://slack.com/api/chat.postMessage",
            params: {
                token: this.token,
                channel: channel,
                text: msg
            },
            transformRequest: [
                (data, headers) => {
                    delete headers.post["Content-Type"];
                    return data;
                }
            ]
        });

**Comment by bcameron1231** [comment]
1. You may want to be careful posting your token in a public space like this... it will allow others to now post messages to your slack.

2.  I would double check with Slack to make sure that endpoint really does allow JSON. Because it seems to always fail when specifying the content type application/json.

3. I have confirmed if you use application/x-www-form-urlencoded and pass the values for token, channel and message over the query string (much like Axios does), everything will work as expected.

**Comment by bcameron1231** [comment]
Well I'm glad you got it worked out!

**Comment by patmill** [comment]
Out of curiosity - does this help simplify your code (and work)?
```
private async postToChannel(msg = "Testing API", channel = this.channel) {
      const url = `https://slack.com/api/chat.postMessage?token=${
          this.token
      }&channel=${this.channel}&text=${msg + " using HttpClient"}`;


    return await this.context.httpClient.post(
        url,
        HttpClient.configurations.v1,
        {
          mode:"cors",
          headers:{
            "Content-Type":"application/x-www-form-urlencoded"
          }
        }
    );
}
```

**Comment by simkessy** [comment]
Yea, that is way cleaner. Thanks!
