### ISSUE TITLE
cmdlet add-spositescript 

### ISSUE THREAD

**Issue by umaknow-alain** [SharePoint/sp-dev-docs#3087]
Hi this this cmdlet is no longer working. I have a very small site scrip to test the cmdlet. I am using the following line to add the script 

$siteScript = (Get-Content $siteScriptFile -Raw | Add-SPOSiteScript -Title $siteScriptTitle) | Select -First 1 Id

(the $siteScriptFile is loaded with this line)
$siteScriptFile =  "C:\Users\xxxx\xxxx\provisioning\department2-site.json"

But when i run the add-spositescript i get this error code 

Add-SPOSiteScript : Specified argument was out of the range of valid values.
At line:1 char:1
+ Add-SPOSiteScript -Content $siteScript -Title $siteScriptTitle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-SPOSiteScript], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.AddSPOSiteScript

Site script:
{
    "$schema": "schema.json",
        "actions": [
            {
                "verb": "createSPList",
                "listName": "Customer Tracking",
                "templateType": 100,
                "subactions": [
                    {
                        "verb": "SetDescription",
                        "description": "List of Customers and Orders"
                    },
                    {
                        "verb": "addSPField",
                        "fieldType": "Text",
                        "displayName": "Customer Name",
                        "isRequired": false,
                        "addToDefaultView": true
                    }
                ]
            }
    ],
    "bindata": {},
    "version": 1
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by umaknow-alain** [comment]
We found that the limit of a 100 site design / script was creating the error. Deleting all unnecessary design solve our problem.

**Comment by seansquires** [comment]
Ack - thanks for updating. I was logging on to write that we couldn't repo ;)
