### ISSUE TITLE
sp-field-customFormatBackground

### ISSUE THREAD

**Issue by spcrux** [SharePoint/sp-dev-docs#3089]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there more information on how to sp-field-customFormatBackground? It's not really clear how to use this class.

**Comment by Seiyasu** [comment]
Basic demos:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "div",
  "txtContent": "@currentField",
  "attributes": {
    "class": "sp-field-customFormatBackground"
  },
  "style": {
    "color": "red"
  }
}
```
You can try other properties of the background too:  https://www.w3schools.com/css/css_background.asp

**Comment by spcrux** [comment]
Hi Seiyasu,
Could you please show an example of how this "Specifies the padding and margins for all classes that use backgrounds" as per documentation at https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#style-guidelines
