### ISSUE TITLE
Visual Studio 2017 Office Development

### ISSUE THREAD

**Issue by benpolinsky** [SharePoint/sp-dev-docs#3098]
For VS 2017, installing the Microsoft Office Developer Tools should be done through the Visual Studio 2017 Installer, which can be accessed from the New Project window. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7795f659-9cc4-310b-1ea6-9842a6a2930a
* Version Independent ID: cfc98572-f913-6f48-cfe4-1b9dd526d7fc
* Content: [Get started creating SharePoint-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Thanks for post, have added it to the docs.
