### ISSUE TITLE
Garbled code snippet in documentation on replacing client secrets

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#3099]
#### Category
- [ ] Question
- [X] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

The [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in) page contains a garbled code snippet in item 3 of the second section. There are two lines that are shown as unformatted text, outside of any code box, the code is split across multiple code boxes, and the last code box extends beyond the end of the code, consuming the next bullet and header.

Screenshot:
![image](https://user-images.githubusercontent.com/6964029/49885291-2da42f00-fe7a-11e8-99de-634fcb61c8b2.png)

I would try submitting a change to fix this, but given that this appears to be due to an issue in the way docs.microsoft.com renders the markdown, I'm not sure whether the issue is occuring due to the lack of leading indentation (other code on the page is indented by 4 spaces while this snippet has no indent), or whether it is due to the empty lines in the code. Since I don't have any way of verifying that any change I made would fix the formatting issue, I am submitting this as an Issue instead.

**Comment by patmill** [comment]
I've tried a few things, to no avail.  We'll need to bring this up with the team running the doc site.  @VesaJuvonen as an FYI.

**Comment by andrewconnell** [comment]
Just submitted a PR to address this... the code snippet was incorrectly formatted in the markdown.

**Comment by JLRishe** [comment]
@andrewconnell Thanks! For future reference, was the issue that the code snippets need to be indented by at least two spaces?

**Comment by andrewconnell** [comment]
@JLRishe  You can see my edits in the commit above. 

The formatting didn't line up within the code block. The opening code snippet was indented, but part was then left-aligned to the gutter with no indentation. That's invalid markdown for a code snippet... I have to assume that was the issue as I can't see the preview rendering.
