### ISSUE TITLE
Cannot find module \node_modules\@microsoft\npmx\lib\gulp2vs.js

### ISSUE THREAD

**Issue by tom-daly** [SharePoint/sp-dev-docs#31]
loading the .njsproj in VS2015. I'm unable to build because missing a file. 

![2016-08-19_15-27-39](https://cloud.githubusercontent.com/assets/9259305/17821794/7d7c9bf0-6621-11e6-914e-b73fc1194ef6.jpg)

**Comment by pgonzal** [comment]
This is a known issue.  The gulp2vs.js script has been moved to another package, which we are still working on releasing.  Until then, could you try manually editing your .njsproj file to replace this line:

```xml
    <Exec Command="CMD.EXE /c node $(MSBuildThisFileDirectory)\node_modules\@microsoft\npmx\lib\gulp2vs.js" />
```

...with this:

```xml
    <Exec Command="CMD.EXE /c node $(MSBuildThisFileDirectory)\node_modules\gulp\bin\gulp.js bundle" />
```

Let me know if that works...

@mousetraps

**Comment by tom-daly** [comment]
That works - didn't see that in known issues or on the VS page. It's building now.

**Comment by pgonzal** [comment]
FYI we have publicly released @microsoft/npmx, and in the next framework update the Yeoman template will refer to it like this:

```xml
    <Exec Command="CMD.EXE /c node $(MSBuildThisFileDirectory)\node_modules\@microsoft\npmx-lib\lib\gulp2vs.js" />
```

If you want to use this feature, you will need to manually run "npm install @microsoft/npmx-lib".
