### ISSUE TITLE
error when exec "gulp trust-dev-cert"

### ISSUE THREAD

**Issue by foxdave** [SharePoint/sp-dev-docs#310]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
I followed the [guide](https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part) to build a webpart, and can not exec "gulp trust-dev-cert" correctly.

I don't know why, I haven't learn this since November, and it didn't include the function earlier.
Please advice.
![2016_12_13_13_59_39_new_issue_sharepoint_sp_dev_docs](https://cloud.githubusercontent.com/assets/7928690/21129491/c8b5ee34-c13c-11e6-980b-f4987b47d6b5.png)

**Comment by chakkaradeep** [comment]
It looks like you may be trying it an existing project with an older build, can you try to upgrade your project to the [latest drop](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-6#updating-your-existing-projects) and then run the command?

**Comment by dcu-sharepoint** [comment]
I had the same problem and what I found out was that the error message was misleading and the real problem was an access denied issue.

I normally work with a **non-privileged account** so what I did was to include the account in the administrators group, re-logged back into the account, re-run the **gulp trust-dev-cert** and voila, the cert command worked.

I hope this helps.

**Comment by patmill** [comment]
I haven't seen any other comments on this.  Marking as closed for now.  Feel free to reopen or create a new issue,

**Comment by surajit09** [comment]
I faced the same issue. I removed yoman and sharepoint  generator modules and then installed these modules again. Now I can see trust-dev-certs task

**Comment by must19** [comment]
Same error, run the command as Admin solved the problem
