### ISSUE TITLE
Replace an Expiring Client Secret without Admin Rights?

### ISSUE THREAD

**Issue by fowl2** [SharePoint/sp-dev-docs#3104]
'AppRegNew.aspx' allows creation of new service principals with only site collection administrator rights, but the secrets it generates are only valid for one year, but these steps require AAD directory admin rights to perform.

Is there any way of renewing secrets with the same level of access they were created with? Otherwise AppRegNew seems like a bit a of a timebomb waiting to happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
There's, unfortunately, no other way to renew the principals and that does indeed require AAD directory admin rights to perform. This is unfortunately by design or result of badly design capability from permission level perspective, but there are currently no plans to change this.
