### ISSUE TITLE
Issue Hosting webpart to client side

### ISSUE THREAD

**Issue by marcusgohsh** [SharePoint/sp-dev-docs#3106]
Hi All,

This is the issue I am currently facing.

[SPLoaderError.loadComponentError]:
***Failed to load component "0f5db352-d360-406e-8aa1-38e3f25d6d8c" (HelloWorldWebPart).
Original error: ***Failed to load path dependency "HelloWorldWebPartStrings" from component "0f5db352-d360-406e-8aa1-38e3f25d6d8c" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/0f5db352-d360-406e-8aa1-38e3f25d6d8c_0.0.1/HelloWorldWebPartStrings
	https://component-id.invalid/0f5db352-d360-406e-8aa1-38e3f25d6d8c_0.0.1/HelloWorldWebPartStrings did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

Please advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you provide more details on what you're doing? Hard to troubleshoot from what you've provided.
