### ISSUE TITLE
SPFx - Microsoft teams web part not work on desktop app

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-docs#3107]
Hi there,

I created a MS teams web part which requests to custom APIs and they are trusted in API Managements in SP admin center.

I added in as a tab in MS teams ==> Its working fine on web but not on desktop app (keep loading forever).
Is this a known issue of SPFx v1.7 or I need some configurations to get this work?

Thanks in advance.

**Comment by patmill** [comment]
Yes - known issue around auth that we are working on.  There are some workarounds you can try (I think adding a PowerBI tab, authenticating, then cancelling out of the tab, then navigating to the SPFX tab), but the easiest thing (from a developer standpoint) is to stick with the web app for now.

**Comment by Ashish1662** [comment]
Hi All,

I am facing exactly same issue, following the same design (calling AAD protected endpoint using AadHttpClient). It works well as a web page but loads infinitely.

Is there any progress made in the meantime or if there is any better workaround available?

Thanks in advance.

**Comment by honb** [comment]
@Ashish1662 I haven't checked SPFx 1.8 yet, but look likes its still not work
