### ISSUE TITLE
Documentation ???

### ISSUE THREAD

**Issue by moumst** [SharePoint/sp-dev-docs#3111]
When do you think to update your docs.* documentation ??? This is just bullshit! Even going to msdn.microsoft.com where the documentation seems to be up to date, clicking a link on msdn take us back to docs.* where sharepoint documentation is nothing.

A shame!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b18aec9-66bc-e109-ad55-a320567b549e
* Version Independent ID: 91974a33-911a-042c-74ea-92a22e886e41
* Content: [SPList Class (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.splist?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPList.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPList.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Care to provide a specific point where the content is outdated? You realize you commented on a doc from 2013... there isn't an update there. You can see the docs are constantly being updated as the repo that contains the docs is quite active: [/SharePoint/sp-dev-docs/commits/master](https://github.com/SharePoint/sp-dev-docs/commits/master). 

If you have something specific to point to that's outdated, please provide specific link/reference. SharePoint is a *huge* product and maintaining the docs is a big task and things occasionally slip through the cracks, but we're all working hard to get things fixed when provided visibility.

All SharePoint docs have migrated from MSDN => docs.microsoft.com for SharePoint.
