### ISSUE TITLE
After calling the Powershell script, the guid returned is null

### ISSUE THREAD

**Issue by kingfu** [SharePoint/sp-dev-docs#3113]
Value is 00000000-0000-0000-0000-00000000000.  Something tells me this is not correct.  What are my options from this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0dffd-d314-6e01-be9a-f72d852227e3
* Version Independent ID: e48220e4-412d-aee0-ce37-86400efb6cc3
* Content: [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#create-and-upload-json-file)
* Content Source: [docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ToddKlindt** [comment]
Is this before or after you call the $context.ExecuteQuery() ? My experience is that $workItemId.Value is 0s before that and it is populated after that.

**Comment by andrewconnell** [comment]
Closing due to no response from OP
