### ISSUE TITLE
Enable preview capabilities in existing project

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#3114]
Is it possible to enable preview features in existing project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc2714f-5868-1d4f-b2d8-47eabc3247d7
* Version Independent ID: 45ef4bed-492f-136f-a842-7aeeb75c7ce2
* Content: [Try SharePoint Framework preview capabilities](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/try-preview-capabilities)
* Content Source: [docs/spfx/try-preview-capabilities.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/try-preview-capabilities.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Yes.  Just update your package.json to point to the preview packages (they look like 1.7.0-plusbeta or 1.5.1-plusbeta) and then run npm install .

**Comment by aslanovsergey** [comment]
Thanks!
