### ISSUE TITLE
Retrieving default Site Design ID

### ISSUE THREAD

**Issue by qazqwertish** [SharePoint/sp-dev-docs#3115]
Is there a way to retrieve the IDs of the default site designs? We want to change the site design of an existing site back to the "Topic" one, but in order to do it the PowerShell command needs its ID. 

There is "Get-SPOSiteDesignRun" but it is still in experimental (Get-SPOSiteDesignRun : The requested operation is part of an experimental feature that is not supported in the current environment.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a043553-262f-f8ae-7058-6fa1318b8369
* Version Independent ID: 3282aff6-9e90-3cac-37a9-b44d499e7172
* Content: [SharePoint site design - PowerShell cmdlets](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-powershell)
* Content Source: [docs/declarative-customization/site-design-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-powershell.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like you can retrieve details for all designs using the REST API's [GetSiteDesigns](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-rest-api#getsitedesigns) or the POSH Cmdlet [Get-SPOSiteDesign](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Get-SPOSiteDesign?view=sharepoint-ps)

**Comment by qazqwertish** [comment]
Those commands give only the custom Site Designs, but not the OOB ones like Topic or Blank
