### ISSUE TITLE
FieldCustomizer event.userData is cleared between onRenderCell calls

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3117]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`event.userData` during next `onRenderCell` call for the SAME cell contains data that was set by a developer.
#### Observed Behavior

`event.userData` is `undefined`.

#### Steps to Reproduce

1. Create some list and column in it
2. Add single list item
3. In Field Customizer in `onRenderCell` add something like:
```typescript
if (!event.userData) {
  console.log('userData is undefined');
  event.userData = {
    counter: 1
  };
}
else {
  console.log(event.userData.counter++);
}
```
4. Add SPFx app to the site and apply Field Customizer to the list column.
5. Open browser console and try to refresh page. First `onRenderCell` call is done, `event.userData` is initialized.
6. select an item
7. `onRenderCell` called again, `event.userData` is undefined

I also checked that the cell has not been disposed between these two calls of `onRenderCell`.

Additionally, and inconsistently, sometimes I experience an issue that `onRenderCell` is called more that once for the same cell during page load. I was trying to handle it by myself (as I can't provide you specific steps) using `event.userData` and some "hash". But because of the issue I mentioned above it's impossible as well.

**Comment by StfBauer** [comment]
Do you have a sample project to share?

**Comment by AJIXuMuK** [comment]
@StfBauer 
Here it is [https://github.com/AJIXuMuK/issues/tree/master/fc-userdata](https://github.com/AJIXuMuK/issues/tree/master/fc-userdata)

You can get the package from `pkg/` folder and deploy it to your app cat and install the app.
It will add `SPFxUserDataPercentage` field to the site collection with applied customizer.

Or just clone the sample and use as usual in dev.

**Comment by StfBauer** [comment]
According to the remake on the userData property and my testing it works as expected. Not sure what you try to accomplish.

```js
    /**
     * An implementation defined storage property.
     *
     * @remarks
     * For example, suppose that resources need to be allocated during rendering
     * (e.g. a renderer object, an HTTP request to be canceled, a cache slot, etc).
     * The onRenderCell() implementation could store a key or handle in this property,
     * and then onDisposeCell() can use this key to find the resource to be freed.
     */
    userData: any;
```

**Comment by AJIXuMuK** [comment]
@StfBauer my assumption here is that after row selection `onRenderCell` is called for the same instance of the cell.
And if I initialized `userData` for that instance - it should be there. Especially because `onDisposeCell` has never been call.
To me it means one of two:

- either `userData` is set to null between calls on the same instance
- or row selection leads to creation on a new cell object which is incorrect as well to my mind as we will have at least 2 instances for the same cell in the memory.

**Comment by AJIXuMuK** [comment]
Following up...

**Comment by kemesfun** [comment]
@AJIXuMuK  onRenderCell() gets called separate times for each item. It has its own userData per item. This is why the counter looks like it is resetting each time.

**Comment by AJIXuMuK** [comment]
@kemesfun - I get that.
That's why I used "instance of the cell".
It is not saved for each cell.

**Comment by AJIXuMuK** [comment]
Can't repro the issue anymore. `userData` contains correct information
