### ISSUE TITLE
SPFx deployment through WSP solution

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#3118]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

A quick question here, we have product on SharePoint which is compatible with with SharePoint server 2016 (using farm WSP solution) and Add-in (For both online and on-premise). We are planning to migrate our solution to 2019. After testing, the SPFx solution (sppkg) which was built for SP Online, worked just fine on SharePoint Server 2019 (App Server). 

**However is there any way to deploy extensions and SPFx webpart using WSP if we plan to have WSP solution for SharePoint server 2019?**

**Comment by andrewconnell** [comment]
Not directly... the supported way to deploy SPFx solutions is via the generated `.SPPKG` file uploaded to an app catalog.
