### ISSUE TITLE
This page does not clearly describe how to enable support for full-width column

### ISSUE THREAD

**Issue by hazymat** [SharePoint/sp-dev-docs#3119]
This documentation page is well-presented, however the crux paragraph which reads "in the web part manifest set the supportsFullBleed property to true" does not actually describe how to edit this "web part manifest". An online search for how to do this brings up another documentation page on support.office.com called "Open and use the web part maintenance page". This second document shows how to enter maintenance mode, but even that document does not describe how to actually edit the manifest. By following the instructions there, we can VIEW the manifest page, but there is no way to change it.

This document should be updated with clear instructions on how to actually edit the manifest, where it's stored, what to click, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4825eeab-f123-c0fb-0d30-6d634c821bd2
* Version Independent ID: 55d7e710-4faa-4cfa-772d-f83962d9fe52
* Content: [Use web parts with the full-width column](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column)
* Content Source: [docs/spfx/web-parts/basics/use-web-parts-full-width-column.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/use-web-parts-full-width-column.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The articles does show where you should make this change, but it doesn't not explain where you will find the web part manifest file is. I just submitted a fix to the content to add a note to help.

The manifest file is the `*.manifest.json` file that sits beside the web part `*.ts` file in the project.

**Comment by chinnivenkata** [comment]
After applying supportsFullBleed property to true we are able hide quick launch / left navigation from Modern SharePoint Team Sites, but flicking exist on first time page loads, do we have any other way to hide quick launch without flickers?
