### ISSUE TITLE
Images referenced in .scss are loaded from incorrect path

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#312]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Load images referenced in .scss files.

#### Observed Behavior
Image references from .scss file are resolved relative to the page URL rather than the URL of the bundle.

#### Steps to Reproduce
- create new project
- in the web part folder add a .png file
- in the .scss file add:
```css
.helloWorld {
  .img {
    background: url('./myimage.png');
  }
}
```
- in the component add:
```jsx
<p className={styles.img}></p>
```
- `$ gulp serve`
  - workbench tries to load the image from **/temp/myimage_12345.png** rather than from **/dist/myimage12345.png**

**Comment by StfBauer** [comment]
Same applies to all assets. Had the same problem yesterday with custom icon fonts. Those were also loaded from the exact same wrong place.

**Comment by webtechy** [comment]
Still seeing this issue. What is the resolution?

**Comment by webtechy** [comment]
This kind of thing has been driving me crazy. This should be the simplest of things to be able to do. I had to hack it with the following:

```
gulp.task('copyfonts', function() {
  console.log("Coping fonts ...");
  gulp.src('./dist/*.{ttf,woff,woff2,eof,svg}')
  .pipe(gulp.dest('./temp'));
});

gulp.task('copyimages', function() {
  console.log("Coping images ...");
  gulp.src('./dist/*.{png,jpg,jpeg,gif}')
  .pipe(gulp.dest('./temp'));
});

gulp.task('serve-all',['copyfonts', 'copyimages', 'serve'], function() {
  console.log("Fix to serve everything ... but this doesn't work ... ");
});
```

And then open another CMD window and run `gulp copyimages` and `gulp copyfonts`. On deployment, I just have to copy these files to obscure locations in SharePoint to get it to work. Really?!

NB This isn't just referenced from CSS, this is also for doing:

```
import { Component } from '@angular/core';

@Component({
    selector: 'layout-header',
    template: `<div class='wt-header'><img src="{{headerImgSrc}}"></div>`,
    styles: [
        String(require('./header.scss'))//,
] // You need sass-loader for this. Also do not call it "something.module.scss" (see https://bob1german.com/2016/12/12/html-templates-in-spfx/), and also read more here: https://github.com/jtangelder/sass-loader

})
export class HeaderComponent {
 constructor() {}

 private headerImgSrc = require('./FormHeader.png');
 private name: string = 'Requirement';
}
```

**Comment by waldekmastykarz** [comment]
For now, I've documented a workaround you can use for this issue. It involves setting the publicPath in webpack. For more information see: https://blog.mastykarz.nl/correctly-reference-images-sharepoint-framework-solutions/.

**Comment by webtechy** [comment]
@waldekmastykarz - is this kind of thing going to be in the standard yeoman project scaffold?

**Comment by webtechy** [comment]
Do you still have to put the following too?

`require('set-webpack-public-path!');`

**Comment by webtechy** [comment]
@waldekmastykarz Assume `if (build.getConfig().production)` depends on if you run `--ship` or not?

**Comment by waldekmastykarz** [comment]
I don't know if it will be available in the standard template, but I sure hope so, given the default setup doesn't work.

You don't need to reference `require('set-webpack-public-path!');`, at least not that I know of. 

`if (build.getConfig().production)` is true indeed for `--ship` or `--production`

**Comment by iclanton** [comment]
You do need to include `require('set-webpack-public-path!');` if you reference any files that don't become part of your base JavaScript bundle.

Does including that line not fix this issue?

**Comment by iclanton** [comment]
I'm going to close this. Feel free to reopen if you're still having this issue.
