### ISSUE TITLE
View formatting based on ContentType?

### ISSUE THREAD

**Issue by MarianNerd** [SharePoint/sp-dev-docs#3120]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> I have a custom list with multiple contenttypes. Based in the contenttype I want to give the row a background color. I've added the ContentType as a column in my view.
> I use the following JSON as view format
{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "additionalRowClass": "=if([$ContentType]=='Social_Facebook', 'ms-bgColor-themeTertiary', 'sp-field-severity--blocked')"
}
>I've dubble, tripple checked the value of the ContentType :). However the rows that match the ContentType has a the RowClass 'sp-field-severity--blocked' (the if statement goes to the else and the row has the class sp-field-severity--blocked)
> I've tried [$ContentType.title] but with no different result.

#### QUESTION
So my question is: Is it possible to Format a view based on the ContentType? 
Computed columns isn't listed in the (un)supported columns. 
https://docs.microsoft.com/nl-nl/sharepoint/dev/declarative-customization/column-formatting#supported-column-types

**Comment by thechriskent** [comment]
Currently, List Formatting does not allow the retrieval of the value of the ContentType field. However, you _can_ get the **`ContentTypeId`**. So, while not nearly as legible you can do something like this (replace with your own Ids):

```json
{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json", 
  "additionalRowClass": "=if([$ContentTypeId]=='0x0100524AA836B3D3C645AA562C045097A54A00E360498EDC5F864B9CFEB8D675108B79','ms-bgColor-redDark', 'ms-bgColor-orangeLighter') + ' ms-fontColor-white'"
}
```

The above format looks like this:
![image](https://user-images.githubusercontent.com/8364109/50157730-3349ac80-02a0-11e9-9d75-7c02eaa18a80.png)

Note, that `ContentTypeId` is one of the few fields you can utilize without having to add it to the view explicitly.

If you have additional questions about this or if anything isn't clear, please feel free to reopen the issue. Thanks!
