### ISSUE TITLE
How to fix Typescript errors for external packages

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-docs#3121]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I added "devextreme & devextreme-react" to my webpart. When I gulp serve I get these errors: 

> node_modules\devextreme\bundles\dx.all.d.ts(250,43): error TS1005: ',' expected.

I understand that SPFx is running on Typescript 2.X  which might cause issues with packages which are build for TS 3.X

Are there any options or is the answer simple "You can't use this package at the moment" 

From what I can see in devextreme, the devDependencies is `"typescript": "^2.0.3",` so I'm not entirely sure why it's not working in SPFx 

Is there anyway to `gulp serve` and ignore TS errors? 

#### Observed Behavior

![image](https://user-images.githubusercontent.com/5871660/50056203-e8982b00-010d-11e9-94b8-d3ae46e49ace.png)

![image](https://user-images.githubusercontent.com/5871660/50056231-3ad94c00-010e-11e9-97f4-417c6d1da9bb.png)

**Comment by andrewconnell** [comment]
I just installed the **devextreme-react** package in a brand new SPFx React webpart project, added the import statement and reference, then ran **gulp build** & it built with no errors so I can't repo... 

> Is there any way to gulp serve and ignore TS errors?

No... this error is rooted from the **gulp serve** command running the task **gulp build** which leverages TypeScript for compilation. The root problem is not **gulp serve** but instead, it's coming from TypeScript's compiler.

Unfortunately, this isn't related to SPFx so there's not much MSFT can do with this error... also can't repo with what's provided. Feel free to reopen with more detail if you're still having issues.
