### ISSUE TITLE
React is not defined after update SPFx

### ISSUE THREAD

**Issue by kezack** [SharePoint/sp-dev-docs#3123]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

After the update from 1.4.1 to 1.6 I have this error during a "gulp serve"

![image](https://user-images.githubusercontent.com/2874315/50061040-04e2a900-019c-11e9-8039-bfd11f49f014.png)

**Comment by andrewconnell** [comment]
This indicates the JS file is not found upon rendering... can you provide more information on your project? Have you verified there are no build errors when you ran **gulp build** (during the **gulp serve**) process?

**Comment by kezack** [comment]
My gulp build 

![image](https://user-images.githubusercontent.com/2874315/50286564-14921400-0460-11e9-8955-d154708694ca.png)


my gulp serve.

![image](https://user-images.githubusercontent.com/2874315/50286683-75215100-0460-11e9-8bea-52f9502b6a53.png)

**Comment by andrewconnell** [comment]
Everything looks good in the build… could you share more about your project, like package.json? What environment are you running in (SPO / SP2016 / SP2019), etc?

**Comment by kezack** [comment]
SPO

My package.json

![image](https://user-images.githubusercontent.com/2874315/50350872-c3a61c80-0540-11e9-8786-63ba76dc39ad.png)

**Comment by andrewconnell** [comment]
I'm sorry, but there's not enough information here to act on... the error indicates that the bundle isn't found or one of its dependencies (React). 

When this happens to me, I try to start clean: first clearing all builds (`gulp clean`), removing all installs (delete `node_modules`), then reinstall all dependencies and try to build again.

Also, consider how you upgraded... did you just update the dependencies in `package.json`? Have you tried the [Office 365 CLI project upgrade command](https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/) to see if you missed something?
