### ISSUE TITLE
Unique farm ID from SPFx package in SharePoint server 2019

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#3124]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Question**
Is it possible to get something unique about Farm where our SPPKG file is installed using code? 

**Details**
We have product created for modern SharePoint having SPFx solution (SPPKG), for sharepoint online, its quite easy to get the url host (contoso.sharepoint.com) which is unique. However that is not the case in farm, so is there anything we can get using code which is unique in farm? It should also have the server ID so if customer has multi WFE server, we have to bill for each.

**Comment by VesaJuvonen** [comment]
There's, unfortunately, no exposed remote APIs for farm information.
