### ISSUE TITLE
Modern Page is broken when opened inside an iframe

### ISSUE THREAD

**Issue by anasnakawa** [SharePoint/sp-dev-docs#3125]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Starting this weekend, we started to experience an issue that is breaking our product in live production environments, where Modern pages are not being loaded inside an iframe, before the weekend, all pages used to be rendered just fine inside iframes.

**Update:**
The issue seems to happen on some machines, while does not occur for other machines for the same site, multiple colleagues faced this issue recently, and opening the site in private mode didn't help.

**Update 2**
Issue seems to be related to the latest update from Chrome **Version 71.0.3578.98 (Official Build) (64-bit)**, those machines running Chrome less than the version above does not have this issue,
Even latest Chrome Canary build has the same issue **Version 73.0.3642.0 (Official Build) canary (64-bit)**

**Update 3**
So I digged down into what has changed in Chrome since version 71, and found out that they have deprecated `document.origin`, (more info on the following link) https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems

#### Expected or Desired Behavior

Opening a Modern page in an iframe should work, and the content of the opened page should be rendered.

#### Observed Behavior

Any Modern page loaded in an iframe will fail, and will give the following exception:

Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
TECHNICAL DETAILS
Error details: Error: ***Error initializing application. Error: Error: ***Error initializing application. Error: SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'ms-appx://microsoft.sharepointdesktop' in a call to 'postMessage'.

![image](https://user-images.githubusercontent.com/559002/50069872-5cf1cd80-01e5-11e9-939f-bb3fc3b322c8.png)

#### Steps to Reproduce

The issue can be easily reproduced by injecting an iframe into any page, follow these steps to reproduce.

1. Open any Modern Page (e.g: a Team Site Page)
2. Run the following code from the developer tools, that will inject an iframe of the same page and make it clearly visible on the screen.

```
var iframe = document.createElement('iframe');
iframe.setAttribute('src', location.href);
// not necessary, just making the iframe obvious on the page
iframe.style.width = '70vw';
iframe.style.height = '70vh';
iframe.style.position = 'absolute';
iframe.style.top = '100px';
iframe.style.left = '100px';
iframe.style.zIndex = '10';
document.body.appendChild(iframe);
```

**Comment by anasnakawa** [comment]
@patmill Appreciate your response here, 
this is breaking a very major feature in live production environments.

Thanks

**Comment by patmill** [comment]
Is the reference to sharepoint desktop coming from the browser?
________________________________

**Comment by nikskhubani** [comment]
No this is part of our code

**Comment by patmill** [comment]
I'm sorry - not quite following.  Are you injecting the post message to 'Window': Invalid target origin 'ms-appx://microsoft.sharepointdesktop' into the code?

________________________________

**Comment by anasnakawa** [comment]
Is it not recommended to use `env=Desktop`?

**Comment by patmill** [comment]
It's not supported to say "this page is hosted in the desktop app" without it being hosted in the desktop app, no.  If you want a supported way to say "please don't show chrome", you'll need to open a user-voice request.  At this point, the code is working as expected.

**Comment by anasnakawa** [comment]
we want a supported way to "show chrome", that when a page opened in an iframe, we need it to look exactly the same as if it was opened without the iframe, without trimming any content.

**Comment by patmill** [comment]
AS mentioned, there is currently no supported way to do this.  I would recommend opening up a UserVoice request.
