### ISSUE TITLE
Update lookup field using Rest Api

### ISSUE THREAD

**Issue by tim131452** [SharePoint/sp-dev-docs#3126]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery

Based on the above code, I would like to save value in a lookup field, can anyone show me any guidance on how the process works.

**Comment by tim131452** [comment]
> #### Category
> * [x]  Question
> * [ ]  Typo
> * [ ]  Bug
> * [ ]  Additional article idea
> 
> https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery
> 
> Based on the above code, I would like to save value in a lookup field, can anyone show me any guidance on how the process works.

i already added something like this :
![image](https://user-images.githubusercontent.com/38599276/50074376-ac9cbd00-0216-11e9-82f7-7fe7fa80b1ce.png)

My lookup field name is Category and the value i would like to pass is id:2 but i m not able to send the value

**Comment by andrewconnell** [comment]
@tim131452 can you provide more details on your code? Based on the provided info, it's nearly impossible to troubleshoot your code or the error you're having.

The link you reference doesn't address lookup fields, rather it addresses using jQuery to upload a file... two very different things.

Or look to use PnPJS as @CPritch suggests.

**Comment by tim131452** [comment]
@andrewconnell @CPritch
Thk u so much for the feedback guys, really helped me it and i solved my problem, thks again
