### ISSUE TITLE
Updating Existing content type. 

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/sp-dev-docs#3127]
Hi Team, 

When i update the existing content type, by adding a new column or exsiting site column it throws an error. 

![image](https://user-images.githubusercontent.com/10346150/50081904-9fcb9980-0215-11e9-8a0f-2fe14a043b28.png)

Can anyone tell me how to fix this one ? or its a Sharepoint issue ? 

Thanks & Regards, 
Pavan.

**Comment by iamguptarishi** [comment]
Are you updating using UI or some script?

**Comment by semopz** [comment]
Are the content types listed in your screenshot delivered from a Content Type Hub site? Are they children of the content type you are trying to edit? Is your account a site collection admin on /sites/1?

**Comment by andrewconnell** [comment]
As the error indicates, you don't have access to change that content type. The error indicates it has been set to read only which blocks updates. Only content types that are not-readonly can be updated.
