### ISSUE TITLE
React problem with SharePoint hosted Workbench (On-Prem 2019)

### ISSUE THREAD

**Issue by AndreyFedotov** [SharePoint/sp-dev-docs#3128]
Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Expected or Desired Behavior

I would like to test my Client WebPart with Sharepoint page context. So I'm using SharePoint hosted Workbench: http://shp-dev1/sites/testWeb/_layouts/15/workbench.aspx

Observed Behavior

I'v got an error in browser when I try to add simple HelloWorld WP to my **On-Prem 2019 Workbench** page:

_> [SPLoaderError.loadComponentError]:
> ***Failed to load component "fe735b47-53a5-4b5f-98ae-6ce4c3d2fce0" (HelloWorldWebPart).
> Original error: ***Failed to load URL 'https://localhost:4321/node_modules/react/dist/react.js' for resource 'react' in component 'fe735b47-53a5-4b5f-98ae-6ce4c3d2fce0' (HelloWorldWebPart). The file was not found in the server.
> Make sure that you are running 'gulp serve'.
> 
> ***INNERERROR:
> ***Failed to load URL 'https://localhost:4321/node_modules/react/dist/react.js' for resource 'react' in component 'fe735b47-53a5-4b5f-98ae-6ce4c3d2fce0' (HelloWorldWebPart). The file was not found in the server.
> Make sure that you are running 'gulp serve'
>_ 

Steps to Reproduce

1) download latest yo generator (1.7)
2) select 'SharePoint 2019 onwards, including...' as a target
3) select reactJS
4) update config.json by setting
"initialPage": "http://shp-dev1/sites/testWeb/_layouts/15/workbench.aspx"
5) gulp serve

When Workbench is hosted locally - there is no problem!

**Comment by AndreyFedotov** [comment]
Setting **"https": false** give me another error:

> GET https://localhost:4321/temp/manifests.js net::ERR_CONNECTION_CLOSED
> 
> sp-webpart-workbench-assembly.js?uniqueId=2g4QD:105 Failed to load debug manifests: Error: Error loading https://localhost:4321/temp/manifests.js
> 	XHR error loading https://localhost:4321/temp/manifests.js

I see the problem in a path to _react.js_:
- Local Workbench load reactJs from here:
  https://localhost:4321/node_modules/@microsoft/sp-loader/node_modules/react/dist/react.js
- SP-hosted Workbench try to find it here:
  https://localhost:4321/node_modules/react/dist/react.js

**Comment by StfBauer** [comment]
@AndreyFedotov can you share your serve.json?

**Comment by AndreyFedotov** [comment]
{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "initialPage": "http://shp-dev1/sites/testWeb/_layouts/15/workbench.aspx",
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}

**Comment by StfBauer** [comment]
I was able to reproduce your behaviour and got the same result. I am afraid the only option you have right is to create and assign a self-signed cert to your SharePoint. After that and switching the 'server.json' back to serve via HTTPs I was able to debug the web part.

**Comment by AndreyFedotov** [comment]
@StfBauer nothing changed(

![screen shot 2018-12-18 at 13 10 22](https://user-images.githubusercontent.com/13960477/50147374-09f04700-02c7-11e9-9e9f-c3529b98cacc.png)

{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "initialPage": "https://shp-dev1/sites/testWeb/news/_layouts/15/workbench.aspx",
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}

**Comment by StfBauer** [comment]
So the error message says you should make sure that your `gulp serve` is running.
Sorry to ask. Is it running?

**Comment by AndreyFedotov** [comment]
yes, of course it's running)


error text is correct - react folder (_/node_modules/react_) really do not contains **dist** folder:

![screen shot 2018-12-18 at 15 16 12](https://user-images.githubusercontent.com/13960477/50153697-32cd0800-02d8-11e9-95d5-125d02b14b16.png)

**Comment by andrewconnell** [comment]
@AndreyFedotov In an effort to eliminate things, have you tested it in a SharePoint Online hosted workbench?

**Comment by AndreyFedotov** [comment]
@andrewconnell I'v just tested the same HelloWorld client web part in a SPO hosted workbench - it's working good.
SP2019 workbench still give me an error((

**Comment by andrewconnell** [comment]
I doubt SP2019 will support React16... SP2019 is from v1.4.1 which is January 2018. They didn't start rolling React v16 to SPO until just recently. I doubt we'll see React16 on SP2019 anytime soon, if ever.

**Comment by AndreyFedotov** [comment]
@StfBauer your solution helps me a lot. Thanks!

**Comment by andrewconnell** [comment]
@AndreyFedotov Cool... so ok to close this issue as resolved?
