### ISSUE TITLE
Conditional formatting based on calculated field is broken since summer 2018

### ISSUE THREAD

**Issue by hazymat** [SharePoint/sp-dev-docs#3129]
At some unknown point, approximately August 2018, I had a sharepoint online list whose column formatting stopped working. The column formatting was based on a calculated field (where both the reference and the calculated columns are Date and Time type).

Part of the column formatting expression worked, that is the part that evaluates whether there is a value (and if so, apply a green background), however the nested condition that looks to see whether the date is approaching in the next three days, colouring the background red, stopped working.

I have reproduced the problem described above using a new Date and Time column, as well as a column using calculated value based on the first. The formatting only works on the original, not the calculated column.

This previously worked. Is it a new 'feature'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by iamguptarishi** [comment]
Can you please share the JSON format you are using for column formatting?

**Comment by hazymat** [comment]
Hello. I have tested this with both Excel-style expressions and custom JSON. I have pasted this below. The below code is an expansion of the example posted on the documentation page under the heading "[Formatting items based on arbitrary dates (advanced)](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#formatting-items-based-on-arbitrary-dates-advanced)"

Sorry about the formatting, I have also attached (to this comment) a nicely formatted txt file with the json.

`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "debugMode": false,
  "elmType": "div",
  "txtContent": "@currentField",
  "attributes": {
    "class": {
      "operator": "?",
      "operands": [
        {
          "operator": "<=",
          "operands": [
            "[$Next_x0020_Deadline]",
            1
          ]
        },
        "",
        {
          "operator": "?",
          "operands": [
            {
              "operator": "<=",
              "operands": [
                "[$Next_x0020_Deadline]",
                {
                  "operator": "+",
                  "operands": [
                    "@now",
                    86400000
                  ]
                }
              ]
            },
            "sp-field-severity--severeWarning",
            {
              "operator": "?",
              "operands": [
                {
                  "operator": "<=",
                  "operands": [
                    "[$Next_x0020_Deadline]",
                    {
                      "operator": "+",
                      "operands": [
                        "@now",
                        259200000
                      ]
                    }
                  ]
                },
                "sp-field-severity--warning",
                "sp-field-severity--good"
              ]
            }
          ]
        }
      ]
    }
  }
}`
[date-ranges-json.txt](https://github.com/SharePoint/sp-dev-docs/files/2689785/date-ranges-json.txt)

**Comment by andrewconnell** [comment]
Just updated your last post... you can let GH format the code if you [fence it](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and provide help to GH on how to colorize it by telling it the format.

*Sorry, I don't have insight into what the issue is though as not terribly familiar with list formatting*... added labels for visibility to others who may though...

**Comment by iamguptarishi** [comment]
As per Microsoft documentation they say Calculated columns are not supported for Column Formatting. Not sure if this was changed as you mentioned that it was working fine earlier. Probably SharePoint eng team might answer this.

[https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#formatting-items-based-on-arbitrary-dates-advanced]

Supported column types
The following column types support column formatting:

Single line of text
Number
Choice
Person or Group
Yes/No
Hyperlink
Picture
Date/Time
Lookup
Title (in Lists)
The following are not currently supported:

Managed Metadata
Filename (in Document Libraries)
**Calculated**
Retention Label
Currency

**Comment by iamguptarishi** [comment]
@thechriskent It seems that the calculated columns are broken. I tried to debug it and found that the Valid date time columns are converting date properly but with calculated columns its not converting date property as sub-string method is giving error. Not sure if this "  var l = a[0] + ".calculated";" is intentionally added to the code. See the screen shots for more details.
![dateerror](https://user-images.githubusercontent.com/8044005/50193554-edb2d100-02eb-11e9-8b55-079c0ccd79a1.png)

**Comment by niketjain2020** [comment]
This is work in progress, soon user should be able to format calculated columns   output as date, though user can still format calculated columns for Single line text, Numbers and Yes/NO

**Comment by hazymat** [comment]
This has magically* started working again, so I think you're good to close this issue now!

* (Magically = I know someone spent time working on this, so thank you!)
