### ISSUE TITLE
Markdown Web Part in Office 365 has multiple issues

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3135]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Make the Markdown web part work properly.

#### Observed Behavior
The newly introduced markdown web part has multiple issues.

#### Issue 1 - Headline styles are applied through ID's
The Markdown web part allows creating headlines from H1-H6 which is good. On the other hand, the default test web part allows headlines only from H1-H3 so there is maybe an issue with styling.

<img width="426" alt="screenshot 2018-12-18 at 10 49 43" src="https://user-images.githubusercontent.com/5503835/50146440-02737280-02b4-11e9-89fd-4614a32ecd2a.png">

The screenshot was taken directly from the rendered web part.
The bigger issue arises how the headlines are rendered in the web part.

<img width="651" alt="screenshot 2018-12-18 at 10 38 15" src="https://user-images.githubusercontent.com/5503835/50146539-423a5a00-02b4-11e9-970c-568aa367ebb9.png">

The web parts add an additional id to ever headline:
a) The IDs are not unique on the page
b) Those IDs are not used for styling so why render them at all.

#### Issue 2 - Paragraph styles do not match with Text Web Part
A paragraph from the text web part gets rendered like this:
<img width="1230" alt="screenshot 2018-12-18 at 11 05 47" src="https://user-images.githubusercontent.com/5503835/50146844-fa680280-02b4-11e9-9052-33b80f3c3b3b.png">

The Markdown web part renders the text like this:
<img width="1265" alt="screenshot 2018-12-18 at 11 06 08" src="https://user-images.githubusercontent.com/5503835/50146883-12d81d00-02b5-11e9-97f5-584e583c79fd.png">

The font-size of a paragraph is too small and the line-height maybe as well.

##### Issue 3 - Images are not responsive
The Markdown web part does not support responsive images - The images simply got cutoff instead of properly placed inside the page container view CSS.

<img width="1325" alt="screenshot 2018-12-18 at 11 08 48" src="https://user-images.githubusercontent.com/5503835/50147036-73675a00-02b5-11e9-88bf-68f467b14497.png">

There are some CSS classes attached to the image but it seems they only cut off the image instead of use:

```css
.imageclasse{
   width: 100%;
   height: auto;
}
```

It seems like some style sheet classes are attached to the image but they don't do much and especially not support responsive design.
<img width="1004" alt="screenshot 2018-12-18 at 11 12 36" src="https://user-images.githubusercontent.com/5503835/50147272-fee0eb00-02b5-11e9-8876-1eb9df27341a.png">

#### Issue 5 - List support wrong formating?
The default text web part lacks support to add a bullet or numbered list. This is possible through the markdown web part. These elements might not have been styled properly and the text size is too small.

<img width="531" alt="screenshot 2018-12-18 at 11 17 06" src="https://user-images.githubusercontent.com/5503835/50147581-d4436200-02b6-11e9-9491-d9000947e8a5.png">

#### Issue 6 - No Table design
While tables are not really part of the Markdown specification the web part renders table inappropriate and does not have any design attached.
A table designed with the following markdown code:

```md
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

Produces the following design:

<img width="358" alt="screenshot 2018-12-18 at 12 16 50" src="https://user-images.githubusercontent.com/5503835/50150675-f17c2e80-02be-11e9-8664-6e1498f6fed1.png">

While a default table layout without changes at all looks like this:
<img width="403" alt="screenshot 2018-12-18 at 12 18 46" src="https://user-images.githubusercontent.com/5503835/50150747-28524480-02bf-11e9-81c6-970f915d2eb9.png">

#### Issue 7 - Missing block quote aka pull quote style
The text editor web part has a style called "pull quote" that looks like this:

<img width="1244" alt="screenshot 2018-12-18 at 12 21 28" src="https://user-images.githubusercontent.com/5503835/50150878-9c8ce800-02bf-11e9-8217-581aa1e25787.png">

Design the design is not present in the MarkDown, it has the wrong name because it is a blockquote - Not only from the underlying "HTML" element but also from its design.

The markdown web part should have the same style because you can define a block quote like this in Markdown.

```md
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin metus arcu, commodo at gravida at, rhoncus sit amet nunc. Ut leo neque, faucibus ut rhoncus sed, eleifend vehicula ante. Proin finibus condimentum felis, at tempor purus vulputate non. Praesent sed faucibus odio. Nam dignissim, felis at porttitor congue, urna nisi lobortis mauris, id consequat nibh quam a risus. Nulla facilisi. Morbi ornare ultricies sodales. In pulvinar, orci nec luctus elementum, est tortor vehicula erat, a tristique enim massa pharetra lectus.
```

The output produces by the Markdown web part looks like this.

<img width="1271" alt="screenshot 2018-12-18 at 12 35 19" src="https://user-images.githubusercontent.com/5503835/50151526-723c2a00-02c1-11e9-92a4-060b0bc3f059.png">

There are still more issues but those have been for now uncovered yet. Would be great to get those fixed. Otherwise it is not recommended to use it in productive use because it leed to many design inconsitencies in the modern experience.

**Comment by patmill** [comment]
So, this isn't framework code, or code that is handled by this issues list (although your bug report is great).  I'll forward this to the product group responsible.

**Comment by StfBauer** [comment]
Thank you @patmill for forwarding it.

**Comment by VesaJuvonen** [comment]
Closing this at GitHub as it's for oob web part and we cannot track those here. As this investigation had tremendous amount of valuable details, we have bypassed it to the team responsible for the web part. Thanks @StfBauer for this.
