### ISSUE TITLE
[$FieldName] value does not display if referenced column is not in current View

### ISSUE THREAD

**Issue by mattyvx** [SharePoint/sp-dev-docs#3136]
When trying to display the values of a column, using its internal name, nothing is displayed if the referenced column is not in the current View.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm pretty sure that's by design... the only data from an item available in a view are those columns that have been selected in the view.
