### ISSUE TITLE
How to integrate Angular Elements App in SharePoint Framework ?

### ISSUE THREAD

**Issue by iseneggert** [SharePoint/sp-dev-docs#3137]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Angular 7 app with rich features must be running in SharePoint.

#### Observed Behavior

When adding the web part in the SharePoint Workbench, the following error pops up:

    [SPLoaderError.loadComponentError]:
    ***Failed to load component "a9402700-1924-4c05-b9e2-60aeb2e60eaf" (BpmPortalWebPart).
    Original error: ***Failed to load entry point from component "a9402700-1924-4c05-b9e2-60aeb2e60eaf" (BpmPortalWebPart).
    Original error: Error loading https://component-id.invalid/a9402700-1924-4c05-b9e2-60aeb2e60eaf_0.0.1
    	Zone already loaded.

    ***INNERERROR:
    ***Failed to load entry point from component "a9402700-1924-4c05-b9e2-60aeb2e60eaf" (BpmPortalWebPart).
    Original error: Error loading https://component-id.invalid/a9402700-1924-4c05-b9e2-60aeb2e60eaf_0.0.1
    	Zone already loaded.
    ***CALLSTACK:
    Error
    	at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:8668:24)
    	at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4124:28)
    	at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3783:21)
    	at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3691:21)
    	at https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:6936:47
    	at e.invoke (https://localhost:4321/dist/bpm-portal-web-part.js:467:7142)
    	at t.run (https://localhost:4321/dist/bpm-portal-web-part.js:467:2319)
	    at https://localhost:4321/dist/bpm-portal-web-part.js:467:13566
    	at e.invokeTask (https://localhost:4321/dist/bpm-portal-web-part.js:467:7826)
	    at t.runTask (https://localhost:4321/dist/bpm-portal-web-part.js:467:3010)

#### Steps to Reproduce

1. Build Angular app using Angular cli
    ng build --prod --aot --output-hashing=none

1. Concat Angular generated scripts to one file (will be referenced later)
   type runtime.js polyfills.js scripts.js main.js > bpm-portal.js (Windows 10 dev environment)

1. Create the SharePoint web part as described in the documentation
    https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

1. Copy Angular build to SharePoint web part app folder
    ../src/webparts/bpmPortal/app

1. Reference Angular app in SharePoint wep part
    ../src/webparts/bpmPortal/BpmPortalWebPart.ts

        import { Version } from '@microsoft/sp-core-library';
        import {
          BaseClientSideWebPart,
          IPropertyPaneConfiguration,
          PropertyPaneTextField
        } from '@microsoft/sp-webpart-base';

        import { escape } from '@microsoft/sp-lodash-subset';
        import * as strings from 'BpmPortalWebPartStrings';

        import '@webcomponents/custom-elements/src/native-shim';
        import '@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce';

        import './app/bpm-portal.js';

        export interface IBpmPortalWebPartProps {
          description: string;
        }

        export default class BpmPortalWebPart extends BaseClientSideWebPart<IBpmPortalWebPartProps> {
  
          public render(): void {
            this.domElement.innerHTML = `<app-root></app-root>`;
          }

          protected get dataVersion(): Version {
            return Version.parse('1.0');
          }

          protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
            return {
              pages: [
                {
                  header: {
                    description: strings.PropertyPaneDescription
                  },
                  groups: [
                    {
                      groupName: strings.BasicGroupName,
                      groupFields: [
                        PropertyPaneTextField('description', {
                          label: strings.DescriptionFieldLabel
                        })
                      ]
                    }
                  ]
                }
              ]
            };
          }
        }

1. Run SharePoint web part in workbench
    gulp serve

#### Background
The Angular app runs without SharePoint integration perfectly. The app is hosted on Azure and uses AspNetCore REST services. It authenticates against an Office 365 tenant using adal. 
Customers require integration in SharePoint. We have tried out different approaches as decribed in SharePoint docs, but none of them worked.

I ask you guys for help! Is there a way that we can integrate a fully functional Angular app in SharePoint?

Thanks, Tom

**Comment by andrewconnell** [comment]
> Is there a way that we can integrate a fully functional Angular app in SharePoint?

Yup... using Angular Elements. But keep in mind today, it's still going to be a HUGE payload... hopefully, that changes when Ivy finally ships.

To your issue though, without seeing the Angular Elements app & how it's bootstrapping, can't be sure what's up with the error. Your process looks very similar to how I've done it (blog post series showing my process: http://www.andrewconnell.com/blog/using-angular-elements-in-sharepoint-framework-projects).

**Comment by iseneggert** [comment]
Thx Andrew!

The setup I have taken is exactly from your blog post. It was the best explained post I found.

Find below some more information about the Angular Elements app. Any more help is very much appreciated!


#### app.module.ts

        // App modules
        import { BrowserModule } from '@angular/platform-browser';
        import { NgModule, Injector, APP_INITIALIZER } from '@angular/core';
        import { createCustomElement } from '@angular/elements';
        import { HttpModule } from '@angular/http';
        import { HttpClientModule } from '@angular/common/http';
        import { SharedModule } from './shared/shared.module';

        // Material design
        import { FormsModule } from '@angular/forms';
        import { MaterialModule } from './shared/material.module';
        import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

        // Components and directives
        import { AppComponent } from './app.component';
        import { CultureComponent } from './shared/culture.component';
        import { LoadingComponent } from './core/loading.component';
        import { LoadingDirective } from './core/loading.directive';

        // Authentication
        import { AdalService, AdalGuard } from 'adal-angular4';

        // Feature modules and components
        import { MessageComponent } from './shared/message.component';

        // Routes
        import { AppRoutingModule } from './app-routing.module';

        // Services
        import { CultureService } from './shared/culture.service';
        import { HelperService } from './core/helper.service';
        import { SettingsService } from './core/settings.service';
        import { StartupService } from './core/startup.service';

        // Interceptors
        import { HttpInterceptorProviders } from './http-interceptor/http-interceptor-providers';

        // Load configuration at startup
        export function startupFactory(startupService: StartupService): Function {
          return () => startupService.load();
        }

        @NgModule({
          declarations: [
            AppComponent,
            CultureComponent,
            LoadingComponent,
            LoadingDirective,
            MessageComponent
          ],
          imports: [
            BrowserModule,
            HttpClientModule,
            HttpModule,
            AppRoutingModule,
            SharedModule,
            FormsModule,
            MaterialModule,
            BrowserAnimationsModule
          ],
          providers: [
            AdalService,
            AdalGuard,
            CultureService,
            HelperService,
            SettingsService,
            StartupService,
            {
              provide: APP_INITIALIZER,
              useFactory: startupFactory,
              deps: [StartupService],
              multi: true
            },
            HttpInterceptorProviders
          ],
          bootstrap: [AppComponent],
        })
        export class AppModule {
          constructor(
            private injector: Injector
          ) { }

          public ngDoBootstrap() {
            if (!customElements.get('app-root')) {
              const AppElement = createCustomElement(AppComponent, { injector: this.injector });
              customElements.define('app-root', AppElement);
            }
          }
        }

#### app.routing-module.ts
        import { NgModule } from '@angular/core';
        import { RouterModule, Routes } from '@angular/router';
        import { DashboardModule } from './dashboard/dashboard.module';

        export function getDashboardModule() { return DashboardModule; }

        const routes: Routes = [
          { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
          { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
          { path: 'processes', loadChildren: './process/process.module#ProcessModule' },
          { path: 'folders', loadChildren: './document/document.module#DocumentModule' },
          { path: 'workflow', loadChildren: './workflow/workflow.module#WorkflowModule' },

          { path: '**', redirectTo: '' }
        ];

        @NgModule({
          imports: [RouterModule.forRoot(routes)],
          exports: [RouterModule]
        })
        export class AppRoutingModule { }

#### app.component.ts
        import { Component, OnInit, ViewEncapsulation } from '@angular/core';
        import { Router } from '@angular/router';
        import { AdalService } from 'adal-angular4';
        import { StartupService } from './core/startup.service';
        import { SettingsService } from './core/settings.service';
        import { User } from './core/user';

        declare var require: any;
        const { version } = require('../../package.json')

        @Component({
          selector: 'app-root',
          templateUrl: './app.component.html',
          styleUrls: ['./app.component.css'],
          encapsulation: ViewEncapsulation.None
        })

        export class AppComponent implements OnInit {
          appName: string;
          appVersion: string;
          routeLinks: any[];
          showSettings: boolean;
          strings: { [key: string]: string };
          user = {} as User;

          constructor(
            private adalService: AdalService,
            private startupService: StartupService,
            private settingsService: SettingsService,
            private router: Router
          ) {
            // Initialize adal service
            const config = this.startupService.getAppSettings;
            adalService.init(config);

            // Initialize app settings
            this.settingsService.init('app').subscribe();

            // Get app strings
            this.settingsService.getSettings('appStrings')
              .subscribe(strings => { this.strings = strings; }
            );
          }

          // Logout
          logout(): void {
            this.adalService.logOut();
          }

          // Navigate to user settings
          openUserSettings(): void {
            this.showSettings = false;
            this.router.navigate(['/settings/users']);
          }

          // Set initial settings
          private initialSettings(): void {
            this.appName = this.settingsService.settings.appName;
            this.appVersion = version;
            this.showSettings = false;
            this.settingsService.request.authorization = this.startupService.accessToken;
            this.settingsService.request.token = this.startupService.requestToken;

            this.user.firstname = this.adalService.userInfo.profile.given_name;
            this.user.lastname = this.adalService.userInfo.profile.family_name;
            this.user.login = this.adalService.userInfo.userName;
            this.user.name = this.adalService.userInfo.profile.name;
            this.settingsService.settings.user = this.user;

            this.routeLinks = [
              { label: this.strings['dashboard'], path: 'dashboard', icon: 'DashboardAdd' },
              { label: this.strings['processes'], path: 'processes', icon: 'ViewListTree' },
              { label: this.strings['documents'], path: 'folders', icon: 'DocumentSet' },
              { label: this.strings['workflow'], path: 'workflow', icon: 'ProcessMetaTask' }
            ];
          }

          // Sets the selected status
          setStatus(value: number): void {
            this.settingsService.request.status = value;
          }

          // Initialize component
          ngOnInit(): void {
            // Check authentication and redirect to Active Directory if needed
            this.adalService.handleWindowCallback();
            this.adalService.getUser();
            if (!this.adalService.userInfo.authenticated) {
              this.adalService.login();
              return;
            }

            // Set initial settings
            this.initialSettings();
          }
        }

**Comment by andrewconnell** [comment]
I don't have much insight here... really hard to troubleshoot without running the app. I haven't spent much time with Angular Elements (AE)... more of a React person myself these days. I've seen known issues (https://github.com/pnp/generator-spfx/issues/126#issuecomment-439648514) with change detection in AE where you have to force it... not sure if routing is also impacted by this or there is something similar.

**Comment by andrewconnell** [comment]
😊

It’s not really a problem with Angular or SPFx or one web framework being better than another. To me, the issue we now have with Angular + SPFx is that these are both ~very~ opinionated frameworks. Both have specific project structure, build processes, and tools used for each. Trying to put two opinionated things together… well it’s just hard and can lead to sharp edges you cut yourself on all the time.

React on the other hand is not opinionated much at all… if at all. This makes it easy to use in other frameworks, like SPFx. So it’s not a negative with Angular… it’s just that React is easier. I used to be an “Angular guy” as were the others you mention, but what I think we’ve all come to the conclusion of is that React is just easier within SPFx. Hence why you don’t see much content on it anymore. My blog series a few months ago on AE+SPFx was simply there to “close the book” and have something to point people to.

I’ve looked at the source from your project above, but I’m at a loss for why things aren’t working. I haven’t spent much time with Angular lately so I’d have to really study it to try to ID the problem you’re having and to be completely transparent: I’m spread thin and just don’t have the bandwidth… sorry dude ☹

**Comment by gonadn** [comment]
Thanks alot for your time Andrew,

Finally iam getting DONE with Angular and SPFX. Its simply dosent work properly.
And i think its time to just tell everyone, sorry mate you have to learn RECT to create SPFX WebParts.

Using AngulaJS then it is a problem, it takes ownership on all page, this and that, and same with Angular-Cli. Finally i was waiting for Angular Elements with some hope but again disappointed...
Iam just jumping over to REACT, done with wasting so much time for nothing on outdated blogs...

All of other MVP's STOP putting up so much garbage SHITT code and solutions witch dosent work.
I will be really angry if i see one more SPFX angular blog from Waldek or Sebastian. Simply STOP confusing people on it work and look how simple it is....WTF. Save people from this, every one knows how cool developers you are...!

**Comment by andrewconnell** [comment]
Those other guys you mention are of the same mindset I am… at least I think so. I don’t think it’s fair to say they put garbage out there… the stuff we’ve all published was correct at the time, just like most content on the internet. You have to always look at the timestamp and see if it still applies today.

**Comment by andrewconnell** [comment]
While not resolved, fair to close this issue then?

**Comment by iseneggert** [comment]
Thank you guys for commenting on this. I made pretty the same experiences as @gonadn. I love Angular and all the tools that are available today. And SharePoint is used by so many companies, it's just like that. They want to see cool apps running inside. It's just a pitty that SPFX and Angular are not going hand in hand...

Thx again Andrew for all the samples you give to the dev world.

And yes, I close now this issue, even not resolved.
