### ISSUE TITLE
OOB Highlighted Webpart - FlimStrip Template does not work in  SharePoint Mobile App

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3138]
When you click on the card, it displays, below message
![image](https://user-images.githubusercontent.com/11780473/50162065-b3423780-02dd-11e9-82f1-2990b724500e.png)
It also doesnt work for card layout and carousel layout
It works for list layout  only.

**Comment by VesaJuvonen** [comment]
As this is on oob web part, we cannot report his forward using this GitHub issue list. Please report this using the support channels from tenant administration UI. Thx.
