### ISSUE TITLE
Modern Web Part browse back JavaScript fails to trigger onInit

### ISSUE THREAD

**Issue by rrfreeman** [SharePoint/sp-dev-docs#3141]
Note: Related Item #3095 was prematurely closed

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When browsing Back to a page, the JavaScript should run again when clicking back from an item in a Modern Web Part.  
JavaScript should run on page load and again when navigating back from an Announcement or Calendar item.

#### Observed Behavior

JavaScript does not run when the page is returned to using the Back Browse feature (Backspace Button or Click to Go Back browsing arrow).  This occurs on a Modern Communications Site when navigating back from a Calendar or Announcement item.  I have tried mapping to the unload event with no luck.

The Standard apps provided in the spfx-40-fantastics (Rich Text Editor) and Script Editor web part solutions also exhibit this bug.

The result is that JavaScript solution developed using the onInit promise of the SPFx framework will fail under these circumstances.

#### Steps to Reproduce

This is reproducible using a new Communications Site and the Build your first SharePoint Framework tutorial documentation.  https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

Create an announcement item or calendar item first.  Now from the page where the SPFx Extension is running, click on the new Announcement or calendar item.  Use the Back button (or hit backspace) to go back to the page.  JavaScript will not trigger.

**Comment by patmill** [comment]
So again - I don't think there is anything incorrect here.  OnInit fires when the extension is initialized.  It isn't initialized during partial-page navigates.

If you want to trigger something on a navigate, you should hook onto the OnNavigate event.

**Comment by Barba76** [comment]
I don't know if it helps but you can try to override de onDispose method. As far I remember, this method is triggered on the webPart on partial-page navigation
