### ISSUE TITLE
Any other way to register / deploy extension & webpart without SPPKG file

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#3142]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
This is regarding SharePoint On-prem. It is right now only allowed to have SPPKG file to deploy extensions and webparts to site. However if we have app model, its not really easy to do licensing stuffs around different web front end servers in Onpremise (Also asked here about getting farm ID: https://github.com/SharePoint/sp-dev-docs/issues/3124). If this could have been a WSP solution, we could do things much better as part of deployment, 

In our product, I can make asset deployments using same element.xml file to a site however I am not sure whether its possible to deploy extensions and webparts using an on-prem feature. If so I can wrap things around on-premise solution and carry on until we get any easy way to do so.

**Comment by andrewconnell** [comment]
AGAIK, no. 

ATM the only supported way to deploy SPFx components is deploying the `*.sppkg` file to one of the two scoped app catalogs. You can do this programmatically using the ALM REST APIs which are exposed in PowerShell cmdlets & Office 365 CLI commands.

**Comment by VesaJuvonen** [comment]
No - no other way to do that.

**Comment by nikskhubani** [comment]
@VesaJuvonen @andrewconnell thank you for the answer

So for planning the future, we need to understand is it anywhere in Microsoft Road-map to deploy Extension and webpart using WSP?

**Comment by andrewconnell** [comment]
https://docs.microsoft.com/sharepoint/dev/spfx/roadmap

**Comment by VesaJuvonen** [comment]
Just to be clear: We are not planning to use WSPs to deploy SharePoint Framework components and solutions. That will never happen.

**Comment by andrewconnell** [comment]
@VesaJuvonen reopened?
