### ISSUE TITLE
SPFx webpart event on partial navigation ?

### ISSUE THREAD

**Issue by Zhephyr54** [SharePoint/sp-dev-docs#3143]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I am currently developping an SPFx webpart with which users can save some changes. So the functionality I am trying to implement on this is to prompt the user when he leaves the page without saving first, informing him that his changes will be lost. I currently got it working by simply registering an event listener on the 'beforeunload' event.

The only problem I have is that the event isn't trigerred when navigating to another modern page (partial navigation). So I would like to know if there is anything I can do to listen to a partial navigation in an SPFx webpart context in one way or another ? I am aware of the navigated event for SPFx extensions but it's not available in webpart context AFAIK.

Thanks in advance to anyone who may be able to help me on this :).

**Comment by patmill** [comment]
Have you tried hooking onto the onDispose method?  Note that we've found an issue where the onDispose is getting fired multiple times, but it should only get fired once.

In addition, it would be useful to open a UserVoice request asking for the application object to be exposed on the webpart context.
