### ISSUE TITLE
AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint

### ISSUE THREAD

**Issue by klaaslauwers** [SharePoint/sp-dev-docs#3147]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Calling a secured Web API from a custom SPFx component should work. The AadHttpClient should always take the UPN as a login_hint instead of the email address.

#### Observed Behavior
Since this morning, users receive the following error when using the AadHttpClient:
_AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint_
![error](https://user-images.githubusercontent.com/23431246/50223862-9f113f80-039c-11e9-9ffa-40b603aceb4c.png)

We can see that the auto-generated login_hint URL parameter is now the email address of the user, instead of his UPN:
https://login.windows.net/< tenant ID >/oauth2/authorize?response_type=id_token&client_id=< client ID >&redirect_uri=< tenant prefix >%2F_forms%2Fspfxsinglesignon.aspx&state=99a1b7d5-e0df-44a8-a247-d592b829b469%7Cddd8870b-461c-4a84-86c4-db2ee6feff2c&login_hint=**< things go wrong here >**&client-request-id=< request ID >&x-client-SKU=Js&x-client-Ver=1.0.16&prompt=none&nonce=< nonce >

This means that users with a different email address compared to the UPN will receive errors when trying to load a page with our custom components calling a secured Web API.

#### Steps to Reproduce
The following lines of code throw the error. 
`
const aadHttpClient: AadHttpClient = await this.context.aadHttpClientFactory.getClient(appSettings.azureADAppId);
  const result = await this.serviceContext.aadHttpClient.post(
      '${this.serviceContext.serviceUrl}',
      new HttpClientConfiguration({}) as any,
      {
        headers: Utils.withDefaultHeaders({}),
        body: JSON.stringify(data)
      }
    );
`

Am I doing something wrong or can I force the login_hint to use the UPN? 

Thanks in advance!

**Comment by Nasicus** [comment]
Happens on some of our production environments too. Without any changes.

**Comment by PzYon** [comment]
We have the same problem. It's quite critical as our whole intranet doesn't work anymore.  For your info: We're using SPFx 1.6 and all calls to graph and our custom API fail.

**Comment by NickSevens** [comment]
I can confirm the same issue. Started seeing it this morning.

**Comment by MatthiasWeibel** [comment]
We have the same problem since this morning.

**Comment by EagleWizard28** [comment]
+1 Also having the same problem, starting this morning CET time.

**Comment by jansenbe** [comment]
Yes, the error is still visible

**Comment by jansenbe** [comment]
Problem is gone for me, had to log my session off to get it working

**Comment by Nasicus** [comment]
I can also confirm it's working again.

**Comment by EthanEmotion** [comment]
Problem still persist now

**Comment by olemp** [comment]
Reproduced in IE/Edge with 1.8.1.
