### ISSUE TITLE
ContentType can only used in List Formatting when NOT included in the view

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#3150]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

For most column types, you can only reference a field when it is part of the view (for view and column formatting). However, there are a few fields (such as ID) that are always available regardless of the view. `ContentType` is one of those fields.

Creating a format referencing `ContentType` should work regardless of whether ContentType is part of the view.

#### Observed Behavior

When ContentType is NOT part of the view everything works as expected. However, when you add it to the view the format NO LONGER WORKS. This appears to be because of logic in the CustomFormatter that works like this:

- If a field value is retrievable from the row
   - check if the field is part of the rowSchema
   - If part of the rowSchema:
      - Check the field type against the white list of allowed field types
      - If an allowed type
         - Return the value
      - If not an allowed type
         - throw "could not evaluate FIELDNAME"
   - If not part of the rowSchema:
      - return the value

So, when ContentType is NOT part of the view, it is not part of the rowSchema (although it's value is retrievable) so the value is returned without issue.

When ContentType is part of the view, it is included in the rowSchema with a type of `Computed` which is NOT an allowed type so the "could not evaluate ContentType" error is thrown and the value is not returned.

#### Steps to Reproduce

Add 2 or more content types to a list. One of them should be named Apple (for the json below). Then apply this format:

```json
{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json", 
  "additionalRowClass": "=if([$ContentType]=='Apple','ms-bgColor-redDark', 'ms-bgColor-orangeLighter') + ' ms-fontColor-white'"
}
```

When ContentType is part of the view all the rows will be orange (the else case). When you remove it from the view, items with a ContentType of Apple will be red and others will be orange. You can see it here:

![All Orange and sad](https://thechriskent.files.wordpress.com/2018/12/LFContentType.gif)

Related Issue: #3120

**Comment by ahackettms** [comment]
@thechriskent I don't believe you can include teh 'Content Type' field in the view. Could you help check again? Could you clarify the exact repro step? Is it from a out of box document library or list, turn on Content Type, and then you can see the 'Content Type' field in the show/hid column panel? 

Thanks

**Comment by thechriskent** [comment]
You can see that I am including the Content Type field in the view within the animation above. However, it is not the same as just choosing the show/hide column directly from the list view.

You have to first enable content type management for the list/library (a list is shown above). Then edit the view using the classic view editor in list settings to choose the Content Type field.

Once it is part of the view the issue occurs (but you can also now use the add/hide columns panel to remove it from the view as shown above).

The issue isn't with including the ContentType or not. The issue is the flawed logic in custom formatting that skips the type checking if a field is not part of the row schema that creates this weird exception. **Basically, the suggested fix is to add the ContentType type to the list of allowed field types to the custom formatter's internal whitelisted field types.** This will ensure that the formatting behavior stays the same whether you add the ContentType field to the view or not.

Please let me know if there is any other information you need, thanks!

**Comment by ahackettms** [comment]
Thank you for the info. 
This is a reasonable request for fix. We will make a fix for it.

**Comment by thechriskent** [comment]
Just confirming this is working as expected. Thanks so much for your help on this!
