### ISSUE TITLE
Error when deploying in Teams

### ISSUE THREAD

**Issue by umaknow-alain** [SharePoint/sp-dev-docs#3151]
#### Category
- [ ] Question
- [x] Typo
- [x] Bug
- [ ] Additional article idea

**Typo**

Hi,

First, thank you for this material very cool stuff. There is a small mistake (i think) in HTML code for the dom element, the div class="${ styles.myFirstTeamsTab }" should be rename to teamsTab, otherwise you have an error in vscode.

#### Observed Behavior
I am not able to deploy the web part in teams i have an error
![2018-12-19 14_24_10-window](https://user-images.githubusercontent.com/32820097/50243728-f236c280-039b-11e9-831b-3dc30b2d318b.png)

#### Steps to Reproduce
I am able to add the webpart has an app but when i am trying to add it to a channel, the error above show up. This is my zip file. 

[TeamsTab.zip](https://github.com/SharePoint/sp-dev-docs/files/2696295/TeamsTab.zip)

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
#3151 as a docs comment.
