### ISSUE TITLE
Error when deploying in Teams

### ISSUE THREAD

**Issue by umaknow-alain** [SharePoint/sp-dev-docs#3152]
Error when deploying in Teams #3151

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm closing this as the other issue #3151 you referenced in this is already logged.
