### ISSUE TITLE
SPFX Angular Element with UI-Router not displaying data

### ISSUE THREAD

**Issue by gonadn** [SharePoint/sp-dev-docs#3153]
Iam testing Angular Element with SharePoint Framework (SPFX) Webpart, as Andrew Connell has described in his Blog

Every thing is working as asspected, i have added UI-Router in webpart just for testing how it works with Angular Element inside SPFX webpart. And as asspected routing is working, but no data is displayed on the MainComponent (Main page).

And if i add same test data in my AppComponent. then it works, data in table get displayed. But why is data not rendered/displayed on routed view "MainPage" ?

Here is my solution (SPFXAngularUIRouter) on [GITHUB ](https://github.com/gonadn/SPFXAngularUIRouter)

**Comment by andrewconnell** [comment]
Without seeing the code it's hard to troubleshoot, but by chance are you dynamically loading the data after the app loads? If so, are you aware of the change detection issue in Angular Elements? 

REF: https://github.com/angular/angular/issues/23841

Others have seen the same thing and this resolved it for them (and me): https://github.com/pnp/generator-spfx/issues/126#issuecomment-439648514

**Comment by gonadn** [comment]
You can download the code from github for troubleshoot [link](https://github.com/gonadn/SPFXAngularUIRouter)

Iam not loading data dynamically, and honestly i was not aware of "change detection" issues, i will take a look at the links you REF to...

I have seen this issue before when i tried to build a SPFX webpart with Angular and @angular/route (Not Angular Element). And for some reason iam getting same behavior this time with "Angular Element and UI-Route".

Here is how it looks like when webpart is loaded:
<img width="312" alt="pic1" src="https://user-images.githubusercontent.com/3224441/50299417-cee64300-0481-11e9-96be-d8ae1add0aec.PNG">

Data loading in AppComponent and MainPageComponent is:
<img width="197" alt="pic2" src="https://user-images.githubusercontent.com/3224441/50299632-5b910100-0482-11e9-906d-5e840dba8a9e.PNG">

html:
<img width="229" alt="pic3" src="https://user-images.githubusercontent.com/3224441/50299701-89764580-0482-11e9-8b1c-260d45c5512a.PNG">


Please take a look at the code, i will appreciate all help to solve this issue....

**Comment by gonadn** [comment]
My Conclusion is to just stop using so much time on finding out HOW / and Why when using AngularJS/Angular-Cli or Angular Elements. I know its bitter after so many years with Angular.

Simply REACT is better approach for those who want to build SharePoint Framework webparts, and STOP following MVP's putting up confusion BLOG just to show how cool developers they are. Consepts dosent work in reallity...!

**Comment by andrewconnell** [comment]
I think it does work (AE+SPFx)… keep in mind AE is still relatively new and we’re finding rough edges with it, just like other tech.

**Comment by gonadn** [comment]
yes it works, but not properly,  in reality most of the people wants to create SPA application. And all concepts as far as i have seen works but at some point not, it depends, at least Angular-Cli/Elements is not working with routing in SPFX.

At least i have now played a lot with these two samples, one with AE, and one with Angular-Cli.

And dynamically loading list data in SPFX-AE webpart using PnP, dosent work as far as i have tried...

Sample with Angular-Cli and @angular/route: GitHub [LINK](https://github.com/gonadn/SPFxAngularCLIWithRouting)

Sample 2 is with AE: GitHub [LINK](https://github.com/gonadn/SPFXAngularUIRouter)

**Comment by andrewconnell** [comment]
Known issue with AE & the router? https://github.com/angular/angular/issues/23740

**Comment by gonadn** [comment]
solution: [PnP generator-spfx ](https://pnp.github.io/generator-spfx/)
