### ISSUE TITLE
How to "switch to Workbench hosted in SharePoint"?

### ISSUE THREAD

**Issue by haugan** [SharePoint/sp-dev-docs#3154]
Step 4 says: "Switch to the Workbench hosted in SharePoint. Refresh the page and add the HelloWorld web part. You should see lists returned from the current site." It's probably something I've overlooked, but can't seem to find how to do this. All I got is the local Workbench, hosted after running 'gulp serve'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint#retrieve-lists-from-sharepoint-site)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This was shown in a previous doc on the first "getting started" page here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part-in-sharepoint

The hosted workbench is found in every SharePoint Online site. Navigate to a SharePoint Online site & add to the end of the URL `/_layouts/workbench.aspx`. Assuming you are still running the local web server from executing `gulp serve`, you will be able to test your web part in the hosted workbench in SharePoint Online.

**Comment by TroyHostetter** [comment]
Looks like it works on-prem too :)  http://sp2019.mydomain.net/sites/TroyTest/_layouts/15/workbench.aspx
