### ISSUE TITLE
Error: "The SharePoint Online Web Application Service Principal hasn't been provisioned yet."

### ISSUE THREAD

**Issue by haugan** [SharePoint/sp-dev-docs#3155]
If I didn't do something terribly wrong, this is the error message I get in my console log from following this tutorial - when trying to search for a user with the AAD client, in the new Web Part from my local Workbench.

Error: "The SharePoint Online Web Application Service Principal hasn't been provisioned yet. Please contact your Tenant Administrator."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-base-web-part-elements)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by lahuey** [comment]
Hi @haugan,

This is expected behavior, as the local workbench uses mock data for rendering web parts. I would recommend using the online hosted workbench for testing features that integrate with Azure AD/Microsoft Graph.

**Comment by mfdezvil** [comment]
Hi @lahuey , I have same problem and I'm testing tutorial with online hosted workbench but I've got same error: "The SharePoint Online Web Application Service Principal hasn't been provisioned yet. Please contact your Tenant Administrator". Any idea of what's going on? Thanks in advance

**Comment by devoooo4u** [comment]
I am using the sharepoint workbench but getting the same error.. as @haugan .. I am following this  [MSDN tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial ) 

![image](https://user-images.githubusercontent.com/19596216/53069131-e46afe00-3500-11e9-94eb-36763dc66a77.png)

**Comment by devoooo4u** [comment]
> I am using the sharepoint workbench but getting the same error.. as @haugan .. I am following this [MSDN tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
> 
> ![image](https://user-images.githubusercontent.com/19596216/53069131-e46afe00-3500-11e9-94eb-36763dc66a77.png)

I think its resolved now for my case, It takes some time (30 min or so..) after the permission approval by Tenant admin @lahuey
