### ISSUE TITLE
Filter on multi-value lookup - it's possible?

### ISSUE THREAD

**Issue by nightullr** [SharePoint/sp-dev-docs#3156]
The documentation says: "Because multi-value lookup fields are returned as a string of multiple values, there is no way to query for them (for example, the equivalent of an Includes element or NotIncludes element is not supported)."

However, because the value is described as being returned as a string, and that "substringof" IS supported, I tried this:

"?$filter=substringof('123', MultiLookup/Id)"

where '123' is the ID of the list item I wanted to filter by and "MultiLookup" is the name of my multi-value lookup field. This produced all the correct results in SharePoint 2013 (we are migrating to 2016 very soon). Is this not supposed to work, or have a reason why it isn't "supported" despite being an effective equivalent of Includes?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nightullr** [comment]
I did realize a problem with my original filter, because querying an ID of "1" with substringof will also match "421", etc. However, THIS filter value does work without that effect:

"?$filter=MultiLookup/Id eq '123'"

Even though it's the equal operator, it returns all items in the multilookup field that have only that item selected AND those that _include_ that item among others. And it won't match '1234' like the other one does.

So my original observation remains the same, I think! It works fine if you intentionally want to filter on the expanded multilookup values, if that's the goal... I didn't realize that would work either:

"?$filter=substringof('keyword', MultiLookup/TextField)&$select=MultiLookup/TextField&$expand=MultiLookup

**Comment by SeaDude** [comment]
This is helpful, thank you. Do you know if its possible to filter based on multiple OR's? 
Example: 
?$filter=MultiLookup/Id eq '123' or '234' or '345
I CANNOT find a way to do this! I've tried many iterations. 
Any ideas?

**Comment by andrewconnell** [comment]
You should be able OR statements together, but not like you're doing. You have to repeat each statement... think like a regular `if` statement. For instance:

`?$filter=MultiLookup/Id eq '123' or MultiLookup/Id eq  '234' or MultiLookup/Id eq  '345'`
