### ISSUE TITLE
Site Policy Issue When Applied via PNP Provisioning Template

### ISSUE THREAD

**Issue by TreyKent** [SharePoint/sp-dev-docs#3158]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

"Site Policy" site collection feature can be enabled and local site policies can be created and applied to modern SharePoint Online sites all via a PNP provisioning template.

#### Observed Behavior

In SharePoint Online, the "Site Policies" and "Site Closure and Deletion" sections of Site Settings throw a "Something went wrong error" with a correlation ID (actual error from logs below) after applying a PNP Provisioning Template that enables the Site Policy site collection feature, creates a local site policy and then tries to apply it.  This has been reproduced by a Microsoft support resource in their test tenant, as well as with multiple sites and templates in my tenant.  It appears that the site policy exists as a content type that can be viewed in PowerShell but it is malformed in some way.

Error from logs
Application error   when access /_layouts/15/ProjectPolicies.aspx, Error=Object reference not set   to an instance of an object.

System.NullReferenceException: Object   reference not set to an instance of an object.
Getting Error Message for Exception   System.Web.HttpUnhandledException (0x80004005): Exception of type   'System.Web.HttpUnhandledException' was thrown. --->   System.NullReferenceException: Object reference not set to an instance of an   object.

#### Steps to Reproduce

1. Create a new modern site in SharePoint Online
2. Enable the "Site Policy" site collection feature
3. Create a new site policy via the "Site Policy" section of site settings
4. Apply that site policy via the "Site Closure and Deletion" section of site settings
5. Pull the PNP provisioning template associated with this site via the Get-PnPProvisioningTemplate command in XML format
6. Create a 2nd modern site to match the first one made in SharePoint Online
7. Apply the template to the 2nd site via the Apply-PnPProvisioningTemplate command
8. Attempt to open either the Site Policy or Site Closure and Deletion sections of the Site Settings on the 2nd site

**Comment by ravick4u** [comment]
We have a similar requirement and having the same issue.

**Comment by ravick4u** [comment]
"Site Policies" page under "Site Collection Administration" is also broken

**Comment by ravick4u** [comment]
Looks like this is not possible with SPO(Not sure if it's working with OnPrem). See the comments with below check-in by @jansenbe

_"Commenting out the test for sitepolicy since we've no automated way to push policies to the created site collection"_

https://github.com/SharePoint/PnP-Sites-Core/commit/6a7739d24c2133b49e140301b998b2f7f43834b8#diff-a369f46bc04f5afca5aac2d9ef0c5357

**Comment by ravick4u** [comment]
Sometime back I posted the question on how to create site policy with CSOM and couldn't get any answer.

https://sharepoint.stackexchange.com/questions/248952/create-site-policy-in-sharepoitn-online-with-powershell-csom

Site Policies are actually hidden Content Types and when we export template with "Get-PnPProvisioningTemplate" also exports site policies.

https://github.com/SharePoint/PnP/tree/master/Samples/Core.InformationManagement

Here are my recommendations,
1. Do not export site polices(parent content type of site policies is 0x010085EC78BE64F9478AAE3ED069093B9963). If PnP team agrees that this code should be commented.
2. Option one is going to take some time so in meantime, we should exclude policies from export for e.g. Get-PnPProvisioningTemplate -Out '.\template.xml' -ExcludeHandlers:SitePolicy

**Comment by VesaJuvonen** [comment]
This issue is closed as there has not have been any activity on it within the past 2 months. If the issue is still valid, please submit a new issue with updated details. Sorry for the Inconvenience. We are perform this cleaning operation for all inactive issues in this repository to be able to improve our support model in future.
