### ISSUE TITLE
Error "Server relative urls must start with SPWWeb.ServerRelativeUrl"

### ISSUE THREAD

**Issue by tony-921** [SharePoint/sp-dev-docs#3159]
I got the above error with the example-2. My environment is Share Point Online Classic UI mode.

It seems fixed by changing the 16th line as follows. (no slash)

    var serverRelativeUrlToFolder = 'shared documents';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10e358f-545c-9ff3-89ae-a77643da6dc2
* Version Independent ID: 6c76adbc-bd78-d96e-3cc3-4a67af1afb5a
* Content: [Upload a file by using the REST API and jQuery](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery#RunTheExamples)
* Content Source: [docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... fixing typo...
