### ISSUE TITLE
Webpart loaded multiple times in IE

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#3160]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A webpart and it's external should only load once.

#### Observed Behavior

When loading a sitepage in Internet Explorer the webpart gets loaded multiple times. This also included it's `externals`. Which can cause problems.
![loading in ie](https://user-images.githubusercontent.com/10999128/50334167-b9b3f780-0507-11e9-81c3-3fb0963d2579.png)
(in this example I've added jQuery as external)

I'm trying to load `office.js` into my webpart, but this library can only be loaded once. As a result, my webpart will not start when using IE.

#### Steps to Reproduce

Create a webpart, publish it to a sitepage and open it in IE. The issue doesn't exist when using the workbench.

**Comment by RoelVB** [comment]
This issue is related to https://github.com/SharePoint/sp-dev-docs/issues/1438

In my opinion it is really a bug that should be addressed as long as IE is still a widely used browser.

**Comment by patmill** [comment]
Is this specific to IE?  Looking into a separate issue where webparts are getting loaded multiple times on a partial-page-navigate

**Comment by RoelVB** [comment]
Yes this is IE specific.

**Comment by andrewconnell** [comment]
I noticed the other day Microsoft stated the there are known issues with IE11 & the workbench that they do not plan to address (ref: #2892). 

It looks like this is the case from your screenshots. Can you try another browser to eliminate if it's limited to IE11?

**Comment by RoelVB** [comment]
Yes. It is limited to IE (not sure if it's only IE11).
But it's not just the workbench.

**Comment by kemesfun** [comment]
@RoelVB  I am not able to repro this issue as I only see one script file when I upload a webpart. I am using IE11 and using the sitepages. Can you try to and repro this again to see if this still occurs?

**Comment by RoelVB** [comment]
Just checked. Doesn't seem to happen anymore.
