### ISSUE TITLE
Few doubts in site design/scripts

### ISSUE THREAD

**Issue by abulhassanoasis** [SharePoint/sp-dev-docs#3165]
Hi
1. How to add a Calendar and Planner link to left hand menu?
2. how to disable access request settings under site permissions? Just need the checkboxes to be unchecked - that's it.
3. how to remove users from a SP security group that the site creates?
4. how to make a SP security group in a site to be DEFAULT (make default group)?
5. how would you add static links to a QUICK LINKS webpart?
6. how to turn off COMMENTS in the home page of the site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#see-also)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi @abulhassanoasis Can you provide a bit more information on what type of support you are looking for? Site designs and Site scripts currently do not have the functionality that you have addressed in numbers 1-6. However, these can be addressed if you augment the site design using the triggerFlow action and using [PnP](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning) to achieve this. If you follow that link, it will show you how you can incorporate PowerShell into the provisioning process, to fill some of the gaps of site designs and site scripts.
