### ISSUE TITLE
Mac run"yo @microsoft/sharepoint" Error: Missing required file: "config/config.json"

### ISSUE THREAD

**Issue by tangliyong** [SharePoint/sp-dev-docs#3166]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/9368866/50394486-d1ee7580-0798-11e9-8d27-a5dbf25ac5ed.png">

**Comment by StfBauer** [comment]
Seems like you have a `.yo-rc.json` in the parent directory that causes this issue.
Can you please post the content here?

![screenshot 2018-12-24 at 12 54 09](https://user-images.githubusercontent.com/5503835/50398846-2125ad80-077b-11e9-8915-a6fbe69812d6.png)

So the lines hear basically says it tries to redirect the project root to a folder named "tangliyong", which may not contain the 'config/config.json' file

If you previously created a project in the same parent folder using the "Create solution folder" option this might be the cause of this error.

**Comment by VesaJuvonen** [comment]
Hi @tangliyong, can you come back on the question from @StfBauer around the content of yo-rc.json. Thx.
