### ISSUE TITLE
navigate  /open folder in  sharepoint  document  library in modern  view 

### ISSUE THREAD

**Issue by heshambadawy** [SharePoint/sp-dev-docs#3167]
I have  built  a tree  in document library   for  all  folder  and  their  sub_ look  like  one in left  side  of  windows_  ....   my question is   i  want when  i  click on  any  tree  node it  open  it's corresponding   folder  in  document library  without   refresh  the  page  i  want  to  perceive single  page behavior  or   the  question could  be  what  function  it  been   used  to  navigate  between  folders in document library  in  modern  view .

**Comment by VesaJuvonen** [comment]
Seems to be answered with @AlinaLishh, so closing in here.
