### ISSUE TITLE
Cannot find module '@microsoft/sp-build-web

### ISSUE THREAD

**Issue by Murthychitturi** [SharePoint/sp-dev-docs#3169]
Cannot find module '@microsoft/sp-build-web'

after running "npm i" got below information.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Can any one help on this please?

**Comment by AlinaLishh** [comment]
There are a few things missing if you don't have python installed correctly - you will probably find error messages if you scroll far enough back but you can easily miss them. Having got to this stage it may be easier to fix the missing dependencies:
npm install --save-dev @microsoft/sp-build-web
Failing that, make sure you have everything mentioned under "Set up your machine", delete the old helloworld-webpart folder and then create a new one and use Yeoman to re-create everything.

Reference from:

[gulp error : Error: Cannot find module '@microsoft/sp-build-web' #15](https://github.com/SharePoint/sp-dev-docs/issues/15)

**Comment by andrewconnell** [comment]
Please reply with your platform, version of Node.js & SPFx version... hard to troubleshoot the information provided @Murthychitturi

**Comment by Murthychitturi** [comment]
Thank you!!
