### ISSUE TITLE
Communication and Team site(Modern) in SharePoint Server 2016

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#3170]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
Is it possible to create communication and modern team site collection in SharePoint 2016 On-Premise? I have upgraded my farm with sep, 2018 update but I still dont see these sites when I create site collection. Is it supported at all?

**Comment by louyy** [comment]
Perhaps you can review the following links for reference:[Team Sites vs. Communication Sites in SharePoint Online](https://www.psclistens.com/insight/blog/team-sites-vs-communication-sites-in-sharepoint-online/)
[Communication Site vs Team Site](https://techcommunity.microsoft.com/t5/SharePoint/Communication-Site-vs-Team-Site/td-p/84148)

**Comment by nikskhubani** [comment]
Thanks @louyy for your reply, I actually know the diff between them. My question is can I create the Modern sites in SharePoint Server 2016 Farm or not? I know i can do it in 2019 farm.

**Comment by VesaJuvonen** [comment]
Communication and modern team sites are features in SharePoint Online or in SharePoint 2019. They are not available in the SharePoint 2016 platform.

**Comment by nikskhubani** [comment]
Thanks Vesa, got it. One last question, is it possible to create modern page in SharePoint 2016?

**Comment by VesaJuvonen** [comment]
No - that's not possible as modern experiences were released with SharePoint 2019, not with SharePoint 2016.
