### ISSUE TITLE
Fix Microsoft Online Services PowerShell Module x64 link

### ISSUE THREAD

**Issue by ltdu** [SharePoint/sp-dev-docs#3171]
Currently "Microsoft Online Services PowerShell Module" x64 link redirects to "Microsoft Connect Has Been Retired" page. This should changed to actual download page as is with 32-bit version.

I have determined this should be this link: https://bposast.vo.msecnd.net/MSOPMW/Current/amd64/AdministrationConfig-en.msi. However, I think there should be "normal" permalink in case content is moved to another location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by AlinaLishh** [comment]
Have you checked this link: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in

**Comment by ltdu** [comment]
Yes. In fact my issue is exactly with this page. There are two links to download "Microsoft Online Services PowerShell Module", however, only link for 32-bit version works.
