### ISSUE TITLE
Webhooks issues in SP 2019

### ISSUE THREAD

**Issue by jcgonzalezmartin** [SharePoint/sp-dev-docs#3172]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Webhooks working on SP 2019

#### Observed Behavior
Webhooks are supposed to work in SP 2019, but we (I'm working in a SP 2019 book with some other MVP fellows) have not been able to have them working. Attached you can find the description of the issues we have found...basically we are not able to create the required list subscription...Could it be possible to have some kind of guidance / sample doc here? 

#### Steps to Reproduce

We have attached a document describing the steps followed to créate a Webhook in SP 2019 and the errors we are getting.

[Webhooks Issues.docx](https://github.com/SharePoint/sp-dev-docs/files/2713120/Webhooks.Issues.docx)

**Comment by louyy** [comment]
Perhaps you could review the following link for reference:[Overview of SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks)

**Comment by jcgonzalezmartin** [comment]
Thanks...the problema of that official documentation is that is SharePoint Online specific and not focused on SP 2019 so it's really difficult to dig into any problems we can face when trying to implement a webhook for SP 2019
