### ISSUE TITLE
TypeError: Cannot read property 'aadHttpClientFactory' of undefined

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-dev-docs#3190]
Hi,
I am following the [tutorial ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient) in connecting Azure AD with my sharepoint solution.
My current `@microsoft/sp-http` version is 1.7.1
`import { AadHttpClient, HttpClientResponse } from '@microsoft/sp-http';`
`private test(){
    this.context.aadHttpClientFactory
     .getClient('ID')
     .then((client: AadHttpClient): void => {
        //API
     });
  }`
However it gave me
> Uncaught (in promise) TypeError: Cannot read property 'aadHttpClientFactory' of undefined

Thanks in advance to anyone who may be able to help:)

**Comment by patmill** [comment]
So, chances are you have a bug in your code, and you haven't correctly bound the test() function to the current object (and thus the "this" property isn't the normal one for the object).

What does your code look like when you call test()?

**Comment by VesaJuvonen** [comment]
hi @Lilian1331, can you provide the code sample as requested by Pat while back. Thx.
