### ISSUE TITLE
Rest API call to CreateAnonymousLinkForDocument does not work with bearer token.

### ISSUE THREAD

**Issue by TracyGH** [SharePoint/sp-dev-docs#3192]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
According to the 1st FAQ in Vesa's blog posting about the [External sharing API for SharePoint and OneDrive for Business](https://blogs.msdn.microsoft.com/vesku/2015/10/02/external-sharing-api-for-sharepoint-and-onedrive-for-business/#comment-34945), the API's should be accessible with a valid bearer token (see below).  
Or perhaps I am misunderstanding his explanation?  
![ss](https://user-images.githubusercontent.com/38665906/50563081-921b1700-0cdf-11e9-969a-66e4add2d510.png)

#### Observed Behavior
However, I get the following error when trying to run the CreateAnonymousLinkForDocument query with a valid bearer token in Postman.  
(The same bearer token and headers work with a search API query to the same SharePoint tenant in another Postman tab.)
![ss](https://user-images.githubusercontent.com/38665906/50563174-32713b80-0ce0-11e9-8dab-3ef8fbd9740a.png)

For reference, here are my header values.
![ss](https://user-images.githubusercontent.com/38665906/50563200-559beb00-0ce0-11e9-8746-e11680646b0d.png)

All of the examples I can find successfully implementing a CreateAnonymousLinkForDocument Rest API query, are including the X-RequestDigest (see list below).  But again, my understanding is that should not be necessary.  

- https://sharepoint.stackexchange.com/questions/254950/sharepoint-createanonymouslink-with-rest-api-in-postman (my post)
- https://techcommunity.microsoft.com/t5/SharePoint-Developer/How-to-get-guestaccess-URL-of-on-item-file/td-p/34962
- https://sharepoint.stackexchange.com/questions/197009/how-to-generate-anonymous-access-link-to-a-file-using-rest-api

The error leads me to believe that the request payload is formatted incorrectly, or perhaps needs different labels.  But my trial-and-error experimenting with payload changes has not been successful.

#### Steps to Reproduce

Please see screen shots and description listed above.

**Comment by AJIXuMuK** [comment]
Hi @TracyGH 
I've just tried that and it works fine without For Digest.
The headers are:
<img width="725" alt="screen shot 2019-01-07 at 11 48 15 am" src="https://user-images.githubusercontent.com/17036219/50789855-27835180-1272-11e9-8b67-da8147e3ded6.png">

**Comment by TracyGH** [comment]
@AJIXuMuK - Can you provide a screenshot of the request payload that worked for you?

**Comment by AJIXuMuK** [comment]
Hi @TracyGH 
Here is what I have in the Postman:
![screen shot 2019-01-11 at 3 41 01 pm](https://user-images.githubusercontent.com/17036219/51065032-9a186800-15b7-11e9-98db-ee2c6d9e7821.png)
Postman is authorized using OAuth2 v2.0 endpoints.
Request body is the same as in your example:
![screen shot 2019-01-11 at 3 45 00 pm](https://user-images.githubusercontent.com/17036219/51065100-ed8ab600-15b7-11e9-8d00-150be28ddc51.png)

**Comment by AJIXuMuK** [comment]
I cleaned the cookies (to remove FedAuth) and it still works:
![screen shot 2019-01-11 at 3 51 02 pm](https://user-images.githubusercontent.com/17036219/51065271-de583800-15b8-11e9-9cfc-aa5779ec7c24.png)
