### ISSUE TITLE
Dynamic property required in consuming web part's manifest

### ISSUE THREAD

**Issue by mpowney** [SharePoint/sp-dev-docs#3193]
If you add a dynamic property to the ```propertiesMetadata()``` method like:

```typescript
  protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      'dynamicProperty0': { dynamicPropertyType: 'string' }
    };
  }
```

But don't add a property to the web part's manifest like:
```json
    // preconfiguredEntries node:

    "officeFabricIconFontName": "DocumentSearch",
    "properties": {
      "dynamicProperty0": "",
    }
```

You get an exception raised:
```
Uncaught Error: Serialization failed for web part WebPart.DynamicDataConsumerWebPart.3c797b3b-6634-404c-8772-d09a49f94236.
    at t [as constructor] (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:857)
    at new t (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445)
    at Function.t.create (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445)
    at DynamicDataConsumerWebPart.t._internalSerialize (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445)
    at DynamicDataConsumerWebPart.t._internalSetDirtyBit (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445)
    at sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445
    at sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445
    at Map.forEach (<anonymous>)
    at e._executeForIdsOrAll (sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445)
    at sp-pages-assembly_en-us_c565a80043b8eecd7e332455be57225f.js:1445
```

This seems inconsistent with other web part properties, because they can be in use without them defined as preconfiguredEntries in the manifest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79444829-20bc-3b07-8820-29b55798761a
* Version Independent ID: 546cff82-d871-917e-10ba-55df6f18e5eb
* Content: [Connect SharePoint Framework components using dynamic data](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data)
* Content Source: [docs/spfx/dynamic-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/dynamic-data.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Just to fill in all the data, what does the property definition in the webpart properties interface look like?

**Comment by patmill** [comment]
Sorry, I meant the properties interface that you use in the webpart.  Something like "IDynamicDataConsumerWebPartProps"

**Comment by mpowney** [comment]
Oh right yes, this is what the props interface looks like:

```typescript
export interface IDynamicDataConsumerWebPartProps {
  dynamicProperty0: DynamicProperty<string>;
}
```

**Comment by patmill** [comment]
Ah, right.  To work around this, you'll want to create the dynamicProperty object in your interface.  Something like this:

```
      protected onInit(): Promise<any> {
      if (!this.properties.dynamicProperty0)
      {
         this.properties.dynamicProperty0.setValue('Here is some default content');
      }
      return Promise.resolve();
     }
```

**Comment by mpowney** [comment]
Cool thanks @patmill.  

I think it would be helpful to update this issue's content source (docs/spfx/dynamic-data.md) to explicitly call out the step of adding this code to onInit(), or filling out the .manifest.json, to avoid others spending time debugging the ```Serialization failed for web part``` exception.  What do you think?

**Comment by VesaJuvonen** [comment]
Noted on the documentation update requirement - added on the backlog. Closing the original issue in here still. Also - if you @mpowney have time, we would absolutely welcome suggested edit on the article updates - Edit button on the page. Thx.
