### ISSUE TITLE
Permissions issue with REST Api and MS Graph using isDomainIsolated:true

### ISSUE THREAD

**Issue by vano76** [SharePoint/sp-dev-docs#3197]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I would expect to be able to make SP Rest calls and MS Graph calls in the same web part that has the isDomainIsolated:true.

#### Observed Behavior

When using the isDomainIsolated:true and using the pnpjs to make list item calls I am getting access denied (403) for the List Items call. It appears that if I remove the isDomainIsolated:true the list call works but obviously the MS Graph call does not work. Is this the behavior that I should expect? 

#### Steps to Reproduce

Create a spfx project and add a MS Graph call and add a SP List Items call and set the isDomainIsolated:true. Deploy the web part and approve the API Management in the CA Admin for your SP Online tenant.

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Have you granted the isolated-domain app the permissions you require?

**Comment by vano76** [comment]
yes, the graph permission works fine but I get access denied for my rest call to a SP List when I have the isDomainIsolated:true. Just to be clear my Graph call is working fine with that setting but getting access denied for another SP List Rest API call using pnpjs. I doesn't matter if I am using that or a standard http client I am still getting the access denied with the isDomainIsolated:true.

**Comment by patmill** [comment]
Just to double check, did you grant the app SharePoint permissions?

**Comment by patmill** [comment]
Possibly.  The other possibility is that you are referencing the wrong domain for your rest calls.  What's the full URL are you hitting?  It is likely either (tenant).sharepoint.com or (isolatedDomain).sharepoint.com.  Try the other one.

**Comment by vano76** [comment]
I think that is probably the issue. I don't fully understand how this would work or what the isolateddomain url would be. I appreciate your help on this if you could point me in the direction of some documentation of examples that would be greatly appreciated. I am using pnp js to make the REST API call so it is using the (tenant).sharepoint.com. I think that would make the most sense since this is using an iframe I think? Are there examples of projects using the isolateddomain with a pnp rest call to a SP List.

```
    const web: Web = new Web('https://mysptenant.sharepoint.com/sites/sitea');
    const links:ISmartLinkItem[] = await web.lists.getByTitle('linkslist').items
```

Thanks again for all of your help with this.

**Comment by patmill** [comment]
Not sure if you deleted a response or if github is behaving weirdly.  At any rate, in your isolated domain you probably want to replace https://mysptenant.sharepoint.com in this line:
`
const web: Web = new Web('https://mysptenant.sharepoint.com/sites/sitea');
`
with 
`
window.location.origin
`

**Comment by patmill** [comment]
So we've recently found an issue with the serialization of the DomainIsolated part that we are working on.  For the MMS scope, out of curiosity, what happens when you simply call the normal JSOM end point with the domain isolated origin?  Otherwise, I'll see if I can track down the taxonomy service scope name.

**Comment by VesaJuvonen** [comment]
hi @vano76, can you reply on Pat's latest question, so that we can process this issue or close it. Thx.
