### ISSUE TITLE
gulp serve error

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#32]
Hi,

When I build the solution throwing below error

Cannot find module 'orchestrator'

 Subsequent variable declarations must have the same type.  Variable 'require' must be of type '{ (path: string): any; (paths: string[], callback: (...modules: any[]) => void): void; resolve: (...', but here has type 'NodeRequire'.

**Comment by patmill** [comment]
I think we're missing some context here.  What solution are you building?  How did you make it?  Are you following one of the tutorials?

**Comment by bvdinesh** [comment]
Hi,

I have followed steps to create "HelloWorld WebPart" and configured node.js

Version  - v5.10.1
Platform - 64bit Windows

Opened solution on Visual studio code. but when I build (Ctrl+Shift+B) below error showing

![image](https://cloud.githubusercontent.com/assets/21132206/17823831/4289f62a-6624-11e6-9cba-fc3f137413dd.png)

**Comment by StfBauer** [comment]
Node Version 5.10.1 is a Beta version but you need to use LTS which is currently version 4.5.0.
https://nodejs.org/en/download/

**Comment by bvdinesh** [comment]
Thank you . it worked.
