### ISSUE TITLE
SPFX webpart not visible When trying to add to the "Add App" in SharePoint 2016 on premise environment

### ISSUE THREAD

**Issue by kbkotresh** [SharePoint/sp-dev-docs#3200]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
Steps to reproduce :  below Packages are installed in the Local environment.

+-- @microsoft/generator-sharepoint@1.7.1
+-- gulp@4.0.0
+-- npm@3.10.10
`-- yo@2.0.5

step 2:  Create sample webpart 
3. Bundle --ship 
4. pacakage- solution 
5. add json files from Temp/deploy to my CDN path.
6. Upload the Package from SharePoint\Soluiton to App catalog in SP2016 
7. Naigate to Other Web application and Try to Add webpart in Site contents.
8 Not able to see the webpart in the "Add app"
![image](https://user-images.githubusercontent.com/12246218/50677701-4939ca00-1021-11e9-8b85-082910726663.png)

 Reference URL : https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support

**Comment by kbkotresh** [comment]
hi , 
As per the reference url I have uninstalled the current version of @microsoft/generator-sharepoint and installed the generator as below.
+-- @microsoft/generator-sharepoint@1.0.2
+-- @microsoft/sp-build-web@1.7.1
+-- gulp@4.0.0
+-- npm@3.10.10
`-- yo@2.0.5
When i create the Sample webpart i am getting below Error message. Please help to resolve the issue 
![image](https://user-images.githubusercontent.com/12246218/50678636-a5065200-1025-11e9-94db-30bda853924f.png)

**Comment by kbkotresh** [comment]
hi , 
Above issue is resovled by running the below command
![image](https://user-images.githubusercontent.com/12246218/50685089-e30f7000-103d-11e9-85a8-a9e20063696e.png)

But still App is not visible in the App http://Sitecollection/_layouts/15/addanapp.aspx url
Kindly let me know how to resolve the issue

**Comment by iamguptarishi** [comment]
I think SharePoint 2016 does not support spfx v1.7. It only supports v1.1. As per the documentation:-
SharePoint 2016 Feature Pack 2 supports SharePoint Framework client-side web parts hosted on classic SharePoint pages built by using the SharePoint Framework v1.1.0. This means that when you are targeting the SharePoint 2016 platform, you need to use the SharePoint Framework v1.1.0 due to the server-side version dependencies.

Also SharePoint 2019 supports 1.4.1 version. Here are the release notes. https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.7-release-notes

**Comment by kbkotresh** [comment]
hi @iamguparishi,
Yes I have updated with SP2016 feature pack 2 and based on the documentation https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support
I have changed the generator to 1.0.2 and able to do gulp serve. 
but when I added the package to SP2016 app catalog . When trying to Add App its not showing up in the list of apps. 

Kindly let me know how to resolve this issue .

**Comment by iamguptarishi** [comment]
Do you have your code available anywhere, so that I can check?

**Comment by kbkotresh** [comment]
hi
sorry , please find the attached package file 

[testsp-2.zip](https://github.com/SharePoint/sp-dev-docs/files/2731602/testsp-2.zip)

**Comment by kbkotresh** [comment]
> Do you have your code available anywhere, so that I can check?

hi
sorry , could not upload full src code .  please find the attached package file

[testsp-2.zip](https://github.com/SharePoint/sp-dev-docs/files/2731654/testsp-2.zip)

**Comment by andrewconnell** [comment]
@iamguptarishi 
> SharePoint 2016 does not support spfx v1.7. It only supports v1.1.

Correct, but the latest generator can be used to create projects for SP2016 as it adds the correct dependencies.

@kbkotresh When you deployed to the app catalog, did it show any errors with the package you uploaded after clicking **Deploy**?

Furthermore, two more questions/observations:
- what version of NodeJS are you running? (`node -v`)
- you're using a very old version of NPM... suggest you update NPM.

**Comment by manlamcheng** [comment]
I have a similar situation, but it's for SharePoint online, 
before upgrading to SPFx 1.8, deployed apps are visible and can be installed
after upgrading, deployed apps (webparts, extension) are not visible at all.. 

please advice 

thanks

**Comment by ValerasNarbutas** [comment]
> before upgrading to SPFx 1.8, deployed apps are visible and can be instal

Same for me
