### ISSUE TITLE
UI: Search box z-index

### ISSUE THREAD

**Issue by pjwise** [SharePoint/sp-dev-docs#3207]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Search box should be behind other OOTB UI elements/flyouts

#### Observed Behavior

Search box sits above OOTB UI elements/flyouts

#### Steps to Reproduce

1. Create a new communication site
2. Click on your profile image to bring up the flyout
3. Observe that the search box sits on top of this flyout
![image](https://user-images.githubusercontent.com/13385225/50700179-dd9f2f00-1017-11e9-831f-a2b2571de304.png)

I'm not sure if this is the correct place to file this issue but it's definitely a problem with modern pages and I'm having to work around it in my SPFX webparts/extensions so I think it's relevant.

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we can't, unfortunately, process this inconvienet behavior using GitHub channel. If this is still an issue, please report it using the tenant admin support channel. Thx.
