### ISSUE TITLE
Failure:Share.title was not found on the data object.

### ISSUE THREAD

**Issue by spidersbite** [SharePoint/sp-dev-docs#3208]
Error message:
_Failure:Share.title was not found on the data object._

I'm guessing it means that I have not pulled in the title correctly. I am using the format indicated in the Github documentation. "txtContent": "@currentField.title"

Are there cases in which this would not work?

Here is my code: 
{ "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json", "debugMode": true, "elmType": "div", "children": [ { "elmType": "a", "attributes": { "target": "_blank", "href": { "operator": "+", "operands": [ "https://mysharepointsitename.aspx?ListItemId=", "[$ID]" ] } }, "txtContent": "@currentField.title" } ] }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
@spidersbite thanks for the question! What type of column is this? the `@currentField.title` is intended only to pull back the display name of a Person field. If this isn't a person column, then this won't work.

If you are trying to pull back the Title column as the text value, then if this is the Title column where you are applying the format you can simply use `"txtContent":"@currentField"`. If this is another column where you want to reference the Title column you can use `"txtContent":"[$Title]"`

You can find out more about these special strings and referencing other columns in this section: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#special-string-values

**Comment by thechriskent** [comment]
@spidersbite thanks for the additional info!

Formats on a column can reference any other columns in the view (so no need to put it on the Title column unless you want to). The `Title` column is actually a special case where it can be referenced even when it's not part of the view! So you can remove it from the view and use another column to apply your format. If you want a format only column, you can see a demonstration of that on my blog here: https://thechriskent.com/2018/08/29/list-formatting-quick-tip-format-only-columns/

So, you could adjust your format like this (can be applied on either the `Title` column or another one):
```json
{
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json", 
  "elmType": "div",
  "children": [
    {
      "elmType": "a",
      "attributes": {
        "target": "_blank",
        "href": "='https://mysharepointsitename.aspx?ListItemId=' + [$ID]"
      },
      "txtContent": "[$Title]"
    }
  ]
}
```

Please let us know if that works or if there are any other questions, thanks!

**Comment by spidersbite** [comment]
Thank you, that worked in the Title field!
