### ISSUE TITLE
SPFx Version Support

### ISSUE THREAD

**Issue by spjeff** [SharePoint/sp-dev-docs#3214]
How can we query a SharePoint 2016/2019 server for the max SPFx supported version?

Above says "v1.1" for SP2016.   However, I assume this is higher with CU patching or SP2019 server.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1320b802-156c-5d77-db79-b211b66d4b2f
* Version Independent ID: efe018a3-001e-e097-a96c-66ab1786afe5
* Content: [SharePoint Framework development with SharePoint 2016 Feature Pack 2](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support)
* Content Source: [docs/spfx/sharepoint-2016-support.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-2016-support.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
No, 2016 remains at 1.1, and 2019 will remain at 1.4.1 (but no beta features, so really closer to 1.4.0)
