### ISSUE TITLE
Very slight issue with the link name (being picky!)

### ISSUE THREAD

**Issue by MattBrowne1** [SharePoint/sp-dev-docs#3215]
The line that reads:
"Click on the "Azure AD" link that is available under the "Admin centers" group...."
Should say "Azure Active Directory" because that is what the exact link is.  It's a small thing but as it's in quotes I thought I would mention it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... good catch. I've included in a PR with other docs fixes so it should be rolled into the docs in an upcoming update.
