### ISSUE TITLE
Documentation for office ui fabric react

### ISSUE THREAD

**Issue by Edward-Adamson** [SharePoint/sp-dev-docs#3217]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Support documentation for ui fabric core versions released with the spfx react creation template

#### Observed Behavior

Available documentation is only for current Office Ui Fabric, the one shipped with spfx react solutions is several versions earlier

#### Steps to Reproduce

I am using UI Fabric to style my spfx WebParts using the React generator and seem to be having a problem finding reliable documentation for the ui office fabric version.

In my dependencies I have: 
@microsoft/sp-office-ui-fabric-core": "1.7.1"

[spfx on react ui fabric](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components#add-an-office-ui-fabric-component)
>we recommend that you use the Office UI Fabric and Fabric React that ships with the generator.

The current [documentation](https://developer.microsoft.com/en-us/fabric#/components) seems to be targeted at: Fabric Core 9.6.1 and Fabric React 6.119.0 

Is there anywhere I find the documentation to the version of Fabric supplied with the spfx react solution?

Specifically I was trying to add placeholder text to a <Dropdown /> component, the current documentation says use `title` props and said that `placeHolder` is deprecated. The code examples use `placeholder` which is what i originally tried but doesn't work in my react spfx solution as it is case sensitive. `placeHolder` is the one that currently works for this.

I am concerned that as I get further into the application I am going to run into more annoyances like this

**Comment by patmill** [comment]
Thanks @Edward-Adamson - Closing the issue here as it will be tracked and handled in the fabric react repo.

**Comment by Jahnp** [comment]
Just to follow up here, we're tracking adding versioned documentation like this in [this issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/7269).
