### ISSUE TITLE
Cannot position absolute element in custom web part over OOB component

### ISSUE THREAD

**Issue by steevinBradlee** [SharePoint/sp-dev-docs#3218]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm trying to create a search box with an absolutely positioned (via CSS) dropdown which will appear over any content below the search box.

#### Observed Behavior

Any components below my custom component appear in front of my absolutely position element. Changing the z-index, position, opacity, seems to have no effect. Below you can see that the document library and people web parts sit in front of the dropdown (which has position: absolute) for the search box.

![image](https://user-images.githubusercontent.com/6978368/50915390-b6c16e00-1406-11e9-9af8-7ba7901c61d1.png)

#### Steps to Reproduce

- Create a custom component with an absolutely positioned element.
- Place a web part below this component and notice that it will appear in front of the absolutely positioned element.

I think the issue could be related to the animation on the web part zones, specifically the element with this class "Canvas-slideUpIn", which has two animations. One of the animations changes the Z coordinate of the element which I think cause all of the components to exist in CSS 3D space, placing them in front of any absolutely positioned elements.

Was wondering if anyone has experienced this behaviour or has any solutions.

**Comment by araver** [comment]
I don't know if this is a long term fix, but I was able to fix it this way. 
Webpart.ts
```Typescript
let wrapper = jquery(this.domElement).closest(".Canvas-slideUpIn");
wrapper.addClass(styles.transitionFix);
```

Module.scss
```css
.transitionFix{
  opacity: 1 !important;
  animation-name: unset;
}
```
To ensure that the class is on the DOM element and also keep the animation, I only execute the code when the absolute/fixed positioned element shows up.

**Comment by assadarram** [comment]
Thanks Araver i will try this as soon as possible.

**Comment by steevinBradlee** [comment]
Thanks @araver, let me give it a try and get back to you :)

**Comment by steevinBradlee** [comment]
Your fix worked for @araver . I wonder if this should be recognized as a bug?

**Comment by assadarram** [comment]
It worked for me too. I needed to do som changes  because i am using ReactDom.render. This should be a temperary fix until what i think is a bug is fixed

**Webpart.ts**
public render(): void {
        ReactDom.render(element, this.domElement);
  }

**Module.scss (the same)**
.transitionFix{
  opacity: 1 !important;
  animation-name: unset;
}
**webpart.tsx** and after  componentDidMount()
let wrapper = jquery(this.props.context.domElement).closest(".Canvas-slideUpIn");
wrapper.addClass(styles.transitionFix);

**Comment by VesaJuvonen** [comment]
Technically this is not recommend solution as you should not do dom manipulation to hide or change out of the box elements. Seems also that the solution has been already provided if you chose to do this regardless, so we are closing this issue.
