### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sudeepg100** [SharePoint/sp-dev-docs#322]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Successful navigation from https://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment to https://dev.office.com/sharepoint/set-up-your-developer-tenant

#### Observed Behavior
The documentation for SPFramework which is preview has a section named Setup your Office 365 Tenant at https://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment, but clicking this link takes to a page where it says "Page not found"
https://dev.office.com/sharepoint/set-up-your-developer-tenant

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
thx sudeepg100 for reporting. Link fixed now.
