### ISSUE TITLE
CSS Class renaming (Auto appending Unique hash value)

### ISSUE THREAD

**Issue by yatin1155** [SharePoint/sp-dev-docs#3220]
By renaming the file name from example.module.scss to example.scss, compiler not only gives the warning but also error out by saying scss file not found.

Resolution:
change import styles from './example.module.scss'; to require('./example.scss'); 

Reference:
https://n8d.at/blog/how-to-handle-automatic-css-class-renaming-in-spfx/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2c8e90-d70c-a674-9045-a5f1721cf5fb
* Version Independent ID: 83818137-f675-37c5-ea98-5e852d0bcc15
* Content: [Recommendations for working with CSS in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/css-recommendations)
* Content Source: [docs/spfx/css-recommendations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/css-recommendations.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That's expected... if you change the file it's referencing but not rename the file, it will break as the file you're referencing with a new name doesn't exist.
