### ISSUE TITLE
Unclear: "Navigate to the developer site and add the app. Click on App Details"

### ISSUE THREAD

**Issue by ejschoen** [SharePoint/sp-dev-docs#3223]
I think I followed steps 1-4 correctly, but step 5 is not clear.  I clicked "new app to deploy," uploaded the .app file, and got the error that my tenant administrator must approve.  Now what?  The app is not visible on the "developer site."  It is in the App Packages library.  A more detailed walkthrough here would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a36ebb-4574-73c7-e927-488025b980fb
* Version Independent ID: 2cfe998d-fafc-7559-1b6b-7737def6ec36
* Content: [Developing using Tenant permissions with App-Only in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online)
* Content Source: [docs/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like the doc was updated since this feedback was submitted as the doc has instructions for the admin to approve the request.
