### ISSUE TITLE
Employee orientation calendar not available to select

### ISSUE THREAD

**Issue by mahimapspl** [SharePoint/sp-dev-docs#3224]
Not able to see Employee orientation calendar in the drop down for :
"Which particular item is the custom action scoped to?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66525fc-a185-f7c8-814d-97bf1ea6d658
* Version Independent ID: b1bdd159-cae7-0ba3-a959-7f09546695e2
* Content: [Create a custom ribbon button in the host web of a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-custom-ribbon-button-in-the-host-web-of-a-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/create-a-custom-ribbon-button-in-the-host-web-of-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-a-custom-ribbon-button-in-the-host-web-of-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by piotr-kasprzyk** [comment]
"Important

The next procedure requires that the calendar be visible in the UI of Visual Studio, but it won't be if Visual Studio was open when you created the calendar. Before you continue, close Visual Studio, and sign out of any browser windows and PowerShell consoles where you are signed in to your developer site." ;-)
