### ISSUE TITLE
Updating a list item value via field customizer does reinitiliaze the field customizer

### ISSUE THREAD

**Issue by SvenLauterbach** [SharePoint/sp-dev-docs#3228]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When updating a list item value from a field customizer the field customizer does not get reinitialized.

#### Observed Behavior

When updating a list item value from a field customizer the field customizer does get reinitialized.

#### Steps to Reproduce

Create a field customizer which increases a number value when the user clicks a Button in the field customizer. After posting the update via PnPJs, the field customizer gets reinitliazed. 

My question is, is this behavior right? It causes some flickering, because when the field customizer is reinitialized it pops up with a animation.

I will try to provide an example project via GitHub.

**Comment by SvenLauterbach** [comment]
Just a little demo gif
![error](https://user-images.githubusercontent.com/1760777/50903706-cc429200-141e-11e9-8488-06965e78f95b.gif)

In the demo, the field got reinitialized every second click (strange, in my other project its on every click). I uploaded the demo project here: https://github.com/SvenLauterbach/Demo-FieldCustomizer

**Comment by patmill** [comment]
My _guess_ is that the following is happening:
+ You are in view mode
+ When you click "increase", you change the UX and fire an update to the server saying "set the field value to X+1"
+ The "live update" feature on the list detects a change on the server, and rerenders the list view

One way to possibly avoid this is:
+ don't update the value in the UX, and instead change "increase" to "updating..." and wait for the live update to kick in.

I think the main thing is a desire for edit support.

**Comment by SvenLauterbach** [comment]
I will try to implement it and give feedback on it later today.

**Comment by SvenLauterbach** [comment]
Ok, I tried the suggestion, seems to work with the live update (i added a kind of a loading "animation"). However, after the live update happens there is for < 1s the old state visible. I have to check if this has something todo with the way I render the react component.

![heart](https://user-images.githubusercontent.com/1760777/51106563-696d4400-17ec-11e9-9276-ad6a0fb1a774.gif)

**Comment by SvenLauterbach** [comment]
Just a quick question, was the live reload feature disabled? Is there a way to determine if this feature is enabled? The proposed solution does not work anymore....I have to reload the page now or use the implementation from before.
