### ISSUE TITLE
App installation giving error on site in SP 2019

### ISSUE THREAD

**Issue by chadhav** [SharePoint/sp-dev-docs#3229]
Hello,

My project is sitting at d:/abc. I deploy the cdn files to the required folder and my .sppkg to the app catalog. Everything works fine till now, the moment i try to add the app from the app catalog it gives me error:  Sorry, something went wrong with adding the app. Checked the details in the App Failure it says:

There was a problem accessing the file system on the server.
Details: Deployment failed in host web http://sitecollection/sites/abc for app abc/xxxxxxxxx. System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths) at System.IO.Path.InternalGetDirectoryName(String path) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractToWspLocation(SHA256Managed sha, PackagePart packagePart, TemporaryDirectory wspTempDir, String destWspRelative) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractElementPartToWsp(PackagePart elementPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance, Guid featureId, String featureWspRelativeDirectory) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartToWsp(SPFeatureAppPart featureAppPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartsToWsp(List`1 featureAppParts, SPWeb web, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.GenerateAndActivateUserSolutionFromPackage(SPWeb web, SPAppPackage appPackage, Guid productId, String solutionName, SPSolutionLevel solutionLevel) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.InstallOrUpgrade(SPSite site, Nullable`1& solutionId, Boolean& swapNeeded)

As mentioned I am running my solution from d:/abc. Please suggest what is causing this issue.
Thanks very much!

**Comment by VesaJuvonen** [comment]
Based on the exception, the issue is related to the file lengths on the feature xml files in side of the sppkg file. You should be able to determine the issue either by renaming the sppkg file as a zip file and then opening to see what folder or file is a long one... or then having a look on the solution/debug folder after you have executed *gulp package-solution --ship*. Without having access on the sppkg file, this is the best we can do... 

Were you able to solve this or can you share the solution for us to have a look?

**Comment by chadhav** [comment]
Thanks very much for reverting back to my problem. I am facing this issue with any spfx extension on my server (here i have created a application customizer). Attached herewith is the sample .sppkg file contents in zip format. It has no special coding, its a default application customizer with a message box. Your help will be greatly appreciated to resolve this issue. Is this issue related to npm or gulp, please suggest. Thanks very much!!!
[sample.zip](https://github.com/SharePoint/sp-dev-docs/files/2742788/sample.zip)

**Comment by chadhav** [comment]
Please suggest if you get the chance to look into the issue of attaching app error. Previous comment has the .sppkg file attached. Thanks!

**Comment by GrahamMcMynn** [comment]
As this does not repro online it is unfortunately specific to your environment (and perhaps the path you have sharepoint installed in).  Since it is on prem there is nothing we can do and you should open up a support ticket.
