### ISSUE TITLE
addSiteColumn missing under createSPList

### ISSUE THREAD

**Issue by MikeBass13** [SharePoint/sp-dev-docs#3232]
The addSiteColumn subaction documentation is missing under the createSPList action. It is listed in the actual schema and is used in some of the reference samples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#create-a-new-sharepoint-list)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by iamguptarishi** [comment]
In the documentation it is mentioned under the addSiteColumn details.

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#addsitecolumn

Actual content from the doc:-
**addSiteColumn**
Subaction to add a previously defined **site column directly to a list** or content type (existing or created through the site script).

**Comment by MikeBass13** [comment]
Correct but that is a subheading of "Define a new content type (createContentType)" which actually is listed in the document after "Create a new SharePoint List". I agree is covered but not clear. I would think that I could find all the subactions for createSPList "Create a new SharePoint list". Is that not the intent?

**Comment by bcameron1231** [comment]
I can see both sides. I can see the scenario where someone would be adding a site column without adding a content type... in which case,  it'd be nice to know that addSiteColumn is a valid subaction for a list, without having to look at the JSON schema. 

How would you like it represented? Would it suffice to have the subAction listed under the list, but instead of the addSiteColumn definition, it's just a link to the addSiteColumn section lower in the page?  @seansquires  what do you think about this?

**Comment by MikeBass13** [comment]
In this case (i.e. for addSiteColumn), I think it belongs in both places because it has different properties on list than it does on content types (i.e. list one has addToDefaultView, and content type doesn't). 

I'm not sure if everyone uses this doc like I do but I don't generally read it through, so when I jump to a section I am assuming it has all the subactions. I'm not sure how I would know that some action is defined in another section (other than reading it fully every time). I know it causes duplication which is difficult to update but I don't see another way. Maybe I should just stick to looking at the schema. :)

**Comment by MikeBass13** [comment]
@bcameron1231 in cases where identical actions are duplicated I actually like your last point to avoid the duplication. I.e. Write it in one place and just have a stub in others pointing to it.

**Comment by bcameron1231** [comment]
Ya I agree. Let me see if I can come up with a nice/clean way to do that to make the document a bit more clear.

**Comment by MikeBass13** [comment]
@bcameron1231 I attempted the update for addsitecolumn portion but it wouldn't merge that back in ("Merge is blocked. he base branch restricts merging to authorized users..."). Does that go to someone for review? Sorry, I'm new here :)

**Comment by bcameron1231** [comment]
Yes. You can submit a PR and then it will get reviewed and approved first. So the merging is blocked until MSFT merges it in.
