### ISSUE TITLE
How can i use Semantic Slots in SPFX Webpart

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3237]
I have used theme in Webparts, but is there any documentation on using semantic slots

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec15970-7fbb-279f-aba9-4090256c5c7b
* Version Independent ID: 9a97664c-85b4-f1fa-728c-8e56355880f9
* Content: [Designing for section backgrounds using semantic slots](https://docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots)
* Content Source: [docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/design/semantic_slots.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
We are working on a sample and updated documentation for this one.

**Comment by harshdamaniahd** [comment]
@VesaJuvonen  Thanks.
Looking forward for this.

**Comment by heinrich-ulbricht** [comment]
Uhm, is there any news on this topic? I suppose there is a sample out there waiting to be linked? Or is this still to be created?

**Comment by pschaeflein** [comment]
There is some documentation in the [section on section backgrounds](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds). 

Semantic colors are also used in the [Adaptive Cards sample webpart](https://github.com/SharePoint/sp-dev-fx-webparts/blob/886ea3ea88924067f2fde7e550a81be6c790d0d3/samples/react-adaptivecards/src/controls/AdaptiveCard/AdaptiveCard.tsx#L179)

**Comment by heinrich-ulbricht** [comment]
@pschaeflein Better than nothing, thanks ^^

**Comment by harshdamaniahd** [comment]
We have good documentation now 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds
https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html
