### ISSUE TITLE
Site Contents redirects to wrong site when navigating

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#3239]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

This one might not be a dev issue, but I think it's important to be logged somewhere so it gets to the right person. 

When clicking on Site Contents, we should be redirected to the Site Contents page of the current site.

#### Observed Behavior

On some tenants (we could reproduce in at least 2 other tenants), during a browsing session, if using the ASYNC redirect to get to another site (using the Hero WebPart, Quick Links or event custom Extension), when you click the Site Contents menu of the second site, you redirected to the Site Contents of the first site...

_This is something we have found to be critical as it could lead people to delete content in a site they think is the right one and... it's not!_

#### Steps to Reproduce

I added a video, I think it will be easier. But it could be done with anything that redirects withing the SPA of the Page Framework.

https://1drv.ms/v/s!ArrATY5lyKQTjo9HrFD9AofdRWv6Cw

**Comment by VesaJuvonen** [comment]
ack. Not really a dev issue, but reported forward for the feature owners and let's see how we move forward on this one. Most likely a dup with the #3242 on page refresh handling.

**Comment by VesaJuvonen** [comment]
Fix for this has been rolled out worldwide, so closing this one. Unfortunate regression.
