### ISSUE TITLE
SPFx 1.7.1 extension creation doesn't ask framework

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-docs#3240]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Whenever we try to create an extension, it should ask to choose the framework from choices like No Javascript Framework, Knockout and React

#### Observed Behavior

Currently it defaults to No Javascript framework without asking a user to choose the framework of their choice.

#### Steps to Reproduce

1)  Create a new project using SPFx 1.7.1

     Create a new application customizer extension using `yo @microsoft/sharepoint` in an empty solution.

      It will ask for the name and description and create the extension defaulting to No script.

2)  Create a new project using SPFx 1.7.1

    Create a new SPFx webpart based on React Framework

     After that, create a new application customizer in the project. It will ask for extension's name and description and then create it based on the No Javascript framework.

The framework selection popup never appears whenever we try to create the application customizer extension.

**Comment by andrewconnell** [comment]
That's by design... application customers don't have a template for a web framework. They are always just plain old script. Same is true for command sets. Only field customers will prompt you for a web framework (no JS FW / React)
