### ISSUE TITLE
Wrong webparts are shown on page when using browser back-button

### ISSUE THREAD

**Issue by poikjo** [SharePoint/sp-dev-docs#3241]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

User should always see blank frontpage (because it is blank) instead of previous page webparts while using browser back-button. Occurs when browsing back from hubsite.

#### Observed Behavior

Create communication site using blank template --> connect to hubsite --> browse to the hub and come back using browser back-button and you will see webparts in from your hubsite. After a refresh, it will be ok again.

#### Steps to Reproduce

Here's a gif to see what is happening.

[https://onedrive.live.com/?cid=8F1685545B0BA4E6&id=8F1685545B0BA4E6%211599&parId=8F1685545B0BA4E6%21128&o=OneUp](https://onedrive.live.com/?cid=8F1685545B0BA4E6&id=8F1685545B0BA4E6%211599&parId=8F1685545B0BA4E6%21128&o=OneUp)

**Comment by VesaJuvonen** [comment]
ack. Not really a dev issue, but reported forward for the feature owners and let's see how we move forward on this one.

**Comment by VesaJuvonen** [comment]
Most likely a duplicate with #3239 as both are related on modern page refresh handling.

**Comment by VesaJuvonen** [comment]
This might have been fixed already with the changes we applied with #3239. Can you please confirm the status around this one. Thx.

**Comment by poikjo** [comment]
Still seeing the issue.
