### ISSUE TITLE
Bug with Hub Site Navigation - redirecting to hub site when clicking on site contents of associated sites

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3242]
Steps to produce this issue.
1. Create a hub site "Hub"
2. Create another site "AnotherSite" , associate it with hub site
3.Now got to Hub and add links to the Navigation menu (add link of AnotherSite)
4.Now visit Hub, and from navigation visit AnotherSite and then click on SiteContents.You will be redirected to HubSite instead of AnotherSite, Site Contents page.
![issue](https://user-images.githubusercontent.com/11780473/51039312-558bcd00-15b5-11e9-8286-15937b016317.gif)

**Comment by patmill** [comment]
Again - this is outside the scope of this developer-focused issues list.  For product issues, you'll need to open a ticket with support.  Sorry.
