### ISSUE TITLE
Design or Redirection issue with News Webpart -- add news post

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3244]
When you have a news webpart on a site (which is associated to hub)
News webpart settings : 
![image](https://user-images.githubusercontent.com/11780473/51042072-ae5e6400-15bb-11e9-865c-2c27468bcc1c.png)
When you create news post
![image](https://user-images.githubusercontent.com/11780473/51042105-c7ffab80-15bb-11e9-829c-36495e1145de.png)
It doesn't redirect to hub site,instead redirects to existing site.

This is wrong by design , as i am showing news from hub site and when content author clicks to add news he is redirecting to wrong site.
Confusing a lot

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11780473/51042334-4eb48880-15bc-11e9-99c8-45593685a436.gif)

**Comment by patmill** [comment]
This is a product issue, and is outside the scope of this developer focused issues list.  You'll need to open an issue directly with support.
