### ISSUE TITLE
AppForSharePointWebToolkit license information required

### ISSUE THREAD

**Issue by wpomier-devfactory** [SharePoint/sp-dev-docs#3245]
A BlackDuck scan on our software reported the AppForSharePointWebToolkit as without license info.

We couldn't find the license information for it anywhere. The only link we found, searching on the internet, is on [this page](https://www.nuget.org/packages/AppForSharePointWebToolkit/3.1.5), but the link is broken.

Can you help us?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d12c38-1ca0-4720-eb7f-965a624bdee7
* Version Independent ID: eb816ce6-4c6b-3b13-f9af-33adb9c7c961
* Content: [Tools and environments for developing SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/tools-and-environments-for-developing-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/tools-and-environments-for-developing-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/tools-and-environments-for-developing-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by WefNET** [comment]
"As soon as possible" in MSFT parlance, at this point, is greater than 6 months. This is very annoying, because most of us corporate SP developers have to fight with Compliance Officers doing OSS scans. (BTW, there are no non-corporate SP developers.)
