### ISSUE TITLE
SharePoint Online API Management approve permissions

### ISSUE THREAD

**Issue by steevinBradlee** [SharePoint/sp-dev-docs#3247]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm trying to create a spfx web part which will retrieve user details using Microsoft Graph, following this tutorial:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

When I try to approve the api in api management however, I get a 500 error for not having sufficient permissions. What permissions do I need to approve these api requests?

#### Observed Behavior

![image](https://user-images.githubusercontent.com/6978368/51050916-4e0df900-15a0-11e9-8b68-f7bdd3ff5780.png)

#### Steps to Reproduce

Follow tutorial linked above.

**Comment by bcameron1231** [comment]
Hi @steevinBradlee  Per this [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph) at the bottom of the page, tenant administrators can grant permissions for these additional permission scopes.

**Comment by steevinBradlee** [comment]
Thanks @bcameron1231 :)
