### ISSUE TITLE
Cannot use debugLocale in write-manifest.json

### ISSUE THREAD

**Issue by LukasNespor** [SharePoint/sp-dev-docs#3248]
It seems that from version 1.6.0 of Yeoman generator **@microsoft/sharepoint**, it is not possible to use `debugLocale` in **write-manifest.json** file because running `gulp serve` ends with an error. Last working version is 1.5.1

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

```
Build target: DEBUG
./node_modules/@microsoft/node-core-library/lib/JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
./config/write-manifests.json

Error: #/ (Defines configuration options for the...)
        Additional properties not allowed: debugLocale
    at validateObjectWithCallback (./node_modules/@microsoft/node-core-library/lib/JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (./node_modules/@microsoft/node-core-library/lib/JsonSchema.js:193:13)
    at JsonSchema.validateObject (./node_modules/@microsoft/node-core-library/lib/JsonSchema.js:175:14)
    at WriteManifestsTask._readConfigFile (./node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:311:28)
    at WriteManifestsTask.onRegister (./node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:87:32)
    at Object.initialize (./node_modules/@microsoft/gulp-core-build/lib/index.js:299:24)
    at SPWebBuildRig.initialize (./node_modules/@microsoft/sp-build-common/lib/BuildRig.js:61:19)
    at SPWebBuildRig.initialize (./node_modules/@microsoft/sp-build-common/lib/SPBuildRig.js:29:15)
    at SPWebBuildRig.initialize (./node_modules/@microsoft/sp-build-web/lib/SPWebBuildRig.js:15:15)
    at Object.exports.initialize (./node_modules/@microsoft/sp-build-web/lib/index.js:23:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@0.0.1 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-world@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-01-09T16_43_53_070Z-debug.log
```

#### Steps to Reproduce

 1. Created webpart using `yo @microsoft/sharepoint` with default options (using React as Javascript framework)
 2. Added `cs-CZ.js` file to `loc` folder and changed values so I can see that it really grabs the correct file
 3. Added `"debugLocale": "cs-CZ"` to `write-manifests.json` file
 4. Run `gulp serve`
 5. Error occures

**Comment by bcameron1231** [comment]
I've noticed this. It appears the code base inside the sp-build-web was modified and changed from debugLocale to buildSingleLocale.

If you change debugLocale in your write-manifests.json, to "buildSingleLocale" it will work.

@VesaJuvonen Do you know what the real solution is? Is the Schema just out of date or something else?

**Comment by MartyMaro** [comment]
@bcameron1231 "buildSingleLocale" seem to work for the localised files in the `loc` folder. However, the localised entries in the `.manifest.json` will be ignored (i.e. title and description of the WebPart) as well as there is a warning "Property buildSingleLocale is not allowed."

**Comment by bcameron1231** [comment]
That's good to know. I only used the loc files in my testing. And yes, as mentioned, the schema doesn't have this value.  We'll wait to hear from MSFT about the right course of action.

**Comment by bcameron1231** [comment]
@MartyMaro Thanks. If you are talking about the SharePoint Workbench, this is true. The workbench ignores the webpart.manifest.json localization strings, and only uses the default. As for the property, as mentioned it's not in the schema, so you'll have this validation warning.

Let's see what Microsoft says is the right course of action on this.

**Comment by bcameron1231** [comment]
@patmill Do you have any thoughts on this? This could affect people who used debugLocale before 1.6 and are migrating to a newer version of SPFx.

**Comment by cwdata** [comment]
Hi,
I can confirm that this is still not working in SPFx 1.8.2.
Using debugLocale we get an error and buildSingleLocale is simply ignored. We are not using the workbench. We have uploaded the sppkg pointing to localhost to the site collection app catalog.
The only way to debug other languages than en-us is by renaming the language file in the loc folder to en-us.js which is really inconvenient. Why has debugLocale been removed? Can we please get it back :-)

**Comment by srideshpande** [comment]
Hi,
`debugLocale` has been now changed to `buildSingleLocale`. Use the new one instead and try. We're yet to update the json schema online, but that should not stop you from building the project.

If you have already tried the `buildSingleLocale` property, and is not working, then I will get back to you soon on it.

**Comment by cwdata** [comment]
@srideshpande,
it works using `buildSingleLocale` but only if you rebuild and reupload the package. This is a big step backwards compared to `debugLocale` or even `locale=xxx` on the command line which changed the locale directly when running gulp serve. Imagine testing an app with 5 locales using the buildSingleLocale way...

**Comment by andrewconnell** [comment]
To test specific locales with the workbench, start it using the `--locale=xx-xx` flag as shown in this comment: https://github.com/SharePoint/sp-dev-docs/issues/4951#issuecomment-562610290
