### ISSUE TITLE
spo layouts workbench.aspx still trying to load files from local host

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#326]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When using https://your-sharepoint-site-url/_layouts/workbench.aspx
Expected to be possible to run client web part from CDN without running gulp serve

#### Observed Behavior
https://your-sharepoint-site-url/_layouts/workbench.aspx seems to be hard-coded looking for this file from local host:
https://localhost:4321/temp/manifests.js
Although, https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn clearly states: "Notice that you are no longer running gulp serve, and therefore nothing is served from localhost."
This seems to be incorrect.
Opening the workbench shows a warning popup that says "Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running."

#### Steps to Reproduce
Follow this guide up to here: https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn
The only thing I did differently is, I did not use azure CDN. (did not set deploy-azure-storage.json, and did not run gulp deploy-azure-storage).
Instead, I set write-manifests.json to my existing CDN, and copied all files from tmp\deploy to that CDN location.

All my files for my specific project are running from my CDN, but gulp serve must be running since workbench seems to try to load some files from localhost still.

**Comment by shaipetel** [comment]
Correction: just noticed, it is also not loading scripts from my CDN, but instead loading scripts from https://localhost:4321/dist/***.bundle.js

Commands I run:
gulp --ship
(skipped: gulp deploy-azure-storage) <-- did not run this command, instead manually copied to my CDN
gulp bundle --ship
gulp package-solution --ship

**Comment by tortoise386** [comment]
As far as I know - this is by design. The workbench in the cloud offers on-the-fly development with access to the sharepoint instance - but everything is served from localhost.
This is not a bug - but a feature!

Please have a look at this excellent guide to really deploy and test it in sharepoint online:
https://blog.mastykarz.nl/publish-sharepoint-framework-client-side-web-parts-office-365-public-cdn/

Cheers Michel

**Comment by shaipetel** [comment]
Thanks Michel, I quoted from the step by step guide and pasted the link to it: "Notice that you are no longer running gulp serve, and therefore nothing is served from localhost". 

That is what I was referring to, so either there is a bug or documentation is wrong. 

Right?

**Comment by tortoise386** [comment]
The documentation refers to the webpart added to a newly created "HelloWorld web part page" and not the workbench.

Quoting from the step by step guide you linked to:
> Test the HelloWorld web part
>
> Classic SharePoint Page
>
> Go to the HelloWorld web part page you created. Your HelloWorld web part will now load the web part  > bundle and other assets from CDN.
>
> Notice that you are no longer running gulp serve, and therefore nothing is served from localhost.
It is not mentioning the workbench at all. The workbench is designed as I stated above.

Happy holidays!

**Comment by shaipetel** [comment]
Oh, wow. Yeah, I see it now, working. Thanks.
Perhaps documentation on this page was a bit confusing, that it only works on that case and not on the workbench.

Thanks!
