### ISSUE TITLE
Process for setting "SingleWebPartAppPage" doesn't work when page approval is enabled

### ISSUE THREAD

**Issue by raymondlittle100** [SharePoint/sp-dev-docs#3262]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have a SharePoint site which uses the new page approval for managing changes to content. In the same site I have a web part on a page which is set as a single app page, see link below. I should be able to use single app pages in sites where page approval is setup

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

#### Observed Behavior

Currently you need to run a PS script or run JS in the console to update the page layout but as soon as you do that the page approval option disappears. This means you can't publish a page which is a single app because the UI option isn't there. Even if you setup the page and approve it as soon as you run the script to change the layout back to single app it puts the page back as a draft

#### Steps to Reproduce

Create SP site
Enable page approval flow
Create a page
Add web part
Run script to set new page as single app page

There is now no way to trigger the approval on the single app page and if you go to site pages you can click "Submit for approval" but it simply takes you to the page and there is no option available

**Comment by patmill** [comment]
Can you simply go to the list view and approve the page?

**Comment by raymondlittle100** [comment]
When trying to approve via the edit control block it just seemed to re-direct to the page. I'll test again and see

**Comment by raymondlittle100** [comment]
Any other details on this?

**Comment by VesaJuvonen** [comment]
We are looking into fixing this as part of the 1.8 (GA) version of the capability.

**Comment by mcmynn83** [comment]
With release of 1.8 (GA) you will create an app page as a new page and won't run into this approval issue.

**Comment by raymondlittle100** [comment]
Do we have a date for this?

**Comment by VesaJuvonen** [comment]
In a matter of days rather than weeks.
