### ISSUE TITLE
npm install error using node 8.15.0

### ISSUE THREAD

**Issue by vikasbansal9888** [SharePoint/sp-dev-docs#3266]
Getting error while installing "npm install -g yo gulp" cmd.
Not using any type of proxy

Please find attached log file and snapshot for the error.

[2019-01-14T12_42_47_222Z-debug.log](https://github.com/SharePoint/sp-dev-docs/files/2758410/2019-01-14T12_42_47_222Z-debug.log)

It gets struck and freezes on below
![1](https://user-images.githubusercontent.com/13880753/51164571-61340800-18c3-11e9-9c08-e06b83210583.jpg)

After sometime this error popup
![2](https://user-images.githubusercontent.com/13880753/51164578-685b1600-18c3-11e9-9621-e1856f9c30e0.jpg)

Checked on internet but no solution.
Please help on this, thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by StfBauer** [comment]
This is not a SharePoint issue it is more a general npm issue. Can you try:

```sh
npm get registry
```

To see what the configuration returns. Sometimes it also helps when you manually update the configuration once again.

```sh
npm config set registry="http://registry.npmjs.org/"
```

If this does not help I would suggest opening a ticket at the [npm bug site](https://npm.community/c/bugs).

**Comment by vikasbansal9888** [comment]
`npm get registry`

Above command returns - "http://registry.npmjs.org/"

So, i guess no need to set it manually.

**Comment by vikasbansal9888** [comment]
As per the error message attached by me, its due to proxy server. But I am not using any proxy. I'm in a corporate network. But when I check the internet settings >>LAN settings it doesn't show any proxy server. So, I believe I am not behind any proxy server.

**Comment by vikasbansal9888** [comment]
Also, opened ticket at the npm bug site
https://npm.community/t/sharepoint-spfx-npm-install-error-using-node-8-15-0/4645

**Comment by StfBauer** [comment]
This might also help. You can reset/remove the proxy from the configuration.
http://jonathanblog2000.blogspot.com/2013/11/set-and-reset-proxy-for-git-and-npm.html

Could it be that you previously was connected to a network with a proxy?

**Comment by shafaqat309** [comment]
Are you able to fix the issue? I am having the same issue.

**Comment by vikasbansal9888** [comment]
Yes, I'm able to solve the issue.

**Solution**:
The default value of ‘proxy’ and ‘https-proxy’ key of npm config is NULL. After doing some more R & D then I tried to set the proxy setting value to above key (this solution works in my scenario).

![image](https://user-images.githubusercontent.com/13880753/51374688-c9842300-1b29-11e9-9dfc-04665c23bdff.png)

Also, the same proxy settings need to be applied as shown below.
![image](https://user-images.githubusercontent.com/13880753/51374712-d86ad580-1b29-11e9-94ac-90892d26d8a3.png)

**Conclusion**:
In corporate/some environment the proxy is a somewhat mandatory setting otherwise npm install will not work.

**Comment by StfBauer** [comment]
Thank you for the update. Great that you were able to fix your issue.

**Comment by vikasbansal9888** [comment]
I'm closing the issue. You can refer blog for detailed information https://blogs2share.blogspot.com/2019/01/spfx-environment-setup-error.html
