### ISSUE TITLE
tslint warnings on build for type declaration on render method.

### ISSUE THREAD

**Issue by DanKline** [SharePoint/sp-dev-docs#327]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
tslint should not generate warnings on build.

level - minor (non-critical)

#### Observed Behavior
during build, tslint generates the following warning:
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(5,5): error member-access: The class method 'render' must be marked either 'private', 'public', or 'protected'

On checking, the file is indeed missing the public declaration:
```javascript
import { BaseClientSideWebPart, IPropertyPaneSettings, IWebPartContext } from '@microsoft/sp-webpart-base';
import { IHelloWorldWebPartProps } from './IHelloWorldWebPartProps';
export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
    constructor(context: IWebPartContext);
    render(): void;
    protected readonly propertyPaneSettings: IPropertyPaneSettings;
}
```

#### Steps to Reproduce
In my case, WebStorm is running the build scripts using a listener.  Changing any of the code and saving triggers a rebuild which generates the warning.

**Comment by DanKline** [comment]
Here is a list of the warnings in the terminal window of WebStorm.  I wasn’t able to figure out how to run tslint on the project outside of WebStorm.


[12:49:31] Project hello-world version: 0.0.1
[12:49:31] Build tools version: 0.11.1
[12:49:31] Node version: v4.4.5
[12:49:31] Total duration: 18 s
[12:49:31] Task warnings: 7
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(12,5): error member-access: The class method 'render' must be marked either 'private', 'public', or 'protected'
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(13,13): error no-unused-variable: Unused method: '_getMockListData'
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(14,13): error no-unused-variable: Unused method: '_getListData'
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(15,13): error no-unused-variable: Unused method: '_renderListAsync'
Warning - tslint - src\webparts\helloWorld\HelloWorldWebPart.d.ts(16,13): error no-unused-variable: Unused method: '_renderList'
Warning - tslint - src\webparts\helloWorld\MockHttpClient.d.ts(4,5): error member-access: The class method 'get' must be marked either 'private', 'public', or 'protected'
Warning - tslint - src\webparts\helloWorld\MockHttpClient.d.ts(3,20): error no-unused-variable: Unused property: '_items'

I've shared the project code from my OneDrive: https://1drv.ms/u/s!AlipQwFsTaHnl4lD76BpE_zTlsvtJQ 
The SetupSpFx.ps1 is a powershell script to install all the node tooling.  Don't run yoeman or you'll overwrite all the configurations.  I suspect that this is an issue with tslint or a tslint configuration.

**Comment by dcu-sharepoint** [comment]
@DanKline unable to download the zip file from you onedrive link, keeps telling me onedrive can't scan the file for viruses.

**Comment by DanKline** [comment]
Hi Carlos,

 

I downloaded it by choosing continue then scanned the file with Norton.  It found no errors.  I think it must be a limitation of OneDrive.

**Comment by dcu-sharepoint** [comment]
Thanks Daniel,


will try it again...


Carlos



________________________________

**Comment by iclanton** [comment]
Closing this because GA bits were released. Feel free to open another issue if you're still seeing this.
