### ISSUE TITLE
Is it possible to target a Private CDN location for ClientSIdeAssets?

### ISSUE THREAD

**Issue by spsguru** [SharePoint/sp-dev-docs#3270]
For reasons, we are not wanting to enable a public CDN and the CDN origin for */clientsideassets , so we enabled a private CDN, and added the */clientsideassets to it, and deployed web part in the tutorial following directions. It all works fine, but in looking at Sources in the developer tools, it does not show a CDN folder, and it is sourcing the web part files from the clientsideassets library in the app catalog. Is that the expected result? Or should it show the privatecdn.sharepointonline as the source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by 2toLeadMike** [comment]
I was reviewing this a few days ago and recalled this posting, which may still be relevant

https://techcommunity.microsoft.com/t5/SharePoint-Developer/How-do-we-deploy-SPFx-Web-Parts-to-a-Private-CDN-on-O365/td-p/69362

"You cannot deploy SPFx solutions using private CDN at least currently. This is due the fact that the private CDN URL is changing and is not static, which is needed"

**Comment by spsguru** [comment]
Thanks @2toLeadMike ! I should have searched deeper on this. 
I would like to see if there is any change to the situation; if not , then I imagine we'll create a public CDN using the -NoDefaultOrigins, and then create the Public origin */clientsideassets , that would limit exposure of other origins in the public CDN.

**Comment by patmill** [comment]
No, there currently isn't a change to this.

**Comment by spsguru** [comment]
I consider this closed now, and will offer as a workaround the following:

Create a public CDN using the -NoDefaultOrigins, and then create the Public origin */clientsideassets , that would limit exposure of other origins in the public CDN.
