### ISSUE TITLE
Some aliases cannot be used for custom web parts

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#3271]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When creating a a web part I should be able to use any alias, unless the schema validates my alias not to be valid. If I use the name `DividerWebPart` my web part should be possible to use together with the oob divider web part.

Either any alias should be valid, or the schema should validate. What happens if two vendors opt for the same alias?

#### Observed Behavior

If you add an oob divider webpart and a custom webpart which alias is `DividerWebPart` the page shows as blank.

#### Steps to Reproduce

Create a new web part and set the webpart alias to `DividerWebPart`. Add the oob divider and the custom web part to the page, and the page will go blank after saving on refresh.

Change the alias to `MyDividerWebPart` and it works just fine.

**Comment by VesaJuvonen** [comment]
This is actually by design. Alias is uniquely identified in the page. We might revisit this in the future if needed. Should be updated in the docs.

**Comment by wobba** [comment]
Good enough, and guidance could be to always prefix the alias in some way to make sure it’s unique.
