### ISSUE TITLE
Application Extension - Modern Site/Classic Pages

### ISSUE THREAD

**Issue by mkeysae2** [SharePoint/sp-dev-docs#3272]
Is there any option to customize classic pages on a modern site such as /_layouts/settings.aspx?  For classic sites (without the noscript flag), we can use a user custom action to inject into all pages.  It seems for modern sites, we are limited to modern pages only.  Can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Confirmed (sort of)... SPFx Extensions, specifically command sets, don't have the ability ATM to customize anything other than the toolbars & context menus in lists & libraries in modern lists & libraries.

**Comment by mkeysae2** [comment]
Thanks for the feedback!
