### ISSUE TITLE
Using chrome dev tools to find issues shows up blank script files

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#328]
#### Category
- [x] Question

#### Expected or Desired Behavior
When I open dev tools in chrome, and want to identify a bug or break on the JS code, I expect to see the source code and be able to put a breakpoint on it. Even if minified - I can use pretty print.

#### Observed Behavior
All script files served from the web pack (framework files, and my own project files) appear as empty in the chrome debug tools. This is all I see in them:
(function(System, SystemJS, require) {
})(System, System);

If I open them in a new tab, I can clearly see all code is there. Something in the project / script is blocking chrome from allowing debug.

I am experiencing an issue that every few page refresh, the web part would not load (placed in a classic SharePoint page, not inside the workbench), with an error similar to "sp-module-loader_en-us_10099ee….js:55 ***sp-classic-page-application.bundle failed to load. Error: Error: TypeError: Cannot read property 'prototype' of undefined" but I cannot investigate it since all script files look like the above.

#### Steps to Reproduce
Build a web part, deploy to CDN, put the web part in a classic SharePoint page, open chrome dev tools.
Now, try to open either your web part bundle JS file, strings file, or any framework bundled JS file from spoprod-a.akamaihd.net/files/sp-client-prod_xxx and you will see script files appear empty.

Right click on the file name in the debug window -> open link in new tab, and you will see it opens with all source code.

I tried to disable or enable source map in chrome dev settings, with no luck.

If this only happens to me - please let me know as well...

**Comment by patmill** [comment]
Yes, we see that as well.  It seems to be a bug in chrome that comes and goes.  What we have found works is to hit ctrl-shift-f (find in all files), and search for something that is in your source file.  At that point, chrome will load it and you can debug.  It's a pain.

**Comment by shaipetel** [comment]
I noticed then running from workbench, it tends to work better and most times shows the TS source code.
In Edge I didn't notice the issue but noticed something else that is strange: all my script files appear in Edge twice: once with only the strange source code like in Chrome, and a second time with the full minified source code.

Are we sure it is a bug in Chrome? I didn't experience it with any other project except with this one. I did notice there is no map file configured in the SPFx packed files, usually the map file is linked in a //# comment at the end of the minified / combined file. Perhaps this is what is causing the issue?

**Comment by pgonzal** [comment]
FYI this will be fixed in the next drop.  It was actually a SystemJS bug, not a Chrome bug as we had assumed.  (I realized this when I was able to repro it in Firefox.)

Here is a temporary workaround:

1. Open `node_modules\@microsoft\sp-loader\dist\sp-loader.js` using a text editor
2. Search for the string "`# sourceURL=`" and replace with "`# disable=`"
3. Save the file.  (If something breaks, you can restore it by deleting your **node_modules**  folder and redoing "npm install")

@waldekmastykarz @VesaJuvonen @chakkaradeep
