### ISSUE TITLE
Sorry, something went wrong

### ISSUE THREAD

**Issue by GodTigga** [SharePoint/sp-dev-docs#3280]
"A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version." Under "Prepare web part assets to deploy" please add a step in which you tell people to update the app version to avoid this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ConaxLiu** [comment]
I just followed the instructions in this page and did not encounter this issue.

**Comment by iBrooks** [comment]
As ConaxLiu also reported, I have successfully followed this page's instructions without encountering the error.

**Comment by andrewconnell** [comment]
Both @ConaxLiu & @iBrooks are correct... #closing
