### ISSUE TITLE
View formatting customRowActions not firing if list view is accessed by query string

### ISSUE THREAD

**Issue by arielkropp** [SharePoint/sp-dev-docs#3282]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When switching between views in a modern SharePoint list the first view loaded is the direct URL to that view, but if you switch views the view is fetched by query string using the viewID. When switching between views like this elements with customRowActions should result in the set Action taking place.

#### Observed Behavior

If a view is accessed by query string customRowActions do not fire.

#### Steps to Reproduce

Create any view format with a `button` and `customRowAction`. Access a different view directly and then switch to this view using the views dropdown list. customRowActions will not fire. This will only occur on the first time you switch to the view - If you switch back to the original view and then back again using the dropdown it seems the action will fire.

**Comment by ravinleague** [comment]
**onPropertyPaneFieldChanged** not fired on **PropertyPaneDropdown** change event. All other controls such as text,slider etc fire properly! 

 "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-tslint-rules": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.7.1",
    "@microsoft/sp-webpart-workbench": "1.7.1",

**Comment by shagra-ms** [comment]
@arielkropp I am unable to repro this locally. customRowAction works for me with View Formatting, even after I navigate to the view using the view dropdown.

Can you confirm if this is working for you now?
