### ISSUE TITLE
Sharepoint OOTB header is still visible along with the custom header

### ISSUE THREAD

**Issue by haripras92** [SharePoint/sp-dev-docs#3285]
This code was working fine for sometime. Suddenly I am getting two headers, the custom header and OOTB header below it. Is there anyone else who is facing this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
When you use custom placeholders, you are not removing oob capabilities, you are adding additional elements like shown in the pictures of this tutorial, so this is as expected.,
