### ISSUE TITLE
Checkbox, dropdown, and toggle fields.

### ISSUE THREAD

**Issue by haugan** [SharePoint/sp-dev-docs#3290]
I wish this documentation would've shown me how to add the checkbox, dropdown, and toggle fields to the custom web part as well - not just make them appear in the Property sidebar! Other than that, great guide so far (cheers).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
The property pane controls are designed for the property pane, not the web part itself. The contents of the web part UI is just HTML & JavaScript.

If you are using a framework such as React, I suggest taking a look at a UI Framework like Office UI Fabric[]( https://developer.microsoft.com/en-us/fabric) .
