### ISSUE TITLE
Modern SharePoint Admin Center - Create Team site results in Document Center

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#3292]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Creating a site using the new SharePoint admin center using the Team Site (no group) under Other options should create a new site with that template.

#### Observed Behavior

When creating site under Other Options > Team Site (No Group) template, results in the creation of a Document Centre site.

#### Steps to Reproduce

Go to SharePoint Admin Center (modern)
Create Site > Other Options > Team Site
Wait 15 mins
Site is a Document Center.

This is seen in multiple UK based Targeted Release tenants.

**Comment by VesaJuvonen** [comment]
An understandable issue, but as this is not a developer scenario, we cannot, unfortunately, process this issue using GitHub channels and would ask to report this from the tenant admin UI support channel. Thanks.
