### ISSUE TITLE
Site Design Create Content Type action gives an invalid type error

### ISSUE THREAD

**Issue by joshburnssp** [SharePoint/sp-dev-docs#3295]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the createContentType action in a site design I expect the content type to be created in the site that has been created from a site design which contains that site script.

#### Observed Behavior

When using a createContentType action from the Site Design json schema, I get: One or more of the properties on this action has an invalid type.

![sitedesignerror](https://user-images.githubusercontent.com/30901352/51395397-a9a62c80-1b34-11e9-8e5f-d0aaef01c559.JPG)

#### Steps to Reproduce

Put a script with the createContentType action in variable in PowerShell, I used the example of the Site Design document:

`{
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "To",
      "displayName": "To",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "From",
      "displayName": "From",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "CC",
      "displayName": "CC",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "BCC",
      "displayName": "BCC",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "DateTime",
      "internalName": "SentOn",
      "displayName": "Sent On",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "DateTime",
      "internalName": "ReceivedTime",
      "displayName": "Received Time",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "Importance",
      "displayName": "Importance",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "AttachCount",
      "displayName": "Attach Count",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "Sensivity",
      "displayName": "Sensitivity",
      "isRequired": false
    },
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "MessageID",
      "displayName": "Message ID",
      "isRequired": false
    },
    {
      "verb": "createContentType",
      "name": "Email",
      "description": "Project Email",
      "parentName": "Item",
      "hidden": false,
      "subactions": [{
          "verb": "addSiteColumn",
          "internalName": "To"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "From"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "CC"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "BCC"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "SentOn"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "ReceivedTime"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "Importance"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "AttachCount"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "Sensitivity"
        },
        {
          "verb": "addSiteColumn",
          "internalName": "MessageID"
        }
      ]
    }`

#### Submission Guidelines

Using the powershell scripts - Add-spositedesign etc

**Comment by bcameron1231** [comment]
There appears to be a discrepancy between the script you posted and the script that running on your site design.

Notice the internal names of the columns in your site script. Now, look at the sub actions in the image you posted. The screen shot shows "Add site column **HLTo** to content type".  This means it's looking for an internal field named **HLTo**... but in your createSiteColumn, the internal name is "To". The site script you posted is valid, but it's not the one that is being executed in your site design

To verify, call
[Get-SPOSiteScript ](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Get-SPOSiteScript?view=sharepoint-ps) and compare that site script to the one you posted.

If it is different, set the site script again with your new script json posted using Set-SPOSiteScript

**Comment by bcameron1231** [comment]
I would double check, it looks like you missed HLSensitivity.

**Comment by joshburnssp** [comment]
🤦

bad spelling, many apologies and thanks :)

Josh
