### ISSUE TITLE
Change "HelloWorld.module.scss" to "HelloWorldWebPart.module.scss"

### ISSUE THREAD

**Issue by mikeacosta** [SharePoint/sp-dev-docs#3296]
#### Category
- [ ] Question
- [x ] Typo
- [ ] Bug
- [ ] Additional article idea

Minor issue in docs @
```
docs
--spfx
---webparts
-----get-started
--------connect-to-sharepoint.md
```

#### Expected or Desired Behavior

A couple references to 

> HelloWorld.module.scss.ts

should instead be 

> HelloWorldWebPart.module.scss.ts

##### Notes
The Yeoman SharePoint generator appends "WebPart" to the answer given to "What is your Web part name?" when creating web part files while scaffolding the solution.  The docs instruct to accept the default "HelloWorld" answer in this case, thus the "HelloWorldWebPart.*" naming.

**Comment by VesaJuvonen** [comment]
Fixed with #3302.
