### ISSUE TITLE
I wanted to use external JS Google Chart API CDN in SPFx react webpart. Can any please tell me how we can do that.

### ISSUE THREAD

**Issue by rahultrimukhe777** [SharePoint/sp-dev-docs#3298]

**Comment by AJIXuMuK** [comment]
Hi @rahultrimukhe777 
I think you should you the approach that is described in the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library)

**Comment by AJIXuMuK** [comment]
@rahultrimukhe777 
Here is a [sample code](https://github.com/AJIXuMuK/issues/tree/master/google-charts).
I'm not using React here but plain JavaScript.
Basically, as per documentation, you need to reference external non-AMD module.
Then you should call
```typescript
 google.charts.load 
google.charts.setOnLoadCallback
```
I did that in `onInit` of the web part.
Then you can actually render the chart.
Please, feel free to reuse the code if needed.

**Comment by rahultrimukhe777** [comment]
> @rahultrimukhe777
> Here is a [sample code](https://github.com/AJIXuMuK/issues/tree/master/google-charts).
> I'm not using React here but plain JavaScript.
> Basically, as per documentation, you need to reference external non-AMD module.
> Then you should call
> 
> ```ts
>  google.charts.load 
> google.charts.setOnLoadCallback
> ```
> 
> I did that in `onInit` of the web part.
> Then you can actually render the chart.
> Please, feel free to reuse the code if needed.

Thanks alot for taking this much efforts, I really appreciate your help :)

**Comment by AJIXuMuK** [comment]
My pleasure!
