### ISSUE TITLE
Default value showing undefined

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#33]
I have followed steps to add new propertied to helloworld webpart. But default value not updating showing as undefined
![image](https://cloud.githubusercontent.com/assets/21132206/17827484/509e0138-6643-11e6-9af3-bd37f7fcaa28.png)

Also receiving below error
![image](https://cloud.githubusercontent.com/assets/21132206/17827490/7d0410e6-6643-11e6-9870-e70979657e31.png)

**Comment by patmill** [comment]
So changes to manifest.json (where the default values are stored) don't automatically get picked up by the background build.
Try stopping your gulp serve (ctrl-c)
then start gulp serve again
refresh your page

**Comment by bvdinesh** [comment]
In sharepoint, delete the existing webpart and add new one. The value is reflected. Thank you
