### ISSUE TITLE
Workbench completely blank - displays nothing!

### ISSUE THREAD

**Issue by nigel-dewar** [SharePoint/sp-dev-docs#3303]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Brand new setup - installed all the tools, no errors, run gulp cert install or whatever it is to install the dev cert which worked. Fire up using gulp serve and........ nothing.

#### Expected or Desired Behavior

Workbench to actually show something.

#### Observed Behavior

workbench shows nothing

![image](https://user-images.githubusercontent.com/9402456/51450510-abfac780-1d7c-11e9-8414-1bbf92f4d89a.png)

#### Steps to Reproduce

get a windows 10 pro machine
Install everything include node 8.15 from scratch
NPM 6.4.1
Run it all up and observe the epic failure

I get the following dialog when running gulp serve - all looks well
![image](https://user-images.githubusercontent.com/9402456/51450533-bddc6a80-1d7c-11e9-9107-382a3f3e9319.png)
browser fires up blank however, the final output of gulp serve is
![image](https://user-images.githubusercontent.com/9402456/51450544-ce8ce080-1d7c-11e9-9d25-db3bf9b27366.png)

Its quite amazing that this product can be so useless. I tried spfx a year or so ago and got the same BS. So I thought this beta crap and left it in the hopes that microsoft devs would get their act together. Now I try on a completely different machine and SAME AGAIN!

see my post from a year ago https://github.com/SharePoint/sp-dev-docs/issues/1241

**Comment by bcameron1231** [comment]
I'd also like to add that I've seen this for a couple reasons. 1. You have a network/fire wall possibly blocking the request. 2. There have been issues with this before when the 5432 port is already in use by your system, by another application. If you've confirmed it's not 1, could you try to change your port in your serve.json and see if it works?

**Comment by andrewconnell** [comment]
I've seen this before too... delete your `node_modules` folder, delete any lock files and run `npm install` again. 

Also:
- is this a brand new project or an old project?
- can you post more from the console log as there are other things that could be showing up that aren't captured in your logs
- any issues in the browser's console?

**Comment by nick-gaudreau** [comment]
@nigel-dewar Hi. You have to set your workbench url in config/serve.json property initialPage.... your workbench url should look like this:
https://{ReplaceWithYourDomainName}.sharepoint.com/sites/PeerLeader/_layouts/15/workbench.aspx

**Comment by nick-gaudreau** [comment]
@nigel-dewar Then when you do your gulp serve, the workbench page will open requesting to signin with your account then click the +, select your web part
