### ISSUE TITLE
On some sites, role="heading" is set for the page header instead of role="header"

### ISSUE THREAD

**Issue by anasnakawa** [SharePoint/sp-dev-docs#3304]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Page header should have an attribute `role="header"`

#### Observed Behavior

On  some sites, the attribute is set correctly `role="header"` 

![image](https://user-images.githubusercontent.com/559002/51457774-1c4d1d00-1d6c-11e9-9ee9-f184069ca533.png)

While on another sites, it is set to `role="heading"`

![image](https://user-images.githubusercontent.com/559002/51457794-2ff88380-1d6c-11e9-9e05-f057b11ab75e.png)

#### Steps to Reproduce

No steps to reproduce, simply the site either has the correct tag, or not.

**Comment by VesaJuvonen** [comment]
We would need to understand more on the issue to evaluate it. Is this on which pages and how is this impacting you as it seems to be internal html output of the header. We can't really progress without additional details.

**Comment by anasnakawa** [comment]
@VesaJuvonen basically we're trying to understand the structure of the Modern page from the HTML to determine where different parts of the page are placed (like header/side panel, ..etc), 
to hide those different parts based on customer needs.
and we can see on different tenants, that HTML output is different for the same element on the same page.
Now I don't really recall where this has happened.

But the main issue here, you guys need to provide well defined attributes for your elements on the page that will not change over time, to make it easier for vendors to understand and deal with those elements.

**Comment by VesaJuvonen** [comment]
Unfortunately, this is completely unsupported as our html page structure keeps on evolving on weekly basis. This is why we are offering place holders with the SPFx and we will keep on adding new placeholders in the future for these kinds of requirements. We will though not provide guarantees on the page structure to remain intact and you should not build anything based on that assumption.
