### ISSUE TITLE
Error loading debug manifests - SPFx Extensions 2

### ISSUE THREAD

**Issue by AntyfrizZz** [SharePoint/sp-dev-docs#3306]
Hello,

I posted question here, but i am not sure if the issue is closed, that someone will receive notification or something. - https://github.com/SharePoint/sp-dev-docs/issues/1175

![image](https://user-images.githubusercontent.com/6909862/51478411-07847f80-1d94-11e9-865a-4a9ad79dc03e.png)

I have the issue with Error loading debug manifests. I can run debug only in Chrome . When i try to do it on other browser, I get the error.
SPFx 1.7.0
Node - v8.9.4
I ran gulp trust-dev-cert
It is Application Customize Extension
I scaffold new App Customizer with latest version of yeoman and the issue is still in

Nothing. Sad.

Best Regards,
Yavor

**Comment by VesaJuvonen** [comment]
thx @AntyfrizZz - can you be slightly more specific on what do you mean with " When i try to do it on other browser" - which browser and which version, so that we can help you.

**Comment by VesaJuvonen** [comment]
@AntyfrizZz  - also - your steps do no include gulp serve command when you are testing, so can you provide the repro steps, so that we know the steps which you did. Thx.

**Comment by AntyfrizZz** [comment]
@VesaJuvonen ,

Sorry for the lack of information

On your first question
Firefox 64.0.2 (64-bit)
Microsoft Edge 38.14393.2068.0

On your second
Yes, i did run gulp serve.
On the attached files you can find newly scaffolded project (with nothing modified by my side). When i run gulp serve, i can start debugging it on Chrome, but when i try to do it on the browsers mentioned above, i get the error.

[Newfolder.zip](https://github.com/SharePoint/sp-dev-docs/files/2779218/Newfolder.zip)

Best Regards,
Yavor

**Comment by regularroutine** [comment]
Hey all,
just wanted to let you guys know I also have this issue, it works fine if I use IE but not Edge when I develop Extensions. 
IE: 11.523.17134
Edge: 42.17134.10
Node: v8.15.0
Thanks,
David

**Comment by andrewconnell** [comment]
Can you provide the following?

- verify you are testing this against latest SPFx v1.7.1
- what environment (SPO / SP2019)
- URL that's generated & used to load the extension on the page
- screenshot of the command prompt used when running `gulp serve` to run the command
- and ideally, screenshot of the error in the browser's NETWORK tab
