### ISSUE TITLE
ETA for Sharepoint Add-In scaffolding via yeoman generator

### ISSUE THREAD

**Issue by ordinaryorange** [SharePoint/sp-dev-docs#3310]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Not sure if this is the appropriate location to post this question, but I could not find a repo for the generator.
I assume scaffolding of sharepoint add-ins (as opposed to webparts and extensions) with the yo generator is on the roadmap ?
If I am correct, is there an ETA for this option in the generator ?

Thanks !

**Comment by andrewconnell** [comment]
ATM, there is nothing published on the public roadmap. Existing tooling for addins in Visual Studio is still the recommended approach. The Yeoman generator experience is singularly focused on the SharePoint Framework.

This would fall under the "feature request" category... a such it would make for a good User Voice suggestion here: http://aka.ms/sp-dev-uservoice
