### ISSUE TITLE
Error while using "gulp serve" after fresh init of yo @microsoft/sharepoint 

### ISSUE THREAD

**Issue by BenediktRieger** [SharePoint/sp-dev-docs#3311]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

Specs:
Windows Server 2012 R2 Standard
Node v8.11.4 
npm 5.6.0 
@microsoft/generator-sharepoint@latest 

#### Expected or Desired Behavior
Let's create a new SharePoint solution.
 1. What is your solution name? HelloWorld
 2. Where do you want to place the files? Create a subfolder with solution name
 3.  Do you want to allow the tenant admin the choice of being able to deploy the  running any feature   deployment or adding apps in sites? No
 4.  Which type of client-side component to create? WebPart
 5.  What is your Web part name? HelloWorld
 6.  What is your Web part description? HelloWorld description
 7.  Which framework would you like to use? React
 8. Run "gulp serve" and build without errors. 

#### Observed Behavior
 Step 1-7 are working but when I run "gulp serve" I get following error: 
 
 Error - [webpack] 'dist':
./src/webparts/helloWorld/HelloWorldWebPart.js
Module not found: Error: Can't resolve './components/HelloWorld' in 'C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld'
resolve './components/HelloWorld' in 'C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld'
  using description file: C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\package.json (relative path: ./src/webparts/helloWorld)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\package.json (relative path: ./src/webparts/helloWorld)
    using description file: C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\package.json (relative path: ./src/webparts/helloWorld/components/HelloWorld)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld.json doesn't exist
      as directory
        C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld doesn't exist
[C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld]
[C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld.js]
[C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld.json]
[C:\Dev[BRE]\MyProjects\React\ReactSharePoint\HelloWorld\src\webparts\helloWorld\components\HelloWorld]
 
#### Steps to Reproduce
I don't know how to reproduce, because it's a fresh init using yo.

Thanks in advance. I'm really new to this "npm" thing.

**Comment by andrewconnell** [comment]
Hey @BenediktRieger ... can you retry the exact same thing, but this time create it in a path where `[` and `]` aren't present in the path? Just created two projects, one with `[` & `]` and one without... the first one produced an error, the second one didn't (_a different error than you got though... however, I'm on MacOS_).

Also... run the following command at the command prompt and report the results as it will provide more details on your environment:

```
npm list -g --depth=0
```

**Comment by BenediktRieger** [comment]
Hey @andrewconnell! 
It works without "[]".
Thanks!
