### ISSUE TITLE
Is it possible to add a new button or control on social bar using application customizer

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3314]
I have a requirement do track usefulness of each page, I can add a button on footer using application customer. but it is added below social bar.
Is it possible to add it next to **save for later** option
![image](https://user-images.githubusercontent.com/11780473/51538507-c18df100-1e51-11e9-8517-4a36ead3c2f6.png)
or can i add it here
![image](https://user-images.githubusercontent.com/11780473/51538557-e5e9cd80-1e51-11e9-9c86-946ee4fbcd76.png)
or is it possible to add something using floating button.

**Comment by andrewconnell** [comment]
Not in a supported way. The app customizer's "top" & "bottom" placeholders are single `<div>`s you can write to... you can't modify other containers on the page. Technically you _could_ do this, but that would fall into the category of DOM manipulation which is explicitly discouraged and not supported.

**Comment by harshdamaniahd** [comment]
yes, I dont want to do anything via DOM manipluation. Are there any chances of having this as placeholders in future ?

**Comment by andrewconnell** [comment]
Additional placeholders have been requested via UV... suggest you pile on there. You'll find them linked here: https://github.com/SharePoint/sp-dev-docs/issues/625
