### ISSUE TITLE
Property 'msGraphClientFactory' does not exist on type 'WebPartContext'.

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#3315]
I am on SPFx 1.5.1 and getting below error 'Property 'msGraphClientFactory' does not exist on type 'WebPartContext' on below line,

```
    this.context.msGraphClientFactory
     .getClient()
     .then((client: MSGraphClient): void => {
       // use MSGraphClient here
     });
```

Am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2381d26e-96c9-44de-8e4e-f70edc2db498
* Version Independent ID: f81cacee-a1cd-89dd-ee53-c84689c03917
* Content: [Use the MSGraphClient to connect to Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph)
* Content Source: [docs/spfx/use-msgraph.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-msgraph.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by ravick4u** [comment]
I didn't notice the other error "Module "/MyFirstMSGraph/node_modules/@microsoft/sp-http/dist/index-internal" has no exported member 'MSGraphClient'."

As per this article SPFx 1.4.1 is required for this, but as per below this error is due to a lower version than 1.6.

https://github.com/microsoftgraph/msgraph-training-spfx/issues/8

Do I need to upgrade to 1.6?

**Comment by andrewconnell** [comment]
Yes... some API changes happened when the Graph support went GA in v1.6. Ref: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.6-release-notes

Looks like this doc needs to get updated... we'll get that fixed. Thanks for the callout!
