### ISSUE TITLE
Navigation around SharePoint fails when Gallery WebPart is used

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#3318]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

This one might not be a dev issue, but I think it's important to be logged somewhere so it gets to the right person.

When clicking on an image in an Image Gallery, we should be able to browse the gallery, close it and navigate somewhere else.

#### Observed Behavior

On all tenants, we are seeing that when using this WebPart and navigating afterwards, some images are opened and breaks the experience.

#### Steps to Reproduce

1. Add an Image Gallery to any page and add images
2. Click on an image
3. Close the lightbox
4. Navigate by clicking the Site logo of Home link
5. The Image reappears.

![2019-01-22_17-32-24](https://user-images.githubusercontent.com/7620955/51569935-c790cb80-1e6b-11e9-95eb-95629a0704ef.gif)

Click here for the [High-Res version](https://1drv.ms/u/s!ArrATY5lyKQTjpA1MNDV9sPWT3InsA) of the Gif

**Comment by sebastienlevert** [comment]
Adding the link to the Twitter discussion with John Sanders : https://twitter.com/johnsanders/status/1087901588960698369

**Comment by patmill** [comment]
As you mention, this isn't something we can deal with in this forum.  Sounds like you hooked up with John Sanders though, so he can help with taking through the product issue side of things.
