### ISSUE TITLE
Detect environment that Application Customizer is running in

### ISSUE THREAD

**Issue by lworkman** [SharePoint/sp-dev-docs#3319]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm wondering if it's possible to detect the environment a SPFX Application Customizer is running in. A company wide solution isn't rendering properly in embed SharePoint pages in teams or in the SharePoint mobile app, and we want to hide the solution under these scenarios.

I wasn't able to find anything in the context object, and the usual tricks (looking at location or window parent) don't seem to be working.

**Comment by andrewconnell** [comment]
Not clear... you mean this? https://docs.microsoft.com/en-us/javascript/api/sp-core-library/environment

**Comment by bcameron1231** [comment]
To add to Andrew's Comment. Correct me if I'm wrong... here is the list of environment types available https://docs.microsoft.com/en-us/javascript/api/sp-core-library/environmenttype?view=sp-typescript-latest.

I believe if you need to check if you are loading in MS Teams, there is teams context object, this.context.microsoftTeams you can check. You can find more in this documentation https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction

**Comment by bcameron1231** [comment]
Ah, I was thinking a web part. My apologies for leading you down that rabbit hole.

**Comment by patmill** [comment]
With SPFx solutions getting broader (teams integration, etc.) we'll be adding some additional functionality to know the environment it is being loaded into.  It's kind of exploding, so we'll probably have a few different parameters.  It won't be "PageHostedInTeamsTabHostedInIosTeamsApp" (which I think is the broadest set of environments available) but rather something like knowing you are in teams, or you are in an app vs. a browser, etc.  Stay tuned for more info.

**Comment by VesaJuvonen** [comment]
We will be releasing updated information on this topic as part of the General Availability of this feature, so closing this one.

**Comment by PeterHeibrink** [comment]
I cannot really find the answer in the release notes. Where can we find the way to detect if the Application Customizer is ran from Teams? I could only find using the user agent string, but that doesn't work when someone uses Teams via their browser.

**Comment by pvranich** [comment]
Do we know when this feature will reach GA?

If it has already reached GA is there a link to the documentation?

**Comment by jonathanhotono** [comment]
any update over this?

**Comment by lworkman** [comment]
Can we re-open this ticket? We're coming up on a year and this is still an issue

**Comment by netti01** [comment]
We simply use "window.navigator.userAgent" in order to check if our SPO page is running in Microsoft Teams. If it runs in teams you will find "Teams" and "Electron" within its value.

We also tried to embed the Teams SDK within our Application Customizers, but without any success. There seem to be different conflicts when initiating the JS on an SPO modern page. Perhaps this only works for "Team" SPFX Webparts.
