### ISSUE TITLE
Display-Error while uploading Documents with drag & drop into DocLib a ListViewWebpart 

### ISSUE THREAD

**Issue by doxic012** [SharePoint/sp-dev-docs#3321]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The expected behaviour is the completion of the upload-process, when dragging a document into a document library using a listview-webpart on a page in a teamsite.

#### Observed Behavior

The document uploads, but the progress bar stops halfway and the spinner is still shown. The status says "1 of 1 complete" and the user is still able to press the cancel button which does not have any effect after the document was uploaded.
Once the specific document was uploaded, this error is **not reproducible** for the **same** document in the same library. It still occurs with other documents though.

This image shows the state of the document upload:
![dragdrop_error](https://user-images.githubusercontent.com/3975568/51592509-1c762580-1ef0-11e9-9825-9df787933f70.jpg)

This is a screenshot of the error in the formatted version of sp.js (https://static.sharepointonline.com/bld/_layouts/15/16.0.8516.1214/sp.js):
![image](https://user-images.githubusercontent.com/3975568/51592742-b047f180-1ef0-11e9-83de-4c1324a9fb0d.png)

The call to ensure dragdrop.js on the aspx-page to ensure the upload is delegated to the correct library.
Here the selected list is not obtained by using
`SP.ListOperation.Selection.getSelectedList()`
so the script crashes at this point (since the listId is null, obviously)
![image](https://user-images.githubusercontent.com/3975568/51593259-0cf7dc00-1ef2-11e9-8c16-64219022aaf4.png)

Used method on readystatechange in dragdrop.js (https://static.sharepointonline.com/bld/_layouts/15/16.0.8516.1214/dragdrop.js):
![image](https://user-images.githubusercontent.com/3975568/51592905-1765a600-1ef1-11e9-9d07-ab62304f502f.png)

This error occurs using IE 11, Edge, Chrome or Firefox and is not browser-related.

#### Steps to Reproduce

Create a Teamsite (EN) in SharePoint Online, add a listview-webpart for the default document-library and drag a document (in this case an xslx-sheet) into the webpart.
Deleting the file afterwards and reuploading does not reproduce the error, it has to be a new document  or a renamed version of the previous one(probably due to versioning-settings).

#### Submission Guidelines

Since the delegate-call is injected into the aspx-page is not part of any js-file that is requested, the ScriptBlock on the ServerSide-Code is the initiator of this bug. I do not know the details of the object `SP.ListOperation`, but it seems to be the first source to solve this issue.

**Comment by patmill** [comment]
So this issue (being a product issue and not a developer issue) is outside the scope of this tracking system.  I've forwarded the issue to the product team.  Feel free to open a support ticket if you need something more official.

Thanks for all your information.
