### ISSUE TITLE
Retrieve all list items section does not mention paging/item limits

### ISSUE THREAD

**Issue by brandonmcclure** [SharePoint/sp-dev-docs#3323]
The documentation leads me to believe that I can use that example to retrieve ALL the items from my list, but I am getting a limitation of 100 items. 
The specific URL/endpoint is http://site url/_api/web/lists/GetByTitle('Test')/items

I need to handle paging in my app, or use the Top parameter to request more items in a single call. Neither of those solutions are described or mentioned at all in this documentation, which required me to search elsewhere to find the answer of how i can get more than the first 100 items from a list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Correct, by default the REST endpoint returns 100 items. 

In the documentation, you'll notice the navigation menu on the left. If you select the link in the documentation for [Use OData query operations ](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints) ...You'll see where it talks about using the $top operator and the $batch operator.

**Comment by brandonmcclure** [comment]
I think it would be useful to explicitly state that by default it will return 100 items, not all, and to see the [Use OData query operations ](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests) page to read about how to structure your query.

**Comment by patmill** [comment]
Thanks for the feedback @brandonmcclure .  Documentation has been updated, and should show up soon.
