### ISSUE TITLE
TimeZoneInfo wrong daylightDate and standardDate

### ISSUE THREAD

**Issue by mirkori** [SharePoint/sp-dev-docs#3325]
#### Category
- [x] Bug

#### Expected Behavior
TimeZoneInfo on context.pageContext.user should enable me to convert UTC to local time. 

e.g. for  timezone "(UTC+1) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" (TimeZoneId 4)
daylightDate should be: March 31 2019 02:00 CET

#### Observed Behavior

TimeZoneInfo returns wrong dates for daylightDate (Day 5 of Month 3) and standardDate (Day 5 of Month 10) .
dates are returned as ISPSystemTime 

I want to convert UTC to local time. Conversion with the formula from https://docs.microsoft.com/en-us/javascript/api/sp-page-context/sptimezone?view=sp-typescript-latest gives wrong results.

**Comment by mirkori** [comment]
Any updates on this one? Its one week until summer time DST in Europe.

**Comment by lahuey** [comment]
@mirkori Are you still seeing issues here?

**Comment by mirkori** [comment]
This issue still exists for probably all timezones.

Daylight Savings for Pacific Time:
![image](https://user-images.githubusercontent.com/46990834/61897436-519f1700-af17-11e9-94bf-6a17831d288c.png)
_spPageContextInfo.userTimeZoneData:
![image](https://user-images.githubusercontent.com/46990834/61897344-24526900-af17-11e9-84fd-cd79484177a7.png)

**Comment by ahessami** [comment]
Hey there... is there any progress on this issue?  I'm also experiencing the same issue with the incorrect daylightDate (screenshot below):

![image](https://user-images.githubusercontent.com/3638514/78803253-3e2fc100-796b-11ea-85af-6aed93f95cd0.png)

**Comment by kemesfun** [comment]
The calculation of the date is correct, but the daylightDate doesn't have a public documentation, so the values will seem misleading. Here are the some of the non obvious property descriptions for daylightDate:
DayOfWeek = 0-6, Sunday - Saturday
Day = the Nth DayOfWeek in that month
@ahessami that example would be interpreted as the 2nd Sunday of March (March 10th)
There will be an update to the public API.

**Comment by mirkori** [comment]
Thank you for the clarification @kemesfun . Should "day" be actually named "weekOfMonth" in this case, to align to the "dayOfWeek" naming?

**Comment by kemesfun** [comment]
@mirkori The variable name change is something we may consider, but whether or not this api will go beyond beta is still unknown.
