### ISSUE TITLE
SharePoint Framework extension and list template id activation filter

### ISSUE THREAD

**Issue by mschaaks** [SharePoint/sp-dev-docs#3326]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Configured RegistrationId within Elements file should be automatically set as the filtered List Template id in the "TenantWideExtensions" list when opting for  a tenant/site collection scoped extension deployment.

#### Observed Behavior

In elements file this entry has been configured: RegistrationId="101". In "TenantWideExtensions" list the list template id however is set to "100", forcing me to perform an additional deployment step by opening the hidden "TenantWideExtensions" and manually altering the mentioned id from "100" to "101". As a temporary solution I could create some additonal scripting to automate this deployment step, however I expect this to be done automatically by SPO.

#### Steps to Reproduce

1. create a list view command set extension to be available within a document library (id 101) using the RegistrationId option within the elements file
2. set deployment scope of extension to tenant wide
3. create site collection app catalog
4. upload spfx solution package
5. view item within "TenantWideExtensions" list and check the list template id property (is 100 instead of expected 101 value).
![extensie_activation_listtemplateid](https://user-images.githubusercontent.com/13422496/51668778-3af92100-1fc3-11e9-9c5c-f04adc723ca2.PNG)
![registrationid](https://user-images.githubusercontent.com/13422496/51668779-3b91b780-1fc3-11e9-9f71-e08ce6db2900.PNG)

**Comment by patmill** [comment]
Sorry - just to confirm (as the pictures seem to tell a different story).  The elements CustomAction attribute on RegistrationId is 101, but when you look at the actual configuration in the TenantWide Extensions list, it shows as 100?  (in the picture it is showing as 101).

**Comment by mschaaks** [comment]
The picture is indeed misleading. It shows the manually adapted value. But initially it has the wrong value, 100 instead of 101.

**Comment by andrewconnell** [comment]
What goes in the **TenantWideExtensions** is defined in the **./sharepoint/assets/ClientSideInstance.xml** file, not what's in the **elements.xml** file.
