### ISSUE TITLE
Site design for team site not applying theme

### ISSUE THREAD

**Issue by sophieryder** [SharePoint/sp-dev-docs#3327]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I've created a simple site script to set the theme and regional settings. I've deployed this as a team site design with the -IsDefault switch. I'm expecting the theme and regional settings are applied when a team site is created.

#### Observed Behavior

The regional settings are applied but the theme isn't. When I go to the change the look menu it is empty.

If I do the same with a communication site the theme is applied correctly.

#### Steps to Reproduce

1. Create site script with applyTheme and setRegionalSettings verbs.
2. Deploy script and design using PowerShell and the -IsDefault switch.
3. Create new team site.

**Comment by sophieryder** [comment]
@bcameron1231 I can confirm the following:

- Yes, I specified the default site design as web template 64
- I've attached the script I used here: 
[CustomTeamSiteScript.txt](https://github.com/SharePoint/sp-dev-docs/files/2795267/CustomTeamSiteScript.txt)
- Yes, the theme I'm trying to apply is a custom theme

Let me know if you want any more info.

**Comment by bcameron1231** [comment]
I was unable to reproduce. I copied your site script and created a new one. I set the Site Design to be default, and I've tried provisioning a site through UX and through code and it applied the theme color correctly. 

My current thoughts are:

- Confirm the theme name is correct
- Confirm your Site Script is valid

You can get the site script value using Get-SPOSiteScript and confirm it is valid. 

In your observed behavior, you mentioned the change the look wasn't working?  Can you confirm it is just like this Issue #3072 ?

**Comment by sophieryder** [comment]
The theme name is definitely correct and I can confirm the site script is valid and I can return it using Get-SPOSiteScript.

I looked at #3072 (sorry, I didn't come across this when I was looking through issues) and I think this issue is the same thing.

Many thanks,

Sophie
