### ISSUE TITLE
MS Graph issue when programmatically creating an extension

### ISSUE THREAD

**Issue by george-tymvios** [SharePoint/sp-dev-docs#3328]
I get the following error when I programmatically try to create an extension in my SPFx solution:
"maximum number of extensions values supported per application is 2." 

Is there a way to increase the limit or another method to create extensions for all users? I am using the /me/extensions path. If I use the MS Graph explorer, I can create the extension manually with no errors.
Any help on the topic is greatly appreciated.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by patmill** [comment]
Sorry George - I've got no idea what this error refers to.  I think the word extension is overloaded here.  Can you paste the code / API you are calling to create the extension?

**Comment by bcameron1231** [comment]
MS Graph Extensions are limited to 2 per application. See documentation [here ](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/34728316-expand-the-graph-open-extension-limitations)

There is a [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/34728316-expand-the-graph-open-extension-limitations) to extend this beyond 2.

**Comment by patmill** [comment]
Ah, got it.  So this has nothing to do with SharePoint extensions or sp-dev-docs.  I think UserVoice and reaching out to the MSGraph community (which it sounds like you have done) is the right path.

**Comment by george-tymvios** [comment]
Thanks for the answer guys, I must have missed that part in the docs. The weird part is that if I manually go in the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), I am able to create my extensions.
I use this path: https://graph.microsoft.com/v1.0/me/extensions
and then I make a post call.
What do you think is the best approach to go around the limitation other than saving multiple entires in the same extension?

**Comment by patmill** [comment]
Again - these are graph extensions, which we have nothing to do with (and personally no experience with).  If I were to take a guess, I would guess that running the code from the *.sharepoint.com domain with the default permissions that the domain has results in a different registration mechanism taking place in graph - but that's just a guess.
