### ISSUE TITLE
Deploy only on specific custom list

### ISSUE THREAD

**Issue by enti333** [SharePoint/sp-dev-docs#3330]
[X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello. How to deploy the button only on specific list. No on all custom list but only on specific list with same name. Thank you

**Comment by bcameron1231** [comment]
Can you expand a bit more on what you mean? It's a bit unclear.

**Comment by enti333** [comment]
Sorry my mistake. I forgot to say...
1. SharePoint Online 
2. Community Site (Modern New Design)
3. SharePoint Framework Extension - Command Set
I am preparing complex application in modern design for example I have 10 List and every list will have two special buttons... So very easy task..
But the problem is that I need to add these buttons only to specific lisst So I need to register these buttons not directly on all CustomList (RegistrationId = 100) but directly on the list1 list2 list3...list10....

I think that this is not  possible right now and only chance to do this is check URL get info about the list and set visibility to false if is not correct list....

But this is not effective at all if I will have 100 buttons?
Hmm...

I very very like SPFX and also extension features but I am still missing base functionality which was in old UI...I know that SPFX I can vote for some features but I think for example to write something like this is not so much complicated because in workbench I am connections this button directly on specific list....Hmm.... 
Thank you very much for any help

**Comment by patmill** [comment]
The controls you currently have (described here - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions ) allow you to execute the extension on a particular WebTemplate and ListTemplate.

From a feature / forward looking perspective, what additional configuration property would you need?

Alternately, you can simply register the extension only on the particular list instance you are interested in.  (ie, register the customaction on ListInstance1 and ListInstance2.  Depending on how you create those lists, you should be able to have the custom action registration be part of the list creation.

Does that help?

**Comment by andrewconnell** [comment]
> "Alternately, you can simply register the extension only on the particular list instance you are interested in." Please I don't understand this... How to achieve this... For example I have Generic List with name "List1" I have Generic List with name "List1"

You're likely going to have to do this programmatically with the SharePoint REST API / CSOM by getting a reference to the list. Each list object has a `CustomActionElements` collection and each `CustomActionElement` has a `ClientSideComponentId` & `ClientSideComponentProperties`... similar properties you see in the XML generated by the SPFx generator.
