### ISSUE TITLE
Site Designs GUI Fails to Install SPFX Package

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-dev-docs#3337]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFX App's Installed

#### Observed Behavior
SPFX Fails to install from Web GUI

Site Design Works Perfect from Powershell

#### Steps to Reproduce

1. Create Site Design which installs SPFX Package
2. Apply Site Design using web interface

**Comment by pljfdi** [comment]
This had been happening sporadically to us too, but over the past few days it happens everytime the site design is run.

A sitescript that installs a solution. It's the first script in the design. Fails to install. The rest of the site design works fine.
When you create a site collection with the site design, the 'Getting a few things ready' panel is not updated, and you only see the initialising spinner. After a while, the site design has completed, but the spfx is not installed.
Applying the Site Design after a collection has been created, you can see all the steps now, but it still fails.
