### ISSUE TITLE
CommandSet change iconImageUrl dynamically or during deployment

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#3338]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The iconImageUrl for a CommandSet extensions can be defined at build time in the CommandSet Manifest. I'd like to be able to change the icon during deployment (or even runtime).

Is it possible to change the icon command set icon using Add-PnPCustomAction for example?

**Comment by andrewconnell** [comment]
You can't change it at runtime... can't speak to the **Add-PnPCustomAction** cmdlet... if they were in code you could swap them out in the webpack bundling process using a plugin, but I don't think the manifest JSON files are processed at all by webpack.

So... you could create your own process, such as:
1) create your own gulp task that you run after **gulp bundle**
2) run JS that does string replacement on the manifest (similar to what the webpack plugin dones)
3) then when you run **gulp package-solution**, it uses the modified manifest file vs. the one in your source.

**Comment by andrewconnell** [comment]
> My need is to be able to change the icon or button label in either 2 or 3. I understand that it is possible to change the extension properties without having to repackage it. I'd like to be able to do the same for the icon and label without having to deploy multiple different versions of the package where the only difference is in the manifest file...

This part is simply not possible: _without having to deploy multiple different versions of the package where the only difference is in the manifest file_

The manifest file can't be changed per deployment... it's per built package. Your requirement is simply not possible with the current implementation.
