### ISSUE TITLE
SPFx Webpart Lifecycle.

### ISSUE THREAD

**Issue by vikasbansal9888** [SharePoint/sp-dev-docs#3339]
Hi Team,
Please provide information on the life cycle events.
1. SPFx webpart
2. SPFx webpart when react control is added

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
What exactly are you looking for? The page lifecycle doesn't really apply here.

Once SPFx is loaded, it starts to initialize all the web parts on the page, indicated by the `OnInit()` event. Then when it's time to paint the web part on the page, the `render()` method is called.

React web parts aren't special as they are added to the page from within the `render()` method by using `React.render(htmlElement, reactComponet)`. From there, the [React component life cycle](https://reactjs.org/docs/state-and-lifecycle.html) applies.

**Comment by vikasbansal9888** [comment]
I'm new to SPFx and want to create a webpart with webpart custom properties (PropertyPaneConfiguration). As on-premise webpart has life cycle event `OnInit()`, `LoadViewState()`, `CreateChildControls()`, `OnLoad()`, `OnPreRender()`, `Render()`.

So similar to them I want to configure the webpart, read and perform operation on properties at the runtime. I want to relate the SPFx webpart implementation to the classic webpart stytle.

Please provide more details on this with code snippet.

**Comment by andrewconnell** [comment]
Most of those are things that apply to the server-side ASP.NET page lifecycle & don't translate to the client-side. The only two that really apply to client-side are `OnInit()` (_which does the same... it runs when your web part is being initialized_) & `Render()` (_which does the same thing_).

The others, `CreateChildControls()`, `OnLoad()`, & `OnPreRender()` don't translate to client-side. You can always hook into the DOM page events... nothing special with SPFx.

But for what you're doing, it might be best if you run through [this doc to see how custom properties & the property pane work](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/integrate-with-property-pane). There are also some basic training materials here: http://aka.ms/spfx-training

Then ask questions if things aren't making sense.

**Comment by vikasbansal9888** [comment]
@andrewconnell thanks for the help.

**Comment by eschrader** [comment]
I am getting an error about the OnInit vs OnRender with the footer example web part in SPFX.
https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/react-application-regions-footer/src/extensions/yammerFooter/YammerFooterApplicationCustomizer.ts

`  public async onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    // Added to handle possible changes on the existence of placeholders
    // this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);
    // this.context.application._layoutChangedEvent.add(this, this._layoutChanged);
    
    // Retrieve the menu items from taxonomy
    Log.info(LOG_SOURCE, `Creating instance of SPTermStore.SPTermStoreService`);
    Log.info(LOG_SOURCE, `spHttpClient: ${this.context.spHttpClient}`);
    Log.info(LOG_SOURCE, `siteAbsoluteUrl: ${this.context.pageContext.web.absoluteUrl}`);
    let termStoreService: SPTermStore.SPTermStoreService = new SPTermStore.SPTermStoreService({
      spHttpClient: this.context.spHttpClient,
      siteAbsoluteUrl: this.context.pageContext.web.absoluteUrl,
    });

    Log.info(LOG_SOURCE, `SourceTermSetName: ${this.properties.SourceTermSetName}`);
    this._bottomMenuItems = await termStoreService.getTermsFromTermSetAsync(this.properties.SourceTermSetName);
        
    // Call render method for generating the needed html elements
    this._renderPlaceHolders();

    return Promise.resolve<void>();
  }`

This example only has OnInit, but calls render placeholder. I noticed when I navigate to subpages I get an error, most likely because the page is not redrawing correctly. Is the above code best practice, or should it be adjust with an onRender?
