### ISSUE TITLE
Deploy webpart updates

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#334]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Desired Behavior
I would love to have the possibility to update a webpart on the CDN without the need to re-upload the .spapp to Sharepoint

#### Observed Behavior
When I run `gulp --ship` it creates a new bundle in .\temp\deploy (with a filename different from the previous one). I deploy this to Azure `gulp deploy-azure-storage --ship`, but now my Sharepoint package is still pointing to the old bundle file.
So now I have to create a new .spapp and upload it to Sharepoint. Not a big problem for now, but in the near future I would like to upload this package to multiple Sharepoint tenants. So it would be great if I could deploy updates for all tenants at once.

#### Possible solutions
I could think of a these solutions:
- Rename the bundle before deploying to the CDN
- Automate the uploading of the .spapp

But I can imagine someone already thought about this and this is already possible.

**Comment by amishra0909** [comment]
Thanks for the feedback @RoelVB . This is a feature enhancement request and there is a different workflow to follow. Please post your request on our UserVoice. The link is here: https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform
