### ISSUE TITLE
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

### ISSUE THREAD

**Issue by paigeflourin** [SharePoint/sp-dev-docs#3342]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Observed Behavior

get this error in IE11 Classic Page only. when i tried to add teh webpart on a modern page somehow it works. is it a know issue? 

This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

![image](https://user-images.githubusercontent.com/6951524/51823909-b89e9300-231b-11e9-929b-89044134410f.png)

--

**Comment by andrewconnell** [comment]
Same error with other browsers? For kicks, what versions of Node.js, NPM & SPFx? SPO/SP onprem (version)?
