### ISSUE TITLE
SPFX and Graph API: ResourceNotFound at retrieving mails "/me/messages" 

### ISSUE THREAD

**Issue by mfdezvil** [SharePoint/sp-dev-docs#3348]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm working on a SPFX webpart with ReactJS that does service calls to MS Graph API REST in order to show user data: user's display name ("/me") and user's received mails ("me/messages"). 

#### Observed Behavior

While current user info is showing properly with "/me" Graph API service call, I cannot retrieve user emails with "/me/messages". I've got an error:

Request URL: 
`https://graph.microsoft.com/v1.0/me/messages?$select=receivedDateTime,from,subject&$filter=isDraft%20eq%20false&$orderby=receivedDateTime%20DESC`

Response:
```
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Resource could not be discovered.",
    "innerError": {
      "request-id": "c54e3ad8-73c8-40cd-a97d-b98c6d2fcb38",
      "date": "2019-01-29T15:58:58"
    }
  }
}
```
If I try same request URL through Graph Explorer works fine and service return mails list.

#### Steps to Reproduce

I've followed tutorials:
- Implement MSGraphClient client service call 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph#use-the-msgraphclient-in-your-solution
- Configurate webpart permissions:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application 

I've assigned (and approved) following permissions to the package-solution.json of my webpart:

```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.ReadWrite"
      }
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      }
    ]
  }

```
The code in order to show mails for the current user is: 

```
  this.props.context.msGraphClientFactory.getClient().then(
    function(client: MSGraphClient) {
      client
      .api("me/messages")
      .version("v1.0")
      .select("receivedDateTime,from,subject")
      .filter("isDraft eq false")
      .orderby("receivedDateTime DESC")
      .get((error, response) => {
        if(error) {
          console.error(error.message);
          return;
        }
        MailHelper.GetMailsFromResponse(response); //Custom helper in order to format successful response
      });
    }
  );
```

Also I checked that in https://portal.azure.com my webpart has delegated permissions for "Read user mail"

#### Submission Guidelines
Maybe it's a configuration/permission problem, but I don't know in which step. I followed official tutorials step by step with no success... Any ideas? Thanks.

**Comment by vman** [comment]
Hi @mfdezvil are you able to make sure the user has a mailbox configured? What happens when you go to https://portal.office.com and navigate to Outlook?

**Comment by mfdezvil** [comment]
Hi @vman , yes, user has mailbox configured properly: if I go to portal.office and then go to Outlook, I can see user's mailbox, with all his emails.

**Comment by lucabandMSFT** [comment]
hey @mfdezvil  can you please provide to us either the package where the solutions sits or if you get some error messages when you make the call, what are the errors you are experiencing? As it stands right now, that is very difficult for us to investigate and we know that the Graph API you are targeting works.

Thanks

**Comment by mfdezvil** [comment]
Hey @lucabandMSFT , sure, I've attached .sppkg package to this post. When I call Graph API from my solution, I get this error:
```
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Resource could not be discovered.",
    "innerError": {
      "request-id": "c54e3ad8-73c8-40cd-a97d-b98c6d2fcb38",
      "date": "2019-01-29T15:58:58"
    }
  }
}
```
Graph API calls work properly for same users on Graph Explorer, so as I said before, I think the problem may be in permissions configuration, but I followed [Microsoft Graph tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application) step by step in order to allow permissions of my webpart and I don't know why doesn't work. Is there any way else to configure webpart permissions and delegated permissions for Graph API? 
Thanks 
[graph-spfx.zip](https://github.com/SharePoint/sp-dev-docs/files/2859304/graph-spfx.zip)

**Comment by bcameron1231** [comment]
@mfdezvil  I have taken your .sppkg file and uploaded it to my tenant. It works as expected. I am able to return the email messages from my inbox.

**Comment by mfdezvil** [comment]
Hi @bcameron1231 , thanks for testing it. I'm relieved because, at least, the code is working (but not to me)... it seems that is a users accounts problem or permissions problem, but not from code. I will research from that. Thanks all for help
