### ISSUE TITLE
Site Script

### ISSUE THREAD

**Issue by iancaro** [SharePoint/sp-dev-docs#3352]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,  I am new to this JSON in SharePoint I am on my pacing of learning them and understanding them.  I an article that I am following and was able to follow everything except for one editing the Site Script.  Please just point me where I can edit this Site Script.  This is the link I am working on.  Thanks!

https://github.com/SharePoint/sp-dev-list-formatting/tree/master/view-samples/document-library

Regards,
Ian

**Comment by VesaJuvonen** [comment]
Hi @iancaro, that's actually a view formatting definition and not a Site Script. Here's few resources to get you started.

* Site Designs and Site Scripts documentation - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview
* Site Designs and Site Script samples - https://github.com/SharePoint/sp-dev-site-scripts

If you were actually referring to column or view formatting (based on the URL you provided), those resources are following.

* Column formatting - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting
* View formatting - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting
* Site Designs and Site Script samples - https://github.com/SharePoint/sp-dev-list-formatting

**Comment by iancaro** [comment]
Hello VesaJuvonen,

Thanks for the reply and information.  However, links you provided I know them how.  Sorry for my ignorance.

Column formatting - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting - I know how to execute this.

View formatting - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting - I know where to execute this

Site Designs and Site Script samples - https://github.com/SharePoint/sp-dev-list-formatting - I dont know where to execute the site script?  After creating new site where I can edit the site script.

Again sorry for my ignorance but I really cant find it.

**Comment by iancaro** [comment]
Hello,  just wanted to know if where I can edit the site scripts.  Thanks!
