### ISSUE TITLE
Unable to open the property pane in view mode in modern page using SPFX

### ISSUE THREAD

**Issue by Jinitshah0803** [SharePoint/sp-dev-docs#3356]
- [ ] Question
- [ ] Typo
- [*] Bug
- [ ] Additional article idea

I am not able to open the custom property pane on button click in view page in modern page.
Thus if i edit the page and try to open the property pane then its working fine and after then publish the page then its working fine.  once i refresh then its again stops working.

Previously it was working fine but suddenly its stops working since last 24 hours.

for opening the property pane we have used this below code
```
this.context.propertyPane.open();
this.context.propertyPane.refresh();
```
Thanks for your help in advance.

**Comment by paddymccallan** [comment]
Experiencing this issue with web-parts integrated into teams tabs. This used to work. Works fine from Sharepoint modern page but not Microsoft teams. Could be a clash of the context keyword.

**Comment by Jinitshah0803** [comment]
No its not working in modern pages. we are using in the modern site and modern page only. we have also created the demo web part which only open the property pane on hyper link and also it behaves same as above.

**Comment by mcmynn83** [comment]
The property pane is only meant to be opened when a page is in edit mode.  We recently fixed a bug where  it was openable in view mode.
