### ISSUE TITLE
Show trending up/trending down icons based on previous version

### ISSUE THREAD

**Issue by petereit** [SharePoint/sp-dev-docs#3357]
In lists that have versioning enabled, is it possible to format a list column to show the trending up/trending down icons based on the change from the previous version of the value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Unfortunately, no. List formatting only has access to the current values of an item. Thanks for the question!
