### ISSUE TITLE
Extra slash at the end of a sentence

### ISSUE THREAD

**Issue by trickpatty** [SharePoint/sp-dev-docs#3359]
In https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites#provision-a-modern-team-site-using-the-office-365-cli - second sentence, there is a typo at the end of the sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites#provision-a-modern-team-site-using-the-office-365-cli)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Fixed on the docs. Notice that you can also personally always click the "Edit" button on the pages and submit a change request/pull request for any pages.
