### ISSUE TITLE
Contact-Card Formatting JSON not working

### ISSUE THREAD

**Issue by Ishan-seth** [SharePoint/sp-dev-docs#3360]
[ 1 ] Bug

#### Expected or Desired Behavior

I was expecting the view as displayed on Github, but instead just see a blank page. 

To get to this, these were the steps that were performed:
1. List created based on the column requirements.
2. Pulled the code down from Github
3. Edited the Google Map API key with a newly generated key
4. Pasted the code in the Format current view and click on saved
5. Nothing happened, can't see any information

Please let me know if i am doing something wrong or is it something else
<img width="1660" alt="screen shot 2019-01-30 at 12 46 07 pm" src="https://user-images.githubusercontent.com/15080785/52011515-10104080-248d-11e9-8593-2d6a18cb118a.png">

**Comment by Ishan-seth** [comment]
Update, it seems that if i clear out the user image it works not sure why though, any ideas ?

**Comment by Ishan-seth** [comment]
++ I was able to add images in there my keeping them in my OneDrive account linking the images to it, it is a bit weird that Sharepoint document library in the same site doesn't work, i will really appreciate it if some one can point out if there is something else going on

**Comment by thechriskent** [comment]
@Ishan-seth I'm not sure I understand the issues you are experiencing. This format is designed to use a Picture column (these columns are just URLs to images stored elsewhere, presumably a local document library). If the picture column is blank for a row, the standard no profile image is used (`/_layouts/15/userphoto.aspx?size=M`).

To get more details you can add `"debugMode":true to the top of the "rowFormatter". You can also check for any error messages in the console using your browser's dev tools (Generally press F12).

Any extra details would be really appreciated! Thanks!
