### ISSUE TITLE
Type in table for Alternatives to Infopath in Sharepoint 2013

### ISSUE THREAD

**Issue by jasonkatz424** [SharePoint/sp-dev-docs#3361]
Following there is a typo: "This is the recommended approach for extending lists by SharePoint power users ."
-There is an extra space after the s in users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bcc3b9-9289-3d66-8c9c-c161e293a569
* Version Independent ID: 3198056e-6ee0-8e2d-2dbe-6f4e1d2eef87
* Content: [Migrate InfoPath forms to SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-infopath-forms-to-sharepoint)
* Content Source: [docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Raised PR https://github.com/SharePoint/sp-dev-docs/pull/4378 to fix this.
