### ISSUE TITLE
Custom action not working in SharePoint 2019 on premise

### ISSUE THREAD

**Issue by schoesa** [SharePoint/sp-dev-docs#3363]
Hi guys and girls,

I have a problem with a custom action in SharePoint 2019 on premise. The custom action adds a link in the menu item of the SharePoint menu bar. It's a mysite collection. 

SharePoint 2013 (it works):
![image](https://user-images.githubusercontent.com/34265840/52038718-3e485b80-2533-11e9-9ae0-5e8920f1dffa.png)

In SharePoint 2019 theres no link (site collection feature is deployed) see here:
![image](https://user-images.githubusercontent.com/34265840/52039107-ec540580-2533-11e9-93bf-e23589b051e2.png)

The crazy thing is that's not visible on the **Person.aspx.** On the default.aspx it's added:
![image](https://user-images.githubusercontent.com/34265840/52039225-3d63f980-2534-11e9-979b-536e4664ca31.png)

It's working fine on the old 2013 on premise SharePoint. I have no idea why it's not added to the person.aspx

Here's the code for the custom action class:
`
         public class EditProfileCustomLink : SPSecurityTrimmedControl
    {
        protected MenuItemTemplate menuItem;
        protected override void CreateChildControls()
        {
            base.CreateChildControls();

            SPUser currentuser = SPContext.Current.Web.CurrentUser;
            SPWebApplication webApplication = SPContext.Current.Site.WebApplication;
                        
            if (currentuser != null && webApplication != null && webApplication.UserSettingsProvider != null )
            {
                try
                {
                    // Get the assigned settings provide
                    SPUserSettingsProvider usp = webApplication.UserSettingsProvider;

                    // Get the source url
                    string sourceUrl = SPContext.Current.Site.MakeFullUrl(HttpContext.Current.Request.RawUrl.ToString());
                    sourceUrl = SPHttpUtility.HtmlEncode(DeltaPage.RemoveDeltaQueryParameters(sourceUrl));

                    string editProfileUrls = string.Format("~site/_layouts/15/EditProfile.aspx?UserSettingsProvider={0}&ReturnUrl={1}",
                        Uri.EscapeDataString(usp.ProviderIdentifier.ToString()),
                        sourceUrl);

                    // Initialize the menu item
                    this.menuItem = new MenuItemTemplate();
                    this.menuItem.Title = SPUtility.GetLocalizedString("$Resources:EditProfile", Constants.ResourceFile, (uint)CultureInfo.CurrentUICulture.LCID);
                    this.menuItem.Text = SPUtility.GetLocalizedString("$Resources:EditProfile", Constants.ResourceFile, (uint)CultureInfo.CurrentUICulture.LCID);
                    this.menuItem.Description = SPUtility.GetLocalizedString("$Resources:EditProfile", Constants.ResourceFile, (uint)CultureInfo.CurrentUICulture.LCID);
                    this.menuItem.Sequence = 1040;
                    this.menuItem.Visible = true;
                    this.menuItem.ClientOnClickNavigateUrl = editProfileUrls;

                    // Add custom menu item
                    this.Controls.Add(menuItem);
                }
                catch (Exception ex)
                {
                    Logger.Instance.LogError(LogCategory.Web, String.Format("Error while creating edit profile link '{0}'", ex));        
                }               
            }
        }
    }`

The elements.xml:
`  <CustomAction
    Id="29F3F98A-5338-41A3-BFAD-ECEED235873D"
    GroupId="PersonalActions"
    Location="Microsoft.SharePoint.StandardMenu"
    ControlAssembly="$SharePoint.Project.AssemblyFullName$"
    ControlClass="Brose.ProfileDisplay.Source.EditProfileCustomLink" >
  </CustomAction>`

**Comment by schoesa** [comment]
What means soon as possible? One week or 1 year? Still no feeback from you guys.

**Comment by Hiral2010** [comment]
Custom action still not working in SharePoint 2019 on premise.
Is there any update related to this?

**Comment by JereckNET** [comment]
Same problem here.

This `elements.xml` works, the ascx user-control is included :
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <Control Id="QuickLaunchBottom"
           Sequence="95"
           ControlSrc="~/_CONTROLTEMPLATES/15/xxx.yyy/zzz.ascx" />
</Elements>
```
This one (with the `SafeControl` added to the `web.config`) does not :
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <Control Id="QuickLaunchBottom"
           ControlAssembly="$SharePoint.Project.AssemblyFullName$"
           ControlClass="xxx.yyy.zzzControl"  />
</Elements>
```
```xml
<SafeControl Assembly="xyz, Version=1.0.0.24383, Culture=neutral, PublicKeyToken={public key token}" Namespace="xxx.yyy" TypeName="*" Safe="True" />
```
Another mystery/surprise/undocumented limitation added to SP2019 to accommodate O365 ?

**Comment by JereckNET** [comment]
Nice ...
