### ISSUE TITLE
Newtonsoft Version conflicts with Azure Functions V1 and SharePointPnPCoreOnline

### ISSUE THREAD

**Issue by matsla** [SharePoint/sp-dev-docs#3364]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

AzureFunctions V1 is locked to NewtonSoft.Json 9.0.1 and later SharePointPnPCoreOnline packages use Newtonesoft.Json version 10.0.3. To be able to use Azure Functions we have to use SharePointPnPCoreOnline 2.24.1803 that is the latest build using NewtonSoft.Json 9.0.1 from 2018-03-06. 

Will there be a .NET Core version of SharePointPnPCoreOnline to be used with Azure Function V2?
Why can't you build the latest version of SharePointPnPCoreOnline using NewtonSoft.Json 9.0.1 so we can use the latest release of SharePointPnPCoreOnline?

// Mats

**Comment by estruyf** [comment]
@matsla you can overcome this issue by manually adding the `NewtonSoft.Json` version 10.0.3 to your project via NuGet. That way you can install the `SharePointPnPCoreOnline` dependency without any issue.

**Comment by matsla** [comment]
@estruyf thanks for the advice, yes I know that this is possible. But is it safe/supported to using NewtonSoft.Json version 10.0.3 in Azure Functions when dependent on 9.0.1 , may we get any Azure Functions runtime error?

**Comment by estruyf** [comment]
Yes, that is also the advice of the Azure Functions team. Check their GitHub page: https://github.com/Azure/azure-functions-vs-build-sdk

**Comment by matsla** [comment]
@estruyf great this is perfect. 

Do you know anything regarding .NET Core version of SharePointPnPCoreOnline to be used in Azure Functions V2?

**Comment by andrewconnell** [comment]
Closing as appears this is answered & resolved... feel free to reopen this issue if otherwise (might have been more appropriate to post to the PNP POSH repo: https://github.com/SharePoint/PnP-PowerShell
