### ISSUE TITLE
Invalid chars set injected by macs

### ISSUE THREAD

**Issue by Dangerous-Mind** [SharePoint/sp-dev-docs#3366]
Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Inserting the same file in mac or windows should save with the same exact name.

#### Observed Behavior

If the filename has special chars (ç, ã, ê, etc).
In mac the uploaded file name chars are different than in windows and from mac in the classic upload.

#### Steps to Reproduce

Upload a file with special chars to a library in mac in modern view.
Convert the name of the file in windows to ASCII.
Upload the same file on windows in modern view.
Convert the name of the file to ASCII
Compare the two file names.

#### Submission Guidelines

This happens in modern pages like document library and on developed web apps causing several problems including file not found error on returned queries to the search engine (the search engine normalizes the returned filename url but it does not normalizes the saved file address).

Example filenames and converted:

```
UTF-8						|ASCII
çãõ   - Original (File)				|Ã§Ã£Ãµ   - Original (File)
çãõ_1 - Windows - Chrome (Drag Drop)		|Ã§Ã£Ãµ_1 - Windows - Chrome (Drag Drop)
çãõ_2 - Mac Safari Modern (Upload)		|cÌ§aÌoÌ_2 - Mac Safari Modern (Upload)
çãõ_3 - Mac Safari Modern (Drag Drop)		|cÌ§aÌoÌ_3 - Mac Safari Modern (Drag Drop)
çãõ_4 - Mac Safari Classic (upload)		|Ã§Ã£Ãµ_4 - Mac Safari Classic (upload)
```
Tested in Portuguese.

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we are unable to process is from this channel. Please report it by using SharePoint Online tenant admin support UIs. Sorry for the inconvenience.

**Comment by Dangerous-Mind** [comment]
Hi, 

It happens on any new spfx developments. Its not a SharePoint online problem. 
I have to filter the charts to prevent it from happening on my web apps.
It doesn't happen on Sharepoint classic mode. Only on modern spfx developments.

I already reported to the SharePoint online tenant admin and they didnt solve it
