### ISSUE TITLE
Site Design Create Content Type action gives an invalid type error

### ISSUE THREAD

**Issue by drewortiz** [SharePoint/sp-dev-docs#3368]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the createContentType action in a site design I expect the content type to be created in the site that has been created from a site design which contains that site script.

#### Observed Behavior

When using a createContentType action from the Site Design json schema, I get: One or more of the properties on this action has an invalid type.
![image](https://user-images.githubusercontent.com/406563/52085789-5f30a100-2573-11e9-8ebd-279b9dfb7173.png)

#### Steps to Reproduce

Use https://www.sitedesigner.io/#/ to generate the following JSON schema and save to a file:
{
  "$schema": "schema.json",
  "actions": [
    {
      "verb": "createSiteColumn",
      "fieldType": "Text",
      "internalName": "siteColumn1Text",
      "displayName": "Project Status",
      "isRequired": false,
      "group": "Contoso Custom",
      "enforceUnique": true
    },
    {
      "verb": "createContentType",
      "name": "Contoso Projects",
      "description": "custom list content type",
      "parentName": "Item",
      "hidden": false,
      "subactions": [
        {
          "verb": "addSiteColumn",
          "internalName": "siteColumn1Text"
        }
      ]
    }
  ],
  "bindata": {},
  "version": 1
}

#### Submission Guidelines
Use Powershell to add the script and design: (snippet below)
# TODO: connect

             $testData = @{
                "DesignTitle" = "Tax Portal Test 001";
                "DesignTemplate" = 1;
                "DesignDesc" = "Tax Portal Test 001";
                "ScriptTitle" ="Tax Portal Test 001";
                "ScriptDesc" = "Tax Portal Test 001";
                "ScriptJSONFile" = "..\..\..\SiteAssets\Scripts\json\testScript.json"
              }
        $site_script = Get-Content $currentCSV.ScriptJSONFile -Raw -ErrorAction Stop
        $siteInfo=Add-SPOSiteScript -Title $currentCSV.ScriptTitle -Content $site_script -Description $currentCSV.ScriptDesc
        $SScriptId=$siteInfo.Id 
        if ($SScriptId) {
            Add-SPOSiteDesign -Title $currentCSV.DesignTitle -WebTemplate $currentCSV.DesignTemplate -SiteScripts $SScriptId -Description $currentCSV.DesignDesc
		}

#TODO: disconnect

**Comment by drewortiz** [comment]
sorry there was a typo, $testData should be renamed to $currentCSV:  
 $currentCSV= @{
            "DesignTitle" = "Tax Portal Test 001";
            "DesignTemplate" = 1;
            "DesignDesc" = "Tax Portal Test 001";
            "ScriptTitle" ="Tax Portal Test 001";
            "ScriptDesc" = "Tax Portal Test 001";
            "ScriptJSONFile" = "..\..\..\SiteAssets\Scripts\json\testScript.json"
          }

**Comment by bcameron1231** [comment]
Can you run Get-SPOSiteScript and return the JSON of the site script and paste it here?

**Comment by drewortiz** [comment]
Here it is:
Id          : d4468369-7fbc-4474-9a6c-7cc2972896b1
Title       : Tax Portal Test 001
Description : Tax Portal Test 001
Content     : 
{
"$schema": "schema.json",
"actions": [
{
"verb": "createSiteColumn",
"fieldType": "Text",
"internalName": "siteColumn1Text",
"displayName": "Project Status",
"isRequired": false,
"group": "Contoso Custom",
"enforceUnique": true
},
{
"verb": "createContentType",
"name": "Contoso Projects",
"description": "custom list content type",
"parentName": "Item",
"hidden": false,
"subactions": [
{
"verb": "addSiteColumn",
"internalName": "siteColumn1Text"
}
]
}
],
"bindata": {},
"version": 1
}
Version     : 1

**Comment by bcameron1231** [comment]
Thank you. I was unable to reproduce given the script you just sent. I have grabbed your site script and applied it to my site, it works as expected without error. 

![image](https://user-images.githubusercontent.com/7944457/52574786-3a8dc200-2dda-11e9-88fe-8e139da31307.png)

is this site design & site script being run on a sub site by chance?

**Comment by drewortiz** [comment]
Yes it is being run on a sub site.

**Comment by bcameron1231** [comment]
Ah okay. So I wouldn't say that Site Designs and Site Scripts *aren't* supported in Sub Sites,  but there are issues with site designs on sub sites due to the inheritance of columns from the parent site.

That is, Site Scripts that create site columns on a sub site will break, because the site column already exists from the parent, but the site script doesn't detect that. We've already opened up a ticket on this issue #3333 if you don't mind this ticket being closed and you can provide feedback on that ticket as well.

**Comment by drewortiz** [comment]
Thanks
