### ISSUE TITLE
missing "Edit snippet"

### ISSUE THREAD

**Issue by rdnllc** [SharePoint/sp-dev-docs#3369]
#### Category
- [X] Question

for sp-dev-fx-webparts/samples/react-script-editor/

either in console or deployed to SharePoint Online, all I'm seeing is 

![image](https://user-images.githubusercontent.com/44092322/52090138-7e80fb80-257e-11e9-9af1-d2a5366ea821.png)
Missing the Edit snippet, and therefore the intended function.

I expect this is purely a stupid user trick. 

Any hints appreciated!

/Robin

**Comment by andrewconnell** [comment]
You should be posted to the associated repo's issue list: https://github.com/SharePoint/sp-dev-fx-webparts/issues
