### ISSUE TITLE
Hitting 'X' in a non-reactive property pane doesn't reset the values in the property pane

### ISSUE THREAD

**Issue by patmill** [SharePoint/sp-dev-docs#337]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When hitting 'X' in a non-reactive property pane, then hitting edit again, the expectation would be that the property pane shows the currently saved values for the properties.

#### Observed Behavior
When you go back to the property pane, the previously edited values (not the saved values in the webpart) are shown.

**Comment by manishgarg1** [comment]
Fix is in progress.

**Comment by jaredbuttars** [comment]
Hopefully a fix for this comes soon...

In addition, the "Apply" button should save the changes and close the property panel. Also, a cancel button that serves the same purpose as the X in the top right corner would help users a lot.

**Comment by srideshpande** [comment]
The fix is checked in. It should be out in public in a week. Please check back on Friday, the 12th.

> the "Apply" button should save the changes and close the property panel

We have not done this intentionally to avoid unnecessary screen redraws on the user.


> a cancel button that serves the same purpose as the X in the top right corner would help users a lot.

We had a discussion on this and tabled it for now. I will bring this up with the designers again.
