### ISSUE TITLE
Can't apply Site Design using Rest API ApplySiteDesign or PowerShell cmdlet Invoke-SPOSiteDesign

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3370]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

`/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.ApplySiteDesign` REST endpoint and `Invoe-SPOSiteDesign` cmdlet add Site Design to the web.

#### Observed Behavior
Nothing happens.

#### Steps to Reproduce

For REST API:
```
POST https://tenant.sharepoint.com/sites/testsite/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.ApplySiteDesign

{"siteDesignId":"site-design-id","webUrl":"https://tenant.sharepoint.com/sites/testsite"}
```
PnPJS + SPFx
```typescript
await sp.web.siteDesigns.applySiteDesign(siteDesign, this._context.pageContext.web.absoluteUrl);
```

PowerShell
```powershell
Invoke-SPOSiteDesign -Identity site-design-id -WebUrl "https://tenant.sharepoint.com/sites/testsite"
```

I know that there is a `Add-SiteDesignTask` cmdlet and `AddSiteDesignTaskToCurrentWeb` REST endpoint that is used when applying site design from UI.
But if previous ones are "obsolete" why don't just remove them and announce that we don't need to use them?

**Comment by AJIXuMuK** [comment]
My bad - I have 30+ actions (mostly - sub actions).

**Comment by iancaro** [comment]
Hello Guys,  I am currently experiencing this problem right now.  When using the Invoke-SPOSiteDesign -Identity site-design-id -WebUrl "https://tenant.sharepoint.com/sites/testsite" I have no respose from the pwoershell - I don't see the result whether Success/failed/noop it will just return to command prompt.  I was working 5 days ago now in every site I tried its not responding anymore.  Any ideas whay might happened?
