### ISSUE TITLE
has anyone got the jquery accordion to work using a list api and query selector? styles not applied.

### ISSUE THREAD

**Issue by cpluceDev** [SharePoint/sp-dev-docs#3371]
has anyone got the jquery accordion to work using a list api and query selector? styles not applied. I can get the tutorial to work with the template. I can also get the list data with the api and query selector. however, the styles are not applied when using a list api data source. can you share ts code?

**Comment by StfBauer** [comment]
There is a related issue #3375 on that. Can you share your code? This way it is easier to reproduce your overall setup and issues you might run into.

Your problem description doesn't offer much information on how you accessed the list data for example.
