### ISSUE TITLE
Connect SPFx webpart and SP list using dynamic data #773

### ISSUE THREAD

**Issue by HeinPauwelyn** [SharePoint/sp-dev-docs#3379]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I know a SPFx webpart can be connected to another SPFx webpart using `PropertyPaneDynamicFieldSet` and `PropertyPaneDynamicField`. My question is can a webpart being connected to a SP list?

I'll connect a webpart to a list to create or edit items from that list. This I'll do because the webpart contains a form where some fields depends on another field and repeating sections.

**Comment by andrewconnell** [comment]
No, you can't connect a web part to a list using dynamic data. But there is a list notification service (implemented using socket.io) that you can look at to implement the functionality you describe: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications

**Comment by HeinPauwelyn** [comment]
This is not what I mean. I'll to replace the default action, because some fields depends on an other field.

![image](https://user-images.githubusercontent.com/16222780/52951824-19514680-3383-11e9-89e3-ec4d1a974009.png)

See [this question](https://sharepoint.stackexchange.com/questions/256873/replace-default-new-action-to-custom-created-command-spfx) from SharePoint Stack Exchange for more info.

**Comment by andrewconnell** [comment]
The answer you got in SO is correct... you can't remove the existing button. Removing permissions will not only remove the button from the list, but you'll break your new button's ability to write to the list too because changing the permissions doesn't just impact the UX, it impacts the actual rights of the user.

**Comment by HeinPauwelyn** [comment]
Would that feature being added in the future?

**Comment by andrewconnell** [comment]
Microsoft hasn't said, but you can submit a feature request at https://aka.ms/sp-dev-uservoice
