### ISSUE TITLE
How do I get Terms from termstore using SharePoint Framework?

### ISSUE THREAD

**Issue by leifwalder** [SharePoint/sp-dev-docs#338]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Successfully fetch terms from term-store from a SharePoint Framework-app.

#### Observed Behavior
Fetching Mocked up data works fine.
Fetching real data from my o365-tenant gives me this error:
`

> [SPWebPartErrorCode.ScriptLoadError]:: Det går inte att läsa in skriptresurser för webbdelen WebPart.undefined.255db694-1b49-4bac-a6d1-990bbbaeb6e3,TypeError: Cannot read property 'type' of undefined på grund av: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-client-base_sv-se_899e14970aaef71dbcbcd91de5d6b91f.js:48:11145) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_sv-se_0ea5703a63ae7b404f2389ac7097d7ae.js:47:21019) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_sv-se_0ea5703a63ae7b404f2389ac7097d7ae.js:47:21432) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_sv-se_0ea5703a63ae7b404f2389ac7097d7ae.js:47:3096

`

#### Steps to Reproduce
I am using this sample:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/knockout-taxonomy
I followed the instructions to run the sample.
When I try it in my o365-tenant to get real data i get the error I listed above. Note that I am successful in fetching e.g. lists from my o365-tenant using SharePoint Framework

**Comment by patmill** [comment]
Are you running RC0 or Drop 6?

**Comment by leifwalder** [comment]
@patmill Where do I check that information? Thank you for your reply!

**Comment by patmill** [comment]
If you look at the package.json file in your webpart directory, what version of sp-client-base is referenced?  If it is 0.7.0, you have RC0.  Normally we wait until it has rolled everywhere before we publish it to npm, but we switched this one time because it will break existing parts.

**Comment by leifwalder** [comment]
@patmill "@microsoft/sp-client-base": "~0.5.1",

**Comment by patmill** [comment]
@leifwalder - Sorry Leif, I've been trying to get to this, but keep getting pulled into other work.  I'll take a look over the long weekend here and see if I can repro your issue.

**Comment by leifwalder** [comment]
@patmill Thank you, I appreciate it. Let me know if you find out anything. I will do the same.

**Comment by leifwalder** [comment]
This problem is definately related to wrong version with spfx, thanks @patmill 
Reading this information got me on the right track
https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0

To anyone trying to get the sample to work:
If you are attempting to update your spfx(npm package) and get the sample to work:
**1. create a new spfx project(latest version)
2. copy files and folders into new project from sample
3. change \src\webparts\helloWorld\data-helpers\DataHelpersFactory.ts to this:**
`import {
  IWebPartContext
} from '@microsoft/sp-webpart-base';
import { EnvironmentType } from '@microsoft/sp-core-library';
import { IDataHelper } from './DataHelperBase';
import { DataHelperMock } from './DataHelperMock';
import { DataHelperSP } from './DataHelperSP';
export class DataHelpersFactory {
  public static createDataHelper(context: IWebPartContext): IDataHelper {
      return new DataHelperSP(context);
  }
}`
**4. change \src\webparts\helloWorld\HelloWebPart.ts to this:**
`import { Version } from '@microsoft/sp-core-library';
import {
  BaseClientSideWebPart,
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-webpart-base';
import { escape } from '@microsoft/sp-lodash-subset';
import styles from './TermSetRequester.module.scss';
import * as strings from 'helloWorldStrings';
import { IHelloWorldWebPartProps } from './IHelloWorldWebPartProps';
import { TaxonomyControl } from './controls/TaxonomyControl';
export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  public render(): void {
    this.domElement.innerHTML = '<div class="${styles.termSetRequester}"><div class="${styles.container}"></div></div>';
      const container: HTMLDivElement = this.domElement.querySelector('.' + styles.container) as HTMLDivElement;
      var termStoreCtrl = new TaxonomyControl(this.context);
      termStoreCtrl.render(container);
  }
  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }
  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}
`
**I got it to work in the 0365 workbench, as that was what I needed.**
