### ISSUE TITLE
PropertyPane not opening within Microsoft teams tab.

### ISSUE THREAD

**Issue by paddymccallan** [SharePoint/sp-dev-docs#3387]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behaviour

Open Property pane button inside web-part. It Should open side property pane when clicked.

#### Observed Behaviour

Inside teams-tab property pane of web-part app does not fire an event. Clicking has no reaction.

#### Steps to Reproduce

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab. Create a web-part following this guide - Make use of 'this.context.propertyPane.open()' on a button to open property pane. This works as expected through SharePoint modern sites. But not within teams.

**Comment by VesaJuvonen** [comment]
This is by design during a preview of the Teams tab development. We will be supporting opening up the property pane with the GA release of the SPFx Teams Tab development with SPFx v1.8 release. ETA by end of this quarter.

**Comment by paddymccallan** [comment]
@VesaJuvonen Can you suggest any work-arounds temporarily for this?
