### ISSUE TITLE
SharePont Add-in app parts would not appear at available control list for modern page

### ISSUE THREAD

**Issue by windfly2006** [SharePoint/sp-dev-docs#3388]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The SharePoint Add-in Parts should be always available for control list when adding a control to a modern page

#### Observed Behavior

It would be available if I added the SharePoint Add-in to the site for the first time. If I delete the Add-in and re-add, it won't be available especially I add Add-in Parts to a page and publish the page and then later delete the parts from the page and then delete the Add-in from site contents. 

#### Steps to Reproduce

The issue is same for both store add-in or add-in uploaded to app catalog:

1. add an Add-in with Add-in Parts to the site such as https://appsource.microsoft.com/en-us/product/office/WA104380321?src=Office&tab=Overview to the site
2. go to a modern page and then add the add-in parts to the page, then publish the page. 
3. edit the page again and delete the add-in parts from the page and then publish the page
4. delete the Add-in from the site
5. re-add the Add-in to the site
6. edit the page again and the Add-in won't be show up in the available control list. 

we saw same behavior on the our test env and also customer's production env. 
[SharePoint Add-in Issues.docx](https://github.com/SharePoint/sp-dev-docs/files/2823038/SharePoint.Add-in.Issues.docx)

**Comment by windfly2006** [comment]
any update? thanks.

**Comment by andrewconnell** [comment]
Thanks for the submission... MSFT is investigating...
