### ISSUE TITLE
Unable to add tab

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-docs#3389]
Hello,

As described, I have created the solution and it's working as expected in local workbench as well as hosted site.Then, I have created a package as suggested which got uploaded successfully in teams, however when I tried to add as tab, I face following error:

Sorry, something went wrong
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
TECHNICAL DETAILS
Error details: Error: ***Error initializing application. Error: Error: ***Error initializing application. Error: Error setting up Teams environment in TeamsInitializer: Error: ***Manifest not found for component id "544520a0-0b8d-4608-a4fe-761009e4034c".

What could go wrong ? How can I resolve it ?

Thanks and Regards,
Dipti Chhatrapati

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This would indicate the sppkg file is not properly deployed in the SharePoint app catalog. If you have followed the steps in the tutorial, please double check that you have deployed the sppkg file successfully to the catalog with tenant-scoped deployment enabled.

**Comment by dips23** [comment]
Yes, It worked out in next attempt, Thank you Vesa, Regards, Dipti Chhatrapati

**Comment by v-prabus** [comment]
@andrewconnell , Can you please let me know why necessarily the scope should be tenant level for the spfx webpart that to be available to microsoft teams?
