### ISSUE TITLE
Azure Devops unit test example doesn't fail build when tests fail

### ISSUE THREAD

**Issue by gregwilton** [SharePoint/sp-dev-docs#3390]
When following the steps listed in the [Executing Unit Tests](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops#executing-unit-tests) section (using SPFx 1.7), the Azure Pipelines task will succeed regardless of whether there are any failing tests. I was expecting the build to fail if the tests fail.

I think the `--ship` argument needs to be added to the Gulp task as the `gulp test` command only seems exit with a non-zero exit code on production builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by baywet** [comment]
@gregwilton sorry for the late reply. Since then we've updated the documentation to leverage Jest instead of Karma which was removed. Did you get a chance to try again with the new testing configuration?
