### ISSUE TITLE
🐞Broken experience with custom web parts in colored sections on modern experience pages

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3391]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Web part should inherit at least background and font colour at least from the '.CanvasZoneContainer' instead of faulty overspecify styles.

#### Observed Behavior
Placing a web part with no styling at all lead to the following experience:

![screenshot 2019-02-03 at 14 12 22](https://user-images.githubusercontent.com/5503835/52177236-3bad6680-27be-11e9-8be1-bb2c3a156578.png)

The issue is caused because .CanvasZone, .CanvasSection, .Controlzone, .ControlZoneEmphasisBackground overspecify a background color of white on each of the containers. In the end, a third party web part end up with white text on white background. The colour on the hand is not "overspecificed".

![screenshot 2019-02-03 at 14 12 35](https://user-images.githubusercontent.com/5503835/52177272-afe80a00-27be-11e9-982b-3c74cc376e74.png)

The web part, in this case, doesn't use any styling at all and just render 'Hello World'.

An intermediate fix to this issue can be accomplished with the following CSS that forces to the inheritance of 'background-color' and color properties from the '.CanvasZoneContainer' element where the "Colored Section" base properties are defined.

```css
:global {
  .CanvasZone,
  .CanvasSection,
  .Controlzone,
  .ControlZoneEmphasisBackground {
    background-color: inherit;
    color: inherit;
  }
}
```

The result of this fix is a correct displayed web part.

![screenshot 2019-02-03 at 14 24 34](https://user-images.githubusercontent.com/5503835/52177313-7663ce80-27bf-11e9-8a85-166f6b3cd856.png)

This fix works for the 'Neural':
![screenshot 2019-02-03 at 14 27 19](https://user-images.githubusercontent.com/5503835/52177347-d8243880-27bf-11e9-978e-2e1b23b1ef0c.png)

As well as 'Soft':
![screenshot 2019-02-03 at 14 28 25](https://user-images.githubusercontent.com/5503835/52177359-fd18ab80-27bf-11e9-9f76-24314d86374f.png)

as well as 'None':
![screenshot 2019-02-03 at 14 29 39](https://user-images.githubusercontent.com/5503835/52177371-29342c80-27c0-11e9-91a4-62e9b90d2689.png)

#### Steps to Reproduce
* Create an empty web part that does not have any style included at all.
* Place the web part on a colored section on a SharePoint Page.

**Comment by tdwhite0** [comment]
@StfBauer I'm noticing a weird issue with some leaking styles too, at first I thought it was something I caused but it does happen on OOB too. Not on every tenant though. Anywhere there is a tooltip hover, the background of the hover is themePrimary:
![image](https://user-images.githubusercontent.com/2566323/52177480-5b796600-278f-11e9-8d59-5d05c91b76cb.png)

**Comment by StfBauer** [comment]
@tdwhite0 haven't seen this one.

**Comment by tdwhite0** [comment]
@StfBauer Yeah, it was my fault. My bad.

**Comment by pk091990** [comment]
@StfBauer I've applied above workaround in one of my custom spfx webpart and it worked fine as it removes extra white background . However I'm using some office fabric UI components (ex. ChocieGroup ) which are not inheriting color based on section background. I've posted same issue here also https://github.com/SharePoint/sp-dev-fx-webparts/issues/786.
So do we need to individually override each component css or Microsoft will provide any permanent solution which will minimize the extra effort? Thanks !

**Comment by StfBauer** [comment]
@pk091990 Microsoft will release a permanent solution to this. The CSS above is not intended to be used. The CSS classes are just used to present possible issues that currently exist and need to be addressed in a permanent solution.

Until that happens, I would recommend not to use coloured section for third-party web parts.

**Comment by BigBd1** [comment]
I have encountered the same behavior when default client side webparts are added through PnP Template provisioning or CSOM. Here is an example with the News webpart (NewsReel type), the first one is added programmatically and the second one is added manually with the UI 

![image](https://user-images.githubusercontent.com/4406847/53582036-03136980-3b7f-11e9-8db9-6f6fe25e9c19.png)

**Comment by VesaJuvonen** [comment]
We will be releasing documentation and guidance on this area as part of the 1.8 release.

**Comment by vels-io** [comment]
Any updates on this issue? we have been facing this issue on the client-side webparts.

**Comment by phill29** [comment]
I'm facing a similar problem I have several custom spfx web parts but one in particular is bringing in the emphasis-background style. I'm in the process of updating my webparts to work with section colours and change styles as appropriate. For my other webparts this has been straightforward. I've used the theme provider and semantic colours to apply styles to the webpart content. However, for the webpart with this issue, the themeVariant is the same every time - the event is firing and updating the variable. When I change the section colours, the semantic colours are the same every time. The exact same code works in other webparts but there's something special about this one. The webpart has been upgraded to 1.8.2 as have others.

**Comment by GuptaAnubhav** [comment]
Any update on this issue? I am still facing this issue when adding News webpart through PnP Template provisioning.

**Comment by StfBauer** [comment]
At the moment there are some gaps in the documentation yet.

@GuptaAnubhav In the case of provisioning. Have you tried to export a new version of the template and import this version again or do you use a template form before?

**Comment by GuptaAnubhav** [comment]
@StfBauer I had exported a new template yesterday and I am facing the same issue in applying the template.

**Comment by MagtheRag** [comment]
Still no fix for this?

**Comment by StfBauer** [comment]
I am currently testing this for no framework projects and ReactJS. For now no fix or updated documentation.

**Comment by StfBauer** [comment]
I published today a complete guide how to make this experience possible using just CSS - lot of changes since I opened this

[Develop SPFx web parts for different section designs using CSS](https://n8d.at/develop-spfx-web-parts-for-different-section-designs-using-css/)
