### ISSUE TITLE
Authenticating desktop/native applications WebView with SPOIDCRL cookie

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-docs#3392]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

SharePoint is normally accessed trough desktop/mobile browsers using authentication cookies  (**rtfa / fedAuth**) received during authentication. When accessing SharePoint from custom desktop/native applications, the normal way is to use oauth2 access token received using ADAL.

With access token we can leverage data from SharePoint using rest APIs. But to render SharePoint pages in desktop/native application using WebView, is not possible because authentication was done using ADAL (which provides access token) and the authentication cookies are not available.

But there are exceptions, for example **SharePoint App** for iOS/Android. The SharePoint App authenticates using ADAL and accesses SharePoint APIs using access token. But it can also render SharePoint pages using WebView. 

So how is that done? Well before the app loads the SharePoint page in to the WebView, it makes a POST request to undocumented/internal API located at **_api/SP.Oauth.NativeClient/Authenticate**. This API returns a cookie named **SPOIDCRL** in its response headers. After getting this cookie, the app adds it to the WebView and then loads the SharePoint page in to the view.

Unfortunately this undocumented API is not available for Third-party apps. The endpoint verifies the requests by checking the **scope** of the access token and it has to have value **user_impersonation**. This scope is not available in **Azure AD Application** targeted to SharePoint Online.

There is also another endpoint **_vti_bin/idcrl.svc/** to get **SPOIDCRL** cookie. Using that involves much more complicated steps described [here by Vitaly Lyamin](https://blogs.technet.microsoft.com/sharepointdevelopersupport/2018/02/07/sharepoint-online-active-authentication/), and again, not  accessible using access token.

So, my question is: 
Is there another way of getting **SPOIDCRL** cookie using access token? And if not, could it be possible to open **_api/SP.Oauth.NativeClient/Authenticate** API (or to create another API) for Third-party apps to use?

By allowing access to **_api/SP.Oauth.NativeClient/Authenticate** API for Third-party apps, it would allow desktop/native application to leverage the beautiful modern SharePoint UIs using WebViews much more easier (for example [Xamarin.Forms WebView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview) / [react-native-webview](https://facebook.github.io/react-native/docs/webview) / [Electron BrowserView](https://electronjs.org/docs/api/browser-view)). Sharing is caring.

**Comment by andrewconnell** [comment]
@lucabandMSFT would you have any idea on the **SPOIDCRL** question?

@tavikukko For the part about opening the API, I think the best approach is to submit this as a feature request to user voice https://aka.ms/sp-dev-uservoice

**Comment by lucabandMSFT** [comment]
sorry for my delay in answering.
I'm afraid the answer is no: that API is not currently available for 3rd party native clients.
