### ISSUE TITLE
Configure multiple modern SPFx Web Parts on classic pages

### ISSUE THREAD

**Issue by wallissam** [SharePoint/sp-dev-docs#3394]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We have an issue with web parts which have worked perfectly fine in the past, but seem to have broken sometime within the past month without change on our side. Our solution utilises several of the same web part with different configurations (properties set through the 'Edit Web Part' -> 'Configure' menu).

#### Observed Behavior

One modern SPFx web part on a classic page is fine, however upon adding a second web part, neither Web Part's configure menu works any more (clicking 'Configure' doesn't do anything, no console errors)

#### Steps to Reproduce

1. Add a Modern SPFx webpart to a classic SharePoint site page
2. Confirm the configure menu is working
3. Add the same webpart again
4. Confirm the configure menu is now not working

This has been tested with a previously working solution, and a fresh generated HelloWorld web part with a single property.

**Comment by jonathanhotono** [comment]
duplicate to #3345. @VesaJuvonen thanks for the update on this critical issue.

**Comment by VesaJuvonen** [comment]
Fix has been checked in and is currently being rolled out worldwide. Can't provide exact ETA, but the fix should be available soon. This is indeed a duplicate with the #3345. Both are being addressed with the upcoming fix.

**Comment by wallissam** [comment]
Thanks @VesaJuvonen, confirmed fixed in Australia region.
