### ISSUE TITLE
Uncaught (in promise) Error: ***Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db"

### ISSUE THREAD

**Issue by davehax** [SharePoint/sp-dev-docs#3397]
Hi, I've followed the instructions provided and got as far as the heading "Preview the web part in SharePoint" https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part-in-sharepoint

Previewing locally works fine when running "gulp serve". However, attempting to preview in SharePoint Online using the /_layouts/workbench.aspx link fails in Chrome, Edge, and FireFox. Chrome displays the skeleton of the page with no interactive ---(+)--- elements. Edge and FireFox both display a Warning modal that states "Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running."

I've run "gulp trust-dev-cert", of course.

node -v = v8.15.0
npm -v = 6.4.1
@microsoft/generator-sharepoint@1.7.1 

Please let me know if more information is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part-in-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by davehax** [comment]
I've also tried downgrading to @microsoft/generator-sharepoint@1.7.0 and @microsoft/generator-sharepoint@1.4.1. Same results.

**Comment by davehax** [comment]
Update: I managed to get around this by navigating to a non-root Site Collection.

Please consider updating the following instruction under the "Preview the web part in SharePoint" heading:

1. Go to the following URL: https://your-sharepoint-tenant.sharepoint.com/_layouts/workbench.aspx

to

1. Go to the following URL: https://your-sharepoint-tenant.sharepoint.com/sites/your-site-collection/_layouts/workbench.aspx

**Comment by patmill** [comment]
@srideshpande - Any ideas?  The component being referenced is the property pane I believe.

**Comment by andrewconnell** [comment]
I can't repro this... works fine on three different tenants using the workbench at the root site in the tenant. Closing due to no repo...
