### ISSUE TITLE
Nitpicking: conditionally render search button or set a default

### ISSUE THREAD

**Issue by Languafe** [SharePoint/sp-dev-docs#3398]
I spent a couple minutes wondering why the search wasn't working before I realised there is no initial value for the property clientMode. By replacing the JSX for the search button

&lt;PrimaryButton
                    text='Search'
                    title='Search'
                    onClick={this._search}
                  /&gt;

with

{ this.props.clientMode ? 
                  &lt;PrimaryButton
                    text='Search'
                    title='Search'
                    onClick={this._search}
                  /&gt;
                  : &lt;p&gt;Configure client mode by editing web part&lt;/p&gt;
                }

this will be immediately obvious.

I enjoyed the tutorial, but if I could point out something else it would be the order of file edits and interface declarations / imports which provokes errors in VS Code (which I assume most SPFX developers are using) before I've even attempted building, as they occur when I follow the tutorial from start to finish and manually copying or typing the code as instructed. 

For instance, it would make sense to first create the IUserItem.ts file, and then afterwards instruct us to add the code where it is used, perhaps even showcasing auto-import in vs code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
We accept PR's ;)... 

Care to submit an edit to the page fixing the issue you ID in your comment? Sharing is caring :)

**Comment by Languafe** [comment]
First time contributor. I think I forked the repo and submitted a pull request to my own fork first, or something? I believe I now have submitted a pull request to the actual sp-dev-docs repo.
