### ISSUE TITLE
workbench.aspx

### ISSUE THREAD

**Issue by WhiteKnightUK** [SharePoint/sp-dev-docs#34]
I'm currently running through the HelloWorld tutorial, and am currently at stage 6:

> Step 6: Preview web part in SharePoint
> 
> SharePoint Workbench is also hosted in SharePoint to preview and test your local web parts in development. The key advantage is that now you are running in SharePoint context and that you will be able to interact with SharePoint data.
> 
> Navigate to the following URL: https://your-sharepoint-site/Shared%20Documents/workbench.aspx

I can't seem to access this file at all, due to this being so new is it a case that this isn't available on all data centres yet? I ran up a new Dev tenancy about 2 hours ago in order to start playing with the new framework, but may start to struggle if I can't actually preview against SharePoint data.

**Comment by mauricionr** [comment]
@WhiteKnightUK check out these issues #3  #24  #12,  may help you

**Comment by patmill** [comment]
Did you follow the step in setup where you add a column and then upload the file to a library?

**Comment by WhiteKnightUK** [comment]
@patmill and @mauricionr thanks for that, I hadn't seen that guide. Many thanks for your help.
