### ISSUE TITLE
[SPWebPartErrorCode.ScriptLoadError]

### ISSUE THREAD

**Issue by SimonRennocks** [SharePoint/sp-dev-docs#340]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Expected the Basic Hello Webpart to load in my SharePoint Workbench.

#### Observed Behavior
Instead this error appeared:

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloWorldWebPart.4ab01e68-7e68-4746-98cc-62f3d92f1597,Error: Error loading https://placeholder-base-url/56e6aaca-6f2f-43da-822c-6da262194d50 script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-client-base_en-us_f35aa94ac66731c2577eee095f5caab4.js:48:11145) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_en-us_7d0afa6ccf73b6579e56d7cc6f3990b8.js:47:21019) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_en-us_7d0afa6ccf73b6579e56d7cc6f3990b8.js:47:21432) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-21.008/sp-webpart-base_en-us_7d0afa6ccf73b6579e56d7cc6f3990b8.js:47:30960

#### Steps to Reproduce

- Create a new Webpart
- install the dev cert
- gulp serve
- go to developer site and the workbench and add the web part to the page.

I cannot continue testing until this is resolved :(

**Comment by patmill** [comment]
Hi @SimonRennocks - quick question.  What version of the framework / tools are you using?  Your server is on Drop6.  Did you grab the RC0 build from npmjs?  If you look at your package.json, what version of "@microsoft/sp-client-base" do you see?  If it is 0.7.0, then that is RC0 and you will need to wait for your server to match.  You'll know that when the files from spoprod-a-akamaihd.net are pointing to 2017-01-... directory.

**Comment by SimonRennocks** [comment]
RC0. do you know when the server will be on RC0? Is there a way to go back to Drop 6?

**Comment by patmill** [comment]
OK, that's good.  To go back to a previous version, you can do one of two things.
1 - Your previous projects will continue to build against the drop6 bits.  You can continue using them.
2 - you can uninstall the latest @microsoft/generator-sharepoint and install the previous one.  That will create a package.json file (and starting code) that pulls in the older drop6 code which will work on your server until the RC0 bits hit it.

**Comment by SimonRennocks** [comment]
how do you uninstall and install drop 6?

**Comment by tm-3** [comment]
I just went through this earlier today. I ended up having to create a new project with the previous version of the yeoman generator. Here's what I did:

1. Uninstall the latest yeoman generator and install version 0.3.2

```
npm uninstall @microsoft/generator-sharepoint -g
npm install @microsoft/generator-sharepoint@0.3.2
```
2. Run the generator to create a new project.

```
yo @microsoft/sharepoint
```
3. Migrate your code to the new project.

If you're not using react you'll probably not have any issues just rebuilding the project. The first time around I had some a few issues with my particular project and previous code. I didn't narrow it down to root cause, but I think there have been some type definition changes since the 0.3.2 version of the generator that caused some conflicts. 

I copied my old components into the new project and made the necessary changes to the clean project. When I went to build I got a ton of typescript errors, mostly around react. I ended up removing react from the 'typings' folder and that got rid of most of them. Also, the office-ui-fabric-react package was giving me some issues as well. I wasn't using it so I just removed it.

Keep in mind this is essentially a new project so you'll need to reinstall any of the NPM packages your old project was using. 

hth

**Comment by SimonRennocks** [comment]
Thank you hth!

**Comment by nagpuregajanan** [comment]
Thanks. Which server @patmill talking about? Is there any way to point server to RC0 manually?

**Comment by dcu-sharepoint** [comment]
@SimonRennocks Just to clarify your server use. what server are you using and what version of SharePoint are you using.
the reason I ask is because I don't see a known https://tenant.sharepoint.com type address in your error message. what am missing?

my apologies if this is a dumb question.

**Comment by SimonRennocks** [comment]
SharePoint online my own dev tenant.

Sent from my Windows Phone
________________________________

**Comment by dcu-sharepoint** [comment]
Thank Simon for your quick response.

I have my own sharepoint 2016 farm along with a couple of sharepoint 2013 farms. What you are saying is that I can create my own tenant in one of these farms.

Boy I’d love to get my hands on instructions on how to do that. Can you point me to some links or give pointers on how to create my own tenant?

Again, thanks a bunch.

**Comment by SimonRennocks** [comment]
No. The SharePoint framework can only be used with SharePoint online through will.very likely to made available to SharePoint 2016 via some future feature pack (2??). I was testing locally using the buildin framework provided which I think would not include SharePoint specific features. Most testing would have to be in SharePoint online.

Sent from my Windows Phone
________________________________

**Comment by dcu-sharepoint** [comment]
Thanks for clarifying what I understood to be the case.

Your answer does put things in perspective for me. Now I’m going to start doing react/angular labs….
