### ISSUE TITLE
Silverlight CSOM?

### ISSUE THREAD

**Issue by alirobe** [SharePoint/sp-dev-docs#3401]
Silverlight is obsolete...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
While true, it's still available & can be installed. When it was still a popular option, SharePoint included it as one of it's client API surfaces... since you can still install it and since the supported end date for Silverlight 5 is 2021, the SharePoint API is still available.
