### ISSUE TITLE
How to waitForReply for flow to reply?

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-docs#3402]
Documentation says "If true, the script will expect that the Flow will call Microsoft.SharePoint.Utilities.SiteScriptUtility.SetSiteScriptStageOutcome() when it has finished executing. Note that this will not cause the script to block. The script will keep executing, but for record-keeping purposes, the run will be considered incomplete until the reply is made.". 

How to call this from flow? Need some pointers please:)

BR, Ole
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#trigger-a-flow)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
I'm not sure this implemented yet, but I'd be interested in hearing from the MSFT Team.

How this will work (given my review of the api call), is you'll get a stageId that references the stage in the site script being processed. You'll be able to execute a POST request to SetSiteScriptStageOutcome with the stageId as a parameter to update the status.

**Comment by trillian74** [comment]
@bcameron1231 thnx for the reply. I guess it's not implemented since theres close to zero hits on search. Is the API call that you reference an internal thing or is it available online?

**Comment by bcameron1231** [comment]
There isn't any documentation on the API endpoint, but the API endpoint is live.
