### ISSUE TITLE
Build your first SharePoint Framework Extension (Tutorial) not working

### ISSUE THREAD

**Issue by Rxie12** [SharePoint/sp-dev-docs#3403]
I followed the instructions to create the first SharePoint Framework Extension  "Hello World"  sample but had no luck for days. Even the Allow Debug Script - popup doesn't show up.
In VS codes, there are two problems:
  - on package.json ,  
     Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': self signed certificate in certificate chain
  - on serve.json under config, 
    Property serveConfigurations is not allowed.

Tenant URL:  https://mkdevsp.sharepoint.com/
Visual Studio Code version:  1.30.2 
Node.js: 8.9.3

Please help! Thanks!

**Comment by andrewconnell** [comment]
Those are schema errors but they are only used for IntelliSense... no real errors. 

What version of the SPFx generator do you have installed?

Can you be more specific about errors you're hitting when running `gulp serve`? Hard to repro with provided detail...

**Comment by Rxie12** [comment]
No errors when running gulp serve.  Finally I found out the root cause of my issue was the page I used which was in the root site. When I changed the page url (on serve.json) to another page in site collection level, the issue was gone. Why?

**Comment by andrewconnell** [comment]
Sorry... don't know why the root site would be special. Nothing that I'm aware of. 

Were you pointing to a specific URL or to the real root URL that redirected somewhere else when you were having the issue?

**Comment by Rxie12** [comment]
Here is the page url which caused the issue:
https://mkdevsp.sharepoint.com/SitePages/new%20extension%20page.aspx
When I used this one - "https://mkdevsp.sharepoint.com/teams/ist-usa-l-xietest1/SitePages/Home.aspx", it worked fine.

**Comment by andrewconnell** [comment]
Hmm... just grasping at straws, but what about a page in the root site _without_ spaces in the name?

**Comment by Rxie12** [comment]
I tried another new web part page: https://mkdevsp.sharepoint.com/SitePages/extensionPage.aspx but got the same issue.

**Comment by bcameron1231** [comment]
So I tried to repro this and I wasn't able to. Maybe I'm thinking to simply... but are you using a Modern Page in your root site?

**Comment by andrewconnell** [comment]
I too am having trouble repro'ing this on a brand new tenant...

**Comment by Rxie12** [comment]
Thanks for your testings.  I did more testings on different page types on my site collection level. It only works on the default home.aspx page  but no luck at any new pages (wiki and web part page).

https://mkdevsp.sharepoint.com/teams/ist-usa-l-xietest1/SitePages/home.aspx   -- default home page
https://mkdevsp.sharepoint.com/teams/ist-usa-l-xietest1/SitePages/extensionPage.aspx  - web part page
https://mkdevsp.sharepoint.com/teams/ist-usa-l-xietest1/SitePages/newWikipage.aspx    - wiki page

**Comment by bcameron1231** [comment]
Thank you for that information. SPFx Extensions are not supported on classic pages (web part pages, wiki pages, etc...). The only page that supports extensions are the modern UX pages (classic pages do not have the placeholders). 

If you are unsure if you are working in a classic or modern page, there is a [link](https://support.office.com/en-us/article/sharepoint-classic-and-modern-experiences-5725c103-505d-4a6e-9350-300d3ec7d73f) that discusses the UI differences between the two.

**Comment by Rxie12** [comment]
I just created a new site page and it works well.  It seems the extension sample only works in site page type.

**Comment by bcameron1231** [comment]
This is intended behavior. Please let us know if you need any more information from us on this ticket.
