### ISSUE TITLE
SPFx Document Search Result with ECB / CommandSet option

### ISSUE THREAD

**Issue by hsmehta21** [SharePoint/sp-dev-docs#3404]
Hi there, we are building SPFx based document listview based on search / user personalized view - my bookmarks or recent document;

We want to plug in OOTB ECB menu / command set; is there any option to integrate the same. Currently we are building our custom menu and all supported screens and updates.

Please guide us, thanks. Attached is capture 1 - OOTB menu; capture - 2 our SPFx Add-In;

Thanks in advance;
@VesaJuvonen 

![capture1](https://user-images.githubusercontent.com/37153876/52360481-2a589a00-2a0a-11e9-8edc-2c91d726c544.PNG)
![capture2](https://user-images.githubusercontent.com/37153876/52360527-49572c00-2a0a-11e9-88a7-65791a4a276d.PNG)

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Unfortunately, this is not currently supported and we do not have plans to enable that in short timeframe.
