### ISSUE TITLE
No "Edit" access to site property bag on Modern Team Sites

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3405]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

There is a possibility to edit/add site property bag items for Modern Team Site

#### Observed Behavior

```javascript
[{
  "SchemaVersion":"15.0.0.0",
  "LibraryVersion":"16.0.8530.1208",
  "ErrorInfo":{
    "ErrorMessage":"Access denied. You do not have permission to perform this action or access this resource.",
    "ErrorValue":null,
    "TraceCorrelationId":"d762bd9e-3037-8000-d096-15d7fcb240c6",
    "ErrorCode":-2147024891,
    "ErrorTypeName":"System.UnauthorizedAccessException"
  },
  "TraceCorrelationId":"d762bd9e-3037-8000-d096-15d7fcb240c6"
}]
```
#### Steps to Reproduce

In classic experience in browser console:
```javascript
var ctx = SP.ClientContext.get_current();
var web = ctx.get_site().get_rootWeb();
var allProps = web.get_allProperties();
allProps.set_item('Test1', 'Test 1');
web.update();
ctx.executeQueryAsync();
```

Look at last `ProcessQuery` request in Network tab.

**Comment by patmill** [comment]
I believe that (for some reason), you need ACP (lack of no-script) on a site to be able to modify it's property bag.  Any chance that's all you are seeing?

**Comment by AJIXuMuK** [comment]
Hi @patmill,
 Yes, it's NoScript on Modern Team Site.
In Twitter we were discussing with @VesaJuvonen this one and potential changes...
For me site property bag is a great way to store custom provisioning and configuration properties.
And if, let's say, I do the provisioning from Teams or something, I don't want to call tenant admin to disable NoScript for me...
