### ISSUE TITLE
SPO CDN

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#3407]
Where can we learn more about the SPO CDN, such as caching times, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d2c1cca-c6ef-9eb5-fcbb-78c7481b359e
* Version Independent ID: 66783ae9-b10e-5dc7-8a79-4d252ea8a9a7
* Content: [Host extension from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn)
* Content Source: [docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
- https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo
- https://docs.microsoft.com/en-us/sharepoint/dev/general-development/office-365-cdn

Believe the time things are in cache can be seen from the HTTP response header of items returned. *etc* doesn't really narrow it down...
