### ISSUE TITLE
Deployment to Developer Site is not possible: Client Side Solutions cannot be used in this location

### ISSUE THREAD

**Issue by amitphule** [SharePoint/sp-dev-docs#3408]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Able to deploy SPFx .sppkg file on a developer site ("Apps in Testing").

#### Observed Behavior

After uploading `abc.sppkg` file on a developer site ("Apps in Testing") - the following error message occurred:
![upload package](https://user-images.githubusercontent.com/6881833/52395671-0dd56400-2ad5-11e9-84f6-904170e042e0.jpg)
![deploy package](https://user-images.githubusercontent.com/6881833/52395685-13cb4500-2ad5-11e9-93bd-cb92324907fc.jpg)

#### Steps to Reproduce

1. Create a developer site in your tenant
2. Create a new SPFx WebPart: `yo @microsoft/sharepoint`
3. Execute `gulp bundle --ship`
4. Execute `gulp package-solution --ship`
5. On your developer site, go to "Apps in Testing"
6. Click "+ new app to deploy"
7. Upload  `sharepoint\solution\abc.sppkg` from your local filesystem

**Comment by andrewconnell** [comment]
As the message indicates, client-side solutions (such as SPFx projects) are not designed to be created in the **apps in testing** library... 

Once you've installed the app in the app catalog, you install it in the site from the site contents page as shown in these steps: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page#install-the-client-side-solution-on-your-site
