### ISSUE TITLE
SharePoint Framework code not working in Internet Explorer

### ISSUE THREAD

**Issue by mschaaks** [SharePoint/sp-dev-docs#3411]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The code is running in the context of an extension. One of the first things that happens is the retrieval of a sharepoint list item value. The code runs fine in Chrome and Edge, but somehow does not run in Internet Explorer 11.

In chrome when using the debugger the following network calls are shown:

GET /sites/Z010/00001/_api/site/rootweb?$select=Url HTTP/1.1
POST /sites/Z010/_api/contextinfo HTTP/1.1
POST /sites/Z010/_api/web/lists/getByTitle('Configuratie')/getitems HTTP/1.1
GET /sites/Z010/00001/_api/site/rootweb?$select=Url HTTP/1.1
POST /sites/Z010/_api/web/lists/getByTitle('Configuratie')/getitems HTTP/1.1

and all is fine

#### Observed Behavior

However in Internet explorer the browser keeps repeating the following kind of calls without getting any further:

Request URL: https://0-westeurope1-pushp.svc.ms/socket.io/?token=w1-21ca35c1-fc20-4273-8646-83ef9e5fbdee&EIO=3&transport=polling&t=MZ7vdf5&sid=0hrVy9Da0JEyTf9aBUPp

#### Steps to Reproduce

run extension in chrome/edge/ie. Is a custom component for a customer, maybe I can create a test component performing only list access code to try and simulate this behavior.

**Comment by russgove** [comment]
Hi, does your exrenation use pnp.js-core? i'd so, did you install the ie111 shim?

**Comment by mschaaks** [comment]
Fixed using this package: https://pnp.github.io/pnpjs/documentation/polyfill/
