### ISSUE TITLE
Hub Navigation responsiveness in IE11

### ISSUE THREAD

**Issue by gurubn** [SharePoint/sp-dev-docs#3415]
#### Category
- [x ] Bug

I am not sure if it is the right place to raise SharePoint Online First party features related issue, but if this is the wrong place, please redirect me to right Github repo to raise this.

It seems like Hub site navigation is not responsive on IE11. That is, If there is long set of navigation links in Hub, then Hub Site Navigation is not responsive in IE11. In Chrome and Edge, It seems to be responsive. Just wondering is it by design decided to not be responsive in IE11 ? or ? . Please enlighten me. Thank you in advance!.

#### Expected or Desired Behavior

> Hub Navigation needs to be responsive in IE 11

#### Observed Behavior

When we set a hub navigation with aroung 8 links, If the screensize is small, in IE 11 It overlaps the text. Looking at the issue, it seems like it is not responsive in IE 11

#### Steps to Reproduce

1. Create a Communication site, Register it as a Hub site
2. Add lots o first level Hub Navigation links
3. Open it in IE 11

Screenshot is below from IE 11 browser

![image](https://user-images.githubusercontent.com/23011566/52425292-fcec1900-2afb-11e9-8ebd-e8a311dadca7.png)

Screenshot from Google chrome (Where same links are responsive)

![image](https://user-images.githubusercontent.com/23011566/52425829-180b5880-2afd-11e9-86c1-f26882e8f861.png)

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
As this is not a developer topic we cannot, unfortunately, process it through this channel due to internal agreements. it's clearly a bug and should be reported using the tenant admin support channel.

**Comment by gurubn** [comment]
Sorry for late reply here. Thanks Vesa for the reply :). I will raise this issue through admin support channel
