### ISSUE TITLE
"Sorry, only tenant administrators can add or give access to this app" in ADFS Auth Web application

### ISSUE THREAD

**Issue by pathancuet** [SharePoint/sp-dev-docs#3416]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I would like to install SP hosted add-in to my ADFS authenticated web application/site collection. 

#### Observed Behavior

Our On-Prem farm is SP 2013. 

Uploaded the app in App Catalog. When we went to install the app in ADFS authenticated site/web getting error as : "Sorry, only tenant administrators can add or give access to this app". We even tried using Farm admin to install the app in our site but same issue.

I have tired this add-in in our SPO tenant. It works perfectly but not in On-Prem 2013 farm. 

#### Steps to Reproduce

I have created SP Hosted Add-in with Scope as Search and adding the permission as "**QueryAsUserIgnoreAppPrincipal**" in app manifest file. Because we would like to use SP Search API in our SP Hosted Add-in. Here is my permissions in app manifest file.

```
<AppPermissionRequests>
  <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal" />
</AppPermissionRequests>
```

Thanks for looking into this issue. Any help will be greatly appreciated.

**Comment by VesaJuvonen** [comment]
Unfortunately, this capability is only available in SharePoint Online, so the situation you are seeing is by design. This should be obviously documented properly in our documentation.

**Comment by racouster** [comment]
> 
> 
> Unfortunately, this capability is only available in SharePoint Online, so the situation you are seeing is by design. This should be obviously documented properly in our documentation.

Is documentation on this limitation available somewhere?
Should I read your comment to mean
"SP 2013 On premise - Install SP hosted add-in to a Claims authenticated web application/site collection is not possible."?
