### ISSUE TITLE
Dialog.alert(msg) is not working correctly on latest SPO template web part

### ISSUE THREAD

**Issue by westleyMS** [SharePoint/sp-dev-docs#3418]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
This method from sp-dialog-
Dialog.alert(message);

should display the alert box with a message until 'ok' is clicked.

#### Observed Behavior
The page dims in order to show the dialog, 
but it doesn't show until I click the page somewhere.
Then it flashes on the screen and dismisses very quickly.

#### Steps to Reproduce
1. used yeoman generator to create new SPFx webpart for SPO (updated templates first).
2. added dialog library (npm install @microsoft/sp-dialog)
3. added code to call Dialog.alert(message);
4. used gulp to build/bundle/package-solution with the --ship param
5. dragged the sppkg file to my tenant catalog
6. trusted app and tenant deployed it
7. added web part to page to test
8. triggered the dialog and saw behavior above

**Comment by andrewconnell** [comment]
Hmmm... related #1645?

**Comment by westleyMS** [comment]
It sounds quite similar, the only difference is that #1645 seems to not show the dialog at all, and mine does, but in a broken way.

**Comment by andrewconnell** [comment]
Which:
1. browser
1. environment
1. spfx version

?

**Comment by westleyMS** [comment]
Sorry for the delay-
browser - edge, chrome, IE11, and firefox
environment - Windows 10
spfx version - 1.7

**Comment by andrewconnell** [comment]
I've verified this is working in Chrome & Firefox (latest versions) with SPFx v1.7.1... so I'm not able to repro using the latest version. 

Can you try to with the latest version of SPFx? If it still happens, is there anything in the console that shows as errors/warnings with this happens?

**Comment by westleyMS** [comment]
It is actually 1.7.1, I just left off the last bit. 

which version of React is your part using?

**Comment by andrewconnell** [comment]
SPFx v1.7.1 adds React v16.3.2 to your **package.json**... specifically:

```json
 "dependencies": {
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@microsoft/sp-core-library": "1.7.1",
    "@microsoft/sp-webpart-base": "1.7.1",
    "@microsoft/sp-lodash-subset": "1.7.1",
    "@microsoft/sp-office-ui-fabric-core": "1.7.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-tslint-rules": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.7.1",
    "@microsoft/sp-webpart-workbench": "1.7.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
```

**Comment by VesaJuvonen** [comment]
Hi @westleyMS, is this still and issue? If so, can you share what you have in the package.json to check the React versions etc. Thx.

**Comment by westleyMS** [comment]
I do still see this, here is my package.json-
"dependencies": {
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@microsoft/sp-core-library": "1.7.1",
    "@microsoft/sp-lodash-subset": "1.7.1",
    "@microsoft/sp-office-ui-fabric-core": "1.7.1",
    "@microsoft/sp-webpart-base": "1.7.1",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.29",
    "@types/webpack-env": "1.13.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.7.1",
    "@microsoft/sp-tslint-rules": "1.7.1",
    "@microsoft/sp-webpart-workbench": "1.7.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "gulp-sequence": "^1.0.0"
  }

**Comment by VesaJuvonen** [comment]
Ok - that looks exactly as AC's package.json. Right now there's no repro, which makes the investigation impossible basically. Can you share the actual package, even though it seems like a clean solution with minimal edits as we cannot reproduce the issue? 

Also - are you using normal SPO tenant for testing this?

**Comment by westleyMS** [comment]
Yes it is a first release tenant, but I just turned that off. It should revert back today sometime. I'll send you the files.

**Comment by VesaJuvonen** [comment]
Where are we wit this one?

**Comment by westleyMS** [comment]
Still the same, no change.

**Comment by patmill** [comment]
Sorry - it's like a voice from the past...  Looking into this.

**Comment by westleyMS** [comment]
I tried it again, and now it is working. Not sure what changed, but I am good to close this.

**Comment by PhilThome** [comment]
Is ist possible that this is only caused when using Internet Explorer (11) with a Targeted Release?

**Comment by andrewconnell** [comment]
@PhilThome OP said issue fixed so not in this case... if you're experiencing a problem, please submit a new issue with the relevant details.
