### ISSUE TITLE
webpart not loading on SP online workbench

### ISSUE THREAD

**Issue by nagpuregajanan** [SharePoint/sp-dev-docs#342]
#### Category
- [ ] Bug

#### Expected or Desired Behavior
Webpart should load on SharePoint online.
#### Observed Behavior
Getting error that Hello-world.bundle 404 (Not Found)
#### Steps to Reproduce
Just follow the steps to create a simple webpart and type gulp serve and add the webpart on SharePoint online.
![spfxerror](https://cloud.githubusercontent.com/assets/5637183/21892841/b064d8ca-d8fe-11e6-89c6-312086415d3c.png)

**Comment by tm-3** [comment]
Check out the issue below and see if that helps.

#340

**Comment by manishgarg1** [comment]
Hi @nagpuregajanan, is this still happening ? I believe this was happening because we had a delay in pushing our code to production environment.

**Comment by nagpuregajanan** [comment]
Hi, @manishgarg, I just checked and it's working now. Thanks.
