### ISSUE TITLE
SPRegionalSettings.Collation Possible values?

### ISSUE THREAD

**Issue by davehax** [SharePoint/sp-dev-docs#3420]
Hi Team,

What are the possible values for this collection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec3d95c-99e4-da14-5759-5cd6ac8af468
* Version Independent ID: 3741b31f-e718-86d9-2475-1082942c696b
* Content: [SPRegionalSettings.Collation Property (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spregionalsettings.collation?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_SPRegionalSettings_Collation)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by wnzn** [comment]
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ms367805(v=office.15)
