### ISSUE TITLE
manifest.json for Teams gets overwritten when a second SPFx webpart is added to the solution

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#3426]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

If there are 2 (or more) SPFx webparts in the solution, it should be possible to make all of them available as Teams tabs.

#### Observed Behavior

When a second webpart is added to the SPFx solution, the `teams/manifest.json` file gets overwritten by the details of the new webpart.

If multiple webparts are to be made available as Teams tabs, then we have to manually create a new manifest.json file, zip it, and upload it separately to the Teams app catalog. This workaround is not scalable as each webpart/tab would need a separate package to be uploaded.

#### Steps to Reproduce

1) Create a new SPFx solution with `yo @microsoft/sharepoint --plusbeta`
2) When prompted for component type, select webpart.
3) When the scaffolding is generated, navigate to `teams/manifest.json` and observe that the details of the webpart including the component id are present.
4) Now add a second webpart to the solution with `yo @microsoft/sharepoint --plusbeta`
5) Navigate to the `teams/manifest.json` file and observe that all the details of the second webpart are present and the previous manifest.json has been overwritten.

**Comment by VesaJuvonen** [comment]
This will be fixed in 1.8 as we will auto-generate manifest files for the deployment. More details when the 1.8 is out with docs.
