### ISSUE TITLE
ListViewCommandSet not working in debug mode on TR tenants

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#3429]
#### Category
- [x] Bug

#### Expected or Desired Behavior

When creating a default `ListViewCommandSet` project using SPFx and running gulp serve opening up a standard list, I expect the buttons to show.

When debugging the manifest file is loaded, as well as the extension js, but `OnInit` is never triggered.

#### Steps to Reproduce

Create an oob `ListViewCommandSet` extension and run gulp serve targeting a list.

**Comment by Myrlin1** [comment]
Ever figure anything out about this issue?  I am having the same problem.  Tried with 1.7.1 and 1.8

**Comment by mcmynn83** [comment]
@wobba  - Sorry for taking a while, however, I just tried reproducing this today to look into fixing it and it seems like it is working.  Are you still seeing an issue?

**Comment by wobba** [comment]
I'll retest tomorrow while at work. Thanks for looking into it.

**Comment by wobba** [comment]
@mcmynn83 Did a re-testnow, and on two TR tenants nothing happens. On a GA tenant it works just fine. Using SPFx v1.8.0 in this case.

**Comment by mcmynn83** [comment]
Sorry about that... I managed to miss the TR tenant's part.  I am not looking into it.  Thanks!

**Comment by mcmynn83** [comment]
@wobba - thanks for finding this, we are tracking the fix in #3914 so I'm closing this issue.
