### ISSUE TITLE
Failed to validate the notification URL

### ISSUE THREAD

**Issue by vdohare** [SharePoint/sp-dev-docs#3430]
I am trying to create subscription on non standard port, using following payload
{
  "resource": "https://contoso.sharepoint.com/_api/web/lists('5C77031A-9621-4DFC-BB5D-57803A94E91D')",
  "notificationUrl": "https://my.domain.com:1150/api/v1/webhook/handlerequest",
  "expirationDateTime": "2019-04-30T00:00:00+00:00"
}

but i am getting following response
{
    "error": {
        "code": "-1, System.InvalidOperationException",
        "message": {
            "lang": "en-US",
            "value": "Failed to validate the notification URL 'https://my.domain.com:1150/api/v1/webhook/handlerequest'."
        }
    }
}

but on other side when i try to create the subscription without the port "1150", it gets create successfully.

Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc58af9c-d9b8-5ed0-6117-2db7a1d425de
* Version Independent ID: 7cc8696c-5946-0414-b5be-c7561d0e31b5
* Content: [Create a new subscription](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/create-subscription)
* Content Source: [docs/apis/webhooks/lists/create-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/lists/create-subscription.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Checking for an official doc on supported ports, but in my exp & from your test, you can't use something other than 443 (HTTPS). Will post a follow up to official docs / statement if I find something...

**Comment by vdohare** [comment]
Is there any plans in near future, for support of non-standard port?

**Comment by andrewconnell** [comment]
Microsoft hasn't said anything, so there are no public plans.
