### ISSUE TITLE
TemplateProvider : GetHierarchy - ProvisioningTemplate version is overwritten.

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#3436]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

When using TemplateProvider.GetHierarchy method all the templates in the Templates collection have the same version number as ProvisioningHierarchy object. In the ProvisioningTemplate class, if the ProvisioningHierarchy object is set, the template returns hierarchy version.

#### Expected or Desired Behavior

Does it really make sense? In case we are able to obtain the ProvisioningHierarchy version by using it's own Version property or access it directly from the ProvisioningTemplate by accessing ParentHierarchy.Version, the desired behaviour would be to get the Templates real version - the ones assigned in the file. 

#### Steps to Reproduce

Load ProvisioningHierarchy object with a template with provider.GetHierarchy method. Check the version of the loaded templates.

#### Submission Guidelines

File containing the code:
Framework\Provisioning\Model\ProvisioningTemplate.cs
Property:
public double Version {
            get
            {
                if (this.ParentHierarchy != null)
                {
                    **return (this.ParentHierarchy.Version);**
                }
                else
                {
                    return _version;
                }
            }
            set
            {
                if (this.ParentHierarchy != null)
                {
                    this.ParentHierarchy.Version = value;
                }
                else
                {
                    this._version = value;
                }
            }
        }

Sharing is caring.

**Comment by andrewconnell** [comment]
Can you provide some context as to how you're doing this? SharePoint CSOM, PnP, etc?

**Comment by siata13** [comment]
I would like to be able to store multiple templates in the hierarchy and apply them based on the version. E.g. if in the site I have already v1.0 applied, let's apply only v1.1:
`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
     ...
  <pnp:Templates ID="TEMPLATES">
    <pnp:ProvisioningTemplate ID="Base" Version="1">
      ...
    </pnp:ProvisioningTemplate>
    <pnp:ProvisioningTemplate ID="Hotfix1" Version="1.1">
      ...
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>`

GetHierarchy seems to be the only option to retrieve multiple templates from the file at the moment.

**Comment by andrewconnell** [comment]
Didn't really answer the question, but seems like you're referring to the PnP provisioning support in PnP CSOM. 

Their repo is the best place to ask that question as I'm not sure they are monitoring this one as closely: https://github.com/SharePoint/PnP-Sites-Core

Please post your question in their issue list.
