### ISSUE TITLE
Set column value from a Lookup field using JSON

### ISSUE THREAD

**Issue by ChadMagee** [SharePoint/sp-dev-docs#3439]
I've tried assigning a value to a text column based on the choice of a lookup field. I've tried a few solutions but the closest I can get is having  [Object Object] returned instead of the actual value.

What is the JSON code to return the text values of a Lookup column. The Lookup Column referenced is located on the same site.
#### Category
- [] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

![jsonchoiceassign](https://user-images.githubusercontent.com/47586660/52689039-6fa32d00-2f1e-11e9-87cc-1078cad2e5f7.PNG)

Thanks for your contribution! Sharing is caring.

**Comment by PopWarner** [comment]
Hi ChadMagee 

The guidance in the docs for column formatting shows using ‘.lookupValue’ nn the field. Does that work for you? :)

You had mentioned you tried a few solutions, so wasn’t sure if this was one of them. 

You can see the guidance and an example here near the bottom of the page:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting

**Comment by thechriskent** [comment]
@PopWarner you're correct. In this case, the issue was with putting the sub property outside of the brackets. @ChadMagee and I were able to work on this together after my session at SPTechCon.

For everyone stumbling here from search, the solution was to use:

```json
"txtContent": "[$Sand_x0020_Type.lookupValue]"
```

**Comment by PopWarner** [comment]
Awesome!! :)
