### ISSUE TITLE
Unable to deploy SPFx web part at tenant scope

### ISSUE THREAD

**Issue by zplume** [SharePoint/sp-dev-docs#344]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx web part can be deployed at tenant scope by an administrator

#### Observed Behavior
SPFx web part cannot be deployed at tenant scope by an administrator

#### Steps to Reproduce
- Create an SPFx web part using RC0 drop / yo generator
- "gulp --ship"
- "gulp bundle --ship"
- "gulp package-solution --ship"
- Upload "sharepoint\solution\appname.sppkg" to SPO app catalog
- Install the app to the app catalog via site contents
- Switch site contents to classic view
- Click the ellipsis icon next to the app name
- Click DEPLOYMENT
- Select a managed path (e.g. "/sites/")
- Click OK
- A modal dialog is displayed with the header "Error" and the contents "An unexpected error has occurred". A Correlation ID is displayed when clicking "TECHNICAL DETAILS", but no further information is available.

Thanks

**Comment by patmill** [comment]
Hi @zplume - Are you on a dev tenant or a tenant where first release is enabled (not for specific users, but for everyone).  If you are, can you do two things?
1 - what is the correlation ID of the error?
2 - If you go to the app catalog list, there should be an extra field (you might need to add it to the view) that should give a more informative error.  Can you add it here?

**Comment by zplume** [comment]
The tenant was created by someone else but I believe it's first release (is there some way I can check?) - I was able to add an SPFx drop 6 web part to a classic page in this tenant prior to RC0.
Correlation id: 10a0ca9d-a07d-3000-a2e9-203e68f329c5
There is an "App Package Error Message" field which I've added to the AppCatalog list view, but the value for my app is "No errors."
I am able to install the app on the app catalog site successfully, but deploying it to the whole tenant is failing.

Thanks

**Comment by zplume** [comment]
I've confirmed that the tenant release track is set to "First release for everyone" and release track users "All"

**Comment by patmill** [comment]
Hi @zplume - one thing struck me in your post.  "deploying it to the whole tenant is failing."

Do you mean that deploying it to any site fails, or that you are trying to deploy a webpart to the entire tenant?

Also - unfortunately to look up the correlation ID on our side, I need a tenant URL.  Would you mind pasting your tenant name (foobar123.sharepoint.com)?  If that doesn't work for you, we can try a different approach.

**Comment by zplume** [comment]
We would like the app to be installed and trusted in all site collections within a certain managed path, via a one time manual step per tenant (rather than manually adding the app to each of those site collections individually).

We estimate 10,000 new site collections per year within this managed path (hence the desire to avoid manually installing the app on each site).

With provider hosted apps this can be achieved as follows:
- Upload the app to the app catalog
- Install the app in the app catalog site collection
- From the app catalog site contents page, click on the app, then click "deployment" (not sure if this is supported in the new experience, but it is in the classic experience)
- Specify which managed path to install to and click OK

Is this scenario supported for SPFx web parts?

The site collections in this managed path are created and configured by our provisioning engine (a combination of Azure-hosted web service, web jobs and .NET CSOM), which creates a standard team site and then makes various configuration changes.
My client wants the SPFx web part I am developing automatically added to the home page of each new site as part of the automated provisioning process (via .NET CSOM).
I'm hoping that this is possible for a classic page by using the existing CSOM web part management APIs. I did some testing with SPFx drop 6 and was able to export the XML for an SPFx web part after adding it to a classic page via the UI, but the web part didn't work if the app is not also deployed and trusted for the site collection. I haven't had a chance to test adding the web part to a classic page via CSOM yet.

I can't share the URL publicly because it contains my client's name (it's their development tenant though, not production!), but perhaps I can send you the URL via a private message?

Thanks!

**Comment by patmill** [comment]
OK, dug a bit more into this.  @zplume - I think we have a plan for what you are trying to do, but it is not yet implemented.  This is our plan, and you can tell me if it meets your requirements.

There is a class of webpart that doesn't require assets / resources to be put on a site during activation.  Really, any site is capable of using the webpart.  Our goal is that you can mark up a webpart component and say "This webpart is available everywhere, and it doesn't need to be activated / installed on every site collection".

**Comment by zplume** [comment]
@patmill that sounds perfect, thanks for the update :)

**Comment by theepan18** [comment]
@patmill I am still waiting for this feature. Have you any idea of when it will be implemented? :-/

**Comment by zplume** [comment]
Hi @patmill, any idea when this will be available?

My client has a requirement for configuring collaboration site collection (and subsite) home pages during provisioning (which is automated via Azure WebAPI, web job and .NET CSOM) to include a SPFx web part we have developed and this is currently stopping us from doing that (we have thousands of collaboration site collections, and the number is growing rapidly).

Thanks!

**Comment by amishra0909** [comment]
Hi @zplume, thanks for the feedback. We are working on this issue.
