### ISSUE TITLE
Application extension in SharePoint 2019

### ISSUE THREAD

**Issue by lennertcc** [SharePoint/sp-dev-docs#3443]
As of @microsoft/sharepoint 1.7 there is an option to choose "SharePoint 2019 onward", then "Extension", then "Application Customizer". Following the rest of this walkthrough, setting pageUrl to https://sp2019/SitePages/Start.aspx, I don't see the popup.

Should this work or is my scenario not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by lennertcc** [comment]
While debugging I found that replacing Dialog.alert with regular Javascript alert solved my problem and a pop-up is shown.

This should be updated in the documentation or in the scaffolding I think.

**Comment by andrewconnell** [comment]
Any errors in the browser's JS console? There was an issue in the Dialog framework for a while... not sure when that got fixed & if that fix is in the SP2019 onprem release...

**Comment by lennertcc** [comment]
I attached the debugger and found that there is no error on execution of the Dialog.alert line. There is some error after the page is loaded, but I feel it is unrelated.

sp-pages-assembly.js?uniqueId=2g4QD:119 Uncaught Error: No callbackHandler found.
    at Function.e._sendMessage (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at Function.e.sendPageLoaded (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at t._onPostMessageLoading (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at t._onPostMessage (sp-pages-assembly.js?uniqueId=2g4QD:119)

**Comment by andrewconnell** [comment]
Hmmm... related #1645?

**Comment by lennertcc** [comment]
Yes, that's it.

> Hmmm... related #1645?

**Comment by andrewconnell** [comment]
OK... I'll close this one as a dupe to keep things consolidated..

**Comment by lennertcc** [comment]
Maybe good to leave this open to help others that follow the same walk-through and run into the same problem. It may help others to see an open issue that there is a known bug with this walk-through for SharePoint 2019. It may take a while before this is fixed I believe.

**Comment by andrewconnell** [comment]
The general practice is to consolidate to a single issue to better enable tracking. Since I referenced it above, it's showing up in the activity history of that issue so people will find it via the other issue.
