### ISSUE TITLE
Sub-menu only opening after hovering twice

### ISSUE THREAD

**Issue by jcosta33** [SharePoint/sp-dev-docs#3444]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

When hovering an item inside a sub-menu (cascading, not megamenu) that itself has children, the corresponding >=2nd level sub-menu only opens up after hovering its parent menu item twice.

#### Steps to Reproduce

Create a navigation with 3 or more levels and hover a sub menu item with children.

**Comment by patmill** [comment]
Sorry - just checking.  Is this a developer specific issue, or just a "hey, this isn't working correctly in the SharePoint app"?

**Comment by jcosta33** [comment]
It's the latter, just something I noticed while browsing around SharePoint.

**Comment by VesaJuvonen** [comment]
As this is not a dev issue, we cannot process it through this channel. You can report it using the tenant admin support channels if needed.
