### ISSUE TITLE
Mega menus with long strings overflowing container

### ISSUE THREAD

**Issue by jcosta33** [SharePoint/sp-dev-docs#3445]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

![image](https://user-images.githubusercontent.com/8978270/52788777-e1cc5c80-3059-11e9-9b1e-81bb56afd92d.png)

#### Expected Behavior

Limit the width of the menu items and apply overflow ellipsis
or
Break the line

#### Steps to Reproduce

Create a mega menu with items containing long strings

**Comment by VesaJuvonen** [comment]
As this is not a dev issue, we cannot process it through this channel. You can report it using the tenant admin support channels if needed.
