### ISSUE TITLE
cannot connect to runtime process timeout after 10000 ms - (reason cannot connect to the target: connect econnrefused 127.0.0.1:9222

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [SharePoint/sp-dev-docs#3446]
#### Category
- [  ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
Hi,
I am trying to debug my SPFx web part in Visual studio code. So I ran "gulp serve -nobrowser" in npm and hit F5 in VS Code.
But my debugger is not hitting the break point. It is throwing below error.
![image](https://user-images.githubusercontent.com/42473451/52797331-902dcd00-306d-11e9-9a9c-bc7ec2bf01da.png)
I am using spfx: 1.7.0 version
node: 8.12.0 version
npm: 6.5.0 version
Also I don't have any instance of chrome running in my machine
This is my code in launch.json:
```json
{
  "version": "0.2.0",
  "configurations": [{
  "name": "Local workbench",
  "type": "chrome",
  "request": "launch",
  "url": "https://localhost:4321/temp/workbench.html",
  "webRoot": "${workspaceRoot}",
  "userDataDir": "${workspaceRoot}/out/chrome",
  "sourceMaps": true,
  "sourceMapPathOverrides": {
  "webpack:///../../../src/_": "${webRoot}/src/_",
  "webpack:///../../../../src/_": "${webRoot}/src/_",
  "webpack:///../../../../../src/_": "${webRoot}/src/_"
  },
  "runtimeArgs": [
  "--remote-debugging-port=9222"
  ]
  },
  {
  "name": "Hosted workbench",
  "type": "chrome",
  "request": "launch",
  "url": "https://enter-your-SharePoint-site/_layouts/workbench.aspx",
  "webRoot": "${workspaceRoot}",
  "sourceMaps": true,
  "sourceMapPathOverrides": {
  "webpack:///../../../src/_": "${webRoot}/src/_",
  "webpack:///../../../../src/_": "${webRoot}/src/_",
  "webpack:///../../../../../src/_": "${webRoot}/src/*"
  },
  "runtimeArgs": [
  "--remote-debugging-port=9222",
  "-incognito"
  ]
  }
  ]
  }
```
  Please help
#### Expected or Desired Behavior

Debugger to stop at break point

#### Observed Behavior

Getting timed out error

**Comment by andrewconnell** [comment]
Those trailing `_` don't look right at all... is this verbatim your **launch.json**?

Also, does Chrome open?

**Comment by AnjaniChallamcherla** [comment]
@andrewconnell 
_ s are not in my launch.json, not sure how they got added over here.
Also chrome is not opening, when I get F5, I am getting the error mentioned above.
Below is my launch.json:
![image](https://user-images.githubusercontent.com/42473451/52799469-ccfbc300-3071-11e9-9c8e-d014b3f8b80a.png)

**Comment by andrewconnell** [comment]
OK... possibly stupid questions, but....

- Chrome installed?
- VSCode extension for debugging with Chrome installed in VSCode?
- After running `gulp serve --nobrowser`, can you manually open a browser and hit the working local workbench?
- Try not using F5... not sure which configuration that's set to. Manually select the launch config & select the PLAY icon to start it.

**Comment by AnjaniChallamcherla** [comment]
@andrewconnell Thank you so much for your quick responses.
Yes Chrome is installed, Version 72.0.3626.109 
Chrome Extension (Debugger for Chrome) in VS Code is installed, version 4.11.2
After I run the gulp serve --nobrowser and ran local workbench but nothing is displayed as in below screen
![image](https://user-images.githubusercontent.com/42473451/52802533-0d5e3f80-3078-11e9-9247-f8ac4e646912.png)

May I know what do you mean by launch config please?
Do you mean, In VS code -> Debug -> Start Debugging
![image](https://user-images.githubusercontent.com/42473451/52802741-734ac700-3078-11e9-8e9a-98f45e3821ab.png)

If so, I did the same. But still getting the same error.

Is their anything we should check with respect to ports in our machine?

**Comment by andrewconnell** [comment]
Step 1 - figure out why the workbench isn't loading before debugging with VSCode. 

Assume you're doing this with `--nobrowser`. Try doing it without that flag... verify the workbench is loading. Then quit all instances of Chrome. Now, try debugging with VSCode.

**Comment by AnjaniChallamcherla** [comment]
workbench is working fine if I run gulp serve.
workbench is blank when i run gulp serve --nobrowser

**Comment by andrewconnell** [comment]
OK... then that's a different issue... it's come up from time to time that the `--nobrowser` doesn't copy the necessary workbench hosting files to the `./temp` folder. 

The workaround is simple: just run `gulp serve` and kill all instances of Chrome before debugging.

**Comment by AnjaniChallamcherla** [comment]
I closed all instances of chrome.
![image](https://user-images.githubusercontent.com/42473451/52804574-71830280-307c-11e9-9f4c-7d9b656523f7.png)
But still getting the same error.
Don't know the reason...

**Comment by andrewconnell** [comment]
So you ran `gulp serve`, made sure the workbench was open, then killed all instances of Chrome and tried run the launch configuration without F5 to ensure it's trying to hit local workbench?

Is this a corporate managed laptop where you have something that's blocking ports? For instance, can you try disabling your firewall and then attaching to the debugger? I wonder if your firewall is blocking VSCode from attaching to the debugging port...

**Comment by AnjaniChallamcherla** [comment]
Yes, it is a corporate managed machine. I have disabled the firewall but still getting the same error

**Comment by andrewconnell** [comment]
I'm out of ideas... I think it's safe to say this isn't a SharePoint related issue (as it usually is... hence why I recommended you move your issue from the VSCode repo => here). I'd post this to the VSCode repo as an issue, but I'd rec you not focus on the SharePoint aspects of it in that issue as they may think to point you here... rather it seems like it's an issue with VSCode's debugger not attaching to an existing process... in this case a Node.js process.

Sorry, I can't help much more than this, but you've exhausted my ideas. I see others reporting the same issue in the VSCode repo who've resolved their issue... Please do post a link to the issue you create there in this thread so we can monitor it... 

![](https://media.giphy.com/media/jPAdK8Nfzzwt2/giphy.gif)

**Comment by AnjaniChallamcherla** [comment]
Yes, even I am thinking it is something related to VSCode. 
I Uninstalled my VSCode, Google chrome, npm and node, but still its the same issue. So I am planning to format my machine and try.
I raised an issue in VSCode repo, https://github.com/Microsoft/vscode-chrome-debug/issues/784 
Any ways thank you @andrewconnell for your help.

**Comment by andrewconnell** [comment]
Before formatting your machine & trying, spin up a VM (like in Azure so it's quick and cheap) and set up the experience... then test. Make sure it's _YOUR MACHINE_ that's the issue and you have the process correct.

IOW, process of elimination. 

I'm going to close this issue, but please do follow up when you get the debugger working...
