### ISSUE TITLE
After adding webpart to project with an extension serve.json does not have a configuration for newly created webpart

### ISSUE THREAD

**Issue by mike-morr** [SharePoint/sp-dev-docs#3447]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
New webpart added to a project gets a serve.json configuration of it's own

#### Observed Behavior
Not sure if this is a bug of if I'm just not holding it right.  I had an existing project with an extension in it.  I used the generator to add a webpart to the project.  When I run ```gulp serve``` the extension runs.  The webpart was added to the end of the serve.json with no name.  My question is how do I run ```gulp serve``` to run the webpart instead of the extension?

#### Steps to Reproduce
1.  Run ```yo``` and select the out of the box spfx generator.
2. Create an extension
3. Run the generator again and choose a webpart.

Notice the new webpart does not get a "serveConfiguration"

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://tenant.sharepoint.com/sites/NetworkSiteDocs",
      "customActions": {
        "db543787-acd5-4c3c-9952-5cbd80f907d0": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "testMessage": "Test message"
          }
        }
      }
    },
    "complianceCheck": {
      "pageUrl": "https://tenant.sharepoint.com/sites/NetworkSiteDocs",
      "customActions": {
        "db543787-acd5-4c3c-9952-5cbd80f907d0": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "testMessage": "Test message"
          }
        }
      }
    }
  },
  **"initialPage": "https://tenant.sharepoint.com/sites/SharePoint/_layouts/15/workbench.aspx",
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }**
}

```  

Again, how do I get ```gulp serve``` to serve the webpart instead of the extension?

**Comment by andrewconnell** [comment]
Web parts don't need serve configurations since they can run on the local workbench. The point of the serve configurations is to create the URL parameters needed to test an extension.

Create a new project with a web part... notice there are no configurations in it. Web parts are intended to be added to the page using the provided UX tools.

**Comment by mike-morr** [comment]
@andrewconnell So how do I serve the webpart instead of the extension?  gulp serve --config=?

**Comment by andrewconnell** [comment]
You don't specify anything... just `gulp serve`. That will launch the workbench and you can then use the tools in the UX to add it.

See steps here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part

**Comment by andrewconnell** [comment]
Further... you may be misunderstanding what _serve_ configurations do. The gulp task **serve** spins up a local web server and hosts (serves up) the necessary files (including the files that contain the web part / extension). This includes opening a browser & opening the workbench (a place to test stuff).

A _serve configuration_ simply configures the gulp **serve** task. Specifically, it just creates specially crafted URL parameters for you when opening the browser after starting the web server. These URL parameters are needed to dynamically load an extension on the page to test it.

Web parts need no special URL parameters for testing... hence why you don't need a configuration for them.

**Comment by mike-morr** [comment]
@andrewconnell I think you might be missing the point of my question.  

I totally understand what you are saying about serve configurations.

My question is, when I specify ```"initialPage": "https://tenant.sharepoint.com/sites/SharePoint/_layouts/15/workbench.aspx",``` how do I make gulp serve take me there?  Currently it just loads the URL for the extension and then I have to navigate to the workbench manually?  What is the purpose of initialPage if I can't actually make gulp take me there?  The only way currently that initialPage seems to be applicable is in an application where all you have is web parts.

**Comment by andrewconnell** [comment]
I think I understanding what you're saying. When `serveConfigurations` is present, that ignores any `initialPage` setting. Remove the `serveConfigurations` if you want to use the `initiaPage` option.

Notice when you create a project with JUST a web part & another with JUST an extension, how one contains `initialPage` and one contains `serveConfigurations`, but you won't find both.

**Comment by mike-morr** [comment]
I think a better experience would be for everything to be placed under serveConfigurations with a new type field that can be "extension" or "web part" and if it is an extension, it gets the query string added, otherwise it doesn't.  This way "gulp serve --config=XXXX" can be used for both extensions and web parts.  Right now, it is not very smooth for me to switch from developing the extension vs the web part.  

@andrewconnell Should I create a new issue for the feature request?

**Comment by andrewconnell** [comment]
Feature requests should be posted to uservoice... not as an issue here: https://aka.ms/sp-dev-uservoice
