### ISSUE TITLE
SPComponentLoader.loadCss truncate url when passed in without protocol

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3451]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Load CSS without specific protocol should not truncate the url.

#### Observed Behavior
There is a potential bug in the SPComponentLoader.loadCss method. When a URL will be passed in without any protocol (http / https) the URL gets truncated.

```js
SPComponentLoader.loadCss('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
```

Result in the following link reference:

![screenshot 2019-02-15 at 13 29 56](https://user-images.githubusercontent.com/5503835/52856919-efe7af00-3125-11e9-8091-ae10336416e6.png)

When the URL pass to the SPComponentLoader contains the protocol:
```
SPComponentLoader.loadCss('https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
```
The result always looks like this:

![screenshot 2019-02-15 at 13 34 38](https://user-images.githubusercontent.com/5503835/52857122-7c926d00-3126-11e9-8279-79b4d6131a13.png)

#### Steps to Reproduce
Create a new web part and add the following lines:
At the top:
```js
import { SPComponentLoader } from '@microsoft/sp-loader';
```
In the contructor or render method:
```js
SPComponentLoader.loadCss('https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
```

**Comment by VesaJuvonen** [comment]
Right now using // is simply not supported and https:// should be used instead. If that's an issue, let's have a discussion offline to understand implications.
