### ISSUE TITLE
Hub navigation bellow extension placeholder

### ISSUE THREAD

**Issue by carlosmiguelsns** [SharePoint/sp-dev-docs#3452]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The HUB navigation should always be the first element on the page, since it's a link between site collections and therefore it is expected to be the very first item in the page hierarchy. Is it possible to change this behavior or provide a setting with which one could set which would show first?

#### Observed Behavior

When you load an extension this will make the HUB navigation show after the content of the extension.

**Comment by andrewconnell** [comment]
No, there is not presently a way to change this behavior. As this is a change/feature request, it should be posted to UserVoice: https://aka.ms/sp-dev-uservoice
