### ISSUE TITLE
Creating a tenant section and using the tenant prefix

### ISSUE THREAD

**Issue by dlwalla** [SharePoint/sp-dev-docs#3456]
For the uninitiated, explain what a 'tenant' is, how to confirm status, and how to find what the tenant prefix is. Not everyone knows that 'tenant' is really just an instance of Office 365 and that you need to get it, independent of signing up for the Developer program - say that! Also make the instructions idiot proof, as far as what the tenant prefix is. I spent hours stumbling around before I figured it out. Googling wasn't helpful either. Very aggravating

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037842f6-772f-456d-6f44-0c46939bcddd
* Version Independent ID: 608ab68a-92a1-ca34-5ce6-2ae71691f6e6
* Content: [Set up your Office 365 tenant](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant)
* Content Source: [docs/spfx/set-up-your-developer-tenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Would a link to [this doc](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings) help here? That page does a good job of explaining what a tenant is in relation to user accounts, subscriptions, licenses.

This doc does make the assumption you know what that is... so if you did know, does the rest of the doc make sense? It does to me, but I understand it so to improve it, would need to get perspective of someone else. TIA!
