### ISSUE TITLE
application customizer placeholder top sort order

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#3459]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

This has been raised before here:
#885 

How do we control the orders of extension customizers e.g: I want certain customizer displayed on top and the others after that customizer. Currently I can see its randomly ordered on different clients.
Should I wait until certain domElement to be rendered/available first then render the customizer? Is it the correct pattern?

**Comment by andrewconnell** [comment]
You are supposed to be able to control the order of when the app customizers are loaded on the page using the `sequence` attribute on the `<CustomAction>` element ([doc ref](https://docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element)).

You may have to play with different values to get the results you're looking for. Not sure what default value is used when it's not specified though... 

Does that help?

**Comment by jonathanhotono** [comment]
@andrewconnell Thanks! That helps. Also another question out of topic, is it possible to update `CustomActions` on extensions that are using `skipFeatureDeployment: true` ? Like update its manifest on certain site collection scope? Currently I tried to create a new CustomAction since existing ones that are deployed are not exist, but it ends up rendering the extensions twice(with correct manifest update).

**Comment by andrewconnell** [comment]
First, I don't see how the extension would be installed if you are using `skipFeatureDeployment: true` considering all three types of extensions are installed using the feature framework... unless you're doing programmatic provisioning?

With that being said, I just don't know if that's possible. Manifests have to be installed so if you want to update it, you'd have to just deploy an update to the SharePoint package... just make sure you version the component & solution so SharePoint sees it as something new and replaces the existing install.
