### ISSUE TITLE
gulp serve fails in rc0

### ISSUE THREAD

**Issue by dcu-sharepoint** [SharePoint/sp-dev-docs#346]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ X] Bug

#### Expected or Desired Behavior

yo @microsoft/sharepoint should create the correct scaffold bits
gulp serve should be able to build and serve the new webpart page

#### Observed Behavior

Missing environment modules in the RC0 bits.

![missing-mods-in-rc0](https://cloud.githubusercontent.com/assets/22737071/21918929/59909e32-d924-11e6-9317-65e31132a56d.png)

gulp serve output

![rc0-gulp-serve-fails](https://cloud.githubusercontent.com/assets/22737071/21918935/70e41df2-d924-11e6-8d42-608df7d1b7b7.png)

I removed the node_modules several times, re-runned the npm install commands, re-runned the yo commands with the same results.

#### Steps to Reproduce

1) run npm install @microsoft/latest for the **RC0** bits
2) yo @microsoft/sharepoint
         scaffold a new Helloworld project
3) gulp serve and watch it fail

#### Submission Guidelines
Thanks for your contribution! Sharing is caring.

**Comment by chakkaradeep** [comment]
Can you import the variables from the sp-core-library module as described in the tutorials?

```
import {
  Environment,
  EnvironmentType
} from '@microsoft/sp-core-library';
```

Its also [here in the release notes](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0#sp-core-library-package).

**Comment by patmill** [comment]
Hi @dcu-sharepoint - just want to clarify a few things, as I have run this several times on several machines, and haven't hit this issue.
You say "install the RC0 generator and create a new project, watch it fail" but you picture says "code used to work in Drop6".

Is the problem that a brand new, clean, webpart doesn't work correctly, or that copying over a webpart that worked in Drop 6 doesn't work in RC0?

There have been several breaking changes in RC0 as documented in the release notes. 
Thanks

**Comment by dcu-sharepoint** [comment]
Hi @patmill - I'm starting from scratch in running the **yo** command. when I compared the new node_modules scaffolding, what I see is that the environment package is missing from the RC0 node_modules structure.

I'm following the tutorial **SharePoint Framework Tutorial 1 - HelloWorld WebPart** https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part and the code fails when I use the RC0 bits to build the HelloWord app. 

By me saying *"install the RC0 generator and create a new project, watch it fail" but you picture says "code used to work in Drop6"** I meant that I had created the scaffolding using the bits from Drop 6 the day before  and then I built another scaffolding using the bits from the RC0 bits yesterday. I did not re-use anything, I started from scratch in both cases and when I compared the contents of **node_modules**. What I found is that some modules are missing in the **RC0 node_modules** folder and that’s is what is shown on the images I posted. I used vsCode to get to the code folders and also edited the RC0 webpart.ts file where the imported code from the tutorial is failing which is also shown on the gulp serve image. The vsCode image shows the **Drop 6 nodes_module** on the left and the **RC0 node_modules on the right (screen center)** then the **actual code** next on large section on the far right

Currently I'm a newbee swimming against the current so I don't know how to recover from this. All I can tell is that there are some modules missing that are required by the code in the tutorial and the build fails because it can’t find the modules.

Since I'm a newbee, it's probably something I'm doing but I can't see what I'm doing different from drop 6 to the new RC0.

I guess I could copy the missing modules from the drop 6 area to the RC0 area but in my mind, it does not make any sense to do that.

The fact that you can’t reproduce the build failure means that either my bits are corrupted or that I’ve done some to change the build.

Anywho: any ideas of where do I go from here?

Thank you for your patience.

**Comment by dcu-sharepoint** [comment]
@chakkaradeep - **you** are the man. thank you. 🥇 

That bit of code cleared the Environment error. The code still has several more issues in trying to create mock list data but i'll create a new issue on that code problem. but your code definitely took care of the environment error. I read the release notes but it did not click for me, my **mistook.** 👎 

Thanks again.
