### ISSUE TITLE
Showing "</span>"

### ISSUE THREAD

**Issue by hyoshioka0128** [SharePoint/sp-dev-docs#3460]
https://docs.microsoft.com/ja-jp/sharepoint/dev/solution-guidance/custom-field-type-sharepoint-add-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efc70e7-88b1-0023-27bf-3d8b4568ef74
* Version Independent ID: f54e0d1d-673b-16c5-7065-cad7c754ec97
* Content: [Custom field type in the SharePoint Add-in model](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/custom-field-type-sharepoint-add-in)
* Content Source: [docs/solution-guidance/custom-field-type-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/custom-field-type-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by terrysheng** [comment]
@andrewconnell  I have received query from community regarding this has been pending for a while. Could you please have a look? Thanks

**Comment by andrewconnell** [comment]
Looks like it got fixed... will close.
