### ISSUE TITLE
Styles remain on the page whenever the web part gets unmounted

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#3461]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Whenever a web part / component / application customizer gets unmounted, it would be nice to also have a way to unregister the styles. At the moment all styles remain on the page, which means if you navigate between pages, the styles of all components that have been loaded will remain. This could lead to conflicting styles for components.

#### Observed Behavior

*Just as an example, I have overwritten the styles of the page header (this is only for the demo, so don't do this at home)*

![styling-remains-on-page](https://user-images.githubusercontent.com/2900833/52936429-61a93e00-335c-11e9-8db2-9d0f53814832.gif)

In this example, on page 1 and 2 the web part is loaded, on page 3 there is no web part loaded. Once page 1 or 2 gets loaded and you navigate back to page 3, you see that the styling is still in place.

In the real world, you can check the number of loaded style elements on the page. Here is my initial number on the homepage:

![screenshot 2019-02-18 09 09 01](https://user-images.githubusercontent.com/2900833/52936652-18a5b980-335d-11e9-9dde-2af7e71ac8bc.png)

After navigating through the site and its pages, I'll see the number rising (based on the number of web parts loaded):

![screenshot 2019-02-18 09 08 35](https://user-images.githubusercontent.com/2900833/52936683-3410c480-335d-11e9-8b8f-e1166cf9524f.png)

![screenshot 2019-02-18 09 12 03](https://user-images.githubusercontent.com/2900833/52936698-43900d80-335d-11e9-867c-3584b82aad60.png)

![screenshot 2019-02-18 09 17 22](https://user-images.githubusercontent.com/2900833/52936928-02e4c400-335e-11e9-9f4a-2dfbdfea8228.png)

I have checked how the `@microsoft/load-themed-styles` work, but there is no unregister method available.

Just as a test, I implemented a unregister functionality based so that when the web part `onDispose` method gets called, it unmounts the component + the styles. When the web part renders again, it will call the `loadStyles` method to re-add the styles to the page.

![unloading-styles](https://user-images.githubusercontent.com/2900833/52938035-ec8c3780-3360-11e9-8b7a-c5e9dd55b8d5.gif)

Would it be possible to have this kind of functionality coming from the framework itself? This would create fewer conflicts, but also have cleaner pages with fewer style elements.

#### Steps to Reproduce

Add a web part on one page, navigate to another page and you will see the style of the web part is still loaded. The styles are not part of the component, so that is why they do not get unloaded.

**Comment by estruyf** [comment]
This is also an issue when components are dynamically loaded. In the following example, when the button gets clicked, it loads a component that turns the page link to green. Once it was loaded the first time, navigating to another page, you will still see the effect although the component is not on the page anymore.

![dynamic-component](https://user-images.githubusercontent.com/2900833/52940497-00d33300-3367-11e9-9027-d254740f1447.gif)

**Comment by anomepani** [comment]
@estruyf , @VesaJuvonen  Can you please share your custom code or quick fix patch to unregister styles on Dispose method as we are facing the same issue on our production.

**Comment by switch13** [comment]
I'm having the same CSS caching issue whether I load it with:
`require('../css/custom.css');`
or if I add it in the CDN and use SPComponentLoader
`import { SPComponentLoader } from '@microsoft/sp-loader';`
`...`
`...`
`SPComponentLoader.loadCss("https://publiccdn.sharepointonline.com/" + tenantHostName + "/sites/AppCatalog/CDN/custom.css");`

**Comment by patmill** [comment]
So, changing this is a fairly fundamental change in both tooling, as well as the runtime.  We won't be fixing this in the near term, but we do have this marked as future work.
