### ISSUE TITLE
Apply Site Design in CSOM

### ISSUE THREAD

**Issue by manlamcheng** [SharePoint/sp-dev-docs#3462]
I have a CSOM app to provision sharepoint site with template STS#3, is it possible to apply a site design programmatically ?
thanks

**Comment by bcameron1231** [comment]
A couple ways to apply a site design programmatically using REST, PowerShell and CSOM.

To use REST or PowerShell - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview#using-powershell-or-rest-to-work-with-site-designs-and-site-scripts

Using CSOM, you can use tenant.applySiteDesign(). Documentation can be found here https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt845990(v%3Doffice.15)

**Comment by manlamcheng** [comment]
Thank you! I will give it a try

**Comment by VesaJuvonen** [comment]
Seem that @bcameron1231 replied on the question, so closing as answered.
