### ISSUE TITLE
Footer Placeholder broken by SingleWebPartAppPage

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-docs#3463]
#### Category
- [x ] Bug

#### Expected or Desired Behavior

For application customizer footer as documented here [using-page-placeholder-with-extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extension), when this is used in conjunction with SingleWebPartAppPage the footer does not stick to the bottom of the screen. As you scroll it does not stick to the bottom of the screen.

![image](https://user-images.githubusercontent.com/2708345/52963366-7f47c900-3397-11e9-990e-7af92d9b39e1.png)

#### Observed Behavior

when this is used in conjunction with SingleWebPartAppPage the footer does not stick to the bottom of the screen. As you scroll it should stick to the bottom of the screen.

![image](https://user-images.githubusercontent.com/2708345/52963396-8e2e7b80-3397-11e9-8afc-689aeea72ea2.png)

--
![image](https://user-images.githubusercontent.com/2708345/52963957-106b6f80-3399-11e9-9d18-f61278978016.png)

#### Steps to Reproduce

Deploy AppCustomizer to have a custom footer. Create a Site Page and convert that page to SingleWebPartAppPage 

Tks,
Gary

**Comment by VesaJuvonen** [comment]
This should have been fixed in 1.8 but would like to get confirmation in your scenario as well. Can you still repro this with 1.8 release?
