### ISSUE TITLE
Navigate event not triggering after second page navigation

### ISSUE THREAD

**Issue by carlosmiguelsns** [SharePoint/sp-dev-docs#3464]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
When navigating to a page (internally within the site collection) the navigatedEvent is triggered. After the first trigger happens, changing to different pages does not trigger the event again.

Thanks

**Comment by mcmynn83** [comment]
Sorry this took so long to address.  That being said, it looks like we have already fixed this.  If you are still seeing this broken please let me know how you repro it and I will re-open it.

I tried by creating 2 new pages and having them in the left nav.  When clicking the links from one to another multiple times we would fire an event in the _SPEventManager.instance.
