### ISSUE TITLE
Webpart maintaining state across pages when i would expect state to be lost.

### ISSUE THREAD

**Issue by MarkTuSM** [SharePoint/sp-dev-docs#3467]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Context:  I'm Developing a SPFX Webpart,  the general concept of it is that i would like the user to be able to "maximize" the screen into a full screen for this web-part's contents,  then minimize back to the webpart.  I am using react/Office-UI-Fabric to dirve most of this,  i have a variable (initalLoad)  which is true by default, it sets some values on the initial load of the page and then sets itself to false and never runs again. Then everything is driven by setState changes within the react framework.

#### Expected or Desired Behavior

When moving from 1 modern page to another (eg,  Orders.Aspx to Invoices.Aspx)  the "initial load" code within the webpart should run on each page.

#### Observed Behavior

When moving from 1 modern page to another the variable "initialLoad" the value of initialLoad on the first page is true (expected) it executes as expected and is then set to false (expected).   If you then navigate to another page using the Left hand Nav with the same webpart,  i would expect the initialLoad variable in the webpart to be true and execute the code,   however it loads in a "False" state.

i can press F5/click refresh to successfully reset the value of initialLoad and the webpart then functions as expected until i change pages again.

#### Steps to Reproduce

i'm hoping the context above should allow you to make something quickly to reproduce,  if not i'll have to strip my current solution down pretty far to maintain client confidentiality.

**Comment by thomasberman** [comment]
Where in your application does the init function run? In your webpart.ts file or in React's componentDidMount hook? Is there a difference if you move the init code between the two?

**Comment by MarkTuSM** [comment]
Hi,   will add my code below.


This is for the webpart.ts file

`  public onInit(): Promise<void> {
    return super.onInit().then(_ => {sp.setup({
      spfxContext: this.context
    });
  });
  }
  
  public render(): void {
    const element: React.ReactElement<ITestWebPartProps> = React.createElement(
      
      TestWebPart,
      {
        description: this.properties.description,
        URL: this.properties.URL,
        iconColor: this.properties.iconColor,
        AppendProjectNumber: this.properties.AppendProjectNumber,
        context: this.context
      }
    );
    ReactDom.render(element, this.domElement);
  }

  protected onDispose(): void {
    ReactDom.unmountComponentAtNode(this.domElement);
  }
`


This is for the react component

`import * as React from 'react';
import { ITestWebPartProps, ITestWebPartState } from './ITestWebPartProps';
import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http';
import { sp } from '@pnp/sp';

let ProjectSettings: any;
let initialLoad: boolean = true;


export default class TestWebPart extends React.Component<ITestWebPartProps, ITestWebPartState> {
  
  constructor(props){
    super(props);
    sp.setup({spfxContext: this.props.context});
    this.state = {
      promiseIsResolved: false,
      loadingScripts: false,
      isAdmin: false
    };
  }



  private getProjectSettings(): Promise<void> {
    return this.props.context.spHttpClient.get(this.props.context.pageContext.web.absoluteUrl + '/_api/lists/GetByTitle(\'Project Settings\')/items', SPHttpClient.configurations.v1)
      .then((response: SPHttpClientResponse) => {
        return response.json().then((responseJSON: any) => {
        console.log(responseJSON);
        ProjectSettings = responseJSON;
      });
    });
  }


   public componentDidMount(){
    if(this.props.AppendProjectNumber){
        this.getProjectSettings().then((res)=>{
          this.setState({promiseIsResolved: true});
        });
        }
  }
  
  public render(): React.ReactElement<ITestWebPartProps> {

      if(initialLoad) {
        alert("Page Loading")
        };
      initialLoad = false;

    return (
      <div>{ProjectSettings}</div>
    );
  }
}
`


my expected behaviour here,  is that whenever i change pages,  i would get an alert saying "page Loaded"   however observed behaviour is that i get it on the first page i go to,  any subsequent pages i get no popup at all (unless i do a full refresh) and the "initialLoad" variable stays as false across page loads

**Comment by CPritch** [comment]
Hi there, I have a suspicion that this is all from setting the globally set initial load variable from the render function. I have re-factored your code below and neatened up some things. Could you give this a crack instead?

Updated react component:

```
import * as React from 'react';
import { ITestWebPartProps, ITestWebPartState } from './ITestWebPartProps';
import { sp } from '@pnp/sp';

let ProjectSettings: any;

export default class TestWebPart extends React.Component<ITestWebPartProps, ITestWebPartState> {
  //Best to leave things tracked to state or a global store where possible and you can't set state in render
  constructor(props) {
    super(props);
    sp.setup({ spfxContext: this.props.context });
    this.state = {
      promiseIsResolved: false,
      initialLoad: true
    };
    //You don't have to wait for component mounting, you can invoke method from here
    this._initComponent();
  }


  // This is how you'd make the call using pnp
  private getProjectSettings(): Promise<any[]> {
    return sp.web.lists.getByTitle('Project Settings').items.get().then(res => { 
      console.log(res); 
      return res;
    });
  }


  private _initComponent() {
    if (this.props.AppendProjectNumber) {
      this.getProjectSettings().then((res) => {
        //Setting initial loads state here will trigger a re-render and will not show an alert from now on
        //I'd suggest also setting Project Settings as a state here as that would trigger re-render of Project Settings
        this.setState({ promiseIsResolved: true, initialLoad: false });
      });
    }
  }

  public render(): React.ReactElement<ITestWebPartProps> {
    // This should only show once
    if (this.state.initialLoad) {
      alert("Page Loading")
    };
    // If Project Settings is a global variable then you can't set state and use that to trigger a re-render
    return (
      <div>{ ProjectSettings } </div>
    );
  }
}
```
