### ISSUE TITLE
Page title getting bold

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/sp-dev-docs#3468]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When my custom webpart is loaded, the page title should be in the normal font weight.

#### Observed Behavior

After my custom webpart loads, the page title is being set to bold.

#### Steps to Reproduce

Create webpart with yo @microsoft/sharepoint
Run gulp serve
Create a page on a Sharepoint site and give it some title
Go to the page and add 
`?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&Mode=Edit` 
to the url. This will make the new webpart available in edit mode.
Insert the webpart.
Save the page.
Go to the page and add 
`?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js`
to the url.
Note how the title after a short while changes from normal to bold - see attached screenshot.
![image](https://user-images.githubusercontent.com/25172917/52997493-f83f3300-3420-11e9-8ca2-eff2ade04d54.png)

**Comment by StfBauer** [comment]
@Leif-Frederiksen in which browser have you experienced this issue. from a CSS perspective, it always shows the same font-weight.

**Comment by Leif-Frederiksen** [comment]
It happens in Chrome, IE11 and Firefox.

Den ons. 20. feb. 2019 kl. 12.02 skrev Stefan Bauer <
notifications@github.com>:

**Comment by kemesfun** [comment]
@Leif-Frederiksen Is this issue still happening? I am testing on a HeartBeat Tenant and the font weight doesn't change.
