### ISSUE TITLE
emit event from AppComponent to Webpart (Angular2)

### ISSUE THREAD

**Issue by ghost** [SharePoint/sp-dev-docs#347]
#### Category
- [x] Question

I need to emit event  from AppComponent to WebPart in Angular2. 
In my **AppComponent** I added output event:

**@Output() outputEvent : EventEmitter<any> = new EventEmitter();
  sendOutEvent(){ this.outputEvent.emit('hello webpart?')};**

I defined event handler in WebPart render() method:

 **public render(): void {
 this.domElement.innerHTML = `<my-app (outputEvent)="handleEvent($event)"></my-app>`;
}**
 but I cannot seem to find a way to watch it in WebPart. I need it for activation of function openPropertyPane().

**Comment by manishgarg1** [comment]
@ghost, can you please share your web part code? Our Angular2 story is still in the works. There are multiple aspects of Angular2 that are unique.

**Comment by patmill** [comment]
No response for a long time.  Closing this down.
