### ISSUE TITLE
Can't perform modern site searches and entirly jquery isn't working

### ISSUE THREAD

**Issue by MohamedMusthaque** [SharePoint/sp-dev-docs#3472]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

From the SharePoint Admin portal, I have got the following issue. 

Title: Can't perform modern site searches 
User Impact: Users may be unable to perform site searches from modern sites. 
More info: Users may receive a "Something went wrong! Please try searching again or refresh the page" error. While we're focused on remediation, users can click on the Organization search breadcrumb at the top of the search box to perform a tenant-wide search rather than a site search. Until the fix is deployed, we recommend users add path:"[URL-OF-THE-TEAMSITE]" to the search box, in addition to your search term, as a workaround to complete a site search. Current status: We've identified an update to search code has impacted modern site search functionality. We've developed a code fix and are in the process of deploying it throughout all affected environments to resolve the impact. Scope of impact: This issue could potentially affect any users performing a modern site search. 
Start time: Friday, February 1, 2019, at 12:00 AM UTC 
Estimated time to resolve: We estimate the fix will be completely deployed by the end of Tuesday, February 26, 2019. 
Preliminary root cause: An update to search code, which was expected to prevent a user relevancy search issue for modern sites from impacting site searches, isn't working as intended. 
Next update by: Tuesday, February 26, 2019, at 9:00 PM UTC

And also, suddenly today morning onward jquery is not working entirely in the hole tenant.
For the jquery, I used the CDN and SiteAssets options in the script editor. But still remaining the issues.

Are there any connections between these two.

**Comment by andrewconnell** [comment]
In the future, it's better to just submit one issue per topic instead of combining them.

For the search issue, there's no action to perform if MSFT has ack'd an issue, specified a workaround and given an ETA on the resolution rollout.

For jQuery, I can't duplicate. Tried three tenants that use the official CDN version of jQuery and they all work as expected. Please provide more detail or a repro...

**Comment by MohamedMusthaque** [comment]
Hi @andrewconnell,

Now it's working only in Internet Explorer. I don't know why it's only working in IE. Previously it worked well in all browsers. Now not even in Edge browser. Please advice me.

**Comment by andrewconnell** [comment]
In [my original reply above](https://github.com/SharePoint/sp-dev-docs/issues/3472#issuecomment-465600853):

> In the future, it's better to just submit one issue per topic instead of combining them.

You say:

> Now it's working only in Internet Explorer

What is / isn't working? Can't tell what you're referring to as your original post mentions two issues.

For the search issue, that's already been addressed above... there's nothing to do but wait for the fix to roll out which, as the M365 Admin Portal stated, will be next week.

For the jQuery issue, I still can't repro. Please open a new issue that's just dealing with your jQuery problem (if that's what you're having issues with) & share additional details as there isn't enough info to work from & help you. Need things like how you're using jQuery, how it's referenced, SPFx version, environment, code, etc.
