### ISSUE TITLE
Bug with date column calculated values when editing document

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#3474]
SharePoint date column with default calculated value such as [Today] or [Today]+1 sometimes works when document is initially created but then disappears when a document is edited in word online.

To Replicate:
Create time/date column on a document library called “Expiry”, set a default value of =[Today]+1. 
Create new document in library
Edit document again (date field is cleared)

The date value sometimes set automatically when a document is created, other times it isnt but it always loses the default date value when the document is edited for a second time.

![test22](https://user-images.githubusercontent.com/17725046/53088723-7de6df80-3502-11e9-87e7-3d95f9c34098.png)

As you can see it has stripped out the date data after the word document is edited in SharePoint online and lost the metadata.

This can be replicated in any tenancy (as far as i am aware).

This has been logged as an admin centre support ticket.

**Comment by VesaJuvonen** [comment]
As calculated columns is not considered as a development topic, we cannot, unfortunately, route the issue through this channel and it should be reported from tenant admin UIs. Sorry for the inconvenience.
