### ISSUE TITLE
CSOM: Loading TermGroup ContributorPrincipalNames or GroupManagerPrincipalNames throws ServerUnauthorizedAccessException when using application context

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#3475]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It should be possible to load [TermGroup.ContributorPrincipalNames](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt807194(v=office.15)) and / or [TermGroup.GroupManagerPrincipalNames](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt807195(v%3Doffice.15)) using azure ad application permissions.

#### Observed Behavior

When loading **TermGroup.ContributorPrincipalNames** and **TermGroup.GroupManagerPrincipalNames** using an Azure Ad Application context the API throws: **Microsoft.SharePoint.Client.ServerUnauthorizedAccessException**

![image](https://user-images.githubusercontent.com/31658807/53105251-0b412880-3531-11e9-891d-796822946d90.png)

All other termstore read and write operations work fine. The app has all permissions needed:

![image](https://user-images.githubusercontent.com/31658807/53105448-725edd00-3531-11e9-96b9-4d0d8910b436.png)

#### Steps to Reproduce

Use the following code example.  

```
//you do not need to load application context using this function. Just make sure you have a valid application context and not a normal user context.
var appContext = authManager.GetAzureADAppOnlyAuthenticatedContext(siteurl, clientId, tenant, StoreName.Root, StoreLocation.CurrentUser, thumpPrint, AzureEnvironment.Production);

//Enter an existing termGroup here
string groupName = "TestGroup";
var taxonmySession = TaxonomySession.GetTaxonomySession(appContext);
var termStore = taxonmySession.GetDefaultSiteCollectionTermStore();
var termGroup = termStore.Groups.GetByName(groupName);
appContext.Load(termGroup, t => t.ContributorPrincipalNames, t => t.GroupManagerPrincipalNames);
appContext.ExecuteQuery();
```

**Comment by wobba** [comment]
Hi see 
https://www.techmikael.com/2018/08/modifying-terms-using-app-only-tokens.htm for a solution. Basically add `app@sharepoint` as a term store admin and it will work.

**Comment by MrTantum** [comment]
Looks like the link is dead. But I'll give app@sharepoint a try.

**Comment by wobba** [comment]
Added the missing l to the link 👍

**Comment by MrTantum** [comment]
It's working. But still very dangerous for the multi tenant isp solution we want to use this. If Microsoft changes the user principal the operation will fail again.

**Comment by wobba** [comment]
It's very unlikely as this was implemented back in 2013, but up to you. I use it myself in production over delegated permissions and a service account. But, it's not officially documented. @VesaJuvonen, do you think this bit could be officially documented?
