### ISSUE TITLE
Conditional classes based on a date field does not work in non-US locales

### ISSUE THREAD

**Issue by zalbermere** [SharePoint/sp-dev-docs#3477]
This example (https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#conditional-classes-based-on-a-date-field) does not work where site locale is set to display dates DD/MM/YY

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#conditional-classes-based-on-a-date-field)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by pmatthews05** [comment]
I have encountered this problem too, and blogged about it here. https://cann0nf0dder.wordpress.com/2019/03/09/sharepoint-online-custom-format-view-issue-with-now-and-uk-date-format/
