### ISSUE TITLE
Timeline React 16, Typescript 3*, UI Fabric React 6* 

### ISSUE THREAD

**Issue by hohenp** [SharePoint/sp-dev-docs#3478]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi Folks, sorry for creating another ticket to a already discussed situation regarding outdated packages within SPFx, but I could never find information when an possible update will be available.

With the Intro of the Modern UI we have build a bunch of "Modern Solutions" for SP2013 using React, UI Faric, Typescript, etc. There we have used the latest versions like React 16 and UIFabricReact 6. Now we are going to move these solutions within "Real Modern" SPFx for SP19 and SPOnline but now have dependencies to the versions of TS, React, UIFabric, etc... bulid in SPFx / SP2019 / SPOnline.

So in the moment we have the choice to 
a) downgrade all our Solutions to be compatible with SPFx 1.7.x
b) wait until the packages got updated

So, can you give a timeline for these updates? Maybe SPFx 1.8?
Is there anywhere an overview which versions of these packages is supported in a specific SPFx Bundle?
(thanks @andrewconnell for your [1.7 page](http://www.andrewconnell.com/blog/sharepoint-framework-v1-7-0-what-s-in-the-latest-update-of-spfx), that helped)

Thanks alot
Pascal

**Comment by andrewconnell** [comment]
I can answer part of this: no changes are planned for on-prem SharePoint (2016 / 2019); what you see today is what you get until the next major update as there are no plans to update SPFx out of band with major releases.

> Is there anywhere an overview which versions of these packages is supported in a specific SPFx Bundle?

The best approach is to install the SPFx generator version & create a project. that will list the supported versions in the **package.json** file.

WRT updating TypeScript (v3.*), Node.js LTS (v10.*), webpack (v4), latest React (v16.x... *what is currently used in SPFx & SPO is not latest v16 but one that's many months back*) & Fabric React (v6)... no roadmap has been shared ATM. I'll let someone from MSFT address that.

IMHO, probably best to hold on until we see what's in v1.8 which they's stated will drop in the first half of March.

**Comment by VesaJuvonen** [comment]
This was all included in the 1.8 release - or React, TypeScript and fabric support. Node JS LTS v10 and WebPack v4 are targeted in the 1.9... Here's 1.8 release notes - https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes
