### ISSUE TITLE
Create SharePoint Communication site using REST

### ISSUE THREAD

**Issue by timcreancu** [SharePoint/sp-dev-docs#3479]
We were not having any luck with the documentation to create SharePoint Communication site using REST.

Our developer found that the request type “SP.Publishing.CommunicationSiteCreationRequest” does NOT work and the request type"Microsoft.SharePoint.Portal.SPSiteCreationRequest" works.

The first request type just resulted in an error code 3.

Does this documentation just need to be updated, or are we missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d1ea72-8ceb-201c-e2a5-ce75033d246b
* Version Independent ID: 61532d1f-45ab-1100-0fc4-4db441b4c949
* Content: [Create SharePoint Communication site using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/communication-site-creation-rest)
* Content Source: [docs/apis/communication-site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/communication-site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Are you able to share your Request Call to help us further debug the issue?

I have just tested this on two environments both of which were successful.

`fetch("https://MyTest.sharepoint.com/_api/sitepages/communicationsite/create", {
    "credentials": "include",
    "headers": {
        "accept": "application/json;odata=verbose",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/json;odata=verbose",
        "x-requestdigest": "<requestDigest>"
    },
    "body": "{   \"request\":{      \"__metadata\":{         \"type\":\"SP.Publishing.CommunicationSiteCreationRequest\"      },      \"AllowFileSharingForGuestUsers\":false,      \"Classification\":\"LBI\",      \"Description\":\"Description\",      \"SiteDesignId\":\"6142d2a0-63a5-4ba0-aede-d9fefca2c767\",      \"Title\":\"Comm Site 1\",      \"Url\":\"https:\/\/MyTest.sharepoint.com\/sites\/CommsiteTest\",      \"lcid\":1033   }}",
    "method": "POST",
    "mode": "cors"
});`

**Comment by bcameron1231** [comment]
Are you able to share your Request Call to help us further debug the issue?

I have just tested this on two environments both of which were successful.

```
fetch("https://MySite.sharepoint.com/_api/sitepages/communicationsite/create", {
    "credentials": "include",
    "headers": {
        "accept": "application/json;odata=verbose",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/json;odata=verbose",
        "x-requestdigest": "<RequestDigest>"
    },
    "body": "{   \"request\":{      \"__metadata\":{         \"type\":\"SP.Publishing.CommunicationSiteCreationRequest\"      },      \"AllowFileSharingForGuestUsers\":false,      \"Classification\":\"LBI\",      \"Description\":\"Description\",      \"SiteDesignId\":\"6142d2a0-63a5-4ba0-aede-d9fefca2c767\",      \"Title\":\"Comm Site 1\",      \"Url\":\"https:\/\/MySite.sharepoint.com\/sites\/commsiteTest\",      \"lcid\":1033   }}",
    "method": "POST",
    "mode": "cors"
});
```

**Comment by timcreancu** [comment]
Thanks Beau.  I am joining @Youcef N Baouchi<mailto:youcef@Colorado.EDU> into this thread to provide the details.


—
Tim Crean
Sr. Messaging and Collaboration System Administrator
University of Colorado at Boulder
OIT – Messaging and Collaboration
Direct: 303-735-2534
Mobile:  720-841-7811
Email: Tim.Crean@colorado.edu<mailto:Tim.Crean@colorado.edu>

**Comment by timcreancu** [comment]
Hi Beau,

I just recreated this exact request with the same result. Still getting the same error back from the api. The endpoint accepts the body returns a 200 status, but comes back with the response below.

responseFromServer = "{\"d\":{\"Create\":{\"__metadata\":{\"type\":\"SP.Publishing.CommunicationSiteCreationResponse\"},\"SiteStatus\":3,\"SiteUrl\":\"\"}}}";

Please keep in mind that the undocumented endpoint works just fine and creates the site the properly.

**Comment by bcameron1231** [comment]
Sorry  if I'm asking too many questions - Did you execute that in the console of dev tools? Or executing the REST call differently?

Are you able to copy the request from dev tools(feel free to blur out your tenant information), so we can see all of the request headers?

**Comment by findyoucef** [comment]
@bcameron1231 

Hey Beau, thank you for all your help. I was making the request through visual studio project, but here is a curl request showing the same thing:

curl -X POST -H "accept: application/json;odata=verbose" -H "accept-language: en-US,en;q=0.9" -H "content-type: application/json;odata=verbose" -H "x-requestdigest: <RequestDigest>" -H "Authorization: Bearer REDACTED" -d @share.json https://o365coloradoedu-admin.sharepoint.com/_api/sitepages/communicationsite/create

share.json file contains the following json:

{"request":{"__metadata":{"type":"SP.Publishing.CommunicationSiteCreationRequest"},"AllowFileSharingForGuestUsers":false,"Classification":"IT","Description":"test site","SiteDesignId":"6142d2a0-63a5-4ba0-aede-d9fefca2c767","Title":"test site aurora","Url":"https://o365coloradoedu.sharepoint.com/sites/aurora1234Site","lcid":1033}}


and the request returns the following response:

{"d":{"Create":{"__metadata":{"type":"SP.Publishing.CommunicationSiteCreationResponse"},"SiteStatus":3,"SiteUrl":""}}}


I found this issue reported here as well:

https://github.com/SharePoint/PnP-PowerShell/issues/1542

**Comment by findyoucef** [comment]
@bcameron1231 https://github.com/SharePoint/PnP-PowerShell/issues/1542#issuecomment-400593480

**Comment by bcameron1231** [comment]
Could you do me a favorite and execute the Fetch request I had posted earlier, and paste it into dev tools with the proper URLs and Digest?

I believe there ma be an issue with creating Communication sites without a User Context. I think we'll be able to make a better determination if you can execute that fetch in Chrome Dev Tools.  If it does indeed work... then I would advise to try and create a User Context based on the user's access token.

**Comment by findyoucef** [comment]
yes, we're using an app access token which works fine with the other endpoint. I ran the fetch request and go the following from the dev console.

Access to fetch at 'https://o365coloradoedu.sharepoint.com/_api/sitepages/communicationsite/create' from origin 'https://o365coloradoedu-admin.sharepoint.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

**Comment by bcameron1231** [comment]
So that just means you are executing from the admin center "-admin" which is a different domain, so you got a CORS error.

Try to execute the request in Dev Tools but from https://tenant.sharepoint.com/ instead of tenant-admin.sharepoint.com

**Comment by findyoucef** [comment]
@bcameron1231  oops, that just gives me a 403 

"https://tenant.sharepoint.com/_api/sitepages/communicationsite/create 403"


Is that what you expected?

**Comment by bcameron1231** [comment]
Did you get a new Request Digest to pass over in the request? If not, you can get one from POST /_api/contextinfo and grabbing it from the response.

In any case, I do not believe this endpoint allows you to create a site using App Credentials, I believe it requires a  User Context to successfully create a site.

**Comment by findyoucef** [comment]
@bcameron1231

so why does it successfully accept the token? why does the other endpoint work while this one does not with app credentials? Is this documented anywhere?

**Comment by findyoucef** [comment]
@bcameron1231 

and if you're sure that's the case why does  the endpoint url: /_api/sitepages/communicationsite/status

accept app crendentials. This endpoint is documented in the same place as /create?

**Comment by bcameron1231** [comment]
I can't be certain why... except that they are different requests. I confirmed on my end that I was unable to use app tokens for that call.

I don't see a problem using the Microsoft.SharePoint.Portal.SPSiteCreationRequest as the Patterns and Practices JS library also uses this endpoint. 

I also checked against Patterns and Practices Sites Core library and it also used to use Microsoft.Sharepoint.Portal.SPSiteCreationRequest, but is now using another endpoint _api/SPSiteManager/Create which should also allow for app only tokens.

Hope this helps. Maybe we can get some clarify on the endpoint and update the documentation accordingly for app-only requests.

**Comment by findyoucef** [comment]
@bcameron1231 

Thanks for looking into this. I appreciate everything you've done today. One last last thing when you confirmed not being able to use app tokens for that end point did you get a json response with this body:

{"d":{"Create":{"__metadata":{"type":"SP.Publishing.CommunicationSiteCreationResponse"},"SiteStatus":3,"SiteUrl":""}}}

or did you get 401 or something different entirely?

**Comment by bcameron1231** [comment]
Correct. I have received the same response., with the Error code 3.
