### ISSUE TITLE
Item does not exist it may have been deleted by another user

### ISSUE THREAD

**Issue by dhoyek** [SharePoint/sp-dev-docs#3482]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Document to be uploaded successfully

#### Observed Behavior

The first time the document is uploaded fine, however after name change by code and trying to same document again we receive the following error (Check screen shot) 

#### Steps to Reproduce

Upload a document, have its name changed and update some other properties. Upload the same document again. An error popup: Item does not exist
![image](https://user-images.githubusercontent.com/6195708/53231476-aea94f00-3691-11e9-9743-6b03e6d344da.png)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Can you provide some context? Are you doing this with the web UX or with an API (I see `M.S.Client.Rest` in the screenshot). If with code, please share the code that's failing.
