### ISSUE TITLE
Search API : What does UILanguage property actually do?

### ISSUE THREAD

**Issue by cslecours** [SharePoint/sp-dev-docs#3486]
Can't find anything about the effects of setting this property on search results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@wobba do you have insight search master?

**Comment by wobba** [comment]
Hi,
that's a very good question indeed. Can't see anything in the result which uses this on return value, and have never seen the property myself before.

`Culture` I know has a place as it determines the language for stemming/lemmatization.

Looking at the query spec's https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-qssws/5d575c6a-bd74-4142-8e88-ae9534019dbb it seems this is a property left over from the SharePoint 2007 (or 2010?) era before FAST. You could try it against an old SP installation and see if it returns a pointer to some localization resources used in rendering the results or similar.

**Comment by cslecours** [comment]
I did a query on SharePoint Online (I have no access to on premise SharePoint).

As per the docs : 
`GET /_api/search/query?querytext='sharepoint'&uilanguage=1044`

The serialized query that was returned in the results properties looked like this : 
No mention of UILanguage anywhere.

I guess it is effectively ignored.

`<Query Culture="en-US" EnableStemming="True" EnablePhonetic="False" EnableNicknames="False" IgnoreAllNoiseQuery="True" SummaryLength="180" MaxSnippetLength="180" DesiredSnippetLength="90" KeywordInclusion="0" QueryText="sharepoint" QueryTemplate="" TrimDuplicates="True" Site="267ccbfa-ccb3-48ec-80bb-769250ea172b" Web="8319d5e5-a18b-47b0-897c-1764dc5d55f9" KeywordType="True" HiddenConstraints="" />`
