### ISSUE TITLE
Version property shown wrong initial version number in Teams manifest

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3488]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The created team 'manifest.json' should show a semantic version instead of just `0.1`

#### Observed Behavior
The `manifest.json` file created by SPFx generator contains the following version information.

<img width="639" alt="screenshot 2019-02-24 at 11 34 26" src="https://user-images.githubusercontent.com/5503835/53298059-3628c680-3828-11e9-87b0-5bd2e488c7c5.png">

To keep it consistent it should at least create a proper semantic version or the old and outdated Microsoft version system of `<major>.<minor>.<build>.<revision>`. 

This way consistent versioning can be used in the SPFx package-solution as well as the teams manifest.

#### Steps to Reproduce
Create a new project using `--plusbeta`switch and check in the teams folder the manifest.json file for the version number.

**Comment by VesaJuvonen** [comment]
As the implementation has been changed, this issue is no longer valid, so closing it.
