### ISSUE TITLE
PropertyPaneDropdown Property 'SelectedKey' Not Working

### ISSUE THREAD

**Issue by pkwitbrod** [SharePoint/sp-dev-docs#349]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
_According to the documentation found [here](https://github.com/SharePoint/sp-dev-docs/blob/master/reference/spfx/sp-webpart-base/ipropertypanedropdownprops.md) you should be able to add the selectedKey property to the PropertyPaneDropdown to select a default option._

#### Observed Behavior
_`  PropertyPaneDropdown('test2', {
            label: 'Dropdown',
            options: [
              { key: '1', text: 'One'},
              { key: '2', text: 'Two' },
              { key: '3', text: 'Three' },
              { key: '4', text: 'Four'}
            ],
            selectedKey: '4',
        })`

The above code does not give make 'Four' the default option. When I inspect the the DOM using React tools selectedKey is not present and selectedIndex is -1. See image 1. 

<img width="284" alt="screen shot 2017-01-15 at 4 42 34 pm" src="https://cloud.githubusercontent.com/assets/6709629/21967396/6a2aebe8-db4b-11e6-9171-1a1fa3fdf86c.png">

The onChange method appears to set the selectedKey property just fine. See image 2

<img width="315" alt="screen shot 2017-01-15 at 4 43 15 pm" src="https://cloud.githubusercontent.com/assets/6709629/21967400/9dfb064c-db4b-11e6-8c81-c1602df2a02a.png">

I did dig around in the node_modules and found this in spwebpartbase/dist/sp-webpart-base-propertypane_<GUID>.js (Line 477 in my text editor)

`  case IPropertyPaneField_1.PropertyPaneFieldType.Dropdown:
	                groupFieldElement = React.createElement(office_ui_fabric_react_1.Dropdown, __assign({}, groupField.properties, {ref: setRef, selectedKey: propValue, disabled: groupField.properties.isDisabled || groupField.properties.disabled, label: groupField.properties.label, onChanged: function (option, index) {
	                    _this._onDropDownChange(groupField, option, index);
	                }}));
	                break;`

selectedKey's value is set to propValue. disabled works for me and is set to groupField.properties.isDisabled so I changed the value of selectedKey to groupField.properties.selectedKey and re-served the code and it worked fine. 

After I tested that I changed it back and it stopped working again. I doubt that is the final fix but hopefully it will help point you in the right direction. 

_

#### Steps to Reproduce
_
Get RC0 Version of spfx
Create a PropertyPaneDropdown in a webpart and add the selectedKey property too it.
Serve the webpart and open the webpart property pane.
Observe that the default is not set._

**Comment by manishgarg1** [comment]
This definitely looks like a bug. We will try and fix it asap.

**Comment by pkwitbrod** [comment]
Thank you @manishgarg1!

**Comment by srideshpande** [comment]
This is fixed. Can you please check this and confirm the same. I am closing this case now. Please re-open it if you still see the issue.

**Comment by Rajesh-Pradhan** [comment]
This fix works for me but it fails when I'm trying to open the WebpartPros for the first time. From second time onward dropdown values appearing. Any idea ?
