### ISSUE TITLE
Not able to deploy SPFx webpart in Sharepoint 2019 onprem

### ISSUE THREAD

**Issue by krishnavandanapu** [SharePoint/sp-dev-docs#3490]
Hi All,

I have setup SharePoint 2019 on-prem and getting the below error when I am trying to deploy SPFx webpart control as part of the catalog:

**There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsClientSideSolution' attribute is not declared.' on line '1', position '249'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'StartPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '338'., Xml Validation Exception: 'The element 'App' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'AppPrincipal' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '351'.**

When I search over the internet I see the same issue in SP2016 but nothing with SP19.

I have also installed all the updates provided in the below link:
https://docs.microsoft.com/en-us/officeupdates/sharepoint-updates

Request you to help me with the solution.
Thank you for your support in advance.

**Note**: The same solution is working seamlessly in SPO.

Regards,
Krishna.Vandanapu

**Comment by StfBauer** [comment]
In the root of your project, you should find a file named '.yo-rc.json' can you please copy the content of this file in here.

This will help to identify which project template you used to create your project.

Not all the latest features you can use in SharePoint Online can be used in on-premises web parts.

**Comment by krishnavandanapu** [comment]
Hi Bauer,

Thank you for your reply, please find the below content of the file you asked for:

{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "spo",
    "version": "1.7.1",
    "libraryName": "hello-world",
    "libraryId": "62e3d292-3179-42b1-a22c-2ada7dded013",
    "packageManager": "npm",
    "componentType": "webpart"
  }
}

Thank you,
Krishna Vandanapu

**Comment by krishnavandanapu** [comment]
just to update you sir,

I have added the library path as below in "config\copy-assets.json" file (config folder)
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json",
  "deployCdnPath": "/SPFx Files/Multilines Control"
}
thank you for your help in advance!

**Comment by StfBauer** [comment]
@krishnavandanapu thank you for posting your `.yo-rc.json`. The important property in this file is the environment. In your case it state 'spo' which means your web part only is capable of being served on SharePoint Online.

Other possible values are: 
* `onprem`- SharePoint 2016, SharePoint 2019 and SharePoint Online
* `onprem19`- SharePoint 2019 and SharePoint Online

Depending on your selection in this dialogue other dependencies and configurations get installed.

<img width="638" alt="screenshot 2019-02-26 at 08 31 07" src="https://user-images.githubusercontent.com/5503835/53394904-e28db880-39a0-11e9-8457-36f01053a999.png">

You cannot run an SPO targeted web part on an older version but you can run it on a newer version.

To solve your issue you have to target for, 'SharePoint 2019 and SharePoint Online' this way you can install it on an SharePoint 2019 Server and SharePoint Online too,

**Comment by krishnavandanapu** [comment]
Hi Bauer,

I have done that also, but there was no luck 👎 with that option as well. However I will try one more time and let you know.

Regards,
Krishna Vandanapu

**Comment by StfBauer** [comment]
Have you tried it on a new folder or on a previously created folder? What options have you chosen?
Could it be that you have chosen during the wizard "Create new folder"?

**Comment by krishnavandanapu** [comment]
No I have not selected this option as create a new folder but I have a new folder using md command before I run yo @microsoft/sharepoint command.
By the I would like to list the version information on my machine:
PS C:\Users\krish> npm list -g --depth 0
C:\Users\krish\AppData\Roaming\npm
**+-- @microsoft/generator-sharepoint@1.7.1**
+-- gulp@4.0.0
`-- yo@2.0.5

**Comment by StfBauer** [comment]
This listing looks normal to me. The only thing that might cause troubles it the gulp version because currently only gulp@3.x.x is supported and not gulp@4.0.0

Just to make sure: There is no `.yo-rc` file in the folder above your project folder?

Now I create project myself with the following settings:

<img width="898" alt="screenshot 2019-02-26 at 19 27 06" src="https://user-images.githubusercontent.com/5503835/53436922-8fe1ea00-39fc-11e9-9172-8cdde9352585.png">

This produced the following `.yo-rc.json`:

```js
{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "onprem19",
    "version": "1.7.1",
    "libraryName": "moses-2",
    "libraryId": "748c1a6f-d5e5-4262-8bf1-9fd17e736d48",
    "packageManager": "npm",
    "componentType": "webpart"
  }
}
```

The package.json: looks like this:

```js
{
  "name": "moses-2",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
```

**Comment by krishnavandanapu** [comment]
so with this configuration you are able to deploy and run SPFx webpart in SP19 environment ! is that my understanding right Bauer?

**Comment by krishnavandanapu** [comment]
Hi Bauer,

I have uninstalled gulp 4.x.x version and installed gulp 3.9.1 and sharepoint generator 1.4.0 see the below image for your reference !

![image](https://user-images.githubusercontent.com/46300598/53512812-bbfb7a80-3a91-11e9-8071-e7cf1c618aca.png)

Also I have created project with below options:

![image](https://user-images.githubusercontent.com/46300598/53512906-ed744600-3a91-11e9-8eaa-0561fc2655bb.png)

Still I am getting the below error while I am uploading the solution in app catalog gallery :(

![image](https://user-images.githubusercontent.com/46300598/53512996-198fc700-3a92-11e9-985c-ece17d3494e6.png)

.yo-rc.json

![image](https://user-images.githubusercontent.com/46300598/53513113-6c697e80-3a92-11e9-9512-9e007963f434.png)

App Manifest.xml where it says that: 'The 'IsClientSideSolution' attribute is not declared.' in the error message:
![image](https://user-images.githubusercontent.com/46300598/53513159-873bf300-3a92-11e9-9b31-6e9c7a7ab23a.png)


Please help me to resolve this issue !!

**Comment by krishnavandanapu** [comment]
Hi Bauer,

Could you please help me on this I am completely stuck here !

Regards,
Krishna

**Comment by krishnavandanapu** [comment]
Hi Bauer,

Could you please help me on this !!!

Regards,
Krishna

**Comment by nikskhubani** [comment]
We had customer having the same issue and she said she could fix the issue with this comment:

"We fixed it using SharePoint 2019 **without the CU** of 2019 and App Catalog created in **English**"

So looks like the few last updates causing this issues.

**Comment by krishnavandanapu** [comment]
Hi Skhubani,

Thank you for your update I have installed all the updates provided in below blog from Microsoft.
[https://docs.microsoft.com/en-us/officeupdates/sharepoint-updates](https://docs.microsoft.com/en-us/officeupdates/sharepoint-updates).

As I can see KB4462171 is the CU for SP2019, Please let me know in case if you know any other KB.

Regards,
Krishna.Vandanapu

**Comment by nikskhubani** [comment]
Hey Krishna,

I was referring SP2019 **without** CU update. So you might have to unistall that CU update.

**Comment by krishnavandanapu** [comment]
Sure Skhubhani,

I will try and let you know thank you for your help.
Any other suggestions on gulp / node / sharepoint-generator versions? as of now I am using the below:
![image](https://user-images.githubusercontent.com/46300598/53966699-a73a6a80-40c1-11e9-8d4d-94358bf0f551.png)
-Krishna

**Comment by krishnavandanapu** [comment]
Hi Skhubhani,

Since we can't uninstall any CU, I have rebuild the VM but still there is no luck.
Could some one please help on this.
Regards,
Krishna

**Comment by krishnavandanapu** [comment]
Guys,

Could some one help me on this !!!

Regards,
Krishna

**Comment by krishnavandanapu** [comment]
Hi SPFx team,

Is there any way to change the criticality of this? I really need help and I am blocked with this issue !!!!

-Krishna

**Comment by krishnavandanapu** [comment]
Hi All,

It has been almost a month, could someone help me on this.

-Krishna

**Comment by nikskhubani** [comment]
Hi krishna,

We do have version **1.4.1**

Worth for you to upgrade to it and create a test solution

**Comment by krishnavandanapu** [comment]
Hi Skhubani,

Thank you for your response.

I have initially tried with the below set of versions but no luck:
SPFx : 1.4.0 , 1.4.4, 1.7.1
gulp@4.0.0, 3.9.1
yo@2.0.1, 2.0.5

Could you please help with any other idea.

-Krishna

**Comment by nikskhubani** [comment]
I am not sure what more to say here. Can you do following?

1. Try with our package, you can download the latest from: https://www.shortpoint.com/download/spfx
2. Add the app to app catalog and deploy. 

If that worked, that means the issue is in your package, if no, the issue is in your Farm. 

Also can you upload your package here?

**Comment by krishnavandanapu** [comment]
Thank you a ton buddy, I will try it and let you know. I will also share my package to you EST evening.

**Comment by krishnavandanapu** [comment]
Skhubani,

Just to confirm this solution you have deployed in SHP16 / SHP19?

-Krishna

**Comment by krishnavandanapu** [comment]
I got the same error like as my component in **SharePoint 2019** env. Please find the below for your reference.

![Error with Short Point client side webpart](https://user-images.githubusercontent.com/46300598/54945000-28d82800-4f0b-11e9-952e-0a0bdd9b2f32.png)
Skhubani,

-Krishna

**Comment by krishnavandanapu** [comment]
Skhubani,
Please find attached SPFx webpart I have created it is a simple webpart (no change in the default webpart).
I have created webpart with the below versions:
+-- @microsoft/generator-sharepoint@1.7.1
+-- gulp@4.0.0
`-- yo@2.0.5

I have created this package as below:
![image](https://user-images.githubusercontent.com/46300598/54966782-c6534c00-4f4b-11e9-9f5f-bc2d13843e0a.png)

[demo-wp.zip](https://github.com/SharePoint/sp-dev-docs/files/3006226/demo-wp.zip)

Do let me know, if you see any changes required.
-Krishna

**Comment by VesaJuvonen** [comment]
Hi @krishnavandanapu, this thing looks strange and we absolutely need more information on your environment. Looking at the long thread we can conclude the following:

- Things work in normal setup without any additional patches and by choosing right version in Yeoman
- Your environment seems to have something different, which we need to investigate
- Your app catalog is created in strange URL as sp19:9534/apps - not under a managed path, which would be typically the case under normal application - could cause issues

That exception which you see is due the fact that server seems to run the wrong schema file, which implies challenges on the version which you are using, so can you go to the Central Admin and Server UIs - which will show the version of the each server... so that we can understand exactly what version of SP your environment is running. Thx.

**Comment by krishnavandanapu** [comment]
Hi Vesa,

Thank you for your response, please find the below information for my VM:
I have created Explicit managed path "/apps" in web application http://sp19:9535

![image](https://user-images.githubusercontent.com/46300598/55041293-ca8e7080-5002-11e9-85f8-0c2efeeedead.png)

I have created a standalone VM with only one server, and the server version is as follows:
![image](https://user-images.githubusercontent.com/46300598/55041298-d37f4200-5002-11e9-8739-267f80cf36da.png)

Request you to advise me for a right Yeoman & GULP version. Now I am using below versions:
+-- @microsoft/generator-sharepoint@1.7.1
+-- gulp@4.0.0
`-- yo@2.0.5

Please correct me, if you see I am wrong at any step of my server configuration.
-Krishna

**Comment by VesaJuvonen** [comment]
Any chance you could test this by recreating app catalog in sites managed path as that's the only strange setup in the environment based on the information you shared. Thx.

**Comment by krishnavandanapu** [comment]
Vesa,

For sure I will do it tonight failing which this weekend and let you know the results.

Thank you a ton for your help.

-Krishna

**Comment by andrewconnell** [comment]
@krishnavandanapu All site collections are typically created under the managed path **/sites/**.

So... your app catalog would be under that ideally... like **https://.../sites/appcatalog**

**Comment by krishnavandanapu** [comment]
Got it thank you Andrew !
-Krishna

**Comment by krishnavandanapu** [comment]
Hi Vesa,

I have created a new web application and created app catalog as advised, but still I see the same below error :(

![image](https://user-images.githubusercontent.com/46300598/55323793-1d768680-544e-11e9-9f38-0424099c0cbd.png)

-Krishna

**Comment by andrewconnell** [comment]
@krishnavandanapu I can see the error... something doesn't seem right. Any chance you can share the contents of the **./sharepoint/solution/debug/AppManifest.xml** as that's where it's reporting the error... let's make sure its not a custom component problem...

**Comment by krishnavandanapu** [comment]
GM Andrew,
thank you for your response, here is the text in that file and renamed as .txt as we can't upload .xml file directly.

<?xml version="1.0" encoding="utf-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Type="http://schemas.microsoft.com/sharepoint/2012/app/relationships/manifest-feature" Target="/feature_547ad20b-c761-4ca8-997a-70819c9a6fe7.xml" Id="r6"></Relationship><Relationship Type="http://schemas.microsoft.com/sharepoint/2012/app/relationships/manifest-clientsideasset" Target="/ClientSideAssets.xml" Id="r7"></Relationship></Relationships>

[AppManifest.xml.txt](https://github.com/SharePoint/sp-dev-docs/files/3029625/AppManifest.xml.txt)

**Comment by andrewconnell** [comment]
You could share the *contents* of it, not just upload the file.

At any rate... that doesn't look like the **AppManifest.xml** file. You're missing a TON of stuff. That looks like the file from **./sharepoint/solution/debug/_rels/AppManifest.xml.rels**

**Comment by krishnavandanapu** [comment]
here it is..
`<?xml version="1.0" encoding="utf-8"?><App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" Name="demo-sp-fx-client-side-solution" ProductID="786ec8ee-1fab-4e87-8275-465aa10c0178" Version="1.0.0.0" SharePointMinVersion="16.0.0.0" IsClientSideSolution="true"><Properties><Title>demo-sp-fx-client-side-solution</Title></Properties></App>`

**Comment by andrewconnell** [comment]
That's more like it... you uploaded the ***.sppkg** file to the app catalog?

**Comment by krishnavandanapu** [comment]
Andrew,

I have uploaded .sppkg file in app catalog.
Here is the one I uploaded :
[demo-sp-fx.zip](https://github.com/SharePoint/sp-dev-docs/files/3030166/demo-sp-fx.zip)
-Krishna

**Comment by andrewconnell** [comment]
Are you uploading the ***.sppkg** file? That's what should be uploaded, not a ZIP file.

The SPPKG file *is* a ZIP file... that's what you should be uploading. The fact SharePoint is having trouble parsing the contents of the file would imply that either what is being uploaded is not a ***.sppkg** file or it is corrupt.

The file you attached to the last message is a ZIP of the SPPKG... I downloaded it, unpacked it, and uploaded the resulting SPPPK to a SharePoint Online site (_I don't have an SP2019 environment_)... worked just fine.

If that doesn't work for you, the only thing I can suggest is to open a support ticket with MSFT as there's not much more I can do from here. This is going to come down to how your environment is installed & configured.

**Comment by krishnavandanapu** [comment]
Andrew,

I have uploaded .sppkg not the zip file, yes I too agree that .sppkg is working seamlessly in SPO but the same is not working in SP-2019.

-Krishna

**Comment by andrewconnell** [comment]
Unfortunately, the only thing I can suggest is to open a support ticket with MSFT as there's not much more I can do from here. This is going to come down to how your environment is installed & configured.

**Comment by krishnavandanapu** [comment]
Andrew,

But, how will be able to submit a ticket with MSFT for my local environment with RTM version of SP2019.

-Krishna.

**Comment by andrewconnell** [comment]
If you have a premier support agreement with MSFT, that's your best option. Otherwise, the best I can suggest is to go to the main SharePoint page, scroll to the bottom and use the "contact us" / "get support" option: https://support.office.com/sharepoint

**Comment by Bagy88** [comment]
Hi Everyone, we get the same issue on our SP2019 OnPrem Env.
Is there some solution?

**Comment by andrewconnell** [comment]
When creating your project with the Yeoman SPFx generator, did you select the option "SharePoint Server 2019" when specifying the target environment?

Looking at the contents of the **SPPKG** file that was included above implies that the project was created for SPO by the presence of the **ClientSideAssets** folder in the package.

**Comment by krishnavandanapu** [comment]
I am recreating VM to ensure that it is not environment level issue.

**Comment by krishnavandanapu** [comment]
I see the issue at DNS for app model, but I am still not 100% sure because it is working for SharePoint add-ins

**Comment by andrewconnell** [comment]
Sorry... but unclear; those are directly related... app model = add-ins... the apps were just renamed to add-ins. Unclear how this is related to uploading an SPPKG to app catalog...

**Comment by krishnavandanapu** [comment]
Andrew, 
what I mean is, I see an issue at my DNS server level. However, my SharePoint hosted add-ins are working only SPFx add-ins are not working.
So, I am still investigating further on this behavior. I hope, I made it clear now.

**Comment by krishnavandanapu** [comment]
I have cracked the issue after I reinstall my DNS I am able deploy my SPFx webparts.
I would like to close this ticket after my final test case.
thank you all for your support and help.

**Comment by emadhejazian** [comment]
https://support.shortpoint.com/support/solutions/articles/1000273552

**Comment by SpliceVW** [comment]
@krishnavandanapu we are having a similar issue - can you elaborate what you mean by you reinstalled your DNS? As in, you blew up your domain controllers? Or it was some configuration on the SharePoint side?
