### ISSUE TITLE
ISPHttpClientBatchCreationOptions and SPHttpClientBatch has no exported member under the module "@microsoft/sp-http" in spfx v.1.7.0?

### ISSUE THREAD

**Issue by ashokswain27** [SharePoint/sp-dev-docs#3491]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> ISPHttpClientBatchCreationOptions and SPHttpClientBatch used to work on the previous verisons of Spfx (e.g. 1.4.0). Recently upgraded to v1.7.0,. got the below error: Module '"./node_modules/@microsoft/sp-http/dist/index-internal"' has no exported member 'ISPHttpClientBatchCreationOptions'.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Batch support is currently in dev preview so it won't be in the normal **@microsoft/sp-http** library. You need to create your project with the `--plusbeta` flag to use the beta packages.
