### ISSUE TITLE
Multiple different major typescript versions are used

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3493]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Use same typescript version for everything if possible.

#### Observed Behavior
An ```npm ls typescript``` shows that multiple different major version are used in SPFx.

<img width="716" alt="screenshot 2019-02-25 at 17 27 18" src="https://user-images.githubusercontent.com/5503835/53352457-16c29400-3923-11e9-8663-0e10e561f141.png">

#### Steps to Reproduce
1. Create any project using the lastest SPFx generator.
1. run ```npm ls typescript```

**Comment by andrewconnell** [comment]
Build toolchain is not just used by SharePoint, but by multiple teams (ie: rush). Not sure how I see this is a bug...

**Comment by VesaJuvonen** [comment]
Do we really have a bug here which we should be working on?

**Comment by StfBauer** [comment]
There is nothing really that needs to get triaged because all npm packages don't use the referenced typescript versions anyway. All come with their precompiled dist and lib folders.

The only thing you could argue is that typescript is referenced as dependencies instead of devDependencies.

<img width="511" alt="Screenshot 2019-03-28 at 21 35 09" src="https://user-images.githubusercontent.com/5503835/55191026-60600200-51a1-11e9-84ce-2c907626b546.png">

I did some cleanup and everything seems to work. So not critical and no need to change when it technically works.
