### ISSUE TITLE
How to format "group by" headers?

### ISSUE THREAD

**Issue by apruzzr** [SharePoint/sp-dev-docs#3495]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Is there a way to format the "group by" headers with JSON? This is an important part of being able to format a view.

#### Observed Behavior

There does not appear to be anything in this documentation for accessing the "group by" headers in JSON list view formatting. I'd like to be able to eliminate the column name, so that they just say the value. I'd also like to be able to control the text styling, or add an icon. I would also like to make grouped lists more mobile-friendly by over-riding the default styling.

**Comment by PopWarner** [comment]
Thanks for submitting your question @apruzzr. :)

Much of the styling your asking about, relating to text styling, adding an icon, mobile friendliness, etc. can be accomplished using View Formatting. You are able to define the HTML that is displayed for each list item. 

I'm not sure if you have seen them, but there is a nice collection of samples available in the List Formatting repository for both View and Column formatting that might help provide guidance on accomplishing some of what your looking for. They are located here: https://github.com/SharePoint/sp-dev-list-formatting

**Comment by VesaJuvonen** [comment]
As this is missing the documentation reference and @PopWarner replied with additional references, closing this for now as answered.

**Comment by kinsl4yer** [comment]
I think that question should be reopened, as there is no answer on that in the web.

**Comment by jogood** [comment]
I have this issue as well.

For example, it doesn't seems possible to go from this:

![image](https://user-images.githubusercontent.com/17586546/68149406-dc76b100-ff0b-11e9-91d4-5a76e8723186.png)



to the following grouped format:


![image](https://user-images.githubusercontent.com/17586546/68149480-f7e1bc00-ff0b-11e9-9796-38a64184cdc0.png)

This is the default available formating for a group by:

![image](https://user-images.githubusercontent.com/17586546/68149647-42fbcf00-ff0c-11e9-8327-dbdd8836fa75.png)
