### ISSUE TITLE
Grouped list views interfere with responsive JSON view formatting on mobile devices

### ISSUE THREAD

**Issue by apruzzr** [SharePoint/sp-dev-docs#3496]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The "group by" headers should scale, wrap, or otherwise change their styling to be responsive on a mobile device. If this can't be fixed, then JSON-formatted list items should at least display the same way, whether the view has "group by" enabled or not.

#### Observed Behavior

If you apply JSON view formatting to a view using flexbox to create a responsive layout that displays well on mobile and then enable "group by" on that view, the list items no longer lay themselves out responsively. Instead of the list items flexing to fit the screen width, they are too wide for the mobile screen, just like the "group by" headers are too wide.

#### Steps to Reproduce

1). Create a responsive JSON-formatted list view using flexbox layout. Confirm that the list items display well on your mobile device, wrapping so that they fit the horizontal limits of your mobile screen. 
(see first screenshot from mobile device, below)

2). Now, edit the view. Use "group by" to group your list by some variable.
(see second screenshot from mobile, after applying "group by", below)

3). Refresh the page on your mobile device. You will notice that you have to scroll horizontally to see the "group by" headers. If you expand one of the groups, you will also see that the list items no longer exhibit the expected responsive behavior, and are too wide for your mobile device's screen.
(third screen shot from mobile, same list item as in screenshot 1, seen after expanding the group. _The only change_ made to this view was applying a "group by" condition)

![img-0041](https://user-images.githubusercontent.com/41438055/53361564-0d76fe80-3906-11e9-8f57-cf8e1ccbc669.jpg)

![img-0042](https://user-images.githubusercontent.com/41438055/53361570-110a8580-3906-11e9-8360-286fb6c3fc05.jpg)
![img-0044](https://user-images.githubusercontent.com/41438055/53361574-14057600-3906-11e9-89da-17602054c3d6.jpg)

**Comment by shagra-ms** [comment]
@apruzzr Can you share the JSON you are using?

Recommended way to adjust the formatter for small screen devices is to use [@window.innerWidth](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#section-6) token. You can adjust the flex direction based on the window size - 

```javascript
      "flex-direction": "=if(@window.innerWidth < 800, 'column', 'row')",
```
