### ISSUE TITLE
Modern has very limited out of the box controls for content aggregation

### ISSUE THREAD

**Issue by sderix** [SharePoint/sp-dev-docs#3499]
Hi,
This is an awesome article. Problem is that IMHO when using a 'modern' environment there are hardly any out of the box aggregation webparts available. Question: What is your suggestion for content aggregation in a modern environment. As a rule of thumb I always evangelize to use out of the box over 3rd party tools over custom development. Hoping for an answer!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f742fbc-f56f-b511-de3b-0acedcfce702
* Version Independent ID: 4d3cb5e7-1482-1c5c-894e-4882856692f2
* Content: [Content aggregation guidance for SharePoint Online portals](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-data-aggregation)
* Content Source: [docs/solution-guidance/portal-data-aggregation.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-data-aggregation.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Have you tried to  use the Highlighted Content Web Part in Modern? https://support.office.com/en-us/article/use-the-highlighted-content-web-part-e34199b0-ff1a-47fb-8f4d-dbcaed329efd

**Comment by sderix** [comment]
Hi Beau,
I'm currently looking into it. When selecting a content type the filtering acts a bit weird, haven't figured it out entirely but this may work. Thnx!

**Comment by bcameron1231** [comment]
Happy to help in any way. The filtering specification can be a bit unclear.
