### ISSUE TITLE
workbench.aspx for on premise? 

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#35]
Is there or will there be a way to install workbench.aspx on 2016 developer site?

**Comment by chakkaradeep** [comment]
You cannot use the workbench.aspx as it is today on a 2016 developer site.

But yes, I believe we will ship the ASPX version for on-premises when we ship SharePoint Framework for on-premises.

**Comment by patmill** [comment]
Just to set expectations though - that won't happen until sometime next year.
