### ISSUE TITLE
Webpart not loading 

### ISSUE THREAD

**Issue by arujindal123** [SharePoint/sp-dev-docs#350]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [#] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Helloworld webpart should load on page load.

#### Observed Behavior
Getting error 
[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloWorldWebPart.g_9d4eabe5_f55d_4675_9373_1c44b7ca5f39,Error: ***Failed to component "7af95477-fc6b-412e-a4b8-24bd46566bf2" (HelloWorldWebPart). Original error: Error loading https://component-id.invalid/7af95477-fc6b-412e-a4b8-24bd46566bf2_0.0.1 script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-loader_en-us_529d543c5cdfae3136128abb7f516ada.js:60:15897) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:47:21831) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:47:22244) at https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:48:206

#### Steps to Reproduce
Create a new Webpart
Gulp Bundle --ship
Gulp package-solution --ship

Webpart is working on workbench but after package and deploying to any site getting above error. The same part of code was working till yesterday in Test tenant and issue was only till dev tenant but now it stopped working in all of our tenants(devs and test). 

Checked issue #340 as well. But is there any way we can fix error in the webparts which is there already instead creating a new fresh webpart and migrating old webparts. 

Thanks. 
![package](https://cloud.githubusercontent.com/assets/17233483/21973448/c1f39172-dbe6-11e6-904c-b75955e356e5.PNG)

**Comment by dcu-sharepoint** [comment]
@arujindal123 what kind of sever are you using. reason I ask i because I don't see a know http address. are you using your own server? what version of SharePoint are you using? my apologies if this is a dumb question.

**Comment by manishgarg1** [comment]
@arujindal123 , Are you running "gulp serve"? Can you please run gulp serve and try your scenario? My guess is that you uploaded the package without uploading your scripts to a CDN and you are not running gulp serve.

**Comment by patmill** [comment]
RC0 has rolled to all farms.  The reference to sp-client-base at 0.5.1 shows that you are still using the drop6 code.  View the release notes here - https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0
