### ISSUE TITLE
SPFX Integration in Teams: Fabric UI component colors mix with MS Team Dark Theme.

### ISSUE THREAD

**Issue by pk091990** [SharePoint/sp-dev-docs#3501]
I've integrated my custom SPFX webpart with MS Teams using SPFX 1.7.1-plusbeta version. While changing MS Team Settings to Dark theme color, office fabric UI component (ChoiceGroup) are not taking color based on the dark theme color.

![image](https://user-images.githubusercontent.com/46436213/53405382-be9c9800-39dd-11e9-9c34-f08db61851bd.png)

![image](https://user-images.githubusercontent.com/46436213/53405405-ce1be100-39dd-11e9-9a06-a396d4924b04.png)

**Comment by PooLP** [comment]
I have the same problem and Typography of certain UI fabric component is wrong (ex : Activity Item => Times new roman)

**Comment by aslanovsergey** [comment]
same here

**Comment by AJIXuMuK** [comment]
Yep - theme for SPFx doesn't take Teams theme into consideration.

**Comment by joaojmendes** [comment]
Yes, same for me, :(

**Comment by AJIXuMuK** [comment]
Are there any plans on fixing this one?

**Comment by qazqwertish** [comment]
We face the same issue. As a workaround I am defining what theme there is in Teams and do my own CSS for it (we have to maintain it ourselves until this is fixed, but at least we can have something readable for clients). Found it in this post by Alex Terentiev: [https://blog.aterentiev.com/support-microsoft-teams-themes-in](https://blog.aterentiev.com/support-microsoft-teams-themes-in). Hope it helps

**Comment by AJIXuMuK** [comment]
Hello @pk091990 - sorry for the long delay.
We've been working on theming support for web parts in Teams.
Currently the theme is applied correctly as soon as you refresh the tab (open another tab and go back to the custom one).
If you want the theme to be applied immediately, you can use SPFx 1.14 beta and override `onThemeChanged` method. It will be fired each time the theme is changed.
From there you can wrap your controls with OUIFR `ThemeProvider` and pass the theme.

Please, feel free to open a new issue if there are any problems with this approach.
