### ISSUE TITLE
SharePoint On-Premise Support for Modernizer

### ISSUE THREAD

**Issue by dodgecox-dansal** [SharePoint/sp-dev-docs#3502]
Hello, I downloaded the Modernizer in the hopes that there may be a way to make it work for SharePoint 2013 On-Premise to scan and build a report for a 2019 migration.  I see there is a plain username & password authentication option but it throws an exception when attempting to build a SharePointOnline authentication object, which makes sense because it's not SharePoint Online.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jansenbe** [comment]
Hi @dodgecox-dansal,

The scanner currently only supports scanning SharePoint Online and we should have done a better job in explaining that. We'll update the docs to clarify. 

The scanner is open source (https://github.com/SharePoint/sp-dev-modernization/tree/dev/Tools) and you potentially could build your own version that works with 2013 version of the PnP Sites core library + switch to network credentials for the auth.
