### ISSUE TITLE
@microsoft/sp-loader is not declared in manifest

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3503]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`SPComponentLoader` works correctly

#### Observed Behavior
`SPComponentLoader` usage leads to an error:
```
[SPLoaderError.loadComponentError]:
***Failed to load component "54bf2203-2546-44b4-ab33-61aee56349ff" (PageSectionsNavigationWebPart).
Original error: ***The entry point for component "54bf2203-2546-44b4-ab33-61aee56349ff" (PageSectionsNavigationWebPart) has a dependency on "@microsoft/sp-loader" that is not declared in the manifest
```
#### Steps to Reproduce
In SPFx web part (I'm using 1.7.1):

```typescript
import { SPComponentLoader } from '@microsoft/sp-loader';

protected onInit(): Promise<void> {
SPComponentLoader.loadCss(customCssUrl);
}
```

**UPDATE:** It doesn't work on Comm Site but work on Team Site

**Comment by cslecours** [comment]
Are you using the production sppkg? (gulp bundle --ship and gulp package-solution --ship).
Or the development sppkg? (without --ship). 

If it's the development sppkg, you need to call package-solution again and add the sppkg to your app catalog.

**Comment by AJIXuMuK** [comment]
@cslecours it is dev for now.
But I did `package-solution` and upload again - it doesn't help.

**Comment by cslecours** [comment]
Make sure that you do a `gulp bundle` before. Since the package dependencies that get replaced (like SP-ComponentLoader) are identified during this step.

**Comment by AJIXuMuK** [comment]
@cslecours I did both.
It really works on Team Site, not on Comm Site. So I think it is something inside still.

**Comment by VesaJuvonen** [comment]
Hi Alex,
is the issue still present in the following sample - https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-page-sections-navigation. Just for easy repro.

**Comment by AJIXuMuK** [comment]
Hi @VesaJuvonen,
Yes, it's there.
If you uncomment lines 13 and 259 in `PageSectionsNavigationWebPart.ts` you'll see the error in console.
Just to clarify:
1. I've tried release build (`gulp bundle --ship` and `gulp package-solution --ship`)
2. I've tried debug build (`gulp bundle` and `gulp package-solution`)
3. It works on Team site but not on Comm site.

Let me know if you need some additional details.

**Comment by VesaJuvonen** [comment]
Thanks for confirming @AJIXuMuK, we'll investigate this now actively.

**Comment by johnguy0** [comment]
@AJIXuMuK Looking at the `package.json` in the sample linked above, I don't see a reference to `@microsoft/sp-loader`. This would mean its being picked up as an implicit dependency, which for SPFx libraries will have unintended side effects. Can you make the dependency explicit and try again on a Comm Site?

**Comment by AJIXuMuK** [comment]
Thank you @johnguy0 for pointing that!
Yes, implicit dependency fixes the issue.

But I would say that the documentation should be changed.
First, of all, there is no any reference that a separate module should be referenced.
Second, [Connect to SharePoint using JSOM](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom) page still says that the loader is in `sp-application-base` module that is referenced and loaded to the page by default.

**Comment by AJIXuMuK** [comment]
[Documentation PR](https://github.com/SharePoint/sp-dev-docs/pull/5254)

**Comment by johnguy0** [comment]
@AJIXuMuK Agreed on the docs change. Thank you for submitting a PR to fix it!

**Comment by AJIXuMuK** [comment]
Resolved: projects should have implicit dependency on `@microsoft/sp-loader`
