### ISSUE TITLE
Please change the JSON parser to use JSON with comments

### ISSUE THREAD

**Issue by ericleigh007** [SharePoint/sp-dev-docs#3505]
This would allow designers to include some context information in the JSON that would be helpful to troubleshooting and maintenance.
I tried 
//
and 
/*  comment  */  
And was rewarded with "Please enter valid column-formatting JSON."
-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi @ericleigh007, thanks for the comment and enhancement request. Understandably, I can see your concern with wanting to include comments. It should be noted that native JSON doesn't support comments.

In the mean time, you may be able to get by, by loading comments into the JSON object itself. Take for example.... the use of //comment as a property on the JSON object above the command I want to comment.
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "debugMode": true,
  "elmType": "div",
  "children": [
    {
      "elmType": "div",
      "style": {
        "//comment":"Make it red because x,y,z",
        "background-color": "red"
      },
      "txtContent": "@currentField"
    }
  ]
}
```

While not ideal, this should produce valid JSON for you and may work for your current needs.

**Comment by ericleigh007** [comment]
This is helpful.

But please don’t let this suggestion stop here.  Users will appreciate the ability to explain the files for maintainability and documentation.

I’ve seen more and more implementations using JSON5 (I guess), and people call it “ JSON with comments” (which might be a subset of JSON5, I guess).  Azure config files, and the like, now all support comments (with all due respect to the original standard, and the utopian principles that drove the original creators to the madness of not including them)

At any point that any construct might require more than a few lines of data, that construct requires the ability to add comments.  With the wonderfully flexible and complex and sometimes confusing syntax of SharePoint view and column formatting files, it makes GREAT sense to use the latter libraries and let devs put a few notes in these files.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by StfBauer** [comment]
JSON5, as you mentioned, is an open source project on [Github](https://github.com/json5/json5) and there are other tools like this out there too. The problem is that those are not supported in the JSON standard. Their implementation varies depending on which 3rd party library you use.

You can potentially include and use this in your solution for your JSON files that include comments.

The JSON format which is defined in the [ECMA Standard 404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) is a pure data interchange format. It should only contain data only and is not intended to be human readable, but machine-readable.

Especially any compiler or programming language from TypeScript, C#, BabelJS, JavaScript, and so on will fail to read the data when comments like you mentioned, are included.

@bcameron1231 method to integrate comments is one that does not invalidate the JSON file. There are many methods to include comments, in a JSON, if really needed, that keep the data structure intact.

**Comment by ericleigh007** [comment]
Let's see what the rest of the users say.  This is also an entry in user voice, so perhaps it will get more votes, perhaps not. And that is the way it is supposed to work... Thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ericleigh007** [comment]
My last word on the subject from the man who brought us JSON:

https://groups.yahoo.com/neo/groups/json/conversations/topics/152

Douglas Crockford
Message 1 of 42 , Dec 24, 2005
View Source
JSON does not have comments. A JSON encoder MUST NOT output comments.
A JSON decoder MAY accept and ignore comments.

Comments should never be used to transmit anything meaningful. That is
what JSON is for.

As humans are now reading and writing JSON, it needs comments because our brains are much less structured than computers.  We need to remember what we did months ago, and sometimes … just yesterday.

Have a great week, guys.  Thanks for all the input.

-e

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andrewconnell** [comment]
Good discussion... this falls into the category of a feature request / change and thus belongs on User Voice with the others so please feel free to submit it there: https://aka.ms/sp-dev-uservoice
