### ISSUE TITLE
Is there an authoritative source of supported versions?

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-docs#3507]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

## Observed Behavior

I noticed that there are a lot of issues in this list and questions on stackexchange that relate to what is supported in what versions of SPFx.

Is there an authoritative list of supported versions somewhere that lists what versions of what libraries are supported with each version of SPFx?

For example:

---
## SPFx 1.7.1 

Released: December 18, 2018

### Supported libraries

|Library|Min|Max|
|---|---|---|
|Node|vXX|vXX|
|NPM|vXX|vXX|
|React|vXX|vXX|
|TypeScript|vXX|
|...|...|...|

### SharePoint Support
|SharePoint Version|Supported?|Notes|
|---|---|---|
|SharePoint Online| x | |
|SharePoint 2019 On-Premise| x | |
|SharePoint 2016 On-Premise| x | |
|SharePoint 2013 On-Premise| - | |

### Feature Support
- Dynamic Data 
- SPFx for Teams Tabs
- Teams-based Apps in SharePoint
- ...
---

If there isn't something official, I'd be happy to put something together, but I'll definitely need volunteers to help me.

As always, thanks in advance for your help!

**Comment by andrewconnell** [comment]
Not really... not beyond reading the release notes of each version. It's something I'm working on and should have something to share within a few weeks though...
