### ISSUE TITLE
SharePoint Online Provisioning Service

### ISSUE THREAD

**Issue by nicholas-morris** [SharePoint/sp-dev-docs#3509]
How can I sign up to be a Beta tester of SharePoint Online Provisioning Service templates?

**Comment by VesaJuvonen** [comment]
This service is currently open for anyone to use in any tenant. Thanks for your feedback advance. The situation was indeed different back when you asked this question.

**Comment by SathishNadarajan** [comment]
I was trying to create a Site using SharePoint Starter Kit template.  But got the below exception.

Here is the exception that occurred:
Type = System.Threading.Tasks.TaskCanceledException Message = A task was canceled. Source = mscorlib Task = System.Threading.Tasks.Task`1[System.Net.Http.HttpResponseMessage] CancellationToken = System.Threading.CancellationToken TargetSite = Void ThrowForNonSuccess(System.Threading.Tasks.Task) StackTrace = at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__42.MoveNext() in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\ALM\AppManager.cs:line 786 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\ALM\AppManager.cs:line 350 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata, Boolean skipFeatureDeployment, AppCatalogScope scope) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\ALM\AppManager.cs:line 323 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector, TokenParser parser, PnPMonitoredScope scope, ProvisioningTemplateApplyingInformation applyingInformation, ProvisioningMessagesDelegate messagesDelegate) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\Utilities\TenantHelper.cs:line 140 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchyTenant.cs:line 29 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 207 at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line 42 at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 360 HResult = -2146233029

PnP Correlation ID: abac940d-f597-41a7-a059-66ed9cc2503e
