### ISSUE TITLE
Programmatically update WebPart properties

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#351]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Is it possible to update a webpart property trough code in SPFx?

#### Observed Behavior
To update webpart properties the edit properties pane should be used. However, when for example implementing a "dragable tiles" component, the configuration of such component should be saved in the properties without doing this through the toolpane - but directly in the webpart itself (with a check on page state, ...)

Is there a method we can use to update webpart properties without using the tool pane? So for example JSON/XML string can be saved there.

**Comment by waldekmastykarz** [comment]
You should be able to update the value by directly assigning the value to the particular property, eg:

```ts
this.properties.myProp = "newValue";
```

The only challenge with this approach is that on classic pages it works only when the page is in edit mode and the web part is being edited.

**Comment by NickSevens** [comment]
Thanks @waldekmastykarz. I'll try it this way.
Ultimate goal would be to have either an in-place configuration of the webpart, or a modal popup from the toolpane - something like the CSWP editor.

**Comment by manishgarg1** [comment]
Yes. You should be able to control the values in the this.properties object. As far as you keep the properties updated, we will serialize them and they will get saved to the database.

**Comment by dcu-sharepoint** [comment]
@NickSevens love your bbq

**Comment by NickSevens** [comment]
@waldekmastykarz @manishgarg1 setting the property value work indeed.
Having all these read-only properties in context etc made me forget about the easiest of options :)
