### ISSUE TITLE
multi language site use CSOM API get list title issue

### ISSUE THREAD

**Issue by LeoJiang1988** [SharePoint/sp-dev-docs#3510]
If site language select multi language, use CSOM API get list title will return the title by current user's default display language setting.

For example:
current user's default display language is English, but site default language is French, use API get the Documents list title will still return Documents.

**Comment by nikolayyordanov** [comment]
This is by design - this depends on the preferred language in the user profile.

**Comment by VesaJuvonen** [comment]
This is indeed by design.
