### ISSUE TITLE
Person column properties - column formatting

### ISSUE THREAD

**Issue by hbliznakov21** [SharePoint/sp-dev-docs#3515]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Person column properties - column formatting**

Hi, 

I am trying to find all properties that are supported for the person column in SharePoint online.
Here is the example I found in the docs.microsoft.com

{
   "id": "122",
   "title": "Kalya Tucker",
   "email": "kaylat@contoso.com",
   "sip": "kaylat@contoso.com",
   "picture": "https://contoso.sharepoint.com/kaylat_contoso_com_MThumb.jpg?t=63576928822"
}

I found also the the "department" is available and I was wondering what else we can get from the user profile.

Thank you!

**Comment by thechriskent** [comment]
Those are the only values available for use in column formatting. There are other values, however, available from person fields when retrieving them through other means, such as the REST API. Is that what you are referring to?

Some of those additional properties include:

- MobileNumber
- AboutMe
- IsSiteAdmin
- Deleted
- Hidden
- Department
- JobTitle
- LastName
- FirstName

Again, the above are **not** available for column formatting.

**Comment by hbliznakov21** [comment]
Hi Chris, Thank you for your quick answer. Yes, I know that it is possible to retrieve more user data using REST API. I am sending screen shouts of the department propriety I can use in the column formatting, which was surprise for me and my profile in Azure. 
![2019-03-01_13-07-26](https://user-images.githubusercontent.com/48096973/53637526-aae27300-3c23-11e9-885b-411040b7c249.jpg)
![2019-03-01_13-10-51](https://user-images.githubusercontent.com/48096973/53637527-aae27300-3c23-11e9-9a85-6b8c77b1175c.jpg)

That's way I send a question to the community to see if there is additional options I am not aware off. 
Thank you!

**Comment by thechriskent** [comment]
Wow, you're blowing my mind! I'm not able to recreate this yet but I'm looking into it further and will see what I can find out.

**Comment by bcameron1231** [comment]
Here is the list of properties available
- id
- title
- email
- sip
- picture
- jobTitle
- department

**Comment by hbliznakov21** [comment]
@bcameron1231  Perfect! Thanks!

**Comment by thechriskent** [comment]
Thanks @bcameron1231 and @hbliznakov21!

Looks like we need to update the documentation! Guess that will teach me to **not** put the word not in bold in my responses 😄!
