### ISSUE TITLE
Picture Library - Display as List instead of Tiles

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3518]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I'm currently working with Picture Library list and want to display it as List instead of Tiles.
I can select *List* option in the dropdown but as soon as I refresh the page I see Tiles again.
Literally a week ago the selection was stored (probably in session or something) after page refresh.

I would love to have an option to stick with selected view type.

**Comment by AJIXuMuK** [comment]
Same for Promoted Links list type.

**Comment by VesaJuvonen** [comment]
As this is not really a developer issue, closing it. It's more an enhancement request for oob capability. We can't, unfortunately, triage or bypass these to feature owners using this channel.

**Comment by AJIXuMuK** [comment]
@VesaJuvonen I wouldn't say that it's a feature request as it has been working before.
So it's a bug. Or some decision to change ootb behavior that was not announced.
I'd love to post this one somewhere else if you point me where (I don't think uservoice is correct for that as I'm assuming it's a bug).
