### ISSUE TITLE
background-image

### ISSUE THREAD

**Issue by apruzzr** [SharePoint/sp-dev-docs#3522]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

What is the correct syntax for the "background-image" property? I had thought:

"background-image": "url(http://path/image.jpg)"

also tried:

"background-image": "url('http://path/image.jpg')"

#### Observed Behavior

Neither of the above works. Since "background-image" is listed as supported, what is the correct syntax?

#### Steps to Reproduce

Apply either of the above to the style property of any div element.

**Comment by bcameron1231** [comment]
Can you provide a bit more context on where and how you are trying to apply this? Are you trying to do this in column formatting?

**Comment by zypA13510** [comment]
If you meant column formatting, this is being discussed in #1161.

**Comment by VesaJuvonen** [comment]
Closing due no response on the request of more information.
