### ISSUE TITLE
can not open the JSON file attached to the list

### ISSUE THREAD

**Issue by tanimaru** [SharePoint/sp-dev-docs#3523]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I can download it like any other file.

#### Observed Behavior

Please see the attached file
![error](https://user-images.githubusercontent.com/35947522/53611458-00ae1f80-3c12-11e9-998e-fb082ec0fa15.PNG)

#### Steps to Reproduce

1.Create a list and attach a file with extension .json to it.
2.Open the attached file.

However, I can open it by changing the extension to. ".txt"

**Comment by narulasrinivas** [comment]
Even I was having same issue. But the docs refers that there is no file type restriction in files. Please find below link.

[https://support.office.com/en-us/article/types-of-files-that-cannot-be-added-to-a-list-or-library-30be234d-e551-4c2a-8de8-f8546ffbf5b3#ID0EAABAAA=Online](url)

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we cannot triage or support this through this channel. Notice that file type opening is dependent on the OS level mapping of the extension. Closing this as non-dev issue.
