### ISSUE TITLE
ListViewComandSet Extension not showing commands

### ISSUE THREAD

**Issue by Lagarto66** [SharePoint/sp-dev-docs#3525]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I've been developing an Spfx extension. Last week it stopped working. It is not showing custom command any more.
It's weird as I have started a new blank extension and it's not showing the custom command also.

#### Observed Behavior

I've noticed these errors in Chrome 

![greenshot 2019-03-01 15 41 44](https://user-images.githubusercontent.com/2470462/53648788-a7a5b200-3c38-11e9-9756-1c0baa9a0143.png)

I'm not sure if they are related. I've just not seen them before.

**Comment by bcameron1231** [comment]
Can you  provide a bit more information, and possibly source code? The errors you posted, I believe are unrelated to your command set not loading. I have a command set running find in my list, with those errors.

It would be helpful if you could provide a bit more context, such as the the list type & definition, and possible source code so we can try and reproduce.

Thank you.

**Comment by Lagarto66** [comment]
Regarding the source code, it is a new project created using yeoman generator. Spfx version 1.7.1
Here is a serve.json

<img width="521" alt="extensionservejson" src="https://user-images.githubusercontent.com/2470462/53731717-8c72b680-3e73-11e9-9940-3d283aba5372.png">

and here is an expected result after running gulp serve

<img width="485" alt="extensionlistview" src="https://user-images.githubusercontent.com/2470462/53731750-9e545980-3e73-11e9-99e8-7f404300e0bc.png">

The command button is missing. Am I doing something wrong?

**Comment by bcameron1231** [comment]
Any chance you could send the full code? I created a command set from a 1.7 and It is appearing for me. It may be something to do with some of your code.

**Comment by Lagarto66** [comment]
I have not changed anything except pageUrl parameter in the serve.json file

**Comment by bcameron1231** [comment]
Okay great.  Is it happening in every browser? I have just tested in Chrome, FF and Edge. It appears there may be some messages in the console of FF and Edge. Can you confirm?

**Comment by Lagarto66** [comment]
It looks like it's working when the extension is deployed and installed in the SP Online,
but when I'm trying to debug it via gulp serve it's not working. I have double checked everything, I run gulp trust-dev-cert, etc.  Any idea why? It's bizarre.

**Comment by ydescortes** [comment]
I have same issue and also when extension is deployed. Spamming F5 seems to show commands.

When extension is deployed, i have a button with the title of customAction and it does nothing on click

**Comment by bcameron1231** [comment]
@Lagarto66 Is this happening in all browsers?
