### ISSUE TITLE
without "gulp bundle --ship"

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#3527]
without "gulp bundle --ship", "gulp package-solution --ship" is not going to work
Peter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page#feedback)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the note. If you look closely within the document you posted inside the "Package contents" section, you can read about what the --ship does. It is not meant to be used for that tutorial.

> The JavaScript files, CSS, and other assets are packaged inside of the package when the --ship option is used. In this tutorial, however, we will first test deployment and capabilities by hosting JavaScript files from localhost. Automated packaging and hosting option is explained in the next tutorial.

**Comment by peterremote1980** [comment]
thanks
