### ISSUE TITLE
SPFx extension list Command Set cannot read selected row value like "ID"

### ISSUE THREAD

**Issue by harrychen1** [SharePoint/sp-dev-docs#3528]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
>Try to use SPFx extension list Command Set to hide or show command depends on the list field value. Show the command only when one field value equals something. Example to simplify is to display command only when ID equals '1'.

Add the code in onListViewUpdated to check the field value but error out. It will not render the command. 

const itemID = event.selectedRows[0].getValueByName("ID"); // This line error out

Error is:
Failed to loadCommandSet, id: a70c2b01-b238-456e-95ae-5f1681b22e6c, error: TypeError: Cannot read property 'getValueByName' of undefined
>

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> We would expect to get the field value inside the onListViewUpdated function.

const itemID = event.selectedRows[0].getValueByName("ID"); // This line error out
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> The current behavior is have error and command will not be rendered.
Failed to loadCommandSet, id: a70c2b01-b238-456e-95ae-5f1681b22e6c, error: TypeError: Cannot read property 'getValueByName' of undefined
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> Create SPFx command set project based on instruction here.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

Add one line to the onListViewUpdated function like below.
@override
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
    **const itemID = event.selectedRows[0].getValueByName("ID"); // This line error out**
    // Intention is to hid the 
    if (compareOneCommand) {
      // This command should be hidden unless exactly one row is selected.
      compareOneCommand.visible = event.selectedRows.length === 1;
    }
  }

Command will not show and error is:
Failed to loadCommandSet, id: a70c2b01-b238-456e-95ae-5f1681b22e6c, error: TypeError: Cannot read property 'getValueByName' of undefined
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>

>

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Thank you. Not quite a bug, but more so an issue with your code.

This code is executing in the onListViewUpdated(). This function is called every time a change happens in the list view and has to be re-rendered. This means your code executing even when the command button is not being set.

I suggest placing that code into the onExecute() function, as outlined in the document.  Move this code....

`const itemID = event.selectedRows[0].getValueByName("ID");`

inside the execute

```
@override
  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
        let itemID = event.selectedRows[0].getValueByName("ID");
        break;
      case 'COMMAND_2':
        Dialog.alert(`${this.properties.sampleTextTwo}`);
        break;
      default:
        throw new Error('Unknown command');
    }
  }
```

**Comment by harrychen1** [comment]
I understood the code will work inside onExecute. ### **However, the purpose of the customization is to show or hide the custom command only IF one field value equals to certain value**.  One example is bellow.

If the value of "Status" is "Completed", the show the command like "Archive".

There is no point to check the value inside onExecute function since it too late and the command will already be displayed.

Thanks.

**Comment by bcameron1231** [comment]
Thank you for providing some more information. It was unclear this was your intent from your original description. You need to place your code inside of an If statement.

As mentioned previously, your code is executing even when items aren't selected. So first,check to make sure an item is selected, then try and access the selected row.

```
@override
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
    if (compareOneCommand) {
      // This command should be hidden unless exactly one row is selected.
      compareOneCommand.visible = false;
      if(event.selectedRows.length === 1){
        let status = event.selectedRows[0].getValueByName('Status')
        compareOneCommand.visible = status === "Complete" ? true : false;
      }
      
    }
  }
```

**Comment by harrychen1** [comment]
After using your condition code, it's working as expected!

This is not a bug and we just need to write the code in the right order.

Thanks.
