### ISSUE TITLE
custom client web part(SPFx -sppkg) not appearing in webpart gallery list

### ISSUE THREAD

**Issue by vbartari** [SharePoint/sp-dev-docs#353]
#### Category
- [# ]  Bug
#### Expected or Desired Behavior
Helloword web-part should display on webpart gallery to add in to the SharePoint page

#### Observed Behavior
After deploying the SPFx webpart in to the app-catalog ,the web-part is not coming in webpart gallery.
Previously it was working but after drop RC0 it is not working for my tenant.
ideally webpart should be there in webpart gallery "under  Development" as configure in webpart.manifest:

**"groupId": "fd11922f-5da7-4fba-8828-962969da5295",
    "group": { "default": "Under Development" },**

#### Steps to Reproduce
--Create a new webpart using  "yo @microsoft/sharepoint".
-Gulp serve--> working fine.
-after that try to deploy on your dev site like below:
-Change CDN path with you :
"cdnBasePath": "your sharepointsite/SiteAssets/test/"
-gulp bundle --ship
-gulp package-solution --ship
-Upload contents of "temp\deploy" to CDN site path
- deploy on AppCatalog
-Add app in your site
-Create a sharepoint page and add webpart
**Here i'm not getting my App-part group with name"Under Development" OR "Custom"**

Let me know how can i see my webpart?

**Comment by manishgarg1** [comment]
Hi @vbartari , Is the web part visible on a modern page toolbox? Are you on a dev tenant or a tenant where first release is enabled (not for specific users, but for everyone) ?

**Comment by juanmlarios** [comment]
@vbartari  how do you know if you are in the tenant where first release has been enabled?

**Comment by vbartari** [comment]
@manishgarg1 and @juanmlarios , Yes first release is enable for my tenant as "first release for ALL".
And as i said in my post i was working on SPFx webpart but after RC0 drop i'm not able to see my old webpart it's giving error and the new  webpart is not coming in webpart selection

**Comment by vbartari** [comment]
Everything is working fine except showing webpart in webpart gallery so please suggest me regarding that only. why webpart is not in inside"Under Development"Or "Custom" after RC0 drop

**Comment by patmill** [comment]
Hi @vbartari - looks like we found an issue I think.  I had this working last week on a test tenant (on RC0), but something seems to have caused it to stop working.  We'll update this issue when we track what is happening.

**Comment by vbartari** [comment]
Hi @patmill - Yes please update us about the new changes which we need to configure for our SPFx webpart to show in webpart gallery.
also I want to inform you that, one of my colleague's are able to see  RC0 SPFx webpart inside"Under Development"  for one sitecollection in her tenant and same are not coming in different site collection within the same tenant also not in root level site. 
This is very different situation where we are not able to understand why it's not coming for all site collection in same tenant and also it's not working for other's tenant except that colleague :(

**Comment by dcu-sharepoint** [comment]
@vbartari
Question about the CDN path:
"cdnBasePath": "your sharepointsite/SiteAssets/test/"

1. I assume this is the entry on the **write-manifest.jso** file in the config folder.
2. does the **SiteAssets/test** folder have to exist before the deployment?

Thanks

**Comment by vbartari** [comment]
@dcu-sharepoint : Yes the  SiteAssets/test folder have to exist before the deployment.
steps to follow are:
1. Run command **"Gulp bundle --ship"** --It will create package inside Temp--deploy.
  upload that packages to your "your sharepointsite/SiteAssets/test/" 
2. Run command :**gulp package-solution --ship** 
it will create app package inside  sharepoint folder 
: Upload that "sppkg" in to your appcatalog and deploy
3. Go to your site collection add the app which you have created and now you should be able to add youe webpart from webpart gallery.
**:In my case webpart are not coming after RC0 drop.**

**Comment by WhereCodeGoesToDie** [comment]
I have experienced the same issue. In the same tenancy the web part can be added at a Modern Page after adding the app in one Site Collection and in another Site Collection it does not appear at all. Both Site Collections were created one after another, both have a developer site as the root site and FR is turned on. The web part does however appear in the Layouts version of the workbench in each as I would expect.
I cannot add to a classic SharePoint page in either Site Collection.

**Comment by dcu-sharepoint** [comment]
thanks vBartari....


________________________________

**Comment by vbartari** [comment]
Hi All @juanmlarios @patmill @dcu-sharepoint ,

Now my tenant and test updated with latest changes related to the RC0 and i'm able to see my Client webpart in all the pages classic as well as in modern.

**Comment by manishgarg1** [comment]
I am assuming this issue is not resolved. Hence closing. Please reactivate if it continues to be an issue.

**Comment by dcu-sharepoint** [comment]
same here! now staring to add code to the webpart to read data from a list. and now the fun begins.


________________________________

**Comment by honb** [comment]
Is this issue fixed? 
I'm using SPFx v1.0 but still get this error. Do you have any ideas?

**Comment by marcdepelteau** [comment]
I believe I am having the same issue. 

I had no problem uploading and deploying an app all week, but today I went through all the steps about 3 times and nothing happens after the sppkg is uploaded to the App Catalog. I am not asked to Deploy anything and the ''deploy'' column still shows ''No''. 

I also don't see the application anywhere when I try to ''Add App'' or browse installed Web-Parts on my Communication Site. 

Any ideas what could be wrong?

**Comment by mcmynn83** [comment]
@marcdepelteau  - Is the app valid?  Please include the error messages in the view and see that there are no error messages.  If there are no error messages and you are still not able to deploy it could you send the package to grahamc at Microsoft.com and I can take a look at it.

Thanks,
Graham

**Comment by marcdepelteau** [comment]
@mcmynn83 Hi Graham, 

When I look at the app in the list, it is listed as valid, but not deployed. I sent you an email with screenshots and the package as well. Thanks for taking the time to look into this.

**Comment by mcmynn83** [comment]
Issue has been resolved.  Just needed to deploy the app which is can be done via the ribbon if it is not done at initial upload time (the dialog will launch after upload completes so if you navigate away or stop the browser it may not show up).

**Comment by mhijazi** [comment]
Whenever I try to add the app it says "Sorry, something went wrong".

I'm stuck here:

--Create a new webpart using "yo ".
-Gulp serve--> working fine.
-after that try to deploy on your dev site like below:
-Change CDN path with you :
"cdnBasePath": "your sharepointsite/SiteAssets/test/"
-gulp bundle --ship
-gulp package-solution --ship
-Upload contents of "temp\deploy" to CDN site path

   -deploy on AppCatalog
  -**Add app in your site** I cannot add it says Something went wrong but all above went fine

Any Ideas???

**Comment by JeanBarros** [comment]
"Features like JavaScript and CSS are available on the local computer, so rendering web parts will fail unless your local host is running". Open <your-webpart-guid> .manifest.json from \ dist folder.

"internalModuleBaseUrls": [
  "https://`your-local-machine-name`:4321/"
]

Execute local server: gulp serve --nobrowser So try add webpart again.

https://docs.microsoft.com/pt-br/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page
