### ISSUE TITLE
Prevent feature from being activated by default

### ISSUE THREAD

**Issue by PzYon** [SharePoint/sp-dev-docs#3531]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Question:**
Is it possible to prevent features defined in `package-solution.json` from being activated automatically as soon as the app is added to a site collection?

**Background:**
In `package-solution.json` I specify multiple features. One of them deploys a page to sitepages. This shouldn't be done automatically, as it is not required on every site collection. That's why I would like to "force" users to activate the feature manually, if they need this page. The other option would be to create an extra app for this, but for me this seems like an overkill.

**Comment by VesaJuvonen** [comment]
Activating the feature automatically is by design. If you don't want the feature to get activated, you don't have to install the sppkg file to the site.

**Comment by PzYon** [comment]
@VesaJuvonen: Thanks for your reply. If it's by design, then that's just the way it is. But from my point of view it would make sense to have this configurable. 

Sure, you're saying "If you don't want the feature to get activated, you don't have to install the sppkg file to the site.". But that means that every piece of functionality (e.g. as in my case the deployment of an aspx page) would need to be packaged in to an own app in order to make the user/admin be able decide whether she wants it or not. And that just seems like too much.
