### ISSUE TITLE
Azure Function Error

### ISSUE THREAD

**Issue by MohamedRaihane** [SharePoint/sp-dev-docs#3535]
Hi,
i was following the tutorial Calling the PnP provisioning engine from a site script ( https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning ) 

The Azure Function produce an error while proceeding.
The PnP Powershell function are not recognised and i have the following error : 

> 2019-03-02T21:00:39.838 [Error] Connect-PnPOnline : The term 'Connect-PnPOnline' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> at run.ps1: line 3
> 

I uploaded the powershell files following the instruction at the section "Upload the PnP PowerShell module for your Azure Function"

Anny help ?^^
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

**Comment by MohamedRaihane** [comment]
Hi,
I resolved the first bug following this guideline https://stackoverflow.com/questions/37724769/how-to-install-a-powershell-module-in-an-azure-function/39985646#39985646

But now i have another Error 


While executing i have an error message telling that i do not have enough privilege to perform the provision : 

Apply-PnPProvisioningTemplate
+ _____________________________
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
2019-03-02T21:56:46.255 [Error] Exception while executing function: Functions.ApplyPnPProvisioningTemplate. Microsoft.Azure.WebJobs.Script: PowerShell script error. Microsoft.SharePoint.Client.Runtime: Access denied. You do not have permission to perform this action or access this resource.
2019-03-02T21:56:46.615 [Error] Function completed (Failure, Id=d2f5cade-3d39-4176-b571-1dfc29924086, Duration=15289ms)

**Comment by bcameron1231** [comment]
Looks like you don't have permission to execute the PnP Template from the Azure Function. Did you configure the app permissions correctly?

I would confirm you gave the app tenant permissions and also confirm the client id and client secret are correct when the script is running.
