### ISSUE TITLE
List view formatting doesnt support office ui fabric theme ?

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3536]
I am not sure , if this issue is raised . But I can see that theme is not working in office ui fabric
Here is the sample on list view page : 
![image](https://user-images.githubusercontent.com/11780473/53699353-c4341c80-3de7-11e9-974a-0b4b11d24039.png)
Here is the sample on modern page
![image](https://user-images.githubusercontent.com/11780473/53699380-f180ca80-3de7-11e9-8492-a443c04f2373.png)

Is this an ongoing issue?
Will this be fixed?
Any alternatives to resolve this

**Comment by bcameron1231** [comment]
Possible duplicate #2340

**Comment by shagra-ms** [comment]
The issue is fixed. Please let me know if you are still facing this.

@bcameron1231 @harshdamaniahd
