### ISSUE TITLE
List View Formatting breaks due to .ms-List-cell css on modern page

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#3537]
When you add formatting to list items to appear side by side , it works in list view page
![image](https://user-images.githubusercontent.com/11780473/53699469-d2cf0380-3de8-11e9-8a19-ba406d9caeff.png)
 but when we see it in modern page it appears as below
![image](https://user-images.githubusercontent.com/11780473/53699482-fc882a80-3de8-11e9-8e0f-c74e824292ad.png)

The problem here .ms-List-cell minheight css, if we change this it works
![image](https://user-images.githubusercontent.com/11780473/53699510-44a74d00-3de9-11e9-9470-0a87f12ef51d.png)

**Comment by sanjitlpatel** [comment]
I've posted about the same issue in the SharePoint Forum
https://techcommunity.microsoft.com/t5/user/viewprofilepage/user-id/295230

**Comment by martinpyman** [comment]
The references you have posted above do not actually go to anything about the .ms-List-cell issue - can you update your links?

This is a real pain - is there a way of updating the .ms-List-cell inside the List View Formatter, the only other solution I could see is creating an SPFx Solution to patch it which seems overkill

**Comment by sanjitlpatel** [comment]
The links I posted were for your reference.  If the issue with RowIndex gets fixed first, you can use absolute positioning to circumvent the staggered layout created by the min-height setting for .ms-List-cell.

**Comment by martinpyman** [comment]
Now I understand, thanks for clarifying!

**Comment by KevinTCoughlin** [comment]
It seems like this fix can be made on the host application itself, see https://github.com/OfficeDev/office-ui-fabric-react/pull/8672#issuecomment-482741282.

**Comment by ykuijs** [comment]
I am experiencing this issue as well, but the  PR is unfortunately closed due to inactivity. Is there any update on the progress of this issue?

**Comment by svaibhav** [comment]
@ykuijs  We are trying to fix this issue in the host application itself as making changes to Fabric in this case might regress some of the use cases.

**Comment by PrasadKasireddy** [comment]
This issue is started appearing now - refer the latest issues https://github.com/SharePoint/sp-dev-list-formatting/issues/204

**Comment by VesaJuvonen** [comment]
@PrasadKasireddy - any change we could get the repro steps as we would really need to understand the list configuration and how the JSON definition looks, so to be able to help with any specific details. That's the only way to really get the issue resolution forward:

* What's the list configuration - what kind of columns?
* How does the JSON look for the configuration?

Thanks for the additional details advance.

**Comment by VesaJuvonen** [comment]
Our baselines tests are fine for this scenario, so we definitely need the specific JSON configurations to be able to reproduce the issue. Thx.

**Comment by svaibhav** [comment]
@PrasadKasireddy  Just to confirm, this issue is happening when the list are used as a webpart on the SP homepage and not on the list page.
Am also assuming that you are rowFormatter property in the JSON setting "class" as "sp-row-card".

**Comment by PrasadKasireddy** [comment]
@harshdamaniahd - as discussed yesterday, could you please share the details to Vesa

**Comment by harshdamaniahd** [comment]
Thanks, everyone for quick update, but I checked in 3-4  sites and the issue has been gone. Also, I checked in various formatting used across SharePoint sites, and everything looks good

**Comment by Oos12** [comment]
Issue is back again

**Comment by asifahmeds** [comment]
Yes. Issue is back again

**Comment by binaryjam** [comment]
Hi I have this problem again,   on a news page it is doing this on a list view page it is not.

.root-226 .ms-List-cell {
    min-height: 38px;

This min-height setting seems to be the thing that is different between the page types.

This should be enough of my formatter,  the list has a Title and a Number for the happiness field.

{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "button",
    "customRowAction": {
      "action": "editProps"
    },
    "style": {
      "float": "left",
      "display": "flex",
      "flex-wrap": "wrap",
      "flex-direction": "column",
      "align-items": "center",
      "justify-content": "space-around",
      "min-width": "145px",
      "border-radius": "8px",
      "margin-right": "10px",
      "margin-bottom": "10px",
      "box-shadow": "2px 2px 4px #658ba0",
      "background-color": "white",
      "border-color": "#29527a",
      "border-width": "1px"
    },
    "children": [
      {
        "elmType": "div",
        "attributes": {
          "class": "sp-row-title"
        },
        "txtContent": "[$Title]"
      },
      {
        "elmType": "img",
        "style": {
          "height": "30px",
          "padding-bottom": "13px"
        },
        "attributes": {
          "src": {
            "operator": "+",
            "operands": [
              "/sites/BinaryJam/SiteAssets/images/moodIcons/",
              "[$Happiness]",
              ".png"
            ]
          }
        }
      }
    ]
  }
}

**Comment by wwcoop** [comment]
I am seeing the same issue. The CSS reference is causing the formatted content to stair step down the page.
`https://imgur.com/a/pIWOnTS`
I started seeing this behavior ~ a month ago in my site. As noted above, the formatted content looks fine in the list view, but no in the list web part being used on the home page.
The 38px reference is what causes this:
`.root-162 .ms-List-cell {
    min-height: 38px;
    word-break: break-word;
}`

**Comment by svaibhav** [comment]
@wwcoop The fix for this issue is already in the deployment pipeline and will reach production soon.

**Comment by shagra-ms** [comment]
The fix is now available in production tenants.
