### ISSUE TITLE
spfx webparts no longer selectable after adding extension

### ISSUE THREAD

**Issue by daenur76** [SharePoint/sp-dev-docs#3538]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have an spfx solution that contains three webparts. All are selectable in pages and works fine. 

Today I added an extension to the solution and redeployed it to sharepoint online. Now I can see that the extension runs, but my web parts are no longer available in the webparts gallery. No errors are thrown and the deploy was successful with no indications of error as well.

I've searched everywhere with no success. Have anyone experienced this and can point me in the right direction?

Thanks!

**Comment by patmill** [comment]
Did you switch anything in the configuration, like disabling tenant wide deployment?

**Comment by daenur76** [comment]
I just tried to remove and then readd the entire solution instead of just updating it. And now it works. Seems like SharePoint can't really handle major changes in the solution when updating.
