### ISSUE TITLE
Update Item SPHttpClient not working, Bad Request Error

### ISSUE THREAD

**Issue by leodak** [SharePoint/sp-dev-docs#3539]
private updateItem(bodyData: string, itemId: number, listName: string): Promise<any> {  
      this.setState({  
        status: 'Loading latest items...'
      });  
      
      const body: string = JSON.stringify(bodyData);  
  
     return this.props.spHttpClient.post(`${this.props.siteUrl}/_api/web/lists/getbytitle('Inputs')/items(${itemId})`,  
        SPHttpClient.configurations.v1,  
        {  
          headers: {  
            'Accept': 'application/json;odata=nometadata',  
            'Content-type': 'application/json;odata=nometadata',               
            'IF-MATCH': '*',  
            'X-HTTP-Method': 'MERGE'  
          },  
          body: body  
        });        
  } 
           this.updateItem(JSON.stringify(mapObj), a.Id, "Inputs")
                  .then((response: SPHttpClientResponse): void => {  
                  console.log(response);                  
                }, (error: any): void => {  
                  
                });

In Above code even normal title column update not working. Please let me know if this is known issue.

**Comment by patmill** [comment]
What are you seeing?  If you look at the network trace, what does the request sent / response received look like?

**Comment by abdollahkahne** [comment]
Why you doesnt the standard way which uses ISPHttpClientOptions Interface from '@microsoft/sp-http' module for creating the 3rd parameter for post method? Try to create and object similar to this interface. Also v1 configuration have by itself the content type and form digest. Forget about repeating them in the 3 rd parameter. Try to add **as ISPHttpClientOptions** to  3rd parameter probably you succeed. But if you'd failed try to create this type from the scrach! (According to Jussi Roine in his fantastic book about sharepoint framework which describe these methods )

**Comment by FullStackRafik** [comment]
Hello,
I get the same error, any updates please?
Thanks

**Comment by abdollahkahne** [comment]
@FullStackRafik @leodak 
Try to use this type code (It works for me so verified!):
```
  private _updateListItem():void {
    this._newForm.style.display='none';
    const itemId=this._itemID.valueAsNumber;
    const fullUrl=this.context.pageContext.web.absoluteUrl+
    `/_api/web/lists/getByTitle('My List')/Items(${itemId})`;
    const itemTitle:string=this._itemTitle.value;
    const itemInfo:string=this._itemInfo.value;
    const itemDefinition:any={
      Title:itemTitle,
      Info:itemInfo
    }
    const headers:any={
      'X-HTTP-Method':'MERGE',
      'IF-Match':'*'
    }
    const spHttpClientOption:ISPHttpClientOptions={
      'body':JSON.stringify(itemDefinition),
      'headers':headers
    }
    this.context.spHttpClient.post(fullUrl,SPHttpClient.configurations.v1,spHttpClientOption)
    .then((response:SPHttpClientResponse)=>{
      if (response.status===204) {
        this._operationReults.innerHTML="Update: List Item updated successfully!";
        this._readAllItems();
      }
      else {
        this._operationReults.innerHTML="Update: List Item Failed to update!"+
        response.statusText+'('+response.status+')';
      }
    }); 
```
As you see I have two object naming headers and itemDefinition which I convert them to an ISPHttpClientOptions then. Then I use a post method which simply uses 3 parameters including url, configuration template and ISPHTTPClientOptions.

**Comment by FullStackRafik** [comment]
Hello @abdollahkahne ,
Thanks for your reply.
This code is not working for me, but I resolved that using PNP library, it's more optimized to use.
Thanks again.


Rafik

**Comment by andrewconnell** [comment]
Couple things stand out:

- The content type should just be `application/json`... don't include the metadata part.
- What does the body look like? You're passing in a string into your function but then running `JSON.stringify()` on it... what is it, a string or JSON?
- Need more context on the specific request as @patmill mentioned [in his comment](https://github.com/SharePoint/sp-dev-docs/issues/3539#issuecomment-469882251)
