### ISSUE TITLE
Use Workbench in List and List Item Context 

### ISSUE THREAD

**Issue by ShaunCurtis** [SharePoint/sp-dev-docs#354]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Can the Workbench be used for testing a web part that needs a List and List Item context - this.context.pageContext.listItem?  I can't see any examples - all the ones I've seen just use the site or web context - this.context.pageContext_.  The web part will display data from a "custom" list in a different way than the standard viewer.

**Comment by manishgarg1** [comment]
Hi @ShaunCurtis, absolutely. That is exactly the purpose of the SharePoint hosted workbench. The hosted workbench should have the correct context as any other sharepoint page. Please try that option and let us know if you see issues.

**Comment by patmill** [comment]
Just clarifying this a bit.  If you upload the workbench into a document library (this will require no-script to be disabled for the site collection), you will get the context of the item.

However, with some SharePoint trickery, you can explicitly set the list context on the _layouts/15/workbench.aspx page by setting the List query string.  The easiest way to find out the right property is to go to the list in question, view it in classic mode, then click "customize list" in the ribbon.  You'll see a query string with the list ID in it.  Just paste that onto the URL of the workbench.

Unfortunately, the ID property to get a list item appears to not return the item at the moment.

**Comment by ShaunCurtis** [comment]
Hi Pat
Thanks for the info I will try.  

I'm just working on trying to do it the way I did in the past in the server side world - set the DisplayFormUrl property on the content type of the list to _Layouts/workbench.aspx.  I can't see how to so this in SharePoint Online powershell so writing a quick desktop app to set this up.
 
The Server side solution had a page in layouts with the custom viewer as a web control. I then set the DisplayFormUrl property of the Content Type(s) in the list to the layouts page and all worked.  Setting the SPList.DefaultDisplayFormUrl caused all sorts of problems and carried too much baggage!

**Comment by ShaunCurtis** [comment]
Hi,
I've done what I said and set up the workbench.aspx as the DisplayFormUrl for my list.  This works.  The Url looks something like : http://xxx.sharepoint.com/sites/Test/_layouts/15/Workbench.aspx?List=aba0bd7e%2D91e2%2D4233%2D8723%2De3cde2e0ba54&ID=1&....

The Helloworld WebPart with appropriate code to display the list and listitem contexts looks like this:
![image](https://cloud.githubusercontent.com/assets/24959469/22069628/fe80a21e-dd90-11e6-985b-ac678765ad07.png)
As you say the ListId property doesn't work.  You can always get it from the Url, but that would be inventing a new wheel!

**Comment by patmill** [comment]
OK, dug into this a bit more.  There is a bug where the item context is coming down in the workbench, but it is missing a piece of information to populate the page context object correctly.  Bug logged, and we'll get that working.

**Comment by patmill** [comment]
If you follow the standard SharePoint query string model, the hosted workbench will pick up on the list and listitem IDs.  For example, if you append ?List=%7BC1FC063D-8AAB-42EB-BB76-555BFEA09B74%7D&ID=9  The context.pagecontext.list.id and context.pagecontext.listitem.id will be populated correctly.

A bit hacky at the moment, but it will work.
