### ISSUE TITLE
hi am encountering this error when i run gulp serve

### ISSUE THREAD

**Issue by nebiyat123** [SharePoint/sp-dev-docs#3541]
gulp : module.js:549
At line:1 char:1
+ gulp serve
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (module.js:549:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    throw err;
    ^
Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\nebiyat.etana\Desktop\final\sp-dev-fx-webparts\samples\react-side-panel\gulpfile.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by bcameron1231** [comment]
Sounds like you are missing nodule modules. From command line call `npm install @microsoft/sp-build-web` , then serve the solution and see if it resolves your issue?

If not, delete your node_modules folder and your package-lock.json, run `npm install @microsoft/sp-build-web `

**Comment by nebiyat123** [comment]
Thanks bcameron i was able to run the gulp file and it loads to open the workbench and this error pops up
![err](https://user-images.githubusercontent.com/48029087/53750099-eaed6400-3e76-11e9-8d26-d145650e5e32.PNG)

**Comment by bcameron1231** [comment]
You need to run `gulp trust-dev-cert`  as outlined by this document https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

**Comment by nebiyat123** [comment]
I run gulp trust-dev-cert but still the workbench is not loading and when i run gulp serve it gives me this error Warning - tslint - src/webparts/sidePanel/SidePanelWebPart.ts(8,3): error no-unused-imports: unused import: 
'IPropertyPaneDropdownOption'
Warning - tslint - src/webparts/sidePanel/components/WebPart/SidePanel.tsx(4,10): error no-unused-imports: unused import: 
'escape'
Warning - tslint - src/webparts/sidePanel/SidePanelWebPart.ts(8,3): error no-unused-imports: unused import: 
'IPropertyPaneDropdownOption'
Warning - tslint - src/webparts/sidePanel/components/WebPart/SidePanel.tsx(4,10): error no-unused-imports: unused import: 
'escape'
Error - Unknown 
 listen EADDRINUSE :::4321
Error - Unknown 
 listen EADDRINUSE :::5432

**Comment by bcameron1231** [comment]
EADDRINUSE :::4321 means that your port 4321 is already being used. So either stop that application from using that port on localhost or choose a new port number for spfx solution.

**Comment by nebiyat123** [comment]
I change the port number to a new one still the same

**Comment by bcameron1231** [comment]
You stopped running, change the serve.json and re-served and still have that error?

I'm out of ideas. If you are still getting an eaddrinuse error, the port is still being used somewhere. Either by another node/gulp serve instance or being blocked by a firewall.

**Comment by nebiyat123** [comment]
Actually i was able to solve all the error thank you but when i finally deploy the app it will get the content from the previous localhost number.
![image](https://user-images.githubusercontent.com/48029087/53763745-8394db80-3e99-11e9-9c99-e2a994efe02d.png)

**Comment by bcameron1231** [comment]
I suggest reading through all of the documentation available for SharePoint Framework before diving too deep into the development of WebParts and Extensions. The documentation covers these topics in depth. 

Getting Started
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

Deploying your web part
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn
