### ISSUE TITLE
Cannot Install SPFx Solution or Activate Custom Feature using a Site Design

### ISSUE THREAD

**Issue by qazqwertish** [SharePoint/sp-dev-docs#3543]
It is not possible to install an SPFx solution or activate the custom feature that contains the Application Customizers custom actions. Instead, the OOB features are able to be activated. Is there a way at least to access to more traceable information than "Action failed"?

![capture](https://user-images.githubusercontent.com/7807026/53812906-b94ec880-3f5c-11e9-921d-52673c8bdd44.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview#feedback)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Can you provide your Site Script to review? Deploying an Application Customizer is possible with Site Scripts.

**Comment by qazqwertish** [comment]
{
     "$schema": "schema.json",
        "actions": [
            {
                "verb": "installSolution",
                "id": "de5b5cce-0a0c-40b2-820c-1569ba81e9d0",
                "name": "MY_SOLUTION"
            },
            {
                "verb": "activateSPFeature",
                "featureId": "15a572c6-e545-4d32-897a-bab6f5846e18"
            },
            {
                "verb": "activateSPFeature",
                "featureId": "4cd826ba-70fd-4e81-9149-d6edc243e4b0"
            },
            {
                "verb": "applyTheme",
                "themeName": "MY_THEME"
            }
        ],
        "bindata": { },
        "version": 1
}

Our solution contains both webparts and extensions, that is why we use the installSolution action, that already includes both (so no need to do the associateExtension action). We tried with and without the name in the installSolution, since it has been included in the latest schema: [https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json](https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json)

**Comment by melitoSP** [comment]
@qazqwertish if you're still experiencing this issue, please raise a support ticket so we can look into this issue. Improving error reporting is in our backlog.

**Comment by Zerg00s** [comment]
I confirm that we experience the same same issue:

Site Design JSON:
```
{
    "$schema": "schema.json",
    "actions": [
        {
            "verb": "installSolution",
            "id": "{AppPackageId:ContosoCentral}"
        }        
    ],
    "version": 1
  }
```

![image](https://user-images.githubusercontent.com/2797648/61760522-d3693600-ad99-11e9-8620-70b7abc7c0c7.png)
