### ISSUE TITLE
@rowIndex is populated in list view when using rowFormatter in JSON, but not in modern themed site page displaying that list

### ISSUE THREAD

**Issue by sanjitlpatel** [SharePoint/sp-dev-docs#3544]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

@rowIndex returns a non-0 value and can be used to set an additional row class to alternate the row color.  This behavior works as designed when viewing the list and when viewing a modern themed site page with a web part containing that list.

@rowIndex returns a non-0 value and can be used to set the absolute position of a row item in the list view.  This behavior works as expected within the list view.

#### Observed Behavior

The expected behavior is that the modern themed site with the web part containing the list displays the same as the list view.  However, the list items are stacked on top of each other off the screen.   It is presumed that @rowIndex returns -1 for all row items when the list is viewed on the site page.

#### Steps to Reproduce

Create a list with 3 columns:
Icon
URL
Title

Populate the list with any sample data.
Format View and apply the following JSON.

`{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "span",
    "attributes": {
      "class": "sp-row-card"
    },
    "style": {
      "width": "100px",
      "height": "150px",
      "text-align": "center",
      "float": "left",
      "top": "10px",
      "position": "absolute",
      "left": {
        "operator": "+",
        "operands": [
          {
            "operator": "toString()",
            "operands": [
              {
                "operator": "*",
                "operands": [
                  "@rowIndex",
                  130
                ]
              }
            ]
          },
          "px"
        ]
      }
    },
    "children": [
      {
        "elmType": "div",
        "style": {
          "text-align": "center",
          "align-items": "center"
        },
        "children": [
          {
            "elmType": "a",
            "attributes": {
              "class": "sp-row-title",
              "href": "[$URL]"
            },
            "children": [
              {
                "elmType": "img",
                "attributes": {
                  "src": "[$Icon]"
                },
                "txtContent": "[$Title]",
                "style": {
                  "max-width": "100px",
                  "max-height": "100px"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}`
Below is the desired behavior seen in the list view
![image](https://user-images.githubusercontent.com/5403907/53843485-90383300-3f70-11e9-973c-539f9a71cb43.png)

Below is the undesired behavior seen in the modern themed site page.  The list items of My Links have their right edges lined up with the left edge of the viewport.
![image](https://user-images.githubusercontent.com/5403907/53843617-0fc60200-3f71-11e9-8255-4d476c38135d.png)

**Comment by svaibhav** [comment]
I guess this issue is resolved and the @rowIndex is getting properly populated now. Also I don't think that we need to to multiply the @rowIndex to 130 is a very good approach as this will always add the new element to the right, instead of having something like a line-break behavior.

Try the following JSON:
`{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "span",
    "attributes": {
      "class": "sp-row-card"
    },
    "style": {
      "width": "100px",
      "height": "150px",
      "text-align": "center",
      "float": "left",
      "position": "relative"
    },
    "children": [
      {
        "elmType": "div",
        "style": {
          "text-align": "center",
          "align-items": "center"
        },
        "children": [
          {
            "elmType": "a",
            "attributes": {
              "class": "sp-row-title",
              "target": "_blank",
              "href": "[$URL]"
            },
            "children": [
              {
                "elmType": "img",
                "attributes": {
                  "src": "[$Icon]"
                },
                "txtContent": "[$Title]",
                "style": {
                  "max-width": "100px",
                  "max-height": "100px"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
`

Feel free to play along with the various style properties.

**Comment by svaibhav** [comment]
@sanjitlpatel Please let us know if you face any problem with this!

**Comment by shagra-ms** [comment]
The issue is resolved.

@sanjitlpatel Please do let us know if you are still facing this issue.
