### ISSUE TITLE
SharePoint online adding ctag querystring to scriptlinks on publishing sites

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-docs#3545]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Starting from march 2019, in SharePoint online publishing sites, if you have added scriptlink using custom action to site/web level, the scriptlinks are appended with querystring value ctag=yymmdd. Do we have any more information about this feature?

![screenshot 2019-03-06 at 8 55 23](https://user-images.githubusercontent.com/2223355/53863126-07fa7200-3ff2-11e9-8f55-2606ebc59d61.png)

**Comment by VesaJuvonen** [comment]
Can you @tavikukko provide more details on the root cause of the question, so that we can triage this properly. Is this causing a challenge for you somehow?

**Comment by tavikukko** [comment]
Hi @VesaJuvonen ,
This is something that caught my eye back then. I have studied it more and it seems that its busting the ScriptLinks every second day. Also looks like it's using **ControlAdapter** to modify the url just before rendering the link, because the actual injected link in the **ScripLink CustomAction** does not get changed.
This has not broken anything, so seems to work properly. 
Of course it raises questions that if you have many of these links and **busting the cache without no reason can cause unwanted load to the tenants**. We can imagine an intranet with 50K users: so every first day after weekend, all users hitting the first time to their SharePoint site, will load again all the files injected using ScriptLinks. 
Another thing I can imagine, there might be solutions where **'ctag' querystring** was already in use, so no idea how it will affected in those cases. 
I think this is great feature, just interested on how it actually works under the hood, if there is anything we can customize/enable/disable. 
Thanks and cheers!
