### ISSUE TITLE
SharePoint Framework Webpart doesnt work in mozila but works in Opera

### ISSUE THREAD

**Issue by abdollahkahne** [SharePoint/sp-dev-docs#3546]
#### Category
- [x] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I deploy a sample feedback webpart, I expect it work well and same on all browsers

#### Observed Behavior
Unfortunately same part of the code doesnt work on mozilla, although it works on opera well. 

#### Steps to Reproduce

1. Firstly create a simple form in render method (on input and one button)
2. then read the input file after user press the button
3. then submit the inp ut value to a sharepoint list.
For fetching input value I use a method which trigered by key-up event on the input element.
I attached the related code below. Mozila doesnt recognize the srcelement of the event and so doesnt fetch the element value for further process (Step 2). Although there is some trick for solving issue using another methods but I have the question why should two different browser acts differently in this matter
`//This code used for Step 2 and it is the question place
 private setComment(e:Event):void {
    let srcElement:HTMLInputElement=e.srcElement as HTMLInputElement;
    this._commentText=escape(srcElement.value);

  }
`

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
All browsers behave differently, and all browsers support different functions, it is the nature of web development. .srcElement is proprietary alias (Internet Explorer) for "e.target", which is supported in some browsers but not all. FF stopped support for this in FireFox 62.

For your code, I would avoid using `e.srcElement` and replace it with `e.target`  or `e.currentTarget` depending on when you are getting the value from the event.

**Comment by abdollahkahne** [comment]
@bcameron1231   Thanks for such a complete answer. I am new to this area and start learning it for SharePoint client side development. Thanks again
