### ISSUE TITLE
Theme colors does not change on partial page load.

### ISSUE THREAD

**Issue by Mouritze** [SharePoint/sp-dev-docs#3548]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I navigate from one Site to another, with partial page load (e.g. a link or return in browser), I expect that the correct theme color palette for the new Site is loaded.

#### Observed Behavior
When I navigate from one Site to another, with partial page load (e.g. a link or return in browser), the theme color palette for the new Site is not updated. This means that the Site is showing the wrong colors. If I reload the page (F5), the correct theme colors are applied.

#### Steps to Reproduce
Create two sites with different themes. 
For example, we create Site A with primary color GREEN and Site B with primary color RED. 
In Site A, create a link (in the navigation or on the site somewhere) that links to Site B. This should force a partial page load when you click it. Else navigate from Site A to Site B by writing its URL in the browser, and use the return/back button.

To confirm that the theme variable does not update, you can open the developer tools and print the object in the console with **window.__themeState__.theme**. 
Print it on Site A, navigate to Site B with partial page load and print it again (notice it has not changed). Lastly reload(F5) Site B, print the variable again and notice that it is now correct.

#### Last notes
I have a customer with additional HUBS that each have their own theme. Each time they navigate around their intranet with partial page load, the wrong theme palette is loaded, which causes a lot of confusion for the end users.

I hope we can get some clarification :) 

Best Regards
Mads

**Comment by OliverZeiser** [comment]
I can confirm that. We are seeing the same issue in all our tenants.

**Comment by VesaJuvonen** [comment]
This seems to be a non-dev issue, which means that we cannot process it through this channel. This is clearly a bug, but due to our internal process, we cannot bypass this properly to the right people. Please submit this also through the tenant admin support channels which are valid for non-dev topics. Thx.

**Comment by Mouritze** [comment]
@VesaJuvonen 
Hi Vesa, 

Thank you for coming back to me on this issue.
Do we have a tenant admin support channel you can link me, or did you mean that I should reach out to support through the admin interface in my tenant? 

Best Regards
Mads
