### ISSUE TITLE
App doesn't appear on some sites

### ISSUE THREAD

**Issue by Dangerous-Mind** [SharePoint/sp-dev-docs#3549]
#### Category
- [ x ] Question
- [ ] Typo
- [ x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After a successful deploy the solution should appear on de modern page selection box.

#### Observed Behavior

The solution does not show on some of the modern sites.

#### Steps to Reproduce

Create a solution with assets to provision the contentType and Lists.
Deploy to the appCatalog. Add solution to the new site.
The Columns, contentType and Lists/libraries are created but there is no App to add on the selection box.
If I remove the deployment of the feature containing the provisioning the app appears on the site.

I'm using SPFx 1.7.1 -plusbeta (Going to create a Teams App also)

Strangely there other sites were the app is displayed correctly.

#### Submission Guidelines

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "letters-client-side-solution",
    "id": "3816ec12-beb9-4701-a8b6-19dcbad4e9c9",
    "version": "1.0.0.4",
    "includeClientSideAssets": true,
      "features": [
        {
          "title": "Letters List Build",
          "description": "Creates the Lists Used in the Letters App",
          "id": "22400B25-0AF5-41AC-A3C7-D5F42854203E",
          "version": "1.0.0.0",
          "assets": {
            "elementManifests": [
              "elements.xml"
            ],
            "elementFiles": [
              "LettersSchema.xml",
              "ScannedLetters1Schema.xml",
              "ScannedLetters2Schema.xml"
            ]
          }
        }
      ]
  },
  "paths": {
    "zippedPackage": "solution/letters.sppkg"
  }
}
```
Thanks for your Support! Helping is caring.

**Comment by VesaJuvonen** [comment]
Can you send a trace from the browser / Fiddler on the web part picker for investigation? The typical issue around this is that the feature activation was not succeeded and therefore the app is not available in the app picker. Can you check from the site contents that the app has been successfully installed or not for the problematic sites? Thx.

**Comment by Dangerous-Mind** [comment]
Hi Vesa,

New app, same problem.
I have a lot of problem provisioning lookups between lists.
But in the end the app Details page has no errors. 

So I think it was installed correctly. 
Although the provisioning was not has intended I have no errors on the site and the feature, on the site features provisioning the content types and lists is active.

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "logistics-ticketing-client-side-solution",
    "id": "485a8a96-901c-458f-ae03-a8a54f5282bb",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "features": [
        {
          "title": "Logistics List Build",
          "description": "Creates the Lists Used in the Logistics Ticketing App",
          "id": "abeae304-33b0-4a31-8e69-9e2682d2406f",
          "version": "1.0.0.0",
          "assets": {
            "elementManifests": [
              "elements.xml"
            ],
            "elementFiles": [
              "LogisticCategory.xml",
              "LogisticServices.xml",
              "LogisticTickets.xml"
            ]
          }
        }
      ]
  },
  "paths": {
    "zippedPackage": "solution/logistics-ticketing.sppkg"
  }
}
```

`
Timestamp,Level,Scope,Source,Message
--
2019/04/12   11:15:58.548,verbose,RootServiceScope,ServiceScopeBuilder: Added preloaded   FormDigestValue to cache
2019/04/12   11:15:58.554,warning,Session,The pageId parameter was undefined or invalid.   Generating a new Guid
2019/04/12   11:15:58.557,verbose,ServiceScopeBuilder: Added pre,RootServiceScope
2019/04/12   11:15:58.571,verbose,SPComponentLoader.loadComponen,"***Loading   component ""1cea229f-b208-4202-8014-22503d92a019""   (SPDataProviders)."
2019/04/12   11:15:58.571,verbose,"***Loading component   ""1cea229f",SPComponentLoader.loadComponen
2019/04/12   11:15:58.573,verbose,SPComponentLoader.loadComponen,"***Loading   component ""cbe7b0a9-3504-44dd-a3a3-0e5cacd07788""   (PageTitle)."
2019/04/12   11:15:58.573,verbose,"***Loading component   ""cbe7b0a9",SPComponentLoader.loadComponen
2019/04/12   11:15:58.574,verbose,PageDesignPackageProvider,"DesignPackageId:   undefined, webTemplate: 1"
2019/04/12   11:15:58.574,verbose,"DesignPackageId: undefined,   we",PageDesignPackageProvider
2019/04/12   11:15:58.575,verbose,PageDesignPackageProvider,"Design Package:   {""id"":""c8b3137a-ca4c-48a9-b356-a8e7987dd693"",""title"":""***teamSiteTitle"",""description"":""***teamSiteDescription"",""chromeOptions"":{""heade"
2019/04/12   11:15:58.575,verbose,"Design Package:   {""id"":""c8b3137",PageDesignPackageProvider
2019/04/12   11:15:58.575,verbose,SPPageApp,"{""id"":""c8b3137a-ca4c-48a9-b356-a8e7987dd693"",""title"":""***teamSiteTitle"",""description"":""***teamSiteDescription"",""chromeOptions"":{""header"":{""hidden"":fal"
2019/04/12   11:15:58.575,verbose,"{""id"":""c8b3137a-ca4c-48a9-b356",SPPageApp
2019/04/12   11:15:58.575,verbose,PageFieldData,Validated required fields from page   context
2019/04/12 11:15:58.575,verbose,Validated   required fields from,PageFieldData
2019/04/12   11:15:58.577,verbose,PageFieldData,Finish setting page field data from page   context
2019/04/12 11:15:58.577,verbose,Finish   setting page field data,PageFieldData
2019/04/12   11:15:58.578,verbose,PageManager,Loading alternative url map   :loadAlternativeUrlMap
2019/04/12 11:15:58.578,verbose,Loading   alternative url map :l,PageManager
2019/04/12   11:15:58.584,verbose,SPPageApp,start onRender
2019/04/12 11:15:58.584,verbose,start   onRender,SPPageApp
2019/04/12   11:15:58.584,verbose,SPPageApp,Creating page router
2019/04/12 11:15:58.584,verbose,Creating   page router,SPPageApp
2019/04/12   11:15:58.600,verbose,SiteHeaderHost,SiteHeaderHost.tsx: componentIsMounted
2019/04/12   11:15:58.600,verbose,SiteHeaderHost.tsx: componentI,SiteHeaderHost
2019/04/12   11:15:58.600,verbose,Page,Page.tsx: componentIsMounted
2019/04/12 11:15:58.600,verbose,Page.tsx:   componentIsMounted,Page
2019/04/12   11:15:58.603,verbose,PlaceholderProvider,"Creating placeholder content   in placeholder ""1"""
2019/04/12 11:15:58.603,verbose,Creating   placeholder content i,PlaceholderProvider
2019/04/12   11:15:58.608,verbose,CustomTitleRegion,CustomTitleRegion.tsx: Render
2019/04/12   11:15:58.608,verbose,CustomTitleRegion.tsx: Render,CustomTitleRegion
2019/04/12   11:15:58.610,verbose,SPCanvas,SPCanvas.tsx: componentIsMounted
2019/04/12   11:15:58.610,verbose,SPCanvas.tsx: componentIsMount,SPCanvas
2019/04/12   11:15:58.611,verbose,SPPageApp,Setting page display mode
2019/04/12 11:15:58.611,verbose,Setting   page display mode,SPPageApp
2019/04/12   11:15:58.613,verbose,SPCanvas,Rendering Canvas: _renderCanvas
2019/04/12 11:15:58.613,verbose,Rendering   Canvas: _renderCanva,SPCanvas
2019/04/12   11:15:58.614,verbose,CanvasComponent,CanvasComponent _render() is called
2019/04/12   11:15:58.614,verbose,CanvasComponent _render() is c,CanvasComponent
2019/04/12   11:15:58.619,verbose,CanvasComponent,CanvasComponent is mounted
2019/04/12   11:15:58.619,verbose,CanvasComponent is mounted,CanvasComponent
2019/04/12   11:15:58.620,verbose,SPCanvas,SPCanvas _handleCanvasViewportRendered invoked   with endTime 516
2019/04/12 11:15:58.620,verbose,SPCanvas   _handleCanvasViewport,SPCanvas
2019/04/12   11:15:58.647,verbose,NavigationOrchestrator,Loading application customizers
2019/04/12 11:15:58.647,verbose,Loading   application customizer,NavigationOrchestrator
2019/04/12   11:15:58.647,verbose,ApplicationCustomizerLoader,Loading new extensions
2019/04/12 11:15:58.647,verbose,Loading   new extensions,ApplicationCustomizerLoader
2019/04/12   11:15:58.647,verbose,ClientSideCustomAction,The rights object has invalid   format. One of High or Low fields cannot be undefined. Object value is '{}
2019/04/12 11:15:58.647,verbose,The   rights object has invalid ,ClientSideCustomAction
2019/04/12   11:15:58.648,verbose,SPComponentLoader.loadComponen,"***Loading   component ""caa77de4-d809-417a-959a-8e724a617c3a""   (DesignApplicationCustomizer)."
2019/04/12   11:15:58.648,verbose,"***Loading component   ""caa77de4",SPComponentLoader.loadComponen
2019/04/12   11:15:58.684,verbose,SPComponentLoader.loadComponen,Address not found for   module name:   https://shellprod.msocdn.com/shellux/o365/versionless/suiteux.shell.bootstrapper.dc6381dda71d8c5f0593.js.   Using it
2019/04/12 11:15:58.684,verbose,Address   not found for module n,SPComponentLoader.loadComponen
2019/04/12   11:15:58.715,verbose,SPComponentLoader.loadComponen,"***Component   ""1cea229f-b208-4202-8014-22503d92a019""   (SPDataProviders) loaded."
2019/04/12   11:15:58.715,verbose,"***Component   ""1cea229f-b208-42",SPComponentLoader.loadComponen
2019/04/12   11:15:58.722,verbose,SPComponentLoader.loadComponen,"***Component   ""cbe7b0a9-3504-44dd-a3a3-0e5cacd07788"" (PageTitle)   loaded."
2019/04/12   11:15:58.722,verbose,"***Component   ""cbe7b0a9-3504-44",SPComponentLoader.loadComponen
2019/04/12   11:15:58.764,verbose,CustomTitleRegion,CustomTitleRegion.tsx: Render
2019/04/12   11:15:58.764,verbose,CustomTitleRegion.tsx: Render,CustomTitleRegion
2019/04/12   11:15:58.769,verbose,SPComponentLoader.loadComponen,"***Loading   component ""f9e737b7-f0df-4597-ba8c-3060f82380db""   (SPPropertyPane)."
2019/04/12   11:15:58.769,verbose,"***Loading component   ""f9e737b7",SPComponentLoader.loadComponen
2019/04/12   11:15:58.770,verbose,SPPageDataProvider,get home page url from cache
2019/04/12 11:15:58.770,verbose,get home   page url from cache,SPPageDataProvider
2019/04/12   11:15:58.837,verbose,AutoSaveTimer,resetting AutoSaveAttempts
2019/04/12 11:15:58.837,verbose,resetting   AutoSaveAttempts,AutoSaveTimer
2019/04/12   11:15:58.837,verbose,AutoSaveTimer,clearing auto-save timer
2019/04/12 11:15:58.837,verbose,clearing   auto-save timer,AutoSaveTimer
2019/04/12   11:15:58.838,verbose,AutoSaveTimer,cleared autosave with the following timer   ID undefined
2019/04/12 11:15:58.838,verbose,cleared   autosave with the foll,AutoSaveTimer
2019/04/12   11:15:58.838,verbose,AutoSaveTimer,creating auto-save timer
2019/04/12 11:15:58.838,verbose,creating   auto-save timer,AutoSaveTimer
2019/04/12   11:15:58.838,verbose,AutoSaveTimer,created the auto-save timer with the   following timer ID 132
2019/04/12 11:15:58.838,verbose,created   the auto-save timer wi,AutoSaveTimer
2019/04/12   11:15:58.850,verbose,SPCommandBar,CommandBar is mounted
2019/04/12   11:15:58.850,verbose,CommandBar is mounted,SPCommandBar
2019/04/12   11:15:58.870,verbose,SPHttpClient,GET   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/web/lists('%7Bc6e8e98a-a292-4e18-a339-990ed218c94c%7D')/GetItemById(3)/likedByInformatio
2019/04/12 11:15:58.870,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:58.872,verbose,SPHttpClient,"GET   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/sphomeservice/context?$expand=Token,Payload"
2019/04/12 11:15:58.872,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:58.873,verbose,SPHttpClient,"GET   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/sphomeservice/context?$expand=Token,Payload"
2019/04/12 11:15:58.873,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:58.884,verbose,DigestCache,DigestCache: Reusing cached digest.  Expiration: 1770000
2019/04/12   11:15:58.885,verbose,DigestCache: Reusing cached di,DigestCache
2019/04/12   11:15:58.947,verbose,SPComponentLoader.loadComponen,"***Component   ""caa77de4-d809-417a-959a-8e724a617c3a""   (DesignApplicationCustomizer) loaded."
2019/04/12   11:15:58.947,verbose,"***Component   ""caa77de4-d809-41",SPComponentLoader.loadComponen
2019/04/12   11:15:58.948,verbose,BasePerformanceLogger,Extension.ScriptLoad for component   caa77de4-d809-417a-959a-8e724a617c3a (DesignApplicationCustomizer) took 300   ms
2019/04/12   11:15:58.948,verbose,Extension.ScriptLoad for compo,BasePerformanceLogger
2019/04/12   11:15:58.949,verbose,BasePerformanceLogger,Extension.Init for component   caa77de4-d809-417a-959a-8e724a617c3a (DesignApplicationCustomizer) took 1 ms
2019/04/12   11:15:58.949,verbose,Extension.Init for component c,BasePerformanceLogger
2019/04/12   11:15:58.949,verbose,BasePerformanceLogger,Extension.Create for component   caa77de4-d809-417a-959a-8e724a617c3a (DesignApplicationCustomizer) took 300   ms
2019/04/12   11:15:58.949,verbose,Extension.Create for component,BasePerformanceLogger
2019/04/12   11:15:58.958,verbose,ClientSideWebPartManager,Request 1 of 1 received to load   web part PageTitle.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:58.958,verbose,Request 1   of 1 received to loa,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:58.959,verbose,ClientSideWebPartStatusRendere,Displaying loading   indicator
2019/04/12   11:15:58.959,verbose,Displaying loading   indicator,ClientSideWebPartStatusRendere
2019/04/12   11:15:58.959,verbose,ClientSideWebPartManager,Started loading web part   WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:58.959,verbose,Started   loading web part   WebPa,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:58.960,verbose,ClientSideWebPartManager,Successfully loaded modules for   web part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12   11:15:58.960,verbose,Successfully loaded modules   fo,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:58.961,verbose,BaseWebPart,Constructed web part:   WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12   11:15:58.961,verbose,Constructed web part: WebPart.,BaseWebPart
2019/04/12   11:15:58.963,verbose,ClientSideWebPartManager,"All 1 web parts requested   to load, has been processed"
2019/04/12 11:15:58.963,verbose,All 1 web   parts requested to l,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:58.973,verbose,SPComponentLoader.loadComponen,"***Component   ""f9e737b7-f0df-4597-ba8c-3060f82380db"" (SPPropertyPane)   loaded."
2019/04/12   11:15:58.973,verbose,"***Component   ""f9e737b7-f0df-45",SPComponentLoader.loadComponen
2019/04/12   11:15:58.974,verbose,BaseClientSideWebPart,Started first time render for web   part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:58.974,verbose,Started   first time render for ,WebPart.PageTitle.internal.cbe.BaseClientSideWebPart
2019/04/12   11:15:58.974,verbose,ViewportLoader,ViewportLoader is Initialized
2019/04/12   11:15:58.974,verbose,ViewportLoader is Initialized,ViewportLoader
2019/04/12   11:15:58.977,verbose,BaseClientSideWebPart,Actually started first time render   for web part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:58.977,verbose,Actually   started first time re,WebPart.PageTitle.internal.cbe.BaseClientSideWebPart
2019/04/12   11:15:58.977,verbose,ViewportLoader,Web part is loaded in initial viewport.
2019/04/12 11:15:58.977,verbose,Web part   is loaded in initial ,ViewportLoader
2019/04/12   11:15:58.977,verbose,BaseClientSideWebPart,onInit method completed for web   part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:58.977,verbose,onInit   method completed for we,WebPart.PageTitle.internal.cbe.BaseClientSideWebPart
2019/04/12   11:15:58.977,verbose,ClientSideWebPartStatusRendere,Clear loading indicator
2019/04/12 11:15:58.977,verbose,Clear   loading indicator,ClientSideWebPartStatusRendere
2019/04/12   11:15:59.037,verbose,SPHttpClient,GET   https://aenergia.sharepoint.com//_api/SP.Directory.DirectorySession/GetGraphUser(principalName='joao.miguel%40aenergy.com')?$select=sharePointSave
2019/04/12 11:15:59.037,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:59.049,verbose,SPHttpClient,GET   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/search/query?QueryText=%27((WebId:9b66406a-8aa0-49e5-b27e-3d45a369b400%20AND%20SiteId:3b
2019/04/12 11:15:59.049,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:59.060,verbose,BaseClientSideWebPart,Completed async render for web   part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12 11:15:59.060,verbose,Completed   async render for web,WebPart.PageTitle.internal.cbe.BaseClientSideWebPart
2019/04/12   11:15:59.062,verbose,ClientSideWebPartManager,Successfully loaded modules for   web part WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788.
2019/04/12   11:15:59.062,verbose,Successfully loaded modules   fo,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:59.088,verbose,HttpClient,POST   https://northeurope4-sphomep.svc.ms/api/v1/documents/metadata
2019/04/12 11:15:59.088,verbose,POST   https://northeurope4-spho,HttpClient
2019/04/12   11:15:59.102,verbose,SPHttpClient,GET   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/web/GetClientSideWebParts
2019/04/12 11:15:59.102,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:15:59.102,verbose,CanvasComponent,CanvasComponent _render() is called
2019/04/12   11:15:59.102,verbose,CanvasComponent _render() is c,CanvasComponent
2019/04/12   11:15:59.110,verbose,SPCanvas,SPCanvas _handleCanvasViewportRendered invoked   with endTime 1007
2019/04/12 11:15:59.110,verbose,SPCanvas   _handleCanvasViewport,SPCanvas
2019/04/12   11:15:59.135,verbose,ClientSideWebPartManager,Web part   WebPart.PageTitle.internal.cbe7b0a9-3504-44dd-a3a3-0e5cacd07788 is added into   EUPL calculation.
2019/04/12 11:15:59.135,verbose,Web part   WebPart.PageTitle.int,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:59.135,verbose,ClientSideWebPartManager,All Web parts in the viewports   are rendered at 957
2019/04/12 11:15:59.135,verbose,All Web   parts in the   viewports,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:15:59.136,verbose,ViewportLoader,loadOutsideViewPort is called to load   rest of the 0 web parts
2019/04/12   11:15:59.136,verbose,loadOutsideViewPort is called ,ViewportLoader
2019/04/12   11:15:59.136,verbose,ViewportLoader,loadOutsideViewPort is completed
2019/04/12   11:15:59.136,verbose,loadOutsideViewPort is complet,ViewportLoader
2019/04/12   11:15:59.166,verbose,FirstRunDataProvider,"Request successfully for   retrieving first run bit FirstRunSharePointSaveForLaterTeachingBubble, the   status: true"
2019/04/12 11:15:59.166,verbose,Request   successfully for retri,FirstRunDataProvider
2019/04/12   11:15:59.200,verbose,HttpClient,GET   https://northeurope4-sphomep.svc.ms/api/v1/document/metadata?siteId=3b0c4795-de15-405f-99b4-a3681394cb71&webId=9b66406a-8aa0-49e5-b27e-3d45a369b40
2019/04/12 11:15:59.200,verbose,GET   https://northeurope4-sphom,HttpClient
2019/04/12   11:15:59.331,verbose,FirstRunDataProvider,FirstExperience is false in the   local storagage
2019/04/12   11:15:59.331,verbose,FirstExperience is false in th,FirstRunDataProvider
2019/04/12   11:15:59.766,verbose,ClientSideWebPartManager,Successfully loaded webpart   manifests.
2019/04/12   11:15:59.766,verbose,Successfully loaded webpart   ma,Application.b6917cb1-93a0-4b97.ClientSideWebPartManager
2019/04/12   11:16:01.624,verbose,ThumbnailUrlGenerator,Requesting for token
2019/04/12   11:16:01.624,verbose,Requesting for   token,Application.b6917cb1-93a0-4b97.ThumbnailUrlGenerator
2019/04/12   11:16:01.625,verbose,ThumbnailUrlGenerator,Oauth token acquired
2019/04/12 11:16:01.625,verbose,Oauth   token acquired,Application.b6917cb1-93a0-4b97.ThumbnailUrlGenerator
2019/04/12   11:16:03.618,verbose,DigestCache,DigestCache: Reusing cached digest.  Expiration: 1770000
2019/04/12   11:16:03.618,verbose,DigestCache: Reusing cached di,DigestCache
2019/04/12   11:16:03.620,verbose,SPHttpClient,POST   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/web/ActivityLogger/LogActivity
2019/04/12 11:16:03.620,verbose,POST   https://aenergia.sharepoi,SPHttpClient
2019/04/12   11:16:03.794,verbose,SignalProvider,ActivityRequestAPI success
2019/04/12   11:16:03.794,verbose,ActivityRequestAPI success,SignalProvider
2019/04/12   11:16:08.608,verbose,SPHttpClient,"GET   https://aenergia.sharepoint.com/_api/v2.1/sites('aenergia.sharepoint.com,%7B3b0c4795-de15-405f-99b4-a3681394cb71%7D,%7B9b66406a-8aa0-49e5-b27e-3d4"
2019/04/12 11:16:08.608,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:16:08.766,verbose,SPHttpClient,"GET   https://aenergia.sharepoint.com/_api/v2.1/sites('aenergia.sharepoint.com,%7B3b0c4795-de15-405f-99b4-a3681394cb71%7D,%7B9b66406a-8aa0-49e5-b27e-3d4"
2019/04/12 11:16:08.766,verbose,GET   https://aenergia.sharepoin,SPHttpClient
2019/04/12   11:16:18.877,verbose,OfficeFeedbackUtility,Initialized and started floodgate   successfully
2019/04/12   11:16:18.877,verbose,Initialized and started floodg,OfficeFeedbackUtility
2019/04/12   11:16:22.098,verbose,SPCanvas,SPCanvas _handleCanvasViewportRendered invoked   with endTime 23995
2019/04/12 11:16:22.098,verbose,SPCanvas   _handleCanvasViewport,SPCanvas
2019/04/12   11:16:22.103,verbose,SPCanvas,SPCanvas _handleCanvasViewportRendered invoked   with endTime 24000
2019/04/12 11:16:22.103,verbose,SPCanvas   _handleCanvasViewport,SPCanvas
2019/04/12   11:16:22.103,verbose,CanvasComponent,CanvasComponent _render() is called
2019/04/12   11:16:22.103,verbose,CanvasComponent _render() is c,CanvasComponent
2019/04/12   11:16:22.107,verbose,ManifestStore,"***Manifest not found for component   id ""5388ac31-7915-4ba6-a021-0f8808dd5784""."
2019/04/12   11:16:22.107,verbose,***Manifest not found for comp,ManifestStore
2019/04/12   11:16:22.107,verbose,ManifestStore,"Requesting manifest with id:   ""5388ac31-7915-4ba6-a021-0f8808dd5784"" and version:   ""undefined"""
2019/04/12   11:16:22.107,verbose,"Requesting manifest with id:   """,ManifestStore
2019/04/12   11:16:22.107,verbose,DigestCache,DigestCache: Reusing cached digest.  Expiration: 1770000
2019/04/12   11:16:22.107,verbose,DigestCache: Reusing cached di,DigestCache
2019/04/12   11:16:22.108,verbose,SPHttpClient,POST   https://aenergia.sharepoint.com/teams/Logistic-Teste/_api/web/GetClientSideComponents
2019/04/12 11:16:22.108,verbose,POST   https://aenergia.sharepoi,SPHttpClient
2019/04/12   11:16:22.229,verbose,SPComponentLoader.loadComponen,"***Loading   component ""5388ac31-7915-4ba6-a021-0f8808dd5784""   (SPCanvasToolbox)."
2019/04/12   11:16:22.229,verbose,"***Loading component   ""5388ac31",SPComponentLoader.loadComponen
2019/04/12   11:16:22.243,verbose,SPComponentLoader.loadComponen,"***Component   ""5388ac31-7915-4ba6-a021-0f8808dd5784""   (SPCanvasToolbox) loaded."
2019/04/12   11:16:22.243,verbose,"***Component   ""5388ac31-7915-4b",SPComponentLoader.loadComponen

`

**Comment by VesaJuvonen** [comment]
Any chance we could get a fiddler trace on the issue? That would be a giving us more details on what included in the traffic between browser and server. Thx.

**Comment by Dangerous-Mind** [comment]
Passing a new app to prod now. Same issue.
The columns, Content types and libraries are created but the app doesn't appear.
No errors on the app.

Were can I send you the Fiddler safely?

**Comment by mcmynn83** [comment]
You can just send it to GrahaMc at my Microsoft.com address.

**Comment by mcmynn83** [comment]
Did you send anything?  I never received anything.

**Comment by Dangerous-Mind** [comment]
Sorry. I didn't yet,

I'm finishing a new application and will install it on production next week.
I'll use it to make a fresh and more controlled test and create a new
fiddler for you.

Do you need the deploy fiddle, the application activation fiddle or the add
app on the page fiddler?

GrahaMc <notifications@github.com> escreveu no dia quinta, 9/05/2019 à(s)
18:38:

**Comment by mcmynn83** [comment]
We need a fiddler trace of when you edit the page and look in the add a webpart dialog and do not see your webpart.  Also, when you do this please also send the ID of the webpart you expect to see.

**Comment by Dangerous-Mind** [comment]
This new app didn't had problems. I've sent you the previous one.

**Comment by GrahamMcMynn** [comment]
@Dangerous-Mind - as per email thread you didn't send a useable trace.  I can't investigate this.  I believe what is most likely happening is the feature does not get activated correctly and therefore the webpart is not shown.  I can only confirm that with more information from a trace.  If you want you can query your features directly and check that your feature is indeed in a good state.  Otherwise, i need  trace.

**Comment by Dangerous-Mind** [comment]
Sorry @GrahamMcMynn, I had some vacations from past years..

> I believe what is most likely happening is the feature does not get activated correctly and therefore the webpart is not shown.

I agree and probably something on the Provision but it's strange because the same app does appear on some sites.

I'll open a new ticket if this appears again.
Thanks for your support
