### ISSUE TITLE
SPFx web part suddenly stopped working

### ISSUE THREAD

**Issue by annasj** [SharePoint/sp-dev-docs#355]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
My SPFx web part suddenly stopped working this week. The page keeps reloading and I get the error message below. I suspect that this happens because RC0 has been rolled out to our tenant? But how can I solve it? According to Release Notes for RC0 I don't have to change any code in my web part, only delete the web part and recreate it. I have tried this, but I still get the same error.

#### Observed Behavior
My SPFx web part was working last week, but this week it suddenly stopped working. I get the following error message:

[SPWebPartErrorCode.ScriptLoadError]:: Det går inte att läsa in skriptresurser för webbdelen 
WebPart.PageInfoWebPart.eb0d6083-1418-4dfc-976d-8bf13536cbd9,Error: Det gick inte att läsa in 
komponenten dfa610aa-2fb3-4458-b194-71b48f8c9b7b (PageInfoWebPart). Ursprungligt fel: Error 
loading https://component-id.invalid/dfa610aa-2fb3-4458-b194-71b48f8c9b7b_0.0.1 på grund av: 
undefined. CALLSTACK:: Error at t [as constructor] 
(https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/
sp-loader_sv-se_263d4bc3ed62ac04a8c9c80a2be01b35.js:60:15897) at new t 
(https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009
/sp-webpart-base_sv-se_031590ad06838e2656fe087dbd2719d6.js:47:21831) at 
Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/
sp-webpart-base_sv-se_031590ad06838e2656fe087dbd2719d6.js:47:22244) at 
https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/
sp-webpart-base_sv-se_031590ad06838e2656fe087dbd2719d6.js:48:206

#### Steps to Reproduce
Navigate to page containing SPFx web part.

**Comment by patmill** [comment]
RC0 has rolled, and it has breaking changes.  Check out the release notes here - https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0

**Comment by annasj** [comment]
According to the release notes I don't have to change the code in my web part, only delete the web part and recreate it. But this did not work. So does that mean that there are changes that I need to do in the code in my web part anyway?

**Comment by patmill** [comment]
Sorry if the RC0 notes were not clear.  There are a ton of breaking change in RC0.  The existing code won't work.

**Comment by manishgarg1** [comment]
Hi @annasj, were you able to get unblocked? is this issue still an open issue?

**Comment by annasj** [comment]
After some code changes it works again.
