### ISSUE TITLE
Error with version 

### ISSUE THREAD

**Issue by oriejiDavid21** [SharePoint/sp-dev-docs#3552]
I am using the latest version of Nodejs 11.11.0 and I can't complete my work, I have an error that says ( "gulp serve" doesn't run on version 11.110 only on version >=8.9.4 but < 9.0.0. 

What should I do?

**Comment by andrewconnell** [comment]
SPFx is only supported with Node.js v8 as listed in the docs here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-developer-tools
