### ISSUE TITLE
The current tenant is not allowed to use this solution

### ISSUE THREAD

**Issue by expiscornovus** [SharePoint/sp-dev-docs#3553]
I am trying to setup Custom Learning with the Provisioning Service as described overhere:
https://docs.microsoft.com/en-us/office365/customlearning/installsitepackage

I have met all the prerequisites, but I am still getting a not allowed error. Am I missing a prerequisite?

There was an unexpected issue. Please try again after a while.
Invalid request, the current tenant is not allowed to use this solution! 

#### Category
- [ x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I add the Custom Learning for Office 365 (CLO365) to my tenant via this interface I expect it will get installed when you used an account that is signed in to the provisioning site:
https://provisioning.sharepointpnp.com/home/details?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239

#### Steps to Reproduce

1. Create a demo environment on demos.microsoft.com
2. Login with the admin account
3. Create a new SharePoint tenant app catalog
4. Go to https://provisioning.sharepointpnp.com/home/details?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239
5. Log in with the admin account (this should be tenant admin and site collection admin of the app catalog)
6. Click the add to your tenant button
 

Thanks for your contribution! Sharing is caring.

**Comment by expiscornovus** [comment]
Btw, just saw on GitHub you can also install it manually. So will try if this is a workaround:
https://github.com/pnp/custom-learning-office-365

**Comment by VesaJuvonen** [comment]
Provisioning service is still in internal testing like noted in the front page and will be out within days rather than weeks... so what you are seeing is as expected. Soon - really soon. Closing this as answered.

**Comment by expiscornovus** [comment]
Thanks for the quick reply, I totally missed the note on the front page. I immediately read the configuration part of it. Sorry about that!
