### ISSUE TITLE
Navigation partial(not full reload) in mobile does not apply ".mobile" class name in the body

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#3554]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

When accessing SharePoint from a mobile, the ".mobile" class is added to the body and when [partial navigation](https://github.com/estruyf/spfx-navigation) (@estruyf) is performed, the ".mobile" class disappears from the body:

![image](https://user-images.githubusercontent.com/33054287/53956987-7d8f3c80-40dd-11e9-94ed-1052e37caaf2.png)

This causes the mobile styles for the placeholder bottom not to apply:

![image](https://user-images.githubusercontent.com/33054287/53956939-58023300-40dd-11e9-9537-c1588a5d6b35.png)

This means that the placeholder bottom has no fixed position.

**Comment by VesaJuvonen** [comment]
As this is a non-dev issue, we cannot, unfortunately, process it through this channel. Can you please report it through the tenant admin support channels. Thx.
