### ISSUE TITLE
How to update office fabric ui react inside generated solution?

### ISSUE THREAD

**Issue by mtosic** [SharePoint/sp-dev-docs#3555]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I want to update Office Fabric React components inside generated Sharepoint Framework solution according to official documentation at:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#office-ui-fabric-react

#### Observed Behavior

I'm using TextField component from Office Fabric React in latest Sharepoint Framework (1.7.1) and onChange event is not firing (onChanged works fine).
I've generated an empty react app and installed latest Office Fabric React UI library and verified that onChange event works fine in TextField.

The problem is that included Office Fabric React UI is older version and maybe doesn't have that function implemented (don't have an easy way to see in documentation what is implemented in each version).

I've tried to update Office Fabric UI package according to official docs:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#office-ui-fabric-react

But after updating solution can't build anymore and throws following errors:
```
[14:27:29] Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,67): error TS1005: ';' expected.
[14:27:29] Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,114): error TS1005: '(' expected.
[14:27:29] Error - [tsc] node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,136): error TS1005: '(' expected.
[14:27:29] Error - 'tsc' sub task errored after 5.79 s
 exited with code 2
```

#### Steps to Reproduce

1. Generate new sharepoint framework solution (all default options, choose react as framework)
2. Update office fabric react package: npm install office-ui-fabric-react
3. (optional) remove fabric ui core package and update styles
npm uninstall @microsoft/sp-office-ui-fabric-core --save
@import '~office-ui-fabric-react/dist/sass/_References.scss';

4. Run your solution: gulp serve

You should get the above errors.

**Comment by andrewconnell** [comment]
What you're trying to do is not recommended/supported. The version of Fabric React included in each SPFx version is what has been tested with the current version of React & SPFx that is available. More current versions of Fabric React can have dependencies on future versions of React that are not supported by SFPx & SPO at this time.
