### ISSUE TITLE
Disk Usage Problem 

### ISSUE THREAD

**Issue by abdollahkahne** [SharePoint/sp-dev-docs#3556]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
I am a learner, so sorry about my questions. Creating a project for working with SharePoint Framework uses my hard at least 0.5 gig each time. does it necessary and normal?!! After Installing nodeJS and using it I lost about 8 gig of my hard. Is something wrong? How can I delete unncessary files if I decide to do? does simple uninstalling of nodeJS free my hard? For every project it download all the dependecies, may I use a centeral place?! does it uses network traffic each time it creates the project?!
Sry about number of question. I am new to these subjects.

Thanks in advance for your comments

**Comment by bcameron1231** [comment]
Yes, there are a lot of dependencies for SharePoint Framework and a lot of files that come with it. This can be mitigated through various options. 

[Pnpm](https://pnpm.js.org/) is a great package manager which will help you save some space on your drive, by only installing the files once.

I would also look into docker as a means of isolating some of these files and not installing them locally on your machine. Take a look at Waldek's blog post https://blog.mastykarz.nl/sharepoint-framework-docker/

**Comment by PopWarner** [comment]
I can concur with @bcameron1231, as I use Docker for my SPFx development. It allows me to avoid installing directly on my hard drive any of the dependencies, such as Node, Gulp, Yeoman, etc. It does install a local "Node Modules" folder for the solution, which can grow in size, although when your done developing, that can easily be deleted and you are back to no drive space other then what Docker uses.

**Comment by abdollahkahne** [comment]
@bcameron1231 @PopWarner Thanks for your comments. Yeah as I found Docker is a good idea but for the next time using (new windows Installation). For now, I have the pnpm option I think. Thanks again
