### ISSUE TITLE
CSOM Error requesting RecycleBin items with type Web

### ISSUE THREAD

**Issue by TypesInCode** [SharePoint/sp-dev-docs#3557]
The property: DeletedDateLocalFormatted was added to the SPRecycleBinItem class which is unable to be serialized when the item is of type SPRecycleBinItemType.Web.  This prevents loading RecycleBin items through CSOM resulting in the error:
"No value was specified for the {0} parameter. Parameter name: web"

Reproduction steps:
- In a SharePoint 2016 environment at least version: 16.0.4588.1000
- Delete a subsite resulting in it going to the Admin recycle bin
- Try to load the recycle bin using JSOM.  The error is visible in the response from the server:
```
var ctx = SP.ClientContext.get_current();
var site = ctx.get_site()
var bin = site.get_recycleBin()
ctx.load(bin)
ctx.executeQueryAsync(function() { console.log("succeeded"); }, function() { console.log("failed") })
```

Stack trace:
   at Microsoft.SharePoint.SPContext.GetContext(SPWeb web)
↵   at Microsoft.SharePoint.Utilities.SPUtility.FormatDate(SPWeb web, DateTime date, SPDateFormat fmt, Boolean toWebLocalTime)
↵   at Microsoft.SharePoint.SPRecycleBinItem.get_DeletedDateLocalFormatted()
↵   at Microsoft.SharePoint.ServerStub.SPRecycleBinItemServerStub.WritePropertiesAsJson(JsonWriter writer, Object target, ProxyContext proxyContext)
↵   at Microsoft.SharePoint.Client.ServerStub.WriteAsJson(JsonWriter writer, Object obj, ClientObjectQuery objectQuery, ProxyContext proxyContext)
↵   at Microsoft.SharePoint.Client.ServerStub.WriteAsJsonWithMonitoredScope(JsonWriter writer, Object value, ClientObjectQuery objectQuery, ProxyContext proxyContext, MonitoredScopeType scopeType)
↵   at Microsoft.SharePoint.Client.ServerStub.WriteChildItems(JsonWriter writer, Object obj, ClientObjectQuery objectQuery, ProxyContext proxyContext)
↵   at Microsoft.SharePoint.Client.ServerStub.WriteAsJson(JsonWriter writer, Object obj, ClientObjectQuery objectQuery, ProxyContext proxyContext)
↵   at Microsoft.SharePoint.Client.ServerStub.WriteAsJsonWithMonitoredScope(JsonWriter writer, Object value, ClientObjectQuery objectQuery, ProxyContext proxyContext, MonitoredScopeType scopeType)
↵   at Microsoft.SharePoint.Client.ClientMethodsProcessor.WriteQueryResults(Object obj, ClientObjectQuery objQuery)
↵   at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessQuery(XmlElement xe)
↵   at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessStatements(XmlNode xe)
↵   at Microsoft.SharePoint.Client.ClientMethodsProcessor.Process()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8650b8a-3333-1403-6a7f-e322cd03ec29
* Version Independent ID: 447c926c-6855-d98d-1d70-c31cad93a161
* Content: [SPRecycleBinItem Class (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.sprecyclebinitem?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRecycleBinItem.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRecycleBinItem.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by mrstevec** [comment]
It's been over a year. Are there any updates on status or fixes?

**Comment by TypesInCode** [comment]
I'm also interested in an update on this.  Thanks.
