### ISSUE TITLE
Non-reactive Apply button not visible when editing custom PropertyPane control

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#356]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
I started implementing a custom property pane control for my webpart toolpane.
When setting `disableReactivePropertyChanges` to `false`, everything works fine, and my custom property nicely saved the edited property value to the webpart.

However, when setting `disableReactivePropertyChanges` to `true`, the Apply button is not enabled when editing the property through the custom pane.

When editing another (default type) property together with the custom toolpane one, the property is also saved correctly when clicking the (then available) Apply button.

#### Steps to Reproduce
My `getPropertyPaneConfiguration` implementation looks like this:
```
  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.MainGroupName,
              groupFields: [
                new TilesConfigurationControl("tilesConfiguration", {
                  initialValue: this.properties.tilesConfiguration,
                  openConfigDialogButtonLabel: "Open Dialog",
                  openConfigDialogButtonDescription: "Open the dialog to configure your tiles.",
                  onConfigurationChanged: (propertyPath: string, newValue: any): void => {
                    const oldValue: any = get(this.properties, propertyPath);
                    update(this.properties, propertyPath, (): any => { return newValue; });

                    this.onPropertyPaneFieldChanged(propertyPath, oldValue, newValue);
                  }
                })
              ]
            }
          ]
        }
      ]
    };
  }
```

If any more code is needed for it to make sense, let me know :)

**Comment by patmill** [comment]
Thanks for the feedback.  We've noted the issue and are working on a solution.  Basically, we need to incorporate 2 things.
1 - The custom control needs to be able to notify the system when a property has changed (I see that you have tried to do this yourself with the call to .onPropertyPanelFieldChanged(), but that's not quite the way it will work)
2 - Have your webpart be notified that apply has been clicked, so that you can update the webpart property bag with the correct values.

**Comment by NickSevens** [comment]
@patmill Thanks for confirming. Reactive updates will do for now ;)

**Comment by manishgarg1** [comment]
Fix is in the works.

**Comment by srideshpande** [comment]
Hello @NickSevens 

Glad that you brought this up. I apologize for the delay. The change has been made to resolve this issue. You will be getting it in the next release. The change we have made is, the `onRender` prop on the custom field will now have a `changeCallback` method passed in from the framework. This should be invoked if you want the framework to know that something has changed within the custom field. This will trigger the regular property pane field change flow.

This is how the `onRender` prop will look now on the `IPropertyPaneCustomFieldProps`

     /**
      * This API will be called once the custom field is mounted on the host element.
      *
      * @param domElement - DOM element on which the custom control needs to be mounted.
      * @param context (optional) - Instance specific context. This context was passed in the constructor.
      * @param changeCallback (optional) - Callback called when a field changes within the custom field.
      *  This will allow the property pane to be aware of the change and act accordingly.
      *  @param targetProperty (optional) - associated target property from the properties bag.
      *    if not provided then a custom value which is unique at the custom field level is assigned,
      *    which will be in the form of '__CustomField_<key provided when the custom field is created>'.
      *  @param newValue (optional) - new value of the property.
      *    newValue is ignored if targetProperty is not specified.
      */
     /* tslint:disable:no-any */
     onRender: (
       domElement: HTMLElement,
       context?: any,
       changeCallback?: (targetProperty?: string, newValue?: any) => void) => void;

So if a developer calls the `changeCallback` appropriately when something changes within the custom field,  then the property pane knows that something has changed and if it is non-reactive it accordingly enables the `Apply` button.

Please let me know if you still need any more details in this regard.

I am closing the issue for now, but please feel free to re-open it if you still see the issue after the next drop.

Thanks,
Srikanth

**Comment by estruyf** [comment]
It seems that this is not added in the next drop (v1.1.3). Is this postponed?
