### ISSUE TITLE
AadHttpClient calls not working in IE 10, IE 11

### ISSUE THREAD

**Issue by narulasrinivas** [SharePoint/sp-dev-docs#3562]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm using SPFx 1.7 version and should fetch data from azure ad authenticated web api using AadHttpClient and display in table format using Chrome and IE versions.

I followed every step mentioned in the below link in the context of webapp.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi

#### Observed Behavior

SPFx webpart is able to fetch data properly in Chrome, but **NOT in IE 11, IE 10** version.

I've attached one screen shot of the console log, which has error in sp-http-adal.js file.
![ie-workbench issue](https://user-images.githubusercontent.com/2491903/54035274-e3002d80-41b0-11e9-9044-6a4237ec2c2a.JPG)

![ie-workbench issue -1](https://user-images.githubusercontent.com/2491903/54035371-2490d880-41b1-11e9-9560-36401c33ca88.JPG)

#### Steps to Reproduce

Here is the code which I'm using to get the data 

`EndPoint : https://test.azurewebsites.net/api/v1/reports/getdata`

```
  public getServerData(APIENDPOINT: string, ErrorMessage: string): Promise<ITest[]> {
    return new Promise<ITest[]>((resolve, reject) => {
      console.log('getServerData.......');
      this.aadHttpClientFactory
        .getClient(TEST_RESOURCE_ENDPOINT_URI)
        .then((aadHttpclient: AadHttpClient) => {
          const endpoint: string = `${TEST_ENDPOINT_URI + APIENDPOINT}`;
          console.log('endpoint...->'+endpoint);
          aadHttpclient.get(endpoint, AadHttpClient.configurations.v1,)
            .then((rawresponse: HttpClientResponse) => {
              if (rawresponse.status === 200) {
                console.table(rawresponse);
                return rawresponse.json();
              } else {
                throw new Error(`${ErrorMessage}`);
              }
            })
            .then((jsonResponse: ITest[]) => {
              console.log(jsonResponse);
              resolve(jsonResponse);
            })
            .catch((error) => {
              reject(error);
            });
        });
    });
  }

```
Please help me, if I need to alter my code or settings for the code to work with IE .

**Comment by SPFxDeveloper** [comment]
I have the same problem.

Please if anyone knows how to solve it please comment soon, thanks

**Comment by narulasrinivas** [comment]
@SPFxDeveloper , @andrewconnell , @wobba 

The issue is with **console.table** function. It was not allowing to process the success request as it is  not supported in IE browsers. Thanks alot for your help.

```
 public getServerData(APIENDPOINT: string, ErrorMessage: string): Promise<ITest[]> {
    return new Promise<ITest[]>((resolve, reject) => {
      console.log('getServerData.......');
      this.aadHttpClientFactory
        .getClient(TEST_RESOURCE_ENDPOINT_URI)
        .then((aadHttpclient: AadHttpClient) => {
          const endpoint: string = `${TEST_ENDPOINT_URI + APIENDPOINT}`;
          console.log('endpoint...->'+endpoint);
          aadHttpclient.get(endpoint, AadHttpClient.configurations.v1,)
            .then((rawresponse: HttpClientResponse) => {
              if (rawresponse.status === 200) {
               //console.table(rawresponse); //console.table function doesn't support IE browsers.
                return rawresponse.json();
              } else {
                throw new Error(`${ErrorMessage}`);
              }
            })
            .then((jsonResponse: ITest[]) => {
              console.log(jsonResponse);
              resolve(jsonResponse);
            })
            .catch((error) => {
              reject(error);
            });
        });
    });
  }
```

I'm going to close this request.

**Comment by wobba** [comment]
@narulasrinivas `console` calls is basically a no-no with IE11 and should be avoided. Better to use SPFx or PnP logging.

**Comment by andrewconnell** [comment]
@wobba well... better to avoid IE11 ;)

**Comment by wobba** [comment]
@andrewconnell always - but unfortunately not something one can control usually :(
