### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by bigpix2000** [SharePoint/sp-dev-docs#3563]
The dates on these items are way out of date with the newest item from January 2018.  The Issue Links might be more appropriate but even if so, the other information here that is no longer in effect needs to be removed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940aa865-bc19-0acf-0b06-4abd2c9e8111
* Version Independent ID: ca40c15f-9548-b74b-3ba1-0186cfa8025b
* Content: [SharePoint Framework known issues and frequently asked questions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions#feedback)
* Content Source: [docs/spfx/known-issues-and-common-questions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/known-issues-and-common-questions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I don't see what's wrong with this page... it lists a few things people have asked about with answers. that doesn't make them obsolete and should be removed.
