### ISSUE TITLE
Requesting AJAX Post using an elevated Credential

### ISSUE THREAD

**Issue by abdollahkahne** [SharePoint/sp-dev-docs#3565]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [X] Additional article idea

#### Expected or Desired Behavior

I always read at the web and the books that sharepoint Framework webpart runs at the context of current user.  As an investigation to RequestInit Interface (as parent (better to say Ancestor) of SPHTTPClientOptions) I see the following properties today. Who knows about the credentials here?! Thanks in advance.

```
interface RequestInit {
    body?: BodyInit | null;
    cache?: RequestCache;
    credentials?: RequestCredentials;
    headers?: HeadersInit;
    integrity?: string;
    keepalive?: boolean;
    method?: string;
    mode?: RequestMode;
    redirect?: RequestRedirect;
    referrer?: string;
    referrerPolicy?: ReferrerPolicy;
    signal?: AbortSignal | null;
    window?: any;
}
```

**Comment by andrewconnell** [comment]
it is not possible to impersonate a different user & thus, elevate credentials, with SPFx. SPFx is 100% client-side & impersonation is not possible.

You are likely looking at the CSOM which runs server-side...
