### ISSUE TITLE
Footer reappears after turning off in user interface.

### ISSUE THREAD

**Issue by gdavisMDA** [SharePoint/sp-dev-docs#3571]
On our Communication hub site, I can slide the footer visibility off and save it. It will disappear for 24hrs or so then come back. Slider is back on. 
Not happy with Microsoft pushing users in corporate situations to "create their own." At this point we want control of users creating sites and don't want this ad on the screen. I don't want to have to turn this off every day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://docs.microsoft.com/en-us/sharepoint/dev/features/site-footer#feedback)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/site-footer.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by MRuimerman** [comment]
We have this issue as well. Just opened a support case @ Microsoft for this.

**Comment by gdavisMDA** [comment]
Would be nice to see some action on this. I'm having to remove this every one or two days. I've tried both the gear/Change the Look/footer slider and using a command in PowerShell. Both remove it, but it comes back the next day.
Help PLEASE!

**Comment by DRamalho92** [comment]
We have this issue too. Currently running the PowerShell to hide footer each day.

**Comment by gdavisMDA** [comment]
It seems that it has been fixed. I'm not sure if it was intentional or not.
