### ISSUE TITLE
Switching between libraries : Library Settings link not getting updated 

### ISSUE THREAD

**Issue by anoopt** [SharePoint/sp-dev-docs#3572]
Thank you for providing the modern list and library experience in SharePoint. I enjoy using it.

Recently I faced an issue when I switched/navigated between libraries. I have 2 document libraries in a modern team site - "Library_1" and "Library_2". When I navigate from the Library_1 to Library_2 and click on "Library settings" from the cog, the settings page that loads is that of Library_1 and not of Library_2. 

This can be bit confusing as "you think" you are editing the settings of the library that you want however, you are not. I have seen this behavior in the modern library view in a couple of tenants. Can you please address this?

If this is not an issue occurring in other tenants then my apologies for reporting this. 
If this is not the right page to raise this issue, please let me know where do I log this?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c41e533-8210-890c-05f9-a11a2c98306c
* Version Independent ID: 919463a5-d2a8-5048-dc8c-b457f4cf1c19
* Content: [Modernize the user interface](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface)
* Content Source: [docs/transform/modernize-userinterface.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by akshay-randive** [comment]
I have been facing this issue from last few days too with more than one tenants.

**Comment by jansenbe** [comment]
@anoopt / @akshay-randive : if this still an issue for you then please open a support ticket.

**Comment by anoopt** [comment]
@jansenbe - Not facing this issue now. So closing it.
