### ISSUE TITLE
Root level sites currently are not able to be modernized

### ISSUE THREAD

**Issue by PaintrockConsulting** [SharePoint/sp-dev-docs#3574]
Please update the readme with a notice at the introduction stating that root level sites currently are not able to be modernized.  

Currently the only way for an admin to come to this determination is to read through and attempt all of the site modernization efforts and fail, by being guided to: 

1. Connect to O365 through site settings failure ([link](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-classic-sites)),
2. Scripting Set-SPOSiteOffice365Group and failing ([link](https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Modernize-your-SharePoint-team-sites-by-connecting-them-to-new/ba-p/201371)),
3. Surrendering to the Modernization Scanner, which first requires:
4. Configuring an Azure/SP App client and ID, 
5. ONLY THEN to receive the O365 Group Connection Readiness.xlsx file, filtering to your root site, and seeing the */isTenantRootSite and the message that "the root site of your tenant can not be group connected".  

This really needs to be much more prominent at the start of all the Modernization documentation - it currently isn't captured anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d89003-27e6-a443-e99b-5afd8f758b83
* Version Independent ID: 0ca22c7e-e6c0-0c66-3ce9-55a3f663d3c4
* Content: [Modernize your classic SharePoint sites](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-classic-sites#feedback)
* Content Source: [docs/transform/modernize-classic-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-classic-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by loverdeg-ep** [comment]
@sparkitect any path to just deleting the "classic" root site and replacing it with a Communication Site?

**Comment by sparkitect** [comment]
@loverdeg-ep I can't recommend that option. Instead, use [Invoke-SPOSiteSwap](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps)

**Comment by LouFarho** [comment]
Plus one on the Site Swap. The enable comm site command has been delayed. I have a feeling it will be dropped. The swap is a great alternative. Allows you to rebuild and then swap into the root. I have completed this with a Communication site.

**Comment by PaintrockConsulting** [comment]
Invoke-SPOSiteSwap may be as close as we're going to get, based on my reading of the roadmap.

**Comment by jansenbe** [comment]
Invoke-SPOSiteSwap is indeed a good model to get a modern root site collection. When you do want to keep your existing root web and it's a team site (so no publishing enabled) you could consider modernizing it's wiki and web part pages. @paintrockConsulting: I'll add a note in the group connection section to spell out that the root site collection can not be group connected.

**Comment by PaintrockConsulting** [comment]
Thank you, @jansenbe; I'll close the comment thread.
