### ISSUE TITLE
MS Teams WebPart integration is not working

### ISSUE THREAD

**Issue by VKAlwaysWin** [SharePoint/sp-dev-docs#3576]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> Web part should be loaded.

#### Observed Behavior

> Error details: Error: ***Error initializing application. Error: Error: ***Error initializing application. Error: TypeError: Cannot read property 'groupColor' of undefined

#### Steps to Reproduce

> Follow all steps from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab
> "Notice how you can parametrize the tab instance based on the exposed properties. Click Save". You won't notice that because of bug with initialization.

![image](https://user-images.githubusercontent.com/14337164/54182866-5a80d600-44ab-11e9-87b3-cb703adba8c8.png)

**Comment by mhintner** [comment]
Same here - different tenants but the same error. Unfortunately I'm about to demonstrate this on a conference tomorrow - worst timing for this error ;-)

**Comment by VesaJuvonen** [comment]
That's really unfortunate timing and yes - this is related most likely on the 1.8 release, but investigating exact details internally. TBH - I doubt that the situation will be changed by tomorrow.

**Comment by AJIXuMuK** [comment]
I experienced the same yesterday during the day, but it got fixed.

**Comment by VesaJuvonen** [comment]
This should have been now fully fixed after the 1.8 deployment. It was a version conflict before go-live. Can we confirm that we are good? Thx.

**Comment by VKAlwaysWin** [comment]
@VesaJuvonen I will check and let you know. Thank you very much.

**Comment by VKAlwaysWin** [comment]
@VesaJuvonen wow. It is working even better. Thank you very much, closing this issue.
