### ISSUE TITLE
Get-PnPTenantSite throws error

### ISSUE THREAD

**Issue by LouFarho** [SharePoint/sp-dev-docs#3578]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Command should return site or sites
Please note Get-SPOSite throws similar error

#### Observed Behavior
Get-PnPTenantSite -Detailed
Get-PnPTenantSite : The type of data at position 1678 is different than the one expected.
At line:1 char:1
+ Get-PnPTenantSite -Detailed
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenantSite], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.GetTenantSite

#### Steps to Reproduce
Execute command 
Get-PnPTenantSite -Detailed

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
This seems related to the PnP Core PowerShell component... best to submit this question to that specific repo's issue list: https://github.com/SharePoint/PnP-Sites-Core

**Comment by andrewconnell** [comment]
FYI... see [this comment](https://github.com/SharePoint/sp-dev-docs/issues/3577#issuecomment-472160143) in #3577 as it might be related to this...

**Comment by JoaoAlmeidaPoa** [comment]
No @andrewconnell  I can't get the command Get-PnPTenantSite because i'm not working with a tenant site, I worked with Get-PnPProvisioningTemplate because I need to get a template site of a web not from sitecollection

**Comment by andrewconnell** [comment]
ok... wasn't sure... still think the PnP Sites Core repo would be best place to post the Q though... unless I'm missing something else.

**Comment by JoaoAlmeidaPoa** [comment]
Ok, I already try there, but without a response.
the error occurs here
Microsoft.SharePoint.Client.JsonReader.ReadGuid()

full trace
Message          : The type of data at position 1144 is different than the one expected.
Stacktrace       :    em Microsoft.SharePoint.Client.JsonReader.ReadGuid()
                      em Microsoft.SharePoint.Client.Site.InitOnePropertyFromJson(String peekedName, JsonReader reader)
                      em Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
                      em Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      em Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      em Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
                      em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      em Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
                      em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      em Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
                      em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      em Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
                      em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      em Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
                      em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      em Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      em Microsoft.SharePoint.Client.ClientContextExtensions.GetSiteCollectionContext(ClientRuntimeContext clientContext)
                      em OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractFields(Web web, List siteList, List`1 contentTypeFields, ListInstance list, List`1 lists,
                   ProvisioningTemplateCreationInformation creationInfo, ProvisioningTemplate template)
                      em OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation
                   creationInfo)
                      em OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      em SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName)
                      em SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate.ExecuteCmdlet()
                      em SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1
