### ISSUE TITLE
Modern instead of classic site

### ISSUE THREAD

**Issue by DeanGross** [SharePoint/sp-dev-docs#3579]
Can we do this with a modern site instead of a classic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037842f6-772f-456d-6f44-0c46939bcddd
* Version Independent ID: 608ab68a-92a1-ca34-5ce6-2ae71691f6e6
* Content: [Set up your Office 365 tenant](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant)
* Content Source: [docs/spfx/set-up-your-developer-tenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yes... a the **Developer Site** template is not required. You can use any site collection template.
