### ISSUE TITLE
Get-PnPProvisioningTemplate : The type of data at position 1144 is different than the one expected

### ISSUE THREAD

**Issue by JoaoAlmeidaPoa** [SharePoint/sp-dev-docs#3580]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Steps to Reproduce
$userLogin = "xxxx@xxxx.onmicrosoft.com"
$cred =  Get-Credential -UserName $userLogin -Message "Login PNP"

$WebURL = "https://xxxx.sharepoint.com/sites/xxx/"
Connect-PnPOnline -Url $WebURL -Credentials $cred
Get-PnPContext
$teamSiteUrl = New-PnPWeb -Title "Projeto 06" -Url "projeto06" -Description "Projeto 05" -Locale 1046 -Template "STS#3" -ErrorAction Stop

Connect-PnPOnline -Url $teamSiteUrl.Url -Credentials $cred
Get-PnPContext

Get-PnPProvisioningTemplate -Out "C:\scripts\template-demo13-projeto06.xml" -Handlers "Fields,ContentTypes,Lists,Navigation" -ExcludeHandlers "SiteSecurity,TermGroups" -Force 

#### Expected Behavior

Create a XML file with the template of site

**Comment by andrewconnell** [comment]
This seems related to the PnP Core PowerShell component... best to submit this question to that specific repo's issue list: https://github.com/SharePoint/PnP-Sites-Core

**Comment by andrewconnell** [comment]
FYI... see [this comment](https://github.com/SharePoint/sp-dev-docs/issues/3577#issuecomment-472160143) in #3577 as it might be related to this...

**Comment by JoaoAlmeidaPoa** [comment]
No @andrewconnell I can't get the command Get-PnPTenantSite because i'm not working with a tenant site, I worked with Get-PnPProvisioningTemplate because I need to get a template site of a web not from sitecollection
