### ISSUE TITLE
Contoso Team Site provisioned on SharePoint Provisioning Service - invalid URL and author name in news article on home page 

### ISSUE THREAD

**Issue by panjkov** [SharePoint/sp-dev-docs#3581]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

News articles on home page should have valid URLs and proper author name

#### Observed Behavior
Urls for news articles contain HTML encoded tokens sites/%7Bhosturl%7D%7Bsite%7D/SitePages/Contoso-Eagle-press-release-and-product-specs.aspx and "MOD Administrator" as author, instead of correct URL and existing user in tenant
#### Steps to Reproduce
Submit a new request on SharePoint Provisioning Service with template "Contoso Team site", and after site is created news articles in news web part on home page will point to invalid URL and have "MOD Administrator" as author, even if MOD Administrator does not exist in the tenant.
![image](https://user-images.githubusercontent.com/8397641/54220072-dbae8c00-44f0-11e9-9be6-2c24c9821cd2.png)

**Comment by PaoloPia** [comment]
Hi @panjkov,
It should be now fixed. Give it a try please. Thanks for your feedback.
