### ISSUE TITLE
navigationInfo not ported over to this.context.pageContext, relying on legacyPageContext currently

### ISSUE THREAD

**Issue by DA-Mena** [SharePoint/sp-dev-docs#3587]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using this.context.pageContext I should expect to have a navigation info in new pageContext object instead of relying on this.context.pageContext.legacyPageContext.navigationInfo

#### Observed Behavior

this.context.pageContext.legacyPageContext.navigationInfo is the only object that has navigation info

#### Steps to Reproduce

In an SPFx solution, one would need to use this.context.pageContext.legacyPageContext.navigationInfo to get any navigation info.

**Comment by VesaJuvonen** [comment]
Good request, but should be routed through UserVoice as this is a new feature.
