### ISSUE TITLE
Does SharePoint 2019 Support Tenant Wide Deployment of SPFx Extension?

### ISSUE THREAD

**Issue by fengzhenqiong** [SharePoint/sp-dev-docs#3590]
#### Category
-[x] Question

#### Expected or Desired Behavior
I noticed that SharePoint **2019 On Premise** supports SPFx Extension and created a demo and it worked just fine. However, I'm not quite sure whether SP 2019 supports the **Tenant Wide Deployment** or not. I did not find any documentation about this.

I noticed that there IS the "Make this solution available to all sites in your organization" option when uploading app to App Catalog and when I check this option I can not add the app in my site, this seems correct.

According [this documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-scoped-deployment), if this option is checked, the SPFx Extension will be loaded automatically in modern sites in the tenant. But this doc is about SPO.

So my question is whether Tenant Wide Deployment supported in SP 2019 On Premise? If it does, how to enable it?

#### Environment
I have **SP 2019 On Premise without any CU** installed.
My demo is an **Application Customizer** and following is my .yo-rc.json file:
{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "onprem19",
    "version": "1.7.1",
    "libraryName": "sp-2019-extension",
    "libraryId": "793761e6-ae80-4565-9a34-b4bb818cda9e",
    "packageManager": "npm",
    "componentType": "extension",
    "extensionType": "ApplicationCustomizer"
  }
}

Thanks in advance for any help.

**Comment by andrewconnell** [comment]
No, tenant wide deployment was introduced late in 2018. It is only available in SPO. 

SharePoint 2019 is a snapshot of what SPO was in January of 2018.

**Comment by fengzhenqiong** [comment]
So what does the option **"Make this solution available to all sites in your organization"** mean in SP 2019 On Prem SPFx Extension deployment?

As this option will hide the solution from being added in site collection's **Add an App** command. Maybe this option should never be used in SP 2019 On Prem? Am I correct?

**Comment by andrewconnell** [comment]
That's not the same thing. That option will install the SharePoint package to all site collections in the tenant, _but it will not activate any Features_. Features are used to provision extensions, hence the `./sharepoint/assets/elements.xml` file in every extension project that contains a `<CustomAction>` element. SharePoint has always taken the stance that it will not mass add content... which is exactly what that would do if it activated features in _n_ number of site collections in your tenant.

Tenant scoped deployment gets around this limitation and further allows you to set the properties on the extensions and apply filters for what sites (via templates) and lists (via templates) the extension can be applied to.

**Comment by fengzhenqiong** [comment]
> That's not the same thing. That option will install the SharePoint package to all site collections in the tenant, _but it will not activate any Features_. Features are used to provision extensions, hence the `./sharepoint/assets/elements.xml` file in every extension project that contains a `<CustomAction>` element. SharePoint has always taken the stance that it will not mass add content... which is exactly what that would do if it activated features in _n_ number of site collections in your tenant.
> 
> Tenant scoped deployment gets around this limitation and further allows you to set the properties on the extensions and apply filters for what sites (via templates) and lists (via templates) the extension can be applied to.

Thanks for the explanation, I understand the tenant scoped deployment in SPO now.

However, I still don't understand the **"Make this solution available to all sites in your organization"** option in **SP 2019 app deployment** very well. What does this options do?

For now, I noticed that if I **leave this option unchecked** I can add the app in each site and the app will work just fine.

But if I **check this option** during the upload and deployment, I can not see the app in the Add an App page, and the app's code will not be executed.

**Comment by andrewconnell** [comment]
@fengzhenqiong said:
> However, I still don't understand the "Make this solution available to all sites in your organization" option in SP 2019 app deployment very well. What does this options do?
> But if I check this option during the upload and deployment, I can not see the app in the Add an App page, and the app's code will not be executed.

Right... now try to go add a web part that was included in the package... it will show up in the toolbox. When you have the option checked, it effectively automatically installs it in every single site collection, so there's no need to show it when you go to add a new app.

**Comment by fengzhenqiong** [comment]
> Right... now try to go add a web part that was included in the package... it will show up in the toolbox. When you have the option checked, it effectively automatically installs it in every single site collection, so there's no need to show it when you go to add a new app.

Yup, tried that and it did work for WebParts. So actually that option in SP 2019 does nothing with Extensions nor Tenant Scoped Deployment, and only works for WebPart?
@andrewconnell

**Comment by andrewconnell** [comment]
Correct

**Comment by mhazebroucq** [comment]
@andrewconnell How can I automatically deploy and activate a SPFx extension on all site collections of a web application.
I cannot visit each site to add an app to activate the feature.
Please, tell me there is another solution...

**Comment by fengzhenqiong** [comment]
> @andrewconnell How can I automatically deploy and activate a SPFx extension on all site collections of a web application.
> I cannot visit each site to add an app to activate the feature.
> Please, tell me there is another solution...

For SPO, you can use the **tenant wide deployment**. For SP OnPrem, I think you can't. What you can do for **OnPrem** is turn on that **tenant wide deployment** option and use **Web Part**. And the Web Part will be available in all sites(in the same web application) when you edit page to add web part.

**Comment by mhazebroucq** [comment]
@fengzhenqiong I continued to look for a solution to globally deploy an SPFx extension.
Using a PS1 script you can do it:
`
function InstallSpfxExtension
{

param(
		[string]$FeatureName,
		[string]$WebAppUrl,
		[string]$UserName,
		[string]$Password
	)
	
	if(-not($FeatureName)) { Throw "You must supply a value for -FeatureName" }
	if(-not($WebAppUrl)) { Throw "You must supply a value for -WebAppUrl" }
	if(-not($UserName)) { Throw "You must supply a value for -UserName" }
	if(-not($Password)) { Throw "You must supply a value for -Password" }
	
	#Get all Site collections
	$SiteColl = Get-SPWebApplication $WebAppUrl | Get-SPSite -Limit All 
	#Target Feature to Activate

	$encpassword = convertto-securestring -String $Password -AsPlainText -Force
	$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $encpassword

	ForEach($Site in $SiteColl)
	{
		#Connect ot SharePoint with PNP
		Connect-PnPOnline  -Url $Site.Url -Credentials $cred

		$FeatureToActivate =  Get-PnPApp  | Where {$_.Title -eq $featureName}
		if($FeatureToActivate -eq $null){
			throw "Feature not found in appCalalog";
			exit;
		}
		$appCatalogVersion = $FeatureToActivate.AppCatalogVersion.ToString();
		$appInstalledVersion = if($FeatureToActivate.InstalledVersion -ne $null) {$FeatureToActivate.InstalledVersion.ToString()} else {""}

		if($appInstalledVersion -eq "")
		{
			Install-PnPApp -Identity $FeatureToActivate.Id -Scope tenant
			Write-Host "Activated Feature on "$Site.Url
		}
		elseif($appInstalledVersion -eq $appCatalogVersion)
		{
			Write-Host "Feature already up to date on "$Site.Url".";
		}
		else
		{
			Update-PnPApp -Identity $FeatureToActivate.id.Guid
			Write-Host "Updated Feature on "$Site.Url" from v$appInstalledVersion to $appCatalogVersion";
		}
		#pause;
	}

}
`

This only an exemple. Here the extension will be searched into the Global app catalog and deployedon all site collections of the webapp specified as an argument.

If it can help somebody ...

**Comment by fengzhenqiong** [comment]
@mhazebroucq 
surely you can achieve this using a standalone tool/script, but this is another different story from Tenant Wide Deployment. you need to remember to uninstall the app from all the sites before removing it from app catalog.
Anyway, any solution fulfilling your request will be A SOLUTION. :)
