### ISSUE TITLE
Blank screen caused by loadTheme of Office Fabric starting 2019-03-12

### ISSUE THREAD

**Issue by coreyroth** [SharePoint/sp-dev-docs#3593]
We have several SPFx web parts in multiple solutions that use loadTheme from Office Fabric with a custom color palette.  Starting yesterday, we started having issues reported that our pages were showing up as blank.  The page renders and then nothing but the suite bar is shown.  

This issue started on the afternoon of 2019-03-12 and affects multiple tenants for us.

Looking at the console, we see the following error:

sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920 TypeError: Cannot read property 'roundedCorner2' of undefined
    at C (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:91)
    at Wn (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)
    at u (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)
    at sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920
    at t.render (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:91)
    at t.e.(/sites/DigitalIndex/SitePages/anonymous function) [as render] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-01.015/sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920:67795)
    at Dn (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)
    at Mn (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)
    at zn (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)
    at Zn (sp-pages-assembly_en-us_1ba58d40502a1529520e7281a1c23097.js:920)

Removing the call to loadTheme allows the page to render successfully.

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Page should render.

#### Observed Behavior

See images in the links below.
[Image showing Issue](https://upzoga.dm.files.1drv.com/y4mhDYjryTqXn2tdB_GAqMtQZ6X7pt0BjVnZqERVcLH8VxMJn6RzMJ1cDD4VstiT6e4IQLxT-ZEr-soz_QCnjwCp6WSy9D-nhYXp9vSaH5K3wVvlfY8UH3W6RNZmq375nGaW8i_liByZpaR9_ZR-YGSYoHhfeqcsOtPt2DRmSHpD7nyvwS1fggBV1RIvQukmHX8?width=1024&height=760&cropmode=none)

[Image showing no issue with code removed](https://upx1qw.dm.files.1drv.com/y4mULYf3hvJTs2NyPoIyvZb72DBJ1tHd4Pf8iVFcc_ACTXhPbfgr0ZUtqXZ4x1G_f-wMnuq8SRY2ZbcrRD_TfnqOhQruAwpQeN2DJBGq8NEthKBJqJm7uzUv3qleg-1bA268ILmxrTp3S-Xu5Q_s4e99pBreEDpA7W0UOAbDnsTPOhQLgChunyoe6koSvZqxkIj?width=1024&height=762&cropmode=none)

#### Steps to Reproduce

Add a call to your web part with loadTheme such as the snippet below:

`loadTheme({
      palette: {
        themePrimary: '#ee1100',
        themeLighterAlt: '#ff1a08',
        themeLighter: '#ff3222',
        themeLight: '#ff1a08',
        themeTertiary: '#71afe5',
        themeSecondary: '#2b88d8',
        themeDarkAlt: '#d50f00',
        themeDark: '#d50f00',
        themeDarker: '#bb0d00',
        neutralLighterAlt: '#f8f8f8',
        neutralLighter: '#f4f4f4',
        neutralLight: '#eaeaea',
        neutralQuaternaryAlt: '#dadada',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c8c8',
        neutralTertiary: '#c2c2c2',
        neutralSecondary: '#858585',
        neutralPrimaryAlt: '#4b4b4b',
        neutralPrimary: '#333333',
        neutralDark: '#272727',
        black: '#1d1d1d',
        white: '#ffffff',
      }
    });`

You may also see it caused in the repo below.
[Repo](https://github.com/coreyroth/OfficeFabricLoadThemeIssue/blob/master/README.md)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by Pekes317** [comment]
I just wanted to add that It seems to be an issue with Our tenant as well. On the modern pages. We've also noticed that random color changes occurred on other pages that didn't have SPFx webparts on them be theme to the default blue. Wonder if they are connected in some way. Thank you.

**Comment by gmparky** [comment]
I just wanted to add we are also having this issue and it's killed our company portal

**Comment by Promhize** [comment]
It's caused by the newer 6.x versions of ui-fabric which SharePoint online now uses. You need to upgrade to SharePoint Framework 1.8.0 or 😬patch the createTheme function in `node_modules\@uifabric\styling\lib\styles\theme.js`; add this to the object literal that it returns:
```javascript
effects: { 
  elevation4: "0 0 5px 0 rgba(0,0,0,.4)", 
  elevation8: "0 0 5px 0 rgba(0,0,0,.4)", 
  elevation16: "0 0 5px 0 rgba(0,0,0,.4)", 
  elevation64: "0 0 5px 0 rgba(0,0,0,.4)", 
  roundedCorner2: "0px" 
},
spacing: { 
  l1: "20px", 
  l2: "32px", 
  m: "16px", 
  s1: "8px", 
  s2: "4px" 
}

```
Then rebuild and redeploy your webpart

**Comment by gmparky** [comment]
Thanks that worked a Treat

**Comment by mikeschaefer** [comment]
The 1.8 framework I was on didn't support fabric 6 either, had to follow instructions here:

http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2019/03/14/spfx-1-8-now-support-office-fabric-react-6-156-0.aspx

**Comment by TomasNielsen** [comment]
We ran into the same problem, following Promhize's suggestion solved it for us.

**Comment by gmparky** [comment]
I have been advised MS has a fix that is going through roll out but not sure when we will actually see it.

**Comment by srideshpande** [comment]
Hello Everyone,

Thanks for the patience. This issue should now be fixed. The fix is also rolled out to all the production tenants. So, can you please re-try and let us know, if you still see the issue?

For now, I am closing the issue, but please feel free to re-open it, if the issue persists.

Thanks,
Srikanth

**Comment by gmparky** [comment]
I am still having the same issue both in our Preview Tenant and our Live Tenant

**Comment by srideshpande** [comment]
Sorry for the confusion. I saw that too. I was too early to say that the fix rolled out into production. It's in our internal rollout cadence. I will update this thread as I see that the bits are in the production. Should be in a week or so.

Sorry again for the confusion.

**Comment by andrewconnell** [comment]
Can you confirm this issue is still present OP? Seems like this has been fixed in the latest Fabric & SPFx releases.

**Comment by coreyroth** [comment]
Hi Andrew.  I pulled down the repo and got that version of SPFx running again and it seems to work now without any code changes.  It's no longer an issue running on the existing version SPFx 1.5.1.  I assume something changed service-side to correct this.
