### ISSUE TITLE
Custom learning for Office 365  template failed. 

### ISSUE THREAD

**Issue by peterjkrebs** [SharePoint/sp-dev-docs#3595]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Sign in to Provisioning Service, click Custom Learning, then Provision. Expected Success email with provisioned template and web part.

#### Observed Behavior
Get error message in email that Request to Provision failed. 

SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.                                                                                       Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088                                                                                       PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues                                                                          SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it. |   | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. |   | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 |   | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 
SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
SharePoint Online       Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
 
Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088
Here is the exception that occurred:       Type = System.Exception Message =       {"odata.error":{"code":"-1,       Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot       find resource for the request       SP.RequestContext.current/web/tenantappcatalog/."}}} Source = OfficeDevPnP.Core       TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.ALM.AppManager.<BaseRequest>d__38.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       OfficeDevPnP.Core.ALM.AppManager.<DeployAsync>d__20.MoveNext() ---       End of stack trace from previous location where exception was thrown ---       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Deploy(AppMetadata appMetadata,       Boolean skipFeatureDeployment, AppCatalogScope scope) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       333 HResult = -2146233088
 
PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
PnP       Correlation ID: 8a680089-ff48-4129-9e23-27abdfa941a6              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>

>

Thanks for your contribution! Sharing is caring.

**Comment by karuanag** [comment]
HI @peterjkrebs  - Which tenant generated this error?  Thanks

**Comment by peterjkrebs** [comment]
Didn't wait 30 minutes after tenant app catalog creation.
