### ISSUE TITLE
SharePoint Online Modern Text Editor colliding with Custom built CKEditor (React) Component

### ISSUE THREAD

**Issue by ravinleague** [SharePoint/sp-dev-docs#3596]
We have built a custom Rich Text Editor Web Part using CKEditor 4 and SPFx for Online. 
The component is built on React as a SharePoint Framework Component and deployed to SharePoint Online. Everything was fully functional until we added a Text Editor to the Page. See image attached.
We have tested our web part with several other web parts (SPFx) provided by MS OOTB. No issue seems to exist with other web parts. The Text Editor is the one causing the issue. the network log reports: https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-01.015/sp-ckeditor-flight/plugins/tableselection/styles/tableselection.css cannot be found. 
We are not even using the CDN spoprod.xx.xxx.xx. We are not sure why the CKEditor css is being pulled from spoprod-a.akamai...

![image](https://user-images.githubusercontent.com/18733308/54331441-bbeca480-4665-11e9-9244-49f5136a3438.png)

**Comment by ravinleague** [comment]
From the image above - the toolbar appears to be missing, this happens only when there is a text editor web part added to the page.

**Comment by VesaJuvonen** [comment]
Challenge is that your component will be using exactly the same CSS entries, which is then causing things to fail. You'd need to decorate your CSS entries to avoid this not to happen with the version which SharePoint is using natively.

**Comment by ravinleague** [comment]
Thank you! We have figured a way out if this - Stopped using native SharePoint Rich Text Editor on Modern Pages.

Ravi Challa
