### ISSUE TITLE
SPFX fieldcusomizer different behaviour in developer and commercial tenant

### ISSUE THREAD

**Issue by naarts2004** [SharePoint/sp-dev-docs#3597]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have created a simple field customizer using SPFX. I followed the steps described in [building simple field customizer](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer). When testing this component using gulp serve in my commercial tenant I do not see a change on the listcolumn. When trying this same component in my developer tenant the contents of the column is directly changed. For me both the commercial and developer tenant are in first release mode.

#### Observed Behavior
In the commercial tenant the fieldcustomizer does not seem to work while in developer tenant it is.

#### Steps to Reproduce
The fieldcustomizer is rather equal to the one specified in the sample. The content of the title field is changed to a value supplier in a property. Starting it in commercial tenant in first release does not work. Switching back to public release and field customizer is working again. In developer tenant both first and public release are working.

**Comment by AJIXuMuK** [comment]
Might be related to #3476

**Comment by VesaJuvonen** [comment]
We would need to have more details on what does your solution do or a repro solution to be able to reproduce the issue. Without having additional details, we can't really solve the issue.
