### ISSUE TITLE
SPFX site (SharePoint 2016 on-premise site with react) reloading continuously. What to do?

### ISSUE THREAD

**Issue by JEEVANJGA** [SharePoint/sp-dev-docs#3600]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I am trying to setup a SharePoint 2016 on-premise site with react using Yeoman generator : @microsoft/generator-sharepoint (V1.7.1).

I followed the instructions from microsoft docs only. I had referred few other resources as well for changing package modules and getting a working solution. 

Need help in fixing this.

#### Expected or Desired Behavior

1.  package.json file should have latest functional node modules to provide latest features and functionalities..

2. The loaded site view should not get refreshed continuously. and should not throw any errors.

#### Observed Behavior

1. Package.json file being created on solution creation using Yoeman generator( @microsoft/sharepoint V1.7.1) had older versions of SPFX modules (V1.1.0). I had to manually change the package.json file and then update node modules.

2. After following sequence of steps mentioned in Steps to Reproduce , 
SPFX site got loaded in the localhost at port 4321. 
But in every 5 to 10 seconds it is getting reloaded continuously in chrome and IE as well.

#### Steps to Reproduce

Steps I followed :

1. Downgraded my Node from 10.x to 8.15.1 .Reason : 9.x or 10.x Node versions are currently not supported with SharePoint Framework development.

2. Install Yeoman and gulp ==> npm install -g yo gulp

3. Install Yeoman SharePoint generator ==> npm install -g @microsoft/generator-sharepoint .

4. Creating a new web part project ==> yo @microsoft/sharepoint --skip-install

5. After solution got created,updated package.json to following :

   {
      "name": "sample",
      "version": "0.0.1",
      "private": true,
      "engines": {
      "node": ">=0.10.0"
      },
      "scripts": {
      "build": "gulp bundle",
      "clean": "gulp clean",
      "test": "gulp test"
      },
      "dependencies": {
        "react": "16.3.2",
        "react-dom": "16.3.2",
        "@types/react": "16.4.2",
        "@types/react-dom": "16.0.5",
        "@types/react-addons-shallow-compare": "0.14.17",
        "@types/react-addons-update": "0.14.14",
        "@types/react-addons-test-utils": "0.14.15",
        "@microsoft/sp-core-library": "~1.7.1",
        "@microsoft/sp-webpart-base": "~1.7.1",
        "@microsoft/sp-lodash-subset": "~1.7.1",
        "@microsoft/sp-office-ui-fabric-core": "~1.7.1",
        "@types/webpack-env": "1.13.1",
        "@types/es6-promise": "0.0.33"
      },
      "resolutions": {
        "@types/react": "16.4.2"
      },
      "devDependencies": {
        "@microsoft/sp-build-web": "~1.7.1",
        "@microsoft/sp-module-interfaces": "~1.7.1",
        "@microsoft/sp-webpart-workbench": "~1.7.1",
        "gulp": "~3.9.1",
        "@types/chai": "3.4.34",
        "@types/mocha": "2.2.38",
        "ajv": "~5.2.2"
      }
    }

6. Then run ==> npm i --save ==> Ignored warnings generated along with it

7. After installation, run ==> gulp trust-dev-cert

8. Finally, run ==> gulp serve.

Hope I haven't missed anything so far for the SPFX Project setup.

**Comment by mrukas** [comment]
We are experiencing the exact same issue.

**Comment by Malouke** [comment]
where is the solution or help ????  i had same probelm

**Comment by VesaJuvonen** [comment]
When you set up a solution for SharePoint 2016 FP2, you will need to use SharePoint Framework 1.1 version for the npm packages in the package.json. This is automatically done for you when you create a solution and choose the SP2016 as the target environment.

If you are targeting SP2016 Feature Pack 2, you cannot use SPFx v1.7 packages, so you should NOT do any manual updates on the package.json after the initial configuration. This is exactly why the version question is done in the Yeoman flow. You can't use 1.7 packages in SP2016 as there is also server side dependencies which are now causing you a version mismatch, which will then cause your solution execution to fail.

Please repeat the steps by creating a web part (extensions are not supported in SP2016) and not updating the package.json solution. If refresh issue still continues, please report a new issue with the repro steps. Thx.
