### ISSUE TITLE
Doubled application customizer displayed

### ISSUE THREAD

**Issue by MaartenSundman** [SharePoint/sp-dev-docs#3604]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect to see my application customizer displayed once on the page when going to another site collection.

#### Observed Behavior

Starting mid-day yesterday we started getting user reports that when clicking on links to another site collection. The header and footer of the site are duplicated. Our header and footer are provided by an application customizer. A refresh gets rid of the duplication, and it appears to be caused by a change in how the partial-refresh occurs when going around the site.

#### Steps to Reproduce

- Create two site collections
- Enable a branding application customizer on both
- Add a link to the other site collection on a page in the first site
- Click the link
- Note the elements inside of the Top and Footer placeholder have both the original displayed content from Site 1 and the content for Site 2

#### Additional Notes
This can be avoided by having the link do a window.location.href to the new url. But thats a bandaid.
The application customizer is built on SPFX 1.4.1

Thanks for your contribution! Sharing is caring.

**Comment by MaartenSundman** [comment]
![dom-doubled](https://user-images.githubusercontent.com/25912928/54382097-7f607f00-464c-11e9-837f-5a1cdd1c8479.gif)
![doubled](https://user-images.githubusercontent.com/25912928/54382099-7f607f00-464c-11e9-9f9c-fb1662b9acec.gif)

**Comment by VesaJuvonen** [comment]
Is this still happening or did it got fixed automatically? Please confirm that status. Sorry for the delay on following up with the issue.

**Comment by MaartenSundman** [comment]
Yes, seems to be related to partial page loads. Triggering a full page load from the initial site to the new one prevents the issue from occurring. That, of course, is not a desirable or sustainable path.

For the time being, I have added styling that hides the second instance which at least hides the behavior to end users.

**Comment by VesaJuvonen** [comment]
As we cannot repro this on our side, any change you could share your solution for us to repro the issue? Would help on moving forward on the troubleshooting. You could use for example MS Tech Community for sending the sppkg file in safe ways only for me.

**Comment by MaartenSundman** [comment]
Here you go, just got back from vacation :)

[spfx-branding.zip](https://github.com/SharePoint/sp-dev-docs/files/3174576/spfx-branding.zip)

**Comment by VesaJuvonen** [comment]
Thanks @MaartenSundman, sorry for the small delay. We'll use this for reproducing the issue and get back to this. Thx.

**Comment by mcmynn83** [comment]
@MaartenSundman  - Thanks for uploading your package.  That being said I'm still not able to repro the issue, and there I am having trouble fixing it.

Let me know where I went wrong:
1.  Create a new 2 new site collections (team1 and team2)
2.  Add your app to the app catalog (tenant deployed)
3.  Go to team1, add the custom action to the web
4. Go to team2, add the custom action to the web
5.  In team 2 create a link in the left nav to link to team1
6.  Click the click the link

According to you in step 6 i should get duplicate headers/footers.  The thing is, I don't.

Thanks,
Graham
