### ISSUE TITLE
React types using an old version in SPFx 1.8.0

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#3605]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

@patmill in the latest version of SPFx, the version of React got bumped to 16.7 which is a great thing, but the types are still referencing the same version as in 1.7.0 and 1.7.1: `"@types/react": "16.4.2"`. Due to this, you are not able to use any of the new features in React version 16.7.

**Comment by patmill** [comment]
OK, thanks.  We can certainly bump that and push an update.  Is there any issue when you manually bump the version and re-install/rebuild?

**Comment by estruyf** [comment]
@patmill check: https://www.eliostruyf.com/using-the-full-potential-of-react-in-sharepoint-framework-1-8-0/

In order to manually bump the types version, the TypeScript version also needs to be updated to version 3.2.

**Comment by patmill** [comment]
When you go down that rabbit hole, what version of OUIFR do you use? (or do you?)

**Comment by estruyf** [comment]
The same version that is part of SPFx, so in this case it will be `6.143.0`. Although I have not yet tested it.

**Comment by VesaJuvonen** [comment]
We are working on the updated setup of default scaffolding which will use the right React, Office UI Fabric and TypeScript combination. Right now the right version matrix is not properly yet documented and we are also working on that setup if you want to use for example later version of the React as that has then dependencies on TypeScript and OUIFR... more details soon.

**Comment by ronaldborman** [comment]
@patmill I noticed that in a freshly generated SPFx project (1.8.1 but also earlier versions) types/react and types/react-dom are listed under the dependencies key in package.json (instead of devDependencies which imho would be more logical). In his article about SPFx 1.8 @andrewconnell also installed a newer version of types/react under the devDependencies key. Is there a specific reason to use the dependencies key?

**Comment by andrewconnell** [comment]
@ronaldborman it's an issue they've acknowledged... just not high on the priority: https://github.com/SharePoint/sp-dev-docs/issues/2249

**Comment by kemesfun** [comment]
As of 1.10, this issue doesn't repro. @estruyf can you verify whether or not this issue still occurs?
