### ISSUE TITLE
Doesn't seem possible to check for both an object being set, and a field of that object 

### ISSUE THREAD

**Issue by ericleigh007** [SharePoint/sp-dev-docs#3607]
A conditional such as the following seems to fail because in the case of null objects, the second half of the "or" causes an error:

"=IF([$personField] == '' || [$personField.email] == @me ,'flex', 'none')",

What seems to happen is that only rows with a personField set are going to be tested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Currently, accessing a sub property of a person field anywhere in your expression on a blank person field will fail the entire expression. Details of this can be seen by adding `"debugMode":true` to your format.

You can however, check if a person field is blank without causing expression failure by using `"=if(length([$personField]),'Not blank','Blank')"`

But you cannot go further and do any property access in that expression. This is a big limitation. A work around is to include the check above at a higher level (parent object), but this is not easy and doesn't fit all scenarios.

I believe sub expression failures shouldn't fail entire expressions. These should either be caught, or preferably, only evaluated when necessary. So, in the example condition shown above, the true portion should NOT be evaluated when the condition evaluates to false. This would allow you to have those sub property accessors only be evaluated when the field is not blank and would let the expression succeed.

Any thoughts @ldemaris?

**Comment by ldemaris** [comment]
{
  "debugMode": true,
  "elmType": "div",
  "txtContent": "= 'Email : ' + @currentField.email"
}

This format appears to works correctly, even if @currentField is a person/group field and the value is blank.

What’s an example JSON that errors out with blank values in the person/group field?

**Comment by ericleigh007** [comment]
The confusion may be that this problem report is in the context of a view formatter, not a column formatter.  In the view formatter, problems occur that make it impossible to check for a field being null/blank, and also checking for a subfield’s value as well.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ericleigh007** [comment]
Wondering if it is possible this is on the backlog yet to fix?
You can see above in the documentation feedback the exact syntax that fails to work as one might expect.  Thanks

**Comment by thechriskent** [comment]
I am now seeing this work correctly both in column and view formatting. This format works in column formatting:

```json
{
  "debugMode": true,
  "elmType": "div",
  "txtContent": "= 'Email : ' + @currentField.email"
}
```

```json
{
  "rowFormatter": {
    "debugMode": true,
    "elmType": "div",
    "txtContent": "= 'Email : ' + [$Person.email]"
  }
}
```

Both formats look similar to the following:
![image](https://user-images.githubusercontent.com/8364109/59340750-960e8480-8cd4-11e9-9a2f-76d191e308b3.png)

Thanks everyone!
