### ISSUE TITLE
Unable to create application customizer or Listview Command Set

### ISSUE THREAD

**Issue by michaelmaillot** [SharePoint/sp-dev-docs#3609]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect the generator to create a SPFx solution with my Application Customizer or my Listview Command Set.

#### Observed Behavior

Once I chose the name and the description of the extension, I got the following error :

**Application Customizer:**
Error: ENOENT: no such file or directory, scandir 'C:\Users\me\AppData\Roaming\npm\node_modules\@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react'

**Listview Command Set:**
Error: ENOENT: no such file or directory, scandir 'C:\Users\me\AppData\Roaming\npm\node_modules\@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react'

But when I try to create an Application Extension with @pnp/spfx, everything's fine.

#### Steps to Reproduce

- Type "yo @microsoft/sharepoint"
- Set Solution Name
- Set Location
- Set "No" to feature deployment
- Set "No" to unique permissions to access web APIs
- Select "Extension" to the type of client-side component
- Select "Application Customizer" or "Listview Command Set" to the client-side extension to create
- Set Extension Name
- Set Extension Description

Versions of the @microsoft/generator tested : 1.7.1 and 1.8

Thank you for your help !

**Comment by patmill** [comment]
I've tried this a few times now with 1.8.0, both with new solutions and existing ones, and I'm not able to repro.  Sticking with the usual "turn it off and turn it back on again" approach to diagnosing issues, can you remove the generator and then reinstall it globally?  (npm install -g @microsoft/generator-sharepoint@1.8.0 )

Also - what versions of npm and node are you using?

**Comment by michaelmaillot** [comment]
Hi,

Thanks for the reply. I tried the classic "turn off / turn on" from IT Dep, without success. My version of npm is 5.6.0 and node 8.11.3.

**Comment by andrewconnell** [comment]
@michaelmaillot Can you try with a more recent version of NPM (v6+) and the latest generator (1.8.2)? Seems to be an issue in acquiring packages... doesn't appear related to SPFx...

**Comment by michaelmaillot** [comment]
Hi @andrewconnell, since I upgrade everything to latest version (1.9.1), it works ! Sorry for the delay and thank you for your time !

**Comment by priyarane30** [comment]
I am facing same issue . 
node version : v10.15.3
npm version :  6.13.4
generator : 1.10.0
I am tried to create extension with VS 2015 and VS 2017, facing same issue .
