### ISSUE TITLE
npm i -g @microsoft/generator-sharepoint@latest not installing latest version

### ISSUE THREAD

**Issue by statto1974** [SharePoint/sp-dev-docs#361]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [* ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Running `npm i -g @microsoft/generator-sharepoint@latest` and then creating a new project using `yo @microsoft/sharepoint` I'd expect to see the latest RC0 release.

The cmd console is running as an Administrator

#### Observed Behavior
Opening package.json I see the following dependencies
```
"dependencies": {
    "@microsoft/sp-client-base": "~0.2.0",
    "@microsoft/sp-client-preview": "~0.2.0",
    "office-ui-fabric-react": "0.36.0",
    "react": "0.14.8",
    "react-dom": "0.14.8"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~0.5.0",
    "@microsoft/sp-module-interfaces": "~0.2.0",
    "@microsoft/sp-webpart-workbench": "~0.2.0",
    "gulp": "~3.9.1"
  },
```

These are not the dependencies listed in https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0

#### Steps to Reproduce
Run `npm i -g @microsoft/generator-sharepoint@latest` and then `yo @microsoft/sharepoint`

**Comment by chakkaradeep** [comment]
Can you try uninstalling the generator and then installing it?

```
npm uninstall @microsoft/generator-sharepoint -g
```

```
npm install @microsoft/generator-sharepoint -g
```

**Comment by statto1974** [comment]
Thanks, I had tried that, but it didn't work.

I had to do a `npm cache clean` which solved the problem
