### ISSUE TITLE
Custom action 'CA_1' was not added/updated because the site was configured for noscript

### ISSUE THREAD

**Issue by anisiaalexandra** [SharePoint/sp-dev-docs#3610]
Hi,

I have created a fresh team modern site and tryied  to apply the above template. I in the logs provided by PNP I have as information: "Custom action 'CA_1' was not added/updated because the site was configured for noscript". I have the latest version of PnP PowerShell install. I would really appreciated some help with this. Thank you in advance. 
BR,
Anisia Pop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4245fa14-c317-5a0f-7aba-6569d5cb268d
* Version Independent ID: 2a351a4d-3600-b80a-6ae3-8b1a494d69c7
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-lists-and-libraries#feedback)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It seems you created the site using the [PNP Sites Core](https://github.com/SharePoint/PnP-Sites-Core) project? If so, this question may be more appropriate in their repo's issue list (linked above)...

**Comment by anisiaalexandra** [comment]
The site was created from the SharePoint Admin via the interface. PnP was only used as described in the context above. Other actions like Lists work as expected.
