### ISSUE TITLE
Subsites wrongly call parent site theming API in SharePoint server 2019

### ISSUE THREAD

**Issue by Promhize** [SharePoint/sp-dev-docs#3611]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
> Subsites pages use the subsite's color theme on modern pages
> 
> **More details** On page load in a subsite , if there is no cached theme in localStorage, the page should call an API similar to **{webAbsoluteUrl}/_api/SP.Web.GetContextWebThemeData**, instead it calls an API similar **{location.origin}/_api/SP.Web.GetContextWebThemeData**
>
> **Initiator** window.spModuleLoader.e.loadThemeData | @ | sp-pages-assembly.js?uniqueId=2g4QD:253
>
> Environment: SharePoint server 2019, Browser - Chrome 72.0.3626.121 (Official Build) (64-bit)

#### Observed Behavior

> Subsite uses theme from root site collection
>

#### Steps to Reproduce

1. Use the documented API at https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api to apply a theme on a root site collection in sharepoint 2019
2. Create a subsite in the root site collection
3. Use same API to apply a theme on the subsite
4. Open subsite in a different browser/incognito mode 

Result
Parent site theme is applied on subsite

### Easier steps to reproduce

1. Open **Change the look** on a modern page in a subsite
2. Select and apply a theme different from that of the root site
3. Open a new browser window in incognito mode
4. Go to the same modern page in the subsite

#### Result
Page is rendered with root site's theme

**Comment by VesaJuvonen** [comment]
As this is not a dev issue, we cannot provide support using this channel. This can be reproduced with the out of the box themes as well, so it's not a dev issue. Please report the issue using the tenant admin support channels. This might be also by design that the themes are always set in the site collection level.
