### ISSUE TITLE
Can't use loadLegacyFabricCss in SPFX 1.8

### ISSUE THREAD

**Issue by araLT** [SharePoint/sp-dev-docs#3612]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

According to SPFX 1.8 documentation, it is possible to add **"loadLegacyFabricCss": true** to web part manifest file in order to force old fabric CSS to be loaded in the page. 

#### Observed Behavior

After adding the mentioned property (`"loadLegacyFabricCss": true`) to web part manifest file, execution of commands `gulp serve` or `gulp bundle` failed and after webpacking the following error message is displayed:

[15:29:01] Error - [write-manifests] Manifest validation error (./src/webparts/helloWorld/HelloWorldWebPart.manifest.json): 
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/) Missing required property: extensionType
(#/componentType) No enum match for: WebPart
(#/) Additional properties not allowed: loadLegacyFabricCss
(#/) Missing required property: items
(#/) Missing required property: rootComponentId

#### Steps to Reproduce

1. Create new spfx 1.8 project containing web part.

2. Add `"loadLegacyFabricCss": true` to web part manifest file. Here is Example of such manifest file:
![image](https://user-images.githubusercontent.com/1893673/54436036-3d6a3280-474b-11e9-9e5b-fd22bd8949a6.png)

3. Run command `gulp serve` or `gulp bundle` and you will get the mentioned error:
![image](https://user-images.githubusercontent.com/1893673/54436288-a94c9b00-474b-11e9-97d5-e22a40480786.png)

**Comment by patmill** [comment]
Thank you to @srideshpande for finding a temporary solution.  The final one will require an update to our public packages.

Go to the below location

	node_modules\@microsoft\sp-module-interfaces\lib\manifestSchemas\jsonSchemas\client-side-web-part-manifest.schema.json

Add the following line to the file before the 'canUpdateConfiguration' entry 
	
     "loadLegacyFabricCss": { "$ref": "any-value.schema.json" }

save, and run gulp or gulp build or gulp bundle or gulp --ship.

**Comment by abhishek-raj** [comment]
@patmill Is this fixed yet? I am facing the same issue when I used it yesterday.

@araLT Can you reopen the bug as it is not fixed yet and the temporary solution would not work in build pipelines?

For now, I am just including the fabric css file directly using `require('../../../../node_modules/office-ui-fabric-core/dist/css/fabric.min.css');` till this is fixed.

**Comment by salahsaleh** [comment]
@patmill  is this fixed yet?

I am also facing same issue but with another property **'supportedHosts:["SharePointWebPart","TeamsTab"]'**

When I am passing this values in manifiest file of project I am getting error.

**Comment by VesaJuvonen** [comment]
Fixed with the v1.8.1 release - see release notes at - https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8.1-release-notes
