### ISSUE TITLE
Powershell Command Does Not Work

### ISSUE THREAD

**Issue by jaypatrick** [SharePoint/sp-dev-docs#3615]
$template = Get-AzureADDirectorySettingTemplate | where { $_.DisplayName -eq "Group.Unified" }

Throws error that the Get-AzureADDirectorySettingTemplate command cannot be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27643fd2-8059-f411-224b-bd0815aacc8f
* Version Independent ID: bd410f9a-a3f2-9222-7d4a-2271d7f6161d
* Content: [SharePoint ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification)
* Content Source: [docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-site-classification.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by dmadelung** [comment]
Are you running the version of Azure AD Preview?  The current version of AzureAD does not include that cmdlet. 
https://www.powershellgallery.com/packages/AzureADPreview 

```
# Install the Azure AD Preview Module for PowerShell
Install-Module AzureADPreview
```
