### ISSUE TITLE
Sync to Teams ribbon button is not working

### ISSUE THREAD

**Issue by kchiragowni** [SharePoint/sp-dev-docs#3619]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SharePoint Framework Webpart with 'TeamsTab' supported host added to webpart manifest file deployed to AppCatalog site collection. 

``` javascript
"supportedHosts": ["SharePointWebPart", "SharePointFullPage", "TeamsTab"]
```

Selecting the webpart enabled 'Sync to Teams' ribbon button, clicking the button should deployed the SPFx webpart automatically to Teams.    

#### Observed Behavior

Clicking the 'Sync to Teams' button nothing happens and SPFx webpart not deployed to Teams.

#### Steps to Reproduce

1. Create a standard SPFx webpart
2. Updated Webpart manifest to inculde 'TeamsTab' in Supported Hosts array 'supportedHosts'
3. Bundle, Package solution and add & deploy to App catalog
4. Select the webpart to enable 'Sync to Teams' ribbon button 
5. Click the 'Sync to Teams' button to deploy webparts to team.

**Comment by PooLP** [comment]
Same for me, after click, nothing happens (no loader, message, error ...)

**Comment by etesson** [comment]
I have the same issue. A small toast popup on the right displaying "Failed to sync solution to teams".

![image](https://user-images.githubusercontent.com/5942997/54828077-c7555680-4c89-11e9-8a85-0d65c22b8807.png)

**Comment by AJIXuMuK** [comment]
First time I clicked it I received response something like `SyncSolutionToTeams: null`.
The app is not visible in Teams app catalog.

I tried to click the button again - and now I'm getting 409:
```
{"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server returned an error: (409) Conflict."}}}
```

**Comment by juliemturner** [comment]
I'm having a related issue, with an upgraded solution not a new one. I get the same UX error message as @etesson:
- Updated solution to 1.8
- Got the solution deployed and it's working correctly
- Tried "Sync to teams" got failure message... look at browser console. Call to https://{site}.sharepoint.com/sites/AppCatalog/_api/web/tenantappcatalog/SyncSolutionToTeams return 500 error, error payload: {"error":{"code":"-2146232832, Microsoft.SharePoint.AppPackageValidationException","message":{"lang":"en-US","value":"Package does not contain required images"}}}
- Realized I still had the manifest file in teams folder, removed it, rebuild, deploy, click "Sync to teams" -- same message
- Realized that a new project has different default image names (wondered if it were hard coded or something) -- copied images from new project to old project... still same message.
- Created brand new project, starting with 1.8 generator and it worked fine.

**Comment by VesaJuvonen** [comment]
Hi @kchiragowni, can you update on the status for this. Are you still seeing this? It should be already fixed, so would love to get a confirmation on the status. Thx.

**Comment by BigEaseGueldi** [comment]
Just came around a 

{"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server returned an error: (409) Conflict."}}}

still not sure why.

**Comment by VesaJuvonen** [comment]
If the solution already exists in the Teams side, this is by design. There is no reason for sync to team button to be pressed if you only update your solution as the manifest is already in Teams. If you, however, will need to do more significant changes in the settings, you will first need to remove the package from Teams app catalog as we do not want to blindly override the package in Teams side. Makes sense?

**Comment by pieronegri** [comment]
hi,
just found this error following the tutorial
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

**Comment by ganeshsanap120694** [comment]
> sync

I am facing the same issue while syncing to teams.

**Comment by v-prabus** [comment]
Hi ,
Am also facing "**failed to sync solution to teams**" when we click on "sync to teams" action . Is anyone found the solution?
Thanks,
Prabu S

**Comment by VesaJuvonen** [comment]
@ganeshsanap120694 and @v-prabus - as this issue is closed already, it is no longer actively being looked in our internal systems. Please do open a new issue so that we get it properly tracked for the engineering work. Thanks.
