### ISSUE TITLE
Where is IReadonlyTheme, ThemeChangedEventArgs, ThemeProvider.serviceKey ?..

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#3620]
Hi,
I think some information is missing (It's late and I'm a little tired ^^)
Where is IReadonlyTheme, ThemeChangedEventArgs, ThemeProvider.serviceKey ?..
it's a new lib to import ?

Thanks,
Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5fe832e-68cc-0f3a-acc1-c9116a5c981d
* Version Independent ID: 4b6961ad-45a6-aef9-f197-c31b1cb4a5f8
* Content: [Supporting section backgrounds](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds)
* Content Source: [docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
They should be in sp-component-base.

**Comment by PooLP** [comment]
Thanks, it's work fine ;)

**Comment by gswdn** [comment]
Unfortunately, some information is missing in the tutorial. Would be nice to provide step-by-step tutorials that are complete and that work on a green field ;) - at least, in the beginner's section. Took me some time to figure it out. 

- you need to "npm install @microsoft/sp-component-base"
- import { ThemeProvider, ThemeChangedEventArgs, IReadonlyTheme } from '@microsoft/sp-component-base';
- declare variables "private _themeProvider: ThemeProvider;" and "private _themeVariant: IReadonlyTheme;"
