### ISSUE TITLE
React-router (hash routing) is not working directly after login

### ISSUE THREAD

**Issue by mwiedemeyer** [SharePoint/sp-dev-docs#3624]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have an SPFx 1.8 web part which uses react hash routing. So you can open the page with a specific route to navigate to a specific part within the web part. E.g. `Page.aspx#/my/route/1`
It shoud be possible to open the link directly, for example from an email.

#### Observed Behavior

Direct link to a page with a hash before logging-in removes the hash after redirecting from login page.

#### Steps to Reproduce

Open a browser where you are already logged-in to SharePoint Online, everything is working as expected.
If you are not already logged-in to SharePoint Online, the call to `Page.aspx#/my/route/1` redirects you to `login.microsoftonline.com`. After logging in, you are redirected back to `Page.aspx` but without the hash route.

Note: This works fine if I'm using a custom web app (hosted on azure) and using a registered AAD app with adal.min.js (which automatically saves the state and previous requested url).

You can find a [sample Web Part here](https://github.com/mwiedemeyer/spfx-router-issue-sample).

Hashrouting and login should work in SharePoint Online exactly like in the Azure Portal. You can open this link and the hash is preserved after login: https://portal.azure.com/#blade/HubsExtension/Resources/resourceType/Microsoft.Web%2Fsites

**Comment by patmill** [comment]
Hi there @mwiedemeyer - What you are asking for seems reasonable, however it is a more core behaviour to SharePoint Online than this issue list is able to cover.  Would it be possible for you to open a support ticket (it might be a "Design Change Request") to get this into the broader system?

**Comment by mwiedemeyer** [comment]
Thank you for your fast response. I already have an open premier support case for this. Hoped it gets more visibility here. 😉
So we can close this for now. I can later add the response from my support ticket.

**Comment by Rainson12** [comment]
I have the same issue and already reported it a long while ago however the general sharepoint support seems to be intellectual incapable of understanding what this issue is about. So if possible could you guys from spfx team forward this case internally to the appropriate team?

**Comment by mwiedemeyer** [comment]
I asked to get my case forwarded to someone who knows something about SPFx or at least web development in general. Hope it reaches someone who can do something about this issue.

**Comment by patmill** [comment]
Well, I'm glad that you consider us to be non-muppets (although Kermit is cool).  I'll see what I can do.

**Comment by Rainson12** [comment]
> Well, I'm glad that you consider us to be non-muppets (although Kermit is cool). I'll see what I can do.

wasnt meant as offense but i got a red phone to office 365 support already. And doing the 3rd screencapture because the content type hub sync. is spamming errors in the sync log doesnt really make any sense. 
However thank you!

**Comment by mwiedemeyer** [comment]
Good news: I just heard, that the change was accepted by the product group! So it will be fixed in a future update.

**Comment by patmill** [comment]
Well that's good to hear.  I was digging into a bit, and it's rather tricky, given that the fragment information is never sent down to the server, so you need to bounce back to the client, get it to stick it some place else (cookie, form, query string, etc.) head back, pass that around through all the auth flows, then reconstitute it back to the client at the end.  Glad it is getting fixed.
