### ISSUE TITLE
How to store username & password for SPFx webpart?

### ISSUE THREAD

**Issue by lrolseth** [SharePoint/sp-dev-docs#3625]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have a SPFx web part that is making a call to a 3rd party API.  I need to be able to send a login and password for the API call.  
Could somebody kindly direct me to the best practices for securely storing credentials in O365 for use in a SharePoint web part please?

**Comment by patmill** [comment]
Are you wanting this to be secure in any way, or just want a way to have different tenants use different names/passwords?  You can take a look at this documentation for a way to store information per-tenant that can be used in your solution.  https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties

**Comment by patmill** [comment]
Sorry - there was some internal discussion that I was making it sound like the tenant properties was a secure way of doing this.  It is not.  The tenant properties are visible to everyone.  I only meant that if you need some property stored that you need to use in your part (say, a tenant wide analytics key), and that is the same for all users, but different per tenant, then the tenant props are a good way of handling this.  If you want a way to securely store a username and password, please don't use it.  There is no general SSO story for non-AAD protected end points.  One possible thing to do would be to create an azure service that the user can call, and it does the secure storage.
