### ISSUE TITLE
Extreme performance loss after upgrade to SPFx 1.8.0 in redraw of React components

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#3627]
After upgrading from SPFx 1.7.1 to 1.8.0 I noticed that input in FabricUI TextFields (controlled) is suddenly slow (in a non-tolerable way, see videos attached, takes 70ms to show a typed character instead of <20ms as before, on a very fast computer) and is instable (before it used to be fluently the same little delay, now I have sporadical stops and slowdowns on the already slow input). 

I just tested it again and can reproduce it by just changing the 1.7.1 packages to 1.8.0 (without adjusting React, leaving it at 16.3.2 (same issue with 16.7.0 though, so React does not seem to be the cause), and without switching to the new Typescript compiler (uses 3.2.4 instead of 2.x before, but same issues also with 3.3). 

I will have to investigate what causes the problem (can it have sth to do with the new isolated Fabric style changes?). 

Check the videos - all I did was replace 1.7.1 by 1.8.0, npm install, gulp serve and F5: 
![171](https://user-images.githubusercontent.com/5341447/54574870-4af51600-49f2-11e9-81b3-82eb9e43fdb7.gif)
![180-1](https://user-images.githubusercontent.com/5341447/54574873-4e889d00-49f2-11e9-86e5-dd0539d2c6a2.gif)

It is not only slow but also input gets rendered delayed. I tried to delete only the "iiii"s but ended up deleting all the text before as well even though the key was released (this is how the user experience looks in real-time on a 8core CPU): 
![180-2](https://user-images.githubusercontent.com/5341447/54574866-4597cb80-49f2-11e9-9504-0b940e9b4fb4.gif)

**Comment by patmill** [comment]
So, a few questions.  
1 - Does this repro in the "hosted" workbench (/_layouts/15/workbench.aspx)?
2 - Are you creating the control, or is this in the property pane?
3 - If you are creating the control, did your version of fabric react change?

**Comment by frevds** [comment]
Hi @patmill, thanks for following up. 

This does indeed reproduce in the workbench, locally and in SharePoint Online, but less visibly so than on a real SitePage. 
I attached two solutions (shipped), one using 1.7.1 and one using 1.8.0 (with different IDs so you can deploy them together). 
I hope you can reproduce it. I also attached the project source. 

The difference between the two versions is immanent only with a lot of controls redrawing, but it is there (I went overboard and made 200 text fields). 
The 1.8.0 version typically takes twice the time and has irregular latencies and delayed processing, compared to the rather fluent 1.7.1 packages. 

To rule out any issues with my project, I created a brand new test project using the latest yo generator, a simple webpart solution with React framework. 
This btw does not compile because the Fabric components use a newer Typescript version than the configured rush-stack-compiler-2.7 can deal with. 
One has to remove line in tsconfig or use 3.3. 
Also I run into strange "cannot find module 'typescript'" errors whenever switching between the 2.7 and 3.3 compilers, when tslint runs, which I can solve only by toggling between versions of the rush-stack-compiler-x.y package, apparently npm install has to run twice for this package). 
I documented the whole procedure in the HOW-TO-TEST.md in the attached project. 

In the webpart I render 200 controlled FabricUI TextFields (they all re-render if one changes and display the same value), in order to see the impact visually. 

I then profiled how long it takes to enter text, once using the 1.8.0 packages and once using 1.7.1. 
I need 10 seconds to fill a textbox with "i"s using 1.8.0, and merely 5 seconds to do the same using the 1.7.1 packages. 


[Perf-Test.zip](https://github.com/SharePoint/sp-dev-docs/files/2984038/Perf-Test.zip)

**Comment by johnguy0** [comment]
If you still experience this, please open an issue on the Fabric team.
