### ISSUE TITLE
stupid

### ISSUE THREAD

**Issue by bdc604** [SharePoint/sp-dev-docs#3628]
this is stupid. what is all this 1980s command line bs to implement simple js behaviour? u guys feeling retro or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037437d9-e752-4c2a-4817-33e89daed5f9
* Version Independent ID: b748c4b5-b449-22f3-e375-e519a8c44928
* Content: [Tutorial - Migrating from JSLink to SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions#feedback)
* Content Source: [docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Not exactly actionable.
