### ISSUE TITLE
Issue with deploying extension 

### ISSUE THREAD

**Issue by sruthikokkalla** [SharePoint/sp-dev-docs#3629]
I have created spfx extension to add header & footer section referring above article. When I run it in my local host it works fine, I can see the output as mentioned in article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions 
but when I deploy the package in app catalog I was able to upload it successfully but could not find it in app list when I try to add it in my site collection.

What could be the issue ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46bf1b1-6910-2905-43ad-d24d88ef05e3
* Version Independent ID: f74fc1df-0ae6-6f5b-5008-9e95922faa9d
* Content: [Deploy your extension to SharePoint (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint#feedback)
* Content Source: [docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by abdollahkahne** [comment]
I do it just now for learning and it works fine for me, altough I had to delete escape part because it doesnt recognize sp-loadash-subset module which it is not necessary here. Did you replace the element.xml as it says? (only the last line should be replace) and did you remove ClientSideInstance.xml from package-solution? and at the end did you run gulp serve --nobrowser?

**Comment by sruthikokkalla** [comment]
Tenant wide deployment is working fine, issue is with Site Collection scope. After adding package to app catalog, when i selected "Add an app" in site collection this app is not visible.

 Did you replace the element.xml as it says? (only the last line should be replace) and did you remove ClientSideInstance.xml from package-solution? and at the end did you run gulp serve --nobrowser? --- Yes followed all the process

**Comment by sruthikokkalla** [comment]
Tenant wide deployment is working fine, issue is with Site Collection scope. After adding package to app catalog, when i selected "Add an app" in site collection this app is not visible.

 Did you replace the element.xml as it says? (only the last line should be replace) and did you remove ClientSideInstance.xml from package-solution? and at the end did you run gulp serve --nobrowser? --- Yes followed all the process

**Comment by VesaJuvonen** [comment]
As this has gone stale and seems that others have been able to make things work, closing it as not sure what we can do here. We have improved the documentation also after this submission, which might have resolved the issue. Please add a new comment on the documentation or add a new issue if needed.
