### ISSUE TITLE
Configure dynamic datasource in manifest

### ISSUE THREAD

**Issue by stridsbr** [SharePoint/sp-dev-docs#3630]
I would like to set a default dynamic datasource in the *Webpart.manifest.json file. Is this possible? The dynamic datasource is in the same solution but I don't know how or if it's possible to configure this. If this isen't possible to configure in *Webpart.manifest.json, is it possible to write some code in getPropertyPaneConfiguration to set a value if it's found and the value from this.props.dynamicDatafield === undefined?

Thanks for youre help

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by patmill** [comment]
So this isn't really possible at this point.  The actual datasource (say another webpart) can appear multiple times on a page, so the configuration has the instance information of the webpart in it.  You would need to handle the lookup (say in onInit of your webpart) to look at the available data sources and pick the right one. Does that make sense?

**Comment by stridsbr** [comment]
This makes perfect sence. So what i have to do is make a check in onit if the this.props.variable is configured and of it's not create a 'default' connection.

This would be nice to be able to configure in the manifest. I understand that it can be multiple instances of the same component and a guid is generated for each instance.

But a configure like this would help a lot. Use the first with the configure componentid would make this 'deployable'. Many times there is only one source. So this would be usable in many cases.

**Comment by stridsbr** [comment]
thanks @patmill . You sent me in the right direction.

This is how I wrote the code to hook this up in the onInit for a webpart. If someone else looking for the solution to this problem :-)

It would be nice to have this built in to the manifest with a property on the object. like sourceComponentId: 'guid'.

```javascript
public onInit() :Promise<void> {

        const reference = this.properties.myprop.reference;
        const val = this.properties.queryKeywords.tryGetValue();

        if (reference == undefined && !val ) {

            const source = this.context.dynamicDataProvider.getAvailableSources()
                .filter(item => {
                    return item.id.indexOf('{componentId}') > -1;
                })[0];
            
            if(source){
                var prop = new DynamicProperty<string>(this.context.dynamicDataProvider);
                prop.setReference(`${source.id}:searchQuery:rawInputValue`);

                // TODO known issue: when webpart is added to page a save and page reload is needed for the the DynamicProperty to start refreshing.
                this.properties.myprop= prop;
            }
        }

        return super.onInit();
    }
```
