### ISSUE TITLE
Using App Studio 

### ISSUE THREAD

**Issue by icelandgrecian** [SharePoint/sp-dev-docs#3631]
It would be worthwhile mentioning on here that the config url in the format 'https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=aa3fecf0-1fd0-4751-aba0-12314dc3a22f%26forceLocale={locale}' can´t be added into App Studio as it says it´s an invalid url format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Thanks for the heads up.  I'll pass that along to the AppStudio folks.

**Comment by cfitzsimonds** [comment]
I'm experiencing a similar issue with the config url in App Studio:

Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "{teamsitedomain}{teamsitepath}"

My full URL is:

"configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=d162bc8b-93a4-4bb9-97c1-bc06d4ff975b%26forceLocale={locale}"

Any updates on this issue?

**Comment by DakJack** [comment]
This is an issue even outside the app studio. it's not resolving the {teamSiteDomain}{teamSitePath}. When I attempt to load the web part to a tab, the url does not resolve and just fails the network request, so it's https://_layouts/15/TeamsLogon.aspx.
Any update on this?

**Comment by clearab** [comment]
I believe you need to install the app, then load it. You can't do both at the same time. Try going to ... => Manage Team > Apps > upload and install the app package. Once you've done that, try adding it as a tab.

**Comment by tom-daly** [comment]
it's almost impossible to actually complete this. the solution fails to sync from sharepoint so trying to install via app studio doesn't work b/c the urls.

**Comment by juanmlarios** [comment]
Has anyone actually successfully installed a teams app using this method? from the invalid wildcard domain issue and this issue with the {teamsitePath} invalid urls, this is impossible. Why even have this documentation up?

**Comment by akshay-randive** [comment]
I am still facing the issue mentioned by @cfitzsimonds . Not able to create a App from App Studio as well i see "Sync to teams" greyed out, even after mentioning "TeamsTab" under supported host in SPFx solution.  Webpart manifest
