### ISSUE TITLE
SPFx Application customizer get page all components data (List, Documents, Search etc..)

### ISSUE THREAD

**Issue by knalbandianbrightgrove** [SharePoint/sp-dev-docs#3632]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm creating SPFx Application Customizer, and I face to some lack of information.

Is there a way to get data about all components that present on page in ApplicationCustomizer like SearchBox, Search, Documents Library, Lists, Navigation bar etc..__????__

In example I want to make an additional action when user click on folder, file, list item, navigation item, search result item etc...

I do see that FieldCustomizer provide the field model in IFieldCustomizerCellEventParameters that contains domElement, listItem etc.. data, I wish to have smth similar to this.

I will be grateful for any response, sample or refernce to documentation that will help be to move further

Best regards,
Kolia

**Comment by patmill** [comment]
No, that is not currently possible.  New feature requests are handled by User Voice here - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform
