### ISSUE TITLE
After SPFx 1.8 update, ms-fontColor-[colorname] is not applied

### ISSUE THREAD

**Issue by artxach** [SharePoint/sp-dev-docs#3634]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

ms-fontColor-[colorname] classes do not work anymore after I updated to 1.8 version.

**Comment by andrewconnell** [comment]
Have you tried using the latest version of SPFx (v1.8.2)? Also, can you provide code that demonstrates the issue?

SPFx v1.8.0 introduced a few regressions fixed in 1.8.1 & 1.8.2... so this might have been resolved by 1.8.
