### ISSUE TITLE
Adding a list

### ISSUE THREAD

**Issue by vish302727** [SharePoint/sp-dev-docs#3635]
Can we create a new list using SPFx extension?
We can create list using SPFx webpart but webpart are not suitable for my requirement.
I want to way create List with SPFx extension so i can keep only one package

**Comment by bcameron1231** [comment]
You can provision assets in SharePoint Framework using the Feature Framework. 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package

Another option would be to use Site Designs and Site Scripts instead
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview

**Comment by vish302727** [comment]
Hi,
The above solution work for me.
Thanks for your help.

**Comment by bcameron1231** [comment]
@andrewconnell This ticket can be closed, as it's been answered.
