### ISSUE TITLE
Library Component not available for 'Create a subfolder with solution name' option

### ISSUE THREAD

**Issue by agtenr** [SharePoint/sp-dev-docs#3636]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

This question is regarding the new SPFx 1.8 library components feature (which is till in preview). When running the generator (yo @microsoft/sharepoint --plusbeta) the Library component type is not available when selecting 'Create a subfolder with solution name' in one of the previous steps of the yeoman generator. Is there a specific reason for this?

Thanks in advance.

**Comment by patmill** [comment]
Yeah, that looks like a bug.  Workaround for now would be to create the folder, cd, yo, use the current folder.

**Comment by kemesfun** [comment]
@agtenr I did not come across  this issue when using yeoman-generator v1.10. Can you try and repro this with v1.10?

**Comment by StfBauer** [comment]
@kemesfun It is now fixed 1.10.0. In general most people create a project using the "Create Folder option" start a another project on the same folder again with "Create Folder option".

The `.yo-rc.json` in the root folder caused a lot of trouble in the past.

<img width="435" alt="Screenshot 2020-01-29 at 22 05 20" src="https://user-images.githubusercontent.com/5503835/73397333-99966080-42e3-11ea-8c48-0c667b463708.png">
