### ISSUE TITLE
Reference custom CSS styles in SPFx web parts

### ISSUE THREAD

**Issue by vbartari** [SharePoint/sp-dev-docs#364]
#### Category
- [*] Bug

#### Expected or Desired Behavior
Reference custom CSS styles in SharePoint Framework web parts should work 

#### Observed Behavior
**Not able to reference custom CSS in sharepoint framework getting error:**

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part ,Error: ***Failed to component "87051fce-760f-4819-8bd0-2b01607657a4" (FooterWebPart). Original error: Error loading https://component-id.invalid/87051fce-760f-4819-8bd0-2b01607657a4_0.0.1 script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-loader_en-us_529d543c5cdfae3136128abb7f516ada.js:60:15897) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:47:21831) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:47:22244) at https://spoprod-a.akamaihd.net/files/sp-client-prod-npmx_2017-01-02.009/sp-webpart-base_en-us_cc837bf83be14d559d8c0d7bfe1bc34f.js:48:206

#### Steps to Reproduce
1. **In config.json file:**
  "externals": {
    "@microsoft/sp-module-loader": "node_modules/@microsoft/sp-module-loader/dist/sp-module-loader.js"
  }
2. **In webpart.ts file:**
import SPModuleLoader from '@microsoft/sp-module-loader';
export default class JQueryAccordionWebPart extends BaseClientSideWebPart<IJQueryAccordionWebPartProps> {
  public constructor(context: IWebPartContext) {
    super(context);
    SPModuleLoader.loadCss('css path');
  }
}

But now in RC0  drop , they have removed:
 public constructor(context: IWebPartContext) {
    super(context);
}
and we are getting error while using :ModuleLoader.loadCss('css path');
now anyone can let me know how do I refer my Custom Css in SPFx?
so that i can access Css style for my client webpart

**Comment by tortoise386** [comment]
Hello,
this is documented in the release notes to RC0:
https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0

They renamend and moved the SPModuleLoader to: SPComponentLoader in @microsoft/sp-loader.
In WebPart.ts file:
`import { SPComponentLoader } from `'@microsoft/sp-loader';`

And then you can still create the constructor yourself (visual studio code: just type ctor).
```typescript
constructor() {
    super();
    
    SPComponentLoader.loadCss('...');
}
```

For running long-running operations they now created the onInit() Method (which you can override):
```
  protected onInit(): Promise<void>{
    //Your code goes here ...
    //If you need the WebPartContext, access it with this.context

    return super.onInit();
  }
```

**Comment by vbartari** [comment]
@michel-weber : Thanks
