### ISSUE TITLE
SPFX 1.6 AadTokenProvider Inconsistent Client ID

### ISSUE THREAD

**Issue by jarellm** [SharePoint/sp-dev-docs#3640]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I'm not sure if this is a bug, a missing upgrade or an overlooked config item but we're trying to follow the instructions here:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad

We're unable to make the following code work using the app id or object id  of the target enterprise API (instructions state object id but we tried both anyway):

```javascript
   this.context.aadTokenProviderFactory
    .getTokenProvider()
    .then((tokenProvider: AadTokenProvider): Promise<string> => {
       // retrieve access token for the enterprise API secured with Azure AD
       return tokenProvider.getToken('<enteprise app object id>');
    }) .then((accessToken: string): void => {
        console.log(accessToken);
    });
```

Using the App ID:

```
Uncaught (in promise) Error: AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxxx' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
Trace ID: ea90d432-6c32-42fb-a9a0-7871af85b000
Correlation ID: d0799795-f0b7-4d3d-abdd-ba9fbf9eed3d
Timestamp: 2019-03-20 03:05:58Z
    at Array.<anonymous> (sp-pages-assembly_en-us_c99e462b02bf90b47583e0490d1c2544.js:1189)
    at _callBackMappedToRenewStates.(/sites/app_operations/SitePages/anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.006/1.sp-http-adal_7a2d498ba73bbc02778f.js:3:7561)
    at AuthenticationContext.handleWindowCallback (adal.min.js:2)
    at parseTokenFromUrl (spfxsinglesignon.aspx:20)
    at onload (VM900 spfxsinglesignon.aspx:31)`
```
Using the Object ID:

```
The resource principal named xxxxxx was not found in the tenant named xxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 42b9ef4a-5846-472a-8752-b2f73399d500
Correlation ID: 38cc4a04-40ed-4908-a049-6fd84c562f23
Timestamp: 2019-03-20 03:11:08Z
    at Array.<anonymous> (sp-pages-assembly_en-us_c99e462b02bf90b47583e0490d1c2544.js:1189)
    at _callBackMappedToRenewStates.(/sites/app_operations/SitePages/anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.006/1.sp-http-adal_7a2d498ba73bbc02778f.js:3:7561)
    at AuthenticationContext.handleWindowCallback (adal.min.js:2)
    at parseTokenFromUrl (spfxsinglesignon.aspx:20)
    at onload (VM1037 spfxsinglesignon.aspx:31)
```

We're using SPFX 1.6, and I understand there had been changes in the enterprise app registered in Azure. We've re-added the required permissions and had them approved by admin. I've verified in the portal that permissions are in effect under the principal `SharePoint Online Client Extensibility Web Application Principal`.

However I notice that another app (presumably the old one) `SharePoint Online Client Extensibility` still exists in the Azure list.  And its app ID is still the one being used for the SPFX IFrame redirect page (spfxsinglesignon.aspx)

ADAL IFrame Source is using the correct principal ID

`https://login.windows.net/tenant/oauth2/authorize?response_type=token&client_id=<SharePoint Online Client Extensibility Web Application Principal ID>`

But the embedded JS in the redirect page is still using the old one (spfxsinglesignon.aspx)

```javascript
		var authContext;
		var config = {
			clientId: '<SharePoint Online Client Extensibility ID>'
			navigateToLoginRequestUrl: true
		};
		function parseTokenFromUrl() {
			try{
				authContext = new AuthenticationContext(config);
				var hashValue = window.location.hash;
				if (!hashValue) {
					PageMethods.LogErrorsInSingleSignOnRedirectPage("window.location.hash is null!");
				}
				authContext.handleWindowCallback();
			} catch (err) {
				PageMethods.LogErrorsInSingleSignOnRedirectPage(err.message);
			} finally {
				if (window.parent === window) {
				  window.location.href = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST) || window.location.origin;
				}
			}
		}
````
	

Any ideas?

**Comment by patmill** [comment]
You will want to follow the guidance in the "important" section.  I've pasted it here - 

 Important

When connecting to Azure AD-secured APIs, we recommend that you use the MSGraphClient and AadHttpClient classes, which are now generally available. For more information about the recommended models, see Connect to Azure AD-secured APIs in SharePoint Framework solutions and Use the MSGraphClient to connect to Microsoft Graph.

**Comment by jarellm** [comment]
Hi Pat, correct me if Im wrong.
I believe both approaches use adal.js underneath, the only difference is
you get a client out of the box with your approach. This one you can pass a
token around your app.

Either way should yield the same result or error in this case, which I
confirm from my tests.

Check the excerpt from the same documentation:

"Typically, when building SharePoint Framework solutions, you would use the
MSGraphClient
<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph> to
connect to the Microsoft Graph and the AadHttpClient
<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient> to
connect to an enterprise API secured with Azure AD. If you however work
with a JavaScript framework that has its own service for executing web
requests, such as AngularJS or jQuery or your solution is built on an older
version of the SharePoint Framework, you might need to use other approaches
to obtain an access token to APIs secured with Azure AD."

**Comment by patmill** [comment]
The framework has made a bunch of changes under the covers to streamline access via ADAL / AAD.  If you run into issues using these methods, we'll be happy to help diagnose.

**Comment by jarellm** [comment]
Hi Pat,

As I said, both approaches yielded the same result. 


```javascript
        this.getAadClient().then((client) => {
            return client.get(`${this.rootUrl}/me`, AadHttpClient.configurations.v1).then((response) => { console.log(response); });
        });

        this.tokenFactory.getTokenProvider()
                         .then((provider) => { return provider.getToken(this.webApiId); })
                         .then((token) => { console.log(token); });

```

Using the Object ID from Azure Portal, Enterprise Apps:

![image](https://user-images.githubusercontent.com/10770226/54796591-c291a200-4c8b-11e9-9858-530d4af885b0.png)


Using the App ID:

![image](https://user-images.githubusercontent.com/10770226/54796661-0c7a8800-4c8c-11e9-8e0e-30a9535c9f48.png)

Using the App Resource UR (e.g. api://<guid>) :

![image](https://user-images.githubusercontent.com/10770226/54796899-28caf480-4c8d-11e9-818d-304b8aedaada.png)


I don't get it though. Why make the AadTokenProvider class available publicly, and go the lengths of documenting it as one of the implementation options, and then not support it afterwards?

Is it up for deprecation?

**Comment by lahuey** [comment]
@jarellm, could you try to use the Target App's Identifier Uri instead of the ID (i.e. https://graph.microsoft.com')?

**Comment by lahuey** [comment]
The AadTokenProvider is supported. Did you visit the API Management page? It's mentioned in these instructions -> https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient

**Comment by jarellm** [comment]
Yup admin has approved the spfx app to use the said APIs. I dont have the
screenshot with me right now, but I can confirm its there.

Using the API uri in the case of https://graph.microsoft.com actually works.

But using the default generated URI in the form of api://<app id> does not.

**Comment by lucabandMSFT** [comment]
so.. I assume that when you say "Using the API uri in the case of https://graph.microsoft.com actually works." it means that you used the AadTokenProvider class to fetch data / a token from Microsoft Graph endpoint, while the same call doesn't work if you replace Graph endpoint with your custom 3rd party ST/MT App Principal that has been already registeded and consented at tenant level.

is that correct?

if yes, can you confirm in AAD that such App Principal has been approved by the SharePoint Application in AAD?

a screen shot of your AAD Portal would be really helpful if possible.

**Comment by jarellm** [comment]
Yup that is correct.

This is the screenshot. We've added it manually via portal aside from the o365 API Admin Permissions page.

This is the screenshot of that shows we have 2 different Enterprise Apps for Sharepoint, one of which I presume is already deprecated.

![image](https://user-images.githubusercontent.com/10770226/56707838-19880c80-674d-11e9-9b2e-c3132f3cefc7.png)

Highlighted in red are the attached permissions to the API that we are trying to connect to:

![image](https://user-images.githubusercontent.com/10770226/56708022-c95d7a00-674d-11e9-8b1c-15e1ba431438.png)

This has also been approved in Sharepoint Admin API Management page

![image](https://user-images.githubusercontent.com/10770226/56708133-34a74c00-674e-11e9-8acc-6248b35b4249.png)

**Comment by mjarmstrong** [comment]
Running into the same issue as @jarellm

**Comment by lucabandMSFT** [comment]
hey @jarellm, thanks. did you create the service principal for your 3rd party application in the tenant?
Also, as an additional question, does your application has a different conditional access policy compared to SharePoint?

**Comment by jarellm** [comment]
Hi Luca,

Yes I did. I don't remember setting a different conditional access policy. Whatever was in the default, when Enterprise App was created.

![image](https://user-images.githubusercontent.com/10770226/57276382-00c81100-70d4-11e9-8005-d9a179c4066a.png)

**Comment by lucabandMSFT** [comment]
@jarellm , thanks for the additional information. two things:
1) I want to be sure about that: you are using the resourceURI as part of the call to aadHTTPClientFactory, yes? I know that some of our documentation has the guid documented but that's not the right way to do that (and, yes, we are aware of the documentation issue and we are fixining it right now)

2) if that still doesn't work.. would be possible to have a screen sharing session with you to understand more about the scenario?

**Comment by jarellm** [comment]
@luca

sorry for the late reply. Do you mean the field in the enterpise app that defaults to "api://<appid>"? then yes.

Otherwise, can you point me where this resource uri is?

Let me revisit the issue and send you a Skype invite. Please message me your skype id.

**Comment by lucabandMSFT** [comment]
it.. depends. It should be, realistically, an http endpoint. example here: 
![image](https://user-images.githubusercontent.com/46542683/58361996-6132ae80-7e47-11e9-814b-4d897d88e5d4.png)

**Comment by jarellm** [comment]
@lucabandMSFT , we are using the default value provided by AD when registering the app.

![image](https://user-images.githubusercontent.com/10770226/58759957-866c9e80-8564-11e9-9c5a-e0351e10e585.png)

![image](https://user-images.githubusercontent.com/10770226/58759961-93898d80-8564-11e9-8dbd-6adc4ae41eb0.png)

![image](https://user-images.githubusercontent.com/10770226/58759989-da778300-8564-11e9-930c-f124a7d3e774.png)

`
this.tokenFactory.getTokenProvider()
                         .then((provider) => { return provider.getToken('api://1512eb88-6e0c-43de-a894-45648181ecec/user_impersonation'); })
                         .then((token) => { console.log(token); });
`
Any suggestions?

**Comment by lucabandMSFT** [comment]
hey @jarellm can you please let me know what you mean when you say "I am able to get a token successfully by manually implementing the OAuth2 flow in an iframe"?

the api:// can't (or shouldn't be) resolvable from the browser (aka: the browswer doesn't know what that is). so, while AAD will return back the token for that endpoint, you cannot navigate, from the browser, to that endpoint. which is why you get that error /failure. Changing to https:// and making your API available externally should resolve the issue.
Thanks,
Luca

**Comment by jarellm** [comment]
@lucabandMSFT 


I meant the OAuth2 implicit flow which allows anyone with a valid session to get a token using the endpoint: 

https://login.microsoftonline.com/{tenant}/oauth2/authorize?client_id={clientid}&response_type=token&redirect_uri={redirecturi}&resource={app resource URI}

wherein {app resource URI} = api://guid  (this is where that value is actually used)


Without any help from a library such as adal.js or spfx, this can be done manually and transparently by using an iframe.

In this light, I think you're confusing the API resource URI with the redirect URI, wherein the redirect URI is resolved after the token request is granted. 

![image](https://user-images.githubusercontent.com/10770226/59347297-da3a6d00-8d46-11e9-87e1-5adbba38a91d.png)

I used a registered redirect URI and got the token with no problems using the method that I just described.

![image](https://user-images.githubusercontent.com/10770226/59347573-9b58e700-8d47-11e9-9093-36c9993d2a06.png)

True enough the App Resource URI (the value you were referring to that is supposed to be a resolvable URL) appears as the "aud" claim, as described in the tooltip.


![image](https://user-images.githubusercontent.com/10770226/59349588-964a6680-8d4c-11e9-8b46-41f8b00d08c3.png)

**Comment by lucabandMSFT** [comment]
Ok, I think I know where the problem is: you are trying to reach a V2 endpoint using ADAL.JS (we still use ADAL.JS behind the scene as well).
And that, to be fair, is us (Microsoft) making things little bit complicated for you as that's what we show in AAD UX as you pointed out above. 

in, short, to fix your scenario, can you try the following code instead?

this.tokenFactory.getTokenProvider()
                         .then((provider) => { return provider.getToken('api://1512eb88-6e0c-43de-a894-45648181ecec'); })
                         .then((token) => { console.log(token); });

Thanks,
Luca
