### ISSUE TITLE
New FlexPane_MeControl Error on Classic Experience

### ISSUE THREAD

**Issue by mirkori** [SharePoint/sp-dev-docs#3641]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When clicking on the user icon in the O365 NavHeader, it should open the new FlexPane_MeControl panel on the right side of the page.

#### Observed Behavior
This works only for modern experience. However, when enabling **classic experience** on a site
(e.g. demotenant.sharepoint.com/DemoDocs/Forms/AllItems.aspx )
The FlexPane does flicker and then immediately disappears again with the following error in the console:

`
suiteux.shell.vendor.....js:134
TypeError: Cannot read property 'Id' of null
    at suiteux.shell.core.....js:11
    at Array.map (<anonymous>)
...
`

The other Sidepanels (Notifications, Settings, Help) work as intended.

**Edit:**
This happens on Release preference setting: "Targeted release for everyone", on "Standard release" settings the old SidePanels are still active

**Comment by patmill** [comment]
Just making sure - this has nothing to do with the developer side of things correct, this is simply a "hey SP.  You've got a bug" correct?

**Comment by AJIXuMuK** [comment]
It looks like it might be also related to specific tenant or page. I can't reproduce it on any of my tenants.

**Comment by mirkori** [comment]
It seems the bug has been fixed in SP in the meanwhile. I will close that Issue.
