### ISSUE TITLE
Can't use supportedHosts: TeamsTab in SPFX 1.8

### ISSUE THREAD

**Issue by salahsaleh** [SharePoint/sp-dev-docs#3644]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

According to SPFX 1.8 documentation, it is possible to add "**`supportedHosts: TeamsTab`**" to web part manifest file in order to implement Microsoft Teams tabs using SharePoint Framework.

#### Observed Behavior

After adding the mentioned property ("`supportedHosts:TeamsTab`") to web part manifest file, execution of commands gulp serve or gulp bundle failed and after webpacking the following error message is displayed:

`[16:20:39] Error - [write-manifests] Manifest validation error (./src/webparts/myFirstTeamTab/MyFirstTeamTabWebPart.manifest.json):
    (#/) Data does not match any schemas from 'oneOf'
    (#/) Missing required property: description
    (#/) Missing required property: extensionType
    (#/componentType) No enum match for: WebPart
    (#/) Additional properties not allowed: supportedHosts
    (#/) Missing required property: items
    (#/) Missing required property: rootComponentId`

#### Steps to Reproduce

- Create new SPFX 1.8 project containing web part.

- Add property `"supportedHosts:["TeamsTab"]"` to web part manifest file. Here is screenshot of my manifest file:

![image](https://user-images.githubusercontent.com/6734481/54718065-138c8380-4b30-11e9-836b-05e2a51fe4b3.png)

- Run `gulp serve` or `gulp bundle` command, after which below error appears in console:

![image](https://user-images.githubusercontent.com/6734481/54718139-3f0f6e00-4b30-11e9-9e11-262efceec03e.png)

**Comment by patmill** [comment]
what changes did you make?  Are you starting from a blank / new project, or are you migrating an existing one? The image of the manifest looks different than a new project would generate.

**Comment by salahsaleh** [comment]
I haven't made any changes, just added the property and removed comments.
I am starting new project.

I followed [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab) to create Teams Tab using SPFX.

URL: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

**Comment by patmill** [comment]
Can you dump your package.json file here?  I've just created a new solution with 1.8.0 and not had any problems.  I've tried ship and debug builds, build, serve, bundle, package, etc.  What command are you running?

**Comment by salahsaleh** [comment]
@patmill 

Thanks after going to package.json, I came to know I was having SPFX v1.7

I upgraded to version 1.8 and this issue got resolve, but another issue arise.

**Comment by patmill** [comment]
Yes - the fixes to "sync with teams" are rolling.  If it is still not working in a few days, can you please open another issue?

**Comment by FullStackRafik** [comment]
Hello,
I get the same error when I upgraded to 1.8.0, my package.json doesn't indicate the version of SPFX.
Any suggestions please?

**Comment by karthikmakam** [comment]
Hi,
I am on latest version but still getting below errors when doing gulp serve:
Error - [write-manifests] Manifest validation error (./src/webparts/reactCarousel/ReactCarouselWebPart.manifest.json):
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/) Missing required property: extensionType
(#/componentType) No enum match for: WebPart
(#/) Additional properties not allowed: supportedHosts
(#/) Missing required property: items
(#/) Missing required property: rootComponentId

Any help/suggestions please.

**Comment by AnjaniChallamcherla** [comment]
@patmill Did the fixes for "Sync to Team" rolled out?
I am getting "Failed to sync solution to teams" error when I try to sync my SPFx app to team
Please suggest
![image](https://user-images.githubusercontent.com/42473451/60500410-33485180-9cb2-11e9-9869-c115f4770614.png)

**Comment by Evuri-SriDeepika** [comment]
We are also facing the same issue with "Sync to Teams". we are getting "Failed to sync solution to teams" error when we tried to deploy our sharepoint framework web-part to teams.
Any help/Suggestion ?
