### ISSUE TITLE
Failed to load URL 'react.js' for resource 'react' in component (2019 on prim)

### ISSUE THREAD

**Issue by HeinPauwelyn** [SharePoint/sp-dev-docs#3647]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I'm creating a webpart for SharePoint 2019 on prim. If I test that webpart on localhost, I don't have any problems. But when I open the workbench on the on prim SharePoint environment, I've got this error:

![Something went wrong](https://user-images.githubusercontent.com/16222780/54739514-ba1c6700-4bb8-11e9-8fee-fb6fd97da59d.png)

[Technical details on this bin.](https://pastebin.com/cF9BSsMR)

`gulp serve` is running.

I've found a similar problem over here #3621.

**Comment by patmill** [comment]
What changes have you made from the 2019 base code?  What version of the generator are you using?  What version of react are you using?

**Comment by HeinPauwelyn** [comment]
I'm accessing a SP list using `@pnp/sp` and rendering it in the web part.

This are the versions:

- @microsoft/generator-sharepoint: 1.8.0 _(global installation)_
- react: 16.3.2
- react-dom: 16.3.2

Content of `.jo-rc.json`:

```json
{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "onprem19",
    "version": "1.8.0",
    "libraryName": "temp-3",
    "libraryId": "376d1b81-109e-43e9-a89b-51b2ff8b4304",
    "packageManager": "npm",
    "componentType": "webpart"
  }
}
```

**Comment by HeinPauwelyn** [comment]
I've solved it by downgrading the react version said here: #3145
