### ISSUE TITLE
SelectedKey property is ignored when configuring a dropdown

### ISSUE THREAD

**Issue by patmill** [SharePoint/sp-dev-docs#366]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

copied over from stackechange
http://sharepoint.stackexchange.com/questions/205113/default-dropdown-option-propertypanedropdown-selectedkey-not-working/205601#205601

The issue is that this code doesn't set the SelectedKey
  PropertyPaneDropdown('test2', {
            label: 'Dropdown',
            options: [
              { key: '1', text: 'One'},
              { key: '2', text: 'Two' },
              { key: '3', text: 'Three' },
              { key: '4', text: 'Four'}
            ],
            selectedKey: '4',
        })

**Comment by mpasarin** [comment]
This has been fixed.
