### ISSUE TITLE
How to remove deployed files from Azure CDN ?

### ISSUE THREAD

**Issue by michaelmaillot** [SharePoint/sp-dev-docs#3660]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When removing sppkg solution from App Catalog, It would be nice that it removes also deployed files on the Azure CDN, or through a gulp task (like deploy-azure-storage).

#### Observed Behavior

When removing the sppkg from the App Catalog, the deployed files are still on the CDN.

#### Steps to Reproduce

- Create, configure and deploy a SPFx WebPart, based on the Microsoft Documentation : https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn

- Test the WebPart and confirm that deployed files are in the Azure CDN.

- Remove the sppkg solution from the App Catalog and go the Azure Blob Storage to see that files are still deployed.

**Comment by lucabandMSFT** [comment]
Thank you for your feedback.
the current flow assumes that the developer is in charge to deploy the file in the CDN and not the end user.
The way you are describing the flow would create problems if, for example, I'm a developer and I sell or deploy my solutions to multiple customers / tenant.
