### ISSUE TITLE
Error in Connect your client-side web part to SharePoint (Hello World part 2)  

### ISSUE THREAD

**Issue by arpan426** [SharePoint/sp-dev-docs#3662]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Article Url: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint

Connect your client-side web part to SharePoint (Hello World part 2) ---- Fetch the list data

#### Observed Behavior

I have followed all the step and I have successfully implement the HelloWorldWebpart. 
But when I am trying to fetch list date I am getting the blow error.

private _getMockListData(): Promise<ISPLists> {
    return MockHttpClient.get()
      .then((data: ISPList[]) => {
        var listData: ISPLists = { value: data };
        return listData;
      }) as Promise<ISPLists>;
  }

Error: 
Argument of type '(data: ISPList[]) => ISPLists' is not assignable to parameter of type '(value: ISPList[]) => ISPLists | PromiseLike<ISPLists>'.
  Types of parameters 'data' and 'value' are incompatible.
    Type 'import("/Users/AC/Desktop/Projects/SPFX/helloworld-webpart/src/webparts/helloWorld/HelloWorldWebPart").ISPList[]' is not assignable to type 'import("/Users/AC/Desktop/Projects/SPFX/helloworld-webpart/node_modules/@microsoft/sp-page-context/dist/index-internal").ISPList[]'.
      Type 'ISPList' is missing the following properties from type 'ISPList': id, permissions, serverRelativeUrl, titlets(2345)

#### Steps to Reproduce

Follow the steps into the article

**Comment by bcameron1231** [comment]
Are you able to share your solution? I went through the tutorial on that page for both the mock data and retrieving SharePoint List data, and it is successful for me. 

It looks like it is trying to use the ISPList interface from the internal Microsoft node module, instead of the interface being used in the tutorial.
