### ISSUE TITLE
Command line switches for --skip-feature-deployment and --is-domain-isolated produce invalid results

### ISSUE THREAD

**Issue by eshupps** [SharePoint/sp-dev-docs#3663]
There are two critical issues with this documentation. First, the --skip-feature-deployment and --is-domain-isolated options are implemented as boolean switches without default values in the underlying code. They do not, as the documentation suggests, implement string handling for the values specified.  The second, and more problematic issue, is that the lack of default values means that any strings passed to the commands are inserted into the package-solution.json file as string literals instead of boolean values, causing the gulp build tasks to break. There is no way from the command line to set either of those values to false; omitting them simply causes the generator to prompt for input, which is not the desired behavior.

An issue was opened for this in v1.7.0.0, which was supposedly fixed, but the problem still exists in v1.8.0.0 and the documentation has never been updated. Refer to issue #3042 in the GitHub repo for a detailed example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2345258-f135-178a-a5af-9705ebafa081
* Version Independent ID: 90ee54a0-1409-6f4d-5018-c9f3e26e46ef
* Content: [Scaffold projects by using Yeoman SharePoint generator](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator#feedback)
* Content Source: [docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I see you provided more detail in the original referenced issue... I re-opened that issue, updated the title to show it's now a bug (not a doc issue) and will close this one as a dupe. Thanks!
