### ISSUE TITLE
SPFx webpart stuck in "Loading..." mode in Internet Explorer 11 with Document Mode 10 on classic pages

### ISSUE THREAD

**Issue by MFSWE** [SharePoint/sp-dev-docs#3664]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SPFx webpart needs to work in Internet Explorer 11 with Document Mode 10 on classic pages.

#### Observed Behavior
We have several custom SPFx webparts on a classic page in SP Online. When using Internet Explorer 11 in Document Mode 10 the webparts are stuck in "Loading..." mode and will not render. I can see that the language files of each webpart are loaded but the bundle-/code files are not loaded. No error or warning that can be related to this is shown in the browser console.

The same webparts set up on a modern page work without issues.

I've tried adding only one single SPFx webpart to a classic page but still the webpart gets stuck "Loading..."

Reloading the page (pressing F5), the webparts load just fine.

Everything works as expected in Chrome, Edge and Firefox.

#### Steps to Reproduce

1. Create a SPFx React webpart.
2. The JS-files are located in a normal SP library, I am not using a CDN.
3. office-ui-fabric-react.bundle.min.js and pnp.min.3.0.10.js are set as externals and are not bundled
4. Add the webpart to a classic page
5. Use Internet Explorer 11. Open Developer Tools and set Document Mode to 10.
6. Set the cursor in the address bar and press RETURN.
7. The page should now load normally except for your webpart that is stuck "Loading..."

Any input/help is appreciated!
Regards, 
Magnus

**Comment by patmill** [comment]
Before diving in too far, why are you setting the document mode to 10?

**Comment by MFSWE** [comment]
Setting Document Mode 10 is the only way for me to reproduce the problem our customer has. They experience the problem when using IE in Document Mode 11. I do not have that problem in Document Mode 11, but when switching to Document Mode 10 i can reproduce the issue.

**Comment by cameronsibbald** [comment]
@MFSWE We had a similar problem that ended up being related to missing polyfills in IE. It might be a good place to start, especially since things seem to work in modern browsers. 

https://pnp.github.io/pnpjs/documentation/polyfill/

**Comment by lucabandMSFT** [comment]
@cameronsibbald , was Pat's answer providing you any help?

**Comment by cameronsibbald** [comment]
@lucabandMSFT - It doesn't look to me like Pat's answer provides any help. He's asking for some additional info from @MFSWE. 

As mentioned in my comment, we encountered an issue that manifested itself in a similar way to what @MFSWE was describing and solved it by adding some missing polyfills. I was just sharing that information in hopes that it might be helpful here.

**Comment by lucabandMSFT** [comment]
sorry, the question was referred to @MFSWE . Apologies for my error and thanks for your reply.

@MFSWE , can you please try the suggestion @cameronsibbald  provided and report if that addresses your scenario?

**Comment by mcmynn83** [comment]
We only support IE 11 in its native mode.  We do not support IE 11 in all of its different document modes.
