### ISSUE TITLE
Modern Page Comments - Shows Duplicates

### ISSUE THREAD

**Issue by jashwanthreddyn** [SharePoint/sp-dev-docs#3666]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We have comments enabled on site pages. We're seeing duplicate comments. We had similar behavior back in december. 

This happens if you go to site page from news webpart. And if you open the site page in a new window/tab or refresh the page, we don't see duplicate comments. 

Please see below from production tenant. As highlighted, count is accurate but I think its getting rendered twice. 

![image](https://user-images.githubusercontent.com/33126513/54840933-7c950800-4ca4-11e9-9914-d5fe3f0dc1c2.png)

Browser inspect 
![image](https://user-images.githubusercontent.com/33126513/54841215-2c6a7580-4ca5-11e9-850d-f69462640b2a.png)

Please let me know if you need additional info. 

Thank you for your time !

**Comment by jashwanthreddyn** [comment]
Hi - Any update, please ?

**Comment by evobis** [comment]
We have the same issue on several customers. For some this is a major issue. Are there any update on this ?

**Comment by makelana** [comment]
We have the same issue, too. Just for Info... please fix it.

**Comment by jashwanthreddyn** [comment]
Update from MS Support Engineer "identified a code issue that was introduced in a recent SharePoint Online update. Reverted the change and deployed a fix to mitigate the issue." 

This issue is resolved on our tenant.

**Comment by HandyAndyOnGitHub** [comment]
I noticed this comment-duplication issue for the first time in our Tenant yesterday (13 June 2019).  Has this issue been re-introduced or is the fix still in the deployment process?

**Comment by magnus-goransson-altitude365-com** [comment]
I have one customer that are facing this issue as well. They are using modern pages and only standard web parts. No custom code.

The duplicated comments are a big issue to them as they are trying to push end users to comment on all the news pages. Let me know if you need URL's or anything to troubleshoot and see the problem.
