### ISSUE TITLE
Connect-PnPOnline with Legacy auth disabled

### ISSUE THREAD

**Issue by rachoksh** [SharePoint/sp-dev-docs#3667]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Has anyone figured out how to Connect using Connect-PnPOnline PowerShell for **unattended** scripts with **Site Collection admin permissions**  when legacy authentication in the O365 Tenant  is turned off with this command **Set-SPOTenant -LegacyAuthProtocolsEnabled $false** ?  Thanks in advance!

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
If you are writing unattended scripts, are you using Application Credentials? This would be the preferred and recommended approach for unattended scripts.

**Comment by rachoksh** [comment]
Yes, we are trying to use the AppId and AppSecret. They want Site Collection Administrators to be able to run these PnP PowerShell Scripts.  I found this post which seems to say you can connect to Graph but for connecting to SPO you need a SharePoint Addin - https://techcommunity.microsoft.com/t5/SharePoint-Developer/PnP-PowerShell-Connect-PnPOnline-using-AppId-gives-Access-denied/td-p/140958.
Text from above link:
Using the syntax "Connect-PnPOnline -Url $siteUrl -AppId $appId -AppSecret $appSecret" connects using SharePoint App-only permissions as described here. **Using this method you need to register the app using SharePoint (not the graph).**

**Comment by bcameron1231** [comment]
You can register the powershell application the same way you'd register an add-in in SharePoint to give it the permissions it needs.

Here is an example we use for connecting to SharePoint using app credentials for provisioning.
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning#set-up-app-only-access-to-your-tenant

**Comment by rachoksh** [comment]
This works but needs to be granted Full control at tenant level. Can the AppID and AppSecret be limited to a site collection so end users can run unattended scripts to sync site content, javascript files from DEV to UAT to Production site collections? Thanks

**Comment by bcameron1231** [comment]
You can lower it to Site Collection level, but I do not believe you can scope it to a specific site collection. If end users are going to be run scripts like this, the best and most secured way would be to make them use their credentials to do the execution. 

If end users have the ability to read the client secret, this is a security risk and should be avoided.

**Comment by rachoksh** [comment]
Today I did tell the customer that we should not hand out the AppID / Appsecret and IT admins should work with site collection admin to create specific unattended scheduled task to sync the site content. I also suggested this certificate option : https://mmsharepoint.wordpress.com/2018/12/19/modern-sharepoint-authentication-in-azure-automation-runbook-with-pnp-powershell/. Thanks for your guidance.
