### ISSUE TITLE
Remove css styles if extension/webpart is disposed

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#3669]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

spfx 1.8.

I noticed that each time an extension/webpart is disposed the css referenced to the page is not destroyed. E.g: an spfx extension for custom site header is disposed when moving between site/pages but the css `<style/>` is still intact on `<head>` and isn't removed. Is it possible to clean the css as well?

**Comment by andrewconnell** [comment]
Closing as appears this is a dupe of #3461
