### ISSUE TITLE
Error When Adding Add In to Site

### ISSUE THREAD

**Issue by WorTony** [SharePoint/sp-dev-docs#3671]
Hi,
I’ve tried deploying the Addin to a classic and a modern site Coll - an error occurs and the Addin is not added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4f0dcc-bd27-abf1-0fa6-a602ebe949ef
* Version Independent ID: 6c451da4-39b0-296f-aa6b-b0a1c57c2dea
* Content: [Corporate event add-in integration with SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/corporate-app-event-registration-with-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Corporate-app-event-registration-with-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Corporate-app-event-registration-with-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by WorTony** [comment]
Hit send to soon .....

I wanted to see if anyone else had experienced such a problem?

**Comment by patmill** [comment]
Can you give some more information and context?  It should work.
