### ISSUE TITLE
Why shared component called as Library component ?

### ISSUE THREAD

**Issue by manoj1201** [SharePoint/sp-dev-docs#3673]
Documentation say's it's used as shared component. Same can be referenced to other component as dependency. The word "Library" component is quite confusing. It seems like i.e. related to document library. Can it be better name ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b431da26-3a26-bab5-1af4-a151d9e50f2e
* Version Independent ID: 50656bd9-3514-ae39-0805-0927d30e4355
* Content: [Using library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview#feedback)
* Content Source: [docs/spfx/library-component-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I can see the confusion there, but when talking about code, _library_ is a common name. Think DLL... a _dynamic linked library_ is just a binary of shared code used by other processes. This follows the same model.

If you don't like the name, that's probably best suited as a User Voice submission (feature request / design change request) and posted here: https://aka.ms/sp-dev-uservoice
