### ISSUE TITLE
Error navigating between SPFx SPAs

### ISSUE THREAD

**Issue by olemp** [SharePoint/sp-dev-docs#3674]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When navigating between several SPFx SPAs (on different pages obviously) through the global navigation HUB menu, I expect the components to load correctly.

#### Observed Behavior

When navigating between several SPFx SPAs (on different pages obviously) through the global navigation, I get the following error:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

SPFx v1.7.1

#### Steps to Reproduce

Create several SPAs.
Add them to the global (or local) navigation.
Attempt to navigate between them

**Comment by mcmynn83** [comment]
Thanks for reporting the issue.  We are aware of the issue and I have made a fix locally which will roll out within the next few weeks.

**Comment by mcmynn83** [comment]
This is fully rolled out to prod now.
