### ISSUE TITLE
New Footer in theme does not honour SharePoint settings to hide site creation button

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#3675]
To replicate create a new communication site. There will be a new footer with the words:
Powered by SharePoint communication sites. Click here to create your own. Get Mobile App.
![spfooter](https://user-images.githubusercontent.com/17725046/54914795-b9a00b00-4eed-11e9-8606-f6abb3e648c4.png)

This does not honour the settings option in the admin centre, allowing users to create sites.
![settings](https://user-images.githubusercontent.com/17725046/54914902-f8ce5c00-4eed-11e9-9c96-1c78c2b8fa1d.JPG)

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

Expected behaviour is to not see the link to create new communication sites. Only workaround is to remove the footer via script globally looping through the sites.

**Comment by lucabandMSFT** [comment]
Thanks for your feedback.
This channel is for developer related issues. We will certainly provide the feedback to the right team that own Communication sites but I'm closing this issue here in Git Hub
