### ISSUE TITLE
Signing out does not sign out from list form Power app

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/sp-dev-docs#3678]
I don't know if this is the right group but wanted to bring this attention to this serious situation. Create a simple list and modify form with PowerApps. The best way to reproduce it would be to have a lookup field with item level permissions on lookup items so one users have access to different items. 
Steps:
1. login in with user ONE, open the list add item
2. sign out, 
3. sign in with user TWO, add item and see lookup values from previous user. 

I think this is serious issue especially on kiosk machines. 
Are there any recommendation on how to force sign out?
 
#### Category
- [ x] Bug

Thanks
Saulius

**Comment by Saulius-Laurinaitis** [comment]
Referencing PowerApps Community post: https://powerusers.microsoft.com/t5/General-Discussion/Signing-out-portal-office-com-does-not-sign-out-from-SharePoint/m-p/257562#M75390

**Comment by andrewconnell** [comment]
Seems like it's best to address over in the PowerApps forum where you've posted it and had some response from MSFT... best to keep just one thread going...
