### ISSUE TITLE
Not display modal view on click custom-formatting-lookup column. 

### ISSUE THREAD

**Issue by tomasgazsi** [SharePoint/sp-dev-docs#3680]
I customize my lookup column with JSON formatting. But when clicked on item in this column there's problem with display modal view (probably the class of the modal view is "od-IFrameDialog") and this view not support on the custom formatting lookup column. 

![image](https://user-images.githubusercontent.com/43842556/54944035-e9bdcd00-4f32-11e9-9e15-fb6fd1481115.png)

After click 758 number, nothing happens. 
But after click on 2 565, whitch is the same type of column as Obj. dopravce, it show this window.
![image](https://user-images.githubusercontent.com/43842556/54944253-60f36100-4f33-11e9-84a5-effa4ce90570.png)

Have anybody idea how to solve this? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@thechriskent @bcameron1231

**Comment by bcameron1231** [comment]
Unfortunately, I do not believe what you are trying to do is supported by Column Formatting. @thechriskent can probably confirm, but the click events that are registered would not be picked up by the customization.

An option, could be to provide a link to the item in a new window, by constructing a URL to the lookup list. Not the same experience, but another way around it.

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "debugMode": true,
  "elmType": "a",
  "txtContent": "@currentField.lookupValue",
  "attributes":{
  "href":"=@currentWeb + '/Lists/YourLookupList/DispForm.aspx?ID=' + @currentField.lookupValue",
  "target":"_blank"
  }
}
```

**Comment by tomasgazsi** [comment]
Yes, then I solved it with link to the item in new window. Thanks for help.
