### ISSUE TITLE
Hide custom Sharepoint Classic Ribbon

### ISSUE THREAD

**Issue by Sylar007** [SharePoint/sp-dev-docs#3683]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi there,

Need you help regarding SPFX.
Currently we work on migrating from classic exp for Document Library to Modern exp. I'm having difficulties to hide the existing Ribbon Button. We have develop a new Ribbon Button using SPFX and it's working fine. But now we have 2 ribbon coexist in same library (Existing & New ribbon button). 

My question, how do we hide the existing Ribbon Button?
I tried to set the element (existing button) to be style.display="none" but it won't work.

Regards

#### Expected or Desired Behavior
Remove existing custom Ribbon Button when switch to Modern Experience Library

**Comment by andrewconnell** [comment]
At the current time, SPFx does not provide an API to hide existing buttons in the toolbar.

The way you are trying to hide it, using CSS, is DOM manipulation which is not recommended or supported in SPFx.
