### ISSUE TITLE
Adding items to the default SharePoint online navbar programmatically

### ISSUE THREAD

**Issue by tpf89** [SharePoint/sp-dev-docs#3684]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I think it would beneficial for everyone if we were able to manipulate (in my case: add items/links) the default SharePoint Online navbar with SPFx extensions programmatically. I could be used to add dynamic links, depending on the user context for example. 

The status quo is that we are able to add/create a custom navbar, additionally to the default navbar and the user can edit the default navbar manually. Or am I missing something? Everything I found via Google leads me creating a separate navbar via the top placeholder. 

On the other I am of course able to manipulate the DOM and add ms-HorizontalNavItems, but it's a bad idea and bad practice for known reasons.

**Comment by patmill** [comment]
At the moment, there is no way to modify the nav at run-time (please feel free to open a user-voice request).  I agree with the scenario as a possible future type of extension, but there is nothing today.

But, I'm not sure if you are asking for that, or asking if you can make changes to the underlying persisted data.  Ie, I would like to permanently add link foo to navigation.  If it is the latter, there is an API for managing the nav nodes in SharePoint - you just need to know which navigation collection you want to modify.
