### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by kevinguyer** [SharePoint/sp-dev-docs#3687]
I believe that the line that reads 'In the code editor, open the ./src/webparts/listInfo/IListInfoWebPartProps.ts file, and extend the interface definition with the listName property of type string.' should refer to the file './src/webparts/listInfo/ListInfoWebPart.ts' instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08aa20fb-4cde-4ea6-8946-d67451e78e55
* Version Independent ID: 3c47f3e6-427a-681d-42c7-db0a821da0e9
* Content: [Validate web part property values](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values#feedback)
* Content Source: [docs/spfx/web-parts/guidance/validate-web-part-property-values.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/validate-web-part-property-values.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi @kevinguyer The documentation is correct. This line is referring to modifying the interface for the IListInfoWebPartProps. This is located inside a file called "IListInfoWebPartProps.ts". 

I have circled it in red in the below image.
![image](https://user-images.githubusercontent.com/7944457/55041504-f144ab00-4ff2-11e9-8dd5-dc1f38a460f5.png)
