### ISSUE TITLE
Please ad the actual solution id to entry properties when calling "AvailableApps"

### ISSUE THREAD

**Issue by spcph** [SharePoint/sp-dev-docs#3688]
Currently you only list the internal id of the solution. Without the actual solution id, the one coming from package-solution.json, we have no way of getting the internal id for a solution we already know the actual id for. The current lack makes working with site scripts and the "InstallSolution" verb really annoying, as I have to install the solution before I can actually create the site script. Not really ideal for ISVs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good suggestion, but the best place for feature requests is UserVoice https://aka.ms/sp-dev-uservoice as that's where MSFT triages feature reqests.
