### ISSUE TITLE
Application Customizers: skipFeatureDeployment enabled but without ClientSideInstance.xml included in package

### ISSUE THREAD

**Issue by maps05** [SharePoint/sp-dev-docs#3690]
For Application Customizers I've identified three different outcomes with this feature:

1. skipFeatureDeployment is false
    Extension not deployed in site collections. Extension visible in site collections' "Add App" option.
2. skipFeatureDeployment is true and ClientSideInstance.xml included in package
    Extension deployed in all site collections, using the clientSideComponentProperties defined in the ClientSideInstance.xml
3. skipFeatureDeployment is true and ClientSideInstance.xml NOT included in package
    Extension not deployed in site collections. Extension NOT visible in site collections' "Add App" option.

Scenario 3 is not clearly documented here. Not sure if it's an intentional scenario or not, but functionally is valid as there may be application customizers which required specific clientSideComponentProperties per site. Therefore they can't be deployed centrally with the same config and neither should be added by regular regular end-users, so it should be hidden in the "Add App" option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e41df74-a651-cfa5-a538-9397e6793f52
* Version Independent ID: 9f272325-fdb3-68e3-634b-e7428128f75b
* Content: [Tenant Wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions)
* Content Source: [docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Sorry - not exactly sure what you are asking.  You're statements are correct - #3 is a supported scenario.  It basically means "yes, this component is available for use in the tenancy, but it has not been configured to run anywhere".  You would need to either add your own entries to the tenant wide deployment configuration list, or add your own entries to the SPCustomAction collection on the specific location you want it to run.

**Comment by maps05** [comment]
Apologies for not being clear. It was not a question, rather feedback that there's information missing concerning the behavior that you've just described. It is said in the article that the ClientSideInstance.xml can be excluded from the package but it's not explained what's the outcome of that. A simple one liner similar to what you've said would be very helpful.

I've had already to showcase scenario 3 to clients (and even to other developers) because I can't provide documentation to it. Not to mention that it's something easily missed by a developer trying this feature for the first time, with the new scaffolding.

**Comment by andrewconnell** [comment]
@maps05 said:
> there's information missing concerning the behavior that you've just described

Actually, it is already documented in this article... copied straight from the doc:

> ClientSideInstance.xml is taken into account in the solution activation at the app catalog if the skipFeatureDeployment attribute is set to true in the package-solution.json file.
