### ISSUE TITLE
SP 2019 - Command Set extension, dynamic data

### ISSUE THREAD

**Issue by dkorolev1** [SharePoint/sp-dev-docs#3691]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi everyone,

I need to implement the file preview feature in SharePoint 2019. When a user selects a file in the library view, I want to show its preview on the right side of the page. So, I planned to use SPfx Command Set extension, SPFx Webpart and dynamic data functionality. The extension determines updates in the list view (item(s) is selected or unnselected) and sends updates to my preview web part using the dynamic data feature. We are talking about the modern UI.

And here I have a couple of questions:
1. Is there a better way to subscribe to List (lib) View updates than using SPfx Command Set extension?
2. Can I use the dynamic data functionality in SP 2019?

Any other suggestions, workarounds how it may be implemented, are welcome as well.

@andrewconnell , perhaps, you could give some recommendations? Thanks!

**Comment by andrewconnell** [comment]
The ability to subscribe to lists & dynamic data are not available in SharePoint 2019; they are only available in SharePoint Online. Both features were added after January 2019... SP2019 is based on SPO from January 2019.

**Comment by dkorolev1** [comment]
@andrewconnell are there any other options for subscribing to the selection changed event in the list view? (modern look, sp2019).

**Comment by andrewconnell** [comment]
No that I'm aware of...
