### ISSUE TITLE
SPFx Gulp Package-Solution --Ship Error

### ISSUE THREAD

**Issue by patrickabel** [SharePoint/sp-dev-docs#3694]
I am in the process of completing some feature updates to a SPFx extension (Application Customizer) that hasn't been modified in approx a year. I've completed my changes and can successfully build, serve, and debug my extension locally. Everything is working great, but I'm running into some trouble with deployment.

Bundling appears to be completing successfully (`gulp bundle --ship`), but **I'm running into the following error trying to package the solution (`gulp package-solution --ship`)**:

> **Could not find Element Manifest: sharepoint\assets/elements.xml**

Can anyone offer some guidance regarding what could cause this error and how best to troubleshoot?

#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

the ability to execute `gulp package-solution --ship` without error.

#### Observed Behavior

Here is the detailed output and error I'm seeing trying to `gulp package-solution --ship`:

> PS C:\s7sgit\IBSA\spfx\extensions\ibsa-spfx-extensions> gulp package-solution --ship
> Build target: SHIP
> [14:55:42] Using gulpfile C:\s7sgit\IBSA\spfx\extensions\ibsa-spfx-extensions\gulpfile.js
> [14:55:42] Starting gulp
> [14:55:42] Starting 'package-solution'...
> [14:55:42] Starting subtask 'configure-sp-build-rig'...
> [14:55:42] Finished subtask 'configure-sp-build-rig' after 5.67 ms
> [14:55:42] Starting subtask 'package-solution'...
> [14:55:42] [package-solution] Found manifest: C:\s7sgit\IBSA\spfx\extensions\ibsa-spfx-extensions\temp\deploy\90fa8f0c-3a3f-4a42-adc4-f86985a7a572.json
> [14:55:42] [package-solution] Found client-side build resource: ibsa-app-insights-application-customizer_5c1a7f415ba2be16ecf4cb1b7cbccd1f.js
> [14:55:42] Verifying configuration...
> [14:55:42] Done!
> [14:55:42]
> [14:55:42] Normalizing solution information...
> [14:55:42] Attempting creating component definitions for {1} manifests
> [14:55:42] Created component definitions for {1} manifests
> [14:55:42] feature.componentIds not set! Adding all [1] components to feature { Application Extension - Deployment of custom action. }.
> [14:55:42] Done!
> [14:55:42]
> [14:55:42] Reading custom Feature XML...
> [14:55:42] Done!
> [14:55:42]
> [14:55:42] Validating App Package...
> [14:55:42] Done!
> [14:55:42]
> [14:55:42] Reading resources...
> [14:55:42] Done!
> [14:55:42]
> [14:55:42] Reading Sharepoint Assets & Creating XML...
> [14:55:42] Error - 'package-solution' sub task errored after 51 ms
>  Could not find Element Manifest: sharepoint\assets/elements.xml
> [14:55:42] 'package-solution' errored after 60 ms
> [14:55:42]
> [14:55:42] ==================[ Finished ]==================
> Error - 'package-solution' sub task errored after 51 ms
>  **Could not find Element Manifest: sharepoint/assets/elements.xml**
> [14:55:43] Project ibsa-spfx-extensions version:0.0.1
> [14:55:43] Build tools version:3.9.7
> [14:55:43] Node version:v8.15.1
> [14:55:43] Total duration:5.27 s
> [14:55:43] Task errors:1
> The build failed because a task wrote output to stderr.
> Exiting with exit code: 1
> PS C:\s7sgit\IBSA\spfx\extensions\ibsa-spfx-extensions>

**Comment by arnieraju** [comment]
@patrickabel I am running into a similar issue at the moment.  Did you end up resolving yours?
