### ISSUE TITLE
Column formatting - calc not allowed in height style property

### ISSUE THREAD

**Issue by zypA13510** [SharePoint/sp-dev-docs#3696]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Be able to use [`calc()`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc)([caniuse](https://caniuse.com/#feat=calc)) in dimensional properties e.g. width/height.
This is required for a custom formatted column to fill the entire height of the table cell (in case there're multiple lines of text, possibly due to wrapping):
```CSS
height: calc(100% + 22px); /* the parent div has 11px padding both at top and bottom */
```

#### Observed Behavior

It seems using ( inside of a style value is not allowed.
> Failure: The style values 'calc(100% + 22px)' contains one or more of the following disallowed characters ( : & ; ! .

#### Steps to Reproduce

1. Paste the following into the column formatting of any supported column.
    ```JSON
    {
      "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
      "elmType": "div",
      "children": [
        {
          "elmType": "span",
          "txtContent": "@currentField",
          "style": {
            "padding": "0 8px",
            "white-space": "nowrap"
          }
        }
      ],
      "attributes": {
        "class": "sp-field-dataBars"
      },
      "style": {
        "padding": "0",
        "height": "calc(100% + 22px)",
        "width": "100%"
      },
      "debugMode": true
    }
    ```
2. Create another text column
3. Create a new row, fill the text column with a lot of text so that it is wrapped to the second line and stretch the height of the row.

(Step 2 and 3 is only here to demonstrate why using `calc()` is required)

**Comment by zypA13510** [comment]
Related: #1161

**Comment by andrewconnell** [comment]
@thechriskent @bcameron1231

**Comment by PopWarner** [comment]
As @zypA13510 noted, when using debugMode, SP returns:

> Failure: The style values 'calc(100% + 22px)' contains one or more of the following disallowed characters ( : & ; ! .

@thechriskent would be able to confirm best, but by calc() using a "(", the parser will not execute it. (The exception being rgba() as noted in #1161)

Likely the best step would be to open a UserVoice request if this is accurate?
https://sharepoint.uservoice.com/

**Comment by andrewconnell** [comment]
Good point... if the expression in `calc()` is not currently supported, then that woudl be a feature request and those are best submitted to UserVoice: https://aka.ms/sp-dev-uservoice
