### ISSUE TITLE
Deprecating legacy Fabric CSS consumption

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#3697]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Does this mean that ms-Grid (Fabric layout https://developer.microsoft.com/en-us/fabric#/styles/layout) will stop to work? What other functionality will stop to work?

In my case Fabric grid stop to work after upgrading

**Comment by andrewconnell** [comment]
I fairly certain the grid is *not* affected, but you can test a solution that that uses SPFx v1.8 and the `ms-Grid` class. If it still works, you're good.

Everything in the **@microsoft/sp-office-ui-fabric-core** is still good... they just removed stuff they were adding to the rendered pages automatically and thus reduced the page weight.

**Comment by shashank2490** [comment]
ms-Grid classes are not working for me on neither 1.8.0 nor 1.8.1.

my package.json file

{
  "name": "sample",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.8.1",
    "@microsoft/sp-property-pane": "1.8.1",
    "@microsoft/sp-webpart-base": "1.8.1",
    "@microsoft/sp-lodash-subset": "1.8.1",
    "@microsoft/sp-office-ui-fabric-core": "1.8.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "@microsoft/rush-stack-compiler-3.3": "0.1.6",
    "@microsoft/sp-build-web": "1.8.1",
    "@microsoft/sp-module-interfaces": "1.8.1",
    "@microsoft/sp-tslint-rules": "1.8.1",
    "@microsoft/sp-webpart-workbench": "1.8.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "3.3.4000"
  }
}

Please suggest
