### ISSUE TITLE
getPreview.ashx SVG support?

### ISSUE THREAD

**Issue by cslecours** [SharePoint/sp-dev-docs#3700]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [x] Additional article idea

Applies to : SharePoint Online

#### Expected or Desired Behavior

I should be able to get a svg preview using getPreview.ashx.

#### Observed Behavior

In a site collection, I have a svg image in a document library. 
I want to be able to see this image when I have a limited access. 
I use the `/layouts/15/getPreview.ashx` handler to do that.

When I get  `/layouts/15/getPreview.ashx?action=supportedTypes`. I see that svg is supported, but when I try to get the svg image via this handler, I have a http 501 response with no body.

#### Steps to Reproduce

Upload a svg image to a document library (to make things easier, ensure that the site collection url has no weird characters such as spaces or accents).

myImageUrl = Complete image url beginning with https://{tenantName}.sharepoint.com
MYIMAGEURLENCODED = encodeURIComponent(myImageUrl);

GET /layouts/15/getPreview.ashx?path=MYIMAGEURLENCODED

Any help would be appreciated !
Thanks, 
Charles

**Comment by andrewconnell** [comment]
@StfBauer have you tried to get a preview of user uploaded SVG's?

**Comment by StfBauer** [comment]
getPreview.ashx service is for binary files only. 

It won't make sense to use it for Scalable Vector Graphics which is only a text file and rendered by the browsers just like HTML.

The images preview, in the end, would be potentially bigger than the content of the actual SVG file.

I did a short test and when the service is used it only downloads a blank file. I can confirm that this is not supported and doesn't need to support from my point of view.

I haven't tested the `action=supportedTypes` but it is more a bug that it is listed there as a supported type.
