### ISSUE TITLE
Issues with SharePoint "Read" privilege with Client App

### ISSUE THREAD

**Issue by code2expert** [SharePoint/sp-dev-docs#3706]
I'm working on a classic ASP page with VBScript API calls and I can't seem to read files from SharePoint Online(SPO) folders even though I can do it via the browser. I am not an admin and I do have access to read the files through the browser. Can you advise on the best approach.

This a copy of the code I'm using, it returns error 403: ACCESS DENIED:

            Dim restReq, url
            'create a JSON request object to interact with Sharepoint
            Set restReq = CreateObject("Msxml2.XMLHTTP")
            restReq.async = false
           url = "http://&lt;tenant url&gt;.sharepoint.com/sites/_api/web/GetFolderByServerRelativeUrl('/Shared Documents')"
            '  Indicate that we want a XML+ATOM reply
              restReq.Accept = "application/atom+xml"

            'make the API call to sharepoint by opening the endpoint and making the call, in this case to check if a file exist in the specified folder
            call restReq.open ("GET", url, false)
            call restReq.send()
            
            response.write(restReq.status)
            response.write(restReq.responseText)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
I feel like you are missing the entire auth flow here...

**Comment by bcameron1231** [comment]
To expand on what Pat is saying, is it looks like you are just trying to execute a request to SharePoint Online, but you haven't authenticated yet. You will need to register this application with SharePoint, in order to request a token to execute requests against SharePoint.

However, I have another concern. If you do not have access to view the files via the Browser. Your application also will not have access to read those files as it would execute under your permissions.

**Comment by andrewconnell** [comment]
Please see the response I left for your other issue #3681

**Comment by code2expert** [comment]
Thanks for your feedback. I do have read access to the folders via the web browser and I am not the administrator. I will take a look at the links to get a better feel of how to authenticate and revert back if I’m still facing problems. 

I would also like to know if the authentication methods exist in vb scripts running in classic asp....

**Comment by andrewconnell** [comment]
I've never seen code samples for authenticating using OAuth and obtaining an access token for VBScript with classic ASP. You can do it, but never seen scripts for it nor are their libraries published by Microsoft.
