### ISSUE TITLE
Small type-o 'Framweork'

### ISSUE THREAD

**Issue by RobinAgten** [SharePoint/sp-dev-docs#3707]
There is a small type-o in the first paragraph on the second line:
Framweork --&gt; Framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b431da26-3a26-bab5-1af4-a151d9e50f2e
* Version Independent ID: 50656bd9-3514-ae39-0805-0927d30e4355
* Content: [Using library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview#feedback)
* Content Source: [docs/spfx/library-component-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by cslecours** [comment]
This was fixed by #3704

**Comment by andrewconnell** [comment]
@cslecours in the future if you include the text "fixes #3707", when the PR is merged, it will trigger github to automatically close the referenced issue, also sparing you from having to include a [comment like this](https://github.com/SharePoint/sp-dev-docs/issues/3707#issuecomment-478701099).

See the "References" section in this doc for more details: https://guides.github.com/features/issues/#notifications
