### ISSUE TITLE
custom dialog sample not working for spfx 1.8.0

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#3708]
This https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md example not working with SPFx 1.8.0
thanks

**Comment by VesaJuvonen** [comment]
thx @peterremote1980 or reporting. We have pushed updates on the document to address the issue with 1.8 version. Most readable version at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx

You should be explicitly using Office UI Fabric v5.x to avoid issues, so executing this in the solution folder will help to address this. 

``` 
npm install office-ui-fabric-react@5.132.0
```
