### ISSUE TITLE
Issue with setting web part property

### ISSUE THREAD

**Issue by kmprasad4u** [SharePoint/sp-dev-docs#3709]
I am not sure which is the right place to raise this issue. So please redirect me accordingly to the right forum, if this is not the right place.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior / Issue
Setting \\]] in Web Part Properties is causing the webpart / page to break.

#### Steps to Reproduce
Add OOTB "News" webpart into a page, set the title to \\]]
Save the page
Refresh the page

#### Background Info
I was using React Script Editor web part sample from the SPFx web part samples repository, when I stumbled upon a issue. I tried to add some script in the web part, and as soon as I saved the page, the page got broke. 
* It not only caused the web part to break, but none of the web parts in the page loaded. 
* I tried to remove the web part or make updates to the property with PnP Powershell commands, but when I tried to execute "Get-PnPClientSideComponent" I got the error 
> Get-PnPClientSideComponent : Bad JSON escape sequence: \\]
* So I did some trial and error to narrow down on the line which caused the error, and found that the presence of \\]] in the script (used in a regex) caused the issue
* I thought its a issue with the script editor project, but the code looked straight forward, and there is no reason this error should be happening because of the sample webpart.
* So I tried to add OOTB "News" webpart into a page and I set the title to \\]] and it broke the page as well
 
So it looks like this is a problem with the SPFx framework itself. 

#### Note
* Issue found in SharePoint Online, Communication site, Modern Page. Haven't checked other areas. 
* When this issue happens we were not able to edit the page in UI as well. 

#### Questions I have
* I have one page where it broke the entire page, and I was not able to delete the webpart that is causing the problem. Is there any means by which I can remove the webpart ?
* Is there any workaround that can be done for setting the properties.script in the Script Editor Web Part Sample

**Comment by andrewconnell** [comment]
What script did you add? 

The **React Script Editor** web part isn't an official web part from Microsoft... that's a community sample by @wobba.

**Comment by kmprasad4u** [comment]
@andrewconnell 
Thanks for the reply. I have updated the question to make it straight forward.  Though I noticed the issue with Script Editor WebPart sample, the problem seems to be there for OOTB webpart properties as well.

**Comment by andrewconnell** [comment]
The error implies the data you're saving is not valid JSON... so you'll need to escape the `\]`. Properties are serialized to JSON when the web part is saved.

**Comment by wobba** [comment]
Guess web parts by default should escape whatever you add as the oob news wp breaks if you add this in the title field. Sort of an edge case - so might not be prioritized.

**Comment by kmprasad4u** [comment]
We could totally control webparts that we have control over. 

But please suggest an option to remove the broken web part from the page ?  Assume that somebody has made a change in one of the webparts by adding "Hey [[\\]] There" in one of the property in OOTB webpart. Whats the way to remove the problematic web part from the page, so that the entire page is not affected.

**Comment by wobba** [comment]
@kmprasad4u you could edit the field `canvascontent1` and fix it - and a very edge case. I might look into encoding my samples to avoid this.

**Comment by kmprasad4u** [comment]
@wobba 
Thanks, that would be helpful. I have been searching on how to properly escape the string for JSON, and unable to get the right one to use. I am confused whether to escape every special character like newline, tab, quote, backslash - because the issue is happening only for a certain combination of them and not individually. For eg, giving \\] is not causing the issue, \\\\] is not causing the issue, but \\\\]] is causing the issue. 

And Thanks for the suggestion to update the field.

**For anyone facing this issue (and just confirm if I am doing it right)**

I thought updating the one in data-sp-webpartdata would fix the issue. But it didn't
```powershell
$canvasContent1 = (Get-PnPListItem -List "Site Pages" -Id 64 -Fields "CanvasContent1").FieldValues["CanvasContent1"]
#$canvasContent1.IndexOf("Hey \]] There");
$canvasContentModified = $canvasContent1.replace("Hey \]] There", "Hey \\]] There");
Set-PnPListItem -List "Site Pages" -Identity 64 -Values @{"CanvasContent1" = $canvasContentModified}
```

Updating the one in the div tag with attribute data-sp-htmlproperties fixed the issue. (not sure why)
```powershell
$canvasContent1 = (Get-PnPListItem -List "Site Pages" -Id 64 -Fields "CanvasContent1").FieldValues["CanvasContent1"]
#$canvasContent1.IndexOf("Hey ]] There");
$canvasContentModified = $canvasContent1.replace("Hey ]] There", "Hey \]\] There");
Set-PnPListItem -List "Site Pages" -Identity 64 -Values @{"CanvasContent1" = $canvasContentModified}
```

**Comment by kmprasad4u** [comment]
I have tried to use the escape function below when saving to this.properties.script and unescape function when trying to read values from this.properties.script

Just escaping backslash didnt work. Also trying to stringify when saving the data didn't work either
```javascript
private escapeString(str : string) : string {
    return str.replace("\\", "\\\\");
    //return JSON.stringify(str ? str : null);
}
private unescapeString(str : string) : string {
    return str.replace("\\\\", "\\");
    //return JSON.parse(str ? str : null);
}
```

Below worked. I am quite sure this is not the way it is supposed to be done. So is there a proper way to do this ?
```javascript
private escapeString(str : string) : string {
    return str.replace("]]", "\\]\\]");
}
private unescapeString(str : string) : string {
    return str.replace("\\]\\]", "]]");
}
```
