### ISSUE TITLE
Can I use Client secret besides certificates for realizing app-only access for my Azure AD app?

### ISSUE THREAD

**Issue by aravindmunna** [SharePoint/sp-dev-docs#3711]
I'm not able to access sharepoint online tenant using azure ad app with client secret , i'm getting 401 access denied message. But when i'm trying with certificate i'm able to access the sharepoint tenant using my console app. Need suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you confirm what auth flow you are using to authenticate with Azure AD to obtain a token and how you are accessing the SharePoint? SharePoint CSOM/REST, Microsoft Graph API, etc?

It sounds like the Azure AD application using the client credentials via the app-only flow but need to confirm...

**Comment by robinmeure** [comment]
The FAQ at the bottom states the following:
"Q: Can I use other means besides certificates for realizing app-only access for my Azure AD app?
A: No, all other options are blocked by SharePoint Online and will result in an Access Denied message."

**Comment by aravindmunna** [comment]
Thanks @andrewconnell :- We use Client grand Auth flow using CSOM classes to obtain token with certificate and without certificate. But we are successfully able to connect with the token provided cetificate only, others giving 401 error.
