### ISSUE TITLE
Search REST API : InternalError when using specific SelectProperties

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#3712]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When performing a GET or POST search request using the search API, the user should be able to specify any managed property in the *SelectProperties* parameter without receiving a 500 internal error.

#### Observed Behavior

Whether I use the GET or POST method, I can specify pretty much any managed property in the **SelectProperties** parameter (even non existing managed properties...), but as soon as I specify one of the managed properties below, I get a 500 Internal Error response :

- ClassificationConfidence
- ClassificationCount
- ClassificationLastScan

Now the reason I found these is because I am using the [following query](https://www.techmikael.com/2014/03/debugging-managed-properties-using.html) in order to find all available managed properties for a specific result, that way I can show the user a "Show all managed properties" link next to a search result, exactly like the [Search Query Tool](https://archive.codeplex.com/?p=sp2013searchtool) does. 

After completing the functionnality, I realized the link was failing for some results. After investigation, it turns out the results failing all had one of these 3 managed properties above. So I trimmed down the query to absolutely nothing else than SelectProperties='ClassificationConfidence' and I still got the internal error. Turns out that the Search Query Tool also has the same problem, since after discovering this I tried the "All managed properties" for the exact same result in the Search Query Tool just to see how he was handling it and the window failed to open, most likely because of the same internal error.

For now I made sure that these 3 managed properties are removed from the request before performing the query but it's not a reliable fix, there could be other problematic properties that I didn't come across, these are just the ones I spotted for now.

#### Steps to Reproduce

Simply try this URL and you'l get a *An unkown error occured* message :

/_api/search/query?querytext='*'&selectproperties='ClassificationConfidence'

**Comment by andrewconnell** [comment]
Any ideas @wobba ?

**Comment by wobba** [comment]
I have seen this as well and would strike this up as expected behavior and mp's you should not use. Probably internal ones used in maybe eDiscovery. Never investigated it. We also exclude some properties in the query tool for "view all properties" as they caused said errors. Maybe we need to exclude more.

**Comment by spplante** [comment]
Yeah that's pretty much what I did but I was hoping someone could take a look and fix the backend code which actually causes the error, but I am fine with excluding them if that's not a possibility 👍 

Thanks!

**Comment by wobba** [comment]
@spplante If you want it properly fixed you most likely have to file a ticket via premiere support.
