### ISSUE TITLE
Specifically calling out limitations when using an Azure AD app

### ISSUE THREAD

**Issue by NelsonLamprecht** [SharePoint/sp-dev-docs#3718]
After confirm with product support, an Azure AD app-only can not be used to write user profile data. Even though the permission granted is "Read and write user profiles", this not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It isn't feasible or <imho>really appropriate</imho> to call out all the limitations on this page as different capabilities support different things. It depends on what you're trying to do and if that specific thing supports app-only permissions.

App-only isn't supported in all scenarios as some require auditing on WHO made the change and that must be traced back to a specific individual. App-only, by definition, does not have an user interaction.
