### ISSUE TITLE
Formatting issue with "content approval status" columns - stopped working since March 2019

### ISSUE THREAD

**Issue by alanjimenez1** [SharePoint/sp-dev-docs#3721]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have implemented column formatting for an Approval Status column in a SP List (_ModerationStatus). It used to work, but all of a sudden the formatting is not rendered properly and I cannot longer format this type of column (so I can't remove the formatting). 

#### Observed Behavior
Column values are not displayed and a red background with an "X" icon is displayed in the cell. I can't edit the formatting of this specific column.

#### Steps to Reproduce
Create a SP custom list
Add content approval on the list
Try to format the "Approval Status" column (follow this article https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#)

![image](https://user-images.githubusercontent.com/24574911/55398834-cce45380-5549-11e9-8b69-d204efd2aca3.png)
![image](https://user-images.githubusercontent.com/24574911/55398861-da99d900-5549-11e9-8fae-2ab5e68bbd81.png)

**Comment by pbjorklund** [comment]
Same issue here.

More reports around this at: https://techcommunity.microsoft.com/t5/SharePoint/Approval-Status-Column-Formatting-gone/td-p/389737

This formatting ability is a critical part of customer solutions - what is going on?

**Comment by alanjimenez1** [comment]
Thanks Patrik! The solution there helped me at least to remove the previous formatting -- but indeed, I'm not sure what MS will do to re-deploy this feature which was pretty useful.

**Comment by andrewconnell** [comment]
Do you have any insights on this @thechriskent ?
