### ISSUE TITLE
How to generate pagination number and based on that apply paging for sharepoint listitem

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#3723]
Let's consider I have 4000 items in Sharepoint List(Office 365 or Sharepoint Online) and want to display 100 records at a time so PageSize 100 ($top=100). Now  What I want is that based on the number of item in the list I would like to generate page number like `First`, `Page1`, `Page2`, `...`, `Page10`, `Last` or Use Drodown in which paging number will be there and based on that display records.

I have searched for `$skiptoken` and read out it which works perfectly fine if I have to fetch next top records or say lazy loading fetch records( Currently in default sharepoint modern list this feature is working). Different issue may arise if some item are deleted from list, due to this ordinal index is reset as documented at [Sharepoint OData Query](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)

But didn't found any way to achieve functionality like this using paging number.

Does it possible to achieve?

**Comment by bcameron1231** [comment]
You can grab the # of items in the list, if you query the list for the item count fist

`/_api/web/lists/getbytitle('<listname>')/ItemCount`

**Comment by anomepani** [comment]
@bcameron1231  Yes You are right I can get Total Item count using `/_api/web/lists/getbytitle('<listname>')/ItemCount` but the issue is with how `$skiptoken` work after some of the list items are deleted. We can not predict the paging number correctly.

e.g.  Consider that Id from 101 to 4000 is deleted and after that Currently I have 4000 items count and pageSize 100.

For page 1  it displays records from Id 1 to Id 100 and rest api result return  `__next` link.
using  `__next` we can get result expected result.
But if I have to move at specific page number e.g. `10 or 15 or last` etc then it doesn't return the correct result.

**Comment by andrewconnell** [comment]
There's simply no perfect solution here. You can't expect that paging through 4000 items, 100 at a time, that no items will be added / deleted that may impact the number of pages. When going from one page to the next, the total number of items in the collection can change, and thus the number of pages. Even this issue list works like that.

You could use the `$skip` OData parameter to skip ahead... so if you were doing pages of 100 items and were on page 5, the OData query would be something like `?$skip=500&$top=100`

**Comment by anomepani** [comment]
@andrewconnell  Thank you for your explanation. I have found that, the `$skip` query option does not work with queries for SharePoint list items based on [SP Rest Doc](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests). I know as the collection is changing it also affects the number of paging as well. Just want to know that in this type of situation does pagination with number possible or not so based on that I can give an answer to the client and explain some alternative to this.

**Comment by andrewconnell** [comment]
_To your point about using `$skip`..._
If you are in SharePoint Online, have you looked at using the [Microsoft Graph to get the data in the list](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0)? I don't know if that supports `$skip`, but it's worth checking.

The Microsoft Graph doesn't use the same SharePoint REST API (v1) that you linked to above... it uses SP the REST API v2.

@anomepani said
> Just want to know that in this type of situation does pagination with number possible or not so based on that I can give an answer to the client and explain some alternative to this.

IMHO, you should guide the client that paging through 4000 items might be a good feature request, but think usability... no one will use this functionality. Rather implement a good search to limit the number of items back, then paging isn't as big of an issue.

I'm going to close this issue as there's not much more we can do here...
