### ISSUE TITLE
SPO webpart not available after syncing to teams

### ISSUE THREAD

**Issue by Ashish1662** [SharePoint/sp-dev-docs#3727]
I was able to create a webpart by following the steps from below article
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

Everything works untill I synced with teams from App Catalog. After syncing, I can add as a teama tab but it is no longer available in SPO and hence can not be added on any other site.

P.S. The webpart was enabled tenant wide.

**Comment by andrewconnell** [comment]
There are known issues with the **Sync to Teams** functionality. I'm working on updating the docs you linked to... MSFT is investigating issues.

The docs currently say this capability is not fully working so it's not really something you should be doing at this time. For now, I'm going to go ahead and close this issue. Instead, I'd recommend following the manual deployment process by creating the **manifest.json** for the Teams app package and uploading it to the Teams store for now.
