### ISSUE TITLE
Custom learning for Office 365 

### ISSUE THREAD

**Issue by sarahcharlesRW** [SharePoint/sp-dev-docs#3728]
SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.                                                                                       Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088                                                                                       PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues                                                                    SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it. |   | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. |   | Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 |   | PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 
SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed. | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "Custom       learning for Office 365"        template failed.
 
Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 | Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088
Here is the exception that occurred:       Type = System.Exception Message =       {"error":{"code":"-2147024891,       System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access       denied. You do not have permission to perform this action or access this       resource."}}} Source = OfficeDevPnP.Core TargetSite = Void       MoveNext() StackTrace = at       OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String       filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant       tenant, ProvisioningTenant provisioningTenant, FileConnectorBase       connector, TokenParser parser, PnPMonitoredScope scope,       ProvisioningTemplateApplyingInformation applyingInformation,       ProvisioningMessagesDelegate messagesDelegate) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088
 
PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
PnP       Correlation ID: 88f036fd-69a7-49a2-a1a8-29b87e22a788              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.

**Comment by andrewconnell** [comment]
Unfortunately, This issue is not actionable and thus will be closed.

Please use the issue template provided to explain (1) what you are doing, (2) what is expected & (3) what happened with details.

**Comment by ainnanigit** [comment]
I worked perfectly fine for me.  I installed it both the ways described and both worked good.
I also wrote a bit about the solution and find it great
[Custom Learning Office 365](https://innanis.com/2019/04/04/office-365-custom-learning-solution-part-1/)

**Comment by ainnanigit** [comment]
Soon I will write another article on the customization options that we have
