### ISSUE TITLE
SPFx 1.8 generator errors

### ISSUE THREAD

**Issue by dkorolev1** [SharePoint/sp-dev-docs#3730]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

### Find the details below:

? Which baseline packages do you want to target for your component(s)? **SharePoint 2019 onwards, including SharePoint Online**
? Where do you want to place the files? **Use the current folder**
Found npm version 6.4.1
? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites? **Yes**
? Which type of client-side component to create? **WebPart**
Add new Web part to solution bt-5.
? What is your Web part name? **HelloWorld**
? What is your Web part description? **HelloWorld description**
? Which framework would you like to use? **React**

**gulp build**

### Error - typescript - src/webparts/helloWorld/HelloWorldWebPart.ts(7,7): error TS2307: Cannot find module '@microsoft/sp-property-pane'.

Okay, as I understood now these interfaces (IPropertyPaneConfiguration,PropertyPaneTextField) are declared here @microsoft/sp-webpart-base

replace this:

_import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';_

to:

_import { IPropertyPaneConfiguration, 
PropertyPaneTextField 
} from '@microsoft/sp-webpart-base';_

**gulp bundle** 

### 
Error - [write-manifests] Manifest validation error (./src/webparts/helloWorld/HelloWorldWebPart.manifest.json): 
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/) Missing required property: extensionType
(#/componentType) No enum match for: WebPart
(#/) Additional properties not allowed: supportedHosts
(#/) Missing required property: items
(#/) Missing required property: rootComponentId

Sadly, instead of developing, you always have to deal with some strange errors!

**Comment by Enersoft-Intl** [comment]
+1, we're also facing this issue with serve. 

Additionally, this show up after refactoring a reference in the web part template due to a compilation error:

``` zsh
[12:17:22] Error - typescript - src/webparts/card/CardWebPart.ts(15,21): error TS2415: Class 'CardWebPart' incorrectly extends base class 'BaseClientSideWebPart<ICardWebPartProps>'.
```

Original
``` typescript
import {
  // symbols do not exist in reference
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-core-library/';
```
Updated:
``` typescript
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-webpart-base';
```

**Comment by dkorolev1** [comment]
@StfBauer, perhaps you have some suggestions regarding this issue? If I try to scaffold a project for SP online only it works well, but there are troubles with SharePoint 2019. Thanks.

**Comment by patmill** [comment]
Tracked in #3621 , along with a work around.  We hope to have an updated released very soon that will fix this.  If the information in 3621 is insufficient to solve this, please reopen this bug.
