### ISSUE TITLE
Subtraction Operations Incorrectly Tokenized in List Formatting

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#3733]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A list formatting expression using a subtraction operator should work with both simple numbers and nested operations.

#### Observed Behavior

The subtraction operator is recognized as a negative modifier for a number rather than as a subtraction operator when the first operand is a nested operation. This leads to expressions being returned as strings rather than being correctly evaluated. The issue is within the AST Tokenizer.

#### Steps to Reproduce

Using this format we see the expected result:
```json
{
  "elmType": "div",
  "txtContent": "=4-2"
}
```

Here is how the tokenizer recognizes this expression:
![image](https://user-images.githubusercontent.com/8364109/55506789-52d4cd00-5624-11e9-962d-cb26a9e93f37.png)

All values are returned as 2 as expected.

---

Applying the following derivation we run into problems (applied to a multi-choice column):
```json
{
  "elmType": "div",
  "txtContent": "=length(@currentField)-2"
}
```

Here is how the tokenizer recognizes this expression:
![image](https://user-images.githubusercontent.com/8364109/55506991-c24abc80-5624-11e9-853c-413bee66f5ea.png)

Notice that the `-` and the `2` have been incorrectly combined into `-2`. **This causes the operation/operand evaluation to fail since this isn't a valid expression. This results in the expression being returned as a string rather than the evaluation of the expression**:

![image](https://user-images.githubusercontent.com/8364109/55507089-f45c1e80-5624-11e9-81ce-a8d110fa7953.png)

Note that adding spaces makes no difference.

---

The addition operator does not have this problem:
```json
{
  "elmType": "div",
  "txtContent": "=length(@currentField)+2"
}
```

Correct tokenization:
![image](https://user-images.githubusercontent.com/8364109/55507202-24a3bd00-5625-11e9-820e-859468b62f2a.png)

---

It is possible to work around this problem by surrounding raw numbers used in the right-side of the subtraction operation in parenthesis:
```json
{
  "elmType": "div",
  "txtContent": "=length(@currentField)-(2)"
}
```

![image](https://user-images.githubusercontent.com/8364109/55507363-806e4600-5625-11e9-8afd-45d849ed99ab.png)

This is a temporary solution and definitely not an obvious one.

**Comment by andrewconnell** [comment]
@bcameron1231 @thechriskent

**Comment by thechriskent** [comment]
@andrewconnell Did you just tag me in my own issue? 😆

**Comment by andrewconnell** [comment]
Oops... me thinks I maybe was triaging too quickly this morning...

![](https://media.giphy.com/media/9n5UIlRppk91e/giphy-downsized.gif)

With that being said... any ideas on your own issue? :)

**Comment by shagra-ms** [comment]
This was fixed in May 2019.

@thechriskent Are you still facing this issue?
