### ISSUE TITLE
default.aspx in Site Pages loads page rather than default view

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#3735]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When navigating to the site pages library, library loads the default view. 

#### Observed Behavior

When navigating to Site Pages library that contains a named file called "default.aspx" this page is loaded instead of default view for the library.

This isn't documented or cannot find a reference to it and wondering if this is a bug. 

#### Steps to Reproduce

- Go site pages library and create a page, ensure it is named default.aspx
- Go to Site Contents > Site Pages
- The default page is loaded rather than the default view.

**Comment by patmill** [comment]
Outside the scope of this issues list, but what you are seeing is that there is a property on the root folder of the library "WelcomePage", which is the URL that should be used if the library is addressed directly.  Here is some older server-side documentation that should give you a general idea.  https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ms457546%28v%3doffice.15%29
