### ISSUE TITLE
Large file upload optimization

### ISSUE THREAD

**Issue by mariusRT** [SharePoint/sp-dev-docs#3737]
Hi,

The example on uploading large file using the UploadFileSlicePerSlice method can be optimized on last chunk upload.
You don't need to copy the buffer to the resized lastBuffer.
You just have to create a size restricted MemoryBuffer on the existing buffer.
This removes an unnecessary memory allocation.

if (last)
{
	// Is this the last slice of data?
	using (MemoryStream s = new MemoryStream(buffer, 0, readBytes))
	{
		// End sliced upload by calling FinishUpload.
		uploadFile = uploadFile.FinishUpload(uploadId, fileoffset, s);
		ctx.ExecuteQuery();

		// Return the file object for the uploaded file.
		return uploadFile;
	}
}

and discard the lines
// Copy to a new buffer that has the correct size.
lastBuffer = new byte[bytesRead];
Array.Copy(buffer, 0, lastBuffer, 0, bytesRead);

and the declaration of the lastBuffer variable
Byte[] lastBuffer = null;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8869da6e-b785-abff-937e-a1d95bcd8314
* Version Independent ID: d77fd4c4-5149-f4ac-da03-f0803091dc1c
* Content: [Upload large files sample SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-large-files-sample-app-for-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good suggestion @mariusRT ... care to submit a PR for this doc?

**Comment by SaSapalan** [comment]
We don't need to create UploaFile session for every chunk. 
UploadFile should be reused and without that it may at times lead to invalid session issue.

**Comment by SaSapalan** [comment]
This line is not needed

uploadFile = ctx.Web.GetFileByServerRelativeUrl(docs.RootFolder.ServerRelativeUrl + System.IO.Path.AltDirectorySeparatorChar + uniqueFileName);

And uploadFile variable should be initialized to null at the beginning.

**Comment by andrewconnell** [comment]
Agreed... care to submit a PR fixing the code sample and cleaning up the code formatting?

**Comment by andrewconnell** [comment]
@mariusRT & @SaSapalan Instead of listing specific line changes, can you either submit a PR or post what you think the code final code should look like? These piece-mail edits in comments are not easy to follow...

**Comment by SaSapalan** [comment]
I have PR created. But it gives me option only to 'Close and Comment'.

The modified code should be like this

Change 1
+++++++++++++++
Original
// File object.
            Microsoft.SharePoint.Client.File uploadFile

Modified
// File object.
            Microsoft.SharePoint.Client.File uploadFile = null;

Change 2 (need to remove the line)
++++++++++
Original:
// Get a reference to your file.
                                uploadFile = ctx.Web.GetFileByServerRelativeUrl(docs.RootFolder.ServerRelativeUrl + System.IO.Path.AltDirectorySeparatorChar + uniqueFileName);

Modified:

**Comment by andrewconnell** [comment]
@SaSapalan said:
> "I have PR created. But it gives me option only to 'Close and Comment'."

That's because you don't have permissions to directly edit the docs. A PR says "I've made some edits... I'm requesting your pull these changes into the repo". Please also see my comment and how I edited your PR
