### ISSUE TITLE
Webpart title localization in picker unstable

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#3739]
#### Category
- [x] Bug

#### Expected or Desired Behavior
A webpart that has a localized title set in the Webpart.manifest.json for a specific language should always show this localized title in the webpart picker dialog when the specified language is active.
Localizing the title in the manifest is done according to the article at
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts

#### Observed Behavior
Sometimes the localized title is shown, sometimes the default title is shown. Sorry for that 'sometimes' but I really can't see any reproducible pattern. 
One example: I installed the solution containing the webpart on a new site. When I added the webpart to the page the title was localized. Some time later I modified the page and the title in the picker was now in english(default). I added a new page and opened the picker there -> the title was localized again. I went back to the original page and now the picker there also showed the localized title. It seems to be somehow random.
Used browser: Chrome (current version). Language in the browser and default language of the site are set to German.

#### Steps to Reproduce
See above - hard to say...

**Comment by patmill** [comment]
The goal is that the language in the picker should match the language that you see in the rest of the site.  Is the whole system picking a random language, or just your webpart?

**Comment by cwdata** [comment]
It is just our own webparts that show up in the wrong language. And not all of them. Some are showing up with the correct title and some not. All webpart titles are configured the same way in the manifest and it "randomly" changes which ones are picking the correct or the wrong language.

**Comment by kemesfun** [comment]
The parsing for title in preconfiguredEntries is case sensitive. Adding"title": { "default": "Greeting", "nl-nl": "Begroeting" } will not work since it has to be nl-NL. Everything next to the '-' has to be UpperCase. This solves the issue, but there will be a fix to make nl-nl work.

**Comment by cwdata** [comment]
@kemesfun 
Thanks for the update and the workaround, we'll change our manifest files accordingly.
