### ISSUE TITLE
CommandSet Appending multiple times at new modern list view

### ISSUE THREAD

**Issue by dpobo** [SharePoint/sp-dev-docs#3740]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I deploy one extension from SPFx with a couple of command set -from the template by yeoman-. I'm expecting to use on custom action in order to append a react component.

#### Observed Behavior

If I'm using the new modern view from a list, all the custom actions get appended each time I click one item from the list -it's like it gets rendered one time per action-.

If the enviorment of sharepoint is in the previous version, everything works as expected.

The only difference between the two versions, is that in the new, the settings icon from the top right of the window shows a new overview. I have some sharepoint online with the last version and others with the previous one, I guess that those sites aren't updated yet

So, If I go to the rootfolder, it renders the two custom actions 

<img width="765" alt="start" src="https://user-images.githubusercontent.com/9421655/55557080-567e5780-56e9-11e9-9092-6ca5028191ea.png">

But, If click in one item, it's like it renders multiple times:

<img width="859" alt="02" src="https://user-images.githubusercontent.com/9421655/55557128-71e96280-56e9-11e9-8522-47a67d6434d5.png">

#### Steps to Reproduce

Create a new ListView Command Set SPFx extension and deploy to SharePoint

I have checked the central admin in order to try to change this new modern view but i cannot either, is there a way for me to change it as admin of the tenant?

Thank you!

**Comment by andrewconnell** [comment]
Can you confirm this is still an issue, as a bug was recently fixed that may have addressed this (ref: #3703)

**Comment by dpobo** [comment]
Hi Andrew!
       Yeah, now it's working as expected! Thanks!
