### ISSUE TITLE
Cannot add installed webparts to tenant

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#3741]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Adding installed webparts to a page is possible. The endpoint `GetClientSideWebParts` returns a response and does not error.

#### Observed Behavior
Only the Text webpart and (in the workbench) webparts being served by gulp can be added to the page. The endpoint `GetClientSideWebParts` returns a 500.
![image](https://user-images.githubusercontent.com/5057870/55566595-ee813e80-56f3-11e9-822e-ed95f239a25b.png)

#### Steps to Reproduce

Edit a page, click the add part button.

This has occurred for us on two tenants. One resolved itself, the other (shown in the screenshot) has had the issue for months, with no known workaround.

**Comment by patmill** [comment]
Do you know how to get the correlation ID for the failed request? If so, can you paste it here?

**Comment by JakeStanger** [comment]
Would you mind explaining how I find the ID in this case? Once I can I'll paste it.

**Comment by patmill** [comment]
Look at the response headers in the failed request.  It might have something like "requestId" .  It should be a GUID.  Ideally the failure should say what is going on, but failing that, we can try and pull logs.
________________________________

**Comment by JakeStanger** [comment]
Headers, should have thought of that :man_facepalming:. Here's the ID: `f2c7cf9e-70f5-8000-84dd-9158d6f86ac7`

**Comment by mcmynn83** [comment]
In order to investigate this further could you go into your app catalog and go to the list at Lists/ComponentManifests and take a take a screenshot of the fields for the component with ID f1697ee1-4edb-4af5-b834-0b1171d85b38?  

If you would like to unblock yourself removing the solution which added that app will fix the problem.  That being said, I'm not sure what is special/different about this app yet.  It is a bug in our code which we will fix, but that should fix it immediately for you.

**Comment by JakeStanger** [comment]
![image](https://user-images.githubusercontent.com/5057870/55611362-313b2900-577d-11e9-88b5-7ce0e0351dc1.png)

This solution is an extension, and was developed after the issue started occuring. It has also never been installed on the other tenant where the issue is present.

I will remove the solution for now still and hopefully it can shed some further light for you guys.

**Comment by patmill** [comment]
OK, this has been fixed, and should start rolling across the service in a bit.  I'll check back when it has reached 100%.

**Comment by VesaJuvonen** [comment]
Hi @JakeStanger, can you double check the situation again as this should be now fully fixed. Thanks for confirming the status.

**Comment by JakeStanger** [comment]
All is working now, thanks
