### ISSUE TITLE
request to provision "SharePoint Starter Kit"  template failed

### ISSUE THREAD

**Issue by wynnetransport** [SharePoint/sp-dev-docs#3743]
Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088                                                                                       PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues                                                                          SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it. |   | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "SharePoint       Starter Kit"              template failed. | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "SharePoint       Starter Kit"              template failed. |   | Here is the exception that occurred:       Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 | Here is the exception that occurred:       Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 |   | PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | SharePoint Online Provisioning Service     This is an automatic email and you shouldn't reply to it.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 
SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "SharePoint       Starter Kit"              template failed. | SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "SharePoint       Starter Kit"              template failed.
SharePoint       Online Provisioning Service       Unfortunately, your       request to provision       "SharePoint       Starter Kit"              template failed.
 
Here is the exception that occurred:       Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088 | Here is the exception that occurred:       Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088
Here is the exception that occurred:       Type = Microsoft.SharePoint.Client.ServerException Message       = File Not Found. Source = Microsoft.SharePoint.Client.Runtime       ServerStackTrace = ServerErrorCode = -2147024894 ServerErrorTypeName =       System.IO.FileNotFoundException ServerErrorTraceCorrelationId =       70bdcf9e-c041-8000-8b70-66e62462dbdf TargetSite = Void       ProcessResponseStream(System.IO.Stream) StackTrace = at       Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream       responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()       at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at       System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()       --- End of stack trace from previous location where exception was thrown       --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task       task) at       System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task       task) at       Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext       clientContext, Int32 retryCount, Int32 delay, String userAgent) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessWebApiPermissions(Tenant       tenant, ProvisioningTenant provisioningTenant, TokenParser parser,       PnPMonitoredScope scope, ProvisioningMessagesDelegate messagesDelegate)       at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser       parser, ProvisioningTemplateApplyingInformation applyingInformation) at       OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation provisioningInfo) at       Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant       tenant, ProvisioningHierarchy hierarchy, String sequenceId,       ProvisioningTemplateApplyingInformation applyingInformation) at       SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()       in       C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line       337 HResult = -2146233088
 
PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a              Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
PnP       Correlation ID: e2627a8b-8eb3-4fb6-8d8e-d2855aeb6a8a

**Comment by VesaJuvonen** [comment]
Hi @wynnetransport, can you provide details on the parameters which you provided for the provisioning as that's the only way we can try to figure out what went wrong in the provisioning. The exception does indicate that you used some strange URL targets, but without the facts, we can only speculate.

Alternatively, can you retest the situation and record the parameters before starting the provisioning, so that we can investigate if the issue still occurs. Thx.
