### ISSUE TITLE
New Languages

### ISSUE THREAD

**Issue by t-rurodr** [SharePoint/sp-dev-docs#3744]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello team,

I'm part of the Marketing team at Microsoft and we're super interested in promoting this among all our Office 365 clients in Portugal. Are there any plans to have the materials available in Portuguese?

Many thanks,
Rui

**Comment by andrewconnell** [comment]
Can you clarify what materials you're referring to?

**Comment by patmill** [comment]
Taking this out of the issues list.
