### ISSUE TITLE
AAD Http client error using Mobile app

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-docs#3746]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Aad client should work the same on mobile and in browser.

#### Observed Behavior

When connecting to aad secured api there is a parse error. "SyntaxError: Unexpected token u in JSON at position 0"

#### Steps to Reproduce

1. Create Webpart
2. Call AAD Secure API.
3. Observe Correct behavior in browser.
4. Open using mobile app and see error message "SyntaxError: Unexpected token u in JSON at position 0"

Here is a repo with observed issue
[Repro](https://github.com/araver/aad-spfx-bug)

**Comment by VesaJuvonen** [comment]
Duplicate with #3665 and things should work now properly.
