### ISSUE TITLE
Issues while creating SPFx web part

### ISSUE THREAD

**Issue by harshalgite11** [SharePoint/sp-dev-docs#3747]
I am trying to create SPFx webpart but facing issues on running the following command.
`yo @microsoft/sharepoint`

OS - WIindows 10
Node version - 8.15.1
NPM version - 6.9.0
SPFx version - 1.8.0

I followed everything as per Microsoft documentation. I tried installing node version 8.12.0 and still same issue. 
Also tried cleaning the npm cache many times but to no effect. Tried to create through administrator cmd still the same issue.

It just won't create a solution for me. :( 
Am I doing something wrong? Can someone please help? Error log is attached.
[2019-04-07T13_27_50_737Z-debug.log](https://github.com/SharePoint/sp-dev-docs/files/3051624/2019-04-07T13_27_50_737Z-debug.log)

**Comment by patmill** [comment]
Make sure you don't have any IDEs open to the project, go to your directory, and run npm install again.  I've seen similar things in the past where npm just doesn't want to install a package.

**Comment by harshalgite11** [comment]
Everything is closed. Just the command prompt is running. NPM just won't install. Everything works fine with `yarn install` though. WHat might be the issue with NPM?

**Comment by patmill** [comment]
Searching the interwebs for "npm install windows The operation was rejected by your operating system" has a collection of hits.  Here's a long thread in the npm github about something similar - https://github.com/npm/npm/issues/10826 .  There workaround suggestions were`npm cache clean` or disabling your anti-virus.  Alternately, using Yarn or pnpm seems like a good idea as well.

**Comment by andrewconnell** [comment]
In your log, I see what appears to be a network drive: **H:\**. Is that correct?

If so, try to create it on a local drive... there are well-known issues when NPM tries to work with network drives... [ref](https://www.google.com/search?q=NPM+EPERM+network+drive&oq=NPM+EPERM+network+drive&aqs=chrome..69i57j69i64.7672j0j7&sourceid=chrome&ie=UTF-8).

**Comment by harshalgite11** [comment]
No. My local drive is named H:/
And I have tried every solutio I could find cache clearing, disabling antivirus and firewall tried downgrading npm as well but npm does not install.

**Comment by andrewconnell** [comment]
As @patmill suggested, have you tried using Yarn instead of NPM?

Unfortunately, this doesn't appear related to SPFx / SharePoint, rather it seems like an NPM+Windows issue...

**Comment by harshalgite11** [comment]
Yes. I have mentioned in my previous comment that it works fine with Yarn. Maybe you are right, it seems NPM-Windows issue.

**Comment by andrewconnell** [comment]
OK... I'm going to go ahead and close this issue then. I think you'd have better success in the NPM forums / issue lists than here trying to resolve this issue since it's not specific to SharePoint / SPFx.
