### ISSUE TITLE
Upgrade React,React Dom, Types/React, Fabric UI React

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-docs#3749]
My Webparts are working, but I still need to upgrade the versions of : React,React Dom, React types and Fabric UI React,
My spfx's version is 1.8, when I update those packages I get errors.
Any help please?

**Comment by VesaJuvonen** [comment]
Can you share more details on what exact version you need to update the solution and what are you looking into in the new versions? Also - can you share the error details that you are getting so that we can investigate what's causing them. Thx.

**Comment by FullStackRafik** [comment]
Hi @VesaJuvonen 
I want to upgrade the following packages:
React, React-Dom, types/react,typescript.
As I'm using SPFx 1.8 I need to upgrade React to ^16.3.0

Here are some of the errors I get with this command npm ls --depth=0  :
npm ERR! peer dep missing: react@^16.0.0, required by
npm ERR! missing: typescript@2.2.2, required by @microsoft/gulp-core-build-typescript@3.1.1


Here is the error when I upgrade only React using : npm install react@16.3.0 --save
lib\states\IFactoryMethodState.d.ts(0,24): error TS1003: Identifier expected.
Error - typescript - src\webparts\*************************** rror TS2345: Argument of type '{ status: string; *****: ******[]; }' is not assignable to parameter of type 'IJobRequestState'.
Error - 'typescript' sub task errored after 4.82 s
 "TypeScript error(s) occurred."






But when I upgrade also React-Dom(npm install react-dom@16.3.0 --save) I get this error in the browser's console with a blank page:
Failed to load URL 'https://localhost:4321/node_modules/react/dist/react.js' for resource 'react' in component '0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d' (react). The file was not found in the server.

In the other side I still always getting errors with this command npm ls --depth=0   : 

npm ERR! missing: react@15.4.2, required by @microsoft/sp-webpart-base@1.1.1
npm ERR! missing: react-dom@15.4.2, required by @microsoft/sp-webpart-base@1.1.1
npm ERR! missing: react@15.4.2, required by @microsoft/office-ui-fabric-react-bundle@1.1.0
npm ERR! missing: react-dom@15.4.2, required by @microsoft/office-ui-fabric-react-bundle@1.1.0
npm ERR! missing: react@15.4.2, required by @microsoft/sp-loader@1.1.1
npm ERR! missing: react-dom@15.4.2, required by @microsoft/sp-loader@1.1.1

Here is my package.json after the upgrades:

`
{
  "name": "adem-commission",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/common": "^1.3.1",
    "@pnp/logging": "^1.3.1",
    "@pnp/odata": "^1.3.1",
    "@pnp/sp": "^1.3.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/rx-lite": "^4.0.6",
    "@types/webpack-env": "1.13.1",
    "@uifabric/styling": "^6.45.2",
    "bootstrap": "^4.3.1",
    "core-js": "^3.0.1",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "react": "^16.3.0",
    "react-accessible-accordion": "^2.4.5",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "^16.3.0",
    "react-icons": "^3.5.0",
    "reactstrap": "^7.1.0",
    "rx-lite": "^4.0.8"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^3.3.4000"
  }
}

`
Any suggestions about upgrade planning?

Thanks

**Comment by FullStackRafik** [comment]
Hi @VesaJuvonen
I want to upgrade the following packages:
React, React-Dom, types/react,typescript.
As I'm using SPFx 1.8 I need to upgrade React to ^16.3.0

Here are some of the errors I get with this command npm ls --depth=0 :
npm ERR! peer dep missing: react@^16.0.0, required by
npm ERR! missing: typescript@2.2.2, required by @microsoft/gulp-core-build-typescript@3.1.1

Here is the error when I upgrade only React using : npm install react@16.3.0 --save
lib\states\IFactoryMethodState.d.ts(0,24): error TS1003: Identifier expected.
Error - typescript - src\webparts*************************** rror TS2345: Argument of type '{ status: string; *****: ******[]; }' is not assignable to parameter of type 'IJobRequestState'.
Error - 'typescript' sub task errored after 4.82 s
"TypeScript error(s) occurred."

But when I upgrade also React-Dom(npm install react-dom@16.3.0 --save) I get this error in the browser's console with a blank page:
Failed to load URL 'https://localhost:4321/node_modules/react/dist/react.js' for resource 'react' in component '0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d' (react). The file was not found in the server.

In the other side I still always getting errors with this command npm ls --depth=0 :

npm ERR! missing: react@15.4.2, required by @microsoft/sp-webpart-base@1.1.1
npm ERR! missing: react-dom@15.4.2, required by @microsoft/sp-webpart-base@1.1.1
npm ERR! missing: react@15.4.2, required by @microsoft/office-ui-fabric-react-bundle@1.1.0
npm ERR! missing: react-dom@15.4.2, required by @microsoft/office-ui-fabric-react-bundle@1.1.0
npm ERR! missing: react@15.4.2, required by @microsoft/sp-loader@1.1.1
npm ERR! missing: react-dom@15.4.2, required by @microsoft/sp-loader@1.1.1

Here is my package.json after the upgrades:

{
  "name": "crud-solution",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/common": "^1.3.1",
    "@pnp/logging": "^1.3.1",
    "@pnp/odata": "^1.3.1",
    "@pnp/sp": "^1.3.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/rx-lite": "^4.0.6",
    "@types/webpack-env": "1.13.1",
    "@uifabric/styling": "^6.45.2",
    "bootstrap": "^4.3.1",
    "core-js": "^3.0.1",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "react": "^16.3.0",
    "react-accessible-accordion": "^2.4.5",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "^16.3.0",
    "react-icons": "^3.5.0",
    "reactstrap": "^7.1.0",
    "rx-lite": "^4.0.8"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^3.3.4000"
  }
}
Any suggestions about upgrade planning?

Thanks

**Comment by andrewconnell** [comment]
There are a lot of issues that you'll need to address...

- you say you're using SPFx 1.8, but your package.json shows you're using a VERY old version: 1.1.0
- your TypeScript type declaration packages for React are very outdated (0.14.*)
- you're trying to use TypeScript v3.3, but you aren't using the rush compiler package.

I suggest creating brand new SPFx 1.8 React project and comparing the differences with your package.json in the new project as you'll see a lot of incorrect versions.

After upgrading your packages, it's recommended to DELETE **node_modules** and any package lock files, then run `npm install` again.

**Comment by FullStackRafik** [comment]
@andrewconnell Thanks for your reply.
Actually, I said that I'm using SPFx 1.8 because when I ran `npm outdated --global`, the @microsoft/generator-sharepoint generator was listed as v1.7.1,
 after that I ran : 
`npm install @microsoft/generator-sharepoint --global`

Now I'll follow your instructions, but when I Scaffold a new project using Yeoman SharePoint generator, I get this error:
Error: Cannot find "package.json" file required by this generator.
I already initialized the project folder with : npm init.

**Comment by andrewconnell** [comment]
You missed my point @FullStackRafik ... installing SPFx v1.8 isn't enough... you have old packages referenced in your project. 

For instance, in your snippet above from **package.json**, you have (*among others*):

```json
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "~1.1.0",
```

That's a mix of SPFx v1.1.0 & 1.4.1... not 1.8. Create a new project and compare the versions in the **package.json** to the **@microsoft/*** packages.

**Comment by FullStackRafik** [comment]
I agree with you that I've some issues with the versions of packages, and I need to compare my package.json with another package.json newly created.
Now when I Scaffold a new project using Yeoman SharePoint generator, I get this error:
Error: Cannot find "package.json" file required by this generator.

I've never this problem before, but just after upgrading generator-sharepoint.

**Comment by andrewconnell** [comment]
Where are you creating the project? In the same folder hierarchy?

When you create a project with the SPFx generator, Yeoman creates a hidden file **.yo-rc.json** in the folder. When you run the Yeoman generator a second time, it looks in the current folder + all folders above it, for this file. If it finds it, it thinks it's working in an existing project and is looking for other files, like **package.json**. I suspect this is what's going on. Create the project in a totally different folder from where you were creating others.

Here's what a plain SPFx v1.8.0 React project's **package.json** should look like:

```json
  "dependencies": {
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@microsoft/sp-core-library": "1.8.0",
    "@microsoft/sp-property-pane": "1.8.0",
    "@microsoft/sp-webpart-base": "1.8.0",
    "@microsoft/sp-lodash-subset": "1.8.0",
    "@microsoft/sp-office-ui-fabric-core": "1.8.0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.0",
    "@microsoft/sp-tslint-rules": "1.8.0",
    "@microsoft/sp-module-interfaces": "1.8.0",
    "@microsoft/sp-webpart-workbench": "1.8.0",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
```

@FullStackRafik says:
> I've never this problem before, but just after upgrading generator-sharepoint.

Without knowing previous scenarios, hard to say why, but the current issue is very clear what's going on. It's not just the generator that's your issue ATM, the project's **package.json** is the biggest problem.

**Comment by FullStackRafik** [comment]
> Where are you creating the project? In the same folder hierarchy?
I didn't know that I have to change also the parent directory(Workspace).
Now Here my new package.json:
```
{
  "name": "new-project",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "@types/react": "0.14.46",
    "@types/react-dom": "0.14.18",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-update": "0.14.14",
    "@types/react-addons-test-utils": "0.14.15",
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

```
I don't understand why I still get the same versions of SPFx and TypeScript type for React??!!

**Comment by andrewconnell** [comment]
@FullStackRafik said:
> I don't understand why I still get the same versions of SPFx and TypeScript type for React??!!

What do you mean "why i still get"... you mean when you run `npm install`? NPM uses what's in **package.json** when it downloads its dependencies. From the JSON in your last issue, you still haven't updated the versions as I've mentioned above. You have to manually edit **package.json** to update these.

Just take one example... you have:

```json
"@microsoft/sp-build-web": "~1.1.0"
```

Look at what I posted... notice the version number:

```json
"@microsoft/sp-build-web": "1.8.0"
```

That's just one example... compare yours to mine... there are a lot of incorrect versions. Until you update your **package.json**, you'll keep having the same experience.

You can also try the project update task from the Office 365 CLI... it will tell you what's wrong: https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/

**Comment by andrewconnell** [comment]
Also... you should *not* be using the `~` or `^` prefix on any **@microsoft/..** packages... install exact versions.

**Comment by FullStackRafik** [comment]
Perhaps I miss some details, but I know about NPM / Node.js project stuff and how it's working.
Before I upload the solution to a repository, I have just a question, I'm using Sharepoint 2016 On-Premises, so is this information can be an issue for SPFx versions?

**Comment by FullStackRafik** [comment]
Perhaps I miss some details, but I know about NPM / Node.js project stuff and how it's working.
Before I upload the solution to a repository, I have just a question, I'm using Sharepoint 2016 On-Premises, so is this can be an issue for SPFx, TypeScript and React versions?

**Comment by andrewconnell** [comment]
@FullStackRafik said:
> What are the supported versions of SPFx, TypeScript and React, React-Dom...for Sharepoint 2016 On-Premises?

:-|

Uh... yeah... **that is a critical detail that would have helped from the very start**. Basically, this whole thread is moot as you can't use the latest React...

Only SPFx 1.1 is supported in SP2016 on-premises & React is pinned to v15.4.2. Everything I said about no longer applies as I thought you were using SPO.

**Comment by middiu** [comment]
> @FullStackRafik said:
> 
> > What are the supported versions of SPFx, TypeScript and React, React-Dom...for Sharepoint 2016 On-Premises?
> 
> :-|
> 
> Uh... yeah... **that is a critical detail that would have helped from the very start**. Basically, this whole thread is moot as you can't use the latest React...
> 
> Only SPFx 1.1 is supported in SP2016 on-premises & React is pinned to v15.4.2. Everything I said about no longer applies as I thought you were using SPO.

Sorry to re-open this old conversation but I would like to make sure I got this right.

So for Sharepoint 2016 we can only use SPFx 1.1, that means we can only use React 15 and then only the libraries/modules that work with React 15. For example we can only use Fabric 5.

Am I correct?

**Comment by FullStackRafik** [comment]
> > @FullStackRafik said:
> > > What are the supported versions of SPFx, TypeScript and React, React-Dom...for Sharepoint 2016 On-Premises?
> > 
> > 
> > :-|
> > Uh... yeah... **that is a critical detail that would have helped from the very start**. Basically, this whole thread is moot as you can't use the latest React...
> > Only SPFx 1.1 is supported in SP2016 on-premises & React is pinned to v15.4.2. Everything I said about no longer applies as I thought you were using SPO.
> 
> Sorry to re-open this old conversation but I would like to make sure I got this right.
> 
> So for Sharepoint 2016 we can only use SPFx 1.1, that means we can only use React 15 and then only the libraries/modules that work with React 15. For example we can only use Fabric 5.
> 
> Am I correct?

Unfortunately, that's true :(
