### ISSUE TITLE
SPFx webpart is not loading in IE/Edge  and getting ReactMount errors for all my webparts

### ISSUE THREAD

**Issue by vbartari** [SharePoint/sp-dev-docs#375]
#### Category

- [x] Bug

#### Expected or Desired Behavior
In IE/Edge : SPFx Wepart should load and no errors in developer tool[F12]..

#### Observed Behavior
SPFx web-part is not loading in IE/Edge  and getting error like below for all the webparts:

**Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null**
It is working fine in Chrome.
#### Steps to Reproduce
Create a web-part using **yo @microsoft/sharepoint**
Select option as" **No JavaScript web framework**"
After doing require changes i have deploy my web-part in developer site and  getting reactmount error and I haven't created my web-part in react.
Can anyone let me know how can i solve this error as it's working only for chrome .

**Comment by patmill** [comment]
Hi @vbartari, can you add a bit more information.
Is this happening on the local workbench, the sharepoint workbench, a modern page, a classic page, everywhere?
Are you using the latest RC0 bits (I believe 0.4.1 is the most recent version of @microsoft/generator-sharepoint, which should reference all the correct files).
Does this happen with the default code, or have you modified it?  If you have made changes, what were they?

**Comment by vbartari** [comment]
@patmill No.. in local workbench it's working fine and i'm working on classic pages.. i havn't try for modern.
Yes it's latest RC0 because other drop like 6 is not working now
I have modified the code and added Angular code
 which you can find  from any site

**Comment by vbartari** [comment]
Anyone has any idea.. M still getting same issue

**Comment by nickaranz** [comment]
I am experiencing the same behavior. IE Edge will not render any of my SPFx web parts. The web parts are loaded on an old fashion publishing page. I get his error 

> Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.

from sp-application-base......js

**Comment by patmill** [comment]
Two asks

1 - If you select "technical Details", what does it say?
2 - Is the error scoped to the webpart itself, or is it a full page error?

**Comment by patmill** [comment]
No response for a long time - closing.
