### ISSUE TITLE
Incorrect single quotes in Typescript

### ISSUE THREAD

**Issue by johnseto** [SharePoint/sp-dev-docs#3750]
In step 4 of "Associate the dialog box with the ListView Command Set button click"

Line with code "Dialog.alert(`Picked color: ${dialog.colorCode}`);" 
The single quotes need to be changed from "back quote" to "single quote"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02c0a61-69ec-736e-2f49-d36bfe6cdddf
* Version Independent ID: 2eda912c-ebc1-f287-9c1a-656364e59457
* Content: [Tutorial - Use custom dialog boxes with SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx#feedback)
* Content Source: [docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Thanks @johnseto .  I've updated the source docs.  It will take a little while to prop.
