### ISSUE TITLE
New-SPOSite Adding an "a" to Subsite URLs that have a Leading Underscore

### ISSUE THREAD

**Issue by TreyKent** [SharePoint/sp-dev-docs#3751]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In SharePoint Online, the New-PnPSite command throws an error when attempting to submit a site with an underscore as the first character in the alias instead of adding an 'a' in front of it.  This would match the New-SPOSite command.  This should also work for communication sites.

#### Observed Behavior

New-PNPSite allows you to submit an alias of "_example" but the site that is actually provisioned has a URL of "https://example.sharepoint.com/sites/a_example".  This is confusing as it does not give an expected URL or match what Microsoft does with the SPO commands or through the GUI.

#### Steps to Reproduce

Use the New-PNPSite command to provision a site in SharePoint Online that has an underscore as the leading character in the alias.

**Comment by andrewconnell** [comment]
This issue should be posted to the issue list of the PnP PowerShell project here: https://github.com/SharePoint/PnP-PowerShell. It will get more visibility by those who work on that project & can associate work with specific commits.
