### ISSUE TITLE
Problem creating web parts for ON-PREM 2019

### ISSUE THREAD

**Issue by Mhepplew** [SharePoint/sp-dev-docs#3752]
I am trying to create SPFx web part FOR ON-PREM 2019 but facing issues on running the gulp serve command following creating a basic helloworld web part (no coding).

OS - Windows 10
Node version - 8.15.1
NPM version - 6.9.0
SPFx version - 1.8.0

I followed everything as per Microsoft documentation, which I have done successfully for ONLINE many times. However, when trying to create same but for ON-PREM 2019 the yoman generator doesn't create something that builds. gulp serve throws an error.

With some investigation I note that package.json dependancies are "~1.4.0" and devdependancies are "~1.4.1". The error complains about "@microsoft/sp-property-pane" which is in the header of the main web part (HelloWorldWebPart.ts).

With a little reading up, isn't "@microsoft/sp-property-pane" a SPFx 1.8.0 thing? Shouldn't the generator for ON-PREM 2019 be outputting 1.4 compatible code? 

I build ONLINE web parts too so may well be that my environment is too 'latest/greatest' for On-PREM?

Can anyone provide the ideal node/npm/yo/SPFx etc. versions required to build ON-PREM 2019 SPFx web parts?

**Comment by patmill** [comment]
See #3621  for more information and a workaround.
