### ISSUE TITLE
SharePoint Migrations too Slowly

### ISSUE THREAD

**Issue by silvafr1** [SharePoint/sp-dev-docs#3753]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hello,

On the last couple of months we have been on migration process from SharePoint On premise to SharePoint Online using a third part tool ShareGate and every site migration we plan to do is a nightmare because of the slowness, it can take 2 days or more to copy 2 Gb site to 0365. For example, at the moment we are copying a 3,1Mb site for 5 hours and still going..

We are following some recommendation like, copying one site each time, copy structure first and them content after but without getting better. There are a few days that the behavior is quite better but most of them are really hard. We also notice that most of the migrations we got Throtling messages like: “One of your tasks is currently throttled by Office 365”. And even time to time we also get this error message “The remote server returned an error: (429)”

Could you help us on this subject and check were could be the issues?

Let us know which is the right way to provide you the tenant name and other details that might be the subject of GDPR.

Thank you!

**Comment by patmill** [comment]
This is outside the scope of this issues list.  Have you contacted product support and/or ShareGate?
