### ISSUE TITLE
SharePoint Learning Center bug on our Dev Tenant

### ISSUE THREAD

**Issue by simplysql** [SharePoint/sp-dev-docs#3754]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea
Trying to provision SharePoint learning site - we get this error

SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed. | SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed.
-- | --
SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed.
 
Here is the exception that occurred:     Type = System.ArgumentException Message = Page Home.aspx is     not a "modern" client side page Source = OfficeDevPnP.Core     TargetSite = OfficeDevPnP.Core.Pages.ClientSidePage     Load(Microsoft.SharePoint.Client.ClientContext, System.String) StackTrace =     at OfficeDevPnP.Core.Pages.ClientSidePage.Load(ClientContext cc, String     pageName) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web     web, ProvisioningTemplate template, TokenParser parser,     ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web     web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation     provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2147024809 | Here is the exception that occurred:     Type = System.ArgumentException Message = Page Home.aspx is     not a "modern" client side page Source = OfficeDevPnP.Core     TargetSite = OfficeDevPnP.Core.Pages.ClientSidePage     Load(Microsoft.SharePoint.Client.ClientContext, System.String) StackTrace =     at OfficeDevPnP.Core.Pages.ClientSidePage.Load(ClientContext cc, String     pageName) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web     web, ProvisioningTemplate template, TokenParser parser,     ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web     web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation     provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2147024809
Here is the exception that occurred:     Type = System.ArgumentException Message = Page Home.aspx is     not a "modern" client side page Source = OfficeDevPnP.Core     TargetSite = OfficeDevPnP.Core.Pages.ClientSidePage     Load(Microsoft.SharePoint.Client.ClientContext, System.String) StackTrace =     at OfficeDevPnP.Core.Pages.ClientSidePage.Load(ClientContext cc, String     pageName) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web     web, ProvisioningTemplate template, TokenParser parser,     ProvisioningTemplateApplyingInformation applyingInformation) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web     web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation     provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     337 HResult = -2147024809

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Your exception indicates that you are trying to apply the template on top of an existing site, which is not compliant with the template... like the existing site being classic team site. In upcoming versions, we will not even support this, but to test the service, would suggest ensuring that you use a new URL or delete the old site collection from the URL which you want to use.

Can you retest this with the latest version and use a clean URL?
