### ISSUE TITLE
[Feature request] add --nobuild flag to gulp serve

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#3758]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

#### Expected or Desired Behavior

Feature request: add `--nobuild` flag to `gulp serve`

#### Observed Behavior

When using `@microsoft/rush` the `rush build` command bundles all projects which are referenced in the monorepo - including SPFx projects.
When running `gulp serve` in (one of) the SPFx project(s), the `bundle` gulp command _rebuilds_ the project. This is an unnecessary step, which would be nice if we could disable.

#### Proposed solution
Add a `--nobuild` flag support to the `gulp serve` command so we can start the local web server without rebuilding the SPFx code.

**Comment by andrewconnell** [comment]
Good suggestion... feature requests should be posted to user voice @ https://aka.ms/sp-dev-uservoice

**Comment by NickSevens** [comment]
Uservoice has been created @ https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37327795-add-nobuild-flag-to-gulp-serve
