### ISSUE TITLE
Error using SPHttpClientConfigurations with the SPHttpClient

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#376]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Using the SPHttpClient should work as [described in the release notes](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0#update-your-webpart-code).

#### Observed Behavior
When trying to use the `SPHttpClient` passing `SPHttpClientConfigurations.v1` as the configuration, the browser throws an error `Cannot read property 'v1' of undefined`.

#### Steps to Reproduce
- create new web part using React
- add `import { SPHttpClientConfigurations } from '@microsoft/sp-http';`
- in the **render** method add `this.context.spHttpClient.get('/_api/web', SPHttpClientConfigurations.v1);`
- `$ gulp serve --nobrowser`
- open hosted workbench and add the web part to canvas
  - error is displayed in the console

**Comment by vman** [comment]
I got this in a couple of tenants as well. Is it that the RC0 bits have not fully landed in all the tenants yet?

Worked fine on other tenants.

**Comment by waldekmastykarz** [comment]
It turns out it's due to a typo in the documentation (that has been fixed). The correct usage is:

```ts
import { SPHttpClient } from '@microsoft/sp-http';

this.context.spHttpClient.get('/_api/web', SPHttpClient.configurations.v1);
```

**Comment by vman** [comment]
This one is interesting. @VesaJuvonen I see you have made the edit to the docs. Could we get more info on which method of specifying the config is recommened? As @pgonzal has recommened using SPHttpClientConfigurations.v1 here https://github.com/SharePoint/sp-dev-docs/issues/44

**Comment by pgonzal** [comment]
When writing new code, our intent is for you to always specify the most recent version (i.e. "v" followed by the largest integer that is defined).  This should give you all the recommended features, and disable any deprecated features.

When reusing code, e.g. copying snippets from the internet, you should not change the version number unless you are explicitly doing the work to migrate/retest the code.

That is the main reason why we introduced these configurations.  (You can also use `overrideWith()` to customize the configuration, but personally I believe that is a rare edge case.  In most cases you can achieve what you need by using the normal options.)

**Comment by bilalkhan870** [comment]
i am facing some issues with Alert notification, 
--------------------------------------------------------
TypeError: Cannot read property 'spHttpClient' of undefined
    at alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
    at new Promise (<anonymous>)
    at e._loadUpcomingAlerts (alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15)
    at alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
(anonymous) @ alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
Promise.catch (async)

Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:420
    at a (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:523)
    at render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:104206)
    at https://alsaqergroup.sharepoint.com/sites/APPS/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15:258561
----------------------------------------------------------------------------

thanks in advance
