### ISSUE TITLE
How can I add a logo image to the header and links to footer?

### ISSUE THREAD

**Issue by coxwagner** [SharePoint/sp-dev-docs#3761]
This is great! Thank you so much! 
I have a couple questions that may be too easy for you... 
1. How can I add a link logo image on the header?
2. How can I add some text navigation on the footer? If the links on the footer could be populated from a SP Links list that will be even 'awesomer'.

Thank you in advance!
Wagner

**Comment by patmill** [comment]
At the moment, there are no customizations that can specifically target existing components.  You can create your own top and bottom sections using the ApplicationCustomizer and Placeholders, but that's not going to solve your problem.  Your best bet is to open a UserVoice request in the product section, as this seems more like configuration scenario than a customization scenario.  In other words, you shouldn't have to write code to set an link on your logo.  https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration
