### ISSUE TITLE
Change footer add links

### ISSUE THREAD

**Issue by hekema** [SharePoint/sp-dev-docs#3763]
How does one change the footer text? (the support@contoso.com etc?

**Comment by patmill** [comment]
Sorry - can you elaborate?  Is this the standard product, tweaking a PNP solution, something else?

**Comment by hekema** [comment]
I've provisioned the starter site - but can't find where/how I change the text in the footer

**Comment by bcameron1231** [comment]
@hekema  You'll want to download the source files from  Github for the PnP Starter Kit, and modify the templates.

Here is a blog post that discusses this topic for the footer, for already installed solutions or during fresh installs. 
https://beaucameron.net/2018/07/19/customizing-the-pnp-starter-kit-for-office-365-part-1-portal-footer/
