### ISSUE TITLE
TypeScript errors. SP2016 On-Premises, SPFx 1.1.0

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-docs#3764]
Hello,
I get some errors when trying to execute gulp serve:

error TS1005: ',' expected.
: error TS2345: Argument of type '{ 
error TS2346:
sub task errored after 5.29 s
 "TypeScript error(s) occurred.

I'm using SharePoint2016 On-Premises with SPFx1.1.0.
This is my **package.json**

```
{
  "name": "Crud-Project",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/common": "^1.3.1",
    "@pnp/logging": "^1.3.1",
    "@pnp/odata": "^1.3.1",
    "@pnp/sp": "^1.3.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/rx-lite": "^4.0.6",
    "@types/webpack-env": "1.13.1",
    "bootstrap": "^4.3.1",
    "core-js": "^3.0.1",
    "jquery": "^3.3.1",
    "minimatch": "^3.0.4",
    "minimist": "0.0.8",
    "mkdirp": "^0.5.1",
    "moment": "^2.24.0",
    "popper.js": "^1.14.7",
    "react": "15.4.2",
    "react-accessible-accordion": "^2.4.5",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "15.4.2",
    "react-icons": "^3.5.0",
    "rx-lite": "^4.0.8"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^2.2.2"
  }
}

```

This is the ouput of `npm list typescript`
```
+-- @microsoft/sp-build-web@1.1.0
| `-- @microsoft/gulp-core-build-typescript@3.1.1
|   +-- @microsoft/api-extractor@2.3.8
|   | `-- typescript@2.4.2
|   `-- typescript@2.2.2
`-- typescript@2.9.2
```
I removed npm_modules and I executed npm install several times, but always I get the same error.

Any suggestions please?

**Comment by FullStackRafik** [comment]
Just for information, I can resolve this issue by replacing @microsoft folder in node_modules from a newly created SPFx project.
But I'm still wondering about the reason, and how can I resolve it without copying this folder each time

**Comment by andrewconnell** [comment]
As the issue template requested, please provide the additional core details:

- version of node
- version of NPM
- version of SPFx generator installed

**Comment by FullStackRafik** [comment]
> version of node

v8.11.4


> version of NPM

5.6.0

> Version of SPFx generator installed

`-- @microsoft/generator-sharepoint@1.8.0, but in the current project I use SPFx1.1.0

**Comment by andrewconnell** [comment]
Can you show more details for the error? Does it happen when you run `gulp build`?

Impossible to know what's going on without more details on the error or what it's pointing to...

**Comment by FullStackRafik** [comment]
@andrewconnell said:
> Can you show more details for the error? Does it happen when you run gulp build?

It happen when I run "npm install" then "gulp serve" or "gulp build".
Here are the errors I get:
```
node_modules\@pnp\common\src\util.d.ts(66,56): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\common\src\util.d.ts(66,88): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\parsers.d.ts(44,36): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(88,24): error TS1005: ',' expected.
node_modules\@pnp\sp\src\items.d.ts(59,0): error TS1128: Declaration or statement expected.
 error TS2346: Supplied parameters do not match any signature of call target.
```
I can resolve the issue by removing some created folders inside 'gulp-core-build-typescript', and I know that is about packages versions, but I need to know which packages are causing the issue.

**Comment by andrewconnell** [comment]
If you look at the errors, those are all related to the PNPJS library's type declarations. Best if you post your issue in the repo for that library: https://github.com/pnp/pnpjs

**Comment by FullStackRafik** [comment]
Ok, I'll post my issue in the repo for pnpjs, but there are also other erros related to uifabric:
`node_modules\@uifabric\utilities\lib-es2015\BaseComponent.d.ts(97,4): error TS1005: ',' expected.`

and others related to my files:
`src\states\IFactoryMethodState.ts(1,11): error TS1109: Expression expected.`

So I don't know if the problem is only related to PnPJS.
