### ISSUE TITLE
[LOC] Invalid links in an article 

### ISSUE THREAD

**Issue by OfficeGlobal** [SharePoint/sp-dev-docs#3766]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
2. Search links listed below
3. Click the link --> 404 error page

Link text | Link URL
-- | --
Debugging Remote Event Receivers with   Visual Studio (MSDN Blog Post) | http://blogs.msdn.com/b/officeapps/archive/2013/01/03/debugging-remote-event-receivers-with-visual-studio.aspx
Update to debugging SharePoint 2013   remote events using Visual Studio 2012 (MSDN Blog Post) | http://blogs.msdn.com/b/officeapps/archive/2013/03/21/update-to-debugging-sharepoint-2013-remote-events-using-visual-studio-2012.aspx

**Expected:** Links should be updated or removed from the article

Screen:
![image](https://user-images.githubusercontent.com/47977325/55872048-4dc7ce80-5b8c-11e9-8810-7f5ab9f98dac.png)

**Comment by patmill** [comment]
OK, removed the links, since the blog posts have been removed from the system.
