### ISSUE TITLE
Localization: How to prevent code duplication with SPFx RC0?

### ISSUE THREAD

**Issue by michel-weber** [SharePoint/sp-dev-docs#377]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a loc-file `en-us.js` and a translated german file `de-de.js`.
Now I would like to add the language de-CH which is in this instance exactly the same as de-DE.
How can I achieve this without copying & pasting & renaming the file (de-de.js --> de-ch.js)?

#### Steps to Reproduce
1) Create a new project: yo @microsoft/sharepoint
2) Add a translated loc-file
3) Try to define a new locale without just duplicating the file

#### Thoughts
1) First thought was to somehow "link" the existing file (similarly to Visual Studios functionality to not copy but add a file "as link"). This is not supported by VS Code.
2) Define a custom gulp build task to copy (and rename it) before running the app. Defining a custom build task with typescript seems to be quite complicated.

Links:
https://blog.mastykarz.nl/sharepoint-framework-build-custom-tasks/

http://webcache.googleusercontent.com/search?q=cache:GbWsbgQFQOYJ:www.n8d.at/blog/use-custom-gulp-tasks-in-the-new-sharepoint-framework/.

**Comment by patmill** [comment]
@iclanton , @nickpape-msft  - any ideas on this?

**Comment by iclanton** [comment]
We have locale disambiguation logic on the server, so a user in the de-CH locale may automatically get mapped to de-DE. Have you tried it?

You can use the pre-copy build task to copy a file before the main build if you don't want to have two copies of the same file checked into your repository.

**Comment by michel-weber** [comment]
I have not tried running it on a server as I don't have a first release tenant at the moment. So I haven't tried out the locale disambiguation logic on the server.

I'm still trying to find out how I can use the pre-copy build task - especially where and how I define it?
The only resource I found is this:
https://github.com/Microsoft/gulp-core-build-typescript/blob/master/README.md

At least with the local workbench, it does not work to rename the resource "de-de.js" to "de.js". After a `gulp clean` - when I specify either `gulp serve --locale=de-de` or `gulp serve --locale=de-ch` it always loads en-us.js (the default).

**Comment by iclanton** [comment]
I spoke too soon WRT the copy tasks - they don't support renaming files, just moving them around. However, in case anyone stumbles upon this thread and is winder how to define a copy, you need to drop a file called `pre-copy.json` (or `post-copy.json`) in the `config` folder with this schema:

```JSON
{
  "copyTo": {
    "dist": [
      "src/*.html"
    ]
  }
}
```

If you rename your resource to just `de.js`, you'll want to run `gulp serve --locale de`, because the locale you've specified is "de", not "de-CH" or "de-DE". There's no disambiguation logic in the build tools :).

The parent locale of both "de-CH" and "de-DE" is "de", so a user in either should end up with the "de" resource.

**Comment by michel-weber** [comment]
Thank you very much Ian. I renamend the resource to the parent locale and will try it out on SharePoint Online as soon as I get a first release tenant.
