### ISSUE TITLE
SharePoint 2019 OnPrem?

### ISSUE THREAD

**Issue by mjones0204** [SharePoint/sp-dev-docs#3777]
Does this work for SharePoint 2019 OnPrem?  I performed the steps above using PowershellPNP to update the Site Page and am getting the following message when accessing the page:  ***Error initializing application. Error: Error: ***Invalid GUID string: "SingleWebPartAppPage".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42d2d41-61bb-e281-3dac-328292b7b192
* Version Independent ID: 05b12512-7aa9-3ac7-e23e-0d5ae2209a59
* Content: [Using single part app pages in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages#feedback)
* Content Source: [docs/spfx/web-parts/single-part-app-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/single-part-app-pages.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
No, this is not supported in 2019 - only SharePoint Online.
