### ISSUE TITLE
Syntax problem with the schema file example

### ISSUE THREAD

**Issue by KendraCodes** [SharePoint/sp-dev-docs#3778]
The example schema.xml syntax for linked ContentTypes didn't work for me. The example shows &lt;ContentTypes&gt;&lt;ContentTypeRef ID=""/&gt;&lt;/ContentTypes&gt;, but doing it that way kept the columns I created from showing up in the New/Edit views of my provisioned list. It worked as expected when I changed the syntax to &lt;ContentTypes&gt;&lt;ContentType ID=""/&gt;&lt;/ContentTypes&gt; instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets#feedback)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Hmm... can you provide a repro because that's not what I've seen & that doesn't follow the **schema.xml** syntax: https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms459356%28v%3doffice.14%29
