### ISSUE TITLE
Sharepoint navigation to other pages, other pages with hashes, or to the same page with hashes have weird behavior

### ISSUE THREAD

**Issue by tgorgdotcom** [SharePoint/sp-dev-docs#3779]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Links with hashes should work.  Navigation between pages and pages with hashes should work.

#### Observed Behavior

- URLs with hashes do not scroll to the area within the page that contains the element ID attribute on initial page load
- Clicking on links to go to different IDs within the page work, but clicking back or forward to navigate in between hashes do not work
- Following a link to another page with a hash does not scroll to the area within the page that contains the element ID attribute
- The following was tested within pages on the same site:
  - Using the forward button in the browser to advance to another page sometimes does not fire the page load.  This usually occurs after:
    - Clicking a few links to ID items within the same page,
    - Then clicking a link that goes to an ID on another page,
    - Then clicking the back button, 
    - And then finally clicking the forward button.
  - Sometimes links to IDs on the same page will fire a reload on click (rather than it just going to the element with the ID).  This will also occur when going back or forward to different hash/IDs on the same page.  This is usually triggered by:
    - Clicking on a link on one Sharepoint page to go to another Sharepoint page /w a hash, 
    - Then clicking back
    - Now all links and history navigation to IDs on the same page will exhibit this behavior

#### Steps to Reproduce

**I tested this on Chrome 73.0.3683.86, Safari 12.0.3, and Firefox 65.0.1 (64-bit)**

- Create two pages within the same site (or perhaps even different sites)
- For both pages: In text editor webparts that allow you to create elements with id tag attributes, create a few elements and set an id values to them.  Alternatively you could create the elements using a script editor webpart.
- Create a section of links that link to IDs in the same page and to IDs on other pages

-------

I hope this was complete.  I've written a lot of code (days/weeks) to override these behaviors, but it would be better if it was working by default.  Thanks!

**Comment by andrewconnell** [comment]
Sounds like the page router is causing issues with how you expect things to work? Have you seen this? https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target 

Is that related?

**Comment by tgorgdotcom** [comment]
It's similar in that its probably related to some kind of page routing process in Sharepoint.  I do have a bunch of code to work around most of the issues, but it's not perfect.  To fix it I added an extension that runs on all pages and adds events and overrides as needed.  I did try to add logic to include the "data-interception" argument to any and all anchor tags that referenced the same page, but I fell back to adding a event on a container div, because I was worried about adding these to webparts that weren't visible or not loaded.

Ultimately, I don't believe these issues should be fixed by workarounds.  Anchors/hashes, along with the target attribute, are an integral component of the browser.  I feel like anything that would override this basic behavior is problematic.

**Comment by andrewconnell** [comment]
@tgorgdotcom said:
> Ultimately, I don't believe these issues should be fixed by workarounds. Anchors/hashes, along with the target attribute, are an integral component of the browser. I feel like anything that would override this basic behavior is problematic.

Microsoft would see this as a feature to minimize the page size when navigating through SPO. As such, I don't think they see what you're doing as "workarounds" so I think your request is more in line with a feature request to change a behavior that's "by design", if your issue is in fact related to the page router. As such, feature requests should go to user voice https://aka.ms/sp-dev-uservoice.

If you think this is not related to the page router & there are UX bugs, please follow up and we can re-open the issue.

**Comment by tgorgdotcom** [comment]
Would it be possible to get a second opinion on this?  @VesaJuvonen?

**Comment by tgorgdotcom** [comment]
Bump.  Sorry to be a bug.  I understand the advantages to dynamic loading, but it shouldn't break basic browser behavior.

 @VesaJuvonen

**Comment by andrewconnell** [comment]
@tgorgdotcom respectfully @VesaJuvonen can't follow up on every issue in the issue list. :) 

In a recent conversation, I did make him aware of it and if he disagreed with what I stated above, I'm sure he would have chimed in.

**Comment by tgorgdotcom** [comment]
Totally understood.  I appreciate that at least it was brought up to anyone at MS offline.
