### ISSUE TITLE
Bug: Css element Position fixed behaves differently in Edit and Read Mode in Modern Page

### ISSUE THREAD

**Issue by Masood10** [SharePoint/sp-dev-docs#3781]
#### Category
- [X] Question
- [X] Bug

#### Expected or Desired Behavior
Placing an HTML element with position fixed should stay in its place in both edit and read mode of the Modern page.

#### Observed Behavior
I am trying to place a fixed html div element on my web part like for example a header behaves on scrolling the page. I am using the position fixed to achieve it and it seems to be working in edit mode of modern page but when I go to the read mode all of sudden the fixed position stops working. 
In Classic pages it works as expected.

The behavior has nothing to do with my implementation of the Web part. For Instance even If I take a sample code from spfx examples and change the position of an element to fixed. I observe the same behavior  

#### Steps to Reproduce

Go to Inspect Element of any web Part and change the position of top element to fixed and scroll the page in both edit and read mode you will see it.
Thanks

@VesaJuvonen 
@KingKangMSFT 
@wobba

**Comment by mcmynn83** [comment]
@Masood10  - Unfortunately you are doing something that is unsupported.  We provide extensions that give areas of the page that can be updated and we will flow the page around these specified areas. As soon as you position something absolute or fixed you are outside of the supported scenario.  We do not guarantee that rendering like that will continue to work the same, or look the same in different modes.
