### ISSUE TITLE
PropertyPaneDynamicField class properties ignored

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#3786]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the PropertyPaneDynamicField widget for dynamic data, the properties **sourcesLabel** and **filters** should not be ignored and work as explained in their respective documentation.

As documented: 
- The **sourcesLabel** property should let you replace the default "Connect to source" label by your own label
- the **filters** property should let you filter the sources displayed in the widget's dropdown either by componentId, propertyId or sourceId

#### Observed Behavior

Using the code below in SPFx 1.8.0 :

```typescript
PropertyPaneDynamicFieldSet({
    label: 'Paging 1',
    fields: [
        PropertyPaneDynamicField('selectedPage', {
            sourcesLabel: 'Connect to a paging WebPart',
            label: 'Paging 2',
            filters: {
                componentId: Guid.parse('e8e4a931-16e9-4980-98fa-a911cd517080'),
                propertyId: 'selectedPage'
            }
        })
    ]
})
```

- The label "Paging 1" is ignored and not displayed anywhere
- The label "Connect to a paging WebPart" is ignored and does **not** replace the default "Connect to source" label
- The **filters** property is ignored and the dropdown shows everything available no matter what I put in there

It looks like the API is there but not coded yet, and it's a shame because I must be able to filter the sources displayed in the dropdown :(

#### Steps to Reproduce

Use the code above and notice how the properties are ignored

**Comment by andrewconnell** [comment]
Where are you seeing the `sourcesLabel` incorrectly documented? This works locally for me in v1.7.1+ with respect to `filters`, `label` & `sourcesLabel`:

```ts
PropertyPaneDynamicFieldSet({
  label: 'Select image source',
  fields: [
    PropertyPaneDynamicField('apolloImageFilename', {
      label: 'Apollo image source'
    })
  ],
  sharedConfiguration: {
    depth: DynamicDataSharedDepth.Property,
    source: {
      sourcesLabel: 'Select the web part containing the list of Apollo Missions'
    },
    property: {
      filters: { propertyId: 'image' }
    }
  }
})
```

**Comment by spplante** [comment]
@andrewconnell I didn't see anything incorrectly documented, it just doesn't do anything on my side :(

However, if you look at my code, the **sourcesLabel** and **filters** property are on the **PropertyPaneDynamicField** control, not within the **sharedConfiguration** property as shown in your code.

Is that how it's supposed to be done? Because both properties are also documented on the **PropertyPaneDynamicField** control...I will try it the way you suggested tonight, will report back if that works better 👍 

Thanks!

**Comment by spplante** [comment]
@andrewconnell I confirm that specifying the **sourcesLabel** and **filters** properties in the **sharedConfiguration** object rather than on the **PropertyPaneDynamicField** itself does work as expected. And since my source only exposes one property than I my **filter** is targeting it, the property dropdown is not even shown which is exactly what I needed because at this point it's too much information for the user.

Still not sure why the properties are also documented on the **PropertyPaneDynamicField** since it doesn't look like they do anything, but it does work perfectly on the sharedConfiguration so thanks a lot for this!
