### ISSUE TITLE
1.8 Teams: Inconsistent load order for CSS

### ISSUE THREAD

**Issue by d-martins** [SharePoint/sp-dev-docs#3788]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The web part styles should load in a predictable, consistent order regardless of environment.

#### Observed Behavior

After migrating some projects to teams, we noticed that two of our CSS files were being loaded into the page in the wrong order and breaking the visual style of the web parts.
In the workbench and modern pages we cannot reproduce the same behavior.

I've created a simplified example project [here](https://github.com/d-martins/spfx-css-issue) which can be used to observe the issue.

#### Steps to Reproduce

1. Clone or download the [example repo](https://github.com/d-martins/spfx-css-issue) 
1. Install and deploy the .sppkg file found in the `sharepoint/solution/` folder to the App Catalog
2. From the App Catalog, click the "Sync with teams" button in the ribbon
3. Open a team in the Microsoft Teams application
4. Add a new tab and select the "Red or Green" app
5. Close the property pane
6. Refresh a couple times using the tab using the "reload tab" button (not the browser refresh button)

Some times the background will be displayed in green when it should always be red

**Comment by patmill** [comment]
Hi, and sorry for the long delay.  We've tried to repro this on recent builds, but we can't get it to be random.  Is it still happening for you?
