### ISSUE TITLE
Creating an in-memory provisioning template from an xml string

### ISSUE THREAD

**Issue by rjn71** [SharePoint/sp-dev-docs#3789]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Creating an in-memory provisioning template from an xml string

All the examples I've come across for applying a provisioning template involve reading the template from a physical file path. I would like to create an in memory template reading from an xml string and then call Apply-PnPProvisioningTemplate. Reason being I'm executing the powershell script in Azure function and I'm passing the template as a string parameter to the azure function. I've tried creating a template object using New-PnPProvisioningTemplate, but after that I couldn't figure out how to set the template with the xml supplied. I looked at Read-PnPProvisioningTemplate, but that also expects a file path as input. 

Thanks

**Comment by rjn71** [comment]
Wrong github repository as this is related to PnP

**Comment by andrewconnell** [comment]
This question is probably best posted to the PnP Core repo as that's where all the work & people involved with it address feedback: https://github.com/SharePoint/PnP-Sites-Core
