### ISSUE TITLE
Site design/ Site script AddSPView how to enable mobile view

### ISSUE THREAD

**Issue by cbadouin** [SharePoint/sp-dev-docs#3790]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I am creating a new list with a SharePoint Site Design / Site Script and create one or several custom views. I expect an (sub-)action to enable the view(s) as mobile view.

#### Observed Behavior
I can't find a way to activate the view as mobile view. All created views are disabled for mobile...
 (https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)

Am I missing something or is there no way to add the view as mobile at the moment?

Thanks for your help!

**Comment by VesaJuvonen** [comment]
That setting is currently not unfortunately supported by the Site Design / Site Scripts capability.
