### ISSUE TITLE
What means tenant admin?

### ISSUE THREAD

**Issue by stche** [SharePoint/sp-dev-docs#3793]
#### Category
- [X] Question
- [X] Additional article idea

#### More clarity on the service description

Using a dedicated "SharePoint Admin" should be enough to log-on and use the 
"SharePoint Online Provisioning Service"  to install a solution (i.e. Custom learning)
While the "service Description (https://provisioning.sharepointpnp.com/home/contentPage?contentPageId=ServiceDescriptionLong) just says:
"...you must be authenticated with appropriate credentials--tenant admin or site admin--as specified in the template documentation."

#### Question:

It is not clear, whether this means a "global tenant admin" with the full set of highly privileged permissions is required 
OR 
if a dedicated user with the "SharePoint Admin Role" would be sufficient for this task to install and add a template.

#### Expected Behavior

Please can you update the documentation to clarify the "role" that is required as it may confuse customers and in a highly regulated environment following the "least privilege model" it might be difficult to get the global tenant admin credentials just for a template installation that likely is maybe nothing more than a simple SharePoint Admin task.

**Comment by VesaJuvonen** [comment]
It should be clear that the messaging will be SharePoint Admin role when that's sufficient. As in this case we are talking about underlaying permission set model in Azure AD, where we need to have the full permission in tenant level, tenant admin means tenant admin... as in tenant administrator. Unfortunately, Azure AD does not support more granular permission setup for the applications.

You can though apply these templates in your tenant manually using PnP PowerShell or CSOM extension with the SharePoint admin role as the above limitation is not valid when you are not running in the application context.

**Comment by stche** [comment]
Thank you Vesa ;-)
