### ISSUE TITLE
Section background color is messing up with list webpart

### ISSUE THREAD

**Issue by BigBd1** [SharePoint/sp-dev-docs#3794]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The standard list webpart used to have a white background even if it was inserted into a section with a background color :

![issue_original](https://user-images.githubusercontent.com/4406847/56196486-34fd6400-6037-11e9-9c37-53501ff0267c.png)

#### Observed Behavior

Since a week the list webpart has taken the section's background color making the items (especially the title column) barely readable : 

![issue_actual](https://user-images.githubusercontent.com/4406847/56196630-7db51d00-6037-11e9-994a-1e73c6d61951.png)

Is it a bug or the expected behavior ? In the second case, it would be great if the title font color could be turned to white as the other column, in order to make it more readable.

Thanks in advance for your assistance !

**Comment by VesaJuvonen** [comment]
As this is not a developer related issue, we cannot provide support for it through this channel. Can you please submit it as an issue using the tenant admin UI support channels in your tenant admin dashboard. Thx.
