### ISSUE TITLE
SPFx extensions not working in Sharepoint Modern list default pages

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#3795]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Hi Team,

We have created a SPFx extension with Top and Bottom placeholders. Both these placeholders have data manipulations which is fetched from external js file(loaded through SPComponentLoader inside Init method) uploded in the same SIte Collections. 
After deploying and adding the app across Site Collection,the extensions are working fine across Site Pages. But when we tried creating a new Sharepoint list with Modern Experience, the Top and Bottom Placeholders are not loading in the list pages(AllItems.aspx).

Any ideas on why this is happening.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
@srisspfx says:
> Any ideas on why this is happening.

Not without having more context (SPFx version used), browser, SharePoint environment & seeing some code... can you provide some additional context?

**Comment by MaartenSundman** [comment]
Sounds like it may be related to https://github.com/SharePoint/sp-dev-docs/issues/2779 

The root cause on that was the application extension wasn't properly interacting with the placeholders. Due to using an older method of interaction. Updating to use: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions instead fixed the issue

**Comment by patmill** [comment]
Sorry - misread the thread.  I thought Maarten was saying he fixed his code and the bug was gone, not that he solved it, so srisspfx might try the same thing.

**Comment by srisspfx** [comment]
> @srisspfx says:
> 
> > Any ideas on why this is happening.
> 
> Not without having more context (SPFx version used), browser, SharePoint environment & seeing some code... can you provide some additional context?

Hi Andrew,

Tried logging in console after the promise, below is the error that we are getting.

![image](https://user-images.githubusercontent.com/49272371/56268581-5598ed00-610f-11e9-8e59-386cd79d8027.png)
![error](https://user-images.githubusercontent.com/49272371/56268641-7a8d6000-610f-11e9-8f29-0f1aeee1da1e.png)

NOTE: We have noticed that the placeholder is loading properly, but components loaded through SPComponentLoader doesn't work. This is happening only in List pages and not on Site Pages.

Thanks in advance.

**Comment by andrewconnell** [comment]
@srisspfx Can you provide a link to a GH repo that has a minimal repo of the issue? Would make for evaluating this as a bug a lot easier...

**Comment by srisspfx** [comment]
[HelloWorldApplicationCustomizer.txt](https://github.com/SharePoint/sp-dev-docs/files/3116092/HelloWorldApplicationCustomizer.txt)

Above is the source code for .ts file.

Its not passing beyond the below code:
SPComponentLoader.loadScript("https://ABC.sharepoint.com/sites/uatModern/SiteAssets/Modern/jquery-3.3.1.min.js")
So it fails to load the jquery plugin, because of which, none of the subsequent js files are loaded.

Thanks.

**Comment by srisspfx** [comment]
This happens only when we open the Modern list page(AllItems.aspx). If i create a normal Modern SitePage, its executing all .js files successfully.

**Comment by srisspfx** [comment]
any updates on the issue why it is happening?

**Comment by andrewconnell** [comment]
According to the 1.8.2 release notes out today it appears MSFT is aware and "working on it"

**Comment by GrahamMcMynn** [comment]
@srisspfx - sorry for the super slow response here.  We just got around to looking at this and it appears that it is no longer reproing (on a list I am able to load a placeholder which in the oninit function calls SPComponentLoader.loadScript("https://<tenant>/SiteAssets/Modern/jquery-3.4.1.min.js") and then have the promise resolve).  Are you still seeing this issue?
