### ISSUE TITLE
Best way to connect external API secured without Azure AD  ?!

### ISSUE THREAD

**Issue by falkin** [SharePoint/sp-dev-docs#3796]
I'm currently developing a WebPart for Sharepoint Online with Sharepoint Framework and react.

Each user need to connect to an external API protect with a username and passwords. This external API isn't connected with an Azure AD or AD and return a "Bearer Token". This token is generated inside service. This is an external service and I can't change how it works. I'm a little bit lost about what is the best and proper way to do that.

Firstly, I decided to manage connection directly inside WebPart but I saw that there is options on Azure to add applications and manage connection may be i can use that but most of them use Azure AD and this is not my case. 

I want that each user can give his username and password and use it for generate token and call API requests. 

So how I can do that in with a cleanest and securest way? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b84eaa-9fbf-6d45-fda6-0f59ea10ac30
* Version Independent ID: 46395b70-89c3-b77b-0fc1-e8a86ff093ad
* Content: [Connect to anonymous APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-anonymous-apis)
* Content Source: [docs/spfx/connect-to-anonymous-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/connect-to-anonymous-apis.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
What type of auth does the external API supports? You mention bearer token, so it smells like OAuth... but what flow does it support? 

If it does not support the implicit flow where you can do auth client-side, your best option is to create a proxy service. THAT could be secured with Azure AD, then your SPFx component could leverage the `AADHttpClient` to auth against your custom proxy service. 

That proxy service could then authenticate with your external service, call it and return the data back to the SPFx compone that called it.

**Comment by falkin** [comment]
What type of auth does the external API supports? None except with explicit password and username combination. (Bearer Token is just use for a state-full exchange). 

Ok I will check if a solution like that with a proxy is possible but firstly i will check with who did API if it's possible to change how it was done. 

Thank you.

**Comment by andrewconnell** [comment]
@falkin says:
> What type of auth does the external API supports? None except with explicit password and username combination.

But that is a type of auth... username/password = basic... but that's not an OAuth flow. The use of a bearer token is not clear... but I don't have full context so it's expected.

A proxy is definitely possible as it will use server-side code. The challenge with this approach is the user experience, but sometimes it's the only option.
