### ISSUE TITLE
Link in hub site nav not working (when it has sub links)

### ISSUE THREAD

**Issue by MayraJaimes** [SharePoint/sp-dev-docs#3797]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The expected behavior is that when I click on the link in the navigation bar of the hub site that it takes me to the URL I specified. 

#### Observed Behavior

When clicking on the link it does not take me anywhere. It stays on the same page. 

#### Steps to Reproduce

To reproduce this problem add a link and then add sub links under it and when clicking the main link it wont take me anywhere. Having links work and having sub links work but not when there is a link with sublinks.

#### Submission Guidelines
![githubissue](https://user-images.githubusercontent.com/30779784/56222461-b18d4400-6031-11e9-8b40-5575c4f48041.PNG)
![githubissue2](https://user-images.githubusercontent.com/30779784/56222597-f022fe80-6031-11e9-90ac-2efe12eef086.PNG)

**Comment by VesaJuvonen** [comment]
As this is an issue related to out-of-the-box behavior, we cannot provide support for it using this GitHub issue list. Would ask to submit it as an issue through the tenant admin support pages, which would be the right process for any non-dev issues. Sorry for the inconvenience.
