### ISSUE TITLE
SPO column formatting customRowAction regression

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#3798]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the **customRowAction** within SharePoint's column formatting JSON, we should be able to use the conditional syntax in order to build dynamic **actionParams**.

#### Observed Behavior

We were using the **customRowAction** property in order to call a specific Flow based on a particular condition, and everything was working perfectly since a couple of days. We didn't touch anything and suddenly got a JSON parsing error with something as simple as this :

```json
"customRowAction": {
    "action": "executeFlow",
    "actionParams": "=if('test' == 'test', '{\"id\": \"186b77f1-ddd6-4b27-8032-3c10dec67d6c\"}', '{\"id\": \"186b77f1-ddd6-4b27-8032-3c10dec67d6c\"}')"
    }
```

After looking at the javascript error, the error occurs in the file below :

[https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-04-05-sts_20190415.002/splistitemsscope-is-mini-dc133da0.js:formatted](https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-04-05-sts_20190415.002/splistitemsscope-is-mini-dc133da0.js:formatted)

```javascript
t.itemExecuteFlowActionControlHandler = function(e, t) {
    return {
        onClickAction: n.createElement(s, {
            flow: JSON.parse(JSON.parse(t.actionParam)),
            itemKey: t.itemKey,
            noCache: t.noCache
        })
    }
}
```

Precisely, I suspect there was a copy/paste error in that specific line :

```javascript
flow: JSON.parse(JSON.parse(t.actionParam)),
```

JSON.parse() expects a string and returns an object, which means parsing the result of JSON.parse() doesn't make any sens and will end in an error 100% of the time, hence the reason why I think someone might have done a copy/paste error in the code, resulting in the error we have.

#### Steps to Reproduce

Use the following JSON format on an empty text column and see the parsing error when you "Preview" the JSON result :

```
{
	"$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
	"elmType": "span",
	"style": {
		"color": "#0078d7",
		"display": "Block",
		"padding": "8px 0px 0px 0px"
	},
	"children": [{
			"elmType": "span",
			"attributes": {
				"iconName": "Flow"
			}
		}, {
			"elmType": "button",
			"style": {
				"border": "none",
				"background-color": "transparent",
				"color": "#0078d7",
				"cursor": "pointer"
			},
			"txtContent": "Send for approval",
			"customRowAction": {
				"action": "executeFlow",
				"actionParams": "=if('test' == 'test', '{\"id\": \"186b77f1-ddd6-4b27-8032-3c10dec67d6c\"}', '{\"id\": \"186b77f1-ddd6-4b27-8032-3c10dec67d6c\"}')"
			}
		}
	]
}
```

**Comment by thechriskent** [comment]
The issue is the same as reported here: https://github.com/SharePoint/sp-dev-list-formatting/issues/141

Besides the strange double parse issue, the actionParam doesn't appear to have been resolved either. It is still full of AST (operator/operand) syntax rather than having been evaluated to the expected JSON as seen here:
![image](https://user-images.githubusercontent.com/8364109/56247283-44e66980-6072-11e9-8186-88da05565247.png)

**Comment by spplante** [comment]
Yeah same thing here, I figured the AST syntax was intentional though, not sure if that has anything to do with the problem.

Parsing an already parsed object instead of a string surely doesn’t work though, you can test this by trying to parse a simple object instead of a string and you will see it fail with the same kind of message, this line can simply not work.

**Comment by spplante** [comment]
Note that I do not have the problem on another tenant I have, and when debugging the code, it looks like the file [https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-04-05-sts_20190415.002/splistitemsscope-is-mini-dc133da0.js:formatted](https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-04-05-sts_20190415.002/splistitemsscope-is-mini-dc133da0.js) is never called in the stack trace.

**Comment by ldemaris** [comment]
@Niket Jain<mailto:Jain.Niket@microsoft.com> please have your team take a look and file a bug if necessary.

**Comment by shagra-ms** [comment]
The issue has been fixed. Can you check if this works for you?
@spplante

**Comment by shagra-ms** [comment]
This has been fixed. @spplante Please let us know if this is still not working for you.
