### ISSUE TITLE
CreateGroupForSite - Authorization_RequestDenied error when using Azure AD App Only permissions

### ISSUE THREAD

**Issue by lrtoenjes** [SharePoint/sp-dev-docs#3799]
I have my app setup to use Azure AD App Only permissions. I am doing what is described [here](https://docs.microsoft.com/en-us/sharepoint/dev/features/groupify/groupify-csom) regarding the "groupify" process. However, when I call `CreateGroupForSite()`, I get an "Authorization_RequestDenied" error. I believe I have setup the required permissions for my registered app in Azure AD, but perhaps there is one that I missed and someone could point that out? Or perhaps this CSOM endpoint doesn't work with Azure AD App Only permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aeac4f-8228-6a10-4340-01eda05351fe
* Version Independent ID: d55c4044-7b41-a4bb-270c-f3fee0d5ed4e
* Content: [Connect to new Office 365 group - CSOM development](https://docs.microsoft.com/en-us/sharepoint/dev/features/groupify/groupify-csom#feedback)
* Content Source: [docs/features/groupify/groupify-csom.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/groupify/groupify-csom.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by robinmeure** [comment]
Did you use the certificate approach as described here at https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread?

**Comment by lrtoenjes** [comment]
@robinmeure Yes, that is the exact process I used to setup my registered app in Azure AD. I am able to perform certain SharePoint CSOM operations, but when I try to groupify my site, I get the following error:
`{"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"e3ef9598-bd4e-4239-b605-a83ae08027ff","date":"2019-04-16T22:26:41"}}`

**Comment by robinmeure** [comment]
Ah yes, I got the same error as you. Probably same permission issue as calling the other API's like CreateGroupEx and Communicationsite/Create. 
#3771 #3718

**Comment by lrtoenjes** [comment]
I have granted permissions in Azure AD to almost every API permission scope I can think of that could involve creating a O365 Group, but still haven't been able to get it to work. I even went and read through the [Microsoft Graph API permissions](https://docs.microsoft.com/en-us/graph/permissions-reference#group-permissions) and added what I initially had missing (e.g. `User.ReadWrite.All`) but even then I received the same error.

**Comment by MrTantum** [comment]
We can confirm this is not working with application permissions. We added all permission scopes for SharePoint and even the graph permission Sites.FullControl.All but it's still not working.

**Comment by andrewconnell** [comment]
I just commented on another issue with a similar root question. To summarize, not every operation supports app-only and some (as demonstrated in this page) require user interaction/context for auditing. Ref: https://github.com/SharePoint/sp-dev-docs/issues/3718#issuecomment-503622624
