### ISSUE TITLE
Architecture document

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#38]
Please let me know any architecture or how the request is processed on Sharepoint document available

**Comment by manishgarg1** [comment]
Can you please be a bit more specific about which parts you want to learn?

**Comment by bvdinesh** [comment]
Would like to know how following details
1. Architecture life cycle
2. internal process request. Means how client webparts are processed internally
3. What is the role of workbench

Thanks.

**Comment by bvdinesh** [comment]
Any update on this?

**Comment by nickpape-msft** [comment]
For 1 & 2 @manishgarg1 and @chakkaradeep have more insight into this. Are you interested in the lifecycle of the App package on the SP server? Or are you more interested in WebPart lifecycle on a page? Architecturally, when you upload your App Package, the package is dissected similarly to App Parts, and the components (i.e. the WebPart manifest) are stored in a special list. When activating the App on a Site, it flips a feature which enables that specific WebPart. The server-rendered older pages on SharePoint simply read this component list and add it to the list of available WebParts. Then, a special server-side WebPart is uses the manifest information to render the WebPart. Things are a bit different on the newer pages, where we just write the list of manifests directly onto the page. If you are more interested in the lifecycle (e.g. deploy, activate on site, upgrade), @chakkaradeep will be the best person to ask. If you are more interested in the WebPart's lifecycle while running on a page, talk to @manishgarg1.

The role of the workbench is to allow a local testing environment which is decoupled from SharePoint. They are essentially the same code in either place. The Workbench will be improved, as we plan to add features which aid in developing & debugging your WebPart.

**Comment by VesaJuvonen** [comment]
We are covering pretty much all topics in the official documentation at docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview. If there are any specific areas, where improvements would be needed, we absolutely welcome input on those. Since this is a really old issue and the majority of our documentation has been created after it, closing this for now. Like mentioned - if there's anything especially missing, just let us know.
