### ISSUE TITLE
Unable to get EditorId in PnP Search

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [SharePoint/sp-dev-docs#3803]
#### Category
- [ ] Question
- [ ] Typo
- [  ] Bug
- [ ] Additional article idea

Hi,

I was trying to get the "EditorId" of a document in my PnP Search query.
I am actually able to get "ModifiedBy" (User name) but I don't know why for few users the first letter is being removed by Search query (For eg: UserName: **xAnjani Challamcherla** the query is resulting UserName: **Anjani Challamcherla**)
So to get rid of this I am trying to get the EditorId of a document so that from EditorId I can extract name.
My PnP Search query is: 
` await sp.search({
      QueryTemplate: `((SiteID:${siteId} OR SiteID: {${siteId}}) AND (WebId: ${webId} OR WebId: {${webId}})) AND LastModifiedTime < {Today} `,/
      RowLimit: 60,
      RefinementFilters: ["FileType:NOT(aspx)", "FileType:NOT(html)", "FileType:NOT(one)"],
     SelectProperties: [
        "ModifiedBy",
        "Title",
        "Path",
        "LastModifiedTime",
        "ParentLink",
        "FileType",
        "EditorId",
        "AuthorId"
      ],
      
      TrimDuplicates: false,
      SortList: [
        {
          "Property": "LastModifiedTime",
          "Direction": SortDirection.Descending
        }
      ]

    }).then(async (r: any) => {
      console.log(r.PrimarySearchResults);`

Please help
#### Expected or Desired Behavior

The EditorId should be displayed
#### Observed Behavior

EditorId is null

**Comment by andrewconnell** [comment]
By PnP Search, are you referring to the PnPJS library? I think so by looking at the code... if so, please post your issue to the appropriate issue list: https://github.com/pnp/pnpjs

If I'm incorrect, please follow up with additional details on what you're using so we can reopen and triage as appropriate.

**Comment by AnjaniChallamcherla** [comment]
Ohh okay Andrew 
Sorry for raising my issue here.
Apologies for any inconvenience caused.

**Comment by andrewconnell** [comment]
No inconvenience... wish there was a better way to direct folks before creating issues... until that day, we just do this :)
