### ISSUE TITLE
Overwrite attribute is not working while provisioning the custom list definition from SPFx solution

### ISSUE THREAD

**Issue by akt2006** [SharePoint/sp-dev-docs#3805]
The Overwrite attribute is not supported when provisioning the custom list definition in the form of elements.xml from SharePoint Framework client site solution.

Here is the example.

 <Field ID="{DBD71E4F-C995-4CF2-B72E-49D65076A32D}"
           Name="NavOrder"
           DisplayName="Nav Order"
           Type="Number"
           Indexed="TRUE"
           Required="TRUE"
           Overwrite="TRUE"
           Group="NavBar Columns" />

**Comment by patmill** [comment]
@akt2006 - It looks like your sample wasn't included.

**Comment by akt2006** [comment]
Sorry for that here is the sample code where I am trying to add **Overwrite="TRUE"**
 <Field ID="{DBD71E4F-C995-4CF2-B72E-49D65076A32D}"
           Name="NavOrder"
           DisplayName="Nav Order"
           Type="Number"
           Indexed="TRUE"
           Required="TRUE"
           Overwrite="TRUE"
           Group="NavBar Columns" />
