### ISSUE TITLE
this.context.pageContext.web.absoluteUrl not taking current web URL

### ISSUE THREAD

**Issue by KaushalKhamar** [SharePoint/sp-dev-docs#3807]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I am using list picker control in SPFx webpart. I need to get lists from sub site in webpart. When i put web part in page i am getting error and when i troubleshoot this issue i have found that current web url is wrong.

**this.context.pageContext.web.absoluteUrl** not taking current web's URL. 

Instead taking current web url (_https://kaushalkhamar.sharepoint.com/sites/mysite_) it is taking App web url i.e. (_"https://kaushalkhamar-app0c7ded7ed12d49eab97d77a8fcbc5820.sharepoint.com/sites/mysite"_)

Is i am doing anything wrong? The same thing is working with 1.7 version but in version 1.8 it is not working.

**Comment by patmill** [comment]
Is this webpart using the new isolated domain functionality?

**Comment by KaushalKhamar** [comment]
Hello,

Yes i have used isolated domain functionality in this webpart. 

I got to know that whenever we are using this functionality, webpart will have his own context rather then site context on which webpart is added.

Thank you @patmill for help and pointing out me that i have used isolated domain functionality.
