### ISSUE TITLE
Custom Webparts not working on mobile app 

### ISSUE THREAD

**Issue by MayraJaimes** [SharePoint/sp-dev-docs#3810]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The expected behavior is that the custom webparts that I create get displayed on the mobile SharePoint app. It is currently only being displayed on mobile if using a browser.

This is the expected behavior for the SharePoint app:
![expectedbehavior](https://user-images.githubusercontent.com/30779784/56394078-cf0e0980-61fb-11e9-8714-953fc6348794.jpg)

#### Observed Behavior

When using the SharePoint App the custom webparts are not displaying the information. It is only displaying if I go to the SharePoint site through the browser but not the SharePoint app.  I am attaching the picture of one of the webparts that is not displaying correctly even though its other custom webparts that are also not working. The custom webpart is using Microsoft graph to get the staff's images, birthdays, and anniversaries. 

This is the observed behavior on the SharePoint app:
![current behavior](https://user-images.githubusercontent.com/30779784/56393972-86eee700-61fb-11e9-9010-1a8fc0397fcb.jpg)

#### Steps to Reproduce

Add a custom webpart to a page and go to the SharePoint mobile app.

**Comment by patmill** [comment]
Hi @MayraJaimes - Where does the data come from?  Are you making a graph call?

**Comment by MayraJaimes** [comment]
@patmill yes the data is coming from a graph call.

**Comment by patmill** [comment]
OK - the problem is that getting a graph token from the mobile app is currently not working (from a mobile browser it is fine).  We are very close to releasing code to the service that will address this.  No change will be required from your code.

**Comment by MayraJaimes** [comment]
Thank you so much for that information. Very helpful!
