### ISSUE TITLE
Various issues with SPFx apps and the new SharePoint online release

### ISSUE THREAD

**Issue by florianwachter** [SharePoint/sp-dev-docs#3812]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Icons showing up in SPFx command sets, field customizer rendering correctly, grouped views containing columns with field customizer not throwing exceptions and an updated context when navigating between lists.

#### Observed Behavior

In the last two to three weeks I noticed the following issues with one of our SPFx apps. All issues are related to an update that Microsoft rolled out recently (or they are still in the process of rolling this out). The reason for this assumption is that we only see this issue since the new sticky headers feature and totals in list views are available. When I first noticed this behavior I checked our tenant's release preferences and noticed that 'target release' was configured. After changing this to standard release everything was working as expected again. About a week or so later we noticed the issues again and also Sticky headers and totals came back. At the moment I think the update has been retracted again. Everything is back to normal at the moment in my tenant and I also don't see totals in views and no sticky headers. So maybe Microsoft already stopped the release of the new version and maybe they are already fixing this. I also talked to an Office 365 Escalation Engineer from Microsoft Support about this issue, but they don't have any insight on this. Since I'm not sure if Microsoft is already working on this or if they continue releasing the new version I decided to share my experience here.

Back to the actual issues, this is what's happening: 

**- Icons are not showing up in SPFx command sets:** This issue has already been reported: https://github.com/SharePoint/sp-dev-docs/issues/3692

**- We loose all the customizations a few seconds after the view renders:** SPFx field customizer show up correctly, but the customizations disappear a few seconds later. This is only the case if the items in the list exceed the configured row limit of the view. If you open a modern SharePoint view the first batch of items will be rendered and this also calls the field customizer so that the column you want to customize changes depending on your implementation. After a few seconds, the view renders the next batch of items. That's when we loose all the customizations. If I change the row limit of the view to a higher value than items in the list, everything seems to work as expected again.

**- Grouped views that are collapsed by default and contain a column with a field customizer throw the following exception as soon as we expand a group.**

![error_in_grouped_view](https://user-images.githubusercontent.com/5690610/56415594-6e7bdc80-628e-11e9-8295-8f389ca2d11d.png)

**- The page context will not be updated between different lists in field customizes, command sets and application customizer.** The current list properties like serverRelativeUrl, Title, etc. that we can access using this.context.pageContext.list don't change if you navigate from one list to another. The context will always be the list from the last full page load.

#### Steps to Reproduce
As already mentioned above, it depends on the SharePoint version if you are able to reproduce the issues or not. To sum it up, if you see sticky headers or totals in modern list views, you should be able to reproduce it. 

**Icons not showing up in SPFx command sets:**

Create a new SPFx project and select the extension 'Command Set'. Basically follow this guide: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api
Configure the full address to an icon in the iconImageUrl property in the *.manifest.json and test the app. Icons will not show up.

**Field Customizer Issue:**

Create a new SPFx project and select the extension 'Field Customizer'. Basically follow this guide: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

If the list has more items than the row limit configured in your view and you test the extension you should have the same behavior. The field customizer rendering correct first and then disappear a few seconds later. If you use 'gulp serve' it's possible that everything is still working as expected because of the delay so that the field customizer will render after the view rendered all items in the list. If you deploy the app instead of the debug mode you should be able to reproduce it.
Also create a collapsed grouped view that contains a column with a field customizer, expand a group and you should see the exception from the screenshot above.

**The page context will not be updated between different lists**
Create a SPFx project with a commandSet or application customizer and log this.context.pageContext.list.serverRelativeUrl to the browser console and check the output if you navigate between lists.

Thanks in advance for any tips or insights !

**Comment by patmill** [comment]
Thanks for the details.  We'll get this looked at.

**Comment by patmill** [comment]
Thanks again @florianwachter .  The team has the issues local fixed and they will roll out soon.  You won't need to rebuild or redeploy or anything like that, so "fixed-next-drop" doesn't mean SPFx 1.8.2 or 1.9.

**Comment by rchendev** [comment]
Yes we'll roll out the new bits with the flight to FR tenants and users early next week. Let us know if you still have issues wit this. Thanks for reporting this.

**Comment by florianwachter** [comment]
Looks like the fix has already been rolled out. Everything works as expected now. I can see totals and sticky headers again and our extensions also seem to work. Thanks to @patmill and @rchendev for your prompt action.

**Comment by VesaJuvonen** [comment]
Closing this issue as @florianwachter confirmed that everything is fine now.
