### ISSUE TITLE
Add note about enabling "Custom Scripts" for the site

### ISSUE THREAD

**Issue by stijnbrouwers** [SharePoint/sp-dev-docs#3813]
It would be useful to have a note on the page to remind users to enable "Custom Scripts" for the site they are developing for...
If it's not enabled, you will be able to retrieve data with JSOM, but updating operations will fail.

We had this issue when trying to update a propery bag value for the web. The REST-API does not support it (still missing...!) so we were forced to revert to JSOM. We were constantly getting errors on update operations because custom scripts was not enabled. We were thrown of a little because get-operation still worked.

See following link for enabling Custom Scripts: https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#to-allow-custom-script-on-other-sharepoint-sites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3762e11e-4284-069c-ed5d-d4695a5100b7
* Version Independent ID: 42b56024-f9c6-2e76-2fc1-acd84f9440b2
* Content: [Connect to SharePoint using the JavaScript Object Model (JSOM)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom#feedback)
* Content Source: [docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
This is generally a "Bad Idea".  You really don't want to enable custom scripts on your site.  What you are seeing isn't an issue with general "JSOM can't update a side", but rather that updating the property bag of a web is blocked if scripting is disabled.  I would suggest open up a user voice request saying "we need a portion of the web property bag that we can update when scripting is disabled".

**Comment by PopWarner** [comment]
There was talk about this some time ago with @VesaJuvonen on twitter...which led to the creation of a UserVoice that is similar to this need.
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/36785302-spfx-key-value-pair-properties-that-support-read-w

It's not exactly for the Property Bag, but it's similar and wanted to share at least. :)

**Comment by patmill** [comment]
Great - that's the one.  @stijnbrouwers - add your vote to that user voice.  I'm resolving this with 'wont fix' not because we aren't considering the user voice, but because we are not going to update the docs to say "enable scripting".
