### ISSUE TITLE
not working, there is "library" option

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#3816]
this step "Select Library as the client-side component type to be created." not working, there is "library" option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac926949-7ab3-3a40-14e8-3b5b032803c1
* Version Independent ID: d3ae1d27-3976-64ac-fda6-5ca18a25dbd0
* Content: [Building solutions with the library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial)
* Content Source: [docs/spfx/library-component-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by luismanez** [comment]
This is still a preview feature, so ensure yo create your project with:
```
yo @microsoft/sharepoint --plusbeta
```
I´ve tried with spfx 1.8.1 and the Library option is only available when using the _plusbeta_ option
