### ISSUE TITLE
webpart is not available in page.Available Client Side Components();

### ISSUE THREAD

**Issue by anandasanyal** [SharePoint/sp-dev-docs#3817]
#### Category
- [ ] Additional article idea
webpart is not available in page.Available Client Side Components();
I'm provisioning SharePoint Modern site using CSOM.
I've uploaded a SPFX app in App Gallery, which I'm trying to add in my new provisioned page.  
#### My code
var components = page.AvailableClientSideComponents();
                //string wpName = "project-status-client-side-solution";
                string wpName = "7fd19df0-1ec9-4fe8-9c7e-7812e5ef583a";

                // Find our custom "project-status-client-side-solution" web part
                List<string> componentsnames = components.Select(k => k.Name).ToList();
                var webPartToAdd = components.Where(wp => wp.ComponentType == 1 && wp.Name == wpName).FirstOrDefault();
                if (webPartToAdd != null)
                {
                    ClientSideWebPart clientWp = new ClientSideWebPart(webPartToAdd) { Order = -1 };
                    page.AddControl(clientWp);
                }
                page.Save();

webPartToAdd is always returning null. checked with Name, Id both.

#### Observed Behavior
Using below code, I can see that app, in my tenant.
 var apps = appManager.GetAvailable();

Once the new site is created, I can see the app - Add an App > [Apps you can add] section. 
I've to add manually, to get the app available in web part gallery.
I don't want to do this manually. How can I perform this using code.
Am I missing something here.

Any help on this is really appreciated.
Thank you
ananda

**Comment by mcmynn83** [comment]
You need to ensure that when you add the app in your app catalog that it is tenant deployed.
