### ISSUE TITLE
DynamicDataSharedDepth undefined in hosted workbench (SPFx 1.8.1)

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#3820]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When running an SPFx 1.8.1 solution that uses Dynamic Data with 'gulp serve', I expect it to work correctly in the local workbench, the hosted workbench and SharePoint pages.

#### Observed Behavior
Running the solution works without an issue in the local workbench and SharePoint pages, but in the hosted workbench it throws the following exception: "Cannot read property 'Source' of undefined". Issues occurs with `DynamicDataSharedDepth.Source`

![HostedWorkbench181](https://user-images.githubusercontent.com/9973962/56499169-7abd9f00-6505-11e9-88a5-2ebf597953f1.png)

The error doesn't occur when using SPFx 1.7.1. It starts occurring when I upgraded the solution to 1.8.1 with the guidance from the Office 365 CLI and only when opening the Property Pane.
Also occurs in a newly created solution. Tested on 3 different tenants, with Google Chrome.

#### Steps to Reproduce
- Create new SPFx 1.8.1 solution, keep defaults and I based it on React
- Put the following code in the existing groupFields array of the property pane (update the imports):
```
PropertyPaneDynamicFieldSet({
                  label: "Keywords",

                  fields: [
                      PropertyPaneDynamicField('queryKeywords', {
                          label: "Keywords"
                      })
                  ],
                  sharedConfiguration: {
                      depth: DynamicDataSharedDepth.Source,
                  },
                })
```
- Run gulp serve.
- Open the property pane of the webpart. In the local workbench, it works. In the hosted workbench, you will find the following error in the developer console:
```
Uncaught (in promise) TypeError: Cannot read property 'Source' of undefined
    at HelloWorldWebPart.getPropertyPaneConfiguration (HelloWorldWebPart.ts:65)
    at sp-webpart-workbench-assembly_en-us_adc4bc24c9e68c9e1b136ddf960e5a9d.js:605
```

**Comment by patmill** [comment]
Just to clarify.  The local workbench is the one served from localhost, the hosted workbench is the one in SPO.  Is it the local workbench that is failing?

**Comment by YannickRe** [comment]
@patmill no, it is the hosted one that fails. The local one AND the SharePoint pages work without issues.

**Comment by patmill** [comment]
So that's certainly strange.  DynamicDataSharedDepth is undefined?  That's an enum...  What package are you importing it from?  Can you make sure that it is sp-property-pane?

**Comment by YannickRe** [comment]
I tried both the old one (SP-webpart-base) and the new one (SP-property-pane), both resulting in the same behavior locally and hosted.

**Comment by patmill** [comment]
I'm having trouble repro'ing this.   Here's what my quick repro code looks like:

```
import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart, IWebPartPropertiesMetadata } from '@microsoft/sp-webpart-base';
import {
  IPropertyPaneConfiguration,
  PropertyPaneDynamicField,
  PropertyPaneDynamicFieldSet,
  DynamicDataSharedDepth
} from '@microsoft/sp-property-pane';
import { escape } from '@microsoft/sp-lodash-subset';
import styles from './HelloWorldWebPart.module.scss';
import * as strings from 'HelloWorldWebPartStrings';
import { DynamicProperty } from '@microsoft/sp-component-base';

export interface IHelloWorldWebPartProps {
  description: string;
  name: DynamicProperty<string>;
  email: DynamicProperty<string>;
}

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {

  protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      // Specify the web part properties data type to allow the address
      // information to be serialized by the SharePoint Framework.
      'name': {
        dynamicPropertyType: 'string'
      },
      'email': {
        dynamicPropertyType: 'string'
      }
    };
  }

  public render(): void {
    this.domElement.innerHTML = `
      <div class="${ styles.helloWorld}">
        <div class="${ styles.container}">
          <div class="${ styles.row}">
            <div class="${ styles.column}">
              <span class="${ styles.title}">Welcome to SharePoint!</span>
              <p class="${ styles.subTitle}">Customize SharePoint experiences using Web Parts.</p>
              <p class="${ styles.description}">${escape(this.properties.name.tryGetValue())}</p>
              <a href="https://aka.ms/spfx" class="${ styles.button}">
                <span class="${ styles.label}">Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>`;
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          groups: [
            {
              groupFields: [
                PropertyPaneDynamicFieldSet({
                  label: 'Select person source',
                  fields: [
                    PropertyPaneDynamicField('name', {
                      label: 'Name text'
                    }),
                    PropertyPaneDynamicField('email', {
                      label: 'Email text'
                    })
                  ],
                  sharedConfiguration: {
                    depth: DynamicDataSharedDepth.Property
                  },
                })
              ]
            }
          ]
        }
      ]
    };
  }
}
```

**Comment by patmill** [comment]
One other thing - looking at the "compiled" js from 1.8.0, it winds up being a explicit #, not even an object reference.  Let me try with 1.8.1...

**Comment by patmill** [comment]
OK - figured it out.  A seemingly innocuous change.  We will work on getting a proper fix rolled out, and you won't need to modify your code.  In the meantime, if you want to work around this, use a hard coded value (0,1,2) rather than the enum.

**Comment by YannickRe** [comment]
Thank you for figuring it out! I’ll wait for the fix to roll out, it isn’t that pressing.

**Comment by YannickRe** [comment]
This is fixed in my environments, so I'm closing this!
