### ISSUE TITLE
gulp trust-dev-cert on WSL

### ISSUE THREAD

**Issue by kasuken** [SharePoint/sp-dev-docs#3822]
#### Category
- [x ] Question
- [ ]   Typo
- [x ]  Bug
- [ ]    Additional article idea

#### Expected or Desired Behavior

I try to lunch "gulp trust-dev-cert" from Windows Subsystem Linux but it doesn't work.
The command runs correctly but nothing happens.

#### Steps to Reproduce

I have the correct setup for SPFx dev environment according with the documentation.

**Comment by andrewconnell** [comment]
Can you elaborate on *"nothing happens"*? Does nothing happen when you run it, or does it run but the cert isn't trusted when you load the local workbench in the browser?

If the latter, have you seen #2758? There's an obscure folder that might impact it...

**Comment by kasuken** [comment]
I don't have that folder on my root directory.
When I run the command, the command has no error but the certificate is not valid.
I am using node 8.16 at the moment.

**Comment by andrewconnell** [comment]
Doesn't the Linux subsystem in Windows effectively run under a VM? If so, then that would make sense... the linux VM trusts the cert, but if you're hitting it from your host Windows 10 machine doesn't because it doesn't have the cert in its trusted root authority...

**Comment by kasuken** [comment]
I have the same issue on my machine with Windows 10.

**Comment by andrewconnell** [comment]
So... this isn't exclusive to SPFx or the SPFx tooling... it's what you're trying to do. Seems the ASPNETCore stuff has the same challenge with WSL: https://github.com/aspnet/AspNetCore.Docs/issues/7166

**Comment by andrewconnell** [comment]
@kasuken said:
> I have the same issue on my machine with Windows 10.

So... excluding WSL from the scenario and running native on Windows 10? There is a long list of closed issues related to this with various solutions and things to investigate... have you reviewed the closed issues to see if something might help in that case?

https://github.com/SharePoint/sp-dev-docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+trust-dev-cert
