### ISSUE TITLE
SingleWebPartAppPage Remove CommandBar (Edit button)

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#3824]
#### Category
- [x] Question
- [ ] Additional article idea
- [ ] Typo
- [ ] Bug

#### Expected or Desired Behavior
The app page component (SingleWebPartAppPage) should allow us peasants to take over the entire page (i.e., everything inside the SharePoint chrome). There should be no SharePoint controls sharing space with our SPA that we can't control (i.e., hide or modify).

#### Observed Behavior
The SPA component became GA in SPFx 1.8. Once a page was turned into a 'SingleWebPartAppPage', the webpart content would be the only thing visible in the SharePoint chrome. Any changes to the page or webpart would necessitate changing the page type back to Article. A few weeks later, my SPA has a command bar component above it with an Edit button that brings up my webpart's property pane. There is no mention on how to remove this command bar in the documentation below.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages
My webpart already has a command bar on top of it

So at the time 1.8 was released, these were our options for SPAs in SharePoint (I consider the Office 365 navbar separate to SharePoint so do not expect SPFx or SP in general to let me do anything to it).

> Problem 1: Webparts share Site Page controls (banner, command bar, etc...)
> Solution: Use the new App Page SPFx feature by including "SharePointFullPage" in the supportedHosts webpart manifest property and change the site page type to SingleWebPartAppPage
> 
> Problem 2: Webparts share screen space with the Quick Navigation
> Solution: Disable Quick Luanch in Site Settings (unfortunately, that can't be targeted to a particular Site Page and affects the rest of the SPWeb)
> 
> Problem 3: Webpart width and horizontal padding is controlled by SharePoint
> Solution:  Set webpart manifest property supportsFullBleed to true and place webpart inside a Full-width column page layout section.

So as of day 0 of 1.8, we had full control of the SharePoint "page".

A few weeks after the 1.8 release, we have a **new** problem

> Problem 4: Single page webpart shares space with a command bar and button that opens said webpart's property pane.
> Solution: no known supported solution to either place own buttons in the command bar or hide command bar completely
> Workaround: Give page users read only rights to the page and the command bar will be hidden. This increases the administration complexity of the solution and reduces its flexibility. Furthermore, this functionality is not explicitly documented and is liable to change (i.e., the permission-level targeting of who sees the Edit button may be altered in a future update which would affect my solution).

#### Steps to Reproduce
Follow office guide to deploy a webpart as an SPA
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

Once deployed, observe Command Bar with a single farItem 'Edit' PrimaryButton.

**Comment by VesaJuvonen** [comment]
Actually, your "Expected Behavior" is incorrect as current experience is by design by leasing the header control on the page. There's currently no support for hiding the SharePoint header from the pages due to a design decision done in engineering/design team.

If you'd like to change this, you can vote on following UserVoice entry - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33933100-when-creating-an-spfx-extension-for-a-custom-heade
