### ISSUE TITLE
The keyCredentials snippet can be omitted with the new App registration portal page

### ISSUE THREAD

**Issue by o-utofbounds** [SharePoint/sp-dev-docs#3825]
The keycredentials step is not necessary anymore, hoewever you have to upload your .cer file to the Certificates & Secrets section of the app registration, this automatically updates the manifest
The new App registration page is currently in preview and planned for GA release in may 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jansenbe** [comment]
This was implemented, closing this issue
