### ISSUE TITLE
Example of date.

### ISSUE THREAD

**Issue by MichaelMc64** [SharePoint/sp-dev-docs#3827]
One example of how to construct a query based on date would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d931357-f63f-1f3d-5e2f-90d32c5d3818
* Version Independent ID: f95bfa79-cd41-208d-9d2d-6d2724f605ae
* Content: [Keyword Query Language (KQL) syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference)
* Content Source: [docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/keyword-query-language-kql-syntax-reference.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@wobba ?

**Comment by wobba** [comment]
`LastModifiedDate:2019-04-24`

See KQL samples at https://www.techmikael.com/2014/03/s15e01-kql-basics.html :-)
