### ISSUE TITLE
SingleWebPartAppPage Remove CommandBar (Edit button)

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#3828]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The app page component (SingleWebPartAppPage) should allow us peasants to take over the entire Site Page. The command bar component that allows contributors to change the webpart's properties should be configurable since the webpart author should have control over who or if the "app" can be configured. This behavior was observed at the time the App Page was released in March (i.e., no command bar)

#### Observed Behavior
The SPA component became GA in SPFx 1.8. Once a page was turned into a 'SingleWebPartAppPage', the webpart content would be the only thing visible in the SharePoint chrome. Any changes to the page or webpart would necessitate changing the page type back to Article. A few weeks later, my SPA has a command bar component above it with an Edit button that brings up my webpart's property pane. There is no mention on how to remove this command bar in the documentation below.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages
My webpart already has a command bar on top of it

So at the time 1.8 was released, these were our options for SPAs in SharePoint (I consider the Office 365 navbar separate to SharePoint so do not expect SPFx or SP in general to let me do anything to it).

> Problem 1: Webparts share Site Page controls (banner, command bar, etc...)
> Solution: Use the new App Page SPFx feature by including "SharePointFullPage" in the supportedHosts webpart manifest property and change the site page type to SingleWebPartAppPage
> 
> Problem 2: Webparts share screen space with the Quick Navigation
> Solution: Disable Quick Luanch in Site Settings (unfortunately, that can't be targeted to a particular Site Page and affects the rest of the SPWeb)
> 
> Problem 3: Webpart width and horizontal padding is controlled by SharePoint
> Solution: Set webpart manifest property supportsFullBleed to true and place webpart inside a Full-width column page layout section.

So as of day 0 of 1.8, we had full control of the SharePoint "page".

A few weeks after the 1.8 release, we have a new problem

> Problem 4: Single page webpart shares space with a command bar and button that opens said webpart's property pane.
![Command bar on top of App Page](https://i.imgur.com/3V35YyM.png)
> Solution: no known supported solution to either place own buttons in the command bar or hide command bar completely
> Workaround: Give page users read only rights to the page and the command bar will be hidden. This increases the administration complexity of the solution and reduces its flexibility. Furthermore, this functionality is not explicitly documented and is liable to change (i.e., the permission-level targeting of who sees the Edit button may be altered in a future update which would affect my solution).

#### Steps to Reproduce
Follow office guide to deploy a webpart as an SPA
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

Once deployed, observe Command Bar with a single farItem 'Edit' PrimaryButton.

**Comment by mcmynn83** [comment]
@semopz - Thank you for the feedback.  Unfortunately the design of the feature changed slightly.  All users who have edit permissions will always see the edit bar.  This is to keep the page consistent with the rest of our experience.  All users who only have view permissions will not see the edit bar.  There is not a currently supported way or removing this bar.  If enough people are interested in the feature we could provide something.  Please leave an ask in uservoice for this feature if you feel strongly about it.
