### ISSUE TITLE
SPHttpClientBatch missing in Build 1.8.1

### ISSUE THREAD

**Issue by Billbrockbank** [SharePoint/sp-dev-docs#3829]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

In build 1.8.0 SPHttpClientBatch was in the release version, but it is missing in the 1.8.1 release version.
 
#### Expected or Desired Behavior

I get a missing reference to SPHttpClientBatch.

#### Observed Behavior

I can not build the upgraded project, had to roll back to 1.8.0.

#### Steps to Reproduce

Add: 
Import { SPHttpClientBatch } from "@microsoft/sp-http";

**Comment by andrewconnell** [comment]
@patmill ... similar to regression in #3820 & #3826?

**Comment by patmill** [comment]
The batch is (still) in beta.  Did you use the plusbeta flag?

There was an issue with the 1.8.0 build where ALL the APIs wound up in the typings.  We fixed that in 1.8.1 (although missed the microsoftTeams property).

**Comment by Billbrockbank** [comment]
With build 1.8.0 I did not use the plusbeta flag.

So as I understand SPHttpClientBatch is still only only in beta.

**Comment by andrewconnell** [comment]
That's correct... according to what @patmill said above, the beta flag requirement was incorrectly removed in 1.8.0 for batch but added back in 1.8.1.
