### ISSUE TITLE
Logging is broken (RC0)

### ISSUE THREAD

**Issue by michel-weber** [SharePoint/sp-dev-docs#383]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
If i use the Log class from @microsoft/sp-core-library, and log a message in my WebPart, I should see my log output in the console.

#### Observed Behavior
There are log-messages written to the output - but my supplied message is not shown - and no context information is added. Only the word "message" appears. The source is appearing correctly.

| nr of times | console output | source |
|---|---|---|
| 1 | onInit(): message | DefaultLogHandler.js:9 |
| 6 | onInit(): WARNING message | DefaultLogHandler.js:12 |

If i drill it down to the DefaultLogHandler (`node_modules/@microsoft/sp-core-library/lib/log/DefaultLogHandler.js`) - the error is very easily visible:
```javascript
"use strict";
var DefaultLogHandler = (function () {
    function DefaultLogHandler() {
    }
    DefaultLogHandler.prototype.verbose = function (source, message, scope) {
        console.log(source + ": VERBOSE message");
    };
    DefaultLogHandler.prototype.info = function (source, message, scope) {
        console.info(source + ": message");
    };
    DefaultLogHandler.prototype.warn = function (source, message, scope) {
        console.warn(source + ": WARNING message");
    };
    DefaultLogHandler.prototype.error = function (source, error, scope) {
        console.error(source + ": ERROR: " + error.message);
    };
    return DefaultLogHandler;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = DefaultLogHandler;
```
As you can see, info, warn and error are broken. And the scope is ignored.

#### Steps to Reproduce
1) Create a new WebPart: `yo @microsoft/sharepoint`
2) Add line in *WebPart.ts:  
`import { Log } from '@microsoft/sp-core-library';`  
3) Add a log statement with your own message (info, warn, error):  
`Log.info("render()", "This is a log-message from the render method", this.context.serviceScope");`

#### Thoughts
1) Could it be that the logging has changed and we should not just use the "Log" class directly?
The documentation is not updated at the moment (still drop-6):  
https://github.com/SharePoint/sp-dev-docs/wiki/Working-with-the-Logging-API.

But if it's a confirmed bug - please fix it. Otherwise everybody is resorting to console.log.

**Comment by patmill** [comment]
Yup - that's a bug.  Thanks @michel-weber

**Comment by patmill** [comment]
This is fixed in GA.  Thanks.
