### ISSUE TITLE
Does not work in Microsoft Teams desktop app (SharePoint page added as a tab)

### ISSUE THREAD

**Issue by Languafe** [SharePoint/sp-dev-docs#3831]
The web part works as expected when added to a regular SharePoint page and viewed in the browser or the SharePoint app (I've tried on iPhone). However, I was REALLY hoping I could simply add the SharePoint page as a tab in Microsoft Teams, but it does not work when using the desktop version of Microsoft Teams (under Windows 10). It does work when using the teams web app at teams.microsoft.com.

I have used this technique for other simpler web parts with great success, which leads me to believe the issue has to do with accessing MS Graph.

I do not know how I can troubleshoot the rendered page inside the teams client. Any assistance would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#feedback)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Maybe this is a limitation of the Windows 10 MSFT Teams client at this time? 

I've had no problem adding a custom tab in Teams using an SPFx web part as the custom tab... I've been able to access MS Graph in an SPFx web part running in SPO & Teams (web, iOS & MacOS clients)... in fact, recently demonstrated this at a recent PNP meeting...

**Comment by Languafe** [comment]
Yes sorry. When I invoke the search, the spinner is displayed and nothing happens. The same web part works as expected when viewed in a browser, rendering a table with user information in that Fabric component I don't remember the name of. I don't currently have access to my work in order to confirm versions, although I am quite certain I had spfx 1.7.x for this

**Comment by andrewconnell** [comment]
@Languafe said:
> When I invoke the search, the spinner is displayed and nothing happens

Are you rendering a page or a web part in the Teams tab? If that's the SP page search control, I can't speak to that or if it would even work within an IFRAME (which is how tabs are loaded in Teams).

If you're talking about something in the web part, we need more details on what's going on (or not going on) like errors, response from Graph, etc... there's not much to go off of based on the avail information provided.

**Comment by Languafe** [comment]
I understand, and sorry for the poor description. I have added a SharePoint page as a "website" tab in teams. This SharePoint page has a single web part added, which is the one that the relevant tutorial results in. This web part solution  is deployed only to the single tenant app catalog and added to the SharePoint site where this page is. I am logged in as a site owner of said site. Also one of the issues I mentioned originally is that I don't know how to troubleshoot the rendering of a page inside a teams tab. In a browser I am used to the developer tools but Teams has no such thing (right?) Also the web part works as expected when the page is viewed right in SharePoint and in the SharePoint iPhone app.

**Comment by andrewconnell** [comment]
@Languafe said:
>  In a browser I am used to the developer tools but Teams has no such thing

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-tools

@Languafe said:
> I have added a SharePoint page as a "website" tab in teams.

Is there a reason for the whole page to be a tab? Seems excessive in a tab when you can now just have a web part be a tab: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

**Comment by Languafe** [comment]
Thank you for the link to teams dev tools. I feel stupid having actually mentioned it without searching for its existence.

As for the page. No particular reason, other than it not requiring additional work. I have several other "solutions", custom forms and the like distributed as SharePoint pages already and the option to simply add those as tabs in teams is very convenient.

I wouldn't really expect this scenario to simply work as its not promised in the tutorial or otherwise, but I asked for assistance and you've already given me plenty. Thank you!

I will attempt using the teams devtools when able.
