### ISSUE TITLE
SharePointFullPage hide from New<Pages<Apps

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#3832]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Question:

**Is it possible to deploy a SPFX WebPart as "SharePointFullPage" without making it available to the user in the "**New<Pages<Apps**"-dialogue?**

We often have use cases where we would like to deploy system pages similiar to application pages from Sharepoint OnPremise (_layouts). These pages should not be changed by users.

Currently we have to check for url parameters (e.g. ?applicationPage=UserEditor) and "hack" the dom of existing pages to show the system page.

The "**SharePointFullPage**" model would be a fantastic method to avoid these hacks. We then could just add links to the different application pages using _**_layouts/15/appPageHost.aspx?componentId=yourComponentGuidHere**_ and set **canUpdateConfiguration** property to false.

The problem here is that users should not be able to create these system pages manually.

**Comment by andrewconnell** [comment]
I don't think you can hide it from that dialog if you set the `supportedHosts` to `SharePointFullPage`... but what you could do is follow the steps in the docs to just add the web part to a page, then use the REST API (or POSH or O365 CLI) to convert the page layout to the one that is used as a full page.

I think this would give you the same net result + not making it available in the Apps dialog.

But you'd have to try it out... haven't confirmed this...

**Comment by MrTantum** [comment]
So in this case we would not set anything in `supportedHosts ` at all and therefore the WebPart would not be visible in any of the areas (Page, Teams, App dialog)?

**Comment by andrewconnell** [comment]
I'd think at minimum you'd need to make it a web part to get it to show up in the toolbox to get it added to a page.

if that doesn't work for you, I don't think your scenario is possible at this time... would make for a good uservoice feature request at https://aka.ms/sp-dev-uservoice

**Comment by patmill** [comment]
If you don't want it to appear in any picker experience, then you'll want to have the supportedHosts entry, but have it be empty.  You can still use the control if you configure it through the API, or by using the _layouts/15/apppagehost.aspx?componentid=asdfasdfasdf URL.

Does that solve your problem?

**Comment by MrTantum** [comment]
Yes this sounds perfect. We will try this. 

Thank you guys!
