### ISSUE TITLE
Again issues with ListviewCommandSet Extensions in targeted release

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#3837]
#### Category
- [x] Bug

#### Expected or Desired Behavior
A command in a commandset extension should only be shown once in the command bar.

#### Observed Behavior
All commands are shown twice in the command bar. This only happens in targeted release. If the tenant is switched back to standard release the commandsets are behaving as expected.

#### Steps to Reproduce
Create a ListViewCommandSet extension which shows the commands in the command bar and deploy it to a tenant set to targeted release. All contained commands will be shown twice.
Could be somehow related to issue #3703 because we have seen this behaviour there too.
I can't see any error message related to this in the debugging console.

**Comment by KoenZomers** [comment]
Linking to this post where someone is reporting the same behavior: https://github.com/SharePoint/sp-dev-docs/issues/3703#issuecomment-484111388

**Comment by patmill** [comment]
OK, spent a bunch of time trying to repro these issues.  I couldn't get anything to duplicate this.  It's possible it's a bug, but it's more likely that you've got a couple of registrations.

1 - Bring up the developer tools, hit f-5, and then look for a call in the network tab to CustomActionElements
2 - Grab the response, format it (https://www.bing.com/search?q=json+formatter ftw), and check and see if your solution is appearing more than once.

**Comment by cwdata** [comment]
Thank you @patmill for taking your time.
I switched our tenant back to targeted release and after that all extensions are now again shown twice.
Checking the call to 'CustomActionElements' reveals that the extensions appear two times in the json response.
What exactly do you mean by "a couple of registrations"? And why is it working when we switch to standard release without changing anything else?

**Comment by cwdata** [comment]
Addition:
Looking at all the lists there is one custom extension that only shows up once. The most obvious difference between its solution and the ones that are shown twice is that the correctly working solution only contains one extension while the others contain two.

**Comment by ahackettms** [comment]
Hello @cwdata 
Could you provide the results of the network call to CustomActionElements? for the case when the extension shows twice. 
Or you can provide fiddler track or network HAR file. 
Thanks

**Comment by cwdata** [comment]
@ahackettms 
Call:
`:path: /sites/busapps2/_api/web/GetList(@a1)/CustomActionElements?@a1=%27%2Fsites%2Fbusapps2%2FLists%2FsnsAbsences%27`
Query String Parameters:
`@a1: '/sites/busapps2/Lists/snsAbsences'`
Response:
`{"d":{"CustomActionElements":{"__metadata":{"type":"SP.CustomActionElementCollection"},"Items":{"__metadata":{"type":"Collection(SP.CustomActionElement)"},"results":[{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"vwaViewAsWebAccessFromEcb","EnabledScript":null,"ImageUrl":null,"Location":"EditControlBlock","RegistrationId":"vdw","RegistrationType":4,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Webbrowser anzeigen","UrlAction":"~site/_layouts/15/VisioWebAccess/VisioWebAccess.aspx?listguid={ListId}&itemid={ItemId}&DefaultItemOpen=1"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"vwaViewAsWebAccessVsdxFromEcb","EnabledScript":null,"ImageUrl":null,"Location":"EditControlBlock","RegistrationId":"vsdx","RegistrationType":4,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Webbrowser anzeigen","UrlAction":"~site/_layouts/15/VisioWebAccess/VisioWebAccess.aspx?listguid={ListId}&itemid={ItemId}&DefaultItemOpen=1"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"vwaViewAsWebAccessVsdmFromEcb","EnabledScript":null,"ImageUrl":null,"Location":"EditControlBlock","RegistrationId":"vsdm","RegistrationType":4,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Webbrowser anzeigen","UrlAction":"~site/_layouts/15/VisioWebAccess/VisioWebAccess.aspx?listguid={ListId}&itemid={ItemId}&DefaultItemOpen=1"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"FormServerEcbItemOpenXsn","EnabledScript":null,"ImageUrl":"/_layouts/15/images/icxddoc.gif?rev=47","Location":"EditControlBlock","RegistrationId":"xsn","RegistrationType":4,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Browser bearbeiten","UrlAction":"~site/_layouts/15/formserver.aspx?XsnLocation={ItemUrl}&OpenIn=Browser&Source={Source}"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"FormServerEcbItemOpenInfoPathDocument","EnabledScript":null,"ImageUrl":"/_layouts/15/images/icxddoc.gif?rev=47","Location":"EditControlBlock","RegistrationId":"InfoPath.Document","RegistrationType":3,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Browser bearbeiten","UrlAction":"~site/_layouts/15/formserver.aspx?XmlLocation={ItemUrl}&OpenIn=Browser&Source={Source}"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"FormServerEcbItemOpenInfoPathDocument2","EnabledScript":null,"ImageUrl":"/_layouts/15/images/icxddoc.gif?rev=47","Location":"EditControlBlock","RegistrationId":"InfoPath.Document.2","RegistrationType":3,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Browser bearbeiten","UrlAction":"~site/_layouts/15/formserver.aspx?XmlLocation={ItemUrl}&OpenIn=Browser&Source={Source}"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"FormServerEcbItemOpenInfoPathDocument3","EnabledScript":null,"ImageUrl":"/_layouts/15/images/icxddoc.gif?rev=47","Location":"EditControlBlock","RegistrationId":"InfoPath.Document.3","RegistrationType":3,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Browser bearbeiten","UrlAction":"~site/_layouts/15/formserver.aspx?XmlLocation={ItemUrl}&OpenIn=Browser&Source={Source}"},{"ClientSideComponentId":"00000000-0000-0000-0000-000000000000","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"FormServerEcbItemOpenInfoPathDocument4","EnabledScript":null,"ImageUrl":"/_layouts/15/images/icxddoc.gif?rev=47","Location":"EditControlBlock","RegistrationId":"InfoPath.Document.4","RegistrationType":3,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"1"},"Title":"Im Browser bearbeiten","UrlAction":"~site/_layouts/15/formserver.aspx?XmlLocation={ItemUrl}&OpenIn=Browser&Source={Source}"},{"ClientSideComponentId":"957443ba-d69f-4847-8695-4e3108f081cd","ClientSideComponentProperties":"{\"sampleTextOne\":\"One item is selected in the list.\", \"sampleTextTwo\":\"This command is always visible.\"}","CommandUIExtension":null,"Id":"{0fb9c1e3-6107-43a3-a98d-43780ac4afd0}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet.CommandBar","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"CalendarGenerate","UrlAction":null},{"ClientSideComponentId":"4c68e118-4e69-4bd4-9ab3-55add4fd75e1","ClientSideComponentProperties":"{\"sampleTextOne\":\"One item is selected in the list.\", \"sampleTextTwo\":\"This command is always visible.\"}","CommandUIExtension":null,"Id":"{7642e464-6ca8-46b4-bdb8-912328ededcd}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"CancelRequest","UrlAction":null},{"ClientSideComponentId":"b8bc858d-2aa5-4805-ad95-3f8cb7133b07","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"{545e7307-9928-4f22-9677-f95a1c600e9a}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"EditPlannedVacation","UrlAction":null},{"ClientSideComponentId":"4c68e118-4e69-4bd4-9ab3-55add4fd75e1","ClientSideComponentProperties":"{\"sampleTextOne\":\"One item is selected in the list.\", \"sampleTextTwo\":\"This command is always visible.\"}","CommandUIExtension":null,"Id":"{31dd2c39-ec87-41a3-b62d-8dbd996ebded}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"CancelRequest","UrlAction":null},{"ClientSideComponentId":"b8bc858d-2aa5-4805-ad95-3f8cb7133b07","ClientSideComponentProperties":"","CommandUIExtension":null,"Id":"{43f8d8c1-a02a-4a90-a390-042c7deb4089}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"EditPlannedVacation","UrlAction":null},{"ClientSideComponentId":"4133be33-1268-4c83-965a-dc8a094ac5ed","ClientSideComponentProperties":"{\"sampleTextOne\":\"One item is selected in the list.\", \"sampleTextTwo\":\"This command is always visible.\"}","CommandUIExtension":null,"Id":"{0961017b-f6fb-4880-97af-79eca35255c1}","EnabledScript":null,"ImageUrl":null,"Location":"ClientSideExtension.ListViewCommandSet","RegistrationId":"100","RegistrationType":1,"RequireSiteAdministrator":false,"Rights":{"__metadata":{"type":"SP.BasePermissions"},"High":"0","Low":"0"},"Title":"EditTask","UrlAction":null}]}}}}`

Just tell me if you need more.

**Comment by patmill** [comment]
So if the entry appears twice, it will load twice.  So at least that makes sense.  Next question - why is it showing up twice?

If you go to the app catalog, there is a list that shows all the tenant-wide configurations of extensions.  Do your entries appear twice there?

**Comment by cwdata** [comment]
Thanks @patmill for following up.
The list "Tenant Wide Extensions" in the app catalog is empty. Our extensions are not configured for tenant wide deployment.

**Comment by cwdata** [comment]
Ok, I finally figured it out.
The fact that you were not able to reproduce this and that no one else here added "oh I'm experiencing the same issue" made me sleepless. So I used the additional time to create a new solution containing two extensions and that worked perfectly fine. After spending some time with "find the 10 errors in the right picture" I found the difference:
The problematic solution had two features in the package-solution.json (one for each extension). I remember that being necessary some time ago. The working solution contained only one feature. Removing the second feature did the trick.
I will now switch the tenant back to standard release to see if it is still working there with only one feature. 
It's embarrassing for me that I haven't done this test before posting and I promise to do more investigations next time.

**Comment by ahackettms** [comment]
Thank you @cwdata for the update. 
Please let us know if it is still working fine when you switch to Standard release.

**Comment by patmill** [comment]
No worries @cwdata - thanks for the update.  I think it is too hard to really know what extensions are being loaded, and from where.  I'm working on a sample to help diagnose things like this.

**Comment by cwdata** [comment]
@ahackettms Yes the extension is still working in Standard release.
