### ISSUE TITLE
'fetch' is undefined error in SPFX and out-of-the-box webparts

### ISSUE THREAD

**Issue by michelsmit** [SharePoint/sp-dev-docs#3838]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The Yammer Full Feed Webpart or other (custom) SPFX webparts using the http- or graph client should be able to render without any issues regarding the fetching of remote data.

#### Observed Behavior

When using the Graph client (or HTTP client) from our custom SPFX webparts the following issue occurs randomly (so not all the time, but sometimes):

 ```
"ReferenceError: 'fetch' is undefined
   at t.prototype.handleFetch (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/0.sp-http-msgraphclient_5ae609ae3611d0f0b2ab.js:1:5850)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/0.sp-http-msgraphclient_5ae609ae3611d0f0b2ab.js:1:6272)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-pages-assembly_nl-nl_7c0a30236f866238c82ab1edd0f121fb.js:1213:44723)
   at L (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-pages-assembly_nl-nl_7c0a30236f866238c82ab1edd0f121fb.js:8:2116)
   at T (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-pages-assembly_nl-nl_7c0a30236f866238c82ab1edd0f121fb.js:8:2232)
   at O (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-pages-assembly_nl-nl_7c0a30236f866238c82ab1edd0f121fb.js:8:2026)
```

This also occurs in (for example) the Yammer Full Feed webpart frequently so it's not really related to our custom SPFX webpart code. Yammer webpart shows following error:

```
"ReferenceError: 'fetch' is undefined
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js:132:28114)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js:118:35158)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js:118:34471)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js:118:34389)
   at A (eval code:1:14872)
   at a (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js:118:34182)
```

#### Steps to Reproduce

Place a Yammer Full Feed webpart (or custom SPFX webpart which uses the http- or graph client) on a page and watch the console log for errors. Since the issue occurs randomly it's hard to predict when the issue shows up.

Issue occurs regularly in Edge and IE11. Environment is SharePoint Online.

**Comment by VesaJuvonen** [comment]
hi @michelsmit - can you provide more details on what is the custom Yammer Full Feed web part you are referring to so that we can investigate the issue with more details. Thx.

**Comment by michelsmit** [comment]
Hi @VesaJuvonen it's the Yammer Full Feed webpart which SharePoint delivers out-of-the-box. See info below taken from maintenanceMode=true:

**Overview**
`
{
  "general": {
    "alias": "YammerFullFeedWebPart",
    "id": "cb3bfe97-a47f-47ca-bffb-bb9a5ff83d75",
    "instanceId": "27520be6-1b85-4017-b814-ae8383de9091",
    "isInternal": true,
    "version": "0.0.1",
    "environment": "2",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; rv:11.0) like Gecko"
  },
  "manifest": {
    "canUpdateConfiguration": true,
    "version": "0.0.1",
    "alias": "YammerFullFeedWebPart",
    "isInternal": true,
    "loaderConfig": {
      "internalModuleBaseUrls": [
        "https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-04-12.003/"
      ],
      "entryModuleId": "sp-yammer-full-feed-webpart",
      "scriptResources": {
        "sp-yammer-full-feed-webpart": {
          "type": "localizedPath",
          "defaultPath": {
            "default": "sp-yammer-full-feed-webpart_nl-nl_139b7b0791a7a8329a4f36a6e941af8b.js"
          }
        },
        "@microsoft/office-ui-fabric-react-bundle": {
          "type": "component",
          "id": "02a01e42-69ab-403d-8a16-acd128661f8e",
          "version": "1.9.0"
        },
        "@microsoft/sp-core-library": {
          "type": "component",
          "id": "7263c7d0-1d6a-45ec-8d85-d4d1d234171b",
          "version": "1.9.0"
        },
        "@ms/sp-webpart-shared": {
          "type": "component",
          "id": "914330ee-2df2-4f6e-a858-30c23a812408",
          "version": "1.0.25"
        },
        "@microsoft/sp-webpart-base": {
          "type": "component",
          "id": "974a7777-0990-4136-8fa6-95d80114c2e0",
          "version": "1.9.0"
        },
        "@microsoft/sp-http": {
          "type": "component",
          "id": "c07208f0-ea3b-4c1a-9965-ac1b825211a6",
          "version": "1.9.0"
        },
        "@microsoft/sp-page-context": {
          "type": "component",
          "id": "1c4541f7-5c31-41aa-9fa8-fbc9dc14c0a8",
          "version": "1.9.0"
        }
      }
    },
    "manifestVersion": 2,
    "id": "cb3bfe97-a47f-47ca-bffb-bb9a5ff83d75",
    "componentType": "WebPart"
  },
  "webPartData": {
    "id": "cb3bfe97-a47f-47ca-bffb-bb9a5ff83d75",
    "instanceId": "27520be6-1b85-4017-b814-ae8383de9091",
    "title": "Gesprekken",
    "description": "Yammer-feed voor groep, gebruiker, onderwerp of startpagina weergeven",
    "serverProcessedContent": {
      "htmlStrings": {},
      "searchablePlainTexts": {},
      "imageSources": {},
      "links": {}
    },
    "dataVersion": "1.0",
    "properties": {
      "type": "All",
      "threadCount": 4,
      "title": "Yammer gesprekken"
    }
  }
}
`

**Comment by patmill** [comment]
Can you provide some more information?  Does it happen on all browsers, or just IE/Edge?  Is it possible that you have installed your own polyfill on the page via an app extension or anything?

**Comment by michelsmit** [comment]
Hi @patmill, issue occurs only in IE11 and Edge. We don't polyfill the 'fetch' method in our code since this is taken care of in SP/SPFX. It also most of the times works as expected, but frequently the console raises the error 'fetch' is undefined', this in our custom web part but also in (for example) the Yammer Full Feed web part.

**Comment by andrewconnell** [comment]
@michelsmit said:
> We polyfill the 'fetch' method in our code as PNP provides the fetch polyfill in @pnp/polyfill-ie11 npm package.

Are you aware the SPFx already polyfills the `fetch` API by default as part of the `HttpClient` with the [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) polyfill? Could be the two polyfills are conflicting...

**Comment by andrewconnell** [comment]
Have you reviewed the recently published supported browsers docs here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Pay special attention to the IE11 node for the modern experience & IE's document mode.

If you continue to have the issue, please comment back with some additional context. Thanks!
