### ISSUE TITLE
Without upgrading the app, new changes are reflecting in sites. I am working with SPFx.

### ISSUE THREAD

**Issue by srinivasravila** [SharePoint/sp-dev-docs#3839]
We have a solution(SPFx V1.1) which Is already deployed in the app catalog and installed in the sites as well. Now we have new features in the solution and we re deployed the solution with next version. We did not upgrade the app in the sites, but the new features are available in the sites including new web parts also. Please provide the solution to control the new features in already installed sites.

**Comment by andrewconnell** [comment]
This is working by design... when you update the code in an SPFx package, all components that use the code receive then change when deployed.

@srinivasravila said:
> Please provide the solution to control the new features in already installed sites.

That would fall into the category of a feature request as the way things are working is by design. Feature requests should be posted to user voice: https://aka.ms/sp-dev-uservoice

**Comment by srinivasravila** [comment]
Thanks for your quick response.

**Comment by srinivasravila** [comment]
Actually we have SPFx solution which contains 2 web parts and few features. We have deployed into the App Catalog with version 1.0.0.0 and placed the reference files in CDN location (On-Premises). After deployment we have installed the app in the sites, features and web parts are available as per the version. Since we have new requirement on top of that, like one more web part and additional features, we have implemented the same and changed the version of the solution to 2.0.0.0 as well. Now we deployed the solution into the App Catalog and CDN files also placed in different location but **we didn't upgrade the app to version 2.0.0.0**. but versin 2.0.0.0 features and web parts are available in the sites. How we can control this? Is this by design as you said or we can control?

**Comment by srinivasravila** [comment]
> Actually we have SPFx solution which contains 2 web parts and few features. We have deployed into the App Catalog with version 1.0.0.0 and placed the reference files in CDN location (On-Premises). After deployment we have installed the app in the sites, features and web parts are available as per the version. Since we have new requirement on top of that, like one more web part and additional features, we have implemented the same and changed the version of the solution to 2.0.0.0 as well. Now we deployed the solution into the App Catalog and CDN files also placed in different location but **we didn't upgrade the app to version 2.0.0.0**. but versin 2.0.0.0 features and web parts are available in the sites. How we can control this? Is this by design as you said or we can control?
