### ISSUE TITLE
Safe to update office-ui-fabric-react npm package?

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#384]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
I noticed the included _office-ui-fabric-react_ package version is `0.69.0`. However, some important issues have been resolved in the meantime which would unblock current development issues (e.g. context propagation inside Layer components like Dialog, Panel).

I was wondering if it was safe to update the office-ui-fabric-react package to later versions, or what the possible side-effects would be?

Also, how would releasing a package with newer version have to be done?

**Comment by manishgarg1** [comment]
Hi @NickSevens, are you asking how to independently include a newer version of office-ui-fabric-react in your web part ? Or when will the SharePoint Framework include a newer version of this package?

**Comment by NickSevens** [comment]
@manishgarg1 I'm mainly asking if it's safe to update the office-ui-fabric-react package to a newer version inside my SPFx project, in order to have some issues pulled in which were fixed in post-0.69.0 versions of the package. Currently, the component I'm developing is only in development - so publishing to O365 is not that relevant yet.

However, I do believe it would be something to have a guideline for, since the office-ui-fabric-react package will probably be updated much faster than the SPFx bits will. I expect there will be quite some cases where developers would want to have these updates pulled in, and that could indeed be a "custom" include in the package then.

**Comment by manishgarg1** [comment]
Hi @NickSevens, at the current time it is recommended to use the version of office-ui-fabric-react that we ship with the framework. Currently we do not support side-by-side loading of this package on one page. e.g. It still has some global styles. That said, we are trying to work towards side-by-side loading as we march forward. So if you upgrade this package independently, there may be unexpected side effects on the modern pages, or the property pane or the workbench.

**Comment by NickSevens** [comment]
Okay. Thank you @manishgarg1.
Do you perhaps have an idea when or how often the package will be updated withing SPFx?
For example, will the package be upgraded to the latest version when releasing RC1 (or similar)?

**Comment by chakkaradeep** [comment]
@NickSevens SPFx depends on a set of packages and office-ui-fabric-react is one of them. As you guessed, it depends on a specific version. All the new modern experiences as well depend on that version at that time we ship. 

So we recommend to not update the office-ui-fabric-react package. One good thing about this is that since Microsoft is also using this in the production and if we deemed blockers we would upgrade the version immediately and release an update to npm.

**Comment by NickSevens** [comment]
Does this mean that when shipping, the latest version at that moment is shipped with SPFx? Or when can an upgrade occur?

**Comment by chakkaradeep** [comment]
When SPFx ships, a version of the office-fabric-react will be shipped. SPFx and Office Fabric React are two independent projects.

**Comment by NickSevens** [comment]
@chakkaradeep but, "a" version of office-fabric-react is included as npm dependency. When is it decided to upgrade that dependency version? And when shipping a new version of SPFx (RC1 for example), what version of office-fabric-react is made dependent? The latest version? Or some other version used during dev?

**Comment by chakkaradeep** [comment]
Choosing the right version is owned by the engineering team. If you are asking how we choose the right version, thats up to the engineering team to decide based on various factors.

**Comment by NickSevens** [comment]
Okay, thanks for the explanation @chakkaradeep.

**Comment by chakkaradeep** [comment]
@NickSevens if you feel this has answered your queries, please feel free to close the issue. Thanks!

**Comment by MKaslaan** [comment]
com.microsoft.office.word
