### ISSUE TITLE
Sorry something went wrong while deploying assets from spfx

### ISSUE THREAD

**Issue by mukeshhope** [SharePoint/sp-dev-docs#3840]
Hello Experts ,

As per the guide line give at 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package
I am following same steps but when ever i am trying to do "Add an app" then i can not add the app and it says "Sorry some thing went wrong with adding the app " 
![image](https://user-images.githubusercontent.com/18657453/56751756-6ba84c80-67a4-11e9-997f-97525e4273a5.png)

Below is steps to reproduce,
Followed the guideline and created a new solution
below is elements.xml file
`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">

    <Field ID="{060E50AC-E9C1-4D3C-B1F9-DE0BCAC300F6}"
            Name="SPFxAmount"
            DisplayName="Amount"
            Type="Currency"
            Decimals="2"
            Min="0"
            Required="FALSE"
            Group="SPFx Columns" />

    <Field ID="{943E7530-5E2B-4C02-8259-CCD93A9ECB18}"
            Name="SPFxCostCenter"
            DisplayName="Cost Center"
            Type="Choice"
            Required="FALSE"
            Group="SPFx Columns">
        <CHOICES>
        <CHOICE>Administration</CHOICE>
        <CHOICE>Information</CHOICE>
        <CHOICE>Facilities</CHOICE>
        <CHOICE>Operations</CHOICE>
        <CHOICE>Sales</CHOICE>
        <CHOICE>Marketing</CHOICE>
        </CHOICES>
    </Field>

    <ContentType ID="0x010042D0C1C200A14B6887742B6344675C8B" 
            Name="Cost Center" 
            Group="SPFx Content Types" 
            Description="Sample content types from web part solution">
        <FieldRefs>
            <FieldRef ID="{060E50AC-E9C1-4D3C-B1F9-DE0BCAC300F6}" /> 
            <FieldRef ID="{943E7530-5E2B-4C02-8259-CCD93A9ECB18}" />
        </FieldRefs>
    </ContentType> 

    <ListInstance 
            CustomSchema="schema.xml"
            FeatureId="8bab261f-ed6f-4663-9fd5-51D042f6633d"
            Title="SPFx List" 
            Description="SPFx List"
            TemplateType="100"
            Url="Lists/SPFxList">
    </ListInstance>

</Elements>`

below is schema.xml file
can not add here. i have attached the file instead
![error2](https://user-images.githubusercontent.com/18657453/56752242-731c2580-67a5-11e9-9ef1-96a886463055.png)

 and finally below is package-solution.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "assetdep-1-client-side-solution",
    "id": "c55f6765-d7c7-42c0-a557-78b3162dc1a5",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "features": [{
      "title": "asset-deployment-webpart-client-side-solution",
      "description": "asset-deployment-webpart-client-side-solution",
      "id": "8bab261f-ed6f-4663-9fd5-51d042f6633d",     
      "version": "2.0.0.0",
      "assets": {
        "elementManifests": [
          "elements.xml"
        ],
        "elementFiles":[
          "schema.xml"
        ]
      }
    }]
  },
  "paths": {
    "zippedPackage": "solution/assetdep-1.sppkg"
  }
}

depedencies in package.json :

 "dependencies": {
    "@microsoft/sp-core-library": "1.7.1",
    "@microsoft/sp-webpart-base": "1.7.1",
    "@microsoft/sp-lodash-subset": "1.7.1",
    "@microsoft/sp-office-ui-fabric-core": "1.7.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-tslint-rules": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.7.1",
    "@microsoft/sp-webpart-workbench": "1.7.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
I am not sure what i am doing wrong. it is frustrating.
Please suggest if someone have some solution.
If possible please suggest if there any other smooth way for deploying assets.

Thank you in advance for your response

**Comment by SimSpfx** [comment]
Hello Mukesh,

Could try each part seperately. 
First try to provision only the columns. If they appear:
provision columns and contenttype.
If they appear provision listinstance. 

If you are using example code, it might be better to generate your own guids using a generator.

Kind regards
Simon

**Comment by AJIXuMuK** [comment]
this is fixed in 1.14 beta
