### ISSUE TITLE
Incorrect information about flow launch panel

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-dev-docs#3846]
documentations says that "If the Flow is configured to gather data from the end user before running, the Flow Launch Panel will be displayed after choosing the button. Otherwise, the Flow will just run." We just spend time with MS Support who said that this is not possible and flow launch panel will always show, even if there's no user input required. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good to know... thanks for the feedback. Seems like that sentence should be removed. Care to submit a PR?

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
PR https://github.com/SharePoint/sp-dev-docs/pull/4230 is raised for this change.
Please review and let me know in case of any changes needed. Thanks!

**Comment by andrewconnell** [comment]
FYI - you don't need to link to PRs in the comments... as you can see above, it's already linked. When PRs are reviewed, it will get reviewed ;)
