### ISSUE TITLE
Generalize documentation to cover communication sites as well

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#3847]
Does the section _What's not supported on "modern" team sites_ also apply to communication sites? (I think so.) Then the documentation should be changed accordingly. Otherwise there will always be doubt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecfd641-4d66-1e34-8c32-1f59b53233d6
* Version Independent ID: 8627d0b0-94c0-f8fe-b753-b8e1411ead41
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites#feedback)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yes, Communication sites are considered modern sites.

**Comment by heinrich-ulbricht** [comment]
@andrewconnell I'd like to be specific here: are communication sites considered _modern **team** sites_? Because this is what the documentation is talking about.
* _Customizing "modern" **team** sites_
* _These "modern" **team** sites are integrated_
* _key benefits of the "modern" **team** sites_
* _options within "modern" **team** sites_
etc.
