### ISSUE TITLE
Consent link in custom Web Api

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#3849]
Could you please explain how I can let to consent to App in my tenant for my customer in order to get Service Principal in his tenant. I see that in this article Azure function endpoint is used and it somehow prompts for consent, but I use my custom Web Api 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbbb69a-f2dd-ed42-d887-14a72494000f
* Version Independent ID: 7e5c254a-fd12-0fc6-fc7d-61f4ef009226
* Content: [Consume multi-tenant enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
To consent using the API, you would typically navigate to the API URL in the browser which would trigger authentication and the consent flow the first time.

**Comment by andrewconnell** [comment]
This page may offer additional info for you: https://docs.microsoft.com/azure/active-directory/develop/consent-framework
