### ISSUE TITLE
The link is not shortened as decribed

### ISSUE THREAD

**Issue by delfuria** [SharePoint/sp-dev-docs#3851]
In the article you say that the link is shortened as
https://contoso-my.sharepoint.com/:w:/p/john/ERGZUIZ8E0pAuC1oJtwz4dQB23IabPgbMtiVe0OLPtMybw
but actually the link has this form
https://contoso-my.sharepoint.com/:w:/p/john_contoso/ERGZUIZ8E0pAuC1oJtwz4dQB23IabPgbMtiVe0OLPtMybw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a09a95-2554-dfcd-8229-f06706d5402d
* Version Independent ID: 9f2919a2-e88a-4af9-e3df-1cd4b4502691
* Content: [Shorter share link format in OneDrive and SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/shorter-share-link-format#feedback)
* Content Source: [docs/spfx/shorter-share-link-format.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/shorter-share-link-format.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi @delfuria , @VesaJuvonen 
This issue is fixed is pull request https://github.com/SharePoint/sp-dev-docs/pull/3985
Please review. Thank you.
