### ISSUE TITLE
How to change result format from XML to JSON for Search REST API?

### ISSUE THREAD

**Issue by ErikSwan** [SharePoint/sp-dev-docs#3852]
[This other page](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/using-the-sharepoint-search-query-apis#query-using-the-rest-service) suggests that the Search REST API can return results in either JSON or XML format, but this page has no mention of how to change the format of the returned results.

This page should be updated with information on the result format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#feedback)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by waldekmastykarz** [comment]
By default, the results are returned as XML. To get them in JSON format, you should add the following header to your request:

```text
accept: application/json;odata=verbose
```

or, if you're not interested in the metadata:

```text
accept: application/json;odata=nometadata
```

**Comment by ErikSwan** [comment]
Thanks. Maybe this seems obvious to some, but I feel like it could still be helpful to have this added to the doc.
