### ISSUE TITLE
Update list item REST API not working as expected

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/sp-dev-docs#3859]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The Update list item REST API should work as described in the documentation or the documentation should be updated.

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#update-list-item
#### Observed Behavior

When using the Update list item REST API, it is not possible to make it work as described in the documentation.  The following error is thrown 

> The property __metadata does not exist on type...

#### Suggested update
In the documentation it is explicitly mentioned to add the metadata field in the body.
`body: { '__metadata': { 'type': 'SP.Data.TestListItem' }, 'Title': 'TestUpdated'}`

However this triggers an error. After removing the metadata from the body I was able to make the code work. So please update the documentation accordingly.

**Comment by bcameron1231** [comment]
I have successfully updated an item using this REST documentation. If you are able to share your request and the headers being sent, we may be able to find the issue in your code.

**Comment by unowiz** [comment]
@EagleWizard28 @lucabandMSFT  I don't think this is a bug. The [note on the page](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#create-list-item) clearly mentions getting **ListItemEntityTypeFullName** 

> To do this operation, you must know the ListItemEntityTypeFullName property of the list and pass that as the value of type in the HTTP request body.

Here's how you can get that:
`http://site url/_api/web/lists/GetByTitle('Test')?$select=ListItemEntityTypeFullName `

**Comment by EagleWizard28** [comment]
@unowiz it seems it doesn't matter which value I pass, I get the following error:

> The property __metadata does not exist on type

So yes I was able to fetch the "ListItemEntityTypeFullName", but I'm unable to pass it. When I just drop the "_metadata" it works. Here some example code that works for me, which updates the list item. Take into account that the list has a custom content type.

``` javascript
    public async setItemComplete(itemId: number) {
        const itemUrl = `${this._normalizedWebUrl}/_api/web/lists/getByTitle('${this._ListTitle}')/items(${itemId})`;
        const client = new SPHttpClient();

        const updateData = {
            ResolutionDate: new Date().toISOString()
        };

        const httpClientOptions: FetchOptions = {
            headers: new Headers({
                 Accept: "application/json",
                "Content-Type": "application/json",
                "X-HTTP-Method": "MERGE",
                "IF-MATCH": "*",
            }),
            body: JSON.stringify(updateData)
        };

        return client.post(itemUrl, httpClientOptions);
    }
```

Am I overlooking something?

**Comment by sureshchandanam** [comment]
Hi
I am facing same issue.
I am using Fetch api  post request to create an Item, if I remove '__metadata' property then only item gets created otherwise it throws error. 
Is there anyone still facing this issue?
