### ISSUE TITLE
add more to sharepoint-webhooks-using-azure-functions.md 

### ISSUE THREAD

**Issue by johnnliu** [SharePoint/sp-dev-docs#386]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [x] Additional article idea

#### Expected or Desired Behavior

Several lines of code devoted to talking to Azure Storage Queue.  Can be simplified with default Azure Functions configuration in the Integrate tab.

Section detailing how to set up SharePoint to set up the WebHook is missing.  This can be run from client side javascript on SharePoint's side (need access_token to talk to SharePoint REST API).

some quick notes:

![image](https://cloud.githubusercontent.com/assets/1279372/22277452/b47f85d4-e30f-11e6-8b53-3e0af3a50096.png)

add Azure Queue to additional Output for the Function

![image](https://cloud.githubusercontent.com/assets/1279372/22277462/c733c10e-e30f-11e6-981b-8d49195c43d3.png)

Select the Storage Account

![image](https://cloud.githubusercontent.com/assets/1279372/22277465/d0e9c9b4-e30f-11e6-807d-2a0b70430d5a.png)

![image](https://cloud.githubusercontent.com/assets/1279372/22277473/d6f602dc-e30f-11e6-92b5-58eeecb6bb8f.png)

Add additional output parameter

![image](https://cloud.githubusercontent.com/assets/1279372/22277481/e554d3e4-e30f-11e6-9782-db8ec89acb22.png)

result

![image](https://cloud.githubusercontent.com/assets/1279372/22277483/ec36a3c2-e30f-11e6-85ac-3247863dbba7.png)

**Comment by chakkaradeep** [comment]
@jansenbe can you have a look? Thanks!

**Comment by johnnliu** [comment]
I should sit down and learn how to commit a PR properly.  :-(

(I actually don't know how)

**Comment by patmill** [comment]
Closing out old issues.  I can't tell what the status of this actually is, or if it is even an issue.
