### ISSUE TITLE
You need Python2.7 installed and added to Path env variable before start to do anything.

### ISSUE THREAD

**Issue by rodriguinIT** [SharePoint/sp-dev-docs#3861]
This is a message to help IT guys like me. I don't know if you miss it or you took for granted that all dev guys have python installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
You shouldn't have needed python installed for quite a while now (1+ years).  Where are you hitting this requirements?  What OS/SPFx version are you using?

**Comment by rodriguinIT** [comment]
My intention was create a development VM. SO I installed a fresh copy of Windows 10 Enterprise 1809 x64 in a VM - Then I installed Office Pro (from Office 365 portal) and Sharepoint designer. After that I started to follow this instruction. First attemp with Node 8.16.0 x64 - Install @microsoft/generator-sharepoint drops me a lot of error trying to install several components (also some rare error like that it can't install some dependencies because it can't download some packages - so I test the url and the download works fine - also I don't have proxy or nothing at all) - when I tried to create helloworld-webpart the first attemp yeoman hangs - then finished but with a lot of errors and gulp serve drops Error: Cannot find module '@microsoft/sp-build-web' - so I downgrade to node version that was used in the video linked in this page and the same behavior. Reading github issue tracker i've found a stackoverflow link that show me differents forms to solve the issue https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies so I've rollback to previous checkpoint and start it again but now I installed Python2.7 and set up the correct path env var (and also i've added some npm property that points to python binary but i'm not sure if it really needed) and voila. I have my workbench with my first webpart.

**Comment by andrewconnell** [comment]
It sounds like dependencies aren't being installed correctly. As @patmill said, installing python hasn't been a required step for quite some time. I recently built a brand new Win10 VM and didn't have this experience.

Could all those errors be because you are behind a proxy on your corp network? That would cause it... If so, there are configuration changes you can make to NPM to let it know the proxy server details...

**Comment by StfBauer** [comment]
It depends on some situation you run for what reason ever NodeJS on Windows only in 32bit mode. Since there are no precompiled versions are available for Windows 32bit you have to compile them yourself using:

```sh
npm install -g windows-build-tools
```

The check if NodeJS is running on 32bit or 64bit can be done with.

```sh
node -p "process.arch"
```

<img width="395" alt="Screenshot 2019-06-27 at 20 04 39" src="https://user-images.githubusercontent.com/5503835/60289530-ed3c6800-9916-11e9-9e22-8022afe2b278.png">

- **ia32** -32bit NodeJS
- **x64** - 64bit NodeJS

**Comment by rodriguinIT** [comment]
As I said, my deployment was a fresh Windows 10 Install

> It sounds like dependencies aren't being installed correctly. As @patmill said, installing python hasn't been a required step for quite some time. I recently built a brand new Win10 VM and didn't have this experience.
> Could all those errors be because you are behind a proxy on your corp network? That would cause it... If so, there are configuration changes you can make to NPM to let it know the proxy server details...

Sorry but no, it was my home network. no firewall or UTM at all. My vms have full Internet Access. But it's ok I found a solution and maybe it will help someone with my issue.

**Comment by rodriguinIT** [comment]
> It depends on some situation you run for what reason ever NodeJS on Windows only in 32bit mode. Since there are no precompiled versions are available for Windows 32bit you have to compile them yourself using:
> npm install -g windows-build-tools
> The check if NodeJS is running on 32bit or 64bit can be done with.
> node -p "process.arch"
> 
> 
> ia32 -32bit NodeJS
> x64 - 64bit NodeJS

Maybe this is the issue. I always use x64 in my VMs.  Also I don't remember my exact procedure but I remember playing around with Architecture versions and NodeJS.

**Comment by andrewconnell** [comment]
Seems like this is localized to your environment @rodriguinIT as you say you were playing around with arch versions & node.js... so we're good?

**Comment by rodriguinIT** [comment]
Yes sir! We're good!! thanks!
