### ISSUE TITLE
List View web part doesn't respect hideColumnHeader set to true

### ISSUE THREAD

**Issue by robertoyg** [SharePoint/sp-dev-docs#3862]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Setting hideColumnHeader should hide the columns header in the view when being rendered inside a page using a list view web part in order to be consistent with the behavior in the view of the list itself.

#### Observed Behavior

When setting hideColumnHeader to true, the behavior works as expected in the list itself (column headers are hidden) but not when this list view is selected inside of the List web part on a page, there the headers still show.

#### Steps to Reproduce

I used the tiled example to confirm this (even though this is not rendering well in new versions the behavior is the one mentioned in the bug):

`{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": "true",
  "hideColumnHeader": "true",
  "rowFormatter": {
    "elmType": "a",
    "attributes": {
      "href": "[$URL]",
      "target": "=if([$NewTab] == true, '_blank', '')"
    },
    "style": {
      "float": "left"
    },
    "children": [
      {
        "elmType": "div",
        "attributes": {
          "class": "ms-bgColor-themeLighterAlt ms-bgColor-themePrimary--hover ms-fontColor-white--hover"
        },
        "style": {
          "display": "flex",
          "flex-wrap": "wrap",
          "min-width": "180px",
          "min-height": "150px",
          "margin-right": "10px",
          "margin-top": "10px",
          "box-shadow": "2px 2px 4px darkgrey"
        },
        "children": [
          {
            "elmType": "div",
            "style": {
              "text-align": "center",
              "margin": "auto"
            },
            "children": [
              {
                "elmType": "div",
                "attributes": {
                  "class": "sp-row-title "
                },
                "txtContent": "[$Title]"
              },
              {
                "elmType": "div",
                "attributes": {
                  "iconName": "[$Icon]",
                  "class": "ms-fontSize-su"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}`

**Comment by MisterAnderson91** [comment]
I'm also having this issue. It was working previously (As recent as 26/04/19)

**Comment by VayaCh** [comment]
it used to work for 2-3 weeks ago. Now it doesn't. I got the same problem.

**Comment by gobigfoot** [comment]
This needs attention

**Comment by gobigfoot** [comment]
This suddenly started working again across multiple tenants.

**Comment by MisterAnderson91** [comment]
Same here, working today.

**Comment by svaibhav** [comment]
This was because of a minor bug, which was fixed soon. But since out list's and web parts deployment happens independently, this was was there on the web parts for a little longer.
We can close this PR now!
