### ISSUE TITLE
Windows Defender finds Trojan creating new SPFx solution.

### ISSUE THREAD

**Issue by TheDeadman** [SharePoint/sp-dev-docs#3863]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Windows would not find a trojan when generating a new SPFx solution.

#### Observed Behavior

Windows Defender finds a [trojan](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aJS%2fCoinMiner&threatid=2147727229) in one of the dependencies... `\node_modules\flatmap-stream\index.min.js`

#### Steps to Reproduce

Install the latest version of `@microsoft/generator-sharepoint` and create a new project using `yo @microsoft/sharepoint`

**Comment by patmill** [comment]
So, that's a bit strange.  There was the whole issue previously with event stream (https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)  which I think flatmap stream used.

Can you grab the version of flatmap-stream that is showing up there?  Also, what does your package.json file look like?  Any chance you are using your own repo that has an older version of flatmap-stream cached?

**Comment by TheDeadman** [comment]
Sorry for not getting back to you sooner. I generated another SPFx solution and was able to reproduce the issue. This is a new SPFx solution and I have not installed any dependencies of my own. I also updated the SharePoint Generator again and still reproduced the issue.

Here are the files that Win Defender indicates are trojans.
file: C:\Users\****\Documents\dev\win-def-issue\node_modules\.staging\flatmap-stream-07a5f784\index.min.js
file: C:\Users\****\Documents\dev\win-def-issue\node_modules\.staging\flatmap-stream-07a5f784\test\data.js

From my package-lock.json, here is the entry for flat-map
    "flatmap-stream": {
      "version": "0.1.1",
      "resolved": "https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz",
      "integrity": "sha512-lAq4tLbm3sidmdCN8G3ExaxH7cUCtP5mgDvrYowsx84dcYkJJ4I28N7gkxA6+YlSXzaGLJYIDEi9WGfXzMiXdw==",
      "dev": true
    },

and it looks like it is coming in as a dependency of event-stream.
        "event-stream": {
          "version": "3.3.6",
          "resolved": "https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz",
          "integrity": "sha512-dGXNg4F/FgVzlApjzItL+7naHutA3fDqbV/zAZqDDlXTjiMnQmZKu+prImWKszeBM5UQeGvAl3u1wBiKeDh61g==",
          "dev": true,
          "requires": {
            "duplexer": "^0.1.1",
            "flatmap-stream": "^0.1.0",
            "from": "^0.1.7",
            "map-stream": "0.0.7",
            "pause-stream": "^0.0.11",
            "split": "^1.0.1",
            "stream-combiner": "^0.2.2",
            "through": "^2.3.8"
          }
        },

Let me know if you want any other information.

Thanks

**Comment by TheDeadman** [comment]
It looks like when I am creating the new SPFx solution using Yeoman, it is creating it using version 1.7.1 instead of the latest version. It looks like there may be issues with my setup. I will try to get this resolved and try again.

**Comment by TheDeadman** [comment]
So I got the issues resolved. It was related to using Node Version Manager. I have uninstalled it from my machine and completely re-installed node. I am able to generate a SPFx solution at version 1.8.2 now but I still get the issues with flatmap and event-stream.
