### ISSUE TITLE
AadHttpClient sandbox iframe issue

### ISSUE THREAD

**Issue by antoniobriones** [SharePoint/sp-dev-docs#3866]
I have an SPFX Web part running on 1.8.0 using AADHttpClient that generates the following error in the console when the page is opened:
Unsafe JavaScript attempt to initiate navigation for frame with origin from frame with URL 'https://login.microsoftonline.com/... The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

I'm following the steps from here; https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi

**Comment by JorisZzz** [comment]
I have the exact same issue.

**Comment by lahuey** [comment]
Hi,

This is a warning that you can safely ignore. The browser is warning you that an iFrame with the address login.microsoft.com is attempting to perform a full page redirect. We have wrote code to explicitly block this, as it creates a terrible user experience (page randomly navigates to the Microsoft login page).
