### ISSUE TITLE
{Site.ID}, {Web.Id} and {SiteCollection.ID} all resolve to webId in Search REST API

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#3869]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm sending a search query to the Search REST API (_/api/search) using Query Variables in the QueryTemplate:
- `searchTerms: *`
- `QueryTemplate: {searchTerms} DepartmentId:{Site.ID} or DepartmentId:{Web.ID} or DepartmentId:{SiteCollection.ID}`

As a result, I expect to see a QueryModification that translates the tokens to at least two different GUID's (the SPWeb ID and the SPSite ID).

#### Observed Behavior
All three tokens get translated to the SPWeb ID.
 ```
* DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf or DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf or DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf -ContentClass=urn:content-class:SPSPeople
```

Behavior was discovered here (https://github.com/SharePoint/sp-dev-solutions/issues/136#issuecomment-488121865) and confirmed by @wobba (https://github.com/SharePoint/sp-dev-solutions/issues/136#issuecomment-488248056)

#### Steps to Reproduce
- Use the [Search Query Tool](https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool)
- Connect to a SharePoint Online site
- QueryText: `*`
- QueryTemplate: `{searchTerms} DepartmentId:{Site.ID} or DepartmentId:{Web.ID} or DepartmentId:{SiteCollection.ID}`

**Comment by YannickRe** [comment]
I've got a ticket open for this, and it currently is under review for a hotfix by the product engineering team.

**Comment by RichG82** [comment]
Hello,

Is there any update on this item?  I am experiencing the same issue.

**Comment by YannickRe** [comment]
It’s recognized as incorrect in the code (docs are correct), but this is the latest response I got from my support ticket about the potential hotfix:

> Please know that we have checked with the Product Engineering team and they currently have marked this request as a "Low Priority", as they consider it to be more of a "How to improve" topic rather than a critical issue. The good news is that they have not rejected the request, but it will take a very long time (several months at least) for them to make a decision regarding this issue.

**Comment by PieterHeemeryck** [comment]
This is still the case. Any update? It's been almost 2 years.
