### ISSUE TITLE
Referring CSS file from azure blog-storage cdn path text Format styles not working

### ISSUE THREAD

**Issue by dvinodeluru** [SharePoint/sp-dev-docs#3875]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Linking the CSS file outside SharePoint domain, SharePoint text format styles are not applying.

**Inside SharePoint** - works referring CSS file from _Layouts_ or _Style library_ 
domain.com/pages/default.aspx
CSS file /_layouts/15/styles/styles.css 
.rteStyle-Call-Out-Tip,
.ms-rteStyle-Call-Out-Tip {
    -ms-name: "Call-Out-Tip";
    display: block;
    margin: 80px auto 20px auto;
    line-height: 22px;
    color: #000000;
    font-size: 20px;
    position: relative;
}

**Outside SharePoint** - wont work when referring CSS file from _azure blog_ storage **cdn** path
domain.com/pages/default.aspx
**CSS** file cdn.azuredomain.com/styles/styles.css 
.rteStyle-Call-Out-Tip,
.ms-rteStyle-Call-Out-Tip {
    -ms-name: "Call-Out-Tip";
    display: block;
    margin: 80px auto 20px auto;
    line-height: 22px;
    color: #000000;
    font-size: 20px;
    position: relative;
}

#### Observed Behavior

referring CSS file from azure blog storage cdn path or any where

#### Steps to Reproduce

**Add a CSS format style**  
.rteStyle-Call-Out-Tip,
.ms-rteStyle-Call-Out-Tip {
    -ms-name: "Call-Out-Tip";
    display: block;
    margin: 80px auto 20px auto;
    line-height: 22px;
    color: #000000;
    font-size: 20px;
    position: relative;
}

Upload the file in CDN or Github
Point the CSS file in SharePoint master page or refer the link through "Look and Feel > Master page > Alternative CSS"

#### Submission Guidelines

![formate styles](https://user-images.githubusercontent.com/2167566/57086878-95212500-6d1c-11e9-90c5-dcee0e171ac6.png)

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Not clear on what you're reporting... in the _expected / desired behavior_ section you're saying it's not working... is that what is happening or what's expected? Not sure what the two pictures are showing in the _submission guidelines_ section either... 

Can you update the issue to use the provided headings as they are intended as it's not clear what you expect to happen or what is happening that shouldn't or should be happening...

**Comment by StfBauer** [comment]
The styles that you are referring to are from the classic publishing infrastructure. Based on my experience this has something to do how quickly the style get loaded by SharePoint. The support for those styles never worked from a CDN.

At least the attribute `-ms-name` needed to be loaded from inside SharePoint. So basically the minimum of:

```css
.ms-rteStyle-Call-Out-Tip {
-ms-name: "Call-Out-Tip";

**Comment by dvinodeluru** [comment]
When referring CSS file from Azure CDN storage, the custom styles for SharePoint Text Styles are not rendering, Only works when they are referring from SharePoint Style library or Layouts folder, I was wondering if the application got migrated from On-Premises to Online(CDN), SharePoint Text styles won't work?

**Comment by StfBauer** [comment]
Sadly not the support on modern experience pages for CDN has nothing to do with the classic experience. It has not been upgraded in years now. You can host your style sheets in general from a CDN but in case of RTE Extensions and modification, those need to be served from the style library or _layouts folder.

What you can do is to cut out only the RTE extension from your style sheet and load them from the Style Library or _layouts and in addition to this host the overall branding from a CDN.

**Comment by dvinodeluru** [comment]
Thank you for your responses and I have separated the SharePoint "Text Styles" and referring from SharePoint location(Style Library or _Layouts) and reset of the styles from azure CDN. 

Hope for SharePoint online, O365, SharePoint CDN won't make this issue in future. Hence consider this issue answered and closing.
