### ISSUE TITLE
SPFX isDomainIsolated true - Orphan API permission

### ISSUE THREAD

**Issue by antoniobriones** [SharePoint/sp-dev-docs#3876]
Hi all, I'm facing this issue:

- I created SPFX webpart with the setting isDomainIsolated = true
- I uploaded it to the tenant app catalog and then approved the permission in Admin Center - API management
- That created an Azure AD app reg called "{thenameofthewepart} - client-side-solution"
- Some time later, I deleted that app from the catalog
- The day after, I realized it hadn't deleted that app reg in Azure, so I deleted it manually.
- After that, the API management page got completely useless, it keeps behaving like this:

![image](https://user-images.githubusercontent.com/50162129/57101400-85431a00-6cf7-11e9-96a1-81f26463481e.png)

Same thing happens if I use Get-SPOTenantServicePrincipalPermissionGrants:

![image](https://user-images.githubusercontent.com/50162129/57101492-bf142080-6cf7-11e9-90c5-96c32ba56dac.png)

After a long time researching, I found that if I restore that Azure AD app reg with that name, and I create a service principal for it, the command and the page work fine. However, if I create a new webpart and approve the permissions, it's not working as expected. All new webparts that I upload seem to want to use the id that app that is orphaned in Azure when the try to authorize.

Does anyone know if there's a way to "clean" the API permissions in SharePoint? So that if I delete the Azure AD app, that doesn't stay orphaned? Now, I can't approve any other webpart, I got to MS support but they don't seem to be able to do anything.

Thanks

**Comment by patmill** [comment]
I believe we have a fix for this rolling, and I believe will not require anything on your part.  @lahuey to confirm.

**Comment by antoniobriones** [comment]
Thanks @patmill In the meanwhile, is there a way on sharepoint to get rid of those "mappings" to the unexisting azure apps? otherwise, my tenant is useless (at least for what i need to use it now)

**Comment by lucabandMSFT** [comment]
hey @antoniobriones, I need to get more information from you before being able to provide an educated reply. 
When you say "unexisting / Orphan app", what do you mean?
I'm asking because, if I understood correctly your current situation, you should have:
* a "SharePoint Online Client Extensibility Web Application Principal" App + Service Principal
* a "{thenameofthewepart} - client-side-solution" App + Service Principal (this was the one that was created by SPFx when you selected 'isDomainIsolated = true')

so, what else is not existing?

Thanks

**Comment by antoniobriones** [comment]
Hi @lucabandMSFT

Right, it created both for me. This is what happened. 
- After the first deployment, I deleted the app from the catalog. Uploaded it again, approved the permissions again in API mngmt. Then, deleted this second "instance" of the app from the catalog.
- Then, I realized that the API mng page was displaying an error twice saying that there were two apps with the same URI (nothing showed up in API mng).
- So went to Azure and realized there were two apps the name and redirect uris
- Deleted them
- Another error appears now in API mngt page saying "Unknown error"
- After some time I founf that the error appeared because one of those two apps was deleted. Restored it, created a Service Principal for it and the error was gone.

But what I found from there on is:

- I can't remove "{thenameofthewepart} - client-side-solution" app reg and its corresponding service principal from Azure, it just makes API mngt page show that 500 error and become useless.
- On the other side, I also found that if I don't delete that application, any other SPFX wbp I create that needs API permissions will authorize passing that client id instead of the one corresponding to its own app.

Hope that helps. When I refer to deleting something, is because I suppose there may be something in SharePoint that is still "pointing" to the deleted app reg.That's what I want to delete. If I run get-spotenantserviceprincipalpermissiongrants it just returns nothing, so I suppose there might be something else.

**Comment by lucabandMSFT** [comment]
ok so .. yes, that's the problem and a patch is rolling as we speak.
between this weekend and Monday (worst case) you should be unblocked.

I will let this issue open and will check with you on Monday.

**Comment by andrewconnell** [comment]
@antoniobriones You can remove permission grants via the SharePoint Online PowerShell or via the Office 365 CLI, which are good alternatives when the browser experience has issues.

**Comment by antoniobriones** [comment]
@lucabandMSFT this got resolved after the patch today, closing the thread, thanks.
