### ISSUE TITLE
Failed to loadCommandSet ***Expecting a class that extends BaseExtension.

### ISSUE THREAD

**Issue by DanSantoDomingo** [SharePoint/sp-dev-docs#3877]
Hi everyone,

I recently created spfx extension ListView Commandset and upload it in our app catalog but sometimes the button does not show in our page. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Commandset button will show on sharepoint online page.

#### Observed Behavior

Button sometimes don't show and throws this error
`Failed to loadCommandSet, id: 7dcabc2e-7905-4b8a-9547-7da8b44f4edc, error: Error: ***Expecting a class that extends BaseExtension.`

#### Steps to Reproduce

Create spfx extension commandset, package it, upload to app catalog.

**Comment by patmill** [comment]
Is there anything in the console that looks suspicious?  Are you doing anything other than a basic scaffolded project?  What version of the framework are you using?  Are you in SharePoint online, or on prem?
