### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by PaulMGibson** [SharePoint/sp-dev-docs#3883]
I am having issues with this tutorial.  I do run VS with admin rights, and I am an admin on our sharepoint online site.  I have created the developer site within sharepoint, and when I browse to it I don't see Add-ins in Testing, but instead I see Apps in Testing.

I get to the point in the tutorial when I am creating the list item, and then I get a connection error that says I don't have permissions to access the dev site (url is https://mycompany.sharepoint.com/sites/PMDev/) where mycompany is the corporate 365 registration name.  The only references to this error have to do with SQL Server permissions for Sharepoint server, but this is for sharepoint online.  Can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7795f659-9cc4-310b-1ea6-9842a6a2930a
* Version Independent ID: cfc98572-f913-6f48-cfe4-1b9dd526d7fc
* Content: [Get started creating SharePoint-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins#feedback)
* Content Source: [docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You shouldn't have any connection issues related to SQL Server if you're working in SharePoint Online... Can you provide more detail where you were getting the error or error message? Not clear if you got the error from the browser / visual studio / etc....

Submitted a PR to address the inconsistency in the name of the list.
