### ISSUE TITLE
Some users encountering AADSTS50058 error with web part

### ISSUE THREAD

**Issue by RyanMcCarney** [SharePoint/sp-dev-docs#3884]
#### Category
- [x] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

I have 2 web parts that use the AadHttpClient class to access an Azure AD secured oData service. All permissions have been configured and approved via the SharePoint Admin Portal's API Management. Both web parts are also not domain isolated.

Each web part has been deployed to a seperate classic publishing site collection via site collection scoped app catalogs. One instance has no issues, the on the other site collection (root site collection of the tenant) the web part consistently throws an error for some users.

Here's the error:
AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint. Trace ID: fa91fe89-e91d-4138-a191-611faa672800 Correlation ID: 512a2107-0000-440f-acd3-97b593fa4dd2 Timestamp: 2019-04-30 18:45:51Z

For additional testing, I deployed both the web parts to a seperate site collection (modern team site) via it's site collection scoped app catalog. The users encounting the error on root site collection have no issues on the modern site accessing the same web part.

The web part assets are all deployed to Azure Blob Storage and are delivered via an Azure CDN.

I've also gone through the exercise of updating both web parts to the latest SharePoint Framework (1.8.1) from the initial version of 1.7, the behaviour hasn't changed.

#### Expected or Desired Behavior
Web part should work as expected in all site collections.

#### Observed Behavior
Some users have no issues, small subset of users get the noted error on just the root site collection, exact same web part works on a different site collection for those users.

#### Steps to Reproduce
User accesses the page that has the web part added to it.

#### Additional Info Request / Guidance
Is there any other site collection configuration settings I should be looking at for troubleshooting the web part for those users encountering the issues?

#### Code Snippets

//getting an instance of the AadHttpClient
  protected onInit(): Promise<void> {
    return new Promise<void>((resolve: () => void, reject: (error: any) => void): void => {
      this.context.aadHttpClientFactory
        .getClient([GUID])
        .then((client: AadHttpClient): void => {
          this.domoClient = client;
          resolve();
        }, err => reject(err));
    });
  }
  
  //using the client
   this.domoClient           
            .get([URL],AadHttpClient.configurations.v1, { headers: this.reqHeaders })
                .then(response => { })...

**Comment by lahuey** [comment]
Hi Ryan,

Could you look at the url of the request to retrieve tokens (both the success and failure case)? They should be identical. 

 The url should look like this -> https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id={}&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2Fwebshell.suite.office.com%2Fiframe%2FTokenFactoryIframe&state=f0d8e53d-77f2-438a-bcf4-4abd34d08393%7Chttps%3A%2F%2Fgraph.microsoft.com&client-request-id={}&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none&login_hint=UPN&domain_hint=microsoft.com

**Comment by desseray** [comment]
My users have also been having the same issue with the same setup, but I am yet to be able to replicate this myself so I can't accurately debug it. very frustrating.

**Comment by RyanMcCarney** [comment]
> Hi Ryan,
> Could you look at the url of the request to retrieve tokens (both the success and failure case)? They should be identical.
> The url should look like this -> https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id={}&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2Fwebshell.suite.office.com%2Fiframe%2FTokenFactoryIframe&state=f0d8e53d-77f2-438a-bcf4-4abd34d08393%7Chttps%3A%2F%2Fgraph.microsoft.com&client-request-id={}&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none&login_hint=UPN&domain_hint=microsoft.com

I'm trying to schedule some time with some affected users to get this info for you.
Thanks again for the assist.

**Comment by RyanMcCarney** [comment]
> Hi Ryan,
> Could you look at the url of the request to retrieve tokens (both the success and failure case)? They should be identical.
> The url should look like this -> https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id={}&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2Fwebshell.suite.office.com%2Fiframe%2FTokenFactoryIframe&state=f0d8e53d-77f2-438a-bcf4-4abd34d08393%7Chttps%3A%2F%2Fgraph.microsoft.com&client-request-id={}&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none&login_hint=UPN&domain_hint=microsoft.com
> 
> I'm trying to schedule some time with some affected users to get this info for you.
> Thanks again for the assist.

So I've done some additional troubleshooting and the login hint's don't line up between the 2 site collections hosting the web part. 

My client over the last year has been changing their upn's from a 7 character username (first initial, last name) to a firstname.lastname structure.

The site collection where the web part isn't working is passing the 7 character username for the login hint. I've also discovered that there's 2 entries in teh hidden site users list for the 2 users that I know have the issue. One with the proper UPN, the other with the old one. I have to script out a report to see if there are any other users that might be impacted.

I'm looking into writing a script right now to see if there's any content associated with the old entry for one of the impacted users before removing the duplicate entry from the site users list. 

Not sure if this will resolve the issue or not or if there's a better approach to resolving the issue with the wrong UPN being passed to Azure AD in this scenario.

If you need more specific details lahuey please shoot me an email and I can pass along any additional details you might need.

**Comment by lucabandMSFT** [comment]
so.. it looks like where the web part doesn't work (classic site) is where there's duplication and the "wrong" UPN is sent.. correct?

**Comment by RyanMcCarney** [comment]
> so.. it looks like where the web part doesn't work (classic site) is where there's duplication and the "wrong" UPN is sent.. correct?

That's correct. I'm still working towards removing the duplicate entry in the Site Users list, but dealing with some potential data issues as the wrong site user entry is used in metadata on the site. Once I get that cleaned up I'll have the user retest.

**Comment by RyanMcCarney** [comment]
> Hi Ryan,
> Could you look at the url of the request to retrieve tokens (both the success and failure case)? They should be identical.
> The url should look like this -> https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id={}&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2Fwebshell.suite.office.com%2Fiframe%2FTokenFactoryIframe&state=f0d8e53d-77f2-438a-bcf4-4abd34d08393%7Chttps%3A%2F%2Fgraph.microsoft.com&client-request-id={}&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none&login_hint=UPN&domain_hint=microsoft.com
> 
> I'm trying to schedule some time with some affected users to get this info for you.
> Thanks again for the assist.

So I've been able to fix it for the impacted users. 

By doing a SharePoint.Client.Web.Ensure([old upn]) it actually updates the Site Users entry and deletes the duplicate. Haven't gone and sorted out any potential content issues that may have occurred (spot checks didn't identify any) but I can confirm that it fixes the web part issues for the impacted users.

Thanks again for the help.
