### ISSUE TITLE
SPFX Extension doesnt work on HUB site. 

### ISSUE THREAD

**Issue by enti333** [SharePoint/sp-dev-docs#3885]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hello. I have created simple SPFX extension. This extension is a type command Button. 
Everything was working fine. But The site on which I have this button is now added to HUB site...And the button is gone... I see that event scripts for this button are not loaded. When I revert back setting and set the site to NONE in HUB settings everything start to work...
Hmm...What can be a problem?
Thank you

**Comment by rchendev** [comment]
Thanks for reporting this. 2 questions:1. are you on First release tenant or are you first release user? 2. Is the command button on the listview header area? Is there anyway for us to get a repro to debug the issue?
