### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by IstvanYbema** [SharePoint/sp-dev-docs#3886]
Two comments:
"url – The url of the link to add" shout be "... to remove" on the "Remove a navigation link" verb.

Please explain how to remove the Dutch version of Pages what is translated to "Pagina's". 
Just using the title "Pagina's" does not work. Probably because of the '
What is the escape character?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi,
This is fixed in pull request [3918](https://github.com/SharePoint/sp-dev-docs/pull/3918)

@andrewconnell , @VesaJuvonen , @IstvanYbema 
Please review. Thank you!
