### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by Sako73** [SharePoint/sp-dev-docs#3887]
The document says to import from '@microsoft/sp-property-pane', but it is '@microsoft/sp-webpart-base'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Your comment is incorrect... in the latest generator (v1.8+), the property pane objects were refactored to their own package as the doc says. There are still "maps" to them in the `sp-webpart-base` package, but those will be removed in v1.9.0). See the 1.8 release docs for more details: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#removing-propertypane-code-out-of-sp-webpart-base

**Comment by NZTEbaribc** [comment]
I think regardless of who's comment is right or wrong. Following the instructions on this page fails due to the import of microsoft/sp-property-pane
because microsoft/sp-webpart-base already exists after you create the project. but if you remove the contents of the microsoft/sp-webpart-base import then the project just continues with more issues.
