### ISSUE TITLE
MSOnlineExtended is no longer valid

### ISSUE THREAD

**Issue by SpliceVW** [SharePoint/sp-dev-docs#3892]
Looks like the module MSOnlineExtended is now MSOnlineExt, so that step should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58462e32-ad55-2351-ee7d-67c047fa4157
* Version Independent ID: 0cba1f85-d95c-6b4e-583d-608a6743e15f
* Content: [Use an Office 365 SharePoint site to authorize provider-hosted add-ins on an on-premises SharePoint site](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on#feedback)
* Content Source: [docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
No... that's a module by a third party, not by Microsoft.

The recommended thing to do is to use the SharePoint Online POSH: https://www.microsoft.com/download/details.aspx?id=35588

Will update the docs...
