### ISSUE TITLE
Unable to play along

### ISSUE THREAD

**Issue by anvilation** [SharePoint/sp-dev-docs#3895]
#### Category
- [ ] Question
- [x ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`<p class="${ styles.description }">Loading from ${escape(this.context.pageContext.web.title)}</p>`

Two issues: 

1. React (well the latest version of your SharePoint boilerplate) longer rendering this way - on the latest build of the SharePoint project you would render it like this `{escape(this.context.pageContext.web.title)}`

2. `this.context` is an empty JSON string so attempting to prompt `this.context.pageContext.web.title` wont work. 

Is there update documentation that covers what is being observed in the latest project?

**Comment by patmill** [comment]
Not sure we're on the same page.  this.context isn't a JSON string, it should be a fully typed object.  What version / etc. are you using?  Ie, what version of the generator, and how did you answer the questions?
