### ISSUE TITLE
Issue While Provisioning Sharepoint site with Template

### ISSUE THREAD

**Issue by 026907** [SharePoint/sp-dev-docs#3897]
PnP Correlation ID: 2053a99a-ba48-4669-93f5-f053540427e

Here is the exception that occurred:    

Type = System.Exception Message =     {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"51ae104a-8c1c-4126-b0ec-b8de5e295678","SiteStatus":1,"SiteUrl":null}     Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at     OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__3.MoveNext() in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     256 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     OfficeDevPnP.Core.Sites.SiteCollection.Create(ClientContext clientContext,     TeamSiteCollectionCreationInformation siteCollectionCreationInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     43 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     59 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     207 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     360 HResult = -2146233088 | Here is the exception that occurred:     Type = System.Exception Message =     {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"51ae104a-8c1c-4126-b0ec-b8de5e295678","SiteStatus":1,"SiteUrl":null}     Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at     OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__3.MoveNext() in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     256 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     OfficeDevPnP.Core.Sites.SiteCollection.Create(ClientContext clientContext,     TeamSiteCollectionCreationInformation siteCollectionCreationInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     43 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     59 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     207 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     360 HResult = -2146233088
-- | --
Here is the exception that occurred:     Type = System.Exception Message =     {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"51ae104a-8c1c-4126-b0ec-b8de5e295678","SiteStatus":1,"SiteUrl":null}     Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at     OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__3.MoveNext() in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     256 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     OfficeDevPnP.Core.Sites.SiteCollection.Create(ClientContext clientContext,     TeamSiteCollectionCreationInformation siteCollectionCreationInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line     43 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     59 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     207 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     360 HResult = -2146233088
=================================

**Comment by andrewconnell** [comment]
You said PNP so I'm guessing this is more of a PNP provisioning issue? If so, can you post it to that project's issue list?
https://github.com/SharePoint/PnP-Sites-Core

If I"m mistaken, can you provide more context? What are you using, what are you doing, version of SharePoint you're targetting, where the code is running, etc.
