### ISSUE TITLE
Webpart within a

### ISSUE THREAD

**Issue by trey-miller** [SharePoint/sp-dev-docs#3899]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

@lucabandMSFT
Hi Luca, per your suggestion to post my question here:

We at LiveTiles are working on the next generation of our LiveTiles Page Designer product, which will be in the form of an SPFx webpart, to target single page apps and Teams tabs as well. We would like to enable reusability of other webparts, so my question is would it be possible to render an SPFx webpart inside of our single webpart app page? This might involve loading a webpart, based on just its manifest and configuration, in a custom way, i.e. into a div container in our custom webpart app page. 

Please let me know if you need more information. 

Thank you!

-Trey Miller

Please

**Comment by andrewconnell** [comment]
Is the question _"can we load a web part within another web part"_ or _"can one web part programatically load another web part in another div"_?

**Comment by patmill** [comment]
And what exactly does this mean "our single webpart app page"?  (Maybe that's related to AC's comment).

**Comment by andrewconnell** [comment]
@patmill It _sounds_ like they are trying to use the FPAP option where a web part (_err... app_) loads another web part on that special page layout... 

#NeedInput 🤖

**Comment by trey-miller** [comment]
Hi, yes I've butchered the terminology apparently. I mean a webpart with the supportedHosts property as "SharePointFullPage" but also potentially "TeamsTab". 

To answer "Is the question "can we load a web part within another web part" or "can one web part programatically load another web part in another div"?"
Yes both of these basically describe my question. If you mean to ask which if these is my question, I would choose the latter, but both basically apply.

**Comment by patmill** [comment]
No, there isn't currently a way to have a webpart load another webpart, at least not in the same div/document.  You could probably have it iFrame a page that has a single webpart host though.
