### ISSUE TITLE
Capture webpart properties event

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#39]
Please let us know how to capture webpart properties event in scripts.

**Comment by patmill** [comment]
Could you clarify a bit what you are looking for?  Do you want to capture the onChange event when a property is changed in the property panel?

if so, take a look here - https://sharepoint.github.io/classes/_sp_client_preview_.baseclientsidewebpart.html#onpropertychange

**Comment by bvdinesh** [comment]
Thank you.

**Comment by patmill** [comment]
Also worth pointing out - in the near future this API will change slightly, with it becoming OnPropertyChanged, and the value passed in being the old value (the new value will already be set on the property, so you can just read it from there).  Expect that in the next one or two drops.
