### ISSUE TITLE
ApplicationCustomizer extension not loading

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-docs#3901]
I created a Site Collection App Catalog and deployed a Custom Application Extension to it. I enabled Tenant Wide deployment when I uploaded the package. 

I also used o365 CLI to run `spo customaction` but the extension is not running in my application. 

Are there other steps I'm missing?

**Comment by andrewconnell** [comment]
Tenant wide deployment only applies to tenant scoped app catalog... if you deployed it to a site collection app catalog, you typically need to install the app within the site collection to get it to work.

You said you use the Office 365 CLI... can you provide more detail on the command you used as in the arguments.

**Comment by patmill** [comment]
Tenant wide deployment _should_ work within a site collection app catalog.  It should be deployed to all the sites in the site collection.  I am aware of some issues around 1st release / targeted release tenants and users and the modern list/library app.  Does your solution work on a modern webpart page?  I'm assuming that a) you deployed it to the site collection app catalog (not just uploaded it) and b) that the site collection app catalog is configured correctly at the tenant level to be a valid app catalog.  Does everything work if you upload a basic "hello world" webpart to your site collection app catalog?

**Comment by patmill** [comment]
@rchendev as an FYI

**Comment by simkessy** [comment]
> a) you deployed it to the site collection app catalog (not just uploaded it) 
I uploaded it, enabled the "Make this solution available on all sites..." and it didn't work. 

The only way I was able to get it working was by running: 

> Add-PnPCustomAction -ClientSideComponentId "8E9FB372-8793-4DFB-936A-54AA5CB4452C" -Name "ga-spfx" -Title "ga-spfx-client-side-solution" -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: '{"trackingID":"ID"}' -Scope site

I saw old blog posts that mention using Powershell but the current documentation does not saying anything about running Add-PnpCustomAction so I'm not sure if that's expected, unnecessary or just missing in the docs.

**Comment by andrewconnell** [comment]
You do not need to use the command line (POSH/O365 CLI) to make an extension work... I'm not familiar with that specific cmdlet, but it's not required.

Setting aside the tenant scoped deployment from a site collection scoped app catalog aspect (as @patmill stated it _should_ work)...

@patmill had a few questions in his reply... you should have seen it listed in the options of "New => App" list of available apps. When you added to the app catalog, assume you clicked DEPLOY? Did the app catalog list show as there were no errors & it was deployed?

**Comment by simkessy** [comment]
Hey Andrew, 

I see this: 

![image](https://user-images.githubusercontent.com/5871660/57471546-35f17200-7240-11e9-8ff7-991140f112ec.png)
![image](https://user-images.githubusercontent.com/5871660/57471603-60dbc600-7240-11e9-8beb-bc5c7eee6154.png)

It was deployed, and there's no errors. 

However, if I go to my sites, I do not see it running in any of them. I added a console.log to check if it was working.

**Comment by andrewconnell** [comment]
According to the v1.8.2 release notes, appears there are issues with extensions that MSFT is tracking down. Curious... is your tenant configured for SR / TR?

**Comment by patmill** [comment]
is it not working on both webpart pages as well as lists/libraries?

**Comment by simkessy** [comment]
@andrewconnell I'm not sure what SR/TR yet. 

@patmill yea I checked the console in a list page and on the home.aspx page in one of my collections. Nothing.

**Comment by andrewconnell** [comment]
@simkessy said
> I'm not sure what SR/TR yet

Sorry... I should have spelled those out. It's the release configuration of your tenant. 
- SR = standard release
- TR = targetted release (you get updates a few weeks before SR gets them)

**Comment by simkessy** [comment]
@andrewconnell we're on the TR. 

Also, I decided to delete the app, and re-upload it but without enabling tenant scope. I then saw the app in my collections, so I added it. However it's still not running. I realized that I don't have my `Tracking ID` set anywhere. Is this something I need to set or activate through powershell? Before I could edit the properties through the Tenant Wide Extension list but now I'm not sure what' the procedure is. 

```
export interface ICfaiGaTenantApplicationCustomizerProperties {
  // This is an example; replace with your own property
  trackingID: string;
}

/** A Custom Action which can be run during execution of a Client Side Application */
export default class CfaiGaTenantApplicationCustomizer extends BaseApplicationCustomizer<
  ICfaiGaTenantApplicationCustomizerProperties
> {
  @override
  public onInit(): Promise<void> {
    let trackingID: string = this.properties.trackingID;
    if (!trackingID) {
      Log.info(LOG_SOURCE, "Tracking ID not provided");
    } else {
      var gtagScript = document.createElement("script");
      gtagScript.type = "text/javascript";
      gtagScript.src = `https://www.googletagmanager.com/gtag/js?id=${trackingID}`;
      gtagScript.async = true;
      document.head.appendChild(gtagScript);

      console.info("GA tenant level set");

      eval(`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());    
        gtag('config',  '${trackingID}');
        `);
    }
    return Promise.resolve();
  }
}

```

**Comment by andrewconnell** [comment]
Hmm... sounds like the previous problem was that the tenant scoped deployment wasn't working when you deployed it to the site collection app catalog...

Typically properties are defined in the element manifest file (**./sharepoint/assets/elements.xml**). These values are set when you install the app. You can also control this via the REST API (via PowerShell / Office 365 CLI).

**Comment by mcmynn83** [comment]
I validated that site collection app catalog tenant wide extensions (which are actually site collection wide extensions) are working.  It sounds like this is an issue with the solution itself and not a product bug.  If you believe otherwise please let me know.

**Comment by simkessy** [comment]
I deployed the application to two other tenants and it seems to be working. I think we're good. Thanks for the help everyone.
