### ISSUE TITLE
Explicitly add references to package.json

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#3905]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I am very happy that in [1.8.2](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8.2-release-notes), "for the react scaffolded projects, we now explicitly add office-ui-fabric-react version 6 to package.json". 

Shouldn't you include in the scaffolding the other two common **shadow references** as well? 
- **tslint**
- **typescript**

As you said, shadow dependencies are a bad thing and including them in the default scaffolding will help to eliminate these shadow dependencies and make easier the use of **pnpm** and **rush**.

#### Observed Behavior
tslint and typescript are common shadow references as they are not in the scaffolded package.json.

#### Steps to Reproduce
Run yo @microsoft/sharepoint and see the package.json

**Comment by patmill** [comment]
Good question @Rafaelki .  In this case, however, the answer is no, and we should probably add some additional documentation around it.  The rush-stack-compiler-x.y package brings in the appropriate typescript and tslist packages, as well as other build tools (webpack, etc.).  The goal here is that for tooling, you include the one package, and we make sure that everything matches correctly and is tested to work together.

**Comment by Rafaelki** [comment]
I see! So basically tslint and typescript are no longer shadow references since rush-stack-compiler was added (1.8.0), right? 
Thank very much @patmill!
