### ISSUE TITLE
SPFx 1.8.2 is missing SPHttpClientBatch

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#3906]
#### Category
- [X] Bug

#### Expected or Desired Behavior
SPHttpClientBatch is not available in 1.8.2.

#### Observed Behavior
index-internal.ts sais:

/* Excluded from this release type: SPHttpClientBatch */

/* Excluded from this release type: SPHttpClientBatchConfiguration */

/* Excluded from this release type: ISPHttpClientBatchConfiguration */

/* Excluded from this release type: ISPHttpClientBatchConfigurations */

/* Excluded from this release type: ISPHttpClientBatchCreationOptions */

/* Excluded from this release type: ISPHttpClientBatchOptions */

#### Steps to Reproduce
try to use SPHttpClientBatch with a project using spfx 1.8.2

**Comment by andrewconnell** [comment]
It's not GA... it's still beta. You need to include the `--plusbeta` flag

**Comment by andrewconnell** [comment]
Ref https://github.com/SharePoint/sp-dev-docs/issues/3829#issuecomment-486348415
