### ISSUE TITLE
Markdown formatting not applied

### ISSUE THREAD

**Issue by Toonshorty** [SharePoint/sp-dev-docs#3907]
References on this (and other) pages that should be rendered bold are showing as **Field**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c7942c-96f6-db0d-6c50-66f228a95e74
* Version Independent ID: 00a32cea-43fb-f437-10bc-ea67e1066685
* Content: [Field element (Field)](https://docs.microsoft.com/en-us/sharepoint/dev/schema/field-element-field#elements-and-attributes)
* Content Source: [docs/schema/field-element-field.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/field-element-field.md)
* Product: **office-online-server**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yup... on my backlog of things to fix... closing as a dupe to #3780
