### ISSUE TITLE
SPFx aadTokenProviderFactory issues token for browser but not for native Sharepoint mobile app

### ISSUE THREAD

**Issue by butchmarshall** [SharePoint/sp-dev-docs#3910]
Using `aadTokenProviderFactory.getTokenProvider().then(tokenProvider => tokenProvider.getToken('https://graph.microsoft.com'))` is working properly in the web browser but hits the failure condition with no error in the native app.

Is this a bug?

**Comment by lucabandMSFT** [comment]
@butchmarshall , can you please check if this is related to #2521 and, if yes, if the instructions provided there solve your issue?

Thanks

**Comment by butchmarshall** [comment]
Nope - it does not seem to fix it, I copied the "appId" from oauth2Permissions, put it into the permissionsId in preAuthorizedApplications... still fails.

**Comment by lucabandMSFT** [comment]
hey @butchmarshall ,do you have an update to share?
