### ISSUE TITLE
Not able to update favicon In IE 11 and Windows 10 Edge Browser using SPFX Extension.

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#3911]
> SPFx-favicon in IE11 and Windows 10 Edge Browser are not updating the favicon
>I have tried to change modern SharePoint sites Favicon using custom sp package.
This code dynamically changes the Favicon in Chrome and Firefox but not in IE11 and Windows 10 Edge Browser
We have used .ico file and have tried all the solution as per
https://stackoverflow.com/questions/122067/favicon-not-working-in-ie?rq=1
https://stackoverflow.com/questions/29404559/how-to-force-ie11-to-request-a-new-favicon/29465098#29465098
Your help will be greatly appreciated.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug

**Comment by patmill** [comment]
I think we saw something similar - but nothing to do with spfx, but rather the favico was just broken.  Do you see any icon?  Additionally, if you look at the source, do you see an unterminated " at the end of the content attribute in the

<meta name="viewport" content="width=device-width, initial-scale=1/>

tag?

**Comment by anomepani** [comment]
I can see only the default IE icon and the viewport meta tag looks as below 
`<meta name="viewport" content="width=device-width,initial-scale=1">`

Weird thing is that I can see the favicon set only in IE Version `11.0.9600.19326`
Can you provide any fix so that it will appear in all IE 11 versions?

**Comment by preetishikhariya** [comment]
I am facing issue with Favicon not displaying on Edge & IE browser but can see on Chrome &  Firefox browser, I have used SPFx app customizer code and below is the code snippet:
 let url: string = this.properties.faviconpath;
    debugger;
	if (!url) {
	  Log.info(LOG_SOURCE, 'Icon URL was not provided.');
	}else{
		var link = document.querySelector("link[rel*='icon']") as HTMLElement || document.createElement('link') as HTMLElement;
		link.setAttribute('type', 'image/x-icon');
		link.setAttribute('rel', 'shortcut icon');
		link.setAttribute('href', url);
		document.getElementsByTagName('head')[0].appendChild(link);
	}
	return Promise.resolve(); 

Can someone please let me know if favicon works on Edge/IE ?

**Comment by VesaJuvonen** [comment]
As Internet Explorer is no longer supported in the Microsoft 365 services, we will be closing this issue. If there are still similar issues on the modern supported browsers, please open up a new issue.
