### ISSUE TITLE
Necessary permissions

### ISSUE THREAD

**Issue by lafe** [SharePoint/sp-dev-docs#3915]
Unfortunately, the page does not list the minimum required permissions for the ALM APIs. It would be great if these permissions could be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins#feedback)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It would be the same permissions required for doing the same operations in the UX. For tenant app catalog, need to have tenant admin rights. For site collection app catalog targets, need to be site collection owner. To install/upgrade/uninstall apps, need to have the correct permissions to do those operations in the UX.

Is that what you're looking for?

**Comment by lafe** [comment]
Yes. Thank you very much for the information!
