### ISSUE TITLE
Hub Navigation Headers are Clickable

### ISSUE THREAD

**Issue by Maher256** [SharePoint/sp-dev-docs#3919]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Hub Navigation elements that are set as "Headers" should not be clickable. 

![Hub Navigation Working](https://user-images.githubusercontent.com/19497918/57469675-2cbed000-7255-11e9-8aba-8c7c828174a4.gif)

#### Observed Behavior

After refreshing the page the Hub Navigation Header elements are clickable and refresh the current page.

![Hub Navigation Not Working](https://user-images.githubusercontent.com/19497918/57469661-24669500-7255-11e9-9f56-14f7fffd0de6.gif)

#### Steps to Reproduce

1. Edit the hub Navigation.
2. Add a new link and select "Header" as the link option.
3. Save the navigation.
4. Refresh the page.

**Comment by lucabandMSFT** [comment]
Thanks a lot for your feedback. We use this channel for developer feedbacks only. 

Please use UserVoice to provide feedbacks on the product to be sure we can properly track those issues in the right place.

**Comment by Maher256** [comment]
Thanks @lucabandMSFT , I will add it over there.
