### ISSUE TITLE
SPFx Framework deleted (or updated in the AppCatalog)

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#392]
#### Category
- [ x] Question
- [ ] Typo
- [x ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I have deployed an SPFx App into the App catalog, and deployed to a site collection.  If I were to *delete* or *update* the app in the app catalog, web parts on the site collections immediately use that version.  I would like to see the app work like traditional apps - the site collection owner has the ability to control what happens to the app on the site.

#### Observed Behavior
When i *delete* the app from the app catalog -- the app no longer functions on the site collection.  We get the error: 
Home.aspx:591 Failed to render client side web part. Id: [2b125755-159d-4799-8210-b091a3d967c3], Manifest: [<NULL>], Error Details:: [Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkException: Web Part 2b125755-159d-4799-8210-b091a3d967c3 failed to render as manifest is not found
   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.GetManifest[TManifest](Guid componentId, String& manifestJson)
   at Microsoft.SharePoint.WebPartPages.ClientSideWebPart.<>c__DisplayClass4.<Render>b__0()
   at Microsoft.SharePoint.ClientSideComponent.SPClientSideFrameworkReliabilityHelper.ExecuteInReliabilityMonitoredScope[TException](Action userCodeDelegate, SPReliabilityMonitor monitor, UInt32 expectedFailureTag, Action`1 customErrorHandlerDelegate, Boolean reThrow)]
cswp_WPQ2 @ Home.aspx:591
(anonymous) @ Home.aspx:594
Home.aspx:592 Web Part framework is not loaded.

#### Steps to Reproduce
Create the Hello World SPFx app and deploy to App Catalog and then Site Collection.  Then delete from the app catalog.  You will get an error when trying to load the page.
 -- or update and you will immediately see the updates in the manifest.

**Comment by manishgarg1** [comment]
Hi @suz7777 , can you please explain what behaviour you expect in detail? This behavior you are experiencing is by design. If you delete the app from the app catalog, the web part will stop rendering.

**Comment by suz7777** [comment]
[issue 392.pdf](https://github.com/SharePoint/sp-dev-docs/files/775066/issue.392.pdf)

see attached
•	Deploy app 1.0 into the app catalog
•	Deploy app 1.0 into 3 site collections (Dev, QA, UAT)
•	Make changes to the app
•	Deploy app 2.0 into the app catalog
•	Activate app 2.0 into site collection dev
•	The app in the remaining 1.0 site collections begins using the 2.0 code NOT the 1.0 code as designed.

**Comment by suz7777** [comment]
We want to do the following:
•	Deploy version 3.0 to DEV site collection
•	Deploy version 2.0 to QA site collections
•	Deploy version 1.0 to UAT/Prod site collections

What we are able to do is the following:
•	Deploy version 3.0 to ALL site collections

**Comment by frankchen76** [comment]
@suz7777, are you using the CDN to host your client JS? if you do, just curious when you deploy different versions, did you manage your JS to have different version on CDN?

**Comment by SanchiKabbina** [comment]
Do we have a solution for this?

**Comment by mpasarin** [comment]
You can use site collection app catalog (for each site collection) to keep the version of your packages separate. 
https://support.office.com/en-us/article/Manage-the-Site-Collection-App-Catalog-928b9b61-a9de-4563-a7d1-6231aa9d4d19

Also you can follow the webcast that explain some more about it: https://www.youtube.com/watch?v=ZfUKkdMnSYQ
