### ISSUE TITLE
Expose IPopupWindowPosition enumeration from sp-property-pane

### ISSUE THREAD

**Issue by pschaeflein** [SharePoint/sp-dev-docs#3924]
#### Category
- [ ] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Property name should match enumeration name

#### Observed Behavior
The IPopupWindowProps interface in sp-property-pane contains a property to specify the position of a popup window. 

The property is named **positionWindowPosition**.

The type is an enumeration named **PopupWindowPosition**.

#### Steps to Reproduce
Review the IPopupWindowProps interface in file: 
   sp-property-pane\lib\propertyPaneFields\propertyPaneLink.d.ts

**Comment by andrewconnell** [comment]
Unclear what the issue is... in JS & TS, non-default types generally are sentence case while properties are camel case. Seems like that's followed here...

**Comment by pschaeflein** [comment]
```
enumerationName.substring(0,5) !=== propertyName.substring(0,5)
       popup                                 position
```

**Comment by andrewconnell** [comment]
I'm sorry... maybe a little dense today, but I'm not clear on what you're saying...

**Comment by pschaeflein** [comment]
I would expect the property name to match, except for casing:

**Popup**WindowPosition    < - enumeration
**position**WindowPosition <- property
^^^^

In other words, what is a positionWindowPosition?  What is a positionWindow?

**Comment by andrewconnell** [comment]
OOOHHHHH... I thought you were logging a bug. Now I see. I'm not sure you're going to see that chance now that the APIs are published... but that's going to fall in the realm of a feature request and as such should go to User Voice: https://aka.ms/sp-dev-uservoice
