### ISSUE TITLE
SharePoint Framework 1.8.1 relies on js-yaml@3.9.1 which has a known security vulnerability

### ISSUE THREAD

**Issue by labbruzzesi** [SharePoint/sp-dev-docs#3925]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

My organization has an internal node package management system.  No code with known security vulnerabilities can be uploaded to that repository.  The following 2 packages in SPFX 1.8.1 rely on js-yaml@3.9.1, which has a known security vulnerability.  Is there any way to get a version that can use js-yaml@3.13.1 so that I can bring it in for use? 

"@microsoft/sp-build-web": "1.8.1",
"@microsoft/sp-webpart-workbench": "1.8.1",

**Comment by grhillmsft** [comment]
This problem remains in 1.8.2. The dependencies on js-yaml@3.7.0, extend@1.2.1 and tar@2.2.1 are also known to be vulnerable and it's causing problems for me.

**Comment by kemesfun** [comment]
This problem was resolved in SharePoint Framework 1.10+. The dependency package has been updated. * now js-yaml@3.13.
