### ISSUE TITLE
Deploy solution packages in the app catalog using REST, Tenant-wide

### ISSUE THREAD

**Issue by tobiaswest83** [SharePoint/sp-dev-docs#3926]
Documentation describes how to do this via PnP-PowerShell, but not via REST. 

To do so, {"skipFeatureDeployment":true} needs to be sent as the body of the request, adding this to the documentation will help clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins#deploy-solution-packages-in-the-app-catalog)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... will get docs updated. Thanks!
