### ISSUE TITLE
Office UI Fabric core styles are not loaded to the page

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3927]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We can use Office UI Fabric Core styles in web parts.
Example:
```typescript
<i className="ms-Icon ms-Icon--Mail" aria-hidden="true"></i>
```
#### Observed Behavior
`ms-Icon` is not presented on the page.
As a result, the icon is not rendered:
![Screen Shot 2019-05-09 at 6 57 31 PM](https://user-images.githubusercontent.com/17036219/57497435-855d8f80-728c-11e9-9a0a-58ea4632a278.png)

#### Steps to Reproduce

1. scaffold default web part
2. add `<i className="ms-Icon ms-Icon--Mail" aria-hidden="true"></i>` somewhere in web part's HTML

The example web part can be found [here](https://github.com/AJIXuMuK/issues/tree/master/ouifr-styles)

**Comment by NickSevens** [comment]
Could be caused by: https://github.com/OfficeDev/office-ui-fabric-react/wiki/using-icons

**Comment by patmill** [comment]
Hey @AJIXuMuK - You are using the really old style (v1.0/v1.1).  If you want to continue to do this in 1.8.2 and beyond, there is a flag you need to put in your webpart manifest - `  "loadLegacyFabricCss": true` .  Note that this will load all the legacy fabric styling, etc., which is about 250k of css (once it is uncompressed).  A better solution would be to use the @uifabric/icons package.  We will update this document shortly with more information on how to do this. - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration
