### ISSUE TITLE
SharePoint native mobile app (iOS), will not allow navigation through menu

### ISSUE THREAD

**Issue by efuertesvalencia** [SharePoint/sp-dev-docs#3929]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
Accessing a SharePoint Online site through the native app in iOS devices (iPhone (6+) and IPad and IPad Air, quick launch menu items other than the home page one will not navigate to the right page and will always navigate to the home page instead.

#### Steps to Reproduce

1. Create several pages through SharePoint Pnp cmdlets using Home as layout type : 
`$homePage = Add-PnPClientSidePage -Name "Home.aspx" -LayoutType Home`
`$otherPage = Add-PnPClientSidePage -Name "Other.aspx" -LayoutType Home`
2. Edit content to differentiate them through the UI.
3. Add them to navigation through SharePoing PnP cmdlets:
`Add-PnPNavigationNode -Title "Home" -Url "/SitePages/Home.aspx" -Location "QuickLaunch"`
`Add-PnPNavigationNode -Title "Home" -Url "/SitePages/Other.aspx" -Location "QuickLaunch"`
4. Set one of them as Home Page:
`Set-PnPHomePage -RootFolderRelativeUrl SitePages/Home.aspx`
5. Open native iOS app (iPhone or iPad) and navigate to site. Home page is shown.
6. Click on the waffle to open navigation menu.
7. Click on the "other" page link.  
8. Home page instead of Other page is shown.

**Comment by andrewconnell** [comment]
Not sure this is a developer topic and thus not really suited for this issue list as there's nothing that can be done here. Might be best to suggest the feedback directly on the app in the iOS AppStore.
