### ISSUE TITLE
Load multiple java script using SPComponentLoader.loadScript

### ISSUE THREAD

**Issue by Shanmugamvasu** [SharePoint/sp-dev-docs#3931]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I am using SPFx 1.8.1. Developed a webaprt for simple report with chart. I placed all js and css files in style library.

Using SPComponentLoader.Loadscript to load the scripts in order like below

`SPComponentLoader.loadScript('https://abcd.sharepoint.com/sites/xyz/Style%20Library/assets/theme/js/min.js', {
      globalExportsName: 'jQuery'
    }).then(() => {
     SPComponentLoader.loadScript('https://abcd.sharepoint.com/sites/xyz/Style%20Library/assets/theme/js/chart.js', {
      globalExportsName: 'jQuery'
    }).then(() => {

 });
});`

Like above i need to load 3-4 js files with dependencies. i hope js files loading properly. 

My issue is,

1. i have two report pages. chart displaying in first page. When i navigate to second report page (all js are same, even data are hard coded) the chart not displaying. Throwing promise error. why this is happening? If i use ctrl + f5 chart is loading in second report page.
2. how to handle promise error to get the actual error
3. How to check the js file is already loaded or not, if not loaded, then only execute the SPComponentLoader.loadscript code

Thanks.

**Comment by wobba** [comment]
This is due to async smart loading. See https://github.com/SharePoint/sp-dev-fx-webparts/blob/5dca7cb216385d4ca6fa7c2a4dd24d6272048b7f/samples/react-script-editor/src/webparts/scriptEditor/ScriptEditorWebPart.ts#L173 for a workaround where I add a new random param to force a reload.

**Comment by Shanmugamvasu** [comment]
Apologies for late reply. Just came back from holidays.

I checked it. It's working now. Thanks @wobba
