### ISSUE TITLE
for the dropdown  "custom tab", how to add icon?

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#3934]
Hi, for the dropdown "custom tab", how to add icon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4245fa14-c317-5a0f-7aba-6569d5cb268d
* Version Independent ID: 2a351a4d-3600-b80a-6ae3-8b1a494d69c7
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-lists-and-libraries)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Look at the snippet in the code in the doc... you'll see the `Button` element has an attribute `Image16by16`
