### ISSUE TITLE
Best way to make a personal document library with a new view 

### ISSUE THREAD

**Issue by falkin** [SharePoint/sp-dev-docs#3937]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

My challenge is to reproduce a view more or less like these one. I must use the basic document library  but with new columns  (for that part it's all good) and with completely new view and news functionalities. And my question is, what is the best way to do that ? I really need to have these view but but i want to keep in maximum all basic functionalities from document library. 

![img232](https://user-images.githubusercontent.com/1089835/57609644-93066400-756f-11e9-9f0f-aa64e598e4f0.png)

Options found :

- Create an extension with SharePoint framework. I don't know if it's possible to do that with an extension. 
- Create an add-in. Well with this way i will loose all basic functionalities from document library.
- Create an external web site connected with SharePoint by API.  Well with this way i will loose all basic functionalities from document library too.
- Another option ?

With classic views and SharePoint on premise, it was possible to edit the page and add or remove the webpart who displays the view for another. Why this option was removed ?

Thank you for your help

**Comment by andrewconnell** [comment]
That picture appears to be a mockup... you're not going to be able to easily create a custom SP list/library view within a list that mirrors that. The tree view nav, the gripper resizing it... that's not going to be possible to implement.

An SPFx extension won't help you with this... it will only help with the rendering of the field columns & buttons in the toolbar.

Your other two points about using external site / add-in are correct... you lose some of the native functionality the SP list/library UX offers. But as I said above, you going to have a very hard time making a list view that looks like that, not to mention it will be hard to maintain.

You're going to have to compromise at some point.

If you want a highly customized interface for the list, consider an SPFx web part that either runs as a web part of full page app part.

I'll share an example: I have a list I use to maintain a newsletter... it contains a list of links. I have multiple capabilities I need to implement like categorizing, renaming titles & descriptions, sorting, etc. All of these things are hard to do in the list UX.

So I created an SPFx web part that runs as a full page app part. That web part gives me the UX I need to perform the tasks I need to do. I still use the list for my data storage, but I don't use the list UX

**Comment by falkin** [comment]
Thank you for your response. It's make sense.... I also thought to do something with the new feature inSP to do single part app pages and a web part. 

But I think it could be very interesting if extension will be more powerful in the future with more functionalities and other placeholder where to use it.  It's inside the pipeline if I remember right but I really agree in the sens.
