### ISSUE TITLE
Getting 404 error while adding the app to Tab

### ISSUE THREAD

**Issue by shwethegde** [SharePoint/sp-dev-docs#3943]
Hi All,

I have followed the steps mentioned above. But Getting error 404 when trying to add the app to the MS Teams apps. If i am not wrong i think "configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=b7771434-9587-4a79-9990-48c310f78a3d%26forceLocale={locale}" 

part is wrong for me in the manifest. However can anyone help me with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Have you (1) deployed the SharePoint Framework package to SharePoint Online, (2) and installed it globally / in the site collection that is backing the SharePoint site? 

This is required as the component must be hosted by SharePoint to be surfaced in MSFT Teams.

If you have, then what's the component ID of your web part?

**Comment by shwethegde** [comment]
Thank you Andrew for your response.
Yes, I have deployed the webpart to sharepoint app catalog as given in the section "Packaging and deploying your web part to SharePoint". 

When you mean component ID do you want the ID which i have in manifest file of the webpart or Product ID which i have in App catalog?

**Comment by andrewconnell** [comment]
@shwethegde said:
> When you mean component ID do you want the ID which i have in manifest file of the webpart or Product ID which i have in App catalog?

The product ID listed in the app catalog is the ID of the package, defined in the **package-solution.json** file. 

The component ID is the ID of the component (web part/extension) found in its manifest file which is typically found in the same folder as the code file for the component.

**Comment by patmill** [comment]
I'll also add - do you need to create a custom manifest because your teams solutions contains extra things (bots, etc.)?  From the app catalog, there should be a "sync to teams" button that will create the manifest and load it into teams for you.

**Comment by shwethegde** [comment]
> I'll also add - do you need to create a custom manifest because your teams solutions contains extra things (bots, etc.)? From the app catalog, there should be a "sync to teams" button that will create the manifest and load it into teams for you.

This also i have tried. Yet, while adding the webpart to tab i get this error.

**Comment by shwethegde** [comment]
> @shwethegde said:
> 
> > When you mean component ID do you want the ID which i have in manifest file of the webpart or Product ID which i have in App catalog?
> 
> The product ID listed in the app catalog is the ID of the package, defined in the **package-solution.json** file.
> 
> The component ID is the ID of the component (web part/extension) found in its manifest file which is typically found in the same folder as the code file for the component.

Component ID: cc4ee9db-e867-4b20-94ae-d998a02fd292

**Comment by andrewconnell** [comment]
@shwethegde said:
> Component ID: cc4ee9db-e867-4b20-94ae-d998a02fd292

There's your problem... look at the URL in your OP. You'll see `componentId=b7771434-9587-4a79-9990-48c310f78a3d`. This is what Teams is using to tell SharePoint to "load this component on the page in the IFRAME in the custom tab". You aren't pointing to the correct component ID.

Refer this doc for details on creating the manifest.json manually:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart
