### ISSUE TITLE
SPFx in Teams: execute deep link

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3945]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

How to execute a deep link to team/channel/whatever from SPFx web part in Teams?
Currently there is a `executeDeepLink` function in MS Teams JavaScript library that works perfectly. But it is marked as **private**.
Are there any other ways to execute deep links?
`window.parent.href` and `window.parent.open` are blocked.

**To make it a bit more generic**
Let's say we have an aggregator tab, that shows all users' teams. And we have a web url for each team.
When user clicks on a team name we want Teams app to open that team.
How to achieve that?

**Comment by andrewconnell** [comment]
Might be more appropriate to ask this question in a Teams JS SDK forum. If that method is marked as private, it's not intended to be used... so not surprising it's not working in an SPFx context.

**Comment by AJIXuMuK** [comment]
I agree about asking regarding the method. 
But I also interested in allowing changing location of parent window. At least between known hosts like `teams.microsoft.com`, `sharepoint.com`, etc.
