### ISSUE TITLE
Missing space in list address suffix for refreshing the page

### ISSUE THREAD

**Issue by piotr-kasprzyk** [SharePoint/sp-dev-docs#3950]
The suffix for the list address in the last line of Page_Load methos should be: "Lists/Local%20Employees/AllItems.aspx" (the space - %20 - was missing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42afced-99c6-19a0-0eb3-5b8dd8a41997
* Version Independent ID: c31e26fb-1751-fb5a-6de0-830eb19fe322
* Content: [Include a custom button in the provider-hosted add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in)
* Content Source: [docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... will get it fixed.
