### ISSUE TITLE
IE11/EDGE: Webparts do not load after navigating from a successfully loaded page containing either an Image or a Custom webpart

### ISSUE THREAD

**Issue by tgorgdotcom** [SharePoint/sp-dev-docs#3952]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After loading a page successfully, clicking on a link to go to another page in sharepoint should cause a successful page load (all webparts visible).

#### Observed Behavior

If you go to another Sharepoint page by a link on a successfully loaded Sharepoint page with either a custom webpart we created, or the built-in image webpart, the new page does not load any webparts, and the following error shows in the console:

```
[object DOMExceptionPrototype]
   {
      ABORT_ERR: 20,
      code: 17,
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "TypeMismatchError",
      name: "TypeMismatchError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   }
sp-pages-assembly_en-us_d6111532b318945247d6da168889789f.js (960,127910)
```

This error shows for every custom or image webpart that was on the original page

#### Steps to Reproduce

1. Create two webpages (can be on the same site collection).  The first page should have one built-in image webpart and one built-in text webpart that contains a link to the second page.  The second page should only have one built-in text webpart.

2. Load the first page by typing it into the browser url box.  

3. After a successful load, click on the link created in the first step.  

4. Profit?? No webparts will load.

**Comment by tgorgdotcom** [comment]
Just to add.  When you're on the page that doesn't load, clicking on another page will work find, then the subsequent page after that will not load.  So it's every even page that doesn't load as long as there's an image web part on the odd page.

**Comment by jonathanhotono** [comment]
@patmill / @VesaJuvonen  sorry, I also got this issue as well on client for edge 15 (yes I know its old but their SOE team needs time to upgrade to latest edge).

**Comment by jonathanhotono** [comment]
Update: it seems that microsoft edge did not support history api well, therefore it is best to override the page routing (history pushstate) and force hard refresh, not great but at least webpart loads.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11373805/

@tgorgdotcom if you need this solution, I have made it available for you to use at own risk. Currently only limited to override Edge 15.
https://github.com/jonathanhotono/spfx-ext-disable-edge-routing

**Comment by lucabandMSFT** [comment]
Hi @tgorgdotcom. we were unable to repro this issue to the latest version of Microsoft Edge that is available on Windows 10 (currently 18.17763).
For this reason I'm closing the issue. if that's not the case please reopen it indicating the platform and the version of the Browser.

**Comment by tgorgdotcom** [comment]
Hello lucabandMSFT.  Note that this doesn't work on IE11, and unfortunately about 50% of our users are still on IE due to several applications requiring it.

**Comment by tgorgdotcom** [comment]
Oh shoot, I forgot to mention I was running Edge 15.15063 on Windows 10 Enterprise 1703!  Sorry about that
