### ISSUE TITLE
Is the File Picker something we can use as well?

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#396]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When adding the Image Gallery webpart to a page (or workbench), you are presented with a File Picker dialog window. Is this something we can (re-)use, or should we create one ourselves if we want to use this kind of behavior?

**Comment by manishgarg1** [comment]
Hi @NickSevens, thank you for the question. At the current time this is not possible. We will evaluate the possibility of this.

**Comment by NickSevens** [comment]
@manishgarg1 thank you for the response. Looking forward to a positive evaluation ;)
