### ISSUE TITLE
Field customizer does not work for a particular user but works for other users.

### ISSUE THREAD

**Issue by arshad815** [SharePoint/sp-dev-docs#3962]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Field customizer to render a React Fabric Primary button has been deployed to the site collection App catalog. It should render a button but it throws a React error for one user. The error from the console is given in the next section. 

#### Observed Behavior
 The same error is shown in IE 11 and Chrome:

spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/spoapp-mini-4c2994d0.js:1 Initialized ClientSideExtensionHelper
spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/spofiles-mini-e28054fa.js:1 Defined clientSidePlaceholders: DialogContainer,Top,Bottom
spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1 Uncaught Error: There is no operation handler registered for '{"operation_301":["getItems_1","spItemThumbnail_493"]}'.
    at e.n (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/spofiles-mini-e28054fa.js:1)
    at new e (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1)
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1
    at dispatch (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1)
    at Object.<anonymous> (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/splist-is-mini-fd87efa7.js:1)
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/listviewdataprefetch-mini-2ad1b140.js:15
    at Object.next (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-05-03-sts_20190508.007/listviewdataprefetch-mini-2ad1b140.js:15)

#### Steps to Reproduce

I have deployed the spfx field customizers for 2 fields which show up in Site columns. Added them to the list and then it works for many users by showing the buttons in the field but for one user, it fails. My code is checked into github at https://github.com/arshad815/spfx-favorite-extension

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Is the one user that fails opted into the first release experience?

**Comment by srideshpande** [comment]
To add to what Pat asked, since when is this happening? Also, what version of react are the other people using? I see that you are using react 16. Can you please confirm?

**Comment by arshad815** [comment]
@patmill I have asked the tenant admin to check the Target release setting for me. 

@srideshpande We do not have any other customization running on the site. This is the only SPFX component, so I guess the version should be the same for all users. I had used the SPFX 1.7 version.

**Comment by arshad815** [comment]
@patmill That was the issue, the user was added to receive targeted releases. After removing the user, everything started working fine. Really appreciate your help.
