### ISSUE TITLE
Incomplete data, and links to dead ends.

### ISSUE THREAD

**Issue by SleepingJay** [SharePoint/sp-dev-docs#3971]
There is no links to where to find namespaces, objects, functions, properties, methods, etc. 

Also, some of the related links inside the "See also" links are dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842f7c06-9642-df05-4ee2-644145ca25ee
* Version Independent ID: 822afabb-9f32-be7d-e9b7-efd791ba7d5d
* Content: [Determine SharePoint REST service endpoint URIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris#feedback)
* Content Source: [docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you suggest where you think there should be links _"to where to find namespaces, objects, functions, properties, methods, etc."_?

I just checked every link in the **See Also** section and every single one worked.
