### ISSUE TITLE
Should Web Ids be unique across tenant?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3972]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web Ids are **unique** across tenant

#### Observed Behavior

Web Ids in different site collections are equal

#### Steps to Reproduce
I'm experiencing the issue with duplicating web ids on my tenant.
All the webs with duplicated ids that I've found were created through new MS Teams team creation.

Example:
```
https://splst.sharepoint.com/sites/SPHub3/_api/web?$select=Id
---
<d:Id m:type="Edm.Guid">f3d0579e-5131-4f7f-a5fe-9f9796c51fe8</d:Id>

https://splst.sharepoint.com/sites/sphub2/_api/web?$select=Id
---
<d:Id m:type="Edm.Guid">f3d0579e-5131-4f7f-a5fe-9f9796c51fe8</d:Id>
```

**Comment by patmill** [comment]
Nope.  There was always a possibility of having web ids match (content deployment, etc.).  There isn't a DB constraint.  The move towards fast site creation makes it more likely.  It _will_ be unique within any given site, but not across sites.

**Comment by AJIXuMuK** [comment]
wow...

Then, cross-site collection search with query like `WebId=""` can return absolutely unpredictable results...

**Comment by patmill** [comment]
That would always be a bug waiting to happen - now it's more obvious.  If you want to target a single one, you'll want site+web

**Comment by AJIXuMuK** [comment]
@patmill - actually there is a weird behavior of search in such scenarios at all :)
I have a search query `(WebId="") AND LastModifiedTime>=date`.

And it returns results from one web only.
If I remove `LastModifiedTime` filter - I will see results from both webs.

If you want me - I can create a separate issue on that.
