### ISSUE TITLE
gulpfile

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [SharePoint/sp-dev-docs#3976]
please include the gulpfile.js configuration code here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f89fed-848e-50b9-6be4-657824ad262e
* Version Independent ID: 3d3c5227-7281-ef49-a2d1-686c0a049497
* Content: [Use Office UI Fabric React components in your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components#feedback)
* Content Source: [docs/spfx/web-parts/get-started/use-fabric-react-components.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/use-fabric-react-components.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There's nothing to add... the `gulpfile.js` that is created by the Yeoman generator for a new SPFx project is all that's needed.

**Comment by evlo** [comment]
https://www.youtube.com/watch?v=RnXD10a-2ww 10:10
