### ISSUE TITLE
Issue with CDN for Theme

### ISSUE THREAD

**Issue by dvinodeluru** [SharePoint/sp-dev-docs#3979]
While referring the CSS from CDN path the background-color: "[theme: themePrimary, default: #0078d7]"; is unable to render, when the CSS is referred from _layouts or Style Library works perfectly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations#feedback)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-theme-colors-in-your-customizations.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by StfBauer** [comment]
What is your target environment?
- SharePoint 2016
- SharePoint 2019
- SharePoint Online

**Comment by dvinodeluru** [comment]
> What is your target environment?
> �
> 
> * SharePoint 2016
>   �- SharePoint 2019
> * SharePoint Online

SharePoint 2013 on-premises  with Azure CDN

**Comment by StfBauer** [comment]
The article you are referring in the initial comment applies only to SharePoint 2019 on Modern Experience pages and SharePoint online.

The article is out of scope for SharePoint 2013 and SharePoint 2016.

**Comment by dvinodeluru** [comment]
Ok, Thank you for your responses, One more how to enable the "Text Styles" to be appear in "Lists" (https://domain.sharepoint.com/sites/content/Lists/Test/NewForm.aspx?Source=) also

![image](https://user-images.githubusercontent.com/2167566/59100697-7da11180-8944-11e9-9461-a2bebdbcb4bc.png)
 
Which works in pages
![image](https://user-images.githubusercontent.com/2167566/59100737-96a9c280-8944-11e9-9b6b-1815510e0d33.png)

**Comment by StfBauer** [comment]
The class name named to be named `.ms-rteStyle-<customSelectorDefinition>`.

You will find more on my blog post from 2011. [Enhance rich text editor using CSS – Part 1](https://n8d.at/blog/enhance-rich-text-editor-using-css-part-1/)
