### ISSUE TITLE
Page is constantly reloading when I add web part on the SharePoint Online

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-docs#398]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I expect that the content of the web part appears when I add it to the SharePoint Online in my dev tenant.

#### Observed Behavior
When I add the web part on the modern page, it starts reloading indefinitely.
When I add it on the wiki page, it shows an error.

#### Steps to Reproduce
1. yo @microsoft/sharepoint
2. selecting React in the wizard
3. gulp trust-dev-cert
4. gulp serve
web part works perfectly on the bench
5. gulp package-solution
6. uploading sppkg file to the app catalog and deploying
7. gulp serve --nobrowser
8. adding app onto some /sites/<sitename> web site.
9. trying to add the web part on a modern page
10. trying to add the web part on a wiki page

![hw2mod](https://cloud.githubusercontent.com/assets/11289124/22487707/798f296a-e81f-11e6-8ff5-2bd6b70b07bb.PNG)

![hw2trad](https://cloud.githubusercontent.com/assets/11289124/22487705/7564b2a6-e81f-11e6-9d5e-3a6fc3fb98b1.PNG)

Thank you in advance

**Comment by dmcrock** [comment]
@shurick81 Same is happening to me. Using RC0

**Comment by patmill** [comment]
Looking into it, thanks.

**Comment by shurick81** [comment]
In the topic, I mentioned bench. What I meant is my local one, https://localhost:4321/temp/workbench.html.

And now I have also tried to add on the SharePoint Online Bench, I get this:
![spfxbench](https://cloud.githubusercontent.com/assets/11289124/22502897/1281edbe-e880-11e6-89a3-f22676b116e4.PNG)

**Comment by shurick81** [comment]
I also checked the server log (gulp) and there seems to be no requests from the page when I add to SharePoint Online, while adding a web part on the local workbench triggers following requests:
  Request: '/dist/hello-world-3.bundle.js'
  Request: '/lib/webparts/helloWorld3/loc/en-us.js'

**Comment by webtechy** [comment]
Hi @shurick81 - did you get to the bottom of this? Webpart is throwing an Uglify/Angualr error in Chrome, but continual page reloads in IE.

**Comment by patmill** [comment]
Just to keep you informed - we're looking into this and a couple other loading issues.  It is our primary focus at the moment.  It's proving tricky.  There are really two issues at play here.  The first is that loading the webpart is generating an error, the second is that the page is refreshing on the error (which then triggers again, etc. etc.)  The 2nd issue has been fixed and should be rolling out to the tenants this week (I think it's currently at 10%).  That should result in only the webpart error itself appearing.  That is something we are investigating.

If you get to just the error showing, can you try this?  
1 - Open the dev console (ctrl-F12 now)
2 - Go to the trace tab
3 - Paste the errors that appear in it?

Thanks, Pat.

**Comment by webtechy** [comment]
@shurick81 It probably can't find the resources as it will still be looking in localhost (unless you are running "gulp serve" whilst also looking at the SP online site). You need to specifically run:

gulp clean
gulp build
gulp bundle --ship
gulp package-solution --ship

Also copy contents to /temp/debug (not /dist) to CDN location specified in write-manifest.json.

**Comment by shurick81** [comment]
Hello Pat,

Thanks for your reply.
I use edge and probably 'console' is that what you meant by 'trace tab'. When I just open a /_layouts/workbench.aspx, before I try to add a web part I get this in the console:
![spfxconsole01](https://cloud.githubusercontent.com/assets/11289124/22586082/ecd67070-ea0b-11e6-9ec7-44e33734ad76.PNG)

At the same time in in the browser area I get this:
![image](https://cloud.githubusercontent.com/assets/11289124/22586097/0e7a562e-ea0c-11e6-807f-df27bbe63ed7.png)

After this, when I add web part itself on the bench, console is not updated at all

As for adding the web part on the modern page, When I create a new page, I get this in console:
![image](https://cloud.githubusercontent.com/assets/11289124/22586264/ca8bdfea-ea0c-11e6-9ae0-8e225976aa01.png)

And when I add the web part on this page, I can see two messages in console after which the navigation is occurring:
![image](https://cloud.githubusercontent.com/assets/11289124/22586408/9d8ddc5e-ea0d-11e6-9c7f-b3aa6d0d90ac.png)


Just for information: before I test anything, I run `gulp serve --nobrowser` so that files are available on my localhost.

**Comment by shurick81** [comment]
Hello Ben,

I run gulp serve --nobrowser everytime so that files are available on my localhost. I am going to try the sequence you suggest, but what do you mean by "write-manifest.json"? I've got HelloWorld3WebPart.manifest.json in my solution and that is its content:

`{
  "entries": [
    {
      "entry": "./lib/webparts/helloWorld3/HelloWorld3WebPart.js",
      "manifest": "./src/webparts/helloWorld3/HelloWorld3WebPart.manifest.json",
      "outputPath": "./dist/hello-world-3.bundle.js"
    }
  ],
  "externals": {},
  "localizedResources": {
    "helloWorld3Strings": "webparts/helloWorld3/loc/{locale}.js"
  }
}
`

**Comment by webtechy** [comment]
You should have a config folder with the weite-manifest.json folder in it.

**Comment by shurick81** [comment]
Thanks, I shouldh've found it before. I will probably try to follow this article then: https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn

I mean when you said copy files to CDN, I think this article would be a good one to follow, right?

**Comment by shurick81** [comment]
I tried another deployment scenario and it worked:

"cdnBasePath": "/siteassets/<projectname>/"
and uploaded files on https://<devtenant>.sharepoint.com/siteassets/<projectname>

So cannot the web part on the SharePoint use js files on my developer machine via https://localhost/...?

**Comment by webtechy** [comment]
Yes it can as long as you "gulp serve" so the node server is running. No good for production though of course.

**Comment by webtechy** [comment]
(For the /siteassets/ location you need to copy the contents of your temp/deploy (not /dist/).

**Comment by shurick81** [comment]
I also expected this to work but it did not work for me for some reasons, as I described earlier. It would be great to understand how can I fix that. It is not that critical since I can use the deployment procedure to site assets, but it would significantly improve my development if I could do it properly. As for the files, yes, I copy from temp/deploy, thanks

**Comment by patmill** [comment]
This should be sorted out now.
