### ISSUE TITLE
Lost code while running gulp serve

### ISSUE THREAD

**Issue by dvinodeluru** [SharePoint/sp-dev-docs#3980]
After adding code as specified getting the error, but not while compiling, after running "gulp serve" pasted code is gone, and .ts change state to initial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Where did you add the code? The command `gulp serve` does not delete *anything*. The only command that deletes stuff is `gulp clean` and that *only* deletes temp files you should not be edited directly in `lib`, `dist` & `temp`.

**Comment by dvinodeluru** [comment]
in src\extensions\helloWorld\HelloWorldApplicationCustomizer.ts file and saved it, when ever i run the "gulp serve" code get removed and came back to initial state of file.

**Comment by andrewconnell** [comment]
That should not happen. Can you record a screencast and post it somewhere reproducing this?

**Comment by dvinodeluru** [comment]
Sure i can do that.

**Comment by dvinodeluru** [comment]
![aftergulpserve](https://user-images.githubusercontent.com/2167566/58023289-148c6200-7b2d-11e9-9dd1-605f29c38e0e.PNG)
![beforegulpserve](https://user-images.githubusercontent.com/2167566/58023290-1524f880-7b2d-11e9-80d8-594b99ec3d77.PNG)
![exected](https://user-images.githubusercontent.com/2167566/58023291-1524f880-7b2d-11e9-99d8-a5a5e1e54547.PNG)

I have attached the images can't make a video, restrictions

**Comment by PopWarner** [comment]
It looks like your making changes to the TypeScript Declaration file, “HelloWorldApplicationCustomizer.d.ts”, which is generated for you. 

You should be editing just the non declaration file, “HelloWorldApplicationCustomizer.ts”.

If you make changes to that and then perform a gulp Serve, do you retain and see your changes? :)
