### ISSUE TITLE
Site Url Rename not working with Powershell

### ISSUE THREAD

**Issue by vtikam** [SharePoint/sp-dev-docs#3981]
I am first connecting to Admin Tenant
Then I'm running the Site Collection Rename command.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The site rename process starts and status become in progress. It may take a while to reflect the changes, but after some time the site gets renamed and old url will also redirect to new site.

#### Observed Behavior

Getting below error-
This site address can't be changed.
It's not supported.

#### Steps to Reproduce
Connecting to Admin Tenant
Connect-SPOService
Provide credentials
Start-SPOSiteRename -Identity *** -NewSiteUrl ****

#### Submission Guidelines
I have installed latest version of SPO Management Shell. SharePointOnlineManagementShell_8812-1200_x64_en-us
What do I need to do in order to enable this feature on my tenant.

**Comment by chanchaljainms** [comment]
Getting the same error.
Start-SPOSiteRename : Error Code: -5,This site address can't be changed.
It's not supported.
At line:1 char:1
+ Start-SPOSiteRename -Identity https://arenapharm.sharepoint.com/sites ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Error Code: -5,This site address can't be changed.
It's not supported.
,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

**Comment by deepikatyagi** [comment]
Same error for me.

**Comment by ashuetawah** [comment]
Same issue  -
1. Powershell version is latest
PS C:\WINDOWS\system32> Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version,Path

Name                                   Version        Path                                                                                                                                        
----                                   -------        ----                                                                                                                                        
Microsoft.Online.SharePoint.PowerShell 16.0.8812.1200 C:\Program Files\WindowsPowerShell\Modules\Microsoft.Online.SharePoint.PowerShell\16.0.8812.1200\Microsoft.Online.SharePoint.PowerShell.psd1

2. Error - 
PS C:\WINDOWS\system32> Start-SPOSiteRename -Identity $nowUrl -NewSiteUrl $newurl
CorrelationId: 1965e09e-70df-8000-4d8d-a0bcb605fd2d
Start-SPOSiteRename : Error Code: -5,This site address can't be changed.
It's not supported.
At line:1 char:1
+ Start-SPOSiteRename -Identity $nowUrl -NewSiteUrl $newurl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Error Code: -5,This site address can't be changed.
It's not supported.
,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

**Comment by Rocket101101** [comment]
Same error for me. Is there any update? 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps

**Comment by andrewconnell** [comment]
Is this a standard / targetted release tenant you're trying this on?

**Comment by andrewconnell** [comment]
Update... I believe while the PowerShell cmdlet has been released, this feature is not yet released / fully deployed across SPO...

**Comment by vtikam** [comment]
> Is this a standard / targetted release tenant you're trying this on?

Currently tenant is in Targeted release for everyone.

**Comment by andrewconnell** [comment]
@vtikam [as I said above](https://github.com/SharePoint/sp-dev-docs/issues/3981#issuecomment-496548069), the feature has not been released / fully rolled out

**Comment by YemiYemi** [comment]
Same here , it is September and I am getting the same error. Any update on this ? 
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Error Code: -5,This site address can't be changed.
It's not supported.
,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

**Comment by elpinto007** [comment]
I received the following error when I ran the command:
`Start-SPOSiteRename : The type initializer for 'Microsoft.Online.SharePoint.PowerShell.TelemetryMonitorAria' threw an
exception.`

Any timeline when this is rolling out?

**Comment by phillippoole** [comment]
Same here:

PS C:\Windows\system32> Start-SPOSiteRename -Identity https://xxxxxxxx.sharepoint.com/sites/01-20021 -NewSiteUrl https://xxxxxxxx.sharepoint.com/sites/01-20074

Confirm
Are you sure you want to perform this action?
This operation will change the URL for site https://xxxxxxxx.sharepoint.com/sites/01-20021 to
https://xxxxxxxx.sharepoint.com/sites/01-20074. Do you want to continue? Y/N
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
CorrelationId: 7067099f-805f-9000-ea3c-f77ae7a521e0
Start-SPOSiteRename : Error Code: -5,This site address can't be changed.
It's not supported.
At line:1 char:1
+ Start-SPOSiteRename -Identity https://xxxxxxxx.sharepoint.com/sites/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Error Code: -5,This site address can't be changed.
It's not supported.
,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

**Comment by munrobasher** [comment]
Ditto here - my clients have been waiting patiently for this. They have hundreds of Office 365 group projects and the project name does change in 5% of cases.

**Comment by galaxyflow** [comment]
Same error. Hope this feature is rolled out soon.

**Comment by ATJSM** [comment]
Any updates?

**Comment by gristy58** [comment]
works now
