### ISSUE TITLE
SPFx Dialog.alert has problems in IE11

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#3982]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
It should be possible to open a Dialog.alert() a second time after it has been closed.

#### Observed Behavior
Using IE11 the Dialog opens when invoked for the first time. When clicking th "OK" Button it closes and an error is thrown in the console. After that, the Dialog.alert() could not be opened again (without any further error messages) until the page is refreshed with F5.
The error (DOMException) in the console when closing the Dialog:
`NotFoundError
   {
      [functions]: ,
      @@hasInstance: undefined,
      @@isConcatSpreadable: undefined,
      @@iterator: undefined,
      @@match: undefined,
      @@replace: undefined,
      @@search: undefined,
      @@species: undefined,
      @@split: undefined,
      @@toPrimitive: undefined,
      @@toStringTag: undefined,
      @@unscopables: undefined,
      __proto__: { },
      ABORT_ERR: 20,
      code: 8,
      constructor: { },
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "NotFoundError",
      name: "NotFoundError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   }`
This is most likely related to issue #3698 because custom dialogs are also only working for the first time they are opened in IE11.

#### Steps to Reproduce
To make sure that nothing else in our solution is generating the problem I created a new Listview Commandset Extension using the standard yeoman generator. SPFx version was 1.8.1.
I created and packaged the bundle (--ship) and uploaded it to a site collection app catalog. 
Installed it to the site and then got the "Command Two" button on every list.
The first click on "Command Two" shows the alert. The second click shows nothing.
It's the unmodified basic code:
`@override
  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
        Dialog.alert(`${this.properties.sampleTextOne}`);
        break;
      case 'COMMAND_2':
        Dialog.alert(`${this.properties.sampleTextTwo}`);
        break;
      default:
        throw new Error('Unknown command');
    }
  }`

Is there anything we can do to get this to work? Upgrading to Office UI fabric V6 would be much work because we are using the SPFx reusable controls in nearly all dialogs. As they are tied to UI fabric V5 we would have to replace all of them with own code.

**Comment by andrewconnell** [comment]
As I said in #3698, there were plenty of known issues with OUIFR v5 related to the dialog that were fixed in v6.
