### ISSUE TITLE
Which versions of SPfx / SharePoint support provision content types and columns?

### ISSUE THREAD

**Issue by softwarecraft** [SharePoint/sp-dev-docs#3983]
I need to deploy some content types and columns in SharePoint 2016 / SPfx v1.1 and I don't have access to full Visual Studio SharePoint tooling. Looking for alternate ways to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets#feedback)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Have you looked at the PnP Provisioning? This would be your best bet in SP2016 as I believe it does work for SP2016: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-framework

**Comment by patmill** [comment]
Also - all versions will allow you to have feature.xml in your solution that will create content types / etc.  The document you refer to shows how to do this.  Are you looking for something specific that isn't listed?

**Comment by mohdmuqtdeer** [comment]
Check SPFX provisioning here

https://sharepoint-data.blogspot.com/2019/04/spfx-provisioning.html
