### ISSUE TITLE
Search Issue with Refinablestrings in Office 365

### ISSUE THREAD

**Issue by jbranders** [SharePoint/sp-dev-docs#3986]
#### Category
- [x] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We have made a solution in SharePoint based on Search queries and display templates.
For some refiners, we using the default RefinableString of SharePoint and attached the crawled property of a column to it. But the value does not appear in the RefinableString so these are empty. Strange behaviour, because on some tenants the solution works but for one tenant not. 
What can I do to check these error or has anyone a solution? 

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Have you seen this @wobba ?

**Comment by wobba** [comment]
You can first try to click "reindex this site", then check the crawl log (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsearchcrawllog?view=sharepoint-ps). If you don't find anything you need to file a support ticket.
