### ISSUE TITLE
Get SP2010 based workflows in SPO

### ISSUE THREAD

**Issue by ashuetawah** [SharePoint/sp-dev-docs#3989]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

>I am trying to reach all workflows listed in SharePoint Online. There can be Nintex workflows, SPD 2013 and 2010 workflows. When I use WorkflowServiceManager(clientContext,Web).GetDeploymentService().EnumerateDefinition(false) never give me the list of SP 2010 based workflows.
But when I do a list.workflowassociations, I only get SP 2010 SPD workflows. 

#### Observed Behavior

> I am not able to get SP 2010 based workflows by using the Deployment service of workflow manager.

**Comment by andrewconnell** [comment]
That’s because SP2010 workflows are not part of the WM platform, rather they are part of the Workflow Foundation platform. Workflow Manager wasn’t adopted by SharePoint until after SP2010.

**Comment by ashuetawah** [comment]
Thanks AC for replying.
I should for formatted it differently. I could get all SP2013 based workflows existence by using WFM API as mentioned. What's straight option (without iterating list.workflowassociation) to list all SP2010 workflows in a web?

**Comment by andrewconnell** [comment]
@ashuetawah said:
> What's straight option (without iterating list.workflowassociation) to list all SP2010 workflows in a web?

You can't... that's the only option.
