### ISSUE TITLE
the app is overwritten when added to the web site

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-docs#399]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I expected that when I create a new project with different name and add the app to the site, it does not overwrite any other apps that I added earlier.

#### Observed Behavior
when I add app on the SharePoint Online site, the previous app is being displaced.

#### Steps to Reproduce
1. Create one project with yeoman. Let's say, the name is "helloworld001".
2. Upload the app to the catalog.
3. add the app on the SharePoint Online web site.
4. Create another project, say "helloworld002".
5. Upload the other app to the catalog.
6. Add it on the same SharePoint Online site.

Afterwards, I cannot see the helloworld001 on the web site anymore. It still available in the app catalog though.

**Comment by shurick81** [comment]
Cannot replicate it anymore, will try later

**Comment by patmill** [comment]
OK, let us know.  That would certainly be a bug.  The same package name - yes it will overwrite.  Different package name - should not.

**Comment by shurick81** [comment]
Yes, I think I had the same package name. My apologies for the false alarm.
