### ISSUE TITLE
Creating list templates when adding SPFx solution. 

### ISSUE THREAD

**Issue by Danielaroc** [SharePoint/sp-dev-docs#3991]
Is there a way to add a list template to a site collection once an SPFx solution is added to the site? Reading through the docs, we can only do these: 

Fields / site columns
Content types
List instances
List instances with custom schema

But I'd like to add a list template to be used with the webpart, so I can create multiple instances of the list for multiple instances of the webpart. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
Not directly... the XML provisioning within a SPFx component only applies to the ones listed the docs. 

You could still solve it though... for instance, from the property pane you could have an admin-like experience that uses one of the various provisioning capabilities (site designs/scripts, PnP provisioning, etc) that your web part kicks off, such as making a call to a Flow that triggers the provisioning.

**Comment by Danielaroc** [comment]
@andrewconnell Thank you for this idea, I haven't thought about doing it from the webpart property pane. 

I saw this post: https://blog.velingeorgiev.com/sharepoint-framework-advanced-assets-provisioning .. it mentions that Custom List and Library Schemas and other assets not mentioned in the docs can be created using the elements.xml file, is this officially supported? 

If it's officially supported, how can I use the schema.xml without an elements.xml file, I mean, to provision a list template, without an instance.

Thanks again @andrewconnell
