### ISSUE TITLE
SPFs Command Set: event.selectedRows empty if default view is 'ByAuthor'

### ISSUE THREAD

**Issue by PhilThome** [SharePoint/sp-dev-docs#3993]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm using the generated template for a List View Command Set, but changed the list registration id to 119 (Page Library):

```
    <CustomAction
      Title="NewsPublisher"
      RegistrationId="119"
      RegistrationType="List"
      Location="ClientSideExtension.ListViewCommandSet"
      ClientSideComponentId="dfa3c6a1-5b2a-49d0-bfa7-868f14363d31"
      ClientSideComponentProperties="{}">
    </CustomAction>
```
There are two commands, one of them is only shown when one item is selected:

```
@override
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
    if (compareOneCommand) {
      // This command should be hidden unless exactly one row is selected.
      compareOneCommand.visible = event.selectedRows.length === 1;
    }
  }
```

When I've tried this with the SitePages-Library the button for COMMAND_1 was not shown (after selecting one item). The default view for this library is 'By Author' which is a grouped view. When I've selected another view, the button was shown (after selecting one item). Switching back to 'By Author' then worked fine. 
I've then changed the default view to 'All Pages' or 'Created by me' (I have German labels, I'm not sure if these are the correct English ones). With these views the button works as expected. 

Debugging showed that the event.selectedRows is [] in the line shown above, when the default view is 'By Author' and the opened URL is '/sites/pth59/SitePages/Forms/ByAuthor.aspx' without url parameters.

#### Observed Behavior

The observed behavior should be the same in all views. 

#### Steps to Reproduce

- Create ListViewCommandSet-Extension by running yo @microsoft/sharepoint
- change RegistrationId
- build, bundle, package deploy
- open SitePages
- select one element

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Can you share some context, like SPFx version, SharePoint environment (SP19/SPO) & browser(s) you’ve tested this in?

**Comment by patmill** [comment]
And if the user or the tenant is in targeted release.

**Comment by PhilThome** [comment]
SPFx-Version: @microsoft/sp-core-library@1.8.2
TypeScript: 2.9.2
SharePoint Version: SPO
Browsers: Edge 44, Chrome74

The tenant is in Targeted Release for Everyone

**Comment by ahackettms** [comment]
This issue is fixed and you should see the change in the next 3 weeks. Thanks
