### ISSUE TITLE
SPFX property pane controls : How to make ChoiceGroupOptions multi-select ?

### ISSUE THREAD

**Issue by Amysno** [SharePoint/sp-dev-docs#3994]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I would like to reproduce the behavior of the "Highlighted content" WebPart, when it comes to select which scope (or site) we want to select the content from. like in this property pane screenshot : 
![image](https://user-images.githubusercontent.com/5112089/58032373-c4100700-7b22-11e9-8155-8909f293c3a5.png)

I am using ChoiceGroup (with IChoiceGroupOptions) as a Property pane's custom control.

Nowhere in the documentation it is stated that the ChoiceGroup can be multi-select, even if it is recommended for options from 2 to 7 items display.
Checkboxes are not "grouped", and are treated one by one.
Dropdowns are not multi-select either (and not user-friendly with loading few items at a time). 

So, could you explain to me how I could do a multi-select with radio buttons?
I know it could be possible with Checkboxes, but I would like to group the results. I don't really see how I could construct a whole custom control with Checkboxes (or by using a IList?)

#### Observed Behavior

With choiceGroup and IChoiceGroupOptions, I can not select several options at a time.

#### Steps to Reproduce

Create a custom component, as shown in the doc, but instead of AsyncDropdown and IDropdownOptions, create a AsyncChoiceGroup with IChoiceGroupOptions.

Thanks a lot for the time you will be taking.
I hope I am clear with what I'm looking for.

 Sharing is caring.

**Comment by andrewconnell** [comment]
The OOTB choice group control doens’t support multi-select. You can see the options here: https://docs.microsoft.com/en-us/javascript/api/sp-webpart-base/ipropertypanechoicegroupoption?view=sp-typescript-latest

For the screenshot you referenced, you’re probably looking at a custom property pane control. But check this out... it’s a multi-select option from an source library of controls by PnP:
https://sharepoint.github.io/sp-dev-fx-property-controls/controls/PropertyFieldMultiSelect/
