### ISSUE TITLE
Consume enterprise APIs secured with Azure AD in SharePoint FrameworkL The Code is Outdated for Later Versions

### ISSUE THREAD

**Issue by clohigh** [SharePoint/sp-dev-docs#3995]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

For the API and SPFX code to not be outdated.

#### Observed Behavior

I observed that the code is out of date and needs to be updated.

#### Steps to Reproduce

I just wanted to call out that I got this example working, but I'm unsure where to put the updated code at.

@waldekmastykarz  @VesaJuvonen

**Comment by patmill** [comment]
Not sure which document you are referring to, but normally there is an "edit" command in the top right that should take you to github.  From there, you can update the docs and issue a pull request.

**Comment by andrewconnell** [comment]
As @patmill said, please refer to the doc (link) where there's an issue, or comment on the actual doc using the comments feature at the bottom of the document. Also, if you feel specific code is outdated, please reference which snippet... 

IOW, help us help resolve the issue :)
