### ISSUE TITLE
Autoprefixer and Browserslist is outdate and CSS Grid support missing

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#3996]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Autoprefixer should only support actually supported browser and fallback CSS grid layout syntax.

#### Observed Behavior

In the following file the CSS autoprefixer browser support is defined:
/node_modules/@microsoft/gulp-core-build-sass/lib/SassTask.js

<img width="644" alt="Screenshot 2019-05-20 at 21 49 36" src="https://user-images.githubusercontent.com/5503835/58047759-2ed43900-7b49-11e9-89b2-3f5f149caf74.png">

This definition means that from a CSS side of things even IE10 would be supported.
[https://browserl.ist/?q=%3E+1%25%2Clast+2+versions%2Cie+%3E%3D+10](https://browserl.ist/?q=%3E+1%25%2Clast+2+versions%2Cie+%3E%3D+10)

Which is as I know not the case anymore a better option would be to use the following browser support definition:

```js
"> 1%","last 2 versions","ie > 11","not dead"
```

In addition, CSS grid is already supported in IE11 (with vendor-specific prefixes).
https://caniuse.com/#feat=css-grid

To support this in SPFx an additional setting is required so the overall configuration should look like this. So the overall configuration should look like this:

```js
{
  grid: true,
  browsers: ["> 1%","last 2 versions","ie > 11","not dead"]
}
```

The current version used as the autoprefixer is "~9.1.3". This is the first version for CSS Grid included according to my research.
https://css-tricks.com/css-grid-in-ie-duplicate-area-names-now-supported/#article-header-id-11

**Comment by KevinTCoughlin** [comment]
@StfBauer this PR merged yesterday should allow the configuration of `autoprefixer` - https://github.com/microsoft/rushstack/pull/1891. We also updated the associated dependencies. You can override the SASS build task configuration using `mergeConfig` API.

cc: @andrewconnell @lucabandMSFT

**Comment by andrewconnell** [comment]
Tagging as fixed next drop as it will assume to take effect in SPFx v1.11...

**Comment by KevinTCoughlin** [comment]
> Tagging as fixed next drop as it will assume to take effect in SPFx v1.11...

Yes, it should be included cc: @lucabandMSFT @johnguy0. We see significant savings by eliminating outdated vendor prefixes and want the community to benefit also.

**Comment by StfBauer** [comment]
@KevinTCoughlin so I can configure everything in package.json or via config file?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin so I can configure everything in package.json or via config file?

Via SassTask config: https://github.com/microsoft/rushstack/blob/83001f419e191098e5137e047f5cbe478dc7de1d/core-build/gulp-core-build-sass/src/SassTask.ts#L80. Which we intentionally made configurable in https://github.com/microsoft/rushstack/pull/1891.

There are multiple reported issues in this one issue which makes it difficult to close. I recommend a single issue per GitHub issue. If this is still open because you want the browserlist tweaked further and grid support enabled please raise a PR modifying this LoC: https://github.com/microsoft/rushstack/blob/83001f419e191098e5137e047f5cbe478dc7de1d/core-build/gulp-core-build-sass/src/SassTask.ts#L104

**Comment by VesaJuvonen** [comment]
Seems that this issue has been closed and concluded. If there's any related issues still, please open a new issue for helping us to track things. Thanks.
