### ISSUE TITLE
SPFx javascript errors

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-docs#3998]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
Hello,
I get this error when executing my solution that contains 7 webparts, but just on the customer side , in my side everything works as expected.
"Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '@-moz-keyframes animation_do0sdn{from{opacity:0;}to{opacity:1;}}'.
Any suggestions please?

**Comment by patmill** [comment]
Is this running on classic or modern pages?  Also, does this break the page, or just trace something to the console?  SPO or on-prem?  Which browser / version are you using vs. your customer?

**Comment by FullStackRafik** [comment]
Hello,
Is this running on classic or modern pages?
Classic page.
Also, does this break the page, or just trace something to the console? 
Console.
SPO or on-prem? 
SP 2016 On-Premises.
Which browser / version are you using vs. your customer?
Me: Google Chrome: 70.0.3538 
Customer: Google Chrome 70.0.3626

Thanks for your response.

**Comment by andrewconnell** [comment]
Isn't the `@-moz-*` used for Mozilla CSS extensions? If so, it would make sense to be failing in Chrome... so not really an issue.

Have you tested with FF?

**Comment by FullStackRafik** [comment]
Have you tested with FF? Yes, no problems

Which version of SFPx? 1.1.0

Which SharePoint environment? SP2016 On-Premises.


Thanks

**Comment by andrewconnell** [comment]
You mention SP2016 & that it works in your env but not in the customer env... by chance does the customer not have SP2016 feature pack 2 installed? Sounds like something is different between the two environments...

If not, can you share some of the code for the simplest web part that's triggering the error?

**Comment by FullStackRafik** [comment]
The issue is not related to SP2016, but to Google Chrome, it works in my env (Without SP2016 installed but just from Browser), and not in the customer env(I meant Google Chrome), so the issue has nothing to do with SP versions but it's about Google Chrome version, in addition to that There is no probleme using Edge for example.

**Comment by andrewconnell** [comment]
OK, so I understand now that you are saying SPFx v1.1.0 is throwing this error in Chrome but not in Edge. 

I'm not able to reproduce this with a default SP2016 web part using SPFx v1.1.0 on my side... can you please provide a repro?
