### ISSUE TITLE
Currently Windows exclusive but no support for Mac, Linux and Bash On Windows

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4]
Currently the new SharePoint Framework is Windows exclusive. The problem is caused when a file system is case-sensitive and not case-aware like Windows.

Got the following error message:
<img width="1058" alt="screen shot 2016-08-17 at 22 29 26" src="https://cloud.githubusercontent.com/assets/5503835/17754090/338c217c-64d3-11e6-8524-8cd63eeee432.png">

Currently it cannot reproduced on Bash for Windows because there is yet an unresolved issue with Yeoman generators.
To fix this issue you need to take care of correct written file names in all references.
Checked it on a partition that is case-insensitive and Yeoman generator is working perfectly.

**Comment by patmill** [comment]
Nick has a fix for this.  It should roll in the next drop.  We have people developing on Macs though.  Are you running Linux, or a file system on the mac that is case sensitive?

**Comment by nickpape-msft** [comment]
Hey, we just fixed this issue. A temporary workaround would be updating the casing of the imports.

In both `@microsoft/sp-client-base/lib/index.d.ts`, change:

`./odataTypes/IOdataNavigationNodeCollection` => `./odataTypes/IODataNavigationNodeCollection`

`./odataTypes/IOdataWeb` => `./odataTypes/IODataWeb`

In `@microsoft/sp-client-preview/lib/local/bundles/platform-exports.d.ts`:

`../clientSideWebParts/propertyPane/propertyPaneFields/propertyPaneDropDown/IPropertyPaneDropdown` => `../clientSideWebParts/propertyPane/propertyPaneFields/propertyPaneDropdown/IPropertyPaneDropdown`

`../clientSideWebParts/propertyPane/propertyPaneFields/propertyPaneDropDown/PropertyPaneDropDown` => `../clientSideWebParts/propertyPane/propertyPaneFields/propertyPaneDropdown/PropertyPaneDropdown`

`../clientSideWebParts/propertyPane/propertyPaneFields/PropertyPaneTextField/PropertyPaneTextField` => `../clientSideWebParts/propertyPane/propertyPaneFields/propertyPaneTextField/PropertyPaneTextField`

Thanks!

**Comment by StfBauer** [comment]
Great will try this. The Bash On Windows issue I'm referring to is https://github.com/Microsoft/BashOnWindows/issues/468

You might add a comment just in case someone like to use it this way.

**Comment by StfBauer** [comment]
@nickpape-msft Workaround works. Updated the files in the project after it have been provisioned it and got it running.

**Comment by StfBauer** [comment]
Sorry too fast. Just reopend it because it is not fixed in generator. Sorry.

**Comment by chakkaradeep** [comment]
Added the issue of node-gyp rebuild here in the [known issues](https://github.com/SharePoint/sp-dev-docs/wiki/Known-issues). Basically, you can ignore this as the bufferutil dependency uses JavaScript fallback if MSBUILD is not available, though it still outputs the error.

**Comment by StfBauer** [comment]
@chakkaradeep I my case it wasn't related to node-gyp. It was only related to case sensitive file systems. Most MacOS X installations don't have it anymore. Some still use (ok mostly web developers) it because the do regular web projects too and deploy it to Apache Web Server.
It is a big helper to get your file names right for any platform.

**Comment by chakkaradeep** [comment]
@StfBauer updated the [doc](https://github.com/SharePoint/sp-dev-docs/wiki/Known-issues) with the workaround for the case sensitive file bug. Thanks!

**Comment by StfBauer** [comment]
Intermediate fix. ;) 

All that needs to be done is to copy it over the @microsoft in node_modules.
It contains only the two affected node modules.

[@microsoft.zip](https://github.com/SharePoint/sp-dev-docs/files/437340/microsoft.zip)

**Comment by nickpape-msft** [comment]
This has been fixed in the lastest drop.
