### ISSUE TITLE
Cannot install framework - fails at Yeoman SharePoint Generator step

### ISSUE THREAD

**Issue by CalamityLorenzo** [SharePoint/sp-dev-docs#40]
Running this command from the wiki:
npm i -g @microsoft/generator-sharepoint 
fails. Log file pasted below.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   '@microsoft/generator-sharepoint',
1 verbose cli   '--no-optional' ]
2 info using npm@1.4.9
3 info using node@v5.10.1
4 verbose cache add [ '@microsoft/generator-sharepoint', null ]
5 verbose cache add name=undefined spec="@microsoft/generator-sharepoint" args=["@microsoft/generator-sharepoint",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@microsoft/generator-sharepoint',
6 verbose parsed url   path: '@microsoft/generator-sharepoint',
6 verbose parsed url   href: '@microsoft/generator-sharepoint' }
7 verbose cache add name="" spec="microsoft/generator-sharepoint" args=["","microsoft/generator-sharepoint"]
8 verbose parsed url Url {
8 verbose parsed url   protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'microsoft/generator-sharepoint',
8 verbose parsed url   path: 'microsoft/generator-sharepoint',
8 verbose parsed url   href: 'microsoft/generator-sharepoint' }
9 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
10 verbose lock microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\8e76695a-microsoft-generator-sharepoint.lock
11 info maybeGithub Attempting microsoft/generator-sharepoint from git://github.com/microsoft/generator-sharepoint
12 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
13 verbose lock git://github.com/microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\171b9617-m-microsoft-generator-sharepoint.lock
14 verbose addRemoteGit [ 'git://github.com/microsoft/generator-sharepoint', 'master' ]
15 warn `git config --get remote.origin.url` returned wrong result (git://github.com/microsoft/generator-sharepoint) https://github.com/CalamityLorenzo/IamgeekSpoConfig.git
16 verbose git clone git://github.com/microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\Paul\AppData\Roaming\npm-cache\_git-remotes\git-github-com-microsoft-generator-sharepoint-171b9617'...
16 verbose git clone git://github.com/microsoft/generator-sharepoint fatal: remote error:
16 verbose git clone git://github.com/microsoft/generator-sharepoint   Repository not found.
17 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
18 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
19 info maybeGithub Attempting microsoft/generator-sharepoint from git+ssh://git@github.com:microsoft/generator-sharepoint
20 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
21 verbose lock git@github.com:microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\7880b29f-m-microsoft-generator-sharepoint.lock
22 verbose addRemoteGit [ 'git@github.com:microsoft/generator-sharepoint', 'master' ]
23 warn `git config --get remote.origin.url` returned wrong result (git@github.com:microsoft/generator-sharepoint) https://github.com/CalamityLorenzo/IamgeekSpoConfig.git
24 error git clone git@github.com:microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\Paul\AppData\Roaming\npm-cache\_git-remotes\git-github-com-microsoft-generator-sharepoint-7880b29f'...
24 error git clone git@github.com:microsoft/generator-sharepoint Host key verification failed.
24 error git clone git@github.com:microsoft/generator-sharepoint fatal: Could not read from remote repository.
24 error git clone git@github.com:microsoft/generator-sharepoint
24 error git clone git@github.com:microsoft/generator-sharepoint Please make sure you have the correct access rights
24 error git clone git@github.com:microsoft/generator-sharepoint and the repository exists.
25 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
26 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
27 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
28 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
29 error addLocal Could not install microsoft/generator-sharepoint
30 error Error: ENOENT: no such file or directory, stat 'D:\code\microsoft\generator-sharepoint'
30 error     at Error (native)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 10.0.10586
33 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@microsoft/generator-sharepoint" "--no-optional"
34 error cwd D:\code
35 error node -v v5.10.1
36 error npm -v 1.4.9
37 error path D:\code\microsoft\generator-sharepoint
38 error syscall stat
39 error code ENOENT
40 error errno -4058
41 verbose exit [ -4058, true ]

**Comment by StfBauer** [comment]
First you are running on the wrong NodeJS Version.
```35 error node -v v5.10.1```
The line above means you are running on v5.10.1 and which is not a LTS version of NodeJS.
The version you need to have is 4.5.1. - https://nodejs.org/en/download/
Detailed information on this can be found in the documentation too:
[Set up your Machine](https://github.com/SharePoint/sp-dev-docs/wiki/Setup-your-machine)

**Comment by CalamityLorenzo** [comment]
I have both installed, but hadn't sorted out my PATH.
Anyway deleted them both reinstalled the nodejs-lts, same problem.
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   '@microsoft/generator-sharepoint' ]
2 info using npm@1.4.9
3 info using node@v4.5.0
4 verbose cache add [ '@microsoft/generator-sharepoint', null ]
5 verbose cache add name=undefined spec="@microsoft/generator-sharepoint" args=["@microsoft/generator-sharepoint",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@microsoft/generator-sharepoint',
6 verbose parsed url   path: '@microsoft/generator-sharepoint',
6 verbose parsed url   href: '@microsoft/generator-sharepoint' }
7 verbose cache add name="" spec="microsoft/generator-sharepoint" args=["","microsoft/generator-sharepoint"]
8 verbose parsed url Url {
8 verbose parsed url   protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'microsoft/generator-sharepoint',
8 verbose parsed url   path: 'microsoft/generator-sharepoint',
8 verbose parsed url   href: 'microsoft/generator-sharepoint' }
9 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
10 verbose lock microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\8e76695a-microsoft-generator-sharepoint.lock
11 info maybeGithub Attempting microsoft/generator-sharepoint from git://github.com/microsoft/generator-sharepoint
12 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
13 verbose lock git://github.com/microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\171b9617-m-microsoft-generator-sharepoint.lock
14 verbose addRemoteGit [ 'git://github.com/microsoft/generator-sharepoint', 'master' ]
15 warn `git config --get remote.origin.url` returned wrong result (git://github.com/microsoft/generator-sharepoint) https://github.com/CalamityLorenzo/IamgeekSpoConfig.git
16 verbose git clone git://github.com/microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\Paul\AppData\Roaming\npm-cache\_git-remotes\git-github-com-microsoft-generator-sharepoint-171b9617'...
16 verbose git clone git://github.com/microsoft/generator-sharepoint bash: /dev/tty: No such device or address
16 verbose git clone git://github.com/microsoft/generator-sharepoint error: failed to execute prompt script (exit code 1)
16 verbose git clone git://github.com/microsoft/generator-sharepoint fatal: could not read Username for 'https://github.com': Invalid argument
17 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
18 silly lockFile 171b9617-m-microsoft-generator-sharepoint git://github.com/microsoft/generator-sharepoint
19 info maybeGithub Attempting microsoft/generator-sharepoint from git+ssh://git@github.com:microsoft/generator-sharepoint
20 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
21 verbose lock git@github.com:microsoft/generator-sharepoint C:\Users\Paul\AppData\Roaming\npm-cache\7880b29f-m-microsoft-generator-sharepoint.lock
22 verbose addRemoteGit [ 'git@github.com:microsoft/generator-sharepoint', 'master' ]
23 warn `git config --get remote.origin.url` returned wrong result (git@github.com:microsoft/generator-sharepoint) https://github.com/CalamityLorenzo/IamgeekSpoConfig.git
24 error git clone git@github.com:microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\Paul\AppData\Roaming\npm-cache\_git-remotes\git-github-com-microsoft-generator-sharepoint-7880b29f'...
24 error git clone git@github.com:microsoft/generator-sharepoint Host key verification failed.
24 error git clone git@github.com:microsoft/generator-sharepoint fatal: Could not read from remote repository.
24 error git clone git@github.com:microsoft/generator-sharepoint
24 error git clone git@github.com:microsoft/generator-sharepoint Please make sure you have the correct access rights
24 error git clone git@github.com:microsoft/generator-sharepoint and the repository exists.
25 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
26 silly lockFile 7880b29f-m-microsoft-generator-sharepoint git@github.com:microsoft/generator-sharepoint
27 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
28 silly lockFile 8e76695a-microsoft-generator-sharepoint microsoft/generator-sharepoint
29 error addLocal Could not install microsoft/generator-sharepoint
30 error Error: ENOENT: no such file or directory, stat 'C:\Users\Paul\microsoft\generator-sharepoint'
30 error     at Error (native)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 10.0.10586
33 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@microsoft/generator-sharepoint"
34 error cwd C:\Users\Paul
35 error node -v v4.5.0
36 error npm -v 1.4.9
37 error path C:\Users\Paul\microsoft\generator-sharepoint
38 error syscall stat
39 error code ENOENT
40 error errno -4058
41 verbose exit [ -4058, true ]

**Comment by StfBauer** [comment]
If you have both installed then maybe thats the problem. You can only have both installed when you use a tool such as [NVM (Node Version Manager)](https://github.com/creationix/nvm).
There is a special [Node Version Manager](https://github.com/coreybutler/nvm-windows) especially for Windows too.

Otherwise you are a bit out of luck, when you have both installed on the same machine. Those scripts make sure that the current Node Version is referenced everywheren and also helps to switch between the Versions.

**Comment by CalamityLorenzo** [comment]
Second line of the the previous comment, 
I've already removed them both, and reinstalled just the lts version, which you can see in the log is the version being executed.
In the log where it appears to go wrong is in these lines 
24 error git clone git@github.com:microsoft/generator-sharepoint Cloning into bare repository 'C:\Users\Paul\AppData\Roaming\npm-cache_git-remotes\git-github-com-microsoft-generator-sharepoint-7880b29f'...
24 error git clone git@github.com:microsoft/generator-sharepoint Host key verification failed.
24 error git clone git@github.com:microsoft/generator-sharepoint fatal: Could not read from remote repository.
It seems more likely that I have an issue with git config?

**Comment by StfBauer** [comment]
Have you configured git with these commands?
```
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
```

Replace the one with your values.
In additon you can cofigure git to use https instead of git://.
This can be done by the following command:
```
git config --global url."https://".insteadOf git://
```
If you like to narrow it down to just use https:// on github you can do this:
```
git config --global url."https://github.com".insteadOf git://github.com
```
Not sure if last config works with this generator.

**Comment by CalamityLorenzo** [comment]
I've tried again on a different (linux) machine, and I get the same result,  I cannot access the git@github.com:microsoft/generator-sharepoint repo. (via https or git)

**Comment by chakkaradeep** [comment]
We do not have the generator source code published. It is only available as a NPM package. So you will need to se NPM install command.

What are you looking for?

**Comment by StfBauer** [comment]
All packages will be cloned from github repositoryies and NPM packages need to point to a available repository.

**Comment by CalamityLorenzo** [comment]
Finally got it working, the problem (on windows at least) was Chocolatey (See the second row in the logs).
It's version of npm superseded whatever should have been used. 
I'm guessing this is a PATH hierarchy issue as NVM didn't help here.
