### ISSUE TITLE
SPFx Web Part(s) Not Available on Modern Page

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#400]
I have created a new SPFx web part solution, it has now successfully deployed.

However, I note that when I deploy and it prompts me to trust it, the URL is blank when it says it will get resources from that URL. I can successfully add the app to a developer site collection (with First Release enabled). When I go to add the web part to a modern page, it is not listed however.

My **prepare-deploy.json** is as follows:

`{
  "deployCdnPath": "https://[somecompany].sharepoint.com/sites/Development/SiteAssets/[somefolder]/"
}`

My **write-manifests.json** is as follows:

`{
  "cdnBasePath": "https://[somecompany].sharepoint.com/sites/Development/SiteAssets/[somefolder]/"
}`

I can confirm that the assets have been successfully deployed to the SiteAssets folder.

#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

**Comment by amishra0909** [comment]
Thanks for the feedback, we are investigating this issue.

**Comment by patmill** [comment]
Doing old-issue maintenance.  Is this still an issue?

**Comment by spdevdocs** [comment]
Closing as no response.
