### ISSUE TITLE
Icon colour on listviewcommandset

### ISSUE THREAD

**Issue by wills01** [SharePoint/sp-dev-docs#4001]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

When using custom icon on Listviewcommandset, is there a way for it to pick up the theme colour, at the moment i'm using base64.

json

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/command-set-extension-manifest.schema.json",

  "id": "81a9c4f5-8ea8-4b6a-b6e0-0d42aca6d8b4",
  "alias": "OfsDmsCommandSet",
  "componentType": "Extension",
  "extensionType": "ListViewCommandSet",
  "version": "*",
  "manifestVersion": 2,
  "requiresCustomScript": false,
  "items": {
    "COMMAND_1": {
      "title": { "default": "Submit" },
      "iconImageUrl": "data:image/png;base64,etc...…..",
      "type": "command"
    }
  }
}

Thanks for your contribution! Sharing is caring.

**Comment by lucabandMSFT** [comment]
Hello @wills01. No, today that is not possible as you are using the IconImageUrl property. 
One option would be to pick up the right icon at runtime and change it when the color theme changes. But that would be custom code you would have to add to your solution as the framework doesn't give you the ability to provide an array of values that you can pick up at runtime for that properties.
