### ISSUE TITLE
This topic is a duplicate, please redirect

### ISSUE THREAD

**Issue by kelleyvice-msft** [SharePoint/sp-dev-docs#4002]
This topic is a duplicate of the original version of https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo, which has been broadly updated and expanded with updated guidance and procedures. I would recommend redirecting to the updated topic. Please review and let me know if you have any questions.

- Kelley Vice

**Comment by patmill** [comment]
Sorry @kelleyvice-msft  - not sure which page you are referring to.  Can you link to the page that is showing older data?

**Comment by kelleyvice-msft** [comment]
Sorry! I thought the page was included already. I'm referring to https://docs.microsoft.com/en-us/sharepoint/dev/general-development/office-365-cdn.
