### ISSUE TITLE
Create app site catalog - updates needed

### ISSUE THREAD

**Issue by calebmil** [SharePoint/sp-dev-docs#4007]
With the rollout of the new admin center, updated steps are needed for how to set up an app catalog even if it just means adding a new step saying "Click on the Classic SharePoint Admin Center link"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037842f6-772f-456d-6f44-0c46939bcddd
* Version Independent ID: 608ab68a-92a1-ca34-5ce6-2ae71691f6e6
* Content: [Set up your Office 365 tenant](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant#feedback)
* Content Source: [docs/spfx/set-up-your-developer-tenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks & good catch... will get this updated.

**Comment by safayatzisan** [comment]
I can't find _Classic SharePoint Admin Center_ in **SharePoint Admin Center**

**Comment by andrewconnell** [comment]
Looks like things changed a bit... I just updated the doc... will take a day or few to get it live on the site, but you can see the new version here until then: https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md
