### ISSUE TITLE
Issue After Removing Web Part with "Gulp Package-Solution"

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#401]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Expected to remove the webpart/[webpartname] and the entry for that web part from the config/config.json directory, then run "gulp build" and "gulp package-solution" and the web part could be added to the App Catalog (I removed it as I had forgotten to change the ID in the manifest and it was causing issues even after I changed the GUID so decided to just remove and re-add it later properly using the yo @microsoft/sharepoint rather than manually as before). It would be expected that the package-solution command should remove (or clear the folder and regenerate removed web part manifests - see resolution below).

#### Observed Behavior
You get an error with the GUID of the web part you just removed. Such as:

There were errors when validating the App part configuration xml for part ''''/feature_ggaa6a0e-9eba-40a0-bec5-226d1db53cah.xml.config.xml''''.: Xml Validation Exception: ''''The ''''http://schemas.microsoft.com/sharepoint/2012/app/partconfiguration:Id'''' element is invalid - The value ''''ggaa6a0e-9eba-40a0-bec5-226d1db53cah'''' is invalid according to its datatype ''''http://schemas.microsoft.com/sharepoint/2012/app/partconfiguration:GUID'''' - The Pattern constraint failed.'''' on line ''''1'''', position ''''171''''.

#### Steps to Reproduce
Add a web part (with duplicate GUID of another web part) to the solution, package, remove web part, re-package, add to catalog.

#### Temporary resolution
Delete the contents of the "/sharepoint/solution" folder.
Delete the contents of the "/temp" folder.
Delete the file with matching GUID, "[GUID].manifest.json" from the "/dist" folder.
Run "gulp build" and the "gulp package-solution".

**Comment by nickpape-msft** [comment]
Hi @webtechy,

You are correct that the package-solution command is ignoring the contents of your `config.json` file. It determines which manifests to include in the SPPKG by analyzing your `dist/` or `deploy/` folder (depending on if you are using `--ship` flag or not). I've raised an issue in our internal tracking system to resolve this issue, by having the `package-solution` command respect the `config.json`.

The temporary resolution you have is correct. The recommended mitigation is to run `gulp clean` before building and re-packaging the solution.

Thanks for bringing the issue to our attention.

**Comment by webtechy** [comment]
There's definitely an issue here, as for example I updated the **config/write-manifests.json** at 20:08 with:

`{
  "cdnBasePath": "https://grantthorntondev.sharepoint.com/sites/Development/SiteAssets/GrantThornton/"
}`

And then ran "gulp build" and "gulp package-solution". However, if I go back and look at **dist/[webpart-guid].maifest.json**, it has a timestamp of a few minutes earlier, and the contents is:

    "internalModuleBaseUrls": [
      "https://localhost:4321/"
    ],

(I presume this is pulled from the config). I thought I had tried the Gulp Clean (didn't at first as README.md says it's still to be implemented) but maybe not at that point. "Gulp Clean" certainly seems to delete the /dist/ folder, after which you must re-run "gulp build" and "gulp bundle" (regenerates the "/dist/" folder), however, it seems unless you go "gulp bundle --ship" it will leave localhost in there. However, if I use "gulp bundle --ship" I am faced with a new error of:

`[23:22:28] Error - [webpack] 'dist':
requirements-form.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (Def) [./~/source-map-loader!./~/sp-pnp-js/l
ib/pnp.js:43,0]`

**Comment by venkatkonjeti** [comment]
I am started getting this issue after I install the latest build yesterday. The given cdnBasePath is getting updated to the "internalModuleBaseUrls" variable in the bundled JS file in the "./temp/deploy" folder which is generating after running "gulp bundle --ship" command but in the WebPart XML file in the .sppkg file still referring to "https://localhost:4321/".

I see the packge.json change from my old solution to the new one. The new one has updates the devdependencies section as follows
`"@microsoft/sp-build-web": "~1.0.1"`

**Comment by chakkaradeep** [comment]
@webtechy the _package-solution_ command is intended to only package and not compile, build and bundle components. Developers can also have their own custom gulp tasks. The _package-solution_ is not an uber command to execute all of those tasks. 

In your scenario: 

_Add a web part (with duplicate GUID of another web part) to the solution, package, remove web part, re-package, add to catalog._

I see that you are missing the step to build the project after modifying your project which is a critical step before the components are packaged for distribution. The steps I would recommend to execute are as follows:

1. gulp clean
2. gulp bundle --ship
3. <any other custom gulp tasks>
4. gulp package-solution --ship

The _--ship_ command is the one that takes configuration for CDN deployment. If you do not input the _--ship_ command, the tools will build for debugging which today is supported from the localhost. Hence, you see the localhost in the manifest.

Please try executing the gulp tasks above. And if you are not debugging and want to build and package for distribution, use the _--ship_ flag. 

I am closing this issue for now. Please feel to open a new issue for any other specific errors you get.

Thanks,
Chaks
