### ISSUE TITLE
Error in API management "Host name in property identifierUris is not on any verified domain of the company or its subdomain."

### ISSUE THREAD

**Issue by roberAlb** [SharePoint/sp-dev-docs#4011]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm deploying a SPFx web part which needs to use the Graph API and when I go to the API management panel I expect to see the request to be approved or denied.

#### Observed Behavior

Instead of a request when I go to the API management panel I'm getting this error

[HTTP]:500 - [CorrelationId]:7214df9e-80b0-8000-8316-c766bf3e9d57 [Version]:16.0.0.8908 - Host name in property identifierUris is not on any verified domain of the company or its subdomain.

#### Steps to Reproduce

I'm using the 1.8.2 SPFx version but I saw it for other versions as well.

**Comment by andrewconnell** [comment]
Can you provide additional details... what does the JSON look like in the permission request?

**Comment by roberAlb** [comment]
Hi Andrew,

Thanks for coming back.

the permissions that I'm requesting are:

"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.Read"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      }
    ]

**Comment by roberAlb** [comment]
More information:I have tested it in a new tenant and it works as expected, the request is appearing in the API Management portal to be accepted or rejected.

**Comment by andrewconnell** [comment]
Have you tried granting the scope to the tenant via PowerShell / Office 365 CLI? I've noticed errors with that Admin API management page and understanding it's been addressed...
