### ISSUE TITLE
Language issue when navigating between sites with different languages

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#4012]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When working on a multi-lingual environment, we have multiple hub sites which are created for specific languages. Only one language is enabled for these language-specific hub sites. What I noticed is, when you navigate from a Dutch site to an English site, the UI language remains in that of the previous site.

![language-ootb-navigation](https://user-images.githubusercontent.com/2900833/58173514-dceff800-7c9b-11e9-9ca1-e0e3e8897277.gif)

It would be great if the navigation handler sees these kinds of differences between languages and does a full page load instead of a partial load.

#### Steps to Reproduce

- Create an EN site
- Disable all other languages (/_layouts/15/muisetng.aspx)
- Create an NL site
- Disable all other languages
- Create a link on the navigation bar on both site, to make navigating easier
- Start on EN and go to the NL site, you will see that everything is still EN

**Comment by patmill** [comment]
Thanks Elio.  I assume that this is running plain SharePoint code, correct?  In other words, there isn't any custom code at play here.

**Comment by estruyf** [comment]
@patmill indeed, this is done on two out of the box sites without any customizations.

**Comment by lucabandMSFT** [comment]
so.. this is a good product feedback and I will absolutely pass that to the right team.
However, you guys know that we can only handle development related issues here.. which is why I'm closing this issue.
But, again, rest ensured that I'm passing the feedback to the right team.
