### ISSUE TITLE
SPFx Command set extension not visible in Image Library

### ISSUE THREAD

**Issue by Rameishvaghela** [SharePoint/sp-dev-docs#4014]
#### Category
- [x ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

#### Expected or Desired Behavior
It should show command action in image library.

#### Observed Behavior

I have created a SPFx Extension with command bar action and deployed it. however it shows only in the custom list , not showing in the document library or image library. 
I have added the list templated id in element.xml and in ClientSideInstace.xml file.

#### Steps to Reproduce

1.Deployed package to app catalog
2.Go to the library it should show the command bar action in image library or document library

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
What ID are you using?

**Comment by Divyeshkotadia** [comment]
> What ID are you using?

109 - Picture Library

Please let me know if you have any workaround for this issue. Thanks

**Comment by Divyeshkotadia** [comment]
@andrewconnell can you please provide me some guidance ? Thank you...

**Comment by Carolinavv** [comment]
`Title="ExtensionTitle"
        RegistrationId="109"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"`

**Comment by Carolinavv** [comment]
`Title="MyExtension`
` RegistrationId="109"`
 `RegistrationType="List"`
 `Location="ClientSideExtension.ListViewCommandSet.CommandBar"`
