### ISSUE TITLE
Mapping configuration issue

### ISSUE THREAD

**Issue by ManuMora9** [SharePoint/sp-dev-docs#4015]
I'm trying to migrate a classic page to modern experience. In the classic page, I have two zones, one occupies two-thirds, and the other, one-thirds. I'm trying to migrate it using a xml mapping file, in which I set the first zone "column" propertie to 1, and the second zone to 2 and 3, but when I migrate it, the layout it's two equal columns, instead of the two-thirds/one-thirds that I expected. I also tried to set the first zone "column" propertie to 2 and the second one to 3 but the result it's the same. 

This is the XML code that I'm talking about:

`<WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Order="1" Row="1" Column="1">
          <Property Name="Text" Type="string" />
        </Field>
      </WebParts>`
`<WebPartZones>
        <WebPartZone ZoneIndex="2" Order="2" ZoneId="g_3EABBA081F5C47FCBEE3A54DE44829EA" Row="1" Column="3" />
      </WebPartZones>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e4e027-ceb5-5e46-9b68-f09344d5ef20
* Version Independent ID: e6479d50-7e92-62de-49b4-23fcc697803e
* Content: [Transform classic pages to modern client-side pages using PowerShell](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell)
* Content Source: [docs/transform/modernize-userinterface-site-pages-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages-powershell.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
As the top of the document states, this would be best to be submitted => https://github.com/SharePoint/sp-dev-modernization/issues
