### ISSUE TITLE
missing CommentSolid in the Office UI Fabric Icons

### ISSUE THREAD

**Issue by rychlym** [SharePoint/sp-dev-docs#4017]
Please excuse me, I am not sure where to ask, so I am using this channel.

It seems to me to be highly convenient to add the Comment Solid icon to the  Office UI Fabric Icons. 
Customers often would like to see  the count of likes and the count of comment in a blog post item.  The solid variants of the icons would be suitable for that . The "Like" icon (and lot of other icons) already have its "solid" counterpart (the most near is the "Chat" icon).
The enclosed picture shows, what I mean...
![blog](https://user-images.githubusercontent.com/11144487/58230751-83d4a280-7d35-11e9-839d-8f4a0792e9e4.png)

Can you,please, provide the icon in the near future?
(Or at least, would you know which Unicode character could be reserved for it in the future?)

**Comment by rychlym** [comment]
In a tech detail: creation of that icon based on the original seems to be quite simple to do - just removing the second border line and set the lines for the apostrophe symbol counter-wise - tried using the [FontForge](https://fontforge.github.io/en-US/) tool first time :) )

**Comment by andrewconnell** [comment]
Thanks for the submission, but this should go to the team & repo that owns the Office UI Fabric: https://github.com/OfficeDev/office-ui-fabric-core. 

This repo/issue list is for general sp-dev issues...
