### ISSUE TITLE
How to open specific property pane page (cfr. Image Gallery webpart)

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#402]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
In the _Image Gallery webpart_, when editing an image you added to the page, the _property pane_ opens with options to configure the selected image.

I can't find however how to open a specific property pane page from code, and also how to hide the "special" configuration pages from the webpart panel itself.

**Comment by chakkaradeep** [comment]
You can use this method to open the property pane, say on a button click:

```js
this.context.propertypane.open();
```

**Comment by NickSevens** [comment]
@chakkaradeep thank you but that's not entirely what I meant.
In the Image Webpart provided in the o365 tenant, when clicking the edit button of an image, a specific pane opens to edit the selected image's properties.
Also, when editing the webpart itself, those "image property"-pages are not available (as in no paging controls at the bottom).

**Comment by chakkaradeep** [comment]
@NickSevens There is no magic there. Based on the context, relevant controls and properties are rendered in the property pane.

**Comment by NickSevens** [comment]
Ah, that's indeed less magic than I expected :)
Thanks for the help @chakkaradeep
