### ISSUE TITLE
Not able to search WebParts if provided searchablePropertyNames in manifest

### ISSUE THREAD

**Issue by user546** [SharePoint/sp-dev-docs#4021]
#### Category
- [ ] Question

#### Expected or Desired Behavior

should return sites containing WebParts if provided WebPart property value in search according to properties which are set in manifest under searchablePropertyNames

#### Observed Behavior

Not getting sites containing webparts

#### Steps to Reproduce

just add WebPart properties under searchablePropertyNames which are searchable in WebPart manifest file.

Please provide any steps to resolve issue or any documentation to understand the procedure and I am using only manifest approach instead of coding approach (like using protected get propertiesMetadata()) to make WebParts searchable. Thanks

**Comment by patmill** [comment]
The content in the field should wind up in the search index.  What is your expectation for what can be searched / how it can be searched?

**Comment by user546** [comment]
If I search with webpart title in the search box, I should get the page where the web part was added or location of the webpart as search result
