### ISSUE TITLE
Deployment Failed - Inconsistent issue 

### ISSUE THREAD

**Issue by loflet** [SharePoint/sp-dev-docs#4022]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The SPFx Package should be deployed successfully everytime on the Site Collection App Catalog.

#### Observed Behavior
The package deployment is failing with error as "Deployment Failed. Correlation id - {GUID}

#### Steps to Reproduce
Inconsistent issue, not able to reproduce every time. This is what I am trying to find as what is causing this issue. The things I do: -
1. Check if the site collection has the app catalog or not. If it doesn't then create one. 
2. Add the package to the app catalog.
3. Upload the sppkg file using AppManager.Deploy passing the AppMetaData which I added in Step 2.

Result -
1. The package will be deployed successfully sometimes and sometimes it won't. When the deployment fails we get the error message as "Deployment Failed. Correlation id - {Guid}" 

#### Issue Details
I am facing the package deployment failed issue. The issue is not at all consistent in my scenario. This is what I am doing: -
I am uploading a sppkg file in the site collection app catalog using OfficeDevPnP. My function is suppose to upload the same package to 5 different site collection app catalog. Out of the 5 site collection it is uploading to 2 or 3 site collection. Each time it is failing for one or many site collection. The same package if I try to upload again deploys successfully sometimes and sometimes it doesn't.

Not able to understand what is causing this issue. Following are my details: -
![image](https://user-images.githubusercontent.com/7891707/58268951-16ac2600-7da4-11e9-93bf-f4469d9fa37b.png)

SPPKG File link - https://gofile.io/?c=oRhq8f

Thanks,
Sanket

CC: @patmill #3358

**Comment by patmill** [comment]
It looks like you are getting conflicting updates.  From the logs, it looks like uploading a package ultimately (several layers down the call stack) updates a single web.  Is it possible that you are trying to upload the packages in parallel?  Can you switch it to serial?

**Comment by loflet** [comment]
Yes I am executing this in parallel. All the execution is happening for different sites. So I have 5 different sites. For each site the package is getting uploaded. Out of these 5 sites any site fails. Do you still want me to execute the upload of the package to these different sites in serial?

**Comment by loflet** [comment]
Hello @patmill, thank you for your suggestion. I have implemented serial upload of the package to these site collections and it seems to work. I have tested with around 9 deployments and it worked.
I will be testing with around 20 more deployments to make sure it work. Will share more update soon.

Can you help me to understand how parallel execution caused this issue?

**Comment by loflet** [comment]
I can confirm now that this works although I am curious to know what part is causing this issue. @patmill
