### ISSUE TITLE
Not able to display search result in .net web application (hosted in Azure Environment) from online SharePoint using modern authentication.

### ISSUE THREAD

**Issue by santhmon** [SharePoint/sp-dev-docs#4023]
#### Category
- [x] Question

Hi All, 
  
We have an asp.net application and it is integrated with Online SharePoint (displaying a search results using legacy authentication). We are planning to block the legacy authentication in our online SharePoint tenant. I tried the SharePoint add-ins but search (KQL) method getting error and I saw one blogs , it is mentioned that Client ID need to create, provide tenant level permission to get search result. Instead of giving tenant level permission, please let me know is there any other method / model is available to get search result in .net application using modern authentication.

**Comment by andrewconnell** [comment]
I believe you can use delegated permissions to call the SharePoint Search REST API... is that correct @wobba?

@santhmon when you say "modern auth", you're referring to the add-in model that leverages Azure AD applications. More info here: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints#add-ins-that-use-oauth-must-pass-access-tokens-in-requests

**Comment by wobba** [comment]
If you use delegated permissions against SharePoint with the `Sites.Search.All` scope (ADAL) set it should work, or using `http://sharepoint/search | QueryAsUserIgnoreAppPrincipal` as an add-in scope.

**Comment by santhmon** [comment]
Hi @wobba  and @andrewconnell ,

Thanks for the update , I have registered new application in Azure active directory and provided the delegated permissions against SharePoint with the Sites.Search.All for that App ID (API Permission Grant admin consent for Domain).  Created the client secrets for that app id. 

I used the App (Client ) ID and Client secrets in my .net code using OfficeDevPnP.Core.AuthenticationManager  , GetAppOnlyAuthenticatedContext method , getting access denied error in ExecuteQuery. 

then , i provided the full control access to that app ID in Specific SharePoint Site collection appinv.aspx page , able to get clientContext but getting access denied error while executing KeywordQuery , searchExecutor.

Please let me know if i missed any steps or do i need to use different approach to get search result in specific Site collection (we need to give permission to specific site collection to get search results and we should not provide access to entire tenant level).

Currently we are displaying a specific site collection search results using service account legacy authentication.  As per the Microsoft recommendation, we are planning to block the legacy authentication in our online SharePoint tenant and we are working for update our authentication code in .net application , facing above issue in following options. 

1.Azure App id (Delegate, Application)
2.REST (HttpWebResponse error because of Proxy)
3.SharePoint App id  

Need your help please.

Thanks,

**Comment by wobba** [comment]
@santhmon As you are using app-only. Have you also added the needed certificate? Certificate is needed for CSOM and app-only. Take a look at my updated docs on https://github.com/SharePoint/PnP-PowerShell/tree/master/Samples/SharePoint.ConnectUsingAppPermissions which uses PowerShell, but still the same, and it uses the authmanager to load the cert.
