### ISSUE TITLE
Office UI Fabric not loaded with SharePoint 2016 | SPFx

### ISSUE THREAD

**Issue by DMZ011** [SharePoint/sp-dev-docs#4024]
I am not sure if this is the right place to ask this question. But I have sharepoint 2016, and i am trying to load the property panel of spfx webpart, however it's loaded without fabric icons. For example the Back and Next buttons look like this:

![image](https://user-images.githubusercontent.com/42124517/58288642-3af70b00-7d82-11e9-9e38-1be7ed7aec9b.png)

Is there a way to force UI fabric to load for the webpart or do I need to do it as an external link? I already have these folders in my project:

![image](https://user-images.githubusercontent.com/42124517/58288656-41858280-7d82-11e9-8362-59bced30377c.png)

**Comment by andrewconnell** [comment]
A few questions:
- Is this a default web part project you've created? If not can you share some of the code you've editted?
- Are NONE of the icons working?
- Have you verified the icons load in the SPFx local workbench or is it just SP2016?
- Can you verify the version of SPFx you're using?
- Can you verify the version of OUIF you're using (see `package.json`)
