### ISSUE TITLE
Error while granting permissions in SharePoint API Management

### ISSUE THREAD

**Issue by Narendra1224** [SharePoint/sp-dev-docs#4028]
I deployed SharePoint Framework Extension to the app catalog and then permissions need to be granted by API Management in SharePoint admin center. But it is giving an  error 
HTTP]:500 - Internal Server Error [CorrelationId]:bfa8df9e-90b8-0000-2b43-8498f1a491e6 [Version]:16.0.0.8915 - Unknown Error
Please help me to solve the issue

Thanks in Advance
![Spfx error](https://user-images.githubusercontent.com/50985220/58317095-9e298180-7e04-11e9-8483-52029eb90d7d.png)

**Comment by waldekmastykarz** [comment]
There are no pending permission requests in the list. Have you removed them by any chance? Also, have you tried looking at the browser dev tools console to see if you can see any more details about what is going on?

**Comment by Narendra1224** [comment]
I have deployed my SharePoint framework solution for the first time in this tenant. When I came across through the API Management section in the tenant it is showing the errors. I haven't removed any permission from the list. Attaching the screenshot of browser dev tools console logs.
![image](https://user-images.githubusercontent.com/50985220/58396703-74be5f00-806b-11e9-9e11-a42942424af0.png)
![logs](https://user-images.githubusercontent.com/50985220/58396832-ebf3f300-806b-11e9-95c1-e5ec7d24768f.PNG)

**Comment by andrewconnell** [comment]
Can you share what permissions you're requesting? IOW, what's the `webApiPermissionRequests` property within **package-solution.json**?

Also, what version of SPFx are you using?

**Comment by Narendra1224** [comment]
Thanks @andrewconnell 
Sharing the permissions which are declared in package-solution.json and using the SPFx version 1.6.0.
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.Send"
              
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.Read"

      }
      
    ]

**Comment by andrewconnell** [comment]
Have you tried granting the permission via PowerShell / Office 365 CLI?

**Comment by Narendra1224** [comment]
Yes, I have tried granting permissions via PowerShell and O365 CLI also but it gave an error as Unknown error.

**Comment by andrewconnell** [comment]
What command did you use to grant the permission with PowerShell / Office 365 CLI?

Just for kicks, have you checked your tenant's Azure AD apps to see if the special one for SPO is listed?

**Comment by Narendra1224** [comment]
I tried this Get-SPOTenantServicePrincipalPermissionRequests command for getting the pending permission it gave me error as Unknown error. I also tried this Approve-SPOTenantServicePrincipalPermissionRequest command it gave me the same error.

I have gone through tenant's Azure AD app, I found this app 
![image](https://user-images.githubusercontent.com/50985220/58791776-75796700-8610-11e9-9cc4-dac7982cb3b0.png)

**Comment by andrewconnell** [comment]
Can't tell if that's the correct AAD app because the name is cut off, but it should be "SharePoint Online Client Extensibility Web Application Principal". Yours might be that...

Assuming you are logged in as a global tenant admin, something seems wrong in your tenant. You may need to open a support ticket with Office 365 through the Admin portal...

**Comment by Narendra1224** [comment]
The AAD app is the correct one 
![image](https://user-images.githubusercontent.com/50985220/58801844-53d8a980-8629-11e9-876c-f2d6fa0ae9c7.png)
I will open a support ticket with Office365 through Admin Portal  

Thanks, @andrewconnell  for helping me 

Can you please help me  on this issue https://github.com/SharePoint/sp-dev-docs/issues/4046

**Comment by andrewconnell** [comment]
Please don't cross-reference unrelated issues. Will address issues where I can help / have value to add :)

**Comment by Narendra1224** [comment]
Sorry @andrewconnell  for the inconvenience
