### ISSUE TITLE
troubleshoot 'Something Went Wrong' error

### ISSUE THREAD

**Issue by mohitcreative** [SharePoint/sp-dev-docs#4029]
[How can I troubeshoot what is the error in my Ekements.XML or Shcema.XML file. My files have grown in size now and its difficult to find the error by spot checking the syntax. Does SharePoint provides us what the issue is in my files? I tried to open the hyperlink against the app that show error, but it is blank ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets#feedback)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
If you go to the app catalog list, you should be able to change the view to show the error column.  Is there anything displayed there?
