### ISSUE TITLE
Unable to install SPFx app to Teams in GCC tenant

### ISSUE THREAD

**Issue by JayBerg44** [SharePoint/sp-dev-docs#4032]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I should be able to install an SPFx app in MS Teams on a GCC tenant.  I looked through all of the documentation I could find to see if this is supported, but wasn't able to find anything to confirm or deny.

##### Sync to Teams

After installing a Teams Tab supported app in the tenant App Catalog and clicking the **Sync to Teams** button in the ribbon, I receive a **Failed to sync solution to teams** message.  

Here's the response via dev tools:

`POST <My Tenant App Catalog>/_api/web/tenantappcatalog/SyncSolutionToTeams 400 (Bad Request)`

If I dig into the response, I can see that it is actually returning a 403 - Forbidden: 

`{"error":{"code":"-1, System.Net.WebException","message":{"lang":"en-US","value":"The remote server returned an error: (403) Forbidden."}}}`

##### Teams App Catalog

I also tried installing the app directly via the Teams App Catalog, but was not able to access this in the GCC tenant.  I tried to both whitelist my app in the Admin Center and toggle the setting to allow the ability to sideload apps, but was not able to do so successfully.

#### Steps to Reproduce

- Create an SPFx app with "TeamsTab" as a supported host, must be version 1.8(?) or above.
- Deploy to tenant app catalog in GCC tenant.
- Attempt to sync app to Teams.

**Comment by patmill** [comment]
This seems like an issue with Teams and GCC.  Let me see if I can find someone to chime in.

**Comment by lucabandMSFT** [comment]
Teams LoB app catalog should be available in GCC tenants. Do you have the right permissions on Teams? The error above seems more related to a permission issue.
