### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by nambrose** [SharePoint/sp-dev-docs#4034]
The gGoal =&gt; The goal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e9cccb-0bd3-9747-08ff-407bc32cb1f1
* Version Independent ID: 951bca4c-e9a7-fb2d-49a8-ccb29444cb94
* Content: [OneDrive for Business and SharePoint Online Migration API – Encryption](https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-encryption#feedback)
* Content Source: [docs/apis/migration-api-encryption.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/migration-api-encryption.md)
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by thechriskent** [comment]
Thanks for spotting this!
