### ISSUE TITLE
Removed org news site still returned among configured org news sites

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#4035]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After removing an org news site, it's no longer listed among the configured news sites.

#### Observed Behavior

After removing an org news site, it's intermittently being returned as one of the configured org news sites. This happens for a minute or two after removing the site. After a few mins, the site is no longer returned. This could indicate that some time is required to propagate the change but it would still be an issue in provisioning scenarios where there is no reliable way of telling if the particular site is an org news site or not.

#### Steps to Reproduce

- Mark a site as an org news site using the `Set-SPOOrgNewsSite` cmdlet
- Verify that the site is configured using the `Get-SPOOrgNewsSite` cmdlet
- Remove the org news site using the `Remove-SPOOrgNewsSite` cmdlet
- Execute the `Get-SPOOrgNewsSite` cmdlet a few times. Sometimes the removed site will still show up in the list of configured org news sites.

**Comment by VesaJuvonen** [comment]
As this is not a dev issue, we cannot unfortunately process this issue through this channel. Sorry for the inconvenience.  These kind of non-dev issues should be reported either through Premier Support or through Tenant admin support request tooling. Sorry for the inconvenience.
