### ISSUE TITLE
unexpected  behavior  with  command Set extension with any   lists in sitecollection  where i add my on!!1

### ISSUE THREAD

**Issue by heshambadawy** [SharePoint/sp-dev-docs#4038]
i  make  a  command list  to  do some  functionality in lists  both two  command work   fine as  expected and  doing   their   functionality   well  
![command](https://user-images.githubusercontent.com/13408250/58379790-bc2fe700-7fa8-11e9-92f0-3b1990c5225c.PNG)

i  conditionally  add  my  custom  scripts and any js/css library 
`public onInit(): Promise<void> {
    if(location.pathname=="/sites/any/Lists/mylistname/AllItems.aspx"){
   // SPComponentLoader.
       .    .......
    }`

  and  add  condition  on "onInit" method 
`public  constructor() {
    
    super();
    if(location.pathname=="/sites/any/Lists/mylistname/AllItems.aspx"){
    .........
     `
 when  i  add  my app  to  the  site collection  the "ADD , Edit nor delete" of  ordinary  sharepoint
  list  are  worked  and  get  those error  in console

Uncaught (in promise) Error
    at t [as constructor] (listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:77)
    at new t (listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:374)
    at Function.e.buildErrorWithVerboseLog (listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:374)
    at Function.e.buildLoadPathDependencyError (listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:374)
    at listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:374
    at listview-host-assembly_default_cf771226529558ef869fe66cba018dd5.js:374

**Comment by thechriskent** [comment]
Please provide more information such as the version of SPFx you are using, where you are developing this extension (online or SP2019), behavior you expect, additional details about your code, etc.

We're happy to help but we need more detail to identify the issue. Thanks!
