### ISSUE TITLE
SPFx 1.8.2 local workbench error in IE11

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#4039]
#### Category
- [X] Bug

#### Expected or Desired Behavior
I expect the local workbench to work in IE 11

#### Observed Behavior
The local workbench fails in IE 11:
```
SCRIPT1053: Const must be initialized
workbenchInit.js (10,21)

SCRIPT5007: Object expected
sp-loader-assembly_default.js (5190,13)
```
![182-localworkbench-IE11](https://user-images.githubusercontent.com/9973962/58384085-03849a80-7fde-11e9-93b5-691fe63229dc.PNG)

Side remark: hosted workbench currently still works.

#### Steps to Reproduce
1. Create a solution with SPFx 1.8.2
2. Run `gulp serve`
3. Open local workbench in IE 11

#### Preliminary analysis
workbenchInit.js uses `for..of` loops (with `const`) which isn't supported in IE11:
```
for (const manifest of manifests) {
    manifestIds.push(manifest.id.toUpperCase());
}
```
See: https://kangax.github.io/compat-table/es6/

**Comment by andrewconnell** [comment]
Have you reviewed the recently published supported browsers docs here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Pay special attention to the IE11 node for the modern experience & IE's document mode.

If you continue to have the issue, please comment back with some additional context. Thanks!

**Comment by YannickRe** [comment]
I checked it again with SPFx 1.9.1 and made sure the IE 11 document mode was set correctly, but it still doesn't work.

I create a new SPFx 1.9.1 project, select webpart and no javascript framework (basically I hit enter until the project is ready). I run gulp serve, it opens in Chrome without issue. I then open https://localhost:5432/workbench in IE11. The screen stays blank and the errors from my original post show in the console. 

Not sure what additional context you'd like?

**Comment by euvin3582** [comment]
Any fix for this?

**Comment by YannickRe** [comment]
@andrewconnell While running through the list of issues, I think this ticket might be a duplicate of #2892 I'm sorry, maybe we can merge or close this?

**Comment by andrewconnell** [comment]
Yup... good eye.
