### ISSUE TITLE
Sync to teams icon is missing

### ISSUE THREAD

**Issue by bolatovumar** [SharePoint/sp-dev-docs#4041]
See the note here: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction#development-process](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction#development-process)

Corresponding markdown file is here: [https://github.com/SharePoint/sp-dev-docs/blob/da6ba5914faf1e6c2e3cd7ca5369a14c7c738294/docs/spfx/integrate-with-teams-introduction.md](https://github.com/SharePoint/sp-dev-docs/blob/da6ba5914faf1e6c2e3cd7ca5369a14c7c738294/docs/spfx/integrate-with-teams-introduction.md)

Notice that the note points to a .png file which does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac71237-d078-e29e-4115-5efbbbebd3ec
* Version Independent ID: 5af01d79-5f92-b256-2872-34266ea14d9f
* Content: [Building Microsoft Teams Tabs using SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction)
* Content Source: [docs/spfx/integrate-with-teams-introduction.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/integrate-with-teams-introduction.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... will get this fixed.
