### ISSUE TITLE
New SPFx Web Parts default styles should comply with standard SharePoint styles

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-docs#4042]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Creating a web part using the Yeoman generator should produce a web part that is visually indistinguishable from an out-of-the-box SharePoint web part. It should encourage new developers to adopt the UI Fabric look without requiring additional efforts on their part.

#### Observed Behavior

A newly generated SPFx web part defines CSS styles that are inconsistent with other SharePoint web parts.

#### Steps to Reproduce

1. Create a web part solution using the yeoman generator
2. Once the solution is created, open the generated component's `.module.scss` 
3. Find the `.container` CSS class
4. Notice the CSS styles, such as `box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);` and `max-width: 700px;`
5. Using the workbench (or a web part page), insert any out-of-the-box web part, such as the **Image**, **File Viewer**, **Document Library**, etc.
6. Using the workbench (or a web part page), insert your newly created web part
7. Using your browser's developer tools, compare the out-of-the-box web part CSS styles to the newly created web part's styles

While it is a minor issue, I believe that it is our responsibility to create tools that make it easy for new SPFx developers to build web parts that leverage the UI Fabric styles without over-complicating the default web part. Re-evaluating the default CSS styles (e.g.: removing the `box-shadow` and `max-width` CSS styles) is a potential quick win in that direction.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Thanks for the submission, but this might fall into the category of a user voice request as it's not really a bug, rather it's a request to change something that does work... 

Care to suggest exactly how you'd resolve it? IOW, what should the default SCSS look like? Different for a React & non-React based web part?

**Comment by hugoabernier** [comment]
@andrewconnell Sorry for the delayed response, I completely missed this. I'll put something together this week and get back to you.

**Comment by hugoabernier** [comment]
I believe that my suggestions apply to React and non-React.

Considering that the [SharePoint Design article on grid and responsive design](https://docs.microsoft.com/en-us/sharepoint/dev/design/grid-and-responsive-design) says that web parts can go as wide as 1204px in the case of an XXXL screen (1920 x 1080) with a 1 column layout, I would remove the:
```CSS
max-width: 700px;
```
in the `.container` class.

On the other hand, it may be worth adding a `min-width`, considering that the Small screen layout (320 x 568) will be 280px (320px with 20px margin on each side):
```CSS
min-width: 280px
```

Finally, I would remove the `box-shadow` because no other Web Part implement a box shadow.

Therefore, the final `.container` class would look like this:

```CSS
.container {
    min-width: 280px;
    margin: 0px auto;
  }
```

In my opinion, it would be a very small change that would help all new SPFx solution create web parts that look and feel like the out-of-the-box web parts.

Does this help?

**Comment by andrewconnell** [comment]
Maybe... I'm an expert on design (I yield to @StfBauer on those things), but from my POV this is still a feature/change request to the existing platform that would fall into the user voice bucket: https://aka.ms/spdev-uservoice. Right?

**Comment by hugoabernier** [comment]
Was unsure what the proper channel to suggest a change to the yeoman generator, short of waiting until it becomes open source. I'm happy to oblige with any recommendations @StfBauer and others make on this matter.

**Comment by andrewconnell** [comment]
@hugoabernier said:
> Was unsure what the proper channel to suggest a change to the yeoman generator

Uservoice... bugs / issues / questions / discussions... those are things that work great for this issue list. But Microsoft defines their feature backlog based on uservoice.

As this is really a feature request / change, I'm going to update it's tag & close it as that's how we've handled these in the past.
