### ISSUE TITLE
Issue while creating new Office 365 group and attach it to an existing site

### ISSUE THREAD

**Issue by amitpatil2019** [SharePoint/sp-dev-docs#4044]
Issue while creating new Office 365 group and attach it to an existing site:
I have to create new Office 365 group using csom and attach it to an existing modern sharepoint team site, for that I am following the below GitHub link:
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/groupify/groupify-csom.md 

While debugging I didn't found any error but when I tried to verify the new created group on this link "https://portal.office.com/adminportal/home#/groups" so I am not able to see the group, below code I am using:

AuthenticationManager authManager = new AuthenticationManager();
                SecureString password = new SecureString();
                foreach (char c in Password.ToCharArray())
                {
                    password.AppendChar(c);
                }

                ClientContext clientContext = new ClientContext(TenantAdminUrl);
                clientContext.Credentials = new SharePointOnlineCredentials(UserName, password);
                Tenant tenant = new Tenant(clientContext);
                GroupCreationParams optionalParams = new GroupCreationParams(tenant.Context);
                tenant.CreateGroupForSite("my existing modern sharepoint team site url", "new office 365 group name", "new office 365 group name", true, optionalParams);

Could you please help me to resolve this issue?

**Comment by brianvan2** [comment]
@amitpatil2019, we could use some more information.
- Can you reproduce the issue? If there's a bug, a network trace of your CSOM call will help.
- Does your team site have a GroupId now? I'm talking about the SPSite.GroupId property.
- If it does, are you able to get the group with that id in [Microsoft Graph](https://developer.microsoft.com/en-us/graph/graph-explorer)?

**Comment by brianvan2** [comment]
To be clear, the issue is likely on the server side and unrelated to SPFx.

**Comment by brianvan2** [comment]
@amitpatil2019, if you are still experiencing the issue then please open a ticket with regular SharePoint support.

**Comment by amitpatil2019** [comment]
Hi Brian,

Thanks for reply but actually I was looking for solution immediately, now
we are not working on this.

If you can provide me immediate contact team email id then that would be
good so that going forward i will contact them directly.


Thanks & Regards
Amit Patil
