### ISSUE TITLE
SharePoint Framework extensions are not working

### ISSUE THREAD

**Issue by Narendra1224** [SharePoint/sp-dev-docs#4046]
I deployed a SharePoint Framework Extension Solution to a developer tenant which release preference is "Targeted release for everyone". The extension is not visible or not working. When coming to another tenant which release preference is " Standard release"  I deployed the same solution extension is working fine. 

Please help me solve the issue.

Thanks in advance

**Comment by lucabandMSFT** [comment]
@Narendra1224, this issue is not really actionable as we don't know if that is generic to all extensions (which doesn't seem the case). Can you please check if the issue is still occurring and, if that's the case, can you provide us sample of what is not working?

**Comment by Narendra1224** [comment]
@lucabandMSFT  Thanks for your response.

 I deployed a SharePoint Framework extension in Tenant where the preference is Target for the First release. I couldn't see the header and footer on my site whereas I deployed the same extension on a tenant where preference is of Standard Users then I could see the header and footer working correctly. The issue is still occurring.

**Comment by andrewconnell** [comment]
Is this for a deployed extension or when trying to debug one, running it via **gulp serve**?
