### ISSUE TITLE
Navigating between pages loses my reference to Fabric Icons in SPFx Top Placeholder (SPFx v1.8.0)

### ISSUE THREAD

**Issue by LDock1** [SharePoint/sp-dev-docs#4047]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm creating my own tenant navigation extension using the SPFx application customizer, jQuery, KnockoutJS, PnPJS and the Fabric Icons (v 10.1.0).  After I've deployed the app to my tenant and added it to a site collection on the first page load everything works fine, but the icons disappear when I navigate to any other page in the site collection using the local navigation links.

I'm still learning how to develop using the SPFx, so I know I'm developing it a bit unconventionally but I'm curious about the best way to do this.  I'm using the SPComponentLoader.loadCss function to load a CDN version of fabric.min.css (https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.1.0/css/fabric.min.css).  I can see the CSS file being loaded in the dev tools when the page has loaded, but after navigating to another page the css file disappears from the dev tools (so the file is "unloaded").

I have the Minimal Download Strategy feature disabled for the site so it shouldn't be related to that.  I've littered my code with console.logs to see if any code in the extension gets executed more than once, but it doesn't seem to be the case - so moving my SPComponentLoader call won't help.

Is there some obvious step that I'm missing?  Is there some extra coding which must be accounted for when using local navigation in SharePoint (where the top placeholder isn't reloaded)?  

Thanks in advance for any tips.  I spent most of the day reading documentation and related issues but couldn't find much about my specific case.

**Comment by andrewconnell** [comment]
OOTB you shouldn't need to load the CSS for Fabric Core... it's already in a default SPFx project (using any relatively recent version of the SPFx Yeoman generator) & referenced in the web part's SCSS file (look at the first line).

Hard to assist without any code snippets / screenshots / etc... also need the standard questions answered:

- what version of SPFx are you using
- what SharePoint environment
- what browser(s) are you using

**Comment by LDock1** [comment]
@andrewconnell Thanks for your reply.  I'm using SPFx 1.8.0, SharePoint Online, and it affects all browsers that I've tested with (Firefox, Chrome, IE, Edge).

I think my issue boils down to not understanding how to use Fabric icons in a non-react SPFx extension (note this isn't a web part, it's an application customizer using the top placeholder).  

The icons don't seem to load from the first line in the default scss file - when I follow the `@import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';` trail, I can see that the `@import './Icon';` line of that document is commented out, and according to the [Office UI Fabric Integration](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration) documentation, icons are not included in the package. 

I've attempted to load the icons using the method outlined in the [@uifabric/icons](https://www.npmjs.com/package/@uifabric/icons) and [Using Fabric react icons](https://github.com/OfficeDev/office-ui-fabric-react/wiki/using-icons) pages (which doesn't work at all - possibly because I'm not using react(?)):
`import { initializeIcons } from '@uifabric/icons';`
`initializeIcons();`

The only method I can use to get the icons to show is with this line in the overriden onInit() method:
`SPComponentLoader.loadCss('https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.1.0/css/fabric.min.css');`

My issue only occurs when navigating between modern site pages - when first loading any modern page or when I navigate to a modern list page, the whole screen refreshes, so the icon file reloads.  When I navigate between modern site pages, the site header and top placeholder are not refreshed - this is when some of the icons go missing.  When the icons are missing, I can see the [file loaded](https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.1.0/css/fabric.min.css) by the SPComponentLoader has disappeared from the page sources in the dev tools.  I assume some of the icons remain because they are loaded by other page elements.

Side note - the way I'm using the icons is to store a list of important links in a SharePoint list with the icon name as a column in the list.  I want users to have the flexibility to pick any icon from the [Fabric Icons site](https://uifabricicons.azurewebsites.net/), so I don't want to register individual icons, I want the whole set.  I use KnockoutJS to put `<i class="ms-Icon ms-Icon--XXXXX" style="color:#E66B5B" aria-hidden="true"></i>` elements on the page.

Working example - you can see all icons, and the dev tools shows the fabric css file.
![Working](https://user-images.githubusercontent.com/48901878/58544531-0ed10380-8234-11e9-8324-0f7e57eda55a.png)

Not working example - I navigated to a different site page and back.  There are 2 missing icons (on the remainder of the page there are more), and the css file is missing from the dev tools.
![Not-Working](https://user-images.githubusercontent.com/48901878/58544530-0ed10380-8234-11e9-809a-75ae8be45ebb.png)

**Comment by andrewconnell** [comment]
@LDock1 said:
> I've attempted to load the icons using the method outlined in the @uifabric/icons and Using Fabric react icons pages (which doesn't work at all - possibly because I'm not using react(?)):

Correct... the package you are loading is intended to be used in react controls, not outside of React. You're actually getting more than you need there.

But to the issue, if it's only showing up when a user is navigating between pages, maybe you can trap the navigated event to check if the icons are present and if not, load again? While not directly related, #1971 contains a discussion on this event... the code is something like `this.context.application.navigatedEvent.add(this, () => { // your logic })`.

**Comment by LDock1** [comment]
Thanks for your help @andrewconnell.

I managed to get it working by adding this code to the onInit():

```
this.context.application.navigatedEvent.add(this, () => {
	//console.log("Navigated event fired");
	SPComponentLoader.loadCss('https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.1.0/css/fabric.min.css');
	this._renderPlaceHolders();
});
```

I needed to add the extra _renderPlaceHolders() function call in there as the icons would change to weird symbols (e.g. ïŠŸ) if I didn't re-render the placeholder after reloading the fabric CSS file.
