### ISSUE TITLE
Breaking change in SharePoint add-in app permissions for web.RootFolder.Name

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#4048]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SharePoint add-ins which get the web.RootFolder.Name should be working with just the app permission: Web Read

#### Observed Behavior
Since today we noticed the SharePoint add-ins stopped working which get the web.RootFolder.Name and have the app permissions: Web Read requested and approved.

When giving the app permission: Web Full Control, things start working again.

#### Steps to Reproduce
Create a SharePoint Add-in, set the app permissions to Web Read, and within the app make a call to get the web.RootFolder.Name

**Comment by SanderSiep** [comment]
Also when giving the app permission web.edit it is working. But indeed with web.read it is not working anymore.

**Comment by advdberg** [comment]
Maybe unnecessary to mention, but the user opening the SharePoint add-in should now also have the edit permissions on the site where the add-in is installed (when the add-in gets the web.RootFolder.Name). This wasn't needed before last weekend.

**Comment by advdberg** [comment]
@VesaJuvonen this was the issue my colleague @SanderSiep spoke to you about during the ECS this afternoon, which was a breaking change for our SharePoint Add-ins since this weekend.
