### ISSUE TITLE
After 'Sorry, something went wrong with adding the app' AppMonitoringDetails does not give any info

### ISSUE THREAD

**Issue by PiWiBardy** [SharePoint/sp-dev-docs#4049]
Hello,

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

While adding a SPFX package to a site, if i'm getting an error during installation process, if i'm going to the AppMonitoringDetails, and then click on error '1' i should be able to see the error details instead of blankpage.

#### Observed Behavior

When I click on the '1' to show the errors, it shows a blank page

#### Steps to Reproduce

This happens if we're deploying an SPFX Application that includes a SharePoint feature to provision list or CT, with something wrong in it. This issue seems very similar to #1089 so
to help i got the **sprequestguid** from the response header : **34b3e09e-b045-0000-a1c5-05a3b1304057**

Thanks for your help

**Comment by andrewconnell** [comment]
Someone else posted something similar recently in #4029 ... might want to monitor that one. Can you provide the details @patmill requested in that thread as well?

**Comment by PiWiBardy** [comment]
Hello andrew, thanks for your help there's no error in 'error' column, please find a screenshot of all significant column in the app catalog : [https://ibb.co/mGfdNGw](url)

**Comment by andrewconnell** [comment]
@PiWiBardy Can you paste the screenshot in the comment, not as a link tot he "ibb.co" domain? I'm getting loads of warning and browser warnings when hitting that site so I can't see the image...

**Comment by PiWiBardy** [comment]
Sure @andrewconnell  ![image](https://user-images.githubusercontent.com/1949353/58546906-a91a5280-8206-11e9-8aea-24e1d8dfbf60.png)

**Comment by GrahamMcMynn** [comment]
We didn't look at this anywhere close to fast enough, and now cannot capture logs... it is possible to get a new correlation ID for the issue?
