### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (NOT FOUND)

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#405]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
No 404 and finds the resource as named in the /dist folder.

#### Observed Behavior
It is looking for:

https://[somecompany].sharepoint.com/sites/Development/SiteAssets/[somefolder]/requirements-form.bundle_7d870013ff1fbe71dfc94b839bfbed8f.js

But the file is located here:

https://[somecompany].sharepoint.com/sites/Development/SiteAssets/[somefolder]/requirements-form.bundle.js

Hence, I get:

> Failed to load resource: the server responded with a status of 404 (NOT FOUND)

NB It works if I forget to set "--ship" and add the package, and run "gulp serve" (and in my /dist/ folder is not requirements-form.bundle_7d870013ff1fbe71dfc94b839bfbed8f.js, just requirements-form.bundle.js)

#### Steps to Reproduce
Expected that it should find the CDN resources (as it does when I run "gulp serve" to when I deploy files to CDN (I can confirm they are there) and upload the package to the app catalog in SharePoint after running:

`gulp clean
gulp build
gulp spsave
gulp bundle --ship
gulp package-solution --ship`

#### Workaround

Manually rename the file (although this maybe creating/related a related issue?)

**Comment by waldekmastykarz** [comment]
When running a production build the files to be deployed are located in the **./temp/deploy** folder rather than **./dist**.

**Comment by webtechy** [comment]
Ah! Thanks Waldek :-) OK, maybe I should change it to a suggestion that the **./temp/deploy** folder is moved to **./sharepoint/deploy** where the package also gets saved?

**Comment by chakkaradeep** [comment]
The `/sharepoint` folder only includes the stuff that is packaged, hence you dont see the bundle in that folder. It also helps not to confuse with the normal web flow which is to use dist and lib folders.

**Comment by waldekmastykarz** [comment]
@chakkaradeep the one confusing part is that when running `gulp bundle --ship`, the **./dist** folder contains the minified version of the bundle which might give the impression, that the folder contains all files required for deployment, which isn't the case.

**Comment by patmill** [comment]
Closing the issue.  If you feel there is an enhancement that should be made, please add an entry in user voice - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/
