### ISSUE TITLE
How to use npm link?

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#4051]
Can you please explain how to use the npm link to use SPFx libraries from SPFx webpart projects? I didnt find official documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b431da26-3a26-bab5-1af4-a151d9e50f2e
* Version Independent ID: 50656bd9-3514-ae39-0805-0927d30e4355
* Content: [Using library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview#feedback)
* Content Source: [docs/spfx/library-component-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PopWarner** [comment]
Hi @levalencia, how are you my man? :) Hope all is well.

Did you happen to see the tutorial documentation for the Library Components here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial

It covers how to connect a web part to a Library Component. It doesn't go super deep on the inner-workings of the "npm link" functionality, so maybe you were meaning to add additional documentation on that? Or maybe just adding a link to the tutorial from the overview page might work? It's in the table of contents, but sometimes it helps to have a link on the page as well.

Coincidentally, I just recorded a video this weekend on that exact topic, so keep an eye out on my blog as I should have it published out in the next day or so.

**Comment by levalencia** [comment]
Thanks David, the tutorial is perfect, but I think there should be a link from the overview page to make it easier to find.

**Comment by PopWarner** [comment]
Gotcha. :)

**Comment by andrewconnell** [comment]
Probably best to refer to the official NPM link docs too: https://docs.npmjs.com/cli/link
