### ISSUE TITLE
How to hide "Get the mobile app" & "Feedback" buttons on home page on SharePoint Modern Communication site?

### ISSUE THREAD

**Issue by AdityaALPS** [SharePoint/sp-dev-docs#4053]
Issue Category: SharePoint PNP (Custom Learning for Office 365) app.

Question: how to hide "Get the mobile app" & "Feedback" buttons on home page on SharePoint Modern Communication site.
Current Version we are using: VERSION | 2.0.13.0 | RELEASE DATE | May 2019

<img width="443" alt="FeedbackHide" src="https://user-images.githubusercontent.com/50898002/58474809-d664f300-8169-11e9-99a9-79cd7dc68ce0.PNG">

**Comment by MRuimerman** [comment]
You can remove this using PowerShell but that is a tenant wide setting.

**Comment by andrewconnell** [comment]
There's a POSH way to do this. Note it is a tenant-wide setting... 

```powershell
Set-SPOTenant -UserVoiceForFeedbackEnabled $false
```
