### ISSUE TITLE
ApplicationCustomizer: context.application.navigatedEvent logic

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4054]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Could you please explain the logic, how `context.application.navigatedEvent` is called in `ApplicationCustomizer`?

From what I can see:
1. it is called when navigating between pages. For example, from one list to another. That seems correct.
2. If you navigate between **two same pages (in my cases - two lists)** it stops firing. List A -> List B - fired. List B -> List A - no fired
3. it is called when navigating between views in the same list **FOR THE FIRST TIME ONLY**. It seems weird.

**Comment by OliverZeiser** [comment]
Seems to be the same old issue as this #3836

**Comment by ahackettms** [comment]
We are working on fixing this issue soon. Thank you for your patience.

**Comment by OliverZeiser** [comment]
@ahackettms please also make sure, that the pageContext of sharepoint framework is getting updated correctly. This is not the case right now when navigating between lists. Thank you!

**Comment by ctofts86** [comment]
Is there any update or idea as to when this fix may be deployed yet? Experiencing similar issues myself when navigating using quick links web part / Hub nav / sites web part to navigate to sites associated with a Hub.

**Comment by ahackettms** [comment]
The fix for this issue should have been deployed. Please try again. @andrewconnell 
Note that the fix address the scenario of navigating between pages and lists, but doesn't address navigating into folders.

**Comment by OliverZeiser** [comment]
It took quite a long time, but I can confirm it is finally working! Thank you!

**Comment by ahackettms** [comment]
Great! I was actually deployed a few weeks ago. 
@patmill shall we close this issue and other duplicate issues?

**Comment by srinutamada** [comment]
I didn't see it's working in my scenario. Do I need to rebuild the solution? Please provide steps to perform from my side to see the change.

**Comment by ctofts86** [comment]
I can confirm it does not work in my scenario either. Scenario is I am on a hub site and navigate to another site via the sites webpart. Anything clickable in the footer that uses this.context still uses the context of the page I navigated away from.

As @srinutamada says, do we need to rebuild / redeploy the solution?

**Comment by AJIXuMuK** [comment]
Hi all,

It works better.
But...

1. Sometimes the event is fired after navigation, and sometimes before. You can check it by adding `console.log(window.location.href)`. Sometimes you'll see the final url there, sometimes transitional url like `https://tenant.sharepoint.com/sites/site/Lists/List%201/AllItems.aspx?id=%2Fsites%2Fsite%2FLists%2FList%202&newTargetListUrl=%2Fsites%2Fsite%2FLists%2FList%202&viewpath=%2Fsites%2Fsite%2FLists%2FList%202%2FAllItems%2Easpx`
2. Point 3 from the initial description is still there - when navigating between views the even is fired for the first time only.

**Comment by andrewconnell** [comment]
@ahackettms people are still saying this issue is present... as such I don't think we can close this or others...

**Comment by clarktozer** [comment]
As per my ticket #5029 , the event does not fire when creating new pages from a Site Page, which means the context is not correct.

**Comment by afrorarw** [comment]
I am also able replicate #5029 , when creating a new page does not trigger the navigatedEvent.

@andrewconnell I believe #5029 is a different issue as it has never been mentioned in this issue previous to your mention of it. This issue (#4054) is very generic with specific issues being mentioned in it. This makes it really hard to tell what specific issues have been addressed by the SP team.

**Comment by clarktozer** [comment]
#5029 still remains an issue for me.

**Comment by AJIXuMuK** [comment]
@clarktozer - sorry for the long delay. #5029 seems to be fixed.

For the initial one - it works fine now. The event is not firing when navigating between views, but technically we're not changing the page.

If there are any proposals on how application customizers should work - please comment in this discussion: https://github.com/SharePoint/sp-dev-docs/discussions/7406
