### ISSUE TITLE
Command Set Customizer: onListViewUpdated Logic

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4056]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Command Set's `onListViewUpdated` firing logic is clear and consistent between different types of tenants (Standard and Targeted releases).

#### Observed Behavior

1. `onListViewUpdated` is called multiple times (4-6) in some situations
2. `onListViewUpdated` is called when switching between list view on Standard Release but not called on Targeted Release - **this contradicts with the statement that previously developed SPFx customizations will work in future releases and after future updates**

A bit more details.
Command Set Customizer is a simple one created by default by Yeoman generator and is registered to appear in Command Bar only.
`onListViewUpdated` is called:
1. 4-6 times on initial page load (page refresh) both on Standard and Targeted Release tenants
2. 4 times when navigating to another list both on Standard and Targeted Release tenants
3. **Targeted Release**: 2 times when navigating back to list from 1 (the one from initial state). If you're navigating between these two lists back and forth in can stop firing at all. **Standard Release**: 4 times
4. **Targeted Release**: 2 times when switching from one view to another and 0 times when switching back (All Items -> other view -> All Items); **Standard Release:** 4 times and 2 times respectively
5. **Targeted Release:** 2 times when selecting/deselecting item; **Standard Release:** 4 times

I'm concerned about number of calls as well as the fact that it is not called when switching view in Targeted Release.

#### Steps to Reproduce

1. Create Command Set customizer using Yeoman generator
2. `gulp serve`
3. Play around with it on list pages.

**Comment by ronnyagous** [comment]
My observation is that the number of calls is related to the number of command buttons you have - For me it is twice the number of buttons. I guess once for the command bar and once for the context menu.

**Comment by AJIXuMuK** [comment]
currently (Targeted release) it is not called when navigating back to the list.
Example:
1. open list 1
2. navigate to list 2
3. go back to list 1

**Comment by henningeiben** [comment]
> My observation is that the number of calls is related to the number of command buttons you have - For me it is twice the number of buttons. I guess once for the command bar and once for the context menu.

I experienced something similar, at least as far as that the `onInit` and `onListViewUpdated` are fired at least twice (I have my commandbar set up to show in the commandbar as well as the context menu, so this could be the reason).

However - I would have expected this event to only fire once, as this extension is only registered once (from my point of view).

**Comment by patmill** [comment]
This is being tracked as a general 'future of command sets' here: https://github.com/SharePoint/sp-dev-docs/discussions/7375
