### ISSUE TITLE
Links to legacy content that is no longer maintained

### ISSUE THREAD

**Issue by softwarecraft** [SharePoint/sp-dev-docs#4058]
Many / most of the links in the SharePoint API index table point to pages under https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/... which include a disclaimer "We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported" and a link button "Recommended Version" that leads to a top level doc page not specific to API index hence not a useful link.

AFAIK SP JS CSOM still still fully supported and not deprecated. Therefore the current page should point to current documentation not out-of-docs.

I looked for current versions of these doc pages but wasn't able to find them. Microsoft Sharepoint product team needs reminding to publish and maintain current docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94956608-25b4-0605-f43d-d161ebdde905
* Version Independent ID: 5a5b71db-be77-2ac8-7b9f-82f13961d4fa
* Content: [SharePoint .NET Server, CSOM, JSOM, and REST API index](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index)
* Content Source: [docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The JavsScript Object Model (JSOM) is the JS implementation of the client-side object model (CSOM). While it is technically supported, there haven't been any improvements to it and the docs on this page are current. 

The current recommended guidance is that you should use the SharePoint REST API if you are doing client-side solutions (as the SharePoint Framework does). 

Another alternative is to look at the [PnPJS](https://pnp.github.io/pnpjs/) library which is a community project. While not supported by Microsoft, it's quite popular and is run by a Microsoft employee in his spare time.
