### ISSUE TITLE
SPFx Licence

### ISSUE THREAD

**Issue by ds22083** [SharePoint/sp-dev-docs#4060]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

As per SP documentation SharePoint Framework components are licensed under this Microsoft EULA. That means this repository is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 United States license. 
Creative commons legal terms restricted SPFx for any commercial benefits. Please help me understand this legal term as this is prohibiting us using SPFx . Thanks.
- 

> 4. Restriction -You may not exercise any of the rights granted to You in Section 3 above in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation. The exchange of the Work for other copyrighted works by means of digital file-sharing or otherwise shall not be considered to be intended for or directed toward commercial advantage or private monetary compensation, provided there is no payment of any monetary compensation in connection with the exchange of copyrighted works.   
> 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview
https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
We're working on possibly clarifying the language.  The intent is "you can use SPFx to build solutions and profit from those solutions.  You can't resell or profit off SPFx itself".  However, I'm not a lawyer (nor do I play one on television), so that's all I'll comment.

**Comment by ds22083** [comment]
Thanks pat, actually for me also legal terms are Alien language. Actually concerned raised by attorney who approved any OSS that we can use in our firm and they just go by what is written in legal terms unfortunately:(.

**Comment by ds22083** [comment]
Guys, Any progress on this issue?

**Comment by ds22083** [comment]
Thanks Andrew for updating the Licence. But the terms still saying that this can not be use for any commercial purpose:
3.	SCOPE OF LICENSE. The software is licensed, not sold. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you will not (and have no right to):
a)	work around any technical limitations in the software that only allow you to use it in certain ways;
b)	reverse engineer, decompile or disassemble the software;
c)	remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software;
d)	**### use the software for commercial, non-profit, or revenue-generating activities;**
e)	use the software in any way that is against the law or to create or propagate malware; or

Please advise?

**Comment by andrewconnell** [comment]
Two things:

1. I'd suggest opening a new issue asking this... this issue is closed and thus no one is watching it.
1. I can't comment on Microsoft licensing. I help with this issue list, but I am not a MSFT employee nor can I speak on their behalf, especially about licensing.
