### ISSUE TITLE
An o365 update has caused window.performance to be undefined in IE11(CORE BROWSER functionality)

### ISSUE THREAD

**Issue by jasonarden** [SharePoint/sp-dev-docs#4062]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

window.performance is NOT undefined

#### Observed Behavior

window.performance is undefined in IE11 on sharepoint.com domain

#### Steps to Reproduce

Go to any Sharepoint URL (_layouts/15/viewlsts.aspx) in IE11 and hit F12 (debugger) – 

Type “window.performance” in the console

You will see it is UNDEFINED (if you use the same browser in IE11 and go to a NON Sharepoint.com domain window.performance is NOT undefined)

It is not UNDEFINED initially if you set a breakpoint…  at some point (assuming Sharepoint scripts or other JS scripts) are resetting window.performance to undefined) – I have not investigated which script is causing it.

![perf1](https://user-images.githubusercontent.com/1065222/58636294-f7d6f380-82bd-11e9-8498-8e99b9d5daf2.png)

![perf2](https://user-images.githubusercontent.com/1065222/58636298-fa394d80-82bd-11e9-8902-979a873ce453.png)

**Comment by patmill** [comment]
OK, there was another component getting loaded onto all the pages in SharePoint (classic and modern) that was causing this.  It's been fixed and should be rolled out world-wide by the end of the day.
