### ISSUE TITLE
Accessibility bug: Focus order is incorrect after Sign in link

### ISSUE THREAD

**Issue by lindalu-MSFT** [SharePoint/sp-dev-docs#4064]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Tab focus order is incorrect. Users who rely on keyboard navigation will be affected if the focus order is incorrect. When tabbing through this document, the Focus should move to the "Filter by title" search box after Sign in link.

#### Observed Behavior
Focus is moving to "Add an office UI Fabric component" link after Sign in link.

#### Steps to Reproduce
Repro Steps:
Step 1: Go to [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components)
Step 2: Navigate to the page using tab key.
Step 3: Verify that focus order after sign in button.

This was reported during an Accessibility pass. Bug can be found here:
https://office.visualstudio.com/OC/_queries/edit/3294367/?triage=true

**Comment by andrewconnell** [comment]
The link you shared to the VS.com bug isn't publically accessible to get more context... 

I just did your repro steps and the tab through the links seems to work the same as every other page, from the "sign in" link > filter box > current topic > download PDF. Looks like its working correctly...

**Comment by patmill** [comment]
I'm sorry - this isn't the correct place to log / discuss / etc. these issues.  Can you mail us directly internally and we'll figure out the correct system to handle it?

**Comment by lindalu-MSFT** [comment]
@patmill Certainly, will do! I'll reach out on email shortly if I find any additional Accessibility bugs that can be repro'd.
