### ISSUE TITLE
Can we expect improvements/fixes on the list web part?

### ISSUE THREAD

**Issue by furler** [SharePoint/sp-dev-docs#4066]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Embedding a view formatted list on a modern page still leaves a lot to be desired when trying to achieve a nice end user experience:

- Internal scroll bars are annoying, it would be nice if we could place a list view on a page and have it sit seamlessly with other content like was possible in the classic experience. 
- Office Fabric UI classes are still not rendering when a list is added to a page via the web part
- The view formatting repository contains many examples of people using flex to display tiles on the page. None of these display correctly when used via the web part. The CSS does not even seem  to be correct, as ideally the flex needs to be applied BEFORE the rowFormatter styles. 
- Ideally I think a "container formatter" would solve the flexbox issue, allowing us to apply styles to the parent container and open up more flexibility for list display.

Is there anywhere we can monitor if the list web part is still being worked on?

**Comment by patmill** [comment]
Are you looking for fixes specific to extensibility, or just general usability?

**Comment by furler** [comment]
> Are you looking for fixes specific to extensibility, or just general usability?

I think this falls under general usability.
