### ISSUE TITLE
Can we use relative urls for pictures?

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-dev-docs#4074]
All examples in this document show absolute URL for pictures, but can it be relative urls or can those urls support tokens like in the classic JSlink? https://docs.microsoft.com/en-us/sharepoint/dev/general-development/urls-and-tokens-in-sharepoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for your question!

You can reference the local site (same as the webAbsoluteUrl) by using the `@currentWeb` token. You can see an example of using this to reference an image from the local site in this sample: [text-local-image](https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/text-local-image).

The key is in this section of the [text-local-image.json](https://github.com/SharePoint/sp-dev-list-formatting/blob/master/column-samples/text-local-image/text-local-image.json) format where the `src` of the `img` element is set using an expression involving `@currentWeb`:

```json
  "attributes": {
    "src": "=@currentWeb + '/Shared Documents/Evilness/' + @currentField + '.png'"
  },
```
