### ISSUE TITLE
Column/List Formatting DAX not full featured

### ISSUE THREAD

**Issue by CPritch** [SharePoint/sp-dev-docs#4075]
[This documentation here ](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#expressions)lists that in SPO an Excel Expression string can be used, it doesn't list any lack of functionality that does exist in Calculated Columns.

From testing this is not the case. Only an incredibly limited subset of DAX style functions work.

It seems odd that there are no string operations other than an implied concat in both DAX and the modern expressions object. Could someone propose how to remove '.url' from the Name column of a document library and have it still link to the document/url?

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Either documentation should list what does not work or the subset of DAX functions or they should work. It seems like I'm missing something to not have any string operations.

1. =LEFT should be method to trim string

#### Observed Behavior

1. =LEFT renders as =LEFT and does nothing.

#### Steps to Reproduce

1. Try the following Column Formatting JSON on any list or library
```JSON
{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
   "elmType": "div",
   "txtContent": "=LEFT(@currentField,4)"
}
```
2. It just displays the text `=LEFT(@currentField,4)`

**Comment by bcameron1231** [comment]
I think the key thing to clarify is it's "Excel-style" expressions, not "Excel expressions". The listing of functions available are listed on that documentation referenced. With that being said, string manipulation is currently quite limited in column formatting.

**Comment by CPritch** [comment]
@bcameron1231 I'm well aware of the limitations in SP and it's DAX subset but the article doesn't seem to imply that there's less than OOTB calc column. There doesn't seem to be any string manipulation at all for substrings or replacing of string values.

**Comment by bcameron1231** [comment]
I can understand that and could see the confusion it may cause. Though there is no relationship between column formatting and calculated columns, this is something we could add to the documentation for a bit more clarification.

**Comment by CPritch** [comment]
That's as I figured but It'd be really handy to have the list of available DAX style functions as I can only seem to be able to us IF and basic mathematical operators. I think I'll have to go with a calc column with json formatting otherwise. W regexp operator in the expression object would be a dream but will leave for the uservoice haha.

**Comment by PopWarner** [comment]
@CPritch, I would definitely recommend the uservoice route. I believe Microsoft is really looking to continue to invest in the features available for List Formatting due to the extremely empowering functionality it provides to users without having to deploy any SPFx apps, etc. :)
