### ISSUE TITLE
SPLoaderError.loadComponentError on Hub Site home page components

### ISSUE THREAD

**Issue by MrNigel** [SharePoint/sp-dev-docs#4076]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I am running the SPOL Provisoning Service using the SharePoint Starter Kit solution template.  All the pre-requisites are checked OK and the three sites are created with no error messages.

#### Observed Behavior

If I go to the Hub Site home page several apps/web parts are displaying this error message:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "26cb4af3-7f48-4737-b82a-4e24167c2d07" (pnpTiles).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/imgroupltd.sharepoint.com/sites/appcatalog/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/solution-propertycontrolstrings_en-us_24df0ae17fe08d19f6a630a1cbd23af4.js' for resource 'PropertyControlStrings' in component '26cb4af3-7f48-4737-b82a-4e24167c2d07' (pnpTiles). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://publiccdn.sharepointonline.com/imgroupltd.sharepoint.com/sites/appcatalog/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/solution-propertycontrolstrings_en-us_24df0ae17fe08d19f6a630a1cbd23af4.js' for resource 'PropertyControlStrings' in component '26cb4af3-7f48-4737-b82a-4e24167c2d07' (pnpTiles). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:915:16084)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:1538:21156)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:1538:16215)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:1538:12246)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-03.013/sp-pages-assembly_en-us_5493085219cddd015fe284db23f333b4.js:1538:61575

#### Steps to Reproduce

This bug was present on a site created Thursday as well as a new one today.  It is reproduced by provisioning the SharePoint Starter Kit solution template.

Thanks for your contribution! Sharing is caring.

**Comment by patmill** [comment]
Just double-checking.  The tenant that you are accessing this from is imgroupltd.sharepoint.com ?

**Comment by ThomasVB96** [comment]
We experience the same error on one of our clients tenant. We have 1 DEV environment where the error never appears, but on the TST environment it does. Is there a temporary workaround available to resolve this issue? 

**Error :** 

[SPLoaderError.loadComponentError]:
Failed to load component "24bddb3e-9e7d-43da-8126-5bb7970a21f6" (GoDossieraanvraagFormWebPart).
Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/<tenant>.sharepoint.com/sites/appcatalog/ClientSideAssets/38d70d14-7a41-451d-bd9a-b5dec7940e2f/go-dossierbeheerwebparts-bundle_6eb8f529380c189c56e3a58195bf60ac.js' for resource 'go-dossierbeheerwebparts-bundle' in component '24bddb3e-9e7d-43da-8126-5bb7970a21f6' (GoDossieraanvraagFormWebPart). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/<tenant>.sharepoint.com/sites/appcatalog/ClientSideAssets/38d70d14-7a41-451d-bd9a-b5dec7940e2f/go-dossierbeheerwebparts-bundle_6eb8f529380c189c56e3a58195bf60ac.js' for resource 'go-dossierbeheerwebparts-bundle' in component '24bddb3e-9e7d-43da-8126-5bb7970a21f6' (GoDossieraanvraagFormWebPart). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.005/sp-pages-assembly_nl-nl_5acaa6a406dd536235a0f0ae17aff897.js:862:16092)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.005/sp-pages-assembly_nl-nl_5acaa6a406dd536235a0f0ae17aff897.js:1485:21156)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.005/sp-pages-assembly_nl-nl_5acaa6a406dd536235a0f0ae17aff897.js:1485:16215)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.005/sp-pages-assembly_nl-nl_5acaa6a406dd536235a0f0ae17aff897.js:1485:12246)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.005/sp-pages-assembly_nl-nl_5acaa6a406dd536235a0f0ae17aff897.js:1485:61659

**Comment by lucabandMSFT** [comment]
just double checking two things:
1. Is the error still occurring?
2. if you disable the Public CDN feature, does the error go away?
Thanks

**Comment by ThomasVB96** [comment]
Hi @lucabandMSFT ,

The error is still occuring sometimes. I will disable the public CDN again and and then wait some time before I enable it again.

Keep you posted! ;)
