### ISSUE TITLE
Download and install the SharePoint Online Management Shell

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#4092]
Why we need to reinstall if its already there. Is there a way to update the existing install?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a433bf-b243-03ff-f733-484dca2be753
* Version Independent ID: 7a173ed3-1700-b24f-ee78-417dd494ce16
* Content: [Get started creating SharePoint site designs and site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design)
* Content Source: [docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/get-started-create-site-design.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by russgove** [comment]
Just download the msi and run it. It will update the existing installation.
