### ISSUE TITLE
Start-SPOSiteRename results in type initiliazer exception

### ISSUE THREAD

**Issue by nthng** [SharePoint/sp-dev-docs#4097]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

This command starts a rename of a site on a SharePoint Online site into a new title, name and url.

#### Observed Behavior
```

PS C:\WINDOWS\system32> Start-SPOSiteRename -Identity https://tenant.sharepoint.com/sites/oldurl/ -NewSiteUrl https://tenant.sharepoint.com/sites/newurl/
Start-SPOSiteRename : The type initializer for 'Microsoft.Online.SharePoint.PowerShell.TelemetryMonitorAria' threw an exception.
At line:1 char:1
+ Start-SPOSiteRename -Identity https://tenant.sharepoint.com/sites ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-SPOSiteRename], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

```
#### Steps to Reproduce

1. Connect to SPOService
2. Execute the start-spositerename cmdlet

I have tried x86 and x64 Powershell and I am working with version 16.0.8924.1200 of the microsoft.online.sharepoint.powershell module.

Thank you!

**Comment by chanchaljainms** [comment]
Same here 
The type initializer for 'Microsoft.Online.SharePoint.PowerShell.TelemetryMonitorAria' threw an exception.
Is this gonna ever work?

**Comment by m-montesdeoca** [comment]
Exactly [same error](https://github.com/SharePoint/sp-dev-docs/issues/4097#issue-452866570) here also.

**Comment by andrewconnell** [comment]
While the PowerShell cmdlet has been released, the feature is not fully rolled out yet. Ref #3981

**Comment by andrewconnell** [comment]
While the PowerShell cmdlet has been released, the feature is not fully rolled out yet. Ref #3981

**Comment by PvilleStang** [comment]
+1 on this issue.  Why release cmdlets before they are operational?!

**Comment by dominicbrien** [comment]
Same here...

**Comment by ccullum** [comment]
This had worked for months during the beta multi-geo program.  I used it to move hundreds of sites across geos.  We don't have a GUI way of moving sites. Why break it and not fix it?

**Comment by galaxyflow** [comment]
ETA on this?
