### ISSUE TITLE
Clarify documentation on "Upload SharePoint Workbench" (Page: Setup SharePoint Tenant)

### ISSUE THREAD

**Issue by renefritsch** [SharePoint/sp-dev-docs#41]
It took me some time to get workbench.aspx up and running on my Dev-Tenant. The current documentation chapter "Upload SharePoint Workbench" (Page: Setup SharePoint Tenant) could be more clear in how to handle the file.

I suggest changing the above mentioned paragraph to read as follows:

"While we will introduce and talk about the SharePoint Workbench in the tutorials, to get set up, download the workbench.aspx to your local machine. **Open the file from our GitHub repo in your browser, switch the view to RAW format,** then right click, choose Save As option to save as workbench.aspx to your local computer, and upload it to the Documents library in the dev site collection."

**Comment by patmill** [comment]
Thanks for the feedback.  I've reworked it a bit.  Unfortunately IE doesn't have a "save as" context item on a page. :(  Instead, I simply said "right click on the raw link and select save target as".  Hope that makes it more clear.
