### ISSUE TITLE
SharePoint Admin Center active sites and deleted sites page broken

### ISSUE THREAD

**Issue by giuleon** [SharePoint/sp-dev-docs#4100]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The SharePoint Admin should be able to navigate in the active and deleted sites page

#### Observed Behavior

After having clicked on the left menu "active sites" or "deleted sites" I get the following error which break the page:
![image](https://user-images.githubusercontent.com/3914090/59032887-9b4c7900-8867-11e9-8c8f-92a9b82a9d29.png)

#### Steps to Reproduce

Open the SharePoint Admin center and click on active sites

**Comment by giuleon** [comment]
I solved by resetting the time zone in the admin site:
![image](https://user-images.githubusercontent.com/3914090/59033820-e4053180-8869-11e9-9973-d89951be2100.png)

anyway more controls should be there to prevent this issue

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we cannot unfortunately process this through here. Please report the issue through the tenant admin support channels, which is the right process for non-developer tooling.
