### ISSUE TITLE
Error saving page as template in SitePages

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-docs#4102]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The tenant has the new-ish "Save as template" capability available, so I should be able to save a page as a template.

#### Observed Behavior

When I try to do so, I get this error:

`REST error Error with code -2147024809, System.ArgumentException due to Inner-Message: Value does not fall within the expected range. Exception-Message: [HTTP]:400 - [CorrelationId]:6cf8e39e-5056-8000-c5db-b14c253483f0 [Version]:16.0.0.8922 at Error: Inner-Message: Value does not fall within the expected range. Exception-Message: [HTTP]:400 - [CorrelationId]:6cf8e39e-5056-8000-c5db-b14c253483f0 [Version]:16.0.0.8922 at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.007/sp-pages-assembly_en-us_f87e3760b9aa6c2684c21e30278a6b60.js:91:260926) at Function.e._getOdataRestApiError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.007/18.sp-pages-statemanager_1b675d4c96764e72ad3a.js:1:11448) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-05-24.007/18.sp-pages-statemanager_1b675d4c96764e72ad3a.js:1:25623}`

I've tried deleting the Templates folder (which was there from earlier attempts), but still no joy. It looks like it may be an issue moving the aspx page from the root of the SitePages library to the Templates folder after it is saved, as I do end up with new pages with names like 5cc7j2po.aspx.

The SitePages library has custom metadata columns of several types. Other SitePages libraries with the same metadata and structure work fine, so it may be some sort of damage.

This may be an isolated instance, but I wanted to log it in case it occurs elsewhere.

#### Steps to Reproduce

Create a new page, and save it as a draft (or publish). Open for editing again, and choose "Save as template". Add new name for the template and click the "Save page template" button. Error above.

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we cannot unfortunately process this issue through this channel. All non-dev topics should be reported through the Tenant Admin support channels or through Premier support. Sorry for the inconvenience.
