### ISSUE TITLE
Site Design Templates are not available

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#4103]
I created site design with -WebTemplate value "1" and its not available under drop down to choose from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a433bf-b243-03ff-f733-484dca2be753
* Version Independent ID: 7a173ed3-1700-b24f-ee78-417dd494ce16
* Content: [Get started creating SharePoint site designs and site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design)
* Content Source: [docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/get-started-create-site-design.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KEMiCZA** [comment]
@ravick4u value "1" is not associated with any existing current template, which is why you're not seeing it in the UI. Use one of the following values:
- 64: Team Site
- 68: Communication Site

Kind regards

**Comment by ravick4u** [comment]
Not sure why @ mentioned that its not possible. This document says that if group less team site can be created with template 1.

If you have disabled modern Group creation (or restricted to a subset of users) and wish to still allow your users to apply site designs to the "group-less" modern Team site template, publish your site designs using the -WebTemplate value "1".

**Comment by KEMiCZA** [comment]
@ravick4u 
I've created two site designs:
- Groupless Team Site **"TEST Groupless"**, with WebTemplate **1**
- Team Site **"TEST Teamsite"**, with WebTemplate **64**

```typescript
    await sp.siteDesigns.createSiteDesign({
        Title: "TEST Groupless",
        WebTemplate: "1"
    });

    await sp.siteDesigns.createSiteDesign({
        Title: "TEST TeamSite",
        WebTemplate: "64"
    });
```

I've also created a groupless teamsite STS#3 on site collection **"/sites/modern-site"**
On this site collection I can choose from both site designs:
![2019-06-12_14-19-57](https://user-images.githubusercontent.com/3862716/59350909-80717d00-8d1d-11e9-9118-b7d2598b0c5e.gif)

On the main /_layouts/15/sharepoint.aspx page, where you can create a new Team Site, I can only select the "TEST TeamSite" site design:
![2019-06-12_14-23-25](https://user-images.githubusercontent.com/3862716/59351001-b7e02980-8d1d-11e9-89b0-4fe7896cb08c.gif)

Do you have the same findings? I think this works as designed, please correct me if I'm wrong.

Kind regards

**Comment by ravick4u** [comment]
Yes its the same behavior I see. But how can I create a new site without group?

**Comment by melitoSP** [comment]
@ravick4u On SharePoint start page (previously referred to as SharePoint home page), for site designs we respect the WebTemplate. Therefore if you have a site design with WebTemplate = 64, it should only show for group connected sites. If your site creation experience is for non-group connected team sites, only site designs with WebTemplate = 1 would show.
