### ISSUE TITLE
Development tools issue

### ISSUE THREAD

**Issue by SoloRider67** [SharePoint/sp-dev-docs#4104]
When clicking on Build an App.....I get this message.
You need Office Development Tools installed on this site to build apps for Office and SharePoint. Redirecting you to SharePoint Store to download this tool. Click on 'Build an app' after download is complete to build apps.
If you are not automatically redirected, please click here.

It wants me to install "Napa Office 365 Development Tools". 

When I try to install It fails with this error: 

Sorry, something went wrong.
058d0bb6-5046-4817-8dfe-876e72f04be8
Select Continue to try again or find another app.

Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f90fd32e-4666-fe01-348c-14ae3f8e4dbe
* Version Independent ID: a561c546-6a45-441c-cbfb-1ba01abdbf9c
* Content: [Set up a development environment for SharePoint Add-ins on Office 365](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365#feedback)
* Content Source: [docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The Napa tools were retired and are no longer available.
