### ISSUE TITLE
Security Issues with depreciated packages in Yeoman generators

### ISSUE THREAD

**Issue by AndreJones216** [SharePoint/sp-dev-docs#4105]
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We are having security issues using the SharePoint Framework. 

We are using an artifact repository manager which only allows secure packages in the environment. Several times the SharePoint framework, package dependencies , have been flagged within our organization which is causing us the inability to download the entire SharePoint Framework and start development in O365. 

Our tools team here along with myself have found that there are depreciated packages in the Yeoman generator for SharePoint. 

One example that our tools team found: 

Flatmap-stream 0.1.0 is a poisoned package as discussed here: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

Who updates this package, the open source community, Microsoft?

**Comment by patmill** [comment]
So this was mentioned earlier, and I'm not sure how you are getting into this state.  Can you see where the dependency is coming from, by running 
` npm list flatmap-stream `

I'm running this, and not seeing it anywhere.  We cleaned up our dependencies to the packages bringing the offending package in quite a while ago (a day or two after the report).

Is there a possibility that you have an older package of ours cached in your own repo, and that's referencing the older package?

**Comment by AndreJones216** [comment]
I apologize for not searching through the issues thread for more information with the packages we detected. I will do that before posting.

This has been held up by our security/legal team for a while. However there were other packages that we found for example: basic-auth-connect@1.0.0.

Are you suggesting that the generators have been updated and I should retry pulling in the latest generator?

**Comment by patmill** [comment]
No worries - I only mention it in that you aren't the only one seeing this, but I'm not sure why.

Even an old generator shouldn't get this, as we had an indirect dependency (ie, we used stream, and it used flatmap) and our dependency was updated.

Is it possible you have these references in a package lock file?

Can you try running the npm list flatmap-stream though?  It should show the full dependency tree w/ versions, and we can see where it is coming from.

**Comment by AndreJones216** [comment]
We will need to close this item for now. I need to work with our security team to get the entire package in our environment for review with the updated package.
