### ISSUE TITLE
Typo in "Sporadic traffic" paragraph?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [SharePoint/sp-dev-docs#4106]
Hi, would you mind checking the following sentence from the "Sporadic traffic" paragraph.  I'm either misunderstanding something or there's a typo:
"These apps include sync engines, backup providers, search indexers, classification engines, data loss prevention tools, and any other which attempts to reason over the entirety of data and change."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
While technically correct, it could be wordsmithed a bit. I'll add that to my backlog.

The last part of the sentence is saying essentially restating the rest of the sentence. Basically "any other tool that attempts to reason over lots of data and any changes to that data" resulting in a lot of HTTP calls...
