### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#4107]
Can you give some examples of And Or queries with a combination of fields? Trying to troubleshoot the syntax vs CAML query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#feedback)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Refer to the docs on CAML: https://docs.microsoft.com/en-us/sharepoint/dev/schema/and-element-query

**Comment by eschrader** [comment]
Wait, so does ODATA use CAML or a different syntax?

**Comment by andrewconnell** [comment]
Sorry... misunderstood your question. Thought you were asking about doing CAML queries via ODATA.

Look at the links at the bottom of this page. There's "odata resources" and that page points to the OData protocol docs. Makes more sense to go there than it does to dupe OData docs in SharePoint REST docs
