### ISSUE TITLE
Graph client calls not working in IE 10 on classic pages

### ISSUE THREAD

**Issue by clarktozer** [SharePoint/sp-dev-docs#4108]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In SPFx 1.7 create a webpart and make a call to the graph api using the graph client ([tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)).

#### Observed Behavior

Any request to get data from the graph api will fail as there is a "const" variable in the sp-http-adal file. In IE 10 this is a syntax error. IE 11 works fine. Attached is screenshots from Chrome dev tools and IE dev tools. I have seen this [related issue](https://github.com/SharePoint/sp-dev-docs/issues/3562) but it doesnt solve the syntax error for IE 10. 

![chrome-devtools](https://user-images.githubusercontent.com/9270883/59079740-7966fb00-8928-11e9-80ed-162cf8d85b25.png)

![ie-devtools](https://user-images.githubusercontent.com/9270883/59079741-7c61eb80-8928-11e9-8de1-63fec0fab89f.png)

#### Steps to Reproduce

- Create SPFX webpart using yeoman generator
- Get the graph client off the SPFX context object and make a call to the graph API
- Deploy SPFX webpart
- Create a classic page and add the webpart to the page in IE
- IE Dev tools will have the syntax error resulting in the webpart not working

**Comment by patmill** [comment]
Unofrtunately, IE 10 is not a supported browser.  This is the supported browser page - https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452
