### ISSUE TITLE
Latest version of Office UI Fabric React Components do not work with SPFx RC0 React web part

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#411]
#### Category
- [X ] Bug

#### Expected or Desired Behavior
Create SPF React web part with yo

Install latest version of Office UI Fabric React Components (**npm install office-ui-fabric-react@latest --save**)

**gulp serve**

Web part compiles **successfully**

#### Observed Behavior
Create SPF React web part with yo

Install latest version of Office UI Fabric React Components (**npm install office-ui-fabric-react@latest --save**)

C:\ToddSPFx\ReactComponentsTest>npm install office-ui-fabric-react@latest --save
react-components-test@0.0.1 C:\ToddSPFx\ReactComponentsTest
`-- office-ui-fabric-react@1.4.0
  `-- @uifabric/utilities@1.0.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@* (node_modules\@microsoft\gulp-core-build-webpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**gulp serve**

Web part **DOES NOT compile successfully**

C:\ToddSPFx\ReactComponentsTest>gulp serve
Build target: DEBUG
[09:38:43] Using gulpfile C:\ToddSPFx\ReactComponentsTest\gulpfile.js
(node:23460) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:38:43] Starting gulp
[09:38:43] Starting 'serve'...
[09:38:43] Starting subtask 'pre-copy'...
[09:38:43] Finished subtask 'pre-copy' after 7.61 ms
[09:38:43] Starting subtask 'copyStaticAssets'...
[09:38:43] Starting subtask 'sass'...
[09:38:45] Finished subtask 'sass' after 1.43 s
[09:38:45] Starting subtask 'tslint'...
[09:38:45] Starting subtask 'typescript'...
[09:38:45] [typescript] Using custom version: 2.0.10
[09:38:45] Finished subtask 'copyStaticAssets' after 1.48 s
[09:38:50] Error - typescript - node_modules\@uifabric\utilities\lib\scroll.d.ts(1,51): error TS1039: Initializers are not allowed in ambient contexts.
[09:38:50] Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(1,43): error TS1039: Initializers are not allowed in ambient contexts.
[09:38:50] Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(2,36): error TS1039: Initializers are not allowed in ambient contexts.
[09:38:50] Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(3,38): error TS1039: Initializers are not allowed in ambient contexts.
[09:38:50] Error - typescript - node_modules\office-ui-fabric-react\lib\utilities\selection\interfaces.d.ts(4,39): error TS1039: Initializers are not allowed in ambient contexts.
[09:38:50] Finished subtask 'tslint' after 4.87 s
[09:38:50] Error - 'typescript' sub task errored after 4.87 s
 "TypeScript error(s) occurred."
[09:38:50] 'serve' errored after 6.34 s
[09:38:50]
[09:38:50] ==================[ Finished ]==================
Error - typescript - node_modules\@uifabric\utilities\lib\scroll.d.ts(1,51): error TS1039: Initializers are not allowed in ambient contexts.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(1,43): error TS1039: Initializers are not allowed in ambient contexts.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(2,36): error TS1039: Initializers are not allowed in ambient contexts.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\ColorPicker\colors.d.ts(3,38): error TS1039: Initializers are not allowed in ambient contexts.
Error - typescript - node_modules\office-ui-fabric-react\lib\utilities\selection\interfaces.d.ts(4,39): error TS1039: Initializers are not allowed in ambient contexts.
Error - 'typescript' sub task errored after 4.87 s
 "TypeScript error(s) occurred."
[09:38:51] Project react-components-test version: 0.0.1
[09:38:51] Build tools version: 1.1.0
[09:38:51] Node version: v7.0.0
[09:38:51] Total duration: 11 s
[09:38:51] Task errors: 6

#### Steps to Reproduce
Create SPF React web part with yo

Install latest version of Office UI Fabric React Components (**npm install office-ui-fabric-react@latest --save**)

**gulp serve**

**Comment by chakkaradeep** [comment]
Yes, this is expected. As Fabric and Fabric React are coupled with the SharePoint Framework & SharePoint deployments, they rely on the specific version that is rolled out. We will be updating this in the documentation as we move towards GA. 

Also note that if you use yeoman generator, the generator will scaffold the project with the right versions required. It is when you are migrating you will need to know the exact versions for that release or drop.

The current version of Fabric and Fabric React for RC0 is as follows:

- react 0.14.8
- react-dom 0.14.8
- office-ui-fabric-react 0.69.0

**Comment by TBag** [comment]
Got it, thanks @chakkaradeep .  I'll close this one.

**Comment by russgove** [comment]
Does this mean that we cannot use a later version of fabric than that which is used by SPFX?

**Comment by jlemoo** [comment]
so, I'm trying to work through this tutorial https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components and it doesn't work because of this issue. How would I fix it?

**Comment by chakkaradeep** [comment]
@jlemoo yea, right now i am working on that. I will have some update by tomorrow.

@russgove Please see this issue #384

**Comment by AmrHamam** [comment]
@chakkaradeep any solution for this? as im trying to work through same tutorial https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components and it doesn't work because of this issue.
How would i fix it?

**Comment by AmrHamam** [comment]
@chakkaradeep  I followed the tutorial in https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/spfx/web-parts/get-started/use-fabric-react-components.md  and it worked for me, looks like the video is not updated but this url is updated

**Comment by chakkaradeep** [comment]
@AmrHamam are you referring to the PnP Video in that tutorial? @VesaJuvonen can help out there.

But glad to know the tutorial steps are working. 

Thanks!

**Comment by AmrHamam** [comment]
@chakkaradeep  @VesaJuvonen  The video tutorial is not accurate now due to the updates, but the written one is updated so it works without any problem.
This note in written tutorial explains everything:

> Important: You must upgrade existing projects to use @microsoft/sp-build-web@1.0.1 or later to use Office UI Fabric React. Easiest way to achieve this is to ensure that you have latest package by running npm install -g @microsoft/generator-sharepoint in your console before completing this tutorial.

**Comment by VesaJuvonen** [comment]
thx @AmrHamam for confirming the challenge. We obviously can't keep all the videos unfortunately completely up to date all the time, which is a bit unfortunate, but written guidance is meant to be always 100% up to date. Just a FYI -  We are looking to refresh all the guidance videos in Ignite 2017 time frame - so in Sep-Oct.
