### ISSUE TITLE
div with the class "dragIconContainer disableMouseEvents" appears at the top left of the suite bar

### ISSUE THREAD

**Issue by Chaitra1006** [SharePoint/sp-dev-docs#4112]
Below div is added to whenever a page is edited inside <body> tag after <style> tag, which will end up appearing as box at the top left of the header when a page is edited.
<div class="dragIconContainer_6bb55d22 disableMouseEvents_6bb55d22"><div class="dragIcon_6bb55d22"><i data-internal-id="iconControl"></i></div><div class="dragText_6bb55d22 ms-fontSize-m" data-internal-id="textControl"></div></div>

![image](https://user-images.githubusercontent.com/38909384/59100652-55b1ae00-8944-11e9-82af-52664b058eea.png)

SPFx application extension is used to display a header with a functionality to hide and display OOTB Office365 suite bar.
Mentioned div tag disappear when the Office 365 suite bar is displayed.
It can be reproduced in both Team and Communication site by editing any page/news post.
#### Category
- [x] Question

#### Expected or Desired Behavior
<div class="dragIconContainer_6bb55d22 disableMouseEvents_6bb55d22"> should not load

#### Observed Behavior
<div class="dragIconContainer_6bb55d22 disableMouseEvents_6bb55d22"> should loads and display a box in the top left corner of the header.

#### Steps to Reproduce
1. Use a SPFx application extension to display custom header with a icon to hide/display OOTB Office365 header
2. Edit a page
3. Mentioned div tag is loaded with the box at top left corner
![image](https://user-images.githubusercontent.com/38909384/59100065-9ad4e080-8942-11e9-8f14-a603d98f7755.png)

![image](https://user-images.githubusercontent.com/38909384/59099973-50ebfa80-8942-11e9-9ff0-0b9fb7038d06.png)

**Comment by patmill** [comment]
Trying to clarify this.  While hiding arbitrary elements on a page can't be blocked, it's also not "supported".  If the page changes over time and additional elements are added, changed, etc. that isn't a bug.  Are you seeing odd behaviour that an end user would see?

**Comment by Chaitra1006** [comment]
Agree, have modified to a question.
The same customization was working absolutely fine couple of days back.

**Comment by Chaitra1006** [comment]
Observed the duplicate div gets rendered when page is Edited multiple times on a OOTB site with no customization.
![image](https://user-images.githubusercontent.com/38909384/59342145-cda61c80-8d26-11e9-9601-5192ea5750b6.png)

**Comment by patmill** [comment]
OK, I've forwarded this to the owning team.  However, what you are trying to do (modify arbitrary elements on a page) isn't supported, meaning that if your solution breaks, it's not an issue with the product that would necessarily be fixed. Thanks for the heads up though.
