### ISSUE TITLE
SPfx Web Part on Classic Wiki Page - Supported?

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#412]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Web Part will render correctly on classic Wiki Page (in Wiki Content area).

#### Observed Behavior
Adding web part to a classic Wiki Page results in the following intermittent error:
`[SPWebPartErrorCode.IncorrectBoostrapModule]:: Bootstrap module for web part WebPart.ProjectTimelineWebPart.g_40ba90e0_80a7_4e39_bfd9_743fa1d9f236 not of the correct type. Make sure to export your web part as 'export default WebPartName'. CALLSTACK:: Error at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.006/sp-loader_en-us_c6554f8ef470ee0d617402401b9e20e1.js:57:16567) at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.006/sp-webpart-base_en-us_6e4f6353e26c918a168d3e0f5f02168a.js:47:22094) at t.createWithLogProperties (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.006/sp-webpart-base_en-us_6e4f6353e26c918a168d3e0f5f02168a.js:47:22628) at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-16.006/sp-webpart-base_en-us_6e4f6353e26c918a168d3e0f5f02168a.js:47:31292) LOGPROPERTIES:: {"actualType":"object","wp":{}}`

It doesn't happen on every page load, only occasionally and I cannot seem to find a reason/pattern.
It seems to work fine on a classic Web Part Page in Web Part Zone.

**Comment by manishgarg1** [comment]
Hi @sparkitect, a fix is rolling out soon. We know about these issues. Thanx for your feedback.

**Comment by sparkitect** [comment]
Ok, thanks!

**Comment by manishgarg1** [comment]
@sparkitect, is this fixed ? If yes, please close the issue.

**Comment by sparkitect** [comment]
Can't reproduce it now; closing issue.

**Comment by araver** [comment]
This is still an issue.

**Comment by craghavendra21** [comment]
Hi, All I am getting this issue in normal classic page.

`
[SPWebPartErrorCode.IncorrectBoostrapModule]:
Bootstrap module for web part WebPart.PowerLinksWebPart.g_32239c64_e2c5_46fa_ae64_b9040049f2e0 not of the correct type. Make sure to export your web part as 'export default WebPartName'.

***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:201:20910)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:26738)
    at Function.t.createWithLogProperties (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:27319)
    at e._instantiateWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:44485)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-10.009/sp-classic-page-assembly_en-us_89fc552e11063ddb601e966dd2b79117.js:301:32598
    at <anonymous>
***LOGPROPERTIES:
{"actualType":"object","wp":{"config":{"_settings":{"keys":[],"values":[]}},"graph":{},"sp":{"_options":{},"_baseUrl":""},"storage":{"_local":null,"_session":null}}}
`

Please help with this

**Comment by waldekmastykarz** [comment]
@craghavendra21 which version of the SharePoint Framework are you using in your project?

**Comment by Masood10** [comment]
I am also getting the same error. I am using the latest version of spfx 1.4.1. Is there some problem with the 1.4.1 version compatibility with react, gulp etc
