### ISSUE TITLE
Sorting and limiting the number of items on SPFx webpart 

### ISSUE THREAD

**Issue by gargankush010** [SharePoint/sp-dev-docs#4120]
Hello Everyone,

I am new to SPFx development so please bear with my mistakes or lack of knowledge.

I have created a webpart using typescript framework in spfx and the data that is getting displayed consists of URL in anchor tag , the text and a specific icon for that URL. 

Now i want to provide a functionality in which user edits the webpart and he can sort the items and also limit the number of items to be shown on webpart. How do i do that? I am attaching a picture of the item that is being displayed on my webpart. 

![DataonWebpart](https://user-images.githubusercontent.com/50606842/59192540-1c887080-8bc6-11e9-8dd7-a1916c882784.PNG)

**Comment by andrewconnell** [comment]
You're describing an admin like experience... check out the property pane for allowing editing admin -like capabilities of the web part: https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/basics/integrate-with-property-pane
