### ISSUE TITLE
Sorting SPFx custom action buttons in modern list experience

### ISSUE THREAD

**Issue by remar27** [SharePoint/sp-dev-docs#4121]
Hello,

I have developed important feature for our company using SPFx ListView Command Set extension. Also we use many 3rd party SharePoint Add-ins from app source. 

So the main question and problem: 
it is possible to control SPFx custom action button ordering? Sequence parameter is not working. The only thing I was able to do is to control ordering between SPFx custom action buttons but not over SharePoint Add-in buttons.
My requirement is to make SPFx custom action button higher priority over other 3rd party add-in buttons.

![image](https://user-images.githubusercontent.com/15183344/59196955-9ba68600-8b7f-11e9-8c87-d2b82eba6c82.png)

I did some tests with SharePoint Online PowerShell and tried to experiment with custom action "sequence" property. After some tests I noticed that toolbar is divided into two groups: SharePoint Add-in buttons and SharePoint Framework buttons. I can change ordering by changing UserCustomAction.Sequence property value but ordering is changed only in the group. I can't force to go my SPFx buttons first over SP Add-ins. Also I can't to move SPFx button between two SP Add-in buttons.

So maybe is possible to change SPFx custom action ordering over SharePoint Add-in custom action ordering? Without workarounds (I can do this with javascript but is not recommended...).

Thanks :)

#### Category
- [x ] Question

**Comment by patmill** [comment]
That sounds like a bug.  The sequence number is supposed to control that.  Let me see if I can find someone to comment.  Thanks.

**Comment by lucabandMSFT** [comment]
After further investigation we identified that, unfortunately, that is not possible today.
Please provide your vocal feedback on UserVoice: that will help us properly triage this requirement and hopefully bring this feature to you soon

**Comment by FlorianLabranche** [comment]
Hello,

As I haven't found one, I've posted a new [idea](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37914715-use-sequence-parameter-to-sort-listview-command-se) on UserVoice.

Go give it a like 👍
