### ISSUE TITLE
How to set SPFx Field Customizer SharePoint Column width #spfx

### ISSUE THREAD

**Issue by georgenorberg** [SharePoint/sp-dev-docs#4122]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm developing a field customizer that takes a JSON value and renders different elements such as informative texts, buttons with custom behavior etc.

I've noticed that when a new user enters the list all fields have a default width. I've noticed that SharePoint JSON-Formatting of a field does not work as it seems to overwrite the rendering of my field completely.

Resizing the column and saving the view seem to work for the current user but does not have affect on other users experience.

I would like to know if its possible to set a columns width for the modern experience some other way or if its possible to do so from the SPFx solution.

Here you can see two examples of my SPFx Field Customizer. In the first image you can see the field as viewed by a new user and the second the way i would like it to be implemented (after resizing the field).

Picture 1:
![1](https://user-images.githubusercontent.com/24222739/59206627-a1af5d80-8ba5-11e9-916d-625161b6c785.PNG)

Picture 2:
![2](https://user-images.githubusercontent.com/24222739/59206639-aa079880-8ba5-11e9-8e1d-35dc0f22668b.PNG)

**Comment by thechriskent** [comment]
The column sizes are stored in Local Storage on individual user's machines. You can find them with entries in the form of SPColumnSize-VIEWGUID stored as an object with the internal column name and the size of the column in pixels. Like this:

![image](https://user-images.githubusercontent.com/8364109/59340078-509d8780-8cd3-11e9-9b27-39e3dbe2eae1.png)

I'm not aware of any open API to set these values. Technically you could be able to write these values yourself from a SPFx Field Customizer (NOT list formatting) but just writing the value wouldn't have effect until a refresh and a user could always override this value by resizing.

**Comment by georgenorberg** [comment]
@thechriskent interesting and thanks for the info 👍 I'm thinking this could fit well in the onInit function and I will definitely try it out. 

If there are other ways to do this I would appreciate it as this does not really fulfill my requirements due to the user having to reload the page. It would be great if this was supported to set the width some other way.

I have one more question, In my case, this field will be present in different lists and libraries throughout a staging environment so I would like to fetch the viewguid of the current context but I can't seem to find a way to do this, any tips?

**Comment by thechriskent** [comment]
I believe you can get the view id by using `this.context.pageContext.legacyPageContext.viewId`

You can find out more about [legacyPageContext in the docs](https://docs.microsoft.com/en-us/javascript/api/sp-page-context/pagecontext?view=sp-typescript-latest#legacypagecontext). Why it hasn't been added as part of the TypeScript API yet, I don't know.

**Comment by georgenorberg** [comment]
I would really like to see this as a feature to be able to set the width more easily.

**Comment by andrewconnell** [comment]
@georgenorberg best approach then is to submit a feature request via user voice (https://aka.ms/sp-dev-uservoice
