### ISSUE TITLE
addna

### ISSUE THREAD

**Issue by MikeJDavis** [SharePoint/sp-dev-docs#4125]
I have a question about addNavLink in the JSON file.  

I would like to push the standard "Planner" link into the SPO site's navigation list, so it's visible to the site's members from the start.   

Unfortunately, I can't figure out how to script that without coding a URL that is unique to a) each O365 group and b) its Planner ID.    This seems out-of-reach for the JSON schema.

Is there a work-around, so I actually can manage this in a JSON script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
The solution is to reference to "_layouts/15/groupstatus.aspx?target=planner" url. This url points to the default planner of Office 365 group. This way you need neither the Planner ID nor the group ID. This is what the site script looks like:

{
    "verb": "addNavLink",
    "url": "/_layouts/15/groupstatus.aspx?target=planner",
    "displayName": "Planner",
    "navComponent":"QuickLaunch",
    "isWebRelative": true
}
