### ISSUE TITLE
Not able to download Bot Framework V4 Emulator for windows.

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#4129]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi Team,

Currently we are not able to down load Bot Framework V4 Emulator from the link (https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.4.2). When we try to download the .exe file for windows,  an xml file gets opened with a message - "**The request signature we calculated does not match the signature you provided. Check your key and signing method.**". Please assist us here.

**Comment by AJIXuMuK** [comment]
Hi @srisspfx - probably it's better to ask that question in Bot Framework Emulator repo. This one is for SharePoint dev questions.

**Comment by srisspfx** [comment]
Okay. Thanks. Do we have any best approaches to develop Chat bots in using SPFx in modern pages?
