### ISSUE TITLE
group-less modern Team site template

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#4130]
As per this document I should be able to create group-less modern Team site template with -WebTemplate value "1" but when I created site design with -WebTemplate value "1" its not available under drop down to choose from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a433bf-b243-03ff-f733-484dca2be753
* Version Independent ID: 7a173ed3-1700-b24f-ee78-417dd494ce16
* Content: [Get started creating SharePoint site designs and site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design)
* Content Source: [docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/get-started-create-site-design.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by KEMiCZA** [comment]
@ravick4u https://github.com/SharePoint/sp-dev-docs/issues/4103#issuecomment-501250561

**Comment by melitoSP** [comment]
@ravick4u On SharePoint start page (previously referred to as SharePoint home page), for site designs we respect the WebTemplate. Therefore if you have a site design with WebTemplate = 64, it should only show for group connected sites. If your site creation experience is for non-group connected team sites, only site designs with WebTemplate = 1 would show.

**Comment by arnieraju** [comment]
@melitoSP I believe I have the same issue (or potentially a question).  

I have added a site design to my tenancy for a non-group connected Team site.  Should I expect to see this when I am creating a non-group connected Team site from the SharePoint admin center? i.e. should I expect a drop down with designs to choose from in the screenshot below?

![image](https://user-images.githubusercontent.com/1208184/65925533-adfd4600-e434-11e9-9f78-79f9d88a74a8.png)
