### ISSUE TITLE
Content Security Policy errors in Safari

### ISSUE THREAD

**Issue by justdevelopment** [SharePoint/sp-dev-docs#4131]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

For Safari to work without 50+ errors :)

#### Observed Behavior

When loading a modern page from SPO Safari gives a ton of errors regarding Content Security Policy. We've seen this issue in the past but it was fixed. As of this morning it seems to have returned on at least 3 separate tenants (we can send tenant URL if wanted). 

![image](https://user-images.githubusercontent.com/23448165/59359889-78bad400-8d2f-11e9-91ac-7cf6f4ee2e0c.png)

~~I also experience issues login into ms-graph-client on SPFx, but I'm not sure if this issue is related as my coworker can login just fine using his Mac + Safari. I get an error AADSTS50058, but it loads fine using Private? Just adding in case it is related.~~ Nevermind, this has been solved. Main issue remains.

#### Steps to Reproduce

Login to your favorite SPO tenant, navigate to the SharePoint landing page and open the Web Inspector.

**Comment by patmill** [comment]
Well that's a bit weird.  Can you look at the response headers of the main page and see what the CSP report header policy is and paste it here?

**Comment by AJIXuMuK** [comment]
I see the same in Safari.
```
Content-Security-Policy-Report-Only: script-src 'strict-dynamic' 'unsafe-eval' 'nonce-afde21ba-1ce4-48c1-b377-2174f30ff367' ; report-uri https://splst.sharepoint.com/sites/SPHubDiscussions/_layouts/15/CSPReporting.aspx
```

**Comment by patmill** [comment]
OK - so it makes sense that the report would fire, since Safari apparently has no idea what CSP3 is.  The strange this is why would you only notice it now (unless safari rolled out then rolled back support).  I'm currently working on updating the CSP code, so I'll make note of Safari (and IE) getting confused.

**Comment by AJIXuMuK** [comment]
@patmill - from my side - I open Safari dev tools once in few months :) So I noticed it after reading this issue :)

**Comment by justdevelopment** [comment]
I see the same CSP as Alex, no change yet, glad that it at least makes sense :)

I also don't really use Safari as my daily dev browser, I noticed it yesterday because I got some other bug reports that needed looking into. I was seeing the issue in Safari 12.1 and it remains after updating to 12.1.1

**Comment by justdevelopment** [comment]
@patmill Any chance for an ETA on this? The issue still occurs and I would like to know what to tell our customers :)

**Comment by Gmeeler** [comment]
same problem here, using Safari as default browser for all users, lots of pages not loading properly. For instance modern site contents pages remain blank, file viewer web parts not working with Word or PDF files.

**Comment by tritter** [comment]
Any updates on this? I am also seeing many content security errors!! I get around 50.

**Comment by DaniCorretja** [comment]
Any updates, please? I'm also seeing many content security policy errors. I'm also experiencing an issue where the SPFx web parts using the Office Graph API are not working in Safari and I wonder if this is related?
