### ISSUE TITLE
SPFX Extension - Command button not displayed in document library but only on custom lists after app deployment 

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-docs#4136]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Command button should be displayed on document libraries.
#### Observed Behavior
Command button is displayed only  on custom lists
#### Steps to Reproduce

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

- Elements.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction 
        Title="SPFxListViewCommandSet"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="588a8428-4372-4700-af0b-26f01a9ad11d"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
</Elements>
```

**Comment by PoojaDhingra** [comment]
Any update on this issue i am still facing i all command set extensions!!!

**Comment by Gowtham171996** [comment]
I solved the issue by using the changing in elements.xml file to
`<CustomAction
        Title="PublishButtonreplica"
        **_RegistrationId="109"_**
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="7647cd55-a132-47fa-a70a-43790e785177"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>`

**Comment by andrewconnell** [comment]
@FullStackRafik can you confirm you are still seeing the issue?

**Comment by FullStackRafik** [comment]
@andrewconnell Actually, I resolved the issue just by increasing the version number and updating the clientsideinstance.xml:
   "elementManifests": [
            "elements.xml",
            "clientsideinstance.xml"
          ]
        }
 I Uninstalled the app installed in web, Deleted the app,Uploaded the app to app catalog and Installed the app again in the web.

But I still always using the same RegistrationId 101.
