### ISSUE TITLE
Adding descriptions to tags would help people understanding the flow

### ISSUE THREAD

**Issue by baywet** [SharePoint/sp-dev-docs#4137]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Feedback on repo organization
- [x] More work for AC

#### Expected or Desired Behavior
Lots of tags today don't have descriptions. I think this doesn't help people understanding the flow and where are their issues at in terms of replies/being sloved etc...
Adding clear descriptions to every tag about what they need, what's the next step would help people understand, making the life of maintainers easier
CC @andrewconnell

**Comment by andrewconnell** [comment]
Boom: it’s done
