### ISSUE TITLE
CSS is not working after upgrading from spfx 1.7.1 to 1.8.2

### ISSUE THREAD

**Issue by vimalpatel1826** [SharePoint/sp-dev-docs#4139]
I upgraded all my solutions (Header/Footer Application Customizer & Few Web Parts) from 1.7.1 to 1.8.2 using the _spfx project upgrade cmd_ using office 365 CLI. All the solutions build and deployed without any issues. But the Header was distorted upon testing. It references a few global classes but most of them were missing CSS upon checking them from developer tools. (.ms-Grid_col, .ms-GridRow, .ms-Grid, .ms-lg7 etc )

node version - v8.11.2
npm version - 6.9.0

Below is the snap of before and after upgrade _package.json_ 
![Before_After_Upgrade](https://user-images.githubusercontent.com/10360688/59448582-7ad66e80-8dd3-11e9-9ee5-113032cfbc04.jpg)

Interestingly, reverting and removing the packages to below makes the Header and the rest of the CSS works fine.  Note: all the spfx (microsoft) packages are all upgraded to 1.8.2 except _sp-build-web_ & _sp-webpart-workbench_ in dev dependencies. Looks like they have a dependencies on specific rush-stack/typescript versions. 

_"dependencies": {
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-lodash-subset": "1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "1.8.2",
    "@microsoft/sp-webpart-base": "1.8.2",
    "@pnp/common": "^1.2.1",
    "@pnp/logging": "^1.2.1",
    "@pnp/nodejs": "^1.2.1",
    "@pnp/odata": "^1.2.1",
    "@pnp/sp": "^1.2.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "classnames": "^2.2.5",
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "sp-pnp-js": "^3.0.4"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.1",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.7.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "5.0.0"
  }_

Trying to figure out what exactly is causing it to break. Looks like react,react-dom along with the types when reverted back to there original versions along with removing the rush stack and other dependencies do the trick. Not sure if its the right fix/approach but it works. 

Since the Header loads first are there any precedence conflict between _sp-office-ui-fabric-core_ vs _office-ui-fabric-react_? 

Is react/react-dom along with the _types_ the issue?

**Comment by andrewconnell** [comment]
Did you see the release notes in 1.8.2 about the changes to CSS?

https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#deprecating-legacy-fabric-css-consumption

**Comment by vimalpatel1826** [comment]
Yup thx andrew!! _”loadLegacyFabricCss”: true_  resolves the issue. I came across the notes shortly after creating this issue and is now resolved by setting the above property.
