### ISSUE TITLE
[Bug] SPFx webpard work on workbench but error when add to page

### ISSUE THREAD

**Issue by phamquocthang** [SharePoint/sp-dev-docs#414]
I managed to create a default web part using the tutorial on dev.office.com, with RC0 updated. The web part works just fine on workbench, however, showed errors when I tried to add to both classic and modern pages

`[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.SpfxContactsWebPart.d1bc6cb9-375f-4e36-9ebc-c4ecc04ba4b2,Error: ***Failed to load component "68e51384-4cd9-4b89-85d8-3a7f13f4a4f1" (SpfxContactsWebPart). Original error: Error loading https://component-id.invalid/68e51384-4cd9-4b89-85d8-3a7f13f4a4f1_0.0.1 script resources due to: undefined. CALLSTACK:: t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.017/sp-loader_en-us_c74e875cb1e6e4596e88d56a5ce1a27a.js:57:18038 t@https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.017/sp-webpart-base_en-us_6db76028c45120ea42004229244f8a94.js:47:22051 __WEBPACK_AMD_DEFINE_RESULT__</</p</t.create@https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.017/sp-webpart-base_en-us_6db76028c45120ea42004229244f8a94.js:47:22502 __WEBPACK_AMD_DEFINE_RESULT__</</E</e.prototype.loadWebPart/</<@https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.017/sp-webpart-base_en-us_6db76028c45120ea42004229244f8a94.js:48:697 `

![image](https://cloud.githubusercontent.com/assets/6511700/22698066/721b0e50-ed8e-11e6-888e-1e6f0705d35d.png)

Please instruct me for a solution

**Comment by manishgarg1** [comment]
Hi @phamquocthang, are you running gulp serve while loading this web part ?

**Comment by manishgarg1** [comment]
@phamquocthang, do things work fine when it is running ?

**Comment by mauricionr** [comment]
try add the wp with gulp serve running 😄

**Comment by phamquocthang** [comment]
@mauricionr Exactly! It works! But I remember that I didn't let gulp serve running in previous releases, or my memory is messy??

**Comment by manishgarg1** [comment]
Hi @phamquocthang, so this is how it works. When you build your web part all the code is on your local host. So you need gulp serve to be running. Only once you do the "deploy" step to deploy it to a CDN, does the need for local gulp serve go away. 

Please close the issue if you feel your question has been answered.

**Comment by phamquocthang** [comment]
Okay, I got it. So when I upload the .sppackage to app catalog, the code is not uploaded along.
Please close the issue

**Comment by manishgarg1** [comment]
Hi @phamquocthang, No., The deploy step is required for that.
