### ISSUE TITLE
ListView Command cannot pick up new custom properties from serve.json

### ISSUE THREAD

**Issue by harrychen1** [SharePoint/sp-dev-docs#4144]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

Build the SPFX extension OoB ListView Command project. Then try to add a new custom property called "sampleTextThree" with value "This is new text.". However, this cannot be retrieve from the code.

Here is the way to reproduce and workaround.

1. Add sampleTextThree as string in the interface

export interface IExampleCommandSetProperties {
  // This is an example; replace with your own properties
  sampleTextOne: string;
  sampleTextTwo: string;
  **sampleTextThree: string;**
}

2. Add property to serve.json like below.

  "serveConfigurations": {
    "default": {
      "pageUrl": "https://mysompont.sharepoint.com/sites/HarryTestX/Shared%20Documents/Forms/AllItems.aspx",
      "customActions": {
        "4de6483f-cccf-465d-b0ee-4aa6ebb0eb81": {
          "location": "ClientSideExtension.ListViewCommandSet.CommandBar",
          "properties": {
            "sampleTextOne": "One item is selected in the list",
            "sampleTextTwo": "This command is always visible.",
            **"sampleTextThree": "This is new text."**
          }
        }
      }
    },
...

3. Change the default alert to use new property.

  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
        Dialog.alert(`${this.properties.sampleTextOne}`);
        break;
      case 'COMMAND_2':
        Dialog.alert(`${**this.properties.sampleTextThree**}`);  // This was this.properties.sampleTextTwo as OoB
        break;
      default:
        throw new Error('Unknown command');
    }
  }

4. Gulp serve run locally is fine. After this deployed to tenant, the property cannot be found and is "null".

Here is the workaround:

Add another step#5.

5. Add the new custom property to "elements.xml" like below.

        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;**, &quot;sampleTextThree&quot;:&quot;This command is new text.&quot;**}">

New the property can be retrieved and displayed.

Here is the question.

Do we need to add new property to  "elements.xml"? Should the properties inside serve.json to be automatically build into  "elements.xml"?

Thanks.

**Comment by andrewconnell** [comment]
This isn't valid: `${**this.properties.sampleTextThree**}` ... it won't see this property with the asterisks in the code.

Also ensure you recycle the local web server (ie: terminate `gulp serve` and restart it) after making the change. The serve configuration defined in **serve.json** is only read when `gulp serve` is run. All this does it create the special URL that will load the extension from your local web server, and include the new property in the URL.

**Comment by harrychen1** [comment]
Sorry. I meant ${this.properties.sampleTextThree}.

We can close this case if server.json is only available by running locally gulp serve. I've added the property into "elements.xml" that works.

My question is that if the properties inside serve.json to be automatically build into "elements.xml"?

If not, this is enhancement request.

**Comment by andrewconnell** [comment]
No... that’s not how it works. While I understand you say this is an enhancement request, that’s not how it’s intended to be used so I doubt MSFT will approve. But feel free to submit to the aka.ms/sp-user-voice list as that’s where feature requests go.

**serve.json** is used by the `gulp serve` command and is only intended to be used to make your life easier so you don’t have to create the debugging url by hand (as we used to when extensions were initially released).

What goes in **elements.xml** is what will be deployed.
