### ISSUE TITLE
"Provision classic team sites in a Multi-Geo environment" incorrectly states that SPO multi-geo is still in preview

### ISSUE THREAD

**Issue by zplume** [SharePoint/sp-dev-docs#4146]
The following pages state that "SharePoint Online Multi-Geo is currently in preview and is subject to change":

* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-permissions
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-onedrive
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-apps
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-userprofileexperience
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-managedmetadata
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-contenttypehub
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-bcsandsecurestore
* https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sampleapplicationsetup

This conflicts with the announcement on the following page, which states that "Today, we’re thrilled to announce the General Availability of Multi-Geo Capabilities in SharePoint Online and Office 365 Groups":
https://techcommunity.microsoft.com/t5/Office-365-Blog/Now-available-Multi-Geo-in-SharePoint-and-Office-365-Groups/ba-p/263302

Please can the pages be updated given that SPO multi-geo is now GA (as per the link above).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d299ba9c-d4c4-a7e7-fc63-ff348347c519
* Version Independent ID: 0c1db9b5-5f74-3db4-9518-6950aa23d929
* Content: [Provision classic team sites in a Multi-Geo environment](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning)
* Content Source: [docs/solution-guidance/multigeo-sites-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/multigeo-sites-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... the content has been updated.
