### ISSUE TITLE
Is Cross-site publishing supported for Sharepoint Online ?

### ISSUE THREAD

**Issue by annigam01** [SharePoint/sp-dev-docs#4151]
I am trying to verify if the Cross site publishing is supported for sharepoint online Classic sites AND sharepoint online Modern sites ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa4eef7-53cf-6150-a817-ae4bbfc49e10
* Version Independent ID: b338a9f5-265a-713c-d2ac-59ea585eb8a0
* Content: [Cross-site publishing in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/cross-site-publishing-in-sharepoint)
* Content Source: [docs/general-development/cross-site-publishing-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/cross-site-publishing-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Cross-site publishing is only available in on-premises environments. We have just added environment note on the document, which will be visible within next 30 min.

**Comment by cblomart** [comment]
@VesaJuvonen some do use cross site publishing on SharePoint Online. Your modification took them by surprise.

Here are some reference supporting the view of cross-site publishing as supported:

* The [SharePoint Online service description ](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description) indicates that cross-site publishing is available to SharePoint P2 (and E3) with a [content descitption](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/content#cross-site-publishing).
* There is even documentation on [how to activate it](https://support.office.com/en-us/article/activate-the-cross-site-publishing-feature-in-sharepoint-aef0b911-40d7-4d01-a97a-aae8c77dc177)

If the intent is to "unsupport" it, some foreword and notifications would have been good.

**Comment by VesaJuvonen** [comment]
@cblomart  - what's the use case of using cross site publishing in SharePoint Online? This capability was designed for on-premises to have publishing mechanism for anonymous users... so for doing .com sites, which are not supported in SPO. Can you clarify how it is used and what is the business case / reason for using it.

**Comment by cblomart** [comment]
Large companies: internal customers and B2B.
Editing team on company content (policies interpretation) on one site.
Search, Navigation and consultation on another site.
