### ISSUE TITLE
SharePoint Online New experience migration problems

### ISSUE THREAD

**Issue by FullStackRafik** [SharePoint/sp-dev-docs#4152]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Since 17th May, we noticed that SharePoint online has been migrated to the new experience even if that was expected on June, but no problem for that, On the other hand this migration is not stable because sometimes the lists and libraries are displayed using new experience and other times using the old experience.
We like the new experience, but it would be great to fix it and not switch between it and the old one, because that can disrupt the users.
Any responses about that please?

**Comment by VesaJuvonen** [comment]
As this is not a developer issue, we cannot unfortunately process this request through this channel. Please report the issue from the tenant administrative UIs or using Premier support, if that's an option for you. Sorry for the inconvenience.
