### ISSUE TITLE
Lookup Fields in SharePoint Online not Working Correctly

### ISSUE THREAD

**Issue by pogorman** [SharePoint/sp-dev-docs#4154]
Recently my SharePoint Online lookup fields have been defaulting to the first value in the list no matter what I select.  Example.  I upload a document, then go to set some lookup fields on that document.  When I pull up the list of values, no matter which value I select SharePoint will select the first and auto-save.  I can then change that value to something else, then click that value or select it from the list again and it will save correctly.  Basically 3 clicks for what should take 1.  We had this problem in 6 different tenants, then one day it was fixed, then the next day it was broken again. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SharePoint should allow you to select any value from the lookup field value list and auto-save with the correctly selected value.

#### Observed Behavior

SharePoint will always select the first value in the lookup field value list, regardless of what you selected.  

#### Steps to Reproduce

1. Add a generic list.  Populate it with 3 or 4 items (titles only is fine).
2. Add a new lookup column to a document library.  Configure that lookup column to point to the generic list you created in step 1.
3. Upload a document to the library. 
4. Click details on the document if the details/property pane is not yet open.  Attempt to set the value for the lookup column to any value EXCEPT the first value in the list.
5. BUG : this is where SharePoint will automatically use the first value in the lookup list, regardless of the value you selected.
6. SharePoint will autosave with the incorrect first value from the list.
 
Now here’s the work around I’ve been telling my clients.

1. Select the value you want again.  SharePoint won’t do a thing.
2. Select the value you want again or just click the lookup field drop-down since the value is already selected from step 7.
3. SharePoint will engage auto-save and save the correct value from the list.

Thanks for your contribution! Sharing is caring.

**Comment by pogorman** [comment]
As of 715 CST this morning the issue has been fixed.  I am reluctant to close this issue out though b/c last time a fix was rolled out, it was broken 24-36 hours later.  I will gladly close this out in a couple of days if the fix persists.  Mods please feel free to close out if you feel differently.

**Comment by andrewconnell** [comment]
Since nothing is broken ATM, let's close it and feel free to create a new issue if it comes up again...
