### ISSUE TITLE
Update Item wrapped in batch return Bad request

### ISSUE THREAD

**Issue by seanix99** [SharePoint/sp-dev-docs#4155]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When updating an item using a post call wrapped in SPHttpClientBatch, I expect the request succeed and not returning a bad request.

#### Observed Behavior

When using directly the post call, the call succeed. But when the post is used with a SPHttpClientBatch, the call fail and the result is "Bad request". I observed that the post call is not wrapped inside a changesets witch I think is necessary.

#### Steps to Reproduce

const requestHeaders: Headers = new Headers();
			requestHeaders.append('Content-type', 'application/json;odata=verbose');
			requestHeaders.append('Accept', 'application/json;odata=verbose');
			requestHeaders.append('X-HTTP-Method', 'MERGE');
			requestHeaders.append('IF-MATCH', '*');

			let webUrl:string = this.context.pageContext.web.absoluteUrl.toLocaleLowerCase().trim();
			let batchcreationOpts: ISPHttpClientBatchCreationOptions = { webUrl: webUrl };
			let batch: SPHttpClientBatch = this.context.spHttpClient.beginBatch(batchcreationOpts);

			let order:number = 0;

			let requests: Promise<SPHttpClientResponse>[] = [];

			for (let node of nodes) {
				let endpoint:string = Text.format("{0}/_api/web/lists/getbytitle('{1}')/items({2})", webUrl, Constants.List_SitePages_Title, node.id);
				let data:any = {
					__metadata:  
					{  
						type: "SP.Data.SitePagesItem"  
					},  
					PageOrder: order,
					WikiParentPageId: node.parentId ? node.parentId : null
				};

				let options: ISPHttpClientBatchOptions = { headers: requestHeaders, body: JSON.stringify(data) };

				requests.push(batch.post(endpoint, SPHttpClientBatch.configurations.v1, options));

				order++;
			}		
			
			batch.execute().then(() => {
				Promise.all(requests).then((responses:SPHttpClientResponse[]) => {
					responses.forEach(response => {
						console.log(response.statusText);
					  });

					  resolve();
				});
			}).catch((error) => { 
				reject(error); 
			});

regards.

**Comment by andrewconnell** [comment]
Can you provide the raw payload request & response? I'm not able to repro this...

**Comment by seanix99** [comment]
**Request Payload**

--batch_1db932b9-821e-4c92-b3a1-956bdfaf7eca
Content-type: application/http
Content-Transfer-Encoding: binary

POST https://xxxxx.sharepoint.com/sites/wikinavigation16/_api/web/lists/getbytitle('Site%20Pages')/items(22) HTTP/1.1
accept: application/json;odata=verbose
content-type: application/json;odata=verbose
if-match: *
x-http-method: MERGE

{"__metadata":{"type":"SP.Data.SitePagesItem"},"PageOrder":0,"WikiParentPageId":3}

--batch_1db932b9-821e-4c92-b3a1-956bdfaf7eca
Content-type: application/http
Content-Transfer-Encoding: binary

POST https://xxxxx.sharepoint.com/sites/wikinavigation16/_api/web/lists/getbytitle('Site%20Pages')/items(23) HTTP/1.1
accept: application/json;odata=verbose
content-type: application/json;odata=verbose
if-match: *
x-http-method: MERGE

{"__metadata":{"type":"SP.Data.SitePagesItem"},"PageOrder":1,"WikiParentPageId":3}

--batch_1db932b9-821e-4c92-b3a1-956bdfaf7eca--


**Request Response**

--batchresponse_3c071bed-4219-4e15-8689-b82d7750a7ae
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8

{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"Invalid request."}}
--batchresponse_3c071bed-4219-4e15-8689-b82d7750a7ae
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8

{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"Invalid request."}}
--batchresponse_3c071bed-4219-4e15-8689-b82d7750a7ae--

**Comment by andrewconnell** [comment]
The changeset isn't required... so that's not your issue.

However, I think I see a possible issue. The SPFx client is going to set the OData protocol version on the SharePoint REST API to 4.0 (look at the header `odata-version` in your request). However, in the above, you're using OData v3 syntax for the **content-type** and **accept** header.

For **accept**, if you really want verbose data coming back, use the value `application/json;odata.metadata=full`, but if you don't want any, use `application/json;odata.metadata=none`.

For **content-type**, just use `application/json`.

For reference, here's the payload of a request I just made for my test project:

```
--batch_ef1ce23e-11f4-4340-8a7e-5af580ca5810
Content-type: application/http
Content-Transfer-Encoding: binary

POST https://voitanosdev.sharepoint.com/sites/vdemos01/_api/web/lists/getbytitle('Apollo%20Missions')/items HTTP/1.1
accept: application/json; odata.metadata=none
content-type: application/json

{"Title":"Apollo 18","Commander":"Lovell","SrPilotCmPilot":"Swigert","PilotLmPilot":"Haise","@odata.type":"SP.Data.ApolloMissionsListItem"}

--batch_ef1ce23e-11f4-4340-8a7e-5af580ca5810
Content-type: application/http
Content-Transfer-Encoding: binary

GET https://voitanosdev.sharepoint.com/sites/vdemos01/_api/web/lists/getbytitle('Apollo%20Missions')/items?$select=Id,Title,Commander,SrPilotCmPilot,PilotLmPilot,LaunchDate,ReturnDate HTTP/1.1
accept: application/json; odata.metadata=none



--batch_ef1ce23e-11f4-4340-8a7e-5af580ca5810--
```

**Comment by seanix99** [comment]
I corrected my header and I still have the error. I give a try with a get like your second batch command, and it work with a get. It seem to only not working when updating an existing item. Can you try updating an existing item in your test ?

regards,

**Comment by seanix99** [comment]
@andrewconnell  have you been able to reproduce the bug when updating an existing item ?

**Comment by lucabandMSFT** [comment]
hey @andrewconnell, where you able to repro the issue? I'm checking if we need some investigation from our side on this issue?

**Comment by andrewconnell** [comment]
I haven't repro'd it... I just haven't had the time to create a new project that updates a list item in a batch... hence why I haven't followed up on this thread.
