### ISSUE TITLE
Formatting does not work on the Display Forms

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-dev-docs#4157]
Could it be clarified if column formatting is supposed to work on the list modern Display Forms as well as list views, the same way as it used to work in classic with JSLink? And what should happen if a field has both properties set, CustomFormatter and JSLink?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for you question!

List Formatting (column & view) are not currently supported in the forms views (display, edit, or new). List Formatting can only be applied to the display within the list view itself. However, a recent change enabled support for column formatting and rowClass style view formatting to work within the Quick Edit mode of modern list views. There is also support for list formatting within the list/library webparts.

JSLink only applies to classic sites whereas List Formatting only applies to modern. It is not possible to mix them.
