### ISSUE TITLE
OnPrem19 - Invalid App Manifest file

### ISSUE THREAD

**Issue by canbayraktar777** [SharePoint/sp-dev-docs#4158]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

.sppkg file should have been deployed.

#### Observed Behavior

There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsClientSideSolution' attribute is not declared.' on line '1', position '252'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'StartPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '344'., Xml Validation Exception: 'The element 'App' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'AppPrincipal' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '357'.

![onPremIssue](https://user-images.githubusercontent.com/19236242/59659994-1db23280-91b0-11e9-9ccd-4e9832176b93.PNG)

#### Steps to Reproduce
```
yo @spfx/pnp
```

pnp selections:

Sharepoint 2019 onwards selection is enough by itself. Almost tried every other combination.

![pnpSelections](https://user-images.githubusercontent.com/19236242/59659975-125f0700-91b0-11e9-99d9-8862077411e3.PNG)

```bash
gulp dist
```

upload .sppkg file to app catalog.

## Additional info: ##

AppManifest.xml
![appManifest](https://user-images.githubusercontent.com/19236242/59660626-bc8b5e80-91b1-11e9-941a-8bde31f13064.PNG)

### .yo-rc.json ###
![yoRc](https://user-images.githubusercontent.com/19236242/59660333-edb75f00-91b0-11e9-9727-b6f8c50aa116.PNG)

### environment versions: ###

node@10.16.0
yo@2.0.6
gulp@3.9.1

I have tried Sharepoint 2016 and onwards solution too. It has the same issue. However deploying same 2016 solution to a SP16 environment works fine.

Thank in advance. Any help would be appreciated.
Can.

**Comment by VesaJuvonen** [comment]
This seems like environmental issue. Can you share the exact SP2019 version which you are using from central admin server page, so that we can build a repro. Might be that some new CUs accidently contain older schema files, but we would need to understand your detailed SP2019 version for testing and building repro for this issue. Thx for the additional details advance.

**Comment by canbayraktar777** [comment]
Hi Vesa,

Thanks for the reply, 

#### Farm Information:
Configuration database version: 16.0.10337.12109

![farmInfo](https://user-images.githubusercontent.com/19236242/59690396-0a23bd80-91ea-11e9-9d33-2cd556604f52.PNG)

#### Patch Status:
![patchesAndUpdates](https://user-images.githubusercontent.com/19236242/59690517-3c351f80-91ea-11e9-93f3-8969a03e42a3.PNG)

**Comment by canbayraktar777** [comment]
Hi again,
We have updated the farm:

Farm Info1rmation
Configuration database version: 16.0.10346.20001
Configuration database server: SPSQLSERVER
Configuration database name: SharePoint_Config_SP2019_DEV

Generators that we have tried with react and plain javascript options for onprem19
spfx@1.8.1 
spfx@1.8.0
microsoft@1.8.2
microsoft@.1.4.1
microsoft@1.4.0

issue still exists.

**Comment by canbayraktar777** [comment]
Hello,

We re-install the sharepoint farm from scratch with different .iso. Interestingly, we did not encounter the same problem. All service configuration and versions are exactly the same.
