### ISSUE TITLE
SPFx angular web-part intermittently behavior in IE/Edge 

### ISSUE THREAD

**Issue by vbartari** [SharePoint/sp-dev-docs#416]
#### Category
- [ ] Question
- [ ] Bug

#### Expected or Desired Behavior
In IE/Edge : SPFx Wepart (Multiple) should load without  errors in test site as well(Official test tenant).

#### Observed Behavior
SPFx angular web-part is loading in chrome but on IE and Edge browser on first load webparts are loading. But if we hit ctrl+F5 sometime webparts are getting loaded but sometimes not   and getting error like below for all the webparts (and was working fine for dev tenant till 7th feb):

findComponentRoot(..., .0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
react.bundle_f20550c769ff33641f6f9ea9424d6fed.js (1,11510)
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null
Warning: ReactMount: Root element has been removed from its original container. New container: null

**What I  found there is some difference in sp-client-prod files:**
The dev Tenant site file is in :
**files/sp-client-prod_2017-01-31 folder** 
And test tenant files are in :
**files/sp-client-prod_2017-01-16**
I have observed , last week  both the environment was using same files (files/sp-client-prod_2017-01-16)   and after 4th feb'17  **test  env** using files/sp-client-prod_2017-01-16 & **Dev** is using  files/sp-client-prod_2017-01-31  till 7th feb.
and Today SP package in dev tenant is reverted to old i.e. sp-client-prod_2017-01-16 and webparts are broken again.
and I'm getting same errors for both the enviorments again :(

**(You can found this folder in edge/Chrome browser while pressing F12 ,go to  debugger 
check for spoprod-a.akamaihd.net and you will get files/sp-client-prod_2017-01-16" in this folder.)**

#### Steps to Reproduce
Create an angular web-part using yo @microsoft/sharepoint
Select option as" No JavaScript web framework"
After doing require changes you have to deploy web-part in both the site (Test and developer)site and  you will get errors

**Comment by patmill** [comment]
Sorry for the long delay here.  It sounded like the issue was fixed, but then the build with the fix was rolled back.  I'm assuming that the fix has rolled out.  If not, please reopen this.
