### ISSUE TITLE
Summary Link webpart is also deprecated

### ISSUE THREAD

**Issue by taisino** [SharePoint/sp-dev-docs#4161]
Microsoft engineers often suggest to remove summary link webpart for better page performance because this is the kind of DataForm Webpart.
The name of "DataForm Webpart" isn't familiar to customer, so I appreciate if you can add Summary Link Webpart in "Avoid XSLT based webparts" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32870f8f-aae6-75ed-b21b-1379e6be3ac0
* Version Independent ID: 4d7f6c24-94e2-861e-de5f-94e0fa68a164
* Content: [Performance guidance for SharePoint Online portals](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-performance)
* Content Source: [docs/solution-guidance/portal-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/portal-performance.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi @taisino , @andrewconnell 
PR https://github.com/SharePoint/sp-dev-docs/pull/4172 is raised for this fix.
Please review. Thank you.
