### ISSUE TITLE
Extension - Application Customizer footer not rendered correctly on mobile

### ISSUE THREAD

**Issue by joakimhogberg** [SharePoint/sp-dev-docs#4163]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I expected that the footer placeholder in Application Customizer would keep rendering at the bottom of the page using mobile phone.

#### Observed Behavior
The footer is rendered correctly on the bottom of the page on first load, and page refresh. However, if I go to a news page and then back to the home page again, the footer isn't visible. In the DOM I can see that the footer is rendered at the middle of the page, and using `z-index: 0` on element styles in Dev Tools, I can make it visible, and see that it's rendered in the middle of the page:
![image](https://user-images.githubusercontent.com/5407853/59746793-e73fea80-9277-11e9-9b88-9903b08d32b4.png)

#### Steps to Reproduce

1. Follow the steps in this article to create a new Application Customizer extension: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
2. Bundle, package and deploy the extension to your tenant, and install it to a communication site
3. Ensure that you have at least one other client side page on this site (I use a news post)
4. Open the site on a mobile sized screen (I use Dev Tools to emulate an iPhone 6/7/8 to be able to inspect the DOM)
5. Observe that the header and footer are rendered correctly on first page load:
![image](https://user-images.githubusercontent.com/5407853/59747000-50bff900-9278-11e9-9f46-ea1de2d775c8.png)
6. Navigate to another client side page (news post)
7. Navigate back to the start page by clicking the site logo on top of the page
8. Observe that the header is now rendered correctly, but footer is invisible:
![image](https://user-images.githubusercontent.com/5407853/59747166-9ed4fc80-9278-11e9-8494-06a1ed90abef.png)
9. Inspect the DOM using dev tools and find the invisible footer (CTRL+F to search for "Bottom property"):
![image](https://user-images.githubusercontent.com/5407853/59747231-c5933300-9278-11e9-9bc7-3d3d482930e6.png)
10. Set the element style to `z-index:1`, now we can see that the footer is rendered on the middle of the page:
![image](https://user-images.githubusercontent.com/5407853/59747298-e5c2f200-9278-11e9-96f2-f7793a48eb9a.png)
11. Refresh the page and observe that the footer is rendered correctly again

Comments:
This issue seems to be for smaller screens only. I have never seen it on a screen larger than 768px width. This is also the case in the SharePoint iPhone app.

I am not sure if this is an error in the documentation, or the actual implementation in SPFx/SPO server side features. I have tried to changed the code using the `this.context.application.navigatedEvent` insead of `this.context.placeholderProvider.changedEvent` to listen to changes, but no success so far.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions#feedback)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by TheDeadman** [comment]
I hope this issue gets more attention. I have had to resort to a hack to manually force a position:fixed footer at the bottom of the pages when the user navigates in mobile app.

I believe the issue has to do with how SharePoint Framework apps handle their lifecycle / context. When navigating, the SPFx footer customizer area is lost from the DOM but calling the code to initialize the footer area does not work after the navigation. 
this.properties.context.placeholderProvider.changedEvent is not called and this.properties.context.placeholderProvider.tryCreateContent will not create the footer content in the pages context after navigation has occurred.

**Comment by johnguy0** [comment]
@joakimhogberg Are you still seeing this issue?

**Comment by joakimhogberg** [comment]
Hi @johnguy0, thanks for reaching out.

I have not seen this issue in a while actually!

**Comment by johnguy0** [comment]
Thanks! Feel free to open a new issue if you encounter this again.
