### ISSUE TITLE
Typescript errors on @types\lodash\index.d.ts

### ISSUE THREAD

**Issue by rrkushner** [SharePoint/sp-dev-docs#417]
- [x] Bug

#### Expected or Desired Behavior
Run my new Helloworld-webpart

#### Observed Behavior
8 errors on node_modules\@types\lodash\index.d.ts; 4-TS1005 & 4-TS1128
Full error messaages below

#### Steps to Reproduce
spfx/set-up-your-development-environment
spfx/web-parts/get-started/build-a-hello-world-web-part
I got the errors when I ran "gulp serve"
There were no errors when I ran "yo @microsoft/sharepoint"

I am running on a win 10 azure vm.

Error - typescript - node_modules\@types\lodash\index.d.ts(11444,21): error TS1005: ']' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,22): error TS1005: ';' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,23): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,33): error TS1005: ']' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,34): error TS1005: ')' expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,35): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(11444,37): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\lodash\index.d.ts(19441,1): error TS1128: Declaration or statement expected.

**Comment by andrewconnell** [comment]
Dupe #394  ?

**Comment by sparkitect** [comment]
@andrewconnell It's a different set of errors, but the workaround in #394 fixes this one, too.

**Comment by rrkushner** [comment]
I did this workaround from #394 and it worked:
npm install @types/lodash@4.14.50

**Comment by andrewconnell** [comment]
Different error depending on which version of TypeScript you use, but same root cause & workaround.

**Comment by fksontini** [comment]
npm install @types/lodash@4.14.50

**Comment by anishetty** [comment]
@fksontini  running the command fixed the issue.(npm install @types/lodash@4.14.50)

**Comment by ChioukhLyes** [comment]
https://github.com/ionic-team/ionic-app-scripts/issues/700#issuecomment-276684485
