### ISSUE TITLE
REST API: The UTC time represented when the offset is applied must be between year 0 and 10,000. Parameter name: offset

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4174]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

One of our customer is experiencing a weird issue that I cannot reproduce on other tenancies.
The error appears during GET REST API request using SPFx `context.spHttpClient` helper:
```typescript
let url: string;
url = context.pageContext.web.absoluteUrl;
url = GeneralHelper.trimSlash(url);

url += `/_api/lists/getById('${context.pageContext.list.id.toString()}')/rootFolder/Properties`;
await context.spHttpClient.get(url, SPHttpClient.configurations.v1); 
```

and the request itself is:
```
GET https://tenant-name.sharepoint.com/sites/site-name/sub-site-name/_api/lists/getById('list-id')/rootFolder/Properties
```

The result of that request is 400: Bad Request with the next error inside:
```
code: -2146233086, System.ArgumentOutOfRangeDescription,
message: The UTC time represented when the offset is applied must be between year 0 and 10,000. Parameter name: offset
```

Some details:
1. The tenant is **Standard** release. We switched to Targeted release - the behavior is the same
2. Initially root site collection time zone was set to Pacific, sub site time zone was set to UTC+1 (Madrid, Paris). We changed root time zone to be UTC+1 as well, but the behavior remains the same.
3. User is a global admin
4. Browsers: Chrome, Firefox, IE - doesn't matter

Any thoughts what can be the reason for that?
Thanks!

**Comment by GrahamMcMynn** [comment]
Since this cannot be reproduced elsewhere it would help to get the tenant that this is happening on, the approximate time it happens on, and the requestid from the response headers (so we can look at the logs).  Without this information there isn't alot we can do.
