### ISSUE TITLE
Spelling mistake on search rest api overview

### ISSUE THREAD

**Issue by LBoyle** [SharePoint/sp-dev-docs#4177]
Importance: low 

#### Category
- [ ] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Capitalisation to be correct, so that when I copy and paste the query param, SP does not produce an error. 

#### Observed Behavior

I copied a query param from this page, but as it was capitalised incorrectly, SP produced an error when I made the request. 
```
The property 'HithighlightedProperties' does not exist on type 'Microsoft.Office.Server.Search.REST.SearchRequest'. 
Make sure to only use property names that are defined by the type.
```

The mistake is in "Table 1." under "POST requests" on this page: 
[sharepoint-search-rest-api-overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview)

Where "HithighlightedProperties" should read "HitHighlightedProperties" with the second H capitalised. 

Later on this page, the param is capitalised correctly in a usage example. 

Capitalisation is only important for the POST query, it doesn't matter for GET requests.

**Comment by andrewconnell** [comment]
Thanks for calling this out... care to submit a PR to fix the typo? Easy submission...

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
PR https://github.com/SharePoint/sp-dev-docs/pull/4229 is raised for this fix.
Please review and let me know in case of any changes needed. Thanks!
