### ISSUE TITLE
need a page to address inventory of which sites have addin registered

### ISSUE THREAD

**Issue by bakerm00** [SharePoint/sp-dev-docs#4178]
its great this information exists - but doesn't address Security Operations...  how to find out which site have this enabled, as it could be a back door.
Also how do you manage key rotation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be8c8d6-7ed2-1907-3038-49d8e1c92e8a
* Version Independent ID: a2adbe13-e625-3995-fded-fce6c4a701ac
* Content: [Register SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/register-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
At the moment there's no page / API that gives you a list where this is installed. You can use the SharePoint ALM APIs (_if you're in SharePoint Online_) to walk through your sites and query for installed apps.

Key rotation is a practice... simply create a new key before the old key expires & redeploy the solution & upgrade where it is in use. This will use the new key while the old key expires. Just like SSL certs on a website, you need to keep track of your keys and when they expire to ensure there's no gap.
