### ISSUE TITLE
SPFX webpart Not working in sites/_layouts/15/workbench.aspx

### ISSUE THREAD

**Issue by poovarasan1461988** [SharePoint/sp-dev-docs#418]
Getting error :
[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloworldWebPart.82ceb8e4-96b6-4eb6-8151-9eba90cc328a,Error: ***Failed to load component "a8366e45-65f2-4bdf-bafa-4d6c7f0992a9" (HelloworldWebPart). Original error: ***Failed to load component dependency "@microsoft/sp-webpart-base" from component "a8366e45-65f2-4bdf-bafa-4d6c7f0992a9" (HelloworldWebPart). script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.032/sp-loader_en-us_2032158c7e81d8ca6cabd8d5f3651bfa.js:57:19057) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.032/sp-webpart-base_en-us_83e865c7afcaf523daf607745ec20719.js:47:22053) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.032/sp-webpart-base_en-us_83e865c7afcaf523daf607745ec20719.js:47:22502) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-01-30.032/sp-webpart-base_en-us_83e865c7afcaf523daf607745ec20719.js:48:714

The webpart is working on workbench of localhost(localhost:../temp/workbench.html) but not working on workbench of sharepoint(sites/_layouts/15/workbench.aspx).

I have created helloworld webpart in RC0 version.
![lastestjson](https://cloud.githubusercontent.com/assets/25666717/22791669/32a3a1d2-ef10-11e6-9bd3-20e08cd94e42.png)

**Comment by manishgarg1** [comment]
Hi @poovarasan1461988, a fix is rolling out today. Please try the same scenario tomorrow and let us know if it still repros.

**Comment by manishgarg1** [comment]
Hi @poovarasan1461988 , is it working now ?

**Comment by poovarasan1461988** [comment]
Hi @manishgarg1  Thanks for your quick response. It works now. Thanks you very much. :+1:

**Comment by vball525** [comment]
I am getting this exact error today in my developer tenant. Should I open a new bug or will this be reopened?

**Comment by tracy-zaact** [comment]
Me, too.  See full details here:  https://sharepoint.stackexchange.com/questions/233822/error-when-displaying-helloworld-web-part-in-tenant-workbench/233823#233823.  My issue is resolved when I use the workbench within a developer site collection, but that is contrary to the current documentation.
