### ISSUE TITLE
WebPartContext is not a exported member of sp-webpart-base

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#4182]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
gulp build should run successfully when importing WebPartContext in a class.

#### Observed Behavior

TypeScript-Error occurs: Module '"../../../../../Projects/...../node_modules/@microsoft/sp-webpart-base/lib"' has no exported member 'WebPartContext'. Did you mean 'IWebPartContext'?

#### Steps to Reproduce

- Create a new SPFx-React-Project with yeomen.
- Choose 2016 and onwards and online
- Add a new class or interface and import WebPartContext of sp-webpart-base

Using following versions:
@microsoft/generator-sharepoint@1.8.1
@pnp/office365-cli@1.18.0
gulp@3.9.1
npm@5.7.1
yo@2.0.6
Node version: v8.10.0
Build tools version: 2.5.3

![WebPartContextError](https://user-images.githubusercontent.com/22025808/59866757-a7b6f280-938c-11e9-8975-6db9f30d5fd2.png)

**Comment by andrewconnell** [comment]
There were some known issues in v1.8.0 & 1.8.1 related to on-prem projects. Can you upgrade to the latest version of the SPFx Yeoman Generator (1.8.2) & try again?

**Comment by EA12** [comment]
Thank you for your quick Response. I used

> npm install @microsoft/generator-sharepoint --global

to get the latest version of SPFx Yeoman Generator.
After that I checked the version. 

![latestversion](https://user-images.githubusercontent.com/22025808/59874007-8c081800-939d-11e9-891b-d6c6434140bc.png)

I did not upgrade my current Project but created a new one.
I was not even asked about the target Environment (2016 onwards, SharePoint Online only, etc.)

![notevenasking](https://user-images.githubusercontent.com/22025808/59874116-cf628680-939d-11e9-8e31-2ab50d821c2e.png)

And then the import of BaseClientSideWebPart and IPropertyPaneConfiguration which has already been changed in 1.8.0 is wrong:

![webpartbase](https://user-images.githubusercontent.com/22025808/59874287-37b16800-939e-11e9-8dda-fcee29093a3d.png)

I think it should be:

![exspected](https://user-images.githubusercontent.com/22025808/59874401-6a5b6080-939e-11e9-9bdc-727a49bd2abc.png)

**Comment by andrewconnell** [comment]
1. On the SharePoint environment question, that's strange. Try this again, but look in the folder where you are creating the project & folders above it... look if there's a file **.yo-rc** file. That sets default settings for the generator and it might be automatically setting it.
1. The point about the `BaseClientSideWebPart` & `IPropertyPaneConfiguration` refactoring to two packages only applies to SPFx v1.8.0+ which only applies to SharePoint Online. SharePoint Server 2016 and SharePoint Server 2019 will use the original organization where both of those are in the same package **@microsoft/sp-webpart-base**.

**Comment by EA12** [comment]
1. The .yo-rc.json in the root directory of the new project has the setting of "Environment": "onprem"
`{
  "@microsoft/generator-sharepoint": {
    "version": "1.8.2",
    "libraryName": "sptest",
    "libraryId": "8e1cc13f-f044-4395-a186-f911fa6ffac3",
    "environment": "onprem",
    "packageManager": "npm",
    "isCreatingSolution": true,
    "componentType": "webpart"
  }
}`

I restarted the machine, checked all versions again, verified the npm cache. Installed yo again. Everything with no avail.
So, the Question is: Why yo is using onprem as the default setting.

I had a look into <user>\AppData\Roaming\npm\node_modules\@microsoft\generator-sharepoint\lib\generators\component\BaseComponentGenerator.js. I cannot find the prompt for the Environment:

`class BaseComponentGenerator extends BaseGenerator_1.BaseGenerator {
    prompting() {
        return this.checkSolution().then(() => {
            const availableFrameworks = [
                { name: 'No JavaScript framework', value: 'none' }
            ];
            if (this.allowedFrameworks.indexOf('react') !== -1) {
                availableFrameworks.push({ name: 'React', value: 'react' });
            }
            if (this.allowedFrameworks.indexOf('knockout') !== -1) {
                availableFrameworks.push({ name: 'Knockout', value: 'knockout' });
            }
            return this.prompt([
                {
                    type: 'input',
                    name: 'componentName',
                    default: 'HelloWorld',
                    when: () => !this.config.get('componentName'),
                    message: `What is your ${this.friendlyName} name?`,
                    validate: (input) => {
                        const normalizedNames = normalizeComponentNames(input, this.codeName);
                        const outputFolderPath = this._getOutputFolder(normalizedNames.componentNameCamelCase);
                        if (fsx.existsSync(outputFolderPath)) {
                            console.log(colors.yellow(`\nThe folder "${outputFolderPath}" already exists.`
                                + ` Please choose a different name for your component.`));
                            return false;
                        }
                        // disallow quotes, since this will mess with the JSON we put this string into
                        if (input.indexOf('"') !== -1) {
                            console.log(colors.yellow(`\nDo not use double quotes in your title.`));
                            return false;
                        }
                        return true;
                    }
                    // required: true
                },
                {
                    type: 'input',
                    name: 'componentDescription',
                    when: () => !this.config.get('componentDescription'),
                    message: `What is your ${this.friendlyName} description?`,
                    default: (answers) => `${this.config.get('componentName') || answers.componentName} description`
                    // required: true
                },
                {
                    type: 'list',
                    name: 'framework',
                    when: () => (!this.config.get('framework')) && (availableFrameworks.length !== 1),
                    message: 'Which framework would you like to use?',
                    choices: availableFrameworks
                }
            ]).then((answers) => {`

Maybe something went wrong with Building the latest yo generator?

Regarding 2.) Thanks for clarifying.

Any help is appreciated.

**Comment by andrewconnell** [comment]
@EA12 said:
> The .yo-rc.json in the root directory of the new project has the setting of "Environment": "onprem"

In my reply, I said (emphasis added):
> but look in the folder where you are creating the project **& folders above it**... look if there's a file .yo-rc file.

I can't tell what the path is because you've blocked it out, but let's assume its **c:\projects\folder1\folder2\sharepointanalyzer**. You looked in the **sharepointanalyzer** folder. 

What about:
- c:\projects\folder1\folder2
- c:\projects\folder1
- c:\projects

???

**Do any of those have **.yo-rc** files in them?** If so, they would be used by the Yeoman generator run in a downstream folder.

I don't suspect there's anything wrong with the generator... I suspect it's something in your environment. SPFx v1.8.2 has been out for over a month and this is the first report we've seen of this in this issue list. I would have expected to see this prior if it was a generator issue.

**Comment by EA12** [comment]
My first thought was, why should I look folders above? - Why should the generator use a file from current location if I create a new Project beneath? -  But you are right, there was such file one folder above (this must be a left over from some older times?). After removing this .yo-rc.json file, the generator was working as espected.
With option "SharePoint 2016 onwards, including 2019 and SharePoint Online", the imports are now as this:

`import {
  BaseClientSideWebPart,
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-webpart-base';`

Even if the way of Scaffolding a new SPFx-WebPart ( .yo-rc.json file somewhere else) is kind of confusing and not comprehensible, my issue is solved. Thank you very much for your patience, your time and the hint to solve it.

**Comment by andrewconnell** [comment]
@EA12 said:
> My first thought was, why should I look folders above?

Because that's how Yeoman works. When you run the generator it checks the current folder & all folders above it for that file. That file contains settings a generator may have set previously.

In the case of the SharePoint generator, it uses this technique to determine if you are running the generator within an existing SharePoint solution that was created with the generator. If so, it can ignore certain questions & skip straight to "what do you want to create, a web part / extension".
