### ISSUE TITLE
SPFx ApplicationCustomizer not executed on Modern NewForm.aspx

### ISSUE THREAD

**Issue by brettlonsdale** [SharePoint/sp-dev-docs#4184]
Re-creating this ticket as per conversation with Vesa Juvonen. It was raised in issue #2523
 but not yet resolved. 

**Category**
  
 Bug
 
**Expected or Desired Behavior**
An Alert from ApplicationCustomizer sample has to be shown or custom debugger fired when dev tools are opened on default modern NewForm.aspx.
**Observed Behavior**
No alert and debugger on default modern NewForm.aspx, even no ApplicationCustomizer scripts loaded when opened network tab in chrome browser dev tools as well in debug mode no prompt to enable debug scripts, however on default modern EditForm.aspx, DispForm.aspx alert is shown and debugger fired, from dev tools scripts are loaded as well as on home page and custom site pages everything works.
**Steps to Reproduce**
Deploy ApplicationCustomizer sample with following onInit method:
  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);
    debugger;
    let message: string = this.properties.testMessage;
    if (!message) {
      message = '(No properties were provided.)';
    }

    Dialog.alert(`Hello from ${strings.Title}:\n\n${message}`);

    return Promise.resolve();
  }
And try to install it through app catalog or run using gulp serve on SharePoint online web site then visit on custom list default modern NewForm.aspx
**Submission Guidelines**
Looks like something special happens only on NewForm.aspx, I have tried as well on different site templates and got the same behavior, Please let me know how can I inject script to default modern NewForm.aspx on custom list or if it is a bug then approximately when it will be fixed and rolled out ?

**Comment by ahackettms** [comment]
@brettlonsdale This issue is fixed. Please check after mid-November to verify. Thanks

**Comment by ferinder** [comment]
Hi, @ahackettms any update on this issue? Any workaround for it?
Will fix be included in next SPFx relesase?

**Comment by kemesfun** [comment]
@brettlonsdale Can you verify if this issue still occurs?
