### ISSUE TITLE
Explicitly specify "Executing Unit Tests" needs React version 16

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#4190]
The version of React in SPFx solution should be 16. Otherwise, "npm test" throws below error:
TypeError: Cannot read property 'hasOwnProperty' of undefined

Under section "Executing Unit Tests", please include below:

1. Disclaimer about using React version 16. 
2. Instructions on how to upgrade to SPFx version that supports React version 16.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Hey @baywet, didn't you write this? Can you comment on this issue?

**Comment by baywet** [comment]
@andrewconnell yes I wrote this documentation and updated it a couple of times. Thanks for triaging.
@nanddeepn it is supposed to work as is on new projects, could you put your project, or a least a reproduction, on a repository/archive somewhere please?

**Comment by nanddeepn** [comment]
Hi @baywet ,
Yes, the instructions works perfect for new projects (SPFx version 1.8.2).

However, for SPFx solutions created with prior version (e.g. 1.6.0), which was supporting React (version 15.6.6), the "npm test" throws below error:
TypeError: Cannot read property 'hasOwnProperty' of undefined.

The idea is, in the documentation we should explicitly mention about React version of 16.
Please let me know, if it sounds a good idea. Thanks!

**Comment by baywet** [comment]
Out if curiosity, did you install the version 15 of the preset instead of version 16 https://www.npmjs.com/package/@voitanos/jest-preset-spfx-react15 ?

**Comment by nanddeepn** [comment]
Yes, It does work for SPFx v1.6.0 project.
Should we then add instructions to use this npm package for SPFx solutions with React version 15?

**Comment by baywet** [comment]
@nanddeepn thanks for the information. I just authored a pull request to fix the content.

**Comment by nanddeepn** [comment]
Thanks @baywet 
Appreciate your quick response on this!
