### ISSUE TITLE
@pnp typescript not compatible with SharePoint 2016 onwards, including 2019 and SharePoint Online

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#4195]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

gulp build leads to many errors regarding pnp:
Error - typescript - node_modules\@pnp\common\src\util.d.ts(66,56): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(88,24): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\sp\src\clientsidepages.d.ts(102,49): error TS1005: ',' expected.

#### Steps to Reproduce

Use latest Yeomen generator 1.8.2
Add a new WebPart Project with `yo @microsoft/sharepoint`
Use "SharePoint 2016 onwards, including 2019 and SharePoint Online" as package.
Use "React" as Framework.
Install @pnp with `npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save`
Add a import to the webpart file like so `import { sp, SPRest } from '@pnp/sp';`
Run gulp build

#### Version used
@microsoft/generator-sharepoint@1.8.2
Build tools version: 2.5.3
Node version: v8.10.0
+ @pnp/odata@1.3.3
+ @pnp/sp@1.3.3
+ @pnp/logging@1.3.3
+ @pnp/common@1.3.3

`npm list typescript`

`-- @microsoft/sp-build-web@1.1.0
  `-- @microsoft/gulp-core-build-typescript@3.1.1
    +-- @microsoft/api-extractor@2.3.8
    | `-- typescript@2.4.2
    `-- typescript@2.2.2

**Comment by andrewconnell** [comment]
This issue is related to the PnPJS library... please post this issue to the repo for that project:
https://github.com/pnp/pnpjs

We'd usually transfer the issue automatically, but we can't because it's in a different github org, so you'll have to recreate it in the repo linked above.
