### ISSUE TITLE
SharePoint Documentation - Down

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#4196]
Cannot see any documentation for SharePoint at the moment:

![docs](https://user-images.githubusercontent.com/8781041/60087074-31bbde00-9734-11e9-9544-88a9138d3d73.png)

The site is partially down.

**Comment by andrewconnell** [comment]
The **en-gb** locale isn't one that is supported. Leave the locale off and it redirects to the correct location.

It's not really a SharePoint issue, rather one with the entire docs.microsoft.com platform (including Azure: https://docs.microsoft.com/en-gb/azure)... nothing we can do here, but I've raised it to their attention to investigate. Closing as it's not a SharePoint issue...

**Comment by pkbullock** [comment]
The site redirects to that locale, but ok thanks for looking into this and forwarding to the team.
