### ISSUE TITLE
SharePoint Commandset extension not showing up within a specific site

### ISSUE THREAD

**Issue by mschaaks** [SharePoint/sp-dev-docs#4198]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The commandset extension works fine in site A within the same tenant and is expected to work in site B. The extension is deployed via the tenant app catalog and installed on a site basis. Also, the O365 CDN is used. 

#### Observed Behavior

The commandset extension does not load in site B, with the following trace log:

2019/06/24   21:11:40.963,verbose,ManifestStore,"***Manifest not found for component   id ""e3de3aac-3b44-4431-be9d-a74f6bee2ccb""." |   |   |  
-- | -- | -- | --
2019/06/24   21:11:40.964,verbose,ManifestStore,"***Manifest not found for component   id ""e3de3aac-3b44-4431-be9d-a74f6bee2ccb""." |   |   |  
2019/06/24   21:11:40.991,error,ListViewAdapter,"***Manifest not found for   componentId ""e3de3aac-3b44-4431-be9d-a74f6bee2ccb""." |   |   |  
2019/06/24 21:11:40.992,info,ListViewAdapter,"EventName:Error:   ***Manifest not found for componentId   ""e3de3aac-3b44-4431-be9d-a74f6bee2ccb""., ResultCode:   undefined"
 

#### Steps to Reproduce

Add commandset extension form app catalog to site. A site level usercustomaction object was also not created within site B. Manually creating this object using PnP powershell also did not solve the issue.

**Comment by lucabandMSFT** [comment]
sorry, this is quite confusing and I really don't understand where the problem is. Can you please help and provide exact step by step to repro the issue?
