### ISSUE TITLE
Generator doesn't check if the webpart name is valid

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-dev-docs#420]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Running `yo @microsoft/sharepoint` and setting a webpart name, the webpart name should be validated before the project will be created.

#### Observed Behavior
Running `yo @microsoft/sharepoint` and setting a webpart name like "20170210Spfxrc0" will result in invalid class names.
`gulp serve` will fail with the following typescript errors.

> Error - typescript - src\webparts\20170210Spfxrc0\20170210Spfxrc0WebPart.ts(13,2
> 2): error TS1005: '{' expected.
> Error - typescript - src\webparts\20170210Spfxrc0\20170210Spfxrc0WebPart.ts(13,3
> 0): error TS1005: ';' expected.
> Error - typescript - src\webparts\20170210Spfxrc0\20170210Spfxrc0WebPart.ts(13,4
> 5): error TS1005: ';' expected.
> Error - typescript - src\webparts\20170210Spfxrc0\20170210Spfxrc0WebPart.ts(37,3
> ): error TS1005: ',' expected.
> Error - typescript - src\webparts\20170210Spfxrc0\20170210Spfxrc0WebPart.ts(41,3
> ): error TS1005: ',' expected.
> 

#### Steps to Reproduce
WIN 7
node v4.6.0
npm 3.10.10

**Comment by nickpape-msft** [comment]
This is a legitimate issue. Thanks for the feedback! We will investigate this problem and update this issue.

**Comment by andrewconnell** [comment]
Confirmed this is still an issue in SPFx v1.7.0

**Comment by andrewconnell** [comment]
Appears fixed... not throwing any errors in SPFx v1.9.1
