### ISSUE TITLE
template provided as code

### ISSUE THREAD

**Issue by sunishabraham** [SharePoint/sp-dev-docs#4200]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
my company does not allow templates from non-Microsoft sites (only from https://support.office.com/en-us/article/using-templates-to-create-different-kinds-of-sharepoint-sites-449eccec-ff99-4cf3-b62e-dcfee37e8da4) but the "Giving Campaign" template is almost exactly what we need...and so is there anyway to provide that template as "code" so we can execute against a SharePoint modern teamsite?

**Comment by VesaJuvonen** [comment]
If this is related on the Give template available from https://provisioning.sharepointpnp.com/home/details?packageId=755a5a3b-91d5-452e-8d89-2ed2ca8e7137, you can install this in two different ways. Either by using the provisioning service web site or by using PnP PowerShell. In both cases you would need to be a tenant administrator to be able to deploy the template to your tenant.

Technically template is an instructions for code - as it's translated to CSOM execution commands and then executed to the given tenant. If you are looking into doing this outside of the web site, you can download the pnp file from https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/GiveAtContoso and then use Apply-PnPTenantTemplate cmdlet (https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnptenanttemplate?view=sharepoint-ps).
