### ISSUE TITLE
ListViewCommandSet code is not working

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#4201]
- [x] Bug

Environment: Office 365

I have written SPFx solution with list view command set few months back. Now i wanted to do some changes to that solution. so i have added few lines of code and then deployed, nothing is working. It is not triggering onInit method, 

Below is my onListViewUpdated method.
```
@override	  
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, 'Initialized HideDeleteButtonsCommandSet');       
   debugger;
    this.checkAndValidate();
    return Promise.resolve();
  }
@override
public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
debugger;
    this.checkAndValidate();
}
```
After deployment, debugger points are not hitting at all. in development mode with gulp serve it is not working. it was described already in [another issue](https://github.com/SharePoint/sp-dev-docs/issues/3914)
In console I am getting below errors:
![image](https://user-images.githubusercontent.com/7568187/60119742-c65a2680-979c-11e9-8662-ce7093f36676.png)

What could be the possible resolution for this?

**Comment by andrewconnell** [comment]
As you stated, this is the same issue as described in another issue, I'm flagging this as a dupe and closing it. It doesn't mean it's being dismissed, but that other issue is currently tracked by MSFT and they are investigating it... so better to keep issues consolidated.

If you have additional information to provide, that would be the best place to post it.

**Comment by ymihir** [comment]
@andrewconnell  The only reason I have opened this to indicate that this issue also happening in production version also. Thanks for the update.

**Comment by andrewconnell** [comment]
Understood... but all extensions are "in production" as they only run in live SharePoint environments. But like I said, if you've got additional details, feel free to add them to the existing issue. 

It's common practice to try to keep issues consolidated for tracking purposes... not trying to dismiss your issue, just trying to keep things organized :)
