### ISSUE TITLE
Add Teams tab with properties

### ISSUE THREAD

**Issue by phettz** [SharePoint/sp-dev-docs#4203]
Hey

Is it possible to add the webpart to a tab with properties using the graph api? 

Looks like the Teams client is first sending a post to _api/web/hostedapps/add on the SharepointPoint site behind the Team when you add it. 

Example: 

webPartDataAsJson: {
            "dataVersion":"1.0",
            "description":"MyFirstTeamsTab description",
            "id":"c9573db2-e061-47c7-86e2-de2008e352b6",
            "properties":{"description":"MyFirstTeamsTab description"},
            "instanceId":"02d4cabf-6642-43ce-8999-4f41d796ae02",                       
            "title":"MyFirstTeamsTab"
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unsure... I think it's more of a question for the Graph / Teams API teams as it wouldn't be handled from their site. A custom tab in Teams is just a manifest definition & the URL is specially crafted to point to a special SharePoint page with specific URL parameters.
