### ISSUE TITLE
SPFX Change the position of a ListView Command Set button in the command bar

### ISSUE THREAD

**Issue by boby5555** [SharePoint/sp-dev-docs#4204]
## Category
- [x ] Question

#### Expected or Desired Behavior

I created a custom SPFX ListView Command Set button in the command bar which works fine. My only concern is that I don't control his order of appearance in the command bar. My goal is to be able to place it further left or further right as I desire. Also, is there anyway to move or hide the microsoft build-in button(Open, Share, Flow, and so on...)?

See image below
https://i.stack.imgur.com/ECEKm.jpg

**Comment by patmill** [comment]
At this point in time the list app doesn't allow for reordering / hiding / specifying an order to the commands.    I would go to user voice and upvote the following entries:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33476878-add-support-to-hide-list-view-command-set-buttons
and
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37914715-use-sequence-parameter-to-sort-listview-command-se

(There might be others with more votes, but that's what I found with a quick search.)
