### ISSUE TITLE
Specify the location of manifest file in SPFx solution

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#4205]
The section "Create a Microsoft Teams app manifest" mentions to create a manifest file. However, we should also mention the file name and location, where it should be saved in SPFx solution.
I think the file should saved as "teams\manifest.json"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
No, we no longer create an explicit teams manifest.  When you use the "sync to teams" functionality in the app catalog, we create one on the fly.  If you need to create one yourself (say you have a solution that has tabs, bots, etc. ) then you would create your own manifest / zip / etc.

**Comment by patmill** [comment]
(Apparently we need to update that document and remove the big "not ready" warning a the top)

**Comment by nanddeepn** [comment]
Hi @patmill 
Thanks for your reply.
In this case, is the section "Create a Microsoft Teams app manifest" (or may be entire page) obsolete?

**Comment by VesaJuvonen** [comment]
@nanddeepn  - There might be still absolutely cases where you want to create the manifest manually as if you want to adjust settings of the manifest. This is why the doc is absolutely still valid and will be only adjusted around the messaging, but should not considered as obsolete.

**Comment by nanddeepn** [comment]
Thank you @VesaJuvonen
