### ISSUE TITLE
Limit of unique scurity scopes

### ISSUE THREAD

**Issue by b6202lam** [SharePoint/sp-dev-docs#4206]
The SPO Limits article (https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits) states that the limit of Unique security scopes per list or library is 5,000.  However, this migration article mentions that the 5,000 recommended limit and 50,000 hard limit is *per site*. Can you help reconcile the apparent conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842a924e-01b2-5aed-5b1a-c190431fe3fb
* Version Independent ID: d6e9e76b-bcf4-e2d6-f268-5ca411b8e4f6
* Content: [SPO Migration API: Migrating shared files and folders](https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-shared)
* Content Source: [docs/apis/migration-api-shared.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/migration-api-shared.md)
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by timdw** [comment]
@bernardlam I wrote a script to test the hard limit and ran it in two different tenants. The limit is (currently at least) 50,000. The script created list items and broke inheritance on them until it came up with the ServerException "You cannot break inheritance for this item because there are too many items with unique permissions in this list.".

**Comment by bernardlam** [comment]
@timdw  based on your test is the 50,000 hard limit per list or per site?

**Comment by bernardlam** [comment]
@timdw have you tried creating 2 (or more) lists in a site and adding 50,000 unique permission scopes to each list?

**Comment by timdw** [comment]
@bernardlam another list in the same site has more than 5,000 unique permissions which means the 50,000 limit cannot be per site.

**Comment by bernardlam** [comment]
I see. good to know! in this case should this article be corrected, since it mentions that the limits are per site, instead of per list?

**Comment by timdw** [comment]
Yes, and the SPO limits article updated too. Unless Microsoft are planning to enforce the 5,000 limit of course ...
