### ISSUE TITLE
Unable to Install Web Part to Sub Site

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#421]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
The web part is installed on the root site collection but not on subsites. I expect to be able to install the web part to a sub site of the root collection.  

#### Observed Behavior
Attempting to add the app to a subsite I get the full page error:
```
Sorry, something went wrong
A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version.
```
The web part has not been previously installed to the subsite and is not in either the first or second stage recycle bins of the subsite or root site.

#### Steps to Reproduce
Install (add app) to a root site then try to install it to a subsite of the root site.

**Comment by NickSevens** [comment]
Possible relation to https://github.com/SharePoint/sp-dev-docs/issues/304

**Comment by mcmynn83** [comment]
This is most likely not related to #304.  Your package should no longer contain a .webpart file.  That being said, I just adding an app in both a root web and a subweb and was able to do so without issue.  Could you more details about the site having the problem?

**Comment by jaredbuttars** [comment]
@mcmynn83 

Site:
https://office365lds.sharepoint.com/sites/framework
Subsite:
https://office365lds.sharepoint.com/sites/framework/jared

Sorry, something went wrong
A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version.

Correlation ID: cac5d49d-408b-3000-e18d-fbbfcf96f804
Date and Time: 2/13/2017 5:14:58 PM

**Comment by jaredbuttars** [comment]
Package works on root site, built with RC0.

**Comment by jaredbuttars** [comment]
This either started working or I was doing something wrong. More likely the latter. Either way, seems fine now.
