### ISSUE TITLE
Modern Site Page banner not visible or editable

### ISSUE THREAD

**Issue by in8aakbh** [SharePoint/sp-dev-docs#4210]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The page banner should be visible with the Title, Text above title when it is successfully updated at the time of provisioning using pnpjs code. 

#### Observed Behavior
The properties for PageTitle banner part is successfully updated and visible in the page maintenance mode but it does not show when the page is in read mode and is not editable when the page is in edit mode.

Edit option for banner not visible:
![image](https://user-images.githubusercontent.com/49864599/60245660-ab8dcc00-98da-11e9-8c1e-962ebec91825.png)

PageTitle par visible in page maintenance mode:
![image](https://user-images.githubusercontent.com/49864599/60245789-ec85e080-98da-11e9-9d04-8d3d2b9c8832.png)

Page title and topic header updated (checked using the _api/sitepages/pages(id) api):
![image](https://user-images.githubusercontent.com/49864599/60246036-79309e80-98db-11e9-980e-3d49ff573c31.png)

This behavior is expected for some pages only. For other pages it works fine.

#### Steps to Reproduce
Update page's LayoutWebPartsContent, TopicHeader properties as per the below values:

``{
  "id": "cbe7b0a9-3504-44dd-a3a3-0e5cacd07788",
  "instanceId": "cbe7b0a9-3504-44dd-a3a3-0e5cacd07788",
  "title": "Title area",
  "description": "Title Region Description",
  "serverProcessedContent": {
    "htmlStrings": {},
    "searchablePlainTexts": {},
    "imageSources": {
      "imageSource": ""
    },
    "links": {},
    "customMetadata": {
      "imageSource": {
        "siteId": "null",
        "webId": "null",
        "listId": "null",
        "uniqueId": "null"
      }
    }
  },
  "dataVersion": "1.4",
  "properties": {
    "title": "France Chapter 1",
    "imageSourceType": 2,
    "layoutType": "FullWidthImage",
    "textAlignment": "Left",
    "showTopicHeader": true,
    "showPublishDate": false,
    "topicHeader": "France - Employee Hand Book",
    "authorByline": null,
    "authors": [],
    "altText": "",
    "translateX": 99.24069855732725,
    "translateY": 45.614035087719294,
    "webId": "null",
    "siteId": "null",
    "listId": "null",
    "uniqueId": "null"
  }
}``

**Comment by andrewconnell** [comment]
Unclear... is this an issue with a page created using the PNPJS library? If so, the issue should be posted to the repo's issue for that project.

**Comment by VesaJuvonen** [comment]
If this issue is only present for pages which have been created using PnPjs, issue should be reported to https://github.com/pnp/pnpjs repository. We cannot unfortunately redirect this issue from here to right repository or team.
