### ISSUE TITLE
what is the main use of microsoft/sp-lodash-subset??

### ISSUE THREAD

**Issue by narulasrinivas** [SharePoint/sp-dev-docs#4211]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

What is the use of **microsoft/sp-lodash-subset** package along with SPFx version? Apart from **escape**, I don't find powerful functions such as **filter** and **startswith** from the default package.

In my case, I installed **lodash** packages and completed my task.

I tried to get answer from docs and blogs but didn't find relevant answer. Please help me to understand **microsoft/sp-lodash-subset** package.

**Comment by abdollahkahne** [comment]
As you have said, `escape `is a very helpfull function for preventing scripts to be injected as user input.

**Comment by narulasrinivas** [comment]
@abdollahkahne -  I agree with you. How about other functions such as **filter** and **startswith** of  default package?.

**Comment by abdollahkahne** [comment]
@narulasrinivas sry I didn't understand your question right. `@microsoft/sp-lodash-subset` is a subset of main loadash module and it doesn't include all the method. Sry again. Have a good time.  I quote the following parageraph from [microsoft](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/optimize-builds-for-production):

> Some of the Lodash methods are provided with the SharePoint Framework in the **@microsoft/sp-lodash-subset** library. Before using Lodash, verify if the method that you want to use isn't already available in the **@microsoft/sp-lodash-subset** library, which is already available as a part of the SharePoint Framework and does not need to be included in your bundle.

**Comment by patmill** [comment]
Right.  We use a subset of lodash for our code, and rather than have people include copies themselves, they can use the ones provided by us.  Not necessary, but it can keep your package smaller.
