### ISSUE TITLE
OOTB RSS feed escaping double quotes character unnecessarily

### ISSUE THREAD

**Issue by jojocode77** [SharePoint/sp-dev-docs#4212]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Using the OOTB RSS Feed webpart on a modern site, double-quotes should not be escaped in the Title property

Sample body:
```
<item>
      <title>Redacted has received "Redacted" nomination from redacted</title>
      <link>https://redacted</link>
      <description>redacted</description>
      <pubDate>Thu, 27 Jun 2019 11:02:13 +0100</pubDate>
      <author>redacted@redacted.com (Redacted)</author>
      <guid>https://Redacted</guid>
</item>
```

#### Observed Behavior

The title display as: 
Redacted has received \"Redacted\" nomination from redacted
with backslashes escaping the quotes. The backslashes are not present in the feed.
![SPORSSEscapeQuotes](https://user-images.githubusercontent.com/23478322/60275976-a0469a80-98f2-11e9-8349-8005f9cabc7d.png)

#### Steps to Reproduce

Unsure...perhaps find an RSS feed with double quotes in an item title and add as a connection to the OOTB RSS feed webpart.

**Comment by andrewconnell** [comment]
Unfortunately, this isn't the right place for this issue. Please submit a ticket via the tenant admin UI. This issue list is a channel only for development issues.

**Comment by jojocode77** [comment]
Apologies @andrewconnell I was given this link in one of the dev calls last week.

**Comment by VesaJuvonen** [comment]
@jojocode77 - This is indeed right location around the dev issues, but we cannot route any bugs related on the oob capabilities from this issue list. All dev issues are 100% welcome from here. All non-dev issues should be reported using the tenant admin support channel.
