### ISSUE TITLE
"Error: Token renewal operation failed due to timeout"

### ISSUE THREAD

**Issue by alisalih1** [SharePoint/sp-dev-docs#4214]
Built a super simple spfx webpart that uses MSGraphClient, calling /group end-point. I am getting a failure as seen below. Permissions are requested in the package and granted in the SPO Admin Center. Tried both beta/v1.0 end-points as well. Tried with both full end-point URL and .api("Groups") as well. 

The issue shows resemblance to already reported issue #1801 however the workaround does not work in my case. 

> Error: Token renewal operation failed due to timeout
>     at Array.<anonymous> (sp-pages-assembly_en-us_6b7c467dac13b54cb9ff078c773aa7b5.js:1184)
>     at Object._callBackMappedToRenewStates.<computed>._callBackMappedToRenewStates.<computed> (1.sp-http-adal_c2097657830cc37ce4b2.js:3)
>     at 1.sp-http-adal_c2097657830cc37ce4b2.js:3

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Graph call to complete properly to give details of an existing Office 365 Group. React-based webpart, bundled, packaged, deployed. API permissions granted in the SPO Admin Center. App added to a site. Client-side webpart added to a modern page. Call is observed with Chrome Dev tools. 

#### Observed Behavior
Call fails with the error observed in the Chrome Dev tools. 

#### Steps to Reproduce
Simple Graph call as below. Both Beta and v1.0 shows the same behavior. 

```
private _readGroupNames(): void {
    console.log ("Retrieving Group names from Graph");
    const requestUrl = "https://graph.microsoft.com/beta/groups?$filter=displayName eq 'Marketing'";
    this.props.context.msGraphClientFactory
      .getClient()
      .then((client: MSGraphClient): void => {
        client
        .api(requestUrl)
        .get((err, res) => {
          if (err) {
            console.error(err);
            return;
          }
          console.log('Response', res);
        });
      });
  }
```

**Comment by patmill** [comment]
Hi @alisalih1 if you look at the network trace when running this code, can you see what calls are timing out / failing / etc?

**Comment by lucabandMSFT** [comment]
so.. I just tried this in a production environment and it succeeded. Version what I'm testing with is 1.8.2...
I used the PnP Email project (updated to 1.8.2) to test it in my tenant. 
I think that if you can reply to questions @patmill  posted above it would be very useful for the investigation

**Comment by alisalih1** [comment]
@patmill / @lucabandMSFT  - I can not immediately see a call failure here. Does this screenshot help? If not, I can get a fiddler trace and console logs and send in an email. Please let me know, I emailed Luca already, which I can send the package as well. 

![image](https://user-images.githubusercontent.com/21177498/60361269-cd0ab880-99ab-11e9-83ab-dc727d40813a.png)

**Comment by lahuey** [comment]
@alisalih1 

Could you look in your network tab for a request that looks like this ->
https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id={}&resource=**"resource you're requesting"**&redirect_uri={}&state={}&client-request-id={}&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none

Navigating to this url should indicate what the actual failure is.

**Comment by alisalih1** [comment]
Himm. May be it is something on our part... Let me see why the app is disabled or if it is. 

![image](https://user-images.githubusercontent.com/21177498/60361852-5a024180-99ad-11e9-910e-bb517f3ab836.png)

**Comment by alisalih1** [comment]
Himm.. I will have to look into this a bit more on our side may be..

![image](https://user-images.githubusercontent.com/21177498/60362042-e280e200-99ad-11e9-90af-2437739d4ca8.png)

**Comment by lucabandMSFT** [comment]
hey @alisalih1, you said in the message that "I do not see it disabled"... but in the picture you attached it says "is disabled". Can you please clarify?

**Comment by alisalih1** [comment]
That's the part I am confused about Luca - In the manifest I see the following. Wouldn't that indicate that it is 'enabled' ?

![image](https://user-images.githubusercontent.com/21177498/60363146-b450d180-99b0-11e9-9ca3-b7f71b06b097.png)

**Comment by alisalih1** [comment]
![image](https://user-images.githubusercontent.com/21177498/60363278-14e00e80-99b1-11e9-9a03-dfa0f4ce32c5.png)

**Comment by alisalih1** [comment]
@lucabandMSFT Sorry for the disturbance. It was in-fact disabled. We are investigating how and why this may have been turned off. Didn't turn on yet but I assume, everything will be OK.

**Comment by lucabandMSFT** [comment]
@alisalih1 , glad to hear that. Thanks for the update

**Comment by Noeky** [comment]
I'm also having this problem. I'm having two spfx webpart on one page that are making graph calls. One webpart is working correctly the other is giving this issue. Anyone some suggestions on how to fix
