### ISSUE TITLE
Trailing space in document library causes upload error

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4215]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The path is automatically trimmed when the file is uploaded, or the document library does not try to correct the error and instead throws a useful error.

#### Observed Behavior

Navigating to a document library path with a trailing space correctly ignores the space and loads the folder. Dragging and dropping into the folder to upload it does not trim the path space, and treats it as an invalid filename.

![image](https://user-images.githubusercontent.com/5057870/60341061-2f13ef80-99a5-11e9-8161-3f34c2459967.png)

`/Shared Documents/Forms/AllItems.aspx?viewid=3531193d-cf1d-467f-93ab-553780c15c9f&id=%2Fdev%2Fjsdev%2FShared Documents%2FFolder%20`

#### Steps to Reproduce

- Create a folder in a document library
    - If the folder name ends in a space, the server will automatically trim this.
- Navigate to the folder in the modern view
- Add a `%20` onto the end of the URL

I understand this is quite an odd scenario. I have an app which programatically navigates to the document library and noticed this strange behaviour before trimming user input for the path.

**Comment by andrewconnell** [comment]
Doesn't look like a dev issue... if anything a UX thing right? If so, I don't think the issue belongs here...

But, I don't follow what you're saying... why just randomly add a `%20` to the URL? What does that reproduce?

**Comment by JakeStanger** [comment]
Files are failing to upload due to the way SP internally trims URLs (or doesn't in some places, or does and then treats the entire path as the filename and rejects the slashes). I'd say that's a dev issue rather than a UX issue.

I get it's quite a weird one. I have a web part which generates/navigates to document library folders based on list entries created from user input. I wasn't trimming my user input, which is how I came across this. 

Obviously the easy fix was to trim user input to avoid the trailing `%20` but this is definitely a bug and I figured it should be brought to your attention.

**Comment by andrewconnell** [comment]
OK... but it's not really a dev issue so IMHO doesn't belong in this list... seems like it should be submitted as a SPO/Office365 support ticket. No?

**Comment by JakeStanger** [comment]
If that is the more appropriate place for SharePoint bug reports then yes. If that's the case, I'll close this ticket and open a support ticket.

**Comment by andrewconnell** [comment]
Personally, I think so... this is for developer related things. Your issue seems like UX... I'd close & post as a support ticket.
