### ISSUE TITLE
Taxonomy update scheduler timer job workaround for SP Online

### ISSUE THREAD

**Issue by vtikam** [SharePoint/sp-dev-docs#4216]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have 2 taxonomy terms 'Category A' and 'Category B'. I tag list items using my taxonomy terms randomly. After that I merge term Category B with Category A. I wait for a day to check if the terms in my list are updated with merged taxonomy term. In SP 2013, this used to happen automatically as there existed an timer job "taxonomy update scheduler timer job".

#### Observed Behavior
I wait for a day to check if the terms in my list are updated with merged taxonomy term.They had to be edited in bulk edit view. In bulk edit, the terms will change automatically.

 Does SP Online provide any sync job similar to this. If not, is there any work around.

**Comment by jashwanthreddyn** [comment]
@andrewconnell any update on this please ?

**Comment by andrewconnell** [comment]
@jashwanthreddyn I don't have an answer, hence why I didn't leave one earlier. I just classified it as a question. Sorry...

**Comment by jashwanthreddyn** [comment]
@andrewconnell : Sorry, any update please ? Looking specifically for details of a timer job (if exists) that runs TaxonomySession.SyncHiddenList(site)
