### ISSUE TITLE
Reporters section for test does not work

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#4217]
Under the paragraph, "Finally you need to modify the package.json to configure the reporter", the configuration ""jest-junit" does not work.

**Suggestion# 1:**
The below code part 
```json
"jest-junit": {
    "output": "temp/test/junit/junit.xml",
    "usePathForSuiteName": "true"
}
```
should be changed to
```json
"jest": {
  "reporters": [
    [
      "jest-junit", {
        "suiteName": "SharePoint SPFx Testing",
        "outputDirectory": "./reports/",
        "outputName": "./junit.xml"
      }
    ]
  ]
}
```

**Suggestion# 2:**
Importing test results should be changed as per "Publish Test Results" section [here](https://www.eliostruyf.com/setting-up-puppeteer-to-run-on-azure-devops-for-your-automated-ui-tests/) - an article by @estruyf 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by baywet** [comment]
Thanks for the information @nanddeepn  I'll double check that.
@andrewconnell can you assign this one to me please? I'll double check when I get a minute. Thanks!
