### ISSUE TITLE
generator-sharepoint creates incorrect .vscode/launch.json

### ISSUE THREAD

**Issue by timdw** [SharePoint/sp-dev-docs#4218]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In .vscode/launch.json the url for local workbench should be `https://localhost:5432/workbench` as per #2507

#### Observed Behavior
In a project created with `yo @microsoft/sharepoint` the url is currently set to `https://localhost:4321/temp/workbench.html` in .vscode/launch.json

#### Steps to Reproduce

run `yo @microsoft/sharepoint`

**Comment by patmill** [comment]
Are you encountering any particular problem?

**Comment by timdw** [comment]
@patmill Not one that will reoccur, well not for me anyway! I was configuring WebStorm and given that launch.json was generated by Yeoman I expected it to be correct. I then had to spend time trying to work out why it was not which is another story best told in #2507.

**Comment by Js-Brecht** [comment]
I agree, should be able to trust that the Yeoman generated files are correct.  It's time wasted having to track down the source of the problem, and more to remember to fix when scaffolding new projects.

**Comment by andrewconnell** [comment]
Don't believe this is still an issue as v1.9.1 debug launch config for debugging is working.
