### ISSUE TITLE
Command Set extension has stooped working on Gulp serve and on package deployment

### ISSUE THREAD

**Issue by gagan2singh** [SharePoint/sp-dev-docs#4219]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

A CommandSet extension which was working fine a couple of days ago stopped working yesterday.
The console logs:
Uncaught Error: There is no operation handler registered for '{"operation_4":["getItems_16","spColumnAdapter_222"]}'.
at e.n (spofiles-mini-be65a0bf.js:1)
at new e (splistitemsscope-is-mini-8ce35f12.js:1)
at splistitemsscope-is-mini-8ce35f12.js:1
at splistitemsscope-is-mini-8ce35f12.js:1
at splistitemsscope-is-mini-8ce35f12.js:1
at splistitemsscope-is-mini-8ce35f12.js:1
at dispatch (splistitemsscope-is-mini-8ce35f12.js:1)
at Object. (splistitemsscope-is-mini-8ce35f12.js:1)
at listviewdataprefetch-mini-f46dba5c.js:15
at Object.next (listviewdataprefetch-mini-f46dba5c.js:15)

**Comment by gagan2singh** [comment]
[https://github.com/SharePoint/sp-dev-docs/issues/3703](url)

**Comment by patmill** [comment]
So, I'm trying to repro this, and not having much luck.  Can you do a couple of things?

1 - hit https://yourtenant.sharepoint.com/[siteurl]/_api/web/usercustomactions
Make sure your component is listed.  Also, look at what the registered section has.  It should look something like:
                <d:RegistrationId>100</d:RegistrationId>
                <d:RegistrationType m:type="Edm.Int32">1</d:RegistrationType>
                <d:Scope m:type="Edm.Int32">3</d:Scope>

2 - When you hit your list, open the network tab and look for an XHR call to customActionElements.  If you look at the response, does your component show there?

3 - Is there a request to fetch your .js file?

4 - Are there any errors in the console?

**Comment by gagan2singh** [comment]
Hi @patmill thanks for the update.

All the above are true. The error on the console is on the original bug description.

Please see the steps to reproduce:
1) Open the project extension
2) Run gulp serve
3) Copy and paste the URL generated and enter that on the URL:
    e.g. (LibraryURL)?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&fieldCustomizers=%7B"(Field Name)"%3A%7B"id"%3A"(Field ID)"%2C"properties"%3A%7B%7D%7D%7D
4) Try to add a debug point to the webpack file generated
5) Debug point will not hit

Background, it use to work only stopped during the recent update.

JUST and FYI, when we deploy the code it works only gulp serve errors out. This is an issue as we cannot publish the code until we debug using gulp serve.

Hope the above will help you to regenerate the issue

**Comment by ramonitor** [comment]
I can conform this. 

We are seeing the same behaviour on our O365 dev tenant with our command set extension. Breakpoints are no longer hit and we get the 'There is no operation handler registered..' error @gagan2singh is experiencing.

**Comment by gagan2singh** [comment]
Hi team, any update on this one. It is impacting our schedule for any deployments. Let us know if we can go ahead and raise a case with Microsoft, or this can be resolved in this forum.

**Comment by gagan2singh** [comment]
It seems that the issue was reported previously, and has started occurring back
https://github.com/SharePoint/sp-dev-docs/issues/3703

**Comment by ArunRajiv** [comment]
@gagan2singh I too experiencing the exact problem as yours. List View Command Set Extension is not working in the Debug Mode. But it works after i package the solution -> upload .sspkg file in App Catalog -> Add the extension to my site.

In the debugging mode, there were No Errors in the console. Break Points don't get hit.

@andrewconnell @VesaJuvonen is this something which can be fixed soon? we have an urgent business feature to be implemented based on this.

**Comment by JonathanJourdan** [comment]
@gagan2singh I too experiencing the exact problem as yours. List View Command Set Extension is not working in the Debug Mode. But it works after i package the solution -> upload .sspkg file in App Catalog -> Add the extension to my site.

 In the debugging mode, there were No Errors in the console. Break Points don't get hit.


Same problem for me... extension don't works
No error in the console in the debugging mode.

**Comment by rich8rd** [comment]
I'm also experiencing this issue and is hampering critical development work.

**Comment by gagan2singh** [comment]
@andrewconnell @VesaJuvonen Hope you guys are doing well.
Can you please check what has been updated again that is causing this to break.

**Comment by gagan2singh** [comment]
@andrewconnell do you have any update on this one.

**Comment by gagan2singh** [comment]
Hi Team, the issue seems to be fixed on the new version of Chrome (Version 75.0.3770.142 (Official Build) (64-bit).

**Comment by frnk01** [comment]
Command sets do not show up here either while running gulp serve. Running newest Chrome without any luck.

**Comment by dreamsandcode** [comment]
We are also still experiencing the exact  same issue.

**Comment by JonathanJourdan** [comment]
Guys here a workaround by @jackpoz it's work for me ! :)
#4374 (comment)

**Comment by andrewconnell** [comment]
This workaround may help: https://github.com/SharePoint/sp-dev-docs/issues/4374#issuecomment-516815819. 

Appears a regression was introduced at some point that caused the wrong URL to be generated by **gulp serve** which isn't telling SPO to load SPFx onto the page if it isn't already there.

Please try this and report back if it resolves your issue.

**Comment by ramonitor** [comment]
@andrewconnell, the workaround mentioned in [#4374 ](https://github.com/SharePoint/sp-dev-docs/issues/4374) (changing loadSPFX to loadSpfx in the query string) resolves our issue!
