### ISSUE TITLE
OnQuickLaunch=TRUE does not work

### ISSUE THREAD

**Issue by Arioule** [SharePoint/sp-dev-docs#4225]
When I use this attribute on the list instace, the list is not appearing on the quicklaunch

              `OnQuickLaunch="true"  `

**Comment by andrewconnell** [comment]
As strange as it sounds, you need to make it all CAPS: `OnQuickLaunch="TRUE"`

Ref: https://docs.microsoft.com/en-us/sharepoint/dev/schema/listinstance-element-list-instance
