### ISSUE TITLE
Can not open dialog second time in IE11

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#4235]
Everything works well but when I am working with IE11 and try to reopen the popup it doesn't work. Also when I select the color below code is not working so don't see the selected color in dialog as well.

Dialog.alert('Picked color: ${dialog.colorCode}');

Works well with Chrome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02c0a61-69ec-736e-2f49-d36bfe6cdddf
* Version Independent ID: 2eda912c-ebc1-f287-9c1a-656364e59457
* Content: [Tutorial - Use custom dialog boxes with SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx)
* Content Source: [docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Have you reviewed the recently published supported browsers docs here: https://support.office.com/en-us/article/Which-Browsers-Work-With-Office-Online-AD1303E0-A318-47AA-B409-D3A5EB44E452

Pay special attention to the IE11 node for the modern experience & IE's document mode.

If you continue to have the issue, please comment back with some additional context. Thanks!
