### ISSUE TITLE
"Server Too Busy" or "Server Unavailable"? 

### ISSUE THREAD

**Issue by MagicalFan** [SharePoint/sp-dev-docs#4237]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Does the 503 throttling error come with "Server Too Busy" or "Server Unavailable"? We've observed some "Server Unavailable" exceptions when the tenant gets busy, but the doc says" Server Too Busy".
The provided sample code also uses "Server Unavailable".

**Comment by andrewconnell** [comment]
503 != throttling... 429=throttling... that's different.

**Comment by MagicalFan** [comment]
The [Document](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#what-happens-when-you-get-throttled-in-sharepoint-online) says 

> For all other requests, including CSOM or REST calls, SharePoint Online returns HTTP status code 429 ("Too many requests") or 503 ("Server Too Busy") and the requests will fail.

Do you mean 429 must be throttling. For 503, it only means throttling when Server Too Busy, then Server Unavailable is a different exception?

**Comment by andrewconnell** [comment]
[HTTP status 429](https://httpstatuses.com/429) is the response you get when SharePoint reports that your request is being throttled. 

That is not the same as a 500-series error which is a server error. Without more context (SharePoint environment, what you're doing to trigger that, etc), can't comment further.
