### ISSUE TITLE
Command Set pageContext.list points to SitePages library when inserting doc lib as webpart

### ISSUE THREAD

**Issue by barisbikmaz** [SharePoint/sp-dev-docs#4238]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug

#### Expected or Desired Behavior

> Users can insert document librarys also as WebPart into a page.
> My Extension must get the list id of the current document library to do more operations.

#### Observed Behavior

> When I add a document library to a page as webpart and start my command,  **this.context.pageContext.list** points to NOT to the list on which its running but the list where the current page lives. 

#### Steps to Reproduce

> Install a command set extension for a library / list.
> Add this type of list to a page.
> Debug the pageContext

**Comment by andrewconnell** [comment]
That seems by design... the `pageContext` is the current context of the page. 

If you are currently on a page, no matter the extension was added to a document library, it's currently running on a page & pages live in the SitePages library so the context is correct.

**Comment by barisbikmaz** [comment]
@andrewconnell So that means that there is no possiblity to get infos about the document library on which the command set runs, when using a doclib as webpart?

**Comment by andrewconnell** [comment]
"no possibility" is a bit definitive... I can't think of one offhand though... sorry ¯\_(ツ)_/¯
