### ISSUE TITLE
Updated Webpart Title of Provider webpart not reflecting in the Source List of Consumer webpart

### ISSUE THREAD

**Issue by pk091990** [SharePoint/sp-dev-docs#4241]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Could you please suggest how to get the updated **webpart Title** of Provider webpart in to Consumer webpart. Below are the snapshots of sample webpart, I would like to get the "Upcoming Events" name in the Consumer webpart source list not "Events" (which is coming now from manifest file.).

**Provider  Webpart Title Name:**

![image](https://user-images.githubusercontent.com/46436213/60670009-4bc09380-9e8d-11e9-8d99-40397f546887.png)

**Consumer Webpart Source List:**

![image](https://user-images.githubusercontent.com/46436213/60670070-6d217f80-9e8d-11e9-8d65-891e23814077.png)

This scenario would be helpful if I'm adding more than one instance of same webpart on the  page and want to get different data from different instances.Also It is working fine with SharePoint OOB webparts. Please share your thoughts. Thanks!

**Comment by andrewconnell** [comment]
The value shown in the **Connect to source** selector in the consumer is reflecting the title of the web part that is providing data. In this case, the title of the web part was set to "Events". 

Where is "Upcoming events" coming from in the provider?

**Comment by pk091990** [comment]
"Upcoming events " is coming from the webpart properties provided in the manifest file (EventsWebPart.manifest.json)

![image](https://user-images.githubusercontent.com/46436213/60753234-09ae6380-9fed-11e9-99c9-f3885cb7b151.png)
In my project also, I'm using [Pnp spfx webpart title control](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/) which allows to change the webpart title in edit mode. How can i get the updated webpart title in Connect To Source selector of Consumer webpart, not the default one given in the manifest file.
Let me know in case more information required , Thanks !

**Comment by andrewconnell** [comment]
Ah... ok so you've created a custom property **title** that's not the same as the web part **title** property. The property pane is going to show the actual web part title... not the custom property you've created.

**Comment by pk091990** [comment]
Ok..then how the OOB webparts  are exposing their webpart title in case of dynamic data. I just added one oob list webpart and able to get the updated webpart tile in the source List of Consumer webpart.

Just selected one list from oob list webpart and update its title. Same title get reflected in the consumer source list. Is there any other way to expose it?

![image](https://user-images.githubusercontent.com/46436213/60755784-6b34f900-a012-11e9-80b2-2666e25ae991.png)

![image](https://user-images.githubusercontent.com/46436213/60755790-8273e680-a012-11e9-8848-8d3e51a60f6e.png)

**Comment by andrewconnell** [comment]
Sorry, I'm not understanding what you're saying in your last reply. Can you be more descriptive with your repro steps so I can try to repro on my side?

**Comment by pk091990** [comment]
We are using [Pnp spfx webpart title control](https://sharepoint.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/) to render webpart title in our custom spfx webparts. I understood that this is not same as webpart default **title** property. 
However I'm just thinking how to get that pnp webpart title in my Source list of Consumer webpart as it is a custom property. Do you have any sample code for the same or any idea that pnp support its webpart title dynamic connection?

**Comment by patmill** [comment]
If I read this correctly, you are wanting some basic properties (like the webpart title) to be exposed via dynamic data, is that correct?  If so, that would be a feature request, and the best thing would be to open a request in uservoice (https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform)

**Comment by andrewconnell** [comment]
Only the default web part's **Title** property is provided in the dynamic data connection as you've seen. Additional fields aren't provided to the selector in the consumer's property pane... so this would be a feature request as @patmill said.
