### ISSUE TITLE
Page title escaping NPM package when rendered

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#4243]
The page title should be updated to "Use @pnp/sp (PnPJS) library with SharePoint Framework web parts", as the sample demonstrates using @pnp/sp library with SPFx.

The page content source has the correct title set. But it is not reflected may be due to markdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b19eb96-192d-2d8b-8d4e-0de787f22093
* Version Independent ID: e2cbd2b2-8bb7-a95f-0768-15f1b045b4c4
* Content: [Use @pnp/sp (PnPJS) library with SharePoint Framework web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts)
* Content Source: [docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like an escaping issue in the title when rendered. Thanks... will get this sorted.
