### ISSUE TITLE
SharePoint Modern experience suddenly stopped working in Chrome , Mozilla browser

### ISSUE THREAD

**Issue by vivekkanse** [SharePoint/sp-dev-docs#4244]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

Modern experience suddenly stopped working in Chrome and Mozilla browser. We are getting below issue in the console log.

splistitemsscope-is-mini-84383ece.js:1 Uncaught Error: There is no operation handler registered for '{"operation_4":["getItems_16","spItemGroup_235"]}'.
    at e.n (spofiles-mini-be65a0bf.js:1)
    at new e (splistitemsscope-is-mini-84383ece.js:1)
    at splistitemsscope-is-mini-84383ece.js:1
    at splistitemsscope-is-mini-84383ece.js:1
    at splistitemsscope-is-mini-84383ece.js:1
    at splistitemsscope-is-mini-84383ece.js:1
    at dispatch (splistitemsscope-is-mini-84383ece.js:1)
    at splistitemsscope-is-mini-84383ece.js:1
    at listviewdataprefetch-mini-f46dba5c.js:15
    at Object.next (listviewdataprefetch-mini-f46dba5c.js:15)

and

Uncaught Error: Timed out waiting for OAuth.
    at e.n (spofiles-mini-be65a0bf.js:1)
    at new e (sp-http-mini-c362ff75.js:1)
    at e.<anonymous> (sp-http-mini-c362ff75.js:1)
    at spofiles-mini-be65a0bf.js:1

Note: For same Libraries, List modern experience working in Internet Explorer. 
**SharePoint Environment:** SharePoint Online
**SPFx Version:**  1.4.1

I have developed Application Customizer extension using SPFx last year and publish it to Production environment last year Sep-Oct 18. It is still working as expected but the problem we are facing in Chrome and Mozilla browser for Modern experience which is not working in document libraries, lists.

![image](https://user-images.githubusercontent.com/40199872/60796467-0bae2900-a18b-11e9-841c-6ee3bf9ad48e.png)

Error ScreenShot - SitePages Library
![image](https://user-images.githubusercontent.com/40199872/61035672-398eaa00-a3e5-11e9-9f3e-7eb8f64e2c59.png)

**Comment by andrewconnell** [comment]
Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:

- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
- If SharePoint Online, is tenant configured for standard / targeted release
- SPFx version
- Sample code that triggered this 

As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.

**Comment by patmill** [comment]
When you say "Note: It seems some script getting blocked in Chrome and Mozilla. For same Libraries, List modern experience working in Internet Explorer."  what scripts are getting blocked?  Is it content-security-policy errors?  Anything in the console or the network tab?

**Comment by vivekkanse** [comment]
> When you say "Note: It seems some script getting blocked in Chrome and Mozilla. For same Libraries, List modern experience working in Internet Explorer." what scripts are getting blocked? Is it content-security-policy errors? Anything in the console or the network tab?

@patmill I have added the console log error screenshot from Chrome.

**Comment by vivekkanse** [comment]
@andrewconnell  Now it stopped working in IE also. It will be great if you can help me out on this issue.

**Comment by vivekkanse** [comment]
Hello,
The issue gets resolved now, The content was invisible for Library and List in Modern UI due to update in SharePoint classes from Microsoft. Earlier we had added some custom CSS for client requirement.
