### ISSUE TITLE
CSOM: Create password protected sharing links

### ISSUE THREAD

**Issue by rbarten** [SharePoint/sp-dev-docs#4245]
# Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

CSOM should contain an option to create a password protected sharing link. Currently I cannot find that option within the SDK. We currently have that option in the UI, is it also possible to create them through CSOM/API's? Or will this be available in the near future?
https://www.microsoft.com/nl-nl/microsoft-365/roadmap?filters=&searchterms=27018

#### Observed Behavior
Currently cannot find an option to create a sharing link which is password protected.

**Comment by andrewconnell** [comment]
That capability is just now rolling out to the service and doesn't appear to be present in the REST API / CSOM API ATM... this is a good resource to use to track changes int he APIs: https://s-kainet.github.io/sp-rest-explorer

**Comment by rbarten** [comment]
@andrewconnell : Thanks for your reply. I was hoping for a API first strategy here :wink:. But let's hope it will be available soon.
