### ISSUE TITLE
SPFx 1.8.2 MSGraphClient fails with /me/drive/root/children

### ISSUE THREAD

**Issue by anthonywhite** [SharePoint/sp-dev-docs#4248]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behaviour
SPFx **1.8.2** web part using **MSGraphClient**, calls to 2 separate endpoints:

#### /me/drive/root/children

would expect both calls to be honoured, given correct AAD permissions granted (which they are)

#### Observed Behaviour

the call to **/me/drive/root/children** only works **_if I also sign into the Graph Explorer_** at [developer.microsoft.com](https://developer.microsoft.com/en-us/graph/graph-explorer)

otherwise fails with ```HTTP 400``` on endpoint ```fetch``` (from F12 network tab):

```/driveItem/recommendedItems?$expand=analytics($expand=allTime,lastSevenDays)&filter=recommendation/itemRankingScore%20gt%200.5&top=8```

initiator:
```https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-21.010/sp-pages-assembly_en-gb_e015df117304671c0961231b906dc409.js```

and response:
```{"error":{"code":"invalidRequest","message":"The requested expand is not supported for this endpoint"}}```

#### Steps to Reproduce
SPFx v 1.8.2
SPFx web part using MSGraphClient, calls to 2 separate endpoints:

/me/calendar/events
/me/drive/root/children

**Comment by andrewconnell** [comment]
Looking at the network tab, compare the full URL endpoints requested. That error indicates that `$expand=analytics` isn't supported on the endpoint you're calling (v1.0) where it might be supported on the beta endpoint...

**Comment by anthonywhite** [comment]
Hi Andrew, just to clarify, I didn't add the expand, my code simply calls /me/drive/root/children, so the expand has been added under the covers somewhere, I guess in the sp-pages-assembly_en-gb_e015df117304671c0961231b906dc409.js?

**Comment by andrewconnell** [comment]
I doubt that's adding it... AFAIK, that has nothing to do with the Graph. The MSGraphClient is just a shim wrapper to the Graph JS SDK so if anything is changing the URL, I'd expect it's coming from that.

With that being said, if you can provide a repo (public github repo) I can try it out in my tenant...

**Comment by anthonywhite** [comment]
Interesting...reducing to a single call for repo purposes, data now retrieves ok (however the error on the expand endpoint is still visible in F12)...I can see previous issues logged around chaining/sequencing multiple client calls. Are there any dos/don'ts guidance on:
a) calling the msGraphClientFactory more than once in a component
b) running the graph calls in sequence/parallel?

**Comment by andrewconnell** [comment]
@anthonywhite said:
> Are there any dos/don'ts guidance on...

Not really... the SPFx & Microsoft Graph integration is very simple. The factory simply obtains an access token from SPO and uses that to initialize the Microsoft Graph JS SDK. Once you have the `MSGraphClient`, you're not really doing anything with SPFx. At that point, it's all Microsoft Graph JS SDK.

Issues calling the factory more than once in a component? Not that I'm aware of, but for perf reasons, you'd do better to reuse the client you get from the first call (to avoid the request to SPO to obtain a new access token) _UNLESS_ the access token has expired (ie: you are in a SPA-like scenario and the user is on the page for an extended period of time).

Running calls to Microsoft Graph in sequence / parallel? Not that I'm aware of, but that is really more of a question to the Graph team with [their JS SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript)

**Comment by andrewconnell** [comment]
@anthonywhite said:
> however the error on the expand endpoint is still visible in F12

Is this triggered by one of your calls or is it possibly by something else on the page, like an OOTB SPO component? There are SPFx components from MSFT used in SPO that leverage the Microsoft Graph... if it's not your code, you can ignore it...

**Comment by anthonywhite** [comment]
Yes, looks like it's SP itself as it persists after I remove my component. Just assumed an error would be my code;-).
Thanks...
