### ISSUE TITLE
Renewing certification in production environment

### ISSUE THREAD

**Issue by hsantan** [SharePoint/sp-dev-docs#4250]
I couldn't find anything mention about renewing certificate in production environment. Is it possible create a topic or Note talking about this!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c6ed75-c877-0342-6dea-60da2f80a866
* Version Independent ID: 7c7d70ba-1847-5d0d-135f-4dd84f9642d8
* Content: [Create high-trust SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-high-trust-sharepoint-add-ins#feedback)
* Content Source: [docs/sp-add-ins/create-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-high-trust-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You don't renew, you replace it with a new one.

You basically repeat the process as explained in the document... ideally before the existing certificate expires... specifically the part of the doc where you [replace the dev cert with a real cert](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-high-trust-sharepoint-add-ins#NewCertificate).

Once the new cert has been setup to trust it, update the app to use it.

Optionally, delete the told token issuer & TRA for the cert you're expiring. The following are some steps  you can use to remove it.

1. Run `Get-SPTrustedRootAuthority` to get a list of all TRA's
1. Delete the existing cert with `Remove-SPTrustedRootAuthority -Identity <name of existing RA>`
1. Verify it's gone with `Get-SPTrustedRootAuthority` again
1. Remove old token issuer:
    1. Run `Get-SPTrustedSecurityTokenIssuer` to get a list of existing issuers
    1. Run `Remove-SPTrustedSecurityTokenIssuer -Identity <name of token issuer>`
