### ISSUE TITLE
Schema for the actionParams JSON

### ISSUE THREAD

**Issue by haschdl** [SharePoint/sp-dev-docs#4251]
In the context of column formatting in SharePoint, it is currently possible to trigger a Flow using the  `"action" : "executeFlow"` in `customRowAction` of a button element. This is documented here https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow

Documentation and accompanying examples only show `actionParams` containing a escaped JSON with a single `id` attribute. Can other values be passed to `actionParams`, enabling parametrized execution of flows? 

```
"customRowAction": {
	    "action": "executeFlow",
	    "actionParams": "='{\"id\": \"11441f46-d8eb-4137-9c7e-a085"}'"
}

```      
Note: since this is a question I omitted the sections Steps to reproduce etc.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
This seems to be a question related to flow, not SharePoint development, correct? If so, your question should be posted to the flow community:

https://powerusers.microsoft.com/t5/Microsoft-Flow-Community/ct-p/FlowCommunity

**Comment by haschdl** [comment]
I’m not sure. All the code I mentioned is applicable to SharePoint column formatting, and documented in a SharePoint development. I’d assume the code base for parsing the JSON and make the API calls towards MS Flow lies on the SharePoint side, so I’m inclined to say this is the right repo.

**Comment by thechriskent** [comment]
You are correct, there are a couple of other options we should get documented there. Here is the full list of options:

- **ID**: ID of the Flow to launch (required)
- **headerText**: Sets the text at the top of the flow panel (optional)
- **runFlowButtonText**: Sets the text of the primary button in the flow panel (optional)

Here's an example of using all three:

```JSON
"customRowAction": {
    "action": "executeFlow",
    "actionParams": "{\"id\":\"f7ecec0b-15c5-419f-8211-302a5d4e94f1\", \"headerText\":\"It's Flow Time!\",\"runFlowButtonText\":\"Do it\"}"
  }
```
The code above can be found in the rowactions sample: https://github.com/SharePoint/sp-dev-list-formatting/blob/master/column-samples/generic-rowactions/executeFlow.json
