### ISSUE TITLE
Never specify where to use Application (client) ID once it is created

### ISSUE THREAD

**Issue by zlavoie** [SharePoint/sp-dev-docs#4252]
In the document it says "Once the application has been created copy the "Application (client) ID" as you’ll need it later." But then there is never instruction on where to use "Application (client) ID" again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yes there is... there are a few places. In the PowerShell cmdlet `Connect-PnPOnline` in [this section](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#using-this-principal-with-pnp-powershell) as well as when setting the `appid` variable in the code within [this section](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#using-this-principal-in-your-powershell-script-using-the-pnp-sites-core-library)
