### ISSUE TITLE
cannot serve using-page-placeholder-with-extensions

### ISSUE THREAD

**Issue by RiccardoAmadi** [SharePoint/sp-dev-docs#4256]
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

Hello, I'm trying the tutorial at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
From Visual Code Studio I see a Problem in serve.json:
`Property serve configurations is not allowed`

if I ignore the warning and try gulp serve I get:
```
Build target: DEBUG
[15:38:57] Using gulpfile ~\Documents\app-extension\gulpfile.js
[15:38:57] Starting 'serve'...
[15:38:57] Starting gulp
[15:38:57] Starting subtask 'configure-sp-build-rig'...
[15:38:57] Finished subtask 'configure-sp-build-rig' after 3.75 ms
[15:38:57] Starting subtask 'spfx-serve'...
[15:38:57] Starting server...
[15:38:57] Error - [spfx-serve] Error: Invalid glob argument:
[15:38:57] Error - 'spfx-serve' sub task errored after 138 ms
 Invalid glob argument:
[15:38:57] 'serve' errored after 146 ms
[15:38:57] About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1
```

**Comment by andrewconnell** [comment]
Can you share the contents of your **server.json**? 

*NOTE: when you copy a bunch of code / output from the console, use three backticks, not just a single one. Otherwise, everything is thrown on one line. Edit your original post above to see how I changed it so it would be easier to read the output from the console.*

**Comment by RiccardoAmadi** [comment]
This is my serve.json
`{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://mcquayit.sharepoint.com/sites/intranet/SitePages/test_extension.aspx",
      "customActions": {
        "3a458201-a743-46fe-808e-4b0f4897ef3c": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "Top": "Top area of the page",
            "Bottom": "Bottom of the page"
          }
        }
      }
    },
    "helloWorld": {
      "pageUrl": "https://mcquayit.sharepoint.com/sites/intranet/SitePages/test_extension.aspx",
      "customActions": {
        "3a458201-a743-46fe-808e-4b0f4897ef3c": {
          "location": "ClientSideExtension.ApplicationCustomizer",
          "properties": {
            "Top": "Top of the page",
            "Bottom": "Bottom of the page"
          }
        }
      }
    }
  }
}
`

**Comment by andrewconnell** [comment]
Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:

	- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
	- If SharePoint Online, is tenant configured for standard / targeted release
	- Browser(s) tested (if applicable)
	- SPFx version
	- Office UI Fabric React version (if applicable)

As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.

**Comment by RiccardoAmadi** [comment]
- Sharepoint Online
- user is configured for targeted release. Tenant is configured for standard
- SPFx version v1.8.2
- gulp v4.0.2

Gulp version was the issue. Solution at https://github.com/PointCloudLibrary/pcl/issues/2407#issuecomment-430223175
### Make sure your local version of gulp is not 4.0.0

If the local version of gulp is 4.0.0 then change into the package.json and make the configuration to 3.9.1 and try npm install --save and then try gulp serve

This will do the trick.
