### ISSUE TITLE
Event date time zone issue

### ISSUE THREAD

**Issue by sephys** [SharePoint/sp-dev-docs#4259]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hello, I'm facing to a weird behavior about **EventDate** and **EndDate** that are displayed in a particular Event. 

#### Expected or Desired Behavior
I'm currently creating an event starting the 26/10/2019 at 04:00:00 AM and ending at 05:00:00 AM
Site in which I create this event have a time zone set to(UTC+01:00) Bruxelles, Copenhague, Madrid, Paris.

I'm supposed to get an event starting at specified time, meaning event page should display :
When : 	Saturday, October 26, 2019
		4:00 - 5:00
		(UTC+01:00) Brussels,Copenhaguen,Madrid,Paris

And retrieved data (from rest-api for exemple) for created event should be :

{   
    "EventDate": "2019-10-26T02:00:00Z",
    "EndDate": "2019-10-26T03:00:00Z"
}

Indeed Sharepoint storing date in UTC format and target dates are before 27/10/2019 at 03:00:00 AM, the date we switching from UTC+02:00 to UTC+01:00.

#### Observed Behavior

Once event is created I get folowing information on event page : 

When : 	Saturday, October 26, 2019
		5:00 - 5:00
		(UTC+01:00) Brussels,Copenhaguen,Madrid,Paris
		
And retrieved data (from rest-api) for created event :

{   
    "EventDate": "2019-10-26T03:00:00Z",
    "EndDate": "2019-10-26T04:00:00Z"
}		

I'm little confused about stored dates which did'nt match (with expected stored dates and displayed dates).
Why EventDate is converted from  2019-10-26T03:00:00Z to 2019-10-26T05:00:00+02:00 and EndDate from 2019-10-26T04:00:00Z to 2019-10-26T05:00:00+01:00 ?

Am I misunderstanding about something or is it a bug?  

#### Steps to Reproduce

Set your Site time zone to (UTC+01:00) Brussels,Copenhaguen,Madrid,Paris.
Create an Event at Saturday, October 26, 2019 from 04:00:00 AM to 05:00:00 AM

**Comment by lucabandMSFT** [comment]
@juliemturner  wrote a great article on this topic available here: https://julieturner.net/2017/04/sharepoint-time-is-not-your-time-is-not-their-time/. Does that provide the help you are looking at?
