### ISSUE TITLE
SPListSubactions/setTitle - SPO Site design is not updating the existing library

### ISSUE THREAD

**Issue by prasantabhowmik** [SharePoint/sp-dev-docs#4268]
Hi,

SPO Site design is not updating the existing library, if I use the sub action setTitle.

Every time I apply the SPOSiteDesign, its create a new document library instead of updating the existing one.

e.g
1. I have created a document library name MyTestLib using createSPList.
2. Set the title of the library as "My Test Lib" using subaction setTitle.

Please let me know if I am missing something in the scripts.

Thanks,
Pras

**Comment by bcameron1231** [comment]
Thanks for issue. This is a known problem, here is a related issue #4081
