### ISSUE TITLE
Team site (no Office 365 group) provisioning

### ISSUE THREAD

**Issue by Lagarto66** [SharePoint/sp-dev-docs#4273]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi, how to provision a team site programmatically, with no connection to an Office 365 Group?

**Comment by bcameron1231** [comment]
Can you provide more information on how you want to go about creating these? Are you using C#, PowerShell, JavaScript? Do you want to try and use REST?

A modern team site without a group uses a web template called STS#3. 

**Using PnP**
```
New-PnPTenantSite `
  -Title "Modern Site" `
  -Url "https://tenant.sharepoint.com/sites/modern-site" `
  -Description "Modern Site" `
  -Owner "admin@tenant.onmicrosoft.com" `
  -Lcid 1033 `
  -Template "STS#3" `
  -TimeZone 10 `
  -Wait
```
**Using REST**
Check out the section 'Create a modern site' and use STS#3
https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest

**Comment by Lagarto66** [comment]
thank you @bcameron1231 
That would work nicely with PnP PowerShell in my scenario/automation
Is there a way to apply the same concept to site design so the user can create it( team site without O365 group)?

**Comment by bcameron1231** [comment]
@Lagarto66 In theory yes. You can create a Site Design for Non-Group Connected Team sites by using WebTemplate = 1 for the Site Design. However, there seems to be an issue/bug with these Site Designs. See reference #4130 . I'm still waiting to hear back from MSFT on whether or not this will be fixed.

**Comment by Lagarto66** [comment]
Thank you, looks like this needs a custom flow and Power Shell. Cheers
