### ISSUE TITLE
tslint errors when creating SharePoint 2016 React Web Part

### ISSUE THREAD

**Issue by k-mad** [SharePoint/sp-dev-docs#4275]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The @microsoft/sharepoint yoeman generator should install demo code that can be edited without lint errors. The file node_modules/@microsoft/sp-tslint-rules/base-tslint.json is missing.

Should the file node_modules/@microsoft/sp-tslint-rules/base-tslint.json exist when SharePoint 2016 is targeted?

#### Observed Behavior

When I run the @microsoft/sharepoint yeoman and make any edit to a TypeScript file, I get the following error:

Cannot read tslint configuration - 'Failed to load c:\Users\k\hello\tslint.json: Invalid "extends" configuration value - could not require "@microsoft/sp-tslint-rules/base-tslint.json". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.'

#### Steps to Reproduce

1. Run the yeoman generator

```bash
yo @microsoft/sharepoint

Let's create a new SharePoint solution.
? What is your solution name? hello
? Which baseline packages do you want to target for your component(s)? SharePoint 2016 onwards, including 2019 and SharePoint Online
? Where do you want to place the files? Use the current folder
Found npm version 6.9.0
? Which type of client-side component to create? WebPart
Add new Web part (on-prem) to solution hello.
? What is your Web part (on-prem) name? hello
? What is your Web part (on-prem) description? hello description
? Which framework would you like to use? React
```
2. Add a new line to src/webparts/hello.ts and save the change.

3. Open the problems panel in VS Code to view the error.

#### Environment

Windows 10
node 10.16.0
npm 6.9.0
yeoman 3.1.0
gulp 3.9.1

package.json
```JSON
{
  "name": "hello",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "@types/react": "0.14.46",
    "@types/react-dom": "0.14.18",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-update": "0.14.14",
    "@types/react-addons-test-utils": "0.14.15",
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0-0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
```

**Comment by andrewconnell** [comment]
Yes, it should be there. What version of SPFx are you running? I just verified it's working with SPFx v1.8.2

**Comment by k-mad** [comment]
I also have version 1.8.2.
```
PS C:\Users\k\hello> npm list -g @microsoft/generator-sharepoint
C:\Users\k\AppData\Roaming\npm
`-- @microsoft/generator-sharepoint@1.8.2
```
I reran the generator and had the same issue. I'll try uninstalling and reinstalling but I probably won't get to it until Monday. I'm not sure what else to do if you have the file and I don't.
 Let me know if you have any other ideas.

**Comment by andrewconnell** [comment]
After creating the project, did you let it run `npm install` to download all dependencies? It does this by default... you should see a **node_modules** folder within the project root with a ton of folders/files.

**Comment by k-mad** [comment]
It the generator seems to run `npm install` (it installs 980 packages in the node_modules folder).

I reinstalled @microsoft/generator-sharepoint. It's still version 1.8.2. Re-running with the 2016 option and React still doesn't create the file node_modules/@microsoft/sp-tslint-rules/base-tslint.json

```
PS C:\Users\k\hello> ls .\node_modules\@microsoft\sp-tslint-rules\
    Directory: C:\Users\k\hello\node_modules\@microsoft\sp-tslint-rules

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/15/2019   7:55 AM                EULA
d-----        7/15/2019   7:54 AM                lib
d-----        7/15/2019   7:59 AM                node_modules
-a----         6/6/2017   1:38 PM           1967 CHANGELOG.json
-a----         6/6/2017   1:38 PM            720 CHANGELOG.md
-a----        7/15/2019   7:58 AM           2903 package.json
-a----        5/26/2017  12:39 PM            555 README.md
```

**Comment by andrewconnell** [comment]
When I try to repro, I don't have that file either, but I'm not getting an error when I build. Can you share the complete output when you run `gulp build`?

**Comment by k-mad** [comment]
I'm not having any problem with `gulp build` either:

```
PS C:\Users\k\hello> gulp build
Build target: DEBUG
[10:03:49] Using gulpfile ~\hello\gulpfile.js
[10:03:49] Starting gulp
[10:03:49] Starting 'build'...
[10:03:49] Starting subtask 'pre-copy'...
[10:03:49] Finished subtask 'pre-copy' after 204 ms
[10:03:49] Starting subtask 'copy-static-assets'...
[10:03:49] Starting subtask 'sass'...
[10:04:09] Finished subtask 'sass' after 20 s
[10:04:09] Starting subtask 'tslint'...
[10:04:10] Starting subtask 'typescript'...
[10:04:10] [typescript] TypeScript version: 2.2.2
[10:04:13] Finished subtask 'copy-static-assets' after 24 s
[10:04:31] Finished subtask 'tslint' after 22 s
[10:04:31] Finished subtask 'typescript' after 20 s
[10:04:31] Starting subtask 'ts-npm-lint'...
[10:04:31] Finished subtask 'ts-npm-lint' after 127 ms
[10:04:31] Starting subtask 'api-extractor'...
[10:04:31] Finished subtask 'api-extractor' after 2.32 ms
[10:04:31] Starting subtask 'post-copy'...
[10:04:31] Finished subtask 'post-copy' after 1.09 ms
[10:04:31] Finished 'build' after 42 s
[10:04:31] ==================[ Finished ]==================
[10:04:32] Project hello version: 0.0.1
[10:04:32] Build tools version: 2.5.3
[10:04:32] Node version: v10.16.0
[10:04:32] Total duration: 1.77 min
```

I can also run `gulp serve`, `gulp clean`, `gulp bundle --ship`, and `gulp package-solution --ship` without any problem.

The only problem so far is the message in the problems panel in VS Code. I'm assuming that linting rules that I may want also aren't being applied.

**Comment by andrewconnell** [comment]
That changes things... there's nothing wrong with SPFx then... so I'm going to close the issue.

Seems like you have something with VSCode that's the issue... but it's not related to SPFx. Maybe an old version of an extension in VS Code or something like that. This is the only tslint related extension I have installed in my VSCode and I don't see those issues: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin
