### ISSUE TITLE
AADSTS65001 only when debugging in workbench

### ISSUE THREAD

**Issue by SharePickle** [SharePoint/sp-dev-docs#4279]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Hello, I honestly not sure if bug or im doing something wrong.
Getting this error `AADSTS65001` every time I try to debug (in hosted workbench or debugManifest query string).

I have deployed an azure function and try to access it from SPFx webpart.
I did use this guide [Consume enterprise APIs secured with Azure AD in SharePoint Framework
](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
It DOES work when I deploy a production (--ship) version, but won't work in debug mode.

Here's the error:
![image](https://user-images.githubusercontent.com/32567749/61060868-ea0ba680-a403-11e9-83c7-d2f2c91a11f1.png)

I have tried many solutions related to this error, but nothing seems to work.
Thanks.

#### Expected or Desired Behavior

Should work in debug mode.

#### Observed Behavior

Doesn't work in debug mode.

**Comment by SharePickle** [comment]
Okay, probably my bad.
I had to manually add my Azure AD app (called it `SPFXFuncAppTestAD`) permissions to `SharePoint Online Client Extensibility Web Application Principal` and grant permissions.
![image](https://user-images.githubusercontent.com/32567749/61063196-348f2200-a408-11e9-88bf-5a99b9ac065f.png)

The question is - should I do it manually or it supposed to be automatic?

**Comment by bcameron1231** [comment]
You shouldn't have to do that. You should consent the permissions from the API management page in the new SharePoint Admin Center.  Did you do that?

**Comment by SharePickle** [comment]
> You shouldn't have to do that. You should consent the permissions from the API management page in the new SharePoint Admin Center. Did you do that?

Yes, I followed the example steps.

**Comment by andrewconnell** [comment]
This is by design... you can't run the component from the local web server to obtain an access token from SPO. You must deploy it to test it to obtain the access token. This applies to component using the **AADHttpClient** & **MSGraphClient**.

**Comment by SharePickle** [comment]
> This is by design... you can't run the component from the local web server to obtain an access token from SPO. You must deploy it to test it to obtain the access token. This applies to component using the **AADHttpClient** & **MSGraphClient**.

Thanks for replying, I just wonder how do I test it properly then? I think I saw it's possible to use `gulp serve` in spfx to test it?
