### ISSUE TITLE
How do restrict the app-auth for just a subset of site collections?

### ISSUE THREAD

**Issue by nddipiazza** [SharePoint/sp-dev-docs#4280]
Is app-auth "all or nothing?"

I want to know how to specify an app-auth key but *only* for a certain subset of site collections.

So let's say you use the app-client-id, and app-client-secret... then you authenticate to your sharepoint online account using my.username@tenant.onmicrosoft.com to get the refresh token.

Does my User's access my.username@tenant.onmicrosoft.com dictate my permissions? Or does the app-auth key give me basically all the access in the world? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It doesn't work like that... it's tied to the TLD, so the tenant domain and thus, all site collections.

**Comment by nddipiazza** [comment]
Thank you for your prompt response @andrewconnell ! super appreciated.

**Comment by nddipiazza** [comment]
@andrewconnell so app-auth is not meant to be used for fine-grained access to a subset of the tenant or site collections, correct?

is the correct alternative a sharepoint service account authenticated through SAML?

**Comment by andrewconnell** [comment]
@nddipiazza said:
> app-auth is not meant to be used for fine-grained access to a subset of the tenant or site collections, if I read that correct.

Correct

@nddipiazza said:
> is the correct alternative a sharepoint service account authenticated through SAML? are there additional options?

Not for app-only that I can think of
