### ISSUE TITLE
CommandSets are not picking up the selected rows from the event when the user scrolls down the page and it content re-renders

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#4284]
BUG: first reported in two tenants yesterday

#### Category
- [ X] Bug

Description
When scolling down a long list and selecting an item, the CommandSet is not picking up the selected rows from the event. It is intermittent but can be replicated after a few attempts.
event.selectedRows.length is returning 0 despite rows being selected.
Seems to be a problem as you scroll down the list and items load dynamically. Worked fine for months until this week and confirmed on twitter by other developers.

To Replicate:
Follow the guide here to create a commandset: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

Before this line:
switch (event.itemId) {

Add this line 
alert(event.selectedRows.length)

When running it from the top of the page you will get an alert with the number of rows. When scolling down the page, you will only get 0 returned.

**Comment by CloudDesignBox** [comment]
@patmill To make you aware of this issue 👍

**Comment by CloudDesignBox** [comment]
More tenants are also having this issue:
https://twitter.com/Tonyp543212003/status/1149601933398663171

**Comment by patmill** [comment]
Got it, thanks.  I'll forward this to the relevant team.

**Comment by martinlaukkanen** [comment]
I have a customer facing this issue as of this week, and I have been able to reproduce the problem in my test tenant by doing the following:

- Deploy a basic command set to test against
- Create a simple list with 3+ multi-line text columns
- Create 31+ (min) items in the list,  copy some large text paragraph into every item
  - I found with only 2-3 columns with no data the problem does not occur
- Now scroll to the 31st or later item, and in my case in two environments event.selectedRows.length is zero consistently in onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters)

Hope that helps,

**Comment by CloudDesignBox** [comment]
Great tip @martinlaukkanen, that workaround helped for our tenants too. This isn't ideal though, as some point we will hit the 5000 item limit of a view. 
It is hard to replicate (sometimes it works and others it doesn't so Microsoft closed my support case) but I hope a MS developer sees this and fixes the problem.

**Comment by patmill** [comment]
Hi @CloudDesignBox - we've had a dev digging into this alongside the updated list logic rollout.  They are unable to reproduce this with the changes pushed through the service in the past month or two.  Can you see if the problem is still reproducible on your side?  Thanks.

**Comment by CloudDesignBox** [comment]
@patmill I don't seem to be able to replicate this. It was intermittent before but the workaround was to set the view item limit to 4999 so that it didnt load on demand. I've tried this on 30 items in the view and scrolling down, didnt get the error this time. Thanks for looking.
