### ISSUE TITLE
For Modern News Article page Like Count is inconsistent for Same Item Id

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4290]
> For SharePoint Online In Modern Site, News Article Count For Modern News Article page's Like Count is inconsistent for Same Item Id
>

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
```
fetch("https://tenant.sharepoint.com/sites/abc/_api/web/lists('%7B33e70554-e77a-4961-8f6d-cb64046fe3cf%7D')/items(109)?$select=Id,LikedByInformation/likeCount&$expand=LikedByInformation,LikedByInformation/likedBy",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r))
 fetch("https://tenant.sharepoint.com/sites/abc/_api/web/lists('%7B33e70554-e77a-4961-8f6d-cb64046fe3cf%7D')/items(109)/LikedByInformation",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r))
 
```
Both Endpoints should return same like count e.g. `likeCount=1`
> 

#### Observed Behavior
```
Result of First Request : {"LikedByInformation":{"likedBy":[],"likeCount":"0"},"Id":109,"ID":109}
Result of Second Request : {"isLikedByUser":true,"likeCount":"1"}

```

#### Steps to Reproduce

> Open any modern site in a browser(Here I have used chrome) and open developer console
> Run below requests(Here you can make changes as per your tennat and site collection
> Make sure in your site pages you have article and you have liked that article.
> Use SitePages Library guid and item id to test below requests 
```
fetch("https://tenant.sharepoint.com/sites/abc/_api/web/lists('%7B33e70554-e77a-4961-8f6d-cb64046fe3cf%7D')/items(109)?$select=Id,LikedByInformation/likeCount&$expand=LikedByInformation,LikedByInformation/likedBy",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r));

fetch("https://tenant.sharepoint.com/sites/abc/_api/web/lists('%7B33e70554-e77a-4961-8f6d-cb64046fe3cf%7D')/items(109)/LikedByInformation",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r))
 
```

**Comment by andrewconnell** [comment]
I'm not able to repro this... 

![image](https://user-images.githubusercontent.com/2068657/61239580-36f5c280-a70d-11e9-82e4-2a9675c9a403.png)

**Comment by anomepani** [comment]
@andrewconnell , First Like one of the article and then check both endpoint likeCount value not consistent.

**Comment by andrewconnell** [comment]
I did with two users (admin & normal user)... assuming it takes time for the counts to get updated, but both still show 0 for now. Will check again tomorrow.

**Comment by anomepani** [comment]
![Article_Page_Inconsistent_likeCount](https://user-images.githubusercontent.com/2988295/61278746-5d316600-a7d2-11e9-9ebb-23d6ba85e71a.png)

@andrewconnell , See attached screenshot for what I am getting.

**Comment by andrewconnell** [comment]
OK... now I'm seeing the same. Using the following queries:

```
fetch("https://m365x460234.sharepoint.com/sites/SalesAndMarketing/_api/web/lists/getbytitle('Site Pages')/items(3)?$select=Id,LikedByInformation/likeCount&$expand=LikedByInformation,LikedByInformation/likedBy",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r));

fetch("https://m365x460234.sharepoint.com/sites/SalesAndMarketing/_api/web/lists/getbytitle('Site Pages')/items(3)/LikedByInformation",{headers:{accept:"application/json;odata=nometadata"}}).then(r=>r.text()).then(r=>console.log(r))
```

I get two different values back:
![image](https://user-images.githubusercontent.com/2068657/61291851-ab784200-a79d-11e9-88a0-52e2ea2314f2.png)

@JeremyKelley The docs would indicate these two values should be the same... something doesn't seem right. Any insight?
