### ISSUE TITLE
SharePoint Framework Extension ApplicationCustomizer - Allow debug scripts popup not loading

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#4291]
#### Category
- [ ] Question

#### Expected or Desired Behavior
gulp serve command execution should display the allow debug script popup in the pageurl configured in serve.json
![image](https://user-images.githubusercontent.com/21008316/61172544-796fa180-a54b-11e9-8c47-833ec48fe176.png)

#### Observed Behavior
Allow debug script popup is not loading to debug

#### My Environment 
node - v10.16.0
npm - 6.9.0
gulp - 3.9.1 

Any idea?

**Comment by vinod9691** [comment]
I am also facing the same issue. Please help me out

**Comment by andrewconnell** [comment]
Can you please share some context? SharePoint environment you've tested this in, SPFx version, browser used, etc. Also, in this case, can you share the URL as there are URL parameters that trigger this...

**Comment by sprider** [comment]
@andrewconnell 
Please find the details below: 

SharePoint Environment - SharePoint Online
SPFx Version - 1.8.2 
Browser - Chrome Version 75.0.3770.100 (Official Build) (64-bit)
URL : https://mytenantname.sharepoint.com/SitePages/DevHome.aspx?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&customActions=%7B%22fd56ce3c-8333-45a2-9c0c-94f86fa30078%22%3A%7B%22location%22%3A%22ClientSideExtension.ApplicationCustomizer%22%2C%22properties%22%3A%7B%22Top%22%3A%22Top+Message%22%7D%7D%7D

**Comment by lucabandMSFT** [comment]
hey @sprider, is that URL split out from GULP Serve?
I just tried that on a plain 1.8.2 environement and I can't repro the issue: every time I run gulp serve and I open the browser with the URL that is outputed in the CLI I can see the dialog showing up. The instruction I followed to test my extension is here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

**Comment by sprider** [comment]
@lucabandMSFT 
I have followed the same instructions. Please refer my code here https://github.com/sprider/temp

**Comment by andrewconnell** [comment]
@sprider I cloned your repo, installed dependencies (`yarn`), updated the **serve.json** to point to my tenant & ran `gulp serve`. Worked exactly as designed. Tested in Chrome, Chrome Canary, FireFox & Microsoft Edge _[Cromium]_ Canary.

**Comment by sprider** [comment]
@andrewconnell In this case, I need to check something at my end. Thank you for confirming.
