### ISSUE TITLE
Custom tab is not added to Home.aspx or other publishing pages

### ISSUE THREAD

**Issue by weechong-ong** [SharePoint/sp-dev-docs#4292]
I have tried following the examples, and the custom tab appear for all pages except the "Pages" such as the Home.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfd70c5c-2c65-05e1-cc47-bb9f2fa83bc5
* Version Independent ID: c452fbf2-1b7f-c227-0371-143b4a36b3d6
* Content: [Add a custom ribbon to your SharePoint site](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/add-a-custom-ribbon-to-your-sharepoint-site#feedback)
* Content Source: [docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unclear... what do you mean by _"except the Pages such as the Home.aspx"_? Can you provide more context?
