### ISSUE TITLE
isGroupNameHidden excluded from this release type

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-docs#4294]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I want to create a web part property pane with a header and hyperlink, similar to the out-of-the-box **Highlighted content** web part.

![Header sample](https://user-images.githubusercontent.com/13972467/61229989-2fc3ba00-a6f7-11e9-8a24-576f2dec5739.png)

After looking at the rendered HTML, I have found the web part doesn't use the `header.description` attribute. Instead, it defines the property pane page as `displayGroupsAsAccordion` set to `true`, and creates a property pane group to display a property pane label and link -- the first group in the array. The first group sets `isGroupNameHidden` to `true` to hide the group name -- which is why the first group looks like a property pane header rather than a property pane group with an accordion.

I should be able to set `isGroupNameHidden` to `true` on my property pane groups.

#### Observed Behavior

The `isGroupNameHidden` is not defined in the `IPropertyPaneGroup` interface. 

When I look at the module, I noticed that the `@microsoft/sp-property-pane` the code says:

```Typescript
/* Excluded from this release type: isGroupNameHidden */
```

What release type(s) allows us to define `isGroupNameHidden`?

#### Steps to Reproduce

1. Create an SPFx web part using the 1.8.2 Yeoman generator.
2. In your web part's `getPropertyPaneConfiguration`, add `isGroupNameHidden:true` to the first property pane group.
3. You'll get an error.
4. Navigate to the definition of `IPropertyPaneGroup` interface, through `IPropertyPaneConfiguration` > `IPropertyPanePage` > `IPropertyPaneGroup`
5. Find the following line, just below the `groupName` prop:
```Typescript
/* Excluded from this release type: isGroupNameHidden */
```

My `package.json` `dependencies` section:
```JSON
 "dependencies": {
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-lodash-subset": "1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "1.8.2",
    "@microsoft/sp-property-pane": "1.8.2",
    "@microsoft/sp-webpart-base": "1.8.2",
    "@pnp/spfx-property-controls": "^1.15.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.7.22",
    "@types/react-dom": "16.8.0",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "6.143.0",
    "react": "16.7.0",
    "react-dom": "16.7.0"
  },
```

I would like to believe that third-party SPFx developers have access to the same tools than first-party developers. I assume that `isGroupNameHidden` will be available in an upcoming version of SPFx. I've also tried using the `--plusbeta` flag to see if that's what I was missing.

Any help is greatly appreciated!

**Comment by AJIXuMuK** [comment]
fixed in 1.14 beta
