### ISSUE TITLE
Update branding doc to indicate page is focused on classic mode

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#4295]
This entire section (Branding and Site Provisioning Solutions" should probably be re-titled and noted that this is all for classic.  Need to add a new section related to branding in Modern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28dce46b-a552-800a-621a-efcd6ee41d4e
* Version Independent ID: ea865148-7860-c247-6ae5-454ddb9c60c6
* Content: [Branding and site provisioning solutions for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Appreciate the comment, but it's not correct. There is a lot of stuff within this section that applies to both classic & modern and where things differ, they are called out.
