### ISSUE TITLE
Shouldn't be recommending Access Applications

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#4296]
These are now deprecated as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bcc3b9-9289-3d66-8c9c-c161e293a569
* Version Independent ID: 3198056e-6ee0-8e2d-2dbe-6f4e1d2eef87
* Content: [Migrate InfoPath forms to SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-infopath-forms-to-sharepoint)
* Content Source: [docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... easy one to submit as a community contribution... ;)

**Comment by nanddeepn** [comment]
Created PR https://github.com/SharePoint/sp-dev-docs/pull/4333 for this fix
