### ISSUE TITLE
SPFx gulp serve issue in workbench.html 

### ISSUE THREAD

**Issue by dimportfolio** [SharePoint/sp-dev-docs#4297]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Desired behavior is to open up workbench and see the hello world application

#### Observed Behavior

Observed behavior is it runs into 

#### Steps to Reproduce

I followed the documentation on setting up a development environment and proceeded to the hello world application. 

#### Additional information

I have attached the requested console output of running GULP trust-dev-cert && serve. Please let me know if you're able to view the output & if it is what you need.

https://imgur.com/a/KVDHomA

Steps I took to remedy the issue but failed:

I attempted to follow the troubleshooting steps from the Microsoft documentation but I don't believe it applies to my situation. The NODE version I am running is 10.16. I am using 0365 and followed the steps of setting up the Office 365 tenant & Development Environment.

_Troubleshooting
SPFx Development for SharePoint Server 2016
SharePoint Server 2016 uses the SharePoint Framework (SPFx) v1.1. Around this the time of the v1.1 release, NodeJS was transitioning from NodeJS v6.x to v8.x. In this update, NodeJS introduced a change where the default changed from HTTP1 to HTTP2. For some, this caused issues with SPFx. A later version of SPFx resolved these issues, but those who are still working with SPFx v1.1 (such as those working with SharePoint Server 2016) may run into issues.

To resolve this, set the following environment variable to instruct NodeJS to use HTTP1 instead of the default HTTP2: NODE_NO_HTTP2=1.

For more information, refer to issue #1002.

Unable to Trust the Self-signed Development Certificate
In some cases, executing the command gulp trust-dev-cert, does not have the desired effect of trusting the self-signed development certificate on your machine. In rare cases such as these, you may need to delete a hidden folder that's generated in your profile folder. Locate & delete the folder /.gcb-serve-data and then try to trust the self-signed development certificate again._

**Comment by andrewconnell** [comment]
Please elaborate on this this:

> ### Observed Behavior
> Observed behavior is it runs into

What exactly is / is not happening. Please provide screenshots, error messages, etc. 

Also please provide context... SPFx version installed, browser tested, etc.

**Comment by dimportfolio** [comment]
When I run "gulp serve", I expect the workbench on sharepoint to run on my chrome browser. I'm not sure what SPFx version is installed. Everything I've done up to this point is the following

Getting Started:
Created an app catalog site
Created an developer site collection
Created a team site
- This was all done in the office 365 SharePoint Admin Center-

Set up Development Environment
Installed NodeJS LTS v10.16
Installed Visual Studio Code
Installed Yeoman & Gulp
Installed Yeoman SharePoint Generator

Then I proceeded to create our first client side webpart

**Comment by andrewconnell** [comment]
Need versions... please run `npm list -g --depth=0`.

@dimportfolio said:
> When I run "gulp serve", I expect the workbench on sharepoint to run on my chrome browser. 

But what is happening... what do you see when you run **gulp serve**? Errors/no errors in the console, nothing in the browser, etc? Provide details on what is happening... you say you expect the above to happen, as do I... but if it isn't, what _is_ happening.

**Comment by dimportfolio** [comment]
@microsoft/generator-sharepoint@1.8.2
gulp@4.0.2
yo@3.1.0

there is no errors in my console, also gulp serve seems to run fine. I've attached an imgur in the initial post that has a image of what the gulp serve outputs.

I also attached here an imgur of the browser page.

https://imgur.com/a/LpV4Jtt

**Comment by DaveHaasPowderSoftware** [comment]
I tried to get Node LTS 10.16 to go as well. No dice. I kept getting the SSL error (referenced in the above imgur url).

Setting the environment variable NODE_NO_HTTP2=1 did nothing to alleviate the problem.
Toasting the c:\Users\$me\.gcb-serve-data folder and running gulp trust-dev-cert did nothing either.
 
I had to go back to Node 8.16 to get it to work.

**Comment by andrewconnell** [comment]
@DaveHaasPowderSoftware Node.js 10.* should work with SPFx v1.8.x... what version are you running?

@dimportfolio In the past, when all else failed I suggest uninstalling Node completely, reboot, verify it's not installed (_by running `node -v` & `npm list -g --depth=0`... both should fail... if not, you haven't uninstalled everything_), and try installing everything again & re-trusting the cert from an administrative command prompt.
