### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#4298]
Would be good to add a reference to the install instructions for the page transformation solution.  Only the UI has a guide...but for modernizing publishing pages, we wouldn't be using the UI part of the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c9c192-eb6e-5c54-f03f-7f66d43f92e6
* Version Independent ID: 328da4aa-fa66-0491-6a8d-94189f14e060
* Content: [Transform classic pages to modern client-side pages](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages#feedback)
* Content Source: [docs/transform/modernize-userinterface-site-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@jansenbe Would there be a good point to point people to per this request?

**Comment by jansenbe** [comment]
@danmyhre: by now you've found the git repo for asking questions and logging issues (https://github.com/SharePoint/sp-dev-modernization/issues). When it comes to publishing portal transformation there's a section in the https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell page + the page layout mapping model is explained in https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing. If things don't work as expected please create an issue in our issue list
