### ISSUE TITLE
Apply retention label

### ISSUE THREAD

**Issue by jashwanthreddyn** [SharePoint/sp-dev-docs#4299]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Hi - We have to started to see 'Apply retention label' field in pages/document libraries in all Sites in prod tenant. And we're not seeing this on other tenants. Can you please let me know if there has been any recent change related to this ? Also, please suggest if there is a way to disable this ?   

![image](https://user-images.githubusercontent.com/33126513/61242675-5a703b80-a714-11e9-80a7-16ec038ced4d.png)

Thank you for your time !

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
