### ISSUE TITLE
Disabling property pane controls issues

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#43]
Currently there is huge inconsistencies in how the different controls in the property pane works. For instance if you want to **disable** different properties this is my findings.
1. `disabled` can be used on for instance `PropertyPaneToggle` and it is reactive, i.e. it can be connected to other property values. 
2. `PropertyPaneDropdown` has an `isDisabled` property and it is not reactive, and you have to reload the page to toggle the disabled state
3. `PropertyPaneTextField` does not have any disabled possibilities at all to set it to disabled

I'd like to see `disabled` used throughout all property pane controls and the property should be reactive.

**Comment by nickpape-msft** [comment]
@srideshpande @manishgarg1 any updates?

**Comment by srideshpande** [comment]
Dropdown disable/enable feature is now fixed and will be in the next drop. However, we have not yet introduced 'disabled' feature for all controls.

**Comment by patmill** [comment]
I believe this is resolved.  If there are specific gaps, please let us know.
