### ISSUE TITLE
Ionic2 anchor tag with onclick issue.

### ISSUE THREAD

**Issue by srikanth748** [SharePoint/sp-dev-docs#430]
html:
     htm += "<a class='link' href='javascript:void(0)' onclick='viewTeam("+JSON.stringify(obj[i])+")'>";
     htm += "<span class='title'>"+obj[i]['tl_title']+" "+obj[i]['tl_location']+"</span>";
    htm += "</a>";

function:
viewTeam(val){
  console.log("value is"+val);
}

Error in the console:
Uncaught ReferenceError: viewTeam is not defined
    at HTMLAnchorElement.onclick (VM6391 :1)
onclick @ VM6391 :1

/////////////////////////////////////////////
the issue is when i click on the links to execute the function ,it says the viewTeam is not defined .

looking for some help in solving this this issue. thanx

**Comment by chakkaradeep** [comment]
I am not sure we have folks who are familiar with Ionic2. You might get better help posting this at Ionic2 forums.

Thanks!

**Comment by amishra0909** [comment]
@srikanth748 , was your issue resolved? The right place to discuss this will be Ionic2 forums so I am closing this issue now.
