### ISSUE TITLE
 How to add modern webpart in classic page layout?

### ISSUE THREAD

**Issue by MatheusNascimentoAraujo** [SharePoint/sp-dev-docs#4300]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> I need to add a modern webpart made with spfx in the classic page layout, but I do not know if this is possible

**Comment by andrewconnell** [comment]
Yup... supported. Just add it like a normal web part.

**Comment by MatheusNascimentoAraujo** [comment]
The web part modern does not appear in sharepoint designer, in the list of webparts to add

**Comment by andrewconnell** [comment]
SharePoint Designer has no concept of modern web parts... you will see them listed in the browser UX
