### ISSUE TITLE
Broken Link on Readme.md

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4303]
>  Broken Link on [ReadMe File](https://github.com/SharePoint/sp-dev-docs/blob/master/README.md) under Deployment Status.

#### Category
- [ ] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> If the link is broken it should be removed otherwise it should be corrected.

#### Observed Behavior

> [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) repository contains broken on Readme.md file.

#### Steps to Reproduce

[SharePoint Framework reaches general availability—build and deploy engaging web parts today](https://blogs.office.com/2017/02/23/sharepoint-framework-reaches-general-availability-build-and-deploy-engaging-web-parts-today/) link is broken on 
https://github.com/SharePoint/sp-dev-docs/blob/master/README.md

**Comment by andrewconnell** [comment]
Can't repro... it's working for me on two different networks & machines.

**Comment by anomepani** [comment]
![BrokenLink](https://user-images.githubusercontent.com/2988295/61368925-92aa8200-a8ac-11e9-8561-b335de017658.png)
Don't know what is an issue but I am seeing [https://blogs.office.com/2017/02/23/sharepoint-framework-reaches-general-availability-build-and-deploy-engaging-web-parts-today/](https://blogs.office.com/2017/02/23/sharepoint-framework-reaches-general-availability-build-and-deploy-engaging-web-parts-today/) link with attached screenshot.
Thanks

**Comment by andrewconnell** [comment]
Interesting... looks like there's a localization issue with the site. change the locale in the URL to **en-us** and see if that works as it does for me...
