### ISSUE TITLE
Attempting to access Teams Files in SharePoint Gives error

### ISSUE THREAD

**Issue by lieshidden** [SharePoint/sp-dev-docs#4304]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Expected: Click on "View in SharePoint" on Teams would open SharePoint and allow access to Files that I have access to.

#### Observed Behavior

Observed: 
Something went wrong! Failed to execute removeChild on Node. The node to be removed is not  a child of this node.

#### Steps to Reproduce

Open Teams, go to Files in a Team, click on three dots next to a folder, and click open in SharePoint.

![image](https://user-images.githubusercontent.com/4284612/61315960-200ea900-a7bd-11e9-9383-f1c5f237c7dc.png)

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
