### ISSUE TITLE
sp list subscription 1.8.2 - ListSubscriptionFactory - has no exported member

### ISSUE THREAD

**Issue by NWH-SAmin5** [SharePoint/sp-dev-docs#4306]
Installed latest version of @microsoft/sp-list-subscription.  There are no exported members

Not able to find this documented any where - if this version was updated anything or not. Not even on NPM site.

Which is the working version I can use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ade5442-a0dc-e57c-bde0-876396aba7f1
* Version Independent ID: 50aa69e3-8a27-dac1-5c60-1d5309a60a33
* Content: [Subscribe to list notifications](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications)
* Content Source: [docs/spfx/subscribe-to-list-notifications.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/subscribe-to-list-notifications.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The current version is v1.8.2 as it's published along with each version of SPFx. However, I believe this is still a developer preview feature, not one in GA (see the [v1.7.0 release notes here](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.7-release-notes#listsubscriptions-in-the-browser-developer-preview)).

Therefore you need to use the `-plusbeta` flag when installing the package as that includes a different type declaration file that exposes the objects.

IOW, use:

```shell
npm install @microsoft/sp-list-subscription@1.8.2-plusbeta
```

... until this ships as a GA feature. At that time you won't need to use the specific version flags.

I'll update the docs to make this more clear.

**Comment by NWH-SAmin5** [comment]
@andrewconnell Got it, thanks, appreciate it!
