### ISSUE TITLE
Simple Standalone BatchUtils for SharePoint Online

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4308]
>I have created small [BatchUtils ](https://github.com/anomepani/sp-rest-util/blob/master/BatchUtils.ts) which might be helpful to add as reference code or example for SharePoint Batch API on Batch API documentation page
> Usage for BatchUtils and other SharePoint Rest API Sample code also written over [here](https://github.com/anomepani/sp-rest-util/blob/master/Sharepoint-REST-API-Code-Example.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f963c2-441f-8f40-9c2a-3d31f4a79b1f
* Version Independent ID: d4a6f050-b632-a5a0-1814-33699760fccb
* Content: [Make batch requests with the REST APIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis)
* Content Source: [docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks, but as a general rule the docs don't reference 3rd party code / projects that haven't been vetted by Microsoft. However, having this comment on the page will help others find it
