### ISSUE TITLE
single part app pages - Remove webpart Edit Button

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-docs#4309]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question/Issue
I have implemented a SIngle part app page which works great. My webpart has an "Edit" Button in its own Commandbar and I wondered if it was possible to remove the webparts "Edit" button since it may cause confusion with end users because of 2 Edit Buttons. 

![image](https://user-images.githubusercontent.com/2708345/61352727-feb5c780-a865-11e9-98da-ba77543e1b06.png)

Tks,
Gary

**Comment by andrewconnell** [comment]
No... you can't remove OOTB UX elements in a supported way.
