### ISSUE TITLE
Issue with loading SPFx Extensions and webpart

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#4310]
#4122 ## Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

Hi Team,
We are facing Issue with loading SPFx Extensions and SPFx Webpart in SPO modern pages. The issue happens only for the first time when the users logs in after entering their credentials. Later if they try to open on the second/third time, page opens up properly.

During the first time load, it doesn't even load the SPFx Extensions, and the page gets hanged. If we close this window and open in a new window, the page renders properly now. 
Looks like this is clearly a cache issue, where SPFx expects a cache while loading. 

Please assist us here.

Thanks, Sridhar Sadasivam

**Comment by andrewconnell** [comment]
Can you provide additional details and context to help assist with your issue? Things that always help posting with every issue include:

- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
- If SharePoint Online, is tenant configured for standard / targeted release
- Browser(s) tested
- SPFx version
- If applicable, version of Office UI Fabric React

As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.
