### ISSUE TITLE
There is no mention regarding how to control the image and preview of the full page

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#4313]
When going to add a page on my site, visiting the "apps" tab I can see my SPFx web parts, but they all show up with empty image and the preview shows up an un-configured web part.
Would be useful to let us know how to set the preview image for each web part, as well as a flag in the web part render that tells us to render the web part in preview mode (using sample data perhaps).

Not sure if this is possible today and not documented, or if these are new features...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42d2d41-61bb-e281-3dac-328292b7b192
* Version Independent ID: 05b12512-7aa9-3ac7-e23e-0d5ae2209a59
* Content: [Using single part app pages in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages)
* Content Source: [docs/spfx/web-parts/single-part-app-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/single-part-app-pages.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Believe that's a feature request as the preview shown is a live rendering of the web part.

**Comment by shaipetel** [comment]
Yes, indeed it is.
I have detected in my code that it is running inside that frame and render demo content accordingly. However would be nice if there was a flag I can check instead of relying on checking the frame/container etc.

If there isn't one, I'll open a feature request - but not sure if there is one that isn't documented?

**Comment by andrewconnell** [comment]
That's not an existing feature... no clue if someone has already requested.

**Comment by shaipetel** [comment]
I think this is an excellent example of something that will never get people to vote on it, but why not give it a try.

I added it here:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38256541-allow-spfx-full-page-webparts-to-provide-an-image

Thanks!
