### ISSUE TITLE
'InstallSolution' action in site script fails with Provider Hosted SharePoint Add-in

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#4317]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When applying a site design which contains a site script which contains an "InstallSolution" action with the id of a Provider Hosted SharePoint Add-in deployed in the tenant app catalog, the Add-in should be installed to the current site.

The documentation states that both SP add-ins as SPFx solutions can be installed with this action: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema
 _Use the installSolution action to install a **deployed add-in** or SharePoint Framework solution from the tenant app catalog._

#### Observed Behavior

When applying a site design which contains a site script which contains an "InstallSolution" action with the id of a Provider Hosted SharePoint Add-in deployed in the tenant app catalog, you'll get an error 'Action failed'

![image](https://user-images.githubusercontent.com/28447261/61449373-1750db00-a955-11e9-93be-1e815211e8c0.png)

(tested on the same environment with a SPFx solution, that works fine)

#### Steps to Reproduce

1. Install a Provider Hosted SharePoint add-in to the tenant app catalog
2. Register a Site Script in the tenant with the following content:
```
{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json",
    "actions": [
      {
          "verb": "installSolution",
          "id": "<guid of provider hosted sp add-in from app catalog, retrieved by get-pnpapp command>"
      }
    ],
    "version": 1
}
````
3. Register a new Site Design with the id of the Site Script from step 2 associated
4. Create a new teamsite
5. Apply the Site Design to the newly created teamsite
6. Inspect the outcome

**Comment by advdberg** [comment]
It turns out that there's still no way to automate the deployment of Provider Hosted Add-ins through modern authentication (app-only), it seems that you'll always need a user based context. Hopefully this issue is addressed in the near future while a lot of companies and ISV's have invested heavily on these type of SharePoint extensions. Not being able to deploy them on tenants which have the legacyauth disabled would cause a lot of re-investments on rewriting everything to SPFx. @andrewconnell @VesaJuvonen @waldekmastykarz  what's your opinion on this?

**Comment by advdberg** [comment]
Related issues:
#1501
https://github.com/SharePoint/PnP-Sites-Core/issues/2327

**Comment by lucabandMSFT** [comment]
hey @advdberg , we finally were able to take a look at the issue and we were no able to repro it. Are you still experiencing the issue? Thanks and sorry that it took soo long for us to look at it.
