### ISSUE TITLE
Broken link for MVA

### ISSUE THREAD

**Issue by kamleshrao** [SharePoint/sp-dev-docs#4319]
Under the [See also] link, the [MVA Getting Started with SharePoint Add-Ins] link is pointing to below URL, which does not exist:

https://mva.microsoft.com/en-US/training-courses/getting-started-with-sharepoint-addins-14053

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0afbd41-2b6f-a591-3e06-ca8d5aea802e
* Version Independent ID: b3568699-c9a9-19b7-14a2-b538ec647062
* Content: [SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-add-ins#feedback)
* Content Source: [docs/sp-add-ins/sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Bummer... appears all MVA links now point to MS Learn even if the content hasn't been migrated. Will get this doc updated. Thanks for the report.

**Comment by kamleshrao** [comment]
I checked the original [article](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-add-ins) and found that you have updated the issue in [**See Also**] section.

Thanks @andrewconnell  for updating the documentation.
