### ISSUE TITLE
Javascript File Loading

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#432]
•	The use of require.js – we need the best way to implement this type of functionality
•	Classic SharePoint JS file loading – we require the use of SP.js, etc in our web parts and we need to know from your team the best implementation mechanics for these inclusions.

#### Category
Question

**Comment by suz7777** [comment]
You can either use the ComponentLoader to do this

> import {SPComponentLoader} from '@microsoft/sp-loader';
>               …
> SPComponentLoader.loadScript("MyUrlHere");


Alternatively, you can use path dependencies in the manifest so they don’t need any code and can safely assume the dependencies are loaded.

I’d say the 2nd is a more recommended way, as it’s how we were telling people to use jquery, etc.

**Comment by debajyoti** [comment]
In the recommended approach, can we assume that if these files are loaded from Master page; it will not be reloaded again (multiple http request), even if we require them in webpart and update the config as follows ?
    "jquery": {
      "path": "https://code.jquery.com/jquery-2.1.1.min.js",
      "globalName": "jQuery"
    },
    "simpleWeather": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js",
      "globalName": "jQuery",
      "globalDependencies": [ "jquery" ]
    }
Does the same holds good for 
    "sp-init": {
      "path": "https://CONTOSO.sharepoint.com/_layouts/15/init.js",
     "globalName": "$_global_init"
    },
    "microsoft-ajax": {
      "path": "https://CONTOSO.sharepoint.com/_layouts/15/MicrosoftAjax.js",
      "globalName": "Sys",
      "globalDependencies": [ "sp-init" ] 
    }

**Comment by chakkaradeep** [comment]
To use SP.js, here are the steps. I will compile this into a doc later this week, but until then below are the steps to unblock your team:

Open config.json and add these to the externals:

```json
    "sp-init": {
        "path": "https://your-full-site.sharepoint.com/_layouts/15/init.js",
        "globalName": "$_global_init"
      },
      "microsoft-ajax": {
        "path": "https://your-full-site.sharepoint.com/_layouts/15/MicrosoftAjax.js",
        "globalName": "Sys",
        "globalDependencies": [
          "sp-init"
        ]
      },
      "sp-runtime": {
        "path": "https://your-full-site.sharepoint.com/_layouts/15/SP.Runtime.js",
        "globalName": "SP",
        "globalDependencies": [
          "microsoft-ajax"
        ]
      },
      "sharepoint": {
        "path": "https://digitalbreak.sharepoint.com/sites/samples/_layouts/15/SP.js",
        "globalName": "SP",
        "globalDependencies": [
          "sp-runtime"
        ]
      }
```

Now install the types:

```
npm i --save-dev @types/microsoft-ajax
npm i --save-dev @types/sharepoint
```

Update `tsconfig.json` to include the types under the `types` json property just below `webpack-env` like this:

```json
"types": [
      "webpack-env",
      "microsoft-ajax",
      "sharepoint"
    ]
```

In your code, use `require` to load the SP.JS and its dependencies:

```
require('sp-init');
require('microsoft-ajax');
require('sp-runtime');
require('sharepoint');
```

Now you can write code to interact with JSOM. Below is an example:

```typescript
private siteUrl: string = '/sites/samples';
private collListItem:SP.ListItemCollection;

public render(): void {
    const spClientContext: SP.ClientContext = new SP.ClientContext(this.siteUrl);
    const oList: SP.List = spClientContext.get_web().get_lists().getByTitle("Announcements");

    const camlQuery = new SP.CamlQuery();
    camlQuery.set_viewXml('<View><Query><Where><Geq><FieldRef Name=\'ID\'/>' + '<Value Type=\'Number\'>1</Value></Geq></Where></Query><RowLimit>10</RowLimit></View>');
    this.collListItem = oList.getItems(camlQuery);

    spClientContext.load(this.collListItem);

    spClientContext.executeQueryAsync(this.onQuerySucceeded, this.onQueryFailed);
  }

  private onQuerySucceeded = (sender:any, args:SP.ClientRequestSucceededEventArgs) => {
    const listItemEnumerator = this.collListItem.getEnumerator();

    while(listItemEnumerator.moveNext()){
      const listItem = listItemEnumerator.get_current();
      alert(listItem.get_item('Title'));
    }
  }

  private onQueryFailed = (sender, args:SP.ClientRequestFailedEventArgs) => {
    alert('Request failed. ' + args.get_message() + '\n' + args.get_stackTrace());
  }
```

**Comment by frankchen76** [comment]
@chakkaradeep , as I asked the same question in [#319](https://github.com/SharePoint/sp-dev-docs/issues/319), is there a way to use sp.js relative url instead of hard coding the sp.js full url in the config.json? It makes sense to not bind your client web part with specific SPO site when you deploy it to different tenants. @waldekmastykarz actually mentioned an great approach to load sp.js via `ModuleLoader.loadScript` which is good at this moment. But I am curious if there is a better way to do that from long term perspective. Thanks

**Comment by patmill** [comment]
Sorry for the delay.  So it looks like currently the file may be requested twice (although the second time it will be cached).  Once from an embedded script, and once from the request.  @iclanton - Is this expected?  Anything we can do to sort it out?

@debajyoti - Is it possible for you to look for something on the page (like a global name or something) and request it if it is not present?

**Comment by debajyoti** [comment]
@patmill - Currently we are checking if those script files are loaded or not in our webparts. so We can do it that way.

Q: But in that case, if we use the above approach (keeping external files in config), not sure where should we keep the 'file loading condition'.

**Comment by suz7777** [comment]
we have modified our code as described above and it appears that the js files get loaded only once for all web parts... however, since our master page loads the javascript files, we are still seeing double loading.. suggestions on a workaround?

**Comment by suz7777** [comment]
In chrome we are seeing the following issue:

If we load init.js, SP.JS, and SP.Runtime.JS inside our web parts using the config.json suggestion - the OOB search web part will not behave as expected.  The search box placeholder text does not 'remove' when a user clicks inside the box.

The user must manually remove the text and then click the search icon for the function to work.

**Comment by patmill** [comment]
Hi @suz7777  I believe you mentioned that you couldn't get your webparts to access the globally loaded js (like SP.ClientContext)

I tried the following code, and it seemed to work. Have you tried something like this (apologies for the hackiness)?

var SP:any = window['SP'];
if ( SP )
{
let spContext = new SP.ClientContext();
}

**Comment by suz7777** [comment]
this works - thanks for the help!
we created a global function
in onInit i do:

this.GlobalMethods.getJSDependencies().then(() => {
      return super.onInit();
    });
in global function library i do

public getJSDependencies(): Promise<any> {
        var logFunctionName = "getJSDependencies";
        var isLoadingComplete = [];

        //jquery loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for jQuery");
        if (!window['jQuery']) {
            this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery");
            isLoadingComplete.push(SPComponentLoader.loadScript(globals.mmmGoJQueryDir, { globalExportsName: 'jQuery' }).then(() =>
                SPComponentLoader.loadScript(globals.mmmGoSwipeJs, { globalExportsName: 'jQuery' }).then(() => 
                SPComponentLoader.loadScript(globals.mmmGoPluginsDir, { globalExportsName: 'jQuery' }).then((jq: any): void => {
                    jq = jq;
                    jq = window['jQuery'];
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoJQueryDir + ") - succeeded");
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoPluginsDir + ") - succeeded");
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoSwipeJs + ") - succeeded");
                }))));
        }

        //cacheManager loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for cacheManager");
        if (!window['cacheManager']) {
            isLoadingComplete.push(SPComponentLoader.loadScript(globals.mmmGoCacheMgrDir, { globalExportsName: 'cacheManager' }).then((cacheManager: any): void => {
                cacheManager = cacheManager;
                cacheManager = window['cacheManager'];
                this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: cacheManager (" + globals.mmmGoCacheMgrDir + ")loading completed");
            }));
        }

        //cacheManager loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for classic SP");
        if (!window['SP']) {
            isLoadingComplete.push(SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/init.js', { globalExportsName: '$_global_init' }).then(() =>
                SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/MicrosoftAjax.js', { globalExportsName: 'Sys' }).then(() =>
                   SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.Runtime.js', { globalExportsName: 'SP' }).then(() =>
                    SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.js', { globalExportsName: 'SP' }).then(() =>
                            SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.taxonomy.js', { globalExportsName: 'SP' }).then((SP) => SP))))));
            this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: SP loading completed");
        }

        return Promise.all(isLoadingComplete);
    }
now in front of all SP, jQuery, etc
var context = new (window as any).SP.ClientContext.get_current();
