### ISSUE TITLE
Cannot re-sync after app updated

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#4322]
Build an SPFx app, followed these steps - all good.
Made some changes, new icon, added features.
Deleted the app from the app catalog, added the new app package.
"Sync to teams" gives a conflict error.
Went to teams - clicked "manage team"=&gt;"apps", deleted my SPFx app.
-- this took hours, during which time the entire team wasn't accessible. giving various errors...
Now, finally the SPFx is gone. but:
1. I can still see it in teams with old icon when trying to add a tab.
2. Sync to teams from the app catalog still gives a conflict error.

I'm in limbo now, can't do anything about it...
Could you please describe the steps to redeploy new versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shaipetel** [comment]
Found the issue, perhaps update this article.
You must go to add tab -> more apps, find the app there and either delete it from there or update it.
Now it all works.
Still - some operations take hours to update.

**Comment by andrewconnell** [comment]
Good suggestion... care you submit changes to the article as a PR to help others on updating Teams apps?

**Comment by shaipetel** [comment]
Thanks @andrewconnell I can definitely add that content, however following my workaround allows me to install the new version but removed any tabs that were created using that app.
I'm not sure how happy people will be with that side effect in a production environment, so I think a better approach will be needed to share on the article.

Would you agree?

Otherwise, I can suggest this content to be added to the article, if you think it is appropriate:

## Updating your app package

When you make changes to your app and create a new package, you might encounter an error when clicking "sync to teams".

A notification "Failed to sync solution to teams" might appear on the top right of your page.

If this happens follow these steps to delete your app from Microsoft Teams and then try to sync it again:

1. Open Microsoft Teams
1. When viewing your team channel, click + to "Add a tab"
1. Click the "More apps" link at the top
1. Find your app in the list, and click on the "..." menu
1. Click "Delete" to remove the app from Microsoft Teams

You should now be able to sync your new version to Microsoft Teams.

**Comment by gswdn** [comment]
Yes, I also think it's annoying for users to remove the app to sync it again.
But for me, it wasn't necessary to sync the app again after making some changes for the SPFx Webpart. Redeploying the SPFx solutions also updated the app in Teams.
I guess, re-syncing is only needed, if something changes in the manifest file.
In a production scenario, I'm going to create the manifest manually anyway to have more control. And then, it's also easy to just create a new ZIP file and updating the app by uploading in Teams. I assume, removing then is not needed.

**Comment by andrewconnell** [comment]
@shaipetel Best to submit in a PR... MSFT can review & we can address it there.

**Comment by VesaJuvonen** [comment]
This behavior has been changed as we cannot demand the existing solution to get deleted - since it would remove all existing instances. Sync to teams will currently override the auto-generated app registration in Teams side to ensure working model also with updates.

As issue is no longer relevant, closing as resolved.
