### ISSUE TITLE
SPO Workbench.aspx and Deployed Webpart Styling differently

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-docs#4324]
#### Category
- [x ] Question

### Question
How do I figure out what is being loaded for my css. I have a hunch that some npm packages locally on my machine may be getting loaded but in production they are not. 
It would be helpful if I could examine whats be loaded from localhost and whats being loaded from production and compare. How do I do this?

#### Version
1.8.2

#### Expected or Desired Behavior
During my development I use the SPO workbench to test my work, however when I deploy my webpart to the site (same tenant) I get different rendering (css looks broken).
Expected rendering to be the same.

#### Observed Behavior
Rendering different styling. 

#### Steps to Reproduce
Build webpart and test in live workbench.aspx. Deploy to same tenant site.

**Comment by andrewconnell** [comment]
@StfBauer, do you have insight / suggestions for @gbminnock?

**Comment by StfBauer** [comment]
@gbminnock Do you use the local workbench for your development? You also mentioned that you load CSS from local npm packages? Are those SASS or regular CSS files. Can you provide some sample on how you embedded the style sheets? 

This would be really helpful.

I might be that your embedded style sheets load not via a SASS import and just uses CSS imports.
