### ISSUE TITLE
SPFX to teams Issue : failed to sync solution to teams

### ISSUE THREAD

**Issue by DeepikaEvuri** [SharePoint/sp-dev-docs#4325]
Hi,
 We are facing an issue in deploying the sharepoint framework webpart to teams. After deploying the solution to app catalog and clicking on the "Sync to teams" we are facing "**failed to sync solution to teams**" error and in console we are getting 400 response code.
![image](https://user-images.githubusercontent.com/46048680/61516377-79c3dd00-aa22-11e9-8298-261017b7bab5.png)
Any help/Suggestions ?

**Comment by narulasrinivas** [comment]
@DeepikaEvuri  - Did you find the solution to this issue?

**Comment by SujiJohn** [comment]
Go to Microsoft 365 Admin center by selecting Admin and enable "Allow sideloading of external apps" like the below:

![Enable-SideLoading](https://user-images.githubusercontent.com/20598968/65628718-00a3b180-dfa0-11e9-8c12-7518677b1170.png)

**Comment by muradhaider5** [comment]
you should find and remove it by opening Teams -> Apps -> Built for [tenantname]. After removing it here, you should be able to successfully sync the app once.
