### ISSUE TITLE
Dynamically populated list ignoring selectedKey

### ISSUE THREAD

**Issue by michaelppaye** [SharePoint/sp-dev-docs#433]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
We have a dynamically populated list, this works as expected in terms of population and persisting the property key (we can retrieve the value for the property successfully). We would expect the dropdown to pre-select the current option from the dropdown list (assuming that it exists).

#### Observed Behavior
After a reload the dropdown list displays as if no option has been selected (though, interestingly - if you change another property it doesn't clear the option)

#### Steps to Reproduce
Code for the dynamic population:

`if(!this.termsetsFetched) {
        this.termsetOptions = new Array<IPropertyPaneDropdownOption>();

        this.getTermsets().then((options) => {        
          this.termsetsFetched = true;
          this.onDispose();
        });
    }

And the dropdown creation:

     PropertyPaneDropdown('filterTermsetId1', {
              label: strings.FilterTermsetLabel,
              options: this.termsetOptions,
              selectedKey: this.properties['filterTermsetId1']
            })`

**Comment by patmill** [comment]
Hi @michaelppaye - you are correct - and that is a bug.  I need to track down the bug to dupe it.  It basically takes the current property value as a default.  So, if you are binding the dropdown to a property - for now - I would set the this.properties.filterTermsetId1 to be the value that you want it to default to.

**Comment by michaelppaye** [comment]
Hi @patmill - great, thanks.

Two other things that I've now noticed:

1) If I add an alert for the property just above the return of the config, then the small delay that it adds by me having to click ok ensures that the dropdown item is selected.
2) If I hit F5, then open the property dialog the item will always not be selected, if I then close the dialog and re-open it the dropdown item is always selected

I think the dropdown is just not choosing the selected item when onDispose is called, so it only pre-selects if the data for the dropdown is already available.

**Comment by kmartindale** [comment]
Any updates to this issue? Also noticing the same problem. Thanks!

**Comment by patmill** [comment]
This should have been fixed a while ago. Sorry for not updating.
