### ISSUE TITLE
"Update onInit in PnPjsExampleWebPart.ts" text doesn't match code

### ISSUE THREAD

**Issue by timdw** [SharePoint/sp-dev-docs#4335]
Under [Install and set up @pnp/sp](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts#install-and-set-up-) the text states: 
> In the `onInit` method, update the code to appear as follows. Add the block after the `super.onInit()` call. We do this after the `super.onInit` to ensure that the framework has a chance to initialize anything required, and that we are setting up the library after those steps are completed.

but I don't think it matches with the layout or the functionality of the code shown.

I haven't tested it but would this be better?

```typescript
/**
* Initialize the web part.
*/
protected onInit(): Promise<void> {
    return super.onInit()
      .then(() => {
        this._id = _instance++;

        const tagName: string = `ComponentElement-${this._id}`;
        this._componentElement = this._createComponentElement(tagName);
        this._registerComponent(tagName);

        // When web part description is changed, notify view model to update.
        this._koDescription.subscribe((newValue: string) => {
          this._shouter.notifySubscribers(newValue, 'description');
        });

        const bindings: IPnPjsExampleBindingContext = {
          description: this.properties.description,
          shouter: this._shouter
        };

        ko.applyBindings(bindings, this._componentElement);

        sp.setup({
          spfxContext: this.context
        });

        // optional, we are setting up the @pnp/logging for debugging
        Logger.activeLogLevel = LogLevel.Info;
        Logger.subscribe(new ConsoleListener());
      });
  }
 ```

Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

    ID: 4b19eb96-192d-2d8b-8d4e-0de787f22093
    Version Independent ID: e2cbd2b2-8bb7-a95f-0768-15f1b045b4c4
    Content: Use @pnp/sp (PnPJS) library with SharePoint Framework web parts
    Content Source: docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
    Product: sharepoint
    Technology: sharepoint-framework
    GitHub Login: @spdevdocs
    Microsoft Alias: spdevdocs

**Comment by bcameron1231** [comment]
Thanks for the question. Since this is a PnPJs question, I suggest trying to ask the question over in the PnPJs GitHub. https://github.com/pnp/pnpjs/

**Comment by timdw** [comment]
I got an email notification for a reply - was it deleted?

**Comment by andrewconnell** [comment]
@patrick-rodgers ... care to comment on this as it's related to a PNPJS doc?

**Comment by GrahamMcMynn** [comment]
@andrewconnell - we're not tracking this as it looks like it should be in PNP.

**Comment by patmill** [comment]
As mentioned (a long time ago), this is PNP related.
