### ISSUE TITLE
CommandSet Appending  multiple times at list view 

### ISSUE THREAD

**Issue by AnisELTAIEF** [SharePoint/sp-dev-docs#4337]
Command set are added many times as i deselect and i select a list items ; 
here are my configuration (**package.json**):

_{
  "name": "generate-documents",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.6.0",
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-dialog": "1.6.0",
    "@microsoft/sp-listview-extensibility": "1.6.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "15.6.6",
    "@types/webpack-env": "1.13.1",
    "axios": "0.18.0",
    "webfontloader": "^1.6.28"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.6.0",
    "@microsoft/sp-module-interfaces": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-workbench": "1.6.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@types/node": "8.5.8",
    "ajv": "~5.2.2",
    "camljs": "^2.11.0",
    "es5-ext": "^0.10.50",
    "gulp": "~3.9.1",
    "office-ui-fabric-react": "5.83.0",
    "sp-pnp-js": "^3.0.10",
    "tslint-microsoft-contrib": "~5.0.0"
  }
}_

#### Category
- [x] Bug
- [x] SPFx 
- [x] React
- [ ] Question
- [ ] Typo
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
Have you tried using the latest version of SPFx (v1.8.2) as many issues have been resolved since 1.6...

**Comment by Philluxx** [comment]
The same with SPFx v1.8.1. In some site collections the CommandSet is append correctly once. Only in one site collection it is shown multiple times.

**Comment by AnisELTAIEF** [comment]
Thank you @andrewconnell  , as  i mentioned in  description i already use the SPFx version 1.6.
Also @Philluxx has mentioned that he has the same problem with version 1.8.1.
You recommond me to upgrade anyway to latest version ?

**Comment by AnisELTAIEF** [comment]
> Have you tried using the latest version of SPFx (v1.8.2) as many issues have been resolved since 1.6...

Thank you @andrewconnell , as i mentioned in description i already use the SPFx version 1.6.
Also @Philluxx has mentioned that he has the same problem with version 1.8.1.
You recommond me to upgrade anyway to latest version or to latest stable version ?

**Comment by andrewconnell** [comment]
Before we chase down any issues, yes, I'll ask you to upgrade to the latest version. Since you're already on 1.6, that means you're SPO so please upgrade to latest and confirm it's still present.

Further, please see this https://github.com/SharePoint/sp-dev-docs/issues/4374#issuecomment-516815819 for a known issue  ... the fix is currently rolling out (https://github.com/SharePoint/sp-dev-docs/issues/4374#issuecomment-520717740)

**Comment by Philluxx** [comment]
Just tried it with SPFx 1.8.2 and got the same result. Here ist my package.json

`{
  "name": "xxxyyy",
  "version": "1.0.0",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.8.2",
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-dialog": "1.8.2",
    "@microsoft/sp-listview-extensibility": "1.8.2",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "0.7.7",
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}
`

**Comment by Philluxx** [comment]
Just tried it with SPFx 1.9.1. Same result. Just in one site collection

**Comment by AnisELTAIEF** [comment]
> Just tried it with SPFx 1.9.1. Same result. Just in one site collection

Thank you @Philluxx , it work's only in one site collection using SPFx v 1.9.1 ?

**Comment by vegardei** [comment]
Same here. Only working in one site collection, all other get appended buttons. Same problem on two tenants, one of them are on targeted release.

**Comment by andrewconnell** [comment]
I'm not clear what "Just in one site collection" means... 

@vegardei as mentioned above, since the current version of SPFx is v1.9.1 and 1.6 is nearly 12 months old, I'd ask you to please upgrade to latest & test again. Very well could be bugs have been fixed in the last 12mo with as we've had 6 releases since then.

**Comment by andrewconnell** [comment]
For others, can you provide a repro project in a public GH repo? I can't repro this with a new command set project using SPFx v1.9.1 & SPO.

**Comment by vegardei** [comment]
@andrewconnell will give upgrading to 1.9.1 a shot, but it should work with 1.8.2 right? @Philluxx tried upgrading to 1.8.2 but he got the same bug.

**Comment by andrewconnell** [comment]
@vegardei It should but if it's an issue in 1.8.2 but not 1.9.1, then the solution is to upgrade. If not, then it's something else. Process of elimination :)
