### ISSUE TITLE
spfx ListViewCommandSet CommandBar does not show up

### ISSUE THREAD

**Issue by 123Flick123** [SharePoint/sp-dev-docs#4338]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [x] spfx
- [ ] Additional article idea

#### Bug behaivor

If I want to host my spfx ListViewCommandSet at localhost with "gulp serve" I got following issue. Everything works fine - no errors, but after clicking "Load Debug Scripts" nothing happend. No custom CommandBar Items will appear. 

Ironically, if I type something in the SharePoint List Search Bar, the Custom CommandBar will appear... 

I used this MS Demo: https://docs.microsoft.com/de-de/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

After clicking "Load Debug Scripts":
![image](https://user-images.githubusercontent.com/39533303/61645043-1f3ab300-aca6-11e9-8b71-5468ee5c9738.png)

After typing something in the searchbar:
![image](https://user-images.githubusercontent.com/39533303/61645142-514c1500-aca6-11e9-9f16-29383b4195d8.png)

I hope you can help me to fix this, that I can also use my Custom List Actions in the normal list view.. 

Thanks!

**Comment by kcasamento** [comment]
Same exact issue here.  Would love to get an update as this is blocking active development work.

**Comment by jonesron** [comment]
I'm having the same issue with the field customizer and the CommandBar.  I've gone through the docs for all three extensions to make sure it wasn't something I was doing.  

The Application Customizer however is still loading correctly and displaying the pop-up.  When I put break points on OnInit() in the developer tools, the Application Customizer hits them correctly.  The other two never stop on the break points.

Please let me know if there are any logs or screenshots that would help.

**Comment by barisbikmaz** [comment]
I have the same issue now with my tenant which is updated later since today. In my dev tenant this didn't work before. I think its the same issue as [https://github.com/SharePoint/sp-dev-docs/issues/3705#issuecomment-510615099](url)

**Comment by jonesron** [comment]
@barisbikmaz Thanks, it does look like the same issue.  I'll keep an eye on that one.

It looks like some in the page and not with the extensions.  I tried the same test as @123Flick123 did with the field extension.  The script didn't show up till I searched for the item.

![field-extension-debug](https://user-images.githubusercontent.com/7633261/61712104-92ced580-ad23-11e9-9cb3-c27350f92152.png)

The search also hit the breakpoints.

**Comment by 123Flick123** [comment]
> @barisbikmaz Thanks, it does look like the same issue. I'll keep an eye on that one.
> 
> It looks like some in the page and not with the extensions. I tried the same test as @123Flick123 did with the field extension. The script didn't show up till I searched for the item.
> 
> ![field-extension-debug](https://user-images.githubusercontent.com/7633261/61712104-92ced580-ad23-11e9-9cb3-c27350f92152.png)
> 
> The search also hit the breakpoints.

Hi @jonesron,

Thanks for testing! I did some researches today. Somebody wrote it's an issue of version 1.8.2 of spfx. I don't know if it's possible but maybe we can downgrade our version to 1.8.1 or lower. I will try ittomorrow. If somebody has downgraded their version someonce, please reach out to me.

**Comment by jonesron** [comment]
Well, I downgraded to 1.8.1 and upgraded to 1.9.0.  Neither worked.  The results were exactly the same as the ones described above.

**Comment by JonathanJourdan** [comment]
Same problem here since 15 days in local gulp serve command... !
After clicking "Load Debug Scripts" nothing happend. No custom CommandBar Items will appear, no log and breakpoint work.
I don't know if is the same problem... but i think it's the same issue as https://github.com/SharePoint/sp-dev-docs/issues/4219

**Comment by frnk01** [comment]
Same issue. Command sets do not work when running gulp serve.

**Comment by stwel** [comment]
I also experience this issue, but works fine when deployed. 🔥🧯 hotfix needed because this is blocking active development.

**Comment by barisbikmaz** [comment]
There is a "non-dev-friendly" workaround:

- gulp bundle
- gulp package-solution
- deploy created package to SharePoint app catalog
- gulp serve --nobrowser

Then you can debug the code as it comes from the localhost. But you need to rebuild the whole stuff if you want to change sth in the code.

**Comment by JonathanJourdan** [comment]
Guys here a workaround by @jackPoz it's work for me ! :)
https://github.com/SharePoint/sp-dev-docs/issues/4374#issuecomment-516815819

**Comment by jonesron** [comment]
Thanks @JonathanJourdan  (and @jackpoz).  Tested it out and changing it to _&loadSpfx=true_ worked for me.

Due to my lack of understanding of gulp, when I change it to _&loadSpfx=true_  and tried @123Flick123 test with the item search, the 'value' text was still on the item.  Shouldn't that not work now?  Not a big deal, but just wondering.

Thanks for everyone's help.

**Comment by 123Flick123** [comment]
Thank you very much! This workaround is also working for me!

**Comment by 123Flick123** [comment]
Now it's working also with SPFX in big case! Thanks for fixing the Bug!

**Comment by jonesron** [comment]
@123Flick123 I just tried as it as well following the office dev instructions and it worked exactly as it's laid out in the instructions.  

Thanks to the team for resolving this issue.
