### ISSUE TITLE
All of sudden gulp command not recognizing

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#4340]
I made windows update on this Sunday. From that point, I am not able to execute gulp commands. I am not sure if there is any relation between windows update and gulp command. I am getting below error.
![image](https://user-images.githubusercontent.com/7568187/61656808-2d58f580-acdf-11e9-9415-a0f15a07d57f.png)
I have installed gulp again by `npm install gulp -g`. I have restarted my machine and tried. But still same issue.

**Comment by andrewconnell** [comment]
Need more context... where are you running this, what version do you have installed (`npm list -g --depth=0`), are you running this within a SPFx project where you've installed all dependencies?

If so, try deleting the **node_modules** folder in the project and re-installing all dependencies (`npm install`)

**Comment by ymihir** [comment]
I have tried to delete the node_modules folder and added back with `npm install` command. But no use.
Below is the list with `npm list -g --depth=0`
![image](https://user-images.githubusercontent.com/7568187/62128294-bda3c580-b2f1-11e9-87cb-3cf2c6dab71c.png)

**Comment by andrewconnell** [comment]
This is an old issue... can you please ensure you have installed the latest version of SPFx and try again.
