### ISSUE TITLE
Allow PropertyPaneButton to validate & show errors on other properties

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#435]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I'd like to have a few properties, drop down and text fields.
for example: SiteUrl(text), ListName(text), ViewName(text)
and to be able to validate them in one go, using one PropertyPaneButton
So that clicking the button will get the values of these properties, validate them, and show errors next to the right field: if the site could not be contacted - set the error next to that text box.
If the list doesn't exist on that site - set the error next to that text box. etc...

#### Observed Behavior
Assuming your text properties configured with onGetErrorMessage to return a string variable, I can set the error string variable to contain the error message.
But: the property pane will not refresh its UI and will not show the error message until the value of that text box is changed (either user type inside, or I change the property value by code).

I would like to have some API to trigger this update without changing the user entered data, something like "RefreshPropertyPane()"

This is important since IRL validation often will require to validate a bunch of values together. If it is a lengthy process you would want to do it on a button click and not on live change.

**Comment by shaipetel** [comment]
I've come up with a somewhat ugly solution that works really well.

I changed my onGetErrorMessage to return a promise.

Each time onGetErrorMessage  is being called - I reject the previous promise and create a new one.

I never resolve it.

In the button click, if the field is valid I resolve the promise with empty string.
If it is invalid I resolve it with an error message.

This seems to work well, can anyone comment if this is a good practice?

I noticed documentation on onGetErrorMessage for promise is wrong, since it suggests for valid values we should reject. I noticed I have to resolve with empty string in order to get the column validated.

Still it seems very counter intuitive vs. just being able to flag the error message directly.

**Comment by patmill** [comment]
@srideshpande - can you comment?

**Comment by srideshpande** [comment]
@shaipetel - Today we support **validation only on Textfield control** and we **do not** support validating multiple controls validation at one go. As far as I understood your situation, whatever you are doing is fine considering what we have exposed.

As far as the comments are considered - This is what they mean:
```
if onGetErrorMessage returns a string then
      if the string is empty then the validation is considered to be successful
      else then the non-empty string is used as an error message 
else if onGetErrorMessage returns a Promise then 
      if the promise is resolved
            to an empty string then validation is considered to be successful
            or
            to a non-empty string then it is displayed as an error message
      else if the promise is rejected then it's a NO-OP
```
We will update the comments to make them more readable in the future releases.

Please let me know if you still have any questions in this regard.

**Comment by srideshpande** [comment]
As said earlier, we have added validation on text field for `onblur` and `onfocus` cases. Here are the associated properties in the `IPropertyPaneTextFieldProps` api:

```sh
- validateOnFocusIn?: boolean

- validateOnFocusOut?: boolean
```

I am closing the comment now. Please feel free to re-open it if required.

Thanks!
