### ISSUE TITLE
Error "Could not save the list changes to the server" via Sharepoint Designer 2013

### ISSUE THREAD

**Issue by wanq-pg** [SharePoint/sp-dev-docs#4351]
Hi, I have an issue for today which is unable to save my new custom form in Sharepoint Designer 2013. 
Error "Could not save the list changes to the server"

Previously I'm able to create and save and got this issue starting today. Tried remove my SP Designer 2013 and reinstall, but same error occur. Need help. 
![sharepoint save error](https://user-images.githubusercontent.com/53242087/61756470-b0b53c80-adee-11e9-811e-1dc7d548916a.PNG)

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
