### ISSUE TITLE
Usage with SharePoint 2019

### ISSUE THREAD

**Issue by lafe** [SharePoint/sp-dev-docs#4354]
The article is missing a description on how to achieve the same functionality with an on premises SharePoint 2019 that uses Azure Active Directory for authentication. The `AadHttpClient` is not available in the SPFx version for SharePoint 2019 and there seems to be no reliable way as an SPFx web part to authenticate against Azure AD without prompting the users for credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thanks for the comment. If you look closely at the documentation you linked, there is a section in purple that has a description on how to achieve the similar functionality.

The documentation specifies what you can do if you are using a version of SPFx earlier than 1.4.1 (shipped with AadHttpClient).

![image](https://user-images.githubusercontent.com/7944457/61797941-a3e01b00-ade5-11e9-9d17-844e227f14ab.png)

**Comment by lafe** [comment]
@bcameron1231 Unfortunately, that is not a real solution, as it does not offer the same functionality as the `AadHttpClient` and has severe drawbacks (additional pop-ups, registration of additional redirect URLs, etc.).

**Comment by bcameron1231** [comment]
@lafe  Understand you feel that way. It is a real solution, unfortunately it's just not an ideal solution... one of the side effects of working in older versions of a framework.

There have been techniques used in the Adaljs library for silent authentication using a hidden Iframe, I suggest taking a look and seeing if you can implement that.
