### ISSUE TITLE
Set-ComplianceTag has incorrect number of arguments in the docs

### ISSUE THREAD

**Issue by westerdaled** [SharePoint/sp-dev-docs#4356]
#### Category
- [ ] Question
- [X] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Firstly, I am not sure on which  documentation ( product) I , meant to raise this issue: on ak.ms/spdev-docs or  https://github.com/MicrosoftDocs/office-docs-powershell/issues/new.
Happy to delete and recreate as needed. 

ok in the docs [ListItem.SetComplianceTag ](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt827769(v%3Doffice.15))method refers to 
```
public void SetComplianceTag(
    string complianceTag,
    bool isTagPolicyHold,
    bool isTagPolicyRecord,
    bool isEventBasedTag
)
```

#### Observed Behavior

```
 $fileItem.SetComplianceTag("Retention 4 years", $false, $false,$false)

Cannot find an overload for "SetComplianceTag" and the argument count: "4".
At line:1 char:1
+ $f.SetComplianceTag("Retention 4 years", $false, $false,$false)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

```
#### Steps to Reproduce

```
$filename = "Daniel's P45 if he can't fix this issue.docx"
 $query = "<View Scope='RecursiveAll'><Query><Where><Eq><FieldRef Name='FileLeafRef'/><Value Type='File'>$filename</Value></Eq></Where></Query></View>"
            $fileItem = Get-PnPListItem -List Documents -Query $query

```
Instead, I had guess the last parameter - could somebody let me know what it is?
```
$fileItem.SetComplianceTag("Retention 4 years", $isPolicyHold, $isPolicyRecord, $isEventBasedTag,$false)
$fileItem.Update()
```
#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
I'm not clear... is the issue witih a PowerShell cmdlet, server side API, or... ?

**Comment by westerdaled** [comment]
Good question AC as the docs refer to C# .  I am working with PS  But assumed the underlying API is written in C# . Also, there doesn't appear much docs on using the compliance methods in PS.

**Comment by andrewconnell** [comment]
This repo is for dev issues, so I'm not surprised about the lack of PowerShell stuff. But the docs you reference in your OP refer to the CSOM docs but in a version that's not maintained for regular updates (see header).

The current docs are here: https://docs.microsoft.com/dotnet/api/microsoft.sharepoint.client.listitem.setcompliancetag

With that being said, the docs match between the two pages. It's a .NET method, not a PowerShell cmdlet. Also, you're working with a file object not a ListItem... the file object doesn't have this method on it. So... to me, this is expected as you're calling a non-existant method.

**Comment by westerdaled** [comment]
I have not problem closing this issue .  However, I am actually  working against a ListItem as in
`  $fileItem.SetComplianceTagWithMetaInfo($DefaultLabel, $isPolicyHold, $isPolicyRecord, (Get-Date), "daniel.westerdale@myclient.co.uk", $false) ` 

Still no idea what that last parameter does so set $false, kept calm and carried on😁

So to conclude this is for dev issues as in SPFx  and not issues pertinent to the usage of  PnPCommandlets  .
