### ISSUE TITLE
SP Field Customizer: Uncaught ReferenceError: Sys is not defined

### ISSUE THREAD

**Issue by arshad815** [SharePoint/sp-dev-docs#4358]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

There should be no errors in the console when the Field customizer is loaded. This happens only in Google Chrome, it works well in IE but it takes a while to load the field customizer.

In Chrome, the field customizer does not load initially but loads after a second refresh and the error is not there in the console anymore

#### Observed Behavior

Uncaught ReferenceError: Sys is not defined

    at sp.core.js:2

(anonymous) @ sp.core.js:2

setTimeout (async)

hideSubMenu @ sp.core.js:2

$1j_2 @ sp.core.js:2

(anonymous) @ sp.core.js:2

b @ ScriptResource.axd?d=XqRD2nxphZyyAgXbZGZRBjg7Cvmjc0xIXYkwKaysDfUhgp45nW1TS2mLL9-vKf6H3YmbXsbp1SzNBWhNeuum-jQrZfabtj9iClehOXgmWYcfo95vBF56VkYsTp4IB1ua4eAEgZc6Nru6oBLkB9k9NurO7QqL4Fi5cWl5g1ddMC0xUmN2OYBN1x3QpFB9R63U0&t=ffffffffa580202a:5

RemoveDOMNodes @ core.js:1

clearAllDOMElements @ core.js:1

doPrepareWorkBeforeOnePageNavForFasterOnePage @ core.js:1

bootModernApp @ core.js:1

performModernOnePageNavigationForFasterOnePage @ core.js:1

a @ init.js:1

EnsureScript @ init.js:1

EnsureScriptFunc @ init.js:1

OnePageNavigationHandler @ init.js:1

 

#### Steps to Reproduce

My code is checked in at 
https://github.com/arshad815/spfx-favorite-extension

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Can you provide additional details and context to help assist with your issue? Things that always help to post with every issue include:

- SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
- If SharePoint Online, is tenant configured for standard / targeted release
- Browser(s) tested
- SPFx version
- If applicable, version of Office UI Fabric React

As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.

**Comment by arshad815** [comment]
I am traveling out of country and do not have access to the client environment, I will return August 17 and give the additional details. Kindly keep the issue open. Thanks

**Comment by arshad815** [comment]
Andrew,

The following are the details:

- SharePoint Online
- SPO is configured for "Targeted release for Select users" but there are no users that are set to receive the targeted release in the Admin center. Earlier there was a user listed and the user was not able to use the functionality.
- IE 11, the Field customizer button loads slowly, but does not work in Chrome. Need to refresh the browser and the buttons will show up.
- SPFx version is 1.7.1
- React 16.3.2, React DOM 16.0.5, Office UI Fabric React 5.131.0

The source code is at:
https://github.com/arshad815/spfx-favorite-extension

There is a list named " Library" that will display an "Add to Favorites" button. This is a number column which I have used a field customizer to display a button using the Fabric React Button. when the button is clicked, it would add an entry in another list called "My Favorites Library". This is a way for user to keep track of their favorite documents. This was working fine but then the issue started about 3 weeks ago. 

In Chrome browser, the button does not display and the error is displayed in the Javascript console. After another refresh, the button displays and works fine. In IE 11, the button displays but it takes a while to load.

Uncaught ReferenceError: Sys is not defined

at sp.core.js:2


Thanks.

**Comment by GrahamMcMynn** [comment]
Does this actually repro for you in 1.9.1?
