### ISSUE TITLE
Can't update a People metadata field for a document in a doc library

### ISSUE THREAD

**Issue by gsheeley** [SharePoint/sp-dev-docs#4359]
Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using SPFx to a custom ribbon action "Submit for Approval" we are using the people picker https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-peoplepicker
to get the person object that they want the document checked by, and then using it to update the documents metadata field, i.e. Checker
e.g.
const result = await sp.web.lists.getByTitle("UserFieldList").items.getById(1).validateUpdateListItem([{
    FieldName: "Checker",
    FieldValue: JSON.stringify([{ "Key": "i:0#.f|membership|person@tenant.com" }]),
},
{
    FieldName: "Title",
    FieldValue: "Test - Updated",
}]); 

the title is updating but not the Checker(people) object field.

Any advice, guidance, pointers to reference material will be greatly received. Been google and looking at this now for two days. Now looking at delete person in the field and using the add method rather than the update method. 

update works on most fields, we just can't get it to work on people type fields.

**Comment by andrewconnell** [comment]
People fields are lookup fields under the covers... you say the **checker** field isn't updating... can you be more descriptive? Error? Just nothing happening? Context? Etc...

**Comment by gsheeley** [comment]
@andrewconnell - Thanks for reviewing and getting in touch. Sorry for the delay in response. I was on holiday.

Our "Checker" field is the name of a People type field.
We are able to update the Title, but if we try to include the People picker field in the update, none of the fields update. Its as if it doesn't trigger. 

Andrew - I have attached the whole tsx file and a couple of screenshots with some explanations. 

We are currently reviewing the REST api instead, due to the issues we are having with the SPFx method.

Any help you can give, would be most appreciated as we would prefer to use the newer SPFx way of working. 
[SubmitApproval.tsx.txt](https://github.com/SharePoint/sp-dev-docs/files/3491585/SubmitApproval.tsx.txt)
![PeoplePicker issue 2](https://user-images.githubusercontent.com/11026572/62854443-4275e280-bce7-11e9-8fa7-327182146c4e.png)
![PeoplePicker issue](https://user-images.githubusercontent.com/11026572/62854444-430e7900-bce7-11e9-8d3d-1a93c5ac1223.png)


Many thanks in advance.

**Comment by anomepani** [comment]
@gsheeley  Does `iNSTOREAuthorizer` People Picker Field allows multiple value or single value?

As your 'Checker' field is People Picker, it will be considered as  Lookup Column.

To Update Single valued 'Checker'  or `iNSTOREAuthorizer` People Picker filed using REST API.
In your above screenshot change 'iNSTOREAuthorizer' to 'iNSTOREAuthorizerId' and try to update item.
