### ISSUE TITLE
Get Site Description from pageContext

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#436]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Suggestion
Similar to `context.pageContext.web.title`, get site description with `context.pageContext.web.description`

**Comment by amishra0909** [comment]
Hi @jaredbuttars, If this is not a blocking issue, this will be treated as enhancement request and we have a different workflow to follow for such requests. If you still need this feature please post your request on our UserVoice page. Here is the link: [https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform)

**Comment by jaredbuttars** [comment]
Added to User Voice
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/19261366-pagecontext-web-description-and-pagecontext-user-i
