### ISSUE TITLE
Substring of a Text Field

### ISSUE THREAD

**Issue by LtCmdrKeene** [SharePoint/sp-dev-docs#4360]
#2813 ## Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a way to get a substring when formatting a column?  I want to format a column to have a hyperlink, but I need only the first 8 characters from a text field. For example:

        "href": "='https://sharepoint/team/page.aspx?Shop=' + @currentField"

I need to use use just the first left 8 characters of the @currentField, not the entire string. But I have tried **Left(@currentField,8)**, or **(@currentField).substring(0,7)** and neither worked. Any other way?

Thanks for your help! Sharing is caring.

**Comment by bcameron1231** [comment]
Unfortunately, there is no Substring or LEFT function in  the JSON formatting.

What you can do is create a hidden calculated column that takes the first 8 characters for you. Let's say your column is the 'Title' field.

Create a calculated column 'TitleCalc' with a calculation of:
`=LEFT(Title,8)`

Then format your href column by referencing that field
` "href": "='https://sharepoint/team/page.aspx?Shop=' + [$TitleCalc]"`

**Comment by LtCmdrKeene** [comment]
Unfortunately that doesn't seem to work, and I can't find a workaround. I already had a pre-existing column with that exact formula, but referencing it caused the column formatting to break entirely (show nothing at all in the column, not even the text or icon.) I dug through some documentation and discovered that calculated columns are not supported.

I don't know if they will be supported to use calculated column in the future, but I was hoping I could use the column formatting by another method.

**Comment by bcameron1231** [comment]
Can you share the calculated column formula, internal name, and then the JSON formatting you are using? 

I'd be happy to try and explore your issue. At this moment, there isn't a formula for LEFT or Substring in JSON formatting.

I have this working in my environment,

**Comment by LtCmdrKeene** [comment]
Sure thing. So the field I'm wanting to show the hyperlink on is the title field of the list, although I've renamed it to "Shop". The first 8 characters of that field are what I'd like to grab onto and concatenate onto a static link. Here's a screenshot of the initial code, I'm hovering over one of the icons so you can see the browser tip at the bottom-left showing the not-quite perfect link I'm after.

![image](https://user-images.githubusercontent.com/4219926/61975859-e6edea00-afaf-11e9-8baf-72743326c723.png)

I also have another list column called "ShopID" that is just a _=LEFT(Shop,8)_ formula calculated column. But if I reference that column then it doesn't render anything:

![image](https://user-images.githubusercontent.com/4219926/61976231-d8540280-afb0-11e9-9d9e-8368a6a3b4bc.png)

I had noticed that I _can_ successfully use regular text columns like [$Issue] or [$Subject], but [$Topic] wasn't working for me (it's just text also). That was an easy fix: the internal name of that field is actually [$Reason], I later renamed it but the internal name remained the same.  Unfortunately that wasn't the solution for [$ShopID] (that is indeed the original and internal name of the calculated column).

A last resort I might consider is linking to the original @currentField text, but link to a different static URL that is just a simple HTML file with a tiny bit of Js to read the parameter from the URL, extract the first 8 chars and then immediately redirect to the final URL. It certainly wouldn't be the first time I'd done something like that, but I was hoping to avoid it if possible.

**Comment by bcameron1231** [comment]
Thank you. Can you enable debugMode on your JSON script so we can try and see what the error is? You can specify "debugMode":true, in your JSON schema.

Second, can you confirm that the **internal field** name of ShopID is in fact ShopID?

I have copied your JSON file and placed it into my list. It's working for me. I'm hoping by you setting debugMode to true, we'll be able to see if there is an error.

![image](https://user-images.githubusercontent.com/7944457/61978257-0257f580-afae-11e9-85ef-5286fcce5938.png)

**Comment by bcameron1231** [comment]
Ah, I think the issue is because ShopID is actually hidden. If you put the column in your view, does it render your Title (Shop) field correctly?

I just tested with a view, to reference the column It had to show up in the view.

**Comment by LtCmdrKeene** [comment]
That was it!  Adding that calculated column to the view immediately made it work exactly as expected. I don't know why I didn't even think to try that.

Do you know if it's possible to add a 2nd icon?  This one is working perfect, but there's one other URL that would be great to link to if I can use multiple on the same column

**Comment by LtCmdrKeene** [comment]
Nevermind that question, that was easy to add another child element.

**Comment by jmaguial** [comment]
How come this is solved?

Being forced to add an auxiliar column to the view (needs to be added otherwise can't be reference in JSON), is a bit of a dirty workaround...

Anyone knows if there is any plan from MSFT to address this?

**Comment by bcameron1231** [comment]
It's closed because it's not a bug, it's an enhancement request. 

You can vote on the uservoice for enhanced string operations. 
https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/32345281-column-formatting-string-operations

**Comment by jmaguial** [comment]
Thanks for the reply!

As per this documentation, I would expect the substring to work, which doesn't seem to be the case. I'll go ahead with the vote then ;)

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#formatting-multi-value-fields
