### ISSUE TITLE
This method has been updated for SharePoint Server 2016-2019

### ISSUE THREAD

**Issue by MigueGo** [SharePoint/sp-dev-docs#4364]
[Enter feedback here]

Based on the source code the method forcedeletesite() can take in SPS 2016-2019 5 parameters. The 2 additional parameters are updateSiteMap and deleteIsForMigration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d46d7feb-0734-97e4-bb0f-cea450f8f260
* Version Independent ID: 7c712dff-e1cd-5fee-f384-df6fee7bf342
* Content: [SPContentDatabase.ForceDeleteSite(Guid, Boolean, Boolean) Method (Microsoft.SharePoint.Administration)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.spcontentdatabase.forcedeletesite?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint.Administration/SPContentDatabase.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint.Administration/SPContentDatabase.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Sorry... I'm not clear on what you are saying in your post... can you elaborate?
