### ISSUE TITLE
"dataLocationCode" is not available in Version 1.0

### ISSUE THREAD

**Issue by fzbm** [SharePoint/sp-dev-docs#4365]
This page states, that version 1.0 of Graph could be used to retrieve the "dataLocationCode" information, which is not the case. As right now, only the "beta" endpoint supports this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9c6a3a-4dd5-6096-e838-4451fa72c7b8
* Version Independent ID: 283e3382-85f7-fee0-278b-73d6320bfa2f
* Content: [Discover a Multi-Geo tenant configuration](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery#feedback)
* Content Source: [docs/solution-guidance/multigeo-discovery.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/multigeo-discovery.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... will get the doc updated... 

ref: https://docs.microsoft.com/en-us/graph/api/resources/sitecollection?view=graph-rest-beta
