### ISSUE TITLE
How to create user profile property in SharePoint Online

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [SharePoint/sp-dev-docs#4366]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

I have a requirement to develop a script which will create a custom user property in SharePoint Online.
In the below url, I observed that it can be done only by SSOM. But my query is how to execute SSOM in SharePoint Online? How can I achieve my task?
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/work-with-user-profiles-in-sharepoint.md
![image](https://user-images.githubusercontent.com/42473451/61945288-82bf2c00-af97-11e9-9dc3-7e0615f6eb02.png)

I observed that it can be done only by SSOM. But my query is how to execute SSOM in SharePoint Online? How can I achieve my task?
Please help 

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi, unfortunately you will not be able to achieve this requirement. You cannot execute SSOM in SharePoint Online. 

Any new profile properties created in SharePoint Online need to be done through the User Experience. However, you are able to update user profile properties using client side code, after they  have been created.

**Comment by AnjaniChallamcherla** [comment]
We can't execute SSOM on SharePoint Online. 
And there is no way to programatically create user profile properties in SharePoint Online, we must do it manually.
For reference, check this url: https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md
