### ISSUE TITLE
Tapable.plugin is deprecated. Use new API on `.hooks` instead at VisualizerPlugin.apply

### ISSUE THREAD

**Issue by user546** [SharePoint/sp-dev-docs#4367]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

I am doing SPFx upgrade to 1.9.0 and also upgrading Webpack to 4 and i am getting mentioned warning. Please help me to resolve the warning.

#### Steps to Reproduce

upgrade Webpack from 3 to 4
and build

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
SPFx v1.9.0 was pulled due to various issues (ref #4371) so until it is re-released, I'm going to close this while they fix known issues and publish v1.9.1
