### ISSUE TITLE
Customization on Modern Page - SharePoint OOB Pages

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#4369]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi Team,

Can we customize the modern page(Out-of-the box SP Pages) like Site Assets page through Application Customizer. We have added JQuery code through SPFx Application Customizer for Header and Footer. This works on normal modern site pages created manually. For OOB Site Pages like AllItems.aspx, etc.., the  Application Customizer fails with JQuery library not loading properly. Because of this, all JQuery code fails in the external js file. Please assist.

![image](https://user-images.githubusercontent.com/49272371/61947643-62a56200-afc3-11e9-94f6-b3d2336186f3.png)

**Comment by andrewconnell** [comment]
Need more context & details... 

App Customizers are installed site-wide and run on all modern pages. If you're having an issue in that context, need more detail as the OP is lacking...
