### ISSUE TITLE
🐞Wrong reference for @microsoft/sp-office-ui-fabric-core

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4370]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Bugfix or publish 1.9.0

#### Observed Behavior
Wrong reference of @microsoft/sp-office-ui-fabric-core in new projects.

```
"@microsoft/sp-office-ui-fabric-core": "1.9.0",
```

According to npm the latest version is 1.8.2 and not 1.9.0.

<img width="769" alt="Screenshot 2019-07-26 at 07 34 25" src="https://user-images.githubusercontent.com/5503835/61949144-d15cce00-af77-11e9-9a0d-84efe20a63be.png">

#### Steps to Reproduce
<img width="787" alt="Screenshot 2019-07-26 at 07 32 56" src="https://user-images.githubusercontent.com/5503835/61949068-a1152f80-af77-11e9-86c4-5d0f9470ffb5.png">

**Comment by andrewconnell** [comment]
Since 1.9 was pulled (#4371), I think this is no longer relevant... will see when 1.9.1 is released.
