### ISSUE TITLE
Can't update to SPFx v1.9, package doesn't appear

### ISSUE THREAD

**Issue by MarianoPrz** [SharePoint/sp-dev-docs#4372]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi, what happened with version 1.9 of spfx ?, I can't update this version, by any method on different machines, it seems that this version was deleted ... I have updated the package @microsoft/sharepoint and reference 1.9 doesn't appear... thanks in advance greetings!

**Comment by bcameron1231** [comment]
1.9.0 was pulled from NPM because of issues with the local workbench. Please see this issue posted by @patmill 

#4371

**Comment by MarianoPrz** [comment]
Ok thanks!
