### ISSUE TITLE
SharePoint Modern Custom Footer SPFx Customizer - Multiple scrollbars

### ISSUE THREAD

**Issue by ashwane** [SharePoint/sp-dev-docs#4375]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
There should only be one scrollbar on the page.

#### Observed Behavior
We have created a custom footer using SPFx application Customizer to provide information like social media icons, feedback button, site map (html) etc.

This is now occupying more than 90% of content area providing vertical scroll to see the content. We, then use CSS to set  footer div contents position to absolute so that when user scrolls to bottom of page then only footer visible.

Problem here is multiple scrollbar appearing which is very annoying. Footer is not placing on bottom of page rather on screen bottom - which might be the issue.
We need footer contents appear when user scrolls to bottom of page not always.
Any help is highly appreciated !!!!
<img width="1244" alt="CustomFooter" src="https://user-images.githubusercontent.com/31452750/61985038-97a8c780-b04a-11e9-9ff2-9fda81d7823e.png">
#### Steps to Reproduce
- Attaching the code in Zip.
-  run "npm  install"
- edit serve.json and add your sharepoint URL.
- run "gulp serve"
- Test and Add long length content on a  page, multiple scroll bar appears.
Thanks for your contribution! Sharing is caring.
[MyFooter.zip](https://github.com/SharePoint/sp-dev-docs/files/3437561/MyFooter.zip)

**Comment by bcameron1231** [comment]
If you want it fixed at the bottom of the screen, remove the position:absolute on your .hiveMenuFooter . However, understand your footer is quite large, this is going to reduce the viewable area on the page.

```
.hiveMenuFooter {
    padding-left: 150px;
    /* position: absolute; */
    height: 70px;
    right: 0;
    left: 0;
    padding-top: 20px;
}
```

Also if you are interested, the PnP Team has created a footer very similar to yours, included with the starter kit except it's list driven and can be opened and closed via click of a button.  It's helps with the reduction in the viewable area on the page.

Check it out here.
https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/ext-portal-footer.md

**Comment by ashwane** [comment]
@bcameron1231  Thanks for your help. Much appreciated.
I don't want to fixed it at bottom - that's why I provided the position:absolute - I want something similar to Microsoft official site (https://www.microsoft.com/en-au), where footer only visible upon scroll to bottom.

The PnP team footer is quite amazing, only thing is it opens after click of button and we are intended to make it expanded by default - which is the reason of making footer sticky/absolute not fixed. I am using enterprise taxonomy to retrieve navigation items. Please suggest if

**Comment by bcameron1231** [comment]
Unfortunately, I do not think you'll be able to achieve that.  The Footer Placeholder is outside the the scrollableArea of the content body of the page (the reason for the inner scroll bar).

**Comment by ashwane** [comment]
@bcameron1231 Thanks for your valuable advice.
We have to look for some alternative then.

**Comment by hugoabernier** [comment]
@ashwane How about making your footer expandable? It could take very little space at the bottom unless the user clicks on it or scrolls to it? That way, you're still staying within the constraints of the application extender, but you get something that doesn't take over the user's browser real estate...

**Comment by ashwane** [comment]
@hugoabernier Thanks for your valuable advice. I think that's the only option left with me and feasible as well by looking at modern page HTML design.I am wondering why MS position OOTB footer in scrollable area but recommend us to add custom footer outside of scrollable area I,e bottom placeholder.
