### ISSUE TITLE
Yammer Related Content

### ISSUE THREAD

**Issue by alwaysrcorliss** [SharePoint/sp-dev-docs#4376]
What is the best way to add a Yammer Embed component to an existing yeoman generated SPFX framework project (no javascript framework template)?  Trying to figure out how I call the Yammer API either with a require or do I need something different?

**Comment by andrewconnell** [comment]
What do you mean by "Yammer Embed component"? Can you provide more context?

**Comment by alwaysrcorliss** [comment]
I'm new to typescript and spfx based projects and much of the msft documentation on web parts talks to how to do a CRUD based wp project, or how to jQuery UI, or Graph, or Teams even.  But I can't find anything that definitively shows me how to render a Yammer conversation thread in Yeoman generated spfx web part project template.  I know there is the OOTB Yammer Conversations and Yammer Highlight web parts but I'm trying to embed my web part into a tabbed UI.  I've tried going to my Yammer group thread, and grabbing the embed code from down in the lower right link "Embed this feed in your site" and then placing it in my render method but I just get a blank content placeholder on the page and dev tools isn't giving me much to go from.  I've also tried from the msft samples, the ReactYammerAPI web part, going to the Yammer client applications and registering a new app (adding url to javascript origins as well), editing the prodconfigurations.ts with the client id and redirect url, running npm install, and trying a gulp serve but I get a could not load.  The terminal output gives an error of EADDRINUSE - address already in use.  But I'm unclear how to course correct that.  Not sure if the issue is in the code, my registered app, and like I said - there's just not much in the way of documentation on how Yammer works with the new framework so I'm feeling stuck and honestly a little naive about this.  Any help or guidance would be awesome.   Thanks!

**Comment by alwaysrcorliss** [comment]
The best source of info I found btw was this URL:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/yammer-integration-sharepoint-add-in
It cites there are 3 main options you can utilize: OOTB Yammer web part, Yammer Embed, or Yammer Graph or REST API.  Since my scenario requires customizing by nesting it in a tabbed UI interface, I chose the 3rd option (REST...not Graph)

**Comment by andrewconnell** [comment]
@alwaysrcorliss said:
> The terminal output gives an error of EADDRINUSE - address already in use.

This means when you are spinning up the local webserver that runs the local workbench for SPFx using **gulp serve**, the port is already opened and attached to something. So, you need to find the other process that's running and either stop it, or configure the local workbench to use a different port (see **config/serve.json**).
