### ISSUE TITLE
Provide Sharepoint Batch REST API Support in the cross site collection and subsites in the same Tenant.

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4377]
Provide Sharepoint Batch REST API Support in the cross site collection and subsites in the same Tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047ea71c-e866-b2dd-5530-8451de27ba4a
* Version Independent ID: 3b886e81-c3b7-d5c1-136f-4cb827b4952f
* Content: [Complete basic operations using SharePoint REST endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
The REST API does support making calls across site collections and sub sites.

Can you clarify?

**Comment by anomepani** [comment]
Here is sample request code snippet, **"A"** and **"B"** is subsite under SharePoint root site collection.

To Setup easily and test Batch API in Sharepoint I have used [BatchUtils](https://github.com/anomepani/sp-rest-util/blob/master/BatchUtils.ts)

```js
var arr=["https://brgrp.sharepoint.com/_api/web/id"
, "https://brgrp.sharepoint.com/A/_api/web/id"
, "https://brgrp.sharepoint.com/B/_api/web/id"];

BatchUtils.GetBatchAll({rootUrl:"https://brgrp.sharepoint.com",
batchUrls:arr}).then(r=>console.log(JSON.stringify(r)))
```
![Batch_API_Cross_Site_Notworking](https://user-images.githubusercontent.com/2988295/61995897-b2f7ef00-b0ab-11e9-87c9-6f378598e3b0.png)

See the attached screenshot as I have requested WebID of root site and its subsites with three request but returning only one result.

**Comment by bcameron1231** [comment]
Sorry I accidentally deleted my previous comment.

I think the issue you are seeing,  is that you can't execute a single batch request against multiple sites. You can use $batch to make multiple calls to the same site though.

**Comment by anomepani** [comment]
Yes individuals batch request is possible and it is working but for multiple sites it not working. If Batch API request support with multiple sites in single request then it reduces performance issue.

**Comment by bcameron1231** [comment]
Right. So this is an enhancement you are looking for then?

Also, in the meantime you may want to look into using the Search REST API, as you can query across all sites in a single request.

**Comment by andrewconnell** [comment]
@bcameron1231 is correct... this is a feature request as it's currently working by design... best to post this to user voice at https://aka.ms/sp-dev-uservoice
