### ISSUE TITLE
SPFX 1.9.0 is released but not being scaffold by the @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by NWH-SAmin5** [SharePoint/sp-dev-docs#4379]
SPFx 1.9.0 = https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.9-release-notes
https://www.npmjs.com/package/@microsoft/generator-sharepoint is at 1.8.2

I was able update @microsoft/generator-sharepoint to 1.9.0, 5 days back. But today I am trying update it on another computer, but not able upgrade later than 1.8.2

Can you please update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
SPFx 1.9 was pulled from NPM because of some issues with the local workbench. 

Please see issue #4371

**Comment by KaushalKhamar** [comment]
As SPFx 1.9.0 was pulled from NPM, if you have upgraded your solution to 1.9.0 then you need to downgrade your solutions to 1.8.2

**Comment by andrewconnell** [comment]
Closing this as 1.9.0 was pulled (#4371) so this is _sort of_ fixed for the time being...

**Comment by NWH-SAmin5** [comment]
@bcameron1231 @KaushalKhamar @andrewconnell Thank you for the information
