### ISSUE TITLE
What is the Office 365 tenant prefix and can we use an existing tenant to join Office 365 Developer ?

### ISSUE THREAD

**Issue by burakgunay72** [SharePoint/sp-dev-docs#4380]
Hello,

This article talks about how we can find the Office 365 Tenant ID

https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id

To find your Office 365 tenant ID in the Azure AD admin center

1. Sign in to the Azure Active Directory admin center as a global or user management admin.

2. Under Manage, select Properties. The tenant ID is shown in the Directory ID box.

I have 2 questions:

1) Now my question is, what part of this long ID is the <b>prefix</b>? 

2) This part on the page(https://docs.microsoft.com/en-US/sharepoint/dev/spfx/set-up-your-developer-tenant)  is confusing:
"If you already have an Office 365 tenant, see the section Create app catalog site.

If you don't have one, you can get an Office 365 developer subscription when you join the Office 365 Developer Program. ,," 

"Make sure that you are signed out of any existing Office 365 tenants before you sign up for the Office 365 Developer Program."

So, on the one hand it says sign up for Office 365 Developer if you don't have a tenant but then goes on to say sign out of any existing Office 365 tenants. I already have an Office 365 tenant. Can't I sign into Office 365 Developer Program with that tenant?

Your help is appreciated.

#### Category
- [X ] Question

**Comment by bcameron1231** [comment]
The Office 365 Developer Program gives you a completely different Office 365 Tenant - as a new subscription, so it's not tied your current Office 365 tenant. The documentation is just stating that if you don't have a tenant already, you can use the Developer Program to get one.

However, if you'd like to build and test solutions in your current tenant, you are also able to do that. The option is really yours. Personally, I like have use a developer tenant for developing, that is separate from my production Office 365 environment.
