### ISSUE TITLE
Formatting Email to use data from other columns

### ISSUE THREAD

**Issue by jheckccr** [SharePoint/sp-dev-docs#4383]
#2813 ## Category
- [x] Question

I have a JSON script working with an email address to open Outlook and fill in the subject and some text in the body of the email. My question, how do I incorporate data from other columns into the body of the email?  For example, I have columns named: Name1, Email1, Name2, Email2, Topic1, and Topic2. What I would like to do is have the body of the text show something like this:

Dear [Name1], 

We have found [Name2] is also interested in [Topic2]. If you would like to reach out to them you may contact them by email at [Email2].

If Name1 = Tom and Name2 = David and Email2 = david@email.com and Topic2 = Nature Photography, the email would look something like this:

Dear Tom,

We have found David is also interested in Nature Photography. If you would like to reach out to them you may contact them by email at david@email.com.

I have tried using [$Name1], [$Name2], and [$Topic2] without any success. I don't know if this is possible to accomplish or not.  If it is possible, what am I missing?

Regards,
John

**Comment by bcameron1231** [comment]
In order to reference the other columns, I believe they need to also be visible in the view.

**Comment by jheckccr** [comment]
Hello bcameron1231, they are visible in the view.

**Comment by jheckccr** [comment]
Here is the JSON that I am currently using.  Where the underscores are is where I want to fill in with information from other columns.

{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
    "elmType": "div",
    "children": [
        {
            "elmType": "span",
            "style": {
                "padding-right": "8px"
            },
            "txtContent": "@currentField"
        },
        {
            "elmType": "a",
            "attributes": {
                "iconName": "Mail",
                "class": "sp-field-quickActions",
                "href": {
                    "operator": "+",
                    "operands": [
                        "mailto:",
                        "@currentField",
                        "?subject=We have a match","\r\n\r\n",
                        "Dear __________________.\r\n",
                        "We have a match for _______________________.\r\n\r\n",
                        "Here is the contact email: _______________\r\n",
                        "Happy corresponding!\r\n\r\n",
                        "Kind regards,\r\n\r\n",
                        "John"
                    ]
                }
            }
        }
    ]
}

**Comment by bcameron1231** [comment]
Thanks for the comment. Are these columns visible in your view? As mentioned, if you want to reference them via [$column] they need to be visible in the view.

**Comment by jheckccr** [comment]
Yes, they are visible in the view.

**Comment by jheckccr** [comment]
If I add [$NameOne] to the JSON script nothing shows up in the field to open up an email.  The column is blank.

{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
    "elmType": "div",
    "children": [
        {
            "elmType": "span",
            "style": {
                "padding-right": "8px"
            },
            "txtContent": "@currentField"
        },
        {
            "elmType": "a",
            "attributes": {
                "iconName": "Mail",
                "class": "sp-field-quickActions",
                "href": {
                    "operator": "+",
                    "operands": [
                        "mailto:",
                        "@currentField",
                        "?subject=We have a match","\r\n\r\n",
                        "Dear ", "[$NameOne]","\r\n",
                        "We have a match for _______________________.\r\n\r\n",
                        "Here is the contact email: _______________\r\n",
                        "Happy corresponding!\r\n\r\n",
                        "Kind regards,\r\n\r\n",
                        "John"
                    ]
                }
            }
        }
    ]
}

**Comment by bcameron1231** [comment]
A couple things.

1. The URL you are building is incorrect, to specify the body you need to pass in the Body parameter
2. You'll need to concatenate your values on separate lines to get the values.

Try this JSON

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "debugMode": "true",
  "elmType": "div",
  "children": [
    {
      "elmType": "span",
      "style": {
        "padding-right": "8px"
      },
      "txtContent": "@currentField"
    },
    {
      "elmType": "a",
      "attributes": {
        "iconName": "Mail",
        "class": "sp-field-quickActions",
        "href": {
          "operator": "+",
          "operands": [
            "mailto:",
            "@currentField",
            "?subject=We have a match",
            "\r\n\r\n",
            "&body=Dear ",
            "=[$Test2]",
            ",\r\n",
            "We have a match for ",
            "=[$Test3]",
            "\r\n\r\n",
            "Here is the contact email: ",
            "=[$Test4]",
            "\r\n",
            "Happy corresponding!\r\n\r\n",
            "Kind regards,\r\n\r\n",
            "John"
          ]
        }
      }
    }
  ]
}
```

Replace the Test values with your **internal** column values.

**Comment by jheckccr** [comment]
Thanks for the catch on the &body=Dear, I missed that.  I did substitute the internal column values for the $Test2 (with $NameOne), $Test3 (with $Name2), and $Test4 (with $Email2).  the Column Email1, where this JSON is being placed, displays the following.  

Failure: NameOne was not found on the data object.  It is in the list and on the list view being displayed.

**Comment by bcameron1231** [comment]
It appears to be having trouble referencing that column. Can you send me a screen grab of your internal column name?

Also, why type of column is this?

**Comment by jheckccr** [comment]
It works perfect now.  It was my mistake.  When you asked for the internal column name that triggered it for me.  I changed the name of the columns that were being displayed for the user and that is the name I was using for the column and not the internal column name that is shown in the URL when I selected the column while editing the list.

Now I have something I can expand upon and understand it.

Thank you so much for helping me with this bcameron1231!  Really appreciate it!

**Comment by jheckccr** [comment]
bcameron1231, thanks for the help.  Also, for showing me how to break up the JSON so it does work.  I really appreciate it.

**Comment by bcameron1231** [comment]
Absolutely! I appreciate the clear and concise issue descriptions and json. Very helpful to figuring out the problem!

**Comment by jheckccr** [comment]
Question for you.  Are there any good reference material to be found where there are more examples of using JSON with SharePoint other than a couple of the standard web sites that are found when do a search on this topic?  For example, a reference that would have shown how to format an email correctly so that it works the way you help me to get mine to work?

**Comment by bcameron1231** [comment]
So your issue with two-fold. The missing body parameter is just an HTML requirement, not unrelated to JSON column formatting. 

It's defined in RFC2368 https://www.ietf.org/rfc/rfc2368.txt , but there are likely tons of blogs out there talking on this.

In terms of JSON formatting for SharePoint, a couple great resources:

[GitHub Repo With Samples](https://github.com/SharePoint/sp-dev-list-formatting)
[Chris Kent's Blog](https://thechriskent.com/tag/column-formatter/)

Chris is the resident expert on JSON formatting and has provided many of those samples in the GitHub. His blog and this repo is a great resource to see more in depth examples of JSON formatting in SharePoint.
