### ISSUE TITLE
Is there JSON code to create Folders in a document library?

### ISSUE THREAD

**Issue by CaseyRoot** [SharePoint/sp-dev-docs#4385]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Can you clarify what you mean by this? Are you talking about JSON Column formatting? If so, no you cannot use JSON formatting to create folders in your library.

**Comment by CaseyRoot** [comment]
If adding folders means JSON column formatting, then yes I am talking about that.  I want to create folders in the default Documents library using code.

**Comment by bcameron1231** [comment]
Can you provide more information? When do you want to create these folders? Automatically? Via user interaction with code? There are many ways to create folders in SharePoint using REST APIs, CSOM, w/ C#, PowerShell, JavaScript, etc...

**Comment by CaseyRoot** [comment]
My options would be to set up folders as part of $site_script code to create a site design or Powershell would work too.

**Comment by bcameron1231** [comment]
Okay. There is no way to do it using a Site Script inside a Site Design using JSON. The folders will need to be created after the fact, you could do it via Flow which is likely the easiest.

**Using Microsoft Flow**
As a part of your site design, use the TriggerFlow action to send a request to Microsoft Flow when a site design is run during the creation of a new site.

//Calling Flow from Site Script
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial
 When the flow runs, you can Send an HTTP Call to SharePoint to create the folders that you need using REST. Here is the REST documentation for creating a folder https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest

**Using PowerShell**
If you want to use PowerShell, it wouldn't be apart of your site design (unless you augmented your provisioning flow using TriggerFlow).  In either case, you can use CSOM and/or PnP to create the folder.
//PnP
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpfolder?view=sharepoint-ps

**Comment by CaseyRoot** [comment]
This is perfect, thank you!

**Comment by YOUBIMAX** [comment]
> This is perfect, thank you!

Hello. I hope you're doing fine! Did you manage to create the folders finally ?

**Comment by CaseyRoot** [comment]
I went route of the Flow option, however looks like I need Premium to continue.
Next I'll be looking at PS option.

**Comment by bcameron1231** [comment]
Yea the creator needs premium unfortunately. You can also use Azure Logic Apps w/ TriggerFlow which would be a slightly cheaper cost than buying premium for your account.
