### ISSUE TITLE
Internet Explorer 11 does not support Domain isolated webparts

### ISSUE THREAD

**Issue by unowiz** [SharePoint/sp-dev-docs#4386]
I have followed the Isolated webparts getting started guide here 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts and the Youtube post https://www.youtube.com/watch?v=dZBzVuM6XiQ under SharePoint Developer Community - PnP channel.

This works fine in Edge DEV(Chrome version) and IE 11 but not for Chrome(Desktop and mobile) and SharePoint iOS App. I have not tested this in Firefox yet.

Has this been recently tested across browsers? I wonder if this related to the 14th May windows update (KB4494440 ) causing issues with iFrames unable to get authenticated due to X-IFRAME-Options: deny header(fixed in July update - KB4507459 and probably not yet rolled out to the poor ADFS servers).

Update: 
EDGE DEV: works
IE11: Started working! No idea how but I have screenshot below from the initial failure

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The webpart should be rendered correctly

#### Observed Behavior
Webpart won't render in Chrome(desktop and mobile) browsers and SharePoint iOS App.

(Update: seems to be working after a while in IE11)
The webpart fails to render in IE 11 and displays the below message:

This content cannot be displayed in a frame
```
 To help protect the security of information you enter into this website, the publisher of this content does not allow it to be displayed in a frame.
 What you can try:
Open this content in a new window |   | Open this content in a new window
Open this content in a new window
```

#### Steps to Reproduce

scaffold a new SharePoint Framework project using the SharePoint Framework Yeoman generator and when prompted, if the solution requires API permissions that should be isolated and not available to other components, select Yes!

Build and deploy to app catalog and Approve the API permission requests via API Management Page within SharePoint Admin center

Add the add to the target site collection and then add the webpart to a page. 
This renders fine in Edge DEV but not in IE 11. 
![image](https://user-images.githubusercontent.com/6661669/62069245-ba480580-b22f-11e9-9e40-0271e2b519e7.png)

IE11 (Update: seems to be working after a while):
Open the iframe area in a new window, the webpart works fine in new tab.
Refresh the test page, the webpart now works fine. This might be to do with failure at authentication server not accepting request from IFRAME.

Chrome:
![image](https://user-images.githubusercontent.com/6661669/62082846-77952600-b24d-11e9-8c84-51e4d141a777.png)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Closing as appears no longer issue
