### ISSUE TITLE
AddSPField to existing Documents library is not working.

### ISSUE THREAD

**Issue by CaseyRoot** [SharePoint/sp-dev-docs#4387]
The script is not throwing an error.  When I run this in a site script, create script/design - then create the site.  I do not see my fields in the library.
I have also tried this list name:
"listName":"Shared Documents"

I have also tried this verb:
{
                "verb": "addSiteColumn",
                "internalName": "ClientID",
                "addToDefaultView": true
            }

Here is the code below:
{
	    "verb": "createSPList",
	    "listName": "Documents",
	    "templateType": 101,
	    "subactions": [
	        {
	            "verb": "addSPField",
	            "fieldtype": "Text",
				"displayName": "Client ID",
				"addToDefaultView":true
	        },
			{
	            "verb": "addSPField",
	            "fieldtype": "Text",
				"displayName": "Project ID",
				"addToDefaultView":true
	        }
	    ]
	},

**Comment by bcameron1231** [comment]
Thanks for the question. 
So your site script is erroring for me. A couple of issues -

1. The value of 'fieldtype' should be 'fieldType' with a capital T. Be careful with the JSON schema case sensitivity.
2. isRequired is a required property (the irony)

Please try this script
```

{
  "$schema": "schema.json",
  "actions": [
    {
        "verb": "createSPList",
            "listName": "Documents",
            "templateType": 101,
            "subactions": [
                {
                    "verb": "addSPField",
                    "fieldType": "Text",
                    "displayName": "Client ID",
                    "addToDefaultView":true,
                    "isRequired":false
                    },
                    {
                    "verb": "addSPField",
                    "fieldType": "Text",
                    "displayName": "Project ID",
                    "addToDefaultView":true,
                    "isRequired":false
                }
            ]
        }
  ],
  "bindata": { },
  "version": 1
}

```

**Comment by CaseyRoot** [comment]
WORKED!  Thanks
