### ISSUE TITLE
add iFrame to web part during onInit

### ISSUE THREAD

**Issue by DaveHaasPowderSoftware** [SharePoint/sp-dev-docs#4388]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We're trying to render our actual content for the web part inside an iframe. So, what I'd like to do is add and iframe to the domElement for the web part during onInit and then reference the iframe during render (by sending it messages via postMessage)

#### Observed Behavior

Adding an iframe to the dom element has no effect in onInit and the iframe is not present in the dom element during render

#### Steps to Reproduce

In the onInit() method I have:

```typescript
onInit() {

    this.iFrame = document.createElement('iframe');
    this.iFrame.src = '...';
    this.iFrame.style.width = '100%';
    this.iFrame.style.height = '100%';
    this.iFrame.style.border = '0';
    this.iFrame.style.margin = '0';

    console.log(this.domElement);
    this.domElement.appendChild(this.iFrame);
    console.log(this.domElement);

}
```

In the two console.log methods the domElement doesn't change suggesting that the append of the iframe didn't work.

In render() I have:

```typescript
render() {

    this.domElement.style.height = `${this.properties.dashboardHeight}px`;

    if (this.iFrame.contentWindow) {
      this.loadFile();
    }

}
```

However, the iFrame contentWindow property is not set up since adding the iframe to the dom element during onInit doesn't seem to work.

So, my questions are:

1) Is adding an iframe to the web part's dom element a valid approach
2) If it is a valid approach then how does one do it without having to add the iframe to the dom element on every render call, which would be expensive and a pain to set up.

Cheers,

Dave

**Comment by DaveHaasPowderSoftware** [comment]
Ok.

So I found the a relevant issue which gave me some ideas:

[relevant issue](https://github.com/SharePoint/sp-dev-docs/issues/1332)

Which references render() and renderCompleted()

I've now managed to do the following:

1) create the iframe in the render() method
2) attach a 'load' event to the iframe so that when the iframe is fully loaded i call renderCompleted()
3) use the iframe later on

Is this the appropriate way to do this? It seems to work.

Also, the docs reference the isRenderAsync property of the web part:

[docs](https://docs.microsoft.com/en-us/javascript/api/sp-webpart-base/baseclientsidewebpart?view=sp-typescript-latest)

The docs say the property isRenderAsync is meant to be override, however the property is marked read only so how is that supposed to work. It doesn't make any sense at all as described.

Cheers,

Dave

**Comment by andrewconnell** [comment]
You can configure the web part to be loaded in an IFRAME instead of a DIV using the isolated web part capability. Why not use that instead of programmatically changing it?

The way you are going about it in the above comments isn't supported so you're going to have problems doing it. SharePoint will always create a DIV and put your contents there.

**Comment by DaveHaasPowderSoftware** [comment]
Hi Andrew.

If the method I am using isn't supported why is it mentioned in the documentation that I referenced in the post?

Specifically. from the documentation for BaseClientSideWebPart renderCompleted() method:

---
This API should be called by web parts that perform Async rendering. Those web part are required to override the isRenderAsync API and return true. One such example is web parts that render content in an IFrame. The web part initiates the IFrame rendering in the render() API but the actual rendering is complete only after the iframe loading completes.
---

Also, the documentation for the domain isolated web parts includes the text:

---
When added to the page, isolated web parts are displayed using an iframe. This iframe points to a unique domain assigned to the SharePoint Framework solution where the web part is located.
---

I need to be able to point to our hosted domain. How would I do that?

Regards,

Dave

**Comment by andrewconnell** [comment]
I didn't say the _method_ is not supported, I said _the way you're going about it_  is unsupported. 

Web parts render inside of a DIV... the reference to an IFRAME in the docs is referring to isolated web parts. These web parts are rendered in their own _Microsoft-managed_ domain to isolate the web part from the rest of the SharePoint site.

There is no facility in SPFx that allows you to point to your own domain for the contents of the IFRAME.

With that being said, if you really want to load your HTML page from your domain within an IFRAME, you should look at the older dev model: SharePoint Addins, specifically [Provider Hosted addins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-add-ins#provider-hosted-sharepoint-add-ins).

**Comment by DaveHaasPowderSoftware** [comment]
So, to be as clear as possible, having a iframe in a web part is fine, however using render and renderComplete to implement it it not supported, correct?

**Comment by andrewconnell** [comment]
@DaveHaasPowderSoftware said:
> having a iframe in a web part is fine

Yes

> using `render` and `renderComplete` to implement it it not supported

It's not that it isn't supported, it's that those methods are tied to the existing `<div>` or `<iframe>` that the web part is rendered within that Microsoft provides. You're free to add your own `<iframe>` to the rendered HTML in the web part like below, it's just nothing provided is going to monitor / tap into it.

```ts
public render(): void {
  this.domElement.innerHtml = '<iframe src="https://www.contoso.com/app/index.html"></iframe>';
}
```

**Comment by DaveHaasPowderSoftware** [comment]
Perfect. That's what I wanted know. Thanks.
