### ISSUE TITLE
Setting a single application page as homepage removes 'special' New button

### ISSUE THREAD

**Issue by justdevelopment** [SharePoint/sp-dev-docs#4390]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug ?
- [X] Feature request ?
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to create a news (link) items easily when using Single Application Page as homepage.

We could probably build something that recreates this functionality, but it would be much cleaner if it was default SPO behavior. A bit more consistency in which options are available in the New button would also help.

#### Observed Behavior
When using a regular page as a homepage for a site, there is a 'special' add button where someone with sufficient privileges can easily add new news posts, news links, etc. This button is very much loved and used by our end-users.  
![image](https://user-images.githubusercontent.com/23448165/62108180-b3f66f80-b2a9-11e9-97c5-b567185dc0ec.png)
This button seems to be context aware (or just plain different everywhere :) ). When on site contents, you can add apps, lists, regular pages, etc. 
![image](https://user-images.githubusercontent.com/23448165/62108763-261b8400-b2ab-11e9-95f9-fbcb3dcd679b.png)
On a normal page it only has Page and Copy of this Page.
![image](https://user-images.githubusercontent.com/23448165/62108347-1f404180-b2aa-11e9-8237-48b7e8085b40.png)
In the site pages library you can add a new site page and a 'url' but this is the old URL link, not the new news link.
![image](https://user-images.githubusercontent.com/23448165/62108919-7e528600-b2ab-11e9-95a4-e527f6044dc1.png)

Meaning, if you are not on your site homepage, you can't create a news link item, or easily add news pages. We have not been able to find a button anywhere else to do this. 

The way pages are added also seems to differ depending on where you are when you click on New > Page. On another page you will get the nice selector with templates, but on site contents it will just create a default page for you.  Less of a problem, but something we noticed.

When creating a single application page all the extra buttons go away, this is great. However, when you make this single application page your homepage you now miss this special New button. So, when using a SAP as a homepage, it's now very very difficult for end-users to create news links.  

Is this intended behavior? We would really like the option to have a single app page as our homepage, it makes it very clean, but we also really want this special add button.

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
