### ISSUE TITLE
spHttpUtility.get() with search query returns Error: Microsoft.SharePoint.Client.UnknownError

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-docs#4392]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using spHttpClient to retrieve a response from the SharePoint search REST API, the correct JSON response value should be returned.

Example URL:
`/_api/search/query/queryText='foo'&selectproperties='Title,Path'&rowlimit=5`

#### Observed Behavior

The response in full:

`{"error":{"code":"-1, Microsoft.SharePoint.Client.UnknownError","message":"Unknown Error"}}`

#### Steps to Reproduce
Make a call to:
`this.context.spHttpClient.get`

Passing in a valid SharePoint search query.

**Comment by bcameron1231** [comment]
Can you provide a bit more information? I'm trying to understand what you are trying to do. 

SPHttpUtility is an OM class used for encoding URLs.

Are you trying to spHttpClient?

Some clarity would be helpful.

**Comment by MartinHatch** [comment]
Gah .. typo sorry!

Yes this was spHttpClient 

I have actually resolved this, I had to force the OData version headers back to v3 instead of v4 as the search API doesn't support v4.

It would be useful if the client identified /_api/search as being the target endpoint and adjusted the headers automatically.

**Comment by bcameron1231** [comment]
Ah, alright. 

Well glad to hear you got it resolved!
