### ISSUE TITLE
Error : 400 Bad Request - GET https://registry.npmjs.org/gulp

### ISSUE THREAD

**Issue by abdelnew** [SharePoint/sp-dev-docs#4402]
I want to install Yeoman and gulp, but i have the error below:

PS C:\Users\XHDE952&gt; npm install -g yo gulp
npm ERR! code E400
npm ERR! 400 Bad Request - GET https://registry.npmjs.org/gulp

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XHDE952\AppData\Roaming\npm-cache\_logs\2019-07-31T13_05_56_891Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Can you share what NPM version you are using?

**Comment by abdelnew** [comment]
Thank u for your help.
NOM version : 6.9.0
Node version : 10.16.0

it is my debug log file :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo',
1 verbose cli   'gulp' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 1652a4dc82a4c40c
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 405 https://registry.npmjs.org/yo 96ms
8 http fetch GET 405 https://registry.npmjs.org/gulp 96ms
9 silly fetchPackageMetaData error for yo@latest 405 Method Not Allowed - GET https://registry.npmjs.org/yo
10 silly fetchPackageMetaData error for gulp@latest 405 Method Not Allowed - GET https://registry.npmjs.org/gulp
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 142ms
13 verbose stack Error: 405 Method Not Allowed - GET https://registry.npmjs.org/yo
13 verbose stack     at res.buffer.catch.then.body (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
14 verbose statusCode 405
15 verbose pkgid yo@latest
16 verbose cwd C:\Users\XHDE952
17 verbose Windows_NT 10.0.17763
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "gulp"
19 verbose node v10.16.0
20 verbose npm  v6.9.0
21 error code E405
22 error 405 Method Not Allowed - GET https://registry.npmjs.org/yo
23 verbose exit [ 1, true ]

**Comment by andrewconnell** [comment]
This isn't an issue related to SharePoint, but more of an issue with NPM and installing packages. You'd do better to post in their community / forums.

One thing to consider, are you behind a proxy? If so, you'll need to configure NPM with the proxy details.
