### ISSUE TITLE
blocked by CORS policy Issue

### ISSUE THREAD

**Issue by SanthoAnbros** [SharePoint/sp-dev-docs#4404]
Getting the error message in cosole repeatedly :

Access to XMLHttpRequest at 'https://centralindia0-completenessp.svc.ms/api/collection' from origin 'https://santhoanbros4.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Also getting this error in home page also where it doens't have any custom web parts as well.

Thanks.

**Comment by andrewconnell** [comment]
Can you provide additional context? Where are you getting this, browser, SharePoint Online / on prem, etc...

![](https://media.giphy.com/media/2yqYwtl5MUa6V405Ib/giphy.gif)

**Comment by SanthoAnbros** [comment]
Facing the issue in sharepoint online site, In all the browsers and even in defaut home page also which is provided by default

**Comment by andrewconnell** [comment]
Is this a custom solution or just the OOTB experience? If the latter, this isn't the right forum to report...

**Comment by SanthoAnbros** [comment]
Thanks for the response,

I am using some custom solutions also in my sp tenant but in this case i am
not added the custom web part in home page still its showing the error.

Environment:
Custom script allowed for tenant
O365 cdn enabled for sp apps

**Comment by andrewconnell** [comment]
_OK, in that case, it's OOTB... so here's the stock message we use in that case. Sorry, but this isn't the forum for the issue:_

Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
