### ISSUE TITLE
Fonts?

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#4405]
Does the capability exist to replace the default fonts as well as colors, or is it coming soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi @sparkitect 
As of now, fonts are not supported as part of site theme.
However, Vote for an User voice [here](https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/35997901-custom-fonts)
