### ISSUE TITLE
Broken Link: Theme Generator Tool

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#4406]
https://developer.microsoft.com/en-us/fabric#/styles/themegenerator gets redirected to https://developer.microsoft.com/en-us/fabric#/styles/web which is not the Theme Generator Tool.

Haven't looked for a new link yet...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4c91be-dca2-6411-b707-a023ad26306c
* Version Independent ID: 29ba4619-814e-784a-04a8-84b4d56933dd
* Content: [SharePoint site theming - JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema#see-also)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Should point to: https://aka.ms/spthemebuilder

Will get docs updated, or feel free to submit PR ;)

**Comment by joeparzel** [comment]
https://aka.ms/themedesigner

**Comment by PopWarner** [comment]
Thanks for the info @joeparzel & @sparkitect! :) Submitted a PR to fix.
