### ISSUE TITLE
Set branding properties

### ISSUE THREAD

**Issue by sneomal** [SharePoint/sp-dev-docs#4407]
'headerBackground – Specify the header background as None, Neutral, Soft or Stong' - Spellings on Stong needs to be changed to Strong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#set-branding-properties)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... care to fix & submit a PR?

**Comment by iamguptarishi** [comment]
Submitted a PR
