### ISSUE TITLE
Add Get/Set-PnPStorageEntity to documentation (need less permissions)

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#4409]
Using PnP PowerShell you can manage tenant properties without being tenant admin. It's enough to be member in the Owners group of the app catalog site (even when using tenant scope) which can make a huge difference regarding who is able to manage the properties.

Those cmdlets should be mentioned:
```
Connect-PnPOnline
Set-PnPStorageEntity
Get-PnPStorageEntity
```

Related: https://github.com/microsoft/Office365DSC/issues/177

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ce8c13-ed38-bd19-de74-c8c42c064887
* Version Independent ID: 2eef7358-714e-853c-634e-ee15814b7cdf
* Content: [SharePoint Online tenant properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties)
* Content Source: [docs/spfx/tenant-properties.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tenant-properties.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to contribute and submit a PR improving the docs?

**Comment by heinrich-ulbricht** [comment]
Yep :)

**Comment by heinrich-ulbricht** [comment]
Hm. Seems I have to do some more testing before I can be sure how to describe the necessary permissions. Setting tenant app catalog properties as Owner works fine. But currently I am not able to set any site collection app catalog properties - not by Set-SPOStorageEntity and not by Set-PnPStorageEntity, not as site admin, not as tenant admin. Strange. Will check on other tenants.

**Comment by heinrich-ulbricht** [comment]
Ok I did not know this. Adding tenant properties to site collection app catalogs of no-script sites is not allowed. This should definitely be in the docs. Thank you Basem Tohamy from Microsoft Support for helping me out on this.
