### ISSUE TITLE
Programmatically enter DisplayMode.Edit for Single Part App Page (SharePointFullPage)

### ISSUE THREAD

**Issue by trey-miller** [SharePoint/sp-dev-docs#4410]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I was curious if there was a way to enter edit mode programmatically for a web part, specifically the single part app page (web part targeting the `supportedHosts.SharePointFullPage`). I've noticed inside the web part, `this.displayMode` is readonly. I can call `this.context.propertyPane.open()` however this only works if the current page has been in edit mode already. If you refresh the page and don't click the Edit button, the call to open the propertyPane does nothing.

I've also noticed that once you close the property pane, either with the X or the Save button, the web part does not seem to enter back into `DisplayMode.Read`. Maybe that's why `this.context.propertyPane.open()` works when calling programmatically only after the user has clicked the Edit button since the page has been loaded.

A general use case is that I want to streamline the user experience if loading the page when web part properties have not been fully configured yet, but any changes to `this.properties` seem to not get saved to the server unless the web part is in edit mode.

**Comment by andrewconnell** [comment]
Not that I'm aware of... but you can update the URL programmatically which will change the current mode. Ref: https://www.eliostruyf.com/check-page-mode-from-within-spfx-extensions/

**Comment by trey-miller** [comment]
Thanks Andrew. This looks like it works for normal modern pages, but when I try it for Single Part App Pages, it just redirects to the page url but without that search string and does not enter edit mode. By "try it" I mean appending `?Mode=Edit` at the end of the page url, either manually or by running `window.location.search = 'Mode=Edit'` in the browser console. Is this potentially a bug with the single part app pages?

**Comment by andrewconnell** [comment]
A bug, no... I'm not aware of way supported way to put a page into edit mode... this was just a hack. But another way you _could_ do it is to programmatically click the EDIT button...

... _but this is NOT supported and is just a hack instrumenting user behavior_ ...

The button is named "Edit", so when you get all elements with that name (_run this in the dev tools console_):

```js
document.getElementsByName("Edit")
```

... you see two items come back... you want the second one as it's the button (the first one is the link at the end of the quick launch nav):

![image](https://user-images.githubusercontent.com/2068657/62496618-7dd45680-b7a7-11e9-806e-148890a104c9.png)

You'd want to do a bit more work to make sure you have a reference to what you expect, but once you have the reference, you could just call `.click()` on it.

Personally, I wouldn't do this... use the UX that the users already expect.

**Comment by trey-miller** [comment]
Thanks Andrew. I agree it doesn't sound like a great solution to programmatically click the Edit button. The main reason for my query was really to get the web part properties to save, and it shifted to getting into edit mode after I noticed that the web part doesn't save when not in edit mode. I think we can work without it, but if needed I might also explore using the REST API to save the page while on the page in read mode.
