### ISSUE TITLE
Upload ZIP File to Teams

### ISSUE THREAD

**Issue by gswdn** [SharePoint/sp-dev-docs#4411]
Do I miss something? I haven't created a ZIP file prevously until this point:
"Select the Microsoft Teams application ZIP file previously created. This is the file that contains the manifest.json and two image files."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
It looks like that tutorial may be missing the instruction to Zip up the contents of the Teams folder. 

Head over to your solution and locate the Teams folder and zip up everything inside (should contian your manifest), and use this for your zip file.

**Comment by gswdn** [comment]
Hi.
Hm. the ./teams folder only contains two image files. No manifest.
Reinstalled Node, yo, gulp and @microsoft/sharepoint on my and a different machine and created a tab-enabled webpart according to the tutorial again. 
But also then: no manifest file in ./teams folder.
Any help would be appreciated...

**Comment by bcameron1231** [comment]
See if this answers your question https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction

**Comment by gswdn** [comment]
Ok. Finally, got it flying. So the tutorial is a little bit misleading here.
To make the webpart available in Teams, it's sufficient to sync the solution to Teams ("Sync to Teams" button at in the ribbon at the files tab of the SharePoint App Catalog; select solution first to enable that ribbon). Then, wait some time until the app appears in Teams.
I guess, if you'd like to have more control over how the app is displayed in Teams (icon, description etc.), you have to create your own manifest file, include icons, ZIP it and upload it in Teams as described in the Tutorial.
