### ISSUE TITLE
Gulp serve can not find module @microsoft/sp-build-web

### ISSUE THREAD

**Issue by jkgeorge1989** [SharePoint/sp-dev-docs#4413]
This is the error that I can not fix - 

`
Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Jason\tutorials\helloworld-webpart\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`
I have tried running `npm install` and `npm install @microsoft/sp-build-web@1.8.2 -save` in order to force download the package. However when I do I get a parse JSON error. I've included the snip from the cache_log below:

`129 silly fetchPackageMetaData error for jsdom@~11.11.0 Unexpected end of JSON input while parsing near '...h-cookie":"^2.2.0","w'`

I know some other issues #1380 was related to corporate proxy which is not relevant in my case. 

Any ideas?
`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nateforsyth** [comment]
If you haven't done so already, delete your **node_modules** folder and **package-lock.json** file and then run **npm install** again.

**Comment by jkgeorge1989** [comment]
@nateforsyth thanks for your suggestions. I went ahead and deleted **node_modules** folder and **package-lock.json** and then ran **npm install**. Unfortunately the issues still persists. 

The next thing I tried was to manually add the **@microsoft/sp-build-web** via `npm install @microsoft/sp-build-web@1.8.2` and get the same parse JSON error. I've attached the full debug log. 

When I run `npm outdated` it still shows all of my `@microsoft/XX` dependencies and devDependencies are missing. I'm assuming this is because the **@microsoft/sp-build-web** has thrown an error. I went ahead and manually installed all dependencies but still get can not install: 
**@microsoft/sp-build-web@1.8.2** or **@microsoft/sp-webpart-workbench@1.8.2**
`
[2019-08-02T13_03_04_310Z-debug.log](https://github.com/SharePoint/sp-dev-docs/files/3461348/2019-08-02T13_03_04_310Z-debug.log)

**Comment by andrewconnell** [comment]
Not enough info provided... can you please share your **package.json** (_please just paste the code into the comment, not the actual file_). Also, where is your project located? The logs don't make it clear, or it appears you are creating the project within your Node.js install path... which is not recommended.

You shouldn't have this issue... something else is going on.

Can you provide additional details and context to help assist with your issue? Things that always help to post with every issue include:

  - SharePoint environment (on-prem / SP 2016 / SP 2019 / SharePoint Online)
  - If SharePoint Online, is tenant configured for standard / targeted release
  - SPFx version
  - NPM & Node version

As always, any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you.
