### ISSUE TITLE
Bad Sign in Error

### ISSUE THREAD

**Issue by shivdk7** [SharePoint/sp-dev-docs#4415]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

we are facing bad sign in error while executing context.GetRequestDigest() and also used context.useragent in the header ,
DLL used: 
we are using SharePointPnPCoreOnline.dll - 1.3 version

 

### Reporting an Issue or Missing Feature
The partner returned a bad sign-in name or password error

 

### Expected behavior 
 should not get the bad sign error

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Hi is this the same issue as your previous ticket #4393?

**Comment by shivdk7** [comment]
yes i pasted in wrong forum,sorry @bcameron1231
