### ISSUE TITLE
How to call web service (ASP.NET) in SPFx webpart(React)

### ISSUE THREAD

**Issue by vivekkanse** [SharePoint/sp-dev-docs#4416]
Hello,

Customer is having existing web service which is developed into ASP.NET. Currently, we are developing office 365 - SharePoint application using SPFx web part. We want to fetch some information using this web service and need to populate into this webpart.

Need suggestion about how we can progress on this.

**Comment by bcameron1231** [comment]
How is authentication handled in the ASP.NET web service?

Please have a look at this documentation around connecting to APIs secured with Azure AD using SPFx and the AadHttpClient.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient
