### ISSUE TITLE
The articles referred to by this article point to itself !

### ISSUE THREAD

**Issue by PetRose** [SharePoint/sp-dev-docs#4418]
The is no link to No-Code solutions - it point to this article. Its an endless loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21c896ce-8059-3220-2a5a-ccfae3dc034f
* Version Independent ID: aa3c45c8-72f1-06f9-fcdd-3d75b8a6fe84
* Content: [Create SharePoint no-code solutions](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-sharepoint-no-code-solutions)
* Content Source: [docs/general-development/create-sharepoint-no-code-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/create-sharepoint-no-code-solutions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Doc bug... we'll get this fixed, or feel free to remove the link in a PR
