### ISSUE TITLE
Before Adding new  site design by running Add-SPOSiteScript I ran Get-SPOSiteDesign and Get-SPOSiteScript but didn't got anything.

### ISSUE THREAD

**Issue by beyondbhupendra** [SharePoint/sp-dev-docs#4421]
Before Adding new  site design by running Add-SPOSiteScript I ran Get-SPOSiteDesign and Get-SPOSiteScript but didn't got anything.

I have SharePoint Online Management Shell and PNP SharePoint PowerShell installed.

I have ran Connect-SPOService for connecting to my tenant after that I ran Get-SPOSiteDesign and Get-SPOSiteScript but didn't got anything.

**Comment by andrewconnell** [comment]
Not clear on the submission... is this a question, is something wrong, etc? There's not enough detail here... please share the results you are getting and the command you are running (ie: show the command prompt).
