### ISSUE TITLE
Error - [spfx-serve] Error: Invalid glob argument: 

### ISSUE THREAD

**Issue by mantis** [SharePoint/sp-dev-docs#4422]
#### Category
- [x] Bug

#### Expected or Desired Behavior

Same issue as closed issue - #2897

Attempting to use spfx framework for the first time. I seem to be hitting a loop of latest gilp 3.9 crashing on windows 10 and spfx-serve not work with gulp4/node12

yo
select generator @microsoft/sharepoint
*create web part project*
gulp trust-dev-cert
gulp serve

No changes have been made to the project generated by the generator so far.

#### Observed Behavior

if I try to run with gulp 4.0.2:

gulp -v
CLI version: 2.2.0
Local version: 4.0.2

node -v 
v12.7.0

Starting api server on port 5432.
Registring api: /getwebparts
Registring api: /*.*
Registring api: /workbench
[15:17:54] Error - [spfx-serve] Error: Invalid glob argument:
[15:17:54] Error - 'spfx-serve' sub task errored after 362 ms
 Invalid glob argument:
[15:17:54] 'serve' errored after 378 ms

if I downgrade to globally installed gulp 3.9.1, gulp crashes with:

gulp[20232]: c:\ws\src\node_contextify.cc:651: Assertion `args[1]->IsString()' failed.
 1: 00007FF663E8AA8F napi_wrap+122063
 2: 00007FF663E32746 v8::base::CPU::has_sse+34470
 3: 00007FF663E32A63 v8::base::CPU::has_sse+35267
 4: 00007FF663E3B4B3 v8::base::CPU::has_sse+70675
 5: 00007FF66442A89B v8::internal::StubCache::Set+1627
 6: 00007FF6645AF636 v8::internal::Builtins::builtin_handle+335398
 7: 00007FF6645AFCC2 v8::internal::Builtins::builtin_handle+337074
 8: 00007FF6645AFAFE v8::internal::Builtins::builtin_handle+336622
 9: 00007FF664A3982D v8::internal::SetupIsolateDelegate::SetupHeap+614605
10: 00007FF6649A950A v8::internal::SetupIsolateDelegate::SetupHeap+23978
11: 00007FF664A8DBD4 v8::internal::SetupIsolateDelegate::SetupHeap+959604
12: 00007FF6649ADCDC v8::internal::SetupIsolateDelegate::SetupHeap+42364
13: 00007FF6649ADCDC v8::internal::SetupIsolateDelegate::SetupHeap+42364

Installling locally gives with npm install gulp@3.9.1 --save-dev

gives the following error:

fs.js:27
const { Math, Object } = primordials;                         
ReferenceError: primordials is not defined

**Comment by bcameron1231** [comment]
A couple quick notes

1. the current node version supported for SPFx is Node LTS version 10.
2.  unrelated to SPFx/SharePoint - Gulp 3 isn't supported in Node v12 anyways, which is likely why you have the error with 3. 

My recommendation would be to uninstall Node 12, install NodeJS LTS version 10 and see if you have the same issues.

**Comment by mantis** [comment]
@bcameron1231 consider this closed. I needed node 12 for a different project, so have set up nvm to run node side by side - gulp serve is now running, listenings on two 2 ports - I can access one port, but not the /workbench url, but I suspect that is as I've done nothing yet and not completed the bits of the guides I could not get to originally :)

**Comment by bcameron1231** [comment]
Great! Thank you. We'll close this ticket.

**Comment by Worble** [comment]
The current node LTS is now 12.13.0 according to their website, is there any ETA on when SPFx will be supporting this?
