### ISSUE TITLE
some info missing

### ISSUE THREAD

**Issue by gswdn** [SharePoint/sp-dev-docs#4423]
Unfortunately, some information is missing in the tutorial. Would be nice to provide step-by-step tutorials that are complete and that work on a green field ;) - at least, in the beginner's section. Took me some time to figure it out.

* you need to "npm install @microsoft/sp-component-base"
* import { ThemeProvider, ThemeChangedEventArgs, IReadonlyTheme } from '@microsoft/sp-component-base';
* declare variables "private _themeProvider: ThemeProvider;" and "private _themeVariant: IReadonlyTheme;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5fe832e-68cc-0f3a-acc1-c9116a5c981d
* Version Independent ID: 4b6961ad-45a6-aef9-f197-c31b1cb4a5f8
* Content: [Supporting section backgrounds](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds)
* Content Source: [docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You don't need to install **@microsoft/sp-component-base**... it's already part of the dependency tree.

But the other points would help... care to submit an update to the doc as a PR to help us improve them?

**Comment by thechriskent** [comment]
The code shown comes from the full samples available here: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/section-backgrounds

I've added the import statements and private variable declarations as well as linked off to the full samples. Hopefully, that will help clear up any confusion. Thanks for bringing this to our attention!
