### ISSUE TITLE
CSP Error on fp.js

### ISSUE THREAD

**Issue by mickebackman** [SharePoint/sp-dev-docs#4424]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When using the filter by directly on a column the list should filter by that choice and not throw an error. 

#### Observed Behavior
When using the filter by directly on a column in a list an error occurs. "Cannot read property 'replace' of undefined'. The filtering works by going to the filter icon to the right but not directly on the columns.

Occurs on many browsers: Chrome Version 76.0.3809.87, Firefox 68.0 and Microsoft Edge 44.17763.1.0.

The error message from Chrome is (same on the others but in my own language):

suiteux.shell.header.98bb5695a3deb798f239.js:11 Refused to load the script 'https://r4.res.office365.com/footprint/v2.9/scripts/fp.js' because it violates the following Content Security Policy directive: "script-src 'self' https://contentstorage.osi.office.net https://swx.cdn.skype.com https://res.delve.office.com https://lpcres.delve.office.com https://static.sharepointonline.com https://widget.uservoice.com https://by2.uservoice.com https://www.bing.com/api/maps/ https://www.bing.com/rms/ https://spoprod-a.akamaihd.net https://fabriciss.azureedge.net https://publiccdn.sharepointonline.com https://ajax.aspnetcdn.com https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-07-19-sts_20190725.002/ https://r1.res.office365.com https://webshell.suite.office.com https://shellux.msocdn.com https://shellprod.msocdn.com https://shellppe.msocdn.com https://shellprod.msocdn.com https://c1-excel-15.cdn.office.net https://c1-onenote-15.cdn.office.net https://c1-powerpoint-15.cdn.office.net https://c1-visio-15.cdn.office.net https://c1-word-view-15.cdn.office.net 'unsafe-eval' 'nonce-698a3de8-180a-49d2-ba96-9f085a70f06d'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

As you can see the r4.res.office365.com is not included. And the pages response headers include this CSP row (also seen in the error):

content-security-policy: script-src 'self' https://contentstorage.osi.office.net https://swx.cdn.skype.com https://res.delve.office.com https://lpcres.delve.office.com https://static.sharepointonline.com https://widget.uservoice.com https://by2.uservoice.com https://www.bing.com/api/maps/ https://www.bing.com/rms/ https://spoprod-a.akamaihd.net https://fabriciss.azureedge.net https://publiccdn.sharepointonline.com https://ajax.aspnetcdn.com https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-07-19-sts_20190725.002/ https://r1.res.office365.com https://webshell.suite.office.com https://shellux.msocdn.com https://shellprod.msocdn.com https://shellppe.msocdn.com https://shellprod.msocdn.com https://c1-excel-15.cdn.office.net https://c1-onenote-15.cdn.office.net https://c1-powerpoint-15.cdn.office.net https://c1-visio-15.cdn.office.net https://c1-word-view-15.cdn.office.net 'unsafe-eval' 'nonce-a711bf48-0f64-47bc-999f-dc70ff16a343'

Sharepoint Online Modern on a communication site is the one we are using with version:

vti_encoding:SR|utf8-nl
vti_extenderversion:SR|16.0.0.9124

Have tried on multiple tenants and multiple lists with the same result.

Any suggestions or workarounds?

#### Steps to Reproduce
Make a modern communication site in SPO and make a list. Then try to filter by a specific value in a column and the error should appear. Do not filter by the icon because it works there.

**Comment by andrewconnell** [comment]
I believe this is an issue with the OOTB experience, not custom code as I don't see anything in your issue related to a custom component you're working on, correct? 

Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
