### ISSUE TITLE
SPComponentLoader.loadScript does not provide requirejs' define

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#4426]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I created an ApplicationCustomizer trying to load our company's javascript files, among those is `require.js` and the `config.js` for it.

```js
  @override
  public async onInit(): Promise<any> {
    return new Promise(async resolve => {
      // works
      await SPComponentLoader.loadScript('https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js')

      // works, returns object with { define, require, requirejs }
      await SPComponentLoader.loadScript(`.../require.js`)
      // "works", require and requirejs are defined. "define" is not.
      await SPComponentLoader.loadScript(`.../config.js`)
      resolve()
    })
  }
```

The `config.js` file calls `define(...)` to register additional modules.

#### Observed Behavior

I get an exception in the `config.js` file when it calles `define(...)`

Uncaught (in promise) TypeError: Error loading .../config.js
	Evaluating ...config.js
	define is not a function
    at eval (config.js:87)
    at eval (config.js:91)
    at eval (<anonymous>)
    at l.N (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:4:18617)
    at r.execute (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:5:7820)
    at u (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:5:3340)
    at n (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:5:1893)
    at Object.execute (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:5:6964)
    at y (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:4:11182)
    at w (eval at <anonymous> (sp-pages-assembly_de-de_02834f180ce7e458885afd9cc9d7eae3.js:169), <anonymous>:4:11561)

#### Steps to Reproduce

Adding `SPComponentLoader.loadScript` to load `require.js` and another file that calls `define(...)` should throw this error.

**Comment by andrewconnell** [comment]
Have you tried loading **config.js** explicitly after **requre.js** is loaded like:

```js
SPComponentLoader.loadScript(`.../require.js`).then({
  SPComponentLoader.loadScript(`.../config.js`).then({
    resolve()
  })
});
```

Or have you considered using the `externals` capability to set the dependencies before **config.js** is loaded? [ref this doc for more options](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom). 

Possible dupe with #1117??

**Comment by johannes-z** [comment]
@andrewconnell Sadly that didn't work either:

```js
      SPComponentLoader.loadScript(`.../require.js`, {globalExportsName: 'define'}).then(() => {
        SPComponentLoader.loadScript(`.../config.js`).then(() => {
          resolve()
        })
      });
```

Results in: `define is not a function`.

I've tried a variety of different ways now. It seems as if the spfx is overriding the global require. This is the closest I got to:

```js
const requirejs: REQUIRE_JS = await SPComponentLoader.loadScript(`.../require.js`) as REQUIRE_JS
window['define'] = requirejs.define
window['require'] = requirejs.require
window['requirejs'] = requirejs.requirejs
requirejs.require([`.../config.js`])
```

This loads both `require.js` and `config.js` without errors, but the `requirejs.config` that's called within `config.js` is lost when I call `require` later. For example, `require(['file'])` works within the `config.js` but not when I call it from the console.

**Comment by andrewconnell** [comment]
Yup... `define` is already loaded on the page by SPO...

![image](https://user-images.githubusercontent.com/2068657/62545741-4b227080-b830-11e9-89a5-dcceec59f6c4.png)

I recall others having issues with requirejs in the past, but can't recall the resolution. @StfBauer / @estruyf / @waldekmastykarz / @VelinGeorgiev you have any ideas? I haven't touched requirejs in years so don't recall...

@johannes-z have you considered using systemjs? It's already on the page and what SPFx is using... not sure how much you own custom stuff (or if you're trying to load a vendor solution).

**Comment by johannes-z** [comment]
We have a suite of javascript files, all built as `umd/amd` modules, but not as npm packages. Changing the project structure to make those files available via an application customizer is a very tedious and time costly task. I'd prefer keeping the current structure, and simply make requirejs and our company's config.js available via application customizer that I can distribute tentant-wide.

**Comment by andrewconnell** [comment]
OK... fair enough. Have you tried using the externals option, as I mentioned in [my comment](https://github.com/SharePoint/sp-dev-docs/issues/4426#issuecomment-518630970) instead of using the component loader?

However, I suspect you're going to run into problems, either with your solution or with OOTB SharePoint capabilities, if you are trying to replace the `define` instsance already present in SPO.

**Comment by johannes-z** [comment]
@andrewconnell I tried using the externals option, but the modules aren't an npm package, so I can't `npm install` them, so the package isn't compiled because of typescript errors saying that the module wasn't found... I don't necessarily have to replace the `define` of SPO, but I need to configure it so I can set aliases, baseUrl, shims, etc.

**Comment by andrewconnell** [comment]
Researched a bit more, seems requirejs is already on the page (_see https://github.com/SharePoint/sp-dev-docs/issues/714#issuecomment-319142037_).

There's a long discussion on that issue (#714) that might help... I'm not sure though... 

Looping @mpasarin who might have some ideas on using requirejs with your solution...

**Comment by johannes-z** [comment]
> Yup... `define` is already loaded on the page by SPO...
> 
> ![image](https://user-images.githubusercontent.com/2068657/62545741-4b227080-b830-11e9-89a5-dcceec59f6c4.png)
> 
> I recall others having issues with requirejs in the past, but can't recall the resolution. @StfBauer / @estruyf / @waldekmastykarz / @VelinGeorgiev you have any ideas? I haven't touched requirejs in years so don't recall...
> 
> @johannes-z have you considered using systemjs? It's already on the page and what SPFx is using... not sure how much you own custom stuff (or if you're trying to load a vendor solution).

@andrewconnell I don't think it's on the page. It's only available within the sp-pages-assembly (I think). `define` is exposed to `window` but `require` and `requirejs` aren't.

**Comment by johannes-z** [comment]
@StfBauer @estruyf @waldekmastykarz @VelinGeorgiev @andrewconnell Sorry for the bump. Are there any news on this topic? This is "bug" or behavior is a big blocker for us.

**Comment by johannes-z** [comment]
In `require.js` there is this block that makes `require`, `requirejs` and `define` global variables:

```js
    if (typeof define !== 'undefined') {
        //If a define is already in play via another AMD loader,
        //do not overwrite.
        return;
    }

    if (typeof requirejs !== 'undefined') {
        if (isFunction(requirejs)) {
            //Do not overwrite an existing requirejs instance.
            return;
        }
        cfg = requirejs;
        requirejs = undefined;
    }

    //Allow for a require config object
    if (typeof require !== 'undefined' && !isFunction(require)) {
        //assume it is a config object.
        cfg = require;
        require = undefined;
    }
```

But the modern UI pages only expose `define`, so `require` and `requirejs` are never set. Commenting this out doesn't work either - I think because the `define` is still overridden by the modern ui page

**Comment by johannes-z** [comment]
@andrewconnell I did some experiments with system.js, but I couldn't register libraries, such as vuejs:

```
Uncaught Error: System.config() is not supported. Use a manifest to specify the configuration.
```

`System.register` works with my libraries, but since `config` is unavailable, I can't register libraries from CDNs.

**Comment by GrahamMcMynn** [comment]
We currently use System.js.  We are moving to require.js, however, that change has not rolled out yet (and we don't have an ETA).  However, system.js and require.js have conflicts that prevent them from working with SPFX at the same time.

**Comment by johannes-z** [comment]
What's the reason to change to requirejs?

Also is there a workaround for the lacking system.config function?

**Comment by johannes-z** [comment]
@andrewconnell @GrahamMcMynn 
Using `System.amdRequire` and `System.amdDefine` **could** potentially work, **BUT**  I cannot use named aliases for my files, since there is no `System.amdConfig`, nor can I use SystemJS' own `System.config` because it's disabled by SPFX:

```
System.config({ ... })
```
```
sp-pages-assembly_de-de_647c5efaa2e7346020b494dd9d4a56fd.js:formatted:61554 Uncaught Error: System.config() is not supported. Use a manifest to specify the configuration.
    at l.e.config (sp-pages-assembly_de-de_647c5efaa2e7346020b494dd9d4a56fd.js:formatted:61554)
    at <anonymous>:1:8
e.config @ sp-pages-assembly_de-de_647c5efaa2e7346020b494dd9d4a56fd.js:formatted:61554
(anonymous) @ VM2995:1
```

1. How can I work around this issue.
2. Is there documentation on how to create such a manifest outside of an spfx webpart?
