### ISSUE TITLE
yoeman code generator @microsoft/sharepoint is not working for few days

### ISSUE THREAD

**Issue by peni4142** [SharePoint/sp-dev-docs#4429]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Steps to Reproduce

Have NodeJS version v.8.11.4 installed.
Execute `yo @microsoft/sharepoint`

![image](https://user-images.githubusercontent.com/33463108/62546761-5d1e0680-b864-11e9-97e9-808190125b67.png)

If you replace all `1.9.0` Versions with `*` or `1.8.1` in `package.json` you can execute `npm i` but if you execute `gulp serve` you get following on https://localhost:4321/temp/workbench.html

![image](https://user-images.githubusercontent.com/33463108/62546985-c30a8e00-b864-11e9-8d1b-e99ddd516ba0.png)

**Comment by andrewconnell** [comment]
Have you uninstalled SPFx v1.9.0 and reinstalled SPFx v1.8.2?

You can see in the screenshot you're still pulling a v1.9.0 package... that won't work as 1.9.0 was unpublished.

Don't try to just replace the packages in 1.9.0... recreate the project. There very well have been other configuration stuff in the v1.9.0 generated project scaffolding... best to create a new project and attempt.

**Comment by peni4142** [comment]
Yeah... that was a new project...

**Comment by andrewconnell** [comment]
Yes... it's working fine for me.

Can you post your project to a public github repo and share a link to it, or share the contents of **package.json** here?

**Comment by peni4142** [comment]
Removing and adding generator solved it for me:
`npm uninstall -g @microsoft/generator-sharepoint`
`npm install @microsoft/generator-sharepoint`

`yo @microsoft/sharepoint`
Is now executeable again
