### ISSUE TITLE
Upgrade TypeScript package from 3.4.5 to 3.5.3

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#4430]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Upgrade Typescript package version to 3.5.3

#### Observed Behavior

I still see older version of TypeScript:

![image](https://user-images.githubusercontent.com/6519992/62558753-7906b580-b82e-11e9-9a34-bd449d3cce03.png)

![image](https://user-images.githubusercontent.com/6519992/62558776-8459e100-b82e-11e9-8947-5a02e20120a9.png)

#### Steps to Reproduce

npm install -g typescript@3.5.3
npm ls typescript

Please let me know how I can get latest version of TypeScript in my project?

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Thanks for the question.

Looks like you submitted a similar ticket last year #3007 . Does this resolution no longer work for you?

**Comment by xyz92** [comment]
Will try that, Thank you!

**Comment by deshaware** [comment]
![image](https://user-images.githubusercontent.com/19376058/62649563-b5dbc500-b972-11e9-958f-84abeebf28d1.png)

I did install, but it didn't work when I _gulp serve_

![image](https://user-images.githubusercontent.com/19376058/62649487-9e9cd780-b972-11e9-842a-e5eaf1db33f0.png)

**Comment by andrewconnell** [comment]
You haven't completed all the steps for using a different version of TypeScripts. Please follow the instructions when using a different version of TypeScript than what the project is created with: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#support-for-typescript-27-29-and-3x

I wrote about it in more detail in this post: http://www.andrewconnell.com/blog/sharepoint-framework-v1-8-0-what-s-in-the-latest-update-of-spfx

**Comment by deshaware** [comment]
@andrewconnell  Thank you sir! it worked for me :) 

New typescript version and office-react works perfect.

Although, there is just an error coming which I am unsure of 

![image](https://user-images.githubusercontent.com/19376058/62652011-effb9580-b977-11e9-9113-c8b03f3a2516.png)

Thanks again :)

**Comment by andrewconnell** [comment]
@deshaware can you please open a new issue? That is different from what the OP submitted & this issue is closed. We try to keep one issue per topic and not hijack existing ones. Also will need you to provide more context (package.json file, etc...)
