### ISSUE TITLE
How about explaining what is returned?

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#4431]
The old documentation had other useful information, like: what is returned, what permissions are needed to use this API, what exceptions could be thrown and even a sample code on almost everything.
All this information is now gone from the new documentation site... making the server API documentation virtually useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc04e7f2-0f5b-2f1a-c7e9-f6490a86e72e
* Version Independent ID: 6a694c84-920c-0991-0b04-4b05a3ebdf95
* Content: [SPFieldCollection.AddFieldAsXml Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spfieldcollection.addfieldasxml?view=sharepoint-server#Microsoft_SharePoint_SPFieldCollection_AddFieldAsXml_System_String_System_Boolean_Microsoft_SharePoint_SPAddFieldOptions_)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPFieldCollection.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPFieldCollection.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
Not sure I follow... the old docs ([referenced here](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-services/ms472543(v%3Doffice.12))) don't have any additional details about what's returned...

**Comment by shaipetel** [comment]
Hey @andrewconnell , thanks for the quick response.

Sure they do, looking at the link you sent.

It says:
**Return Value**
Type: System.String
**A string that contains the name of the new field.**

that last line is the missing information I was referring to.
Telling the developer a string is returned is meaningless unless you tell him what that string contains, and how he should use it.

You can also see the "Syntax" area, which had a bit of a code usage sample, on some objects more than on others. In the new version that ONLY has the signature, without any samples at all.

Also, in other APIs such as SPWeb.Users vs. SPWeb.SiteUsers vs. SPWeb.AllUsers it used to list that some of them require the user to have higher permissions or he will get an access denied error.
That's gone now as well.

Here, in the old docs:
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-services/ms461381%28v%3doffice.12%29

there is a code sample, as well as a warning about disposing of objects. this is all gone now from the new documentation.
Granted, the code samples are usually not very helpful, but the descriptions for parameters, return values and warnings are - and these were all removed from the new documentation.

**Comment by andrewconnell** [comment]
Totally understand, but this (_migration of old docs from MSDN => docs.microsoft.com_) is a known issue. Here's a comment from MSFT about this, but there's no much more I can say on it: https://github.com/SharePoint/sp-dev-docs/issues/2364#issuecomment-414684429

Not dismissing your issue, but it's technically a dupe as this has been raised so closing...
