### ISSUE TITLE
Setting iconPath in package-solution.json does almost nothing?

### ISSUE THREAD

**Issue by eralston** [SharePoint/sp-dev-docs#4433]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Setting the iconPath in package-solution.json should set the icon for the solution everywhere; however, right now it seems that it only works to set the classic view.

#### Observed Behavior
Icon path is set in solution here:
![image](https://user-images.githubusercontent.com/636858/62233116-bd044100-b37c-11e9-8de2-c653c7d7c0d5.png)

Does display in the classic view here:
![image](https://user-images.githubusercontent.com/636858/62233079-a8c04400-b37c-11e9-9d45-44ad108c39a2.png)

But does NOT display anywhere else. Is this the correct property?

#### Steps to Reproduce
1) set the iconPath property in package-solution.json of an SPFx add-in
2) Upload to the site collection app catalog
3) Try to install the app of the given name

You will see that it is NOT using the iconPath to set the icon.

I'm worried I'm doing the right thing or that perhaps there is a limitation with where the Icon Path can be set and perhaps I have done the right thing and just have wrong expectations.

Thanks for your contribution! Sharing is caring.

**Comment by thechriskent** [comment]
That is all the `iconPath` property is useful for (classic views). If you are wanting to have the app catalog use your icon and to have that icon show up on the App Details page, you'll need to also specify the Icon URL property of your app in the app catalog (this is not something that can be controlled from your package, currently).

Here is a post I put together explaining how to set both: https://thechriskent.com/2017/06/19/sharepoint-framework-app-icon/

**Comment by eralston** [comment]
Thank you @thechriskent! Too bad it doesn't do more than change the classic view, but I'll survive. Thanks!
