### ISSUE TITLE
Work for task list? Regional settings affect the code?

### ISSUE THREAD

**Issue by S-Taipa** [SharePoint/sp-dev-docs#4434]
Does this work for task list? I've being trying and doens't work. Does the code change with regional settings? Thank you.

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/pt-pt/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Column Formatting is only supported in modern list views. Since Task Lists do not support a modern view currently, you will be unable to use Column Formatting.
