### ISSUE TITLE
This is a useless document

### ISSUE THREAD

**Issue by edcartagena** [SharePoint/sp-dev-docs#4435]
How about telling us which connector was used for this document rather than telling use there are hundreds to choose from or telling us of possible connectors we can choose because I have no clue with connectors support "HTTP request"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afac891-6cf5-1746-6392-8cb61a441770
* Version Independent ID: b5d1f95b-f40b-8d0c-7334-7608a3add9ff
* Content: [Using site designs and Microsoft Flow to track site creation requests](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial)
* Content Source: [docs/declarative-customization/site-design-trigger-flow-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-trigger-flow-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
This page describes a process that doesn't use connectors, it uses triggers. The page does say which is being used on number 3, "**When an HTTP request is received**" (This is the Trigger name)

![image](https://user-images.githubusercontent.com/7944457/62644041-3b318c00-b917-11e9-8df2-556d56da1e47.png)

If you feel this is unclear, please submit a PR with the change that you think would be more appropriate.
