### ISSUE TITLE
Get value with the same selectedItems function for 2 differentes PeoplePicker

### ISSUE THREAD

**Issue by danbran99** [SharePoint/sp-dev-docs#4440]
## Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [] Example checked item (*delete this line*)

Hello, I am a beginner with SPFX. I added 2 "PeoplePicker" in a webpart and I would like to use the same function "selectedItems" for all "PeoplePicker". I would like to know how I can pass information from my control or retrieve control information in the "selectedItems" function.

I tried to pass a parameter and tried to use bind like this._getManager.bind (this, "controlName") but it does not work.

I could call 2 different functions and push the peoplepicker value in 2 different variables but it's not really clean.

Example : 

public render(): React.ReactElement<IWebPartTeamFormDrpProps> {
    const { dpselectedItem, dpselectedItems } = this.state;
    const { name, description } = this.state;   
    pnp.setup({
      spfxContext: this.props.context
    });
 
    return (
			<form>
				<div className="ms-Grid-col ms-u-sm8 block">
				  <PeoplePicker
					context={this.props.context}
					key="Manager"
					personSelectionLimit={1}
					groupName={""} // Leave this blank in case you want to filter from all users
					showtooltip={false}
					isRequired={true}
					disabled={false}
					selectedItems={this._getManager}
					errorMessage={(this.state.Manager.length === 0 && this.state.onSubmission === true) ? this.state.required : " "}
				   // errorMessageclassName={styles.hideElementManager}
					/>
				</div>
				<div className="ms-Grid-col ms-u-sm8 block">
				  <PeoplePicker
					context={this.props.context}
					key ="Tech_x0020_leader"
					titleText=" "
					personSelectionLimit={1}
					groupName={""} // Leave this blank in case you want to filter from all users
					showtooltip={false} 
					isRequired={true}
					disabled={false}
					selectedItems={this._getManager)}
					errorMessage={(this.state.Tech_x0020_leader.length === 0 && this.state.onSubmission === true) ? this.state.required : " "}
				   // errorMessageclassName={styles.hideElementManager}
					/>
				</div>
			</form>
			
 );
  }

 private _getManager(items: any[]) {
  //  this.state.controlName.length = 0;
    for (let item in items)
    {   
  //    controlName.push(items[item].id);
      console.log(items[item].id);        
    }
  }
...

Could you help me please.

Thank you

Danny

**Comment by andrewconnell** [comment]
This question looks to be specific to the [PnP Reusable property pane controls for the SharePoint Framework solutions](https://sharepoint.github.io/sp-dev-fx-property-controls/) project... is that correct? 

If so, better to post your question in that project's issue list since it's not a general SharePoint dev: https://github.com/SharePoint/sp-dev-fx-property-controls/
