### ISSUE TITLE
Browsing HTML file in Modern View of Classic Site

### ISSUE THREAD

**Issue by bhanuchintha** [SharePoint/sp-dev-docs#4447]
Hello Team, What is the expected behavior when browsing HTML file (Present in Documents library) in Modern view of Classic site? I am able to browse the page normally. Is this issue only in Classic sites? Can you please let me know. 

Thanks, 
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46053cad-6e95-c45d-608f-5262c31b0eeb
* Version Independent ID: 641cf9a1-7e4c-ea58-dd55-dcb80b80435d
* Content: [Migrating from the permissive browser file handling to the default strict browser file handling](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting#feedback)
* Content Source: [docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-permissivesetting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
