### ISSUE TITLE
Allow Unsafe Updates

### ISSUE THREAD

**Issue by towkneed** [SharePoint/sp-dev-docs#4448]
### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After following the instructions under the "Create app catalog site" section and getting to step 3 I expect the New App Catalog form to load.

#### Observed Behavior
After clicking 'Ok' as per step 3 instructions under "Create app catalog" I receive the error "Updates are currently disallowed on GET requests.  To allow updates on a GET, set the 'AllowUnsafeUpdates' property on SPWeb."

#### Steps to Reproduce
Follow the instructions at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant .  After step 3 under Create app catalog site the error appears.

I understand 'AllowUnsafeUpdates' on an SPWeb object from the server side object model but I have no idea how to set that property in this context.

**Comment by towkneed** [comment]
Nevermind.  It's working now.  Guess it just took time to process.

**Comment by shiwanik** [comment]
I am also facing exactly same issue at the same step. Any resolution ? already tried doing it multiple times but still getting the same error .

**Comment by georgey58** [comment]
I have exactly the same problem. Been trying repeatedly for over an hour. @shiwanik did you find a solution?

**Comment by vkool85** [comment]
I am facing the exact same issue while creating the App Catalog in my newly created sharepoint online tenant with my E5 developer subscription. As I was able to create the same app catalog in my E3 developer subscription.
