### ISSUE TITLE
How to get all users in my SharePoint tenant using C# code

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [SharePoint/sp-dev-docs#4457]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

I have a requirement to list down all the user profiles in my SharePoint tenant using C# code .
How can I do that? 

Thanks in advance.

**Comment by anomepani** [comment]
@AnjaniChallamcherla For which platform you want this functionality e.g. SharePoint Online or SharePoint OnPremise(Specific version)? 
Which information do you want to display from the user profile?

For SharePoint Online you can use  Microsoft Graph [https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp)

**Comment by AnjaniChallamcherla** [comment]
@anomepani Thanks for your  reply

I want it for SharePoint Online. 
I want to display user profile properties like First Name, Last Name,...... also I want to display custom properties as well.

I tried with Graph,
https://graph.microsoft.com/v1.0/users - this query displays only 100 user profiles.
I couldn't understand how to get all the users in my tenant

**Comment by anomepani** [comment]
@AnjaniChallamcherla by default Graph will return 100 users. In Request, if you pas $top =999 then you can get 999 users at once. If you notice along with users response you will get paging related fields as well which will be used for next request.

You can use paging feature for fetching n number of users using Microsoft Graph.
Refer : [https://docs.microsoft.com/en-us/graph/paging](https://docs.microsoft.com/en-us/graph/paging)

**Comment by AnjaniChallamcherla** [comment]
Okay, Thank you
