### ISSUE TITLE
How to convert JSLink for New/Edit/Display form

### ISSUE THREAD

**Issue by lafe** [SharePoint/sp-dev-docs#4463]
How can a JSLink be converted to the modern approach, so that its customization for the New, Edit and Display form are shown in the new edit panel. As far as I can tell, SPFx does not allow this customization and there seems also to be no way to replace the content of the panel itself or to inject code there. Unfortunately, PowerApps is also not an option due to the complexity of the field logic/rendering as well as license restrictions (we have the requirement to only use SharePoint online Plan 1 which just includes SharePoint and OneDrive). From my point of view, we are currently stuck with JSLink, because SPFx is not powerful enough, but I would be glad to be proven wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037437d9-e752-4c2a-4817-33e89daed5f9
* Version Independent ID: b748c4b5-b449-22f3-e375-e519a8c44928
* Content: [Tutorial - Migrating from JSLink to SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions)
* Content Source: [docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PopWarner** [comment]
This is correct for the current state. The Field Customizer extension does not support at this time the new/edit override capability that classic jslink does. 

PowerApps has been a replacement for that to date, but there is a request for SPFx customization of the new/edit forms. 

You can help that request by voting for it here UserVoice:
 https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37169995-allow-us-to-develop-custom-modern-forms-with-custo

I’d definitely keep an eye there as Microsoft is very good about keeping the UV entries updated.
