### ISSUE TITLE
Can I grant more specific permissions to the application instead of Site.FullControl.All ?

### ISSUE THREAD

**Issue by sjtuxzq** [SharePoint/sp-dev-docs#4464]
Can I grant permission on, like site level, to the application? Currently, if I understand correctly, all sites under my tenant will be accessible to the application if Site.FullControl.All permission is granted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unfortunately no, your current understanding is accurate.
