### ISSUE TITLE
Trigger Flow requires a Premium Flow license

### ISSUE THREAD

**Issue by kylepdx** [SharePoint/sp-dev-docs#4467]
It would be good to note in the Trigger Flow section that the Flow will require a premium license since it is required to use the HTTP trigger. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Toonshorty** [comment]
Would there be any scope for the creation of a new non-premium trigger, isolated to site designs?
'When a site design is applied' for example?

**Comment by bcameron1231** [comment]
@Toonshorty Yes. Or just a Flow Trigger for 'When a site is created' would also suffice. 

I've ended up not using Flow, and instead using Logic Apps. It's far cheaper to use Logic Apps and they can be used in the "TriggerFlow" site script action.

**Comment by andrewconnell** [comment]
While I appreciate the comment, IMHO licensing isn't a dev issue that should be pointed out. In other places in the docs, it refers to using Azure Functions, but it doesn't go into the licensing / costs on it.
