### ISSUE TITLE
Office-ui-fabric-react in GA

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#447]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
Guys, first of all congrats with the GA release. Great job!

In the Release Notes, there is this line:

> We have temporarily removed office-ui-fabric-react from the react template until we can get the package moved to a future-proof form. We expect that to take a couple of weeks.

What does this mean exactly? Can we no longer use it in React webparts (for now)? Or should we simply include the package ourselves when developing? And does this also mean we can include any version we want for now?

Thanks, and again: awesome job!

**Comment by manishgarg1** [comment]
Hi @NickSevens, we are about publish a more detailed advisory and the plan around office-ui-fabric-react soon. Will let you know when that is available.

**Comment by NickSevens** [comment]
Thank you for the update @manishgarg1.

**Comment by jonathanhotono** [comment]
I managed to include and use fabric react on sp framework however encountered issue on including fabric components css.
https://github.com/OfficeDev/office-ui-fabric-react/issues/1162

**Comment by NickSevens** [comment]
@manishgarg1 any update on this?
Thank you.

**Comment by manishgarg1** [comment]
Hi @NickSevens, we are working on documented guidelines how to use office-ui-fabric-react and office-ui-fabric in web parts. And also what are the options if you are not using React. Soon we should be able to share the white paper. Please note, due to global CSS all around and lack of native CSS scoping solutions in the browser, this is a non trivial problem.

**Comment by patmill** [comment]
Sorry for the delay.  Doc is here - https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/office-ui-fabric-integration.
