### ISSUE TITLE
.png is not displayed

### ISSUE THREAD

**Issue by hyoshioka0128** [SharePoint/sp-dev-docs#4472]
en-us:https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/custom-field-type-sharepoint-add-in
![custom-field-type-sharepoint-add-in_e](https://user-images.githubusercontent.com/40815708/63027748-7835e980-bee8-11e9-9f51-5febfc242314.png)

ja-jp:https://docs.microsoft.com/ja-jp/sharepoint/dev/solution-guidance/custom-field-type-sharepoint-add-in
![custom-field-type-sharepoint-add-in_j](https://user-images.githubusercontent.com/40815708/63027772-8552d880-bee8-11e9-8adc-2489a9b5f420.png)

same page: #3460
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efc70e7-88b1-0023-27bf-3d8b4568ef74
* Version Independent ID: f54e0d1d-673b-16c5-7065-cad7c754ec97
* Content: [Custom field type in the SharePoint Add-in model](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/custom-field-type-sharepoint-add-in)
* Content Source: [docs/solution-guidance/custom-field-type-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/custom-field-type-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by dplotnikov** [comment]
@andrewconnell should be fixed by my PR, please merge one
