### ISSUE TITLE
Add full list of people object lookup values

### ISSUE THREAD

**Issue by jshihadeh** [SharePoint/sp-dev-docs#4473]
Formatting people items is a fun activity and we often want to add other metadata fields. I could not find - on this page - a way to see the full list of People object lookup values / properties. Can you add a table that shows the full list? eg list here: https://social.technet.microsoft.com/wiki/contents/articles/31210.sharepoint-2013-get-user-details-from-person-or-group-field-using-rest-api.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Agreed, we should outline what fields are available.

The current properties available are

- id
- title
- email
- sip
- picture
- jobTitle
- department

If you'd like to make a PR, that would be great!

**Comment by bcameron1231** [comment]
@andrewconnell  #Please-Close 

The documentation referenced includes this.

![image](https://user-images.githubusercontent.com/7944457/67427157-ca565380-f598-11e9-9218-3f42b7e191ee.png)
