### ISSUE TITLE
Authentication Failure in Edge - AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint.

### ISSUE THREAD

**Issue by JBoman32768** [SharePoint/sp-dev-docs#4476]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Calling a secured Web API from a custom SPFx component should work in all supported browsers for users that have successfully logged into SharePoint.

#### Observed Behavior

Usage from the Edge browser fails in the following scenario - All other browsers unaffected.

Scenario:
 - Using Edge
 - Using Windows 10
 - The credentials used for SharePoint currently logged in user is NOT in the Windows Settings Account list
 - ADFS is in use on the SharePoint tenant (although it was not tested if it is necessary for repro)

In this scenario code fails with exception:

`AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint.`

SPFX then presents the user a Banner at the top of the page with the text: 
> To view the information on this page, you need to verify your identity.

Clicking on the banner takes the user through authentication screens but doesn't change the behaviour.

The following error can also be seen on the Edge console:
`SEC7134: Resource 'https://autologon.microsoftazuread-sso.com/de51b747-1916-436b-8f14-0dceea1db769/winauth/sso/edgeredirect?client-request-id=668ad028-e5f4-4359-92db-59a4c6264376&origin=login.microsoftonline.com&is_redirected=1&response_type=token&client_id=cd38b624-3c5e-487a-afac-7dacb0ac4f70&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2F<tenant>.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&state=fa09276c-2301-4050-ade9-648050280b8b%7Chttps%3A%2F%2Fgraph.microsoft.com&login_hint=<Correct User UPN>&x-client-sku=Js&x-client-ver=1.0.16&prompt=none' not allowed to load.`

Comparing Edge network traces when working versus not working we see that Edge is not submitting certain cookies to https://login.microsoftonline.com when the account is not also in Windows 10 settings
 - CkTst
 - SignInStateCookie
 - CcsSharedSignInState

Adding the account used for logging into SharePoint into Windows 10 Accounts then allows the SPFX webpart to function normally.

#### Steps to Reproduce

See above conditions in the observed behaviour.

**Comment by JBoman32768** [comment]
I realise there may be little that can be done from the SPFX side to fix this - except perhaps wait until Chromium-based Edge (tested as unaffected) is rolled out.

**Comment by cwdata** [comment]
We have seen this behavior in Microsoft browsers too when the relevant sites are not added to the "trusted sites" zone.
You could try adding
https://login.microsoftonline.com
https://yourtenant.sharepoint.com
to trusted sites.
If it works this could be rolled out org wide by using group policies.

**Comment by JBoman32768** [comment]
> We have seen this behavior in Microsoft browsers too when the relevant sites are not added to the "trusted sites" zone.

Yes - I saw other issues talking about this and we tried adding the sites to the Trusted Sites in IE11, but found it didn't appear to influence this behaviour in Edge.  Bring on the Chromium based Edge! Any ideas when will the rollout will be?

**Comment by lucabandMSFT** [comment]
did you change the "trusted sites" option from Control Panel? if not, can you try that?

**Comment by JBoman32768** [comment]
> did you change the "trusted sites" option from Control Panel? if not, can you try that?

Yes - Trusted sites had no effect on Edge behaviour in my testing.  The thing that fixed it was adding the account to the Windows 10 Settings, and accepting AAD policies be applied to my machine.  

Other browsers (Including IE11) were unaffected.

![Win10Settings](https://user-images.githubusercontent.com/8730120/65555514-0bdcea00-df6c-11e9-94fe-fff5fe2d01dc.png)
