### ISSUE TITLE
date formatting in spfx

### ISSUE THREAD

**Issue by alwaysrcorliss** [SharePoint/sp-dev-docs#4477]
Hi,

Within the first tutorial, you outline how to fetch and display some various columns: text, choices, multiple lines, and booleans.  But you don't go over dates.  
If I call a date such as Modified date I get:
"2019-08-12T03:19:38Z"

I've made attempts at trying to format this to a simple "MM-dd-YYYY" format but with no luck.  I've installed moment.js and tried to format by doing something like:
`<div>moment(${item.Modified},"MM-dd-YYYY")</div>` in my render method but that doesn't seem to be correct as nothing changes or I literally get the function call as a literal string.

Can someone help point me in the right direction as to how this should be handled in Typescript?  I'm just very new to this and would appreciate some direction since your documentation doesn't really cover dates and this seems really important.

**Comment by bcameron1231** [comment]
In order to evaluate the moment expression, you need to the move your curly braces to the outside

`<div>{moment(item.Modified).format('L')}</div>`
