### ISSUE TITLE
Cannot select empty field on lookup

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4478]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Expanding a lookup field where multiple selections is enabled, and the expanded field on the lookup item is null, omits the field.

#### Observed Behavior

An HTTP 5000 error is returned. 

For example, the error message is `Cannot get value for projected field Assigned_x005f_EMail.`, where `Assigned` is a "Person or Group" column and `EMail` is the user's email address. This occurs if the user has no mailbox.

#### Steps to Reproduce

- Create a list with a single additional column
- Create a single item in the list, with the title field set and *leaving the additional column blank*
- Create a list with a lookup column to the first list which allows multiple selections.
- Create a single item in the list with the lookup field set.
- Send a request to `_api/web/lists/getByTitle('SecondList')/items?$select=Lookup/AdditionalField&$expand=Lookup`

OR

- Create a list with a single user field which allows multiple selections
- Create a single item. Add a user to the users column *which does not have a mailbox*
- Send a request to `_api/web/lists/getByTitle('List')/items?$select=Users/EMail&$expand=Users`

**Comment by JakeStanger** [comment]
To follow this up in case anybody encounters the same issue, you're better selecting `Users/UserName`, which is their login email. This will always exist, unlike the mailbox address.

Obviously this is still a bug that needs reviewing and fixing. Selecting optional fields on regular multi-lookups is an impossibility.

**Comment by CPritch** [comment]
@andrewconnell also having the same issue here. Can't select a multi-value lookup due to several items having a null value. This adds tons of time to develop workarounds. This worked fine with CAML but seems to have been a repeat issue with REST from some initial research.

**Comment by Dayof** [comment]
Also having the same issue! I tried to lookup person/group column in a SP list but some groups just have e-mail, I would like to be able to get other data even if some group doesn't contains every value.

**Comment by Snoemannen** [comment]
Anyone found a workaround for this issue?
Need to get email from a person field in a list with around 20000 items but for a few persons the email field is blank and I would like to have it just return null in the column for those items but now the whole request fails like in the original post.

**Comment by Dayof** [comment]
My workaround was using **RenderListDataAsStream** (further information : https://blog.octavie.nl/index.php/2018/03/30/getting-term-label-values-with-the-sharepoint-renderlistdataasstream-api-endpoint) :

This is the way I call it :  

```js
function getListItem(url, listTitle, itemID) {
        itemID = itemID || false
        var newUrl =  url + "_api/web/lists/getbytitle('" + listTitle + "')/RenderListDataAsStream",
            payload = {}
        
        if (itemID) payload = { parameters: 
                                    { RenderOptions: 2, 
                                      ViewXml: '<View> \
                                                <Query> \
                                                    <Where> \
                                                        <Eq> \
                                                            <FieldRef Name="ID"/> \
                                                            <Value Type="Number">' + itemID + '</Value> \
                                                        </Eq> \
                                                    </Where> \
                                                </Query> \
                                            </View>' 
                                    }
                                }
        var options = { 
            url: newUrl, 
            method: "POST",
            payload: payload
        }
        
        return callAJAX(options)
    }

function callAJAX(options) {
        var headers = options.headers || {},
            asyncStatus = "asyncStatus" in options ? options.asyncStatus : true
        headers["Accept"] = "application/json;odata=nometadata"
        var ajaxOptions =
            {
                async: asyncStatus,
                url: options.url,
                type: options.method,
                contentType: "application/json;odata=nometadata",
                headers: headers
            }

        if (options.method == "POST") {
            var data = post(options, ajaxOptions)
            console.log(data)
            return data
        }
        return $.ajax(ajaxOptions)
    }
```

**Comment by JakeStanger** [comment]
@andrewconnell Since this seems to be an issue with the API since 2013 and not a developer issue, would you like me to close this issue and create a uservoice for it instead?

**Comment by andrewconnell** [comment]
Personally, that's my take as I think it will have the best chance at results. 

It's hard to convince someone there's been an existing bug for 6+ years... it's more "by design" at this point so you're looking at a change request IMHO... and that should go to UV.
