### ISSUE TITLE
Need to read User Profile Properties in SharePoint Online

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [SharePoint/sp-dev-docs#4489]
## Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,

I have to read all the properties (default and custom properties) of users in my SharePoint Tenant

With reference to https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/read-or-update-user-profile-properties-sample-app-for-sharepoint I can read one user profile in one call (clientContext.ExecuteQuery()).

But I have 10,000 users, so should I make 10,000 calls to get each user profiles and is it safe to do so? or is there any other way to get all user profiles in one call?

Please suggest.

Thanks in advance

**Comment by bcameron1231** [comment]
Can't say for sure what is the most performant. It's possible you'll get throttled anyways.  Might I ask what the requirement is for needing to pull all profiles and all properties at once?

When accessing many user profiles, I like to use SharePoint Search REST API (requires mapping managed properties for some user profile fields), but you can execute a single request and select the properties you want in a more efficient way.

**Comment by AnjaniChallamcherla** [comment]
@bcameron1231 
Thanks for the response.
The requirement is I have to update each users custom properties in SharePoint User profile with user properties in Azure AD. I am able to get all users in Azure AD through Graph (https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)

**Comment by bcameron1231** [comment]
Have you taken a look at the Bulk Update API?

https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online

**Comment by AnjaniChallamcherla** [comment]
Yes, I saw.
But before update I should check existing values in SharePoint User profile, so I must get all users before using api

**Comment by AnjaniChallamcherla** [comment]
I am able to get all user profile properties using SharePoint search REST API as suggested by @bcameron1231.
Below is my search query which I looped till I get total users:
RESTURL = "{0}/_api/search/query?properties='SourceLevel:SPSiteSubscription,SourceName:Local People Results,EnableMultiGeoSearch:true'&selectproperties='AccountName,WorkEmail,FirstName,PersonBrand,LastName,PreferredName,PictureURL'&rowlimit=500&startrow=" + getUsersCount + "& trimduplicates=false&querytext='*'";
