### ISSUE TITLE
use of old @microsoft/sharepoint versions

### ISSUE THREAD

**Issue by dcu-sharepoint** [SharePoint/sp-dev-docs#449]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

can we go back and forth between versions of the @microsoft/sharepoint  versions in case we need to test or review any material in an old version or drop before RC0 or V1.0?

Thank you and congrats on your v1.0 release; happy times for all of us.....

**Comment by patmill** [comment]
So for the next while, you can continue to build using the previous yeoman generator / references.  At runtime, the hosted workbench, the modern pages and the classic pages will load the most recent framework code - independent of what was used at build time.  They are backward compatible.  I'm in the process of writing up a post on how the versioning works.

**Comment by dcu-sharepoint** [comment]
Thanks Pat.
