### ISSUE TITLE
SharePoint OnPrem 2013 and 2016 CSWP's show no data when server side rendered for Google after patch

### ISSUE THREAD

**Issue by EricCantrell** [SharePoint/sp-dev-docs#4491]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When On Prem Public-facing SharePoint displays a CSWP to Google/Bing/etc, it uses an XSL transform server-side instead of JavaScript client-side to display the data.

Also, if you download a CSWP's XML file, and change the AlwaysRenderOnServer property from False to True, it uses that XSL server-side transform for everybody.

#### Observed Behavior

One of the patches, from October 2018 to February 2019 (inclusive) breaks this functionality, and an XSL server-side transform's show no data.

The KQL query does return results when you edit the web part, but the web part displays nothing for output.

This is affecting everybody that is running SP 2013 and 2016 on-prem public facing, and it means that all CSWP's show no data when google/bing/etc looks at them, which means it will never show up in search results.

We were able to replicate this on SharePoint 2013 and 2016.  We do not have a 2019 farm so were unable to test there.

We did have Microsoft tech support confirm this bug. We opened a ticket with MS March 6.  Ticket was closed March 20 and listed as a confirmed bug related to a patch, but not fixed.  Support team answered 2 followup emails after closing regarding other patches in April, but then stopped responding.

Our case # was 119030623001877

For a demo of the issue, Please see this page
     https://www.cas.udel.edu/cas-it/utility/test
In the top left, we have a CSWP.  The KQL query gives us 1 result.
In the top right, we have a CSWP with the AlwaysRenderOnServer flag set to True.  The KQL query gives us 1 result BUT no data is shown.

#### Steps to Reproduce

Create a CSWP that shows data.
Download the web part.
Find this line: <property name=”AlwaysRenderOnServer” type=”bool”>False</property>
Change it to this: <property name=”AlwaysRenderOnServer” type=”bool”>True</property>
Upload that web part to a page
Save and view

**Comment by bcameron1231** [comment]
Sounds like you made the bug known through the proper channels, that's likely more than we can do here. If the product team knows it's a bug, my suggestion would be to keep trying to reach out to them on the status and/or see if you can get escalated.

**Comment by EricCantrell** [comment]
While we've talked to support on a few issues we've never needed to go further and the support team didn't give us a way to escalate.  We've asked but they've stopped responding to our emails.

Is there a way we can reach out to the next tier of support or the product team directly?

One person on twitter suggested we open a new ticket and reference the old one.  I can do that but I'm wary of the delays/timeline on that.

**Comment by EricCantrell** [comment]
I wanted to post this for reference to that recommendation
https://twitter.com/koskila/status/1161670057799421953
and now I think I see your name on one of the likes, so I'm going to get approval from my supervisor to start that process.
