### ISSUE TITLE
[SPLoaderError.loadComponentError]: Cannot find module "jquery"

### ISSUE THREAD

**Issue by burakgunay72** [SharePoint/sp-dev-docs#4495]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello,

I am trying to load the jquery library programmatically on my webpart .ts file.

This code works and loads jquery:

    import { SPComponentLoader } from '@microsoft/sp-loader';
    import * as $ from 'jquery';

    export default class HelloWorldWebPart extends 
    BaseClientSideWebPart<IHelloWorldWebPartProps> {

    public render(): void {

    SPComponentLoader.loadScript('//code.jquery.com/jquery-3.4.1.slim.min.js', 
                             {globalExportsName: '$'});

But when I modify the loadScript code as follows

    SPComponentLoader.loadScript( '//code.jquery.com/jquery-3.4.1.slim.min.js',
    {globalExportsName: '$'}
    ).then(() => {
    alert($('a').length);
    });
 
I am getting the following error

   " [SPLoaderError.loadComponentError]: ***Failed to load component "c2e267f8-8b0c-47d5-ba20-ba7d151da675" (HelloWorldWebPart). Original error: ***Failed to load entry point from component "c2e267f8-8b0c-47d5-ba20-ba7d151da675" (HelloWorldWebPart). Original error: Error loading https://component-id.invalid/c2e267f8-8b0c-47d5-ba20-ba7d151da675_0.0.1 
Cannot find module "jquery" 

I think the cause of the problem is that the following code

    alert($('a').length);

is getting executed before the jquery library is fully loaded.

Any ideas on how this issue can be fixed will be appreciated.

Thank you.

**Comment by andrewconnell** [comment]
Take a look at this article from the SP docs... it demonstrates how to do this: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part

**Comment by burakgunay72** [comment]
Thank you Mr. Connell  but I already have that code with the accordion working.  It calls loadCSS,  not loadScript. I got the code in question from Sahil Malik's course on linkedin. It worked for him in his course video but I can't get it to work. I wish I had his email so I could ask him directly.

**Comment by andrewconnell** [comment]
My suggestion was more to not use the `SPComonentLoader` for loading the jQuery library, rather move that to a pre-req for the entire bundle. Look at the snippet right before this section in the doc: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part#build-the-accordion

This page also shows how to do it: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library#load-a-script-from-a-cdn

It uses the `externals` option in the **config.json** file. Change the URL to point the CDN reference. This will ensure jQuery is loaded on the page BEFORE your bundle is loaded.

**Comment by burakgunay72** [comment]
Thank you. The code below worked

SPComponentLoader.loadScript('https://code.jquery.com/jquery-2.1.1.min.js', {
          globalExportsName: 'jQuery'
        }).then(($: any) => {
          var jQuery = $;
          alert($('a').length);
}) ;

**Comment by andrewconnell** [comment]
Yes... use `externals` as that's what it's designed for.
