### ISSUE TITLE
Web part manifest json cannot be resolved

### ISSUE THREAD

**Issue by duquedennis** [SharePoint/sp-dev-docs#4496]
After the scaffolding, I opened the code via vs code, went to open the manifest json and the schema https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json cannot be resolved. Looks like it only worked when I changed it to 
https://dev.office.com/json-schemas/spfx/client-side-web-part-manifest.schema.json

Wonder what would be the side effect of pointing to this url with some difference in properties where the latter contains lesser property.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

![CannotResolveWebpartManifestJson](https://user-images.githubusercontent.com/54252594/63232547-6ee7ac80-c25b-11e9-838a-600e0788df37.PNG)

**Comment by GrahamMcMynn** [comment]
https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json  is the correct json file.  You should not be changing it to the one on dev.office.com (it is outdated and obsolete).  We are not seeing this issue.
