### ISSUE TITLE
Partial Page Load - ApplicationCustomizer not loading

### ISSUE THREAD

**Issue by tknaller** [SharePoint/sp-dev-docs#4497]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When navigating between Classic & Modern Pages I expect the ApplicationCustomizers to be loaded - meaning its onInit() to be called

#### Observed Behavior

onInit is not being called, therefore neither this.context.placeholderProvider.changedEvent nor this.context.application.navigatedEvent are working.

#### Steps to Reproduce

Steps to reproduce:

1. Deploy an extension to a site.
2. Navigate to task list or any classic page.
3. Navigate back to any list or library (with modern page) via Side Navigation which does a partial load (for example _layouts/15/viewlsts.aspx is always a full load and the issue cannot be reproduced - but a ListView like any AllItems.aspx is a partial load)
4. The extension won't load.

Also described here (Isuses already closed):
https://github.com/SharePoint/sp-dev-docs/issues/1042#issuecomment-497196583
https://github.com/SharePoint/sp-dev-docs/issues/1971#issuecomment-520399952

**Comment by tknaller** [comment]
as a workaround I am doing the following in a classic jslink, so that issue does not arise:
  $("a[onepagenavigationaction='1']").removeAttr("onepagenavigationaction");

**Comment by andrewconnell** [comment]
Can you comment if this is still the case? Many updates have been rolled out to the platform since this issue was submitted & ATM, I'm unable to repro this...
