### ISSUE TITLE
SPFx 1.9.1 AadHttpClient not working in SharePoint mobile app

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#4498]
#### Category
- [x] Bug

#### Expected or Desired Behavior
I'd expect the AadHttpClient to work in the SharePoint mobile app.

#### Observed Behavior
SPFx Webparts using the built in AadHttpClient class for accessing a 3rd party API are unable to access the API when executed in the SharePoint mobile app. I tested both Android and iOS.
SPFx version used: 1.9.1
SharePoint app on Android: 3.11.0
SharePoint app on iOS: 4.11.0
The same webpart works in the native mobile browser without issues.
As the SharePoint mobile app does not provide any kind of debugging console, I can't provide an error message. In the log stream of the Azure App Service (the 3rd party API) I can't see an error message either. It seems that the API is not being accessed at all.

#### Steps to Reproduce
Build a webpart using AadHttpClient and try to run it in the SharePoint mobile app.

If more details are needed please tell me how to find them.

**Comment by klaaslauwers** [comment]
I have the same issue with SPFx 1.7.1

**Comment by JeroenDerde** [comment]
Tested with 1.9.1: Still not working in the SharePoint App.
Does work in mobile browser when using option: open in browser from app.
@microsoft/generator-sharepoint@1.9.1
gulp@4.0.2
yo@3.1.0

**Comment by klaaslauwers** [comment]
Is there any pointer towards the solution? I've tried upgrading all dependencies but no luck so far.

**Comment by martinvillysson** [comment]
seeing the same issue in multiple spfx webparts as well

**Comment by achappey** [comment]
I was facing the same issues with spfx webparts, but was able to resolve with this solution:
https://github.com/SharePoint/sp-dev-docs/issues/4357#issuecomment-515131702

**Comment by cwdata** [comment]
Hi @achappey,
while that solution might work for internal use it is too complicated for apps that are sold to customers.

**Comment by andrewconnell** [comment]
There is a known issue with the AADHttpClient & the mobile app... MSFT is working on it (it's mentioned in another issue in this list I'm having trouble finding ATM). The workaround referenced in #4357 is a temp solution, but for now, it's the only solution @cwdata
