### ISSUE TITLE
Property pane scrollbar is missing

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#45]
If I have a lot of properties and groups with in a property pane page, and they do not have show as accordion configured, then the last property field is only half visible. 

![image](https://cloud.githubusercontent.com/assets/5854279/17837543/2f1fec46-67b6-11e6-9610-0148e0a6841d.png)

**Comment by waldekmastykarz** [comment]
👍 seen that too. Property pane should have a scroll bar if the contents are longer than window height.

**Comment by manishgarg1** [comment]
It is supposed to have a scrollbar. We will investigate what is going on. Thanx for the information.

**Comment by pgonzal** [comment]
VSO 239946

**Comment by srideshpande** [comment]
This is fixed and will be available in the next release.

**Comment by nickpape-msft** [comment]
Closing this issue as it was addressed in [Drop #2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2). Please reopen if necessary.
