### ISSUE TITLE
GA Documentation enhancement suggestion

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#450]
The [GA documentation](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-GA) states that you should uninstall the old SharePoint generator first and then install the new GA release. 
After re-installing the generator i still had the previous version.
This problem can be solved in two ways:

**Solution 1: Clear npm package cache**
```
npm cache clean
```

**Solution 2: append @latest**
```
npm install -g @microsoft/generator-simplestyle@latest
```

I used solution 1 to solve the problem but before that I always installed the generator from local cache.

**Comment by patmill** [comment]
Thanks Stefan.  I've updated the page accordingly.
