### ISSUE TITLE
Unable to hide Socialbar on site pages on modern communication site

### ISSUE THREAD

**Issue by ViralPatel1** [SharePoint/sp-dev-docs#4503]
While executing below commands I didn't encounter any issues. However the socialbar on modern pages still appear.

**Step 1-** executing below command.
Set-SPOSite -Identity <site> -SocialBarOnSitePagesDisabled $true

**Step 2**- executing below command. which shows the value seems do not changed.
Get-SPOSite -Identity <site> -Detailed | select SocialBarOnSitePagesDisabled

SocialBarOnSitePagesDisabled
----------------------------
                       False

Can anyone advice?

Thanks.

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
