### ISSUE TITLE
Generate multiple sppkg within the same project

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#4505]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have a spfx solution where I want to create multiple webparts. This works fine, but running `gulp package-solution` creates a single `.sppkg` file for all webparts. I'd like some more control over that, i.e. creating a single `.sppkg` for every webpart (or an arbitrary amount of webparts).
Is there already a way to add webparts to separate `.sppkg`s?

**Comment by andrewconnell** [comment]
That's not how the build toolchain is setup; one package is created per project as defined in the **config/package-solution.json** file. You'll need to create different projects.

It works the same as a .NET project... each project can generate a DLL / EXE. If you want to break it up more, you need multiple projects.
