### ISSUE TITLE
Apply default property setting to custom SharePoint SPFx webpart

### ISSUE THREAD

**Issue by gemini6609** [SharePoint/sp-dev-docs#4506]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The value of a new property specified in the manifest of a custom SharePoint SPFx webpart is expected to be applied to new and existing instances of the webpart after the installation or upgrade of the webpart on a SharePoint o365 installation.

#### Observed Behavior

The new property value specified in the manifest, is only applied if a new instance of the webpart is applied on a SharePoint page.  For existing instances of the webpart, the webpart must be reapplied and reconfigured in order for the manifest to set the property value.

Is this the intended behavior of the manifests in the SharePoint SPFx framework?  If so, would creating an appSettings.json and applying our property value there allow it to be automatically applied to existing instances of the webpart, or is there yet another way to do this?

**Comment by andrewconnell** [comment]
@gemini6609 said:
> Is this the intended behavior of the manifests in the SharePoint SPFx framework?

Yes, that's how it works. The values in the manifest are only used to set the public properties on the component when it is initially added to the page.

>  If so, would creating an appSettings.json and applying our property value there allow it to be automatically applied to existing instances of the webpart... 

No... that wouldn't work. 

> or is there yet another way to do this?

There's no capability that does this for you. You'll have to write something that finds all instances of the web part and changes the value.

Public properties on a web part are intended to allow for configuration. If you are updating the web part and want to change all values, then it doesn't make sense why it's configurable. Maybe instead implement something where it pulls the value from a central store, such as tenant properties if you are in SPO.
