### ISSUE TITLE
MSOL-powershell module to be deprecated

### ISSUE THREAD

**Issue by CTMSASnowfox** [SharePoint/sp-dev-docs#4510]
Hi as per the last two links all msol modules will be deprecated when functionality is available in newer modules - for this code new-azadspcredential as per https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadspcredential?view=azps-2.5.0. Any chance of this document getting updated to use the new modules?
https://docs.microsoft.com/en-us/powershell/module/msonline/?view=azureadps-1.0
https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in#feedback)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sorry, but I'm not clear on what you're saying. Can you elaborate?

**Comment by CTMSASnowfox** [comment]
[Image]
Hi Andrew,

Sorry for being unclear, let me try to elaborate.
The article points to use https://docs.microsoft.com/en-us/powershell/module/msonline/new-msolserviceprincipalcredential?view=azureadps-1.0 to change the SP credentials. However https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-1.0 states that the msonline family is being deprecated (see picture) so my request is you could update the documentation to use the newer New-AzADSpCredential.

Main reason is that a client I'm working with currently is hesitant to do anything no in the documentation, and using the msonline modules requires the use of azureRM conflicts with the newer AZ modules.

Makes sense?

Thank you in advance
Kristian Rickardt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrewconnell** [comment]
Following up... I've made MSFT aware of this and it's something they'll have to tackle as it involves them changing a guidance rec (_not something I can do on the docs without them being involved in this case_)

**Comment by CTMSASnowfox** [comment]
Hi Andrew @andrewconnell  have you heard anything?

**Comment by andrewconnell** [comment]
Nope... nothing to report.
