### ISSUE TITLE
[SPFX Extension] Find installed App from Custom Action

### ISSUE THREAD

**Issue by Zhephyr54** [SharePoint/sp-dev-docs#4511]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
I am currently trying to build an SPFX webpart to configure SPFX extensions such as Application Customizers and List View Command Set which work with Custom Actions.

I have successfully retrieved SPFX extensions related Custom Actions from my development tenant site. The next step I would like to take is to find the SPFX related App installed on the site from the Custom Action data in order to display the App title.  
I have currently tried to find the App by looking at (mainly looking for the Custom Action ClientSideComponentId buried in another property) :
- AppTiles using the REST API (filtering on AppPrincipalId not empty)
- Features using the REST API as I noticed that the App installation is creating a related feature on the site and also found an XML Relationship definition file related to this feature inside the SPPKG file
- Apps and AppInstances using Get-PnPApp and Get-PnPAppInstance from PnP PowerShell

Unfortunately, I couldn't find any way to link the Custom Action to the installed App from any metadata of the entities listed above in order to deduce the App title.

So if anyone can help me on this (@VesaJuvonen?), I would be grateful!

Thanks in advance.

**Comment by andrewconnell** [comment]
Unclear as to what you're trying to do... can you elaborate?

The custom action used to install the app customizer/command sets items points to a ClientSideComponentID. That's the ID of the component defined within the SharePoint package (SPPPK) that was used to install it.

**Comment by Zhephyr54** [comment]
@andrewconnell 
First of all, thanks for your answer.

What I am trying to do is to get informations about the installed App corresponding to a custom action from the custom action metadata (in the case of an app customizer/command sets SPFX extension).

I will elaborate by giving a concrete example.
Suppose that we just followed [this tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint) and that we installed the application customizer in a SharePoint Online site collection.

The deployment of this SPFX extension includes (among other things) a custom action and an App (app-extension-client-side-solution) that can be found in the site content. Now, suppose that I am getting this custom action metadata from the SharePoint Rest API :
```XML
<CustomAction 
        Title="SPFxApplicationCustomizer"
        Location="ClientSideExtension.ApplicationCustomizer"
        ClientSideComponentId="46606aa6-5dd8-4792-b017-1555ec0a43a4"
        ClientSideComponentProperties="{&quot;Top&quot;:&quot;Top area of the page&quot;,&quot;Bottom&quot;:&quot;Bottom area in the page&quot;}">
    </CustomAction>
```
Now, from those data, I want to know which installed App on my site is coming from the related SPFX extension. So, in our example, I would like to infer that the related App is **app-extension-client-side-solution**.

I hope that it helped clarifying my question.

**Comment by andrewconnell** [comment]
I'm not aware of an API that offers that information. 

The only option that comes to mind is to walk through the app catalog in the current context (site collection / tenant), download & expand the contents of the SPPKG files, and examine the manifest files they contain to find your ID. Assume that's not what you're looking for, but it would work.

With that being said, I've worked with a group that had an inventory step in their deployment process that registered the component ID+version & solution ID+version in a central store that let them look that information up.

**Comment by Zhephyr54** [comment]
Indeed, I was afraid that there was no simple way to get such information. The app catalog way should work even if it's quite an hassle, I don't see any other option.

Thanks a lot for your answer.
