### ISSUE TITLE
[MS Teams] SharePoint page not loading in personal tab of static app (MS Teams desktop client)

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#4512]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When adding a SharePoint page as a static tab in my custom personal app, I expect the page to render in the MS Teams desktop client.

#### Observed Behavior

The added SharePoint page is not loaded in the MS Teams **desktop** client, but works as expected in the **web** client.

_Also_, when switching to Developer Preview the tab starts to work. Even when switching _out of_ Developer Preview the web page _still_ loads as expected.

#### Steps to Reproduce

- Create a page in SharePoint online
- Create a new MS Teams app (e.g. in App Studio's Manifest editor)
- Add a new **Personal** tab, linking to the SharePoint page
- Install the MS Teams app (e.g. with App Studio's Test and Distribute)
- Open the MS Teams app
--> The SharePoint page is not loaded (nothing is shown, just a blank screen)

- Switch to developer preview (& sign in if needed)
- Open the MS Teams app
--> The SharePoint page is loaded correctly

- Switch **out of** developer preview (& sign in if needed)
- Open the MS Teams app
--> The SharePoint page is **still** loaded correctly

**Comment by NickSevens** [comment]
PS: it seems initially there is a redirect happening to /_layouts/15/Authenticate.aspx, which redirects to the MS login page. However, this redirect is not happening when the switch to or from developer preview has occured. So, it looks like initially MS Teams does not pass authenticated correctly?

**Comment by andrewconnell** [comment]
What are you doing in the SPFx component? Any chance it's something with **MSGraphClient** / **AADHttpClient**? 

If so, see #2521... you said it worked in web but not native clients, which is a known issue _so this smells like a dupe_...

**Comment by NickSevens** [comment]
@andrewconnell it happens with OOTB pages as well. (e.g. brand new communication site homepage, or empty news page, ...)
narrowed it down to SharePoint redirection to /_layouts/15/Authenticate.aspx - which in turn ends up redirecting to login.microsoftonline.com
This one has an x-frame-options = deny, resulting in the MS Teams Tab not able to render anything.
Seems like Teams auth is not passed on to the SharePoint page.

Weird thing is however that it works when doing a switch from "normal" to "developer preview", **or** "developer preview" to "normal" mode...

**Comment by andrewconnell** [comment]
Wait... sorry... I missed from your OP that this isn't a dev topic... you're just having trouble getting Teams to show content from SharePoint. 

Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
