### ISSUE TITLE
overriding tenant wide extension custom action on certain site collection

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#4514]
Is it possible to override tenant wide extension (application customizer) default custom action properties on certain site/site collection?

**Comment by andrewconnell** [comment]
No, not in what's provided. You could implement something within the code of the app customizer to look for something in the local site to see if it overrides the value passed in, but that's all custom.

**Comment by jonathanhotono** [comment]
Thanks.. just confirming before doing this custom bits.
