### ISSUE TITLE
List view Command Set extension stopped work

### ISSUE THREAD

**Issue by ivanvakhovich** [SharePoint/sp-dev-docs#4515]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

There is ListView Command Set extension on SPO site, which was deployed more then year ago. Yesterday(20.08) it stopped to work. Error is:

Error: There is no operation handler registered for '{"operation_4":["getItems_16","itemDetailsRow_546"]}'. 2 spofiles-mini-554118cb.js:1:291777
    n https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/spofiles-mini-554118cb.js:1
    e https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    c https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    r https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    runOnceMiddleware https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    loggingMiddleware https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    dispatch https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    getItems https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    t https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15
    t https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15
    __awaiter https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15
    __awaiter https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15
    getItems https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    r https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    runOnceMiddleware https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    loggingMiddleware https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    dispatch https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1
    a https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splistitemsscope-is-mini-8771809b.js:1

When I run gulp serve then I could see my buttons twice and everything works.

Tenant is in standard release.

#### Steps to Reproduce

Deploy List View Command Set to SPO site.

**Comment by ivanvakhovich** [comment]
There are also some records in console:

TypeError: Cannot read property 'indexOf' of null
    at new r (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.e._getServerRelativePath (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.e._getServerRelativeListUrl (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.e._getServerRelativeItemUrl (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.e._getFullItemUrl (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.e._getNormalizedItemUrl (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at t.get [as normalizedItemUrl] (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/splist-is-mini-e74f83b8.js:1
    at Object.P [as _notify] (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)
    at Object.enter (spoprod-a.akamaihd.net/files/odsp-next-prod_2019-08-09-sts_20190819.001/listviewdataprefetch-mini-2fe249c6.js:15)


GET https://<my tenant>.sharepoint.com/_api/v2.0/drive/apps?select=*%2Cpromoted&%24expand=actions 404

**Comment by ivanvakhovich** [comment]
I found that a problem is in onListViewUpdated method. It doesn't execute when one item selected. My buttons work when one item is selected. onListViewUpdated executes when several items are selected, but not only one.

**Comment by ivanvakhovich** [comment]
Update: Looks like no spfx code works when one item selected. I tried OOTB example from yo generator with with two commands. There are no buttons in list when one item selected. Weird. It was working during year and now it just stopped to work.

**Comment by AbhisheshPradhan** [comment]
public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const testCommand: Command = this.tryGetCommand('TestCommand');
    if (testCommand) {
      testCommand.visible = event.selectedRows.length === 1; 
    }
  }

The above code should render "testCommand" when only one row is selected.

**Comment by ivanvakhovich** [comment]
@AbhisheshPradhan , I wrote above that I tried OOTB sample and onListViewUpdated doesn't execute when I select one item in list. When I select second one - it executes. I also tried to delete onListViewUpdated method from extension, but buttons don't appear when one item is selected.

So, I really don't know why it happens. Everything works and suddenly it stopped. I think I have to do implement something instead of buttons.

**Comment by ivanvakhovich** [comment]
Today I found that same problem exists for another customer in another tenant. it was also working in production during more than year and now doesn't work.

**Comment by ivanvakhovich** [comment]
So, I found how to fix this stupid bug. I found that my extensions stopped works because there was List Id in RegistrationId in CustomAction. Then I replaced it with 101 and added some code to onListViewUpdated for filtering and everything works now.

**Comment by lucabandMSFT** [comment]
hey @ivanvakhovich , can you please confirm that the issue has now been resolved?
Thanks!

**Comment by ivanvakhovich** [comment]
Hi @lucabandMSFT. I fixed my problem using workaround above, but original problem is not fixed. Is it impossible to use list id for RegistrationId in CustomAction?

**Comment by patmill** [comment]
Hi there, very sorry for the delay in this, we dropped the ball.  Going through issues to make sure we haven't missed anything.  We are not currently able to reproduce this.  If it is still an issue, feel free to open a new bug and reference this issue, (or re-open this one)
