### ISSUE TITLE
Hello World Part does not work

### ISSUE THREAD

**Issue by Lurs** [SharePoint/sp-dev-docs#4516]
Chrome console says the following under https://localhost:4321/temp/workbench.html after the first "gulp serve" in the article: 
GET https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js net::ERR_ABORTED 404 (Not Found)
workbench.html:60 GET https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js net::ERR_ABORTED 404 (Not Found)
workbench.html:13 GET https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js net::ERR_ABORTED 404 (Not Found)
workbench.html:60 GET https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js net::ERR_ABORTED 404 (Not Found)
workbench.html:69 Uncaught TypeError: Cannot read property 'start' of undefined
    at workbench.html:69

I have node v10.16.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you provide a bit more context, like what version of SPFx you have installed at a minimum?

**Comment by Lurs** [comment]
Well I followed the instructions under https://docs.microsoft.com/de-de/sharepoint/dev/spfx/set-up-your-developer-tenant and https://docs.microsoft.com/de-de/sharepoint/dev/spfx/set-up-your-development-environment before. So I have installed NodeJS v10.16.3, Yeoman v3.1.0, Gulp v4.0.2 and the Yeoman SharePoint generator v1.9.1. Besides of that I did not install any Sharepoint Framework?
