### ISSUE TITLE
Building Your First Web Part Does not build anymore after V1.0

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-docs#452]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

In the instructions for HelloWorld WebPart "Connect to SharePoint" under the heading "Retrieve List Data" is the following code :-
```
<div class="${styles.column}">
  <span class="${styles.title}">
    Welcome to SharePoint!
  </span>
  <p class="${styles.subtitle}">
    Customize SharePoint experiences using Web Parts.
  </p>
  <p class="${styles.description}">
    ${escape(this.properties.description)}
  </p>
  <p class="${styles.description}">
    ${escape(this.properties.test2)}
  </p>
```

Unfortunately, styles.Column, styles.title, styles.subtitle, styles.description are not defined in HelloWorld.module.sccs So will not compile.

How do I fix this. If I try and use the RC0 version, then it fails to compile :-
.title {
 @include ms-font-xl;
 @include ms-fontColor-white;
  }

fails to compile - 
Error: no mixin named ms-font-l

           Backtrace:
            src/webparts/helloWorld/HelloWorld.module.scss:20
            on line 20 of src/webparts/helloWorld/HelloWorld.module.scss
    >>   @include ms-font-l;

How do I fix this ?(I suspect this may be due to pulling Office UI Fabric)

**Comment by VesaJuvonen** [comment]
Unfortunate typo, which is now fixed in the source article, also getting refreshed to dev.office.com soon. Here's the fixed html structure.

    this.domElement.innerHTML = `
      <div class="${styles.helloWorld}">
        <div class="${styles.container}">
          <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
            <div class="ms-Grid-col ms-u-lg10 ms-u-xl8 ms-u-xlPush2 ms-u-lgPush1">
              <span class="ms-font-xl ms-fontColor-white">Welcome to SharePoint!</span>
              <p class="ms-font-l ms-fontColor-white">Customize SharePoint experiences using Web Parts.</p>
              <p class="ms-font-l ms-fontColor-white">${escape(this.properties.description)}</p>
              <p class="ms-font-l ms-fontColor-white">Loading from ${escape(this.context.pageContext.web.title)}</p>
              <a href="https://aka.ms/spfx" class="${styles.button}">
                <span class="${styles.label}">Learn more</span>
              </a>
            </div>
          </div>
        </div>  
        <div id="spListContainer" />
      </div>`;

    this._renderListAsync();

**Comment by NPrice99** [comment]
Thanks Vesa – that worked successfully.
