### ISSUE TITLE
addSPLookupFieldXml where to put the values of the lookup field

### ISSUE THREAD

**Issue by CaseyRoot** [SharePoint/sp-dev-docs#4521]
The name of my field is Phase, how do I add the values to the field?  I'd like to have Phase field with a drop down - is lookup the right verb to use?
"schemaXml": "&lt;Field Type=\"Lookup\" DisplayName=\"Phase\" Required=\"FALSE\" EnforceUniqueValues=\"FALSE\" ShowField=\"Title\" UnlimitedLengthInDocumentLibrary=\"FALSE\" RelationshipDeleteBehavior=\"None\" ID=\"{101f1f89-d667-4c7f-9ebc-76cb5831d0a2}\" StaticName=\"Phase\" Name=\"Phase\" /&gt;",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Lookups are used to look up to another list in your site.  Sounds like you might be looking for a choice field?

Checkout the example on the page you linked
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema

**Comment by CaseyRoot** [comment]
I overlooked this, thank you for clarity.  I'm all set.
