### ISSUE TITLE
Spfx extension disappears from page

### ISSUE THREAD

**Issue by vkvikash337** [SharePoint/sp-dev-docs#4523]
I have created a spfx extension for my communication site, it is working perfectly when page is reloaded. When I click on search bar on the page then it takes me to the search page and when I return back to my page, my extension is not available on the page

Any idea how we can fix this?

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The extension should remain on page after returning from any navigation like search etc.

#### Observed Behavior
Extension disappears when navigated back to the page.

#### Steps to Reproduce
Deploy extension on communication site
Search anything using search bar, it takes to search page, then close the search page.
When returned to the page, the extension is not available

**Comment by OS-Lee** [comment]
Are you customizing modern communication site by Application Customizer?

I did test in my online environment while not reproduced.

Test result.

[https://1drv.ms/u/s!ArH29oxgtifigRAF3HKAV9JZJUTn?e=dSDUYq](url)

**Comment by vkvikash337** [comment]
For me the search bar is coming on the right side of the page, not in the center like yours. 

![image](https://user-images.githubusercontent.com/32191184/65238891-60f7a680-dafb-11e9-8b5a-20bdf633ca8e.png)

**Comment by kemesfun** [comment]
@vkvikash337 Is this still occurring? If so, can you share more information? (possibly a gif). I am not able to reproduce the issue using the search bar on the right or in the center.
