### ISSUE TITLE
Column Formatting will not stick on the "Title" column on a library

### ISSUE THREAD

**Issue by ferrety2006** [SharePoint/sp-dev-docs#4528]
I can preview and see the formatting be accepted for a moment, but after clicking save the formatting syntax is wiped out when I go back to view it. I tried to add the column formatting from the column settings via Library settings, but the same issue happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PopWarner** [comment]
Hi @ferrety2006. Could you share the column formatting definition you are trying to use? :)

**Comment by mberkeley** [comment]
Not stale.  This is a bug that needs to be addressed.
