### ISSUE TITLE
New build SharePoint App not able to add to site

### ISSUE THREAD

**Issue by LiveLikeCounter** [SharePoint/sp-dev-docs#4530]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A new added app to the App-catalog has to appear to a site in the collection.

#### Observed Behavior

The new app doesn't appear.

#### Steps to Reproduce

I did the following steps:
1. Created a new SharePoint webapp with the yo @microsoft/sharepoint
2. Build it with gulp package-solution, with the follow output (no errors):
[10:09:06] Project dev-sharepoint-webpart-fakedata version:0.0.1
[10:09:06] Build tools version:3.9.26
[10:09:06] Node version:v10.16.3
[10:09:06] Total duration:6.22 s
3. Upload the app to the catalog:
![image](https://user-images.githubusercontent.com/24720382/63577389-8e9a1000-c58e-11e9-8815-886ef5222f7a.png)
4. Add the app to a site:
![image](https://user-images.githubusercontent.com/24720382/63577469-c012db80-c58e-11e9-93f7-7689715a5180.png)
The webpart isn't there...
5. The app could either be added directly on a page as well.

#### Submission Guidelines

Just add everything in basic form.

**Comment by bcameron1231** [comment]
Did you first run?

`gulp bundle --ship`
then
`gulp package-solution --ship`

**Comment by LiveLikeCounter** [comment]
Hej,

No, at first I did not (the documentation did not say so). But now I did,
without errors :)

I did all the steps again (after I removed the app), but is still doesn't
show up :(


Met vriendelijke groeten,
Johan Walhout

**Comment by GrahamMcMynn** [comment]
Your app is tenant deployed.  That means it should not show up as it is available everywhere.  What do you mean it cannot be added on a page though?  Does it now show up in the webpicker?

**Comment by LiveLikeCounter** [comment]
Ah, that makes sense!
If looked again and tried to add the Webpart to a page.
Now I see the webpart:
![image](https://user-images.githubusercontent.com/24720382/64939823-83bb5e00-d862-11e9-9b30-830f882ec209.png)

Sorry for the inconvenience. Thank you for your help!
