### ISSUE TITLE
FieldCustomizer - InternalFieldName does not work, DisplayName does

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#4535]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The FieldCustomizer scaffolding generates a `serve.json` that looks like this:

```json
      "fieldCustomizers": {
        "InternalFieldName": {
          "id": "...",
          "properties": {
            "sampleText": "Value"
          }
        }
      }
```

It specifically says `InternalFieldName`, although only the DisplayName of the field works. 

#### Observed Behavior

I have a column called `MyField` (InternalName) with a title of `My Custom Field` (DisplayName). Using `MyField` as InternalFieldName, nothing happens when I run `gulp.serve`. When I change the field name inside `serve.json` to `My Custom Field` instead, it works.

**Comment by CPritch** [comment]
@GrahamMcMynn why was this closed? This is still an issue.

**Comment by GrahamMcMynn** [comment]
Sorry about that, I misunderstood your comment when you said you can confirm it is an issue on your end of things.

**Comment by andrewconnell** [comment]
Can you provide additional context? Which SPFx version, which environment, etc?

**Comment by johannes-z** [comment]
@andrewconnell  I used the latest version back then, which was, I believe, `1.9.1`, targetting SharePoint Online.

**Comment by CPritch** [comment]
This was not working correctly for me in both a Dev tenant and Production tenant in SPO. The served component only works for the title of a column rather than the internal name as described by all documentation.

**Comment by andrewconnell** [comment]
Confirmed...

**Comment by kemesfun** [comment]
@johannes-z I am not able to reproduce this issue. Let me know if you are still having this issue.

**Comment by jcoolsen** [comment]
I think that the missing piece here, is that this issue only happens in development mode. So there is a difference between how stuff works when developing and how it works when deployed.
