### ISSUE TITLE
Failed to load component dependency "@microsoft/sp-http" 

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#454]
I am facing below error while deploying HelloWorld WebPart to SharePoint online workbench

Failed to load component dependency "@microsoft/sp-http" from component "2679bc73-139a-4e0c-9222-b8f880e4dedb" (HelloWorldSpWebPart). script resources due to: {1}.

Can anyone please help?

![error](https://cloud.githubusercontent.com/assets/8310319/23365069/752947cc-fcf9-11e6-9717-ed33db0fefee.png)

**Comment by manishgarg1** [comment]
Hi @nanddeepn, is this web part built with SPFx GA bits or earlier bits?

**Comment by patrick-rodgers** [comment]
Seeing this as well, GA bits.

**Comment by manishgarg1** [comment]
Hi @nanddeepn / @patrick-rodgers , this is happening because PROD is not fully on GA bits. We are about to push that today. That should take care of this problem automatically.

**Comment by manishgarg1** [comment]
Hi @nanddeepn / @patrick-rodgers , this should be fixed now. Please reactivate the issue if it is not.

**Comment by nanddeepn** [comment]
Hi, Thank you for the quick fix. It is working now.

**Comment by syaifulamir** [comment]
i have same problem.. how to fix this case ? please
