### ISSUE TITLE
PowerShell text colour stays yellow after gulp package-solution

### ISSUE THREAD

**Issue by BassemNKhalil** [SharePoint/sp-dev-docs#4541]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug (minor)
- [ ] Additional article idea

#### Observed Behavior
> As in the screenshot, text colour for PowerShell stays yellow after gulp package-solution 
![Capture](https://user-images.githubusercontent.com/11630074/63748397-9f2eeb00-c8ec-11e9-9b1e-f665b4854218.PNG)

#### Expected or Desired Behavior
> Text colour for PowerShell should not change after executing gulp package-solution 

#### Steps to Reproduce
> Run gulp package-solution on a WebPart

**Comment by GrahamMcMynn** [comment]
Thank you for your submission. Please submit your feedback and suggestion using UserVoice at http://sharepoint.uservoice.com, so that we can take it into account in our future planning. Thank you for your input advance.

**Comment by BassemNKhalil** [comment]
Hi @GrahamMcMynn, if I understand correctly UserVoice is for feature suggestions while the above is more of a bug as it is an unexpected behaviour. I’d understand if you weren’t able to replicate or believe it to be related to my settings but it needs further inspection on your end before closing. Would you mind re-opening this one?

**Comment by GrahamMcMynn** [comment]
Hi @BassemNKhalil, it is for feature suggestions.  However, we are not going to investigate this bug as we didn't believe it met the bar for being investigated/fixed.  If you believe severity of the issue impacts you enough that you would like it fixed please report it on user voice and see if other people feel the same impact and upvote it.  Thanks for the submission and sorry that we are not investigating it.

**Comment by BassemNKhalil** [comment]
But that’s exactly the thing, if this not a feature then it belongs here @GrahamMcMynn. I understand that you may not plan to address it at this point but it belongs here still. The community looks at user voice for features and here for issues/bugs.

**Comment by GrahamMcMynn** [comment]
So what you're saying is you want the issue left open indefinitely?

**Comment by BassemNKhalil** [comment]
Not necessarily. If it happened to stay for a few months without activity, it can be closed. Alternatively, you’d either open source the framework so that the community can help with stuff like this or you’d eventually have a bug crush and get to it at some point.

The whole point is that closing something just because it’s minor is not a good message to the community and user voice is not the place for it.

**Comment by GrahamMcMynn** [comment]
Having people understand that we will not work on this is better than just having it left open indefinitely (or for 3 months untouched as we won't come back to it).  This is no different than when we had an on premises product and we let customers know that we wouldn't fix an issue.  No answer is/was always worse than a definite answer.  Sorry that this is not what you were hoping for.
