### ISSUE TITLE
SPFx Command Set not working for all lists defined in the elements 

### ISSUE THREAD

**Issue by joaoferreira** [SharePoint/sp-dev-docs#4547]
#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I've defined two Custom Actions in the elements.xml one for lists (100) the other for libraries (101)

```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="ShareItemToMicrosoftTeams"
        RegistrationId="100"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="96efbc30-8ddb-4352-b17e-6f0034df68d9"
        ClientSideComponentProperties="">
    </CustomAction>
    <CustomAction
        Title="ShareItemToMicrosoftTeams"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.CommandBar"
        ClientSideComponentId="96efbc30-8ddb-4352-b17e-6f0034df68d9"
        ClientSideComponentProperties=""> 
    </CustomAction>
</Elements> 
```

#### Observed Behavior

When the extension is globally deployed in the global app catalog the second custom action is not executed meaning that the the button never appears on document libraries.

As a workarround I had to duplicate the extension entry in the global extension lists to get the extension executed on lists and libraries

**Comment by patmill** [comment]
Sorry - this got lost in some metadata shuffle.  For the tenant-wide deployment, you'll want to update the ClientSideInstance.xml file, not the elements.xml file.
