### ISSUE TITLE
Unable to install dev-cert on my laptop

### ISSUE THREAD

**Issue by dankotsmith** [SharePoint/sp-dev-docs#455]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

I am trying to install the dev-cert on my laptop through powershell running as Administrator using v1.0 dev tools that shipped last week.  I am receiving a permissions error but not sure how that can be when running as Admin. Does anyone have any ideas on how to correct this issue.  I am running Windows 10.

[07:57:11] Using gulpfile C:\mydev\helloworld-webpart\gulpfile.js
[07:57:11] Starting gulp
[07:57:11] Starting 'trust-dev-cert'...
[07:57:11] Starting subtask 'trust-cert'...
[07:57:18] [trust-cert] Attempting to trust a dev certificate. This self-signed certificate only points to localhost and
 will be stored in your local user profile to be used by other instances of gulp-core-build-serve. If you do not consent
 to trust this certificate, click "NO" in the dialog.
[07:57:18] Error - [trust-cert] Error: root "Trusted Root Certification Authorities"
Signature matches Public Key
CertUtil: -addstore command FAILED: 0x80070005 (WIN32: 5 ERROR_ACCESS_DENIED)
CertUtil: Access is denied.

[07:57:18] Error - [trust-cert] Certificate trust failed with an unknown error.
[07:57:18] Error - 'trust-cert' sub task errored after 7.37 s
 "Error trusting development certificate."
[07:57:18] 'trust-dev-cert' errored after 7.38 s
[07:57:18]
[07:57:19] ==================[ Finished ]==================
Error - [trust-cert] Error: root "Trusted Root Certification Authorities"
Signature matches Public Key
CertUtil: -addstore command FAILED: 0x80070005 (WIN32: 5 ERROR_ACCESS_DENIED)
CertUtil: Access is denied.

Error - [trust-cert] Certificate trust failed with an unknown error.
Error - 'trust-cert' sub task errored after 7.37 s
 "Error trusting development certificate."
[07:57:19] Project helloworld-webpart version: 0.0.1
[07:57:19] Build tools version: 2.4.0
[07:57:19] Node version: v6.10.0
[07:57:19] Total duration: 13 s
[07:57:19] Task errors: 3

**Comment by patmill** [comment]
Hi @dankotsmith - I imagine this is the same issue as on StackExchange.  Can you give us any further information?
Is it possible that this is a work laptop and your IT department has a policy that denies you the ability to trust a cert?
@iclanton - Is there a way to do this manually and see where the error occurs?

**Comment by iclanton** [comment]
The code that generates and trusts the dev certificate is [here](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build-serve/src/certificates.ts).

While we're attempting to trust the certificate, it's written to the project's temp directory (see [here](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build-serve/src/certificates.ts#L232)), but if the trust fails we delete it. We also don't write the private key to disk unless the trust succeeds, so right now there's no easy way to do it manually with GCB on Windows. We can put together something that lets you trust the certificates manually, but that'll take some time.

However, if you generate and trust your own certificate, you can either specify it in your `serve.json` file (see [these properties](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build-serve/src/ServeTask.ts#L48-L61)), or you can drop `gcb-serve.cer` and `gcb-serve.key` files in PEM format in `<your-home-directory>/.gcb-serve-data/` (see [this code](https://github.com/Microsoft/web-build-tools/blob/master/gulp-core-build-serve/src/CertificateStore.ts#L82-L88)).

**Comment by dankotsmith** [comment]
@iclanton  I placed the .cer and .key file in the suggested location and the error goes away however I still get the untrusted site warning error when I debug.  I am guessing I created the .cer and .key incorrectly.  Any documentation on how to create those?

@patmill - Yes this is the same issue on StackExchange.  It is a work laptop, but IT assures me they have no policies on trusting certs. Although that doesn't mean I believe them.  Is there a way for me to check?  I seem to remember having issues using fiddler as well because of an untrusted cert issue.

**Comment by patmill** [comment]
What browser are you using?  I found that Edge keeps giving me grief, while Chrome / IE / etc. works fine.

**Comment by iclanton** [comment]
You can trust the cert by running `certutilExePath -user -addstore root <cert path>` as an administrator.

You also should be able to double-click on the certificate and click "Install."

**Comment by seaSide974** [comment]
Also ensure you are into your SP Project folder before running that command

**Comment by iclanton** [comment]
Did you get this working? Please reopen the issue if you didn't.

**Comment by dankotsmith** [comment]
I was able to get this working.  Thanks
