### ISSUE TITLE
SharePoint API for getting /GetSharingInformation is not resulting in share info 

### ISSUE THREAD

**Issue by yuvarajp1515** [SharePoint/sp-dev-docs#4551]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Used API: <site_url>/_api/web/Lists(@a1)/GetItemById(@a2)/GetSharingInformation?@a1=(‘parent_id’)&@a2=(‘id’)&$Expand=permissionsInformation,pickerSettings

#### Expected or Desired Behavior
Calling from UI is responding with valid info :
![1](https://user-images.githubusercontent.com/37432927/63832136-c984b500-c98d-11e9-9765-d8f707b36a20.png)
![2](https://user-images.githubusercontent.com/37432927/63832141-cc7fa580-c98d-11e9-8caf-1c13347b4b11.png)

#### Observed Behavior
But when raw API is made then we do  not get valid info ( result is empty)

With headers:
Authorization:Bearer <token>
Content-Type:application/json;odata=verbose
Accept:application/json;odata=verbose

Body;
{"request":{"populateInheritedLinks":true}}
![3](https://user-images.githubusercontent.com/37432927/63832204-ede09180-c98d-11e9-86d5-195c48fbc68c.png)

![Screenshot from 2019-08-28 12-21-05](https://user-images.githubusercontent.com/37432927/63832395-59c2fa00-c98e-11e9-963c-c33b02ba24b9.png)

#### Steps to Reproduce
Executed the above API

**Comment by andrewconnell** [comment]
Sorry, but I'm not clear what is missing from your pictures. Also, what are you using for the access token (how did you obtain it)?
