### ISSUE TITLE
News repost unavailable, but it does work

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#4552]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

On some tenants `/_api/sitepages/pages/reposts/iscontenttypeavailable` returns `false` while the "Repost page" contenttype is there. How does Sharepoint determine this state?

Because of this the news webpart cannot repost, it shows a message "The contenttype Repost page is missing" (or something like this). If I use Fiddler to replace this `false` response with `true` the news webpart works fine.

So it seems there's nothing wrong with the contenttype, but the API somehow thinks there is.

**Comment by andrewconnell** [comment]
Not clear what you're asking... are you saying there's an issue with the News web part?

**Comment by RoelVB** [comment]
On some tenants `/_api/sitepages/pages/reposts/iscontenttypeavailable` returns the incorrect status.

As a result, the news webpart doesn't fully work.

**Comment by andrewconnell** [comment]
In that case, that's more of an OOTB product issue that can't be addressed here.

Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
