### ISSUE TITLE
Generator 1.9.1 doesn't support '--component-type library'

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4554]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It should be able to use `--component-type library` as argument of the generator.

#### Observed Behavior

When the generator gets executed with the following command option:

```sh
yo @microsoft/sharepoint --component-type library --framework react
```

The result is  the following:

<img width="637" alt="Screenshot 2019-08-28 at 22 59 49" src="https://user-images.githubusercontent.com/5503835/63892302-9707a600-c9e7-11e9-9ca6-a9879205fb0f.png">

#### Steps to Reproduce

Execute the following command line with the @microsoft/generator-sharepoint@1.9.1 installed.

```sh
yo @microsoft/sharepoint --component-type library --framework react
```

**Comment by kemesfun** [comment]
@StfBauer That command doesn't work since there is no framework prompt for library component. 
``yo @microsoft/sharepoint --component-type webpart --framework react``  works since there is a component type of webpart and a prompt for framework. This is working by design.
