### ISSUE TITLE
[Suggestion] streamline new webpart generation with less questions

### ISSUE THREAD

**Issue by BassemNKhalil** [SharePoint/sp-dev-docs#4556]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Context
> When generating a new webpart, I'm asked for solution name (which as far as I can tell is only used to create folder if I don't use the existing current folder). Instead, I'd like to be asked first which folder I'd use and if I elect to use the current folder, no prompt for solution name needs to be shown. Same goes for component type when I'm targeting SP16 as that's the only option. WebPart Description can be skipped entirely and it is editable afterwards anyways. That's 3 questions instead of 6.

> I understand the generator can be parametrised but for beginners, this is an unlikely scenario. I'm also yet to see a demo where the generator is invoked with parameters not directly as a step wizard but that might just me 😄.

#### Observed Behavior
>**What is your solution name?**
_mysolution_
**Which baseline packages do you want to target for your component(s)?**
_SharePoint 2016 onwards, including 2019 and SharePoint Online_
**Where do you want to place the files?**
_Use the current folder_
Found npm version 6.9.0
**Which type of client-side component to create?**
_WebPart_
Add new Web part (on-prem) to solution _mysolution_.
**What is your Web part (on-prem) name?**
_FormsWP_
**What is your Web part (on-prem) description?**
_Sample WP for Forms_

#### Expected or Desired Behavior
>**Where do you want to place the files?**
_Use the current folder_
No need for solution name now that I've selected current folder
~~>**What is your solution name?**~~
~~_solution name_~~
**Which baseline packages do you want to target for your component(s)?**
_SharePoint 2016 onwards, including 2019 and SharePoint Online_
Found npm version 6.9.0
Since we're building for SP2016, WebPart is the only option - skip component type as well
~~**Which type of client-side component to create?**~~
~~_WebPart_~~
Add new Web part (on-prem) to solution _solution name_.
**What is your Web part (on-prem) name?**
_FormsWP_
Skip description as well - not the most important property and usually skipped
~~**What is your Web part (on-prem) description?**~~
~~_Sample WP for Forms_~~

**Comment by andrewconnell** [comment]
Thanks, but this would fall into a feature request as the generator is working by design. These feature request / changes should be posted to User Voice, not this issue list. Thanks!

**Comment by BassemNKhalil** [comment]
For reference: https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38485852-streamline-new-webpart-generation-by-asking-fewer
