### ISSUE TITLE
SharePoint List view command bar Flow set a reminder not working

### ISSUE THREAD

**Issue by veerasekarmeiyappan** [SharePoint/sp-dev-docs#4559]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I click the "Flow" --> "Set a reminder" --> "Due Date" option available in SharePoint List command bar it should redirect to Microsoft Flow site opened with "Set a reminder" template in edit mode

#### Observed Behavior

When I click the "Flow" --> "Set a reminder" --> "Due Date" option available in SharePoint List command bar it is not redirecting to Microsoft Flow site with "Set a reminder" template in edit mode. It does nothing I am still on my SharePoint online site list view page only. No errors on console or on screen.

#### Steps to Reproduce
- In a SharePoint Modern Team Site create a new List
- Create a new date field named "Due Date". Created with OOTB date field settings, no changes made
- Now in the list view command bar under "Flow" the "Set a reminder" option was available with my new "Due Date" field
- But when I clicked "Due Date" in "Set a reminder" floating menu nothing happened
- No window redirection, I still stay in my SharePoint list view screen itself. Did not get any error in Console or on screen
- But the "Create a flow" option works. Only the default "Set a reminder" is not working as expected.

#### Submission Guidelines
Sure this is not a big bug as it has worked earlier for many users, may be a regression bug.
![FlowSetReminderIssue](https://user-images.githubusercontent.com/50662144/63934806-116e0f80-ca54-11e9-9e34-bb18fd96c6e1.jpg)

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
