### ISSUE TITLE
Multiple SPFx webpart on a Teams Tab

### ISSUE THREAD

**Issue by AriGunawan** [SharePoint/sp-dev-docs#4563]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi, I see that it's possible to create a Teams Tab using SPFx ([docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)).
Is it possible to have multiple SPFx webpart (from one solution) on a Teams Tab?
Thanks.

**Comment by VesaJuvonen** [comment]
Not directly using the SPFx model, but you can absolutely have a page in SharePoint with multiple web parts and then surface that in Microsoft Teams. Currently though for web part and SPFx model, we only support usage of single web part as a tab, which is something to consider in your implementation.

**Comment by AriGunawan** [comment]
@VesaJuvonen , thanks for your response.
I already have the page with multiple web parts. I just want to know the possibilities on other implementations. Thanks!
