### ISSUE TITLE
Error AggregateException in createcopyjobs and move button

### ISSUE THREAD

**Issue by magonzalezm** [SharePoint/sp-dev-docs#4564]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I use the button "move" or "copy" to copy files between subsites. It works when moving withing the same site, but not from the root site to any subsite.

#### Observed Behavior

It returns the following error:
![image](https://user-images.githubusercontent.com/37692947/64016705-fa005680-cb27-11e9-987e-7317fd731ace.png)

And in the UI:
![image](https://user-images.githubusercontent.com/37692947/64016783-2c11b880-cb28-11e9-94a2-eddfaae2b8ca.png)

I have create new subsite and new library, and try, but it continues returning the same error.

#### Steps to Reproduce

Push the button "move" or call the service CreateCopyJobs.

**Comment by RoelVB** [comment]
Can we make this high priority somehow?!

As of today we're seeing this error on multiple tenants. Our customers business processes depend on this functionality.

**Comment by RoelVB** [comment]
We're experiencing the same issue on standard release and targeted release tenants.

**Comment by VesaJuvonen** [comment]
Which copy and move we are talking here? If this is copy and move buttons visible in the UI, then this is a wrong forum to report the issue as we can only provide support for dev topics. All issues with the out-of-the-box capabilities should be reported through tenant admin support channels, which apparently @RoelVB has already done.

Can you confirm the if the issue is around oob buttons or with APIs. Thx.

**Comment by RoelVB** [comment]
@VesaJuvonen 
The problem is with the API.
We have a custom webpart which calls the createCopyJobs API gets this error as of today.

**Comment by magonzalezm** [comment]
I confirm you it happens too with the web service:  _api/site/CreateCopyJobs, and surely the API.

**Comment by VesaJuvonen** [comment]
Got it - so you had some code to run the operation. Any change you can share the code as that would significantly reduce the investigation time on our side? If issue is only on the API layer and NOT on the oob capabilities, then standard O365 support cannot help on this as they do not provide support for dev topic. 

If you can however reproduce the same issue with oob buttons (kind of indicated above), they can provide support with agreed SLAs, which is certainly the fastest way to get anything fixed.

**Comment by RoelVB** [comment]
The oob buttons show the same error (since they're calling the same API).

If still necessary I could see if I could create some example code.

**Comment by VesaJuvonen** [comment]
Like said - as this is then an issue on the oob capabilities, getting it moving through standard support channels is absolutely the right model. We cannot provide support support for oob capabilities through this channel based on our internal agreements and anyway getting someone to investigate the issue in API level through this channel would take days or more.

Now - as this is reproducible by using oob buttons - that means that it's a real issue on the oob capabilities and standard support can deal with it. 

This is not to reduce the urgency on your issue, but rather to provide you some additional transparency on our internal processes and available resources.

**Comment by RoelVB** [comment]
Thank you for your prompt response.
I'll wait for a reply from the Office365 support team.

**Comment by RoelVB** [comment]
Got a call from the support team. They're working on it. It will be resolved "as soon as possible".

**Comment by VesaJuvonen** [comment]
Thanks for following up on that @RoelVB. Let's keep this open until they provide a "fixed" status or we can see that the APIs are working. This way others who might be running in to this, can see where we are heading.

**Comment by magonzalezm** [comment]
I can see it has been solved, and now files can be moved to subsites without any problem. 
If you have any more info about it, @RoelVB  / @VesaJuvonen, please add more comments.
Thx both of you for the help.

**Comment by RoelVB** [comment]
I didn't hear anything from Microsoft, but it seems the problem was resolved.
