### ISSUE TITLE
gulp trust-cert-dev access denied problem

### ISSUE THREAD

**Issue by kkyim1** [SharePoint/sp-dev-docs#4565]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Hello,

I am trying to create a spfx Hello World web part on Windows 10 Professional and when I run "gulp trust-cert-dev" command, I received "Trusted Root Certification Authorities" (under Certificates - Current User) access denied problem.

My machine is connecting to company domain and I believe a Group Policy Object is setup to cause the issue. 

I installed the invalid certificate (gulp-connect) into "Trusted Root Certification Authorities" (under Certificates (Local Computer)). The certificate's status showed OK (In Certificate panel)  but IE and Chrome still showing "Certificate Error".

Can someone guide me to create a localhost self-signed certificate for SharePoint Framework by using Powershell? (Like using New-SelfSignedCertificate cmdlet). I researched on the Internet and the solutions that I found don't work for me.

Thanks for your help.

Ken

**Comment by nanddeepn** [comment]
Hi @kkyim1 ,
Please see if this helps: https://www.sharepointed.com/2018/04/sharepoint-spfx-gulp-trust-dev-cert-error/

**Comment by PrasantiKintali** [comment]
Hi @kkyim1,

will get this issue when your corporate proxy is restricting to execute the gulp, to over come this the below commands needs to be executed.

npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
npm config set strict-ssl false
npm config set unsafe-perm true 

8080 is the sample proxy, this needs to be replaced with your organization proxy number.
to find proxy : go to internet options -> lan settings  in proxy server  u will find it

refer to  : https://jjasonclark.com/how-to-setup-node-behind-web-proxy/
