### ISSUE TITLE
Documentation is Incorrect

### ISSUE THREAD

**Issue by araver** [SharePoint/sp-dev-docs#4567]
Site Create example needs to be wrapped in a "request" property e.g.
```json
{
    "request": {
      "Title": "Communication Site 1",
      "Url":"https://contoso.sharepoint.com/sites/commsite1",
      "Lcid": 1033,
      "ShareByEmailEnabled":false,
      "Classification":"Low Business Impact",
      "Description":"Description",
      "WebTemplate":"SITEPAGEPUBLISHING#0",
      "SiteDesignId":"6142d2a0-63a5-4ba0-aede-d9fefca2c767",
      "Owner":"owner@yourtenant.onmicrosoft.com"
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest#feedback)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you. I have submitted a PR to fix this issue.
