### ISSUE TITLE
Clarify this with examples

### ISSUE THREAD

**Issue by pmoricz** [SharePoint/sp-dev-docs#4569]
It would be very useful to the less experienced crowd to include some real examples. For instance, I really don't understand how to use those instructions. I need to see a real example with a full real path to understand how to place the /contextinfo operator in it. Could you help? This happens to me with many articles that don't show real down to earth examples and given it's abstraction I get lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff7437f2-cb7e-e175-fe04-c92a7ee3dfb4
* Version Independent ID: 68ed5402-71da-c403-14c7-a3e78e2e91b8
* Content: [Navigate the SharePoint data structure represented in the REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service#feedback)
* Content Source: [docs/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, have you had a chance to read the documentation that is linked in that page that you posted? Hopefully if you are able to spend some time in the REST documentation (it's a prerequisite) it will be come a bit more clear.

There are lots of examples/samples at the bottom of this page that also includes sample code.
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service

//Includes samples in C# and JQuery doing both GET/POST requests
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints
