### ISSUE TITLE
Webpack Code Splitting plugin not working

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4574]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [x] Additional article idea

#### Expected or Desired Behavior
Code splitting for webpack 4 should be supported to prevent code duplication. In case you are dealing or like to share components across multiple web parts. Code splitting is supported by [webpack 4](https://webpack.js.org/guides/code-splitting/#root).

Additional article idea for template configuration of webpack to not blindly merge plugins in the configuration.

#### Observed Behavior

When the following entry get merged in the web pack configuration the result is that bundle refuse to work. I personally consider this as a bug or more a question. Is Webpack currently configured to prevent code-splitting? If not, it seems more like a bug.

```js
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    generatedConfiguration.optimization = {
      splitChunks: {
        chunks: 'all'
      }
    }
  }
});
```

The result is like this:

<img width="639" alt="Screenshot 2019-09-02 at 17 17 40" src="https://user-images.githubusercontent.com/5503835/64123803-9daa6a80-cda5-11e9-8577-d39e8c808725.png">

#### Steps to Reproduce
1. Add the setting from above into the gulp file.
2. Run `gulp build --ship`
3. Run `gulp bundle --ship`
4. The output of `gulp bundle` looks like the screenshot above.

**Comment by andrewconnell** [comment]
Two things:

- there's no `--ship` flag on the **build** task
- you aren't returning the modified configuration back to the `additionalConfiguration()` method... that method gives you the config the toolchain created in memory and gives you a chance to modify it, but you have to give it back, otherwise webpack has no config as the messages in the console indicate

```ts
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    generatedConfiguration.optimization = {
      splitChunks: {
        chunks: 'all'
      }
    }
    return generatedConfiguration;
  }
});
```

Once you add that line, the warnings in the output go away.

**Comment by StfBauer** [comment]
* `--ship` there is a switch but might do nothing
<img width="607" alt="Screenshot 2019-09-03 at 18 56 38" src="https://user-images.githubusercontent.com/5503835/64193238-ac178580-ce7c-11e9-92c6-2c1e35cd09da.png">
* Thanks @andrewconnell  - Me 🤦‍♂️
