### ISSUE TITLE
Footer not visible in "_layout" modern pages

### ISSUE THREAD

**Issue by lovethakker02** [SharePoint/sp-dev-docs#4575]
We are having issue when the page URL is "_layouts". Below are common modern pages:
1. Site content
2. News or any other webpart see all page
3. search page

Please look in to this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://docs.microsoft.com/en-us/sharepoint/dev/features/site-footer#feedback)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/site-footer.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by lovethakker02** [comment]
Please see attached screenshot for same.
search page
![screencapture-layouts-15-search-aspx-siteall-2019-09-03-18_04_58](https://user-images.githubusercontent.com/42000241/64174022-30b2d580-ce76-11e9-96d7-1e7e53ef3b58.jpg)

Events see all page
![screencapture-layouts-15-Events-aspx-2019-09-03-18_04_09](https://user-images.githubusercontent.com/42000241/64174024-314b6c00-ce76-11e9-97b3-91822684db4c.jpg)

Site content page
![screencapture-viewlsts-aspx-2019-09-03-18_03_29](https://user-images.githubusercontent.com/42000241/64174025-314b6c00-ce76-11e9-8d62-c493355ba767.jpg)

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
