### ISSUE TITLE
Section title incorrect:  Deploy the extension to SharePoint Online and host JavaScript from local host

### ISSUE THREAD

**Issue by danwatford** [SharePoint/sp-dev-docs#4577]
Section title, 'Deploy the extension to SharePoint Online and host JavaScript from local host', looks to be incorrect as the instructions given in the section content cause javascript files to be hosted from the O365 CDN or from the App Catalog.

Suggest changing section title to 'Deploy the extension to SharePoint Online'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api#feedback)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the issue. You are correct, I have submitted a PR to fix this issue.
