### ISSUE TITLE
Its possible use Visual Studio with SPFX?

### ISSUE THREAD

**Issue by AdrianDiaz81** [SharePoint/sp-dev-docs#458]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Is it possible to use Visual Studio to develop with SPFX?
I try to import it with the NodeJS tools and in the 2015 version it does not build  for an error in the TypeScript version.
And in the 2017 version it gives me an error in the task of SASS.
In both cases, I go to the folder and run the gulp it serves and it works correctly.

**Comment by manishgarg1** [comment]
Hi @AdrianDiaz81, there are know issues with Visual studio integration. We would like to support that scenario going forward.

**Comment by amishra0909** [comment]
Hi @AdrianDiaz81, as @manishgarg1 answered we want to support this for future but for now we are not there yet. I am closing this issue for now.

**Comment by waldekmastykarz** [comment]
Just recently a community-driven initiative started to better support building SPFx solutions in Visual Studio. Check out https://github.com/SharePoint/sp-dev-fx-vs-extension for more information.
