### ISSUE TITLE
Missing "?" from example URI

### ISSUE THREAD

**Issue by byrongits** [SharePoint/sp-dev-docs#4580]
In the "Page through returned items" section, the "?" is missing from the example URI:
http://server/site/_api/web/lists('&lt;guid&gt;')/items$top=10

should be:

http://server/site/_api/web/lists('&lt;guid&gt;')/items?$top=10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#bk_supported)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the issue. I have created a PR to update the documentation and include the '?'
