### ISSUE TITLE
Cleanup / modernize default README.md in SPFx projects

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#4581]
#### Category
- [X] Question

#### Expected or Desired Behavior

A default README.md file in a project should be complete, well-formed & have correct code snippets.

#### Observed Behavior

The intro section always implies it's a web part, regardless if it's an extension or library component

The section **Building the code** has inaccurate steps or those that don't match what the docs tell people today. It also is dated, talking about the CDN when most SPO targets will use the O365 CDN.

The section **Build options** includes a list of gulp tasks, but with descriptions of "TODO". The list of tasks doesn't render as a list as it's incomplete markdown.

#### Steps to Reproduce

```shell
yo @microsoft/sharepoint --skip-install
```
- accept all defaults
- open & inspect **README.md**

#### Steps to Resolve

Replace the existing **READMD.md** in the generator (located in the generator codebase: **./lib/generators/solution/templates/base/README.md**) with this:

https://gist.github.com/andrewconnell/f27f3117f8f7ee836ae38c5e530eee35

> link provided to gist otherwise it gets rendered in this issue

**Comment by StfBauer** [comment]
@andrewconnell in the meantime I clean up yours and add it to the pnp generator. I was always looking for the right anchor point to add some additional information such as the frameworks. Being used + additional information.

**Comment by andrewconnell** [comment]
@StfBauer said:
> I clean up yours

Mine needed cleaning up?

![](https://media.giphy.com/media/13yUJuYdyGQxqM/giphy.gif)

**Comment by StfBauer** [comment]
[--ship | --production | -p] 😀 That are all possible switches.

Those three are implemented and working. They are not even working on those tasks that you have mentioned. The even work on `gulp clean` does not make any sense at all but works.

<img width="636" alt="Screenshot 2019-09-05 at 13 12 45" src="https://user-images.githubusercontent.com/5503835/64337085-e5680680-cfde-11e9-9e49-02dec21b5065.png">

When you never have installed the project you may like to install the trust-dev-cert too and what are the other tasks doing?

<img width="584" alt="Screenshot 2019-09-05 at 13 14 23" src="https://user-images.githubusercontent.com/5503835/64337230-3aa41800-cfdf-11e9-8515-61b98551b514.png">

Forget `dev` and `dist` those are customs gulp tasks that combine some.

Think about some regular web developer stumble upon a Github project. Just wondering don't we have an official documentation on all gulp tasks.

Fixed some typos and wording - [Updated is forked](https://gist.github.com/StfBauer/23afa057d9df4a30751ad08c45d0827f) based on yours

**Comment by patmill** [comment]
Old issue, but it was cleaned up a while ago w/ feedback from the community.
