### ISSUE TITLE
SharePoint  custom property control with angular 2+

### ISSUE THREAD

**Issue by MayurSorthiya** [SharePoint/sp-dev-docs#4585]
how to implement SharePoint custom property control with angular 2+?

**Comment by andrewconnell** [comment]
You asked the same question, and I responded, to my post on my blog: https://www.andrewconnell.com/blog/using-angular-elements-in-sharepoint-framework-projects#comment-4603853160

Same answer as there: 

> The property pane controls are all built using React. I wouldn't recommend building custom controls for the property pane with Angular, but it's technically possible. This article shows how to create custom controls with React: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-custom-property-pane-controls
>
> This module has a HOL that shows the same thing in a more step-by-step process: https://github.com/SharePoint/sp-dev-training-spfx-webpart-proppane
>
> You'll have to figure out how to create the control using Angular Elements, but you can use the approaches I outline in this blog post for that.
