### ISSUE TITLE
[Question] Could not add app into SP Online site.

### ISSUE THREAD

**Issue by honb** [SharePoint/sp-dev-docs#459]
I tried to deploy HelloWorld client web part by using new SP framework (1.0.0) without any modifications. But I didn't see Trust dialog when uploading .sppkg into app catalog (product id is empty as well) so that my app is unavailable for adding.

Do you have any idea for this issue? 
Thanks!

**Comment by patmill** [comment]
Is your tenant opted into first release (the tenant, not a specific user)?

**Comment by honb** [comment]
Right. The client web part can be displayed on workbench.aspx (both local & SP while debugging) but not working with app package (Could not deploy app into AppCatalog).
Do I need to make some changes on tenant settings?

**Comment by patmill** [comment]
Yes - You need to make sure that the tenant is opted in to first release experiences.  It is done through the tenant admin.  Alternately, we'll be rolling this out beyond first release tenants soon.

**Comment by honb** [comment]
"the tenant is opted in to first release experiences" ==> How do I know that? Can you please give me more details about the way that I can check?

**Comment by patmill** [comment]
If you go to the Admin in the waffle menu (top left), search for "First Release", it should take you to your "Home > Organization profile" page.  From there, scroll down to "Release preferences", then make sure that RElease track is "first release for everyone"

**Comment by SumitKanchan4** [comment]
Hi,

As per the latest update from Microsoft , we got to know that the General availability release of SharePoint Framework is available now which has fixed this problem. Microsoft has started rolling it out to all tenants now. I just wanted to ask if there is any date/timeline by when this GA release will be deployed to all tenants worldwide? We checked our tenant and the SharePoint framework app packages are still showing as invalid which means that the GA release is not applied on our tenant till now.

Thanks,
Sumit

**Comment by amishra0909** [comment]
@SumitKanchan4, thanks for your comment. Was the issue resolved?

**Comment by lucaband** [comment]
Hi @SumitKanchan4, sorry for our delay in addressing your question.
You probably already know this but the framework has been rolled out 100% Worldwide. 
If you experience any problem in creating or deploying SharePoint Framework artifacts please let us know.

Thanks
