### ISSUE TITLE
🐞 @microsoft/sp-list-subscription@v1.9.1-plusbeta has no exported members (regression)

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#4592]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When installing the list subscription NPM package on a project that was created with `-plusbeta`, to include developer preview features, you should be able to create list subscriptions.

#### Observed Behavior

When installing the list subscription NPM package on a project that was created with `-plusbeta`, no members are exported, which is the same as the non `-plusbeta` version.

This wasn't the case with the v1.8.2 `-plusbeta` version... thus, v1.9.1 regression

#### Steps to Reproduce

- Install the 1.9.1 beta version of the package:

    ```sh
    npm install @microsoft/sp-list-subscription@1.9.1-plusbeta
    ```

- open **./node_modules/@microsoft/sp-list-subscription/dist/index-internal.d.ts** & notice no members are exported: ❌

    ```ts
    /* Excluded from this release type: ICreateSubscriptionSettings */
    /* Excluded from this release type: IListSubscription */
    /* Excluded from this release type: ISubscriptionCallbacks */
    /* Excluded from this release type: ListSubscriptionFactory */
    export { }
    ```

- Install the 1.8.2 beta version of the package:

    ```sh
    npm install @microsoft/sp-list-subscription@1.8.2-plusbeta
    ```

- open **./node_modules/@microsoft/sp-list-subscription/dist/index-internal.d.ts** & notice members **are** exported ✅

**Comment by patmill** [comment]
Hey @andrewconnell .  You should be looking at lib/index.d.ts.  

Are you seeing an actual issue (like you can't import the factory, etc.)?

**Comment by andrewconnell** [comment]
Arg... amateur mistake. My bad... sorry about that.

**Comment by patmill** [comment]
No worries.  I do think there is some messed up aspect there that we need to clean up, but it shouldn't stop you from building.  Let us know if you run into build problems.
