### ISSUE TITLE
Conversion Utility Recommendation & Clarification Needed

### ISSUE THREAD

**Issue by TracyGH** [SharePoint/sp-dev-docs#4593]
Here is [a console app](https://github.com/TracyGH/SPTheme-Converter) which converts a SharePoint classic (SPColor file) theme to a SharePoint modern (Fabric JSON file) theme, and vice versa.  I have indicated the palette slot mappings that I used in the associated ReadMe file.  

Also, I would like to suggest adding some clarification to this sentence:  

> "The modern site theming experience has been rolled out to classic site templates, too." 

 
When experimenting on my dev tenant, I have found this is true only when the site collection was a modern Teams or Communication template.  However, if I create the root site collection as a classic Teams, Publishing, etc., I am unable select a modern theme for the root site or any sub-sites.  
(Unless I'm misunderstanding the verbiage.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@TracyGH said:
> Here is a console app which converts a SharePoint classic (SPColor file) theme to a SharePoint modern (Fabric JSON file) theme, and vice versa. I have indicated the palette slot mappings that I used in the associated ReadMe file.

Microsoft can't reference a non-MSFT sample in their docs due to liability reasons. However your comment will appear in the closed comments once this comment is  addressed.

@TracyGH said:
> When experimenting on my dev tenant, I have found this is true only when the site collection was a modern Teams or Communication template. However, if I create the root site collection as a classic Teams, Publishing, etc., I am unable select a modern theme for the root site or any sub-sites. (Unless I'm misunderstanding the verbiage.)

Sorry, but the comment isn't clear. Are you saying the statement in the docs is incorrect? If so, can you explain how it isn't correct? Not sure how to address/investigate your comment

**Comment by TracyGH** [comment]
**In my dev tenant, when I create a modern site collection (Teams or Communication) - I see the following for the 'Change the look' menu option:**

![image](https://user-images.githubusercontent.com/38665906/64548009-a5589a80-d2e2-11e9-9150-d6b16ab3d207.png)

**Conversely, when I create a classic modern site collection (I tested Teams or Publishing) - I see the following for the 'Change the look' menu option:**

![image](https://user-images.githubusercontent.com/38665906/64548372-5a8b5280-d2e3-11e9-88d0-476eafc24de4.png)

It appears I have modern theme-ing AND classic theme-ing options when using a modern site collection, but I only have the classing theme-ing options when using a classic site collection.  This impact also appears to spill over into any sub-sites created within the respective site collection(s).  When creating sub-sites beneath a modern site collection, I can opt for modern or classic themes.  But when creating sub-sites beneath a classic site collection, I only have classic options.  
If that is the intended behavior, I have not been able to find it described anywhere within MS documentation.
