### ISSUE TITLE
Can a desktop application built using Electron JS that interacts with SharePoint list using Graph API be submitted ?

### ISSUE THREAD

**Issue by Ramakrishnan24689** [SharePoint/sp-dev-docs#4597]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have few samples which i would like to share\contribute. Out of these one is a desktop application built using Electron JS that interacts with SharePoint list using Graph API. 

Wanted to check whether this would be the right Repos to share these samples. If yes, then which repo would that be.

I once again thank you guys for the awesome work.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
If you want to share them, best to post the dev samples repo here: https://github.com/SharePoint/sp-dev-samples
