### ISSUE TITLE
Unable to fetch other user outlook calendar events using MSGraphClient in SPFX webpart

### ISSUE THREAD

**Issue by soumyadeep2207** [SharePoint/sp-dev-docs#4599]
Category
 Question

Hi All,

I am facing issue while fetching other O365 tenant users calendar events using MSGraphClient in SPFX Webpart. I am able to get records for api "/me/events", "/users/events" but whenever I am specifying user like "/users/{id/upn}/events" its giving 403 access denied. I provided permission scope for Microsoft Graph to read user calendar in package-soution.json as webAPIPermissionRequests. Tenant Admin also approved the permission scope.
 Below is my scope as in package-solution.json file
"**webApiPermissionRequests**": [
     
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      }
      ,
    
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.Read"

      },
      {
        "resource": "Microsoft Graph",
        "scope": "Calendars.ReadWrite"

      }
   ]

Also below is my code snippet which I used.

**this.props.msGraphClientFactory.getClient()
    .then((client: MSGraphClient):void=>{

      client.api('/users/{id/upn}/events').get((err, response:any,rawResponse?:any)=>{
        console.log(response)
        console.log(rawResponse)
      })
})**

The access token which is being generated also includes my permission scope which I have defined. 

Looking forward to any suggestions.. where am I going wrong? Thanks in advance

**Comment by soumyadeep2207** [comment]
Hi Team,

Looking forward to your response

**Comment by andrewconnell** [comment]
The user that is initiating this request from SPFx must also have access to that user's calendar that they are hitting. The permissions you are getting are delegated permissions, not application permissions, so the access token is in the context of the current user. The scopes you've granted the app say the app CAN use those permissions, but it doesn't mean the actual user has access to the target user's mailbox.

This permission is granted within Outlook.

**Comment by soumyadeep2207** [comment]
Hi Andrew,

Thanks for your valuable input, indeed if i generate token and pass it along with the Api call as auth header I am getting the response. Is there anything I am missing on permission part in my config json file? or i need to pass explicitly the token from spfx to the api ?  Looking forward to your inputs.

**Comment by andrewconnell** [comment]
Please [re-read my comment](https://github.com/SharePoint/sp-dev-docs/issues/4599#issuecomment-529924979).

Specifically **This permission is granted within Outlook.**

Permission grants to the Microsoft Graph only say "This application (SPFx) can DO [these permissions] on that application (Graph)" It doesn't say "Jane as given John rights to read her calendar".

That permission is defined within the mailbox. Not in SharePoint. Not in Microsoft Graph.

**Comment by soumyadeep2207** [comment]
Hi Andrew,

If I understood correctly , user needs to specifically share their
calendars with the respective person from their outlook, like John will
share his calendar from his outlook with Jane and Jane needs to accept that
to get this working.

Regards,
Soumyadeep

**Comment by andrewconnell** [comment]
![](https://media.giphy.com/media/l1J9wXoC8W4JFmREY/giphy.gif)

Sort of... Jane doesn't need to accept anything. Once John shares his calendar with Jane, then Jane has permissions to access it. She can open it up in Outlook on desktop, Outlook Web, Outlook iOS, etc.

However, that wouldn't be enough to access it using SPFx via the Microsoft Graph. The reason why is because SharePoint would need the **Calendar.Read** permission to use that scope with the Graph. You've already done that part though so you should be good. Mentioned it just for the sake of completeness.

**Comment by soumyadeep2207** [comment]
Thanks Andrew for your inputs.
