### ISSUE TITLE
Breaking changes in RC0 cause sample code to fail in [connect-to-sharepoint.md]

### ISSUE THREAD

**Issue by Rubonix** [SharePoint/sp-dev-docs#460]
SPFx RC0 contains breaking changes as per `https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0`

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [X ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
The sample code in [connect-to-sharepoint.md] should work with RC0.

#### Observed Behavior
Breaking changes in SPFx RC0 prevent the sample code from working.

#### Steps to Reproduce
Implement the code from [connect-to-sharepoint.md] and test it against SharePoint online.

#### Suggested Fixes to the Sample

`// Add the following import statements towards top of [HelloWorldWebPart.ts]

import {SPHttpClient} from '@microsoft/sp-http'; /* NB: for breaking change in SPFX RC0 httpClient.get(, HttpClientConfiguration)*/
import { Environment, EnvironmentType } from '@microsoft/sp-core-library'; // was:  '@microsoft/sp-client-base'

// in [HelloWorldWebPart.ts] _getListData()

return this.context.spHttpClient.get('/_api/web/lists', SPHttpClient.configurations.v1)

// in [HelloWorldWebPart.ts] _renderListAsync()
if (Environment.type === EnvironmentType.Local)  // was: if (this.context.environment.type === EnvironmentType.Local)`

#spfx, #spfx-webparts

**Comment by patmill** [comment]
Sorry - not sure I understand.  Is the issue that the code doesn't work on the 1.0 release, or that you are trying to use the 1.0 labs against the RC0 build?

**Comment by Rubonix** [comment]
The problem seems to be fixed now.
FYI: earlier this week at least one of the following get-started samples had not been updated for the latest release:-
[https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/spfx/web-parts/get-started/connect-to-sharepoint.md](url)
[https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md](url)
