### ISSUE TITLE
Description property is missing in Site design JSON schema for addSPField and createSiteColumn methods

### ISSUE THREAD

**Issue by jordyvanbremen** [SharePoint/sp-dev-docs#4600]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

It would make sense to be able to give fields a description while creating them from a Site Design. Therefore I suggest to add a property "description" like in the below example. Would this be possible?

{
    "verb": "createSiteColumn",
    "fieldType": "User",
    "internalName": "siteColumn4User",
    "displayName": "Project Owner",
    **"description": "This is my description",**
    "isRequired": false,
    "id": "181c4370-cdae-471b-9499-730046e55b75"
}

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#define-a-new-site-column

Btw: Although it's not really a bug I post this here and not on UserVoice because I think the request is somewhere between a bug and a change. Anyway it's not 'big' enough for UserVoice. Pls correct me if I'm wrong.

**Comment by andrewconnell** [comment]
While it does falls close to between the two, because nothing is broken and works as designed, it should be a user voice submission as it is a change / addition to the feature.
