### ISSUE TITLE
Unable to trust certificates

### ISSUE THREAD

**Issue by vaderj** [SharePoint/sp-dev-docs#4606]
OS : Windows 10/1809
Node : same behavior for both v8 and v10
@microsoft/generator-sharepoint@1.9.1
Gulp:   CLI version: 2.2.0 ; Local version: 3.9.1

I have attempted this over a dozen times, with each attempt completely emptying my project folder and restarting. 
When I run "gulp trust-dev-cert" I get a dialog which I am able to authorize the installation of the certificate, but regardless of the browser, I am not able to load the Local Workbench without the browser telling me the certificate is invalid.

I have untrusted the certificate, deleted the .gcb-serve-data folder of my user profile, completely uninstalled and reinstalled with both Node 8 and Node 10, and restarted my workstation multiple times.

No combination of the guidance has allowed Chrome 76, Firefox, or IE11 to recognize the dev cert as a valid certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Have you tried trusting the dev cert from an administrative command prompt?

Seems like you've done everything else... in these cases, the other thing I recommend trying is uninstalling everything (Node.js, **.gcb* folder, then making sure you've deleted the files from the Node.js installer), rebooting and trying again.

**Comment by vaderj** [comment]
I did try it from an admin console as well.  Tomorrow I will be inquiring about "security patches" being applied.
