### ISSUE TITLE
How to have tenant wide deployment and targeted (scoped) deployment in same project?

### ISSUE THREAD

**Issue by hamedy** [SharePoint/sp-dev-docs#4607]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I've followed this guide for deployment: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint

wondering if it's possible to combine tenant wide deployment for some webparts/extensions and scoped deployment to only certain sites/lists for other webparts/extensions in the same yo generated project. If so, how is it done. 

Thanks in advance, 
Hamed

**Comment by andrewconnell** [comment]
Not possible... you'd need to have separate packages (*.sppkg), one for the stuff that goes everywhere, then one for each targeted site collection.

**Comment by hamedy** [comment]
thanks for clarification :)
