### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by cruzex100** [SharePoint/sp-dev-docs#4609]
Is anyone else seeing this issue with the latest node version?

The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET

Here is the gulp output:
[17:11:06] Starting gulp
[17:11:06] Starting 'trust-dev-cert'...
[17:11:06] Starting subtask 'trust-cert'...
[17:11:06] Finished subtask 'trust-cert' after 62 ms
[17:11:06] Finished 'trust-dev-cert' after 70 ms
[17:11:07] ==================[ Finished ]==================
[17:11:07] Project submission-form version: 0.0.1
[17:11:07] Build tools version: 2.5.3
[17:11:07] Node version: v10.16.3
[17:11:07] Total duration: 2.43 s

**Comment by BassemNKhalil** [comment]
Are you able to provide some more information:
Results for npm list -g —depth=0 (to show your current global npm packages)
Current NodeJS version: node -v
Type of solution (WebPart, Extension or Library)
The target SharePoint version selected when creating the solution (SP16, SP19 or SPOnline)

**Comment by andrewconnell** [comment]
What issue? All you ran was the **trust-dev-cert** task. It does some work and terminates. In your post, there's nothing that indicates an error. Maybe provide the full output of the console?

@BassemNKhalil - look at the OP, the version of Node is specified.

**Comment by cruzex100** [comment]
I was able to get past the error by upgrading gulp and also installed the missing dependency @microsoft/rush-stack-compiler-3.2. i have also updated the serve.json to include http instead. 

I'm now seeing a blank page and its goes into a loop.. i will see if this is caused by some other configuration.. For now the connection error issue is resolved.

Thanks for looking into this.
