### ISSUE TITLE
Running two instances of spfx web app at the same time on workbench.aspx

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#461]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I would like to run two instances of sp framework web app at the same time on /_layouts/15/workbench.aspx. It currently works on localhost workbech with different port specified under serve.json

**Comment by patmill** [comment]
Hi @jonathanhotono - just to clarify.  Is the desire to run 2 different command prompts, each with gulp serve running, and you want to have two windows open to workbench.aspx, each served by a different command prompt gulp serve?

**Comment by jonathanhotono** [comment]
@patmill That is correct. And this can also be a single workbench.aspx containing two different webparts if possible.

**Comment by patmill** [comment]
Digging in a bit more here. do you actually want different projects, or simply a project that can have 2 it 3 web parts?

________________________________

**Comment by jonathanhotono** [comment]
Hi @patmill - Maybe 2 different projects with 2 different JS framework. Also it's interesting to know if we could actually could have a project with multiple webpart, did a bit of research(https://www.itunity.com/article/add-web-part-sharepoint-framework-project-3629 ) is this method still valid? @waldekmastykarz

**Comment by waldekmastykarz** [comment]
Yes, it is @jonathanhotono although the bug mentioned in the article has been fixed so just calling the generator is sufficient.

**Comment by iclanton** [comment]
The way to do this would be to put the two webparts in the same project and run gulp serve from that project. We don't support grabbing debug files from two different gulp serve instances in workbench.aspx because of issues with conflicting library references.

Please reopen this issue if that doesn't work.

**Comment by Azhakeswari** [comment]
I am also facing the same issue.If two people running the gulp serve it is showing me only one instance of local host.Any pointers would be helpful.
