### ISSUE TITLE
Library components are not working

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4613]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Related issue #4507 but more in-depth analysis.

#### Expected or Desired Behavior

It seems like that library components or documentation is missing following the instructions do not lead to a l[ibrary component](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial).

#### Observed Behavior
Following the instruction 1:1 on how to create a [library component](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial) Leaded to the following result.

It doesn't make any difference if the library component is deployed to the server or not.

![Screenshot 2019-09-11 at 13 57 14](https://user-images.githubusercontent.com/5503835/64695312-18f1d780-d49c-11e9-98ac-abf9ae795e96.png)

The following statement should be rendered by the library component that, at this time wasn't installed on the tenant.
> The current time as returned from the corporate library is 13:22:54 GMT+0200 (Central European Summer Time)

The web part potentially should have raised an error. This behaviour is caused due by the following in code snippet:

```javascript
import * as myLibrary from 'corporate-library';
```

This treats the 'corporate-library' as a regular NPM package and compiles directly the code in the final web part code. Instead of loading it from a library component.

This might could have been used as a fallback mechanism but even after installing the library component, with a changed return value of the library.

```javascript
export class CorporateLibraryLibrary {
  public getCurrentTime(): string {
    return 'Hello World: time as returned from the corporate library is ' + new Date().toTimeString();
  }
}
```

The result of the web part looked exactly the same.

![Screenshot 2019-09-11 at 13 57 14](https://user-images.githubusercontent.com/5503835/64695781-35dada80-d49d-11e9-8152-36f73b10657b.png)

The result was that the library component wasn't picked up at all.

To verify that the source code of the library component was embedded in the code. The actually library component showed up directly in.

<img width="1019" alt="Screenshot 2019-09-11 at 15 14 21" src="https://user-images.githubusercontent.com/5503835/64700258-daade580-d4a6-11e9-8cf4-0b3181e87269.png">

This screenshot shows the result of the compiled web part.

#### Steps to Reproduce

Source code used to reproduce can be [found here](https://github.com/StfBauer/librarycomponent-error)..

**Comment by PopWarner** [comment]
@StfBauer, I can reproduce your issue, but I noticed your repo didn't include the reference to the library in your web part's package.json. When I added the reference, the library component code was no longer included in the web part's js bundle.

Does this work for you? :)

**Comment by StfBauer** [comment]
@PopWarner Yeah found it myself two minutes ago... I submit a PR to the documentation ... this one is pretty bad

**Comment by PopWarner** [comment]
@StfBauer good find! Yea, some more documentation would help.

I also just did a clean pull of your code and did NOTHING but add the dependency reference and the library code was still included in my web part .js bundle.

I found that if I did ONLY a gulp bundle on the library, it would still be included in the web part .js, even when I added it as a dependency to the package.json.

Although, once I did a gulp bundle --ship on the library, the library code was no longer included in the web part .js bundle, even if I again did only a gulp bundle.

Gonna run a few more tests to see if that wasn't an anomaly.

**Comment by StfBauer** [comment]
Somehow a bit strange constellation - https://n8d.at/blog/tips-and-tricks-working-with-spfx-library-components

Angular Elements in pnp/spfx use the "library" approach since last October or so and it handles things in a more web development / nodejs manner.

**Comment by Ashlesha-MSFT** [comment]
Hi @StfBauer, @PopWarner,
Tested with SPFx Version: 1.22.1
Changed Library component to below -
```
 public getCurrentTime(): string {
  return '🚀 UPDATED LIBRARY v2.0: The current time as returned from the corporate library is ' + new Date().toTimeString();
}
```
1. Library component builds and deploys successfully with heft build --production and heft package-solution --production
2. Updated .sppkg re-deploys to App Catalog successfully (with "Replace It" option)
3. Library is marked as tenant-wide available
4. Consuming web part continues to show old library behavior/code
5. Hard refresh, incognito mode, and different browsers don't resolve the issue
6. Web part [package.json] correctly references the library dependency

<img width="958" height="398" alt="Image" src="https://github.com/user-attachments/assets/0dc45847-5326-4d41-99ed-e11effd4b985" />

I can provide a minimal reproduction case with both library and web part source code for testing if that would help confirm whether this is a regression or configuration issue.
