### ISSUE TITLE
Term Group table in diagram for Asia is incorrect

### ISSUE THREAD

**Issue by cimares** [SharePoint/sp-dev-docs#4614]
The reach for TGAsia1 in the Asia table shows as All Sites in Europe when it should be all sites in Asia.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711de1ae-029d-8c45-f42a-0d16014468e8
* Version Independent ID: 87cdbc16-829f-0787-5a5a-cfe6f719c780
* Content: [Manage metadata in a Multi-Geo tenant](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-managedmetadata)
* Content Source: [docs/solution-guidance/multigeo-managedmetadata.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/multigeo-managedmetadata.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@davidchesnut Looks like you were the author of the image. Do you have the source to it?

**Comment by andrewconnell** [comment]
@davidchesnut can you suggest where one could obtain this theme of artwork to replicate it?

**Comment by nanddeepn** [comment]
Hi,
Tried to update the file at path "https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/media/multigeo/multigeomanagedmetadata_intro.png" with the image attached here.

![multigeomanagedmetadata_intro](https://user-images.githubusercontent.com/8310319/68144241-3b164c00-ff59-11e9-8317-a423fcda51b9.png)

Please update the image at above location, if in case my commit fails. Thanks!

**Comment by andrewconnell** [comment]
It appears you submitted a PR to YOUR fork's master branch... that won't work :)

At any rate, took your screenshot and updated the doc.

**Comment by nanddeepn** [comment]
Thank you @andrewconnell
