### ISSUE TITLE
Creating a new SPFx solution for SP2019 tslint.json file ignored

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#4615]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Have the rules from tslint.json respected, and suppressed when turned off.

#### Observed Behavior
Even though the default project was created with tslint.json, and it has the default rules in it, it seems the tslint.json file is ignored.
This code for example:
```
var x = 3;//test
```
will report a warning of a missing whitespace.
this code:
```
let y = someFunctionThatReturnsATypedObject();
```
will report the "typedef" warning.
this code:
```
let z = "hello!"
```
will report a warning that strings must use single quotes.

Also, the default file is created with this line:
```
"extends": "@microsoft/sp-tslint-rules/base-tslint.json"
```
but the version of sp-tslint-rules that was installed with 1.4 does not have this file.

When creating a project for sp2019 it forces us to use 1.4 but there seems to be plenty of issues with the current way the default project is created.

#### Steps to Reproduce

On a desktop that was previously configured to build spfx projects in v1.8.1, do the following:
1. create a new SPFx project 
1.1. target SP2019
1.1. Add a single web part
1.1. do not use any library for rendering
1. run npm install
1. add the following code to your web part render method:
```
var x = "hello!";//how about that?
```

when you run gulp, you will see warnings reported for this code.
also, if you check under node_modules the file "@microsoft/sp-tslint-rules/base-tslint.json" does not exist in this version of the package. it does exist on a later version of this package.

**Comment by FTWhaywood** [comment]
This appears to be a scaffolding issue, when generating a SP2019 project with SPFx 1.4.1 you get a top level tslint file as well as a empty index.ts file. Neither of these are used in SPFx 1.4.1. TS Lint is via the tslint.json file in the config directory (missing from the newer generator?) and dependencies installed such as tslint-microsoft-contrib.

**Comment by bcameron1231** [comment]
The same is happening for scaffolding 2016 solutions.

**Comment by kemesfun** [comment]
Scaffolding with 1.4.1 does repro. and does have this issue. Changing the packages to 1.8.1 will resolve this issue.
