### ISSUE TITLE
Import JSOM

### ISSUE THREAD

**Issue by z1988hf** [SharePoint/sp-dev-docs#462]
The guide about using JSOM on this page https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom has one flaw.
That is, it hard code the url of these js file. In real world, the app should get these js file from the website it runs, not from a fixed website. So this approach doesn't fit. SPFX should provide a loader to load external js file on demand. 
"sp-init": {
      "path": "https://contoso.sharepoint.com/_layouts/15/init.js",
      "globalName": "$_global_init"
    },

**Comment by patmill** [comment]
Fair point.  If you were creating a package that you wanted to distrubute to multiple tenants, you would need this.  Thanks for the request.

**Comment by frankchen76** [comment]
@z1988hf I agree what you talked about. Having the url of JSOM hard coded in config.json isn't good for the case that we need deploy web part deployed to multiple tenants. @patmill , I wish SPFx can have better way to address this. At this moment, If we really want to make JSOM loaded dynamically, I guess we probably can use SPComponentLoader to load JSOM dynamically. the "Load SharePoint JSOM scripts using SPComponentLoader" section mentioned detail in that document. It provides a example for React, but I am looking for something for AngularJS, especially when you leverage AngularJS for web part display and control pane displaying.

**Comment by iclanton** [comment]
@mpasarin - You've been doing some work around this. Assigning this to you.

**Comment by patmill** [comment]
There is a package available for this - https://www.npmjs.com/package/@microsoft/sp-jsom

**Comment by waldekmastykarz** [comment]
@patmill unfortunately this package doesn't work. First of all, it tries to load SharePoint JSOM files from `https://localhost:4321/node_modules/@microsoft/sp-jsom/_layouts/15/init.js` rather than from the current SharePoint site. Then, even if it would be loading files from the correct location, it would break on classic SharePoint pages where JSOM is already present because it's not checking if JSOM is already loaded or not.
