### ISSUE TITLE
Include instructions to unlink Library

### ISSUE THREAD

**Issue by nanddeepn** [SharePoint/sp-dev-docs#4626]
The documentation should also include how to unlink a library from SPFx solution and a symlink from local "node_modules" folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac926949-7ab3-3a40-14e8-3b5b032803c1
* Version Independent ID: d3ae1d27-3976-64ac-fda6-5ca18a25dbd0
* Content: [Building solutions with the library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial)
* Content Source: [docs/spfx/library-component-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sounds like a great PR op for the community :) Care to submit one?

**Comment by nanddeepn** [comment]
Thanks
I will submit a PR

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
Submitted PR https://github.com/SharePoint/sp-dev-docs/pull/4630 for this.
Please review and suggest.
Thank you.

**Comment by andrewconnell** [comment]
Thanks!

In the future, you don't need to comment that you submitted a PR. If you reference the issue in the PR, you can see GH adds a reference to the PR within the issue.
