### ISSUE TITLE
Formatting the Attachments Field In a List

### ISSUE THREAD

**Issue by Famidar** [SharePoint/sp-dev-docs#4627]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hello.  I was wondering if anyone knew of a way for us to use JSON formatting on the Attachments field in a list.  I was hoping to be able to display a click link for each attachment attached to a record in a list.  

I cannot seem to find anything in regards to iterating this particular "field". 

Thanks,

Fam

**Comment by bcameron1231** [comment]
Unfortunately there is no way to do this. The attachment value only returns a boolean whether attachments exists, so there isn't a way to generate a link in the way you want to.

**Comment by Famidar** [comment]
Thanks.  I was afraid that was the answer.  /bummer
