### ISSUE TITLE
Touchmove event not working in Mobile Browsers

### ISSUE THREAD

**Issue by kmprasad4u** [SharePoint/sp-dev-docs#4632]
Touchmove events are not working as expected in SPFx webpart. Issue is probably not with SPFx but with Modern UI itself. Let me know if there is any better ways for handling this from SPFx.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior
Touchmove event is not fired even once both in SPFx webpart and also with html in script editor webpart. With some analysis, I found that Modern UI attaches a touchmove event in body tag which is stopping propagation. This seems to be registered earlier with capture true, and hence it is doesn't trigger the touchmove event attached in custom element. 

PS: I am aware of touchmove doesn't fire as expected in Android Chrome. But here it doesn't fire even once.

```javascript
// Below code in console
getEventListeners(document.body)

// Leads to below handler in one of sharepoint's scripts for navigation
 t.prototype._enableMobileTouchMove = function(e) {
                e && !e.target.classList.contains("ms-Overlay") && e.stopPropagation()
}

```

#### Workaround
As a workaround, I am able to make it work by adding "ms-Overlay" class to the element.

#### Steps to Reproduce
Below code in script editor or in spfx webpart.

```html
<div id="testSwipe">
    Test Swipe<br />
    Test Swipe<br />
    Test Swipe<br />
</div>
<script>
    function touchStart(e) {
        console.log("touchStart");
    }
    function touchMove(e) {
        console.log("touchMove")
    } 
    var testSwipe = document.getElementById("testSwipe");
    testSwipe.addEventListener("touchstart", touchStart, { passive: false, capture : true });
    testSwipe.addEventListener("touchmove", touchMove, { passive: false, capture : true });
</script>
```

**Comment by migee** [comment]
Just confirming that the ms-Overlay class did work, however I couldn't simply apply it to a parent container of everything and have it work. Instead I had to apply the class to the each of the items within 
 that get the primary touch event notification.

**Comment by kmprasad4u** [comment]
@migee, Yes I did realise that when I implemented this workaround. I didn't remember to come back here to inform about it. I used the below code to avoid adding the class to every element, which will also cause issues with styles. So I did it dynamically when it is required. And yes i think the fix needs to be from SharePoint, and this is a temporary workaround. 

```typescript
export class SwipeFix {
  private static isFixed : boolean;

  private static TouchEnd(ee : Event) : void {
    const currentTarget : any = ee.currentTarget;
    currentTarget.classList.toggle("ms-Overlay", false);
    currentTarget.removeEventListener("touchend", SwipeFix.TouchEnd);
  }
  public static Fix() : void {
    if(!SwipeFix.isFixed) {
      SwipeFix.isFixed = true;
      document.documentElement.addEventListener("touchstart", (e : Event) => {
        const target : any = e.target;
        if ((target.className && target.className.indexOf("fix-swipe") >= 0) || DomHelper.closest(target, ".fix-swipe")){
            target.classList.toggle("ms-Overlay", true);
            target.addEventListener("touchend", SwipeFix.TouchEnd);
        }
      }, { passive: false, capture: true });
    }
  }
}
```

And in components that require the fix
```typescript
public componentDidMount() {
    SwipeFix.Fix();
  }

public render() {
    // Add "fix-swipe" class to the element to which touch events are attached.
}
```

I initially had problem with a carousel component that I was using, and later used some other package that didn't require this fix. Probably the newer package handled touch events differently.

**Comment by dev-a11y** [comment]
fyi. this issue is causing trouble with [Bing Maps webpart](https://support.office.com/en-us/article/use-the-bing-maps-web-part-c0e3f2f6-dc0d-49df-9308-1bf7c888e794) on modern pages in spo; incorrect behavior can be reproduced by switching to mobile view in Chrome and refreshing page - you can't pan the map; workaround with overlay class is a bit tricky to apply for bing maps v8 control...

**Comment by Nootvar** [comment]
I can confirm that the event is not fired if the web part is on a published page, yet it work on both the local and hosted workbench. Also the 'ms-Overlay' fix is not working for me.

**Comment by dev-a11y** [comment]
this issue has been fixed few months ago on our tenant (we had support ticket for that);
for some time we had a workaround in place but later on it was not needed anymore;
most likely it should be closed now
