### ISSUE TITLE
Field customizer rendering in percentage column after deployment

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-docs#4633]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Issue
I have created three solutions to render a button for one of my list column by following [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer). 

The process of solution created is the same as to the article. The only difference in the deployment. All the three works perfect while running gulp serve command. After deployment, below are my observations: 

1. post-deployment, If the Percentage column is not added in the list, it was throwing an error saying manifest not found. 
2. The customization done was applied to the percentage column if available, rather than the actual column. 
3. I have tried by deleting the element.xml and updated the package-solution accordingly. 
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "fieldcustomizer-client-side-solution",
    "id": "7e2c24dd-0c9e-4050-8edc-e3fc1e4888e0",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false
  },
  "paths": {
    "zippedPackage": "solution/fieldcustomizer.sppkg"
  }
}
```

Still, after deployment, it is the same scenario. There is no expected output.  

I have attached the sample I have tried. 
[fieldcustomizer.zip](https://github.com/SharePoint/sp-dev-docs/files/3615810/fieldcustomizer.zip)

Screenshot of the local workbench: 
![localworkbench](https://user-images.githubusercontent.com/14230498/64951390-68b91000-d89b-11e9-95ff-54b275557c70.png)

Screenshot after deployment: 
![actual](https://user-images.githubusercontent.com/14230498/64951470-969e5480-d89b-11e9-84a9-8f8ffc5e2801.PNG)

Please let me know if I have missed anything. 

Package details: 
 ```
"@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
```

**Comment by andrewconnell** [comment]
Please post your project, if you're willing to share, to a public github repo and provide a link here. It's safer as people shouldn't download a random ZIP with JavaScript in it.

Field customizers are deployed as NEW site columns on a site, so you will need to add the site column to your list in order for it to appear.

**Comment by Harshagracy** [comment]
Hi Andrew, I will share the link. I am trying for an existing column. That's why I have removed element.xml and feature deployment part in package-solution.

**Comment by Harshagracy** [comment]
The column has to be mapped. i did using pnp powershell script:

$list = Get-PnPList -Identity $listTitle  
$fld = Get-PnPField -List $list -Identity $fieldTitle  
$fld.ClientSideComponentId = "0407eb29-728c-47c3-9f9b-bb1d2e04c4cc"  
$fld.Update()  
Invoke-PnPQuery

Thanks for the help Andrew. I am closing the thread.
