### ISSUE TITLE
SPFx in MS Teams: Created by, Version, privacy policy and terms of use information in manifest.

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4638]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Created by, version, privacy policy and terms of use are populated from SPFx solution.

#### Observed Behavior

Created by: SPFx + Teams Dev
Version: 0.1
All the urls lead to Microsoft's resources

#### Steps to Reproduce

1. Create SPFx Teams tab
2. Upload `.sppkg` to SharePoint app catalog
3. click Sync to Teams
4. Navigate to Teams and see the app's card:

![teams app](https://user-images.githubusercontent.com/17036219/64972886-e90d5000-d85e-11e9-9e2f-5c56f08c2116.png)

**Comment by VesaJuvonen** [comment]
This got fixed at some point for sure. Cleaning issues.
