### ISSUE TITLE
Add .tfignore file to the yo spfx generator

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/sp-dev-docs#464]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Suggestion

Add to the Yo generator a .tfignore file. I believe the most of the developers are coming with a TFS instance as a code repo.

EDIT (kudos to @andrewconnell for the input): Add additional step in the generator for choosing a code repository which should generate the respective file, i.e. .gitignore, .tfignore, none, etc.

**Comment by andrewconnell** [comment]
Please don't muddy up the generated projects with this stuff. There's already too much stuff in the root that's not necessary to have in every single project such as:

- `.npmignore`
- `.yo-rc.json`
- `.gitattributes`
- `.editorconfig`

If anything, add flags to include these in the generator. PLEASE don't force a `.tfignore` file on us. The OP's assumption that *"most of the developers are coming with a TFS instance as a code repo"* is a HUGE (*and IMHO flawed*) assumption.

**Comment by Sartor87** [comment]
@andrewconnell 
> If anything, add flags to include these in the generator.

This will be much better - thanks for the input. I will update my original suggestion.

**Comment by iclanton** [comment]
We've added this to our backlog. Thanks for the suggestion.
