### ISSUE TITLE
ModernSearch/react-search-refiners  - Search Refiners showing string;# for calculated columns

### ISSUE THREAD

**Issue by MichalExpP** [SharePoint/sp-dev-docs#4644]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Search Refinrs web part should display a correct value, if the refinable string is mapped to a calculated column.

#### Observed Behavior

Mapped refinable string to a calculated column results in an incorrect value being displayed at the Search Refiners web part. Instead of "Amber" it displays "string;#Amber"

#### Steps to Reproduce

1. Create a simple list and add a choice site collection column column (with choices Red;AmberGreen), then add a site collection calculated column that displays the value from that choice site column.
2. Map a refinable string to the calculated site column
3. Use that refinable string on a Search Results web part
4. The value from a calculated column will display as string;#Amber

In the classic refiner web part, it was necessary to edit a refner template to get rid of the string;# prefix, this was a known issue with calculated columns: https://veenstra.me.uk/2014/04/29/refinement-panel-showing-string-for-calculated-text-fields/

**Comment by bcameron1231** [comment]
Thanks for the issue. I'm not sure I would call this a bug per se, as this is the value being stored by SharePoint for calculated columns. As you mentioned, in the classic pages you would have to edit the display template to get rid of the string;# prefix.

**My suggestion would be to submit a ticket to the PnP Web Parts repository of this issue, as it is related to the PnP Modern Search web part and/or submit a PR to support this.** 

https://github.com/SharePoint/sp-dev-fx-webparts/issues

**Comment by MichalExpP** [comment]
Thank you, I'll log under the original repository. I agree this is not a bug, rather an enhancement
