### ISSUE TITLE
SharePoint 2019 Scenario

### ISSUE THREAD

**Issue by jeffangama** [SharePoint/sp-dev-docs#4647]
Maybe you could specify SharePoint 2019 possible scenario here ? Office 365 Groups are not possible for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d89003-27e6-a443-e99b-5afd8f758b83
* Version Independent ID: 0ca22c7e-e6c0-0c66-3ce9-55a3f663d3c4
* Content: [Modernize your classic SharePoint sites](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-classic-sites)
* Content Source: [docs/transform/modernize-classic-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-classic-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Could you please provide more details about the question ?
For SharePoint 2019, here are some new features for your reference:
[https://dev.to/mlisidoro/meet-the-new-modern-sharepoint-server-sharepoint-2019-rtm-is-here-2oak](url)

**Comment by jansenbe** [comment]
The modernization guidance and associated tools and components only works for SPO at this moment. In theory most of it can apply to SP2019 as well but no investments have been made in this area.

**Comment by somaliasil** [comment]
Does this works for sp 2010 as well?
