### ISSUE TITLE
GraphHttpClient fully disabled?

### ISSUE THREAD

**Issue by TheTedAdams** [SharePoint/sp-dev-docs#4649]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Until recently, our old code which called `await this.context['_graphHttpClient']['_getOAuthToken']();` and then `this.token = this.context['_graphHttpClient']['_token'];` still worked. We know this was removed in `1.9.1` release and we removed it from our code back in April, but we have users who have not upgraded to our latest web part.

#### Observed Behavior

GraphHttpClient no longer seems to be providing a token. Any customers using the old version of our web part are no longer able to authenticate with graph.

#### Question

Before we try to track down anyone using the old version of our web part, we just wanted to get official confirmation that GraphHttpClient was intentionally fully disabled. It seems that over the past several days it has been intermittently working and not working, and then this morning it seemed to quit working for anybody still on the old code. We realize it was deprecated, and like I said it has been out of our new code for months, but we hadn't gone out to chase customers who were still on old web parts yet.

**Comment by andrewconnell** [comment]
_I'm working on tracking down an official answer, but until then..._

GraphHttpClient never made it out of the developer preview phase, which means that it could change at any time. It didn't leverage the current way we obtain tokens and how things were added to the page. In addition, according to your code, the way you were obtaining the access token was using internal stuff, not public APIs, and Microsoft reserves the right to change anything marked as internal without notice.

**Comment by patmill** [comment]
Correct.  GraphHttpClient was never public, it was replaced with MSGraphHttpClient (which leverages a better graph library, etc.).  GraphHttpClient was then deprecated, and has been removed.
