### ISSUE TITLE
self hosting sharepoint 2016 farm On-Premises

### ISSUE THREAD

**Issue by tobiashoeft** [SharePoint/sp-dev-docs#465]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Is the framework also working with self hosting sharepoint 2016 farm On-Premises? 

Or will it be able in the 2017 year?

**Comment by patmill** [comment]
The plan is to back-port the webpart portion of SPFX to OnPrem 2016 as part of Feature Pack 2.  You will be able to create webparts in classic pages.
