### ISSUE TITLE
Error - [tslint] No valid rules have been specified for TypeScript files Error - 'tsc' sub task errored after 8.09 s  exited with code 2

### ISSUE THREAD

**Issue by devendrasv** [SharePoint/sp-dev-docs#4650]
Hi,

I am trying to upgrade the React content Query webpart here https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-content-query-webpart using O365 CLI, which generated below report.

[report.zip](https://github.com/SharePoint/sp-dev-docs/files/3626870/report.zip)

After completing the changes I am getting below error.
<img width="502" alt="error" src="https://user-images.githubusercontent.com/3216636/65156844-5806c680-da62-11e9-8234-83178e3dab0b.png">

<img width="500" alt="error-2" src="https://user-images.githubusercontent.com/3216636/65156895-6ce35a00-da62-11e9-8e42-607b6a36d422.png">

Any suggestions on how to fix this issue, Thanks.

-Devendra

**Comment by jrs-devlev** [comment]
I have the same error / problem - is there a solution ?

**Comment by andrewconnell** [comment]
After making the changes to the project, did you delete both the package lock file & **node_modules** & reinstall all dependencies? Very well could be packages no longer in use are still around...
