### ISSUE TITLE
Title + " is waiting in the lobby to fill out benefits and employment forms." Does not work

### ISSUE THREAD

**Issue by duncanspeidel** [SharePoint/sp-dev-docs#4654]
When I execute the workflow the email I receive does not show the expected value of Title.  The subject line is "is ready for HR paperwork" and the body is "is waiting in the lobby to fill out benefits and employment forms.".  I changed the body of the email to just title and the workflow failed with a null exception.
Instance 'd41a49c1-e681-40d4-b816-81eb23c929b3' of workflow 039c3889-ae63-4a9b-b4ce-169081759e4b Status: Started; Details: .
Instance 'd41a49c1-e681-40d4-b816-81eb23c929b3' of workflow 039c3889-ae63-4a9b-b4ce-169081759e4b Status: SystemSuspended; Details: RequestorId: 26d34922-ffb2-6d44-0000-000000000000. Details: An unhandled exception occurred during the execution of the workflow instance. Exception details: System.ArgumentNullException: Value cannot be null.
Parameter name: Input
   at Microsoft.Activities.Expressions.IndexOfString.Execute(CodeActivityContext context)
   at System.Activities.CodeActivity`1.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.ActivityInstance.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation).

This tells me the Title variable is null but I do not know why.  How can I either populate the variable or get a list of non-null variables that I can use in the email subject and body?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8578d8-4703-1ac5-ae2e-f2ebbd85cdbb
* Version Independent ID: 075145ec-e01c-00bf-358d-4604fa25daad
* Content: [Add a workflow to a SharePoint-hosted SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I know you had another issue open on this, but can you please provide full context here? Screenshot of the activity properties showing the **Title** property is set would be helpful, as the error states that it is not being set.

**Comment by duncanspeidel** [comment]
The email I receive shows: "is waiting in the lobby to fill out benefits and employment forms." On the subject line.  The body shows " is ready for HR paperwork".  The Title variable is not getting populated.
![GetDynamicValue](https://user-images.githubusercontent.com/16256174/65275375-8b456600-daf3-11e9-9053-71d43245aab0.png). This shows how I am trying to populate the title value.  I also tried Title (LinkTitleNoMenu), same result.  The email takes the form of:
![emailFromWorkflow](https://user-images.githubusercontent.com/16256174/65275514-d8c1d300-daf3-11e9-86ab-1b86cd6ff4ea.png).

I need to know how to properly populate the Title field.  I selected Title from the drop down.  I cannot debug this, the breakpoints are ignored.

Best regards,
Duncan

**Comment by duncanspeidel** [comment]
If I set subject or body to just Title it fails with the exception shown in the first post.  It is clear to me that Title is not getting populated.  It is not clear how to fix that.

**Comment by andrewconnell** [comment]
it's been a very long time since I've worked with workflow, but if I recall, you can't set the "Title (LinkTitle)" property. That is dynamically generated by SharePoint. Try setting property "Title"

**Comment by duncanspeidel** [comment]
The drop down doesn't offer title.  It offers Title(LinkTitle) or Title(LinkTitleNoMenu).  I cannot enter free text.
![TitleChoices](https://user-images.githubusercontent.com/16256174/65331399-bdee6d80-db8a-11e9-98a1-95c3dae844ce.png)

**Comment by andrewconnell** [comment]
Sorry but I'm not sure... I'm certain you can't use the two "Title" options that you show in your screenshot. as those aren't real columns, they are dynamically generated based on the value in the "Title" field. As the screenshot in the article shows, you should have a column named "Title(Title)".

Looking back at the [3rd article in this series](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in), I see in the section **Modify the elements.xml file**, step 2, it shows the TItle field is added with the `DisplayName="Employee"` ... have you tried setting the **Employee** field in the workflow?

**Comment by duncanspeidel** [comment]
My employee.xml looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
  <!-- Parent ContentType: Item (0x01) -->
  <ContentType ID="0x01008CB8FAE3BA7C4894B8706227A7506CDB" Name="NewEmployee" Group="Employee  Orientation" Description="Represents a new employee" Inherits="FALSE" Version="0">
    <FieldRefs>
      <!--<FieldRef Name="Title" ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" DisplayName="Employee" />-->
      <FieldRef Name="LinkTitle" ID="{82642ec8-ef9b-478f-acf9-31f7d45fbc31}" DisplayName="Employee" />
      <FieldRef Name="Title" ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" DisplayName="Employee" />
      <FieldRef ID="{e532d801-1bb0-44ee-beca-c7b24eebda4e}" DisplayName="Division" Required="FALSE" Description="The division of the company where the employee works" Name="Division" />
      <FieldRef ID="{dd9bb4a5-2129-4cd8-bd95-a0e9b1086c65}" DisplayName="Orientation Stage" Required="TRUE" Description="The current orientation stage of the employee." Name="OrientationStage" />
    </FieldRefs>
  </ContentType>
</Elements>
```
I added the fields referenced in the **Modify the elements.xml file**.

**Comment by andrewconnell** [comment]
Repeating my last comment:

> have you tried setting the **Employee** field in the workflow?

Don't understand in the snippet why you have TWO references to the title field, one commented out. That's unnecessary.

What you've done in the **elements.xml** file is you've added the **Title** column to the content type, but you've renamed it to **Employee**. That's why in my last comment, I suggested trying to set the value of the **Employee** field because that's the Display Name of the Title field.

If that works, then it seems like there's an error in the doc.

**Comment by duncanspeidel** [comment]
Thank you, switching to employee worked.
