### ISSUE TITLE
Add an Application Customizer to SharePoint 2019 Sites

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-docs#4655]
#2813 ## Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I want to add an Application Customizer to a large number of sites In SharePoint 2019.

#### Observed Behavior

I've built and deployed an Application Customizer to SharePoint 2019. It's in the App Catalog, and I can add it to a site manually by going to Site Contents / New App / From Your Organization / Click on the Application Customizer. It gets installed and works as I would expect.

Now I want to add that same Application Customizer to many different sites in the SharePoint 2019 farm, so I've turned to PowerShell. The `Add-PnPCustomAction` cmdlet is available in the 2019 module, I can run it, and see that the app seems to be added by then running `Get-PnPCustomAction`. But the app actually never shows up in the site. 

Thinking the `Add-PnPCustomAction` cmdlet might not work properly in 2019, I've also tried CSOM directly:

``` powershell
		        $custAction = $customActions.Add()
		        $custAction.Name = $spfxExtName
		        $custAction.Title = $spfxExtTitle
		        $custAction.Description = $spfxExtDescription
		        $custAction.Location = $spfxExtLocation
		        $custAction.ClientSideComponentId = $spfxExtension_GlobalHeaderID
		        $custAction.Update()
		        $clientContext.ExecuteQuery()
```
Clearly, Application Customizers work just fine in 2019. But getting them added to sites at scale seems to be a problem. Any idea what the issue is here?

@juliemturner

**Comment by sympmarc** [comment]
New development: If I add the Application Customizer to a site with `Add-PnPCustomAction` and THEN add it manually, I end up with two instances running. (This Application Customizer adds some functionality into the header of the pages.)

It seems like `Add-PnPCustomAction' doesn't quite get it there, and the subsequent addition kicks it into gear. Not a solution, but maybe evidence of part of the problem.

**Comment by bcameron1231** [comment]
Hi Marc,

Can you try this...

```
//Install the app onto the site (Tenant Wide deployment doesn't exist on-premisess) where Identitity is equal to the ID of the app (Use Get-PnPApp if you need to)
Install-PnPApp -Identity <Guid>
```
Followed by
```
//Add Custom Action from component inside app
Add-PnPCustomAction -Name "YourExtensionname" -Title "ExtensionTitle" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentProperties "{YourJSON}"
```

**Comment by sympmarc** [comment]
Thanks for the suggestion @bcameron1231. When I run
``` powershell
Get-PnPApp # Gets me the GUID
Install-PnPApp -Identity <GUID>
```
I get an error that the app is already installed:
```
Install-PnPApp : {"odata.error":{"code":"-1, System.InvalidOperationException","message":{"lang":"en-US","value":"An instance of this App already exists at the specified location."}}}
At line:1 char:2
+  Install-PnPApp -Identity f22346fe-9287-4a44-a77a-e8eabbb2eae4
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Install-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Apps.InstallApp

```

**Comment by bcameron1231** [comment]
This is definitely true on the site you are currently working on because you manually added the app.

By chance did you run Add-PnPCustomAction multiple times? This will just register a custom action into the site. So you could have multiple registrations for the same custom action. Then when you manually added the app, the custom actions could finally load... but loaded for each registration.

I would start fresh.

1. I would remove the CustomActions using Remove-PnPCustomAction 
2. Remove the App using Uninstall-PnPApp
3. Install-PnPApp
4. Add-PnPCustomAction

**Comment by sympmarc** [comment]
See my addendum above. `Install-PnPApp` does indeed solve it.

Have I ever told you you rock?
