### ISSUE TITLE
onRenderCell() not called for all items in a large list when users scrolls whilst field customizer is being initialized

### ISSUE THREAD

**Issue by orbus-jmyron** [SharePoint/sp-dev-docs#4656]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

onRenderCell() is called for each cell even if the user starts scrolling through the document list before the field customizer is full initialized.

#### Observed Behavior

onRenderCell() is not called for some of rows that are in the process of being loaded due to the user scrolling the document list.

#### Steps to Reproduce

* Create a Field Customizer by following [these](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer) instructions.
* Create a list with 200 or more items (can be a document or item list).
* Debug the field customizer as per the instructions in the article.
* Keep scrolling down the list until the field customizer starts modifying the field.
* Scroll back up the document list. Note that some of the documents have not been customized.

This reproduces easily on Chrome and less frequently on Firefox on both Windows and OSX.

[Video](https://orbus-jmyron.github.io/spfx-fieldcustomizer-issue/) demonstrating the above.

**Comment by StevenDeRoover** [comment]
I have noticed the same issue

**Comment by orbus-jmyron** [comment]
Thanks for the potential work-around @StevenDeRoover.

It doesn't seem too make much of a difference for large document lists. Still seeing exactly the same broken behaviour with the work-around.

It does indeed seem to work most of the time for items list though.

**Comment by cytron201** [comment]
@andrewconnell Hi. This issue is affecting enhancements we've built in SharePoint and deployed to our customers. Is there any timeline for when it might be at least triaged? I've tried contacting Gold Partner support for this but have been told by the SharePoint support team that it's out of their scope to assist with. Are there other means by which we can escalate it? Thanks

**Comment by StevenDeRoover** [comment]
Bump: one of my colleagues (for which we created a field customizer) reported this issue again.  Appearantly it is still an open issue.  Is there an update on the status of this issue?

**Comment by kemesfun** [comment]
@orbus-jmyron I have added 100 items to a list with fieldcustomizers and so far I am not having this issue. I will see what happens after I add 100 more. Does this issue still repro?

**Comment by orbus-jmyron** [comment]
Hi @kemesfun,

We've not recently been doing any development around this area, so will need to set things up agai to try outn. I'll get back to you in a few days.

**Comment by orbus-jmyron** [comment]
Ok. So just dusted off the old sample project I had from when this was initially reported, and yes, this still reproduces.

Behaviour is actually slightly worse now, as it doesn't require the user to even scroll for the renderCell() calls to go missing.

The sample I'm using is still on 1.9.1 of the SPFX libs. Will try updating to latest version to see if anything changes.

**Comment by orbus-jmyron** [comment]
Just to confirm, issue still reproduces after the sample project is updated to 1.10.0.

**Comment by kemesfun** [comment]
@orbus-jmyron I created a list with 200+ items and still don't get this issue. I am not sure what is causing this issue at this point. Can you provide any more details on this repro?

**Comment by orbus-jmyron** [comment]
Can confirm this no longer seems to reproduce with the sample library I've been using.

Just eyeballing it, there definitely seems to be a change in how scrolling behaves and items renders since I last looked at this.
