### ISSUE TITLE
Site Collection App Catalog limitation?

### ISSUE THREAD

**Issue by a2life** [SharePoint/sp-dev-docs#4657]
In the site collection level app catalog, I am seeing the following behavior.
1. In the site collection app catalog page, (ie., https://CERTAIN.sharepoint.com/sites/CERTAINSITE/appCatalog/Forms/Allitems.aspx,  when you select an app in the listing and then go to Files tab,  and select "View Details Page" Icon,  It opens a page https://CERTAIN.sharepoint.com/sites/CERTAINSITE/_layouts/15/storefront.aspx?Source=/sites/somesite/_layouts/15/viewlsts.aspx#app="GUID_string_here",clg=1,vw=AppDetailsView.   This page is SharePoint Store page that says "Your administrator has removed the details of this app."   The same action taken in tenant level appCatalog will show "appCatalog&gt;Add App&gt;" and detail of the App.

2. You go to a sub-site of the site collection and click "Add Apps" It will display a list of Apps that you can add to the site, including the ones from the site collection level app catalog.  However, clicking "App details",  it opens storefront.aspx again but this time with the error message showing "Invalid App ID:&lt;GUID String here&gt;"  Tenant level app shows App detail with 'Add' or  "new version is available, 'GET IT' " action button as appropriate.

So either case, one can not see 'details' page of the app.   This calls for a challenge in updating the app since "Get It" button is in the detailed page. ...Installing the app is not a problem as you just need to double click on app icon in apps selection page, but once installed the App will disappear from 'Apps you can add' display.   (I ended up creating a web part app that uses ALM API to upgrade a selected app. This appears to be working)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb134fd8-6880-360a-faea-7eb0eedca2d9
* Version Independent ID: 16f799b7-deff-b125-ceed-343933bcbe79
* Content: [Use the site collection app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)
* Content Source: [docs/general-development/site-collection-app-catalog.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/site-collection-app-catalog.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm not following the steps outlined. You say:

> when you select an app in the listing and then go to Files tab

What **Files** tab? Can you provide screenshots to what you're seeing? Checked two tenants (one SR & one TR) and both show the details page after installing the app when selecting "app details"

**Comment by a2life** [comment]
Firstly, this is only happening in the apps from site collection level App Catalog.  Apps from tenant level App Catalog is working fine.
As to file tab, Here is a screen shot
![filetab](https://user-images.githubusercontent.com/2119984/67438322-20d78800-f5c1-11e9-80de-878ce4aa6db2.png)

Clicking on "view details page" shows this error message
![removed_detail](https://user-images.githubusercontent.com/2119984/67438375-4c5a7280-f5c1-11e9-9e27-d6f5cb37aefa.png)

If I go 'Add Apps' route and click app detail link of the same app..
![apps_you_can_add](https://user-images.githubusercontent.com/2119984/67438418-6e53f500-f5c1-11e9-8c90-22a69f3f2110.png)

This error page shows up.
![invalid_app_Id](https://user-images.githubusercontent.com/2119984/67438483-99d6df80-f5c1-11e9-972b-3fb3a9f8351e.png)

There are some other apps in the 'Apps you can add' listing that is from Tenant level app catalog.  Those app shows detail page as expected.

If I go to Site Content page (modern page)  and right click on  installed App,  the one from tenant level app catalog shows three options (Details, Monitor, Remove).  The apps installed from Site collection app catalog  only shows two (Monitor, Remove)

I originally reported this in sp-dev-fx-webpart section but closed out because I did not think that was  the right forum ([See above thread](https://github.com/SharePoint/sp-dev-fx-webparts/issues/568)) . From the comment I received to that posting, I don't think its just me experiencing this issue.

**Comment by matthong** [comment]
We are having the same issue with Site Collection App catalog.
