### ISSUE TITLE
Office 365 Dark Themes Quick Edit Problem with Dropdown controls

### ISSUE THREAD

**Issue by miguelisidoro** [SharePoint/sp-dev-docs#4659]
Hello.

The Office 365 Dark Yellow and Dark Blue themes have been recently updated and now when a user is now in Quick Edit mode in a SharePoint List, and fills a Choice or Lookup Field (using a DropDown control) both the Dropdown background color and the text color are white, which makes the text unreadable (check the attached image). I am able to create a custom theme where I can control the text color but the Dropdown background color is not controlled by any of the theme settings and it always has the white background color regardless of the theme. This however seems to be a recent update by Microsoft and the customer who reported this says that a few weeks ago, this was not happenning. I was able to create a custom theme using the UI Fabric Theme Designer at https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html but was only able to control the text color and make the dropdown slightly more readable by darkening the whole theme text color to grey instead of white. Questions:
  1 - Is there a way to control the background color of a dropdown control in quick edit mode in a Office 365 theme setting? I didn’t find it…
  2 - Are you aware of any recent change that Microsoft applied to Dark Themes? I know that Quick Edit was recently updated to allow List and Column Formatting

If possible, allow a theme parameter in the JSON schema to allow the background color of dropdown controls and if possible change the dark themes dropdown colors to the same dark theme color by default.
![O365Theme](https://user-images.githubusercontent.com/5429152/65235454-891ce080-dace-11e9-9835-91d1228f26e7.png)

**Comment by andrewconnell** [comment]
This isn't a dev topic... this is more OOTB, so I'm going to tag it as such which will close it. But Also tagging as uservoice because this implies a feature request:

> ... allow a theme parameter in the JSON schema...
