### ISSUE TITLE
SP2019

### ISSUE THREAD

**Issue by jeffangama** [SharePoint/sp-dev-docs#4664]
What about sharepoint 2019 deployment options ? Is includeClientSideAssets supported ? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1320b802-156c-5d77-db79-b211b66d4b2f
* Version Independent ID: efe018a3-001e-e097-a96c-66ab1786afe5
* Content: [SharePoint Framework development with SharePoint 2016 Feature Pack 2](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support#feedback)
* Content Source: [docs/spfx/sharepoint-2016-support.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-2016-support.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Nope... that feature uses the Office 365 CDN which doesn't exist on-prem.
