### ISSUE TITLE
The code shown doesn't work

### ISSUE THREAD

**Issue by duncanspeidel** [SharePoint/sp-dev-docs#4666]
Hi,

The if statement that checks "Not started" fails.  It seems to fail because of the space between Not and started.  If I have:
    if (orientationStageValue == "Not started") {
        return "&lt;span style='color:red'&gt;" + orientationStageValue + "&lt;/span&gt;"
    }
Those with a status of "Not Started" are not shown in Red.  If I change the code to have no space in "Not Started" so it becomes "NotStarted" I can check using:
    if (orientationStageValue == "Notstarted") {
        return "&lt;span style='color:red'&gt;" + orientationStageValue + "&lt;/span&gt;"
    }
and this works.  I tried checking using ASCII encode space (Not%20Started) but that didn't work.  Is there a string compare function we should use here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483f6043-0f8e-17cf-5905-5e6a9b619044
* Version Independent ID: 47268bda-6881-8848-1874-2e621c8c157b
* Content: [Add custom client-side rendering to a SharePoint-hosted SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-custom-client-side-rendering-to-a-sharepoint-hosted-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/add-custom-client-side-rendering-to-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-custom-client-side-rendering-to-a-sharepoint-hosted-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This is an easy thing to test... can you just write the contents of the `orientationStageValue`? That will tell you what the value is that is returned and if the doc is incorrect.
