### ISSUE TITLE
Is there a way to merge LocalizedResources outputs?

### ISSUE THREAD

**Issue by kmprasad4u** [SharePoint/sp-dev-docs#4667]
Is there a way to merge LocalizedResources outputs using WebPack ? 
Eg. All en-us strings into a single file.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
Context?

**Comment by kmprasad4u** [comment]
Using SPFx Framework v1.9.1 in SharePoint Online. 

We are looking at optimizing load time (especially in IE 11), and hence looking at reducing the number of requests for loading the localized resource files.

**Comment by andrewconnell** [comment]
You can't merge the localization files in SPFx solutions. They are loaded based on the filename which defines the locale on demand by SPFx based on the site & browser setting of the user. So only one bundle + one localization file is loaded for each user anyway.
