### ISSUE TITLE
Webparts not reloaded on page change for pages created from a page template

### ISSUE THREAD

**Issue by hosoistreet** [SharePoint/sp-dev-docs#4670]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When navigating between different modern pages that have been created from the same page template the webparts are not reloaded.

#### Observed Behavior

We have a SP online site with modern pages. These pages have been created using a page template to speed up content authoring. The page template has several webparts on it, such as out of box document library webpart.

After publishing the pages, during navigating, we are seeing that these webparts are not being reloaded. Instead they still show the content of the previous page. 

We also notice that some other out of the box properties of the page do not load correctly such as the last publish date for the page. 

In order to get the page to load properly we have to force a full page reload.

For the problematic pages, a workaround is delete all webparts from the page and readd them. As the site is quite large we are hoping to avoid this, and we also want to still use the page template for future content authoring.

**Comment by patmill** [comment]
That's a bit strange.  Just to double check, if you create 3 pages manually with the exact same configuration and navigate around, everything works fine?

**Comment by hosoistreet** [comment]
Yes manual pages work fine. 

I can recreate the issue by following these steps:

1. Create out of the box blank page.
2. Add out of box document library web part on it.
3. Save as a template.
4. Create 2 new pages from this template, pointing the webpart to different document libraries.
5. Save and publish the pages.
6. Update the standard top navigation with links to these pages.

When clicking between the pages in the top navigation the document library web part does not update correctly. To make it work have to force a full page refresh.

This tenant is on targeted release. 

I was unable to recreate the issue in our own development tenant also on targeted release.

Going to see if can recreate the issue on another Comms site on the tenant with the issue.

**Comment by hosoistreet** [comment]
Any update on this issue please?

**Comment by hosoistreet** [comment]
Hellllooooooooo, response?

**Comment by beavisnz** [comment]
Any updates on this?
