### ISSUE TITLE
Apply to folders

### ISSUE THREAD

**Issue by orso295** [SharePoint/sp-dev-docs#4671]
How can I use this approx with folders also?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/it-it/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you be a bit more specific in your question? It's not that clear when you say "*this approx with folders*"

**Comment by orso295** [comment]
I'd like to use "Conditional formatting based on the value in a text or choice field (advanced)" also for folders like files

**Comment by bcameron1231** [comment]
Folders don't have the same metadata columns as items in your list. So you wouldn't be able to reference the other columns, but you could reference the Name column. Be aware this column is technically not supported (even though it can work).  

However,  there is also a UX change as a result. When you see a folder by default, it's a button to click into the folder. When you use column formatting, this link goes away and you are forced to double click to navigate into the folder.

My advice would be to tread lightly here, is it's not exactly supported currently... even though you can apply formatting to the folder.
