### ISSUE TITLE
Force Reload of Hub Site Navigation

### ISSUE THREAD

**Issue by patrick-rodgers** [SharePoint/sp-dev-docs#4674]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When doing mass updates for navigation (a migration for example) many updates are required to the navigation at all levels - which are then intended to roll-up to the hub sites to which the sites are associated. Currently there is no way to trigger an "update" of the cached hub site navigation from script.

A method is discussed in [this thread](https://github.com/SharePoint/sp-dev-docs/issues/2529) but manual intervention is not practical when dealing with the creation of 1000's of sites.

When the navigation does not update stakeholders will not approve changes or resist until the site is visually correct as they want to see it causing confusion, csat issues, or delays.

**Ask: provide a client callable method to trigger a cache refresh for hubsite navigation to assist with these scenarios.**

#### Observed Behavior

It takes an unknown amount of time for the navigation to update.

**Comment by andrewconnell** [comment]
Hate to do this to THE @patrick-rodgers , but this is a feature request which should be posted to user voice :)
