### ISSUE TITLE
What does PnP Modernizer actually do?

### ISSUE THREAD

**Issue by dem123-cthulu** [SharePoint/sp-dev-docs#4676]
I thought that I can customize my company webpart mappings using pagelayoutmapping.xml and it will be the schema used for all transformations from classic to modern.
I cannot, however, find a way to upload/apply customized mapping.xml to a page and the support claims it's impossible.
So why would you publish all this info about transformation functions etc. if I can't use it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000d65e3-ca4c-d7f2-6b1a-42d71119567f
* Version Independent ID: 5e9fb753-f825-e387-33f1-d4108c9ff419
* Content: [Page Transformation Functions and Selectors](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-api#feedback)
* Content Source: [docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages-api.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
This library  transformation classic wiki page / web part pages / publishing pages to modern Site Page.

Below github demo shared a sample project to do this

https://github.com/SharePoint/PnP/tree/dev/Samples/Modernization.PageTransformation

[Webpart Mapping](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#web-part-transformation-list-updated-for-september-2019-release)

[Page layout mapping](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-layout)

**Comment by dem123-cthulu** [comment]
Thanks. The key part I was missing was that you upload your customized webpartmappings.xml file to Azure Function. 

Does MS support know about the Modernizer? 
_"Did you want to change classic page to modern page?
If so, then it is not what a PnP modernizer does."_
https://social.technet.microsoft.com/Forums/msonline/en-US/b4aa40bc-bcb1-47cf-8983-d57ed6e5ed3c/pnp-modernizer-mappingsxml?forum=onlineservicessharepoint
