### ISSUE TITLE
Syntax error in provided Connect-SPFarmToAAD function

### ISSUE THREAD

**Issue by smotti** [SharePoint/sp-dev-docs#4683]
This syntax error seems to present since 2013: https://social.msdn.microsoft.com/Forums/en-US/00ba9320-4942-4c5b-9a14-fa1132d2248e/use-an-office-365-sharepoint-site-to-authorize-providerhosted-apps-on-an-onpremises-sharepoint?forum=sharepointdevelopment

The error:

```
Set-MsolServicePrincipal : Invalid syntax.  Parameter Name: ServicePrincipalNames.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\MySharePointFunctions\MySharePointFunctions.psm1:103 char:9
+         Set-MsolServicePrincipal -AppPrincipalId $SPAppPrincipal.AppP ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Set-MsolServicePrincipal], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.StringSyntaxValidationException,Microsoft.Online.Administration.Auto
   mation.SetServicePrincipal
```

The value to `-ServicePrincipalNames`, `$SPAppPrincipal.ServicePrincipalNames`, must be in double-quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58462e32-ad55-2351-ee7d-67c047fa4157
* Version Independent ID: 0cba1f85-d95c-6b4e-583d-608a6743e15f
* Content: [Use ACS to authorize low-trust provider-hosted add-ins on an on-premises SharePoint site](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on#feedback)
* Content Source: [docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not clear what you mean... are you saying the values within the property should be in quotes or the property reference should be in quotes? Can you provide a sample that does work to see how it differs from the docs?
