### ISSUE TITLE
Add potential solution related to error in article

### ISSUE THREAD

**Issue by Marweis** [SharePoint/sp-dev-docs#4685]
Error: The e-mail message cannot be sent. Make sure the outgoing e-mail settings for the server are configured correctly

In SPO, this error can also be thrown if the IP Address of the recipient is blocked by a spam filter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a7796d-ff03-d501-8b08-e1b3ccef37d6
* Version Independent ID: 20f31996-9ed1-64a4-592b-b46ac4e20833
* Content: [Common error messages in SharePoint workflow development](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/common-error-messages-in-sharepoint-workflow-development#feedback)
* Content Source: [docs/general-development/common-error-messages-in-sharepoint-workflow-development.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/common-error-messages-in-sharepoint-workflow-development.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good point... will be good to have this extra not in the comments for the doc.
