### ISSUE TITLE
Is there a SP TypeScript library or not?

### ISSUE THREAD

**Issue by Katydude** [SharePoint/sp-dev-docs#4686]
I am confused by this page and by the various reference materials regarding TypeScript for SharePoint. There's a whole area dedicated to a SharePoint TypeScript "library" at https://docs.microsoft.com/en-us/javascript/api/overview/sharepoint?view=sp-typescript-latest but there seems to be no actual reference anywhere to a typed package that I can install and use to access SharePoint data. I have to be missing something obvious, right? So sorry if I am.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142aa03b-97e7-1755-bf21-dcda38a6fe24
* Version Independent ID: 5516201f-4576-16c9-b5bb-39fee234506a
* Content: [SharePoint Framework development tools and libraries](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tools-and-libraries#feedback)
* Content Source: [docs/spfx/tools-and-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tools-and-libraries.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
The SPTypeScript library details includes lasses, methods, and other types available will be started in this section link:

[https://docs.microsoft.com/en-us/javascript/api/sp-application-base?view=sp-typescript-latest](url)

**Comment by Katydude** [comment]
I'm sorry. I don't understand what this means. Are you saying that there is
no code library yet but there soon will be?

**Comment by Jerry0527** [comment]
Sorry for the typo, I have updated the link and it's the latest SPTypeScript Library reference.

**Comment by Katydude** [comment]
Yes, I can see that it is a reference but where is the download of the
SPTypeScript library that I can use with my TypeScript project? What is
this a reference for? It's just a bunch of definitions. Where is the source
library that this reference describes?

**Comment by andrewconnell** [comment]
@Katydude There's no TypeScript library for SharePoint provided by Microsoft. This doc is referring to the SharePoint Framework (SPFx), which contains type declarations for all the objects & methods in the SPFx API. There's nothing to install... it's part of the project when you create a new SPFx project.

I believe years ago there was a set of type declarations created by the community for the SharePoint JSOM, but that's not what this page is referring to.
