### ISSUE TITLE
Unable to fill text input

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#469]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Usable text input fields in IE outside the workbench.

#### Observed Behavior
When using a text <input> field in a SPFx webpart in IE. I'm unable to fill in a value when using it outside the workbench.

#### Steps to Reproduce
1. Create a new SPFx project (I did this using generator 1.0.0)
2. Add a text input, like: `<input type='text' value='test' />`
3. Place the part in a page (classic of modern doesn't make a difference)
4. You won't be able to change te text in the input

**Comment by RoelVB** [comment]
I guess no one is using Internet Explorer anymore?

**Comment by RoelVB** [comment]
It seems that this issue got resolved.

So this issue can be closed.

**Comment by amishra0909** [comment]
Thanks for confirmation @RoelVB. I am closing this issue now.
