### ISSUE TITLE
 Command set extension in Picture Library - SPFx

### ISSUE THREAD

**Issue by Carolinavv** [SharePoint/sp-dev-docs#4691]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> I want to show a command extension on a commanBar Picture library but it is not giving results.
I understeand that i must configure the element.xml file ,RegistrationId and RegistrationType fields, but i can't find the way to make it work.

**Comment by bcameron1231** [comment]
Can you share your elements.xml file with us?

**Comment by Carolinavv** [comment]
`Title="MyExtension`
`RegistrationId="109"`
`RegistrationType="List"`
`Location="ClientSideExtension.ListViewCommandSet.CommandBar"`

**Comment by bcameron1231** [comment]
Can you provide a bit more information for us? SharePoint version/SPFx version and your deployment process?

**Comment by Carolinavv** [comment]
- I use spfx v1.7.0.
- To deploy the extension i do the solution package with
 `gulp bundle --ship`
 `gulp package-solution --ship`

   and then i upload the file to my AppCatalog

**Comment by bcameron1231** [comment]
And are you using tenant wide deployment or manually adding the apps to your site?

**Comment by Carolinavv** [comment]
I'm adding manually the apps to my site

**Comment by andrewconnell** [comment]
Have you tried upgrading the project to the latest version of SPFx (v1.9.1) to see if there is any change?

**Comment by OS-Lee** [comment]
When I test this in my environment(SPFx 1.8.2), I found the RegistrationId revert to default 100 in SPFx package, check the image below.

![image](https://user-images.githubusercontent.com/40845109/65938894-e44bbd00-e456-11e9-949d-319271005fc9.png)

This cause extension doesn't apply to Picture library.

So I use 7-zip to edit the RegistrationId to 109 and redeploy the solution to tenant(uninstall the solution from target site, remove from recycle bin), re-add the app to target site, and it works now.

![image](https://user-images.githubusercontent.com/40845109/65939029-3ee51900-e457-11e9-886c-3dd6740ba845.png)

**Comment by andrewconnell** [comment]
When you shared the **elements.xml** file above, that's the one in the **./sharepoint/assets**, correct? 

You're saying when you built the project, the build process changed the registration ID?

**Comment by Gowtham171996** [comment]
Yes the above solution worked for me too. I did the same for the Site pages with Registration Id to 119.
Uninstall and Reinstall is also a crucial step. And dont forget to change the version of the app.

**Comment by OS-Lee** [comment]
@andrewconnell  the **RegistrationId**  of elements.xml in **/sharepoint/assets** is set to 109, when package the solution,  the **RegistrationId**  of elements.xml in package(.sppkg) and **/sharepoint/solution/debug/featureid** both set to 100.

**Comment by andrewconnell** [comment]
@OS-Lee / @Carolinavv 

Do you have a repro solution (link to public GH repo) you can share that shows this?

**Comment by OS-Lee** [comment]
@andrewconnell 

I publish my test demo to github https://github.com/OS-Lee/ListExtension , the demo just official demo, nothing special.

**Comment by OS-Lee** [comment]
After I update ListTemplateId(ListTemplateId="109") of ClientSideInstance.xml to keep the same as elements.xml(RegistrationId="109") and package, the RegistrationId="109" set to correct value now.
