### ISSUE TITLE
Webpack configuration specifically because of empty rule tests

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#4692]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Documentation on default webpack configuration. More specifically the generatedConfiguration.

#### Observed Behavior
I case additional loader or configuration changes should be added the webpack configuration the following script can be used:

```javascript
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    /** Do something **/
    return generatedConfiguration;
  })
}
```

There is just one big question mark in case of the generatedConfiguration this object passed to the function contain the folliowing content.

```json
{
  "module": {
    "rules": [
      {
        "use": [
          {
            "loader": "/Volumes/Code/research/webpack-performance/node_modules/@microsoft/loader-load-themed-styles/lib/index.js",
            "options": {
              "async": true
            }
          },
          {
            "loader": "/Volumes/Code/research/webpack-performance/node_modules/css-loader/index.js",
            "options": {
              "minimize": true
            }
          }
        ],
        "test": {}
      },
      {
        "use": [
          {
            "loader": "/Volumes/Code/research/webpack-performance/node_modules/@microsoft/loader-cased-file/lib/index.js",
            "options": {
              "name": "[name:lower]_[hash].[ext]"
            }
          }
        ],
        "test": {}
      },
      {
        "use": [
          {
            "loader": "/Volumes/Code/research/webpack-performance/node_modules/html-loader/index.js"
          }
        ],
        "test": {}
      },
      {
        "test": {},
        "enforce": "pre",
        "use": "/Volumes/Code/research/webpack-performance/node_modules/source-map-loader/index.js"
      }
    ],
    "noParse": [
      {}
    ]
  },
  "resolve": {
    "alias": {},
    "modules": [
      "node_modules",
      "lib"
    ]
  },
  "context": "/Volumes/Code/research/webpack-performance",
  "devtool": "source-map",
  "mode": "development",
  "entry": {
    "high-performance-web-part": "/Volumes/Code/research/webpack-performance/lib/webparts/highPerformance/HighPerformanceWebPart.js"
  },
  "externals": [
    "@microsoft/sp-lodash-subset",
    "@microsoft/sp-core-library",
    "@microsoft/sp-office-ui-fabric-core",
    "@microsoft/decorators",
    "@microsoft/sp-diagnostics",
    "@microsoft/sp-dynamic-data",
    "@microsoft/sp-polyfills",
    "@microsoft/sp-http",
    "@microsoft/office-ui-fabric-react-bundle",
    "@microsoft/sp-page-context",
    "@microsoft/sp-loader",
    "@microsoft/sp-component-base",
    "@microsoft/sp-property-pane",
    "@microsoft/sp-webpart-base",
    "@microsoft/sp-extension-base",
    "@microsoft/sp-application-base",
    "@microsoft/sp-client-preview",
    "@microsoft/sp-webpart-workbench",
    "webpack-performance",
    "react",
    "react-dom",
    "HighPerformanceWebPartStrings"
  ],
  "output": {
    "chunkFilename": "[id].[name]_[chunkhash].js",
    "filename": "[name].js",
    "library": "8d5e0295-b233-4295-9930-9c048ba0438c_0.0.1",
    "libraryTarget": "amd",
    "path": "/Volumes/Code/research/webpack-performance/dist",
    "devtoolModuleFilenameTemplate": "webpack:///../[resource-path]",
    "devtoolFallbackModuleFilenameTemplate": "webpack:///../[resource-path]?[hash]"
  },
  "plugins": [
    {
      "options": {
        "scriptName": {
          "name": "\\/[name](_[a-z0-9-]+)*\\\\.js",
          "isTokenized": true
        }
      }
    },
    {
      "definitions": {
        "process.env.NODE_ENV": "\"dev\"",
        "DEBUG": true,
        "DEPRECATED_UNIT_TEST": false,
        "NPM_BUILD": false,
        "DATACENTER": true
      }
    }
  ]
}
```

More specificly the rules all contains empty tests to check which file which loader should use. So the question is how does it work and is this supposed to work? Why multiple rules when basically are all for any project.

I guess there must be some black magic happing with the webpack configuration behind the scenes because it basically works somehow.

**Comment by andrewconnell** [comment]
My understanding is that when there's no `test: {}` specified, everything is passed into the loader. The loaders may have their own filter logic in them. In other projects, I've seen where `test:{}` is the default value so since the config is built in memory & you're just writing it out, you might just be seeing the default.

**Comment by StfBauer** [comment]
Well not really. The "In Memory" webpack configuration is invalid where it will be applied and still has the same empty tests in there for one. (Could be that I look at the wrong place)
Second, it doesn't make sense to apply all the rules on files in the `lib` folder when there are different files in there. CSS/JS mostly.

**Comment by andrewconnell** [comment]
@StfBauer said:
> Well not really. The "In Memory" webpack configuration is invalid where it will be applied and still has the same empty tests in there for one. (Could be that I look at the wrong place)

Then how does it work if it's invalid? If you don't do anything, that's what it uses & it builds... so... what's invalid about it?

@StfBauer said:
> it doesn't make sense

Agreed, but that's more a matter of opinion than a fact ;)

**Comment by StfBauer** [comment]
Well, that is the big mystery. Well like I send I saved the configuration that goes right in the Webpack process. I might need to have a third look into that. 😀

> Agreed, but that's more a matter of opinion than a fact ;)

In case of Webpack more a fact than opinion. For example in the case of "loader-load-themed-styles" and CSS loader only CSS should be affected and not really a JavaScript.
