### ISSUE TITLE
Running SharePoint Bulk Profile Update results in Error

### ISSUE THREAD

**Issue by mhunter86** [SharePoint/sp-dev-docs#4698]
### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I am trying to implement a bulk update for SharePoint Online user profiles as documented here: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#check-the-status-of-an-import-job

I have uploaded a JSON file to a SharePoint site, which should be processed and upload custom values to custom fields and update everyone's profiles in SharePoint.

#### Observed Behavior

When running the "updateUPA.ps1", the script successfully logs into the document library and takes the JSON and creates a Job ID:

Value : 00000000-0000-0000-0000-000000000000
Import job created with following identifier: bf683310-62a8-41b4-ac3e-2e89668dbabb
Import job state is Submitted 

After a few moments it transitions to "Processing" as expected.
Write-Host "Import job state is" $job.State
Import job state is Processing 

The error occurs after about 2 hours 30 minutes of Processing.
Write-Host "Import job state is" $job.State
Import job state is Error 

I have no information on what this error is.  No logs are produced along side the JSON file in the SharePoint Document library and no profiles are updated.  I have no way of knowing if it is timing out (we have about 1600 employees) or if there is some other error.

#### Steps to Reproduce

I am running the commands in Power Shell.  I created a default SharePoint site to house the JSON and logs if any were produced.  This is consistent with my tenant, but cannot seem to be reproduced elsewhere. (Microsoft Rep performed test in Dev successfully)

#### Submission Guidelines

The Microsoft SharePoint Developer I was working with had never seen this error occur before and suggested I submit the issue here.

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. If this is a capability question/discussion, please use the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint).

If it is an issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
