### ISSUE TITLE
Missing git installation in "Setup your machine" section

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#47]
Git installation and configuration is missing in the "[Setup your machine](https://github.com/SharePoint/sp-dev-docs/wiki/Setup-your-machine)" section.

Just in case git is not installed cloning of the generator will fail because it is a core requirement for Yeoman.

**Comment by chakkaradeep** [comment]
We do not have generator source code available. You shouldn't be needing to install git unless you are using it as your version control system.

**Comment by StfBauer** [comment]
Yeoman lists it as a prerequisite before you install [yeoman](http://yeoman.io/codelab/setup.html).
In fact I know many scenarios where packages will be directly fetched from github that eventually fail without git.
For this it does't matter if you have published your source code or not.

**Comment by wictorwilen** [comment]
That requirement listed on that page is if you want to build your own generator, which is not the case, right?

**Comment by chakkaradeep** [comment]
To use the generator, you do not need git. I would like to know more which component of yeoman requires that.

**Comment by StfBauer** [comment]
First there is no QA involved in NPM. You can publish there whatever you want. An no one will check what you pulish there. 
Second you can add depenedecies to git repositories directly to package.json and you will never know when this happens nor can guarantee that this will not happen. In this case parts of a package will be downloaded directly from github and not from NPM.
It is valid in NPM packages.
You can simply try it out using the [trash-xyz-stfbauer](https://www.npmjs.com/package/trash-xyz-stfbauer).
You can simply install it with
```npm install trash-xyz-stfbauer```
and will install express via github and not via NPM.

Sometimes you are unable to download directly from NPM in this case also the github url will be used based on the information available in the package.json.
To guarantee everthing is working in most cases you should have git installed even if you don't use it for your development.

**Comment by patmill** [comment]
Would adding an entry to the Optional Tools section w/ a description of why it is useful?   We've gotten a fair amount of feedback on the list of pre-reqs, so we've been attempting to pare them down to the minimum.

**Comment by patmill** [comment]
Updated machine setup docs.
