### ISSUE TITLE
How do I update a SharePoint list with form data that is on my SPFx React webpart?

### ISSUE THREAD

**Issue by yarrahdevi** [SharePoint/sp-dev-docs#4702]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have successfully created a webpart using SPFX and React framework. So far, the webpart is set up with page routing that displays each page accordingly. The tutorial I followed to achieve this is located here: 
https://sharepointlessons.wordpress.com/2019/03/18/building-an-app-with-spfx-react-and-typescript-part-1-stateless-functional-components/ 
I have worked my way up to Part 3 in the tutorial link above. 

I understand that I can use PnP.js to manage data access between SharePoint lists and my webpart, however I am fairly new to Pnp.js and SPFx development in general. What I am trying to achieve involves:

<ol>
<li>Setting up a form on my webpart (not on the property panel), and sending that form data to a SharePoint list upon clicking the save button</li>
<li>Retrieving data from existing SharePoint lists to populate drop-downs in this form</li>
<li>Accessing SharePoint list data and displaying them on different views on my webpart</li>
<li>Filtering the retrieved data by logged in user</li>
</ol>

Can some guidance be offered to point me to tutorials to achieve this functionality please?
Thank you very much!

**Comment by andrewconnell** [comment]
There are multiple ways to write to a SharePoint list... PnPJS is one, the SharePoint REST API is another. Look at this repo for lots of SPFx samples, including React samples and a sample on using SP REST: https://github.com/SharePoint/sp-dev-fx-webparts... specifically this CRUD example: https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/sharepoint-crud. Many of the projects in that repo are outdated but you get the picture.

Also check out the SPFx training: https://aka.ms/spfx-training that contains plenty of starting points.
