### ISSUE TITLE
SPFx multi component solution issue

### ISSUE THREAD

**Issue by meerapan** [SharePoint/sp-dev-docs#4703]
I'm working on an SPFx solution with multiple components - 2 webparts and 2 listview commandsets(command bar, context menu). Upon deploying the package to App Catalog, while the webparts seem to work fine, only one of the extensions is activated and not the other one.

elements.xml has 2 <CustomAction> elements, one for each extension, 
ClientSideInstance.xml has 2 <ClientComponentInstance> elements, one for each extension.

But still no luck, wonder what's missing. Appreciate any help.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by andrewconnell** [comment]
Did you do one deployment or multiple deployments to the app catalog & installation of the apps? If you did multiple, did you bump the version of the package and upgrade it? 

If not, SharePoint has no way to know that there are features that should be reactivated with new things to provision - ie: if you test it with one extension and later added the 2nd one, the 2nd one would not be provisioned unless the package version was bumped.

**Comment by meerapan** [comment]
Thanks for the reply @andrewconnell.

I've always been deleting the previous package from the app catalog and uploading a new package and on sites, it was a new installation every time. But never worked.

**Comment by andrewconnell** [comment]
Need more info then, like sharing your project, sharing the **package-solution.json** file, **element.xml** files, etc... should have worked... so something else may be going on.

**Comment by meerapan** [comment]
I'll see how I can share my project/ package-solution, element.xml files. Will post details here.

**Comment by andrewconnell** [comment]
Just copy the contents (_not the actual file, just their contents_) of those files into a comment... please use [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to make it readable
