### ISSUE TITLE
content-security-policy-report-only throws errors for anonymous users

### ISSUE THREAD

**Issue by BeccaAtAcumen** [SharePoint/sp-dev-docs#4707]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
-
We are using SharePoint modern pages for our public web site, yes I know it was a terrible idea but it was not mine. SharePoint is injecting the CSPRO header but the reporting page is not accessible to anonymous users which is every user of our public web site. I can find no documentation on how to disable this header. 

#### Expected or Desired Behavior

Configuration of SharePoint can be updated to remove this header

**Comment by andrewconnell** [comment]
This isn't something you can disable.

**Comment by BeccaAtAcumen** [comment]
Thank you Andrew for the confirmation. We're using our load balancers to strip the header off but I was hoping for a slightly more elegant approach. Guess the brute force solution is all we have.
