### ISSUE TITLE
MSGraphClient does not seem to work for most of the Guest user

### ISSUE THREAD

**Issue by gurubn** [SharePoint/sp-dev-docs#4709]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the MSGraphClient as guest user, it should return data

#### Observed Behavior

MSGraphClient  used in an SPFx web part does not seem to work for most of the Guest user from September 23rd onwards
For me, This issue seems to be similar to https://github.com/SharePoint/sp-dev-docs/issues/3722.
We have a SPFx web part leveraging MSGraphClient. This web part works fine for Internal employees (Account present in AD), but stopped working for  Guest accounts
from September 23rd (before that it used to work well for Guest account from past 3-4 months). Console log error looks like below.
![MsGraphClientError](https://user-images.githubusercontent.com/23011566/66110029-3101d600-e5c6-11e9-8254-63f405ef022c.png)

Anybody else having similar issue ?. Any directions on  how to fix the problem for Guest accounts ?. 

Steps to Reproduce
using SPFx 1.6
When a guest (from another tenant) tries to use a spfx webpart that uses the MSGraphClient, the endpoint returns the error: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint.

Thank you in advance!.

**Comment by kuku82** [comment]
Hello, is there any update on this issue?

**Comment by gurubn** [comment]
Unfortunately no. We are still struggling with the issue. I have raised Microsoft Support ticket as well on this and they are looking into it

**Comment by kuku82** [comment]
Thanks for the update. I assume none of the Teams Apis are working for you for guest users?

**Comment by gurubn** [comment]
The issue fixed now through regular Microsoft support ticket. Unfortunately, the Product Group did not disclose any information about root cause. Anyways, I am happy that issue is fixed.
@kuku82 : Recently PG has pushed some fix around this it seems. You can check if things are working for you. 
I will mark this Github issue as closed (as Issue seems to be fixed for us and many other customers who raised similar issue through Microsoft Support ticket)
