### ISSUE TITLE
Image Not Found

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#471]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I expect an image to appear.

#### Observed Behavior
Image gives 404.

#### Steps to Reproduce
I have a header component that has the following:

```
import { Component } from '@angular/core';

@Component({
 selector: 'layout-header',
 template: `<div><img src="{{headerImgSrc}}"></div>`
})
export class HeaderComponent {
 constructor() {}

 private headerImgSrc = require('./FormHeader.png');
 name: string = 'Requirement';
}
```

I see in the /dist/ folder there is the FormHeader_<somelongstring>.png. However, after running `gulp serve` to see the local workbench, the image is showing a 404 as it is looking for the image in the /temp/ directory, not the /dist/ directory.

The HTML generated is as follows:

`<img ng-reflect-src="formheader_a211966eff7592363e4d08aa53fe9f3c.png" src="formheader_a211966eff7592363e4d08aa53fe9f3c.png">`

**Comment by webtechy** [comment]
Any ideas on this one?

**Comment by amishra0909** [comment]
Thanks for the feedback @webtechy. We are investigating this issue.

**Comment by iclanton** [comment]
It looks like you're missing a `require('set-webpack-public-path!);` line from your bundle's entrypoint. See some docs here: https://dev.office.com/sharepoint/docs/spfx/toolchain/sharepoint-framework-toolchain

This will get much easier in the next drop - we've built this functionality into the build tools.

Please reopen this issue if you're still having this issue.
