### ISSUE TITLE
Script doesn't change references in HTML file if more than 999

### ISSUE THREAD

**Issue by bhanuchintha** [SharePoint/sp-dev-docs#4711]
Hello Team, 

I am using this script for converting HTML/HTM to ASPX and i observed that when a HTML file has reference links to other HTML/HTM files of more than 999 - The complete file content references are not changed and remained as is. Can you please let me know how to handle this scenario.

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46053cad-6e95-c45d-608f-5262c31b0eeb
* Version Independent ID: 641cf9a1-7e4c-ea58-dd55-dcb80b80435d
* Content: [Migrating from the permissive browser file handling to the default strict browser file handling](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting#feedback)
* Content Source: [docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-permissivesetting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bhanuchintha** [comment]
@Team, Any update on this issue.

**Comment by andrewconnell** [comment]
Not clear what you mean by:

> i observed that when a HTML file has reference links to other HTML/HTM files of more than 999

Can you elaborate with more details?
