### ISSUE TITLE
sp-dev-docs/docs/spfx/use-aadhttpclient-enterpriseapi.md missing step

### ISSUE THREAD

**Issue by colinbarnard** [SharePoint/sp-dev-docs#4713]
#### Category
- [x] Question
- [x] Typo

#### Expected or Desired Behavior

Minor changes to documentation to mirror newest versions. On sp-dev-docs/docs/spfx/use-aadhttpclient-enterpriseapi.md

#### Observed Behavior

There is a new prompt when creating a web part

"Will the components in the solution require permissions to access web APIs that are unique and not shared with other components in the tenant?" y/N

The document doesn't specify which we should pick.

#### Steps to Reproduce

When running yo @microsoft/sharepoint in the terminal you will be asked that question.

**Comment by andrewconnell** [comment]
We'll get the doc updated, but in this scenario, it doesn't matter what you select. That is related to the isolated web parts capability.
