### ISSUE TITLE
SPFx webparts are failing to load just for Targeted Release Users alone. Does anyone have this weird issue?

### ISSUE THREAD

**Issue by suryakancherla** [SharePoint/sp-dev-docs#4714]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details.

TECHNICAL DETAILS ERROR:

Cannot read property 'ProfileService' of undefined CALL STACK: TypeError: Cannot read property 'ProfileService' of undefined at t. (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:110507) at o (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109779) at Object.next (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109114) at https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109023 at new Promise () at Y (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:108800) at t._getUserProfile (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:110401) at t. (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:112403) at o (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109779) at Object.next (https://.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109114)

**Comment by suryakancherla** [comment]
Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details. 

TECHNICAL DETAILS ERROR: 

Cannot read property 'ProfileService' of undefined  CALL STACK: TypeError: Cannot read property 'ProfileService' of undefined     at t.<anonymous> (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:110507)     at o (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109779)     at Object.next (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109114)     at https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109023     at new Promise (<anonymous>)     at Y (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:108800)     at t._getUserProfile (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:110401)     at t.<anonymous> (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:112403)     at o (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109779)     at Object.next (https://<Tenant name>.sharepoint.com/sites/apps/ClientSideAssets/a0a33fb7-226c-466e-a175-246b07fdc13e/popular-tools-web-part_d4417cb68bc2626fc785077b0c0f2ccc.js:15:109114)

**Comment by andrewconnell** [comment]
Can't repro this in my tenants (includes both standard & targetted release)... 

In those URLs you can see the tenantID is missing... verify across other tenants?

**Comment by suryakancherla** [comment]
@andrewconnell, Thanks for taking a look into the issue.

Do you want me to reach out to Microsoft support to know whether other Tenants got affected with this issue.

**Comment by andrewconnell** [comment]
If you are only seeing this in your tenant & you've confirmed the same solution works in other tenants, then I'd submit a ticket using your SPO admin center as it sounds localized to your tenant.

**Comment by suryakancherla** [comment]
I had already submitted a ticket as the webparts are failing to load all of a sudden. This is possible because of O365 updates pushed to our tenant.

**Comment by andrewconnell** [comment]
OK... I'm going to close this issue as there's not much we can do from here if it's a tenant-specific issue localized to your tenant. Feel free to open a new issue if you have more information.

**Comment by shweta19051** [comment]
The same issue is occurring for me as well. The web parts which were working fine a few days ago for all the users suddenly stopped working for the targeted release ones. Is there any update pushed from Microsoft's side?

**Comment by suryakancherla** [comment]
Hi Shweta, 

Are you referring to any JS files as reusable code from ClientSideAssets library in the Config.json file ?

**Comment by shweta19051** [comment]
No, just referring to a common module and linking the same though "npm link <modulename>"
