### ISSUE TITLE
Web part does not show up in tenant

### ISSUE THREAD

**Issue by vaderj** [SharePoint/sp-dev-docs#4720]
I am out of ideas.

I was working on a webpart, deploying to a site collection level app catalog in the root site collection of my tenant, and I tried to deploy it my dev site collection under /sites/dev, but despite deploying the solution with no errors, I could not get the web part to show up in either a classic or modern site.

So I have now tried multiple times of starting with a completely bare project from 
"npm install yo gulp"
"yo @microsoft/sharepoint"      with all defaults, followed by 
"npm install"                  and then
"gulp clean ; gulp bundle --ship ; gulp package-solution --ship",
copy the resultant .sppkg file from /sharepoint/solution/ to the app catalog and deploy, but now even the most basic HelloWorld web part will not show up as an option on either classic or modern pages.

The web part shows up in the local workbench as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Did you also install the app in a site collection after deploying it in the app catalog? All deploying in an app catalog does is simply make it available for install. You must then install it in the site collection where you want to use it.

**Comment by vaderj** [comment]
Oh well thats embarrassing! 
That worked, thanks!
