### ISSUE TITLE
Sugested way of calling REST API returns 400

### ISSUE THREAD

**Issue by amykhailiuk** [SharePoint/sp-dev-docs#4722]
Request to resource in form of

https://contoso-my.sharepoint.com/_api/SP.RemoteWeb(@url)/web/GetFileByUrl(@url)?@url='https%3A%2F%2Fcontoso-my.sharepoint.com%2Fpersonal%2Fjohn_contoso_com%2F_layouts%2F15%2Fguestaccess.aspx%3Fshare%3DERGZUIZ8E0pAuC1oJtwz4dQB23IabPgbMtiVe0OLPtMybw'

returns

HTTP 400
A potentially dangerous Request.Path value was detected from the client (?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a09a95-2554-dfcd-8229-f06706d5402d
* Version Independent ID: 9f2919a2-e88a-4af9-e3df-1cd4b4502691
* Content: [Shorter share link format in OneDrive and SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/shorter-share-link-format#feedback)
* Content Source: [docs/spfx/shorter-share-link-format.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/shorter-share-link-format.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
If want to get a specific file with url in SharePoint Rest API,please use this endpoint:
https://tenant.sharepoint.com/sites/dev/_api/web/GetFileByUrl(@url)?@url=%27https://tenant.sharepoint.com/sites/dev/doc2/Banner.jpg%27

**Comment by amykhailiuk** [comment]
thanks, but I want to get the file by link URL, not file URL (the page is about links AFAIK)

**Comment by anomepani** [comment]
@amykhailiuk Just want to understand for which purpose you are using that remote web endpoints?

What is business requirements for get file by url?

**Comment by amykhailiuk** [comment]
em... user gives the sharing link and the app should open file with possibility to check-out, edit, and check-in back from the app (not using browser)

**Comment by amykhailiuk** [comment]
actually, I found the way to do this: it works well if I don't URL-encode the path
