### ISSUE TITLE
Access JS file in SPFx web part from secured Azure CDN

### ISSUE THREAD

**Issue by HanumantPatil** [SharePoint/sp-dev-docs#4725]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

#AzureCDN

Question: I have to access file from azure cdn in spfx app. Azure cdn is secured. While accessing js file we need add qury string. 
Is there any way to add the query string parameters. 

Example : https://azureurl/containername/filename.js?q1=1&q2=2&q3=3

Default path is https://azureurl/containername/filename.js

JS File Path generated using base azure cdn path in mentioned in spfx webpart write-manifests.json.

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/write-manifests.schema.json",
  "cdnBasePath": ""
}

In which file of SPfx web part project we need to change to add query string parameter while accessing JS file form Azure CDN.

Any help will be appreciated. 

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Not clear... what do you mean about a "secured Azure CDN"... the private Office 365 CDN?

**Comment by HanumantPatil** [comment]
No, it is Azure CDN only but while accessing file from Azure CDN we need to pass certain query string parameter as shown below 
 
https://azureurl/containername/filename.js?q1=1&q2=2&q3=3

so how to configure CDN Base path URL with Query string parameter

**Comment by OS-Lee** [comment]
The cdnBasePath used to specify the root path of your cdn, so it's not the case to add query string parameters.

If you view the package file, you could find it also.

![image](https://user-images.githubusercontent.com/40845109/66536487-b0a41d80-eb4f-11e9-921f-076c7ab55310.png)

And [you cannot deploy SPFx solutions using private CDN at least currently](https://github.com/SharePoint/sp-dev-docs/issues/3270)

**Comment by andrewconnell** [comment]
@HanumantPatil The CDN base path is used to retrieve the JS bundle & JSON manifest for your component stored in the Azure CDN. SPFx does this when loading the script. There is no capability to specify any query string parameters as SPFx's module loader is using that to load the files needed for the component when adding them to the page.
