### ISSUE TITLE
Can't connect to custom API

### ISSUE THREAD

**Issue by colinbarnard** [SharePoint/sp-dev-docs#4729]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Able to use aad credentials in my application

#### Observed Behavior
I am getting 

https://login.microsoftonline.com/<Tenant_GUID>/oauth2/authorize?client_id=<Client_GUID>&redirect_uri=https%3A%2F%2F<APP_ID>.azurewebsites.net%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=<NONCE_VALUE>&state=<STATE_VALUE>&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.3.0.0

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

If i watch it in the browser DevTools I get 

Options request that returns 200
Then a get that returns a 302
and another get that returns 302

#### Steps to Reproduce

I have an API that is secured using aad and accessible from the browser.

I followed https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md and got that working with a function.

Substituting my client and my url is causing grief.

**Comment by andrewconnell** [comment]
This isn't clear why you are requesting to the **/authorize** endpoint. If you followed the doc, you use the **AADHttpClient** to obtain the access token from SPO, not from the AAD authorize endpoint.

Need more context... sorry... unable to understand the question / scenario.

**Comment by colinbarnard** [comment]
I figured this one out. It's because I was using the AAD -> App Registrations -> App -> Application ID URI as the client factory resource endpoint.

When using the the function example the Application ID URI is the same as the function URL. On custom apps it is not.
