### ISSUE TITLE
Unable to host teams tab on SharePoint online modern Page

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-docs#4730]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea
- [] Example checked item (*delete this line*)

#### Expected or Desired Behavior

provided [Teams package](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-in-sharepoint?fbclid=IwAR1LxZ-cYmorpxp1-rnm-xKKhWN8F6PitHFcV85kyunVqPKh5inwyeg4geA#introduction) should be successfully deployed in the app catalog and the "Sync to teams" option should get enabled.

#### Observed Behavior

**Step 1:**
downloaded package from [here](https://github.com/MicrosoftDocs/msteams-docs/raw/master/msteams-platform/assets/downloads/TalentMgmt-Azure.zip)
**Step 2:**
after deployment in the app catalog, it doesn't prompt to deploy on all sites, as well as it says it's not a valid package. It doesn't enable "Sync to Teams" option as well as indicated in the following screen:

![image](https://user-images.githubusercontent.com/13658386/66387755-3dc96400-e9e2-11e9-99ae-27abde0025de.png)

How can I test this functionality? Can anyone please help?

Best Regards,

**Comment by andrewconnell** [comment]
Those are the correct steps... the **sync to teams** button is for deploying a web part as a custom team tab. Please see this page within the MSFT Teams docs for detailed steps: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-in-sharepoint

**Comment by dips23** [comment]
Thank you, Andrew, I agree I missed a few steps, however, when I upload the given package in teams, it throws following error in teams to me:

Error: An error occurred while parsing the manifest.json file; Property 'scopes' has not been defined and the schema does not allow additional properties. Path 'composeExtensions[0].scopes', line 102, position 15.

Not sure whether it's an issue with my teams or a package!
