### ISSUE TITLE
New SPFx Framework - Trace Tab

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#474]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
If i go to the Trace tab on a new modern page and export to Excel, the date/time field does not format in excel properly

#### Observed Behavior
The excel spreadsheet does not render the date properly.

#### Steps to Reproduce
Go to an Office Group, create a new modern page.  add a few webparts on the page and press ctrl F12.  Click on the Trace tab - export to CSV.  see the attached spreadsheet

[spfx_trace_logs.xlsx](https://github.com/SharePoint/sp-dev-docs/files/825372/spfx_trace_logs.xlsx)

**Comment by patmill** [comment]
@iclanton

**Comment by iclanton** [comment]
This will be fixed in the next drop and in prod sometime in the next week or two.

**Comment by amishra0909** [comment]
Verified the bug is fixed. Closing this issue.
