### ISSUE TITLE
External Users unable to render custom webparts

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#4743]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Webparts should render for external users with permissions, maybe is related within the WebPart Context.

#### Results 

**Error:**

SPLoaderError.loadComponentError]:
***Failed to load component "8c02ac1f-8292-4454-a417-73cee57d00f6" (SpRenderListWpWebPart). Original error: ***Failed to load path dependency "SpRenderListWpWebPartStrings" from component "8c02ac1f-8292-4454-a417-73cee57d00f6" (SpRenderListWpWebPart). Original error: Error loading https://component-id.invalid/8c02ac1f-8292-4454-a417-73cee57d00f6_0.0.1/SpRenderListWpWebPartStrings
	Unable to load script https://bridgecolab.sharepoint.com/sites/appcatalog/ClientSideAssets/290e491d-b436-4b75-9831-5d5315188755/spfx_webparts-sprenderlistwpwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js

***INNERERROR:
***Failed to load path dependency "SpRenderListWpWebPartStrings" from component "8c02ac1f-8292-4454-a417-73cee57d00f6" (SpRenderListWpWebPart). Original error: Error loading https://component-id.invalid/8c02ac1f-8292-4454-a417-73cee57d00f6_0.0.1/SpRenderListWpWebPartStrings
	Unable to load script https://bridgecolab.sharepoint.com/sites/appcatalog/ClientSideAssets/290e491d-b436-4b75-9831-5d5315188755/spfx_webparts-sprenderlistwpwebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-27.007/sp-pages-assembly_en-us_61b38e7460d331dc3c506e8793260f48.js:4:53495)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-27.007/sp-pages-assembly_en-us_61b38e7460d331dc3c506e8793260f48.js:20:48986)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-27.007/sp-pages-assembly_en-us_61b38e7460d331dc3c506e8793260f48.js:20:112759)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-27.007/sp-pages-assembly_en-us_61b38e7460d331dc3c506e8793260f48.js:20:108790)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-27.007/sp-pages-assembly_en-us_61b38e7460d331dc3c506e8793260f48.js:20:45200

#### Steps to Reproduce

Assign a external user as Owner of the Hub Site, Sites
Try render a custom react webpart

**Comment by Jerry0527** [comment]
Check the cdnBasePath in "config -> write-manifests.json file", it should be a library folder url which stores the JavaScript file generated by SPFX solution, check this Folder's permission, make sure External user have at least read permission to this folder.

**Comment by andrewconnell** [comment]
Where were these web parts deployed, site collection / tenant app catalog?
