### ISSUE TITLE
Misleading subsection title: Retrieve list data

### ISSUE THREAD

**Issue by Fnu-Avi** [SharePoint/sp-dev-docs#4745]
Link: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint#retrieve-list-data

I did as told in the above mentioned link for connection to sharepoint list. But, when I tried to fetch lists from my test sharepoint site; it also fetched document libraries, page libraries (it fetched everything which was there in site contents). 

So, now I'm confused on whether everything under site contents is considered as list or it's just bad title of the section of the page? 

Any help would be appreciated!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Yes, most things in Site Contents are either Lists or Libraries, so this is working as intended.

Using the _api/web/lists endpoint in REST will pull back all of those. If you wish, you could filter out libraries from your query. For more information on the SharePoint REST endpoints, follow this link.

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest

**Comment by Fnu-Avi** [comment]
Thanks @bcameron1231 . That was helpful.
