### ISSUE TITLE
outdated information

### ISSUE THREAD

**Issue by annigam01** [SharePoint/sp-dev-docs#4746]
This page In general needs updation. Specifically the SPFX store options now exists so can be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f553eaa8-5792-3bdf-d9a8-dcbfc92e53ab
* Version Independent ID: e16322c4-8793-4f20-bc6a-984b78c1b403
* Content: [SharePoint Framework (SPFx) enterprise guidance](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#feedback)
* Content Source: [docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/enterprise-guidance.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Microsoft has not published any plans around SPFx & a store at this time... not sure what you're referring to.
