### ISSUE TITLE
Webpart fails to mount when page is loaded with a zoom higher than 100%

### ISSUE THREAD

**Issue by niranjan747** [SharePoint/sp-dev-docs#4749]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The webpart to load properly when the browser zoom is set to any arbitrary %.

#### Observed Behavior

the webpart is not mounted when the the zoom level on the browser is higher than 100%.
Please refer image below.
![image](https://user-images.githubusercontent.com/28514708/66643402-40bf9100-ec3c-11e9-8b9b-bdc4539b943a.png)

the max-height is set to 0px for the container for the webpart which contains some spinner for loading mesages. The webpart will be mounted when i deselect the max-height property or if i set the zoom back to 100% or lower.

![image](https://user-images.githubusercontent.com/28514708/66644072-abbd9780-ec3d-11e9-9327-0c9736ec61b9.png)

the **Canvas-slideUpIn** class is added back when i deselect the max-height property or if i set the zoom back to 100% or lower.

#### Steps to Reproduce

keep the browser zoom to higher than 100%.

#### Submission Guidelines

I've made a copy of the homepage to get the homepage layout to avoid the header section which you normally get when you create site pages in communication sites. Not sure if this is whats causing the issue. The Webpart i'm tying to add has full-bleed set to true.

**Comment by andrewconnell** [comment]
Can you provide a repro such as uploading a sample project to a public GH repo & referencing it help reproduce the issue?
