### ISSUE TITLE
Filtering list items in Microsoft Graph/SP API v1.0 and 2.0 fails for custom Yes/No field

### ISSUE THREAD

**Issue by pettersh** [SharePoint/sp-dev-docs#4750]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have added a custom yes/no column to a document library and expect the available REST APIs to return items according to the odata filter, so I expect to get a list of documents where the column is set to Yes.

Microsoft Graph:

- GET https://graph.microsoft.com/v1.0/groups/{GROUP-ID}/sites/root/lists('Documents')/items?$filter=fields/yesNoColumnName eq true

SharePoint APIs:

- GET http://fake_url/_api/v2.0/sites/root/lists/Documents/items?$filter=fields%2fyesNoColumnName+eq+true
- GET http://fake_url/_api/web/lists/getbytitle('Documents')/items?$filter=yesNoColumnName+eq+true

#### Observed Behavior

The opposite behavior . I get items returned where yesNoColumnName is set to false, representing the documents with the column set to No.

#### Steps to Reproduce

Add

1. Add a custom site column of type Yes/No
2. Create a new site content type inheriting Document
3. Add the new site column to the site content type
4. Add the site content type to the document library
5. Add a document (A) to the library and set it to use the new content type and column to Yes
6. Add another document (B) to the library and set it to use the new content type and column to No
7. Query the documents in any of the three APIs listed above

Thanks for your contribution! Sharing is caring.

**Comment by pettersh** [comment]
After feedback on Twitter, I have learned that all of the three APIs respect the value 1 as true and 0 as false, so yesNoColumnName+eq+1 will yield the items with the column set to Yes in the UI and return the true in the result. I'm able to solve my tasks with this, but still think the APIs should support filtering on the same value as the APIs return in the result for the items. 

But feel free to close this issue if you disagree.

**Comment by andrewconnell** [comment]
Yes/no columns are boolean columns which only store 0/1 for the values. When working with the REST API, you're working with the data as it's stored, not how it's presented in the UI, so using 0/1 is the correct way to do this. You can always see what values are stored by using REST to query the data.
