### ISSUE TITLE
On react-script-editor, getting "Verification failed while extracting @microsoft/sp-polyfills@1.2.0" when running "npm install" 

### ISSUE THREAD

**Issue by ZeweiS** [SharePoint/sp-dev-docs#4753]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

When running "npm install" on react-script editor I am getting following error, already tried to very and clean the cache with no luck:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= integrity checksum failed when using sha1: wanted sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= but got sha512-SZARibyCQB+1j5b7g/6CrsUBA8pz9Yh1z+2RhXMlJcLyGkUmSriKgRmHnPjpjogQSGUAARTIFaYIMncfqL+8Pg== sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=. (1467748 bytes)

**Comment by Jerry0527** [comment]
If you want to install React-Script-Editor Web Part in your environment, please follow the steps below:
Step1:

Download the zip package from GitHub:

https://github.com/SharePoint/sp-dev-fx-webparts

Install Node.js

Run "npm install -g yo gulp" to install Yeoman and gulp

Run "npm install -g @microsoft/generator-sharepoint" to install Install Yeoman SharePoint generator

Detailed steps please refer the official document below:

Set up your SharePoint Framework development environment

Step2:

Unzip the package and in the Node.js command prompt, navigate to the React Script Web Part folder in Node Command, run "npm install", then run "gulp serve" for a local testing:

Step3:

Edit Write-manifests.json in the folder: “sp-dev-fx-webparts-master\samples\react-script-editor\config”

Edit this json file using a text editor,add your own site asserts folder path like this:

"cdnBasePath": "https://tenant.sharepoint.com/sites/dev/SiteAssets/SPFX"

This folder is used to store some Js, CSS file which Script Editor Web Part needs to use.(Make sure you have create the folder inside Site Asserts before input)

Step 4:

Run "gulp –-ship" in Node.js Command Prompt in Node Js Command Prompt.

Run "gulp package-solution –-ship" in Node.js Command Prompt in Node Js Command Prompt.

Step 5:

Copy contents of temp\deploy to the CDN folder created above:

![1374466](https://user-images.githubusercontent.com/28797671/66817607-91055e80-ef6e-11e9-925e-1838392e2be2.png)



Step 6:

Upload .sppkg file from sharepoint\solution to your tenant App Catalog

Step 7:

Back to a site and add this App from Site Contents:

![1374468](https://user-images.githubusercontent.com/28797671/66817684-b1cdb400-ef6e-11e9-89d0-c36303353739.png)


Create a new Modern Page and then try to add the Script Editor Web Part and then it will work.

**Comment by andrewconnell** [comment]
This issue should be posted to the repo for the component mentioned in the OP. The React Script Editor component is provided as a community sample and exists in the sames repo... please post the question there.

**Comment by ZeweiS** [comment]
> If you want to install React-Script-Editor Web Part in your environment, please follow the steps below:
> Step1:
> 
> Download the zip package from GitHub:
> 
> https://github.com/SharePoint/sp-dev-fx-webparts
> 
> Install Node.js
> 
> Run "npm install -g yo gulp" to install Yeoman and gulp
> 
> Run "npm install -g @microsoft/generator-sharepoint" to install Install Yeoman SharePoint generator
> 
> Detailed steps please refer the official document below:
> 
> Set up your SharePoint Framework development environment
> 
> Step2:
> 
> Unzip the package and in the Node.js command prompt, navigate to the React Script Web Part folder in Node Command, run "npm install", then run "gulp serve" for a local testing:
> 
> Step3:
> 
> Edit Write-manifests.json in the folder: “sp-dev-fx-webparts-master\samples\react-script-editor\config”
> 
> Edit this json file using a text editor,add your own site asserts folder path like this:
> 
> "cdnBasePath": "https://tenant.sharepoint.com/sites/dev/SiteAssets/SPFX"
> 
> This folder is used to store some Js, CSS file which Script Editor Web Part needs to use.(Make sure you have create the folder inside Site Asserts before input)
> 
> Step 4:
> 
> Run "gulp –-ship" in Node.js Command Prompt in Node Js Command Prompt.
> 
> Run "gulp package-solution –-ship" in Node.js Command Prompt in Node Js Command Prompt.
> 
> Step 5:
> 
> Copy contents of temp\deploy to the CDN folder created above:
> 
> ![1374466](https://user-images.githubusercontent.com/28797671/66817607-91055e80-ef6e-11e9-925e-1838392e2be2.png)
> 
> Step 6:
> 
> Upload .sppkg file from sharepoint\solution to your tenant App Catalog
> 
> Step 7:
> 
> Back to a site and add this App from Site Contents:
> 
> ![1374468](https://user-images.githubusercontent.com/28797671/66817684-b1cdb400-ef6e-11e9-89d0-c36303353739.png)
> 
> Create a new Modern Page and then try to add the Script Editor Web Part and then it will work.

Hi @Jerry0527 Thanks for the info but I am still getting the same error message running "npm install" command.

@andrewconnell Can you point me to the more appropriate place to post this issue? Seems I am not alone here.

**Comment by andrewconnell** [comment]
The repo where you got it: 
https://github.com/SharePoint/sp-dev-fx-webparts
