### ISSUE TITLE
Targets property

### ISSUE THREAD

**Issue by vaderj** [SharePoint/sp-dev-docs#4754]
Is there any explanation of the "Targets" requirements?

	"Targets": "&lt;acl&gt;&lt;ace identityName=\"c:0t.c|tenant|0d4b97fc-37fb-4db3-84f3-d34243a3afac\" displayName=\"0t.c|tenant|0d4b97fc-37fb-4db3-84f3-d34243a3afac\" sid=\"\" binaryIdType=\"1\" binaryId=\"YzowdC5jfHRlbmFudHwwZDRiOTdmYy0zN2ZiLTRkYjMtODRmMy1kMzQyNDNhM2FmYWM=\" allowRights=\"1\" denyRights=\"0\" /&gt;&lt;/acl&gt;",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b8beafb-a84e-534a-4553-ae25ca81c66c
* Version Independent ID: b246e96e-0188-49d5-19c8-9e488a7e71ff
* Content: [GetById REST method](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-getbyid-method)
* Content Source: [docs/features/hub-site/REST-getbyid-method.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/hub-site/REST-getbyid-method.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
The response type is specified as [SPHubSite](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-sphubsite-type) which explains Targets property.

![SPHubSite](https://user-images.githubusercontent.com/8310319/66744016-f71fb200-ee98-11e9-870f-a05f78821285.png)

**Comment by vaderj** [comment]
Well I see that the 'Targets' property is a member of the SPHubSite type, but I guess my question boils down to .... Can the 'Targets' property be set via REST? 

Copying the <ACL /> generated when I added and cleared a group via PowerShell, and then trying to set it via REST did not work and I can't find any real mention of that particular property anywhere

Thanks!

**Comment by andrewconnell** [comment]
ATM doesn't look at the REST API supports setting this property explicitly.
