### ISSUE TITLE
Could not add addNavLink type header through Site Design JSON

### ISSUE THREAD

**Issue by rpskumar** [SharePoint/sp-dev-docs#4755]
I am trying to add Header top link link communication site. I am able to choose Header type through UI. However i do not find JSON schema to add header style menu in top navigation.  addNavLink needs valid URL to configure. But i need some menu are just header. Any help is appreciated. 

Regards,
Senthil
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by rpskumar** [comment]
I figured out to create header style using JSON. Please include in article as reference to create header navigation.
{
			"verb": "addNavLink",
			"url": "http://linkless.header/",
			"displayName": "Your Header Name",
			"parentDisplayName": "Parent Menu Name",
			"isWebRelative": false
		},

**Comment by andrewconnell** [comment]
This seems like it's already covered in the doc... https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#add-a-navigation-link

**Comment by rpskumar** [comment]
@andrewconnell
There is no example to add Header style navigation. The document has JSON example to add navigation links only. My requirement is to add header type navigation in sub links.

**Comment by andrewconnell** [comment]
But my point is the code snippet you posted above matches pretty close the code snippets that I linked to... I don't see what the difference is...

**Comment by dneimke** [comment]
@andrewconnell This issue should be re-opened.  There is no documentation on how to create Header style navlinks
