### ISSUE TITLE
SP Online REST API - fails to update metadata, reports OK and new version is created

### ISSUE THREAD

**Issue by antonviktorov-emergn** [SharePoint/sp-dev-docs#4758]
We are updating managed metadata columns for document library with ~26k documents.

We update items via this url 
```
https://${TENANT}.sharepoint.com/sites/${SITE}/_api/Web/Lists(guid'${listGuid}/items(${id})
...
headers["X-HTTP-Method"] = "MERGE";
headers["IF-MATCH"] = "*";

```
After trying to update file attributes like this:
![image](https://user-images.githubusercontent.com/56350556/66760613-27704c00-eeab-11e9-818a-cbf0ecc84976.png)
we had Account/Region left unchanged, third column updated properly.
We can't change Account and Region columns anymore.

Please notice WssId is not -1 in those requests. We changed WssId to -1 in our requests and new files got properly updated. but not the old ones.
What we have now  - approximately 2k files got 'stuck', their Account/Region attributes can't be changed via REST API anymore. Even after changing attributes via UI.
Every time we call REST API to change Account/Region for those files - api call reports OK, data not changed, new version is created.

How can we update those files?

**Comment by OS-Lee** [comment]
Did test to update Managed Metadata fieldby Managed Metadata InternalName(the third field you shared), works fine.

Steps:
1. Find Managed Metadata field GUID
/_api/web/lists/getbytitle('Mydoc2')/fields
![image](https://user-images.githubusercontent.com/40845109/66797574-c6458880-ef3d-11e9-8653-0bd1a55d8627.png)
2. Find Managed Metadata field GUID 
/_api/web/lists/getbytitle('Mydoc2')/fields(guid'86043549-ea7d-40f3-b49a-a1f32400a942')
![image](https://user-images.githubusercontent.com/40845109/66797698-44099400-ef3e-11e9-9400-7c392cf052e3.png)
3. Update the item

_api/web/lists/getbytitle('Mydoc2')/items(id)

Request headers:
X-RequestDigest: digest value
If-Match: *
X-HTTP-Method: MERGE
Content-Type: application/json; odata=verbose
Request Body:
{
    "m45df7e9fd814aea84e793e00511c2a4": "101 SharePoint 11|eaceb040-526f-482d-9a11-0227ebb55347",
	"f7dddcdca3604eb0aced66834e0040a1":"B|86116c77-4761-41f6-9b51-08a49ab851d5",
    "__metadata": { "type": "SP.Data.MyDoc2Item" }
}

**Comment by antonviktorov-emergn** [comment]
Finally! 
I tried this way some time ago, but failed since was trying to put value in following format
`"WssId;#Label|guid"` and it wasn't working.
Format `"Label|guid"` worked well. 

Thank you for your help, @OS-Lee !

I still think there is a bug in API which shall be fixed.

**Comment by anomepani** [comment]
It's very tricky way to update managed metadata column,  which involves multiple depenent call for getting actual internalname. 
If this steps documented for managed metadata column it will be very helpful to developers.
