### ISSUE TITLE
How do i set classic page web part properties? (Appearance -> chrome type)

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#476]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
In classic pages, i want to be able to set the standard OOB properties like Chrome Type to None

#### Observed Behavior
I set my manifest.json to

```
  "preconfiguredEntries": [{
    "groupId": "04ce3993-c058-4836-980f-12054589e478",
    "group": { "default": "Core" },
    "title": { "default": "Explore Organizations" },
    "description": { "default": "Core Explore Organizations WebPart - to be used on Core web pages ONLY." },
    "officeFabricIconFontName": "Page",
    "properties": {
      "defaultWebpartTitle": "Explore Organizations",
      "ChromeType": "None"
    }
  }]
}
```

#### Steps to Reproduce
edit your manifest as above and chrome state is still set to default.  Can i get a list of applicable values we can use here?

**Comment by patmill** [comment]
So those properties don't really apply to the underlying SPFX webpart, rather the host container on a classic page.  That isn't settable on the preconfigured entries.

**Comment by suz7777** [comment]
that works
