### ISSUE TITLE
Baseline packages are not asked and by default installing on premise during webpart creation using yo

### ISSUE THREAD

**Issue by Hriday-Muppidi** [SharePoint/sp-dev-docs#4760]
Hello all, 
I've been tryin to create a webpart project using yo @microsoft/sharepoint and i've been facing problem with the workbench not being opened. I've researched and found that workbench is only opening through gulp serve and especially for sharepoint online webparts rather than onpremise. But by default yo @microsoft/sharepoint is creating an on premise webpart and not prompting me to choose the baseline packages for sharepoint online. 
![cmd for yo](https://user-images.githubusercontent.com/41550223/66804000-f2add480-ef3e-11e9-91ce-377981ef2228.PNG)
Can someone suggest me how to migrate to sharepoint online

**Comment by Dennis-LZ** [comment]
Check and try to re-set up your SharePoint Framework development environment follow the steps below.

1.Install [NodeJS LTS version 10](https://nodejs.org/en/)

2.Install Yeoman and gulp

`npm install -g yo gulp`

3.Install Yeoman SharePoint generator

`npm install -g @microsoft/generator-sharepoint`

And then run the Node.js command prompt, and using "**yo @microsoft/sharepoint**" to create SPFx web part.

![Capture](https://user-images.githubusercontent.com/55479607/66814279-eb032580-ef68-11e9-9a5e-b22388110ec4.PNG)

**Comment by andrewconnell** [comment]
If you aren't being prompted for the type of project (baseline packages), that sounds like you have an extra **.yo-rc** file in your folder hierarchy. Check the closed issues in this repo as there are plenty of people who've posted about this with the resolution: https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+.yo-rc+is%3Aclosed
