### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by Disc0veryX** [SharePoint/sp-dev-docs#4762]
You should mention that to pass this tutorial successfully we have to create a new "Fabrikam Hong Kong Store" on a *developer* site. Also we need to install SQL Express 2014 (or 2016) and specify right connectionSting in the web.config (MSSQLLocalDB, Projects12 or Projects13). Without these directions I had many troubles and errors, when I was trying to deploy "BeforeSharePointUI" solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14641c6-8ce6-8838-ab9a-8e6ea90aed50
* Version Independent ID: 9b7fcbf8-4fc6-ade9-62ef-a1d4345827f8
* Content: [Give your provider-hosted add-in the SharePoint look-and-feel](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel)
* Content Source: [docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The previous step in this tutorial refers to the developer site. As this one builds off the previous one, that's assumed you're still working in the same site.

**Comment by Disc0veryX** [comment]
Yes, it's true, however it would be wise to mention this in the article. Anyway, availability of SQL Express and explanation of connectionString in the web.config hasn't presented in both previous and current step in this tutorial. So it creates difficulties.

**Comment by andrewconnell** [comment]
The steps are numbered, the beginning of each says which step it is and implies what you did, and the end of the article pushes you to the next step.
