### ISSUE TITLE
tileProps can only be manually enabled per person

### ISSUE THREAD

**Issue by eschrader** [SharePoint/sp-dev-docs#4763]
Can you elaborate on the tileProps only being set per user? Its very misleading that I can set this as a default JSON view for everyone when tiles are controlled separate per user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by unowiz** [comment]
Can we have a clarity on this aspect please? I didn't find any way to set the View layout to Tiles to be able to use tileProps layout.

**Comment by shagra-ms** [comment]
@eschrader @unowiz Can you please share more information about the ask?

Do you want users to directly land on Tiles layout, when they navigate to your View with tileProps formatter?

**Comment by bu11frogg** [comment]
@shagra-ms I would like to see that, yes.  If a View has custom formatting and it includes tileProps, I think it would make sense to default to Tiles layout when using that View.  It's disappointing to spend a few hours customizing a view just to learn that NONE of your users are seeing it.

Additionally I would also like to see a way to link to a Tiles layout for any View in the URL, e.g. "?layout=tiles" or something along those lines.

Finally, in web parts for Lists and Document Libraries it would be great if the web part options included the ability to select Layout (List, Compact List or Tiles) so we can direct how these items are displayed in a particular page.

**Comment by shagra-ms** [comment]
@bu11frogg Thanks for sharing more details on the ask.

This is now tracked in our backlog.

**Comment by bu11frogg** [comment]
Thank you @shagra-ms.  The idea has been posted here:  https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/39618640-allow-list-library-layouts-compact-tile-to-be

**Comment by shagra-ms** [comment]
Thanks @bu11frogg for sharing this.

**Comment by shagra-ms** [comment]
I am excited to share an update here. 

User can now perform 'Save' when they are on _Tiles layout_. Subsequently all users will land directly on the _Tiles layout_. This applies to List web part as well.

The feature is being actively rolled out, and shall be available in your tenant soon 😊

@bu11frogg @unowiz @eschrader @thechriskent.

**Comment by bu11frogg** [comment]
@shagra-ms  Awesome news, thank you for the update and all your hard work on this!  Can't wait to see it in action!

**Comment by shagra-ms** [comment]
The fix is not rolled out to everyone. Thanks!
