### ISSUE TITLE
The claimed functionality was not implemented

### ISSUE THREAD

**Issue by Disc0veryX** [SharePoint/sp-dev-docs#4765]
The article states that "when a user highlights an employee in the list and selects the button... the Added to Corporate DB field for the employee switches from **No** to **Yes**". But this functionality hasn't realized throughout the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42afced-99c6-19a0-0eb3-5b8dd8a41997
* Version Independent ID: c31e26fb-1751-fb5a-6de0-830eb19fe322
* Content: [Include a custom button in the provider-hosted add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in)
* Content Source: [docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That's exactly what the section [Add the custom button](/sharepoint/dev/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in) shows you how to do in this article. The referenced solution also contains the code that does this.
