### ISSUE TITLE
Should First release for everyone  ON at production for deployment of SPFx Apps?

### ISSUE THREAD

**Issue by vbartari** [SharePoint/sp-dev-docs#477]
#### Category
- [x] Question

#### Expected or Desired Behavior
When you deployed App in app catalog ,the should deployed .

#### Observed Behavior
**App** is not deployed at app catalog. getting **Deployed** column value as **NO**

#### Steps to Reproduce
Create a SPFx webpart. change the CDNPath as your Production package location.
 gulp bundle --ship
after **gulp package-solution –ship**- it will create package ,deploy this package in to the your appcatalog.
Error: App has not deployed and getting deployed column value as **NO**. it should be yes.
and app is not available for add in to the site

Can anyone let me know what i have to do. is it require **First release for everyone**  ON  at production level.

as this issue i have faced at my dev tenant/test site and the solution was **ON** the first release for everyone.
Can anyone please confirm do i need to do it for production as well?

**Comment by zplume** [comment]
Same issue here, SPFx web part works in first release DEV/TEST tenants, but not in UAT (not first-release) tenant.
When the SPFx package is added to the app catalog in the non-first release tenant, the "Valid App Package" column value is "No".
Is the tenant roll-out still in progress?

Thanks

**Comment by patmill** [comment]
Yes - rollout is in progress.  50% of tenants should now have it, with 100% by next week.

**Comment by patmill** [comment]
Sorry - forgot to come back to this post.  It should be at 100%.
