### ISSUE TITLE
"There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsDomainIsolated' attribute is not declared.' on line '1', position '309'."

### ISSUE THREAD

**Issue by SPSTEPBYSTEP** [SharePoint/sp-dev-docs#4770]
Try to deploy in SP2019 SPFx "react-calendar"web-part after create package and upload in catalog side got the error below.

 "T**here were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsDomainIsolated' attribute is not declared.' on line '1', position '309'**."  

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by SPSTEPBYSTEP** [comment]
appreciate your guidance.

**Comment by bcameron1231** [comment]
This is the project you are trying to install? https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-calendar 

This is built with SPFx 1.8.2, which is not supported for SharePoint 2019. SharePoint 2019 only supports up to SPFx 1.4.1
