### ISSUE TITLE
ListView CommandSet - onExecute parameters has wrong selectedRows (in a Doc Library)

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#4772]
Within onExecute, and you inspect event.selectedRows.getValueByName("ID"), the first time you execute the command for a selected item this is correct, but if you highlight another row, and execute the command, the value returned by the getValueByName doesn't update.

If you change the row selection using the checkbox on the left column this gets the correct value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api#feedback)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by zaiby** [comment]
I seem to be having the same issue for list extension, the first item is fine but for the next item it receives the same rowid as the first. As soon as I right click on an item it remembers the selected id, if I then click out of the list and right click on another item, same thing happens.

**Comment by jimmywim** [comment]
> I seem to be having the same issue for list extension, the first item is fine but for the next item it receives the same rowid as the first. As soon as I right click on an item it remembers the selected id, if I then click out of the list and right click on another item, same thing happens. Been happening since yesterday.

Does the rowid  come through correctly if you use the checkbox/selector in the first column on the view?

**Comment by zaiby** [comment]
:O yes it does.

**Comment by jimmywim** [comment]
@zaiby That's the issue I'm seeing. The Row ID only updates correctly when selecting the row using the row selector. Do what any normal user does and just click somewhere else in the row to select it, and the rowid doesn't change.

**Comment by zaiby** [comment]
yes, same issue

**Comment by andrewconnell** [comment]
Thanks for submitting this, but as you said in the other issue submitted previously, this is identical to the #4769. As such, let's keep things consolidated...

**Comment by jimmywim** [comment]
@andrewconnell Up to you which ticket to nix, mine has the docs metadata :)

**Comment by andrewconnell** [comment]
All that's used for is to keep the issue tied to the page where the comment was left. It doesn't impact the issue. 

I know there is work being done on the list codebase around events... unclear exactly what's being done of if this is related so I have to research...
