### ISSUE TITLE
RenderListDataAsStream handles list view threshold differently from CamlQuery?

### ISSUE THREAD

**Issue by gabbsmo** [SharePoint/sp-dev-docs#4776]
I have a document library with 5020 items. I have created a view that will display a subset of its items. The view works fine when running in the modern experience. In the classic experience the view fails with the list view threshold error. I have also found that the view's xml does not work with List.GetListItems using CSOM but it does work with RenderListDataAsStream using REST.

Anything different about the list view threshold and RenderListDataAsStream and is that documented anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The `RenderListDataAsStream` is the recommended approach... the other option you mention is specific to classic mode. Only the modern experience is receiving attention from engineering.

**Comment by gabbsmo** [comment]
Is there any documentation for the list view threshold and how it applies to `RenderListDataAsStream`?

The [end user docs](https://support.office.com/en-us/article/manage-large-lists-and-libraries-in-sharepoint-b8588dae-9387-48c2-9248-c24122f07c59) recommends modern over classic but it is not clear how it is different in this regard or if the list view threshold is applicable at all.
