### ISSUE TITLE
Access denied. You do not have permission to perform this action or access this resource

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#4778]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
#### Expected or Desired Behavior
Using Azure Function to apply template works fine when triggered from Postman 
I expect it to work the same when trigger from Logic App
The authority is of the function (app ID and secret)

#### Observed Behavior
When attaching a debugger to the function running in the context of logic app, I get an exception 
`{"Access denied. You do not have permission to perform this action or access this resource."}
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(
Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)\r\n   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)\r\n   at ApplyTemplateToSite.ApplyTemplate.ApplyProvisioningTemplate(TraceWriter log, String ProjectNumber, String ClientId, String ClientSecret, String SPOManagedPath, String AppDirectory)"
`
#### Steps to Reproduce
Add an azure function step in the logic app and trigger it. 
Is there other thing to do make it work?

Later I found it actually applied the template but returned "InternalServerError" 
Any idea how to make it return OK?

**Comment by andrewconnell** [comment]
This appears related to the PNP Core project, correct? If so, please post your issue to that project's issue list in their repo. This repo is for SharePoint development topics.
