### ISSUE TITLE
ClientPeoplePicker is undefined - SPF'x

### ISSUE THREAD

**Issue by naveenprasaths** [SharePoint/sp-dev-docs#478]
Hi, I am new to SPF'x. I want to create a Client side peoplepicker control in SPF'x with React. I have installed the sharepoint package using "npm install @types/microsoft-ajax @types/sharepoint --save-dev" command. I tried the client side peoplepicker in Jquery and it works fine. But when i try it in SPF'x, it throws "SPClientPeoplePicker is undefined" error. 

What i have done is as follows:
`
<div id="peoplePickerDiv"></div>
            <input id='ipdiv' type='text'/>
            <div> User info:
              <p id="resolvedUsers"></p> 
               User keys:
              <p id="userKeys"></p> 
            </div>

private loadPeoplePicker(peoplePickerElementId:string):void
  {
   var schema: ISPClientPeoplePickerSchema = {
            PrincipalAccountType: 'User,DL,SecGroup,SPGroup',
            SearchPrincipalSource: 15,
            ResolvePrincipalSource: 15,
            AllowMultipleValues: true,
            MaximumEntitySuggestions :50,
            Width: 280,
            OnUserResolvedClientScript: this.onUserResolvedClientScript
        }
      SPClientPeoplePicker.SPClientPeoplePickerDict[peoplePickerElementId];
  }

  private onUserResolvedClientScript(el: string, users: ISPClientPeoplePickerEntity[]) {
 var keys = "";
        var userInfo = "";
        for (var i = 0; i < users.length; i++) {
            var user = users[i];
            keys += user.Key + ",";
            for (var userProperty in user) {
                userInfo += userProperty + ':  ' + user[userProperty] + '<br>';
            }
        }
        $('#resolvedUsers').html(userInfo);
        $('#userKeys').html(keys);
  }`

Shall i need to add another packages or JS references? If yes please guide me the steps.

Thanks in advance.

**Comment by MarianoPrz** [comment]
I have the same issue, i can't resolve it importing the references in the config files, use this method instead:

`public componentDidMount(): void {

    const siteColUrl = Utils.getSiteCollectionUrl();
    SPComponentLoader.loadScript('/_layouts/15/init.js', {
      globalExportsName: '$_global_init'
    })
      .then((): Promise<{}> => {
        return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
          globalExportsName: 'Sys'
        });
      })
      .then((): Promise<{}> => {
        return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
          globalExportsName: 'SP'
        });
      })
      .then((): Promise<{}> => {
        return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
          globalExportsName: 'SP'
        });
      })
      .then((): Promise<{}> => {
        return SPComponentLoader.loadScript('/_layouts/15/core.js', {
          globalExportsName: 'SP'
        });
      })
      .then((): Promise<{}> => {
        return SPComponentLoader.loadScript('/_layouts/15/1033/strings.js', {
          globalExportsName: 'Strings'
        });
      })
      .then((): void => {
       
        SP.SOD.registerSod('SPClientPeoplePicker', siteColUrl + '/_layouts/15/clientpeoplepicker.js');
        SP.SOD.registerSod('clienttemplates', siteColUrl + '/_layouts/15/clienttemplates.js');
        SP.SOD.registerSod('clientforms', siteColUrl + '/_layouts/15/clientforms.js');
        SP.SOD.registerSod('autofill', siteColUrl + '/_layouts/15/autofill.js');

        SP.SOD.loadMultiple(['SPClientPeoplePicker', 'clienttemplates', 'clientforms', 'autofill'], () => {

          this.loadPeoplePicker("divID");
       

        });

      });

  }`

is too important load the strings.js, otherwise clienttemplates.js will broke.

**Comment by luismanez** [comment]
Have you tried this sample?
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-peoplepicker

**Comment by MarianoPrz** [comment]
In that sample we cant filter persons from a determined group, isnt that powerful for the moment, maybe customizing the search query but i dont know

**Comment by giuleon** [comment]
If you want to grab also the AAD group you need to change the end point: /_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.ClientPeoplePickerSearchUser

**Comment by patmill** [comment]
So I don't think there is an issue per-se here, and more of a request on having a reusable people picker.  If that is the case, please open up a user voice request - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/
