### ISSUE TITLE
The name of the "Title" field hasn't changed

### ISSUE THREAD

**Issue by Disc0veryX** [SharePoint/sp-dev-docs#4780]
The public name of the "Title" field hasn't changed from "Title" to "Name" with the suggested code in this article.

    Field field = localEmployeesList.Fields.GetByInternalNameOrTitle("Title");
    field.Title = "Name";
    field.Update();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8525588d-0a98-eb25-1548-5f4e25893308
* Version Independent ID: fa69db6b-be35-5904-69a0-5b5099f98516
* Content: [Add first-run logic to the provider-hosted add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in)
* Content Source: [docs/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you provide any additional context, like the SharePoint environment? This is a very simple snippet that should work.

**Comment by Disc0veryX** [comment]
I work with (1) SharePoint Online (where modern experience switch on by default), (2) configured for standard release. As for the rest, nothing special. All other code snippets from the article works as expected.

**Comment by Jerry0527** [comment]
If you want to update a field Title with another one with CSOM, it's necessary to do ExecuteQuery in ClientContext, please refer the code snippet below:

`  using (ClientContext ctx = new ClientContext("https://tenant.sharepoint.com/sites/sitename/"))
            {
                string password = "***********";
                string account = "user@tenant.onmicrosoft.com";
                var secret = new SecureString();
                foreach (char c in password)
                {
                    secret.AppendChar(c);
                }
                ctx.Credentials = new SharePointOnlineCredentials(account, secret);
                ctx.Load(ctx.Web);
                ctx.ExecuteQuery();
                List list = ctx.Web.Lists.GetByTitle("myList9");
                Field field = list.Fields.GetByTitle("Title");
                field.Title = "Name";
                field.Update();
                ctx.ExecuteQuery();
		    }`

![QQ截图20191023162214](https://user-images.githubusercontent.com/28797671/67372961-57a5a200-f5b1-11e9-8707-852c8f9979fa.png)

**Comment by Disc0veryX** [comment]
Thank you, but it didn't help. I've had an issue with the following code block:
```csharp
using (var clientContext = sPContext.CreateUserClientContextForSPHost())
{
    var query = from list in clientContext.Web.Lists
                where list.Title == "Local Employees"
                select list;
    IEnumerable<List> matchingLists = clientContext.LoadQuery(query);
    clientContext.ExecuteQuery();

    if (matchingLists.Count() == 0)
    {
        ListCreationInformation listInfo = new ListCreationInformation();
        listInfo.Title = "Local Employees";
        listInfo.TemplateType = (int)ListTemplateType.GenericList;
        listInfo.Url = "Lists/Local Employees";
        List localEmployeesList = clientContext.Web.Lists.Add(listInfo);

        Field field = localEmployeesList.Fields.GetByInternalNameOrTitle("Title");
        field.Title = "Name";
        field.Update();

        localEmployeesList.Fields.AddFieldAsXml("<Field DisplayName='Added to Corporate DB'"
                                                    + " Type='Boolean'"
                                                    + " ShowInEditForm='FALSE' "
                                                    + " ShowInNewForm='FALSE'>"
                                                    + "<Default>FALSE</Default></Field>",
                                                    true,
                                                    AddFieldOptions.DefaultValue);

        clientContext.ExecuteQuery();
    }
}
```
After the code execution a list is created and a new field "Added to Corporate DB" is added, but the name of the field "Title" remains unchanged. Should we to do ExecuteQuery twice?

**Comment by Jerry0527** [comment]
Tested with SharePoint CSOM in a Console Application, creating a list with the code snippet you provided, it's still working in my side, only need one time ExecuteQuery:
![QQ截图20191023171449](https://user-images.githubusercontent.com/28797671/67377701-a7d43280-f5b8-11e9-848d-1b02cdf52506.png)

![QQ截图20191023171530](https://user-images.githubusercontent.com/28797671/67377743-b9b5d580-f5b8-11e9-9100-2b7cb36c6071.png)

**Comment by Disc0veryX** [comment]
Hmm... strange enough. Anyway, thank you. I passed the tutorial just for training, so it isn't so important for me right now.

**Comment by Jerry0527** [comment]
You can try to update the field title after the list created using the code in my first reply to see if it works. I think this should be available.

**Comment by andrewconnell** [comment]
I suspect something was wrong with your code... maybe something slightly different. If you can share, maybe someone can spot a difference, but like @Jerry0527, I can't repro this so closing...
