### ISSUE TITLE
Are paged records supported in Export API?

### ISSUE THREAD

**Issue by upadhyayadhaval** [SharePoint/sp-dev-docs#4781]
- [x] Question
In case where there are large number of list items at root level or any folder level, does API have limit after which it will provide some continuation token to get another chunk or it gives one large Manifest.xml file?
I tried with 1500 list items and it produced single Manifest around 3 MB in size since I included metadata and versions.
Thanks.

**Comment by andrewconnell** [comment]
Can you be more specific which API you're referring to and if you're having an issue?

**Comment by andrewconnell** [comment]
I'm not aware of a limit, nor do I see one listed in the docs. Are you running into one?

**Comment by upadhyayadhaval** [comment]
So example if there are 10,000 list items in list, will it return all 10,000 items in single manifest or does CreateSPAsyncReadJob API support to get few thousand at a time.

**Comment by andrewconnell** [comment]
@JeremyKelley ... can you answer this?

**Comment by JeremyKelley** [comment]
Cleaning up my backlog I found the internal work item associated with this, apologies for this being over a year old but hopefully a late answer is better than no answer:

There shouldn't be an item # limit, however, once the manifest file reaches a large enough size, around 24MB, a new manifest with an interger appended at the end will get generated., e.g. Manifest1.xml. So, for a big list, you will have manifest 1 to N. 

Hopefully that wasn't a blocking issue and you were able to get your scenario working!

**Comment by upadhyayadhaval** [comment]
Yes it was not blocking issue. Thank you for reply.
