### ISSUE TITLE
Search with complete matching on the managed property is not working as expected

### ISSUE THREAD

**Issue by freemstr** [SharePoint/sp-dev-docs#4786]
Could you please provide examples of special character handling
I have documents with the following string values in column "RN" mapped to managed property RN
1. ABC/123
2. ABC/123-B
3. 11/12/13
I am not able to produce a search result for 1 and 2 using query RN:"ABC/123" and RN:"ABC/123-B" respectively. but #3 is found with RN:"11/12/13"
And so far found no documentation for this scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d931357-f63f-1f3d-5e2f-90d32c5d3818
* Version Independent ID: f95bfa79-cd41-208d-9d2d-6d2724f605ae
* Content: [Keyword Query Language (KQL) syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference)
* Content Source: [docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/keyword-query-language-kql-syntax-reference.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@wobba do you have any suggestions / input here?

**Comment by wobba** [comment]
Take a look at https://docs.microsoft.com/en-us/sharepoint/manage-search-schema and read section about language neutral tokenization, finer tokenizarion and complete matching. Depending on your query patterns one of these should help your scenario.

**Comment by freemstr** [comment]
Thank you,
Issue is in the online version, thus the 1st link you referenced seems to be the one to refer to
The issue seems to be outside what is covered in the above  document though.

Per the doc, this describes my situation best:
> Users who search for a datasheet and expect to only get results that match the full product identifier, typically write queries like ProductID:"11.132-884-115#4" . Finer query tokenization doesn't make a difference for such queries.

The goal here is finding documents by their unique ProductID but only ones matching the ID exactly
in my case
 ProductID:"11.132-884-115#4" should not find
 ProductID:"11.132-884-115#4-2"

I also tried [per this article]( https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference) to use ProductID="11.132-884-115#4"
But that does not produce expected results either

**Comment by wobba** [comment]
@freemstr Complete matching on the managed property should solve what you are after.

**Comment by freemstr** [comment]
Thank you,
I have Complete Matching and Token Normalization turned on
However it seems to not matter for values with slashes
string values "AB/20190709", "AB/20190709-B" and "2019/07/09" are not found consistently and uniquely
My theory was that this is a syntactic issue on my end but I am unable to find a clear reason for why
RN:"AB/20190709" - too many results including "AB/20190709" AND "AB/20190709-B" and more (seems to still look inside the document)
RN:"AB/20190709-B" - expected result (1 document)
RN="AB/20190709-B" - NO Result
RN="AB/20190709" - expected result (1 document)
RN:"2019/07/09" - expected result (2 documents)
RN="2019/07/09" - NO Result

Could this be a result of "Include content from all crawled properties" combined with "Complete Matching"?

Another suspect is settings "Token Normalization" to false results in
"The settings could not be saved because of an internal error: Internal Server Error"
on /_layouts/15/searchadmin/ta_managedproperty.aspx

**Comment by wobba** [comment]
Question, you want both exact matching as well as matching on the start of a query? I thought you asked for exact only..(?)

Complete matching should be used with = and any start matching will not work. Exact or nothing. And you don't need any tokenization with complete matching - they sort of work opposite.

**Comment by freemstr** [comment]
Mikael, 
Sorry for the confusion
I am looking for exact matches only, so there are no asterisks in my queries
which is why RN:"AB/20190709" returning too many and RN="AB/20190709-B" not working is an issue, each of these strings matches 1 document exactly.

If using equals should work, which I agree, it should according to documentation, it does not seem to explain this situation also:
RN:"2019/07/09" - 2 documents (there are actually 2 with this exact string)
RN="2019/07/09" - NO Result

**Comment by wobba** [comment]
If you turn off tokenization and turn on complete matching, reindex the content, then ProductID="11.132-884-115#4-2" does not only yield results with that id?

**Comment by freemstr** [comment]
Mikael, 
what do you mean by 
> turn off tokenization
are you referring to "Finer Query Tokenization"?

RN:"2019/07/09" - 2 documents (there are actually 2 with this exact string)
RN="2019/07/09" - NO Results

I am not getting expected results with equals, which is why I resorted to GitHub

I already have  
Token Normalization > ON
Complete Matching > ON
Language Neutral Tokenization > OFF
Finer Query Tokenization > OFF
and
Include content from all crawled properties in the list (the list is of 5 fields)

**Comment by wobba** [comment]
Token normalization: Off
Complete matching: On
Language Neutral Tokenization: Off
Finer Query Tokenization: Off

I haven't tested complete matching if you map multiple cp's and have complete matching - so unsure if that works or not. If you check include first, then you should be ok. And then possibly map all 5 cp's to individual mp's. Are they all unique id's for the same item?

**Comment by freemstr** [comment]
They are uniqie doc id, on different content types
like Invoice ID or Case ID

**Comment by freemstr** [comment]
This combination 

> Token normalization: Off
Complete matching: On
Language Neutral Tokenization: Off
Finer Query Tokenization: Off
Include content from the first crawled property 

results in message 

> The settings could not be saved because of an internal error: Internal Server Error

I will open a separate ticket for the error message as there is nothing indicating what exactly is wrong here but I have to keep 
Token Normalization: ON or it would not save the settings

**Comment by wobba** [comment]
Have you tried the settings on a new managed property?

**Comment by freemstr** [comment]
I did, with the same result
this combination of settings seems to not work on my tenant
ON a new property, I have to uncheck searchable to be able to set Token normalization: Off and Include content from the first crawled property

so I added a new property "RNows" with recommended settings and searchable OFF and queryable ON
It finds 
I re-indexed the site about 10 hours ago, just ran search again:
RNows:"2019/07/09" - expected result (2 documents)
RNows="2019/07/09" - UPDATE: 2 results as expected

On the same site, same content type, different library (so I am assuming re-indexed with the site re-index)
RNows:"AB/20190709-B" - UPDATE: NO Results
RNows="AB/20190709-B" - UPDATE: NO Results
RNows="AB/20190709" - UPDATE: NO Results

Same content type, so maybe I should re-index again?
Another idea i had is using ows_q_TEXT instead of ows_q_ for "Include content from the first crawled property"
I will implement and reindex and report back

Thank you for following up on this

**Comment by wobba** [comment]
Hi,
I'll try to set up a test myself. Might be a few days though.

**Comment by freemstr** [comment]
In case this makes a difference for indexing issues:
Column and type are defined in a content type hub
(subsequently the type is used in the libraries)
which corresponds to creation of properties in search schema
Once the libraries are filled with scanned documents, the requirement is to find specific scanned document by the column value, since there are multiple libraries I believe search is the way we accomplish this.

**Comment by wobba** [comment]
I've done some tests myself, and cannot really make it work as expected :) I'll investigate more and check internally.

**Comment by wobba** [comment]
I managed to get complete matching to work with the following enabled: Searchable, Queryable, Retrievable, Token Normalization, Complete Matching

As a bonus, if you query by appending the wildcard * at the end, that also works.

Meaning ` RNows:"AB/20190709"` yields one, ` RNows:"AB"`  yields none, and ` RNows:"AB*"`  yields all starting with AB. As long as you don't have " or * as a special character this seems to solve the scenario.

**Comment by freemstr** [comment]
Thank you. 
I already have it set up this way
on _layouts/15/searchadmin/ta_managedproperty.aspx
I do have "Complete Matching:
By default, search returns partial matches between queries against this managed property and its content. Select Complete Matching for search to return exact matches instead"

However,
RNows:"AB/20190709" yields both RNows:"AB/20190709" and RNows:"AB/20190709-A" even without wildcard
So I cannot use it instead of equals

Is this not the document I should be using?https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

**Comment by wobba** [comment]
Having the three items `AB/20190709` `AB/20190709-B` `AB/20190709-BB` all those return on exact match, when I use `property="AB/20190709"`

If I use `:` instead, I can add wildcards to get more if I want. That said, using `=` works as expected for me.
