### ISSUE TITLE
Setting ListViewXml resets the view

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#4787]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We should be able to change the `ListViewXml` through the REST API. It did work before!

#### Observed Behavior

I've observed the same behavior using PnPJS and PnPPowershell.

When trying to change `ListViewXml` on a view, the view resets to default. Meaning in a document library you're left with `DocIcon`, `Name`, `Modified` and `Editor`. With a list only the `Title` column's left.

I'm seeing the on standaard and targeted release tenants.

#### Steps to Reproduce

It's easiest to reproduce using PnP Powershell like this:
```powershell
$theList = "SomeList"; # The list to test with
$theView = "SomeView"; # The view to test with

# Get a view
$view = Get-PnPView -List $theList |? {$_.Title -eq $theView};

# Set the view (without changing it)
Set-PnPView -List $theList -Identity $view.Title -Values @{ListViewXml=$view.ListViewXml};
```

**Comment by andrewconnell** [comment]
Can you please provide some context? SharePoint environment, classic / modern, etc...

**Comment by RoelVB** [comment]
It's Sharepoint Online (as mentioned targeted **and** standard release). I've only looked at modern lists/libraries.

**Comment by OS-Lee** [comment]
Use Fields to set the view instead of ListViewXml.

My test script:

```
Connect-PnPOnline -Url $siteURL -Credentials $PSCredentials

$theList = "TestList"; # The list to test with
$theView = "View2"; # The view to test with
#$targetView = "View1"; # The view to test with

# Get a view
$view = Get-PnPView -List $theList |? {$_.Title -eq $theView};

[xml]$Doc = New-Object System.Xml.XmlDocument
$Doc.LoadXml($view.ListViewXml);
$nodes = $Doc.SelectNodes("//View//ViewFields//FieldRef");
$Fields=New-Object System.Collections.Generic.List[System.String];
#[string[]]$Fields=@();
for($i=0;$i -lt $nodes.Count;$i++){
	$Field = $nodes[$i].attributes['Name'].value
	$Fields.Add($Field)		
}
$FieldsList=$Fields -as [string[]]
$FieldsList.GetType()
Write-Host $FieldsList
# Set the view (without changing it)
Set-PnPView -List $theList -Identity $theView -Fields $FieldsList
```

**Comment by RoelVB** [comment]
@OS-Lee Thank you for the effort. It's a nice workaround, but...

This would double the API requests, because creating the view and adding the fields become separate requests.
And I'm not actually using Powershell so this will require me to write/add an XML parser.

But I'm still going to look into a similar approach, because I expect it'll take some time before this bug is going to be squashed.

**Comment by jpalo** [comment]
I can reproduce this issue on SPO modern list.

Attempt to fetch&modify&update ListViewXml results in just default view, even if before this step I have successfully added fields to the view.

```
// set field widths
let lv: any = await list.defaultView.select('ListViewXml').get();
let lvXml: string = lv.ListViewXml.replace('30', '10'); // just some test where I replace the default RowLimit of 30
await list.defaultView.update({
    ListViewXml: lvXml
}); 
```

Results in HTTP POST to `https://xyz.sharepoint.com/sites/projectfolders_test/_api/web/lists/getByTitle('w18')/DefaultView` with payload:
```
{"__metadata":{"type":"SP.View"},"ListViewXml":"<View Name=\"{42EFDF84-26E2-459D-872A-C45BDA1470D2}\" DefaultView=\"TRUE\" MobileView=\"TRUE\" MobileDefaultView=\"TRUE\" Type=\"HTML\" DisplayName=\"All Documents\" Url=\"/sites/projectfolders_test/w18/Forms/AllItems.aspx\" Level=\"1\" BaseViewID=\"1\" ContentTypeID=\"0x\" ImageUrl=\"/_layouts/15/images/dlicon.png?rev=47\" >
<Query><OrderBy><FieldRef Name=\"FileLeafRef\"/></OrderBy></Query>
<ViewFields><FieldRef Name=\"DocIcon\"/><FieldRef Name=\"LinkFilename\"/><FieldRef Name=\"PF_FolderDescription\"/><FieldRef Name=\"FolderChildCount\"/><FieldRef Name=\"ItemChildCount\"/><FieldRef Name=\"Modified\"/><FieldRef Name=\"Editor\"/></ViewFields>
<RowLimit Paged=\"TRUE\">10</RowLimit>
<JSLink>clienttemplates.js</JSLink>
<XslLink Default=\"TRUE\">main.xsl</XslLink>
<Toolbar Type=\"Standard\"/></View>"}
```

However after the POST that succeeds with HTTP 204, looking at the list view xml via `https://xyz.sharepoint.com/sites/projectfolders_test/_api/web/lists/getByTitle('w18')/DefaultView` gives just default XML
```
<View Name="{42EFDF84-26E2-459D-872A-C45BDA1470D2}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="/sites/projectfolders_test/w18/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=47" >
<Query><OrderBy><FieldRef Name="FileLeafRef" /></OrderBy></Query>
<ViewFields><FieldRef Name="DocIcon" /><FieldRef Name="LinkFilename" /><FieldRef Name="Modified" /><FieldRef Name="Editor" /></ViewFields>
<RowLimit Paged="TRUE">30</RowLimit>
<JSLink>clienttemplates.js</JSLink>
<XslLink Default="TRUE">main.xsl</XslLink>
<Toolbar Type="Standard"/></View>
```

**Comment by NZainchkovskiy** [comment]
I know, it's a old issue, but maybe it'll help someone.

@RoelVB you need to set InnerXml of ListViewXml (without <View></View> tags).
Something like that:
```
[xml]$xmlDoc = New-Object System.Xml.XmlDocument
$xmlDoc.LoadXml($view.ListViewXml);
Set-PnPView -Web $web -List $listName -Identity $view.Title -Values @{ListViewXml = $xmlDoc.FirstChild.InnerXml };
```

If you don't want to add XML parser, you can just substract these tags from string.
