### ISSUE TITLE
How to make dependable sharepoint rest get call using $batch api

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4789]
I am finding a way to make dependable batch rest call if possible, as I need to make multiple sync sharepoint rest get call based on outcome of first rest call and subsequent call.
It's like cascade rest call. 
Is there any way or demo example which describes usage of this feature using sharepoint batch api it Will be very helpful.

Thanks in advance

#### Category
- [x] Question

**Comment by andrewconnell** [comment]
As I shared in another one of your issues, more details on the docs for batching here: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis

If your question is about taking the results from one request in a batch and using them in another, that currently isn't supported.

**Comment by anomepani** [comment]
@andrewconnell  Thanks for answering. Yes, My question is about taking the results from one request in a batch parse result and using them in another.
