### ISSUE TITLE
SASS file embed as external css file 

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#479]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

Hello, is it possible to embed the generated css file as external stylesheet with sourceMap enabled so I can see the sass code in my chrome browser devtool? 

Thanks

**Comment by jonathanhotono** [comment]
@manishgarg1 @iclanton 
Is there any progress on this particular issue?
It's getting increasingly difficult for me to locate the css rule on bigger project since all css is rendered within <style></style>
Understood it might be hard to do it for xxx.module.scss but I think for normal scss files without modules, we at least should be able to display it as sourcemap functionality already exists on sass-loader webpack (not sure whether spfx in the future will also upgrade the webpack version).

**Comment by nickpape-msft** [comment]
Looks like this issue has flown under the radar as it was assigned to Manish in our internal tracking tool, rather than the team responsible for build tooling. I've reassigned it, hopefully this will help get some traction.

**Comment by iclanton** [comment]
This should ship in the next drop. See [this PR](https://github.com/Microsoft/web-build-tools/pull/561).

**Comment by jonathanhotono** [comment]
Thanks guys! @iclanton when is the next drop due on?

**Comment by andrewconnell** [comment]
@VesaJuvonen seems like this can get merged as the referenced PR implemented this months ago.

**Comment by jonathanhotono** [comment]
@VesaJuvonen it seems that the sass is still not referencing to the correct sass file.
Is there any additional configuration that I missed to enable source mapping?
![image](https://user-images.githubusercontent.com/6864547/56777026-6aedd580-67f9-11e9-9395-3e9e98ca9761.png)
