### ISSUE TITLE
What is purpose of RequestDigest or Form Digest in SharePoint Online? 

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4790]
What is the purpose of RequestDigest or Form Digest in SharePoint Online?
What information does it contain?
Can we decode or view information stored in Request Digest?

#### Category
- [x] Question

**Comment by andrewconnell** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/working-with-requestdigest
