### ISSUE TITLE
Is it Possible to execute SharePoint $batch REST API using SharePoint App Only Token?

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#4791]
Is it Possible to execute SharePoint $batch REST API using SharePoint App Only Token from the console app?

Is there any demo Batch Wrapper available to make SharePoint $batch API call from console app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047ea71c-e866-b2dd-5530-8451de27ba4a
* Version Independent ID: 3b886e81-c3b7-d5c1-136f-4cb827b4952f
* Content: [Complete basic operations using SharePoint REST endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It all depends on what you're doing within the batch. The token is used by each request within the batch. 

More details on the docs for batching here: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis

**Comment by anomepani** [comment]
Hey @andrewconnell  Thanks for reply.
As per https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis, In Given sample I don't know what is purpose if "**Expect; 100-Continue**"

I have noticed this is not there if we make batch request from the browser.

```
POST https://fabrikam.sharepoint.com/_api/$batch HTTP/1.1
Authorization: Bearer <access token omitted>
Content-Type: multipart/mixed; boundary=batch_e3b6819b-13c3-43bb-85b2-24b14122fed1
Host: fabrikam.sharepoint.com
Content-Length: 527
Expect: 100-continue

--batch_e3b6819b-13c3-43bb-85b2-24b14122fed1
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://fabrikam.sharepoint.com/_api/Web/lists/getbytitle('Composed%20Looks')/items?$select=Title HTTP/1.1

--batch_e3b6819b-13c3-43bb-85b2-24b14122fed1
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://fabrikam.sharepoint.com/_api/Web/lists/getbytitle('User%20Information%20List')/items?$select=Title HTTP/1.1

--batch_e3b6819b-13c3-43bb-85b2-24b14122fed1--
```

**Comment by anomepani** [comment]
Is there any reason why $batch API does not work with Cross-Site or SubSite?
Assuming For SharePoint App Token it has Sites FullControl Permission and wants to get data from multiple sites using single **$batch** endpoint.

**Comment by andrewconnell** [comment]
I'm fairly certain that's not possible... batch can only target a specific site, not multiple sites

**Comment by anomepani** [comment]
Thanks @andrewconnell I am closing this issue. As I get information which I required.
