### ISSUE TITLE
CSS from React component (from SPfx library project) is not getting rendered in React App (created using create-react-app)

### ISSUE THREAD

**Issue by hasannaqvi83** [SharePoint/sp-dev-docs#4792]
#4122 ## Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I did a Test SPFx Library component with a test React component (using Yoman generator) which I referred from a React app built using (create-react-app) CLI.

#### Expected or Desired Behavior

React component from SPFx Library Component which has SCSS applied on it should be rendered in Non SPFX React App along with CSS applied on it.

#### Observed Behavior

Non SPFX React App renders the React component from SPFX Library successfully however it is unable to apply the desired CSS.
 
This is the generated CSS file "Hello.module.css" which seems to be generated by gulp pipeline

exports = module.exports = require("../../../../react-app/node_modules/css-loader/dist/runtime/api.js")(false);
// Module
exports.push([module.id, ".Hello_Hello_eb973632__1M-4D .Hello_heading_eb973632__bhUkm{font-size:18px;font-weight:700;color:#00f}", ""]);

// Exports
exports.locals = {
	"Hello_eb973632": "Hello_Hello_eb973632__1M-4D",
	"heading_eb973632": "Hello_heading_eb973632__bhUkm"
};
#### Steps to Reproduce

Check the project uploaded here:
https://github.com/hasannaqvi83/Spfx-Library-Test

1) Clone the repo
`git clone https://github.com/hasannaqvi83/Spfx-Library-Test
`
2) In order to create references between the projects, I used Lerna as explained in this article from @s-KaiNet  :
https://spblog.net/post/2019/06/24/using-lerna-to-manage-spfx-projects-with-library-components
so, as a first step to setup Lerna, install it globally:
`npm install lerna -g`

3) Remove "spfx-library": "0.0.1" from 'dependencies' section of react-app's and spfx-app's package.json files.

4) Remove package-lock.json files from all the projects.

5) Now to actually develop the symlinks and install the dependencies of all the projects using lerna, run : (if this doesn't install the dependencies then do npm install for each individual project)
`lerna bootstrap`

6) Now, add "spfx-library": "0.0.1" under the 'dependencies' section of react-app's and spfx-app's package.json files and re-run:
`lerna bootstrap` 

7) Finally, in order to run spfx and react applications, do:
`lerna run --parallel serve` OR '`runlerna.bat`' using the batch file which is there in the root folder.

![10-20-2019 6-56-21 PM](https://user-images.githubusercontent.com/30181379/67156640-01e0b800-f36d-11e9-83cb-eae68e99f9d4.png)
![10-20-2019 6-53-37 PM](https://user-images.githubusercontent.com/30181379/67156641-01e0b800-f36d-11e9-9e32-98d99580e8b9.png)

**Comment by andrewconnell** [comment]
You're going to need to provide a lot more context on the repo steps... cloned your repo, but this is 3 different projects: web part, spfx library & the react app. I don't see where any of them reference each other...

**Comment by hasannaqvi83** [comment]
Thanks @andrewconnell for your valueable feedback.
Sorry for not posting the detailed steps to reproduce in the first place however they have been updated now.
Thanks again.
Hoping to hear from the community soon.

**Comment by andrewconnell** [comment]
Sorry, but can't repro following your steps:

![image](https://user-images.githubusercontent.com/2068657/67210669-7c4e1e00-f3e7-11e9-9bf0-cc7c3f1bfd2e.png)

```
sp-fx-app: [09:41:17] Error - [tsc] src/webparts/spfxWebPart/components/SpfxWebPart.tsx(5,23): error TS2307: Cannot find module 'spfx-library'.
sp-fx-app: [09:41:17] Error - 'tsc' sub task errored after 3.53 s
sp-fx-app:  exited with code 2
```

But, using lerna isn't a common situation. It's not something we can support in this repo (MSFT can't support every situation that developers want to use). Suggest maybe posting a common/question to the blog post you reference.
