### ISSUE TITLE
Can not read or post data to the database

### ISSUE THREAD

**Issue by YanYi2017** [SharePoint/sp-dev-docs#4795]
I followed the tutorial but when I click the button to read data(eg. "Show Orders") or post data(eg. "Place Order" in order form) in the debugging session, an error happened:

Error Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. The specified LocalDB instance does not exist.)

Source File: E:\code\SharePoint_Provider-hosted_Add-ins_Tutorials-master\1_BeforeSharePointUI\ChainStoreWeb\Pages\OrderForm.aspx.cs    Line: 48

Source Error:
Line 48:                 conn.Open();

It's obviously that something went wrong with the database, but I'm a new back end developer and I don't know how to fix it. Can anyone help me? Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14641c6-8ce6-8838-ab9a-8e6ea90aed50
* Version Independent ID: 9b7fcbf8-4fc6-ade9-62ef-a1d4345827f8
* Content: [Give your provider-hosted add-in the SharePoint look-and-feel](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel#feedback)
* Content Source: [docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by YanYi2017** [comment]
Thanks for your comment. 
Is "connection string" the Site URL? I have replaced it as my sit URL and the connection is ok. And the code is cloned from the repository from GitHub. Except for the changes in the tutorial, I didn't change anything. Maybe not this problem.
I found there are no IIS Express and SQL Express in my computer. Does it matter?

**Comment by YanYi2017** [comment]
> The issue is likely with your connection string you're using., or the ability to connect to the database. Need to make sure the database is running & accessible and that you're using the correct connection string.

Thanks for your comment.
Is "connection string" the Site URL? I have replaced it as my sit URL and the connection is ok. And the code is cloned from the repository from GitHub. Except for the changes in the tutorial, I didn't change anything. Maybe not this problem.
I found there are no IIS Express and SQL Express in my computer. Does it matter?

**Comment by YanYi2017** [comment]
@andrewconnell Thanks for your comment.
Is "connection string" the Site URL? I have replaced it as my sit URL and the connection is ok. And the code is cloned from the repository from GitHub. Except for the changes in the tutorial, I didn't change anything. Maybe not this problem.
I found there are no IIS Express and SQL Express in my computer. Does it matter?

**Comment by andrewconnell** [comment]
Not familiar with the code in this sample, but the error you mention talks about a DATABASE, not a site URL. The [code appears to be throwing an error when you are opening a connection to the database](https://github.com/OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials/blob/master/1_BeforeSharePointUI/ChainStoreWeb/Pages/OrderForm.aspx.cs#L48). Thus, you're not looking for a site URL for the connection string, you're looking for a SQL DB CONNECTION STRING.

If you look at the [README in the project you cloned](https://github.com/OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials), it talks about some pre-req's... such as: 

> The samples assume that Visual Studio is using Version 12 (SQL 2014) of SQL Express. If you have SQL Server 2016 installed on your development computer, you need to make a change to the web.config file in the solution. Find the line that sets the SqlAzureConnectionString near the top of the file. Change the phrase "ProjectsV12" in the value to "ProjectsV13". You will need to do this for each of the solutions in the repo.

If you're using a SQL Azure DB, you need to ensure the firewall on the SQL Azure DB has an entry for your web app to connect to the DB.

**Comment by YanYi2017** [comment]
@andrewconnell Thanks, I'm using VS 2017 and forgot to install SSDT. After installing the SSDT and changing the connection string in the web.config to replace "ProjectsV12" with "ProjectsV13", it worked.
And I also found a same issue in this tutorial project and [more information about it](https://github.com/OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials/issues/7#issuecomment-411914405).
