### ISSUE TITLE
OSX sp-build-web module permissions issue

### ISSUE THREAD

**Issue by daviddnet** [SharePoint/sp-dev-docs#48]
I'm using OSX with "El Capitan" I have latest LTS version of Node JS 4.5.0 and NPM 2.15.9.

I did the setup for Yeoman, Gulp and Yeoman generator for SharePoint.

When I tried to generate HelloWorld Webpart example I got the following error (I even tried run gulp serve without success):

**btw, I did that with and without ROOT privileges** 
------------

node-sass@3.8.0 postinstall /Users/juan/Desktop/SharePoint/helloworld-webpart/node_modules/@microsoft/sp-build-web/node_modules/gulp-core-build-sass/node_modules/gulp-sass/node_modules/node-sass
 node scripts/build.js

"/Users/juan/Desktop/SharePoint/helloworld-webpart/node_modules/@microsoft/sp-build-web/node_modules/gulp-core-build-sass/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /Users/juan/.npm/object-assign/4.0.1
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/juan/.npm/object-assign/4.0.1'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/juan/.npm/object-assign/4.0.1']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/juan/.npm/object-assign/4.0.1',
npm ERR!   parent: 'gulp-core-build-typescript' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juan/Desktop/SharePoint/helloworld-webpart/npm-debug.log

      _=+#####!       
   ###########|       .-------------------------------------------.
   ###/    (##|(@)    |              Congratulations!             |
   ###  ######|   \   |  Solution helloworld-webpart is created.  |
   ###/   /###|   (@) |      Run gulp serve to play with it!      |
   #######  ##|   /   '-------------------------------------------'
   ###     /##|(@)    
   ###########|       
      **=+####!       

juans-MacBook-Pro:helloworld-webpart juan$ pwd
/Users/juan/Desktop/SharePoint/helloworld-webpart
juans-MacBook-Pro:helloworld-webpart juan$ pwd
/Users/juan/Desktop/SharePoint/helloworld-webpart
juans-MacBook-Pro:helloworld-webpart juan$ ls -l
total 2496
-rw-r--r--   1 juan  staff      613 Aug 21 12:31 README.md
drwxr-xr-x  10 juan  staff      340 Aug 21 12:31 config
-rw-r--r--   1 juan  staff      126 Aug 21 12:31 gulpfile.js
-rw-r--r--   1 juan  staff     4412 Aug 21 12:31 helloworld-webpart.njsproj
drwxr-xr-x   5 juan  staff      170 Aug 21 12:32 node_modules
-rw-r--r--   1 juan  staff  1250951 Aug 21 12:35 npm-debug.log
-rw-r--r--   1 juan  staff      545 Aug 21 12:31 package.json
drwxr-xr-x   4 juan  staff      136 Aug 21 12:31 src
-rw-r--r--   1 juan  staff      154 Aug 21 12:31 tsconfig.json
drwxr-xr-x  15 juan  staff      510 Aug 21 12:31 typings
juans-MacBook-Pro:helloworld-webpart juan$ gulp serve
module.js:327
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/juan/Desktop/SharePoint/helloworld-webpart/gulpfile.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
juans-MacBook-Pro:helloworld-webpart juan$

**Comment by daviddnet** [comment]
The Node Module sp-build-web was not created
<img width="822" alt="screen shot 2016-08-21 at 1 02 04 pm" src="https://cloud.githubusercontent.com/assets/2099181/17838956/8621cc1a-679f-11e6-9804-31df2f05d83f.png">

**Comment by StfBauer** [comment]
Have you also applied the fix for permission issues with NPM on Linux and OSX?
https://docs.npmjs.com/getting-started/fixing-npm-permissions

Seems like you are running into this problem.

**Comment by daviddnet** [comment]
The default directory was ok, but not /.npm/object-assign. I run the next command and did the trick:

sudo chown -R $(whoami) ~/.npm/object-assign/

Thanks
