### ISSUE TITLE
Compiled SCSS file (from SPFx library component) is not getting applied when the React component is hosted in a React Application (created using create-react-app CLI)

### ISSUE THREAD

**Issue by hasannaqvi83** [SharePoint/sp-dev-docs#4804]
## Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

The idea of this solution is to test React components exposed as a shared library and bootstrapped using SPFx library components because:

"We are a team of SPFx and React developers who are going to use these components in a Non-SharePoint React Application. Our existing suite of components which we developed using SPFx framework contains come of the components which are not purely accessing SharePoint resources except Graph API. So in order to bring these components outside of SharePoint world, we selected SPFX Library template (from yo man) to base our shared library on."

Before jumping on the actual implementation, I did three projects:
1) A Test SPFx Library with a test React component (using Yoman generator) 
2) A React app built using (create-react-app) CLI.
3) A SPFx App WebPart project (using Yoman generator) 

SPFX library is shared between React App and SPFX App.

#### Expected or Desired Behavior

React component from SPFx Library which has SCSS applied on it should be rendered in React App (Non SPFX) along with CSS applied on it.

#### Observed Behavior

React App (Non SPFX) renders the React component from SPFX Library successfully however it is unable to apply the desired CSS.
 
This is the generated CSS file "Hello.module.css" which seems to be generated by gulp pipeline

exports = module.exports = require("../../../../react-app/node_modules/css-loader/dist/runtime/api.js")(false);
// Module
exports.push([module.id, ".Hello_Hello_eb973632__1M-4D .Hello_heading_eb973632__bhUkm{font-size:18px;font-weight:700;color:#00f}", ""]);

// Exports
exports.locals = {
	"Hello_eb973632": "Hello_Hello_eb973632__1M-4D",
	"heading_eb973632": "Hello_heading_eb973632__bhUkm"
};

![image](https://user-images.githubusercontent.com/30181379/67281055-54130c00-f51a-11e9-96d0-56cf145d1a65.png)

![image](https://user-images.githubusercontent.com/30181379/67281536-588bf480-f51b-11e9-8da2-5319577dfd78.png)

![image](https://user-images.githubusercontent.com/30181379/67281661-aacd1580-f51b-11e9-9a6b-3ee1d07f3681.png)

#### Steps to Reproduce
Check the project uploaded here:
https://github.com/hasannaqvi83/Spfx-Library-Test

[NOTE: For someone who is more familiar with lerna, I had to log this as a new issue as the steps mentioned previously were based on "lerna" which is not supported by this repo](https://github.com/SharePoint/sp-dev-docs/issues/4792)

1) Clone the repo
`git clone https://github.com/hasannaqvi83/Spfx-Library-Test`

2) Remove "spfx-library": "0.0.1" from 'dependencies' section of react-app's and spfx-app's package.json files.

4) Remove package-lock.json files from all the projects (if there are any).

5) Install the dependencies :
`cd spfx-library`
`npm install`
`cd spfx-app`
`npm install`
`cd react-app`
`npm install`

5) Now to actually develop the symlinks:
`cd spfx-library`
`npm link`
`cd spfx-app`
`npm link spfx-library`
`cd react-app`
`npm link spfx-library`

6) Now, add back "spfx-library": "0.0.1" under the 'dependencies' section of react-app's and spfx-app's package.json files:

7) Now compile 'spfx-library' to generate the "lib" folder, otherwise react-app and spfx-app would not run.
`cd spfx-library`
`gulp build`

8) Finally, in order to run spfx and react applications, do:
`cd react-app`
`npm run serve`
`cd spfx-app`
`gulp serve`

See the output:
![10-20-2019 6-56-21 PM](https://user-images.githubusercontent.com/30181379/67156640-01e0b800-f36d-11e9-83cb-eae68e99f9d4.png)
![10-20-2019 6-53-37 PM](https://user-images.githubusercontent.com/30181379/67156641-01e0b800-f36d-11e9-9e32-98d99580e8b9.png)

I would really appreciate if I could get help on fixing the CSS issues when the react component from SPFx library component is hosted in a non-SPFx React App.

**Comment by andrewconnell** [comment]
@hasannaqvi83 said:
> So in order to bring these components outside of SharePoint world, we selected SPFX Library template (from yo man) to base our shared library on

I doubt this is going to work. The CSS loaded from SPFx components is updated at runtime when requested by the theme engine in SPO. SPFx library components are designed to work within SPO & by SPFx components.

If you're trying to use them "outside the SharePoint world", that's not going to work... that's not a targetted scenario for these components.
