### ISSUE TITLE
Improve the layout of doc pages, especially for printing

### ISSUE THREAD

**Issue by biste5** [SharePoint/sp-dev-docs#481]
#### Category
 [  ] Question
 [  ] Typo
 [  ] Bug
 **[ X ] Enhancement / Suggestion**
 [  ] Additional article idea

#### Expected or Desired Behavior
I want to print this gem [SharePoint Framework (SPFx) enterprise guidance](https://dev.office.com/sharepoint/docs/spfx/enterprise-guidance), so that I can stick it all around home and office to assimilate it properly. Also, I'm getting old, and I always used to prefer to read on paper rather than on screen.
I expect to be able to print an acceptable layout readable on A4 size paper

#### Observed Behavior
- Left navigation is included in print, taking quite much left part of page
- It isn't possible to collapse side navigation (it was/is possible with MSDN instead)
- Right side navigation gets printed at the bottom of content
- Content isn't fully readable as it goes over page's margins

#### Steps to Reproduce
- Hit https://dev.office.com/sharepoint/docs/spfx/enterprise-guidance
- Try printing it

![image](https://cloud.githubusercontent.com/assets/8156032/23856153/d2f805dc-07f8-11e7-87f4-eecb12488120.png)

**Comment by amishra0909** [comment]
Thanks @biste5 for the feedback on document layout. We are investigating the issue. Meanwhile you can have a **work around** by going to the GitHub link ([https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/spfx/enterprise-guidance.md)) and print the document from there.

**Comment by patmill** [comment]
Looks like the doc team has made improvements in this area.  When I took a look today, I didn't see your issue.
