### ISSUE TITLE
Create a modern site with SiteDesignId

### ISSUE THREAD

**Issue by laurens1984** [SharePoint/sp-dev-docs#4810]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

As described in the documentation [Create a modern site](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest#create-a-modern-site) we use 'Get-PnPSiteDesign' to get a site design ID and call the '/_api/SPSiteManager/create' with that SiteDesignId in the payload. I expect the site to be created and the site design started/applied on that site.

#### Observed Behavior

The site gets created, but no site design is applied or started for it.

#### Steps to Reproduce

I used PnP Powershell to create the request to the API for me. I used a build of their dev branch, that passes the supplied SiteDesignId on to the API call. Below the steps to reproduce:
Connect-PnPOnline -Url https://tenant.sharepoint.com -UseWebLogin

New-PnPSite -Type CommunicationSite -Title Test -Url https://tenant.sharepoint.com/sites/sitedesignreprotest1 -Lcid 1033 -SiteDesignId [guid of your site design] 

In Fiddler I can see the SiteDesignId in the JSON payload in the call to the '/_api/SPSiteManager/create' service.

**Comment by bcameron1231** [comment]
Thanks for the comment. I also agree this is an issue. 

Here is the documentation for _api/SPSitemanager/Create 
https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest

This page specifies the REST call by passing in SiteDesignId guid. However, I have inspected the Out-of-the-box call from SharePoint home, and it doesn't pass the SiteDesignId in the call, it is actually using WebTemplateExtensionId for my custom site designs.


**Docs show a request like this (which doesn't work)**
```
fetch("https://test.sharepoint.com/_api/SPSiteManager/create", {
    "credentials": "include",
    "headers": {
        "accept": "application/json;odata=verbose",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/json;odata=verbose",
        "x-requestdigest": "<RequestDigest>"
    },
    "body": "{  \"request\": {    \"Title\": \"Communication Site 1\",    \"Url\":\"https:\/\/test.sharepoint.com\/sites\/Testsite16\",    \"Lcid\": 1033,    \"Description\":\"Description\",    \"WebTemplate\":\"SITEPAGEPUBLISHING#0\",    \"SiteDesignId\":\"835df885-9964-4d88-ad6d-2e4be2aa802d\",    \"Owner\":\"beau@test.onmicrosoft.com\"  }}",
    "method": "POST",
    "mode": "cors"
});
```

**Inspect SharePoint home creation using Dev Tools shows this**
```
fetch("https://test.sharepoint.com/_api/SPSiteManager/create", {
    "credentials": "include",
    "headers": {
        "accept": "application/json;odata=verbose",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/json;odata=verbose",
        "x-requestdigest": "<RequestDigest>"
    },
    "body": "{  \"request\": {    \"Title\": \"Communication Site 1\",    \"Url\":\"https:\/\/test.sharepoint.com\/sites\/Testsite16\",    \"Lcid\": 1033,    \"Description\":\"Description\",    \"WebTemplate\":\"SITEPAGEPUBLISHING#0\",    \"WebTemplateExtensionId\":\"835df885-9964-4d88-ad6d-2e4be2aa802d\",    \"Owner\":\"beau@test.onmicrosoft.com\"  }}",
    "method": "POST",
    "mode": "cors"
});
```

**Open question to Microsoft**
Can we get some clarity on what this REST call is supposed to have as parameters? If the docs are wrong, we should update the docs to match and also create a new ticket in the PnP Repository to update accordingly.
