### ISSUE TITLE
Refresh?

### ISSUE THREAD

**Issue by panjkov** [SharePoint/sp-dev-docs#4814]
Should this page be refreshed? I recently went through this tutorial and noticed that Azure Function app has to be written completely differently, and the screenshots of Azure portal also don't match. I could submit a pull request to do that, just need someone to say "OK".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
OK :)

**Comment by panjkov** [comment]
Azure function function has different signature, even if the returned values are same. I will create a branch in my github and you can review it before merge.
Yes, please assign it to me.

**Comment by andrewconnell** [comment]
BTW, since you're reshooting the screenshots, can you avoid the full window screenshots and have them be more focused (ie: zoom) on what the actual point of the image is?
