### ISSUE TITLE
Using isolated web parts in this tutorial?

### ISSUE THREAD

**Issue by panjkov** [SharePoint/sp-dev-docs#4815]
Would it make sense to use isolated web parts in this tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
See my [last comment](https://github.com/SharePoint/sp-dev-docs/issues/4814#issuecomment-545607176)... IMHO, I'd just mention and point to the docs on them. The more singularly focused the doc is, the better. We don't want people to have the impression that you have to do isolated WP's when using the AAD client.

**Comment by panjkov** [comment]
OK, but the approach is a bit different - in my walkthrough I had to register the app web of the iframe as a CORS target in order that it works. Alternatively we could use * in CORS (but, security...).

Or I'm missing something?

**Comment by andrewconnell** [comment]
My point is more that if the article doesn't address isolated web parts today, let's not "rewrite it" to include them. The docs already address isolated web parts. if a brief callout about isolated web parts makes sense & requires a mention about CORS, that's fine, but I'd prefer if we didn't put across the impression. That you must do isolated web parts When working with the AADHttpClient.
