### ISSUE TITLE
"Cannot enumerate sites" on all tested tenants

### ISSUE THREAD

**Issue by fzbm** [SharePoint/sp-dev-docs#4816]
The request https://graph.microsoft.com/beta/sites?filter=siteCollection/root%20ne%20null&select=webUrl,siteCollection seems no longer to be working. On each tested tenant I get the error message "invalidRequest: Cannot enumerate sites". This request worked definitely before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9c6a3a-4dd5-6096-e838-4451fa72c7b8
* Version Independent ID: 283e3382-85f7-fee0-278b-73d6320bfa2f
* Content: [Discover a Multi-Geo tenant configuration](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery#using-the-microsoft-graph-api)
* Content Source: [docs/solution-guidance/multigeo-discovery.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/multigeo-discovery.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
APIs under the /beta version in Microsoft Graph are subject to change. Use of these APIs in production applications is not supported.

Please try to use the API below to check if it works.

`https://graph.microsoft.com/v1.0/sites?select=siteCollection,webUrl&filter=siteCollection/root%20ne%20null`

**Comment by fzbm** [comment]
At the moment both URLs (yours and the one in the documentation) seem to be working again, but I switched to CSOM to retrieve all available instances. I will close this issue.
