### ISSUE TITLE
Missing controls/buttons (Submit for approval, Review approvals) related to modern SharePoint page approvals in SharePoint 2019 (On-Premises)

### ISSUE THREAD

**Issue by devangbhavsar89** [SharePoint/sp-dev-docs#4818]
Recently, I've been playing around "Content Approval" functionality for modern Site Pages in SharePoint 2019 and I noticed that corresponding UI (buttons inside command bar wrapper container) needed to trigger relevant actions (namely "Submit for approval", "Review approvals", etc.) is missing!

On editing a modern site page with Content Approval enabled for the corresponding Site Pages library, we only see "Publish" button in the command bar wrapper container. Further, on publishing the page, end-users are not able to see the page. And if they directly try to open the page using its URL, they get "Access Denied" error on that page. This indicates that the page has indeed been created and published alright, however because it has not yet been approved, it is not available for end users.

**[P.S.]:** Apparently, the Content Approval functionality seems to be working in the back-end. However, at moment, there is no front-end available for it to trigger the submission for approval/review approvals from modern site pages.

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I create/edit any site page (with Content Approval enabled on the underlying Site Pages library), ideally I should be able to see "Submit for approval" button in the command bar wrapper container.

Here is a screenshot of expected UI as can be seen in **SharePoint Online** environment:

![image](https://user-images.githubusercontent.com/46373637/67464091-66409780-f64b-11e9-9ed7-21eb76991ea4.png)

#### Observed Behavior

However, what we actually see in **SharePoint 2019 On-Premises** environment is as follows:

![image](https://user-images.githubusercontent.com/46373637/67464240-aef85080-f64b-11e9-818f-e169822effa1.png)

So clearly, the action buttons for content approval (such as "Submit for approval", etc.) are missing in the command bar wrapper.

#### Steps to Reproduce

1.  Enable "Content Approval" by setting "Require content approval for submitted items?" to YES inside Versioning Settings of Site Pages library in any modern Communication site.
2. Create a new modern Site Page using OOTB UI from Site Pages library and start editing it.
3. Notice the buttons available in Edit mode inside command bar wrapper container. You will only see the conventional "Publish" button instead of "Submit for approval" button.

#### Additional Notes

- The SharePoint Cumulative Update which is installed in my dev environment, is from September 2019. So the environment is pretty much up-to-date with latest update available. 
- It's corresponding Configuration Database Version is: 16.0.10350.20000

**Comment by bcameron1231** [comment]
AFAIK, Modern Page Approvals are only available in SharePoint Online.  With that being said, I don't think this is a bug.

**Comment by devangbhavsar89** [comment]
Yup, right. However, it would be nice to know, if this is coming to onprem anytime soon. As I mentioned, at least the approval functionality in the back-end seems to be working normally.
