### ISSUE TITLE
Field customizer not rendering correclty in grouped views that are collapsed by default

### ISSUE THREAD

**Issue by florianwachter** [SharePoint/sp-dev-docs#4819]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The field customizer should also render in grouped views that are collapsed by default.

#### Observed Behavior
If I include columns in a view and I use a field customizer to change the rendering of the column, the column is empty if the view is a group view that is collapsed by default. The column renders correclty if I wait a few seconds before I expand a group. If I expand the group immediately after loading the view, the column is empty. This means if I expand the group before my custom app is fully loaded, the column stays empty.

#### Steps to Reproduce

Create a new field customizer using yo @microsoft/generator-sharepoint, select extension/field customizer

Change the onRenderCell in the field customizer to:

```
@override
  public onRenderCell(event: IFieldCustomizerCellEventParameters): void {
    // Use this method to perform your custom cell rendering.
    const text: string = "TEST";

    const helloWorld: React.ReactElement<{}> =
      React.createElement(HelloWorld, { text } as IHelloWorldProps);

    ReactDOM.render(helloWorld, event.domElement);
  }
```

The field always renders the same value 'TEST'.

Run gulp bundle and gulp package-solution, gulp serve --nobrowser, upload the package to the app catalog, deploy it and add the app to a SharePoint site.

Create a new custom list and add a few items.

Open the list settings, add a column form existing site columns and add the column that is specified in the element.xml file. By default the column name is 'SPFxPercentage'. Make sure you also add the column to the default view.

The column should show up correctly and you should see the value TEST for all items.
<img width="425" alt="2019-10-24_13-42-41" src="https://user-images.githubusercontent.com/5690610/67482547-30f47380-f664-11e9-8da7-8d9925ad4c03.png">

Now change the view and select the column 'Title' in the Group By section. Make sure the group is collapsed by default.

If you now load the view and you immediately expand a group, the field customizer doesn't render correctly, the column is empty. This is only the case if you immediately expand the view after loading the page. If you wait a second, everything is fine.  

<img width="673" alt="2019-10-24_13-45-13" src="https://user-images.githubusercontent.com/5690610/67482893-dd365a00-f664-11e9-985a-f135f8e7acd3.png">

**Comment by florianwachter** [comment]
@andrewconnell: Do you have an update on this. The issue still occurs.

Thanks, Florian

**Comment by andrewconnell** [comment]
Yeah, I can see the same thing... :(

**Comment by AJIXuMuK** [comment]
Sorry @florianwachter for the super long delay on this one.
The issue has been fixed.
Feel free to open a new issue if the problem is still there for you.
