### ISSUE TITLE
Local workbench loading but workbench online is not

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-docs#4820]
I am trying to extend the Documents web part (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-documents-detailslist)

(Any working alternatives welcome!)

In order for 'gulp serve' to run I have disabled https and created a dev script in the package.json
`
    "dev": "set NODE_NO_HTTP2=1&& gulp serve",`

However, as I am trying to load a document library I need to run the workbench on the tenant.
site.com/subsite/_layouts/15/workbench.aspx
Says that I am not running gulp serve, when localhost is working while running gulp serve

**Comment by bcameron1231** [comment]
I'm guessing it's because you are serving up only HTTP and the online workbench requires HTTPS. 

For SP2016, you shouldn't need to disable HTTPS. You should only have to set the node variable to use HTTP1 instead of HTTP2.
