### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yeiner899** [SharePoint/sp-dev-docs#4821]
Is there a limitation for GCC tenants? we are trying to make this work and we are receiving an error 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afac891-6cf5-1746-6392-8cb61a441770
* Version Independent ID: b5d1f95b-f40b-8d0c-7334-7608a3add9ff
* Content: [Using site designs and Microsoft Flow to track site creation requests](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial#feedback)
* Content Source: [docs/declarative-customization/site-design-trigger-flow-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-trigger-flow-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by yeiner899** [comment]
parameter URL has an invalid value

**Comment by andrewconnell** [comment]
@yeiner899 "an error" doesn't provide anywhere near enough detail to help...

**Comment by yeiner899** [comment]
Hello team

This is the error


[cid:image001.png@01D58B1A.AD41D140]
﻿ --
Yeiner Lopez
SUPPORT ENG
Power Platform
Office: +506 (4) 1161287
Mobile: 72244905
Yeiner.Lopez@microsoft.com<mailto:Yeiner.Lopez@microsoft.com>
10 AM - 7 PM MDT

If you have any feedback about my work, please let either me or my manager Doug Verona know at doverona@microsoft.com<mailto:doverona@microsoft.com>
[Microsoft]
﻿"The only difference between a good day and a bad day is your attitude"​



The content of this email including its attachments (the “Content”) is confidential and provided for information purposes only. It does not under any circumstance constitute a legally binding offer or acceptance of Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. This Content shall not be construed as (i) any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate and/or (ii) supplementing or amending the terms of any existing agreement with Microsoft Ireland Operations Limited or any other Microsoft Group affiliate. In any case, any commitment from Microsoft Ireland Operations Limited or any other Microsoft Group affiliate must be prior stated in an agreement drafted by Microsoft and signed by the duly authorized representatives of the Microsoft affiliate concerned and your company. Furthermore you are reminded that the Content is solely based on the information provided to us at the time of this email and that it will be subject to possible change.

**Comment by andrewconnell** [comment]
Closing due to lack of useful response...
