### ISSUE TITLE
How do I modify or load JSON in SharePoint online site

### ISSUE THREAD

**Issue by TimShegrud** [SharePoint/sp-dev-docs#4823]
I have found many web articles saying how to create or edit a JSON to format SharePoint Sites.  

This is all well and good but I don't know how to apply these changes.  Is there an existing JSON I need to update?  Do I create my own then run some sort of command in PowerShell connected to the SharePoint Online site???  What would that command be?

BTW.  My goal is to force my SharePoint Online Modern Team Site to use my web part to occupy the full width of the page rather than to leave that ugly white space to the right.  Additionally to lessen the need to scroll to see the entire width of that web part.

My apologies if this is the wrong forum for this kind of question.

Thank you,

Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d43002-eb85-711b-a441-6fc772614e6b
* Version Independent ID: 6ef38943-3cb1-ff5f-0fbb-1498b63f6cc9
* Content: [SharePoint site theming - REST API](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
There is no supported way to remove the white space on the right of your Modern Team sites, or modify the display of the modern Web Parts.

If you'd like to use up a bit more space of the screen, you could opt for Communication Sites instead of Team Sites. 

However,  what you are trying to achieve is not available.

**Comment by TimShegrud** [comment]
Hi Beau,

Thank you for the quick response.

I understand that it is not a ‘current’ feature of SharePoint Online but I am wondering if there is any kind of a fix for this in the future.  It seems to be a pretty popular request and has been for a while.

Mostly this submission was to see if we could get some action going on this feature request.

Thanks for you time,

Tim Shegrud

**Comment by bcameron1231** [comment]
If you would like to get some enhancements, the best place for this would be the UserVoice.

There are already a lot of suggestions you can vote for.
https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/32879746-much-too-much-white-space
https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/32858962-too-much-white-space
https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/33118819-too-much-white-space
