### ISSUE TITLE
Choice with space not shown

### ISSUE THREAD

**Issue by duncanspeidel** [SharePoint/sp-dev-docs#4827]
I am working &lt;choices&gt; that takes the following structure:
    &lt;CHOICES&gt;
      &lt;CHOICE&gt;New&lt;/CHOICE&gt;
      &lt;CHOICE&gt;Ready for staffing&lt;/CHOICE&gt;
      &lt;CHOICE&gt;Draft&lt;/CHOICE&gt;
      &lt;CHOICE&gt;Approved &lt;/CHOICE&gt;
      &lt;CHOICE&gt;Rejected&lt;/CHOICE&gt;
      &lt;CHOICE&gt;Completed&lt;/CHOICE&gt;
    &lt;/CHOICES&gt;

When I debug my app, the choice with space (&lt;CHOICE&gt;Ready for staffing&lt;/CHOICE&gt;) is not shown.  I have tried double and single quotes with the same result.  Running Visual Studio 2019, against latest version of SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83792d77-9975-fcaf-1869-4e21b47f7d83
* Version Independent ID: 7977c542-e1ea-9064-e046-1a64ba65aaa3
* Content: [CHOICE element (List)](https://docs.microsoft.com/en-us/sharepoint/dev/schema/choice-element-list#feedback)
* Content Source: [docs/schema/choice-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/choice-element-list.md)
* Product: **office-online-server**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
If you want to create choice field in custom list in SharePoint add-in, the field Schema like below.

```
<Field Name="ChoiceField" ID="{cf2d0af1-2f4d-4284-b630-813159ed08ef}" DisplayName="ChoiceField" Type="Choice">
      <CHOICES>
          <CHOICE>New</CHOICE>
          <CHOICE>Ready for staffing</CHOICE>
          <CHOICE>Draft</CHOICE>
          <CHOICE>Approved </CHOICE>
          <CHOICE>Rejected</CHOICE>
          <CHOICE>Completed</CHOICE>
      </CHOICES>
</Field>
```
![Untitled](https://user-images.githubusercontent.com/55479607/67734907-5b1bac00-fa3d-11e9-90b2-c176a55f1a16.png)

You can create a new choice field and add choices with space in the UI to check if it works.
