### ISSUE TITLE
Field Customizer not rendering when local serving

### ISSUE THREAD

**Issue by CPritch** [SharePoint/sp-dev-docs#4829]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When serving locally, to initialize and render the field customizer for the name specified in the serve config. 

#### Observed Behavior

`OnInit` and `OnRender` are never called when locally serving a customizer. I have only tested this for a document library in general release.

#### Steps to Reproduce

Environment: General Release - SPO
SPFx Version: 1.9.1

1. Generate a fresh Field Customizer
2. Run `gulp serve`
4. Assure the View has a field with both/either a matching:
  - Internal Name
  - Title
5. The field customizer is never initialized or rendered, regardless of Internal Name or Title.

#4535 
This was a previous issue I was involved in where Title was being used instead of internal name. This does not seem to work at all anymore for me.

**Comment by CPritch** [comment]
I can confirm that the issue doesn't appear to exist in a first-release tenant.

**Comment by AJIXuMuK** [comment]
Sorry @CPritch for the super long delay on the response.
The issue has been fixed a while ago.
Feel free to open a new issue if the problem still exists on your environment.
