### ISSUE TITLE
How to decrypt the .xml files stored in the block blob container

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-dev-docs#4830]
I wanted to follow up on #4699 with the ask for an example on how to properly decrypt the xml files stored created by the `ctx.Site.CreateSPAsyncReadJob()` method.

@Dennis-LZ could you provide an example for properly decrypting the xml files?

At the moment I either end up with some bytes at the beginning of the xml file or without the first 16 characters:

1. Trying to get the IV based on the first 16 Bytes of the xml without moving the position within the stream 
```
M��k�H�)�w����="1.0" encoding="utf-8"?>
<SPObjects xmlns="urn:deployment-manifest-schema">
```

2. Trying to obtain the IV based on the first 16 Bytes of the xml with moving the position within the stream
```
="1.0" encoding="utf-8"?>
<SPObjects xmlns="urn:deployment-manifest-schema">
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1654a603-da1f-b11b-fd2f-9aa20e9fac02
* Version Independent ID: e8453081-caea-ee38-137d-3cfe2c145f45
* Content: [Sharepoint Migration Export (Asynchronous Metadata Read) API](https://docs.microsoft.com/en-us/sharepoint/dev/apis/export-amr-api)
* Content Source: [docs/apis/export-amr-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/export-amr-api.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by andikrueger** [comment]
@JoanneHendrickson Any chance to get an example for this issue?

**Comment by andikrueger** [comment]
Any chance to get an update on this issue?

**Comment by tsegato** [comment]
The files are not encryped as article states. Try following:
   CloudStorageAccount account = CloudStorageAccount.Parse(_storageConnectionStrong);
            CloudBlobClient blobClient = account.CreateCloudBlobClient();

            CloudBlobContainer container = blobClient.GetContainerReference("migration-read-container");

            CloudBlobDirectory folder = container.GetDirectoryReference("4a17d596-2172-46eb-a22d-56f09dc70592");
            CloudBlockBlob blob = folder.GetBlockBlobReference("Manifest.xml");

            string templateHtml;         
            using (var memoryStream = new MemoryStream())
            {
                blob.DownloadToStream(memoryStream);
                templateHtml = Encoding.UTF8.GetString(memoryStream.ToArray());
            }
