### ISSUE TITLE
Question: How to update list item's multichoice field?

### ISSUE THREAD

**Issue by Karthickraju2690** [SharePoint/sp-dev-docs#4831]
I can create list item through REST API by using documentation. But, when I try to create list item with Multichoice field, 

        {'__metadata': {'type': 'SP.Data.MyListItem'}, 'Title': 'Test Task',
                           'CategoryDescription': 'This is a test Task',                               
                           'Multichoicefield':{
                               '__metadata' : {'type' : 'Collection(Edm.String)' },
                               'results': ['value1', 'value2']
                               }
                           }

On running with above payload, receiving _An open collection property 'Multichoicefield' was found. In OData, open collection properties are not supported.", "400 Client Error: Bad Request for url:_

Can you provide example of how to create?

**Comment by Jerry0527** [comment]
If your list name is "MyList", the type should be   type: "SP.Data.MyListListItem" 

Here is a demo to create item with multiple choicefield with Rest API for your reference:

<script type="text/javascript">
    $.ajax  
        ({  
        url: _spPageContextInfo.webAbsoluteUrl + "/_api/web/lists/GetByTitle('MyList')/items",  
        type: "POST",  
        data: JSON.stringify  
        ({  
            __metadata:  
            {  
                type: "SP.Data.MyListListItem"  
            },  
            'Title':  "Test Task",
            'CategoryDescription': "This is a test Task",
            'Multichoicefield': {'results': ['Enter Choice #1', 'Enter Choice #2', 'Enter Choice #3']} 
        }),  
        headers:  
        {  
            "Accept": "application/json;odata=verbose",  
            "Content-Type": "application/json;odata=verbose",  
            "X-RequestDigest": $("#__REQUESTDIGEST").val(),  
            "X-HTTP-Method": "POST"  
        },  
        success: function(data, status, xhr)  
        {  
            console.log(data);
        },  
        error: function(xhr, status, error)  
        {  
            console.log(data.responseJSON.error);  
        }  
    });
    
   </script>
![QQ截图20191029174851](https://user-images.githubusercontent.com/28797671/67756127-650cd180-fa74-11e9-9c3f-a4b68713654a.png)

**Comment by luismanez** [comment]
and if memory serves me well, you can see that "type" value if you call:
_/_api/lists/getbytitle('MyList')?$select=ListItemEntityTypeFullName_

**Comment by Karthickraju2690** [comment]
Thanks Andrew, actually my list name is different and I am using the correct one which I got with the help of `_/api/lists/getbytitle('MyList')?$select=ListItemEntityTypeFullName`

I am using Python sharePoint online library -[Office365-REST-Python-Client](https://github.com/vgrem/Office365-REST-Python-Client) to create new list item. I am able to successfully create new list.

Only when I try to create new list with Multi-choice field, I receive an error
`An open collection property 'Multichoicefield' was found. In OData, open collection properties are not supported.", "400 Client Error: Bad Request for url:`

Seems like OData stopped supporting this. 

Note: Have already tried like `'Multichoicefield': {'results': ['Choice #1', 'Choice #2', 'Choice #3']}`, but couldn't be successful as it throws `A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.`. so, I had to use `'Multichoicefield':{ '__metadata' : {'type' : 'Collection(Edm.String)' }, 'results': ['value1', 'value2'] }`

I've already raised the issue on library's Github page [here](https://github.com/vgrem/Office365-REST-Python-Client/issues/134)

**Comment by Jerry0527** [comment]
You can add a item with multi choice field in the UI firstly and then check the Json response with Rest:

_api/web/lists/getbyTitle('MyList')/items

Make sure the field name is valid and the value should be mateched in the field settings:


![QQ截图20191030160817](https://user-images.githubusercontent.com/28797671/67839892-a0b8a180-fb2f-11e9-9160-f2e0a94cb3c6.png)

**Comment by Karthickraju2690** [comment]
I can add new item with multi choice field through UI and below is the detail:

![image](https://user-images.githubusercontent.com/46005386/67842917-50eac380-fab8-11e9-9330-0c2dc895ed7e.png)

**Comment by Jerry0527** [comment]
'Multichoicefield': {'results': ['Enter Choice #1', 'Enter Choice #2', 'Enter Choice #3']}  works in my side, change fieldname and choice option with yours for a test.

**Comment by Karthickraju2690** [comment]
I've tried Jerry. 

Error is `An open collection property 'Multichoicefield' was found. In OData, open collection properties are not supported.", "400 Client Error: Bad Request for url:`

It seems like problem is with OData. When do we get this error? On what scenario will this be thrown?

**Comment by Jerry0527** [comment]
You can test with JavaScript firstly, as I can't reproduce the error you are meeting in my side. Then migrate to Python.

**Comment by Karthickraju2690** [comment]
I am not much familiar with that.... I can see you code above, but doesn't have authentication part. Can you share complete example to test or if you can share a link that would be helpful

**Comment by Jerry0527** [comment]
My code snippet above is a complete example....
If you want to learn about call Rest API with Jquey ajax, please refer here:

[CRUD Operations On A SharePoint List Using REST API](https://www.c-sharpcorner.com/article/crud-operation-on-a-sharepoint-list-using-rest-api/)
