### ISSUE TITLE
SharePoint Online - Tasks not get completed

### ISSUE THREAD

**Issue by naveenprasaths** [SharePoint/sp-dev-docs#484]
Hi,
I am using SharePoint - O365, Where we have a tasks list. When i click Complete Task checkbox it tooks more time to complete and sometimes it gets revert back ie) Tasks not getting completed. What are the factors for this issue? Is there any way to resolve it?

**Comment by amishra0909** [comment]
@naveenprasaths, please explain your scenario in detail. Is the the task list created using JSOM on modern page? If yes, how are you doing it? What is the role of SPFx in your scenario? Also, can you post some screenshots of the error you see.

**Comment by naveenprasaths** [comment]
The task list is a default Task list. I have added the Tasks list in site template and created a new site with this template. In that case, if i complete the Tasks by clicking "Mark As Complete" check box, it took more time to change the status to "Completed" and also sometimes it didn't gets completed. It stays in the "In Progress" status. It throws "Save conflict" error.

**Comment by patmill** [comment]
Sorry - this isn't related to SPFX / development from what I can tell here.
