### ISSUE TITLE
RefinementFilters Documentation

### ISSUE THREAD

**Issue by campuslane** [SharePoint/sp-dev-docs#4842]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

The example for RefinementFilters shows fileExtension equals docx example.  Is there any documentation anywhere on other RefinementFilters options like not equal, startswith, or similar?  Or how to combine filters with AND/OR etc.   I can't find the documentation online, and have to rely on blog posts, stackoverflow answers etc. 

`'RefinementFilters': {
    'results': ['fileExtension:equals("docx")']
  }`

**Comment by OS-Lee** [comment]
[RefinementFilters ](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#refinementfilters)is specified as FQL filters so you could check  [FQL syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/fast-query-language-fql-syntax-reference).
