### ISSUE TITLE
Can't connect to my customize Azure AD-secured APIs in listview extension

### ISSUE THREAD

**Issue by 598490521** [SharePoint/sp-dev-docs#4851]
Can't connect to my customize Azure AD-secured APIs in listview extension, A very serious problem happened.
Error screenshots:
![image](https://user-images.githubusercontent.com/57263544/68036078-f2178b00-fcff-11e9-9e04-e298365d549a.png)

My code is as follows:
```
    this.context.aadHttpClientFactory
      .getClient('https://contoso.azurewebsites.net')
      .then((client: AadHttpClient): void => {
        client
          .get('https://contoso.azurewebsites.net/api/orders', AadHttpClient.configurations.v1)
          .then((response: HttpClientResponse): Promise<Order[]> => {
            return response.json();
          })
          .then((orders: Order[]): void => {
            // process data
          });
      });
```

**Before October 18, it's ok. But it doesn't work now. I think this is a problem caused by the spfx upgrade**

**Comment by andrewconnell** [comment]
Dupe... see #4840
