### ISSUE TITLE
SPFx 1.9.1 local workbench failure when using pnpm

### ISSUE THREAD

**Issue by Js-Brecht** [SharePoint/sp-dev-docs#4853]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Local workbench should load successfully when using `gulp serve`.

#### Observed Behavior

`gulp serve` completes successfully, no errors or warnings.  However, a great deal of exceptions are thrown in the devtools console on the local workbench site.  I am attaching a copy of the console log.

[localhost-1572741541800.log](https://github.com/SharePoint/sp-dev-docs/files/3801106/localhost-1572741541800.log)

<details>
<summary>Just a small excerpt, for those coming along after</summary>

```
sp-loader-assembly_default.js:11572 [1572741463288][RootServiceScope] AadTokenProviders: Failed to initialize
sp-loader-assembly_default.js:11572 [1572741463290][RootServiceScope] ServiceScopeBuilder: Added preloaded FormDigestValue to cache
sp-loader-assembly_default.js:10685 [1572741463297][Session] The pageId parameter was undefined or invalid. Generating a new Guid
./lib/Api/Log/LogHandler.js.LogHandler.warn @ sp-loader-assembly_default.js:10685
sp-loader-assembly_default.js:10673 [1572741463299][RootServiceScope] AadTokenProviders: Failed to initialize
sp-loader-assembly_default.js:10673 [1572741463299][RootServiceScope] ServiceScopeBuilder: Added preloaded FormDigestValue to cache
sp-loader-assembly_default.js:10673 [1572741463303][ManifestStore] ***Manifest not found for component id "cc2cc925-b5be-41bb-880a-f0f8030c6aff".
sp-loader-assembly_default.js:11572 [1572741463303][ManifestStore] ***Manifest not found for component id "cc2cc925-b5be-41bb-880a-f0f8030c6aff".
sp-loader-assembly_default.js:10673 [1572741463305][SPComponentLoader.loadComponen] ***Loading component "4df9bb86-ab0a-4aab-ab5f-48bf167048fb" (SPApplicationBase).
sp-loader-assembly_default.js:11572 [1572741463305][SPComponentLoader.loadComponen] ***Loading component "4df9bb86-ab0a-4aab-ab5f-48bf167048fb" (SPApplicationBase).
sp-loader-assembly_default.js:10673 [1572741463307][SPComponentLoader.loadComponen] ***Loading component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators).
sp-loader-assembly_default.js:11572 [1572741463307][SPComponentLoader.loadComponen] ***Loading component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators).
sp-loader-assembly_default.js:10673 [1572741463307][SPComponentLoader.loadComponen] ***Loading component "467dc675-7cc5-4709-8aac-78e3b71bd2f6" (SPComponentBase).
sp-loader-assembly_default.js:11572 [1572741463307][SPComponentLoader.loadComponen] ***Loading component "467dc675-7cc5-4709-8aac-78e3b71bd2f6" (SPComponentBase).
sp-loader-assembly_default.js:10673 [1572741463309][SPComponentLoader.loadComponen] ***Loading component "0773bd53-a69e-4293-87e6-ba80ea4d614b" (SPExtensionBase).
sp-loader-assembly_default.js:11572 [1572741463309][SPComponentLoader.loadComponen] ***Loading component "0773bd53-a69e-4293-87e6-ba80ea4d614b" (SPExtensionBase).
sp-loader-assembly_default.js:10673 [1572741463309][SPComponentLoader.loadComponen] ***Loading component "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" (react).
sp-loader-assembly_default.js:11572 [1572741463309][SPComponentLoader.loadComponen] ***Loading component "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" (react).
sp-loader-assembly_default.js:10673 [1572741463310][SPComponentLoader.loadComponen] ***Loading component "aa0a46ec-1505-43cd-a44a-93f3a5aa460a" (react-dom).
sp-loader-assembly_default.js:11572 [1572741463310][SPComponentLoader.loadComponen] ***Loading component "aa0a46ec-1505-43cd-a44a-93f3a5aa460a" (react-dom).
:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_default.js:10673 [1572741463345][SPComponentLoader.loadComponen] ***Component "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" (react) loaded.
sp-loader-assembly_default.js:11572 [1572741463345][SPComponentLoader.loadComponen] ***Component "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" (react) loaded.
:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_default.js:10679 [1572741463352][SPComponentLoader.loadScript] EventName:[SPLoaderError.urlStatusLocalhostFileNotFoundError]:
***Failed to load URL 'https://localhost:4321/node_modules/.pnpm/registry.npmjs.org/@m
sp-loader-assembly_default.js:11569 [1572741463351][SPComponentLoader.loadScript] [SPLoaderError.urlStatusLocalhostFileNotFoundError]:
***Failed to load URL 'https://localhost:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js' for resource 'decorators' in component 'f97266fb-ccb7-430e-9384-4124d05295d3' (Decorators). The file was not found in the server. Make sure that you are running 'gulp serve'.

***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:8828:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4354:28)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__../lib/error/ErrorBuilder.js.ErrorBuilder.buildErrorWithErrorLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4275:21)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__../lib/error/ErrorBuilder.js.ErrorBuilder.buildUrlStatusLocalhostFileNotFoundError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4209:21)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__../lib/utilities/ResourceUrlChecker.js.ResourceUrlChecker._throwUrlStatusError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:7357:87)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:7348:43
    at async Promise.all (index 0)
./lib/Api/Trace/TraceLogger.js.TraceLogger._writeToConsole @ sp-loader-assembly_default.js:11569
sp-loader-assembly_default.js:10673 [1572741463352][SPComponentLoader.loadComponen] ***Failed to load component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators). Original error: ***Failed to load URL 'https://localhost:4321/node_mo
sp-loader-assembly_default.js:11572 [1572741463352][SPComponentLoader.loadComponen] ***Failed to load component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators). Original error: ***Failed to load URL 'https://localhost:4321/node_mo
sp-loader-assembly_default.js:10673 [1572741463353][SPComponentLoader.loadComponen] ***Loading component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators). Attempt 2 of 3.
sp-loader-assembly_default.js:11572 [1572741463353][SPComponentLoader.loadComponen] ***Loading component "f97266fb-ccb7-430e-9384-4124d05295d3" (Decorators). Attempt 2 of 3.
:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_default.js:10673 [1572741463392][SPComponentLoader.loadComponen] ***Component "aa0a46ec-1505-43cd-a44a-93f3a5aa460a" (react-dom) loaded.
sp-loader-assembly_default.js:11572 [1572741463392][SPComponentLoader.loadComponen] ***Component "aa0a46ec-1505-43cd-a44a-93f3a5aa460a" (react-dom) loaded.
:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_default.js:10679 [1572741463397][SPComponentLoader.loadScript] EventName:[SPLoaderError.urlStatusLocalhostFileNotFoundError]:
***Failed to load URL 'https://localhost:4321/node_modules/.pnpm/registry.npmjs.org/@m
sp-loader-assembly_default.js:11569 [1572741463397][SPComponentLoader.loadScript] [SPLoaderError.urlStatusLocalhostFileNotFoundError]:
***Failed to load URL 'https://localhost:4321/node_modules/.pnpm/registry.npmjs.org/@microsoft/sp-webpart-base/1.9.1_052fcf153ec79c77e0d1778fd73206f7/node_modules/@microsoft/decorators/dist/decorators.js' for resource 'decorators' in component 'f97266fb-ccb7-430e-9384-4124d05295d3' (Decorators). The file was not found in the server. Make sure that you are running 'gulp serve'.
```

</details>

This appears to be related to use of `pnpm` as a package manager, in a mono-repo (workspaces) environment.  When using `npm`, the workbench for the same repo works flawlessly.  Also notable: this works perfectly fine when **not** running in a workspace.  If I scaffold just a basic standalone webpart project, I can use `pnpm` without any issues.

I recently updated my repo to SPFx v1.9.1, to take advantage of the libraries feature, which is when it began to fail.  This used to work with SPFx 1.8.2.  I also recently updated `pnpm` to version 4, and they changed some things in the way it handles `node_modules`, so I thought maybe that was part of the problem.  Rolled back to version 3.8.2; same problem.

I also tested on the hosted workbench, and didn't have any problems.  Using a freshly scaffolded HelloWorld webpart, I am able to `gulp serve` successfully, then load up the hosted workbench, and mount the webpart to the page, no problems.

Judging by the nature of the exceptions being thrown, I think this issue is similar to #3736.  The workbench does not seem to like the location of the `node_modules` directory 🤷‍♂; same kind of thing that is happening there.  This is actually very similar to what I experienced when trying to use `rush` as the monorepo manager (using `pnpm` with it, too); that was when I was still using SPFx v1.8.2.  Which is why I went back to using `pnpm` alone, and that worked fine... until the upgrade to 1.9.1 🙄 

I'm getting similar results as #4261, but I don't think the issues are related.

#### Steps to Reproduce

* Create a pnpm workspace environment
* Scaffold an HelloWorld webpart starter using yeoman
    * `yo @microsoft/sharepoint --package-manager pnpm`
* After installation, run `gulp serve`
* Observe exception hell from your browser

**Comment by Js-Brecht** [comment]
So, after further investigation, I've figured out that the entire issue is that `pnpm` symlinks dependencies to the root `node_modules`, which isn't exposed by `gulp serve`.

It looks like this:

```
workspace-root
|-- node_modules
  |-- .pnpm
    |-- @microsoft
      |-- sp-webpart-workbench
|-- packages
  |-- workspace1
    |-- node_modules
      |-- @microsoft
        |-- sp-webpart-workbench >> ../../../../../node_modules/.pnpm/@microsoft/sp-webpart-workbench
```

The server's working directory is `workspace-root/packages/workspace1`, so it is unable to serve files located in `workspace-root/packages/workspace1/../../node_modules`.

**Comment by andrewconnell** [comment]
Need some help here... can you provide a public repo to repro this?

Also... I'm not sure this is an SPFx issue, rather an issue with PNPM & workspaces. It's not clear from your issue what the problem is with SPFx...

**Comment by Js-Brecht** [comment]
[Here's a reproduction repository](https://github.com/Js-Brecht/pnpm-spfx-workspace-issue)

This issue is present in yarn workspaces, Lerna workspaces (using yarn), and rush workspaces.  It's all the same issue... those three hoist common dependencies to the root of the repo so they can be shared by all of the workspaces.  pnpm does it for all workspace dependencies, no matter what, and then symlinks from each workspace's `node_modules`, to the root `node_modules`.

I was able to get this working using yarn workspaces a couple different ways:

1. Use `--nohoist '**/@microsoft/**`, or put `"nohoist": ["**/@microsoft/**"]` in the package.json `workspaces` field.
    * Even using `--link-duplicates`, this reeaaallly slows down the build.

2. Loop through `@microsoft/*` dependencies+sub-dependencies for a workspace and hardlink them from the root `node_modules` into the workspace `node_modules` (if they don't already exist).
    * Much, much faster, and 100% effective
    * Have to check sub-dependencies, too, because they might have been hoisted into the root `node_modules`, too.

It wasn't until after I figured out what the root problem was that I realized this might not be something that could be fixed by SPFx.  Is it possible to have `gulp serve` also serve files from a `node_modules` that is in a parent directory.... ?

I put together a little postinstall script for lerna/yarn that can be run for each workspace (that needs the local workbench), but it needs to be extended a little bit.  I am also working on implementing features to support pnpm workspaces, too, but that's just a little bit more involved.  I'll post it here when I'm done with it, for anybody else with this problem.

I think the ideal solution would be to address this in a) `gulp serve` (if it's possible), or b) the package manager.  I opened a ticket with pnpm to try to get some insight on how to address this problem, or if maybe they'd include a feature that would solve this.

One thing I'm curious about... any idea why this would have changed between SPFx v1.8.2, and SPFx v1.9.1?  I'm starting to think that maybe I just didn't go back far enough in pnpm versions.  I will run a test later with v1.8.2, to see if it will actually still work with pnpm v4.

**Comment by Js-Brecht** [comment]
After examining some of `pnpm`'s code, I noticed that it puts the `.pnpm` directory where its lockfile is.... And I always use `shared-workspace-lockfile = true`, which is what causes it to store all of the dependencies in the root `node_modules/.pnpm`.  Turning that off fixes the problem.

**Comment by andrewconnell** [comment]
Sorry, but I don't think this is an "issue" or something that's wrong with SPFx or the SPFx build toolchain. Microsoft recommends NPM for the package manager... what you're running into (at least how I understand it) isn't a supported scenario as it sounds like to get this to work with PNPM, you need changes made to the **gulp serve** task.

Therefore, this falls more in the case of a feature request or a design change request which belongs in user voice as things are working by design today.
