### ISSUE TITLE
[SPFx] [404] Not Found errors during pnpm install

### ISSUE THREAD

**Issue by Js-Brecht** [SharePoint/sp-dev-docs#4854]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A successful install

#### Observed Behavior

Periodically, I run into a problem installing dependencies for packages using pnpm... I don't recall ever having this issue with any other package managers.

It will, intermittently, decide that it cannot find `@ms/*` packages.  Which makes sense, because those aren't available for download from any public registry (closed source packages?).  Once this happens, I can try installing as many times as I like, but it will **always** fail with the same error, but every install results in it failing to find a _different_ `@ms/*` package....
![image](https://user-images.githubusercontent.com/1935258/68091110-c5f32b80-fe1f-11e9-8fe3-557de99d7a23.png)

The only way I've been able to get around this is to completely delete my node_modules, and reinstall from scratch.

#### Steps to Reproduce

This is an intermittent issue, so it won't be very easy to reproduce.  However, I just had it happen in [this repository](https://github.com/Js-Brecht/pnpm-spfx-workspace-issue).

I guess my question right now is, where is it finding `@ms/*` sources to download?  If I knew that, maybe I could figure out why it's getting hung up periodically.

**Comment by johnguy0** [comment]
@Js-Brecht Is this still intermittently happening with 1.10.0? Our private package dependencies shouldn't be leaking into the public package dependencies.

@iclanton Thoughts?

**Comment by Js-Brecht** [comment]
It happened once or twice more not too much longer after I posted this.  But it hasn’t  since maybe mid/late December.

Maybe it’s some idiosyncrasy in pnpm that’s since been fixed?  🤷‍♂️

**Comment by johnguy0** [comment]
@Js-Brecht It's possible. I'm going to close the issue, but please feel free to open a new one if this happens again. Thanks!
