### ISSUE TITLE
PropertyPaneDynamicField filters

### ISSUE THREAD

**Issue by timdw** [SharePoint/sp-dev-docs#4855]
Please mention that you can filter the source using the filters property of IPropertyPaneDynamicFieldProps. The online documentation is non existent, maybe this is because it has been moved to @microsoft/sp-property-pane?
https://docs.microsoft.com/en-us/javascript/api/sp-webpart-base/ipropertypanedynamicfieldprops?view=sp-typescript-latest
Maybe also point out that filtering by componentId will prevent interoperability with other components, as I found out when I tried to use the standard File viewer web part. It can only connect to Microsoft's Document library web part because of this feature.

Just as a reference for anyone else, here's the documentation from the code for the filters properties:

> Component Id.
> Usage: Use this filter when the author should only be able to connect to a
> specific type of source.
> This is to filter what type of source needs to be shown in the data sources
> dropdown (first level) on the dynamic data widget.
> When provided, the dynamic data sources dropdown in the dynamic data widget
> is filtered to only show the sources matching the given component id.
> Example - If the document library web part component id is supplied, then
> the dynamic data sources dropdown only shows document library web parts on
> the page which are registered dynamic sources.
> 
> Property Id
> Usage: Use this filter when the author can only to connect to a specific
> property from the selected source.
> This is to filter which specific property is to be pre-selected in the
> properties dropdown(second level) on the dynamic data widget.
> When provided, the dynamic data properties dropdown is pre-selected to show
> the specific property, if avaialble. Otherwise the dropdown will fall back
> to show all the exposed properties from the source. If a property is
> pre-selected, the control will be disabled to ensure that authors can not
> change it.
> 
> Source Id
> Usage: Use this filter, when the author can only to connect to a specific
> data source.
> This is to filter which specific source is to be pre-selected in the data
> sources dropdown (first level) on the dynamic data widget.
> When provided, the dynamic data sources dropdown is pre-selected to show the
> source with the provided id, if available. Otherwise the dropdown will
> fall back to show all the existing data sources on the page. If a source
> is pre-selected, the control will be disabled to ensure that authors can not
> change it.
> The source id for a web part will be of the form
> WebPart.&lt;ComponentId&gt;.&lt;InstanceId&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79444829-20bc-3b07-8820-29b55798761a
* Version Independent ID: 546cff82-d871-917e-10ba-55df6f18e5eb
* Content: [Connect SharePoint Framework components using dynamic data](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data#feedback)
* Content Source: [docs/spfx/dynamic-data.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/dynamic-data.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like the docs for the **@microsoft/sp-property-pane** package aren't getting posted to the docs.microsoft.com site. Investigating...
