### ISSUE TITLE
Are these still valid

### ISSUE THREAD

**Issue by tiwilk** [SharePoint/sp-dev-docs#4856]
Do these scripts still work now that Opt-Out at tenant level has been removed? I was trying to Opt-In at a site level and was unable to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 267c10c8-06a1-82b8-224e-4cea30144f0a
* Version Independent ID: 1d18b823-62d1-c44b-cdb0-a326e142b487
* Content: [Opting out of the modern list and library experience](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-optout#feedback)
* Content Source: [docs/transform/modernize-userinterface-lists-and-libraries-optout.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-lists-and-libraries-optout.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You can still opt-out of modern lists and libraries by enabling a site or web scoped feature. You mentioned opt-in...and that's not needed. 

SharePoint uses modern lists and libraries by default unless you've opted out at site, web or list level. 

If a list can't be shown in modern then SharePoint will automatically flip back to the classic rendering of the list
