### ISSUE TITLE
Missing escape character example

### ISSUE THREAD

**Issue by jbostoen** [SharePoint/sp-dev-docs#4857]
This lacks essential info on how to properly escape certain characters (:) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d931357-f63f-1f3d-5e2f-90d32c5d3818
* Version Independent ID: f95bfa79-cd41-208d-9d2d-6d2724f605ae
* Content: [Keyword Query Language (KQL) syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#feedback)
* Content Source: [docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/keyword-query-language-kql-syntax-reference.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
FYI: @wobba

**Comment by wobba** [comment]
@jbostoen You cannot really escape characters in KQL. The best you can do is add quotes around it. Special characters are also tokenized away, unless you use complete matching.

Eg. the query `title:"page: with a link::::"` will ignore the :'s and still match, and there is no escape character to use to force them.

What's your concrete scenario?

**Comment by jbostoen** [comment]
@wobba The idea is to match an exact subject 
`subject="specific subject but it contains a wildcard at the end which should be escaped*"`

**Comment by wobba** [comment]
@jbostoen not doable with kql. You can however use FQL where you can turn off wild card expansion. https://docs.microsoft.com/en-us/sharepoint/dev/general-development/fast-query-language-fql-syntax-reference#fql_string_operator That said, the property you query against have probably tokenized away the * anyways - so not easily solvable.

Which means, there is nothing to add to the docs for this the way I see it.

**Comment by jbostoen** [comment]
Could this use case be mentioned as an example of a limitation where it's simply impossible to escape this?

Can FQL be used in a compliance search against Exchange Online?

**Comment by wobba** [comment]
@jbostoen FQL can not be used in compliance search afaik, and not sure what operators are supported for Exchange search. The KQL docs you refer to also relates to SharePoint content, not Exchange.
