### ISSUE TITLE
NPM Errors related to office-ui-fabric-react

### ISSUE THREAD

**Issue by CindyRay** [SharePoint/sp-dev-docs#4858]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm not sure if this is a bug or something that is specific for my environment. 

For the last couple weeks, I have been unable to install packages in my solution.
Windows 10 Enterprise
I'm using version 1.9.1 of the generator.  
Node 10.13.0
NPM 6.4.1

I have the same issue with Yarn and pnpm.

When installing files I get the following:
EPERM: operation not permitted, open 'C:\dev\test\node_modules\.staging\office-ui-fabric-react-bcd6c5b9\lib\components\ThemeGenerator\ThemeGenerator.doc.js'

The above is just a sample, this occurs for all the components in that folder.

McAfee EndPoint Security is blocking these files because of double extensions.  I notice in the folder, the names of the extensions of these files are doc.js.map.

I've been working with my networking engineers.  They say nothing has changed on their part.  
Turning  McAfee off is not an option.  

Is this something that has been reported or does anyone have any suggestions?

**Comment by JakeStanger** [comment]
From personal experience, having antivirus scanning node_modules and your NPM/yarn cache is always going to cause problems. The problem is your antivirus locks the file to be scanned just before your package manager tries to read it. 

Unfortunately the only feasible solution we've come across is to add a real-time scanning exclusion to the relevant directories.

**Comment by andrewconnell** [comment]
This is specific to your environment. As @JakeStanger commented, your A/V is blocking this. This would happen with any NPM package and isn't specific to this package.

Other than what @JakeStanger suggested, the only other solution is to get the package authors of the package that's causing issues. But, you'll likely run into this same issue with other packages down the road.

Regardless, this isn't a SharePoint / SPFx issue... this should be posted to the Office UI Fabric project site as the SharePoint team can't address this as it's not something they "own".

**Comment by JakeStanger** [comment]
I will say that I have had a bizarrely large number of similar issues with Fabric compared to any other package, so it is probably an issue worth raising with them.
