### ISSUE TITLE
SPFx Provisioning - WriteSecurity and ReadSecurity is ignored

### ISSUE THREAD

**Issue by nsoeth** [SharePoint/sp-dev-docs#4859]
#### Category
- [ ] Question
- [ ] Typo
- [ x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I add the Properties
```
WriteSecurity="2" 
ReadSecurity="2"
```
to my schema.xml file in the <List> node, they get ignored. After provisioning the list, they are still on "1" in the created list. When I add these properties to the ListInstance, the app installation fails completely.

My example line, which is not working (took them from the official docs):
`<List xmlns:ows="Microsoft SharePoint" Title="Basic List" EnableContentTypes="FALSE" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Basic List" BaseType="0" WriteSecurity="2" ReadSecurity="2" xmlns="http://schemas.microsoft.com/sharepoint/">`

#### Observed Behavior

In the schema.xml when provisioning a list for SPFx.

#### Steps to Reproduce

Try to set WriteSecurity and ReadSecurity to another value in the schema.xml.

**Comment by andrewconnell** [comment]
Which docs are you referring to?

**Comment by nsoeth** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package

I have to say that I took the example line and added these two properties. So I believe, they are "missing" from the provisioning process. I didn't found any mention, that these are working.

**Comment by andrewconnell** [comment]
I was looking more for a doc that references the list schema. The only one I'm aware of doesn't list these two properties at all on the public schema, which implies:

- they don't exist
- they are not public and thus, not supported to be set

_REF MS docs: [List element](https://docs.microsoft.com/en-us/sharepoint/dev/schema/list-element-list)_

**Comment by nsoeth** [comment]
No I didn't found anything. I wasn't aware they need to be available, I thought all properties just get written into the SchemaXML of the list.

When I get the list per PowerShell and take a look at the SchemaXml, they are there once I set the properties through the advanced list settings UI.

Is there any chance these get added to the "List element schema"?

**Comment by andrewconnell** [comment]
That would be considered a feature request, which should be submitted to user voice.

@nsoeth said:
> Is there any chance these get added to the "List element schema"?

My personal opinion (not MSFT's stance): nope. The feature schema is supported, but that's not the preferred or "modern" way to provision assets. They will push you towards Site Designs & Scripts or to use the PnP provisioning framework.

**Comment by nsoeth** [comment]
Okay thank you a lot. Sorry for the wrong label. Like I said, I thought it would be just written into the SchemaXml.

I'll take a look at the PnP Provisioning framework.
