### ISSUE TITLE
sharepoint framework + AngularJs 2 

### ISSUE THREAD

**Issue by jfarissi** [SharePoint/sp-dev-docs#486]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

sharepoint framework + AngularJs 2 

I'm this Error after gulp serve

Popup message
**Argument number 2 is missing. stringformat was called with format ***failed to component "{{0}}" {{1}}. Original error {2}** 

afrer i have this message in my page 

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloWorldWebPart.e5f316d5-1057-453a-9981-6ce6c4a6dc48,Error: ***Failed to component "43188899-ef76-432b-886f-28fd928dc22d" (HelloWorldWebPart). Original error: script resources due to: undefined.

Any idea to resolve ?

**Comment by webtechy** [comment]
Example here:

https://github.com/webtechy/sp-dev-fx-webparts/tree/master/samples/angular2-taxonomy

Could be your web part constructor has an issue, or a component's constructor. Also try running `gulp clean` first.

**Comment by amishra0909** [comment]
Hi @jfarissi, was the issue resolved using the example which @webtechy pointed to?

**Comment by iclanton** [comment]
Please reopen this issue if you're still having this problem.

**Comment by zuhairrizvi** [comment]
@jfarissi @iclanton I'm getting the similar error when trying to reference template in the web part. Any idea?
