### ISSUE TITLE
SPFx webpart not loading on Single Part App Page (onInit not triggered) when running MS Teams desktop client for targeted release users

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#4860]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When adding a static tab in MS Teams which references a SharePoint page with SPFx webparts on it, the webparts should load for all users.

#### Observed Behavior

When adding a static tab in MS Teams which references a SharePoint page with SPFx webparts on it, the webparts do not load for some users. It used to work find before the weekend, and then suddenly some users started experiencing issues.

#### Debug information

Using Chrome dev tools in MS Teams, I noticed the **onInit** function of the webpart is never initiated. However the .js webpart file **is** loaded fine. It just doesn't seem to start execution.

> Also, in the SPFx debug window (ctrl+f12), the messages show that the webpart is loaded.
> 2019/11/05 08:28:01.963  verbose   SPComponentLoader.loadComponen  ***Loading component "26fce1e5-3884-4c29-8e53-b9641aae605d" (HomeViewWebPart). 
> 2019/11/05 08:28:01.963  verbose   SPComponentLoader.loadComponen  ***Loading component "26fce1e5-3884-4c29-8e53-b9641aae605d" (HomeViewWebPart).

Example request's correlation id: 62cd149f-b092-9000-9e2a-0b6777fa527f (I think?)

**Edit:** the issue occurs on **single part app pages** only. When reverting the page to a "normal" page layout, the webparts load just fine. When switching back to single part app page, the issue returns.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

**Edit 2:** turns out the issue occurs for all users in targeted release. So, not sure what feature is in there, but we definitely hope it won’t break all users when going to GA :o

**Comment by andrewconnell** [comment]
Which Teams client... web / native? 

There are known issues with the desktop & mobile Teams clients with SPFx solutions. As announced at Ignite, these will be fixed in the SPFx v1.10 update + Teams November 2019 update.

**Comment by NickSevens** [comment]
Actually all non-web clients.
What worries us the most, and keeps us hesitant to implement certain solutions for customers, is that the same issue occurs with the OOTB webparts, and only on Single Part App pages.

**Comment by andrewconnell** [comment]
Like I said in my last comment, it's a known limitation is being fixed in the Teams November 2019 client update. This was shared during the SPFx session @ MSFT Ignite 2019.

**Comment by NickSevens** [comment]
Okay, thanks for the info @andrewconnell
