### ISSUE TITLE
Custom task for serve

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#4863]
How can I make a custom task to run when debugging (gulp serve)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ea7187-d184-a7d7-bee8-eafffc5b2b47
* Version Independent ID: e34bb8a6-c90d-275d-57d9-840534ec46e4
* Content: [Integrate gulp tasks in SharePoint Framework toolchain](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline#feedback)
* Content Source: [docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Available extension to add custom task(1.8.2 for my environment).

![image](https://user-images.githubusercontent.com/40845109/68285225-d3c3dd80-00b9-11ea-8b4b-24cd883da044.png)

Add custom task.

`let helloWorldSubtask = build.subTask('log-hello-world-subtask', function(gulp, buildOptions, done) {
    this.log(buildOptions);   
    // use functions from gulp task here
    done();
  });

build.rig.addBuildTasks(helloWorldSubtask);

build.initialize(gulp);`

This will run when you run `gulp serve` or update code(build) when debugging.
