### ISSUE TITLE
ListViewCommand: listView.selectedRowsChangedEvent is not fired when user changes selection in list view.

### ISSUE THREAD

**Issue by 23W** [SharePoint/sp-dev-docs#4864]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Each time when user changes selection in list view, `ListViewAccessor.selectedRowsChangedEvent` should be fired.

#### Observed Behavior

```ts
  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, 'Initialized HelloWorldCommandSet');

    if (this.context.listView !== undefined) {
      this.context.listView.selectedRowsChangedEvent.add(this, this.onSelecteChanged);
    }

    return Promise.resolve();
  }

  private onSelecteChanged(args: SelectedRowsChangedEventArgs): void {
    console.log('onSelecteChanged called');
  }
```

Method `onSelecteChanged` is not called when user changes selection in list view.

#### Steps to Reproduce

1. Add event handler for `listView.selectedRowsChangedEvent` event.
2. Change selection in list view
3. Handler is not called.

**Comment by 23W** [comment]
Can be tied with https://github.com/SharePoint/sp-dev-docs/issues/4828

**Comment by andrewconnell** [comment]
This is a dupe... see #4769. Also, it's fixed & the fix is currently rolling out worldwide to all tenants.
