### ISSUE TITLE
How to format a Group By view

### ISSUE THREAD

**Issue by jogood** [SharePoint/sp-dev-docs#4865]
I could not find a way to format the Group By view.

I could not find a way to get values from previous/next rows to make my own Group By either.

For example, it doesn't seems possible to go from this:

![image](https://user-images.githubusercontent.com/17586546/68149406-dc76b100-ff0b-11e9-91d4-5a76e8723186.png)

to the following grouped format:

![image](https://user-images.githubusercontent.com/17586546/68149480-f7e1bc00-ff0b-11e9-9796-38a64184cdc0.png)

This is the default available formating for a group by:

![image](https://user-images.githubusercontent.com/17586546/68149647-42fbcf00-ff0c-11e9-8327-dbdd8836fa75.png)

Edit:
(Remade the last screenshot to be more like my examples)

Available formating for a group by:
![image](https://user-images.githubusercontent.com/17586546/68151069-07163900-ff0f-11e9-8649-9cd63d550918.png)

_Originally posted by @jogood in https://github.com/SharePoint/sp-dev-docs/issues/3495#issuecomment-549501487_

**Comment by gobigfoot** [comment]
This is not currently supported in the JSON schema. I would also appreciate adding the ability to modify / style group headings.

**Comment by Dennis-LZ** [comment]
As a workaround, we can use column formatting to achieve it.

Example:

Create a custom list "TestList", add new field "Value". Group by the default "Title" field.

Formatting "Title" column using the JSON below.

```
{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
   "elmType": "div",
   "txtContent": "[$Value]"
}
```
Formatting "Value" column using the JSON below.

```
{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
   "elmType": "div",
   "txtContent": ""
}
```

The result:

![Capture](https://user-images.githubusercontent.com/55479607/68464778-292ff400-024c-11ea-9e84-53eac4d4949d.PNG)
