### ISSUE TITLE
ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library

### ISSUE THREAD

**Issue by oliverlp** [SharePoint/sp-dev-docs#4868]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In a library with a pinned document, when I selected a document from a view, the Listview Command Set will return the ID of the selected document, and not the ID of the pinned document.

SPFx version 1.4 and 1.8

#### Observed Behavior

event.selectedRows[0].getValueByName('ID') returns the ID of the pinned document, not the selected row in the library

#### Steps to Reproduce

Create a listview command set and apply it to a library.
Add 4.  documents, and pin one of them.
Select one of the others and click on the command. The event will return a wrong ID.

**Comment by oliverlp** [comment]
Note: It works for spfx 1.9.1, but I have extensions in production with previous versions.

**Comment by oliverlp** [comment]
I move this to another repo https://github.com/SharePoint/sp-dev-fx-extensions/issues/267

**Comment by oliverlp** [comment]
I move this to another repo SharePoint/sp-dev-fx-extensions#267

**Comment by oliverlp** [comment]
Now it does not work for 1.9.1.

**Comment by oliverlp** [comment]
Hi,
I'm reopening the issue here as 10 days have gone by and and I'm not getting feedbak on SharePoint/sp-dev-fx-extensions#267
I'm sorry but I'm unsure in which repo I should report SPFx bugs.
Thanks in advance.

**Comment by andrewconnell** [comment]
@oliverlp said:
> I'm not getting feedback on SharePoint/sp-dev-fx-extensions#267 I'm sorry but I'm unsure in which repo I should report SPFx bugs.

That repo is just a collection of samples... it's not monitored except by those who have uploaded samples. This (sp-dev-docs) is the correct repo.

There is currently a fix rolling out worldwide related to selected items in lists. Can you keep an eye on #4769 and see if once that's closed, it's addressed?

**Comment by oliverlp** [comment]
@andrewconnell , 
Yes, I'll do that. Thanks for your answer.

**Comment by oliverlp** [comment]
This is solved now.
