### ISSUE TITLE
Make host name configurable / change "localhost" occurances in SPFx modules

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#487]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I tried to deploy the workbench to a Docker container on Azure but it fails to work properly. Technically it was running correctly but I spotted some issues in the SharePoint Framework.
The scenario for this is to allow customer to preview web parts and test the behaviour before the web part will be deployed to any tenant.
In addition this scenario allows enhance and improve cross browser testing as well es automated front end testing
It would be great to make hostname configurable vie `serve.json`.

#### Observed Behavior
Currently the workbench cannot run on any other host name than localhost. This is because inside the framework the "localhost" string is exposed in many different source files in the node modules. Overall the treatment of the host name is inconsistent in many ways.
`serve.json` allows to set ports and an initial start page, even if another host name is defined there the all requests will be redirected to localhost.

**Comment by patmill** [comment]
@iclanton - FYI

**Comment by iclanton** [comment]
Sounds like a good idea to me. I'll create a work item for it.

**Comment by amishra0909** [comment]
Fixed.

**Comment by StfBauer** [comment]
@amishra0909 Is this fixed version currently available?

**Comment by StfBauer** [comment]
"Fixed" is not a valid reason to close an issue.
@iclanton Can you please provide some more information because @amishra0909 won't respond for some reason?

Thank you in advance.

**Comment by VesaJuvonen** [comment]
Hi @StfBauer, @amishra0909 is not from Microsoft, so will now re-open this to be able to follow up on the actual request. Actual request does make lot of sense.

**Comment by StfBauer** [comment]
Thank you @VesaJuvonen !
