### ISSUE TITLE
In SPFx Command set extension onListViewUpdated event is not fired while opening/traversing a folder inside document library

### ISSUE THREAD

**Issue by sameerjmansuri** [SharePoint/sp-dev-docs#4870]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

onListViewUpdated event should be fired while opening or traversing folders inside the document library.

#### Observed Behavior

Form last 2 or 3 days i noticed that the onListViewUpdatedevent is not fired. onListViewUpdatedevent is fired after i select any folder/item in list view.

It was working perfectly fine before 2-3 days.

#### Steps to Reproduce

Open document library and open any folder or traverse back to root folder. It will never invoke onListViewUpdated event. 

#### Submission Guidelines

 I have written a code to show the command set extension only if the user is in the first level of folders in list view and not at the root level of folders.

Code:
@override
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const salesFolderCreateCommand: Command = this.tryGetCommand('OpportunityCommand');
    
    ClientFolderURL = this.getParameterByName("id",window.location.href);
    if (salesFolderCreateCommand) {
      if(ClientFolderURL != null && ClientFolderURL != "")
      {
        var clientCurrentFolder = ClientFolderURL.substring(ClientFolderURL.indexOf("/Sales1/"),ClientFolderURL.length);
        if(clientCurrentFolder.split('/').length == 3)
          salesFolderCreateCommand.visible = true;
        else
          salesFolderCreateCommand.visible = false;
      }
      else
      salesFolderCreateCommand.visible = false;
    }
  }

Example: 
Document Library
-Test A (Root Level Folder) - Extension button is hidden
      -Test AA (First Level Folder) - Extension button is visible
            -TestAAA (Second Level Folder) - Extension button is hidden
-Test B (Root Level Folder) - Extension button is hidden
      -Test BB (First Level Folder) - Extension button is visible
            -TestBBB (Second Level Folder) - Extension button is hidden

**Comment by 23W** [comment]
I think it's the same as https://github.com/SharePoint/sp-dev-docs/issues/4828, https://github.com/SharePoint/sp-dev-docs/issues/4769 and maybe https://github.com/SharePoint/sp-dev-docs/issues/4864. Current version of SPO script works improperly: notifications about selection/content changes are NOT processed by SPFx in some cases.

**Comment by andrewconnell** [comment]
As referenced above, a fix is rolling out that may address this... see #4769... supposed to be fully rolled out by Wednesday, NOV 20.

**Comment by sameerjmansuri** [comment]
Thanks for rolling a fix.
