### ISSUE TITLE
triggerFlow to Azure function

### ISSUE THREAD

**Issue by bmarcos81** [SharePoint/sp-dev-docs#4872]
Is there any possibility to trigger an Azure function with http request trigger? I know that Logic App is an alternative to MS Flow, but as a developer I prefer to skip no-code intermediaries. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Unfortunately no, this is not possible. You'll need to call Flow or Logic Apps.
