### ISSUE TITLE
HTML Injection when it's not required?

### ISSUE THREAD

**Issue by pconnell99** [SharePoint/sp-dev-docs#4874]
I found https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/react-menu-footer-classic-modern/SPFx/src/extensions/customHeaderFooter/CustomHeaderFooterApplicationCustomizer.ts from a month after this page was generated and it doesn't do the HTML injection as a bove - a no-no accordign to my React-developing friends.  Why the discrepancy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, Thank you for the question. It's a bit unclear what you are asking... Can you provide more detail?
