### ISSUE TITLE
Can I hide default "Approve/Reject" item property?

### ISSUE THREAD

**Issue by srinutamada** [SharePoint/sp-dev-docs#4877]
I got a requirement to hide default "Approve/Reject", Publish, Cancel Approval options from item properties.

Requirement:
Users uploads documents to the document library. All these document should appear after review and approval process. The contribute user or approve user should not get an option to publish or approves the document using OOTB operations. These actions should be happen using Flow because of business requirements.

SharePoint online + SPFx

**Comment by andrewconnell** [comment]
This isn't supported... you can't change the default menu options without using DOM manipulation which isn't supported.
