### ISSUE TITLE
SPFX- Not able to commit across site collection.

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#4881]
SPFX is allowing us to deploy in teams as well but if I want to create or update or delete a list item which is located in the different site collection, I am not allowed to do it, but can able to read items and show in the data table.

If I could able to commit across site collection then I can deploy all my custom development in one site collection and i can do the transaction in other transactions as well.

**Comment by bcameron1231** [comment]
Thanks for the question.

Are you able to share your request and the error you are getting? There shouldn't be a problem deleting/creating/updating items in a different site collection using REST.

**Comment by nsksaisaravana** [comment]
@bcameron1231 Sorry my bad, it works like charm. SPFX rocks !!!

**Comment by nsksaisaravana** [comment]
I am closing this.
