### ISSUE TITLE
spfx listview command 

### ISSUE THREAD

**Issue by EricZhaoM** [SharePoint/sp-dev-docs#4882]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

#### Expected or Desired Behavior

> when there are more lists on the site, and click the left navigation to the list, the onInit() and onListViewUpdated just execute once to the every list, when you click the navigation  back to the list from other list, the two functions not execute .
>

>

#### Observed Behavior

>  when there are more lists on the site, and click the left navigation to the list, the onInit() and onListViewUpdated just execute once to the every list, when you click the navigation  back to the list from other list, the two functions not execute .

#### Steps to Reproduce

> 1.Created a new SPFX ListView Command Set as in Microsoft site
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api
>2. code: public onInit(): Promise<void> {
   alert(1);
    return Promise.resolve();
  }
  public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    alert(2);
}
>3. deploy on the sharepoint
4. click the left navigation to the list first time, the two functions execute normally, then click the navigation to the other list, the two functions execute normally too, but then click the navigation back to the list, the two functions not execute

#### Submission Guidelines

I think is a big bug about the spfx listview command, because I want show the button by the list title, but when back to the list, the function not execute, so the button don't show anymore.

**Comment by andrewconnell** [comment]
Sorry, but unclear what you're trying to do or what the error is. What button are you referring to? Can you provide a repo in a project in a public github repro showing your error?

**Comment by EricZhaoM** [comment]
public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
alert(2);
}
 this function is not work when click the left navigation to go to the list view

**Comment by SaSapalan** [comment]
@andrewconnell , we can reproduce the issue in these scenario

-> You have a Listview Command applied 
-> And you are performing some operation on the event OnListviewUpdated 
-> You have two or more lists (in the Quick Launch)
-> When you navigate to the list from the Quick Launch for the first time , then the event is getting fired
-> If you navigate to the same list again from the quick launch (without refreshing the page) then the event is not getting fired.

**Comment by vijaybhanu** [comment]
Hi,
I'm facing the same issue. 
Steps:
Scenario1:
1) I have two lists say list1, list2 with different command sets cs1,cs2
2) When I click on list 1 from left navigation it is showing cs1 command set
3) Again when I click on list2 from left navigation it is showing cs2 command set
4) Now I click on list 1 from left navigation, here it is not showing cs1 but showing cs2 command set
Scenario2:
1) I have two lists say list1, list2 with different command sets cs1,cs2
2) When I click on list 2 from left navigation it is showing cs2 command set
3) Again when I click on list1 from left navigation it is showing cs1 command set
4) Now I click on list 2 from left navigation, here it is not showing cs2 but showing cs1 command set

Second time click it is not loading the proper command set but showing the previously loaded command set.

**Comment by andrewconnell** [comment]
There are some known issues with lists & the raising of events that SPFx extensions rely on [that MSFT has commented that fixes are coming](https://github.com/SharePoint/sp-dev-docs/issues/4191#issuecomment-539724040)... trying to track down exactly what those are as I believe this may be related. Will follow up when I learn something...

**Comment by SaSapalan** [comment]
onListViewUpdated event does not fire if you visit the same list again within the same page.  And it fires only on these two scenarios

1)  When visiting the list first time
2) When selection is changed in the view

Seems to be intended change for performance improvement and by design.

**Comment by westleyMS** [comment]
@andrewconnell should this be closed out as by design? Or is there a change coming?

**Comment by patmill** [comment]
(sorry - lost in a metadata shuffle).  The command sets will be created / initialized once, and then may be cached / resused when you navigate back and forth.  We have fixed issues around navigating and the correct command sets being shown..  However, we are iterating on future improvements here - https://github.com/SharePoint/sp-dev-docs/discussions/7375
