### ISSUE TITLE
AlertCreationInformation class not available SPFX solution using JSOM for creating alerts

### ISSUE THREAD

**Issue by ashiqf** [SharePoint/sp-dev-docs#4883]
I am trying to create List alert using JSOM in SPO SPFx solution. The class/property AlertCreationInformation is not available, getting the message Property 'AlertCreationInformation' does not exist on type 'typeof SP' . The property is not available in the file index.d.ts

JSOM libraries are referred on the solution declaratively as per the reference article https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom

`let notify = new SP.AlertCreationInformation;`

Could you please help

**Comment by OS-Lee** [comment]
Sample demo:

`public render(): void {
    SPComponentLoader.loadCss('/_layouts/15/1033/styles/corev15.css');  
    
    SPComponentLoader.loadScript('/_layouts/15/init.js', {
      globalExportsName: '$_global_init'
    })
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
        globalExportsName: 'Sys'
      });
    })
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/ScriptResx.ashx?name=sp.res&culture=en-us', {
        globalExportsName: 'Sys'
      });
    })
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
        globalExportsName: 'SP'
      });
    })
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
        globalExportsName: 'SP'
      });
    })
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/sp.init.js', {
        globalExportsName: 'SP'
      });
    })        
    .then((): Promise<{}> => {
      return SPComponentLoader.loadScript('/_layouts/15/sp.ui.dialog.js', {
        globalExportsName: 'SP'
      });
    });
this.domElement.innerHTML = `
      <div class="${ styles.fixWebpart }">
        <div class="${ styles.container }">
          <div class="${ styles.row }">
            <div class="${ styles.column }">
              <span class="${ styles.title }">Welcome to SharePoint!</span>
              <p class="${ styles.subTitle }">Customize SharePoint experiences using web parts.</p>
              <p class="${ styles.description }">${escape(this.properties.description)}</p>            
              <input id="myButton" type="button" value="Click me" />                                  
            </div>
          </div>
        </div>
      </div>`

    this.domElement.querySelector('#myButton').addEventListener('click', () => { this.MyNotify(); });
}
public MyNotify():void{ 
var ctx = SP.ClientContext.get_current();

  var user = ctx.get_web().get_currentUser();
  var alerts = user.get_alerts();
  var list = ctx.get_web().get_lists().getByTitle('Documents');

  ctx.load(user);
  ctx.load(alerts);
  ctx.load(list);

  ctx.executeQueryAsync(()=> {
    let alertTime = new Date();
    alertTime.setHours(alertTime.getHours() + 24);

    let notify = new SP.AlertCreationInformation;

    notify.set_title('Documents - Movers and Shakers');
    notify.set_alertFrequency(SP.AlertFrequency.daily);
    notify.set_alertType(SP.AlertType.list);
    notify.set_list(list);
    notify.set_deliveryChannels(SP.AlertDeliveryChannel.email);
    notify.set_alwaysNotify(true);
    notify.set_status(SP.AlertStatus.on);
    notify.set_alertTime(alertTime);
    //notify.set_user(this.user.get_loginName());
    notify.set_user(user);
    notify.set_eventType(SP.AlertEventType.all);

    // 0 = Anything Changes
    // 1 = Someone else changes a document
    // 2 = Someone else changes a document created by me
    // 3 = Someone else changes a document modified by me
    notify.Filter = '0';
    
    debugger;
    alerts.add(notify);
    user.update();  
    
    ctx.executeQueryAsync(()=> {
       console.log('CHEESE ON TOAST!'); debugger; 
      }, 
      ()=> { 
        console.log('EGGS!'); 
      })
  }, ()=> {
    console.log('WORSE THAN EGGS!');
  });
  }`

Alert code from [here](https://gist.github.com/beckettkev/6f3389963294aa1b566a59fde48dc245)

**Comment by ashiqf** [comment]
Thanks Lee for the comment, the code implementation for accessing the JSOM properties is Imperative & not declarative. I've added the import statement
import { SPComponentLoader } from '@microsoft/sp-loader';
And the code you have given on the Render method, the build is still failing. Its not able to resolve the following properties get_alerts(),AlertCreationInformation,AlertFrequency,AlertType etc

**Comment by OS-Lee** [comment]
Add `declare var SP:any;` to avoid build error.

![image](https://user-images.githubusercontent.com/40845109/68724670-1ecc7c00-05f7-11ea-994d-b52e58d797b3.png)

**Comment by ashiqf** [comment]
This works! Thanks for the help.
