### ISSUE TITLE
SPFx Solutions are dead in MS Teams

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4884]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx solutions work in MS Teams

#### Observed Behavior

Login fails when the web part is served through Teams:
```
ERROR:
Token renewal operation failed due to timeout

CALL STACK:
Error: Token renewal operation failed due to timeout
    at Array.<anonymous> (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/teams-web-part-application-assembly_default_c630174accea338c987cda5dc34553ec.js:20:89032)
    at Object._callBackMappedToRenewStates.<computed>._callBackMappedToRenewStates.<computed> (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/chunk.vendors~sp-http-adal_6a29bd503d1db27efc57.js:1:7704)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-10-18.027/chunk.vendors~sp-http-adal_6a29bd503d1db27efc57.js:1:10166
```

#### Steps to Reproduce

Serve any SPFx solution in Teams.
<img width="1183" alt="Screen Shot 2019-11-11 at 11 56 35 AM" src="https://user-images.githubusercontent.com/17036219/68616712-71345e00-047a-11ea-8172-3fa30e7ddc5d.png">

**Comment by AJIXuMuK** [comment]
Details from console:
```
Refused to display 'https://splstdemo.sharepoint.com/_forms/spfxsinglesignon.aspx#access_token=ACCESS_TOKE_GOES_HERE&token_type=Bearer&expires_in=3599&state=522a5414-9c1c-4add-9b0f-47a29c631b63%7chttps%3a%2f%2fgraph.microsoft.com&session_state=66c20ccd-6f38-4d2d-acc8-5fbae46d7044' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

**Comment by patmill** [comment]
Hmn - does this only happen if you are doing OAuth token fetches?

**Comment by huey253** [comment]
@AJIXuMuK does this issue repro on MS Teams Desktop, Browser or both?

**Comment by lahuey** [comment]
The issue should be resolved. Please clear your browser cache if you're still seeing issues.

Thanks!

**Comment by AJIXuMuK** [comment]
Wow, that was quick!
I can confirm that it has been fixed.
