### ISSUE TITLE
SPFx Teams Tab can't be set up/added to the preprovisioned team

### ISSUE THREAD

**Issue by Kirill-Vostretsov** [SharePoint/sp-dev-docs#4886]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have a webjob that provisioning a MS Teams  with several channels and tabs in each channel based on some information from user. To some of these channels SPFx Teams tab is being added. 
After MS Teams creating I expect user to be able to start working with SPFx Team Tab without any additional actions. 

#### Observed Behavior
After MS Teams creation if I(user) go directly to preprovisioned SPFx Teams Tab or try to add a new one to any channel I'm receiving the following: 
![image](https://user-images.githubusercontent.com/13979978/68656163-98019b80-0531-11ea-8e6a-a4106662f158.png)
with the following information in the console:

```
2019-11-12T08:50:52.724Z AUTHADAL: Iframe - AuthenticationContext: cddde464-a1d9-48a7-8d39-57368dfaf6e7, Error :invalid_resource; Error description:AADSTS500011: The resource principal named https:// was not found in the tenant named <TenantID>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 52e7c0a1-682d-4c86-9857-43ce1e889400
Correlation ID: 0e50c20f-e106-47c8-859c-23b2da9615ad
Timestamp: 2019-11-12 08:50:51Z
```
```
angular.min.js:113 2019-11-12T08:50:52.776Z AUTHADAL: Attempting to handle adal response: error:AADSTS500011: The resource principal named https:// was not found in the tenant named 3ccc0137-e738-4461-87b6-4709e880587c. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:https://, error mapped to action:resourceDisabled
```
```
angular.min.js:113 2019-11-12T08:50:52.787Z ExtensionTabService: prefetchAuthTokenForApp: Failed to find app with error - resourceDisabled
```
In console network explorer each time I observe following call meanwhile:
`Request URL: https://_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=5da598e4-b78c-44d9-b3c2-373e6a016133%26forceLocale=en-us`

To make it work I need for example open default Files tab to see the following message
![image](https://user-images.githubusercontent.com/13979978/68657038-38a48b00-0533-11ea-801a-827bae04b634.png)
After some time visiting Files tab will work just fine. 
And starting from that moment the SPFx MS Team App will be added/ set up without any issues.

P.S. It's not an issue for the our of the box Teams.

#### Steps to Reproduce

Prerequisites:
- Dummy SPFx Teams app deployed to SharePoint Apps Catalog and synced already with MS Teams
I was following the the path of webjob
1. Create 0365 Group with Graph API (/v1.0/groups)
2. Set classification (/beta/groups/)
3. Set External access (/v1.0/groups/{groupGuid}/settings)
4. Add  some users as Owner/Members
5. Extending group with the team (/v1.0/groups/{groupGuid}/team)
6. Install SPFx Tab to the Team (/beta/teams/{groupGuid}/installedApps)
7. Get list of Channels (/v1.0/teams/{groupGuid}/channels)
8. Add SPFx Tab to any channel  (/v1.0/teams/{groupGuid}/channels/{channelId}/tabs)
with the following configuration tab

```
{
"displayName": "SPFx Tab",
"teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/{teamsSPFxAppI}",
"configuration": {}
}
```
Thank you for your help in advance

**Comment by qrown** [comment]
Hi @Kirill-Vostretsov, this might be related to this issue: #3063

**Comment by andrewconnell** [comment]
Agree with @qrown ... this looks like a dupe to #3063, a known issue that's still tracked.
