### ISSUE TITLE
Specified $skiptoken is invalid.

### ISSUE THREAD

**Issue by jwiersem** [SharePoint/sp-dev-docs#4889]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
API management page does not give error when openen and approve/reject buttons are not grayed out.

#### Observed Behavior

API management page gives the error ' Specified $skiptoken is invalid.' and approve/reject buttons are not working.
I added an SPFX webpart and then this occurred. The webpart is working on another tenant and the AAD App it uses is available in Azure. I want the API management page working again and the SPFX WebPart permissions approved.

#### Steps to Reproduce

Upload an spfx webpart in the app catalog that requests api permissions

![api_management](https://user-images.githubusercontent.com/37477912/68671643-09e8dd80-0550-11ea-9435-f7841257704e.png)

**Comment by andrewconnell** [comment]
I'm not seeing this in my tenants, but I am seeing the following in a TR SPO tenant:

![image](https://user-images.githubusercontent.com/2068657/68683453-cd5bb880-0534-11ea-93a3-ee2cbdc373dd.png)

No pending permission requests in my tenant... will raise visibility with SP engineering...

**Comment by andrewconnell** [comment]
Until then @jwiersem, try granting the permissions via POSH / Office 365 CLI.

**Comment by jwiersem** [comment]
Microsoft support fixed the issue for the tenant almost immediately. Also
it turns out that you need more rights than just SP admin to approve api
permissions!

Op di 12 nov. 2019 16:12 schreef Andrew Connell <notifications@github.com>:
