### ISSUE TITLE
Getting the context (and URL) in a service

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#489]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
This used to be so easy, and the complexities of TypeScript have cost me days :-(

#### Observed Behavior
I have a service where I simply want to know the site URL. I have tried various solutions.

#### Steps to Reproduce
See line 305 here:

[https://github.com/webtechy/sp-dev-fx-webparts/blob/master/samples/angular2-taxonomy/src/webparts/requirementsForm/app/services/DataHelperSP.ts](https://github.com/webtechy/sp-dev-fx-webparts/blob/master/samples/angular2-taxonomy/src/webparts/requirementsForm/app/services/DataHelperSP.ts)

```
      //let layoutsUrl: string = this.context.pageContext.site.absoluteUrl;
      let layoutsUrl: string = (<any>window)._spPageContextInfo.siteAbsoluteUrl;
```

The above is a "hack" (but doesn't work consistently across the SP workbench and actual deployment). I have also tried:

  `      window.console && console.log((<any>SP).ClientContext.get_current());`

But I get "SP is not defined". This shouldn't be so difficult.

**Comment by patmill** [comment]
Certainly stay away from the _spPageContextInfo window variable.  That may or may not be present, may likely be out of date if it is present, etc.  context.pageContext.xxx is the right approach to take.  What is wrong with the commented out code -  //let layoutsUrl: string = this.context.pageContext.site.absoluteUrl; ?

**Comment by webtechy** [comment]
context is undefined. I believe this goes back to the web part not passing it into the component.

**Comment by patmill** [comment]
Can you pass it in / set it manually after the component is created?  There are all sorts of things in the context you are going to want to use (like the SPHttp object, context, logging, etc.)

**Comment by webtechy** [comment]
The knockout-taxonomy example does:

```
  public render(): void {
    this.domElement.innerHTML = `
      <div class="${styles.termSetRequester}">
        <div class="${styles.container}">

        </div>
      </div>`;

      const container: HTMLDivElement = this.domElement.querySelector('.' + styles.container) as HTMLDivElement;
      var termStoreCtrl = new TaxonomyControl(this.context);
      termStoreCtrl.render(container);
  }
```

However, I am doing:

```
public render(): void {
    this.domElement.innerHTML = `
    <app-root></app-root>
    `;
    platformBrowserDynamic().bootstrapModule(AppModule);

  }
```

But, it seems daft to me that I have to trickle the context down the hierachy like that. The nearest I can find is to do something like the following (but that is not the full IWebPartContext):

```
import pnp from "sp-pnp-js";

      pnp.sp.site.getContextInfo().then(function(result) {
        let layoutsUrl: string = result.SiteFullUrl;
      });
```

**Comment by patmill** [comment]
So the context has a collection of per-webpart data in it that you will want to maintain.  It's technically possible for two webparts to be on the same page with completely different contexts, pointing to different webs, etc.  Certainly not standard operating, but possible.  Your code seems to have a constructor that takes a context - are you just not setting it?  Do you not have it present in your constructing class?

**Comment by webtechy** [comment]
Ah, I had assumed that the context was the same per page you are on, not per web part.

New to both Angular 2, SPFx, and TypeScript so was a little unsure how to pass the context down at this point:

```
public render(): void {
    this.domElement.innerHTML = `
    <app-root></app-root>
    `;
    platformBrowserDynamic().bootstrapModule(AppModule);

  }
```

I notice that the examples you find do:

```
using { IWebPartContext } from '@microsoft/sp-client-preview'

public constructor(context: IWebpartContext) {
  super(context)
}
```

Which I assume in the GA release you do:

```
import { IWebPartContext } from '@microsoft/sp-webpart-base';
public constructor(context: IWebpartContext) {
  super(context)
}
```
