### ISSUE TITLE
More details on `Retrieve List Schema`?

### ISSUE THREAD

**Issue by SeaDude** [SharePoint/sp-dev-docs#4890]
Thank you for the great docs. Will you provide some more details on how to request a custom list's schema using:
```
POST https://contoso.sharepoint.com/sites/team-a/_api/web/GetList(@listUrl)/RenderListDataAsStream?@listUrl=%27%2Fsites%2Fteam-a%2Flists%2FList%27
accept: application/json;odata=nometadata
content-type: application/json;odata=nometadata

{
    "parameters": {
        "RenderOptions": 4
    }
}
```
**Specifically:**
  - Where do I insert the list name/ID?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
If you want to get list schema with Rest API, please refer the following snippet:

```
<script type="text/javascript">
$.ajax({
	url:"https://zheguo.sharepoint.com/sites/dev/_api/web/lists/getbytitle('MyList12')?$select=schemaXml",
	type: "GET",
	async: false,
	headers: { "Accept": "application/json; odata=verbose" },
	success: function (data){
		var listProperties = schemaXml2Json(data.d.SchemaXml);
		console.log(listProperties);
		//alert( parseInt(listProperties.Author));
	},
	error: function (err){
	   console.log(JSON.stringify(err));
	}
});

function schemaXml2Json(schemaXml)
{
		var jsonObject = {};
		var schemaXmlDoc = $.parseXML(schemaXml);
		$(schemaXmlDoc).find('List').each(function() {
		$.each(this.attributes, function(i, attr){
		jsonObject[attr.name] = attr.value;
		});
		});
	    return jsonObject;
}

</script>
```
The schema will display like this in  Browser Console:

![QQ截图20191113142701](https://user-images.githubusercontent.com/28797671/68738598-ae872000-0621-11ea-9870-c59a97ecf786.png)

**Comment by SeaDude** [comment]
Thanks for the response. 

The Docs say to issue a **POST** request. Is the **GET** method you propose a better option? Should the docs be changed?

**Comment by Jerry0527** [comment]
@SeaDude,
For Post Request, it will be also available to get list schema, please see the code demo below:

```
<script type="text/javascript">
var APIUrl = _spPageContextInfo.siteAbsoluteUrl + "/_api/web/lists/getbyTitle('MyList12')/RenderListDataAsStream";
console.log(APIUrl);

var call = $.ajax({
		     url: APIUrl,
		     type: "POST",
             data: JSON.stringify
             ({
                 parameters:
                 {
                     RenderOptions: 4
                 }
              }),
             headers:
             {
                 "Accept": "application/json;odata=verbose",
                 "Content-Type": "application/json;odata=verbose",
                 "X-RequestDigest": $("#__REQUESTDIGEST").val(),
                 "X-HTTP-Method": "POST"
             },
             success: function (data, status, xhr) {
                 console.log(data);
                 console.log(status);
             },
             error: function (xhr, status, error) {
                 console.log(data.responseJSON.error);
             }
       });

</script>
```
This is the response:
![QQ截图20191114140307](https://user-images.githubusercontent.com/28797671/68830750-83670400-06e7-11ea-9318-f085d7a6679c.png)

So in this case, both GET/POST is avialable to do the same thing, get list schema.

**Comment by SeaDude** [comment]
Thanks for the help.
