### ISSUE TITLE
How to get List's Id, which ListView Commands Set is connected?

### ISSUE THREAD

**Issue by 23W** [SharePoint/sp-dev-docs#4891]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Instance of ListView Commands Set extension is tied with list view representation of SP list. This list's Id is accessible in `ListViewCommandSetContext` (i.e. `this.context.page.pageContext.list.id`). But when list is shown as part of custom page (e.g. Home page), `this.context.page.pageContext.list.id` contains Id of other list (id of "Site Pages" list), not the list connected with Commands Set. 

How to get correct list's Id on any pages?

**Comment by gobigfoot** [comment]
Command Set can't get the id of the list within WebParts #4238, #4687  They really need to fix this issue.

**Comment by johnguy0** [comment]
The answer in #4238 is correct. As your submission is an enhancement on existing feature or a feature request, we cannot process it through this channel. Please submit your feedback and suggestion using UserVoice, so we can take your suggestion into account in our future planning. Thank you for your input in advance.
