### ISSUE TITLE
MSGraphClient Error AADSTS650056 with IE in "InPrivate" mode

### ISSUE THREAD

**Issue by virtualducttape** [SharePoint/sp-dev-docs#4895]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When a user is authenticated with SharePoint Online, they should be able to navigate to a page containing SPFx components using the Graph API without needing to authenticate again, regardless of browser. The "seamless" Graph API is supposed to be a feature of SPFx, and the behavior we see when using Chrome matches the behavior we expect with regards to the Graph API.

If the Graph API needs to reauthenticate for some reason, it should be able to use the currently-functioning SharePoint Online session to "reestablish" authentication for the Graph API (single sign on is supposed to handle this sort of thing...) without needing to prompt the user to reauthenticate.

#### Observed Behavior
When using IE to connect to a SharePoint Online "legacy" page containing an SPFx component that uses the Graph API, we are sometimes prompted with an authentication message (possibly related to an expiring token similar to #2685 ?), and we are *always* prompted for it when we use IE "InPrivate" mode to connect to the page. (If I had to guess, I suspect that the Graph API is trying to store/load it's authentication token in a storage mechanism that isn't available in IE "InPrivate" mode? Regardless, it should "fall back" to establishing the Graph API connection from the current SharePoint session without needing user input)

Dialog title: "Message from webpage" 
>  To view the information on this page, you need to verify your identity.

Clicking "OK" on this dialog redirects you to the "Pick an Account" step (which does not require you to provide a password, because you are already authenticated with that account). And after that you get redirected to the root site collection, but if you attempt to navigate to the page containing the SPFx component, the "loop" starts again.

No matter how many times we jump through the "Pick an Account" step and "verify our identity", every time we hit the page containing the SPFx component, we are once again prompted with the same dialog, that then redirects us to "Pick an Account", and it just loops forever. If we hit the "Cancel" button instead of OK, the page loads, but without retrieving the Graph API content that we requested (this part is probably working as expected, since it seems to think we're not authenticated).

The redirect URL at the end of the loop also includes an error message:
> AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'Microsoft Graph' in the requested permissions in the client's application registration. Or: The admin has not consented in the tenant. Or: Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. 

However, this error message seems inaccurate to me, because if I follow the same repro steps using Chrome, it is able to load the Graph API resources seamlessly, without needing to prompt me to "verify my identity" or anything. Surely the Graph API shouldn't care which browser I'm connecting from?

#### Steps to Reproduce

1. Open new InPrivate IE browser session
2. Paste URL for page containing SPFx component which loads a Graph API resource (for what it's worth, the resource I'm trying to load is an "Open Extension") into the address bar
3. Hit enter
4. Sign in to tenant with SharePoint Online account using normal procedure
5. "Message from webpage" message appears, "To view the information on this page, you need to verify your identity" (page URL and Title show up for the "correct" page as expected in browser) 
6. Click "OK" button on dialog
7. Dialog shows up a second time (perhaps because we have two SPFx components that use the Graph API?)
8. Click "OK" button on dialog again
9. Browser redirects to "Pick an account" screen: https://login.microsoftonline.com/[guid]/oauth2/authorize?response_type=token&client_id=[guid]&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=[tenantrooturl]%2F_forms%2Fspfxsinglesignon.aspx&state=[guid]%7Chttps%3A%2F%2Fgraph.microsoft.com&login_hint=[currentaccoountname]&client-request-id=[guid]&x-client-SKU=Js&x-client-Ver=1.0.16&prompt=select_account
10. Select the same account that you signed in with earlier (which is present in the "login_hint" value, and you are not prompted to provide credentials a second time, so it's obviously still authenticated)
11. Browser then redirects to: https://[tenantrooturl]/_forms/spfxsinglesignon.aspx#error=access_denied&error_description=AADSTS650056%3a+Misconfigured+application.+This+could+be+due+to+one+of+the+following%3a+The+client+has+not+listed+any+permissions+for+%27Microsoft+Graph%27+in+the+requested+permissions+in+the+client%27s+application+registration.+Or%2c+The+admin+has+not+consented+in+the+tenant.+Or%2c+Check+the+application+identifier+in+the+request+to+ensure+it+matches+the+configured+client+application+identifier.+Please+contact+your+admin+to+fix+the+configuration+or+consent+on+behalf+of+the+tenant.+Client+app+ID%3a+[guid].%0d%0aTrace+ID%3a+[guid]%0d%0aCorrelation+ID%3a+[guid]%0d%0aTimestamp%3a+2019-11-13+15%3a54%3a29Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d650056&state=[guid]%7chttps%3a%2f%2fgraph.microsoft.com
12. This then redirects to the root site collection, and if we attempt to navigate back to the page containing the SPFx component, we jump back to step 5.

**Comment by andrewconnell** [comment]
Can you confirm you are using IE11 when the Document Mode is set to IE 11 as listed in the supported browsers?

https://support.office.com/en-us/article/which-browsers-work-with-office-for-the-web-ad1303e0-a318-47aa-b409-d3a5eb44e452

**Comment by virtualducttape** [comment]
Well, I'm not sure why I was seeing the behavior I was (working in Chrome but errors in IE 'InPrivate' mode), but it turns out the error message I was getting was actually correct. We had not granted (in this tenatn) the SPFx solution the Microsoft Graph access needed for what we were doing.  This ticket can be closed, though the fact that Chrome wasn't giving me the error is still very confusing.
