### ISSUE TITLE
Property Pane in Single Part App Page gets stuck closed but in edit mode with unresponsive Save button

### ISSUE THREAD

**Issue by trey-miller** [SharePoint/sp-dev-docs#4897]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Clicking the X to close the property pane should leave Edit mode and re-enter Read mode, and the Save button should revert to an Edit button.

#### Observed Behavior

Clicking the X to close the property pane closes the pane, but does not leave Edit mode and does not revert the Save button into the Edit button. In this state, clicking the Save button does nothing, and it is not possible to re-open the property pane until the browser is refreshed.

#### Steps to Reproduce

1. On a single part app page, click the Edit button to open the property pane.
2. Click the X in the upper right to close the property pane.
3. See that the property pane closes, but there is still a Save button which does nothing, and no way to re-open the property pane.

This is potentially related to my other open issues #4456 and #4550 

Thanks!

**Comment by andrewconnell** [comment]
Appears to be a dupe / very closely related to root of #4896 that is being investigated...
