### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by Disc0veryX** [SharePoint/sp-dev-docs#4899]
On this page and others in the section "WorkflowInfo schema reference", there is a problem with words in tables, that have to be **bold**. Instead of it I see only asterisks in the text. Please, fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 234f2dd3-aeb7-9b52-66d0-8c58c62ff093
* Version Independent ID: 85879237-437d-589d-6dc2-f1dcb06dcf5f
* Content: [FieldBind Element (WorkflowInfo)](https://docs.microsoft.com/en-us/sharepoint/dev/schema/fieldbind-element-workflowinfo?source=docs)
* Content Source: [docs/schema/fieldbind-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/fieldbind-element-workflowinfo.md)
* Product: **office-online-server**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you  for the issue. I've made a pull request to fix the table.

On a side note, I've noticed you've put in a couple issue requests before. Any chance you'd be interested in help improve the documentation? The docs are open source and we are always looking for more help to improve them!
