### ISSUE TITLE
SPSite:id is not a Guid type

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#49]
The `id` property of `SPSite` is of the format `string` instead of `Guid`, which is what the `SPWeb` class is using for the `id` property.

**Comment by huey253** [comment]
This issue has been addressed and should be resolved in the next update. Thank you for the feedback

-Landis

**Comment by nickpape-msft** [comment]
Closing this issue as it was addressed in [Drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2). Please re-open if necessary
