### ISSUE TITLE
Gulp 3 is no longer supported

### ISSUE THREAD

**Issue by 23W** [SharePoint/sp-dev-docs#4900]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

`yo @microsoft/sharepoint`  should be updated to use Gulp 4.

#### Observed Behavior

Command `yo @microsoft/sharepoint` with all default settings for SharePoint Online Application Customizer generates project with dev-dependency from gulp **3.9.1**.
Gulp 3 is not compatible with NodeJS 12 **LTS**. It crashes with exception https://github.com/gulpjs/gulp/issues/2324
The single solution is to use Gulp 4 that doesn't depend on outdated packages.

#### Steps to Reproduce

1. Install NodeJS LTS (it's 12.13.0 currently)
2. run `npm install -g yo gulp @microsoft/generator-sharepoint`
3. run `yo @microsoft/sharepoint` with all defaults
4. try to build solution `gulp bundle --ship`
5. You will receive exception https://github.com/gulpjs/gulp/issues/2324

**Comment by bcameron1231** [comment]
Thanks for the comment.

Unfortunately, you are using an unsupported of Node. SPFx currently only supports Node 10x. Please uninstall Node 12, and re-install Node 10.

**Comment by 23W** [comment]
@bcameron1231 
Thank you, not so good news. I hope, new nodejs LTS version will be supported soon.
