### ISSUE TITLE
Steps in adding properties section

### ISSUE THREAD

**Issue by ConaxLiu** [SharePoint/sp-dev-docs#4906]
I think this step "2. Update the web part properties to include the new properties. This maps the fields to typed objects." should be combined with step 3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thanks for your comment. Yes 2 & 3 are referencing the same thing.

If this is unclear, feel free to update the documentation as it is open source! Thanks!

**Comment by ConaxLiu** [comment]
Ok I've created a PR for it. I hope I've done it right. I'm very new to GitHub. :)

**Comment by andrewconnell** [comment]
@ConaxLiu Couple things... first, that's not a PR... you just made an edit to the content in your fork. There's tons of resources out there showing how to submit a PR... please exercise your Google Fu :)

Also, I looked at the edit... all you did was merge two steps into one step... not sure I understand how things are more clear...

**Comment by ConaxLiu** [comment]
Hi @andrewconnell, each step in itself should have something for the reader to action. If I had not watch the video I would have spent hours trying to figure out how to do step 2, while the actual doing part is in step 3.

And sorry for not submitting a PR correctly. I am so new to Github and I actually had to Google what 'PR' means.
