### ISSUE TITLE
Wrong word on page

### ISSUE THREAD

**Issue by ConaxLiu** [SharePoint/sp-dev-docs#4908]
Step 4 in the Render lists information section: "Things to note about hostType in the _renderListAsync method:"
The word "hostType" should be "EnvironmentType"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the issue.

Would you be willing to submit a PR for this change?

**Comment by ConaxLiu** [comment]
Ok I've created a PR for it. I hope I've done it write. I'm very new to GitHub. :)

**Comment by ConaxLiu** [comment]
Oops...hope I've done it *right*.

**Comment by andrewconnell** [comment]
Unfortunately not, you just made the update in your fork. You need to submit a PR to request it to be merged... might want to google how to submit a PR. There are a TON of resources on GitHub and videos on YouTube showing this.

**Comment by andrewconnell** [comment]
@ConaxLiu refer to how I did it in the above links... the only diff: you can't merge your PR once you submit it.

**Comment by ConaxLiu** [comment]
Hi @andrewconnell, on the bottom of every page has this notice: "If you find an issue in the documentation or in the SharePoint Framework, please report that to SharePoint engineering by using the issue list at the sp-dev-docs repository or by adding a comment to this article. Thanks for your input in advance."

That's the reason why I had left comment. I don't even know why I need to try to update the page and submit PR myself. If that's what people need to do to correct possible mistakes on these pages, then the above mentioned notice is rather misleading and should be updated to point readers to the information of exactly how they can contribute properly.
