### ISSUE TITLE
SPO Group Membership UI is not showing correct permissions

### ISSUE THREAD

**Issue by vasanthtt** [SharePoint/sp-dev-docs#4909]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SPO Group Membership users should refect when changes are done through Microsoft Graph API.

#### Observed Behavior

Through Microsoft graph [API](url), I added few users as owners to O365 Group which is associated with my SPO site.

Then when I ran the below API to verify whether those users were added as owners, I found them added as owners. But when I verified the same in the SPO group membership panel, I see those users were showing as group members and sometimes not even visible. inconsistent.

Example:
GET: https://graph.microsoft.com/v1.0/groups/<groupid>/owners
<groupid>: site group id

**Comment by andrewconnell** [comment]
It does take a few moments for the UX to reflect the changes due to caching... give it some time and I've seen them resolve to be eventually consistent.

**Comment by vasanthtt** [comment]
@andrewconnell But its already 3 days still permission showing incorrect in UI

**Comment by andrewconnell** [comment]
That seems too long. I think MSFT would say to open a ticket with your tenant, provide screenshots of what the UI shows & what you see in the API as it's an issue with the rendering of the group members from what you describe..
