### ISSUE TITLE
Content Type missing from Command Set selected rows

### ISSUE THREAD

**Issue by CPritch** [SharePoint/sp-dev-docs#4910]
## Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The method call `getSelectedValueByName("ContentType")` should return a string value of the content type.

#### Observed Behavior

This value is missing from the mapped values.

#### Steps to Reproduce
Env: SPO and SR Tenant

1. Generate a new Command Set extension
2. Attempt to use `item.getSelectedValueByName("ContentType")`
3. Observe that no value is returned

**Comment by andrewconnell** [comment]
I believe only the fields that are present in the view are available in the API. Do you have the **ContentType** field in the view?

**Comment by CPritch** [comment]
> 
> 
> I believe only the fields that are present in the view are available in the API. Do you have the **ContentType** field in the view?

Hi @andrewconnell I don't think that's right. This is true for custom fields but not for certain OOTB columns. It's also the case that a required custom column will always be present in the API also. 

We have had code dependent on this behaviour for a few months in SR now. We have now had to use the OOTB column 'FSObjType' which is also not on the view.

Also ContentType was coming through as the ContentType/Name value via the API. I'm not sure if I can even add that field to the view as I believe I can only use ContentTypeId.

Regardless, this was working in SR and is still working in TR.

**Comment by AJIXuMuK** [comment]
Hi @CPritch.
Sorry for really long delay...

You can get `ContentTypeId` from selected rows and get the Content Type object or name based on it.
There are no plans to expose `ContentType` in these events as this will lead to reduced performance on the page.
