### ISSUE TITLE
Using a SPFx webpart unloads master page fabric css ?

### ISSUE THREAD

**Issue by carletto75** [SharePoint/sp-dev-docs#4919]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I customized a sharepoint site using a Classic master page that loads:
--link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.min.css--

then I use Fabric's Grid system to create a homepage layout,
and placed a webpart zone in each ms-Grid-col zone.

-div class="ms-Grid">
      --div class="ms-Grid-row">
        ---div class="ms-Grid-col ms-xl8 ms-lg12 ms-sm12 block fix-owl-carousel" >
            ----WebPartPages:WebPartZone runat="server" AllowPersonalization="true" ID="WebPartZone2" FrameType="None" Title="<%$Resources:cms,WebPartZoneTitle_Top%>" Orientation="Vertical"

#### Observed Behavior
So far so good. It works.
But, starting today, it does not work any more if I place an SPFx webpart in any webpart zone.
The SPFx webpart (even empty) unloads the Fabric css, and the Grid system does not work any more.
You can look the file:
static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.min.css
disappear from browser's sources only after loading the SPFx webpart.

#### Steps to Reproduce
Create a master page which links:
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.min.css">

then put an SPfx 1.7.0 webpart into it.
you cannot use the fabric.min.css grid system classes in master page any more.

**Comment by carletto75** [comment]
It does not happen any more.
Magically solved. 
(But I lost 1 day :| )

**Comment by carletto75** [comment]
Now happening again this morning.
Should I fix something? Or it's something on your side ?

**Comment by carletto75** [comment]
Problem is still present.
I see other users having workarounds for this problem occurring in SPFx webparts.
I have class="ms-Grid" code in static .aspx pagelayouts instead.
Fabric UI css is referenced in my custom master page: it is initially loaded, but it gets removed when first SPFx webparts is loaded.

**Comment by KevinTCoughlin** [comment]
@carletto75, Fabric core styles are supported in the following scenarios: https://github.com/SharePoint/sp-dev-docs/wiki/Safely-using-legacy-Fabric-Styles

Would it be possible for you to include the Fabric core stylesheet as part of your solution?

The styles were present on the host SPO page due to a bug that has since been patched.

**Comment by carletto75** [comment]
@KevinTCoughlin Fabric css was already linked in my custom classic masterpage.
But was not loaded any more due to new scope.
Now I added "ms-SPLegacyFabricBlock" to the parent div, which olds the ms-Grid content and works fine.
Thank you for pointing me in the right direction!
