### ISSUE TITLE
It is good to have a github code repository associated with this

### ISSUE THREAD

**Issue by chanmmn** [SharePoint/sp-dev-docs#4922]
You have so much code in this page. Isn’t it good to have a github repository associated with this page, something like this one https://github.com/OfficeDev/SharePoint-Add-in-CSOM-BasicDataOperations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code?source=docs)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm unclear as to what your question is... are you asking for a repo with all the snippets in it or a working sample?

**Comment by chanmmn** [comment]
Yes, the code snippets should be the working samples in a solution that people can easily run it. That would be great.

**Comment by andrewconnell** [comment]
Good feedback and a great op for someone from the community to contribute. Interested?

**Comment by chanmmn** [comment]
I can try to put all those code snippet in a .Net Framework console app and organize them accordingly. But need reviewer and maybe other roles.

**Comment by andrewconnell** [comment]
If you create a working console app with these samples, share it and I'll see about getting it moved to an official repo in the SharePoint GH org. Then it can be linked to.

**Comment by chanmmn** [comment]
Sounds good. I will build on my github and share this link with you so you can check the and comment later. Thanks in advance.
