### ISSUE TITLE
HTTP 503: SERVICE UNAVAILABLE - "The service is temporarily overloaded" in Microsoft Edge 

### ISSUE THREAD

**Issue by dev-karpov** [SharePoint/sp-dev-docs#4928]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Environment
- [x] SharePoint Online

#### Expected or Desired Behavior

I should be able to get changes on Site Pages library with Microsoft Edge

#### Observed Behavior

I am getting

> HTTP503: SERVICE UNAVAILABLE - The service is temporarily overloaded.
(Fetch)POST - https://.../_api/web/lists/getByTitle('Site Pages')/getchanges

**NOTE:** The error appears only in Microsoft Edge, in the rest of the browser I do not get this error
(Chrome, Opera, Firefox, Microsoft Edge Dev)

#### Steps to Reproduce

In my SPFx solution I'm using PnP Js,
`sp.web.lists.getByTitle('Site Pages').getChanges({
      Item: true,
      Add: true,
      Update: true,
      DeleteObject: true,
    });`

**Comment by andrewconnell** [comment]
Can you repro this? There's nothing you can do about a 503 as that's a server issue. It doesn't make sense why it would work in one browser and not another.

**Comment by orbus-dkreivenas** [comment]
We are experiencing the same issue. We are running Integration Tests that communicate with SharePoint Online. These tests store excel documents that contain data to be imported, once the import process finish then an excel report is generated and placed in SharePoint. Later this report is retrieved, by running number of these request in sequence we receive the 503. All the tests are run one by one in sequence to ensure a small load, however this does not help. This is slowing down our CI pipeline as Integration Test are failing and need to be rerun constantly, can we please have this looked at as soon as possible?
