### ISSUE TITLE
requiresCustomScript and CSS

### ISSUE THREAD

**Issue by trey-miller** [SharePoint/sp-dev-docs#4930]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

A quick question on the `requiresCustomScript` property in the web part manifest: Does this apply to allowing custom CSS as well, or just custom JavaScript? For example, if a web part has a configuration property that is a text editor that accepts arbitrary CSS styles, and the web part on render will append those styles to the page (e.g. inside a style block), is this enough to need the `requiresCustomScript` flag to be true? 

Thank you for any clarification!

**Comment by Jerry0527** [comment]
"requiresCustomScript" is a setting in SharePoint Online Admin Center.
 If true, the component can only be installed on sites where Custom Script is allowed, please check out this official document for details:

[https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script?redirectSourcePath=%252fen-us%252farticle%252fTurn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f](Allow or prevent custom script)

And the CustomScript stand for JavaScript code not CSS.

If want to reference CSS in the web part, just follow this demo:

[https://www.c-sharpcorner.com/article/how-to-add-custom-css-file-in-sharepoint-framework-spfx-projects-and-refer-in/](How To Add Custom CSS File In SharePoint Framework Projects And Reference It In Your Component)

**Comment by trey-miller** [comment]
Thanks Jerry. This doesn't quite address my question except this statement of yours: "And the CustomScript stands for JavaScript code not CSS." I think this means I'm OK doing this, but just to clarify:

Imagine I have developed a web part with a string property in its properties, and in the property pane, I put a text field for this property. The user of the web part writes CSS code in the text field and saves the web part. Then the web part, in its render() function, takes that CSS code and injects it into the page in a style block. Does this web part need to have `"requiresCustomScript": true` in its web part manifest? 

I know if I allowed a user to input arbitrary JavaScript in a text field in the web part's properties, and then the web part injected that code into a script block in the page, it would definitely need the `"requiresCustomScript": true` in its web part manifest. I'm just wondering if exposing custom CSS alone is enough to require this value.

**Comment by kmprasad4u** [comment]
"requiresCustomScript" should be set to true, if you want your webpart to be visible (to be picked from add Webpart) to only the sites which allows adding custom script. 

SPFx Framework doesn't know how you are getting the css/html and injecting into the DOM. Its upto you to decide whether you want to allow the users to inject something in the page.
