### ISSUE TITLE
Date coulmn condtional formating

### ISSUE THREAD

**Issue by ushroff79** [SharePoint/sp-dev-docs#4932]
Using below code i have checking coulmn value is less than,grater than and equal to todaty's but it is not working.First two condtion works but when i put equal condtion all coulmn going white
{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
   "elmType": "div",
   "txtContent": "@currentField",
   "style": {
      "color": "=if(@now < [$Agreed], '#ff0000',if(@now > [$Agreed],'#2552cf',if(@now > [$Agreed],'#2552cf', '#3fdaeb')))"
   }

**Comment by OS-Lee** [comment]
Try to use toLocaleDateString function to convert the date.

[Official document](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)

`if(toLocaleDateString(@now) == toLocaleDateString([$AgreedTrainingDate]),'green', 'orange')`

**Comment by ushroff79** [comment]
Thank you so much for quick response.I t working but is not coming like below
![image](https://user-images.githubusercontent.com/37068621/69339274-f98cdd00-0c8a-11ea-95f9-ed35862cd413.png)

**Comment by OS-Lee** [comment]
Suppose you want background color:

`{ "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json", "elmType": "div", "txtContent": "@currentField", "style": { "background-color": "=if(Date(@now) < [$AgreedTrainingDate], '#ff0000',if(Date(toLocaleDateString(@now)) > Date(toLocaleDateString([$AgreedTrainingDate])),'#2552cf',if(toLocaleDateString(@now) == toLocaleDateString([$AgreedTrainingDate]),'#3fdaeb', 'orange')))" } }`

**Comment by ushroff79** [comment]
Thank you so much for your help .It's working now.
