### ISSUE TITLE
There are multiple modules with names that only differ in casing. ./node_modules/fbjs/lib/setImmediate.js

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#4934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nsksaisaravana/SPFX-Ant-Design](https://github.com/nsksaisaravana/SPFX-Ant-Design)

### Steps to reproduce
1. gulp serve
2. check the console and see the errors related to the title

### What is expected?
no error on webpack building

### What is actually happening?
webpack is giving the error

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.8.3 |
| System | Windows |
| Browser | Google chrome |

![image](https://user-images.githubusercontent.com/17681573/69406006-29a0b280-0d55-11ea-8f2f-30c869117632.png)

**Comment by Dennis-LZ** [comment]
Check the steps below.
1.Download the solution from here: [https://github.com/nsksaisaravana/SPFX-Ant-Design](https://github.com/nsksaisaravana/SPFX-Ant-Design)
2.Open Node.js command prompt(Run as administrator).
3.Go to the folder "SPFX-Ant-Design-master"(example: "cd C:\Program Files\nodejs\SPFX-Ant-Design-master").
4.Run npm install.
5.Run gulp serve
![Capture](https://user-images.githubusercontent.com/55479607/69416102-d3317500-0d50-11ea-965e-67cbfde9388a.PNG)

If still not works, please check your SharePoint framework development environment follow the article below.
[Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by nsksaisaravana** [comment]
@Dennis-LZ please check your console, you will find those above-mentioned errors. In development everything works fine but when you will not able to release it to the production due to those errors. 

https://github.com/facebook/fbjs/issues/234 Please check this issue, they recommended some solutions but I don't know how to do it in the spfx environment.

**Comment by nsksaisaravana** [comment]
@AJIXuMuK resolved this by importing _import Button  from 'antd/es/button_'; thanks @AJIXuMuK

**Comment by Dennis-LZ** [comment]
> @AJIXuMuK resolved this by importing _import Button from 'antd/es/button_'; thanks @AJIXuMuK

Glad to hear that you solve this issue, thanks for your sharing.

**Dennis Guo
Microsoft SharePoint Community Support**
