### ISSUE TITLE
Regarding "URL and hosting restrictions for production remote event receivers"

### ISSUE THREAD

**Issue by aparnackeshav** [SharePoint/sp-dev-docs#4935]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

As per the article  https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-remote-event-receiver-in-sharepoint-add-ins, the following is mentioned:
If you are using HTTPS and the receiver service is hosted on-premises, but the add-in is on SharePoint Online, the hosting server must have a publicly trusted certificate from a certificate authority.

So does that mean that Sharepoint Online add-ins can only access public facing receiver service hosted on-premises?

Regards,
Aparna

#### Observed Behavior
I tried with a https receiver service hosted on-premises which is not exposed to the internet. This service was never called when an item was added to the SharePoint online list.

**Comment by aparnackeshav** [comment]
Any updates on this?

**Comment by andrewconnell** [comment]
The service must be accessible from SPO so yes, you must have a legit SSL cert on the service & it must be exposed to the internet. Otherwise, there's no way for SPO to (1) reach the service or (2) establish a secure handshake as it can't trust the cert.
