### ISSUE TITLE
List data validation failed on list without validation

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4938]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Sending a request to update an item succeeds, since none of the columns have a validation formula and none of the columns are required.

#### Observed Behavior

The server responds with `500: List data validation failed.`. None of the columns on the list have any form of validation. This only occurs using the REST API - creating a completely blank item from the modern list view succeeds, as does updating it. 

#### Steps to Reproduce

I don't know. I've only had this on one tenant ever. Here's the request that's going out:

![image](https://user-images.githubusercontent.com/5057870/69440385-a70df800-0d40-11ea-9eac-91dd7f54e611.png)

And the response:

![image](https://user-images.githubusercontent.com/5057870/69440424-bc832200-0d40-11ea-9aef-60f944b6e7ec.png)

The column was a number column with `1` and `2` in it. I have converted the column to a single line of text **with no validation**. The first 15 items succeeded without a problem.

![image](https://user-images.githubusercontent.com/5057870/69440732-416e3b80-0d41-11ea-86d9-ae2b3bd5cc45.png)
![image](https://user-images.githubusercontent.com/5057870/69440754-4b903a00-0d41-11ea-8377-259cd1b6178d.png)

<details><summary>I have also included the small script I am running (requests are formed using a global @pnp/sp instance)</summary>

```js
/*
Updates values in a column by mapping them from
one value to another.

Uses the existing value if it does not exist in the map.
*/

LIST_TITLE = "CC_GeneralLeasing";
COL = "Owned_x0020_or_x0020_Leased";

MAP = {
  1: "Owned",
  2: "Leased"
};

/* ============== */

(async () => {
  const items = await sp.web.lists
    .getByTitle(LIST_TITLE)
    .items.select("Id", COL)
    .top(10000)
    .get();

  let i = 0;
  for (let item of items) {
    console.log(`${i + 1}/${items.length}`);

    if(item[COL] in MAP) {
      await sp.web.lists
      .getByTitle(LIST_TITLE)
      .items.getById(item.Id)
      .update({ [COL]: MAP[item[COL]] });
    }

    i++;
  }
})();

```
</details>

---

I appreciate this isn't an awful lot to go by so let me know if you need anything more. Also is this the best place for issues like this - we have tried raising Office365 tickets before to be told they do not support development issues.

**Comment by JakeStanger** [comment]
It seems that a column elsewhere was a choice column and the value in the column was not one of the choices. Choice columns never used to validate server-side so this is very new.

I would like to request better handling and error messages with this - updating one field shouldn't fail with a vague error on the basis that another unknown column now doesn't meet unannounced new criteria.

**Comment by andrewconnell** [comment]
Technically things are working by design... it's a fair request, but that would fall in the category of a change/feature so it belongs on user voice
