### ISSUE TITLE
Cannot read property 'pageX' of undefined

### ISSUE THREAD

**Issue by BenGWeeks** [SharePoint/sp-dev-docs#494]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Would expect deployed code to work as per workbench (where I do not see this issue).

Is there any particular reason why the event within a SharePoint context would not have a pageX?

#### Observed Behavior

I am seeing the following error when running the froala editor within a SharePoint (SPFx) context:

> core.umd.js:3064 EXCEPTION: Cannot read property 'pageX' of undefined
> ErrorHandler.handleError @ core.umd.js:3064
> next @ core.umd.js:8041
> schedulerFn @ core.umd.js:3689
> SafeSubscriber.__tryOrUnsub @ Subscriber.ts:250
> SafeSubscriber.next @ Subscriber.ts:202
> Subscriber._next @ Subscriber.ts:135
> Subscriber.next @ Subscriber.ts:95
> Subject.next @ Subject.ts:61
> EventEmitter.emit @ core.umd.js:3675
> NgZone.triggerError @ core.umd.js:4040
> onHandleError @ core.umd.js:4001
> ZoneDelegate.handleError @ zone.js:334
> Zone.runTask @ zone.js:169
> ZoneTask.invoke @ zone.js:416
> data.args.(anonymous function) @ zone.js:1527
> arguments.(anonymous function) @ init.js:1

> core.umd.js:3069 ORIGINAL STACKTRACE:
> ErrorHandler.handleError @ core.umd.js:3069
> next @ core.umd.js:8041
> schedulerFn @ core.umd.js:3689
> SafeSubscriber.__tryOrUnsub @ Subscriber.ts:250
> SafeSubscriber.next @ Subscriber.ts:202
> Subscriber._next @ Subscriber.ts:135
> Subscriber.next @ Subscriber.ts:95
> Subject.next @ Subject.ts:61
> EventEmitter.emit @ core.umd.js:3675
> NgZone.triggerError @ core.umd.js:4040
> onHandleError @ core.umd.js:4001
> ZoneDelegate.handleError @ zone.js:334
> Zone.runTask @ zone.js:169
> ZoneTask.invoke @ zone.js:416
> data.args.(anonymous function) @ zone.js:1527
> arguments.(anonymous function) @ init.js:1

> core.umd.js:3070 TypeError: Cannot read property 'pageX' of undefined
>     at i (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:149:3933), <anonymous>:17:5549)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:363:31)
>     at Object.onInvokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:18:48), <anonymous>:3971:41)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:362:36)
>     at Zone.runTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:166:47)
>     at ZoneTask.invoke (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:416:38)
>     at data.args.(anonymous function) (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:1527:25)
>     at arguments.(anonymous function) (https://static.sharepointonline.com/bld/_layouts/15/16.0.6309.1206/init.js:1:95300)
> ErrorHandler.handleError @ core.umd.js:3070
> next @ core.umd.js:8041
> schedulerFn @ core.umd.js:3689
> SafeSubscriber.__tryOrUnsub @ Subscriber.ts:250
> SafeSubscriber.next @ Subscriber.ts:202
> Subscriber._next @ Subscriber.ts:135
> Subscriber.next @ Subscriber.ts:95
> Subject.next @ Subject.ts:61
> EventEmitter.emit @ core.umd.js:3675
> NgZone.triggerError @ core.umd.js:4040
> onHandleError @ core.umd.js:4001
> ZoneDelegate.handleError @ zone.js:334
> Zone.runTask @ zone.js:169
> ZoneTask.invoke @ zone.js:416
> data.args.(anonymous function) @ zone.js:1527
> arguments.(anonymous function) @ init.js:1

> Subscriber.ts:253 Uncaught TypeError: Cannot read property 'pageX' of undefined
>     at i (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:149:3933), <anonymous>:17:5549)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:363:31)
>     at Object.onInvokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:18:48), <anonymous>:3971:41)
>     at ZoneDelegate.invokeTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:362:36)
>     at Zone.runTask (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:166:47)
>     at ZoneTask.invoke (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:416:38)
>     at data.args.(anonymous function) (eval at <anonymous> (https://????.sharepoint.com/sites/Development/SiteAssets/????/requirements-form.bundle_849135b793670aa75ed843f6802f94d7.js:2:14506), <anonymous>:1527:25)
>     at arguments.(anonymous function) (https://static.sharepointonline.com/bld/_layouts/15/16.0.6309.1206/init.js:1:95300)
**> i @ froala_editor.pkgd.min.js:17**
> ZoneDelegate.invokeTask @ zone.js:363
> onInvokeTask @ core.umd.js:3971
> ZoneDelegate.invokeTask @ zone.js:362
> Zone.runTask @ zone.js:166
> ZoneTask.invoke @ zone.js:416
> data.args.(anonymous function) @ zone.js:1527
> arguments.(anonymous function) @ init.js:1

#### Steps to Reproduce
This is angular 2 (with Froala) embedded into a SPFx web part.

**Comment by webtechy** [comment]
Possibly related:

http://stackoverflow.com/questions/8583249/jquery-1-7-clientx-pagex-undefined

http://blah.winsmarts.com/2013-5-SharePoint_2013_-_JavaScript_-and-amp;_jQuery_big_booboo_to_watch_out_for.aspx

**Comment by AJIXuMuK** [comment]
Hello @BenGWeeks - sorry for the really long delay.
Is that still an issue? If yes - could you provide a simple repro example?

Thanks
