### ISSUE TITLE
Column Header Size

### ISSUE THREAD

**Issue by einue** [SharePoint/sp-dev-docs#4942]
Hi, how can I set the size of the text in the header line of my list view via json?

**Comment by Dennis-LZ** [comment]
You can check the official document here: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting).

Unfortunately, there is not a way to customize the column header of list view using JSON formatting.

As a workaround, we can use SPFx Applications Customiser to inject the custom CSS style to achieve it.

The CSS style as below:
```
.ms-DetailsList-headerWrapper .ms-DetailsHeader-cell{
	font-size:18px !important;
}
```

The SPFx solution is here: [SPFx Applications Customiser CSS Injection](https://github.com/hugoabernier/react-application-injectcss)

![Untitled](https://user-images.githubusercontent.com/55479607/69592261-5e9c5600-1030-11ea-9aeb-9f75a8e740c1.png)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by andrewconnell** [comment]
I caution the use of the workaround listed above... that is definitely not supported & falls under the "DOM manipulation" category as it relies on CSS classes that are subject to change.
