### ISSUE TITLE
Double top and bottom extension placeholders on search pages causes extension issues

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#4945]
## Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

On some search pages, we started to notice strange behavior with the top and bottom extension placeholders. Normally only one of both is available on a page, but on search pages, we see two of them. This sometimes causes issues where the extension gets loaded.

#### Observed Behavior

![Screenshot 2019-11-25 10 49 11](https://user-images.githubusercontent.com/2900833/69529995-985a5780-0f71-11ea-9222-3ff80135cde8.png)

#### Steps to Reproduce

- Go to: `/_layouts/15/search.aspx/siteall?q=test` 
- Check the bottom and top placeholders

**Comment by ahessami** [comment]
I'm experiencing the same issue.  On the search page (ex: _layouts/15/search.aspx/siteall?q=pdf), there are two of each Top and Bottom placeholders.  This is causing the page to have to vertical scrolls and then a gap at the bottom of the page where the bottom placeholder should be flush with the window.

![image](https://user-images.githubusercontent.com/3638514/70101572-f8e53680-15fa-11ea-9aad-0be6678cfe85.png)

**Comment by andrewconnell** [comment]
Noticing the same thing... odd...

**Comment by kemesfun** [comment]
@estruyf  I am not able to reproduce this following your steps. Can you give a more descriptive repro step if it still repros?

**Comment by corriespondent** [comment]
I was about to post an issue and found this one! We are experiencing the same thing. This seems to be a recent change.

My steps for repro:

1. Go to a site which uses an application customizer to render a custom header/footer (note - I have only tested this on sites that have the extension applied across the entire tenant)
2. Run a search in the SharePoint search bar. (This issue happens in tenants that have the global O365 search bar as well as on sites which do not yet have the O365 search bar and only have a search bar in the OOTB header area.)
3. The search page renders as shown in the screenshots below:

Double scrollbar on the right:
![image](https://user-images.githubusercontent.com/23064475/77552586-f5f3a780-6e70-11ea-87b1-997d133897d2.png)

Scrolling down in the internal frame means that the results are cut off at the bottom:
![image](https://user-images.githubusercontent.com/23064475/77552726-220f2880-6e71-11ea-930a-439652378cb0.png)

Scrolling down in the external frame reveals an issue with the placeholders:
![image](https://user-images.githubusercontent.com/23064475/77552817-3f43f700-6e71-11ea-8c35-ec374b8ebc42.png)

Inspecting the code reveals that the search page seems to have double top and bottom placeholders:
![image](https://user-images.githubusercontent.com/23064475/77552925-639fd380-6e71-11ea-8e8e-38cf50e7b424.png)

**Comment by corriespondent** [comment]
P.S. Maybe not so recent - I can't recall if we tested the OOTB search page in this way before for our projects. I did come across a comment in January describing the same issue: https://github.com/SharePoint/sp-dev-docs/issues/1922

**Comment by corriespondent** [comment]
My temporary hacky fix is to add this to my extension CSS:
(Inside :global)

SECTION.mainContent DIV[class^=searchResultsContainer] { min-height: 0 !important; }

**Comment by kemesfun** [comment]
@estruyf A fix for the scrollbar issue has been added and will part of the next rollout.

**Comment by netti01** [comment]
@estruyf guided me to this issue. 

We are experiencing the same but not only on the search pages. Please have a look at #6253.
Since a few weeks this also happens on inline navigation between a page and a library.

**Comment by AJIXuMuK** [comment]
I can't repro this one. Is that still an issue for anyone?

**Comment by corriespondent** [comment]
I believe this was resolved last year @AJIXuMuK! :-) Our tenant is good.
