### ISSUE TITLE
When sorting view Descending on Modified the Column Formatting disappears

### ISSUE THREAD

**Issue by m3ngi3** [SharePoint/sp-dev-docs#4946]
When sorting on Name column the JSON of the formatting code works fine, when changing to other sorting order like Modified column the column format (using Fabric icons) disappears / shows blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
@m3ngi3 I couldn't repro this locally. Can you please share the JSON that is failing when Modified column is sorted?

**Comment by m3ngi3** [comment]
Thank you for checking in @shagra-ms !
So when sorting Ascending on Name with link & menu = 
![pvmFormattingOKViewAscendingNameLinkMenu](https://user-images.githubusercontent.com/47530580/73337954-c2800c80-4275-11ea-865f-55e5a54c4242.png)

When changing to Descending on Modified (and a bunch of other columns) = 
![pvmFormattingNotOKViewDescendingModified](https://user-images.githubusercontent.com/47530580/73337966-c7dd5700-4275-11ea-9587-04c300fbef32.png)

JSON =
`{
  "elmType": "div",
  "children": [
    {
      "elmType": "div",
      "children": [
        {
          "elmType": "span",
          "style": {
            "padding-right": "5px",
            "padding-left": "0px",
            "display": "block"
          },
          "txtContent": {
            "operator": "?",
            "operands": [
              {
                "operator": "==",
                "operands": [
                  "@currentField",
                  ""
                ]
              },
              "=if([$ContentType]=='Folder','Folders not editable',if([$ContentType]=='Contract'&&[$CMgtContractId]=='','No contract actions possible yet',if([$ContentType]=='Contract','',''))",
              ""
            ]
          }
        },
        {
          "elmType": "div",
          "style": {
            "float": "left",
            "padding-right": "0px",
            "padding-left": "0px",
            "display": "block"
          },
          "children": [
            {
              "elmType": "button",
              "customRowAction": {
                "action": "defaultClick"
              },
              "attributes": {
                "class": "ms-fontColor-themePrimary ms-fontColor-themeDark--hover",
                "title": "Check it out!"
              },
              "style": {
                "border": "none",
                "background-color": "transparent",
                "cursor": "pointer",
                "font-size": "25px",
                "color": "=if([$ContentType]=='Folder','transparent','#E4051F')"
              },
              "children": [
                {
                  "elmType": "span",
                  "Style": {
                    "padding-right": "0px",
                    "padding-left": "0px"
                  },
                  "attributes": {
                    "iconName": "Play"
                  }
                }
              ]
            }
          ]
        },
        {
          "elmType": "div",
          "style": {
            "float": "left",
            "padding-right": "0px",
            "padding-left": "0px",
            "display": "block"
          },
          "children": [
            {
              "elmType": "button",
              "customRowAction": {
                "action": "editProps"
              },
              "attributes": {
                "class": "ms-fontColor-themePrimary ms-fontColor-themeDark--hover",
                "title": "=if([$ContentType]=='Folder','','Edit properties')"
              },
              "style": {
                "border": "none",
                "background-color": "transparent",
                "cursor": "pointer",
                "font-size": "25px",
                "color": "=if([$ContentType]=='Folder','transparent','#E4051F')"
              },
              "children": [
                {
                  "elmType": "span",
                  "Style": {
                    "padding-right": "0px",
                    "padding-left": "0px"
                  },
                  "attributes": {
                    "iconName": "Edit"
                  }
                }
              ]
            }
          ]
        },
        {
          "elmType": "div",
          "style": {
            "float": "left",
            "padding-right": "0px",
            "padding-left": "0px",
            "display": "block",
            "color": "=if([$CMgtContractId]=='','transparent','#E4051F')"
          },
          "children": [
            {
              "elmType": "a",
              "style": {
                "padding-right": "5px",
                "padding-left": "0px",
                "font-size": "25px",
                "text-decoration": "none",
                "color": "=if([$CMgtContractId]=='','transparent','#E4051F')"
              },
              "attributes": {
                "iconName": {
                  "operator": "?",
                  "operands": [
                    {
                      "operator": "<",
                      "operands": [
                        "[$CMgtContractId]",
                        "1"
                      ]
                    },
                    "BufferTimeBefore",
                    "DocumentSearch"
                  ]
                },
                "title": "=if([$CMgtContractId]=='','No info yet','See more related information')",
                "target": "=if([$CMgtContractId]=='','','_blank')",
                "href": {
                  "operator": "?",
                  "operands": [
                    {
                      "operator": "<",
                      "operands": [
                        "[$CMgtContractId]",
                        "1"
                      ]
                    },
                    {
                      "operator": "+",
                      "operands": [
                        "",
                        ""
                      ]
                    },
                    "=if([$ContentType]=='Contract'&&[$CMgtContractId]=='','','/sites/global-contracts/SitePages/Search-Contracts.aspx?ContractID='+[$CMgtContractId]+'&HolderName='+[$CMgtHolder]+'&FolderName='+[$LinkFilename])"
                  ]
                }
              }
            },
            {
              "elmType": "a",
              "style": {
                "padding-top": "3px",
                "padding-right": "0px",
                "padding-left": "0px",
                "font-size": "25px",
                "text-decoration": "none",
                "color": "=if([$CMgtContractId]=='','transparent',if([$ContentType]=='Contract','#E4051F','transparent'))"
              },
              "attributes": {
                "iconName": {
                  "operator": "?",
                  "operands": [
                    {
                      "operator": "<",
                      "operands": [
                        "[$CMgtContractId]",
                        "1"
                      ]
                    },
                    "BufferTimeBefore",
                    "NewFolder"
                  ]
                },
                "title": "=if([$ContentType]=='Contract'&&[$CMgtContractId]=='','No Sub contract possible yet',if([$ContentType]=='Contract','Add new Sub contract','No Sub contract possible'))",
                "target": "=if([$ContentType]=='Contract'&&[$CMgtContractId]=='','',if([$ContentType]=='Contract','_blank',''))",
                "href": {
                  "operator": "?",
                  "operands": [
                    {
                      "operator": "<",
                      "operands": [
                        "[$CMgtContractId]",
                        "1"
                      ]
                    },
                    {
                      "operator": "+",
                      "operands": [
                        "",
                        ""
                      ]
                    },
                    "=if([$ContentType]=='Contract'&&[$CMgtContractId]=='','',if([$ContentType]=='Contract','https://apps.powerapps.com/play/8444e4b8-db25-4282-8f2f-050056fb5bd3?tenantId=492abf3a-00ce-4b06-9273-66fef44e5548?ParamCTRID='+[$CMgtContractId],''))"
                  ]
                }
              }
            },
            {
              "elmType": "span",
              "style": {
                "padding-right": "0px",
                "padding-left": "0px"
              },
              "txtContent": "\n"
            },
            {
              "elmType": "span",
              "style": {
                "padding-right": "0px",
                "padding-left": "0px"
              },
              "txtContent": {
                "operator": "?",
                "operands": [
                  {
                    "operator": "<",
                    "operands": [
                      "@currentField",
                      "1"
                    ]
                  },
                  "",
                  ""
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by shagra-ms** [comment]
Thanks @m3ngi3 for sharing the JSON. Can't see any issues with the JSON.

To investigate this a bit more, please share more info - 
1. Can you add [debugMode](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#debugmode) flag in the JSON and check if there is any error?
2. Can you share the field type for the columns referred in the JSON?
3. Can you confirm that only [supported column types](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#supported-column-types) are present in the View?

**Comment by shagra-ms** [comment]
@m3ngi3 I am looking forward for your reply to help you resolve the issue.

**Comment by m3ngi3** [comment]
Hi @shagra-ms ,
I can also not reproduce this in "fresh" libraries in the same tenant so I'm starting to think migrating the library with ShareGate may be part of the cause? 
Because the screenshots clearly show working formatting and not working formatting with the only difference in the sorting of certain columns (showing same columns in the view, same JSON code etc), I will check on your requests coming week when I have access to that specific tenant again 👍

**Comment by shagra-ms** [comment]
@m3ngi3 Were you able to check on my requests?

**Comment by m3ngi3** [comment]
Sorry @shagra-ms! I had to proceed with creating new lists / libraries not migrated from ShareGate as the same formatting codes would then work successfully. So this would confirm that I only used supported columns right... otherwise the same code would not work on the fresh lists.

If I ever run to into this again, I can provide additional data with debug mode enabled.

**Comment by shagra-ms** [comment]
Thanks @m3ngi3. I will close the issue. Please do let me know if you run into this issue again.
