### ISSUE TITLE
A vs. an: Usage Guide

### ISSUE THREAD

**Issue by Cyclogrammer** [SharePoint/sp-dev-docs#4947]
In speech and writing a is used before a consonant sound. a door a human Before a vowel sound an is usual an icicle an honor but especially in speech a is used occasionally, more often in some dialects than in others. a apple a hour a obligation Before a consonant sound represented by a vowel letter a is usual a one a union but an also occurs though less frequently now than formerly. an unique  such an one  Before unstressed or weakly stressed syllables with initial h both a and an are used in writing. a historic an historic In the King James Version of the Old Testament and occasionally in writing and speech an is used before h in a stressed syllable. an huntress an hundred  children are an heritage of the Lord  — Psalms 127:3 (King James Version)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint#feedback)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Closed as an unclear comment.
