### ISSUE TITLE
All SharePoint styles should exist in workbench

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#495]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I would expect my components to be having matching styles in the workbench to the actual deployed versions. However, there are a couple of discrepancies.

#### Observed Behavior
Styles of buttons (for example) vary between workbench and production.

#### Steps to Reproduce
Create a <button> that does not have a min-width set, but is smaller than 6em. In production, there in _catalogs/theme/Themed/AC81EBEB/corev15-51C31438.themedcss?ctag=2:

```
input[type=button], input[type=reset], input[type=submit], button {
  min-width: 6em;
}
```

Which I have to override, which I wouldn't mind if I could at least be aware of the issue in the workbench.

**Comment by StfBauer** [comment]
The workbench and SPFx targets toward the new experience not the classic experience. Especially in your case you have a classical custom theme. This should be treated like a third party CSS.

[Reference third party CSS in SPFx](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/reference-third-party-css-styles)

You can also reference through SPModuleLoader.

```
// target to your theme and URL.
SPComponentLoader.loadCss('https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css');
```

**Comment by webtechy** [comment]
But functionally it is [still] possible to add a web part to a classic page ...

**Comment by StfBauer** [comment]
Yes but most of the style sheet classes doesn't exist in the modern experience anymore because it is built on Office UI Fabric.
So the code then needs to be rewritten to match the modern experience.

**Comment by amishra0909** [comment]
As @StfBauer pointed out, your classic custom CSS should be treated as third party CSS to make it work on SPFx.
Closing this issue.
