### ISSUE TITLE
https://your-sharepoint-tenant.sharepoint.com/_layouts/workbench.aspx--site can't be reached

### ISSUE THREAD

**Issue by shyambeer** [SharePoint/sp-dev-docs#4950]
- [x ] Question not able to access the page: https://your-sharepoint-tenant.sharepoint.com/_layouts/workbench.aspx 

Error message: This site can’t be reachedyour-sharepoint-tenant.sharepoint.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

I've followed all the steps mentioned on-- https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part
I've installed the dev certificate  using the command: gulp trust-dev-cert
Still not able to open the page: 

The workbench: https://localhost:4321/temp/workbench.html is working fine.

**Comment by Jerry0527** [comment]
Please checkout if you have enter the valid tenant url in .vscode/launch.json like below:

![Untitled](https://user-images.githubusercontent.com/28797671/69612100-0d10bd00-106a-11ea-8984-55d0bb485643.png)
