### ISSUE TITLE
debugLocale not allowed

### ISSUE THREAD

**Issue by JBorras-summar** [SharePoint/sp-dev-docs#4951]
When setting "debugLocale" in manifest.json compiler says it's not allowed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33394188-10be-0875-025d-9ffff6618df9
* Version Independent ID: ca9875f8-4f6a-21d3-8483-66ced7c2d55c
* Content: [Localize SharePoint Framework client-side web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts#feedback)
* Content Source: [docs/spfx/web-parts/guidance/localize-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/localize-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not sure why that's in the docs as that's not a valid option on the **write-manifest.json** file (look at the schema linked in the file for everything that is allowed).

To test, specify the locale to serve upon the local workbench like this:

**gulp serve --locale=fr-ca**

Will get this fixed in the docs...

**Comment by cwdata** [comment]
@andrewconnell,
AFAIK the locale option on the command line doesn't work either. You now have to use **buildSingleLocale** in the write-manifest.json. For reference see issue #3248.

**Comment by andrewconnell** [comment]
@cwdata said:
> AFAIK the locale option on the command line doesn't work either

It does work... I tested it before I wrote the above comment.

As for the `buildSingleLocale`, [yes that is an option](https://developer.microsoft.com/json-schemas/spfx-build/write-manifests.schema.json) within the **write-manifest.json** file if you want to limit the bundle creation to a specific locale. That's useful for packaging, but in testing, it has zero use as it's only used when bundling with the `--ship` or `-p` flag.

**Comment by bcameron1231** [comment]
@andrewconnell So can there be an action item to fix the documentation to remove debugLocale or update the documentation for clarity on the newer versions of SPFx that no longer support it?

**Comment by andrewconnell** [comment]
@bcameron1231 Correct... this is a doc bug. That's why I flagged this issue as a bug & assigned it to me to get fixed.

**Comment by bcameron1231** [comment]
Ah, I missed that :)

Thanks!!
