### ISSUE TITLE
Property pane always gets opened once Tab is reloaded.

### ISSUE THREAD

**Issue by muradhaider5** [SharePoint/sp-dev-docs#4954]
I am able to add an SPFx webpart as a 'tab application' in Microsoft Teams however, I am facing a strange issue with one of my tabs. Whenever the tab is reloaded (by clicking on the tab or 'Refresh' button), property pane gets opened. This is not happening with all of the tabs but just one particular tab. Is there some setting related to this in 'manifest.json' to prevent the property pane from getting opened on every reload, that i might be missing?
Any help is appreciated. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

 Property pane should be open just once while the tab is being added, on subsequent tab reloads it should not get opened.
#### Observed Behavior

 Property pane always gets opened once Tab is reloaded. Just to check, I have also added the same Webpart on a page in SharePoint as well where property pane doesn't get opened upon page refresh/reload.

**Comment by andrewconnell** [comment]
If the SPFx web part has settings to configure then they will be displayed when the tab is added, just like how a tab with a configuration option always shows it before adding the tab. But it shouldn't show every time. 

However, I can't replicate what you describe... works as expected from my POV: add the tab, settings appear, then they don't show again unless you select the **Settings** context menu from the tab.

Suggest recording a screencast and pasting the video as a comment to show what you're seeing...

**Comment by muradhaider5** [comment]
@andrewconnell Thanks for replying. One thing i missed here that i identified later was, this is always happening for the webparts that are configured to be hosted in an isolated domain. However, property pane for the wabparts with non-isolated domain, works fine for me as well.

**Comment by andrewconnell** [comment]
@muradhaider5 said:
> One thing i missed here that i identified later was, this is always happening for the webparts that are configured to be hosted in an isolated domain.

That's a known issue and as mentioned in https://github.com/SharePoint/sp-dev-docs/issues/4669#issuecomment-572788792, MSFT is working on it.
