### ISSUE TITLE
How to create custom lookup in modern pages #spfx  

### ISSUE THREAD

**Issue by AnoopNagappan** [SharePoint/sp-dev-docs#4956]
I would like to create a advanced lookup in modern pages..is it possible with SPFx field customizer?
or any other alternatives to achieve this

**Comment by andrewconnell** [comment]
_With the limited information, this won't be a complete answer..._ 

Field customizer is intended to be used to change the rendering of a cell within the display view of a list. It does not render on the display/new/edit forms.

If you are looking to do a custom form, the recommended solution is to use PowerApps.

You could do something like this with a web part and custom property pane.
