### ISSUE TITLE
Not Able to Add Member to Private Group using Graph API in SPFX

### ISSUE THREAD

**Issue by Prasadjoshigit** [SharePoint/sp-dev-docs#4960]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

We are trying to add an member to Private Office 365 Group as a member, Using 

**graph.groups.getById(groupid).members.add('https://graph.microsoft.com/v1.0/users/'+username)**

Its working fine for Public Groups but when we try it on Private group its give below error, Can anyone guide me?

 **Uncaught (in promise) Error: Error making HttpClient request in queryable [403] Forbidden ::> {
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "0e0c3141-97b1-4411-b004-66422c157647",
      "date": "2019-11-28T08:38:51"
    }
  }
}**
We have added below permissions

"webApiPermissionRequests": [
      {
      "resource": "Microsoft Graph",
      "scope": "Group.Read.All"
      },
      {  
        "resource": "Microsoft Graph",  
        "scope": "User.Read.All"  
    },
    {  
      "resource": "Microsoft Graph",  
      "scope": "Directory.Read.All"  
  },
  {  
    "resource": "Microsoft Graph",  
    "scope": "GroupMember.ReadWrite.All"  
},
{  
  "resource": "Microsoft Graph",  
  "scope": "Group.ReadWrite.All"  
},
{  
  "resource": "Microsoft Graph",  
  "scope": "Directory.ReadWrite.All"  
}
    ]

**Comment by anomepani** [comment]
Are you member or owners of private group?

Due to different permission model for public and private group you are experiencing 403 issue for private in whcih you are neither member nor owner in group

**Comment by andrewconnell** [comment]
This is a question for the Microsoft Graph API... this issue list is for SharePoint development topics. The problem here isn't with SharePoint, it's a permission question with Graph.

https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http
