### ISSUE TITLE
Risk of Infinite Loop

### ISSUE THREAD

**Issue by kenmoritest** [SharePoint/sp-dev-docs#4963]
For the people who would like to extend this implementation. 
The retry loop is risky as is. Recommendation is to add the following code to throw when in invalid state.

    while (retryAttempts &lt; retryCount)
    {
        try
        {
            if (!retry)
            {
                clientContext.ExecuteQuery();
                return;
            }
            else
            {
                // retry the previous request
                if (wrapper != null && wrapper.Value != null)
                {
                    clientContext.RetryQuery(wrapper.Value);
                    return;
                }
                // The following code should be added here...
                else
                {
                    throw new Exception("Invalid Retry State");
                }
            }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#feedback)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good suggestion... care you submit a PR?

**Comment by nanddeepn** [comment]
The fix is already in the MSDN

`// Do while retry attempt is less than retry count
    while (retryAttempts < retryCount)
    {
        try
        {
            if (!retry)
            {
                clientContext.ExecuteQuery();
                return;
            }
            else
            {
                //increment the retry count                
                retryAttempts++;
                
                // retry the previous request using wrapper
                if (wrapper != null && wrapper.Value != null)
                {
                    clientContext.RetryQuery(wrapper.Value);
                    return;
                } 
                // retry the previous request as normal
                else
                {
                    clientContext.ExecuteQuery();
                    return;
                }                
            }
        }`

**Comment by nanddeepn** [comment]
The fix is already in MSDN content source

`while (retryAttempts < retryCount)
    {
        try
        {
            if (!retry)
            {
                clientContext.ExecuteQuery();
                return;
            }
            else
            {
                //increment the retry count                
                retryAttempts++;
                
                //retry the previous request using wrapper
                if (wrapper != null && wrapper.Value != null)
                {
                    clientContext.RetryQuery(wrapper.Value);
                    return;
                } 
                // retry the previous request as normal
                else
                {
                    clientContext.ExecuteQuery();
                    return;
                }                
            }
        }`
