### ISSUE TITLE
Unit test error in SPFx web part on service scope class

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/sp-dev-docs#4964]
Hi Team,
I am working in SPFx using the default httpclient response. In that, I am using Service Scope to inject the service with DI concept. I am using the below code in componentDidMount method to connect to SharePoint site and am able to get the results.
`const commonListService = this.props.serviceScope.consume(
        CommonListServiceKey
      );
      commonListService
        .getChoiceFieldValues("User Registration", "UserRole")
        .then(choiceResults => {
          this.setState({ UserRoles: choiceResults });
        })
        .catch(error => console.log(error));`

For this component, I am writing unit testing using jest. I am using the below code in Webpart.test.tsx file.
`beforeEach(() => {
    componentDidMountSpy = sinon.spy(
      SpFxHttpClient.prototype,
      "componentDidMount"
    );
    reactComponent = mount(
      React.createElement(SpFxHttpClient, {
        description: description
      })
    );
  });`

`afterEach(() => {
    reactComponent.unmount();
    componentDidMountSpy.restore();
  });`

`it("<SpFxHttpClient /> should render the main DIV element", () => {
    expect(reactComponent.find("div.spFxHttpClient").length).toEqual(0);
  });`

`it("<SpFxHttpClient /> should render as a React component", () => {
    const component: SpFxHttpClient = reactComponent.instance() as SpFxHttpClient;
    expect(component).not.toBeNull();
  });`

`it("<SpFxHttpClient /> should have state initialized", () => {
    const state: ISpFxHttpClientState = reactComponent.state();
    expect(state.UserRoles).toBeNull();
  });`

`it("<SpFxHttpClient /> should have properties initialized", () => {
    const props: ISpFxHttpClientProps = reactComponent.props();
    expect(props.description).toEqual(description);
  });`

When I run the command npm test, I am getting the error as below.
\node_modules\@microsoft\sp-http\lib\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as HttpClient } from './httpClient/HttpClient';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token export

How to solve this and how to write the unit testing for service scope class? Please guide me.

I am calling the below method in componentDidMount(). But still it is referring service scope concept.
`private renderDropDownAsync(): void {
    if (
      Environment.type === EnvironmentType.SharePoint ||
      Environment.type === EnvironmentType.ClassicSharePoint
    ) {
      const commonListService = this.props.serviceScope.consume(
        CommonListServiceKey
      );
      commonListService
        .getChoiceFieldValues("User Registration", "UserRole")
        .then(choiceResults => {
          this.setState({ UserRoles: choiceResults });
        })
        .catch(error => console.log(error));
    } else if (Environment.type === EnvironmentType.Test) {
      const dropDownItems: Array<string> = [
        "Administrator",
        "Brand Manager",
        "Media Manager"
      ];
      const choiceResults: ListFieldChoiceData = ListDataUtil.castAsChoiceField(
        dropDownItems
      );
      this.setState({
        UserRoles: choiceResults
      });
    }
  }`

**Comment by andrewconnell** [comment]
Pretty advanced question :)

The problem you're likely running into is that service scopes are an SPFx concept and thus, they expect the SPFx runtime to be loaded and running on the page. You don't get that with Jest... Jest isn't loading the SPFx runtime.

I'd recommend you refactor the project so the component you're testing doesn't have any of the SPFx APIs in it and instead, you have an abstraction.
