### ISSUE TITLE
How to get the current selected item ID in the QuickLauch ? 

### ISSUE THREAD

**Issue by Versatile2** [SharePoint/sp-dev-docs#4969]
I'm currently developing a BreadCrumb in SPFX with React and i need to get the current id of the selected item in the  QuickLauch  menu. 

![Capture](https://user-images.githubusercontent.com/33726069/69973498-e21fe080-1523-11ea-8d31-427cfbe813b5.PNG)

I'm currently searching the item exploring the object in the context (context.pageContext.legacyPageContext.navigationInfo.quickLaunch) . 

Is there an other ways to get the current QuickLauch selected item id ?

**Comment by andrewconnell** [comment]
This is not exposed via an API. As such, there's no supported way to do this. When I say "supported", I mean anything you do would be inspecting the DOM & classes to get the selected item, and those are subject to change without notice.

**Comment by Versatile2** [comment]
Ok ok Thank you for the response
