### ISSUE TITLE
SharePoint Online Rest API FinishUpload method erroneously returns old file details

### ISSUE THREAD

**Issue by mcgeeky** [SharePoint/sp-dev-docs#4970]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using the SharePoint Online large file upload API (StartUpload, ContinueUpload and FinishUpload) after successfully calling the FinishUpload method the details of the file are returned by the method. We are expecting the updated file properties to be returned by this method (i.e. the new modified date, file version, file length). This is how it had been working for many months.

#### Observed Behavior

Over the past few days we have noticed that the FinishUpload method is now returning the old properties of the file. I.e. the properties of the file before the file had been uploaded.

E.g. if the file was 100 bytes in size before the upload, then after finalising the upload with FinishUpload, the results returned by FinishUpload still return 100 bytes instead of the new file size.

#### Steps to Reproduce

Create a new file of 100 bytes in a document library, say "myfile.txt". Use the large file upload API to overwrite the existing "myfile.txt" file but with 200 bytes of data. Examine the response of FinishUpload. For the length of the file it will show 100 bytes instead of the expected 200 bytes.

```
  <content type="application/xml">
    <m:properties>
      ...
      <d:Length m:type="Edm.Int64">100</d:Length>
      ...
    </m:properties>
  </content>
```

**Comment by andrewconnell** [comment]
Do you have a repro project showing this behavior? (Would help speed up the triage...)

**Comment by mcgeeky** [comment]
Hi Andrew,

Thanks for the response, and sure no problems here is the repro code below. Change the parts where indicated for your environment.

First create a new text file in the default document library of your root SharePoint Online site called ExitsingFile.txt of 10 bytes in length. Now run the code below using CSOM.

```
            //

            var context = [your code to get a SPO CSOM context];

            var fileServerRelativeUrl = "/Shared Documents/ExistingFile.txt";

            var file = context.Web.GetFileByServerRelativeUrl(fileServerRelativeUrl);

            context.Load(file, fl => fl.Length);

            context.ExecuteQuery();

            var fileLengthBeforeOverwrite = file.Length;

            Console.WriteLine("Current file length of '{0}' is '{1}'", fileServerRelativeUrl, fileLengthBeforeOverwrite);


            //

            var fileLengthExpectedAfterOverwrite = fileLengthBeforeOverwrite + 10;

            var bytes = new byte[fileLengthExpectedAfterOverwrite];

            Console.WriteLine("Expected file length after overwrite '{0}'", fileLengthExpectedAfterOverwrite);


            // start upload

            var stream = new MemoryStream();

            stream.Write(bytes, 0, bytes.Length);

            stream.Position = 0;

            var uploadId = Guid.NewGuid();

            var offset = file.StartUpload(uploadId, stream);

            context.ExecuteQuery();


            // finish upload

            stream = new MemoryStream(0);

            var updatedFile = file.FinishUpload(uploadId, offset.Value, stream);

            context.Load(updatedFile, fl => fl.Length);

            context.ExecuteQuery();


            //

            Console.WriteLine("file length returned by FinishUpload is '{0}' but should be '{1}'", updatedFile.Length, fileLengthExpectedAfterOverwrite);
```

**Comment by andrewconnell** [comment]
Been quite a while since I've dusted CSOM off (*first step: remember how to get a context*), & currently traveling without a Windows VM... I'll try to take a look at this when I return in a week+ unless someone else jumps on it first...

**Comment by mcgeeky** [comment]
Thanks Andrew. We would appreciate this being looked in to as soon as possible as it is affecting our customers. The behaviour of the FinishUpload method has changed unexpectedly which has now impacted our application.

**Comment by andrewconnell** [comment]
Understood, but please keep in mind this is a community-focused forum. Many from MSFT engineering monitor it, but many (_such as myself_) donate free time to help manage this issue list.

It's not official support. If you need urgent support, you should use Microsoft Premier Support.

**Comment by mcgeeky** [comment]
Hi Andrew. Your time dedicated to this as a non-Microsoft employee is much appreciated. Official support routes will reject issues relating to the SharePoint Online APIs. Ultimately we are directed to post issues here.

**Comment by mcgeeky** [comment]
Hi Andrew, If you don't have access to CSOM you can reproduce as follows just with the IE browser. Navigate to a SharePoint Online document in the browser. Create a new text file on your desktop with 10 bytes of data in it "TestFile.txt". Drag this file in to your browser window to upload it in to the document library. Edit "TestFile.txt" on your desktop so it has 20 bytes of data. Now hit F12 to open up the debug window in IE. Click the network tab to see the network activity. Drag and drop "TestFile.txt" from your desktop in to the browser window. After the overwrite and upload completes check the network activity for the FinishUpload method call. Click on the Body tab to see the response body. Locate the "Length" property in the request body. It will show 10 bytes, the previous size of the file, not 20 bytes which is the new size of the file.

**Comment by andrewconnell** [comment]
I don't have CSOM because I'm not on Windows, so no IE :)

**Comment by mcgeeky** [comment]
Hi Andrew, Thanks for investigating this. That's correct up until the last week or two, FinishUpload was returning the results of the new file version - which our application is expecting and working with for at least the past 2 years. Then unexpectedly the behaviour of FinishUpload has changed to return the old properties of the file which has then impacted our application.

**Comment by andrewconnell** [comment]
@JeremyKelley are you aware of any changes with the REST API lately that caused this change in behavior? 

Summary:
- Previously, the `FileUpload` method would return a `File` object where the `Length` = final filesize
- According to OP, within last ~2wks, this has changed... now `File.Length` returned = filesize of the version BEFORE the upload
- I confirmed here https://github.com/SharePoint/sp-dev-docs/issues/4970#issuecomment-562848263

**Comment by JeremyKelley** [comment]
I'm not aware of any changes but I've asked some people to take a look and make sure there isn't a problem.

**Comment by mcgeeky** [comment]
That's great thanks Jeremy.

**Comment by mcgeeky** [comment]
@JeremyKelley have your colleagues had a chance to look at this issue?

Thanks

**Comment by mcgeeky** [comment]
@JeremyKelley any news from your colleagues on this? @VesaJuvonen can you help with this?

The un-announced behaviour change has impacted our application. Its now been over a month since I logged this.

**Comment by mcgeeky** [comment]
@andrewconnell @JeremyKelley @VesaJuvonen Can anyone chime in on this issue? This un-announced API change ,with apparently no recourse with Microsoft afterwards, knocks confidence in the SharePoint Online API as a 3rd party developer. I can't image the Azure team changing APIs, let alone without communication.

**Comment by mcgeeky** [comment]
@andrewconnell @JeremyKelley @VesaJuvonen it appears the problematic behaviour has now been reverted back to how it was before? Can any of you verify this? The lack of communication from Microsoft is impacting us. We had to update our tool to cope with the broken behaviour of the upload API - but now apparently the upload API has been reverted back to the correct behaviour it has now affected our tool again.

**Comment by andrewconnell** [comment]
Good to hear it's fixed... I'll mark this issue as resolved then. I've passed along your feedback RE coms...

**Comment by mcgeeky** [comment]
Hi @andrewconnell that would be much appreciated if you can pass the feedback on, thank you.

It would be great if the team responsible for the large file upload API could comment here as we are in a quandary whether to update our application again - is this a temporary fix to the upload API or can we expect it to revert back to the incorrect behaviour?

**Comment by andrewconnell** [comment]
@mcgeeky I'd suggest posting your issue to this repo:
https://github.com/OneDrive/onedrive-api-docs/issues

My understanding (*trying to confirm for this & future issues*) that the team responsible for SP REST API specific issues are monitored in that repo. Make sure you cross-reference this issue for history...

**Comment by mcgeeky** [comment]
@andrewconnell if you could confirm that is the best place to post that would be great - I will then post my issue there for feedback.

Thanks!
