### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JannikMichel123** [SharePoint/sp-dev-docs#4971]
it would be nice if there was a code for testing included or maybe some remarks to testing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online?redirectedfrom=MSDN#feedback)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sorry, but not clear on your comment. Can you clarify?

**Comment by JannikMichel123** [comment]
Thanks for the response. So it would be nice if there where unit tests for the ExecuteQueryWithIncrementalRetry function or maybe a way to simulate a sharepoint that responds with 429. Maybe even a option in ClientContext to force SharePoint to respond with 429 like "Test429=true" for RESTApis.

**Comment by andrewconnell** [comment]
Actually you can... use exactly what you specify: `Test429=true` on the query string will simulate a 429 response. This works for SPO & OneDrive.

**Comment by JannikMichel123** [comment]
Could you please provide me with a caml query. I did not find anything on the Internet.
