### ISSUE TITLE
Use ESLint instead of TSLint

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#4972]
## Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

## Description
Is there a general guideline - if at all possible - on how to move to **ESLint** in SPFx?

TSLint is moving away from being a separate package to being integrated in ESLint. It would be nice for SPFx to move there as well, or at least to provide the option as a configuration.

Currently the TSLint task is part of the build process, so there doesn't seem to be an easy way as a developer to replace it.

Thanks.

**Comment by andrewconnell** [comment]
ATM you're correct... it's tightly coupled in the build process so there's not much you can do to remove it. You can add ESLint to the process if you want by creating a custom gulp command and attaching it before the build process, then remove TSLint rules so it effectively does nothing.

This would be done on a project-by-project basis.
