### ISSUE TITLE
Cannot navigate to Home page (SingleWebPartAppPage) from Events page

### ISSUE THREAD

**Issue by jyothsnag29** [SharePoint/sp-dev-docs#4975]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

By clicking on Site Logo or Site Title user should navigate to landing page of that site from anywhere within the site irrespective of the landing page PageLayoutType.

#### Observed Behavior

When we click on Site Logo or Site Title from /_layouts/15/Events.aspx page of that site, user is not able to redirect back to the landing page when its PageLayoutType is set to SingleWebPartAppPage. The page url gets changed from events page to home page but content doesn't load and we get to see blank page until we refresh the home page. However navigation works from other layout pages like viewlsts.aspx and settings.aspx. 
If we set the PageLayoutType to be Article then everything works as expected. 
 
![image](https://user-images.githubusercontent.com/43003891/70064145-540e2d80-15e9-11ea-8c0f-2dad23412d08.png)

Are there more people having this problem?

**Comment by andrewconnell** [comment]
Can you share some context? SPO?

**Comment by jyothsnag29** [comment]
We have observed this issue in SharePoint Online configured in Standard release.
Our SingleAppPage was developed using SPFx 1.8 version using React and the Office UI Fabric React version is 6.189.0
But we can reproduce the same issue using OOB Document library webpart.
### Steps to Reproduce ###

1. Create a test page by adding OOB Document library webpart in communication site.
![image](https://user-images.githubusercontent.com/43003891/70423381-a928c400-1a6d-11ea-9580-5ce4f381f895.png)
2. Make it home page.
3. Convert this page type to SingleAppPage using power shell script.
4. Navigate to /_layouts/15/Events.aspx and click on Site Logo or Title to navigate to Home page.
5. The page url gets changed to home page..but the content doesn't load.

**Comment by MRuimerman** [comment]
Any updates on this?

**Comment by kemesfun** [comment]
@jyothsnag29 I am able to reproduce this issue, but on an inconsistent bases. It seems like the workaround is to click on the List item or refresh the page.

**Comment by jyothsnag29** [comment]
We are still able to reproduce this issue.

**Comment by kemesfun** [comment]
@jyothsnag29 What is the error that you getting? The issue that I am reproing is 'Title is undefined', but this may have came from a change that was made to pages since it was an issue before, then it was solved, and know is back.

**Comment by MRuimerman** [comment]
We are getting this error: TypeError: Cannot read property 'Title' of undefined
