### ISSUE TITLE
Error - TypeError: this.log is not a function

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4979]
When adding `this.log` to custom subtasks I'm getting the error listed in the title.
v1.9.1 of SPFx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ea7187-d184-a7d7-bee8-eafffc5b2b47
* Version Independent ID: e34bb8a6-c90d-275d-57d9-840534ec46e4
* Content: [Integrate gulp tasks in SharePoint Framework toolchain](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline)
* Content Source: [docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Could you provide more details?

I did sample test in my local environment while can't reproduce.

`'use strict';

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');
build.addSuppression(`Warning - [sass] The local CSS class 'ms-Grid' is not camelCase and will not be type-safe.`);

let helloWorldSubtask = build.subTask('log-hello-world-subtask', function(gulp, buildOptions, done) {
    this.log('Hello, World!');   
    // use functions from gulp task here
    done();
  });

build.rig.addBuildTasks(helloWorldSubtask); 
build.initialize(gulp);
`

![image](https://user-images.githubusercontent.com/40845109/70218539-17c00600-177e-11ea-9984-03e6b88d8629.png)

Or

`const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');
build.addSuppression(`Warning - [sass] The local CSS class 'ms-Grid' is not camelCase and will not be type-safe.`);

let helloWorldSubtask = build.subTask('log-hello-world-subtask', function(gulp, buildOptions, done) {
    this.log('Hello, World!');   
    // use functions from gulp task here
    done();
  });

//build.rig.addBuildTasks(helloWorldSubtask); 
// Register the task with gulp command line
let helloWorldTask = build.task('hello-world', helloWorldSubtask);
build.initialize(gulp);`

![image](https://user-images.githubusercontent.com/40845109/70219136-4094cb00-177f-11ea-9c3e-9e81d71a1c56.png)

**Comment by AJIXuMuK** [comment]
Hi @OS-Lee,

Sorry, my bad in initial description. The project is on version 1.8.2.
The code:
```javascript
let updateVersionTask = build.subTask('update-version', (gulp, buildOptions, done) => {
    this.log('TEST');
    done();
});

build.rig.addPreBuildTask(updateVersionTask);
```

**Comment by OS-Lee** [comment]
Define the function as 

```
let updateVersionTask = build.subTask('update-version', function(gulp, buildOptions, done){    
    this.log('TEST');
    done();
});
```

will fix the error based on my testing.

**Lee
Microsoft SharePoint Community Support**

**Comment by AJIXuMuK** [comment]
Yep, arrow function replaces the context! Thanks!
