### ISSUE TITLE
SPFx List View command set is not working when user navigates between lists 

### ISSUE THREAD

**Issue by vijaybhanu** [SharePoint/sp-dev-docs#4980]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at https://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior
When user navigates between lists to view the different list view command sets by clicking on left navigation, should see the appropriate command sets. If user clicks on List1 using left navigation should see CS1 Command set, clicks on list2 should see CS2

#### Observed Behavior

First time click user is being able to see respective command sets **Ex:** List1 click able to see CS1 command set and List2 click able to see CS2. But when user clicks on lists from the left navigation second time without refreshing the page, not able to see the proper command set.

#### Steps to Reproduce

**Scenario1:**

- I have two lists say list1, list2 with different command sets cs1,cs2
- When I click on list 1 from left navigation it is showing cs1 command set
- Again when I click on list2 from left navigation it is showing cs2 command set
- Now I click on list 1 from left navigation, here it is not showing cs1 but showing cs2 command set

**Scenario2:**

- I have two lists say list1, list2 with different command sets cs1,cs2
- When I click on list 2 from left navigation it is showing cs2 command set
- Again when I click on list1 from left navigation it is showing cs1 command set
- Now I click on list 2 from left navigation, here it is not showing cs2 but showing cs1 command set
- Second time click it is not loading the proper command set but showing the previously loaded command set.

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by kemesfun** [comment]
@vijaybhanu I am not able to reproduce this issue. Let me know if the issue still occurs.
