### ISSUE TITLE
SPFx WebPart:  group/category of the WebPart

### ISSUE THREAD

**Issue by Laul0** [SharePoint/sp-dev-docs#4982]
### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Maybe the case was already opened but I didn't find it and sorry if this is the case.

The question is mostly to know if this use case will be available in the future or not?
Maybe it is already possible? I didn't find documentation about that.

#### Expected or Desired Behavior

When some additional WebParts are developed for a same purpose, by the same editor or with a specific category, that can be useful to group them in the same custom category visible from the WebPart picker in the Modern UI.

#### Observed Behavior

When your are developing several WebPart components, where are all available from the **Other** category on the WebPart picker.

![Screen Shot 2019-12-05 at 12 04 06](https://user-images.githubusercontent.com/15279205/70257489-5fcc3200-1758-11ea-937e-b57604544731.png)

Even if the groupId and goup "title" is modified, the WebPart still in the "Other" category.

```json
"preconfiguredEntries": [{
    "groupId": "Other GUID or Custom GUID",
    "group": { "default": "My Custom Group Name" },
    "title": { "default": "My custom WebPart title" },
    "description": { "default": "My Custom WebPart description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "Custom default property value"
    }
  }]
```

> I found the list of preconfigured category here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#predefined-modern-groups

#### Steps to Reproduce

- Once you were created a new SPFx WebPart, edit the `mysolution.manifest.json` file under **/src/webparts/mysolution** folder.
- Build the solution and deploy it to your Site collection app catalog ou Tenant catalog.
- Install the solution in your site collection (if you didn't have enable skip feature)
- Edit a page and add a WebPart via the WebPart Picker

Thank you by advance 😉

**Comment by OS-Lee** [comment]
I did sample test in my online environment while not reproduced.

Details:

![image](https://user-images.githubusercontent.com/40845109/70424218-faef3f80-1aa9-11ea-9f8e-0befb2b750cb.png)

![image](https://user-images.githubusercontent.com/40845109/70424273-12c6c380-1aaa-11ea-9690-f94fcb93fa07.png)

Package the solution and deploy to tenant app catalog /sites/appcatalog.

Add the solution to target site collection.

![image](https://user-images.githubusercontent.com/40845109/70424368-40137180-1aaa-11ea-8a22-6ae8afd79bcd.png)

Result.

![image](https://user-images.githubusercontent.com/40845109/70424379-47d31600-1aaa-11ea-984d-f65eb4b0c505.png)

If the solution is installed and you added new webpart to solution, add the app version to upgrade your solution, then you can upgrade in target site collection.

![image](https://user-images.githubusercontent.com/40845109/70424504-77821e00-1aaa-11ea-9c48-0745f4db74da.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by Laul0** [comment]
Thx for your answer @OS-Lee .
I will try again and try to deploy the app to the Tenant App Catalog rather than Site Collection.

**Comment by Laul0** [comment]
I tried again and that still not work !

- Deploy the SPPKG on the Tenant App Catalog.
- SPFx `1.9.1`
- Manifest:
<img width="477" alt="Screen Shot 2019-12-09 at 16 37 09" src="https://user-images.githubusercontent.com/15279205/70475357-5b7a7e80-1aa2-11ea-9ad9-4e0a8c4a6a64.png">

**Comment by OS-Lee** [comment]
The groupId(d17b0fb8-xxx) is not listed in official out-of-the-box groups.

![image](https://user-images.githubusercontent.com/40845109/70492492-967ebf80-1b3f-11ea-9b1b-bf9ff0d451f9.png)

**"If the developer fills an ID not in the previous list, the web part falls back to the Other group."**

**Lee
Microsoft SharePoint Community Support**

**Comment by Laul0** [comment]
Yes, I read all of this documentation and this is not my question currently. My question is: "Will it be possible to use custom groups/categories of WebPart in the future?"

Sorry if it was not clear

**Comment by andrewconnell** [comment]
At the moment that's not in the plan. Would fall as a feature request...
