### ISSUE TITLE
How to get hold of content above header (top area of the page)

### ISSUE THREAD

**Issue by Fnu-Avi** [SharePoint/sp-dev-docs#4985]
I'm trying to grab the class or id of the section above header of the page.

Link: [Image](https://imgur.com/a/SCSi0Kw)

Currently for the work around I've to use PlaceholderName.Top to grab the nearest tag and then I'm using position: absolute to mostly hide the sections.. But, this doesn't helps me alot. I need to do more than just hiding tags.

Is there a way I can get the control to that section?

Thanks & Regards,
Fnu Avi

Link: `https://imgur.com/a/SCSi0Kw`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions#feedback)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There is no supported way to do this. The top placeholder is the only customization option. What you are describing is DOM manipulation which is not supported.
