### ISSUE TITLE
Error is thrown while executing gulp trust-dev-cert command

### ISSUE THREAD

**Issue by anthony-git** [SharePoint/sp-dev-docs#4987]
am following the instructions from: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part
Error is thrown while executing gulp trust-dev-cert command.Tried with Node 8.11.4 as mentioned.
Even i tried deleting .gcb-serve-data folder but still i get the same error.

**Error - [trust-cert] TypeError: Cannot read property 'toString' of null
Error - 'trust-cert' sub task errored after 13 s
 Cannot read property 'toString' of null
Error - [trust-cert] TypeError: Cannot read property 'toString' of null
Error - 'trust-cert' sub task errored after 13 s
 Cannot read property 'toString' of null**

**Comment by andrewconnell** [comment]
Context please... what version of SPFx, what environment, etc...

**Comment by anthony-git** [comment]
SharePoint Environment - SharePoint online
Node.js - V8.11.4
gulp - 4.0.2
yeoman - 3.1.1

**Comment by Jerry0527** [comment]
This is a known issue for Node.js v8:
[gulp trust-dev-cert command not working for SharePoint Framework project creation ](https://github.com/SharePoint/sp-dev-docs/issues/1033)

Try to install Node.JS v10 as official document suggested, I tested in my local with Node.Js v10, it's working:

![Snipaste_2019-12-09_16-45-25](https://user-images.githubusercontent.com/28797671/70420736-4f42f100-1aa3-11ea-84cb-b87732269217.png)
