### ISSUE TITLE
Authenticating where MFA is enabled

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4989]
Username/password authentication is only possible on accounts where MFA is disabled. 

It is possible to authenticate through a custom Azure app registration using certificate authentication but this requires (as far as I can see) consenting full permission over all sites. 

Firstly, can something be added to the docs explaining about MFA authentication. Secondly, is it possible to limit the scope of application permissions to only specific sharepoint sites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops#continuous-deployment)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
1) Not at this time... deployment permissions don't support app-only so you must use a user account. The way most do this is a service account without MFA enabled.

2) No, because permissions are tied to a resource (ie: the FQDN), not the full path to the resource.
