### ISSUE TITLE
Error with office ui fabric react modules

### ISSUE THREAD

**Issue by abdollahkahne** [SharePoint/sp-dev-docs#4993]
### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I have created a webpart using SharePoint Framework. But the following error doesnt let me to use office-ui-fabric-react components:

`node_modules/office-ui-fabric-react/node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(50,0)`

After some search I have noticed that people have encountered this issue before (Almost one years ago!). I found that my package.json is completely old regard to my other project that works correctly. Both are generated using same yo sharepoint generator but for different targeted product (SharePoint versions!). 
Sorry if it is trivial or repetitive. I am almost new in these areas.

Thanks in advance

**Comment by andrewconnell** [comment]
Need context... what version of SPFx are you using, Fabric React, environment, etc.... also would help if you shared your package.json & more context where you are seeing the error. Hard to help with limited info provided.

**Comment by abdollahkahne** [comment]
Sry about the lack of information. I attach them in this comment (1- Sharepoint 2019 onwards 2- + office-ui-fabric-react@7.73.0 and 3- node version v10.15.2 4- npm version 5.8.0


![Screenshot from 2019-12-14 18-36-36](https://user-images.githubusercontent.com/48277995/70850559-ef808780-1ea0-11ea-8165-830ca8b5495a.png)
)
![Screenshot from 2019-12-14 18-44-50](https://user-images.githubusercontent.com/48277995/70850648-f1971600-1ea1-11ea-834b-bd8d640d23a6.png)
I also attached json for my last two project which one is without bug (sharepoint online) and the other has bugs (sharepoint 2019 onward). Both generated using same generator and both use office-ui-fabric-react (first extract the following file please).


[package.zip](https://github.com/SharePoint/sp-dev-docs/files/3963965/package.zip)

Thanks again

**Comment by andrewconnell** [comment]
You are trying to use an unsupported version of Fabric React with SPFx v1.4 (SP2019). 

In the **package.json** you included, you are referencing `"office-ui-fabric-react": "^7.73.0"`. That's the current version of Fabric React, but it is not supported on SP2019. SP2019 already has a version of Fabric React deployed & in use... it's not supported to update it. The supported version for SP2019 is 5.132.0.

See the first big purple note on this page: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components

**Comment by abdollahkahne** [comment]
@andrewconnell Thanks for your complete answer. After changing `office-ui-fabric-react `version to `5.132.0 `in `package.json` and running `npm install`, I build the webpart without any error. Thanks again.
