### ISSUE TITLE
skiplistsonlyblockedbyoobreaons spelling mistake

### ISSUE THREAD

**Issue by Forket** [SharePoint/sp-dev-docs#4996]
--skiplistsonlyblockedbyoobreaons  should be --skiplistsonlyblockedbyoobreasons

missed S in skiplistsonlyblockedbyoobreaSons 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Hi @Forket, 
Although a spell mistake, the option --skiplistsonlyblockedbyoobreaons is correct. No extra S is needed to run the tool.

**Comment by andrewconnell** [comment]
Thanks... fixing the doc...

**Comment by andrewconnell** [comment]
Actually not a spelling error in the doc... but in the tool. The doc is correct, but it appears the tool's help report may need to be fixed. @jansenbe, you own this tool, correct?
