### ISSUE TITLE
Get-SPOTheme return nothing?

### ISSUE THREAD

**Issue by kongmengfei** [SharePoint/sp-dev-docs#4997]
where are the "examples"?  And if i run get-spotheme, it returns nothing!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff514d24-111a-d79e-396f-feb65a1fb7d7
* Version Independent ID: 20540d08-e747-3395-29df-e266919bfc36
* Content: [SharePoint site theming - PowerShell cmdlets](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-powershell)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
The following example for your reference.
```
$tenant="tenant"
Connect-SPOService ("https://{0}-admin.sharepoint.com" -f $tenant) -Credential (Get-Credential)
$themes = Get-SPOTheme
foreach ($theme in $themes) {
    $theme.Name
}
```
If you want to get all the themes from tenant, we can also use PnP PowerShell to achieve it.
```
$adminUrl= "https://tenant-admin.sharepoint.com"
Connect-PnPOnline -Url $adminUrl -UseWebLogin
$themes = Get-PnPTenantTheme
$themes | Format-Table Name
```
If you want to get the theme from current web, we can use the PowerShell below.
```
$siteUrl= "https://tenant.sharepoint.com/sites/team"
Connect-PnPOnline -Url $siteUrl -UseWebLogin
$themes = Get-PnPTheme
$themes | Format-Table Name
```
**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by kongmengfei** [comment]
i still get nothing.
![sp10 NIC1 (RDP) (shvmasrdp fareast corp microsoft com) - Remote Desktop Connection Manager v2 7](https://user-images.githubusercontent.com/57654821/70416919-130b9280-1a9b-11ea-9d7e-c7a46a959893.jpg)

**Comment by Dennis-LZ** [comment]
If you can't add theme, you will get nothing. You can use the Script below to add theme to the tenant.
```
$themepalette = @{
  "themePrimary" = "#00ffff";
  "themeLighterAlt" = "#f3fcfc";
  "themeLighter" = "#daffff";
  "themeLight" = "#affefe";
  "themeTertiary" = "#76ffff";
  "themeSecondary" = "#39ffff";
  "themeDarkAlt" = "#00c4c4";
  "themeDark" = "#009090";
  "themeDarker" = "#005252";
  "neutralLighterAlt" = "#f8f8f8";
  "neutralLighter" = "#f4f4f4";
  "neutralLight" = "#eaeaea";
  "neutralQuaternaryAlt" = "#dadada";
  "neutralQuaternary" = "#d0d0d0";
  "neutralTertiaryAlt" = "#c8c8c8";
  "neutralTertiary" = "#a6a6a6";
  "neutralSecondaryAlt" = "#767676";
  "neutralSecondary" = "#666666";
  "neutralPrimary" = "#333";
  "neutralPrimaryAlt" = "#3c3c3c";
  "neutralDark" = "#212121";
  "black" = "#000000";
  "white" = "#fff";
  "primaryBackground" = "#fff";
  "primaryText" = "#333"
}
Add-PnPTenantTheme -Identity "MyCompanyTheme" -Palette $themepalette -IsInverted $false
```
**Dennis Guo
Microsoft SharePoint Community Support**
