### ISSUE TITLE
SPFX Icons disappeared

### ISSUE THREAD

**Issue by dguarneri71** [SharePoint/sp-dev-docs#4998]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
<i class="ms-Icon ms-Icon--NavigateForwardMirrored" aria-hidden="true"></i>

The above class should display fabric ui icon from https://uifabricicons.azurewebsites.net/ with the same name. 

#### Observed Behavior

Nothing is displayed

#### Steps to Reproduce

Our package contents: 

"dependencies": {
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-lodash-subset": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-base": "1.6.0",
    "@pnp/pnpjs": "^1.2.2",
    "@pnp/spfx-controls-react": "1.8.0",
    "@pnp/spfx-property-controls": "1.10.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.0.0",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.0.0",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  }

We are importing icons using

import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';

And this is our "onInit" method: 

public onInit(): Promise<void> {  
    initializeIcons("https://spoprod-a.akamaihd.net/files/fabric/assets/icons/");

    return super.onInit().then(_ => {
      sp.setup({
        spfxContext: this.context
      });
    });
  }

Thank you for reading!

**Comment by andrewconnell** [comment]
Unclear what you're saying is wrong here... 

@dguarneri71 said:
> The above class should display fabric ui icon from https://uifabricicons.azurewebsites.net/ with the same name.

What's the "above class"? There's no class listed above that statement in your post...

**Comment by dguarneri71** [comment]
I'm sorry.
I use this code <i class="ms-Icon ms-Icon--NavigateForwardMirrored" aria-hidden="true"></i> but the icon does not appear.
About the questions:
1) SharePoint environment(s): SharePoint Online
2) ... is the tenant configured for standard / targeted release: YES
3) +-- @pnp/generator-spfx@1.2.0
    +-- @pnp/office365-cli@1.16.0
    +-- gulp@4.0.0
     `-- yo@2.0.5
4) IE 11 and Chrome
5) "@microsoft/sp-office-ui-fabric-core": "1.6.0", "react": "15.6.2"

**Comment by andrewconnell** [comment]
@StfBauer Is this is SharePoint issue or is this really an OUIF issue? It seems inappropriate in this list... but not sure...

**Comment by andrewconnell** [comment]
@dguarneri71 said:
>  @pnp/generator-spfx@1.2.0

What SPFx version are you using... not the PNP generator (although that looks REALLY old). Would be helpful if you shared:
- contents of your package.json
- how you're referencing icons in your code (you haven't shown this yet in this thread)

IOW, we need more context... but I'm also not sure this is a SharePoint thing. This might be more appropriate to ask the OUIF forum as I'm not sure this is SharePoint related and thus, no one here could do much about this...

**Comment by dguarneri71** [comment]
This is my package.json
{
  "name": "xxxxxxxx",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-lodash-subset": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-base": "1.6.0",
    "@pnp/pnpjs": "^1.2.2",
    "@pnp/spfx-controls-react": "1.8.0",
    "@pnp/spfx-property-controls": "1.10.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.0.0",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.0.0",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.6.0",
    "@microsoft/sp-module-interfaces": "1.6.0",
    "@microsoft/sp-webpart-workbench": "1.6.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "~5.0.0"
  }
}

For the icon I use 
**import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';**
**initializeIcons("https://spoprod-a.akamaihd.net/files/fabric/assets/icons/");** in Init method
and
`<i class="ms-Icon ms-Icon--NavigateForwardMirrored" aria-hidden="true"></i>`

**Comment by andrewconnell** [comment]
There were fixes related to the icons in a later version of the referenced packages... this is a quite old version (1.6). Suggest you first upgrade the project to the latest and reverify to ensure you have the latest fixes applied.

**Comment by dguarneri71** [comment]
Thanks Andrew

**Comment by dguarneri71** [comment]
I will try to follow the suggestion
