### ISSUE TITLE
Feature request: E-mail property on the SPUser object

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#50]
I would like to see an `EMail` property on the `SPUser` object. Even though it is "best" practice to use UPN=e-mail, this is not the case in many scenarios, so the `loginName` is not the same as the e-mail.

**Comment by vman** [comment]
The _spClientSidePageContext object does contain a user.Email property (_spClientSidePageContext.user.Email) and according to [this](https://github.com/SharePoint/sp-dev-docs/wiki/Drop-1), the properties from _spClientSidePageContext will be gradually moved into the Context variable. So hopefully this request should be coming soon.

**Comment by manishgarg1** [comment]
Yes, we will be evolving the pageContext and objects contained in it. Requirements are greatly appreciated.

**Comment by huey253** [comment]
This issue has been addressed and should be resolved in the next update. Thank you for the feedback

-Landis

**Comment by nickpape-msft** [comment]
Closing this issue as it was addressed in [Drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2). Please re-open if necessary
