### ISSUE TITLE
The getPropertyPaneConfiguration() method gets called twice when a OOTB textfield property pane changes

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-docs#500]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
The **getPropertyPaneConfiguration()** method is called twice every time a out-of-the-box TextField property pane changes, which causes problems with custom property panes within the same toolpart.
 
#### Observed Behavior
I was following this great article on how to create a custom PropertyPaneASyncDropdown :

[Build custom controls for the property pane](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/build-custom-property-pane-controls)

The tutorial works perfectly, and the cascading async dropdowns behaves like expected. However, as soon as you add an out-of-the-box textfield property pane along with the cascading dropdowns, things start to get funky.

When a OOTB textfield property pane changes, the **getPropertyPaneConfiguration()** method gets called twice (for some reason?), which causes the following :

On the first call, everything is normal :
- The method **getPropertyPaneConfiguration()** gets called for the first time
- Within that same method, the async property panes are re-initialized
```javascript
protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {

    // Creates a custom PropertyPaneAsyncDropdown for the webUrl property
    this.webUrlDropdown = new PropertyPaneAsyncDropdown('webUrl', {
      label: strings.WebUrlFieldLabel,
      loadingLabel: strings.WebUrlFieldLoadingLabel,
      errorLabelFormat: strings.WebUrlFieldLoadingError,
      loadOptions: this.loadWebUrlOptions.bind(this),
      onPropertyChange: this.onWebUrlChange.bind(this),
      selectedKey: this.properties.webUrl || ""
    });

    ...
```
- The re-initialized async property pane's constructor is then called
```javascript
constructor(targetProperty: string, properties: IPropertyPaneAsyncDropdownProps) {
    this.targetProperty = targetProperty;
    this.properties = {
      label: properties.label,
      loadingLabel: properties.loadingLabel,
      errorLabelFormat: properties.errorLabelFormat,
      loadOptions: properties.loadOptions,
      onPropertyChange: properties.onPropertyChange,
      selectedKey: properties.selectedKey,
      disabled: properties.disabled,
      onRender: this.onRender.bind(this),
      key: targetProperty
    };
  }
```
- Immediatly after the constructor, the **onRender()** method of the property pane is then called, allowing the property pane to store it's associated HTMLElement locally in order to be able to reference it later on when re-rendering the property pane manually
```javascript
private onRender(elem: HTMLElement): void {
    if (!this.elem) {
      this.elem = elem;
    }

    ...
```

So far so good, but then the **getPropertyPaneConfiguration()** methods gets called a second time, and the following happens : 

- The async property panes are re-initialized again (no big deal)
- The async property panes constructors are once again called (so far so good)
- But the property panes **onRender()** method never gets called this time! That means the following snippet is never executed :
```javascript
private onRender(elem: HTMLElement): void {
    if (!this.elem) {
      this.elem = elem;
    }
    ...
```
- This is a problem because later on, when a dropdown tries to re-render another dropdown like explained in the tutorial, it uses the following public **render()** method : 
```javascript
public render(): void {
    if (!this.elem) {
      return;
    }
    this.onRender(this.elem);
  }
```
- The last line within that method never gets called because the **this.elem** variable that has been persisted locally on the first **getPropertyPaneConfiguration()** call got lost on the second call.

Basically the second call seems wrong to me, it does reinitialize the property panes object, but never calls their **onRender()** method, while the first call does. Not sure if there is any good reason for calling that whole method twice because of a textfield change.

I have "hacked" a fix by putting the cascading dropdown on a different toolpart page, but it really isn't a real fix since putting back everything on the same page brings back the problem.

#### Steps to Reproduce
- Create this exact example of cascading async dropdowns :
[Build custom controls for the property pane](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/build-custom-property-pane-controls)
- Add on the same toolpart page, a OOTB textfield property pane
- When the toolpart opens for the first time, cascading dropdowns will work perfectly
- Then add a value to the textfield
- Then try the cascading dropdowns again, nothing will happen because their **render()** method now have no effect at all

**Comment by patmill** [comment]
@srideshpande

**Comment by suz7777** [comment]
this works - thanks for the help!
we created a global function
in onInit i do:
```
this.GlobalMethods.getJSDependencies().then(() => {
      return super.onInit();
    });
```

in global function library i do
```
public getJSDependencies(): Promise<any> {
        var logFunctionName = "getJSDependencies";
        var isLoadingComplete = [];

        //jquery loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for jQuery");
        if (!window['jQuery']) {
            this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery");
            isLoadingComplete.push(SPComponentLoader.loadScript(globals.mmmGoJQueryDir, { globalExportsName: 'jQuery' }).then(() =>
                SPComponentLoader.loadScript(globals.mmmGoSwipeJs, { globalExportsName: 'jQuery' }).then(() => 
                SPComponentLoader.loadScript(globals.mmmGoPluginsDir, { globalExportsName: 'jQuery' }).then((jq: any): void => {
                    jq = jq;
                    jq = window['jQuery'];
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoJQueryDir + ") - succeeded");
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoPluginsDir + ") - succeeded");
                    this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: loading jQuery (" + globals.mmmGoSwipeJs + ") - succeeded");
                }))));
        }

        //cacheManager loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for cacheManager");
        if (!window['cacheManager']) {
            isLoadingComplete.push(SPComponentLoader.loadScript(globals.mmmGoCacheMgrDir, { globalExportsName: 'cacheManager' }).then((cacheManager: any): void => {
                cacheManager = cacheManager;
                cacheManager = window['cacheManager'];
                this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: cacheManager (" + globals.mmmGoCacheMgrDir + ")loading completed");
            }));
        }

        //cacheManager loading
        this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: checking for classic SP");
        if (!window['SP']) {
            isLoadingComplete.push(SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/init.js', { globalExportsName: '$_global_init' }).then(() =>
                SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/MicrosoftAjax.js', { globalExportsName: 'Sys' }).then(() =>
                    SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.taxonomy.js', { globalExportsName: 'SP' }).then(() =>
                        SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.Runtime.js', { globalExportsName: 'SP' }).then(() =>
                            SPComponentLoader.loadScript('https://microsoft.sharepoint.com/_layouts/15/SP.js', { globalExportsName: 'SP' }).then((SP) => SP))))));
            this.handleErrorNew((<any>this).constructor.name, logFunctionName, "start processing: SP loading completed");
        }

        return Promise.all(isLoadingComplete);
    }
```


now in front of all SP, jQuery, etc
`var  context = new (window as any).SP.ClientContext.get_current();`

**Comment by srideshpande** [comment]
I will take a look into it.

**Comment by spplante** [comment]
Thanks!

If it can help, I think it does the same thing with any other ootb property panes, at least I noticed the checkbox and toggle property panes also call the method twice.

**Comment by spplante** [comment]
Closed the issue by mistake my bad.

**Comment by spplante** [comment]
Any update on this?

**Comment by srideshpande** [comment]
@spplante - Sorry for the delay. Its been fixed and available to the public in the next release.
I am closing the issue now. Please feel free to re-open and assign it to me if you think it's not fixed.

**Comment by spplante** [comment]
Great news thank you!

**Comment by kmartindale** [comment]
Has this been pushed? I'm experiencing a similar issue.
