### ISSUE TITLE
Error: Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by JasonPan** [SharePoint/sp-dev-docs#5003]
Seems related to #4214 and #1420 - however navigating to the URL mentioned only returns a page saying "Sorry, something went wrong. An unexpected error has occurred." - there is no error ID but status code is "302 Found".

We originally deployed in early November with multiple deployments since then and no issues, it has only started appearing on our production environment yesterday after our last deployment (changes were minor CSS changes).

Tried with signing out, clearing browser cache, incognito - no luck. However, after using Chrome Devtools and navigating to Application tab > Storage > Session storage and clearing the values under xx.sharepoint.com and xx-isolated-domain.sharepoint.com, refreshing the page shows that the error disappears, and does not come back. This issue does not appear for everyone, and did appear once in our dev tenant (current issue is in our production tenant), but once it resolved itself it hasn't appeared since.

There is an error message prior to the token renewal error "Refused to display "<spfxsinglesignon-url>" in a frame because it set 'X-Frame-Options' to 'sameorigin'. This message doesn't show up if there is no token renewal error.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Graph call to complete properly to give details of signed-in user's directReports. React-based webpart (v1.9.1, isDomainIsolated
 is TRUE), bundled, packaged, deployed. API permissions granted in the SPO Admin Center. App added to a site. Client-side webpart added to a modern page. Call is observed with Chrome Dev tools.

#### Observed Behavior

Call fails with the error observed in the Chrome Dev tools.

#### Steps to Reproduce

Simple Graph call as below
```
const client: MSGraphClient = await context.msGraphClientFactory.getClient();
const res = await client
    .api("me/directReports")
    .version("v1.0")
    .select("id,displayName,onPremisesSamAccountName,jobTitle")
    .get()
    .catch(err => {
       if (err) {
         console.error(err);
           return;
       }
    });
```

**Comment by andrewconnell** [comment]
Appears to be a dupe to an existing open discussion #4892 ... per our normal process, we try to limit dupe issues so closing.
