### ISSUE TITLE
error No valid versions available for undefined

### ISSUE THREAD

**Issue by parthipan15** [SharePoint/sp-dev-docs#5004]
1265 silly pacote range manifest for to-regex@^3.0.2 fetched in 106ms
1266 silly resolveWithNewModule to-regex@3.0.2 checking installable status
1267 silly pacote range manifest for regex-not@^1.0.0 fetched in 123ms
1268 silly resolveWithNewModule regex-not@1.0.2 checking installable status
1269 silly pacote range manifest for snapdragon@^0.8.1 fetched in 114ms
1270 silly resolveWithNewModule snapdragon@0.8.2 checking installable status
1271 timing stage:rollbackFailedOptional Completed in 1ms
1272 timing stage:runTopLevelLifecycles Completed in 15529ms
1273 verbose type range
1274 verbose stack Error: No valid versions available for undefined
1274 verbose stack     at pickManifest (C:\Users\parthipan_s\node_modules\npm\node_modules\npm-pick-manifest\index.js:39:11)
1274 verbose stack     at fetchPackument.then.packument (C:\Users\parthipan_s\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14)
1274 verbose stack     at tryCatcher (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
1274 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
1274 verbose stack     at Promise._settlePromise (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
1274 verbose stack     at Promise._settlePromise0 (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
1274 verbose stack     at Promise._settlePromises (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
1274 verbose stack     at _drainQueueStep (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
1274 verbose stack     at _drainQueue (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
1274 verbose stack     at Async._drainQueues (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
1274 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\parthipan_s\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
1274 verbose stack     at runCallback (timers.js:705:18)
1274 verbose stack     at tryOnImmediate (timers.js:676:5)
1274 verbose stack     at processImmediate (timers.js:658:5)
1275 verbose cwd C:\Users\parthipan_s
1276 verbose Windows_NT 10.0.17134
1277 verbose argv "C:\\Users\\parthipan_s\\node.exe" "C:\\Users\\parthipan_s\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
1278 verbose node v10.17.0
1279 verbose npm  v6.11.3
1280 error code ENOVERSIONS
1281 error No valid versions available for undefined
1282 verbose exit [ 1, true ]

After installed node and npm
![image](https://user-images.githubusercontent.com/44926524/70503655-e2366680-1b49-11ea-97cd-09b70e656f4c.png)

**Comment by andrewconnell** [comment]
Sorry, but unclear what you're saying is wrong. Please resubmit with more detail...
