### ISSUE TITLE
French version of SharePoint Modernization scanner

### ISSUE THREAD

**Issue by FrancoisNevo** [SharePoint/sp-dev-docs#5007]
Hello,

I would like to know: is there a French version of the SharePoint Modernization scanner? Because looking at the screenshots from this page: https://docs.microsoft.com/fr-fr/sharepoint/dev/transform/modernize-scanner#page-1-scanner-authentication-configuration it looks like there is a French version, but the only one I can get is the English one.

Could you confirm that the UI of this tool has been localized?
Thanks and best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner?source=docs#feedback)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jansenbe** [comment]
The docs are translated, the scanner however is English only.
