### ISSUE TITLE
Can't get past yo @microsoft/sharepoint

### ISSUE THREAD

**Issue by Kyle-Champion** [SharePoint/sp-dev-docs#5008]
Hi guys, 

This script fails when trying to get the dependency "node-sass@4.9.3"... Below is the snippet of the error log:

&gt; node-sass@4.9.3 install C:\Workspace\Experiments\SharePointDev\2019_SPFX\hellowworld\node_modules\node-sass
&gt; node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-72_binding.node":

HTTP error 404 Not Found

...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension#feedback)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you provide some context? Environment, SharePoint environment, version of Node, NPM, SPFx generator installed (`npm list -g --depth=0`), etc...

**Comment by Kyle-Champion** [comment]
Thanks @andrewconnell for the reply. I managed to solve this problem, but here are the details that caused it.

I was attempting to create an SPFx Extension for SharePoint Online.

Using the latest version of Node JS 12.13.1 is the problem here. I downgraded to v10.17.0 and everything was fine again. 

Things I tried in the process however, included trying to upgrade gulp from 3.9.1 to 4.0.2 - no change.
Upgrade yeoman to 3.1.1 - also no change.
I even tried to download node-sass and reference it locally - also no change.

Here is a dump of `npm list -g --depth=0` for interest sake.

C:\Users\Kyle>npm list -g --depth=0
C:\Users\Kyle\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.9.1
+-- azure-functions-core-tools@1.0.6
+-- bower@1.8.2
+-- gulp@4.0.2
+-- gulp-cli@2.2.0
+-- node-sass@4.9.3 -> C:\Users\Kyle\Downloads\node-sass-4.9.3\node-sass-4.9.3
+-- npm-windows-upgrade@6.0.1
+-- ts-node@3.0.6
+-- typescript@2.3.4
+-- uglify-js@3.0.11
+-- vim@0.1.0
`-- yo@3.1.1

**Comment by andrewconnell** [comment]
Yup... that will do it. The docs explicitly say only Node 8 & Node 10 are supported at this time.
