### ISSUE TITLE
BUG: SPFx Builds Fail after March 19 ~1900UTC | gulp-core-build-typescript update breaks builds

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#501]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Builds succeed on the default project created from accepting all defaults in the Yeoman generator.

#### Observed Behavior
Builds fail TypeScript transpilation step... specifically the subtask **typescript**. Errors start with the following & yield 25 errors.

```shell
21:39:28] Starting subtask 'typescript'...
[21:39:28] [typescript] TypeScript version: 2.2.1
[21:39:28] Finished subtask 'copy-static-assets' after 523 ms
[21:39:29] Error - typescript - node_modules/@microsoft/sp-http/lib/httpClient/HttpClientResponse.d.ts(16,21): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
[21:39:29] Error - typescript - node_modules/@types/whatwg-fetch/index.d.ts(5,14): error TS2300: Duplicate identifier 'Request'.
[21:39:29] Error - typescript - node_modules/@types/whatwg-fetch/index.d.ts(20,1): error TS2403: 
[...]
```

#### Steps to Reproduce
1. Install all prereqs using any version of Node (verified with Node.js v4.\*, v6.\* & v7.\*)
1. Run the generator `$ yo @microsoft/sharepoint` and accept all defaults
1. Build the project... it will fail as seen in the screenshot below

#### Steps to Resolve
Uninstall the updated **gulp-core-build-typescript** package updated March 19, 2017 ~1900 UTC (see https://github.com/Microsoft/web-build-tools/commit/0a793bccdb99f0976272129dc12839c1a0da32db for commit that triggered the issue) which is version **2.4.0**. ~Revert back to 2.3.0 which will work.~ Install **2.4.1** which patches the issue that caused this regression (*[see below for info](https://github.com/SharePoint/sp-dev-docs/issues/501#issuecomment-287712135)*).

1. After the SharePoint generator completes, before building the project, delete **gulp-core-build-typescript**:

  ```shell
  rm -rf node_modules/@microsoft/gulp-core-build-typescript
  ```

  > note the step above is NOT required as the next step will simply overwrite the old version... I added it here to be explicit.

1. Reinstall the previous working version:

  ```shell
  npm install @microsoft/gulp-core-build-typescript@2.4.1
  ```

1. Now run `gulp build` and the project will successfully transpile.

#### PERSONAL REQUEST by OP

Microsoft SPFx Engineer: PLEASE _PLEASE_ consider this a feature request... _PLEASE_ shrink wrapping [ref npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) the dev tools... this is the second time an upstream dependency has broken development for your adopters of the SharePoint Framework and it's unecessarily giving SPFx a bad rep. I thought the #394 "lodash-gate" incident would have been enough to consider this prior to GA. This is a common technique for packages that have significant number of dependencies such as this.

![pasted_image_at_2017_03_19_06_16_pm](https://cloud.githubusercontent.com/assets/2068657/24086871/82057642-0ced-11e7-8144-256a13520477.png)

**Comment by davidhartman** [comment]
Thanks @andrewconnell I've been trying to figure this issue out for the past few hours.

**Comment by patmill** [comment]
Fixed.  There is a shrinkwrap work item on the backlog as well.

**Comment by waldekmastykarz** [comment]
Not sure if it's related but I've just created a new project and while it's building, there are a few instances of the following warning displayed:

```
Could not find implementations for the following rules specified in the configuration:
    prefer-const
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

**Comment by andrewconnell** [comment]
Little more detail for those tracking... here's the fix that @patmill referenced: https://github.com/Microsoft/web-build-tools/pull/140

**Comment by andrewconnell** [comment]
@waldekmastykarz check your TSLint... With the latest version & a clean project, I don't see any of that.

**Comment by andrewconnell** [comment]
@patmill since the 2.4.1 patch has been published for **[gulp-core-build-typescript](https://www.npmjs.com/package/@microsoft/gulp-core-build-typescript)**, appears this issue is now moot. This should be flagged as a bug... but I'm going to go ahead and close it.

**Comment by waldekmastykarz** [comment]
I've just created a brand new project @andrewconnell (no JS framework): still the same error

**Comment by waldekmastykarz** [comment]
Error is reported only on a vanilla SPFx project. After scaffolding the project and running

```
npm i @microsoft/gulp-core-build-typescript -D
```

no error is reported anymore.

**Comment by patmill** [comment]
Hey Waldek - for the one that doesn't work, what version of gcb-typescript is getting used?  Could the wrong version be cached in your machine?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by waldekmastykarz** [comment]
It's on @microsoft/gulp-core-build-typescript@2.4.1 @patmill
