### ISSUE TITLE
Batching REST operations in SharePoint Online

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#5010]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
This is status update request for the batch client feature in SPFx (`spHttpClient.beginBatch`). It is currently only available in project scaffolded using the --plusbeta flag (although, it has gone in GA accidentally a few times but I guess those don't count). As of 1.9.1, is there a recommended or supported way of making batch calls in SPFx?

**Comment by andrewconnell** [comment]
No change & no update. ATM that's the only batch support for the SharePoint REST API in the SPFx API. Alternatively, you can use the Microsoft Graph's support for batch.
