### ISSUE TITLE
Group ListView CommandBar commands

### ISSUE THREAD

**Issue by vvvvasilev** [SharePoint/sp-dev-docs#5013]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Question

Is there a way to group several ListView CommandSet commands under one custom button in the command bar?  Just like the New, Upload or Flow buttons in the command bar of a document library... 
![image](https://user-images.githubusercontent.com/50363057/70610856-f5f6d100-1c0c-11ea-94ec-103b66e8ab2c.png)

**Comment by andrewconnell** [comment]
Not at this time. Good submission idea for User Voice though...
