### ISSUE TITLE
Column Format in on-premise SP2019 generates Error when use condition

### ISSUE THREAD

**Issue by Basti087** [SharePoint/sp-dev-docs#5014]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We want to format a column with a Background Color based on a field with an IF condition.

#### Observed Behavior

In Sharepoint 2019 on-premise the column displays an error for the JSON.
In Sharepoint Online, the JSON works and the column displays the color.

#### Steps to Reproduce

You can take a look at my thread in the product forum at microsoft:
https://social.technet.microsoft.com/Forums/de-DE/d7ae48d3-6959-4053-bdab-4ac19590a4a4/column-format-not-working?forum=SP2019

Special Thanks to: Jerry Zy.
He helped me narrow it down.

I tried it also with the Example from the offical doku with the same error message.
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting

Many thanks and best regards
Basti

**Comment by shagra-ms** [comment]
Excel style expressions are not supported on SP2019 on premises. This is expected.

@Basti087 Can you share the JSON you are trying to use? Can you try the below JSON, which is equivalent to the JSON you are referring to in the product forum - 

```javascript
{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
    "elmType": "div",
    "debugMode": true,
    "txtContent": "@currentField",
    "style": {
        "color": {
            "operator": "?",
            "operands": [
                {
                    "operator": "<=",
                    "operands": [
                        "[$Created]",
                        "@now"
                    ]
                },
                "#ff0000",
                ""
            ]
        }
    }
}
```

**Comment by PrasadKasireddy** [comment]
Expressions can be written using Excel-style expressions in SharePoint Online, or by using Abstract Syntax Tree expressions in SharePoint Online and SharePoint 2019.
