### ISSUE TITLE
Adding the app is not only not necessary, its not possible

### ISSUE THREAD

**Issue by iBrooks** [SharePoint/sp-dev-docs#5015]
This guide instructs you to, once you have uploaded your package, add the 'app' to a site.

The web part is not available as an app, you cannot add it to your site.

However the part is available to add on-page already and works as intend.

The 'Install the client-side solution on your site' section needs to be completely cut to return this guide to accuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ee4609-11a2-b852-daed-585f9f678957
* Version Independent ID: df1d0ade-b26f-2b48-eaff-4ed2d6b1ec63
* Content: [Deploy your client-side web part to a SharePoint page (Hello World part 3)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)
* Content Source: [docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Have you checked "Make this solution available to all sites in the organization" when deploying your SPFx web part through the appcatalog? Maybe we only need to add this detail to the documentation in order to avoid misunderstanding.

**Comment by andrewconnell** [comment]
@JarbasHorst is correct... if you answered "YES" to that question, it will automatically install the app behind the scenes and thus, it won't need to be installed and thus, not shown. This is expected.

The instructions [in a previous step](https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) said to specify NO to that answer, therefore this doc appears to be correct.
