### ISSUE TITLE
PPTXGENJS unable to create ppt styled data

### ISSUE THREAD

**Issue by thamazingone** [SharePoint/sp-dev-docs#5023]
I have a css formatted table and I am trying to get the same in ppt format for which I wrote the below code.

function table2slidesDemoForTab(inTabId,inOpts) {
 var pptx = new PptxGenJS();
pptx.addSlidesForTable(inTabId,(inOpts||null));
pptx.save( inTabId+'_'+getTimestamp() );
 }

But still I get the table data in unstyled format. Please help me get this done!! Thank you!

**Comment by andrewconnell** [comment]
What is PptGenJS()? Not nearly enough context here to help... sorry... but if you're having trouble with a third party library, should check with that library's support as from the limited info shown, doesn't look like a SharePoint related issue.
