### ISSUE TITLE
Adding SPFx web part to teams gives a random error when not tenant-deployed

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#5025]
#4912 ## Category
- [x] Bug

#### Expected or Desired Behavior

If the SPFx was not deployed tenant-wide either DO NOT show it in the teams app at all, or when a user try to add it show a friendly message saying the package must be deployed globally, using the "Make this solution available to all sites in the organization"

#### Observed Behavior

Users can try to add the SPFx as a tab to teams, but get redirected to an unclear error page saying the component ID is wrong.

#### Steps to Reproduce

Create and SPFx that allows tenant-wide deployment
Deploy it WITHOUT selecting "Make this solution available to all sites in the organization"
Sync it to teams

Switch to teams: try to add this app as a tab to teams >> see error page.

#### Comments
Sure, the documentation says this option is required, and that is fine. The bug I open here is strictly for asking to either not show apps that were not deployed globally in the teams app OR to show a friendly error message explaining how to make it work in the teams app, IE: "You must deploy this app globally before you add it to Teams"

**Comment by shaipetel** [comment]
Referencing documentation, step 5:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction#deployment-options

**Comment by andrewconnell** [comment]
While I agree & it's a good suggestion, I'm not sure this is a bug because it is working as designed. From my POV, this is a change request to the UX... correct? If so, those goto User Voice as they aren't really bugs...

**Comment by shaipetel** [comment]
@andrewconnell  perhaps we disagree on the definition of bug vs. by design,
IMHO if you allow the user to click add -> SPFx webpart and they end up in a random error page that would be considered a bug.

In fact, I can't imagine a clearer scenario of a bug.

But, agree to disagree? ;)

**Comment by andrewconnell** [comment]
IMHO, bug = doesn't work as designed.

The docs you linked to state when you create the project to say to make it available for tenant wide deployment and when you deploy it, the docs explicitly state "*Ensure that the Make this solution available to all sites in the organization option is selected, so that the web part can be used from the Microsoft Teams side.*".

From my POV, if you don't follow the instructions, and it doesn't work, that's not a bug. That's by design.  Like I said, could the UX be a bit clearer for the end user? Sure, but that's not a bug...

**Comment by shaipetel** [comment]
> IMHO, bug = doesn't work as designed.
> 
> The docs you linked to state when you create the project to say to make it available for tenant wide deployment and when you deploy it, the docs explicitly state "_Ensure that the Make this solution available to all sites in the organization option is selected, so that the web part can be used from the Microsoft Teams side._".
> 
> From my POV, if you don't follow the instructions, and it doesn't work, that's not a bug. That's by design. Like I said, could the UX be a bit clearer for the end user? Sure, but that's not a bug...

Sorry, but where in the document does it say the users should be able to try to add the web part and they should be redirected to a strange error page?

The documentation says it is not supported, sure. But the bug is not about that - the bug is about the error page that is showing up. I'm sure that is not intentional OR by design.

**Comment by andrewconnell** [comment]
@shaipetel said (*my emphasis*):
> Sorry, but where in the document does it say the users should be able to try to _**add the web part**_ and they should be redirected to a strange error page?

I didn't say that. Users aren't adding a _web part_, they are adding a _tab_ in Microsoft Teams.

I just copied the docs that say they have to select the box to deploy it to all sites in the org which is what the docs say. The one you linked to in your comment contains this in the deployment step:

![image](https://user-images.githubusercontent.com/2068657/71112504-a595eb00-2199-11ea-955c-9d3bf9392234.png)

That page contains the text I quoted in my last reply.

**Comment by shaipetel** [comment]
True, but the user adding the Tab is not the developer, or the person who deploys the app.

Assuming someone else deployed your SPFx to be used on one specific site.

From my POV, of a Teams user - I open Teams, click to add a tab, see a "cool weather viewer" and selects it. Boom - error page.

Maybe its a Teams bug, maybe should not be reported here, IDK, but definitely a bug.

All the documents you are referencing aren't relevant to the user who just adds the tab.

The more these apps become popular, the more support tickets these users will open, rightly so, since they aren't appear to be doing anything wrong but are getting a random error page.

that said, feel free to keep it closed I've said what I had to say and its fine if you don't agree. I'm sure it will get fixed when other people keep reporting it I'm not about to make this a crusade of mine.

Thanks for the quick responses!

**Comment by andrewconnell** [comment]
NP... I'm just trying to stay by the "rules" of this repo's issue list. This is for dev issues... from my POV, what you're describing is a UX experience change and that's, according to the convention, is a user voice submission.

**Comment by shaipetel** [comment]
I love Elmo. You win ;)
