### ISSUE TITLE
webApiPermissionRequests "resource" property

### ISSUE THREAD

**Issue by aaronmi** [SharePoint/sp-dev-docs#5026]
Regarding webApiPermissionRequests/"resource" property, doc: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application says it should be the displayName of the application. Here (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi#request-permissions-to-the-enterprise-api) it says it can be either displayName or ID. It's confusiong. Should it always be displayName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It should be the display name, NOT the GUID. The GUID was an option in the dev preview. 

Currently researching something else about that doc... once that's confirmed  I'll get it updated.

**Comment by andrewconnell** [comment]
It should be the **Name** of the specified app, not the GUID.

**Comment by Ballzer0** [comment]
it does not seem to work to request access to Dynamics CRM like this.
{
        "resource": "Dynamics CRM",
        "scope": "user_impersonation"
 }

Had to manually add this on the registered app in azure AD

**Comment by ajashish7** [comment]
I am seeing HTTP 400 while approving web API request in admin center. What might be causing this?
