### ISSUE TITLE
New webpart created by new Yo generator creates completely blank Workbench

### ISSUE THREAD

**Issue by Cmohan** [SharePoint/sp-dev-docs#5027]
I created a blank web part scaffold with the new Yo generator and tried to run "gulp serve". It works but the workbench that is created is completely blank. No SharePoint headers, body or footers. I tried this two times and it didn't work either time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Need more context info... any errors in the console, environment (Windows/MacOS), target environment (SPO/SP2019/SP2016), Node version installed, SPFx version installed, etc...

**Comment by Cmohan** [comment]
1) Technically SharePoint Online but this webpart never got anywhere close to my environment.
2) Again, the webpart was not installed in my environment.
3) from npm list -g --depth=0:
+-- @microsoft/generator-sharepoint@1.9.1
+-- @microsoft/sp-build-web@1.9.1
+-- @pnp/office365-cli@2.0.0
+-- gulp@4.0.2
+-- typescript@3.7.3
+-- webpack@4.41.3
+-- windows-build-tools@5.2.2
`-- yo@3.1.1
4) Edge, Chrome, Vivaldi
5) no other frameworks, just a blank scaffold right out of the generator.

**Comment by andrewconnell** [comment]
Looks like Windows... from your list. In your OP you say "no headers, no footers". The only thing you see in the workbench is the suite bar. There are no normal page headers / footers or left-hand nav in the workbench.

![image](https://user-images.githubusercontent.com/2068657/71111466-8302d280-2197-11ea-8dc9-b777376cf790.png)

What version of Node.js (`node --version`)? 

Did you also [install the self-signed dev cert](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate) after installing the pre-reqs? 

Any errors showing in the console when you run `gulp serve`?

BTW, you've got extra stuff you don't need... these aren't necessary for SPFx (they are included in the project itself:
- @microsoft/sp-build-web
- typescript
- webpack

**Comment by Cmohan** [comment]
Yes, I'm on Windows. The other packages are from other projects that I work on on this machine. The dev cert installed correctly.

Here's what the workbench looks like:
![image](https://user-images.githubusercontent.com/2027643/71112473-6dce7980-2180-11ea-92ba-acbe788836b0.png)

Here's the console errors:
![image](https://user-images.githubusercontent.com/2027643/71112488-76bf4b00-2180-11ea-9868-ca3613f56b35.png)

Highlighted line is the one with the error:
![image](https://user-images.githubusercontent.com/2027643/71112541-93f41980-2180-11ea-9257-60d8c32e6930.png)

**Comment by andrewconnell** [comment]
Appears external JS files are not being loaded in the workbench page... what do you see in the **Network** tab? Anything in the console (not JS console, the command line where you executed **gulp serve**?

**Comment by Cmohan** [comment]
Network tab:
![image](https://user-images.githubusercontent.com/2027643/71113786-2f868980-2183-11ea-864a-4a8327e9f803.png)

Console output of **gulp serve**:
Build target: DEBUG
[10:42:10] Using gulpfile (path to gulp file in project root)
[10:42:10] Starting gulp
[10:42:10] Starting 'serve'...
[10:42:10] Starting subtask 'configure-sp-build-rig'...
[10:42:10] Finished subtask 'configure-sp-build-rig' after 9.2 ms
[10:42:10] Starting subtask 'spfx-serve'...
[10:42:11] Starting server...
Starting api server on port 5432.
Registring api: /workbench
Registring api: */*
[10:42:12] Finished subtask 'spfx-serve' after 2.02 s
[10:42:12] Starting subtask 'pre-copy'...
[10:42:12] Finished subtask 'pre-copy' after 195 ms
[10:42:12] Starting subtask 'copy-static-assets'...
[10:42:12] Starting subtask 'sass'...
[10:42:12] Server started https://localhost:4321
[10:42:12] LiveReload started on port 35729
[10:42:12] Running server
[10:42:12] Opening https://localhost:5432/workbench using the default OS app
[10:42:12] Finished subtask 'copy-static-assets' after 73 ms
[10:42:13] Finished subtask 'sass' after 422 ms
[10:42:13] Starting subtask 'tslint'...
[10:42:16] [tslint] tslint version: 5.12.1
[10:42:16] Starting subtask 'tsc'...
[10:42:16] [tsc] typescript version: 2.9.2
  Request: [::ffff:127.0.0.1] '/workbench'
  Request: '/temp/workbench.html'
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
[10:42:21] Finished subtask 'tsc' after 4.99 s
[10:42:22] Finished subtask 'tslint' after 8.86 s
[10:42:22] Starting subtask 'post-copy'...
[10:42:22] Finished subtask 'post-copy' after 840 μs
[10:42:22] Starting subtask 'collectLocalizedResources'...
[10:42:22] Finished subtask 'collectLocalizedResources' after 3.53 ms
[10:42:22] Starting subtask 'configure-webpack'...
[10:42:28] Finished subtask 'configure-webpack' after 6.52 s
[10:42:28] Starting subtask 'webpack'...
  Request: '/temp/workbench.html'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
[10:42:41] Finished subtask 'webpack' after 13 s
[10:42:41] Starting subtask 'configure-webpack-external-bundling'...
[10:42:41] Finished subtask 'configure-webpack-external-bundling' after 1.04 ms
[10:42:41] Starting subtask 'copy-assets'...
[10:42:41] Finished subtask 'copy-assets' after 25 ms
[10:42:41] Starting subtask 'write-manifests'...
  Request: '/temp/manifestsFile.js.map'
[10:42:49] Finished subtask 'write-manifests' after 7.52 s
[10:42:49] Starting subtask 'reload'...
[10:42:49] Finished subtask 'reload' after 1.25 ms
  Request: '/temp/workbench.html'
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
  Request: '/temp/manifestsFile.js.map'
  Request: '/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'

**Comment by andrewconnell** [comment]
_Stange... appears all JS files in `/temp/workbench-packages/` aren't being served up..._ 

Look in your project, specifically the **temp** folder. Do you see those files? If not, I'd try:
- delete any lock files in the root of your project
- delete the **node_modules** folder
- reinstall all dependencies (**npm install**)
- retry **gulp serve**

Outside of that, any chance there's something installed in your browser blocking JS files?

**Comment by Cmohan** [comment]
Did all that and no luck. Still won't run. Checked all the settings I could think of that might block files but I didn't see anything. I know I've run the workbench successfully before with past projects.

Here's what my **temp** folder contains:
![image](https://user-images.githubusercontent.com/2027643/71118389-e20f1a00-218c-11ea-82f6-f662ca69b653.png)

When I try to open any of the folders I get this:
![image](https://user-images.githubusercontent.com/2027643/71118453-0ec33180-218d-11ea-8823-1c744c39bf86.png)

I'm not sure if that's supposed to happen or not.

**Comment by andrewconnell** [comment]
Those folder icons don't look normal... are you running off a network drive? If so, that's not supported and has known issues.

Or is that folder DEEPLY nested (*looks like you modified that image to hide some of your folder path*)? Not sure what version of Windows that is, but I know Windows has issues with long paths. Maybe try moving it up to a less-deep path.

If not, Those appear to be symbolic or hard links... your machine may not be navigating to the actual folders.

**Comment by Cmohan** [comment]
Ah, it was the fact that I had it on a network drive. I copied the files to the local drive and it loaded the workbench fine. My bad 😃 Thank you for all your assistance!

**Comment by andrewconnell** [comment]
BTW, that's an aspect of Node... nothing to do with SPFx.
