### ISSUE TITLE
Method "GetSitePropertiesByUrl" can't return the new value

### ISSUE THREAD

**Issue by WilliamZheng** [SharePoint/sp-dev-docs#5028]
I am trying to update the "UserCodeMaximumLevel" and "UserCodeWarningLevel" of site property on sharepoint online using CSOM. But I notice that  Method "GetSitePropertiesByUrl" can't return the modify value

Here is the steps:

1. I update the "UserCodeMaximumLevel" and "UserCodeWarningLevel" with below code:

using Microsoft.Online.SharePoint.TenantAdministration;
using Microsoft.SharePoint.Client;

Tenant tenant = new Tenant(ctx);
var site = tenant.GetSitePropertiesByUrl("https://url", true);
tenant.Context.Load(site);
tenant.Context.ExecuteQueryAsync().Wait();
site.UserCodeMaximumLevel = 380.0;
site.UserCodeWarningLevel = 30.0;
site.Update();
tenant.Context.ExecuteQueryAsync().Wait();

2. When I try to get the value, the return value of "site.UserCodeMaximumLevel" and "site.UserCodeWarningLevel" is always the old value

var site = tenant.GetSitePropertiesByUrl("https://url", true);
tenant.Context.Load(site);
tenant.Context.ExecuteQueryAsync().Wait();

Why "GetSitePropertiesByUrl" doesn't works?

Btw, the site property which get from "tenant.GetSiteProperties(0, true);"  is correct.

**Comment by andrewconnell** [comment]
These two properties are related to user code (ie: managed code running in the sandbox). User code is no longer supported in SPO & that service is disabled.

REF: https://blogs.msdn.microsoft.com/sharepointdev/2014/01/14/deprecation-of-custom-code-in-sandboxed-solutions/

**Comment by WilliamZheng** [comment]
@andrewconnell  But why "tenant.GetSiteProperties(0, true)" is still working?  Any different with "GetSitePropertiesByUrl"?

**Comment by WilliamZheng** [comment]
And the interest thing is that, the method "GetSitePropertiesByUrl" can reflect the new value when we change the value in the UI page.

**Comment by andrewconnell** [comment]
Not sure, but regardless it doesn't matter as those properties are no longer useful because user code is no longer enabled in SPO.
