### ISSUE TITLE
Updating a group owner with SharePoint REST API does not work

### ISSUE THREAD

**Issue by KEMiCZA** [SharePoint/sp-dev-docs#5031]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When updating the group object in SharePoint REST API, the group owner should be updated. 

For more information see https://github.com/pnp/pnpjs/issues/957

#### Observed Behavior
REST call is successfully executed but the group owner is not updated.

#### Steps to Reproduce
Tested on SPO & SP2019

Request URL: /_api/web/sitegroups(5)
Request Method: POST
Status Code: 204
Headers: content-type: application/json;odata=verbose;charset=utf-8
Request Body:
```json
{
    "__metadata": {
        "type": "SP.Group"
    },
    "Owner": {
        "PrincipalType": 1,
        "Id": 6
    }
}
```

It seems that a _SetUserAsOwner_ method was provided on the SP.Group object and this method does work for updating the group owner, but unfortunately it only works for a user id as argument and not a group id. Perhaps implement a _SetGroupAsOwner_ on the SP.Group object?

A workaround exists by using the _/vti_bin/client.svc/ProcessQuery service ([example implementation](https://github.com/pnp/pnpjs/issues/957#issuecomment-565484501)).

**Comment by andrewconnell** [comment]
@JeremyKelley

**Comment by JeremyKelley** [comment]
After review, since there's a workaround we won't be making a change here.  Please use the suggested workaround to make this work.
