### ISSUE TITLE
SPFx Command Set Extension does not fire onListViewUpdated when navigating to/from folders

### ISSUE THREAD

**Issue by rob-windsor** [SharePoint/sp-dev-docs#5034]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The onListViewUpdated event should fire when the user navigates to or from a folder in a list view. 

#### Observed Behavior

The onListViewUpdated event does not fire when the user navigates to or from a folder in a list view.

#### Steps to Reproduce

- Create a command set extension 
- Add an alert dialog in the `onListViewUpdated` event handler
- Test the command set extension 

The alert dialog will show on initial load or when selecting/deselecting items but it will not show when navigating to/from folders.

This bug is related to #4870 

![Folder Issue](https://user-images.githubusercontent.com/5740654/71101049-1205ef80-2184-11ea-97c0-331ce709438f.gif)

**Comment by joelfmrodrigues** [comment]
Just experienced the same on a client tenant

**Comment by ioan-agopian** [comment]
We are experiencing the same issue on several tenants. 
Is a fix planned?

**Comment by kemesfun** [comment]
@rob-windsor I am not able to repro this issue, let me know if this still happens.
