### ISSUE TITLE
SPComponentLoader.loadScript init.js in application extension breaks OOB "Edit Source"

### ISSUE THREAD

**Issue by menu4web** [SharePoint/sp-dev-docs#5035]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

"Edit Source" button on a rich text field should open HTML Source editor.

#### Observed Behavior

"Edit Source" freezes after opening.

#### Steps to Reproduce

1. Create SPFx application extension.
2. Add in ApplicationCustomizer.ts: import { SPComponentLoader } from '@microsoft/sp-loader';
3. Add in ApplicationCustomizer.ts:  SPComponentLoader.loadScript('/_layouts/15/init.js', { globalExportsName: '$_global_init' }); to onInit method;
4. Bundle and package the solution;
5. Deploy to apps store and install on a test site collection.

"Edit Source" will not work on the test site collection.

**Comment by menu4web** [comment]
I there any update on this issue? What do these labels mean: area:other type:question?

**Comment by westleyMS** [comment]
Is there any update on this?
