### ISSUE TITLE
SP2019 - React Framework Application Customizer

### ISSUE THREAD

**Issue by FlamingFox911** [SharePoint/sp-dev-docs#5036]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Does anyone know if a React Framework exists for Application Extensions built for SP 2019 or if it is in the pipeline? I tried generating one, but the option does not exist with the latest yo generator and I can't find any reference of it online.

Thanks in advance.

**Comment by andrewconnell** [comment]
_Assuming you're talking about application customizers..._

No, there's nothing that has been shared. You can easily use React though... within an app customizer's placeholder. The placeholder, like a web part, is just a DIV so you have access to the `domElement` and can use the same `ReactDOM.render()` method, passing in a React component & reference to the DIV
