### ISSUE TITLE
Query operators case is invalid

### ISSUE THREAD

**Issue by Wawawum** [SharePoint/sp-dev-docs#5037]
#### Category
- [ ] Question
- [x] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

In the page [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests):
In the "OData query operators supported in the SharePoint REST service" paragraph, numeric and string comparison operators should not have the first letter capitalized.

Therefore, operators should be: lt le gt ge eq ne.

#### Observed Behavior

Using operators with the a capitalized first-letter returns an error when using the $filter OData query operation.

**Comment by Dennis-LZ** [comment]
@Wawawum you are right, the OData query operators supported in the SharePoint REST service as below.

**Numeric comparisons**: lt le gt ge eq ne

**String comparisons**: startswith substringof eq ne

**Date and time functions**: day() month() year() hour() minute() second()

**Dennis Guo
Microsoft SharePoint Community Support**
