### ISSUE TITLE
sp-filepicker component

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#504]
#### Category
- [x] Question

I see the  document web part is using a react component named **sp-filepicker**. Are there plans to release this to the public as I'd hate to program this myself when you have done the heavy lifting already.

**Comment by patmill** [comment]
Similar to the people-picker request.  Can you open a user-voice request for this?  Trying to keep the issues list filled with open issues, rather than feature requests.  Thanks,  https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/
