### ISSUE TITLE
SPFx Extension not loading at all

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-docs#5041]
I ported this code over, but modified it so that it works (https://github.com/bcameron1231/SharePoint-Framework/tree/master/react-hubsite-securitytrim-navbar)

I added the "includeClientSideAssets: true" so that I do not have to deploy to CDN, renamed the CDN path to the default <! CDN PATH HERE/> and have got it working perfectly fine on localhost using gulp serve

I have uploaded Web parts perfectly fine to the AppCat, I uploaded the extension and then added as an App to the Hub site I am working on.

I console log inside my onInit() method to check if the Extension has been loaded. Dev tools show that no errors (from my Ext) are present.

How can I get this working? It is my first extension but I have got web parts loaded fine

**Comment by OS-Lee** [comment]
Here are my suggestions for troubleshooting.

Try to use developer  toll(F12) to check the error information, for example:  "includeClientSideAssets": true will load the js from your local, will get error if 'gulp server' not run similar as below.

![image](https://user-images.githubusercontent.com/40845109/71222679-620fbe00-230c-11ea-8b45-80ac79e7dc97.png)

If 'gulp server' is running and you had added the extension app to your hub site, try to debug the extension follow official guideline [Here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages#debug-extensions-using-serve-configuration)

![image](https://user-images.githubusercontent.com/40845109/71222992-72746880-230d-11ea-9ec0-2ded5011962a.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by robiharid** [comment]
Thanks for getting back to me @OS-Lee 

I have includeClientSideAssets on all of my webparts, which run without gulp-server and load the files locally from AppCat? We do not want to expose our CDN of this tenant.

I also have a lot of errors stemming from sp-pages but none of them say localhost. It says the navbar extension has been added to the AppCat ("GOod news you already have this").

I have the sample debug serve config.. should I change this?

The github repo I forked said to use this `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"1859a5f8-d2fc-4c55-91ba-a097edf6da00":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"NavHeading":"Sites"}}}` when running on localhost but does not mention it when deploying live.
![image](https://user-images.githubusercontent.com/16907484/71247104-fe878f80-230f-11ea-9e05-9d2a1fea4ac0.png)
![image](https://user-images.githubusercontent.com/16907484/71247182-22e36c00-2310-11ea-903b-f09540262e47.png)
![image](https://user-images.githubusercontent.com/16907484/71247205-2b3ba700-2310-11ea-9ed0-dd166d7fedf2.png)

**Comment by andrewconnell** [comment]
When you packaged your solution, you must include the `--ship` or `-p` flag when running **gulp bundle** & **gulp package-solution**. Otherwise, you will package in debug mode which will then deploy components that are expected to be loaded from localhost.

**Comment by robiharid** [comment]
> When you packaged your solution, you must include the `--ship` or `-p` flag when running **gulp bundle** & **gulp package-solution**. Otherwise, you will package in debug mode which will then deploy components that are expected to be loaded from localhost.

Good check, but the first thing I do in all new projects is replace the build script in package.json
`
    "build": "gulp clean && gulp bundle --ship && gulp package-solution --ship",`

This is the standard I used for all my web parts.

**Comment by andrewconnell** [comment]
First step: try following the tutorial in the docs and get a brand new extension working rather than porting an existing solution.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

If that works, then there's an issue with the project you're trying to port.
