### ISSUE TITLE
accept = 'application/json;odata=nometadata'  gives results in XML; only get JSON with odata=verbose

### ISSUE THREAD

**Issue by repton-infinity** [SharePoint/sp-dev-docs#5045]
e.g. in PowerShell, suppose $url is a suitable search API query URL.

If I do this, I get json results:

$headers = @{ accept = 'application/json;odata=verbose' }
Invoke-WebRequest -Uri $url -Headers $headers -UseDefaultCredentials

but if I do this, I get XML results:

$headers = @{ accept = 'application/json;odata=nometadata' }
Invoke-WebRequest -Uri $url -Headers $headers -UseDefaultCredentials

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#search-rest-results-format)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
This is by design, by default, it will return XML data. If want to get Json data format, use this:

accept: application/json;odata=verbose

If don't want any metadata, use this:

accept: application/json;odata=nometadata

Reference:
[Making Your REST Calls Simpler by Changing the Metadata Setting](https://sympmarc.com/2016/05/02/making-your-rest-calls-simpler-by-changing-the-metadata-setting/)

**Comment by repton-infinity** [comment]
In my experience with SharePoint 2013, if I use

accept: application/json;odata=nometadata
I get XML in response. I only get JSON response if I specify odata=verbose.
If this is by design then the docs should mention this.
