### ISSUE TITLE
Context correction 

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#5049]
This below statement under the Install NodeJS from below mentioned URL
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

The below highlighted context is misleading, please correct this statement  
**Current statement**
 Important
The current supported LTS version of NodeJS for the SharePoint Framework is both Node.js v10.x and **Node.js v12.x. ### **Node.js v12.x is not currently supported****. Notice that 9.x or 11.x versions are currently not supported with SharePoint Framework development

Refer the yesterday commit https://github.com/SharePoint/sp-dev-docs/commit/27b3b50d0526ca626078d8cf74e71188f2a9a786

**Correct statement**

The current supported LTS version of NodeJS for the SharePoint Framework is both **Node.js v8.x** and **Node.js v10.x. **Node.js v12.x is not currently supported****. Notice that 9.x or 11.x versions are currently not supported with SharePoint Framework development
 

#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [X] Context

**Comment by andrewconnell** [comment]
I don't understand what you're saying is incorrect in the doc. The current doc is correct.

**Comment by PrasadKasireddy** [comment]
Vesa was correct the document on 21st dec
https://github.com/SharePoint/sp-dev-docs/commit/e473999f1af15be9af994be9cd38955391c21ef9

**Comment by andrewconnell** [comment]
Node 12 is not supported at the present time. The update to the doc was done by mistake. The current published version of the doc is correct.
