### ISSUE TITLE
Context correction

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#5050]
The below statement is confusing that IS Node.JS v12.x is supported or not?
The statement under the Install NodeJS 
Important
The current supported LTS version of NodeJS for the SharePoint Framework is both Node.js v10.x and Node.js v12.x. Node.js v12.x is not currently supported. Notice that 9.x or 11.x versions are currently not supported with SharePoint Framework development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Node 12 is not supported.

The only supported versions are Node 8 & Node 10. Node 10 is recommended unless you are working with SPFx 2016
