### ISSUE TITLE
Cannot test SPFX extension on classic page

### ISSUE THREAD

**Issue by gloshkaj** [SharePoint/sp-dev-docs#5055]
Category
- [x ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
I am writing a spfx extension to customizeaster page navigation. I am trying to test the extension on a classic site. But I am not being promoted to load debug scripts after running gulp serve. Are SPFX extensions incompatible with classic sites?
Expected or Desired Behavior: Prompt to load debug scripts comes up when loading classic site when running gulp serve.

Observed Behavior

After running gulp serve prompt to load debug scripts does not show up.

Steps to Reproduce

Create an SPFX extension and set it so that the URL of a classic site loads. Then run gulp trust-dev-cert and gulp serve.

**Comment by Dennis-LZ** [comment]
Here is a SPFx application customizer solution works on Classic sites and Modern sites.

**Solution**: [spfx-global-navigation](https://github.com/tom-daly/spfx-global-navigation)

Classic site deployment process is different. It’s not an app / app package. The solution creates a separate JavaScript file that is uploaded to your site and linked via a site script link.

To generate the latest JavaScript run the build.cmd. That will generate both a new .sppkg for Modern sites and the .js file for Classic sites. After a successful build, the top-navigation.js file will be in the classic-dist folder.

Then upload the file to a library, alternatively you could host this file on a CDN if the plan is to use it on more than 1 site collection. And we can use SP-Editor for Chrome to attach a site script link.

The following article for your reference.

[SPFx Application Customizer that works on Classic SharePoint Sites](https://thomasdaly.net/2019/08/28/spfx-application-customizer-that-works-on-classic-sharepoint-sites/)

**Dennis Guo
Microsoft SharePoint Community Support**
