### ISSUE TITLE
Tenant side spFx Application Customizer onInit not consistent

### ISSUE THREAD

**Issue by monzerhijazi** [SharePoint/sp-dev-docs#5056]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Hi I'm expecting a Tenant deployed Application Customizer to run onInit every time a site is visited. The Application Customizer runs JS and displays a Dialog.

#### Observed Behavior

It always runs on a full page refresh, but randomly fails when moving from site to site using top navigation.

#### Steps to Reproduce

Open sharepoint site. Use top navigation to go to another site. No console errors are displayed.

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
SP implements a page router ([this post talks about it](https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/)) to implement partial page routing. [Elio has written about how to address navigation events with extensions](https://www.eliostruyf.com/handling-page-creation-events-spfx-application-customizer/) as well... suggest you read up on those.

This isn't a bug, it's just how SP works
