### ISSUE TITLE
Can't get site fields using SharePoint Online CSOM

### ISSUE THREAD

**Issue by AntonGavrin** [SharePoint/sp-dev-docs#5059]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I tried to get site fields using SharePoint Online CSOM (C# and JavaScript) and got an error.
Microsoft.SharePointOnline.CSOM version 16.1.19515.12000 is being used.
The desired outcome is site fields.

#### Observed Behavior
For site fields, upon calling ClientContext ExecuteQuery, a server exception is generated:
For C#:
`Microsoft.SharePoint.Client.ServerException
  HResult=0x80131500
  Message=Input string was not in a correct format.
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
`

For JavaScript:
`$6_1: SP.ClientRequest {$18_0: Array(4), $s_0: {…}, $0_0: SP.ClientContext, $P_0: SP.ClientQueryInternal, $$d_$3K_0: ƒ, …}
$2I_2: "Input string was not in a correct format."
$2Q_2: undefined
$1H_2: -1
$2G_2: null
$2F_2: "System.FormatException"
$2E_2: undefined
$1I_2: "fff9249f-c08e-9000-8c8d-90ec1fde01e7"
$w_2: Sys.Net.XMLHttpExecutor {_webRequest: Sys.Net.WebRequest, _resultObject: null, _xmlHttpRequest: null, _responseAvailable: true, _timedOut: false, …}
__proto__: Object
`

#### Steps to Reproduce
Just try to run this code:
using (var ctx = new ClientContext("SharePoint Online site collection url"))
{
                ctx.Credentials = new SharePointOnlineCredentials(userName, securePwd);

                Web web = ctx.Web;

                web.Context.Load(web.Fields);

                web.Context.ExecuteQuery();
}

Or this:

_var ctx = SP.ClientContext.get_current();
var fields = ctx.get_web().get_fields();
ctx.load(fields);
ctx.executeQueryAsync(() => console.log('done'), (s, a) => console.log(a));_

#### Submission Guidelines
Looks like something wrong on SharePoint Online server side.

Thank you,
Anton

**Comment by OS-Lee** [comment]
Can't reproduce in my online environment.
![image](https://user-images.githubusercontent.com/40845109/71452331-fc657b00-27be-11ea-8018-f34dcefc4ecd.png)

![image](https://user-images.githubusercontent.com/40845109/71452336-04bdb600-27bf-11ea-9f38-fd73b4be9e8e.png)

Try to test in other site or a new site to check is this happens for specific site.

My test code:

`string SiteURL = @"https://tenant.sharepoint.com/sites/lee/";

            var login = "user@tenant.onmicrosoft.com";
            var password = "password";

            var securePassword = new SecureString();

            foreach (char c in password)
            {
                securePassword.AppendChar(c);
            }
            SharePointOnlineCredentials onlineCredentials = new SharePointOnlineCredentials(login, securePassword);

            using (var ctx = new ClientContext(SiteURL))
            {
                ctx.Credentials = onlineCredentials;
                Web web = ctx.Web;
                web.Context.Load(web.Fields);
                web.Context.ExecuteQuery();
                Console.WriteLine(web.Fields.Count);
            }`

**Comment by AntonGavrin** [comment]
Hi Lee,
So I tested on three tenants. On my tenant i have old site and I reproduced this issue. Then I created two new site collections with STS#0 and STS#3 templates and cannot reproduce this issue. I tested on my customer's tenant and cannot reproduce this issue, but yesterday I saw it. Finally I tested on my colleague's tenant: I reproduced it on one old site, but cannot reproduce on new created site and on another old site. It is very strange.

Thank you,
Anton

**Comment by RafaMaVa** [comment]
Hi,
I have the same problem getting the columns of the site. I have tried on different tenants and it shows the same error. The version of SPO Management Shell is from December 2019.

Thanks!

**Comment by OS-Lee** [comment]
Hi,

Does rest api has same error?

`/sites/yoursite/_api/web/fields`

and try to filter to find the issue one.

`/sites/yoursite/_api/web/fields?$filter=StaticName%20eq%20%27Categories%27`

**Lee
Microsoft SharePoint Community Support**

**Comment by AntonGavrin** [comment]
Hi Lee, I'm sorry, I was on vacation.
So, I retested it with REST API and got the same error for /sites/yoursite/_api/web/fields:
`<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-1, System.FormatException</m:code>
<m:message xml:lang="en-US">Input string was not in a correct format.</m:message>
</m:error>`

If I use filter (for example Category field), I didn't receive this error.

**Comment by abdollahkahne** [comment]
@AntonGavrin  If it worked with filter but doesn't work without it , I think possibly you have a problem with one of the site columns. Try to find that column(s)( and get ride of it in some way)

**Comment by abdollahkahne** [comment]
As an alternative way you may try for diagnosing is to use other query customization like `$orderBy` or  `$select.`
