### ISSUE TITLE
Adding additional webpart within a project after project is deployed doesn't update the webpart list

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#506]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
New webparts added into the project after deployed should be reflected on the webpart adder on both classic page & modern page.

#### Steps to Reproduce
- Create a new SPFX project with the sample helloworld webpart
- Add the secondary webpart using `yo @microsoft/sharepoint` code as usual before any deployment to site
- `gulp bundle --ship` and `gulp package-solution --ship` on the project, then deploy to site (this should work)
- Create the third webpart and try to redeploy with updated solution version (both cdn files and app catalogue is updated). (`gulp clean`, `gulp bundle ---ship`, `gulp package-solution --ship`)
- Expect the third webpart isn't coming out on the webpart add option.

Tested on SPFX GA 1.0 within two SP environments.

**Comment by jonathanhotono** [comment]
@iclanton any ETA on when this bug will be fixed? I think it's quite normal to add additional webpart on existing deployed site.

**Comment by iclanton** [comment]
@chakkaradeep is going to look at this.

**Comment by chakkaradeep** [comment]
@jonathanhotono I tried your steps and unable to repro. I get all the three web parts in the toolbox to add. Can you make sure you are updating the app at the site where you installed?

**Comment by jonathanhotono** [comment]
@chakkaradeep , still getting this issue however I found how to fix this.
Basically if the spfx solution requires to add an app, I will need to remove the installed spfx app manually first then re-add the app again to pick up the new webpart.

**Comment by huynp** [comment]
Have the same issue when I add new webpart and redeployed the package.  The webpart never show up until you remove the app from site content and re-add app again.

**Comment by juliemturner** [comment]
I had this happen to me once but it was because I didn't update the version in the package-solution.json file.  Now I change that version number every time I deploy just to make sure that everything I've done gets updated.

**Comment by jonathanhotono** [comment]
Yep I can confirm it works now by updati g the version number => go to classic experience => update the app manually. Closing this.
