### ISSUE TITLE
Making a submenu in the top and left navigation using SPFX in modern

### ISSUE THREAD

**Issue by gloshkaj** [SharePoint/sp-dev-docs#5061]
Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to make spfx extensions that include submenus as part of the top navigation? This is a requirement as part of migrating existing submenus in classic sites.

**Comment by andrewconnell** [comment]
It sounds like you're asking about the suite bar. No, customizations to the suite bar are not supported.

You can use an app customizer spfx extension to add a top placeholder that contains your additional navigation elements though.
