### ISSUE TITLE
SPClientBatch not found in @microsoft/sp-http

### ISSUE THREAD

**Issue by fussytroll** [SharePoint/sp-dev-docs#5062]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Availability of beginBatch method on SPHttpClient class as per documentation

#### Observed Behavior

I am using
node@10.14.0
npm@6.4.1
@microsoft/generator-sharepoint@1.9.1 
As per previous posts i expected beginBatch method to be available but it is not. 
Is it still in Beta ?
if it is not in GA what alternatives can i use?

Thanks

#### Steps to Reproduce

Create React WebPart project using yo @microsoft/sharepoint
try 
import {SPHttpClientBatch} from '@microsoft/sp-http'
or 
trying using beginBatch method on SPHttpClient object
Both fail with error indicating that beginbatch and SPHttpClientBatch do not exist

Thanks for your contribution! Sharing is caring.

**Comment by Dennis-LZ** [comment]
Please create a new solution and in the generator add the flag as:

`yo @microsoft/sharepoint --plusbeta`

![Untitled](https://user-images.githubusercontent.com/55479607/71575663-c6125d80-2b28-11ea-997e-2e52fb34a1bb.png)

Refer to the similar thread here: [#2385](https://github.com/SharePoint/sp-dev-docs/issues/2385)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by andrewconnell** [comment]
A more complete answer is...

@fussytroll said:
> Is it still in Beta ?

Yes... it's in developer preview

@fussytroll said:
> if it is not in GA what alternatives can i use?

There is no GA option for using the batch endpoint with the SP REST API in the SPFx API. I'm not certain if you can use the Graph REST API's batch support with SPFx entities or not, but I believe you can (you'll just have to test it to confirm).

**Comment by fussytroll** [comment]
Thank you very much, for taking the time to answer my query.
fussytroll

On 31 Dec 2019, at 12:59, Andrew Connell <notifications@github.com<mailto:notifications@github.com>> wrote:


A more complete answer is...

@fussytroll<https://github.com/fussytroll> said:

Is it still in Beta ?

Yes... it's in developer preview

@fussytroll<https://github.com/fussytroll> said:

if it is not in GA what alternatives can i use?

There is no GA option for using the batch endpoint with the SP REST API in the SPFx API. I'm not certain if you can use the Graph REST API's batch support with SPFx entities or not, but I believe you can (you'll just have to test it to confirm).
