### ISSUE TITLE
Generic Link

### ISSUE THREAD

**Issue by eliasm3075** [SharePoint/sp-dev-docs#5064]
"REST API reference and samples" link in "See Also" section is a generic link to https://msdn.microsoft.com/library and doesnt specify where the relevant samples and references can be found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Looks like a bad link... will get this fixed... it shouldn't be in the list of additional resources.
