### ISSUE TITLE
Delay in SPFx App customizer extension loading. Loads after the page and other elements load.

### ISSUE THREAD

**Issue by jithil89** [SharePoint/sp-dev-docs#5066]
Is this resolved yet ? I created a SPFx app customizer to hide a certain section in the pages. But due to the delay, the sections load first and then get hidden. I believe this is a replacement for custom action. In that case, this should load first. I read that the onInit() function is fired before DOM is loaded.
@waldekmastykarz @estruyf @thechriskent , please advice

_Originally posted by @jithil89 in https://github.com/SharePoint/sp-dev-docs/issues/2909#issuecomment-527313734_

**Comment by andrewconnell** [comment]
@jithil89 said:
> I read that the onInit() function is fired before DOM is loaded.

That's not correct... `onInit()` in SPFx components runs before the component is rendered on the page. This doesn't correspond with the DOM `onLoad` event. the DOM loads and then the SPFx components are bootstrapped and loaded.

**Comment by andrewconnell** [comment]
@kapilmehtagit said:
> I would like to understand if the delay between page render and SPFx application customizer availability could be reduced.

No... there are no facilities to control this provided by the SPFx API.

As the other issue indicates, MSFT is adding the ability in SPFx v1.10 to "block space" for an app customizer so the page doesn't reflow when the extension renders, but you can't change how the events work.

**Comment by sebastienlevert** [comment]
I still think that there is value in having the extensions load earlier in the lifecycle. The "block space" feature will be great for some scenarios but for some others, we will still get a flickering UI. But for now, the dedicated space for the extensions is a great start!
