### ISSUE TITLE
Can we make changes to Suite Navigation using SPFX

### ISSUE THREAD

**Issue by Fnu-Avi** [SharePoint/sp-dev-docs#5067]
- [x] Question
- [ ] Bug
- [] Enhancement

Can we make changes to the main header of the SharePoint site? In my case, I need to make changes to the Suite Navigation (which is the top most part of the page - can be seen in the image).
Link: [Image](https://imgur.com/a/k4vRYfd)

I need to remove the logo from here only for a particular site (not from the whole tenant). Moreover, I need to add more icons with functionalities on the right side (currently having only 4-icons: Notifications, Settings, Help and Account Manager).

Insights on this appreciated.

Thanks & Regards,
~Avi

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
No, SPFx does not provide an API to customize the suite bar. Anything you do here programmatically would be considered not supported as it would be DOM manipulation.

Office 365 does have options for customizing the logo and color of the suite bar though... but it's outside the scope of this forum.
