### ISSUE TITLE
Fetching view count, like count and comment count using SP REST api . 

### ISSUE THREAD

**Issue by HadrienAllemon** [SharePoint/sp-dev-docs#5072]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I have some requirement for a development on O365 . I'm trying to use sharepoint REST api from a webpart to retrieve the view count, like count and comment count of every news posted on the current site collection. I know that the view count is possible to get via the search api and the like count via the list/getByTitle function of the REST api. However after hours of research and trials I haven't been able to 

1. Find the comment counts of the news of the site.
2. Get the view count and the like count in a single call. 

So before losing my mind trying things randomly, I wanted invoke in the wisdom of some more experienced sharepoint developer. 

Thanks a lot for reading :)

**Comment by OS-Lee** [comment]
Hi,

The requirement had answered [here](https://www.eliostruyf.com/getting-likes-and-comments-from-modern-pages/).

Post

`/_api/web/lists/getbytitle('Site%20Pages')/RenderListDataAsStream`

Headers:

`accept: application/json;odata=verbose
content-type: application/json;odata=verbose`

Body( the id is news page item id):

`{
  "parameters": {
    "ViewXml": "<View><ViewFields><FieldRef Name=\"_LikeCount\" /><FieldRef Name=\"_CommentCount\" /></ViewFields><Query><Where><Eq><FieldRef Name=\"ID\"/><Value Type=\"Number\">6</Value></Eq></Where></Query><RowLimit /></View>"
  }
}`

**Lee
Microsoft SharePoint Community Support**

**Comment by HadrienAllemon** [comment]
@OS-Lee Thanks a lot for the answer. I successfully managed to fetch the data I needed using two different calls, however  something bothers me: 

For some of the most recent article, every viewcount returns "null" 

![image](https://user-images.githubusercontent.com/34393917/71725402-09741100-2e34-11ea-9a05-96b7d0e7fcf0.png)

Even tough the article is 3 days old. 

Does the viewcount only update for old enough articles or is it like in SharePoint 2013 where least-popular article do not get their stats automatically updated ? 

Thanks a lot.

**Comment by OS-Lee** [comment]
Hi,
How you search the news? 

The search should crawled the page after 24 hours.

Try with path property.

`/_api/search/query?querytext=%27Path:https://xxx.sharepoint.com/sites/communication1/SitePages/LeeNewsTest.aspx%27&$selectproperties=%27Title,path,ViewsLifeTime,ViewsLifeTimeUniqueUsers,ViewsRecent,ViewsLast1Day%27`

**Lee
Microsoft SharePoint Community Support**
