### ISSUE TITLE
themeProvider.tryGetTheme does not seem to work :(

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#5075]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The tutorial on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds does not work in my webpart. 

#### Observed Behavior

The tryGetTheme method always returns _undefined_: 
```
    // If it exists, get the theme variant
    this._themeVariant = this._themeProvider.tryGetTheme();
```

Secondly, the _themeChangedEvent_ is never triggered (when changing the theme in the SharePoint user interface): 
```
    // Register a handler to be notified if the theme variant changes
    this._themeProvider.themeChangedEvent.add(this, this._handleThemeChangedEvent);
```

I'm not sure whether I'm doing something wrong here or whether the functionality is broken (I'm using SPFx 1.9.1). 

I'd appreciate a working example of how to get the current theme colors and react on the event when the user changes the page theme (including when the user previews it).

**Comment by Dennis-LZ** [comment]
Please check the example code below.

```
import { ThemeProvider, ThemeChangedEventArgs, IReadonlyTheme, ISemanticColors } from '@microsoft/sp-component-base';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';

export default class BasicPlainSectionBackgroundExampleWebPart extends BaseClientSideWebPart<void> {
  private readonly _textContent: string = 'This web part has support for section backgrounds and will inherit its background from the section';
  private _themeProvider: ThemeProvider;
  private _themeVariant: IReadonlyTheme | undefined;

  public render(): void {
    // See https://github.com/OfficeDev/office-ui-fabric-react/wiki/Theming
    const semanticColors: Readonly<ISemanticColors> | undefined = this._themeVariant && this._themeVariant.semanticColors;

    const style: string = ` style="background-color:${semanticColors.bodyBackground}"`;
    this.domElement.innerHTML = `<p${'' || (this._themeProvider && style)}>${this._textContent}</p>`;
  }

  protected onInit(): Promise<void> {
    // Consume the new ThemeProvider service
    this._themeProvider = this.context.serviceScope.consume(ThemeProvider.serviceKey);

    // If it exists, get the theme variant
    this._themeVariant = this._themeProvider.tryGetTheme();

    // Register a handler to be notified if the theme variant changes
    this._themeProvider.themeChangedEvent.add(this, this._handleThemeChangedEvent);

    return super.onInit();
  }

  /**
   * Update the current theme variant reference and re-render.
   *
   * @param args The new theme
   */
  private _handleThemeChangedEvent(args: ThemeChangedEventArgs): void {
    this._themeVariant = args.theme;
    this.render();
  }
}
```

I suggest you check the solution with source code from here:  [Supporting section backgrounds in your web parts](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/section-backgrounds)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by frevds** [comment]
Yes, this is the code I was using and afaik this is exactly also what I'm doing, but as I said, this code does not work. I will try the sample project to see whether it works there and if so, where the differences are. For me, the very first line (in onInit) throws already an exception (the this.context is undefined, because the super.onInit has not been called yet (last line)). If I do it afterwards (e.g. in a .then), no exception occurs, but neither do I get a current theme (tryGetTheme just returns undefined), nor do I get change events.

**Comment by Dennis-LZ** [comment]
Please check the serve.json file in config folder and set the "initialPage" to "https://tenant.sharepoint.com/_layouts/workbench.aspx". Then run "gulp serve" to check if it works.

![Untitled](https://user-images.githubusercontent.com/55479607/71965191-2fd1ec00-323a-11ea-82e0-5da9fa741614.png)


**Dennis Guo
Microsoft SharePoint Community Support**
