### ISSUE TITLE
Render method called twice

### ISSUE THREAD

**Issue by sameerjmansuri** [SharePoint/sp-dev-docs#5076]
Hi,

I am facing an issue where the render method is called twice in spfx webpart. This happens only when navigating from a non webpart page to spfx webpart page. If we navigate from non webpart pate to spfx webpart page it is firing render method two times.

I am using no javascript framework.

Howerver, I found almost same issue in below link.
https://github.com/SharePoint/sp-dev-docs/issues/1305

I tried the below solution which is given in above issue but there is no luck.

public render(): void {
    if (!this.renderedOnce) {
      this.domElement.innerHTML = `bla bla bla`;
    }
  }

In my solution i am calling my custom methods in render method which binding controls, events and binding data to datatable. All these method are called twice and my solution is not working as expected.

Also my bootstrap loader is always visible if the render method called twice. The loader wont hides if render called twice.

If we reload the spfx webpart page then everything is working fine and render method fires only once. 

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If we navigate from non webpart pate to spfx webpart page it should fire render method only once.

#### Observed Behavior

If we navigate from non webpart pate to spfx webpart page it fires render method twice.

#### Steps to Reproduce
Add a alert in render() method.
Deploy solution and add in page.
Add the page link in let navigation.
Navigate to home and then navigate to spfx webpart page.
You will see two alerts one after another.

**Comment by patmill** [comment]
You should assume that render can be called multiple times.  There is a property (this.renderedOnce) that will let you know if this is the first time that render is called.

**Comment by sameerjmansuri** [comment]
@patmill Property (this.renderedOnce) doesn't work. The render() is called twice and Property (this.renderedOnce) is false in each call. It seems that it is a totally new instance call of class. Not just render() but constructor() is also called twice. 
This issue occurs when I come to my page(SPFX webpart page) from other page using quick launch Please help
