### ISSUE TITLE
SharePoint Framework - SPFX Webpart is not visible under the root sitecollection

### ISSUE THREAD

**Issue by mhijazi** [SharePoint/sp-dev-docs#5077]
Hey all,

I have SharePoint 2019 (on-prem) and one web app; one root site collection for Intranet Portal and other one /sites/apps for the app catalog, where I deployed react-script-editor (Modern Script Editor).

The issue is that the webpart is only visible under the apps site collection but NOT under the root site collection.

Any help???

Thank you.

**Comment by Jerry0527** [comment]
Can you see the web part in "Apps you can add" in the root site collection ? If that is the case, please add the app and create a modern page to add the web part.

**Comment by andrewconnell** [comment]
The app must be installed on each site collection where you want to use it. The term you are using, "root site collection" is simply a description of the site collection. Site collections are not hierarchal... think of them all at the same flat level.
