### ISSUE TITLE
SPFx v1.10 Project Cannot be created

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5083]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SPFx v1.10 Yeoman generator creates a new project.

#### Observed Behavior

SPFx v.10 Yeoman generator throws an error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@microsoft%2fsp-search-extensibility - Not found
npm ERR! 404
npm ERR! 404  '@microsoft/sp-search-extensibility@1.10.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@microsoft/sp-application-base'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

#### Steps to Reproduce

`yo @microsoft/sharepoint`.
I'm trying to scaffold a web part project.

**Comment by varunms365** [comment]
Not Found - GET http://registry.npmjs.org/@microsoft/sp-search-extensibility

**Comment by lucabandMSFT** [comment]
Working on it right now.. We had an issue on the process of publishing that specific package on NPM.

**Comment by KevinTCoughlin** [comment]
The package has been published at https://www.npmjs.com/package/@microsoft/sp-search-extensibility.

**Comment by AJIXuMuK** [comment]
The fix is confirmed!
Thanks!
