### ISSUE TITLE
Problems with Node.js 12 and gulp 3

### ISSUE THREAD

**Issue by BigEaseGueldi** [SharePoint/sp-dev-docs#5089]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

> As stated [here](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md), SPFx should work with node 12 LTS. 

#### Observed Behavior

Because of [this issue](https://github.com/gulpjs/gulp/issues/2324), I can't build an SPFx 1.10 project.

It results in:
```
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
```

#### Steps to Reproduce

Use SPFx 1.10 with node.js version 12.14.1.

**Comment by andrewconnell** [comment]
Node 12 is **not** supported at this time. The [release notes](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.10-release-notes#what-is-deprecated--getting-removed) for v1.10 state that it will be added in the next release.

You should use Node v10 for SPFx v1.10. Node v8 will also work.

I'm aware the docs state Node 12 is recommended... that is not correct & I'm fixing it now...

**Comment by patmill** [comment]
Thanks for pointing to the doc.  The doc is incorrect.  I've kicked off an update to it to only mention Node 8 and 10.  The version of gulp required for node 12 causes issues with the toolchain at the moment .  We're working on support in the future.
