### ISSUE TITLE
Publishing new version of sppkg does not take new settings

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#509]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
After publishing an sppkg to my SharePoint (v.1.0.0 and 1.0.0.0) which pointed to load the script file from this cdn: https://my.cdn.com/webpartbundlefile1.js
Everything works well.
Next, we built a new version 1.0.1 and 1.0.0.1, in this one we changed the file location to be https://my.cdn.com/webpartbundlefile2.js

We expect all existing pages with the web part, as well as new pages adding the web part to now use the new JS file "webpartbundlefile2.js"

#### Observed Behavior
Loading the page and refreshing will alternate between loading the old JS file and the new JS file, with no apparent logic.
It will randomly load one of these files, not consistent. Even after clearing browser cache this behavior was observed.
What is most strange, this behavior was also observed on pages that the web part was added to after the new version was in the catalog.
This happens on both classic pages and modern pages.

#### Steps to Reproduce
1. publish your web part to a CDN:
2. use gulp --ship to build everything in the temp/deploy folder, publish these files to your CDN
3. use gulp package-solution --ship to get a web part package
4 deploy that web part to your tenant catalog, and add it to a page on your site
5. change the version in both package.json and package-solution.json
6. make a change in code that will show you are now loading the new version so you can tell the difference
7. repeat steps 2-4
8. refresh the page you have your web part on. it will switch between the older JS and the newer JS back and forth randomly.

This can be very confusing for a user that one time he gets the new web part version and the next - the older one.

**Comment by shaipetel** [comment]
If anyone one is answering this, perhaps you can also clarify:
1. what is the difference/use of the version of the package (package-solution.json) vs. the version of the web part in package.json?
2. When making changes to the package, for instance - changing the CDN location, with of these versions do I have to change in order for my changes to take affect? (none? both?)

As for the issue here, I found that I can resolve it by removing the sppkg from the app catalog, and re-add it. Simply adding it and using "replace" causes the error I describe here. I am pretty sure most people will try to replace and not delete it first, so I think this issue is important at GA stage.

**Comment by nickpape-msft** [comment]
Hi @shaipetel, we are looking into the first issue that you mentioned. As for your other questions:

1. The version in the package.json file is not used for anything in SHarePoint.. The version in `config/package-solution.json` is used for versioning the SPPKG file (including all assets inside of it including webparts). 

2. You should only need to change the `config/package.json` version. There is also a version number in the webpart manifest file, but that number is for your own use (for example to perform upgrades).

3. The manifest file (guid.json) is not needed on the CDN. It is directly included in the SPPKG that is uploaded to the App Catalog.

**Comment by chakkaradeep** [comment]
Did you install that app in the site? If so, did you happen to upgrade that app in that site once you deployed the new package? The workflow here is same as add-ins where you will need to upgrade the app to pick up the new version.

If you are doing a tenant wide deployment, then it should pick up the new script eventually from the cache.

**Comment by shaipetel** [comment]
Hi @chakkaradeep, thanks for the reply but that's entirely not the behavior that I see.

Here is what I experienced:
1. I add the package to the tenant's app catalog at V1.
1. Used it in 2 sites, under V1, pointing to JSv1
1. Once I have V2, I deleted V1 and uploaded V2 to the tenant's app catalog.
1. From that moment both sites immediately start using JSv2, with no need to update the app in each site.

I do see in classic view and option to update the app but even without doing so it is using the JSv2.

To be clear - this is EXACTLY what we want. We have customers who use our apps in hundreds of sites or more, and they all want to update it on one location (in the catalog), and not in each and every site.

Could you clarify what you mean by "tenant wide deployment"? in SPFx, since there is no store, I am not aware of any other way of deploying an app that is different than what I described above.

Also, IMHO if you plan to cache the package definition and update it after it was uploaded it could cause a lot of confusion when people trying to verify a bug was fixed or a new feature works. At the very least, you should consider adding a clear message about it saying "your update will be deployed within x minutes" when you update the package.

**Comment by nickpape-msft** [comment]
@shaipetel , were you able to work through this issue through the workaround you described? Otherwise it definitely sounds like it is taking a while for the upgraded manifest definition to propagate to the caches on all the front-end machines.

**Comment by shaipetel** [comment]
@nickpape-msft Last I tested it, it seems to be fixed now. Meaning: once you drag a new version of the package to the catalog, the trust window shows up again.
Before, the trust window did not show up and that was what I was told causing the problem.

So now, yeah its working as expected.

**Comment by nickpape-msft** [comment]
In that case we will close the issue. Please open a new one if you see any other unexpected behavior.
