### ISSUE TITLE
sp-build-common doesn't support node 12.x

### ISSUE THREAD

**Issue by akdum** [SharePoint/sp-dev-docs#5091]
#2813 ## Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx should support node 12 LTS.

#### Observed Behavior
sp-build-common/lib/spbuildrig.js file contains check for node version: '>=8.9.4 <9.0.0 || >=10.13.0 <11.0.0' which doesn't allow to use node 12.x.

`            
Error: Your dev environment is running NodeJS version v12.13.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0 || >=10.13.0 <11.0.0
    at SPWebBuildRig.initialize (...\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:26:19)`

#### Steps to Reproduce

1. Setup package.json with SPFx 1.10.
2. Update 'gulp' dev dependency to '^4.0.2' to make it work.
3. Run 'gulp' command.

**Comment by patmill** [comment]
Apparently the "setting up your environment" doc said node 12 was supported.  It isn't, and I've updated the document accordingly.
