### ISSUE TITLE
semicolon at the end of JSON?

### ISSUE THREAD

**Issue by MarkStokes-outlook** [SharePoint/sp-dev-docs#5092]
Why is there a smicolon at the end of "the overall JSON structure" at the very start of this article?

Is that intentional and needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That appears to be a typo... that's not valid JSON.

**Comment by MarkStokes-outlook** [comment]
That’s what I thought.

**Comment by MarkStokes-outlook** [comment]
Hi @Vesa. I see you closed this but it’s not been updated.. Does that mean it’s supposed to be there for some reason?

As AC says it’s not valid JSON.

**Comment by VesaJuvonen** [comment]
It was merged 9 min ago to the docs and publishing process takes 10-15 min. I'm trying - I'm trying... but you guys demand so much.... no....................................... it will be there soon as fixed doc, trust me. We are trying and not lying... 😀

**Comment by VesaJuvonen** [comment]
thx @nanddeepn  for providing the fix, highly appreciated.

**Comment by MarkStokes-outlook** [comment]
Lol. Thanks Vesa!

Us? Demanding? Whenever did that start?

Sharing is caring!
