### ISSUE TITLE
@guillaume-kizilian following up on my last comment https://github.com/SharePoint/sp-dev-docs/issues/4892#issuecomment-567040079, confirmed with engineering the supported approach is to use the Azure AD app's URI.

### ISSUE THREAD

**Issue by guillaume-kizilian** [SharePoint/sp-dev-docs#5093]
@guillaume-kizilian following up on my last comment https://github.com/SharePoint/sp-dev-docs/issues/4892#issuecomment-567040079, confirmed with engineering the supported approach is to use the Azure AD app's URI. 

Will bug & update the referenced doc...

_Originally posted by @andrewconnell in https://github.com/SharePoint/sp-dev-docs/issues/4892#issuecomment-567075541_

**Comment by andrewconnell** [comment]
@guillaume-kizilian Don't worry about the doc update... I'm working on it (along with a few other updates) ... it's already assigned to me and I've done some work on it. REF #5033 & #5069
