### ISSUE TITLE
SPFx in MS Teams with MS Graph API: Token renew failed. Token renewal operation failed due to timeout.

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5094]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Web part is able to communicate with MS Graph inside MS Teams.

#### Observed Behavior

`Error - Type : Token Renewal Failed - Description : Token renewal operation failed due to timeout`.

The error appears on the first `get` for any MS Graph endpoint **when the web part is hosted in Teams only**. It works correctly when hosted in SharePoint.
The weird thing that it's reproduced in browser (chrome, chromium edge, FF), but not in a desktop/Mac app.

I tried different users, private mode, clearing of all browser resources - nothing helps.
I've also tried to revoke all the permissions in SP Admin center and even recreating Azure AD Apps propagated for SPFx.

#### Steps to Reproduce

1. Create a simple web part
2. Add next code:
```typescript
protected async onInit(): Promise<void> {
    const client = await this.context.msGraphClientFactory.getClient();
    const joinedTeams = await client.api('/me/joinedTeams').version('v1.0').get();

    console.log(joinedTeams);
  }
```

**Comment by andrewconnell** [comment]
Can you look at the raw HTTP request to get the token and see what is returned? What error, what raw response, etc?

There's another long-running issue that may be related... #4892...

**Comment by AJIXuMuK** [comment]
Hi @andrewconnell,

Yes, it looks similar to the issue you've referenced. 
The error is somewhere inside `sp-http-adal.js`.

And I figured out the reason: the last request of the chain for authentication is `GET https://tenant.sharepoint.com/_forms/spfxsinglesignon.aspx`.
And this page is cached (the response is `200 OK from disk cache`.
As soon as you disable the cache in a browser - it starts working.

For the page itself response for cache control is:
`cache-control: public, max-age=82054`
So, I think, it must be changed to no-cache.

**Comment by AJIXuMuK** [comment]
Digging a bit deeper.
As I mentioned in the beginning - clearing browser cache doesn't help. So, it's interesting as the page is cached...
The reason - authentication flow is called twice.
<img width="398" alt="Screen Shot 2020-01-09 at 1 21 29 PM" src="https://user-images.githubusercontent.com/17036219/72106844-04f0a200-32e5-11ea-880c-b7a07699c124.png">

During the first cycle the page is cached and loaded from the cache for the second cycle.

And I don't see the difference in requests in these 2 cycles so don't have an idea why this is called twice.

**Comment by andrewconnell** [comment]
See #4892... MSFT working on a fix... appears to be a race condition under the covers. You say this looks like the same thing, so I'm going to mark as a dupe and close. If you think otherwise, we can reopen.

**Comment by AJIXuMuK** [comment]
No objections
