### ISSUE TITLE
SPFx v1.10.0 - Subscribe to list notifications not working with list, but only with document library

### ISSUE THREAD

**Issue by SmartFlow365** [SharePoint/sp-dev-docs#5095]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

#### Expected or Desired Behavior

Is not possible subscribe list, but only document library

#### Observed Behavior
This is the documentation reference https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications
When this feature was in preview, in the documentation there was this note

> "At this moment, you can subscribe only to changes in SharePoint Document Libraries. If you try to subscribe to changes in SharePoint List, you will get an error." 

And before that, the considerations were

> - both web parts and extensions can use the list subscription capabilities
> - it is only possible to subscribe to notifications in SharePoint Document Libraries. SharePoint Lists don't support this capability at the moment
> - there is a few seconds delay between the change and the notification being received by the component
> - components can subscribe to changes in multiple Document Libraries
> - the change notification doesn't pass any information about the added or changed document. To see what has changed, use the SharePoint REST API or Microsoft Graph

But now, this is new Consideration and the note is not present

> - all SharePoint Framework components can use the list subscription capabilities
> - **you can subscribe to events from lists and libraries**
> - there is a few seconds delay between the change and the notification being received by the component
> - components can subscribe to changes in multiple Document Libraries or lists
> - the change notification doesn't pass any information about the added or changed document. To see what has changed, use the SharePoint REST API or Microsoft Graph

#### Steps to Reproduce
1- create a new webpart based on v1.10.0
2- install the @microsoft/sp-list-subscription, here find step https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications
3- try to subscribe list, with list ID
4- you get error
5- try to subscrive document library
6- all work fine

**Comment by patmill** [comment]
Thanks @SmartFlow365 - Looks like the documentation got ahead of itself.  Only libraries are supported at the moment (as the underlying subscription service is not available on lists).  I'll get the docs cleaned up.
