### ISSUE TITLE
Blocked by CORS policy making 3rd party API calls using SPFx

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#5096]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

#### Observed Behavior
I am trying to call quote of the day third party API call and it is giving me below error

> has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The same api has been called through the postman and works fine, please check the below screenshot.

![image](https://user-images.githubusercontent.com/17681573/72035351-bbf01c00-32eb-11ea-9ebb-74a395040eb7.png)

#### Steps to Reproduce
Please check my below code.

```
public static getQuoteOfTheDay(httpClient:HttpClient): Promise<any>{
    
        const requestHeaders: Headers = new Headers();  
        // 'ACCEPT': 'application/json
        //requestHeaders.append('Accept', 'application/json');  
        //requestHeaders.append('Content-type', 'application/json');  
        requestHeaders.append('Content-type', 'application/x-www-form-urlencoded'); 
        requestHeaders.append('Authorization', 'Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');  

        const httpClientOptions: IHttpClientOptions = {  
            headers: requestHeaders,  
            mode:'cors',
            method:'GET'
          }; 

              let promise: Promise<any> = new Promise<any>((resolve, reject) => {
                httpClient.get(`https://api.paperquotes.com/quotes/?language=en&limit=1&offset=5&tags=work%2Clife`,
                HttpClient.configurations.v1,
                httpClientOptions
            ) // get response & parse body as JSON
              .then((response: HttpClientResponse): Promise<{ value: any }> => {
                console.log("Final response");
                return response.json();
              }) // get parsed response as array, and return
              .then((response: { value: any }) => {
                resolve(response.value);
              })
              .catch((error: any) => {
                reject(error);
              });
          });
      
          return promise;
    }
```

#### Submission Guidelines

Any help would be appreciated.

**Comment by patmill** [comment]
Take a search for preflight cors errors.  You likely need to remove some of the extra headers you are adding in your get request.  Take a look at the headers on the call that succeeds, and the call that fails.
