### ISSUE TITLE
Creation of Extension with VS 2015 Application Customizer: Error: ENOENT: no such file or directory, scandir 'C:\Users\me\AppData\Roaming\npm\node_modules@microsoft\generator-sharepoint\lib\generators\applicationCustomizer\templates\react' I am facing same issue .

### ISSUE THREAD

**Issue by priyarane30** [SharePoint/sp-dev-docs#5097]
I am facing same issue . 
node version : v10.15.3
npm version :  6.13.4
generator : 1.10.0
I am tried to create extension with VS 2015 and VS 2017, facing same issue .

_Originally posted by @priyarane30 in https://github.com/SharePoint/sp-dev-docs/issues/3609#issuecomment-572398332_

**Comment by VesaJuvonen** [comment]
We do expect each issue to fill up the issue form, which would help to speed up providing support for you, but let's try. What you you mean with using VS 2015 and VS 2017?

Typically you'd be using obviously Visual Studio Code. We would also need to understand how exactly you have installed the SharePoint Framework yeoman generator as we cannot reproduce the issue with basic setup. 

Thanks for the details advance.

**Comment by priyarane30** [comment]
Hi ,
I am trying to create SPFx extension using Visual studio 2015 with Project template.
while Creation of Application Customizer extension , getting error 'no such file or directory, scandir 'C:\Users\me\AppData\Roaming\npm\node_modules@microsoft\\generator-sharepoint\lib\generators\applicationCustomizer\templates\react' . I upgraded generator , but facing same issue.
node version : v10.15.3
npm version : 6.13.4
generator : 1.10.0

**Comment by VesaJuvonen** [comment]
We do not have a project template for Visual Studio 2015 with SharePoint Framework, so can you provide more details what exactly you are trying to achieve. 

Notice that if you are planning to get started with SharePoint Framework development, we would recommend follow assets, which also include step-by-step guidance on your development environment.

* [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* SharePoint Framework training package with videos, hands on labs and other assets - http://aka.ms/spfx-training

Are these getting you started to the right direction?
