### ISSUE TITLE
this.context.propertyPane.open() opens within iframe on isolated webparts

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#5098]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

SPFX isolated webpart when triggering `this.context.propertyPane.open()` opens the config panel within iframe

#### Steps to Reproduce
1. create an isolated webpart
2. create a button that triggers `this.context.propertyPane.open()` and it will open the configuration panel within the isolated webpart iframe instead of parent frame

![image](https://user-images.githubusercontent.com/6864547/72048310-176fd900-32ef-11ea-9957-d554eeeaea7a.png)

**Comment by VesaJuvonen** [comment]
Can you provide details around the SharePoint Framework version which you are using as that would help to proceed with the issue repro and resolution. Thanks.

**Comment by jonathanhotono** [comment]
@VesaJuvonen it's spfx 1.9.1

**Comment by patmill** [comment]
And if you use the UX itself, does it open in the correct place (pane on the page, not pane on the webpart iFrame)?

**Comment by jonathanhotono** [comment]
@patmill using the UX itself open in the correct place (on the page instead of iframe). This is the first time I am using isolated webpart and using `.open()` (pnp react placeholder component).

**Comment by patmill** [comment]
Thanks Jonathan, that's helpful.

**Comment by PaoloPia** [comment]
Hi @patmill,
I can confirm that it really looks like a bug of the _.open()_ method of the _this.context.propertyPane_ object. If needed I can share a sample solution to reproduce the issue. I'm using SPFx 1.10.0 now, but the bug was there also with 1.9.x. Thanks.

**Comment by patmill** [comment]
At some point I'll stop saying "sorry for ghosting".  We're working on issues from oldest to newest.  I can confirm that this isn't working correctly.  While we no longer open the property pane in the webpart iFrame, we also don't open the property pane in the main page either.  That's not right.  We'll take a look at this.

**Comment by AJIXuMuK** [comment]
this should be ww now.
