### ISSUE TITLE
Naming of IPropertyPaneFieldType

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#51]
Is `IPropertyPaneFieldType` really the correct naming for that enumeration? Normally `I` is used to show that it is an intererface. I recommend renaming it to `PropertyPaneFieldType`.

**Comment by manishgarg1** [comment]
I understand your concern @wictorwilen. We had a big debate over the naming of interfaces. The confusion comes from the fact that TypeScript does not have a separate annotation for typing javascript objects. Interfaces are used for both Class interfaces and javascript object typing. Eventually, we agreed to the current convention.

**Comment by wictorwilen** [comment]
I don't get it. This is not an interface, it's an enumeration, that's why it should not be prefixed with an `I`. Just because it all transpiles down to JavaScript doesn't mean we(you) should ignore all known naming conventions?

**Comment by patmill** [comment]
Following up on this.  This wasn't intended, and will get fixed up.  We do occasionally use I* naming, but as you say, that should only be for scenarios where they act like traditional interfaces, not an artifact of what you can do in TS/JS.  Thanks for pointing it out.

**Comment by pgonzal** [comment]
VSO 239932

**Comment by patmill** [comment]
Cleaning up closed issues.
