### ISSUE TITLE
Not able to use a TeamsPersonalApp webpart with mobile client; Cannot configure webpart in windows native app

### ISSUE THREAD

**Issue by FrankMuraschow** [SharePoint/sp-dev-docs#5101]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After deploying a SPFX webpart as an Teams app it should be accessible via the mobile client.
Additionally I should be able to configure the webpart.

#### Observed Behavior
The deployed SPFX webpart is not visible in the native Teams app.
It works in the browser (although there were some token timeout issues) and the native Windows app.
It is not possible to configure the webpart in either the browser or the native Windows app

#### Steps to Reproduce
Deploy an SPFX webpart with supportedHosts _TeamsPersonalApp_ and sync it with Teams via the SharePoint AppCatalog. Add the app via the Teams client or the Teams admin UI.

Greetings,
Frank

**Comment by lucabandMSFT** [comment]
@Gitkohn , thanks for reporting that back. SPFx based tabs are available on Teams Mobile Client under "developer preview". Please follow the documentation reported here to check if you can access Teams Personal Apps that are SPFx based in Teams Mobile: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro

**Comment by Gitkohn** [comment]
@lucabandMSFT thanks for the info. 
I activated the development preview. I still can't see the personal app inside the mobile client, but maybe it will take 24 hours for the settings to take effect. 

Additionally remarks:
- I still don't know how to configure the webpart settings (or if it's possible) when using a Personal Teams App
- The performance between Teams and Graph seems to be better when running the developer preview
- I was able to get rid of the token timeout error by using the Chrome dev console and disabling cache and reloading the page - I tried using CTRL+F5 before but the error persisted. Maybe CTRL+F5 and "Disable Cache" works differently although I thought they were practically the same

**Comment by lucabandMSFT** [comment]
hey @FrankMuraschow , couple of answers:
- Personal apps in Teams do not have any settings experience. That is indipendent to SPFx and it is a peculiarity of Teams personal Apps
for the disabled cache and fore the fact that you may need 24 hours for the personal tab to show up .. I will defer to @lokimeyburg to provide additional feedbacks
