### ISSUE TITLE
SharePoint Rest API or JSOM for updating user profile props

### ISSUE THREAD

**Issue by abdollahkahne** [SharePoint/sp-dev-docs#5115]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

"User profile properties from client APIs are read-only (except the profile picture, which you can change by using the PeopleManager.setMyProfilePicture method). If you want to change other user profile properties, you must use the server object model. "
This was a quote from [Microsoft SharePoint Dev Site ](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-javascript-object-model-in)
Is there any plan for future implementation? (On-Prem). I need it for some branding tasks.
Thanks

**Comment by andrewconnell** [comment]
Not at this time

**Comment by abdollahkahne** [comment]
Thanks for your answer @andrewconnell  as always.
