### ISSUE TITLE
MS Teams App - SPFx webpart can't get AD token

### ISSUE THREAD

**Issue by rayhogan** [SharePoint/sp-dev-docs#5116]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

SPFx webpart should be able to get token using AadHttpClient

#### Observed Behavior
When calling an API from our teams tab app (SPFx sharepoint hosted app), we are getting a "Token Renewal Failed - Description : Token renewal operation failed due to timeout" error. This has been working for the last number of months. It only started throwing this error this week.

![console_errors](https://user-images.githubusercontent.com/769565/72207005-3fe10a00-348c-11ea-8377-8c027fa0b04b.png)

#### Steps to Reproduce

Build a MS Team Tab application using SPFx webpart hosted in SharePoint. Use AadHttpClient to obtain a token to call an AAD protected endpoint.

**Comment by rayhogan** [comment]
Some more additional info. I can see in the Network tab the following calls:
![image](https://user-images.githubusercontent.com/769565/72208838-ac193900-349f-11ea-8c0d-44dfc3475cf0.png)

The 4 authorize? endpoints appear to be fine, and I can see that I am getting back a valid jwt token from AAD. The issue appears to be when it is calling the https://<mytenant>.sharepoint.com/_forms/spfxsinglesignon.aspx endpoint (highlighted).

In the response headers I am getting back:
![image](https://user-images.githubusercontent.com/769565/72208855-e5ea3f80-349f-11ea-9636-b22eda3e8e14.png)

Which is what is causing the first few errors in the screenshot in my original post.

Why would this suddenly be complaining about x frame options?

**Comment by mpaukkon** [comment]
I'm also getting same error with MSGraphClient.

![image](https://user-images.githubusercontent.com/11973653/72221168-8f910580-3560-11ea-9422-c31c8fe3d1d5.png)

**Comment by andrewconnell** [comment]
Suspect this is a dupe... see this comment for an update from MSFT: https://github.com/SharePoint/sp-dev-docs/issues/4892#issuecomment-572300906

As this is a dupe, closing so keep the issue consolidated.
