### ISSUE TITLE
MSGraphClient still does not work for guest accounts without browser activity

### ISSUE THREAD

**Issue by wysisoft** [SharePoint/sp-dev-docs#5119]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

related to #3722, I have a mobile app that gets an oauth token and then uses it in the graph client

var c = new GraphServiceClient(
   new DelegateAuthenticationProvider(
       (requestMessage) =>
       {
           requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", syncInfo.accessToken);
           return Task.FromResult(0);
       }));

I then try to get some list items from a site the user is a guest account on.

var items = await c.Sites["mysite"].Lists["9ed7b835-610e-405b-ad6b-b71782f55d3d"].Items
                    .Request().Filter("fields/Title eq '" + userId + @"'").Expand("fields")
                    .GetAsync();

If the user is logged into the website using the browser, I get the list item result. If not (or its been ~24 hours since the user was logged in to the site using the browser) I fail to get the list items.

**Comment by andrewconnell** [comment]
What error are you getting? You say it's failing if they are not signed into the site or it's been 24 hours since they were signed in... that sounds like the access token has expired...
