### ISSUE TITLE
MSI Installer Link is dead.

### ISSUE THREAD

**Issue by kenmoritest** [SharePoint/sp-dev-docs#5120]
If you are in Windows, you can use the msi installers (x86 or x64) in this link for the easiest way to set up NodeJS.Typical insta

x86 points ...
BAD URL : https://nodejs.org/dist/latest-v10.x/node-v10.18.0-x86.msi
PRECISE URL : https://nodejs.org/dist/latest-v10.x/node-v10.18.1-x86.msi

x64 points to ...
BAD URL : https://nodejs.org/dist/latest-v10.x/node-v10.18.0-x64.msi
PRECISE URL : https://nodejs.org/dist/latest-v10.x/node-v10.18.1-x64.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
Seems that there was a minor update on the 1.10 release which then changed the URLs. Thanks for the comment, fixed on the docs now.
