### ISSUE TITLE
Missing example for transferring odata.type

### ISSUE THREAD

**Issue by jfgoodhew1** [SharePoint/sp-dev-docs#5127]
Under Rename a Folder using MERGE method:
"From the result, obtain the odata.type value, such as SP.Data.Shared_x0020_DocumentsItem (the value may be different depending on your library configuration). Then issue a MERGE"
It is unclear how to transfer the odata.type from the GET request into the MERGE request. odata.type is not a valid dynamic item in Power Automate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The sample after the section you quote shows how it should be used. You don't pass the `odata.type`, rather it's just `type` as a property of the `__metadata` object.

It's included in the object submitted in the body of the request, like this:

```json
{
  "__metadata": {
    "type": "SP.Data.Shared_x0020_DocumentsItem" 
  }
}
```
