### ISSUE TITLE
className for PropertyPane controls

### ISSUE THREAD

**Issue by artxach** [SharePoint/sp-dev-docs#513]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I would like to be able to set className for propertyPane predefined controls. e.g PropertyPaneTextField or PropertyPaneButton. 

#### Observed Behavior
_I am aware of custom property pane controls, but what if i want just to set the background of PropertyPaneButton - is it useful to create a custom button for that, or if i just want to set the width of PropertyPaneTextField _

Thanks for help.

**Comment by manishgarg1** [comment]
Hi @artxach, we do not allow customization of inbuilt PropertyPane fields on purpose. The idea is that the API contract is a data model and the PropertyPane UX is owned by Microsoft. This way it is easier for us to evolve the PropertyPane UX without worrying about breaking customers.  And for exact that reason we have the CustomField support.

**Comment by artxach** [comment]
Ok, thanks)
