### ISSUE TITLE
Create Site not working

### ISSUE THREAD

**Issue by ahemavathy** [SharePoint/sp-dev-docs#5147]
I noticed that the create site does not work when I pass in STS#3 when I try to create a team site. Also the Topic value should be "96c933ac-3698-44c7-9f4a-5fd17d71af9e" not NULL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,

Did test while can't reproduce, what's your request body?
My Test result with Fiddler,
![image](https://user-images.githubusercontent.com/40845109/72510560-9e3f2b80-3884-11ea-8993-93bccf31d994.png)

Showcase site design.

![image](https://user-images.githubusercontent.com/40845109/72511005-608ed280-3885-11ea-8c08-cd0ba3347f5f.png)

![image](https://user-images.githubusercontent.com/40845109/72511123-8a47f980-3885-11ea-8a70-dda3b3f8d454.png)

**Lee
Microsoft SharePoint Community Support**
