### ISSUE TITLE
🐞 Syncing Web parts with too long names to Teams fails silently (or not verbose enough) with a 400 bad request

### ISSUE THREAD

**Issue by MortenGuldbaek** [SharePoint/sp-dev-docs#5148]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

1. Building a SharePoint Framework package containing multiple web parts (no other types of components).
2. One or more web parts have a 'long' name.
3. Building, bundling, packaging and uploading to Tenant app catalog as we have done 1000 times before.
4. Clicking 'yes' to tenant wide deployment.
5. Hitting 'Sync to Teams' button in Ribbon menu.
6. Seeing a small notification that the package was synced successfully.
7. Web parts should now be available in the associated Team.

#### Observed Behavior
Following all the above steps from 1 to 4 works a charm, but when performing step 5, the following happens:

The network panel in Chrome's web developer tools show the request as returning a 400 (Bad request) with no explanation whatsoever.

I found out (after way too much investigation and testing) that the culprit is the Web part manifests which have a `preconfiguredEntries[].title.default` that is over 30 chars in length.

#### Steps to Reproduce
Example web part configuration that will lead to this bug:
![image](https://user-images.githubusercontent.com/6163736/72502300-4deeac00-3839-11ea-9d6c-edf617b3ecf1.png)

#### Improvement or bugfix
Could we get a more verbose message than 400 Bad request? I am hoping that others can save some time by me submitting this, as the documentation is not very specific from the SharePoint side that this is  a requirement. Either this or notice it in the Web part documentation or in the schema file: [https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json](https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json)

The following [documentation for creating Teams manifests for Web parts manually](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart#create-a-microsoft-teams-app-manifest)  
![image](https://user-images.githubusercontent.com/6163736/72503040-1254e180-383b-11ea-801b-921ac3cb302c.png)
 led me to find the error, but nowhere does SharePoint Web part development mention that this is an issue.

**Comment by andrewconnell** [comment]
Interesting find... not sure if I'd call this a bug as a SharePoint web part can have a name that's longer than 30 characters. The Teams manifest file is created dynamically if it's not present when you hit **Sync to Teams**. 

It would be nice if when **Sync to Teams** fails, it would provide more detail (long-running request).

The JSON schema for the web part manifest could include this as some guidance though... I'll raise this with engineering to see what they say...

**Comment by andrewconnell** [comment]
Following up... eng aware...

**Comment by patmill** [comment]
This has been fixed a while ago.  Sorry for the delay in responding here.
