### ISSUE TITLE
Link update

### ISSUE THREAD

**Issue by wildebaard** [SharePoint/sp-dev-docs#5154]
The link to 'SharePoint 2010 and web templates' in the 'See also' section should be updated to:
https://docs.microsoft.com/archive/blogs/vesku/sharepoint-2010-and-web-templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d260574-2e52-61cf-bd83-dfa10699c8c8
* Version Independent ID: 6947088a-5b8c-b58b-617f-c3e0f3686c3b
* Content: [Upgrade web templates for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/upgrade-web-templates-for-sharepoint#feedback)
* Content Source: [docs/general-development/upgrade-web-templates-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/upgrade-web-templates-for-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Easy fix... want to submit a PR yourself?
