### ISSUE TITLE
Are there some methods to listen to the view change?

### ISSUE THREAD

**Issue by YanYi2017** [SharePoint/sp-dev-docs#5155]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi there. I am developing an app, which need to listen to the view change. I have read ["Handle events in SharePoint Add-ins"](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins), but I found there are no events like `ListUpdating` and `ListUpdated`(as I know, view is belong to the list). I want to know why, and are there some other methods to listen to the view change?

**Comment by andrewconnell** [comment]
No, there are no events exposed with a list is updated.
