### ISSUE TITLE
cannot access specific team site using share-point REST APIs

### ISSUE THREAD

**Issue by bdv1234** [SharePoint/sp-dev-docs#5157]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When calling REST endpoint for creating a folder in custom team site , it should be created.
response code should be 201.

#### Observed Behavior

When I called the REST endpoint I got 403 Forbidden with Access denied error message.

#### Steps to Reproduce

I have register a share-point app in following URL.
`https://***.sharepoint.com/sites/ModernTeamSite/_layouts/15/appregnew.aspx`

In there we have to provide permission and the scope for my app. 
following is the permission I have provided.
`<AppPermissionRequests AllowAppOnlyPolicy="true">`
`<AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="FullControl"/>`
`</AppPermissionRequests>`

following is the endpoint I'm trying to access.
`https://***.sharepoint.com/sites/TeamSite_ForB/_api/web/folders`

following is the JSON body I'm setting in the Postman.
`{` 
`   "__metadata":{ `
`      "type":"SP.Folder"`
` },`
`    "ServerRelativeUrl":"/sites/TeamSite_ForB/Shared Documents/testFolder"`
`}`

following is the error response I'm getting.
`{
    "error": {
        "code": "-2147024891, System.UnauthorizedAccessException",
        "message": {
            "lang": "en-US",
            "value": "Access denied. You do not have permission to perform this action or access this resource."
        }
    }
}`

#### Queries I have

1. Above REST endpoint which I'm trying to access, is it correct ?
2. what is SCOPE for accessing custom team site in share-point online ?

I have raise the full detailed question in sharepoint stackexchange as well.
If above not clear please look into the following URL.
`https://sharepoint.stackexchange.com/questions/274721/cannot-access-specific-team-site-using-sharepoint-rest-apis`

**Comment by andrewconnell** [comment]
First, there's more info in your SO post that you shared here... please pick one place to post the question. The two posts are a bit conflicting so it's hard to tell where you are on this.

In the SO post, it appears you created two apps... one using AppRegNew & one using the Azure AD admin center. Those are TWO DIFFERENT APPS, not the same app.

403 means you you don't have permissions to the resource.
In this post you say you created the app using AppRegNew for one site, and creating a folder worked, but when trying to work with a different site, it isn't. 

Take the access token you got, plug it into jwt.io and look at the resource & scopes. That will tell you (1) who the token is valid for (resource) (2) what permissions it has.

**Comment by bdv1234** [comment]
@andrewconnell sorry If I'm being confused you here.
so as you mentioned I plugged my token into jwt.io and I got following payload data.

> {
  "aud": "00000003-0000-0ff1-ce00-000000000000/awsconnector100.sharepoint.com@cc0588dd-6b7f-423f-8546-7778667239d6",
  "iss": "00000001-0000-0000-c000-000000000000@cc0588dd-6b7f-423f-8546-7778667239d6",
  "iat": 1579330613,
  "nbf": 1579330613,
  "exp": 1579359713,
  "identityprovider": "00000001-0000-0000-c000-000000000000@cc0588dd-6b7f-423f-8546-7778667239d6",
  "nameid": "d7e33003-3ee1-4bec-af9a-05795da82f11@cc0588dd-6b7f-423f-8546-7778667239d6",
  "oid": "bfa7bd30-6204-4620-9b5b-961c8bce9deb",
  "sub": "bfa7bd30-6204-4620-9b5b-961c8bce9deb",
  "trustedfordelegation": "false"
}

but in this token I can't find the permission or scopes as you mentioned.

to give you more context, I was able to do any crud operations in "communication site" of my share-point account. (I'm the owner as well as admin in my share-point account)
but the above same crud operations I cannot perform in any custom team site which I have created. 
(I can create a custom site using web interface or using REST API, but cannot do any get, post operations inside that site).

All the permission for my apps I have been given are show cased in the stack exchange post as well. 

I know that I don't have permission for accessing that resource.
please can you give me insights where I should look into , because at this point I'm clueless where I should look into.
thanks.

**Comment by andrewconnell** [comment]
When you created the app using AppRegNew, you are creating it for that site collection, not for multiple sites. Therefore the error makes sense as the access token is for one site (the one where it works), while it won't work on the other site (why you get a 403).

AppRegNew is more of the "legacy" or old way of creating apps... the recommended approach is to create the app in Azure AD, grant it the necessary permissions, and use that.

If you want to create an app that will work against multiple site collections, I'd use the Azure AD approach. In fact, unless there's a requirement to use AppRegNew, I'd avoid it. You can also use MS Graph to read/write to SharePoint doc libraries: https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0

**Comment by bdv1234** [comment]
@andrewconnell ,
thank you for your reply.
As per your suggestion I have decided to go with Graph sdk.
