### ISSUE TITLE
Custom manifest.json is ignored when using "Sync to Teams" inside the app catalog

### ISSUE THREAD

**Issue by FrankMuraschow** [SharePoint/sp-dev-docs#5158]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
According to the answer given by  @andrewconnell in #5152 the manually created manifest.json should be used when syncing the SPFX app to Teams. 

#### Observed Behavior
It seems the default manifest is still being used.

#### Steps to Reproduce
1. Upload a SPFX webpart with a custom manifest.json file located inside the teams-folder 
2. Sync it to teams via the ribbon button.

#### Additional thoughts
According to [this documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart#feedback) I have to manually upload to zipped package to take advantage of the custom manifest.json.  
1. Is this the way we should provide an app to teams for now? 
2. Will there be an update to the sync process to use the custom manifest?

**Comment by michelsmit** [comment]
Experiencing the same, blocks resolving some issues while verifying our solution for SPFX AppSource... Any updates on this one?
