### ISSUE TITLE
Question about the Bing Maps key

### ISSUE THREAD

**Issue by SteIvanov** [SharePoint/sp-dev-docs#5159]
Hello team, 
Is it possible to set one particular Bing Maps key to be applicable on SPO tenant level e.g. to use the same Bing Maps key for ALL site collections inside the tenant or it is only possible to use one Bing Maps key per site collection? I would be very thankful for a fast reply. 
Thanks in advance! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f512d30-b714-7b3c-a567-c5c58197c636
* Version Independent ID: 5e7b7d5a-88eb-4472-074c-469441a27ae5
* Content: [Set the Bing Maps key at the web and farm level in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint#feedback)
* Content Source: [docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
You can use tenant properties to achieve this: https://docs.microsoft.com/sharepoint/dev/spfx/tenant-properties
