### ISSUE TITLE
Recommended JSON isn't valid to the Schema

### ISSUE THREAD

**Issue by MarkStokes-outlook** [SharePoint/sp-dev-docs#5161]
Maybe I am wrong on this, but when I add the latest schema to my Site Script JSON files I get errors in Visual Studio Code.

{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json",
    "actions": [
        {
            "verb": "createSiteColumnXml",
            "schemaXml": "&lt;Field Type=\"Text\" DisplayName=\"Document UID\" Group=\"CDMS\" Required=\"FALSE\" EnforceUniqueValues=\"FALSE\" Indexed=\"TRUE\" MaxLength=\"255\" ID=\"{a90f8dc0-74e6-40ec-85cb-9c5f63b225f9}\" StaticName=\"cdmsDocumentUID\" Name=\"cdmsDocumentUID\" /&gt;"
        }
    ]
}

This generates two error in VS Code stating: 
{
	"resource": "/c:/Users/Mark Stokes/source/repos/CDMS/Site Scripts/cdms-core.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Property verb is not allowed.",
	"startLineNumber": 5,
	"startColumn": 13,
	"endLineNumber": 5,
	"endColumn": 19
}
and
{
	"resource": "/c:/Users/Mark Stokes/source/repos/CDMS/Site Scripts/cdms-core.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Property schemaXml is not allowed.",
	"startLineNumber": 6,
	"startColumn": 13,
	"endLineNumber": 6,
	"endColumn": 24
}

Am I doing something wrong? or does the schema not match the code examples?

Thanks

Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @MarkStokes-outlook ,
the schemaXml property contains an invalid value since you have to escape the quotas first. Consider adding one backslash (\\) in front of quotes. I've edited and tested your Site Script. This is how it looks:

``` JSON
{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json",
    "actions": [
        {
            "verb": "createSiteColumnXml",
            "schemaXml": "<Field Type=\"Text\" DisplayName=\"Document UID\" Group=\"CDMS\" Required=\"FALSE\" EnforceUniqueValues=\"FALSE\" Indexed=\"TRUE\" MaxLength=\"255\" ID=\"{a90f8dc0-74e6-40ec-85cb-9c5f63b225f9}\" StaticName=\"cdmsDocumentUID\" Name=\"cdmsDocumentUID\" />"
        }
    ]
}

I hope it helps!
```
