### ISSUE TITLE
How to avoid stuttering effect in SP online page render

### ISSUE THREAD

**Issue by rpskumar** [SharePoint/sp-dev-docs#5170]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Reserve corresponding space for asynchronously rendering media or visual elements to avoid skipped frames and stuttering (also known as jank).

#### Observed Behavior
My Communication site Home page has 2 sections layout. 

Section 1 layout is full width style with 1 custom App to display Hero style news web part(custom SPFx web part to display 5 images and link to News from SharePoint list. The images are less than 300 KB.

Section 2 has 3 columns layout with 3 custom SPfx web parts. 2 SPFx Image web part and 1 event web part.

I do not have performance issue in overall page load (5 - 7 seconds). However section 2 web parts appears on page first and then take a second to load web part in section 1. 

From user experience , Section 2 web parts loads, then all of sudden section 1 web part is appearing by pushing down section 2. This gives bad user experience.

Lazy loading may not help me since both section visible in view port of the page. 

How to avoid the flickering effect on page? Is there any way to sequence the section loading or reserve space for section 1?

I referred the article to optimize web part , https://docs.microsoft.com/en-us/office365/enterprise/modern-web-part-optimization#feedback.  It tells to reserve space to avoid jank effect , but i do not find any reference on how to do that.
Thanks in advance.

**Comment by andrewconnell** [comment]
At this time, only SPFx extensions have the native ability to preallocate space to avoid a page reflow. Web parts don't have this capability.

REF: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders

**Comment by rpskumar** [comment]
> At this time, only SPFx extensions have the native ability to preallocate space to avoid a page reflow. Web parts don't have this capability.
> 
> REF: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders

Thank you @andrewconnell . SPFx extension preallocate space only in top placeholder and bottom placeholder.
I have implemented PnP caching for 1st section web part list items which helps in page refresh and navigate back to home page again. 
Is there any other solutions when Section 1 web parts take longer time than section 2 web parts, such as Defining execution order of web parts , dependency load?

**Comment by andrewconnell** [comment]
@rpskumar said:
> Is there any other solutions when Section 1 web parts take longer time than section 2 web parts, such as Defining execution order of web parts or dependency load?

Nothing provided by SPFx... there may be some patterns people have employed, but there's nothing official like the placeholder's preallocated space capability.
