### ISSUE TITLE
🐞❓Missing copy-static-assets.json shema

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#5173]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In an SPFx solution to copy static assets in the config folder, a file named copy-static-assets.json can be stored that includes file extension to get copied automatically to the lib folder.

The definition in this file should also have a schema definition available.

#### Observed Behavior
Following the pattern of copy-assets.json which has a schema defined at the url:
[https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json](https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json)

This schema is missing for copy-static-assets.json:
[https://developer.microsoft.com/json-schemas/spfx-build/copy-static-assets.schema.json](https://developer.microsoft.com/json-schemas/spfx-build/copy-static-assets.schema.json)

#### Steps to Reproduce
Open both URLs defined previously.

**Comment by patmill** [comment]
Thanks Stefan - chatted with the heft folks, and they will publish this - https://github.com/microsoft/rushstack-legacy/blob/main/core-build/gulp-core-build/src/tasks/copyStaticAssets/copy-static-assets.schema.json - to the developer.microsoft.com site.  Might take a little while for it to publish.
