### ISSUE TITLE
Column formatting @currentWeb doesn't resolve as AsoluteWebUrl

### ISSUE THREAD

**Issue by ikmoss** [SharePoint/sp-dev-docs#5174]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
@currentWeb should be resolved as AbsoluteWebUrl in column formatting

#### Observed Behavior
"@currentWeb + '/SitePages/testpage.aspx'"
transform to
https://testspsite.sharepoint.com/sites/testsite/documentlibrary/forms/@currentWeb/SitePages/testpage.aspx
instead of
https://testspsite.sharepoint.com/sites/testsite/SitePages/testpage.aspx

#### Steps to Reproduce
Example of the problematic part of a format column JSON
...
"href": "=@currentWeb + '/SitePages/History.aspx?number=' + substring(@currentField, 0, indexOf(@currentField, '|'))"
...

**Comment by semopz** [comment]
Same issue here. I think we'll need to wait for someone with premier support to raise an official ticket. Not sure if the SPFx team can do anything about this

**Comment by PrasadKasireddy** [comment]
Related - https://github.com/SharePoint/sp-dev-list-formatting/issues/201 & https://github.com/SharePoint/sp-dev-list-formatting/issues/199

**Comment by phillipharding** [comment]
This seems to be working again now

**Comment by VesaJuvonen** [comment]
There was unfortunately a regression with @me and @currentWeb tags starting from 3rd of January. Fix has been already applied and is >50% rolled out in the production, expected to be at 100% level within upcoming days.

**Comment by ikmoss** [comment]
Our production tenant has now received the hotfix. Thanks @VesaJuvonen

**Comment by PrasadKasireddy** [comment]
it is fixed now in our tenant
