### ISSUE TITLE
Consume aadHttpClientFactory.getClient response code 200 but no data fetched

### ISSUE THREAD

**Issue by ozie02** [SharePoint/sp-dev-docs#5175]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I have created an extension that consists of child components and a webpart to make a call to an Azure function that has authentication enabled which would return data in the response after successfully authenticating. 

#### Observed Behavior

The webpart returns data after successfully authenticating but not for the extension even though they are consuming the same API. Once you click the button the extension attempts to fetch data from the API after authenticating but it seems the response comes back blank even though the response code is 200.

I am passing **this.context** from the Root component which extends BaseApplicationCustomizer to the child component (**Root --> ReactHeader --> ReactPanel --> ReactOrders.ts**) which requires to make authentication and the API call. 

On the other hand, for some reason after upgrading the extension to SPFX 1.9.1, the generated files are showing in the source folders.

I have added more details (steps + Screenshots) in each example.

#### Steps to Reproduce

The first example is a webpart consuming my Azure Function and rendering data accordingly (this is to ensure the web service configuration is healthy).

In the second example, I have an Extension attempting to use the same web service via child component that fails to fetch data but successfully authenticated.

**Webpart Source Code + Steps:** [https://github.com/ozie02/Learning/tree/master/Webpart/contoso-api](https://github.com/ozie02/Learning/tree/master/Webpart/contoso-api)  

**Extension Source Code + Steps:** [https://github.com/ozie02/Learning/tree/master/Extensions/contoso-api-extension](https://github.com/ozie02/Learning/tree/master/Extensions/contoso-api-extension) 

Thanks for your contribution! Sharing is caring.

**Comment by andrewconnell** [comment]
Do the two work if they are not on the page at the same time? Asking because there's a known issue (#4892) where a race condition is present... a fix is being worked on.

**Comment by ozie02** [comment]
That a good point, I removed the webpart from the page and had the extension all alone but unfortunately, I still had the same issue.

**Comment by andrewconnell** [comment]
What exactly is the error you're receiving? Use the browser's dev tools & look at the network tab. Find the request that is fetching the data / access token. Look at the raw response... there has to be a response that's got more detail than "failed to fetch data". :)

Also... what is the code doing. Please share the code snippet from the extension where the error is occurring.

**Comment by ozie02** [comment]
That's the problem, I don't see any errors in browser console or the Network tab :)

I have uploaded the complete code on github under as well [https://github.com/ozie02/Learning/tree/master/Extensions/contoso-api-extension](https://github.com/ozie02/Learning/tree/master/Extensions/contoso-api-extension)

**Code Snippet**
```
public componentDidMount() {
    this.authenticateUser().then( () =>{
      this.ordersClient
      .get('https://func1.mintranet.net/api/HttpTrigger2?id=12', AadHttpClient.configurations.v1)
      .then((res: HttpClientResponse): void => {
        this.setState({myOrders: res.json()});
      });
    });
  }
  
  protected authenticateUser(): Promise<void> {
    return new Promise<void>((resolve: () => void, reject: (error: any) => void): void => {
      this.props.context.aadHttpClientFactory
        .getClient('https://func1.mintranet.net')
        .then((client: AadHttpClient): void => {
          this.ordersClient = client;
          resolve();
        }, err => reject(err));
    });
  }
```

**Screenshot below**
Console Tab
![image](https://user-images.githubusercontent.com/58676455/72872920-eee0d980-3d07-11ea-803e-0a79152f9916.png)

Network Tab
![image](https://user-images.githubusercontent.com/58676455/72865412-314aec00-3cf1-11ea-9bf9-2ed1bd84b0e2.png)

**Comment by andrewconnell** [comment]
1. For the second screenshot on the network tab, you see nothing in the **Response** tab?
1. Have you tried taking that access token that is used in the request to a tool like Postman to submit the request outside of SPFx to verify the service is returning data?

**Comment by ozie02** [comment]
Apologies for the delay, after your response, what I have done is tried to see if actually data coming through and noticed once I clicked on the 'Preview' tab in the browser debugger there is data coming in but I can't figure out why the res.json() is not feeding this data back. The same piece of code used in the webpart returns data to the component.

![image](https://user-images.githubusercontent.com/58676455/73054473-f937da80-3ea3-11ea-83ee-38c3baca9c5e.png)

**Comment by andrewconnell** [comment]
That's what I suspected... the `json()` method returns a promise so your code isn't waiting for it to complete. Minimally, this should fix it:

Change:

```ts
.then((res: HttpClientResponse): void => {
  this.setState({myOrders: res.json()});
});
```

to

```ts
.then((res: HttpClientResponse): void => {
  res.json().then((results) => {
    this.setState({myOrders: results});
  });
});
```

*Pretty sure this will work... I didn't test this... but you can see what I'm doing...*

**Comment by ozie02** [comment]
Awesome that worked :) 
Thanks to you I spent so many days on this issue. But I don't understand why we had to change the code to make it work this way.

![image](https://user-images.githubusercontent.com/58676455/73092322-d2a28f80-3ef5-11ea-9778-449b32a3f051.png)
