### ISSUE TITLE
Tenant wide deployment of extensions on SP 2019

### ISSUE THREAD

**Issue by merlinko637** [SharePoint/sp-dev-docs#5178]
Hello, is there any was to achieve this also on SP 2019? It works for webparts, but not for extensions. I created an Application customizer for injecting css file, to create custom styling for SP sites. I need to have this working also on subsites that will be created later, so we dont want the user to install it manually. Is there a chance to achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e41df74-a651-cfa5-a538-9397e6793f52
* Version Independent ID: 9f272325-fdb3-68e3-634b-e7428128f75b
* Content: [Tenant Wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions)
* Content Source: [docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
No, not like this capability in SharePoint Online. 

You can use PowerShell to enumerate through all site collections and install the app to the desired site collections.

@merlinko637 said:
> I need to have this working also on subsites that will be created later, so we dont want the user to install it manually.

Unfortunately, the only option is what I mentioned above. You can set up a scheduled process to check for new site collections and install the app via PowerShell.
