### ISSUE TITLE
Is it possible to set STS#2 as WebTemplate value?

### ISSUE THREAD

**Issue by PetarSam** [SharePoint/sp-dev-docs#5179]
#4880 ## Category
- [x] Question

Hi dear people of Sharepoint,

I am trying to set Flow which as a result creates a new SharePoint site
with "Send an HTTP request to Sharepoint".

https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest was used as inspiration and everything works well except template which site is build upon. 

I would like to set it as STS#2 but API call gets declined every time template-id is not STS#3 or SITEPAGEPUBLISHING#0.

Anyone had the same experience and found any solution?

Thank you

**Comment by andrewconnell** [comment]
No... the endpoint you are using is for creating *modern* sites, not *classic* sites. The template you are trying to use (STS#2, a Document Workspace) is a classic site template, not a modern site template.
