### ISSUE TITLE
Sass build - path alias configuration

### ISSUE THREAD

**Issue by clarktozer** [SharePoint/sp-dev-docs#5180]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to add path aliases to the sass builder so I can avoid having very long relative paths?
Tilde in SPFx scss files is relative to node_modules. 

For example
`../../../../../common/mixins/animations.module.scss`
Could become
`~common/mixins/animations.module.scss`

**Comment by andrewconnell** [comment]
That would be considered a feature request which should be posted to SP Dev UserVoice. But you may also be able [to leverage webpack](https://spblog.net/post/2019/02/05/sharepoint-framework-development-tips-prettify-your-imports) here (but not sure if it would apply to SASS resolutions)
