### ISSUE TITLE
How to create site with STS#2 template programmaticlly?

### ISSUE THREAD

**Issue by PetarSam** [SharePoint/sp-dev-docs#5183]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

First of all thank you for the fast answer for previous question, this time I am interested if it is possible and how to create an STS#2 type of site with an API call?

Thank you!

**Comment by gobigfoot** [comment]
I'm using this to create a team site no group. I imagine it will work for you by swapping the Template type.

`New-PnPTenantSite -Owner $SharepointAdminUser -StorageQuota 26214400 -Url $SiteUrl -Template "STS#3" -Title $SiteTitle -TimeZone 10 -ErrorAction Stop `

**Comment by gobigfoot** [comment]
I take it that worked for you?

**Comment by PetarSam** [comment]
Oh sorry for not giving you credits, yes it worked perfectly, thank you :)
