### ISSUE TITLE
Cannot approve apps permission on my api management

### ISSUE THREAD

**Issue by komzy96** [SharePoint/sp-dev-docs#5184]
im trying to use a webpart i downloaded from github but im having issues with the api management. Can you help resolve this.
![Screenshot (195)](https://user-images.githubusercontent.com/48515129/72804643-204a9e00-3c51-11ea-863b-945dd93f42bf.png)

**Comment by VesaJuvonen** [comment]
Hi @komzy96, can you share the tenant name using a private message either using LinkedIn, TechCommunity or Twitter, so that we can have a closer look on this. We are getting few of these now, so curious on checking exact details from the server side logs. Thx.

**Comment by komzy96** [comment]
Can I share the tenant here via mail or kindly share your linkedin profile.
Warm regards

**Comment by komzy96** [comment]
Or your Twitter handle I'll be willing to share any information you want

Kind Regards.

**Comment by VesaJuvonen** [comment]
@komzy96  - LinkedIn profile would be following - https://www.linkedin.com/in/vesajuvonen/ - most likely easiest. Just send message there. Thx.

**Comment by komzy96** [comment]
Can't send you a message on LinkedIn cause I don't have the premium version.
Can you share your email address?

**Comment by komzy96** [comment]
Although I just connected with you as *Willie ekomobong* please accept the
connection.

**Comment by JarbasHorst** [comment]
It is not the same kind of error, but it would be interesting to see if the error persists when changing the resource from Microsoft Graph to Microsoft.Azure.AgregatorService in the package-solution.json. I've found it in this documentation here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions

I hope it helps!

**Comment by komzy96** [comment]
Thanks jarbas I'll quickly try this out although the error I'm have is HTTP
500 rather than HTTP 400. I'll update soon on my results.
Kind regards.

**Comment by VesaJuvonen** [comment]
@komzy96 - my email address is quite obvious considering my first name, last name and the company I work with. You do not though need premium to send messages in LinkedIn as I don't have that either and can do that... but either way.

**Comment by VesaJuvonen** [comment]
@komzy96 - was actually able to trace this with the GUID from the pic. Seems like a permission issue. Is the account which you are using tenant administrator as the logs would suggest otherwise, so would double check that first. Can you please confirm this as it helps on the trouble shooting - thx.

**Comment by komzy96** [comment]
The account is just a SharePoint administrator for the tenant but not a
global administrator for the tenant.

**Comment by VesaJuvonen** [comment]
and that's the problem in this case. Behind of the scenes you are actually approving tenant admin operations in Azure AD, which then a SharePoint admin account does not have the permissions... as by default that would not be the case. This then throws an ugly exception which we at the Microsoft need to make more informative. 

We should actually check that the user who arrives on the API management page has the sufficient permissions and if that's not the case, we should have clear and informative message around the required permissions. 

So - in short - Your exception is as expected you'll need to be tenant administrator to approve the API permissions.

**Comment by komzy96** [comment]
Hello good morning so I told the global admin of my tenant to approve but
it's still giving errors

**Comment by komzy96** [comment]
Hey vesa you where right. the issue has been fixed. Thanks
