### ISSUE TITLE
Will this, when i GA, have support for the React Framework

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-docs#5187]
Or is it just javascript?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d7dc0df-037f-4783-7867-8c34b4ade989
* Version Independent ID: ee99f6b9-246c-216f-7a8e-1472f813a14c
* Content: [Creating Outlook add-ins using SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-addins-create#feedback)
* Content Source: [docs/spfx/office-addins-create.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/office-addins-create.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This feature is in dev preview... no timeline for GA has been shared at this time.
