### ISSUE TITLE
No -BlogPage  &  -PostAsNews  available in  command 'ConvertTo-PnPClientSidePage'

### ISSUE THREAD

**Issue by mmohamedbasith** [SharePoint/sp-dev-docs#5191]
While running the script , we receives error ConvertTo-PnPClientSidePage : Cannot bind positional parameters because no names were given. 
Please refer below url :  No -BlogPage  &  -PostAsNews  available in  command 'ConvertTo-PnPClientSidePage'
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/convertto-pnpclientsidepage?view=sharepoint-ps

I have update the lastest Sharepoint pnp version
SharePointPnPPowerShellOnline 3.11.1907.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3cc7206-e210-2281-8d45-c012dc3b7f6a
* Version Independent ID: 85a6d3bb-ada9-4654-9262-b8cc03fdaf86
* Content: [Modernize Delve blogs and classic blogs](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-blogs#feedback)
* Content Source: [docs/transform/modernize-blogs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-blogs.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Probably best to post this to the [PnP PowerShell's repo's](https://github.com/SharePoint/PnP-PowerShell) issue list for the best visibility...
