### ISSUE TITLE
Sharepoint Framework does already support SharePoint 2016(with the right Feature pack) and SharePoint 2019 .

### ISSUE THREAD

**Issue by Ibtissam-Azure-Office365** [SharePoint/sp-dev-docs#5202]
Good article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f02c78f-11e2-c9b9-ec7c-191e6e55caa8
* Version Independent ID: 4ed11eb8-a57e-d719-e0e5-95cdaa863b87
* Content: [Overview of the SharePoint Framework (SPFx)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview#feedback)
* Content Source: [docs/spfx/sharepoint-framework-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-framework-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks for your feedback!
