### ISSUE TITLE
Reopened: List Formatting style whitelisting typo: flex-basic instead of flex-basis

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#5203]
## Category

- [x] Bug

## Describe the bug

This is a previously opened issue that was closed (#2403) but it is still an issue and needs to be tracked/fixed by the team.

**Comment by KevinTCoughlin** [comment]
Thanks for reporting @thechriskent, we've committed a fix. cc: @VesaJuvonen

**Comment by andrewconnell** [comment]
@KevinTCoughlin as this issue was just a request to reopen an existing issue, I closed this one and reopened the other one as it contains the detail fo the issue.
