### ISSUE TITLE
@me not being converted/translated correctly as logged on user

### ISSUE THREAD

**Issue by 365Iain** [SharePoint/sp-dev-docs#5204]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
@me token in view and column formatting has previously displayed email address of the logged on user and the 'if' condition to set text colour should evaluate to true and therefore display as red text.

Code used for testing:

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "div",
  "txtContent": "@me",
  "style": {
    "color": "=if(@me == @Author.email, 'red', 'blue')"
  }
}
```

#### Observed Behavior
The txtContent is not converting correctly so @me is being output instead of logged on user's email address and when used conditionally it is not evaluating to match .email property of a user field where the user matches the logged on account.

![image](https://user-images.githubusercontent.com/29796236/72825623-45e6a000-3c6f-11ea-94ed-28c0ad987728.png)

Issue is occurring across multiple tenants.

NB: Both https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json and https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json schemas reproduce the issue.

#### Steps to Reproduce
JSON added to column formatting on person/group field.

**Comment by VesaJuvonen** [comment]
As this is an issue on the actual column and view formatting capability and not on any of the samples at the sp-dev-list-formatting repository, moving it to the sp-dev-docs for more visibility.

**Comment by 365Iain** [comment]
> As this is an issue on the actual column and view formatting capability and not on any of the samples at the sp-dev-list-formatting repository, moving it to the sp-dev-docs for more visibility.

Thanks for moving this. Had a check this morning and it looks like it is now fixed. Just confirming in some production  sites and lists. Will reopen if I see any issues on these.

**Comment by VesaJuvonen** [comment]
There was unfortunately a regression with @me and @currentWeb tags starting from 3rd of January. Fix has been already applied and is >50% rolled out in the production, expected to be at 100% level within upcoming days.

**Comment by PrasadKasireddy** [comment]
Please reopen this ticket as tracking as it is not completed fixed
