### ISSUE TITLE
{ListUrlDir} not working as described

### ISSUE THREAD

**Issue by michalhainc** [SharePoint/sp-dev-docs#5205]
**Reopening as original issue got closed by some bot for inactivity https://github.com/SharePoint/sp-dev-docs/issues/2879#issue-377299755**

{ListUrlDir} - claims to be the Server-relative URL of the site plus the list's folder, for me it translated to "Sp2Ex_Emails" but the "Server-relative URL of the site plus the list's root folder" should have been "/sites/sp2ex/testweb1/Sp2Ex_Emails"

My command UI handler element:

         <CommandUIHandler 
         Command="Invoke_Emails_RibbonAction_FilesButtonRequest"
         CommandAction="~remoteAppUrl/Modal/FolderTreeModal?{StandardTokens}&amp;SPListItemId={SelectedItemId}&amp;SPListId={SelectedListId}&amp;folder={ListUrlDir}&amp;itemUrl={ItemUrl}&amp;selectionKind=messages&amp;IsDlg=1"/>

**Comment by andrewconnell** [comment]
Reopened original issue.
