### ISSUE TITLE
Fields hidden in ContentType are shown in forms

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#5206]
## Category

- [x] Bug

## Describe the bug

We have a SharePoint App that creates site columns, contenttypes and lists programmatically through CSOM (C#). This worked for several years without a problem. Now (don't know exactly the time it changed) when this solution creates a site contenttype which doesn't use the "Title" column and therefore sets it to hidden, this title column is nevertheless shown in all the standard SharePoint forms of lists using that contenttype:

![image](https://user-images.githubusercontent.com/26869201/72978913-882af100-3dd7-11ea-8977-0554a7efc92f.png)
_____________________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/26869201/72979044-c7f1d880-3dd7-11ea-959c-7bb0e3b0bd07.png)

## Steps to reproduce

Create a new empty communication site in SharePoint Online called 'myTestSite'.
Create a new C# Application in Visual Studio and add the latest SharePointPnPCoreOnline Nuget package.
Use the following code:
```C#
AuthenticationManager authenticationManager = new AuthenticationManager();
ClientContext ctx = authenticationManager.GetSharePointOnlineAuthenticatedContextTenant("https://<your tenant here>.sharepoint.com/sites/myTestSite", "<your username here>", "<your password here>");
string schemaXml = "<Field Name='myNewField' StaticName='myNewField' DisplayName='myNewField' Type='Text'/>";
            
Field newField = ctx.Web.Fields.AddFieldAsXml(schemaXml, true, AddFieldOptions.AddFieldInternalNameHint);
newField.Title = "myNewField";
newField.Update();
ctx.ExecuteQueryRetry();
ctx.Load(newField);
ctx.ExecuteQueryRetry();

var itemContentTypes = ctx.LoadQuery(ctx.Web.ContentTypes.Where(c => c.Id.StringValue == BuiltInContentTypeId.Item));
ctx.ExecuteQueryRetry();
var itemContentType = itemContentTypes.FirstOrDefault();
ContentType newContentType = ctx.Web.ContentTypes.Add(new ContentTypeCreationInformation { Name = "myNewCT", ParentContentType = itemContentType });
newContentType.FieldLinks.Add(new FieldLinkCreationInformation { Field = newField });
newContentType.Update(true);
ctx.ExecuteQueryRetry();
ctx.Load(newContentType, t => t.Id, t => t.FieldLinks.Include(f => f.Name));
ctx.ExecuteQueryRetry();
newContentType.FieldLinks.Where(f => f.Name == "Title").FirstOrDefault().Hidden = true;
newContentType.Update(true);
ctx.ExecuteQueryRetry();

List newList = ctx.Web.Lists.Add(new ListCreationInformation()
{
    TemplateType = (int)ListTemplateType.GenericList,
    Title = "myNewList"
});
ctx.ExecuteQueryRetry();
newList.ContentTypesEnabled = true;
newList.ContentTypes.AddExistingContentType(newContentType);
newList.Update();
ctx.ExecuteQueryRetry();

```
Adjust the tenant / credentials and run it.
Side note: The same steps executed via the SharePoint GUI in the browser lead to the correct result (the Title column is hidden). So seems to be related to using CSOM for the creation.

## Expected behavior

A column that is set to "hidden" in a contenttype should actually be hidden in the standard forms.

## Developer environment

Visual Studio 2019 on Windows 10
SharePointPnPCoreOnline Package version 3.17.2001.2

**Comment by cwdata** [comment]
Add-On:
I just saw that our tenant already has the new "Edit Form" command in the standard forms where you can manually hide/unhide fields.
Maybe this new feature introduced the bug.

**Comment by andrewconnell** [comment]
Unsure what the behavior was previously, but it doesn't make sense to hide the Title field. This field is required on all list items and thus users must be able to enter a value.

Even if you could do this previously, if it changed, I suspect this fixes the previous behavior.

Unclear from your post, but there are actually three Title fields, a main one & two calculated ones. Not sure if what's being shown in your edit form is one you aren't trying to hide.
