### ISSUE TITLE
The code sample in the "Query for filtered information" section is incorrect

### ISSUE THREAD

**Issue by DmytroLapshyn** [SharePoint/sp-dev-docs#5207]
Hi there,

The code sample in the "Query for filtered information" section is incorrect. The Filter class does not have a FilterValue property; however the FilterCollection itself has a convenience method named SetFilterValue that does exactly what's expected.

The issue also seems to affect the "Retrieve paged result sets" section as well where a similar incorrect approach to setting filter values is demonstrated in the code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c436ad-8a6c-91e8-7ddb-9cab5e50cb30
* Version Independent ID: 2c087b2a-7a72-e3b2-39c4-b82818e1fad9
* Content: [Get started using the client object model with external data in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-using-the-client-object-model-with-external-data-in-sharepoint#feedback)
* Content Source: [docs/general-development/get-started-using-the-client-object-model-with-external-data-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/get-started-using-the-client-object-model-with-external-data-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to submit a PR with proposed fixes to the doc?

**Comment by DmytroLapshyn** [comment]
@andrewconnell sure - does this link to the pull request work for you?
https://github.com/Sigma-Software/sp-dev-docs/pull/1

**Comment by andrewconnell** [comment]
Unfortunately not... that's a PR in your fork to your own fork... you need to create a PR in this repo to pull from your fork. See [How to create a good pull request](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests) for details & additional links to github's help on this.

**Comment by DmytroLapshyn** [comment]
Apologies, my bad. Now there should be a proper PR.
