### ISSUE TITLE
Non-Reactive Properties:  Last control not visible in property pane.

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#521]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When using a non-reactive property panel with enough properties to make the panel scroll on the Y axis I expect to be able to see all of the property controls.   

#### Observed Behavior
The non reactive "propertyPaneFooter" is absolutely positioned over the bottom of the property pane, covering the last property control.

#### Steps to Fix
Add "padding-bottom: 80px;" to your "propertyPanePageContent" element.

**Comment by swalker1595** [comment]
I have observed this issue before as well.
