### ISSUE TITLE
Site URL in the manifest file

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-docs#5212]
I think the URL of the domain needs to be updated in the manifest file. It is an important point in the documentation which we expected. Could you please add it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b8fe2a-2de5-5ebd-c525-506c3916abd5
* Version Independent ID: 2eb9af47-f722-7ec7-e79b-819b6b2b06ac
* Content: [Tutorial for creating Outlook Web Access extension using SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/office-addins-tutorial#feedback)
* Content Source: [docs/spfx/web-parts/get-started/office-addins-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/office-addins-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
@Harshagracy  - manifest file is created automatically by default with default settings.
@VesaJuvonen  - Is it required to add details about manifest files - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-addins-create#configuration-support-with-office-add-ins. If yes, I will add that

**Comment by VesaJuvonen** [comment]
There is no need to update the manifest file after the initial creation of the project. It has a specific tag, which is then automatically updated based on the hosted tenant. If you follow up on the tutorial, there's no need to update manifest file in any ways to get things running - we set up it properly with default values which do work as such.

**Comment by Harshagracy** [comment]
Yes I tried it without updaing the URL now. It works. Thanks @VesaJuvonen !
