### ISSUE TITLE
Properly way to remove a Tenant Wide Deployed Extension

### ISSUE THREAD

**Issue by eaquiler** [SharePoint/sp-dev-docs#5216]
Hi, I'm wondering which is the right process to remove an Extension that have been deployed tenant wide. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e41df74-a651-cfa5-a538-9397e6793f52
* Version Independent ID: 9f272325-fdb3-68e3-634b-e7428128f75b
* Content: [Tenant Wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions#feedback)
* Content Source: [docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
You can go to the Tenant Wide Deployment list at your app catalog site collection (site contents) and simply remove the entry for the extension or alternatively simply uninstall the solution from the app catalog, if that's the intention. This will simply remove the association from the sites and extension will no longer be rendered.

If extension is part of a larger solution and you ONLY want specific tenant wide deployed extension to be removed, you can do that from the **Tenant Wide Extensions** list at app catalog site collection. This list has even a disable option for specific extensions, which will disable the extension to be included on the pages across the tenant.
