### ISSUE TITLE
Centering tiles in list view

### ISSUE THREAD

**Issue by MiliusCZ** [SharePoint/sp-dev-docs#5217]
## Category
- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hi, I'm using JSON formatting to display list items as tiles. Is there a way how to center the tiles on the page? Currently it is aligned to the left no matter what I do. I can't override the margins or text-align properties as with "tileProps" attribute in JSON formatter, I can only influence the css of tile itself, not the parent container.
Thanks!

**Comment by shagra-ms** [comment]
@MiliusCZ Can you please share more details about what you are trying to achieve?
