### ISSUE TITLE
getting HTTP 400 Correlation ID error when you approve Graph API Permissions from sharepoint admin center

### ISSUE THREAD

**Issue by applekajui6** [SharePoint/sp-dev-docs#5218]
Expected Behaviour : I have a spfx webpart which displays calender events using Graph API . When you try to approve the Graph API Permission under API Mgmt of SP Admin Center it should get approved

Observed Behavior: When I try to approve it using global admin accessi am getting  HTTP 400 Correlation ID 

![image](https://user-images.githubusercontent.com/60218749/73082368-5b69fd00-3eef-11ea-93d7-64d7b406d877.png)

**Comment by lahuey** [comment]
@applekajui6  could you email me your tenant's url so that I can investigate the logs? 
lahuey@microsoft.com

Thanks

**Comment by applekajui6** [comment]
when I see in Portal Azure it is showing permissions are granted. In my webpart im getting "sp-webpart-workbench-assembly_en-us_f0d9d879eac858478672d13ba224a03e.js:19 Uncaught (in promise) Error: Error - Type : Token Renewal Failed - Description : Token renewal operation failed due to timeout - AADCorrelationId: " Error

**Comment by lahuey** [comment]
Is this happening consistently? Which browser? @applekajui6

**Comment by applekajui6** [comment]
Yes ... Please .. for browser -chrome

**Comment by applekajui6** [comment]
sent you URL in email

**Comment by johnnycardy** [comment]
I can also reproduce this error;
`[HTTP]:400 - [CorrelationId]:ae1c5b9f-b08b-2000-5962-97ea956ad6bd [Version]:16.0.0.20127`
