### ISSUE TITLE
Table 7. Site options in SharePoint Online - Table is messed up

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#5221]
Content should be fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28dce46b-a552-800a-621a-efcd6ee41d4e
* Version Independent ID: ea865148-7860-c247-6ae5-454ddb9c60c6
* Content: [Branding and site provisioning solutions for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yup... content bug... thanks. Will get this fixed.
