### ISSUE TITLE
Modern vs Classic

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#5222]
Would like to re-open this discussion
https://github.com/SharePoint/sp-dev-docs/issues/4295

If any of this applies to modern, it is unclear.  I would recommend that a section be created for branding modern sites and then have an entirely separate page for classic and publishing pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28dce46b-a552-800a-621a-efcd6ee41d4e
* Version Independent ID: ea865148-7860-c247-6ae5-454ddb9c60c6
* Content: [Branding and site provisioning solutions for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint#feedback)
* Content Source: [docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good point... docs need to get updated. #reopened
