### ISSUE TITLE
Application Customizer not initialized for top placeholder on first load of modern site

### ISSUE THREAD

**Issue by user546** [SharePoint/sp-dev-docs#5223]
## Category

- [x] Bug

## Describe the bug

> Error:
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.XXXXXXX'. Error information is '***Extension failed to load for componentId "XXXXXXX".'.
at sp-pages-assembly_en-us_XXXXXXX.js:XXXX

## Steps to reproduce

> 1) Create Application Customizer in a solution which includes other spfx webparts also for rendering text in top placeholder
2) create sppkg
3) deploy to tenant with out clicking on add tenant wise
4) do add an app in site collection where top placeholder was rendered
5) try sign out or open in incognito mode or clear local storage and session storage and reload the page.
6) top place holder was not loaded and getting above mentioned error in console

## Expected behavior

> able to see text in top placeholder when site was initially loaded for first time

## Developer environment

> chrome

### Additional context

> I am able to load in one of the tenant where no spfx web parts are present in the home page
Unable to load top place holder in another tenant where other spfx web parts are added

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Can you provide the code for your placeholder? There's not much detail to work from in your submission...
