### ISSUE TITLE
List-formatting : What is difference b/w Operators "?" & ":"

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#5225]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
List-formatting : What is difference b/w Operators "?" & ":" , I know that **?** is a conditional Operator, Is ":" also conditional Operator?

@thechriskent

**Comment by shagra-ms** [comment]
There is no difference between **?** & **:**.
