### ISSUE TITLE
 QuickLaunch navigation (for SinglePageWebParts) fails

### ISSUE THREAD

**Issue by ng-marcus** [SharePoint/sp-dev-docs#5227]
## Category

- [x] Bug

## Describe the bug

On some tenancies, we are seeing clicks on the left hand menu (QuickLaunch) being ignored unless the link is clicked twice.   This is quite similar to an error we had some months ago #3168   When the link is clicked, the URL updates but the original content is rendered.   We're not seeing our React didMount or render functions getting called.

## Steps to reproduce

Add a page and set it to SinglePageWebPart.  Add an SPFX component.
Create another page 
Click the first page - its content will render
Click the second page - the URL changes but the content remains the same
Click either link twice and it forces a reload and the full content is there.

Adding another page without seeing it to SinglePageWebPart - navigation between the two page types works as expected.

## Expected behavior

Page content to update

## Developer environment

SPFX 1.09 and 1.10 have the same issue

**Comment by andrewconnell** [comment]
@GrahamMcMynn Is this related to the navigation events?

**Comment by ng-marcus** [comment]
This may be related (and I only looked because this was the issue last time) but when the page loads, it makes two calls to get the page json

![image](https://user-images.githubusercontent.com/20163757/73177807-d60d6500-4107-11ea-832c-5614d6d1486c.png)

Both are GET calls

The second response has no response body.

**Comment by GrahamMcMynn** [comment]
@andrewconnell  - I don't believe it is, however, I will take a look and try reproducing it.

**Comment by ng-marcus** [comment]
If it would help with analysis if you would like access to our Dev tenancy let me know and I can create a user account for you.

**Comment by patmill** [comment]
Sorry for going dark @ng-marcus .  We have made a series of fixes on the page->page navigation flows over the past while.  Is this still an issue for you?

**Comment by ng-marcus** [comment]
Hi @patmill     Thanks for checking in.   I'll get the team to test and get back to you tomorrow.  We added a work around that fully loaded the page each time, so we will disable that and see how it works now.

**Comment by ng-marcus** [comment]
Hi @patmill  We still see the same problem sorry.    With Single Page Apps we still have the issue where the user has to click twice on a navigation link to make the content change.

**Comment by patmill** [comment]
Thanks @ng-marcus - we're looking into this.

**Comment by AJIXuMuK** [comment]
This should be WW now.
