### ISSUE TITLE
Querying large lists by code

### ISSUE THREAD

**Issue by gszdev** [SharePoint/sp-dev-docs#5232]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Is it possible to query large lists by code (REST, CSOM, ...) to get over the 5000 items list view threshold limit, like in the modern experience list views?

Background:
We are using indexed columns inside the query and the result of the first query part will return more the 5000 items. So we get the 5000 items threshold error. Same happens for the view using classic experience. BUT NOT using the modern experience.

Using Fiddler I see that the following REST API is used:
<serverRelativeSiteUrl>/_api/web/GetListUsingPath(DecodedUrl=@a1)/RenderListDataAsStream?@a1='<serverRelativeListURL>'&View=<ViewId>&TryNewExperienceSingle=TRUE

Can we get details about this api (parameter, samples, ...) to use it in our code.

## Environment details
SharePoint Online

**Comment by andrewconnell** [comment]
The method you are asking about, `RenderListDataAsStream`, is documented here: https://docs.microsoft.com/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#renderlistdataasstream-uri-parameters

**Comment by gszdev** [comment]
@andrewconnell, Yes you right the method is documented. But are there any information to get around the 5000 items list view threshold like modern experience list view does?

I see the following URI-Parameter "TryNewExperienceSingle" in Fiddler which I cannot find in the documentation.

Additional information to the question:
[SharePoint Online List View Threshold](https://joannecklein.com/2017/07/25/sharepoint-online-list-view-threshold/)
