### ISSUE TITLE
How to navigate with partial load to a page from a Single WebPart App Page link

### ISSUE THREAD

**Issue by panggio** [SharePoint/sp-dev-docs#5235]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> In a STS site, we have a single webpart app page with a button to another page. In our tenant with Standard Release, on click it does partial reloading to the destination page successfully. However, since last weekend, in our Targeted Release tenant, it changes the url on the navigation bar but it doesn't redirect the user to the destination page.
> 
> We're using the code suggested by nero120 here:
> https://github.com/SharePoint/sp-dev-docs/issues/1547
> 
> then we tried using:
> https://www.npmjs.com/package/spfx-navigation
> https://www.eliostruyf.com/navigating-to-other-pages-in-sharepoint-framework-from-code/
> 
> Without any luck.
> Any suggestions? As this is (potentially) is caused by a change in targeted release tenants, we'd like to update our code before it affects our site in the tenant with standard release set.

**Comment by ng-marcus** [comment]
We're seeing the same issues with navigation since the weekend, hitting more of our customer tenants through the week - see  #5227

**Comment by panggio** [comment]
Since yesterday we've also detected this issue in our standard release tenants.

**Comment by ng-marcus** [comment]
We see the same too with this appearing on standard release tenants.

**Comment by ikmoss** [comment]
This issue need to be escalated related #5277 and https://github.com/SharePoint/sp-dev-docs/issues/5211
