### ISSUE TITLE
Schema change in package-solution.json

### ISSUE THREAD

**Issue by PiotrekKrakowiak** [SharePoint/sp-dev-docs#5239]
There seems to be a schema change on the package-solution.json file. 
The old one (generated by yeoman) said:
"$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",

The new version as suggested by this article says:
 "$schema": "https://dev.office.com/json-schemas/spfx-build/package-solution.schema.json",

Could you comment on this difference? Should the sharepoint-generator get update it to implement this?

Thanks and cheers!
Piotrek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package#feedback)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The schemas referenced in the latest Yeoman generator are the most current and correct references. The docs may be a bit outdated. Note the last time this page was updated: March 2019 (*while the latest SPFx release v1.10 was in January 2020*).

**Comment by PiotrekKrakowiak** [comment]
Thanks Andrew - I am going to create a PR to update this article then, to use the developer.microsoft.com schema as generated by yeoman! Cheers!

**Comment by PrasadKasireddy** [comment]
@PiotrekKrakowiak  & @JarbasHorst  - duplicate PRs #5242  & #5243
