### ISSUE TITLE
Modern Comm site event page does not scroll properly when SPFx footer is used

### ISSUE THREAD

**Issue by corriespondent** [SharePoint/sp-dev-docs#5246]
## Category

- [x] Bug

## Describe the bug

A modern communication site's event page on O365 does not scroll properly when SPFx footer is used. The footer sticks in the middle of the page.

## Steps to reproduce

1. Apply SPFx extension to add a footer to the bottom placeholder of a modern communication site
2. Add custom events to the site so that there are enough to require the page to scroll
3. The custom SPFx footer will scroll up with the page, fixed to the original location.

![image](https://user-images.githubusercontent.com/23064475/73322355-81e2ad80-41f9-11ea-9a14-b44c5ea43d3a.png)

## Expected behavior

The footer should remained fixed to the bottom, as it does on other modern pages.

## Developer environment

- OS: Windows 10
- Browser(s): Chrome

### Additional context

 It seems like the event page container doesn't allow for scrolling the way that most other pages do. The top is the event page, and there is no height or overflow-y styling, while the main page (bottom) allows for scrolling. If you have a footer rendering in the bottom placeholder, it becomes very evident that this is a problem.

![image](https://user-images.githubusercontent.com/23064475/73322447-a9d21100-41f9-11ea-97d1-92067742c9fb.png)

**Comment by VesaJuvonen** [comment]
Acknowledge and being worked on. Really unfortunate and quite visible issue on the modern experiences. We should have updates on this relatively soon.

**Comment by patmill** [comment]
Sorry - missed this due to metadata.  I've followed the repro steps, created a customizer w/ a footer, added a bunch of events, and when I go to the events page and scroll, the footer stays at the bottom.  Please open a new issue if you find that this isn't what you experience.
