### ISSUE TITLE
Exempting from having to load jquery or angular on spfx if already setup on masterpage level

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#525]
- [ ] Question
- [ ] Enhancement / Suggestion

Is there any workaround to exempt certain libraries from being loaded again by sharepoint framework if the libraries are already loaded in the sharepoint masterpage level? E.g: angularjs/jquery(with some plugins like flexslider) are already set on masterpage and just need to be reused. 

Maybe like check if `(window as any).angular` is already set then ignore and just use the existing object instead or else load from cdn.

**Comment by NickSevens** [comment]
I think if you make sure both usages are referencing the same URL, the file will only be loaded once.

**Comment by jonathanhotono** [comment]
Hi @NickSevens , both are referenced to the same cdn url. Note that angular is first loaded on master page. Then the SP webparts loads the framework again without having to download it however it executes angular again for the second time and you'll get this following warning: 
`WARNING: Tried to load angular more than once.`
And for some reason this breaks the sp framework webpart on edge browser, on second refresh.

![warning](https://cloud.githubusercontent.com/assets/6864547/24546099/8d2e09d2-1655-11e7-96e9-658b98fe5cea.JPG)

**Comment by waldekmastykarz** [comment]
Theoretically you could do it by loading external scripts using the `SPComponentLoader` class. You would perform the necessary checks for the existence of the scripts in the global scope and load them only if they are not there. Please note, that this issue applies only to classic sites. Modern sites currently don't support custom Master Pages or script injection so it's a non-issue there.

**Comment by jonathanhotono** [comment]
Thanks @waldekmastykarz . Yes this issue is only applicable for classic publishing site only as I need to apply branding on the masterpage level(not sure when microsoft will support custom masterpage on modern pages).
I managed to get it working by using this following solution as per your suggestion:
![image](https://cloud.githubusercontent.com/assets/6864547/24576183/179b158a-1703-11e7-9422-35cacd49b661.png)
![image](https://cloud.githubusercontent.com/assets/6864547/24576181/006b7a8a-1703-11e7-9da2-9a65cf8e1d45.png)

One tiny issue here is that I'm unable to use angular typings on my services/controllers since if I do `import * as angular from 'angular'`, it will basically loads up angular again twice. So I will have to perform this sort of checks on each services and controller if I decided to use `angular` global object. 

@waldekmastykarz , what is your opinion about this solution and do you have any better suggestion for this issue? 

Thanks

**Comment by waldekmastykarz** [comment]
One thing that you could try is to register Angular typings as global in the tsconfig.json file, by adding `angular` to the **types** property next to **es6-promise** and other types in there. I haven't tried it myself, but it might just work.

**Comment by jonathanhotono** [comment]
That works fine @waldekmastykarz ! Thanks for your help.
