### ISSUE TITLE
Disabled the Sync to Teams button in the SharePoint tenant App Catalog

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#5252]
Select the teams-tab-client-side-solution package in the SharePoint tenant App Catalog and disabled the Sync to Teams button at in the ribbon at the Files tab.
While creating sample Teams tab SPfx 1.10 and also Updated the web part manifest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4521ae6c-2ac6-8898-4731-0a5a50349d76
* Version Independent ID: 49edacf9-9538-079b-24ab-3ce17017ba77
* Content: [Building Microsoft Teams tab using SharePoint Framework - Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)
* Content Source: [docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Did you ensure the solution was deployed to the entire tenant when prompted? Can you provide a repro or upload your project's code to a public GH repo and reference it to assist researching the issue?

**Comment by PrasadKasireddy** [comment]
Reproduce :
1. I created the team tab as per the document - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab
2. SPFx 1.10.
3. Web part manifest file
     `{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
  "id": "1baa6995-0828-4855-8004-51268b2903a4",
  "alias": "MyFirstTeamsTabWebPart",
  "componentType": "WebPart",

  // The "*" signifies that the version should be taken from the package.json
  "version": "*",
  "manifestVersion": 2,

  // If true, the component can only be installed on sites where Custom Script is allowed.
  // Components that allow authors to embed arbitrary script code should set this to true.
  // https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f
  "requiresCustomScript": false,
  **"supportedHosts": ["SharePointWebPart","TeamsTab"],**

  "preconfiguredEntries": [{
    "groupId": "5c03119e-3074-46fd-976b-c60198311f70", // Other
    "group": { "default": "Other" },
    "title": { "default": "MyFirstTeamsTab" },
    "description": { "default": "MyFirstTeamsTab description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "MyFirstTeamsTab"
    }
  }]
}
`
4. Make this solution available to all sites in the organization
![SPFx_teamstab_solution](https://user-images.githubusercontent.com/11626905/73431169-ce4afc00-4365-11ea-95c7-370d44facd97.PNG)

5. Disabled the Sync to Teams buttion in the SharePoint tenant App Catalog.
![SPFx_teamstab](https://user-images.githubusercontent.com/11626905/73430640-93949400-4364-11ea-8971-f2b829e3aec6.PNG)

6. find the solution file
[teams-tab.zip](https://github.com/SharePoint/sp-dev-docs/files/4132837/teams-tab.zip)

**Comment by JarbasHorst** [comment]
Hello @PrasadKasireddy 
I've created a new teams-tab web part based on [the provided]( https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab) Microsoft documentation. Everything worked properly and I was able to sync the web part as a Teams tab. 

I was able to reproduce the problem with your sppkg file. Maybe it has not been generated correctly. I am wondering if this issue is related to your environment's configuration. I posted below my configurations:

* OS: Windows 10
* SPFx: 1.10.0
* Node: 10.17.0
* Yeomen: 3.1.0
* Gulp: CLI version: 2.2.0 and Local version: 3.9.1
* Npm: 6.11.3

Could you check your environment's configuration and maybe update that please?
I hope it helps!

**Comment by PrasadKasireddy** [comment]
Please refer my environment configuration details
OS  - windows 10 
SPFx - 1.10.0
Node - 10.18.0
Yeomen - 3.1.1
gulp - 4.0.2
npm - 6.13.4


![SPFx version](https://user-images.githubusercontent.com/11626905/73541209-d6836400-4457-11ea-9320-07c11b1c9654.PNG)

**Comment by JarbasHorst** [comment]
I've analysed your sppkg file. The file WebPart_1baa6995-0828-4855-8004-51268b2903a4.xml doesn't contain TeamsTab as a supported host. This is the reason why the Sync to Teams button is disabled. The WebPart_1baa6995-0828-4855-8004-51268b2903a4.xml file represents part of your web part's manifest. For some reason your changes to the manifest file didn't get saved! Would you like to give the web part a new chance?

**Comment by PrasadKasireddy** [comment]
Thanks for your suggestion @JarbasHorst, sure I will try and let you know.

**Comment by PrasadKasireddy** [comment]
Thanks @JarbasHorst , now it is working you are right manifest file didn't get saved.
