### ISSUE TITLE
I cannot create a new SPFx project with version 1.10

### ISSUE THREAD

**Issue by MarkStokes-outlook** [SharePoint/sp-dev-docs#5253]
## Category

- [x] Bug

## Describe the bug

I have just installed Node 10 and SPFx version 1.10 on a new computer. I am trying to create a new project but the Yeoman generator crashes / freezes at a particular point and I can't do anything to progress.

## Steps to reproduce

1. Bring up a new Console window (same with a PowerShell terminal in VS Code)
2. Navigate to new project folder
3. Run yo @microsoft/sharepoint
4. Choose options
5. Get stuck on the question below

![image](https://user-images.githubusercontent.com/17313109/73406539-92c11b00-42ee-11ea-86ec-512b47df85ba.png)

## Expected behavior

Progress past this point.

## Developer environment

- OS: Windows 10
- Framework: Node.js v10
- Browser(s): N/A - Not at that point yet
- Tooling: VS Code, Command Prompt (both with Administration mode on and off), SPFx v1.10.0

**Comment by andrewconnell** [comment]
What version of Yeoman are you running? There was a known issue with one of its dependencies for a while.

Consider uninstalling Yeoman and reinstalling it, then try again.

**Comment by MarkStokes-outlook** [comment]
@microsoft/generator-sharepoint@1.10.0

**Comment by MarkStokes-outlook** [comment]
I was able to seed the project on another machine and can open it on this computer now.

**Comment by MarkStokes-outlook** [comment]
I wonder if this helps?

![image](https://user-images.githubusercontent.com/17313109/73870892-b92e0b80-4844-11ea-9715-0b9bb36ed98d.png)

**Comment by MarkStokes-outlook** [comment]
Ok. I just uninstalled the generator and yo and reinstalled them and now I can create the webpart on this computer. It must have been that version of yo.

Working config:
![image](https://user-images.githubusercontent.com/17313109/73871772-5e95af00-4846-11ea-81cc-116624b957cb.png)

Thanks AC
