### ISSUE TITLE
SharePoint Redirect URI Needed?

### ISSUE THREAD

**Issue by byronwjones** [SharePoint/sp-dev-docs#5259]
Given that web parts are granted authorization via OAuth Implicit flow, what exactly is the mechanism that establishes the trust relationship between the Azure AD secured Web API and SharePoint? Specifically, what configures the Web API's app registration to accept [my-tenant].sharepoint.com/etc/etc as a valid redirect URI?  Is this done automatically when a SharePoint admin grants permission to the API, or are there other steps to be taken to establish the trust relationship?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@byronwjones said:
> what exactly is the mechanism that establishes the trust relationship between the Azure AD secured Web API and SharePoint

Every SPO tenant has an Azure AD app that's created in your tenant the first time you grant a permission to SPO to the Azure AD app that protects your HTTPS endpoint. Both apps are in Azure AD so they share trust with Azure AD. When you grant SPO the permission to your HTTPS endpoint, you're effectively giving SPO permission to call it. SPFx is obtaining an access token from AAD for SPO. SPO then hands that token to your SPFx component which it uses to directly call your HTTPS endpoint. The first picture in the first section of this article shows how it works.

@byronwjones said:
> Specifically, what configures the Web API's app registration to accept [my-tenant].sharepoint.com/etc/etc as a valid redirect URI?

The redirect URI is only used when you are authenticating with Azure AD... IOW: when you're logging in. There is no login with SPFx... you're already logged into SharePoint Online.
