### ISSUE TITLE
Having more than one web part 'preconfiguredEntries' does not work in SharePoint 2016 on prem

### ISSUE THREAD

**Issue by thriggle** [SharePoint/sp-dev-docs#5260]
## Category

- [x] Bug

## Describe the bug

When multiple preconfiguredEntries are present in the web part's manifest.json file, only the first (alphabetically) can be added to a page in SharePoint 2016 on premises. The others are visible in the web part gallery and can be added to the workbench demo page without any issue, but can't be added to actual (classic) pages.

## Expected behavior

When one web part has 2 or more preconfiguredEntries with different default values, the web part appears as multiple available web parts to end users. The end user can add any of the web parts to the page to have a web part with the predefined default values set.

## Observed behavior

The additional web parts display correctly in the web part gallery when adding a web part to a page, but only the first preconfigured web part can ever be added to a page. Adding any of the web parts to the page always adds the first entry for that web part, based on its alphabetical order in the list.

The different web parts appear as expected in the workbench (at /_layouts/15/workbench.aspx): 
![workbench screenshot](https://i.stack.imgur.com/A0VBB.gif)

But when you go to add them to a publishing page, only the first web part is added each time.

In the screenshot below, the Horizontal Bar Chart was added even though I tried to add the Line Chart.
![publishing page screenshot](https://i.stack.imgur.com/3vODT.png)

## Steps to reproduce

Create a web part with multiple preconfigured entries in the manifest.json. 

For example: 

> "preconfiguredEntries": [
>     {
>       "groupId": "1e95b737-7aeb-459a-8b74-ff30335ea553", 
>       "group": { "default": "Charts from SharePoint Lists" },
>       "title": { "default": "Pie Chart" },
>       "description": { "default": "Web part for displaying charts using data from SharePoint lists" },
>       "officeFabricIconFontName": "PieDouble",
>       "properties": {
>         "chartType": "Pie",
>         "options":"{\"labelDirection\":\"explode\",\"labelPosition\":\"outside\"}"
>       }
>     },
>     {
>       "groupId": "1e95b737-7aeb-459a-8b74-ff30335ea553", 
>       "group": { "default": "Charts from SharePoint Lists" },
>       "title": { "default": "Line Chart" },
>       "description": { "default": "Web part for displaying charts using data from SharePoint lists" },
>       "officeFabricIconFontName": "LineChart",
>       "properties": {
>         "chartType": "Line",
>         "options":"{\"lineSmooth\":true,\"low\":0,\"showArea\":false,\"showPoint\":false,\"axisY\":{\"onlyInteger\":true}}"
>       }
>     },
>     {
>       "groupId": "1e95b737-7aeb-459a-8b74-ff30335ea553", 
>       "group": { "default": "Charts from SharePoint Lists" },
>       "title": { "default": "Horizontal Bar Chart" },
>       "description": { "default": "Web part for displaying charts using data from SharePoint lists" },
>       "officeFabricIconFontName": "BarChartHorizontal",
>       "properties": {
>         "chartType": "Bar",
>         "options":"{\"horizontalBars\":true,\"low\":0,\"reverseData\":true,\"seriesBarDistance\":15,\"stackBars\":false,\"chartPadding\":{\"left\":30,\"right\":0}}"
>       }
>     }
>   ]

Build and deploy the web part. 

Add the web part to a publishing or wiki page. Be sure to try adding any web part other than the first. 

Only the first web part is ever added, even if it was not selected.

## Developer environment

- OS: Windows 10
- Framework: Node.js v8.16.2
- Browser(s): Chrome 79.0.3945.130, IE v11
- Tooling: VS Code, SPFx v1.1.0
- Platform: SharePoint Server 2016 (on premises), January 2019 patch

### Additional context

This issue was reported for SharePoint Online in May of 2017 and resolved in June of 2017. See Issue: https://github.com/SharePoint/sp-dev-fx-webparts/issues/209

**Comment by andrewconnell** [comment]
As your referenced issue indicates, this was fixed in SharePoint Online in mid/late 2017. However, you say you're on SharePoint Server 2016. 

Unfortunately, there is no mechanism to update SPFx on-prem so the issue that was fixed in SPO hasn't & won't be fixed in the existing SPFx v1.1 on SP2016. The fix would have been applied to SharePoint Server 2019 though.
