### ISSUE TITLE
SPFX WebPart consuming Graph api to display events is not working in IE11

### ISSUE THREAD

**Issue by applekajui6** [SharePoint/sp-dev-docs#5262]
## Category
Issue
- [x] Bug
SPFX WebPart consuming Graph api to display events is not working in IE11
## Describe the bug

I have created SPFX Webpart which displays calendar events using Graph API. It is working in Chrome but not in IE11

**Comment by applekajui6** [comment]
used the same code in this link https://github.com/microsoftgraph/msgraph-training-spfx/tree/master/Demos/02-events .. it is not working in ie11

**Comment by andrewconnell** [comment]
The **Needs: Context Detail** is more than just "where is your code". It would help if you can provide detail son what isn't working. What error are you getting, where, etc.

**Comment by applekajui6** [comment]
![image](https://user-images.githubusercontent.com/60218749/73841623-fdb7a800-4840-11ea-9131-45edd0f65f4f.png)

Im getting above error in IE11 when trying to display upcoming events using Graph API in my spfx webpart:

im getting response null in IE11 but not chrome or Edge
please see my sample code below:
  this.props.graphClient
      .api('/me/mailboxSettings/timeZone')
      .get ( (error:any,eventsResponse:any,rawResponse?:any)=>{
var timeZone:string=  eventsResponse.value;
this.props.graphClient
      .api('/me/calendar/events')    
        .header("Prefer","outlook.timezone=\""+timeZone:string+"\"")     
        .filter(currentDate)      
        .orderby("start/dateTime")
        .top(3)
        .get( (error:any,eventsResponse:any,rawResponse?:any)=>{
 const calendarEvents:MicrosoftGraph.Event[]=eventsResponse.value;
              console.log('calendarEvents',calendarEvents);
              this.setState({events:calendarEvents});

});

});

**Comment by andrewconnell** [comment]
Which `value` reference is throwing the error? There are multiple in your code.

Have you looked at the NETWORK tab to inspect the data being returned from your query? Seems one of the two queries is returning no data. Consider running the same queries using the [Graph Explorer](http://aka.ms/ge) with different browsers. 

SPFx isn't doing anything here other than providing a configured Graph client. The calls are being submitted by the Graph JS SDK.
