### ISSUE TITLE
getting 400 BadRequest Error sometimes when I try to get calendar events in SPFX Webparts 

### ISSUE THREAD

**Issue by applekajui6** [SharePoint/sp-dev-docs#5263]
## Category
Issue
- [x] Bug
getting 400 BadRequest Error sometimes when I try to get calendar events in SPFX Webparts 

## Describe the bug

I am getting 400 BadRequest Error sometimes when I try to get display calendar events in SPFX Webpart.

![image](https://user-images.githubusercontent.com/60218749/73540168-375d6d00-4455-11ea-9e44-d5f41561de7e.png)

URL:
https://graph.microsoft.com/v1.0/me/calendar/events?$filter=end/dateTime%20ge%20%272020-1-31T18:5:36.246%27&$orderby=start/dateTime&$top=3

**Comment by andrewconnell** [comment]
Your query isn't valid. Use the [Graph Explorer](https://aka.ms/ge) to test your query.
