### ISSUE TITLE
What is the least privilege permission to deploy solution in site collection app catalog? 

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-docs#5267]
## Category

- [x] Bug

## Describe the bug

I have been verifying the least permission as per [this ](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)article that says, the user should be site collection administrator to deploy the solution in site collection app catalog, however, if I try to deploy the solution with "Edit" permission, I face following error message:

**"Must have Manage Web Site permissions in order to add apps to site collection app catalog"**

Further, I have verified in the following ways:

1) Created custom permission level with "Manage Website" permission and user with that permission level was able to deploy the solution
2) Also, the user from the "Site Owners" group was able to deploy the solution as "Manage Website" permission is applicable to the "Owners" group.

Does it mean minimum requiring permission is a user from "Site Owner" by design OR it's a site collection administrator for some reason I am not aware? Would you please clarify?

Thank you for your time!

Best Regards,

**Comment by dips23** [comment]
Hello,

I have got a piece of information from this link - [](https://docs.microsoft.com/en-us/sharepoint/request-app-installation-permissions) which clarifies: “Only those users who have the appropriate permission level can add apps to a site. Typically, Full Control permission (or membership in the Site Owners group) is the minimum requirement.”

We can close this ticket.

Thank you and Regards,

**Comment by VesaJuvonen** [comment]
thx @dips23 for coming back and providing also the answer, that helps for anyone else who might ran into your question. Really appreciated. Closing based on the request from you.
