### ISSUE TITLE
Change the look theme throws error and does not load, sidebar collapsed.

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#5268]
## Category

- [x] Bug

## Describe the bug
I can no longer change theme/color across multiple tenants(some tenant works) via "Change the look"

## Steps to reproduce
1. Click "Change the look"
2. Click "Theme"
3. Sidebar collapsed and theme section not loaded

![change-the-look](https://user-images.githubusercontent.com/6864547/73625020-ad401f00-4675-11ea-9145-0be40bae637e.gif)

## Developer environment

- OS: Windows 10
- Browser(s): Latest Chromium Edge, Chrome

**Comment by furler** [comment]
I'm seeing this too

**Comment by VesaJuvonen** [comment]
We do understand that this is not certainly optimal, but as this is non-dev issue impacting out-of-the-box experience, it should be reported using the tenant admin support channels (admin UIs in your tenant). We cannot unfortunately provide support for non-dev topics through GitHub.
