### ISSUE TITLE
[HTTP]:500 - [CorrelationId]:ddb9319f-5045-a000-e515-bd44a26a8eb0 [Version]:16.0.0.19708

### ISSUE THREAD

**Issue by anthony-git** [SharePoint/sp-dev-docs#5269]
Manage access to Azure AD-secured APIs from SharePoint Framework. 
I'm trying to give the permission to Graph Api for my sharepoint SPFX webpart am getting [HTTP]:500 - [CorrelationId]:ddb9319f-5045-a000-e515-bd44a26a8eb0 [Version]:16.0.0.19708

**Comment by anthony-git** [comment]
![2020-02-03_13h10_26](https://user-images.githubusercontent.com/54057007/73634185-9a821600-4686-11ea-8db6-c38724ee4d33.png)

**Comment by anthony-git** [comment]
Am following this post : https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-birthdays 

Am trying to give graph permission for birthday web part that has been deployed in App-catalog .

**Comment by VesaJuvonen** [comment]
Thx @anthony-git, can you also provide details around the SharePoint version which you are using and what permissions you are trying to approve? Are the Graph permissions or something else. In general our issue template is provided for reason, so that we can help you as efficiently as possible, so would not recommend deleting the template as suggested also in writing.

**Comment by VesaJuvonen** [comment]
Are you a tenant administrator in this tenant or just SharePoint administrator?

**Comment by VesaJuvonen** [comment]
We can see an permission exception at the Logs for this issue, which would indicate that you are using an account which is SharePoint administrator, but not a tenant administrator. That would clarify the situation. If you are however using a tenant administrator, then we are potentially running into a regression, which we can solve by clearing the status at the Azure AD side, but this step is slightly more complex, so let's first double check the permissions which you have and move forward to Azure AD app registration cleaning only if needed.

**Comment by anthony-git** [comment]
Am using SharePoint online.
Am trying to Approve the Graph API permission
I'm SharePoint Administrator

**Comment by VesaJuvonen** [comment]
@anthony-git - if you are ONLY a SharePoint administrator, this is as expected as the permissions which you are trying to approve are actually applied in the Azure AD and you need to be tenant administrator aka. global administrator.

We can see following exception in the logs for you case - *"Insufficient privileges to complete the operation."*.

This means that you either need to request your tenant administrator to approve these requests or request more permissions for your account in your organization. 

See also following documentation - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient - *"SharePoint Framework allows you to specify which Azure AD applications and permissions your solution requires, and a tenant administrator can grant the necessary permissions if they haven't yet been granted. "*
