### ISSUE TITLE
cannot find module '@microsoft/sp-build-web'

### ISSUE THREAD

**Issue by karishmaTCS** [SharePoint/sp-dev-docs#527]
I am trying to execute **gulp serve** but it gives me error **cannot find module '@microsoft/sp-build-web'** . How do i resolve it ?

**Comment by waldekmastykarz** [comment]
Have you executed `npm install` first to restore the missing dependencies?

**Comment by nickpape-msft** [comment]
@karishmaTCS are you still seeing this issue? @waldekmastykarz 's suggestion is correct. Feel free to re-open this issue if you are still having troubles.
