### ISSUE TITLE
Does not work in SP 2019

### ISSUE THREAD

**Issue by piekenpuil** [SharePoint/sp-dev-docs#5271]
All of these demos work as a charm with SharePoint Online, but a lot of them are useless for SP2019. E.g. the data bar example just shows blanks instead of values in SP2019. Is the syntax different there ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I believe only v1 of the column formatting is supported. There's a note in the section [Get Started with Column Formatting](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#get-started-with-column-formatting) in this doc that states you need to specify the v1 schema. 

Any of the samples you see that list v2 or higher will only work on SharePoint Online.

**Comment by shagra-ms** [comment]
@piekenpuil Can you confirm the JSON you used? 

Please note that excel style expressions are not supported on SP 2019. You need to use the AST version of the JSON from the sample repository on SP 2019.
