### ISSUE TITLE
Most of my texts does not get BOLD

### ISSUE THREAD

**Issue by artxach** [SharePoint/sp-dev-docs#528]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [X] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
_I want my fontWeight to take effect on most of my texts_

#### Observed Behavior
_I use ms-fontSize-[size] and ms-fontWeight-[weight] classes of office ui fabric, font sizes work excellent but font weights do not take effect_

#### Steps to Reproduce
_I have a `<span className={'ms-fontSize-xl ms-fontWeight-semibold'}>sometext</span>`- but actually semibold doesn't take effect_

**Comment by manishgarg1** [comment]
Hi @artxach, did you look at the developer console and see what is overriding your styles ?

**Comment by artxach** [comment]
the thing is that nothing is overriding it. In console developer i see the my style is applied.

**Comment by iclanton** [comment]
Can you post a screenshot of the style hierarchy from the developer console?

**Comment by manishgarg1** [comment]
Hi @artxach, did you inspect the DOM of the span to look if you had the correct classes applied. I just added a span to my page with the following code and it was bold   

<span class="ms-fontSize-xl ms-fontWeight-semibold">sometext</span>
