### ISSUE TITLE
Formatting list views hideColumnHeader doesn't work on List webpart

### ISSUE THREAD

**Issue by panggio** [SharePoint/sp-dev-docs#5281]
## Category
- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question
> In SharePoint Online, Is there a way to hide the columns header of a formatted list view when displaying in the List webpart

## Environment details
 - Platform: SharePoint Online

**Comment by OS-Lee** [comment]
You could deploy [react-script-editor](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor) to hide the header when you add list to modern page by List webpart

```
<style>
div.ms-DetailsList-headerWrapper{
display:none;
}
</style>
```

![image](https://user-images.githubusercontent.com/40845109/73807739-71898e80-4808-11ea-9a2d-e2497f120c55.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by panggio** [comment]
Thanks! I'm guessing that's not a supported customisation? Meaning, any updates from Microsoft to the platform could rollback this change

**Comment by bcameron1231** [comment]
@panggio  Correct. This wouldn't be a supported customization and could break in the future.

**Comment by andrewconnell** [comment]
@bcameron1231 @thechriskent This isn't possible today with view formatting, correct?

**Comment by bcameron1231** [comment]
hideColumnHeader should remove the headers. This is a recent bug re-introduced, and looks to be a duplicate of #5226

**Comment by shagra-ms** [comment]
The issue is now fixed.
