### ISSUE TITLE
LookupMulti Projected Field as a ViewField in CAML

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#5282]
I'd like to request an update on the Join element article to list capabilities (or limitations, as the case may be)  for `LookupMulti` type fields.

I can create a join-based query on a lookup column, but as soon as I change the lookup field to allow multiple values, the query fails with
> Value does not fall within the expected range.

I guess the following statement answers my question but I think it should be more explicit/prominent.
> so Type always has the value "Lookup"

In my mind a single or multi lookup fields are both "Lookup" (could just be me though).

I've spent a lot of time trying to string together 4 "entities" with CAML and I don't think it is practical in SharePoint. In SQL, I could get away with having just two link tables (associative entities) but in SharePoint, I'd need to also have a link list to link the two other link lists (exponential duplication). If there was a way to create joins on `LookupMulti` fields, the data structure could be simplified but I don't think that's possible.

### In Summary
It would have helped me a lot if this (and the linked to "Joins and Projections") article explicitly mentioned that many-to-many relationships can not be described using joins and projections.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14ff1bdb-b935-d84d-be8b-969f6d485292
* Version Independent ID: 2eb41473-f5c3-e351-3280-686324c3a7aa
* Content: [ProjectedFields element (View)](https://docs.microsoft.com/en-gb/sharepoint/dev/schema/projectedfields-element-view)
* Content Source: [docs/schema/projectedfields-element-view.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/projectedfields-element-view.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I think what you're trying to do (join multiple things together) is going beyond what is the intended use-case for SharePoint lists. It's hard in docs to explain every single scenario that works or doesn't work. This is one of those cases.

FWIW, this debate has been going on for years. The general guidance from Microsoft & the community is to not use lists as replacements for database(s) table(s) which are more suited for complex joins.
