### ISSUE TITLE
Hub site on navigation preserves SPFx header display state of associated site

### ISSUE THREAD

**Issue by wvstrien** [SharePoint/sp-dev-docs#5283]
## Category

- [x] Bug

## Describe the bug

https://williamvanstrien.blogspot.com/2020/01/peculiarity-with-hub-sites-spfx-header.html

Following information architecture situation:
1. A communication site registered as hub site
2. Another site (can be communications or modern teams site) associated with the hub site
3. The associated site has some site info tagging; which is visualized to site visitors through a SPFx Header extension
4. The hub site either does not have site info, or the values that it has are different from that in the associated site

Effect of this situation is that when one navigates within the hub association from associated site to hub and vice versa, it can in its (cached / preserved) header display false / incorrect information...

Cause: in an hub, only on 'first-visit' the SPFx Header(s) are executed Inspecting the network traffic, it is evident that the displayed header info is not refreshed on navigating 'within hub context': the SPFx Header is not re-executed. Apparent only on explicit 'first-visit' to an Hub assocation - hub or associated site; then SPFxHeader components are executed. And on any navigation 'within' the hub; the (visual) state of the SPFxHeader is preserved; on same notice as the 'hub navigation.

## Steps to reproduce

set up information architecture as described, navigate to associated site, SPFx header displayed. Then via hub navigation go to the hub site: SPFx header visual state remains.

## Expected behavior

SPFx header refreshes its display state on navigating to other site or even page

**Comment by andrewconnell** [comment]
Can you clarify what you mean by "SPFx header"? Are you referring to SPFx application customizer extensions & the top placeholder?

**Comment by wvstrien** [comment]
Correct: SPFx extension, displayed in top place holder.
See referred post for screenshots that visualize; but generic you can identify by lack of triggering the SPFx extension on navigating back from associated site to hub (monitor via F12)

**Comment by andrewconnell** [comment]
@wvstrien said:
> See referred post for screenshots that visualize

I know this may seem trivial, but can you please post the complete issue in this thread instead of linking to a blog post? It's harder to track when the thread is fragmented like this...

**Comment by andrewconnell** [comment]
This seems like it's related to the `navigatedEvent` & the page routers partial page loading. Impossible to tell without seeing your extension, but have you seen this: https://www.eliostruyf.com/handling-navigation-in-a-sharepoint-framework-application-customizer/

**Comment by wvstrien** [comment]
> This seems like it's related to the `navigatedEvent` & the page routers partial page loading. Impossible to tell without seeing your extension, but have you seen this: https://www.eliostruyf.com/handling-navigation-in-a-sharepoint-framework-application-customizer/

Andrew, thanks for referring to this; I applied the construct suggested by Elio and now on every navigation in the (logical) hub information architecture, our header correct updates itself with info that is valid for the hub-navigated site

  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    // https://www.eliostruyf.com/handling-navigation-in-a-sharepoint-framework-application-customizer/
    this.context.application.navigatedEvent.add(this, this._renderPlaceHolders);

    return Promise.resolve();
  }
