### ISSUE TITLE
SharePoint Framework list subscription for 'List'

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-docs#5288]
Subscribe to list notifications does not support '**List**'? 

When subscribing to the 'List', I am getting the error - Error: **NotificationUrl not found in response**
It works fine with Document library but not with a list. 

I read the consideration as well which says 'you can subscribe to events from libraries (but not lists)'. 
But will it be supported in the upcoming spfx versions? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ade5442-a0dc-e57c-bde0-876396aba7f1
* Version Independent ID: 50aa69e3-8a27-dac1-5c60-1d5309a60a33
* Content: [Subscribe to list notifications](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications#feedback)
* Content Source: [docs/spfx/subscribe-to-list-notifications.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/subscribe-to-list-notifications.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Harshagracy** [comment]
https://www.youtube.com/watch?v=WhxIWNSCE6I&start=109&end=128

**Comment by andrewconnell** [comment]
No plans have been publically shared for supporting lists. Would make for a good user voice request though.

**Comment by Harshagracy** [comment]
Thanks @andrewconnell . Submitted the User voice request. Link: https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/39642082-subscribe-to-list-notifications-for-lists
