### ISSUE TITLE
Build pipeline with Webpack 2?

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#529]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

Are there any news about upgrading spfx build pipeline to webpack 2?

Webpack 1 is officially deprecated. Many folks upgraded and use webpack 2 on different projects.    

When working with spfx sometimes you need to add additional webpack loader or to do any other fine tuning for webpack task. It will be much more convenient to do that with webpack 2, because this is current version of webpack, no need to switch "context" back to webpack 1, also the schema for webpack 2 is much more understandable. 
One another caveat with webpack 1 that some loaders don't guarantee backward compatibility with webpack 1.   

Taking all this into account I really would like to see webpack 2 in the build pipeline.

**Comment by jonathanhotono** [comment]
I definitely look forward for webpack to be updated. Plus sass will need to support sourcemap by default so on dev mode it doesn't reference it straight to <style> but instead the scss file.

**Comment by nickpape-msft** [comment]
Hi @s-KaiNet, we have upgraded to Webpack 2.0 and this will be in the next release. @iclanton can comment more.

**Comment by jonathanhotono** [comment]
@nickpape-msft do we have the sass sourcemaps enabled as well on the next release?
