### ISSUE TITLE
Querying large lists by code using a query

### ISSUE THREAD

**Issue by gszdev** [SharePoint/sp-dev-docs#5291]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is it possible to query large lists by code (REST, CSOM, ...) to get over the 5000 items list view threshold limit, like in the modern experience list views?

Background:
We are using indexed columns inside the query and the result of the **first** part of the query will return more the 5000 items. So we get the 5000 items threshold error. Same happens for the view using classic experience. BUT NOT using the modern experience.

Using Fiddler I see that the following REST API is used:
/_api/web/GetListUsingPath(DecodedUrl=@A1)/RenderListDataAsStream?@A1=''&View=&TryNewExperienceSingle=TRUE

Can we get details about this api (parameter, samples, ...) to use it in our code.

#5232 
@andrewconnell, Yes you right the method is documented. But are there any information to get around the 5000 items list view threshold like modern experience list view does?

I see the following URI-Parameter "TryNewExperienceSingle" in Fiddler which I cannot find in the documentation.

Additional information to the question:
[SharePoint Online List View Threshold](https://joannecklein.com/2017/07/25/sharepoint-online-list-view-threshold/)

## Environment details
SharePoint Online

**Comment by andrewconnell** [comment]
Not that I'm aware of... you need to use filters & paging to make the resulting data set smaller.

I'm not familiar with the parameter you mention... I'm guessing it's likely not documented as it's not officially supported for 3rd party use

**Comment by gszdev** [comment]
Thanks @andrewconnell
We are using a filter (index column) and paging (page size 30 items) already.
The problem is that the list contains a lot more then 12,000 items and the first result of the query returns about 6,000 items.

May someone else can give us a hint.

**Comment by ng-marcus** [comment]
This is a really useful discussion: https://github.com/pnp/pnpjs/issues/532  .  I had to switch to using  RenderListDataAsStream as even with indexes applied, the filtered value had > 5000 items so I hit the threshold.    Using RenderListDataAsStream works great and has proper paging build in too.

**Comment by gszdev** [comment]
Thanks @ng-marcus 
With the information in [renderListDataAsStream paging](https://github.com/pnp/pnpjs/issues/532) we get the hint we needed.
