### ISSUE TITLE
Unable to automatically add a SPFx customizer extension app to modern sub sites?

### ISSUE THREAD

**Issue by Hal93** [SharePoint/sp-dev-docs#5292]
## Category
- [ x] Question

## Environment details

- Version: Sharepoint Online 0365
 - OS: Windows 10
 - Browser: Chrome v79
 - Tooling: Powershell, PnP, VS Studio Code,
 
## Question

I am unable to automatically add a SPFx customizer extension app to modern sub sites (new and existing). 

**PNP Attempt**

- I got the SPFx added to the global app catalog, its deployed successfully. (Not tenant deployed)
- I installed the app to the site collection successfully 
- By looping over all subwebs within site collection, I added the spkkg and this worked for existing subsites but not newly created ones.

<img width="594" alt="WinDev1907Eval__Running_" src="https://user-images.githubusercontent.com/13520440/73849648-32683700-4822-11ea-9e7b-e4ff498fe5e4.png">

<img width="754" alt="WinDev1907Eval__Running_" src="https://user-images.githubusercontent.com/13520440/73848804-b5888d80-4820-11ea-8ee6-cc53e9339e54.png">

- I even tried changing the -Scope flag to site and tenant but no still no luck. App can only be found on the global app catalog.

**Tenant Wide Deployment**
- Correct me if I'm wrong but tenant wide seems to only make the SPFx app available to all site and subsite catalogs but doesn't add the app? 

- Could I use tenant wide deployment to add SPFx app across all site collections and subsites, will this remove the need to go into site contents > add an app for new subsites?

**So the following questions are below,** 

1) Is it possible to add SPFx extension app to a site collection and for existing and newly created subsites, the app is automatically added? (Without having to go to every subsite and click site contents > add an app everytime)

2) Tenant Wide Deployment. Does this only make the SPFx app available in all the site / subsite catalogs? It does not automatically add the app to site contents?

3) If this is possible, can you please provide me an example?

It looks like it relates to this open issue https://github.com/SharePoint/sp-dev-docs/issues/2418

Thanks very much in advance for any help with this issue

**Comment by bcameron1231** [comment]
I would use Add-PnPCustomAction to add the extension to your Site Collection. Then specify the scope to site, it should automatically apply the Extension through the custom action on all sub sites.

`Add-PnPCustomAction -Title "MyExtension" -Name "MyExtension" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentId c0ab3b94-8609-40cf-861e-2a1759170b43 -Scope Site

**Comment by Hal93** [comment]
Thanks very much for your reply @bcameron1231 . So I tried that, the PS code runs fine no errors. But I'm not seeing the app added in the site collection at all? 

<img width="823" alt="Site_Contents" src="https://user-images.githubusercontent.com/13520440/73854832-07ceac00-482b-11ea-9d24-65d92991a8eb.png">

By going to site catalog > add an app, I can see it does exist it just didn't add to site contents. I tried creating subsite but it still didn't have the app added

The ClientSideComponentId, is this found in package-solution.json? Which ID is it, within features node?
<img width="749" alt="config_package-solution_json_·_master_·_sharepoint___sharepoint-online-spfx-app-customizer_·_GitLab" src="https://user-images.githubusercontent.com/13520440/73856396-4e250a80-482d-11ea-9f0c-0cecac8de780.png">

Or does clientSideComponentId, title, name come from ClientSideInstance.xml? I have no name specified, is this required?

<img width="578" alt="sharepoint_assets_ClientSideInstance_xml_·_master_·_sharepoint___sharepoint-online-spfx-app-customizer_·_GitLab" src="https://user-images.githubusercontent.com/13520440/73856600-9b08e100-482d-11ea-94a7-7c1b621366cc.png">

Thanks :)

**Comment by bcameron1231** [comment]
The ClientSideComponentId is the id inside of your extension manifest.json file.

Adding the extension via a custom action on your Site Collection isn't going to Install the App on the sub sites in Site Contents. The App is on the Site Collection, but rendered on the subsite using the Custom Action Scope parameter.

**Comment by Hal93** [comment]
Thanks @bcameron1231 sorry I'm new to all this. Starting to understand it, 

So are saying execute, `SharePointPnPPowerShellOnline\Install-PnPApp -Identity $appId` to install the app on the site collection 

And then run `SharePointPnPPowerShellOnline\Add-PnPCustomAction -ClientSideComponentId $extensionGUID -Title $extensionTitle -Name $extensionTitle -Location ClientSideExtension.ApplicationCustomizer -Scope Site -Connection $connection` which will render the custom action on existing and new subsites?

**Comment by bcameron1231** [comment]
Yes. Adding the custom action on the site collection with the Scope of Site, should render it on all subsites of that site collection

**Comment by Hal93** [comment]
Thanks @bcameron1231 , I have tried adding the custom action site scoped but it isn't working as expected. My JS isn't being loaded on the page and its subsites?

Wonder should I be adding the custom action like below? 
https://tahoeninjas.blog/2018/04/18/automatically-deploy-spfx-extension-to-multiple-sites-using-powershell/

![Blank](https://user-images.githubusercontent.com/13520440/73928553-32704180-48cb-11ea-9351-11a8e284fb37.png)

**Comment by bcameron1231** [comment]
It's hard to say without seeing what you are doing. Installing the App and Registering the Custom Action on the Site Collection with the Site scope, works for me. It applies the extension to the sub sites.

**Comment by justin0522** [comment]
[here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions#controlling-tenant-wide-deployment-from-app-catalog-site-collection) is the Controlling tenant wide deployment from App Catalog site collection docs
App catalog site collection contains a Tenant Wide Extensions list, which can be used to manage SharePoint Framework Extension activations in the tenant. Check and config this list, then try is again.

**Comment by patmill** [comment]
I believe that Justin and Beau have described things.  The tenant wide deployment doesn't explicitly _add_ the app to all sites, but the tenantwideconfiguration applies to all sites / subwebs, which achieves the same thing.
