### ISSUE TITLE
Tenant admin

### ISSUE THREAD

**Issue by metro-mark** [SharePoint/sp-dev-docs#5293]
## Category
- [x ] Question

## Question
I am trying to provision any templates found in the lookbook site and it requires a user to be a tenant admin. Does anyone know how to add a user to become a tenant admin? I have looked as much as I could but drawing blank so far. Thank you.

## Environment details
SharePoint Online

**Comment by andrewconnell** [comment]
https://docs.microsoft.com/en-us/office365/admin/add-users/assign-admin-roles?view=o365-worldwide

**Comment by metro-mark** [comment]
I know how to add a user to a role. My question was more specific to the tenant admin role. What is that role name equivalent to?

**Comment by andrewconnell** [comment]
Global admin / SharePoint admin
