### ISSUE TITLE
Custom web part suddenly not available on newly created Modern Online site

### ISSUE THREAD

**Issue by iBrooks** [SharePoint/sp-dev-docs#5295]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I've been creating sharepoint sites for internal use and I have this custom part I've made that adds our zendesk widget and hides some things with css. I have created multiple new sites recently and the part has always been available to immediately add to the page.

Just today I went to create yet another site, went to add the part, and it's not available. Looking at the part in the app catalog reveals no errors. I've googled a couple variations of the phrase 'custom web part not appearing' and not found anything helpful. The strange thing is that my random HelloWorld web part that I had started with IS available to add to the newly created site. I'm pretty confused as to why this newly created site can clearly use SOME custom parts, but not all?

Please help, feeling very lost as I have no errors to work on, just silent failure.

**Comment by andrewconnell** [comment]
Lots of questions:
- Did you install the app that contains the web part into the new site, or was the package deployed to all sites?
- What type of site did you create that worked?
- What type of site did you create that didn't work?
- Was it just the one site, or multiple sites?
- Did show up over time?
- Did it happen for new sites that were created?

@iBrooks said
> hides some things with css

BTW, that's considered DOM manipulation and is not supported.
