### ISSUE TITLE
list-formatting - style property cannot have any of the following characters ( : & ; ! .

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#5296]
## Category
- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question
 
> I can see couple answers that the style properties cannot support any of the following characters: (, :, &, ;, ! exception and that is the use of the rgba css function:

Scenario 01: background-image URL property is not supported because URL contains ( character. 
`"style": {
                "display": "inline-block",
                "width": "8px",
                "height": "8px",
                "background-image": {
                    "operator": "?",
                    "operands": [
                        {
                            "operator": "==",
                            "operands": [
                               "@currentField",
                               "expectedValue"
                            ]
                         },
                        "url('/site/Shared Documents/imageName.jpg')",
                        ""
                        ]
                }
            }`
Scenario 02: calc() method is not supported because calc contains ( character. 

`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "span",
      "txtContent": "@currentField",
      "style": {
        "padding": "0 8px",
        "white-space": "nowrap"
      }
    }
  ],
  "attributes": {
    "class": "sp-field-dataBars"
  },
  "style": {
    "padding": "0",
    "height": "calc(100% + 22px)",
    "width": "100%"
  },
  "debugMode": true
}`
![image](https://user-images.githubusercontent.com/11626905/73941265-ee089400-4912-11ea-8a0c-c51c27c5326d.png)
Refer the URL 
- https://github.com/SharePoint/sp-dev-docs/issues/1161#issuecomment-404240884
- https://github.com/SharePoint/sp-dev-docs/issues/3696#issuecomment-478178019

However, the character ( is supported in style proprieties - refer color property 
`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "debugMode": true,
  "txtContent": "@currentField",
  "style": {
    "color": "=if([$DueDate] <= @now, '#ff0000', '')"
  }
}`

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#apply-formatting-based-on-date-ranges 

> Is background-image style property support in column formatting? as this property calls URL() which contains ( character.
`background-image: url("paper.gif");` 

If no, I will update the document accordingly - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference

@ shagra-ms @thechriskent  &PopWarner   

*Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Issue #1161 outlines this issue accordingly, and even states that using url() is not supported (by @shagra-ms).

 @Shagra-ms already noted that he will updated the documentation for this. There is no action necessary.

**Comment by PrasadKasireddy** [comment]
@bcameron1231 - do you have any idea why the character ( is supported in style proprieties - refer color property
`{ "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json", "elmType": "div", "debugMode": true, "txtContent": "@currentField", "style": { "color": "=if([$DueDate] <= @now, '#ff0000', '')" } }`

**Comment by bcameron1231** [comment]
That's because the character is used in an Excel Style conditional expression =if(), which is supported in column formatting.
