### ISSUE TITLE
Meeting Client requirements

### ISSUE THREAD

**Issue by marc-hopkins** [SharePoint/sp-dev-docs#5298]
The biggest problem at least what I see is in a tenant environment.. is when there is a need to add default elements to all pages. For instance the client has a requirement for security banners on all pages. There isn't currently (as I understand) a mechanism to AUTOMATICALLY add something like mandatory security banners on O365.. not on prim.. on a tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926ab97b-0406-116a-9b44-59df02beee7d
* Version Independent ID: 3094c3cf-cd16-518e-48fc-095fb14036dd
* Content: [Customizing ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages#feedback)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-pages.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Can you  describe a bit more what you mean by mandatory security banners? In Modern SharePoint, we can use SPFx Application Customizers to load a banner at the top of modern pages.

**Comment by Jerry0527** [comment]
You can use the PnP PowerShell to add a banner for both Site Collection/Web Scope, please take a look at this example:

[Add a banner to your SharePoint Online site with a custom message using SharePoint Framework.](https://github.com/bschlintz/spfx-message-banner)
