### ISSUE TITLE
Cannot create link to file on UNC path in column formatting

### ISSUE THREAD

**Issue by calebmil** [SharePoint/sp-dev-docs#5299]
## Category
- [X] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

I am trying to create a dynamic link to files on a Shared Drive.  Because of data sensitivity, our business does not want these files stored in the cloud.  When I try to use JSON Column Formatting to create a link based on a value in a list item, I am unable to use a UNC path (e.g. \\host\drive\folderpath\somefile.zip).  When I try to put anything that is not a URL for a web-based system, the column shows a blank value because of some arbitrary validator not liking the UNC path.

## Environment details (if applicable)

- SharePoint Online with a modern list
- Windows 10
- Latest version of Edge

**Comment by bcameron1231** [comment]
Correct, this is not supported

Only http, https and mailto protocols are allowed for JSON  Column formatting.
