### ISSUE TITLE
Cannot find module jquery?

### ISSUE THREAD

**Issue by rolandoldengarm** [SharePoint/sp-dev-docs#53]
I'm following [the tutorial](https://github.com/SharePoint/sp-dev-docs/wiki/Add-an-external-library-to-a-web-part) to include jquery. I've added the required line to config.json, and the import line to the web part, but I still get this error:
````
Error - typescript - src\webparts\reactWebPart\components\ReactWebPart.tsx(5,20): error TS2307: Cannot find module 'jquery'.
````
What am I doing wrong here?

**Comment by iclanton** [comment]
Did you download the typings for jQuery using `tsd install jquery --save`?

**Comment by rolandoldengarm** [comment]
Oh dear... Yes that was it. Sorry, and thanks.
