### ISSUE TITLE
Custom Actions in Modern Experience

### ISSUE THREAD

**Issue by arnabchat90** [SharePoint/sp-dev-docs#530]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Is there any thing planned for adding a spfx webpart or custom js on all pages in a site, basically a replacement for custom actions for Modern Team Sites?

**Comment by VesaJuvonen** [comment]
Hi,
we are working on a modern replacement around the custom actions and JSLink, like mentioned in our roadmap page at http://aka.ms/spfx-roadmap. We don't have public schedule for this right now, but we  should have more public information available soon.

**Comment by arnabchat90** [comment]
@VesaJuvonen Thanks Vesa!!
