### ISSUE TITLE
SPFx + Office Fabric UI + DetailsList

### ISSUE THREAD

**Issue by sanjayadsure** [SharePoint/sp-dev-docs#5300]
## Category
- [X] Question
- [ ] Typo
- [ ] Additional article idea
- [] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

Hi,

I have a custom list and want to the items in detailsList control of Office Fabric UI. Can someone please let me know how to do this with an example. I went through the Office Fabric UI page but not able to understand how we can fetch items in practical scenario from custom SharePoint list and bind it to detailsList?

Thank you in advance.

Regards,
Sanjay

**Comment by bcameron1231** [comment]
This is a fairly loaded question. Sounds like you may need to spend some more time learning SharePoint Framework and how to make calls against SharePoint's REST API.

The SPFx documentation walks you through how to make calls to SharePoint to retrieve items from lists. I suggest running through these tutorials.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-sharepoint

From there, it should be pretty straightforward on how to bind data to a UI Fabric Details List. If you still struggle, there are some open source samples you can view.

https://github.com/SharePoint/sp-dev-fx-webparts/ .
