### ISSUE TITLE
Sharepoint 2019 offline column formatting 

### ISSUE THREAD

**Issue by rsantosveloso1** [SharePoint/sp-dev-docs#5301]
## Category
- [ x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Can I use this column formatting described in https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting in an intranet (without internet access) sharepoint server?

Basically i am not sure how to give access to the following schema https://developer.microsoft.com/json-schemas/sp/v1/column-formatting.schema.json
if the server does not have access to the internet.

Should i download the file and copy it to the sharepoint server? if so, where/how?

**Comment by andrewconnell** [comment]
@thechriskent @bcameron1231 You know if the schema is used for anything other than with IntelliSense in editors? IOW, if removed, or downloaded & point to an internal URL, will that work?

**Comment by bcameron1231** [comment]
Yup, the column formatting works even if you specify an empty schema.

**Comment by shagra-ms** [comment]
@andrewconnell & @bcameron1231 that is correct. The schema.json file is required only for IntelliSense and column formatting on SP2019 would work even without access to internet.

@rsantosveloso1 If you want IntelliSense in your formatter authoring tool, you can create a copy as you mentioned.

Please do let me know if you have any further questions.
