### ISSUE TITLE
How do you do this to an existing MS web part  Example  the Embedded web part

### ISSUE THREAD

**Issue by Urgeoverkill** [SharePoint/sp-dev-docs#5302]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
-
## Question
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column

>
## Submission guidelines (delete this section before submitting)

> - All suggestions or bugs are welcome!
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

*Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
You cannot convert an out of the box webpart to use full width. However the embed webpart Is a fairly simple webpart that could be recreated with a custom SPFx web part.

**Comment by Urgeoverkill** [comment]
Thanks    Not what I wanted to hear of course.   where would I find
tutorials to make such an easy web part?

**Comment by bcameron1231** [comment]
Here is all the information on getting starting with SPFx. Development skills will be required.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview
