### ISSUE TITLE
data-interception off no longer working as per documentation

### ISSUE THREAD

**Issue by ervingayle** [SharePoint/sp-dev-docs#5307]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
I have been using data-inception off for links in my application customizer that renders application specific navigation in the top placeholder within a Communications site. This has been working for some time but it looks like this has stopped working in the last 30 days.

Referencing the documentation here specifically: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

## Environment details (if applicable)

Modern Communications site
Application customer that renders to top placeholder
Links with data-inception="off" work on the home page, viewlsts.aspx page but if you click into a document library or list they links with data-inception="off" do not work and the page refreshes.

Tested in all browsers:
Chrome
Firefox
Edge
Edge dev version

**Comment by andrewconnell** [comment]
Can you provide additional context such as the SPFx version you are using? That was in the original issue template that apparently was removed when you submitted this issue.

**Comment by ervingayle** [comment]
Hello @andrewconnell ,

I have two solutions that are installed, both Application Customizers running SPFx version 1.8.2. However, this functionality was working, I would say up to late December.

**Comment by ervingayle** [comment]
Hello @andrewconnell , 

Do you have any update or idea on what could be causing this behavior?

**Comment by andrewconnell** [comment]
Nope... I ping'd MSFT to see if they had any insight... no update to share ATM.

**Comment by andrewconnell** [comment]
It appears to work, but is has broken on list & library app pages (which is where you're using it). I made engineering aware of it...

**Comment by DanyLaco** [comment]
Any Update of this issue?

**Comment by patmill** [comment]
Sorry for the delay - we are looking into this now.

**Comment by KeviCheng** [comment]
So it appears you may have a typo in your original post. With data-inception="off" the page is supposed to refresh on navigation, and navigation via page router happens only when you do not specify data-inception="off" AND you start from a SPFx page. I have investigated this, and it seems that the feature is working as expected.
