### ISSUE TITLE
@types/es6-promise  deprecated

### ISSUE THREAD

**Issue by fonbrauzen** [SharePoint/sp-dev-docs#5308]
## Category

- [x] Bug

## Describe the bug

please remove adding a reference in package.json to @types/es6-promise since it is deprecated "This is a stub types definition for es6-promise (https://github.com/jakearchibald/ES6-Promise). es6-promise provides its own type definitions, so you don't need @types/es6-promise installed!"

## Steps to reproduce

1. generate new project in yo generator
2. go to package.json
3. in dependecies is "@types/es6-promise": "0.0.33",
4. on [npm page for this package](https://www.npmjs.com/package/@types/es6-promise) "This is a stub types definition for es6-promise (https://github.com/jakearchibald/ES6-Promise). es6-promise provides its own type definitions, so you don't need @types/es6-promise installed!"

## Expected behavior

this dependency absence probably should be checked the presence of es6-promise explicitly.

**Comment by PrasadKasireddy** [comment]
It seems to be duplicate - https://github.com/SharePoint/sp-dev-docs/issues/2249#issuecomment-580044282
@johnguy0 your views please

**Comment by andrewconnell** [comment]
@PrasadKasireddy is correct, this is a dupe and as stated in the referenced issue, will be resolved in the next SPFx version.
