### ISSUE TITLE
Desperately needed - Custom Content Type Grouping

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#5309]
{
  "verb": "createContentType",
   "group":"Something other than 'Custom Content Types', please. 🙏🏻",
    --rest--
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#define-a-new-content-type)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by MarkStokes-outlook** [comment]
I agree. +1

**Comment by bcameron1231** [comment]
I suggest heading over to UserVoice and voting on this.

https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/36320569-enhance-createcontenttype-with-group-property-to-d
