### ISSUE TITLE
Uncaught (in promise) undefined (Classic Page)

### ISSUE THREAD

**Issue by webtechy** [SharePoint/sp-dev-docs#531]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Web part should load in both classic and modern pages.

#### Observed Behavior
Web part does not load in classic pages (Chrome or IE).

> [SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.RequirementsFormWebPart.g_60ab8107_010d_49f9_823c_f9e2db87f58a,Error: ***Failed to load component "ffaa6a0e-9eba-40a0-bec5-226d1db53caf" (RequirementsFormWebPart). Original error: ***Failed to load entry point from component "ffaa6a0e-9eba-40a0-bec5-226d1db53caf" (RequirementsFormWebPart). script resources due to: {1}. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-loader_en-us_c6f9eaa435c045364ff414fb3b4a7714.js:88:24230) [<root>] at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25414) [<root>] at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:25855) [<root>] at e._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:55700) [<root>] at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js:146:46098 [<root>]

Complains on (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-17.008/sp-webpart-base_en-us_c1717fe3a65c3606bc67c06f229b0eb5.js):

`e.prototype.setPropertyPaneControl=function(e,t){}`

sp-webpart-base_en-us_c1717fe….js:146 Uncaught (in promise) undefined

#### Steps to Reproduce
See source code here:

https://github.com/webtechy/sp-dev-fx-webparts/tree/master/samples/froala-simpleinput

I have created a "Requirements" list, added a "Requirement Details" multiline field (should run with out that anyway), set the list to classic mode, then added the "RequirementsForm" to the "New Form" page and hidden the default form.

Let me know if you would like access a dev SharePoint site you can see this running (inbox me).

(There is a separate issue with running this web part in IE even in a modern page but work sin Chrome in a modern page).

Possible reasons: Some cachine issue, or, some pre-GA code floating about.

**Comment by alex-buys-github** [comment]
Any progress on this?  I am experiencing something very similar to this.
