### ISSUE TITLE
NodeJs download link not working

### ISSUE THREAD

**Issue by gxy-dev** [SharePoint/sp-dev-docs#5310]
The nodejs download link returns 404 
https://nodejs.org/dist/latest-v10.x/node-v10.18.1-x64.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
The latest v10.x version of the NodeJs is v10.19.0, please download file using the below link.

[https://nodejs.org/dist/latest-v10.x/node-v10.19.0-x64.msi](https://nodejs.org/dist/latest-v10.x/node-v10.19.0-x64.msi)

**Dennis Guo
Microsoft SharePoint Community Support**
