### ISSUE TITLE
On Partial Page load , 'Anchor on page headings H1,H2,H3' are not appearing.

### ISSUE THREAD

**Issue by mmohamedbasith** [SharePoint/sp-dev-docs#5312]
## Category

- [x] Bug

## Describe the bug

On Partial Page load, 'Anchor on page for headings font H1,H2,H3' are not appearing. If we do a manual full refresh , it is appearing.  [Feature ID:53198 ](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=O365&searchterms=53198)is broken.

**On Partial page load,** 

![image](https://user-images.githubusercontent.com/28502351/74236945-5fbc5580-4cf8-11ea-9f13-c762974f08d9.png)

**On Full page load,**

![image](https://user-images.githubusercontent.com/28502351/74237078-b590fd80-4cf8-11ea-8ce3-79a9fd4212b7.png)

## Steps to reproduce

1.Create a page with title 'Page1'
2. Add text webpart and insert text as "Section 1" with Heading 1 Font
3.Below Section 1 add a link 'Page2' (should redirect to page2.aspx)
4.Create a page with title 'Page2'
5. Add text webpart and insert text as "Section 1" with Heading 1 Font
6.Below Section 1 add a link 'Page1' (should redirect to page1.aspx)
7.Go to Page1.aspx (do full refresh). you will see anchor link present near to 'Section 1'.
8.Now go to page2.aspx by click on the link page2 .It will redirect to page2.aspx (Particial refresh). In Page 2 , you will not see anchor link present near the heading "Section 1".

## Expected behavior

Anchor should appear for H1,H2,H3 fonts in the page irrespective of partial or full page load.

Refer:https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=O365&searchterms=53198
this feature is broken. I have tested this in two different tenant.

*Thanks for your contribution! Sharing is caring.*

**Comment by patmill** [comment]
This would appear to be a product issue, and not specific to developing on top of SharePoint.  As such, I'd recommend opening a ticket with Support.
