### ISSUE TITLE
After upgrading to SPFx v1.10, webpart creation fails

### ISSUE THREAD

**Issue by sallaadithya** [SharePoint/sp-dev-docs#5314]
## Category
- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

## Question
When upgraded SPFx version to v1.10, creation of webpart fails.

## Environment details (if applicable)

- OS: Windows 10
- Framework: Node.js v10.15.3
- Browser(s): [e.g. Chrome v79, Safari v22, FireFox v31, IE v11, Edge, Chromium Edge v79]
- Tooling: SPFx v1.10.0
 
After I upgrade from @microsoft/generator-sharepoint from v9 to v10, tried creating a webpart, there were few warnings related to Office-UI-Fabric, and when I hit gulp serve, nothing works.

Also, I have updated gulp and yo with -g command added to latest.

![image](https://user-images.githubusercontent.com/39057966/74154063-ed843c00-4c37-11ea-91aa-ac609e534ef6.png)

![image](https://user-images.githubusercontent.com/39057966/74153937-9e3e0b80-4c37-11ea-814d-df3d01808229.png)

*Thanks for your contribution! Sharing is caring.*

**Comment by sallaadithya** [comment]
Quick update:
I just uninstalled the latest version (1.10) and installed 1.9.1, created a web-part, everything is working fine as previously did!!

**Comment by Jerry0527** [comment]
Please use the command below to install the latest SPFX generator:

npm install @microsoft/generator-sharepoint@latest -g

After update, it will be able to generate the SPFX 1.9.1 solution

[Update SharePoint Framework packages](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages)

**Comment by sallaadithya** [comment]
> Please use the command below to install the latest SPFX generator:
> 
> npm install @microsoft/generator-sharepoint@latest -g
> 
> After update, it will be able to generate the SPFX 1.9.1 solution
> 
> [Update SharePoint Framework packages](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages)

I'm not sure whether you understand my issue. I clearly said that I upgraded from 1.9.1 to v1.10 (obviously by running the above command from documentation) by which I faced the issue and later uninstalled the package (v1.10) and specifically installed the v1.9.1, then I was able to create and run the webpart. 
After having this long sentence writing, my real intention is to tell that on the same machine, v1.9.1 is working fine where 1.10 was failing.

**Comment by patmill** [comment]
Can you see what the error was in the first screenshot?

**Comment by Jerry0527** [comment]
Sorry for the misunderstand, I just test to upgrade to 1.10.0 and the package.json will like:
![Snipaste_2020-02-12_18-32-23](https://user-images.githubusercontent.com/28797671/74326812-06baf300-4dc6-11ea-9b3c-f0205d1bcb84.png)

Now I suggest you could change the dependencies to 1.10.0 for "@microsoft/.." and delete node_module folder, then run npm install to see if it works to build.

**Comment by andrewconnell** [comment]
After upgrading the project, did you delete your **node_modules** folder, any package lock files, rerun `npm install` to get the dependencies and try again?

If that didn't work, have you tried creating a new v1.10 project and building it to see if that works? If so, that means there's something wrong with your project that you're upgrading.

Can you also share all globally installed packages? (`npm list -g --depth=0`)

**Comment by sallaadithya** [comment]
Actually, I was trying to test v1.10 by creating a new webpart, so as not to disturb my existing applications.

Here are the steps I followed:
1. I have already v1.9.1 installed on my local desktop (Laptop) and we were developing few webparts for our ongoing development for a reputed company.
2. When I heard about the recent release, I wanted to give a try to develop our upcoming webparts on v1.10, and probably upgrade the exisiting ones.
3. So I opened cmd prompt, upgraded the version by typing "npm install -g @microsoft/generator-sharepoint". Nothing I added more lines, just left the cmd to complete.
4. Then I restarted the machine (Not necessary though), created a new webpart by typing and following the rest in cmd as: yo @microsoft/sharepoint
5. All I saw were Warnings (as attached in above), and when I hit gulp serve, nothing worked.
6. Then I uninstalled v1.10 by tying "npm uninstall -g @microsoft/generator-sharepoint" and re-installed by typing as "npm install -g @microsoft/generator-sharepoint@1.9.1", then created a sample webpart, on hit of gulp serve, it's working fine.

PS: Please confirm me if v1.10 is working for you, so that I can again test on my personal computer.

**Comment by andrewconnell** [comment]
@sallaadithya said:
> Please confirm me if v1.10 is working for you, so that I can again test on my personal computer.

Yup... v1.10 works great for me... no issues.

**Comment by NPM57** [comment]
I am having exact same issue with SPFx v1.10 when creating new web part.
I had SPFx v1.9.1 it was working fine until I updated to v1.10
![image](https://user-images.githubusercontent.com/20369626/74697784-8114c880-5247-11ea-8436-c8e7f2ca8601.png)

**Comment by sallaadithya** [comment]
> @sallaadithya said:
> 
> > Please confirm me if v1.10 is working for you, so that I can again test on my personal computer.
> 
> Yup... v1.10 works great for me... no issues.

This is working for me on my personal laptop.
Steps I followed:
Step 0: Already I have 1.9.1 installed on my computer
Step 1: Open cmd, Uninstalled by typing "npm uninstall -g @microsoft/generator-sharepoint"
Step 2: Install the latest version by typing "npm install -g @microsoft/generator-sharepoint"
Step 3: Created the default webpart HelloWorld, on hit of gulp serve, ran with out issues.

But not sure, when not following the step 1, gives an error.

**Comment by sallaadithya** [comment]
> I am having exact same issue with SPFx v1.10 when creating new web part.
> I had SPFx v1.9.1 it was working fine until I updated to v1.10
> ![image](https://user-images.githubusercontent.com/20369626/74697784-8114c880-5247-11ea-8436-c8e7f2ca8601.png)

Hello,

I recommend you to please uninstall the npm package first, then install later (No need of restarting computer required).
Hope it can fix the issue.

**Comment by NPM57** [comment]
> > I am having exact same issue with SPFx v1.10 when creating new web part.
> > I had SPFx v1.9.1 it was working fine until I updated to v1.10
> > ![image](https://user-images.githubusercontent.com/20369626/74697784-8114c880-5247-11ea-8436-c8e7f2ca8601.png)
> 
> Hello,
> 
> I recommend you to please uninstall the npm package first, then install later (No need of restarting computer required).
> Hope it can fix the issue.

Hi there,
Thanks for your suggestion but can you specify the node version that you are using for v1.10
I ma using node 8.0 which compatible to spfx 1.9.1

**Comment by sallaadithya** [comment]
> Hi there,
> Thanks for your suggestion but can you specify the node version that you are using for v1.10
> I ma using node 8.0 which compatible to spfx 1.9.1

Node version: v10.15.3
npm version: 6.4.1

**Comment by NPM57** [comment]
> Node version: v10.15.3
> npm version: 6.4.1

Thanks, got it fixed

**Comment by andrewconnell** [comment]
@sallaadithya [said](https://github.com/SharePoint/sp-dev-docs/issues/5314#issuecomment-587244419):
> But not sure, when not following the step 1, gives an error.

Which is what? What's the error you get this time?

**Comment by sallaadithya** [comment]
> @sallaadithya [said](https://github.com/SharePoint/sp-dev-docs/issues/5314#issuecomment-587244419):
> 
> > But not sure, when not following the step 1, gives an error.
> 
> Which is what? What's the error you get this time?

I haven't got any error this time.
But if I skip the step 1, ie., directly updating the package by running "npm install -g @microsoft/generator-sharepoint", and creating a webpart, gives me warnings as stated in my 1st comment, and hit on gulp serve nothing works.

**Comment by andrewconnell** [comment]
- The upgrade instructions don't specify you have to uninstall anything... just reinstall the latest and you're good. But this shouldn't matter...
- warnings !== errors... you can ignore those.

I'll close this then as you're not having an issue and have resolved your issue.
