### ISSUE TITLE
Unable to provision Learning Pathway site

### ISSUE THREAD

**Issue by Ogresham** [SharePoint/sp-dev-docs#5315]
## Category
- [X ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

>I am attempting to provision a learning pathways site for our SharePoint.  Every time I attempt to do so it says provisioning site and it just spins.  I have left it sitting for hours with no response or change.  I have checked all prerequisites and I cannot figure out what I am missing. Any suggestions will be helpful.  I do not get any type of error messages and I have tried to do this using Edge, Chrome and Firefox.

## Environment details (if applicable)

>SharePoint online 

- OS: Windows 10
- Framework: [e.g. .NET Framework v3.x, .NET Core v3.x, Node.js v6/v8/v10/v12]
- Browser(s): Tried Chrome and Edge
- Tooling: [e.g. VS Code, SPFx v1.10.0, Visual Studio 2019]

**Comment by andrewconnell** [comment]
Please submit your issue to the Learning Pathways project as this repo is for general SharePoint development questions: https://github.com/pnp/custom-learning-office-365
