### ISSUE TITLE
Guidance about managing dev/prod versions of the .sppkg?

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#5318]
I can't seem to find any guidance about how we should ensure a separation of Dev and Prod .sppkg files. They both need to be added to the app catalog, so having separate Dev and Prod versions of them would presumably require changing the package name and various IDs back and forth to alternate between one build and the other.

In SharePoint Online, this can be solved by using site collection-scoped app catalogs and separate site collections. What about in on-premises? Should we use separate Web Applications for Dev and Prod?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f0c08f-4169-7d32-c93c-a20c4b14bb4d
* Version Independent ID: fe3faf7d-b5f2-cb22-2d5e-6650124094f1
* Content: [Team-based development on the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework#feedback)
* Content Source: [docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/team-based-development-on-sharepoint-framework.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@JLRishe says:
> so having separate Dev and Prod versions of them would presumably require changing the package name and various IDs back and forth to alternate between one build and the other.

Correct. If you are deploying them to the same tenant, you need to manually make sure the IDs of the package & components are different (I'd also make sure the names of the packages & components aren't the same to make it easier to find them). 

Ideally, you have two environments (DEV/PROD). If you only have one, you need to have two different packages & components.
