### ISSUE TITLE
Can't deploy the package in an app catalog site

### ISSUE THREAD

**Issue by tchagan** [SharePoint/sp-dev-docs#5319]
The comment after packaging the app states "Now deploy the add-in in the app catalog site." I've tried this and I'm prompted with the initial problem "Your tenant administrator has to approve this app", so you cannot deploy the add-in, is there a step missing here, how can the add-in be deployed to the app catalog if I still get the prompt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a36ebb-4574-73c7-e927-488025b980fb
* Version Independent ID: 2cfe998d-fafc-7559-1b6b-7737def6ec36
* Content: [Developing using Tenant permissions with App-Only in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online)
* Content Source: [docs/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @tchagan 

I'd like to reproduce this error. Can you please share your app file?

Regards,
Jarbas

**Comment by OS-Lee** [comment]
Hi,

When you get tenant administrator has to approve this app, click 'Request Approval' to submit your request.
![image](https://user-images.githubusercontent.com/40845109/74411746-f7e04900-4e76-11ea-8d56-d4927a0a278b.png)

Go to your tenant app catalog site to approve your request.

https://yourtenant.sharepoint.com/sites/yourAppCatalog/AppRequests/ActiveRequests.aspx

![image](https://user-images.githubusercontent.com/40845109/74411898-442b8900-4e77-11ea-84eb-afd799342945.png)

**Lee
Microsoft SharePoint Community Support**
