### ISSUE TITLE
write-manifests.json cdnBasePath relative url

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#532]
- [ ] Question

Can we set the cdnBasePath with the server relative url instead of full FQDN if we opted to use normal sharepoint document library?
sample:
`"cdnBasePath": "/apps/relativeurl"`

**Comment by wictorwilen** [comment]
If you have a need to deploy to multiple tenants, without hardcoding the server name - see this workaround: https://www.npmjs.com/package/spfx-build-url-rewrite

**Comment by zplume** [comment]
@jonathanhotono I've used a relative cdnBasePath for a SPFx web part for simple deployment across multiple environments (dev, test, uat, prod for same company) and this works well.
The rewrite package wictor links to would be useful when using varying CDN hostnames though.

**Comment by iclanton** [comment]
Apologies for not seeing this thread sooner.

I don't believe there's any reason you wouldn't be able to use a server-relative path in write-manifests.json. Have you having issues using one?

**Comment by jonathanhotono** [comment]
All good guys. I'm able to use server relative url for cdnBasePath.

**Comment by peterremote1980** [comment]
This is meaningless, because i still need to recompile for each of my customer, who has different tenant. It just saved me to edit the json file manually.
