### ISSUE TITLE
SPFx Application Customizer: Partial page loads causes navigatedEvent event to trigger before navigation occurs

### ISSUE THREAD

**Issue by a-sam-randall** [SharePoint/sp-dev-docs#5321]
## Category
- [x] Bug

## Describe the bug

I think I have found a bug when using the navigatedEvent in the SPFx extension (i.e., an application customizer). In the event details of the [documentation](https://docs.microsoft.com/en-us/javascript/api/sp-application-base/applicationaccessor?view=sp-typescript-latest) for the navigatedEvent it states that 'The event fires after a top-level PageContext has navigated to a new page', however I have noticed that when navigating between SharePoint Modern Site Pages that event is firing before the navigation occurs. Going between Site Pages seems to only cause part of page to reload, and in this scenario it is causing the event to fire in the navigatedEvent before the navigation to the new page occurs. Can you please confirm if this is a bug?

## Repro Steps

I noticed the issue when I added the code below into the onInit method of the SPFx extension. When navigating between Site Pages I noticed that `window.location.href` was logging out the previous page href not the href of the page I was navigating towards, indicating that the event was firing before navigation to the new page occured.

```ts
    this.context.application.navigatedEvent.add(this, () => {
      console.log('Navigated Event:', window.location.href);
    });
```

## Environment details

- OS: [Windows 10]
- Framework: [Node.js v10]
- Browser(s): [Chrome v80, Chromium Edge v80]
- Tooling: [VS Code, SPFx v1.10.0]

**Comment by patmill** [comment]
Yes, seeing that as well.  It looks like an underlying issue that manifests itself in the customizer.  For example, if you set your network to slow in the debug tools, and just navigate from one page to another, the address bar updates before the page switches.  I'll follow up with the team that works on that.

**Comment by ThomasVB96** [comment]
Are there any updates yet? We are currently facing the same issue.

**Comment by AJIXuMuK** [comment]
Seems to be fixed by now. The event is fired after the navigation occurs.
