### ISSUE TITLE
Shared external library sometimes not loaded before webpart is being loaded

### ISSUE THREAD

**Issue by jaspermeijaard** [SharePoint/sp-dev-docs#5324]
## Category

- [x] Bug

## Describe the bug

I have a project with multiple webparts. Some of the webparts use the `@ckeditor/ckeditor5-build-classic` NPM package which exports a class `ClassicEditor`. The requirement of this package is that it should be loaded once; and so shared among all webparts. I followed these steps to make it shared: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library#share-a-library-among-multiple-web-parts

The bug that occurs is that sometimes the import is a class and sometimes not:

Expected:

```
console.log(ClassicEditor) // class Sb extends Sd{}
```

Not expected:

```
console.log(ClassicEditor) // r {}
```

## Steps to reproduce

1. Have multiple webparts with React in place (created with the YO command)
2. Install NPM package `@ckeditor/ckeditor5-build-classic`
3. Share the build script as external in `config.json` with:

```
  "externals": {
    "ckeditor": {
      "path": "node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js",
      "globalName": "ClassicEditor"
    }
  }
```

4. Import the shared library in multiple webparts with

```
import ClassicEditor from 'ckeditor'
```

5. Put the `console.log` in a React render

```
<div>
  {console.log(ClassicEditor)}
</div>
```

6. Run `gulp serve`

7. Add different webparts with this shared dependency on the same page. 

8. Notice the difference and see the bug occur.

## Expected behavior

I expect the output of the import always the same:

```
console.log(ClassicEditor) // class Sb extends Sd{}
```

## Developer environment

- OS: Ubuntu 18
- Framework: Node.js v8/v10
- Browser(s): Chrome v80
- Tooling: VS Code, https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

**Comment by patmill** [comment]
Hey @jaspermeijaard - That is somewhat old guidance.  I'll make a note to get it updated to point to the actual Library component type that came out a while ago.  It will be much better:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview is the overview, and here is a tutorial
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial

That should make things much more robust for you, and avoids any sort of race condition that the browser / scripts / etc. will introduce.

**Comment by andrewconnell** [comment]
@patmill while a library component may make sense here, wouldn't two components that reference the same external library still trigger it to be only downloaded once by the module loader?
