### ISSUE TITLE
Requesting Additional MS Graph Permissions for SPFx Solution

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5327]
## Category

- [x] Bug

## Describe the bug

I noticed a weird behavior when requesting additional MS Graph permissions for my SPFx web part.
Let's say, initially I requested `Files.Read.All` and `User.Read` permissions for the app. It has been installed to the App Catalog, admin approved requests - everything works as expected.

Then I added additional permission request. In my case - `Sites.Manage.All`. Again - same process - installed, approved. But the changes took effect after few hours only (overnight). Before that I'm still getting 403.
Same happened again with `InformationProtectionPolicy.Read` permissions. And also on multiple tenants. So, it doesn't look like permission-specific or tenant-specific.

If I look at SharePoint Online Client Extensibility Web Application Principal Azure AD app - the approved permissions are there right away.

So, it's some additional level somewhere that causes such a behavior.

## Steps to reproduce

1. Create new SPFx web part and request some MS Graph permissions
2. Install the app to the App Catalog and approve permissions request
3. In a while - add additional permissions request to the app
4. Redeploy the app and approve additional permissions
5. The app will throw 403 for at least few hours for the operations related to the new permission scope.

## Expected behavior

Permissions are granted as soon as the request is approved in Admin Center (in next 10-15 minutes).

**Comment by patmill** [comment]
Could this be a problem with caching?  Ie, your client has a cached token for service A (The graph, I assume).  When you refresh your page, etc. the token already exists in local storage (yay, no need to run through the ADAL flow again.) but the token you get only has the specific scopes that were granted when it was requested.  Does that seem likely?  If you flush your cache, does the problem go away?  (@lucabandMSFT , @lahuey - does that seem likely?)

**Comment by lucabandMSFT** [comment]
I believe @patmill  is right. ADAL.JS has a default token cache for 1 hour and I believe we didn't change such default time (@lahuey  to keep me honest here).

@AJIXuMuK: just for testing purposes, if you wait 1 hour before refreshing the page, does the behavior still reproduces?

**Comment by AJIXuMuK** [comment]
Yep! Clearing the cache resolves the issue!

> @AJIXuMuK: just for testing purposes, if you wait 1 hour before refreshing the page, does the behavior still reproduces?

@lucabandMSFT I believe I waited more than hour. But it always was almost at night... so, maybe it was 59 minutes that for me was few hours :)

**Comment by andrewconnell** [comment]
🚨*Issue police on the scene* 🚨 ;)

So... would this be a bug, by design, closed?

**Comment by patmill** [comment]
This is by design, but in more recent builds, when you open a new tab you will get the new permissions.
