### ISSUE TITLE
I am getting Deployment failed

### ISSUE THREAD

**Issue by rnpramasamy** [SharePoint/sp-dev-docs#5329]
I tried to deploy package to sharepoint app catalog but I got below error:

Deployment failed.  Correlation ID: 4c9b349f-100e-a000-8f9e-cbc69e800add

**Comment by PrasadKasireddy** [comment]
@rnpramasamy 
The above information is not enough to carry out the investigation
1) Could you please check the ULS log based on above mention correlation ID.
2) Add more details about the solution and package details including the all development tools  versions.

**Note:** it would be better to understand how  to create a good issue - it would be really help us to resolve this issue quickly - https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues
