### ISSUE TITLE
🐞 "Create folder for solution" show different behaviour depending on where to create additional web part

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#5333]
## Category

- [x] Bug

## Describe the bug
When I create a new solution and select the "Create folder for solution" option the result is that two `.yo-rc.json` files exist for this solution.

![Screenshot 2020-02-12 at 18 27 10](https://user-images.githubusercontent.com/5503835/74362490-1982f700-4dc9-11ea-95bf-0fbe70fd5c89.png)

One is located in the root folder the other one is located in the create folder.

<img width="553" alt="Screenshot 2020-02-12 at 18 56 22" src="https://user-images.githubusercontent.com/5503835/74362671-623ab000-4dc9-11ea-97aa-1d92ca7a3698.png">

Now adding a new web part to an existing project let me instead of adding create a new solution and also reuse the same name.

<img width="712" alt="Screenshot 2020-02-12 at 18 58 46" src="https://user-images.githubusercontent.com/5503835/74362942-d83f1700-4dc9-11ea-9327-ba278c038196.png">

I even can select a different framework like knockout when I choose ReactJS previously.

<img width="795" alt="Screenshot 2020-02-12 at 19 05 34" src="https://user-images.githubusercontent.com/5503835/74363343-aed2bb00-4dca-11ea-816c-2f270652b854.png">

Due to the force overwrite I can even ruin a ReactJS Project with a knockout web part. This does not really make much sense to me. So there is no safety mechanism implemented that avoids this overwriting of an existing solution.

Inside the solution folder I can also choose suddenly a new framework. When I am not cautions an just click through I get another framework mixed into an existing solution.

<img width="793" alt="Screenshot 2020-02-12 at 19 10 21" src="https://user-images.githubusercontent.com/5503835/74363731-71226200-4dcb-11ea-8a53-6a0f239f7999.png">

In my opinion this is a really huge bug with the "Create solution folder" option since the beginning and can cause a lot of troubles now and in future.

## Steps to reproduce

As described above.

## Expected behavior

The bug aspect of this please make it more solid and failsafe by reading the .yo-rc.json.
The user voice aspect and easy fix is to get rid of this option at all cause it caused issues since the beginning and was never properly fixed.

**Comment by andrewconnell** [comment]
I don't think this is a bug... if you're at the root folder and run the generator again, you're not in a solution, so it makes sense that you get all the same prompts for creating a new solution. In fact, you have the exact same experience with many other generators (yo teams / yo office) & CLIs (dotnet).

It is an interesting scenario though... the generator could use a little work to catch this edge case @johnguy0.

*Makes me feel a little better with my guidance to never let the generator create a subfolder for you* :P

**Comment by StfBauer** [comment]
Bug in a sense that it do not detect that there is already a solution with the same name. I could be detected cause it is stored in that folder in the `.yo-rc.json`

It even tries to re-use the same folder when once again the "Create folder option" was selected.

_You can feel good about not recommending to use this option. 😜_

**Comment by andrewconnell** [comment]
This can fall down the "what's considered a bug" debate... not fun so I'll set it aside. Instead, I'll leave this to @johnguy0 @VesaJuvonen @patmill to decide if it's a bug or scenario that the generator should account for :)

**Comment by patmill** [comment]
This was fixed in the 1.13 release.
