### ISSUE TITLE
SPFX to convert docx to pdf

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#5338]
## Category

- [x] Bug

## Describe the bug

I am trying to convert the docx to pdf in the SharePoint framework, it is not working.

## Steps to reproduce
1. Getting item in blob format and convert to base 64

        let fileInBlob=await ComponentContextCrudDocuments.getFileBlob(connectionDetails);
        var reader = new FileReader();
        reader.readAsDataURL(fileInBlob); 
        reader.onloadend = function() {
            var base64data = reader.result;                
            console.log(base64data);
            let finalBase64Data=base64data.toString().split(',')[1];
            let encodedUrl = "u!" + finalBase64Data.toString().trimRight()
            console.log(encodedUrl);
        
           this.graphClient = await this.spContext.msGraphClientFactory.getClient();
        const results: any = await this.graphClient
        .api(`/shares/${base64String}/driveItem/content?format=pdf`)
        .version('v1.0');

        console.log(results);

## Expected behavior

results should provide the URL for the pdf but i am not getting the ulr

## Developer environment

- OS: [e.g. Windows 10, MacOS 10.15.x]
- Framework: Node js 10
- Browser(s):  Chrome
- Tooling: VS Code, SPFx v1.10.0

**Comment by nsksaisaravana** [comment]
I am using the graph client to convert the file.

**Comment by andrewconnell** [comment]
Missing a lot of context here (including what is the error), but regardless, this is a Microsoft Graph specific question, not a question specific to SharePoint / SPFx development. Please post your question to the [Graph support channels](https://developer.microsoft.com/en-us/graph/support)
