### ISSUE TITLE
Not available on Sub-sites & Cannot deploy throgh App-Catalog (App Stapling)

### ISSUE THREAD

**Issue by ramakrpr** [SharePoint/sp-dev-docs#534]
We have multiple site collections and many sub-sites within. The content authors intent to use the modern web-parts even from the sub-sites. We want the web parts to be by default available across sub-sites once installed at the root. Its a very tedious process & practically not possible to ask the site owners to install the app across all sites considering the amout of sub-sites in scope.
We observed the below issues though - to achieve the objective
1. Web parts installed in root site is not available to sub-sites. Added to App-catalog and installed in Root site.
2. Unlike the regular SharePoint Add-ins / .APP which can be installed at the app-catalog and deployed across site collections from app-catalog, when we try this with the moden web parts it fails with an exception

This is a very important capability which you might have to consider and if not will result in limited usage of the framework for large scale implementations.

**Comment by zplume** [comment]
My client needs this capability too, but it's currently not supported:
#483 (comment)
#344 (comment)

Hopefully tenant-scoped deployment (SPFx equivalent described by Pat in the 2nd link above) will be implemented soon to resolve this...
