### ISSUE TITLE
react-carousel web part

### ISSUE THREAD

**Issue by ricardocarneiro** [SharePoint/sp-dev-docs#5340]
## Category
- [X ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

Hi Folks, it is no t exactly an issue or bug, but a simple question.

Any guide or tip on how to deploy react-carousel web part to SharePoint 2019 Server?

I know I have to use 1.4.0 (1.4.1) version, but for that web part probably I have to make more changes.

## Environment details

 - OS: Windows 10
 - Framework: Node.js v10.18.0]
 - Browser(s): Chrome
 - Tooling: VS Code, SPFx v1.4.1 (1.4.0)
 
I changed spfx version in Package.json and "npm install" again, but I got  lots of errors.
Any tip?
** Error image attached **

Best, Ricardo.
![err1](https://user-images.githubusercontent.com/4666947/74426227-6e2c7d80-4e6e-11ea-9863-177acd73454e.PNG)

**Comment by andrewconnell** [comment]
Not enough context... share your **package.json** file contents.

But if you just updated the SPFx package versions, that won't be nearly enough. Not sure what project you're referring to, but if it's using a more recent version of SPFx, there are likely a lot of other dependencies that need to be rolled back (React version, type declaration package versions, etc).
