### ISSUE TITLE
Filtering in Office Fabric UI React

### ISSUE THREAD

**Issue by sang1205** [SharePoint/sp-dev-docs#5341]
Hi Team, 

I am using SPFX with React and using the Office fabric UI for design. As of now I am able to add drop down icon near to the column header in Detailslist by using ColumnActionsMode.hasDropdown. 

![image](https://user-images.githubusercontent.com/61009077/74437079-8bbd0f80-4e8d-11ea-9270-2a99739dcd05.png)
I want to show the drop down menu by clicking on the drop down icon as like below image

![image](https://user-images.githubusercontent.com/61009077/74437286-e2c2e480-4e8d-11ea-97a6-39ca5629c3e6.png)

**Comment by KaushalKhamar** [comment]
@sang1205  Can you please provide more information?

**Comment by andrewconnell** [comment]
Not clear if this is a question about SPFx (doesn't appear so) or Office UI Fabric React (appears so). If you're having an issue, please add details around your context. 

If it's a question on how to do something, respectfully you need to provide a lot more "here's what I've tried" instead of a generic "someone help me do this."

**Comment by ng-lboyle** [comment]
@sang1205 I was able to implement something like this by passing an IContextualMenu props object into the menuProps of a CommandBarItem in a CommandBar. 

Though we don't use DetailsList, we made our own list component instead, but I'm sure it can be done with a column header like that. 

So it can be done, it's just a matter of putting the right props in the right place, once I figured that out I think I finally understand Fabric, after two years of using it... 

Perhaps look at these props for DetailsList
- onColumnHeaderClick
- onColumnHeaderContextMenu

[IDetailsList documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist)

**Comment by sang1205** [comment]
> @sang1205  Can you please provide more information?

I have updated my question . Please check and let me know if you can help

**Comment by andrewconnell** [comment]
This question isn't so much about SharePoint dev / SPFx, it's more specific on how to use the Office UI Fabric React library. I suggest you please post your question to the OUIFR projects as they have more context and can likely provide a solution. Feel free to cross-link this issue.

https://github.com/OfficeDev/office-ui-fabric-react
