### ISSUE TITLE
Might be a typo

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5343]
Hello,

I see the below at the beginning of an article.

Currently, webhooks are only enabled for SharePoint list items. SharePoint list item webhooks cover the events corresponding to list item changes for a given SharePoint list or a document library.

At first, it says that it's only supported for List and immediately in the next line its says "list of a document library"

Is that a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6393d95-8c1d-2341-0cbd-282cd7016204
* Version Independent ID: b7506441-6d16-1689-91aa-e9f45a2bb9e0
* Content: [Overview of SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks)
* Content Source: [docs/apis/webhooks/overview-sharepoint-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/overview-sharepoint-webhooks.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @ravick4u ,

the documentation looks good. In the first line "Currently webhooks are only enabled for SharePoint list items." the documentation says that webhooks are only enabled for SP list items which doesn't exclude document libraries.

I hope it helps to clarify your question.

Regards,
Jarbas
