### ISSUE TITLE
🙏🏽Predefined classes comprehensive lists

### ISSUE THREAD

**Issue by ingepepe** [SharePoint/sp-dev-docs#5348]
Could you please add the full lists of available classes like the one for fields in https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#style-guidelines but for row and tile elements like:
sp-row-title, sp-row-listPadding, sp-row-card, sp-row-button, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#feedback)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
As of now, these are the available classes for row - 
sp-row-title
sp-row-listPadding
sp-row-card
sp-row-button

As of now, we do not have any classes specifically for tiles. 

I will update the docs to reflect this.
