### ISSUE TITLE
Full Code?

### ISSUE THREAD

**Issue by myerzman** [SharePoint/sp-dev-docs#5353]
Could you please share the full code to help debug errors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions#feedback)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Here is an example Application Customizer. It's about 99% identical to the Microsoft Docs tutorial you listed above. 

Maybe this will help you debug some of your issues.

https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/tutorials/app-extension#
