### ISSUE TITLE
Failure: the style values contains one or more of the following disallowed characters

### ISSUE THREAD

**Issue by rsantosveloso1** [SharePoint/sp-dev-docs#5355]
## Category

- [x] Bug

## Describe the bug
I am using  column formatting described in https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting in an intranet (without internet access) sharepoint server.

I have preceeded with some tests (examples available on the online documentation) and i didn't get the expected results as decribed on the documentation.
Basically the column formating was not working. Only when I set debug mode on i could identify the errors (see image below) 

![sharepoint issue](https://user-images.githubusercontent.com/22193484/74689432-6f95d700-51db-11ea-9eac-5b7f32e9fb47.png)

On the right side of the image is the code and on the left side the result of the debuging.
The error is Failure: the style values contains one or more of the following disallowed characters  ( : & ; ! .

Besides that the code interpreter is translating > into &gt;=20 and ' into &#39; 

However if i don't use contionals (if clause ) and for example only set a fixed color it works correctly.

I can i overcome this problem?

**Comment by PrasadKasireddy** [comment]
@rsantosveloso1 - could you please confirm which environment(SharePoint Online or 2019) are you trying?

>a) SharePoint Online - no issue it is working as expected.

>b) SharePoint 2019 - it doesn't supported.  
 >>All Excel-style expressions begin with an equal (=) sign. This style of expression is only available in SharePoint Online (not SharePoint 2019).
>>Use Abstract Syntax Tree expressions for  SharePoint 2019.

**Comment by bcameron1231** [comment]
As @PrasadKasireddy mentioned, Excel-Style expressions are not available in SharePoint 2019. This is not a bug, you'll have want to use AST expressions instead.

An example of a AST Expression can be found here.

https://github.com/SharePoint/sp-dev-list-formatting/blob/master/column-samples/number-data-bar/number-data-barAST.json
