### ISSUE TITLE
PowerBI

### ISSUE THREAD

**Issue by jmachale** [SharePoint/sp-dev-docs#5356]
It would be great to see how we can use this in Power BI data to connect to SharePoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by JarbasHorst** [comment]
Hello @jmachale

thank you for your suggestion. This documentation only describes how to set up app-only permissions. In addition, it contains two common examples which demonstrate how to request access to SharePoint using the app-only approach. From my point of view, your suggestion could be created as a separated documentation. There is already a good documentation example which demonstrates [how to call the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning) using the app-only approach. Would you like to create this additional documentation and contribute it to the community?

Regards,
Jarbas

**Comment by andrewconnell** [comment]
Thanks for the comment, but as @JarbasHorst says, this general request isn't specific for the topic of the doc, but rather an open request for a new doc page. If you have a specific question on how to do something, please feel free to create an issue, but this request isn't entirely actionable... a quick [google search](https://www.google.com/search?q=connect+powerbi+to+sharepoint+list) shows lots of hits for using SharePoint data in PowerBI.
