### ISSUE TITLE
Troubleshooting missing "Save as Site Template" option

### ISSUE THREAD

**Issue by egomadking** [SharePoint/sp-dev-docs#5358]
This article should include information to enable the "Save as Site Template" option if it is unavailable. (enabling scripts, disabling publishing, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5f465-6d87-5a7d-9b0a-7807da51d30b
* Version Independent ID: bc4f4c42-d5ba-a36a-1578-70103e14cde8
* Content: [Save, download, and upload a SharePoint site as a template](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template#feedback)
* Content Source: [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good suggestion... care to make the edit and submit a PR to help with the docs?

**Comment by bcameron1231** [comment]
My guess the reason it's not outlined is because Save Site as a Template is not supported in Modern SharePoint. Thus, disabling scripting and enabling publishing isn't a supported scenario.

If adding a PR, can you make sure it's clear (aside from the current notification at the top of the page), that the process is only for classic SharePoint sites?

**Comment by andrewconnell** [comment]
Correct... Save Site as a Template should ONLY be used for classic sites... not modern & not publishing sites.

**Comment by egomadking** [comment]
@bcameron1231 and @andrewconnell- I am a SCA in an enterprise environment that maintains our own SP16. I would be happy dig in with that specific version but I really do not have access to SharePoint online from my work environment (blocked because of DLP concerns) so do not have a larger perspective. I can see where adding this sort of content into support for an evergreen product may not be the best practice. With your last comments in mind, is there a particular way to contribute to a certain version of the documentation?

**Comment by andrewconnell** [comment]
@egomadking There's no docs for a specific version ... at least not the dev docs. The IT support (support.microsoft.com) docs might have something though.

The more I think about this, I think this doesn't fit in this article. This isn't really a dev issue so I don't think it really belongs in the dev docs.

For your specific use case, there may be specific reasons why it's not present. Namely, custom scripts are disabled / publishing is enabled. See the support article here, specifically the troubleshooting section's first **Resolving common problems**: https://support.office.com/en-us/article/create-and-use-site-templates-in-sharepoint-server-versions-60371b0f-00e0-4c49-a844-34759ebdd989

**Comment by egomadking** [comment]
@andrewconnell Thanks.
