### ISSUE TITLE
Sharepoint office ui fabric default version

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#536]
- [ ] Question

I'm trying to make office-fabric-js to coexist with office-fabric-react as I got certain apps that are ported to the new spfx on classic page that is using office-fabric-js dialog box since it's not based on react, and there are also newer apps/webparts written in office-ui-fabric-react combined together in a page.

I noticed that sharepoint online/o365 also bundled office fabric by default but I'm not sure what version it is actually using. I tried to include/reference these following files in sharepoint masterpage:
```
//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js
```
And it definitely breaks office fabric react components look and feel. I noticed that the styling of buttons, dialog boxes, etc are intermittently broken on sharepoint online as well(probably from their end).

I read the docs online:
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components
![image](https://cloud.githubusercontent.com/assets/6864547/24650922/34db4a20-196f-11e7-8796-684434cbd224.png)

And when you go to their dev github, the release notes on GA Drop:
https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-GA
![image](https://cloud.githubusercontent.com/assets/6864547/24651076/bc1a08d2-196f-11e7-98db-c2c20e2f4623.png)

^When will this be updated?

**Comment by Danny-Engelman** [comment]
Test first with FabricCore 5.0.1 (which FabricJS 1.4.0 uses by default)

then increment to FabricCore 5.1.0 

It could be FabricCore 6.0.0 (you are now referencing) is the culprit, as it introduced some breaking changes

**Comment by jonathanhotono** [comment]
Thanks @Danny-Engelman . Just found out the announcements here:
https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/office-ui-fabric-integration
and related issue here: #434

**Comment by Danny-Engelman** [comment]
https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/office-ui-fabric-integration

Interesting choice of words,  

> The primary reason for these breaks is the use of Global CSS styles in both Fabric libraries. Such conflicts need to be avoided at all cost.

>  at the current time, customer solutions cannot yet safely use parts of Fabric

> Global CSS styles and how to avoid them at all cost

> the key objective [is] to enable 3rd party developers to **safely** use Office UI Fabric styles.

The Microsoft Fabric team is doing its best to battle the Bootstrap world  
(where Google is positioning Material)

And the SPFx team is trying to put the handcuffs on Fabric?

Wonder what the world would look like if Microsoft teams worked together.
