### ISSUE TITLE
Wildcard valid domains are not accepted when using this package in AppSource

### ISSUE THREAD

**Issue by MarksPoint** [SharePoint/sp-dev-docs#5360]
We're using this manifest as a base for our application that we want to publish on AppSource. AppSource doesn't allow a manifest to use wildcard domains (e.g. *.sharepoint.com). I've removed these lines and the application still works. I'm not sure why they're necessary in the first place.
Also, it is said here (https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema) that one could also add {teamSiteDomain} as a validDomain. That should at least be a valid replacement for *.sharepoint.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good observation... checking with engineering if there's an issue with that. In fact, the other wildcards could be removed as with all the dogfood/preprod links. Will post an update & update the doc when I get confirmation on the change.

**Comment by andrewconnell** [comment]
Moot issue now as docs refer to the MS Teams docs for details on the manifest.
