### ISSUE TITLE
This document is sorely lacking examples of how to download a file or providing any sample responses!

### ISSUE THREAD

**Issue by bitsofinfo** [SharePoint/sp-dev-docs#5363]
I'm trying to figure out how to download the contents of a file from sharepoint, I come to this page and read `The following example shows how to retrieve a specific file.`.... yet there is zero information on what the actual responses look like or how i can pull down the binary content of the file. 

Please update the doc w/ this information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
`  /// <summary>
        /// Download File Via Rest API
        /// </summary>
        /// <param name="webUrl">https://xxxxx/sites/LeeLiuDevSite</param>
        /// <param name="credentials"></param>
        /// <param name="documentLibName">MyDocumentLibrary</param>
        /// <param name="fileName">test.docx</param>
        /// <param name="path">C:\\</param>
        public static void DownloadFileViaRestAPI(string webUrl, ICredentials credentials, string documentLibName, string fileName, string path)
        {
            webUrl = webUrl.EndsWith("/") ? webUrl.Substring(0, webUrl.Length - 1) : webUrl;
            string webRelativeUrl = null;
            if (webUrl.Split('/').Length > 3)
            {
                webRelativeUrl = "/" + webUrl.Split(new char[] { '/' }, 4)[3];
            }
            else
            {
                webRelativeUrl = "";
            }
           
            using (WebClient client = new WebClient())
            {
                client.Headers.Add("X-FORMS_BASED_AUTH_ACCEPTED", "f");
                client.Credentials = credentials;
                Uri endpointUri = new Uri(webUrl + "/_api/web/GetFileByServerRelativeUrl('" + webRelativeUrl + "/" + documentLibName + "/" + fileName + "')/$value");
                
                byte[] data = client.DownloadData(endpointUri);
                FileStream outputStream = new FileStream(path + fileName, FileMode.OpenOrCreate | FileMode.Append, FileAccess.Write, FileShare.None);
                outputStream.Write(data, 0, data.Length);
                outputStream.Flush(true);
                outputStream.Close();                
            }
        }`

 ```
 static void Main(string[] args)
        {
            string siteURL = "https://xxxxx/sites/DevSite";
            
            //set credential of SharePoint online
            SecureString secureString = new SecureString();
            foreach (char c in "Password".ToCharArray())
            {
                secureString.AppendChar(c);
            }
            ICredentials credentials= new SharePointOnlineCredentials("xxxxxx.onmicrosoft.com", secureString);

            //set credential of SharePoint 2013(on-premise)
            //string userName = "Administrator";
            //string password = "xxxxxxx";
            //string domain = "CONTOSO";
            //ICredentials credentials = new NetworkCredential(userName, password, domain);

            ListDal.DownloadFileViaRestAPI(siteURL,credentials,"MyDocumentLib", "test.docx", "c:\\");

            Console.WriteLine("success");
            Console.ReadLine();
```
