### ISSUE TITLE
"update a file by using the PUT method" provides zero explanation of encoding for the file

### ISSUE THREAD

**Issue by bitsofinfo** [SharePoint/sp-dev-docs#5364]
The section "update a file by using the PUT method" provides zero explanation of encoding for the file:

```
POST https://{site_url}/_api/web/GetFileByServerRelativeUrl('/Folder Name/{file_name})/$value
Authorization: "Bearer " + accessToken
Content-Length: {length of request body as integer}
X-HTTP-Method: "PUT"
X-RequestDigest: "{form_digest_value}"

"Contents of file"
```

Huh? is this url encoded data? what is it? provide real samples...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,
Sample code for your reference, the script execute in SharePoint page(script editor webpart), if you use oauth request, send the Bearer token in your request also.

`<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <input id="getFile" type="file" /><br />    
    <input id="addFileButton" type="button" value="Update" onclick="UpdateFile()" />

    <script type="text/javascript">
        'use strict';

        jQuery(document).ready(function () {

            // Check for FileReader API (HTML5) support.
            if (!window.FileReader) {
                alert('This browser does not support the FileReader API.');
            }
        });
        
        function UpdateFile() {
            // Define the folder path for this example, the file need exists in the folder
            var serverRelativeUrlToFolder = '/sites/lee/MyDoc/SubFolder';
            // Get test values from the file input and text input page controls.
            var fileInput = jQuery('#getFile');            
            // Get the server URL.
            var serverUrl = _spPageContextInfo.webAbsoluteUrl;
            // Initiate method calls using jQuery promises.
            // Get the local file as an array buffer.
            var getFile = getFileBuffer();
            getFile.done(function (arrayBuffer) {
                // Get the file name from the file input control on the page.
                var parts = fileInput[0].value.split('\\');
                var fileName = parts[parts.length - 1];

                // Construct the endpoint.
                var fileEndpoint = String.format(
                    "{0}/_api/web/GetFileByServerRelativeUrl('{1}/{2}')/$value",
                    serverUrl, serverRelativeUrlToFolder, fileName);

                // Send the request and return the response.
                // This call update the SharePoint file.
                jQuery.ajax({
                    url: fileEndpoint,
                    type: "POST",
                    data: arrayBuffer,
                    processData: false,
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),                        
                        "X-HTTP-Method": "PUT"
                    },
                    success: function (result) {
                        console.log("update done");
                    },
                    error: function (error) {
                        console.log(JSON.stringify(error));
                    }
                });
            });
            getFile.fail(onError);

            // Get the local file as an array buffer.
            function getFileBuffer() {
                var deferred = jQuery.Deferred();
                var reader = new FileReader();
                reader.onloadend = function (e) {
                    deferred.resolve(e.target.result);
                }
                reader.onerror = function (e) {
                    deferred.reject(e.target.error);
                }
                reader.readAsArrayBuffer(fileInput[0].files[0]);
                return deferred.promise();
            }
        }

        // Display error messages.
        function onError(error) {
            alert(error.responseText);
        }
    </script>`

**Lee
Microsoft SharePoint Community Support**
