### ISSUE TITLE
Sharepoint On Premise não retorna resultados de busca

### ISSUE THREAD

**Issue by alexinfnascimento** [SharePoint/sp-dev-docs#5366]
## Category

- [x] Bug
Prezados boa tarde, acabei de realizar uma instalação local do Sharepoint Server 2019 e notei que em nenhum dos sites a busca retorna resultado, já habilitei o serviço na interface de administração e mesmo assim os resultados não retornam, isto é algum tipo de erro de configuração ou bug?

**Comment by JarbasHorst** [comment]
Olá @alexinfnascimento ,

obrigado pela pergunta! Vou tomar a liberdade de traduzir sua pergunta para o inglês. Acredito que assim você encontre mais ajuda técnica.

Grande abraco
Jarbas

Translated question:
Good afternoon. I've just installed SharePoint Server 2019 locally. I noticed that in none of the sites the search returns results. I have already enabled the service in the administration interface (central administration?) and even then the results do not return! Is this a configuration error or a bug?
