### ISSUE TITLE
Deployment to Developer Site is not possible: Client Side Solutions cannot be used in this location

### ISSUE THREAD

**Issue by michel-weber** [SharePoint/sp-dev-docs#537]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I cannot deploy my SPFx-App to a developer site ("Apps in Testing").

#### Observed Behavior
After uploading my `.sppkg` file to my developer site ("Apps in Testing") - the following error message appears:
![image](https://cloud.githubusercontent.com/assets/23656762/24664135/25462248-195a-11e7-81ae-b093cb17ab3f.png)

Consequently I cannot use my SPFx WebPart on a dev site.

#### Steps to Reproduce
1. Create a developer site in your tenant
2. Create a new SPFx WebPart: `yo @microsoft/sharepoint`
3. Execute `gulp bundle --ship`
4. Execute `gulp package-solution --ship`
5. On your developer site, go to "Apps in Testing"
6. Click "+ new app to deploy"
7. Upload  `sharepoint\solution\spfx-helloworld.sppkg` from your local filesystem

#### Thoughts
For me, this is a drawback as I cannot test different versions of the same SPFx WebPart on the same tenant. 

This does not seem to be a supported use case at the moment.
It is possible with SharePoint Add-Ins, but not SPFx WebParts.
Is there another way to support this scenario? Any help is greatly appreciated.

Only option to date is, to add it to the global app catalog. But this is a high risk operation and I wouldn't do this for testing. We can use another tenant for testing - but there we won't have the same data as on our production tenant.

**Comment by mariotoffia** [comment]
+1 
I too have the exact same problem.

**Comment by xascha** [comment]
+1 also :) thanks for supporting this scenario. It would be appreciated 👍

**Comment by craghavendra21** [comment]
+1
I too have the exact same problem.

**Comment by mcmynn83** [comment]
Thanks for the feedback, we are currently looking into ways to solve this.

**Comment by patrick-blanc** [comment]
@mcmynn83 any news ?

**Comment by JeremyKelley** [comment]
We're still actively working on the solution that we're going to offer for this scenario, as soon as we can make an announcement about timing and availability we'll be sure to do so.

**Comment by MarieLePanda** [comment]
Hi, I have the same problem, any news about that ? Oh build an app with this Framework if you can't deploy, there is an other way ?

**Comment by michaelgalyon** [comment]
I'm getting the same issue.  Any news here?

**Comment by jmardoy** [comment]
Same issue. Some news about the temp work-around?

**Comment by steve1607** [comment]
+1

**Comment by JeremyKelley** [comment]
The short answer is still under development.  The longer answer is that we took a step back to make sure the solution we were going to deliver was going to meet all the needs of both developers and IT.  As soon as I have timing I can announce we'll be sure to come back and let people know.

**Comment by michel-weber** [comment]
As with good game development - it's done when it's done. I prefer quality and good design. Thank you for the feedback.

@jmardoy The temp work-around is, to use the global app catalog for deployment and do the testing on another tenant (not the productive one). In my current project we have several tenants.

**Comment by michel-weber** [comment]
@MarieLePanda Yes, you can deploy your package to the global app catalog:
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page#deploy-the-helloworld-package-to-app-catalog

**Comment by AniruddhaBapat** [comment]
How do we prevent "under development" client side apps deployed to global app catalog being available to all site collections?

**Comment by michel-weber** [comment]
@AniruddhaBapat You can deploy SPFx WebParts either [tenant wide](https://dev.office.com/sharepoint/docs/spfx/tenant-scoped-deployment) (available to all site collections) or (by default) you have to add them to each site collection (after deployment to the global app catalog) in order for them to be available.

So yes, this can be prevented.

What is not support at the moment, have a productive version running and a "under development" version side-by-side on the same tenant. At the moment you need another tenant to do this.

**Comment by AniruddhaBapat** [comment]
@michel-weber: I am sorry not able to understand. 
in my understanding is SPFx web-parts are required to be added to global app-catalog to be able to use it in any site. When it is added to global app catalog, it automatically becomes available to _all_ sites and then can be added to any site. - Is there a way to prevent it, particularly when the web-parts are under-development?

**Comment by michel-weber** [comment]
@AniruddhaBapat 
No, it is the other way around. By default it does not become available to all sites.
If you want to enable it (available to all sites), follow the link i mentioned in my last answer.

**Comment by vman** [comment]
@AniruddhaBapat Yes right now, tenant scoped SPFx webparts deployed to the tenant app catalog are available to all site collections. In one of the recent PnP calls, it was mentioned that the product team is working on a **Site Collection App Catalog** which will allow us to deploy SPFx solutions to only specific site collections. Hopefully that will come out soon.

**Comment by JeremyKelley** [comment]
Just to keep on the transparency train as I mentioned above we took a little bit of a step back from our initial implementation of the Site Collection App Catalog feature.  In essence it will still be the same (you'll get the ability to have a local app catalog in a given site collection), but we're modifying the initial steps of how you get one of those and the controls that an admin has over where they can be used.  It's still actively being worked on so it's not a feature we've forgotten about or delayed for any reason other than to make it a better feature.  Thanks for your patience!

-Jeremy Kelley

**Comment by jmardoy** [comment]
Well, my SPFx WebPart integrate authentication matters under Azure AD between client app on SPO and Azure Web API (througth ADAL JS). So testing on other development tenat isn't so easy. I'll try a development package on the Production App Catalog. If you can find better workaround for me, please tell me. Thanks everyone!

**Comment by VladHaroun** [comment]
You should create a site collection App Catalog from central admin.



![apps](https://user-images.githubusercontent.com/32766150/31541700-d3b475fe-b00f-11e7-8298-f6c9229772ee.png)

**Comment by michel-weber** [comment]
@VladHaroun 
The site collection scoped App Catalog is a feature not released yet (just checked)!
What you are referring to is the "Global App Catalog" (tenant scoped).

**Comment by marcocao** [comment]
@michel-weber When the above feature is available?

**Comment by michel-weber** [comment]
@marcocao The site collection app catalogs are live and available on all tenants :).

I'm closing this issue.

**Comment by marcocao** [comment]
@michel-weber is there a app catalog in each team site in a tenant? or only one under a tenant?

**Comment by michel-weber** [comment]
@marcocao Please refer to the Microsoft documentation. You have to create all app catalogs yourself - they are not automatically created.

**Comment by andrewconnell** [comment]
Refer to this @marcocao https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog

**Comment by AmayKulkarni** [comment]
I AM FACING BELOW ISSUE, WHILE PACKAGE IS ADDED:

### **Client side solutions cannot be used in this location.**

**Comment by AmayKulkarni** [comment]
> I AM FACING BELOW ISSUE, WHILE PACKAGE IS ADDED:
> 
> ### **Client side solutions cannot be used in this location.**

Any help on it?

**Comment by andrewconnell** [comment]
You're posting to a closed issue. Please open a new issue and provide context on your problem.
