### ISSUE TITLE
Single web part page not loading in iPhone

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#5375]
## Category

- [x] Bug

## Describe the bug

Adding an spfx single web part page on my site works on any browser in PC/Mac. Opening the page in iPhone opens an empty page. 
Tried with several different web parts.

## Steps to reproduce

Build an spfx web part that allows to be hosted in a single web part page.

Create a page based on your web part. 

Open in iPhone browser - web part is gone. 

## Expected behavior

Page should load the content.

## Developer environment

SPFx 1.8.1 used among other versions. 
iPhone XS Max used to get the error.

**Comment by andrewconnell** [comment]
Believe dupe ref: #4968
