### ISSUE TITLE
IOSX/Safari MSGraphClient To view Information on this page, you need to verify your identity

### ISSUE THREAD

**Issue by half-naan** [SharePoint/sp-dev-docs#5376]
## Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

When using MSGraphClient on Safari non-private mode the user gets the following error on yellow bar at the top of the page. "To view the information on this page, you need to verify your identity. Click to provide additional credentials"

**Expected or Desired Behavior**
The MsGraphClient should not request additional credentials.  This error is happening even after the user has just logged in.  This only occurs in Safari.  The API call works fine in IE, Chrome, and Firefox. 

- OS: MacOS 10.14.6
- Framework: SharePoint Framework MSGraphClient
- Browser(s):  Safari 13.0.5
- Tooling: SPFx 
 
## Submission guidelines (delete this section before submitting)

**Steps to Reproduce**
SharePoint Online
SPFx WebPart fetching data using MSGraphClient. 
Example 
```
var client = await this.context.msGraphClientFactory.getClient();
    var p = new Promise<string>(async (resolve, reject) => {
    let query = client
        .api("/me")
        .version("v1.0")
        .select("displayName,mail,userPrincipalName,id");
        let callback = (error: GraphError, response: any, rawResponse?: any) => {
                    reject(error);
          } else {
            // console.log(response);
            resolve(response);
          }
        };
      await query.get(callback);
    });
```

**Comment by half-naan** [comment]
Hi.  It has been 4 days and no have not heard a response.  Any recommendations or alternatives?

**Comment by andrewconnell** [comment]
@half-naan do you have a screenshot of this?

Also, need more context... what version of SPFx?

**Comment by half-naan** [comment]
we are using version 1.10.0 and attached is the screenshot.  Thank you!
<img width="1583" alt="screenshot" src="https://user-images.githubusercontent.com/57302140/75477107-c634ab00-5969-11ea-94f3-1ddb2d5d96e7.png">

**Comment by half-naan** [comment]
Hi. Have you guys been able to reproduce the issue? Thank you.

**Comment by ng-marcus** [comment]
This only happens when prevent cross-site tracking is enabled (the default for Safari):

![image](https://user-images.githubusercontent.com/20163757/76324983-b197d180-62de-11ea-9669-e8f41f2a8b26.png)

**Comment by edenruffellNG** [comment]
Has there been any progress with this?

**Comment by Mosabov** [comment]
Hi team,
has there been an update to this topic yet? mainly users who are using iPads and iPhones are being affected by it.

**Comment by patmill** [comment]
Sorry for the delay.  The behavior for Safari and other 3p cookie blocking browsers will be a redirect on page load to get the authentication, and a redirect back to the original page to use it.  The previous banner was also expected as design.

**Comment by half-naan** [comment]
Dear Pat.  Thank you for fixing it.  I can confirm that the redirect is working properly and the banner is no longer showing. 
Cheers!
