### ISSUE TITLE
Powershell code snippet for this page please

### ISSUE THREAD

**Issue by merly-cortez** [SharePoint/sp-dev-docs#5378]
Hi, Can we have Powershell version for the code snippets provided please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code#feedback)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
If you want to learn about CSOM PowerShell, please get started from here:
[CSOM SharePoint PowerShell Reference and Example Codes](https://social.technet.microsoft.com/wiki/contents/articles/29518.csom-sharepoint-powershell-reference-and-example-codes.aspx)
[SharePoint CSOM Scripting in PowerShell](https://www.timlinenterprises.com/sharepoint-csom-scripting-in-powershell/)

**Comment by JarbasHorst** [comment]
Hello @merly-cortez 

this [documentation](https://docs.microsoft.com/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code) only provides examples using C# or SQL. Can you provide detailed information about your request? Sorry if I misunderstood your question.

Regards,
Jarbas

**Comment by JarbasHorst** [comment]
Hello @merly-cortez 

sorry, now I understood your request 😀 As @Jerry0527 said, there are already a lot of blog posts covering your request. If you would like to have examples based on PowerShell, that would be a great opportunity for you to contribute to our community. Does this sound interesting to you?

Regards,
Jarbas

**Comment by andrewconnell** [comment]
Thanks for the comment @merly-cortez, but this page is about CSOM, not PowerShell. As @JarbasHorst mentioned, there are lots of community posts on the topic and if you have a specific question, feel free to ask it. This isn't the proper channel for requesting new docs.
