### ISSUE TITLE
Updates are currently disallowed on GET requests.  To allow updates on a GET, set the 'AllowUnsafeUpdates' property on SPWeb.

### ISSUE THREAD

**Issue by LeonardoDavidisc** [SharePoint/sp-dev-docs#5379]
## Category

- ERROR MESSAGE

## Describe the bug

I get this error message every time I want to create an App in the App Catalog

"Updates are currently disallowed on GET requests.  To allow updates on a GET, set the 'AllowUnsafeUpdates' property on SPWeb.
"

**Comment by JarbasHorst** [comment]
Hello @LeonardoDavidisc 

I did a quick google search and found this: https://sharepoint.stackexchange.com/questions/20317/updates-are-currently-disallowed-on-get-requests-to-allow-updates-on-a-get-set. Can you provide the code you are using? It is difficult to provide assistance only having the error message 😀

Regards,
Jarbas

**Comment by tplive** [comment]
@JarbasHorst I get this error message when I try to add an App Catalog from the SharePoint Admin center, on this URL: https://my-o365-tenant-admin.sharepoint.com/_layouts/15/online/CreateAppCatalog.aspx
