### ISSUE TITLE
unable to give permission

### ISSUE THREAD

**Issue by marloesdekrom84** [SharePoint/sp-dev-docs#5381]
The API management page gives an error: Could not retrieve Global Service Principal ID Error: Error: {} when the page is opened. No request is pending. I've used the exact code from this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642064a1-1971-d88b-6eeb-3bcde4333383
* Version Independent ID: 11fbb2ac-f682-e963-a07a-a28c9cb3d9d8
* Content: [Building SharePoint Framework solutions, which use Microsoft Graph APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-microsoft-graph-apis#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This isn't a developer issue... it's going to be hard to troubleshoot it in this forum. Suggest you open a support request from your M365 tenant admin portal.
