### ISSUE TITLE
Browser(chrome) is crashed while uploading large file size

### ISSUE THREAD

**Issue by deveshkrsingh** [SharePoint/sp-dev-docs#5383]
Chrome Browser (Version 80.0.3987.106 (Official Build) (64-bit)) is crashed when uploading a large document file(100MB+).It is working fine for smaller files.I am on windows 10(16GB RAM)I am following this article and using 

> Code example 2: Upload a file in the same domain by using the REST API and jQuery

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery

Browser is crashed as soon as POST method is sent from addFileToFolder is called.Nothing in console and network tab when  **addFileToFolder**  is called.
![image](https://user-images.githubusercontent.com/5374728/75411716-303b5900-5946-11ea-86c7-e3bccf7dbf2a.png)

 ```
function addFileToFolder(arrayBuffer) {
    // Get the file name from the file input control on the page.
    var parts = fileInput[0].value.split('\\');
    var fileName = parts[parts.length - 1];

    // Construct the endpoint.
    var fileCollectionEndpoint = String.format(
        "{0}/_api/sp.appcontextsite(@target)/web/getfolderbyserverrelativeurl('{1}')/files" +
        "/add(overwrite=true, url='{2}')?@target='{3}'",
        appWebUrl, serverRelativeUrlToFolder, fileName, hostWebUrl);

    // Send the request and return the response.
    // This call returns the SharePoint file.
    return jQuery.ajax({
      url: fileCollectionEndpoint,
      type: "POST",
      data: arrayBuffer,
      processData: false,
      headers: {
        "accept": "application/json;odata=verbose",
        "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
        "content-length": arrayBuffer.byteLength
      }
    });
  }
```

**Comment by andrewconnell** [comment]
Not surprising, but need additional context about your environment.

**Comment by bcameron1231** [comment]
Agreed. In my experience with large file uploads, 100MB is a lot of data to load into a browser. Most browsers, including Chrome and Firefox both will crash when you hit 100MB limit.

With large files, I would recommend using the chunked method of file uploads. This is supported both in REST and CSOM, but you may have a better experience if you use PnPJs chunked file uploads.

This is my preferred method for uploading large files to SharePoint, using PnPJs.
https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Files#adding-files

**Comment by andrewconnell** [comment]
Furthermore, Look at the Graph API for resumable uploads... well documented and intended for files > 4MB
