### ISSUE TITLE
Use React People picker in a React project

### ISSUE THREAD

**Issue by ASpiteri-BCGov** [SharePoint/sp-dev-docs#5389]
## Category
- [x] Question

## Question

Hello, is it possible to use a component such as the people picker your team developed, in a regular React App?  I am developing a React App that has a form, everything works fine but I wanted to use the PNP people picker in my app as a component as it would save time.  Is this possible?

## Environment details (if applicable)

SharePoint 2016 on premise 
React App
Not an SPFx webpart

- OS: [Windows 10]
- Framework: [NET Framework v3.x, .NET Core v3.x, Node.js]
- Browser(s): IE, Chrome
- Tooling: [VS Code, React]

**Comment by andrewconnell** [comment]
Unfortunately, this isn't the right forum for this question. Please post that question to the PnP reusable controls project's repo's issue list.

I believe the answer is NO as that library is written to run in an SPFx context. It's open-source so you can see how it was done and create your own though.
