### ISSUE TITLE
Is it possible to host create ASP.NET Core applications on SharePoint Online?

### ISSUE THREAD

**Issue by DreamITSoftware** [SharePoint/sp-dev-docs#5394]
Is it possible to host create ASP.NET Core applications on SharePoint Online?

**Comment by luismanez** [comment]
Unless I'm missunderstanding the question, you can't host a asp.net core application in SharePoint. In SP you can only host what is called a SP Hosted App (https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-add-ins), and that means you can´t use Server side code in there.
If you have an asp.net core app, you can create a Provider-Hosted App (https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins), but you have to host your app externally (i.e: Azure web app)

If you specify a bit more about your scenario, I can try to help a bit more.

**Comment by OS-Lee** [comment]
Hi,

You can't host asp.net core web app in SharePoint online, you could register it as add-in web component(you could host asp.net core web app in azure).

[How to create SharePoint Online add-in with ASP.NET Core 2.1](https://spblog.net/post/2018/12/03/How-to-create-SharePoint-Online-add-in-with-ASPNET-Core-21)

**Lee
Microsoft SharePoint Community Support**

**Comment by DreamITSoftware** [comment]
Thanks so much guys!  All roads I've researched kept bringing me back to Provider Hosted in Azure.  I appreciate your feedback.
