### ISSUE TITLE
Load debug scripts not prompting after page reload

### ISSUE THREAD

**Issue by jrichmond4** [SharePoint/sp-dev-docs#5399]
## Category
- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I'm on version 1.10.0 and using the configuration within serve.json to debug our SPFX applications. When I run gulp serve I have some profiles to go to the correct environment, and on first load I get the 'Load Debug Scripts' prompt. However when I reload the page I'm not prompted again and lose debug capability, allow the query string params are still there. This wasn't happening previously and I'm not sure what may have changed to cause the issue, but it forces me to restart gulp every time which is obviously very inconvenient. It used to be that any time I refreshed the page it would prompt me correctly. Any help?

## Environment details (if applicable)

- OS: Windows 10
- Framework: Node.js v10
- Browser(s): FireFox
- Tooling: SPFx v1.10.0

**Comment by jhholm** [comment]
See #5385 or #5395

**Comment by rabwill** [comment]
This is working now today . I am getting the prompts and changes reflected
Browser : MS edge (chromium)
