### ISSUE TITLE
spfx become very slow when i add package "buffer"

### ISSUE THREAD

**Issue by quantrpeter** [SharePoint/sp-dev-docs#5402]
https://peter.quantr.hk/2020/02/spfx-becoming-super-slow-after-added-package-buffer/
Thanks

**Comment by andrewconnell** [comment]
With so many NPM packages available, impossible to validate every single one against SPFx. Not sure what the **buffer** package does or its dependency chain is like so unclear how it could impact the build change.

Please don't create an issue that posts to another page...
