### ISSUE TITLE
"office-ui-fabric-react": "6.189.2"

### ISSUE THREAD

**Issue by quantrpeter** [SharePoint/sp-dev-docs#5403]
if i remove "office-ui-fabric-react": "6.189.2" in package.json, in windows i can still build the project by "gulp bundle --ship". But in mac, gulp can detect the error, just windows don't. Probably a bug.
thanks

**Comment by andrewconnell** [comment]
If you just edit the **package.json** file, that doesn't do anything. You need to uninstall the package using `npm uninstall office-ui-fabric-react`.
