### ISSUE TITLE
Azure Functions in .NET Core SharePoint Online CSOM Support

### ISSUE THREAD

**Issue by miguelisidoro** [SharePoint/sp-dev-docs#5405]
Hello,

Is SharePoint Online CSOM API already supported in .NET Core?

From what I see in the web and in https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/16585795-support-net-core-with-csom, not yet.

There are some arounds, but nothing oficial:

https://sharepoint.stackexchange.com/questions/267481/execute-csom-code-from-net-core
https://github.com/seahawks8/netCoreandSharePointToPlayNice
https://sakarih.wordpress.com/2019/05/15/sharepoint-online-client-object-model-and-net-core/

Can you please confirm?

Thanks

**Comment by Jerry0527** [comment]
SharePoint Online haven't released the .NET Core CSOM Library version.
Still need to wait for it.

**Comment by VesaJuvonen** [comment]
Can confirm that @Jerry0527 noted. We have not yet unfortunately released .NET Core/Standard version of CSOM. Exact ETA still to be defined. No news at this point, which we could share.

**Comment by luismanez** [comment]
Hi @VesaJuvonen , is this comment not valid then? "_We are also working now actively on new .NET Standard version of CSOM package and are planning to get it released later this spring first as a preview release and then followed up with monthly release cycle as we do with old NuGet package._"
https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-february-2020/

I know is not an Exact ETA, but gives us some hope :) ... Working with CSOM and V1 is really terrible. Dependencies hell all around.

**Comment by VesaJuvonen** [comment]
We will keep on updating the CSOM support statement as needed. I've also written that blog post, so it's indeed valid, BUT - spring is quite broad statement and we don't want to provide more detailed ETA for now. I also provide status updates for this through the UserVoice entry at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform?query=vesa.juvonen%40microsoft.com.

We are aware of the situation and trying to prioritize this as much as possible internally. Votes on UserVoice do matter and will drive this eventually to home.
