### ISSUE TITLE
Setting Bing Maps Key on SPO tenant level?

### ISSUE THREAD

**Issue by Inveins** [SharePoint/sp-dev-docs#5407]
Hello Dev team, 
May I please ask for a confirmation whether one Bing Maps Key can be set on SPO tenant level?

(I am not talking about SP On-Prem farm level, as written in this article, or SPO web level)

I just want to know whether I can set one key on SPO tenant level, so that it can be applicable for all SPO web site collections, or I need different keys for different site collections? 

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f512d30-b714-7b3c-a567-c5c58197c636
* Version Independent ID: 5e7b7d5a-88eb-4472-074c-469441a27ae5
* Content: [Set the Bing Maps key at the web and farm level in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint)
* Content Source: [docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Yes, see the feature "tenant properties": https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties
