### ISSUE TITLE
Sharepoint on Teams Personal Tabs

### ISSUE THREAD

**Issue by crf200** [SharePoint/sp-dev-docs#5408]
I found this video from Mid-February (2020) that walks you thru the setup of a Teams App using the App Studio.
https://www.youtube.com/watch?v=WyB4MBQwICs&list=PL6AXe4uV2Of5QN7_6sB1eJ_XzT6sZJpNR&index=5&t=0s

I'm trying to embed my company intranet (SharePoint Communication Site) into an org Teams App using the principles from the video. Where I'm running into an issue is getting Teams Desktop to render the SharePoint pages. I've verified that they do work in the Teams Online. I also added a App Registration in AAD with permissions to Directory.ReadAsUser.All and grated admin consent.

Is there a setting somewhere that I'm missing?

Teams Desktop
![image](https://user-images.githubusercontent.com/49801826/75709104-436c6280-5c7f-11ea-8d03-0eca1b71a511.png)

Teams Online
![image](https://user-images.githubusercontent.com/49801826/75709184-66971200-5c7f-11ea-8039-c57fef0ee612.png)

**Comment by JarbasHorst** [comment]
Hello @crf200 

can you provide your Teams app file, please? I would like to have a look at the manifest file, since I believe that must be something wrong with the configuration.

Regards,
Jarbas

**Comment by crf200** [comment]
[CommandCenter.zip](https://github.com/SharePoint/sp-dev-docs/files/4282163/CommandCenter.zip)

Here's the zip file the manifest generates.

**Comment by JarbasHorst** [comment]
Hello @crf200 

your manifest.json file is missing configuration. All the contentURL's are mal-formatted which results in endless spinner and the webApplicationInfo property hasn't been provided. You can have a look at [this documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart) which gives you a good start for creating custom app manifests. Additionally, you can also have a look at this sample created by Bob German: https://github.com/msft-teams/tools/blob/master/getstartedapp/manifest.json. That is exactly what you are looking for.

I hope it helps.

Regards,
Jarbas

**Comment by crf200** [comment]
I'm still missing something, but I'm at least getting the endless spinning wheel. I've update the contentUrl string to both the strings belowbelow with no luck 
```https://<tenant>.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=5dsecure.sharepoint.com/SitePages/Home.aspx```
```https://<tenant>.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/SitePages/Home.aspx```

All of the pages I'm trying to connect to exist in the SitePages collection of the root SharePoint Site. ```<tenant>.sharepoint.com/SitePages/Home.aspx```

Fiddler is coming back with a 200 on the when loading any of the tabs. I noticed the manifest doesn't have any of the SSO credentials I entered. The gitHub link to the getstartedapp repo lists the property below, should I add that manually or does it make a difference
```
      "webApplicationInfo": {
        "id": "00000003-0000-0ff1-ce00-000000000000",
        "resource": "https://<YOUR TENANT>.sharepoint.com"
    }
```

**Comment by JarbasHorst** [comment]
Hello @crf200 

your app manifest might be missing something. I've created a working version which you could give a try:

```JSON
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
   "manifestVersion":"1.5",
   "version":"1.0.01",
   "id":"049abb6b-139b-4edb-beae-aa68a78c2554",
   "packageName":"com.company.commandcenter",
   "developer":{
      "name":"5D Shield",
      "websiteUrl":"https://www.company.com",
      "privacyUrl":"https://www.company.com/privacy",
      "termsOfUseUrl":"https://www.company.com/termsofuse"
   },
   "icons":{
      "color":"color.png",
      "outline":"outline.png"
   },
   "name":{
      "short":"Command Center",
      "full":"Command Center"
   },
   "description":{
      "short":"Company Intranet",
      "full":"Welcome to the Command Center with access to information accross the organization."
   },
   "accentColor":"#492970",
   "staticTabs":[
      {
         "entityId":"1003",
         "name":"Area Offices",
         "contentUrl":"https://<YOUR TENANT>.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/SitePages/Home.aspx",
         "websiteUrl":"https://<YOUR TENANT>.sharepoint.com/SitePages/Home.aspx",
         "scopes":[
            "personal"
         ]
      }
   ],
   "permissions":[
      "identity",
      "messageTeamMembers"
   ],
   "validDomains":[
      "*.login.microsoftonline.com",
      "*.sharepoint.com",
      "*.sharepoint-df.com",
      "spoppe-a.akamaihd.net",
      "spoprod-a.akamaihd.net",
      "resourceseng.blob.core.windows.net",
      "msft.spoppe.com"
   ],
   "webApplicationInfo":{
      "resource":"https://<YOUR TENANT>.sharepoint.com",
      "id":"00000003-0000-0ff1-ce00-000000000000"
   }
}
```

The webApplicationInfo property is required and if I am not mistaken, it will be used for authentication.

I hope it helps.

Regards,
Jarbas

**Comment by crf200** [comment]
ITS WORKING. The only changes was with the additional validDomains that the App Studio didn't include the different MSFT domains and I guess I didn't have them typed in correctly when I tried.

I did register and AAD App and included the client ID for the webApplicationInfo.id

Thanks for your help in getting this figured out! We now have access to our company intranet without leaving Teams!
