### ISSUE TITLE
REST endpoint determination

### ISSUE THREAD

**Issue by sganta** [SharePoint/sp-dev-docs#5409]
Hi,

I was recently trying to write an spfx webpart that lists all the SharePoint lists/libraries in a web along with their authors. I was trying to determine the REST endpoint URL I would need to query for the author of a list. I read the page titled "Determine Sharepoint REST Service Endpoint URIs". On the page, it is mentioned that the client object model is the basis to determine the method, parameters or properties to access using the REST API. 

When I browsed the CSOM API reference [here](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee545367%28v%3doffice.15%29) for Microsoft.Sharepoint.Client.List class, there was no property for Author. I do know that there is an Author property for the SPList SOM class. So I tried the following REST endpoint URL and it worked.

https://<sharepointsiteurl>/_api/web/lists/getbytitle('<list title>')/author

Please do clarify on the Sharepoint REST API documentation whether the endpoint URIs are dependent on the server-side object model or the client-side object model. If you did not intend for the 'Author' property to be available, please do leave it alone. I need it, thank you.

I understand this is similar to #1692 and #2739 but I did not find a proper answer anywhere.  I would appreciate it if there was a proper statement regarding undocumented endpoints. Since REST API is the only recommended API, I am assuming my suggestion is critical to all Sharepoint developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842f7c06-9642-df05-4ee2-644145ca25ee
* Version Independent ID: 822afabb-9f32-be7d-e9b7-efd791ba7d5d
* Content: [Determine SharePoint REST service endpoint URIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris?tabs=csom)
* Content Source: [docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
We can use the REST API URI below to get all the metadata of the REST API.

`/_api/$metadata`

Here is a tool [SharePoint REST API Metadata Explorer](https://s-kainet.github.io/sp-rest-explorer/#/)  for your reference. It helps you to explore SharePoint REST API in an easy way.

In this case, we can get all the properties of SP.List in here: [SP.List](https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.List)

**Source code of this tool from GitHub**: [sp-rest-explorer](https://github.com/s-KaiNet/sp-rest-explorer)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by sganta** [comment]
Thank you. That is really helpful. I think it will be useful to everyone if this information was made part of the documentation page (https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris?tabs=csom) this issue is attached to. My original suggestion still stands. The documentation needs to be updated.

**Comment by andrewconnell** [comment]
@sganta I'm not clear what needs to be updated. The `$metadata` operator is a default part of the OData protocol. The SharePoint REST docs don't try to duplicate the OData protocol docs, they only provide that SharePoint specific pieces to it.
