### ISSUE TITLE
Local Workbench does not able to load

### ISSUE THREAD

**Issue by dips365** [SharePoint/sp-dev-docs#5410]
## Category

- [x] Bug

## Describe the bug

gulp serve is work expected but the + webpart section does not displayed in local workbench environment.
Error as below in browser console.
**Error**
`sp-webpart-workbench-assembly_default.js:26411 [1583223717106][PropertyPaneLoader] [SPLoaderError.loadComponentError]:
***Failed to load component "f9e737b7-f0df-4597-ba8c-3060f82380db" (SPPropertyPane). Original error: ***Manifest not found for component id "467dc675-7cc5-4709-8aac-78e3b71bd2f6" and version "1.10.0".

***INNERERROR:
***Manifest not found for component id "467dc675-7cc5-4709-8aac-78e3b71bd2f6" and version "1.10.0".
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:24453:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:42171:28)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.ff4n.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:46165:21)
    at Function../sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.ff4n.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:46034:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:45372:75
H9JW.TraceLogger._writeToConsole @ sp-webpart-workbench-assembly_default.js:26411
H9JW.TraceLogger._log @ sp-webpart-workbench-assembly_default.js:26384
H9JW.TraceLogger.logErrorData @ sp-webpart-workbench-assembly_default.js:26292
(anonymous) @ sp-webpart-workbench-assembly_default.js:110542
Promise.catch (async)
get @ sp-webpart-workbench-assembly_default.js:110541
./sp-canvas.js.__WEBPACK_AMD_DEFINE_RESULT__.TOEr.CanvasStore._loadPropertyPaneModule @ sp-webpart-workbench-assembly_default.js:15532
./sp-canvas.js.__WEBPACK_AMD_DEFINE_RESULT__.TOEr.CanvasStore.initializeForEditMode @ sp-webpart-workbench-assembly_default.js:14841
CanvasStore @ sp-webpart-workbench-assembly_default.js:14818
Canvas @ sp-webpart-workbench-assembly_default.js:11679
./sp-canvas.js.__WEBPACK_AMD_DEFINE_RESULT__.7Sy0.Canvas.instantiateCanvas @ sp-webpart-workbench-assembly_default.js:11719
./sp-webpart-workbench.js.__WEBPACK_AMD_DEFINE_RESULT__.TUfI.CanvasHost.componentDidMount @ sp-webpart-workbench-assembly_default.js:7108
commitLifeCycles @ sp-webpart-workbench-assembly_default.js:92536
commitAllLifeCycles @ sp-webpart-workbench-assembly_default.js:93938
callCallback @ sp-webpart-workbench-assembly_default.js:75386
invokeGuardedCallbackDev @ sp-webpart-workbench-assembly_default.js:75436
invokeGuardedCallback @ sp-webpart-workbench-assembly_default.js:75493
commitRoot @ sp-webpart-workbench-assembly_default.js:94150
(anonymous) @ sp-webpart-workbench-assembly_default.js:95620
unstable_runWithPriority @ sp-webpart-workbench-assembly_default.js:97202
completeRoot @ sp-webpart-workbench-assembly_default.js:95619
performWorkOnRoot @ sp-webpart-workbench-assembly_default.js:95548
performWork @ sp-webpart-workbench-assembly_default.js:95456
performSyncWork @ sp-webpart-workbench-assembly_default.js:95430
requestWork @ sp-webpart-workbench-assembly_default.js:95299
scheduleWork @ sp-webpart-workbench-assembly_default.js:95113
scheduleRootUpdate @ sp-webpart-workbench-assembly_default.js:95774
updateContainerAtExpirationTime @ sp-webpart-workbench-assembly_default.js:95802
updateContainer @ sp-webpart-workbench-assembly_default.js:95859
lFMe.ReactRoot.render @ sp-webpart-workbench-assembly_default.js:96155
(anonymous) @ sp-webpart-workbench-assembly_default.js:96292
unbatchedUpdates @ sp-webpart-workbench-assembly_default.js:95661
legacyRenderSubtreeIntoContainer @ sp-webpart-workbench-assembly_default.js:96288
render @ sp-webpart-workbench-assembly_default.js:96357
./sp-webpart-workbench.js.__WEBPACK_AMD_DEFINE_RESULT__.E+gO.SpWebpartWorkbench.onRender @ sp-webpart-workbench-assembly_default.js:5437
./sp-application-base.js.__WEBPACK_AMD_DEFINE_RESULT__.n9Iz.BaseApplication._render @ sp-webpart-workbench-assembly_default.js:145974
(anonymous) @ sp-webpart-workbench-assembly_default.js:142091
Promise.then (async)
./sp-application-base.js.__WEBPACK_AMD_DEFINE_RESULT__.Q81X.ApplicationManager._initializeApplication @ sp-webpart-workbench-assembly_default.js:142084
./sp-application-base.js.__WEBPACK_AMD_DEFINE_RESULT__.Q81X.ApplicationManager._initializeApplicationWithTelemetry @ sp-webpart-workbench-assembly_default.js:142021
./sp-application-base.js.__WEBPACK_AMD_DEFINE_RESULT__.Q81X.ApplicationManager.startApplication @ sp-webpart-workbench-assembly_default.js:141977
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.fjGJ.PlatformLoader._runApplicationManager @ sp-webpart-workbench-assembly_default.js:46313
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.fjGJ.PlatformLoader._executePlatformCode @ sp-webpart-workbench-assembly_default.js:46304
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.fjGJ.PlatformLoader._startApplication @ sp-webpart-workbench-assembly_default.js:46279
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.fjGJ.PlatformLoader.startApplication @ sp-webpart-workbench-assembly_default.js:46248
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.Uk6p.BaseComponentLoader._startApplication @ sp-webpart-workbench-assembly_default.js:44734
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.KZU3.SPComponentLoader._startApplication @ sp-webpart-workbench-assembly_default.js:43420
(anonymous) @ sp-webpart-workbench-assembly_default.js:47176
Promise.then (async)
./sp-loader.js.__WEBPACK_AMD_DEFINE_RESULT__.wMLj.SPStarter.start @ sp-webpart-workbench-assembly_default.js:47165
(anonymous) @ workbench.html:28
Show 6 more frames
sp-webpart-workbench-assembly_default.js:38761 POST https://wwww.contoso.com/sites/workbench/_api/contextinfo net::ERR_NAME_NOT_RESOLVED`

![image](https://user-images.githubusercontent.com/40450958/75757083-b77a3980-5d57-11ea-91ad-68b6b94b1620.png)

> Created a SPFx Webpart with below versions.
   **Gulp** 
   CLI version: 2.2.0
   Local version: 3.9.1
  **Node**
    v10.13.0
  **npm**
    6.13.4
  **package.json**

## Steps to reproduce

> npm install
> gulp serve

## Expected behavior

>I want add web part in local workbench.

## Developer environment

**json**
> {
>   "name": "stocks",
>   "version": "0.0.1",
>   "private": true,
>   "engines": {
>     "node": ">=0.10.0"
>   },
>   "scripts": {
>     "build": "gulp bundle",
>     "clean": "gulp clean",
>     "test": "gulp test"
>   },
>   "dependencies": {
>     "@microsoft/rush-stack-compiler-3.2": "^0.6.3",
>     "@microsoft/sp-core-library": "~1.4.1",
>     "@microsoft/sp-lodash-subset": "~1.4.1",
>     "@microsoft/sp-office-ui-fabric-core": "~1.4.1",
>     "@microsoft/sp-webpart-base": "~1.4.1",
>     "@types/axios": "^0.14.0",
>     "@types/chart.js": "^2.9.15",
>     "@types/react": "15.6.6",
>     "@types/react-dom": "15.5.6",
>     "@types/webpack-env": "^1.13.9",
>     "axios": "^0.18.1",
>     "chart.js": "^2.9.3",
>     "office-ui-fabric-react": "^5.135.5",
>     "react": "15.6.2",
>     "react-chartjs": "^1.2.0",
>     "react-chartjs-2": "^2.9.0",
>     "react-dom": "15.6.2"
>   },
>   "devDependencies": {
>     "@microsoft/sp-build-web": "^1.10.0",
>     "@microsoft/sp-module-interfaces": "~1.4.1",
>     "@microsoft/sp-webpart-workbench": "^1.10.0",
>     "@types/chai": ">=3.4.34 <3.6.0",
>     "@types/mocha": ">=2.2.33 <2.6.0",
>     "ajv": "~5.2.2",
>     "gulp": "^3.9.1"
>   }
> }

### Additional context
![addwebpartmissiong](https://user-images.githubusercontent.com/40450958/75757446-628af300-5d58-11ea-9e13-12b20c5fe483.png)

**Sharing is Caring**

**Comment by sudharsank** [comment]
Hi @dips365 
I see some discrepancies in your package.json file, some modules are using version 1.10.0 and some are using 1.4.1, this is not possible, please try to use the latest version and make sure your SharePoint generator is updated to 1.10.0
