### ISSUE TITLE
I always get 403 with Bearer authentication.

### ISSUE THREAD

**Issue by voronkovsergey** [SharePoint/sp-dev-docs#5412]
I can get app catalog url using SharePointOnlineCredentials and auth cookies but when I try to use Bearer header I always get 403 response code.
My app has all possible API permissions.
Is any working sample how to do this call with bearer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7e0963-0eed-5e16-8a30-960940913071
* Version Independent ID: 1e01dca9-63e3-ce4a-0c6c-f3dd7080407d
* Content: [Retrieve the URL of the tenant app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/retrieve-tenant-app-catalog-url-rest?source=docs)
* Content Source: [docs/sp-add-ins/retrieve-tenant-app-catalog-url-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/retrieve-tenant-app-catalog-url-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Need more context... 403 indicates you don't have permissions to the App Catalog. What REST API are you trying to hit, how did you obtain the token, what permissions are in the token, etc...
