### ISSUE TITLE
How to localize content type name, list title etc.

### ISSUE THREAD

**Issue by Troi7** [SharePoint/sp-dev-docs#5413]
Missing information, how to localize all elements? List, content type...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets#feedback)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That's not missing, it's just part of the feature framework. This topic is just about provisioning assets from SPFx projects. All the existing capabilities to localize feature & element manifest files applies.
