### ISSUE TITLE
View Formatting Applied to Grouped View Prevents Display of Grouped Documents In Library

### ISSUE THREAD

**Issue by Freddy-Crypto** [SharePoint/sp-dev-docs#5414]
## Category

- [x] Bug

## Describe the bug
The mere presence of any JSON view formatting in a grouped view prevents the display of **_any_** of the items that are grouped!  How silly.

![bug4](https://user-images.githubusercontent.com/53233826/75793680-55a8d800-5d35-11ea-859b-1adad6b747bc.PNG)
![bug3](https://user-images.githubusercontent.com/53233826/75793682-56416e80-5d35-11ea-9636-9b6e2e693f0d.PNG)
![bug2](https://user-images.githubusercontent.com/53233826/75793683-56416e80-5d35-11ea-9abe-f81a98bd0f9a.png)
![bug1](https://user-images.githubusercontent.com/53233826/75793684-56416e80-5d35-11ea-9545-3dcfe6398990.png)

## Steps to reproduce

1. Create a new view in a document library.
2. Ensure that it is grouped view.
3. Save the view.
4. Ensure the grouped view is working properly by navigating to that view.
5. add the following JSON formatting to the grouped view:
```
{
  "schema": "https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json",
  "hideSelection": true,
  "hideListHeader": true
}
```

## Expected behavior

Expected behavior = the same behavior as a grouped view **_without_** JSON view formatting.

## Developer environment

- OS: Windows 10 (client),
- Framework: none (JSON is not a framework)
- Browser(s): Chromium Edge v80, Chrome v80, IE11
- Tooling: [e.g. VS Code, SPFx v1.10.0, Visual Studio 2019] 

### Additional context

SharePoint Online Production Tenant.

**Comment by shagra-ms** [comment]
@Freddy-Crypto We are unable to repro this locally, with the steps provided. Could you please check if you are able to repro this?
