### ISSUE TITLE
PropertyPaneTextField not working anymore?????

### ISSUE THREAD

**Issue by artxach** [SharePoint/sp-dev-docs#542]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
_Want to see a multiline text field on my web part property pane_

#### Observed Behavior
_Today my property pane started to fail. When i click on edit web part, i see an empty property pane opening. I have a button and a PropertyPaneTextFiled in it. When i comment the text field my property pane starts to work correct and showing me up my button. So has anything been changed? May be i need to update something? new version of SPFx?_

#### Steps to Reproduce
_Place a PropertyPaneTextField in your property pane with some label and **multiline:true** attribute_

**Comment by manishgarg1** [comment]
@artxach , thanx for the notification. We will look at this and report back.

**Comment by artxach** [comment]
@manishgarg1 , @srideshpande thanks. The other day it started working, and i don't understand where is the issue. Perhaps it is connected with the path (property key) of the TextField, but i looked at my codes and don't find anything strange.

**Comment by manishgarg1** [comment]
Hi @artxach, should we close this issue?
