### ISSUE TITLE
Potential security gap on msGraphClientFactory?

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#5424]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

I am writing an application for users to be able to create group and events and granting them access to:
1. Group.ReadWrite.All
2. Directory.ReadWrite.All

I am also getting a requirement where any users (everyone) should be able to register to a group event. I found that graph api to accept calendar event isn't capable of accepting group event therefore user must get the group and update the attendees list using Group.ReadWrite.All access. 

I noticed that any users can easily gain access to the access token on browser devtools network tab and basically gain access to read/write/delete all o365 groups and others. I know there is a time gap of 30 minutes period before the token is expired, but is it possible to configure the access token to expire on each request straight after?

![image](https://user-images.githubusercontent.com/6864547/75957845-0ae2b800-5f0f-11ea-84de-46513913b300.png)
![image](https://user-images.githubusercontent.com/6864547/75958087-9b20fd00-5f0f-11ea-9699-f9b3d669c429.png)

**Comment by andrewconnell** [comment]
There's no way to hide the access token. All requests are coming from the client, and they must include the access token to authorize the request.

@jonathanhotono said:
> is it possible to configure the access token to expire on each request straight after?
No, but [Azure AD has a preview feature](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes where you can configure the lifetime of an access token

FWIW, granting application permissions (which is what you're doing) is <IMHO>quite risky</> in a client-side scenario. Remember, *ALL* scripts in your tenant can get an access token, not just your app. This (app permissions for the SPO tenant) is generally not a recommended practice... so just FYI.

**Comment by jonathanhotono** [comment]
@andrewconnell I understand that thanks. So what you say you would recommend to wrap this under azure function / logic apps?
