### ISSUE TITLE
Interested in presenting a SharePoint Development Topic

### ISSUE THREAD

**Issue by bogeorge** [SharePoint/sp-dev-docs#5426]
I'm interested in presenting a custom Question and Answer solution we created that works within a SharePoint site (like a Communication site). It enables all members and visitors to ask, answer, moderate, follow and be notified and more.  I think it presents another alternative to a Yammer embed which some customers still hesitate on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f0bf18-5ece-8fac-f602-17500085ad26
* Version Independent ID: 087cf5a1-6c1e-1f19-b3c1-d1e661092fb3
* Content: [SharePoint Developer Community (SharePoint PnP) resources](https://docs.microsoft.com/en-us/sharepoint/dev/community/community#feedback)
* Content Source: [docs/community/community.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/community/community.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bogeorge** [comment]
I neglected to mention that it is a solution we create for a customer so I can show bits of code but it hasn't been added to sp-dev-fx-webparts yet.  However, I'm going to work with the custom to pursue open sourcing it in a few weeks so there is a chance.  :)

**Comment by VesaJuvonen** [comment]
Agreed in email - Looking forward - thx for volunteering @bogeorge.
