### ISSUE TITLE
Sites missing from search results

### ISSUE THREAD

**Issue by nozhT** [SharePoint/sp-dev-docs#5429]
We use this API to search for all websites in our tenant. Our application used daemon permissions so we can usually retrieve all the websites -- including group sites -- as long as they're not disabled to show in search results. However recently we found out there are some sites that are missing from the search results.

The sites in question were created "recently": one was created a month ago and the other 1 day ago. Both are group sites and both groups are private.

We've turned on the sites' "Allow this site to appear in Search results" option and followed the instructions in https://docs.microsoft.com/en-us/sharepoint/crawl-site-content to re-crawl the site.

Are we missing parameters in our query? For example, I've seen places saying that setting `EnableDynamicGroups:true` would help.

The query we use:
`curl -v -H 'Accept: application/json' -H "Authorization: Bearer $ACCESS_TOKEN" -G "https://$SITE_URL/_api/Search/Query" --data-urlencode "QueryText='IT-Test'" --data-urlencode "EnableStemming=false" --data-urlencode "TrimDuplicates=false" --data-urlencode "RowLimit=300" --data-urlencode "StartRow=0"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#feedback)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nozhT** [comment]
Update:

Strangely we get the same results no matter if we set `EnableDynamicGroups` to `true` or `false`, and one of the results is the `/FormServerTemplates/Forms/All Forms.aspx` of one of the missing group sites.

**Comment by wobba** [comment]
Hi,
Could you re-verify using PnP PowerShell to check the crawl log and query?

To get all sites in search use (automatically includes duplicates)  :
```
Invoke-PnPSearchQuery -Properties @{"EnableDynamicGroups"=$true} -Query "contentclass:sts_site" -All -RelevantResults
```
And you can use `Get-PnPSearchCrawlLog -Filter "https://contoso.sharepoint.com/sites/mysite"` to see crawl entries from that site (requires SP admin permissions). You can also filter on the exact UIRL for an item - it's prefix matching.

**Comment by nozhT** [comment]
I copy-pasted the query into Powershell and ran it, but the sites are still missing from the search results.

Interestingly, the crawl log shows that the sites have been successfully crawled:

```
Url             : https://tenant-url/sites/IT-Test
CrawlTime       : 1/28/2020 1:31:56 PM
ItemTime        : 1/1/0001 12:00:00 AM
LogLevel        : Success
Status          :
ItemId          : 17735237
ContentSourceId : 1
```

PnP version, in case I'm accidentally using an old version:
```
PS C:\WINDOWS\system32> Get-Module SharePointPnPPowerShell* -ListAvailable| Select-Object Name,Version| Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.18.2002.0
SharePointPnPPowerShellOnline 3.4.1812.2
```

**Comment by wobba** [comment]
Can you double which users/AAD groups are added to visitors/owners/members on the sites? And could you try go to site settings and click the "Reindex site" button on the Search and Offline Availability page? Checking the crawl log will identify if it's recrawled as the crawl time updates.

**Comment by nozhT** [comment]
As the site is an Office 365 group site, its owners is the associated group's owners and its members likewise. The group has 1 owner and 2 members, all of them users.


I'm troubleshooting for a client so I'll need to ask the client to do so (again). I'll comment here if I receive any updates.

**Comment by nozhT** [comment]
Is there any way I can re-open this? #5433 does not fix our issue.

**Comment by wobba** [comment]
@nozhT does search work from within the site itself?

**Comment by nozhT** [comment]
It works from https://tenant-name.sharepoint.com/_layouts/15/sharepoint.aspx

**Comment by wobba** [comment]
@nozhT Can you try this query from the browser as a user, and via your app-only tokens:

`/_api/search/query?querytext='contentclass:sts_site+it-test'&trimduplicates=false&enablequeryrules=false&clienttype='ContentSearchRegular'&properties='EnableMultiGeoSearch:true,EnableDynamicGroups:true'`

Also, try your original query as a user in the browser to validate. Added the multi-geo option as I'm unaware if you are multi-geo or not.

**Comment by nozhT** [comment]
The query doesn't work with the app-only tokens.

Our client has given up on this issue and I can no longer ask them to try stuff in the browser. I'm afraid I can no longer investigate the issue until another client with the same issue appears.

I greatly appreciate your help and hope I can soon get back to investigate and solve this issue.

**Comment by wobba** [comment]
If we cannot narrow down if the issue is with app-only, permissions, or parameters passed in the query, as geo, query rules etc could mess up results - we cannot really triage the issue you are seeing. Please report a new issue later once you have more information.

As you are seeing the data returned from the UI, it's either a query param error on your API call, or related to app-only.
