### ISSUE TITLE
Spfx extension is added two times when it is deployed to tenant app catalog and site design.

### ISSUE THREAD

**Issue by ashokswain27** [SharePoint/sp-dev-docs#5434]
## Category
- [x] Question

## Question
Requirement:  A a custom Header/Footer will be applied on a site when a site is created  with a custom site design and site script. It should not be available to all sites in the tenant.

Spfx extension is deployed to tenant to render a customized header and footer. Didn't check the option to "Make solution available to all sites in the organization." As this extension will be applied only for specific site design.
Followed the below github link to apply the site design. Header and footer are getting created two times on the page.
https://github.com/spblog/spfx-pnp-signalr/blob/master/PS/siteScript%20sample.ps1

Also there is no option to manage the deployment for any specific site design form "Tenant Wide Extensions list".

Got this warning while creating the package: "Warning - Admins can make this solution available to all sites immediately, but the solution also contains feature.xml elements for provisioning. Feature.xml elements are not automatically applied unless the solution is explicitly installed on a site."

**Comment by andrewconnell** [comment]
If you want a solution to be available in all site collections, you can use the tenant scoped App Catalog. If you only want it available in SOME sites, you'd use the site collection App Catalog. You wouldn't use the solution in BOTH App Catalogs... you'd only add it to ONE or the OTHER.

When using the tenant App Catalog, if you don't want to deploy it to the Tenant Wide Extensions list, delete the element manifest file **ClientSideExtentions.xml**.

**Comment by ashokswain27** [comment]
Thank you. Removed the ClientSideExtentions.xml from the package-solution.json.
The extension needs to be deployed for 100-120 site collections via Site script and site design. When the site is created, extension will be automatically applied via site script and site design.
As per the below link, solution needs to be installed on every site. The app needs to be deployed to Tenant app catalog so that the solution id can be identified.
https://github.com/SharePoint/sp-dev-site-scripts/blob/master/samples/site-register-spfx-extension/register_extension.json
It's functioning correctly now by removing ""verb": "associateExtension" step from the site script.
What's the significance of "verb": "associateExtension"?
