### ISSUE TITLE
SPFx web part can't be used in a modern page

### ISSUE THREAD

**Issue by ABoedt** [SharePoint/sp-dev-docs#5435]
## Category

- [x] Bug

## Describe the bug

I created a new web part using SPFx. When trying it out on the workbench it works fine. Adding it to a legacy page works fine. The only thing that is giving issues is when I add the web part to a modern page I get this error instead of the working web part.

## Steps to reproduce

1. Scaffold a new web part using ```yo```
2. ```gulp package-solution```
3. Add the package to the sharepoint app catalog
4. Add the app to the site collection
5. Add the app to a modern page
6. Error appears in place of the web part

![](https://i.stack.imgur.com/10jEw.png)

## Expected behavior

A working hello world web part in a modern page.

## Developer environment

- OS: Windows 10
- Framework: Node.js v10
- Browser(s): Chrome v79, FireFox v31
- Tooling: VS Code, SPFx

**Comment by andrewconnell** [comment]
Unfortunately. we need a LOT more context. What version of SPFx are you using, any other details about the error, what environment you're using, etc.. Also consider posting your project to a public github repo and sharing a link to it
