### ISSUE TITLE
SharePoint Client (CSOM 16) problem with authenticating (most likely due basic auth being deprecated)

### ISSUE THREAD

**Issue by jernejk** [SharePoint/sp-dev-docs#5437]
## Category

- [x] Bug

## Describe the bug

On Friday, 06/03/2020, we started to have issues where authentication to SharePoint broke using SharePoint CSOM with no code change or changes to SharePoint 365. We were hoping that the #5425 was a related issue and it would fix our problem as well since it happened roughly the same time.

We suspect that we need to change the way we authenticate to SharePoint in our SharePoint CSOM code. We have no issues authenticating to the SharePoint website with the same credentials.

I tried to find instructions for how to do OAuth 2.0 for SharePoint CSOM with no success so far, all examples are for SharePoint REST or Graph API.

## Steps to reproduce

I have built a new console application on .NET Framework 4.7.2 using the Nuget package Microsoft.SharePointOnline.CSOM, 16.1.7618.1200.
The minimum repo is based on https://docs.microsoft.com/en-us/sharepoint/dev/features/groupify/groupify-csom and this GitHub issue suggestions.

``` cs
    public static class Program
    {
        private static ClientContext _context;
        public static async Task Main(string[] args)
        {
            _context = new ClientContext("https://sswcom.sharepoint.com/");

            var pwd = "tnTK8teyYmxXORznrHwy";
            var passWord = new SecureString();
            foreach (char c in pwd) passWord.AppendChar(c);
            _context.Credentials = new SharePointOnlineCredentials("SP_TimePro_SVC@ssw.com.au", passWord);

            var cookie = GetAuthCookies("https://sswcom.sharepoint.com/accounting");
        }

        private static CookieContainer GetAuthCookies(string url)
        {
            //var url = _context.Web.EnsureProperty(w => w.Url);
            var webUri = new Uri(url);

            var credentials = _context.Credentials as SharePointOnlineCredentials;
            var authCookie = credentials?.GetAuthenticationCookie(webUri);

            var cookieContainer = new CookieContainer();
            cookieContainer.SetCookies(webUri, authCookie);

            return cookieContainer;
        }
    }
```

![image](https://user-images.githubusercontent.com/5943653/76377678-3f36f800-6397-11ea-8dd2-9b1860dcada7.png)

I assume the problem is that this authentication type is being disabled.

We have 2 problems with that:

1. We need to fix our application to fix production issue causing a major blocking issue to business
2. We are allowing our customers to do SharePoint integration as well. Luckily we don't have many clients using this feature but we need an upgrade strategy for them as well.

## Expected behavior

A successful authentication.

## Developer environment

- OS: Windows Server 2016 (on prod) / Windows 10 (on dev machine)
- Framework: .NET Framework 4.7.2
- Nuget package: Microsoft.SharePointOnline.CSOM, 16.1.7618.1200
- SharePoint server: SharePoint 365 (clients might have on-prem)
- Browser(s): -
- Tooling: Visual Studio 2019

**Comment by luismanez** [comment]
Asking a silly question, but, are you able to load a ClientContext using those Crendetials? and if so, what happens if you do this code (this is how the PnP Core library is getting the Auth cookie):
```cs
private CookieContainer GetAuthCookies()
        {
            var url = _context.Web.EnsureProperty(w => w.Url);
            var webUri = new Uri(url);

            var credentials = _context.Credentials as SharePointOnlineCredentials;
            var authCookie = credentials?.GetAuthenticationCookie(webUri);

            var cookieContainer = new CookieContainer();
            cookieContainer.SetCookies(webUri, authCookie);

            return cookieContainer;
        }
```
Basically is your code, but getting the Credentials from the Context, so maybe something is loaded first... likely won't help, but who knows.

**Comment by andrewconnell** [comment]
Not sure if it's related, but basic auth + forms auth is being retired/deprecated across Office this year. Exchange Online is doing it (see message center ID: [MC204828](https://admin.microsoft.com/AdminPortal/home#/MessageCenter?id=MC204828)) and Office clients are doing it too (see message center ID: [MC203731](https://admin.microsoft.com/AdminPortal/home#/MessageCenter?id=MC203731))

**Comment by jernejk** [comment]
@andrewconnell we are targetting SharePoint 365 on sharepoint.com and I can't access any of the URLs you are referring to.

What are the alternatives for auth with SharePoint Client?

I'll provide more information later this day.

**Comment by jernejk** [comment]
@msft-github-bot, @andrewconnell I have updated the title and description to hopefully give more details on the issue. The code is very old and I haven't done any SharePoint work so far, so I need to figure out how to fix this issue.

I have tried a minimum repo based on the docs I have found and managed to make it fail due to credential issues. I'm still looking at how to do OAuth 2.0 in SharePoint Client CSOM.

I suspect that I need to use SharePoint REST instructions and retrofit it into SharePoint Client CSOM.
Either there is something wrong with our SharePoint server or I'm doing something wrong or this instruction no longer works: https://docs.microsoft.com/en-us/sharepoint/dev/features/groupify/groupify-csom

![image](https://user-images.githubusercontent.com/5943653/76377205-fe8aaf00-6395-11ea-9534-83c8aa01bdf4.png)

**Comment by andrewconnell** [comment]
@jernejk said:
> I can't access any of the URLs you are referring to.

You need to be logged into your tenant as an admin who has access to the M365 admin portal to see those links. They are in the portal's Message Center.

@jernejk said:
> I think we need to follow this?
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?redirectedfrom=MSDN

That's my rec... the currently recommended way to auth with SPO is to use OAuth2. Your admins don't generate a token for you. You'll need to create an Azure AD app, give it the necessary permissions for what you want to do, and then your code will auth and obtain a token as that doc describes.

**Comment by jernejk** [comment]
This will be problematic for us as we already have put quite a bit of effort to have SharePoint integration not just for us but also for our clients. I don't have access to create an Azure AD app and a lot of our clients might also struggle with that.

This is what we currently use to add integration for uploading files to SharePoint.
![image](https://user-images.githubusercontent.com/5943653/76431623-8fe13c00-63fd-11ea-9843-1a9978e769cd.png)

If I understand there is no good option then:
1. Create an Azure AD App
2. Update code and UI to accept the new configuration
3. Add redirect URI handling?
4. Notify all of the customers about this change

And instructions for clients:
1. Create an Azure AD App (some organizations will require Azure Portal admins for that)
2. The Azure AD App is redirecting to our product for finalizing auth?
3. Use client ID and client secret in the settings?

I'll likely get our sysadmins to create Azure AD app within or maybe a dev might already have one for Graph API. My concern is that the suggested solution might not work for us.

Another alternative we were thinking was to completely remove SharePoint integration and replacing it with a webhook to Power Automate (MS Flow). This will still take quite a bit of time but at least we don't have to create new Azure resources.

**Comment by andrewconnell** [comment]
@jernejk So you're an ISV (TimePro?) that offers a product that can write to SharePoint document libraries?

If that's correct, you should go research Azure AD and single vs. multi-tenant. This is a MUCH bigger topic than can be "answered" in a forum like this. But you create a single Azure AD app that your company manages. It's a multi-tenant app which means that other people can use it once they trust it in their tenant (such as how many other products & services integrate with SharePoint). An admin for the tenant will have to grant your app permissions to their tenant, but then your code can auth with Azure AD using your Azure AD app to obtain a token to connect to your customer's SPO tenant.
