### ISSUE TITLE
Applying Field Customizer Leads to Empty Cells in Teams Files Tab

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5438]
## Category

- [x] Bug

## Describe the bug

If you apply SPFx Field Customizer to any column in Documents Library, the column will have empty cells in Teams Files Tab:
**SharePoint**
<img width="862" alt="Screen Shot 2020-03-10 at 10 14 43 AM" src="https://user-images.githubusercontent.com/17036219/76339934-05db8b00-62b8-11ea-915c-d8a994f83ce2.png">

**Teams**
<img width="651" alt="Screen Shot 2020-03-10 at 10 14 48 AM" src="https://user-images.githubusercontent.com/17036219/76339956-0b38d580-62b8-11ea-93a2-d72ca23e103f.png">

## Steps to reproduce

1. Apply any field customizer to Documents library
2. Navigate to Teams Files tab with the same document library
3. Cells for the column with field customizer are empty
## Expected behavior

In ideal world - field customizer should be displayed in Teams
Temporary solution - at least cells shouldn't be empty

**Comment by schneika** [comment]
Any Updates? Field Customizer not working in Teams Tab Views

**Comment by patmill** [comment]
Sorry for the delay.  This is being fixed in the Teams app.  Unfortunately we don't have an explicit ETA on that, but it is rolling through their release rings.

**Comment by eduardpaul** [comment]
Hi all! does it still being rolling through their release rings, or it's dropped? any updates?

**Comment by FlorianLabranche** [comment]
Hi!
Will it also fix ListView Command Set extension integration in Teams or only Field Customizer ?

**Comment by AJIXuMuK** [comment]
@FlorianLabranche - it should fix all 3 extensions

**Comment by AJIXuMuK** [comment]
This should be rolled out WW by now.
