### ISSUE TITLE
Teams Personal Tab calling Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken returns 403 in Teams Windows client

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#5441]
## Category

- [x] Bug

## Describe the bug

We created a webpart which is loaded as a Personal Teams Tab in MS Teams.
The webpart uses AadHttpClient to call secured web-apis.
We have deployed the webpart to multiple environments without issue, but in a single tenant now, we receive `HTTP 403` response on the call to `https://<tenant>/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=<guid>&clientId=<guid>`

The issue only occurs on the **desktop** client, and not on the web client.

Response of the AcquireOBOToken call is:

> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

Edit: if it helps, `sprequestguid: 22bb3d9f-e038-b000-134f-6dc3fc357546`

**Comment by andrewconnell** [comment]
So it works in some tenants but not others?

**Comment by NickSevens** [comment]
Correct, we have a couple of similar solutions running, but on this tenant it fails.

**Comment by andrewconnell** [comment]
If tenant-specific, I'd suggest creating a support request in your M365 portal.

**Comment by NickSevens** [comment]
@andrewconnell could Conditional Access rules for MFA in AAD be a possible root cause for this?

**Comment by andrewconnell** [comment]
¯\_(ツ)_/¯

Sorry, but my last comment is all I have to suggest or add to this thread at this point.

**Comment by czullu** [comment]
@NickSevens i solved the issue by following the Answer here https://stackoverflow.com/questions/59860729/spfx-webpart-in-msteams-desktop-client-throws-an-unauthorizedaccessexception

**Comment by NickSevens** [comment]
Issue was resolved by re-creating the sharepoint external credential app
