### ISSUE TITLE
Connect an Office 365 group is WRONG

### ISSUE THREAD

**Issue by the-epoch** [SharePoint/sp-dev-docs#5445]
The explanation to "Connect an Office 365 group using the SharePoint user interface" is wrong. I believe this is for the Classic site design - how do we do this in the current Office 365 interface?
If I click on the Settings (Gear) icon in the Sharepoint site, these are my options:

 - Settings
Add a page
Add an app
Site contents
Site information
Site permissions
Site usage
Change the look
Site designs

 - Office 365
View all

MS You need to up your game - not good enough. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb7f9871-ee80-3bed-5085-fd7e2374641d
* Version Independent ID: fe06b607-6f98-edcb-f6ff-f0fa426d5666
* Content: [Connect to an Office 365 group](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-connect-to-office365-group#feedback)
* Content Source: [docs/transform/modernize-connect-to-office365-group.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-connect-to-office365-group.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @the-epoch ,

you are right. That screenshot is outdated. We will get that updated. 

Regarding your question: "how do we do this in the current Office 365 interface?"
If you don't see the option to groupify the SharePoint site, it may be that you either doesn't have enough permission or that modernization is not available for this site collection. This is the statement from the documentation:

For publishing portals (sites based upon BLANKINTERNET#0, ENTERWIKI#0, SRCHCEN#0, SRCHCENTERLITE#0, BICENTERSITE#0, POINTPUBLISHINGHUB#0, POINTPUBLISHINGTOPIC#0 or sites using the “Pages” library) it's not currently supported to connect these to an Office 365 group or to use modern pages. If you want to modernize your publishing portal it's recommended to start from a new communication site and configure that one accordingly. 

I hope it helps to clarify your question.

Regards,
Jarbas

**Comment by andrewconnell** [comment]
@JarbasHorst Thanks for jumping in... are you tackling the update to the doc in a PR? If so, I'll assign it to you... otherwise, I can assume ownership

**Comment by JarbasHorst** [comment]
@andrewconnell Please, assign it to me. PR coming in the upcoming days.

**Comment by B3J** [comment]
My site is not root site, is not publishing site and I don't have that option..
