### ISSUE TITLE
Theme color not getting applied for icon

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-docs#5446]
## Category

- [x] Bug

## Describe the bug

I have applied the color property to the icon. Please check my code below. It is not getting applied. 
![image](https://user-images.githubusercontent.com/14230498/76517859-16406100-6484-11ea-8d52-613eeff9cf7b.png)

## Steps to reproduce

```
const iconStyles: IIconStyles = {
  root: {
    fontSize: 16,
    fontWeight: FontWeights.regular,
    color: "[theme: themePrimary , default: #0078d7]" 
  }
};

//in the render method
 <Icon iconName="Edit" styles={iconStyles} style={{ cursor: 'pointer' }} />
```
Please let me know if i have missed anything.

**Comment by OS-Lee** [comment]
Hi,

Define the CSS in your CSS module file and reference it as 

`<Icon iconName="Edit" className={styles.iconStyles} style={{ cursor: 'pointer'}} />`

CSS definition:

`.iconStyles{
    font-size:16;
    font-weight: $ms-font-weight-regular;
    color: "[theme: themePrimary , default: #0078d7]" ;
    background-color: "[theme: themePrimary, default: #0078d7]"
  }`

Result:

![image](https://user-images.githubusercontent.com/40845109/76595262-32043f80-6536-11ea-9d0f-3e908f8dd263.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by Harshagracy** [comment]
Are you applying these css from the SCSS file? 
will it work if it is applied from css file?

**Comment by OS-Lee** [comment]
Hi,
Mentioned in my first reply, applying these css from the SCSS module file.
Have you tested?

**Lee
Microsoft SharePoint Community Support**
