### ISSUE TITLE
SyncSolutionToTeams Error 500 Unknown Error

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#5447]
## Category

- [x] Bug

## Describe the bug
@VesaJuvonen  When trying to sync the spfx solution with teams, the SyncSolutionToTeams request returns a 500 error.

The spfx version is 1.10.0 with a default hello world webpart and with the following information changed in the manifest: "supportedHosts": ["TeamsPersonalApp"].

Related issue: https://github.com/SharePoint/sp-dev-docs/issues/5425#issuecomment-596960575

![image](https://user-images.githubusercontent.com/33054287/76533422-53065b00-6478-11ea-8b01-55f81ce913a8.png)

![image](https://user-images.githubusercontent.com/33054287/76533974-2dc61c80-6479-11ea-8967-185508c45f9f.png)

**Comment by andrewconnell** [comment]
Being that PersonalApps are in dev preview, have you tried manually deploying your Teams app package => your Teams tenant?

**Comment by sortegamartin** [comment]
Hi, @andrewconnell , is it possible to upload a spfx solution directly to Teams? I think the only way to deploy a spfx TeamsPersonalApp is to upload it to the app catalog and click on the sync button.

**Comment by andrewconnell** [comment]
@sortegamartin said:
> is it possible to upload a spfx solution directly to Teams?

No... the SPFx components should be deployed & installed to SharePoint Online.

You can then upload the Microsoft Teams app package that includes the two image files & Teams app manifest directly to Teams.
