### ISSUE TITLE
Anchors within SPFx web part wont trigger navigation of first click within a single app part page

### ISSUE THREAD

**Issue by mchip88** [SharePoint/sp-dev-docs#5448]
## Category

- [x] Bug

## Describe the bug

When using a single app part page, anchors don't trigger on first click

## Steps to reproduce

1.- Create an SPFx web part which contains anchors and link to a different page within the same site collection

2.-Enable the web part to be added on a single app part page 

3.-Add the web part to a single app part page (please note that you will need to create a page like this using the instructions found on 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

4.-When you click on your web part's link, no navigation will occur on first click.  However, the link on the browser's link bar will change to the desired page

5.-Clicking once more should make the page navigate 

NOTE: We fixed this issue by setting the anchor property data-interception to "off" 
Even if we set the data-interception property to "propagate" the link would not work on first click

## Expected behavior

1. Clicking once on a link causes navigation

## Developer environment

Windows 10
SPFx  1.9
Chrome  Version 80.0.3987.132 (Official Build) (64-bit)
Build with Visual Studio Code

### Additional context

I tried using the same web part on a standard modern page and the links worked fine, didn't even need to add the data-interception property to them

**Comment by andrewconnell** [comment]
By design.... see https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

**Comment by 2toLeadMike** [comment]
@andrewconnell I don't see how this is by design, if we make an app part page, every link, when clicked, will not go anywhere, and merely update the URL. Yet clicking the same link, again, actually has the page updated? Essentially the only way to make links work is to disable data-interception on every link. This feels like an issue, not something by design. Why have a link not go anywhere unless double clicked?

I also don't see how singleappwebpartapppages get this behavior, but spfx webparts on regular pages do not. Maybe I am missing something here?

**Comment by 2toLeadMike** [comment]
@mchip88 I tried just now with a very basic webpart and it doesnt exhibit this behavior. Was your code basic or was it a part of a project that had more going on?

**Comment by mchip88** [comment]
@2toLeadMike within the page there were other web parts, in this case one extension and it does extract the link information from SharePoint, could that be related? Not sure if should

Could you paste the react code rendering of the web part you tested please?

**Comment by andrewconnell** [comment]
@2toLeadMike See the OP... it was updated to include:
> NOTE: We fixed this issue by setting the anchor property data-interception to "off"

That's what the doc I referenced says.

If there's something else going on, then consider creating a new issue with a repro please.
