### ISSUE TITLE
SharePoint client-side web part Deployment failed.

### ISSUE THREAD

**Issue by zkingdesign** [SharePoint/sp-dev-docs#5451]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

So my issue is the following: I've created a new sharepoint app following this tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part.

I did the following steps:
1. `mkdir new-webpart`
2. `cd new-webpart`
3. `yo @microsoft/sharepoint` 
4. Followed exact options as described in the article linked above.
5. `gulp trust-dev-cert`
6. `gulp serve`
7.  `gulp package-solution`
8. Uploaded the `new-webpart.sppkg` file to the app catalog.
9. And I get the following error as in the screenshot: https://imgur.com/a/BwumbOX . Deployment failed. Correlation ID: .......

Worth to mention I don't get any errors in the developer console or during builds.

## Environment details (if applicable)
- OS: MacOS 10.15.3
- Framework: Node.js v10.13.0
- Browser(s): Chrome v80.0.3987.132,  FireFox v74
- Tooling: VS Code

**Comment by PrasadKasireddy** [comment]
could you please share the .sppkg file

**Comment by zkingdesign** [comment]
@PrasadKasireddy here is a link to the file https://drive.google.com/open?id=17siy_F8dp0-DVybi0WCop7f65E3YHzje

**Comment by PrasadKasireddy** [comment]
@zkingdesign  - sorry i could not find the .sppkg file, could you please add files directly here, you can find the open below as attach files by dragging & dropping, selecting or pasting them (at the bottom of comments section)

![image](https://user-images.githubusercontent.com/11626905/76782482-59793780-67d6-11ea-92d9-8daeccb2b319.png)

**Comment by zkingdesign** [comment]
I cannot upload sppkg on github because it says that it's unsupported. So what I did is that I archived the sppkg file into a .zip file attached below. Will this work?
[new-webpart.sppkg.zip](https://github.com/SharePoint/sp-dev-docs/files/4339490/new-webpart.sppkg.zip)

<img width="828" alt="Screenshot 2020-03-16 at 19 25 09" src="https://user-images.githubusercontent.com/1790418/76784176-dba83280-67bb-11ea-8236-22d1b419e24a.png">

**Comment by PrasadKasireddy** [comment]
@zkingdesign  - this solution is deployed successfully on my tenant (SharePoint Online)

![image](https://user-images.githubusercontent.com/11626905/76786980-2fc40e80-67de-11ea-960d-2a3e4617e077.png)

Could you please confirm which environment (SharePoint online / On premises )are you trying to use this solution ?

**Comment by zkingdesign** [comment]
@PrasadKasireddy I'm using SharePoint online

**Comment by zkingdesign** [comment]
I think I've found the issue, the app catalog was created in English language, but the tenant default is German. 
What I did is I deleted the current App catalog, created a new one with the default language, and it seems to work like charm.

Is this a bug? any ideas why is this happening?

**Comment by andrewconnell** [comment]
Unknown, but because its not a dev issue, this isn't the right place to post this question. Better to post this to TechCommunity...
