### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by jhinshawkcidev** [SharePoint/sp-dev-docs#5452]
This is the order in which I placed the functions within the HelloWorldWebPart class:
1. _renderListAsync() 
2. _renderList(items: ISPList[])
3. _getListData()
4. _getMockListData()

Does the order in which these functions are added matter in relation to the original "render()" method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint#feedback)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,
They're just functions, the order won't impact.

**Lee
Microsoft SharePoint Community Support**
