### ISSUE TITLE
Fabric DetailsList causes multiple issues

### ISSUE THREAD

**Issue by raytri** [SharePoint/sp-dev-docs#5453]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have a custom SPFx webpart built with React, containing a DetailsList component. The DetailsList component is causing two major issues with the webpart.

**Observed behavior:**
In local workbench, online workbench and online with deployed webpart, I am able to select the web part and add it to the zone. It displays properly. So far so good. However:

1. Clicking on the "edit" icon for the web part does nothing.
2. When I add the deployed version to a page and publish the page, the webpart displays properly. But if I refresh the page (or navigate away and come back), the webpart disappears.

If I remove the DetailsList component (by commenting it out in my JSX template) and render the webpart contents in vanilla HTML instead, everything works properly.

**Expected behavior:**
1. Should be able to open Property Pane when clicking the edit icon for the webpart
2. When webpart is placed on a page and the page is published, the webpart should persist.

## Environment details (if applicable)

- OS: Windows 10
- Framework: React
- Browser(s): [Chrome v80.0.3987.132, Edge v44.17763.831.0]
- Tooling: [VS Code, SPFx v1.10.0]

**Comment by sudharsank** [comment]
Hi @raytri, are you receiving an error in the browser console when the web part disappears? can you please post some screenshots for better clarity.
