### ISSUE TITLE
Angular web part is not working in IE

### ISSUE THREAD

**Issue by ZhaoYunhe** [SharePoint/sp-dev-docs#5456]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Environment details
Share point online+SPFx+Angular8

## Question

Angular web part is not working on the explorer IE.
The error is:
[Original error: Unable to set property '@@iterator' of undefined or null reference ]
Please help to resolve this problem.

The detail info for this error is as:
Because of the error:[Original error: Cannot redefine non-configurable property 'startsWith'], I commented out the code 'core-js/es6/string', so the Polyfills I've defined is as below.
But after setting the Polyfills, a new error [Original error: Unable to set property '@@iterator' of undefined or null reference ] is showed up.

## Polyfills 
// /***************************************************************************************************
//  * APPLICATION IMPORTS
//  */
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
//import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
if (WeakMap.toString().indexOf('function WeakMap()') === -1) {
    WeakMap = undefined;
}
import 'core-js/es6/weak-map';

// Check for native support of Map vs Polyfill
if (Map.toString().indexOf('function Map()') === -1) {
    Map = undefined;
}
import 'core-js/es6/map';
// Check for native support of Map vs Polyfill
if (Set.toString().indexOf('function Set()') === -1) {
    Set = undefined;
}
import 'core-js/es6/set';

**Comment by semopz** [comment]
The Symbol sham that is used by the Modern UI is outdated.

On a modern browser (or IE11 with core-js v3 Symbol polyfill), the following should return an iterator function.
```ts
var myString = 'a string of chars';
myString[Symbol.iterator]
// Should return the iterator function
// undefined in the case of IE11 on a Modenr UI page
myString[Symbol.iterator]().next().value
// "a"
```

My guess is that angular has a check as follows
```ts
// *** pseudo code ***
if (Symbol) {
  //Symbol exists so therefore Symbol.iterator will extract iterator function from objects and strings
} else {
  //fallback
}
```

Since the Modern UI uses a Symbol sham that doesn't have a working implementation of a Symbol.iterator symbol, Angular is not allowed to take the fallback branch (assuming it had one).

I don't know of a way to correctly sham/polyfill Symbol in the Modern UI. I think you might have to raise a call with Microsoft.

**Comment by andrewconnell** [comment]
Not enough info... need more context. What version of IE, what SharePoint environment are you targetting, etc.

Also refer to these:
- https://angular.io/guide/browser-support
- https://support.office.com/en-us/article/which-browsers-work-with-office-for-the-web-ad1303e0-a318-47aa-b409-d3a5eb44e452
