### ISSUE TITLE
Cannot change content types in document library for MS Office Open XML documents (.docx, .xlsx, .pptx). All other file types, even .doc/.xls/.ppt, change content types without issue.

### ISSUE THREAD

**Issue by robnoyes** [SharePoint/sp-dev-docs#5459]
## Question
Why do only OOXML documents fail to change content types when all other files types work?

## Environment details
 - OS: Windows 10
 - Framework: .NET
 - Browser(s): All
 - Tooling: None (OOB-only)

FYI: Custom columns where added to the 'Item' content type. 'Update all content types inheriting from this one was 'On' when the custom columns where added to the 'Item' content type.

The name of the default document content type "Document" was changed to "Non-Record". 

Workflows were applied to the default document content type (renamed 'Non-record').

**Comment by bcameron1231** [comment]
Hi, If possible could you update your issue with all the fields to help us work through your issue. It's hard to tell exactly what your issue is. Is this a development issue?

**Comment by robnoyes** [comment]
ok..updated.

thank you
