### ISSUE TITLE
Tel and geo schema are not supported for custom field formattings

### ISSUE THREAD

**Issue by fiechter** [SharePoint/sp-dev-docs#5460]
## Category

- [x] Bug

## Describe the bug

Creating a field formatting returning a link to a Teams call or maps application doesn't work, and shows an error that only http, https and mailto protocols are supported.

## Steps to reproduce

1. Add a custom formatting to SharePoint list field
2. Set the href to geo or tel

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "debugMode": true,
  "txtContent": "Call me",
  "attributes": {
    "target": "_blank",
    "href": "='tel://+2345"
   }
}
```

## Expected behavior

That "tel" and "geo" schemas are supported.

## Developer environment
SharePoint Online

**Comment by Jerry0527** [comment]
Currently, tel/geo hyperlink schema still not supported in Json Column Formatting. Only http://, https://, or mailto can be used, please refer the official document here:

[Create clickable actions](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-clickable-actions)

**Comment by bcameron1231** [comment]
Correct, this is intended functionality. 

If this is something you'd like to see as part of Column/View Formatting,  please head over to the UserVoice https://sharepoint.uservoice.com/ and see there is an existing UV or create your own for this!
