### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by quantrpeter** [SharePoint/sp-dev-docs#5461]
spfx 1.10.0 , latest chrome on windows. i saw "Initialized ClientSideExtensionHelper" in debugger, but i also have this error:

suiteux.shell.plus.56e22b40b087f443cfc8.js:144 Refused to load the script 'https://r4.res.office365.com/footprint/v3.2/scripts/fp-min.js' because it violates the following Content Security Policy directive: "script-src 'self' https://contentstorage.osi.office.net https://swx.cdn.skype.com https://res.delve.office.com https://lpcres.delve.office.com https://static.sharepointonline.com https://widget.uservoice.com https://by2.uservoice.com https://www.bing.com/api/maps/ https://www.bing.com/rms/ https://spoprod-a.akamaihd.net https://fabriciss.azureedge.net https://publiccdn.sharepointonline.com https://ajax.aspnetcdn.com https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-02-28-sts_20200310.001/ https://r1.res.office365.com https://webshell.suite.office.com https://shellux.msocdn.com https://shellprod.msocdn.com https://shellppe.msocdn.com https://mem.gfx.ms https://amcdn.msftauth.net https://shellprod.msocdn.com https://c1-excel-15.cdn.office.net https://c1-onenote-15.cdn.office.net https://c1-powerpoint-15.cdn.office.net https://c1-visio-15.cdn.office.net https://c1-word-view-15.cdn.office.net 'unsafe-eval' 'nonce-1f480e64-1d78-4c7f-af5e-897e52a73600'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

so my extension can't run, please help
thanks
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc14882-1021-df0e-73c1-95d049f091d7
* Version Independent ID: eda24750-4e60-f05c-a6bb-0cc017dfe9ed
* Content: [Build your first Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#feedback)
* Content Source: [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi! Can you please provide more information for your issue? Are you able to share the code you are using by chance?

Based on the error, my initial thoughts are it looks as though you may be trying to do inline scripting which is bad practice and being blocked by the browser.

**Comment by andrewconnell** [comment]
As @bcameron1231 implies, impossible to help without more context, seeing the code, etc.
