### ISSUE TITLE
deploy for this.properties.sampleText

### ISSUE THREAD

**Issue by quantrpeter** [SharePoint/sp-dev-docs#5466]
After deploy, where i can set this.properties.sampleText ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc14882-1021-df0e-73c1-95d049f091d7
* Version Independent ID: eda24750-4e60-f05c-a6bb-0cc017dfe9ed
* Content: [Build your first Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#feedback)
* Content Source: [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,

I haven't tested the solution mentioned in [this thread](https://sharepoint.stackexchange.com/questions/227137/how-does-one-pass-parameters-to-sharepoint-framework-extensions-in-practice) while I tested below solution with similar approach to do configuration by clientSideComponentProperties.

`
  public onRenderCell(event: IFieldCustomizerCellEventParameters): void {
    // Use this method to perform your custom cell rendering.    
    var prefix=JSON.parse(this.context.field.clientSideComponentProperties).sampleText;
    const text: string = `${prefix}: ${event.fieldValue}`;
    
    event.domElement.innerText = text;

    event.domElement.classList.add(styles.cell);
  }`

`Set-PnPField -List "MyListCSR" -Identity "Percentage" -Values @{ClientSideComponentProperties='{"sampleText": "LeePnP"}'}`

Result:
![image](https://user-images.githubusercontent.com/40845109/76946636-4df55000-693f-11ea-932e-17edc5d1abe8.png)

**Lee
Microsoft SharePoint Community Support**
