### ISSUE TITLE
Pre-allocating space for top app customizer hides the 'collapse content' button for library

### ISSUE THREAD

**Issue by kapilmehtagit** [SharePoint/sp-dev-docs#5467]
## Category

- [x] Bug

## Describe the bug

App customizer in Top placeholder has a pre-allocated height of 40px. When a user clicks on the 'Expand content' option in a library's command bar, the 'Collapse content' option gets hidden behind the app customizer due to it's pre-allocated height.

## Steps to reproduce
Create a top placeholder customiser (an empty div would do) with a pre-allocated height of 40px. 

elements.xml/ClientSideInstance.xml should include:
 HostProperties="{&quot;preAllocatedApplicationCustomizerTopHeight&quot;:&quot;40&quot;}">

Deploy the placeholder. Click 'Expand content' from a libary's command bar. Note the 'Collapse content' button is now hidden behind the app customizer.

## Expected behavior
The 'Collapse content' button and associated div should be placed below the app customizer when the library is shown in 'expanded content' mode.

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by CloudDesignBox** [comment]
Can i just add to this. even if you don't set the preAllocatedApplicationCustomizerTopHeight setting, we are still seeing this issue. 

I can reproduce following this to create a header placeholder app customizer: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions

In some tenancies it works as expected, in others it doesn't (see examples below):
![readingpane](https://user-images.githubusercontent.com/17725046/78570797-58f41f80-781d-11ea-8adf-2dbb82e31098.png)

**Comment by CloudDesignBox** [comment]
I've made a workaround solution for this. Not pretty but works, similar solution to @estruyf used for checking page navigation. Hopefully Microsoft can resolve so we don't have to add these hacks.

`private checkForexpandCollapseList(){
    const interval = window.setInterval(() => {
      let collapsebuttons:any = document.querySelectorAll("[data-automationid='expandCollapseList']");
      //if item exists on the page
      if(collapsebuttons){
        //hide menu
        if(collapsebuttons[0].title == "Collapse content"){
          const topbannermenu: HTMLElement = <HTMLElement>document.querySelector(`#${styles.myheader}`);
          if(topbannermenu){
            topbannermenu.style.display = "none";
          }
        // show menu
        }else if (collapsebuttons[0].title == "Expand content"){
          const topbannermenu: HTMLElement = <HTMLElement>document.querySelector(`#${styles.myheader}`);
          if(topbannermenu){
            topbannermenu.style.display = "block";
          }
        //show menu if another value
        }else{
          const topbannermenu: HTMLElement = <HTMLElement>document.querySelector(`#${styles.myheader}`);
          if(topbannermenu){
            topbannermenu.style.display = "block";
          }
        }
      }
    }, 200);
   }`

**Comment by mirkori** [comment]
Any updates regarding this issue?

**Comment by patmill** [comment]
Sorry for the delay / missing metadata.  This looks like it is fixed, although a separate issue (the customizer doesn't appear in focus mode) is being addressed separately.
