### ISSUE TITLE
PhantomJS no longer maintained - Build Chain, JS Testing, ...

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#547]
@patmill In case you haven't heard yet. 

[PhantomJS is no longer maintained anymore.](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE)

I guess we will see and replacement for that in SPFx. The news is pretty fresh and came right after the Google Chrome team announced the [headless mode](https://news.ycombinator.com/item?id=14101233) for their browser.

I know that for the end user experience aka developer that use SPFX won't care that much what is used inside but sooner or later an alternative needs to be found for that parts of the build chain that used PhantomJS. There is no urgent need to change because it still works now but it would be great to here what this means for example in case of web part testing and which direction you will go in future now.

In addition there are things like Karma that also rely on PhantomJS on one way or another.

**Comment by andrewconnell** [comment]
Seems Chrome 59 (where headless mode is introduced) won't be stable until early June 2017 and there's no Linux distro yet... therefore switching isn't feasible yet. But this a HUGE step forward for web dev!

**Comment by manishgarg1** [comment]
@StfBauer, thanx for sharing the news. We will evaluate the consequences of this.

**Comment by StfBauer** [comment]
@andrewconnell Currently the canary releases are at version 60. Even for Linux but those are developer previews and beta. Installed 59 a couple of days ago [via Google Release Channel](https://www.chromium.org/getting-involved/dev-channel).

<img width="682" alt="screen shot 2017-04-17 at 10 02 04" src="https://cloud.githubusercontent.com/assets/5503835/25083086/472aa0d2-2355-11e7-8768-7da32c528587.png">

But there is still some time until a stale headless mode is available.

**Comment by iclanton** [comment]
We're working on updating our karma task to support headless Chrome, but we've run into a number of issues. One big issue is that Chrome still opens in the foreground even if it's launched in headless mode. I'm going to watch the Chrome bugfixes and continue work on implementing this when the issues are fixed.

We're also investigating [Jest](https://facebook.github.io/jest/) as a test environment as an alternative to Karma, but it's not a drop-in replacement.

**Comment by StfBauer** [comment]
Thank you @iclanton good to know. Meanwhile I try to set up a front-end cross browser testing through browserstack. We will see how this works. ;)

**Comment by YonasJ** [comment]
Any update on this? I would really like to be able to run tests, and there are too many features that don't work in Phantom for it to be worth maining that level of backwards compatibility. 

So right now, I am manually running my tests in chrome via `gulp test --debug` and it is annoying.

I would be happy to move my tests to Jest, if that somehow helps.

**Comment by pgonzal** [comment]
We definitely have heard the feedback that unit testing is an important requirement for SPFx developers. We want to provide better solution that will be easier to support than the current karma task. We're experimenting with different approaches and will announce the new plan as soon as it's ready.

@qz2017 @nickpape-msft @iclanton

**Comment by jayarjo** [comment]
How this thread came out in the end?
