### ISSUE TITLE
Scrollbar on PdfViewer not Appear on chrome.

### ISSUE THREAD

**Issue by cryongen** [SharePoint/sp-dev-docs#5470]
## Category

- [x] Bug

## Describe the bug

When a zoom of 200% or more is applied on pdf view on sharepoint librarie. the scrollbar not appear

## Steps to reproduce

1. Open a Sharepoint Library
2. Open a pdf document.
3. Open DetailsPane
4. Set zoom to 200%

## Expected behavior

> Document amplified  and scrollbar shown

## Developer environment

- OS: Windows 10
- Browser(s): Chrome 80.0.3987.132 (Official Build) (64-bit)

### Additional context

Seems it's related with an error in plt.odsp-common.chunk.js.
Because when i access directly the file using a url, it work's fine.
And if i close the file then reopen it by the library it's work's too.

The bug is only when i load a library and then open a file.
*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Can't repro this in Chrome setting Zoom to 200% and 250%...

![image](https://user-images.githubusercontent.com/2068657/77350142-7354d600-6d12-11ea-8654-51cb92db1935.png)
