### ISSUE TITLE
Verbs supported in a Site Script

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-docs#5471]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

What are the verbs that can be used in a site script? I couln't find that in this doc: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design. Please let me know.

**Comment by JarbasHorst** [comment]
Hello @xyz92 

the [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema) documentation contains all supported verbs(actions) and sub-verbs(sub-actions) in Site Script.

Regards,
Jarbas
