### ISSUE TITLE
SharePoint 2019 On-Prem Spfx

### ISSUE THREAD

**Issue by qiumc** [SharePoint/sp-dev-docs#5472]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
 

## Question
I using spfx to develop extension.
sharepoint 2019 On-Prem，Can't access the Internet.
When deployed have some error.
http://sp2019.contoso.com:8080/_layouts/15/next/spclient/0.legacy-third-party-fabric-core.js   reference some files from Internet.

> https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.woff2 
> https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-semibold.woff2 
 
Can these files not be applied? These files cause slow page loading;

dependencies
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.10.0",

  "componentType": "Extension",
  "extensionType": "ApplicationCustomizer",

chrome console have error:

26.sp-pages-idlesessionactivitymonitor.js:1 GET http://sp2019.contoso.com:8080/_layouts/15/activitymonitor.js net::ERR_ABORTED 404 (Not Found)
n @ 26.sp-pages-idlesessionactivitymonitor.js:1
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
Promise.then (async)
n @ sp-pages-assembly.js?uniqueId=tGdUL:119
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
setTimeout (async)
e.startDeferredComponents @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._handleCanvasViewportRendered @ sp-pages-assembly.js?uniqueId=tGdUL:119
e.onViewportWebPartsRendered @ sp-pages-assembly.js?uniqueId=tGdUL:1226
t._onViewportWebPartsRendered @ sp-pages-assembly.js?uniqueId=tGdUL:1226
e._onViewportWebpartsLoaded @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
setTimeout (async)
e._onAllWebpartsAdded @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
e.loadWebPart @ sp-pages-assembly.js?uniqueId=tGdUL:456
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:1226
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
e._render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
e.render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
t._renderCanvas @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
e.<computed> @ sp-pages-assembly.js?uniqueId=tGdUL:267
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
t.render @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._internalRenderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._renderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
Promise.then (async)
t.onRender @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._render @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._renderApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:944
Promise.then (async)
e._initializeApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._initializeApplicationWithTelemetry @ sp-pages-assembly.js?uniqueId=tGdUL:944
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._runApplicationManager @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:807
Promise.then (async)
e.start @ sp-pages-assembly.js?uniqueId=tGdUL:807
startSpfx @ Home.aspx:53
(anonymous) @ Home.aspx:61
(anonymous) @ Home.aspx:78
Show 26 more frames
3Home.aspx:1 GET https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-light.woff2 net::ERR_NAME_RESOLUTION_FAILED
sp-pages-assembly.js?uniqueId=tGdUL:456 GET https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-semibold.woff2 net::ERR_NAME_RESOLUTION_FAILED
get @ sp-pages-assembly.js?uniqueId=tGdUL:456
t._calculateMinimumHeight @ sp-hero-webpart-bundle.js?uniqueId=tGdUL:187
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
t._internalFirstTimeRender @ sp-pages-assembly.js?uniqueId=tGdUL:456
e._initializeAndRenderWebPart @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
e.loadWebPart @ sp-pages-assembly.js?uniqueId=tGdUL:456
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:1226
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
e._render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
e.render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
t._renderCanvas @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
e.<computed> @ sp-pages-assembly.js?uniqueId=tGdUL:267
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
t.render @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._internalRenderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._renderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
Promise.then (async)
t.onRender @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._render @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._renderApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:944
Promise.then (async)
e._initializeApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._initializeApplicationWithTelemetry @ sp-pages-assembly.js?uniqueId=tGdUL:944
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._runApplicationManager @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:807
Promise.then (async)
e.start @ sp-pages-assembly.js?uniqueId=tGdUL:807
startSpfx @ Home.aspx:53
(anonymous) @ Home.aspx:61
(anonymous) @ Home.aspx:78
Show 21 more frames
sp-webpart-shared.js?uniqueId=tGdUL:84 GET https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-semilight.woff2 net::ERR_NAME_RESOLUTION_FAILED
e._truncateLines_fast @ sp-webpart-shared.js?uniqueId=tGdUL:84
e.truncateLines @ sp-webpart-shared.js?uniqueId=tGdUL:84
t._truncateText @ sp-hero-webpart-bundle.js?uniqueId=tGdUL:187
t.componentDidMount @ sp-hero-webpart-bundle.js?uniqueId=tGdUL:187
e.<computed> @ sp-pages-assembly.js?uniqueId=tGdUL:267
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
(anonymous) @ sp-hero-webpart-bundle.js?uniqueId=tGdUL:187
Promise.then (async)
t.render @ sp-hero-webpart-bundle.js?uniqueId=tGdUL:187
t @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
t._renderWithAccessibleTitle @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
t._internalRenderInViewPort @ sp-pages-assembly.js?uniqueId=tGdUL:456
e._renderWebpartInViewport @ sp-pages-assembly.js?uniqueId=tGdUL:456
e._checkVisibilityAndRender @ sp-pages-assembly.js?uniqueId=tGdUL:456
e.register @ sp-pages-assembly.js?uniqueId=tGdUL:456
t._internalDelayedRender @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
t._internalFirstTimeRender @ sp-pages-assembly.js?uniqueId=tGdUL:456
e._initializeAndRenderWebPart @ sp-pages-assembly.js?uniqueId=tGdUL:456
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
Promise.then (async)
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:456
e.loadWebPart @ sp-pages-assembly.js?uniqueId=tGdUL:456
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:1226
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
e._render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
e.render @ sp-pages-assembly.js?uniqueId=tGdUL:1226
t._renderCanvas @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
e.<computed> @ sp-pages-assembly.js?uniqueId=tGdUL:267
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
t.render @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._internalRenderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._renderPageLayout @ sp-pages-assembly.js?uniqueId=tGdUL:119
t.componentDidMount @ sp-pages-assembly.js?uniqueId=tGdUL:119
window.spModuleLoader.e.notifyAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
close @ sp-pages-assembly.js?uniqueId=tGdUL:286
closeAll @ sp-pages-assembly.js?uniqueId=tGdUL:272
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
s @ sp-pages-assembly.js?uniqueId=tGdUL:286
perform @ sp-pages-assembly.js?uniqueId=tGdUL:272
batchedUpdates @ sp-pages-assembly.js?uniqueId=tGdUL:286
i @ sp-pages-assembly.js?uniqueId=tGdUL:272
_renderNewRootComponent @ sp-pages-assembly.js?uniqueId=tGdUL:286
_renderSubtreeIntoContainer @ sp-pages-assembly.js?uniqueId=tGdUL:286
render @ sp-pages-assembly.js?uniqueId=tGdUL:286
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:119
Promise.then (async)
t.onRender @ sp-pages-assembly.js?uniqueId=tGdUL:119
t._render @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._renderApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:944
Promise.then (async)
e._initializeApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._initializeApplicationWithTelemetry @ sp-pages-assembly.js?uniqueId=tGdUL:944
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:944
e._runApplicationManager @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e.startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
e._startApplication @ sp-pages-assembly.js?uniqueId=tGdUL:807
(anonymous) @ sp-pages-assembly.js?uniqueId=tGdUL:807
Promise.then (async)
e.start @ sp-pages-assembly.js?uniqueId=tGdUL:807
startSpfx @ Home.aspx:53
(anonymous) @ Home.aspx:61
(anonymous) @ Home.aspx:78
Show 45 more frames
6Home.aspx:1 GET https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-light.woff net::ERR_NAME_RESOLUTION_FAILED
static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.woff2:1 GET https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.woff2 net::ERR_NAME_RESOLUTION_FAILED
static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.woff:1 GET https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.woff net::ERR_NAME_RESOLUTION_FAILED
static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.ttf:1 GET https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-2.23.ttf net::ERR_NAME_RESOLUTION_FAILED

**Comment by andrewconnell** [comment]
Unclear... are you saying your environment doesn't have internet access? Can you also provide additional context, as in SPFx version used, etc.

**Comment by sudharsank** [comment]
Hi @qiumc, SPFx for SharePoint On-Prem works on version 1.4.1 and I don't think the SPFx extensions are supported for On-Prem.
@andrewconnell Please correct me if I am wrong.

**Comment by andrewconnell** [comment]
Extensions were added to 1.4.0 & are available in SP 2019 (only on modern pages), but not SP 2016.
