### ISSUE TITLE
Is it possible to render an api calling in the templateservice based on the item in searchresults in Modern-Search-Refiners

### ISSUE THREAD

**Issue by PranathiAnna** [SharePoint/sp-dev-docs#5474]
- Question : we have a scenario, were we need to insert a custom webpart based on the item id for each result in the searchresult pane. 
or 
Render a webapi to get the required html layout

**Comment by bcameron1231** [comment]
Hi, can you provide a bit more information as you the scenario and how you have been trying to solve it? If you are trying to modify the out of the box Modern Search Page and Refiners, this is not supported.
