### ISSUE TITLE
ExecuteQueryWithIncrementalRetry seems not working

### ISSUE THREAD

**Issue by educos35** [SharePoint/sp-dev-docs#5475]
Hi,
I am facing the problem and try implementing the code above in place of the standard ExecuteQuery.
All seems to work, but when the code returned is 503, then the wrapper is null and the native ExecuteQuery is retried successfully after the Retry-After perid set in the header.
The problem is that the item that I loaded in te context to retrieve its properties seems not to be correct as I get an execption when trying to acces the item properties: the collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#feedback)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
503's indicate a service error... see this comment for reference & guidance on how to report this to MSFT: https://github.com/SharePoint/sp-dev-docs/issues/4924#issuecomment-602026513
