### ISSUE TITLE
$specificIssuerId is not printed to File

### ISSUE THREAD

**Issue by YetiNerd** [SharePoint/sp-dev-docs#5480]
## Category

- [x] Bug

## Describe the bug

The IssuerID for the Code-Snippet "HighTrustConfig-ForSharedCertificate.ps1" is not printed to File due to last line of Code: $specificIssuerId | select * | Out-File -FilePath "SecureTokenIssuerID.txt"

## Steps to reproduce

When Running the Script: 
./HighTrustConfig-ForSharedCertificate.ps1 -CertPath "C:\Certs\MyCert.cer" -CertName "My Cert" -TokenIssuerFriendlyName "SharePoint High-Trust Add-ins Token Issuer"

The Outputfile "SecureTokenIssuerID.txt" only contains the length of the ID (the GUID).

## Expected behavior

The Outputfile "SecureTokenIssuerID.txt" should contain the GUID.

Removing the Select-Pipe is doing the Job for me:
$specificIssuerId | Out-File -FilePath "SecureTokenIssuerID.txt"

## Developer environment

- OS: Windows Server 2016
- Framework: PowerShell 5.x

**Comment by andrewconnell** [comment]
Can you provide some context, as in where you are seeing the **HighTrustConfig-ForSharedCertificate.ps1** file? Is that in the docs somewhere?

**Comment by MarcHochleutner-Koellisch** [comment]
I have the same error. Here is the script https://docs.microsoft.com/de-de/sharepoint/dev/sp-add-ins/high-trust-configuration-scripts-for-sharepoint

**Comment by andrewconnell** [comment]
Thanks... doc fixed & will be merged into the live site in the next site refresh.
