### ISSUE TITLE
As per given document Odata filter on datetime not working with day, month, year etc function.

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#5481]
I am trying filter records based on `datetime` Odata filter on year function but not working. I have tested with below function

Date and time OData functions:

```day()
month()
year()
hour()
minute()
second()
```
does not seem to work with SharePoint Online REST Service

`Error: The query is not valid`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#feedback)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Please provide some context... such as an example query. For example, have you verified the query is a valid OData query?

**Comment by anomepani** [comment]
I am using query like this, `https://brsupport. Sharepoint.com/_api/Lists/GetByTitle('test')/items?$filter=year(salesdate) eq 2019`
I am not sure where I am doing wrong, I am using below type filter.
`$filter=year(salesdate) eq 2019`
Tried with wrapping value in string as well
`$filter=month(salesdate) eq '2019'`

Hope this information will helpful

**Comment by Jerry0527** [comment]
Please refer the same question in StackOverflow:
[REST API filter by month](https://sharepoint.stackexchange.com/questions/122199/rest-api-filter-by-month)

Use Listdata.svc:
/_vti_bin/listdata.svc/ListName?$filter=month(<DateColumn>) eq <MonthNumber>

Example:
/_vti_bin/listdata.svc/Employees?$filter=year(test) eq 2020

**Comment by anomepani** [comment]
I have also tried same but for sharepoint online it's not working,  I have Reffered this answer but as it's not working I have rised queries on github. 

Thank for reply

**Comment by Jerry0527** [comment]
@anomepani, Listdata.svc is still available in SharePoint Online.
What's the response in your side ? Is there any error status.
You can also do a Post Request with CAML same as the Option 2 in the similar thread above.

**Comment by andrewconnell** [comment]
The primary OData endpoint, `_api`, should respect these functions per the docs. You should not be reverting back to the legacy **listdata.svc** endpoint or having to revert to CAML.

Investigating & will follow up...

**Comment by bcameron1231** [comment]
fwiw, I've never seen date functions work in the REST API, only in the SOAP APIs.

**Comment by diveshgup** [comment]
Hello,

I am trying to filter on a datetime field and i am getting issues.

When i use rest api and filter on Created, it works. however when i use EventDate, it does not.
When i use listdata.svc, same issue occurs.

Thanks.
Divesh

**Comment by thailakadre** [comment]
Hi, I am trying to use the OData function too in power automation(Flow). And I am receiving the same error.

Error:
body":{"status":400,"message":"The query is not valid.\r\nclientRequestId: xxxxxxxxxxxxxb\r\nserviceRequestId: xxxxxx"}}

Filter query.
day(Birthday) eq 28 and month(Birthday) eq 10

Please, someone knows if I am doing something wrong or if this error still happens?
