### ISSUE TITLE
Image Renditions are not working in SPO 

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#5483]
[x] Bug

The Image Rendition with resolution=6 is not working anymore. In the beginning, the issue is limited to my dev tenant only and now it effected our PROD tenant. I am not able find any links for the fix. 

## Steps to reproduce

1. Create any news with BannerImage in SharePoint Online Communication site.
2. Post the News
3. Try to get the BannerImageURL using RestApi from the List.
4. Append "resolution=6" at the end of URL
5. Append it to Image as Src 
6. Images will not be rendered.

## Expected behavior

resolution=6 should work like other renditions.

## Developer environment

- SharePoint Online
- Frameworks: SharePoint Framework, TypeScript, React
- Browser(s):  Chrome v79, Safari v22, FireFox v31, IE v11, Edge, Chromium Edge v79
- Tooling:  VS Code, SPFx v1.10.0

This problem occurred on PROD environment on 20th March and on DEV environment last month.

**Comment by bcameron1231** [comment]
Thank you for the question. This is working as expected. Image Renditions _are a thing of the past_. They are only provided for Classic Publishing Sites.

In Modern SharePoint Online, renditions are automatically provided and sized depending on the wise of the browser window. For more information on this, please see the following links.

https://docs.microsoft.com/en-us/office365/enterprise/image-optimization-for-sharepoint-online
https://docs.microsoft.com/en-us/office365/enterprise/modern-image-optimization

**Comment by c-eiser13** [comment]
I am seeing something similar across my environments and wanted to elaborate on what @arunakshi has described. I also have a news solution where I issue a REST call to the site pages library and the API returns a URL in the BannerImageUrl property formatted with the getpreview.ashx format: 

https://tenant.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=34b1234c280fc4c358c412a0083c67621&guidWeb=97c6e7e3ba07498dab6a51ef3ab6e58d&guidFile=e096014429a54bb445c83cf56e24ac6f&ext=jpeg&resolution=4

In the last couple weeks, we see intermittent 404's in the console with the call to getpreview.ashx and the image does not display. I've seen other posts on this repo where the search API began returning URL's with the new /_api/2.0 format for the PictureThumbnailUrl managed property, and I was hoping the BannerImageUrl would eventually start returning a URL formatted this way, but it has not and seems that getpreview.ashx may be going away? I've begun extracting the guidFile param from the BannerImageUrl property and creating the 2.0 format myself for the image url for my News solution and so far in testing, this has been working well, but really wanted to see if the API would eventually start returning the proper URL? I'm creating this format:

`https://tenant.sharepoint.com/_api/v2.0/sites/tenant.sharepoint.com,${siteId},${webId}/items/${itemId}/driveItem/thumbnails/0/medium/content?preferNoRedirect=true`

It is a little extra work, but has alleviated the 404's we were seeing intermittently with the URL's formatted with getpreview.ashx. Hopefully this helps add context to what I believe is being described in this issue.
