### ISSUE TITLE
PowerShell Automation

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5486]
Can below steps be done with PowerShell?

- Creating app on "appregnew.aspx"
- granting permissions on "appinv.aspx"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs#setting-up-an-app-only-principal-with-tenant-permissions)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
AppRegNew:
[AppRegNew.aspx in PowerShell](https://olafd.wordpress.com/2017/01/16/appregnew-aspx-in-powershell/)
In On-Premise environment, appinv.aspx can be set with [Set-SPAppPrincipalPermission](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spappprincipalpermission?view=sharepoint-ps), 
But for SharePoint Online, there is no PowerShell equal with it, please check the similiar question here:

[Set-SPAppPrincipalPermission equivalent in SharePoint Online
](https://sharepoint.stackexchange.com/questions/233878/set-spappprincipalpermission-equivalent-in-sharepoint-online)

**Comment by ravick4u** [comment]
Thanks @Jerry0527

**Comment by mattcobb** [comment]
In the first example, I get an error:  "AuthenticationManager does not contain a constructor that takes 0 arguments."

using System;
using System.Net;
using Microsoft.SharePoint.Client;

namespace spsample
{
    class Program
    {
        static void Main(string[] args)
        {
            string siteUrl = "https://pryoninc.sharepoint.com/SitePages/Home.aspx";
            Console.WriteLine("Hello World!");
            using (var cc = new AuthenticationManager().GetAppOnlyAuthenticatedContext(siteUrl,
                "12c4deb4-d08a-4e01-a26c-1d3f85738448",
                "redacted"))
            {
                cc.Load(cc.Web, p => p.Title);
                cc.ExecuteQuery();
                Console.WriteLine(cc.Web.Title);
            };
        }
    }
}
