### ISSUE TITLE
Exclude inheriting page-level CSS into webpart

### ISSUE THREAD

**Issue by lrolseth** [SharePoint/sp-dev-docs#5487]
## Category
- [x] Question

Is it possible to exclude or block a CSS file that is used at the page level and not have it interfere with my SPFx webpart CSS?
Example: The navigation uses bootstrap.css.  In my webpart, I am using material-ui controls - like TextField.  I don't want the bootstrap to overwrite the CSS from my controls when I put the web part on the page.  I'm hoping that I can find a workaround because transferring my form over to Fabric UI controls won't be easy due to some of the material ui features needed.

**Comment by andrewconnell** [comment]
Have you looked at how SPFx uses CSS Modules are used to avoid collisions with CSS classes? https://docs.microsoft.com/en-us/sharepoint/dev/spfx/css-recommendations
