### ISSUE TITLE
Resize SharePoint Online image by using the Microsoft Graph APIs not working properly

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#5488]
## Category

- [x] Bug

## Describe the bug
I am using the sharepoint graph API to resize the image but is not coming correctly.

Original Image

![image](https://user-images.githubusercontent.com/17681573/77397735-3f54e000-6dfa-11ea-894a-1207c67c517a.png)

After using the below URL to resize it, shows like below

https://xxx.sharepoint.com/_api/v2.0/sharePoint:${file.FileRef}:/driveItem/thumbnails/0/large/content

![image](https://user-images.githubusercontent.com/17681573/77397814-67dcda00-6dfa-11ea-8c3d-6133527a2d56.png)

## Steps to reproduce

I am using the below url- Velin Georgiev for the reference
https://blog.velingeorgiev.com/resize-sharepoint-image-by-using-microsoft-graph-api

## Expected behavior

Need to show the image properly

## Developer environment

- OS: [e.g. Windows 10, MacOS 10.15.x]
- Framework: Node.js 10
- Browser(s): Chrome
- Tooling: VS Code

### Additional context

I am using this for my image gallery developed in SharePoint Framework.

**Comment by nsksaisaravana** [comment]
My Height is 426 and width is 372.

For specific height and width also not working.

https://xxx.sharepoint.com/_api/v2.0/sharePoint:${file.FileRef}:/driveItem/thumbnails/0/c246x372/content

**Comment by andrewconnell** [comment]
This repo is for SharePoint development issues... this question is specifically related to Microsoft Graph. Can you please post this to the MS Graph support forums? Thanks: https://developer.microsoft.com/en-us/graph/support
