### ISSUE TITLE
The page does not render correctly

### ISSUE THREAD

**Issue by slyuso** [SharePoint/sp-dev-docs#549]
The referred page Url:
https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page

#### Category
- [X] Bug

#### Expected or Desired Behavior
Expect to page render correctly 

#### Observed Behavior
The page does not render correctly 

#### Steps to Reproduce
1. Open the page https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page
2. Scroll the page up to "Next Steps" section.
The left navigation is being overlapped with the main section content. 
This is observed on Windows 10 for both Edge and Chrome browsers 
See attached.
![2017-04-17](https://cloud.githubusercontent.com/assets/14893446/25104965/6ad988f0-2377-11e7-8995-5eec5bfffbdf.png)
The affected area is in red rectangle.

Thanks

**Comment by VesaJuvonen** [comment]
thx slyuso,
this is clearly an issue in our CMS system or the used stylings. Have reported that forward and this should get resolved soon.

**Comment by VesaJuvonen** [comment]
CMS has been ow fixed. Ctrl+F5 in your browser should fix the page. Closing issue, since it has been resolved.
