### ISSUE TITLE
Errors POST ing large files

### ISSUE THREAD

**Issue by Kevinrp01** [SharePoint/sp-dev-docs#5491]
Large File Posting works and the file gets uploaded, but returns 400 error code and states:  "POST method cannot be used for media resource" and recommends GET/PUT but but PUT does not allow to upload a new file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you share more about your query? What kind of file are you uploading, how big is "large", etc. Also need context... SharePoint environment, etc...

**Comment by Kevinrp01** [comment]
For testing I'm uploading a small file (simple json with one key:value pair) for testing. The POST does work, but comes back with an error message. 

The sharepoint/directory I'm uploading to is due to it beging crated by teams, so the directory name is something like "Shared Documents/my channel".  I did not do anything to enable media types for the sharepoint (as I see is an option in the site settings)



The code looks something like this:

```
       # headers also include bearer token
        headers['X-HTTP-METHOD'] = "POST"
        headers['Accept'] = "application/json;odata=verbose",
        headers['Content-Length'] = str(len(file_contents))
        headers['Content-Type'] = 'application/octet-stream'

        result = requests.post(
            (self.site_url +
             f"/_api/web/GetFolderByServerRelativeUrl(" +
             f"'{self.site_path}/{sharepoint_folder}')/Files/Add(url='{sharepoint_filename}', overwrite=true)"+
             "/$value"),
             headers=headers, data=file_contents)
```

The result comes back as the below **_(even though the post works)_**

```
{'error': {'code': '-1, '
                   'Microsoft.SharePoint.Client.InvalidClientQueryException',
           'message': {'lang': 'en-US',
                       'value': 'The HTTP POST method cannot be used for media '
                                'resource. The media resource could only be '
                                'accessed by HTTP GET or updated by HTTP '
                                'PUT.'}}}
```

**Comment by andrewconnell** [comment]
Why do you have `headers['X-HTTP-METHOD'] = "POST"`? That's not necessary... remove that to see if it helps.

What kind of file are you uploading? What file extension?

**Comment by Kevinrp01** [comment]
I've tried with and without the POST, same failure.

The name of the file being uploaded is "test.json"

**Comment by Kevinrp01** [comment]
changing to test.json.bin did not work

**Comment by andrewconnell** [comment]
How big is the file? Have you tried uploading it via the browser to ensure you can upload it?

Assuming you have reviewed this:
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#working-with-large-files-by-using-rest

Also, the Microsoft Graph REST API provides a useful resumable upload option which works well for large files in SharePoint Online:
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0

**Comment by Kevinrp01** [comment]
The working with large files documentation is what I reviewed and used as an example here (and where I found the link to provide feedback)

**Comment by bcameron1231** [comment]
Can you remove the **/$value** part of your call and let me know if it resolves the error?

**Comment by Kevinrp01** [comment]
Thank you that seemed to do it.  I thought I copy pasted from the docs to do this, but I admit it is not there now, not sure if I mixed it with the example below the big files or if it was updated, but either way, its working now. Thank you!
