### ISSUE TITLE
Decorate your http traffic to avoid throttling

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5492]
One of the recommendations is to avoid throttling is to decorate HTTP traffic. Does this mean that decorating message will reduce in throttling or completely stop throttling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic-to-avoid-throttling)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by krainer** [comment]
The decoration of your calls will not completely stop throttling (I still see 429/503/504 return codes in my scripts with decorated calls to both MS Graph and SPO REST API's).

As per the article, it will be prioritized over non-decorated traffic, meaning it should be reduced in throttling compared to non-decorated traffic.

I can recommend to look at the batch options in both the MS Graph and SPO REST API's to reduce the number of calls
