### ISSUE TITLE
Out of date - No longer workable

### ISSUE THREAD

**Issue by itsallbr0ken** [SharePoint/sp-dev-docs#5498]
I'm unable to complete the steps here as NodeJS and gulp no longer work together, even downgrading to versions that should work together causes problems due to being out of date, can you update the information here with the steps needed for current versions of the tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
The current supported LTS version of NodeJS for the SharePoint Framework is Node.js v10.x.

Notice that latest nodejs 12.x versions are currently not supported with SharePoint Framework development.

**Comment by andrewconnell** [comment]
@itsallbr0ken Need more context... as the document is written, the steps do work. Without more detail as to what problem you're having, it's impossible to troubleshoot.

**Comment by itsallbr0ken** [comment]
The issue is that gulp is incompatible with recent versions of node, i know the documentation states this, however, there are no instructions available if you have a later version (which most people will), i managed to get around the issue by installing node version manager (nvm) in order to switch my node versions depending on what i'm developing. Downgrading node to an older version was not an option as i do other development work that require a later version

**Comment by andrewconnell** [comment]
The docs can't cover every single use case for anything developers have on their environment. The docs explain what is required and supported and that's all they need to include.

FWIW, the next version of SPFx will drop support for Node v8 & add support for the latest LTS version, Node v12.

NVM is a great solution for having multiple versions of Node installed on your Windows/MacOS environment.

**Comment by chrsh18** [comment]
If the support docs rely on third party tools, you should ensure that it works. IMHO

**Comment by andrewconnell** [comment]
@chrsh18 They do... the docs are very clear on the versions that are currently supported. Node v10 LTS is still supported. Note v10 does not even reach EOL for another 12 months.

**Comment by chrsh18** [comment]
Thanks for your answer, node.js is not the problem gulp isn't working correctly. Too many optional dependencies are skipped.

**Comment by chrsh18** [comment]
I finally got it, here my working solution:

node-v8.15.0-x64
npm install -g yo gulp@3.9.1
