### ISSUE TITLE
Unable to update SC Server Resource Quota property

### ISSUE THREAD

**Issue by anbeel** [SharePoint/sp-dev-docs#5499]
## Category
- [x ] Question

## Question
We are able to update 'Server Resource Quota' property by below code ago.

  Tenant tenant = new Tenant(ctx); 
  var siteProperties = tenant.GetSitePropertiesByUrl("https://url", true); 
  tenant.Context.Load(siteProperties); 
  await tenant.Context.ExecuteQueryAsync();
  siteProperties.StorageMaximumLevel = 0.0;
  siteProperties.StorageWarningLevel = 24975.00;
  siteProperties.UserCodeMaximumLevel = 100.0;
  siteProperties.UserCodeWarningLevel = 80.0;
  var updatePropertiesOperation = siteProperties.Update();
  tenant.Context.Load(updatePropertiesOperation );
  await tenant.Context.ExecuteQueryAsync();

Recently above properties 'UserCodeMaximumLevel' and 'UserCodeMaximumLevel' can not be updated. Do you know why?

## Environment details

I test it in two tenants with same problem.

**Comment by bcameron1231** [comment]
Server Resource Quota was used for Sandbox Solutions running a site collection. Code Based Sandbox Solutions in SPO has been disabled.

AFAIK, adjusting this setting, doesn't do anything anymore.

**Comment by anbeel** [comment]
Thank you for quick response. It is bad news for me. It doesn't throw any exception. In the case we want to migrate this property from a site collection to another by CSOM.
