### ISSUE TITLE
What is the minimum version of JQuery that the framework requires if any?

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#55]
Running into an issue with particular versions of JQuery and third party plug-ins that require it. The Yo generator puts in a dependency of compatibility of 3.1.0. Are there any ramifications by changing the dependency to something lower so the plug-in can work?

**Comment by wictorwilen** [comment]
What issues do you see? I've used SPFx successfully with jQuery versions less than 3.1.0. Also, as soon as you have scaffolded your project using Yeoman, Yeoman is out of play and should not put any constraints on the solution.

**Comment by SteveCurran** [comment]
Thanks. Some third party plug-ins have issues with newer versions of JQuery. I was just wondering if the SP framework modules had any dependency on a certain version of JQuery.

**Comment by manishgarg1** [comment]
At the present time you can use any jQuery version to build your web part. There should be no issues. Please share more details about the exact problem you are seeing.
