### ISSUE TITLE
Deployment failed.  Correlation ID: bb94429f-7083-0000-4482-d9a6c875955e in Appcat log

### ISSUE THREAD

**Issue by piraga** [SharePoint/sp-dev-docs#5501]
## Category

- [x] Error

My .sppkg works fine in local work bench when I deploy it in my application it shows me Deployment failed.  Correlation ID: bb94429f-7083-0000-4482-d9a6c875955e. Please let me know how to figure out this issue to deploy my webpart.

Curious to know why this webpart works good in work bench, but failed deployment.

![image](https://user-images.githubusercontent.com/36080304/77656791-6813db80-6f9a-11ea-9bba-76e457bfae61.png)

**Comment by PrasadKasireddy** [comment]
Could you please share more details about environment, nodejs version details

**Comment by PrasadKasireddy** [comment]
Also, please check whether the app catalog & the tenant was created in same language (like English language ).

**Comment by piraga** [comment]
node --version
v8.17.0
npm --version
6.13.4

And this is React webpart for Microsoft Sharepoint online lastest. Please let me know I you need something else.

**Comment by piraga** [comment]
I have another webpart which is working fine and that webpart is cloned from git repo, but even fresh new welcome react webpart project after running yo @microsoft/sharepoint (without adding code) throw me same error after deploying it in my app cat log.

**Comment by piraga** [comment]
Steps I have dove are below:
1. yo @microsoft/sharepoint
(without adding new codes in my project)
2. gulp bundle --ship
3. gulp package-solution --ship

Even tried 
1. yo @microsoft/sharepoint
(without adding new codes in my project)
2. gulp clean
3. gulp bundle --ship
4. gulp package-solution --ship

But still facing the issue in my app cat log

**Comment by piraga** [comment]
Firstly, I have tried in node version 10. However, issue does not solved by downgrading the node version to 8 too.

**Comment by PrasadKasireddy** [comment]
as you mentioned that you cloned webpart from git repo, could you please follow the respective repo instruction and check whether any  dependency

**Comment by piraga** [comment]
I have tried with with same installation steps, and the project cloned from git is different web part, but having issue with simple HelloWorld fresh new webpart.

**Comment by cwdata** [comment]
@piraga 
Do you eventually have whitespace or other special characters in the name of the folder where you develop your Webpart? If yo, remove them, use only [a-zA-Z0-9], then repackage and reupload your solution. This may also count for parent folders of your solution (don't know exactly if that's the case).

**Comment by andrewconnell** [comment]
What version of SPFx?

The template for a new issue had a section about context information you could provide that helps in troubleshooting. We need all that information to help... SPFx version, Node version, environment, browser, SharePoint environment, etc.

Please help us help you...
