### ISSUE TITLE
Clarify if SiteStatus=2 means "created but unfinished" or "created and ready"

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#5502]
Please clarify if `SiteStatus=2` means "created and ready to be used" or just "created but please wait some time before using it". How _ready_ is "created"?

Why am I asking this? Because sometimes sites are _unfinished_ after creating them (at least for a couple of seconds).

How do I know this? We use PnP Provisioning a lot. And we create sites a lot and apply templates directly after creating sites. Sometimes we get strange errors indicating that the site is being manipulated in parallel by SharePoint itself. So SharePoint does some changes and we do some changes. They collide.

One example of SharePoint changing things after creating a site is group names. The default Visitor, Member and Owner groups are being renamed a few seconds after creating a site. SharePoint inserts the site name. I discovered this while working on unit tests in the PnP PowerShell repo.

What do we need? We need to now when site creation is finished _for sure_. Including asynchronous activities SharePoint does afterwards. Because currently our solutions all contain some kind of ugly "wait some minutes" code to be sure the site is ready.

This boils down to the question: Is `SiteStatus=2` the indicator that a site merely has been created? Or is it the indicator that the site has been created and _all post-creation activities have been applied as well_? (And if not: how can we determine the time we can take over?)

I'd like a hint to this potential issue being added to the documentation as it is important to know what "created" means. Is it "ready"? Or is it "created but please wait some time to use it"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I *believe* it means the site is created, but other things may still be provisioned. AFAIK, there's no property that says "everything is finished".

@JeremyKelley can you confirm?

**Comment by heinrich-ulbricht** [comment]
If there is no such property as "everything is finished" - what is the recommended approach for determining this state? How can we determine that everything is finished? Is polling for "expected finishness" of certain things the way to go? And if yes: what are (currently) the things that will be finished asynchronously that we need to wait for (like group names)?

Thanks a lot for looking into this. It's a common question when provisioning new sites.

**Comment by andrewconnell** [comment]
AFAIK, no... because there's no telling what else has hooked into the site creation process. It's similar to the scenario we have in Azure AD where creation/updating users are eventually consistent across the entire platform. There's no "done replicating" event in that scenario...

¯\_(ツ)_/¯
