### ISSUE TITLE
headerBackground: strong not being applied to modern team site using site script and setSiteBranding verb.

### ISSUE THREAD

**Issue by mjarmstrong** [SharePoint/sp-dev-docs#5504]
Hello, I am applying a site design to a modern team site, but not all of my actions are being applied. While the theme is correctly being set, none of the options in setSiteBranding are being applied (headerLayout is not being set to compact, and headerBackground is not being set to strong. Script below, please advise. 

{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json",
  "actions": [
    {
      "verb": "setSiteBranding",
      "headerLayout": "Compact",
      "headerBackground": "Strong"
    },
    {
      "verb": "applyTheme",
      "themeName": "Company collab"
    }
  ],
  "bindata": {},
  "version": 1
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by mjarmstrong** [comment]
Update. Re-applying the site design using Invoke-SPOSiteDesign after creation correctly applies the setSiteBranding action, though it is not applied on site creation by default.

**Comment by JarbasHorst** [comment]
Hello @mjarmstrong 

I haven't been able to reproduce this issue using the provided Site Script. Can you please provide us more information:
- Do you get errors when applying this Site Script on site creation? Consider also checking the network traffic to get detailed information.
- How often have you faced this issue?
- Does it also happen when applying the Site Script to a communication site or when applying the Site Script to an existing modern team site?

Regards,
Jarbas

**Comment by mjarmstrong** [comment]
Hi @JarbasHorst, well, this is awkward. I just went through the steps again to take screen shots for you, and it appears to be working fine. Must've been a user error somewhere along the lines. Apologies and thank you for the quick reply.

**Comment by JarbasHorst** [comment]
No worries and thank you for the feedback!
