### ISSUE TITLE
limit spfx app into specific site collection/subsite

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#551]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Is it possible to limit the installation of the spfx app into just a single site collection/subsite? Something like this documentation: https://msdn.microsoft.com/en-us/library/office/fp179896(v=office.15).aspx#AppScope

**Comment by VesaJuvonen** [comment]
Hi,
this is currently not supported, but we are looking for site collection specific app catalog possibility in the future. There's however no public schedule for this currently.
