### ISSUE TITLE
Where does the MyStyleSheet.css file go?

### ISSUE THREAD

**Issue by leighwebber** [SharePoint/sp-dev-docs#5513]
The examples show the CSS file as MyStyleSheet.css, but we are not told where to store that CSS file. With no path information, I guess the system will expect MyStyleSheet.css to be .... where, exactly? On the server in a hive? On a local path on the server? In a library on the current SharePoint website? If you guess wrong, you will get a SharePoint crash when you try to open a page using your page layout, and ULS viewer will show the error as "File not found". Of course it can't find the file, because I have no idea where to put it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53944252-7624-4b1c-970d-398b69b9fee1
* Version Independent ID: 7aede32f-6ba1-3875-cb1d-7fa9570a7674
* Content: [Create a page layout in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-page-layout-in-sharepoint?redirectedfrom=MSDN#feedback)
* Content Source: [docs/general-development/how-to-create-a-page-layout-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-create-a-page-layout-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
You can place the file anyplace you see fit. You could place it in the master page gallery, you could put it in the Style Library on the site. Just put it into a location that will be accessible by everyone. Wherever you place it, just update the href to that location.

**Comment by Jerry0527** [comment]
CSS file can be stored in some places like Site Asserts, Master Page Gallery or 15 hive folder even a normal document library is also available.
This will depend on your needs.
And you will need to set at least read permission for everyone so that they can access.
