### ISSUE TITLE
regarding <.scss.ts> file

### ISSUE THREAD

**Issue by hilfiger1014** [SharePoint/sp-dev-docs#5516]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

If we create a file in Visual Studio Code, we couldn't find the file named <xxxxx.scss.ts> in the Visaul studio code explorer window. but actually we could find it in the local disk.

does anyone have any way to solve it out.?

**Comment by nanddeepn** [comment]
When building your SPFx project, the SASS module gets processed and a TypeScript representation of your SCSS styles named “MyComponent.module.scss.ts” will be generated.

**Comment by hilfiger1014** [comment]
thanks. got it
