### ISSUE TITLE
regarding "window.open"

### ISSUE THREAD

**Issue by hilfiger1014** [SharePoint/sp-dev-docs#5518]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

When I try to use SPFX to do some customization for my document library. I created a ListView Command Set extension for set listitem permission. the simple scenario is when user select a listitem or document, he/ she could click the "Set item permissions" on the ECB menu and open a new window. my question is when we open the new window, my code is :

> window.open(`${this.context.pageContext.web.absoluteUrl}/_layouts/15/user.aspx?List=%7B${listId}%7D&obj=%7B${listId}%7D,${event.selectedRows[0].getValueByName('ID')},**LISTITEM**`, '_blank');

and found out a parameter called "LISTITEM", whether or not we could change this parameter to others, or the parameter is fixed cannot be changed.??

Thanks

## Submission guidelines (delete this section before submitting)

*Thanks for your contribution! Sharing is caring.*

**Comment by OS-Lee** [comment]
Hi,

You should call window.open in your onExecute function.

`@override
public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
  switch (event.itemId) {
    case 'yourCOMMAND':
      window.open(${this.context.pageContext.web.absoluteUrl}/_layouts/15/user.aspx?List=%7B${listId}%7D&obj=%7B${listId}%7D,${event.selectedRows[0].getValueByName('ID')},**LISTITEM**, '_blank');
      break;    
    default:
      throw new Error('Unknown command');
  }
}`

The obj parameter used to check the object type which you want to set permission based on my researching so you should not change it.

For example:

For List item:
/_layouts/15/user.aspx?List={6D175EE3-5EC5-4981-9912-C30B4FE69BC7}&obj={6D175EE3-5EC5-4981-9912-C30B4FE69BC7},1,LISTITEM

For List:

/_layouts/15/user.aspx?obj={6D175EE3-5EC5-4981-9912-C30B4FE69BC7},list&List={6D175EE3-5EC5-4981-9912-C30B4FE69BC7}

**Lee
Microsoft SharePoint Community Support**

**Comment by hilfiger1014** [comment]
> Hi,
> 
> You should call window.open in your onExecute function.
> 
> `@override public onExecute(event: IListViewCommandSetExecuteEventParameters): void { switch (event.itemId) { case 'yourCOMMAND': window.open(${this.context.pageContext.web.absoluteUrl}/_layouts/15/user.aspx?List=%7B${listId}%7D&obj=%7B${listId}%7D,${event.selectedRows[0].getValueByName('ID')},**LISTITEM**, '_blank'); break; default: throw new Error('Unknown command'); } }`
> 
> The obj parameter used to check the object type which you want to set permission based on my researching so you should not change it.
> 
> For example:
> 
> For List item:
> /_layouts/15/user.aspx?List={6D175EE3-5EC5-4981-9912-C30B4FE69BC7}&obj={6D175EE3-5EC5-4981-9912-C30B4FE69BC7},1,LISTITEM
> 
> For List:
> 
> /_layouts/15/user.aspx?obj={6D175EE3-5EC5-4981-9912-C30B4FE69BC7},list&List={6D175EE3-5EC5-4981-9912-C30B4FE69BC7}
> 
> **Lee Microsoft SharePoint Community Support**

Hi Lee,

the "list" or "listitem" in the URL is fixed, we cannot change it. right??

**Comment by OS-Lee** [comment]
Hi,

I checked the logic from SharePoint 2019, the value is type of enum used to check permission object type which you want to set, can't be change. I think it's same logic as SharePoint online.

**Lee
Microsoft SharePoint Community Support**

**Comment by hilfiger1014** [comment]
> Hi,
> 
> I checked the logic from SharePoint 2019, the value is type of enum used to check permission object type which you want to set, can't be change. I think it's same logic as SharePoint online.
> 
> **Lee Microsoft SharePoint Community Support**

Hi Lee,

thanks, may I know where to find the documentation.??

**Comment by OS-Lee** [comment]
Hi,

It's a application page which can't be customized for SharePoint online, and I didn't find official documentation to document so details for this.

**Lee
Microsoft SharePoint Community Support**
