### ISSUE TITLE
This may be a problem with a HTTPS certificate. Make sure you have the right certificate

### ISSUE THREAD

**Issue by EY2023** [SharePoint/sp-dev-docs#5520]
![2020-03-29_23-51-52](https://user-images.githubusercontent.com/62847185/77854682-3ca12300-721e-11ea-866a-dcc6cf97d346.jpg)
![2020-03-29_23-51-52](https://user-images.githubusercontent.com/62847185/77854687-49be1200-721e-11ea-9136-a7ddc9c6a13c.jpg)

## Category

- [x] Bug

## Describe the bug

We have developed few web parts using SharePoint Framework SPFX for one of our portal that is powered by SharePoint Online and was working fine. Until 27 March,, there is an issue in loading the web parts. Please refer to the attached screenshot of the error.

- OS: [e.g. Windows 10, MacOS 10.15.x]
- Framework: [e.g. .NET Framework v3.x, .NET Core v3.x, Node.js v6/v8/v10/v12]
- Browser(s): [e.g. Chrome v79, Safari v22, FireFox v31, IE v11, Edge, Chromium Edge v79]
- Tooling: [e.g. VS Code, SPFx v1.10.0, Visual Studio 2019] 

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Those look more like 404's than cert issues. Few questions:

- have you verified the files in question are reachable via the browser (directly, not via the web part)?
- have you verified the component is still deployed & installed?
- have you checked the /ClientSideAssets library to see if the files are there?

In your original post, you didn't edit the context bullet points at all... those are there for a reason to provide context with the browser/platform. Please update that/

**Comment by EY2023** [comment]
> Those look more like 404's than cert issues. Few questions:
> 
> * have you verified the files in question are reachable via the browser (directly, not via the web part)?
> * have you verified the component is still deployed & installed?
> * have you checked the /ClientSideAssets library to see if the files are there?
> 
> In your original post, you didn't edit the context bullet points at all... those are there for a reason to provide context with the browser/platform. Please update that/

The component is deployed and installed. All the files are reachable via browser. Below are the errors found from the browser console log. Not sure if there are any changes made by Microsoft to the SharePoint Online environment recently. The error is intermittent.
![2020-04-03_12-24-13](https://user-images.githubusercontent.com/62847185/78324049-242a6300-75a6-11ea-9a77-18275f1770de.jpg)

**Comment by andrewconnell** [comment]
Few more points of clarification:

@EY2023 said:
> Until 27 March,, there is an issue in loading the web parts. 

Are you saying the error STARTER on March 27 or happened UNTIL March 27 and no longer happens

Also, at the end of the OP, there was a section for you to provide context, but you apparently didn't do anything with it. Please add that in your reply or update the OP... context is key for issue reports.

With all that said, if you can get to the files & the error is intermittent, it might be related to the extra load SPO has had on it since the cloud demand skyrocketed in March/April across the world. If so, there's not much we can do about it here... but they are aware and working on these issues.

**Comment by Sendil85** [comment]
Hello,
I do have the same issue, its work fine in workbench, other than IE.
Stuck with this issue for a while, is there any solution for this?
I have deployed it in  Appcatalog site.
those files are accessible via browser
https://publiccdn.sharepointonline.com/<tenant>/sites/<appcatalog>/ClientSideAssets/ff82b95b-2168-474c-b8e4-a72de48366d7/spfx-student-search-web-part_6f14a2d1a811d0dcd4010788bfa0b558.js, but it still says
There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
