### ISSUE TITLE
ApplyTheme and ApplyTenantTheme are identical?

### ISSUE THREAD

**Issue by pconnell99** [SharePoint/sp-dev-docs#5523]
If you look the invocations are identical apart from the URL.  Applying a theme should not require the JSON to be sent!  All it should do is apply a named template from an ApplyTenantTheme setup?

This has caused major confusion on a project we are working on!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d43002-eb85-711b-a441-6fc772614e6b
* Version Independent ID: 6ef38943-3cb1-ff5f-0fbb-1498b63f6cc9
* Content: [SharePoint site theming - REST API](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api#applytheme)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Your comment isn't clear... can you please clarify? Are you saying...

- the code sample is incorrect for `ApplyTemplate`
or
- in your opinion, you shouldn't have to include the theme JSON with the `ApplyTemplate` endpoint?

**Comment by bcameron1231** [comment]
ApplyTenantTheme is not a valid endpoint. The two endpoints are **ApplyTheme** and **AddTenantTheme**. 

To clarify, you need to pass the Theme JSON to both commands as this is how the REST endpoint was built.

However, there is a difference between ApplyTheme and AddTenantTheme. ApplyTheme will apply a theme to a site **without** adding it to the tenant theme catalog (meaning it won't be available in the UX). AddTenantTheme only adds the theme to the tenant to be available for selection in the UX, but does not apply the theme.

If you want to use a theme that you've added to your Tenant Theme Catalog.You would use GetTenantThemingOptions, select the theme you want from the results return, and use the JSON in the ApplyTheme method.

Hope this helps.
