### ISSUE TITLE
Unable to deploy a working spfx package to new site collections

### ISSUE THREAD

**Issue by mhazebroucq** [SharePoint/sp-dev-docs#5525]
## Category

- [x] Bug

## Describe the bug

Since a few weeks, I am not able to deploy spfx app on newly created site collections.
The spfx works well on old site collections but when I try to add it on a new site I get this error message :
![image](https://user-images.githubusercontent.com/6292435/77915393-b0cbdd00-7297-11ea-823c-c3d0a37048b9.png)

And if I try to add it by using pnp powershell I get this error message :

Install-PnPApp : {"odata.error":{"code":"-2146232832, Microsoft.SharePoint.AppPackageValidationException","message":{"lang":"en-US","value":"There were errors when validating the App manifest."},"innererror":{"message":"There were
errors when validating the App manifest.","type":"Microsoft.SharePoint.AppPackageValidationException","stacktrace":"   at Microsoft.SharePoint.Packaging.SPAppManifest.ValidateAndLoadXML(Stream xmlFileStream, XmlReaderSettings
settings)\r\n   at Microsoft.SharePoint.Packaging.SPAppManifest.ValidateAndLoadManifest(Stream manifestStream)\r\n   at Microsoft.SharePoint.Packaging.SPPackagePartBackedAppManifest.<.ctor>b__0()\r\n   at
Microsoft.SharePoint.Utilities.SecurityContext.RunAsProcess(CodeToRunElevated secureCode)\r\n   at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(WaitCallback secureCode, Object param)\r\n   at
Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(CodeToRunElevated secureCode)\r\n   at Microsoft.SharePoint.Packaging.SPPackagePartBackedAppManifest..ctor(PackagePart appManifestPackagePart)\r\n   at
Microsoft.SharePoint.Packaging.SPAppManifest.Create(PackagePart manifestPart)\r\n   at Microsoft.SharePoint.Packaging.SPPackageFactory.CreateAppPackage(Package opcPackage, TemporaryDirectory tempDir, Boolean extract)\r\n   at
Microsoft.SharePoint.Packaging.SPPackageFactory.CreatePackage(Stream stream, Boolean extract)\r\n   at Microsoft.SharePoint.Administration.SPApp.CreateAppAndCommitPackage(SqlSession session, Byte[] fingerprint, String path, Guid
siteId, String assetId, String contentMarket, SPAppSource source, Boolean throwIfClientSolution)\r\n   at Microsoft.SharePoint.Administration.SPApp.CreateAppUsingPackageMetadata(Stream appStream, SPWeb web, SPAppSource source,
Boolean isCabStream, String assetId, String contentMarket, Boolean throwIfClientSolution)\r\n   at Microsoft.SharePoint.Utilities.MarketplaceUtilities.CreateAppUsingPackageMetadata(Stream appStream, SPWeb web, SPAppSource source,
Boolean isCabStream, String assetId, String contentMarket)\r\n   at Microsoft.SharePoint.Utilities.MarketplaceUtilities.InstallAppSynchronously(SPWeb web, Stream appStream, String oauthAppId, Guid productId, Boolean isUpgrade,
CultureInfo installationCulture, SPAppSource source)\r\n   at Microsoft.SharePoint.Utilities.MarketplaceUtilities.TriggerAppInstall(SPWeb web, String appCatalogId, SPAppMetadataCatalogType appCatalog, String oauthAppId, Boolean
isUpgrade, CultureInfo installationCulture)\r\n   at Microsoft.SharePoint.Marketplace.CorporateCuratedGallery.SPCorporateCatalogAppMetadata.Install(SPWeb web, Boolean allowLegacyApps)\r\n   at
Microsoft.SharePoint.Marketplace.CorporateCuratedGallery.SPCorporateCatalogAppMetadata.Install()\r\n   at Microsoft.SharePoint.Marketplace.CorporateCuratedGallery.SPCorporateCatalogAppMetadataServerStub.InvokeMethod(Object target,
String methodName, ClientValueCollection xmlargs, ProxyContext proxyContext, Boolean& isVoid)\r\n   at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, ClientValueCollection
args, ProxyContext proxyContext, Boolean& isVoid)\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.InvokeMethod(Boolean mainRequestPath, Object value, ServerStub serverProxy, EdmParserNode node, Boolean
resourceEndpoint, MethodInformation methodInfo, Boolean isExtensionMethod, Boolean isIndexerMethod, Boolean useArgumentNode)\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPathMember(Boolean
mainRequestPath, String path, Object value, EdmParserNode node, Boolean resourceEndpoint, MethodInformation& methodInfo)\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPath(Boolean mainRequestPath,
String path, String pathForErrorMessage)\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.Process()\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.ProcessRequest()\r\n   at
Microsoft.SharePoint.Client.Rest.RestService.ProcessQuery(ClientServiceHost serviceHost, Stream inputStream, IList`1 pendingDisposableContainer)"}}}
At E:\EmaxPro\ActivateSpfxFeature.ps1:79 char:4
+             Install-PnPApp -Identity $FeatureToActivate.Id -Scope ten ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Install-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Apps.InstallApp

## Developer environment

- OS: Windows 10
- Framework: Node.js v10.19
- Browser(s): Chrome v80, Chromium Edge v81

### Additional context

package.json content :
{
  "name": "scripts-injection",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/decorators": "~1.4.0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.0",
    "@microsoft/sp-module-interfaces": "~1.4.0",
    "@microsoft/sp-webpart-workbench": "~1.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

.yo-rc.json content :
{
  "@microsoft/generator-sharepoint": {
    "isCreatingSolution": true,
    "environment": "onprem19",
    "version": "1.9.1",
    "libraryName": "scripts-injection",
    "libraryId": "d7a4566b-9565-4cdd-a4e1-f7dc73fa061e",
    "packageManager": "npm",
    "componentType": "extension",
    "extensionType": "ApplicationCustomizer"
  }
}

Thanks for your help

**Comment by andrewconnell** [comment]
What's the environment? Need context...

Also, have you tried installing this without using the PnP tools, rather via the browser & app catalog?

**Comment by mhazebroucq** [comment]
> What's the environment? Need context...
> 
> Also, have you tried installing this without using the PnP tools, rather via the browser & app catalog?

Hi Andrew

The develoment has been done on VSCode on a Windows 10.
The SP farm is installed on 4 servers Windows 2016 Enterprise and Configuration database version: is v 16.0.10357.20002.
What other type of information do you need?

I tried to install deploy it using both GUI and PnP tools.

Thanks in advance for your help

**Comment by mhazebroucq** [comment]
Hi

For information if I try to install a new application in the SharePoint App Store, I get an error message too:
![image](https://user-images.githubusercontent.com/6292435/78227172-2d93cc80-74cd-11ea-96db-c9a459c692eb.png)

**Comment by andrewconnell** [comment]
@mhazebroucq said:
> What other type of information do you need?

I can't see where you've said what version of SP you're using... I'm guessing on-prem, but SharePoint Server 2016 or 2019?

@mhazebroucq said:
> For information if I try to install a new application in the SharePoint App Store

App Store? Do you mean App Catalog?

Your last comment shows an error in the app manifest. If you create a new project with zero customizations, do you get the same error?

**Comment by mhazebroucq** [comment]
I'm on SharePoint 2019 enterprise.

I just tried to create a new HelloWorld extension using yo @microsoft/sharepoint without modifying anything and the result is the same when adding it to the App Catalog.

I also tried to launch gulp server using a page of my SP2019 and everything works fine...

Can you help me please ?
Thanks in advance

**Comment by mhazebroucq** [comment]
@andrewconnell FYI it seems I encounter the same error as @krishnavandanapu in issue https://github.com/SharePoint/sp-dev-docs/issues/3490

I followed all the thread and I did not understand how @krishnavandanapu fix this issue.
Pease @krishnavandanapu could you give us more information on that DNS issue please ?

**Comment by andrewconnell** [comment]
Unfortunately, as you can see from that other issue, this is directly related to the setup & config of apps in your environment.

If a default project won't work with zero customizations, then there's not much we can do in this repo as it isn't a development issue, rather it's an installation & config issue with your deployment. Suggest you post the question to TechCommunity as that's where questions like this should go...
