### ISSUE TITLE
Please provide the code to show how to set JSON configuration to provisioning engine

### ISSUE THREAD

**Issue by frankchen76** [SharePoint/sp-dev-docs#5536]
It seems like the doc doesn't provide the sample to show how to set those json configuration to the engine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8604e955-4a77-7abe-0138-e554fdef0b41
* Version Independent ID: b03bc3e7-88ec-b808-190c-32e69f0b968e
* Content: [Configurating the PnP Provisioning Engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine#feedback)
* Content Source: [docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thank you for the comment. Yes, the documentation does make it a little unclear. To clarify, the configuration settings is in regards to the "Get-PnPProvisioningTemplate" command above it. 

You would pass in your configuration to this command. Please see documentation [here](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#parameters). 

`Get-PnPProvisioningTemplate -Out "Test.xml" -Configuration "MySchema.xml"`
