### ISSUE TITLE
Overwrite attribute of <Field> element is not working while provisioning site column from SPFx solution

### ISSUE THREAD

**Issue by cjmorelock** [SharePoint/sp-dev-docs#5537]
## Category
- [x] Bug
- [ ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I'm trying to declaratively provision site columns (Field) in an SPFx solution to a SharePoint Online site.  I want to use the 'Overwrite="TRUE"' attribute of the Field element as documented at https://docs.microsoft.com/en-us/sharepoint/dev/schema/field-element-field.  When attempting to install (Add) the solution in a site, I receive the following Install Errors message:

> "There were problems with the app web definition in the package.
> Details: Deployment failed in host web...Microsoft.SharePoint.SPException: Feature definition with Id...failed validation...**The 'Overwrite' attribute is not allowed.** at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack(Object sender, ValidationEventArgs evtargs)..."

This is the same issue that was reported previously in #3805. 

## Environment details (if applicable)

- Tooling:  VS Code, SPFx v1.10.0

**Comment by andrewconnell** [comment]
That's by design... that property isn't supported when applying the feature from an SPFx component.
