### ISSUE TITLE
Any plans for ES6 & AMD support

### ISSUE THREAD

**Issue by manivannan-mp** [SharePoint/sp-dev-docs#554]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
1) Any plans to support ES6 insted of typescript.
2) Any sample about how to load & run project in AMD Module

**Comment by StfBauer** [comment]
1.) The ES6 syntax, or the official name ECMAScript 2015, is just a subset of the capabilities you have in TypeScript. I recommend you to read [TypeScript, ES6, Questions, Answers](https://daveceddia.com/typescript-es6-questions-answers/).
You will also find a good overview over the capabilites in ES6 and TypeScript
[http://kangax.github.io/compat-table/es6/](http://kangax.github.io/compat-table/es6/)

2.) There is a good tutorial that shows [how to use external libraries in SPFX](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md). This tutorial use jQuery, which is based on AMD.

Hope this answers your questions.

**Comment by chakkaradeep** [comment]
@manivannan-mp 

1) We do not currently have plans to support ES6 syntax but only TypeScript.

2) Can you be more specific on what you mean by AMD support? We already support those in SPFx solutions.

**Comment by iclanton** [comment]
Closing this issue as there hasn't been any activity in several months.
