### ISSUE TITLE
Weird behavior of Page Customizer in library view (Hub Site)

### ISSUE THREAD

**Issue by salascz** [SharePoint/sp-dev-docs#5543]
## Category
- [x] Question

## Question

Hello,
we have a page customizer deployed on the hub sites + associated sites. The customizer contains custom footer implementation. The footer contains a simple link to expand/collapse:

`<Link href="#" onClick={onCollapseClick}><Icon iconName="ChevronDown" /></Link>`

The solution was used for a few months without any issue.

Suddenly, the page is reloaded when the user clicked on expand/collapse button. The issue occurs in the library on **hub site only** (associated sites are not affected).

Was there any update deployed recently that could cause such an issue?

Thanks

## Environment details
 - OS: [Windows 10, MacOS ]
 - Browser(s): [Chrome v80, Edge]
 - Tooling: [SPFx v1.9.1, SPFx v1.10.0]

**Comment by andrewconnell** [comment]
Page customizer?

I don't have visibility into changes rolled into production in SPO. Is your code snippet exact... the `href="#"`? Curious if this is impacting it: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

If so, maybe try setting the `data-interception` attribute on the link to `off`?
