### ISSUE TITLE
Office Schema URI should be allowed in JSON formatting HREF

### ISSUE THREAD

**Issue by bbouski** [SharePoint/sp-dev-docs#5545]
Enable Office URI Schemes in href formatting: https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes
For example to allow reformatting a file link that would open a Word document as a new document (on a template library)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Is your comment a feature request? It seems so... in that case, please follow the guidelines in our docs for submitting a feature request: https://docs.microsoft.com/en-us/sharepoint/dev/support-feedback
