### ISSUE TITLE
Enabling & disabling Content Approval in page library nullfies the OOTB PromotedState managed property

### ISSUE THREAD

**Issue by mmohamedbasith** [SharePoint/sp-dev-docs#5548]
## Category

- [x] Bug

## Describe the bug

I have a site with page library. By mistake i enabled the Content Approval for library (in version settings) .Then i reverted by disabling the content approval.

Now pages in that library gives PromotedState Managed property value as empty. Even for newly created pages in that site,PromotedState Managed property is empty (Though the library view shows the promote state value , it is not picked by search PromotedState Managed property)

## Steps to reproduce

Steps to reproduce:
1)Go to any sharepoint modern site
2)Go to Site Pages-->Library settings --> version settings -->Enabled Content Approval for Site pages in library settings 
2)Create News, publish and approve.
3)Then Disable Content Approval for site pages. 

Now try to Check the PromotedState Managed property value for the old and new pages (i used Chrome SharePoint Editor extension & SearchQuerytool for checking the ManagedProperty) .PromotedState Managed property return Empty for all the Pages in the Site.

## Expected behavior

After disabling Content Approval for page library, "PromotedState" Managed property should return value for old pages . If not for old pages, at least for newly created pages "PromotedState" Managed property should return value.

*Thanks for your contribution! Sharing is caring.*

**Comment by sympmarc** [comment]
As you describe this, I would see it as a bug. (Editorial: Asking about things like this on Twitter isn’t the best approach.)

PromotedState indicates the editing state and what type of page it is. It’s named oddly and unfortunately displayed as numbers rather than relevant state names. Whether or not approval is enabled shouldn’t have a bearing on the value in PromotedState, just whether it makes it to 2 for News Posts.

**Comment by wobba** [comment]
@mmohamedbasith can you verify that all the pages are published, having a major version?

**Comment by mmohamedbasith** [comment]
Yes, all are in major version.

**Comment by andrewconnell** [comment]
Unfortunately, this isn't the right place for this question... this is for SharePoint development topics. Please see the links in the auto-comment for guidance on where to post this.
