### ISSUE TITLE
CreateSPAsyncReadJob Returning 500 Internal Server Errors

### ISSUE THREAD

**Issue by richmcgni** [SharePoint/sp-dev-docs#5549]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

I am attempting to kick of an Async Metadata Read job at a library level using the CreateSPAsyncReadJob endpoint. This location has previously worked but today it is returning 500 Internal Server errors with the following message:
Failed to verify async read options on url Error: Failed to determine object type of {url} Only folder, document library, or list are valid object types to run async read.

The url I have passed in worked last week. Has there been any changes to this API and deployed to tenants since 3rd April 2020?

**Comment by andrewconnell** [comment]
No context... need details to know what environment you're referring to.

If it's SPO, 500 errors are service issues... they aren't dev issues, so, unfortunately, there's nothing we can do here. MSFT has said to open a ticket in these cases.

**Comment by richmcgni** [comment]
So the environment was SPO, and it has been fixed and now works again so this can be closed
