### ISSUE TITLE
SPFX addin manifest not working on Outlook Desktop 

### ISSUE THREAD

**Issue by dineshR86** [SharePoint/sp-dev-docs#5552]
## Category

- [x] Bug

## Describe the bug
The Manifest provided as part of the SPFX solution dosent work on the outlook desktop version. When we try to upload the manifest file on a desktop version of outlook the addin is not visible. If the addin manifest is uploaded as part of the web version the addin is visible on the web but not visible on the desktop version.

## Steps to reproduce
1.  Navigate to the web version of outlook and Click on the get addins and upload the addin manifest file under the My addins section. 
2.  Install the addin.
3.  addin works well on the web version of outlook. 
4.  Try to browse the same addin on the desktop version of the outlook. The addin is not visible. 
5.  The same behaviour is shown when the manifest file is uploaded from the desktop version.  

## Expected behavior

The SPFX addin should be visible from both the web and desktop version of outlook.

## Developer environment

- OS:  Windows 10
- Framework: Node js
- Browser(s): Chrome v80
- Tooling: [e.g. VS Code, SPFx v1.10.0, Visual Studio 2019] VS code, SPFX v1.10 

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by nanddeepn** [comment]
Hi @dineshR86 ,

Please see the documentation [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-addins-create)

> During preview time frame, this feature is only supported within the context of the Outlook Web Access. Feature will be however supported across all Office desktop and web clients when it will be generally available.

**Comment by dineshR86** [comment]
@nanddeepn  thanks for pointing that out. Missed that part. Any idea when it will be generally available?
