### ISSUE TITLE
UserAgent matching of decorated traffic

### ISSUE THREAD

**Issue by smotti** [SharePoint/sp-dev-docs#5555]
Can the values for the CompanyName and AppName also be the UIDs or do they have to be the human-readable strings?

Or in general how is the UserAgent header actually evaluated to determine to which app/company it belongs?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic-to-avoid-throttling)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by smotti** [comment]
With UIDs i mean ISV GUID or Tenant ID for the CompanyName, and the AppID for AppName.

**Comment by andrewconnell** [comment]
These are used to help MSFT identify the vendor impacted by this. If you use GUIDs, that's not easy. They should be exactly what's shown in the doc: Company Name & App Name... not GUIDs.
