### ISSUE TITLE
Client ID expire?

### ISSUE THREAD

**Issue by gheester** [SharePoint/sp-dev-docs#5557]
Hi, I have a few questions..

Under the section "Create a client secret that is valid for three years", why does it say "The clientId needs to match your expired clientId.". How can clientId expire? 

$keys = Get-MsolServicePrincipalCredential -AppPrincipalId $clientId
What 'ReturnKeyValues' parameter is this expecting? If I just enter "1" I get many, many results back for 1 Client ID? 

IMPORTANT:
How can we have multiple Secrets so we don't have a production issue when one expires. Or, how would we avoid a production issue as soon as the secret expires. There would be hours between picking up the expiry, generating the new one, and setting it, especially if we have to wait 24 hours as it says above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9d8235-c495-a7a3-a4a6-0d073db41d1d
* Version Independent ID: bdd22da6-06c6-569d-fccf-fd55baa3cef8
* Content: [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in#feedback)
* Content Source: [docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
The message about ClientID match your expired ClientID is just to make sure you are updating the _correct_ expired secret. Your ClientIDs do not expire. We could probably make this more clear in the documentation.

-ReturnKeyValue is just a boolean to specify whether the command should return key values. [See documentation.](https://docs.microsoft.com/en-us/powershell/module/msonline/get-msolserviceprincipalcredential?view=azureadps-1.0)

In terms of being prepared for expiring secrets. There are a couple of options that you have. You could just mark it on your calendar to send you a notification a few days before the secret expires, to let you know to update your secrets. Or, what I've done is actually create a Task Schedule for the PowerShell script in this document (get principals, loop, find end dates) to check expiring secrets with an EndDate of Today + 3 days, and to notify me it's expiring.

Then I follow the documentation provided about using the "SecondaryClientSecret" in the Web.Config, which allows for the fallback when my secret expires for my production apps.

I hope this helps.

**Comment by gheester** [comment]
Yes it does help, many thanks for this. I like your suggestion about the scheduled task. I have also proven in my lab that the current secret and the newly created secret both work, hence a few days before expiry we can generate a new key and give it to the external system, knowing the old one will still work for a few days whilst they update their system. A side note: the client ID and secret is given to consuming parties, but they will not use the appSettings (XML). The secondary secret seems to work regardless of that appSettings.
