### ISSUE TITLE
Issue is back: Failed to synch SPFX apps to Teams 

### ISSUE THREAD

**Issue by negarfield** [SharePoint/sp-dev-docs#5558]
## Category

- [x] Bug/issue probably  #5425 is back!

## Describe the bug
I think this is a similar problem to what was dicussed here: https://github.com/SharePoint/sp-dev-docs/issues/5425  #5425   in early March 2020 and was set to resolved then but it is back now.

-	We have an SPFX package (Teams app) that we have deployed previously to the SP catalogue and have previously also tried to synch to Teams app store on our Preprod tenant successfully.
-	However, Since Mnday April 6th we realised synch to Teams is not working on this tenant anymore with the error message : failed to synch to Teams

-	Inspecting the browser console, I see the error: 
**HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(XHR)POST - https://[tanant].sharepoint.com/sites/apps/_api/web/tenantappcatalog/SyncSolutionToTeams**
 
-	A month ago in early March, many people reported this problem on their tenants and Microsoft fixed it within 24 hours, but it seems like the issue is back, please see Vesa’s reply on the thread below: https://github.com/SharePoint/sp-dev-docs/issues/5425

## Steps to reproduce
1. Go to SP app catalog
2. upload and deploy an SPFX Teams app
3. Try "Synch to Teams" - it fails!
4. Inspect the browser console for error

## Developer environment
This is observed on a pre-production tenant upon deployment, not a developer tenant

**Comment by andrewconnell** [comment]
Checking... did you edit what's in the console, or is that exactly what it said? Because **https://[tanant].** isn't spelled correctly...

**Comment by Dangerous-Mind** [comment]
Still no news about this issue?

**Comment by Dangerous-Mind** [comment]
@andrewconnell  
Since there is no response from the owner can you please reopen my request so that this issue does not die?
Can @VesaJuvonen check it, since he already knows what happened on the previous error?

**Comment by Dangerous-Mind** [comment]
The problem still happening.
