### ISSUE TITLE
Adding custom list to SharePoint framework app - SPFx app

### ISSUE THREAD

**Issue by szulfiqar** [SharePoint/sp-dev-docs#556]
I want to add list, site column, content type etc to a SharePoint framework app using may be yeoman generator or anything else, i know it might be achieved by API calls but i want to add like the way we can add list, columns, content types to SharePoint hosted app by Add->New Item->List etc. Actually i don't want to add the list on run time. Any help ????

**Comment by VesaJuvonen** [comment]
Hi szulfiqar,
we have following resources for this under the SharePoint Framework documentation site and in YouTube channel. 

- Tutorial - https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/provision-sp-assets-from-package
- Additional details - https://dev.office.com/sharepoint/docs/spfx/toolchain/provision-sharepoint-assets
- Webcast - https://www.youtube.com/watch?v=r-UdJhhHlEQ
