### ISSUE TITLE
Using MS Graph to fetch email

### ISSUE THREAD

**Issue by ChristerRussberg** [SharePoint/sp-dev-docs#5560]
I am a beginner of using SPFX but i want to learn.
I have followed the instructions in this example but it does not work OK.
I can add the webpart in a SharePoint page but I get no emails from my inbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642064a1-1971-d88b-6eeb-3bcde4333383
* Version Independent ID: 11fbb2ac-f682-e963-a07a-a28c9cb3d9d8
* Content: [Building SharePoint Framework solutions, which use Microsoft Graph APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-microsoft-graph-apis#feedback)
* Content Source: [docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, thank you for the comment. Can you provide a bit more information about your environment (What version of SharePoint, What Version of SPFx). 

Also if possible, could you provide any errors in your console that may be present in your developer tools when the web part loads? (Access Developer tools by using F12 in your browser)

**Comment by ChristerRussberg** [comment]
Hi

I have just started to learn about SPFx so any help is appreciated.

I use SharePoint Online.
Please see SPFx info below.
![image](https://user-images.githubusercontent.com/53228216/78865680-53c1eb00-7a3e-11ea-96ee-fb5742f82ca0.png)

I get error when using F12. But I am not sure how to correct them.
![image](https://user-images.githubusercontent.com/53228216/78865785-91267880-7a3e-11ea-9cd7-744a8469047b.png)

**Comment by ChristerRussberg** [comment]
Hi

One further notice is that it differs depending on what browser I use.
So far I have only tested in new Edge browser.
But when I use Google Chrome then the values for subject is present.

**Comment by bcameron1231** [comment]
To confirm: You are saying that the Graph Calls when using Edge are not working?

**Comment by ChristerRussberg** [comment]
Hi

The webpart works like this:
I get the email address back but not the subject value.
This is the same in both Microsoft Edge as well in Chrome.

**Comment by bcameron1231** [comment]
It's strange if the email comes back, but not the subject. Sounds like it may be more of a solution issue, than a Graph issue.

Can you share your source to compare to the tutorial?

**Comment by ChristerRussberg** [comment]
Hi, I still have the problem that I only get e-mail address back. The subject field is not returned.

**Comment by bcameron1231** [comment]
Hi, it would be helpful if you could screen shot the requests in Dev Tools (F12) in both Chrome and IE. If you could, provide the Request being sent, and the response coming back in the Network Tab of Dev Tools.

**Comment by TheEagle82** [comment]
Hi, I couldn't see it on my Apps Gallery to add it to my site. Why?
