### ISSUE TITLE
Joining a Team via GraphAPI inside a SPFX webpart leads to corrupt Team membership

### ISSUE THREAD

**Issue by FrankMuraschow** [SharePoint/sp-dev-docs#5561]
## Category

- [x] Bug

## Describe the bug

After joining a Team via [the group members endpoint](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-beta&tabs=javascript) and receiving a  _Response 204 OK_  it is not possible to access the Team or any underlying resources like channels.
[Listing the channels](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&tabs=http) will produce a _403 Unauthorized_ response.

Collaterally the bug causes the Team to not be listed in either the desktop client or the webapp and it is not possible to find the Team via the search / discover page. 
This behavior makes this Team basically invisible / unusable to the user who tried to join it.

The bug was first encountered around February 12th. 
The code was working fine before and broke without any change on our side.

## Steps to reproduce
The behavior can be reproduced with the graph explorer.

- Go to [the graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

- Sign in with an non-admin account

- List all unified groups
````
GET
https://graph.microsoft.com/beta/groups?$filter=groupTypes/any(c:c+eq+'Unified')&$top=999&$select=id,displayname

Response:
Status code should be 200 with group names and ids in the response object
````

- Pick the ID of a group your not a member of yet

- Get your user id
````
GET
https://graph.microsoft.com/beta/me?$select=id

Response:
Status code should be 200 with your id in the response object
````

- Add yourself to the group

````
POST
https://graph.microsoft.com/beta/groups/{groupId}/members/$ref

body
{
"@odata.id": "https://graph.microsoft.com/beta/users/{myId}"
}

Response:
Status code should be 204 with an empty response body
````

- View Team information
````
GET
https://graph.microsoft.com/beta/teams/{groupId}

Response:
Status code 403
Message: Failed to execute Skype backend request GetThreadRequest.
````

- List channels

````
GET
https://graph.microsoft.com/beta/teams/{groupId}/channels

Response:
Status code 403
Message: Failed to execute Skype backend request GetThreadRequest.
````

## Expected behavior
I should be able to see the channels of the Team I just joined.

## Developer environment
- OS: Windows 10
- Framework: Node 10.19.0
- Browser(s): Chromium Edge v80.0.361.109
- Tooling: VS Code 1.43.2, SPFx v1.10.0

### Additional context
Current webApiPermissionRequests
````
{
    "resource": "Microsoft Graph",
    "scope": "Group.ReadWrite.All"
},
{
    "resource": "Microsoft Graph",
    "scope": "GroupMember.ReadWrite.All"
},
{
    "resource": "Microsoft Graph",
    "scope": "User.ReadWrite.All"
},
{
    "resource": "Microsoft Graph",
    "scope": "Directory.Read.All"
}
````

*Thanks for your contribution! Sharing is caring.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 558e6675-990e-b571-6bfb-7392f097edbe
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @FrankMuraschow 

"membership changes made to an Office 365 group backing a team via the Microsoft Graph API or through the admin portal (outside of the Teams client) have to sync to the Teams service in order for newly added users to be able to see and participate in the team.

The current SLA for synchronizing membership changes made to groups to Teams is up to 24 hours after the sync is triggered by client activity. It can take longer under certain circumstances (due to service load, for example)." 

The information was copied from the MS Graph docs, please refer to this [link](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team#how-office-365-group-membership-changes-are-synchronized-to-microsoft-teams) for more information.

I have faced the same delay. However, it is good to have an official statement from Microsoft that we can present to our customers.

I hope it helps to clarify your question.

Regards,
Jarbas Horst

**Comment by andrewconnell** [comment]
This repo is for SharePoint development questions, not Microsoft Graph.

**Comment by andrewconnell** [comment]
@JarbasHorst is correct...

But something strange happened here... this issue was left on the Graph REST API, not the SharePoint docs. This repo is only for SP dev issues... we're suppose to close other issues. I've alerted the Graph team about this...
