### ISSUE TITLE
Need Form View Command Sets

### ISSUE THREAD

**Issue by dilanarandara** [SharePoint/sp-dev-docs#5569]
Could you please provide Display/Edit form view command set examples? Or maybe you can mention about the Location of the command set. ex: `Location="ClientSideExtension.ListViewCommandSet.CommandBar"`

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Thanks for the question. Display/Edit form view command sets don't exist currently. 

The definition for ListViewCommandSet.CommandBar and it's location is provided in that document you provided. Please see [this section](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api#more-details-about-servejson-options).

**Comment by dilanarandara** [comment]
Thank you.
