### ISSUE TITLE
Broken links (404)

### ISSUE THREAD

**Issue by jcoolsen** [SharePoint/sp-dev-docs#5571]
The links for windows installers for node.js 10.19.0 are broken.
(https://nodejs.org/dist/latest-v10.x/node-v10.19.0-x64.msi and https://nodejs.org/dist/latest-v10.x/node-v10.19.0-x86.msi)
Working links are https://nodejs.org/dist/v10.19.0/node-v10.19.0-x64.msi and https://nodejs.org/dist/v10.19.0/node-v10.19.0-x86.msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#feedback)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
Vesa has updated the Node.JS version 10.20.1 - 117e2d3,
Please close the incident

**Comment by andrewconnell** [comment]
@PrasadKasireddy in the future, if you reference issues correctly in the PR submission, it will auto close them.

FWIW, we've moving away from direct links to downloads so we aren't constantly chasing the latest patch version released.
