### ISSUE TITLE
Default properties not working

### ISSUE THREAD

**Issue by mic8989** [SharePoint/sp-dev-docs#5579]
I followed the instruction about the default properties in manifest.json file and recompile it, I didn't see any default value in editing mode of the web part. Why?
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @mic8989 

can you please share with us your HelloWorldWebPart.manifest.json and HelloWorldWebPart.ts files. We need more information in order to help you!

Regards,
Jarbas

**Comment by mic8989** [comment]
Hi Jarbas,
It's working now. I rewrote the code but did not re-compile with gulp serve. That's the reason.Other question I tried to git clone https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angular-greeting with git clone https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/angular-greeting.git but it doesn't work. How can I know the right  .git syntax?
Thanks.

    On Thursday, April 16, 2020, 01:13:29 AM CDT, Jarbas Horst <notifications@github.com> wrote:  
 
 


Hello @mic8989

can you please share with us your HelloWorldWebPart.manifest.json and HelloWorldWebPart.ts files. We need more information in order to help you!

Regards,
Jarbas
