### ISSUE TITLE
What validations are done on "Server notification URL"?

### ISSUE THREAD

**Issue by eszjay** [SharePoint/sp-dev-docs#5581]
I submit my subscribe request and receive back an error that says:
System.InvalidOperationException Failed to validate the notification URL
SharePoint Online does not send a POST request to the "Server notification URL" I sent, so I assume the URL is failing some kind of validation in SharePoint Online, but I cannot find any additional information about the issue. Are additional details about the failures logged somewhere? What validations are done on the URL before POSTing the validationtoken request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6393d95-8c1d-2341-0cbd-282cd7016204
* Version Independent ID: b7506441-6d16-1689-91aa-e9f45a2bb9e0
* Content: [Overview of SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks#feedback)
* Content Source: [docs/apis/webhooks/overview-sharepoint-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/overview-sharepoint-webhooks.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you share the payload of what you sent to the REST API to subscribe? Can't troubleshoot with limited info provided
