### ISSUE TITLE
Sharepoint app cannot see List content

### ISSUE THREAD

**Issue by joeridehing** [SharePoint/sp-dev-docs#5583]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

We've created a SharePoint app, The SharePoint app has FullControl permissions on the tenant and list permissions on the Documents Library in the site. 
The SharePoint app can retreive all Libraries in site with Powershell function: Get-PnPList 
The SharePoint app cannot retreive library content with Powershell function: Get-PnPListItem
What can we do. any thoughts?

## Environment details
 - Framework: Powershell
 - Tooling: VS Code / Azure Automation

**Comment by AdamBilski** [comment]
Hi Joe, are you trying to retrieve library content as in fields or actual documents within library.
With the Get-PnPlistitem you need to tell it what to look for in more details than just Get-ListItem.
If trying to get the Fields following helped me achieve this:

$items = Get-PnPListItem -List $list
$items[0].FieldValues

This will return all of the available columns with their internal names.

Kind Regards,

Adam B.

**Comment by joeridehing** [comment]
Being more specific we use the following:
$items = Get-PnPListItem -List $list -Fields "FileLeafRef", "SMTotalFileStreamSize", "FileDirRef", "FolderChildCount", "ItemChildCount", "GUID", "UniqueId"

The issue is that this list stays empty. When i authenticate with a user instead of the app the content is being shown.

**Comment by AdamBilski** [comment]
Hi Joe,

Right my first though would be that you are using you admin credentials to login to sp-connect that may cause confit of credentials. (may be completely wrong here)
The other one is site app permissions under site setting, you have to make sure to add app permissions there as well. 

Let me know how you get on. 

Ill try to replicate the issue when time allows. 

Regards, 

Adam B

**Comment by joeridehing** [comment]
Hi Adam,

I've given app permissions on the site for the specific list aswell without any improvements. i'm using the spappsecret and spappclientid as authentication tokens. That way i'm sure that i'm connected with the correct credentials.

**Comment by OS-Lee** [comment]
Hi,

I did sample test based on existing add-in(app) while not reproduced.

My test steps:

![image](https://user-images.githubusercontent.com/40845109/79521527-f9eba180-808b-11ea-8e73-abde05b0fb34.png)

Script from local PowerShell(not host in Azure).

![image](https://user-images.githubusercontent.com/40845109/79521644-40d99700-808c-11ea-80f6-fe154eeca29a.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by joeridehing** [comment]
Hello Lee,

First results look promising. 
We had 2 issues it seems. 
- We were using the Adminurl instead of the siteurl
- We were using a wrong translated library name

Thanks for the assistence. Will let you know on monday for the results.

**Comment by andrewconnell** [comment]
You might want to try posting this to the PNP PowerShell project instead of the general SharePoint developer repo...

**Comment by joeridehing** [comment]
Case closed. Issue solved :)
