### ISSUE TITLE
Failed to enumerate DefaultDocument from DocumentSetTemplate.DefaultDocuments

### ISSUE THREAD

**Issue by anbeel** [SharePoint/sp-dev-docs#5584]
## Category

- [x] Bug

## Describe the bug

Microsoft.SharePoint.Client.DocumentManagement.Portable.dll

We are using this code:
using Microsoft.SharePoint.Client.DocumentSet;
var documentSetSetting = DocumentSetTemplate.GetDocumentSetTemplate(clientContext, spContentType);
clientContext.Load(documentSetSetting, x => x.AllowedContentTypes, x => x.DefaultDocuments, x => x.SharedFields, x => x.WelcomePageFields);
await clientContext.ExecuteQueryAsync()
				
foreach (var doc in documentSetSetting.DefaultDocuments)   //error from here
{
	....
}
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'Microsoft.SharePoint.Client.DocumentSet.DefaultDocument'.
[4/16/2020 7:05:36 AM]    at Microsoft.SharePoint.Client.ClientObjectCollection`1.GetEnumerator()+MoveNext()

## Developer environment

- OS: [e.g. Windows 10]
- Framework: [e.g. .NET Core v2.0
- Tooling: [e.g. Visual Studio 2019]

**Comment by Jerry0527** [comment]
Are you using .NET Core with CSOM ?

Per my undertstanding, .NET Core CSOM library has not been released officially.

I tested the code snippet below in normal .NET Framework Console Application, it's working in foreach loop:

```
  using (ClientContext ctx = new ClientContext("https://xxx.sharepoint.com/sites/dev/"))
            {

                ctx.Credentials = new SharePointOnlineCredentials(account, secret);
                ctx.Load(ctx.Web);
                ctx.ExecuteQuery();
                
                List targetList = ctx.Web.Lists.GetByTitle("Documents");
                ContentType ct = targetList.ContentTypes.GetById("0x0120D52000942D80A6EEAA9640B7E28C930278C75900D84B2EEE308E4745ACB92B6C4BF90766");
                ctx.Load(targetList.ContentTypes);
                ctx.Load(ct);
                ctx.ExecuteQuery();
                var documentSetSetting = DocumentSetTemplate.GetDocumentSetTemplate(ctx, ct);
                ctx.Load(documentSetSetting, x => x.AllowedContentTypes, x => x.DefaultDocuments, x => x.SharedFields, x => x.WelcomePageFields);
                ctx.ExecuteQuery();
                foreach (DefaultDocument doc in documentSetSetting.DefaultDocuments)
                {
                    Console.WriteLine(doc.Name);
                }   
}
```
![2020-04-16_175103](https://user-images.githubusercontent.com/28797671/79442283-ed733480-800a-11ea-8f69-efa233e6db15.png)

**Comment by anbeel** [comment]
Thank you for the quick response, it works indeed in .NET framework.
However, our code run in Azure Function with .Net Core. We add reference for Dlls with latest version 16.1.19814.12000 from NuGet under the folder '.nuget\packages\microsoft.sharepointonline.csom\16.1.19814.12000\lib\netcore45'

**Comment by andrewconnell** [comment]
.NET Core isn't yet supported by CSOM. Not sure how you got those references. Not surprising it doesn't work, but it's still an open item on User Voice as of early April 2020:

https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/16585795-support-net-core-with-csom
