### ISSUE TITLE
Import Migration API overwrite strategy.

### ISSUE THREAD

**Issue by anbeel** [SharePoint/sp-dev-docs#5585]
## Category
- [x ] Question

## Question
It works well to create new document set with properties using the API.
However, we want to overwrite some properties of the same document set. The API doesn't work.
How does the API identify the document set properties changes?

**Comment by andrewconnell** [comment]
The issue template that was created when you created this issue had sections for content that you should have filled out. That context detail help us quite a bit. Please provide additional detail... environment, target, etc.

**Comment by anbeel** [comment]
The core code is invoke 'site.CreateMigrationJob' method.
I confirm this issue is caused by different uniqueId in manifest.xml file. The API realize this is new document set. But failed to create because the same name document set is existing. If I give the correct uniqueId for existing document set its properties can be changed correctly.
