### ISSUE TITLE
cannot apply row formatting based on lookup column value

### ISSUE THREAD

**Issue by miguelrrsantos** [SharePoint/sp-dev-docs#5586]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hi there. 

I'm trying to apply rows conditional formatting based on a Status column value. However, in the rules this column do not appear, i think it's because a lookup value. I tryed advanced mode and write my own json code but i can't make it display anything... it seems it's invalid.

A litle example:

{
  "additionalRowClass": {
    "operator": ":",
    "operands": [
      {
        "operator": "==",
        "operands": [
          {
            "operator": "toLowerCase",
            "operands": [
              "[$Status]"
            ]
          },
          {
            "operator": "toLowerCase",
            "operands": [
              "Closed"
            ]
          }
        ]
      },
      "sp-css-backgroundColor-successBackground50",
      "sp-css-backgroundColor-neutralBackground"
    ]
  }
}

It's not possible to do formatting based on lookup values?

## Environment details (if applicable)

I'm using sharepoint online with moder page.

- OS: Any
- Framework: Online
- Browser(s): Any
- Tooling: None

**Comment by bcameron1231** [comment]
Lookups are supported in view formatting.

Lookups are complex field types though, and represented as objects. This is outlined in the column formatting docs [here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#display-field-values-basic).

In your example you'd get access the value by doing [$Status.lookupValue]
