### ISSUE TITLE
Deployment from app catalog to site collection: "An unexpected error has occurred"

### ISSUE THREAD

**Issue by kruegernet** [SharePoint/sp-dev-docs#5587]
## Category

- [x] Bug

## Describe the bug

Attempting to deploy bcameron1231's module from https://github.com/bcameron1231/SharePoint-Framework/tree/master/react-hubsite-securitytrim-navbar, During deployment from App Catalog, receive:

"Sorry, something went wrong
An unexpected error has occurred.
Technical Details
Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: 4a64499f-10e8-b000-0c6a-7ac518357843
Date and Time: 4/16/2020 10:44:49 AM"

## Steps to reproduce

1. Download https://github.com/bcameron1231/SharePoint-Framework/tree/master/react-hubsite-securitytrim-navbar
2. Build and deploy per instructions on README.md, to include CDN hosting and proper bundling and packaging of sppkg
3. Encounter error

## Expected behavior

App deploys to site collection successfully.

## Developer environment

- OS: Win 10 Pro x64 2004
- Framework: React / TypeScript, node 12
- Browsers: Chrome v80, Firefox Developer 76.0b5
- Tooling: VS Code

### Additional context

App Catalog is about 48 hours old by now. I have no issues building this app and running it from the local dev server for CDN against a live tenant sharepoint site within the target hub.

**Comment by andrewconnell** [comment]
Node 12 isn't supported with SPFx... not sure if that's related. As it's a custom solution provided by someone else, suggest you submit the issue to their REPO.
