### ISSUE TITLE
SPFx localization doc

### ISSUE THREAD

**Issue by ypcode** [SharePoint/sp-dev-docs#559]
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x] Enhancement / Suggestion
- [ ] Additional article idea

#### Observed Behavior
Just to notify that some of the code samples are outdated [here](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/localize-web-parts)

lines 72 and 684
```
  protected get propertyPaneSettings(): IPropertyPaneSettings {
    return {
      pages: [
...
```
instead of 
` protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {`

in current release

Cheers
Yannick

**Comment by manishgarg1** [comment]
@ypcode, thanx for the notification. Looks like this is resolved now. Please close the issue if you agree.

**Comment by ypcode** [comment]
With pleasure :)
