### ISSUE TITLE
I am getting JavaScript heap out of memmory

### ISSUE THREAD

**Issue by lovyjain** [SharePoint/sp-dev-docs#5591]
## Category
SPFx testign using Gulp serve

- [x] Bug
I am getting the fatal error when running gulp serve

<--- Last few GCs --->

[25532:00000246AF349B70]   171164 ms: Scavenge 1381.5 (1422.2) -> 1380.8 (1422.7) MB, 1.9 / 0.0 ms  (average mu = 0.102, current mu = 0.066) allocation failure
[25532:00000246AF349B70]   171167 ms: Scavenge 1381.6 (1422.7) -> 1380.9 (1423.2) MB, 1.8 / 0.0 ms  (average mu = 0.102, current mu = 0.066) allocation failure
[25532:00000246AF349B70]   171170 ms: Scavenge 1381.7 (1423.2) -> 1381.0 (1423.7) MB, 1.9 / 0.0 ms  (average mu = 0.102, current mu = 0.066) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000034C48B5C5C1]
Security context: 0x0177fd59e6e9 <JSObject>
\node_modules\bluebird\js\release\promise.js:~143] [pc=0000034C493C046E](this=0x00da0a81efc1 <Promise map = 0000038847AF3B69>,didFulfill=0x00da0a81f001 <JSFunction then (sfi = 000002948BD952A9)>,didReject=0x01472df826f1 ...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF629C0C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF629BE7416 node::MakeCallback+4534
 3: 00007FF629BE7D90 node_module_register+2032
 4: 00007FF629F0189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF629F017CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF62A0E7F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF62A0DEF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF62A0DD5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF62A0E6317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF62A0E6396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF62A210637 v8::internal::Factory::NewFillerObject+55
12: 00007FF62A28D826 v8::internal::operator<<+73494
13: 0000034C48B5C5C1

## Describe the bug
When i run gulp serve it gives me the error, 
## Steps to reproduce
gulp serve
## Expected behavior
it should succesfully run it.

## Developer environment
SPFX generator -1.9.1

Window

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
That was a known issue with SPFx projects pre-dating 1.8.2. See the release notes for 1.8.2: https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8.2-release-notes

Check the version of the project (package versions in **package.json**)... you've got the generator version listed in your OP... that's not going to be related to the project once it's created.

**Comment by lovyjain** [comment]
My package json file reads as 

{
  "name": "fillform",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "bundle": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@material-ui/core": "^4.9.2",
    "@microsoft/decorators": "1.9.1",
    "@microsoft/sp-application-base": "1.9.1",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-dialog": "1.9.1",
    "@microsoft/sp-http": "^1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^1.3.6",
    "@pnp/logging": "^1.3.6",
    "@pnp/odata": "^1.3.6",
    "@pnp/polyfill-ie11": "^2.0.1",
    "@pnp/sp": "^1.3.6",
    "@pnp/spfx-controls-react": "1.15.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.31",
    "@types/webpack-env": "1.13.1",
    "@types/yup": "^0.26.30",
    "@yazanaabed/react-tabs": "^2.3.6",
    "bootstrap": "^4.4.1",
    "chartjs-plugin-labels": "^1.1.0",
    "formik": "^2.1.4",
    "html5sortable": "^0.9.17",
    "immutability-helper": "^2.9.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "office-ui-fabric-react": "6.189.2",
    "popper.js": "^1.16.0",
    "react-chart-tooltip": "^0.1.2",
    "react-chartjs-2": "^2.8.0",
    "react-contenteditable": "^3.3.3",
    "react-responsive-carousel": "^3.1.51",
    "react-tabs": "^3.1.0",
    "react-tooltip": "^3.11.2",
    "yup": "^0.28.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "webpack-bundle-analyzer": "^3.6.0",
    "@types/moment-timezone": "^0.5.12"
  }
}


I know a lot of but hope it helps as i see here/ Project is using 1.9.1
And this is my Version overall

+-- @microsoft/generator-sharepoint@1.9.1
+-- component@1.1.0
+-- gulp@4.0.2
+-- power-library-component@0.0.1 -> 
+--`-- yo@3.1.0

**Comment by andrewconnell** [comment]
No... the project is 1.10... your generator is v1.9.1 (that's only used to create a project). Look at your **package.json**... all the SPFx packages are v1.10.

But... need more context. You deleted a lot of the prompts for the context section in the original post.

**Comment by lovyjain** [comment]
Oh My bad.. As workig with others some may have used this version and while fetching got this.
THis is my gulpserve response
----------------
Build target: DEBUG
[10:02:19] Using gulpfile D:\DailyWork\Code\SharePoint\.SP.Online\AppCatalog\SPFx\Webparts\XjtWidgets\gulpfile.js
[10:02:19] Starting gulp
[10:02:19] Starting 'serve'...
[10:02:19] Starting subtask 'configure-sp-build-rig'...
[10:02:19] Finished subtask 'configure-sp-build-rig' after 6.28 ms
[10:02:19] Starting subtask 'spfx-serve'...
[10:02:19] [spfx-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
[10:02:19] Starting server...
Starting api server on port 5432.
Registring api: /workbench
Registring api: */*
[10:02:19] Finished subtask 'spfx-serve' after 360 ms
[10:02:20] Starting subtask 'pre-copy'...
[10:02:20] Finished subtask 'pre-copy' after 27 ms
[10:02:20] Starting subtask 'copy-static-assets'...
[10:02:20] Starting subtask 'sass'...
[10:02:20] Server started https://localhost:4321
[10:02:20] LiveReload started on port 35729
[10:02:20] Running server
[10:02:20] Opening https://localhost:5432/workbench using the default OS app
  Request: [::1] '/workbench'
  Request: '/temp/workbench.html'
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
[10:02:21] Warning - [sass] src\webparts\photoOfWeek\components\Comments\Comments.scss: filename should end with module.sass or module.scss
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[10:02:21] Warning - [sass] The local CSS class 'table-striped' is not camelCase and will not be type-safe.
  Request: '/node_modules/@microsoft/sp-dialog/node_modules/@microsoft/sp-property-pane/dist/sp-property-pane_en-us.js'
[10:02:21] Warning - [sass] The local CSS class 'nav-tabs' is not camelCase and will not be type-safe.
[10:02:21] Warning - [sass] The local CSS class 'nav-link' is not camelCase and will not be type-safe.
[10:02:22] Finished subtask 'copy-static-assets' after 2.65 s
[10:02:23] Finished subtask 'sass' after 3.42 s
[10:02:23] Starting subtask 'tslint'...
[10:02:24] [tslint] tslint version: 5.12.1
[10:02:24] Starting subtask 'tsc'...
[10:02:24] [tsc] typescript version: 2.9.2
  Request: '/temp/manifests.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
[10:02:35] Finished subtask 'tsc' after 11 s
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/temp/manifests.js'
[10:02:43] Warning - tslint - src\webparts\xjtperformance\components\CompetitorComparisons.tsx(58,22): error no-use-before-declare: variable 'RenderRow' used before declaration
[10:02:43] Finished subtask 'tslint' after 20 s
[10:02:43] Starting subtask 'post-copy'...
[10:02:43] Finished subtask 'post-copy' after 682 μs
[10:02:43] Starting subtask 'collectLocalizedResources'...
[10:02:43] Finished subtask 'collectLocalizedResources' after 12 ms
[10:02:43] Starting subtask 'configure-webpack'...
[10:02:47] Finished subtask 'configure-webpack' after 3.71 s
[10:02:47] Starting subtask 'webpack'...
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifestsFile.js.map'
  Request: '/dist/commodities-dashboard-webpart-web-part.js.map'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifestsFile.js.map'
  Request: '/dist/commodities-dashboard-webpart-web-part.js.map'
[10:06:23] Finished subtask 'webpack' after 3.58 min
[10:06:23] Starting subtask 'configure-webpack-external-bundling'...
[10:06:23] Finished subtask 'configure-webpack-external-bundling' after 2.36 ms
[10:06:23] Starting subtask 'copy-assets'...
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
[10:06:28] Finished subtask 'copy-assets' after 5.18 s
[10:06:28] Starting subtask 'write-manifests'...
[10:06:33] Finished subtask 'write-manifests' after 5.32 s
[10:06:33] Starting subtask 'reload'...
[10:06:33] Finished subtask 'reload' after 2.07 ms
[10:06:33] Starting subtask 'pre-copy'...
[10:06:33] Finished subtask 'pre-copy' after 793 μs
[10:06:33] Starting subtask 'copy-static-assets'...
[10:06:33] Starting subtask 'sass'...
  Request: '/temp/workbench.html'
  Request: '/temp/manifests.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js'
  Request: '/temp/workbench-packages/@microsoft_sp-webpart-workbench/lib/api/workbenchInit.js'
  Request: '/node_modules/@microsoft/sp-dialog/node_modules/@microsoft/sp-property-pane/dist/sp-property-pane_en-us.js'
[10:06:35] Warning - [sass] src\webparts\photoOfWeek\components\Comments\Comments.scss: filename should end with module.sass or module.scss
[10:06:35] Warning - [sass] The local CSS class 'table-striped' is not camelCase and will not be type-safe.
[10:06:37] Warning - [sass] The local CSS class 'nav-tabs' is not camelCase and will not be type-safe.
[10:06:37] Warning - [sass] The local CSS class 'nav-link' is not camelCase and will not be type-safe.
  Request: '/temp/manifests.js'
[10:06:38] Finished subtask 'sass' after 4.97 s
[10:06:38] Starting subtask 'tslint'...
[10:06:38] [tslint] tslint version: 5.12.1
[10:06:38] Starting subtask 'tsc'...
[10:06:38] [tsc] typescript version: 2.9.2
[10:06:38] Finished subtask 'copy-static-assets' after 5.17 s
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/temp/manifests.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/lib/webparts/commoditiesDashboard/loc/en-us.js'
  Request: '/node_modules/jquery/dist/jquery.min.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/commodities-dashboard-webpart-web-part.js'
  Request: '/dist/img_lightcrude_84efbdc30a274992fae08029d2247171.png'
  Request: '/dist/img_time_42846de0b74315cf0ceb4eb6c6e8643f.png'
  Request: '/dist/editpencil_dca9c87c931f1765028847e3babee572.png'
  Request: '/temp/manifestsFile.js.map'
  Request: '/dist/commodities-dashboard-webpart-web-part.js.map'
[10:07:10] Finished subtask 'tsc' after 32 s
[10:07:11] Warning - tslint - src\webparts\xjtperformance\components\CompetitorComparisons.tsx(58,22): error no-use-before-declare: variable 'RenderRow' used before declaration
[10:07:11] Finished subtask 'tslint' after 33 s
[10:07:11] Starting subtask 'post-copy'...
[10:07:11] Finished subtask 'post-copy' after 2.34 ms
[10:07:11] Starting subtask 'collectLocalizedResources'...
[10:07:12] Finished subtask 'collectLocalizedResources' after 243 ms
[10:07:12] Starting subtask 'configure-webpack'...
[10:07:12] Finished subtask 'configure-webpack' after 1.99 ms
[10:07:12] Starting subtask 'webpack'...

<--- Last few GCs --->

[3404:000001F560B6A220]   353791 ms: Mark-sweep 1354.3 (1416.4) -> 1354.3 (1413.4) MB, 255.0 / 0.0 ms  (average mu = 0.161, current mu = 0.000) last resort GC in old space requested
[3404:000001F560B6A220]   354029 ms: Mark-sweep 1354.3 (1413.4) -> 1354.3 (1413.4) MB, 237.7 / 0.0 ms  (average mu = 0.087, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000009863C079E0]
Security context: 0x0344a539e6e9 <JSObject>
    1: fromString(aka fromString) [000001E435D13251] [buffer.js:~334] [pc=0000009864EC3E60](this=0x0316967826f1 <undefined>,string=0x0148f2de11c1 <Very long string[4747718]>,encoding=0x0316967826f1 <undefined>)
    2: get gzipSize [0000003AA12D22B9] [D:\DailyWork\Code\SharePoint\SP.Online\AppCatalog\SPFx\Webparts\XjtWidgets\node_module...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF737A8C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF737A67416 node::MakeCallback+4534
 3: 00007FF737A67D90 node_module_register+2032
 4: 00007FF737D8189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF737D817CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF737F67F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF737F6645B v8::internal::Heap::MaxHeapGrowingFactor+2651
 8: 00007FF7380902BB v8::internal::Factory::AllocateRawWithImmortalMap+59
 9: 00007FF738092D6D v8::internal::Factory::NewRawTwoByteString+77
10: 00007FF737DDDDA8 v8::internal::Smi::SmiPrint+536
11: 00007FF737D74EAB v8::internal::StringHasher::UpdateIndex+219
12: 00007FF737D9A2C6 v8::String::Utf8Length+22
13: 00007FF737A507AC node::Buffer::New+4332
14: 0000009863C079E0
-----
So does that means it is an issue of Version mismatch. as some of the packages still using 1.9.1 in my project.?

**Comment by andrewconnell** [comment]
First, you haven't provided enough context as requested in my last reply. Pasting another console output from Gulp isn't context. This is what the default template included that contains questions to which your answers could help. Please, FILL IT OUT:

## Developer environment

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- OS: [e.g. Windows 10, MacOS 10.15.x]
- Framework: [e.g. .NET Framework v3.x, .NET Core v3.x, Node.js v6/v8/v10/v12]
- Browser(s): [e.g. Chrome v79, Safari v22, FireFox v31, IE v11, Edge, Chromium Edge v79]
- Tooling: [e.g. VS Code, SPFx v1.10.0, Visual Studio 2019] 

Second, you shouldn't mix SPFx versions. In your package.json, I see references to both 1.9.1 & 1.10.0 SPFx packages. I don't know if that's the root of the problem, but that should be fixed.

Third, you've added a lot of references to the project… are you having the same issue with the default project? Are you externalizing libraries? I see references to React controls, moment (which is huge), jQuery, etc… could be running out of memory if all those things are going in the bundle

**Comment by lovyjain** [comment]
Please refer the context:

OS:Windows 10
Framework: Node - v10.16.0, .Net framework 4.6.2, .Net core 2.2
Browser(s): Google Chrome
Tooling: Vs Code, Spfx 1.9.1 globally and in project (1.9.1 and 1.10)

No i am having issues with this project only. And from some time only.

Yes i am having a lot of references as number of webparts are also around 12 and i am using separate component for each webpart.
Yes i am using some libraries as external. And after deploying  it runs fine, the problem is with testing only.

 "externals": {
    "moment": "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js",
    "myLibrary": "https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.27/moment-timezone.min.js",
    "jquery": {
      "path": "node_modules/jquery/dist/jquery.min.js",
      "globalName": "jquery"
    },
    "vTicker": {
      "path": "./src/plugins/js/jquery.vticker.min.js",
      "globalName": "jquery",
      "globalDependencies": [
        "jquery"
      ]
    }
  },

**Comment by andrewconnell** [comment]
@lovyjain said:
> Tooling: Vs Code, Spfx 1.9.1 globally and in project (1.9.1 and 1.10)

See my last comment... you can't mix SPFx package versions in your project like your **package.json** shows.

@lovyjain said:
> Yes i am using some libraries as external. 

While you have some externals (4 by my count), there's a LOT more in your **package.json**... OUIFR, multiple react components and many more. I have to believe that's a huge bundle... and I bet that's the root of your issue.

@lovyjain said:
> And after deploying it runs fine, the problem is with testing only.

So it's just **gulp serve** when you see the issue? Then that sounds like it's an issue building/bundling/serving a huge unminified bundle.

Not sure what we can do here... this is a huge project (12 components) with a lot of external dependencies. If it works with a default project, then I'd suggest one or multiple of the following: (1) break out components to different projects so one project isn't so big, (2) externalize the resources you're pulling out

**Comment by andrewconnell** [comment]
In addition, this has come up before... see this comment on how to increase the memory allocated to Node on your machine: https://github.com/SharePoint/sp-dev-docs/issues/3679#issuecomment-478164539
