### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by masterbasser007** [SharePoint/sp-dev-docs#5592]
fails every single time. followed the examples verbatim and it fails on the json config every single time. What's the deal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5a35c2-9914-fc67-1550-15d4f63c918c
* Version Independent ID: 8418c398-1a93-622d-4df8-84c866fef67f
* Content: [Add jQueryUI Accordion to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part#feedback)
* Content Source: [docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by hubbardw** [comment]
Works for me.

**Comment by masterbasser007** [comment]
I'm sure it's me, thanks that makes me feel better, so I'll revist my code
some more

**Comment by andrewconnell** [comment]
Unfortunately, you have given us much to work with. Without sharing code, context or screenshots, there's nothing we can do. Please feel free to resubmit your comment with additional details.
