### ISSUE TITLE
Filter using true/false string on boolean list column results in opposite behavior

### ISSUE THREAD

**Issue by mcqueene** [SharePoint/sp-dev-docs#5594]
## Category

- [x] Bug

## Describe the bug
Similar to #4750 when using a filter on a SharePoint list that has true/false values, if you try to filter on true/false literally it has the opposite results.

## Steps to reproduce
Using syntax GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items on a list that has a boolean field try to filter using the string true or false. For example, if the column is called "IsActive" this filter query should reproduce the problem. items?expand=fields($select=Title,isActive)&$filter=fields/IsActive eq 'true'

## Expected behavior
Given the filter on "true" you would expect only the items with the boolean "true". What happens is actually the opposite. The results you will get will be the items that have "false".

### Additional context
Please note that you can work around this by avoiding using true/false and instead use the binary 0 or 1 as below.
items?expand=fields($select=Title,isActive)&$filter=fields/IsActive eq 1

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
@mcqueene said:
> Please note that you can work around this by avoiding using true/false and instead use the binary 0 or 1 as below. `items?expand=fields($select=Title,isActive)&$filter=fields/IsActive eq 1`

Did you see my comment in the issue you referenced? It explains why this is expected...
