### ISSUE TITLE
Difference between using appregnew.aspx from site and admin

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5595]
What will be difference using appregnew.aspx page with below two URLs

https://[yourtenant].sharepoint.com/_layouts/15/appregnew.aspx
https://[yourtenant]-admin.sharepoint.com/_layouts/15/appregnew.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning#set-up-app-only-access-to-your-tenant)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
No difference. You can use the AppRegNew.aspx page from any site within the tenancy. More information can be found in the [Add-In Registration Documentation](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins).
