### ISSUE TITLE
The link to  Office UI Fabric doesn't work

### ISSUE THREAD

**Issue by mariolonghi** [SharePoint/sp-dev-docs#5597]
Anywhere this is mentioned, the link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sathiya-io** [comment]
I hope recently DEV domain name changed from 'dev.office.com' to 'developer.office.com', which can be managed from MS IT team.  Possibly you can access the resources over https://dev.office.com/fabric#/.

**Comment by sathiya-io** [comment]
update: https://developer.microsoft.com/en-us/fluentui#
