### ISSUE TITLE
Get started with Power Automate and SharePoint - "404 - Page not found"

### ISSUE THREAD

**Issue by ofuen** [SharePoint/sp-dev-docs#5599]
"Get started with Power Automate and SharePoint" link is broken. Just wanted to report it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e427d1-8493-5610-8bcf-0ceab91ba540
* Version Independent ID: ebfa7a4a-6e37-7f6d-e9bf-a0750f36f745
* Content: [Business apps and business process automation](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/introduction-to-sharepoint-business-process-integration#feedback)
* Content Source: [docs/business-apps/introduction-to-sharepoint-business-process-integration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/introduction-to-sharepoint-business-process-integration.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @ofuen 

if I click on the reported link, I end up here: https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your%20first-flow

What page exact do you see?

Regards
Jarbas

**Comment by ofuen** [comment]
Hi @JarbasHorst 

I was seeing "**404 - Page not found**" yesterday. It seems the link is working now. Thank you!
