### ISSUE TITLE
Instructions for creating Storage account name, Blob Container Name and Storage Account Access Key not clear

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-docs#56]
Hi
In Tutorial4 -  Instructions for creating Storage account name, Blob Container Name and Storage Account Access Key are not clear. They just point to a generic set of instructions.  eg Blob Container Name - what sort of access type to the BLOB Container is required ? Private, Container or BLOB ?

Also Path to CDN - is this a url ? if so what sort of url ? - an example would be useful here.

This is frustrating for those of use who are not very familiar with AZURE.  (Yes, I can create VMs and Networks etc in Azure and deploy SharePoint into those VMs.)

Regards

Nigel

**Comment by patmill** [comment]
Chaks - is this something you can update in the tutorial to make it clearer?

**Comment by chakkaradeep** [comment]
@NPrice99 I have updated the tutorials with more [detailed steps](https://github.com/SharePoint/sp-dev-docs/wiki/HelloWorld,-Deploy-to-CDN). Please let us know if that works.

**Comment by NPrice99** [comment]
Hi Chakkaradeep.
That works fine !
Thanks
Nigel
