### ISSUE TITLE
SPFX upgrade using Office 365CLi

### ISSUE THREAD

**Issue by lovyjain** [SharePoint/sp-dev-docs#5600]
This command runs like Super Duper fast!!
spfx project upgrade --toVersion 1.5.0 --output md --outputFile "upgrade-report.md"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c43fab8f-85bf-e577-317b-a71dada5c865
* Version Independent ID: 4d041f90-2cc7-ed20-c007-d2a36f9c7c7b
* Content: [Update SharePoint Framework packages](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages)
* Content Source: [docs/spfx/toolchain/update-latest-packages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/update-latest-packages.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi there!

Is there a specific question that you have regarding Office 365 CLI?

**Comment by lovyjain** [comment]
No Thank, that was a feedback .. I put it in issues instead..

**Comment by waldekmastykarz** [comment]
Appreciate the kind words! If there is ever anything we could help it, don’t hesitate to reach out. Have a great day!

**Comment by VelinGeorgiev** [comment]
Thank you very much @lovyjain !  You rock! :)
