### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Ib01** [SharePoint/sp-dev-docs#5602]
AFter days of banging my head against the wall. Followed the instructions to the letter but It SIMPLY DOES NOT WORK.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-au/sharepoint/dev/spfx/use-aad-tutorial#feedback)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
Please provide with the issues you are facing while following the steps to help you better.

**Comment by andrewconnell** [comment]
Unfortunately, you haven't provided enough information to assist. Without some context, repro steps, screen captures, code, errors, etc... , there's not much we can do to help you.

**Comment by plamber** [comment]
@andrewconnell 

I had the same issue today.

In a nutshell, the current example uses components that are not more working for the latest fabric and SPx version. For example, autobind is a deprecated component. I just upgraded the solution and created a pull [request](https://github.com/SharePoint/sp-dev-fx-webparts/pull/1264). 

If you want, I can go and update also the documentation to reflect the new changes.

**Comment by andrewconnell** [comment]
Always interested in contributions on the docs if there are issues. 

What I suggest is creating a NEW issue on this doc as the OP is not responding and this will eventually get closed without their response. In the new issue, explain what's wrong and what needs to be fixed. Feel free to submit a PR against the doc and we'll review & merge it if helps!
