### ISSUE TITLE
Cannot read property 'tostring' of null after giving command "gulp-trust-dev-cert"

### ISSUE THREAD

**Issue by Pratikshabb** [SharePoint/sp-dev-docs#5607]
![img](https://user-images.githubusercontent.com/47237880/79722810-5c4dd780-8302-11ea-9efc-9f4e298d17ca.png)

**Comment by andrewconnell** [comment]
Unfortunately, you haven't provided enough information to assist. Without some context, repro steps, screen captures, code, errors, etc... , there's not much we can do to help you.
