### ISSUE TITLE
Add-In permission at List level

### ISSUE THREAD

**Issue by anoopkv39** [SharePoint/sp-dev-docs#5610]
Can it be done via PowerShell to grant permission at site level, web level or list level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be8c8d6-7ed2-1907-3038-49d8e1c92e8a
* Version Independent ID: a2adbe13-e625-3995-fded-fce6c4a701ac
* Content: [Register SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins#feedback)
* Content Source: [docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/register-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unfortunately no, permissions are applied at the site collection level.

**Comment by anoopkv39** [comment]
@andrewconnell As per this article https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint; SharePoint add-in permission scope can be set to a List through UI. So, permission can be applied at list level as well?? Can we do it via PowerShell?

![image](https://user-images.githubusercontent.com/64012522/79806450-ca9aa480-83ab-11ea-8c84-669268b4c8b3.png)

**Comment by Jerry0527** [comment]
In On-Premise environment, appinv.aspx can be set with Set-SPAppPrincipalPermission"
[set a SharePoint-hosted app's permissions via PowerShell](https://stackoverflow.com/questions/25246144/how-do-i-set-a-sharepoint-hosted-apps-permissions-via-powershell)
But for SharePoint Online, there is no PowerShell equal with it, please check the similiar question here:
[Set-SPAppPrincipalPermission equivalent in SharePoint Online](https://sharepoint.stackexchange.com/questions/233878/set-spappprincipalpermission-equivalent-in-sharepoint-online)
