### ISSUE TITLE
AverageRating in List View Formatting

### ISSUE THREAD

**Issue by naveen9026** [SharePoint/sp-dev-docs#5617]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am not able to read [$AverageRating] in format list view. May I know how to present, rating feature in Tile view or custom format view.

**Comment by bcameron1231** [comment]
Hi, this is a good question. It looks like the AverageRating field does populate with data to be used with Column Formatting. 
![image](https://user-images.githubusercontent.com/7944457/79873204-0af62480-83a4-11ea-807e-5fde9e24a26f.png)

However, when you try to select on it, it doesn't return "3", it just returns empty. To be fair, I'm not sure if this is a bug or if Ratings aren't officially supported in JSON Column Formatting. We'll need to investigate.
