### ISSUE TITLE
Error with localized strings at library components

### ISSUE THREAD

**Issue by mfdezvil** [SharePoint/sp-dev-docs#5623]
## Category

- [x] Bug

## Describe the bug

I'm working on a SPFX's library component that has a component and localized strings used in that component. When I link library component with a webpart and I test it in workbench, webpart shows an error about cannot find module of localized strings:

[SPLoaderError.loadComponentError]:
***Failed to load component "XXX" (MyWebPart). 
Original error: ***Failed to load entry point from component "XXX" (MyWebPart). Original error: Error loading https://component-id.invalid/XXX.0.1
Cannot find module 'ComponentLibraryStrings'

## Steps to reproduce

1. Create a library component connected to a webpart following these steps: [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial)

2. Create a new string in files "mystrings.d.ts" and "en-us.js", and use it in a component/class of the library component.

3. Call component/class from linked webpart, and test it in workbench. Error shows at loading webpart.

## Expected behavior

When I link library component with a webpart and I test it in workbench, webpart should show my component with translated literals, as a normal webpart. 

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: SPFX 1.10
- **Browser(s)**: Google Chrome, IE, all of them.
- **Tooling**: VS Code

### Additional context

I don't know if this is a bug or I'm missing something in my code, but I follow steps of the Library Component tutorial, and my code cannot be more simple, so I don't know what I missing of localized strings and I think this might be a bug, or maybe there are missing steps in tutorial. Thank you for your attention.

**Comment by Macro21** [comment]
Same error....
![image](https://user-images.githubusercontent.com/24574303/80095862-ee571980-8568-11ea-86fc-3165776c204a.png)
If i quit this line in the library project, all work properly: (So traduction strings not working)
![image](https://user-images.githubusercontent.com/24574303/80095980-265e5c80-8569-11ea-8b18-23cec63f91a2.png)

**Comment by bcameron1231** [comment]
Hi, can you confirm you used npm link to connect your library componenet?

**Comment by Macro21** [comment]
yes. With one library works. I did this:

- Root folder
     -Folder with library code
     -Folder with extension code

1. In the library folder:
     -npm link
     -import strings and make console.log(importedStringName)
     -gulp

2.In the extension folder:
     -Add the dependence in package.json
     -npm link nameLibrary (in the library folder package.json)
     -gulp serve (and error making gulp serve)

If i delete one of two librarys all works.

**Comment by Macro21** [comment]
¿any update? :)

**Comment by lukju** [comment]
any updates on this? error / bug is still present in SPFx 1.12...

**Comment by AJIXuMuK** [comment]
Hello @mfdezvil - sorry for the long delay.

As with any other SPFx solution, you need to "register" strings from your library component in the web part in `config\config.json` file:
```
"localizedResources": {
    "ComponentWebPartWebPartStrings": "lib/webparts/componentWebPart/loc/{locale}.js",
    "ComponentLibraryLibraryStrings": "node_modules/lib/lib/libraries/componentLibrary/loc/{locale}.js"
  }
```
here the second registration is for library component's strings. Same approach is used, for example, by [PnP React Controls](https://pnp.github.io/sp-dev-fx-controls-react/#configuration).

I'm also attaching the sample that contains the correct configuration.
[lib-component.zip](https://github.com/SharePoint/sp-dev-docs/files/7529638/lib-component.zip)
