### ISSUE TITLE
Retrieve file details related to the change

### ISSUE THREAD

**Issue by madhavsankar** [SharePoint/sp-dev-docs#5624]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

As per https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation

After retrieving the changes in change List and getting its ID, how to retrieve other details pertaining to the file. Like if the file was added, can we get the file name?

**Comment by bcameron1231** [comment]
The Call to get the changes should return you the list of changes of type (ChangeItem). ChangeItem contains some members, including the ItemId of the changed item. So you would use CSOM to get a reference to the item.

// Here is some psuedo code (I haven't tested)
//assuming your result is in an object called **changes** and you have a reference to the list it was changed on **changedList**

```
foreach(Change change in changes){
    ListItem changedItem  = changedList.GetItemById((change as ChangeItem).ItemId);
    SPClientContext.Load(changedItem);
    SPClientContext.ExecuteQuery();
}

```
Any fields or properties you would Load using CSOM using the standard CSOM load method
