### ISSUE TITLE
React-Modern-Chart Sample (Bug) - Can't Retrieve Managed Metadata Value

### ISSUE THREAD

**Issue by tanweeteck** [SharePoint/sp-dev-docs#5626]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

Source file: 
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-modern-charts

Solution | Author(s)
react-modern-charts | Jeremy Coleman (MCP, PC Professional, Inc.)

## Question
There are 3 fields (Managed Metadata) created in Opportunity custom list, Client Group, Client Segment and Client Company.
I would like to display the opportunity value based on Client Group. 
The React Modern Chart displayed managed metadata with **Object Object** instead of showing Client Group Name.

Expected Behavior:
Showing Client Group Name 

## Environment details (if applicable)
SharePoint Online (Office 365)
- **OS**: [e.g. Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**:  Node.js v6/v8/v10/v12
- **Browser(s)**: Chrome v79 | Chromium Edge v79
- **Tooling**: VS Code 
- **Additional details**: None.

![Chart_Show Object Object](https://user-images.githubusercontent.com/45476945/80325417-a0435e00-8867-11ea-90c1-1d65c2bf0dd6.JPG)
![Managed Metadata(Taxanomy)](https://user-images.githubusercontent.com/45476945/80325429-b18c6a80-8867-11ea-8069-ec0cf3c9eb61.JPG)

**Comment by bcameron1231** [comment]
Hi, Thank you for the question. From a high level, it would appear this web part doesn't quite support complex field types (object object, infers it could be parsed). 

I've noticed you've already submitted the question at the sp-dev-fx-webparts repo here https://github.com/SharePoint/sp-dev-fx-webparts/issues/1252 . As this code base lives in that repo, sp-dev-fx-webparts repo is best place to raise this question.

**Comment by tanweeteck** [comment]
> Hi, Thank you for the question. From a high level, it would appear this web part doesn't quite support complex field types (object object, infers it could be parsed).
> 
> I've noticed you've already submitted the question at the sp-dev-fx-webparts repo here [SharePoint/sp-dev-fx-webparts#1252](https://github.com/SharePoint/sp-dev-fx-webparts/issues/1252) . As this code base lives in that repo, sp-dev-fx-webparts repo is best place to raise this question.

Yeah. That's why I posted this issue in sp-dev-fx-webparts repo as well.

**Comment by andrewconnell** [comment]
This question is about a specific sample, so it should only be posted there.
