### ISSUE TITLE
How can i create sharepoint modern web pages with paragraph and image web parts using sharepoint APIs.

### ISSUE THREAD

**Issue by PrathyushP95** [SharePoint/sp-dev-docs#5627]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

**Comment by JarbasHorst** [comment]
Hello @PrathyushP95 

could you please provide more information. For instance:
- What do you want to do in detail?
- Do you want to create SharePoint pages using Power Automate?
- Do you want to create modern pages using a solution based on C#?
- What have you tried so far? Do you have any code example?

Regards,
Jarbas

**Comment by PrathyushP95** [comment]
I'm trying to create modern web pages in sharepoint site using Python code. APIs to create folder and upload files in sharepoint document library is working fine for me but i could not find a way to create modern pages with Title, sub-heading, images and text. Could you please help me out in this?

**Comment by bcameron1231** [comment]
Modern Pages content get stored internally on the item in the Site Pages library. There are hidden fields that contain the values for whats represented in the UX. Such properties include **_TopicHeader**, **BannerImageUrl**. The HTML and controls loaded on the page get stored in **LayoutWebpartsContent**, **CanvasContent1** properties.

**Comment by PrathyushP95** [comment]
@bcameron1231 I need to create modern web page with image and text web parts using sharepoint API. Is it possible to do that?

I tried with below API which creates samplePage.aspx inside Site pages library but when i tried to open it it gives me error.

https://domain-url/sites/SiteName/_api/web/GetFolderByServerRelativeUrl('/sites/SiteName/SitePages')/Files/AddTemplateFile(urlOfFile='samplePage.aspx',templateFileType=3)

![image](https://user-images.githubusercontent.com/20680181/80380731-977d7700-88bd-11ea-8cfa-f3df0c82f23a.png)

Can someone please help me on this.

**Comment by bcameron1231** [comment]
I've seen this before when the ClientSideApplicationId is not specified on the new page. 

I would try to programatically set the internal field **ClientSideApplicationId** equal to the following guid **b6917cb1-93a0-4b97-a84d-7cf49975d4ec**
