### ISSUE TITLE
Permissions Required

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#5631]
Please add details on what permissions are required in order to manage designs and scripts as well as if there is a way to delegate that out.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
@andrewconnell, please assign this issue to me. I don't have time atm, but will take care asap.
