### ISSUE TITLE
Attribute incorrectly documented

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#5634]
Should be "OffsetDays" not just "Offset".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1aed3c6-d0f2-df91-ecae-0345158a138b
* Version Independent ID: 8df123fe-96af-d50a-a614-2f265a1cd8fa
* Content: [Today element (Query)](https://docs.microsoft.com/en-us/sharepoint/dev/schema/today-element-query)
* Content Source: [docs/schema/today-element-query.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/today-element-query.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Thanks @sparkitect for your feedback. The issue has just been fixed and the documentation will be updated in the upcoming days.
