### ISSUE TITLE
There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

### ISSUE THREAD

**Issue by Sendil85** [SharePoint/sp-dev-docs#5635]
Hello,
I built 6 SPFX react webpart all having the same issue, it works fine in workbench and other than IE in Prod environment too.
Stuck with this issue for a while, is there any solution for this?
I have deployed it in  Appcatalog site andthose files are accessible via browser
https://publiccdn.sharepointonline.com/<tenant>/sites/<appcatalog>/ClientSideAssets/ff82b95b-2168-474c-b8e4-a72de48366d7/spfx-student-search-web-part_6f14a2d1a811d0dcd4010788bfa0b558.js, but it still says
There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:

I have noticed similar error in git hub, but none has the solution to fix it off.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details

[SPLoaderError.loadComponentError]:
***Failed to load component "c7c27d56-0ad7-48cc-9729-ae006be262f4" (SpfxStudentSearchWebPart). Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/<tenant>/sites/AppCatalog/ClientSideAssets/ff82b95b-2168-474c-b8e4-a72de48366d7/spfx-student-search-web-part_6f14a2d1a811d0dcd4010788bfa0b558.js' for resource 'spfx-student-search-web-part' in component 'c7c27d56-0ad7-48cc-9729-ae006be262f4' (SpfxStudentSearchWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

Thanks,
-Sendil

**Comment by andrewconnell** [comment]
Sorry, but you need more context. When you created the issue, there was a section for context. Can't tell if you're saying IE works or doesn't work with the workbench (BTW, it's not supported). Please resubmit a new issue with the same info, but please complete the context section...
