### ISSUE TITLE
SharePoint Designer Issues

### ISSUE THREAD

**Issue by Rfeltner00** [SharePoint/sp-dev-docs#5638]
## Category

- [x] Bug

## Describe the bug

Noticed these SP Designer issues started on 04/27/2020:
When editing any classic SharePoint Online page within SPDesigner that has a dataview within it, the dataview gets its dataresources ripped out and if saved now the dataview on the page no longer works. Was able to make dataview edits via SPDesigner on 04/24/2020. 

<img width="1438" alt="Screen Shot 2020-04-28 at 9 42 17 AM" src="https://user-images.githubusercontent.com/64546736/80620354-e4736180-8a13-11ea-8648-e2a73ac33214.png">

Also from within the SPDesigner, when trying to add a new Display, Edit or New Item form from within the list it gives the dreaded error, could not save list changes to the server.

<img width="1247" alt="Screen Shot 2020-04-29 at 10 45 08 AM" src="https://user-images.githubusercontent.com/64546736/80620298-cd347400-8a13-11ea-99ff-881d7928f23d.png">

We have tested on various tenants, site collections and all the same results. Tested with various admin accounts. We have cleared cache multiple times, reinstall of SPDesigner  and updating service pack. Checked lists for any possible lookup or calculated column issues. 

## Steps to Reproduce List Form Error

1. Open 'SPO Site in SPDesigner'
2. Click on 'Lists and Libraries'
3. Open 'SharePoint List'
4. Under Forms Click on 'New'
5. Create any type of Form, Click 'OK'
6. See error 'Could not save the list changes to the server'

## Expected behavior
1. Create a new Form with the chosen type and added to the List. 

## Steps to Reproduce Dataview Data Resource Issue

1. Open 'SPO Site in SPDesigner'
2. Go to a 'Classis Page with working Dataview on it'
3. Right Click and Select 'Edit File in Advanced Mode'
4. Scroll down to 'Dataview' on page.
5. Dataview appears to now be missing the Data Resources referenced in the code. 
6. Save page 'Dataview now stops functioning'

## Expected behavior
1. Opened Classic Page would display the datasource details within the dataview webpart. 
2. Allow updates
3. Save page and dataview still functioning and updates are there.

## Environment details (*development & target environment*)

- **OS**: [e.g. Windows 10 ]
- **Target Environment**: [SharePoint Online]
- **Tooling**: [SharePoint Designer]
- **Additional details**: *Classic Publishing Pages, Standard SharePoint Lists*

**Comment by bcameron1231** [comment]
Hi, thank you for the comment. Unfortunately what you are experiencing is now intended behavior. You will no longer be able to use SharePoint Designer to created custom forms in your environment (existing forms still work). This went into affect on the 25th of April. 


Please check your admin center for the following Service Message regarding this.
https://admin.microsoft.com/AdminPortal/home?switchtomodern=true#/MessageCenter?id=MC210713

**Comment by Rfeltner00** [comment]
@bcameron1231, with support being removed on the 25th, did this also impact dataviews embedded in classic pages?
