### ISSUE TITLE
Chrome Issue Aw Snap

### ISSUE THREAD

**Issue by KbWorks** [SharePoint/sp-dev-docs#564]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
Show webpage without going Aw Snap in Chrome. Since a couple of weeks we see this issue in Multiple tenants and PC happening. 

#### Observed Behavior
The Problem is you can not track exact behaviour it happens without doing anything on the pc like a time out others report that it is a blocking issue in the header 
It also happens on pages without customisations. https://techcommunity.microsoft.com/t5/SharePoint/Aw-Snap-issue-in-Chrome/m-p/64715#M6112
Could it be that it has something todo with the new HTML field Security field and domains?

**Comment by dgabrahams** [comment]
I have been getting this issue for the past month too. No discernible pattern.

**Comment by manishgarg1** [comment]
Hi, this is most likely a chrome bug. No matter what html/css/javascript we load, we should not be able to crash the browser. If somebody has consistent repro steps, we could work with google to help them resolve this.

**Comment by Worrelpa** [comment]
We are seeing it in Sharepoint online for the past few weeks. Getting a bit frustrating having to press refresh every so often when a page won't load.
