### ISSUE TITLE
Update the tutorial "Consume the Microsoft Graph in the SharePoint Framework"

### ISSUE THREAD

**Issue by plamber** [SharePoint/sp-dev-docs#5641]
## Category

- [x] Bug

## Describe the bug
The current tutorial [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-au/sharepoint/dev/spfx/use-aad-tutorial#feedback) has an outdated version of office react and does not work if you try to follow the steps in a newly provisioned SPFx 1.10 project.

I already updated the project provided for download [here](https://github.com/SharePoint/sp-dev-fx-webparts/pull/1264). 
Is it ok for you if I am going to update the steps provided in the tutorial? If this is the case, I will take it up asap.

Thank you,
Patrick

**Comment by JarbasHorst** [comment]
Hello @plamber 

please, submit a PR with your suggestions for the doc edits! Also, please make sure you reference this issue in your PR 😀

Thanks
Jarbas

**Comment by plamber** [comment]
@JarbasHorst just created the PR
