### ISSUE TITLE
Selectproperties parameter does not filter the managed properties requested instead returning all properties

### ISSUE THREAD

**Issue by manojkgaai** [SharePoint/sp-dev-docs#5643]
In SP.SimpleDataTable xml response, search api is returning below properties, eventough passing Selectproperties parameters with just Title as property required response.

Rank,DocId,Title,SiteId,WebId,UniqueId,PartitionId,UrlZone,Culture,ResultTypeId,RenderTemplateId,GeoLocationSource

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#bk_SelectProperties)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Ping @wobba

**Comment by wobba** [comment]
By design as a mimimal set of properties is always returned with the SP REST API.
