### ISSUE TITLE
Developer blog link not working

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/sp-dev-docs#5644]
In the beginning of the documentation, a link is mentioned to the developer blog "more background behind this on our developer blog." This is a dead link. So please update to the new location or remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77701e1-868a-3768-b2ab-ce97ba41b408
* Version Independent ID: c18e9584-f323-926e-0cc2-7742d1a2736b
* Content: [Supporting % and # in files and folders with the ResourcePath API](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api)
* Content Source: [docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
This is fixed in master branch https://github.com/SharePoint/sp-dev-docs/commit/e49588c642eac9aff573ba84ffde2ca35ee07546 , yet to merge in live branch 

The right URL - https://developer.microsoft.com/office/blogs/upcoming-changes-to-sharepoint-and-onedrive-for-business-apis-to-support-and-in-file-names

**Comment by andrewconnell** [comment]
The live branch is refreshed on a specific schedule.
