### ISSUE TITLE
Connect-SPOService : Could not Connect to Sharepoint Online

### ISSUE THREAD

**Issue by kboovaragan** [SharePoint/sp-dev-docs#5645]
## Category

- Connect-SPOService : Could not connect to Sharepoint online

## Describe the bug

I am following the tutorial to Deploy the WebPart in Office 365 CDN (Host your client-side web part from Office 365 CDN (Hello World part 4)), As per Point 2, when i try to Run the Command, Connect-SPOService -Url https://contoso-admin.sharepoint.com, in the PowerShell

## Steps to reproduce

1. Open up the PowerShell
2. Install the Module using command - Install-Module -Name Microsoft.Online.SharePoint.PowerShell
3. Run the Command - Connect-SPOService -Url https://contoso-admin.sharepoint.com, got the below error.
4. See error:
![image](https://user-images.githubusercontent.com/6533160/80734578-ff85c480-8b2c-11ea-8653-4ab11e078289.png)
Connect-SPOService : Could not connect to SharePoint Online.

## Expected behavior
It should Connect so that, we can run the next steps to Host the webpart.

## Environment details (*development & target environment*)

Development Environment
- OS : Windows 10
- Target Enviroment : SharePoint Online
- Framework : Node.js v10
- Browser : Chrome v81
- Tooling : VS Code

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Just for clarification, are you replacing the **https://contoso-admin.sharepoint.com** with your tenant URL? Contoso-admin is just for the sample. You will want to use the URL of your SharePoint Admin Center.

**Comment by kboovaragan** [comment]
Okay, I suspected it, but the instructions given in that page, never had
this info, so I was bit confused.
Let me try it again with my url and let you know, if I face any issues...
Thanks for the prompt response...

**Comment by andrewconnell** [comment]
Hi @kboovaragan this repo is for developer-specific questions... this should be posted to TechCommunity...

**Comment by kboovaragan** [comment]
Thanks Andrew, for the update.
Can you let me know the correct forum with URL, where i can get help for
the issues that i get when following the MS tutorial to setup Dev
environment? and create sharepoint webparts, i have few clarifications ,
issues, that i might need some support/help, to move forward in my learning.

Warm Regards,
Krishnasamy.

**Comment by andrewconnell** [comment]
@kboovaragan I removed my comment because I realized you were asking about the steps for a specific article in the docs... its fine here.

When you create a new issue, there's a link that points to the **SharePoint TechCommunity**.

**Comment by Jerry0527** [comment]
Contoso is a demo domain name, need to replace with yours.

The URL format will be like this:

https://TenantName-admin.sharepoint.com

**Comment by kboovaragan** [comment]
Thanks for your response, I had progressed further giving my url...
Still, in the last part, where we host in CDN, it failed... Not able to
make what was the issue.
I followed the steps as given in ms site...
After packaging my solution, when I drag and drop the package into my team
site content, it was not getting copied...rather it is getting downloaded
to my download folder...
Kindly help....

**Comment by Jerry0527** [comment]
@kboovaragan, you are uploading to the wrong place, should upload into SharePoint Online Admin Center App Catalog instead of Team Site Contents.

**Comment by kboovaragan** [comment]
Thanks for prompt response...
Will check accordingly

**Comment by kboovaragan** [comment]
Hello,

Good day to you.
In continuation to my learning, i am trying the tutorial, as given in MS
site, when i tried to implement the DropDown List feature, i am getting
this error... I followed all the steps as given in the MS site... Kindly
help to overcome this issue.
[image: image.png]

Warm Regards,
Krishnasamy.

**Comment by Jerry0527** [comment]
Seems you are meeting the new issue ? Can't see the image.
You can create a new issue if you have the new problem.
For the question in this issue 
"Connect-SPOService : Could not Connect to Sharepoint Online"
Have you resolved yet ?

**Comment by kboovaragan** [comment]
Okay thanks, will check again and if I have issues, will create new issue.
Thanks for prompt response.

**Comment by Jerry0527** [comment]
You can close this issue, if the error has been resolved in your side.
Thanks

**Comment by kboovaragan** [comment]
Okay, this issue can be closed....
