### ISSUE TITLE
Security best practice - don't load js files from CDNs

### ISSUE THREAD

**Issue by jeremyjee** [SharePoint/sp-dev-docs#5652]
## Category

- [ ] Question
- [ ] Typo
- [x] Additional article idea

## Additional article idea

With reference to dev/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint there is a bad practice being given as an example i.e.
<script 
    src="//ajax.aspnetcdn.com/ajax/4.0/1/MicrosoftAjax.js" 
    type="text/javascript">
</script>
<script
    type="text/javascript"
    src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js">
</script>
It is not good security practice to load .js files from a CDN because the contents of the .js files are not within the application developers control being loaded directly from the internet they could be compromised. 

Wouldn't it be better to give an example local site assets location for the loaded files instead?

**Comment by bcameron1231** [comment]
Thank you for your question. I wouldn't say using CDNs is a _bad practice_. CDNs are still the most widely accepted way of serving up cached client side assets in web development across the world. Of course, I always recommend serving files from reputable CDNs. However, the use of CDNs and possible security concerns (if one became compromised) vary by organization/individual and if you feel uncomfortable using a CDN... by all means, you don't have to use them. 

A quick note about that CDN being referenced. It is owned and operated by Microsoft. If you don't feel confident or safe using Microsoft's CDN for your Microsoft solutions, then pull them in locally and use them within your solution.
