### ISSUE TITLE
SPFx app permission policy

### ISSUE THREAD

**Issue by mdanielcristian** [SharePoint/sp-dev-docs#5655]
## Category

- [x] Bug

## Describe the bug

SPFx app permission policy can be bypassed by creating another app, in which you put a tab to a blocked app.

## Steps to reproduce

-Create new SPFx Teams Personal application APP1
-Create an app permission policy so that user is blocked from accessing APP1
-Create another personal app APP2 in which APP1 (blocked) is a tab. You can do this by adding the following content URL (https://{tenant-url}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={component-id}%26forceLocale=en-us)

User is able to access APP1, using the tab in APP2

## Expected behavior

-User is not able to access APP1 through the catalog and user is not able to access APP1 from the tab in APP2

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: Teams
- **Browser(s)**: all
- **Tooling**:  VS Code, SPFx v1.10.0

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Unclear... can you provide more detail? There's no such thing as an app permission policy in SPFx...
