### ISSUE TITLE
SharePoint API permissions with client/secret authentication

### ISSUE THREAD

**Issue by ls-mze** [SharePoint/sp-dev-docs#5658]
Is there a specific reason why the SharePoint API permissions only work with this authentication method? We would like to use the client/secret authentication method while also preferably managing all permissions for apps directly on the app permissions page.
It is a bit misleading within the azure portal that you can add "Sites.FullControl.All" SharePoint permissions to an app, but can't use them when using "Connect-PnPOnline -AppId xxx -AppSecret yyy -Url zzz", which produces 403 errors when using "Get-PnPWeb" afterwards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#feedback)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by ls-mze** [comment]
It's been two weeks. Any news on this?

**Comment by Udaykiran24** [comment]
any answer?

**Comment by ls-mze** [comment]
Hello? Anyone here?

**Comment by ls-mze** [comment]
Seeing as this question is now over half a year old with no reaction: Is there any chance of actually getting an answer?
