### ISSUE TITLE
No examples and link points to archived docs page.

### ISSUE THREAD

**Issue by bradlis7** [SharePoint/sp-dev-docs#5660]
The See Also &gt; Class Library link is an archived page, so I'm not sure if it's functional. This page tells us what it can do, but there's no indication about how to do it. I would like to see some example code for people to use this programmatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc2d53c5-9198-3dfe-e38b-646d11764246
* Version Independent ID: 304fd11b-bca0-2284-93b0-0ccd38caebe0
* Content: [What's new in Word Automation Services for developers](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-word-automation-services-for-developers#feedback)
* Content Source: [docs/general-development/what-s-new-in-word-automation-services-for-developers.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/what-s-new-in-word-automation-services-for-developers.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Here are some code demos to use Word Automation Service to Covert Word to PDF using C#:

[Convert Doc/Docx Files To PDF In SharePoint 2013 Using Word Automation Services (C#)](https://jaredmeredith.com/2015/08/20/convert-docdocx-files-to-pdf-in-sharepoint-2013-using-word-automation-services/)

[Converting a Library’s Word Documents to PDF using Word Automation Services for SharePoint 2013](https://cann0nf0dder.wordpress.com/2015/02/01/converting-a-librarys-word-documents-to-pdf-using-word-automation-services-for-sharepoint-2013/)
