### ISSUE TITLE
module "@pnp/sp/index" has no member "List"

### ISSUE THREAD

**Issue by frankchienwang** [SharePoint/sp-dev-docs#5663]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I'm trying to run this tutorial at this link

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts

which seems to link back to this repo. 

when I'm trying to complete this step.

Update the ViewModel 

in the editor the import statement for @pnp/sp has the error in the title for all the items.

## Environment details (*development & target environment*)
 

- **OS**: Windows 10  
- **Target Environment**:  SharePoint Server 2016  
- **Framework**:   Node.js  v12
- **Browser(s)**:  Edge  
- **Tooling**:  VS Code  
 
  #spfx-webparts

**Comment by AJIXuMuK** [comment]
This article is old. It is based on PnPJS version 1.2.5. Currently PnPJS jumped to v2 that has breaking changes to the modules.

If you want to go through the tutorial, you can install specific version of the modules like that:
```
npm install @pnp/logging@1.2.5 @pnp/common@1.2.5 @pnp/odata@1.2.5 @pnp/sp@1.2.5 --save
```

Or you can look at [PnPJS](https://pnp.github.io/pnpjs/) documentation and use the latest and greatest instead.
