### ISSUE TITLE
Support for Managed Metadata column?

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#5664]
[ ] True
[ ] False

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by PrasadKasireddy** [comment]
@sparkitect - Please can you share the more details about issue, it is really help us to resolve issue quickly

**Comment by sparkitect** [comment]
The document does not indicate whether or not a Managed Metadata column can either be hidden with a formula or be used in a formula to hide another column.

The document indicates which column types _cannot_ be used, and only a subset of the remaining column types. Data Types not specifically mentioned include:

- Managed Metadata
- Lookup
- Single line of text
- Multiple lines of text
- Yes/No
- Person or Group
- Hyperlink or Picture

-
