### ISSUE TITLE
Create list item rest API has wrong

### ISSUE THREAD

**Issue by AmoLUsoi** [SharePoint/sp-dev-docs#5665]
Accept: "application/json;odata=nometadata"
Content-Type: "application/json"

should be:

Accept: "application/json;odata=verbose"
Content-Type: "application/json;odata=verbose"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#create-list-item)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, thank you for the comment. Yes this is true. Given that the example is passing in the __metadata attribute, using `nometadata` would result in a 400 error. I've submitted a PR to fix this.
