### ISSUE TITLE
Error while scaffolding SPFx project using Yarn

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5666]
## Category

- [x] Bug

## Describe the bug
When trying to scaffold SPFx project using `yarn` I'm getting the next error:
```
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fluentui/react-icons/-/react-icons-0.1.9.tgz: ESOCKETTIMEDOUT".
```

Default (`npm`) works just fine.

## Steps to reproduce

`yo @microsoft/sharepoint --package-manager yarn`

## Expected behavior

The project is scaffolded correctly

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: not applicable
- **Tooling**: SPFx v1.10.0

**Comment by bcameron1231** [comment]
Hi Alex. 

I am unable to reproduce using node v10 and SPFx 1.10. Can you try creating a new solution again? It could rule out a possible network issue you may have been having last night. If you still have this issue, could you try increasing the network timeout for yarn? I believe the default timeout for yarn is 30s. It can be increased using `--network-timeout`.

If you are still having issues even after the above, at least we can rule out those as possible issues. :)

**Comment by AJIXuMuK** [comment]
good catch @bcameron1231!
`yarn config set network-timeout 600000 -g` did the trick.
