### ISSUE TITLE
__metadata is not required

### ISSUE THREAD

**Issue by merly-cortez** [SharePoint/sp-dev-docs#5667]
When updating list item, including __metadata throws an error. __metadata needs to be excluded to have a successful update to a list item. This was previously raised from https://github.com/SharePoint/sp-dev-docs/issues/3859 but was unnecessarily marked as resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#feedback)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, thank you for the question. Can you provide more context information and share the request you are trying to make? 

Your request including with headers being sent will be helpful, as I've seen this issue when the wrong Accept and Content-Type headers being passed in.

**Comment by merly-cortez** [comment]
> Hi, thank you for the question. Is the request you are making related to this issue that was recently submitted #5665 for the Create List Item example?
> 
> When making a POST request, __metadata attribute isn't required if aren't passing the `Accept:"application/json;odata=nometadata"` header. If you are passing in a `verbose ` header you would need to specify the __metadata attribute.
> 
> We noticed that the Create Item sample in the documentation was doing this incorrectly by passing in the`__metadata`property and also the `nometadata` header.

I am referring to the Update List item example.
I had the headers as
{
  "Contet-Type": "application/json",
  "X-HTTP-METHOD": "MERGE",
  "IF-MATCH": "*",
  "Accept": "application/json;odata=verbose"
}
I had the Body as
{
 '__metadata': {
    'type': 'SP.Data.Projects_x0020_and_x0020_work_x0020_packagesListItem'
  },
'SharePoint_x0020_Document_x0020_':
{'Description':'Document folder',
'Url':'https://tenant.sharepoint.com/sites/ets-hub/Shared%20Documents/ETS00124%20-%20Project001'}
}

Each time I add the__metadata, I am getting this error:
The property '__metadata' does not exist on type 'SP.Data.Projects_x0020_and_x0020_work_x0020_packagesListItem'. Make sure to only use property names that are defined by the type.

I had to remove __metadata to make a successful POST and get the item updated.
