### ISSUE TITLE
hello world error code

### ISSUE THREAD

**Issue by fantje** [SharePoint/sp-dev-docs#5668]
Learning code and sharepoint true Build your first SharePoint client-side web part (Hello World part 1)
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

ad the end always get this message:
{
	"resource": "/c:/Users/fantje/src/webparts/helloworld/HelloworldWebPart.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 88,
	"startColumn": 2,
	"endLineNumber": 88,
	"endColumn": 2
}

how do I fix this?  
thanks

**Comment by bcameron1231** [comment]
Hi @fantje, the error specified looks like you are missing a closing bracket `}` in your main web part file. Check on line 88 where you are missing it.
