### ISSUE TITLE
Read access user not able to see the content of SPFx webpart

### ISSUE THREAD

**Issue by anandkumar0289** [SharePoint/sp-dev-docs#5671]
I am very new to SPFx web part creation.

I have created simple alert in SPFx webpart using React.

Added package to app catalog then added in my page.

The issue that i am facing is user having read access not getting alert or content of this webpart.

But user having higher access able to see the content also getting alert.

I don't know the root cause behind this.

#sharePoint SPFx
#spfx

**Comment by bcameron1231** [comment]
Hi, could you please provide more context info and update your original issue? Please use the template provided when creating a new issue.  Information that we will need to help, are below.

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

Also please provide more information as to how your web part is implemented (Static Data, Data from SharePoint, etc..) and any source code you have that would aid in helping you further. 

Currently, there isn't enough information provided.

**Comment by anandkumar0289** [comment]
i am able to fix my issue..thanks
