### ISSUE TITLE
在SharePoint 2019中是否支持ClientSideExtension.ListViewCommandSet扩展

### ISSUE THREAD

**Issue by qiumc** [SharePoint/sp-dev-docs#5673]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

>需要在SharePoint 2019 On-Pre中扩展list按钮。
按照https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api添加功能后，没有显示按钮。
SharePoint2019是否支持ClientSideExtension.ListViewCommandSet扩展

Need add a button at list commadnbar，

After adding the function according to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api, no button is displayed.

Does SharePoint 2019 support clientsideextension.listviewcommandset extension

## Environment details (*development & target environment*)

> SharePoint 2019 On-Premise
SPFX version 1.4.1
NodeJS version 10.18

*Thanks for your contribution! Sharing is caring.*

**Comment by qiumc** [comment]
有没有办法在列表页面获取选中状态的Item。

Is there has any way to get selected item id on the list view modern page

**Comment by andrewconnell** [comment]
Yes... the `event` parameter passed into the `onExecute()` method, specifically the `event.selectedRows` array, contains a list of all the selected items.

**Comment by qiumc** [comment]
Is there an article or example for SharePoint 2019 on-pre.The ListViewCommandSet extension has not been implemented in my environment.
