### ISSUE TITLE
Experiencing Random Crashing in Various spFx solutions in IE

### ISSUE THREAD

**Issue by rmbw74** [SharePoint/sp-dev-docs#5676]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Started to get random reports from users that are using Internet Explorer of Web Parts and Extensions crashing or reporting issues in Internet Explorer, noticed that there was a similar 
issue noted here, and wondered if they may be related

https://docs.microsoft.com/en-us/sharepoint/troubleshoot/web-parts/something-went-wrong-error-configuring-spfx-component

## Environment details (*development & target environment*)

- **OS**: [ Windows 10 ]
- **Target Environment**: SharePoint Online Modern Pages 
- **Browser(s)**: [IE v11]
- **Tooling**: [ SPFx (varies between 1.4 , 1.9 and 1.10 | spPnP varies between 1.3.X | sp-pnp-polyfillIE11 various versions]
- **Additional details**: 

In the technical details, the original error is as follows 

Failed to load entry point from component XXXXXXXX Original Error: Can't convert object to primitive value 

this seems to happen most often on initial page load, and a refresh of the page fixes the problem. 
Random web parts and extensions seem to fail when it does happen.

https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d7-7517bc4b514417582c5ea8556bcb4918/views/imgpsh_mobile_save

https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d3-d2d9a00a78f556761475895707efe318/views/imgpsh_mobile_save

**Comment by rmbw74** [comment]
![SomethingWentWrong](https://user-images.githubusercontent.com/15833201/81206371-a0430c80-8f91-11ea-82d2-3002c73a2ceb.png)
![Technical Details](https://user-images.githubusercontent.com/15833201/81206420-b650cd00-8f91-11ea-8331-056b83688128.png)

**Comment by andrewconnell** [comment]
Have you verified IE's document mode is set to 11? That stated as a requirement in the SPO browser support for IE specifically.

If so & the issue is still happening, you'll likely have to open a ticket via your admin center / post to TechCommunity. This repo is for developer-related issues and unfortunately, browser support isn't something that can be addressed here.
