### ISSUE TITLE
"Edit conditional formula" is missing

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#5677]
In my library I do not see "Edit conditional formula" option. Only have two option "Move Up" and "Move Down"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by renehenriksenskat** [comment]
I don't have it either. Has it not rolled out completely yet?

**Comment by bcameron1231** [comment]
This feature has not been 100% rolled out yet.

**Comment by andrewconnell** [comment]
Wrong tag applied. Reverted the workflow that closed & locked this issue. #mybad
