### ISSUE TITLE
create context for another site from SPFX webpart - sharepoint online

### ISSUE THREAD

**Issue by rajjspfx** [SharePoint/sp-dev-docs#5679]
Hi,

Please help me to create sp context for another site  and fetch list data from spfx web part using react.

For example : I have spfx webpart on http://siteone.com  and i need to create context for another site http://sitetwo.com or it might be different domain too http://site.net .

One scenario site one SPO => Site two also SPO 
Second Scenario Sharepoint online => On prem site

How to get authentication success if it's another site or different domain ?  

Suppose if i use Azure API to talk second site and get data , how should i call Azure api with successful authentiction ?

**Comment by andrewconnell** [comment]
@rajjspfx said:
> create sp context for another site and fetch list data from spfx web part 

Not possible... if you want to make calls across site collections, you'll need to either build a new request using the SP REST API & an access token OR use Microsoft Graph's support (I'd use the latter).

Each request using the **SPHttpClient** uses cookie authentication that's. been set for the site you're on. That can't be used to make calls across sites.

**Comment by andrewconnell** [comment]
In the future, please use the issue templates we've provided to include the required information when creating a new issue.
