### ISSUE TITLE
Property Pane multi checkbox group based on server data

### ISSUE THREAD

**Issue by malexandrum** [SharePoint/sp-dev-docs#568]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I need to add a list of countries to the web part configuration page as checkboxes so that the user can choose as many countries as needed. List of countries comes after a REST call. I didn't see a field type that could handle that. 
1. Do I need to create a custom one? 
2. In what type of variable would I store the checked countries so I get them in the root React component passed from the web part container?

Thanks!

**Comment by manishgarg1** [comment]
Hi @malexandrum, we do not have an inbuilt control in the propertyPane for displaying a list of checkboxes. Dropdown is the only control that could match your need. A custom control would be a perfectly fine choice. Could you please clarify your second question? It is unclear exactly what you are asking for.

**Comment by malexandrum** [comment]
Thanks @manishgarg1, i figured the second question in the mean time.
