### ISSUE TITLE
Sharepoint Version? only online I assume ...

### ISSUE THREAD

**Issue by haticapp** [SharePoint/sp-dev-docs#5684]
you really should inform us on to which versions this feature applies to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://docs.microsoft.com/en-us/sharepoint/dev/features/site-footer#feedback)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/site-footer.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Correct, SharePoint Online.
