### ISSUE TITLE
Please update for SharePoint 2019

### ISSUE THREAD

**Issue by haticapp** [SharePoint/sp-dev-docs#5687]
Please update for SharePoint 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, thank you for the comment. Can you clarify what you think is missing? The development environment for SharePoint 2019 is the same.

**Comment by haticapp** [comment]
Hi,
You have a note on the page “Set up your Office 365 tenant<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant>."
And you can think “Maybe I’m can only use this on SPO.” But how can I developed solutions on SP2019 SPFx …
Then you make some remarks about SP2016 … I think because of the changes on NodeJS.
And you think “ok this works on SP2016” …
And what about SP2019 ??

Finally I found on setup and deployment section this link
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support
Ok now I’m getting on the right track.
There are a lot of resources about SPFx but many of them lack the reference to the version of SPFx or if it works only at SPO or also on SP2019, SP2016 … I now the mainstream is SPO but …

Best Regards,
Helder Alexandre
