### ISSUE TITLE
Multi Geo: SPFX aadTokenProviderFactory fails because of missing redirect uris

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#5688]
## Category

- [x] Bug

## Describe the bug

On a Tenant where the multi geo features for SharePoint have been enabled the SPFX `aadTokenProviderFactory` is failing on the non-Worldwide geo location with:

`InvalidAccessError: A parameter or an operation is not supported by the underlying object`

## Steps to reproduce

Add a webpart or application customizer using the aadTokenProviderFactory to a site collection of a SharePoint geo tenant which is not your master geo tenant:

`aadTokenProviderFactory.getTokenProvider().then(tokenProvider => tokenProvider.getToken('ClientId'));`

## Expected behavior

The function should return a valid jwt token because the redirect URIs for the second geo location should have been automatically added to the **SharePoint Online Client Extensibility Web Application Principal** app.

Alternatively please add somewhere to the documentation that you need to manually add the redirect uris for each geo location.

# Environment details (development & target environment)

OS: Windows 10
Target Environment: SharePoint Online
Framework: Javascript
Browser(s): Chrome 81.0.4044.138
Tooling: SPFx v1.10

### Geo locations

The two geo locations look like this:

|URL|GeoLocation|
|--|--|
|exampleTenant.sharepoint.com|Worldwide|
|exampleTenantNAM.sharepoint.com|US|

### login.microsoftonline.com error

We digged a little bit deeper and found that https://login.microsoftonline.com is returning the following error message:

`AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'dea06361-c2f8-4aa5-8a74-2bf7dc911ced'. `

**dea06361-c2f8-4aa5-8a74-2bf7dc911ced** is the id of the **SharePoint Online Client Extensibility Web Application Principal** app.

We checked the redirect uris of this app and saw that it only contains the redirect uris for **exampleTenant.sharepoint.com** and not for **exampleTenantNAM.sharepoint.com**.

![image](https://user-images.githubusercontent.com/31658807/81412009-77627900-9143-11ea-9b0b-6e5a32c5155a.png)

**We have manually added the redirect urls for the exampleTenantNAM.sharepoint.com location Afterwards the error did not appear anymore.**

**Comment by andrewconnell** [comment]
Please don't delete the relevant questions that were in the template... these are needed for context. Please complete the original section:

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by MrTantum** [comment]
Sorry. I have added the missing information.

**Comment by lucabandMSFT** [comment]
So, we had some problems back to that time that we think we have fully fixed now. Can you please perform the following steps to see if that solves the issue: on each geo location where the app catalog exists, go to the API access page in SPO tenant admin for that location using an account that is Global Admin in AAD: that will create the right URIs in the application principal in AAD and also enable the right information in SPO for the auth process.

**Comment by MrTantum** [comment]
Thanks for the feedback. I have no possibility to check this anymore in the affected tenant. We just have to hope that this has been fixed.
