### ISSUE TITLE
missing modern ... classic and modern pages on 1st paragraph

### ISSUE THREAD

**Issue by haticapp** [SharePoint/sp-dev-docs#5690]
missing modern ... classic and modern pages on 1st paragraph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae796d02-c060-77fd-6448-e1a0f6f149e1
* Version Independent ID: b85cb658-3b40-fd0c-8491-511c42a2d4b8
* Content: [SharePoint Framework development with SharePoint 2019](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support)
* Content Source: [docs/spfx/sharepoint-2019-support.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-2019-support.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Fixed 3a3581f2102d0eabaf058974b22efb6a59900ff5
