### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by robgarrett** [SharePoint/sp-dev-docs#5691]
I believe the "theme" property of the JSON at the beginning of the page should be "palette".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4c91be-dca2-6411-b707-a023ad26306c
* Version Independent ID: 29ba4619-814e-784a-04a8-84b4d56933dd
* Content: [SharePoint site theming - JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bookworm2death** [comment]
The problem was revealed when we tried to create a site design with a custom theme. If you actually export a site design you see it uses the word "palette". Here is some example JSON from a blog post about it. Also there look to be a lot more color tokens than described in the article. https://laurakokkarinen.com/the-ultimate-guide-to-sharepoint-site-designs-and-site-scripts/ 

{
      "verb": "applyTheme",
      "themeJson": {
        "version": "2",
        "isInverted": false,
        "palette": {
          "themeLight": "#fffdd3ce",
          "themeTertiary": "#ff7088aa",
          "black": "#ff3f3f3f",
          "neutralSecondary": "#ff53c7bd",
          "neutralTertiaryAlt": "#ffc8c8c8",
          "themeSecondary": "#ff567095",
          "themeDarker": "#ff1c3557",
          "neutralQuaternary": "#ffd0d0d0",
          "neutralPrimaryAlt": "#ff818181",
          "neutralPrimary": "#ff8c8c8c",
          "themeDark": "#fff87060",
          "themeLighter": "#fffee7e5",
          "neutralTertiary": "#ffd4d4d4",
          "accent": "#fff87060",
          "neutralQuaternaryAlt": "#ffdadada",
          "themeLighterAlt": "#ffd3dce8",
          "neutralLighter": "#fff4f4f4",
          "neutralLight": "#ffeaeaea",
          "neutralDark": "#ff555555",
          "themeDarkAlt": "#fff87060",
          "neutralLighterAlt": "#fff8f8f8",
          "white": "#ffffffff",
          "themePrimary": "#ff102542",
          "HyperlinkActive": "#ff1c3557",
          "CommandLinksPressed": "#ff1c3557",
          "NavigationPressed": "#ff1c3557",
          "EmphasisHoverBorder": "#ff1c3557",
          "TopBarPressedText": "#ff1c3557",
          "HeaderNavigationPressedText": "#ff1c3557",
          "Hyperlinkfollowed": "#ff1c3557",
          "EmphasisHoverBackground": "#fff87060",
          "EmphasisBorder": "#fff87060",
          "AccentText": "#ff102542",
          "CommandLinksHover": "#ff102542",
          "RowAccent": "#ff102542",
          "NavigationAccent": "#ff102542",
          "NavigationHover": "#ff102542",
          "EmphasisBackground": "#ff102542",
          "HeaderNavigationHoverText": "#ff102542",
          "HeaderNavigationSelectedText": "#ff102542",
          "SuiteBarBackground": "#ff102542",
          "Hyperlink": "#ff102542",
          "ContentAccent1": "#ff102542",
          "AccentLines": "#ff567095",
          "HeaderAccentLines": "#ff567095",
          "ButtonPressedBorder": "#ff567095",
          "SuiteBarHoverBackground": "#ff7088aa",
          "StrongLines": "#fffdd3ce",
          "HeaderStrongLines": "#fffdd3ce",
          "SuiteBarHoverText": "#fffdd3ce",
          "ButtonPressedBackground": "#fffdd3ce",
          "ButtonHoverBorder": "#fffdd3ce",
          "ButtonHoverBackground": "#fffee7e5",
          "SelectionBackground": "#7ffdd3ce",
          "HoverBackground": "#7ffee7e5",
          "NavigationHoverBackground": "#7ffee7e5",
          "PageBackground": "#ffffffff",
          "EmphasisText": "#ffffffff",
          "SuiteBarText": "#ffffffff",
          "TileText": "#ffffffff",
          "BackgroundOverlay": "#d8ffffff",
          "HeaderBackground": "#d8ffffff",
          "FooterBackground": "#d8ffffff",
          "DisabledBackground": "#fff8f8f8",
          "HeaderDisabledBackground": "#fff8f8f8",
          "ButtonBackground": "#fff8f8f8",
          "ButtonDisabledBackground": "#fff8f8f8",
          "SubtleEmphasisBackground": "#fff4f4f4",
          "DialogBorder": "#fff4f4f4",
          "NavigationSelectedBackground": "#c6eaeaea",
          "TopBarBackground": "#c6eaeaea",
          "DisabledLines": "#ffeaeaea",
          "HeaderDisabledLines": "#ffeaeaea",
          "ButtonDisabledBorder": "#ffeaeaea",
          "SuiteBarDisabledText": "#ffeaeaea",
          "SubtleLines": "#ffc8c8c8",
          "HeaderSubtleLines": "#ffc8c8c8",
          "ButtonGlyphDisabled": "#ffc8c8c8",
          "DisabledText": "#ffd4d4d4",
          "CommandLinksDisabled": "#ffd4d4d4",
          "HeaderDisableText": "#ffd4d4d4",
          "ButtonDisabledText": "#ffd4d4d4",
          "Lines": "#ffd4d4d4",
          "HeaderLines": "#ffd4d4d4",
          "ButtonBorder": "#ffd4d4d4",
          "CommandLinks": "#ff53c7bd",
          "Navigation": "#ff53c7bd",
          "SubtleEmphasisText": "#ff53c7bd",
          "TopBarText": "#ff53c7bd",
          "HeaderNavigationText": "#ff53c7bd",
          "ButtonGlyph": "#ff53c7bd",
          "BodyText": "#ff8c8c8c",
          "WebPartHeading": "#ff8c8c8c",
          "HeaderText": "#ff8c8c8c",
          "ButtonText": "#ff8c8c8c",
          "ButtonGlyphActive": "#ff8c8c8c",
          "TopBarHoverText": "#ff8c8c8c",
          "StrongBodyText": "#ff555555",
          "SiteTitle": "#ff555555",
          "CommandLinksSecondary": "#ff555555",
          "SubtleEmphasisCommandLinks": "#ff555555",
          "HeaderSiteTitle": "#ff555555",
          "TileBackgroundOverlay": "#7f3f3f3f",
          "ContentAccent2": "#ff00485b",
          "ContentAccent3": "#ff288054",
          "ContentAccent4": "#ff767956",
          "ContentAccent5": "#ffed0033",
          "ContentAccent6": "#ff682a7a"
        }
      }
    }

**Comment by andrewconnell** [comment]
Fixed in in recent PR merge #5696
