### ISSUE TITLE
SPFx ListViewCommandSet Extensions are no longer being loaded when switching list context in side navigation!

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#5692]
## Category

- [X] Bug

## Question

I registered a list view command set extension for a list. 
If I open the list page for a list for which the extension is activated, the extension gets loaded. 
If I open the list page for a list for which the extension is not activated and then navigate to the list for which it is activated using the navigation tree, the extension does NOT get loaded. 
Also, if the extension was loaded for a list and the user switches to another list using the navigation, the extension activated for that list does not get initialized (onInit is not being called again). 
Finally, the onListViewUpdated-Event never worked. 

This issue makes list view command set extensions quite useless and breaks our product. 
Is there any fix coming for this or should we move on to generic extensions loaded for every page?

**Comment by andrewconnell** [comment]
Can you please not delete the issue template sections and complete them as requested? The sections are there for a reason... we need context around the scenario to investigate.
