### ISSUE TITLE
`DoesUserHavePermissions`, `EffectiveBasePermissions`  return incorrect value when accessed using OAuth Access Token

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#5694]
## Category

- [x] Bug

## Describe the bug

When using `DoesUserHavePermissions` with OAuth access token it returns `false` when should return `true`.
`EffectiveBasePermissions` returns incorrect `High` and `Low`.

When used in browser (cookie auth with `SPOIDCRL`) - both methods/endpoints behave correctly.

## Steps to reproduce

User has Full Control permissions set, but the code below returns `false`
```csharp
m_ctx.ExecutingWebRequest += (sender, e) =>
{
  e.WebRequestExecutor.RequestHeaders["Authorization"] = $"Bearer {accessToken}";
};
var meetingWeb = m_ctx.Site.OpenWeb(url);
var basePermissions = new BasePermissions();
basePermissions.Set(PermissionKind.ManageWeb);
var hasPerms = meetingWeb.DoesUserHavePermissions(basePermissions);
m_ctx.ExecuteQueryRetry();

if (hasPerms.Value)
{
  // has permissions
}
else
{
  // doesn't have permissions
}
```

## Expected behavior

`DoesUserHavePermissions` and `EffectiveBasePermissions` return correct values

## Environment details (*development & target environment*)

- **OS**: [Azure App Service]
- **Target Environment**: SharePoint Online
- **Framework**: .NET Framework v4.7.2
- **Browser(s)**: any
- **Tooling**: Visual Studio 2019
- **Additional details**: CSOM v16.1.19927.12000

### Additional context

The user definitely has permissions.

**Comment by AJIXuMuK** [comment]
Additional Info:
Although `_api/web/effectiveBasePermissions` returns correct `High` and `Low`, CSOM equivalent:
```csharp
var meetingWeb = m_ctx.Site.OpenWeb(url);
m_ctx.Load(meetingWeb, w => w.EffectiveBasePermissions);
m_ctx.ExecuteQueryRetry();
```
returns incorrect value for `High`. That probably leads to all other issues.

**Comment by AJIXuMuK** [comment]
One more update.
There is a difference on the results of `_api/web/effectiveBasePermissions` if I used it directly in the browser or in the custom app with access token.

If I use it from the browser, I getting something like that:
```xml
<d:EffectiveBasePermissions xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml" m:type="SP.BasePermissions">
<d:High m:type="Edm.Int64">2147483647</d:High>
<d:Low m:type="Edm.Int64">4294967295</d:Low>
</d:EffectiveBasePermissions>
```

The same user, but using the access token received from Azure AD:
```json
{"odata.metadata":"https://splst.sharepoint.com/sites/pervasent-o365/meets2/MeetingPack_25/_api/$metadata#SP.BasePermissions","High":"65712","Low":"1010539519"}
```

Access Token is correct. I'm requesting `AllSites.Manage` permissions.

**Comment by wobba** [comment]
What does permissionkind.fullMask yield?

**Comment by AJIXuMuK** [comment]
Sorry, @wobba, I didn't quite get your question...
`PermissionKind.FullMask` is an enum value... The value is 65.
Or do you want me to check `Has(PermissionKind.FullMask)` or something?..

**Comment by wobba** [comment]
I believe effectiveBasePermissions is a bitmask of those enums, so the Has() would bitmask check that.

**Comment by AJIXuMuK** [comment]
@wobba - right.
So, for both "access token" and "cookies" results `Has(PermissionKind.FullMask)` returns `false`.
For the one that I'm interested in (`PermissionKind.ManageWeb`):
"access token" returns `false`, but
"cookies" returns `true`.

Here is the code I used for test:
```javascript
var basePerms = new SP.BasePermissions();
basePerms.initPropertiesFromJson(effectiveBasePermissionsJson);
console.log(basePerms.has(SP.PermissionKind.fullMask)); // false for both access token and cookies
console.log(basePerms.has(SP.PermissionKind.manageWeb)); // false for access token, true for cookies
```

**Comment by wobba** [comment]
Seems weird indeed, and I'd expect both auth methods to yield the same. Thank you for adding more detail.

**Comment by AJIXuMuK** [comment]
Any updates?

**Comment by AJIXuMuK** [comment]
Any updates from Dev team?
It's kinda blocker if you try to work with SharePoint permissions from OAuth-authenticated apps.

**Comment by iNick** [comment]
@andrewconnell How can we help move this suspected bug forward toward a resolution? This is affecting several of our customers as well.

**Comment by andrewconnell** [comment]
@iNick Added two more labels that should have been there initially. Not much more I can do here... process is that if MSFT needs to review something, we tag it with the "status:to-be-reviewed". If it's impacting customers, suggest you/your customers open a support ticket with MSFT.

**Comment by stuartwil** [comment]
Is there any progress on getting this fixed?

**Comment by AJIXuMuK** [comment]
@iNick, @stuartwil - after long investigation I have an explanation and potential solution.

Your Azure AD App registration requests `AllSites.Manage` delegated permissions. And although the name implies managing of the sites, webs, etc. it actually allows to manage items, views, and some other operations.
To be more precise:
```
Microsoft.SharePoint.SPBasePermissions.ViewListItems | Microsoft.SharePoint.SPBasePermissions.AddListItems | Microsoft.SharePoint.SPBasePermissions.EditListItems | Microsoft.SharePoint.SPBasePermissions.DeleteListItems | Microsoft.SharePoint.SPBasePermissions.ApproveItems | Microsoft.SharePoint.SPBasePermissions.OpenItems | Microsoft.SharePoint.SPBasePermissions.ViewVersions | Microsoft.SharePoint.SPBasePermissions.DeleteVersions | Microsoft.SharePoint.SPBasePermissions.CancelCheckout | Microsoft.SharePoint.SPBasePermissions.ManagePersonalViews | Microsoft.SharePoint.SPBasePermissions.ManageLists | Microsoft.SharePoint.SPBasePermissions.ViewFormPages | Microsoft.SharePoint.SPBasePermissions.SubmitItems | Microsoft.SharePoint.SPBasePermissions.Open | Microsoft.SharePoint.SPBasePermissions.ViewPages | Microsoft.SharePoint.SPBasePermissions.ApplyThemeAndBorder | Microsoft.SharePoint.SPBasePermissions.ApplyStyleSheets | Microsoft.SharePoint.SPBasePermissions.ViewUsageData | Microsoft.SharePoint.SPBasePermissions.BrowseDirectories | Microsoft.SharePoint.SPBasePermissions.BrowseUserInfo | Microsoft.SharePoint.SPBasePermissions.AddDelPrivateWebParts | Microsoft.SharePoint.SPBasePermissions.UpdatePersonalWebParts | Microsoft.SharePoint.SPBasePermissions.UseClientIntegration | Microsoft.SharePoint.SPBasePermissions.UseRemoteAPIs | Microsoft.SharePoint.SPBasePermissions.CreateAlerts | Microsoft.SharePoint.SPBasePermissions.OpenWebOnly | Microsoft.SharePoint.SPBasePermissions.ViewItemsRequiresOpen
```

As a result, even site admin will not get the `ManageWeb` permissions when accessing SharePoint data using the access token from your app.

There are few options you could consider.

## Request `AllSites.FullControl` API Permissions in AAD App
These permissions require admin consent, but they give you a full mask for SharePoint permissions. As a result, when intersecting with a user permissions - you will receive actual permissions of the user.

## Use `Web.GetUserEffectivePermissions` API
This approach will throw an exception if a current user doesn't have an `enumeratePermissions` permission level. But in your case, as you're interested in `manageWeb` permissions, you could probably treat an exception as missing permissions.
