### ISSUE TITLE
Bash on Ubuntu on Windows, Webpack interface issue

### ISSUE THREAD

**Issue by JasonDunbar** [SharePoint/sp-dev-docs#57]
When running nodejs, npm and all the other goodies in Bash on Ubuntu on Windows, you'll likely receive the following Error when you run 'gulp serve':

`Error - [webpack] 'dist':
EINVAL: invalid argument, uv_interface_addresses
 @ ./lib/webparts/helloWorld/HelloWorld.module.css 1:14-94`

This appears to be due to a known issue in Bash on Ubuntu on Windows - [Bash on Windows os.networkInterfaces: EINVAL ](https://github.com/nodejs/node/issues/7150)

Despite the issue, you're able to open up a browser and go to the address to see the Workbench.

**Comment by StfBauer** [comment]
Thats correct. The support to evaluate the network interface is coming nad then it will work with yeoman and all the other NodeJS stuff as well.
I tested Yeoman on NodeJS in a pretty early stage and opened an issue on the [Bash On Windows](https://github.com/Microsoft/BashOnWindows/issues/468) project.

**Comment by patmill** [comment]
I'm not even going to pretend that I have anything worthwhile to contribute here.  Is there anything we can do in the framework or tooling to improve this scenario, or should I close this issue?

(On the plus side, the fact that we have people conversing about Bash, Ubuntu, Windows and SharePoint on a single page is a minor miracle I think)

**Comment by JasonDunbar** [comment]
I had initially looked to how I might add this to 'Known Issues' because although not directly related to the framework (at least not the cause), it'll no doubt be something that people run into and may not know the underlying cause.

Not an 'Issue' per se, but worth putting somewhere.

**Comment by StfBauer** [comment]
In additon you can note that the detection of network interfaces in currently not full supported by Bash on Windows.
Once it will be you have to open the browser manually because Bash On Windows is currently unable to launch a Windows process. I think it might be on the roadmap in the meantime.
