### ISSUE TITLE
Getting file from drive doesn't return @microsoft.graph.downloadUrl property.

### ISSUE THREAD

**Issue by slavag** [SharePoint/sp-dev-docs#5705]
Hi,
I'm trying to get file content. When I'm calling :
`GET /groups/{group-id}/drive/root:/{item-path}`
Response contains all information about the file, but no @microsoft.graph.downloadUrl field is returned. Also if in headers for the GET I don't put Prefer="apiversion=2.1" I'm getting error that item is not found (Tried in postman and code). 
If I change to :
`GET /groups/{group-id}/drive/root:/{item-path}:/content`
Then I'm getting 302 response with Location header with the URL, so now to be able to get content from Sharepoint file and validate that file downloaded is fine (using hash), I need to do 3 calls , first to get all file metadata, then call to get Location URL and then real call to get a content.

So, two issues:
1) Why I can't get @microsoft.graph.downloadUrl in /groups/{group-id}/drive/root:/{item-path}
2) Why without prefer header item is not found ?

Please advise. Thanks

**Comment by andrewconnell** [comment]
The issue template contained sections we ask you to complete to provide context, but you seem to have deleted them. Please resubmit your issue but complete the provided sections & clarify if this is a Graph / SharePoint REST question... if it's Graph, it should be posted to the Graph support as this repo is for SharePoint development topics.
