### ISSUE TITLE
Possible to deploy a Library component that is not tenant scoped?

### ISSUE THREAD

**Issue by jhholm** [SharePoint/sp-dev-docs#5706]
## Category

- [X] Question

## Question

I'm creating a SPFx Library component that provides functionality for multiple solutions. In the [tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial) you are instructed to use default values while scaffolding your library and thus enabling tenant wide deployment. **I did not enable tenant wide deployment**.

Development workflow works as intended and documented.

When trying to install the library app in a site collection, I get a similar error as in #829. **The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype**

I'm just guessing that only tenant wide deployment is supported. The tutorial nor the [overview](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview) does not mention this explicitly.

Am I correct that you must always use tenant wide deployment on a library component?

## Environment details (*development & target environment*)

- **Target Environment**: [SharePoint Online]
- **Tooling**: [SPFx v1.10.0]

**Comment by andrewconnell** [comment]
Library components can be deployed to site collection scoped app catalogs. The docs have been [updated recently](https://github.com/SharePoint/sp-dev-docs/pull/5611/files), but the live site has not yet been refreshed indicating this.

**Comment by jhholm** [comment]
Yeah, I read about that. So in that case you would need to deploy it to each site collection specifically and still use "tenant wide deployment", though it still works within that app catalog scope (site).

Just to make sure. My use case that I'm activating the app in a site collection is incorrect use of the library component? So the only way to get the library working is to enable tenant wide deployment in tenant or site collection app catalog usecase?

**Comment by jhholm** [comment]
If that is the case, it might be a good idea to update the documentation to specify explicitly that tenant wide deployment is required in the scaffolding process.
