### ISSUE TITLE
any guidance or samples for using oAuth2 authorization grant flow with spfx?

### ISSUE THREAD

**Issue by rmbw74** [SharePoint/sp-dev-docs#5714]
## Category

- [X ] Question

## Question

I am working on a webpart [spfx v 1.4.0 / react]  that is integrating with a 3rd party api that is using the oAuth2 Authorization Grant flow.  Does anyone have any recommendations for how to best implement this with an spfx webpart. 

Been looking for any spfx samples that may implement this but have been unsuccessful so far in finding one. 

One of the tricky things, and supposedly this has been implemented on the vendor side, is a way to do this flow without a popup that the user must click on everytime the webpart loads to authorize.
I've never dealt with oAuth2, and most resources seem to concentrate on how to implement this on the server side, but not on the client side. 
 

SharePoint Online
SPFx v1.40 (may upgrade current solution to 1.10 if needed)

**Comment by andrewconnell** [comment]
You can't... 

SPFx is a client-side solution. The only auth flow that's supported for client-side solutions ATM is the implicit flow.

The auth code flow involves a client secret... you can't include the secret in a client-side solution because it would no longer be a secret.

If you need to call a 3rd-party API that only supports the auth code flow, a common option people use is to create a proxy service that calls that 3rd-party API, secured with Azure AD, and call your proxy using the `AadHttpClient`.

**Comment by rmbw74** [comment]
Thanks for the response @andrewconnell - if I’m understanding the authorization grant flow correctly I would be Passing a client ID to the Auth server from the client which would return an authorization code. My initial though was to pass that code to a an azure function. The azure function would be handling the client secret thus not exposing it in the client. It would then use the Auth code and the client secret to generate a beater token. I’m guessing these oAuth client side libraries all expose the client secret?

**Comment by andrewconnell** [comment]
@rmbw74 said
> if I’m understanding the authorization grant flow correctly I would be Passing a client ID to the Auth server from the client which would return an authorization code

That's not completely correct... the app has to authenticate with the authorization endpoint (what you refer to as *auth server*). To do this, it passes a client ID **and client secret**.

Old post, but it explains the difference between each flow: https://www.andrewconnell.com/blog/looking-at-the-different-oauth2-flows-supported-in-azuread-for-office-365-apis/

Don't have perfect information (not knowing what endpoint you're calling), but the way I'd do it:

- SPFx app uses the `AadHttpClient` API to use the OAuth2 implicit flow to call your custom Azure Function
- your custom Azure Function uses the OAuth2 auth code flow / on-behalf-of / client credentials flow (to call the 3rd party API)

Yes... it's a hoop you have to jump through, but it's not SharePoint/SPFx specific... it's an aspect of client-side dev.

**Comment by rmbw74** [comment]
> Don't have perfect information (not knowing what endpoint you're calling), but the way I'd do it:

I'm trying to use the flow as shown here
[social chorus authorization](https://partner.socialchorus.com/authorization)

I believe the vendor is relying on the user having already logged into their platform via my company SSO.  When we hit the authorization endpoint, the user doesn't have to actually grant consent, if the user is logged into the platform the authorization endpoint simply spits out the code in the redirect url.  When I set this up via postman, the redirect first made me provide my SSO credentials.

**Comment by andrewconnell** [comment]
What I describe in my approach would work... the two OAuth2 flows they support are the two I mentioned. It is not possible to call their endpoint direct from a client-side component.

**Comment by rmbw74** [comment]
@andrewconnell  - thanks so much for your input. It helps. I guess the part of this that’s confusing me or I’m just not grasping is how the authorize endpoint is aware of the user context when it’s being handled via a proxy service.

**Comment by andrewconnell** [comment]
@rmbw74 said:
> I guess the part of this that’s confusing me or I’m just not grasping is how the authorize endpoint is aware of the user context when it’s being handled via a proxy service.

**It isn't**... you aren't missing anything. 

The 3rd-party endpoint has zero context about the current user. You'll have to dig into their docs a bit more to see if they support on-behalf-of (OBO)... but if not, you'll have to implement client credentials flow between the AF & 3rd-party API.

From the little I read from the link you shared (_sorry, this isn't really a consulting forum & I don't have the bandwidth to design out a solution :) _), it doesn't appear to support OBO... so you have to do client credentials. That means you'll have zero user context from your app. The [Azure AD docs have some info about OBO](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow for your learning, but that doesn't necessarily apply to the 3rd-party endpoint

**Comment by rmbw74** [comment]
Again, thank you @andrewconnell i appreciate your input.
