### ISSUE TITLE
Getting file from drive doesn't return @microsoft.graph.downloadUrl property

### ISSUE THREAD

**Issue by slavag** [SharePoint/sp-dev-docs#5715]
## Category

- [x] Bug

## Describe the bug

I'm trying to get file content. When I'm calling :
`GET /groups/{group-id}/drive/root:/{item-path}`
Response contains all information about the file, but no @microsoft.graph.downloadUrl field is returned:

    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('domain.sharepoint.com%2Ccc767111-cda2-4eb2-b42e-8836305f1420%2Cc0db7f82-b16f-4fe5-9885-7e434b11e5b8')/drives('b%22k4l2zKLNsk61Log2MF8UIBtTYFV52M5EtW4ZTyYF38gyZs2y-wOfSL0tPWbYys-4')/root/$entity",
    "createdDateTime": "2020-03-22T20:29:23Z",
    "eTag": "\"{0E8182EC-5EE9-41E6-96BA-372340F873CB},1\"",
    "id": "01J7TAN47MQKAQ52K64ZAZNORXENAPQ46L",
    "lastModifiedDateTime": "2020-03-22T20:29:23Z",
    "name": "A Survey of Applications of Markov Decision Processes.pdf",
    "size": 6590404,
    "webUrl": "https://domain.sharepoint.com/sites/Test/Shared%20Documents/A%20Survey%20of%20Applications%20of%20Markov%20Decision%20Processes.pdf",
    "cTag": "\"c:{0e8182ec-5ee9-41e6-96ba-372340f873cb},1\"",
    "createdBy": {
        "user": {
            "displayName": "Slava",
            "email": "slava@domain.onmicrosoft.com",
            "id": "1bf721e3-d0f7-4238-88a9-7e13f22efa01"
        }
    },
    "lastModifiedBy": {
        "user": {
            "displayName": "Slava",
            "email": "slava@domain.onmicrosoft.com",
            "id": "1bf721e3-d0f7-4238-88a9-7e13f22efa01"
        }
    },
    "parentReference": {
        "driveId": "b%22k4l2zKLNsk61Log2MF8UIBtTYFV52M5EtW4ZTyYF38gyZs2y-wOfSL0tPWbYys-4",
        "id": "01J7TAN123Y2GOVW7725BZO354PWSELRRZ",
        "path": "/drives/b%22k4l2zKLNsk61Log2MF8UIBtTYFV52M5EtW4ZTyYF38gyZs2y-wOfSL0tPWbYys-4/root:",
        "driveType": "documentLibrary"
    },
    "file": {
        "mimeType": "application/pdf",
        "hashes": {
            "quickXorHash": "cwjdhie41VYT6k3bdKT/y30bKX0="
        }
    },
    "fileSystemInfo": {
        "createdDateTime": "2020-03-22T20:29:23Z",
        "lastModifiedDateTime": "2020-03-22T20:29:23Z"
    }

Also if in headers for the GET I don't put 
`Prefer="apiversion=2.1"` header I'm getting error that item is not found (Tried in postman and code).

If I change to :
`GET /groups/{group-id}/drive/root:/{item-path}:/content`
Then I'm getting 302 response with Location header with the URL, so now to be able to get content from Sharepoint file and validate that file downloaded is fine (using hash), I need to do 3 calls , first to get all file metadata, then call to get Location URL and then real call to get a content.

So, two issues:

1. Why I can't get @microsoft.graph.downloadUrl in /groups/{group-id}/drive/root:/{item-path}
2. Why without prefer header item is not found ?

## Steps to reproduce
Issue 1: call :
`GET /groups/{group-id}/drive/root:/{item-path}`

Issue 2: call :
`GET /groups/{group-id}/drive/root:/{item-path}`
Without Prefer header.

## Expected behavior
1. I'm expecting @microsoft.graph.downloadUrl property to be returned when calling 
`GET /groups/{group-id}/drive/root:/{item-path}`
2. I'm expecting that header `Prefer="apiversion=2.1"` will not influence if item is found or not.

## Environment details (*development & target environment*)

Sharepoint Graph API call (code and postman)

### Additional context

Please adivse.
Thanks

**Comment by andrewconnell** [comment]
This question isn't about SharePoint, this is about Microsoft Graph. This issue list is for SharePoint development topics. Please use the Graph support options: https://developer.microsoft.com/en-us/graph/support
