### ISSUE TITLE
Link description

### ISSUE THREAD

**Issue by hwkwicre** [SharePoint/sp-dev-docs#5718]
The link says "Changes from SharePoint 2010 to SharePoint"
But the contents of the link only includes SharePoint Server 2016 and 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fb7a08-23fb-19a5-bc70-4026e555f971
* Version Independent ID: 9b42bd75-9353-fb33-e193-2be5d679aff8
* Content: [Search in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/search-in-sharepoint)
* Content Source: [docs/general-development/search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/search-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That bullet should be removed... the target doc only deals with "what's new" in the last two on-prem versions.

**Comment by JarbasHorst** [comment]
Sorry @andrewconnell I saw the help wanted tag and fixed the bug 😀 I didn't notice it was assigned to you!
