### ISSUE TITLE
Linebreak error

### ISSUE THREAD

**Issue by jesper-ego** [SharePoint/sp-dev-docs#5719]
There is a linebreak error in these lines

31 (UTC) Monrovia, Reykjavik
4 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna 6 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague 3 
(UTC+01:00) Brussels, Copenhagen, Madrid, Paris
57 (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb

3 should be the starting value on next line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac08219-6183-0904-50e6-682d748946fb
* Version Independent ID: 549cb147-3696-9a9a-f22e-ee76decf6e59
* Content: [SPRegionalSettings.TimeZones Property (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spregionalsettings.timezones?view=sharepoint-server#feedback)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by JarbasHorst** [comment]
The following values are displayed wrongly:
- 6 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
- 3 (UTC+01:00) Brussels, Copenhagen, Madrid, Paris

It looks like the markdown content gets generated from an XML file.

**Comment by andrewconnell** [comment]
Thanks... unfortunately we can't fix this from here, so I posted an issue on your behalf to the repo so the owners of the doc can look into it: https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/issues/71
