### ISSUE TITLE
Set extensions in specific order in Sharepoint Online

### ISSUE THREAD

**Issue by alexandradianachira** [SharePoint/sp-dev-docs#5721]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

>Hello, I am struggling now with an issue regarding 2 extensions. They are loading in the wrong order. I tried to add the sequence in the ClientSideInstance.xml and elements.xml, but it's not working. 
Setting the sequence in Tenant wide deployment list is not useful because we want to deploy both extensions only on specific site collections.
Do you have any other ideas for this?
Also, the counting from sequence starts from 0 or 1? 

Thank you a lot!

**Comment by OS-Lee** [comment]
Hi,
Did sample test(SPFx ClientSideComponentInstance Sequence property) while same result as https://github.com/SharePoint/sp-dev-docs/issues/4121.

So, try to provide feedback on[this](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37914715-use-sequence-parameter-to-sort-listview-command-se).

**Lee
Microsoft SharePoint Community Support**
