### ISSUE TITLE
Install solution to Outlook Web Access - Not able to follow this instruction

### ISSUE THREAD

**Issue by kboovaragan** [SharePoint/sp-dev-docs#5726]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am following the SharePoint Developer Tutorial, and developing sharepoint webparts.
In this tutorial, in a point, i am not able to follow the instruction as given in the heading "Install solution to Outlook Web Access", it is not clear, where / which part of the site will have such feature to upload my solution/package. Kindly help.
Link for your reference from where i am facing this difficulty.
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms459356(v=office.14)?redirectedfrom=MSDN

Other details, i have furnished in my earlier issue (#5645 - This issue is closed now), you can use the same....

*Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Thanks for the question. As the instructions state in that documentation, open up your outlook on the web. Open up (It says "Activate") an existing email in your inbox. 

Within the email, on the top right of the email you will see '...', select that and then select "Get Add-Ins".

**Comment by kboovaragan** [comment]
Thanks for the clarification. I am able to follow, still, i was not able to
get it in Inbox, i need to get into one of my email, to get to the [...]
context menu to proceed further, able to add the custom plug-in that i
created to my outlook email, thanks.
This issue can be closed....  Still the explanation there does not tell
clearly that we should go into one of our email in our inbox to add this
plug-in... that looks vague explanation on the site though....

Warm Regards,
Krishnasamy.

**Comment by bcameron1231** [comment]
Thanks @kboovaragan . If you'd like to make a change to the documentation for a bit more clarity, they are open source and you submit a PR if you think it would make it easier for others to understand the documentation. In the meantime, we'll close out this issue. Thanks!

@andrewconnell  #Please-Close
