### ISSUE TITLE
Issue with documentation Consume enterprise APIs secured with Azure AD in SharePoint Framework

### ISSUE THREAD

**Issue by JMTeamway** [SharePoint/sp-dev-docs#5727]
## Category

- [x] Bug

## Describe the bug
The Microsoft documentation to consume enterprise APIs secured with Azure AD in Sharepoint Framework can not be successfully followed.

At the point where we Grant access to the enterprise API (https://docs.microsoft.com/fr-fr/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi#grant-access-to-the-enterprise-api), the grant fails both with Azure portal UI and Powershell. 
Portal error :
`[HTTP]:400 - [CorrelationId]:06f7519f-30c6-2000-524d-0866b29e548f [Version]:16.0.0.20029`

Powershell error : 
```
Approve-SPOTenantServicePrincipalPermissionRequest : Nous n’avons pas trouvé de principal de service nommé juju-contoso-tuto-application-ad.
Parameter name: resourceName
Au caractère Ligne:1 : 1
+ Approve-SPOTenantServicePrincipalPermissionRequest -RequestId 6a88d62 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Approve-SPOTena...rmissionRequest], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.ApproveSPOTenantServicePrincipalPermissionRequest
```

## Steps to reproduce
Follow the tutorial provided here :
https://docs.microsoft.com/fr-fr/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi

## Expected behavior
I can follow the tutorial to the end.

## Environment details (*development & target environment*)
- **OS**: Win10
- **Target Environment**: SharePoint Online

### Additional context
Looks very much like the closed issue #2866.
All the possible causes seems not to apply in my case.
The names of all ressources are unique.
I checkef that the user_impersonation scope  is correctly set.

**Comment by JarbasHorst** [comment]
Hello @JMTeamway 

can you please confirm the name of the Azure AD application. The value of the resource property must refer to the name of the Azure AD application used to secure the API! If "juju-contoso-tuto-application-ad" hasn't been created in Azure AD as an application or was misspelled, you won't be able to approve it.

Regards,
Jarbas Horst

**Comment by JMTeamway** [comment]
Hello @JarbasHorst 

Here is the screenshot of my Azure Active Directory Express configuration with the correct name, created as specified in the documentation  :

![image](https://user-images.githubusercontent.com/42567407/81816577-d05b5400-952b-11ea-89fc-477e8549fc93.png)

**Comment by JMTeamway** [comment]
Still I noticed a strange behavior : 
the Azure Active Directory configuration was originally created as Express, but sometimes, if I open it after, I see it configured as Advanced although I never modified it this way.
So I set it back to express and save all configuration.

**Comment by bcameron1231** [comment]
Can you confirm whether the API is in the same Active Directory Tenant as your Office 365 tenant?

**Comment by JMTeamway** [comment]
Oh ! You got it, it is not !!! :-/

Then I guess I just have to follow the correct documentation "Consume multi-tenant enterprise APIs secured with Azure AD in SharePoint Framework" 💯 
https://docs.microsoft.com/fr-fr/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant

Thank you all for your help and incredible efficiency !

**Comment by bcameron1231** [comment]
Awesome, glad we got that worked out in a timely manner!
