### ISSUE TITLE
Support for rgba using theme tokens?

### ISSUE THREAD

**Issue by ianchursky** [SharePoint/sp-dev-docs#5728]
Is there a way to use rgba while using the theme tokens like [theme: themePrimary]? There's a way to do it with the SASS compiler if you give a valid HEX e.g. background-color: rgba(#333333, 0.5); but the compiler always complains when you throw in one of those string tokens.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations#use-theme-colors-in-your-customizations
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-theme-colors-in-your-customizations.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by StfBauer** [comment]
This is not supported because the theme token will be replaced during runtime and not during compile time. The SPFx solution will compile in the theme tokens as strings and the correspondent value.

**Comment by ianchursky** [comment]
Thank you for your quick response. I have a way to work around it but I was just wondering if there was something I was missing.
