### ISSUE TITLE
Limiting App Only Permissions

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#5730]
How do you limit which sites an application principal can access?  Granting Sites.FullControl.All is way too broad if you have an application that needs to work with data on a single site.  This goes against the best practice of least permissions - which is part of the Zero Trust principles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
Currently, There is no App Permission level which can set for a specific site collection, please refer the Permission list below:
[Microsoft Graph permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference)
Sites.FullControl.All is set to all site collections based on description:
![Image 1](https://user-images.githubusercontent.com/28797671/81909418-264bfc80-95fd-11ea-8fe2-4b0303cc0632.png)

**Comment by danmyhre** [comment]
Well this is leading to terrible security practices when you have an API that requires broad access and bypasses all application-layer security controls.

**Comment by Jerry0527** [comment]
Yes, this should be have a security issue if not limit to specific site collection.
However, currently, there is no available permission for this.
You can submit a UserVoice in the link below：

[Microsoft Graph Feature Requests](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests)

**Comment by andrewconnell** [comment]
@danmyhre said
> Well this is leading to terrible security practices when you have an API that requires broad access and bypasses all application-layer security controls.

All requests are coming from the client... and thus any permissions are tied to the TLD, not the site collection. ATM, it's not possible to limit the scope/permission to a specific site. This is more of a MSGraph question/issue than a SharePoint one and thus, not one we can address here (as this forum is for SharePoint development issues).

With that being said...

One solution is to use isolated web parts so the permission will only apply where that component is used: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts

I wouldn't recommend granting Sites.FullControl.All to the SPO AAD app that can return a token to the client... that's way too permissive IMHO for a client-side solution.
