### ISSUE TITLE
Problem getting Graph tokens inside Azure function called from SPFx Webpart

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#5734]
## Category

- [x] Question

## Question

I have the following scenario:
An SPFx Webpart is calling an Azure function (WebAPI) through AadHttpClient. The Azure function is set to require AAD Authentication. Inside the function a call to the Graph API is made, using the logged on user (delegated access, on-behalf-of).
This is working well when the user is using Firefox, Chrome or the chromium Edge browser.
It does not work, when the user is using the old Edge browser or IE11.
Apparently, the older Microsoft browsers have an issue with the SSO between the SPFx Webpart and the Azure function. After some investigation I found out that the "principal" object in the Azure function is always filled with the correct values, no matter what browser the user is using.
But to access Graph on behalf of the user an access token is needed. This access token is accessible inside the function through the 'X-MS-TOKEN-AAD-ACCESS-TOKEN' request token. But here is where the difference between the browsers shows up. Using the older browsers the token retrieved inside the function is invalid.
So I did some more investigations and found a difference in the call to the function:
Chrome and Firefox are sending a cookie named 'AppServiceAuthSession' which is not sent from Edge or IE. If I paste the url of the Azure function directly inside the address bar and go through authentication, then the function also works with the MS browsers. And this is also true when I access the function afterwards from that browser through the Webpart. The browser is then always adding the above mentioned cookie to the request. But that works only until I close the browser.
So the question is:
Is there any way to get full SSO working with the old Edge/IE11 browsers? I tried hard but couldn't find a way to force them to provide that cookie when sending the request to the function. Also I didn't find a way to get a valid token inside the function if it isn't already there automatically (the refresh token then doesn't work either…).

## Environment details (*development & target environment*)
- SharePoint online
- SPFx 1.10
- Azure function v3 (WebAPI, .netCore 3.x, AAD Auth forced)
- Microsoft Graph v1.0 endpoint

**Comment by andrewconnell** [comment]
MSFT browsers (IE / Edge) have a security [zone] setting... that's one difference. Maybe the Azure Function URL is not in the same security zone that's causing it to strip/block the cookie from the SPO site?

**Comment by cwdata** [comment]
Thanks for the suggestion @andrewconnell 
I tried with setting the SharePoint Url and the function Url both to 'Local Intranet' and afterwards to 'Trustworthy Sites'. Neither of them convinced the browser to send that cookie.
Any other idea I could try?

**Comment by andrewconnell** [comment]
Unfortunately not... let me ping engineering to see if they are aware or have an idea...

**Comment by andrewconnell** [comment]
Can you share more about your investigation (sorry, I'm not on Windows so I can't dupe easily). Screenshots showing the cookie sent & not sent from the different browsers? It will help with repro'ing and investigation...

**Comment by cwdata** [comment]
OK, first for the **SPFx part**:
The AadHttpClient is initialized by doing this:
`this.aadClient = await this.context.aadHttpClientFactory.getClient(this.properties.appId);`
and passed on to the React component.
Then the calls to the function inside the component:
The first call is done when the component is loading
```TypeScript
public async componentDidMount() {
    let options: IHttpClientOptions = {};
    options.mode = 'cors';
    options.headers = new Headers({ 'Content-Type': 'application/json', 'Accept': 'text/plain' });
    options.credentials = 'include';
    await this.props.aadClient.get("https://onedrivereadertest.azurewebsites.net/api/Function1?code=SomeSecretCodeForCallingTheFunction==&refresh=1", AadHttpClient.configurations.v1, options);
}
```
I also put that call in an iframe on the page
`<div style={{display:'none'}}><iframe src="https://onedrivereadertest.azurewebsites.net/api/Function1?code=SomeSecretCodeForCallingTheFunction==&refresh=1"></iframe></div>`
This is just for making sure that all cookies are ready when the actual call is made later on. The parameter 'refresh=1' instructs the function to do nothing other than immediately return 200 OK.
After the user clicks a button on the page the actual call that will access Graph through the function is made:
```TypeScript
let options: IHttpClientOptions = {};
options.mode = 'cors';  // CORS is enabled for the function app
options.headers = new Headers({ 'Content-Type': 'application/json', 'Accept': 'text/plain' });
options.credentials = 'include';  // include the AppServiceAuthSession cookie
await fetch("https://onedrivereadertest.azurewebsites.net/.auth/refresh", options);  // tell the function app to refresh the tokens
options.method = 'POST';  // could use GET as well -> same problem
options.body = JSON.stringify(this.props.settings);  // send some data
this.props.aadClient.post("https://onedrivereadertest.azurewebsites.net/api/Function1?code=SomeSecretCodeForCallingTheFunction==", AadHttpClient.configurations.v1, options).then((result) => { ..... }
```
The underlying App registration has the following permissions set:
![image](https://user-images.githubusercontent.com/26869201/82054279-f49b6a00-96be-11ea-9520-a53114412a84.png)
I also added the 'user_impersonation' scope to the 'oauth2Permissions' section.

Regarding the **Azure function**:
As said it is a v3 function using .net Core 3.1 and it is set up to enforce AAD authentication using the same App registration as mentioned above. In the CORS section the 'Enable Access-Control-Allow-Credentials' is enabled.
Additionally I added the part needed to automatically retrieve the graph tokens to it's config/authsettings section in the Azure resource explorer:
```
"additionalLoginParams": [
      "response_type=code id_token",
      "resource=https://graph.microsoft.com"
 ]
```
The code itself is retrieving the access token for Graph through:
```C#
[FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log, ClaimsPrincipal principal)
        {
            string accessToken = req.Headers["X-MS-TOKEN-AAD-ACCESS-TOKEN"];
            ....

```
This accessToken is then passed over to the GraphServiceClient from the Graph SDK and used there as a bearer token.

Now for **the results**:
This is all working nice and clean when using current versions of Chrome / Firefox and also Chromium Edge.
The request to /.auth/refresh works
![image](https://user-images.githubusercontent.com/26869201/82057205-49d97a80-96c3-11ea-956b-6899dcee4d4d.png)
![image](https://user-images.githubusercontent.com/26869201/82057943-56aa9e00-96c4-11ea-82c0-31362d51a063.png)

And accessing the function works:
![image](https://user-images.githubusercontent.com/26869201/82057553-cbc9a380-96c3-11ea-8c03-1504092bb4ff.png)
![image](https://user-images.githubusercontent.com/26869201/82058190-b1dc9080-96c4-11ea-9ec2-3e1ebf9792a8.png)

Using a Microsoft browser I get the following results:
On /.auth/refresh
![image](https://user-images.githubusercontent.com/26869201/82058464-14359100-96c5-11ea-8cce-4ad36d1d985e.png)
![image](https://user-images.githubusercontent.com/26869201/82059317-25cb6880-96c6-11ea-8e12-92c24978d49a.png)

And on the call to the function:
```
Microsoft.Graph.ServiceException: Code: InvalidAuthenticationToken
Message: Access token has expired.
```
![image](https://user-images.githubusercontent.com/26869201/82059002-c2413b00-96c5-11ea-905e-b2a44559f39b.png)

Please tell me if there is anything more needed.

**Comment by cwdata** [comment]
@andrewconnell,
did you get any update from engineering regarding that issue?

**Comment by patmill** [comment]
Hi, Sorry @cwdata .  With Edge and IE support being deprecated, we won't be making fixes or investigations in the area.
