### ISSUE TITLE
Deserializing Teams Tab configuration in a Web Part does not return the correct result. 

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#5736]
## Category

- [x] Bug

## Describe the bug

When using a Microsoft Teams tab as a Web Part (full page or normal) the settings is incorrectly deserialized. Instead of returning the dserialized setting of `entityId` SharePoint Online instead returns the value of the `contentUrl` instead.

This is how the `context` object looks like when running ` microsoftTeams.getContext((context) => {})` inside Microsoft Teams (the expected result of `entityId`):
![image](https://user-images.githubusercontent.com/5854279/81932811-a3bb4100-95ec-11ea-88fb-35961c0ec44d.png)

And this is when running the exact same code in SharePoint Online:
![image](https://user-images.githubusercontent.com/5854279/81932767-8f774400-95ec-11ea-8c40-8e525dab41a7.png)

## Steps to reproduce

1. Use a random tool to create a new Teams App with a tab 
2. In the Teams tab content page, use the Teams SDK to retrieve the current context (as shown above)
3. Test it in Teams
4. Add the Teams package to the SPO app catalog
5. Add the web part to a SPO page and see that it yields a different result

## Expected behavior

I expect that the serialized `entityId` is the same in both Microsoft Teams and SharePoint Online.

- **OS**: Windows 10
- **Target Environment**:  SharePoint Online
- **Browser(s)**: Chromium Edge v81
- **Tooling**:  VS Code, Yo Teams

**Comment by patmill** [comment]
Sorry @wictorwilen - this was missed due to some issue metadata inconsistencies.  Is this still an issue for you?

**Comment by wictorwilen** [comment]
@patmill - I have no idea, :-) Haven't fiddled with this for years. Just close it.

**Comment by patmill** [comment]
I tested first.  I can't get a repro, and the properties are persisting correctly.  I'll close it down.
