### ISSUE TITLE
Does not work in Microsoft Teams desktop app (SharePoint page added as a tab)

### ISSUE THREAD

**Issue by Mike61704** [SharePoint/sp-dev-docs#5739]
## Category

- [x] Bug

## Describe the bug

SharePoint webpart does not show all information when added in Teams tab. Our situation is that we have added a SharePoint site displaying events. Normally you can click the link to download an ICS and add the event to the calendar. The link is missing in the Teams Desktop App as a SharePoint tab.

## Steps to reproduce

1. Add webpart events to SharePoint site, create new event
2. In Teams desktop app, add new SharePoint tab, point to site with webpart
3. Add to Calendar does not display
4. No error. Works online but does not work in Teams Desktop app.

## Expected behavior

I expect to see the Add to my calendar link to download an ICS

## Environment details (*development & target environment*)

SharePoint Online, Teams desktop application

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: NET Framework v3.x 
- **Browser(s)**: Chrome | Chromium Edge
- **Tooling**: N/A
- **Additional details**: I do not know if this is a limitation on the Teams desktop application or a SharePoint display issue. 

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
@Mike61704 said:
> Framework: NET Framework v3.x

How are you creating the web part? Is this an old-style server-side web part or SPFx? In your context, you're saying server-side... is that correct?

**Comment by Mike61704** [comment]
Not server side. SPFx

**Comment by patmill** [comment]
Sorry for not closing this earlier.  This looks like a product issue, not something to do with SPFx / developer extensibility.  This is outside the scope of this issues list.
