### ISSUE TITLE
UrlUtilities import won't work with spfx webpart in typescript / react

### ISSUE THREAD

**Issue by brspnnggrt** [SharePoint/sp-dev-docs#574]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
I want to use the function "removeEndSlash" of the UrlUtilities class. When I import the UrlUtilities class I get an error loading the webpart

#### Observed Behavior
I'm using typescript/react template based on yeoman generator "@microsoft/sharepoint"
I get the following error on loading the webpart:

***The entry point for component "af8355b2-b0b6-4b8f-9e3f-8a8545859977" (TemplatePickerWebPart) has a dependency on "@microsoft/sp-lodash-subset" that is not declared in the manifest.
    at https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_nl-nl_fa852c62be2f51c90266a1c8a9ff508e.js:88:47516

#### Steps to Reproduce
Open a random spfx webpart, include the UrlProperties class 
import UrlUtilities from "@microsoft/sp-core-library/lib/url/UrlUtilities";
Use it like this:
let cleanTargetLocation = UrlUtilities.removeEndSlash(this.props.targetLocation);

**Comment by vman** [comment]
Hi @brspnnggrt 

You have to import the class from the package, like this:

```typescript
import { UrlUtilities } from '@microsoft/sp-core-library';
```

and then it works:
```typescript
console.log(UrlUtilities.removeEndSlash("https://localhost.com/")); //logs https://localhost.com
```

**Comment by iclanton** [comment]
If this doesn't work, please re-open this issue.
