### ISSUE TITLE
On-Premise Options?

### ISSUE THREAD

**Issue by contecc** [SharePoint/sp-dev-docs#5740]
This is a great reference but I can't see how to apply these modern theme to anything other than SharePoint Online.  What gives?  Can't I just manually upload the JSON somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4c91be-dca2-6411-b707-a023ad26306c
* Version Independent ID: 29ba4619-814e-784a-04a8-84b4d56933dd
* Content: [SharePoint site theming - JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-json-schema#feedback)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,

> Site designs and site scripts are currently only supported by SharePoint Online.

[official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)

**Lee
Microsoft SharePoint Community Support**

**Comment by iruletheworld** [comment]
> Hi,
> 
> > Site designs and site scripts are currently only supported by SharePoint Online.
> 
> [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
> 
> **Lee Microsoft SharePoint Community Support**

Hi, where to put the JSON script in the SharePoint Online site? I struggle to find the place in my site.

**Comment by JarbasHorst** [comment]
Hello @iruletheworld 

do you mean Site Script when you say JSON script? If yes, you can use PowerShell to create your Site Script as well as to associate it with a Site Design. Check out [this](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview#using-powershell-or-rest-to-work-with-site-designs-and-site-scripts) documentation for more information. Unfortunately, Microsoft doesn't provide an UI to manage Site Designs and Scripts!

I hope it helps.

Regards
Jarbas

**Comment by iruletheworld** [comment]
> Hello @iruletheworld
> 
> do you mean Site Script when you say JSON script? If yes, you can use PowerShell to create your Site Script as well as to associate it with a Site Design. Check out [this](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview#using-powershell-or-rest-to-work-with-site-designs-and-site-scripts) documentation for more information. Unfortunately, Microsoft doesn't provide an UI to manage Site Designs and Scripts!
> 
> I hope it helps.
> 
> Regards
> Jarbas

All right, that's it! I thought there was a place to put the JSON theme config through the UI. PS could be a problem if it needs local admin right to run the cmdlet and others.

Big thanks anyway!

**Comment by JarbasHorst** [comment]
Hello @iruletheworld

you don't need local admin rights to run Site Designs cmdlets. BTW, there is an open source tool called [Site Designs Studio V2](https://github.com/ypcode/site-designs-studio-v2) which you can use to manage Site Designs and Site Scripts directly from SharePoint.

Regards,
Jarbas

**Comment by iruletheworld** [comment]
@JarbasHorst 

Brilliant! Will give that a go! Thank you so very much!

**Comment by iruletheworld** [comment]
@JarbasHorst 

Turns out that I do need local admin right install the [SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps&redirectedfrom=MSDN) T_T
