### ISSUE TITLE
Unable to install Microsoft Graph API

### ISSUE THREAD

**Issue by mansoorgithub** [SharePoint/sp-dev-docs#5741]
Unable to install  Microsoft Graph API for my SharePoint framework:
 npm install @microsoft/microsoft-graph-types 
**Error:**
**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @microsoft/microsoft-graph-types@1.12.0
removed 11 packages, updated 1 package and audited 1858 packages in 60.134s
found 2724 vulnerabilities (2291 low, 34 moderate, 392 high, 7 critical)
run `npm audit fix` to fix them, or `npm audit` for details**

**Below are versions available in my machine:**

+-- @angular/cli@6.1.1
+-- @microsoft/generator-sharepoint@1.9.1
+-- gulp@4.0.2
+-- install@0.13.0
+-- json-server@0.14.0
+-- minimatch@3.0.2
+-- npm@6.12.0
+-- typescript@2.9.2
`-- yo@3.1.0

**Comment by andrewconnell** [comment]
Doesn't look like there's anything wrong. You installed the MS Graph NPM package... those are warnings, not errors from NPM. Have you looked in your project's **package.json** file to verify they are installed? Have you tried using the type declarations?

**Comment by andrewconnell** [comment]
In addition, you didn't fill out the issue template that contains sections for you to complete with context questions... that's required... please correct before we can move forward.
