### ISSUE TITLE
Update Create a multi-tenant enterprise API secured with Azure AD for AAD Authentication settings

### ISSUE THREAD

**Issue by rabwill** [SharePoint/sp-dev-docs#5751]
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Update to existing documentation

The documentation for [Create a multi-tenant enterprise API secured with Azure AD](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md) is awesome. No doubt it's helpful. But there have been some UI change in Azure Portal , for e.g  *On the Azure Active Directory Settings blade, choose the Manage Application button* I could not see the settings here  instead I had to go to the **App Registrations** to configure the App ID URL. 
Should this document be improved to update that tiny information to help developers speed up their process to set things up (if they are new and trying to build something) ? 
Happy to help update it as well. 
Thanks,
Rabia

**Comment by andrewconnell** [comment]
A big part of the docs are community driven...PR's are always welcomed!

**Comment by rabwill** [comment]
Thanks Andrew! I can take this up.

**Comment by JMTeamway** [comment]
Hi all !

I am currently struggling with the implementation of this documentation.

I think there are 2 issues in it ( distinct from navigation to mentionned screens ).

1. The code sample do not work ( or I was unable to make it work ;-) )
The code differs from the similar documenation "Consume enterprise APIs secured with Azure AD in SharePoint Framework" :
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md

The code given in this example works well. I think the documentation should be updated with this piece of code.

2. The method given to make the aure ad application multi tenant can nt be followed
The screenshots and menu given in the doc are not available to me.
See #5732 for details

I will contribute if needed, but today I just can't get the feature working myself ...

**Comment by rabwill** [comment]
Working on this @andrewconnell today as promised.
