### ISSUE TITLE
Column formatting show html

### ISSUE THREAD

**Issue by Jenny-Neal** [SharePoint/sp-dev-docs#5752]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I've setup a list in SharePoint Online and one of the columns contains html which I would like to be displayed, is this possible?  I've had a look through the documentation, but can't see anything that will use the html that is already set as a value of a column.

## Environment details (if applicable)

- **OS**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: JSON column formatting
- **Browser(s)**: Edge
- **Tooling**: [n/a]
- **Additional details**: 

*Thanks for your contribution! Sharing is caring.*

**Comment by kongmengfei** [comment]
Hi Jenny-Neal,

Column formatting does not support this functionality of rendering field value as html. I have tried it with [Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#create-an-extension-project). I just insert below code in the extension, it works well here:

![1](https://user-images.githubusercontent.com/57654821/82290964-a5b14580-99da-11ea-994b-83cd950d85bb.jpg)

`event.domElement.innerHTML= ${event.fieldValue};`

Thanks
Baker Kong
Microsoft SharePoint Community Support
