### ISSUE TITLE
Error TS2345 While Connecting Client side-web to SPFx

### ISSUE THREAD

**Issue by najwa-prog** [SharePoint/sp-dev-docs#5753]
### Error

- [Error - [tsc] src/webparts/helloWorld/HelloWorldWebPart.ts(30,55): error TS2345: Argument of type '(test: any) => any' is not assignable to parameter of type 'string'.] 

Hello, I am very new to SPFx . I am following the guidelines on how to connect a client side web part to Sharepoint as per the below link : 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint

By following the guideline and updating the public render() I get the below error 

<img width="1375" alt="Screen Shot 2020-05-16 at 8 56 55 PM" src="https://user-images.githubusercontent.com/63407921/82127999-d1081a80-97b7-11ea-9b61-08c4b6970c0c.png">

## Steps to reproduce

1. Go to 'Switch to Visual Studio code (or your preferred IDE) and open src\webparts\helloWorld\HelloWorldWebPart.ts.'
1. Click on 'Inside the render method, replace the innerHTML code block with the following code:'

1. See error: It Is not recognising the Type test 

<img width="1248" alt="Screen Shot 2020-05-16 at 8 36 07 PM" src="https://user-images.githubusercontent.com/63407921/82127759-58ed2500-97b6-11ea-95c4-795bccace28d.png">

## Expected behavior

I should have no errors and be able to render any website context and import the its lists

## Environment details (*development & target environment*)

- **Mac**:
- **SharePoint Online**: 
- **Node.js**:
- **Safari**
- **Visual Studio 2019**:

**Comment by najwa-prog** [comment]
I succeeded in exporting my lists as I changed the export of list from test to string

**Comment by bcameron1231** [comment]
@najwa-prog  Thank you. Sounds like you got this resolved and this ticket can be closed?

**Comment by najwa-prog** [comment]
> @najwa-prog Thank you. Sounds like you got this resolved and this ticket can be closed?

Hi Bcameron , well I got it resolved as I replaced

**<p class="${ styles.description }">${escape(this.properties.test}</p>**

With 

<p class="${ styles.description }">${escape(this.properties.title)}</p>

Don't know if it is a good action. But of you think so yes you can close the ticket. 

Thank you. 
Najwa.

**Comment by andrewconnell** [comment]
@najwa-prog the `properties` object is the interface of the web part properties... see the web part class declaration. This interface is defined above the web part in the same file.

You were referencing a property `test` that either didn't exist or was the wrong type (`any`) where the `escape` function requires a `string` as an argument. The error you were seeing was saying exactly what the problem was.
