### ISSUE TITLE
PnP PeoplePicker not working on full names

### ISSUE THREAD

**Issue by jnimmala** [SharePoint/sp-dev-docs#5758]
## Category

- [x] Bug

## Describe the bug

Hello All, Below is the PnP Peoplepicker control code that I'm using. The issue that I'm having here is with space-character within the name. Say I have valid user "Rachel Green". If I type-in "Rachel" I get 40 different Rachel's. So I continue to type "Rachel " or "Rachel G" or "Rachel Green", I get no results found. Is there anyway to deal with space-char or able to search based on full name. (If I go by last name i.e Green, since I have only one colleague with Green I'm able to pick correct name).

```
                <PeoplePicker
                         peoplePickerCntrlclassName=""
                         context={this.props.context}
                         titleText=""
                         personSelectionLimit={1}
                         groupName={""}
                         showtooltip={false}
                         suggestionsLimit = {10}
                         disabled={false}
                         selectedItems={this._getSelectedProfile}
                         principalTypes={[PrincipalType.User]}
                         defaultSelectedUsers={this.state.defaultUser}
                         resolveDelay={1000}
                         errorMessage={this.state.required}
                       /> 
```
## Expected behavior
Able to select user by full name with space character in between first and last name

## Environment details (*development & target environment*)
Prod tenant 

Thank you for your time

**Comment by bcameron1231** [comment]
Thank you for the question. As this is a question relating to the PnP React-Reusable-Controls, the best place for asking this question and getting support would be over in the SP-Dev-Fx-Controls-React repository. 

https://github.com/pnp/sp-dev-fx-controls-react/issues

**Comment by jnimmala** [comment]
thanks @bcameron1231 https://github.com/pnp/sp-dev-fx-controls-react/issues/565
