### ISSUE TITLE
Taxonomy Timer job for SyncHiddenList

### ISSUE THREAD

**Issue by jnimmala** [SharePoint/sp-dev-docs#5759]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Hello - I'm looking for some documentation around SyncHiddenList for taxonomy in SharePoint Online. For below scenario, in earlier versions of SharePoint we used to have timerjob which used to take care of  TaxonomySession.SyncHiddenList(site). Do we have this in SP Online ? If not, what's the alternative ?  
 
Lets suppose if 10 documents are tagged to TermA and 10 documents are tagged to TermB. If we plan to merge TermA with TermB, TermA will be added as a synonym to TermB. We'd like to make sure by merging terms, we're not loosing capability of search/highlighted webpart to bring the content tagged with pre-merged tags.

## Environment details (*development & target environment*)
In our production tenant, I don't think this timer job is running 

Thank you for your time !

**Comment by andrewconnell** [comment]
This repo is for developer-specific questions... this would be best suited for the tech community forums
