### ISSUE TITLE
code blocks inside tables should be moved out of the tables

### ISSUE THREAD

**Issue by davidchesnut** [SharePoint/sp-dev-docs#576]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
This topic has tables in which code examples are shown side-by-side. https://dev.office.com/sharepoint/docs/general-development/optimize-page-performance-in-sharepoint 

This isn't the best way to show them using markdown. Especially because there is no clear visual boundary between the samples next to or below each other. They tend to visually connect. It would probably be better to show them in sequential order and not use the tables.

#### Observed Behavior
Code side by side in tables doesn't scan well visually.

#### Steps to Reproduce
Scroll down to the tables with code in them.

**Comment by Linda-Editor** [comment]
I moved the code out of what were Tables 3 and 4; the other tables looked okay. I also updated the Note styles and added breaks to improve readability.

I made my changes here: https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/optimize-page-performance-in-sharepoint.md

**Comment by Linda-Editor** [comment]
@davidchesnut @VesaJuvonen (see last comment)

**Comment by Linda-Editor** [comment]
I found this issue hadn't been closed, so am closing it.
