### ISSUE TITLE
Can't upload photos from mobile devices.

### ISSUE THREAD

**Issue by shamwoox** [SharePoint/sp-dev-docs#5761]
Uploading photos from computers work fine but it doesn't work from mobile devices such as smartphones and tablets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you provide more context? There's not much go on... please share context & expand on "doesn't work"

**Comment by shamwoox** [comment]
I am trying to attach a photo to a SharePoint list item. In my AJAX call, I am passing the array buffer to data. On my computer, attaching photos work and actually attaches the file to a SharePoint list item. On mobile devices, it seems to work and calls the success function but actually doesn't attach anything to the SharePoint list item. This problem seems to only occur with images.

```
function readFile() {
	var element = document.getElementById('add-photo');
	//Get File Input Control and read the file name
	var file = element.files[0];
	var fileName = element.files[0]['name'];
	//Read File contents using file reader
	var reader = new FileReader();
	reader.onload = function(e) {
		attachFile(e.target.result);
	};
	reader.onerror = function(e) {
		alert(e.target.error);
	};
	reader.readAsArrayBuffer(file);
}

$.ajax({
	url: `${site}/_api/web/lists/getbytitle('List_Name')/items(${id})/AttachmentFiles/add(FileName='${fileName}')`,
	method: 'POST',
	binaryStringRequestBody: true,
	processData: false,
	headers: {
		accept: 'application/json;odata=verbose',
		'content-type': 'application/json;odata=verbose',
		'X-RequestDigest': data.d.GetContextWebInformation.FormDigestValue
	},
	data: content,
	success: function() {
	        alert("Success");
	},
	error: function(err) {
		alert('DID NOT ATTACH FILE: ' + JSON.stringify(err));
	}
});
```
