### ISSUE TITLE
No command to set a custom message for access request page

### ISSUE THREAD

**Issue by heitbaum** [SharePoint/sp-dev-docs#5762]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

As per Issue #2597 this is still outstanding.
Could you please reopen #2597

Since about March 2018 it is possible to set a custom message at the access request page GUI in Sharepoint Online. See Screenshot here.

Since we are setting up our Sharepoint Webs using PnPPowershell, we want to add a message here using powershell. Since March I am monitoring the changelog and the Documentation of Set-PNPRequestaccessmails, but there does not seem to be any change or addition here.

Am I missing something? Is there a pnp powershell command available to change the custom message for access request page? Is it on the roadmap?

## Environment details (*development & target environment*)

- **Target Environment**: SharePoint Online

**Comment by andrewconnell** [comment]
Thanks for the question, but this seems directly related to the PnP PowerShell suite a cmdlets. Please post your question to their repo as this forum is for SharePoint development related topics.

https://github.com/pnp/PnP-PowerShell
