### ISSUE TITLE
Button Elements appearing in panel with borders

### ISSUE THREAD

**Issue by rmbw74** [SharePoint/sp-dev-docs#5764]
## Category

- [x] Bug

## Describe the bug

SPFx 1.4.0 webpart has begun showing black borders around button elements.

## Steps to reproduce

1. Navigate to page with deployed webpart
1. open panel that contains button element
1. observe black borders around button elements

## Expected behavior
There should be no black borders around button elements that are not specified in CSS

## Environment details (*development & target environment*)

- **OS**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: React 16.3.2
- **Browser(s)**: Chrome v81 | IE v11 |  Chromium Edge v80
- **Tooling**: SPFx v1.4.0 
- **Additional details**: *
  "dependencies": {
    "@microsoft/applicationinsights-web": "^2.0.0-rc4",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "react": "16.3.2",
    "react-dom": "16.3.2"
  },
  "resolutions": {
    "@types/react": "16.4.2"
### Additional context

This may be related to previous issues reported in #5763 
Possible regression of #4911

*Thanks for your contribution! Sharing is caring.*

**Comment by KevinTCoughlin** [comment]
@rmbw74 can you provide the isolated HTML markup that exhibits this problem so that I can repro?

Additional questions:

- Do you have `loadLegacyFabricCss: true` specified in your SPFx `1.4.0` manifest? 
- Do you the following CSS asset, `chunk.legacy-third-party-fabric-core.css` requested in the browser's "Network" pane?

**Comment by KevinTCoughlin** [comment]
@rmbw74, I will create a repro based on `1.4.0` SPFx as you shared above with the manifest flag specified. I will render thru Fabric's `<Button />` thru React unless you have some prop overrides to share from your solution.

**Comment by Encodian** [comment]
@KevinTCoughlin @rmbw74 
I just scaffolded a new 1.10.0 solution... relevant code below, where I've just added the CommandBar control and some data:
![image](https://user-images.githubusercontent.com/45834050/82993990-5c27b280-9ff9-11ea-9593-4df86c808ad8.png)
Via the workbench:
![image](https://user-images.githubusercontent.com/45834050/82994039-6d70bf00-9ff9-11ea-8e52-7d0b7164a438.png)
Via SharePoint post packaging and deployment:
![image](https://user-images.githubusercontent.com/45834050/82994166-a01ab780-9ff9-11ea-828a-d25a1d0120c3.png)

I will check the questions/suggestions and update shortly.

**Comment by rmbw74** [comment]
@KevinTCoughlin 
> * Do you have `loadLegacyFabricCss: true` specified in your SPFx `1.4.0` manifest? It should be unnecessary since it is `< 1.8.2`, but I want to repro 1-1.

No, we do not have this specified in the manifest

> * Do you the following CSS asset, `chunk.legacy-third-party-fabric-core.css` requested in the browser's "Network" pane?

No, the only file I see with chunk.legacy is the following
https://spoprod-a.akamaihd.net/files/sp-client/chunk.legacy-third-party-fabric-core-localfont_none_5799920ee18b33249af2.js

**Comment by rmbw74** [comment]
`<Fabric>
          <DefaultButton className={styles.adminPanel_button} onClick={this._showPanel}
            text='Admin Access' />

          <div className={styles.launchpad}>
            <Panel
              className={styles.adminH}
              headerClassName={styles.adminHeader}
              isOpen={this.state.showAdminPanel}
              onDismiss={this._hidePanel}
              type={PanelType.large}
              headerText='LaunchPad Admin'
              closeButtonAriaLabel='Close'
            >
              <div >
                <DefaultButton
                  className={styles.greenButtonNewLink}
                  onClick={this._newLink}
                  text='Add New Link' />
              </div>
      // remainder of panel content here

 

`

**Comment by rmbw74** [comment]
Just curious if there has been any movement on this. We are still seeing this behavior with our webpart

**Comment by rmbw74** [comment]
This is now happening in my SPFx 1.10 solutions defaultbutton components. @andrewconnell @KevinTCoughlin 
![2020-08-05 07_20_47-Window](https://user-images.githubusercontent.com/15833201/89412289-68f90e80-d6ec-11ea-9bd5-8431f8294997.jpg)

**Comment by patmill** [comment]
Hi @rmbw74 - it looks like this got lost in some metadata shuffle.  Is this issue still showing up for you in recent builds?
