### ISSUE TITLE
Conditional Background Color Formula in tileProps not loading properly (List View JSON Formatting)

### ISSUE THREAD

**Issue by jvaleros** [SharePoint/sp-dev-docs#5767]
## Category

- [x] Bug

## Describe the bug

Background conditional color using an if formula for a single choice field works only some of the time. The rest of the time JSON does not even load, and thus the list shows a blank page. This formula I am using was provided by @thechriskent, but didn't seem to solve the issue.

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. Go to 'a list that has a tileProps JSON list view formatting'
1. Click on 'the tile view'
1. Add JSON background color to the style inside the children of the formatter div 
`"background-color": "=if(toLowerCase([$Status]) == 'pending', '#98FB98', if(toLowerCase([$Status]) == 'reviewed', '#FFEC8B', if(toLowerCase([$Status]) == 'referred for review', '#FF6F61', '')))"`
1. Save the JSON
1. Update the page, and it will show a blank page. Click on any other view, and click back on the tile view you just formatted, you should now see the formula.
## Expected behavior

The formula should be loaded every single time regardless of how you access the list view. If I set this tile view as the default view for the list it should still format correctly.
## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**:  Chrome v79 
- **Tooling**: VS Code

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by thechriskent** [comment]
I'm having trouble recreating this. I created a simple format that seems to work regardless of refresh. Could you give this a try and confirm if you are still seeing the issue?

```JSON
{
  "tileProps": {
    "width": "80",
    "height": "80",
    "formatter": {
      "elmType": "div",
      "txtContent": "Wowee!",
      "style": {
        "background-color": "=if(@rowIndex % 2 == 0, 'steelblue', 'teal')"
      }
    }
  }
}
```

![screenshot of simple format](https://user-images.githubusercontent.com/8364109/82474447-11f27e80-9a99-11ea-9d94-d2e83055e063.png)


If the above format works consistently, could you provide the full format you are using? Thanks!

**Comment by jvaleros** [comment]
Thanks for you quick response, I can confirm the last code snippet provided works as intended all the time. I think I found the reason why the background-color was only applying half them time, was due to an override of the class using some sp-color class.
