### ISSUE TITLE
Is this feature Generally Available on all tenants now?

### ISSUE THREAD

**Issue by pawanjajoo** [SharePoint/sp-dev-docs#5768]
Please include the status of this feature to better understand the availability. I am not able to see the "Edit conditional formula" section for columns on my lists and libraries. Seems that this feature is not yet GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#feedback)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Tim-5000** [comment]
We also do not have conditional access available for "Show/hide" columns in our lSharePoint Online lists and libraries
