### ISSUE TITLE
Getting Bad Request with the File CheckOut REST API

### ISSUE THREAD

**Issue by ChineduOkoronkwo** [SharePoint/sp-dev-docs#5773]
## Category

- [X ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## DotNet Core, DotNet Standard 2. 0

- **OS**: Windows 10
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: NET Core v2.0
- **IE v11 | Edge
- **Tooling**: Visual Studio 2019
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

I am able to download and checkout a file using the link http://tfs/sites/DefaultCollection/Test Project/Dev/Functional/testDoc.docx

I am working on a code that will do the checkout but each time I run the code from I receive the 404 error "Bad Request". What could be wrong with my code?

Below is the code doing the check out

public void CheckOutFile(string site, string folderName, string fileName)
        {
            site = site.EndsWith("/") ? site.Substring(0, site.Length - 1) : site;
            string siteRelativeUrl = null;
            if (site.Split('/').Length > 3)
            {
                siteRelativeUrl = "/" + site.Split(new char[] { '/' }, 4)[3];
            }
            else
            {
                siteRelativeUrl = "";
            }
            
            string api = $"{site}/_api/web/GetFileByServerRelativeUrl('{siteRelativeUrl}/{folderName}/{fileName}')/CheckOut()";
            Uri endPointUri = new Uri(api);
            WebRequest req = WebRequest.Create(endPointUri);
            req.Method = "POST";
            req.Credentials = CredentialCache.DefaultCredentials;
            var response = req.GetResponse();
        }

and below is the calling code:

public void SharePointTest()
        {
            string targetSite = "http://tfs/sites/DefaultCollection/Test Project/Dev";
            string folderName = "Functional";
            string fileName = fileName = "testDoc.docx";            
            CheckOutFile(targetSite, folderName, fileName);
        }

**Comment by OS-Lee** [comment]
Hi,

Sample tested code in my local SharePoint 2013 for your reference.
`class Program
    {
        public static string GetFormDigest(string sConnStr)
        {
            string sFormDigest = null;            
            Uri oUri = null;
            oUri = new Uri(sConnStr + "/_api/contextinfo");

            HttpWebRequest oWebRequest = HttpWebRequest.Create(oUri) as HttpWebRequest;
            oWebRequest.UseDefaultCredentials = true;
            oWebRequest.Method = "POST";
            oWebRequest.Accept = "application/json;odata=verbose";
            oWebRequest.ContentLength = 0;
            oWebRequest.ContentType = "application/json";
            string sResult;
            WebResponse sWebReponse = oWebRequest.GetResponse();

            using (StreamReader sr = new StreamReader(sWebReponse.GetResponseStream()))
            {
                sResult = sr.ReadToEnd();
            }

            var jss = new JavaScriptSerializer();
            var val = jss.Deserialize<Dictionary<string, object>>(sResult);
            var d = val["d"] as Dictionary<string, object>;
            var wi = d["GetContextWebInformation"] as Dictionary<string, object>;
            sFormDigest = wi["FormDigestValue"].ToString();

            return sFormDigest;

        }
        public static void CheckOutFile(string site, string folderName, string fileName)
        {
            site = site.EndsWith("/") ? site.Substring(0, site.Length - 1) : site;
            string siteRelativeUrl = null;
            if (site.Split('/').Length > 3)
            {
                siteRelativeUrl = "/" + site.Split(new char[] { '/' }, 4)[3];
            }
            else
            {
                siteRelativeUrl = "";
            }            

            string api = $"{site}/_api/web/GetFileByServerRelativeUrl('{siteRelativeUrl}/{folderName}/{fileName}')/CheckOut()";
            var endPointUri = new Uri(api);
            var req = WebRequest.Create(endPointUri);
            req.Method = "POST";
            req.ContentLength = 0;
            req.Headers.Add("X-RequestDigest", GetFormDigest(site));
            //req.Credentials = CredentialCache.DefaultCredentials;
            req.Credentials = new NetworkCredential("administrator", "password", "domain");
            var response = req.GetResponse();
            Console.WriteLine("---");
        }
        static void Main(string[] args)
        {
            string targetSite = "http://sp2019:12001";
            string folderName = "MyDoc";
            string fileName = "test.docx";
            CheckOutFile(targetSite, folderName, fileName);
        }
    }`

**Lee
Microsoft SharePoint Community Support**

**Comment by ChineduOkoronkwo** [comment]
Hi Lee,
Thanks for the swift response. 
Prior to getting your email, I got the code working up to the point that the error I receive is "(403) FORBIDDEN".
I have implemented exactly what you sent and here is what happens:
- With "req.Headers.Add("X-RequestDigest", formDigest)" it returns error "(400) BAD REQUEST"- If I remove the code porting above, it goes back to "(403) FORBIDDEN"..
I'd also like to point out that I changed the JSON deserialization in the GetFormDigest because the value was null when I ran it. Below is the what I changed it to (and I used Newtonsoft.Json instead of Nancy).
var val =                JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, Dictionary<string, object>>>>(sResult);            sFormDigest = val["d"]["GetContextWebInformation"]["FormDigestValue"].ToString();
403 means that I am not authorized to do checkout but I am able to checkout documents outside the application and this is what worries me. Thanks for further assisting.
Alfred Okoronkwo.
    On Thursday, May 21, 2020, 01:55:48 AM EDT, Lee_MSFT <notifications@github.com> wrote:  
 
 


Hi,

Sample tested code in my local SharePoint 2013 for your reference.
`class Program
{
public static string GetFormDigest(string sConnStr)
{
string sFormDigest = null;
Uri oUri = null;
oUri = new Uri(sConnStr + "/_api/contextinfo");
        HttpWebRequest oWebRequest = HttpWebRequest.Create(oUri) as HttpWebRequest;
        oWebRequest.UseDefaultCredentials = true;
        oWebRequest.Method = "POST";
        oWebRequest.Accept = "application/json;odata=verbose";
        oWebRequest.ContentLength = 0;
        oWebRequest.ContentType = "application/json";
        string sResult;
        WebResponse sWebReponse = oWebRequest.GetResponse();

        using (StreamReader sr = new StreamReader(sWebReponse.GetResponseStream()))
        {
            sResult = sr.ReadToEnd();
        }

        var jss = new JavaScriptSerializer();
        var val = jss.Deserialize<Dictionary<string, object>>(sResult);
        var d = val["d"] as Dictionary<string, object>;
        var wi = d["GetContextWebInformation"] as Dictionary<string, object>;
        sFormDigest = wi["FormDigestValue"].ToString();

        return sFormDigest;

    }
    public static void CheckOutFile(string site, string folderName, string fileName)
    {
        site = site.EndsWith("/") ? site.Substring(0, site.Length - 1) : site;
        string siteRelativeUrl = null;
        if (site.Split('/').Length > 3)
        {
            siteRelativeUrl = "/" + site.Split(new char[] { '/' }, 4)[3];
        }
        else
        {
            siteRelativeUrl = "";
        }            

        string api = $"{site}/_api/web/GetFileByServerRelativeUrl('{siteRelativeUrl}/{folderName}/{fileName}')/CheckOut()";
        var endPointUri = new Uri(api);
        var req = WebRequest.Create(endPointUri);
        req.Method = "POST";
        req.ContentLength = 0;
        req.Headers.Add("X-RequestDigest", GetFormDigest(site));
        //req.Credentials = CredentialCache.DefaultCredentials;
        req.Credentials = new NetworkCredential("administrator", "password", "domain");
        var response = req.GetResponse();
        Console.WriteLine("---");
    }
    static void Main(string[] args)
    {
        string targetSite = "http://sp2019:12001";
        string folderName = "MyDoc";
        string fileName = "test.docx";
        CheckOutFile(targetSite, folderName, fileName);
    }
}`

Lee
Microsoft SharePoint Community Support

**Comment by OS-Lee** [comment]
Hi,

I tested the code in my SharePoint 2013, it works fine. Make sure the request for digest is correct:

`oUri = new Uri(sConnStr + "/_api/contextinfo");`

The url should be like http://yoursite/_api/contextinfo,

**Lee
Microsoft SharePoint Community Support**
