### ISSUE TITLE
SPFx WebPart cannot be added as a SPA

### ISSUE THREAD

**Issue by holmesrm23** [SharePoint/sp-dev-docs#5777]
## Category

- [x] Bug

## Describe the bug

A SPFx webpart added as a SingleWebPartAppPage using the UI results in a breaking bug; does not display webpart.

**Error: ***The value for "IFramedWebPartController is undefined" must not be undefined
in t in t in o in t in t in t in t in t in section in div in div in t in Styledt in t in o in t in t in t

## Steps to reproduce

1. Create a webpart using the SharePoint Framework
2. Configure supported hosts: `  "supportedHosts": ["SharePointWebPart", "SharePointFullPage", "TeamsTab"],
`
3. Create Single App page using the UI
4. Navigate to new page: error

## Expected behavior

I should see my webpart alone on a page. The webpart looks fine as a webpart placed on any other page type.

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: SharePoint Framework 1.10.0, Node v10.18.0
- **Browser(s)**: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- **Tooling**: VSCode

**Comment by bcameron1231** [comment]
Duplicate #5357
