### ISSUE TITLE
Enter invalid condition

### ISSUE THREAD

**Issue by Laul0** [SharePoint/sp-dev-docs#5778]
## Category

- [x] Bug

## Describe the bug

The formula seems never valid.

## Steps to reproduce

1. Create custom SPList
2. Create three *choice* columns (with choices)
3. From the list, click on **New** then from the panel, **Edit form** and **Edit columns**
4. Click on the _ellipsis_ of the second choice column and **Edit conditional formula**
5. Type de formula
    ```
    =if([$Provider]=='Microsoft','true','false')
    ```
6. Click Save

At this point, the "error" message appear: "Enter invalid condition"

<img width="357" alt="Screen Shot 2020-05-21 at 09 30 38" src="https://user-images.githubusercontent.com/15279205/82563950-ee394200-9b45-11ea-9035-54e2d5bdc782.png">

- Internal name and display name of the columns are the same
- The value exist

> Note: if the `[$Provider]` is changed by `@currentField` the formula is valid

## Expected behavior

The formula seems good so, the conditional should be saved.

## Environment details (*development & target environment*)

- **OS**: MacOS 10.15.x
- **Target Environment**: SharePoint Online
- **Browser(s)**: Chromium Edge v84

### Additional context

n/a

**Comment by andrewconnell** [comment]
This is more of an OOTB feature in SPO... as such you should post the question to TechCommunity as this forum is for custom SP dev related issues...
