### ISSUE TITLE
Check Fullmask Permission and the Bitwise JS Limit

### ISSUE THREAD

**Issue by SimpleBase** [SharePoint/sp-dev-docs#5787]
## Category

- [x] Bug

## Describe the bug

I use SPFx 1.4 on an SP2019 Environment and want to check the permissions for an user (this.context.pageContext.web.permissions) and if the user has full mask. In my case I have full mask. The values are right: High: "2147483647", Low: "4294967295" BUT the hasPermission-Function returns everytime false. 

`permission.hasPermission(SPPermission.fullMask) //returns false`

When I go to the definition of this Function, it looks like this:

`SPPermission.prototype.hasPermission = function (requestedPerm) {
        return requestedPerm &&
            ((requestedPerm.value.Low & this.value.Low) === requestedPerm.value.Low) &&
            ((requestedPerm.value.High & this.value.High) === requestedPerm.value.High);
    };`

This condition returns true: 

`(requestedPerm.value.High & value.High) === requestedPerm.value.High`

But this one returns false:

`(requestedPerm.value.Low & value.Low) === requestedPerm.value.Low`

The reason is, that the bitwise AND returns -1 and not 4294967295

And this happens because JS can only check bitwise in the range of -2147483648 to 2147483647 (see [here](https://cwestblog.com/2011/07/27/limits-on-bitwise-operators-in-javascript/))

I would say it is not an environment or SPFx Issue, but a JavaScript.

## Environment details 

- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online
- **Framework**:  spfx
- **Browser(s)**: Chrome
- **Tooling**: VS Code | SPFx v1.4.0

**Comment by AJIXuMuK** [comment]
This should be WW now
