### ISSUE TITLE
InternalFieldName in serve.json can not be like "QM_x0020_SPACE"

### ISSUE THREAD

**Issue by SwaglordHabib** [SharePoint/sp-dev-docs#5788]
## Category

- [x] Bug

## Describe the bug

I'm started setting up an project for an field-customizer and followed this tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer
Instead of choosing no javascript framework I chose react, but that shouldn't matter. I changed the InternalFieldName to "QM_x0020_SPACE" and the pageurl to my sharepoint tendant url in the **serve.json.** Then I run gulp serve and confirm that i want to use the debug-scripts. Then nothing happens. The field-customizer won't load.

## Steps to reproduce

1. follow the tutorial 
2. add an column which is named "QM SPACE" to a list (the sharepoint internaly changes spaces to \_x0020\_ )
3. change InternalFieldName to "QM_x0020_SPACE" in the **serve.json**
4. run _gulp serve_

## Expected behavior

The debug-script should load and the field-customizer should be applied to the column.

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**:  Node.js 10.15.3 | SPFx v1.10.0 | React 16.8.5
- **Browser(s)**:  Chrome v81 | Edge 
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
Unable to repro this... I followed the same steps and it worked as expected. Can you share your project in a public GH repo?

**Comment by SwaglordHabib** [comment]
Sure I will, as soon as I can. Propably tuesday/wednesday.

**Comment by kongmengfei** [comment]
Hi SwaglordHabib,

I am able to reproduce this issue. Below are my test steps:

1. Create a column named: 

![image](https://user-images.githubusercontent.com/57654821/83993786-123eb500-a987-11ea-927a-a00963a24d48.png)

2. Follow the tutorial and modify the related settings:

![image](https://user-images.githubusercontent.com/57654821/83993857-4b772500-a987-11ea-873a-e5e3d2bd9176.png)

3. Run 'gulp serve' and launch the page.  The url in the address box is: 

> https://xxxx.sharepoint.com/sites/xx/yyy/Lists/my/AllItems.aspx?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&fieldCustomizers=%7B%22QM_x0020_SPACE%22%3A%7B%22id%22%3A%22c6b62f50-0660-4a63-9bf6-e5a8dcad9e91%22%2C%22properties%22%3A%7B%22sampleText%22%3A%22Value%22%7D%7D%7D

Decode Url: 

> https://xxxx.sharepoint.com/sites/xx/yyy/Lists/my/AllItems.aspx?debugManifestsFile=https://localhost:4321/temp/manifests.js&loadSPFX=true&fieldCustomizers={"QM_x0020_SPACE":{"id":"c6b62f50-0660-4a63-9bf6-e5a8dcad9e91","properties":{"sampleText":"Value"}}}

Result:
The field-customizer won't load. Even i press 'Ctrl+ F12', did not find any related logs.

But i fond something useful:  

I change the field name to **QM SPACE**. Input the below edited URL in browser: 

> https://xxxx.sharepoint.com/sites/xx/yyy/Lists/my/AllItems.aspx?debugManifestsFile=https://localhost:4321/temp/manifests.js&loadSPFX=true&fieldCustomizers={"QM SPACE":{"id":"c6b62f50-0660-4a63-9bf6-e5a8dcad9e91","properties":{"sampleText":"Value"}}}

The field-customizer works well. 

![image](https://user-images.githubusercontent.com/57654821/83994321-9c3b4d80-a988-11ea-84a2-703fe40737c0.png)

This might be a workaround! 

Best Regards,
Baker Kong
Microsoft SharePoint Community Support

**Comment by andrewconnell** [comment]
@kongmengfei If that's the case, then something is wrong. That field should be the internal field name which can't have a space in it. Your test would prove that SPFx is now using the display name property of a field, not the internal name.

We had another issue like this, but I can't find it now... can you help verify that we should be using the **SPField.InternalFieldName** property or the **SPField.Title** property? Docs say use the former, but this issue & your repro show the latter...
