### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by rmillman** [SharePoint/sp-dev-docs#579]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

https://msdn.microsoft.com/library/rest-api-reference-and-samples(Office.15).aspx
Broken link on bottom of page for **REST API reference and samples**

**Comment by VesaJuvonen** [comment]
Hi rmillman,
apparently, that MSDN link is broken, but could you point to the location where this link was located, so that we could get the link fixed?

**Comment by VesaJuvonen** [comment]
Removed the broken links from the articles which could find, so closing this one.
