### ISSUE TITLE
App not showing in Site Contents > Your App after a successful deployment to catalog

### ISSUE THREAD

**Issue by najwa-prog** [SharePoint/sp-dev-docs#5790]
## Category

- [x] Bug

## Describe the bug

> I have been struggling with an App (cloned from sp-dev-fx-webparts/samples/react-list-form/ ) with its versions. I tried everything deleting from site contents/recycle bin and App catalog No success. Then changing the version in the SPFx files ( Package solution and AppManifest ) nothing worked. Finally, I deleted everything restarted my Mac and restarted the solution packaging and deployment. And the weirdest happened : 

1- App catalog deployment success 
2- App not showing in Site Contents/Your App !!

<img width="1440" alt="Screen Shot 2020-05-26 at 8 18 36 PM" src="https://user-images.githubusercontent.com/63407921/82936899-8f355c00-9f8f-11ea-8190-658942a4558d.png">

<img width="1147" alt="Screen Shot 2020-05-26 at 8 18 23 PM" src="https://user-images.githubusercontent.com/63407921/82936920-95c3d380-9f8f-11ea-8a6c-04e41bc4cdfc.png">

I don't know where to start again. help is needed and appreciated. 
## Expected behavior

> The App should show in the list . And my previous attempts showed the App in Site contents. 

## Environment details (*development & target environment*)

- **Mac**: 
- **SharePoint Online**: 
- **Browser(s)**:  Safari v22 
- **Tooling**:  Visual Studio 2019

### Additional context

> All is clean, the steps were very clean after restart of the PC . The following was executed in my terminal 
- cd react-list-form
- npm install
-gulp serve
-gulp bundle --ship
-gulp package-solution --ship 

thank you. 
*Thanks for your contribution! Sharing is caring.*

**Comment by Jerry0527** [comment]
When installing List Form web part, if selecting "Make  this solution available to all sites in the organization":

![Image 1](https://user-images.githubusercontent.com/28797671/82982180-2d710280-a020-11ea-92fd-49d1a14a8e66.png)

Then no need to add in Site Contents list, you can find the web part when adding in the Modern Page:

![Image 2](https://user-images.githubusercontent.com/28797671/82982268-61e4be80-a020-11ea-9f31-7c203650575a.png)

**Comment by najwa-prog** [comment]
@Jerry0527 , 

This is exactly what has been done has been done . The problem is that the App is not showing in the Site Content List to add it as per above screen shot. 

Thank you.

**Comment by Jerry0527** [comment]
@najwa-prog, can you find the web part when adding into the page ? in my side, Site Content List also didn't show the App.

**Comment by andrewconnell** [comment]
The first screenshot shows **Deployed**=No. As @Jerry0527 showed in the first screenshot in the comment above, you have to click the **Deploy** button.

Either that didn't happen, or there was an error. If you clicked the button, look at the far right side of the app catalog list. There's an errors column there. 

Also... the context detail in your OP doesn't make sense. You say Visual Studio 2019 but you're on a Mac with SPFx? There's no tooling that supports that. Can you make sure that section is accurate to have a better picture of your environment?

**Comment by najwa-prog** [comment]
Hi @Jerry0527 and @andrewconnell thank you for your support. 
I re-added the App into my catalog and it shows deployed with no errors, however the app is still no showing the site content. as per below screen shots. Do you recommend to delete the files and re-package the solution from the start and re-deploy it ? 
I am very new to SPFx , I work on the app files via Visual Studio code. 

<img width="1358" alt="Screen Shot 2020-05-30 at 1 19 25 PM" src="https://user-images.githubusercontent.com/63407921/83326986-d7e36280-a278-11ea-8323-204e5c4456d7.png">

<img width="1301" alt="Screen Shot 2020-05-30 at 1 19 57 PM" src="https://user-images.githubusercontent.com/63407921/83326998-e893d880-a278-11ea-9303-1773217d22c4.png">

<img width="1279" alt="Screen Shot 2020-05-30 at 1 08 34 PM" src="https://user-images.githubusercontent.com/63407921/83327003-ef225000-a278-11ea-949c-24ab23c5642e.png">

**Comment by andrewconnell** [comment]
Have you completely removed the app from the app catalog, then gone back through the upload/deploy process?

Something may have gotten screwed up.

If so & still having an issue, share your project by uploading to a new GH repo and sharing the link.

**Comment by najwa-prog** [comment]
Hi @andrewconnell , yes I deleted everything from the app catalog and repackaged the solution after even restarting my PC. 

I haven't amended anything or customized features from the cloned source file : 
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form.

I created a repository, However I was not able to drag and drop the file so I had to clone it locally on my Github Desktop and respect the files to upload them. 
Please see below the link to the rep and last clean tentative result which is still the App not showing in Site contents. 

Repo Link : https://github.com/najwa-prog/react-list-form-App-Upload-Error

<img width="1280" alt="Screen Shot 2020-05-30 at 3 17 28 PM" src="https://user-images.githubusercontent.com/63407921/83330283-4aab0880-a28e-11ea-81e0-835629451fde.png">

<img width="1434" alt="Screen Shot 2020-05-30 at 3 17 56 PM" src="https://user-images.githubusercontent.com/63407921/83330295-526aad00-a28e-11ea-8c94-b08ceddd8838.png">

<img width="798" alt="Screen Shot 2020-05-30 at 3 16 46 PM" src="https://user-images.githubusercontent.com/63407921/83330307-64e4e680-a28e-11ea-9847-8200d6e1bbc3.png">

**Comment by najwa-prog** [comment]
@andrewconnell This is getting really weird . 

Funny enough I saw my App in a web part . However, it is nor visible in my Sore contents ! 
Please do not bother continuing. I think there is some thing that got corrupted following the App Catalog Add and is not related to the App files. 

<img width="1436" alt="Screen Shot 2020-05-30 at 5 39 15 PM" src="https://user-images.githubusercontent.com/63407921/83332692-e04d9480-a29c-11ea-93cd-a29e60300069.png">

<img width="1034" alt="Screen Shot 2020-05-30 at 5 38 37 PM" src="https://user-images.githubusercontent.com/63407921/83332701-e80d3900-a29c-11ea-8643-08bf4a6866de.png">
