### ISSUE TITLE
Provide non-archived version of the Throttling guidance or clarify "archived" state

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#5792]
This page "Avoid getting throttled or blocked in SharePoint Online" is shown under _Archive_ which indicates it is not up-to-date anymore. This should be clarified.

![image](https://user-images.githubusercontent.com/3469970/82987478-dd7e4580-9ff7-11ea-8aaa-3fa486af044f.png)

Is this guidance still valid? If yes: why archived? Or is there new guidance? If yes: please add a hint to the page.

Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The SharePoint docs are huge and some are outdated. Earlier this year, lots of content was moved to this **Archived** folder knowing that some would need to be moved out. I think this doc falls in that category... I'll get it moved into the **Solution Guidance** section as that's where it should be.
