### ISSUE TITLE
Who is using jQuery now a days for SharePoint Development?

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#5793]
Who is using jQuery nowadays for SharePoint Development?
It looks like SharePoint REST API Client-Side usage changed a lot with SPFX,
So suggesting to provide up to date content or provide banner like this page only supported for this Sharepoint version (OnPremise or Cloud version).

With Modern Browser API Lots's Of New Native API like `fetch` API available.
Utility liked Pnp js and [SPOHelper](https://anomepani.github.io/posts/spohelper-sharepoint-online-rest-api-crud-operation-utility-with-example/)
available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10e358f-545c-9ff3-89ae-a77643da6dc2
* Version Independent ID: 6c76adbc-bd78-d96e-3cc3-4a67af1afb5a
* Content: [Upload a file by using the REST API and jQuery](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery)
* Content Source: [docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
The choice is up to the developer in question. You are free to choose whatever client side framework that works for you, and there are quite a few devs who still use JQuery.

However,  I would recommend learning React, as there are a lot more resources available for SPFx including components from UI Fabric.

**Comment by anomepani** [comment]
Yes @bcameron1231 , you are right. Reference and sample code on official Microsoft site are very old for new developer if referencing those documents,  they are very confused. Add-in code,  accestoken,  old way to get requestdigest etc. Concept and usage best suit for SP 2013. I am just giving my thoughts.

**Comment by thechriskent** [comment]
Nothing wrong with jQuery if it solves your problem. There are several samples in both the SPFx web parts and extensions repositories that feature the use of jQuery.

As @bcameron1231 mentions, some of the more recent frameworks such as React are going to have more resources available and may provide you some more opportunities for following "better" patterns in development. I highly recommend using them and, as you mentioned, using something like PNPjs to access the REST API is a great idea. But none of that is required and the samples shown still work and are supported.

If a developer is comfortable with jQuery or wants to utilize one of the thousands of jQuery plugins available, then it makes a lot of sense to use it. There are enough complications when working with SPFx, SharePoint, REST APIs, etc. and it's tough to take them all on at once. Samples like these that demonstrate familiar techniques to help bridge the gaps from one set of technology to another are really helpful for a lot of developers.
