### ISSUE TITLE
Content of page interchanegd or mixed with Add-In and Client Side Page

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#5794]
Content of page interchanged or mixed with Add-In and Client-Side Page.
As an End User for beginner, He may be looking at REST Operation with cookie or Request Digest, not with Add-In Access Token based approach which is different.

For Beginner SharePoint Developer or someone who wants to explore the Sharepoint world then this content is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I'm unclear on your comment. This page is very basic about making requests to the SharePoint REST API. It only includes HTTP requests which are the most basic requests to the REST API. How you make those requests (add-in / client-side script, etc) gets a bit more complex and the docs in those respective sections cover calling the SharePoint REST API.

Not sure there's anything actionable here... therefore closing. Feel free to submit a new comment if you feel this was closed in error.
