### ISSUE TITLE
Error in Loading debug manifest file ListViewCommandSet SPFX

### ISSUE THREAD

**Issue by Caloy07** [SharePoint/sp-dev-docs#5797]
Hello Team,

While trying to debug using gulp serve command, whenever I tried to load the debug script i received this error.

![image](https://user-images.githubusercontent.com/66045097/83088131-7af37b00-a0c5-11ea-92eb-969391f07780.png)

I already tried the gulp trust-dev-cert command and still not even working on all browsers. I tried downgrading and upgrading the node versions as well and still nothing happens.

Can you please help in this regard.

Thanks &  Regards
Caloy

**Comment by andrewconnell** [comment]
The initial issue template contained a bunch of sections, including a critical "context" section that asked for versions. That's included because it's necessary to get some context about your environment and versions. 

Please resubmit & complete those sections that so we can better help...
