### ISSUE TITLE
How can we make request for https://graph.windows.net from spfx? 

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#5798]
I would like to get token for azure ad graph url, How can we make request for https://graph.windows.net from spfx? 
How can we pass resource scope for azure ad graph request.

Any help much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There's a long & short answer to this.

The long answer: you'll need to grant your SPO tenant the necessary permissions to call the Azure AD Graph REST API, then use the information in this doc to call it.

The short answer is: look at using the [Microsoft Graph](https://docs.microsoft.com/graph/api/overview?view=graph-rest-1.0). Depending on what you want to do with the Azure AD REST API endpoint, you likely can do it with MS Graph. MS Graph is a proxy to many APIs including the Azure AD Graph REST API. Plus, SPFx has native support for calling MSGraph: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph.
