### ISSUE TITLE
OOTB News web part site link is white on hover

### ISSUE THREAD

**Issue by corriespondent** [SharePoint/sp-dev-docs#5799]
## Category

- [x] Bug

## Describe the bug

On the OOTB News web part, if pulling from multiple sites, the site name link turns white on hover, which becomes illegible when on a white background.

Update: This happens on the side-by-side and list views. Featured news layout and Hub news add extra styling so that this doesn't happen.

## Steps to reproduce

1. Add a news web part to a page
2. In the web part settings, choose the source to be from multiple sites to get the site link to show up on the news items
3. Hover over the site link - it turns white

## Expected behavior

The hover color should not be the same as the background color, which can often be white.

## Environment details (*development & target environment*)

O365

- **OS**: Windows and Mac
- **Target Environment**: SharePoint Online
- **Framework**: n/a
- **Browser(s)**: Chrome v81, Firefox v76
- **Tooling**: n/a
- **Additional details**:  n/a

News web part:
![image](https://user-images.githubusercontent.com/23064475/83149988-9eabc680-a0af-11ea-9d61-423fe8150ff7.png)

News web part, hovered over site link:
![image](https://user-images.githubusercontent.com/23064475/83150033-abc8b580-a0af-11ea-84b7-c1a81140e397.png)

Inspector:
![image](https://user-images.githubusercontent.com/23064475/83150112-c4d16680-a0af-11ea-82f4-89238a8316c4.png)

**Comment by JarbasHorst** [comment]
Hello @corriespondent 

the reported issue looks like an OOTB feature in SharePoint. Hence, you should post the question to [TechCommunity](https://techcommunity.microsoft.com/). Our GitHub forum is for custom SharePoint dev related issues!

Thanks
Jarbas

**Comment by corriespondent** [comment]
Oops! Thanks @JarbasHorst! I will do so!
