### ISSUE TITLE
SharePoint Add- in 

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#58]
Just to curiosity, is this going to eliminate SharePoint Provider hosted add-in and SharePoint Add-in in future?

**Comment by patmill** [comment]
Nope - we will continue to support (and improve) both.  It does take away some scenarios where you would use the add-in model.  The main consideration has to do with the permissions / trust that you have in the developer.  Client Side Web Parts run as the current user, and have access to whatever the current user has access to (which is exactly the same as if you had a script editor webpart, custom action or jslink property set).  However if you don't trust the developer and want to impose limitations and restrictions on what the control can do, then the add-in model is still important.  If you want the extra isolation (both "good" and "bad") that the iFrame model gives you, then the add-in model is the right choice for that solution.

**Comment by bvdinesh** [comment]
Thanks for the information
