### ISSUE TITLE
Teams custom personal app (SPFx) - slow authentication startup in desktop app

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-docs#5800]
Hi

We've implemented quite some Teams personal apps at clients now and the custom Teams apps in the (Teams desktop app) sometimes have load times ranging from 4s - 10s before our custom code even begins. The Teams web app handles auth in a different way, so never any issue there. 

It appears to have something to do with the way authentication is done in the desktop app (acquire OBO token call...). With a trick, you can also get the console & network tab to show in the desktop app. That way we can verify when our React is loaded & starting + when our backend api calls are done. 

Clients are complaining about the response times and rightfully so. The response times before our code hits also varies greatly between tenants as mentioned.

Has anyone had the same experience? Is there a magic wonder solution out there that I don't know of yet (e.g. simple AAD authentication setting) ?

See also [techcommunity](https://techcommunity.microsoft.com/t5/microsoft-teams/teams-custom-personal-app-spfx-slow-authentication-startup-in/m-p/1424186#M60380)

**Comment by PieterHeemeryck** [comment]
I moved this issue to SharePoint/sp-dev-training-spfx-teams-dev

**Comment by andrewconnell** [comment]
The initial issue template contained a bunch of sections, including a critical "context" section that asked for versions. That's included because it's necessary to get some context about your environment and versions.
