### ISSUE TITLE
Teams personal app - White screen after password change

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-docs#5801]
Hi

We've had some issues with clients having a white screen when opening our custom personal app for Teams (SPFx) - only on the desktop Teams app, not the web browser. It happens whenever an end user has changed his / her password. I'm fairly certain it has to do with the desktop app caching auth tokens that are no longer valid after the password change.

For now, as a 3rd party app developer, there isn't much we can do besides asking the user to log out, log in and cross our fingers.

Is this on the radar of the SPFx & Teams product teams ? Are there other solutions to this problem ?

PS: we are following the approach outlined by Vesa in this [video](https://www.youtube.com/watch?v=IGBKOreRu3M).

**Comment by andrewconnell** [comment]
The initial issue template contained a bunch of sections, including a critical "context" section that asked for versions. That's included because it's necessary to get some context about your environment and versions.

**Comment by patrikhellgren** [comment]
@PieterHeemeryck have you seen #5320? You are probably seeing the exact same issue.

**Comment by PieterHeemeryck** [comment]
Indeed, it is the same issue.
