### ISSUE TITLE
Sharepoint page show 500 INTERNAL SERVER ERROR during migrate webpart using export api

### ISSUE THREAD

**Issue by WilliamZheng** [SharePoint/sp-dev-docs#5804]
Requirement: Use export api to migrate classic content editor web part .
Issue Step:
1. Call the export API.
2. Get the "Content Editor" web part at "Manifest.xml"
3. Get the value of property "AllUsersProperties" of the webpart,
4. Decode the value of "AllUsersProperties" by "base64", change the value as needed, and encode the value, and then save it back to "Manifest.xml".
`            var newProptertyValue = Encoding.UTF8.GetString(Convert.FromBase64String(webpart.AllUsersProperties));
            newProptertyValue = newProptertyValue.Replace("/sites/a", "/sites/b");
            var encodeProptertyValue = Convert.ToBase64String(Encoding.UTF8.GetBytes(newProptertyValue));
            return encodeProptertyValue;`
5. Call the import API to migration
**Issue: when migration is done, I open the site page which contain this webpart, it shows "500 error".**

Btw, I notice that after I decode the content of "AllUsersProperties" using Encoding.UTF8.GetString(Convert.FromBase64String(webpart.AllUsersProperties)),  I found many control character, is it the root cause of this issue?

Below is the exported setting for the Conent Editor Webpart.
` <WebPart Name="052fd43f-9717-48dc-ab8e-cf81ee6fb594" Version="15" AllUsersProperties="AQUAAAACKgBKACkAAz0AAAIqAEkAKQADPgAAAQIAKQAD//8wJFJlc291cmNlczpjb3JlLENvbnRlbnRFZGl0b3JXZWJQYXJ0RGVzY3JpcHRpb247DwEgACkAA///Hy9fbGF5b3V0cy8xNS9pbWFnZXMvbXNjb250bC5naWYPATsAWgAE//+eBuKAi1R0dHQmIzE2MDsmIzE2MDs8dGFibGUgY2VsbHNwYWNpbmc9IjAiIHdpZHRoPSIxMDAlIiBjbGFzcz0ibXMtcnRlVGFibGUtZGVmYXVsdCI+PHRib2R5Pjx0cj48dGQgY2xhc3M9Im1zLXJ0ZVRhYmxlLWRlZmF1bHQiIHN0eWxlPSJ3aWR0aDogNTAlOyI+4oCL4oCLZmZmZmY8YnIvPjwvdGQ+PHRkIGNsYXNzPSJtcy1ydGVUYWJsZS1kZWZhdWx0IiBzdHlsZT0id2lkdGg6IDUwJTsiPuKAi3R0dHQ8YnIvPjwvdGQ+PC90cj48dHI+PHRkIGNsYXNzPSJtcy1ydGVUYWJsZS1kZWZhdWx0Ij7igItzczxici8+PC90ZD48dGQgY2xhc3M9Im1zLXJ0ZVRhYmxlLWRlZmF1bHQiPuKAi3R0dHQ8YnIvPjwvdGQ+PC90cj48L3Rib2R5PjwvdGFibGU+PGJyLz48YSBocmVmPSIvc2l0ZXMvV2lsaWFtRW1wdHlTaXRlMyI+Q3VycmVudFNpdGXigIs8L2E+JiMxNjA7ICYjMTYwO2h0dHBzOi8vc3BtY2hpbmFzb3VyY2Uuc2hhcmVwb2ludC5jb20vc2l0ZXMvV2lsaWFtRW1wdHlTaXRlM+KAiyYjMTYwOyAmIzE2MDsmIzE2MDs8ZGl2Pjxici8+PC9kaXY+PGRpdj48aDE+Q2hhcjxici8+PC9oMT48aDM+PHNwYW4gY2xhc3M9Im1zLXJ0ZVN0eWxlLUVtcGhhc2lzIj5DaGFyJiMxNjA7PC9zcGFuPuKAizxici8+PC9oMz48YnIvPjwvZGl2PjxkaXY+VERERFRBPGJyLz48L2Rpdj48ZGl2PjxzcGFuIHhtbDpsYW5nPSJmciIgbGFuZz0iZnIiPjxici8+PC9zcGFuPjwvZGl2PjxkaXY+PHNwYW4geG1sOmxhbmc9ImZyIiBsYW5nPSJmciI+PGJyLz48YnIvPjwvc3Bhbj48L2Rpdj48ZGl2Pjxici8+PC9kaXY+PGRpdj48YnIvPjwvZGl2Pg8P" PerUserProperties="AQUAAAACKgBKACkAAz0AAAIqAEkAKQADPgAAAQQAKQAD//8UQ29udGVudCBFZGl0b3I0MzQzNDMPDw==" Level="minor" WebPartZoneID="Header" WebPartTypeId="9b7bf700-588d-6333-22ec-14b3bbfce104" IsIncluded="true" WebPartOrder="1" FrameState="0" />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1654a603-da1f-b11b-fd2f-9aa20e9fac02
* Version Independent ID: e8453081-caea-ee38-137d-3cfe2c145f45
* Content: [SharePoint Migration Export (Asynchronous Metadata Read) API](https://docs.microsoft.com/en-us/sharepoint/dev/apis/export-amr-api)
* Content Source: [docs/apis/export-amr-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/export-amr-api.md)
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by WilliamZheng** [comment]
Any issue about the code for decode and encode the value of "AllUsersProperties"?

**Comment by WilliamZheng** [comment]
@andrewconnell  Hi Andrew, any update on this issue?

**Comment by andrewconnell** [comment]
I know nothing about this API... I simply tagged it for visibility. All I'll add is: 500 errors = server errors = something out of your control.

**Comment by WilliamZheng** [comment]
@andrewconnell  And do we have a special sample code to decode the value of "AllUsersProperties" which can't be decoded using a simple way like "Encoding.UTF8.GetString(Convert.FromBase64String(webpart.AllUsersProperties))"?
