### ISSUE TITLE
iOS Teams SDK fro SPFx always reports General channel

### ISSUE THREAD

**Issue by joeljeffery** [SharePoint/sp-dev-docs#5806]
## Category

- [x] Bug

## Describe the bug

On iOS only:
```
this.context.sdks.microsoftTeams.context.channelId
this.context.sdks.microsoftTeams.context.channelName 
this.context.sdks.microsoftTeams.context.channelRelativeUrl
```

...all return information about the **General** channel for the current team, instead of the channel on which the SPFx web part is loaded. Bizarrely, tab (i.e. entityId) seems to be correct.  ¯\\_(ツ)_/¯

## Steps to reproduce

1. Build an SPFx web part for Teams
1. Get at the channel name via the supplied context object (this.context.sdks.microsoftTeams.context)
1. Render the channelName and channelId somewhere visible
1. Deploy your web part to your tenancy and add it to a team channel that (and here's the important part) ISN'T the General channel ;)
1. Verify this works as expected on the desktop or browser versions of Teams
1. Now visit it on the iOS app (iPhone or iPad) and compare channel names / IDs
1. Fail

## Expected behavior

Lack of fail. Consistent behaviour. The correct channel deets being supplied.

## Environment details (*development & target environment*)

- **OS**: iOS 13
- **Target Environment**: Teams Mobile App
- **Tooling**: SPFx, VS Code, React/TypeScript app 

### Additional context

Apols if this isn't the correct forum to report this.

Other things that are full of fail on iOS:
- this.context.sdks.microsoftTeams.teamsJs.getContext() <--- never comes back on iOS.

## Workaround (really crappy workaround sorry!)
Web part properties are only shown to the desktop. We can use this. 
- Add a string web part property to your project for channelId. 
- Default this to this.context.sdks.microsoftTeams.context.channelId when the property panel is shown and persist it to web part properties
- Use this value instead on iOS

**Comment by joeljeffery** [comment]
Bug repeatable on Android! :) Confirmed on a colleagues phone.

**Comment by joeljeffery** [comment]
Nope. Worse than I thought. :( entityId is wrong on Android. Workaround: cache both channelId and entityId in web part properties from the desktop at the point of adding your web part to a channel.

**Comment by patmill** [comment]
(working our way through old issues, sorry for the delay).  The teams sdk isn't managed by us, but has been through numerous updates.  Is this still an issue?
