### ISSUE TITLE
Add features of background color change and different layout options

### ISSUE THREAD

**Issue by lovethakker02** [SharePoint/sp-dev-docs#5808]
Microsoft has updated the options in footer panel. when you enable it, you can now select footer to display as standard as well as you can set extended design. 

As well as you can set background color. I have attached new footer enable image with this.

Please update this details in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://docs.microsoft.com/en-
![Footer - enable](https://user-images.githubusercontent.com/42000241/83354536-f6c81e80-a376-11ea-9d8f-c4d8b36355ac.png)

us/sharepoint/dev/features/site-footer#controlling-footer-using-the-user-interface)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/site-footer.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to offer a suggestion on the doc updates by submitting a PR? https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests
