### ISSUE TITLE
Apply-PnPProvisioningTemplate: ramdom connection errors 

### ISSUE THREAD

**Issue by alriveiro** [SharePoint/sp-dev-docs#5811]
## Category

- [x] Bug

## Describe the bug

Getting connection errors that abort the operation when the command Apply-PnPProvisioningTemplate last a long time, because the template include list items and library files. Errors like:

> - The underlying connection was closed: An unexpected error occurred on a receive
> - The underlying connection was closed: An unexpected error occurred on a send
> - Unable to write data from the transport connection : An existing connection was forcibly closed by the remote host

## Steps to reproduce

**1.** Create a configuration JSON (conf.json) to get a site template that will include list items for some lists and libraries

**2.** Get the template using Get-PnPProvisioningTemplate:
Get-PnPProvisioningTemplate -Out c:\template.xml -Configuration conf.json 

The command create a template xml and some folders in the filesystem with the files downloaded for the libraries

**3.** Apply the template:
$con = Connect-PnPOnline -Url $siteUrl -ReturnConnection
Set-PnPTraceLog -On -Level:Debug
Apply-PnPProvisioningTemplate -Path c:\template.xml -Connection $con

The process executes correctly for some minutes, creating lists, libraries, fields, uploading hundreds of 
files to the library in the new site but then terminate with a ramdom connection error like:

> - The underlying connection was closed: An unexpected error occurred on a receive
> - The underlying connection was closed: An unexpected error occurred on a send
> - Unable to write data from the transport connection : An existing connection was forcibly closed by the remote host

## Expected behavior

Structure of the new site is the same like the source site and all list items and library files were uploaded to the new site.

## Environment details (*development & target environment*)

- Environment: 

> - Windows PowerShell ISE
> - SharePointPnPPowerShellOnline 3.21.2005.2

**Comment by andrewconnell** [comment]
Best to post to this to the PnP PowerShell repo issue list (https://github.com/pnp/PnP-PowerShell)... unfortunately we can't transfer it across GitHub organizations.
