### ISSUE TITLE
Spfx field customizer for managed metadat field 

### ISSUE THREAD

**Issue by anisiaalexandra** [SharePoint/sp-dev-docs#5816]
## Category

- [x] Bug

## Describe the bug

Hi,

I have been trying to create a simple Spfx field customizer and tried to get related info with @pnp/sp-taxonomy. I constantly get the following issue and the field no longer get rendered. I cannot acces debug in this case. I have verified if it is the async calls but other async calls to Graph for example work. Do you have any idea of what can be wrong?

## Steps to reproduce
Create a hello world field customizer  called MmdCustomizerFieldCustomizer and attach it to a taxonomy field

In the code:
`export default class MmdCustomizerFieldCustomizer
extends BaseFieldCustomizer {

@override
public async onInit(): Promise {
const store: any = taxonomy.termStores.getByName("<Your taxonomy store name>");

var term: ITerm = store.getTermById("${event.fieldValue.TermId}");

this.properties.descr = await term.getDescription(1031);

//var currentUser = (await this.getCurrentUserByGraph())["userPrincipalName"];
//alert(currentUser);
}`

Error  when I try to debug or after deploy on AllItems page load with taxonomy field in it:

listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1 Uncaught (in promise) Error
at r.t [as constructor] (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
at new r (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
at Function.e.buildErrorWithVerboseLog (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
at Function.e.buildLoadComponentError (listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1)
at listview-host-assembly_default_13c644876b8cb32e22df7c593449c80e.js:1

## Expected behavior

In the this.properties.descr have the chosen term description

## Environment details (*development & target environment*)

The environment is a development tenant and it is on targeted release

- **OS**:  Windows 10 
- **Target Environment**: SharePoint Online
- **Browser(s)**: Chrome v79 |
- **Tooling**: VS Code
- **dependencies**: * "@microsoft/decorators": "1.9.1",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-listview-extensibility": "1.9.1",
    "@pnp/common": "^2.0.5",
    "@pnp/logging": "^2.0.5",
    "@pnp/odata": "^2.0.5",
    "@pnp/sp": "^2.0.5",
    "@pnp/sp-clientsvc": "^1.3.11",
    "@pnp/sp-taxonomy": "^1.3.11",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1"*

*Thanks for your contribution! Sharing is caring.*

Thank you in advance for your help.

**Comment by maartendevos** [comment]
If you use the taxonomy libraries, you can't use other versions of the PnPjs libraries. You'll need to stay on the 1.x versions for everything.
This will work:
`npm install @pnp/logging@^1.3.11 @pnp/common@^1.3.11 @pnp/odata@^1.3.11 @pnp/sp@^1.3.11 @pnp/sp-taxonomy@^1.3.11 @pnp/sp-clientsvc@^1.3.11 --save`
