### ISSUE TITLE
CreatorName and CreatorEmail fields incorrectly populated

### ISSUE THREAD

**Issue by Squiggleh** [SharePoint/sp-dev-docs#5817]
With the latest version of Management Shell the CreatorName and CreatorEmail fields are populated with the O365 Members Group, not the person who called the site design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afac891-6cf5-1746-6392-8cb61a441770
* Version Independent ID: b5d1f95b-f40b-8d0c-7334-7608a3add9ff
* Content: [Using site designs and Power Automate to track site creation requests](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial)
* Content Source: [docs/declarative-customization/site-design-trigger-flow-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-trigger-flow-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @Squiggleh 

I have been able to reproduce the reported issue. According to my Flow's history, the issue has been there since April. During my tests, I got the following values:

- CreatorName: {GroupDisplayName} Owners
- CreatorEmail: {GroupMailNickName}@{Tenant}.onmicrosoft.com

Regards,
Jarbas

**Comment by andrewconnell** [comment]
This forum is for SharePoint development issues so I'm not sure it's the right place for SPO Mgmt Shell bugs to be reported. I've asked MSFT where they would recommend where to post issues... likely TechCommunity... I'll leave this open until I have more details.

**Comment by Squiggleh** [comment]
Yeah, I've also been looking where to post this for more clarity from a
technical perspective.

But if it's not a bug and is now the intended functionality, this will need
to be updated.
