### ISSUE TITLE
Retrieve paged result sets no FilterValue

### ISSUE THREAD

**Issue by mvahsen** [SharePoint/sp-dev-docs#582]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
[(https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/general-development/get-started-using-the-client-object-model-with-external-data-in-sharepoint.md)]

The source code in paragraph: "Retrieve paged result sets" doesn't work. I've appended a screenshot from Visual Studio with the properties. There is no FilterValue property in the filter object. How do you set a FilterValue property?

Namespace which I'm using:
```
using Microsoft.BusinessData.MetadataModel;
using Microsoft.SharePoint.Client;
```

![image](https://cloud.githubusercontent.com/assets/16557479/25848595/4b91883a-34bb-11e7-9111-d0b2c03c50f7.png)

**Comment by kavaghela** [comment]
I am also facing same issue. Did you find any solution for that?
