### ISSUE TITLE
Wrong URL for finding an item

### ISSUE THREAD

**Issue by matthewfarrell** [SharePoint/sp-dev-docs#5820]
[Enter feedback here]
Under the section [Retreive specific list item](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-specific-list-item
), the example url is 
```
GET https://{site_url}/_api/web/lists/GetByTitle('Test')/items{item_id}
```
This should be (mising Round Brackets)
```
GET https://{site_url}/_api/web/lists/GetByTitle('Test')/items({item_id})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Thanks @matthewfarrell for the feedback. I have created a PR to fix this issue!
