### ISSUE TITLE
[MSTeams] SPFx TeamsPersonalApp doesn't load in mobile client, showing SP error page

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#5823]
## Category

- [x] Bug

## Describe the bug

We have created an SPFx application running as `TeamsPersonalApp` in MS Teams.
This works as expected in the web and desktop clients, but does not load in the mobile client.
An error message is shown:

![IMG_1775](https://user-images.githubusercontent.com/1467263/83611330-1f236900-a581-11ea-879a-fafbc89b3f4b.PNG)

## Steps to reproduce

1. Create an SPFx webpart with `supportedHosts: ["TeamsPersonalApp"]`
1. Add the SPFx webpart as a personal app in MS Teams
1. Try to open the App in the Mobile client (iOS)

## Expected behavior

The application should open in the mobile client as well, without showing an application error.

## Environment details (*development & target environment*)

- **OS**: iOS
- **Target Environment**: SharePoint Online / MS Teams

**Comment by jp-cf** [comment]
@NickSevens I'm hitting the same error this morning (and other users have been facing this issue for the last week too). Like you, app works correctly in Desktop and web view but not in iOS or Android teams clients - both in Developer Preview and not.

**Comment by Rtoribiog** [comment]
our users are experiencing the same issue , it´s working ok for android users but not for IOS.
