### ISSUE TITLE
HTTPClient dependencies

### ISSUE THREAD

**Issue by zoh-akh** [SharePoint/sp-dev-docs#5824]
The docs say that there are no dependencies for the HTTPClient, but when used directly without importing any dependencies, the code throws an error saying "Cannot find name HttpClient'. Please correct that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b84eaa-9fbf-6d45-fda6-0f59ea10ac30
* Version Independent ID: 46395b70-89c3-b77b-0fc1-e8a86ff093ad
* Content: [Connect to anonymous APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-anonymous-apis)
* Content Source: [docs/spfx/connect-to-anonymous-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/connect-to-anonymous-apis.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by OS-Lee** [comment]
Hi,

httpClient inherits from webpart parent BaseComponentContext, make sure you use it correctly.

Provide details how you use it if you need further assistance.

**Lee
Microsoft SharePoint Community Support**
