### ISSUE TITLE
More details required from the documentation

### ISSUE THREAD

**Issue by brit92** [SharePoint/sp-dev-docs#5835]
## Category

- [ ] Question
- [ ] Typo
- [x] Additional article idea

I went through the steps in this article: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine

It's mentioning that I can run 2 commands, one to get the provisioning template, the other to apply the provisioning template. I created a site, applied a logo, created 3 pages, and linked to these 3 pages from the homepage web parts. When I used the steps in the article, I got a broken site. 

After further reading, I found out that I need to use tokens, which is not mentioned in this article and I couldn't find more details somewhere else on how to use these parameters for these commands. Where can I find more in depth information on how to use the provisioning engine. It's too hard to just figure it out by reading this article.

**Comment by andrewconnell** [comment]
You can find all information about the provisioning framework in the docs (https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning) & on the project sites>
