### ISSUE TITLE
SPFx 1.10.0 Property Pane settings unavailable for Isolated SharePointFullPage WebPart?

### ISSUE THREAD

**Issue by theofred** [SharePoint/sp-dev-docs#5839]
## Category

- [x] Question

## Question

I've created an isolated full page WebPart and in the property pane are no settings. It only shows `No settings to change for this web part.` instead of the default description text field and I can set the site title. When I ad the WebPart to a normal site as a small/non-full-page WebPart, I can see and edit the properties as usual.

Is this behavior expected from an isolated full page WebPart?

## Steps to reproduce

1. create an isolated (Will the components in the solution require permissions to access web APIs that are unique and not shared with other components in the tenant? Yes) WebPart
2. add "SharePointFullPage" to the supportedHosts property inside the *.manifest.json
3. bundle, pack and deploy to app catalog and install it to a modern site
4. create a new Site, choose the App tab, choose the created WebPart

- **OS:** Windows 10
- **Target Environment:** SharePoint Online
- **Framework:** Node.js v10.17.0
- **Browser:** Firefox 77.0.1
- **Yeoman generator:** @microsoft/generator-sharepoint@1.10.0
- **Generator Answers:**
> ? What is your solution name? isotest
> ? Which baseline packages do you want to target for your component(s)? SharePoint Online only (latest)
> ? Where do you want to place the files? Use the current folder
> Found npm version 6.11.3
> ? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites? No
> ? Will the components in the solution require permissions to access web APIs that are unique and not shared with other components in the tenant? Yes
> ? Which type of client-side component to create? WebPart
> Add new Web part to solution isotest.
> ? What is your Web part name? IsolationTest
> ? What is your Web part description? IsolationTest description
> ? Which framework would you like to use? No JavaScript framework

## Additional Context

I would guess that this is a bug, as I can not find an argument why this should not work.
I've also tested if the isolated WebPart takes its properties from a different place than the `_api/sitepages/pages` list, but it doesn't. It is also possible to manually change the properties with api calls (found at João Mendes blog post [Read and Update SPFx WebPart Properties from code](https://joaojmendes.com/2019/02/08/read-and-update-spfx-webpart-properties-from-code/))

**Comment by theofred** [comment]
Bump!
Right now we're creating a workaround by manually creating a new property pane from
`import PropertyPane from '@microsoft/sp-property-pane/lib/propertyPane/PropertyPane';`
and passing all the necessary props to it like the `IPropertyPaneConfiguration` from `getPropertyPaneConfiguration()`. The backend saving is done like I've mentioned with the method descibed here https://joaojmendes.com/2019/02/08/read-and-update-spfx-webpart-properties-from-code/
And we open our pane (and close the old one) inside the `onPropertyPaneRendered()` method. So it mimics the right behaviour.

I still think a workaround should not be necessary.

**Comment by patmill** [comment]
(sorry - added the wrong tag).  We are working on this now @theofred .  Sorry for the delay
