### ISSUE TITLE
call the *.tsx file in ._topPlaceholder.domElement.innerHTML = `<div>....</div>

### ISSUE THREAD

**Issue by yzafat** [SharePoint/sp-dev-docs#5847]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question
I need your help. i would to call the *.tsx file in html element in my spfx extension
**how can I do this ?**
I would like to do as in the code below

if (this._bottomPlaceholder.domElement) {  
          this._bottomPlaceholder.domElement.innerHTML = `<div class="styles.app">  
              
              **<Mytsxfile/>**  

            </div>`;  
        }  

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [ SPFX | React v16]
- **Browser(s)**: [e.g. Chrome v79 ]
- **Tooling**: [VS Code | SPFx ]

Thanks for your contribution!*

**Comment by kongmengfei** [comment]
Hi yzafat,

"this._bottomPlaceholder.domElement" is a dom element, while "`<Mytsxfile/>`" is a React component.  As @andrewconnell  mentioned, it's suggested to use ReactDom.render() to mount the component to the corresponding element where you want to render. 

demo: 

`const element = ()=>{return <Mytsxfile/>} ;   `
` ReactDom.render(element, this._bottomPlaceholder.domElement);`

You may also take a reference of below sample:

- [Regions Footer Application Customizer](https://github.com/kongmengfei/sp-dev-fx-extensions/blob/master/samples/react-application-regions-footer/src/extensions/yammerFooter/YammerFooterApplicationCustomizer.ts)

Baker Kong
Microsoft SharePoint Community Support
