### ISSUE TITLE
SPFx solutions not working in latest SharePoint 2019 update

### ISSUE THREAD

**Issue by d-martins** [SharePoint/sp-dev-docs#5855]
## Category

- [x] Bug

## Describe the bug

After installing the [May 12 security update](https://support.microsoft.com/help/4484332) for SharePoint 2019, new SPFx solution deployments have been consistently failing.

## Steps to reproduce

1. Update SharePoint 2019 server to the [KB 4484332](https://support.microsoft.com/help/4484332) update (version 16.0.10359.20000)
1. Create a new SPFx project with the following yeoman command
```yo @microsoft/sharepoint --component-type webpart --framework none --environment onprem19 --skip-feature-deployment```
1. Package the solution using the `gulp bundle --ship` and `gulp package-solution --ship` commands
1. Open the App Catalog site collection for the SharePoint 2019 environment
1. Upload the .sppkg package
1. After a while, the following error will appear in the error column
```There were errors when validating the App manifest.: Xml Validation Exception: 'The 'SkipFeatureDeployment' attribute is not declared.' on line '1', position '276'.```

## Expected behavior

After uploading the package, the trust dialog should appear instead of the error message.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Server 2019
- **Framework**: Node.js v8.15.0
- **Browser(s)**: any
- **Tooling**: VS Code 

### Additional context

Downloading and removing a previously deployed solution from the App Catalog and then re-uploading it results in the same error.

**Comment by d-martins** [comment]
I'm using version 1.10.0 of the @microsoft/generator-sharepoint
I tried to create the project with the answers in the image and the issue still occurrs

![yo-options](https://user-images.githubusercontent.com/6013384/84376171-92a82480-abd8-11ea-99ba-bf53e4008929.png)

**Comment by d-martins** [comment]
The above yeoman answers actually didn't work for SharePoint Online either due to the title of the solution having a `-` character in the name (issue #1130).
On my 2019 environment, the error was still the same from this report.

I created a new project using a different name and now it works in SharePoint Online and a 2019 without the May 12 Security Update. On my 2019 environment with the update, I still get the reported error.

![yo-options](https://user-images.githubusercontent.com/6013384/84387440-e6236e00-abea-11ea-960e-0e76cd8993f3.png)

**Comment by d-martins** [comment]
Sorry, I jumped the gun on the repro steps.
I built a new SP2019 VM in Azure and upgraded to the May 12 update, but the package deploys there as expected.

The issue started happening shortly after updating SharePoint to the May 12 update, so I assumed it was related, but something else may have happened to this environment.
Not sure where else to look since this was also the main difference between the VM with the issue and the ones without.

Sharing the current patch status on the faulty VM anyways as it might help if anyone else is having this issue:

![patch-status](https://user-images.githubusercontent.com/6013384/84420418-e8e58980-ac11-11ea-919a-37a007464e37.png)

**Comment by andrewconnell** [comment]
Unfortunately, this isn't an SPFx issue, rather this seems like an issue with your environment. As such, we can't triage it here as this issue list is for development/developer issues. This is better suited to TechCommunity or by opening a ticket with MSFT.
