### ISSUE TITLE
SharePoint Solution Generator hangs at 'use current folder'

### ISSUE THREAD

**Issue by mbalcarek** [SharePoint/sp-dev-docs#5858]
Hello,

## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

After typing: yo @microsoft/sharepoint 
What is you solution name: helloworld-webpart-3 (default)
Which baseline..:    SharePoint Online Only (latest)   (default)
Where do you want to place the files?  Use the current folder (default)

At which point it hangs. I have to close the window to get response.

## Environment details (if applicable)

I use windows 10
npm list -g --depth=0
+-- @microsoft/generator-sharepoint@1.10.0
+-- gulp@4.0.2
`-- yo@3.1.1

node -v
10.20.1

I have tried uninstalling and re-installing node, yo, gulp and the generator. 
•	npm uninstall -g @microsoft/generator-sharepoint
•	npm uninstall -g yo
•	npm uninstall -g gulp
•	npm install -g yo gulp
•	npm install -g @microsoft/generator-sharepoint

Please advise what I can do to return to a working environment.

**Comment by andrewconnell** [comment]
If you didn't install the generator after re-installing Node, then it didn't delete the globally installed packages... I'd suggest following the instructions here to completely uninstall everything:

https://stackoverflow.com/a/20711410/306347

**Comment by mbalcarek** [comment]
Hi Andrew,
That worked. I uninstalled npm as per the link you recommended. **I also uninstalled NVM.**
After re-installing npm, yo, gulp and the generator I was able to complete the wizard.
Thank you!
