### ISSUE TITLE
BUG: Using <a /> tag causing whole webpart to be re-rendered in modern site page

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#586]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I'm using normal `<a role="button" />` tag with onClick events to interact with the UI, this works fine in both Classic pages and /_layouts/workbench.aspx page, however when I deploy this to modern page I noticed that each time I clicked on the <a/> tag it always re-render the whole webpart again.

This issue also occurs on normal `<a href="#" ></a>` tag without any onClick event,

**Comment by StfBauer** [comment]
Have you tried to override the onClick event, because even when you don't have an onClick handler attached the browser by default hast on.

Haven't tried it myself but looks a bit strange.

**Comment by jonathanhotono** [comment]
@StfBauer Sorry for the delay, yes I did tried to to override using `event.preventDefault() `and `event.stopPropagation()`. It still re-render the whole webpart.

**Comment by Paul-Colucci** [comment]
I have noticed the same behavior.  This is particularly an issue when using third party components that render <a> tags which you have no control over.

**Comment by matthong** [comment]
We are facing the same problem when using a 3rd party library which uses <a href="#" /> for dropdown menus. Any idea when the bug can be fixed?
Is there a workaround for this issue?

**Comment by jonathanhotono** [comment]
Fyi @iclanton @VesaJuvonen .
This probably isn't an issue with spfx and probably with the o365 modern page bug. Not sure where else to report this bug.

**Comment by matthong** [comment]
Seems that the issue happens in IE 11 and Chrome, but not in Firefox. Post a question to StackExchange: https://sharepoint.stackexchange.com/questions/218265/using-a-tag-in-spfx-web-part-causes-the-whole-page-re-rendered-in-modern-site

**Comment by jonathanhotono** [comment]
@matthong thanks, it seems that the description is a bit different to the issue that i addressed. This only applies on modern pages where any <a> tag click with or without href will re-render the whole webpart (or recall the `render` method in xxxWebPart.ts) without refreshing the page. I will make a sample project with `debugger`  and clear comments to demonstrate the issue soon.

**Comment by CANUSA** [comment]
@patmill @VesaJuvonen  Any chance we could get this triaged? Seems to be a pretty easy to repro, common problem.

**Comment by shaipetel** [comment]
I noticed the same issue, I had to modify an external library I was using to stop rendering a tags with href='#', I replaced it with href='javascript:' and it seemed to work.
Give it a try, although regardless this needs to be fixed.

I noticed it on classic web part pages, not only on modern so it is probably not the modern page that is causing this. Other non-SPFx web parts did not have this issue on the same page.

My web part was using knockout framework.

**Comment by matthong** [comment]
@shaipetel. Thanks for the suggestion. Unfortunately, we can't change the <a> tag as it is rendered by a 3rd party component which we don't have control over.

**Comment by shaipetel** [comment]
well then, good luck. I reported this several months ago and got no feedback so I couldn't wait on our release to production date, I had to create a copy of that library and changed it to work.

Hopefully this will get fixed this time around, seems to be getting more attention this time. It is a very big issue IMHO. I'll keep following this thread.

**Comment by manishgarg1** [comment]
Hi @shaipetel, @matthong 

thanx for reporting the issue and apologies for a delayed response. We have identified a potential issue in our code and will try to provide a fix soon. Once that fix ships, most likely this issue should go away.

regards

**Comment by matthong** [comment]
That will be great! Thank you @manishgarg1.

**Comment by jonathanhotono** [comment]
I can confirm this issue is now fixed. Closing the thread.
