### ISSUE TITLE
Adding propertiesMetadata with isHtmlString nulls existing webpart property value

### ISSUE THREAD

**Issue by clarktozer** [SharePoint/sp-dev-docs#5860]
## Category

- [x] Bug

## Describe the bug

I have an existing webpart with html content stored in a property that i want to be added to search.

Here is a basic example of some HTML in a webpart property (in the webpart manifest json):

```
"properties": {
      "text": "<div><h1 id='test-id'>Testing</h1></div>"
 }
```

I then add the code below for the propertiesMetadata:

```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      'text': { isHtmlString: true }
    };
}
```

On refresh, the value of my property is nulled out so i lose anything i originally had.

## Steps to reproduce

1. Scaffold SPFx webpart
2. Add a property to the webpart eg "text" and with a value that is some basic HTML.
3. Render the HTML string as the webpart output
4. Build and deploy to SharePoint
5. Update the webpart and add the propertiesMetadata to be isHtmlString for your property
6. Build and deploy to SharePoint
7. Value is now null and nothing is being output from the webpart

## Expected behavior

Existing value in the webpart is not nulled out and the value is crawled by search.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome v81
- **Tooling**:  SPFx v1.10.0

**Comment by nithincvpoyyil** [comment]
Hi team,  Any update on this issue ?  I am also getting the same error and using same tooling and environment as @clarktozer. 

##### my configuration:

```
protected get propertiesMetadata(): IWebPartPropertiesMetadata {
    return {
      "content": { isHtmlString: true },
    };
  }
```
#####  value received for `content` property:

```
{ 
content: undefined,
description: "sample webpart",
title: "Test One title",
uniqueId: "xxx-ccvddd"

}
```
Also, In my case, this issue is not happening for new web-parts added, only for existing ones.

**Comment by clarktozer** [comment]
Exact same as me @nithincvpoyyil. We have had to resort to creating powershell scripts for copying and storing the current value when upgrading our webparts, then adding it back again.

**Comment by nithincvpoyyil** [comment]
@clarktozer : As a workaround, I have changed those to  `{ isSearchablePlainText: true }` , hope you knows the cons.

**Comment by cwparsons** [comment]
This is happening for me as well. We have a number of deployed web parts where we want to add the `isHtmlString` property in after they've been used.

We can see that the property is still around in the persisted data when we look at the maintenance mode before republishing the content. We preferably don't want to fix and republish the content for this to work.

**Comment by patmill** [comment]
The right way to do this is not to change the metadata on the existing field.  Changing that metadata changes how the data is stored and retrieved, and you have effectively said "Look for my content over here ==>" and it isn't there.

What you need to do is bump your dataversion, create a new field w/ the right metadata (where new properties will be store), and override the onAfterDeserialize method on your webpart.  You can then take the 'old' property and copy the value to the new property.  In your code, you then only use the new property.
