### ISSUE TITLE
Moving SPFX contextmenu extension above the default contextmenu items

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#5864]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am developing a context menu extension for a document library. The extension always appears beneath all of the default context menu items. Is there any way to move the menu item above the default menu items or at the top of the context menu?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.19
- **Browser(s)**: Chrome v79
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
Look at the `sequence` attribute on the `<CustomAction>` element... https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/hh500259(v=office.14)

I haven't verified this will work for command set extensions... it should, but if it doesn't, you can't impact the order.

**Comment by RafatRashid** [comment]
Thanks a lot for your response. I havent got the opportunity to test it out yet. I will let you know what happens by today hopefully.
