### ISSUE TITLE
Hide top meu in SPFx Personal apps

### ISSUE THREAD

**Issue by mdanielcristian** [SharePoint/sp-dev-docs#5867]
Ability to hide the top menu in a SPFx personal app.
I am developing an enterprise application using SPFx, I have a lot of functionality so I use navigation in my app (react routing) but the tab at the top of the page interferes with it and makes it less usable. 
I would like to have the ability to hide that and have the full screen real-estate to display my app and my custom navigation.

![image](https://user-images.githubusercontent.com/30260770/84480200-db291600-ac9c-11ea-8c72-eb9cbb9a5374.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac71237-d078-e29e-4115-5efbbbebd3ec
* Version Independent ID: 5af01d79-5f92-b256-2872-34266ea14d9f
* Content: [Building Microsoft Teams Tabs using SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction)
* Content Source: [docs/spfx/integrate-with-teams-introduction.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/integrate-with-teams-introduction.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That isn't possible at this time.
