### ISSUE TITLE
How to get a list of the sites that Sharepoint login users belong to?

### ISSUE THREAD

**Issue by cuongdnv2307** [SharePoint/sp-dev-docs#5868]
can get members in the site but How to get a list of the sites that Sharepoint login users belong to?
I can't find this API method?

For example:
Account A belong to Site A , Site B , Site C. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Check out the SharePoint REST API V2, where you can get the list of sites from the _api/v2.0/sites endpoint.

https://docs.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph
