### ISSUE TITLE
BUG: SPFX Client WebPart on sites with German language are not loading

### ISSUE THREAD

**Issue by derCiamas** [SharePoint/sp-dev-docs#587]
#### Category
- [x] Bug

#### Expected or Desired Behavior
Client WebPart should load after being added to the page

#### Observed Behavior
When on site with language set to German the WebParts do not load, there is an error in JavaScript

#### Steps to Reproduce
Create new site, set language to German, try adding client webpart.

The error itself is occuring due to the bad string formatting. In all invocations of application.logClientSideWebPartLoadError and console.log methods, the phrases "Zurück" and "Technische Details" are being placed in quotes, see the code below:

`(function cswp_WPQ17(global) {
    if (global.moduleLoaderPromise) {
        global.moduleLoaderPromise.then(function (application) {
            try {
                application.loadWebPart("g_18dd72f2_46ee_466f_9d53_47cbb7fde3ec", "e4108e42-74a6-4958-ba09-24bc328ff2f4", "<div data-sp-webpart=\"\" data-sp-webpartdataversion=\"1.0\" data-sp-webpartdata=\"{&quot;id&quot;:&quot;e4108e42-74a6-4958-ba09-24bc328ff2f4&quot;,&quot;instanceId&quot;:null,&quot;title&quot;:&quot;Weather&quot;,&quot;description&quot;:&quot;Shows weather for user location&quot;,&quot;version&quot;:&quot;0.0.1&quot;,&quot;properties&quot;:{&quot;description&quot;:&quot;Weather&quot;},&quot;htmlProperties&quot;:null}\" data-sp-splinksapplied=\"true\"><div data-sp-componentid=\"\">e4108e42-74a6-4958-ba09-24bc328ff2f4</div><div data-sp-htmlproperties=\"\"></div></div>", 1, 1, false, []);
            }
            catch (e) {
                if (application != null && application.logClientSideWebPartLoadError != null) {
                    application.logClientSideWebPartLoadError("g_18dd72f2_46ee_466f_9d53_47cbb7fde3ec", "Ein Webpart auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website, und teilen Sie ihm die Informationen unter "Technische Details" mit.");
                    console.error(e);
                }
                else {
                    console.error("Ein Webpart auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website, und teilen Sie ihm die Informationen unter "Technische Details" mit.");
                    console.error(e);
                }
            }
        });
    }
    else {
        console.error("Der Webpart-Wrapper auf dieser Seite kann nicht geladen werden. Verwenden Sie die Schaltfläche "Zurück" im Browser, um es noch mal zu versuchen. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.");
    }
})(window);`

**Comment by VesaJuvonen** [comment]
Thank you @derCiamas for submitting this in here. This seems to be a bug in the platform, which certainly should be resolved asap. Seems to be a duplicate with #596. .

**Comment by srideshpande** [comment]
I will take a look at this issue and will update soon.

**Comment by BigEaseGueldi** [comment]
Just tested the issue on two different tenants with German classic pages -> appears to be fixed!

**Comment by srideshpande** [comment]
@BigEaseGueldi - Thanks for confirming. I will now go ahead and close the issue. 

Thanks again,
Srikanth
