### ISSUE TITLE
Endless gulp rebuild cycle in gulp watch in project as templated from yo generator

### ISSUE THREAD

**Issue by WorldMaker** [SharePoint/sp-dev-docs#5872]
## Category

- [x] Bug

## Describe the bug

I built a fresh SharePoint 2016 SPFX web parts solution using the yo generator (`@microsoft/generator-sharepoint`). When trying to develop/debug the solution with `gulp serve` I was seeing near constant rebuilds causing near constant reloads which made it difficult to develop/debug in the SharePoint Workbench.

It appears that the solution seems easy and it is a bug in the basic generator output: Adding an `"outDir": "lib"` to the solution's `tsconfig.json` file keeps Typescript's generated outputs from compiling to the `src` directory and confusing the gulp watch with changing .d.ts/.js files on every Typescript build. Given other things about the build setup and the `.gitignore` I presume something like `"outDir": "lib"` was intended in the first place.

(Though this may have something to do with tech debt changes in the build pipeline caused by `npm audit fix`.)

I'd file a PR directly to the generator template, but a quick search did not turn up a repository for it, only a suggestion to file feedback in the issues of this repository. (Apologies if I'm mistaken and this is not the correct place.)

## Steps to reproduce

1. `yo @microsoft/sharepoint`
1. Select a target of SharePoint 2016
1. `npm audit fix` (to fix up several *Critical* package updates)
1. `npm i @microsoft/rush-typescript-compiler-3.2` (to get the build and the Workbench working)
1. `npx gulp serve`

## Expected behavior

The `watch` build process in `npx gulp serve` should compile only on user file changes.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Server 2016
- **Framework**: Node.js v10
- **Browser(s)**: FireFox v78 | Chromium Edge v83
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
Couple things... 

- If you're working with SP2016 & this, SPFx v1.1, you should be using Node.js v8 ([see the docs for more details](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#spfx--sharepoint-server-2016))
- Do not run `npm audit fix`... that upgrades dependency package to versions that have not been tested with the SPFx build pipeline.
- Changing the version of TypeScript is not supported in SPFx v1.1 projects... [this capability was added to SPFx v1.8](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#support-for-typescript-27-29-and-3x).

**Comment by WorldMaker** [comment]
Maybe remove the SPFX v1.1 option from the yeoman generator if critical-level npm audit flaws cannot be easily addressed? That seems to me that clearly security support has ended for that framework version.

It also sounds like there should should have been a semver-major version bump somewhere between 1.1 and 1.8 to stop automated tools for assuming backward compatibility. I certainly assumed coming into this that a change in supported SharePoint version would be a semver-level breaking change, and it would have avoided some immediate confusion in the above thread that 1.10 is not 1.1.

**Comment by andrewconnell** [comment]
The core of the issue is your version of Node that you're using. As I said in my response, SPFx v1.1 requires Node.js v8.

@WorldMaker said:
> That seems to me that clearly security support has ended for that framework version.

The report of issues has nothing to do with SPFx itself... it's simply with the tooling. None of those packages are included in the bundle you create and deploy to SharePoint.

@WorldMaker said:
> It also sounds like there should should have been a semver-major version bump somewhere between 1.1 and 1.8 to stop automated tools for assuming backward compatibility. I certainly assumed coming into this that a change in supported SharePoint version would be a semver-level breaking change, and it would have avoided some immediate confusion in the above thread that 1.10 is not 1.1.

Not sure I follow this. 

Think of the SPFx generator like Visual Studio. You can use any version to create a .NET v2 project. It's usually ideal to use the latest version and not an older version... just like SPFx. You use the most current version to create your project.

Once the project is created, the generator (v1.10) doesn't matter at all... the project defines the SPFx version it uses (look in **package.json**). SP2016 FP2 has SPFx v1.1 installed, so that's what your project targets.

**Comment by WorldMaker** [comment]
Node v8 has been EOL since December. Again, it doesn't seem like this version of the framework can be considered in active security support if all of its build tools are out of security support, and have known critical vulnerabilities. I return to my recommendation that to avoid confusing other potential users of the generator that you remove the SharePoint 2016 option if you aren't going to update the build tools for it to a more recent supported version.

**Comment by andrewconnell** [comment]
Thanks for the feedback.

Simply repeating what MSFT has said: all feedback & change requests should be submitted to User Voice. When I add the label to this issue, it will automatically close it as that's where MSFT triages their backlog for changes/feature requests, not this list.
