### ISSUE TITLE
SharePoint Online Script Editor Web Part

### ISSUE THREAD

**Issue by Praveen044** [SharePoint/sp-dev-docs#5880]
## Category

- [x ] Question

## Question
Is it safe using script editor web part in SPO?

If we restrict Add/Customize Pages (ACP) permission in SharePoint to limited users, will it ensure safe to use Script editor web part?

Thanks,
Praveen Kumar Padmakaran

**Comment by wobba** [comment]
It's as safe as you deem fit. If you build the web part with default settings it will not show up on sites with ACP=false. In general exposing random scripting to end users to pose a security threat, thus coding a proper SPFx part with code review is always the more secure approach.
