### ISSUE TITLE
SPFX personal apps not working in the apple ios devices

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#5882]
## Category

- [x] Bug

## Describe the bug

SPFX Personal apps not working in the IOS devices but it is working fine in the android devices and Windows devices.

![image](https://user-images.githubusercontent.com/17681573/84636783-4d695700-af38-11ea-86d9-6fb90937b134.png)

## Steps to reproduce

1. Deploy the spfx in teams as personal apps.
2.Browse the app in the mobile - IOS devices.
3.Clicking the app and it is throwing error.

## Expected behavior

It should work properly in all devices

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Your Developer Environment**: Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome v79 
- **Tooling**: SPFx v1.10.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by andrewconnell** [comment]
Dupe #5823
