### ISSUE TITLE
Automatically make custom filed available in a Document library

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#5884]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Hi
I have developed a field customizer that just shows some text data in a document library. Everything is fine and okay. On deployment what I am trying to do is make the field available in all document libraries of the site where the customizer is installed on. So far on deployment of the customizer a new field gets provisioned but it still needs to be added from settings->add new column and selecting the column from a column group. Is there any way to automatically make the column available?

Thanks in advanced for your time

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SP online
- **Framework**: Nodejs V10.19
- **Browser(s)**: Chrome v83
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
@RafatRashid said:
> Is there any way to automatically make the column available?

I can't answer that directly... but... 

To use the field customizer, which is tied to a site column (aka: Field), you'd need to add that site column to a new document library. Plenty of ways you can do this (content types, list templates, etc).

If you want to modify EXISTING document libraries... it depends...

If you're using content types in a document library, you can add the site column to the document library and have those changes get pushed down where the content type is being used.

If you want to add the customizer to an EXISTING column, you'll need to do that via the SharePoint REST API. Get a reference to the SPField and update the properties to associate the field customizer & it's properties with the field.

**Comment by RafatRashid** [comment]
Could you explain what is 'content types'? and how do I push down? some docs or refrences would be helpful.
And I dont think our use case requires adding to existing column so I would pass on that for the time being.

**Comment by andrewconnell** [comment]
https://support.microsoft.com/en-us/office/introduction-to-content-types-and-content-type-publishing-e1277a2e-a1e8-4473-9126-91a0647766e5
