### ISSUE TITLE
invalid examples in authorization code flow

### ISSUE THREAD

**Issue by mbakhoff** [SharePoint/sp-dev-docs#5886]
Authorization Code OAuth flow page has a bad example of a GET request for getting the auth code. 

Example is: 
```
GET /authcode HTTP/1.1
Host: fabrikam.sharepoint.com/oauthauthorize.aspx?client_id= c78d058c-7f82-44ca-a077-fba855e14d38&scope=list.read&response_type=code&redirect_uri= https%3A%2F%2Fcontoso%2Ecom%2Fredirectaccept.aspx
```

The host header should only contain the host. The path is incorrect, should be `/_layouts/15/OAuthAuthorize.aspx` as documented above the example.

Correct example should be this: 
```
GET /_layouts/15/OAuthAuthorize.aspx?client_id=c78d058c-7f82-44ca-a077-fba855e14d38&scope=list.read&response_type=code&redirect_uri=https%3A%2F%2Fcontoso%2Ecom%2Fredirectaccept.aspx HTTP/1.1
Host: fabrikam.sharepoint.com
```

Right below that there is another issue: 
```If you want a separate consent pop-up dialog, you can add the query parameter IsDlg=1 to the URL construct as shown here: /oauthauthorize.aspx?IsDlg=1&amp;client_id= c78d058c-7f82-44ca-a077-fba855e14d38&amp;scope=list.read&amp;response_type=code&amp;redirect_uri= https%3A%2F%2Fcontoso%2Ecom%2Fredirectaccept.aspx```

The path is wrong there as well. Additionally the `&amp;` escaping is wrong. Should be `?IsDlg=1&client_id=...` as these are separate query params.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be50ae2-2435-480a-0c1e-efca679cd00e
* Version Independent ID: d3c81315-c73e-61c8-2287-dc6e6e5eec5c
* Content: [Authorization Code OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to submit a PR to help improve the docs?
