### ISSUE TITLE
Custom Sharepoint Permissions using Microsoft Graph

### ISSUE THREAD

**Issue by gurleensethi** [SharePoint/sp-dev-docs#5888]
## Category

- [x] Question
- [ ] Typo
- [x] Additional article idea

## Question

Is there a way to modify custom **Sharepoint Online** permissions using Microsft Graph API.

[This article](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-custom-permissions-on-a-list-by-using-the-rest-interface) explains the entire process but uses the old api. Is there a way to do the above steps but using Graph API v1.0

## Environment details (*development & target environment*)

- **Your Developer Environment**: MacOS
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v12
- **Browser(s)**: FireFox
- **Tooling**: VS Code

**Comment by andrewconnell** [comment]
No, the MS Graph only supports CRUD operations on sites, lists, & list items along with following sites: https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0
