### ISSUE TITLE
Error when accessing Sharepoint v1 API

### ISSUE THREAD

**Issue by gurleensethi** [SharePoint/sp-dev-docs#5889]
## Category

- [x] Bug

## Describe the bug

When accessing the Sharepoint API using the following URL:

```
https://<tenant>.sharepoint.com/_api/sites
```

I get the following response for all endpoints:
```
{
  "error_description": "Invalid issuer or signature."
}
```

If I try to access Sharepoint via Graph API, with the same Bearer token, it works. I have enabled all the permissions for Sharepoint in Azure Active Directory.

Is this a bug or am I missing something here?

## Environment details (*development & target environment*)

- **Your Developer Environment**: MacOS
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v12
- **Browser(s)**: FireFox
- **Tooling**: VS Code

**Comment by kongmengfei** [comment]
Hi gurleensethi,

one access token can only against one resource.  From the description, the token is for MS Graph. it cannot be used to request SharePoint API. How did you get this token? Can you share more background info?

Baker Kong
Microsoft SharePoint Community Support

**Comment by gurleensethi** [comment]
@kongmengfei Hi,

I used the below url to obtain the access token:

```
https://login.microsoftonline.com/<secret>/oauth2/v2.0/token
```

What end point should I use to obtain token for Sharepoint's old api?

**Comment by kongmengfei** [comment]
> @kongmengfei Hi,
> 
> I used the below url to obtain the access token:
> 
> ```
> https://login.microsoftonline.com/<secret>/oauth2/v2.0/token
> ```
> 
> What end point should I use to obtain token for Sharepoint's old api?

This endpoint of course can be used to get token for SP, how about the headers or body? Are you using [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)?

**Comment by gurleensethi** [comment]
> > I used the below url to obtain the access token:
> > ```
> > https://login.microsoftonline.com/<secret>/oauth2/v2.0/token
> > ```
> > 
> > 
> > What end point should I use to obtain token for Sharepoint's old api?
> 
> This endpoint of course can be used to get token for SP, how about the headers or body? Are you using [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)?

By client credentials flow I think you mean adding this header `grant_type: client_credentials`, yes I have already added this header. The other headers I have added are `client_id`, `scope` and `client_secret`.

**Comment by kongmengfei** [comment]
> > > I used the below url to obtain the access token:
> > > ```
> > > https://login.microsoftonline.com/<secret>/oauth2/v2.0/token
> > > ```
> > > 
> > > 
> > > What end point should I use to obtain token for Sharepoint's old api?
> > 
> > 
> > This endpoint of course can be used to get token for SP, how about the headers or body? Are you using [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)?
> 
> By client credentials flow I think you mean adding this header `grant_type: client_credentials`, yes I have already added this header. The other headers I have added are `client_id`, `scope` and `client_secret`.

What's the scope?  
I acquired one like this:

![image](https://user-images.githubusercontent.com/57654821/84741302-7a257900-afe1-11ea-8148-0624ba15266b.png)

And you can [decode token](https://jwt.ms/) here to see what claims it contains.

**Comment by kongmengfei** [comment]
And you can also use old ACS endpoint: 

- https://www.anexinet.com/blog/getting-an-access-token-for-sharepoint-online/

**Comment by gurleensethi** [comment]
@kongmengfei The scope was pointing to microsoft graph api, I changed it to my sharepoint, now I use the newly generated token I get the following error:

```
Unsupported app only token.
```

**Comment by kongmengfei** [comment]
> @kongmengfei The scope was pointing to Microsoft graph API, I changed it to my SharePoint site, now I use the newly generated token I get the following error:
> 
> ```
> Unsupported app only token.
> ```

Yes, that's correct. The token has no problem. This is a known issue, refer this thread: 

- https://stackoverflow.com/questions/62356709/unsupported-app-only-token-sharepoint-api-error-even-after-adding-certificate

You need to turn to use "appid + certificate" or old ACS. 

- [Second case: Access token request with a certificate](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#second-case-access-token-request-with-a-certificate)

- [Setting up an Azure AD app for app-only access](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#setting-up-an-azure-ad-app-for-app-only-access)

Baker Kong
Microsoft SharePoint Community Support

**Comment by gurleensethi** [comment]
@kongmengfei I was trying to authenticate with certificate-based authentication, all the examples use PowerShell to create the certificate, how can I create a certificate on a MacOS. And how to get `client_assertion` once the certificate is created.

**Comment by kongmengfei** [comment]
Hi gurleensethi,

I do not have MacOS environment. You can try to install [poweshell on MacOS](https://github.com/PowerShell/PowerShell/blob/master/README.md) to create a certificate. 

We cannot directly generate client_assertion, we need to achieve it through code. Here i attached my test demo, it's a console app that generates a client_assertion.

- [test demo](https://github.com/kongmengfei/sharedproject/blob/master/ConsoleApp-bkwebTest/ConsoleApp-bkwebTest/Program.cs)

In the above demo, I have attached my test certificates. 

![1](https://user-images.githubusercontent.com/57654821/84872068-f6888c80-b0b3-11ea-8281-596f73d9aefa.jpg)

Upload .cer file to your AAD registered APP: 
![2](https://user-images.githubusercontent.com/57654821/84872170-1f108680-b0b4-11ea-9cd0-aab7fde95764.jpg)

Result: 
![3](https://user-images.githubusercontent.com/57654821/84872407-731b6b00-b0b4-11ea-9d11-5e20efe7b235.jpg)

Copy the assertion and go ahead to the client certificate flow:

![4](https://user-images.githubusercontent.com/57654821/84872614-b1b12580-b0b4-11ea-806a-d19f13efd5da.jpg)

This access token could access SharePoint Rest API.

***Note**, Do not forget to replace the variables with your own value in the code.

Baker Kong
Microsoft SharePoint Community Support
