### ISSUE TITLE
Web part does not render as soon as editing web part properties

### ISSUE THREAD

**Issue by kavitajoshi** [SharePoint/sp-dev-docs#5895]
Web part renders fine on load but does not render as soon as editing web part properties

Getting Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container. Happens when calling this.context.statusRenderer.displayLoadingIndicator(this.domElement, 'options');  commenting out this line resolves the issue but does not show loading indicator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fe85ee-ede7-1cac-d524-d448051dfc45
* Version Independent ID: 1ee793b9-d693-4967-988f-53c3657b5970
* Content: [Use cascading dropdowns in web part properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties)
* Content Source: [docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unable to repro this... can you share more about the issue, like a copy of the project in a public GH repo so we can repro this? I recently ran through this tutorial and everything worked as expected...
