### ISSUE TITLE
Official method to get Azure AD Token on SharePoint classic pages

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#5897]
## Category

- [x] Question

## Question
Hello everyone,

we are currently looking for an official method to get an azure AD Token on classic SharePoint pages. SPFX already contains clean methods to get a token using the `AadTokenProvider`-class but SPFX can only be used on classic pages if an SPFX webpart is present.

Is there a similar official method or rest endpoint to get a token on classic pages without having an spfx webpart at the page (e.g. Application pages like `/_layouts/settings.aspx`)?

We now there are "hacky / unofficial" ways to get a token (e.g. manually calling [/_forms/spfxsinglesignon.aspx](https://spblog.net/post/2018/09/15/Calling-MS-Graph-API-from-classic-SharePoint-pages)) but this not fail-safe.

We still have dozens of components and solutions working on classic pages and it will take yours until Microsoft replaces all of the classic page application pages. More and more of this stuff is more and more using MS Graph etc. therefore getting a token is a must have here.

## Environment details (*development & target environment*)

- **Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Javascript
- **Browser**: Chrome v83 | Safari v22 | IE v11 | Edge

**Comment by andrewconnell** [comment]
The short answer is no, there's no specific way to obtain an AAD token without SPFx. That feature was added only for SPFx. 

With that being said, that's just an API to an endpoint. You can use the browser's network tab to monitor the endpoint the SPFx endpoint uses to call to obtain the access token and use it. There's nothing server-side in the endpoint that can tell that it was/wasn't SPFx that requested the token so that should work...

**Comment by MrTantum** [comment]
Thanks for the clarification Andrew.

Yes as already stated we are using some self build logic to get the token by reproducing the steps from the AadTokenProvider but this always has the chance that Microsoft changes something in the background and then it's not working anymore (e.g. changes on /_forms/spfxsinglesignon.aspx).

Maybe this we be an interesting topic for a new community project. A bet that there are still hundreds of developers working with classic pages and would like to use the modern SharePoint API's there to.
