### ISSUE TITLE
Webparts Package Errors 

### ISSUE THREAD

**Issue by aaronshore** [SharePoint/sp-dev-docs#5898]
Hi guys, I have downloaded https://github.com/pnp/sp-dev-fx-webparts and going through each one to build a package so that I can test on my local tenant.  I get errors with some web parts but bot others using the same commands.

Am I able to download the packages somewhere?  I was just after the react web parts.  If there is no way to download the packages, can some please let me know what tools I should be using to build the web part packages.

Thanks for all your time on this.

**Comment by OS-Lee** [comment]
Hi aaronshore,

Configure your dev environment as official document as below.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

Then, follow the guideline to build/test the webpart.

cd webpart folder

npm install

gulp serve

**Lee
Microsoft SharePoint Community Support**

**Comment by JarbasHorst** [comment]
Hello @aaronshore 

additional to Lee's comment, I would like to suggest you to have a look the **Minimal Path to Awesome** section which you can find in each web part's readme documentation. This section explains the required steps to run the sample web part. E.g.: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-app-settings#minimal-path-to-awesome

Regards,
Jarbas

**Comment by aaronshore** [comment]
> Hi aaronshore,
> 
> Configure your dev environment as official document as below.
> 
> https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
> 
> Then, follow the guideline to build/test the webpart.
> 
> cd webpart folder
> 
> npm install
> 
> gulp serve
> 
> **Lee Microsoft SharePoint Community Support**

Hi Lee thanks for that...I did get all that setup but some web parts compile and some don't.  Do I report errors on each one on this forum?

**Comment by aaronshore** [comment]
> Hello @aaronshore
> 
> additional to Lee's comment, I would like to suggest you to have a look the **Minimal Path to Awesome** section which you can find in each web part's readme documentation. This section explains the required steps to run the sample web part. E.g.: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-app-settings#minimal-path-to-awesome
> 
> Regards,
> Jarbas

Hi Jarbas and thanks for the suggestion.  I am not a developer and just trying to see if I can get the web parts on my tenant.  Do I just report each error I am getting on this thread or create a thread for each one?

**Comment by andrewconnell** [comment]
Please use the issue list in that repo for questions on that repo... that's what it's there for :)

This issue list is for general SP development questions/issues.
