### ISSUE TITLE
ConfigurationUrl in manifest spfx

### ISSUE THREAD

**Issue by hntlk** [SharePoint/sp-dev-docs#5900]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question
How can I redirect to webpart by teamshotedapp.aspx
I have flie manifest.json and file html be hosted in local like below:

`{
  "$schema": "https://developer.microsoft.com/json- 
 schemas/teams/v1.5/MicrosoftTeams.schema.json",

  "manifestVersion": "1.5",
  "packageName": "HelloWorldWebPart",
  "id": "59ac54d1-4e14-4617-8de8-2a5b7bec576a",
  "version": "0.0.0.51",
  "developer": {
    "name": "Corporation",
    "websiteUrl": "https://www.google.com",
    "privacyUrl": "https://www.google.com",
    "termsOfUseUrl": "https://www.microsoft.com/servicesagreement"
  },
  "name": {
    "short": "HelloWorldWebPart"
  },
  "description": {
    "short": "Test config tab",
    "full": "Test config tab full desc."
  },
  "icons": {
    "outline": "59ac54d1-4e14-4617-8de8-2a5b7bec576a_outline.png",
    "color": "59ac54d1-4e14-4617-8de8-2a5b7bec576a_color.png"
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
     "configurationUrl": "https://localhost/?componentId=59ac54d1-4e14-4617-8de8-2a5b7bec576a",
     "canUpdateConfiguration": true,
      "scopes": [ "team" ]
    }
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
}
`

### Here code in html. (configurationUrl)
<script src="https://statics.teams.microsoft.com/sdk/v0.4/js/MicrosoftTeams.min.js"></script>

`			

                       var url = '';
			var websiteUrl = '';
			var context;
                      // Initialize the Microsoft Teams Library
			microsoftTeams.initialize();

			// Set the 'Save' Button state based on name field content
			$('#name').on('input', function () {
				if ($('#name').val().length != 0) {
					microsoftTeams.settings.setValidityState(true);
				}
				else {
					microsoftTeams.settings.setValidityState(false);
				}
			});

			// Save handler when user clicked on Save button
			microsoftTeams.settings.registerOnSaveHandler(function(saveEvent){
				microsoftTeams.getContext(function(context) {
					color = $('#color').val();
					name = $('#name').val();
					numdays = $('#numdays').val();
					console.log('context',context);
					var teamSiteDomain = context.teamSiteDomain;
					var teamSitePath = context.teamSitePath;
					var locale = context.locale;
					var urlParams = new URLSearchParams(document.location.search);
					var componentId = urlParams.get('componentId');
				var url = 'https://'+teamSiteDomain+teamSitePath+ '/_layouts/15/TeamsLogon.aspx?SPFX=true&dest='+teamSitePath+'/_layouts/15/teamshostedapp.aspx%3F3FopenPropertyPane=true%26teams%26personal%26componentId='+componentId +'%26forceLocale='+locale;
						
					microsoftTeams.settings.setSettings({
						entityId: "redIconTab",
						contentUrl: url,
						suggestedDisplayName: name,
						websiteUrl: websiteUrl
					});
					saveEvent.notifySuccess();
				});
			});

		</script>`

If i config contentUrl in html like above, it will redirect to PersionalApp. It works But webpart properties pane ,its showing error saying **No settings to change for this web part**.
I think the root cause from manifest file. 
I want to redirect TeamsWebpart instead of PersionalApp like contentUrl below:
https://xxxx.sharepoint.com/sites/test123/_layouts/15/teamshostedapp.aspx?list=9fcf4c89-f109-4427-af7f-5e883d29f361&id=11&webPartInstanceId=8fc53faa-a18f-466b-ab07-c0df7f2b3494
How can i get _list_, _id_ and _webPartInstanceId_ to pass to query of contentUrl, I dont know exactly these param mean and how to get it.

> *Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Those values are set dynamically by SPFx & Teams when you install the tab within a channel. More information on how the URLs are generated can be found here, but it's not intended to generate those values dynamically: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart

In the future, please use the new issue template when submitting issues.
