### ISSUE TITLE
spfx webpart deploying to site features not site collection features

### ISSUE THREAD

**Issue by mbalcarek** [SharePoint/sp-dev-docs#5901]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question
Hello,
I have deployed an SPFx webpart which contains site columns and content type definitions. I see the feature in site features and not the site collection features. Is this expected? I want the feature to be available to the whole site collection, including sub-sites. Is there something I need to change?

![image](https://user-images.githubusercontent.com/21264424/84918277-9bd43e00-b07d-11ea-9234-61c114aeae2d.png)

**Comment by andrewconnell** [comment]
Yes, that's expected. When installing the app, it's installed int he root site in the site collection.
