### ISSUE TITLE
accept header not respected for json

### ISSUE THREAD

**Issue by rdnobrega** [SharePoint/sp-dev-docs#5902]
When doing REST calls against ProjectServer installed over SP2013, the "accept" header gets ignored in some instances.

## Steps to reproduce

The endpoint is '/_api/ProjectServer/Projects'.

The response is ok for:

Accept: application/json;odata=verbose

The response is in XML for everything else:

Accept: application/json;odata=nometadata
Accept: application/json;odata=minimalmetadata

Also, there is no options for compressing the response, which makes it absurdely large. Tested for gzip, deflate, compress & br. I'm trying to construct an app and for mobile this huge amount of data is not only useless but also a burden in the client's data plan.

**Comment by andrewconnell** [comment]
This might be more suited to post to a ProjectServer forum... 

For the compression question, you might be able to do something at the IIS level, but I'm not sure if that's supported or not.

SP2013's OData3 support only included the **Accept: application/json;odata=verbose** header. Additional headers for JSON Light was added in SP2013 SP1... more info in the links below... but I strongly encourage you to verify this is supported with Project Server before upgrading dependencies.

https://www.microsoft.com/en-us/microsoft-365/blog/2014/08/13/json-light-support-rest-sharepoint-api-released/

https://support.microsoft.com/en-us/help/2817429/description-of-microsoft-sharepoint-server-2013-service-pack-1-sp1
