### ISSUE TITLE
SyntaxError in appPageHost.aspx

### ISSUE THREAD

**Issue by db3005** [SharePoint/sp-dev-docs#5912]
## Category

- [x] Bug

## Describe the bug

When opening any WebPart on the layouts appPageHost.aspx page with a valid componentId 
({siteurl}/_layouts/15/appPageHost.aspx?componentId={webpartId}) a SyntaxError occurs and the page displays only the top bar:

![image](https://user-images.githubusercontent.com/32265743/85102910-e97bb280-b205-11ea-80ef-70365134fd13.png)

The error in the aspx file looks like this:

![image](https://user-images.githubusercontent.com/32265743/85102933-fbf5ec00-b205-11ea-861d-931870066f98.png)

## Steps to reproduce

1. Create a spfx webpart
2. Deploy the webpart on your tenant
3. Open the webpart on the appPageHost.aspx

## Expected behavior

The page should render the webpart

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Javascript
- **Browser(s)**:  Chrome v83.0.4103.97 | FireFox v77.0.1
- **Tooling**: SPFx v1.8.2

### Additional context

This issue affects multiple tenants, pre release tenants and standard release tenants.

**Comment by NicolasMCAG** [comment]
Hello!

I'm currently facing this issue as well, and it's blocking some developments in my team.

Can you provide any news, please?

Thank you, and kind regards.

**Comment by patmill** [comment]
Sorry for the delay.  Working back through old issues.  When I use this on current sites, it is working.  Are you still facing this issue?
