### ISSUE TITLE
Are we still maintaining 'SharePoint .NET Server, CSOM, JSOM, and REST API index'?

### ISSUE THREAD

**Issue by xieofxie** [SharePoint/sp-dev-docs#5914]
From my understanding, when we are developing SharePoint Add-in, we need to use these APIs to communicate with SharePoint service to do CRUD etc.

However, it seems they are no longer maintained. For example here https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245160(v=office.15)?redirectedfrom=MSDN.

So will it be updated to support function like this https://docs.microsoft.com/en-us/javascript/api/sp-http/aadtokenproviderfactory?view=sp-typescript-latest by any chance?

Or we just should not use Add-In any more and use Framework instead.

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94956608-25b4-0605-f43d-d161ebdde905
* Version Independent ID: 5a5b71db-be77-2ac8-7b9f-82f13961d4fa
* Content: [SharePoint .NET Server, CSOM, JSOM, and REST API index](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index)
* Content Source: [docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
- The SharePoint Framework is the recommended approach to extending & customizing SharePoint.
- Add-ins are still supported, so you'd an use them.
- The API you reference (JSOM) is still supported, but Microsoft isn't investing in them at this time. The recommended approach is to use the SharePoint REST API.

@xieofxie said:
> So will it be updated to support function like this https://docs.microsoft.com/en-us/javascript/api/sp-http/aadtokenproviderfactory?view=sp-typescript-latest by any chance?

I can't speak for MSFT, but I don't expect you will see that added to the JSOM.

**Comment by xieofxie** [comment]
Thanks! I have confirmed internally that add-in is almost deprecated. I closed it now.
