### ISSUE TITLE
SharePoint Starter Kit - Followed Sites Error

### ISSUE THREAD

**Issue by aaronshore** [SharePoint/sp-dev-docs#5919]
Hi All,

I am trying to compile, bundle and package the web part from SharePoint Starter Kit - Followed Sites but get the following error when I run **npm install**:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@starter-kit%2fshared-library - Not found
npm ERR! 404
npm ERR! 404  '@starter-kit/shared-library@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-followed-sites'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Any idea how I can fix this please?

Thanks for all your time on this.

**Comment by andrewconnell** [comment]
Please post questions about the starter kit to the starter kit's repo: https://github.com/pnp/sp-starter-kit
