### ISSUE TITLE
Secure access with SAS

### ISSUE THREAD

**Issue by RhoninPL** [SharePoint/sp-dev-docs#5920]
Can I secure azureedge/storage container with a SAS key? So it is not possible to access anonymously? Are there any other ways to secure it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e46a7b-157b-0974-fced-df23d1536bb4
* Version Independent ID: 14b1a252-149f-356c-b19b-ffd312615c1c
* Content: [Deploy your SharePoint client-side web part to Azure CDN](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn)
* Content Source: [docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Please to the Azure CDN documentation on options to secure the CDN.

However, there's nothing in SPFx that will support adding a SAS key to the request for resources.

If you want to secure the Azure CDN, you can use things like the support baked into the Azure CDN for IP or GEO restrictions. You can also use CORS to block requests.
