### ISSUE TITLE
Multi Select combo box , UI Fabric , stop working in SPFX Control

### ISSUE THREAD

**Issue by Sachindagar** [SharePoint/sp-dev-docs#5924]
## Category

- [x] Bug

## Describe the bug

Multi Select combo box , UI Fabric , stop working in SPFX Control. 
We are using Multi Select Combo box. It was working till yesterday however sudden its stop working. Whenever we are trying to select multiple values, the values are not selected. 

Post selection, the values are not populated in the combobox 

![image](https://user-images.githubusercontent.com/26018001/85387276-f5f66700-b587-11ea-9281-3a23ac41e0ca.png)

## Expected behavior

Multi select option should be selected.

## Environment details (*development & target environment*)
- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: SharePoint Online
- **Framework**: Node.js 
- **Browser(s)**: Chrome & IE edge
- **Tooling**: VS Code

**Comment by andrewconnell** [comment]
Need more context... OUIFR version used, have you tried this outside of SPFx to isolate if it's an issue with OUIFR or SPFx, etc?

**Comment by Sachindagar** [comment]
> Need more context... OUIFR version used, have you tried this outside of SPFx to isolate if it's an issue with OUIFR or SPFx, etc?

Code was working fine since last 2 months here is the code that we are using

import { ComboBox, IComboBox, IComboBoxOption, Async, colProperties } from 'office-ui-fabric-react/lib/index';

<ComboBox 
	autoComplete={'on'}
	placeholder="Select Model Code" id="ddlModelCode" label="Model Code"
	options={this.state.ModelCodeOptions}  
	multiSelect
	onMenuDismissed={this._OnChangeModelCode_get_VersionCode.bind(this)}
    disabled={this.state.flagVehicleLineHasValue == false}
/>

**Comment by andrewconnell** [comment]
Respectfully... 

> Need more context... OUIFR version used, have you tried this outside of SPFx to isolate if it's an issue with OUIFR or SPFx, etc?

**Comment by Sachindagar** [comment]
Hi Andrew, 

UI Fabric Version - 1.10.0, not tried yet outside of SPFX.  However, we are trying to test outside of SPFX as well. But the thing here is , it is a break as it was working fine till yesterday morning. There might be some issue with OUIFR or SPFX ,

**Comment by Sachindagar** [comment]
Getting error while using OUIFR combo box in SPFX

**Comment by andrewconnell** [comment]
I don't believe this is an issue with SPFx, rather it's an OUIFR issue. I've seen other people report issues recently with OUIFR... you might also try posting to their project's issue list...

**Comment by Sachindagar** [comment]
Yes, issue with OUIFR not with SPFX. Can you please advise where can i log the issue with OUIFR?

**Comment by andrewconnell** [comment]
https://github.com/microsoft/fluentui

it says Fluent, but that's the renamed Office UI Fabric React.
