### ISSUE TITLE
Query sites by classification

### ISSUE THREAD

**Issue by TomekPi** [SharePoint/sp-dev-docs#5925]
Is there a possibiltiy to query sites by classification (or include classification in `SPOSitePropertiesEnumerable`)?
We need to monitor if users change classification of modern sites and currently I see no option beside querying each site, which is not acceptable from performance point of view.

It would be best if `Microsoft.Online.SharePoint.TenantAdministration.SiteProperties` class could include `Classification` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27643fd2-8059-f411-224b-bd0815aacc8f
* Version Independent ID: bd410f9a-a3f2-9222-7d4a-2271d7f6161d
* Content: [SharePoint ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification)
* Content Source: [docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-site-classification.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Search API may be an option... @wobba you know if this is possible with the Search API?

**Comment by wobba** [comment]
Nothing in search. Afaik you have to load up the Site object per site and check the `Classification` property as the property is not stored on the tenant site object. You can get this value both via CSOM and REST.

**Comment by TomekPi** [comment]
So in summary, currently no option for monitoring change of the Classification for many sites.
Do you know if there is a chance to add this property in tenant site object?

**Comment by andrewconnell** [comment]
@TomekPi said
> Do you know if there is a chance to add this property in tenant site object?

That's what @wobba said:
> you have to load up the Site object per site

Or are you asking something different?

**Comment by TomekPi** [comment]
No, I'm asking about `Microsoft.Online.SharePoint.TenantAdministration.SiteProperties` class which we can use to get multiple sites with one request.

**Comment by andrewconnell** [comment]
Ah... ok that would fall into a feature request. Best to post that on user voice where engineering regularly reviews requests.
