### ISSUE TITLE
Localizing a default property in SPFx

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#593]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I am looking for guidance regarding localization of the default values of a webpart.

#### Expected or Desired Behavior
I would expect to use a similar mechanism that exists for manifest (title, description and group) and/or for string manipulations. For example, when I use a PropertyPaneTextField, I would expect 1 of those 2 scenarios : Being able to use the value property (or default value) or being able to localize the properties config options in the manifest. As discussed in the issue #372 , the right approach to set default values should be from the manifest.

### Observed Behavior
There is no way to localize the properties config options in the manifest and value property of the PropertyPane control can't be used for default values.

This approach is not working : 

`"preconfiguredEntries": [{
     ...
    "properties": { 
      "postsCount": 3,
      "readMoreText": {
        "default" : "Read more",
        "fr-FR": "En lire plus"
      }
    }
  }]`

This approach is not working : 

`"preconfiguredEntries": [{
     ...
    "properties": { 
      "default": {
      "readMoreText": "Read more"
      },
      "fr-FR": {
        "readMoreText": "En lire plus"
     }
    }
  }]`

This approach is not working : 

`PropertyPaneTextField('readMoreText', {
                  label: strings.ReadMoreTextFieldLabel,
    value: strings.ReadMoreTextDefaultValue
                }),`

**Comment by nickpape-msft** [comment]
Thanks for the feedback, we will investigate the issue.

**Comment by PooLP** [comment]
Hi,

I have the same problem, you have any news ? (Framework version 1.4.0)

Thanks.

**Comment by PooLP** [comment]
Hi,
`preconfiguredEntries` for `Title`, `Description` etc... is localised, but not for `properties`, I do not know if it's a bug, one forgets or new functionality, in any case, it would be a good feature.

**Comment by andrewconnell** [comment]
Correct @PooLP ... I should have been more specific. the `properties` aren't localized. My understanding is that is by design, so it would fall in the category of a feature request.

**Comment by PooLP** [comment]
ok, thanks for response ... Localization is a real problem for Microsoft, they are not very good on this part ;)

**Comment by andrewconnell** [comment]
The values in the `properties` section would need to be localized on each web part as the properties differ from web part to the web part and from each instance, it's running to another instance. Status properties (like Title, Description, etc) can be localized as they are well known.

Localizing strings in the web part are also well known in the code.

But content... that has to be handled by the developer. This article describes one such approach: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts#localize-web-part-settings-values
