### ISSUE TITLE
primordials is not defined    at fs.js:27:26

### ISSUE THREAD

**Issue by rahulz55** [SharePoint/sp-dev-docs#5934]
Spfx gulp trust command run but issue is there my node version  is v12.13.0 

![error](https://user-images.githubusercontent.com/10138440/85503297-ec601400-b606-11ea-8ee8-cbcff8e1dfa1.jpg)

**Comment by andrewconnell** [comment]
SPFx isn't supported on Node.js v12. Please see the docs for the current supported versions: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
