### ISSUE TITLE
prompts are different now (@microsoft/generator-sharepoint@1.10.0)

### ISSUE THREAD

**Issue by xieofxie** [SharePoint/sp-dev-docs#5937]
See the following screenshot:
![image](https://user-images.githubusercontent.com/2876650/85510846-884f4700-b62a-11ea-800d-d3c2ed2732f4.png)
Note that for certain selections, you can't choose extension type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, it's a bit unclear what you are asking. Once you select the type of component to create, it provides you the option to select the type of extension you want to create. 

![image](https://user-images.githubusercontent.com/7944457/85568719-29201100-b5ef-11ea-8ebc-295fcc0a8777.png)

**Comment by andrewconnell** [comment]
@bcameron1231 agreed... but I think the doc could be a bit more clear in the 2nd question. If they selected SP2016, extensions isn't an option.

We recently updated the doc to remove all unnecessary prompts form the doc if the options selected had no impact on the tutorial. This is one question I shouldn't have removed.

Fixing...
