### ISSUE TITLE
What does the "SPAuditEventType.FileFragmentWrite" mean? 

### ISSUE THREAD

**Issue by kongmengfei** [SharePoint/sp-dev-docs#5939]
Hi All,
Can i know what's the meaning of SPAuditEventType.FileFragmentWrite? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff100b47-97bb-e8e9-5a60-b7e0021b343b
* Version Independent ID: 111c54de-8869-8ac3-82b2-3f48307c744c
* Content: [SPAuditEventType Enum (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spauditeventtype?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPAuditEventType.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPAuditEventType.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by andrewconnell** [comment]
I believe it means only part of a document has been updated.

**Comment by kongmengfei** [comment]
> I believe it means only part of a document has been updated.

but it never is triggered when i update a doc in a library.
