### ISSUE TITLE
Re-render web part after Custom Property Pane Field Value has been changed

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#594]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

In previous drops we had a `onPropertyChange` method that could be used in Custom Property Pane Field to update web part field and initiate re-render.

in GA drop this method is deprecated. And we're using next construction:

- first, we're passing on web part properties and `onPropertyPaneFieldChanged` to Custom Property Pane Field
- then, when needed, we use next construction:
`
// this here is Custom Property Pane Field
`
`this.properties.webPartProperties[targetProperty] = newValue;
`
`
this.properties. onPropertyPaneFieldChanged(targetProperty, oldValue, newValue)
`
It works fine in Workbench and `onPropertyPaneFieldChanged` initiates re-render of the web part.

But if you install your web part to the SharePoint Online, re-render will not be initiated. The reason for that is that in new code deployed to SharePoint re-render is called in **internal** `onPropertyPaneFieldChanged` method that is not available for us.

So, the question is **how to correctly initiate web part re-render after Custom Property Pane Field change?**

Thanks in advance

**Comment by waldekmastykarz** [comment]
Have you considered using the `this.context.propertyPane.refresh();` method, where `this` refers to the web part class instance?

**Comment by AJIXuMuK** [comment]
Hello Waldek,
`this.context.propertyPane.refresh()` refreshes Property Pane itself... It doesn't set any values to web part properties and also it doesn't initiate web part's re-render.
So, unfortunately, it is useless for the situation described here...

**Comment by OlivierCC** [comment]
Hi Alex (@AJIXuMuK), 

I see the same problem as you. In fact this does not come from the GA, but since version 1.1.1 of the sp-webpart-base package. Based on my research, in previous releases, the `onPropertyPaneFieldChanged `method of the `BaseClientSideWebPart `class called another method called `this._renderWithAccessibileTitle`, that refreshed the webpart. Since version 1.1.1 this code has been removed and so it does not work anymore. I have not found workaround yet, but I am looking for. I am generated like you by this change, my library (sp-client-custom-fields) no longer work with this version. I'll let you know if I find an alternative.

**Comment by OlivierCC** [comment]
The call to this.`_renderWithAccessibileTitle `has been move to a new method called `_afterPropertyUpdated`. but this method is private... ;-(

**Comment by OlivierCC** [comment]
@AJIXuMuK, in fact we can just use the render method of a BaseClientWebPart to refresh the web part. A code like that can work:

if (!this.disableReactivePropertyChanges)
      this.render(); 

The render method is protected, so you need to give it as argument for your custom field class. I will update the sp-client-custom-fields lib like that you can reuse similar approach if you want.

Regards,

Olivier

**Comment by AJIXuMuK** [comment]
Hi Olivier,

Yup, I've implemented it in similar way (code below). But I still want dev team to answer what is the "correct" way of doing it from their point of view.
I think that custom property pane fields should have the same behavior as out-of-the-box.

My code:
First, implement custom method in web part:
```
/**
 * Provides logic to update web part properties and initiate re-render
 * @param targetProperty property that has been changed
 * @param newValue new value of the property
 */
  public onCustomPropertyPaneFieldChanged(targetProperty: string, newValue: any) {
    const oldValue = this.properties[targetProperty];
    this.properties[targetProperty] = newValue;

    this.onPropertyPaneFieldChanged(targetProperty, oldValue, newValue);

    // NOTE: in local workbench onPropertyPaneFieldChanged method initiates re-render
    // in SharePoint environment we need to call re-render by ourselves
    if (Environment.type !== EnvironmentType.Local) {
      this.render();
    }
  }
```

Then, pass this method as a parameter to custom property pane field:
```
CustomField('prop', {
  // ...
  onPropertyChange: this.onCustomPropertyPaneFieldChanged.bind(this)
})
```

**Comment by OlivierCC** [comment]
Yes, 100% agree. In my vision (but I'm also interested by the dev team answer, the custom field API has been conceptualized to use a refresh method inside the web part code. So a call to `render `is acceptable. But it's not a great design if you want to implement reusable and packaged custom fields, where we want to have a way to force or not the refresh of the web part by an action implemented in an external component.

To not have to write a `onCustomPropertyPaneFieldChanged `  in every web part that use a custom field,  today I'm implementing like that:

```
CustomField('prop', {
  // ...
  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
  render: this.render.bind(this)
})
```

and in the custom field code:

```
this.props.properties[this.props.targetProperty] = newValue;
this.props.onPropertyChanged(this.props.targetProperty, oldValue, newValue);
if (!this.props.disableReactivePropertyChanges)
      this.props.render(); 
```

But like you I think that a clear position about the dev team is better to have a clean vision for the future.

Regards,

Olivier

**Comment by srideshpande** [comment]
Hello @AJIXuMuK 

Thanks for bringing this up. Today there is no way for property pane to know if something has changed in the custom field. Hence we cannot re-render the web part. However, as I replied to your other thread regarding custom field, we have made few changes to the custom field properties which will now enable the developer to let the property pane know that something has changed within the custom field.

Jus to re-iterate what I said in the other thread -

> The change is made to resolve this issue. You will be getting it in the next release. The change we have made is, the `onRender` prop on the custom field will now have a `changeCallback` method passed in  from the framework. This should be invoked if you want the framework to know that something has 
> changed within the custom field. This will trigger the regular property pane field change flow. This will help resolve your issue.

> This is how the `onRender` prop will look now on the `IPropertyPaneCustomFieldProps`

> ~~~
> /**
>    * This API will be called once the custom field is mounted on the host element.
>    *
>    * @param domElement - DOM element on which the custom control needs to be mounted.
>    * @param context (optional) - Instance specific context. This context was passed in the constructor.
>    * @param changeCallback (optional) - Callback called when a field changes within the custom field.
>    *  This will allow the property pane to be aware of the change and act accordingly.
>    *  @param targetProperty (optional) - associated target property from the properties bag.
>    *    if not provided then a custom value which is unique at the custom field level is assigned,
>    *    which will be in the form of '__CustomField_<key provided when the custom field is created>'.
>    *  @param newValue (optional) - new value of the property.
>    *    newValue is ignored if targetProperty is not specified.
>    */
>    onRender: (
>      domElement: HTMLElement,
>      context?: any,
>      changeCallback?: (targetProperty?: string, newValue?: any) => void) => void;
> ~~~

Please let me know if you still need any more details in this regard.

Thanks,
Srikanth

**Comment by AJIXuMuK** [comment]
Hello @srideshpande ,

Thanks for the follow-up. Will wait for the next release 👍

**Comment by umaknow-francis** [comment]
@OlivierCC , I would like to add to your last message that you added this line in your [current code ](https://github.com/OlivierCC/sp-client-custom-fields/blob/master/src/PropertyFieldDocumentPickerHost.tsx)which really stores the new value in the webpart properties: 
`this.props.properties[this.props.targetProperty] = newValue;`
