### ISSUE TITLE
Error when running sample 'AuthenticationManager' Class

### ISSUE THREAD

**Issue by Greg-Hitchon** [SharePoint/sp-dev-docs#5942]
Hello,

CSOM Version: 16.1.20211.12000

When attempting to add the sample 'AuthenticationManager' class to a project the following error is encountered:

**'ClientContext' does not contain a definition for 'FormDigestHandlingEnabled'**

When using the previous (non-standard) version the project compiles correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .Net Standard instead of CSOM for .Net Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by vman** [comment]
@jansenbe did [mention in his demo](https://www.youtube.com/watch?v=mb6OEDOhVW4&feature=youtu.be&t=439) that the FormDigestHandlingEnabled property is redundant so my guess is this was removed from the published version but it still exists in the docs.

**Comment by Greg-Hitchon** [comment]
Yeah, it seems to work just commenting it out.

**Comment by VesaJuvonen** [comment]
As noted by @vman, this was by design related on the authentication changes with the package. All other areas are working in parity between different versions.
