### ISSUE TITLE
Please provide a License for CSOM compatible with .NET Standard cross platform?

### ISSUE THREAD

**Issue by mattmckinstry** [SharePoint/sp-dev-docs#5948]
FYI your license link for the package https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM is broken

However, I managed to track down a license through some googling:

MICROSOFT SHAREPOINT CLIENT COMPONENTS.  

This specifically forbids distributing on any platform other than Windows.

iii. Distribution Restrictions. You may not

        * distribute Distributable Code to run on a platform other than the
          Windows platform;

Are there any plans to update the License around this product now that it has gone .NET Standard and effectively cross platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .Net Standard instead of CSOM for .Net Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good points... I'll raise with engineering as this is something MSFT needs to comment on being licensing.
