### ISSUE TITLE
Planner tasks assignee is not getting updated properly using Graph API

### ISSUE THREAD

**Issue by premakumaris** [SharePoint/sp-dev-docs#5949]
Describe the bug
When we try to update assignee of planner tasks, assigned user details not getting updated properly. Task is assigned to User-A, when I try to update the the task with User-B, the User-B gets appended to Assignee and the assigned users will be User-A and User-B instead of just User-B. Here we are trying to update the task details using graph API patch operation. Graph API patch operation is not returning any issues but user details are not getting updated properly.

To Reproduce
Used below graph API call to update the assigned users

this.graphClient = await this.webPartContext.msGraphClientFactory.getClient();
const taskDetails = await this.graphClient
.api(planner/tasks/${taskId})
.version('v1.0')
//.header(If-Match, etag)
.headers({["Prefer"]: "return=representation", ["if-Match"]: etag, ["Content-type"]: "application/json"})
.patch({assignments : Userdetails});

Expected behavior
Task should get updated with only User-B

**Comment by andrewconnell** [comment]
Dupe... as I said in my comment on #5940 yesterday, this isn't related to SharePoint... this is a Graph issue. Please refer to their forums: https://developer.microsoft.com/en-us/graph/support

Plus, in the future, please use the template we provide on new issues. As that template states, if you don't complete the sections provided, we'll close the issue as an incomplete submission.
