### ISSUE TITLE
How can I trigger a site workflow via Sharepoint API

### ISSUE THREAD

**Issue by vscavettaGH** [SharePoint/sp-dev-docs#5951]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am trying to use PNPonline to invoke a webrequest in Powershell that triggers a site workflow in Sharepoint Online

## Environment details (if applicable)

- **Your Developer Environment**: N/A
- **Target Environment**: SharePoint Online
- **Framework**: N/A
- **Browser(s)**: Chrome, New Edge
- **Tooling**: Powershell ISE
- **Additional details**:  I am using the following endpoints but this does not seem to work.
    **Get ID:** /_api/SP.WorkflowServices.WorkflowSubscriptionService.Current/EnumerateSubscriptions()?Select=Id
    **Trigger Workflow by ID:** /_api/SP.WorkflowServices.WorkflowInstanceService.Current/StartWorkflow(Subscription=)

**Comment by OS-Lee** [comment]
Hi 

Workaround, use CSOM to start site workflow as rest api not support yet based on my research.

![image](https://user-images.githubusercontent.com/40845109/85815135-39c0ba80-b79a-11ea-8765-20c5e33af301.png)



Add-Type -Path "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll"
Add-Type -Path "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll"
Add-Type -Path "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.WorkflowServices.dll"

# Specify tenant admin and site URL
$SiteUrl = "https://xxx.sharepoint.com/sites/lee"
$Username = "admin@xxx.onmicrosoft.com" 
$Password = "Password" 
$SecurePassword = ConvertTo-SecureString $Password -AsPlainText -Force

$ClientContext = New-Object Microsoft.SharePoint.Client.ClientContext($SiteUrl)
$credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($UserName, $SecurePassword)
$ClientContext.Credentials = $credentials

# Retrieve WorkflowService related objects
$WorkflowServicesManager = New-Object Microsoft.SharePoint.Client.WorkflowServices.WorkflowServicesManager($ClientContext, $ClientContext.Web)
$WorkflowSubscriptionService = $WorkflowServicesManager.GetWorkflowSubscriptionService()
$subscription=$WorkflowSubscriptionService.getSubscription("5fbd6b2c-9f68-452e-b3d2-9a4b25622cb7")
$WorkflowInstanceService = $WorkflowServicesManager.GetWorkflowInstanceService()
$ClientContext.Load($WorkflowServicesManager)
$ClientContext.Load($WorkflowSubscriptionService)
$ClientContext.Load($subscription)
$ClientContext.Load($WorkflowInstanceService)
$ClientContext.ExecuteQuery()

$Dict = New-Object 'System.Collections.Generic.Dictionary[System.String,System.Object]'
$WorkflowInstanceService.startWorkflow($subscription,$Dict);
$ClientContext.ExecuteQuery()

**Lee
Microsoft SharePoint Community Support**
