### ISSUE TITLE
Need more CSOM .net standard sample and docs page missing details

### ISSUE THREAD

**Issue by paololec** [SharePoint/sp-dev-docs#5952]
Not clear section "Configuring an application in Azure AD" example:
-if use Delegated permissions why need "grant admin consent?" 
-application permission are a valid scenario or is not supported? how use it?
-AllSites.Manage -> so I can do everything on all sites indipendent on user+pwd specify into the code?
-secret not need ?

Not clear and incorrect section "Getting an access token from Azure AD and using that in your CSOM for .NET Standard based application":
FormDigestHandlingEnabled = false <- invalid code! need only comment it?
// Get an access token using your preferred approach -> what is valid mode to invoke access token for this scenario?
need sample code to: 
-impersonate a user (by login?) to do sharepoint action on-behalf of user
-execute code with high permission (user/pwd) as background app 

AuthenticationManager sample class:
- System.IdentityModel.Tokens.Jwt.JwtSecurityToken  -> missing indication need import package nuget related to this line of code sample.
- the username/password specify it used for access to site or only to have the token from "app" and then I can do "AllSites.Manage" permission so full controll on all sites?
-missing scenario on-behalf of user (impersonate a user and access shp site only if I have permission and level permission in list for the specific user)
-bug: if the username that I specify using ADFS it not work. I can resolve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .Net Standard instead of CSOM for .Net Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Ddv0623** [comment]
Hi, any update about document for CSOM .net standard.
