### ISSUE TITLE
System.IdentityModel.Tokens.Jwt issue when used in Azure Functions V3

### ISSUE THREAD

**Issue by Greg-Hitchon** [SharePoint/sp-dev-docs#5953]
Hello,

Not sure this is within the scope here but as usage with Azure Functions is noted in the [release post](https://developer.microsoft.com/en-us/microsoft-365/blogs/net-standard-version-of-sharepoint-online-csom-apis/) it might be relevant.

Using the "AuthenticationManager" as posted requires 'System.IdentityModel.Tokens.Jwt' (latest version 6.6.0). If using the latest 'Microsoft.Net.Sdk.Functions' (3.0.7) causes an error as per [this issue](https://github.com/Azure/azure-functions-host/issues/5756). Seems like any of the 5.x Jwt versions work however.

As it seems like a fairly common use case might warrant a note? Probably would save some people time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .Net Standard instead of CSOM for .Net Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unclear... can you elaborate? Even better, submit a PR that adds the elaborated information to the doc?
