### ISSUE TITLE
The page content should be updated with solution for content type name in list settings

### ISSUE THREAD

**Issue by kavitajoshi** [SharePoint/sp-dev-docs#5957]
I just tried the tutorial on this page and issue mentioned in "Custom contenttype is not actually attached to the list when using SPFx asset provisioning #1518" https://github.com/SharePoint/sp-dev-docs/issues/1518  still happens. Seeing 'Item;' for custom content type should never be acceptable. The page should be updated with the solution provided at the end if it is tested and validated solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to submit a PR to the doc that points out issue #1518 for a workaround?
