### ISSUE TITLE
Regarding Microsoft spfx documentation

### ISSUE THREAD

**Issue by wshuo-h** [SharePoint/sp-dev-docs#5962]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

Hi there, 

I try to create a spfx webpart by following Microsoft document : [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries], and a error message comes up. Is there anything missed?? or how should I check this error: Thanks

**### MSFT Document:**

```export default class GalleryWebPart extends BaseClientSideWebPart<IGalleryWebPartProps> {
  // ...
  public render(): void {
    const **element**: React.ReactElement<IGalleryProps> = React.createElement(**Gallery**, {
      listName: this.properties.listName,
      order: this.properties.order,
      numberOfItems: this.properties.numberOfItems,
      style: this.properties.style
    });
    ReactDom.render(element, this.domElement);
  }
}
```
**### My Errors:**

the error was happened at this line:   React.createElement(Gallery
and I attached the image at https://user-images.githubusercontent.com/64821242/86019462-37d84f00-ba59-11ea-8cb9-2cd507371783.png

> No overload matches this call.
>   The last overload gave the following error.
>     Argument of type 'typeof Gallery' is not assignable to parameter of type 'string | ComponentClass<IGalleryProps, any> | FunctionComponent<IGalleryProps>'.
>       Type 'typeof Gallery' is not assignable to type 'ComponentClass<IGalleryProps, any>'.
>         Construct signature return types 'Gallery' and 'Component<IGalleryProps, any, any>' are incompatible.
>           The types of 'state' are incompatible between these types.
>             Type 'void' is not assignable to type 'Readonly<any>'.ts(2769)
> index.d.ts(238, 14): The last overload is declared here.

<img width="500" alt="Gallery" src="https://user-images.githubusercontent.com/64821242/86019462-37d84f00-ba59-11ea-8cb9-2cd507371783.png">

the error was happened at this line:   const **element**: React.ReactElement<IGalleryProps>
and I attached the image at https://user-images.githubusercontent.com/64821242/86019450-33ac3180-ba59-11ea-87cf-f39e2934e437.png

> Type 'DetailedReactHTMLElement<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>' is not assignable to type 'ReactElement<IGalleryProps, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<...>)>'.
>   Types of property 'props' are incompatible.
>     Type 'InputHTMLAttributes<HTMLInputElement>' is missing the following properties from type 'IGalleryProps': listName, order, numberOfItemsts(2322)

<img width="500" alt="element" src="https://user-images.githubusercontent.com/64821242/86019450-33ac3180-ba59-11ea-87cf-f39e2934e437.png">

**Comment by andrewconnell** [comment]
It's hard to understand what's going on or what's wrong without seeing the entire file.

Can you please post that, and [use correct markdown formatting](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#code-blocks-multiple-lines-of-code) to make it easier to read where the code & your question start/stop?

**Comment by wshuo-h** [comment]
> It's hard to understand what's going on or what's wrong without seeing the entire file.
> 
> Can you please post that, and [use correct markdown formatting](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#code-blocks-multiple-lines-of-code) to make it easier to read where the code & your question start/stop?

Hi Andrew, thanks for your kindly reminder. I have adjust the format and it is more clear. Put simply, I do a practice by following up msft document at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries but I still got the error message as I mentioned. To be honest, I cannot figure out what happened. so would you mind give me some suggestions to handle this error. Thanks

**Comment by andrewconnell** [comment]
Thanks, but...

> It's hard to understand what's going on or what's wrong **without seeing the entire file**.

There's not enough context for what you've shared. Can't tell if you have the necessary `imports`, etc.

**Comment by wshuo-h** [comment]
> Thanks, but...
> 
> > It's hard to understand what's going on or what's wrong **without seeing the entire file**.
> 
> There's not enough context for what you've shared. Can't tell if you have the necessary `imports`, etc.

Hi Andrew, this morning I will do it once again and upload whole project and for you to look at. because I am really want to know what happened. I am not good at SPFX.

**Comment by kongmengfei** [comment]
Hi wshuo-h,

I followed the doc and am able to reproduce your issue. It's just a type incompatible issue. 

Test result: 
![image](https://user-images.githubusercontent.com/57654821/85992699-d055db80-ba27-11ea-9502-a99a2580cb94.png)

I put the test demo here: 

- https://github.com/kongmengfei/SharedSPFx/blob/master/react-preconfiguredentries/src/webparts/gallery/GalleryWebPart.ts

Baker Kong
Microsoft SharePoint Community Support

**Comment by wshuo-h** [comment]
> Hi wshuo-h,
> 
> I followed the doc and am able to reproduce your issue. It's just a type incompatible issue.
> 
> Test result:
> ![image](https://user-images.githubusercontent.com/57654821/85992699-d055db80-ba27-11ea-9502-a99a2580cb94.png)
> 
> I put the test demo here:
> 
> * https://github.com/kongmengfei/SharedSPFx/blob/master/react-preconfiguredentries/src/webparts/gallery/GalleryWebPart.ts
> 
> Baker Kong
> Microsoft SharePoint Community Support

Hi Baker,

Thanks for your information. I have sorted it out and figured out what happened.
