### ISSUE TITLE
PnP People Picker not showing disabled/removed user 

### ISSUE THREAD

**Issue by manlamcheng** [SharePoint/sp-dev-docs#5970]
Hello 

I am using the pnp spfx peoplepicker control in my SPFX SharePoint online web part solution. It can fetch users and saved to the database. It also render saved users with emails (not working with user login ID). However, if a user's account is disabled/removed after it's saved in the database, the peoplepicker control will show blank on rendering. I understand that this is because the user's account is not valid anymore. But since this is a historical record, it's normal that users' accounts are disable/removed in a company over a period of time, I would expect that the control should at least showing user's email or name even it's not valid anymore. Just like how SharePoint lists showing users in Person column even the users' accounts are no longer valid.

I am not sure if this is a bug or a feature needed to be implemented. or maybe I have missed some settings to enable it. Any comments is appreciated .

thanks

**Comment by bcameron1231** [comment]
Thank you for the question. This is the general SharePoint Development issue list. If you have specific questions regarding the PnP People Picker, please make that request in that Repo. Thanks!

https://github.com/pnp/sp-dev-fx-controls-react/
