### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#5978]
Need more details on how this should be automated.  For example - recommended approach for automating Azure functions or Azure Automation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb0dffd-d314-6e01-be9a-f72d852227e3
* Version Independent ID: e48220e4-412d-aee0-ce37-86400efb6cc3
* Content: [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#call-the-import-api-from-powershell)
* Content Source: [docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
regards to this topic, I think it's quite subjective as to what that automation approach should be. I think the the document does a great job recommending the architecture for how to implement this, but the automation is really up to each individual organization, whether they choose to use an on-premises Task Scheduler or Azure, don't you think? Providing a recommendation would definitely vary based on organization.

**Comment by danmyhre** [comment]
Perhaps, but covering some of the common / msft recommended ones (like azure functions I would imagine) would be great.  Authentication (i.e. not username and password for unattended app), permissions, setting up CSOM or PnP, etc all should be covered
