### ISSUE TITLE
Public CDN Office 365 return error 406 NotAcceptable

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#5981]
## Category

- [x] Bug

## Describe the bug

Hello, since a few hours ago all requests to https://publiccdn.sharepointonline.com/ are returning error 406 (ErrorCode: 406001, ErrorMessage: "Auth header signature time is out of range", HttpStatus: "NotAcceptable")

We have a library configured as a public CDN, from which we load some style sheets and on the other hand, we have the webparts and extensions hosted in the CDN of the AppCatalog (/sites/AppCatalog/ClientSideAssets/AllItems.aspx)

Please can you confirm if it is a problem with the Office 365 CDN?

**Comment by PooLP** [comment]
Same for me on a tenant without modification.

**Comment by dev-a11y** [comment]
same on our tenant, in our case most of the assets are constantly failing with 406 but some are served correctly

**Comment by ElOmri** [comment]
Hello I have this kind of Issue, 

can someone help please ?
![image](https://user-images.githubusercontent.com/44982094/86262983-789aaa00-bbb8-11ea-96da-42ff986d1b26.png)

I have 403 access denied problem

**Comment by tomekpilat** [comment]
The same for us across 3 dev environments CDN is not returning assets.

**Comment by ujeenator** [comment]
Same on our tenant.

**Comment by ujeenator** [comment]
After I run this script, the problem was solved (It take effect after about 5 minutes):
```
Set-SPOTenant -PublicCdnEnabled $true
New-SPOPublicCdnOrigin -URL https://{my-tenant-name}.sharepoint.com/sites/appcatalog/ClientSideAssets
```

**Comment by tomekpilat** [comment]
@ujeenator I'm getting permission denied for the second command so it's still broken for us.

**Comment by westleyMS** [comment]
The product team is aware of this now, and I am working with them to resolve this.

**Comment by ujeenator** [comment]
@tomekpilat I was running it under global admin role

But for now all custom extensions and web-parts on my tenant are broken, and re-running the script don't help, so either it was coincidence, either CDN has broke even more

**Comment by ujeenator** [comment]
Totally disabled CDN on my tenant:
```
$(Get-SPOTenant).PublicCdnOrigins
Remove-SPOPublicCdnOrigin -Identity <ids from prev command>
Set-SPOTenantCdnEnabled -CdnType Public -Enable $false
Set-SPOTenantCdnEnabled -CdnType Private -Enable $false
```

And re-deployed extensions and web-part from scratch, starting from AppCatalog

All .js files and other assets are loaded now directly from tenant, and it's not good for performance, but at least it works now

**Comment by westleyMS** [comment]
The product team fixed a timestamp issue and now things should be working.
