### ISSUE TITLE
Lookup column provisioning as SharePoint asset

### ISSUE THREAD

**Issue by yukumura** [SharePoint/sp-dev-docs#5982]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I can't create a lookup field through asset provisioning

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**:Sharepoint Online
- **Framework**: Node.js v8/
- **Browser(s)**: Chrome
- **Tooling**: VS Code | SPFx v1.9.1
- **Additional details**: 

**This is my elements.xml:**

`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">

    <ListInstance
            CustomSchema="schemaPurchaseOrder.xml"
            FeatureId="00bfea71-de22-43b2-a848-c05709900100"
            Title="Purchase Orders"
            Description="Purchase Orders List"
            TemplateType="100"
            Url="Lists/PurchaseOrders">
    </ListInstance>

    <ListInstance
            CustomSchema="schema.xml"
            FeatureId="00bfea71-de22-43b2-a848-c05709900100"
            Title="SPFx List"
            Description="SPFx List"
            TemplateType="100"
            Url="Lists/SPFxList">
    </ListInstance>

    <Field 
        ID="{68CF0545-6C14-41A4-89FB-AC1E658F9D6D}"
        Name="TestFieldLK"
        StaticName="TestFieldLK"
        Group="Vendor Fields"
        Type="Lookup"
        DisplayName="Test Field LK"
        List="Lists/PurchaseOrders"
        ShowField="Title" 
    />

    <ContentType ID="0x01006D76FCC446144618BC3E1B3AC4015F8A"
            Name="CTTestSPFX"
            Group="CTTestSPFX"
            Description="Sample content types from web part solution">
        <FieldRefs>
        <FieldRef ID="{68CF0545-6C14-41A4-89FB-AC1E658F9D6D}"/>
        </FieldRefs>
    </ContentType>

</Elements>

**This is my schema.xml:**

```
<List xmlns:ows="Microsoft SharePoint" Title="Basic List" EnableContentTypes="TRUE" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Basic List" BaseType="0" xmlns="http://schemas.microsoft.com/sharepoint/">

  <MetaData>
  <ContentTypes>
   <ContentType ID="0x01006D76FCC446144618BC3E1B3AC4015F8A"
            Name="CTTestSPFX"
            Group="CTTestSPFX"
            Description="Sample content types from web part solution">
        <FieldRefs>
        <FieldRef ID="{68CF0545-6C14-41A4-89FB-AC1E658F9D6D}">
        </FieldRefs>
    </ContentType>
    </ContentTypes>
    <Fields></Fields>
    <Views>
      <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/images/generic.png" Url="AllItems.aspx">
        <XslLink Default="TRUE">main.xsl</XslLink>
        <JSLink>clienttemplates.js</JSLink>
        <RowLimit Paged="TRUE">30</RowLimit>
        <Toolbar Type="Standard" />
        <ViewFields>
          <FieldRef Name="LinkTitle"></FieldRef>
        </ViewFields>
        <Query>
          <OrderBy>
            <FieldRef Name="ID" />
          </OrderBy>
        </Query>
      </View>
    </Views>
    <Forms>
      <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
    </Forms>
  </MetaData>
</List>
```

**This is my schemaPurchaseOrder.xml:**

```
<List xmlns:ows="Microsoft SharePoint" Title="Basic List" EnableContentTypes="TRUE" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Basic List" BaseType="0" xmlns="http://schemas.microsoft.com/sharepoint/">
  <MetaData>
    <ContentTypes>      
    </ContentTypes>
    <Fields></Fields>
    <Views>
      <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/images/generic.png" Url="AllItems.aspx">
        <XslLink Default="TRUE">main.xsl</XslLink>
        <JSLink>clienttemplates.js</JSLink>
        <RowLimit Paged="TRUE">30</RowLimit>
        <Toolbar Type="Standard" />
        <ViewFields>
         <FieldRef Name="Title"></FieldRef>
        </ViewFields>
        <Query>
          <OrderBy>
            <FieldRef Name="ID" />
          </OrderBy>
        </Query>
      </View>
    </Views>
    <Forms>
      <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
    </Forms>
  </MetaData>
</List>

```
This is the final result:

![image](https://user-images.githubusercontent.com/6943411/86267735-768c1780-bbc7-11ea-9b01-75891a5a732b.png)

**Comment by OS-Lee** [comment]
Hi,

Published my test project to github [here](https://github.com/OS-Lee/SPFxAsset), I added a default content type in PurchaseOrders list and all working fine.

**Lee
Microsoft SharePoint Community Support**

**Comment by yukumura** [comment]
> Hi,
> 
> Published my test project to github [here](https://github.com/OS-Lee/SPFxAsset), I added a default content type in PurchaseOrders list and all working fine.
> 
> **Lee Microsoft SharePoint Community Support**

I thank you for the repo and for the code. Now I can correctly install the package, but I noticed that the reference to the list is not present on the lookup column, in fact if I try to insert an element in quick edit it goes into error:

![image](https://user-images.githubusercontent.com/6943411/86327258-45512d00-bc43-11ea-87e3-49ed154efa35.png)

This is my purchase order list:

![image](https://user-images.githubusercontent.com/6943411/86327305-57cb6680-bc43-11ea-8ce8-4cadbc274055.png)


And this is the lookup column:

![image](https://user-images.githubusercontent.com/6943411/86327372-7d587000-bc43-11ea-83c9-225f19b7c647.png)

**Comment by OS-Lee** [comment]
Hi,

Here is test result in based on my test solution.

![image](https://user-images.githubusercontent.com/40845109/86328441-63388500-bc77-11ea-9d37-c28f742e2c27.png)


![image](https://user-images.githubusercontent.com/40845109/86328406-57e55980-bc77-11ea-8037-2a5cf50229d2.png)

**Lee
Microsoft SharePoint Community Support**

**Comment by yukumura** [comment]
> Hi,
> 
> Here is test result in based on my test solution.
> 
> ![image](https://user-images.githubusercontent.com/40845109/86328441-63388500-bc77-11ea-9d37-c28f742e2c27.png)
> 
> ![image](https://user-images.githubusercontent.com/40845109/86328406-57e55980-bc77-11ea-8037-2a5cf50229d2.png)
> 
> **Lee Microsoft SharePoint Community Support**

Okay, you're right. Now works!
I have another question though. Why is there no title within the content types? I would have expected to find Title because the content type inherits from item.

**Comment by OS-Lee** [comment]
Hi,

It does have Title field, hide by dropdown options.

**Lee
Microsoft SharePoint Community Support**
