### ISSUE TITLE
Creating new spfx webpart overlays another webparts

### ISSUE THREAD

**Issue by Sppilka89** [SharePoint/sp-dev-docs#5987]
## Category

- [x] Bug

## Describe the bug

When we add new spfx webpart to the our intranet context, on some PCs the webpart overlays other webparts. The bug started to appear about 14 days ago. Before this period, it worked perfectly.

## Steps to reproduce

1) Create new basic webpart
2) Add webpart in context

![overlaying_webpart](https://user-images.githubusercontent.com/67740054/86353618-d1754b80-bc67-11ea-8faa-9a4543a8d6fc.png)

## Expected behavior

Webpart should not overlay other webpart.

![working_webpart](https://user-images.githubusercontent.com/67740054/86353631-d934f000-bc67-11ea-9aed-1dfbe449f232.JPG)

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: React and Sharepoint Framework
- **Browser(s)**: Chromium Edge v83
- **Tooling**:  VS Code | SPFx v1.10.0 

### Additional context

It seems that the webpart wrongly count heigh of the webpart. On some PC stations is style attribute min-height which is correct, but on other PC stations is attribut static height and webpart start overlaying.

![wrong-render](https://user-images.githubusercontent.com/67740054/86352812-b0602b00-bc66-11ea-954d-abd04771daaa.PNG)

![correct-render](https://user-images.githubusercontent.com/67740054/86352840-bbb35680-bc66-11ea-8c60-76c78e31b0eb.JPG)

**Comment by andrewconnell** [comment]
Can you share the code for your web parts? Also, need more detail on the frameworks... what versions are you using, if you're using Office UI Fabric React & if so, what version.

**Comment by malik-krehic** [comment]
We have a very similar issue in a project. What other feedback is needed?

**Comment by Vertamin** [comment]
Same
![image](https://user-images.githubusercontent.com/69040799/89032308-ad735b80-d334-11ea-8c38-d1a7b07820f1.png)

It looks like there is a parent width with a fixed height that wont let the webpart grow.

![image](https://user-images.githubusercontent.com/69040799/89032423-e9a6bc00-d334-11ea-942c-6f71ab06b3cf.png)

Without that height it still gets cut, but at least the likes/visit counter wont get on top.

![image](https://user-images.githubusercontent.com/69040799/89032504-1ce94b00-d335-11ea-80a0-c52c7be8b5d0.png)

**Comment by Sppilka89** [comment]
After several days, finally solved this problem. Webpart **must not** be marked as **isDomainIsolated = true**. When this attribute is set to **true**, sharepoint cannot inherit their height properly and overflow. 

This attribute can be found under config folder in **package-solution.json**

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "sd-wp-intranet-client-side-solution",
    "id": "xxx",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    }
  },
  "paths": {
    "zippedPackage": "solution/sd-wp-intranet.sppkg"
  }
}
```
