### ISSUE TITLE
Upload function fails in custom web part

### ISSUE THREAD

**Issue by lambayd** [SharePoint/sp-dev-docs#5989]
## Category

Test, Build and deployment succeed but Upload function fails on Production server

## Describe the bug

I have re-installed all required SPFx packages on my Windows system before recreating the SPFx web part
Test, Build and deployment succeed but Upload function fails on Production server

Using SharePoint 2019 and Modern Site
I have followed the steps outlined on the link below to create and deploy an Upload functional web part, however it does not upload to the server and there is no error message displayed. 
Also, I have tried the Stratus Forms App but experienced the same problem

## Steps to reproduce

(a) https://www.c-sharpcorner.com/blogs/file-upload-and-metadata-updation-in-spfx-with-pnpjsreact
(b) http://stratusforms.com/documentation/

## Expected behavior

I am expecting to be able to upload file to a document library

## Environment details (*development & target environment*)

Windows Server 2019
SharePoint 2019 Production  (Latest Windows updates applied)
SharePoint 2019 Development  (Latest Windows updates applied)

- **Your Developer Environment**: Windows 2019 Server
- **Target Environment**:SharePoint Server 2019
- **Framework**: [e.g. .NET Framework v4.6 | .NET Core v3.1 | Node.js v10]
- **Browser(s)**: [ Edge]
- **Tooling**: [ VS Code | SPFx v1.10.0 | Visual Studio 2019]

### Additional context

I have created a Microsoft Support ticket but unfortunately the ticket had been assigned to someone does not seem to have an answer to the issue. The ticket had been open for 2 days.

**Comment by bcameron1231** [comment]
Thank you for the comment. Can you provide any network traces from Fiddler and/or do you see any errors in your Network Log in Developers? As this is all client side, you should be able to see the request in Dev Tools. Thanks,

**Comment by lambayd** [comment]
I thank for the response.

Please find attached 
Logs from Fiddler:
[Log.zip](https://github.com/SharePoint/sp-dev-docs/files/4865194/Log.zip)

Log from Dev Tool:
[Dev.txt](https://github.com/SharePoint/sp-dev-docs/files/4865246/Dev.txt)


Below is the error message from Edge>>Dev Tools >> Network
Name: add(overwrite=true,url='Event_Stream_Failure.txt'

General
Request URL: https://service.kvikna.com/SitePages/_api/web/getFolderByServerRelativeUrl('/SiteAssets')/files/add(overwrite=true,url='Event_Stream_Failure.txt')
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:8888
Referrer Policy: no-referrer-when-downgrade

**Comment by andrewconnell** [comment]
It appears you're trying to upload the **\*.sppkg** file to the Site Assets library... is that correct? SharePoint packages should ONLY be uploaded to the app catalog: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page

**Comment by lambayd** [comment]
@andrewconnell  This .sppkg is in the app catalog (see screenshot) and the only code added  is within the .tsx file (see attachment). There is an upload tab to select a local file and then click upload which should transfer the file to the document library (in this case SiteAssets). Note: I have tried other document library.
https://www.c-sharpcorner.com/blogs/file-upload-and-metadata-updation-in-spfx-with-pnpjsreact
![image](https://user-images.githubusercontent.com/7116472/86404091-7b6fca80-bc9e-11ea-8f2b-7449bd04ecbe.png)
[code.txt](https://github.com/SharePoint/sp-dev-docs/files/4866486/code.txt)

**Comment by andrewconnell** [comment]
Please include code in the issue... please don't upload attachments to the issue. Its easier to view & reference not to mention people won't download it for fear of viruses.

From the screenshot above, it shows it uploaded and there are no errors... so I'm not clear what the problem is that you're describing.

**Comment by lambayd** [comment]
@andrewconnell Please see .tsx content (This is the only code edited)
Problem: The upload function does not work, no file is transferred to the Document Library

import * as React from 'react';
import styles from './SpfxReactPnpFileUpload.module.scss';
import { ISpfxReactPnpFileUploadProps } from './ISpfxReactPnpFileUploadProps';
import { escape } from '@microsoft/sp-lodash-subset';
import "@pnp/polyfill-ie11";  
import {sp} from '@pnp/sp';

export default class SpfxReactPnpFileUpload extends React.Component < ISpfxReactPnpFileUploadProps, {} > {
  constructor(props) {  
    super(props);  
    this.filesave = this.filesave.bind(this);  
  } 
  public render(): React.ReactElement<ISpfxReactPnpFileUploadProps> {
    return(
<div>  
        <div>  
        <input type="file" name="myFile" id="newfile"></input></div>  
        <div>  
        <button onClick={this.filesave}>  
        UploadFile  
      </button></div>    
</div>
    );
  }
  private filesave(){  
    let myfile = (document.querySelector("#newfile") as HTMLInputElement).files[0];  
    if (myfile.size <= 10485760) {  
      sp.web.getFolderByServerRelativeUrl("/SiteAssets").files.add(myfile.name, myfile, true).then(f => {  
        console.log("File Uploaded");  
        f.file.getItem().then(item => {  
            item.update({  
                Title: "Metadata Updated"  
            }).then((myupdate) => {  
              console.log(myupdate);  
              console.log("Metadata Updated");  
            });  
        });  
    });    
    }  
    else{  
      sp.web.getFolderByServerRelativeUrl("/SiteAssets")  
      .files.addChunked(myfile.name, myfile)  
      .then(({ file }) => file.getItem()).then((item:any) => {  
        console.log("File Uploaded");  
          return item.update({  
              Title: 'Metadata Updated'  
          }).then((myupdate) => {  
            console.log(myupdate);  
            console.log("Metadata Updated");  
          });  
      }).catch(console.log);  
}
}
}

**Comment by lambayd** [comment]
@andrewconnell 
Using Powershell I encountered this error:
Add-Type -Path 'C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll'
Add-Type -Path 'C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll'

# SharePoint URL 
#
$ctx = New-Object Microsoft.SharePoint.Client.ClientContext("https://tem.powerk.com")
$web = $ctx.Web

# Authenticating
#
$cred = Get-Credential
$ctx.Credentials = $cred

# Get Document Library
#
$DocLib = $web.Lists.GetByTitle("Upload")

# Load the object
#
$ctx.Load($web)
$ctx.Load($DocLib)
$ctx.ExecuteQuery()

# Get all files
#
$Files = Get-ChildItem -Path "C:\Users\Downloads\Tester" | ? {$_.psIsContainer -eq $False}

# Upload all files in the root folder of the document library
#
Foreach ($File in $Files) {

    Write-Host "Uploading file.." -ForegroundColor Green

    $FileFullName = $File.FullName
    $FileStream = New-Object IO.FileStream($FileFullName, [System.IO.FileMode]::Open)
    $FileCreationInfo = New-Object Microsoft.SharePoint.Client.FileCreationInformation
    $FileCreationInfo.Overwrite = $true
    $FileCreationInfo.ContentStream = $FileStream
    $FileCreationInfo.URL = $File.Name
    $FileUpload = $DocLib.RootFolder.Files.Add($FileCreationInfo)
    $ctx.Load($FileUpload)
    $ctx.ExecuteQuery()
}
---------------------------------------------------------------
Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."
At C:\Users\sam\Desktop\ps_upload_files_sharepoint.ps1:22 char:1
+ $ctx.ExecuteQuery()
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Uploading file..
New-Object : Exception calling ".ctor" with "2" argument(s): "The process cannot access the file 'C:\Users\Downloads\Tester\New Text Document.txt' because it is being used by another process."
At C:\Users\sam\Desktop\ps_upload_files_sharepoint.ps1:35 char:19
+ ... ileStream = New-Object IO.FileStream($FileFullName, [System.IO.FileMo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
Exception calling "ExecuteQuery" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."
At C:\Users\sam\Desktop\ps_upload_files_sharepoint.ps1:42 char:5
+     $ctx.ExecuteQuery()
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by lemonpowah** [comment]
@lambayd You should in general use [PnP PowerShell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps) as it makes your life easier.

There are two issues I can see from your PowerShell snippet:
1. There's a 401 code. If I understand correctly you pass the first ExecuteQuery when loading the lib so your credentials are correct, however you get an error when uploading the file. Please have a look if you have permissions to upload documents to that library.
2. 'New Text Document.txt' appears to be opened in some editor so the code is not able to open the file stream.

Regarding your typescript code, I suspect it is the same problem as the PowerShell script. Check if you have the rights to upload files to that library. Also, did you initialize the sp namespace properly? You are supposed to provide a context upon initialization:
Snippet from [PnPJs](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-setup):
```ts
protected onInit(): Promise<void> {

  return super.onInit().then(_ => {

    // other init code may be present

    sp.setup({
      spfxContext: this.context
    });
  });
}
```
