### ISSUE TITLE
Suggestion to upgrade using pnp cli tools don't support 1.11

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#5996]
In the "tip" box that has the text `If your application is built using an older version of the SharePoint Framework, you can easily upgrade it to SharePoint Framework v1.11 or newer using Office 365 CLI.`, the linked page for the pnp tool doesn't yet support 1.11.

Text on the linked page reads:
```
The spfx project upgrade command helps you upgrade your SharePoint Framework project to the specified version. If no version is specified, the command will upgrade to the latest version of the SharePoint Framework it supports (v1.10.0).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06d649b5-f4bc-ffd9-191b-ab7e758d9a54
* Version Independent ID: c02df482-fcbf-18be-cc15-485ec1d3379b
* Content: [Prepare your SharePoint Framework application for publishing to the marketplace](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist)
* Content Source: [docs/spfx/publish-to-marketplace-checklist.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/publish-to-marketplace-checklist.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks... this will be true when SPFx v1.11 ships & the corresponding O365 CLI update ships for the v1.11 release. 

@waldekmastykarz FYI
