### ISSUE TITLE
Documentation error in Tutorial 3 step 5

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-docs#60]
Hi
I think the <webpart-guid>.manifest.json file is in hello-world-webpart\dist folder rather than  src\webparts\helloWorld\dist folder (or have I done something wrong ?) - see attached screenshot.
![azurewebpart-distpng](https://cloud.githubusercontent.com/assets/8484048/17885487/58b23b62-6915-11e6-9775-350837d4afaf.PNG)

Regards
Nigel

**Comment by VesaJuvonen** [comment]
thx Nigel, updated as well to tutoriasl.
