### ISSUE TITLE
Porting solution to on-premise

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#600]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have built a few webparts for some clients that are using O365, however now I got requests to port the react based webparts to on-premise 2013/2016. Is there any solution for me to port this spfx webparts to on premise? I understand that some feature like manifest(properties) and context may not be available, but this can be replaced with something else on-prem?

**Comment by waldekmastykarz** [comment]
Have you seen this sample: https://github.com/SharePoint/sp-dev-samples/tree/master/Samples/react-generic-app? At this moment it's the only thing available on-premises that you could use, and which reuses some of the concepts of the SPFx. Using this approach you will lose the property pane, so if you require it, you would have to build your own implementation of it.

**Comment by jonathanhotono** [comment]
Thanks @waldekmastykarz , is this project monitored and supported by MS too? Or we(community) just have to maintain it on our own?

**Comment by waldekmastykarz** [comment]
It's a community-owned sample that doesn't have a Microsoft SLA if that's what you're asking.

**Comment by VesaJuvonen** [comment]
I think we have covered the question in the answers. Thx @waldekmastykarz for the replies and @jonathanhotono for the question. Like covered here, SPFx is not yet supported in on-premises. Client-side web parts will be landing to SP2016 with Feature Pack 2 later this year. Provided sample shows how to build customizations using modern web stack also in on-premises. Technique is absolutely supported approach, but the sample itself is provided as a generic sample and maintained by the community.

**Comment by jonathanhotono** [comment]
Thanks Waldek!
