### ISSUE TITLE
PnP Modern Search - Search webpart doesn't work

### ISSUE THREAD

**Issue by mjnda** [SharePoint/sp-dev-docs#6000]
## Category

- [x] Bug

## Describe the bug

we use this solution to custom search results pages in SharePoint Online. 
for a week, we have had a problem displaying the pages with the new version 3.14.1.0.

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. Go to 'Site collection '
1. Click on 'webpart'

![image](https://user-images.githubusercontent.com/67896456/86576888-afd2d780-bf79-11ea-80f1-115a3357c4d7.png)

## Expected behavior
we have just the picture , not the description 

![image](https://user-images.githubusercontent.com/67896456/86577013-e0b30c80-bf79-11ea-8a56-aa074e7e3059.png)

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Your Developer Environment**:  Windows 10 
- **Target Environment**: SharePoint Online]
- **Framework**:  .NET Framework v3.x 
- **Browser(s)**:  Chrome v79  | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**:  VS Code 

*Thanks for your contribution! Sharing is caring.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**
>
> *Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Thank you for the comment. Can you please please post this question over in the modern search web part repository? https://github.com/microsoft-search/pnp-modern-search/

Thanks!
