### ISSUE TITLE
Follow up to this issue #729 SPFX Web parts not loading on load

### ISSUE THREAD

**Issue by stchiew** [SharePoint/sp-dev-docs#6004]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Actually this is a related to this issue [SPFX Web parts not loading on load #729](https://github.com/SharePoint/sp-dev-docs/issues/729) that is already closed - is there are any follow up issues opened for this? I am still experiencing this in our tenant (Standard Release). In the comments of the above issue it is mentioned that it is caused by some optimization enhancements, and it has since been fixed, but I am still facing issues with it.
However, when testing on a tenant with Targeted Release, the issue is not there anymore.

My question is, is there already a fix and is being rolled out eventually to Standard Release tenants? Also, is there a quick fix for it in the meantime?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**:  SPFx
- **Browser(s)**: All
- **Tooling**: SPFx v1.10.0 
- **Additional details**:  
Use case scenario:
I have many custom web parts that creates anchors all over a long page. I then have another custom web part at the top of the page that displays all these anchor labels as a navigation bar. These labels do not appear until user scrolls down the page. It appears that the web parts do not load until it appears in the page viewport.

> *Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
When you say you're "still experiencing" the issue in your SR tenant... how long has that been going on? is this a recent thing or a long-running thing? If long-running, how long?

**Comment by stchiew** [comment]
I started developing a custom web part 2 months ago and started experiencing this since then till now.

I am deep diving into this and came up with some findings. I will close this issue and open a new issue/question with my detailed findings.
