### ISSUE TITLE
After 'Sorry, something went wrong with adding the app' AppMonitoringDetails does not give any info

### ISSUE THREAD

**Issue by adrichema** [SharePoint/sp-dev-docs#6005]
## Category

- [x] Bug

### Expected or Desired Behavior
While adding a SPFX package to a site, if i'm getting an error during installation process, if i'm going to the AppMonitoringDetails, and then click on error '1' i should be able to see the error details instead of blankpage.

### Observed Behavior
When I click on the '1' to show the errors, it shows a blank page

### Steps to Reproduce
This happens if we're deploying an SPFX Application that includes a SharePoint feature to provision list or CT, with something wrong in it. This issue seems very similar to #4049 , #4029 and #1089.

Thanks for your help

**Comment by andrewconnell** [comment]
That's a known issue with the AppMonitoringDetails. Unfortunately, there's not enough information to help... you've provided zero context and removed the context section for a new issue. Please feel free to resubmit with additional detail.
