### ISSUE TITLE
SharePoint Online SPFX Custom Menu

### ISSUE THREAD

**Issue by Bilal-Hamad** [SharePoint/sp-dev-docs#6006]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have created an SPFX extension which I deployed to SharePoint Online.
This extension appends a custom menu to the top bar on load of the site, and hide the OOB menu using CSS.
The thing is, the extension is very slow, so wen you open the site, it takes time for the orginal menu to disappear and for the custom menu to get appended.
And sometimes, if the internet connect is very slow, the SPFX extension wont even load.
The question is, is this considered as the best solution to achieve my target which is create a custom menu with custom html design in SharePoint online? or is there any other way which is considered as a best practice?
And if this is the only way, is it possible to improve its performance?
Below is the code i am using to append the custom menu through SPFX extension which is called **onInit():**

`let topPlaceholder: PlaceholderContent = this.context.placeholderProvider.tryCreateContent(PlaceholderName.Top); 
    if (topPlaceholder) { 
        topPlaceholder.domElement.innerHTML = 'HTML OF THE MENU';
    }`

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | Firefox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
>
>
> *Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Little unclear... are you saying you're hiding the SPO suite bar navigation from the app customizer? That's 100% not supported as it's considered DOM manipulation.

If you're trying to implement a custom menu with an app customizer, suggest you check out the menu samples in the https://github.com/pnp/sp-dev-fx-extensions project.

**Comment by Bilal-Hamad** [comment]
Hello andrew, thank you for the reply.
Yes, that is exactly what iam doing in the extension, i first hide the OOB bar, then I append my own custom menu.
The thing is, this is what my client is requesting as he is demanding to remove the OOB navigation and instead put a custom menu and logo in the middle of the menu along with css effects and animations on hover of a menu item, which can not be done using SharePoint Out Of the Box features and requires custom html, css, jquery, etc...

**Comment by andrewconnell** [comment]
@Bilal-Hamad said
> i first hide the OOB bar, then I append my own custom menu

To be clear, that is 100% not supported & not recommended by Microsoft. I strongly advise you to educate your customer why. The DOM is not a contract and can change at any time without warning with an update from MSFT, breaking anything you implement. The SharePoint Framework was designed to provide a contract for things developers & customizers can customize. If you go outside of that contract, by using DOM manipulation, you're breaking that contract.

IMHO, just because a customer wants it, doesn't mean that's what the product does.

**Comment by Bilal-Hamad** [comment]
Thank you so much Andrew for your advice, will make sure to mention these points.
So in your opinion, there is not a way that we can achieve our targeted layout in an approach that can be considered as a best practice?

**Comment by andrewconnell** [comment]
It's not just my opinion. What you are asking to do (hide/customize the suite bar) is 100% unsupported by Microsoft. It's not a best practice by anyone reputable.
