### ISSUE TITLE
CustomRowActions work as a charm on the listview. But as soon as you embed the view on a modern page, custom row actions no longer seem to work.

### ISSUE THREAD

**Issue by guywel** [SharePoint/sp-dev-docs#6008]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by guywel** [comment]
It is regarding the customRowAction when using column formatting. 
Buttons with a customRowAction will work as long as you stay in the list view. 
When adding the view as a webpart to a modern page, the customRowActions no longer work.

**Comment by shagra-ms** [comment]
@guywel thanks for sharing information about the scenario. I am unable to repro this issues locally. Would you mind sharing a simplified JSON that can help me repro this?
