### ISSUE TITLE
Messaging Extension not rendering SPFX webpart

### ISSUE THREAD

**Issue by NicolasMCAG** [SharePoint/sp-dev-docs#6009]
Hi!

After following the steps to render a SPFX webpart in a messaging extension I get a blank task module.

![image](https://user-images.githubusercontent.com/58806598/86902731-a333b800-c10e-11ea-9955-438a83a3ad49.png)

![image](https://user-images.githubusercontent.com/58806598/86902996-045b8b80-c10f-11ea-863b-6f3277aa9f7e.png)

Steps I performed:

1. Generated a SPFX 1.10 solution, just the basic Hello World from the generator.
2. In the package: **includeClientSideAssets** in true and **skipFeatureDeployment** in true.
3. In the webpart manifest: **supportedHosts** => SharePointWebpart, TeamsTab, TeamsPersonalApp
4. Build/bundle/package solution with ship flag.
5. Uploaded to App Catalog, marked to deploy to all sites, and sync to Teams.
6. Generated an app manifest with the following compose extension (trimmed for brevity) and sideloaded to Teams:

> edited by @andrewconnell ... in the future, please use the markdown code fencing pattern... impossible to read JSON in one line

```
"composeExtensions": [
    {
      "botId": "9fa9af77-11d5-4cfd-986d-658c41fcb195",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "TestID",
          "title": "Test Title",
          "description": "Test Description",
          "initialRun": false,
          "type": "action",
          "context": [ "message", "compose" ],
          "fetchTask": false,
          "taskInfo": {
            "title": "Fill in the fields",
            "width": "large",
            "height": "large",
            "url": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamstaskhostedapp.aspx%3Fteams%26personal%26componentId=68a6425b-df85-4bea-8bf0-9953c1f09f92%26forceLocale={locale}"
          }
        }
      ]
    }
  ],
"validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ]
```

Tests I performed:

- Added the webpart to a page in SharePoint: worked.
- Added the webpart to a Teams tab: worked.
- Invoked the compose extension from compose box: didn't worked -- issue described at the top.
- Invoked the compose extension from the message actions: didn't worked -- issue described at the top.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 856e1bda-6f6a-745a-520b-aacfb5234eed
* Version Independent ID: 49f40dc4-2c4f-bbec-d02a-af2d414dcb4d
* Content: [Expose SharePoint Framework web parts in Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-expose-webparts-teams)
* Content Source: [docs/spfx/build-for-teams-expose-webparts-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/build-for-teams-expose-webparts-teams.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
MS Teams messaging extensions aren't supported with SPFx at this time... I think they may be coming in SPFx v1.11, but they aren't supported in v1.10 at this time.

**Comment by NicolasMCAG** [comment]
Hi @andrewconnell,

This link says they do.... https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-expose-webparts-teams

That's also the same link I created the issue for, can you clarify this, please?

Thank you.

**Comment by andrewconnell** [comment]
The link also says it's supported in SPFx v1.11 apps, which has yet to be released.

**Comment by NicolasMCAG** [comment]
Perfect!!! Thank you very much, @andrewconnell
