### ISSUE TITLE
SPFX webpart property data not appearing in search result

### ISSUE THREAD

**Issue by Divyeshkotadia** [SharePoint/sp-dev-docs#601]
I have developed SPFX webpart that has input field property to which users adds data that appears on page. 

Now I want this page to appear on search result when user search data he entered on SPFX webpart property. I have tried searching over internet but seems no one has done it, please guide.

**Comment by nickpape-msft** [comment]
Related #603

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
