### ISSUE TITLE
No Gulp file Found

### ISSUE THREAD

**Issue by Nagarajan1605** [SharePoint/sp-dev-docs#6010]
Hi Team,

I have downloaded a clone file from git hub and open the same in visual studio code. I have installed the required file types. While trying to run got the error as No gulpfile found.

Herewith i have attached error screenshot
<img width="610" alt="gulpissue" src="https://user-images.githubusercontent.com/21313599/86913872-f02e8300-c13c-11ea-83c1-c1b1ef21be58.png">

**Comment by JarbasHorst** [comment]
Hello @Nagarajan1605 

is your question about a [sample web part](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples)? If yes, please use the issue list in this repo for questions on that repo!

This issue list is for general SP development questions/issues.

Regards,
Jarbas
