### ISSUE TITLE
The method of creating a self-signed cert does not work with the described connect-pnponline method. When attempting to connect, I'm getting: Exception has been thrown by the target of an invocation. at SharePointPnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord()

### ISSUE THREAD

**Issue by jmuehlenbein** [SharePoint/sp-dev-docs#6012]
When attempting to connect, I'm getting: Exception has been thrown by the target of an invocation. at SharePointPnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() 

Resolved by using New-PnpAzureCertificate to generate cert as per pnp/PnP-PowerShell#2181.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by jmuehlenbein** [comment]
Resolved by using New-PnpAzureCertificate to generate cert as per https://github.com/pnp/PnP-PowerShell/issues/2181.

**Comment by andrewconnell** [comment]
Unclear to your comment... are you saying you got an error & that's what you did to solve it?

It would help if you provided more detail in the BODY of your submission. The title is useful for a summary of your issue, not to post the entire error.

**Comment by jmuehlenbein** [comment]
Hey AC, sorry for the unclear message. It was intended to clarify the issue I had what worked for me to resolve it.
