### ISSUE TITLE
How do I add the Group.Read.All permission?

### ISSUE THREAD

**Issue by jmuehlenbein** [SharePoint/sp-dev-docs#6013]
I don't see this as an option anywhere....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @jmuehlenbein 

the documentation provides this [link about Granting access via Azure AD App-Only (recommended)](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread) which shows how to define applications in Azure AD and how to grant permissions to SharePoint. However, this application can be granted permissions to Graph as well.

In your PnP Modernization Scanner Azure AD app, click on "API permissions" in the left menu bar, and click on the "Add a permission" button. A new blade will appear. Here you choose the permissions that you will grant to this application. Choose i.e.:
- Microsoft Graph
  - Application permissions
    - Group
      - Group.Read.All 

Now, click on the blue "Add permissions" button at the bottom to add the permissions to your application, then on "Grant admin consent for Contoso".

I hope it helps to clarify your question.

Regards,
Jarbas

**Comment by Jerry0527** [comment]
Group.Read.All is set in Azure AD App, you can firstly register Azure AD App:

![Image 3](https://user-images.githubusercontent.com/28797671/87017843-161e5b00-c203-11ea-9952-8e48f3c2bde2.png)

Then set Application Permissions:

![Image 6](https://user-images.githubusercontent.com/28797671/87017900-26ced100-c203-11ea-803d-fd4acd76e7d8.png)

Reference:

[Manage app registration and API permission for Microsoft Graph notifications](https://docs.microsoft.com/en-us/graph/notifications-integration-app-registration)
