### ISSUE TITLE
How to add menu items for a single-page web part?

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6014]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is it possible to have menu items added for a single-page web part? 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?tabs=pnpposh

I mean, add menu to the area usually used for menu commands (please see the screenshot):
![image](https://user-images.githubusercontent.com/528366/86980825-2e4f9500-c185-11ea-9050-cf4e67bb9d97.png)

Is it possible to put some items in the highlighted area, and if yes, how?
If the page was a list, that would be possible with command set extension. But for a single page, the commands are just do not seem to be coming.

Would it be possible/okay to "attach" a component like fabric CommandBar to this area?
Is there a standard way to do that (like, placeholders or something)

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [e.g. Chrome v81]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | FluentUI]

**Comment by andrewconnell** [comment]
No, there's no API that enables this in SPFx. 

You have complete control of what you put within the web part, so you can implement your own top/side menu, but it's not going to get added to the yellow bar you have in your screenshot.

**Comment by nbelyh** [comment]
Thank you,  @andrewconnell. It would be nice to have such a possibility though - this area is basically wasted now..

**Comment by andrewconnell** [comment]
Understood... that would fall under the category of a feature request, which should be posted to https://aka.ms/spdev-uservoice

**Comment by nbelyh** [comment]
Okay, will post there then. Thanks :)
