### ISSUE TITLE
Publish Teams Webpart to AppSource

### ISSUE THREAD

**Issue by nikskhubani** [SharePoint/sp-dev-docs#6015]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> I have a question about App Source for Teams / SharePoint. We built a web part for Teams using SPFx framework. And to use it, all customer needs to do is upload our SPPKG file in Tenant App Catalog and add new teams app (zip containing manifest and logos) in their team's environment. We want to upload this App to App Source. I have the following questions:

1. Do we have to upload this app to SharePoint App Source or we can upload app to Teams App Source? I can smell from [this article ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq#can-i-use-a-custom-microsoft-teams-manifest)that I need to create SPFx App and then when customer will add it to their App Catalog, they can sync to teams.
 
2. Can I not create an app in Teams App Source? If my app is for Teams only, it would make more sense for me to upload it to Teams App Source so customers can see it directly in Teams. At present, having them to add from SharePoint App Source business/sales-wise is not a better use-case. 

3. Is there any official document which I missed to find on help for publishing Teams app created using SPFx to App source?

**Comment by andrewconnell** [comment]
These docs were published ahead of the SPFx v1.11 release. This capability will be supported by SPFx v1.11, which will be released in the future.

**Comment by nikskhubani** [comment]
@andrewconnell Thank you for your reply!

**Question** 

Are you saying in future, We can publish apps built for Microsoft Team using SPFx framework in App Source of Teams or App Source of SharePoint?

**Comment by andrewconnell** [comment]
That I'm not sure of.
