### ISSUE TITLE
Cant have html elements in react component render method

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/sp-dev-docs#602]
#### Category

- [ X] Bug

#### Expected or Desired Behavior
Abiliy to create react dropdown react component like in the guild
c

#### Observed Behavior
The project just say  Cannot find name 'div'. or any html element in a react component render method

#### Steps to Reproduce
https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/build-custom-property-pane-controls

**Comment by ravenboilinux** [comment]
Interesting part is if you put the react component into the file that contain the component for the webpart that was generated from yoman, typescript does not throw error on render method.

**Comment by jonathanhotono** [comment]
are you developing it in ts file or tsx file?

**Comment by ravenboilinux** [comment]
everything is in .ts files just like the guild talks about

**Comment by jonathanhotono** [comment]
Firstly if you need to render react element using the xml syntax you then must use tsx file. You must also wrap the whole elements in a container <div> if you need to render multiple elements within render.

**Comment by ravenboilinux** [comment]
So why do the other files dont need tsx?

**Comment by jonathanhotono** [comment]
tsx is basically an extension of jsx which is widely used in reactjs. If you're new to react, reading this article may help:
https://facebook.github.io/react/docs/jsx-in-depth.html
https://facebook.github.io/react/docs/hello-world.html

And maybe if necessary do a bit of tutorial (this is in ES6, not TypeScript but logically works):
https://egghead.io/courses/react-fundamentals

**Comment by nickpape-msft** [comment]
Closing this issue as @jonathanhotono redirected to some good resources for TSX. Feel free to re-open if you have further issues.
