### ISSUE TITLE
GCC/GCCH support

### ISSUE THREAD

**Issue by junterpfe** [SharePoint/sp-dev-docs#6020]
in testing we seem unable to connect to GCCH, is the application supported in GCC/GCCH?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#step-3-alternative-option-launch-a-scan-using-command-line)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by junterpfe** [comment]
looks to be hardcoded to sharepoint.com when GCCH is sharepoint.us

**Comment by andrewconnell** [comment]
Suggest posting this question to the project's GH repo's issue list: https://github.com/SharePoint/sp-dev-modernization/

**Comment by junterpfe** [comment]
done https://github.com/pnp/sp-dev-modernization/issues/494
