### ISSUE TITLE
Error trying to debug SPFx extension

### ISSUE THREAD

**Issue by ani2020** [SharePoint/sp-dev-docs#6021]
## Category

- [x] Bug

## Describe the bug
SPFx version: 1.10
Error caused when trying to debug any extension or Web-Part 
## Steps to reproduce

-- Created new Microsoft SharePoint SPFx extension using "yo @microsoft/generator".
-- SPFx extension type is "Application Customizer".
-- Side load the extension to App catalog
-- Ran "gulp serve" locally to try and debug extension with Url to debug 
launching with Url of following form: 
1. https://<domainnameremoved>/SitePages/Settings.aspx?debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&customActions=%7B%22cc6a4c56-d66f-4274-9bf3-824c4a0b1012%22%3A%7B%22location%22%3A%22ClientSideExtension.ApplicationCustomizer%22%2C%22properties%22%3A%7B%22testMessage%22%3A%22Test+message%22%7D%7D%7D
2. https://<domainnameremoved>/SitePages/Settings.aspx?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"cc6a4c56-d66f-4274-9bf3-824c4a0b1012":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"testMessage":"Test+message"}}}

-- Sharepoint site opened in browser with below error while loading "Debug Menifest file".

Error details: TypeError: sp_loader_._SPLoaderFlights._useNewBootSequence is not a function

Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: 37e25f9f-20d8-0000-ccb2-a9e64282c000
Date and Time: 6/25/2020 7:54:23 AM

## Expected behavior

Should load normally from the local source and allow stepping /debugging code

## Environment details (*development & target environment*)

- **Developer Environment**:  [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v79 | Edge | Chromium Edge v79]
- **Tooling**: [VS Code | SPFx v1.10.0 ]
- **Additional details**: *SPFx version 1.8.2  we were able to debug same code*

### Additional context

None

*Thanks for your contribution! Sharing is caring.*

**Comment by ani2020** [comment]
Do we have any update on this issue?

**Comment by benkenawell** [comment]
Any more information on this?  I'm trying to follow [this guide](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages) for debugging my Application Customizer on a modern page and I'm seeing the same issue as @ani2020 with a brand new sharepoint solution.

### Environment details (development & target environment)

- Developer Environment: [Windows 10]
- Target Environment: [SharePoint Online]
- Framework: [Node.js v10.16.3]
- Browser(s): [Chrome v86]
- Tooling: [VS Code | SPFx v1.11.0 | SPFx v1.10.0 | SPFx v1.9.1 ]

**Comment by patmill** [comment]
Sorry - this looks to be user error.  In that guide, it shows how to set the URL.  You aren't pointing to a page.
"pageUrl": "https://contoso.sharepoint.com/sites/mySite/SitePages/myPage.aspx",
