### ISSUE TITLE
Permissions for Sharepoint modernization scanner

### ISSUE THREAD

**Issue by cblomart** [SharePoint/sp-dev-docs#6022]
Can you limit the rights the application has ?

I don't get why a scanner app need "sites.fullcontrol.all". 
In the same manner, is the "user.read" delegated permission really useful as it looks like the service principal is used.

It just looks like bazooka permissions to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
The issue you opened in the project's repo is the best way to handle this so I'll go ahead and close this comment.
