### ISSUE TITLE
Can't convert object to primitive value in IE11

### ISSUE THREAD

**Issue by rquanx** [SharePoint/sp-dev-docs#6024]
## Category

- [x] Bug

## Describe the bug

My project needs to be compatible with IE11 and Some packages I use depend on ES6 or ES7 , so I need to use polyfill.
Once I use `@babel/polyfill`  or `@pnp/polyfill-ie11` in IE11 I get an error：`Can't convert object to primitive value`

## Steps to reproduce

1. `import "@pnp/polyfill-ie11"`  or `import "@babel/polyfill"` 
2. Run `gulp serve`
3. Open  SPO workbench Page in IE11 and add webpart into column
4. See error `Can't convert object to primitive value`

## Expected behavior

After adding polyfill, webpart can run normally

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**:  IE v11 
- **Tooling**: VS Code 、 SPFx v1.10.0 

### Additional context

```Error message```
![image](https://user-images.githubusercontent.com/36622981/87180285-d6df2f80-c312-11ea-892d-22295c82d448.png)

```Error breakpoint```
![image](https://user-images.githubusercontent.com/36622981/87180606-700e4600-c313-11ea-9aac-67c351021b84.png)

```Object Information```
![image](https://user-images.githubusercontent.com/36622981/87180652-87e5ca00-c313-11ea-8529-ee4848b0641c.png)

![image](https://user-images.githubusercontent.com/36622981/87180670-8ddbab00-c313-11ea-822a-6957412be511.png)

![image](https://user-images.githubusercontent.com/36622981/87180710-a055e480-c313-11ea-8e70-5ecc1bb8f8c2.png)

```Normal operation after removing polyfill and ES6/ES7 dependent components ```
![image](https://user-images.githubusercontent.com/36622981/87181174-6e914d80-c314-11ea-9960-489f71606642.png)

**Comment by rquanx** [comment]
Can someone answer this question?

**Comment by rmillener** [comment]
@rquanx - @pnp/polyfill-ie11 should work fine, we use it successfully in IE11. 

Using @babel/polyfill in it entirety wont work due to the issues discussed in https://github.com/SharePoint/sp-dev-docs/issues/888 

The workbench is also fairly flakey in IE11 to begin with. To avoid this we use a debug build deployed to a real SharePoint page rather than the workbench.

**Comment by rquanx** [comment]
@rmillener  Thanks.

**Comment by aslanovsergey** [comment]
My users periodically have the same error 'Can't convert object to primitive value' in IE, sometimes it goes away by itself but comes back later. I use @pnp/polyfill-ie11 in 1.9.1 spfx webpart

**Comment by rquanx** [comment]
I solved the problem by manually import each dependency package

**Comment by aslanovsergey** [comment]
do you mean each polyfill from core-js? or from @pnp/polyfill-ie11? Can you provide an example?

**Comment by rquanx** [comment]
> do you mean each polyfill from core-js? or from @pnp/polyfill-ie11? Could you provide an example?

yeah,
```
import "core-js/modules/es6.array.from";
import "core-js/modules/es6.array.fill";
import "core-js/modules/es6.array.iterator";
import "core-js/es6/promise";
import "core-js/es6/reflect";
import "es6-map/implement";
// import "core-js/es6/symbol";  // in my case ,symbol is unnecessarily 
import "whatwg-fetch";
```

**Comment by shahid-mehmood** [comment]
Is there any solution you could find? @aslanovsergey I have same problem as yours. Sometimes It works and mostly it does not.

**Comment by AtoZShaileshPatel** [comment]
### **For IE, follow below steps**

**Install @pnp/polyfill-ie11**
- npm install @pnp/polyfill-ie11 --save

**Import @pnp/polyfill-ie11**
- import "@pnp/polyfill-ie11";

**Add/Updated onInit in web part TS file**

protected onInit(): Promise<void> {
    debugger;
    sp.setup({
      ie11: true,
      spfxContext: this.context
    });
    return super.onInit();
  }

**Note:** It won't work in workbench, you must generate package and check it on the SharePoint page

**Comment by patmill** [comment]
I'm going to close this one.  IE support has been deprecated.
