### ISSUE TITLE
Use of tags similar to column formatting

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/sp-dev-docs#6032]
Could you indicate what tags are available in form configuration conditional formula. Are tags such as @me or @currentWeb available, similar to column formatting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
@andrewconnell This is related to form configuration. @VesaJuvonen Do we have an area tag for form configuration?
