### ISSUE TITLE
The parameter d does not exist in method GetListItemChangesSinceToken.

### ISSUE THREAD

**Issue by jon241** [SharePoint/sp-dev-docs#6033]
Whats the "d" element all about? I get an error if I submit that request:

{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message": {
            "lang": "en-US",
            "value": "The parameter d does not exist in method GetListItemChangesSinceToken."
        }
    }
}

Only when I remove the "d" element so that "query" becomes the root element that this request succeeds.
Also note I am using Postman to send my request if thats any help.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e747d28b-d124-0d64-47a3-c39416cd9e64
* Version Independent ID: dec49c04-dcd5-6faa-c88b-2b4bebab285c
* Content: [Synchronize SharePoint items using the REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service)
* Content Source: [docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi jon241,

I followed the doc and am able to reproduce this issue. 

![1](https://user-images.githubusercontent.com/57654821/87518099-69385800-c6b2-11ea-97bd-e9bcb542e84e.jpg)

While the reference of the API metadata ( "_api/$metadata") shows that this method only require 'query' parameter: 

- http://definitelytyped.org/docs/sharepoint--SharePoint/classes/sp.list.html#getlistitemchangessincetoken

![image](https://user-images.githubusercontent.com/57654821/87518554-fe3b5100-c6b2-11ea-8ea2-db58de0fc5d4.png)

I believe this is a mistake, might be it means 'dictionary‘, we can remove it in the request. 

Baker Kong
Microsoft SharePoint Community Support

**Comment by jon241** [comment]
I can close this as soon as its fixed.

**Comment by rajneeshRSI** [comment]
Getting Same error in response in Postman.Is there any workaround to deal with this error in postman.

![image](https://user-images.githubusercontent.com/64845300/103226266-c159d280-4951-11eb-8887-8f9fd9993f5f.png)

Thanks
Rajneesh

**Comment by jon241** [comment]
> 
> 
> Getting Same error in response in Postman.Is there any workaround to deal with this error in postman.
> 
> ![image](https://user-images.githubusercontent.com/64845300/103226266-c159d280-4951-11eb-8887-8f9fd9993f5f.png)
> 
> Thanks
> Rajneesh

If I remember correctly I think the workaround was to remove the "d" parameter enclosing the "query" object (it was some time ago and I no longer work for that company). For example it now becomes:

{
  "query": {
    ...
  }
}
