### ISSUE TITLE
Drag and drop Document library webpart not working

### ISSUE THREAD

**Issue by yborghmans** [SharePoint/sp-dev-docs#6037]
## Category

- [x] Bug

## Describe the bug

> Drag and drop functionality with the out of the box Document Library webpart, isn't working anymore. When performing the drag and drop action, the outline of the website becomes visible but the document is not copied to the webpart.
When going inside the document library itself, so not a page wit the webpart, it works perfectly. 

Tested it with multiple production tenants.

Same page was 100% working a couple of days ago.

## Steps to reproduce

> 
1. Add the out of the box Document Library webpart on a page
1. Select the document library
1. Publish the page
1. Try to drag and drop a document

## Expected behavior

> The document is uploaded to the library/folder.

## Environment details (*development & target environment*)

> 
- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**: Chrome, IE v11 | Edge

**Comment by yborghmans** [comment]
It's also not working with the default webpart that is on a newly created team site.

**Comment by bcameron1231** [comment]
Thank you. This definitely appears to be a bug. We have notified the Team to try and investigate.

**Comment by yborghmans** [comment]
Thx for the answer. I also created a ticket from the O365 admin center, but after waiting for a hour they only came up with uservoice... 🙃
