### ISSUE TITLE
Intercepting Query Changes In Webparts feature is breaking SP.

### ISSUE THREAD

**Issue by OmriCIntlock** [SharePoint/sp-dev-docs#6043]
Using this code now breaks SharePoint.
We have customers using the code in production at the moment.

When will this be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9907ffa7-f129-9b96-d59f-29a060433769
* Version Independent ID: c0c5d82a-a8a6-a44c-81c8-daa47e457ebc
* Content: [Intercepting Query String Changes in Web Parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/intercepting-query-changes-in-webparts#feedback)
* Content Source: [docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **bekaise**

**Comment by andrewconnell** [comment]
There's not enough detail in this to troubleshoot... "breaks SharePoint" isn't descriptive enough. Help us help you.
