### ISSUE TITLE
Custom field created doesn't appear on the UI. It is hidden

### ISSUE THREAD

**Issue by viveksk6** [SharePoint/sp-dev-docs#6044]
I create a custom field using the REST API :
POST https://{site_url}/_api/web/lists(guid'{list_guid}')/Fields
{
  "__metadata": {
    "type": "SP.Field"
  },
  "Title": "field title",
  "FieldTypeKind": 2,
  "Required": "true",
  "EnforceUniqueValues": "true",
  "StaticName": "field name"
}

Custom field created doesn't appear on the UI. It is hidden. To make it appear on the UI, we need to do the following:
Add column -> Show/ Hide columns -> Select the checkbox of the "field title" -> Apply
After doing these steps, I can see the newly created field/column on the UI

Shouldn't it automatically appear on the UI? Also if not, which REST API should I use to make it unhidden? Or which property should I change to make it unhidden via REST API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a8f160-c2fd-8692-1c3f-2c5c44c7a286
* Version Independent ID: 2d7064f8-409c-4465-3fbb-bd6a4c2806f5
* Content: [Working with lists and list items with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#using-etag-values-to-determine-document-and-list-item-versioning)
* Content Source: [docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi viveksk6, 

You need to add it to a view to display it. [Here](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn531433(v=office.15)?redirectedfrom=MSDN#viewfieldcollection-methods) is the API reference:

![image](https://user-images.githubusercontent.com/57654821/87645800-97846900-c780-11ea-9b2f-ae155dbf533a.png)

Test :

1, Create a field
![1](https://user-images.githubusercontent.com/57654821/87646279-3315d980-c781-11ea-8e8e-ff4316ec1c95.jpg)
2, Add to a view (by default it's All Items)
![image](https://user-images.githubusercontent.com/57654821/87646338-4c1e8a80-c781-11ea-8383-2b34b06c6da9.png)

Result: 
![2](https://user-images.githubusercontent.com/57654821/87646481-7bcd9280-c781-11ea-8527-588dfe14d0cf.jpg)
![image](https://user-images.githubusercontent.com/57654821/87646585-99026100-c781-11ea-8f20-3d415903e7b9.png)

Baker Kong
Microsoft SharePoint Community Support
