### ISSUE TITLE
spContext is null

### ISSUE THREAD

**Issue by patriciocarpio** [SharePoint/sp-dev-docs#6045]
[Enter feedback here]

I edited the code exactly as indicated in this page, but when I run it, the spContext comes out as null.
I debugged it and the Session["SPContext"] returns null because Sessions has zero not elements (count = 0)

Any ideas?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42afced-99c6-19a0-0eb3-5b8dd8a41997
* Version Independent ID: c31e26fb-1751-fb5a-6de0-830eb19fe322
* Content: [Include a custom button in the provider-hosted add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in)
* Content Source: [docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, I am unable to reproduce this issue. Are you able to provide your source code to help debug?

**Comment by patriciocarpio** [comment]
Thank you!
Attached is the code. I removed the packages folder.
[1_BeforeSharePointUI.zip](https://github.com/SharePoint/sp-dev-docs/files/4932637/1_BeforeSharePointUI.zip)

**Comment by bcameron1231** [comment]
Hi, Unfortunately, I am unable to figure out what is wrong with your solution. I personally walked through that tutorial in my dev environment and my session objects are populated with values. Can you confirm when you are launching the app from Visual Studio, you aren't just launching the web project... but the add-in is installing in your developer site and launching the Provider Hosted Add-in, passing in the SPHostUrl parameters?

**Comment by patriciocarpio** [comment]
Yes, I can confirm that. 
If I remove the following line from the OrderForm.aspx file, I can use the Web part with no problems:
<link type="text/css" rel="stylesheet" href="<%= spContext.SPHostUrl.ToString() + "_layouts/15/defaultcss.ashx" %>" />

But I don't have access to the SP context at all... Is there any setting in the SP site (or the browser) that may be causing the problem?

**Comment by bcameron1231** [comment]
It doesn't appear to be a SharePoint problem. I tried to create other variables server side, and they were inaccessible in your solution... so something is wrong in your solution... I'm just not sure what.

As mentioned, I started fresh from the tutorial using their sample and walked through it and it worked for me. Maybe it would be worth trying again.
