### ISSUE TITLE
Do you really support Node 10.X?

### ISSUE THREAD

**Issue by mkeysae2** [SharePoint/sp-dev-docs#6046]
I originally setup my development environment a year or two back.  Recently I was having issues, so I uninstalled Node and reinstalled the latest 10.X version following your instructions.  I also uninstalled/installed GULP, YO, and 
@microsoft/generator-sharepoint

When I attempted to use GULP, I received the following error: 

"Your dev environment is running NodeJS version v10.21.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0".

I found this reference where a user has the same issue and the response explains how to install multiple versions of Node: https://sharepoint.stackexchange.com/questions/255951/nodejs-not-compatible
https://github.com/coreybutler/nvm-windows/releases

After switching to version 8.9.4, I am able to use GULP and build my projects.  Is this happening because my project is built on an older version of the SharePoint Framework?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi mkeysae2,

I am using V10.21.0 for SPFx web part development. It works well here.
![image](https://user-images.githubusercontent.com/57654821/87641753-21c9ce80-c77b-11ea-88e1-3881f6ad3e88.png)

Based on the [doc](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs), v8.x.x is for SharePoint Server 2016 and v10.x.x is for SPO. 

I attach the [test demo](https://github.com/kongmengfei/SharedSPFx/blob/master/react-preconfiguredentries/README.md) here, you may have a look.

Baker Kong
Microsoft SharePoint Community Support

**Comment by bcameron1231** [comment]
Hi, yes this is because you are using an older version  of SPFx. My recommendation would be to use the latest version of the SharePoint Framework. Also, if these are scenarios where you are working on different versions of SPFx, my recommendation would be to look into NVM so you can have different versions of node running on your machine.

**Comment by mkeysae2** [comment]
Thank you for the comments.  It makes sense now that this issue is because we are using an older version of SPFx.  I am running NVM so I can switch between versions.
