### ISSUE TITLE
Syntax for conditional field visibility based on multi-choice checkbox selection

### ISSUE THREAD

**Issue by Halfaglassdarkly** [SharePoint/sp-dev-docs#6047]
Hi, is there a more comprehensive list of supported syntax functions for conditional field visibility? I'm trying to confirm if it is possible to show or hide a field based on the selection/s in a multi-choice checkbox drop-down. I have tried Find and Search to search within the multi-choice field's output string but does not appear to be supported?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
@andrewconnell This is for list-form conditional show hide customization. Clearing the list-formatting tag.
