### ISSUE TITLE
URLs mentioned on the page are wrong

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/sp-dev-docs#6049]
## Category

- [x] Bug

## Describe the bug

> URLs mentioned on the page "https://github.com/SharePoint/sp-dev-docs/wiki/SPFX-and-Feature-XML" are wrong.

## Steps to reproduce

> 

1. Go to 'https://github.com/SharePoint/sp-dev-docs/wiki/SPFX-and-Feature-XML'
2. Click on 'How To'
3. Click on  'Turorial.'

## Expected behavior

> These links should open proper page.

## Environment details (*development & target environment*)

> 
- Windows 10
- **Target Environment**: NA
- **Framework**: NA
- **Browser(s)**: Chrome
- **Tooling**: NA
- **Additional details**: NA

### Additional context

>

**Comment by bcameron1231** [comment]
Hi, thank you. Yes indeed these links are wrong. I would suggest working from the docs.microsoft.com site for your documentation as these are updated frequently.  The wiki in the GitHub Repo  is not maintained. 

The links you are trying to find are here.

[How To](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets)
[Tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
