### ISSUE TITLE
What happened to adding SPFX webparts to other office products( i.e. outlook)

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#6055]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ca1a68-c91c-077f-b082-c5184af9b93f
* Version Independent ID: b6b0f7ff-4f39-b05d-c203-92f5aaec3f63
* Content: [SharePoint Framework v1.11 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0)
* Content Source: [docs/spfx/release-1.11.0.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.11.0.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
They are in preview status still with the v1.11 and in roadmap for now. No ETA as such.
