### ISSUE TITLE
SPFX Property panel UI - Title

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#606]
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

The "g" is cutoff in the Property Panel for SPFX webparts - see image
![capturespfx2](https://cloud.githubusercontent.com/assets/9094896/26577365/cef7c8ee-4549-11e7-9310-b998fcb1f95f.PNG)

can we increase the height of the title panel by a pixel or two?

**Comment by nickpape-msft** [comment]
Thank you for the feedback, we will investigate the issue.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
