### ISSUE TITLE
1.11.0 gulp package-solution --ship error

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#6068]
## Category

- [x] Bug

## Describe the bug

Upgraded a project with 365 CLI followed all the steps. (spfx project upgrade --output tour)
gulp serve --nobrowser works fine, the web part show OK
gulp bundle --ship Works OK
gulp package-solution --ship Errors:
`[14:51:06] Verifying configuration... [14:51:06] Done! [14:51:06] [14:51:06] Normalizing solution information... [14:51:06] Attempting creating component definitions for {1} manifests [14:51:06] Created component definitions for {1} manifests [14:51:06] config.solution.features not set! Instead generating a feature for each component. [14:51:06] Creating feature for ECG Requester Inbox... [14:51:06] Done! [14:51:06] [14:51:06] Reading custom Feature XML... [14:51:06] Done! [14:51:06] [14:51:06] Validating App Package... [14:51:06] Done! [14:51:06] [14:51:06] Reading resources... [14:51:06] Done! [14:51:06] [14:51:06] Reading Sharepoint Assets & Creating XML... [14:51:06] Error - 'package-solution' sub task errored after 130 ms Cannot read property 'name' of undefined [14:51:06] 'package-solution' errored after 165 ms [14:51:06] [14:51:06] ==================[ Finished ]================== Error - 'package-solution' sub task errored after 130 ms Cannot read property 'name' of undefined [14:51:07] Project dpc-requester-inbox version:0.0.1 [14:51:07] Build tools version:3.12.1 [14:51:07] Node version:v10.16.0 [14:51:07] Total duration:5.25 s [14:51:07] Task errors:1 The build failed because a task wrote output to stderr. Exiting with exit code: 1`
What Should I do to make it work?

**Comment by larraiz** [comment]
I have the same issue.

**Comment by garrytrinder** [comment]
This is being tracked in the Office 365 CLI repo under pnp/office365-cli#1719

**Comment by waldekmastykarz** [comment]
Reopening this issue, as it's not related to Office 365 CLI. It's an issue with SPFx v1.11. If you don't include the newly introduced _developer_ section in `package-solution.json`, packaging the project fails.

**Comment by jmunozcastro** [comment]
Hi @waldekmastykarz,
Sorry, maybe is obious but, How can I add the developer section in `package-solution.json` since [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/sharepoint-framework-toolchain#scaffold-a-new-client-side-project](url) suggest the same solution but when I add that info I get the next error as the SPFx was not upgraded:
package-solution.json:
`{
  "solution": {
    "name": "JWSPFX Calendar",
    "id": "3d593a2f-73f1-486f-9dae-555c6f6b584d",
    "version": "1.0.0.1"
  },
  "paths": {
    "zippedPackage": "solution/jwspfx-calendar.sppkg"
  },
  "developer": {
    "name": "Whatchtower bible and track society of Pensilvania",
    "websiteUrl": "https://jwsite.sharepoint.com/",
    "privacyUrl": "https://jwsite.sharepoint.com/",
    "termOfUseUrl": "https://jwsite.sharepoint.com/"
  }
}`
Error:
`Error: #/ (Defines parameters for task which cre...)
       Additional properties not allowed: developer
    at validateObjectWithCallback (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at PackageSolutionTask._readConfigFile (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
    at PackageSolutionTask.onRegister (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-common\node_modules\@microsoft\gulp-core-build\lib\index.js:300:24)
    at SPWebBuildRig.initialize (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:30:15)
    at Object.exports.initialize (C:\src\jwspfx-calendar\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\src\jwspfx-calendar\gulpfile.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)`

Next is my package.json, and you can notice the version 11.1.0
`{
  "name": "modern-calendar",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.4.0",
    "@fullcalendar/list": "^4.4.0",
    "@microsoft/rush-stack-compiler-3.2": "0.6.5",
    "@microsoft/sp-core-library": "^1.11.0",
    "@microsoft/sp-webpart-base": "^1.11.0",
    "@types/moment": "^2.13.0",
    "@types/webpack-env": "^1.15.1",
    "jquery": "^3.4.1",
    "node-sass": "^4.14.1",
    "sweetalert2": "^6.4.2",
    "typescript": "^3.9.7"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "^1.11.0",
    "@microsoft/sp-module-interfaces": "^1.11.0",
    "@microsoft/sp-webpart-workbench": "^1.11.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "^3.9.1"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "serve": "gulp serve",
    "bundleShip": "gulp bundle --ship",
    "packageSolutionShip": "gulp package-solution --ship",
    "uploadAppCatalog": "gulp upload-app-pkg"
  }
}
`

Thanks in advance.

**Comment by natpdeee** [comment]
Hi @jmunozcastro 

Can you try to add the `$schema` property in package-solution.json?
 `$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json`

The latest schema contains the developer section
https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json

Thanks @waldekmastykarz . Adding developer property solves the issue!

**Comment by jmunozcastro** [comment]
Thanks so much for the help @natpdeee and @waldekmastykarz, with the schema I can locate rightly the developer section

**Comment by andrewconnell** [comment]
I'm unclear... is this still an error? There was an issue initially when SPFx v1.11 was released that the MSFT-hosted schema hadn't been updated... but I think that's been resolved. Can you confirm @Ofer-Gal as you're the OP?

Also, when pasting a lot of logs and code, please use code fencing (surround with three backticks)... the way things are posted in the issue make the code snippets impossible to read: https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#use-code-formatting-inline--blocks

**Comment by Ofer-Gal** [comment]
@waldekmastykarz  confirmed, on another thread, that the issue is the missing ` "developer": {...} ` section in package-solution.json file.
1.11.0 must have it for `gulp package-solution --ship` to work
I am closing

**Comment by prabhu8323** [comment]
Hello Team,

I am also facing this issue. Could you please help to fix it.

I have create a new webpart and then it gives error whicle executing gulp package-solution --ship

The error occurred after the line:

[10:36:36] Reading Sharepoint Assets & Creating XML...               
[10:36:36] Error - 'package-solution' sub task errored after 189 ms  
 Cannot read property 'name' of undefined                            
[10:36:36] 'package-solution' errored after 220 ms                   
[10:36:36]                                                           
[10:36:37] ==================[ Finished ]==================          
Error - 'package-solution' sub task errored after 189 ms             
 Cannot read property 'name' of undefined                            
[10:36:37] Project recognition version:0.0.1

**Comment by legendgod** [comment]
I added the "developer" section in my package-solution.json. Visual Studio code complain "Property developer is not allowed."
Could you provide a sample for package-solution.json?

**Comment by Ofer-Gal** [comment]
You are some how in the middle between 1.10.0 to 1.11.0 
I suggest you update the yo generator and create a new project, then add your code only 
in 1.11.0 you must have the  developer section 
` "developer": {
      "name": "{yourname}",
      "websiteUrl": "{someurl}",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    },`
You must have the properties, values don't matter

**Comment by legendgod** [comment]
> You are some how in the middle between 1.10.0 to 1.11.0
> I suggest you update the yo generator and create a new project, then add your code only
> in 1.11.0 you must have the developer section
> ` "developer": { "name": "{yourname}", "websiteUrl": "{someurl}", "privacyUrl": "", "termsOfUseUrl": "", "mpnId": "" },`
> You must have the properties, values don't matter

Thanks. I can run gulp package-solution after upgrade yo to 1.11.0
