### ISSUE TITLE
SharePoint Webhooks tenantId not same as azure tenantId

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-docs#607]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When receiving webhook Notification, the notification **tenantId** property is the same as the azure **tenantId** behind o365 subscription.

#### Observed Behavior
If you first create o365 tenant and later associate that tenant with another Azure Ad, the webhooks will still use the old tenantId when sending notifications. This is probably like this on purpose, but this can cause problems when, for example, you try to send the notification to all users belonging to that specific o365 tenant but cannot match the users because they have different tenantId.

#### Steps to Reproduce
associate another azure ad to existing o365 subscription and check the notifications received in endpoint and view the tenantId and compare that to the associated azure ad tenantId.

**Comment by nickpape-msft** [comment]
Thank you for the feedback, we will investigate the issue.

**Comment by chackman** [comment]
The tenantId in the notification package is the SharePoint tenant ID.  It will not necessarily change.
