### ISSUE TITLE
Error publishing spfx 1.11 to AppSource

### ISSUE THREAD

**Issue by tnsholding** [SharePoint/sp-dev-docs#6070]
Please specify how to add a SharePoint Framework solution to the Marketplace/AppSource.

I have followed the instructions to upgrade an existing Spfx 1.10 webpart solution to 1.11. The webpart works when manually uploading to SharePoint app site catalog. 

But I'm failing to upload the sppkg file when trying to create a new SharePoint Solution in the Microsoft Partner Center - Office Store. The verification of the package fails with the following error:

```
Package acceptance validation error: XML Schema Validation Error Error found during XML Schema validation. Error code: The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has invalid child element 'DeveloperProperties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. List of possible elements expected: 'UpgradedEventEndpoint, WebTemplate, SupportedLocales, UninstallingEventEndpoint, InstalledEventEndpoint, SettingsPage, StartPage, SupportedLanguages, SupportPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. Line: 1 Column: 373
Package acceptance validation error: XML Schema Violation Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests.
```

It seems the schema validation fails on the new Developer section added in package-solution.json as specified. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06d649b5-f4bc-ffd9-191b-ab7e758d9a54
* Version Independent ID: c02df482-fcbf-18be-cc15-485ec1d3379b
* Content: [Prepare your SharePoint Framework application for publishing to the Marketplace](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist)
* Content Source: [docs/spfx/publish-to-marketplace-checklist.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/publish-to-marketplace-checklist.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by johnnycardy** [comment]
Also seeing this issue.
I have an open ticket with Partner Center support but haven't had a response yet.

**Comment by andrewconnell** [comment]
Yup... known issue. Nothing you can do on your side, it's an issue on the MSFT side that they need to remove. Simply need to update the schema file used for pre-validation of the solution.

**Comment by tnsholding** [comment]
Thanks for info. Any idea of timeline for this to be done?

**Comment by johnnycardy** [comment]
I think this issue can be closed - AppSource is now accepting SPFx solutions  @tnsholding

**Comment by tnsholding** [comment]
@johnnycardy - yes, seems to work now. Closing issue.
