### ISSUE TITLE
https://mohmmedmeshaa.blogspot.com

### ISSUE THREAD

**Issue by mohmmedmeshi2030** [SharePoint/sp-dev-docs#6071]
[
)https://mohmmedmeshaa.blogspot.com

**Comment by JarbasHorst** [comment]
Hello @mohmmedmeshi2030 

we cannot help you just based on a link. Please, provide more information!

As explained in our wiki ([Issue List: What doesn't belong in the issue list](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#what-doesnt-belong-in-the-issue-list)), this issue list is for SharePoint developer/development issues. All capability question/discussion questions, or topics related to SharePoint administration & end-user topics should be reported through the support user interface available in the tenant admin settings. You can also have a discussion and ask questions at the SharePoint TechCommunity forum.

Regards,
Jarbas
