### ISSUE TITLE
Throttle.htm#1049

### ISSUE THREAD

**Issue by Moberaptor** [SharePoint/sp-dev-docs#6072]
OneDrive for Business always redirect to Throttle.htm#1049

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a62687-377a-6009-47c0-68231099486f
* Version Independent ID: bceadb01-fa32-1f2c-e306-2842a06c4461
* Content: [Handle SharePoint Online throttling by using exponential back off](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/handle-sharepoint-online-throttling-by-using-exponential-back-off)
* Content Source: [docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unclear... I don't see "OneDrive" mentioned anywhere in this doc...
