### ISSUE TITLE
List of Products referred to is out of date

### ISSUE THREAD

**Issue by jeremybarker** [SharePoint/sp-dev-docs#6074]
The page refers to various products as follows:

    Office 365 Midsize Business
    Office 365 Enterprise E1, E3, E4, E5, or K1
    Office 365 Education A2, A3, or A4
    Office 365 Government G1, G3, G4, or K1

but these don't correspond to the currently available products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b3a5c8-08fe-a0c9-c4df-9daaab5a649e
* Version Independent ID: c7e977b2-f2b5-685f-6e84-ce243305cf77
* Content: [Create a developer site on an existing Office 365 subscription](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription)
* Content Source: [docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by NeverHere** [comment]
Please assign this issue to me. Hopefully the pull request #6168 resolves this. Please let me know if additional updates are needed.

**Comment by andrewconnell** [comment]
@NeverHere Just left feedback on the PR... there are some required changes that need to be applied.
