### ISSUE TITLE
Where is the InfoPath replacement for SharePoint 2010 Workflow Initiation Forms?

### ISSUE THREAD

**Issue by zylantha** [SharePoint/sp-dev-docs#6075]
This page goes into great detail about the replacement path for SharePoint 2010 and 2013 workflows, but mentions InfoPath forms only ONCE in passing.

The initiation form for SharePoint 2010 workflows can be highly configured with rich rules and capabilities in InfoPath 2013, which are totally non-existent in Power Automate.  As a very elementary example, the initiation form for a Power Automate flow can have a date field as an input parameter, however the format of this date input field is locked into a "YYYY-MM-DD" format, regardless of localisation.  By contrast, InfoPath 2013 provides a highly configurable workflow initiation form that can be built up with dropdown and multi-select listboxes, with sophisticated filters and heirarchical options.  NO such facility exists in Power Automate, and there is no clear migration path without developing entirely new Power Apps just to create a parameter flow input form (even if that is possible).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc176ce2-e245-8c2a-62a9-29f0fa3f755a
* Version Independent ID: 50df0c72-d567-a572-a4db-80730c5881f7
* Content: [Guidance - Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)
* Content Source: [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nanddeepn** [comment]
You can design similar to initiation form experience in Power Automate.

![automate](https://user-images.githubusercontent.com/8310319/87956469-b3fc0a80-cacc-11ea-87e9-b52adbb09cf5.png)

This will help you to get input from users before starting the Power Automate flow.

**Comment by zylantha** [comment]
Thank you for your response, I am fully aware of the ability to provide BASIC inputs in an initiation into a Power Automate flow.  

As per the original report, there is:

1. No localisation of the date format (it is locked to "YYYY-MM-DD").

2. No dynamic picklist support - the possible selections for a text input are locked and defined in the flow, they cannot be looked up from a SharePoint list.

3. No comparable  equivalent of Infopath 2013 to create highly customised initiation forms - for example, dynamic picklists (with filters, cascading lookups), dynamically visible/invisible sections (e.g. click a checkbox, and a new set of inputs appears that was previously hidden), dynamic rulesets (e.g. column validation, actions), and much more rich functionality to define an initiation form.  There are MANY more features in Infopath that are not available in Power Automate.

The "here are a bunch of user inputs as variables" is no replacement for InfoPath, nor does it even provide basic functionality equivalent to what is available out of the box for SharePoint 2010 workflows.

For a web page that is trying to describe all the pain points, this falls way short of a passing grade in this respect.

**Comment by rmillener** [comment]
We moved to using Logic Apps for workflow and https://www.form.io/ for forms.

**Comment by zylantha** [comment]
Thanks for your input @rmillener but I'm not clear on how that really solves the gap in the ability to customise the initialisation form for a Power Automate flow, for a citizen developer.

Power Automate easily enough allows you to specify various input parameters that can be used within the flow, as @nanddeepn pointed out.  No big deal, SharePoint 2010 workflows from 10 years ago allowed you to do this as well.  

The issue, which is the entire point of this pain point, is that SharePoint 2010 allows you to instantly customise that initialisation form using InfoPath 2013.  Literally all you need to do to edit the initialisation form is to click on the form against the workflow in SharePoint Designer, and it opens up in InfoPath 2013, and you can edit EVERYTHING to do with the form, no programming required, no app required, no powerapps license, no powerapps training.  The entire form just gets opened up in a form editor for you to start working on.  Add messages, hyperlinks, change fonts, lookups - whatever.  It's all there.

If you have a "number" parameter that is meant to contain an ID from a sharepoint list, you can just create a lookup using a secondary data source in about 30 seconds flat, tied to that input parameter.  Want to do cascading lookups?  No problem, just set them up.  It starts in a basic form, and ends in a highly customised form, with no programming, and the outputs usable by the workflow to do whatever is required.

How are you supposed to do that equivalent function in a Power Automate flow?  

Well, I am gradually learning that this is *POSSIBLE* with the combination of PowerApps and Power Automate.  However there is no way to create the PowerApps form (app) as a starting point in the same way that SharePoint Designer 2013 creates your form for you.  I literally would have to learn PowerApps from scratch, then instead of starting with my workflow I have to start with a PowerApp, which needs to be passed the ID of the SharePoint item that I want to initiate the flow against, then recreate the form that normally appears on the initialisation of the flow, then pass all those parameters over to a flow by linking them manually.  THEN I have to go back to SharePoint 2013 to add the initialisation of that flow as a custom action against the list that I started with in the first place, using the URL of the PowerApp, passing the ID of the item to operate on.  I can conceptualise how this potentially can function, however it is a LONG way from how it worked in InfoPath 2013 / SharePoint Designer 2013 / SharePoint 2010 workflows.

I can also see that IF Power Automate had the equivalent of the "Edit Initialisation Form" feature that SharePoint Designer 2013 has for a SharePoint 2010 workflow, which:

1. Created a PowerApp that was automatically linked into the flow, the list item that the flow was initiated against, and replaced the default form that was displayed for the flow
2. Was in all respects identical in function and capability to the form that is normally displayed, but provided the ability to customise it with all the lookups and functionality of PowerApps, WITHOUT needing the user to create it from scratch and link it up with everything
3. When there are any changes to the parameters of the flow, could easily be updated (refreshed) so that those parameters became available to be added into or updated in the form (equivalent to the way that it currently operates in InfoPath 2013 - i.e. make the changes to the parameters in SharePoint Designer, save the flow, open the form, and it automatically prompts to update the available fields --> fix the fields --> publish the form, then publish the workflow, job done)...

... THEN there it could be said there was broadly equivalent functionality - i.e. PowerApps could be a feasible replacement of InfoPath for editing the initialisation form of Power Automate flows.  

However all the tutorials, automated app creation functionality, and everything else about Power Apps is aimed at using it to replace the View/Edit/Create forms in SharePoint.  Well guess what, that capability is NOT going away yet - you can still edit those forms in InfoPath 2013, and it still works pretty seamlessly (even if you are using modern views).  

There is nowhere I've seen that gives you a demonstration of how to use Power Apps to replace the initialisation form editor capability of InfoPath 2013 for SharePoint 2010 workflows.  It's even been said to me that "there is no way to customise the initialisation form of a PowerApps flow" - which isn't strictly true, however it is just (as I have described above) incredibly clunky and requires a significant amount of non-citizen-developer skills.  

Don't get me wrong, there are many limitations in the way that InfoPath 2013 works and the capabilities that it can provide in the initialisation form, that PowerApps has the potential to address.

However the current disconnectedness between PowerApps and Flow, in particular that there is no way to transform the initialisation form of a Power Automate flow into a customisable Power App, is a SIGNIFICANT pain point that needs to be mentioned and addressed before SharePoint 2010 workflows are killed in Office 365.  That this article that is specifically meant to identify those pain points makes NO MENTION of the initialisation form cusomisation is a serious shortcoming and shows that there is a significant gap in the current understanding within Microsoft of how its own customers use its own tools.  Has Microsoft forgotten about this initialisation form customisation functionality from SharePoint 2010, or is it just choosing to ignore it?
