### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by MDBosa** [SharePoint/sp-dev-docs#6078]
There is no walkaroud to create and update hyperlink. Rest is all we have

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc176ce2-e245-8c2a-62a9-29f0fa3f755a
* Version Independent ID: 50df0c72-d567-a572-a4db-80730c5881f7
* Content: [Guidance - Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)
* Content Source: [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sorry, but I'm not clear what you are referring to...

**Comment by zylantha** [comment]
MDBosa is referring to the inability of Power Automate to update any SharePoint Hyperlink column in any list/library - the update actions available simply ignore this column type and they are not available to update.

This type of update is trivially easy in SharePoint Workflow - they are simply treated as a text field that can be updated like any other text field.

Any SharePoint 2010 workflow that needs to update a Hyperlink column cannot be migrated to Power Automate, given that Power automate cannot update Hyperlink columns - a feature gap that is not mentioned in this article, but should be.

**Comment by zylantha** [comment]
@MDBosa please reiterate that my summary of the issue is correct, in order to keep this issue open.  This affects me as well, however due to no action from MS and comment from you this is being marked as stale, even though it isn't.

**Comment by MDBosa** [comment]
The summary of Zylantha is correct
