### ISSUE TITLE
403 Forbidden SharePoint Designer 2013 connecting to SPO

### ISSUE THREAD

**Issue by mmmiller73** [SharePoint/sp-dev-docs#6080]
SharePoint Designer 2013 connecting to SPO

We migrated from SP2013 to SPO with classic sites (not my idea).  We have a ton of SP Designer workflows that will eventually be redone in Power Automate but for now I need to access them to make adjustments.  When I try to connect to the SP Online sites on my new laptop with SP Designer 2013, I get the 403 forbidden error.  I have downloaded the 64-bit version and tried to download SP 1 but I had already downloaded the latest version.  It is not a permissions issue as I am global admin and site collection admin as well as access the SP Online sites using SP Designer on my old machine.  When I log in, I am getting a 403 Forbidden error.  Microsoft sent me here for assistance.  Any help would be appreciated.

**Comment by andrewconnell** [comment]
Unfortunately, this isn't a development issue... they shouldn't have sent you here. If "MSFT" = partner support or premiere support or creating a ticket in your SPO admin center, I'd suggest you use Tech Community. This forum is for development topics.
