### ISSUE TITLE
Can't open link with  "data-interception='off'" for IE

### ISSUE THREAD

**Issue by IlyeniaMaksim** [SharePoint/sp-dev-docs#6081]
We are using "data-interception='off'" attribute for <a> elements with server-relative SharePoint links like `<a href='/sites/home' target='_blank'>Home site</a>    `
I've checked without "data-interception='off'" and it works but opens in self tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2321fde2-93bd-8529-a7e6-76d1f85b359f
* Version Independent ID: 9b6fd36b-0a17-3648-cc56-808334efa861
* Content: [Hyperlinking considerations in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking)
* Content Source: [docs/spfx/hyperlinking.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/hyperlinking.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi IlyeniaMaksim,

I tested this issue with following anchors in an SPFx webpart:

1. The href is an external site and did not set "data-interception='off'"
`<a href="https://github.com" className={styles.button} target="_blank">external site, no data-interception</a>`

2. The href is an external site and set "data-interception='off'"
`<a href="https://github.com" className={styles.button} target="_blank" data-interception="off">external site + data-interception</a>`

3. The href is a server-relative SharePoint link and did not set "data-interception='off'"
`<a href="/sites/sbdev/Lists/DraftApps/AllItems.aspx" className={styles.button} target="_blank" >SP site, no data-interception</a>`

4. The href is a server-relative SharePoint link and set "data-interception='off'"
`<a href="/sites/sbdev/Lists/DraftApps/AllItems.aspx" className={styles.button} target="_blank" data-interception="off">SP site + data-interception</a>`

Result: 
Here it shows that when the URL is an external site, it will open a new tab whether we set "data-interception" or not. 
For SP links, by default it will open in a self tab. If we add "data-interception", it will open in a new tab, this is an expected result as the doc described. 

![test](https://user-images.githubusercontent.com/57654821/88125670-5a95f780-cc02-11ea-89f3-dd037c56b8f4.gif)

Baker Kong
Microsoft SharePoint Community Support

**Comment by IlyeniaMaksim** [comment]
Thanks!
It works:
```
<a href="..." target="_blank" data-interception="off" >
    <div>
          <span>Text</span> 
          <span>Text</span>
    </div>  
</a>
```

But does not work:
```
<a href="..." target="_blank" data-interception="off" >

          <span>Text</span> 
          <span>Text</span>

</a>
```

In <a> tag content must be wrapped to one element
