### ISSUE TITLE
New comer to the community

### ISSUE THREAD

**Issue by Wadneyare** [SharePoint/sp-dev-docs#6087]
I worked with powershell  & pnp powershell for 8 years and build and learn self made techniques. i would like to share my million code Powershell development asset. please advise who i can share this solitary findings and how i can post to my space, 
Born to learn and sharing is caring.
http://galans.net 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f0bf18-5ece-8fac-f602-17500085ad26
* Version Independent ID: 087cf5a1-6c1e-1f19-b3c1-d1e661092fb3
* Content: [SharePoint Developer Community (SharePoint PnP) resources](https://docs.microsoft.com/en-us/sharepoint/dev/community/community#community-calls)
* Content Source: [docs/community/community.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/community/community.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @Wadneyare 

if you have something specific you want to share with the Microsoft 365 community, please create a pull request in the corresponding repository.

Thanks
Jarbas

**Comment by nanddeepn** [comment]
Hi @Wadneyare 

Here is the PnP PowerShell repo: https://github.com/pnp/PnP-PowerShell
