### ISSUE TITLE
Getting warning messages : Warning - [sass] The local CSS class 'min-chart' is not camelCase and will not be type-safe.

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/sp-dev-docs#6088]
## Category

- [X] Question

## Question

I am using third party css in SPFx. When I am building it, SPFx is showing me lots of warning messages :

![image](https://user-images.githubusercontent.com/6926513/88081588-34d70700-cb9e-11ea-8928-3c900907a39c.png)

Please let me know how to disable these warning messages.

## Environment details (*development & target environment*)

- **Windows 10**: 
- **Target Environment**: [SharePoint Online]
- **Framework**: [ Node.js v6/v8/v10]
- **Browser(s)**: [e.g. Chrome v79 | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.11.0 ]
- **Additional details**: *NA.*

**Comment by kongmengfei** [comment]
Hi gauravgoyal5,

I think the cause of this warning is that the generated style object has a dash in its name. You can tell Gulp to ignore these warnings: 

- [Warning suppression in SPFx](https://www.c-sharpcorner.com/blogs/spfxlearning-and-findings)

Baker Kong
Microsoft SharePoint Community Support

**Comment by gauravgoyal5** [comment]
Thank you. This solution is working fine.
Here is another solution also : https://sharepoint.stackexchange.com/questions/282956/getting-warning-messages-warning-sass-the-local-css-class-min-chart-is-n/282958#282958
