### ISSUE TITLE
Additional HTML Tags are visible in footer of this page t;>'; }

### ISSUE THREAD

**Issue by virendrak** [SharePoint/sp-dev-docs#609]
#### Category
- [ ] Typo
#### Steps to Reproduce
_Please see bottom of the page (https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/integrate-with-property-pane), above footer section. I have used Google Chrome browser._

![image](https://cloud.githubusercontent.com/assets/10959600/26625575/285effe2-4612-11e7-8264-6ef18b403710.png)

**Comment by pgonzal** [comment]
@VesaJuvonen

**Comment by VesaJuvonen** [comment]
These are unfortunately rendering issues from the dev.office.com CMS system. Will forward this again to right contacts.

**Comment by VesaJuvonen** [comment]
These should be now again fixed - issues from our CMS system, which hopefully should be finally properly resolved.
