### ISSUE TITLE
Recipients field

### ISSUE THREAD

**Issue by Peter-Ross-C** [SharePoint/sp-dev-docs#6092]
Hi there,

I feel that some clarity should be added around the Recipients field as to my understanding only entities that have an email address will work, e.g. users, O365 Groups etc. I think it should also be more clear from the front-end that the Role Definition can be used. 

Most people using the older 2010/2013 workflows I believe would be used to using SharePoint groups to assign permissions, so there needs to be some clear outline of the shift to using O365 Groups. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970571ac-4a34-7ec7-a412-91ad243d24c0
* Version Independent ID: ae225235-4559-e28b-bc32-453a1b96dea5
* Content: [Manage list item and file permissions with Power Automate](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/manage-list-item-file-permissions)
* Content Source: [docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jlagden** [comment]
The page doesn't even tell you what the recipients field should contain - Should it be an array of email addresses? Comma separated list? Semi-colon separated email list?
