### ISSUE TITLE
When I deploy SPFX Webpart to specific Teams as Teams Tab , Property Pane is always opening it is not hiding at all

### ISSUE THREAD

**Issue by applekajui6** [SharePoint/sp-dev-docs#6093]
## Category

When I deploy SPFX Webpart to specific Teams as Teams Tab , Property Pane is always opening it is not hiding at all

## Describe the bug
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart
I have  deployed SPFX Webpart to my group site and for that specific Team , i want to show my SPFX as a Team Tab I have followed the instructions in the MS DOCS but Property Pane is not hiding at all always opening and there is not close button for the property pane to close it

![image](https://user-images.githubusercontent.com/60218749/88160020-b9bc3200-cc2b-11ea-9fc0-fcca7e1885fd.png)

## Steps to reproduce

Followed the below article
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart

## Expected behavior

Property Pane should be hidden always.

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node JS 10.17.0
- **Browser(s)**: Chrome Version 84.0.4147.105 and Edge 41.16299.1480.0
- **Tooling**:  VS Code 1.47.3 | SPFx v1.10.0 
- **Additional details**:  Solution - Github Repo URL : https://github.com/applekajui6/teamstab

**Comment by kongmengfei** [comment]
Hi applekajui6,

I followed the tutorial and created a team app, it works well. 

![2](https://user-images.githubusercontent.com/57654821/88260136-5d721480-ccf6-11ea-8e7f-c9ad920fc99b.jpg)

The property panel could be closed and open again through "Settings".

I attached the [test demo](https://github.com/kongmengfei/SharedSPFx/blob/master/teams-tab/teams/manifest.json) here, you may have a check.

Baker Kong
Microsoft SharePoint Community Support

**Comment by applekajui6** [comment]
Its not working for me.. tried same solution ...  Is there any configuration required?
![image](https://user-images.githubusercontent.com/60218749/88368181-20b42500-cdab-11ea-908f-d4d592c85cc0.png)

**Comment by andrewconnell** [comment]
@applekajui6 Can you provide a repro? Such as sharing the code for your project in a public GH repo? Like @kongmengfei I can't repro what you're seeing.

**Comment by applekajui6** [comment]
Hi Andrew ,
I have updated those contex details and also PFB for the repo URL link:
https://github.com/applekajui6/teamstab

**Comment by patmill** [comment]
Sorry for going dark.  We can't repro this, but my guess is that you have created / uploaded a custom manifest where you have a static tab that has openpropertypane=true in the query string.
