### ISSUE TITLE
Failed to load some part of a WebPart

### ISSUE THREAD

**Issue by mbratukha** [SharePoint/sp-dev-docs#6099]
## Category

- [x] Bug

## Describe the bug

We have a wab part that is used productive since more than 6 months. One of our customers getting sometimes the following error:
![image](https://user-images.githubusercontent.com/1413357/88377306-3885ac00-cd9f-11ea-927b-631eff161b40.png)

I was able to get the error on customer's environment with my account in Chromium Edge v84. The error that I've got:
```
Da hat etwas nicht geklappt.
Wenn das Problem weiterhin besteht, wenden Sie sich an den Websiteadministrator, und teilen Sie ihm die Informationen unter "Technische Details" mit.
TECHNISCHE DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "2b62a679-0691-4378-a58e-edef3656c5d0" (ModernNewsWebPart). Original error: Failed to load URL 'https://contoso-app3a23c3e4cda846a085282455972a5a23.sharepoint.com/sites/intranet/ClientSideAssets/307f56f4-58f9-4ef9-b9df-ef6b9b90a1f0/modern-news-web-part_2886373515bbb985856f9f93e3acd26c.js' for resource 'modern-news-web-part' in component '2b62a679-0691-4378-a58e-edef3656c5d0' (ModernNewsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://contoso-app3a23c3e4cda846a085282455972a5a23.sharepoint.com/sites/intranet/ClientSideAssets/307f56f4-58f9-4ef9-b9df-ef6b9b90a1f0/modern-news-web-part_2886373515bbb985856f9f93e3acd26c.js' for resource 'modern-news-web-part' in component '2b62a679-0691-4378-a58e-edef3656c5d0' (ModernNewsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_c9133458c77abc2d9b9504f909a25885.js:1:861189)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_c9133458c77abc2d9b9504f909a25885.js:1:1162925)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_c9133458c77abc2d9b9504f909a25885.js:1:1218211)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_c9133458c77abc2d9b9504f909a25885.js:1:1214256)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_c9133458c77abc2d9b9504f909a25885.js:1:1206205
```

In most cases the reloading of a page helps, but there are some users that need to reload a page multiple times (more than 4 times) until the web part is loaded correctly. 

We have invested a lot of time trying to figure out the source of the issue, but no luck till now.

## Expected behavior

The WebPart is loaded correctly for all users in any browser.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: node v10.19.0
- **Browser**: Chromium Edge v84.0.522.40
- **Tooling**: SPFx v1.8.2

### Additional context
- until now the issue is appeared only in Chromium Edge
- the web part is deployed to the app catalog of a site collection
- related issues: #3871 and https://github.com/SharePoint/sp-dev-gdpr-activity-hub/issues/51

Any ideas what can be the source of the issue?

**Comment by andrewconnell** [comment]
Usually this is a temporary issue with the O365 CDN... from my exp, there's not much you can do to "fix" this. The first thing I'd do is upgrade your component to the latest SPFx.

MSFT is in the midst of switching their module loader in SPFx (from system.js > require.js)... hopefully this will address some of these random CDN issues.

**Comment by mbratukha** [comment]
@andrewconnell thank you for your answer.
We will try to upgrade the component to the latest SPFx.

It there any information when the switching to RequireJS may occur?

**Comment by andrewconnell** [comment]
Yes: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.10.0#deprecations-and-removed-items-in-this-release

But note that's from January 2020. Nothing since then...
