### ISSUE TITLE
Workbench.html is blank

### ISSUE THREAD

**Issue by spcrux** [SharePoint/sp-dev-docs#61]
After running gulp serve, localhost:4321/temp/workbench.html is opened in default browser but it's blank.

**Comment by VesaJuvonen** [comment]
Client side web part does not appear automatically on the page, so you'll need to hover on the middle of the page to get + icon visible, from where you can then add your web part on the page. That should sort this one out or is your web part missing from the editor as well?

**Comment by mauricionr** [comment]
i'm also got a blank screen because the files were not found as i said here #9

**Comment by spcrux** [comment]
For me there's nothing on the page. Not even the text "SharePoint Workbench" as shown in the screenshot in first tutorial.

**Comment by johnnliu** [comment]
which browser?  I've had issues with Edge.  Chrome and IE11 works ok.

**Comment by iclanton** [comment]
Are there any errors in the developer tools console when the page loads?

**Comment by mauricionr** [comment]
This happen on ubuntu

![image](https://cloud.githubusercontent.com/assets/2263551/17877709/a3362978-68bb-11e6-8645-05bb1acbba3e.png)

**Comment by patmill** [comment]
So the references to things like react.js should have a node_modules before them.  This is what I see on windows - http://patmill6:4321/node_modules/react/dist/react.js and flux is http://patmill6:4321/node_modules/flux/dist/Flux.js 

Your picture is showing a much stranger collection of URLs, with react missing the node_modules and flux looking for them inside our module loader.

**Comment by mauricionr** [comment]
@patmill i just call this task `gulp serve` and when i switch to the browser got a blank screen with lot of 404, checkout the other image

![image](https://cloud.githubusercontent.com/assets/2263551/17913247/14ed4a84-696f-11e6-8ed8-d67d2919f207.png)

**Comment by spcrux** [comment]
Same for me. I'm using Chrome
![workbench error](https://cloud.githubusercontent.com/assets/12823646/17914886/4ec113e2-69e9-11e6-94eb-14712c454320.jpg)

**Comment by chakkaradeep** [comment]
@mauricionr @spcrux this error message of not able to find react, flux is because it didn't run one of the post install scripts. Basically here is the line that downloads and bundles react for local dev environment, which should be when yo ran:

```
> @microsoft/sp-module-loader@0.1.11 install C:\Users\Admin\apps\helloword-webpart\node_modules\@microsoft\sp-module-loader
> node npm-install-script.js

Can you try in a new fresh project to see if you still get this error and also notice what happens during the above command?

**Comment by iclanton** [comment]
It might also mean that react, react-dom, or flux wasn't fully installed. You can try running `npm install` again.

**Comment by spcrux** [comment]
@iclanton @chakkaradeep I tried running npm install again but that didnt help. so I created a new project and it worked. 
Thanks everyone for the response. I think the issue can be closed unless anyone else has same issue.

**Comment by mauricionr** [comment]
I created a new fresh project, fixed the issues as here #9 and i'm still seem a blank page with lots of 404(ubuntu)


Thanks

**Comment by jbristowe** [comment]
@mauricionr: Make sure you can resolve your hostname:

```bash
$ hostname
mauricionr
$ ping mauricionr
ping: cannot resolve mauricionr: Unknown host
```

If your hostname cannot be resolved (like above) then check to see if the hostname is present in **/etc/hosts**. Once you can resolve your hostname to an IP address, everything should work.

**Comment by nickpape-msft** [comment]
@mauricionr, did jbristowe's advice help? Are you still encountering this issue?

**Comment by mauricionr** [comment]
For me its ok

**Comment by manishgarg1** [comment]
This should be fixed now. Hence resolving.

**Comment by nigel-dewar** [comment]
Doesnt work for me. Fresh install of ALL the tools, get nothing but a blank screen

**Comment by DinethNipuna** [comment]
Hi all,
I also have the same issue, my SP page also blank. 
See the attached 
![emptysp](https://user-images.githubusercontent.com/24534571/51654249-12851d00-1feb-11e9-8aec-f7c30153560c.png)

see my gulp serve
![gulp](https://user-images.githubusercontent.com/24534571/51654283-3d6f7100-1feb-11e9-931e-ae207047fd1a.png)
