### ISSUE TITLE
Environment is only available during render

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/sp-dev-docs#610]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Environment.type should be available when methods within my BaseClientSideWebPart are called from an onclick event on my web part.

#### Observed Behavior
Environment.type is not available after render as the Environment is not set.

#### Workaround
set a private variable within my BaseClientSideWebPart with the value of Environment.type during within the render method.

#### Steps to Reproduce
create event that checks the Environment.type

**Comment by waldekmastykarz** [comment]
How are you accessing `Environment.type`? If I do it like:

```ts
// ...
import { Environment } from '@microsoft/sp-core-library';

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  public render(): void {
    this.domElement.innerHTML = `
      <div class="${styles.helloWorld}">
        <div class="${styles.container}">
          <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
            <div class="ms-Grid-col ms-u-lg10 ms-u-xl8 ms-u-xlPush2 ms-u-lgPush1">
              <span class="ms-font-xl ms-fontColor-white">Welcome to SharePoint!</span>
              <p class="ms-font-l ms-fontColor-white">Customize SharePoint experiences using Web Parts.</p>
              <p class="ms-font-l ms-fontColor-white">${escape(this.properties.description)}</p>
              <a href="#" class="${styles.button}">
                <span class="${styles.label}">Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>`;

      this.domElement.querySelector('a').addEventListener('click', this.click.bind(this));
  }

  private click(): boolean {
    console.log(Environment.type);
    return false;
  }

  // ...
}
```

everything seems to work as expected?

**Comment by Pieter-Veenstra** [comment]
Hi Waldek,

I'm attaching the event listener in a slightly different way. I wonder if that makes the difference:

```
var myForm: Element = document.querySelector(`#myForm`);

        myform.addEventListener('click', (evt: Event) => {
            this.updateData();
        }, false);
```

**Comment by waldekmastykarz** [comment]
In which method are you using this code? If I use this approach in `render` everything still seems to be working correctly.

**Comment by Pieter-Veenstra** [comment]
The above 4 lines are included in render method. within the updateData method, I seem to be missing the Environment. If it is working for you then I'll investigate a bit further. 

At least I now know that it should be working. Thanks for your help so far.

**Comment by waldekmastykarz** [comment]
You're welcome. Hope it helps.

**Comment by Pieter-Veenstra** [comment]
This is weird, I've now switched the code back to use Environment.type instead of using my private variable within the web part class. and it is all working again as expected.
