### ISSUE TITLE
Debug error message appears on _layouts/15/viewlsts.aspx after debugging

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#6101]
## Category

- [x] Bug

## Describe the bug

The following error message appears all over SharePoint on Site Contents after debugging has started and already ended.

![Screenshot 2020-07-24 at 19 19 42](https://user-images.githubusercontent.com/5503835/88417855-fbdba400-cde2-11ea-9b53-e8a05e38bea6.png)

## Steps to reproduce
1. Debug SharePoint Framework web part or application customizer with the query string '?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js'
1. Stop debugging and navigate to any site collection using /_layouts/15/viewlsts.aspx?view=14 like the regular link on 'Site Contents'

## Expected behavior
* **Option 1:** Once a debugging session has been finished it may ask only once if you really like to debug still
* **Option 2:** Don't try to load debugging for _layouts pages.

## Intermediate solution
* **Option 1:** Closing the browser and open it again.
* **Option 2:** sessionStorage.clear() on the console of the browser

## Environment details (*development & target environment*)
General issue related by passing in the query parameter.

Tested in this case in Firefox.

**Comment by andrewconnell** [comment]
I think that's related to this: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages#disabling-debug-scripts

Once you start a debug session, it is persisted through the browser session unless you reset it.

**Comment by StfBauer** [comment]
Thank you @andrewconnell - Confirmed - documented but awkward implementation.

The only question left. Why pages only in the _layouts/15 show this error message but none of the others. Considering this I think it is a bug rather than a wanted behaviour. 

Especially look at the "errorLoadingDebugManifestTitle" as well as "debugManifestErrorDebugDismissButtonText" this seems more like an incomplete malicious implementation.

**Comment by andrewconnell** [comment]
@johnguy0 ... can you address @StfBauer's follow up questions? This is related to the change that was made a while back that you were looking into...

**Comment by patmill** [comment]
BTW, adding ?reset=true  will remove the debug state as well (https://onedrive.visualstudio.com/WEX!/_boards/board/t/Extensibility/Features)

I can't get the exact last comment you have to repro, but depending on which codepath executes (service worker, full navigate, partial navigate, etc.) if the specific 'try and load the debug manifests' isn't triggered, the warning won't pop up.
