### ISSUE TITLE
Underlying connection closed

### ISSUE THREAD

**Issue by pawans9127** [SharePoint/sp-dev-docs#6106]
## Category
Question

## Question
I'm using SharePoint CSOM to perform operations like creating site, updating user roles etc from my web api. I'm seeing an error occurring often in my environment with the following stack trace  :

The underlying connection was closed: The connection was closed unexpectedly.
at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()

I have already checked for the TLS version/Throttling issues in SharePoint environment and found no problems there. Can you please help me explain the root cause for this.

## Environment details (if applicable)

- **Your Developer Environment**: Win server 2016
- **Target Environment**: SharePoint Online
- **Framework**: NET Framework v4.5 
- **Browser(s)**: 
- **Tooling**: Visual Studio 2013
- **Additional details**: 

Thanks

**Comment by andrewconnell** [comment]
Can you provide more context? What version of the CSOM are you using, share code where the issue is happening, etc?

**Comment by pawans9127** [comment]
Hi Andrew,

Apologies for the incomplete details. 

I'm using 16.1 version of SharePoint.client.dll

The problematic code looks something like this (Apologies, I can't add the code in its entirety , Idea is to add new roles to users in a site.) : 

var usersList = GetSiteUsers(spsiteurl) ; //Fetches all the users of the site
`var newroles = GetRoles(); //Get the new roles that need to be assigned to the user in the site

foreach(var user in usersList){
     
     SP.User checkuser = this.Web.EnsureUser(user.LoginName);
     SP.Principal p = (SP.Principal)checkuser;
    //Break role inheritance
     this.Web.BreakRoleInheritance(true, false);
    SP.RoleAssignment requiredassignment = this.Web.RoleAssignments.GetByPrincipal(p);

    //Assign each role to the user
    foreach (string role in newrole)
    {
               SP.RoleDefinition roletypes = this.Web.RoleDefinitions.GetByType(GetRoleType(role)); //GetRoleType gives..
              ..corresponding SharePoint roles that needs to be added to the user
               requiredassignment .RoleDefinitionBindings.Add(roletypes);
     }
    requiredassignment.Update();
    this.ExecuteQuery(); //Update
}
`
After code executes the last line : ExecuteQuery, I get WebException : with the mentioned stack trace :

The underlying connection was closed: The connection was closed unexpectedly.
at System.Net.HttpWebRequest.GetResponse()
at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()

I understand there is a problem of code efficiency, however, I have seen it works fine for hundreds of users fine but fails sporadically for which I don't understand the root cause.

Please let me know if I can provide any more details. 

Thank you!

**Comment by andrewconnell** [comment]
So you're saying it sometimes fails? That sounds like either a networking issue or that whatever process contains this code is long running and the connection is timing out. Doesn't look like there's anything wrong with the code :-/
