### ISSUE TITLE
clientSideComponentProperties Usage Clarification

### ISSUE THREAD

**Issue by newgardj** [SharePoint/sp-dev-docs#6109]
**clientSideComponentProperties** is listed as an optional parameter for passing properties to extensions. No example is provided on this page or in the example documentation:

_clientSideComponentProperties: An optional parameter, which can be used to provide properties for the extension instance._

[Register Extension Sample](https://github.com/pnp/sp-dev-site-scripts/blob/master/samples/site-register-spfx-extension/register_extension.json)

Site Design Schema notes the property type as String, based on this and the XML/JSON examples I have tested the following:

[Site Design Schema](https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json)

**serve.json**
![image](https://user-images.githubusercontent.com/34944901/88605950-9bde3b00-d038-11ea-9e10-92f8f305399d.png)

**elements.xml**
![image](https://user-images.githubusercontent.com/34944901/88605974-abf61a80-d038-11ea-8dad-cc29e90c7493.png)

**Escaped JSON** - Site Design Action Succeeds - Property Not Displayed
![image](https://user-images.githubusercontent.com/34944901/88606013-c3350800-d038-11ea-8334-446badf28c7f.png)

**Escaped XML** - Site Design Action Fails
![image](https://user-images.githubusercontent.com/34944901/88606031-d47e1480-d038-11ea-8379-0360e152da60.png)

I am using the yeoman generator and default code here:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension

Looking to confirm and/or see an example of the expected format and that this functionality does work via Site Design Scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by DaleyKD** [comment]
Any update on this?

**Comment by patmill** [comment]
So, the contents of the parameter are ultimately JSON.
`{"Top":"Top area of the page","Bottom":"Bottom area in the page"}`

  However, the transport of that content determines the encoding.  For example, if it is being put into an XML file, then you need to XMLEncode it
 `{&quot;Top&quot;:&quot;Top area of the page&quot;,&quot;Bottom&quot;:&quot;Bottom area in the page&quot;}
`

Given that the site scripts are JSON, I would assume that you don't need to encode them (given that encoding it as a plain string doesn't work).  To be honest though, I'm not completely familiar with the site design formatting.  If the un-encoded doesn't work, report back here and we'll try and find a site-design person to follow up.
