### ISSUE TITLE
Warning on hosted workbench points to dev.microsoft.com

### ISSUE THREAD

**Issue by hugoabernier** [SharePoint/sp-dev-docs#6110]
## Category

- [x] Bug

## Describe the bug

If you launch the hosted workbench while your SPFx solution isn't `gulp serv`ing, you get a dialog:

![image](https://user-images.githubusercontent.com/13972467/88674704-231ec380-d0b8-11ea-8981-65177a39ec96.png)

The link provided in the dialog points to `https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part`

## Steps to reproduce

1. Go to your tenant's hosted workbench without running `gulp serve`
1. A dialog will appear telling you that you won't see your web parts
1. Click on the `click here` link
1. You'll get a page not found error

## Expected behavior

- URL should point to a valid page
- Dialog box **should not** say **click here** for accessibility reasons. Maybe something like "Find out [how to build your first web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)"

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chromium Edge
- **Tooling**: VS Code | SPFx v1.11.0

**Comment by KevinTCoughlin** [comment]
Thanks for reporting @hugoabernier, we have a fix for this.

**Comment by KevinTCoughlin** [comment]
Closing. The link was fixed and points to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part.
