### ISSUE TITLE
How Can We Ensure SPFx Web Part Titles Always Match the Style of Default Web Parts

### ISSUE THREAD

**Issue by joshmcrty** [SharePoint/sp-dev-docs#6113]
SharePoint has recently been updated with new Fluent UI styles, which looks great, but unfortunately this has created inconsistency with default web part titles and custom SPFx web parts that use https://pnp.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/ or their own styles that matched the "old" design.

Web part titles are bolder and use a smaller font size now. I (and I'm sure many others) have created multiple SPFx web parts that display a web part title, and these title styles no longer match the default web parts in SharePoint that use the newer Fluent UI design. How can we develop web parts with titles in the future so the title always matches the "global" web part title styles and we don't have to manually update and redeploy all of our SPFx web parts for all clients to match the styles again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64088ab-1fa9-5657-e827-a3d13eb52406
* Version Independent ID: 97acfdcc-2f1f-c135-fb6f-89c7633d4c8e
* Content: [Titles and descriptions for SharePoint web parts](https://docs.microsoft.com/en-us/sharepoint/dev/design/web-part-titles-and-descriptions)
* Content Source: [docs/design/web-part-titles-and-descriptions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/design/web-part-titles-and-descriptions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sunishissac** [comment]
To solve this issue, one solution is to provide a property pane option to hide or edit the webpart title. The text webpart provided with SharePoint can then be added above the webpart to format/customize the Title as per the user requirement.

**Comment by AJIXuMuK** [comment]
Hello @joshmcrty - sorry for the long delay.
It's a completely valid question.

Unfortunately, there is no universal code you can use to "match" the look and feel of the webpart title, or any other page component.
We're trying to be more predictive next time the styles change to provide look books/changes notes beforehand as well as work more closely with PnP Controls team to release new versions with needed updates.
