### ISSUE TITLE
Command Set onInit is executed only once

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/sp-dev-docs#6116]
## Category
- [x] Bug?
- [x] Question

## Describe the bug
The oninit() for my command set is only executed once. This happens after navigating to another list and go back to my original list.

Is this behavior by design? Or is this a bug that I found. I only wan't to enable my custom command set on specific list so I use the oninit() at this moment to do this. But this breaks when switching lists through navigating in the quick launch. When doing a hard refresh with CTRL+F5 the oninit() is fired again.

## Steps to reproduce
Create 2 custom lists
Add both to quick launch
Create a Hello World Command Set example with console.log() in the oninit()
Deploy the solution
Click on list 1 in the quick launch and see a console log
Click on list 2 in the quick launch and see a console log
Now click again on list 1 in the quick launch. There is no oninit in the console.log. 
When setting a breakpoint in the oninit() see it isn't called

## Expected behavior
When I click on list 1 in the quick launch I see a console log
When I click on list 2 in the quick launch I see a console log
When I now click again on list 1 in the quick launch I want to see a console log oninit()
I use the oninit() to enable of disable the command on specific list with specific contentypes.
So I want to use the oninit() to do this.

## Environment details (*development & target environment*)
Windows 10
SharePoint online
Node V10
Browser: Chrome
VSCode, SpFx 1.10

![image](https://user-images.githubusercontent.com/16294209/88789699-54ba8c00-d197-11ea-9aa0-7cc04c877dcb.png)

**Comment by andrewconnell** [comment]
A fix has been applied to a similar issue... see #6611... can you verify if this resolved your issue?

**Comment by waaromikniet** [comment]
I created this example because I had the issue mentioned in #5704. That is working (oninit is firing when navigating in the quicklaunch) now so this issue can be closed.

**Comment by waaromikniet** [comment]
I have tested on one of my older tenants and there I still see the oninit() is fired only once when switching between lists in the quicklaunch. 

Does this mean that this is by design? And I should use another route to display a command button in my list?

**Comment by AJIXuMuK** [comment]
@waaromikniet - sorry for the long delay.
`onInit` is fired when the command set is initialized. For example, when you navigate to a list for the first time.
At that moment your commands will be "attached" to the list and will be available for use.
You can change the visibility of the commands in `onListViewUpdated` or `onExecute` later on if needed.
