### ISSUE TITLE
Need React Component for new Taxonomy Picker control released by Microsoft to use it in custom SPFx Webparts.

### ISSUE THREAD

**Issue by bhavyachhabra29** [SharePoint/sp-dev-docs#6117]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> Microsoft have pushed some new changes recently where the taxonomy picker in modern sites has changed. It is coming in a modal pop up as a taxonomy web tagging control like it used to be earlier in classic sites. I have attached the screenshot for this control in this issue below as well. 
We have some custom SPFx React webparts where we need to use the latest taxonomy picker control. I haven’t found the new taxonomy picker control which is being used on modern sites anywhere on the Fluent UI (https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers) . There is a control on PnP controls page (https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/) but that opens the term set and terms in a panel and not in a modal dialog.  Since we want to have a similar look and feel for the users for taxonomy picker in our custom webparts as well, please let us know where we can get the React component for this new taxonomy control pushed by Microsoft. 

We have around 20 sites in our tenant which are having the usage of taxonomy and are using custom webparts. It will help us in providing the same experience to the users If we have that control , it will help us a lot.

![NewTaxonomyPicker1](https://user-images.githubusercontent.com/47315777/88789401-58a8d700-d1b4-11ea-8e6b-03f8403d4766.jpg)
![NewTaxonomyPicker2](https://user-images.githubusercontent.com/47315777/88789405-59416d80-d1b4-11ea-87e4-4b25a04bd6ce.jpg)

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows Server 2012 R2]
- **Target Environment**: [e.g. SharePoint Online]
- **Framework**: [e.g. Node.js v8]
- **Browser(s)**: [e.g. Chrome v84 ]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by bcameron1231** [comment]
Thanks for the comment / question. Unfortunately, Microsoft doesn't provide the components for us to implement in our custom solutions. 

You will have to build this taxonomy picker yourself, and you could also ask for an enhancement from the PnP Reusable controls to match OOTB functionality (This is likely to take a while if it were to happen). Given the PnP Controls is open source, you could also make the UX experience changes yourself using that code base as a starting place. 

Best of luck!

**Comment by bhavyachhabra29** [comment]
Hi Beau, Thanks a lot for the update. Actually I had asked for this because on Fluent UI page which is managed by Microsoft, we are able to see lot of other controls which are used on modern sites. These controls are given there with some sample code as well. I checked the pickers section there https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers .It has other pickers with sample code but not a taxonomypicker. Hence, I asked this question.

**Comment by andrewconnell** [comment]
As @bcameron1231 said, there's no component provided by MSFT for us to use. You can look at this project that contains a picker to see if this helps: https://pnp.github.io/sp-dev-fx-controls-react/controls/TaxonomyPicker/
