### ISSUE TITLE
Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/

### ISSUE THREAD

**Issue by viveksk6** [SharePoint/sp-dev-docs#6118]
All the ALM APIs on this page return the error when i use tenant scope

```
{
    "odata.error": {
        "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException",
        "message": {
            "lang": "en-US",
            "value": "Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."
        }
    }
}
Same thing is happening with the site collection scope too:
{
    "odata.error": {
        "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException",
        "message": {
            "lang": "en-US",
            "value": "Cannot find resource for the request SP.RequestContext.current/web/sitecollectionappcatalog/."
        }
    }
}
```

What would the workaround be? What am I missing?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Need more context in how you are building the endpoint... the error indicates you aren't correcting the correct endpoint

**Comment by viveksk6** [comment]
When I try to hit the endpoint GET /_api/web/tenantappcatalog/AvailableApps I get the error
![image](https://user-images.githubusercontent.com/36484434/89033798-38644e00-d355-11ea-9bf5-0dea7417e55d.png)
But when I try to use the endpoint GET /_api/web/tenantappcatalog I dont get any error:
![image](https://user-images.githubusercontent.com/36484434/89034082-dfe18080-d355-11ea-8e2d-50e2b043e6de.png)

**Comment by andrewconnell** [comment]
Can you confirm the site URL you are using? The `{{sp_site_url}}` in your screenshots should be the URL of your tenant app catalog.

**Comment by viveksk6** [comment]
I actually wanted to manage the apps in a particular site added through sharepoint store. I want to perform actions like create a replica of an app present in a site. How should I do that?  Should I use a different REST API endpoint?
