### ISSUE TITLE
Using yammer api making the page slow.

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#612]
We are using Yammer api in one of our web part:
Functionality:
For every list item , there will be a yammer thread created in yammer and then with flow we are updating the list item with the thread ID created in yammer.
We are binding the list data along with the Yammer likes and Comments for that Thread.
So, ideally if there are 10 items, there are 10 yammer api calls are being called.
This is making the page slower and we are facing a poor performance because of this.
We are using Yammer Rest api to achieve this.
@VelinGeorgiev  Could you be able to help us in this?

Many Thanks
Siddhartha

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
