### ISSUE TITLE
Scope of permissions

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#6123]
Please details on how you limit the scope of the permissions for a given AppID (ClientID).   Granting access to all site collections in the tenant is a huge security problem and violates basic least-permissions best practices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
This is the app permission scope description:
![Image 7](https://user-images.githubusercontent.com/28797671/89019660-377ced80-d350-11ea-828d-19a2ac090c89.png)

When setting to http://sharepoint/content/sitecollection, it will give site collection permission where the add-in installed, this won't be affect all the site collections in Tenant just the one which installed the App.

You can control the permission type to make sure the security.

[Add-in permissions in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint)
