### ISSUE TITLE
Dynamic Data UI issue with collapsible property groups

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#6125]
## Category

- [x] Bug

## Describe the bug
When you put a property field as the first field in a web part property pane group, the three dots to select a data source is misplaced a bit:
<img width="234" alt="SPFx-DynamicField" src="https://user-images.githubusercontent.com/9973962/88983151-78caba00-d2ca-11ea-8468-01e75458fae0.PNG">
Things become worse when you make the groups collapsible, the three dots move somewhere in the property group header AND becomes unclickable. Clicking it, collapses/expands the group instead of showing the Dynamic Data selection:
<img width="251" alt="SPFx-DynamicField-AccordionGroup" src="https://user-images.githubusercontent.com/9973962/88983199-9dbf2d00-d2ca-11ea-91d6-e380b67b0e66.PNG">

## Steps to reproduce
1. Create an SPFx web part with 1.11
2. Put a Dynamic Data property as the first property in a property pane group
3. Make the property pane groups collapsible (accordion == true)
4. Install the package
5. Notice the three dots being misplaced/unclickable.

## Expected behavior
I expect the three dots to be closer to the actual field for which they trigger Dynamic Data + that it is actually clickable!

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 1909
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chromium Edge v84
- **Tooling**: VS Code | SPFx v1.11.0

**Comment by AJIXuMuK** [comment]
Hello @YannickRe  - sorry for the long delay.
It seems the issue has been fixed by now:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/17036219/143296605-2f584a54-bcbb-420a-8d8d-c4d95b7eea14.png">
<img width="258" alt="image" src="https://user-images.githubusercontent.com/17036219/143296695-9acf4cd9-b5e0-4051-ad38-de0b7fd0545a.png">

Could you please check it on your side?

**Comment by YannickRe** [comment]
Hi @AJIXuMuK ,

Better late than never, but I don't have anything anymore to test now and no time to actually create something new to test this.
I will just assume it now works (I totally forgot that I logged this issue anyway 😀).
