### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by paulaeschlimann** [SharePoint/sp-dev-docs#6129]
Unfortunately, I already encounter a problem when trying to start developing a SharePoint Provider Hosted Add-In. When processing step 4 in chapter "_To modify the TokenHelper_" I alway get an error with `X509SigningCredentials` saying:

> Error	CS1729	'X509SigningCredentials' does not contain a constructor that takes 3 arguments

I have added the reference to "C:\Program Files\Reference Assemblies\Microsoft\Windows Identity Foundation\v3.5\Microsoft.IdentityModel.dll".

I tried to replace this using directive:
`using X509SigningCredentials = Microsoft.IdentityModel.Tokens.X509SigningCredentials;`

with:
`using X509SigningCredentials = System.IdentityModel.Tokens.X509SigningCredentials;`

But then, I get two other errors saying:

> Error	CS0117	'SecurityAlgorithms' does not contain a definition for 'RsaSha256'
> Error	CS1503	Argument 6: cannot convert from 'System.IdentityModel.Tokens.X509SigningCredentials' to 'Microsoft.IdentityModel.Tokens.SigningCredentials'

Can somebody please point me into the right direction? Many thanks in advance for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352d4d6f-951b-979e-fb9b-d1bd8a565462
* Version Independent ID: 4168674f-a1ea-a70b-b7d6-4eea85734e89
* Content: [Package and publish high-trust SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nbeniou** [comment]
Is there any answerto this?
