### ISSUE TITLE
Spfx web part - not able to programmatically open property pane in Teams

### ISSUE THREAD

**Issue by tnsholding** [SharePoint/sp-dev-docs#6134]
## Category

- [ X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have an Spfx web part using the PnP Placeholder control (https://pnp.github.io/sp-dev-fx-controls-react/controls/Placeholder/) and having the button open the property pane with the following 'onConfigure' handler:
`props.context.propertyPane.open();`

This works fine when the web part is on a SharePoint page. But when added as a Teams tab, the above code only works, if the property pane has already been opened before (by clicking 'Settings' from the tab dropdown menu). 
If the web part loads and the user immediately clicks the button, then nothing happens.  

It seems some javascript for property pane is not properly loaded until 'settings' has been clicked. 

## Environment details (if applicable)

- **Your Developer Environment**:  Windows 10
- **Target Environment**: Teams
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: SPFx v1.11.0

**Comment by patmill** [comment]
Sorry for the delay.  Teams doesn't really allow you to modify the settings of an app w/o going through the settings flow.  Thus, the property pane won't open outside of that flow.
