### ISSUE TITLE
Scoping

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-docs#6138]
This is a continuation of this:
https://github.com/SharePoint/sp-dev-docs/issues/6123

What about details on when the app registration is created in the Azure AD portal?  Is there any way to limit access to a given site / library / etc

The scenario that I am thinking of here is an automated process that runs on-prem to add/update data in a SharePoint list or library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
The app registered in Azure AD Portal still didn't provide permission scope for specific site/library, please see the capture below:

![Image 23](https://user-images.githubusercontent.com/28797671/89505537-5a018180-d7fc-11ea-9fed-7b4946fa7a52.png)

[Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
