### ISSUE TITLE
Add screenshots with steps on how to acquire solution from store and add/distribute solution to tenant users

### ISSUE THREAD

**Issue by Indrasenac** [SharePoint/sp-dev-docs#6139]
We have general points on where to install solution ex: app catalog but we do not have specific steps with clear guidance to ISV on how to Install the solution from store, distribute it to users etc 

Current document helps developers but not end users/IT admins to acquire solutions from sharepoint store. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c67e69-7ad4-63d7-9731-5db531553761
* Version Independent ID: 63c39c79-2c3b-e018-dfa5-91bbb0117f29
* Content: [Maintain and support your published app](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-after-publishing)
* Content Source: [docs/spfx/publish-to-marketplace-after-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/publish-to-marketplace-after-publishing.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
That's correct... this is the SharePoint developer documentation site, so that would be expected...

**Comment by Indrasenac** [comment]
Could you please route this to correct document page, if this is not the write place.  Its a feedback from our ISV's as they are looking for documentation to share with their customers to easily accquire SPFx solutions from store.
