### ISSUE TITLE
Error on phantom

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#614]
Error when creating the first webpart.

Hello

When I try to use the yeoman generator, I get this error, I already installed the latest version of SPFx, any idea?

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--cache-min" "86400"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luis.valencia/Documents/npm-debug.log

**Comment by waldekmastykarz** [comment]
Have you tried deleting the node_modules folder and restoring dependencies using `npm install`?

**Comment by levalencia** [comment]
thanks Waldek, that worked.

**Comment by cythomli** [comment]
@waldekmastykarz I'm receiving the same error. I tried deleting node_modules and running npm install gives the same error. Please let me know if you have any other suggestions to resolve. Thanks!

**Comment by waldekmastykarz** [comment]
@cythomli I've seen this error come and go. Lame advice, but could you wait a moment, and try to see if it still happens? Alternatively, can you check if a different project or machine yield the same error?
