### ISSUE TITLE
Excluding on-premise entries from search results with Sharepoint search REST API?

### ISSUE THREAD

**Issue by nozhT** [SharePoint/sp-dev-docs#6140]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

How do I exclude on-premise entries from my search results?

I'll need to do so for multiple clients, and since these are my client's tenants I can't add / modify their search settings.

Ideally I can add a keyword or tweak a flag when querying and the search API will exclude on-premise results from the response, but I can't identify any flags in https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview that seem to do this.

If that's impossible,  I can also retrieve on-premise and Sharepoint Online results and then somehow filter out the on-premise results using some of the returned properties, but I don't know if there's a reliable way to do so for different tenants.

## Environment details (*development & target environment*)

- **Target Environment**: SharePoint Online
- **Additional details**: The tenant is an on-premise and Sharepoint Online hybrid environment

**Comment by andrewconnell** [comment]
What about filtering by domain? If the domain is `*.SharePoint.com`, it's SPO... otherwise it's on-prem?

**Comment by wobba** [comment]
`NOT (IsExternalContent:1)` should do the trick for hybrid crawled content. Docs at https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-cloud-hybrid-searchroadmap#about-the-isexternalcontent-managed-property
