### ISSUE TITLE
How to get document icon while using CMAL query in document library in sharepoint online

### ISSUE THREAD

**Issue by spo365** [SharePoint/sp-dev-docs#6141]
## Category

- [ ] Question

## Question
How to get document icon while using CMAL query in document library in sharepoint online
below is my query 
> public static getItemsByViewQuery(context,listName:string, query:string):Promise<any> {
    let web = new Web(context.pageContext.web.absoluteUrl); 
    const xml = '<View><Query>' + query + '</Query></View>';  
    return web.lists.getByTitle(listName).getItemsByCAMLQuery({'ViewXml':xml}).then((res:SPHttpClientResponse) => {
        return res;
    })
}

## Environment details (*development & target environment*)

>  sharepoint online

**Comment by kongmengfei** [comment]
Hi spo365,

I think the icon of a doc is determined by its file type. Can you have a look this blog? It mentioned an endpoint that could get the correspoinding icon for each type file. 

- http://sharepoint.sureshc.com/2016/05/how-to-get-document-type-icon-using-maptoicon-rest-api.html

Baker Kong
Microsoft SharePoint Community Support
