### ISSUE TITLE
SPFx solution with SP assets Access Denied on mobile requests

### ISSUE THREAD

**Issue by flaviuc** [SharePoint/sp-dev-docs#6142]
## Category
- [x] Bug

## Describe the bug
SPFx solution with SP assets (resources deployed in hidden library in App Catalog "Client Side Assets")
Deploy solution through app catalog to a regular site.
Accessing through desktop browser -> no problem
Accessing with iPad or iPhone browser -> we get an Access Denied on the resources in "Client Side Assets"
Very important: End Users for the app catalog is empty, but this should not be a problem since "End Users" goal is to control which users can install / deploy solutions, not which users access the resources.

## Steps to reproduce
SharePoint 2019
Latests SPFx 
SPFx solution with SP assets (resources deployed in hidden library in App Catalog "Client Side Assets")
Deploy solution through app catalog to a regular site.
Accessing through desktop browser -> no problem
Accessing with iPad or iPhone browser -> we get an Access Denied on the resources in "Client Side Assets"
Very important: End Users for the app catalog is empty, but this should not be a problem since "End Users" goal is to control which users can install / deploy solutions, and NOT which users access the resources files.

## Expected behavior
That we do not get an Access Denied on the resource file from "Client Side Assets" in mobile browsing.

## Environment details (*development & target environment*)
SharePoint 2019 Server On-Premises
Latests SPFx version, supported Node versions and Yo generator.

### Additional context
The behavior is not consistent between mobile and desktop browsing and between on-premises and SPO. In SPO the behavior does not reproduce.
The "extra" difference between OK / NOK cases is that if we assign a user the Site "Open" permission on the app catalog then the behavior goes away. However this is not a mandatory step in our documentation as the "End Users" field on app catalog creation is meant for another functionality.
It feels like an impersonation step is missing somewhere in the mobile browsing code path.

**Comment by patmill** [comment]
You'll want to make sure that the client side assets folder is accessible (read) to the users.  Is it possible that the ios browser isn't properly authenticating the user in some way?  What is the current user when this happens?

**Comment by flaviuc** [comment]
@patmill no actually, users do not require explicit permission on that folder. Access through the desktop experience works fine. This means, there must be 2 codepaths: one for mobile, one for desktop experience.
In the desktop experience codepath there must be some kind of background elevation or impersonation of a system account, that is just completely missing in the mobile codepath.
The behavior is thus inconsistent.

**Comment by kitzler-walli** [comment]
I solved this problem by assigning read access to all authenticated users on the Client Side Assets library.

**Comment by smchargue** [comment]
I'm getting what I think is a similar issue - framework is working as expected on all supported browsers on a desktop, but fail in testing all browser on an iOS device.  assigning additional permissions to the /sites/apps catalog not an option, and assigning permission that are not needed except to mask a problem in the code is not solving a problem, it is working around a problem. 

If this helps anyone, this is what is under "details" on the mobile devices. 

SPLoaderError.loadComponentError]:
Failed to load component "12deff50-a81a-414a-90af-9b0ba6606e86" (*******WebPart). Original error: 
Failed to load entry point from component "12deff50-a81a-414a-90af-9b0ba6606e86" 
(*******WebPart). Original error: Error loading https://component-id.invalid/12deff50-a81a-414a-90af-9b0ba6606e86_0.0.1
Unable to load script https://*******.sharepoint.com/sites/apps/ClientSideAssets/746c6fa4-4728-4cf2-b5bb-bd011ad1e46d/*******-*****_604d6b7beb71bfb9651f9da88785c647.js

INNERERROR:
Failed to load entry point from component "12deff50-a81a-414a-90af-9b0ba6606e86" (*******WebPart). Original error: 
Error loading https://component-id.invalid/12deff50-a81a-414a-90af-9b0ba6606e86_0.0.1

Unable to load script https://*******.sharepoint.com/sites/apps/ClientSideAssets/746c6fa4-4728-4cf2-b5bb-bd011ad1e46d/*******-*****_604d6b7beb71bfb9651f9da88785c647.js

CALLSTACK:
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_5d5c3b3c5c270587c1170972ed477e14.js:65:19899
t@https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_5d5c3b3c5c270587c1170972ed477e14.js:65:169956
t@[native code]
https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_5d5c3b3c5c270587c1170972ed477e14.js:65:207325
https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_ec51c37c549687dc4960.js:1:66002
promiseReactionJob@[native code]
