### ISSUE TITLE
Get .app or .sppkg file content of the apps 

### ISSUE THREAD

**Issue by viveksk6** [SharePoint/sp-dev-docs#6143]
Using the REST API: 
GET /_api/web/{scope}appcatalog/AvailableApps
does not give me the list of apps installed using sharepoint store. It gives me only the apps in tenant app catalog.
How do I get the .app or .sppkg file content of the particular app installed using sharepoint store? Where can I find the documentation of which REST API endpoint to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97580aa9-d30e-fc44-e83f-ae11422e7aa6
* Version Independent ID: 83691fea-7fbc-1b87-7c3f-08152d28f136
* Content: [Application Lifecycle Management (ALM) APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest)
* Content Source: [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/alm-api-for-spfx-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The ALM APIs are scoped to your SharePoint tenant... apps from the SharePoint Store are coming from App Source so they won't include those apps. I'm not aware of an API for App Source at this time.
