### ISSUE TITLE
gulp package-solution return  Cannot read property 'name' of undefined error

### ISSUE THREAD

**Issue by legendgod** [SharePoint/sp-dev-docs#6144]
I follow the tutorial to update my schema.xml, elements.xml and package-solution.json.
After I ran "gulp package-solution" it throw error 

```
[18:42:17] Error - 'package-solution' sub task errored after 42 ms
 Cannot read property 'name' of undefined
[18:42:17] 'package-solution' errored after 50 ms
```

I check the "name" property is all 3 files and looks good.. how could I can troubleshoot it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Akeloya** [comment]
Hello!

Can you check this issue https://github.com/SharePoint/sp-dev-docs/issues/6068 ?

It's helped me.
A added 'developer' section inside 'solution' section:

```
"solution": {
  "name": "some existed name",
  "developer": {
    "name": "added name"
  }
}
```

**Comment by Jerry0527** [comment]
I suggest you can upgrade to latest spfx generator version using this command:
npm install @microsoft/generator-sharepoint@latest -g
Then you can create a new spfx web part solution with the latest spfx generator, then open the solution with VSCode, open package-solution.json within config folder, you can find out the schema below, check to see if you have missed some necessary tag:

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "latestwebpart-client-side-solution",
    "id": "b3141c3c-9ebd-44ae-a1b2-cd2b1a8c511b",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    }
  },
  "paths": {
    "zippedPackage": "solution/latestwebpart.sppkg"
  }
}

**Comment by legendgod** [comment]
Thanks it work after upgrade yo generator and add "developer" section.

**Comment by Jerry0527** [comment]
@legendgod ,

Great to hear this information. Then you could close the issue now :)

**Comment by legendgod** [comment]
I am not sure whether it is related. After upgrade generator I can no longer Yo a new project.
my node version is v10.22.0, @microsoft/generator-sharepoint@1.11.0

When I create a new folder and key in "yo @microsoft/sharepoint" but fail. I got error:


npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uifabric%2ficons - Not found
npm ERR! 404
npm ERR! 404  '@uifabric/icons@7.3.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)


It works before I upgrade the sharepoint generator. May I know the best version combination for SPFX?

**Comment by Akeloya** [comment]
@legendgod This is npm issue. Please check npm status. https://status.npmjs.org/
This Incident began on Aug 6, 08:29 UTC and was resolved Aug 6, 12:01 UTC

**Comment by legendgod** [comment]
> @legendgod This is npm issue. Please check npm status. https://status.npmjs.org/
> This Incident began on Aug 6, 08:29 UTC and was resolved Aug 6, 12:01 UTC

You're right. It is working now. Thanks.
Is there any way to switch to alternative server during outage?
