### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getClient' of undefined

### ISSUE THREAD

**Issue by legendgod** [SharePoint/sp-dev-docs#6146]
I follow the sample and build my function like follow:
```
@autobind
private retrieveUserInfo(): void { 
    this.context.msGraphClientFactory 
    .getClient()
    .then((client: MSGraphClient): void=> { 
      // get information about the current user from the Microsoft Graph 
      client 
      .api('users')
      .version("v1.0") 
      .select("displayName,mail,userPrincipalName") 
...........
```

In VS Code, there is no error indicated. Right click on "getClient" and "msGraphClientFactory" cannot find the definition. In the test run by gulp serve, the function is throwing error in console: "**Uncaught TypeError: Cannot read property 'getClient' of undefined**". It sounds like function is not properly defined. How should I troubleshoot it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2381d26e-96c9-44de-8e4e-f70edc2db498
* Version Independent ID: f81cacee-a1cd-89dd-ee53-c84689c03917
* Content: [Use the MSGraphClient to connect to Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph)
* Content Source: [docs/spfx/use-msgraph.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-msgraph.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The code seems fine, but there's a lot of context missing (SPFx version, environment, etc.) making it hard to troubleshoot...
