### ISSUE TITLE
SPFx Application Extension not rendering

### ISSUE THREAD

**Issue by tplive** [SharePoint/sp-dev-docs#6148]
## Category

- [x] Bug

## Describe the bug

> I follow the guidance [Build your first SharePoint Framework Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension) and get to the point where the page is rendered and the dialog should be displayed. I see no dialog, there is nothing in the console log corresponding to the logging code in the extension, but the locally running gulp terminal shows requests coming from the browser.

## Steps to reproduce

1. Go to [Build your first SharePoint Framework Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
1. Follow the steps to get the basic HelloWorld extension running locally with gulp
1. Go to your SharePoint tenant modern page, add the debug query parameters as indicated by gulp. 
1. Confirm allow running debug scripts
1. Observe that no SP dialog opens.
1. Observe that there is no logging from the extension in the Chrome Dev Tools log.
1. Observe that the running gulp console shows that requests for the extension are coming from the browser.

## Expected behavior
I expect the same outcome as in the mentioned article; that the dialog shows the configured message as expected.

## Environment details (*development & target environment*)

- **Developer Environment**: MacOS 10.15.6 Catalina
- **Target Environment**: SharePoint Online client tenant.
- **Framework**: Node.js v10.19.0
- **Browser(s)**: Chrome 84
- **Tooling**: VSCode, @microsoft/generator-sharepoint@1.10.0
- **Additional details**: 

### Additional context

We are developing solutions in our client's SharePoint tenants, and currently have one test and one QA SharePoint Online tenants, configured the same. I get the same problem in both tenants.  I've tried Googling the issue, but haven't found any similar problems.

*Thanks for your contribution! Sharing is caring.*

**Comment by tplive** [comment]
I have now also tested from Windows, and using a brand new, clean SharePoint tenant, and I get the same result.

**Comment by andrewconnell** [comment]
Can you share a copy of your project in a public GH repo?

**Comment by tplive** [comment]
I have now also tested from Windows, and using a brand new, clean SharePoint tenant, and I get the same result.

> 
> 
> Can you share a copy of your project in a public GH repo?

Sure can 😄: https://github.com/tplive/spfxtest

**Comment by kongmengfei** [comment]
Hi tplive,

I downloaded your project and tested it on my SPO, here it works well. 

![test](https://user-images.githubusercontent.com/57654821/89879277-45a2f780-dbf5-11ea-9bf3-23ecb07d54f4.gif)

Just changed 'pageUrl' in server.json file:

![image](https://user-images.githubusercontent.com/57654821/89879508-a3cfda80-dbf5-11ea-8966-b2515198c739.png)

My Environment details:
Node.js : v10.21.0
Chrome: Version 84.0.4147.105 (Official Build) (64-bit)

Best Regard,
Baker Kong

**Comment by tplive** [comment]
Today I did the same as before, on the same Windows computer, no changes. Today it works. I have no idea why. 🙄
