### ISSUE TITLE
JSON view formatting hideSelection broken in targeted release

### ISSUE THREAD

**Issue by RowanAdvisors** [SharePoint/sp-dev-docs#6150]
## Category

- [x] Bug

## Describe the bug

JSON view formatting hideSelection does not work correctly in targeted release.  Instead when set to false the row formatter is not applied to the view.

## Steps to reproduce

1) Create a new site/list in a targeted release tenant
2) Copy and paste the Multi-line view style sample from the link below into the JSON view formatter
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#:~:text=%20Use%20view%20formatting%20to%20customize%20SharePoint%20,you%20understand%20the%20schema.%20%20...%20More%20
3) Click Preview
4) Change the hideSelection value to false
5) Click Preview

## Expected behavior

View renders with/without the row selector.

## Environment details (*development & target environment*)
Targeted release
SharePoint Online

### Additional context
An MS Support case has been opened and apparently they are "unable to escalate the ticket to the SharePoint product team".  This makes no sense from an organizational or product support standpoint.

Waiting to test this in a standard release environment

**Comment by RowanAdvisors** [comment]
Also MS support pointed me to github/stackoverflow in general.  Which also makes no sense.

**Comment by shagra-ms** [comment]
@RowanAdvisors Thanks for reporting this. The issue has been addressed and the fix will be rolled out in the next few weeks.

**Comment by shagra-ms** [comment]
This has been fixed. Please let me know if you are still facing this issue. Thanks!
