### ISSUE TITLE
Cannot read property 'name' of undefined - when run "gulp package-solution"

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-dev-docs#6151]
## Category

- [x] Bug

## Describe the bug

When i run the command `gulp package-solution`. It shows me the below error:
![image](https://user-images.githubusercontent.com/23545532/89608871-d94c8f00-d8a8-11ea-933c-09c882ea6d7e.png)

This error only occured in some of ,my projects. Other projects in my same computer have no issue. So i believe there is not a problem of my enviorment.

And I cloned the project to my other computer and it works fine.

I tried to remove all the `node_modules` `lib` and` package-lock.json` and `npm i `again. Issues still exists.

## Steps to reproduce

1. Run `gulp clean` , `gulp bundle --ship` and `gulp package-solution --ship`
2.  `Cannot read property 'name' of undefined` error comes out

## Expected behavior

the ability to execute gulp package-solution --ship without error.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**: Node.js v10.22.0
- **Browser(s)**: Chrome 
- **Tooling**: VS Code

![image](https://user-images.githubusercontent.com/23545532/89609295-ff266380-d8a9-11ea-9c45-4444f56fff16.png)

**Comment by Jerry0527** [comment]
@Lilian1331,

Please check the same issue below which I answered yesterday:

[gulp package-solution return Cannot read property 'name' of undefined error #6144](https://github.com/SharePoint/sp-dev-docs/issues/6144)

I suggest you can upgrade to latest spfx generator version using this command:
npm install @microsoft/generator-sharepoint@latest -g

Then you can create a new spfx web part solution with the latest spfx generator, then open the solution with VSCode, open package-solution.json within config folder, you can find out the schema below, check to see if you have missed some necessary tag like developer:

{
"$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
"solution": {
"name": "latestwebpart-client-side-solution",
"id": "b3141c3c-9ebd-44ae-a1b2-cd2b1a8c511b",
"version": "1.0.0.0",
"includeClientSideAssets": true,
"isDomainIsolated": false,
"developer": {
"name": "",
"websiteUrl": "",
"privacyUrl": "",
"termsOfUseUrl": "",
"mpnId": ""
}
},
"paths": {
"zippedPackage": "solution/latestwebpart.sppkg"
}
}

**Comment by Lilian1331** [comment]
> @Lilian1331,
> 
> Please check the same issue below which I answered yesterday:
> 
> [gulp package-solution return Cannot read property 'name' of undefined error #6144](https://github.com/SharePoint/sp-dev-docs/issues/6144)
> 
> I suggest you can upgrade to latest spfx generator version using this command:
> npm install @microsoft/generator-sharepoint@latest -g
> 
> Then you can create a new spfx web part solution with the latest spfx generator, then open the solution with VSCode, open package-solution.json within config folder, you can find out the schema below, check to see if you have missed some necessary tag like developer:
> 
> {
> "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
> "solution": {
> "name": "latestwebpart-client-side-solution",
> "id": "b3141c3c-9ebd-44ae-a1b2-cd2b1a8c511b",
> "version": "1.0.0.0",
> "includeClientSideAssets": true,
> "isDomainIsolated": false,
> "developer": {
> "name": "",
> "websiteUrl": "",
> "privacyUrl": "",
> "termsOfUseUrl": "",
> "mpnId": ""
> }
> },
> "paths": {
> "zippedPackage": "solution/latestwebpart.sppkg"
> }
> }T

**Comment by Lilian1331** [comment]
> > @Lilian1331,
> > Please check the same issue below which I answered yesterday:
> > [gulp package-solution return Cannot read property 'name' of undefined error #6144](https://github.com/SharePoint/sp-dev-docs/issues/6144)
> > I suggest you can upgrade to latest spfx generator version using this command:
> > npm install @microsoft/generator-sharepoint@latest -g
> > Then you can create a new spfx web part solution with the latest spfx generator, then open the solution with VSCode, open package-solution.json within config folder, you can find out the schema below, check to see if you have missed some necessary tag like developer:
> > {
> > "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
> > "solution": {
> > "name": "latestwebpart-client-side-solution",
> > "id": "b3141c3c-9ebd-44ae-a1b2-cd2b1a8c511b",
> > "version": "1.0.0.0",
> > "includeClientSideAssets": true,
> > "isDomainIsolated": false,
> > "developer": {
> > "name": "",
> > "websiteUrl": "",
> > "privacyUrl": "",
> > "termsOfUseUrl": "",
> > "mpnId": ""
> > }
> > },
> > "paths": {
> > "zippedPackage": "solution/latestwebpart.sppkg"
> > }
> > }T

Great I have added the section of developer in my `package-solution.json` and it works!!!!!! Thanks!!!

```
"developer": {
"name": "",
"websiteUrl": "",
"privacyUrl": "",
"termsOfUseUrl": "",
"mpnId": ""
}


```
