### ISSUE TITLE
Isolated webpart IFrame overlaps with other page elements and webparts

### ISSUE THREAD

**Issue by NaveenK-J** [SharePoint/sp-dev-docs#6158]
## Category

- [x] Bug

## Describe the bug

Isolated webpart's IFrame container never resizes and gets rendered in a fixed height (157px) parent div element, as a result when the data within isolated webpart grows, it starts overlapping with other page elements. If isolated webpart has custom properties then updating values in one of the custom properties in the property panel sometimes updates the parent div's height according to the height of the isolated webpart, which either leaves an empty space if the data within webpart shrinks or will start overlapping again if the data grows beyond the updated height which was set during last property update.

## Steps to reproduce

1. Deploy an Isolated webpart to a modern site collection
2. Add isolated webpart to a modern page

## Expected behavior

Webpart is added to the page without overlapping with other page elements (e.g. comments box and footer)

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Your Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8/v10
- **Browser(s)**: Chrome v84, Edge, Chromium Edge
- **Tooling**: VS Code, SPFx v1.10.0
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

Please refer attached screenshots

![IsolatedWebpart_Error1](https://user-images.githubusercontent.com/32855769/89820661-38f1a700-db02-11ea-913e-0e4804bfc67c.PNG)
![IsolatedWebpart_Error3](https://user-images.githubusercontent.com/32855769/89820665-3a22d400-db02-11ea-9bcd-0ffa6e9d8c6a.PNG)
![IsolatedWebpart_Error](https://user-images.githubusercontent.com/32855769/89820666-3abb6a80-db02-11ea-956c-68ac5a680b52.PNG)
![IsolatedWebpart_Error2](https://user-images.githubusercontent.com/32855769/89820671-3b540100-db02-11ea-924e-00f510acac1b.PNG)

**Comment by patmill** [comment]
Thanks - we're seeing this and working on a solution.

**Comment by patmill** [comment]
Sorry - lost track of this.  This should have been addressed a while ago.
