### ISSUE TITLE
toLocaleDateString() not working in JSON list view formatting

### ISSUE THREAD

**Issue by JoeAyre** [SharePoint/sp-dev-docs#6159]
It appears that the toLocaleDateString() function only works in JSON column formatting and not in JSON list view formatting. Is this expected?

**Comment by thechriskent** [comment]
I'm not seeing this issue currently:

Column Formatting:
![toLocaleDateString working in Column Formatting](https://user-images.githubusercontent.com/8364109/89910594-6dc33400-dbbe-11ea-873f-e9b62e902a95.png)

View Formatting:
![toLocaleDateString working in View Formatting](https://user-images.githubusercontent.com/8364109/89910639-7a478c80-dbbe-11ea-817b-d3857c91f2b2.png)

Could you elaborate on your use case or provide a sample of your format? Thanks!

**Comment by JoeAyre** [comment]
Sure. I'm in Australia and the library I am working with is in a SharePoint site that has the following regional settings:

![image](https://user-images.githubusercontent.com/36215002/89975117-434da580-dca8-11ea-8cca-d129ba008c7c.png)

I am using list view formatting and have the following line to display the last modified person's name and when a document was last modified. The line of JSON is as follows:

`"txtContent": "='Last modified by ' + [$Editor.title] + ', ' + toLocaleDateString([$Modified])",`

The example document I am using was last modified on August 10, 2020 but using the JSON above, the display is as follows:

![image](https://user-images.githubusercontent.com/36215002/89975378-eb636e80-dca8-11ea-930f-6f01ccfa8279.png)

If I create a calculated column (called ModifiedDDMMYYYY) to format the 'Modified' column as text and use the following JSON:

`"txtContent": "='Last modified by ' + [$Editor.title] + ', ' + [$ModifiedDDMMYYYY]",`

....I get the following displayed:

![image](https://user-images.githubusercontent.com/36215002/89975461-249bde80-dca9-11ea-93c7-380c0c3f80a4.png)

My question is, why doesn't the toLocaleDateString() function have the desired effect i.e. displaying the date in DD/MM/YYYY format?

If you need any more details let me know. And thanks for being so quick to respond!

**Comment by kikogerde** [comment]
Same issue here - toLocaleDateString() does not seem to adopt the correct date/time format set for the site/list

**Comment by shagra-ms** [comment]
@kikogerde Do you mind sharing the output of `window.navigator.languages` in your console?

`toLocaleString`, `toLocaleTimeString` and `toLocaleDateString` currently relies on the browser's locale settings, which may be different from Site/User locale settings. I will have a look at this.

I will recommend you to try [.displayValue property](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#displayvalue) for Date Fields, which will get the value based on the field settings.

**Comment by shagra-ms** [comment]
@JoeAyre @kikogerde This is not fixed, and shall be available on your tenants in upcoming updates.

**Comment by shagra-ms** [comment]
@JoeAyre @kikogerde @thechriskent I will recommend using [.displayValue property](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#displayvalue) in case you intend to maintain the default display text for Date fields. It's much easier to use and works with 'friendly format'.

**Comment by shagra-ms** [comment]
The fix is rolled out. Closing this.
