### ISSUE TITLE
Search Results webpart not working with longer query filters

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#6160]
## Category

- [x] Bug

## Describe the bug
We have a search query which filters our news based on current user's profile properties. Our query is bit longer with length of 1,409 characters, but this is within the limit in the modern search webpart query template.

## Steps to reproduce
1. Create a query which filters based on current user's profile properties such as department, region, country and additional country, site name and also different news category topics.  
2. If the all the news category topics (we have 20 topics selected), then the webpart starts failing with above given error.

## Expected behavior
We expect that the webpart works in the tenant whatever the selected number of properties are for the filtering. 

## Environment details (*development & target environment*)
- development environment
- Sharepoint online

**Comment by andrewconnell** [comment]
This looks like a question related to the OOTB features of SPO... if this is a developer question, please resubmit with details on the custom API/code you're working with. Thanks!
