### ISSUE TITLE
.Net Standard Authentication not working with users with Multi-Factor Authentication

### ISSUE THREAD

**Issue by ajhosek** [SharePoint/sp-dev-docs#6162]
Following the docs for [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard#using-modern-authentication-with-csom-for-net-standard), I have had success with accounts without multi-factor authentication, but none without. 

When trying an account that has Multi-Factor Authentication enabled and looking at the JSON that is returned from trying to Acquire a Token:

- If I use my regular password I get the error "interaction_required" with the description "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access."

- If I use with an App Password I get the error "invalid_grant" with the description "Error validating credentials due to invalid username or password."

Am I doing something wrong here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .Net Standard instead of CSOM for .Net Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
@ajhosek 

I tested to create App Password  from this link:

[App Password](https://account.activedirectory.windowsazure.com/AppPasswords.aspx)

And then use the csom code below to connect to SharePoint Online successfully:

```
            string userName = "user@tenant.onmicrosoft.com";
            string apppassword = "********";
            var securePassword = new SecureString();
            foreach (char c in apppassword)
            {
                securePassword.AppendChar(c);
            }
            using (var ctx = new ClientContext("https://tenant.sharepoint.com/"))
            {
                ctx.Credentials = new Microsoft.SharePoint.Client.SharePointOnlineCredentials(userName, securePassword);
                Web web = ctx.Web;
                ctx.Load(web);
                ctx.ExecuteQuery();
	    }
```

Another option is SharePointPnPCoreOnline assembly,  this will pop up a login dialogue and make it available to use MFA Authentication:

```
static void Main(string[] args)  
{  
   string siteUrl = "https://<tenant-name>.sharepoint.com/sites/contosoteam";  
   var authManager = new OfficeDevPnP.Core.AuthenticationManager();  
   // This method calls a pop up window with the login page and it also prompts  
   // for the multi factor authentication code.  
   ClientContext ctx = authManager.GetWebLoginClientContext(siteUrl);  
   // The obtained ClientContext object can be used to connect to the SharePoint site.  
   Web web = ctx.Web;  
   ctx.Load(web, w => w.Title);  
   ctx.ExecuteQuery();  
   Console.WriteLine("You have connected to {0} site, with Multi Factor Authentication enabled!!", web.Title);  
}   
```
Reference:

[Using CSOM To Connect To A SharePoint Site With Multi Factor Authentication Enabled](https://www.c-sharpcorner.com/blogs/using-csom-to-connect-to-a-sharepoint-site-with-multi-factor-authentication-enabled)

**Comment by ajhosek** [comment]
Sorry, maybe I should clarify.

I am targeting .NETCore 3.1.4, trying to move over a an application that was on .NET Framework 4.7.2 since Microsoft.SharePointOnline.CSOM is now supported with .NET Standard. One of the results was that they got rid of the SharePointOnlineCredentials class and connecting now is done through Azure AD with an app registration and acquiring a token. 

My problem is that MFA is enabled on an account I can't retrieve a token to gain access and connect.

**Comment by Jerry0527** [comment]
With .NET Core Solution, I can reproduce the issue in the original question.
It seems that currently, .NET Core CSOM isn't compatible with MFA.
I suggest you can now switch to normal .NET Framework if you want to use MFA.
You can submit a UserVoice here to Microsoft so that in the future .NET Core CSOM can support MFA:
[https://sharepoint.uservoice.com/](https://sharepoint.uservoice.com/)

**Comment by ajhosek** [comment]
Thanks.

I opened up a [user voice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/41139859-add-mfa-support-for-net-standard-csom) on the link you provided.

**Comment by Jerry0527** [comment]
You are welcome :)
