### ISSUE TITLE
How to display images in SPFX Application Customizer Extensions 

### ISSUE THREAD

**Issue by yahookevin** [SharePoint/sp-dev-docs#6163]
## Category

- [V ] Question

## Question

How can i reference and display images in SPFX Application Customizer Extensions. I have tried the approach similar to SPFx Webparts where we update the gulpfile.js and reference the image from the assets folder. But this doesn't seem to work with Extensions.
Can anyone please help? 

## Environment details (*development & target environment*)
SharePoint Online.

- **Your Developer Environment**:Windows 10 
- **Target Environment**:  SharePoint Online
- **Browser(s)**: [e.g. Chrome v84

**Comment by kongmengfei** [comment]
Hi yahookevin,

I tried following code to reference a local image and it works well here. You may take a reference:

`const logo: any = require('../../../assets/1.jpg');
....
 <img src="${logo}" alt="surf logo" />
`
Test Result: 

![image](https://user-images.githubusercontent.com/57654821/90474664-610f8480-e158-11ea-97dc-0c8a8342bb2d.png)

Test demo:

- https://github.com/kongmengfei/SharedSPFx/blob/master/iamgeExten/src/extensions/imageExten/ImageExtenApplicationCustomizer.ts

More reference:

- https://stackoverflow.com/questions/58975471/spfx-webpart-referencing-images-in-html

Baker Kong
Microsoft SharePoint Community Support

**Comment by yahookevin** [comment]
thanks a lot @kongmengfei I made use of your code to get it working. Probably might have been issue with my render method.
