### ISSUE TITLE
Dialog is not loading on loading the debug script

### ISSUE THREAD

**Issue by saumya-goel** [SharePoint/sp-dev-docs#6167]
below in my package.json file used in the project. Still dialog is not loading on loading the debug script. I am using Sharepoint 2019 onprem environment for this project.

{
  "name": "new-app-ext",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Unfortunately, there's not enough detail to help... the project's **package.json** helps, but without seeing the code or how you're loading the extension in the browser with the debug URL, it's hard to help...

**Comment by patmill** [comment]
Are you still seeing issues here?  If you are, can you paste the query string that you are using?
