### ISSUE TITLE
Manifest not found for component id - sp-loader-assembly

### ISSUE THREAD

**Issue by arafhossain** [SharePoint/sp-dev-docs#6170]
## Category

- [x] Bug

## Describe the bug

After installing @microsoft/sp-dialog and @microsoft/sp-property-pane via NPM into my project, running Gulp Serve will sometimes fail to load the whole workbench and will display a blank page. Sometimes Gulp loads the workbench and the webpart, but after a random amount of time it will fail to display the page/workbench on the next Gulp Reload. Uninstalling these packages from project will erase the errors and the workbench will display fine.

## Steps to reproduce

I have a project with the following dependencies:
![image](https://user-images.githubusercontent.com/17367761/90276626-d9f5a000-de29-11ea-9a49-949f5abb205e.png)

Then npm install @microsoft/sp-dialog and npm install @microsoft/sp-property-pane.
I see these errors:
Shot 1:
![image](https://user-images.githubusercontent.com/17367761/90276708-f7c30500-de29-11ea-9f54-5a20a3798aff.png)
Shot 2:
![image](https://user-images.githubusercontent.com/17367761/90276723-feea1300-de29-11ea-996c-9921a689f99a.png)
Shot 3:
![image](https://user-images.githubusercontent.com/17367761/90276742-04dff400-de2a-11ea-8d8f-db355a72d027.png)

Originally was facing on Mac OS machine. Restarted project on Windows machine and faced same issue.

## Expected behavior

I expect to be able to load my workbench and have the sharepoint site with my webpart displaying.

## Environment details (*development & target environment*)

Node version: 8.17.0
Dev Environment: Windows 10 & MacOS 10.15.5
Target: Sharepoint Online
Browser: Chrome 84 Browser and Brave Browser
Gulp CLI version 2.3.0
Tooling: Visual Studio Code

### Additional context

1. This used to not be a problem. My workbench would be working fine WITH the installed packages, then after a reload on the gulp server, it would bug out with these errors. There's no indication on what changed that would cause it to bug out. I then did a clean install again of the repo, reinstalled the packages, then it worked fine for a half hour - then after a gulp reload I was faced with these errors again.
2. If I uninstall the two packages, everything works fine - no errors - but I need the packages to further develop.

**Comment by andrewconnell** [comment]
You've go conflicting versions... All SPFx packages are 1.9.1 but you added the dialog package as 1.10. You can't mix versions... try uninstalling the sp-dialog package & installing the correct version that matches the rest of the project.

I'd also delete your package lock file & **node_modules** folder followed by a clean **npm install** as you might have mixed versions in dependencies.
