### ISSUE TITLE
Linked: Modern list no longer navigates to customised classic new/edit/display list forms

### ISSUE THREAD

**Issue by phillipharding** [SharePoint/sp-dev-docs#6171]
Linking back to #6157 _(Modern list no longer navigates to customised classic new/edit/display list forms)_ as I don't believe the issue received an answer.

## Category

- [x] Bug

## Describe the bug

On a modern list that has customised (classic) new/edit/display list form pages, clicking New or clicking the Title column value or selecting Edit does not load the customised list form page, instead it opens the details panel.

Previously the customised (classic) list form page was opened instead.
This happens whether the list view has a custom JSON formatter applied or not.

If the list view has a custom JSON format applied, the ```defaultClick``` and ```editProps``` actions of ```customRowAction``` used to navigate to the (classic) customised list forms, now they just open the details panel instead.

## Steps to reproduce

1. Create a new modern list
2. The list properties for New/Edit & Display form pages are left as standard OOTB
2. Customise the standard New/Edit/Display list form pages by editing the page(s) and adding 1 or more webparts

## Expected behavior

1. Click New from the command bar should open the customised (classic) New form page
2. Select an item and choose Edit should open the customised (classic) Edit form page
3. Select an item and click on the Title column value should open the customised (classic) Display form page

## Environment details (*development & target environment*)

- Your Developer Environment: Windows 10 & MacOS
- Target Environment: SharePoint Online
- Browser(s): Chrome, IE 11, Edge, Chromium Edge, Safari

**Comment by andrewconnell** [comment]
Let me reopen the referenced issue as it appears the bot closed it too fast due to the labels...
