### ISSUE TITLE
This Page is Bullshit the Modernisation framework does not work on SharePoint 2019

### ISSUE THREAD

**Issue by JasonMichaelRobertson** [SharePoint/sp-dev-docs#6173]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c9c192-eb6e-5c54-f03f-7f66d43f92e6
* Version Independent ID: 328da4aa-fa66-0491-6a8d-94189f14e060
* Content: [Transform classic pages to modern pages](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages)
* Content Source: [docs/transform/modernize-userinterface-site-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Closing due to inappropriate language

**Comment by jansenbe** [comment]
@JasonMichaelRobertson : page transformation can read SP2019 pages and create modern pages for them in SharePoint Online. Transforming classic SP2019 pages to modern pages in SP2019 is indeed not supported.
