### ISSUE TITLE
Extension Development In SharePoint 2019 Server Meet Problems

### ISSUE THREAD

**Issue by tntboneman** [SharePoint/sp-dev-docs#6174]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> * I've generated a basic appliction customizer with the guide of offical document (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension) ,but the code cannot work in my enviroment, no matter live develop or add it to sharepoint apps.
> * when I'm in live develop ,the javascript function can work .like console/alert ,but use microsoft library function ,they all fails and bring errors.
Uncaught Error: No callbackHandler found.
    at Function.e._sendMessage (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at Function.e.sendPageLoaded (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at t._onPostMessageLoading (sp-pages-assembly.js?uniqueId=2g4QD:119)
    at t._onPostMessage (sp-pages-assembly.js?uniqueId=2g4QD:119))
> * when I upload it to sharepoint ,the page will also bring error and the javascripts will not appear(they can appear in live develop)
> * I tried to change SPFx/Node/@microsoft/generator-sharepoint version but they were all failed
> * is it really useful the extension function in sharepoint server 2019 ,the webpart I tried is useful but the extension is not
> * the project I developing will deploy in a enviroment which has no web , will it affect the function too?
> * sharepoint server 2019 was created by azure version

## Environment details (*development & target environment*)

- **Your Developer Environment**: [ Windows 10 ]
- **Target Environment**: [ SharePoint Server 2019 ]
- **Framework**: [ Node.js v10 ]
- **Browser(s)**: [ Chrome v84 | IE v11 | Edge]
- **Tooling**: [ VS Code | SPFx v1.4.1 | @microsoft/generator-sharepoint@1.11.0 ]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by andrewconnell** [comment]
Sorry, but it's unclear what the issue is or what the specific problem is you're having. Can you share code / provide a repro as without that, there's not much to go off of ...

**Comment by tntboneman** [comment]
> * Ok, this is my code(https://github.com/tntboneman/testSPFXExtension), please verify it on sharepoint server 2019, thanks.

**Comment by andrewconnell** [comment]
I don't have an SP2019 environment so tested in SPO... works fine for me.

Do you see any errors in the browser console? By chance, are there certificate errors listed?

**Comment by tntboneman** [comment]
* >Yes, there are quite a lot errors in browser console.

![QQ截图20200828104542](https://user-images.githubusercontent.com/69451164/91515429-bd726100-e91b-11ea-8c6a-70cc4abe246b.jpg)
![QQ截图20200828104432](https://user-images.githubusercontent.com/69451164/91515491-e561c480-e91b-11ea-8d5b-fdd22ca7360a.jpg)
* >after a series of tests, I found only spfx 1.4.1 can use in my enviroment(sharepoint server 2019 on premise), any higher or lower version has no effect.
* >the typescript version should higher than 3.6.4, typescript dependencies in package.lock.json should all be the same version(remove node_modules, manual modify package.lock.json, reinstall node_modules).
* >if use @pnp/sp, 1.3.X version seems all right but some function like copy file will fail, the 2.0.4 version may be a better choice.
* >after these changes, I can see my extension items show in page(button and dialog), even still with some errors I think it's a correct way

**Comment by andrewconnell** [comment]
@tntboneman said:
> after a series of tests, I found only spfx 1.4.1 can use in my enviroment(sharepoint server 2019 on premise), any higher or lower version has no effect.

That's correct... SPFx v1.4.1 is what's included on SP2019... that version is pinned so you must use that version.

@tntboneman said:
> manual modify package.lock.json

You should never do this... if anything, delete **node_modules** & the lock file, then run **npm install** and let NPM manage the lock file creation. Don't ever hand-edit this.

As for the connection errors, did you trust the dev cert as part of your local development workstation setup as the docs state?

**Comment by tntboneman** [comment]
@andrewconnell said:
* >As for the connection errors, did you trust the dev cert as part of your local development workstation setup as the docs state?

Yes, I ran the command 'gulp trust-dev-cert'.

Why I manual modify package.lock.json because I use pnpjs(https://pnp.github.io/pnpjs/SPFx-on-premises/).
I can run most logic (open dialog/choose templdate page) but get trouble in copy page now.
pnpjs throw a error:
```js
Uncaught (in promise) TypeError: Cannot read property 'zoneEmphasis' of undefined
    at Proxy._ClientsidePage.mergeColumnToTree (localhost:4321/dist/command-set-list-command-set.js:10618)
    at Proxy._ClientsidePage.setControls (localhost:4321/dist/command-set-list-command-set.js:10498)
    at Proxy._ClientsidePage.fromJSON (localhost:4321/dist/command-set-list-command-set.js:10088)
    at Proxy.<anonymous> (localhost:4321/dist/command-set-list-command-set.js:10106)
    at step (localhost:4321/dist/command-set-list-command-set.js:813)
    at Object.next (localhost:4321/dist/command-set-list-command-set.js:794)
    at fulfilled (localhost:4321/dist/command-set-list-command-set.js:784)
```
perhaps this is no matter with @microsoft/sp

**Comment by andrewconnell** [comment]
OK... now you're talking about a specific challenge you're facing with PnPJS. For that, you should direct questions to their repo: https://github.com/pnp/pnpjs

**Comment by tntboneman** [comment]
Thank you andrewconnell.
