### ISSUE TITLE
Incorrect Extension Manifest JSON Schema

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#618]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The [ExtensionName]ApplicationCustomizer.manifest.json's schema should point to the client side extension manifest schema JSON file.

The value should actually be "$schema": "../../../node_modules/@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/client-side-extension-manifest.schema.json"

#### Observed Behavior
The default value is not resolving (incorrect relative path) and is still pointed at the clientSideComponentManifestSchema.json

The schema files have also switched to using hyphens instead of camel casing. This may not be a bug but could cause issues for previous webpart manifest files.

#### Steps to Reproduce
Generate a new ApplicationCustomizer extension with the Yeoman Generator and open the src/extensions/[extensionName]/[ExtensionName]ApplicationCustomizer.manifest.json in VSCode and you'll see the squiggly line and a message about it not resolving correctly.

**Comment by waldekmastykarz** [comment]
Worth noting: this also results in a build error if you try to run the `gulp bundle` command.

**Comment by mjimison** [comment]
@thechriskent I noticed this as well, but I found the below to be the full correct path (perhaps yours got trimmed in copy/paste?)

"$schema": "../../../node_modules/@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/client-side-extension-manifest.schema.json"

**Comment by mjimison** [comment]
@thechriskent I noticed this as well, and I was about to say I had to use a different path to make it work, but then I realized that part of my text was getting stripped when I copied it, just likes yours, and so I've added the below in code format, so that the entire value can be seen.

Cheers,
Matt

`"$schema": "../../../node_modules/@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/client-side-extension-manifest.schema.json"`

**Comment by mjimison** [comment]
I wrote up a quick blog post summarizing the issue. Even after pointing to the correct schema, you'll then technically have a violation on the use of '*' to indicate the version comes from package.json. Perhaps the schema within the framework should be updated to account for this value, to suppress the warning.
[SharePoint Framwork Extensions Developer Preview Schema issue](http://mattjimison.com/2017/06/09/sharepoint-framework-extensions-developer-preview-schema-issue/)
