### ISSUE TITLE
Dynamic Properties are not laoding after deployment - In Work Bench, its working fine.

### ISSUE THREAD

**Issue by PrashanthReddy7** [SharePoint/sp-dev-docs#6182]
## Category

- [x] Bug

## Describe the bug

Dynamic properties are not loading after deployment, but the same is working in WorkBench.
In Work Bench
![InWorkBench](https://user-images.githubusercontent.com/63856494/90539923-c4151180-e180-11ea-8877-e1aeaddd97b3.jpg)

After Deployment
![AfterDeployment](https://user-images.githubusercontent.com/63856494/90539926-c4ada800-e180-11ea-8eaa-6335eff7e38c.jpg)

## Steps to reproduce

1. Created Dynamics data flow webpart
2. During the test run, its working and configurable
3. Same not working after deployment.
4. Connect source - properties are not loading

## Expected behavior

The same work bench should be shown

## Environment details (*development & target environment*)

-Windows10
- SharePoint Online]
- Node.js v10.21.0
- Chrome v84 and IE v11 
- VS Code | SPFx v1.11.0 

*Thanks for your contribution! Sharing is caring.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

**Comment by andrewconnell** [comment]
Unclear... what properties aren't loading and loading from where?

By chance did you delete the web part that you've deployed (non-workbench) and added it back to the page? 

If you're saying "the properties in the `preconfiguredEntries` section of the web part manifest file aren't loading, those are only used when the web part is first added to the page. When the web part is added to the page, those are the default values set on the public properties on the web part. After that, the values in the web part manifest file's `preconfiguredEntries` aren't used.

**Comment by PrashanthReddy7** [comment]
Hi @andrewconnell ,
Sorry for the confusion:
Actually I have created two webparts (Navigator & Page Viewer)
For Dynamic Data Flow:
**Source** : Navigator , on selection send page title to page viewer webpart
**Target** : Page viewer, it will be shown the page based on input from Navigator webpart
**Dynamic Property**: Wiki Page is a property to expose data from navigator to page viewer.

While configuring dynamic property in target web part, I cant see that in connect source.
The same is working fine with workbench.

For delete webpart : now I create new page added the source & target webpart , still the same issue.

preconfiguredEntries sections as follows:

**Source, Navugation webpart:**
![Source Pre configured entries](https://user-images.githubusercontent.com/63856494/90791307-53e5c780-e309-11ea-9a9c-eda8d9c96989.png)
**Target:**

![Traget- Pageviewer](https://user-images.githubusercontent.com/63856494/90791303-534d3100-e309-11ea-8b7e-5d7161f37c98.png)

**Comment by andrewconnell** [comment]
I'm sorry... I'm still not clear... can you provide a repro? A link to a video reproducing the error?

**Comment by PrashanthReddy7** [comment]
Sorry again :(
Please find the repos here..
https://github.com/PrashanthReddy7/Tree-View-Navigation.git

**Comment by PrashanthReddy7** [comment]
Hi @andrewconnell ,

Can you please let me know if any further information requires.
I am trying but still not getting succeed :(

**Comment by patmill** [comment]
Your producer webpart looks somewhat different in the normal page vs. the workbench.  Can you make sure that your 'initializeSource' code is getting executed and isn't throwing an exception?
