### ISSUE TITLE
It is not possible to debug SPFx projects in Visual Studio Codespaces using only a browser

### ISSUE THREAD

**Issue by sebastianrogers** [SharePoint/sp-dev-docs#6184]
See issue #6165 which has been closed in error as the proposed solution only works from a desktop copy of VS Code and not a browser based copy

## Category

- [x] Bug

## Describe the bug

I have tried creating a new v1.11 web part project in my Codespace, which all works fine, I can gulp serve successfully, I've set up Port Forwarding for 4321, 5432 and 35729, but the workbenches fail to load.

I haven't had any luck with https even after exporting and installing the dev certificate, but disabling https in serve.json at least allows content to be served from localhost:4321 via port forwarding at https://[guid]-4321.app.online.visualstudio.com/. Navigating to /temp/workbench.html loads the file, but nothing displays as the page tries to load scripts etc from localhost:4321, not the port forwarding URL.

Attempting to use the hosted workbench at https://[domain].sharepoint.com/_layouts/15/workbench.aspx?debug=true&noredir=true&debugManifestsFile=https://[guid]-4321.app.online.visualstudio.com/temp/manifests.js also fails: TypeError: Cannot read property 'getManifests' of undefined, again because the manifests.js it loads, references content at localhost:4321 instead of the port forwarding URL. I've tried setting "hostname":"[guid]-4321.app.online.visualstudio.com" in my serve.json but this just causes gulp serve to fail: Error: listen EADDRNOTAVAIL: address not available.

There is a blog article claiming that SPFx in Codespaces should work except:

I used a local install of VSCode instead of the browser.

## Steps to reproduce

See above

## Expected behavior

See above

## Environment details (*development & target environment*)

Your Developer Environment: Windows 10
Target Environment: SharePoint Online
Framework: Node.js v10
Browser(s): Chrome v84/Chromium Edge v83
Tooling: Visual Studio Codespaces (Cloud-hosted codespace, no VS Code installed locally)

**Comment by andrewconnell** [comment]
I'll reopen the referenced issue to keep the thread consolidated...
