### ISSUE TITLE
Text not selectable in box format

### ISSUE THREAD

**Issue by cledramatt** [SharePoint/sp-dev-docs#6188]
Hello 

I've done some of the examples on this page, when doing a box format on a list it means the text inside the box can't be selected. I can't find any information to get around this, I have users that still need to be able to select text with in the formatted area, the same as you normally would on a list. Do you have any tips for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
@cledramatt Can you clarify more on what you are trying to do here? A JSON sample for the referred 'box format' would be helpful.

Regarding text selection - there isn't any existing ways to enable text selection on a formatted column/row/tile. This is a known limitation. 
Would like to understand the steps users take to do the same on a non-formatted area. Can you please share more info here?
