### ISSUE TITLE
Setup Global Properties for SPFX webpart on whole tenant.

### ISSUE THREAD

**Issue by enti333** [SharePoint/sp-dev-docs#6189]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hello.
I am preparing SPFX webpart. This webpart can be used on many site collections on tenat. But I need to prepare for this webpart some global tenant settings. So if some user use the webpart the webpart will read properties not from current site collection or from current webpart properties but from such a Global SharePoint Online\tenant settings.
So I need to store\create some properties on tenat level which can for example read only tenant administrator or can be readed by GraphApi level. For example in old sharepoint we have something like Property bag but this can be used only on sharepoint site collection level but I need something on upper level...on tenat level...Is possible something like this?
Thank you.

## Environment details (*development & target environment*)

SPFX 1.X  - SPFX 1.11
It is not important to have details about enviroment because it is global question...

**Comment by andrewconnell** [comment]
Yup... see: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties

@enti333 said
> It is not important to have details about enviroment because it is global question...

Actually it is, because the answer is different if you are talking SharePoint Online / SharePoint on-prem. The above link only refers to SPO. There is no OOTB solution for SP on-prem.

**Comment by enti333** [comment]
Thank you very for your answer @andrewconnell. Yes you are right it is important to know that this is s SharePoint Online. Sorry for that. The main problem is that we are not able to SET these properties by RestApi or GraphApi...So I am not able to prepare some nice interface for admin in SPFX...Maybe CSOM? Hmm....Thank you for some anothe hint....
