### ISSUE TITLE
Where is the documentation on what is included in sp-lodash-subset?

### ISSUE THREAD

**Issue by dylancristy** [SharePoint/sp-dev-docs#6191]
## Category

- [x] Question
- [ ] Typo
- [x] Additional article idea

## Question

While I have seen many times over that "sp-lodash-subset is a subset of lodash functions", I haven't been able to find anywhere a list of _exactly which functions are included_.

This page is blank: https://docs.microsoft.com/en-us/javascript/api/sp-lodash-subset

This page does not have any details either: https://www.npmjs.com/package/@microsoft/sp-lodash-subset

The only reference to it I can find in the main SPFx documentation is on the [Toolchain page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/sharepoint-framework-toolchain), where it just says, again:

> Provides a custom bundle of lodash for use with the SharePoint Framework's module loader. To improve runtime performance, it only includes a subset of the most essential lodash functions.

But still no reference to which functions are included.

Even if the "documentation" is just a link back to the documentation on the lodash website, I think a definitive list of exactly which functions are included would be incredibly helpful.

(Currently the only way I know of to see what's included is doing "exploration via Intellisense" in a named `import` line, which is....annoying.  And inefficient.)

**Comment by andrewconnell** [comment]
There's a known issue with the API doc generation on the site... they are working on that.

But the easiest and best way to see what's there is to look in the **/node_modules/@Microsoft/sp-lodash-subset** to see what's functions are listed there, specifically the **index.d.ts** file.

![image](https://user-images.githubusercontent.com/2068657/91297917-1fd92f00-e76d-11ea-97a2-71c38071a3ea.png)

To see what each one does, refer to the lodash docs: https://lodash.com/docs/

**Comment by dylancristy** [comment]
Ah, I did not know they were listed out like that in that file.  Thanks!.

**Comment by andrewconnell** [comment]
![](https://media.giphy.com/media/1k4UUaabLlDsBXQtXI/giphy.gif)
