### ISSUE TITLE
Web parts not rendered when page created using template on communication site

### ISSUE THREAD

**Issue by campsa** [SharePoint/sp-dev-docs#6192]
## Category

- [x] Bug

## Expected or Desired Behaviour

When creating a page from a custom page template, the page should render all the web parts in the template.

## Observed Behaviour

Intermittently, web parts are not rendered when creating a page from a page template, especially within a vertical section.  All the web parts from the template are included, but not rendered.  

![image](https://user-images.githubusercontent.com/9635259/90867561-7b7e7380-e38d-11ea-916e-7a2cca2f8d93.png)

Generally these are page templates with 10+ web parts - inspecting shows all the webparts are there but not rendered.
![image](https://user-images.githubusercontent.com/9635259/90867848-e9c33600-e38d-11ea-9698-2035d2ab256c.png)

It seems to happen if the template has many web parts, a vertical section and if the Create page button is clicked before the template has fully rendered in the Page template picker panel.  It also seems to happen the first time using the template - the template is possibly cached after creation/use? 

## Steps to reproduce

1. On a communication site, create a page template including multiple web parts in a vertical section as well as in the main sections
1. Go to the home page of the site you created the template in - clear the cache
1. Click New -> Page
1. Select the new template and QUICKLY click Create page before the template fully renders in preview
1. The page will be created but the web parts in the vertical section won't have rendered.  Those in the main sections will render.
1. If you create another page from the template again, it should work fine 
1. After sometime, coming back to the site and using the template, the same issue occurs

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**: [e.g. Chrome v84 | Chromium Edge v84]

**Comment by andrewconnell** [comment]
This looks like it's more of an issue with an OOTB capability than a developer topic... which means you should post this to a TechCommunity forum as there's not much we can do in this developer forum.
