### ISSUE TITLE
Question regarding publishing of SPFx solutions to AppSource

### ISSUE THREAD

**Issue by DaveHaasPowderSoftware** [SharePoint/sp-dev-docs#6195]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

This reference document says that **only** solutions using 1.11 of the SPFx framework can be published to AppSource ...

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist

However, SP2016 On-Prem solutions require SPFx version 1.1 and SP2019 On-Prem solutions require SPFx version 1.4.

I read that and conclude that it is not possible to publish solutions to AppSource that are intended to be deployed to 2016 and 2019 on premises installations.

Is that assessment correct?

Regards,

Dave

**Comment by VesaJuvonen** [comment]
This is correct. We currently only support SharePoint Online as the target for SharePoint Framework solutions in marketplace.

**Comment by DaveHaasPowderSoftware** [comment]
Thanks Vesa.

So that means we have to deploy to 2019 On-Prem and 2016 On-Prem using .sppkg's then, the same way that a regular Add-In would have been deployed? Basically, we have to ship the .sppkg to the customer directly ...

I'm assuming that's the case, just making sure.

Cheers,
