### ISSUE TITLE
[Docs] Clarify which versions of SPFx can consume Azure AD secured APIs

### ISSUE THREAD

**Issue by semopz** [SharePoint/sp-dev-docs#6202]
The article does not have an "applies to" section. SPFx version 1.4.1 is mentioned which could suggest that the article also applies to SharePoint 2019 which I don't think is the case (no way to authorize the webApiPermissionRequests on-prem).

Could we have a note explicitly stating whether or not Azure AD secured APIs can be consumed from SharePoint on-prem? And if it is possible, to point us in the right direction.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
This is a tutorial... the official docs for the **AadHttpClient** object are here (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient) which state exactly what you're requesting.

**Comment by semopz** [comment]
The linked article doesn't explicitly answer the question "Can I consume Graph/AAD apps from SP on-prem". The article muddles the issue a bit with this note

> If you build solutions on a version of the SharePoint Framework earlier than v1.4.1, you can still connect to resources secured with Azure AD. In this case, you need to implement the OAuth implicit flow by using ADAL JS. For more information, see Connect to API secured with Azure Active Directory.

As an SP on-prem developer reading this, I would think to myself "Ah, SP 2019 supports SPFx 1.4.1 so it should work". The articles mentioned in this thread do not explicitly state that on-prem is not supported. According to @baywet 
>Even though it is not clearly stated in the documentation at this point, the ability to connect (and have authentication and authorization) automatically to AAD secured APIs (including the Microsoft Graph) is limited to SharePoint online only.
This is because SharePoint Online registers AAD applications, declares and approves the permissions/scopes behind the scenes, this is something SharePoint on prem (2016 or 2019) can't do today.
- https://sharepoint.stackexchange.com/a/263502

Now this is clear as rain and would be really helpful information to be part of the official MS docs. It would help justify architectural decisions (I don't have to "prove" it doesn't work if it is explicitly stated in official documentation). It would be even better if the tutorial/documentation also stated whether there are any workarounds. Is it a case that it is difficult to do from SP on-prem or that it is impossible/insecure to do so (I genuinely don't know)?

**Comment by andrewconnell** [comment]
I can say definitively: you can't use the SPFx APIs for the Microsoft Graph or Azure AD secured endpoints outside of SharePoint Online. This capability was added as [GA in SPFx v1.6.0](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.6).

What was added in [1.4.1 were developer preview APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.4.1, not supported and were replaced in 1.6.0 as the release notes state. 

If you want to consume Azure AD-secured APIs from SP 2019, you'll need to do it *without* the SPFx APIs provided. It's possible using the OAuth implicit flow, but there's no SPFx "special sauce".

**Comment by semopz** [comment]
Thanks, that's good to know. If I understand this correctly, the MSAL v2 package should help me with this https://www.npmjs.com/package/@azure/msal-browser.

**Comment by andrewconnell** [comment]
Yes, ADAL.js & MSAL.js both support the OAuth implicit flow. MSAL is the better choice as ADAL is being retired.

Just a few more things then I'll close this issue as it's resolved. In addition to the code you'll write that leverages MSAL.js to talk to an API, you're going to need an Azure AD with the implicit flow enabled, that app will use delegated permissions to talk to the app that secures the endpoint you are wanting to talk to as well.

Refer to this MS Learn module I wrote for Microsoft that includes a unit & associated HOL that demonstrates this. It's the "Single Page App" unit & HOL exercise: https://docs.microsoft.com/en-us/learn/modules/identity-application-types/

The tech is the same, but it's not the exact same thing you're trying to do... but it should put you on the right track.
