### ISSUE TITLE
Graph Termstore API: GetAllTerms and GetSiteCollectionGroup

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#6204]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hello everyone,
the Graph Termstore API was announced, but apparently important components are still missing despite 3 years of development. 

Furthermore the documentation for using this in SharePoint directly is missing completely using the REST API (`_api/v2.1/termStore/`).

I could not find a replacement for the following endpoints in the documentation:

- [TermSet.GetAllTerms](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termset.getallterms?view=sharepoint-server): This call is important for performance reasons. We don't won't to make multiple calls to get child terms.
- [TermStore.GetSiteCollectionGroup](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termstore.getsitecollectiongroup?view=sharepoint-server): There seems now way to get the Site Collection Termgroup at all currently? My expectation would have been something like `/termStore/groups/SiteCollectionGroup/{siteId}` but the documentation does not State anything comparable. Even calling the site collection group using its ID with `https://graph.microsoft.com/beta/termStore/groups/{groupId}` fails with

```
{
    "error": {
        "code": "itemNotFound",
        "message": "Group with id 5d53ea26-23ce-4509-a514-62bbd7bd0e14 not found",
        "innerError": {
            "date": "2020-08-26T09:04:27",
            "request-id": "27781264-f9b2-4b92-afc9-1658579d316c"
        }
    }
}
```
This also would not be a valid way to load this because it is not possible to know the `SiteCollection.TermGroup.Id` from Javascript.

**Did anyone find a way to use this stuff using Graph or `_api/v2.1/termStore/`?**

We had really big hopes for this new API Endpoints because the peformance of the current Termstore API Performance in CSOM and JSOM is catastrophic. But in the current state the endpoints are useless.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: MS Graph, SharePoint Rest API
- **Browser(s)**: Chrome v84
- **Tooling**:  Graph Explorer

**Comment by andrewconnell** [comment]
This question is a Graph API question. There's no SharePoint REST API for taxonomy... it's being introduced in the MS Graph. This repo is for SharePoint development questions. Please direct your question to the Graph API forums.
