### ISSUE TITLE
Why does the Considerations say "but not Lists"?

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#6209]
In the Considerations section, there is the line:

```
you can subscribe to events from libraries (but not lists)
```

Why? This page is about subscribing to *list* notifications. If there's special meaning about the word `events` there, can this be clarified as to how this differs from list subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ade5442-a0dc-e57c-bde0-876396aba7f1
* Version Independent ID: 50aa69e3-8a27-dac1-5c60-1d5309a60a33
* Content: [Subscribe to list notifications](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications)
* Content Source: [docs/spfx/subscribe-to-list-notifications.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/subscribe-to-list-notifications.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dangerous-Mind** [comment]
You got to love when Microsoft says.

**"Subscribe to list notifications"**
then say 
**"you can subscribe to events from libraries (but not lists)"**

**Workarounds**
- Call the list every x seconds to check if it is updated (very bad for performance).
- Create a Document Library and subscribe to it.
Save a dummy file on the Document Library every time you change a item on the list. (hide the list in shame for having to use so low level trick to get things to work).

In a interactive app with 15 persons accessing three lists at the same time and pinging several lists every two seconds making 450 calls each list every minute (1.250 call total) I would use the second solution.

Any other solution would be appreciated.

**User Voice**
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/39642082-subscribe-to-list-notifications-for-lists

**Comment by Dangerous-Mind** [comment]
Third workaround. Get version 1.11. 

Get @microsoft/sp-list-subscription.
On sp-list-subscription.js line 3426
Changing the line from
this.transports = opts.transports || ['polling', 'websocket'];
to
this.transports = opts.transports || ['websocket','polling'];

This seams to be working on list's also.

**Comment by jimmywim** [comment]
*Ping*

This has been fixed in SPFX 1.12.1

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1

**Comment by jimmywim** [comment]
Re-opened accidentally.
