### ISSUE TITLE
Can the "path" ManagedProperty of SharePoint Online be used in the RefinementFilters parameter of a search query?

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#6210]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

### Short question

Can the "path" **ManagedProperty** of SharePoint Online be used in the **RefinementFilters** parameter of a search query?

#### Example
We have a "Shared Documents"-Library at the following location: `https://MyTenant.sharepoint.com/sites/MyTestSite123/Shared Documents/Forms/AllItems.aspx`

Now we want to search for this property using SharePoint search api's (e.g. Rest API: )
`https://mytenant.sharepoint.com/sites/MyTestSite123/Shared Documents/Forms/AllItems.aspx/_api/search/query?querytext='*'&refinementfilters='path:starts-with("https:%2f%2fMyTenant.sharepoint.com%2fsites%2fMyTestSite123%2fShared+Documents%2fForms%2fAllItems.aspx")'`

The problem here is that the path property does not seem to work at all:

`title:equals("shared documents")` 
**=> This works fine and finds the result**

`path:equals("https://MyTenant.sharepoint.com/sites/MyTestSite123/Shared Documents/Forms/AllItems.aspx")` 
**=> This does not find any results**

`path:equals("https%3A%2F%2Fmytenant.sharepoint.com%2Fsites%2FMyTestSite123%2FShared%20Documents%2F")` 
**=> This does not find any results**

### Long question

When using MS Graph to get the followed pages of a user graph returns the page urls:
![image](https://user-images.githubusercontent.com/31658807/91450159-476aed00-e87c-11ea-9054-bbafef149329.png)

Since we have some logic based on SharePoint pages we need to get additional search data from these pages. The problem with this is that a user can have a huge number of followed pages. Therefore when passing the PageUrl as search query parameter we get a very long query string. Since the query string is limited multiple search calls would be necessary to get all data.

An [article](https://www.techmikael.com/2020/03/searching-within-office-365-groups-or.html) and a [followup article](https://www.techmikael.com/2013/07/limiting-search-results-by-exact-time.html) by @wobba gave us the idea to prevent the need of multiple search queries by using the RefinementFilter property. This property does not have a length limit because it is using FQL:

_If you are a member of many groups, then I suggest using a POST payload instead of GET, and refinementfilters is not limited by 4k either (at the time of this writing) :)_ 

This property seems to work fine when using normal Search Management Properties like title or GroupId (as stated in wobba's article). But it does not work for the path property (see examples above).

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *Complete the following (if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission).*

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: NET Framework v4.5
- **Browser(s)**: Chrome v83
- **Tooling**: Search Query Tool

**Comment by wobba** [comment]
`path` is a bit wonky in how it works (with good reason), but you can do this as a refinement filter:

Replace spaces with %20 and add a * at the end.

`path:"https://MyTenant.sharepoint.com/sites/MyTestSite123/Shared%20Documents/Forms/AllItems.aspx*"`

For documents and folders you may also use:
`DocumentLink:"https://MyTenant.sharepoint.com/sites/MyTestSite123/Shared Documents/Mydoc.docx"`

**Comment by MrTantum** [comment]
Thank you.

DocumentLink seems to be working fine even with RefinementsFilter!

Path is not working. In my example above you can already see that I have used encoded the whole string:

path:equals("https%3A%2F%2Fmytenant.sharepoint.com%2Fsites%2FMyTestSite123%2FShared%20Documents%2F")

Furthermore your example (path:"https://MyTenant.sharepoint.com/sites/MyTestSite123/Shared%20Documents/Forms/AllItems.aspx*") is not valid FQL at all is it?

**Guys I would really appreciate it if you would stop closing threads so fast. This really makes it hard to get any discussion working at all...**

@wobba  If you are already reading this thread a comment on another closed topic (#6155): Your workaround worked fine. :)

**Comment by wobba** [comment]
@MrTantum you encoded too much....only encode the spaces, not the other characters. And it's valid fql indeed. You don't have to encapsulate it in string(), but you can 😉 And sorry for closing, but I felt the answer pretty much was spot on...I'll wait for confirmation next time and I'll reopen so you can close ☺️

**Comment by MrTantum** [comment]
Nope path is still not working.

# Test results
I did some test using search query tool.

## Pure KQL works fine (just to test we get results at all)
![image](https://user-images.githubusercontent.com/31658807/91530492-77ad9c80-e90b-11ea-8d57-d4dc2f762e66.png)

## path using FQL Refinements Filter with encoded whitespaces does not work
![image](https://user-images.githubusercontent.com/31658807/91530519-87c57c00-e90b-11ea-9947-1de1300f946c.png)

## path using FQL Refinements Filter with unencoded whitespaces does not work too
![image](https://user-images.githubusercontent.com/31658807/91530546-94e26b00-e90b-11ea-8098-ae7b7563fcc4.png)

## DocumentLink using FQL Refinements Filter with unencoded whitespaces does work
![image](https://user-images.githubusercontent.com/31658807/91530602-adeb1c00-e90b-11ea-90d9-f84d36fc951f.png)

## DocumentLink using FQL Refinements Filter with encoded whitespaces does not work
![image](https://user-images.githubusercontent.com/31658807/91530610-b0e60c80-e90b-11ea-9924-0b28f1302051.png)

# Summary
Getting DocumentLink to work is at least something. This means we can put everything in one search call when loading documents or pages (they luckily count as document too) the user is following.

But we will still need to make multiple calls when loading sites the user is following (and he has too many followed sites). :(


# Some words to the closing topic:
I know you guys are eagerly trying to reduce the huge amount of tickets in this repo. This is ok. But in the last weeks it seemed like this resulted in closing a lot of topics without leeting the creator react at least once.

One of this cases was #6155. I had recreated this by the way in the [techcommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/the-app-sharepoint-principal-is-not-resolving-in-newly-created/m-p/1595624#M9450) forum. But as expected there has been no feedback at all because developers don't seem to use this forum (and this is understandable because of the terrible performance.).

**Comment by wobba** [comment]
Could be an encoding issue if you use the query tool using GET vs POST. Works for both in the dev branch of the query tool at least when using the `path` property.

I tested with this refinement filer:
`path:"https://tenant.sharepoint.com/Delte%20dokumenter/Forms/AllItems.aspx*"`

REST query:
```
https://tenant.sharepoint.com/_api/search/query?querytext='*'&refinementfilters='path%3a%22https%3a%2f%2ftenant.sharepoint.com%2fDelte%2520dokumenter%2fForms%2fAllItems.aspx*%22'
```

As for the app@sharepoint issue, this may fall outside the scope of public forums, requiring using official/other support. As this forum deal with dev API's. I only proposed a work around because I wanted to see if there was one. If you want to figure out why it has changed, you most likely have to file a support ticket as it's not an API issue, but a technical backend issue.

**Comment by MrTantum** [comment]
Nope still not working. I tried with the query tool dev version too (master branch, as there is no dev branch [here](https://github.com/pnp/PnP-Tools/branches)):

# Post Query KQL
![image](https://user-images.githubusercontent.com/31658807/91545872-f01f5800-e921-11ea-97e6-70c2f44f8238.png)

# Post Query RefinementFilters
![image](https://user-images.githubusercontent.com/31658807/91545886-f6153900-e921-11ea-849b-8220b0f9d33f.png)

# Data from RAW Tab

POST	https://navoo.sharepoint.com/_api/search/postquery	HTTP 1.1
Request:
	Accept: application/json;odata=verbose;charset=utf-8
	Content-Type: application/json;odata=verbose;charset=utf-8
	x-requestdigest: 0xFEDD843E871CA49FA7A6F808618D1A0BDA3F121874A29BA36D036192A1A895C5F0FD55054942B4EB624C2589466E29F687661E490A51B5892D71296DC322B677,28 Aug 2020 09:28:59 -0000
	Host: navoo.sharepoint.com
	Cookie: ...
	Content-Length: 223
	Expect: 100-continue

	{'request': { 'Querytext':'*', 'SelectProperties':{'results':['Path','Url']}, 'RefinementFilters':{'results':['path:"https://navoo.sharepoint.com/Shared%20Documents/testfile1.docx"']}, 'ClientType':'ContentSearchRegular'} }

Looks like Query Tool Authentication is working much better with the new version. Looking forward to get this one as release version. 😃

**Comment by wobba** [comment]
Well.. feel free to close the issue as I have nothing more to add. FQL works - you just have to play with it :) And why not just use KQL for this scenario?

**Comment by MrTantum** [comment]
After searching through the properties the **SitePath** property seem to be a good alternative for the path (but only non-documents). 

For lists, libraries and list item it always starts with the path followed by some domain formatting:

Example List = https://navoo.sharepoint.com/ExampleList

SitePath = https://navoo.sharepoint.com/ExampleList;com.sharepoint.navoo./eimlistserviceslink/

Therefore using the RefinementFilter works like this:

SitePath=https://navoo.sharepoint.com/ExampleList*

![image](https://user-images.githubusercontent.com/31658807/91555634-ac344f00-e931-11ea-9978-3157e689bade.png)

To the Scenario:
As I mentioned above we are dealing with all items the user is following. A KQL Query would look like this:
`Path={UrlToItem1} OR Path={UrlToItem2} OR Path={UrlToItem3} OR Path={UrlToItem4} OR Path={UrlToItem5}...`

Since the querytext can only contain up to 4096 characters you will not be able to get all results using only one query. Furthermore FQL looks much cleaner:
`Path:Or({UrlToItem1},{UrlToItem2},{UrlToItem3},{UrlToItem4},{UrlToItem5})`
