### ISSUE TITLE
Fluent DetailsList refresh data

### ISSUE THREAD

**Issue by mrcpgn** [SharePoint/sp-dev-docs#6216]
## Category

- [x] Bug

## Describe the bug

I have a custom SPFx webpart built with React, containing a DetailsList component.
When I update the elements of the list through the status, the list doesn't show the updates until after a scroll.

## Steps to reproduce

I created a basic example on [codepen](https://codepen.io/Pagani/pen/QWNMNze?editors=1010)
Clicking on the button "Update first value" the first element within the state is updated, but nothing happens.
Only when scroll down the page, the change appears.

When the button is clicked, this function is executed:
`  private _changeFirstItem = (): void => {
    let temp = this.state.items;
    temp[0].value = "UPDATED";
    this.setState({ items: temp });
  }`

## Expected behavior

Items must be updated after the state update

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Framework**: React
- **Target Environment**: SharePoint Online
- **Browser(s)**: Chrome 84.0.4147.135
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by mrcpgn** [comment]
Ok, 
I resolved changing from:
private _changeFirstItem = (): void => {
    let temp = this.state.items;
    temp[0].value = "UPDATED";
    this.setState({ items: temp });
}
to:
private _changeFirstItem = (): void => {
    let temp = **[...this.state.items]**;
    temp[0].value = "UPDATED";
    this.setState({ items: temp });
  }

I didn't understand why, but it works

**Comment by andrewconnell** [comment]
This forum is for SharePoint related development topics. This is more of an issue/topic specific to the Fluent DetailList, not SharePoint. As such, the SP engineering team can't do much to influence this... so the guidance is to post Fluent issues to their appropriate repo. 

Thanks for following up on your resolution though!
