### ISSUE TITLE
navigatedEvent in SharePoint Framework Extension is triggering on same page reload

### ISSUE THREAD

**Issue by user546** [SharePoint/sp-dev-docs#6220]
## Category

- [x] Bug

## Describe the bug

> navigatedEvent in application customizer is triggering on same page reload.

## Steps to reproduce

1. Create navigatedEvent in onInit method
2. Reload same page
3. Navigated event will be triggered

## Expected behavior

> Action created for navigatedEvent should trigger only when navigated to another page from current page.

**Comment by AJIXuMuK** [comment]
@user546 do you mean you hit f5 to refresh the page? Or you click on navigation item?

**Comment by patmill** [comment]
Closing for lack of an update.  Feel free to open a new issue if you encounter a problem.  Thanks!
