### ISSUE TITLE
Vue types for 'vue/dist/vue.esm.js' not working

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6222]
## Category

- [x] Bug

## Describe the bug

When I do 

import Vue from 'vue/dist/vue.esm.js';

it says

Could not find a declaration file for module 'vue/dist/vue.esm.js'. 'c:/GitHub/D.SPScripts/SPFx/node_modules/vue/dist/vue.esm.js' implicitly has an 'any' type.
  Try `npm install @types/vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue/dist/vue.esm.js';`ts(7016)

## Steps to reproduce

1. Happens on intellisense right away

## Expected behavior

No error or warning

## Environment details (*development & target environment*)

Windows 10
SharePoint Online
Node v10
Chrome v79
VS Code | SPFx v1.10.0

**Comment by StfBauer** [comment]
Which version of VueJS are you using?

In the case of VueJS, the PnP/SPFx generator comes with a fully configured VueJS support upon project creation.
[https://pnp.github.io/generator-spfx/](https://pnp.github.io/generator-spfx/)

There are some steps needed to be taken to support VueJS in SPFx.
