### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by OlafD** [SharePoint/sp-dev-docs#6223]
Since renaming in github.io to "https://pnp.github.io/cli-microsoft365", the links to the CLI commands are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ce08da-2103-2d18-7726-08d3f329c6a1
* Version Independent ID: d085498b-8e61-1f7b-c29f-146b7653c299
* Content: [SharePoint site design - Office 365 CLI commands](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-o365cli)
* Content Source: [docs/declarative-customization/site-design-o365cli.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-o365cli.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by SmitaNachan** [comment]
Hello,
Thanks for reporting, I will raise PR to fix this.

**Comment by waldekmastykarz** [comment]
Thank you for reporting this @OlafD and sorry for the trouble. Appreciate your help @SmitaNachan
