### ISSUE TITLE
You are missing the Yoeman command in step 3.

### ISSUE THREAD

**Issue by Marker4** [SharePoint/sp-dev-docs#6227]
You are missing important information in Step 3.

You have instructions for making the project directory and changing to that project directory (Step 1 and Step 2), but you are missing the Yeoman command:
yo @microsoft/sharepoint

For someone new to this, that is an important command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7cd562-b54f-0157-2912-e8100a9dbb0b
* Version Independent ID: 6b9554bd-2d7e-d8b0-7461-c80dd89f5be8
* Content: [Tutorial - Migrating from Edit Control Block (ECB) menu item to SharePoint Framework Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions)
* Content Source: [docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Good catch... how about submitting a PR to fix this? :)
