### ISSUE TITLE
Authorization for sharepoint search in only one Site

### ISSUE THREAD

**Issue by bguivarch** [SharePoint/sp-dev-docs#6228]
## Category

- [x] Bug

## Describe the bug

We would like to provide our users with a search via API on a sharepoint site. 
We created an application but we need to add way too much right to the application in order to be able to get a result from the sharepoint search API. We expected the search to be working with only read right on One Sharepoint site.
Here is the process we followed

## Steps to reproduce
All requests are done with Postman.
1. Create of a Sharepoint application via an url like this one: https://YourSharePointOnlineSiteUrl/_layouts/15/appregnew.aspx
We use localhost for host and redirection URI for test purposes.

2. Add Read Authorisation to the application via an url like this one:
https://YourSharePointOnlineSiteUrl/_layouts/15/appinv.aspx
Here are the XML we provide
```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read"/>
</AppPermissionRequests>
```

3. Get the token via an API post request `https://accounts.accesscontrol.windows.net/{tenantID}/tokens/OAuth/2`

4. Execute Get request with the token we just get 
`https://YourSharePointOnlineSiteUrl/_api/search/query?querytext=’sharepoint’` 

The request send us a code 500 with this message
```javascript
{
    "error": {
        "code": "-1, Microsoft.Office.Server.Search.REST.SearchServiceException",
        "message": {
            "lang": "fr-FR",
            "value": "Application does not have administrative permissions in tenant"
        }
    }
}
```

5. We need to add these rights in order to be able to make the request
```xml
<AppPermissionRequests AllowAppOnlyPolicy="false">
  <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal" />
</AppPermissionRequests>
```
```xml
<AppPermissionRequests>
  <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="Read" />
</AppPermissionRequests>
``` 

```
## Expected behavior
We would like to be able to perform the search only on 1 Sharepoint site without the tenant read right.
Otherwise we can search on all sharepoint site which is what we want to avoid.


## Environment details (*development & target environment*)

- **Your Developer Environment**: MacOS 10.14.6
- **Target Environment**: SharePoint Online
- **Tooling**: Postman

**Comment by andrewconnell** [comment]
@bguivarch said:
> We would like to be able to perform the search only on 1 Sharepoint site without the tenant read right.

That's not possible... app permissions are specific to the tenant (ie: the TLD part of the URL), not a specific site.

Users will get results for anything they have access to. If you want to block it, you can apply filters to your query to filter out everything that isn't in a specific site, but there's no app permission to block those results.

**Comment by bguivarch** [comment]
@andrewconnell Thank you for your response.

I saw this API route on the graph API in Beta: https://docs.microsoft.com/fr-fr/graph/api/search-query?view=graph-rest-beta&tabs=http

Do you have any information about the production release ?

**Comment by andrewconnell** [comment]
I don't, but you should direct MS Graph questions to their forums. This is specifically focused on SharePoint development.
