### ISSUE TITLE
Extension type parameter is not passed to extension generator in @microsoft/generator-sharepoint@1.1.0

### ISSUE THREAD

**Issue by phawrylak** [SharePoint/sp-dev-docs#623]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
To support creating SharePoint Framework Extension solutions from command line without prompt,
`--extensionType` parameter should be passed to extension generator.

#### Observed Behavior
Parameter `--extensionType` is not passed from component generator to extension generator.

#### Steps to Reproduce
1. `npm install -g @microsoft/generator-sharepoint@1.1.0`
2. `yo @microsoft/sharepoint --solutionName "spfx" --componentType "extension" --extensionType "ApplicationCustomizer" --componentName "spfx" --componentDescription "spfx"`
3. Generator still prompts for extension type.

#### Version
`@microsoft/generator-sharepoint@1.1.0`

**Comment by nickpape-msft** [comment]
This is definitely an issue. I'll update this thread once we push an update to the generator.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
