### ISSUE TITLE
Getting errors about <div> cannot be nested in <p> when looking at web part data in workbench testing environment

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6232]
## Category

- [x] Bug

## Describe the bug

When I test out one of the default react templates without changing any code, when I click the web part data button, I see errors.

## Steps to reproduce

Load the default react template from @microsoft/sharepoint
Click the web part data button
See error

## Expected behavior

No error

## Environment details (*development & target environment*)

Windows 10
 SharePoint Online
Node.js v10
Chrome v79
VS Code | SPFx v1.10.0

[https://i.imgur.com/ufjQl5I.png](https://i.imgur.com/ufjQl5I.png)
[https://i.imgur.com/nuSJCb0.png](https://i.imgur.com/nuSJCb0.png)

Errors

	Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
		in div (created by SerializedCanvasView)
		in p (created by SerializedCanvasView)
		in div (created by SerializedCanvasView)
		in div (created by PivotItem)
		in PivotItem (created by SerializedCanvasView)
		in div (created by PivotBase)
		in div (created by PivotBase)
		in PivotBase (created by Context.Consumer)
		in StyledPivotBase (created by SerializedCanvasView)
		in div (created by SerializedCanvasView)
		in div (created by DialogContentBase)
		in div (created by DialogContentBase)
		in div (created by DialogContentBase)
		in DialogContentBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by DialogBase)
		in div (created by ModalBase)
		in div (created by FocusTrapZone)
		in FocusTrapZone (created by ModalBase)
		in div (created by ModalBase)
		in div (created by Popup)
		in Popup (created by ModalBase)
		in div (created by FabricBase)
		in FabricBase (created by Context.Consumer)
		in StyledFabricBase (created by LayerBase)
		in span (created by LayerBase)
		in LayerBase (created by Context.Consumer)
		in CustomizedLayer (created by Context.Consumer)
		in StyledCustomizedLayer (created by ModalBase)
		in ModalBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by DialogBase)
		in DialogBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by SerializedCanvasView)
		in SerializedCanvasView (created by WorkBench)
		in div (created by WorkBench)
		in WorkBench
		in div

	sp-webpart-workbench-assembly_default.js:75789 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
		in div (created by SerializedWebPart)
		in p (created by SerializedWebPart)
		in SerializedWebPart (created by SerializedCanvasView)
		in div (created by SerializedCanvasView)
		in div (created by PivotItem)
		in PivotItem (created by SerializedCanvasView)
		in div (created by PivotBase)
		in div (created by PivotBase)
		in PivotBase (created by Context.Consumer)
		in StyledPivotBase (created by SerializedCanvasView)
		in div (created by SerializedCanvasView)
		in div (created by DialogContentBase)
		in div (created by DialogContentBase)
		in div (created by DialogContentBase)
		in DialogContentBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by DialogBase)
		in div (created by ModalBase)
		in div (created by FocusTrapZone)
		in FocusTrapZone (created by ModalBase)
		in div (created by ModalBase)
		in div (created by Popup)
		in Popup (created by ModalBase)
		in div (created by FabricBase)
		in FabricBase (created by Context.Consumer)
		in StyledFabricBase (created by LayerBase)
		in span (created by LayerBase)
		in LayerBase (created by Context.Consumer)
		in CustomizedLayer (created by Context.Consumer)
		in StyledCustomizedLayer (created by ModalBase)
		in ModalBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by DialogBase)
		in DialogBase (created by WithResponsiveMode)
		in WithResponsiveMode (created by Context.Consumer)
		in StyledWithResponsiveMode (created by SerializedCanvasView)
		in SerializedCanvasView (created by WorkBench)
		in div (created by WorkBench)
		in WorkBench
		in div

**Comment by patmill** [comment]
Where are you seeing these errors?

**Comment by TheInvoker** [comment]
In the dev tools console tab.

**Comment by kongmengfei** [comment]
Hi @TheInvoker,

I am able to reproduce this issue here： 

![image](https://user-images.githubusercontent.com/57654821/92548631-1fbb5200-f28a-11ea-97f4-fb079f5bf26f.png)

This warning comes from a constraint of browsers:
Paragraph tags are limited to only containing a limited set of tags (mostly tags for formatting text). It's strongly not recommended to have a div inside a paragraph. in a word, the "web part data" popup element not up to the tag omission specification.

When you click the web part data button, it will insert a div into `<p>` tag, which will trigger the warning:

![image](https://user-images.githubusercontent.com/57654821/92549156-3c0bbe80-f28b-11ea-9b0e-2683fd34eff2.png)

I think you can just ignore this warning as it won't affect your web part. 

Baker Kong
Microsoft SharePoint Community Support

**Comment by AJIXuMuK** [comment]
Hello @TheInvoker  - sorry for the long delay.
We're changing the templates for the web parts. The new templates will be available in v1.14.

**Comment by AJIXuMuK** [comment]
The templates have been changed in 1.14 beta
