### ISSUE TITLE
Error AADSTS160021: Application requested a user session which does not exist

### ISSUE THREAD

**Issue by karllarssonusawest** [SharePoint/sp-dev-docs#6233]
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Bug

## Question

I am using MsGraphClientFactory to grab items from a SharePoint list for an SPFX. Worked great, but the GET call has suddenly started returning this error:

Error AADSTS160021: Application requested a user session which does not exist

Here's the relevant code:

```
this._context.msGraphClientFactory.getClient()
          .then((client: MSGraphClient): void => {
            client
              .api(_url)
              .version('v1.0')
              .expand('fields')
              .top(upcommingDays)
              .filter(_filter)
              .get((error, response: any, rawResponse?: any) => {
                console.log(rawResponse);
                //
                if (!error) {
                  _results = response.value;
                  debugger;
                  resolve(_results);
                } else {
                  reject(error);
                }
              });
          });`
```

## Environment details (if applicable)

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**:@microsoft/sp-core-library 1.10.0
- **Browser(s)**: Chrome 84
- **Tooling**:  Visual Studio 2019

**Comment by karllarssonusawest** [comment]
Update: I was using my regular browser, but on a different browser the code was working. I deleted all my organization and MS cookies and it started working again, perhaps unsurprisingly as the error seems to relate to authenticated sessions.

**Comment by andrewconnell** [comment]
Sounds like something got cached in your cookies... unable to repro this myself, but seeing that clearing cookies resolved it, seems temporary. If this continues or comes up again, please submit another issue.
