### ISSUE TITLE
Workflow to publish major version

### ISSUE THREAD

**Issue by AlexRademeyer** [SharePoint/sp-dev-docs#6236]
Sharepoint 2010 workflows had the option to start a workflow to publish a major version of a document.

This workflow could be easily enabled and configured by any site administrator (no need to hire consultants in order to activate a workflow....).

Microsoft have removed this simple workflow but I don't see a replacement for it. what am I missing?

Can you please show me how to enable an equivalent of this workflow now that Microsoft have disabled it?

And/or how to migrate my existing workflows of this kind to Power Automate?

Thanks,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc176ce2-e245-8c2a-62a9-29f0fa3f755a
* Version Independent ID: 50df0c72-d567-a572-a4db-80730c5881f7
* Content: [Guidance - Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)
* Content Source: [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by AlexRademeyer** [comment]
within this SP2010 workflow we also had the option to assign the workflow tasks (approvals) to a sharepoint group which would be easily maintained by the site owner, within Sharepoint.
Can you confirm that we can do the same using Power Automate?

**Comment by justin0522** [comment]
if you want to publish a SharePoint page, please refer to this [docs](https://support.microsoft.com/en-us/office/schedule-a-sharepoint-page-or-news-post-to-go-live-at-a-specific-time-4b81873c-9bbc-4307-b7ea-7b6662ff1af2)

**Comment by AlexRademeyer** [comment]
Sorry, Justin, you have not understood the question.
The question is not about publishing pages (at all) but rather about the sharepoint online classic workflows for publishing major versions of documents.

**Comment by justin0522** [comment]
you can use the power automate to replace the classic workflows
[Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)

**Comment by AlexRademeyer** [comment]
Justin please, the original post is about a specific type of Sharepoint classic workflow:
Publish a major version of a document when approved.
Please take the time to read and answer the question fully.
