### ISSUE TITLE
TokenHelper class not working on .net core

### ISSUE THREAD

**Issue by SouravBiki** [SharePoint/sp-dev-docs#6238]
I was trying to use the TokenHelper class using .net core 3.1 web application. But AppForSharePointOnlineWebToolkit nuget package is unable to generate the code files. It works on .net framework projects though. 
Also I tried with copying the content of the TokenHelper class too but most of the imports are not supported in .net core. 

So is there any .net core compatible version of this class so that we can get clientcontext using accesstoken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Vansyork** [comment]
Any updates on this matter? i'm encountering the same problem

**Comment by zontak** [comment]
Hi, I've the same issue.
