### ISSUE TITLE
Generated component alias is too long

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#624]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Based on the provided component name, the generated alias should be no longer than 40 characters to comply with the manifest schema.

#### Observed Behavior
Depending on the provided component name, the generated alias can exceed 40 characters which will result in validation errors when trying to build the project.

#### Steps to Reproduce
1. Create new project
1. Add application customizer with name **ApplicationCustomizer** > the generated alias is **ApplicationCustomizerApplicationCustomizer** which exceeds the allowed 40 characters.

**Comment by giuleon** [comment]
Hi Waldek,

I opened the same issue here:
https://github.com/SharePoint/sp-dev-fx-extensions/issues/2

**Comment by waldekmastykarz** [comment]
Nice catch!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
