### ISSUE TITLE
[App Studio Teams App for SharePoint Page] - Page Never Loads

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#6242]
Followed the instructions to the letter (swapping out domains where appropriate), on multiple tenants, but the page never loads.

Page eventually fails to "There was a problem reaching this app".

Occurs on both Teams Desktop and Web App.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by patmill** [comment]
Hey, sorry for the delay @jimmywim - the docs have been updated, and the best way to do this now is via the Viva Connections Desktop feature.
