### ISSUE TITLE
401 after successfull connect

### ISSUE THREAD

**Issue by J-a-k-o-b** [SharePoint/sp-dev-docs#6243]
Hi,
thank you for sharing this helpful information. I´m using this method in more than one environment. 
Now i have a problem with using that procedure in one single tenant. When i´m connecting with PNP using your described way:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#using-this-principal-with-pnp-powershell
or using it with the certstore and certificatethumprint, the connect is successfull. But when i try to read anything out, or change anything i get a 401error.
If I encode the access token I can see that i´ve the role assigned Sites.FullControl.All
![image](https://user-images.githubusercontent.com/46894290/92435359-6fbee980-f1a2-11ea-9d69-c1f2e91e81d3.png)
Any idea what´s going wrong here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
@erwinvanhunen do you have insight on this question?

**Comment by michaelmaillot** [comment]
Hi @J-a-k-o-b 

Is everything ok on your ADD Application API permissions page ? I reproduce your error with an AAD Application, which contains application scoped permissions not consented by an administrator, even if I was successfully connected to my site.

**Comment by J-a-k-o-b** [comment]
After creating the App, Certificate and so on with Initialize-PnPPowerShellAuthentication, and not manually as described in the docs,  i was able to connect and use the pnp commands as expected. Thank you for your support.
