### ISSUE TITLE
can we show a column in a form based on a lookup field?

### ISSUE THREAD

**Issue by ioanagopian** [SharePoint/sp-dev-docs#6249]
We have tried using a formula to show a Column based on a lookup field.
Based on the Person example we used the following formula:
`=if([$Category.Title]=='Product Management','true', 'false')`
but it did not work.

Are lookup fields supported, or are they planned?

Thanks,
Ioan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not at this time.
