### ISSUE TITLE
🙏 Extensions: Application Customizer - Additional Placeholders Requested

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#625]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Today we get `PageHead` & `PageFooter`... would like to have BEFORE/AFTER DIV's for `QuickLaunch` & `PlaceHolderMain`

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

OK... cross-referenced:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/19536022-extensions-application-customizer-additional-pl

**Comment by VesaJuvonen** [comment]
Thx AC for the input. 
We'll absolutely introduce additional placeholders for the framework and this is a good input for getting the needed placeholders tracked. We would also love to have some details around the actual scenarios where you'd use the requested capabilities. That might be obvious in some cases, but actual business scenarios and use cases help to prioritize the requests. Thx.

**Comment by patmill** [comment]
Cross posting my response from UV.  

Hey AC - While I know what you mean here, can you refine this to target the modern experiences? For example, PlaceholderMain is an asp.net masterpage div that doesn't exist in the newer code. Would you think of Pre/Post Placeholdermain to be ContentHeader and ContentFooter (as opposed to PageHeader and PageFooter?

Additionally, how would you expect scrolling to work in this scenario? For example - what should happen with a listview with infinite scroll vs. a page with 500k of text?

**Comment by andrewconnell** [comment]
@patmill Will xpost from UV too :) 
Specifically looking for any place these extensions are supported... if that's just modern experiences, then just those (*although I hope these will also apply to classic pages, just as client-side web parts do*). Understand the names are different... I was referring to the intent of where things would go... a picture might help. I see the RED is what you provide today... the GREEN is what I'm asking for:

![image](https://user-images.githubusercontent.com/2068657/26953100-733059d4-4c76-11e7-9dfc-dab47a431551.png)

As for infinite scroll... I'd expect it to behave like the components that wrap them. For instance, on the QuickLaunch, it doesn't scroll so I'd expect what I put right after it to be pinned to the bottom border of the QL. Same is true with the main body of the page.

@VesaJuvonen - Biz case: context help, messages to the user based on the context of what they are doing or reminders they haven't done something. I could do this by doing DOM manipulation from the header / footer, and that's what folks will do as these are common places we want to add / remove stuff... but that's now how we *should* be doing it... so don't give them a reason to do it and add it for them. Make sense?

**Comment by PopWarner** [comment]
I agree with AC. While @VesaJuvonen has mentioned that keeping our customization's within the confines of these placeholders, which I assume is the contractual safe place for custom content, ensures that it will not get destroyed or broken with future updates to the DOM, if there are not additional Placeholders to be populated, users will simply begin manipulating the DOM.

While this isn't how they should add customization's, as @andrewconnell as mentioned, if there are no other places, peeps will still do it. 

The Pre/Post locations could also provide the ability to wrap that content with a custom CSS classname for ensuring specificity within a certain brand/design.....just one possible other thought.

**Comment by SPParseError** [comment]
Adding some additional placeholder requests here, as discussed in #656 
1. Site metadata: custom site meta data (state, contacts, project duration...)
2. Search bar: custom search bar
3. Left navigation: having a global navigation, buttons to create documents from templates, showing company's applications...

![placeholders](https://user-images.githubusercontent.com/12406819/28374120-1b7c442a-6ca4-11e7-92e1-9585a835252e.PNG)

**Comment by lucaband** [comment]
To updated everyone on this topic: the scenario is well understood and we are working to be sure we tackle that properly. There's still an open conversation to understand if Placeholders is the right technology to use to enable such scenarios or it is something else.

**Comment by andrewconnell** [comment]
I'm confused @lucaband ... why close the issue if the conversation is still open even if internally?

**Comment by lucaband** [comment]
Andrew, thanks,
Reason why I closed was because I though I answered the initial question.
But I'm perfectly fine to keep it open, assign it to me, and reply back here once we have some concrete news.

**Comment by saendu** [comment]
This might be interessting for you as well: https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/31752808-extensions-property-pane-sidebar-placeholder-r
I would like to see a sidebar placeholder on the right side.

**Comment by nsksaisaravana** [comment]
I would like to achieve the below-highlighted stuff in the modern experience but it is not possible due to the limited number of placeholders. Please introduce more placeholders as requested.

![image](https://user-images.githubusercontent.com/17681573/37136467-e459543e-22f5-11e8-8bb8-2ca538ec09e0.png)

**Comment by mpowney** [comment]
@lucaband  Are there any updates on a solution to this issue?

**Comment by VesaJuvonen** [comment]
as this is a new feature request and not specifically an issue, we'll close this, for now, to help on tracking actual issues in the issue list (trying to drive new feature requests to UserVoice). We will have some announcements coming up around this area during this spring - SPC18 and later.

**Comment by chemtrec2900** [comment]
I dont see any additional placeholders. The following only shows me Top and Bottom. Is there anything I have to do to get the other placeholders?
console.log(
      "Available placeholders: ",
      this.context.placeholderProvider.placeholderNames
        .map(name => PlaceholderName[name])
        .join(", ")
    );

**Comment by patmill** [comment]
Sorry for the lack of clarity.  Feature requests are handled via user-voice.  There are currently no additional placeholders.

**Comment by kashek85** [comment]
I dont think there are any new placeholders till today. I can only fine Top and Bottom. So people who want to customize have to manipulate DOM directly. @VesaJuvonen Please throw us a light on this.

**Comment by andrewconnell** [comment]
Top & bottom are the only two.

Microsoft has said in recent public community calls they are working on some stuff related to extensions. With a big conference (Ignite) coming up in November, I'd suspect we may learn more there, but not likely much before that.

**Comment by malleshatla** [comment]
Any update on above request, i am looking for solution.

**Comment by luismanez** [comment]
Afraid not @malleshatla 
With new 1.10 version, we have an option to modify Search experiences (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/building-search-extensions), but no new PlaceHolders yet

**Comment by VesaJuvonen** [comment]
Locking the issue as it's already closed and no reason to keep on having chat on closed issues as those comments can easily get fully ignored.
