### ISSUE TITLE
SPFx Command Set Extension does not fire onListViewUpdated when navigating to/from folders

### ISSUE THREAD

**Issue by prademi** [SharePoint/sp-dev-docs#6252]
## Category

- [x] Bug

## Expected or Desired Behavior
The onListViewUpdated event should fire when the user navigates to or from a folder in a list view.

## Observed Behavior
The onListViewUpdated event does not fire when the user navigates to or from a folder in a list view..

## Steps to reproduce

Create a command set extension
Add an alert dialog in the onListViewUpdated event handler
Test the command set extension
The alert dialog will show on initial load or when selecting/deselecting items but it will not show when navigating to/from folders.

This bug is related to #5034

Demo link: 
https://user-images.githubusercontent.com/5740654/71101049-1205ef80-2184-11ea-97c0-331ce709438f.gif

**Comment by barisbikmaz** [comment]
Dito same problem. Our command button is displayed based on the permissions of the user on the current folder. When navigating to a subfolder we want to check the permissions again. Currently this is not possible.

**Comment by AJIXuMuK** [comment]
This should be WW now.
