### ISSUE TITLE
pageContext does not refresh in app customizers on inline navigation

### ISSUE THREAD

**Issue by netti01** [SharePoint/sp-dev-docs#6253]
## Category

[x ] Question

## Question

We assume that based on inline navigation between modern pages and lists/libs, that there is a possible issue with refreshing the page context. This is likely not only a problem with SPFX, perhaps more a general logic bug in SPO itself ?!

This has been tested using the following app customizer template from github: 
[https://github.com/estruyf/appcustomizer-navigation-issues-spfx](https://github.com/estruyf/appcustomizer-navigation-issues-spfx)

We extended the information the app customizer delivers within the header section with additional properties like "pageItemId, listTitle..."

![image](https://user-images.githubusercontent.com/44964962/92569088-6dcb5800-f280-11ea-8b75-6d4368a84c59.png)

When a user does an inline navigation between a modern UI page and e.g. the SitePages library, the header displays empty properties, even if you use the standard refresh events in SPFX like: 

`this.context.application.navigatedEvent`

**This is the default output if you directly load a doc lib.**
![image](https://user-images.githubusercontent.com/44964962/92568555-a0c11c00-f27f-11ea-8c1c-2b075d41fb23.png)

**This is the output if you do an inline navigation from a page to the lib**
![image](https://user-images.githubusercontent.com/44964962/92568693-d534d800-f27f-11ea-9e24-9b300d042830.png)
As you can see, also the url of the lib is incorrect.

We also figured out that inline navigation to doc libs/lists causes some additional issues which may be related to this behavior, like:

- Header placeholder element in DOM is contained twice (one from the page you navigated from, the other from the lib). Perhaps the Modern Page Header is simply outdated?

![image](https://user-images.githubusercontent.com/44964962/92583096-20f07d00-f292-11ea-9175-224ec9d6864c.png)

- If you navigate inline from a modern page to SitePages lib, you are not able to open a modern news link in edit mode anymore (an url parameter is not set correctly - ?stay=true) > Fully reload SitePage lib (F5) and it works as expected.

Any help or tipps on how to address this issues to the right people? We allready opened support tickets for these issues on our tenant, still at first level support, and it is not easy to explain the direct user impact because the app customizer is somehow "custom development".

Thanks 
Bjoern

## Environment details 

- **Your Developer Environment**:Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**: any
- **Tooling**: VS Code | SPFx 1.10

## Tags
#spfx-tooling #spfx

## Possible related issues
#6237

**Comment by MrTantum** [comment]
We have noticed this too. Could this be a general problem with query parameters when using inline navigation?

**Comment by estruyf** [comment]
There are indeed issues with partial page transitions, check the following posts for a couple of techniques to overcome this: https://www.eliostruyf.com/things-to-check-in-your-spfx-application-customizer-after-page-transitions/

**Comment by netti01** [comment]
@estruyf - Thanks for your answer..

Actually we are allready using the same techniques you mentioned in your blog post to **workaround** this issues. If nothing works, pageContext somehow did not refresh, the only thing we can do (like in your code) is to trigger a full page reload.

![image](https://user-images.githubusercontent.com/44964962/92871527-4fdb3000-f405-11ea-805c-1c5cc938f5ed.png)

The big difference is, that this actually happens if a user navigates between a modern page and a doc lib and not like in your code, only when the user navigates between different hubs or site collections. Means: the overall inline navigation concept between pages and libs can not be used and **always needs a full page reload** in order to provide the correct pageContext.

**Comment by estruyf** [comment]
BTW, the double placeholders #4945 was already reported a long time ago. Issue is still open.

**Comment by Peter-Ross-C** [comment]
Can confirm that we are also experiencing this issue. 

We are making use of an ApplicationExtension to run some code on all pages, which is now only running on full page loads/reloads. 

@estruyf Will explore the options in your article, thanks for that.

**Comment by MartinWhiteDAZN** [comment]
We are experiencing this as well. 
It happens with the simplest test:
Scaffold a new extension and deploy it as-is.
Navigate between pages using the SharePoint navigation and the dialog only appears when the same navigation link is clicked twice.

**Comment by coreyroth** [comment]
This is definitely still an issue for me and according to my logs, it started happening more and more starting in May for me.  I see this happen across tenants thousands of times per week.  I've used some of the workarounds but it's not guaranteed.

**Comment by AJIXuMuK** [comment]
Sorry @netti01 for the long delay.
We've fixed this issue, and the fix should be available WW in the next couple of weeks.

**Comment by patmill** [comment]
This should be WW now.
