### ISSUE TITLE
Still missing yo @microsoft/sharepoint in Step 3

### ISSUE THREAD

**Issue by Marker4** [SharePoint/sp-dev-docs#6256]
Still missing "yo @microsoft/sharepoint" in Step 3 making the instructions confusing for someone new to spfx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7cd562-b54f-0157-2912-e8100a9dbb0b
* Version Independent ID: 6b9554bd-2d7e-d8b0-7461-c80dd89f5be8
* Content: [Tutorial - Migrating from Edit Control Block (ECB) menu item to SharePoint Framework Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions)
* Content Source: [docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by SmitaNachan** [comment]
Hi @Marker4 
This has been fixed recently with a [PR](https://github.com/SharePoint/sp-dev-docs/pull/6234).
It might take some time to reflect.
