### ISSUE TITLE
Date format in Lists for teams

### ISSUE THREAD

**Issue by kevdevries** [SharePoint/sp-dev-docs#6258]
How can I change date format from mm/dd/yyyy to dd/mm/yyyy ?

I am in Australia.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by CallumCrowley** [comment]
Hi @kevdevries 👋

It sounds like you may need to change the regional settings of the SharePoint site that your Microsoft 365 group is connected to. You can do this by navigating to the site and following the instructions here:

[Change regional settings for a site](https://support.microsoft.com/office/change-regional-settings-for-a-site-e9e189c7-16e3-45d3-a090-770be6e83c1a)

**Comment by kevdevries** [comment]
Thank you very much Callum. 
Your help is appreciated, and yes, I had the site region set to USA.
Many thanks,
Kevin
