### ISSUE TITLE
CustomRowActions not working on first page load

### ISSUE THREAD

**Issue by luisebenkert** [SharePoint/sp-dev-docs#6261]
## Category

- [x] Bug

## Describe the bug

I have a document library in my Sharepoint (modern view) in which I use the advanced JSON formatting to add some action buttons (editProps, delete, preview etc.). These used to work just fine but recently I have issues with them. Whenever I try to access the library directly through its url, or from the teamwebsite and then clicking on the left nav item, the buttons stop working entirely. No matter how many times I refresh the page the buttons don't do anything.

**The only way to make them work is to click on another page in the left nav menu and then clicking the left nav menu item to go back to the library (sometimes it also works by just clicking the library left nav menu item again)**

What I have tried so far - but nothing worked:

- deactivated MDS in the settings
- created a new library with the same settings
- tested on various browsers, laptops, networks

## Steps to reproduce

My JSON formatting is as follows: 

`
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "div",
    "_comment_": "CONTAINER",
    "style": {...},
    "attributes": {},
    "children": [
      {
        "elmType": "button",
        "customRowAction": {
          "action": "defaultClick"
        },
        "style": {...},
        "children": [
          {
            "elmType": "img",
            "_comment_": "PREVIEW",
            "style": {...},
            "attributes": {
              "src": "@thumbnail.large"
            }
          }
        ]
      },
      {
        "elmType": "div",
        "_comment_": "DETAILS",
        "style": {...},
        "children": [
          {
            "elmType": "span",
            "txtContent": "= if([$Kategorie] == '', 'Unbearbeitetes Dokument', [$Kategorie])",
            "style": {...}
          },
          {
            "elmType": "span",
            "txtContent": "erstellt von"
          },
          {
            "elmType": "span",
            "txtContent": "[$Author.title]",
            "style": {...}
          },
          {
            "elmType": "span",
            "txtContent": "='am ' + toLocaleDateString([$Created]) + ' um ' + toLocaleTimeString([$Created])"
          }
        ]
      },
      {
        "elmType": "div",
        "_comment_": "ACTIONS",
        "style": {...},
        "children": [
          {
            "elmType": "div",
            "style": {...},
            "children": [
              {
                "elmType": "a",
                "attributes": {
                  "iconName": "Mail",
                  "class": "sp-field-quickActions",
                  "href": "= 'mailto:' + [$Author.email]"
                },
                "style": {...}
              }
            ]
          },
          {
            "elmType": "button",
            "customRowAction": {
              "action": "editProps"
            },
            "style": {...},
            "children": [
              {
                "elmType": "span",
                "attributes": {
                  "iconName": "Edit"
                },
                "style": {...}
              }
            ]
          },
          {
            "elmType": "button",
            "customRowAction": {
              "action": "delete"
            },
            "children": [
              {
                "elmType": "span",
                "attributes": {
                  "iconName": "Delete"
                }
              }
            ],
            "style": {...}
          }
        ]
      }
    ]
  }
}
`

**Whenever it doesn't work I see the following error in the console:**

GET https://WEBSITE/_api/v2.0/drive/apps?select=*,promoted&$expand=actions  -> 404

I am also getting the other following errors:

- Uncaught (in promise) TypeError: e.navigationPreload is undefined | splistwebpack.js:1:217503

- GET https://WEBSITE/_vti_bin/homeapi.ashx/sites/followed/isFollowed?siteId={d6b8da5a-25b6-4049-b28c-456d9fee917a}&webId={8b54cde2-4bf0-42ab-bfb3-c927254aac31}&url=WEBSITE | 500

- Content Security Policy: The page’s settings blocked the loading of a resource at https://r4.res.office365.com/footprint/v3.2/scripts/fp-min.js (“script-src”). | suiteux.shell.plus.539fd7f68f5452a8c36c.js:135:25575

Thank you for your help!

## Environment details (*development & target environment*)

- Windows 10
- SharePoint Online
- FireFox v80 & Edge v42

**Comment by shagra-ms** [comment]
@luisebenkert Thanks for the detailed steps. I was able to repro this locally. Will investigate and share an update soon on this.
