### ISSUE TITLE
fluentui icons

### ISSUE THREAD

**Issue by ghost** [SharePoint/sp-dev-docs#6262]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

My app stopped displaying Icons in SharePoint Online. I am using the following: 

"loadLegacyFabricCss": true in the manifest,

In my customizer:

import { DefaultButton } from 'office-ui-fabric-react';

<i className={['ms-Icon', 'ms-Icon--ChevronUpSmall]}></i>

Question. Do I need to remove the office-ui-fabric and reference the latest Fluent-ui or is there an actual proven method for legacy implementations that works ?

## Environment details (if applicable)

- **Your Developer Environment**: [e.g. Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**:  Node.js /v10/
- **Browser(s)**: [e.g. Chrome v79 
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio Code
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by FAT77** [comment]
Hi,

We have experienced the same issue. All webparts in our Tenant that are using fabric icons suddenly stop watching.

After some research, I found that if you call the method initializeIcons() it fix the problem.

import { DefaultButton, initializeIcons } from 'office-ui-fabric-react';
initializeIcons();

**Comment by justin0522** [comment]
@FAT77  you are right, please refer to this document
https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

**Comment by AJIXuMuK** [comment]
Sorry for the long delay here.
`initializeIcons` call is the correct approach of dealing with missing icons.
