### ISSUE TITLE
Property 'execute' does not exist on type 'IObjectPathBatch' SPFx 1.11

### ISSUE THREAD

**Issue by sharepointkonsult** [SharePoint/sp-dev-docs#6264]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

Expected or Desired Behavior
Would like to make batch requests using taxonomy.

Observed Behavior
import {taxonomy, ITerm, ITermSet, ITermStore} from '@pnp/sp-taxonomy';
. . .
const taxonomyBatch = taxonomy.createBatch();
. . .
taxonomyBatch**.execute**().then(_r => {resolve

I'm using spfx 1.11.0 and is pnp/sp-taxonomy.
 Error: Property 'execute' does not exist on type 'IObjectPathBatch'. What is the recommended or how I can fix it.

**Comment by andrewconnell** [comment]
This is a question about the PnPJS library, not general SharePoint development. Please post your question to the PnPJS repo: https://github.com/pnp/pnpjs
