### ISSUE TITLE
Adding extension column to the library breaks search (in private mode only)

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [SharePoint/sp-dev-docs#6265]
## Category

- [x] Bug

## Describe the bug

We use SP online and SPFX (extenstions).
We have automation tests which run in private mode. One of the tests opens library with column which is added from our SPFX extensions. Then test uses SP search to enter name of a doc and press Enter, but that action fails, since search is not finished and we see endless loader.

## Steps to reproduce

1. open Chrome in private mode
1. Go Sharepoint online, then to library with custom extension column
1. Click on SP search and enter name of some document
1. press Enter
1. See error - endless scroller

## Expected behavior

Document is found and displayed

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [SPFX 1.10]
- **Browser(s)**: [Chrome (private mode)]
- **Tooling**: [VS Code | SPFx v1.10.0]

**Comment by andrewconnell** [comment]
Unclear by what you mean by "custom extension column"... can you please clarify?

**Comment by VladyslavGoloshchapov** [comment]
Sorry, I meant
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

**Comment by justin0522** [comment]
@VladyslavGoloshchapov  you mean modern search, right ?

**Comment by VladyslavGoloshchapov** [comment]
@justin0522 not sure if that is modern search, but I can send you a video.
Please note this is only is Chrome in private mode with third party cookies enabled.

[https://www.screencast.com/t/fgvXnuvyG](https://www.screencast.com/t/fgvXnuvyG)

**Comment by justin0522** [comment]
I did a test in my env, and it worked well.

![20200930215151](https://user-images.githubusercontent.com/20319639/94694215-2f005d80-0367-11eb-808c-bf4500741292.png)
you are doing a modern search in list scope, could you try to input **ggggg** or **gggg*** for a test

**Comment by VladyslavGoloshchapov** [comment]
Also did you add custom field @justin0522 ?

**Comment by VladyslavGoloshchapov** [comment]
tried, but still reproducible.

Please note additional condition which I found is required to reproduce the issue:
- you must come into the list from Home page without visiting any other pages.

**Comment by AJIXuMuK** [comment]
Hi @VladyslavGoloshchapov,
Sorry for the long delay here.
Could you please check if the issue still exist for you?
Currently it seems to be fixed.
