### ISSUE TITLE
Office 365 Suite Bar not loading properly for SingleWebPartAppPage

### ISSUE THREAD

**Issue by jyothsnag29** [SharePoint/sp-dev-docs#6271]
## Category

- [x] Bug

## Describe the bug

The Office 365 Suite Bar is not loaded properly for SingleWebPartAppPage (Single App Page) which contains a SPFx webpart. 
- missing Settings icon
- tenant logo
- SharePoint link
- showing less details when we click on person name
![image](https://user-images.githubusercontent.com/43003891/92902072-4495fd80-f421-11ea-9843-501cc6b2320e.png)
- Doesn't show any apps and the Office 365 link navigates to office.live.com
![image](https://user-images.githubusercontent.com/43003891/92902831-e6b5e580-f421-11ea-85ba-177115726d7d.png)

## Steps to reproduce

1. Navigate to any of the SharePoint page which is of type SingleWebPartAppPage
2. Observe the  Office 365 Suite Bar and Office 365 App Launcher.
3. Observe the Person details

## Expected behavior

Irrespective of SharePoint page PageLayoutType, Office 365 Suite Bar should load properly. 

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [SharePoint Online]
- **Framework**: [SPFx 1.11]
- **Browser(s)**: [Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [VS Code | SPFx v1.10.0 ]

### Additional context
We use the SingeWebpartAppPage (has SPFx webpart) as a HomePage and this will be the landing/starting page to open other office 365 application from there.
We have observed this behavior in multiple tenants.

**Comment by arunkumarperumal** [comment]
Have the exact same issue. additional issue is also with the search box not working.

**Comment by KevinTCoughlin** [comment]
We've pulled the offending change. This should be resolved in 10-15 mins if not already. Thanks for the report.

**Comment by jyothsnag29** [comment]
This has been fixed in our tenants, Thank you for providing the quick fix.
