### ISSUE TITLE
Running react with ListView Command Set not working

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6272]
## Category

- [x] Bug

## Describe the bug

The command buttons don't load. Looking in the console, it says react.js and react-dom.js is not found.

## Steps to reproduce

Run this tutorial (no further customizations)
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx

## Expected behavior

Command buttons show up

## Environment details (*development & target environment*)

Windows 10 
SharePoint Online
Node.js v10
Chrome v79
VS Code | SPFx v1.10.0

**Comment by patmill** [comment]
Can you paste the specific errors in the console?
