### ISSUE TITLE
why too slow when cmd gulp bundle --ship ? 7(minutes)

### ISSUE THREAD

**Issue by jimmyhoum** [SharePoint/sp-dev-docs#6273]
when i cmd : gulp bundle --ship     ,it spend too long time,  how to solve it?
![image](https://raw.githubusercontent.com/jimmyhoum/test1/master/q.png)

**Win10**

**Gulp Version**
CLI version: 2.3.0
Local version: 3.9.1

**webpack version**
4.44.1

**config/package-solution.json**
`
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "client-side-solution",
    "id": "1593639c-200b-44b7-abd9-da6ea6c16f4a",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    }
  },
  "paths": {
    "zippedPackage": "solution/myapp.sppkg"
  }
}
`

**Comment by patmill** [comment]
Out of curiosity, how big is your output?

**Comment by jimmyhoum** [comment]
Finally, the sppkg file size is 6.5MB,  that's only 22 webparts in the solution

**Comment by andrewconnell** [comment]
First, closing this as incomplete as there's no nearly enough context... please use the template that's provided with new issues as it has a section to complete with more context that helps us help you (SPFx version, node version, etc, etc).

But... 6.5MB for a production build? What are you ingesting into the bundle? 

Suggest including the following detail as well: What's your **./config/config.json** & **package.json** look like & what external libraries are you using?
