### ISSUE TITLE
About build and deploy sppkg file, how to discriminate uat and production package ?

### ISSUE THREAD

**Issue by jimmyhoum** [SharePoint/sp-dev-docs#6274]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have only one SharePoint online, that's two site collections
>sites/UAT
>sites/production.

When I develop spfx and only want to test the UAT environment, how can I deploy to appcatalog? And does not affect the production environment

when cmd run "gulp package-solution --ship", modify id,name in config/package-solution.json every time ?

**Comment by bcameron1231** [comment]
I would use Site Collection App Catalog in your UAT site if your environments are in the same tenant. This will allow you to have a Production app living in the Tenant level, and then you can separately deploy the app into your UAT site collection.

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog

**Comment by jimmyhoum** [comment]
Vert thanks. That's great
