### ISSUE TITLE
Are you sure this article is for SharePoint Online?

### ISSUE THREAD

**Issue by legendgod** [SharePoint/sp-dev-docs#6275]
I cannot find display templates in SharePoint Online site settings. Is this page up-to-date?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889fe138-d543-4ef9-0ddb-fdbdb468a175
* Version Independent ID: eaacc54c-7a1e-d40a-2268-ec467a3a2ec3
* Content: [Search customizations for SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-customizations-for-sharepoint)
* Content Source: [docs/solution-guidance/search-customizations-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/search-customizations-for-sharepoint.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, yes this does apply to SharePoint Online. However, it is a **classic** SharePoint feature (so you cannot use these in modern sites). So you would need to be working with classic sites.

If you are looking to implement similar functionality in Modern SharePoint, checkout the PnP Modern Search Web Parts https://microsoft-search.github.io/pnp-modern-search/

**Comment by legendgod** [comment]
I see. It would be helpful if you update the article and add the PnP Modern Search link.

**Comment by NeverHere** [comment]
@andrewconnell I can take this one if you want to assign to me.
