### ISSUE TITLE
SharePoint Modernization Presentation not available

### ISSUE THREAD

**Issue by DilisGeorge** [SharePoint/sp-dev-docs#6276]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0688e7ba-f044-2b4b-3b41-9c84c157615c
* Version Independent ID: b5ae7629-3624-8b80-cd90-18dfb834a6bb
* Content: [SharePoint modernization guidance](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-partner-guidance)
* Content Source: [docs/transform/modernize-partner-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-partner-guidance.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
I navigated to the page and all of the presentations downloaded fine for me.
