### ISSUE TITLE
Need Help.  I broke my SharePoint List

### ISSUE THREAD

**Issue by acostae** [SharePoint/sp-dev-docs#6278]
[Enter feedback here]
I tried copying the JSON text from this page into my SharePoint List, but now whenever I click on a list item in Modern Mode (Not Classic Mode), I don't see any of my columns in the form editor.  "Edit Columns" and "Configure Layout" no longer do anything, and I fear I broke the form for.

Is there a way to roll back changes to a list in SharePoint (Version settings), or is there a way to remove the JSON text from the "Configure Layout"?  Bare in mind, Configure Layout is no longer working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by shagra-ms** [comment]
@acostae Can you share the JSON that you used from view-formatting docs? Can you also confirm the steps that you used to add the JSON in the form editor?

**Comment by acostae** [comment]
The JSON I used is listed on this page: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting

The JSON used can be found under the “Multi-line view style” section (The first one).

The steps I took:

  1.  I opened my list
  2.  I clicked on the first item in my list (there are 900+ items)
  3.  I clicked on “Edit form” and selected “Configure Layout”
  4.  I applied the JSON to the open text field with “Header” selected.
  5.  When that did not work, I tried doing the same thing, but with “Body” Selected
  6.  When that did not work, I tried doing the same thing, but with “Footer” Selected

At this point  is where my form broke.

Thanks,

Emmanuel Acosta
Information Security Governance Reviews – Data Governance Analyst
acostae@vmware.com<mailto:acostae@vmware.com>

[signature_514391341]

Notice of Confidentiality - This email message is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by shagra-ms** [comment]
Thanks for confirming @acostae. The JSON used is a view-formatting JSON and has been applied on Form Header/Body/Footer layout customization, where it would not work.

Did you 'Save' the changes in Header/Footer/Body JSON?

@chakkaradeep request your attention here.

**Comment by acostae** [comment]
Yes.

Emmanuel Acosta
Information Security Governance Reviews – Data Governance Analyst
acostae@vmware.com<mailto:acostae@vmware.com>

[signature_2113232011]

Notice of Confidentiality - This email message is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by chakkaradeep** [comment]
@acostae we have not released the 'Configure layout' feature to the public. Are you or your company part of the Teams TAP program? Is that why are you seeing that option>

**Comment by acostae** [comment]
If VMware is part of the Teams TAP program, then I am not aware of it.  I found the page I referenced through a web search, and tried applying the JSON myself.  My efforts obviously failed epically, so I want to know if it is possible to revert the changes?

Emmanuel Acosta
Information Security Governance Reviews – Data Governance Analyst
acostae@vmware.com<mailto:acostae@vmware.com>

[signature_1505008624]

Notice of Confidentiality - This email message is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by chakkaradeep** [comment]
@acostae  we have not documented about 'Configure layout' and unfortunately since it's not released yet, we are unable to provide help on that. Can you please check with your team and confirm if VMWare is part of the Teams TAP program?

**Comment by acostae** [comment]
I will ask when my IT team gets back to me.  In the meantime, would you happen to know if there is a way to backup a SharePoint list?  This whole ordeal has made me conscious of how easy it is for the data to become compromised, and I would like to see if there is a way to shield ourselves from these sort of mishaps.

Emmanuel Acosta
Information Security Governance Reviews – Data Governance Analyst
acostae@vmware.com<mailto:acostae@vmware.com>

[signature_1885032199]

Notice of Confidentiality - This email message is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by chakkaradeep** [comment]
@acostae  I don't believe the data is lost. If you dont mind, can you please send me screenshots of what you are experiencing to chaksc at microsoft dot com? We can discuss this in the email. Thanks!

**Comment by shagra-ms** [comment]
Removing the area:list-formatting tag.
