### ISSUE TITLE
need help. Where I can find the Webpack configuration of the Spfx project.

### ISSUE THREAD

**Issue by simonssspirit** [SharePoint/sp-dev-docs#6280]
## Category

- [x] Question

## Question

Where I can find the Webpack configuration of the Spfx project.

We have an issue with the CSS that is produced from the SASS that we are importing.

We want to see the full configuration to inspect what could be causing this issue.

The same SASS is successfully transpired to CSS with the same version of node-sass in an isolated project.

**Comment by andrewconnell** [comment]
This isn't documented as it's dynamically generated for each build by the toolchain. You can dump the config to the console by adding the following to the end of the **gulpfile.js**:

```javascript
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfig) => {
    console.log('<webpack.config type="object">');
    console.log(generatedConfig);
    console.log('</webpack.config>');

    console.log('<webpack.config type="string">');
    console.log(JSON.stringify(generatedConfig));
    console.log('</webpack.config>');

    return generatedConfig;
  }
});
```
