### ISSUE TITLE
Extension that is tenant deployed will fully reload when navigating between sites once ANY other extension is installed on one of the sites

### ISSUE THREAD

**Issue by mbice** [SharePoint/sp-dev-docs#6286]
## Category

- [x] Question
- [x] Bug

## Question

I'm seeing some odd behavior with tenant deployed extensions when there are also extensions that are not globally deployed, but installed on any site.

To test this I spun up two hello world extensions using latest scaffolding. I deployed both to my app catalog. The first extension, I deployed globally to the entire tenant. When I navigate around from site to site, as long as the page is client-side navigating, the init method of my extension does not keep firing (i.e. it only fires once per full page load). Next, I deploy my second extension to the tenant app catalog. For this one, though, I don't deploy it globally. Instead, I install it on the root site collection. When I reload the root home page, I see both extensions fire (both the tenant deployed one and the site deployed one). However, now when I navigate to another site collection, my tenant deployed extension fires it's init, even though it's client-side navigation.

This is problematic because if I want an extension with a visually static UI, I can't really do that even if it's globally deployed because the extension is completely unloading and re-initialized so it disappears and then pops back in. So it doesn't match up with the smooth transition of client-side navigation. If I uninstall that site scoped extension, it goes back to the normal behavior and only fires its init() when the page is fully reloaded.

Is this expected behavior? 

Another question (somewhat related) - If I install the same app package on multiple sites (so it's not globally deployed), should those extensions totally re-initialize when navigating from site-to-site? For example, if I have an extension displayed across the top of the page and I want to limit that extension to a particular set of sites, it will unload and reload on when navigating between site collections, which creates a jarring user experience.

Thanks!

## Environment details (if applicable)

- Windows 10
- SharePoint Online
- Node.js v10
- Chrome v85
- SPFx v1.11.0

**Comment by patmill** [comment]
Just to confirm what you are seeing / expecting:

navigating from site -> site, 
    if the source and target site extensions match, no unload/reload takes place
    if the source and target site extensions don't match, all of them are unloaded and the target ones are loaded

What you would expect
If the source and target don't match, only things that aren't on the target are unloaded, and only new extensions on the target are loaded

?

**Comment by mbice** [comment]
@patmill 

When extensions are site scoped they reload on every site navigation, matching or not. If an extension is tenant deployed and ANY other extension is site scoped even the tenant deployed extension starts to reload on every site navigation as well.

My expectation would be if an extension is tenant deployed, it should never reload on site navigation unless it's a hard page reload. I think it would also be nice to have it working so that if the same extension is deployed to multiple sites that it also not reload on site navigation b/c they are identical extensions. Otherwise we get that flicker from site to site.

Hope that helps clarify?

Thanks!

**Comment by mbice** [comment]
Hi,

I'm still seeing this behavior. Any insights as to whether or not this is expected? I would still assume that global extensions should not re-initialize on each client-side page navigation as soon as any site-scoped extension is installed (even if it's on a totally different site that the one being navigated to).

Thanks!

**Comment by mbice** [comment]
Hi,

I did some more testing and noticed that this somehow seems related to the name of the custom action that gets registered via the site-scoped extension. For example, if I manually register the extension's custom action using the **same** name on multiple sites, all the other global extensions don't reload on each client-side navigation event. If I install the extension as an app OR use a site design "associateExtension" verb, the custom action that gets registered on each site has a different name (it's assigned a random GUID). If the site-scoped extension is installed on every site with the same name, no reloading of other global extensions occurs. If the site-scoped extension is either NOT installed on a site being navigated to OR has a custom action registered with a different name, it triggers all the other tenant deployed extensions to reload on every navigation event.

Thoughts @patmill ?

**Comment by mbice** [comment]
Hi,

Hoping to follow up on this and see if it's a known issue or any possible workaround? We are still experiencing this issue. If we install an app extension on a site, it forces extensions everywhere to reload on each client-side navigation action. For site designs, custom actions registered also reload on every navigation event. Seemed like these issues might be related and somehow caused by different custom action IDs being used on each site..

**Comment by patmill** [comment]
Sorry for going dark @mbice .  So this is by design.  When you have the same extension registered in different sites, you effectively have different registrations (they could have different parameters, etc), so they are unloaded / loaded.  Tenant wide deployment would solve this (and you can target specific site templates this way), but individual registrations will be treated as unique.  For site design custom actions, if it is happening where the same registration should be in place (same site / list / etc.) can you open a new issue, and we can route it accordingly?  (we won't go dark for months).  Thanks.
