### ISSUE TITLE
Minified React error 290 SPFx Field Customizer

### ISSUE THREAD

**Issue by RamaKaryam** [SharePoint/sp-dev-docs#6289]
## Category

- [x] Bug

## Describe the bug

I have an SPFx field customizer. Below is the package.json
{
  "name": "custom-column",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.9.1",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-listview-extensibility": "1.9.1",
    "@types/es6-collections": "^0.5.31",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "@uifabric/file-type-icons": "^7.1.4",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "react-to-print": "^2.5.0"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

The extension loads fine when I go to the library directly. However, if go to it via a link to the library on some other page, it is giving this error: https://reactjs.org/docs/error-decoder.html/?invariant=290&args[]=A.%20General

## Steps to reproduce

1. Render an IconButton in your field.
2. On click, open a panel with a details list inside it like below. Make sure you render a DetailsHeader (so its close to what I have).
                         <DetailsList
                                className={`${styles.details}`}
                                items={GroupedDocuments.documents}
                                groups={GroupedDocuments.groups}
                                columns={ColumnsToRender}
                                ariaLabelForSelectAllCheckbox="Toggle selection for all items"
                                ariaLabelForSelectionColumn="Toggle selection"
                                checkButtonAriaLabel="Row checkbox"
                                onRenderDetailsHeader={this._onRenderDetailsHeader}
                                groupProps={{
                                    showEmptyGroups: true
                                }}
                                onRenderItemColumn={this._onRenderColumn}
                                compact={true}
                                selectionMode={SelectionMode.none}
                                styles={DetailsListStyles}
                          />
3. Put a link to this library on some other page (using quick links webpart).
4. Go to the page where you put the link to library, click on the link.
5. The IconButton loads fine on each cell. But when you click on it, the panel opens and in console, you get the below:
Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=A.%20General for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Xl (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at d (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at m (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1
    at ea (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at Oo (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at ko (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at bo (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at po (sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1)
    at sp-pages-assembly_en-us_46805f7878f48f4fe42a07d3e6741d15.js:1
6. However, if you go to the library directly and click on the IconButton on any row, the panel opens and you see the DetailsList.

## Expected behavior

On click of the IconButton, the panel opens and shows DetailsList we have.

## Environment details (*development & target environment*)

SPFx is 1.9, office-ui-fabric-react is 6.189.2. If you put latest version for office-ui-fabric-react, the IconButton itself won't load when we go the library via a link on some other page.

### Additional context

I tried to go to lower versions of office-ui-fabric-react but they don't have DetailsHeader etc. The versions that do have it, give the above error.

**Comment by patmill** [comment]
What DOM element is the details list getting added to?

**Comment by cwdata** [comment]
@patmill 
we are seeing similar problems in a Webpart using UI Fabric <DetailsList>:
Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=page-0
The problem doesn't appear consistently, sometimes it works and sometimes you need to press F5 to avoid the error.
In our case it happens exactly when the List should render items. If there are no items provided the error does not show up. It will appear as soon as there's at least one item to display.
Tried different settings on the DetailsList component - even removed all but the items= setting - but kept getting the same error.
In the DOM the list is placed inside a MarqueeSelection which itself is inside a ScrollablePane. Placing the list directly inside a div without the other 2 elements around also makes no difference.
I found a similar problem report here:
https://docs.microsoft.com/en-us/answers/questions/85293/spfx-list-view-command-set-react-error-invariant-2.html
which is also quite new.
And it doesn't happen on all tenants.
Affected: M365x671637.sharepoint.com (Id: 3897eded-715f-4c4b-bff5-ee508b76d3c5)
NOT affected: snsdev4.sharepoint.com (Id: e76c06ff-f7ae-49a4-ade2-af23ad73ae91)
Both as of 2020-09-24 09:00 UTC

**Comment by RamaKaryam** [comment]
@patmill the DetailsList is inside a <div>. It has some more parent divs. As I mentioned in the original post, all this is rendered inside a Panel via onRenderBody.
