### ISSUE TITLE
Docs on usage of Web.GetFileByUrl method in SharePoint REST API?

### ISSUE THREAD

**Issue by haneef95** [SharePoint/sp-dev-docs#6293]
Hi,

I see that there are docs for using **GetFolderByServerRelativeUrl** and **GetFileByServerRelativeUrl** methods in the SharePoint REST API, however, I couldn't find any docs on using **[GetFileByUrl method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt684226(v=office.15))** with SharePoint REST API.

Could that information be added please?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Actually, Official document didn't list the usage of GetFileByUrl.
This is the sample to use this method, actually it's using the absolute file url like this:

https://tenant.sharepoint.com/_api/web/GetFileByUrl(@url)?@url='https://tenant.sharepoint.com/Shared%20Documents/0%20(7).jpg'

 This is the difference with GetFileByServerRelativeUrl

**Comment by haneef95** [comment]
Thanks @Jerry0527 

I've given it a shot and I'm getting either the FileNotFound or "fileURL" is missing error, I've tried different combinations.

What am I doing wrong here, here's my example:
https://contoso.sharepoint.com/_api/web/GetFileByUrl(@url)?@url='https://contoso.sharepoint.com/teams/TechTeam-Contoso-/Shared%20Documents/General/Email%20Messages/FW%20Phase%201%20Migration%20%20to%20affected%20users_123456.eml'

**Comment by Jerry0527** [comment]
Hi @haneef95,

It seems the file is located at the site url:
https://contoso.sharepoint.com/teams/TechTeam-Contoso-/

Then should like this:
https://contoso.sharepoint.com/teams/TechTeam-Contoso-/_api/web/GetFileByUrl(@url)?@url='https://contoso.sharepoint.com/teams/TechTeam-Contoso-/Shared%20Documents/General/Email%20Messages/FW%20Phase%201%20Migration%20%20to%20affected%20users_123456.eml'
