### ISSUE TITLE
List page with field customizer takes a long time to load

### ISSUE THREAD

**Issue by patrikhellgren** [SharePoint/sp-dev-docs#6294]
## Category

- [x] Bug

## Describe the bug

We have a field customizer that is in the same bundle as a web part. We have the web part on a site page with a link in quick launch (e.g. Home.aspx) and the field customizer is visible in a view in a list that also has a link in quick launch. If I reload the site page and wait until everything is loaded and then go to the list with the field customizer by clicking the menu item so that only a partial page reload is made, there is a really long delay (about a minute) until the list page is fully loaded, A few lines of the list (header and footer?) and the _Toggle selection for all items_ radio button gets loaded and then nothing happens for about a minute and then the rest gets loaded.

This has been working without the delay until recently, we started to notice this about a week ago.

This seems to have something to do with this being a single bundle. If I split the webpart and field customizer up into separate bundles it seems to work as it should.

After the long delay there are several error messages that seem to be identical logged in the console when the rest of the page is loaded:
Uncaught (in promise) Error
    at t [as constructor] (listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1)
    at new t (listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1)
    at Function.e.buildErrorWithVerboseLog (listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1)
    at Function.e.buildLoadPathDependencyError (listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1)
    at listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
    at listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
t @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
t @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
e.buildErrorWithVerboseLog @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
e.buildLoadPathDependencyError @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
(anonymous) @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
(anonymous) @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
Promise.then (async)
g @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
(anonymous) @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
(anonymous) @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
e @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1
(anonymous) @ listview-host-assembly_sv-se_d4b3e8fedfb34c75ded59576c84488b0.js:1

## Steps to reproduce

Create a new SPFx solution with the Yeoman generator and select to create a Field Customizer.
Add a new webpart to the same solution.
Edit config.json to have both components in the same bundle.
Build and deploy to app catalog.
Create a new modern Team Site.
Add the webpart to Home.
Add a new custom list and then add a link to it in quick launch.
Add a field with the field customizer to the list.
Go to Home and do a Ctrl+F5 and wait until the page has finished loading.
Click on the list menu item in quick launch.
Now when the list page loads you will see a very long delay until the page finish loading.

## Expected behavior

A list page with a field customizer should load without delays.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online (seeing this in both targeted and standard release)
- **Framework**: Node.js v10
- **Browser(s)**: Tested with FireFox v80 | IE v11 | Chromium Edge v87
- **Tooling**: VS Code | SPFx v1.11.0
- **Additional details**:

**Comment by AJIXuMuK** [comment]
Sorry @patrikhellgren - lost track of this item due to lacking metadata.

There were a lot of optimizations and rendering changes during the last year.
Could you please check if that's still an issue for you?
From my observations list is loading pretty fast. There is a delay of loading cells for the column that has field customizer (if it has some heavy logic), but nothing more.
