### ISSUE TITLE
SPFx web part error when using twilio flex webchat caused by webpack uglification

### ISSUE THREAD

**Issue by westleyMS** [SharePoint/sp-dev-docs#6297]
## Category

- [x] Bug

## Describe the bug

when adding a webpart to a page with the twilio flex webchat control here-
https://www.npmjs.com/package/@twilio/flex-webchat-ui

we receive this error-
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
[SPLoaderError.loadComponentError]:
***Failed to load component "3db54597-e541-40ea-a5d9-4c469f38f28e" (ChatItHelpWebPart). Original error: ***Failed to load entry point from component "3db54597-e541-40ea-a5d9-4c469f38f28e" (ChatItHelpWebPart). Original error: Super expression must either be null or a function

***INNERERROR:
***Failed to load entry point from component "3db54597-e541-40ea-a5d9-4c469f38f28e" (MyChatWebPart). Original error: Super expression must either be null or a function
***CALLSTACK:
t@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_<>.js:1:1024446
r@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_<>.js:1:1375543
ff4n/d[/e.buildErrorWithVerboseLog@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_<>.js:1:1413493
ff4n/d[/e.buildLoadComponentError@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_<>.js:1:1409524
e/[/[@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_<>.js:1:1403150

## Steps to reproduce

1. Create a webpart using the twilio flex webchat component
2. build and package (--ship) the solution
3. deploy the solution
4. add the webpart to a page

## Expected behavior

Web part shows on page

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: SPFx 1.10.0
- **Browser(s)**: all
- **Tooling**:  SPFx v1.10.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
@westleyMS said:
> Create a webpart using the twilio flex webchat component

Please provide a repro helping others dupe your issue.
