### ISSUE TITLE
Use async method in command set extension

### ISSUE THREAD

**Issue by KodulkarNilesh** [SharePoint/sp-dev-docs#6298]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

Can we use async method in "onExecute" method of Listview command set extension? I am trying to get column values of the selected item. 
![image](https://user-images.githubusercontent.com/63402109/93749239-36ad5d00-fc17-11ea-9abd-90c57711b8b6.png)

## Environment details (*development & target environment*)

Your Developer Environment: Windows 10
Target Environment: SharePoint Online
Framework: Node.js V 8.x
Browser(s): Chrome & Edge
Tooling: VS Code | SPFx v1.11.0

**Comment by KodulkarNilesh** [comment]
I need to get a column value which is not included in the listview.

**Comment by luismanez** [comment]
Just curious. Have you tried to define the onExecute with the async keyword, and then await your call to getListItem ?

**Comment by KodulkarNilesh** [comment]
well. actually not. Not sure if it is a good way modify OOTB methods.

**Comment by KodulkarNilesh** [comment]
I am getting expected result by making the method async.

**Comment by luismanez** [comment]
yeah, I get your concern, as you´re overriding a method provided by the spfx framework. However, the async/await ts are just wrappers around Promises, so I think is fine to do so (I mean, likely the generated javascript has the expected signature, but using Promises inside the method). I´ve seen some of the experts doing something similar with the _componentDidMount_ react event, making it working with async/await...

**Comment by andrewconnell** [comment]
@KodulkarNilesh You can't just override the existing method and make it async. The SPFx engine won't expect it to be so.

This isn't a SPFx issue, rather a scripting question. You can just use the Promise...

```ts
this.getItem().then(result => alert(result);
```

or wrap the call to the async method in a method that doesn't return a promise like,

```ts
public async getItem(): Promise<any> { .. }

public onExecute(): void {
  ... 
  ( async () => {
    let result = await this.getItem();
    ...
  });
}
```

**Comment by KodulkarNilesh** [comment]
hello, 

problem here is that I need to get column values for the selected item in onListViewUpdated() & OnExucte() event in listview command set. Certain operation needs to be done based on the column value.

**Comment by andrewconnell** [comment]
@KodulkarNilesh Great... I see that's what you're trying to do inyour code, you're having trouble calling your async method, so I provided a solution. So... what's your question?

**Comment by KodulkarNilesh** [comment]
@andrewconnell , "Command One" is not visible for me based on the column value. Code looks like below:

![image](https://user-images.githubusercontent.com/63402109/94164427-a7b67400-fea6-11ea-9f51-eb47e0dc5c51.png)

![image](https://user-images.githubusercontent.com/63402109/94164536-c74d9c80-fea6-11ea-9c8e-0c0695fc9308.png)

**Comment by luismanez** [comment]
Thanks @andrewconnell for the correction.

@KodulkarNilesh problem here is that the framework _onListViewUpdated_ method is a sync method, and even with the Promise, once the Promise is resolved, the _onListViewUpdated_ method is already done, and the _commandOne.visible = true_ has no effect. This is the same issue described here: https://github.com/SharePoint/sp-dev-docs/issues/1846 with no solution. The only option here is described by @wobba: you show the Command, and do your validations when is clicked. 
In your scenario, either:
- Add the column to the View
- Create a custom FieldCustomizer, and render a button when your logic decides (yeah, that button will be render for each list item)

In my opinion, this is something to review by the spfx team...

**Comment by luismanez** [comment]
Found also this Open Issue. Apparently there´s a UserVoice request, and also Pat has sent the problem to the team (more than a year ago)...
https://github.com/SharePoint/sp-dev-docs/issues/4449
