### ISSUE TITLE
ColumnFormatter-"editProps"-action does not work in client-side ListView-webpart

### ISSUE THREAD

**Issue by S-e-b-i** [SharePoint/sp-dev-docs#6299]
## Category

- [x] Bug

## Describe the bug

Hello,

I'm not sure if it's already known, but the ColumnFormatter-"editProps"-action
does not work in the client-side ListView-webpart (added for instance on the Home.aspx-SitePage)
(see screenshots below)!

-> Nothing happens when clicking on it. Only a double-click opens the corresponding EditForm
... but in a new browser-tab and not in the right panel as expected! :(

## Expected behavior

When opening the list directly (/MyList/MyView.aspx) the editProps-action works correctly
and opens an overlay-panel on the right side (see second screenshot).

-> It would be great if a  _single click_  on the edit icon  _in the webpart_  would open a panel
instead of a new browser-tab!

## Environment details

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Browsers**: all

## Screenshots

**Home.aspx with WebPart (not working):**
![Screenshot1](https://user-images.githubusercontent.com/71315982/93778558-5304c600-fc26-11ea-8c56-2761b7a824d8.png)

**Standalone List (working):**
![Screenshot2](https://user-images.githubusercontent.com/71315982/93778569-5730e380-fc26-11ea-87ff-0a9d088e3b99.png)

**ColumnFormatter (editProps):**
![Screenshot3](https://user-images.githubusercontent.com/71315982/93778596-5c8e2e00-fc26-11ea-911c-dca71b029677.png)

**Comment by bcameron1231** [comment]
Hi. This is correct. The List View Web Part doesn't have 100% feature parity with the functionality of lists. In this case, editProps functions as the edit form with a slide out panel. There is no slideout panel from the web part page. 

Your option would be to create the Edit link manually.

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "txtContent": "Edit Item",
  "attributes": {
    "href":"='/Sites/<SiteName>/Lists/People/EditForm.aspx?ID='+[$ID]",
    "target": "_blank"
  }
}
```

**Comment by S-e-b-i** [comment]
Hello and thanks for the reply!

Are there any plans to support the "editProps"-action (-> panel) in the near future?
If not: would it be possible that your webpart opens the standalone-EditForm by clicking **once**?
At the moment only a double-click works (-> standalone-page) … what the users might not know
and don't expect. :(

Nice regards!

**Comment by bcameron1231** [comment]
I am not sure. You could submit the enhancement to the SharePoint UserVoice.

The example I showed above works for a single click to get to the edit form. My recommendation is to construct your edit link using JSON column formatting.
