### ISSUE TITLE
RequireJS anonymous define module errors

### ISSUE THREAD

**Issue by mherrema** [SharePoint/sp-dev-docs#630]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
If an SPFX web part is included in a page, it should not break other angular or javascript plugins based on RequireJS changes associated with SPFX.

#### Observed Behavior
As of 6/7/17 - Getting many RequireJS console errors related to various angular plugins that rely on javascript libraries including angular-masonry and angular-moment. Also getting an error when a basically vanilla SPFX web part is included in a page: 
`Uncaught Error: Mismatched anonymous define() module: function (){return t()}
http://requirejs.org/docs/errors.html#mismatch
    at B (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/classic-pages-assembly_en-us_756f9c60d98b16ec539ae8fac4a29cac.js:109:205284)
    at y (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/classic-pages-assembly_en-us_756f9c60d98b16ec539ae8fac4a29cac.js:109:208648)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/classic-pages-assembly_en-us_756f9c60d98b16ec539ae8fac4a29cac.js:109:214637
    at arguments.(anonymous function) (https://static.sharepointonline.com/bld/_layouts/15/16.0.6601.1204/init.js:1:95586)`

<img width="1311" alt="screen shot 2017-06-08 at 5 18 50 pm" src="https://user-images.githubusercontent.com/3245025/26952074-d7a90578-4c71-11e7-9b20-aff43c326953.png">

#### Steps to Reproduce
Unfortunately the issue I'm experiencing is on a government tenant. The best route to troubleshoot would be to look at changes recently deployed, see what might interfere with plugins using Require, or files that might be trying to overwrite plugins already included in a government tenant website. Note, none of these errors were present previous to 7/7/17 as they were breaking changes to the platform that many users reported.

**Comment by mpasarin** [comment]
How are your javascript plugins using RequireJS? I see that the original call comes from init.js, but it seems to not come from the page itself.
Are you running a custom script in the page? Are you trying to load RequireJS by yourself?

I can see from the error that there's a problem with conflicting definitions of the define() method, but what is the change in the experience? Is the page not rendering at all? Are there missing parts of it or unexpected behavior?

We are carefully trying not to break any known scenario, but it seems this scenario was not caught, that's why I want to understand what's the behavior that triggered this.

**Comment by mherrema** [comment]
So honestly I'm not entirely sure how the plugin/library linking goes with the angular plugins I'm using, it's one of those thing that I just dropped in and it worked. I'm actually not sure if they're using RequireJS as much as they might be creating a conflicting definition. I'm not manually loading RequireJS or manipulating it in any way. We're running custom scripts, but nothing more than typical angular controllers, services, a few jquery click handlers, etc. One plugin I'm using is here in case you wanted the code: [angular-moment](https://github.com/urish/angular-moment). 

The error shown above is not breaking the experience, though I believe it to be related to the breaking changes. It breaks as soon as I pull in the angular moment plugin, or masonry. This either kills off angular and prevents rendering of much of the page, or breaks masonry and breaks some of our grid displays. The masonry error is below. The angular moment error is the same error wrapped around the function, the function just isn't minified so it's too big to include here.

<img width="1184" alt="screen shot 2017-06-08 at 9 11 16 pm" src="https://user-images.githubusercontent.com/3245025/26956879-16b6bba8-4c8f-11e7-851b-8c0dbcfba1c1.png">

Please let me know if there are any other questions, I appreciate the fast response.

**Comment by mherrema** [comment]
Note - just tried the web part with a default master page and page layout, and it didn't return the same error. Which implies a conflict. Just wanted to make sure it wasn't an issue with the web part itself.

**Comment by mherrema** [comment]
I believe I have this resolved. Had to do with load order/loading scripts in the head as opposed to the body. Strange that it only became a problem a few days ago though. Anyway, thanks!

**Comment by nickpape-msft** [comment]
Is this issue resolved?

**Comment by mherrema** [comment]
Yes, it's resolved.

**Comment by RafiullahOmar** [comment]
dear mherrema i am also face with almost the same problem,
but with little difference, that my code works fine when i connect with my mobile internet, but when i connect with office internet it does not work and produce the following error:
"
GET http://gis.mail.gov.af/Scripts/jadex/gisAPI/jdxbasemap.min.js 
Error: scriptError
    at d (init.js:5)
    at HTMLScriptElement.<anonymous> (init.js:30)
src: dojoLoader
info: ["/Scripts/jadex/gisAPI/jdxbasemap.min.js", Event]
"
