### ISSUE TITLE
localization JS files have content-disposition: attachment; filename=... HTTP headers

### ISSUE THREAD

**Issue by MartinLaplante** [SharePoint/sp-dev-docs#6302]
## Category

- [x] Bug

## Describe the bug

This is a bit of a mystery that is sometimes making browsers download a JS file rather than execute it.  It happens occasionally at a site that is using ADFS and is not using Office 365 CDN for ClientSideAssets.

While most of the js files in the app's folder under the ClientSideAssets folder in the App Catalog are served with no "content-disposition" http header, the one whose name includes "strings_en-us", created by the SPFx localization code gets served with the http header 
`content-disposition: attachment; filename="(file name).js"
`

When the download dialog occurs the file always has that anomalous value of the content-disposition header.  Since it is difficult to reproduce, I am focusing instead on reproducing the anomalous content-disposition header, which is easy.

In normal use, this has no effect, browsers probably override this header based on other context, but according to the standard they should download the file.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)

## Steps to reproduce

Create a webpart or extension using the [guidance here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts)
There is no need to add languages other than en-us or even enter any strings in the en-US.js file

Use includeClientSideAssets and no CDN so that the assets are deployed in the ClientSideAssets folder of the app catalog

Add and deploy the sppkg in the app catalog

Go to the ClientSideAssets folder and the subfolder corresponding to the app

Use the Chrome F12 network tab or equivalent to monitor http response headers

Click on the file whose name includes "strings_en-us" and note the value of the "content-disposition" header

You will also note that the browser prompts you to download the file.

For comparison, click on a different js file in the same folder.  Those other js files have no content-disposition header and do not prompt to download.

## Expected behavior

either no content-disposition header or content-disposition: inline
and does not prompt to download.

## Environment details (*development & target environment*)

Chrome Version 85.0.4183.102 on Windows 10
SharePoint Online
SPFx, several different version from the past year or two.

### Additional context

I have not seen this on projects that have several real nn-nn.js localization files, only empty en-us.js ones, but I have not done extensive testing of this.

**Comment by MartinLaplante** [comment]
Additional info:  this seems to affect application customizers, not webparts as I had said previously.

**Comment by MartinLaplante** [comment]
Well, I have solved it but the problem is very odd.  It turns out that the length of the file name affects the content-disposition http header in the ClientSideAssets library.  I'm not sure whether the length limit is in the file name or the path, but in my case a file name with a length in the low 80s had the correct header, while the same file with a name length in the high 80s had the wrong header.

The solution was to shorten the part of the file name that I was responsible for.

The underlying problem is probably with SharePoint or IIS, not SPFx.

**Comment by patmill** [comment]
Making our way through old bugs.  We think this might have been addressed earlier this year, and are working to see if it still repros.

**Comment by patmill** [comment]
This looks to be resolved.
