### ISSUE TITLE
Explanation for SitesWithCustomizations.csv is missing

### ISSUE THREAD

**Issue by TuomasPakkanen** [SharePoint/sp-dev-docs#6304]
Explanation for file SitesWithCustomizations.csv is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bac24c2-b3c8-ce42-7844-d00f6e79d96a
* Version Independent ID: d78f672f-ff63-2268-638e-6623ed0d59ea
* Content: [The SharePoint modernization scanner reports](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports)
* Content Source: [docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner-reports.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you elaborate? I don't see any reference to this file on the doc...

**Comment by TuomasPakkanen** [comment]
> Can you elaborate? I don't see any reference to this file on the doc...

Exactly. This file gets output by the modernization scanner, but the docs do not explain what it contains.

**Comment by andrewconnell** [comment]
@jansenbe ?
