### ISSUE TITLE
Syntax for OR conditions not documented

### ISSUE THREAD

**Issue by 8i5i8** [SharePoint/sp-dev-docs#6306]
## Category

- [x] Question
- [ ] Typo
- [x ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

&& is the operator for AND
what is the operator and syntax for OR?

## Environment details (if applicable)

> **DELETE THIS LINE BEFORE SUBMITTING** | *Complete the following (if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission). If this section is not relevant to your issue, please delete it.*

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**
>
> *Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Sorry, there is not enough information in your post. Please re-submit and fill out the issue template and follow the submission guidelines. Thanks!
