### ISSUE TITLE
SharePoint Online custom site giving 404 error and /false in URL

### ISSUE THREAD

**Issue by vikasbansal9888** [SharePoint/sp-dev-docs#6307]
## Category

- [x] Bug

## Describe the bug

> **SharePoint Online custom site giving 404 error and /false in URL** - We are using SPO publishing template site (site collection) having classic pages. Custom SPFx webparts are added on our site. News webparts are not rendered/loaded properly. Issue is with the below two webparts in both IE and chrome browser. They are custom SPFx webpart getting data (JSOM & CAML query) from publishing pages library present at the sub-site level.
They were previously working properly and we haven’t done any changes to them.

In console error is coming as below screenshot. Both direct site collection and direct homepage to it gives error
![image](https://user-images.githubusercontent.com/13880753/93900616-3e522c00-fd13-11ea-9f23-78f0879d5461.png)

![image](https://user-images.githubusercontent.com/13880753/93900684-5033cf00-fd13-11ea-8191-b64dc2dc876c.png)

Even network tab in console is giving error as 404 not found.
![image](https://user-images.githubusercontent.com/13880753/93901798-8756b000-fd14-11ea-9b5a-c972f79bf10f.png)

![image](https://user-images.githubusercontent.com/13880753/93901837-92114500-fd14-11ea-934d-76e270f92bd0.png)

Tried clearing cache memory as well but still error.

## Steps to reproduce

> Steps to reproduce the behavior:

1. Opening our site homepage to by hitting URL in browser

## Expected behavior

> This 404 not found & /false error should get removed so that page can render properly.

## Environment details (*development & target environment*)

> **Environment Details**.

- **Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10.18.0]
- **Browser(s)**: [Chrome | IE v11 | Edge]
- **Tooling**: [VS Code | SPFx v1.9.1]

*Thanks for your contribution! Sharing is caring.*

**Comment by patmill** [comment]
I expect this has something to do with your custom code.  If you remove it, does the problem go away?  It looks like you are changing the current URL / the URL that is navigated to when a link is clicked.

**Comment by vikasbansal9888** [comment]
Complete console error is shown below:
![image](https://user-images.githubusercontent.com/13880753/93975801-96317700-fd95-11ea-8261-f62fc01bea6f.png)

After removing my NEWS webparts /false error still remains but other are removed.

## Please find the news webpart code snippet below:
> ** ExternalLibraries.ts **

`public static LoadDependentLibraries(): JQueryPromise<void> {
        var deferred: JQueryDeferred<void> = $.Deferred<void>();        
        SP.SOD.loadMultiple(["sp.js"], function() {
            SP.SOD.registerSod("sp.taxonomy.js",SP.Utilities.Utility.getLayoutsPageUrl("sp.taxonomy.js"));     
            SP.SOD.loadMultiple(["sp.taxonomy.js"], function() {
                console.log('inner ["sp.taxonomy.js"] loaded');
                deferred.resolve();
            });
        });  
        return deferred.promise();
  }`



> ** TopNewsRender.tsx **


`public componentDidMount(): void {
        try {
            ------------
           $.when(ExternalLibraries.LoadDependentLibraries()).then(() => {
                $.when(TopNewsData.GetData(this.state.take, this.state.TagsOrUrl, this.state.SiteUrl, this.state.Tags))
                    .then((newsData: NewsModel[]) => {
                        if (newsData && newsData.length > 0) {
                            this.setState({
                                TopNewsContent: newsData
                            });
                        }
                    });
            });
            -----------
        }
        catch (e) {
            console.log(e.message);
            console.log(e.stack);
        }
    }
`



> ** TopNewsData.ts **


`public static GetData(take: number, TagOrUrl: string, siteUrl: string, tags: string): JQueryPromise<NewsModel[]> {
           -----------------------
            var context = new SP.ClientContext(siteUrl);
            var list = context.get_web().get_lists().getByTitle("Pages");
            var camlQuery = new SP.CamlQuery();

            let queryString: string = `<View>
                                        <Query>
                                            <Where>
                                                <And>
                                                    <And>
                                                        <Eq>
                                                            <FieldRef Name='ContentType' />
                                                            <Value Type='Computed'>News Article Page</Value>
                                                        </Eq>
                                                        <Eq>
                                                            <FieldRef Name='_ModerationStatus' />
                                                            <Value Type='ModStat'>Approved</Value>
                                                        </Eq>
                                                    </And>
                                                    <Or>
                                                        <Eq>
                                                            <FieldRef Name='IsHighlightedNews' />
                                                            <Value Type='Boolean'>0</Value>
                                                        </Eq>
                                                        <IsNull>
                                                            <FieldRef Name='IsHighlightedNews' />
                                                        </IsNull>
                                                    </Or>
                                                </And>
                                            </Where>
                                        <OrderBy>
                                            <FieldRef Name='ArticleStartDate' Ascending='False'/>
                                        </OrderBy>
                                        </Query>
                                        <RowLimit>` + take + `</RowLimit>
                                    </View>`;
            
            camlQuery.set_viewXml(queryString);
            var items = list.getItems(camlQuery);

            context.load(items, 'Include(Title,ArticleStartDate,FileRef,TagsMultiple,NewsTeaser,PublishingRollupImage)');
            
            context.executeQueryAsync(
                function () {
                    var enumerator = items.getEnumerator();
                    while (enumerator.moveNext()) {
                        var item = enumerator.get_current();
                        
                        let newsItem: NewsModel = new NewsModel();
                        
                        let newsImage = item.get_item('PublishingRollupImage');
                        if (newsImage != null) {
                            var regEx;
                            if (newsImage.indexOf("http://") >= 0) {
                                regEx = /<img[^>]+src="(http:\/\/[^">]+)"/g;
                            }
                            else if (newsImage.indexOf("https://") >= 0) {
                                regEx = /<img[^>]+src="(https:\/\/[^">]+)"/g;
                            }
                            else {
                                regEx = /<img[^>]+src="(\/[^">]+)"/g;
                            }
                            var src = regEx.exec(newsImage);

                            if (src != null) {
                                newsItem.NewsImage = src[1];
                            }
                        }

                        let newsArticleStartDate = item.get_item('ArticleStartDate');
                        if (newsArticleStartDate != null) {
                            newsItem.NewsDate = new Date(newsArticleStartDate).toLocaleString("en-GB", { month: 'short', year: 'numeric', day: 'numeric' });
                        } else {
                            newsItem.NewsDate = new Date(0).toLocaleString("en-GB", { month: 'short', year: 'numeric', day: 'numeric' });
                        }
                        newsItem.NewsLink = item.get_item('FileRef');

                        newsItem.NewsTags = "";
                        newsItem.NewsTeaser = "";
                        
                            var newsTags = item.get_item('LEOTagsMultiple');
                            for (var i = 0; i < newsTags.get_count(); i++) {
                                var newsTag = newsTags.getItemAtIndex(i);
                                if (newsItem.NewsTags.length > 0) {
                                    newsItem.NewsTags = newsTag.get_label() + "; " + newsItem.NewsTags;
                                }
                                else {
                                    newsItem.NewsTags = newsTag.get_label();
                                }
                            }
                            newsItem.NewsTeaser = item.get_item('LEONewsTeaser');

                        newsItem.NewsTitle = item.get_item('Title');
                        news.push(newsItem);
                    }

                    deferred.resolve(news);
                },
                function (sender, args) {
                    console.error('Error: ' + JSON.stringify(args));
                    deferred.resolve(news);
                }
            );
        return deferred.promise();
    }
`


Please provide guidance on this issue. Do I need to modify the code?

**Comment by patmill** [comment]
It's the rendering that would be causing problems / interacting with the DOM / etc.  This just looks like data fetching.

**Comment by vikasbansal9888** [comment]
Yes, I'm fetching data and showing it in SPFx webpart.

I have found that individual webpart works, but **/false** error still remains

If two (or more) webparts are added which are getting from Pages library using JSOM & CSOM gives same error.

**Comment by vikasbansal9888** [comment]
Hi,
Can you please suggest something on this issue.

**Comment by AJIXuMuK** [comment]
Hi @vikasbansal9888,

Seems like `siteUrl` gets the `/sites/false` value somewhere.
Could you please debug this part and see if you're passing the correct `siteUrl` to the CSOM?
