### ISSUE TITLE
Unable to debug the spfx solution when we try to use gulp serve or gulp serve --nobrowser

### ISSUE THREAD

**Issue by swetha0702** [SharePoint/sp-dev-docs#6308]
Hi Team,

We are unable to debug spfx solution when we tried using gulp server or gulp server --nobrowser. Getting  below error:

![image](https://user-images.githubusercontent.com/71710977/93912008-cd197580-fd20-11ea-949e-101857c741d9.png)

Also we tried to debug in browser for the production site by adding the url as  "debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js&loadSPFX=true&customActions=%7B%221dc03dd9-2637-40c6-97e3-abe78d875228%22%3A%7B%22location%22%3A%22ClientSideExtension.ApplicationCustomizer%22%2C%22properties%22%3A%7B%22testMessage%22%3A%22Test+message%22%7D%7D%7D ", this works sometimes after system restart but fails most of the times.
This is critical for fixing a production issue. Kindly request your help in how we can debug

**Comment by patmill** [comment]
What shows up in the "technical details"?  Anything in the console?

**Comment by Jerry0527** [comment]
Make sure you have configure SPFX development environment correctly:

[Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

And you can try to create a default SPFX solution with yo @microsoft/sharepoint and directly running gulp serve to see if it works.
