### ISSUE TITLE
SPFx webpart loading error: "There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate."

### ISSUE THREAD

**Issue by aaronmi** [SharePoint/sp-dev-docs#6309]
## Category

- [x] Bug

## Describe the bug

We have the same issue as #3871 but unfortunately it was closed.
Any updates on how to fix it ?

![image](https://user-images.githubusercontent.com/11667890/93917937-7ed48a00-fcc0-11ea-9d02-01eb93473c51.png)

This only happening with IE11
![image](https://user-images.githubusercontent.com/11667890/93918103-bcd1ae00-fcc0-11ea-99f9-2b1c535cd725.png)

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Browser(s)**: [IE v11]
- **Tooling**: [VS Code | SPFx v1.11.0]

### Additional context

Network trace shows the file actually get loaded.
![image](https://user-images.githubusercontent.com/11667890/93918852-c9a2d180-fcc1-11ea-85a0-2b31c54e1f86.png)
However, SPFx webpart caught the loading error.

Manifest:
![image](https://user-images.githubusercontent.com/11667890/93919211-37e79400-fcc2-11ea-927a-104adff7cee1.png)

**Comment by aaronmi** [comment]
Why http HEAD is used instead GET with IE11?
HEAD /xxx.sharepoint.com/sites/EE/ClientSideAssets/137ac681-8f42-4ca2-a918-375570d72e61/collage-web-part_494204d025acb4540f24f0231a02e064.js

**Comment by aaronmi** [comment]
Same issue:
https://github.com/SharePoint/sp-dev-gdpr-activity-hub/issues/51
https://github.com/SharePoint/sp-dev-docs/issues/3871

**Comment by btohme** [comment]
same issue on sp2019, any updates!?

**Comment by patmill** [comment]
Closing this one down, as IE support is deprecated, and additionally (in this particular case) it would have been a cert issue with the public CDN host (resolved)
