### ISSUE TITLE
[MS Ignite] Support multiple SSO domains on Teams app ?

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-docs#6313]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Regarding the documentation on [SSO on Teams apps](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso), are there plans to support multiple domains for SSO and if so, is there an ETA on this ?

This could be interesting in a scenario where you would be able to SSO login to SP pages & a custom web app (e.g. our own custom app service showing a landing page, with content redirecting to SP pages).

**Comment by andrewconnell** [comment]
I think MS said that they are working on adding SSO support (like that which exists in Teams & Office Addins) to SSO, but not sure what the ETA is on this.
