### ISSUE TITLE
[MS Ignite] ETA on Teams SSO support for the .azurewebsites.net domain ?

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-docs#6314]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Is there an ETA that can be shared on the Teams SSO support for the .azurewebsites.net domain ?

From the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso):

> We don't support applications that use the azurewebsites.net domain because it is too common and may be a security risk. However, we're actively seeking to remove this restriction.

**Comment by A-Ghorab** [comment]
yes this is critical for us after using the SSO and deploying we found that we can't use azurewebsites so we are reverting back to adal but it isn't as smooth as SSO

**Comment by PieterHeemeryck** [comment]
> yes this is critical for us after using the SSO and deploying we found that we can't use azurewebsites so we are reverting back to adal but it isn't as smooth as SSO

@A-Ghorab You can use SSO for your web app, but you must pay for your own domain name instead of the default azurewebsits.net domain. e.g. myapp.com would work.

**Comment by A-Ghorab** [comment]
> 
> 
> > yes this is critical for us after using the SSO and deploying we found that we can't use azurewebsites so we are reverting back to adal but it isn't as smooth as SSO
> 
> @A-Ghorab You can use SSO for your web app, but you must pay for your own domain name instead of the default azurewebsits.net domain. e.g. myapp.com would work.

yes but for our staging and development we were using CI/CD on the development environment only the production on will have a custom domain so it will be working normal but for testing we had to revert back to the normal way until SSO is fixed for Azure domains.

**Comment by andrewconnell** [comment]
This issue list is for general SharePoint development topics, but this seems to be about SSO & Teams, not SharePoint.
