### ISSUE TITLE
Field customizer in view makes that the new top bar Search quite often does not complete (eternal loading animation)

### ISSUE THREAD

**Issue by oliverlp** [SharePoint/sp-dev-docs#6318]
## Category

- [x] Bug

## Describe the bug
If you have a document library view with a field, and that field has a HelloWorld FieldCustomizer (new project SPFx 1.11.0), and then you use the new modern searchbox in the top bar then the search quite often never completes. You get the loading animation and it does not end.

The same applies to SPFx 1.11.0 and SPFx 1.9. both in targeted release tenants and not targeted.

I have also observed that even with plain vanilla sites with no customization, every time I use Search, an error appears in the Console. I wonder if that exception is the cause of problem when later a field customizer is added.

Uncaught (in promise) Canceled: Unmounted at t.r (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.odsp-common.chunk.js:2:483548) at t [as constructor] (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.odsp-common.chunk.js:2:482716) at new t (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.odsp-common.chunk.js:2:49324) at https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.items-view.chunk.js:1:490845 at vo (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.react.chunk.js:2:76135) at yo (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.react.chunk.js:2:77871) at qo (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.react.chunk.js:2:81997) at Xo (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.react.chunk.js:2:85577) at https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.react.chunk.js:2:98817 at Object.t.unstable_runWithPriority (https://spoprod-a.akamaihd.net/files/odsp-next-prod-webpack_2020-09-11-sts_20200915.001/splistwebpack/plt.odsp-common.chunk.js:2:310125)

Has anyone seen this problem? Ideas?

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. Add a site column “Field1” (for ex. Text), add the field the Documents library default view .
2. Create a SPFx 1.11.0 solution with yo with a HelloWord field customizer and deploy it tenant wide. It will show “Hello world” instead of the field value.
3. Associate the field to the customization.
4. Add a few documents to the library
5. Navigate to Home, then to Document and write something in the new modern search box on the top bar. In some cases the search experience will not complete and the animation is on and on.
Try navigation between those 2 pages and trying to search and quite often you get that situation.

## Expected behavior
The search completes even if there are field customizations.

## Environment details (*development & target environment*)
- Windows 10
- SharePoint Online
- Node.js v10
- Chrome | Edge
-  VS Code | SPFx v1.11.0

**Comment by AJIXuMuK** [comment]
Hi @oliverlp,
Sorry for the long delay.
Could you please check if that's still an issue on your end?
Thanks!
