### ISSUE TITLE
Error when testing new SPFx web part in online workbench

### ISSUE THREAD

**Issue by tommyvanhee** [SharePoint/sp-dev-docs#632]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm trying to create a new client-side web part using the latest release of SharePoint Framework, however I get errors when running it inside the online Workbench. I'm using a dev tenant. Local workbench works fine.

#### Observed Behavior
I get these error details: seems like a missing package in the online environment.
```
TECHNICAL DETAILS
***ERROR MESSAGE:
***Failed to load component "32e3c107-49e2-4d28-a097-95ebc025f790" (TestWebPart).
Original error: ***Manifest not found for component id "c07208f0-ea3b-4c1a-9965-ac1b825211a6" and version "1.1.1".

***CALLSTACK:
Error: ***Failed to load component "32e3c107-49e2-4d28-a097-95ebc025f790" (TestWebPart).
Original error: ***Manifest not found for component id "c07208f0-ea3b-4c1a-9965-ac1b825211a6" and version "1.1.1".
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:198039
    at <anonymous>
```
#### Steps to Reproduce
1. Create a new project using the yeoman generater with a React web part.
2. Run gulp serve.
3. Open online workbench

**Comment by patmill** [comment]
@mpasarin - Can you take a look at this?

**Comment by seaSide974** [comment]
Hi

I also got a similar error : 
- webpart created under 1.0.0 version
-debug mode worked fine for local workbench and o365 workbench
-1.1.1 came out, seems like i cant debug anymore o365 workbench (got similar error)
-I am updating my webpart to 1.1.1 now, see if it helps, that is why i cant share the error details

**Comment by vman** [comment]
I am getting this as well. In addition, here are the local and global npm package versions I am using:

![image](https://user-images.githubusercontent.com/173794/26997433-823d80ea-4d71-11e7-8381-7a9a68f7f538.png)

**Comment by patmill** [comment]
Yes, sorry for not updating this thread.  The fix is understood and going through validation rings.  It should be out soon if all goes well (today).

________________________________

**Comment by JeremyKelley** [comment]
To elaborate on Pat's update we expect the fix to be server side only, you shouldn't need to further update your packages for the Workbench to start working again.

**Comment by patmill** [comment]
Should be fixed now.

________________________________

**Comment by tommyvanhee** [comment]
Fixed indeed. Tnx!

**Comment by pauldalyii** [comment]
I think I am seeing this issue (or one very similar).  Is it possible the update hasn't finished rolling out yet?

```
[SPLoaderError.loadComponentError]:
***Failed to load component "36ee92d5-853d-4fe2-b336-dac244538ff6" (PublishAppsWebPart).
Original error: ***Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version **"15.6.1"**.

***INNERERROR:
***Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version **"15.6.1"**.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.012/sp-pages-assembly_en-us_38d46b82c30234ea57778fa6f0a411d0.js:351:10483)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.012/sp-pages-assembly_en-us_38d46b82c30234ea57778fa6f0a411d0.js:911:17735)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.012/sp-pages-assembly_en-us_38d46b82c30234ea57778fa6f0a411d0.js:911:14892)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.012/sp-pages-assembly_en-us_38d46b82c30234ea57778fa6f0a411d0.js:911:12701)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-07.012/sp-pages-assembly_en-us_38d46b82c30234ea57778fa6f0a411d0.js:911:111188
    at <anonymous>
```

**Comment by Debbledon** [comment]
What was actually done to fix this?

**Comment by Debbledon** [comment]
@patmill , 

Can you please share what was actually done to fix this?

I am experiencing the exact same issue and need to be able to explain to the server administrators what will need to be done.

Thank you.
