### ISSUE TITLE
API for copying documents from one sharepoint to another

### ISSUE THREAD

**Issue by Oiesof** [SharePoint/sp-dev-docs#6322]
Hello,

I am new to SharePoint (and GitHub for that matter). I am working With RPA and we have a process that copies document from one SharePoint to other SharePoints (in total 10 different SharePoints). Typically, the mother Company adds new documents to SharePoint which in turn should be copied to the daughter companies (not completely accurate example, but you might get the point). I have been using graphical user Interface (GUI) for this process so far, and I struggle with lots of errors and problems. I am wondering if there are any APIs that might work? So that I can replace GUI with API. 

In advance, thank you.

Kind regards,
Sofie

**Comment by andrewconnell** [comment]
Probably best to look at using the Microsoft Graph: https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http
