### ISSUE TITLE
GetClientSideWebParts api missing ListWebPart

### ISSUE THREAD

**Issue by OverkillTV** [SharePoint/sp-dev-docs#6323]
## Category

- [x] Bug

## Describe the bug

The GetClientSideWebParts API doesn't return ListWebPart in its response.

## Steps to reproduce

1. Access the api [Site]/_api/web/GetClientSideWebParts
2. Observe that there is no value for ListWebPart (ID: f92bf067-bc19-489e-a556-7fe95f508720)

## Expected behavior

[Site]/_api/web/GetClientSideWebParts returns value for f92bf067-bc19-489e-a556-7fe95f508720

## Environment details (*development & target environment*)

SharePoint Online

**Comment by asimmon** [comment]
We are also experiencing this behavior - the list modern web part is not returned by the API and this causes problems on our end.

**Comment by andrewconnell** [comment]
I heard that MSFT engineering is aware of this & they are investigating.

*FYI - they'll update this thread if they have an update*

**Comment by jansenbe** [comment]
The root cause of the problem has been found and a fix is rolling out soon.

**Comment by jansenbe** [comment]
Think we can close, there's many independent confirmations the issue is fixed
