### ISSUE TITLE
SPFx React Checkbox issue

### ISSUE THREAD

**Issue by Namrata99sah** [SharePoint/sp-dev-docs#6324]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

I have a PNP search template with customization, there is one checkbox. After searching a item the search results are there and there is a button to relate the items. after searching the results give the original item and the related items. If i check the origional items check box, it gives one message that "You cant relate an item to itself" and the checkbox should get cleared(ideal case). But the check box is not getting cleared. 

in the UI the checkbox is checked but in code via a boolean variable its disabled. Please help to clear the Checkbox. Its Fluent UI checkbox.

**Comment by andrewconnell** [comment]
Unclear... this sounds like you're talking about Office UI Fabric React. Correct? If so, I think the question should be directed to their forums as this isn't a SharePoint issue: https://github.com/microsoft/fluentui

If not, please use the form for a new issue question that was provided when you submitted your question. It provides additional context for people to help you.
