### ISSUE TITLE
Are the webApiPermissionRequests delegated permission requests?

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#6325]
## Category

- [ x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hi
I am trying to convert a doc/excel file in a sharepoint site to pdf and upload the file to an external API. I am using the MSGraphClient for accessing the graph api endpoint for pdf conversion (/drives/${driveId}/items/${driveItemId}/content?format=pdf).
To read the file I added Files.Read.All permission.
![image](https://user-images.githubusercontent.com/25546855/94773083-e1263c80-03dc-11eb-99d3-fdb3c2bbdfda.png)

What I cannot find for sure is that, is this permission a delegated permission or not. I read the following doc:
<a href='https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient'>https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient</a>
What I understand is these requests impersonate a user but I am not sure if it is the same thing as delegated permissions. Could anyone please clarify whether these permissions are delegated permission or not as per azure AD context.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome v79
- **Tooling**:VS Code | SPFx v1.10.0
- **Additional details**: Graph client permission request in Spfx ContextMenu Extension

**Comment by Jerry0527** [comment]
Files.Read.All is Delegated permissions:

![Snipaste_2020-10-01_16-07-33](https://user-images.githubusercontent.com/28797671/94784115-417aa580-0400-11eb-92c6-a9df8ecf6b5d.png)
Reference:

[Microsoft Graph permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference)

**Comment by RafatRashid** [comment]
But there's also this.
![Screenshot 2020-10-01 141152](https://user-images.githubusercontent.com/25546855/94784556-256f0800-03f0-11eb-93ce-321c7a3f1fd9.png)

**Comment by Jerry0527** [comment]
SPFX solution needs user log in and then perform file read, so it's delegated permissions, please check out the explaination about the difference between Delegate and Application Permissions:

[Azure AD App Application Permissions vs Delegated Permissions](https://stackoverflow.com/questions/31404128/azure-ad-app-application-permissions-vs-delegated-permissions)
