### ISSUE TITLE
Add solution directly to New menu

### ISSUE THREAD

**Issue by Henke-visual** [SharePoint/sp-dev-docs#6326]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is it possible to add you app directly to the New menu?
**New - App Name**, or is this reserved for Microsoft products only?
![image](https://user-images.githubusercontent.com/63777424/94783725-6275d300-03cd-11eb-9e9a-999fdab2fa46.png)

Currently we have to go to **New - Page - select Apps-tab - App Name**.
![image](https://user-images.githubusercontent.com/63777424/94783346-d82d6f00-03cc-11eb-8b00-8b184661b1a0.png)   ![image](https://user-images.githubusercontent.com/63777424/94783945-bb456b80-03cd-11eb-9222-80d6ba4ea670.png)

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: 
- **Browser(s)** :ANY
- **Tooling**: SPFx v1.10.0
- **Additional details**:

**Comment by andrewconnell** [comment]
No, that's not currently supported.
