### ISSUE TITLE
RenderListDataAsStream does no longer return available choices for lookup fields

### ISSUE THREAD

**Issue by florianwachter** [SharePoint/sp-dev-docs#6327]
## Category

- [x] Bug

## Describe the bug

The following REST API used to return all columns in a form including all available Choices for lookup fields. These values are no longer present in the response.

`POST: 
https://company.sharepoint.com/sites/yoursite/_api/web/GetList(@listUrl)/RenderListDataAsStream?@listUrl=%27%2Fsites%2Fyoursite%2FLists%2Fyourlist%27

HEADERS:
{
                    'Accept': 'application/json;odata=verbose',
                    'Content-type': 'application/json;odata=verbose',
                    'X-SP-REQUESTRESOURCES': 'listUrl=' + encodeURIComponent(listUrl),
                    'odata-version': '',
}

BODY
{
                    parameters: {
                        __metadata: {
                            type: 'SP.RenderListDataParameters',
                        },
                        AddRequiredFields: true,
                        ViewXml: '<View><ViewFields><FieldRef Name="ID"/></ViewFields></View>',
                        RenderOptions: 64
                    }
}
`

RenderOption 64 means ClientFormSchema (Returns the client form schema to add and edit items).

Up until yesterday this was working fine, all the lookup values were present in the response, but now this is no longer the case. It still works fine on tenants with standard release and also on most with target release, but on some it doesn't. 

Expected response:

...
ClientForms: {
New: {
ContentTypeName: [
{
AllowMultipleValues: false
ChoiceCount: 32
**Choices: [{LookupId: 1, LookupValue: "lookup value 1"},…]**
...

The highlighted values (Choices) are no longer part of the response. There are still there for choice columns, but no longer for lookup columns.

## Steps to reproduce

Use the REST api call above on a SharePoint list that has a lookup column added to the form and verify the data in the response. As I mentioned above, it works on some tenants, but not on others.

## Expected behavior

The REST api call above should also return the lookup values in the Choice attribute of the response JSON.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Same in all browsers: tested with Chrome, Edge, Firefox
- **Tooling**: SPFx v1.11.0
- **Additional details**: Looks like it's still working on tenants with standard release and also on some with target release, but on one of my customers tenant, it stopped working this week.

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by chr-sad** [comment]
We experienced the same. But I think this feature won't come back, we already changed our code. See the following release notes:
https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-august-2020/

![image](https://user-images.githubusercontent.com/65161973/95305404-356e6800-0886-11eb-8e18-484bef6e8b8b.png)

There is a new API for Lookups which supports pagination so I think this change was made by design to improve performance and support large Lookups as well.

**Comment by florianwachter** [comment]
> We experienced the same. But I think this feature won't come back, we already changed our code. See the following release notes:
> https://developer.microsoft.com/en-us/sharepoint/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-august-2020/
> 
> ![image](https://user-images.githubusercontent.com/65161973/95305404-356e6800-0886-11eb-8e18-484bef6e8b8b.png)
> 
> There is a new API for Lookups which supports pagination so I think this change was made by design to improve performance and support large Lookups as well.

Thanks Christoph,
We also changed our code in the meantime. I agree that the change makes sense to improve performance, but I was hoping that Microsoft would add a new input parameter and not change the response for the same request data or at least add it to the release notes.

Thanks again, Florian

**Comment by chr-sad** [comment]
@florianwachter I totally agree with you. I was hoping the same - our solution was broken like yours and we had to create a fix asap  because of changes on an existing API without prior notifications or infos on that.

**Comment by paulthorpe** [comment]
Also facing the same issue.  I am trying to apply a fix but can anyone offer any pointers on how to get the choices back via the API currently I can't seem to find what steps I would need to take to get the choices for a Lookup field.

**Comment by florianwachter** [comment]
@paulthorpe: We used GetLookupFieldChoices instead.
/_api/web/lists(guid'${lookupListId}')/GetLookupFieldChoices(targetFieldName='${lookupField}',pagingInfo='')

I hope this helps.

Florian

**Comment by paulthorpe** [comment]
@florianwachter thanks.  Is GetLookupFieldChoices documented anywhere I cant seem to find it. When I make the call I am getting a 405 (Not allowed) status.

**Comment by monkeyibrowstudios** [comment]
GetLookupFieldChoices is the recommended and supported way to get lookup items

**Comment by kongmengfei** [comment]
Hi florianwachter,

I tested this issue with below request, it seems that the response contains those choices:

![image](https://user-images.githubusercontent.com/57654821/97417234-60f2e880-1942-11eb-98e7-73d12a096b11.png)

Endpoint:
`_api/Web/Lists(guid'916f8af8-83ca-4d1b-abff-ab7682f97cdb')/RenderListDataAsStream`

Body:

```
{
  "parameters": {
    "AddRequiredFields": "true",
    "DatesInUtc": "true",
    "RenderOptions": 64
  }
}
```
Baker Kong
Microsoft SharePoint Community Support

**Comment by florianwachter** [comment]
@kongmengfei:
Yes, it looks like the Choices are back. This was not working for the last 4 weeks or so.

Thanks, Florian

**Comment by garrytrinder** [comment]
> I tested this issue with below request, it seems that the response contains those choices

@kongmengfei whilst working with a customer today we observed that this is no longer the case, that Choices are no longer being returned by the RenderListDataAsStream endpoint and breaking the functionality of the web part that is using it, this is still an issue.
