### ISSUE TITLE
Error - No compatible version found: @microsoft/decorators@~1.0.1

### ISSUE THREAD

**Issue by patmill** [SharePoint/sp-dev-docs#633]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

Copying from https://twitter.com/alexaterentiev/status/873028053919608836

Is anyone else seeing this error?  Alex - can you describe how you got to your current state?  What version of the @microsoft/generator-sharepoint do you have?  What does your package.json file look like?  Did you delete your node_modules folder before running npm install?

**Comment by AJIXuMuK** [comment]
Thanks Pat for creating the issue.
Initial error was:
```npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microsoft/decorators@~1.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@microsoft/sp-application-base'
```

I was able to fix it by updating versions in package.json:
```
@microsoft/sp-webpart-base: ~1.1.0 -> ~1.1.1
@microsoft/sp-listview-extensibility: ~0.1.0 -> ~0.1.1
@microsoft/sp-application-base: 1.1.0 -> 1.1.1
```

So, I believe the issue may be closed

**Comment by thechriskent** [comment]
I was also receiving this value when creating an **Extension** component of type **Field Customizer** with **No JavaScript framework**.

Here is the full error I received:
```
649 verbose stack Error: No compatible version found: @microsoft/decorators@~1.0.1
649 verbose stack Valid install targets:
649 verbose stack 1.1.0, 1.0.0, 0.2.1, 0.0.0
649 verbose stack
649 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
649 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
649 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
649 verbose stack     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
649 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:233:18
649 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
650 verbose cwd C:\Users\ckent\Dropbox\Documents\Projects\Allegient\Internal\Internal Projects\SPFx\field-extension
651 error Windows_NT 10.0.10586
652 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--cache-min" "86400"
653 error node v6.9.1
654 error npm  v3.10.8
655 error code ETARGET
656 error notarget No compatible version found: @microsoft/decorators@~1.0.1
656 error notarget Valid install targets:
656 error notarget 1.1.0, 1.0.0, 0.2.1, 0.0.0
657 error notarget This is most likely not a problem with npm itself.
657 error notarget In most cases you or one of your dependencies are requesting
657 error notarget a package version that doesn't exist.
657 error notarget
657 error notarget It was specified as a dependency of '@microsoft/sp-application-base'
```
Just to make sure, I attempted to generate an ApplicationCustomizer as well since I verified that the one I made the other day had the same package.json values and it too failed with the same error. 

I checked the version of the generator I had
```
npm list -g @microsoft/generator-sharepoint
```
and saw that I had **1.1.0**

Viewing the versions available
```
npm view @microsoft/generator-sharepoint versions
```
showed that **1.1.1** was the latest, so I installed it:
```
npm install -g @microsoft/generator-sharepoint
```

I ran the generator again and this time it worked! I took a look at the new package.json and found the dependencies had indeed changed:

### New package.json dependencies:
```
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.1",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "@microsoft/sp-listview-extensibility": "0.1.1",
    "@microsoft/sp-application-base": "1.1.1"
  },
```
### Failed package.json dependencies (that worked just a few days ago)
```
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "@microsoft/sp-listview-extensibility": "0.1.0",
    "@microsoft/sp-application-base": "1.1.0"
  },
```

I'm not sure what broke the previous version, but upgrading your generator should fix the issue.

**Comment by nickpape-msft** [comment]
This issue should be resolved by upgrading your package.json, the generator, and cleaning and reinstalling your node modules. You can run "npm outdated" to see which packages need to be upgraded.
