### ISSUE TITLE
How to detect if a web part is running as "single part app page"?

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6332]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is it possible to tell if a web part is running in "[single page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages)" mode? I.e. programmatically, with javascript.

For example, to detect if the part is running full-width, there is [formFactor](https://docs.microsoft.com/en-us/javascript/api/sp-webpart-base/basewebpartcontext?view=sp-typescript-latest#formfactor) Or maybe the "formFactor" property is providing exactly this information?

## Environment details (*development & target environment*)
- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v79]
- **Tooling**: [SPFx v1.11.0]

**Comment by bcameron1231** [comment]
Someone may correct me, but I don't think this is available via the page context. However, you can use the page context to query the current page to get the PageLayoutType.

1. Retrieve the ID from the page context
`this.context.pageContext.listItem.id`
2. use this id to query your site pages library
`/_api/web/lists/getbytitle('Site Pages')/items(this.context.pageContext.listItem.id)?$select=PageLayoutType`

A Single Part App Page would have a PageLayoutType of "SingleWebPartAppPage"

**Comment by nbelyh** [comment]
Thanks!
