### ISSUE TITLE
How do I specify preview for an app in a single page mode?

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6336]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
It is now possible to specify an icon for an application using single page configuration using fullPageAppIconImageUrl
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/configure-web-part-icon#to-set-the-single-part-app-page-preview-image

How do I set the preview page?
I mean, normally pages have text on the right side, but now there is only description that is basically short plain text. How do I put something similar to the built-in pages? Is something like "fullPageAppDescriptionPageUrl" available (please see the screenshot)

![image](https://user-images.githubusercontent.com/528366/94944929-3d22bb00-04da-11eb-8e9c-31e9d12d1acc.png)

Now this area is basically empty (or occasionally shows some random error about some missing component)

## Environment details (*development & target environment*)

- **Tooling**: [SPFx v1.11.0]

**Comment by andrewconnell** [comment]
The preview _(where your ??? are in the screenshot)_ is a live rendering of the component.

**Comment by nbelyh** [comment]
@andrewconnell thank you for the response.
Could you please give more details (or where can I look for them) - what is "live rendering"?
Or maybe you mean I should see my SPFx web part there (is it called with some specific parameters maybe - which method?)

Jus to be clear, you get to this page from the site Home page using New => Page => Apps ("single page app")

**Comment by andrewconnell** [comment]
I mean SharePoint renders the web part and uses that as the preview. IOW, you don't have to do anything. Here's one I created in my course... I didn't specify anything special... that preview rendering is what SharePoint generates by running my web part.

![image](https://user-images.githubusercontent.com/2068657/95115863-27003f00-0714-11eb-8cf2-309d7e3dd77c.png)

If you aren't seeing that or getting an error, please provide a repro to assist further.

**Comment by nbelyh** [comment]
Could you share a link to the course (or code sample)?

**Comment by andrewconnell** [comment]
You can learn more about my course here: https://www.voitanos.io/course-master-sharepoint-framework

If you watch the video on the documentation page you linked to, it shows the web part loading.

@nbelyh said:
> For me, the right area is either blank, or just shows some error (like "component with guid "{bla-bla-bla}" not found".

Sorry, but that's not much to go on... like I said, please provide a repro to your error.

**Comment by nbelyh** [comment]
@andrewconnell Thank you for the link. I see. 
Looks like it should show the web part by default (i.e. "Hello World" web part is visible in examples).
So probably something is wrong either with my web part, or my site. Thank you!

**Comment by nbelyh** [comment]
@andrewconnell I have verified it. It does not seem to work with the current version of SharePoint online. I have tested on two newly created sites (a group site and a collaboration site). I just get a javascript error in the console from the page that is supposed to host the web part:

![image](https://user-images.githubusercontent.com/528366/95118851-436b9e00-074b-11eb-8502-2a8f6cc8011c.png)
```
Uncaught SyntaxError: Unexpected token , in JSON at position 1633
    at JSON.parse (<anonymous>)
    at AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:254
    at AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:320
(anonymous) @ AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:254
(anonymous) @ AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:320
```

The JSON it cannot parse is  (it breaks at "\r\n") here:
```
, spClientSidePageContext = JSON.parse('{"user" : {"@odata.context":"https://unmanagedvisio.sharepoint.com/a/_api/$metadata#Users/$entity","@odata.type":"#SP.User","@odata.id":"https://unmanagedvisio.sharepoint.com/_api/Web/GetUserById(12)","@odata.editLink":"Web/GetUserById(12)","Id":12,"IsHiddenInUI":false,"LoginName":"i:0#.f|membership|nbelyh@unmanagedvisio.onmicrosoft.com","Title":"Nikolay Belykh","PrincipalType":1,"Email":"nbelyh@unmanagedvisio.onmicrosoft.com","Expiration":"","IsEmailAuthenticationGuestUser":false,"IsShareByEmailGuestUser":false,"IsSiteAdmin":true,"UserId":{"NameId":"1003000085840810","NameIdIssuer":"urn:federation:microsoftonline"},"UserPrincipalName":"nbelyh@unmanagedvisio.onmicrosoft.com"},"page" : {\r\n                "DoesUserHaveEditPermission" : false,\r\n                "Content" : {"CanvasContent1":"{\\r\\n  \\"addedFromPersistedData\\": \\"False\\",\\r\\n  \\"controlType\\": 3,\\r\\n  \\"id\\": \\"bd983d77-6c7d-4d0b-ba07-9141dd146d16\\",\\r\\n  \\"webPartData\\": {\\r\\n    \\"id\\": \\"9a9646e2-306f-4a6a-8122-cf038fc32ce5\\",\\r\\n    \\"instanceId\\": \\"bd983d77-6c7d-4d0b-ba07-9141dd146d16\\",\\r\\n    \\"title\\": \\"Visto Plan\\",\\r\\n    \\"description\\": \\"
```

The steps basically are:
- use yeoman generator to create a new sharepoint "HelloWorld" app.
- Enable full page in manifest `"supportedHosts": ["SharePointWebPart", "SharePointFullPage"],`
- Try to add the page: there is no preview, but just this javascript error in the console.

Would be happy if you could check it.

**Comment by nbelyh** [comment]
@andrewconnell Can I file another issue as a possible bug with these details?

**Comment by nbelyh** [comment]
https://github.com/SharePoint/sp-dev-docs/issues/6343
