### ISSUE TITLE
Cannot view publiccdn.sharepointonline.com in sources/chrome after enabling CDN

### ISSUE THREAD

**Issue by savannahp** [SharePoint/sp-dev-docs#6341]
## Category

- [x] Bug

## Describe the bug

I enabled CDN just like it said in the documentation, then shipped and packaged the files. When I get to the end of this page where it says  

"Open your browser's development tools and open the Sources tab.

Extend publiccdn.sharepointonline.com under the source and notice how the hello-world-web-part file is loaded from the Public CDN URL pointing dynamically to a library located under the app catalog site collection."

Even though I have enabled CDN, I still only see it in the my tenant client side. The publiccdn.sharepointonline.com is not in there at all in my chrome source. 
![image](https://user-images.githubusercontent.com/42783981/95113217-58224480-06ff-11eb-811d-cc24b532a7db.png)

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. gulp bundle --ship
2. gulp package-solution --ship
3. upload the new helloworld-webpart.sppkg
4. open browsers dev tools and go to sources, look for public

## Expected behavior
 Should be showing the publiccdn.sharepointonline.com 

## Environment details (*development & target environment*)

- **Your Developer Environment**: 10.15.7 (19H2)
- **Target Environment**: SharePoint Online
- **Framework**:React
- **Browser(s)**: Chrome 85.0.4183.121
- **Tooling**: VS Code
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by andrewconnell** [comment]
The CDN can take up to 30 minutes to get provisioned. You reference a URL in your question, but don't include the URL. Also, you are missing context on what version of SPFx you're using.

**Comment by savannahp** [comment]
@andrewconnell thank you that was it! I wish it would of said it takes time to provision
