### ISSUE TITLE
Preview is not displayed for web part in a single page mode

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6343]
## Category

- [x] Bug

## Describe the bug

When you add a single-app page, the right pane is supposed to show a preview of the web part. It was the case in the past, in particular, in the introductory Video you can see this:

https://youtu.be/8BATz6LD6tA?t=451

![image](https://user-images.githubusercontent.com/2068657/95115863-27003f00-0714-11eb-8cf2-309d7e3dd77c.png)

![image](https://user-images.githubusercontent.com/528366/94944929-3d22bb00-04da-11eb-8e9c-31e9d12d1acc.png)

Currently, instead of the preview, an error appears in the console. It seems to be broken in the current version of SharePoint Online? I have tested on two newly created sites (a group site and a collaboration site, on two different tenants), with HelloWorld web part. I just get a javascript error in the console from the page that is supposed to host the web part:

The exception happens at AppPageHost.aspx page (built-in), that is supposed to show the web part, when it tries to set web part context. Looks like some issue with encoding:

![image](https://user-images.githubusercontent.com/528366/95118851-436b9e00-074b-11eb-8502-2a8f6cc8011c.png)
```
Uncaught SyntaxError: Unexpected token , in JSON at position 1633
    at JSON.parse (<anonymous>)
    at AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:254
    at AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:320
(anonymous) @ AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:254
(anonymous) @ AppPageHost.aspx?Mode=Preview&componentId=9a9646e2-306f-4a6a-8122-cf038fc32ce5&preconfiguredEntryId=0&mode=preview:formatted:320
```

The JSON it cannot parse is  (it breaks at "\r\n") here:
```
, spClientSidePageContext = JSON.parse('{"user" : {"@odata.context":"https://unmanagedvisio.sharepoint.com/a/_api/$metadata#Users/$entity","@odata.type":"#SP.User","@odata.id":"https://unmanagedvisio.sharepoint.com/_api/Web/GetUserById(12)","@odata.editLink":"Web/GetUserById(12)","Id":12,"IsHiddenInUI":false,"LoginName":"i:0#.f|membership|nbelyh@unmanagedvisio.onmicrosoft.com","Title":"Nikolay Belykh","PrincipalType":1,"Email":"nbelyh@unmanagedvisio.onmicrosoft.com","Expiration":"","IsEmailAuthenticationGuestUser":false,"IsShareByEmailGuestUser":false,"IsSiteAdmin":true,"UserId":{"NameId":"1003000085840810","NameIdIssuer":"urn:federation:microsoftonline"},"UserPrincipalName":"nbelyh@unmanagedvisio.onmicrosoft.com"},"page" : {\r\n                "DoesUserHaveEditPermission" : false,\r\n                "Content" : {"CanvasContent1":"{\\r\\n  \\"addedFromPersistedData\\": \\"False\\",\\r\\n  \\"controlType\\": 3,\\r\\n  \\"id\\": \\"bd983d77-6c7d-4d0b-ba07-9141dd146d16\\",\\r\\n  \\"webPartData\\": {\\r\\n    \\"id\\": \\"9a9646e2-306f-4a6a-8122-cf038fc32ce5\\",\\r\\n    \\"instanceId\\": \\"bd983d77-6c7d-4d0b-ba07-9141dd146d16\\",\\r\\n    \\"title\\": \\"Visto Plan\\",\\r\\n    \\"description\\": \\"
```
Would be happy if you could check it. Just wondering if it is just me or everyone.

## Steps to reproduce

- use yeoman generator to create a new Sharepoint "HelloWorld" web part.
- Enable full page in manifest `"supportedHosts": ["SharePointWebPart", "SharePointFullPage"],`
- Build and deploy the app part (I have not used tennant-wide deployment)
- Try to add the the web part to the site as app page, using (Home => New => Page => Apps)
- Now: there is no preview, but just javascript error in the console.

### alternatively

Try to install any app from the store, like the "Navigator 365" mentioned here. There is no preview when you try to add the part as a single page, but just this error in the console

## Expected behavior

The web part preview is shown.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v85]
- **Tooling**: [SPFx v1.11.0]

### Additional context

Related question:
https://github.com/SharePoint/sp-dev-docs/issues/6336

More about single-page apps:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

**Comment by patmill** [comment]
This should be WW now.
