### ISSUE TITLE
On-Premise Support?

### ISSUE THREAD

**Issue by contecc** [SharePoint/sp-dev-docs#6344]
It is unclear whether or not this scanner tool works for ON-premise SharePoint (ie. SharePoint 2010/2013/2016/2019)  Can you please add a note or statement in the beginning to clarify this point?

Respectfully,
Chris Conte
Senior Consultant
Microsoft Federal
chconte@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by SmitaNachan** [comment]
Hello @contecc 
The page has Note on modernization scanner support:

> The SharePoint modernization scanner only is supported for running against SharePoint Online. For scanning on-premises SharePoint you can consider using the SharePoint Migration Assessment Tool (SMAT).
