### ISSUE TITLE
Client Side Extension Manifest Schema Doesn't Honor '*' as Valid Version

### ISSUE THREAD

**Issue by mjimison** [SharePoint/sp-dev-docs#635]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
The version attribute of the customizer json manifest should accept '*' as a valid value, since that's the default value, and there's a comment indicating its usage when pulling the version number from package.json

#### Observed Behavior
After you update the $schema to the correct file, it immediately flags the '*' value for version as being invalid.

#### Steps to Reproduce
1. Update the $schema to the correct file (see: http://mattjimison.com/2017/06/09/sharepoint-framework-extensions-developer-preview-schema-issue/)
2. Observe '*' as invalid

_

**Comment by iclanton** [comment]
It's true that `*` is not a valid version in a built manifest, which is what the schemas are for. However, we should probably also publish schemas for what developers write.

I'll talk with @nickpape-msft about doing this.

**Comment by mjimison** [comment]
Thanks!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
