### ISSUE TITLE
ApplyProvisioningTemplate function needed

### ISSUE THREAD

**Issue by ahollandusc** [SharePoint/sp-dev-docs#6353]
This is a good walk thru though would be made simpler to follow through if the full listing of the ApplyProvisioningTemplate() function was provided in the same way as is done for the GetProvisioningTemplate() function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e581d3f-a187-b893-70e3-4c3ab5d45936
* Version Independent ID: d2316e36-fa51-f00e-26eb-5a1efaa0213d
* Content: [Provisioning console application sample](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample)
* Content Source: [docs/solution-guidance/provisioning-console-application-sample.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/provisioning-console-application-sample.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Thanks for the feedback... many of the docs are driven from community contributions, so please feel free to submit an update via a PR with your suggestions!

**Comment by ahollandusc** [comment]
Thanks Andy,
I’ve submitted a PR. Have a good weekend!
Adrian

**Comment by andrewconnell** [comment]
^Andrew... not "Andy" :)

**Comment by ahollandusc** [comment]
Sorry – nicknames are a bit of a habit. :p
Thanks Andrew :)
