### ISSUE TITLE
Incorrect documentation...this line is referring to modifying the interface for the IListInfoWebPartProps. This is located inside a file called "IListInfoWebPartProps.ts".

### ISSUE THREAD

**Issue by savannahp** [SharePoint/sp-dev-docs#6356]
So that is not in a ts file of it's own at all. It's just declared as an interface in the file he mentioned. 

![image](https://user-images.githubusercontent.com/42783981/95521638-3cc96a80-0987-11eb-8953-e7d7c3a292d9.png)

![image](https://user-images.githubusercontent.com/42783981/95521642-4357e200-0987-11eb-982b-b98f2658b973.png)

Hi @kevinguyer The documentation is correct. This line is referring to modifying the interface for the IListInfoWebPartProps. This is located inside a file called "IListInfoWebPartProps.ts". 

I have circled it in red in the below image.
![image](https://user-images.githubusercontent.com/7944457/55041504-f144ab00-4ff2-11e9-8dd5-dc1f38a460f5.png)

_Originally posted by @bcameron1231 in https://github.com/SharePoint/sp-dev-docs/issue_comments/476906438_

**Comment by andrewconnell** [comment]
If you can provide context where you saw this, it would help to get the doc fixed.

The web part property pane interfaces used to be in their own files, but have since been merged to be included in the web part themselves. Looks like the doc just needs an update.
