### ISSUE TITLE
Continually prompted to Allow Debug Manifests even after app removed

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#636]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After removing an app containing an application customizer and removing the custom action using Remove-PnPCustomAction users should no longer be prompted to Allow Debug Manifests on every modern page.

#### Observed Behavior
Despite removing the app (and ensuring it is removed from the recycle bins) and removing the Custom Action for the ApplicationCustomizer, users are still being prompted to Allow Debug Manifests.

When choosing to Load debug scripts and checking the console, there are no file not found errors (as would be expected when debugging and gulp serve is not running or when the CDN location doesn't contain any assets).

#### Steps to Reproduce
Follow the [Deploy your extension to SharePoint tutorial](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint) and then remove the app and the custom action.

**Comment by patmill** [comment]
Can you hit the page with ?reset=true and see if it clears things up?

**Comment by thechriskent** [comment]
@patmill that worked perfectly! Thanks! I only needed to do this on a single page and all other modern pages were corrected as well. What is this magic?

**Comment by patmill** [comment]
A debug cookie gets set sometimes, and reset= true clears it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
