### ISSUE TITLE
Sharepoint Number Column Displays Percentages Weird for 55-59

### ISSUE THREAD

**Issue by Code-Padawan** [SharePoint/sp-dev-docs#6363]
## Category

- [x] Bug

## Describe the bug

Column Formatting for a SharePoint number column formatted as apercent adds 13 0s and a 1 when txtContent = @currentField * 100

## Steps to reproduce

-Create a number column in a SharePoint List with "Show as percentage checked"
-Enter any value between 55 and 59
-Format the column with the following JSON:
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "span",
      "txtContent": "=@currentField*100 + '%'",
      "style": {
        "padding-left": "8px",
        "white-space": "nowrap"
      }
    }
  ],
  "attributes": {
    "class": "sp-field-dataBars"
  },
  "style": {
    "padding": "0",
    "width": "=@currentField * 100 + '%'",
    "background-color": "#ffe699",
    "color": "black",
    "border-top-color": "#f7c12a"
  }
}

## Expected behavior
Text Display is 2 digits

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: .NET Framework v4.x 
- **Browser(s)**: Chromium Edge v79
- **Tooling**: Notepad++
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

## Submission guidelines
![2020-10-09_10-39-33](https://user-images.githubusercontent.com/28579429/95603360-c6c31300-0a1b-11eb-89f2-5540eb7db179.png)

**Comment by shagra-ms** [comment]
@Code-Padawan Thank you for reporting this. We will take a look. 

To unblock you, I will recommend to use the newly introduced [displayValue property](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#displayvalue) that does exactly what you are trying to do above with the expression (convert field value to percentage).

**Comment by Code-Padawan** [comment]
That unblocked me.  Thanks!

**Comment by shagra-ms** [comment]
Regarding the unexpected behavior - the custom formatter process all the code in the browser and some of these floating arithmetic are expected to return the results that you have observed. 
E.g. Try `0.56*100` in your browser's console

A usual way to bypass this is to use [toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed). 

We will check if exposing such a function can be helpful in such cases. For now, as you are unblocked, I will resolve this issue.
