### ISSUE TITLE
How to set details of SPFx extension application customizer?

### ISSUE THREAD

**Issue by mzbrandl** [SharePoint/sp-dev-docs#6367]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

How can I specify in the source code of an SPFx extension application customizer, what the description and supported languages, displayed in the app catalogs details view are?
![image](https://user-images.githubusercontent.com/32365313/95725364-de96d300-0c77-11eb-8e01-0a387a9282e0.png)
When I generate a new extension with the Yeoman generator, the description text I enter is nowhere to be found in the whole solution. This might be a bug with the generator, but I would still like to know where the description would be saved.
Thanks!

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**:Chrome v79
- **Tooling**: SPFx v1.11.0
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by kongmengfei** [comment]
Only find `SUPPORTED LANGUAGES` settins in `package-solution.json` file. 

![image](https://user-images.githubusercontent.com/57654821/95971557-f458f380-0e43-11eb-8660-5b88b6c0b8c7.png)

For `DESCRIPTION` property, We may need to update it in app catalog item details. 

![image](https://user-images.githubusercontent.com/57654821/95971772-38e48f00-0e44-11eb-9427-98e0f5b5bcdc.png)
![image](https://user-images.githubusercontent.com/57654821/95971497-e5724100-0e43-11eb-990f-0aa32deafd05.png)

Baker Kong
Microsoft SharePoint Community Support
