### ISSUE TITLE
How to find the tenant name

### ISSUE THREAD

**Issue by mirkori** [SharePoint/sp-dev-docs#6368]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

In a SPO App-Only environment, what is the recommended way on **how to find the tenant name** ( **tenantname**.onmicrosoft.com ) or sharepoint url, if the tenant id is available?

Alternatively, is there a way to open a (CSOM) ClientContext to the sharepoint admin url, with only the tenant id available?

The other way around (find tenant id by name) is easy and can be done by checking the openid configuration of the tenant:
https://login.microsoftonline.com/tenantname.onmicrosoft.com/v2.0/.well-known/openid-configuration

Happy for any input on this.

**Comment by Jerry0527** [comment]
This is not possible to get Tenant Name based on Id using CSOM as it's always need SharePoint site url to create ClientContext firstly.

And if the envrionment is using App Only Authentication, the registered application can be found in:

http://tenant.sharepoint.com/sites/sitename/_layouts/15/_layouts/15/AppInv.aspx

The Tenantname should be know at first.
