### ISSUE TITLE
SPFX web part in embedding SharePoint landing page in Microsoft Teams

### ISSUE THREAD

**Issue by joostvdlinden** [SharePoint/sp-dev-docs#6369]
## Category

- [x] Bug

## Describe the bug
I have applied the preview solution of adding a SharePoint landing page to Teams in my test environment:
https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams
I have added an SPFX web part which loads in Edge, but does not load in Teams: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-birthdays

## Steps to reproduce
Basically apply the SPFX web part (https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-birthdays) to any SharePoint site page, and add this page as a tab to Teams (through SharePoint page type tab or through Website type tab)

## Expected behavior
I am wondering if this is by design that SPFX web parts do not render.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: I don't know?
- **Browser(s)**: Chromium Edge v79
- **Tooling**: n/a
- **Additional details**: n/a

### Additional context
n/a

**Comment by andrewconnell** [comment]
As the question seems to be about a specific sample, please use the samples repo for this question.
