### ISSUE TITLE
Debugging SPFx Extension in SPO does not work

### ISSUE THREAD

**Issue by hohenp** [SharePoint/sp-dev-docs#637]
#### Category
- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After creating a Application Customizer Extension and running gulp serve --nobrowser, i have added the URL to debug the Extension on our SPO modern list URL and expected "Allow debug manifests?" Dialog.

#### Observed Behavior
If I run my Extension locally using gulp serve --nobrowser, and I add the URL 
"?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"214a5747-738d-45ae-b719-c376dc7a9544":{"location":"ClientSideExtension.ApplicationCustomizer","properties":{"testMessage":"Hello as property!"}}}" 
to my modern list URL in SPO, nothing happens. I have checked the URL, replaced the GUID and checked that localhost:4321 is running.

Is there a way to debug the Debugging :) or to figure out what is going wrong. In the console I do not have any different requests then when I call the URL without the ?loadSPFX... 

Thanks for your help

**Comment by waldekmastykarz** [comment]
At this moment extensions work only on developer tenant. Are you trying to debug your extension on a non-dev tenant perhaps?

**Comment by hohenp** [comment]
Hi Waldek, thanks for your quick response. ok thanks, so I created a new Developer Site Collection within the SharePoint Admin Center of our 365 subscription. Or do I need a whole new Developer Subscription?

**Comment by giuleon** [comment]
Hi,
You need of a dev tenant take a look here
https://dev.office.com/devprogram

**Comment by hohenp** [comment]
All right. Thanks!!
