### ISSUE TITLE
Search Webparts not loading on unmanaged device with web-only access

### ISSUE THREAD

**Issue by sdevreese** [SharePoint/sp-dev-docs#6373]
## Category

- [x] Bug

## Describe the bug

Installed the solution in a new app catalog. The tenant has web-only access policy activated for unmanaged devices.
This causes the webparts to not load properly and returns this error:

![image](https://user-images.githubusercontent.com/72727150/95840728-d22c7c00-0d44-11eb-83ac-371131c17738.png)

When working on a managed device, there is no error and we can configure the webparts. So it has something to do with the policy.
On a managed device, we get the SAME error when using IE for example.

## Steps to reproduce

Activate policy in SharePoint Admin center
image
![image](https://user-images.githubusercontent.com/72727150/95840756-d9ec2080-0d44-11eb-9461-12cec409fbf9.png)

2.. Install Solution in App Catalog
3.. Add webparts to a communication site
4. reload page

## Expected behavior

webparts should show up and we should be able to configure the webpart properties

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **Target Environment**:  SharePoint Online
- **Browser(s)**: Chrome
- **Tooling**: SPFx

**Comment by andrewconnell** [comment]
@sdevreese said:
> Installed the solution

Not clear which solution... assume you're referring to something out of the box. This will get closed because this issue list is for developer issues
