### ISSUE TITLE
CORS Issue when UI not able to download JS Bundle for Spfx webpart.[Chrome/IE/Firefox]

### ISSUE THREAD

**Issue by AnkitSDesai** [SharePoint/sp-dev-docs#6377]
## Category

- [x] Bug

## Describe the bug

> After Deploying .sppkg file to the Appstore, When UI  trying to get bundle its getting blocked [CoRS error]- 

## Steps to reproduce

> Deploy your package to SharePoint App store and try in any major browser such as Chrome and Firefox.
Error:
![image](https://user-images.githubusercontent.com/11935710/96032036-1e062080-0e2c-11eb-8864-c21e10b7802c.png)

## Environment details (*development & target environment*)

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x]
- **Target Environment**: [e.g.  SharePoint Online]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v10]
- **Browser(s)**: [e.g. Chrome v854 | FireFox v31 | IE v11 ]
- **Tooling**: [e.g. VS Code | SPFx 1.11]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

FYI I  already tried this but no luck. 
![image](https://user-images.githubusercontent.com/11935710/96032847-46dae580-0e2d-11eb-997b-1b53d5286ab9.png)
  https://github.com/SharePoint/sp-dev-docs/issues/3871

> Seems like The UI request for .js Bundle is blocked out. even before any http calls like Get etc happends.

*Thanks for your contribution! Sharing is caring.*

**Comment by VesaJuvonen** [comment]
@AnkitSDesai - can you provide details on the sppkg file content and the settings. Is the assets served from the Office 365 CDN and what are the configurations there? - Looking on the picture you provided, you might be trying to load assets from a different tenant, which will not work due the CORS policy, but would need to know the settings more...

Or if you can share the package details, we can have a look on that directly from the store.

**Comment by AnkitSDesai** [comment]
Thanks @VesaJuvonen   for looking into this.
Yes the asset is served from the same tenant from O365 CDN.

Observation: 
1-When we created app store at the first place, it created(or recommended in dropdown)  as following URL.
https://****-portal1.sharepoint.com/*   (Generally I haven't see this behavior in my personal or other tenants but this tenant)
while expected behavior should be  https://companydomain.sharepoint.com/sites/app
2-Just an FYI the same .sppkg(Webparts) works fine with other tenants with no issues or any kinds of CORS blocking from the same tenant.

above point 2 suggest that there might be something tenant specific going on. I shall further share CDN settings in case required once I get from global admin.

Question: Do you recommend recreating App- catalog again. by deleting current one.

Thanks!

**Comment by VesaJuvonen** [comment]
ah - this is terminology thing. I though that with app store you were referring to actual Microsoft owned store, but it was the app catalog. Seems that this specific tenant has then some strange setup as it's not supported to have app catalog in different URL than the rest of the tenant... which will cause the CORS issue.

I would re-create the app catalog if possible - which I don't think is possible from the UX - BUT - you can actually use SPO PowerShell to do this with following setup:

`New-SPOSite -Url https://yourtenant.sharepoint.com/sites/apps -Owner admin@yourtenant.onmicrosoft.com -Template APPCATALOG#0 -StorageQuota 0`

This will reset the app catalog configuration to new URL. Can you test it and confirm that things are fixed. Thanks.

**Comment by AnkitSDesai** [comment]
@VesaJuvonen  the solution worked! what we endedup doing is deleting the current app catalog and creating brand new from the UI itself since PowerShell was giving a trouble.
Thank you this issue can be closed.

**Comment by VesaJuvonen** [comment]
Excellent - thanks for confirming the situation @AnkitSDesai. We'll close up this issue then.
