### ISSUE TITLE
Column Formatting New Image Field in Modern Lists

### ISSUE THREAD

**Issue by MichaelS4G** [SharePoint/sp-dev-docs#6382]
I see that Image is in the list of supported column types for column formatting, but it isn't clear if that is the new Image column type in modern lists. If that is supported, can we get an example? I can only return "object, object" when trying to adjust the column formatting. I simply want to make the thumbnail bigger.  The thumbnail formatting options for document libraries don't work and you can't seem to get a src or title from the currentfield.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-simple-data-visualizations)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi @MichaelS4G,

I think Image column type is supported, see below I add some style to the image column.

`{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
    "elmType": "div",    
    "children": [
        {
            "elmType": "img",
            "attributes": {
                "src": "@currentField.serverRelativeUrl"
            },
            "style": {
                "border": "2px solid red",
                "border-radius": "5px"
            }
        }
    ]
}`

![image](https://user-images.githubusercontent.com/57654821/96683090-44880680-13ac-11eb-8c58-422dfc393f38.png)

The above column is Image type, not Hyperlink or Picture.

![image](https://user-images.githubusercontent.com/57654821/96683235-739e7800-13ac-11eb-9b5a-531f0630b428.png)

How to know the property name of `@currentField`? I just get it via rest api request.

![image](https://user-images.githubusercontent.com/57654821/96683815-3dadc380-13ad-11eb-99a1-d19957444c47.png)

Baker Kong
Microsoft SharePoint Community Support

**Comment by shagra-ms** [comment]
@MichaelS4G Thanks for pointing out the gap in the documentation. I will update more details about how to use the Image column in list formatting.

**Comment by MichaelS4G** [comment]
Thank you! @currentField.serverRelativeUrl seems to do the trick. I had tried guessing at other variations with no luck. The API suggestion is a good idea too.

**Comment by shagra-ms** [comment]
The documentation is not updated with an example. Closing this.
