### ISSUE TITLE
Sharepoint Online API Not Listing Files

### ISSUE THREAD

**Issue by kngohil** [SharePoint/sp-dev-docs#6383]
The examples on this page to getting files don't work. Can someone please have a look and help please? With also some troubleshooting guides, since the API errors are not useful.

I am trying this in a Data Factory Pipeline. Following this page: https://docs.microsoft.com/en-us/azure/data-factory/connector-sharepoint-online-list 

My aim is to retrieve the file (and it's content) and store it into an Azure Storage v2 Container. Not just list the metadata about the folder/files. 

Example of API failures:

GET https://{site_url}/_api/web/GetFolderByServerRelativeUrl('/Folder Name')/Files
This works and lists the metadata of the folder about the folders and files. 

GET https://{site_url}/_api/web/GetFolderByServerRelativeUrl('/Folder Name')/Files('{file_name}')/$value
This doesn't work. The error I get is an HTTPS 400 Bad Request in Data Factory.

GET https://{site_url}/_api/web/GetFileByServerRelativeUrl('/Folder Name/{file_name})/$value
This also doesn't work. This also gives a HTTPS 400 Bad Request in Data Factory. 

Is there any working example that can be documented here please? 

Or point me to the correct way of doing it if this is not the correct API?

Thanks, 

Kishan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
@kngohil said:
> This also doesn't work. This also gives a HTTPS 400 Bad Request in Data Factory.

Assume you're actually replacing the `{site_url}` part of the URL? Have you tried other SPO REST queries from ADF (IOW, is it any request or just these endpoints)? I'd expect a LOT more errors to get reported if this popular endpoint wasn't working...

**Comment by kngohil** [comment]
Hi - yes I've replaced the site URL, folder path etc.

**Comment by Jerry0527** [comment]
Make sure server relative url is correct, you can check if the endpoint which without $value appended could return data:

https://{site_url}/_api/web/GetFileByServerRelativeUrl('/Folder Name/{file_name}')

For example, if the site url like this:

https://tenant.sharepoint.com/sites/sitename

Then for default documents library, the relative url should be:
https://tenant.sharepoint.com/sites/sitename/_api/web/GetFileByServerRelativeUrl('/sites/sitename/shared%20documents/filename')

**Comment by kngohil** [comment]
Hi @Jerry0527 - sure I can check this. Here is what I was trying with confidential data removed: 

https://blah.sharepoint.com/sites/BlahSiteName/_api/web/GetFolderByServerRelativeUrl('Folder1/Folder2/Folder3/test.csv')/$value 

So are you saying that I would need this instead:

https://blah.sharepoint.com/sites/BlahSiteName/_api/web/GetFolderByServerRelativeUrl('**/sites/BlahSiteName/**Folder1/Folder2/Folder3/test.csv')/$value  - so that the "sites/xxx" path is listed in both the URL and also the relative URL inside the () ?

**Comment by Jerry0527** [comment]
Yes, if the file is hosted in this site url "/sites/BlahSiteName", then the relative url should also using "/sites/BlahSiteName/LibraryName/FolderName1/FolderName2/FolderName3/filename.csv"

**Comment by Jerry0527** [comment]
In additional, please using GetFileByServerRelatveUrl instead of GetFolderByServerRelativeUrl to get file directly.

**Comment by kngohil** [comment]
@Jerry0527 Thanks for this - I was able to read the single file now. Ok so GetFileByServerRelativeUrl will get me a file, but can I retrieve multiple files using GetFolderByServerRelativeUrl? Or is there some alternative batch retrieval I can do via the API endpoint?

**Comment by Jerry0527** [comment]
Similiar like this:

https://blah.sharepoint.com/sites/BlahSiteName/_api/web/GetFolderByServerRelativeUrl('/sites/BlahSiteName/Folder1/Folder2/Folder3')/files

**Comment by kngohil** [comment]
Hi @Jerry0527 thanks - the HTTPS response here tells me the metadata about the folder, e.g. the folders/files listed, their creation times etc. I was actually hoping for an API that does a bulk/batch download of all files (e.g. the file with content) in the folder.

**Comment by Jerry0527** [comment]
Rest API didn't provide option to download files in a folder directly, it needs to loop files url and do request to download files one by one with GetFileByServerRelatveUrl.

You can consider to use SharePoint CSOM PowerShell instead:

[How to Download a Folder from SharePoint Online using PowerShell?](https://www.sharepointdiary.com/2017/07/download-folder-from-sharepoint-online-using-powershell.html)
