### ISSUE TITLE
 Create Site not working with Power Automate

### ISSUE THREAD

**Issue by SharePointAcademy** [SharePoint/sp-dev-docs#6388]
Hi,
I tried using Power Automate to create the website and I get the error shown in the image.
https://sharepointacademy.files.wordpress.com/2020/10/error-create-site-1.png
It's possible?
Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by marcjordana** [comment]
Hello @SharePointAcademy,

You need to use a different parameter to invoke the Site Design in the site creation REST API call.

As I've seen in [this article from Simon Ågren's blog](https://simonagren.github.io/sites-sitedesign-rest/), you need to use the "WebTemplateExtensionId". It looks like the "SiteDesignId" attribute is used only for OOTB Site Designs.

I tried with the following json settings in the request body and it worked:

```
"SiteDesignId":"00000000-0000-0000-0000-000000000000",
"WebTemplateExtensionId":"2892a9bf-3015-41c9-924c-dacfc95c11ec"
```

I hope this helps!

Regards,

Marc Jordana

**Comment by SharePointAcademy** [comment]
Perfect, it worked. Thank you for your help @marcjordana .
