### ISSUE TITLE
Can't add a SPFx package that includes an Application Customizer to the App Catalog

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#639]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When creating a new SharePoint Framework project, you should be able to add the generated package to the App Catalog.

#### Observed Behavior
As soon as we add an Application Customizer, the _gulp package-bundle_ generates an invalid package that can't be added to the App Catalog. When uploaded, the package is marked as invalid and the Trust dialog does not pop up. Even if you add the Elements.xml to add the CustomAction and the features entry in the package-solution.json, the package is still considered as invalid. The "Hello World" project (yo @microsoft/sharepoint without any customization) doesn't work either.

![image](https://user-images.githubusercontent.com/7620955/27059405-46769c92-4fa4-11e7-9a6b-9ff1b1e400a0.png)

At this point, the only way to "serve" Application Customizer is to load it through the URL which is not the optimal way to test Enterprise Scale applications.

#### Steps to Reproduce

1. Create a SharePoint Framework project with an Application Customizer
2. Run gulp bundle
3. Run gulp package-solution
4. Drag & Drop the generated package to you App Catalog
5. Invalid Package

**Comment by VesaJuvonen** [comment]
Hi @sebastienlevert, since this has been working properly for numerous people, we would need some additional details around the scenario or the package. Can you check the error details around the package by clicking **unavailable apps** in this UI you provided. That should give you insights on the actual error what caused the package not to be valid. This would be also needed for us to give any additional support around this. thx.

**Comment by VesaJuvonen** [comment]
Hi @sebastienlevert, did you had a chance to check the error description from the *unavailable apps* tab in the app catalog? - that would give us more insights on what actually was wrong in your package. thx.

**Comment by chrisobriensp** [comment]
Yep, definitely working for me too - as shown at http://www.sharepointnutsandbolts.com/2017/06/SPFx-Application-Customizer-Global-JS-Page-Header.html 

Could it be a path length issue somewhere perhaps, or an issue with the package-solution.json file?

Cheers,

COB.

**Comment by VesaJuvonen** [comment]
Hi @sebastienlevert, did you had a chance to check the error description from the unavailable apps tab in the app catalog? - that would give us more insights on what actually was wrong in your package. 

We'll close the issue soon unless we can get a response for this, so would appreciate a comment around this. Thx.

**Comment by VesaJuvonen** [comment]
Closing this for now, due no response. Please reopen, if this is still an issue for you with requested details. Thx.

**Comment by shaipetel** [comment]
Shame this got no reply from the original poster, I am having the same problem with a package now, I opened a new issue: https://github.com/SharePoint/sp-dev-docs/issues/2288

Can you guys jump in there an perhaps we can investigate this further? It is currently happening to me on 2 tenants while 1 tenant is working ok with the same package.
