### ISSUE TITLE
Error while uploading SPPKG in SharePoint 2019

### ISSUE THREAD

**Issue by valerc** [SharePoint/sp-dev-docs#6396]
## Category

- [x] Bug

## Describe the bug

Since the moment when application for SharePoint was updated and section "developer" was added into package-solution.json, I have an error when application is uploaded.
Error text:
`There were errors when validating the App manifest.: Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has invalid child element 'DeveloperProperties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. List of possible elements expected: 'SupportedLanguages, SettingsPage, SupportedLocales, UpgradedEventEndpoint, SupportPage, StartPage, InstalledEventEndpoint, WebTemplate, UninstallingEventEndpoint' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '321'.`
![image](https://user-images.githubusercontent.com/39829451/96610006-d4be4100-1303-11eb-89f1-61978f8a119f.png)

Our solution (an SPPKG/SPFX) app throws an error upon deployment on any SharePoint 2019 version, we already been through some of suggested issues that should resolved this, such as updating to latest CU of SharePoint 2019, but the error persist through the versions. On SharePoint Online there is no such issue present.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Server 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by VesaJuvonen** [comment]
Error message implies that you are trying to upload SharePoint Framework v1.11 solution package to the SharePoint 2019 which is not supported. SharePoint 2019 is on the 1.4.x level and only supports those sppkg files which are explicitly created with the the 2019 as the target environment option when the solution is created.

There's no updates on the supported SPFx version for SP2019 in any CUs as that would require end-to-end update for native UX layer, which we cannot do for SP2019.

Can you double check the used SPFx version on the package and let us know if things work properly when 2019 is used in the targeted environments. Thanks.

**Comment by valerc** [comment]
@VesaJuvonen Our sppkg solution was initially created with SP2019 as the target environment but we've got the issue after SPFx was updated to v.1.11. Since 1.11 is not supported in SP2019 we had to do rollback and now the application uploading works fine again.
Thank you very much for your help!
