### ISSUE TITLE
ListView Command Set extension: Error after gulp serve

### ISSUE THREAD

**Issue by psarm1** [SharePoint/sp-dev-docs#6402]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

**Repro Steps:**

1. SPFx project solution with ListView Command Set extension
2. Run gulp serve
3. SharePoint site opened in browser with allow debug scripts popup dialog
4. Choose 'Load debug scripts'

**Expected Behavior**
We should be able to test the command list button

**Actual Behavior**
Redirected to error page with the following Technical Details,
Error details: TypeError:
_microsoft_sp_loader__WEBPACK_IMPORTED_MODULE_2__._SPLoaderFlights._useNewBootSequence is not a function

![Screenshot 2020-10-22 121450](https://user-images.githubusercontent.com/40935723/96814752-37c4ea80-1460-11eb-82e3-ffbe114922a6.png)

## Environment details (if applicable)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.22.0
- **Browser(s)**: Microsoft Edge v86.0.622.48
- **Tooling**: VS Code | SPFx v1.11.0
**Dependencies**:
    "@microsoft/decorators": "1.9.1",
    "@microsoft/rush-stack-compiler-3.2": "^0.4.6",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-dialog": "1.9.1",
    "@microsoft/sp-listview-extensibility": "1.9.1",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "gulp-cheerio": "^0.6.3",
    "gulp-xmlpoke": "^0.2.1",
    "libxmljs": "^0.19.5",
    "office-ui-fabric-react": "5.133.0",
    "react": "15.6.2",
    "react-dom": "15.6.2"
**devDependencies**:
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "3.9.1",
    "gulp-cli": "2.3.0"

  "@microsoft/generator-sharepoint": {
    "version": "1.11.0",
    "libraryName": "hatch-process",
    "libraryId": "c858d212-7c8b-47d6-b08d-8d488872349d",
    "environment": "spo",
    "packageManager": "npm",
    "isCreatingSolution": true,
    "componentType": "extension",
    "extensionType": "ListViewCommandSet"
  }

Tags: #spfx #spfx-webparts #spfx-tooling

**Comment by andrewconnell** [comment]
Just verified a brand new extension with zero customizations created using SPFx v1.11 loaded fine. Maybe share a repo to repro?
