### ISSUE TITLE
DynamicData.tryGetValue() should not fail if disposed

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#6403]
## Category

- [x] Bug

## Describe the bug

It's intermittent when switching between normal and edit mode and you are using DynamicData that you get the error

```
 The "DynamicData" object cannot be used because it has been disposed
```

when having code like this:

```
let queryDataSourceValue = this.properties.queryKeywords.tryGetValue();
```

where `queryKeywords` above is `DynamicProperty<string>`.

It would be useful if `tryGetValue` returned null if the object was disposed. This way you don't have to check for this manually in the code.

## Steps to reproduce

Create a web part using page context dynamic data, and hit edit/save a couple of times, and you should see issues where the dynamic data component is not hooked correct. Which is ok, hence "tryGetValue". The DynamicProperty object is present, but can be disposed due to page navigation.

If checking `isDisposed` is the right way to handle this then the sample at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-data could be updated to showcase this pattern.

## Expected behavior

I expect `tryGetValue()` to return null/empty if the dynamic data object happens to be there but it's disposed. If it had internal logic to try to reload itself, even better.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome v86 | Chromium Edge v86
- **Tooling**: SPFx v1.10.0

**Comment by andrewconnell** [comment]
Context? SharePoint Framework version, browser, etc? Please use the environment context section in the default issue template and don't delete it.

**Comment by wobba** [comment]
Sorry.. my bad. Added more info.

**Comment by mbice** [comment]
I've reproduced this same issue with SPFx 1.11.0 as well.

**Comment by patmill** [comment]
Sounds reasonable.  Working on it.

**Comment by wobba** [comment]
And update... I have this code, and `tryGetSource` still throws and error that the data source is disposed. When manually checking first, which return false, then I would not expect an error afterwards.

```
if (this.properties.queryText.isDisposed) {
   return;
}
const source = this.properties.queryText.tryGetSource();
```

Checking twice works.

```
if (this.properties.queryText.isDisposed) {
    return;
}

if (this.properties.queryText.isDisposed) {
    return;
}

const source = this.properties.queryText.tryGetSource();
```

**Comment by AJIXuMuK** [comment]
@wobba  - this should be rolled out WW

**Comment by wobba** [comment]
Thank you and I'll test it out 👍
