### ISSUE TITLE
Default Click doesn't open details page

### ISSUE THREAD

**Issue by csteelatgburg** [SharePoint/sp-dev-docs#6405]
This note is incorrect:
defaultClick: buttons with this action will do the same thing as clicking the list item in an uncustomized view. Below is an example of a button that, when clicked, simulates a click on the item, which results in the details pane being opened.

The default click action when using a document library isn't to open the details pane, but instead opens the file. There doesn't seem to be an option to open the details pane in view mode using a custom action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to submit a PR to contribute and update the doc?

**Comment by csteelatgburg** [comment]
The update from @SmitaNachan is not accurate, either. The second sentence should read something like this:
Below is an example of a button that, when clicked, simulates a click on the item, which results in the details pane being opened for that list item. 

The following third sentence would provide more clarification:
Adding this example button to a document library simulates a click on the file or folder, which results in the file or folder being opened.

(As an aside, @andrewconnell, by boss's name is also Andrew Connell, so the notifications for this thread were a bit confusing for me, at first. )

**Comment by andrewconnell** [comment]
@csteelatgburg 

How about submitting a PR with the suggested change?
