### ISSUE TITLE
https://graph.microsoft.com/v1.0/lists returns 400 error

### ISSUE THREAD

**Issue by MatthewSteeples** [SharePoint/sp-dev-docs#6409]
The table gives 4 graph endpoint equivalents for 4 SharePoint v2 endpoints, but only 3 of them seem to work. `Sites`, `Drives` and `Drive` all return a 200 response with some data, but `lists` returns a 400 error with the following message

```
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'lists'.",
        "innerError": {
            "date": "2020-10-23T12:46:40",
            "request-id": "98724143-e705-46f9-8e48-5503d3e533fa",
            "client-request-id": "23fde489-dc69-00ae-f2cf-354824a9cef6"
        }
    }
}
```

Is there a mistake in the table, or is additional configuration required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: accadff1-1b70-6a67-4465-d66245aa3a09
* Version Independent ID: 8e108e60-9c50-0856-712c-f85e64c9813a
* Content: [Operations using SharePoint REST v2 (Microsoft Graph) endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph)
* Content Source: [docs/apis/sharepoint-rest-graph.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/sharepoint-rest-graph.md)
* Product: **sharepoint online**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, it looks like you may not be forming the URL correctly. In order to call the /Lists endpoint, you need to provide a Site ID first.

_api/v2.0/sites/mytesttenant.sharepoint.com,532bd9a4-869f-45e2-b5f0-323f6604a429,c67564a0-242f-40bf-b4ac-a0ea8dbc935e/lists

Use the following documentation on the API usage and resources
https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0

**Comment by Jerry0527** [comment]
@MatthewSteeples ,

To get the site id in Azure AD, try to call the endpoint below in Graph Explorer with GET Request:

https://graph.microsoft.com/v1.0/sites?search=*

![Snipaste_2020-10-27_15-18-56](https://user-images.githubusercontent.com/28797671/97268993-befecd80-1867-11eb-920c-2c564e3888a3.png)

Then as suggested from bcameron1231, use this endpint format:

https://tenantname.sharepoint.com/_api/v2.0/sites/zheguo.sharepoint.com,6f0d629d-b9b2-44f2-a676-2a590f7d08a2,040f9461-79c2-4cda-8afe-f8b592a0b646/lists

**Comment by MatthewSteeples** [comment]
Hi @bcameron1231 and @Jerry0527,

Thanks for those pieces of information. That gives back queries that I'd expect. One thing I'm having trouble finding (and I don't seem to be able to find it here either) is where the "personal" lists created through [Microsoft Lists](https://www.microsoft.com/en-us/microsoft-365/microsoft-lists) are stored. I've tried looking in the sites, and in the `-my` suffix too but don't seem to be able to track these down. I recognise that this isn't the right place to ask for support, but is there anything you can point me in the direction of?

**Comment by bcameron1231** [comment]
Personal Lists are stored in the User's OneDrive. You would need to use the standard SharePoint REST APIs to get the data from these lists, from that Users OneDrive site.

e.g

`https://mytenant-my.sharepoint.com/personal/bcameron_mytenant_com/_api/web/Lists/getbytitle('Issue Tracker')/items`

**Comment by MatthewSteeples** [comment]
Thanks. Feels like I'm getting closer now. Is there a way to get those through the Graph API (as that's what the rest of our system currently uses)?

**Comment by MatthewSteeples** [comment]
@bcameron1231 Exactly what I was after thanks. It was the middle syntax that I was having trouble with deducing (what to put as the "site" for a personal site)
