### ISSUE TITLE
Installing @microsoft/generator-sharepoint fails on MacOS 10.11.6 and 10.12.5

### ISSUE THREAD

**Issue by jacek-eq** [SharePoint/sp-dev-docs#641]
[error_log.txt](https://github.com/SharePoint/sp-dev-docs/files/1069959/error_log.txt)

**Comment by jacek-eq** [comment]
When I tried pasting the log, all instance of "@microsoft/generator-sharepoint" have been removed.

**Comment by jacek-eq** [comment]
I have found a workaround: changed ownership of /usr/local/lib/node_modules (and contents) to me and reran installer without sudo

**Comment by jacek-eq** [comment]
It looks like the problem is that phantomjs-2.1.1-macosx.zip and its contents are owned by nobody (-2)

**Comment by qz2017** [comment]
Thanks for posting. It looks like you have found out the solution. Please feel free to open if you still have problem with that.
