### ISSUE TITLE
SpFx Helloworld webpart does not show up under modern Page toolbox

### ISSUE THREAD

**Issue by kanchankumbhar2** [SharePoint/sp-dev-docs#6419]
## Category

- [x] Question

## Expected or Desired Behavior
Upon installation of the app, i can add the webpart to the pages as well

## Observed Behavior
After adding app ,i try to add the app to my page, the app is not showing up in the list of the available apps.
## Steps to reproduce

Follow the steps mention in https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part and created simple helloworld web part

Add the .sppkg file in appcatalog and add the app in site

## Expected behavior
After adding app in site, I should able to add the web part on page.
>## Environment details 
I have two tenants, on test tenant I don't face any issue it is working perfectly fine. But on Production tenant I am facing this issue

- **Your Developer Environment**: - Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**:  Node.js v10
- **Browser(s)**: Chrome v79 
- **Tooling**:  VS Code 

### Additional context

I am trying to add Modern Script Editor web part from [this ](https://medium.com/niftit-sharepoint-blog/add-the-script-editor-webpart-back-to-sharepoint-modern-experience-688a7b7208e4) blog but I cant add it on production as I can not see it in web part list after deployment,so I am trying to deploy the simple Helloworld WebPart but I cannot see it as well in web part list on Production Tenant. On Test tenant everything is working fine. 
Note : I have admin account with admin access. In Past I have deployed SPFX Extension and it worked very well

*Thanks for your contribution! Sharing is caring.*

**Comment by kanchankumbhar2** [comment]
I am not able to attach the solution because of the size limitation

**Comment by bcameron1231** [comment]
Can you confirm a couple of things.

1. Did you use --ship when you bundled and packaged your solution?
2. Do you see any errors in the app catalog list from when you uploaded the sppkg file?

**Comment by kanchankumbhar2** [comment]
Hi,
Yes I used it. Below are the commands I used 

gulp build --ship
gulp bundle --ship
gulp package-solution --ship

I dont see any error in app catalog.

One more update I am able to see and add the webpart on classic site. It is not visible on Modern site/Page

**Comment by andrewconnell** [comment]
Couple things... 

1) have you tried creating a new web part and testing that?
2) if the issue is specific to this project/blog post, suggest you post the question to the same repo where you got the project or as a comment to that blog post as this is for general SharePoint developer questions/support.

@kanchankumbhar2 said:
> I am not able to attach the solution because of the size limitation

Create a new public repo in GitHub & share a link to that. Even if you managed to upload a ZIP to this issue, people shouldn't download unknown ZIPs filled with script

**Comment by andrewconnell** [comment]
Edited OP to be a QUESTION, not a BUG.

**Comment by kanchankumbhar2** [comment]
> Couple things...
> 
> 1. have you tried creating a new web part and testing that? - Yes I tried to create new web part as well and it is also not visible
> 2. if the issue is specific to this project/blog post, suggest you post the question to the same repo where you got the project or as a comment to that blog post as this is for general SharePoint developer questions/support. - in this case issue is not specific to this project
> 
> @kanchankumbhar2 said:
> 
> > I am not able to attach the solution because of the size limitation
> 
> Create a new public repo in GitHub & share a link to that. Even if you managed to upload a ZIP to this issue, people shouldn't download unknown ZIPs filled with script

**Comment by andrewconnell** [comment]
@kanchankumbhar2 Your last response is unclear... looks like you just pasted what I sent in the reply.

**Comment by kanchankumbhar2** [comment]
Ohh Ok ..I have answered your questions from last reply (See my anwers in bold)

Couple things...

1. have you tried creating a new web part and testing that? - **Yes I tried to create new web part as well and it is also not visible**

2. if the issue is specific to this project/blog post, suggest you post the question to the same repo where you got the project or as a comment to that blog post as this is for general SharePoint developer questions/support. - **in this case issue is not specific to this project**

**Comment by bcameron1231** [comment]
Can you see if the discussion below can help you resolve your issue? It appears someone else had issues in the past with this. 

https://github.com/sharepoint/sp-dev-docs/issues/775

**Comment by kanchankumbhar2** [comment]
I checked the #775 already and tried all the possibilities mentioned in the discussion ,so far no luck

**Comment by andrewconnell** [comment]
I'm not able to repro this... that's the first step to being able to assist. So... repeating what I said before...

> Create a new public repo in GitHub & share a link to that.

**Comment by kanchankumbhar2** [comment]
Yes I'll share the code

**Comment by kmprasad4u** [comment]
Custom script needs to be enabled in the Site/Tenant... or you need to turn off "requiresCustomScript" in the solution

https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-script-editor/src/webparts/scriptEditor/ScriptEditorWebPart.manifest.json

Beware of the security considerations of using Script Editor in your tenant
https://docs.microsoft.com/en-us/sharepoint/security-considerations-of-allowing-custom-script
