### ISSUE TITLE
when we load a modern sharepoint page some webparts load only after we scroll down

### ISSUE THREAD

**Issue by NitinVarur** [SharePoint/sp-dev-docs#6424]
Hello guys .

whenever i load a page in modern site the custom web parts that are there at the end of page will only load after we scroll down.
can anyone help me on this issue. i have a anchored scroll menu web part at the end of the page, this loads only when i scroll to the end. i want it to load first whenever i open the page.

this issue was discussed and closed but i never got the solution. find it below 

https://github.com/SharePoint/sp-dev-docs/issues/729

**Comment by wictorwilen** [comment]
@NitinVarur  - this is by design, to improve page performance.

**Comment by NitinVarur** [comment]
@wictorwilen  is there any way we can a force load a particular webpart first so when we open or refresh a page it loads immiedetly. Please help

**Comment by wictorwilen** [comment]
@NitinVarur - not that I'm aware of, more than ensuring that you have the web part at the top of the page
