### ISSUE TITLE
SPField.fieldType Enumeration

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#643]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

When creating a Field Customizer extension, you have access to the **FieldCustomizerContext** which has an **SPField** field property that can reveal the type of field with the **fieldType** property. Generally it's accessed like this within the context of your FieldCustomizer extension:
```
this.context.field.fieldType
```
The value returned is a string but the values are actually numbers. What do these numbers correspond to? They do not appear to correspond to the [.NET SPFieldType enumeration](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.spfieldtype.aspx).

Here are a few for example:

FieldType | SPFx Value | SPFieldType Value
---------- | ------------ | ---------------
Text |   | 2
Note | 9 | 3
DateTime | 5 | 4
Counter | 7 | 5
Boolean | 4 | 8
Number | 8 | 9
Computed | 10 | 2

Notice that Single Line of Text fields don't seem to have a fieldType value (empty string). **_(Bug?)_**

**Comment by pgonzal** [comment]
Reclassifying this as a bug.  The intended design was for the `this.context.field.fieldType` API to return the text strings shown in your **FieldType** column above.  If you are seeing an integer, we should fix that.  We will investigate it.

**Comment by pgonzal** [comment]
I have merged a fix for this issue.  It should roll to production over the next couple weeks.  You do not need to upgrade your SPFx packages in order to see the fix.

(If your issue is not resolved after a few weeks, please reopen this bug!)

Thanks @thechriskent for reporting this issue!
