### ISSUE TITLE
Calling Azure Dev Ops API from Isolated SPFx Web Part

### ISSUE THREAD

**Issue by kmprasad4u** [SharePoint/sp-dev-docs#6431]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am trying to call Azure Dev Ops API from an Isolated SPFx Web Part under the context of the user (without using PAT). After I have approved the API permission request via the SharePoint Admin Center I am still still not able to get the data using the API. 

Below repository has a sample project explaining the issue
https://github.com/kmprasad4u/SPFx-DevOps

Below file has the options that we have tried to connect to Azure DevOps, and the errors associated to it.
https://github.com/kmprasad4u/SPFx-DevOps/blob/master/src/services/devOpsService/DevOpsService.ts

Please let me know if there is anything that I am missing, or if there is any example or tutorials I can follow to achieve my needs. 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Chrome
- **Tooling**: VS Code, SPFx v1.11
- **Additional details**: 

https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient

**Comment by andrewconnell** [comment]
First thing I'd check is the URL of the AzDevOps endpoint (as you are pointing to a few different ones) & if the name you listed as the resource is correct.

This isn't a SharePoint specific question unfortunately so you'll likely get better success posting this to the Azure DevOps forums because there isn't an issue with SPFx here... the challenge is specifically calling the AzDevOps API.

**Comment by kmprasad4u** [comment]
@andrewconnell 
Just figured that it worked by using ID of "Azure DevOps" instead of using the URL. Updated the repository code as well. 

Hope it helps somebody :)
