### ISSUE TITLE
How to use Visio API to show/hide toolbar in SharePoint online

### ISSUE THREAD

**Issue by kanchankumbhar2** [SharePoint/sp-dev-docs#6433]
## Category

- [ ] Question

## Question
I wanted to hide the  footer section of visio on Sharepoint page. On the page I have added embeded web part and configured the URL of visio file.

![image](https://user-images.githubusercontent.com/55887332/97867375-c294c780-1d33-11eb-9634-d0bbae754248.png)

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online

I tried with [this](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-visio) repository sample, but when I run gulp serve , for some reason I am not able to edit the properties of it.

Any heads-up on this.
 

>
> *Thanks for your contribution! Sharing is caring.*

**Comment by patrikhellgren** [comment]
There is an active issue with the Visio JS API ([https://github.com/OfficeDev/office-js/issues/1378](https://github.com/OfficeDev/office-js/issues/1378)) and you probably run into that when trying the SPFx sample.
If that is the case you need to download visio-web-embedded.js and bundle that in the SPFx package instead of referencing the external package to make it work until the issue is resolved.

**Comment by andrewconnell** [comment]
Unclear what you're asking... is this within a custom SharePoint web part? I see you referenced a specific sample project in a different repo. If you have a question about that project, suggest you post the question to that repo as this issue list is for general SharePoint development-related questions.

**Comment by kanchankumbhar2** [comment]
> Unclear what you're asking... is this within a custom SharePoint web part? I see you referenced a specific sample project in a different repo. If you have a question about that project, suggest you post the question to that repo as this issue list is for general SharePoint development-related questions.

As I mentioned in the question, I need to hide the toolbar of visio using API. I am new in Sharepoint Online customization i.e SPFX,so need help how to achieve this feature. As I mentioned in above I try the ready to use the SPFX web part but somehow it is not working.

**Comment by kanchankumbhar2** [comment]
> There is an active issue with the Visio JS API ([OfficeDev/office-js#1378](https://github.com/OfficeDev/office-js/issues/1378)) and you probably run into that when trying the SPFx sample.
> If that is the case you need to download visio-web-embedded.js and bundle that in the SPFx package instead of referencing the external package to make it work until the issue is resolved.

Sure I'll this solution.Thanks

**Comment by andrewconnell** [comment]
@kanchankumbhar2 said

> I am new in Sharepoint Online customization i.e SPFX,so need help how to achieve this feature. As I mentioned in above I try the ready to use the SPFX web part but somehow it is not working.

Understood, but SPFx doesn't provide an API to remove toolbars. While I'm not familiar with the Visio API, it appears this toolbar is specific to the Visio API so it's a Visio specific thing, not a SPFx thing.
