### ISSUE TITLE
TypeError on links when react sharepoint module is active on dashboard

### ISSUE THREAD

**Issue by avvink** [SharePoint/sp-dev-docs#6434]
## Category

- [x] Question

## Question

I've developed a sharepoint module in react, it's finished but now with beta testing this strange issue appeared in sharepoint. When they added my module and then they add a link to another sharepoint page on the dashboard I get a `TypeError: Illegal invocation` in de `sp-pages-assembly.js` when redirected to the next page. I tried setting up the project again from the setup tutorial and copying over the components I use, but I still get this error. This error only occurs when they have my module active, if they remove it they can click on the links without any problem. I know it's not a lot information, that's why I put it here as a question. I don't know how to debug this, because it only occurs on production.

## Environment details (*development & target environment*)

- **Your Developer Environment**: MacOS 10.15.7
- **Target Environment**: SharePoint Online
- **Framework**: React
- **Browser(s)**: all
- **Tooling**: SPFx v1.11.0

## Additional details

```
  "dependencies": {
    "@fluentui/react": "^7.149.3",
    "@microsoft/sp-core-library": "^1.11.0",
    "@microsoft/sp-lodash-subset": "^1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.11.0",
    "@microsoft/sp-property-pane": "^1.11.0",
    "@microsoft/sp-webpart-base": "^1.11.0",
    "date-fns": "^2.16.1",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "resize-observer-polyfill": "^1.5.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.7": "^0.6.26",
    "@microsoft/sp-build-web": "^1.11.0",
    "@microsoft/sp-module-interfaces": "^1.11.0",
    "@microsoft/sp-tslint-rules": "^1.11.0",
    "@microsoft/sp-webpart-workbench": "^1.11.0",
    "@types/react": "16.9.53",
    "@types/react-dom": "16.9.8"
  }
```

**Comment by lexdenotter** [comment]
Anyone an idea why this is happening?

**Comment by patmill** [comment]
Sorry for not responding earlier.  Is this still an issue?  If it is, could you give some more information, like what your solution is doing (is it intercepting global DOM events, etc.), does it change the DOM on the page outside of your DOMElement property, etc?  What is 'dashboard' in this context, etc?  It's hard to tell from the information you have provided here what the issue is.
