### ISSUE TITLE
Error message details?

### ISSUE THREAD

**Issue by AskYous** [SharePoint/sp-dev-docs#6436]
Would be good to see some details on possible error messages this API returns.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc58af9c-d9b8-5ed0-6117-2db7a1d425de
* Version Independent ID: 7cc8696c-5946-0414-b5be-c7561d0e31b5
* Content: [Create a new subscription](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/create-subscription)
* Content Source: [docs/apis/webhooks/lists/create-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/lists/create-subscription.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Currently, there is no detailed sample error message in documentation.
I suggest you could use Fiddler to see detailed error message returned:

[Fiddler](https://www.telerik.com/fiddler)
