### ISSUE TITLE
POST to a GET for creating a webhook?

### ISSUE THREAD

**Issue by AskYous** [SharePoint/sp-dev-docs#6437]
The documentation says:

> **Add** webhook subscription
> ...
> Change the request to POST from GET.

Why do you use a **GET** request to **Add** a web hook subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc58af9c-d9b8-5ed0-6117-2db7a1d425de
* Version Independent ID: 7cc8696c-5946-0414-b5be-c7561d0e31b5
* Content: [Create a new subscription](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/create-subscription)
* Content Source: [docs/apis/webhooks/lists/create-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/lists/create-subscription.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
@AskYous 

Is the below doc the correct content source?

- https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/get-started-webhooks#add-webhook-subscription

![image](https://user-images.githubusercontent.com/57654821/98332302-62569c00-2039-11eb-9e8c-c37554cfe3f5.png)

I think it means that you need to change the request method to POST, as in the former step, the request method is GET.

Baker Kong
Microsoft SharePoint Community Support

**Comment by AskYous** [comment]
Ah! I misread it. I thought it said to change **from** POST to GET.
