### ISSUE TITLE
Minimum Permissions for App Deploy on App Catalog

### ISSUE THREAD

**Issue by MelAtWork** [SharePoint/sp-dev-docs#6439]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

**What are the minimum required permissions for the account that adds/updates an app to the app catalog in SharePoint 2019 ?**

context details: 

I am working on a DevOps Pipeline for SPFx WebParts. The account, that will be used to add/update the app to the App Catalog should have the minimum required permissions.

First, this account had permission-level "Design" on the site level.
The App was added/updated and the WebPart coming with this app could be added to the pages of the SiteCollection.
However, the WebPart showed an error. 
Error was in German, so just providing some kind of idea, what the error was like:
_error when loading the url "..../nameoftheGermanLocationStringRessourcefileWithThatGuidInTheEnd.js" for resource "SegmentsWebPartStrings" in component "GuidAgain" (SegmentWebPart), file could not be found on the server_

So I understand, that this error is saying, that the first file the WebPart is looking for can not be found/accessed.
This error is solved, as soon as the account that adds/updates the app has Site Collection Admin permissions on the App Catalog. This behavior seems to be independent of tenant scope or site collection scoped app.

We have tried with contribute and full control permissions without luck.

But: I have tested this in my SharePoint Online Demo tenant and the minimum required permission level to successfully deploy the app has been "Full Control" there.

So I am not quite sure if the app catalog of that SP 2019 environment has an issue and doesn't work as expected or if the minimum of Site Collection Admin Permissions on the app catalog are required for the scenario.

Are there maybe any articles, videos, information available with a deep dive on the exact permission landscape around SharePoint App Deployment?

Hoping this is not too much off-topic.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Server 2019
- **Framework**: Node.js v10
- **Browser(s)**: Chromium Edge v79
- **Tooling**: VS Code,  SPFx v1.4.1 (used template for SP 2019), Azure DevOps Server
- **Additional details**: Nexus-Server

**Comment by andrewconnell** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-pipelines
