### ISSUE TITLE
Etag issue if document amended by approver

### ISSUE THREAD

**Issue by veryneant** [SharePoint/sp-dev-docs#6442]
Hi there - I tried using this power automate flow - only issue is during the review stage, if the approver amends the document linked, an Etag error appears - I'm not sure if there's a workaround?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ee96de-6a45-5ff0-50ea-4b627067061b
* Version Independent ID: ad00a0cc-f818-c468-0f54-653f5e6018f2
* Content: [Require approval of documents in SharePoint using Power Automate](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/require-doc-approval)
* Content Source: [docs/business-apps/power-automate/guidance/require-doc-approval.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/require-doc-approval.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Dupe to #6441
