### ISSUE TITLE
Link to overview-sharepoint-webhooks is broken (page not found)  - new link available

### ISSUE THREAD

**Issue by bigpix2000** [SharePoint/sp-dev-docs#6443]
This is an old link
https://developer.microsoft.com/office/sharepoint/docs/apis/webhooks/overview-sharepoint-webhooks

This is the new Link

https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks 

It just needs to be updated.  (I can do it) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8a983b-ae73-33c9-fd11-ac064e1eea9e
* Version Independent ID: 6baa41f1-4d40-b7ad-0f84-670d2700a16b
* Content: [Event receivers and list event receivers in the SharePoint Add-in model](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in)
* Content Source: [docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bigpix2000** [comment]
I can fix it if you like but there may be more bad links in there (it's a big doc!)

**Comment by andrewconnell** [comment]
PR's are welcomed :) Prefer if the doc is updated & there are other links, would be nice if they were fixed all at once.

**Comment by bigpix2000** [comment]
Let's see who gets to it first ... once the [M365 Chicago Conference](http://m365chicago.com) conference is done on Friday I will enumerate all the links on the site to see where they all are .... there does not seem to be that many and hopefully most of them are still valid links.

**Comment by bigpix2000** [comment]
So @andrewconnell ... Was getting to this and three things:

1. The original link was "resolved" by the act of updating the hard coded URL to use ".." dynamic reference to point to the article in docs ... looks like it was there already so not sure why it now works but it resolves the original issue
2. Reviewing all the links as you noted to see what else is out there revealed two blogs that are no longer discoverable or perhaps even out there (look at the dates and we can see why:

 Using Azure storage queues and WebJobs for async actions in Office 365 (MSDN Blog Post)
https://blogs.msdn.com/b/vesku/archive/2015/03/02/using-azure-storage-queues-and-webjobs-for-async-actions-in-office-365.aspx


 Attaching Remote Event Receivers to Lists in the Host Web (MSDN Blog Post)
https://blogs.msdn.com/b/kaevans/archive/2014/02/26/attaching-remote-event-receivers-to-lists-in-the-host-web.aspx

3. It would take a judgement call to decide what the appropriate replacement articles for those are if that is even necessary

On item 3, just let me know if we should close this issue as the original problem is solved OR if you want to track the other links with this (I am ok opening up a new one for those only)    Thanks!

**Comment by andrewconnell** [comment]
PR's are welcome... that's the best way to propose the change.

For the broken outdated links, I'd just remove them. When you submit the PR, pay attention to the automated reports it adds back to the comments as there may be other work that needs to be addressed.

TY!

**Comment by bigpix2000** [comment]
Closing the original issue .... I will create a new one for "broken links" more generally and specify which ones (then take it and fix as per our talk here)  thanks AC
