### ISSUE TITLE
Does this support SharePoint 2019 ?

### ISSUE THREAD

**Issue by OverkillTV** [SharePoint/sp-dev-docs#6445]
Does this support SharePoint 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4825eeab-f123-c0fb-0d30-6d634c821bd2
* Version Independent ID: 55d7e710-4faa-4cfa-772d-f83962d9fe52
* Content: [Use web parts with the full-width column](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column)
* Content Source: [docs/spfx/web-parts/basics/use-web-parts-full-width-column.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/use-web-parts-full-width-column.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Yes, it can be used in SharePoint 2019 with custom SPFX WebPart solution.
