### ISSUE TITLE
Trusting the self-signed developer certificate steps

### ISSUE THREAD

**Issue by mheptinstall** [SharePoint/sp-dev-docs#6447]
**Trusting the self-signed developer certificate** isn't very clear on what steps are required for a new user setting up their environment for the first time. 

Similar issue was raised previously in #2433.

Running `gulp trust-dev-cert` after successfully executing `npm install gulp yo @microsoft/generator-sharepoint --global` results in:

> PS C:\Users\mhept> gulp trust-dev-cert
> [12:58:34] Local gulp not found in ~
> [12:58:34] Try running: npm install gulp

The documentation states:

> A utility task is included in every SharePoint Framework project in the form of a gulp task. **_You can elect to do this now_**, or wait until you create your first project as covered in the Build your first SharePoint client-side web part (Hello World part 1) tutorial.

But then says:

> **_Once a project has been created_** with the Yeoman generator for the SharePoint Framework, **_execute the following command_** from within the root folder of the project.

So I can't elect to do this now without creating a project because I need to create a project first to trust the certificate. 

This section could be reworded to be much clearer on the actual steps required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The process is:
1. install the required packages globally (SP generator, Yeoman, & gulp)
1. create a new project with the generator & install all dependencies (the default action when you create a new project)
1. from within the project's root folder created in the previous step, run the **trust-dev-cert** task

**Comment by andrewconnell** [comment]
Good point about the doc wording... I'll get that tweaked...
