### ISSUE TITLE
Is it possible to install field customizer from list command set click?

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#6449]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Hello
I have 2 extensions, a listview context menu extension and a field customizer extension. What I was hoping to know is, is it possible to install the field customizer in a site from a click on the context menu extension, if the field customer is not installed in current site?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Edge
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
Technically, most likely yes you can do this. Programatically, you can install SPFx components using the SharePoint ALM REST API. While field customizers are typically installed with a new site column you can associate it with an existing site column using the REST API. You can obtain a reference to the site column you want to add the field customizer.

But remember:
- the user that clicks the command is who will be running this code & thus, they must have permission to do all this stuff... so you need to ensure you have a lot of defensive code to handle cases where they don't have the necessary permissions
- field customizers are added to site columns, not lists... so when you install it, it will affect the existing site column in the entire site

**Comment by RafatRashid** [comment]
Ok thanks a lot. Question, I want the added custom site column added to a particular list/document library. After installing the field customizer, the custom field needs to be added for whichever library/list I want it shown. I was wondering can I add the field to a sites libraries/lists?

**Comment by andrewconnell** [comment]
@RafatRashid said:

> can I add the field to a sites libraries/lists programmatically?

Yup... you can do that as part of the SharePoint REST API.

**Comment by RafatRashid** [comment]
> Yup... you can do that as part of the SharePoint REST API.

Was able to do this using <site>/_api/Web/Lists(guid'list id')/FIelds/CreateFieldAsXml endpoint. Couldnt find any official msdoc for this endpoint though.
Thanks

**Comment by andrewconnell** [comment]
Not that I'm aware of.
