### ISSUE TITLE
SPFx extension not displaying image asset coming from Microsoft 365 CDN

### ISSUE THREAD

**Issue by roberAlb** [SharePoint/sp-dev-docs#6450]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> I have a SPFx extension for the header which basically displays some images coming from Microsoft 365 CDN origin. In the classic experience, there was a auto-rewrite publishing feature which basically was replacing those urls to publiccdn.sharepoint..... but it's not happening into the SPFx extension, I have tested to build that static url manually inside of the extension and it's not working either.  Is the CDN supposed to work from a extension? If not, is there a way to load images from the Microsoft CDN from there?

## Environment details (*development & target environment*)

I tested that in a Team and Communication modern site collection

**Comment by patmill** [comment]
Can you see if this feature from the 1.13 release that might help you - https://docs.microsoft.com/en-us/javascript/api/sp-image-helper?view=sp-typescript-latest
