### ISSUE TITLE
ENOTSUP unsupported engine for got@5.7.1 @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by joehaan** [SharePoint/sp-dev-docs#6453]
Hi All,

I am unable to install @microsoft/generator-sharepoint --global as I am getting below error. Any pointers please.

=============================================

186 verbose stack Error: Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.23.0","npm":"6.14.8"})
186 verbose stack     at checkEngine (C:\Users\user2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:14:14)
186 verbose stack     at module.exports.isInstallable (C:\Users\user2\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:60:3)
186 verbose stack     at resolveWithNewModule (C:\Users\user2\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:677:10)
186 verbose stack     at C:\Users\user2\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:600:7
186 verbose stack     at a (C:\Users\user2\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\iferr.js:3:64)
186 verbose stack     at process.nextTick (C:\Users\user2\AppData\Roaming\npm\node_modules\npm\node_modules\call-limit\call-limit.js:28:43)
186 verbose stack     at process._tickCallback (internal/process/next_tick.js:61:11)
187 verbose pkgid got@5.7.1
188 verbose cwd C:\Windows\System32
189 verbose Windows_NT 10.0.17763
190 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user2\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "@microsoft/generator-sharepoint"
191 verbose node v10.23.0
192 verbose npm  v6.14.8
193 error code ENOTSUP
194 error notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.23.0","npm":"6.14.8"})
195 error notsup Not compatible with your version of node/npm: got@5.7.1
196 error notsup Not compatible with your version of node/npm: got@5.7.1
196 error notsup Required: {"node":">=0.10.0 <7"}
196 error notsup Actual:   {"npm":"6.14.8","node":"10.23.0"}
197 verbose exit [ 1, true ]
=====================================================

**Comment by Jerry0527** [comment]
Seems the Node.js you are using is 10.23.0, try to downgrade to Node.js v6.x to see if it works:

[Index of /dist/latest-v6.x/](https://nodejs.org/dist/latest-v6.x/)

**Comment by joehaan** [comment]
I tried earlier. By uninstalling the current Node.js and installing the version 6 still No Luck
actually I want it to be installed with V10.23 as per the documentation https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment. to get latest spfx

Below command fails with the above mentioned error.
npm install @microsoft/generator-sharepoint --global.

**Comment by Jerry0527** [comment]
Try to uninstall Node.js and then reinstall Node.js v10.x

 then please use this command, try to reinstall microsoft/generator-sharepoint

npm uninstall -g @microsoft/generator-sharepoint

npm install -g @microsoft/generator-sharepoint@latest
