### ISSUE TITLE
Add example response

### ISSUE THREAD

**Issue by RitaRomana** [SharePoint/sp-dev-docs#6457]
Would like to ask/suggest if it would be possible to add an example response for the Microsoft Graph API requests? 
Like you have on this article: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery#example-response-for-a-multi-geo-tenant

This helps in understanding what we should expect as an output of the API request.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273329da-9823-06ca-75b5-535a459954d9
* Version Independent ID: 5fbeb9f9-3b06-bd09-5603-d0780cc21a0d
* Content: [Access OneDrive for Business in a Multi-Geo tenant](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-onedrive#get-the-location-of-a-users-onedrive-for-business-site-using-microsoft-graph)
* Content Source: [docs/solution-guidance/multigeo-onedrive.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/multigeo-onedrive.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi! I highly recommend checking out the Microsoft Graph Explorer.  This will allow you to test out requests and see responses coming from Microsoft Graph. This is the best place for testing and viewing responses from the API.

https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by RitaRomana** [comment]
Hi! Thank you for getting back on this. 
Yes, I understood that the tool to use is Microsoft Graph Explorer. But my suggestion was to actually include an example output in the article - like it is included on the other article, as example (https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery#example-response-for-a-multi-geo-tenant) - as that can easily help the reader understand if that output provides the information they are searching for.

**Comment by bcameron1231** [comment]
@RitaRomana I had submitted a PR for this. Thanks!
