### ISSUE TITLE
Column Formatting on a Lookup Field to Document Library

### ISSUE THREAD

**Issue by Steven-Chorkawy** [SharePoint/sp-dev-docs#6459]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

Hello, 

I'm trying to format a lookup column in a list that is linked to a document library.  My goal is the create a clickable link that takes users directly to the list items related document.  
However the documents are located within folders and I am unable to get the direct path to the document.

Here is a sample of the JSON that I am using.  Would anyone be able to guide me on what I should be using for the href property? 
`{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
   "elmType": "a",
   "txtContent": "@currentField.lookupValue",
   "attributes": {
      "target": "_blank",
      "href": "=@currentWeb+'/Shared%20Documents/'+[$choice.lookupValue]"
   }
}`

**Comment by Amos-MSFT** [comment]
@Steven-Chorkawy Could you share how you define the lookup column?
Amos Wu
Microsoft SharePoint Community Support

**Comment by Steven-Chorkawy** [comment]
@Amos-MSFT Here is a screenshot of the column settings.  I hope this is what you were looking for.   Please let me know if I can provide anymore details. 
![image](https://user-images.githubusercontent.com/65408672/98866496-0924a900-243b-11eb-96f2-80bfadb764ce.png)

**Comment by Amos-MSFT** [comment]
You can update the ServerRelativeUrl of the file or folder to the Title column of the corresponding item, then use JSON format to get the ServerRelativeUrl.
Powershell Script for your reference:
```
Add-Type -Path "C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll"
Add-Type -Path "C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll"
    
#Set Variables
$SiteURL= "https://contoso.sharepoint.com/sites/dev"
$ListName="Doc"
  
$username = "amos@contoso.onmicrosoft.com"
$password = "password"
$Cred = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $userName, $(convertto-securestring $Password -asplaintext -force) 
Try {
    #Setup the context
    $Ctx = New-Object Microsoft.SharePoint.Client.ClientContext($SiteURL)
    $Ctx.Credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($Cred.UserName,$Cred.Password) 
    #Get All Items from the List
    $List = $Ctx.web.Lists.GetByTitle($ListName)
    $ListItems = $List.GetItems([Microsoft.SharePoint.Client.CamlQuery]::CreateAllItemsQuery())
    $Ctx.Load($ListItems)
    $Ctx.ExecuteQuery()       
    #Loop through each item
    ForEach($ListItem in $ListItems)
    {	
	$Ctx.Load($ListItem.ContentType)        
    	$Ctx.ExecuteQuery()
	if($ListItem.ContentType.Name -eq "Document"){
		$Ctx.Load($ListItem.File)
		$Ctx.ExecuteQuery()
		$ListItem["Title"] = $ListItem.File.ServerRelativeUrl 
	}
	if($ListItem.ContentType.Name -eq "Folder"){
		$Ctx.Load($ListItem.Folder)
		$Ctx.ExecuteQuery()
		$ListItem["Title"] = $ListItem.Folder.ServerRelativeUrl 
	}	
        $ListItem.Update()       
    $Ctx.ExecuteQuery()
}
Catch {
    write-host -f Red "Error: " $_.Exception.Message
}
```
![image](https://user-images.githubusercontent.com/56672877/98888744-7b48cc80-24d3-11eb-84d3-a7aab1cdd077.png)
Test JSON:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "txtContent": "@currentField.lookupValue",
  "attributes": {
    "target": "_blank",
    "href": "=[$look2.lookupValue]"
  }
}
```
Amos Wu
Microsoft SharePoint Community Support

**Comment by Steven-Chorkawy** [comment]
Hello Amos, 

Thank you for the detailed response!  I will give that a try.
