### ISSUE TITLE
🐞 Chrome JS console message not dark friendly

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#646]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When setting the Chrome debugging tools to the dark theme, nearly impossible to read the message or additional info URL SharePoint/SPFx is adding to it because it is hard coded to black text.

#### Observed Behavior

![image](https://user-images.githubusercontent.com/2068657/27151007-38c94d28-5117-11e7-9ec3-3481975c4f0d.png)

#### Steps to Reproduce
1. Set Chrome developer tools theme to dark (Open Dev Tools, COG => Settings => Preferences => Appearance => Theme = Dark).
1. Open Console in developer tools.

**Comment by patmill** [comment]
Cleaning up old issues.  The rendering of this is actually normal console logging now.
