### ISSUE TITLE
Is SPFx planning to migrate to ESLint?

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#6460]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is SPFx planning to migrate from TSLint to ESLint? If so, do you know when?

TSLint was deprecated more than 1 year ago (Feb 2019), maybe it is about time that SPFx aligns with the new standars?

Related to #4972.

**Comment by andrewconnell** [comment]
Microsoft hasn't stated anything publically about moving to ESLint at this time.
