### ISSUE TITLE
Application Throttling

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#6461]
Could you please let me know what type of application you are referring to in the "Application Throttling" section? Are you refering to Provider Hosted Application? 

[Application Throttling](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#application-throttling)
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Not only Provider Hosted Application.
Something like CSOM console application/ CSOM PowerShell/SharePoint Hosted Application/SPFX Application which used CSOM/Rest API endpoint will be involved in Applicatin Throttling.
