### ISSUE TITLE
Value shown in property panel is not updated on time if it is modified programmatically

### ISSUE THREAD

**Issue by tsekityam** [SharePoint/sp-dev-docs#6462]
## Category

- [x] Bug

## Describe the bug

When I update the property value programmatically, the value shown in property panel is not updated immediately. It updates after another key down or mouse click, however, it is lag behind.

![bug](https://user-images.githubusercontent.com/3814422/98923419-9422a380-250e-11eb-89e9-7b9646237360.gif)
at first I set *title* to `a` in code, the property panel of *title* shows ` `
then I set *title* to `ap` in code, the property panel of *title* shows `a`
etc.

## Steps to reproduce

1. `$ git clone https://github.com/tsekityam/spfx-update-property-panel-web-part.git`
1. `$ cd spfx-update-property-panel-web-part`
1. `$ npm i`
1. `$ gulp serve`
1. Add *Hello World* web part to the workbench page
1. Edit the web part
1. Enter some value in the title field in the web part body

## Expected behavior

The value shown in the property panel should reflect the latest value of the property.

## Environment details (*development & target environment*)

- **Your Developer Environment**: macOS 10.15.7
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Safari v14.0 & Chromium Edge v86
- **Tooling**: VS Code & SPFx v1.11.0

**Comment by Amos-MSFT** [comment]
You could add `this.context.propertyPane.refresh();` in updateProperty function.
```
export default class HelloWorldWebPart extends BaseClientSideWebPart<
  IHelloWorldWebPartProps
> {
  public render(): void {
    const element: React.ReactElement<IHelloWorldProps> = React.createElement(
      HelloWorld,
      {
        title: this.properties.title,
        displayMode: this.displayMode,
        updateProperty: (value: string) => {
          this.properties.title = value;
          this.context.propertyPane.refresh();
        },
      }
    );
      
    ReactDom.render(element, this.domElement);
  }

  protected onDispose(): void {
    ReactDom.unmountComponentAtNode(this.domElement);
  }

  protected get dataVersion(): Version {
    return Version.parse("1.0");
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          groups: [
            {
              groupFields: [
                PropertyPaneTextField("title", {
                  label: "Web part title",
                }),
              ],
            },
          ],
        },
      ],
    };
  }
}
```
My test result:
![test55](https://user-images.githubusercontent.com/56672877/99034792-f7691000-25b8-11eb-95fd-a5863846f266.gif)
Amos Wu
Microsoft SharePoint Community Support

**Comment by tsekityam** [comment]
Thanks, it works.
