### ISSUE TITLE
CommandBar extension not rendering in One Drive

### ISSUE THREAD

**Issue by duffysp** [SharePoint/sp-dev-docs#6463]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I currently have a command bar extension that works well on SharePoint. I'm looking to see if I can extend the same functionality into One Drive. I've not been able to find any documentation or posts about using SPFx/extensions in one drive.
I've managed to install the app onto my one drive site but the button doesn't render when I select a document in the library.
I'm guessing its possible as I also have an adobe add-on which _does_ render in the library as per the image below.

Is there any special switches or configuration that needs to be added to my command bar extension to get it to render in One Drive?

![image](https://user-images.githubusercontent.com/45501139/98929602-4dfc1e80-24d3-11eb-9564-a9b3114cd032.png)

**Comment by andrewconnell** [comment]
SPFx extensions are not supported in OneDrive, only SharePoint lists & document libraries.
