### ISSUE TITLE
SharePoint PnP Provisioning with Powershell - Data from template not imported properly

### ISSUE THREAD

**Issue by MARCJENN** [SharePoint/sp-dev-docs#6465]
## Category

- [x] SharePoint PnP Provisioning with Powershell - Data not saved properly in template

## Describe the bug

I am currently trying to use the PowerShell SharePoint PnP Module to deploy customized PnP Templates to a customer. 
The goal is to export several lists from one sharepoint site in a developer tenant to another, nearly identical sharepoint site in a customer tenant. 

The data in some of these exported lists (the elements in the list) should also be exported together with the template.

The PowerShell script "ExportPnPTemplate.ps1" uses the configuration through this code:

`Get-PnPProvisioningTemplate -Out PnPTemplate.xml -Configuration config.json -Schema V202002 -Force`
`$template = Read-PnPProvisioningTemplate PnPTemplate.xml`
`Save-PnPProvisioningTemplate -Template $template -Out PnPTemplate.pnp -force`

After running the script, the pnp template is created with the parameters of a seperate configuration file in json format. Please check the attached image for more information:

![image](https://user-images.githubusercontent.com/70281249/98948454-bd373a00-24f6-11eb-9fbf-89b5f77a27b1.png)

After exporting the template, the script "ImportPnPTemplate.ps1" is executed:

`Apply-PnPProvisioningTemplate PnPTemplate.pnp`

Both script create connections to the Developer Tenant and the Customer Tenant with Connect-PnPOnline first.

After checking the imported lists, created from exported the PnPTemplate, most data values were correctly exported and imported, with the sole exception of the "App Styles" list. **Most of the data fields inside this list were missing.** This behavior repeats even after changing values in the original Sharepoint list.

The sharepoint list before the export in the Developer Tenant:

![image](https://user-images.githubusercontent.com/70281249/98947326-55ccba80-24f5-11eb-9422-fa0e29d127bd.png)

The sharepoint list after the export, in the Customer Tenant:

![image](https://user-images.githubusercontent.com/70281249/98947999-2bc7c800-24f6-11eb-9f39-3cc65e9a813d.png)

Please notice how most of the values inside the list are missing, but title was imported correctly.

Does anyone have a solution? If theres more information required, please let me know.

## Steps to reproduce

1. Execute PowerShell Script "ExportPnPTemplate.ps1"
2. Check if PnPTemplate.pnp was created
3. Execute PowerShell Script "ImportPnPTemplate.ps1"
4. Login to customer tenant and check site values
5. Multiple data values in the fields are missing in list "App Styles"

## Expected behavior

1. Execute PowerShell Script "ExportPnPTemplate.ps1"
2. Check if PnPTemplate.pnp was created
3. Execute PowerShell Script "ImportPnPTemplate.ps1"
4. Login to customer tenant and check site values
5. The sharepoint site on the customer tenant was imported with all data in list "App Styles" included

## Environment details (*development & target environment*)

- Developer Environment: Windows 10, PowerShell 3.0, SharePoint Online
- TargetEnvironment: SharePoint Online
- Browser: Google Chrome, Edge
- Tooling: Microsoft PowerShell 3.0, Azure DevOps

**Comment by andrewconnell** [comment]
This should be posted to either the PNP POSH related repo or the provisioning framework... unfortunately this is a dev-only forum.
