### ISSUE TITLE
Localization not working in Application Customizers

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#6468]
## Category

- [x] Bug

## Describe the bug

SPFX Custom Application Customizers aren't using the provided locale JS string file for the current user's UI locale. SPFX Web Parts seem to be fine.

## Steps to reproduce

Have added localisation files other than en-us with strings to be used.

Have created a test user in one of the language (by setting in their Office profile) - the SharePoint interface (site contents, editing UX, etc) are all in that language.

SPFX Application Customer only loads the ***_en-us.js file and not the locale of the current user.

## Expected behavior

The strings in the Application Customizer are read from the correct locale for the current user

## Environment details (*development & target environment*)

- **Your Developer Environment**: Win 10
- **Target Environment**: SPO
- **Framework**: Node v8
- **Browser(s)**: Chrome latest
- **Tooling**: VS Code, SPFX 1.11

**Comment by MartinLaplante** [comment]
Are the application customizer and the web part on the same page?  If one works and the other doesn't on the same page, that would eliminate a couple of things that prevent or delay the profile language from being applied.  If not, possibly this issue #6302 with the length of the file name.

**Comment by jimmywim** [comment]
> Are the application customizer and the web part on the same page? If one works and the other doesn't on the same page, that would eliminate a couple of things that prevent or delay the profile language from being applied. If not, possibly this issue #6302 with the length of the file name.

Interesting, I'll have a look but our code isn't hosted in ClientSideAssets, we're using an Azure Blob storage-hosted CDN (served via an Azure CDN endpoint).

The weird thing is that PNP's SPFX Controls, referenced in my project, is loading the localised version.

**Comment by jimmywim** [comment]
My mistake, still has `includeClientSideAssets` set to `true` in our package-solution.json.

Set this to false and all works fine now.
