### ISSUE TITLE
'dataVersion' overridden problem

### ISSUE THREAD

**Issue by jf-grpo** [SharePoint/sp-dev-docs#6469]
## Question

Beginner with coding so please excuse any ignorant questions. And please let me know if I'm out of line with my submissions

Working on this tutorial:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part

Took two tries but it does render on local workbench despite this problem.

This appears as a Problem in the file JqueryWebParts.ts

**'dataVersion' is defined as a property in class 'BaseClientSideWebPart<IJqueryWebPartProps>', but is overridden here in 'JqueryWebPart' as an accessor.**

## Environment details

- **Development Environment [Windows 10]
- **Target Environment** [SharePoint Online] but working only locally
- **Framework** [Node.js v10]
- **Browser(s)** [FireFox v31]
- **Tooling**: [VS Code]

<img width="942" alt="ScreenshotJQueryWepPartTutorial" src="https://user-images.githubusercontent.com/61364175/99156547-3b2a4b00-2687-11eb-9e61-4c26b41ffd41.PNG">

**Comment by kongmengfei** [comment]
@jf-grpo，

You can just delete 'dataVersion' method to overcome the issue. It's compatible with SPFx v1.10 but will prompt errors in SPFx v1.11.

Baker Kong
Microsoft SharePoint Community Support
