### ISSUE TITLE
Manual Teams manifest - Static tab not working allways

### ISSUE THREAD

**Issue by diabhoil** [SharePoint/sp-dev-docs#6470]
The given url for the static/private tab is not working when the webpart is not globally deployed (or in the root site)
`"https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={{SPFX_COMPONENT_ID}}%26forceLocale={locale}"`
The dest parameter must start with a url where the app is installed, otherwise the app will not be found. I needed to change the url to something like this (where /sites/xyz is a sc where the spfx app is installed):
``"https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/xyz/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={{SPFX_COMPONENT_ID}}%26forceLocale={locale}"``

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sorry, but unclear what the question is.

**Comment by diabhoil** [comment]
I am not sure if it is a question or if it is just a missing hint on the linked documentation page. I was working for quite some time to figure out why my spfx webpart was not loading in a teams tab. Its just that the teamshostedapp.aspx can not find the webpart with the given id when it is not deployed to the site mentioned under the "dest" parameter. In Teams you just get the typical sharepoint error page with a correlation id which is not really helping. So maybe a small hint will help other developers not to have the same problem like I had.

I try to explain it with urls (spfx app installed in tenant **but not** globally deployed, deployed to site collection sites/xyz):
**Not working url like in the documentation**:
`https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={{SPFX_COMPONENT_ID}}%26forceLocale={locale}`
**Working**:
`https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/xyz/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={{SPFX_COMPONENT_ID}}%26forceLocale={locale}`

Oh and I just clicked the "feedback button" on the linked documentation page. So if I am wrong here I am sorry.
