### ISSUE TITLE
Error calling Azure Function from Domain-Isolated SPFx web part in local/remote workbench

### ISSUE THREAD

**Issue by TobiasHeck** [SharePoint/sp-dev-docs#6471]
## Category

- [x] Bug

## Describe the bug

I created a domain-isolated SPFx web part for SharePoint Online, which calls an Azure AD secured Azure Function. I added the web part to the SharePoint Online App Catalog, approved the "isolated" API request and checked in Azure AD that the App Registration for the web part includes the "user_impersonation" permission for my Azure Function App Registration.

I now want to use the local or remote workbench in Visual Studio Code to debug the web part, so I run "gulp serve", start debugging in VS Code and add the web part to the workbench page. It always throws the following exception in the workbench, as soon as it calls the Azure Function:

```
Error caught when calling API: Error: interaction_required: 
AADSTS65001: The user or administrator has not consented to use the application with ID 
'2cc...' named 'SharePoint Online Client Extensibility Web Application Principal'.
Send an interactive authorization request for this user and resource.
```

When I add the web part to a "normal" page on one of the sites and look at the Chrome debugger console, I see that it can call the Azure Function just fine.

I was under the impression that I should NOT add the Function App to the 'SharePoint Online Client Extensibility Web Application Principal' API permissions for domain-isolated web parts, as that would allow other SPFx solutions to use that API as well...

Are domain-isolated web parts supposed to be debugged in the workbench? Am I doing anything wrong?

By the way...the link https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues leads to a 404 for me.

## Steps to reproduce

1. Create a simple Azure Function, set up Azure AD authentication, let it create an app registration for you (e.g. by following this guide https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
2. Create a simple "Hello-World" SPFx web part as a domain isolated web part and add code to call the Azure Function from your web part (e.g. by following this guide: https://www.sharepointnutsandbolts.com/2019/04/spfx-isolated-web-parts-with-AadHttpClient.html) 
3. Start debugging in the local or remote workbench --> throws error
4. Add web part app to a site, add web part to a page --> works

## Expected behavior

I expected to be able to use the local and/or remote workbench to debug a domain isolated web part to call an Azure Function.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: SPFx | Node v10.23.0
- **Browser(s)**: Chrome 86.0.4240.193
- **Tooling**: VS Code latest version | SPFx v1.11.0

**Comment by andrewconnell** [comment]
The local workbench isn't expected to work because you aren't in a SharePoint context. Same with the local workbench because the code is running from within localhost, not in a SharePoint context.

@TobiasHeck said:

> By the way...the link https://github.com/sharepoint/playground-repo/wiki/How-to-Create-Good-Issues leads to a 404 for me.

Where did you see that link?

**Comment by TobiasHeck** [comment]
@andrewconnell thank you for taking the time to respond.
In your second sentence you wanted to refer to the hosted (I wrongly wrote remote in my question...) workbench, I assume?

I thought the hosted workbench was running in the SharePoint context and that I should be able to call AAD secured APIs from it as described in the docs e.g. here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#test-the-solution.

There are also several blog posts mentioning that you can call Azure Functions in the hosted workbench (e.g. https://spblog.net/post/2018/07/30/Call-Azure-AD-secured-API-from-your-SPFx-code-Story-3-Web-app-(or-Azure-Function)-and-SPFx-with-AadHttpClient).

And I am able to call the Azure Function from the hosted workbench, if I am **not** using a domain-isolated web part and thus using an organization-wide permitted API.
The error is only thrown if I use a domain-isolated web part and thus an "isolated" permitted API.

@andrewconnell said:
> Where did you see that link?

In the template used to create a bug ;-)
<img width="546" alt="Screenshot 2020-11-18 165059" src="https://user-images.githubusercontent.com/6728720/99553367-59ad8080-29be-11eb-988a-a9c9ccad6b6f.png">

**Comment by andrewconnell** [comment]
Yes, the hosted workbench will work, provided you've installed the app.

When you say hosted workbench, not sure if you installed the app previously, but that's required. Installation of the app is what creates the AAD app identity for that app. If you are just testing it like a non-isolated web part, SPFx is going to use the SPO AAD app.

Thanks for the link update... will get that fixed.

**Comment by TobiasHeck** [comment]
Thanks again for the follow-up!

I did install the domain-isolated web part through the tenant app catalog, approved the "isolated" API request in the admin center, checked that the Azure AD app was created for the web part and that it also contains the API permission for the requested Azure Function AAD app.

But I still can't get the web part to successfully call the Azure Function in the hosted workbench. It only works when I add it to a "real" page in one of the sites.
