### ISSUE TITLE
Support for SharePoint groups

### ISSUE THREAD

**Issue by JPMHuls** [SharePoint/sp-dev-docs#6473]
Dear team,

With regards to migrating classic SharePoint (2010) workflows to Power Automate Flows, would it be possible to make a statement on how to grant permissions to SharePoint groups. These don't seem be included yet and the workaround is to use the SharePoint REST API.

Thank you. Kind regards,

Jean-Pierre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970571ac-4a34-7ec7-a412-91ad243d24c0
* Version Independent ID: ae225235-4559-e28b-bc32-453a1b96dea5
* Content: [Manage list item and file permissions with Power Automate](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/manage-list-item-file-permissions)
* Content Source: [docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Yes, currently grant permission to a SharePoint group is only available to achieve using Rest API in flow:

$.ajax({
        url: _spPageContextInfo.webAbsoluteUrl + “/_api/web/roleassignments/addroleassignment(principalid=Group Id, roledefid=1073741827)",
        type: "POST",
        contentType: "application/json;odata=verbose",
        headers: { "Accept": "application/json; odata=verbose","X-RequestDigest": $("#__REQUESTDIGEST").val(),"X-HTTP-Method": "POST" },
        success: function (data) {
            // Returning the results
               alert('Contribute permission set on group');
        },
        error: function (data) {
               alert("Error: " + JSON.stringify(data));
        }
    });

roledefid for Permission Levels are as follows:

1073741829, Full Control

1073741827, Contribute

1073741826, Read

In the ms flow, action like this:

![Snipaste_2020-11-17_17-15-39](https://user-images.githubusercontent.com/28797671/99370345-88612380-28f8-11eb-92e9-9ebd30ea0584.png)

Reference:

[SharePoint Group Operations in Microsoft Flow](https://powerusers.microsoft.com/t5/Power-Automate-Community-Blog/SharePoint-Group-Operations-in-Microsoft-Flow/ba-p/394446)
