### ISSUE TITLE
FullCalendar example is out of date

### ISSUE THREAD

**Issue by fwd079** [SharePoint/sp-dev-docs#6474]
Outdated, [FullCalendar](https://fullcalendar.io/) is now on TypeScript, not JQuery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ecd027-f5ca-48c0-d60c-1883fa24ab96
* Version Independent ID: 9f38cbc9-464a-a2a4-0eeb-4deb6b2eb339
* Content: [Migrate jQuery and FullCalendar solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The article is demonstrating how to migrate the jQuery FullCalendar to SPFx... not the modern TypeScript one... thus it's not "outdated".

**Comment by fwd079** [comment]
> The article is demonstrating how to migrate the jQuery FullCalendar to SPFx... not the modern TypeScript one... thus it's not "outdated".

Yes that's my point, the **jQuery FullCalendar is outdated**. Current version is 5, the older v3 is just in maintenance mode and might retire at any time. So article is pointing to outdated things. May be show there it's an outdated library or word it better?

You comment would also be correct in another situations though, that Sharepoint web part doesn't support new version(s) / TypeScript itself etc.

Regards.

**Comment by andrewconnell** [comment]
Right, I understand that. The point is that there are people who have the older jQuery FullCalendar implemented & want to migrate to SPFx. It's an older article showing how to **migrate** a jQuery solution to SPFx. Migrate =! upgrade ;)

**Comment by fwd079** [comment]
Okay, whatever makes you happy. lol
