### ISSUE TITLE
How to make sharepoint online list column type as choice(what I describe) via site scrips and site designs?

### ISSUE THREAD

**Issue by macroicedeviance** [SharePoint/sp-dev-docs#6478]
## Category

- [ ] How to make sharepoint online list column type as choice via site scrips and site designs?
- [ ] I've created sharepoint online list via site scripts and site designs. However some columns' type should be choice(what I describe) in this online list.
- [ ] https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser**: [Chrome v84.0.4147.135]
- **Tooling**: [Microsoft.Online.SharePoint.PowerShell 16.0.20414.12000 | Visual Studio Code 2020]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

![Code](https://user-images.githubusercontent.com/8218863/99393699-c0fbff80-28ee-11eb-840d-7460228eb00c.png)

**Comment by bcameron1231** [comment]
You need to use the addSPFieldXml to set a choice field. An example is in the documentation.

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#addspfieldxml

**Comment by macroicedeviance** [comment]
Thanks for reference. Can you show me how to get it done?

{
                "verb": "createSPList",
                "listName": "Proje Bilgileri",
                "templateType": 100,
                "subactions": [
                    {
                        "verb": "setDescription",
                        "description": "Proje Bilgilerinin Yer Aldigi Listedir."
                    },
                    {
                        "verb": "addSPField",
                        "fieldType": "Text",
                        "displayName": "Proje Kodu",
                        "isRequired": true,
                        "addToDefaultView": true
                    },

How should I place below code into above code? For example, under "Proje Kodu" column, field dropdown needs to show "1", "2", "3". And is this Field ID a constant?

{
  "verb": "addSPFieldXml",
  "schemaXml": "<Field ID=\"{596cbd92-36e3-40cc-a910-0f53468ce5e4}\" Type=\"Choice\" DisplayName=\"Project Category\" Required=\"FALSE\" Format=\"Dropdown\" StaticName=\"ProjectCategory\" Name=\"ProjectCategory\"><Default>Operations</Default><CHOICES><CHOICE>Operations</CHOICE><CHOICE>IT</CHOICE><CHOICE>Legal</CHOICE><CHOICE>Engineering</CHOICE></CHOICES></Field>"
}

**Comment by Amos-MSFT** [comment]
You could try to use the following json:
```
{
   "verb":"createSPList",
   "listName":"Proje Bilgileri",
   "templateType":100,
   "subactions":[
      {
         "verb":"setDescription",
         "description":"Proje Bilgilerinin Yer Aldigi Listedir."
      },
      {
         "verb":"addSPField",
         "fieldType":"Text",
         "displayName":"Proje Kodu",
         "isRequired":true,
         "addToDefaultView":true
      },
      {
         "verb":"addSPFieldXml",
         "schemaXml":"<Field ID=\"{596cbd92-36e3-40cc-a910-0f53468ce5e4}\" Type=\"Choice\" DisplayName=\"Proje Kodu\" Required=\"FALSE\" Format=\"Dropdown\" StaticName=\"Proje Kodu\" Name=\"ProjectCategory\"><Default>1</Default><CHOICES><CHOICE>1</CHOICE><CHOICE>2</CHOICE><CHOICE>3</CHOICE></CHOICES></Field>"
      }
   ]
}
```
This ID value needs to be different from the ID values of other fields, and the ID is a GUID, you can generate it with code or get it directly from some websites that can generate GUID.
Amos Wu
Microsoft SharePoint Community Support
