### ISSUE TITLE
PropertyPaneTextField - onGetErrorMessage with Promise is clearing TextField value

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#6479]
If you add `onGetErrorMessage` which returns a Promise of an empty string (i.e. it passes validation), the value of the TextField is cleared when you click or Tab away (blur) from the TextField.

Sample Code:
```
protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
  return {
    pages: [
      {
        header: {
          description: strings.PropertyPaneDescription
        },
        groups: [
          {
            groupName: strings.BasicGroupName,
            groupFields: [
              PropertyPaneTextField('description', {
                label: strings.DescriptionFieldLabel,
                onGetErrorMessage: (): Promise<string> => {
                  return Promise.resolve('')
                }
              })
            ]
          }
        ]
      }
    ]
  };
}
```

Results:
![Demo](https://imgur.com/m4Ayl44.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08aa20fb-4cde-4ea6-8946-d67451e78e55
* Version Independent ID: 3c47f3e6-427a-681d-42c7-db0a821da0e9
* Content: [Validate web part property values](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values)
* Content Source: [docs/spfx/web-parts/guidance/validate-web-part-property-values.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/validate-web-part-property-values.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by juliemturner** [comment]
I can also confirm that I am seeing this issue in [LinksAndHandlebarsTemplate](https://github.com/pnp/sp-dev-solutions/tree/master/solutions/LinksAndHandlebarsTemplate) web parts which is currently in production in multiple tenants.

**Comment by garrytrinder** [comment]
I also seeing a similar behaviour with the out of the box Document Library web part, specifically the Folder property.

Validation works for a entering an incorrect value, but when entering a valid value, it disappears.

![libraryissue](https://user-images.githubusercontent.com/11563347/100106335-57d13a80-2e60-11eb-97b5-d4f915b7ba05.gif)

**Comment by KevinTCoughlin** [comment]
Thanks all for the repro. We've identified the break and have a fix.

**Comment by Christian-Stahl** [comment]
Ok, great me and my customer are waiting for this very welcome fix as well, keep us in the loop, thx!

**Comment by ruchira-sapkal** [comment]
Yes true. Pls keep us posted with the solution.

**Comment by AJIXuMuK** [comment]
Sorry for the long delay.
Seems like the issue has already been fixed.
Sorry for not posting it here.

@jimmywim - could you please check on your end?

Thanks!

**Comment by jimmywim** [comment]
@AJIXuMuK 

Hi, I've long gone from the original project where I reproduced this, but I can no longer reproduce the example @garrytrinder posted above in the Library web part. Think we can consider this closed.
