### ISSUE TITLE
Npm 5 & gulp error

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-docs#648]
Hello, has anyone had issues trying to build SPFx projects with Npm 5? I was getting an error on the local gulp module, which was "resolved" by downgrading Npm (in my case to 4.5.0).

#### Category
- [ X ] Bug

#### Expected or Desired Behavior
Ability to build SPFx project using Npm 5

#### Observed Behavior
Error on local gulp module

#### Steps to Reproduce
-Install latest Nodejs version (which contains Npm 5)
-Delete node_modules folder
-run 'npm install'
-run 'gulp serve' (or any other gulp task)
(I've also tried to delete all npm cache and relevant global npm modules before repeating the steps above, but didn't seem to make any difference)

Thanks
Joel

**Comment by qz2017** [comment]
We do not support NPM 5 yet. But It is in the plan. Thanks for your feedback.
