### ISSUE TITLE
Unable to load Angular WebPart in local workbench on Edge 42

### ISSUE THREAD

**Issue by Tokelin** [SharePoint/sp-dev-docs#6483]
## Category

- [x] Bug

## Describe the bug

When using the [@pnp/spfx](https://pnp.github.io/generator-spfx/howtos/angularelements/) generator and generate a simple HelloWorld project the Angular WebPart is unable to load when using `gulp serve` in Edge 42.17134.1.0

## Steps to reproduce

1. Follow instructions on the [@pnp/spfx](https://pnp.github.io/generator-spfx/howtos/angularelements/) page for generating an Angular SPFX solution
1. Run `gulp serve`
1. When the local workbench loads, press the '+' to add the Angular WebPart
1. The WebPart doesn't load and there are two errors in the console: 
```
[1605706764928][OtherGlobalError.window.onerro] Error: Error:[object ErrorEvent], file:undefined, line:undefined, column:undefined
TypeError: Function expected
```

## Expected behavior

The WebPart is loaded correctly and is visible.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.23.0
- **Browser(s)**: Edge 42.17134.1.0
- **Tooling**: VS Code, yeoman generator, @pnp/spfx

### Additional context

I have tested the generated solution in Firefox and Chrome and the error is not present. Also I have generated a new project using Vue.js and the WebPart is being displayed correctly

**Comment by andrewconnell** [comment]
Suggest you post this to the PNP SPFx generator's repo...

**Comment by StfBauer** [comment]
@Tokelin please do so, and it would be great to mention the Angular version because we support now form 6.0 to 10.0 atm.

**Comment by Tokelin** [comment]
I have created https://github.com/pnp/generator-spfx/issues/285
