### ISSUE TITLE
Incomplete type for themeProvider in IReadonlyTheme

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#6486]
## Category

- [x] Bug

## Describe the bug

The themeProvider object only returns limited typings compared to what gets returned the object returned.

```typescript
      this._themeProvider = this.context.serviceScope.consume(ThemeProvider.serviceKey);
      this._themeVariant = this._themeProvider.tryGetTheme();

      let effects = this._themeVariant.effects
```

In an SPFx solution it looks like this:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/5503835/99599192-2210f980-29fb-11eb-9fa9-027163f4f993.png">

In addition to building error:

```shell
TS2339: Property 'effects' does not exist on type 'IReadonlyTheme'.
```

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5503835/99599437-b11e1180-29fb-11eb-8ab3-2f8961c02a92.png">

The returned object contains the following elements:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5503835/99599498-c8f59580-29fb-11eb-95f3-483239cb619e.png">

## Steps to reproduce

Create SPFx Solution, and follow the instructions on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds

## Expected behavior

Support typings for all returned properties.

## Environment details (*development & target environment*)

Latest SPFx version.

**Comment by KevinTCoughlin** [comment]
We have a fix for the typings in-review. Once merged, they will be available next package publish.

**Comment by StfBauer** [comment]
Thank you @KevinTCoughlin

**Comment by AJIXuMuK** [comment]
@StfBauer  - could you please check if there are some missing parts in the interface?

Thanks!

**Comment by StfBauer** [comment]
No all-in since 1.13. as far as I see.
