### ISSUE TITLE
Getting “Sorry, something went wrong with adding the app. Click to retry.” when adding a SPFx library to a site

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6496]
## Category

- [x] Bug

## Describe the bug

I am getting “Sorry, something went wrong with adding the app. Click to retry.” when adding a SPFx library component to a site.

## Steps to reproduce

1. Create an out of the box SPFx Library component.
2. Upload to tenant app catalogue (don't deploy tenant wide)
3. Add the app to some site
4. Switch back to classic view on site contents to see the error

## Expected behavior

Apps successfully gets added to the site

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

Windows 10 
SharePoint Online
Node v10
Chrome 87
VS Code | SPFx v1.10.0

## Comments

I went into the app details for the instance to check the errors, but when I click the link I get this image. Then it just goes into a white page with no content.

![Capture333](https://user-images.githubusercontent.com/5560751/100114815-ceaa0b80-2e3f-11eb-9012-8ff65fb67ff1.PNG)

**Comment by andrewconnell** [comment]
First suggestion is to use the latest version of SPFx: v1.11.0.

If that doesn't resolve it, suggest posting your project to a public GH repo & post a link to it as without seeing the project, impossible to help.

**Comment by TheInvoker** [comment]
Thanks @andrewconnell  have checked the version using "npm ls -g --depth=0 @microsoft/generator-sharepoint " and it is indeed 1.11.0. In terms of the reproduction, there is actually nothing custom I have done, this is a pure out of the box example. Basically if you could do this you should se it too:

1. Create a SPFx Library component (choose no for allow choice to deploy tenant wide and no for require unique web apis) (do no edits after as well)
 
2. Deploy it on a "tenant app catalogue" (ensure it doesn't get deployed tenant wide)

3. Pick a site collection and add the library app component to that site (note, I am not referring to add to the site collection app catalogue, I mean just add the app to the site here).

4. In default modern view, you should see it being grey text for a long time. If you then click its settings button and then remove, it allows you to switch back to classic view. But at that point, you can see it says "Sorry something went wrong with adding the app...."

**Comment by cwdata** [comment]
@TheInvoker 
just out of curiosity, why do you want to deploy it only to one site? It is a library, so it won't show up anywhere in the UI even if you do tenant wide deployment. And afaik it also won't get copied to all sites. Most likely the tenant wide deployment will work.

**Comment by TheInvoker** [comment]
This is mainly due to different teams and regions working in the same tenant. The teams don't work together and every region's work is totally independent of others and managed by the owning teams only. But we all share the same tenant and tenant app catalogue. If I deploy my SPFx libraries tenant wide, it's possible it might conflict with one they are uploading as well. 

For example, to link one of my webpart apps with a library, I am supposed to put "my-utils":"0.0.1" in the package.json, then what if another region also makes a library with the same name and also puts in "my-utils":"0.0.1" in their webpart package.json. Feels like there would be a name collision and webparts would then import the wrong library causing them to break.

**Comment by cwdata** [comment]
Ok, but sticking to your example, if the other team uploads their my-utils package to the one central tenant app catalog, they will overwrite the lib from the first team. So that might be another problem. 
Using naming conventions like prefixing libraries with the team/region name or putting the library inside a site collection app catalog might solve this. I've read that using a site collection catalog for libraries should be possible but never used or tested that option.

**Comment by TheInvoker** [comment]
I didn't think just uploading to the tenant app catalogue would be an issue because even if the component name matches, the id would be different so it may not overwrite there. But the part I am more concerned about is the internal library name which the package.json references. I wouldn't want it to reference another regions library.

For the site collection app catalogue, in theory that could work, but the problem with that is, I also need to fully automate creating it with PnP provisioning site templates, and seems like making a site collection app catalogue for every site for 1 library is a bit overkill. Not only that, but what if I need to make an update to the library, I would then need to upload it to every site I have which is a lot. The maintenance work might be too much con than pro.

**Comment by AJIXuMuK** [comment]
Hello @TheInvoker  - sorry for the really long delay.
The issue seems to be fixed by now.
Could you please check on your end?

Thanks!
