### ISSUE TITLE
Preconfigured entry for SPFx Teams Tab

### ISSUE THREAD

**Issue by roberAlb** [SharePoint/sp-dev-docs#6499]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Basically we have a SPFx webpart with multiple preconfigured entries and we want to include it as Tab in Microsoft Teams. 
We have created a custom manifest for teams into the project and finally we are allowed to add it as a Tab. The questions is... Is there a way to specify which preconfigured entry for the settings do I want to display from Teams Tab? At the moment is displaying the first preconfigured entry of the webpart and I didn't see any option to specify it from the manifest. Thanks.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **SPFx version**: 1.10

**Comment by patmill** [comment]
Sorry for missing this.  No, at this point you are correct, and we use the first preConfiguredEntry.  We could look into extending that in the future - we'll keep it in mind.  Thanks for posting, and sorry for the extremely delayed response.
