### ISSUE TITLE
SharePoint Online - custom javasript file event not firing on document library

### ISSUE THREAD

**Issue by Mykie89** [SharePoint/sp-dev-docs#6500]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I added custom JavaScript file to all pages in a SharePoint Framework Extension, in the file I set the logo "href" attribute and add custom css class to the top navigation ( I want to mark the selected subsite in the navigation with bold font), The custom javascript file work fine, but If I navigate to any document library, the script stopped working, functions are not called and no error in console.
My custom.js file:

```
function defer(method) {
    if (window.jQuery)
        method();
    else
        setTimeout(function() { defer(method) }, 100);
}
function setLogoUrl() {
    $('[class^="logoWrapper"]').attr("href",$("#HiddenSiteAbsoluteURL").text());
    setSelectedMenu();
    $(".ms-Nav-navItem").on("click", function(){
    	setSelectedMenu();
    });
}
function setSelectedMenu(){
   var url = window.location.href.toLowerCase();
   if(url.indexOf("/support") > -1){
       $('span[class="ms-HorizontalNavItem"] > a[href*="/support"]').addClass("selectedTopNav");
   }
}
defer(setLogoUrl);
```
I tried a lot of load, and read functions, but still not working.
Tried code:
```
jQuery('body').click(function() {
	setSelectedMenu();
});
jQuery('.ms-HorizontalNavItems').load(function() {
	setSelectedMenu();
});
jQuery('body').ready(function() {
	setSelectedMenu();
});

jQuery(window).load(function() {
  setSelectedMenu();
});

jQuery(document).ready(function() {

jQuery('body').trigger( "click" );

});
```
Only `jQuery('body').click(function()` function working, but click event is not a solution.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**: e.g. Chrome v87

**Comment by andrewconnell** [comment]
Note that you're doing DOM manipulation, something that explicitly not supported in SharePoint.

See the **Important** block here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#in-perspective-sharepoint-framework-in-the-broader-sharepoint-platform
