### ISSUE TITLE
SharePoint Online Active Authentication with Two Factor Authentication

### ISSUE THREAD

**Issue by filippotoso** [SharePoint/sp-dev-docs#6503]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is there a way to make the implementation suggested by Vitaly Lyamin, working with Two Factor Authentication?

https://docs.microsoft.com/it-it/archive/blogs/sharepointdevelopersupport/sharepoint-online-active-authentication

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 Pro
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v12
- **Browser(s)**: Chrome v87
- **Tooling**: VS Code
- **Additional details**: I have a working implementation of the SharePoint Online Active Authentication suggested by Vitaly Lyamin. The customer activated the Two Factor Authentication on the whole domain and it stopped working. Is there a way to obtain the SPOIDCRL cookie in this context?

**Comment by andrewconnell** [comment]
Unclear what exactly you're asking... are you asking if you can automate authenticating for an account with MFA enabled? If so, then no... MFA requires user interaction.

**Comment by filippotoso** [comment]
I need to acquire the SPOIDCRL cookie as described in the Vitaly Lyamin in an environment that required MFA.
Without MFA I am able to obtain it and use it for API calls. 

What are the steps to support the MFA part (including the obvious user interaction) to obtain the SPOIDCRL cookie in the context with Custom STS and without (Using MSO STS only).

**Comment by kongmengfei** [comment]
@filippotoso,

You may consider using App password to get this cookie. This password act as the same role as user password but won't require mfa. 

Visit http://aka.ms/createapppassword to create an App password for your MFA enabled account(s), Then connect to SharePoint Online with the App password!

Test: 

![image](https://user-images.githubusercontent.com/57654821/102976377-6df41880-453c-11eb-8c2b-22e93eb7f253.png)
![image](https://user-images.githubusercontent.com/57654821/102976452-882df680-453c-11eb-9d43-91ddf4440d60.png)

Baker Kong
Microsoft SharePoint Community Support
