### ISSUE TITLE
Gulp package-solution --ship error after migrating to SPFx 1.11

### ISSUE THREAD

**Issue by MichelLaplane** [SharePoint/sp-dev-docs#6506]
After migrate with your suggestion, when packaging the solution there is an error

Error - 'package-solution' sub task errored after 171 ms 
 Cannot read property 'name' of undefined

You must also upgrade the "package-solution.json" file in adding a developer section 

```json
{
    "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
    "solution": {
        "name": "Your Webart Name",
        "id": "47c915dd-b5e5-4c2e-82f3-c6075c21b3bb",
        "version": "1.0.0.0",
        "includeClientSideAssets": true,
        "isDomainIsolated": false,
        "developer": {
            "name": "",
            "websiteUrl": "",
            "privacyUrl": "",
            "termsOfUseUrl": "",
            "mpnId": ""
            }
    },
    "paths": {
        "zippedPackage": "solution/process-guide.sppkg"
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ca1a68-c91c-077f-b082-c5184af9b93f
* Version Independent ID: b6b0f7ff-4f39-b05d-c203-92f5aaec3f63
* Content: [SharePoint Framework v1.11 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0)
* Content Source: [docs/spfx/release-1.11.0.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.11.0.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Try to add developer section in package-solution.json to resolve this issue:

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "jerrytest-client-side-solution",
    "id": "5ec36f58-4fce-4371-9000-805fc3041c31",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    }
  },
  "paths": {
    "zippedPackage": "solution/jerrytest.sppkg"
  }
}

After adding the developer section try to rerun gulp package-solution should be working.

**Comment by andrewconnell** [comment]
@Jerry0527 Look at their OP... it's already there.

**Comment by andrewconnell** [comment]
@MichelLaplane I see a similar issue... not sure if there's a regression... investigating...

**Comment by Jerry0527** [comment]
@andrewconnell,

Look at the error message:

Error - 'package-solution' sub task errored after 171 ms
Cannot read property 'name' of undefined

You must also upgrade the "package-solution.json" file in adding a developer section

Clearly, the error message specify the developer section, right ?

I suggest OP to double check this point and in my side, it's working as expected.....

**Comment by MichelLaplane** [comment]
Hi Andrew,
Yes it is just the developer section that should be added from an old project when you migrate to 1.11. 
The issue i have raised was just to point out that this operation must be added to the post "How to update a project from 1.10 to 1.11".
Regards

**Comment by andrewconnell** [comment]
@MichelLaplane said:

> Yes it is just the developer section that should be added from an old project when you migrate to 1.11. The issue i have raised was just to point out that this operation must be added to the post "How to update a project from 1.10 to 1.11".

Correct, but that is already in that section. Immediately after the section, you reference, there is an **important** callout block that explicitly states this, and provides a link with details on it. The upgrade section isn't intended to be complete instructions, rather an overview. That's why you don't see all the packages listed that you need to upgrade.

@Jerry0527 said:

> You must also upgrade the "package-solution.json" file in adding a developer section. Clearly, the error message specify the developer section, right ?

Correct, but if you look at the OP in this thread, the submitter clearly added the `developer` section to the **package-solution.json** file.
