### ISSUE TITLE
Creating items in PnP Provisioning in SP Online site templates does not work

### ISSUE THREAD

**Issue by TheInvoker** [SharePoint/sp-dev-docs#6510]
## Category

- [x] Bug

## Describe the bug

I am creating templates using the PnP provisioning but am noticing the items are not being created. I have this `template.json` file

```
{
    "$schema":"https://aka.ms/sppnp-extract-configuration-schema",
    "persistAssetFiles": false,
    "handlers": [
        "Lists",
        "WebSettings",
        "Pages"
    ],
    "lists": {
        "lists": [
            {
                "title": "MyData",
                "includeItems": true
            }
        ]
    },
    "pages": {
        "includeAllClientSidePages": true
    }
}
```

and the exported XML file has the datarows data in it, but when I apply it to a site, the lists that get created don't have the data in it. Does anyone know what's wrong?

## Steps to reproduce

1. Create a site and a list `MyData` in it with some data
2. Save it using `Get-PnPProvisioningTemplate -Configuration "template.json" -Out "template.xml" -Force`
3. Create new site and apply template to it using `Apply-PnPProvisioningTemplate -Path "template.xml"`

## Expected behavior

Items to be created in the provisioned lists

## Environment details (*development & target environment*)

Windows 10
SharePoint Online
Node v10
Chrome 87
VS Code | SPFx v1.11.0

**Comment by andrewconnell** [comment]
This question should be posted to the PnP provisioning repo's issue list as it's specific to provisioning, not general SP dev which is what this issue list is for. You're likely to get a better chance at a response there.

**Comment by kongmengfei** [comment]
@TheInvoker,

Just tested your JSON and PowerShell cmdlets in my environment. Yeah, it did export the data rows but not create any item in the target site. 

However, if I delete all system fields and only keep 'Title' field in `<pnp:DataRow>`, it works fine, the item will be created. 

`
<pnp:DataRows UpdateBehavior="Overwrite">  
    <pnp:DataRow>
         <pnp:DataValue FieldName="Title">jytjtyjo</pnp:DataValue>
    </pnp:DataRow>
</pnp:DataRows>
`

So I suspect that some fields (especially the built-in fields) can not be imported, which will cause the item creation gets failed.

Hence I suggest you only keep the expected fields. Or you can use `Add-PnPDataRowsToProvisioningTemplate` to help to add data rows. 

- https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpdatarowstoprovisioningtemplate?view=sharepoint-ps

Baker Kong
Microsoft SharePoint Community Support

**Comment by TheInvoker** [comment]
Haven't testing the applying template to a site yet, but a shorter version of choosing the fields to extract for items is

            {
                "title": "Banner",
                "includeItems": true,
                "query": {
                    "viewFields": ["Title"]
                }
            },
