### ISSUE TITLE
How to create empty folder under Documents folder on sharepoint site via site scripts and site designs?

### ISSUE THREAD

**Issue by macroicedeviance** [SharePoint/sp-dev-docs#6514]
## Category

- [ ] How to create empty folder under Documents folder on sharepoint site via site scrips and site designs?
- [ ] I am trying to create a sharepoint team site template via site scripts and site designs. In this template, I need to create a some folders under "Documents" folder.
- [ ] https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Browser(s)**: Chrome v84.0.4147.135 | Edge
- **Tooling**: [Microsoft.Online.SharePoint.PowerShell 16.0.20414.12000 | Visual Studio Code 2020]

![image](https://user-images.githubusercontent.com/8218863/100582261-06aac600-32fa-11eb-90d6-9b1c7278b8d6.png)

**Comment by Amos-MSFT** [comment]
There is no action about creating a list item/file in the official documentation.
You could get all supported actions in the following documentation.
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema
Amos Wu
Microsoft SharePoint Community Support

**Comment by bcameron1231** [comment]
Yup. This action currently is an experimental feature and hasn't been released yet.

**Comment by macroicedeviance** [comment]
Thanks for the information. Good to know that improving.
