### ISSUE TITLE
@me problems

### ISSUE THREAD

**Issue by CCC-Jonathan** [SharePoint/sp-dev-docs#6517]
In my list, when I am formatting the view with JSON.  The "@me" doesn't seem to be working.
We have something like:
...
          {
            "elmType": "div",
            "attributes": {
              "class": "sp-card-displayColumnContainer"
            },
            "children": [
              {
                "elmType": "p",
                "attributes": {
                  "class": "ms-fontColor-neutralPrimary sp-card-content sp-card-highlightedContent"
                },
                "txtContent": "=if ([$BidderNo] == @me, 'You are the Highest bidder', [$BidderNo])"
              }
            ]
          }
...

This if statement is always false.
We have tried
                "txtContent": "=@me"
and
                "txtContent": "@me"
and even
                "txtContent": @me

How do we get the @me to work?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Same question with [@me is not retrieving the current user's email.](https://github.com/SharePoint/sp-dev-docs/issues/6516), Let's discuss there.

**Comment by andrewconnell** [comment]
Dupe #6516
