### ISSUE TITLE
Cannot update App in tenant App Catalog as file is checked out by user who no longer exists in AD

### ISSUE THREAD

**Issue by saderbm** [SharePoint/sp-dev-docs#6521]
## How do I update an app in the app catalog that is checked out by a user who no longer works for the organisation and has had their AD profile deleted? The error I get is: 

**"The file customlearning.sppkg has been checked out by i:0#.f|membership|*******@***.org.uk on 6/16/2020 9:42 AM"**

Asterisks denote personal info. The file can't be deleted or overwritten in the library. When I check the files which aren't currently checked in on library settings, the section is empty. 

- Windows 10 Pro
- SharePoint Online
- I have Global Admin priveleges and I own the library where the apps are stored/deployed

I have had a chat with a Sharepoint Engineer from Microsoft who said they would get back to me, but they pointed me in the direction of GitHub for help.

**Comment by andrewconnell** [comment]
@saderbm said:
> I have had a chat with a Sharepoint Engineer from Microsoft who said they would get back to me, but they pointed me in the direction of GitHub for help.

Best to post this to TechCommunity... this is for developer-specific questions, but this is more of an ITPro/OOTB permissioning question which is what TechCommunity is for.
