### ISSUE TITLE
Can I design sharepoint team site's homepage with web parts(selected of mine) via site-design-script-actions.schema.json?

### ISSUE THREAD

**Issue by macroicedeviance** [SharePoint/sp-dev-docs#6525]
## Question

- [ ] Can I design sharepoint team site's home page with web parts(my selected) via site-design-script-actions.schema.json?
- [ ] I've created sharepoint team site via site scripts and site designs. I would like to design home page as my selected web parts. So some web parts will be added and some will be deleted. If I can do that, can I describe size of each web part? I guess, this is a bit too much for site-design-script-actions.schema.json.
- [ ] https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Browser(s)**: [Chrome v84.0.4147.135 | Edge]
- **Tooling**: [Microsoft.Online.SharePoint.PowerShell 16.0.20414.12000 | Visual Studio Code 2020]

**Comment by bcameron1231** [comment]
Unfortunately no. Site Designs do not support any page or web part changes. Currently, the only option would be to look into PnP Provisioning.

**Comment by macroicedeviance** [comment]
Thanks again. @bcameron1231 What is the best resource to learn PnP Provisioning for newbies?
