### ISSUE TITLE
There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

### ISSUE THREAD

**Issue by sekharB487** [SharePoint/sp-dev-docs#6526]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

> I have deployed pnp-modern-search package in appcatalog. trying to add **Search Result webpart** in modern site page. and getting below errors.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10.20]
- **Browser(s)**: [IE v11 | Edge ]
- **Tooling**: [VS Code]
- **Additional details**: pnp-modern-search v3.16 and 3.15

![image](https://user-images.githubusercontent.com/71835451/100974569-7f13c000-3562-11eb-8f8e-df74256eb9ca.png)
![image](https://user-images.githubusercontent.com/71835451/100974887-11b45f00-3563-11eb-9cc8-cb88d443e312.png)

Could any one please help. Its Urgent!!!! 
Thanks in Advance.

**Comment by andrewconnell** [comment]
Suggest you post this question to the project repo's issue list: https://github.com/microsoft-search/pnp-modern-search

This forum is for SP development questions.
