### ISSUE TITLE
yoman sharepoint generator list view command: Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by kboecher2** [SharePoint/sp-dev-docs#6527]
## Category

- [X ] Question
- [ ] Typo
- [ ] Additional article idea

## Question
using yoman sharepoint generator list view I get the following effor, when adding to an existing project: 
command: Error:

Error: ENOENT: no such file or directory, scandir 'C:\Users\XXX\AppData\Roaming\npm\node_modules\@microsoft\generator-sharepoint\lib\generators\commandSet\templates\react'

There is no folder called react there - I have reinstalled the generatror but i doesn't come up anyway- I have checked with a colleque, and he can use the same generator, even though he also doesn't have that folder. 

## Environment details (*development & target environment*)

Windows 10
SharePoint Online
* NodeJS: 8:11
* NPM: 6.6.0
@microsoft/generator-sharepoint@1.11.0

**Comment by bcameron1231** [comment]
hi, can you please check the compatibility matrix on the SPFx compatibility page. Using SPFx 1.11.0, it's recommended you use Node LTS 10. 

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility

Could you update to 10 and let us know if the error goes away?
