### ISSUE TITLE
Is there a roadmap for this feature?

### ISSUE THREAD

**Issue by dsmeltz** [SharePoint/sp-dev-docs#6530]
Is there a roadmap for the ability to embed modern SharePoint pages into MS Teams?  The functionality is fantastic, but we really need it to be in production before moving forward.  (Notably being able to see the site navigation for the SharePoint site, while viewing in Teams.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
At this time Microsoft has not shared any public timetable when this will be rolled into GA or listed this on the public M365 roadmap.
