### ISSUE TITLE
Webpart doesn't render correctly

### ISSUE THREAD

**Issue by Thomas-1111** [SharePoint/sp-dev-docs#6532]
## Issue

I have followed the tutorial (Add jQueryUI Accordion to your SharePoint client-side web part) and can not get the html to render into the accordion style. 

![image](https://user-images.githubusercontent.com/67689823/101169928-92439000-3635-11eb-89e3-f406ea7828ca.png)

I'm sure this is something that I've done wrong, but I cannot find the issue. 

Here is a .txt file containing the code that I am using.
[JQueryWebPart.txt](https://github.com/SharePoint/sp-dev-docs/files/5643050/JQueryWebPart.txt)

**Comment by bcameron1231** [comment]
Can you open up Developer tools (F12), I suspect there is an error in your console that will provide you some information on the issue.

**Comment by Thomas-1111** [comment]
![image](https://user-images.githubusercontent.com/67689823/101172125-a937b180-3638-11eb-88fa-ea905e1fad2b.png)
Does this help?

**Comment by bcameron1231** [comment]
Ya you definitely have errors loading JQuery. Can you confirm you accurately followed the steps in the tutorial and didn't miss a step? Possibly an incorrect value in your config.json?

**Comment by Thomas-1111** [comment]
I'm pretty confident. I went through and watched the video to ensure that there wasn't anything else that I missed. I made sure to copy and paste everything to avoid any silly errors. I have put the important documents into notepad files for you to see. 
[JQueryWebPart.txt](https://github.com/SharePoint/sp-dev-docs/files/5643464/JQueryWebPart.txt)
[MyAccordionTemplate.ts.txt](https://github.com/SharePoint/sp-dev-docs/files/5643465/MyAccordionTemplate.ts.txt)
[config.json.txt](https://github.com/SharePoint/sp-dev-docs/files/5643466/config.json.txt)


I have attached a wetransfer link for you to see the files yourself. I'm not sure if this is allowed, but thought it's the best way to get them over to you
https://we.tl/t-Jol1spA4uT

**Comment by bcameron1231** [comment]
Im having trouble opening the zip. Did you include the node_modules folder? If you did, could you delete that folder, re-zip it and send it again? Thanks

**Comment by Thomas-1111** [comment]
Yes, of course. I hope this helps!!

Let me know if this doesn't work and I'll try it on we transfer.

[jquery-webpart.zip](https://github.com/SharePoint/sp-dev-docs/files/5644067/jquery-webpart.zip)

**Comment by bcameron1231** [comment]
You have a typo.

![image](https://user-images.githubusercontent.com/7944457/101196315-cf038d00-361d-11eb-9fed-55c391fb7a30.png)


Your import should be a capital Q.

`import * as jQuery from 'jquery';`
