### ISSUE TITLE
Extension: How to get page display mode - read or edit mode.

### ISSUE THREAD

**Issue by lrolseth** [SharePoint/sp-dev-docs#6535]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

How can I get the current page display mode via a SPFx extension?  DisplayMode is only for web parts.
I want to determine if the page is in edit or display mode. 

@microsoft/sp-build-web": "1.11.0",

**Comment by Jerry0527** [comment]
When page is in Edit Mode, the url will append "Mode=Edit" in the url, so please detect if the page in edit mode like this in Extension:
![Snipaste_2020-12-07_16-04-00](https://user-images.githubusercontent.com/28797671/101324878-d63ccc00-38a5-11eb-9fdc-8531a962f78e.png)


  if(document.location.href.indexOf('Mode=Edit')!==-1)
    {
      Dialog.alert('page is in edit mode');
    }

Here is a blog with the complete demo for your reference:

[Check the page display mode from within your SharePoint Framework extensions](https://www.eliostruyf.com/check-page-mode-from-within-spfx-extensions/)
