### ISSUE TITLE
code in doc: fix parameter "wi"

### ISSUE THREAD

**Issue by anhvoduy** [SharePoint/sp-dev-docs#6538]
[fix parameter "wi"]

TokenWaitInfo wi = new TokenWaitInfo();
wi.Handle = ThreadPool.RegisterWaitForSingleObject(
...................................................................................................
if (!timedOut)
{
        TokenWaitInfo wi1 = (TokenWaitInfo)state;
        if (wi1.Handle != null)
        {
            wi1.Handle.Unregister(null);
        }
}
...................................................................................................
,wi,
(uint)CalculateThreadSleep(accessToken).TotalMilliseconds,
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Can you please provide more context around your submission? What's wrong with the existing, what are you changing, etc. Providing updated code with zero context isn't clear...

**Comment by anhvoduy** [comment]
I run the code from link: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard
see that: 
- variable "wi" was declared firstly at line:               "TokenWaitInfo wi = new TokenWaitInfo();"
- and variable "wi" was declared secondly at line:   "TokenWaitInfo wi = (TokenWaitInfo)state;"
please update for build/running with visual studio 2019.

**Comment by andrewconnell** [comment]
Oh... so you're saying the code in the doc is incorrect because it overwrites an existing variable? OK... that makes sense.

It helps to explain WHY something is wrong and WHAT you're fixing rather than just submitting code saying "fixes X" :)
