### ISSUE TITLE
Webparts Randomly Fail to Load, Giving "n._internalInitialize is not a function" Error

### ISSUE THREAD

**Issue by kbroskie** [SharePoint/sp-dev-docs#6546]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
I have created a number of webparts using React that I have deployed to the app catalog of a SharePoint Online site. When loading a page containing various webparts, I am randomly experiencing an issue when loading a modern page containing them. Sometimes all of the content loads fine, but other times, 1 or more of the webparts will fail to load. When they fail to load, I get the standard "Something went wrong" error shown in this screenshot:
![image](https://user-images.githubusercontent.com/6606932/101632432-e662c180-39f3-11eb-8b1b-f4605a4087a9.png)

I am not sure how to resolve this issue and would appreciate help. There is nothing in the developer tools console that provides any additional information about this error. The only errors present are errors that are also present when all of the webparts do load successfully. These errors are:
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:799505
> Uncaught ReferenceError: exports is not defined
>     <anonymous> <site-url>/_layouts/15/activitymonitor.js:25
> 

## Environment details (if applicable)
- **Your Developer Environment**: MacOS 10.15.7
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.22.0
- **Browser(s)**: Chrome v 87.0.4280.88 and FireFox v83.0
- **Tooling**: VS Code
- **Additional details**: Git repo containing code: https://github.com/kbroskie/spfx-welcome-message

**Comment by AJIXuMuK** [comment]
Hello @kbroskie - sorry for the really long delay.
There were many changes with the initialization and navigation.
And the issue you've experienced seems to be fixed.

Could you please check it on your side?

**Comment by kbroskie** [comment]
I am still working on determining if this issue persists. I did discover that the issue stems from another extension I have that loads an external JS script. I had to remove the extension to resolve the issue. Not the resolution I would like to get. The extension loads a script via the below method (actual URL removed for security purposes):
`
  @override
  public onInit(): Promise<void> {
    const scriptUrl = this.properties.scripturl;

    if (scriptUrl) {
      const head: any = document.getElementsByTagName ("head")[0] || document.documentElement;
      let chatBotScript: HTMLScriptElement = document.createElement ("script");

      chatBotScript.type = 'text/javascript';
      chatBotScript.src = scriptUrl;
      chatBotScript.async = true;
      chatBotScript.referrerPolicy = 'no-referrer-when-downgrade';
      head.insertAdjacentElement ("beforeEnd", chatBotScript);
    }

    return Promise.resolve();
  }
}`

**Comment by AJIXuMuK** [comment]
@kbroskie - that is an interesting observation. 
Seems like loading this additional script somehow breaks the pointer/reference to the web part's manifest/script (which is also loading asynchronously at that moment).

What I would suggest is to try using `SPComponentLoader.loadScript` (https://docs.microsoft.com/en-us/javascript/api/sp-loader/spcomponentloader?view=sp-typescript-latest#loadScript_url__options_) instead of direct appending of `<script>` element into the DOM.

Could you please try that and see if the issue is gone?

**Comment by kbroskie** [comment]
I have not had time to look into this yet. I will as soon as I can.

**Comment by AJIXuMuK** [comment]
@kbroskie - I will close this one due to inactivity.
Feel free to open a new issue as a follow up of this one if the suggested workaround doesn't work or you have any other questions/bugs.

Thanks!
