### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by LeopoldLerch** [SharePoint/sp-dev-docs#6547]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I know it is a common question, but: 
As TSLint is not supported anymore and completely replaced by the Typescript-Plugins for Eslint, maybe you can rethink the hard inclusion of Eslint in the SPFx templates? I have to also emphasize the fact, that this also somehow blocks us from using the eslint-plugin-react-hooks, provided and recommended by React. 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: React
- **Browser(s)**: [Chrome  | Firefox | IE v11 | Edge | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | SPFx v1.10.0]

**Comment by andrewconnell** [comment]
At this time MSFT hasn't publically said anything about moving to ESLint... might be best to suggest this as a request to user voice...
