### ISSUE TITLE
SharePoint add-in for USGCC High  

### ISSUE THREAD

**Issue by winperec** [SharePoint/sp-dev-docs#6549]
The article describes where to register SharePoint Add-ins depends on location
https://docs.microsoft.com/en-us/office/dev/store/create-or-update-client-ids-and-secrets
But what about US Government customers? According to this article https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-plan-identity#selecting-identity-for-an-azure-government-application
there are two kind of US Gov customers:
- US GCC who is hosted in Public Azure AD. This kind of customers can use regular SharePoint ACS endpoints and client id and client secrets which is registered in Seller Dashboard

- GCC High or DoD who is hosted in Azure Government AD - what end points should they use? How to register client id, client secret if ISV has multitenant add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be8c8d6-7ed2-1907-3038-49d8e1c92e8a
* Version Independent ID: a2adbe13-e625-3995-fded-fce6c4a701ac
* Content: [Register SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/register-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by winperec** [comment]
@andrewconnell any chance to get some insights on this question?

**Comment by andrewconnell** [comment]
Sure, but not by me 😀 ...  I don't know anything about GCC. I just triaged the type of question.

In my opinion, you'll likely get a better chance at a response by posting to TechCommunity which is where non-developer topics go.
