### ISSUE TITLE
Inconsistent hookin' of old-skool custom action in modern view

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#655]
#### Category
- [x] Bug

#### Expected or Desired Behavior
When you navigate between lists and libraries, the custom action should appear and be removed from the ribbon according to the settings for that list.

#### Observed Behavior
The ribbon action is "stuck" when moving from a library with the action, and over to for example a list which should not have the custom action.

#### Steps to Reproduce
1.	Applied the sample prov template for ribbon actions for 101 doc libs (https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-lists-and-libraries)
2.	Navigate to a doc lib and custom action shows
3.	Navigate to Pages, and the custom action “sticks” and still shows, hard refresh and it’s removed
4.	Navigate back to Documents, and custom action is not showing, hard refresh and it’s back

**Comment by patmill** [comment]
Just to confirm what you are seeing.  You install the commandset into list1, but when you navigate from list to list (presumably using left nav), the commandset remains loaded?

**Comment by wobba** [comment]
Correct, using the left nav moving back and forth. Hard refresh solves it.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
