### ISSUE TITLE
onDisplayModeChanged not called when client page changes display mode

### ISSUE THREAD

**Issue by jklevel** [SharePoint/sp-dev-docs#6552]
## Category

- [x] Bug

## Describe the bug

We have some web part that use onDisplayModeChanged to execute code for saving data etc - and they have worked fine for months - until some days ago.

It works fine on two tested tenants, but not on two others.

## Steps to reproduce
Create a web part with code in event handler for onDisplayModeChanged, t.ex:
MyDisplayModeWebPart.ts

  protected onDisplayModeChanged(oldDisplayMode: DisplayMode) {
   alert("Displaymode changed");
  }

-Add wep-part app to SharePoint Apps
-Insert web part on å client side page and publish.
-Change mode from view to edit mode (click Edit on page toolbar). Now it's expected to see the alert message, but don't.
-Now click Publish to publish the page 
-> trigger display mode change - also expected to show the alert, but don't.

Also - when opening the page for debugging and place a breakpoint in the event handler, the breakpoint isn't hit:
-Insert a web part with an onDisplayModeChanged event to a sitepage
-In browser debugger add breakpoint on the event
-Change page to and from edit mode. No tracepoint pauses exec.

## Expected behavior

Code in onDisplayModeChanged is run - alert is shown when entering and leaving edit mode.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Edge
- **Tooling**: SPFx v1.10.0
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by BharatKhunti** [comment]
We are facing same issue for one of custom web part that we are using to save data onDisplayModeChanged method.
Is any update on issue Or is there any other solution to save data when page go from Edit mode to Display?

**Comment by kalpeshvaghela90** [comment]
I am also facing same issue.

**Comment by Barba76** [comment]
Same here. It works on workbench but not on a real page

**Comment by jklevel** [comment]
This is still a problem - any update?

**Comment by SharePickle** [comment]
Bump. Any plans to fix it in near future?

**Comment by jklevel** [comment]
@andrewconnell  Will there be a fix on this issue?

**Comment by andrewconnell** [comment]
@jklevel I can't speak on behalf of Microsoft (*I don't work for Microsoft... I just was helping classify new issues for a period of time*)

**Comment by RurhiRaj** [comment]
I am also facing this issue. Any update?

**Comment by patmill** [comment]
Looking into this - sorry for the (long) delay.  Will post back w/ updated info.

**Comment by jklevel** [comment]
@patmill Any updates?

**Comment by patmill** [comment]
Sorry for the delay.  Switching to edit mode no longer does an in-line switch of an existing webpart instance, instead the read-mode instance is torn down, and a new edit-mode instance is created.  You will want to hook into the on-dispose of the webpart.
