### ISSUE TITLE
Documentation step incorrect - In the Storage field, select Use existing, and select the storage account that you created earlier.

### ISSUE THREAD

**Issue by cjanow3** [SharePoint/sp-dev-docs#6553]
With updated interface, there is no Storage field to choose from.  I ran into issues later on editing the requirements.psd1 file because my app was out of memory.

![image](https://user-images.githubusercontent.com/21167198/101935934-7300b180-3ba5-11eb-9961-8569606d46b1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi @cjanow3,

In my Azure tenant, it still has 'Storage' option: 
![image](https://user-images.githubusercontent.com/57654821/103744819-6141eb00-5039-11eb-960c-85746424883f.png)

Baker Kong
Microsoft SharePoint Community Support

**Comment by cjanow3** [comment]
After upgrading from Free plan to Consumption, hosting option is available.
