### ISSUE TITLE
Configure the list form

### ISSUE THREAD

**Issue by mbsully7** [SharePoint/sp-dev-docs#6555]
The "Configure the list form" (below) should be available on this page.
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-header

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#feedback)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Not clear what you're saying in your comment... are you saying another doc should be referenced on this page?

**Comment by mbsully7** [comment]
@andrewconnell 

The document detailing how to "show or hide columns in list form" 
(https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide) 
is listed under "forms configuration" in the lefthand navigation. 

The document detailing how to "configure the list form"
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-header
should also be listed in that section. I had a hard time finding this information.

<img width="452" alt="Screen Shot 2020-12-21 at 8 13 41 AM" src="https://user-images.githubusercontent.com/75865727/102797849-19e30b80-4365-11eb-9df7-f863843408fa.png">
