### ISSUE TITLE
Connect Angular Elements component (wrapped by a SPFx Web Part) to AAD-secured API's

### ISSUE THREAD

**Issue by tyh77** [SharePoint/sp-dev-docs#6556]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I saw this thread while I was doing some research on using `@microsoft/sp-http` to connect our SPFx Web Part to AAD-secured API's: https://github.com/SharePoint/sp-dev-docs/issues/3889

 The original poster had almost the same use-case as I did, with a few differences:
- We went the Angular Elements route, but we develop the two parts separately. We have a SPFx Web Part that bootstraps the readied NgElement. It does have Angular dependencies (core, elements, etc.) , but only for bootstrapping the module. The actual bundling of the Angular Library is handled elsewhere in a separate project.
- The Web Part is in charge of certain properties and configurations, and for fetching Dynamic Data properties and providing those to the component.

We're also looking to make HTTP requests to AAD-secured API's. I also thought that we'd just be able to use `@microsoft/sp-http`, but I hadn't anticipated that sp-http relies on some core SPFx parts. My thought process was that `AadHttpClient` is a really easy way of doing so, where we can provide to the Angular Component `AadHttpClientFactory` (from the parent Web Part) as an input, using the Web Part's initialized context.

We definitely need to make requests to AAD-secured API's, do you have any recommendations for doing this? It seems like there are better paths to take aside from `AadHttpClient`?

@andrewconnell I think you provided some inputs in the thread referenced (https://github.com/SharePoint/sp-dev-docs/issues/3889), do you have any suggestions? 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Tooling**: SPFx v1.11.0

**Comment by andrewconnell** [comment]
IMHO, trying to do this with Angular Elements is adding a LOT of complexity. If you insist though...

I wouldn't try to use the **AadHttpClient**. Rather I'd use MSAL.js to make the call to the token endpoint that the **AadHttpClient** makes to obtain the access token. In the end, it's client-side dev so the server has no clue you're making the call from the SPFx API (**AadHttpClient**) or another way (MSAL.js).

To determine what settings you should have in your call to obtain the token, create a pure SPFx web part that calls the secured endpoint and use that as your reference.

**Comment by tyh77** [comment]
Thanks for the suggestion @andrewconnell on **MSAL.js.**

Ideally, we want the Angular component to be isolated and reusable, hence we're trying to keep most of the logic within the Angular library itself. 

Upon some digging, I think there's an Angular variant to MSAL.js in @azure/msal-angular, so we'll look into that as well.

Our other option is not having an HTTP api logic in the ng component and using the SPFx web part to inject that data instead.
