### ISSUE TITLE
There a vital step missing in the documentation

### ISSUE THREAD

**Issue by Joker2000** [SharePoint/sp-dev-docs#6557]
> If you've created an application, the recommendation is to register and use AppID and AppTitle

There is mention of registering the application with SharePoint, but at no point is there any indication how we should do this. Could you please add a reference to another page or perhaps some steps we can follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efe14fc-9d5d-a5fc-07ba-e013e89589e2
* Version Independent ID: 5455b54e-997d-75e3-018a-0bf3f3b2180b
* Content: [Avoid getting throttled or blocked in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)
* Content Source: [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
It's referring to registering an Azure AD application that's granted permissions to SharePoint... that's present in lots of places in the docs, but not sure which would be the best link to use. Adding to docs backlog...

**Comment by Jerry0527** [comment]
Please checkout the document here to register Azure AD Application and use App-Only permission:
[Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
