### ISSUE TITLE
msGraphClientFactory.getClient() no response on first page load (IE11, Edge, Chrome [infrequently])

### ISSUE THREAD

**Issue by BrennanAldridge** [SharePoint/sp-dev-docs#6558]
## Category

- [x] Issue

## Question
I created an Application Customizer, which is deployed to the tenant App Catalog and added to a Communications SharePoint Site Collection. In the componentDidMount() method, I use Graph API to get data. I am using the **@microsoft/sp-http** module to get data from a list using Graph API.

When I load the SharePoint site **the first time** the request to create the MSGraphClient does not resolve (nor return an error). If I reload (Ctrl-F5), or navigate to a new page in the site, or if I close and re-open the browser and load the page, the MSGraphClient is resolved and data is retrieved. This issue occurs in IE11 and Edge (non-chromium); this issue does not occur in Chrome.

Because the solution works on reload, I assume the code is fine and the **@microsoft/sp-http** module doesn't have any inherent issues related to browser compatibility... I'm thinking there is some dependency that is not loading quickly enough in IE and older Edge browsers...

Any suggestions or help would be greatly appreciated!

Here is my code:

    private static _context: ApplicationCustomizerContext;

    public static Init(context: ApplicationCustomizerContext) {
        this._context = context;
    }
    private static async GraphGet(path: string, expand?: string, filter?: string, top?: number, orderBy?: string): Promise<any> {
        const client: MSGraphClient = await this._context.msGraphClientFactory.getClient();
        let request = client.api(path);
        if (expand) { request.expand(expand); }
        if (filter) { request.filter(filter); }
        if (top) { request.top(top); }
        if (orderBy) { request.orderby(orderBy); }

        const response = await request.get();
        return response;
    }

I've also tried the .then() syntax used in documentation; it produces the same result... e.g. the following does not log to the console: .then((client: MSGraphClient): void => { console.log('I got a client!"); }
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph

## Environment details (if applicable)
- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online (Targeted Release)
- **Framework**: React
- **Browser(s)**:  IE v11 | Edge (issues); works in Chrome
- **Tooling**: VS Code | SPFx v1.9.1 | VS Code
- **Additional details**: see above.

**Comment by andrewconnell** [comment]
1. your code doesn't look right... but might be incomplete. Can you please provide the code you're using? For instance, if you're getting your own reference to the context in an init, where is the init being called, and is it happening in the correct init location (iow: after the SPFx runtime has init'd).
2. If this works in other browsers but not IE/LegEdge, have you verified your site is in the same security zone for the endpoint to call AAD (to obtain a token) & Graph. This concept doesn't exist in other browsers so... it's an indicator that might be a culprit.
3. Be aware the IE11 is on it's way out WRT being supported din M365... MSTeams already dropped support (effective NOV-30-2020)... other apps as well. FWIW, all of M365 is dropping support for IE11 in August 2021.

**Comment by BrennanAldridge** [comment]
@andrewconnell  Thank you for the speedy reply! I am aware that IE is thankfully leaving :), but my client still has users with it, and it is the only reliable way for me to recreate the issue. Also not that if I open F12 dev tools in IE before I load the page, it works... Also if I gulp serve to IE and load is that way it also works...

I did try adding login.microsoftonline.com and {client}.sharepoint.com as trusted sites in IE... It appeared to solve the problem at first, but then I returned to test it again a couple days later after first boot, and the issue was still there.

My **applicationcustomizer.ts** calls the Init method. I do this so I don't have to pass context all over the place. I tried refactoring code to use context at the component and sub-component levels, but still had the same issue.

  private _topPlaceholder: PlaceholderContent | undefined;
  private refreshChild: any = React.createRef();

  @override
  public onInit(): Promise<void> {
    Data.Init(this.context);
    this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);
    this.context.application.navigatedEvent.add(this, this.navigatedEvent);

    this._renderPlaceHolders();
    return Promise.resolve();
  }

  private _renderPlaceHolders(): void {
    if (!this._topPlaceholder) {
      this._topPlaceholder = this.context.placeholderProvider.tryCreateContent(PlaceholderName.Top, { onDispose: this._onDispose });

      if (!this._topPlaceholder) {
        console.error('The top placeholder was not found.');
        return;
      }

      const elem: React.ReactElement<IBairdHeaderProps> = React.createElement(BairdWebHeader, {
        spContext: this.context,
        ref: this.refreshChild
      });

      ReactDOM.render(elem, this._topPlaceholder.domElement);
    }
  }

The **component.tsx** has the following:

export default class Header extends React.Component<IHeaderProps, HeaderState> {
  constructor(props: IHeaderProps, state: HeaderState) {
    super(props);

    this.state = {
      hubSiteId: this.props.spContext.pageContext.legacyPageContext.hubSiteId,
      hubSiteURL: hubSiteURL,
      currentSiteUrl: this.props.spContext.pageContext.web.absoluteUrl,
      currentUserEmail: this.props.spContext.pageContext.user.email.toLowerCase(),
      wifiPassword: undefined,
      alerts: {} as Alert[],
      modal: { isVisible: false, title: '' },
      myQuickLinks: {} as QuickLinks,
      showPagePromotion: false
    };
  }

  public async componentDidMount() {
    const alerts: Alert[] = await Data.getAlerts(this.state.hubSiteId);
    const wifiPassword: string = await Data.getWifiPassword(this.state.hubSiteId);
    const hubSiteUrl: string = await Data.getHubSiteUrl(this.state.hubSiteId);

    const showPagePromotion = this.showPagePromotion();

    this.setState(() => ({
      hubSiteURL: hubSiteUrl,
      alerts: alerts,
      wifiPassword: wifiPassword,
      showPagePromotion: showPagePromotion
    }));
  }

**Comment by BrennanAldridge** [comment]
@andrewconnell Regarding SPFX runtime loading... what is the proper way to check for that? In the olden days there were methods like SP.SOD.executeFunc("sp.js") and others to make sure JS dependencies were loaded before you started making calls. Is there an equivalent in SPFX? Do I need to include @microsoft/sp-http as dependency in package.json, or is importing it at the component level sufficient?

**Comment by andrewconnell** [comment]
@BrennanAldridge said:

> Regarding SPFX runtime loading... what is the proper way to check for that?

You're already doing it correctly... you commonly see people make the mistake to do init stuff in the constructor, but as long as you do it the way you're doing it, you're good. SPFx calls the component's `onInit()` method once SPFx is initialized. As long as you override that and resolve the returned promise, that's the correct process to follow.

```ts
  public onInit(): Promise<void> {
    Data.Init(this.context);
  // ...
    return Promise.resolve();
  }
```

I'll flag it as something to be reviewed... I'm not on Windows so no access to IE (_thankfully_) so can't repro. Chalking it up as another reason to get rid of IE11 :)

**Comment by BrennanAldridge** [comment]
@andrewconnell Thank you. sir!

FWIW, I also tried adding a dummy call inside onInit() like: try { this.context.msGraphClientFactory.getClient(); } catch { } ... hoping that that one would fail and the subsequent calls would succeed, but that didn't work (and was hacky anyway). I'm open to any other band-aids I can put on this to get it working ASAP.

Thank you in advance.

**Comment by BrennanAldridge** [comment]
@andrewconnell I updated the title to include Chrome. I saw the same issue in Chrome for the first time this morning (I've been trying to reproduce in all browsers for 1-2 months).
