### ISSUE TITLE
SPFX Teams Personal App  Pop out app feature  blank screen

### ISSUE THREAD

**Issue by Rtoribiog** [SharePoint/sp-dev-docs#6563]
## Category

- [x] Bug

## Describe the bug

>  We created a spfx teams static app ,  using the following url. "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={{SPFX_COMPONENT_ID}}%26forceLocale={locale}"  it´s working ok  in teams desktop app ,  when the user click in pop out app ,  new window is opened but blank screen appears.  It works if it´s a sharepoint page  but not  spfx webpart.

https://windowsreport.com/teams-pop-out-apps/
![1](https://user-images.githubusercontent.com/687795/102198842-2bd73100-3ec3-11eb-81a6-8b08d6c0ab08.png)
![2](https://user-images.githubusercontent.com/687795/102198845-2c6fc780-3ec3-11eb-8281-50c99bbd2f1a.png)

## Steps to reproduce

> - Provide steps to reproduce the behavior:

1. Go to Teams Desktop
1. Right click in  Teams personal app in the left bar
1. Select Pop out app
1. Teams app is not loaded , blank screen

## Expected behavior

> Teams app needs to be loaded the same than in desktop app

## Environment details (*development & target environment*)

> - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- Developer Environment : Windows 10
- Target Environment: SharePoint Online
- Framework : Node.js v10.13
- Browser(s): Teams Desktop
-  Tooling: SPFx v1.11

### Additional context

>  - Provide any other context about the problem.

*Thanks for your contribution! Sharing is caring.*

## Submission guidelines

Dear @VesaJuvonen

**Comment by mrzyko** [comment]
Yup, I can confirm this bug. 
It also appears with our personal app, using spfx.

**Comment by andrewconnell** [comment]
Have you tried using the latest version of SPFx, v1.11? The version you're using is ~12mo old... that's the first thing MSFT will ask you to do is to validate this against the latest version.

**Comment by zakwht** [comment]
I can confirm this appears with our personal app using SPFx 1.11

**Comment by Rtoribiog** [comment]
updated spfx  to version 1.1.1 and it´s still happening the same.  Thanks

**Comment by andrewconnell** [comment]
In your OP you say you're using Node.js v12... SPFx is only supported with Node.js v10 at this time. Although I suspect it's a typo as you should get all sorts of build errors if you try to use Node.js v12.

**Comment by Rtoribiog** [comment]
> In your OP you say you're using Node.js v12... SPFx is only supported with Node.js v10 at this time. Although I suspect it's a typo as you should get all sorts of build errors if you try to use Node.js v12.

corrected it´s  v10.13

**Comment by RoelVB** [comment]
I thought some technical information could be useful.

The embedded and pop-out window both load an iframe with a URL like:
`https://contoso.sharepoint.com/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=00000000-0000-0000-0000-000000000000`

The only difference I noticed is that the content of the embedded iframe contains a `<div class="SPPageChrome isFluent">` (which contains the webpart) in the body, but the pop-out window is missing this div.

**Comment by praveenpudi329** [comment]
Hi All,

Any updates. we are facing the same issue, no difference in fiddler trace for embedded & pop out

**Comment by AhmadAlamili** [comment]
I have the same issue, any updates?

**Comment by giuleon** [comment]
Hi everybody,
we are facing the same issue, is there any progress here @andrewconnell @VesaJuvonen @lucabandMSFT, the product team is already informed about that?

**Comment by giuleon** [comment]
Hi everybody, I officially raised a ticket to Microsoft I'll keep you all in the loop as I have news

**Comment by VesaJuvonen** [comment]
Hi all,
this issue has been fixed and is gradually rolling through eh Teams release circles. Hunting down more detailed ETA internally and hoping to update the thread within upcoming days.

**Comment by giuleon** [comment]
Thanks @VesaJuvonen for your update

**Comment by VesaJuvonen** [comment]
Here's visual proof from normal E3 that the issue is fixed. We will keep this issue though still open as apparently fix has not been confirmed to be 100% deployed worldwide yet.

![image](https://user-images.githubusercontent.com/7446437/119649391-40810300-be2b-11eb-92b3-59412a47b4e0.png)

**Comment by SalmanPadder25** [comment]
Thanks much @VesaJuvonen for the confirmation.
Issue is resolved for my client after the update was pushed.
