### ISSUE TITLE
Is there a way to revert a site after a site design has been applied?

### ISSUE THREAD

**Issue by geraintjames** [SharePoint/sp-dev-docs#6564]
## Category

- [x] Question

## Question

Once a Site design has been applied to a site, is there any way to revert a team site back to the state it was originally in?
It should ideally be possible to reapply the 'None' option to strip out Custom actions and branding artifacts etc without having to use PowerShell for this or better still to allow you to revert to a particular version of the site and rollback a number of site designs in one go.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [All]
- **Browser(s)**: [Chrome v79 | Chromium Edge v79]
- **Tooling**: [VS Code]
- **Additional details**: [It's easy for site owners to apply the wrong site design, but it can be almost impossible for them to get the site back to the way it was without IT Support]

**Comment by bcameron1231** [comment]
Unfortunately, no this is not possible. You cannot revert a site design that has been applied.
