### ISSUE TITLE
Custom App Authentication Questions

### ISSUE THREAD

**Issue by proce** [SharePoint/sp-dev-docs#6566]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

We provide a solution as a Provider-Hosted add-in.

Our add-in is registered using “appregnew.aspx”.
[See Microsoft documentation on the method we use here:](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online)

Our solution requires the “DisableCustomAppAuthentication” tenant setting to be FALSE.
We are aware that this setting is set to TRUE by default on new O365 tenants, however it can be changed to FALSE to enable Provider-Hosted add-ins to authenticate successfully.

We are concerned that if this option is removed in the future, our solution will no longer work without some fundamental code changes.

We are aware an alternative solution is to register our add-in in Azure Active Directory, however this provides app permissions at the tenant-level only so is not an acceptable solution.
We require a solution that allows granular app permission control at the site collection level, rather than the tenant.
[See relevant discussion on this point:](https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/) 

1. Is there a timescale for when Microsoft will disable Provider-Hosted add-ins and remove the ability to re-enable them by changing “DisableCustomAppAuthentication”?

2. Are there any plans to enhance the app-permissions in Azure Active Directory registrations to support site collection level permissions?

3. Are there any other alternatives you can suggest? 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: NET Framework v4.7
- **Browser(s)**: Chrome, Chromium Edge
- **Tooling**: Visual Studio 2019

**Comment by andrewconnell** [comment]
@proce said:

> Is there a timescale for when Microsoft will disable Provider-Hosted add-ins and remove the ability to re-enable them by changing “DisableCustomAppAuthentication”?

No... I haven't seen any public statements from Microsoft if/when they would do this.

@proce said:

> Are there any plans to enhance the app-permissions in Azure Active Directory registrations to support site collection level permissions?

No, Microsoft hasn't said anything about this. It would make for a good feature request on UserVoice.

@proce said:

> Are there any other alternatives you can suggest?

No... as I said above, Microsoft has stated no plans for allowing app permissions to be scoped at the site collection level.
