### ISSUE TITLE
Article Not Rendering Correctly

### ISSUE THREAD

**Issue by veebz** [SharePoint/sp-dev-docs#657]
#### Category
- [ ] Question
- [ ] Typo
- [ X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The following article renders correctly:
https://dev.office.com/sharepoint/docs/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins

#### Observed Behavior
The article renders incorrectly:
![Rendering Issue](https://user-images.githubusercontent.com/1145703/27349003-8501d4dc-55bb-11e7-858a-5d6a850daf1a.jpg)

#### Steps to Reproduce
Visit https://dev.office.com/sharepoint/docs/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins

**Comment by VesaJuvonen** [comment]
All fixed now.
