### ISSUE TITLE
Prevent web font loading from sharepoint domain.

### ISSUE THREAD

**Issue by scream87** [SharePoint/sp-dev-docs#6576]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Is there a way to disable segoeui and FabricMDL2Icons web fonts loading from external resource (which is https://static2.sharepointonline.com)?

In our sharepoint site, blank page does not load any fonts, but with added SPFX web part it start to load web fonts from sharepoint domain.
The problem is that client has private network which is blocking external resources.
We had overwritten these fonts with local ones to solve issue with displaying correct fonts/icons.
But since web part is still trying to fetch external ones - this is causing problems to page loading speed.

**SPFX WebPart information:**

It is raw SPFX web part template, which is created with next steps:

* yo @microsoft/sharepoint
* What is your solution name?: web-font-tester
* Which baseline packages do you want to target for your component(s)?: SharePoint 2019 onwards, including SharePoint Online
* Where do you want to place the files?: Use the current folder
* Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites?: N
* Which type of client-side component to create?: WebPart
* What is your Web part name?: WebFontTester
* What is your Web part description?: WebFontTester description
* Which framework would you like to use?: React

And is built with next command:
```
gulp clean && gulp bundle --ship && gulp package-solution --ship
```
## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10 | yo v3.1.1 | @microsoft/generator-sharepoint@1.11.0 ]
- **Target Environment**: [SharePoint Server 2019]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v87]
- **Tooling**: [WebStorm]
- **Additional details**: Web part package json dependencies
```json
  "dependencies": {
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0"
  },
  "devDependencies": {
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  }
```

**Comment by andrewconnell** [comment]
I don't believe so... @StfBauer, are you aware of a way to block the loading of external fonts?
