### ISSUE TITLE
Copy Master Page from Library in Source Site to Target site Master Page gallery using Copy-PnPFile command

### ISSUE THREAD

**Issue by satyadevidubasi** [SharePoint/sp-dev-docs#6577]
## Category

- [ ] Question

## Question

Copying Master Page from Library in Source Site to Target site Master Page gallery using Copy-PnPFile command. Master page is copied to the master page gallery in Tartget site collection, however when i tried to set master page using Set-PnPMasterPage in the site i am getting file not found error

Copy-PnPFile -Connection $MasterPageSourceConnection -SourceUrl "SiteAssets/Seattle_2020.master" -TargetUrl "$($Uri)/_catalogs/masterpage" -OverwriteIfAlreadyExists -Force

Set-PnPMasterPage -Connection $SiteConnection -MasterPageServerRelativeUrl "$($Uri)/_catalogs/masterpage/Seattle_2020.master" -CustomMasterPageServerRelativeUrl "$($Uri)/_catalogs/masterpage/Seattle_2020.master"

## Environment details (*development & target environment*)

- Windows 10
- SharePoint Online
-Powershell

**Comment by andrewconnell** [comment]
This is related to the PNP PowerShell project... please post your issue to that repo: https://github.com/pnp/powershell
