### ISSUE TITLE
Correction for CLI Command to Verify the origin was added

### ISSUE THREAD

**Issue by kraysco** [SharePoint/sp-dev-docs#6578]
The CLI command provided to verify the origin is listed as: 

m365 spo cdn get --type Public

it looks to me that this is incorrect. The command  should be:

m365 spo cdn origin list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195a21bf-f052-f2c6-d749-3fba526c5c56
* Version Independent ID: 1b6defe0-3296-eb24-6f2c-4b4be88e21da
* Content: [Enable the Microsoft 365 CDN](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enable-microsoft-365-content-delivery-network?tabs=o365cli#options-for-managing-the-microsoft-365-cdn)
* Content Source: [docs/spfx/enable-Microsoft-365-content-delivery-network.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/enable-Microsoft-365-content-delivery-network.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Care to submit a PR with the fix?

**Comment by VesaJuvonen** [comment]
Seems to have been already fixed, so closing this one.
