### ISSUE TITLE
Property panel not clearing input fields

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#658]
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
when we set a edit panel property to "" it should clear out the value in the input field.

#### Observed Behavior
the input field retains the old value

#### Steps to Reproduce
	I have created an issue on GitHub ( ) where we are finding issues when we try to assign an empty string to a web part property.  For example – see image below… we change the dropdown (Language) and the next 4 boxes should clear – if there were values in those boxes – it correctly displays the values.
see attached
[issue.docx](https://github.com/SharePoint/sp-dev-docs/files/1089338/issue.docx)

**Comment by patmill** [comment]
@srideshpande to take a look.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
