### ISSUE TITLE
Azure Authentication Blade Has Changed

### ISSUE THREAD

**Issue by RBStarkey** [SharePoint/sp-dev-docs#6580]
I Think the Azure Authentication blade has changed as I can't identify this step...

    •	Change Default client type - Treat application as public client from No to Yes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
Hi @RBStarkey,

This setting is in the below panel:

![image](https://user-images.githubusercontent.com/57654821/103184598-d0aa3300-48f3-11eb-89ce-2494554cd533.png)

It's asking a public app as the demo is a console app.

Baker Kong
Microsoft SharePoint Community Support

**Comment by RBStarkey** [comment]
Baker

Thanks for pointing me in the right direction but I was hoping someone from Microsoft would say “We will correct the blog item”.

The second problem, once you have set the setting, is that you get an error from the suggested code.

I’ll try again to get help from the Azure Team.

Thanks for trying.

Raymond Starkey.
