### ISSUE TITLE
column formating with percentage

### ISSUE THREAD

**Issue by jlagrut01** [SharePoint/sp-dev-docs#6581]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question
I have a column with the type "number" where in clicked "show as percentage".
When I want to add "format this column" with conditional formatting, the numbers are not displayed as percentage anymore.

How can I put a format with conditional formatting and keep the display in percentage ?

Thanks a lot for your support

## Environment details (*development & target environment*)

- Windows 10 
- SharePoint Online
- Chrome Version 87.0.4280.88

**Comment by Amos-MSFT** [comment]
Hi @jlagrut01,
Could you share the JSON you are using?
Amos Wu
Microsoft SharePoint Community Support

**Comment by shagra-ms** [comment]
You can maintain the display format of a number column by using [displayValue property](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#displayvalue). 

The conditional formatting template does not yet support displayValue for number and currency fields. We will take fix to support that. Meanwhile, please use displayValue property to enable the same using custom JSON.
