### ISSUE TITLE
Add Information About Visual Studio Community Edition

### ISSUE THREAD

**Issue by tictag** [SharePoint/sp-dev-docs#6587]
I am not sure whether Visual Studio Community Edition includes node.js but there does appear to be an option within the Visual Studio Community Installer application. I am installing it now. If I assume that node.js is, or rather, can be installed via the Visual Studio Community Installer and if I assume that it installs v10, then, as a developer, I might already have node.js installed.

It would be useful to add a comment here (or perhaps in a FAQ) that if you already have Visual Studio Community Edition installed, there is no need to separately install node.js.

But at the very least a comment here discussing Visual Studio Community Edition would be useful clarity. I had the question in my mind when reading this doc, I guess other would have too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Node.js is not included in Visual Studio Community version, if didn't install Node.js, it will have this error:

![Snipaste_2021-01-04_11-12-59](https://user-images.githubusercontent.com/28797671/103497896-e84a6400-4e7d-11eb-9e73-5e36eca5687f.png)

So currently, please install Node.js separately .

**Comment by tictag** [comment]
OK, please feel free to close the ticket.

David.
