### ISSUE TITLE
Unable to trust the self-signed developer certificate before creating a project.

### ISSUE THREAD

**Issue by DGDC** [SharePoint/sp-dev-docs#6588]
## Category

- [x] Bug

## Describe the bug

As of 1/4/2021 the [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) article states, with emphasis added:

> ### Trusting the self-signed developer certificate
> The SharePoint Framework's local webserver, used when testing your custom solutions from your development environment, uses HTTPS by default. This is implemented using a development self-signed SSL certificate. Self-signed SSL certificates are not trusted by your developer environment. You must first configure your development environment to trust the certificate.
> 
> A utility task is included in every SharePoint Framework project in the form of a gulp task. **You can elect to do this now**, or wait until you create your first project as covered in the Build your first SharePoint client-side web part (Hello World part 1) tutorial.

When executing `gulp trust-dev-cert` the following error is encountered.
```
[14:55:58] Local gulp not found in ~
[14:55:58] Try running: npm install gulp
```

## Steps to reproduce

After installing Node.js, Visual Studio Code, and the `npm install gulp yo @microsoft/generator-sharepoint --global` toolchain per [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment), execute `gulp trust-dev-cert` from Visual Studio terminal prompt (PS).

## Expected behavior

The self signed certificate is trusted globally.

## Environment details (*development & target environment*)

Windows 10
Visual Studio Code 1.52.1
Node 10.23.1
Gulp CLI 2.3.0
@microsoft/generator-sharepoint@1.11.0

### Additional context

All copy-and-pasted guidance (blogs, articles, training, etc.) on this are for trusting the self-signed developer certificate when working with a specific project.

The [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) article states that the certificate can be trusted before creating any projects- i.e. globally.

Related Bug: [Local gulp not found #3575](https://github.com/SharePoint/sp-dev-docs/issues/3575)

Either provide working instructions on how to trust the self-signed development certificate globally or update documentation to remove statements that the self-signed development certificate can be trusted globally.

**Comment by Amos-MSFT** [comment]
Hi,
According to the description of the document, you need to create an SPFX project first, and then execute this command.
Amos Wu
Microsoft SharePoint Community Support

**Comment by bcameron1231** [comment]
Based on the error, it can't find your instance of gulp. Did you install gulp?

`npm install gulp --global`

**Comment by DGDC** [comment]
The document states that "You can elect to do this now, or wait until you create your first project".

The use of "or" is that of a conjunction used to connect words, phrases, or clauses representing alternatives. E.g. You can dine in or you can carry out. In this case per the documentation, the command to trust the developer certificate can be done before creating a project or after creating a project.

The command fails before creating a project. So please fix the command OR correct the documentation.
