### ISSUE TITLE
ListView Command Set extending existing menu

### ISSUE THREAD

**Issue by rychlym** [SharePoint/sp-dev-docs#659]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Hello, just kind of question or a wish if it is not yet implemented? Is it possible to add a command which will be part of  existing drop-down menus - e.g. extra items in the +New drop-down?
when it is  possible, please can you provide a short tutorial  (I guess mainly how the manifest.json would look like)?

#### Observed Behavior
(As written I am not sure it is working)

**Comment by pgonzal** [comment]
Currently this is not supported.  Eventually we plan to add more command set extension types, both for the List View as well as other SharePoint UI surfaces.

**Comment by ldemaris** [comment]
Hi,

When you say "+New" drop down, are you talking about the New menu:
 - Inside list view pages, for creating new list items or files in document libraries
 - On the team site homepage, for creating new pages, lists, apps, etc. inside the team site
 - On the site contents page
 - All of the above?

**Comment by rychlym** [comment]
to Idemaris:   Sorry when not understandable - I meant the only New menu inside list view pages (for the "modern" user experience)

**Comment by ldemaris** [comment]
Thanks for clarifying.  We don't support that yet, but it makes sense as a requirement.  We'll put that in our backlog.

**Comment by rychlym** [comment]
to ldemaris:
Thanks, it is great to hear it!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
