### ISSUE TITLE
Dynamically filter Document Library based on List/Library Tile selection

### ISSUE THREAD

**Issue by Bhushan12986** [SharePoint/sp-dev-docs#6590]
## Category

- [x] Question
- [ ] Typo
- [x] Additional article idea

## Question

For an OOTB modern site page, I know you can dynamically filter the contents of a Document Library part, based on the filter value of a user's selection in a separate List part. You can also customize the List part with JSON to appear as fancy tiles. I'd like the user to click the tile containing their filter value, then see the document library dynamically filter.

How do you use the JSON to specify the List tile's selection action? Making clicking the tile similar to selecting the radial button in a list view?

At the moment, my list tiles don't do anything when clicked. Using the tile view essentially breaks the connected filtering of the Document Library.

How to filter connected list/document library web parts using list view JSON formatting?

**Comment by shagra-ms** [comment]
@Bhushan12986 Can you share the JSON used int Tiles/Gallery View? 

The selection post formatting works exactly like it works before formatting. You do have the flexibility to disable selection if you want. 

In the scenario above, if you haven't disabled selection, you would see the radial button on the right top of the card in your Gallery View - 
![image](https://user-images.githubusercontent.com/37994247/112158103-dc18ac00-8c0d-11eb-9287-f1619305bbda.png)
