### ISSUE TITLE
Show / Hide Columns based on a field which is not available in the form

### ISSUE THREAD

**Issue by arjunumenon** [SharePoint/sp-dev-docs#6591]
I have a typical request not sure whether it is possible. 

I have a field (**Status** field) which is used for business process and this field is hidden from the SharePoint New / Edit Form. When I give a conditional show / hide for another field let say **Comments** dependent on the above mentioned **Status** field, it is not working. But when I make the **Status** field as NOT HIDDEN  in the New / Edit Form, conditional show / hide approach works.

I am assuming, Conditional Show / Hide will work only for dependent fields which are being shown in the New / Edit Form. Is ,my understanding correct here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Amos-MSFT** [comment]
Yes, my test result is same with yours. It seems that the value of the hidden column is set to empty.
Test result:
![test73](https://user-images.githubusercontent.com/56672877/103871531-21960480-5108-11eb-88a5-ef6d000a9838.gif)
Amos Wu
Microsoft SharePoint Community Support

**Comment by arjunumenon** [comment]
Thanks @Amos-MSFT for confirming the result. Any idea whether this is an intended behavior? I couldn't find anything specific in the documentation. If it is intended, I guess we may have to add it in the documentation.
