### ISSUE TITLE
Webpart only working in edit screen

### ISSUE THREAD

**Issue by RA1449** [SharePoint/sp-dev-docs#6597]
I have followed the instructions from the document and the data table works in the edit screen.  Once previewed, only the table headers appear.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56fb9ec-59c2-413f-eaa2-e84abfb30211
* Version Independent ID: ca610020-3018-fd78-1da5-7f00fed5b04f
* Content: [Migrate jQuery and DataTables solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by kongmengfei** [comment]
@RA1449,

I viewed the doc and have a test with below demo, luckily it works fine here. You may take a reference:

- https://github.com/kongmengfei/SharedSPFx/blob/main/datatables-itrequests/src/webparts/itRequests/ItRequestsWebPart.ts

Test Result:

![image](https://user-images.githubusercontent.com/57654821/104154683-7abfaa00-5420-11eb-8b4e-8682001840ba.png)
Baker Kong
Microsoft SharePoint Community Support
