### ISSUE TITLE
This does not work for item modified, only new items...

### ISSUE THREAD

**Issue by correabruno** [SharePoint/sp-dev-docs#6598]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992f8829-85b4-d17e-c93e-1302d9f7a208
* Version Independent ID: c1e12c09-b58f-c526-907b-b683670a9969
* Content: [Send an email when a new item is created or modified in a SharePoint list](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your-first-flow)
* Content Source: [docs/business-apps/power-automate/get-started/create-your-first-flow.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/get-started/create-your-first-flow.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
For item modified, change the trigger condition to  "When an existing item is modified":

![Snipaste_2021-01-11_14-57-56](https://user-images.githubusercontent.com/28797671/104153485-662de280-541d-11eb-806c-266e13a182e0.png)

**Comment by correabruno** [comment]
Maybe should consider changing the article, as it will not work when the item is modified...


________________________________

**Comment by Jerry0527** [comment]
Maybe need to update the article title, but for me, if I know how to trigger the flow for new items, I will also know how to trigger for item modified..
