### ISSUE TITLE
Text is not correct and there is no information about how to hide fields

### ISSUE THREAD

**Issue by Axalon-Mattias** [SharePoint/sp-dev-docs#6599]
Refering to the following page:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration

All section (header, footer and body) descriptions end with the same text: "Close the form and open the form again to view the applied header." This is not correct. The last word should correspond to the section (header, footer, body).

I also miss information about how to hide fields that I do not want to show at the moment. I also want the option to hide the selection of content type since I only use one in most solutions I build.

Addition: The layout configuration cannot be accessed from a form in "edit all mode" as stated in the text. It can only be accessed from "view all mode".

Kind regards,
Mattias Sandberg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Appears to be a dupe with #6591
