### ISSUE TITLE
How to store client web part properties with per user personalized scope?

### ISSUE THREAD

**Issue by plakhlani** [SharePoint/sp-dev-docs#660]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I am planning to store user preferences and wanted to know if there is way to store user's personalized scope data somewhere?

**Comment by plakhlani** [comment]
updated question text, removed unused text

**Comment by waldekmastykarz** [comment]
At this moment SharePoint Framework client-side web parts don't support user-level personalization.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
