### ISSUE TITLE
SharePoint online native screen loads first, then my customized page getting loaded

### ISSUE THREAD

**Issue by sivanu137** [SharePoint/sp-dev-docs#6603]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

**##Question (How to stop loading native SharePoint screen and load my customized page first?)**

Hi, I'm developing a SharePoint online intranet portal, with custom UI. What happens is, when I load my page, the SharePoint default page gets loaded first (for fraction of seconds), then my custom UI page gets loading.

For reference, I have attached the behavior of the page in the video format.

https://user-images.githubusercontent.com/31919925/104266086-f10dec00-54b4-11eb-87d5-93ca534e921c.mp4

You can see in the top HTML tag, I am adding a class **"loading-in-progress"** when the page gets load, for this class I have added the CSS with a background image (i.e., Loading GIF). Once the page loaded completely I'm removing the class "**loading-in-progress**".

What I want to achieve is, without showing SharePoint native screen directly show my customized page or show a loading gif until the page gets loaded completely.  

Thanks in Advance!!!

**Comment by bcameron1231** [comment]
This is the intended functionality. 

I also want to mention that what you are trying to do is not supported. You are overriding out of the box HTML and styles, which is not a supported scenario in SharePoint Online. The DOM is not an API, and all of your customizations are subject to break at any moment. 

If you are looking to build full page customizations (excluding navigation), you should be using Single Part App Pages. 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?tabs=pnpposh

**Comment by sivanu137** [comment]
@bcameron1231 
Thanks for the response, If I use the Single part app pages, will it resolve my problem???
