### ISSUE TITLE
SPFx Play HTML5 Videos dynamically on a webpart not working

### ISSUE THREAD

**Issue by vivekmurli** [SharePoint/sp-dev-docs#6604]
## Category

- [ ] Question
- [x] Bug

We are developing a webpart

1. That has a textbox where we supply a Video URL
2. This would fetch the Video URL from a SharePoint list on button click and set the SRC of the Video Element.

We are developing a webpart

That has a textbox where we supply a Video URL

This would fetch the Video URL from a SharePoint list on button click and set the SRC of the Video Element.

**Code**

```
function textFieldChanged(newValue: string){ 
    
    let vidplay = document.getElementById('VidPlayer');
    let source = document.createElement('source');
    source.setAttribute('src', newValue);
    vidplay.appendChild(source);
    vidplay.load();
    vidplay.play();
    
    sp.web.currentUser.get().then((user: ISiteUserInfo) => {
    
      console.log("user", user);
      const userId: number = user.Id;
    
      sp.web.lists.getByTitle(videoList).
        items.select("ID", "User/ID", "VideoURL")
        .expand("User")
        .filter(`VideoURL eq '${decodeURIComponent(newValue)}' and User/ID eq '${userId}'`)
        .top(1)
        .get()
        .then((videos: IVideoEntry[]) => {
          console.log("Videos", videos);
    
          // Did we find a video?
          if (videos.length > 0) {
            //Update the record
            const video: IVideoEntry = videos[0];
            console.log("We found the video", video);
    
          }
        });
    });         
    }
```
    
**Video Player Element**

```
<div>
      <video
        id="VidPlayer"
        ref={videoRef}
        style={{ width: elementWidth }}
        src={txtParam}
      //controls
      ></video>< br/>

      <TextField id="txtVideoURL" onChange={(ev,newValue)=> {txtParam=newValue}}/> 

      <DefaultButton text="Submit" onClick={()=>{textFieldChanged(txtParam)}}/>

</div>

```
Read a lot of articles pertaining to the same, however unable to use .play() and .load() which is required to load the video element and then play.

We get an error "Property 'play' does not exist on type 'HTMLElement'.ts(2339)"

![image](https://user-images.githubusercontent.com/6428093/104283264-324bcf00-54a8-11eb-8da6-232cee8b2265.png)

Would appreciate if anyone could let me know how this can be handled in SPFx and if there is a way to play/toggle videos dynamically 

- **Your Developer Environment**: Windows 10 
- **Target Environment**:SharePoint Online
- **Framework**:Node.js v10.23
- **Browser(s)**: Chrome
- **Tooling**: VS Code 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by StfBauer** [comment]
Sadly I can only see partially of your code but when you request:

```typescript
let vidplay = document.getElementById('VidPlay');
...
vidplay.play();
```

Will never work because the native HTML implementation has not such a function in the HTML DOM.

Instead you need to cast the element the following way.

```typescript
let vidplay : HTMLVideoElement = document.getElementById('Vidplay');
...
vidplay.play()

```

Another more fundamental issue is that you can only host one instance of the video player on the page by using it with an ID.

HTML Element register a global variable on the Window object that then get's overwritten by the second instance of your video play.

So in your case it is most likely you will get only the last instance of getElementById and this is the only video you can play.

**Comment by vivekmurli** [comment]
@StfBauer  Thank you for the reply Stefan

I have tried typecasting in the past and get the below error

![image](https://user-images.githubusercontent.com/6428093/104293487-f7e92e80-54b5-11eb-8fe4-80a1caa7b237.png)

Is there any other way to play Videos dynamically on the webpart? or a workaround?

I've also read a few posts on stackoverflow where this has been achieved outside SharePoint on JS based projects where once the SRC is set dynamically , we have to call the load and then the play button to play the 2nd video

Any help would be appreciated

**Comment by StfBauer** [comment]
Sorry had an issue there as it seems, was just coded on top of my head.

I would do something linke this.

```typescript
  public render(): void {

    this.domElement.innerHTML = `
      <div class="${styles.video}">
        <video class='thisvideoplayer'></video>
      </div>`;

    let videoPlayer = <HTMLCollectionOf<HTMLVideoElement>>
      this.domElement.getElementsByClassName('thisvideoplayer');

    if (videoPlayer.length !== 0) {
      videoPlayer[0].load();
      videoPlayer[0].play();
    }

  }
```

Or like in your scenario with getElementById, which I would not use:

```typescript
    let videoPlayer = <HTMLVideoElement>document.getElementById('thisvideoplayer');

    videoPlayer.load();
    videoPlayer.play();
```

**Comment by kongmengfei** [comment]
@vivekmurli ,

I noticed that your project is React web part, please take a referenece of below demo:

- https://github.com/kongmengfei/SharedSPFx/blob/main/Player/src/webparts/player/components/Player.tsx

Test:

![test](https://user-images.githubusercontent.com/57654821/104415342-d323b280-55ac-11eb-8426-1f4adaa1612d.gif)
Baker Kong
Microsoft SharePoint Community Support

**Comment by vivekmurli** [comment]
@StfBauer  Appreciate the proactive help :)

Would give this a try and at the same time , would try out other approach as well through trial and error.

Also would appreciate if you could suggest would could be the best approach of playing multiple videos dynamically the way it works for YouTube?

**Comment by vivekmurli** [comment]
@kongmengfie

Thank you for the reply , would give this a try and keep and let you know :)

**Comment by vivekmurli** [comment]
@kongmengfei  I see that you have used a hardcoded URL , does it work when you change the URL on the textbox?

**Comment by vivekmurli** [comment]
@StfBauer Just a gentle reminder , is there any other approach that you're aware of to play the videos dynamically on SPFx ?

Any suggestions would be appreciated

**Comment by vivekmurli** [comment]
@StfBauer thank you for helping me out with this.. unfortunately the issue still persists... Is there a way we can collaborate on this? Any help would be appreciated

**Comment by VesaJuvonen** [comment]
This issue is closed as there has not have been any activity on it within the past 2 months. If the issue is still valid, please submit a new issue with updated details. Sorry for the Inconvenience. We are perform this cleaning operation for all inactive issues in this repository to be able to improve our support model in future.
