### ISSUE TITLE
Extensions: Application Customizer weird behaviour with header color and positioning

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#661]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
I was testing out the application customizer sample with the header and footer. I have packaged the solution and uploaded it to the app catalog. Once deployed on a site, I noticed the following behaviors:

**One modern site pages**
On modern site pages only the header is loaded. Not the footer. 
<img width="600" alt="screenshot 2017-06-21 16 30 53" src="https://user-images.githubusercontent.com/2900833/27389762-a0cf6d7a-569f-11e7-9bf2-1774bfa66f96.png">

When you check the browser console, I see the following message:
<img width="418" alt="screenshot 2017-06-21 16 31 01" src="https://user-images.githubusercontent.com/2900833/27389800-c93a762e-569f-11e7-9aa6-54f012762dbe.png">

Two questions about this: 
1. Will all pages get all the placeholders?
2. The header should have been green instead of blue. Like when I would open a document library:
<img width="600" alt="screenshot 2017-06-21 16 18 05" src="https://user-images.githubusercontent.com/2900833/27389892-0df29274-56a0-11e7-9e66-b09979caaf50.png">

**Recycle bin**
Once I added the app customizer to the site and went to the recycle bin, I see the following (this happens only 1/3 times I refresh the page):

<img width="1434" alt="screenshot 2017-06-21 16 31 26" src="https://user-images.githubusercontent.com/2900833/27389953-40a0f634-56a0-11e7-9abb-c8086aa134ad.png">

#### Steps to Reproduce
Following the getting started documentation about extensions and publish it to your environment.

**Comment by patmill** [comment]
Hello @estruyf .  I can answer some of the questions:
1 - No, all pages won't necessarily have all the placeholders.  For example in the future I could see a placeholder like "BelowLeftNav" and a page that didn't have left navigation.  In that case, the BelowLeftNav placeholder wouldn't return.  Your code should be robust.  One current gap that we are working on is how to deal with the fact that the available placeholders could change when doing an inner navigate.  Ie, Page1 has no left nav (it's a homepage say), but page 2 does (it's a detail page).
2 - Sounds like a bug where the pages application isn't getting the right theme data.  @srideshpande - can you log that one? 
3 - For the recycle bin, is the issue that occasionally the placeholder doesn't show up when you go to the recycle bin?  If that is the case, can you look at the debug console and see if there is anything there that might indicate what's going on?

**Comment by estruyf** [comment]
Thanks @patmill for the info.

1. Good to know, but as the sample now contains a header and footer, maybe it should be better to point it out or make the sample code more future-proof.
2. -
3. Maybe the screenshot is not so good to see what is happening. It is about the whitespace above the suite bar. Apparently, it is coming from the `#SPPageChrome` element.

<img width="1202" alt="screenshot 2017-06-24 09 54 05" src="https://user-images.githubusercontent.com/2900833/27507249-2d56e866-58c3-11e7-8bf5-8e4a8b2a70b1.png">

I did some more investigation and it seems that sometimes the code runs before the placeholders are available on the page. Here is the error message I get when I see this kind of behavior:

<img width="933" alt="screenshot 2017-06-24 09 56 22" src="https://user-images.githubusercontent.com/2900833/27507277-984a5144-58c3-11e7-875b-499fef31920e.png">

You can see in the screenshot that no placeholders are available. So the code gets binded / executed too early it seems.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
