### ISSUE TITLE
Command Buttons are only shown on refresh on new 365 tenants

### ISSUE THREAD

**Issue by barisbikmaz** [SharePoint/sp-dev-docs#6611]
## Category

- [x] Bug

## Describe the bug

On newer Office 365 tenants if you create a simple command set extension (I used the copy link command set example from PNP) the command button on the library menu is only shown after refresh.

This is working on older  Office 365 tenants without refresh.

![spfx-error](https://user-images.githubusercontent.com/6338132/104458833-2d704380-55ac-11eb-8511-1925547bf0d5.gif)

## Steps to reproduce
1. **Create a new Office 365 tenant** or use a **Developer tenant**
2. Create a Command Set Extension project with Yeoman SharePoint Generator
3. Comment out onListViewUpdated method so that the command button is always visible
```
// @override
// public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
//  const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
//  if (compareOneCommand) {
    // This command should be hidden unless exactly one row is selected.
//    compareOneCommand.visible = event.selectedRows.length === 1;
//  }
// }
```
4. Build project and deploy to SharePoint
5. Note: After the command button is visible after refresh to reproduce this bug again close the browser tab and open the document library again.

## Expected behavior
Command Button should be visible on document library without refresh.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**:Node.js v10
- **Browser(s)**: Chrome v79
- **Tooling**: VS Code | SPFx v1.11.0

**Comment by sumitmodi84** [comment]
I am also facing the same issue where the command button set comes after the refresh of page.

**Comment by MartinSSeifert** [comment]
@andrewconnell thank you for triaging this. Any clue how long it will take for someone to look at this - we have customers complaining! It would be great to understand better the process and what we can expect from logging issues in GitHub! Any feedback is appreciated - thx. Martin

**Comment by andrewconnell** [comment]
@MartinSSeifert said:

> Any clue how long it will take for someone to look at this

Sorry... I can't speak for Microsoft in this case. WRT this issue list, I just assist in triaging, updating the docs, and helping out answering SPFx questions when I can.

**Comment by MartinSSeifert** [comment]
@andrewconnell sure, fully appreciate your help here.
@VesaJuvonen would you know who I could ping to get some attention for this issue?

**Comment by FredrikEkstroem** [comment]
See related issues, looks like someone is looking into it, but haven't seen any estimates
#5704 
#6116

**Comment by MartinSSeifert** [comment]
@FredrikEkstroem thank you for connecting the dots. It's a bit discouraging to see how long this issue has been open (looking at the other issues)! It really begs the question of extensions to SharePoint being a valid business model for ISVs or not, as such basic issues are not even addressed. The lack of active communication is alarming. Our experience with other product teams at Microsoft has been so much better than what we are experiencing here!

Would you know of a better way of communicating product bugs to the SharePoint team?

**Comment by FredrikEkstroem** [comment]
@MartinSSeifert I think here is one of the best places, or if you have Premier Support, that might be a way to raise issues. I'm also waiting for this, so hopefully it get's resolved before my launch to prod :-)

**Comment by VesaJuvonen** [comment]
We are working on solving the issue as soon as possible. In general we do encourage customers and partners, who have premier support, to open ticket using those channels for faster resolution and to speed up the process. 

We are now actively looking into this. Sorry for the delay.

**Comment by FredrikEkstroem** [comment]
@VesaJuvonen  I just opened a premier support ticket an hour ago so will push from that side too. Any reference apart from these github issues I should mention?

**Comment by VesaJuvonen** [comment]
@FredrikEkstroem - GitHub issue is good for pushing things forward. I'll do my best from my side, but great to have this falling also on the official premier support process as that always helps on speeding up the resolution.

**Comment by MartinSSeifert** [comment]
@VesaJuvonen thank you for stepping in and clarifying the situation. Super cool to learn that a fix is already on its way 👍. I will report back to let you know if the fix is working for our customers. Cheers, Martin

**Comment by VesaJuvonen** [comment]
Our internal systems are showing that this fix is now 100% deployed worldwide. Would love to get a confirmation from @barisbikmaz, @FredrikEkstroem, @MartinSSeifert. @sumitmodi84 on the status, if possible.

We want to confirm that your issue is resolved, so would need your input for this. Thanks.

**Comment by MartinSSeifert** [comment]
@VesaJuvonen sure, so far all looks fine but I am still collecting feedback - will post an update once I have all the feedback.

**Comment by MartinSSeifert** [comment]
@VesaJuvonen, I think it's pretty safe now to say that it is working - got almost all feedback in, and it is 100% positive - thank you, Vessa.

**Comment by waaromikniet** [comment]
Do we need to upgrade to the latest SPFX version? Or is this a tenant fix?

**Comment by andrewconnell** [comment]
@waaromikniet said:

> Do we need to upgrade to the latest SPFX version? Or is this a tenant fix?

No action required on your part... it's a platform fix (ie: server-side), nothing in the SPFx SDK.

**Comment by VesaJuvonen** [comment]
As AC noted, this was a platform level fix. We will be taking much more attention on the list and library areas - or more specifically for the extensions. Given this recent issue, we have already updated our internal process to be more agile on any larger issue. We will keep on evolving our internal process to avoid similar issues in future.

If you see any similar issues with extensions or web parts, please do flag them and we'll start investigating. Thanks @barisbikmaz for a great issue description as that helps enormously on the getting things forward. Huge thanks also for @MartinSSeifert for validating things carefully.
