### ISSUE TITLE
SPFX Library Components - Unable to use SPHttp dependency

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/sp-dev-docs#6612]
When following the tutorial for SPFX Library Components and then trying to add references to AadHttpClient or others within sp-http, the build fails.

HelloWorldLibrary.ts:
```
import { AadHttpClient, HttpClient, HttpClientResponse } from "@microsoft/sp-http";

export class HelloWorldLibrary {
  public name(): string {
    const configuration = AadHttpClient.configurations.v1;
    return 'HelloWorldLibrary';
  }
}
```

Error output start:

```
[13:54:45] Finished subtask 'tsc' after 771 ms
[13:54:45] Finished subtask 'tslint' after 1.44 s
[13:54:45] Starting subtask 'post-copy'...
[13:54:45] Finished subtask 'post-copy' after 172 μs
[13:54:45] Starting subtask 'collectLocalizedResources'...
[13:54:45] Finished subtask 'collectLocalizedResources' after 2.71 ms
[13:54:45] Starting subtask 'configure-webpack'...
[13:54:45] Finished subtask 'configure-webpack' after 13 ms
[13:54:45] Starting subtask 'webpack'...
[13:54:46] Error - [webpack] 'dist':
./node_modules/@microsoft/sp-http/lib/oauthTokenProvider/OAuthTokenProvider.js
Module not found: Error: Can't resolve '@ms/sp-client-shared' in '/home/jim/git/tmp/spfx-lib-fail-test/node_modules/@microsoft/sp-http/lib/oauthTokenProvider'
resolve '@ms/sp-client-shared' in '/home/jim/git/tmp/spfx-lib-fail-test/node_modules/@microsoft/sp-http/lib/oauthTokenProvider'
  Parsed request is a module
  using description file: /home/jim/git/tmp/spfx-lib-fail-test/node_modules/@microsoft/sp-http/package.json (relative path: ./lib/oauthTokenProvider)
    Field 'browser' doesn't contain a valid alias configuration
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b431da26-3a26-bab5-1af4-a151d9e50f2e
* Version Independent ID: 50656bd9-3514-ae39-0805-0927d30e4355
* Content: [Using library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview)
* Content Source: [docs/spfx/library-component-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
I can't repro this... I suspect there was an issue when you installed all dependencies. I'd try deleting your **node_modules** folder & package lock files, then retry NPM INSTALL.

The error indicates the **sp-http** package wasn't downloaded, but running through the tutorial, I can see the exact path on my machine.

**Comment by jimmywim** [comment]
Hi @andrewconnell 

I tried that - same result.

I have uploaded a repo that reproduces this:

https://github.com/jimmywim/spfx-lib-fail-test

It's now making me wonder if node and/or npm versions have something to do with it. I'm on node v10.20.1 and npm v6.14.4

**Comment by andrewconnell** [comment]
I cloned your project and can't dupe this:

![image](https://user-images.githubusercontent.com/2068657/105737107-8a9cbb00-5f03-11eb-8533-a7e09f685c2d.png)

If you have a node_modules folder and/or a **package-lock.json** file, purge them, run **npm i** to ensure you arne't getting an old version of some dependency & try **gulp build** again.

Other than that, dunno what else to suggest :-/

**Comment by jimmywim** [comment]
Just cloned to a completely different physical machine - with just Windows (so no WSL), with Node 10.21.0 and I still get the same result with errors.

Even deleted node_modules, and the package-lock.json and reinstalled, with the same result on a bundle.

Note: my node_modules doesn't have the package it's complaining about in the OP: @ms/sp-client-shared - in fact, there is no '@ms' folder.

**Comment by andrewconnell** [comment]
OK... now I dupe when running **gulp bundle**... same error on macOS v11.1.

**Comment by jimmywim** [comment]
I believe I may have found a workaround:

Install the following packages via `npm install`:

`@microsoft/sp-core-library`
`@microsoft/sp-webpart-base`

The component library now bundles, and the deployed component now loads as needed.

**Comment by AJIXuMuK** [comment]
Tested adding `@microsoft/sp-http` reference using SPFx 1.13 and it seems to work correctly event without core and webpart base.

Please, feel free to open a new issue if there are still any problems with this scenario.
