### ISSUE TITLE
how to configure API REST call in order to update an external data field in SharePoint

### ISSUE THREAD

**Issue by elenabranche** [SharePoint/sp-dev-docs#6619]
## SharePoint API REST

- [ ] how to configure API REST call in order to update an external data field in SharePoint?

## SharePoint

- **SharePoint  Server 2016

*/* Please advise

I want to update in SharePoint a field defined as an external data using REST API. Field name is “Parteneri” from bellow. 
The update method used below doesn't work.
![attachement1](https://user-images.githubusercontent.com/77485804/104708662-a98e9680-5726-11eb-98b1-907ddafc275f.jpg)
![attachement2](https://user-images.githubusercontent.com/77485804/104708701-b3b09500-5726-11eb-8007-0f18bc5d3de1.jpg)

--The REST API call that we use for UPDATE is the method from below. This method doesn’t work to update the external data field "Parteneri". 

Request POST:  https://**************/_api/web/GetFolderByServerRelativeUrl('contracte corporate/test11')/ListItemAllFields
Body: {
"__metadata": {
"type": "SP.Data.Contracte_x0020_CorporateItem"
},
"ContentTypeId":"0x0120D520004B7BADB9E271F645A9D9BE9658A91571",
"Numar_x0020_contract":"contract postman",
"Descriere": "descriere postman",
"Title":"yourname",
"DocSetName":"name",
"NumePartener":"name",
"Parteneri_x003a__x0020_PartnerID": "xxxxxxx",
"Parteneri_x003a__x0020_PartnerID0": "xxxxxx",
"Parteneri_x003a__x0020_PartnerID1": "xxxxxxx",
"Societate_x0020_din_x0020_grup1Id":xxxx,
"Partner_ID": "xxxx"
}

**Comment by Amos-MSFT** [comment]
Hi @elenabranche ,
Try to use the external data column internal name and value directly in the body.
My test result for your reference:
![Captureee](https://user-images.githubusercontent.com/56672877/104877005-ced40c80-5993-11eb-8936-5389222f2f5f.PNG)
![Captureef](https://user-images.githubusercontent.com/56672877/104877008-d09dd000-5993-11eb-846b-315e50771317.PNG)
Amos Wu
Microsoft SharePoint Community Support
