### ISSUE TITLE
Rencore script-check link no longer working

### ISSUE THREAD

**Issue by wpo365** [SharePoint/sp-dev-docs#6623]
It seems that the Rencore script-check tool link is no longer working and results in a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea122b-5a05-70f3-408e-ff17872bac44
* Version Independent ID: ad19ac44-ff94-97f6-159b-9fe5964b3727
* Content: [Add an external library to your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library)
* Content Source: [docs/spfx/web-parts/basics/add-an-external-library.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/add-an-external-library.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
As this is a solution provided by a third party (Rencore), I would suggest reaching out to Rencore directly. We are unable to help in that regard.

**Comment by matthiaseinig** [comment]
We have fixed the link. 

There was a broken redirect and it should be accessible agin both with the old and the new url [https://rencore.com/script-check/](https://rencore.com/script-check/)

it can be used also directly from VS Code via this extension
[https://marketplace.visualstudio.com/items?itemName=RencoreGmbH.vscode-spfx-script-check](https://marketplace.visualstudio.com/items?itemName=RencoreGmbH.vscode-spfx-script-check)

**Comment by andrewconnell** [comment]
Thanks for the follow-up @matthiaseinig! I did some googling and didn't see a valid link hence why we pulled it down. We'll get this re-added with the new link!
