### ISSUE TITLE
Add SPFx based outlook add-in in Office Store

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/sp-dev-docs#6624]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

We have created an outlook add-in application using SPFX. Now we want to put this application with SPPKG in the Microsoft office 365 store as an outlook add-in. We are stuck as we have not found a convenient method. Is there any standard way of  doing this? 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online / Outlook Web Access
- **Framework**: Node.js v6/v8/v10/v12]
- **Browser(s)**: Any
- **Tooling**: VS Code | SPFx v1.11.0 
- **Additional details**: *We want to know how to deploy on Office Store*

**Comment by andrewconnell** [comment]
At the moment, using SPFx in Outlook add-ins is in developer preview mode and not presently supported in the app store.
