### ISSUE TITLE
SPFx app deployed to App Catalog throws error with just Correlation Id

### ISSUE THREAD

**Issue by ruudsolidnl** [SharePoint/sp-dev-docs#6626]
## Category

- [X ] Question

## Question
Hi,
I'm pulling my hair out for several hours now. I have a SPFx solution targeting SPO, v1.11.0. When I deploy the app to the tenant catalog or a site collection app catalog, it will throw an error and only give me a correlation Id. After that, the app is set to "Deployed": no. However, it does deploy the lists in the feature. 

My question is not to solve this issue (as no doubt i messed something up); but in order to save time and a good mood I'm looking for a way to get proper error messages. Those correlation Id's in SPO are not of any use. Where can I request for the exact messages belonging to the correlaction Id? Thanks in advance!

Best regards,
Ruud

## Environment details (if applicable)

- **Your Developer Environment**: Windows 10
- **Target Environment**:SharePoint Online
- **Framework**: Node.js v6/v8/v10/v12
- **Browser(s)**:Chromium Edge v79
- **Tooling**: VS Code | SPFx v1.11.0 
- **Additional details**: SPFx solution which includes a web part and list schema's.

**Comment by Amos-MSFT** [comment]
Hi @ruudsolidnl ,
You could submit a service request in Microsoft 365 admin center, you could get the exact messages with the Correlation Id there.
Amos Wu
Microsoft SharePoint Community Support

**Comment by ruudsolidnl** [comment]
Hi Amos,

Thanks, that was what I needed to know. 

Regards,
Ruud
