### ISSUE TITLE
API management page does not exist

### ISSUE THREAD

**Issue by ishaisagi** [SharePoint/sp-dev-docs#6631]
In the document, you refer to an api management page that does not exist...can you update the article please?

---update: ignore this - the link suddenly appeared after an hour...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Thanks @ishaisagi on following up on this and letting us know that situation is sorted out.
