### ISSUE TITLE
The title says when a new item is created OR modified.  Flow only covers new items - not modified

### ISSUE THREAD

**Issue by visuary** [SharePoint/sp-dev-docs#6634]
This has been previously reported and the issue was Closed without any action taken.  The title of the article is misleading because the flow does not run for new items and modified items, only for new items.

The correct trigger would be "When an item is created or modified"
https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-an-item-or-a-file-is-modified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992f8829-85b4-d17e-c93e-1302d9f7a208
* Version Independent ID: c1e12c09-b58f-c526-907b-b683670a9969
* Content: [Send an email when a new item is created or modified in a SharePoint list](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your-first-flow)
* Content Source: [docs/business-apps/power-automate/get-started/create-your-first-flow.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/get-started/create-your-first-flow.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
I cannot reproduce your issue. I have added this trigger to my list in Flow. I added a new item and I updated a different item, and it triggered both times for me successfully. 

If you aren't experiencing the same, I would recommend opening up a support ticket with Microsoft support through your tenant.

**Comment by visuary** [comment]
There is no way that a flow with the trigger “When a new item is created” is going to fire when an existing item is modified.

I have created the exact flow shown in the article and it never fires when an existing item is modified.

If that is happening in your flow, either your flow or your environment is broken, or you have alerts set on the list and you are mistaking the alert for the email notification from Power Automate.

**Comment by bcameron1231** [comment]
Ah, I'm sorry. I misread your question. So it sounds like you just want the document title and the description to be updated because the method being used is "When an item is added". Yes we can fix this! My apologies for misunderstanding the problem.
