### ISSUE TITLE
JSON for body formatting does not work as mentioned in the documentation

### ISSUE THREAD

**Issue by unnieayilliath** [SharePoint/sp-dev-docs#6637]
In the documentation there is sample code written for custom body JSON with sections. The example JSON provided has 

```
"sections": [
        {
            "displayName": "",
            "fields": [
                "Title"
            ]
        },
```

But using "displayName" with capital "N", list form do not render the value of the attribute in the page. If I replace it with small letter "n" , the section display name gets rendered properly. So, working example should be as below:
```
"sections": [
        {
            "displayname": "",
            "fields": [
                "Title"
            ]
        },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by SmitaNachan** [comment]
This is duplicate to issue https://github.com/SharePoint/sp-dev-docs/issues/6643
PR is already raised for the prior issue https://github.com/SharePoint/sp-dev-docs/issues/6643 at https://github.com/SharePoint/sp-dev-docs/pull/6646

**Comment by VesaJuvonen** [comment]
Closing as issue has been fixed.
