### ISSUE TITLE
 Supportability of publishing infrastructure feature on modern team site

### ISSUE THREAD

**Issue by taisino** [SharePoint/sp-dev-docs#6638]
This page states "Enabling site or site collection scoped publishing features; technically, features can be currently activated, but this is not a supported configuration." but the following page sates "SharePoint Publishing Infrastructure is supported for a modern Team Site.". 
https://docs.microsoft.com/en-us/sharepoint/publishing-sites-classic-to-modern-experience

Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecfd641-4d66-1e34-8c32-1f59b53233d6
* Version Independent ID: 8627d0b0-94c0-f8fe-b753-b8e1411ead41
* Content: [Customizing 'modern' team sites](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-sites.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Correcting the docs to say this is **NOT** supported. Thanks.
