### ISSUE TITLE
Does this endpoint url must be public?

### ISSUE THREAD

**Issue by nvliumang** [SharePoint/sp-dev-docs#6647]
I followed this doc to create a webhook subscription for my SP 2019. if I use Ngrok to expose the URL, then it works fine. If I only publish my service in IIS (locally/private), it will get an error:

![image](https://user-images.githubusercontent.com/24580166/106116033-68699e00-618c-11eb-9710-9a70c2797df6.png)

but my sp 2019 only is on-premise, not for the public. can you explain this?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc58af9c-d9b8-5ed0-6117-2db7a1d425de
* Version Independent ID: 7cc8696c-5946-0414-b5be-c7561d0e31b5
* Content: [Create a new subscription](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/create-subscription#url-validation)
* Content Source: [docs/apis/webhooks/lists/create-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/lists/create-subscription.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Dupe #6639
