### ISSUE TITLE
Header JSON sample fails on NEW FORM

### ISSUE THREAD

**Issue by rohit404404** [SharePoint/sp-dev-docs#6650]
Copied Header JSON sample from this page documentation

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration

It works fine on existing items. However it shows an error for new form, since Title doesnt exist yet

error shows as, **:Failure: Title was not found on the data object.**

Is there a better way to write this header?

**Comment by ofreytag** [comment]
I have the same issue.
I tried this "txtContent": "=if ([$Title] == '','Nouvelle fiche contact','Fiche du contact ' + [$Title] + ' ' + [$FirstName])" instead of "txtContent": "='Contact details for ' + [$Title]" but the issue remains.
Any help appreciated.

**Comment by kkazala** [comment]
this works for me:
` "txtContent": "=if(length([$Title]) == 0, 'New item', 'Item '+[$Title])"`
