### ISSUE TITLE
displayName

### ISSUE THREAD

**Issue by Dukeofdork** [SharePoint/sp-dev-docs#6654]
displayName does not show when you configure the Body of a list form.

According to doc at:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-body-with-one-or-more-sections

You should be able to do like this.
 {
            "displayName": "Details",
            "fields": [
                "Department",
                "Email",
                "Country"
            ]
        },

Section grouping works, but displayName is not visible at the form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Dupe #6647 #6637
