### ISSUE TITLE
Examples did not work as provided

### ISSUE THREAD

**Issue by kevhoyt** [SharePoint/sp-dev-docs#6655]
I was not able to get the display name in the Body to show up using these examples. I had to change "displayName" to "displayname" and then it started working. Unless I have an older version of the code on my tenant can you please investigate and either fix the code or update the documentation? Thank you, cool functionality!

![Not Working](https://user-images.githubusercontent.com/8483139/106291040-c049e880-6210-11eb-83ac-897d865a684a.png)
![Working](https://user-images.githubusercontent.com/8483139/106291045-c344d900-6210-11eb-8ad4-9b9cb00aebba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Dupe #6637 #6643
