### ISSUE TITLE
nav bar search box is not encoding "&" when redirecting to a custom page

### ISSUE THREAD

**Issue by Mr-Clrscr** [SharePoint/sp-dev-docs#6659]
## Category

- [x] Bug

## Describe the bug
navbar search box is not encoding the special characters when redirecting to custom search results page

## Steps to reproduce
s1: create a search results web page with search refiner and search results pages (ootb or pnp)
s2: type a word inside the navbar search in my case it is r&d
s3: see the url which is not encoding the value

## Expected behavior
it should encode the special character inside the url

## Environment details (*development & target environment*)

- **Target Environment**:  SharePoint Online
- **Tooling**: pnp search webpart

<img width="356" alt="se" src="https://user-images.githubusercontent.com/39514550/106308722-22453500-6287-11eb-9b57-79713e0fe6dc.PNG">

**Comment by andrewconnell** [comment]
As this is specific to the PNP Search web part, please post this issue to that project's repo. This issue list is for general SharePoint development issues. Thanks! 

https://github.com/microsoft-search/pnp-modern-search/
