### ISSUE TITLE
Issue with SPFx Web Part as a Teams Personal App in GCC

### ISSUE THREAD

**Issue by goodjohnscott** [SharePoint/sp-dev-docs#6660]
## Category

- [x] Bug

## Describe the bug

I deployed a SPFx web part to Teams in GCC as a personal app.  When I click on the app in teams, the page displays a "**_layouts’s server IP address could not be found**".  Deployed the same SPFx web part to a commercial tenant and works as expected in teams.  I used the Teams web client in both cases.

## Steps to reproduce

1. Create a brand new spfx web part project with yeoman.  Enable tenant wide deployment and choose react as the framework.
1. In the web parts manifest file, update the supported hosts to include 'TeamsPersonalApp'
1. In the web parts .ts file, at line 24, replace **this.properties.description** with **"Test"**.  _I read somewhere that the properties will be undefined in Personal Teams Apps so wanted to rule out that_. 
1. Build and Package the web part with --ship flag
1. in a GCC tenant, upload the .sppkg file to the app catalog.
1. Make sure '**Make this solution available to all sites in the organization**' is checked when you deploy it.
1. Sync to Teams
1. View App in Teams
1. Should see the error: "**_layouts’s server IP address could not be found**"

## Expected behavior

Web part should render the web part.

## Environment details (*development & target environment*)

- Windows 10
- GCC SharePoint Online
- SPFx 1.11, React
- Edge
- VS Code
- Teams Web Client

### Additional context

Repro steps work in a commercial tenant.

**Comment by goodjohnscott** [comment]
In GCC, this is the URL found in the network calls.  It's missing the tenant name.

_https://_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=6ed6cdb3-8353-48d4-a9f0-90b1d7b87c5a%26forceLocale=en-us_

Here is what it looks like in the commercial tenant.

_https://{{tenant name}}.sharepoint.com/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=6ed6cdb3-8353-48d4-a9f0-90b1d7b87c5a%26forceLocale=en-us_

**Comment by goodjohnscott** [comment]
I decided to manually make the teams app manifest file instead of synchronizing to Teams from the app catalog.

It appears that GCC is not honoring the {teamSiteDomain} token in the contentUrl property under static tabs in the manifest but if you replace {teamSiteDomain} with your tenant domain (xxx.sharepoint.com) it works.

**Comment by lucabandMSFT** [comment]
@goodjohnscott, coming back to this issue as it got lost due labeling issues (sorry about that). Can you check if the issue still occurs? Our understanding is that "sync to Teams" should now work in GCC environments.
