### ISSUE TITLE
Is this page really still in preview?

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#6662]
I feel that this page may be out of date as last updated 2 years ago. Is the statement at the start of the article accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c84e281-6a29-c743-63f1-0380a20fc9ad
* Version Independent ID: e2eba2b3-c87f-0b97-bb01-5becefe69aac
* Content: [UnRegisterHubSite REST method](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-unregisterhubsite-method)
* Content Source: [docs/features/hub-site/REST-unregisterhubsite-method.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/hub-site/REST-unregisterhubsite-method.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Better late than never - just updated.
