### ISSUE TITLE
Filter results with api for sharepoint online

### ISSUE THREAD

**Issue by jlorences** [SharePoint/sp-dev-docs#6663]
## Category

- [x] Bug

## Describe the bug

> Sharepoint filter result connected with the Api

- [x] Bug

If you try to refine result on sharepoint online basically sharepoint transforms your string to a different value in example try to refine my results with a text like "Docuementacion comercial", sharepoint online transforms that text into something like "ǂǂ446f63756d656e74616369c3b36e20636f6d65726369616c" so when we try to replicate that call from an api created with VB.net we don´t be able to reproduce that transformation. Anyone knows which encode they are using or how we can get the correct results

## Steps to reproduce

1. Go to any sharepoint site
2. Click on searck and search any term
3. Once you get the result then filter it
4. Check the postquery sent 
5. See the RefinementFilters and look for the term  that you are filtering is now transformed to another thing

## Expected behavior

> We need that term can have spaces or transform into the API no before call the API

## Environment details (*development & target environment*)

> This happen in our local environment as in our production and test environments

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: .NET Framework 4 
- **Browser(s)**: Chrome v79 
- **Tooling**: Visual Studio 2019

### Additional context

> also attached a dock with the information (information is in spanish) but can help the screenshots in the document
[consulta sharepoint.docx](https://github.com/SharePoint/sp-dev-docs/files/5902639/consulta.sharepoint.docx)

**Comment by andrewconnell** [comment]
This appears to be a question about SharePoint's OOTB search experience, not a development question. Is that correct? If so, please direct non-development questions to TechCommunity.

**Comment by jlorences** [comment]
> This appears to be a question about SharePoint's OOTB search experience, not a development question. Is that correct? If so, please direct non-development questions to TechCommunity.

I already contact with Sharepoint tecnicals and they send me to ask here. because they are not able to give me any answer about how I can transform my filter text to the encoded text that sharepoint uses. I will be vary happy if is possible to know which encode sharepoint is using

**Comment by bcameron1231** [comment]
The value you are mentioning is for filtering results from refinement panels... given that this is a VB solution, this isn't really something that you need to do.

Sounds like what you are looking for, is the ability to filter results by the managed property of your search results.

Your options are to use KeywordQuery and update the QueryText, or use the Search REST API and update the querytext using KQL. You can filter results like so... 

`<managedPropertyName>:"Docuementacion comercial"`

For full KQL documentation, follow this link https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

**Comment by jlorences** [comment]
> The value you are mentioning is for filtering results from refinement panels... given that this is a VB solution, this isn't really something that you need to do.
> 
> Sounds like what you are looking for, is the ability to filter results by the managed property of your search results.
> 
> Your options are to use KeywordQuery and update the QueryText, or use the Search REST API and update the querytext using KQL. You can filter results like so...
> 
> `<managedPropertyName>:"Docuementacion comercial"`
> 
> For full KQL documentation, follow this link https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

First of all, Many thanks @bcameron1231. with your help finally I got the solution I used the KQL documentation and there I found the solution to my problem. 
Thanks for all.
