### ISSUE TITLE
Top Navigation menu disappears

### ISSUE THREAD

**Issue by shibu-123** [SharePoint/sp-dev-docs#6664]
On a site page, when we add a custom webpart and publish the page. The top menu navigation menu of communication site disappears. The menu appears only when you scroll down the page. The menu disappears when you scroll up the page. Please let us know how the issue can be resolved.

**Comment by bcameron1231** [comment]
I'm sorry, but we need more information. Can you update this ticket, or re-submit a new one using the outlined template provided. It will be helpful to have details of what versions of SPFx you are using, What version of SharePoint, a brief description as to what your web part does and any applicable screen shots would be helpful.
