### ISSUE TITLE
@microsoft/generator-sharepoint@latest not installing the new Extensions feature. 

### ISSUE THREAD

**Issue by kcraigo** [SharePoint/sp-dev-docs#667]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category

- [ x] Bug

MacOS 10.12.5
Node  v6.11.0
npm v3.10.10

microsoft/generator-sharepoint@latest does not match documentation at https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension

#### Expected or Desired Behavior

Let's create a new SharePoint solution.
1. Which type of client-side component to create?
2. Which type of client-side extension to create?
3. What is your Application Customizer (Preview) name?
4. What is your Application Customizer (Preview) description?

#### Observed Behavior

Let's create a new SharePoint solution.
? What is your solution name? app-extension
? Where do you want to place the files? Use the current folder
? What framework would you like to start with? No javaScript web framework
A folder with solution name app-extension will be created for you.
? What is your webpart name? HelloWorld
? What is your webpart description? HelloWorld description

#### Steps to Reproduce
npm uninstall -g @microsoft/generator-sharepoint
npm install -g @microsoft/generator-sharepoint@latest
yo microsoft/sharepoint

Omitted the AT symbol from above, this editor is stripping it and microsoft/sharepoint out.

**Comment by patmill** [comment]
What version of the extension are you getting?  The @latest should be pulling down 1.1.1  .

I assume your repro steps are actually - but just to confirm
npm uninstall -g @microsoft/generator-sharepoint
npm install -g @microsoft/generator-sharepoint

**Comment by kcraigo** [comment]
Hi Pat, 
Tried once more, still no options for creating extensions 
Confirmed version pulled down is 1.1.1

Repro steps
.1 npm uninstall -g @microsoft/generator-sharepoint

.2 npm install -g @microsoft/generator-sharepoint@latest

**Comment by kcraigo** [comment]
Sorry forgot to wrap these,
Yes the repro steps are :
1. `npm uninstall -g @microsoft/generator-sharepoint`
2. `npm install -g @microsoft/generator-sharepoint@latest`

**Comment by patmill** [comment]
One more question to get the obvious out of the way.  Once you install the generator, can you close your command windows, open a new one, and start from the beginning creating a new project?

**Comment by kcraigo** [comment]
Same result

**Comment by patmill** [comment]
Hmn.  I've gone through the same flow a few times on my machine, switching between 1.0.2 and 1.1.1, and the flows follow what is expected.  Let me see if I can track down someone with a mac to see if that might be the issue.

**Comment by chakkaradeep** [comment]
I don't see this issue on my Mac. @kcraigo can you try the following and let us know what you see:

1. Can you paste what you see when you type just "yo" in the command line?

2. Can you paste what you see when you type "yo @microsoft/sharepoint --help" ?

3. Can you see if you have the the ".yo-rc.json", a hidden file in the folder where you are doing "yo @microsoft/sharepoint"?

**Comment by kcraigo** [comment]
Hi,  
Sorry about this. 
Don't know why I didn't think of this until now but several years ago I changed the default node dir /usr/local/lib/node_modules to .npm-global/lib in my home dir , yo `@microsoft/sharepoint` is referencing the /usr/local/lib/node_modules/@microsoft

Not an issue with other node modules that's what confused me.

**Comment by chakkaradeep** [comment]
In that case, you will need to add this to the npmrc file like this one:

```
prefix=/Users/chakkaradeep/.npm-packages
```

**Comment by kcraigo** [comment]
Hi Chakkaradeep,
Thank you for pointing me in the right direction

I did have ~/.npm-global in the .npmrc
I ended up uninstalling yo and `@microsoft/sharepoint` in the /usr/local/lib/node_modules
and reinstalled both in ~/.npm-global dir

Then ran npm cache clean and revisited the instructions on docs.npmjs.com/getting-started/fixing-npm-permissions 
It now works.

Thank you and Pat

**Comment by chakkaradeep** [comment]
@kcraigo glad to know it's resolved. I am closing this thread for now. Please create a new issue or reopen this thread if you find any issues.
