### ISSUE TITLE
Extension failed to load but works in debug without issue

### ISSUE THREAD

**Issue by theitfactor** [SharePoint/sp-dev-docs#6670]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have a an app package that has several web parts and an application extension. When running in development/debug mode it works fine. When I bundle the app and deploy I get:

```
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.a319c905-0c40-478b-9866-895c6e7e09d3'. Error information is 'Extension failed to load for componentId "a319c905-0c40-478b-9866-895c6e7e09d3".'.
    at sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1
    at async Promise.all (index 0)
```

This error is not giving me an indication as to what the actual error is. When I run `gulp serve` and access the extension via `?debugManifestsFile=.....` It works without issues. How can I figure out what is going on?

## Environment details (*development & target environment*)

This is running SPFX 1.11 in SharePoint online.

**Comment by iStroml** [comment]
I've got the same Problem. 
I tried to setup the spfx-announcements webpart. In gulp serve everything is working as expected. Once the solution is packaged and deployed, the error occurs:
`sp-pages-assembly_de-de_017c1eaa45854b943ce72ed2f66bbe51.js:65 Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.21f58d40-a86a-419a-9478-84f78b2bf638'. Error information is 'Extension failed to load for componentId "21f58d40-a86a-419a-9478-84f78b2bf638".'.
    at sp-pages-assembly_de-de_017c1eaa45854b943ce72ed2f66bbe51.js:65
    at async Promise.all (index 0)`

**Comment by iorivera** [comment]
I have the same error message when I deploy an application customizer package

**Comment by Saintenr** [comment]
same error in my side... SPFX 1.11.0 node 10.24.1 LTS.

Since one month...

Any news on that?

**Comment by iorivera** [comment]
Ultimately I just  kept rebuilding, cleaning, npm install all packages Until it worked. No specific solution sorry.

**Comment by Saintenr** [comment]
On my side the problem was caused by react and reactdom dependencies. I moved them to the dev dependencies and rebuild…
That solved my issue.

**Comment by AJIXuMuK** [comment]
This one is similar to #7564.

@theitfactor - could you check if you're using `@microsoft/sp-http` or some other modules without installing them (or maybe you install them as devDependencies when they should be a part of the bundle)?
