### ISSUE TITLE
Top navigation disappears when deploying custom web part

### ISSUE THREAD

**Issue by shibu-123** [SharePoint/sp-dev-docs#6672]
I have created a custom web part using SPFX version 1.10.0. The custom webpart display list of items from the sharepoint list. I have Material UI framework to develop this report. The issue is when I add my webpart in a site page and publish I could observe the top navigation menu disappears as shown in the below screenshot. Please advise to resolve the issue

![screen1](https://user-images.githubusercontent.com/45416215/106789521-5bf7b080-6678-11eb-96e2-aafbb969eca7.jpg)
![screen2](https://user-images.githubusercontent.com/45416215/106789526-5dc17400-6678-11eb-9e92-907ece66a9a8.jpg)

**Comment by bcameron1231** [comment]
Hi, I am having trouble reproducing this in my environment. Can you confirm if your material styles are conflicting with Microsoft styles in some way?

Also, would it be possible if you could share your SPFx solution with us? That may  make it easier to see what is happening.

**Comment by shibu-123** [comment]
Attached my spfx solution.
[WaitingOnMeGrid.zip](https://github.com/SharePoint/sp-dev-docs/files/5924602/WaitingOnMeGrid.zip)

**Comment by bcameron1231** [comment]
Hi, unfortunately, I am unable to load this. It looks like the solution is dependent on a library component that wasn't included in your solution.
