### ISSUE TITLE
special characters % and #

### ISSUE THREAD

**Issue by mores** [SharePoint/sp-dev-docs#6673]
The web UI allows you to create folders and files that can contain % and #.

How does one need to escape these characters so that GetFolderByServerRelativeUrl returns the expected results ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
You will need to use decodeUrl="" in your REST call, and encode your % and #'s.

Example - If folder is named M#Y
` _api/web/GetFolderByServerRelativePath(decodedurl='/sites/contosoportal/Shared%20Documents/M%23Y')`


Example - If folder is named M%Y
` _api/web/GetFolderByServerRelativePath(decodedurl='/sites/contosoportal/Shared%20Documents/M%25Y')`

**Comment by mores** [comment]
@bcameron1231 - That allows my #'s to work, but I am still having some issue with %.

When I try to add a folder using:
`{ '__metadata': { 'type': 'SP.Folder' }, 'ServerRelativeUrl': 'M%Y' }`
it shows up as:
![image](https://user-images.githubusercontent.com/1318377/106814840-00f69700-6641-11eb-8742-c93fb361d471.png)

I also tried:
`{ '__metadata': { 'type': 'SP.Folder' }, 'ServerRelativeUrl': 'M%25Y' }`
but I get the same result.

**Comment by Jerry0527** [comment]
Try to create folder using AddUsingPath like this:
```
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
        $(function () {
            $("#btnClick").click(function () {
                var requestUri = _spPageContextInfo.webAbsoluteUrl + "/_api/web/Folders/AddUsingPath(decodedurl='/sites/sitename/Shared%20Documents/M%25Y')";
                $.ajax({
                    url: requestUri,
                    type: "POST",
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "content-type": "application/json;odata=verbose",
                        "X-RequestDigest": $("#__REQUESTDIGEST").val()
                    },
                    success: onSuccess,
                    error: onError
                });

                function onSuccess(data) {
                    alert('Folder created successfully');
                }

                function onError(error) {
                    alert(JSON.stringify(error));
                }

            });

        });

    </script>

    <input type="button" id="btnClick" value="Create Folder with% Inside Document Library" />
```
![Snipaste_2021-02-04_16-25-32](https://user-images.githubusercontent.com/28797671/106865056-9d826d00-6705-11eb-9379-4e5cac931466.png)



Reference:

[Create Folder](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api#create-folder)

**Comment by mores** [comment]
@Jerry0527 - folders with percent are now working - thanks.

I am still having an issue creating a file with a percent:
`_api/web/GetFolderByServerRelativePath(decodedurl='Shared%20Documents')/Files/add(url='M%25Y',overwrite=true)`

![image](https://user-images.githubusercontent.com/1318377/106908787-9f303e80-66cd-11eb-977b-ef8ddc74821d.png)

**Comment by Jerry0527** [comment]
@mores , did you check the reference link in my answer carefully ?

It will have demo to add file with special character:

```
url: http://site url/_api/web/GetFolderByServerRelativePath(decodedUrl='folder name')/Files/AddStubUsingPath(decodedurl='testfile.txt')
methods: POST
Headers:
  Authorization: "Bearer " + accessToken
  X-RequestDigest: form digest value
  accept: "application/json;odata=verbose"
  content-type: "application/json;odata=verbose"
  Content-Length: length
```

[Add Files](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api#add-files)

**Comment by mores** [comment]
@Jerry0527 - sorry I did not check your reference before - but that link is the missing piece that is needed to close this issue - a merge request has been opened.

**Comment by Jerry0527** [comment]
@mores , the reference link's title have specified "Supporting % and # in files and folders with the ResourcePath API" clearly, if you check the code demo and have a try, it won't have problem to handle special character with folder/files in Rest/CSOM.
