### ISSUE TITLE
SPFX Outlook Addins: how can you debug your addin in Outlook?

### ISSUE THREAD

**Issue by StevenDerveaux** [SharePoint/sp-dev-docs#6675]
Hi guys

This is very awesome to see. All things are coming more and more together when developing solutions for Office and SharePoint online. What I couldn't found is: How can you debug the solution in Outlook Web client? In SharePoint it is easy, just open your workbench online and you are good to go!

Do you have any idea when this SPFX outlook addins can be used in the Outlook desktop client?
Some kind of a raw timeline?

Thanks and good work!!
Steven
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b8fe2a-2de5-5ebd-c525-506c3916abd5
* Version Independent ID: 2eb9af47-f722-7ec7-e79b-819b6b2b06ac
* Content: [Tutorial for creating Outlook Web Access extension using SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/office-addins-tutorial?source=docs)
* Content Source: [docs/spfx/web-parts/get-started/office-addins-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/office-addins-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Microsoft hasn't shared a timeline for future work on SPFx with Office Add-ins.

For debugging, all the same techniques apply... the workbench is just used to host a web part on a page. Once your SPFx component is running in the Outlook Web App, it's hosted on the page. From there, the same debugging techniques would apply.

**Comment by StevenDerveaux** [comment]
Hi Andrew
Thanks for reaching out!

It is not completely clear to me...

Debugging in SP online => You just open the app page "/_layouts/15/workbench.aspx", add the webpart and debug it ... (that works very good!)

**Debugging in OWA => ?? is there a workbench as well?**

Concerning the timeline: That is too bad :-) The question is, should we wait for it or still create an "old" Outlook-Addin via VS2019.

**Comment by andrewconnell** [comment]
@StevenDerveaux said:

> Debugging in OWA => ?? is there a workbench as well?

No... it's like SPFx extensions: you need a real host to test. Just like extensions need a real modern page / modern list to test, using an SPFx web part as an Office Add-in requires you to run it within OWA.
