### ISSUE TITLE
Cannot export SP Website logo to a Provisioning Template

### ISSUE THREAD

**Issue by indieza** [SharePoint/sp-dev-docs#6677]
Hello,
I have a little problem with the ProvisioningTemplateCreationInformation class, I would like to export SharePoint Website logo and the SharePoint Website background image but the problem is that I cannot extract them locally, I follow the steps from [here](https://channel9.msdn.com/blogs/OfficeDevPnP/Getting-Started-with-PnP-Provisioning-Engine), but the result is not obvious. Also I will provide you my [code](https://github.com/indieza/SharePoint-Projects/blob/master/ProvisioningConsoleApplication/ProvisioningConsoleApplication/StartUp.cs), but it is exactly the same from the Video.

Regards
Simeon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e581d3f-a187-b893-70e3-4c3ab5d45936
* Version Independent ID: d2316e36-fa51-f00e-26eb-5a1efaa0213d
* Content: [Provisioning console application sample](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample)
* Content Source: [docs/solution-guidance/provisioning-console-application-sample.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/provisioning-console-application-sample.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by indieza** [comment]
I also noticed that my program behaves differently when I have to create templates from different tenants. In some tenant I get the website logo (for the example) and in the other I don't. Is it could be a problem with the administration settings in the admin panel or a problem with my permissions in the website. For my opinion it could be, because the C# code is the same but the tenants are different.

**Comment by BassemNKhalil** [comment]
Seems to be related to https://github.com/pnp/pnpframework/issues/172, might be worthy to post PnP Provisioning issues not related to documentation on [PnP framework Github issues](https://github.com/pnp/pnpframework/issues/) as the maintainers there may have more information
