### ISSUE TITLE
Deployed SharePoint extension not showing on App Catalog

### ISSUE THREAD

**Issue by Cailenys** [SharePoint/sp-dev-docs#6683]
## Category

- [x] Bug

## Describe the bug

I created a SharePoint extension and deployed it on Microsoft 365 tenant. I want to install this extension on a subsite, but it is not showing on the App Catalog (the extension is on _“Apps for SharePoint”_, but it’s not showing on _“Apps you can add"_).

According to my research, this problem could be fixed by **changing the settings on Master Page?**. 

- 	To activate the master page, is required to activate the SharePoint Server publishing feature.
- 	To active SharePoint Server publishing feature, is required to enable SharePoint Publishing Infrastructure. 
- 	When activating SharePoint Server Publishing Infrastructure, it shows the following error: 

                **Sorry, something went wrong. An unexpected error has occurred.**

Unfortunately, this issue has become “the chicken and the egg" situation. Any suggestions on how to show my extension on the App Catalog would be very appreciated. 

## Steps to reproduce

1. Follow Microsoft tutorial [Build your first SharePoint Framework Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
    **Note:** When creating the new SharePoint solution, **answer _YES_ when you are asked to deploy the solution to all sites running any feature deployment or adding an app in the sites**. 
2. [Deploy your extension to SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint)
3. [Host an SPFx extension from the Microsoft 365 CDN](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/hosting-extension-from-office365-cdn)
4. Create a subsite
5. Try to install the new extension on the subsite

## Expected behavior

App extension is not available on App Catalog.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online
- **Framework**: SharePoint Framework 
- **Browser(s)**: Edge 
- **Tooling**: VS Code

**Comment by andrewconnell** [comment]
@Cailenys said:

> According to my research, this problem could be fixed by **changing the settings on Master Page?**.

That wouldn't be the case, as customizations to Master Pages are not recommended or supported.

Extensions are installed to an entire site collection, not subsites. What exactly are you trying to accomplish?

BTW, when you do this:

> Note: When creating the new SharePoint solution, answer YES when you are asked to deploy the solution to all sites running any feature deployment or adding an app in the sites.

When you upload the solution, it's automatically getting installed to all site collections when the solution is deployed.
