### ISSUE TITLE
Typo under artifacts section

### ISSUE THREAD

**Issue by petrenkotx** [SharePoint/sp-dev-docs#6685]
[Enter feedback here]
Under the section [artifacts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops#preparing-the-artifacts) a typo:
```
**\*.sppkg
```
It should have a forward slash
```
**/*.sppkg
```
With a backward slash it will not match any file, resulting in `0 files found`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Isn't that going to depend on the host agent OS? If it's Windows backslash will work, but under Ubuntu, forward slashes will work.
