### ISSUE TITLE
createDefaultAssociatedGroups throws exception for modern sites

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6693]
## Category

- [x] Bug

## Describe the bug

The REST API method `createDefaultAssociatedGroups` throws exception "Access Denied" for modern sites (if the setting "No Script Site" is set to true, which is the default).

## Steps to reproduce

Create a new modern Teams site, then run against it the following code (creates a sub-site):
```ts
const created = await sp.web.webs.add("My Web", "web1", "", "STS#3", 1033, false);
const admin = await sp.web.ensureUser("me@mytennant.sharepoint.com");
await created.web.createDefaultAssociatedGroups("My Web", admin.data.LoginName, false, true);  // << 403 here
```

This results in 403: Access denied for farm admin

Note: If you [allow custom scripts](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script), the code above works. 

## Expected behavior

The call to **create default groups** for a site works regardless of the scripting setting. For the farm (global) admin, at least.

## Environment details (*development & target environment*)

- **Target Environment**: [SharePoint Online]
- **Browser(s)**: [Chrome v88]
- **Tooling**: [SPFx v1.11.0]

### Additional context

The issue was initially created in PNPJS repository, but since it's more related to REST API, the example is using PNP: https://github.com/pnp/pnpjs/issues/1575. 

The framework used to call this API does not seem to matter, though (same issue with CSOM, for example):  https://sharepoint.stackexchange.com/questions/240933/why-would-createdefaultassociatedgroups-stop-to-serverunauthorizedaccessexceptio

**Comment by andrewconnell** [comment]
This looks like you're using the PnPJS library... so this issue should be posted to their repo: https://pnp.github.io/pnpjs/#issues-questions-ideas

This repo is for general SharePoint development issues. Issues related to specific projects should be posted to their respective project issue lists.
