### ISSUE TITLE
Valid for 12 months

### ISSUE THREAD

**Issue by TobiasAT** [SharePoint/sp-dev-docs#6694]
As I know these SharePoint apps are valid for 12 months, then they expire and a new one must be created. Is there a possibility to extend the 12 months, or to adjust the 12 months during the creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
Yes, By default, the Client Secret is valid for 12 months.

You can generate a new Secret using the function in this documentation:

[Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)

**Comment by TobiasAT** [comment]
Thanks Jerry, that helps a lot 👍
