### ISSUE TITLE
Cancel Upload and Delete File

### ISSUE THREAD

**Issue by jakeb16** [SharePoint/sp-dev-docs#6696]
Note: this page doesn't mention how to handle the case where the upload fails for example if the file exceed the max file size configured. In this case  your left with a half upload file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8869da6e-b785-abff-937e-a1d95bcd8314
* Version Independent ID: d77fd4c4-5149-f4ac-da03-f0803091dc1c
* Content: [Upload large files sample SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-large-files-sample-app-for-sharepoint)
* Content Source: [docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Upload-large-files-sample-app-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
While true, the docs can't address every single possible outcome or error that may happen... not just these docs, but no technical docs do that. 🙂

If they did, they'd be so long that they'd be hard to consume...

For your scenario, IMHO, the solution would be to delete the file you uploaded.
