### ISSUE TITLE
Single Part App Pages - Thumbnail Configuration

### ISSUE THREAD

**Issue by coreyroth** [SharePoint/sp-dev-docs#6697]
In Vesa's video, he mentioned that the documentation for configuring the thumbnail for a web part on a Single Part App Page would be coming later as the documentation has been updated.  I've done a lot of looking through blogs, code, and forums to see if I can figure it out, but I have been unsuccessful.  I assume this can be added by adding something to the web part's manifest.  Any guidance would be appreciated.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42d2d41-61bb-e281-3dac-328292b7b192
* Version Independent ID: 05b12512-7aa9-3ac7-e23e-0d5ae2209a59
* Content: [Using single part app pages in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?tabs=pnpposh)
* Content Source: [docs/spfx/web-parts/single-part-app-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/single-part-app-pages.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by BassemNKhalil** [comment]
The [Set-PnPClientSidePage](https://pnp.github.io/powershell/cmdlets/Set-PnPClientSidePage.html) seems to have a thumbnail parameter, is that what you're looking for ?

**Comment by coreyroth** [comment]
@BassemNKhalil I'm looking on how to do specify it in the configuration of my web part (i.e.: in the manifest perhaps).  That way when it gets deployed by a customer, they would see the thumbnail.  Thanks!
