### ISSUE TITLE
Is it possible to set order of extension button in page ribbon?

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#6700]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
Hi
Is it possible to fix the order of the button for a listview command set in a sharepoint pages ribbon?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**:Edge
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
As they use the [`<CustomAction>`](https://docs.microsoft.com/sharepoint/dev/schema/customaction-element) feature element to provision buttons upon deployment, have you tried using the `sequence` attribute
