### ISSUE TITLE
InstanceId in url for Highlighted Content WebPart

### ISSUE THREAD

**Issue by derhallim** [SharePoint/sp-dev-docs#6704]
## Category

- [x] Question

## Question
I have multiple highlighted content webparts on one page, when clicking on "Sell All" it takes us to a page with url similar to this: 

https://org.sharepoint.com/sites/yoursite/_layouts/15/SeeAll.aspx?Page=%2Fsites%2Fyoursite&InstanceId=efb80a96-6ccf-45c6-8516-b5fc06eb874e

What does the InstanceId represent here? If I want to to provision these pages dynamically, how can I know the url beforehand with the InstanceId in order to link to them in the navigation for example?

**Comment by bcameron1231** [comment]
The instanceId references an internal id that matches the instance of this web part on the page it's been put on.

You shouldn't need this to provision pages with the highlighted content on it. And the See All functionality is handled dynamically from SharePoint.

**Comment by derhallim** [comment]
What I did was provisioning a page with a highlighted content webpart that has a custom query to do what I needed it to do. With a 2 columns section, each has a text webparts, one for title and the other for "see all" link that goes to that page where I can control the exact query.
