### ISSUE TITLE
How to  provision SharePoint online list (asset) with localizing columns from (SPFx) SharePoint client side web part?

### ISSUE THREAD

**Issue by jaganpt** [SharePoint/sp-dev-docs#6705]
My requirement is to provision a SharePoint online list with localizing columns from SPFx web part.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package 

As per the above MS documentation, this has to be done in "Schma.xml" and it referred to the below Url.
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ff955226(v=office.14)

As per this, the xml for the filed looks like: which is to use global resource folder.
 
![image](https://user-images.githubusercontent.com/78982760/107819808-09a24800-6d7a-11eb-9efb-09cf51fd5343.png)
![image](https://user-images.githubusercontent.com/78982760/107819901-30607e80-6d7a-11eb-8e9a-e8154822243f.png)
![image](https://user-images.githubusercontent.com/78982760/107819316-3f92fc80-6d79-11eb-805e-9c18a6328f51.png)

But this applies to: SharePoint Foundation 2010 and not for SharePoint online.

Please let me know how to  provision a SharePoint online list (asset) with localizing columns from (SPFx) SharePoint client side web part.  
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
@jaganpt said:

> Please let me know how to provision a SharePoint online list (asset) with localizing columns from (SPFx) SharePoint client side web part.

If you really want to do it from a web part, your only option is to use the REST API. The provisioning process you link to is for provisioning the assets at the time of installing the solution.

You should also take a look at the [provisioning stuff from PnP](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine) or [site scripts](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview) capability in SharePoint.
