### ISSUE TITLE
Execute Power Automate flow "For selected item"

### ISSUE THREAD

**Issue by masterl1983** [SharePoint/sp-dev-docs#6706]
## Category

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I have built a Command Set Extension and it works great. But is there a way to trigger a Flow which uses "For selected item" trigger. Just like the way when using Column Formatting (customRowAction/executeFlow).

I just want to have a Button which is only visible if one item is selected and when pressed I want to have the flow panel to appear.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]

**Comment by Amos-MSFT** [comment]
We could trigger the flow in SPFX extension command set, but I did not find a way to show the flow panel.
Reference on how to trigger flow in SPF:https://www.c-sharpcorner.com/article/execute-power-automate-workflow-from-spfx/
Amos Wu
Microsoft SharePoint Community Support

**Comment by BassemNKhalil** [comment]
Is using Command Set Extension a requirement? It seems to be possible using column formatting

http://www.benprins.net/2020/02/20/flow-button-to-launch-a-flow-from-a-view/
https://wonderlaura.com/2018/07/18/button-in-sharepoint-list-to-trigger-microsoft-flow/

Both would allow to trigger a flow using a specific item (one in the row with the button clicked) - the second one builds on that with a show/hide flow button based on a column value, possibly you can do the same for selected items

Microsoft docs for reference
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow
