### ISSUE TITLE
Isolated SPFx webparts are not loading in Microsoft Teams Desktop App

### ISSUE THREAD

**Issue by prademi** [SharePoint/sp-dev-docs#6708]
## Category

- [x] Bug

## Describe the bug

We created an isolated web part ( Just vanilla hello world web part ) and tried to load it in Microsoft teams. It worked pretty much fine in the Teams web version but not in the Teams desktop version. It just loads blank.

image
![image](https://user-images.githubusercontent.com/65328772/107914300-244a0c00-6f88-11eb-9117-947a476db4c5.png)

## Steps to reproduce

Here is the screenshot of fiddler trace and how web part is loading in teams (both web and desktop version).

Web Version
image
![image](https://user-images.githubusercontent.com/65328772/107914362-417eda80-6f88-11eb-96a2-17f90a6d94ce.png)

Desktop Version
image
![image](https://user-images.githubusercontent.com/65328772/107914384-5196ba00-6f88-11eb-822b-ab22203967fc.png)

Fiddler Trace:
Teams Desktop (vs) Web

image
![image](https://user-images.githubusercontent.com/65328772/107914266-109ea580-6f88-11eb-8ec6-43eab4601a8f.png)

## Expected behavior

Isolated webparts should work in both teams desktop client and team browser.

## Environment details (*development & target environment*).

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**: Chromium Edge v79
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
Apparently, this is a known issue with isolated web parts & the Teams client: #4669 #4915
