### ISSUE TITLE
Webpart SPFX Issue: Items$expand=Categorie vs column Categorie

### ISSUE THREAD

**Issue by Mustapha147** [SharePoint/sp-dev-docs#6709]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

Hi, 
This is me again I have a trouble in lookup field, my Code list has a field named Categorie and this code:
Items$expand=Categorie&$select=Title,Column_x002d_1,Column_x002d_2,Column_x002d_3,Column_x002d_4,Column_x002d_5,Date,Police_1,Police_2,Categorie/Title"

it seems like he mixed between Categorie for lookup field and my own field Categorie.
![10](https://user-images.githubusercontent.com/44226257/107933009-800f9780-6f7e-11eb-8b7f-b2f148d204f7.png)
![100](https://user-images.githubusercontent.com/44226257/107933012-8140c480-6f7e-11eb-90ec-8c2667536c30.png)

**Comment by andrewconnell** [comment]
This is a TypeScript syntax issue... you can't define a property on an interface of different types. You'd get the same error on line 53 if you added `CodePaie: number;` because it's already defined as a string.
