### ISSUE TITLE
Note: Process does not work on Sites created for Private MSFT TEAMS Channels

### ISSUE THREAD

**Issue by mwsaunders** [SharePoint/sp-dev-docs#6710]
[SharePoint Sites created when a Private Microsoft TEAMS Channel is created have a Web Template ID of 69. As of 02/15/2021 - After a lengthy case, Microsoft has confirmed that this process does not support a Web Template ID of 69. Thus there is no way to customize the default site design when SharePoint sites are created for Private Microsoft Teams Channels.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f32aba9c-798d-263b-27fa-b5e0e23b456c
* Version Independent ID: 554c3429-6bb3-3c0e-3cf9-6365f5b83881
* Content: [Customize default site designs in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design)
* Content Source: [docs/declarative-customization/customize-default-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/customize-default-site-design.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by sparkitect** [comment]
This is still/again a problem.

Prior to the change to the new "Apply a Site Template" UI, we were able to use the "Site designs" UI to apply them to a private channel site, but with the new UI, our designs/template aren't listed.

Corresponding PowerShell cmdlets also don't work for private channel sites.

**Comment by dewcatpaint1** [comment]
We are currently working on updates to allow site scripts via PowerShell to work on Teams Connected channel sites. Some actions will not be allowed on these sites, however they will gracefully fail. Please watch for a message center post and documentation on this issue in the coming month.

**Comment by sparkitect** [comment]
@dewcatpaint1 Would this also make it possible to use them for team sites that were created "without a Microsoft Group", those with an underlying template of STS#3?

**Comment by dewcatpaint1** [comment]
@sparkitect site templates are available for the following web templates: 

WebTemplate - Value = 64 (Team site template)
Web Template 1 - Value = 1 (Team site with group creation disabled)
Web Template - Value = 68 (Communication site template)
Web Template - Value = 69 (Channel site template)

The ability to use site templates on channel sites is now unblocked so I am closing this issue.
