### ISSUE TITLE
Problem with the first commandline

### ISSUE THREAD

**Issue by Donszie** [SharePoint/sp-dev-docs#6716]
Hi,

I got stuck on the first section of the article. The registerAzureADapp line is incomplete. It ends with a space and a period which I think is kind of odd.
I figured it out for myself to put "path c:\temp" after -Out

Thanks for all the work you all put in here!

Niels

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58783cb-5827-81c0-c696-9b4fb299694f
* Version Independent ID: fa4deb1f-144b-8ac2-ff2b-e27232660f1c
* Content: [Calling the PnP provisioning engine from a site script](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning)
* Content Source: [docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-pnp-provisioning.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
@erwinvanhunen, can you look at the first code snippet here:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning#set-up-app-only-access-to-your-tenant

Is the current line correct or should the line just end with `-out`?

**Comment by erwinvanhunen** [comment]
Actually the space and the dot is correct. It means the current folder in PowerShell. Obviously you can provide you own path too if you want.

**Comment by andrewconnell** [comment]
Thanks @erwinvanhunen!
