### ISSUE TITLE
Not able to add the webpart in subsites

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-docs#672]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [x] Bug
- [ ] Typo
- [ ] Additional article idea

#### Expected or Desired Behavior
Deployed WebPart should be available in the pages under subsites.

#### Observed Behavior
WebPart not coming in the WebPart gallery of pages under the subsite.

#### Steps to Reproduce
Create a Sharepoint Framework WebPart and package it using below commands
gulp bundle --ship
gulp package-solution --ship

Deploy package to app catalog and place files in CDN library inside the website where you are adding WebPart. Add deployed app to the root site collection and you will be able to add web part in root site. but you will not be able to see the same web part in subsite page, not able to add the app in subsite its saying that 'App already exists' but it's not added.

If I need to do some configuration then please let me know.

**Comment by craghavendra21** [comment]
First time deployment only facing this issue after removing and adding the app it started working

**Comment by SharadKamate** [comment]
Remove installed app, and make recycle bin empty and try to recreate app in site collection or subsite. It worked fine for me.
