### ISSUE TITLE
Get a URL from a SharePoint List item and convert it to base64 using JavaScript

### ISSUE THREAD

**Issue by vivekmurli** [SharePoint/sp-dev-docs#6721]
Hello All,

I have a list with 2 columns namely DistributorLogo and BaseURL as shown below.

The Distributor logo column contains an image URL

![image](https://user-images.githubusercontent.com/6428093/108250334-09c18f80-714e-11eb-86d5-bd4fccc81707.png)

I am trying to get the image URL from the DistributorLogo column and save the resultant base64 value to the BaseURL Column

**Code to get all the list items:**

```
function GetItemId()
  {
    //debugger;
    var deferred = $.Deferred();
    $.ajax({
        url: _spPageContextInfo.webAbsoluteUrl +"/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/Items?$select=ID,EncodedAbsUrl,BaseURL,DistributorLogo,Distributor_x0020_ID",
        method: "GET",
        type: 'get', 
        async: false,       
        headers: {
            "accept": "application/json;odata=verbose",
            "content-Type": "application/json;odata=verbose"
        },
        success: function(result) {         
            deferred.resolve(result);
            console.log(result);
            
            $.each(result.d.results, function(index, row){

            UpdateListItemUsingItemId(row["ID"],row["EncodedAbsUrl"]); 

            });


        },
        error: function(result){               
            deferred.reject(result);
        }
    }); // Ajax list items
    
     return deferred.promise();

  };  
```
**Update List Item Code**

```
var UpdateListItemUsingItemId = function (Id,dLogo) {
    var deferred = $.Deferred();  
    getBase64Image(dLogo)
    var _listItem = {
            "__metadata": { 'type': 'SP.Data.DistributorsListUpdatedListItem' },            
            
            "BaseURL" : distlogo  
        }

  
    $.ajax({
        url:_spPageContextInfo.webAbsoluteUrl +"/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/GetItemById("+ Id +")",       
        method: 'PATCH',
        async: false,
        data: JSON.stringify(_listItem),
        headers: {
            "accept": "application/json;odata=verbose",
            "X-RequestDigest": $("#__REQUESTDIGEST").val(),
            "content-Type": "application/json;odata=verbose",
            "X-Http-Method": "PATCH",
            "If-Match": "*"
        },
        success: function (data) {          
            deferred.resolve(data);
        },
        error: function (err) {
            deferred.reject(err);
        }
    }); // ajax | POST      
    return deferred.promise();    
}; // updateListItem() | Ends!


```
**Code for base64 conversion**

```
function getBase64Image(dLogo) {

  var canvas = document.createElement("CANVAS");
  var ctx = canvas.getContext("2d");
  ctx.clearRect( 0 , 0 , canvas.width, canvas.height );
  ctx.fillStyle="#FFFFFF";
  ctx.fillRect(0 , 0 , canvas.width, canvas.height);
  var img = new Image();
  
  img.crossOrigin = 'Anonymous';
  
  img.onload = function(){
  
   canvas.width = img.width;
   canvas.height = img.height;
   ctx.drawImage(img, 0, 0);
   
   var dataURL = canvas.toDataURL("image/jpeg");
   //alert(dataURL);
   //return dataURL;
   distlogo = dataURL;
   canvas = null;
   
  };

  
   img.src = dLogo;
}

 });
```
The base64 conversion code works fine when we pass a URL from a textbox control to the function , However fails and returns blank when passed dynamically from the response array.

The working format of the base64 string is

> data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAg

Would really appreciate if anyone could help me fix the issue so that all the URLs in the list could be converted to base64 URL to be used in a PDF.

Please let me know if more details are needed.

Thanks in Advance

**Comment by vivekmurli** [comment]
@waldekmastykarz @PopWarner would really appreciate if you could help me out with this.

**Comment by Jerry0527** [comment]
I just tested and answered in StackExchange, please check the answer:


Here are some points needs to modify:

1. Update List Item needs to use Post method and MERGE X-Http-Method (Not PATCH)
2. If want to convert DistributorLogo to Base64URL, use DistributorLogo instead of EncodedAbsUrl.
3. canvas.toDataURL is async request, needs a callback action to get the base 64 string before updating list item.
4. The BaseURL field should be a Multi-Line text field, othewise will throw 500 error.

Here is the modified code snippet based on the point above:

```
     <script type="text/javascript">
        
        GetItemId();
       
        function UpdateListItemUsingItemId(Id, dLogo)
        {
            var deferred = $.Deferred();
            toDataUrl(dLogo, function (myBase64) {
                console.log(myBase64);
                var _listItem = {
                    "__metadata": { 'type': 'SP.Data.DistributorsListUpdatedListItem' },

                    "BaseURL": myBase64
                }


                $.ajax({
                    url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/Items(" + Id + ")",
                    method: 'POST',
                    async: false,
                    data: JSON.stringify(_listItem),
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "X-RequestDigest": $("#__REQUESTDIGEST").val(),
                        "content-Type": "application/json;odata=verbose",
                        "X-Http-Method": "MERGE",
                        "If-Match": "*"
                    },
                    success: function (data) {
                        deferred.resolve(data);
                    },
                    error: function (err) {
                        deferred.reject(err);
                    }
                });
                return deferred.promise();
            });


         }; 

        function GetItemId() {
            //debugger;
            var deferred = $.Deferred();
            $.ajax({
                url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/Items?$select=ID,BaseURL,DistributorLogo",
                method: "GET",
                type: 'GET',
                async: false,
                headers: {
                    "accept": "application/json;odata=verbose",
                    "content-Type": "application/json;odata=verbose"
                },
                success: function (result) {
                    deferred.resolve(result);
                    $.each(result.d.results, function (index, row) {
                        UpdateListItemUsingItemId(row["ID"], row["DistributorLogo"]);

                    });


                },
                error: function (result) {
                    deferred.reject(result);
                }
            }); // Ajax list items

            return deferred.promise();

        };  
        function toDataUrl(url, callback) {
            var xhr = new XMLHttpRequest();
            xhr.onload = function () {
                var reader = new FileReader();
                reader.onloadend = function () {
                    callback(reader.result);
                }
                reader.readAsDataURL(xhr.response);
            };
            xhr.open('GET', url);
            xhr.responseType = 'blob';
            xhr.send();
        }


       
    </script>
```

Here is the result capture:

![Snipaste_2021-02-18_11-34-21](https://user-images.githubusercontent.com/28797671/108302278-9c117400-71de-11eb-8c28-ff1f906422dd.png)

**Comment by vivekmurli** [comment]
@Jerry0527 Thank you so much for helping me out with the code.

The code returns a base64 string the works as expected in the browser , However when I try to use it an a PDF , it returns a dark image as shown below

![image](https://user-images.githubusercontent.com/6428093/108321618-53e15a00-71bc-11eb-9ff9-f0f33baec845.png)

For the same reason , I used the concept of canvas to set the background image to white and everything was working as expected

Can you help me use the same function dynamically in place of toDataUrl function or if this could be achieved in toDataUrl ?

Thank you again for all the help :)

**Comment by Jerry0527** [comment]
Use the function in here with [canvas ](https://gist.github.com/CawaKharkov/1c477d44fcfdf67aea3f)

```
function convertImgToBase64URL(url, callback, outputFormat){
    var img = new Image();
    img.crossOrigin = 'Anonymous';
    img.onload = function(){
        var canvas = document.createElement('CANVAS'),
        ctx = canvas.getContext('2d'), dataURL;
        canvas.height = img.height;
        canvas.width = img.width;
        ctx.drawImage(img, 0, 0);
        dataURL = canvas.toDataURL(outputFormat);
        callback(dataURL);
        canvas = null; 
    };
    img.src = url;
}
```
Usage:

```
convertImgToBase64URL('http://bit.ly/18g0VNp', function(base64Img){
    // Base64DataURL
});
```
Here is the final modified code snippet, please check:

```
 <script type="text/javascript">

        GetItemId();
       
        function UpdateListItemUsingItemId(Id, dLogo) {
            var deferred = $.Deferred();
            convertImgToBase64URL(dLogo, function (base64Img) {
                console.log(base64Img);
                var _listItem = {
                    "__metadata": { 'type': 'SP.Data.DistributorsListUpdatedListItem' },

                    "BaseURL": base64Img
                }


                $.ajax({
                    url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/Items(" + Id + ")",
                    method: 'POST',
                    async: false,
                    data: JSON.stringify(_listItem),
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "X-RequestDigest": $("#__REQUESTDIGEST").val(),
                        "content-Type": "application/json;odata=verbose",
                        "X-Http-Method": "MERGE",
                        "If-Match": "*"
                    },
                    success: function (data) {
                        deferred.resolve(data);
                    },
                    error: function (err) {
                        deferred.reject(err);
                    }
                });
                return deferred.promise();
            });
        };

        function GetItemId() {
            //debugger;
            var deferred = $.Deferred();
            $.ajax({
                url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DistributorsListUpdated')/Items?$select=ID,BaseURL,DistributorLogo",
                method: "GET",
                type: 'GET',
                async: false,
                headers: {
                    "accept": "application/json;odata=verbose",
                    "content-Type": "application/json;odata=verbose"
                },
                success: function (result) {
                    deferred.resolve(result);
                    $.each(result.d.results, function (index, row) {
                        UpdateListItemUsingItemId(row["ID"], row["DistributorLogo"]);

                    });


                },
                error: function (result) {
                    deferred.reject(result);
                }
            }); // Ajax list items

            return deferred.promise();

        };
        function convertImgToBase64URL(url, callback, outputFormat) {
            var img = new Image();
            img.crossOrigin = 'Anonymous';
            img.onload = function () {
                var canvas = document.createElement('CANVAS'),
                    ctx = canvas.getContext('2d'), dataURL;
                canvas.height = img.height;
                canvas.width = img.width;
                ctx.drawImage(img, 0, 0);
                dataURL = canvas.toDataURL(outputFormat);
                callback(dataURL);
                canvas = null;
            };
            img.src = url;
        }
    </script>
```

**Comment by vivekmurli** [comment]
@Jerry0527 Thank you again for helping me out with something I felt is not possible.

Was able to get the image in the required format.

One last challenge I am facing is in the update function , At the time of debugging , It exits the function after console.log(base64Img); without executing the lines of code after console.log.

Also we get the 400 error

![image](https://user-images.githubusercontent.com/6428093/108333181-9741c580-71c8-11eb-8b44-ad74aefda3da.png)

This is a customized .aspx with a custom masterpage and l am using a submit button to run the getItemId() function

![image](https://user-images.githubusercontent.com/6428093/108333737-2d75eb80-71c9-11eb-8147-df878e1b5d4e.png)


![image](https://user-images.githubusercontent.com/6428093/108333580-04555b00-71c9-11eb-8467-49451c5f834a.png)

Confirmed that the BaseURL is a multi column field with the field name as BaseURL

![image](https://user-images.githubusercontent.com/6428093/108334089-8180d000-71c9-11eb-8c65-97701eda5956.png)

Can you please let me know if I am missing out anything in the code , also would you mind sharing you test aspx page with me for reference.

**Comment by Jerry0527** [comment]
Checkout the Network tab in Developer Tool to get the detailed error message.
400 error will happen if the image size is large to exceed the max stream value like this:

![Snipaste_2021-02-18_17-24-25](https://user-images.githubusercontent.com/28797671/108335703-3341f000-720e-11eb-8c39-f3be8d6a9d40.png)

Try a small size image, it should be working and will return a 201 response code.

**Comment by vivekmurli** [comment]
@Jerry0527 Getting the below error in response

![image](https://user-images.githubusercontent.com/6428093/108337148-b7738380-71cc-11eb-8ae2-396ca2eca842.png)

**Comment by vivekmurli** [comment]
@Jerry0527 Got it to work , changed SP.Data.DistributorsListUpdatedListItem to SP.Data.DistributorsUpdatedListItem .

Thank you for all the help and support , appreciate it :)

**Comment by Jerry0527** [comment]
Yes, the type can be got with this code snippet, if you don't want to set manually:

function GetItemTypeForListName(name) {
    return "SP.Data." + name.charAt(0).toUpperCase() + name.split(" ").join("").slice(1) + "ListItem";
}

usage:

 var itemType = GetItemTypeForListName(listName);
    var item = {
        "__metadata": { "type": itemType },
        "Title": newItemTitle
    };

Now very glad to hear it's working for you, I suggest you could close both this issue in GitHub and the question in StackExchange :)

**Comment by vivekmurli** [comment]
@Jerry0527 closing the issue as resolved :Thank you again 🥇

**Comment by vivekmurli** [comment]
@Jerry0527  closing the issue as resolved :Thank you again 🥇

**Comment by vivekmurli** [comment]
@Jerry0527 just a small doubt , I ran the code on a document library that has around 700+ URLs , However not all the items were updated, any suggestions?

**Comment by Jerry0527** [comment]
Try to trace the Rest Request in Network, check out if there is some error message for updating item like the capture in the comment above :)

**Comment by vivekmurli** [comment]
@Jerry0527 Thanks :) , would check the network to see if I find anything

In the meantime , would you mind checking at your on a few list items to understand the behavior?

**Comment by vivekmurli** [comment]
@Jerry0527 Please check this link when time permits , I'm still getting issues with batch update
https://github.com/SharePoint/sp-dev-docs/issues/6744
