### ISSUE TITLE
Web API with sharepoint

### ISSUE THREAD

**Issue by rwales10** [SharePoint/sp-dev-docs#6722]
This material looks really promising.  What is site_url?  Is it the url of the website?  The sharepoint site?  An explanation would be hepful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Amos-MSFT** [comment]
The `https://{site_url}` reprensents the current site url.

In actual use, we usually add `_spPageContextInfo.webServerRelativeUrl` in front of the REst API before making a request. The value of` _spPageContextInfo.webServerRelativeUrl` is the address of the relative path of the current site. When making a request, SharePoint will automatically add the URL of the web application in front of the API.

Example:
1. URL:http://spwfe/sites/dev/_layouts/15/viewlsts.aspx?view=15
The site_url is `spwfe/sites/dev`
` _spPageContextInfo.webServerRelativeUrl`:/sites/dev
2. URL:http://spwfe/sites/dev/project/default.aspx
The site_url is `spwfe/sites/dev/project`
` _spPageContextInfo.webServerRelativeUrl`:/sites/dev/project
3. URL:http://spwfe/_layouts/15/settings.aspx
The site_url is `spwfe`
` _spPageContextInfo.webServerRelativeUrl`:/

Code example:
```
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
<script>
  test()
  function test() {
    console.log(_spPageContextInfo.webServerRelativeUrl+"/_api/web/GetFolderByServerRelativeUrl('/sites/dev/Shared Documents')")
    $.ajax({
      url: _spPageContextInfo.webServerRelativeUrl+"/_api/web/GetFolderByServerRelativeUrl('/sites/dev/Shared Documents')",
      method: "GET",
      headers: { "Accept": "application/json; odata=verbose" },
      success: function (data) {
        console.log( data)
      },
        error: function (data) {
          console.log(data);
        }
      });
  }
</script>
```
Test result:
![iiii](https://user-images.githubusercontent.com/56672877/108296300-3c15d000-71d4-11eb-8f49-640aea82e8c8.PNG)
Amos Wu
Microsoft SharePoint Community Support

**Comment by rwales10** [comment]
Thank you!

Roland Wales
Senior Programmer/Analyst
207 656-2487
