### ISSUE TITLE
Link to GetChanges API points to unmaintained reference page on microsoft.com

### ISSUE THREAD

**Issue by ejschoen** [SharePoint/sp-dev-docs#6724]
The link to the GetChanges API (https://msdn.microsoft.com/library/office/dn531433.aspx#bk_ListGetChanges) is listed as no longer maintained.  Although it might be valid, from the content on that page, it is difficult to understand how to interpret the response structure from GetChanges.  In particular, the ChangeType field appears to be an integer, and I cannot find a reference for how to map that integer to a meaningful change type.

I cannot find newer online documentation for the GetChanges API, nor can I find any documentation for the structured returned by GetChanges that is listed under:   "https://<site url>/_api/SP.ChangeItem",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6393d95-8c1d-2341-0cbd-282cd7016204
* Version Independent ID: b7506441-6d16-1689-91aa-e9f45a2bb9e0
* Content: [Overview of SharePoint webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks)
* Content Source: [docs/apis/webhooks/overview-sharepoint-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/webhooks/overview-sharepoint-webhooks.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Quick google search shows yields the values of hte enumeration:
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245903(v=office.15)
