### ISSUE TITLE
Flickering issue due to bootstrap CSS included in the SPFx application extension (top navigation menu)

### ISSUE THREAD

**Issue by priya28rajendran** [SharePoint/sp-dev-docs#6727]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Flickering issue due to bootstrap CSS included in the SPFx application extension (top navigation menu). The CSS applies very late and the DOM element loads first resulting in flickering.

We also identified that sometimes the custom bootstrap js (included through the same app extension) used in our application is not loaded initially on page load. After reload of the same page again it applies. 

We have tried the below approaches to resolve this issue. But the issue persists.
1. Using require method
2. Using SPComponentLoader
3. Using external section in config.json
4. Dynamic loading

## Environment details (if applicable)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Server 2019]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chromium Edge v87 (64-bit)]
- **Tooling**: [VS Code], SPFx Version: 1.4.0

**Comment by andrewconnell** [comment]
SPFx version? Please include that in the tooling question above...

**Comment by priya28rajendran** [comment]
Hi @andrewconnell , I have updated the SPFx version. 
In addition to the above we also did a check where only the top menu extension (from where the bootstrap JS is loading) is added in a page and there are no other custom SPFx webparts. In this scenario, every time bootstrap JS is loaded. So, this seems like the JS load is getting disturbed only when custom SPFx webpart and extension are both added in the same page. Please let us know if there is any alterative approach to acheive this.
