### ISSUE TITLE
SharePoint calendar view changed

### ISSUE THREAD

**Issue by momohamed770** [SharePoint/sp-dev-docs#6728]
Hi, i've created a new Teams application that embed a SharePoint site which is composed of a calendar in Agenda view but after encoding the page URL the view changed from Agenda to a list view is it possible to view the page in Teams same as SharePoint Calendar agenda view?

https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
You might have more luck with this question in the Tech Community forums...
