### ISSUE TITLE
SharePoint Online Column Formatting for Approval Status: uses language specific text?

### ISSUE THREAD

**Issue by m3ngi3** [SharePoint/sp-dev-docs#6731]
## Category

- [x] Question

## Question

Does the Content Approval Status column of SharePoint used in SharePoint Column Formatting --> only use the display value of the users profile language (and not the internal column value like 0 for Approved, 1 for Pending etc)??
Does this mean we need to change the Column Formatting for every specific language in the SharePoint Site?
Logical next question --> should we add a feature request to look at the 0-1-2-3 value for Column Formatting?

## Environment details (*development & target environment*)

- Edge on Chrome
- SharePoint Online
- Language settings of site: created in Dutch, English allowed language
- Column formatting
- Content Approval Status column shows English values for my account but Dutch in Filter Options for that same account (bug right? 🐞)
![image](https://user-images.githubusercontent.com/47530580/108388095-92a00000-720e-11eb-9034-d7b5f9de10ae.png)

Please forgive me @thechriskent but somehow I have a feeling that you may know more about this 😁

**Comment by m3ngi3** [comment]
To be able to use the internal code would be a great improvement @shagra-ms 🙏
Let me know if I can be of any help 💪

**Comment by shagra-ms** [comment]
The docs are now updated.
