### ISSUE TITLE
ACS with our SharePoint provider hosted app

### ISSUE THREAD

**Issue by iainlennox** [SharePoint/sp-dev-docs#6735]
[Enter feedback here]

We currently use ACS with our SharePoint provider hosted app, should we be concerned about this retirement and is there an alternative when using provider hosted apps?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90072657-ee15-df69-7ab5-c89b0d8f5cac
* Version Independent ID: 82db8c88-f099-9653-4413-33efb2a475e0
* Content: [Three authorization systems for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/three-authorization-systems-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/three-authorization-systems-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/three-authorization-systems-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Please see the "Important" note at the top of this article... it addresses your question.
