### ISSUE TITLE
Canot open SharePoint Online page within Teams App

### ISSUE THREAD

**Issue by aksridhar** [SharePoint/sp-dev-docs#6737]
I am following the same steps listed above with App studio and trying to open a homepage from communication site but coulkd never get it to work. It is the same error "App cannot load" both in desktop and web client. Not sure if anything has changed. I added all the required domains as well. Any help on this would be appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by BraunJonathan** [comment]
Can you check your manifest.json file and look at the validDomains and webApplicationInfo parts of it to check if you have all those domains filled ?
![image](https://user-images.githubusercontent.com/35366413/110597619-13ed1180-8181-11eb-82e8-d1bb2b7218b2.png)
 
 I got the same problem but this solved it...

**Comment by aksridhar** [comment]
Thanks @BraunJonathan for your suggestions. I did add all the valid domains and the only thing that I helped me fix this issue was to uncheck "Loading Indicator" and "Fullscreen Mode". I had a ticket open with Microsoft and looks like since App studio does not have any code, these two features are not supported and hence the page was not displayed. Once I unchecked, it started working.

**Comment by VesaJuvonen** [comment]
Thanks for following up on this @aksridhar - always great to know the root cause.
