### ISSUE TITLE
Batch Update for 700+ items failing

### ISSUE THREAD

**Issue by vivekmurli** [SharePoint/sp-dev-docs#6744]
- [x] Bug

Hello All,

I have written a code that gets all the URLs from the URL column in a document library , converts them into base64 and stores the resultant string in the respective column.

The code works fine on a few list items , However fails for 700+ items without any errors.

Checked the network trace and found the below 

1. Images being fetched

![image](https://user-images.githubusercontent.com/6428093/108710593-2e31b900-750c-11eb-9788-d938fbd2ac5e.png)

2. Only 100 List Items out of 700+ Updated as shown below

![image](https://user-images.githubusercontent.com/6428093/108710718-57eae000-750c-11eb-82ae-cb64fe52fd34.png)

3. Found the below entry in network tab , not sure what this means. The executions stops at this point and doesn't proceed further

![image](https://user-images.githubusercontent.com/6428093/108710933-98e2f480-750c-11eb-8416-45326f1e8fbf.png)

The end goal here is to convert all the URLs in the URL column to base64 and store it in the base64 column against every entry in the document library. 

Can anyone here suggest how this needs to be handled and if it is possible to skip the entries that cause errors at the time of execution and proceed further?

Below is the code

**Get all the list items**

```
function GetItemId() {
            //debugger;
            var deferred = $.Deferred();
            $.ajax({
                url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DBSDistributorList')/Items?$select=ID,BaseURL,DistributorLogo",
                method: "GET",
                type: 'GET',
                async: false,
                headers: {
                    "accept": "application/json;odata=verbose",
                    "content-Type": "application/json;odata=verbose"
                },
                success: function (result) {
                    deferred.resolve(result);
                    $.each(result.d.results, function (index, row) {
                        UpdateListItemUsingItemId(row["ID"], row["DistributorLogo"]["Url"]);

                    });


                },
                error: function (result) {
                    deferred.reject(result);
                }
            }); // Ajax list items

            return deferred.promise();

        };
```
**Update all the list Items**

```
function UpdateListItemUsingItemId(Id, dLogo) {
            //var deferred = $.Deferred();
            convertImgToBase64URL(dLogo, function (base64Img) {
                //console.log(base64Img);
                var _listItem = {
                    "__metadata": { 'type': 'SP.Data.DBSDistributorListItem' },

                    "BaseURL": base64Img
                };


                $.ajax({
                    url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DBSDistributorList')/Items(" + Id + ")",
                    method: 'POST',
                    contentType: "application/json;odata=verbose",
                    async: false,
                    data: JSON.stringify(_listItem),
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "X-RequestDigest": $("#__REQUESTDIGEST").val(),
                        "content-Type": "application/json;odata=verbose",
                        "X-Http-Method": "MERGE",
                        "If-Match": "*"
                    },
                    success: onSuccess,
                    error: onError
                    /*success: function (data) {
                        deferred.resolve(data);
                    },
                    error: function (err) {
                        deferred.reject(err);
                    }*/   
                });
                //return deferred.promise();		
	     });
	   
	    function onSuccess(data) {
           console.log('List Item Updated');
        }

        function onError(error) {
           console.log(JSON.stringify(error));
        }
	  
   };
```
**Conversion to base64**

```
function convertImgToBase64URL(url, callback, outputFormat) {
        
             var canvas = document.createElement("CANVAS");
             var ctx = canvas.getContext("2d");
             ctx.clearRect( 0 , 0 , canvas.width, canvas.height );
             ctx.fillStyle="#FFFFFF";
             ctx.fillRect(0 , 0 , canvas.width, canvas.height);

            var img = new Image();
            img.crossOrigin = 'Anonymous';
            img.onload = function () {
                //var canvas = document.createElement('CANVAS'),
                   // ctx = canvas.getContext('2d'), dataURL;
                canvas.height = img.height;
                canvas.width = img.width;
                ctx.drawImage(img, 0, 0);
                var dataURL = canvas.toDataURL(outputFormat);
                callback(dataURL);
                canvas = null;
            };
            img.src = url;
        }
```

Would be grateful if anyone could help me with this.

Also please let me know if any other details are required.

Thanks in advance.

**Comment by Jerry0527** [comment]
@vivekmurli , this is becuase of by default Rest API only return 100 items in single paging and have ___next property, if there will be other items in the request, modify the code snippet as below will work:

`        <script type="text/javascript">

           

            function UpdateListItemUsingItemId(Id, dLogo) {
                var deferred = $.Deferred();
                convertImgToBase64URL(dLogo, function (base64Img) {
                console.log(base64Img);
                    var _listItem = {
                "__metadata": {'type': 'SP.Data.DBSDistributorListItem' },

                        "BaseURL": base64Img
                    }


                    $.ajax({
                url: _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('DBSDistributorList')/Items(" + Id + ")",
                        method: 'POST',
                        async: false,
                        data: JSON.stringify(_listItem),
                        headers: {
                "accept": "application/json;odata=verbose",
                            "X-RequestDigest": $("#__REQUESTDIGEST").val(),
                            "content-Type": "application/json;odata=verbose",
                            "X-Http-Method": "MERGE",
                            "If-Match": "*"
                        },
                        success: function (data) {
                deferred.resolve(data);
                        },
                        error: function (err) {
                deferred.reject(err);
                        }
                    });
                    return deferred.promise();
                });
            };
            var url = _spPageContextInfo.webAbsoluteUrl + "/_api/web/lists/getbytitle('DBSDistributorList')/items?$select=ID,BaseURL,DistributorLogo&$top=1000";
            var response = response || [];  
            function GetItemId() {
                //debugger;
                var deferred = $.Deferred();
                
                $.ajax({
                    url: url,
                    method: "GET",
                    async: false,
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "content-Type": "application/json;odata=verbose"
                    },
                    success: function (result) {
                     response = response.concat(result.d.results);
                     $.each(response, function (index, row) {
                             UpdateListItemUsingItemId(row["ID"], row["DistributorLogo"]["Url"]);

                    });
                       if (result.d.__next) {
                            url = result.d.__next;
                            GetItemId();
                        }

                    },
                    error: function (result) {
                          deferred.reject(result);
                    }
                });

                return deferred.promise();

            };
            function convertImgToBase64URL(url, callback, outputFormat) {
                var img = new Image();
                img.crossOrigin = 'Anonymous';
                img.onload = function () {
                    var canvas = document.createElement('CANVAS'),
                        ctx = canvas.getContext('2d'), dataURL;
                    canvas.height = img.height;
                    canvas.width = img.width;
                    ctx.drawImage(img, 0, 0);
                    dataURL = canvas.toDataURL(outputFormat);
                    callback(dataURL);
                    canvas = null;
                };
                img.src = url;
            }
    </script>	

`
![Snipaste_2021-02-23_16-59-30](https://user-images.githubusercontent.com/28797671/108821426-8ba33400-75f8-11eb-8888-25cc0e45349e.png)

**Comment by Jerry0527** [comment]
I tested with 300 items, it's working as expected to update BaseURL field for all items

**Comment by vivekmurli** [comment]
@Jerry0527 Thank you again for all the help . Implemented recursion in code and everything seems to be in place :)
