### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by simplesalt** [SharePoint/sp-dev-docs#6745]
Can you please update the page to either list the new methods associated with Copy and Move or clarify if the old methods apply to the new methods as well?  This page is titled "Sharepoint Copy and Move" but the content only seems to describe the deprecated methods.  What are the methods and limitations for the new Copy and Move?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341380c-0c6c-e1fc-305a-c787ba317ddc
* Version Independent ID: 13df2b3e-301b-1d7d-bd74-8a8c35151135
* Content: [Microsoft 365 Copy and Move API (CreateCopyJobs)](https://docs.microsoft.com/en-us/sharepoint/dev/apis/spod-copy-move-api)
* Content Source: [docs/apis/spod-copy-move-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/spod-copy-move-api.md)
* Service: **sharepoint-online**
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by CallumCrowley** [comment]
@simplesalt I think you may be referring to the Copy functionality which is part of the Graph API. You can find documentation for that here:

[Copy a DriveItem](https://docs.microsoft.com/graph/api/driveitem-copy)
