### ISSUE TITLE
Graph SecurityEvents Permissions not generating a pending permission request.

### ISSUE THREAD

**Issue by jbatselos** [SharePoint/sp-dev-docs#6746]
I'm attempting to to create a webpart which pulls information from the SecurityEvent graph API. So package-solution.json I've added  
   
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "SecurityEvents.ReadWrite.All"
      }
    ]

and when the package is deployed I get this message, 
![image](https://user-images.githubusercontent.com/47537512/108718312-4b568f80-74ec-11eb-9a92-dc47cd1543c3.png)
and hit deploy.

Going by the docs I would assume that would automatically send a request to the API access tab in the admin center but that is not happening. Is there a way around this or am I missing something. ~Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c47bef-6351-3ab4-41e0-0abec261278f
* Version Independent ID: 332d0d0f-6d57-93d2-49b4-98a29e21eac2
* Content: [Consume the Microsoft Graph in the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)
* Content Source: [docs/spfx/use-aad-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aad-tutorial.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
You can grant permission requests via PowerShell or CSOM:
https://www.voitanos.io/blog/consider-avoiding-declarative-permissions-with-azure-ad-services-in-sharepoint-framework-projects/
