### ISSUE TITLE
Do SPO events/calendars support JSON view formatting?

### ISSUE THREAD

**Issue by dantshin** [SharePoint/sp-dev-docs#6749]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Do SPO events lists (*listBaseTemplate: 106*) support view formatting? When accessing the Format View settings (from a modern gallery view), the options presented include only **Apply formatting to**:
- Entire Row
- Title
- Attendees
- Category
- Resources

## Environment details (*development & target environment*)

- **Developer Environment**: Windows 10 
- **Target Environment**: SharePoint Online (western-europe)
- **Framework**: sp-list-formatting (JSON View Formatting)
- **Browser(s)**: Chromium Edge v88.0.705.74
- **Tooling**: VS Code
- **Additional details**: SPO Communications Site Collection (SITEPAGEPUBLISHING#0)

## What Should Happen
This is another list (custom list listBaseTemplate:100) in another Communications Site
![2021-02-23 00_41_10-Clipboard](https://user-images.githubusercontent.com/17646493/108784967-ca8da700-7570-11eb-81ef-9b0ea132b5dc.png)

## What Actually Happens
This is the Events/Calendar list (out-of-the box Events list for SPO Communications site)
![2021-02-23 00_42_32-Clipboard](https://user-images.githubusercontent.com/17646493/108784970-cb263d80-7570-11eb-851c-1c8ddaa8062e.png)

**Comment by bcameron1231** [comment]
Events/Calendars are classic lists, and while you can have a modern view on top of it, Calendars do not have Gallery Views / Tile Views etc.
