### ISSUE TITLE
nP.PowerShell instead of SharePointPnPPowerShellOnline ?

### ISSUE THREAD

**Issue by evlo** [SharePoint/sp-dev-docs#6751]
Aren't we now using PnP.PowerShell instead of SharePointPnPPowerShellOnline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b81c61e2-fab8-9bd4-3b25-a542b02324cd
* Version Independent ID: 69a0a7fd-b209-2f9a-8c3d-010783df2c4c
* Content: [PnP provisioning engine and the Core library](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-engine-and-the-core-library)
* Content Source: [docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
Hi @evlo ，

SharePointPnPPowerShellOnline in GitHub has been archived：

[https://github.com/pnp/PnP-PowerShell/releases](https://github.com/pnp/PnP-PowerShell/releases)

In the future, it's suggested to use PnP.PowerShell instead.
