### ISSUE TITLE
Copy documents with default item ID column between document libraries

### ISSUE THREAD

**Issue by vivekmurli** [SharePoint/sp-dev-docs#6755]
- [x] Question

Hello All,

We have a document library with with a few files which we are trying to replicate for the same reason , we want to copy all the files(with metadata) along with the **default Item ID column** to the new document library.

For Eg.

This is a source document library with the Default ID column , We want to copy the exact same ID column values to the Default ID column in the destination list.

![image](https://user-images.githubusercontent.com/6428093/108986584-34e63a80-768a-11eb-960d-b43f5ed213d3.png)

Read lot of articles online ,Unfortunately there are no articles pertaining to copying the default item ID column.

Would appreciate if anyone could let me know if this could be done using MS Flows

Thanks in advance

**Comment by Amos-MSFT** [comment]
Hi @vivekmurli,
The id values in the SharePoint list/library is automatically generated and we cannot change them. If you want to copy the ID values to the new library, you must keep the order of the copied files consistent with the order in which the files are uploaded to the source library. Copy according to the order of id from small to large, and no id discontinuity (some files are deleted).
Amos Wu
Microsoft SharePoint Community Support
