### ISSUE TITLE
Field customizer doesn't load in a list created in a modern team site (group)

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#676]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Test Field customizer in a list created in a modern team site (group)

#### Observed Behavior
The warning about loading debug manifests is displayed, but the field customizer isn't loading. No errors are reported in the console.

#### Steps to Reproduce
- Go to SharePoint Home (/_layouts/15/sharepoint.aspx)
- Create new site
- In the new site create a new list
- Append the query string parameters to debug a field extension in the list
- The warning about the debug manifests is displayed but the extension isn't loading

For comparison: if you create a new classic site through the SharePoint Admin page and create a new list there, debugging the field customizer works as expected.

**Comment by mmsharepoint** [comment]
I am facing the exact same behavior when "trying" to debug it together with a Display form. I know it is not supported (but REALLY DESIRED ;-) ) so far together with Edit+New form but "thought" it "might" be with a Display form as it is not "that far away" ;-)
https://mmsharepoint.wordpress.com/2017/06/25/sharepoint-framework-spfx-extensions-simple-field-customizer-to-show-a-traffic-light-status-rag/

**Comment by VesaJuvonen** [comment]
Has been fixed while back, so closing from issue list.
