### ISSUE TITLE
Adding UserAgent & X-ClientTag Headers to SharePoint API Calls

### ISSUE THREAD

**Issue by diveshgup** [SharePoint/sp-dev-docs#6761]
I have a SPFx webpart (react) that fetches data from SharePoint List and renders it in a nice visual. One of the requirements is to have: All SharePoint API calls must include UserAgent and X-ClientTag headers. Please help me add the same. Here is the code snippet:

const url: string = Text.format("{0}/_api/Lists/getByTitle('{1}')/items?$select=*&$orderby=Title", this._currentWebUrl, listName);
console.log(url);
     
        return this._spHttpClient.get(url, SPHttpClient.configurations.v1, httpClientOptions)
            .then((response: SPHttpClientResponse) => {
                return response.json()
                .then(data => {
                    console.log(data.value);
                    return data.value;
                });
            });

The value of UserAgent & X-ClientTag should be "NONISV|ABC|XYZ/1.0.0.0"

**Comment by bcameron1231** [comment]
You pass it in via your httpClientOptions;


```
import { SPHttpClient, ISPHttpClientOptions } from '@microsoft/sp-http';

 const opts : ISPHttpClientOptions  = {
    headers: {
      "UserAgent": "NONISV|ABC|XYZ/1.0.0.0",
      "X-ClientTag": "NONISV|ABC|XYZ/1.0.0.0"
    }    
  };
  
return this._spHttpClient.get(url, SPHttpClient.configurations.v1, opts)
        .then((response: SPHttpClientResponse) => {
            return response.json()
            .then(data => {
                console.log(data.value);
                return data.value;
            });
        });
```
