### ISSUE TITLE
_api/SPSiteManager/Create doesn't respect custom site designs

### ISSUE THREAD

**Issue by joshtransient** [SharePoint/sp-dev-docs#6762]
Documentation references the SiteDesignId property when creating a new site. This only works for OOB communication templates, and does not work for any custom site designs on team or communication sites. I know this isn't the right place to report this, but I'm not gonna file a UserVoice for a bug since UserVoices are only looked at when there are a high number of votes. Please at least add a note saying SiteDesignId doesn't work and escalate if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Duplicate of #4810 

Please review my comments on this post to get yourself sorted. 

We've flagged that as being reviewed, and waiting for Microsoft to confirm the API.

**Comment by joshtransient** [comment]
Closing since it's a dupe.
