### ISSUE TITLE
Windows Localhost workbench won't open due to invalid cert in gulp serve (ERR_CERT_AUTHORITY_INVALID)

### ISSUE THREAD

**Issue by synle** [SharePoint/sp-dev-docs#6763]
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

I cloned and tried to start gulp serve locally, but run into this issue opening the project on windows. It works perfectly fine on MAC, but on Windows, it shows `Your connection isn't private - NET::ERR_CERT_AUTHORITY_INVALID`,.

## Findings / Potential solution
I was able to solve the issue. Here is my findings.

- `gulp serve` or `gulp connect` uses a self signed certs that are checked into their own repo.
- The certs are located in this module `node_modules/gulp-connect/certs/server.crt` and `node_modules/gulp-connect/certs/server.key`
- My solution that makes it work is to copy over my own certs.
```
# make a backup
cp node_modules/gulp-connect/certs/server.crt node_modules/gulp-connect/certs/server.crt.bak
cp node_modules/gulp-connect/certs/server.key node_modules/gulp-connect/certs/server.key.bak

# copy over my cert
cp my-server.crt node_modules/gulp-connect/certs/server.crt
cp my-server.key node_modules/gulp-connect/certs/server.key
```

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**: node 8 or node 10 (tried both, still have the same issue)
- **Browser(s)**: EDGE 88.0.705.81 
- **Tooling**: VS Code | SPFx v1.10.0 
- **Additional details**: Below is my JSON deps
```
{
    "@fluentui/react": "7.158.1",
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/spfx-controls-react": "2.4.0",
    "@pnp/spfx-property-controls": "2.3.0",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "react-quill": "1.3.5"
  }
```

## Screenshot
![image](https://user-images.githubusercontent.com/3792401/109389046-7e6b9b00-78bf-11eb-937b-d1c4aa6ef63b.png)

**Comment by Jerry0527** [comment]
Yes, the error "Your connection isn't private - NET::ERR_CERT_AUTHORITY_INVALID" was due to the Chrome 58 update (any other browsers with Chromium core will also have this issue).

Create a self signed certificate will overcome the issue:

[Workbench not working after chrome update - certificate is broken ](https://github.com/pnp/sp-dev-fx-webparts/issues/210)

**Comment by synle** [comment]
@Jerry0527  do you know a way to pass in the path to certificates when executing the `gulp serve` command, right now my approach is a little hacky since I modify the certs stored inside the `gulp` package at `node_modules/gulp-connect/certs`

I worked with react (create-react-app) and they have a env var you can set to define the cert. Something like this
```
SSL_CRT_FILE=~/my-server.crt SSL_KEY_FILE=~/my-server.key react-scripts start
```

If there is not something like this, that's fine. I can override the certs that comes with the `gulp-connect`

**Comment by andrewconnell** [comment]
@synle You need to trust the dev cert... see: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate

@synle said:
> do you know a way to pass in the path to certificates...

No, not aware of a way to use your own cert.
