### ISSUE TITLE
Editing suggestions

### ISSUE THREAD

**Issue by Yuliadocs** [SharePoint/sp-dev-docs#6764]
[Hello, my editing suggestions are below. Like this might be easier for a reader to look for/scan the information].
You can choose an API set  to access the SharePoint platform from several sets of APIs. (You can choose what to do what from what). To determine which API set to use depends on the following factors:
- The type of application. The possibilities include, but are not limited to, the following categories, which are not mutually exclusive: 
   -  an SharePoint Add-in, 
   - a web part on a SharePoint page, 
   - a Silverlight application running on either a client computer or a client mobile device, 
   - an ASP.NET application exposed in SharePoint by an IFrame, 
   - JavaScript running in a SharePoint site page, 
   - a SharePoint application page, 
   - a Microsoft .NET Framework application running on a client computer, 
   - a Windows PowerShell script, and 
   - a timer job running on a SharePoint server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for the suggestions, but please feel free to contribute to the docs by submitting PR's with your suggested changes.
