### ISSUE TITLE
Editing suggestions for the Your existing skills paragraph

### ISSUE THREAD

**Issue by Yuliadocs** [SharePoint/sp-dev-docs#6766]
[Enter feedback here]
**Your programing models experience** (as you are talking about the experience in the programming models in the paragraph). To create applications in SharePoint, you do not need to learn a lot about SharePoint programming (straight to the point). You can jump right into SharePoint development if you already have experience in any of the following programming models:
-     JavaScript
-     ASP.NET
-     REST/OData
-     .NET Framework
-     Windows Phone
-     Silverlight
-     Windows PowerShell. (a dot is missing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for the suggestions, but please feel free to contribute to the docs by submitting PR's with your suggested changes.
