### ISSUE TITLE
Editing suggestions for The device on which the code runs paragraph

### ISSUE THREAD

**Issue by Yuliadocs** [SharePoint/sp-dev-docs#6767]
[Enter feedback here]
**The device on which the code runs**. The devices (instead of possibilities) can include a server in the SharePoint farm, an external server such as a server in the cloud, a client computer, and a mobile device. This topic gives ("provides" is used in this sentence in the contest of the SharePoint) an overview of the various API sets provided by SharePoint (delete "that are"). Figure 1 (Selected SharePoint extension types and SharePoint sets of APIs) shows which sets of APIs you (to make it more use oriented) can use to develop each of 13 common SharePoint-related applications. For many applications, you can choose from more than one API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for the suggestions, but please feel free to contribute to the docs by submitting PR's with your suggested changes.
