### ISSUE TITLE
Editing suggestions to The type of application paragraph

### ISSUE THREAD

**Issue by Yuliadocs** [SharePoint/sp-dev-docs#6768]
[Enter feedback here]
**The type of application**. The types of applications (instead of "possibilities") include, but are not limited to, the following categories which are not mutually exclusive : 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67454e4a-c0b9-58c6-2b4e-a55893db07e1
* Version Independent ID: ded00333-6d0c-471c-d306-0d270b8e7d00
* Content: [Choose the right API set in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint)
* Content Source: [docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/choose-the-right-api-set-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for the suggestions, but please feel free to contribute to the docs by submitting PR's with your suggested changes.
