### ISSUE TITLE
Editing Suggestions

### ISSUE THREAD

**Issue by Yuliadocs** [SharePoint/sp-dev-docs#6773]
[To use the REST capabilities (delete "that are" as there are a number of clauses) built into SharePoint, you can (added "can") construct a RESTful HTTP request by using the OData standard, which corresponds to the client object model API that (added "that") you want to use. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa0c9cd-d807-8d1b-1eb0-66373fa254b9
* Version Independent ID: 409a88a8-7ae9-afde-d66c-81529ad15669
* Content: [Get to know the SharePoint REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom)
* Content Source: [docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for the suggestions, but please feel free to contribute to the docs by submitting PR's with your suggested changes.
