### ISSUE TITLE
SPO Site rename job suspended

### ISSUE THREAD

**Issue by et15** [SharePoint/sp-dev-docs#6775]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

- SPO-Site rename failed (SharePoint Online M365)
- Site connected to M365 Group
- started rename process over browser-admin interface
- recognized issue cause Teams file tab connection broke

Some more informations from PowerShell

```
PS > Get-Spositerenamestate -State Suspended

CurrentSiteUrl                                   RenameID                             State     StateDescription
--------------                                   --------                             -----     ----------------
https://xxx.sharepoint.com/sites/xxx             ddxxxxxxxxxxxxxf                     Suspended
```

```
PS > Get-UnifiedGroup -Identity "Grp name" |fl

...
SharePointSiteUrl                      : https://xxx.sharepoint.com/sites/previous_name
SharePointDocumentsUrl                 : https://xxx.sharepoint.com/sites/previous_name/Freigegebene Dokumente
...
Name                                   : previous_name_5dxxxxxxxxxxxxxf
...
Identity                               : previous_name_5dxxxxxxxxxxxxxf
Id                                     : previous_name_5dxxxxxxxxxxxxxf
...
```

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: n/a
- **Browser(s)**: n/a
- **Tooling**: Power Shell, Microsoft.Online.SharePoint.PowerShell 16.0.20912.12000
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by andrewconnell** [comment]
This repo is for developer SharePoint topics... this PowerShell cmdlet is more in line for the TechCommunity forums which is more in line for the IT Pro topics like cmdlets.
