### ISSUE TITLE
SPFX JavaScript Event Listener Issue

### ISSUE THREAD

**Issue by shawnntt** [SharePoint/sp-dev-docs#6778]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I am currently using an SPFX extension, to add JavaScript to a Sharepoint Online page. I have successfully achieved this, however when adding event listeners on my Sharepoint Online page that are triggered when an <a> tag element is clicked, the results are not as expected. When clicking an <a> tag element not all <a> tag elements seem to trigger the event listener, this seems to be due to event.stopimmediatepropagation() being called in one/multiple of the event listeners that SharePoint includes.

Could you please advise on how I could work around this issue ? 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v
- **Browser(s)**: Chrome v88
- **Tooling**: SPFx v1.10.0

**Comment by bcameron1231** [comment]
Can you confirm, are you trying to attach event listeners to out of the box components in SharePoint.  If so, it's not really a supported scenario. Some of those components, as you mention, may be handling their own events and not allowing them to bubble up. There isn't much you can do in that scenario.

**Comment by JanVorster** [comment]
Hi @bcameron1231  - what would the "supported scenario" be if the business case is to track clicks on hyperlinks on a SharePoint site - so a usage analytics of sorts? I know there are products out there that does SharePoint analytics, but if you wanted to 'roll-your-own'... what guidance would you give about the best approach?
Thank you

**Comment by andrewconnell** [comment]
As @bcameron1231 said, it's not supported because Microsoft does not consider the page DOM to be an API.

**Comment by bcameron1231** [comment]
@JanVorster there technically is no supported scenario for this if you wanted to roll your own. I can't speak for other third party providers and whether or not their tracking is accurate (they may not be if they too can't collect all events).  Unfortunately, I wish I could be more help... but it's kind of the nature of the beast when you don't own the components in the page. GA and other providers would have the same issues.

**Comment by cwparsons** [comment]
Handle anchor click events on the capture phase, rather than the bubble phase.

```html
<script>
document.body.addEventListener('click', (e) => {
    const anchor = e.target.closest('a[href]');

    if (!anchor) {
        return;
    }

    // Track link, for example using Google Tag Manager
    window.dataLayer.push({
        event: 'Anchor click',
        href: anchor.href
    });
}, true);
</script>
```
