### ISSUE TITLE
Application customizers appear in "Lists" team tab after adding item to the list

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#6779]
When adding the "List" tab to a Team, it all looks correct until you add an item to the list, it then shows the SharePoint application customizer installed on the SharePoint site behind the team (see images below).

Before adding an item to the list:
![before](https://user-images.githubusercontent.com/17725046/109706850-5c10a080-7b91-11eb-85d4-0be366018bc4.jpg)

After adding a list item:
![after](https://user-images.githubusercontent.com/17725046/109706859-5e72fa80-7b91-11eb-9dd0-59ca0676bbb2.jpg)

## Steps to reproduce

1. Follow these steps to create a header application customizer: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
2. Deploy the application customizer to a SharePoint team site
3. In Teams,, add the "List" tab and create a new list.
4. Add an item to the list
5. View the application customizer in the tab (bug)

## Expected behavior

I would expect an application customizer to not show in the List tab when adding new items. This should only be viewable on a SharePoint page or SharePoint page tab.

## Environment details (*development & target environment*)

SPFx application customizer
Microsoft Teams web client and desktop app for windows 10

**Comment by AJIXuMuK** [comment]
@CloudDesignBox - sorry for the long delay.
Seems like the issue has been resolved.
Could you please double-check it on your end?

Thanks!

**Comment by CloudDesignBox** [comment]
I've just tested and it still seems to be an issue. Adding a new item to the list, adds the app customizer back in:
![image](https://user-images.githubusercontent.com/17725046/134950240-68af123d-cf35-43fd-ba15-be679649956a.png)

**Comment by AJIXuMuK** [comment]
I was able to repro it and fix.

The fix should appear in the next couple of weeks.

Leaving it open until then.

**Comment by AJIXuMuK** [comment]
This should be WW now
