### ISSUE TITLE
SPFx Webparts are not initialized or re-rendered when switching between pages having the same webparts, despite different properties

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#6786]
## Category

- [x] Bug

## Describe the bug

In the SharePoint navigation I added two links to clientside pages stored in the SitePages library. 
These pages carry an identical set of webparts (the same one webpart to be exact). 
The pages are configured differently (other webpart properties serialized). 

**Problem**: When switching between the pages, nothing happens. The set of webparts is identical, so no re-rendering occurs, and also no reinitialization. The content of the page therefore does not change, although it should, since the webpart renders differently based on the properties. 

## Steps to reproduce

Create two clientside pages (in the SitePages library) added to the navigation and put the same webpart on each (preferably with differently configured properties), then navigate and watch how the webpart's onInit or dispose or render does not get called and consequently no change happens - the content stays the same after navigation, while the content is different when reloading the page.

## Expected behavior

The webpart should re-render in ALL cases of navigation, EVEN IF the webpart properties were identical, since the content of the webpart does not necessarily declare all dependencies and therefore the application cannot decide when re-rendering is necessary. Indeed, a more consistent and correct way would be to dispose of the webpart an initialize a new instance, as the existing state does not necessarily have anything to do with the new location. 
The currently applied workaround is to have a timer running on the page which checks whether the location (URL of the page) was changed (without actual reload) and performs an actual reload. 

## Environment details (*development & target environment*)

- **MyDeveloper Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node 10 LTS
- **Browser(s)**: any (Edge Dev/Chromium)
- **Tooling**: VS Code, SPFx v1.10

**Comment by andrewconnell** [comment]
New issues include a template where you can fill out the environment & context details... please include that in your post as that's the first question people reviewing the issue will need answers to before they can investigate/review the issue.

**Comment by frevds** [comment]
Well, I thought I did. I clicked on New Issue and filled out that template (it was for a question) and removed the section about system environment (as it said I should do that if it doesn't apply, and it doesn't).

**Comment by frevds** [comment]
The context is very general - create two clientside pages (in the SitePages library) added to the navigation and put the same webpart on each, then navigate and watch how the webpart's onInit or dispose or render does _not_ get called.

**Comment by andrewconnell** [comment]
@frevds said:

> Well, I thought I did. I clicked on New Issue and filled out that template (it was for a question) and removed the section about system environment (as it said I should do that if it doesn't apply, and it doesn't).

There were questions about the environment (SP on-prem & which version, SP Online, SPFx, SPFx version, etc)... all of that matters.

**Comment by frevds** [comment]
Ah okay, I will update the main text.

**Comment by astanley86** [comment]
I experience this same behavior.  I have several Sharepoint Pages with one WebPart on each of them (SharePoint Online) and when you navigate from page 1 to page 2 back to page 1 - the screen is blank and it won't load.  If you press refresh on the browser then it loads properly.  I think my issue has to do with not properly destroying/cleaning up and it might be a memory leak?  Is this related to what you're describing @frevds ?

**Comment by frevds** [comment]
> Is this related to what you're describing @frevds ?

My problem is different - when navigating from page 1 to page 2, nothing happens (only the URL is being adjusted), the old webpart of page 1 stays there and is not being re-initialized and not re-rendered (and no dispose being called). I have to press F5 to refresh the page before seeing the new webpart with its different webpart properties. 
The reason is, that page 1 and page 2 have the very same set of webparts (if I add a second webpart on page 2, everything gets re-initialized fine). If the set of webparts is identical, SharePoint's navigation code thinks there is nothing to do (despite there being different webpart properties).

**Comment by AJIXuMuK** [comment]
Sorry for the long delay @frevds.
The issue seems similar to #5227.

We made some fixes related to navigation and not changing content of web parts.

Could you please check on your end if the issue is resolved?

Thanks!

**Comment by frevds** [comment]
@AJIXuMuK No change - neither dispose, nor onInit or constructor are called when I navigate between Pages in the Navigation having the same webpart on them (but with different webpart properties). I have a workaround in place for this case, which checks the URL in intervals (the URL is adjusted fine) and reinitializes the webpart explicitly. Not sure if the changes should be online already in my tenant and old clientside page? I didn't change and didn't test a new setup, merely my existing solution.

**Comment by AJIXuMuK** [comment]
Thanks @frevds for checking.

Could you please do few things as I'm unable to repro it on a general prod tenant?
1. Could you share your web part with us?
2. What web parts do you have on the pages?
3. Could you try to create new pages and check if the issue is presented there?

Thanks!

**Comment by frevds** [comment]
@AJIXuMuK Interesting. I created new clientside pages and the issue does _not_ occur there, the webpart is disposed and reconstructed properly when navigating. The pages we're using are quite old. I have attached them for you. Their only difference is a value for a webpart property (Line 11 Col 1564). The pages are clones. While when you create pages in the UI subtle changes appear, these are truely identical except for the property, and that might cause the refresh issue (or maybe some IDs should be different). They use a full app-page layout with nothing but one webpart on them. Maybe you can tell me what's wrong with these and how we can adjust them so the navigation will work as intended.
[Pages.zip](https://github.com/SharePoint/sp-dev-docs/files/7747789/Pages.zip)

**Comment by frevds** [comment]
@AJIXuMuK I also just discovered that sometimes the onInit of a command-set list extension is not being called when navigating through links to regular lists. The circumstances are not clear. It seems to have to do with time, works later but not when entering fresh, but not consistently reproducible, more of a race condition. This is a rather big issue, if a list extension does not get activated when navigating to a list (one for which I'll have to find a hacky workaround now..). There is another ticket for that, just letting you know that this problem also still persists.

**Comment by AJIXuMuK** [comment]
@frevds - how exactly did you create these pages?
The thing is you pages don't look like a single web part pages. They have settings for multiple sections, and both `CanvasContent1` and `LayoutWebpartsContent` properties.
I would recommend to recreate the pages.

Regarding your comment about command set: `onInit` is called when the command set is initialized. When you're navigating between pages, the command set can be cached. In that case it will not re-initialized.

**Comment by frevds** [comment]
@AJIXuMuK Alright, I will do that (recreate the pages). Regarding: onInit it is my understanding that if the same extension is activated for two different lists, there will be two calls to onInit, with different contexts. That is what happens generally, but not always. Sometimes I get only one onInit and can navigate to another list where I don't get the call. Pressing F5 and doing the same thing I suddenly get two calls. And that keeps working, until I reopen the browser (even then does not happen predicably). There are no console errors, just that onInit is not being called again after navigating (but it is being called for the first list). This issue might even be related to webparts not refreshing.

**Comment by frevds** [comment]
@AJIXuMuK At the time these pages were created (in 2018?) there was no such thing as a SingleWebPart-Page yet, if I remember correctly that came only later (CSS is used to adjust the rest later). 
I think that used to be some Home page layout first and was later adjusted manually to use the SingleWebPartAppPage layout (lost to history how exactly this happened). Anyhow, probably best to recreate them (just updating these pages for hundreds of customer sites won't be fun).

**Comment by frevds** [comment]
@AJIXuMuK I created new Single Part App Pages (the way I'm supposed to do it via New Page > App > WebPart) and compared against the old ones. I cannot find real differences, BUT - I think you're having problems if the **id** or **instanceId** attributes are the same in multiple pages. That might be the reason why nothing refreshes. 

Here is a diff of the raw ASPX (basically just no LayoutWebpartsContent any more): 
![image](https://user-images.githubusercontent.com/5341447/146989298-9c1c7c9e-c5a6-40fa-9272-6187ac61b37f.png)

Here is a diff of the CanvasContent1 (basically the same): 
![image](https://user-images.githubusercontent.com/5341447/146989515-604d8eda-d5c8-4f2a-a704-58920efaed19.png)

And here is the diff of the two JSON chunks (basically the same again, but the issue might be reusing the id/instanceId when cloning the page): 
![image](https://user-images.githubusercontent.com/5341447/146989733-dafdf321-3514-4021-b1e6-c737729babfe.png)

**Comment by AJIXuMuK** [comment]
@frevds  - Yes, the same identifiers could also lead to incorrect behavior as the engine could just check the current rendered component.

You can probably start with changing instanceId and see if it helps.
But it's still, unfortunately, a manual (or automated) work that needs to be performed.

There is no issue on our side to be fixed from what I can see.

I will leave it open for now if you want to share your further investigation with others.

**Comment by frevds** [comment]
@AJIXuMuK Yes, I tested this theory and the problem is now solved (!) - onInit is being called again upon navigating to links of different site pages. Thanks for pointing out the way. 
This solves this issue (for webparts - the onInit issue for list commandset extensions when navigating different lists is a different matter). 
You could close this ticket here (others with the same problem should still find it in the history I guess).
