### ISSUE TITLE
Created and Modified fields to Form

### ISSUE THREAD

**Issue by dan00500** [SharePoint/sp-dev-docs#6787]
There's no mention of whether one can use the automatic fields to the body.  Or, maybe I missed those details?

- **Created**
- **Created By**
- **Modified**
- **Modified By**  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration?source=docs)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Unfortunately, we cannot use them. Only fields that are visible are able to applied to body format... and at this time we can't add those hidden fields to the form.

**Comment by VesaJuvonen** [comment]
Question answered by @bcameron1231, so closing this one for now.
