### ISSUE TITLE
Get-PnPProvisioningTemplate has been renamed to Get-PnPSiteTemplate

### ISSUE THREAD

**Issue by spg-iwilson** [SharePoint/sp-dev-docs#6788]
The command Get-PnPProvisioningTemplate has been renamed to Get-PnPSiteTemplate. 
https://pnp.github.io/powershell/articles/upgrading.html 

I was getting the following error when trying to use the old command after I installed PnP.PowerShell

The term 'Get-PnPProvisioningTemplate' is not recognized as the name of a cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b8037-a569-40c1-86ad-cbf56c9c4b4b
* Version Independent ID: c9dfddaa-7f54-7194-db9e-cf5f6370cbb5
* Content: [Introducing the PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
The docs have been updated and are pending publication to the live site.
