### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by Slogmeister** [SharePoint/sp-dev-docs#6791]
You're missing the "Add" method in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e706745a-56b7-ca75-d246-4cd6945d2509
* Version Independent ID: 74ec3639-b323-8ac9-e167-c479bf7e46a9
* Content: [SPFolder Class (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spfolder?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPFolder.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPFolder.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by Jerry0527** [comment]
There is no Add method in SPFolder class, if you want to add SPFolder in specific library, use SPFolderCollection.Add like this:
```
 using (SPSite site=new SPSite("http://sp/sites/dev/"))

            {
                SPWeb web = site.OpenWeb();
                SPFolderCollection collFolders = web.GetFolder("Shared Documents").SubFolders;
                collFolders.Add("TestFolderForAdd");
            }
```

![Snipaste_2021-03-09_10-01-52](https://user-images.githubusercontent.com/28797671/110407305-9660cd00-80be-11eb-9f3e-3fd54daa2c32.png)

**Jerry Zy
Microsoft SharePoint Community Support**
