### ISSUE TITLE
Pnp people picker control

### ISSUE THREAD

**Issue by RahiniRadha** [SharePoint/sp-dev-docs#6792]
Pnp People picker

- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

We are using Pnp People picker control in one of our spfx webpart. Is there any equivalent option for "Check names" or "Ctrl +K" available for Pnp people picker like SharePoint classic people picker?

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Server 2019]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chromium Edge v87 (64-bit)]
- **Tooling**: [VS Code], SPFx Version: 1.4.0
- **Additional details**: Pnp version 1.20.0

**Comment by Amos-MSFT** [comment]
Hi @RahiniRadha ,
According to my experience and the documentation, pnp people picker control will provide possible suggestions based on the value entered, only the correct user name will be converted into a people card and displayed on the control, and the wrong user name can only be displayed on the control in text.
Amos Wu
Microsoft SharePoint Community Support

**Comment by andrewconnell** [comment]
If you're asking about this:
https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/

Then you should post this question to that project's issue list, as this is for general SharePoint development topics.
