### ISSUE TITLE
SPFx app does not work on Modern page

### ISSUE THREAD

**Issue by janeecko** [SharePoint/sp-dev-docs#6793]
## Category

- [x] Bug

## Describe the bug
I noticed that my app does not work when it is deployed to modern page. On classic page app works. 
I was investigating a bit and I generated new SPFx (hello world sample :) and it does not work on modern page too

Error details: Error: Error initializing application. Error: TypeError: Cannot read property 'Content' of undefined

I tried way with gulp serve running, also I tried to --ship and deploy files into app catalog with sppkg file. 
Nothing is working on modern site, it works on classic site properly. 

## Environment details (*development & target environment*)

- **Your Developer Environment**: windows10
- **Target Environment**: sharepoint online
- **Framework**: node 10.20.1,  @microsoft/generator-sharepoint@1.11.0
- **Browser(s) : chrome Version 87.0.4280.66 (Official Build) (64-bit)
- **Tooling**: vsCode 1.38.1, spfx 1.11.0 (I upgraded today, it did not work on previous version too)

**Comment by bcameron1231** [comment]
Are you able to share your code with us in a repo to look at?

**Comment by janeecko** [comment]
I would, but basically there is not code. I just generated app with yeoman using yo @microsoft/sharepoint and that is what I deployed to app catalog and it is working only in classical page.

**Comment by janeecko** [comment]
classic page
![image](https://user-images.githubusercontent.com/31740215/110351706-61f4fe80-8035-11eb-8864-3ea8ef9584d6.png)

modern page
![image](https://user-images.githubusercontent.com/31740215/110351801-7c2edc80-8035-11eb-89df-5b650ede3e24.png)

**Comment by andrewconnell** [comment]
Unfortunately, we'd need to see what you're doing to repro this as this is pretty basic functionality that doesn't appear to be broken.
