### ISSUE TITLE
Access denied on ClientSideAssets for some users (especially new users)

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/sp-dev-docs#6797]
## Category

- [X] Question
## Question

I ran today into an issu i never had encountered before : some of my users do not have access to the js files of my SPFX webparts/extensions whereas some other users have access...

I tried creating a new user and he has no access to the files either...
I do NOT use CDS so users access directly to the appcatalog.
![image](https://user-images.githubusercontent.com/35366413/110488141-81039700-80ee-11eb-897e-aa1952fed6ac.png)

Has anyone had this issue yet?
this is my Group0 of my appCatalog
![image](https://user-images.githubusercontent.com/35366413/110488575-e5bef180-80ee-11eb-9184-7b4e7802ec5c.png)

I do not manage to understand why some users have access to the js files et some don't...

## Environment details (*development & target environment*)
- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePointOnline
- **Browser(s)**:Chrome last version
- **Tooling**: VSCode mainly

**Comment by michaelhan-1** [comment]
You could try to check the permission of the Client Side Assets library of your appCatalog where host these js files. As far as I know, the Client Side Assets library has unique permissions.

![image](https://user-images.githubusercontent.com/69185043/110593467-90e6ae00-81b6-11eb-82a2-1b2aa9fb8607.png)
**Michael Han
Microsoft SharePoint Community Support**

**Comment by BraunJonathan** [comment]
First of all, thanks Michael for you answer, it's always nice to find some help around here !

Yes it indeed tells me that the library has unique permissions but i can't manage to display them...
When i use the check permissions button, i got the same results for my user who can access to the js files end the other one who can't...
![image](https://user-images.githubusercontent.com/35366413/110596133-3a11b200-817f-11eb-81b3-1466c976448b.png)
![image](https://user-images.githubusercontent.com/35366413/110596265-5d3c6180-817f-11eb-976c-c92b7caffa6e.png)
Aurélie has no problem accessing the js files and therefore displaying the webparts and extensions whereas Juliette cannot display any webparts...

When i try to access the library or even the webpart folder (something like https://MY-TENANT.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b) i got an access denied for both accounts but if i add the js file (like https://MY-TENANT.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-parts-controlstrings_fr-fr_9b5c2bbb8a739c704c1b1087c90d431c.js) Aurélie can download it and Juliette cannot...

I know that if i activate the public CDN my problem will be gone but i cannot understand the difference between my 2 users and that bothers me a lot as i'm beggining to have quite a good knowledge on Sharepoint and i can't figure out what's happening here...

**Comment by BraunJonathan** [comment]
I tried to reproduce the issue on our production tenant even though on this particulat tenant we have the Public cdn enabled...
It seems that with public cdn enabled, standard users do not have direct access to the appcatalog js files... 

So i can only imagine that there is something which grants access to those js files when cdn is not enabled and maybe that thing is broken on some of my developper tenants...
