### ISSUE TITLE
Get/Apply-PnPProvisioningTemplate vs Get/Invoke-PnPSiteTemplate

### ISSUE THREAD

**Issue by franckcdev** [SharePoint/sp-dev-docs#6799]
The PoSH commands **Get-PnPProvisioningTemplate** and **Apply-PnPProvisioningTemplate** are part of the deprecated **PnP-PowerShell** module. 
These commands have been renamed in the new **PnP.PowerShell** module:
Get-PnPProvisioningTemplate --> Get-PnPSiteTemplate
Get-PnPProvisioningTemplate --> Invoke-PnPSiteTemplate
Apply-PnPTenantTemplate --> Invoke-PnPTenantTemplate

Please update the documentation to indicate the different commands according the used PnP PowerShell version.

Thanks

Franck
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b8037-a569-40c1-86ad-cbf56c9c4b4b
* Version Independent ID: c9dfddaa-7f54-7194-db9e-cf5f6370cbb5
* Content: [Introducing the PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Should be already set to be fixed with PR #6765
