### ISSUE TITLE
Pnp People picker suggestion showing irrelevant names

### ISSUE THREAD

**Issue by RahiniRadha** [SharePoint/sp-dev-docs#6806]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
- [ ] Checked items have no spaces between the <kbd>[</kbd><kbd>]</kbd> (*delete this line*)

## Question

We used a pnp people picker control in a webpart. It is working fine in dev and SIT environment. But in UAT when we type a name, it is showing suggestion list with no matching values for typed text in picker. Also in UAT, suggestions always showing same set of results irrespective of desired user.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Server 2019]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chromium Edge v87 (64 bit)]
- **Tooling**: [VS Code], SPFx Version: 1.4.0
- **Additional details**: pnp version: 1.20.0

## Submission guidelines

**Comment by andrewconnell** [comment]
Please post this question to the PnP Controls Project... thanks!
https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/
