### ISSUE TITLE
SPFX Application customizer extension does not run on partial pages updates

### ISSUE THREAD

**Issue by johnGu123** [SharePoint/sp-dev-docs#6809]
## Category

- [x] Bug

## Describe the bug

SPFX Application customizer extension does not run on partial pages updates

## Steps to reproduce

I want to inject some CSS to my SharePoint page, so I follow those steps @ https://tahoeninjas.blog/2018/05/08/inject-custom-css-on-sharepoint-modern-pages-using-spfx-extensions/ to create SPFX Application customizer extension, where i did the following:-

```
md app-extension
cd app-extension
yo @microsoft/sharepoint

What is your solution name?: app-extension
Which baseline packages do you want to target for your component(s)? SharePoint Online only (latest)
Which type of client-side component to create?: Extension
What is your Application Customizer name? HelloWorld
What is your Application Customizer description? HelloWorld description
```

then i added the following code inside the .ts:-

```
import { override } from '@microsoft/decorators';
import { Log } from '@microsoft/sp-core-library';
import {
  BaseApplicationCustomizer
} from '@microsoft/sp-application-base';
import { Dialog } from '@microsoft/sp-dialog';

import * as strings from 'HelloWorldApplicationCustomizerStrings';

const LOG_SOURCE: string = 'HelloWorldApplicationCustomizer';

/**
 * If your command set uses the ClientSideComponentProperties JSON input,
 * it will be deserialized into the BaseExtension.properties object.
 * You can define an interface to describe it.
 */
export interface IHelloWorldApplicationCustomizerProperties {
  // This is an example; replace with your own property
  cssurl: string;
  scripturl: string;
}

/** A Custom Action which can be run during execution of a Client Side Application */
export default class HelloWorldApplicationCustomizer
  extends BaseApplicationCustomizer<IHelloWorldApplicationCustomizerProperties> {

    @override

    public onInit(): Promise<void> {
      Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);
  
      const cssUrl: string = this.properties.cssurl;
      const scriptUrl: string = this.properties.scripturl;

      const url = window.location.href;
      if (cssUrl && url.toLowerCase()=="https://t****.sharepoint.com/sites/customeroperations/sitepages/dashboard.aspx") {
          // inject the style sheet
          const head: any = document.getElementsByTagName("head")[0] || document.documentElement;
          let customStyle: HTMLLinkElement = document.createElement("link");
          customStyle.href = cssUrl;
          customStyle.rel = "stylesheet";
          customStyle.type = "text/css";

          const head2: any = document.getElementsByTagName("head")[0] || document.documentElement;
          
          head.insertAdjacentElement("beforeEnd", customStyle);
          head2.insertAdjacentHTML("beforeEnd", '<META HTTP-EQUIV="refresh" CONTENT="300">');

          

      }
      
      return Promise.resolve();
    }
}
```

So as shown in the above code I am specifying to only attach the custom css if the window.location.href = the url of the home page which is `https://t****.sharepoint.com/sites/customeroperations/sitepages/dashboard.aspx` in our case. now the above is working on most cases but is failing on the following cases:-

1) let say i am inside the Pages library >> then I click on the "Home" link to open the home page>> this will do a partial update to the page and will load the home page content without causing the whole page to load >> where in this cases the SPFX extension will not run.

2) second case>> if I am inside the home page and the SPFX has loaded the custom css file correctly >>then i click on a page inside the news web part >> this will open the news page without refreshing the page >> which will cause the SPFX to run on the news page (which is not the home page)...

so my question is how I can force the SPFX extension to run on partial updates to check the page url, to avoid the above 2 issues?

Thanks in advance for any help.

Regards

**Comment by Amos-MSFT** [comment]
As a workaround, we can add `navigatedEvent `listener inside `onInit `function which will re-render our component every time we navigate to another page.
` this.context.application.navigatedEvent.add(this, () => {})`
Test code for your reference:
![carbon (1)](https://user-images.githubusercontent.com/56672877/110922054-3423f880-835a-11eb-8e51-35712d34887e.png)
Amos Wu
Microsoft SharePoint Community Support

**Comment by johnGu123** [comment]
> 
> 
> As a workaround, we can add `navigatedEvent `listener inside `onInit `function which will re-render our component every time we navigate to another page.
> ` this.context.application.navigatedEvent.add(this, () => {})`
> Test code for your reference:
> ![carbon (1)](https://user-images.githubusercontent.com/56672877/110922054-3423f880-835a-11eb-8e51-35712d34887e.png)
> References:
> https://nanddeepnachanblogs.com/posts/2020-04-10-handle-navigation-in-sharepoint-framework-application-customizer/
> Amos Wu
> Microsoft SharePoint Community Support

thanks for the code. where it fixed most of the navigation issues i were facing. But still i am facing this issue >> if inside the home page's News web-part >> i click on "News Post", as follow:-

![newspois](https://user-images.githubusercontent.com/43375450/110981575-39377680-835f-11eb-8c7d-a84da4f07768.png)

the new page will open and the custom CSS will be applied to it.. not sure why? although the new news page will have a url different than the home page url.. can you advice on this please?
Thanks

**Comment by johnGu123** [comment]
any advice on this ?thanks

**Comment by Amos-MSFT** [comment]
The page created by the new post looks like an asynchronous request, the entire page is not refreshed, and the navigation bar has not changed, so `this.context.application.navigatedEvent.add(this, () => {})` does not take effect.
You could take a reference to this blog:[Handling page creation events in your SPFx application customizer](https://www.eliostruyf.com/handling-page-creation-events-spfx-application-customizer/
Amos Wu
Microsoft SharePoint Community Support)

**Comment by johnGu123** [comment]
> 
> 
> The page created by the new post looks like an asynchronous request, the entire page is not refreshed, and the navigation bar has not changed, so `this.context.application.navigatedEvent.add(this, () => {})` does not take effect.
> You could take a reference to this blog:[Handling page creation events in your SPFx application customizer](https://www.eliostruyf.com/handling-page-creation-events-spfx-application-customizer/
> Amos Wu
> Microsoft SharePoint Community Support)

yes i saw the link, but i am nto sure how i need to combine the code inside the link with my code? as the 2 use different approaches..

**Comment by AJIXuMuK** [comment]
Hello @johnGu123 - sorry for the long delay.
In the last few months me made multiple fixes and improvements related to navigation and `navigatedEvent`.
Currently it should work with in-place navigation correctly.

Could you please check if your issue is resolved?

Thanks!
