### ISSUE TITLE
Edit first paragraph to remove ACS reference

### ISSUE THREAD

**Issue by sujayvsarma** [SharePoint/sp-dev-docs#6812]
The first paragraph ends as:
```
 The authorization server in this scenario is Microsoft Azure Access Control Service (ACS).
```

Then there is a huge blue box under that, talking about retirement of ACS in 2018 (more than 2 years ago). 

Please edit the first paragraph and other references to the (now retired ?) ACS and provide updated information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0dae771-c1ca-b887-8568-ce559962ae0b
* Version Independent ID: 24eb700d-4921-6a17-0c7f-4986e7adefa5
* Content: [Context Token OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Continue reading the blue box... it states that even though retired, it doesn't impact add-ins.

**Comment by sujayvsarma** [comment]
I read that, and that confused me more. Hence this ticket. Does that clause in the parans mean:

1. SharePoint Add-ins never used them, now that ACS is retired you are not impacted
2. Though it is retired, SharePoint Addins still need to use ACS

#1 is clearly not the case because the entire article is about using it with SPS Addins. Which leaves #2, which asks that developers use the ACS (retired now!) service to perform AuthZ. Is it one day going to stop working for this scenario too? Is there some alternate service/API people should switch over to? 

When you read it as an existing SPS Add-in developer (i.e., one who has a few addins in play) with no plans to change or upgrade their code, you would read "okay, no impact to me" and move on. But if you're someone writing a new set of add-ins or working on upgrade plans/etc, then this creates more questions. 

The text is not clear to me.

**Comment by andrewconnell** [comment]
I think you're reading into this a bit more than necessary :). This doc simply explains show things work under the covers. Originally, add-ins use ACS... but since then Azure retired ACS, but not the underlying infrastructure that implemented it.

As such, there's no impact to SharePoint add-ins... everything in the doc still applies... the extra callout about ACS being retired was simply added to address all the questions MSFT was receiving about "now that ACS is being retired, how will this impact add-ins". 

The blue box is saying "it doesn't".
