### ISSUE TITLE
Prerequisites section - text is confusing

### ISSUE THREAD

**Issue by sujayvsarma** [SharePoint/sp-dev-docs#6813]
This text at the start of the Prerequisites section is confusing. Please re-word:

```
If the SharePoint Add-in is to be installed to an on-premises SharePoint farm, these setup requirements don't apply if it is only installed to SharePoint Online
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0dae771-c1ca-b887-8568-ce559962ae0b
* Version Independent ID: 24eb700d-4921-6a17-0c7f-4986e7adefa5
* Content: [Context Token OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
What's unclear? The sentence is clear that if you only plan to install the add-in on-prem, you don't need to do the SPO steps.

**Comment by sujayvsarma** [comment]
> What's unclear? The sentence is clear that if you only plan to install the add-in on-prem, you don't need to do the SPO steps.

If that is the case, the statement should read:

```
The below steps only apply if you plan to install the add-in to an on-prem installation of SharePoint. The steps do not apply to SharePoint Online.
```

The grammar of the original statement is confusing to someone who is not a native English-speaker/reader. It has very complicated grammar even for me :)
