### ISSUE TITLE
Why is getting information from Microsoft so difficult

### ISSUE THREAD

**Issue by julian-hansen** [SharePoint/sp-dev-docs#6814]
We have been trying for over a week to find a way to submit documents to a SharePoint online site using REST. We have an externally hosted application to which documents are uploaded and we need to get these into SharePoint. This, I would have thought would be a common and simple task, Microsoft has turned it into a nightmare.

After trying a bunch of different suggestions found in different locations - most of which seem to have been deprecated we eventually found this page - which seems to indicate that what we want to do is possible. We can construct the URL's but we are having great difficulty finding how one gets an access token. Mention is made to of it in many locations but nowhere can we find a simple set of instructions on how to obtain this. It is mentioned on this page again but no references to a step by step.

What would be really useful would be documentation that deals with common tasks. That did not start with the history of the universe but stated in steps what is required to perform that task.
For instance
How to upload a document using REST
1. Obtain your access token by following these steps
    a)....
    b)....
2. Create a URL by taking your Site url (your site url can be found / located / derived like this ....) and adding these parameters ...
   Example: http://....
3. Add your access token to the header as follows
    Authorization: bearer:{access_token} [replacing {access_token} with the value you created in 1)
4. Put your document data into the body of the request
5. Post your results to the URL created in 2

If all went well you should receive this back
...
If there was an error you will receive this
...
Possible causes of error are.

What we developers want is quick and easy step by steps that get us to where we want to go. What we don't want is to have to read reams of unnecessary background information, wading through multiple pages and still end up with no clear picture of what is required.

A REST request is a very very very simple operation - it should not have to be this difficult to get it to work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa0c9cd-d807-8d1b-1eb0-66373fa254b9
* Version Independent ID: 409a88a8-7ae9-afde-d66c-81529ad15669
* Content: [Get to know the SharePoint REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom)
* Content Source: [docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Have you seen:
- https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest
- https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery

**Comment by julian-hansen** [comment]
Yes - I did - several times. The problem is that the document gives us some of what we need but not everything. In the first one the word accessToken is mentioned 18 times but nowhere is there a reference as to how to obtain it. We can guess it is some OAuth session token or a base64 encoded combination of client id and secret - but the details are important and without that information we cannot proceed. Of course we can look for it - which I have done - and do some guess work - my point is why is that necessary. Why not have the details all in one place in a concise easy to follow manner so that we don't have to search for it.

For instance if we go to this page https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom one would expect that access and authentication would be covered there - but it is not. The document does state under
**Prerequisites**
**This topic assumes you have a basic familiarity with REST and how to construct REST requests.**
Which suggests that if you have basic REST knowledge the rest should follow. 
At this point we have what appears to be a working solution. However we are not confident in the long term viability of this as some of the documentation we came across suggests deprecation of various functions - which may or may not render this unusable in the future.

What would be really helpful is a document (adequately linked to) that lays out the process from start to finish in step by step form of how to upload a document to SharePoint from an external location (not hosted in SharePoint or an add in etc).

**Comment by andrewconnell** [comment]
I don't debate that the REST docs could be improved... it's baggage from a product that's evolved over 20 years from an on-prem product to one that's primarily hosted in the cloud. During this time, things have changed and evolved. For the SPO product, there's been a push to have all M365 APIs be served up primarily via Microsoft Graph which is a proxy to many other APIs including SharePoint.

What would help for your situation is some context. What environment are you working with (SPO/SP on-prem/version), what context on your scenario (connecting from a client-side app in SharePoint, connecting from a remote service), tech you're using (one of the former/current SharePoint extensibility models, .NET code running in a X app), etc.

Additionally, context around your background... where are you coming from (non-SP developer, etc) helps to know the audience. This helps in improving the docs.

WRT the access token comment, the modern SPO REST APIs are protected with OAuth2, so the access token is obtained from an Azure AD app.

So... some context would help to point you in the right direction. This is also helpful in identifying "what can be improved" in the docs as they sit today.

**Comment by julian-hansen** [comment]
Thanks Andrew,
Context: I am a non SPO-developer - although I have bumped into SO from time to time. I have 28 years of development experience from assembler through C++ to most of the Web (full stack) development environments. A project I am working on for a client involves their clients uploading documents to their website (hosted in a Linux environment) and they want those documents to be uploaded to specific folders in their SPO folders. The manner in which this will be done is via CRON initiated script (probably written in PHP - given their server setup) that queries their DB and submits the latest documents uploaded since the last run to the SPO environment.

Regarding the access token - I understand it being OAuth - that part is not in question - however it has been very difficult to find where / how that token is obtained. I would expect it is a combination of a client ID / secret - but where those are obtained is also not clear. You mention that they are obtained from an Azure AD app - which is interesting but does not help if you don't know that is the case and if there are no pointers to that information.

As I said - REST interactions are relatively straight forward - you need an Endpoint, a HTTP method, URL parameters, body parameters and headers - the rest is about calling a URL. For us developers to make this work we need to know what those various elements are - and knowing 90% of them is not going to help us.

For instance one resource I came across (a post in response to my question on a forum) pointed me here https://{company-site}.sharepoint.com/_layouts/15/appregnew.aspx - just a form without a frame or any kind of reference on how one gets there either than a direct URL which seems to give you the means to setup an App - but with no indication if this is the right place to get the information needed for a REST call.

I hear what you say about 20 years of development - which is understandable - however this does not help developers in rapidly upskilling to accomplish tasks that should be relatively simple to do - like REST.

**Comment by BassemNKhalil** [comment]
Hope this one helps - [Microsoft learning - application permissions](https://docs.microsoft.com/en-us/learn/modules/identity-permissions-consent/7-exercise-application-permissions-consent)

**Comment by julian-hansen** [comment]
Thank you Bassem - I will read through that. Question: is an Azure application credentials usable from anywhere i.e. outside of the Azure environment?

**Comment by BassemNKhalil** [comment]
Pretty much, yes - the idea is that you’d create an application in Azure AD then assign it permissions to various services as needed (SharePoint, AAD or Power Automate to name a few. From your code, you’d connect to these services using the app.

**Comment by julian-hansen** [comment]
Thank you, I will have a look. However the original motivation for this post was around the difficulty in finding the information to perform a REST call. I do not doubt that this information is out there in one form or another - it is just not intuitive or easy to find. My suggestion is that simple how-to's are created that give a summary of the complete process end to end such that one new to SP/SPO wanting to do REST interactions has something that can get them moving in a relatively short space of time.

**Comment by andrewconnell** [comment]
Understood... thanks for the additional context @julian-hansen.

What @BassemNKhalil states is correct.
