### ISSUE TITLE
https://your-sharepoint-site/_layouts/workbench.aspx

### ISSUE THREAD

**Issue by prdarm** [SharePoint/sp-dev-docs#6815]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 037842f6-772f-456d-6f44-0c46939bcddd
* Version Independent ID: 608ab68a-92a1-ca34-5ce6-2ae71691f6e6
* Content: [Set up your Microsoft 365 tenant](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant)
* Content Source: [docs/spfx/set-up-your-developer-tenant.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-developer-tenant.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
https://your-sharepoint-site/_layouts/workbench.aspx is the SharePoint Online hosted workbench url.

"your-sharepoint-site" should be replaced by the real SharePoint site url, for example:

https://tenant.sharepoint.com/sites/sitename/_layouts/workbench.aspx
