### ISSUE TITLE
Teams personal app about tab incomplete

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#6817]
## Category

- [x] Bug

## Describe the bug

The about tab that is automatically added to Teams personal apps created with SPFx does not show the information about the developer and the version:
![image](https://user-images.githubusercontent.com/26869201/111296566-edc9e480-864c-11eb-9049-ef4b7ff7d7df.png)
The links at the bottom are pointing to the correct Urls. All the information has been provided through the 'developer' section in the package-solution.json:
```
    "developer": {
      "name": "Syscovery solve and serve GmbH",
      "websiteUrl": "https://www.syscovery.com/",
      "privacyUrl": "https://www.syscovery.com/privacy/",
      "termsOfUseUrl": "https://www.syscovery.com/",
      "mpnId": "123456"
    }
```
Looking at the info screen of the app (right click on the icon -> info), everything is shown correctly:
![image](https://user-images.githubusercontent.com/26869201/111296749-1fdb4680-864d-11eb-8731-921968e29d56.png)
This happens in the Teams desktop app as well as in the browser (Chrome).

## Steps to reproduce

Add the developer information to the package-solution.json of a Teams personal app created with SPFx 1.11. 
Bundle and package a 'ship' version of your app.
Upload the app package to the tenant-wide app-catalog.
Sync the solution to teams.
=> Find the developer information is shown in the info screen but missing from the about tab.

## Expected behavior

The about tab should show the developer and version information.

## Environment details (*development & target environment*)

- **Your Developer Environment**:  Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: SPFx v1.11 on Node.js v10
- **Browser(s)**: Chrome v89 | Teams Desktop app
- **Tooling**: VS Code

### Additional context

None so far.

**Comment by michaelmaillot** [comment]
Hi @cwdata 

I assume that you chose to let SharePoint create the Teams app manifest file during the sync to Teams, right? In that case, looks like it doesn't completely work.

In the meantime, maybe you could generate the app manifest by yourself, so that you could handle all the properties.

You can have a look at [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions#developer-provided-microsoft-teams-app-manifest--package) for more info.

**Comment by cwdata** [comment]
Hi @michaelmaillot 
yes we don't provide a manifest and rely on the automatic one. To me this also looks like a bug - what could you do wrong if you don't do anything :-)
Maybe the automatic generation of the manifest is broken or maybe the displaying of its contents has a bug. Either way, as Vesa suggested, we informed about that issue.

**Comment by AJIXuMuK** [comment]
Hi @cwdata - sorry for the long delay, missed the issue due to metadata.
It has been fixed by now.

Could you please verify it on your end?

**Comment by cwdata** [comment]
Hi @AJIXuMuK,
yes it now shows values but they are not correct:
![image](https://user-images.githubusercontent.com/26869201/148906067-a1564350-b42b-41fa-8b6c-3065d4359e05.png)
Seems that it is having issues with ampersand & characters. The value in the package-solution.json is "solve & serve".

**Comment by GrahamMcMynn** [comment]
Hi @cwdata, could you help me determine where you are seeing this?
I went and created an SPFx app that shows up both in a personal tab as well as a teams tab.  When I go to add the app via Manage Your apps, i see the title and descriptions all on the card correctly:
![image](https://user-images.githubusercontent.com/16929083/153311030-f97fe08f-321d-4e7a-b240-1d4f1b7d29bb.png)


Then when I click it and I also see ampersands encoded correctly:
![image](https://user-images.githubusercontent.com/16929083/153311087-61bc0896-ad09-4540-92af-492bcdeb91f6.png)

Could you let me know where you are seeing this incorrectly added?

**Comment by cwdata** [comment]
Hi @GrahamMcMynn 
the ampersand is shown wrong in the info tab of the installed app:
![image](https://user-images.githubusercontent.com/26869201/153361734-4d4d12ca-59a9-40d1-93d8-988e48708897.png)
In the dialogs where you can add the app it's correct for us too.

**Comment by AJIXuMuK** [comment]
@cwdata - thank you for the details. We've looked into it. 
And it is a Teams issue, not SPFx or Sync to Teams.
If you create a custom manifest file with developer name that contains & - you will see the same behavior for your app.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/17036219/164279754-74407bc8-d9fb-4ea7-9acd-18eebd2f0ef8.png">

I would report this issue in one of the resources listed on this page: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback?wt.mc_id=devcomteams_navcommunity_webpage_mw
