### ISSUE TITLE
Extra 8px of web part padding since yesterdays outage

### ISSUE THREAD

**Issue by rmbw74** [SharePoint/sp-dev-docs#6818]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is anyone else seeing an extra 8px of padding around all web parts since Microsoft restored service after yesterdays outage?
![extra](https://user-images.githubusercontent.com/15833201/111318722-51471880-8633-11eb-93b6-cdb3d814918e.jpg)

**Comment by rmbw74** [comment]
Someone suggested changing the section color and seeing how the webpart reacts.  I cant imagine having this white border is considered normal? 
![2021-03-19 08_58_39-DevSandBox - Home-black back](https://user-images.githubusercontent.com/15833201/111792302-1db5f980-8892-11eb-98e4-a628d15deb17.jpg)\

seems like it is coming from this 

![2021-03-19 09_06_02-DevTools - asurion sharepoint com_sites_DevSandBox](https://user-images.githubusercontent.com/15833201/111792604-666db280-8892-11eb-8793-c5a854f84fcf.png)

**Comment by VesaJuvonen** [comment]
@rmbw74  - can you clarify what was the outage what you are referring to? Just to ensure that we are getting all the details. If this was the access issues last week, that was not really SharePoint Online specific and outage certainly should not have any impact on what is loaded from the servers, so confirming your observations.

**Comment by rmbw74** [comment]
@VesaJuvonen  - Sure.  Yes I'm referencing the global outage that occurred last week. After services were restored we noticed the behavior in the web parts as shown. This seems to be a recurrence of  some of issue #6757  that happened approximately about a month ago.

**Comment by rmbw74** [comment]
Looks like things have reverted back to normal,

**Comment by VesaJuvonen** [comment]
Most likely cause was accidental regression with human related mistake...
