### ISSUE TITLE
Node 10 LTS expires in May

### ISSUE THREAD

**Issue by westleyMS** [SharePoint/sp-dev-docs#6820]
When will SPFx update to a newer version of Node that will be supported past May?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
MSFT has stated that the next version of SPFx, v1.12, will support Node.js v12.

**Comment by westleyMS** [comment]
Is there a public document like the roadmap where we can find this information?
[SPFx Roadmap](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/roadmap)

**Comment by andrewconnell** [comment]
I guess that could have been on the page you reference... usually this is shared in the bi-weekly community calls.

**Comment by bcameron1231** [comment]
It's up on the site now.  

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0

**Comment by Hylar-86** [comment]
This still needs to be address as even in the the Microsoft Release Docs (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0) it states that 1.12 currently considered as deprecated due the unexpected regressions and you recommend usage of v1.11 which then by your documentation (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) is only compatible with Node 10.  So are you guys going to be releasing an updated SPFx that is compatible with Node 12+?
