### ISSUE TITLE
SPFx 1.12 upgrade getTasks is not defined

### ISSUE THREAD

**Issue by mgwojciech** [SharePoint/sp-dev-docs#6823]
## Category

- [x] Bug ? (Maybe)

Hello,
M365 cli migration tool suggests to add 

`
build.rig.getTasks = function () {
    var result = getTasks.call(build.rig);

    result.set('serve', result.get('serve-deprecated'));

    return result;
};
`
to Your gulpfile.js before migration to 1.12. This didn't work for me, I had to use

`
build.rig.getTasks = function () {
    var result = this.__proto__.getTasks.call(build.rig);

    result.set('serve', result.get('serve-deprecated'));

    return result;
};
`

Hope that helps :)

Have a good one.

**Comment by waldekmastykarz** [comment]
Hey @mgwojciech, thanks for reporting. Could you please share the complete gulpfile.js just so that we can double check that everything is in?

**Comment by mgwojciech** [comment]
Sure,
there are some entries to support fast serve and deal with fs dependency so it's a little bit more than minimal setup but I hope others use fast serve as well :)
`'use strict';

const fs = require('fs');
const build = require('@microsoft/sp-build-web');

build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    generatedConfiguration.node = {
      fs: 'empty'
    }
    fs.writeFileSync("./temp/_webpack_config.json", JSON.stringify(generatedConfiguration, null, 2));
    return generatedConfiguration;
  }
});

const argv = build.rig.getYargs().argv;
const useCustomServe = argv['custom-serve'];
const workbenchApi = require("@microsoft/sp-webpart-workbench/lib/api");

if (useCustomServe) {
  build.tslintCmd.enabled = false;

  const ensureWorkbenchSubtask = build.subTask('ensure-workbench-task', function (gulp, buildOptions, done) {
    this.log('Creating workbench.html file...');
    try {
      workbenchApi.default["/workbench"]();
    } catch (e) { }

    done();
  });

  build.rig.addPostBuildTask(build.task('ensure-workbench', ensureWorkbenchSubtask));
}
build.rig.getTasks = function () {
    var result = this.__proto__.getTasks.call(build.rig);

    result.set('serve', result.get('serve-deprecated'));

    return result;
};

build.initialize(require('gulp'));

`

**Comment by waldekmastykarz** [comment]
Thanks for sharing. In the code generated by SPFx v1.12 and suggested by CLI there is one more line that I'm not seeing in your code:

https://github.com/pnp/cli-microsoft365/blob/1760e4a1ab06bcd10f768ea43c518a92c497f50f/src/m365/spfx/commands/project/project-upgrade/rules/FN013002_GULP_serveTask.ts#L23

Could it be that that's causing the issue?

**Comment by mgwojciech** [comment]
oh yeah, that would make sense. Thanks!

**Comment by waldekmastykarz** [comment]
OK to close this issue?

**Comment by mgwojciech** [comment]
Sure!
