### ISSUE TITLE
contentUrl missing from fields that need updating in template

### ISSUE THREAD

**Issue by omarelanis** [SharePoint/sp-dev-docs#6824]
In the guide it does not mention that the contentUrl within the staticTabs object should also be updated with the component ID

"staticTabs": [
    {
      "entityId": "com.contoso.personaltab.spfx",
      "name": "My SPFx Personal Tab",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=**{{SPFX_COMPONENT_ID}}**%26forceLocale={locale}",
      "scopes": [
        "personal"
      ]
    }
  ],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by omarelanis** [comment]
The page has completely disappeared now!

**Comment by andrewconnell** [comment]
This page was retired in favor of the new deployment page for SPFx solutions used in Microsoft Teams: 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions

**Comment by andrewconnell** [comment]
NP... when the SPFx v1.12 release docs were published, the Teams related content was also refreshed to reflect the new deployment option. The SPFx docs shouldn't document how to build a Teams app manifest file, rather the Teams docs are already doing that. All you need in the SPFx docs are the SPFx-specifics, which is what the new page has.
