### ISSUE TITLE
TypeScript error with SharePoint module in SPFx Extension

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#683]
#### Category
- [ ] Question

I am trying to connect to SharePoint term store using the JavaScript Object Model (JSOM) as explained [here](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom). But I am getting the below error:

Any idea?

Feature : SPFx Extension

![image](https://user-images.githubusercontent.com/21008316/27739714-2b035156-5d75-11e7-9580-80b8a99b9205.png)

**Comment by iclanton** [comment]
It looks like the version of the TypeScript compiler isn't compatible with the version of `@types/sharpeoint` that you're trying to use.

Which version of the build tools (`@microsoft/sp-build-web`) are you using in your project? Is it GA or is it the latest drop?

**Comment by sprider** [comment]
@iclanton I am using the latest drop.

**Comment by waldekmastykarz** [comment]
To work around this issue you can install an older version of the SharePoint TypeScript typings, which are compatible with TypeScript v2.2.2 used by SPFx, like `@types/sharepoint@2013.1.7`

**Comment by sprider** [comment]
Yes, this will work until the issue is fixed. Thank you @waldekmastykarz.

**Comment by amishra0909** [comment]
Thanks for your feedback. The fix should be available in next drop when we upgrade to TS 2.4. Please reopen if the bug is reproduced.
