### ISSUE TITLE
Add standard web parts to full width

### ISSUE THREAD

**Issue by johanvandy** [SharePoint/sp-dev-docs#6830]
How can the standard (not custom) web parts be added to full width column?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4825eeab-f123-c0fb-0d30-6d634c821bd2
* Version Independent ID: 55d7e710-4faa-4cfa-772d-f83962d9fe52
* Content: [Use web parts with the full-width column](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column?source=docs)
* Content Source: [docs/spfx/web-parts/basics/use-web-parts-full-width-column.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/use-web-parts-full-width-column.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
@johanvandy the Hero and Image web parts can be added to a full width column. Currently they are the only out-of-the-box web parts that can be added to the full width column. You could however post a suggestion on the [SharePoint UserVoice](https://sharepoint.uservoice.com/).

**Comment by johanvandy** [comment]
@CallumCrowley 

I found a work-around. See [http://jenkinsblogs.com/2018/11/07/solution-add-web-part-in-full-width-section-in-a-sharepoint-online-communication-site/](url)
