### ISSUE TITLE
Error while creating Template xml with Get-PnPSiteTemplate cmdlet

### ISSUE THREAD

**Issue by mvanders** [SharePoint/sp-dev-docs#6835]
When trying to create a template: 
`
Connect-MySiteUrl -SiteUrl "https://upcbe47795.sharepoint.com/sites/EG-TF-NCAP_P"
Get-PnPSiteTemplate -Out "PnP-Provisioning-ACEA-Team-Site.xml"
`
I get the following error:
![image](https://user-images.githubusercontent.com/758617/111761849-a50a6980-88a0-11eb-8ab0-1a1de62e46ba.png)

Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b8037-a569-40c1-86ad-cbf56c9c4b4b
* Version Independent ID: c9dfddaa-7f54-7194-db9e-cf5f6370cbb5
* Content: [Introducing the PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by mvanders** [comment]
The last thing being show before crash...
![image](https://user-images.githubusercontent.com/758617/111774391-b27b2000-88af-11eb-8a41-757c1a38aee8.png)
Hope that helps...

**Comment by mvanders** [comment]
Euh... this even gets worse... now I create a brand clean Team Site from the Sharepoint page in M/O365 not using powershell, and I get the same error??? So even an out-of-the-box brand new Team Site fails???

**Comment by VesaJuvonen** [comment]
Which version of the PnP PowerShell you are using? - Just checking the baseline version status, so that we can start looking into what could be the root cause. Your exception seems to indicate a version conflict, which could be caused for example by having CSOM MSIT installed on your computer, which is not recommended, but we would need more details on your environment to be able to determine next steps.

**Comment by mvanders** [comment]
PS C:\GitHub\ACEA\PowerShell\Scripts> Get-Module * -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending    

Name                                            Version
----                                            -------
Microsoft.Online.SharePoint.PowerShell          16.0.20912.12000
MSAL.PS                                         4.21.0.1        
Pester                                          3.4.0
Microsoft.PowerShell.Utility                    3.1.0.0
Microsoft.PowerShell.Management                 3.1.0.0
Microsoft.PowerShell.Diagnostics                3.0.0.0
Microsoft.PowerShell.Host                       3.0.0.0
Microsoft.WSMan.Management                      3.0.0.0
Microsoft.PowerShell.Security                   3.0.0.0
Provisioning                                    3.0
Dism                                            3.0
PowerShellEditorServices                        2.3.0
PowerShellGet                                   2.2.5
PSReadLine                                      2.2.0
UEV                                             2.1.639.0
PSReadLine                                      2.1.0
ExchangeOnlineManagement                        2.0.3
AzureAD                                         2.0.2.130
AzureAD                                         2.0.2.128
AzureAD                                         2.0.2.118
AzureAD                                         2.0.2.116
Appx                                            2.0.1.0
Whea                                            2.0.0.0
International                                   2.0.0.0
Hyper-V                                         2.0.0.0
NetQos                                          2.0.0.0
AppLocker                                       2.0.0.0
BitsTransfer                                    2.0.0.0
VpnClient                                       2.0.0.0
NetLbfo                                         2.0.0.0
NetAdapter                                      2.0.0.0
SecureBoot                                      2.0.0.0
PSWorkflow                                      2.0.0.0
NetSecurity                                     2.0.0.0
SmbShare                                        2.0.0.0
Storage                                         2.0.0.0
TLS                                             2.0.0.0
TrustedPlatformModule                           2.0.0.0
SmbWitness                                      2.0.0.0
PSReadline                                      2.0.0
PSScriptAnalyzer                                1.19.1
PackageManagement                               1.4.7
Microsoft.Graph.Education                       1.4.0
Microsoft.Graph.Files                           1.4.0
Microsoft.Graph.Financials                      1.4.0
Microsoft.Graph.Devices.CloudPrint              1.4.0
Microsoft.Graph.Devices.CorporateManagement     1.4.0
Microsoft.Graph.DirectoryObjects                1.4.0
Microsoft.Graph.Groups                          1.4.0
Microsoft.Graph.Mail                            1.4.0
Microsoft.Graph.Notes                           1.4.0
Microsoft.Graph.People                          1.4.0
Microsoft.Graph.Identity.DirectoryManagement    1.4.0
Microsoft.Graph.Identity.Governance             1.4.0
Microsoft.Graph.Identity.SignIns                1.4.0
Microsoft.Graph.DeviceManagement.Functions      1.4.0
Microsoft.Graph.Bookings                        1.4.0
Microsoft.Graph.Calendar                        1.4.0
Microsoft.Graph.ChangeNotifications             1.4.0
Microsoft.Graph                                 1.4.0
Microsoft.Graph.Applications                    1.4.0
Microsoft.Graph.Authentication                  1.4.0
Microsoft.Graph.CloudCommunications             1.4.0
Microsoft.Graph.DeviceManagement.Actions        1.4.0
Microsoft.Graph.DeviceManagement.Administration 1.4.0
Microsoft.Graph.DeviceManagement.Enrolment      1.4.0
Microsoft.Graph.Compliance                      1.4.0
Microsoft.Graph.CrossDeviceExperiences          1.4.0
Microsoft.Graph.DeviceManagement                1.4.0
Microsoft.Graph.Sites                           1.4.0
Microsoft.Graph.PersonalContacts                1.4.0
Microsoft.Graph.Teams                           1.4.0
Microsoft.Graph.Reports                         1.4.0
Microsoft.Graph.Security                        1.4.0
PnP.PowerShell                                  1.4.0
Microsoft.Graph.SchemaExtensions                1.4.0
Microsoft.Graph.Planner                         1.4.0
Microsoft.Graph.Users                           1.4.0
Microsoft.Graph.Users.Actions                   1.4.0
Microsoft.Graph.Users.Functions                 1.4.0
Microsoft.Graph.Search                          1.4.0
PowerShellLogging                               1.3.0
PnP.PowerShell                                  1.3.0
PnP.PowerShell                                  1.2.0
MSOnline                                        1.1.183.57
Plaster                                         1.1.3
PSScheduledJob                                  1.1.0.0
PrintManagement                                 1.1
Hyper-V                                         1.1
PSDesiredStateConfiguration                     1.1
ProcessMitigations                              1.0.12
DeliveryOptimization                            1.0.2.0
Microsoft.PowerShell.Archive                    1.0.1.0
Microsoft.PowerShell.Operation.Validation       1.0.1
PowerShellGet                                   1.0.0.1
PackageManagement                               1.0.0.1
HostNetworkingService                           1.0.0.1
PSDiagnostics                                   1.0.0.0
WindowsSearch                                   1.0.0.0
DirectAccessClientComponents                    1.0.0.0
WindowsUpdate                                   1.0.0.0
PnpDevice                                       1.0.0.0
WindowsDeveloperLicense                         1.0.0.0
ScheduledTasks                                  1.0.0.0
StorageBusCache                                 1.0.0.0
StartLayout                                     1.0.0.0
Wdac                                            1.0.0.0
TroubleshootingPack                             1.0.0.0
PSWorkflowUtility                               1.0.0.0
BitLocker                                       1.0.0.0
Microsoft.PowerShell.LocalAccounts              1.0.0.0
BranchCache                                     1.0.0.0
HgsClient                                       1.0.0.0
AppvClient                                      1.0.0.0
AssignedAccess                                  1.0.0.0
Kds                                             1.0.0.0
DnsClient                                       1.0.0.0
EventTracingManagement                          1.0.0.0
HgsDiagnostics                                  1.0.0.0
ISE                                             1.0.0.0
iSCSI                                           1.0.0.0
CimCmdlets                                      1.0.0.0
NetworkSwitchManager                            1.0.0.0
NetworkConnectivityStatus                       1.0.0.0
NetTCPIP                                        1.0.0.0
NetworkTransition                               1.0.0.0
PKI                                             1.0.0.0
PersistentMemory                                1.0.0.0
PcsvDevice                                      1.0.0.0
MsDtc                                           1.0.0.0
NetEventPacketCapture                           1.0.0.0
NetConnection                                   1.0.0.0
NetSwitchTeam                                   1.0.0.0
NetNat                                          1.0.0.0
AppBackgroundTask                               1.0.0.0
Defender                                        1.0
ConfigDefender                                  1.0
Microsoft.PowerShell.ODataUtils                 1.0
MMAgent                                         1.0
WindowsErrorReporting                           1.0
ConfigCI                                        1.0
PowerShellEditorServices.VSCode                 0.2.0

**Comment by mvanders** [comment]
Any news here? For me, it's urgent because I rely on it to deploy team sites!

**Comment by VesaJuvonen** [comment]
On thing to check is that you actually have two different versions of the PnP.PowerShell installed. Would recommend on removing the other one for avoiding conflicts.

Next thing to test is to create oob site and then use the same cmdlet - to ensure that things work - this confirms that issue is not on your environment or the computer you use... rather for example being site specific issue on what you are exporting.

Next would recommend on using -Handlers switch on the cmdlet to detect which content is causing the issue. You could simply use for example Pages handler, which then would help to test if the issue is on pages, which seems to be the case.

That would most likely then confirm the area where the issue is... which we can predict to be in the modern pages. Then next steps would be to see what's on the page - what could cause the issue.

Whenever you get an exception from the PowerShell execution, you can also use $error[0].Exception.StackTrace in the command line to get you the latest StackTrace - this is highly helpful on understanding where things broke.

Hopefully that gets you forward on investigating where the root cause is.
