### ISSUE TITLE
SPFx Application Customizer is causing redirect to spfxsinglesignon.aspx on sub webs

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#6836]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is this the expected behaviour? If so, how to overcome this issue?

## Environment details
Windows 10
SharePoint Online
Node 10.23.1
Yo 3.1.1
TypeScript 4.1.2
VS Code

We have a simple SPFx Application Customizer which renders a global navigation to all sites. We are using pnp to fetch items from a config list. The component is running fine. Each time we navigate to a **sub-web** (new browser-session or adding a tab to the browser), the page is loading twice. We can see that the title "SPFx Single Sign On Redirect Page" is rendered on the tab when the page loads the second time.

![spfx](https://user-images.githubusercontent.com/22025808/111789882-ea8b5e80-88c1-11eb-8e85-a984d127b625.png)

From the network tab, I found some entries with requests and referrer to /_forms/spfxsinglesignon.aspx
`{
       "name": "referer",
       "value": "https://xxx.sharepoint.com/_forms/spfxsinglesignon.aspx"
 }`

Please note, that this issue **only** occurs **on sub-webs**, no matter if this is a team site or communication site.

Additional findings: This does not occur, if we navigate from websitecontent to the sub-web (which also is adding a new tab to the browser)

**Comment by VesaJuvonen** [comment]
Thanks @EA12 - Not quite sure if I got this 100%, so let's confirm.

- You have app customers build with SPFx (v1.11?) which is deployed to all sites in SharePoint Online using tenant wide deployment option
- App customizer renders properly in root site of site collections in modern pages - like https://contoso.sharepoint.com/sites/fuufaa
- When you move to a sub site, page is rendered twice and you see references to spfxsinglesinon.aspx in the network - URL in the browser for example https://contoso.sharepoint.com/sites/fuufaa/sub
- This does not happen for sub sites if you do not have the app catalog deployed or?

Is that accurate?

**Comment by EA12** [comment]
Hi @VesaJuvonen,

yes, with the latest SPfx, using tenant wide deployment option.
Root site rendering is OK. Rendering on pages of root site is also OK.
This happens to **sub-webs** only, if we start a new browser-session or adding a tab to the browser and pasting the url to a sub-web.
We are just using the global app catalog on this tenant, no site app catalog is activated.
Now clearer?

**Comment by VesaJuvonen** [comment]
Thanks @EA12
good information but we can't seem to repro with the following setup. Is this exactly what you are doing?

* Deploy tenant wide deployed app extention
* Include tenant scoped activation of app extension
* Ensure that is rendered properly in root site - https://contoso.sharepoint.com/sites/Comms - works
* Create modern sub site and confirm status - https://contoso.sharepoint.com/sites/Comms/modern

So - not quite sure what's going on. Are you embedding this to Teams or doing something else on the model?

**Comment by EA12** [comment]
Thanks @VesaJuvonen ,

yes, that is how we do it.
What we do:
From the OnInit in the applicationcustomizer.ts, we determine the culture:
`this.culture = this.context.pageContext.cultureInfo.currentUICultureName.toUpperCase().substr(0, 2);`

To render the top placeholder, we provide the context as prop to our component.
`if (this._topPlaceholder.domElement) {
        const element: React.ReactElement<{}> = React.createElement(
          GlobalNav,
          {
            context:this.context,
            lc: this.culture,
            filterFieldName: this.FilterFieldName
          }
        );
        ReactDom.render(element, this._topPlaceholder.domElement);
      }`

The component itself instantiate a provider in componentWillMount():

`public componentWillMount(): void {
    this.globalNavProvider = new GlobalNavProvider(this.props.context, this.props.lc, this.props.filterFieldName);
  }`

The provider will setup pnp and assigns locale variables for the context and so on:

`constructor(context: any, lc: string, filterFieldName: string) {
    this.spfxContext = context;
    sp.setup({
      sp: {
        headers: {
          Accept: "application/json;odata=verbose"
        },
        baseUrl: `${window.location.protocol}//${window.location.hostname}`        
      }
    });
    this.culture = lc; 
    this.FilterFieldName = filterFieldName;
}`

The component is calling the provider to get the data:

`public componentDidMount(): void {
    this.globalNavProvider.isSiteIsPrivate().then((res: string): void => {
      if(res == "Private") {
        this.setState({
          doNotRender: true
        });
      }
      else {
        this.globalNavProvider
        .getGlobalNavigation()
        .then(
          (result: IGlobalNavItem[]): void => {
            this.setState({
              globalNavItems: result
            });
          }
        )
	  }
	});
}`

First, the provider will identify, if the current site is a private group, because, we will not render anything in a private group

`public async isSiteIsPrivate(): Promise<string> {
    return new Promise((resolve, reject) => {  
      const web = Web(this.spfxContext.pageContext.web.absoluteUrl);

      web.select("AllProperties").expand("AllProperties").get().then(w => {
        const jsonString = JSON.stringify(w);
        const pop = JSON.parse(jsonString).AllProperties.GroupType;
        resolve(pop);
      });
    });
}`

If the method isSiteIsPrivate() does not return "Private", we fetch the items to build the global navigation

`public async getGlobalNavigation(): Promise<IGlobalNavItem[]> {
    var self = this;
    
    const results = await sp.web.lists
      .getByTitle(ListNames.GlobalNavigation)
      .items.select("*,"+FieldNames.ZGNParentTitle).top(2000)
      .expand(FieldNames.ZGNParent)
      .orderBy(FieldNames.ZGNOrder)
      .orderBy(self.FilterFieldName)
      .get();
    return this.parseGlobalNavigationNodes(results);
}`

The rest is just building the UI with React, based on the resultset.
So, nothing special here.
Any Idea what is causing the reload?

Please, open a new Browser-Tab and paste the url to a sub-web to the address-bar, then you will see the page loading twice.

Sorry, but the 'Insert code' toolbar action does not always work.

**Comment by EA12** [comment]
Nobody?

**Comment by PooLP** [comment]
I have same problem, but without ApplicationCustomizer, just some custom webpart in page.
Recently, I have this constant reload on admin SP page (the last load finish on spfxsinglesignon.aspx)
I have the problem on several tenants.

**Comment by xrsilver** [comment]
I have same problem that occurs on iPhones and iPads but not for every user. We have extension and web parts in the solution.

**Comment by xrsilver** [comment]
The problem disappeared by itself!

**Comment by patmill** [comment]
@EA12 - nothing stands out from your description that should cause spfxSingleSignOn to be called.  Can you capture a network trace and see what is triggering the redirect to it?  Maybe pnp.js is doing something atypical here?  You might also try asking in their issues list - https://github.com/pnp/pnpjs/issues

@PooLP - the admin pages are outside the scope of this issue list (as it is not extensible).

**Comment by PooLP** [comment]
The issue concerns also the spfxsinglesignon.aspx page, I found it relevant to also report this problem. Sorry, I did not want to destabilize you.
