### ISSUE TITLE
SPFx Application Customizer issue

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#6839]
SPFx Application Customizer issue at Tenant level

- [x] Bug

## Describe the bug

> Hi Team,

We have deployed an SPFx application customizer to apply custom headers and footers to Modern pages in O365 sites.
This has been deployed across tenant level and it was working till last week. 

We have redeployed the solution without any change last week due to a small confusion, and suddenly it stopped working for all users. The issue here is, deployed Application customizer is loading across sites only for the user who deployed the solution(me), and not for others. This is really confusing. Can someone help us on this Please. When it is not deployed at tenant level and added as an app under each sites, it works.

## Expected behavior

> SPFx Application Customizer deployed at tenant level should apply custom header across modern pages.

**Comment by srisspfx** [comment]
The only thing we can suspect is related to permission issue. Is there an compulsion like only tenant admin can push the .spkg package at App Catalog and the bundled files at CDN Path?

**Comment by VesaJuvonen** [comment]
Hi @srisspfx - can you double check the deployment status from the app catalog and ensure that the solution is not in checkedout status... This is just a hunch as never heard about your specific scenario before, but this might explain what happened... so in certain cases sppkg file is left in checked out status which could potentially cause this.

You can see that from the green marker in the app catalog.

![image](https://user-images.githubusercontent.com/7446437/111982348-87900680-8b11-11eb-9884-f4bf9df27010.png)

Thanks for confirming this status advance. Looking forward on hearing from you.

**Comment by srisspfx** [comment]
> Hi @srisspfx - can you double check the deployment status from the app catalog and ensure that the solution is not in checkedout status... This is just a hunch as never heard about your specific scenario before, but this might explain what happened... so in certain cases sppkg file is left in checked out status which could potentially cause this.
> 
> You can see that from the green marker in the app catalog.
> 
> ![image](https://user-images.githubusercontent.com/7446437/111982348-87900680-8b11-11eb-9884-f4bf9df27010.png)
> 
> Thanks for confirming this status advance. Looking forward on hearing from you.

**Comment by srisspfx** [comment]
Hi Vesa Juvonen,
Thanks for your time to look into this. I'm able to fix this issue. I did 2 things but not sure which one fixed the issue :)
First, I upgraded the SPFx Framework to latest version. 
Second, After uploading the .sppkg file, there was a list in App Catalog named "Tenant Wide Extensions" where the Approval status was showing as pending. I approved and it started working again.
