### ISSUE TITLE
Modernization framework support for sharepoint 2019?

### ISSUE THREAD

**Issue by rohit404404** [SharePoint/sp-dev-docs#6840]
Is modernization framework supported for on premise environment? i.e. if i have classic pages in sp 2013, and if farm is migrated to SP 2019- onpremise. Can I convert classsic page to modern with this framework?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c9c192-eb6e-5c54-f03f-7f66d43f92e6
* Version Independent ID: 328da4aa-fa66-0491-6a8d-94189f14e060
* Content: [Transform classic pages to modern pages](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages)
* Content Source: [docs/transform/modernize-userinterface-site-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by jansenbe** [comment]
Hi @rohit404404 , the modernization framework only supports SharePoint Online as target for the modernized pages. You can use it to transform your SP2013 and/or SP2019 classic pages into modern pages living in SharePoint Online. We've no plans to enable page transformation to transform pages into SP2019.

**Comment by rohit404404** [comment]
Thank you @jansenbe  Any documetation url stating same? ( not that i dont trust you)

**Comment by CallumCrowley** [comment]
@rohit404404 the SharePoint Modernization Framework is part of the PnP Framework, the PnP Framework only supports SharePoint Online as stated [here](https://github.com/pnp/pnpframework/blob/dev/README.md).

**Comment by rohit404404** [comment]
Thank you everyone for your response.
