### ISSUE TITLE
regarding spfx property control

### ISSUE THREAD

**Issue by arunsat** [SharePoint/sp-dev-docs#6841]
const { PropertyFieldNumber } = await import (
      /* webpackChunkName: 'pnp-propcontrols-number' */
      '@pnp/spfx-property-controls/lib/propertyFields/number'
    );
    const { PropertyFieldCollectionData, CustomCollectionFieldType } = await import (
      /* webpackChunkName: 'pnp-propcontrols-colldata' */
      '@pnp/spfx-property-controls/lib/PropertyFieldCollectionData'
    );

The above code shows cannot find modeule during gulp build

**Comment by VesaJuvonen** [comment]
Closing as this question is around the PnP Property Controls. Please open the issue at https://github.com/pnp/sp-dev-fx-property-controls/issues and provide details on what exactly is the expectation vs reality. Thanks.
