### ISSUE TITLE
SharePoint top navigation issue

### ISSUE THREAD

**Issue by shibu-123** [SharePoint/sp-dev-docs#6842]
The scope of the issue is been described in the below link  with screenshots(#6672). The top navigation when your spfx component material ui library. I have attached the spfx file which has the issue. This spfx file is linked to the library package file. Am unable attach library file as the file size is more than 20 mb. Could you please provide me a link to attach my library component.

https://github.com/SharePoint/sp-dev-docs/issues/6672#issue-800570013

[WaitingOnMeGrid.zip](https://github.com/SharePoint/sp-dev-docs/files/6182065/WaitingOnMeGrid.zip)

**Comment by andrewconnell** [comment]
Please don't post the project... ZIP's can contain harmful scripts which will prohibit many from downloading... plus, if it's 20MB, sounds like you're including **node_modules**.

Instead, create a public repo in github on your account and post a link to the original issue #6672 you referenced here to keep things consolidated in one thread. Thanks.

**Comment by shibu-123** [comment]
Hi Andrew

Below is my repo link to the library component and WaitingOnMeRequest. They do not contain any node_module folders

 https://github.com/shibu-123/LibraryComponent.git

https://github.com/shibu-123/WaitingOnMeRequest.git
