### ISSUE TITLE
Possible to run PowerAutomate with elevated permissions

### ISSUE THREAD

**Issue by omarelanis** [SharePoint/sp-dev-docs#6843]
For the section "Workflow administration" item "Create a workflow with elevated permissions" it is possible to elevate a workflow in PowerAutomate by calling a child workflow, this allows the child workflow to run under the elevated permissions of the flow publisher instead of the user running the flow granting the elevated permissions of the publisher account.

It would be useful to have this mentioned for when people come across this section:

Workflow administration | SharePoint workflow | Power Automate flow
-- | -- | --
Central location to view all workflows | Yes, only available to view for a given list or library | Yes, 'My flows' lists user flows
Share workflows with list or library users | Yes | Yes
Share workflows with users | Not available | Yes
Save a copy of workflow to create a copy of the workflow | Not available | Yes
Workflow versioning | Not available | No
Create a workflow with elevated permissions | Yes, by granting permissions to workflow app and then using App Step action and SharePoint Add-ins | Not available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc176ce2-e245-8c2a-62a9-29f0fa3f755a
* Version Independent ID: 50df0c72-d567-a572-a4db-80730c5881f7
* Content: [Guidance - Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)
* Content Source: [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Care to submit a PR to the docs so the owners of this page can review your contribution & potentially incorporate it?

**Comment by omarelanis** [comment]
Should have thought of doing that instead of raising it as an issue, I'll submit as a PR
