### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by bCrops** [SharePoint/sp-dev-docs#6844]
[Enter feedback here]

### Documentation error on page: 
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting

### Incorrect content: 
getMonth: returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year). - Only available in SharePoint Online

"txtContent":"=getMonth(Date('12/26/1981'))" results in 11

### Correct content:
getMonth: returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year). - Only available in SharePoint Online

"txtContent":"=getMonth(Date('12/26/1981'))" results in 12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Amos-MSFT** [comment]
There should be no problem with this part of the content. The month retrieved here starts from 0, so 11 represents December.
![image](https://user-images.githubusercontent.com/56672877/112104570-57666780-8be6-11eb-8ab8-578ae2cdd03f.png)
There is a similar method in JavaScript:[Date.prototype.getMonth()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)
![image](https://user-images.githubusercontent.com/56672877/112104713-8086f800-8be6-11eb-9764-4ab2a402d2a0.png)
Amos Wu
Microsoft SharePoint Community Support
