### ISSUE TITLE
This page needs updating to reflect latest changes in SharePoint change the look

### ISSUE THREAD

**Issue by rkeller1012** [SharePoint/sp-dev-docs#6846]
Will these instructions (and schema) be updated to include some of the newer change the look elements, such as the new header and footer options? Several new change the look options have been introduced since the last update to this page and it would be great to be able to start utilizing them in site scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site design JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-json-schema.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Double checked with Microsoft engineering & they say these options you mention aren't in site scripts so there's nothing to update in the docs. When they do update it, they'll update the docs
