### ISSUE TITLE
Blank page on hosted workbench

### ISSUE THREAD

**Issue by MaxMattiello** [SharePoint/sp-dev-docs#6853]
When i debug my webpart using Hosted Workbench (i use Chrome extension) i'm able to add it on the page but when i switch to the preview page i'm able to see only a blank page.
In the browser developer tool area i see a few error message like:
"Uncaught DOMException: Blocked a frame with origin "https://webshell.suite.office.com" from accessing a cross-origin frame."
"URIError: URI malformed
    at decodeURI (<anonymous>)
    at t.render (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:1)
    at Da (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at Fa (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at mo (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at ou (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at iu (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at Go (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)
    at sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65
    at t.unstable_runWithPriority (sp-webpart-workbench-assembly_it-it_f17ddb51e8720a29d7f6ec78401ebe5f.js:65)"
.
I use:
- Node.js v10.24.0
- spfx v1.12.0

![issue 1](https://user-images.githubusercontent.com/81249220/112172436-027e1d80-8bf5-11eb-8c15-51df3097e16d.png)
![issue 2](https://user-images.githubusercontent.com/81249220/112172448-0447e100-8bf5-11eb-878f-bcbf5a36630f.png)
My package.json is
"name": "pianificazione-risorse",
  "version": "1.0.0.0",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.12.0",
    "@microsoft/sp-lodash-subset": "1.12.0",
    "@microsoft/sp-office-ui-fabric-core": "1.12.0",
    "@microsoft/sp-property-pane": "1.12.0",
    "@microsoft/sp-webpart-base": "1.12.0",
    "@pnp/spfx-controls-react": "3.0.0",
    "@types/jquery": "^3.5.5",
    "@types/jqueryui": "^1.12.15",
    "jquery": "^3.6.0",
    "jqueryui": "^1.11.1",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-dom": "16.9.0"
  },
  "devDependencies": {
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@microsoft/sp-build-web": "1.12.0",
    "@microsoft/sp-tslint-rules": "1.12.0",
    "@microsoft/sp-module-interfaces": "1.12.0",
    "@microsoft/sp-webpart-workbench": "1.12.0",
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }

Thanks

**Comment by KevinTCoughlin** [comment]
What URI is throwing this error? Can you set a breakpoint and share? That appears to be root of the problem not the cross-origin Shell frame.

"URIError: URI malformed
at decodeURI ()

**Comment by MaxMattiello** [comment]
Hi Kevin,
thanks for your feedback.
I don't know what happened today, but now i'm able to see and debug my app.
I've a function that call a SharePoint list using REST API and if i comment it i'm able to see the my page; then i uncomment the function and all is working fine...strange!
I think you can put on hold this issue or close it.

Thanks again for your support.

Massimo
