### ISSUE TITLE
Calling clearLoadingIndicator removes entire WebPart

### ISSUE THREAD

**Issue by geoffbarcalow** [SharePoint/sp-dev-docs#6854]
## Category

- [x] Bug

## Describe the bug

> Calling displayLoadingIndicator(this.domElement, "data") works just fine, but after I call clearLoadingIndicator(this.domElement) the entire web part is removed and does not reappear. I've seen other's reports indicate that it's fix will be in an upcoming release, but that was in 2017 and I'm running 1.12 the version released in Mar 2021. 

Similar, but apparently unresolved.
https://github.com/SharePoint/sp-dev-docs/issues/709
https://github.com/SharePoint/sp-dev-docs/issues/696

## Steps to reproduce
1) c:\Project > yo @microsoft/sharepoint
2) code .
3) edit [webpartname].ts add this code:
`  onPropertyPaneConfigurationStart() {
    this.context.statusRenderer.displayLoadingIndicator(
      this.domElement,
      "data"
    );
    setTimeout(() => {
      this.context.statusRenderer.clearLoadingIndicator(this.domElement);
      this.render();
    }, 5000);
  }`
4) gulp serve
5) Click Edit/Configure button

## Expected behavior
After clicking on the configure button, the loading message would be display for 5 seconds. Then, the loading message would disappear and return to my web part. Unfortunately, that never happens.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10, VS Code 1.54.3
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.24.0
- **SPFx**: v1.11 and v1.12
- **Browser(s)**: Chrome v79 and Chromium Edge v79
- **Tooling**: VS Code 1.54.3 | SPFx v1.12.0 and v1.11 | yo v3.1.1 | gulp CLI v2.3.0 Local v3.9.1

### Additional context

I've noticed that the domElement innerHtml is empty after calling clearLoadingIndicator. I can save and restore the innerHtml before and after the call, but all I get back is something that looks like the webPart, but is non-functional.

I also tried the remedy listed in the link below but that just added a loading indicator below the react component.
https://github.com/SharePoint/sp-dev-docs/issues/2771
`let domElement = document.createElement("div");
this.domElement.appendChild(domElement);
this.context.statusRenderer.displayLoadingIndicator(domElement, "Some text", 1);`

**Comment by AJIXuMuK** [comment]
@geoffbarcalow - sorry for the long delay.
The fix has been done and will be included in the next beta of 1.14.
`displayLoadingIndicator` will have additional parameter: `clearDomElementCallback`. You will be able to use it to correctly clear React container.

I will update the sample as soon as the new release is out.

**Comment by AJIXuMuK** [comment]
1.14.0-beta.5 that contains the fix is out.
