### ISSUE TITLE
Build your first SharePoint Framework Extension not working

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#686]
OK, So I have tried three times to get the “Build your first SharePoint Framework Extension” working, but have yet to succeed.
Parts one and two work just fine, but I continually run into issues on parts 3 or four. In my third attempt today, I am stick on part 3. I’ve added the elements.xml file(changing the guid to my guid):
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">

    <CustomAction 
        Title="SPFxApplicationCustomizer"
        Location="ClientSideExtension.ApplicationCustomizer"
        ClientSideComponentId="ee2d9f33-4602-4757-8adb-09336bb64a72"
        ClientSideComponentProperties="{&quot;Header&quot;:&quot;Header area of the page&quot;,&quot;Footer&quot;:&quot;Footer area in the page&quot;}">

    </CustomAction>

</Elements>

and updated the package-solution.json as below:
```
{
  "solution": {
    "name": "app-extension-client-side-solution",
    "id": "b2a0b8b6-77f7-49a4-a5b8-868aa78ad13b",
    "version": "1.0.0.0",
     "features": [{
      "title": "Application Extension - Deployment of custom action.",
      "description": "Deploys a custom action with ClientSideComponentId association",
      "id": "456da147-ced2-3036-b564-8dad5c1c2e34",
      "version": "1.0.0.0",
      "assets": {        
        "elementManifests": [
          "elements.xml"
        ]
      }
    }]

  },
  "paths": {
    "zippedPackage": "solution/app-extension.sppkg"
  }
}
```

I deployed the sppkg to my app catalog and deployed it to a site on my dev tenant. But it is not loading my app. I look at a fiddler trace and it is making no calls to my localhost. I checked out the site features where I installed the app and the feature IS active.

How does one goo about troubleshooting these things?

**Comment by mcmynn83** [comment]
Thanks for your question.  In order to investigate this issue could you please send the following:
What is your tenant URL?
Could you send the correlation ID from the request that is not working (look at the response headers and the GUID under SPRequestId is the correlation ID)?

Thanks

**Comment by NinjaSciurus** [comment]
Hi, I am facing the same issue. Here are my details:

Tenant URL: https://adessodev.sharepoint.com/
SPRequestGuid: 04c12c9e-e047-4000-87a2-b646c4b812f7

Thanks for your help!

**Comment by mcmynn83** [comment]
Please open a new thread for this as we have closed this issue on our side.  I'm closing the git hub thread now. 

Thanks!
