### ISSUE TITLE
spfx 1.12 issue with visio-web-embedded.js

### ISSUE THREAD

**Issue by cfillies** [SharePoint/sp-dev-docs#6861]
## Category

- [x] Bug

## Describe the bug

Using v12.21.0 and gulp 4.0.2
I am failing to get the Visio integration working, and I am wondering if anybody else got this running.

We are currently deploying this with v10 to several customers..
(I will cross post this to the Visio partner Teams channel)

[20:14:48] Finished subtask 'configure-webpack' after 1.67 s
[20:14:48] Starting subtask 'webpack'...
[20:15:00] Error - [webpack] 'dist':
**Did not find linked external "officejs" for bundle "visio-sample-web-part".**

[20:15:00] Finished subtask 'webpack' after 12 s
[20:15:00] Starting subtask 'reload'...
[20:15:00] Finished subtask 'reload' after 3.19 ms

config.json:
  ....
  "externals": {
    "officejs": {
      "path": "https://appsforoffice.microsoft.com/embedded/1.0/visio-web-embedded.js",
      "globalName": "officejs"
    }
  },

my package.json is:
{
  "name": "spfxdummy",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "jtest": "jest"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.12.0",
    "@microsoft/sp-lodash-subset": "1.12.0",
    "@microsoft/sp-office-ui-fabric-core": "1.12.0",
    "@microsoft/sp-property-pane": "1.12.0",
    "@microsoft/sp-webpart-base": "1.12.0",
    "@pnp/common": "^2.0.12",
    "@pnp/logging": "^2.0.12",
    "@pnp/odata": "^2.0.12",
    "@pnp/sp": "^2.0.12",
    "@pnp/spfx-controls-react": "^2.2.0",
    "@pnp/spfx-property-controls": "^2.2.0",
    "@types/jest": "^26.0.21",
    "@types/office-js": "0.0.101",
    "base-64": "^1.0.0",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "typescript": "^3.7.7",
    "utf8": "^3.0.0",
    "webpack": "^5.27.2"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.9": "^0.4.40",
    "@microsoft/sp-build-web": "1.12.0",
    "@microsoft/sp-module-interfaces": "1.12.0",
    "@microsoft/sp-tslint-rules": "1.12.0",
    "@microsoft/sp-webpart-workbench": "1.12.0",
    "@types/enzyme": "^3.10.8",
    "@types/mocha": "^8.0.4",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~6.9.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "gulp": "^4.0.2",
    "identity-obj-proxy": "^3.0.0",
    "jest-junit": "^12.0.0",
    "react-test-renderer": "^17.0.1",
    "ts-jest": "^26.5.4",
    "tslint-microsoft-contrib": "~6.2.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest"
    },
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx|js)"
    ],
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "cobertura"
    ],
    "coverageDirectory": "<rootDir>/jest",
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy"
    },
    "reporters": [
      "default",
      "jest-junit"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 100,
        "functions": 100,
        "lines": 100,
        "statements": 100
      }
    }
  },
  "jest-junit": {
    "output": "./jest/summary-jest-junit.xml"
  }
}
tsconfig.json:
{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-3.9/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env",
      "office-js",
      "mocha",
      "jest"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection",
      "es2015.promise"
    ]
  },
  "include": [
     "src/**/*.tsx",
     "src/**/*.ts",
  ],
  "exclude": [
    "node_modules",
    "lib",
    "acceptance-tests",
    "webpack",
    "jest",
    ".vs",
    ".vscode"
  ]
}

## Steps to reproduce

my repro code is at https://github.com/cfillies/spfx12visiowebpart 

## Expected behavior

get a chance to add the Visio web part

## Environment details (*development & target environment*)

win10
node v12.21.0 and gulp 4.0.2

### Additional context

**Comment by bcameron1231** [comment]
Hi, thank you for adding the issue! At this time, there have been several issues with SPFx 1.12 and it has now been deprecated. Please uninstall SPFx 1.12, and work in SPFx 1.11 and let us know if you have any further issues.

**Comment by andrewconnell** [comment]
Flagging this as "won't-fix" because as @bcameron1231 said, MSFT has pulled/deprecated SPFx v1.12. Please try this again with v1.11: https://twitter.com/vesajuvonen/status/1374620885315948545
