### ISSUE TITLE
SharePoint Top Navigation issue

### ISSUE THREAD

**Issue by shibu-123** [SharePoint/sp-dev-docs#6862]
Hi Andrew

The scope of the issue is been described in the below link with screenshots(#6672). The top navigation when your spfx component material ui library. I have attached the spfx file which has the issue. This spfx file is linked to the library package file. Am unable attach library file as the file size is more than 20 mb. Could you please provide me a link to attach my library component.

Below is my repo link to the library component and WaitingOnMeRequest. They do not contain any node_module folders

https://github.com/shibu-123/LibraryComponent.git

https://github.com/shibu-123/WaitingOnMeRequest.git

**Comment by AJIXuMuK** [comment]
Hi @shibu-123 - sorry for the delay.
Could you please provide some details regarding what exactly is wrong?
Also, could you please double-check that the issue is still repro?
