### ISSUE TITLE
SPFx Application Customizer issue in SPO Hub Communication sites.

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#6864]
Hi Team,

We have tenant wide deployed SPFx Application Customizer. These custom stuffs are not loading in SPO Hub Communication sites. Also we are not able to add Modern script editor web parts. Is there any script blocks which need to be removed on SPO Hub Communication sites, so that custom scripts can be added. Please help.

Thanks in advance,
Sridhar S

**Comment by michaelhan-1** [comment]
Try to enable Custom Script for your Communication  site : `Set-SPOsite <SiteURL> -DenyAddAndCustomizePages 0`

Reference: https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script

**Michael Han
Microsoft SharePoint Community Support**

**Comment by srisspfx** [comment]
Thanks Michael, We will try this and let you know whether that fixes the issue.

Sridhar
