### ISSUE TITLE
Unable to set LocalID to 3081 (Australia) using New-SPOSite

### ISSUE THREAD

**Issue by CrackerboxOnline** [SharePoint/sp-dev-docs#6865]
## Category

- [x] Bug

## Describe the bug

Attempted to batch create sites and set LocaleID to 3081 for Australia however am getting the following error message:
  **Microsoft.SharePoint.Client.ServerException: LocaleId 3081 is not a suppported locale.**

Apparently does not work in PnP PowerShell either but have not validated.
https://github.com/pnp/PnP-PowerShell/issues/1407

## Steps to reproduce

1. Windows PowerShell as Admin
2. Updated Microsoft.Online.SharePoint.PowerShell module
3. Run the following commands in script. Variables imported from CSV 
    #local vars to make this easier
    $siteName = $row.SiteName;
    $siteUrl = $row.SiteUrl;
    $siteOwner = $row.Owner;
    $siteLogoUrl = $row.LogoUrl;
    $siteLocale = $row.Locale;
    $siteTimezone = $row.Timezone;
    $siteTemplate = $row.Template;
    #$hubSiteUrl = $row.HubSiteUrl;

    Write-Output $("Creating {0}..." -f $siteUrl);
    #create site
    Write-Host -ForegroundColor Cyan "Site name: "$siteName
    Write-Host -ForegroundColor Cyan "Site url: "$siteUrl
    Write-Host -ForegroundColor Cyan "Site owner: "$siteOwner
    Write-Host -ForegroundColor Cyan "Site logo: "$siteLogoUrl
    Write-Host -ForegroundColor Cyan "Site LocaleID: "$siteLocale
    Write-Host -ForegroundColor Cyan "Site timezone: "$siteTimezone
    Write-Host -ForegroundColor Cyan "Site template: "$siteTemplate

    Write-Host -f Yellow "...creating comm site and associating with hub site"
    try
    {
      New-SPOSite -StorageQuota 20000 -Template $siteTemplate -TimeZoneId $siteTimezone -Title $siteName -Url $siteUrl -Owner $siteOwner -NoWait -LocaleId $siteLocale
    }
    catch [System.Exception] 
    { 
      Write-Host -ForegroundColor Red $_.Exception.ToString() 
      break;
    }
    finally
    {
      Write-Host -f Green "Site created"$siteName
      Write-Host
    }

4. See error and site not created.

## Expected behavior

Expected to find that site had been created and locale set to English (Australia).

## Environment details (*development & target environment*)

E5 Developer tenancy

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: PowerShell
- **Browser(s)**: latest Chrome/Edge
- **Tooling**: VS Code
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide any other context about the problem.

*Thanks for your contribution! Sharing is caring.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/sp-dev-docs/wiki/How-to-Create-Good-Issues).
> - If you are reporting an issue around any of the documents or articles, please ensure that you have referenced the specific file or URL of the related document.
> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
> - Remember to include sufficient details and context.
> - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**
>
> *Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
As the error states, this isn't a supported locale in SharePoint:

- https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/jj167546(v=office.15)
- https://support.microsoft.com/en-us/office/languages-supported-by-sharepoint-dfbf3652-2902-4809-be21-9080b6512fff
