### ISSUE TITLE
Node 10 LTS Deprecated and SPfx Recommendation only works on Node 10

### ISSUE THREAD

**Issue by Hylar-86** [SharePoint/sp-dev-docs#6867]
This still needs to be address even though this has been asked as an issues #6820 as even in the the Microsoft Release Docs (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0) it states that 1.12 currently considered as deprecated due the unexpected regressions and you recommend usage of v1.11 which then by your documentation (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) is only compatible with Node 10. So are you guys going to be releasing an updated SPFx that is compatible with Node 12+?

**Comment by KevinTCoughlin** [comment]
@Hylar-86 we are releasing a patched `1.12` shortly that includes support for Node 12 as well as regression fixes.

Node 10 is EOL in April; which btw does not mean you must stop using it but that the software is no longer actively maintained.
