### ISSUE TITLE
Set up your Spfx Page references V1.12

### ISSUE THREAD

**Issue by flasponge** [SharePoint/sp-dev-docs#6868]
The main MS setup docs for Spfx ["Set up your SharePoint Framework development environment"](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) reference unstable release Spfx v1.12 this may mislead new developers.
 
Should docs reflect stable Spfx V1.11 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#spfx--sharepoint-server-2016)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
Yes. SPFX  Version 1.12 release is currently considered as deprecated due the unexpected regressions.  Should still use the V1.11 stable version.

And this command currently will install v1.11 SPFX generator:

npm install gulp yo @microsoft/generator-sharepoint --global

Another point needs to care is to install Node.js 10.x as v1.11 didn't support Node. js 12.x .
