### ISSUE TITLE
How to delete modern Team Site?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#687]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm trying to delete modern team site. I've read [the post](https://support.office.com/en-us/article/Delete-a-SharePoint-site-or-subsite-bc37b743-0cef-475e-9a8c-8fc4d40179fb) on how to delete a site. But I don't see 'Delete site' link in Site Information panel (tested on 2 tenants).
Also tried to go to Site Settings to delete the site using old-school way. But I don't see 'Delete this site' link there...
I have Full Control permissions, also tried to add myself to Site collection administrators - no luck. 
Any thoughts?

**Comment by dannyjessee** [comment]
I ultimately had to use PowerShell (SharePoint Online Management Shell) to delete my modern team sites:

`Remove-SPOSite https://yoursite.sharepoint.com/teams/yourteamsite`

I also had an issue where I had deleted my root site collection and couldn't create a new one in the SharePoint admin center until I also removed the modern team sites I had created from the site collection recycle bin:

`Remove-SPODeletedSite https://yoursite.sharepoint.com/teams/yourteamsite`

To fully clean up after deleting your modern team site, make sure you also delete the associated group from the Office 365 admin center after you delete the site.

**Comment by AJIXuMuK** [comment]
@dannyjessee, yup. Now I'm using PowerShell.
But to my mind it should be in UI. Especially if it is described in the documentation.

**Comment by MaruthachalamK** [comment]
Here is your answer:
Check Delete Modern Team site section in this article:
[https://social.technet.microsoft.com/wiki/contents/articles/40067.sharepoint-online-modern-team-sites.aspx] (SharePoint Online Modern Team Sites)

**Comment by AJIXuMuK** [comment]
@MaruthachalamK if you look at my initial question it has link to the same guide on how to delete a site.
The thing is that at the moment when I asked the question 'Delete site' link was not presented on Site Information pane.
Now it is there, so I can close the question.

Thanks
