### ISSUE TITLE
How to get auth token for SharePoint REST Service?

### ISSUE THREAD

**Issue by renanwillian** [SharePoint/sp-dev-docs#6873]
How I get this accessToken?

GET https://{site_url}/_api/lists/getbytitle('{list_name}')/items
Authorization: "Bearer " + accessToken
Accept: "application/json;odata=verbose"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa0c9cd-d807-8d1b-1eb0-66373fa254b9
* Version Independent ID: 409a88a8-7ae9-afde-d66c-81529ad15669
* Content: [Get to know the SharePoint REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?redirectedfrom=MSDN&tabs=csom)
* Content Source: [docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Depends on your SP environment (SP on-prem & which version, SharePoint Online, etc).

For SharePoint Online, you need to create an Azure AD app, grant it the necessary delegated permission auth with Azure AD to obtain an access token & then use that when you call the SP REST API. You can learn more about how to obtain an access token from the MS identity (aka: Azure AD) docs:
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

However, if you're working with SPO, consider using Microsoft Graph to access SharePoint data... it's a proxy on top of the SP REST API, and MANY more services.

FWIW, the MS Graph docs have a whole section on how to obtain an access token. The only difference between using the access token for Graph or SPO: the permissions you grant it. All the concepts are identical.
https://docs.microsoft.com/en-us/graph/auth/
