### ISSUE TITLE
Configuring the PnP Provisioning Engine

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#6875]
Dear team
Perhaps it would make sense to update the commands to the PnP.PowerShell versions, now that  SharePointPnPPowerShellOnline is deprecated?
I.e. `Get-PnPProvisioningTemplate -Configuration "config.json" -Out "template.xml"` should be `Get-PnPSiteTemplate`

[Configuring the PnP Provisioning Engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine)

best regards
Kinga 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8604e955-4a77-7abe-0138-e554fdef0b41
* Version Independent ID: b03bc3e7-88ec-b808-190c-32e69f0b968e
* Content: [Configuring the PnP Provisioning Engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Care to submit a PR with this change and contribute to the docs?
