### ISSUE TITLE
SPFx: Sync to Teams 400 error for long developer name

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#6876]
## Category

- [x] Bug

## Describe the bug

When I enter my full name and company name for my SPFx solution, the sync to Teams fails. When I only enter the company name, the sync to Teams works fine.

## Steps to reproduce

Here is the section from my SPFx package-solution.json
```
    "developer": {
      "name": "Christophe Humbert - User Managed Solutions LLC",
      "websiteUrl": "https://appsource.usermanagedsolutions.com/inPerson",
      "privacyUrl": "https://appsource.usermanagedsolutions.com/inPerson%20Privacy%20Policy.pdf",
      "termsOfUseUrl": "https://appsource.usermanagedsolutions.com/inPerson%20Terms%20of%20Use.pdf",
      "mpnId": ""
    }
```

1. Create a SPFx Web Part solution (v 1.11) with React.
2. Add the above developer information under package-solution.json
3. In the Web Part manifest, make the Web Part a Teams tab: "supportedHosts": ["TeamsTab"]
3. Bundle and package the solution
4. Upload the sppkg to the SharePoint App Catalog
5. Select Sync to Teams
6. Get a fail message and 400 error: "value":"The remote server returned an error: (400) Bad Request."

## Expected behavior

I would expect that:
- Either the Sync to Teams works
- Or there is a documented limitation with the developer information
- Or the error message is more explicit than just "bad request"

## Environment details (*development & target environment*)

SharePoint Framework (SPFx) v 1.11 with React.

**Comment by andrewconnell** [comment]
Looks like the [MSTeams manifest schema](https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json) has a `maxLength` setting on this & other properties on the `developer` element, while the [SPFx package-solution.json schema](https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json) doesn't.

I've made engineering aware of this... not really a bug, rather could be a better experience...

**Comment by PathToSharePoint** [comment]
@andrewconnell Thanks! And right, I had to pick a category as @VesaJuvonen told me to log the issue. Troubleshooting Sync to Teams is an adventure and string length was the last place I thought about. 32 is actually not bad and would work for most people :-)

**Comment by AJIXuMuK** [comment]
Hi @PathToSharePoint - sorry for the long delay.
It has been fixed literally few days after you've submitted the issue. But not mentioned here - sorry for that.

Could you please double-check on your end?

Thanks!
