### ISSUE TITLE
Urgently need to update SPFx tools to newer NodeJS vesion

### ISSUE THREAD

**Issue by Rick-Kirkham** [SharePoint/sp-dev-docs#6879]
According to this article, SPFx requires NodeJS 10.0. This is an old version that will reach End-of-Life at the end of this month (April, 2021) according to the Node site: https://nodejs.org/en/about/releases/.  When it reaches End-of-Life some libraries used with SPFx, like SASS, will stop supporting it. 

The tutorials for SPFs need to updated to use a more recent version of NodeJS ASAP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jerry0527** [comment]
Actually SPFX 1.12 has supported Node12.x, however, as Version 1.12 release is currently considered as deprecated and has been unpublished due the unexpected regressions.

So currently, still suggested to use SPFX v1.11 instead.

You can wait for the new version release of SPFX, it will support Node.js 12.x

**Comment by andrewconnell** [comment]
As @Jerry0527 said, Microsoft is aware. SPFx v1.12 did address this but had to be pulled. They've publically said that v1.12.1 will be released in April and it will include support for Node.js v12 & v14.
