### ISSUE TITLE
How to make SOAP request from spfx-webpart?

### ISSUE THREAD

**Issue by ReDERO** [SharePoint/sp-dev-docs#688]
#### Category
- [+ ] Question

Good day, colleagues!
In my spfx-webpart I need to make SOAP request to SharePoint. How can I do this?

**Comment by chackman** [comment]
Thanks for your question.

Assuming there is an equivalent SharePoint REST API, calling the REST API is preferable.  You can also use the JavaScript Object Model (JSOM) to access SharePoint API's.

To call a SOAP API you would need to handle auth separately.

Could you please clarify whether the API is not available via REST or JSOM?

**Comment by ReDERO** [comment]
@chackman, thank you for your answer. 

I think, that SharePoint Framework doesn't have JSOM libraries. But yesterday I had found [this article](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom). It resolves my problem.

SP REST API has some limits. For example, you can not create JOIN request, that connect two lists, which are located on different sites. $expand will gives an error message. This trick is only works through JSOM.

**Comment by chackman** [comment]
Thanks for your response.
Good to hear that you were able to use JSOM to do this.
