### ISSUE TITLE
Inconsistency in required NodeJS versions

### ISSUE THREAD

**Issue by Rick-Kirkham** [SharePoint/sp-dev-docs#6880]
This article says that SPFx development requries NodeJS 10.0, but later, when the reader is told to run `npm trust-dev-cert`, that command give the following error that says 10.0 can't be used: 

This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0 || >=10.13.0 <11.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment]
Node `10.13.0` is the first `10.x` release tagged LTS https://nodejs.org/en/download/releases/. The docs should either reference `10.13.0` or say `10.x` rather than `10.0`.

**Comment by andrewconnell** [comment]
@Rick-Kirkham the docs say to use Node.js v10.x, not Node.js v10.0. Due to how often Node.js ships releases, a while ago we changed the docs to not reference a specific version, rather the docs explicitly state:

> Install the latest version of Node.js LTS v10.x.
