### ISSUE TITLE
Reference to mysterious file

### ISSUE THREAD

**Issue by Rick-Kirkham** [SharePoint/sp-dev-docs#6883]
Note that the file referred to in the following paragraph (with an extension of `scss.ts` is visible in File Explorer, but it does not appear in Visual Studio code, even if I refresh the files pane in VSC. This is confusing. Can you explain why it is not seen in VSC? 

![image](https://user-images.githubusercontent.com/9088056/113494655-26681b80-949f-11eb-93e3-a6fe5ac5bf23.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment]
Could that extension be excluded in the `.vscode/settings.json` file?

```json
// Place your settings in this file to overwrite default and user settings.
{
  // Configure glob patterns for excluding files and folders in the file explorer.
  "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true,
    "**/bower_components": true,
    "**/coverage": true,
    "**/lib-amd": true,
    "src/**/*.scss.ts": true
  },
  "typescript.tsdk": ".\\node_modules\\typescript\\lib"
}
```

**Comment by andrewconnell** [comment]
@KevinTCoughlin is correct, but this can trip people up so a small mention in the docs could help. Thanks for the feedback...
