### ISSUE TITLE
[Doc-enhancement] Troubleshooting guide - SharePoint site as Personal Tab

### ISSUE THREAD

**Issue by SubbaReddi** [SharePoint/sp-dev-docs#6886]
## Category

- [x] Bug

There are certain issues that can arise to add SharePoint site/pages as Personal tab. Adding below mentioned points as trouble shooting steps will help to resolve the issues.

Possible issues:

1. Personal tab with SharePoint site/page is loading sometimes and showing blank screen intermittently.
2. Working fine in Teams webclient(https://teams.microsoft.com) and not working in Desktop teams client. Showing blank screen.

Possible reasons and solution:

1. contentURL and Website URL might have given wrong.:
    contentUrl in manifest must be in following format: {{siteUrl}}/_layouts/15/teamslogon.aspx?SPFX=true&dest={{sitePath}}
       ex: https://contoso.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/ContosoHub
       ex2: https://orgtenantname.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/teams/site2

   websiteUrl must be in following format: {{siteUrl}}
    ex: https://contoso.sharepoint.com/sites/ContosoHub
    ex2: https://orgtenantname.sharepoint.com/teams/site2

2. SSO(single sign-on) properties missing in manifest
    Make sure you added following properties in manifest:
    AAD application ID: 00000003-0000-0ff1-ce00-000000000000
    Resource Url: {{subdomain}}.sharepoint.com
   Ex: https://contoso.sharepoint.com
   Ex2: https://orgtenantname.sharepoint.com

Final generated manifest should be similar as shown [here](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites#a-sample-manifestjson-file)

**Comment by andrewconnell** [comment]
Thanks for the feedback, but do you have a suggestion where to mention this? Maybe submit a PR to contribute in improving the docs?

**Comment by SubbaReddi** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6994

**Comment by andrewconnell** [comment]
Thanks for that PR! That's in the content owned by another team so we'll let them manage that...
