### ISSUE TITLE
Tenant admin permissions required?

### ISSUE THREAD

**Issue by thomas-bak** [SharePoint/sp-dev-docs#6888]
In the following section it's stated that we need to enter credentials of a "user with administrative permissions on the tenant":
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops#setting-the-variables-for-the-environment

This seems excessive and not a good practice to store credentials for a tenant admin user in DevOps (or anywhere else for that matter). Is there no other way to accomplish this, e.g. using a service principal, a managed identity or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db891d3-c14d-9bae-80fc-cedaf2eb5982
* Version Independent ID: aae8a107-ee2a-7b9c-9022-9946b7f65909
* Content: [Implement Continuous Integration and Continuous deployment using Azure DevOps](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
The user must have permissions to write to the app catalog site
