### ISSUE TITLE
🙏 ISO Named Web Part Groups & their IDs

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#689]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Client-side web part manifests include both a `groupId` and `group` property. My understanding from reading the docs is if you specify the correct `groupId`, your web part can get added to one of the groups that MSFT is using or you can declare your own GUID and name to put your stuff in your own group.

Can MSFT share the master list of all the available groups that are provisioned in a new site collection? Seems to not be documented anywhere...

**Comment by andrewconnell** [comment]
Just noticed this 075279a74d8041dd8539e140ea3ed358221405b0 update... thanks @VesaJuvonen !

**Comment by VesaJuvonen** [comment]
Of course, should have checked if there's an issue for this. Thx @andrewconnell for following up and closing this, appreciated.
