### ISSUE TITLE
List form provisioning

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#6890]
What is the recommended approach for list form provisioning? Site Scripts? PnP provisioning? SPFx? 
I think only Site Scripts support it now but it seems like an overkill ;)

Any recommendations welcome =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
There's no recommended approach... just multiple options for you to choose from. 

Personally, I'd avoid using XML-based (aka: Feature schema) provisioning.

**Comment by bcameron1231** [comment]
To add onto Andrew's comment, there actually isn't a supported way of doing this. Microsoft doesn't support it yet in Site Scripts, and to my knowledge, neither does PnP.

**Comment by andrewconnell** [comment]
Ah... totally missed the word "form"... @bcameron1231 is correct. At this time, customizing the list form is not supported, nor is it even possible.

It's a *long* requested feature...
