### ISSUE TITLE
Node v10 reaching end-of-life

### ISSUE THREAD

**Issue by wonderplayer** [SharePoint/sp-dev-docs#6894]
As stated [here](https://nodejs.org/en/about/releases/), on 30/04/2021 Node v10 will reach its EOL. Does it mean, that soon SPFx will switch to v12?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
As part of the upcoming SPFx v1.12.1 we will support both node 14 and node 12. ETA by end of April.

**Comment by wonderplayer** [comment]
Thanks!
