### ISSUE TITLE
Can this be done on SP2019?

### ISSUE THREAD

**Issue by dipetersen** [SharePoint/sp-dev-docs#6895]
[Enter feedback here]
This is great for creating a theme in SharePoint online, but SP2019 also has modern sites and this doesn't work with SP2019.  Can someone add some documentation on how to do this for SP2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4347bb55-4376-5248-6af5-732c7084779f
* Version Independent ID: e3fa3f65-72f8-9a5c-024e-cc6c38a18874
* Content: [Modernize site branding](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-branding)
* Content Source: [docs/transform/modernize-branding.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-branding.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
The only way I know how is to use REST endpoints for this. 2019 doesn't have a location for uploaded themes (like tenant themes in SPO), so you would have to apply them on each site.

We've created a Web Part to facilitate this, you can find it over in the PnP Samples repository. This will help you apply a modern theme to a site collection in 2019
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/js-theme-manager-2019
