### ISSUE TITLE
Workbench not serving code from localhost if Tenant or Site level sspkg is deployed

### ISSUE THREAD

**Issue by jpalo** [SharePoint/sp-dev-docs#6897]
## Category

- [x] Bug

## Describe the bug

It used to be so that one could override sspkg's deployed on Tenant or Site from localhost in the SPO Workbench. Back in the years there was a time when it was broken a while, then fixed, but now again if you have sspkg deployed on Tenant or Site level, and you debug in the SPO Workbench, it will always just serve the Tenant/Site sspgk and not the code from your localhost.

## Steps to reproduce

1. Build, package and deploy sspkg (web part) to Tenant or Site level
2. Do `gulp serve --nobrowser`
3. Go to SPO Workbench, add web part
4. You will get served the sspkg from Tenant or Site level, you can se it as you won't see the `webpack://` folder in browser Developer Tools' Sources pane

If you remove the sspkg from the Site/Tenant level, the Online Workbench serves correct version from your localhost.

## Expected behavior

 1. Workbench overrides Tenant and Site deployed sspkg.
 2.  Site deployed sspkg overrides Tenant deployed sspkg.

Not being able to do this prevents 'quality assurance' testing in production environment with production data.

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v89 | Chromium Edge v91]
- **Tooling**: [VS Code | SPFx v1.11.0]

**Comment by andrewconnell** [comment]
Is this a dupe to #6838? While that issue is about issues SPFx v1.12, it seems like it's the same topic that's being addressed...

**Comment by jpalo** [comment]
Not related to 1.12 nor #6838. Perhaps something on SPO end how it determines which sspkg to serve when you have same package deployed on different "levels", i.e., tenant/site/localhost.

**Comment by andrewconnell** [comment]
FWIW, *.sppkg files aren't served up... that's just the deployment artifact. When you deploy a package, SPO cracks it open and uses that for deployment. At runtime, it's all about the component manifest. I explained how it works here: https://www.voitanos.io/blog/spfx-5w1h-how-does-the-sharepoint-framework-work/#how-does-workbench--debugging-impact-the-spfx-runtime

If you've deployed the same thing at multiple levels, it could be that the page is confused on which is taking priority. I'm not sure if that's supported...

**Comment by bcameron1231** [comment]
I'm having trouble reproducing this. I built a 1.10 solution, that was deployed to the tenant and site collection app catalog, and in both cases, I was able to debug the solution both Chrome 89 and Credge. I have seen this behavior in FF, but unfortunately I can't reproduce this currently.
