### ISSUE TITLE
workbench.aspx doesn't exist

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/sp-dev-docs#69]
All worked fine when I tried to build these example web parts. However when I tried to navigate to the following URL: https://your-sharepoint-site/Shared%20Documents/workbench.aspx
I found that workbench.aspx didn't exist. All new look changes have come through on my office 365 tenant but I'm not getting the workbench to exist in SharePoint.

Did I miss anything?

**Comment by wictorwilen** [comment]
Did you download Workbench.aspx (found in the code part of this repo) and upload it to your document library? Also it cannot be your top level site collection (scripting is disabled on that site collection by default).

**Comment by patmill** [comment]
Specific details are here - https://github.com/SharePoint/sp-dev-docs/wiki/Setup-SharePoint-Tenant

**Comment by Pieter-Veenstra** [comment]
Thanks. I missed that step.
