### ISSUE TITLE
HttpClientResponse error on build typescript 2.4.1

### ISSUE THREAD

**Issue by Hennadiy** [SharePoint/sp-dev-docs#690]
#### Category
- [ ] Question
- [x] Typo
- [x] Bug
- [ ] Additional article idea

Using typescript 2.4.1 it gives an error:
`node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(14,21): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.`

Because of different types of field "type".
Class field:
`readonly type: string;`
Interface field:
`readonly type: ResponseType;`

If in class field type change to "ResponseType" error disappears.

**Comment by mcmynn83** [comment]
Thank you for the feedback.  At this time 2.4.1 is not supported.  We are doing work to make this happen but we do not have a timeline yet.
