### ISSUE TITLE
List form provisioning

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#6901]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea
## Question

Related to #6890
Thank you @andrewconnell  and @bcameron1231 for your answers. 
I think we still have a bit of misunderstanding =)
I was referring to the "Configure the list form" functionality that is already rolled out and documented: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration. 
This functionality allows for some simple customizations of header, footer and for column ordering. 

The described approach is fully manual, which is fantastic for end users, but perhaps still lacking for developers. 

Executing `Get-SPOSiteScriptFromList` generates a SiteScript that includes these customizations: 
```
          [...]
         "verb": "setClientFormCustomFormatter",
          "clientFormCustomFormatter": {
            "headerJSONFormatter": {           [...]
             },
            "footerJSONFormatter": {          [...]
             },
            "bodyJSONFormatter": {          [...]
             },
             }
          [...]
```
so it seems that it's also already supported in SiteScripts. 

There's one small inconvenience here, however. SiteScripts need to be deployed as part of SiteDesign and although SiteDesign may be scoped to certain users, the deployment still needs SP Admin rights. 
I'm trying to operate with minimum required permissions and requesting SP Admin for a scenario where I'm deploying SPFx extensions and provision a list is a bit too much =)

Is there a way to automate deployment of FormCustomFormatter, without using SiteScripts?
Or... maybe using "standalone" SiteScripts for asset provisioning would be an idea? Is it something already in the making, since @andrewconnell advises against using XML?

looking forward hearing your thoughts on that :D
best regards
Kinga

**Comment by bcameron1231** [comment]
Hi! Well the support for Site Scripts is definitely new! Microsoft must have just released support for that! 

I understand the small inconvenience piece, but isn't that no different than permissions needed to your SPFx solutions? So your minimum required permissions would be same, as you will need the admin to also deploy your SPFx Solution for you as well.

**Comment by kkazala** [comment]
Not if I use site app catalog ;) https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog
