### ISSUE TITLE
Code sample in docs and GitHub code samples not up to date with latest implementations (o365 vs m365)

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/sp-dev-docs#6907]
- [ ] In the docs the code samples have more recent code, using the m365 CLI, compared to the code which is linked in the GitHub article residing in the master branch using o365 CLI. 

- [ ]  The login script already holds the app catalog URL which is not aligned with the latest implementation. This parameter should be removed. Otherwise the deploy fails on this step.
`- script: m365 login $(m365_app_catalog_site_url) --authType password --userName $(m365_user_login) --password $(m365_user_password)
          displayName: Login to Microsoft 365`

- [ ] It should also be stated that the first time you want to use the configured m365 user to login, you should do it with an interactive login on a device, so you are able to grant the "PnP Management Shell" app. Otherwise you are never able to login from the pipeline, which will produce this type of error.

> Error: AADSTS65001: The user or administrator has not consented to use the application with ID '31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for this user and resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ab0e-7e7d-df8f-5607-8794b5d26024
* Version Independent ID: 16b7890e-6e7f-0573-3d79-51bdb04758dd
* Content: [Implement Continuous Integration and Continuous deployment using Azure Pipelines](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-pipelines)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Good feedback... with the name change, there were bound to be some things that slipped through the cracks. Care to submit PR's to help fix these things?
