### ISSUE TITLE
Viva connections not loading application customizers on lists or document library pages when accessed via a link on the page

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#6908]
## Category
- [x] Bug

## Describe the bug

Application customizers using the header or footer zones are not appearing on document library or list pages in viva connections when they are accessed by a link manually added to the page (e.g. Quick Links or Hero). They appear and work fine on all other pages when accessed via a manual link.

## Steps to reproduce

1. create an application customizer with a header and deploy the app - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
2. Setup viva connections with the SharePoint home site
3. Add a link using the Quick Links web part to a list on the site (e.g. a custom list)
4. Click on the link in the viva app
5. View the header in the app and see that it disappears when you go to a list or document library page

Working on SP pages
![app-working](https://user-images.githubusercontent.com/17725046/114419713-9404fd80-9bab-11eb-9d3f-d2cddd5c96fa.jpg)

Accessing a list or doc library via link on page
![link2](https://user-images.githubusercontent.com/17725046/114420318-1f7e8e80-9bac-11eb-88c8-9b3136a67f95.jpg)

App customizer not showing when accessed via link in desktop and web version of Teams
![app cust not working](https://user-images.githubusercontent.com/17725046/114419849-b1d26280-9bab-11eb-94a4-ebfaa3eb6526.jpg)

## Expected behavior

Expected the application customizer to load as if the list has been accessed via the SP navigation.

## Environment details (*development & target environment*)

1.10.0 and 1.11.0 SPFx versions
Desktop and Web version of Teams
All tenants (tried on several)

### Additional context

It seems to work fine via the SharePoint current menu but not when accessed via links added to SharePoint pages (which will be a big part of SP intranets).

Let me know if you need any further info!

**Comment by andrewconnell** [comment]
When submitting your issue, it helps to state what versions you're using, not just *I've tried a few*... ie: which few? :)

**Comment by CloudDesignBox** [comment]
Sorry Andrew. I was rushing trying to post it between meetings yesterday! Just checked and both my packages were actually using the same version, I have updated above! I try using latest version if I get chance later today.

**Comment by CloudDesignBox** [comment]
@andrewconnell I've replicated this with a clean project using SPFx 1.11.0 and shared it here: https://github.com/CloudDesignBox/TestApplicationCustomizer

**Comment by AJIXuMuK** [comment]
This should be now rolled out WW.
