### ISSUE TITLE
Extensions: Support Development in Local Workbench

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#691]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Today, application extensions in SPFx (command sets, application customizers & field customizers) can't be tested within either the local or SharePoint Online hosted workbench. This is a bummer and a big step backwards to such a cool aspect to the development story with SPFx.

I get that you need a list to work with, but at a minimum, the workbench could have a static list with static data and no other functionality for us to test the customizations on.

My wish is that Microsoft adds support to the workbench for extensions before GA.

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

OK, cross-referenced: [Extensions: Support Development in Local Workbench](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/19857541-extensions-support-development-in-local-workbench)

**Comment by andrewconnell** [comment]
Closing to keep feature requests in UserVoice... my bad.

**Comment by Colbz** [comment]
Just starting to develop extensions now and realizing what a huge pain it is not having the local workbench. I have to retract and redeploy the solution every time I make a simple CSS change. We're back to farm solutions all over again. So inefficient

**Comment by frankchen76** [comment]
Have you checked Ignite video [Building the modern SharePoint experience: Best practices from Microsoft for developing with SPFx](https://myignite.microsoft.com/videos/53866) ? It actually mentioned about an approach which you can add your SPO workbench with your customization properties into serve.josn, and then you can call gulp serve --config [your config] to open up your browser and go that url directly. You probably can find out the detail around 00:35:00 in the video. the following is a sample of serve.json: 

`{
  "$schema": "https://dev.office.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "initialPage": "https://localhost:5432/workbench",
  "https": true,
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  },
  "serveConfigurations":{
    "default":{
      "pageUrl":"https://localhost:5432/workbench"
    },
    "appCustomizer":{
      "pageUrl":"https://[your tenant].sharepoint.com/sites/Dev/Shared%20Documents/Forms/AllItems.aspx",
      "customActions":{
        "9738323b-d946-4d29-afc8-abb4d06d9b42":{
          "location":"ClientSideExtension.ApplicationCustomizer",
          "properties":{
            "testMessage":"Hello as property!",
            "header":"Test Header area of the page"
          }
        }
      }
    }
  }
}
`
you can run the following command
`gulp serve --config customActions`

**Comment by Colbz** [comment]
Oh nice, this looks promising I will test and advise

**Comment by andrewconnell** [comment]
@Colbz ... vote it up: https://sharepoint.uservoice.com/users/188371890-andrew-connell
