### ISSUE TITLE
Add a step to show how to connect

### ISSUE THREAD

**Issue by jasonwbaxter** [SharePoint/sp-dev-docs#6914]
A lot of customers have not kept up to date with PNP , and to learn PNP is a steep learning curve , one customer has just told me that its taken him 3 months to learn how to authenticate.

can we consider adding some basic steps on how to connect instead of jumping into the method.

Also because PNPsitesCore is listed , its a bit confusing when suddenly there is a PNP version of how to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926ab97b-0406-116a-9b44-59df02beee7d
* Version Independent ID: 3094c3cf-cd16-518e-48fc-095fb14036dd
* Content: [Customizing 'modern' site pages](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-pages.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
That connection information is provided on the PnP PowerShell page that's linked form this page before you dive into using the cmdlets. Connection details aren't included here because it would be repetitive to include that prerequisite information in every single page in the docs where PNPPOSH is used, hence we refer to te project which has content on that topic.

**Comment by Jerry0527** [comment]
PnP PowerShell Connection command "Connect-PnPOnline" and all other commands detailed documetation can be found here:

[Connect-PnPOnline](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
