### ISSUE TITLE
Using 'SharePoint' link in suite bar (partially) reloads current site/page before actually navigating to _layouts/15/sharepoint.aspx

### ISSUE THREAD

**Issue by MarksPoint** [SharePoint/sp-dev-docs#6915]
## Category

- [x] Bug

## Describe the bug

From our custom web part, we're seeing quite a lot of logged exceptions related to the `pageContext` property (of the web part context object) being `undefined`. For instance, we see the following error messages:

- "Cannot read property 'site' of undefined"
- "Cannot read property 'web' of undefined"

This happens any time we access a `pageContext` property directly (e.g. `context.pageContext.site.id`) but it also happens deeper inside PnP logic when we try to load a list item like this:
```
        const items = await sp.web.lists
            .getByTitle(SOME_LIST)
            .items.filter(`Author eq 1234`)
            .top(1)
            .get();
```

The weird thing was that users never reported these issues to us, even though the web part couldn't have rendered correctly in these cases. I now understand why this is the case: it only seems to occur when the user navigates away to the 'sharepoint.aspx' page using the SharePoint button in the suite bar. 

In this case, before actually navigating away from the current page, the current page seems to (quickly) reload/rerender. This could happen unnoticably in a split-second but it could also take some time in which case you actually see the page reload, as in the example below, in which case I use a default community site and navigate to the SharePoint page. Notice the reload just after the button click:

https://user-images.githubusercontent.com/16799069/114687549-2de7ba00-9d14-11eb-99df-5ffa674df40d.mov

During this reload we see the aforementioned errors occur as the `pageContext`  now is/became `undefined`.

## Steps to reproduce

See video above, but in general:
1. Go to a SharePoint site
2. Click on the SharePoint button in the Suite Bar
3. See the page reload/refresh (quickly)
4. See the navigation to the sharepoint.aspx page take place after the reload

## Expected behavior

The reload seems unnessecary but in any case shouldn't cause exceptions to occur (i.e. `pageContext` shouldn't be `undefined`)
Expected behavior would be that the navigation takes place immediately without the current page to rerender/reload.

## Environment details (*development & target environment*)

- **Your Developer Environment**: macOS 11.2.3
- **Target Environment**: SharePoint Online
- **Framework**: NA
- **Browser(s)**: Issue is seen in all major browsers, but attached videos were with Chrome v89
- **Tooling**: SPFx v1.11.0
- **Additional details**: Environment doesn't seem to matter. It happens in Safari but also in Edge (as I analyzed in the logs). It also doesn't seem to matter if custom web parts are even on the page. As can be seen in the first video, this unexpected reload also happens on a default community site without customizations.

### Update 1 (April 16, '21)

Apologies for skipping Environment Details even though it was pointed out that they're important. I've re-added them.

I've done some more research on the behavior and created a dummy project to reproduce what we're seeing in our (much bigger and more complex) solution.

It comes down to the following code (part of HelloWorld.tsx), that shows some async logic that tries to read the `pageContext` property:

```
    private timeout: number = 0;

    public componentDidMount() {
        this.timeLog('HelloWorld [MOUNT]');
        this.timeout = setTimeout(() => {
            this.timeLog('HelloWorld [ASYNC]');
            try {
                this.setState({
                    siteId: this.props.context.pageContext.site.id.toString(),
                });
            } catch (err) {
                this.timeLog('HelloWorld [ERROR]: ' + err.message);
            }
        }, 500);
    }

    public componentWillUnmount() {
        this.timeLog('HelloWorld [UNMOUNT]');
        // If we'd clear the timeout we will not have the issue in this case
        // if (this.timeout) {
        //     clearTimeout(this.timeout);
        // }
    }
```

See what happens in the console when I run this web part and use the "SharePoint" button in the suite bar:

https://user-images.githubusercontent.com/16799069/115037366-adb98400-9ece-11eb-92d4-1fd1272a8126.mov

So in short this is what you see:

- *Load the page
- [1618582479746] HelloWorld [MOUNT] <- Expected log
- [1618582480263] HelloWorld [ASYNC] <- Expected log
- *Navigate to SharePoint using button in suite bar
- [1618582572356] HelloWorld [UNMOUNT] <- Expected log
- [1618582572362] HelloWorld [MOUNT] <- UNExpected log
- [1618582572536] HelloWorld [UNMOUNT] <- UNExpected log
- [1618582572876] HelloWorld [ASYNC] <- UNExpected log
- [1618582572876] HelloWorld [ERROR]: Cannot read property 'site' of undefined <- UNExpected log

In this case I've used a setTimeout to mimic the async logic, but in our actual solution we're mostly waiting for async API calls to complete before we're doing other things (e.g. using the `pageContext` to access the site id to do some caching). The result however is similar to what you see here.

So I guess my question comes down to:
- Why is there even a refresh before navigating away from the page?
- Why is the `pageContext` undefined all of a sudden inside the async code?

I've attached the project I've used to demonstrate in the video.
[DemoSolution.zip](https://github.com/SharePoint/sp-dev-docs/files/6325774/DemoSolution.zip)

**Comment by andrewconnell** [comment]
Please complete the environment details section that was provided... versions are important. Where are you trying to reference the `pageContext` in your code?

**Comment by MarksPoint** [comment]
@andrewconnell Hi Andrew, apologies for leaving the bits out. I've re-added them, as well as some more information after I did some research. I left the original question intact and added an update in the bottom.

**Comment by AJIXuMuK** [comment]
Hello @MarksPoint - sorry for the long delay.
I believe the behavior has been fixed already and there is no additional mount/unmount during navigation to the SharePoint page. Could you please check it on your side?

But to be on a safe side of things, I'd recommend to review your code, and clear promises in case if the component is unmounted and/or the web part is disposed.
Otherwise there could be memory leaks and access of disposed resources.

**Comment by MarksPoint** [comment]
Hi Alex,

Looking at our logs I think the issue is indeed solved. I no longer see these "Cannot read property 'site' of undefined" messages pop up.

Thanks for the feedback!
