### ISSUE TITLE
View Formatting `hideSelection` ignored for expanded groups

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#6916]
## Category

- [x] Bug

## Describe the bug

When using the `hideSelection` property set to `true` in view formatting the selection is disabled until a group is expanded then the selection is available for that group and all items in it.

![GroupSelectionBug](https://user-images.githubusercontent.com/8364109/114771277-61d5d600-9d3a-11eb-94c7-a10b44ba6be6.gif)

## Steps to reproduce

1. Group a listview by any column
2. Apply this format:

```JSON
{
  "hideSelection": true
}
```

3. See that the selection is hidden on the rows as expected
4. Expand a group
5. Now see the selection is visible and active for the expanded group and any items in that group
6. Cry

## Expected behavior

`hideSelection` should keep working even when groups are expanded or drilled into

## Environment details (*development & target environment*)

SharePoint Online - Targeted Release

**Comment by shagra-ms** [comment]
@thechriskent `hideSelection` takes effect only when `rowFormatter` (for list layout) is present. 
The same is mentioned in the documentation [here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting#hideselection).

**Comment by shagra-ms** [comment]
@thechriskent The group list selection UX is the same without the JSON shared above. The JSON above eventually has no-effect, as per the documentation.

Please do share thoughts if you believe the `hideSelection` should be available without the rowFormatter JSON present.

**Comment by thechriskent** [comment]
Didn't realize the standard behavior was to not allow group selection unless the group was expanded. That seems strange to me, but point taken that this has nothing to do with formatting.

I was aware that hideSelection was only for rowFormatters but I thought it was partially working in this case. That's just my misunderstanding. Thanks for letting me know!

---

However, I think `hideSelection` should work universally as it's a top level property. The above is a great example of when I'd want to disable the selection functionality even when using the out of the box rendering for list items. Selection in this case has no meaning. I am using the list as an expandable FAQ list to be displayed in the webpart. I think having the ability to specify it even with no other properties makes sense.

Back to the issue with `hideSelection` and groups, however, there is still a problem. If I specify a `rowFormatter` as required, the selection functionality is only disabled on the actual rows. It still shows up for group headers when expanded. This is very confusing as these definitely do nothing:

![GroupSelection](https://user-images.githubusercontent.com/8364109/117013564-fd18f600-acbd-11eb-9dd6-4f30521c2af1.gif)

While I would prefer the `hideSelection` to just work regardless of the presence of `rowFormatter`, if that isn't something Microsoft wants to implement, an alternative solution is to add a `hideSelection` property to the `groupProps`.

**Comment by shagra-ms** [comment]
Thanks for detailed explanation. I am noting down 3 major points from your comment -
1. Group not being selectable when collapsed -  _I will pass this feedback to right team_
2. `hideSelection` should work without the `rowFormatter` - _Thanks for your feedback. Will discuss this internally._
3. `hideSelection` doesn't disable selection on groups - _clearly a bug_

Let me know if I missed anything from your comment.

Will keep this GitHub issue open to track 3 above. In case we pick 2 above, I will update the documentation. Thanks!

**Comment by shagra-ms** [comment]
2 is fixed and should be available in all tenants.
3 is fixed, but rollout may take some time.

Resolving this as no actionable item is pending.
