### ISSUE TITLE
Referencing Lookup Values

### ISSUE THREAD

**Issue by Zerg00s** [SharePoint/sp-dev-docs#6917]
It would be useful it this article included an example on how to reference values from lookup fields. Or, if it's not technically possible, mention it as a limitation.

For example, this won't work
```
=if([$LookupField.name]=='London', 'true', 'false')
```

and this won't work either:
```
=if([$LookupField.lookupValue]=='London', 'true', 'false')
```
and this:
```
=if([$LookupField]=='London', 'true', 'false')
```

## Update

Turns out, lookup values can be references this way:

```
=if([$LookupField]=='1;#London', 'true', 'false')
```

So, when referencing a lookup value, we need to use this format: `<Lookup ID>;#<Lookup Title>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Care to submit a PR ot help out with the docs?

**Comment by Zerg00s** [comment]
> Care to submit a PR ot help out with the docs?

Sure. I'll submit a PR today.

**Comment by JaylardPbf** [comment]
In my testing, the sample code for referencing the value of a Lookup field doesn't work. I was the one who [posted a question about this on StackExchange](https://sharepoint.stackexchange.com/questions/292798/spo-using-json-to-show-hide-modern-form-field-based-on-value-selected-in-lookup), to which [you suggested this approach](https://sharepoint.stackexchange.com/a/292805/74663). However, I couldn't get it to work. @Zerg00s , are you actually able to get this code to work in SharePoint?

**Comment by Zerg00s** [comment]
hi @JaylardPbf, we can try to figure out why it didn't work. but here is a quick proof that it should work:

![Lookup condition](https://user-images.githubusercontent.com/2797648/115090450-e82d1c00-9ee2-11eb-9a7b-4b6dae53baba.gif)

**Comment by JaylardPbf** [comment]
@Zerg00s, thanks for your follow up. What you are showing looks like what I was trying to achieve, assuming that "City" is a Lookup field and not a Choice field. In my case, the single-select Lookup field I tried to use was derived from a second list on the same site, as I believe is required by SharePoint. Beyond that, I used the default Title field to contain the text value. In my case, I had three values in the second list, only one value of which, 'Hourly', would trigger the optional field to display. The ID in the secondary table for the row with 'Hourly' as its Title was 1. So using the construction you suggested, my JSON snippet for the field whose visibility I wanted to toggle on and off was:

`=if([$LookupField]=='1;#Hourly', 'true', 'false')`

That seems consistent with your example, and yet it would do absolutely nothing when I selected the 'Hourly' value from my Lookup drop-down list. Reengineering the Lookup field as a Choice field, it worked perfectly with a basic construction like this:

`=if([$ChoiceField]=='Hourly', 'true', 'false')`

Do you see anything in my Lookup example that is different from what you have used?

**Comment by Zerg00s** [comment]
@JaylardPbf , can you try again please? When you select a value in a lookup field, you have to click away in order to see the condition to kick in. When I use a Choice - you won't need to click away. I have just fried the whole think from scratch in a different tenant. And I can confidently say that it works.

**Comment by JaylardPbf** [comment]
@Zerg00s , you are correct. This does work. I think my confusion was caused by my own error, so my apologies for questioning the validity of your solution.
