### ISSUE TITLE
SharePoint Framework Extension - Setting form field values

### ISSUE THREAD

**Issue by michaelppaye** [SharePoint/sp-dev-docs#692]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Firstly, just to quickly say that we're loving the new Extensions framework. We've made good headway in particular with the ListView Command Set functionality. 

This is either a question - or perhaps an enhancement/suggestion. One of our typical use cases is to set field values (specifically managed metadata fields). With classic pages it was fairly simple to update field values (on the page, rather than setting the server values) in JavaScript using the "Microsoft.SharePoint.Taxonomy.ControlObject". We'd like to be able to do the same within modern pages, either on the dedicated edit form - or on the edit panel on the main list view. Is this currently possible? Either from the context of a ListView Command Set button, or perhaps as an ApplicationCustomizer?

**Comment by dgaeta** [comment]
Thanks for the feedback. Today editing scenarios aren't supported through SPFx extensions. 
This is similar to [#1449](https://github.com/SharePoint/sp-dev-docs/issues/1449 )
If you wish, you can enter your request at https://sharepoint.uservoice.com/.
