### ISSUE TITLE
Broken links due to change in PnP github structure

### ISSUE THREAD

**Issue by EagleWizard28** [SharePoint/sp-dev-docs#6920]
Several links on this page are broken due to the new structure in the PnP github.
E.g. the Core.ListItemChangeMonitor link should reference to https://github.com/pnp/PnP/tree/master/Samples/Core.ListItemChangeMonitor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954763a2-afca-5c58-a2aa-3b23b8c84db2
* Version Independent ID: 301d00a9-3ccd-446a-6b5d-49ffa8acad91
* Content: [Query SharePoint change log with ChangeQuery and ChangeToken](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/query-sharepoint-change-log-with-changequery-and-changetoken)
* Content Source: [docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Care to submit a PR to help update the docs?
