### ISSUE TITLE
Cannot download excel file.

### ISSUE THREAD

**Issue by monkeyman51** [SharePoint/sp-dev-docs#6930]
Got the Client ID and Client Secret.  Created an App with tenant help.  However, programmatically having a difficult time accessing excel file and download.

Any ideas on how to resolve this? Code in Python as listed here...

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File

ctx_auth = AuthenticationContext(main_url)
if ctx_auth.acquire_token_for_app(client_id, client_secret):
    ctx = ClientContext(main_url, ctx_auth)
    web = ctx.web
    ctx.load(web)
    ctx.execute_query()

    with open(file_path, 'wb') as output_file:
        response = File.open_binary(ctx, relative_url_2)
        output_file.write(response.content)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Can you clarify a bit what issues you are having? Is there an error happening in your code which could help us determine the issue?

**Comment by monkeyman51** [comment]
Running my code above caused it to download only 1 KB worth of data.  When clicking on the downloaded file, there was a prompt that said that it cannot open the file.  

Are there any libraries or methods that you would recommend to successfully download an excel file from a given site URL?  I cannot seem to do this programmatically despite getting the Client ID, Client Secret, and App approved by a tenant.

**Comment by bcameron1231** [comment]
Sounds like it's just corrupting the file. I normally use CSOM/C# for doing stuff like this, and not Python, so I don't have any specific examples in Python. I did find this example as part of the O365-Rest-Python Client, which uses a slightly similar, but different approach.

https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/download_file.py

**Comment by monkeyman51** [comment]
Thanks for responding and providing the hyperlink.

When I download the file, there is this error message...

{"error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /sites/[site_location]/Shared Documents/[file_name] does not exist."}}}

Worked on it and couldn't resolve it.
Any suggestions on how to resolve this?

**Comment by bcameron1231** [comment]
Are you sure the path is correct? The error seems to indicate that it can't find the file location you are passing.
