### ISSUE TITLE
SPFx Library Component clashing with IE11

### ISSUE THREAD

**Issue by kmartindale** [SharePoint/sp-dev-docs#6932]
## Category

- [X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Having issues with SPFx library component in IE 11 (now I know IE11 is antiquated, but business requirements reign supreme in this case.)

When attempting to use an SPFx Library Component in IE it appears as thought it cant find the location of the library script:

[SPLoaderError.loadComponentError]:
Failed to load component "58686212-df23-4ac2-a06f-1f98a4b026e1". Original error: Failed to load entry point from component "58686212-df23-4ac2-a06f-1f98a4b026e1". Original error: Error loading https://relative-path.invalid/portal-library as "portal-library" from https://component-id.invalid/58686212-df23-4ac2-a06f-1f98a4b026e1_0.0.1
 **Unable to load script https://relative-path.invalid/portal-library**

Is it known that Library Components don't work with IE11? Or am I doing something wrong? Does it somehow need to be listed as an external dependency for IE? Anyone seen this before and overcome it?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10 & React
- **Browser(s)**: IE v11
- **Tooling**: VS Code
- **Additional details**: The webpart package **AND** the library package are both deployed at the site collection app catalog level

#spfx, #spfx-webparts, and #spfx-tooling

**Comment by bcameron1231** [comment]
I haven't seen this. I have some library components and they work in IE11. It's working fine for you in all other browsers?

**Comment by kmartindale** [comment]
Yup completely fine. Are you hosting at the site collection level? Or do you have the library (and or webparts) in the tenant app catalog?

**Comment by bcameron1231** [comment]
It's hosted at the tenant app catalog. I have seen recently on the issues list, people having issues with their library components on the Site Collection App Catalog.

**Comment by kmartindale** [comment]
Possible, everything was working before I split out my code into a library, but I did make some changes before going back into IE because I never think of the browser.

I did go into my dev tenant and deploy the library at the tenant level with my webparts at the site collection - same issue replicated.

Also attempted with them both at the tenant app catalog level - same issue replicated.

Pasting the whole error below to see if that helps any, I appreciate you taking the time to respond. I'm thinking without breaking my library down to bare bones and building it back up there seems to be no easy way to figure out exact what the root cause is. Full Error output below, I bolded areas of interest but can't seem to find any answers. (CallToAction in this case is a web part I've built, not the OOB MS version)


Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details

[SPLoaderError.loadComponentError]:
Failed to load component "8887e217-6fd4-4b74-aa13-2e4e72841789" (CallToActionWebPart). Original error: Failed to load component dependency "8887e217-6fd4-4b74-aa13-2e4e72841789" from component "CallToActionWebPart" **(Failed to load component "951ed466-794c-4700-9aa1-03c0d7922e5c" (PortalLibraryLibrary)**. Original error: Failed to load entry point from component "951ed466-794c-4700-9aa1-03c0d7922e5c" (PortalLibraryLibrary). Original error: Error loading https://component-id.invalid/951ed466-794c-4700-9aa1-03c0d7922e5c_0.0.1
 **https://component-id.invalid/951ed466-794c-4700-9aa1-03c0d7922e5c_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.). Original error: {3}**

INNERERROR:
Failed to load component dependency "8887e217-6fd4-4b74-aa13-2e4e72841789" from component "CallToActionWebPart" (Failed to load component "951ed466-794c-4700-9aa1-03c0d7922e5c" (PortalLibraryLibrary). Original error: Failed to load entry point from component "951ed466-794c-4700-9aa1-03c0d7922e5c" (PortalLibraryLibrary). Original error: Error loading https://component-id.invalid/951ed466-794c-4700-9aa1-03c0d7922e5c_0.0.1
 https://component-id.invalid/951ed466-794c-4700-9aa1-03c0d7922e5c_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.). Original error: {3}
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:65:20220)
   at t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:65:19738)
   at t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:65:118610)
   at e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:65:156394)
   at e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:65:152433)
   at Anonymous function (https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_b3926ee2b815f08898c8.js:1:11885)
   at Anonymous function (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:1:8128)
   at R (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:1:8104)
   at C (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:1:7990)
   at T (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_20759f006f7a6f2abb9d469976dd8709.js:1:7568)

**Comment by bcameron1231** [comment]
Hi, unfortunately, I'm not seeing anything in that which would clarify the problem. You aren't seeing any other errors in your developer console (F12)?
