### ISSUE TITLE
Add x number of links to bottom placeholder?

### ISSUE THREAD

**Issue by JoelHJ** [SharePoint/sp-dev-docs#6933]
## Question
I'm new to developing with SPFX and I'm fillowing the hello world examples which really helps. Now i have managed to run the header footer dev and it works in my gulp env. Now i would like to change the SharePoint footer to have 3 links one in the left corner one in the middle and one in the right. Below is the code that I think i need to edit but lost with the strings and variables. If anyone can help a little that would be awesome. The links I would like to add are

Terms, Site Owner and Coyright. I have added them in a bit in the layout part but not sure what to do next.

export interface IHelloWorldApplicationCustomizerProperties {
  // This is an example; replace with your own property
  Top: string;
  Bottom: string;
  Terms: string;
  SiteOwner: string;
  Copyright: string;

 // Handling the bottom placeholder
    if (!this._bottomPlaceholder) {
      this._bottomPlaceholder = this.context.placeholderProvider.tryCreateContent(
        PlaceholderName.Bottom,
        { onDispose: this._onDispose }
      );
  
      // The extension should not assume that the expected placeholder is available.
      if (!this._bottomPlaceholder) {
        console.error("The expected placeholder (Bottom) was not found.");
        return;
      }
  
      if (this.properties) {
        let bottomString: string = this.properties.Bottom;
        if (!bottomString) {
          bottomString = "(Bottom property was not defined.)";
        }
  
        if (this._bottomPlaceholder) {
          this._bottomPlaceholder.domElement.innerHTML = `
          <div class="${styles.app}">
            <div class="${styles.bottom}">
              <a href="${(
                bottomString
              )}">Terms Contact</a>
           </div>
           <div class="${styles.bottom}">Site Owner: ${this.properties.SiteOwner}
              <a href="${(
                bottomString
              )}">JoelHJ</a>
           </div>
           <div class="${styles.bottom}">
              <a href="${(
                bottomString
              )}">Copyright</a>
           </div>
           </div>`;
        }
      }
    }
  }
  private _onDispose(): void {
    console.log('[HelloWorldApplicationCustomizer._onDispose] Disposed custom top and bottom placeholders.');
  }
  
}

And here is the CSS
  .bottom {
      height:27px;
      float:left;
      width:33%;
      line-height:2;
      padding-left:0px;
      display: flex;
      align-items: left;
      justify-content: center;
      background-color: $ms-color-themePrimary;
      color: $ms-color-white;
  }

  /* A link that has not been visited */
a:link {
    color: white;
}
/* A link that has been visited */
a:visited {
    color: white;
}
/* A link that is hovered on */
a:hover {
    color: red;
  }
}

## Environment details (*development & target environment*)

Windows 10
SharePoint Server 2019
SPFX
Using Chrome
Using Vscode

**Comment by bcameron1231** [comment]
Hi, can you clarify a bit where you are stuck? Do you not know how to get the properties of the extension to render as links in your component? 

Subsequently, if it's of interest to you. We have a pretty robust sample in the PnP Starter Kit of how to set up a footer with links and such. It allows for loading links from a list, so if you have updates, you don' t need to redeploy any updates. 
https://github.com/pnp/sp-starter-kit/blob/master/documentation/components/ext-portal-footer.md

**Comment by JoelHJ** [comment]
"Do you not know how to get the properties of the extension to render as links in your component?" Yes that is exaclty it.. but I shall have a look at the link you posted. I didn't see that before. I shall go through it and see what I can pick up. Thank you so much for coming back to me

**Comment by JoelHJ** [comment]
Is it ok to ask another question? I want to display the Site Owner as "Displayname" in my footer and I'm trying to use something like the below to pickup the name but I can't seem to make it work. I can pickup the current user via this method but can't seem to get the Site Owner ??? What am I missing?? 

<div class="${styles.middle}">Site Owner: ${this.context.pageContext.user.displayName}
              <a href="">Something</a>

Thank you again
Joel

**Comment by bcameron1231** [comment]
The Site Owner is not a part of the pageContext. 

The only way to retrieve the Site Owner would be to make calls to the SharePoint REST API using the SPHttpClient to retrieve values from the Owners group.

**Comment by JoelHJ** [comment]
> The Site Owner is not a part of the pageContext.
> 
> The only way to retrieve the Site Owner would be to make calls to the SharePoint REST API using the SPHttpClient to retrieve values from the Owners group.

OK thank you so much. I'm too new so this goes in the too hard basket lol. I'm tinkering and lost lol. But thank you again

**Comment by bcameron1231** [comment]
Is the console log, logging the information? You'll just need to save the responseJSON into a javascript variable. From there, you can reference that variable when loading similar to how you are up above with ${}

**Comment by JoelHJ** [comment]
Yes it does. I think i got it from here. Thank you for all your help ;-)
