### ISSUE TITLE
 SPFX Field Customizer rich-text columns do not refresh  to reflect updated content after Save

### ISSUE THREAD

**Issue by benjdayco** [SharePoint/sp-dev-docs#6937]
## Category
Bug

## Describe the bug

I have a couple of SPFX Field Customizer rich-text columns on a SP List that fail to reflect updated content after I save using a integrated Power Apps form, requiring me to refresh the browser before I see the correct content.

Non-SPFX columns are immediately refreshed to reflect my edits after I submit the form, it's only SPFX field customizer fields that fail to do so. This only happens when updating currently existing data, no issues when creating as new.

## Steps to reproduce

1. Edit an existing List item that contains SPFx Field customizer rich-text fields using a customized Power Apps List form 
2. Update aforementioned fields.
3. Save the form.

## Expected behavior

Column(s) should refresh to reflect updated content without the need to refresh the browser

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.21.0
- **Browser(s)**:  Chrome v89 
- **Tooling**:  VS Code
- **SPFx**: SharePoint Framework v1.10

### Additional context

The SPFx Field Customizer I'm using is for increasing the number of lines displayed for rich-text columns on an SP List. See code snippet below: 
  ```
  @override
  public onRenderCell(event: IFieldCustomizerCellEventParameters): void {
    event.domElement.classList.add(styles.cell);

    event.domElement.innerHTML = `
      <div class='${styles.RichText}'>
          <div  class='${styles.text} rich-text'>
            ${event.fieldValue}
           </div>
      </div>`;
    let wrapper: HTMLElement = event.domElement;
    let options = {
      ellipsis: "\u2026",
      truncate: "word",
      height: 250,
    };

    let truncate = new Dotdotdot(wrapper, options);
  }
```
After I save my edit on an spfx field customized rich-text field (Recommendation in this case) notice that the Recommendation column does not refresh to reflect the updated content:
![image](https://user-images.githubusercontent.com/19379876/115661443-075afc00-a370-11eb-83ce-c898b0838a84.png)

I need to refresh the browser first before the updated content is shown:
![image](https://user-images.githubusercontent.com/19379876/115663437-14c5b580-a373-11eb-83d5-a086b4b910ae.png)

**Comment by andrewconnell** [comment]
Please update your OP with the SPFx version you’re using.

**Comment by AJIXuMuK** [comment]
Hi @benjdayco - sorry for the long delay.
Seems like the issue has been fixed. Could you please confirm it on your end?
Thanks!
