### ISSUE TITLE
Spfx React webpart not updating on http response 

### ISSUE THREAD

**Issue by Marcos-Coca** [SharePoint/sp-dev-docs#6938]
## Error

- [x] Bug 

## Description

I create a sharepoint framework and react solution and deploy it in my tenant with the commands gulp bundle --ship and gulp package-solution --ship, but when i try see the content of the webpart is not rendering totaly, it's works but when the webpart makes an http call and retrieve the data, the webpart not display the data and stop rendering.

I checked the iframe url of the webpart and the program is executing in the url but, in the site not.

### Here's the tenant view

![115319055-faaa8e00-a14c-11eb-8ec0-321b13235993](https://user-images.githubusercontent.com/54088713/115405077-eb165e00-a1bb-11eb-905a-1e4985119e3f.png)

### This is the view in the Iframe Url

![115319458-def3b780-a14d-11eb-929f-b4d7f638f1eb](https://user-images.githubusercontent.com/54088713/115405264-16994880-a1bc-11eb-8555-3c6a07ede2a9.png)

### Where i got the Url

![115320226-786f9900-a14f-11eb-9201-f596f7990c26](https://user-images.githubusercontent.com/54088713/115405382-303a9000-a1bc-11eb-91fb-859355e2cd67.jpg)

## Environment details (*development & target environment*)

- **Developer Environment**:  Windows 10 
- **Target Environment**:  SharePoint Online
- **Framework**:  Node v10.18.0 | React 16.8.5
- **Browser(s)**:  Chrome v79 | Edge 
- **Tooling**:  VS Code | SPFx v1.10.0 

### Additional context
- In the sharepoint workbench works perfectly.
- The webpart has a loder and when makes the http call the loder execute and the requests is success but the view is not updating

**Comment by andrewconnell** [comment]
Hard to help without providing any code or repro steps. Please help us help you by including this detail.

**Comment by Marcos-Coca** [comment]
package-solution.json

![image](https://user-images.githubusercontent.com/54088713/115418457-7ea15c00-a1c7-11eb-923b-5c93d3295093.png)

write-manifests.json

![image](https://user-images.githubusercontent.com/54088713/115418653-a8f31980-a1c7-11eb-813f-13cc538659b2.png)

useFetch hook

![image](https://user-images.githubusercontent.com/54088713/115418960-ef487880-a1c7-11eb-873f-9ac38ad9f3f1.png)

would any more file be useful to you?

**Comment by Marcos-Coca** [comment]
I used the commands 
- npx gulp clean
- npx gulp bundle --ship
- npx gulp package-solution --ship

Put the files in the temp/deploy folder in the SPFxAssests document library

Uploaded the app to the app catalog

And add the aplication to the site

**Comment by bcameron1231** [comment]
Can you share any errors in the console and the network tab. With the iframe, it looks like you may be loading from another domain (an add-in?). As a result, it may be blocked from loading and you would see an error in your console stating a CORS issue. Can you confirm?

**Comment by andrewconnell** [comment]
In addition to what @bcameron1231 said, it's hard to tell what the issue could be without seeing the complete solution.

**Comment by Marcos-Coca** [comment]
This is the main file idk where is the issue but if i change the place of templaters cards and command bar templaters cards works but the command bar not

![image](https://user-images.githubusercontent.com/54088713/115467221-28500f80-a1ff-11eb-9d4e-23bf464933d2.png)

**Comment by Marcos-Coca** [comment]
Why this works and the other not?

![image](https://user-images.githubusercontent.com/54088713/115468171-ae208a80-a200-11eb-936f-3e9bac865f53.png)

**Comment by bcameron1231** [comment]
Not sure, both samples look valid (the outer div is the only difference I see?). Maybe it was just an anomaly which was fixed when you re-packaged and deployed.

**Comment by Marcos-Coca** [comment]
Yes, the div is the unique difference. Every place where i have a context provider as the highger element only render de first element but if use a div all works fine. This is a spfx error or only happens with me?

**Comment by bcameron1231** [comment]
I'm not sure. I just made a simple hello world web part with a provider, and set it up like you and it works fine for me. Does it work if you wrap it in an empty react element instead of a div? That way you don't have unnecessary html?

e.g,   <> </> instead of <div></div>
