### ISSUE TITLE
Not able to find "app@sharepoint" user on the new Term Store Admin experience

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#6943]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

On the following page: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/elevated-privileges-in-sharepoint-add-ins

It is mentioned that if you want to write to the Taxonomy term store with App Only permissions, then the `app@sharepoint` user needs to be added as a Term store admin: 

![image](https://user-images.githubusercontent.com/173794/115583476-d45a2f00-a2c1-11eb-9b27-b7d29564fdaf.png)

However, in the new term store admin experience, this user is not available in the user search:

![image](https://user-images.githubusercontent.com/173794/115583711-0e2b3580-a2c2-11eb-8827-b140d8d91886.png)

We can still use the classic Term store experience for adding this user but I assume at some point the classic experience will go away and we would be stuck in limbo.

### Steps to reproduce

1. Go to the new Term store admin experience at https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/termStoreAdminCenter
2. Click on `Edit` next to Term Store Admins
3. Search for `app@sharepoint` in the user search pane.

### Expected behavior

Ideally, there should be no need for adding the `app@sharepoint` user to the termstore admins to do write operations to the term store 😆

But in this case, the user should be searchable in the new Term store admin experience.

**Comment by Jerry0527** [comment]
The underlying principal for the app-only addin is i:0i.t|00000003-0000-0ff1-ce00-000000000000|app@sharepoint:

[https://www.techmikael.com/2018/08/modifying-terms-using-app-only-tokens.html](https://www.techmikael.com/2018/08/modifying-terms-using-app-only-tokens.html)

Copy the principal above in the Term Store People Picker and save, then will display app@sharepoint:

![Uploading image_thumb[2].png…]()

**Comment by vman** [comment]
Thanks @Jerry0527 for the response. I have tried that already and it doesn't work in the new Term store experience:

![image](https://user-images.githubusercontent.com/173794/115700895-18e7d800-a35f-11eb-863a-bcf13da6badb.png)

**Comment by andrewconnell** [comment]
Hey @vman, this doesn't look like a dev issue, rather it's a modern experience issue. As such the team that manages the "bugs" that come into this list can't address it and will say this should be submitted to either tech community/support request.
