### ISSUE TITLE
PnP Provisioning - News Webpart point to different site in template

### ISSUE THREAD

**Issue by leanclink** [SharePoint/sp-dev-docs#6945]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

PnP Provisioning Engine

### Issue description

We plan to use PnP Provisioning Engine to create our sites. So far it is working great. 

However, there is a little bit of issue with provisioning "relative" web parts.

For example, I have a tenant template that always creates 2 related sites (Parent, Child). Parent Site has a "News" webpart that should point to "Child". However, if I want to apply this tenant template multiple times, how can I point the "News" in the template to the newly created partner "Child" site?

**Comment by andrewconnell** [comment]
*AUTORESPONSE*

Thanks for your submission, but this repo is for general SharePoint development topics. Your question appears to be about a specific PnP library, tool, or project that has its own GitHub repo & associated issue list for posting questions and issues which is monitored by the people involved in that project

Please submit your question to the relevant repository so the people involved in that project can help you. Thanks!
