### ISSUE TITLE
Error while applying theme variants in SPFx web parts

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#6946]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - chrome latest
- SPFx version - 1.11
- Node.js version - 8.16.1

### Issue description

I have applied theme variants in my web part by following https://www.netwoven.com/2020/10/15/customize-spfx-web-parts-adapted-to-section-backgrounds-using-css-in-js/?unapproved=2923&moderation-hash=c8b85ec88daeab42a02298244f6c474b#comment-2923 article. This is working good when do `gulp serve`. But when I do `gulp bundle --ship` command it is giving following error. 
**Octal escape sequences are not allowed in template strings [design-test-web-part.js:5931,14]**
![image](https://user-images.githubusercontent.com/7568187/115720561-ce844c80-a39a-11eb-89d2-b05f44bddfa9.png)

I found that below line is causing issue:
`const styles = createstyles(this.props.currentThemeVariant);`
Here createstyles method is coming from below function after import.
```
import { stylesheet } from "typestyle";
import { IReadonlyTheme } from "@microsoft/sp-component-base";
export const createstyles = (theme: IReadonlyTheme) => {
  return stylesheet({
    root: {
      backgroundColor: theme.semanticColors.bodyBackground,
    },
    title: {
      color: `${theme.palette.themePrimary}`,
      fontSize: `${theme.fonts.large.fontSize}`,
    },
    subTitle: {
      fontSize: `${theme.fonts.medium.fontSize}`,
      color: `${theme.semanticColors.bodySubtext}`,
      FontWeights: `${theme.fonts.medium.fontWeight}`,
    },
    description: {
      fontSize: `${theme.fonts.smallPlus.fontSize}`,
      color: `${theme.semanticColors.bodySubtext}`,
      FontWeights: `${theme.fonts.smallPlus.fontWeight}`,
    },
  });
};
```

What is the cause of this issue?

**Comment by andrewconnell** [comment]
@StfBauer Have you seen this issue before?

**Comment by StfBauer** [comment]
I would assume that is just coding issue and uses CSS-In-JS, which limits you to simple CSS tasks.
My guess is that the compiler of typescript properly escape the backticks from.

```typescript
     //...
      color: `${theme.palette.themePrimary}`,
     //...
```

To something like this:

```javascript
     //...
      color: \`${theme.palette.themePrimary}\`,
     //...
```

Which then complains about the occtal escape sequence.

Since ther is no real reason to have the definition of a theme slot in a temlate literal. I would try the following

```JavaScript
     //...
      color: theme.palette.themePrimary,
     //...
```

@ymihir  I would change the code to the one above and see if this still happens. Officialy TypedStyles aka CSS-in-JS is neither supported or not supported.

**Comment by AJIXuMuK** [comment]
I agree with @StfBauer - most probably the coding/compiling issue. Or _maybe_ `typestyle` prod chunk has this sequence in the code.
@ymihir - could you please try what Stefan has suggested and then we can think of any additional steps if needed?
