### ISSUE TITLE
Sharepoint App crashing after uploading second time onwards

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-docs#695]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
If app uploaded to the app catalog second time onwards then we should be able to add the app in newly created subsite or any other subsite which is not having the app.

#### Observed Behavior
If app uploaded to the app catalog second time onwards then we are not able to add the app in newly created subsite or any other subsite which is not having the app. Its showing error saying that app already exists.
If all instance of this app in the site collection are removed then it will start working.

#### Steps to Reproduce
Create a SharePoint framework app, build the app and create app package, upload the app package to app catalog. Add the app to any site collection or subsite (Let be site collection name A).
Again build the app and create app package upload the app package to the app catalog.
Now we will not able to add the app in the subsite or in root site of the site collection A. it shows an error saying that app already exists, even though if there is not any app installed in particular subsite or root site.

**Comment by mcmynn83** [comment]
Thank you for the feedback.  We are trying to understand the issue more clearly, you should only be able to upgrade an app if it is already installed.  It sounds like you are trying to re-add the app and that fails by design.  Is there a reason you cannot upgrade the app?

**Comment by mcmynn83** [comment]
We have not heard a response from you so cannot help with this issue.  If you would like help with the issue please open a new thread and stating why you cannot upgrade the app.

**Comment by craghavendra21** [comment]
Hi Please let me know how to upgrade the app.
