### ISSUE TITLE
Permissions required for SharePoint Online Search Crawling

### ISSUE THREAD

**Issue by leanclink** [SharePoint/sp-dev-docs#6952]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

There is a behavior I noticed with how SharePoint Online crawls content.

I have User A and User B. User A is Global Administrator, and User B is SharePoint Administrator.

If I create a Site Collection that only User B owns / has access to, Search doesn't work for that site. I check the crawl log, and it says successfully crawled, but when I run a SharePoint Search REST API call, it doesn't return anything.

If I add User A as an administrator of the site and wait a few minutes, content is successfully crawled and SharePoint Search REST API returns something now.

Lastly, I remove User A again from the Site Collection. After few, SharePoint Search REST API is not returning anything again.

It seems there is a specific User Role which the SharePoint Online Search Service uses to crawl content?

If yes, is this documented somewhere? I cannot seem to find it.

Thank you

**Comment by andrewconnell** [comment]
Search indexes all content SharePoint & results are security trimmed for the user when they issue the query. IOW, if you can access the content, it will be visible in your search contents.
