### ISSUE TITLE
Broken Link - Fabric semantic colors documentation 

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#6954]
Speaking of permanent semantic color slots - The documentation on Fabric semantic color slots is broken and link goes to 404. ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec15970-7fbb-279f-aba9-4090256c5c7b
* Version Independent ID: 9a97664c-85b4-f1fa-728c-8e56355880f9
* Content: [Designing for section backgrounds using semantic slots](https://docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots)
* Content Source: [docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/design/semantic_slots.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment]
It looks like all the Fabric GitHub links 404 on this page because Fabric team changed their repo structure. Perhaps we should link to this current link https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/theme-slots.
