### ISSUE TITLE
Command Set Extension Base 64 Icons cause associated commands to not render.

### ISSUE THREAD

**Issue by TheLegendofXenon** [SharePoint/sp-dev-docs#6959]
I've deployed my package to the site collection level with my base-64 encoded SVG files as shown below.
The commands associated with these icons are not rendered after going through the pipeline.
If they are (which is rarely), then the icons are not loaded.
They show up in my local package in the tenant level and debug mode with the site collection level though.

`"SHARE": {
    "title": { "default": "Share" },
    "iconImageUrl": "data:image/svg+xl;base64,...",
    "type": "command"
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ba7b1f-b77a-0076-ed6c-dd84bbc104ea
* Version Independent ID: d7cc472b-1c5b-fd7b-f7dc-6add54dd0886
* Content: [Configure extension icon in SharePoint Framework (SPFx) Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/configure-extension-icon)
* Content Source: [docs/spfx/extensions/basics/configure-extension-icon.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/configure-extension-icon.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
Hi @TheLegendofXenon - sorry for the delay.
I've just tested an svg button and it works as expected.
From your description I see a missing `m` in the data type. It should be: `data:image/svg+xml;`

Please, let us know if it's still an issue for you.
