### ISSUE TITLE
🐞 Loading indicator not showing in any in base DOMElement

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#696]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
All samples using the loading indicator show it being added to the `this.DOMElement`, then using a timeout to remove it within a web part's `render()` method.

#### Observed Behavior
The loading indicator isn't showing in the local or SPO hosted workbench. 

The only way I was able to get it to appear was to add an element within the `DOMElement`, then put the loading indicator in that... similar to how [this post](https://thechriskent.com/2017/05/22/taking-advantage-of-the-loading-indicator-in-the-sharepoint-framework/) does it.

It appears nothing is being added to the `this.DOMElement` when the loading indicator is added.

#### Steps to Reproduce
Look at this sample within your own training materials linked below. It should show the loading animation for 2s, then an error for 2s, then clear and show a web part. The first step (the loading animation) never renders.

https://github.com/OfficeDev/TrainingContent/tree/master/SharePoint/SharePointFramework/02%20Deep%20Dive%20of%20the%20SharePoint%20Framework/Demos/helloworld-webpart

**Comment by chackman** [comment]
Thanks for your feedback; we're investigating this issue.

**Comment by chackman** [comment]
The issue should be fixed and will be rolling out in an upcoming build.  If it's not fixed within the next week, please open a new bug.   Thanks!
