### ISSUE TITLE
Exceeded 5000 item limit in SharePoint

### ISSUE THREAD

**Issue by Zwartlk** [SharePoint/sp-dev-docs#6960]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Scenario: We exceeded the 5000 items limit in SharePoint in the threshold list.
Solution: we add indexes to existing columns (Title). But we don't know the limitation 
1. How many items can be acquired when an index is set for a column with API filter? 
   let items = await sp.web.lists.getById(this.listId).items.filter(`Title eq '${title}'`).top(?) **** [?] is the number of items
.... 
2. How many items can be indexed? For example, we have a list with 20000 items. It's ok if we index all items. But I wonder if Indexing works when we have 3000000 items on the list.
....
3. If we have 3000000 items (index column Title). Then i use api 
sp.web.lists.getById(this.listId).items.filter(`Title eq '${title}'`).top(5000). Will it work normally?
....

**Comment by andrewconnell** [comment]
To address the 5000 item limit, you must first filter the query before selecting results. The `top()` operator does not apply as it will be working from the result set larger than 5000... you must first filter to get the result set down below 5000 before you can do more work with it.

Indexes won't address this limitation. Filters or list views are the way to get the result set.

The code in your OP appears to be PnPJS... unsure if they apply he `$filter` operator to the query before issuing the query, so you should look at the underlying REST request it's generating, or post the question how they are handling it to their PnPJS repo issue list.
