### ISSUE TITLE
A Newly Created 2nd Web Part Not Trusted on Local Machine After gulp trust-dev-cert  run for new part

### ISSUE THREAD

**Issue by Tobor58** [SharePoint/sp-dev-docs#6962]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Google Chrome is up to date
Version 90.0.4430.93 (Official Build) (64-bit)

+-- @microsoft/generator-sharepoint@1.11.0
+-- gulp@4.0.2
+-- npm@6.4.1
`-- yo@4.0.0

PS D:\VSCodeSPParts> node -v
v10.13.0

### Issue description

This is question
I have successfully created a hello world once - gulp serve / gulp trust-dev-cert / success saw the local workbench etc. no issue.

I created a 2nd new web part in different directory and attempted to serve the new part and could NOT see the part on local workbench etc.
attempts to run gulp trust-dev-cert for the NEW part complete but no new cert is seems to be created I am not prompted to accept the new cert etc. no matter what happens the new part cannot be viewed on the machine I developed it on using the local workbench.
The gist of this is:
The previously developed part works on the local bench - the new one won't.
I can use the workbench of my SharePoint site (on Prem) to view the NEW part no issue - so I know the part works.

Do I need to delete the previously created cert - then create a NEW cert for the new project?
How can I correctly identify the previously created DEV cert and remove it correctly if I need to?
Thank you.

**Comment by andrewconnell** [comment]
This seems like a dupe from the ongoing #6703... let's keep things consolidated to the one issue...
