### ISSUE TITLE
Missing how to update the gulpfile

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#6964]
Hi, I think in the release notes for 1.12.1, it is missing that we need to update the gulpfile.js in order to run gulp serve.

The gulfile.js generate with yeoman for 1.12.1 is the one described in this article: 
https://docs.microsoft.com/en-us/answers/questions/328495/pnp-spfx-breadcrumb-webpart-got-34gulp-serve-refer.html

and it contains this line   
result.set('serve', result.get('serve-deprecated'));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a6341f-3625-3bd1-151a-8fdb057b7295
* Version Independent ID: ad6d6b0c-3d46-adff-6e71-7ca9fca7dede
* Content: [SharePoint Framework v1.12.1 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1)
* Content Source: [docs/spfx/release-1.12.1.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.12.1.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
This isn't necessary... that applied to SPFx v1.12.0 which was pulled & resolved in v1.12.1.

**Comment by andrewconnell** [comment]
I stand corrected... @Rafaelki you're correct... that _is_ required. I'll get the docs updated to include it when upgrading pre-1.12.1 projects.

**Comment by Rafaelki** [comment]
Thank you very much :)
