### ISSUE TITLE
Your advice about hint text

### ISSUE THREAD

**Issue by HGlavina** [SharePoint/sp-dev-docs#6965]
Hint text that appears in the  actual field is not accessible. It disappears for keyboard-only users when they tab into the field.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54672664-e60c-5c8b-6925-626f7b95f682
* Version Independent ID: ff29c702-6b71-f901-811e-52fd545a0f4e
* Content: [UI text guidelines for SharePoint web parts](https://docs.microsoft.com/en-us/sharepoint/dev/design/ui-text-for-web-parts)
* Content Source: [docs/design/ui-text-for-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/design/ui-text-for-web-parts.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by StfBauer** [comment]
In general the proper term for "Hint Text" is Placeholder text. As the real name suggests it is just a placeholder that gives an example of what should be entered in this field it should not be used as a label. 
In most assistive technologies the placeholder will be ignored anyway.

By label the field using "Website address or embed code" the field is labelled correctly.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/5503835/116789644-282dfa80-aab0-11eb-87b2-dae5cb1cad70.png">


More on placeholder please check out the official [WAI guidance](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text)

You are correct that the hint text is not accessible at all but I would not follow the guideline in this way. It is too vague.

There are more considerations to this actually the label should have a reference to the actual file too using `aria-labelledby`.
