### ISSUE TITLE
Overriding OOTB links using SharePoint Framework Extension

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#697]
#### Category
- [ ] Question

What is the correct way to override the highlighted sections in SharePoint Framework Extension? 

Business Use Cases 
1) Custom site request form 
2) Custom list forms

![snip20170705_1](https://user-images.githubusercontent.com/21008316/27885528-efe8d348-619d-11e7-98da-5424dad8db81.png)
![snip20170705_2](https://user-images.githubusercontent.com/21008316/27885527-efe73056-619d-11e7-9602-790580df8c7a.png)
![snip20170705_3](https://user-images.githubusercontent.com/21008316/27885526-efe679ea-619d-11e7-8f7f-d681732a19c2.png)

**Comment by mcmynn83** [comment]
Thank you for your feedback however at this point in time this is not supported by the extension framework.  Custom provisioning for lists and sites is a well known requirement but at this point we do not have a timeline for this.

**Comment by sprider** [comment]
The only option we have right now is to play with DOM elements which is not recommended by Microsoft as it will affect the future updates.
