### ISSUE TITLE
SharePoint alert me fuctionality in SPFx

### ISSUE THREAD

**Issue by rsreeraj** [SharePoint/sp-dev-docs#6971]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc
React

### Issue description

I am trying to create List alert using react in SPO SPFx solution. Basically I need to create a webpart with button control. When user click on the button user alert needs to be created for the list. 

Could you please help to build it.

**Comment by michaelhan-1** [comment]
You could use SharePoint rest api to create the alert: `_api/web/Alerts/Add(...)/`. Refer to: https://s-kainet.github.io/sp-rest-explorer/#/_api/web/Alerts/Add

Here is a similar question: https://sharepoint.stackexchange.com/questions/262556/create-list-alert-using-rest

**Michael Han
Microsoft SharePoint Community Support**

**Comment by rsreeraj** [comment]
I gone through the article  https://sharepoint.stackexchange.com/questions/262556/create-list-alert-using-rest,. still Iam not getting it worked. Could you please advice.

Sreeraj R

**Comment by michaelhan-1** [comment]
You could try this jsom code to add the alert: https://gist.github.com/beckettkev/6f3389963294aa1b566a59fde48dc245

This has been solved here: https://github.com/SharePoint/sp-dev-docs/issues/4883
