### ISSUE TITLE
【List Formatting】Sample Code - Unnecessary padding

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#6978]
The "padding" in the code shown in the example (Color coded group header with aggregate) may be unnecessary.

![image](https://user-images.githubusercontent.com/51254139/117001766-b3f88e80-ad1d-11eb-8395-5abb590360c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by thechriskent** [comment]
Totally agree! Would you be willing to make the change and submit it as a pull request?
