### ISSUE TITLE
httpClient request authorization token header not working

### ISSUE THREAD

**Issue by omarelanis** [SharePoint/sp-dev-docs#6983]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome Version 90.0.4430.93 (Official Build) (64-bit)
- Edge Version 90.0.818.51 (Official build) (64-bit)
- Node JS v10.24.0
- SPFx 1.11.0
- Gulp 3.9.1
- NPM 6.14.11
- React-devtools 4.10.1
- Yo 3.1.1
- Postman v8.3.0

### Issue description

I am using the httpClient control to send a query to an AAD secured Azure function that calls an external API to retrieve an OAuth token, this token is then sent back to the SPFx webpart and stored in cache for a timeout period (or at least will be), Using this authorization token I am then trying to call the external 3rd party API using this authorization token in the header, however the http request that is sent is completely missing the "Authorization: Bearer xxxx" header

My code I am using is as below:

```typescript
private GetToken(token: string): Promise {
   const postURL = "https://api.badgr.io/v2/issuers";
   const requestHeaders: Headers = new Headers();
   requestHeaders.append('Content-type', 'application/json');
   requestHeaders.append('Cache-Control', 'no-cache');
   requestHeaders.append('Authorization', 'Bearer '+token);
   const httpClientOptions: IHttpClientOptions = {
      headers: requestHeaders,
      method: "GET",
      mode: "no-cors"
   };
   console.log("About to make REST API request.");
   return this.context.httpClient.get(
      postURL,
      HttpClient.configurations.v1,
      httpClientOptions)
   .then((response: HttpClientResponse): Promise => {
      console.log("REST API response received.");
      if (response.ok) {
         return response.json();
      } else {
         alert('Badgr could not authenticate you!');
      }
   });
}
```

Calling the same exact headers to the API using Postman works fine, but whenever I try from within the webpart I get an unauthorized error because the authorization header is not being included in the request.

I thought maybe it was an issue with the Headers casting not working how it should so I tried including the header in the call code directly but this time the authorisation header is generated but the token is replaced with the text "Authorization" 

Code:

```typescript
return this.context.httpClient.get( postURL, HttpClient.configurations.v1, {headers: { 'Authorization': 'Bearer xxxxxxxxxxxxxxxxxxx' }, method: "GET", mode: "no-cors" }) 
.then((response: HttpClientResponse): Promise => { 
console.log("REST API response received.");
 if (response.ok) {
        return response.json();
     } else {
        alert('Badgr could not authenticate you!');
     }
}); 
```

And with the Header casted to string[][] like this it just excludes the authorization header entirely:

```typescript
return this.context.httpClient.get(
postURL,
HttpClient.configurations.v1,
{headers: [[
'Authorization', 'Bearer xxxxxxxxxxxxx'
]],
method: "GET",
mode: "no-cors"
})
.then((response: HttpClientResponse): Promise => {
console.log("REST API response received.");
     if (response.ok) {
        return response.json();
     } else {
        alert('Badgr could not authenticate you!');
     }
 });
}
```

This is the HTTP request from the browser with the Authorization header showing when I use the second code of directly adding the authorization header into the httpClient.get() code

![image](https://user-images.githubusercontent.com/35841910/117037774-c31c1400-acfe-11eb-8285-8c7a760ce931.png)

All i want to do is include the authorization bearer token in the header message being sent so the request can be authorised by the third party API and a response can be received back, any guidance would be greatly appreciated as hitting a brick wall here.

*edited by @andrewconnell - changed code listings from blockquotes => fenced. Please see [How to Create Good Issues | Use code formatting (inline & blocks)](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#use-code-formatting-inline--blocks) for reference*

**Comment by andrewconnell** [comment]
Your 1st snippet has an error in the headers... you're submitting an HTTP GET but telling it what type of data you're sending (header=`content-type`)... that should be `accept` (what type of data you support in the response). The content type header only makes sense when you're submitting (POST/PUT/MERGE) to the endpoint. Further, there's no need to set the `method` in the request options... you're already doing that using the `.get()` method. Finally, if your endpoint can't authenticate, it won't respond with an "OK" (ie: 200)... so your `else` in your `if` statement will never get hit... because the response will be a 401/403.

Your 2nd snippet appears correct, but to help, need to see the exact request & response (from the browser's NETWORK tab).

Your 3rd snippet isn't valid... the request `headers` is an object that should be passed in & it contains name-value pairs, not an array.

Not sure what the screenshot is from... suggest replacing your first snippet with the following, then running it again, but look at the NETWORK tab in your browser's dev tools, and inspect the headers sent.

```typescript
private GetToken(token: string): Promise {
   const postURL = "https://api.badgr.io/v2/issuers";
   const httpClientOptions: IHttpClientOptions = {
      headers: {
      'accept', 'application/json',
      'cache-control', 'no-cache',
      'authorization', 'Bearer '+token
     }
   };
   return this.context.httpClient.get(postURL, HttpClient.configurations.v1, httpClientOptions)
   .then((response: HttpClientResponse): Promise => {
      console.log("REST API response received.");
      if (response.ok) {
         return response.json();
      } else {
         alert('Badgr could not authenticate you!');
      }
   });
}```

**Comment by omarelanis** [comment]
Thank you @andrewconnell for taking the time to review and answer, you are right about the content-type header, it's copied from a previous post query I used and forgot to remove!

Technically none of the headers except for the authorization one are needed, even if I strip it down to bare minimal the authorization header is not included in the request that is sent (I had to modify the code you used slightly as headers need to be separated by colons not commas:

```
private GetToken(token: string): Promise<HttpClientResponse> {

    const postURL = "https://api.eu.badgr.io/v2/issuers";
    
    const httpClientOptions: IHttpClientOptions = {
      headers: {
        'authorization': 'Bearer '+token
      },
      mode: "no-cors",
    };
     
    console.log("About to make REST API request.");
  
    return this.context.httpClient.get(
      postURL,
      HttpClient.configurations.v1,
      httpClientOptions
      )
      .then((response: HttpClientResponse): Promise<HttpClientResponse> => {
        console.log("REST API response received.");
        
        if (response.ok) {
          return response.json();
      } else {
        alert('Badgr could not authenticate you!');
      }
      });
  }
```

![image](https://user-images.githubusercontent.com/35841910/117321714-4cf5e980-ae85-11eb-9d5c-8b63c4bab597.png)

But as you can see from the sent request there is no authorisation header included in it :(

I have to use the no-cors mode as the host is outside of the SharePoint domain, not sure if this is what's causing the issue here but then the whole point of the httpClient module is to allow anonymous 3rd party APIs to be called so wouldn't make much sense if we can't include authorisation headers in no-cors requests.

I have spent hours googling this and trying lots of different methods but have not had any luck, I have ended up doing all of the querying on the azure function and sending back the response from azure to the webpart but it all seems like a lot of overkill for what should work in SharePoint.

It would be good to know if this is a glitch with httpClient whilst in no-cors mode or if it's something else causing it.

As a workaround I have ended up building the full query in the Azure Function and passing the response back to SPFx but it means I can't take advantage of browser caching which is a shame

Azure code works fine but does have CORS enabled:

```
        var issuerClient = new HttpClient();
        issuerClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + e.access_token);

        var responseissuer = await issuerClient.GetAsync("https://api.eu.badgr.io/v2/issuers");

        var contentIssuer = await responseissuer.Content.ReadAsStringAsync();
        var f = JsonConvert.DeserializeObject<IssuerClass>(contentIssuer as string);
```

**Comment by AJIXuMuK** [comment]
Hi @omarelanis - sorry for the long delay.
`"mode": "no-cors"` leads to this behavior. And this is default browser behavior, not something added by SPFx.
(You can test it by doing `window.fetch`).

If you're using `no-cors` you can set "safe" headers only. And `authorization` is not one of them.
