### ISSUE TITLE
Inaccurate "void" in Gallery.tsx causes build to fail

### ISSUE THREAD

**Issue by katjones23** [SharePoint/sp-dev-docs#6985]
Using the code provided in **Web parts** > **Concepts & scenarios** > **Preconfigure web parts** > **Add web part properties.**

Step 5 "Update the main React component...", code on line 6 reads:
`export default class Gallery extends React.Component<IGalleryProps, void> {`

However, once I got down to **Add localization labels** step 4 (gulp serve), the build failed with error "Error - [tsc] src/webparts/gallery/GalleryWebPart.ts(26,76): error TS2345: Argument of type 'typeof Gallery' is not assignable to parameter of type 'string | ComponentClass<IGalleryProps, any> | FunctionComponent<IGalleryProps>'."  The error was resolved and the build was successful when I changed line 6 to be:
`export default class Gallery extends React.Component<IGalleryProps, {}> {`

[Add web part properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#add-web-part-properties)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3043faa1-f278-c483-17f4-e1af81d9b097
* Version Independent ID: df4b13b3-4c12-0592-7f29-f54075807c3b
* Content: [Simplify adding web parts with preconfigured entries](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries)
* Content Source: [docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by omarelanis** [comment]
You are adding the code from Step 5 to the wrong file, it should be added in the webpart file ./src/webparts/gallery/components/Gallery.tsx and not the main ts file in  src/webparts/gallery/GalleryWebPart.ts

Can you check you have followed the steps correctly?

**Comment by katjones23** [comment]
Yes, I was working in ./src/webparts/gallery/components/Gallery.tsx

**Comment by KevinTCoughlin** [comment]
FWIW most current TypeScript React documentation opts for `{}` over `void` for the absence of state or props. Tho I am unable to repro the compiler error with `void` reported above.

https://www.typescriptlang.org/play?target=2&ts=4.2.3&strict=true#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4Aoc4AOxiSk3STgEkBxFAG0-oE8AFHGADOcAN4BfCuSQAPSLDgATJIwCuneGk4phojtz5w5daktHJ0MAHQBhXJGpJaAHnZceUAUOEAaOABuEMBKAHzilBJAA
