### ISSUE TITLE
SPFX React Control- FilePicker

### ISSUE THREAD

**Issue by Abhijeet1719** [SharePoint/sp-dev-docs#6986]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I want to add Custom Link  in File Picker control (using spfx react) in SharePoint Modern Ui. Now we are able to see below options
"Recent files - tab allows selecting a file from recently modified files based on the search results.
Web search - tab uses Bing cognitive services to look for a file. (Only images)
OneDrive - tab allows selecting a file from the user's One Drive.
Site document libraries - tab allows selecting a file from the existing site document libraries.
Upload - tab allows uploading a file from a local drive.
From a link - tab allows pasting a link to the document."
Is it possible to add subsite name in above navigation.

![image](https://user-images.githubusercontent.com/65273665/116968229-b33a0b00-acd1-11eb-96b0-d4df4d6ca00a.png)

**Comment by bcameron1231** [comment]
Hi! Thank you for the question. Are you using the out of the box filepicker, or the custom one from the PnP Reusable Controls team? If out of the box, no you can't make changes to it. 

If you are using a the custom one from PnP, You may find better support if you check out the team over on the PnP Re-usable Controls Repository... https://github.com/pnp/sp-dev-fx-controls-react/

https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/

**Comment by Abhijeet1719** [comment]
> Hi! Thank you for the question. Are you using the out of the box filepicker, or the custom one from the PnP Reusable Controls team? If out of the box, no you can't make changes to it.
> 
> If you are using a the custom one from PnP, You may find better support if you check out the team over on the PnP Re-usable Controls Repository... https://github.com/pnp/sp-dev-fx-controls-react/
> 
> https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/

**Comment by Abhijeet1719** [comment]
I am using Custom File picker control and want to add Links on Navigation tab.

**Comment by andrewconnell** [comment]
@Abhijeet1719 this question seems specific to the PnP React controls... please post to that projects issue list as this repo is for general SharePoint development questions.
