### ISSUE TITLE
Filter the default modern list view through a custom spfx webpart

### ISSUE THREAD

**Issue by Link631** [SharePoint/sp-dev-docs#6989]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.4.1
- Node.js version node 10.x

### Issue description

Hi,

when we add two listview webparts they can get connected with dynamic filtering. One webpart can filter another list view webpart. Those webparts are placed on a modern site.

Question:
Does someone know if it is possible to trigger those filters through a custom spfx webpart ie by providing a dynamic datasource? For example, the custom spfx webpart provides a button and a datasource. The out of the box listview webpart  can get configured so that it receives a filter from my custom webpart. Is that possible? And if it is, which properties whould I need to describe my datasource?

Thanks.

Thanks...

**Comment by AJIXuMuK** [comment]
Hi @Link631 - sorry for the long delay.
Unfortunately, it's not possible. The List Web Part is implemented in such a way that you can connect it to another List Web Part only.
