### ISSUE TITLE
Page and instructions out of date.  SPFx 1.12

### ISSUE THREAD

**Issue by Campbellds1991** [SharePoint/sp-dev-docs#6991]
The page is out of date.  Please update for serve-deprecated.  Instructions for using none deprecated methods are not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment]
This tutorial begins with generator scaffolded output which contains a gulpfile that aliases `gulp serve-deprecated` to `gulp serve` for back compat.

```js
const build = require('@microsoft/sp-build-web');

var getTasks = build.rig.getTasks;
build.rig.getTasks = function () {
  var result = getTasks.call(build.rig);

  result.set('serve', result.get('serve-deprecated'));

  return result;
};

build.initialize(require('gulp'));
```

**Comment by andrewconnell** [comment]
In addition to @KevinTCoughlin's comment, we have another PR to be merged that will add this step to the release notes for 1.12.1.
