### ISSUE TITLE
403 trying to set WelcomePage using the _api/web/rootfolder

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-docs#6993]
Have experienced this in 2 tenants and want to check if this is happening elsewhere

Steps to reproduce
You are the owner of the site
post a call to: https://yourtenant.sharepoint.com/sites/test-a-roni/_api/web/rootFolder
with body
{
  "__metadata": {
    "type": "SP.Folder"
  },
  "WelcomePage": "SitePages/new-page.aspx"
}

on both tenants i receive the 403 (it seems that the welcomepage gets set though)

**Comment by tarjeieo** [comment]
Seeing the same in multiple tenants as of today...

**Comment by wobba** [comment]
@trillian74 @tarjeieo can you check if it works now?

**Comment by tarjeieo** [comment]
Works! 🥳

**Comment by trillian74** [comment]
Works @wobba . thanx - always interesting to know why it happend? ;)

**Comment by wobba** [comment]
@trillian74 Setting the home page did actually work, but for some weird reason it returned 403 and not 200 when some new code was added. Looking at the code it was super-weird and we are investigating it - and appreciate you logging this so we could pull the plug on the change.
