### ISSUE TITLE
List Command Set interaction changes the current page's title.

### ISSUE THREAD

**Issue by TheLegendofXenon** [SharePoint/sp-dev-docs#6995]
ListView Command Set interaction (list item selection or various toolbar presses) changes the current page's title? How would I prevent it from doing so all the time? 

Notes: I have prevented some title changes by setting my own title in the onListViewUpdated() method for Custom Command Sets (implementing BaseListViewCommandSet).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
Hi @TheLegendofXenon!
Thank you for reporting this issue!
Could you please provide some details/code you're using in the Command Set?
