### ISSUE TITLE
List form configuration via PnP?

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#6996]
Hi,

Any chance the list form configuration (as described in  [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration) article) will come to PnP soon?

best regards
Kinga 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
This question is better suited to the specific PnP project you're asking about as PnP encompasses a LOT of projects.
