### ISSUE TITLE
New SharePoint Full Page "App" tab redirects to another page 

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#6998]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser: Edge Version 90.0.818.56 (Official build) (64-bit)
- browser: Chrome 90.0.4430.93 (Official Build) (64-bit)90.0.4430.93 (Official Build) (64-bit)
- SPFx: 1.10.0 / React 
- Node.js version: 10.22
- I am a tenant SharePoint Admin and a site owner of the sites tested
- The behavior is reproducible with the basic "Hello World" webpart
- The behavior is new to the tenant since roughly a week ago

### Describe the bug / error

After deploying a SharePointFullPage  enabled webpart I am unable to select the app as a new page app. The app tab redirects to a different URL before I can select the app. This problem is new to our tenant since roughly mid last week (5-5-2021) 

![problem](https://user-images.githubusercontent.com/3818517/117729241-cb18ff80-b1a7-11eb-9cba-de2f547998f2.jpg)

### Steps to reproduce

1. Create the standard "Hello World" web part
2. Set supportedHosts to ["SharePointWebPart","SharePointFullPage"] in the web part manifest
3. Bundle and package the solution
4. Add the solution to the tenant app catalog
5. Add the app to a site
6. From the "Modern" home page choose New -> Page
7. **Clicking the "App" tab causes the page to redirect, disallowing the selection of the app**.

### Expected behavior

Clicking the "App" tab should allow the user to select the installed SharePointFullPage enabled web part.

**Comment by OliverZeiser** [comment]
I can confirm that issue. We are seeing the same thing.

**Comment by GrahamMcMynn** [comment]
@jaredbuttars - we have fixed this issue and it is currently being rolled out.  It should be fixed in production on your tenant in 1-2 weeks.

**Comment by GrahamMcMynn** [comment]
I found a way to mitigate this immediately.  This should now be working.
