### ISSUE TITLE
Tutorial can't build due to massive number of Duplicate identifier errors

### ISSUE THREAD

**Issue by chrisculver701** [SharePoint/sp-dev-docs#70]
First time user of node and type script.
I went though the Visual Studio tutorial.
Was able to work though most of the issues I ran into. Will note some discrepancies from the tutorial at the end.
Biggest issue now is over 800 Duplicate identifier. Most in index.d.ts, and node.d.ts. Both under typings.
I did add "exclude": ["node_modules"] to my tsconfig.json
there are 3 index.d.ts under typings\globals. One for gulp, one for node and one in the root of globals
Do I need to ignore some of these typings?

Some inconsistencies in the tutorial:
1. It tells you to update the gulpfile.js Change let to var. Currently they are const instead of let. I tried both var and const.
2.  The project name is listed as hello-vs-webpart while it is currently downloaded as helloworld-webpart.
3. Creating a new solution with the same name creates it with a 1 at the end. Do we just delete the old solution file?  The reason I did the create solution is the fact that when compiling the existing solution it looks for the gulptovs.js file. Found this under the closed issues. 
4. the C++ Common Tools for Visual C++ 2015 part of Visual Studio 2015 is required but this isn't installed by default. Would be a good note to have.

I am really enjoying this tutorial and looking forward to making web parts with the new SharePoint Framework.

Also some errrors that i haven't looked into at the end of the build.
![image](https://cloud.githubusercontent.com/assets/1316190/17939584/ec45c3b8-69f0-11e6-8059-2d27db2c0db8.png)

**Comment by mike-morrison** [comment]
Did you run into an issue that caused you to install typings?  All of the typings should have already been in place and ready to go?  Most likely the typings installed by typings are conflicting with the typings installed already by TSD.  You can use typings to add things you are adding to the project, but you shouldn't need to install typings for the libraries that were installed by yeoman (yo).

**Comment by chrisculver701** [comment]
Thanks for the response!
I installed them thinking it would fix something else I was seeing with duplication. I'll delete the project and re-download the project with yo and see what i get.

**Comment by chrisculver701** [comment]
Only one build error now. "Build: Cannot find module './HelloWorld.module.scss'. in HellowWorldWebPart.ts line #8. _import styles from './HelloWorld.module.scss'; 
The file is there. Quick research shows others having similar issues but I don't understand the fix.
Any suggestions?

**Comment by mike-morrison** [comment]
The fix is to just gulp serve again I believe.  

@patmill The generator should provide a precompiled version of this file or compile the file during the npm postinstall.  @chrisculver701 just spent some unnecessary time trying to troubleshoot it. :8ball:

**Comment by chakkaradeep** [comment]
I am experiencing issues with VS integration at the moment as well and @chrisculver701 you are spot on the error:

```
"Build: Cannot find module './HelloWorld.module.scss'.
```

Will investigate more and update this thread.

**Comment by chrisculver701** [comment]
Any idea on when an update for this will be available?
Thanks,

**Comment by nickpape-msft** [comment]
The fix is to run `gulp`. That file (`Helloworld.module.scss.ts`) is generated during the build, based on the contents of the sass file.

I've updated the generator to include a precompiled version of this file. This should be included in the 3rd drop. Note, however, that if you run `gulp nuke` and delete this file, you will get the Visual Studio error again.

We will close this issue in drop 3.

**Comment by HeToC** [comment]
I still get over 200 ts errors and cant build sample solution with visual studio (((

**Comment by Jean-Baptiste-Wirth** [comment]
Hi, I'm following the "helloworld-webpart" tutorial and get same kind of issue.

I'm really confused by the thread and the answer about the typings being new to TS.

I used the yo @microsoft/sharepoint to create the solution, then executed "gulp serve" and got typescript errors
![image](https://cloud.githubusercontent.com/assets/24548359/21146205/23388326-c151-11e6-9228-65c6729ef6b0.png)

So I opened the solution with Visual Studio 2015 (community edition) and tried to build from there and received same kind of errors but even more confusing. Errors refer to stuff in file index.d.ts and when I open the file, it is basically empty.
![image](https://cloud.githubusercontent.com/assets/24548359/21146449/fa86f13c-c151-11e6-8016-1c285842bed0.png)

Guidance here would be highly apreciated, thanks in advance :)

**Comment by Jean-Baptiste-Wirth** [comment]
Hi, replying to my own question if someone runs into the problem.
I actually missed 1 small step of "https://dev.office.com/sharepoint/docs/spfx/set-up-your-development-environment" 

"If you are using a PC..." run npm install -g --production windows-build-tools

After this, gulpe serve is working fine.

**Comment by Jean-Baptiste-Wirth** [comment]
Hi, replying again to my own reply. I actually reproduce the problem again.
After running yo @microsoft/sharepoint, the "gulp serve" command works fine and I have access to the hello-world webpart in the workbench.

After opening the solution with visual studio 2015 (community edition), I reproduce the problem.

So it seems that openning with Visual Studio somehow corrupts the code, can you advise how to fix this and continue working?

Let me know if further information is needed

**Comment by chakkaradeep** [comment]
For Visual Studio, please refer to this thread #291 for the workaround. VS unfortunately uses its own npm and TS versions which causes confusions.

**Comment by VesaJuvonen** [comment]
This should no longer be an issue, so closing it.
