### ISSUE TITLE
How to add modern document to a sharepoint with toolbar and search  similar to a webart 

### ISSUE THREAD

**Issue by AnassKartit** [SharePoint/sp-dev-docs#700]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea 

####  Desired Behavior
How can I integrate the modern document library with toolbar into a sharepoint page along with other apps in modern pages. I looked into SPFX but I was not able to find the answer in customization section.

**Comment by chakkaradeep** [comment]
@AnassKartit can you please update the template with your specific ask/issue/question and remove the rest? Thanks!

**Comment by chackman** [comment]
We have list view and document library web parts that are in preview, available worldwide.  More information can be seen in this blog post:

https://techcommunity.microsoft.com/t5/SharePoint-Blog/Introducing-SharePoint-modern-list-library-web-parts/ba-p/64581
(Note: the blog post from April says 'First Release' but it's now rolled out, in preview, for all customers.)


If you're asking about something else then please open a new issue.

**Comment by AnassKartit** [comment]
Thanks for your answer, I tried integrating the new webpart for document library in a page, but the toolbar is not there? my question is it available , if not when would it be available please. Than you

**Comment by betrue-final-final** [comment]
@chackman , I would check with Aditi Mandal on the release timing.

**Comment by chackman** [comment]
Sorry about the confusion here.
The List and Document Library web parts should be available, and you can add them to a page using the toolbox, With that said, the web parts are in a preview state.

Could you explain what you mean by "the toolbar"?  Are you saying that the web parts were not available when you tried to add them to the page, or is there a specific feature that you are asking about?

**Comment by AnassKartit** [comment]
sorry for the confusion in names, I mean when you add the new library app/webpart to a modern page , you cannot interact with the file or folder (copy, move to , share..)
[//i.imgur.com/1AHKq1M.png](url)

**Comment by betrue-final-final** [comment]
Yes, I don't think that commanding is built yet.

**Comment by AnassKartit** [comment]
is it a task in progress with an expected shipping date even preview?
Thanks

**Comment by betrue-final-final** [comment]
Yes. I will have to ask the engineer when.

**Comment by AnassKartit** [comment]
Any update on the this, as we need to find a solution . Thanks
