### ISSUE TITLE
Field customizer and Command set extension event listitem field values missing empty required fields for all documents after uploading new document

### ISSUE THREAD

**Issue by patrikhellgren** [SharePoint/sp-dev-docs#7001]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 92.0.878.0
- SPFx version Tested with 1.10 and 1.12.1
- Node.js version Tested with 10.15.3 and 14.16.1

### Describe the bug / error

The onRenderCell and onListViewUpdated events does in some cases not return empty required fields as it normally does.

### Initial scenario:
I have a document library with required fields which are **not** made visible in the view.
I have a field customizer configured for another field that is not required and that field is visible in the view.
I have a command set extension configured for the library.
Both the field customizer and the command set extension are dependent on getting values (empty or not) from the required fields.
The field customizer can read the field values for the required fields in onRenderCell from event.listItem on every page reload so this works as expected.
The command set extension can read the field values for the required fields in onListViewUpdated from event.selectedRows on every page reload so this also works as expected.

### The problem:
Now we get to the problematic part, consider the following scenario:
1. There are already a few documents in the document library view.
2. The existing documents does not have values in the required fields.
3. I upload a new document to the library by using the upload button.
4. When the new document becomes visible in the view **ALL** field customizers re-renders and this time **ALL** empty required fields are gone from event.listItem.
5. If I now select an item so that onListViewUpdated in the command set extension gets called, **ALL** empty required fields are gone from event.selectedRows.
6. If I now reload the page everything is back to normal again and the events have all empty required fields again until I upload another document.

### Summary:
I can reproduce this in multiple tenants.
I can see that this is also an issue for the out of the box experience with the “Missing required info” icon in the file name column. This also disappears when this happens.
This issue does not seem to happen if the required columns are visible in the view but that is not an option if you have many required columns.

### Steps to reproduce:

1. Create a new field customizer using the yeoman generator
2. Create a new document library
3. Create a new text column named FieldCustomizer in the library and make it **not required**
4. Create a new text column named RequiredField in the library and make it **required**
5. Now make sure that RequiredField is removed from the view so that it is **not visible** in the view but available in the library
6. Configure launch.json so that you have a debug configuration that loads the page with the document library and also loads the field customizer in the FieldCustomizer field
7. Start debugging so that the page with the library opens in the browser
8. Upload a document without setting any values
9. Set a breakpoint in the onRenderCell method
10. Reload the page
11. This will now display the “Missing required info” icon in the documents Name column and when the breakpoint is hit you will see that event.listItem contains the RequiredField field with an empty value as it should
12. Now upload another document
13. This time the “Missing required info” icon is missing, even for the earlier document and when the breakpoint is hit you will see that event.listItem is missing the RequiredField field
14. Reload the page again and everything is back to normal again

You can of course reproduce this in the same way with a command set extension.

### Expected behavior

I expect the onRenderCell and onListViewUpdated events to always contain all empty required fields like it normally does so that we always have access to them in the extensions.

**Comment by AJIXuMuK** [comment]
Sorry for the long delay @patrikhellgren!
We have found the underlying issue and will be working on the fix.

**Comment by AJIXuMuK** [comment]
Sorry for the really long turnaround here. 
But it finally should be fixed!
