### ISSUE TITLE
Field customizer onRenderCell event intermittently returns fieldValue undefined when uploading new document

### ISSUE THREAD

**Issue by patrikhellgren** [SharePoint/sp-dev-docs#7003]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 92.0.878.0
- SPFx version 1.12.1
- Node.js version 14.16.1

### Describe the bug / error

The onRenderCell event intermittently return event.fieldValue = undefined when uploading new document.

### Scenario:
1. I upload a new document to a document library with a text field in the view that has a field customizer.
2. The onRenderCell event.fieldValue then sometimes is an empty string like it should and sometimes undefined.
3. If the event.fieldValue is undefined it sometimes stays undefined until I reload the page and sometimes onRenderCell is called again immediately and then event.fieldValue is an empty string like it should.

When event.fieldValue is undefined, event.listItem contains fewer fields than when it is an empty string. In my simple test it contained 42 fields when undefined and 57 when empty string. The field with field customizer is not one of the 42 so that explains why event.fieldValue is undefined until onRenderCell returns an event.listItem containing all 57 fields.

This issue may or may not be related to #7001, at least it is very similar in that the number of fields change intermittently for event.listItem when uploading a new document.

### Steps to reproduce

1. Create a new field customizer using the yeoman generator
2. Create a new document library
3. Create a new text column named FieldCustomizer in the library and make it **not required**
4. Configure launch.json so that you have a debug configuration that loads the page with the document library and also loads the field customizer in the FieldCustomizer field
5. Start debugging so that the page with the library opens in the browser
6. Set a breakpoint in the onRenderCell method
7. Upload a document without setting any values and take note of the event.fieldValue in onRenderCell
8. Repeat step 7 and pretty soon event.fieldValue should be undefined

### Expected behavior

I expect event.fieldValue to always contain the fields correct value. I also expect event.listItem to always contain the correct fields.

**Comment by AJIXuMuK** [comment]
Sorry for the really long turnaround here. 
But it finally should be fixed!
