### ISSUE TITLE
NodeJs Support for SPFx 1.4.1 (SP 2019)

### ISSUE THREAD

**Issue by MelAtWork** [SharePoint/sp-dev-docs#7005]
Unfortunately I still have to support SPFx 1.4.1 - I know the community and attention around this is pretty small.
However, I hope to find some help here, as there are 2 different doc articles listing the version dependencies.

Reading this article here
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
I would not expect any issues running SPFx with Node.js LTS 14, as the only exceptions mentioned are for SP 2016.

_(This version is the currently recommended version of Node.js to use with the SharePoint Framework (unless otherwise specified below).)_

But the page referred here seems to recommend Node.js LTS 8 as the latest Node.js version for SPFx 1.4.1.

So which version is the truly recommended/supported one? 

Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25459e4a-2488-302d-9906-cfacfdc4639a
* Version Independent ID: 339fbcec-873c-9c47-fd9c-cf5f505132ac
* Content: [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
* Content Source: [docs/spfx/compatibility.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/compatibility.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
As this page states, if you're limited to SPFx v1.4.1, you are limited to Node.js v8.
