### ISSUE TITLE
Nest if statement

### ISSUE THREAD

**Issue by lkimberleyj** [SharePoint/sp-dev-docs#7007]
The page is fantastic... thank you.
Could you please include a statement that looks at 2 or more if's then returns a result.
If this and that, then
if this or that, then

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi! We have some examples on the column formatting page. Given that it's Excel style expressions, it's not really particular to form formatting.

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#excel-style-expressions
