### ISSUE TITLE
Unable to create FieldCustomizer\ListViewCommandSet extensions

### ISSUE THREAD

**Issue by Bassem-Nabil** [SharePoint/sp-dev-docs#701]
Category
- [*] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Has anyone managed to test the FieldCustomizer or the ListViewCommandSet extensions?
I'm following the tutorial [here](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension) and I can easily create the first example (header\footer) but the next two are not working. I generate using yeomen, run gulp serve and use the query string method to run it in my developer tenant, I get the 'load debug scripts' popup but neither the FieldCustomizer nor the ListViewCommandSet show up afterwards.

I've updated SharePoint generator to 1.1.1, changed the manifest schema under HelloWorldCommandSet.manifest.json as per Matt's post [here](https://mattjimison.com/2017/06/09/sharepoint-framework-extensions-developer-preview-schema-issue/) but still nothing.

**Comment by waldekmastykarz** [comment]
Are you testing your extensions on a modern site by any chance? If so, then it's a known issue. Currently you can test them only on classic sites in list with modern experience.

**Comment by andrewconnell** [comment]
I think it's also only available in dev tenants, not in regular tenants.

**Comment by waldekmastykarz** [comment]
Good one. That's another thing you have to take into account.

**Comment by Bassem-Nabil** [comment]
Thank you for the guidance. I'm using a dev tenant with a modern site (new experience).
Do I need to recreate the site or just downgrade the experience?

I've tried to set the option from sharepoint admin to the classic experience and set the list to the new experience under advanced settings but it does not seem to work. I still browse the site in the new experience while the list is in the classic experience (and I'm sure I didn't mix the two in the options). Do I need to clear cache somewhere, I'm using incognito in chrome.

**Comment by Bassem-Nabil** [comment]
Great, that worked out. Just needed to kill chrome and try again!
Cheers mate
