### ISSUE TITLE
How to authenticate SPFx app on SharePoint Page Load

### ISSUE THREAD

**Issue by CoderSharepoint** [SharePoint/sp-dev-docs#702]
#### Category
- [ ] Question

#### Description
I want to create SPFx webpart which will get all users from Azure Active Directory using Microsoft Graph API.
I have used SPFx, Adal.js and react to do it.

I added my SPFx webpart in ShrePoint Site. SPFx webpart should able to get context as logged in user and load data.

I have attached part of code. Please find in attachment.

#### Expected or Desired Behavior
It should get the context of signed in user using cached and loads data.

#### Observed Behavior
I am not getting context once app part loads. I had put sing in buttons which prompts for microsoft login but at that time it gets user and logged in users so i am not coming back to sharepoint page from login prompts.

[Code.txt](https://github.com/SharePoint/sp-dev-docs/files/1130258/Code.txt)

If you have any idea please let me know.

**Comment by mcmynn83** [comment]
Currently this is in dev preview and you should be using the graph http client.  Please see the documentation at https://dev.office.com/sharepoint/reference/spfx/sp-http/class/graphhttpclient.
