### ISSUE TITLE
Facing Issue Getting error 

### ISSUE THREAD

**Issue by kumarudgirkar** [SharePoint/sp-dev-docs#7023]
System.Net.WebException: 'The remote server returned an error: (400) Bad Request. - {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'http://waii.sharepoint.com' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: b44cfe10-e7d2-4144-ac06-c7e2d27a5e00\r\nCorrelation ID: dd6de0dd-b259-4618-a6ee-a291066914dc\r\nTimestamp: 2021-05-20 12:56:37Z","error_codes":[90002],"timestamp":"2021-05-20 12:56:37Z","trace_id":"b44cfe10-e7d2-4144-ac06-c7e2d27a5e00","correlation_id":"dd6de0dd-b259-4618-a6ee-a291066914dc","error_uri":"https://accounts.accesscontrol.windows.net/error?code=90002"}'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Your URL is invalid. You forgot the 's' for 'http**s**://waii.sharepoint.com'
