### ISSUE TITLE
CORS issue with HTTPClient @microsoft/sp-http

### ISSUE THREAD

**Issue by KalapJo1** [SharePoint/sp-dev-docs#7025]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version --> 90.0.4430.212 
- SPFx version 
- @microsoft/generator-sharepoint@1.12.1
- Node.js version --> v12.22.1
- "@microsoft/sp-core-library": "1.12.1",
- "@microsoft/sp-lodash-subset": "1.12.1",
- "@microsoft/sp-office-ui-fabric-core": "1.12.1",
- "@microsoft/sp-property-pane": "1.12.1",
- "@microsoft/sp-webpart-base": "1.12.1",
- "axios": "^0.21.1",
- "lodash": "^4.17.21",
- "office-ui-fabric-react": "7.156.0",
- "react": "16.9.0",
- "react-dom": "16.9.0"

### Issue description

I'm calling the Azure Automation account webhook from SPFX HTTPClient. But the preflight and CORS errors are bothering me.  They are throwing CORS ERROR.

I have even tried Axios.
  

        let options:IHttpClientOptions ={
         body:{"MSG":"HI PS SCRIPT"},mode:"cors",headers:{
            "Content-Type":"application/x-www-form-urlencoded"
          }}; 
       return this.HttpClient.post('{webhookurl}',
            HttpClient.configurations.v1, options).then((response: HttpClientResponse) => {  
                    return response.json();  
            }).then(jsonResponse => {  
                console.log(jsonResponse); 
            }) as Promise<any>;  `

**Comment by KalapJo1** [comment]
#5096

**Comment by waldekmastykarz** [comment]
Could it be that this is a limitation of Azure Automation webhooks? https://feedback.azure.com/forums/246290-automation/suggestions/15318723-cors-support-for-azure-automation-webhooks

**Comment by KalapJo1** [comment]
Yes the preflight fails for only automation account URLs which does not have CORS enabling capabilities at the moment.
