### ISSUE TITLE
Unable to use web app permission in Site Collection App Catalog

### ISSUE THREAD

**Issue by backstrom82** [SharePoint/sp-dev-docs#7026]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

All browsers
SPFx v1.11
Node.js 10.23.3

### Describe the bug / error

I've created a spfx package containing a webpart that reads from MS Graph. The solution request the following permissions in package-solution.json:
```json
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All,Directory.ReadWrite.All"
      }
    ]
```
This works fine when I deploy the solution to the tenant app catalog. When I deploy the solution to a site collection app catalog it gets deployed without any error and creates an API access request (which I approve). But the webpart throws the following error when using the MSGraphClient:

```
Uncaught (in promise) Error: Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2021-05-20T19:40:49","request-id":"82b80ddb-...","client-request-id":"82b80ddb-..."}}}
```
Is this scenario not supported or have I missed any steps required?

### Steps to reproduce

1. Create a new spfx package and create webpart that uses MSGraphClient
2. Add the following to package-solution.json
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All,Directory.ReadWrite.All"
      }
    ]
3. Build and deploy the package to a site collection app catalog.
4. Approve the api request

### Expected behavior

That the code doesnt throw any exceptions and data to be returned from the graph call.

**Comment by AJIXuMuK** [comment]
Hello @backstrom82 - sorry for the long delay.
What API are you trying to use?

I've just tried to repro the issue, and it seems everything works as expected.
Here is my sample:
```typescript
const graphClient = await this.context.msGraphClientFactory.getClient();
const groups = await graphClient.api('groups').version('v1.0').select('id,displayName').get();
const members = await graphClient.api(`groups/${groups.value[0].id}/members`).version('v1.0').get();
```
