### ISSUE TITLE
SPFX Application Customizers break "Share with Anyone" links for certain document types.

### ISSUE THREAD

**Issue by alirobe** [SharePoint/sp-dev-docs#7028]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Latest versions of all browsers on Windows 10. 
A compiled version of 'react-application-breadcrumb' is used as an example, which is SPFX v1.11.
Node v 10.23.0 was used to compile.

### Describe the bug / error

If a site has a SharePoint Application Customizer installed (such as react-application-breadcrumb), and a "Share with anyone" link to a PDF is opened by a completely unauthenticated user (e.g. inprivate), the PDF preview breaks because the OneDrive preview refuses to load until the application customizer is loaded. The Application Customizer is not loaded due to insufficient permissions of the anonymous user to access the AppCatalog's assets. This completely breaks the user's access to the document.

### Steps to reproduce

1. Install any header application customizer on a site
2. Enable "share with any user" on that site
3. Share a link to a PDF
4. Open the link incognito
5. Note that the link fails to load.

### Expected behavior

In an instance where there is a permissions failure, the application customizer should be disabled, or the user should be redirected to a download of the file.

**Comment by alirobe** [comment]
Has there been any progress on this? It is affecting our customers.

**Comment by alirobe** [comment]
Any update?

**Comment by AJIXuMuK** [comment]
Hello @alirobe!
Thank you for reporting this one.
Could you please provide the screenshots of what you're experiencing? I was unable to reproduce the issue.
