### ISSUE TITLE
Error on "package-solution" with SharePoint 2016 onwards, including 2019 and SharePoint Online

### ISSUE THREAD

**Issue by Navazee777** [SharePoint/sp-dev-docs#7029]
Getting errors while packaging using "gulp package-solution --ship" & "gulp package-solution"

![Error2](https://user-images.githubusercontent.com/84514518/119353942-1ad7ea80-bcc1-11eb-8e78-2dfb75f57468.PNG)

Steps to reproduce
1.gulp clean
2.gulp build
3.gulp bundle --ship (or) gulp bundle
4.gulp package-solution --ship (or) gulp package-solution

Additional environment details
C:\Users\ABC\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.12.1
+-- gulp@4.0.2
+-- npm@7.10.0
+-- rimraf@3.0.2
+-- typescript@3.9.6
`-- yo@3.1.1

Installed below package:
npm install @pnp/sp –save
npm install @pnp/spfx-controls-react –save 
npm install --save @types/jquery
npm install --save @types/jqueryui

**Comment by andrewconnell** [comment]
Gulp v4 is not supported with Node.js v10... it's only supported with Node.js v12+. Can you install Gulp v3 & try again?

**Comment by Navazee777** [comment]
> Gulp v4 is not supported with Node.js v10... it's only supported with Node.js v12+. Can you install Gulp v3 & try again?

I tried with Gulp v3, but getting same error.

+-- @microsoft/generator-sharepoint@1.12.1
+-- gulp-cli@2.3.0
+-- gulp-v3@3.12.1
+-- npm@7.10.0
+-- rimraf@3.0.2
+-- touch-cli@0.0.1
+-- typescript@3.9.6
`-- yo@3.1.1

**Comment by Navazee777** [comment]
Some of the observation regarding above issue.

1. At my end, while configuring webpart using [Link](https://pnp.github.io/pnpjs/SPFx-on-premises/).
observation : after (8:Run npm install) typescript in below section is still unchanged(still pointing to typescript version 2.2.2 instead of 3.6.4 at below section in "package-lock.json" file.
` "node_modules/typescript": {
      "version": "2.2.2",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-2.2.2.tgz",
      "integrity": "sha1-YGAiUIR5tV/6NotY/uljoD39eww=",
      "dev": true,
      "bin": {
        "tsc": "bin/tsc",
        "tsserver": "bin/tsserver"
      },
      "engines": {
        "node": ">=4.2.0"
      }
    }`

After:
` "node_modules/typescript": {
      "version": "3.6.4",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.6.4.tgz",
      "integrity": "sha512-unoCll1+l+YK4i4F8f22TaNVPRHcD9PA3yCuZ8g5e0qGqlVlJ/8FSateOLLSagn+Yg5+ZwuPkL8LFUc0Jcvksg==",
      "dev": true,
      "bin": {
        "tsc": "bin/tsc",
        "tsserver": "bin/tsserver"
      },
      "engines": {
        "node": ">=4.2.0"
      }
    }`

I manually changed to 3.6.4 and run "npm Install" once again. it create package without any issues.

2.I'm able to package solution successfully for first time only. second time I'm getting same error()?
Any ideas to overcome this issue.

**Comment by Navazee777** [comment]
One more observation. 

When I ran, Gulp clean.. 
Package file is not deleted "/sharepoint/solution/ofmspfxwebparts.sppkg" 
I try to delete manually, but it is showing "access denied" error. Even I logged in with Administrator account. 
![PermissionError](https://user-images.githubusercontent.com/84514518/120147631-93c8cc00-c204-11eb-8143-70629c8414b3.PNG)
