### ISSUE TITLE
iconImageUrl property and the correct image size

### ISSUE THREAD

**Issue by gjanblaszczyk** [SharePoint/sp-dev-docs#703]
I read a official Sharepoint Framework doc here: (https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries)
Inside the doc it says that "iconImageUrl" should be "the image at the URL must be exactly 38 x 38 px."
I link the png file that has exacly 38x38px but inside the toolbox the icon looks squeezed because canvas resize it to 48x40 px. My question is:
What size of the image I should use? 

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Icon looks great in toolbox.

#### Observed Behavior
Icon is fuzzy. 

#### Steps to Reproduce
try to use 38x38 px png file with "iconImageUrl"

**Comment by nickpape-msft** [comment]
The documentation here is outdated. The image should be 40 x 28 px. I will update documentation shortly.

**Comment by waldekmastykarz** [comment]
@nickpape-msft you also might want to update the comments in `./@microsoft/sp-module-interfaces/lib/manifestSchemas/IClientSideWebPartManifest.d.ts` and `./@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/client-side-web-part-manifest.schema.json` where the icon size is still 38x38px. Whenever there is no official documentation for a particular property, these comments provide valuable information and it would be helpful if it was accurate.
