### ISSUE TITLE
Custom Header & Footer Not Showing

### ISSUE THREAD

**Issue by QuSimone** [SharePoint/sp-dev-docs#7036]
After copy/pasting the code from the [tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions):
![image](https://user-images.githubusercontent.com/72839029/119552911-e65f3f80-bd4f-11eb-9450-c58eff73f390.png)
This error shows:
![image](https://user-images.githubusercontent.com/72839029/119552941-f0813e00-bd4f-11eb-9c1c-dfb47a81bf04.png)

I'm unsure how to fix this issue, I tried replacing the line with:
```
return Promise.resolve();
return Promise.resolve<void>(null);
return Promise.resolve<void>(undefined);

```
The above three lines allow the code to compile and "gulp serve" to be ran.
However, the custom header and footer are not visible.
The browser console indicates the _renderPlaceHolders method was indeed called and seemingly executed successfully.
What am I doing incorrectly?

Tools versions:
node - v14.17.0 LTS
npm - 6.14.13
gulp - CLI 2.3.0 Local version 4.0.2
SPFx - 1.12.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ecfb7b-2d99-1835-1688-8fbb904fcc8c
* Version Independent ID: 9001961c-5199-76ca-c3a7-b3d69b49e20d
* Content: [Use page placeholders from Application Customizer (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)
* Content Source: [docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by sumit9898** [comment]
I removed the "void" and it worked for me. I have attached a picture of the code snippet and output for your reference.

![2021-06-04 (3)](https://user-images.githubusercontent.com/39809199/120696225-ec7cbb00-c4c9-11eb-84eb-aff2118fd53e.png)



![2021-06-04 (2)](https://user-images.githubusercontent.com/39809199/120695848-78421780-c4c9-11eb-9a81-a96ec7b9b3b9.png)

**Comment by QuSimone** [comment]
![image](https://user-images.githubusercontent.com/72839029/120840354-fc72ba00-c51e-11eb-8ae8-062b8229f186.png)

After removing the void, my webpage still does not display the header/footer. In the console I can see the methods were indeed called, but nothing is rendered. This is a newly created SharePoint site with no special additions. What could be wrong?

**Comment by AJIXuMuK** [comment]
Sorry @QuSimone - lost track of that issue.
Is that still an issue for you?

If yes - what version of SPFx are you using? and what is the code of `_renderPlaceholders`?

Thanks!
