### ISSUE TITLE
Migration API speaks about adding MD5 has but XSD does not describe such property

### ISSUE THREAD

**Issue by bk-td** [SharePoint/sp-dev-docs#7048]
The documentation of the SharePoint Migration API tells to add MD5Hashes to the Manifest.xml but the DeploymentManifest.XSD does not have such properties defined.

Is there an updates version of the DeploymentManifest.XSD ?

Besides the MD5Hash attribute, the example Xml also contains a Checksum (for files over 15GB) and an InitializationVector (files under 2 GB) attribute, but the documentation does not explain what they do?

Would be good to have update the documentation, as now it's useless because it is not documentation clear enough.

**Comment by andrewconnell** [comment]
Can you please provide context? What doc are you referring to?
