### ISSUE TITLE
Equivalent way for get web template name from SPFx add in context legacyPageContext object?

### ISSUE THREAD

**Issue by KoteswararaoKata** [SharePoint/sp-dev-docs#7049]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We have a requirement in SPFx add in i.e. conditionally display of banner and footer on SharePoint online site collections based on each particular site collection web template name. for example if web template of "STS#0" then show only banner if other template show both banner and footer.  We have a provision to get web template name value from SPFx add in context legacyPageContext object.

But Microsoft not encouraging to use legacyPageContext variable values, The contents of this variable may change in future releases of SharePoint. What are the equivalent ways to get web template name from SPFx add in/Webpart context?

**Comment by bcameron1231** [comment]
You could make a REST call to the SharePoint Online site in your onInit. You can pull the WebTemplate from the web object.

_api/web?$Select=WebTemplate
