### ISSUE TITLE
SharePoint partial post back does not load the constructor of the elements

### ISSUE THREAD

**Issue by Dangerous-Mind** [SharePoint/sp-dev-docs#7051]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version (any version)
- SPFx version (1.11.0)
- Node.js version (10.24.0)

### Issue description

Wen we click a navigation link on SharePoint online we only have a partial post back that only loads some information on the page.
This means that if you have the two copies of the same spfx application on the links, the element wont run the constructor of the new visible element since he thinks it's the same element from previous page.

Events like componentWillUnmount and componentDidMount are also ignored and do not run..

I can think in some solutions but none seams to be perfect and since we will need to add this code to every SPFx app I think we should have a permanent solution to this issue.

**Comment by andrewconnell** [comment]
Can you please provide repro steps to better understand the issue?

**Comment by Dangerous-Mind** [comment]
My chosen solution for the problem was to add a componentWillReceiveProps event and since the new data was already in props I just needed to refresh the Element stats and the applications started working correctly. 

Since this was a complex old SPFx solution that I updated to SPFx 1.11.0, I tried to replicate the issue with a small helloworld application (SPFx 1.12.1) and it seams to be working fine now.
