### ISSUE TITLE
Invalide reference of @microsoft/sp-diagnostics@1.12.1 - Could not be found

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#7054]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 12.1
- Node.js 12

### Describe the bug / error

Seems like 'generator-sharepoint' references an NPM package that is not available in this specific version.

@microsoft/sp-diagnostics@1.12.1

<img width="685" alt="image" src="https://user-images.githubusercontent.com/5503835/120086546-08561a80-c0e0-11eb-9c66-c81d120f8b9c.png">

### Steps to reproduce

1. Create. a new SPFx 12.1.0
2. Select no-framework project
3. Error will be shown right after provisioning

### Expected behavior

No Invalid references ;)

**Comment by patmill** [comment]
Hey @StfBauer - how are things going?  Did you sort this out?  This package is showing as published here - https://www.npmjs.com/package/@microsoft/sp-diagnostics
