### ISSUE TITLE
Code review tool for SPFX project

### ISSUE THREAD

**Issue by subashrishihar** [SharePoint/sp-dev-docs#7056]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Please suggest a open source code review tool for SPFX projects

**Comment by andrewconnell** [comment]
Can you please be more specific what you're looking for? Aside form a typical client-side project, what are you looking for?

**Comment by subashrishihar** [comment]
I am looking a tool to verify and find defects on source code in development phase. This is to improve the quality of the source code for developer’s in development phase.

For example FxCop is the tool which helps to analyse the C# code. 
(https://docs.inedo.com/docs/buildmaster-platforms-dot-net-fxcop
https://www.c-sharpcorner.com/blogs/code-review-in-net1).

I am looking similar one to review and analyse my SPFx project source code.

Thanks.

**Comment by andrewconnell** [comment]
Microsoft doesn't offer anything like that specific to SPFx.

**Comment by subashrishihar** [comment]
Okey.
Is there any third party tools available to analyse ReactJS code?

**Comment by andrewconnell** [comment]
Maybe... personally not aware of what 3rd party options are out there. Google will be your friend here :)

**Comment by subashrishihar** [comment]
Ok, Thanks
