### ISSUE TITLE
A custom service worker implemented in SPO is always getting redundant state because of spserviceworker.js

### ISSUE THREAD

**Issue by mohammadamer** [SharePoint/sp-dev-docs#7057]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.11.0
- Node.js version v10.24.0
- yo version 

### Issue description

A custom Web Push Notification that has a custom a service worker implemented in SPO. Service worker is always gets redundant state because of spserviceworker.js service worker.
I'm trying to install and activate my service worker using an App Customizer but spserviceworker.js service worker is always kicking out my service worker.
Is there away to get my service worker gets activated with SPO service worker or what would be the best here in this case.

**Comment by andrewconnell** [comment]
Can you please provide some context & repro steps demonstrating what you’re seeing? that would help others in assisting.

**Comment by mohammadamer** [comment]
Sure, We have been trying to extend the SharePoint Online by implementing Web Push Notifications in SharePoint Online after we went through the tutorials in this [link ](https://github.com/MicrosoftEdge/pushnotifications-demo-aspnetcore) which using Java Script and ASP.NET Core. Our implementation are using Azure Functions to achieve the backend part and SPFx extension to achieve the frontend part.

We tried to implement registering service worker to SharePoint root site (adding JS file to the root site https://xxxxx.sharepoint.com/service-worker.js) but stuck with a built-in SharePoint Service worker that kick out our custom service worker and make it in a redundant state or not active. If we tried to activate our custom service worker manually in the browser console SharePoint built-in service worker turns it into redundant state.
SharePoint Service worker:

```
navigator.serviceWorker.controller
ServiceWorker {scriptURL: "https://xxxxx.sharepoint.com/_layouts/15/odsps…estName%22%3A%22stsserviceworkerprefetch%22%7D%5D", state: "activated", onstatechange: null, onerror: null}
onerror: null
onstatechange: null
scriptURL: "https://xxxxx.sharepoint.com/_layouts/15/odspserviceworkerproxy.aspx?swManifestName=spserviceworker&debug=false&bypass=false&applications=%5B%7B%22id%22%3A%22STS%22%2C%22swPrefetchManifestName%22%3A%22stsserviceworkerprefetch%22%7D%5D"
state: "activated"
__proto__: ServiceWorker
```
Our Custom Service Worker:
```
ServiceWorker {scriptURL: "https://xxxxx.sharepoint.com/service-worker.js", state: "activated", onstatechange: null, onerror: null}
onerror: null
onstatechange: null
scriptURL: "https://xxxxx.sharepoint.com/service-worker.js"
state: "activated"
__proto__: ServiceWorker
```

After some search, it turns out that multiple service workers are not allowed in the same scope that's why we thought about registering our custom service worker to every site collection (adding JS file to root folder of every site collection https://xxxxx.sharepoint.com/sites/abc/service-worker.js then register it)
We stopped when we were unable to `Add-PnPFile -Path .\service-worker.js -Folder "/sites/abc/" ` with getting an error `Error: Add-PnPFile: Access denied. You do not have permission to perform this action or access this resource.` [link ](https://github.com/pnp/powershell/issues/747) to the issue.
We would need to know if the issue in this link is a limitation or a bug because the right implementation or service should be in every root site.

As a workaround, we thought about add our custom service worker to Site Pages libraries then register it but somehow the SharePoint built-in service worker is being registered and activated firstly. After the second load of the page our custom service worker gets activated. 
The main point here is that there no enough information about this built-in Service worker to be able to understand how it works how to extend or create another custom service worker that can help us extend SharePoint Functionality.

I hope that my explanation is clear.

**Comment by mohammadamer** [comment]
**Update:**
_We have done the implementation in SharePoint but we have some issues and we need to understand
What does SPO service worker do?
What are the possibilities of adding any other Service Workers?
After registering our Service Worker with specific scope, we noticed that our service worker intercepts all coming requests to the site.
So we need to understand, what will be the impact of adding our custom service worker?_

**Comment by patmill** [comment]
So, unfortunately you can not have multiple service workers for the same scope, so the code SPO service worker will be installed.  The ability to create a concurrent service worker would need to be a new feature.
