### ISSUE TITLE
Unable to copy paste text along with image in Pnp Richtextbox

### ISSUE THREAD

**Issue by RahiniRadha** [SharePoint/sp-dev-docs#7059]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We have used a Pnp rich textbox control in one of SPFx webpart. We are able to copy and paste text and images separately. But when we copy text along with image, the image not getting pasted in Richtextbox.

Any idea on this? How can we achieve this?

**Comment by bcameron1231** [comment]
Hi, as this a PnP Controls specific question. I would ask your question over in that repo, they would most likely be able to help you out.

https://github.com/pnp/sp-dev-fx-controls-react/issues
