### ISSUE TITLE
PnP Provisioning Template to existing SharePoint site

### ISSUE THREAD

**Issue by greeshdhir** [SharePoint/sp-dev-docs#7063]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi, I'm trying to apply a SharePoint Template to an existing SharePoint site.  I'm using the following cmdlets via the Windows PowerShell ISE application.

**Connect-PnPOnline -Url "https://name.sharepoint.com/sites/TemplateSite"
Get-PnPSiteTemplate -Out "PnP-Provisioning-File.xml"
Disconnect-PnPOnline
Connect-PnPOnline -Url https://name.sharepoint.com/sites/NewSite
Invoke-PnPSiteTemplate -Path "PnP-Provisioning-File.xml"**

This seem to work, however I have 3 issues:
1. I get the following error which I don't understand:
**WARNING: ListInstance Style Library is a Style Library of a site with NoScript enabled and will be skipped**

2. The Document Library does not get cloned from the template.  I have several directories in my template site and I was expecting the template to create these on the target site.

3. There is an image on the main home page which does not seem to be applied to the target site.

Any guidance will be very much appreciated.

**Comment by andrewconnell** [comment]
This should be posted to the PNP project about the provisioning service / POSH cmdlets as this repo is primarily for generic SP development issues.

REF: https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps&WT.mc_id=m365-12936-cxa#ive-found-a-bug-where-do-i-need-to-log-an-issue-or-create-a-pr
