### ISSUE TITLE
NodeJs Support for SPFx 1.4.1 (SP 2019): reopened

### ISSUE THREAD

**Issue by MelAtWork** [SharePoint/sp-dev-docs#7065]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

This is a follow-up of my original question here: #7005 

For a big SPFX change project in a customers SP 2019 environment (trying to replace existing WSP solutions with SPFX), we need an official idea about SPFX dependencies and the appropriate versions, in the current case especially Node.Js

As stated in the previous issue, I find several sources with all kinds of different information:

Source 1: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
--> exception/dependency only mentioned for SP 2016, not SP 2019

Source 2: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility
--> this mentions **Node.Js LTS 8** as the dependency for SPFX 1.4.1 (latest version on SharePoint Server 2019)

Source 3: https://docs.microsoft.com/en-us/learn/modules/sharepoint-spfx-get-started/5-exercise-setup-development-environment
--> "If you are building projects for SharePoint 2019 and/or SharePoint Online, then it is recommended that you install **Node.js v10.x** ..."

In the current customer project, Node.JS LTS 10 was also recommended for SP 2019 SPFX projects - the source for this recommendation is unknown, but projects built on this seem to work correctly. 

One of the great PNP masters Andrew Connell already answered the question with Node.JS LTS 8 as the required version, but that would mean I would need to trigger a huge change process now to downgrade from 10 to 8 (it's distributed within a portable package including Git and VS Code for the developers).

I am unsure if the incompatibility is really severe and I am seeking help and recommendation if a downgrade will be really needed for future projects?

**Comment by bcameron1231** [comment]
It definitely appears like we have some mismatching information across our development documentation. As Andrew mentioned, Node 8 LTS (or 6) are the recommended and only *supported* version of Node to use with SharePoint 2019 development. I personally, would recommend downgrading from V10 to V8 to maintain supportability. 

With that being said, it sounds like you have a working solution with v10 LTS. You could continue using that at your own risk... but I personally, try to avoid it and stay within the recommended versions.

**Comment by MelAtWork** [comment]
Hey Beau,
thanks for this recommendation and confirmation of Andrews feedback. This second opinion will give me enough for the customer conversation. KR
