### ISSUE TITLE
🐞 Missing property pane interface & enum for link control (not exported)

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#707]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Should be able to import interfaces & enums leveraged in interfaces.

#### Observed Behavior
The `IPropertyPaneLinkProps` interface in **@microsoft/sp-webpart-base** references the interface `IPopupWindowProps` & enum `PopupWindowPosition`, however the librarys type definition does not export them where everything else related to the property pane exports them: `@microsoft/sp-webpart-base/lib/index.d.ts`

#### Steps to Reproduce

- add the following `import` statement to a CSWP project:

```typescript
import {
  PropertyPaneLink,
  IPropertyPaneLinkProps,
  IPopupWindowProps,
  PopupWindowPosition
} from '@microsoft/sp-webpart-base';
```

- build the project with `gulp build`
- observe the following errors:

![image](https://user-images.githubusercontent.com/2068657/27968939-f20219c6-6316-11e7-944f-d9da41522169.png)

#### Steps for Workaround

add the following reference to directly reference the type definition file:

```typescript
import {
  IPopupWindowProps,
  PopupWindowPosition
} from '@microsoft/sp-webpart-base/lib/propertyPane/propertyPaneFields/propertyPaneLink/IPropertyPaneLink';
```

**Comment by andrewconnell** [comment]
Related to #708

**Comment by pgonzal** [comment]
Thanks for reporting this issue.  It does appear that we are not exporting an interface that was intended to be exported.  We'll follow up when we have a fix.

**Comment by pgonzal** [comment]
Upon further investigation, we realized that the "popupWindowProps" feature was removed from **office-ui-fabric-react** in [September](https://github.com/OfficeDev/office-ui-fabric-react/pull/293).  It should be removed from SPFx as well.  Since this was prior to GA, we won't break anyone by taking that approach.  See #708 for more details.
