### ISSUE TITLE
Isolated webpart with fixed height "150px". What's the recommended fix to make iframe grow based on content or available space? 

### ISSUE THREAD

**Issue by HimanathD** [SharePoint/sp-dev-docs#7070]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser  Edge Version 91.0.864.37 (
- SPFx @microsoft/generator-sharepoint@1.12.1
- Node.js version : v14.15.1
- VS code

### Issue description

Isolated webpart with fixed height "150px".
I tried to host  webpart in single part page and regular site page, don't see any difference and webpart always render with default height 150px.
Is this by design? What's the recommended fix to make iframe grow based on content or available space?

**Comment by patmill** [comment]
The parent iFrame should scale with the size of your host webpart.  Are you forcing the div to be 150 px?
