### ISSUE TITLE
Banner misspelling on https://docs.microsoft.com/en-us/sharepoint/dev/ : "SharePoint developmer documentation"

### ISSUE THREAD

**Issue by markvsql** [SharePoint/sp-dev-docs#7072]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

The banner on the https://docs.microsoft.com/en-us/sharepoint/dev/ landing page has a misspelling in the banner: "SharePoint developmer documentation"
<img width="628" alt="SPMiesspelling" src="https://user-images.githubusercontent.com/17649722/120702949-4f466600-c47a-11eb-942d-8c53d4b68bf2.png">

**Comment by andrewconnell** [comment]
Thanks... this has been fixed, it just hasn't been pushed to LIVE yet.
