### ISSUE TITLE
Not getting API Requests from my SPFX Solution after deploying it to Tenant level app catalog

### ISSUE THREAD

**Issue by sivanu137** [SharePoint/sp-dev-docs#7074]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version --> Chrome (**Version 91.0.4472.77 (Official Build) (64-bit)**) and Edge (**Version 91.0.864.41 (Official build) (64-bit)**)
- Node.js version - **v10.22.0**
+-- @microsoft/generator-sharepoint@1.11.0
+-- gulp@4.0.2
`-- yo@3.1.1

### Issue description

Hi, in my SPFX react framework solution I have some web API permissions added, but the problem is after deploying the solution in tenant level app catalog, nothing is there under pending request in API Management.

![image](https://user-images.githubusercontent.com/31919925/120911550-e6433600-c6a5-11eb-96c8-394a020610dd.png)

and my solution is also deployed without any error.

![tempsnip](https://user-images.githubusercontent.com/31919925/120911620-679ac880-c6a6-11eb-87ab-12ddce44101d.png)

What may be the issue here?? Help me to solve this issue

Thankyou

**Comment by andrewconnell** [comment]
Have you tried uninstalling & deleting it from the app catalog and trying again? It does appear something screwed up.

You could alternatively grant the permission using POSH/M365 CLI.

**Comment by NicolajHedeager** [comment]
We are seeing a similar behaviour when we are trying to add new permission requests to an existing SPFx package. The new permissions doesn’t show up under pending requests in API management. We have tried updating the package version but with no success. 

Running SPFx 1.12.1 and Node 14.15.5

**Comment by sivanu137** [comment]
@andrewconnell  Thanks for the response, I tried the same, but no use, the issue remains the same. But I got some workaround to grant the Same permissions via Azure. 

I'm very much excited to learn what is the root cause? why my API request from SPFX Package is not showing up under Pending request.

**_Steps:
Add Graph API through UI:_**

From the Azure portal, display the Azure Active Directory (AAD), then select the **App Registration** menu and select **All Applications**, then click on **SharePoint Online Client Extensibility Web Application Principal**. It's the AAD Application that holds the connection to the API (Microsoft and others) from SharePoint (SPFx or every other development) using the Implicit Flow.

Once here, click on Add permission, then select Microsoft Graph and add the [ExternalItem.Read.All] Graph API delegated permission (you can type the name of the permission in the available search box to get it easily).

![image](https://user-images.githubusercontent.com/31919925/123368527-03747180-d58d-11eb-8b04-d6e565c7e96b.png)

Once added, grant it by clicking on Grant admin consent for Contoso.

If you go to the API access page (https://contoso-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement), you can see new Permission added under Approved Request.

Reference: [https://michaelmaillot.github.io/tips/20210302-spfx-api-permissions/](https://michaelmaillot.github.io/tips/20210302-spfx-api-permissions/)

**Comment by sivanu137** [comment]
@NicolajHedeager  For time being you can follow the above-mentioned steps to overcome the problem, let's figure out the root cause of this if possible.

**Comment by NicolajHedeager** [comment]
@sivanu137 That approach has also been my workaround for now, but thanks for steps anyway 😄

**Comment by sivanu137** [comment]
@NicolajHedeager , Need your help, Since you were Running SPFx 1.12.1 and Node 14.15.5, can you share with me the **yo** and **gulp** versions too? Because I want to upgrade my SPFX Development Environment. If possible share with me the version details.

**Comment by NicolajHedeager** [comment]
@sivanu137 
Gulp 4.0.2

Yeoman is just scaffolding so it shouldn't matter.
I'm updating an existing solution.

**Comment by andrewconnell** [comment]
> @NicolajHedeager , Need your help, Since you were Running SPFx 1.12.1 and Node 14.15.5, can you share with me the **yo** and **gulp** versions too? Because I want to upgrade my SPFX Development Environment. If possible share with me the version details.
> 
> Currently, I'm running
> 
> **node -v -->**
> Node - 10.22.0
> 
> **gulp -v -->**
> CLI version: 2.3.0
> Local version: 3.9.1
> 
> **npm ls -g --depth=0**
> +-- @microsoft/generator-sharepoint@1.11.0
> +-- gulp@4.0.2
> `-- yo@3.1.1

Gulp v4 isn't supported with Node.js v10... only Node.js v12 and higher. Gulp v3 is supported with Node.js v10 and lower. This is mentioned in the SPFx v1.12.1 release notes: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1#gulp-versions--nodejs-v12

**Comment by MortenGuldbaek** [comment]
We are still seeing this issue in our environments and it's hindering us in releasing new features to our product.
Using PS/M365CLI is not an option for us in our deployment scenario. 

I'm commenting here to hopefully get some attention to this issue.

Do you have any details @andrewconnell ?

Thanks in advance.

**Comment by patmill** [comment]
Sorry for the delay - can you help us drill down a bit into this?
1 - Can you share a screenshot of the API access page?  Is there any chance that the request has already been previously approved?  Are there any errors displayed?
2 - If you look at the network trace in the dev dashboard, or the console, do you see any errors / failed requests / etc?
