### ISSUE TITLE
How to add devExtreme to SPFx and deploy it

### ISSUE THREAD

**Issue by Cawerlip** [SharePoint/sp-dev-docs#7075]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

node: v10.13.0
SPFx: 1.12.1

### Issue description

Hello!
I'm trying to add devExtreme components to SPFx.
In the official documentation of DevExpress thay have steps for creating components using React and webpack.  (https://js.devexpress.com/Documentation/Guide/React_Components/Add_DevExtreme_to_a_React_Application/#Import_DevExtreme_Components)
I did it and it works. I have a Chart which works on localhost. 

And now I tried to add it to gulp build. I installed webpack stream, devextreme-react, devextreme. Wrote webpack config and add it to gulp. Created Chart.js 
![image](https://user-images.githubusercontent.com/65185051/121003104-cf7c0c80-c795-11eb-8cd4-99645d978507.png)

I have mistake with import and cannot figure out what's wrong.
![image](https://user-images.githubusercontent.com/65185051/121003221-f5a1ac80-c795-11eb-81b0-7835d98014cc.png)

If i add "allowJs": true, I have mistake with "declaration".
![image](https://user-images.githubusercontent.com/65185051/121003602-65b03280-c796-11eb-806e-666c03b4df4d.png)

Soo, I hope that anybody can explain me steps to achive my goal.

**Comment by andrewconnell** [comment]
Unclear... what do you mean by this:

> If i add "allowJs": true, I have mistake with "declaration".
