### ISSUE TITLE
Code samples not correct

### ISSUE THREAD

**Issue by andrePKI** [SharePoint/sp-dev-docs#7078]
Examples and code don't match. Especially column formatting is applied, but not present in these code examples.
Also, code samples are formatted for readability, but will not be accapted by SPO.
Example:  "Color coded group header" and  "Color coded group header with aggregate" is not just View formatting, but also column formatting to decorate the City column
Also, the lines with "`=if(@group.fieldData ...`" should appear on one line, and the parentheses are unbalanced (closing ')' is missing)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Jacqueline-ms** [comment]
I would like to tag on to this bug. 

The documentation details customizable JSON that you paste into the list view format, but my edits never accomplish the desired look. This is for an internal MS SharePoint site and I am currently blocked because of it.
