### ISSUE TITLE
Guid.tryParse() not working

### ISSUE THREAD

**Issue by vieirav** [SharePoint/sp-dev-docs#7079]
## Category
- [x] Bug

## Describe the bug
Looks like this method has a bug.
I'm passing a string in the format **"/Guid(####)/"** as expected, and it's returning undefined, so something is wrong!!
If I pass a string in the format **"####"**, it's fine.

![image](https://user-images.githubusercontent.com/13801784/121201389-c7df6500-c874-11eb-9c3a-7940aac62a75.png)
![image](https://user-images.githubusercontent.com/13801784/121202039-45a37080-c875-11eb-8fba-c3a1834f39fc.png)

**package.json**
"@microsoft/sp-core-library": "1.11.0"

## Expected behaviour
Parse the string to guid.

**Comment by patmill** [comment]
Thanks - I think that's a documentation error.  If you skip the /'s, does it work correctly?  Ie
"Guid(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)"

**Comment by vieirav** [comment]
Hi @patmill,

Thanks for replying!

Yes, it works. 
Here's my test.
```
let myGuid = "Guid(68bb7c4a-ecb7-4c39-b298-7455b4cf5287)";
let testGuid = Guid.tryParse(myGuid);
console.log("testGuid: ", testGuid);

let myGuid2 = "/Guid(68bb7c4a-ecb7-4c39-b298-7455b4cf5287)/";
let testGuid2 = Guid.tryParse(myGuid2);
console.log("testGuid2: ", testGuid2);
```
_Result:_
![image](https://user-images.githubusercontent.com/13801784/132219712-d676bfb9-6ea2-475c-bf29-d825d278a835.png)


We can close this now.
Thanks.

**Comment by AJIXuMuK** [comment]
Sorry for the long delay - it has been fixed and will be rolled out WW in the next couple of weeks.

**Comment by AJIXuMuK** [comment]
Closing - should be rolled out WW by now.
