### ISSUE TITLE
Office add-ins build with SharePoint Framework

### ISSUE THREAD

**Issue by MonalisaBaltatescu** [SharePoint/sp-dev-docs#7081]
What about Office add-ins build with SharePoint Framework? Is this feature still in preview? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a6341f-3625-3bd1-151a-8fdb057b7295
* Version Independent ID: ad6d6b0c-3d46-adff-6e71-7ca9fca7dede
* Content: [SharePoint Framework v1.12.1 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1)
* Content Source: [docs/spfx/release-1.12.1.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.12.1.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This feature is still in preview and unfortunately there are no exact plans currently to transition that to be Generally Available. We would love this to happen from SPFx side, but there are resource constraints from the other related organizations.

**Comment by MonalisaBaltatescu** [comment]
Thanks for answering! :)
