### ISSUE TITLE
SPFx - Integrate bootstrap with WebPart

### ISSUE THREAD

**Issue by kevinvugts** [SharePoint/sp-dev-docs#7085]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,

Currently I am struggling integrating the bootstrap framework into my custom webpart.
I have watched tons of tutorials online but all resulting in the same error.

### My Code Repo: 
https://github.com/kevinvugts/test-spfx

When creating a [style.module.scss ](https://pastebin.com/QBJqqG6X) file containing my default bootstrap variables overwrites the gulp builder fails with the following error:

```
 exited with code 2
Error - [webpack] 'dist':
./lib/webparts/webpartDgdmHelloworld/components/Theme.module.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./lib/webparts/webpartDgdmHelloworld/components/Theme.module.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError
(40:4) Missed semicolon
 @ ./lib/webparts/webpartDgdmHelloworld/components/Theme.module.css 1:14-155
 @ ./lib/webparts/webpartDgdmHelloworld/components/Theme.module.scss.js
 @ ./lib/webparts/webpartDgdmHelloworld/components/WebpartDgdmHelloworld.js
 @ ./lib/webparts/webpartDgdmHelloworld/WebpartDgdmHelloworldWebPart.js
```

The weird part is that there is no missing semicolon at all. When disabling the last line in the [scss file](https://pastebin.com/QBJqqG6X) the error disappears but bootstrap will not be loaded.

Of course I am able to load bootstrap with the     SPComponentLoader.loadCss("https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css");

However this is not desired since I want to overwrite certain variables of bootstrap before it's loaded.

### My question
How can I integrate the bootstrap framework & React-bootstrap library with my SPFX webpart? 

When importing components from React-bootstrap library I am getting the following errors:

```
Error - [tsc] node_modules/@popperjs/core/lib/createPopper.d.ts(1,13): error TS1005: '=' expected.
Error - [tsc] node_modules/@popperjs/core/lib/createPopper.d.ts(1,73): error TS1005: ';' expected.
```

Active GitHub thread related to this question: https://stackoverflow.com/questions/67924028/how-to-add-bootstrap-to-sharepoint-spfx-webpart

**Comment by M365Bass** [comment]
Hi @kevinvugts - I did some testing and I seem to have found a way around. The problem with popper is that [it does not provide a types library](https://popper.js.org/docs/v2/typings/#common-flow-and-typescript).

Basically, while SPFx can include external resources using the SPComponentLoader  [as outlined here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/reference-third-party-css-styles#approach-2-load-third-party-libraries-from-a-url), it also requires adding the respective types library as a dev dependency.

Both bootstrap and jQuery provide type libraries `@types/bootstrap @types/jquery` which can be installed as dev deppendencies while popper does not. To get around that, I installed popper itself as a dev dependency.

Hope this helps.

Bass

**Comment by kevinvugts** [comment]
> Hi @kevinvugts - I did some testing and I seem to have found a way around. The problem with popper is that [it does not provide a types library](https://popper.js.org/docs/v2/typings/#common-flow-and-typescript).
> 
> Basically, while SPFx can include external resources using the SPComponentLoader [as outlined here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/reference-third-party-css-styles#approach-2-load-third-party-libraries-from-a-url), it also requires adding the respective types library as a dev dependency.
> 
> Both bootstrap and jQuery provide type libraries `@types/bootstrap @types/jquery` which can be installed as dev deppendencies while popper does not. To get around that, I installed popper itself as a dev dependency.
> 
> Hope this helps.
> 
> Bass

Hi Bass,

Could you provide me with some sample code and the way you configured Popper into SPFX?
Thanks a lot already for your input!

Best,
Kevin

**Comment by M365Bass** [comment]
Hey Kevin,

Here are the detailed steps:
1. Install the following libraries in your project (note the save-dev as they are dev dependencies)
```
npm i @types/bootstrap @types/jquery @popperjs/core --save-dev
```
2. Update config\config.json to include jQuery and bootstrap as external libraries
```
"externals": {
  "jquery": {
    "path": "node_modules/jquery/dist/jquery.min.js",
    "globalName": "jQuery"
  },
  "bootstrap": {
    "path": "node_modules/bootstrap/dist/js/bootstrap.min.js",
    "globalName": "bootstrap"
  }
},
```

3. Add an init function to the Parent WebPart (the one that extends BaseClientSideWebPart)
```
protected onInit(): Promise<void> {
  SPComponentLoader.loadCss(
    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css'
  );
  SPComponentLoader.loadScript(
    'https://code.jquery.com/jquery-3.3.1.slim.min.js'
  );
  SPComponentLoader.loadScript(
    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js'
  );
  SPComponentLoader.loadScript(
    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js'
  );

  return super.onInit();
}
```

Once the setup is done, elements should be able to apply bootstrap - I used the below render function to test
```
return (
  <div>
    <div className="alert alert-primary" role="alert">
      This is a primary alert—check it out!
    </div>
    <div className="alert alert-secondary" role="alert">
      This is a secondary alert—check it out!
    </div>
    <div className="alert alert-success" role="alert">
      This is a success alert—check it out!
    </div>
    <div className="alert alert-danger" role="alert">
      This is a danger alert—check it out!
    </div>
    <div className="alert alert-warning" role="alert">
      This is a warning alert—check it out!
    </div>
    <div className="alert alert-info" role="alert">
      This is a info alert—check it out!
    </div>
    <div className="alert alert-light" role="alert">
      This is a light alert—check it out!
    </div>
    <div className="alert alert-dark" role="alert">
      This is a dark alert—check it out!
    </div>
  </div>
);
```

**Comment by kevinvugts** [comment]
> Hey Kevin,
> 
> Here are the detailed steps:
> 
> 1. Install the following libraries in your project (note the save-dev as they are dev dependencies)
> 
> ```
> npm i @types/bootstrap @types/jquery @popperjs/core --save-dev
> ```
> 
> 1. Update config\config.json to include jQuery and bootstrap as external libraries
> 
> ```
> "externals": {
>   "jquery": {
>     "path": "node_modules/jquery/dist/jquery.min.js",
>     "globalName": "jQuery"
>   },
>   "bootstrap": {
>     "path": "node_modules/bootstrap/dist/js/bootstrap.min.js",
>     "globalName": "bootstrap"
>   }
> },
> ```
> 
> 1. Add an init function to the Parent WebPart (the one that extends BaseClientSideWebPart)
> 
> ```
> protected onInit(): Promise<void> {
>   SPComponentLoader.loadCss(
>     'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css'
>   );
>   SPComponentLoader.loadScript(
>     'https://code.jquery.com/jquery-3.3.1.slim.min.js'
>   );
>   SPComponentLoader.loadScript(
>     'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js'
>   );
>   SPComponentLoader.loadScript(
>     'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js'
>   );
> 
>   return super.onInit();
> }
> ```
> 
> Once the setup is done, elements should be able to apply bootstrap - I used the below render function to test
> 
> ```
> return (
>   <div>
>     <div className="alert alert-primary" role="alert">
>       This is a primary alert—check it out!
>     </div>
>     <div className="alert alert-secondary" role="alert">
>       This is a secondary alert—check it out!
>     </div>
>     <div className="alert alert-success" role="alert">
>       This is a success alert—check it out!
>     </div>
>     <div className="alert alert-danger" role="alert">
>       This is a danger alert—check it out!
>     </div>
>     <div className="alert alert-warning" role="alert">
>       This is a warning alert—check it out!
>     </div>
>     <div className="alert alert-info" role="alert">
>       This is a info alert—check it out!
>     </div>
>     <div className="alert alert-light" role="alert">
>       This is a light alert—check it out!
>     </div>
>     <div className="alert alert-dark" role="alert">
>       This is a dark alert—check it out!
>     </div>
>   </div>
> );
> ```
> 
> Reading through my snippet, I can see I loaded `popper.min.js` but actually installed `@popperjs/core` - might be best to align these two to the same version. I also hear that [unpkg](https://unpkg.com/) is the place to go so it might be good to update the URLs in the SPComponentLoader section to use it

Thanks for your reply. However I already fixed the issue by [these](https://stackoverflow.com/questions/67924028/how-to-add-bootstrap-to-sharepoint-spfx-webpart/67961180#67961180) instructions. Thanks anyways!
Closing off....
