### ISSUE TITLE
Recursive function to handle list view threshold not working

### ISSUE THREAD

**Issue by vivekmurli** [SharePoint/sp-dev-docs#7086]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

We have a list with 0.5 Million items.

The end goal is to get and handle threshold using recursive function. Followed the below article however didn't work as per our requirement.

[](https://sharepoint.stackexchange.com/questions/264002/cant-get-list-items-when-list-item-count-gets-over-5000)

**Code**

```
function FilteredInvoiceNew(ColumnName,ColumnVal){
 
var dataset = [];
var FltrInv = [];
var response = response || [];
var ApprovalStatus = "";
var listName="Claimlist";
var myQuery= _spPageContextInfo.webAbsoluteUrl + "/_api/web/lists/getbytitle('ListName')/items?$select=ID,P_x0020_No,Inv_x0020_Date,Item_x0020_No,ProductCode,Qty,Prj_x0020_Name,
Distributor_x0020_No,Distributor_x0020_Name,Contractor_x0020_Name,Claim_x0020_Amount,YourReference,YourProductCode,YourPONumber,IsApproved,Comments";

if(ColumnName!=="" && ColumnVal!==""){
            
  myQuery+="&$filter=substringof('"+ColumnName+"',"+ColumnVal+")";      
}   

myQuery+="&$top=500";
myQuery+="&$orderby=ID desc";
 
 debugger;
 
        return $.ajax({
            url: myQuery,  
            method: "GET",  
            headers: {  
                "Accept": "application/json; odata=verbose"  
            },
            success: function(data){
                response = response.concat(data.d.results);
                if (data.d.__next) {
                    myQuery = data.d.__next;
                    FilteredInvoiceNew();
                }
              
                const lookup = response.reduce((a, e) => {
                a[e.YourReference] = ++a[e.YourReference] || 0;
                return a;
                }, {});

                FltrInv = response.filter(e => lookup[e.YourReference]);
                console.log(FltrInv);
                
                $.each(FltrInv, function(index, row) {
                    
                    // SomeCode
                    
               });
   
 },
 
 error: function(error){
 
  console.log(error);
 }
 
  });// End of Ajax Call
 
}
```
Executing the function goes to the error section and throws the threshold error as shown below

![image](https://user-images.githubusercontent.com/6428093/121571860-6e656a80-ca1b-11eb-81ab-9c95c2e9e49c.png)

Also tried nested function to include the below logic and it skips the nested function.

Would be extremely grateful if anyone could let us know if this is achievable.

Thanks in advance

**Comment by michaelhan-1** [comment]
If you want to filter more than 5k items in SharePoint list, you need to create index for that column in list settings

![image](https://user-images.githubusercontent.com/69185043/121847756-a8848400-cd1b-11eb-8833-8a7ee2b44879.png)


**Michael Han
Microsoft SharePoint Community Support**
