### ISSUE TITLE
this.context.statusRenderer.displayLoadingIndicator to display a loading indicator it doesn’t work well in child components

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#709]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We found that when we use this.context.statusRenderer.displayLoadingIndicator to display a loading indicator it doesn’t work well in child components. 

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
Add a function in the web part class that is used to show loading indicator.

![1](https://user-images.githubusercontent.com/1407310/27973630-b60f850e-6328-11e7-823e-a1de9f8f950a.png)

Then in a child component, transmit the _utilsLoading function to the loadingCallback.

![2](https://user-images.githubusercontent.com/1407310/27973644-c449e0b0-6328-11e7-813a-428ad2acc32e.png)

![3](https://user-images.githubusercontent.com/1407310/27973658-cefc68fc-6328-11e7-9ca5-db592972d53a.png)

Then, use the loading call back function to show the loading indicator.  The indicator message is never shown.  Instead, the entire web part renders as empty (shown below).

![4](https://user-images.githubusercontent.com/1407310/27973687-ee527584-6328-11e7-9f3b-f63f77a9f5f2.png)

![5](https://user-images.githubusercontent.com/1407310/27973701-f9a6d1e6-6328-11e7-9e4b-04a338980feb.png)

When the code hides the loading indicator, the web part content is still missing.  In fact, it shrinks! 

![6](https://user-images.githubusercontent.com/1407310/27973719-0772661e-6329-11e7-9472-fa6d59b35977.png)

**Comment by andrewconnell** [comment]
I saw the same thing in #696

**Comment by mcmynn83** [comment]
Thank you for the feedback.  Chris is addressing this issue via #696.  Please open up a new thread if after that bug is resolved your issue is not fixed.
