### ISSUE TITLE
Issue with SPFX CommandSet UI

### ISSUE THREAD

**Issue by ivanmaria** [SharePoint/sp-dev-docs#7091]
It seems like there was some recent changes in the SharePoint UI that is causing a glitch in command buttons UI due to which the custom CommandSet button gets hidden behind the 'All Document' option. Refer the below screenshot for reference.

![screenshot](https://user-images.githubusercontent.com/26500608/121904926-3cb81080-cd47-11eb-82b4-2df8e99ee28e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Thanks for leaving the comment, but as this is an OOTB UI issue, it's best posted to your M365 portal for the appropriate to address.
