### ISSUE TITLE
How do you handle Node and NPM versions?

### ISSUE THREAD

**Issue by JoelHJ** [SharePoint/sp-dev-docs#7095]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I just wanted to ask how you guys handle different Node and NPM, gulp versions. It seems everytime i download a new solution to have a look at i have to install a different version of something. I tried some of the verion managers but they seem to have issues also. At the moment I'm reinstalling/uninstalling and forever changing versions. Was thinking of VM machines with different versions. Then someone said that I might be able to use Visual Studio 2019 but I couldn't figure it out. I use visual code most of the time. 

I'm not a developer per se but was put into it at work as i manage to tinker my way around. I have managed to get many solutions to work once i get the version right but it takes time. And when i want to go back and edit something from a solution that i have worked on I again need to install the versions that fit to that solution. Its mad lol. 

I have used the shrinkwrap npm file a couple of times but not sure if it makes it easier. 

Anyway.. thank you for your time and all the help i have had so far. If this is posted in the wrong section or there are better places I do apologise. 

again thank you
Joel

**Comment by M365Bass** [comment]
Hey @JoelHJ,

I've been in the same ship for some time now, between working on SharePoint 2016 and Online as well as using [the WebPart Samples repo](https://github.com/pnp/sp-dev-fx-webparts).

One option is to use containers. @waldekmastykarz mainatains a [repo ](https://rencore.com/blog/try-sharepoint-framework-without-installing/)for the required container images and has detailed the initial setup [here](https://rencore.com/blog/try-sharepoint-framework-without-installing/) as well. Basically, the container image encapsulates Node, NPM as well as Gulp, yo and the respective SPFx version and you can switch between container images as needed.

For me, it was a node version manager & dedicated node version for each SharePoint framework target but I do understand that's a complex setup - currently, I keep a Node v14 for the latest SPFx and a couple of Node v10s for SPFx 1.10 and 1.11 respectively. It took some time to perfect but once in place, I only need to setup a Node version for each new SPFx release which is fairly simple. Happy to share specific gulp/yo installed versions if that's of interest.

Both would require a performant dev machine and admin access to install and manage properly - that was my biggest hurdle when things didn't work as intended.

Best of luck!

**Comment by StfBauer** [comment]
Another option is to use [the Windows port NVM](https://github.com/coreybutler/nvm-windows) which allows you to install and use multiple NodeJS and npm version on the same machine and you are also able to switch dynamically between those.

**Comment by andrewconnell** [comment]
+1 for NVM... https://www.voitanos.io/blog/try-sharepoint-framework-preview-releases/

**Comment by JoelHJ** [comment]
> +1 for NVM... [voitanos.io/blog/try-sharepoint-framework-preview-releases](https://www.voitanos.io/blog/try-sharepoint-framework-preview-releases/)

I did try this but I had issues with some Node versions as it seems to support more new ones than old ones.

**Comment by JoelHJ** [comment]
Hi @M365Bass I had a look at Docker, intresting and I have never heard of it. One thing i note when reading it is that you can only serve in local workbench. Does this mean that you can't do a gulp serve to my own env to test it with my SharePoint data as can be done usually? That would be a drawback one would think?

**Comment by M365Bass** [comment]
While I haven't tested myslef, it seems like it can be done with the workarounds [documented here](https://github.com/waldekmastykarz/docker-spfx#known-issues).

It might also be worth it to give NVM/NVM-Windows another try as well.

**Comment by JoelHJ** [comment]
I think i will try your solution. Work has not given me a machine that is big enough to just run VMWare and I could make some clones sigh. Thank you so much for your help :-)

**Comment by andrewconnell** [comment]
@JoelHJ said:
> I did try this but I had issues with some Node versions as it seems to support more new ones than old ones.

I've been using NVM on macOS way before SPFx came out, going back to the iojs & Node v4 days... I've never had an issue with any Node versions and NVM.

@M365Bass & @JoelHJ, I've seen recent issues pop up of people having problems using the Docker approach (ref #7076) with the latest SPFx version due to changes in the toolchain. Personally, I find the Docker solution much more complicated than the very simplistic NVM approach.
