### ISSUE TITLE
Example could be improved to handle paths when there are multiple solutions in repo subfolders

### ISSUE THREAD

**Issue by petval** [SharePoint/sp-dev-docs#7098]
Example could be improved to handle paths when there are multiple solutions in repo subfolders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f70ab0e-7e7d-df8f-5607-8794b5d26024
* Version Independent ID: 16b7890e-6e7f-0573-3d79-51bdb04758dd
* Content: [Implement Continuous Integration and Continuous deployment using Azure Pipelines](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-pipelines)
* Content Source: [docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Do you mean you are storing multiple SPFx solutions in the same repo?

While it's possible to do this, the point of the article is to demonstrate how to set up CI/CD with SPFx projects using Azure Pipelines and not go into every setup possible.

**Comment by petval** [comment]
@andrewconnell 
> Do you mean you are storing multiple SPFx solutions in the same repo?

Yes. But I have figured out how to reference the subfolders. It's just that the documentation is not very informative about the folder variables used in YAML files. I suggest the document is updated to at least link to [Use predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) document as this took me quite some time to figure out.

```
 /home/vsts/work/1 - Pipeline.Workspace
a - Build.ArtifactStagingDirectory
b - Build.BinariesDirectory
s - Build.SourcesDirectory
drop
```
