### ISSUE TITLE
What additional steps needed to test webpart in workbench.aspx on test tenant?

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#71]
I followed the tutorial of adding the workbench.aspx page to the documents library on the dev site collection in my test tenant. But I seem to be missing the extra steps to test my webpart there. What do I need to do to get the solution to deploy in the tenant. I see the instructions for testing in classic pages. What am I missing. Thanks.

**Comment by wictorwilen** [comment]
If you have `gulp serve`  running then it's just for you to head on over to workbench.aspx, and accept "mixed content" (the little warning shield in the address bar in Chrome, use Chrome, not some other browser).

For usage in classic pages you need to package your solution, add the .spapp package to the app catalog and approve it. Still having `gulp serve` running, or deploy it to a CDN location somewhere.

**Comment by rolandoldengarm** [comment]
Firefox works as well. Same restriction though (i.e. need to load mixed resources)

**Comment by mauricionr** [comment]
i guess at this time it's only possible test one web part at time, i've tried to add more webpart to the same project and fail, run multiple local serve with `gulp serve` and fail it again.

**Comment by SteveCurran** [comment]
Thanks, stupid but not obvious mistake of trying to run workbench.aspx from a machine where the framework is not running.
