### ISSUE TITLE
Using @fluentui/react 8.x

### ISSUE THREAD

**Issue by Greg-Hitchon** [SharePoint/sp-dev-docs#7101]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.12.1
- Node.js version: 14.16.1

### Issue description

Hello,

We are trying to use the [adaptive cards fluent ui library](https://www.npmjs.com/package/adaptivecards-fluentui) however it has a dependency on @fluentui/react. This leads to a few options:

1. Install the latest fluentui/react 8.x side by side the default SpFx office-ui-fabric-react package. Problem with this is it leads to slow build times even with spfx-fast-serve
2. Do something more questionable/not-recommended like replace office-ui-fabric-react with fluentui/react. Have tried this and nothing seems broken from a quick look.

My question then is: are there any better options? and if not is option 2 completely horrible, or just advised against?

**Comment by AJIXuMuK** [comment]
@Greg-Hitchon - thanks for raising this question.
We do not block you from using other versions of Office UI Fabric or Fluent UI in applications.
Any version you've referenced will be bundled with the solution.
The only thing to keep in mind is OOB UI is based on v7, meaning we will load v7, including styling/themes, on the page anyway. And it can affect your solution.
Other than that - there are no limitations.

Hope it helps.
