### ISSUE TITLE
Webparts with assets deployed on Azure CDN

### ISSUE THREAD

**Issue by sephys** [SharePoint/sp-dev-docs#7103]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : 91.0.4472.114
- SPFx version : 1.12.1
- Node.js version : v12.13.1

### Describe the bug / error

I deployed the react-carousel (from sp-dev-fx-webparts) component two weeks ago. The assets are deployed on an azure cdn. The component was working fine until Friday, when I got the following message on my environment:
![image](https://user-images.githubusercontent.com/6817078/122788454-a344ad80-d2b6-11eb-912e-7d8b4111fe9d.png)

Inside developper tools I got cors error.
![image](https://user-images.githubusercontent.com/6817078/122789837-05ea7900-d2b8-11eb-903c-64903f137db4.png)

What is strange is another dev tenant, same webpart is deployed, and still working.

### Steps to reproduce

1. Configure an Azure storage account 
2. Configure the web part to load from CDN
3. Prepare the web part assets to deploy
4. Deploy assets to Azure Storage
5. Deploy the updated package

### Expected behavior

![image](https://user-images.githubusercontent.com/6817078/122788454-a344ad80-d2b6-11eb-912e-7d8b4111fe9d.png)

**Comment by KevinTCoughlin** [comment]
@sephys does this still repro? We believe to have pulled the offending change.

**Comment by sephys** [comment]
Hi @KevinTCoughlin, It's working fine thanks you. Could you give me more informations on what have been done to fix it?

**Comment by VesaJuvonen** [comment]
@sephys - this was a regression (a bug) caused in the server side code, which was gradually rolling out. It was luckily caught pretty early, which explains why things worked in one tenant and didn't in another.

There's technically no point going to further details on which piece of our internal code the issue, but it was a bug from Microsoft side, which has been now fixed. We are working on learning from each and every bug which is getting through, but unfortunately these also happen every now and then, as we are all humans.

Thanks for sharing the finding in here as it helps for others with similar issues on following up on the progress and seeing that they are not unique.

Closing issue as fixed.
