### ISSUE TITLE
SPFx app does not work on Modern page

### ISSUE THREAD

**Issue by RoguePoma** [SharePoint/sp-dev-docs#7106]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Node.js version: v8.13.0
- 
"dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/graph": "^2.3.0",
    "@pnp/sp": "^2.3.0",
    "@types/jquery": "^3.5.5",
    "jquery": "^3.6.0",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },

### Describe the bug / error

Hello My web part works perfectly in a live environment in classic SP and the Semi Modern SP however it fails to load in the Fully Modern SP site.

This image is the error I recieve.
![image](https://user-images.githubusercontent.com/45376111/122825960-84581280-d2da-11eb-9c09-23f30da9695e.png)

Error details: Error: Error initializing application. Error: TypeError: can't access property "Content", this.context.preloadedData.page is undefined
Correlation ID: 8e27d49f-b077-c000-3b7b-df054465a19d

This is what it should look like. 
![image](https://user-images.githubusercontent.com/45376111/122826192-c08b7300-d2da-11eb-89cf-e88fdb80701b.png)

Below is the main portion of the code, any help would be greatly appreciated.  🥳 

import * as React from "react";
import * as ReactDOM from "react-dom";
import { ICalendarSpfxProps } from "./ICalendarSpfxProps";
import { escape } from "@microsoft/sp-lodash-subset";
import Overview from "../components/CalendarOverview";
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { ServiceProvider } from "../../../ServiceProvider";

import { SiteUsers, sp } from "@pnp/sp/presets/all";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";

export interface IOverViewProps {
  context: WebPartContext;
  GroupUuid: string;
}

export interface IOverViewState {
  data: any;
}

export interface IMainViewModel {
  Styles: any;
}

export default class OverViewStats extends React.Component<
  IOverViewProps,
  IOverViewState,
  ICalendarSpfxProps
> {
  private serviceProvider;

  public constructor(props: IOverViewProps, state: IOverViewState) {
    super(props);
    this.serviceProvider = new ServiceProvider(this.props.context);

    this.state = {
      data: {},
    };

    this.renderUsers = this.renderUsers.bind(this);
  }

  public render(): React.ReactElement<IOverViewProps> {

    return (
      <React.Fragment>
        <div className="calendarSpfx container mx-auto min-w-min w-2/3 ml-0">
          <div className="flex items-center p-3 justify-between border-b-2 border-gray-300">
            <p className="font-bold text-base text-gray-700">Project Team</p>
          </div>
          <ul className="user-list">{this.renderUsers()}</ul>
        </div>
      </React.Fragment>
    );
  }

  public User = ({
    name,
    photoUrl,
    statusMessage,
    rowColour,
  }) => (
    <div className={rowColour}>
      <div className="text-s flex items-center">
        <div className="relative block w-12 h-12">
          <img
            className="avatar-person-image rounded-full border border-gray-100 shadow-sm"
            src={photoUrl}
          ></img>
        </div>
        <p className="ml-3">{name}</p>
      </div>
      <div className="flex items-center">
        <span className="text-s text-gray-600 mr-2 ml-2 md:ml-4">
          {statusMessage}
        </span>
      </div>
    </div>
  )

  public renderUsers() {
    const userList = [];
    for (let i = 0; i < this.state.data.length; i++) {
      const key = this.state.data[i].id;
      let row = "";
      let mes = "";
      if (i % 2 == 0) {
        row =
          "py-2 px-4 text-gray-800 flex items-center justify-between bg-white border-b border-gray-300";
      } else {
        row =
          "py-2 px-4 text-gray-800 flex items-center justify-between bg-white border-b border-gray-300";
      }
      mes = this.state.data[i].message;
      userList.push(
        <this.User
          name={this.state.data[i].name}
          photoUrl={this.state.data[i].photoUrl}
          statusMessage={mes}
          rowColour={row}
          key={key}
        />
      );
    }
    return userList;
  }

  public componentDidMount() {
    this.getData();
  }

  private getData() {
    this.serviceProvider
      .getTotals(this.props.GroupUuid)  
      .then((result: any): void => {
        console.log(result);
        this.setState({ data: result });
      })
      .catch((error) => {
        console.log(error);
      });
  }
}

### Steps to reproduce

1. Follow this to deploy https://www.c-sharpcorner.com/article/build-and-deploy-the-client-side-web-part-spfx-in-sharepoint-online/
2. Watch it work on classic and fail on Modern :sad
3.

### Expected behavior

I expect it to work the same as the classic view 😄

**Comment by andrewconnell** [comment]
As the error states, you're trying to access the SPFx API, specifically the `context`, before it exists. Just because your component is created doesn't mean SPFx has been init'd.

The code in your constructor that references the SPFx API should be in the `onInit()` method which is called AFTER SPFx has init'd on the page.

**Comment by RoguePoma** [comment]
Hello @andrewconnell thank you for your response, my understanding is that this 
`this.serviceProvider = new ServiceProvider(this.props.context)`
needs to be like so

`public onInit(): Promise<void> {
    return super.onInit().then(() => {
      this.serviceProvider = new ServiceProvider(this.props.context);
    });
  }`

however, I am getting the following error (Property 'onInit' does not exist on type 'Component<IOverViewProps, IOverViewState, ICalendarSpfxProps>) 

Sorry to be an inconvenience but am I doing this correctly?

**Comment by andrewconnell** [comment]
It's really hard to understand what you're doing with the way you've shared your code. Can't tell if this is within a React component or a SPFx component... or if it is a React component, how you're passing the context in because it looks like that isn't set.

Sharing a solid repro to make it easier to help would be the best next step.

**Comment by RoguePoma** [comment]
Hello, thank you for your continued response @andrewconnell I have added it to a repo. I used a variety of tutorials to get to this point. 

https://github.com/RoguePoma/SPFXReact

**Comment by andrewconnell** [comment]
Is there a reason why you've added the complexity of the service provider? It looks like all you're doing is adding a single HTTP GET call using it.

Seems like this would be a LOT simpler if you made the call in your web part's `onInit()` method and passed its data into the React component. Passing the heavy context object through multiple React components just to create a service provider so you can get data is adding a lot of complexity.

Not sure where the error is coming as it's complaining about a `content` property yet I don't see that anywhere in your code.

**Comment by RoguePoma** [comment]
Thank you for your response, The only reason its setup this way is the tutorial I followed went about it by creating a Service Provider along with the additional classes.  

Would you recommend me ins a sense remaking the complete project and copying over the relevant GET call. If so do you know of a 'guide' that I can use to ensure I don't go on a wild goose chase and end up getting stuck with a project that is way more complex?

As for the `content` I presumed it was when I gave the user the settings option of Group ID?

**Comment by andrewconnell** [comment]
Yes, I'd recreate this and remove the complexity of a service provider in this case. I don't know of a guide in the docs, but you've got the gist of it done. Just make the HTTP GET call in the web part, get the results and set the results of the call to a property on your React component.
