### ISSUE TITLE
_api/$batch does not support uploading multiple files using a single $batch call, can this be called out in the article?

### ISSUE THREAD

**Issue by nibubt** [SharePoint/sp-dev-docs#7122]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f963c2-441f-8f40-9c2a-3d31f4a79b1f
* Version Independent ID: d4a6f050-b632-a5a0-1814-33699760fccb
* Content: [Make batch requests with the REST APIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis)
* Content Source: [docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Can you reference where it's not supported?

**Comment by nibubt** [comment]
Had raised a ticket with the product group for a customer who was trying this scenario out. They confirmed this operation is unsupported.
