### ISSUE TITLE
Examples missing required imports

### ISSUE THREAD

**Issue by fowl2** [SharePoint/sp-dev-docs#7123]
Trying them as is generates the following errors:
``` 
error TS2304: Cannot find name 'SPHttpClientResponse'.
error TS2304: Cannot find name 'SPHttpClient'.
```

VS Code isn't suggesting anything either.

Seems the missing line is 

``` ts
import { SPHttpClient, SPHttpClientResponse } from '@microsoft/sp-http';
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec05dcfb-b91c-969d-0656-bc504f796599
* Version Independent ID: 1de9e72a-3c1f-ea80-ae1c-7721315b349a
* Content: [Connect to SharePoint APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-sharepoint)
* Content Source: [docs/spfx/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
This doc isn't meant to be a tutorial, rather it's just showing options. You could make the same argument for the PnPJS section.
