### ISSUE TITLE
Problems with nested component library link

### ISSUE THREAD

**Issue by yukumura** [SharePoint/sp-dev-docs#7129]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.11.0
- Node.js version v10.24.1

### Issue description

I have a component library (A) that has linked inside it another component library (B) that calls another component library (C).
If I go in gulp serve on the component library (B) there are no problems, I can correctly load the page and the component (C) is called correctly.

![image](https://user-images.githubusercontent.com/6943411/123785987-778a7e80-d8d9-11eb-82a2-87893d194278.png)

If I go to serve on the component (A), the component (C) is not retrieved correctly. From the serve I noticed that the path is wrong.

![image](https://user-images.githubusercontent.com/6943411/123786369-e5cf4100-d8d9-11eb-93d7-b1a1040c8c65.png)

![image](https://user-images.githubusercontent.com/6943411/123787287-e916fc80-d8da-11eb-8a03-e852e4b3a5dd.png)

[SPLoaderError.loadComponentError]:
Failed to load component "bb4e5de1-5686-4157-b8ff-64d79b68fac3" (XXXXX). Original error: Failed to load component dependency "bb4e5de1-5686-4157-b8ff-64d79b68fac3" from component "XXXXXX" (Failed to load component "5f4e0468-a12a-4778-9a2f-71d4dd6b826e" (XXXXXX). Original error: Failed to load URL 'https://localhost:4321/node_modules/ew-auth-provider/node_modules/ew-log-listener/dist/dist/ew-log-listener-library.js' for resource 'ew-log-listener-library' in component '5f4e0468-a12a-4778-9a2f-71d4dd6b826e' (XXXXX). The file was not found in the server. Make sure that you are running 'gulp serve'.). Original error: {3}

Why does it look for the component in the path "dist/dist"?

What can be the problem? Do you have any suggestion?

**Comment by nephinj** [comment]
Not sure if it is the same as my problem but I was getting that with other packages due to a bad webpack.js I had copied into my project when troubleshooting.  Removing the file fixed it for me.

**Comment by patmill** [comment]
So - does this problem only happen during gulp serve?  I'm _guessing_ that you have a couple of SPFx libraries at play (the two components in your errors).  Are they in different packages?  If they are all installed into the app catalog, do things work correctly?
