### ISSUE TITLE
How to move custom page layouts to online?

### ISSUE THREAD

**Issue by jasonwbaxter** [SharePoint/sp-dev-docs#7130]
In the section of this article (Read publishing page in on-premises SharePoint and create the modern page in SharePoint Online) you mention ___When you want to bring over your classic on-premises publishing portals you could first move the complete portal from on-premises to a classic portal in SharePoint Online___

There is a nuance to this where custom page layouts are not picked up by the migration tools, unless i'm incorrect. I'm desperately looking for solutions for my customers on this.

my alias is Jabaxt if you wish to reach out internally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e4e027-ceb5-5e46-9b68-f09344d5ef20
* Version Independent ID: e6479d50-7e92-62de-49b4-23fcc697803e
* Content: [Transform classic pages to modern pages using PowerShell](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell)
* Content Source: [docs/transform/modernize-userinterface-site-pages-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-userinterface-site-pages-powershell.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
@jasonwbaxter do your page layouts reference custom server side code? e.g. branding features which have been deployed to the farm
