### ISSUE TITLE
Unable to change deployCdnPath in copy-assets.json

### ISSUE THREAD

**Issue by ivanmaria** [SharePoint/sp-dev-docs#7131]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version NA
- SPFx version v1.12.1
- Node.js version v14.17.1

### Describe the bug / error

On building the solution, the assets files are not copied to the location mentioned in deployCdnPath in copy-assets.json

### Steps to reproduce

1. Create new SharePoint solution using yo '@microsoft/sharepoint'
2. Update the location of "deployCdnPath" in 'src/config/copy-assets.json' (eg. Change it to "temp/deploy")
3. Build the solution using 'gulp bundle --ship'
4. Verify if the assets files are copied to new location

### Expected behavior

The assets files are not copied to the location mentioned in "deployCdnPath". The assets are only found in 'src/release/assets' folder.

**Comment by andrewconnell** [comment]
That's by design... the **copy-assets.json** file isn't used to tell the build toolchain where to put the files. The build process will always put them in the **./src/releases/assets** folder (prior to v1.12.*, it would put the files in the **./src/temp/deploy**). 

That file is used to tell Gulp tasks where the files are.

**Comment by ivanmaria** [comment]
Thanks @andrewconnell, I was upgrading from v1.9.1. In this prior version, the files were actually being copied to path mentioned in "deployCdnPath". However, as this behavior is by design, I am closing it.

**Comment by andrewconnell** [comment]
For more info, see: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.1#changes-in-this-release
