### ISSUE TITLE
Download link for Color Palette Tool is broken

### ISSUE THREAD

**Issue by MSGRRojas** [SharePoint/sp-dev-docs#7134]
[Enter feedback here]
Download link for Color Palette Tool is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744e3a13-70d7-a4f8-3e86-85a5af48406b
* Version Independent ID: c0117d4b-20f0-646c-ee4e-3d5c43f74342
* Content: [Color palettes and fonts in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint)
* Content Source: [docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/color-palettes-and-fonts-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Unfortunately the tool is no longer available, so doc has been updated and link removed.
