### ISSUE TITLE
login.microsoftonline.com refused to connect in spfx solution

### ISSUE THREAD

**Issue by Marcos-Coca** [SharePoint/sp-dev-docs#7135]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Node version: 10.18.0
```
Package.json: {
  "name": "xxxxxxxxxxxxx",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fluentui/react": "^8.9.0",
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@uifabric/file-type-icons": "^7.6.30",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },
  "devDependencies": {
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  }
}
```
```
Package-solution.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "solution",
    "id": "00e8d953-213e-4a44-a99e-72102f881b2d",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "isDomainIsolated": true,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    }
  },
  "paths": {
    "zippedPackage": "solution/solution.sppkg"
  }
}

```

### Describe the bug / error

I developed 3 weparts using spfx and react, but when i did de deploy some users had the next error with de webparts: 

![image](https://user-images.githubusercontent.com/54088713/124175698-ea335f80-da7b-11eb-8fd7-f267153bf4f9.png)

Initially i thought in permission error, but the users with the problem can access to the webpart with his office 365 account from the computer of a user without problems.

Next i tried with cookies polices and put them to "Allow all cookies", both Google Chrome and edge, but nothing.

Finally with the account of user without problems i logged in the computer of a user with problems and effectively the user had the same error.

I have not idea what can be the error or who policy in the computer can restrict login.microsoftonline.com in sharepoint framework solution because the other content of the tenant can be access without problems. The total of the users with this problem is like 30% of ~1000. The webparts was tested in Internet Explorer, Microsoft Edge ,Google Chrome, FireFox, and the results was the same in both cases.

### Steps to reproduce

1. Develop sharepoint framework and react webparts
2. use the command `npx gulp bundle --ship`
3. use the command `npx gulp package-solution --ship`
4. Deploy the .sppkg file in sharpooint online site as sharepoint application

**Comment by stephentwillis** [comment]
I concur, there is something odd here. 

The browser console errors suggest that iFrames are the issue. Personally, I followed the MS tutorials to create a web part, it works brilliantly on the local workbench, but I get the same error when I've deployed the sppkg out to my site.

**Comment by stephentwillis** [comment]
Any news on this, it say the issue still says it needs triage?

**Comment by Marcos-Coca** [comment]
No, no answers yet

**Comment by EnmanuelParedesR** [comment]
Hello.

Can someone help with this? This is not just an Edge error as they try to explain in this issue #7136. Can this be an issue related to the domain? As @Marcos-Coca  said, this just happens with certain users.

**Comment by patmill** [comment]
Sorry for the delay in responding.  Can you fill in any additional information here?  Is this an isolated part?  Are you running the page in a browser, or embedded in a teams channel / tab?  Do you have a multi-geo tenant or vanity domains?

**Comment by stephentwillis** [comment]
For me this is an isolated webpart on a web page developed by myself,on a Team Sharepoint site. Ours is a single tenant, no vanity address, viewed through various web browsers.

**Comment by stephentwillis** [comment]
Oh and the webpart was developed by following Microsoft's walk through pages:

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-yeoman-and-gulp

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

I don't remember reading anything about the webparts rendering in iFrames and the webpart works beautifully in the workbench.

**Comment by Marcos-Coca** [comment]
> Sorry for the delay in responding. Can you fill in any additional information here? Is this an isolated part? Are you running the page in a browser, or embedded in a teams channel / tab? Do you have a multi-geo tenant or vanity domains?

- **Is this an isolated part?** : I'm not sure but, i followed the guide for hello world webpart and in my package-solution.json has the property `solution:{..."isDomainIsolated": true}` and in the .yo-rc.json has the property `"@microsoft/generator-sharepoint":{... "isDomainIsolated": true}`.

- **Are you running the page in a browser, or embedded in a teams channel / tab?** : i ran the parts in browser, is hosted in sharepoint online team site.

- **Do you have a multi-geo tenant or vanity domains?**: Not have multi-geo tenant but we did a domain change and for the time being have two domains.

**Comment by patmill** [comment]
Hey @Marcos-Coca - can you try one thing?  What happens if you load the main page with `?sw=bypass` as a query string?

**Comment by Marcos-Coca** [comment]
@patmill I tried with my account and nothing happened, do you need me to do the test with user who has the problem?

**Comment by patmill** [comment]
If you could try it with the person facing the issue that would be great.  If you saw the error, and it did nothing - that's sufficient.

**Comment by stephentwillis** [comment]
Bizarrely, without changing anything in code or in my test browsers the offending webpart now fully works! The sw querystring didn't seem to make a difference.

I'd love to know what has changed behind the scenes with SharePoint online!

**Comment by Marcos-Coca** [comment]
@patmill nothing happened

**Comment by patmill** [comment]
Trying to figure out the state of things.  is this specific scenario working now for everyone?

**Comment by Marcos-Coca** [comment]
@patmill  no, the error still happens.
Something new that I observed is, some users has the problems when use ie11 but when changes to chrome or other browser works fine, others users does not work with either.

**Comment by patmill** [comment]
Hi there @Marcos-Coca - trying to dig in a bit more.  If you go to the network tab on a failing instance, do you see a bunch of requests going to authorize / login ?  If so, could you paste the requests (and please remove things like secrets, nonces, etc.)
