### ISSUE TITLE
SPFX webpart in Classic Page not working

### ISSUE THREAD

**Issue by TheNCR** [SharePoint/sp-dev-docs#7136]
**Target SharePoint environment**

**SharePoint Online**
What SharePoint development model, framework, SDK or API is this about?

**SharePoint REST API**
Developer environment

**Windows**
What browser(s) / client(s) have you tested

    💥 Internet Explorer
    💥 Microsoft Edge
    💥 Google Chrome
    💥 FireFox
    Safari
    mobile (iOS/iPadOS)
    mobile (Android)
    not applicable
    other (enter in the "Additional environment details" area below)

**Additional environment details**

    Node version: 14.17.1

**Describe the bug / error**

Several SPFX react webparts developed a long time ago and which were not in any way recently have stopped working in Classic Pages.:

image

![image](https://user-images.githubusercontent.com/40604941/124183166-7abe6f80-da7d-11eb-9e87-7b0a960a1c2b.png)

I noticed the error only happens in Classic Pages but, even if I move to Modern page, there is a current issue with Edge being tracked in issue [#7135](https://github.com/SharePoint/sp-dev-docs/issues/7135) that prevents users from accessing the app.

I tried reuploading the SPPK package with no effect or change.

**Steps to reproduce**

    Develop sharepoint framework and react webparts or take existing sppkg package
    Use webpart in classic page

**Comment by Vertamin** [comment]
Yes. Same happening to us, no changes to the webparts. Stopped working on two entirely diferent Tenants.

**Comment by Vertamin** [comment]
New details:

Our webparts are doing graph calls. We created them with the "Isolated" property as "True". 

If we set the property as "False", package the app again and upload it it starts working.

**Comment by TheNCR** [comment]
New details:

Our webparts are not using graph calls, although there is a graph call issued directly from the page. I tried changing the package.json the property is-domain-isolated to False, with no avail, the error persists.

**Comment by andrewconnell** [comment]
Incorrect reference in linked PR mistakenly closed this. Reopening...

**Comment by patmill** [comment]
Sorry for the delay in getting back to this @Vertamin  / @TheNCR .  Isolated parts are a modern-only feature - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts .  TheNCR - you need to set the isolation level in the package-solution.json file in the config folder, rebuild/bundle and redeploy the solution.
