### ISSUE TITLE
lists/getbytitle('listname')/items extraction of data from full list?

### ISSUE THREAD

**Issue by debbielee1996** [SharePoint/sp-dev-docs#7138]
Hi team,

Regarding the API lists/getbytitle('listname')/items, what view does it extract from? Or does it extract out all the items in a list irregardless of the view? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa0c9cd-d807-8d1b-1eb0-66373fa254b9
* Version Independent ID: 409a88a8-7ae9-afde-d66c-81529ad15669
* Content: [Get to know the SharePoint REST service](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom#feedback)
* Content Source: [docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
It pulls items from the list regardless of view. It will by default only pull 100 items, and a max of 5,000 items at a single time (if you specify the $top odata filter.

**Comment by debbielee1996** [comment]
Hi @bcameron1231 , thanks for the reply. How do I pull >5000 items if the site has more than that? 

Also, I am currently using $top=1000000 since I did not know about the 5000 limit, does this mean that the amount of items pulled will still be capped at 5000? Thanks!

**Comment by CallumCrowley** [comment]
@debbielee1996 yes, you will need to make multiple calls to retrieve more than 5000 items.

**Comment by debbielee1996** [comment]
I see, thanks for the information! :)
