### ISSUE TITLE
Flow button in SharePoint list stops working after the first click

### ISSUE THREAD

**Issue by DavidPGrover** [SharePoint/sp-dev-docs#7139]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- any modern browser

### Describe the bug / error

Flow button in SharePoint list stops working after the first click.

I have added a flow button to a SharePoint list using column formatting (JSON). Using any standard view i.e. All Items, the first click of the button in a row works absolutely fine and the panel to run the flow is shown. If I click cancel on the flow panel and then click on the flow button again, the button is dead and the flow panel is no longer executed. This is repeatable for each and every row in the SharePoint list with the link in the row being killed after the first click.

Interestingly if you append the URL with the search view i.e. /AllItems.aspx?view=7, it works fine.

### Steps to reproduce

1. Create a list and Create an instant cloud flow for a selected SharePoint item
2. Add a column and JSON formatting with customRowAction to execute the flow 
3. Click on the flow button in the list view
4. The flow panel is shown
5. Click 'Cancel' in the flow panel
6. Click on that same flow button again and nothing happens.

### Expected behavior

I would expect the flow button to trigger the opening of the flow panel each time the flow button is clicked. It only works once and you have to refresh to page to get it to work again.

**Comment by shagra-ms** [comment]
@DavidPGrover 

We have taken a few fixes in this area over the last few months. Please try now and share if you are still running into this issue.

**Comment by eduardoj8** [comment]
Fixed in my tests.

**Comment by CryogenicPotato** [comment]
For us it still doesn't work, apparently. Did you have to do anything on your existing lists with the problematic custom actions, or the problem did resolve automatically for you?

**Comment by eduardoj8** [comment]
@CryogenicPotato , after your comment I tested better. For me the fix is working only on the Edge, last version, does not work yet in FF or Chrome.

**Comment by CryogenicPotato** [comment]
Weird enough :) for me, it doesn't work in Edge or Chrome either.

**Comment by shagra-ms** [comment]
Thanks @eduardoj8 and @CryogenicPotato for sharing your findings.

Request you to provide detailed steps, JSON and observations, so we can investigate the issue.

**Comment by CryogenicPotato** [comment]
Hello,

today we tried again, and now it looks like it's working in both Edge and Chrome, so the fix probably wasn't release to us yet.

Worth mentioning that the custom action columns are still not doing anything when clicked from a webpart, user needs to See all the entire list in order to get them working, but that's a different story.
