### ISSUE TITLE
Everything worked  -- Until .... we "transform-the-plain-javascript-code-to-typescript" 

### ISSUE THREAD

**Issue by Tobor58** [SharePoint/sp-dev-docs#7142]
[Enter feedback here]

This example how-to went into the trash after transforming it to use Typescript. Gulp stopped "serving" (no serve task error)

after that  I'd found fixes and work-around for these only to get the webpart serving and then failing in the browser with the errors below. 
These are same type of errors I had gotten using React to create a simple data table from a list. 

I have built the same kind of web part using JavaScript or React (have not attempted PnPS and don't want to) 
the project framework and all moving pieces seem so fragile and/or arbitrary what is going break when. 
this sucks frankly. 

Tomorrow  I will repeat this exercise but won't "improve it by moving to TS."  for me it these other frameworks barely work after  many hours of petty errors only have a some package break the whole damn thing. 

PS D:\SPFx_Builds\DataTablePart> npm ls -g --depth=0
C:\Program Files\nodejs
+-- @microsoft/generator-sharepoint@1.12.1
+-- @microsoft/sp-build-web@1.12.1
+-- @microsoft/sp-core-library@1.12.1
+-- @microsoft/sp-lodash-subset@1.12.1
+-- @microsoft/sp-module-interfaces@1.12.1
+-- @microsoft/sp-office-ui-fabric-core@1.12.1
+-- @microsoft/sp-webpart-base@1.12.1
+-- @microsoft/sp-webpart-workbench@1.12.1
+-- @types/webpack-env@1.16.0
+-- gulp@4.0.2
+-- npm@6.4.1
`-- yo@3.1.1

 

[21:44:06] Error - [tslint] Failed to load D:\SPFx_Builds\DataTablePart\tslint.json: Invalid "extends" configuration value - could not require "./node
_modules/@microsoft/sp-tslint-rules/base-tslint.json". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for
 the approximate method TSLint uses to find the referenced configuration file.
[21:44:06] Finished subtask 'tslint' after 4.49 s

Error - [tslint] Failed to load D:/SPFx_Builds/DataTablePart/tslint.json: Invalid "extends" configuration value - could not require "./node_modules/@microsoft/sp-tslint-rules/base-tslint.json". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
Error - [tsc] src/webparts/dataTableWebPart/DataTableWebPartWebPart.ts(90,17): error TS2416: Property 'dataVersion' in type 'DataTableWebPartWebPart' is not assignable to the same property in base type 'BaseClientSideWebPart<IDataTableWebPartWebPartProps>'.
Error - 'tsc' sub task errored after 4.55 s

Browser errors after working through gulp gulch. 

Uncaught (in promise) Error
    at t [as constructor] (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:283)
    at new t (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:914)
    at Function.e.buildErrorWithVerboseLog (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:914)
    at Function.e.buildLoadComponentError (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:914)
    at sp-webpart-workbench-assembly.js?uniqueId=NTnAt:914
sp-webpart-workbench-assembly.js?uniqueId=NTnAt:283 Uncaught (in promise) Error: ***The value for "error" must not be undefined
    at Function.e.isNotNullOrUndefined (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:283)
    at Function.window.spModuleLoader.e.logError (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:479)
    at sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383 Uncaught TypeError: Cannot read property 'searchablePlainTexts' of undefined
    at sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
    at e._serializeAsJson (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.serialize (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.serialize (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.savePageState (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:105)
SPAndroidAppManifest.aspx:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
DevTools failed to load source map: Could not load content for https://localhost:4321/temp/manifestsFile.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
5sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383 Uncaught TypeError: Cannot read property 'searchablePlainTexts' of undefined
    at sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
    at e._serializeAsJson (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.serialize (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.serialize (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383)
    at e.savePageState (sp-webpart-workbench-assembly.js?uniqueId=NTnAt:105)
(anonymous) @ sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
e._serializeAsJson @ sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
e.serialize @ sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
e.serialize @ sp-webpart-workbench-assembly.js?uniqueId=NTnAt:383
e.savePageState @ sp-webpart-workbench-assembly.js?uniqueId=NTnAt:105

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56fb9ec-59c2-413f-eaa2-e84abfb30211
* Version Independent ID: ca610020-3018-fd78-1da5-7f00fed5b04f
* Content: [Migrate jQuery and DataTables solution built using Script Editor web part to SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx)
* Content Source: [docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by KevinTCoughlin** [comment]
Looks like you have two errors here.

1) You need `@microsoft/sp-tslint-rules` as a devDep so `base-tslint.json` resolves e.g. [this file](https://unpkg.com/browse/@microsoft/sp-tslint-rules@1.12.1/base-tslint.json)

```shell
Error - [tslint] Failed to load D:/SPFx_Builds/DataTablePart/tslint.json: Invalid "extends" configuration value - could not require "./node_modules/@microsoft/sp-tslint-rules/base-tslint.json". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
```

2) You have a TypeScript compilation error (type mismatch)

```shell
Error - [tsc] src/webparts/dataTableWebPart/DataTableWebPartWebPart.ts(90,17): error TS2416: Property 'dataVersion' in type 'DataTableWebPartWebPart' is not assignable to the same property in base type 'BaseClientSideWebPart'.
Error - 'tsc' sub task errored after 4.55 s
```

**Comment by Tobor58** [comment]
Thanks for the suggestion 
Number 1  I will give that a try to repair. 
Number 2 I will revisit after implementing your first   suggestion. 

One other thing - is there an issue with using WinServer12  vs. Win10 as development machine?  

I use a my develop machine is laptop running Win12 Server to host VMs etc.   
I have access to other machines this is my personal lab machine.
