### ISSUE TITLE
Reading data with the SharePoint REST interface errors: 401 unauthorized

### ISSUE THREAD

**Issue by vijayande** [SharePoint/sp-dev-docs#7152]
when I am trying to call a SharePoint Online search service using the C# code mentioned below but it throws "The remote server returned an error: (401) Unauthorized." error to me. what could be wrong? I'm getting error: {x-ms-diagnostics: 3000006;reason="Token contains invalid signature.";category="invalid_client". However if I give 'SharePointOnlineCredentials' it is working.

```
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(sharepointHostWebUrl.ToString() + searchRestUrl);
                request.Method = "GET";
                request.Accept = "application/atom+xml";
                request.ContentType = "application/atom+xml;type=entry";
                //request.Credentials = onlineCredentials;
                request.Headers.Add("Authorization", "Bearer " + result.AccessToken);
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                // process response..
                XDocument oDataXML = XDocument.Load(response.GetResponseStream(), LoadOptions.None);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047ea71c-e866-b2dd-5530-8451de27ba4a
* Version Independent ID: 3b886e81-c3b7-d5c1-136f-4cb827b4952f
* Content: [Complete basic operations using SharePoint REST endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints?source=docs)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Looks like there is an issue with how you are retrieving the access token for SharePoint. Could be a wrong/invalid client ID. The service you requested using the client id, may not have the proper permissions. 

Can you provide a bit more information on how you are trying to authenticate.

- Are you using an ACS App or an Azure AD App? 
- What does the code look like for when you are trying to authenticate and get an access token?
- Can you share what your Azure AD or ACS App configuration looks like?

Unfortunately, there isn't enough information for us to provide valuable feedback in this regard.

**Comment by vijayande** [comment]
Hi, thank you for looking into my issue. I have followed the sample code from git repo "https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect". Yes, you are correct I'm getting "wrong/invalid client ID" in the response Headers.
* I'm using Azure AD App
* the code looks as below

// Upon successful sign in, get the access token & cache it using MSAL
              
  ```
IConfidentialClientApplication clientApp = MsalAppBuilder.BuildConfidentialClientApplication();
                AuthenticationResult result = await clientApp.AcquireTokenByAuthorizationCode(new[] { "User.Read", "Sites.Search.All" }, context.Code).ExecuteAsync();

                Uri sharepointHostWebUrl;
                sharepointHostWebUrl = new Uri("https://mytenantname.sharepoint.com");
                string queryText = "my search query";
                string searchRestUrl = string.Format("_api/search/query?querytext={0}", queryText);
				
		HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(sharepointHostWebUrl.ToString() + searchRestUrl);
                request.Method = "GET";
                request.Accept = "application/atom+xml";
                request.ContentType = "application/atom+xml;type=entry";
                request.Headers.Add("Authorization", "Bearer " + result.AccessToken);
                HttpWebResponse response = (HttpWebResponse)request.GetResponse(); **here I am getting 401 unauthorized**
                // process response..
                XDocument oDataXML = XDocument.Load(response.GetResponseStream(), LoadOptions.None);
```

* what configuration details you need?

**Comment by bcameron1231** [comment]
Can you share what permissions you've granted the application in Azure? Do they match the scopes you are trying to retrieve?

Are you using a common authority, or trying to connect directly to the tenant?

Are you connecting via V1 or V2?

**Comment by vijayande** [comment]
* yes, the scopes are exact match, as you can see below
![image](https://user-images.githubusercontent.com/17985564/124896081-c4b5d100-dffa-11eb-92fa-3d588b1ed625.png)


* trying to connect directly to the tenant (https://login.microsoftonline.com/tenantId). Below is the code that gets executed during startup
![image](https://user-images.githubusercontent.com/17985564/124897475-f8452b00-dffb-11eb-9762-45a5bcf814d7.png)
        /// The authority
 public static string Authority = string.Format(CultureInfo.InvariantCulture, **AADInstance**, "tenantId");
**AADInstancee**="https://login.microsoftonline.com/{0}"

* if I am not wrong it is using Azure AD V2 endpoint.

**Comment by vijayande** [comment]
@bcameron1231, I am looking forward for your advice. I'm stuck with this issue since 2 weeks. Thanks.

**Comment by bcameron1231** [comment]
Hi! So I think the actual issue is because the SharePoint Search Service to not support app authentication. Based on what I'm seeing, the code looks like, but you can't use App Credentials against the Search API.

Please see. https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in#high-level-guidelines
