### ISSUE TITLE
SPFx Provisioning SharePoint assets - managed metadata

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7154]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.12.1

### Issue description

Hi, I am following these steps: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package

I am correct in thinking that we cannot create a managed metadata column as part of a solution meant to be deployed in different tenants because we need to specify the **sspid** (which is tenant-dependent) in the element.xml? or we can put some kind of token there as we can using PnP?

`            <Property>
              <Name>SspId</Name>
              <Value xmlns:q1="http://www.w3.org/2001/XMLSchema" p4:type="q1:string"
                xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">[TERM STORE ID]</Value>
            </Property>`

In my tests, the column is created but it is not linked to the termset.

**Comment by patmill** [comment]
Correct - I believe that managed metadata fields can't be created through feature XML.  Your best bet would be to have a "validate" phase or a manual step to configure the field.
