### ISSUE TITLE
Typo in first sentence

### ISSUE THREAD

**Issue by CoreHF** [SharePoint/sp-dev-docs#7155]
"You can use **_nay_** text editor to build SharePoint Framework solutions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
This appears to be fixed in PR #7126 . Just not merged yet.

Thanks!

**Comment by VesaJuvonen** [comment]
#7126 merged to live and update should be now available.
