### ISSUE TITLE
SPFX Teams App working fine in Teams Browser but not loading in Desktop Teams App

### ISSUE THREAD

**Issue by NewReactUser28** [SharePoint/sp-dev-docs#7158]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

I am trying to deploy an SPFX webpart hosted in Sharepoint to Teams as a configurable tab.
I'm specifying the below as the content URL:
**<SPSiteURL>/_layouts/15/teamslogon.aspx?spfx=true&dest=<</sites/sitename/SitePages/pagename.aspx>>**
Updating the WebApplication info with Azure Add APP and the resource URL for the app
![image](https://user-images.githubusercontent.com/80849954/124810012-6e0ab180-df7e-11eb-92d4-b3023ef05aa6.png)
Reference: https://docs.microsoft.com/en-us/learn/modules/msteams-sso/4-tabs-sso

The domain from the resource URL is also included in the valid domains

However, when app is added as a configurable tab to Teams, it is rendering fine in the browser but not in the Desktop App. A spinner is continuously loading in the Desktop Teams App.

Is there anything that is missing here?

**Comment by patmill** [comment]
Sorry - not quite sure what you are trying to achieve here.  In general, you shouldn't need to create the manifest file at all, unless there is something specific that you need to configure that is atypical from simply "use this webpart as a tab".  

If you need to create a custom manifest, this document has an example of what a meeting app would look like.  In general, the webApplicationInfo isn't modified to look like your entry.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-meeting-app
