### ISSUE TITLE
Not able to import Multi Value User properties using Bulk Import API

### ISSUE THREAD

**Issue by dhruvp29** [SharePoint/sp-dev-docs#7159]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I am trying to use the [Bulk update custom user profile properties for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online) to import the multi-value properties which are types of string. 

But while executing the code, I am getting the below error.

> Property Names [Name of the Property]  are Taxonomic Properties

The property is not taxonomic property. It is the string-based multi-value type that accepts the data comma-separated.

![image](https://user-images.githubusercontent.com/18227071/124887354-b82d7a80-dff2-11eb-935c-07640437e177.png)

It is mentioned in the [document](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#can-i-import-string-based-multi-value-properties), that the import of string type multi-value property is not supported.

**Do we have any workaround for this?** 

Do we have any ETA by which this functionality will be supported?

@VesaJuvonen  @andrewconnell

**Comment by dhruvp29** [comment]
@VesaJuvonen @andrewconnell 
Can we please get any input here? It is a kind of blocker for us.

**Comment by VesaJuvonen** [comment]
There are currently no plans to support multi-value properties in this feature, so can't provide any ETA for this. Feature set has not been evolved for few years, so it's fair to expect things to remain the same for now.

**Comment by dhruvp29** [comment]
@VesaJuvonen  Thanks for the update.
