### ISSUE TITLE
Default web part should use CSS colors from the site theme instead of fixed ones

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#716]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Scaffolded web part uses CSS colors from the site instead of fixed colors. For example, when added on a site with the primary color set to red, the default button is also red and not blue.

For colors that should be replaced on runtime by site's theme colors, scaffolded web part should use the themed CSS tokens that are replaced on runtime by the  **(at)microsoft/load-themed-styles** package, like:

```css
.button {
  background-color: "[theme:themePrimary, default:#0078d7]";
}
```

This pattern should be used to show developers how to properly integrate their customizations with SharePoint.

#### Observed Behavior
Scaffolded web part uses fixed colors.

#### Steps to Reproduce
- create new project
- `gulp serve --nobrowser`
- open hosted workbench on a site with the primary color different than blue
- default button is blue instead of the primary color

**Comment by nickpape-msft** [comment]
I've added this simple theming to the Yeoman generator. It should be released in the next drop. Thanks for the suggestion @waldekmastykarz!
