### ISSUE TITLE
Breaking change in MS Search UniqueID managed property

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#7160]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Microsoft Search

### Describe the bug / error

MS Search 'UniqueID' managed property value syntax has changed from '{GUID}' to 'GUID'. 
All the queries that used old syntax stopped working.
[Twitter discussion](https://twitter.com/vesajuvonen/status/1413122429812154375)

### Steps to reproduce

Execute query to obtain result for a page. Observe the UniqueId property.

### Expected behavior

Support old syntax of the 'UniqueId' Managed Property in the search results.

**Comment by cawillwe** [comment]
We started noticing this on Tuesday, but given the holiday, it could have started sooner.

**Comment by wobba** [comment]
@siata13 Can you check the value of the `x-searchplatform` header please on the response?

**Comment by siata13** [comment]
@wobba 
X-SearchPlatform: Default
![image](https://user-images.githubusercontent.com/6162213/124940134-feda9f00-e009-11eb-986f-c7912677e06b.png)

**Comment by wobba** [comment]
Not a mitigation, but using `NormUniqueID` etc is a better approach, as the `Norm` versions are always without {}.

Are the results from SharePoint or from OneDrive, or do you see the same for items from both of these?

**Comment by siata13** [comment]
Thank you for the advice, we will switch to NormUniqueID.

I've checked only SharePoint,b later on this evening will try for OneDrive.

**Comment by cawillwe** [comment]
Have also only checked SharePoint. Am seeing that some files on same site collection work with UniqueId:"{GUID}" but not UniqueId:"Guid", and some work with UniqueId:"GUID" but not UniqueId:"{GUID}"

**Comment by wobba** [comment]
@cawillwe to clarify you are seeing files on the same site collection where some have {} and some not, correct? Or, is it happening only when you query, or are the values also stored with and without {} if you look at the response?

**Comment by cawillwe** [comment]
@wobba, when I look at the search results, I am seeing both with and without {}. To get that result, I need to search by whichever has been stored. So for one file, I search for {GUID1} and get the result as {GUID1}. If I searched that GUID1 without {}, it will not return. Another file, it is switched - I search for GUID2 and get the result GUID2, I search for {GUID2} and get no results.

**Comment by wobba** [comment]
Thank you for the information. I have logged the issue internally and will report back.

**Comment by siata13** [comment]
Hi, any updates here?

**Comment by vspinelli** [comment]
From today we having same issue.

After a manually request of re-indexing a library, UniqueID property value has changed from '{GUID}' to 'guid' (ex. '{2926D0B4-1600-4C7B-98F1-6039C73EBE08}' to '2926d0b4-1600-4c7b-98f1-6039c73ebe08') on all library items (files and folders).

**Comment by wobba** [comment]
Apparently there has been a design change to not have {} in `UniqueId`. If you want to search without braces you can now use `UniqueId` or `NormUniqueId`. If you want with braces you can use `XUniqueId`. Either way you need to change your code it seems (which is unfortunate imo ☹)

![image](https://user-images.githubusercontent.com/51104/127998367-fcb2fee8-f289-4201-a430-19b08a6b9296.png)

**Comment by siata13** [comment]
Thanks for the update. In that case I think the issue can be closed.

**Comment by wobba** [comment]
If I get the explanation of why the change was made, as it is breaking, I'll share.
