### ISSUE TITLE
SPFx Teams app supportedPlatform getting ignored

### ISSUE THREAD

**Issue by manufz** [SharePoint/sp-dev-docs#7162]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

When setting "supportedPlatform": ["mobile"] in the Teams app manifest the app still shows up in Teams Desktop and Browser.

### Steps to reproduce

1. Create a Teams app with one static tab and add the attribute "supportedPlatform": ["mobile"]

```
"staticTabs": [
        {
            "entityId": "b1feaf13-e470-40d4-ba43-9867b2c5ce53",
            "name": "Sample",
            "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?...",
            "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
            "scopes": [
                "personal"
            ],
            "supportedPlatform": ["mobile"]
        }
    ]
```

### Expected behavior

App should only show up in Teams mobile app.

**Comment by asith-w** [comment]
+1

**Comment by patmill** [comment]
Interesting - thanks for posting.  A few questions, as I am not overly familiar with this.  I assume you have created a customer teams app manifest and included it in your solution and then chose the "sync to teams" action in the app catalog.  Is this correct?  Or did you just create a manifest and upload it to teams directly?

Does anything change if your solution isn't spfx based and you just create a basic teams app?
