### ISSUE TITLE
NPM installation of  "npm install yo -g" fails for spfx framework SET up ( OnPrem)

### ISSUE THREAD

**Issue by nvgopi** [SharePoint/sp-dev-docs#7164]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

 Node.js     v8.11.3
 NPM         5.6.0
<img width="132" alt="spfx version" src="https://user-images.githubusercontent.com/31060544/125138483-547b7e00-e0d4-11eb-84bd-b9d8abef61dd.png">

Corporate Network Behing Proxy.

### Describe the bug / error

I am trying to install the sharepoint framework for 2019 ( OnPrem). Initially,  was **unable** to install packages and after running the npm config commands was successful in installing gulp package.

1. npm config set proxy
2. npm config set https-proxy
3. npm config set registry

<img width="734" alt="spfxgulp" src="https://user-images.githubusercontent.com/31060544/125139062-7295ae00-e0d5-11eb-8c70-4f821bd3d599.png">

The real problem comes when i try to install Yo package. 

npm install yo –g

The above command runs and gets installed however, while sanity check, The following error is thrown. I am not getting any Authentication Required error while installing "gulp",. However, when i try to install yo packages, am getting the authentication error messages. attaching a screenshot
<img width="960" alt="spfxyo" src="https://user-images.githubusercontent.com/31060544/125139870-ef755780-e0d6-11eb-9f47-09d5cf0fe080.png">

Is there any step which am missing ?

### Steps to reproduce

1. Install NodeJS 8.11.3
2. npm install gulp -g
3.npm install yo -g

### Expected behavior

Expecting the installation to complete sucessfully and able to create clientside webparts using yoman templates.

**Comment by nvgopi** [comment]
![image](https://user-images.githubusercontent.com/31060544/125322889-da314080-e303-11eb-92f4-d8f01b40c7d8.png)

It looks like the got node module is making a call and the request is failing as am behind Corporate Network Behind Proxy.

I did look at the index file as highlighted in the screenshot and noticed that there is no code for proxy support. When i digged into the got module on the web, found out that proxy support was added but looks like those changes didnt get pushed. 

https://github.com/alexsantos/got/blob/proxy-from-env/index.js  Line 223. 

As it has references to other modules, Wondering how to fix this to make it work. 

Also, Which yo template is ideal for setting up development for 2019 environment. 

I have 

Node : 8.11.3
NPM : 5.6 
Yo : 3.1.1

**Comment by m0jimo** [comment]
You can try to (It worked for me with SPFx 1.4.1)
- install Node 10 (I’m using nvm for switching the Node versions)
- remove node_modules
- (maybe cleared npm cache - but I’m not sure now)
- npm install (it needs to compile dependencies according to used Node version)
- gulp trust-dev-cert (to solve Proxy issue)
- gulp serve
and cross your fingers …

**Comment by patmill** [comment]
Sorry - this issue appears to be unrelated to SPFx, and is simply trying to install the yeoman package.  That's outside the scope of this issues list.
