### ISSUE TITLE
Errors calling graph from an SPFx WebPart in a Tenant where Microsoft Cloud App Security is enabled

### ISSUE THREAD

**Issue by michelcarlo** [SharePoint/sp-dev-docs#7167]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx 1.11
Google Chrome Version 91.0.4472.124

### Describe the bug / error

In a Microsoft Tenant where Microsoft Cloud App Security is enabled to monitor the sessions only for Teams and Exchange (not monitoring SharePoint), when we call Microsoft Graph even for an endpoint where it's not related to Teams/Exchange, we are getting errors, it seems somehow the token to access graph is being not obtained correctly.

**Error 01**: When trying to obtain the graph client object using msGraphClientFactory (spContext.msGraphClientFactory.getClient()), no error is thrown by the library, but the following error is thrown in the browser console (seems to be by any underlying library used to authenticate in graph):
![image](https://user-images.githubusercontent.com/20910957/125449599-dc2954ab-beaf-492a-b69a-88afb7738ffd.png)

**Error 02**: As the exception is not thrown by the SPFx library and by consequence we cannot manage it. When we try to call a graph endpoint afterwards and the following exception is thrown:
"Token renewal operation failed due to timeout."

### Steps to reproduce

Initialize the Graph Client and call any endpoint from an SPFX webpart:

```
this.graphClient = await this.spContext.msGraphClientFactory.getClient(); 
let drives = await this.graphClient.api("/me/drives").version("v1.0").get();
```

This same code would work in a tenant without Microsoft Cloud App Security enabled.

It would also work in the tenant where MCAS is enabled (but not monitoring SharePoint), by manually appending the mcas.ms  domain to the Tenant SharePoint address:

Example:
Instead of navigating to https://contoso.sharepoint.com/sites/mysite, navigate to https://contoso.sharepoint.com.mcas.ms/sites/mysite

### Expected behavior

Call to graph API from SPFx to work normally without issues.

**Comment by lucabandMSFT** [comment]
We made significant improvements on the authentication stack in the past months. Can you please check if the error still persist?

**Comment by michelcarlo** [comment]
The error still persists. 

It seems a failure due to trying to open the hidden popup to authenticate in Graph in a different domain....
For example, the site is on the address: https://contoso.sharepoint.com/sites/mysite, and tries to open the hidden popup on https://contoso.sharepoint.com.mcas.ms/sites/mysite

**Comment by lucabandMSFT** [comment]
@michelcarlo , would be possible for you to share the SPFx Package and instructions on how you did set up the monitoring on your tenant? We would like to see if we can repro the issue.

**Comment by michelcarlo** [comment]
Hi @lucabandMSFT, I will collect the requested information and update this thread soon with a sample SPFx solution and the policies details...

**Comment by michelcarlo** [comment]
Hi @lucabandMSFT ,

As mentioned, here are the steps to reproduce the issue:

**1) Set up a named location in AAD:**
<img width="458" alt="01_AADNamedLocations" src="https://user-images.githubusercontent.com/20910957/143408855-e1b87d1e-cc22-4dd9-b9af-1c983d2ac6cd.PNG">

**2) Create a conditional access policy targeting Exchange only**
<img width="316" alt="01_Apps" src="https://user-images.githubusercontent.com/20910957/143409296-509a9c8e-8f3f-44a2-92b4-048ae5a3550f.PNG">

In this CA Policy, target  a named location to trigger it (or exclude it, both ways it would happen when it's triggered)
<img width="447" alt="02_Conditions" src="https://user-images.githubusercontent.com/20910957/143409020-f6af9e21-2b03-4b1c-8b0c-02ba551b88d1.PNG">

For the session policy, use App enforced restrictions + Conditional Access App Control setting to Monitor only (which triggers MCAS)
<img width="416" alt="03_AppRestrictions" src="https://user-images.githubusercontent.com/20910957/143409484-9f8a3343-d36d-406d-8ec8-5553e23e317b.PNG">

For testing purposes I am targeting a specific user but in the real scenario it also happened when targeting everyone.
<img width="332" alt="04_Users" src="https://user-images.githubusercontent.com/20910957/143409650-10c28bde-78e9-41c7-a052-063529a5fe6f.PNG">

Sample solution attached below. I cannot share the original but created a simple one to illustrate the issue. 

It is a simple webpart with two buttons, one will make a call to graph and list the current user's drives and the other will list the current user's calendars.

Both actions fail as specified on this issue, while I understand that the calendar might fail due to Exchange being in the policy, the Drives piece seems awkward to fail...

Full solution (ZIP - SPFx 1.13): 
[MCASIssuesTest-main.zip](https://github.com/SharePoint/sp-dev-docs/files/7601544/MCASIssuesTest-main.zip)

**Comment by lucabandMSFT** [comment]
Hey @michelcarlo, apologies for the delay in answering back. Can you please tell us if the issue still exists? We have done a bunch of work in this area and we might have fixed your scenario as well (as we did work to tackle something similar).

Thanks.
