### ISSUE TITLE
OOTB SharePoint Web Parts Broken by SPFx App Customizer

### ISSUE THREAD

**Issue by sunmorgus** [SharePoint/sp-dev-docs#7169]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: N/A
- SPFx version: 1.12.1
- Node.js version: 10.22.x

### Describe the bug / error

We built an SPFx App Customizer that injects a remotely hosted script that was built using parceljs. When compiling this remote script with parcel, we began to see issues where the OOTB SharePoint Web Parts were failing to load properly, with various error messages (example screenshots below).

Example error messages (under the "Something went wrong" title):
1. `r is not a constructor`
2. `[object Object]`

Screenshot 1 - Images Web Part failing to load in the top row, but loading fine in the bottom row
![image](https://user-images.githubusercontent.com/2287216/125489347-ea8a3313-b21b-4dfa-8c92-de0e261c2bc9.png)

Screenshot 2 - Other OOTB web parts failing to load, with error messages
![image](https://user-images.githubusercontent.com/2287216/125489692-627bfe8e-ef0b-4696-8df8-72318f7c737e.png)

We had an MS Support Premier ticket open and through a _lot_ of debugging, we were able to determine that something related to using parcel for compiling the remote script was causing a conflict with the OOTB web parts (which we felt may have been related to this parcel issue: https://github.com/parcel-bundler/parcel/issues/2451). Upon determining that, we switched the remote script over to use webpack and saw the vast majority of the issues disappear (with a few more intermittent cases here and there that we haven't been able to determine the cause of).

So... 2 reasons for creating this bug:
1. For awareness, in case any other developers out there are doing something similar and running into issues that they can't resolve
2. Because I feel as though this may not be completely gone (thanks to us still getting the errors somewhat intermittently and not in a reproducible way)

### Steps to reproduce

1. Create a plain node.js web application with some simple HTML to generate a header/footer and compiles with parcel
2. Create an SPFx App Customizer, that adds a script tag to the header of the page, pointing to the compiled code above
3. Add the app customizer to a page with OOTB SharePoint web parts
4. Refresh the page periodically, the OOTB web parts will fail

### Expected behavior

The App Customizer and all OOTB Web Parts should load correctly, without any errors. Also, to be able to use any build tool (like parcel) to compile a node.js project without needing to deal with potential conflicts within SharePoint pages (with respect that gulp is the supported tool for SPFx).

**Comment by patmill** [comment]
I'll be honest, when you start injecting script onto a page that overrides base level functionality / introduces new polyfills / messes with global variables, is built with alternate tools (rather than webpack) it becomes quite tricky (nigh impossible) to guarantee what will work or not.  The more you can stick to using webpack / require / etc. the safer your code will be.

Thanks for posting your experience for others to view.

**Comment by sunmorgus** [comment]
Yeah, I didn't realistically figure that posting the issue here would lead to some sort of "fix" (especially when we already resolved our issue by switching to webpack); was merely wishing to get the information out there just in case others ran into it.

Hopefully however, nobody has to jump through the same types of hoops we had to for this particular use case lol.
