### ISSUE TITLE
Required Node version 10.

### ISSUE THREAD

**Issue by m0jimo** [SharePoint/sp-dev-docs#7170]
I have tried to create an environment for Sharepoint app and extension on two computers with Win 10.

The only combination which was working was with **Node 10** (I also tried 12, 14, 16). Other mentioned combinations like Node 12+ and Gulp 3/4 didn't work. 

Extension package.json
```
 "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }
}
```
App package.json
```
"engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "serve": "gulp serve",
    "build-1": "gulp bundle --ship",
    "build-2": "gulp package-solution --ship",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.11.0",
    "@microsoft/sp-tslint-rules": "^1.11.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@types/request": "^2.48.5",
    "core-js": "^3.6.5",
    "office-ui-fabric-core": "^11.0.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  }
```
This information could save some time to others if using already the latest node version and having problem with starting the sharepoint app or extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nvgopi** [comment]
@m0jimo , Thanks for the information. Is this for Proxy environment ? Also, What was the npm version and also Yo version which was installed?

**Comment by m0jimo** [comment]
Hi @nvgopi , yes, I'm behind a corporate Proxy. 
- I needed to run `gulp trust-dev-cert`
- Yo - 4.20
- npm - 6.14.12

Errors were related to Gulp 3 and Node 12+ [error](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node-js)
Gulp 4 also didn't work but I don't remember what was the error.

If you'd like more tests and specific errors for versions combination, let me know.

**Comment by bcameron1231** [comment]
I highly recommend reviewing the SPFx Compatibility matrix. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility

It looks like you are using SPFx 1.4.1 for On-Premises. 

The only *supported* node versions are v6 and v8. v10 generally works for this version of SPFx though, 12/14/16 will definitely not work.

**Comment by m0jimo** [comment]
I’ve v 1.4.1. (as defined in package.json - see above) but it was generated by yeoman. I just followed the instructions from the [documentation page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment) :-). There are notes about various versions of SPFx but not how to install the latest. 
I just wanted to point out that as it is written (and I followed the steps on the page) it works only with Node v10.

**Comment by bcameron1231** [comment]
Sounds good!

Yea the documentation implies you are using the latest, and SharePoint Online. If you are building something that Targets 2016 or 2019, it will use an older version of SPFx that is supported. If you are on-premises, check out the two links at the bottom of that documentation page you linked. There is an entry for developing on 2016 and 2019.

**Comment by nvgopi** [comment]
Which specific version of nodeJs did you install. I am running into issues with 10.24.0

**Comment by m0jimo** [comment]
10.24.1 64bit
