### ISSUE TITLE
Whitesource bolt code review declares underscore library as a vulnerability

### ISSUE THREAD

**Issue by thalluripk** [SharePoint/sp-dev-docs#7172]
@microsoft/sp-build-web package has a dependency on underscore-1.8.3.js. This version of underscore.js is identified as a vulnerability by Whitesource bolt code review tool.

We are unable to use this as it doesn't meet security compliance. Can you update this package to the latest version, please? Thank you

**Comment by AJIXuMuK** [comment]
Hello @thalluripk - what version of SPFx are you using?
I don't see `underscore` to be referenced in the latest releases of SPFx.
