### ISSUE TITLE
Missing Legal Information Alerts - Component Governance

### ISSUE THREAD

**Issue by bhanuchintha** [SharePoint/sp-dev-docs#7173]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hi Team, We see that the below packages are giving the component governance alerts - "Missing Legal Information". Can you please help us here in taking the next steps. Do you want us to upgrade to SPFx 1.12 version for this. Is SPFx v 1.12 is stable for production use.

![image](https://user-images.githubusercontent.com/19674673/125737693-5611cd0c-e2ad-4438-9ed1-569e6626b0f9.png)

Thanks & Regards,
Bhanu

### Steps to reproduce

1. Use the respective package and you will see the issue in component governance alerts.

### Expected behavior

No component governance alerts should be coming up when using these packages

**Comment by AJIXuMuK** [comment]
Hi @bhanuchintha - sorry for the long delay.

Could you please check if that's still an issue for you with the latest SPFx version, which is 1.14.0?
