### ISSUE TITLE
Question regarding Contoso photo-printing add-in example in js and python

### ISSUE THREAD

**Issue by DavidBerger98** [SharePoint/sp-dev-docs#7174]
I am building a Javascript frontend and Python backend to achieve almost exactly the same as the Contoso photo-printing add-in example in this article. But some things are not clear to me:

Under step 6, how does the request to ACS look like as an HTTP request? Also, isn't ACS deprecated already?

And regarding scopes: How can I keep them as small as possible? With list.Read and web.Read my add-in could theoretically access all files of the user on that sharepoint tenant, right?
I would like a scenario where the user can browse through all their files, select some, confirm and have that my add-in only ever knows about those selected files and is able to download them in the backend. Is that possible?

Thank you in advance for your answer!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9be50ae2-2435-480a-0c1e-efca679cd00e
* Version Independent ID: d3c81315-c73e-61c8-2287-dc6e6e5eec5c
* Content: [Authorization Code OAuth flow for SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins)
* Content Source: [docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
I'll try to unpack some of this. 

ACS is deprecated but not for SharePoint Add-Ins. SharePoint Apps can still use ACS and are unaffected by that retirement.

The HTTP Request, while I don't have an example, I believe it would be something like this. 

It would make a post call to https://accounts.accesscontrol.windows.net/{YourTenantId}/tokens/Oauth/2.

The body content of the request would be something like...

  'grant_type': "authorization_code",
    'resource': "00000003-0000-0ff1-ce00-000000000000/https://yoursharepointsiteurl.com/{YourTenantId}",
    'client_id': "your client Id",
    'redirect_uri': "your redirect URL",
    'client_secret': "your client secret",
    'code': "your auth code"
}

Unfortunately, the scopes you define are as minimal as possible. There isn't a way to define smaller scopes than this. 

-------------------------------------
Now, this example is a bit dated, you technically don't need ACS, you could just create an App Registration in Azure and give the delegated permissions for a user if you don't want to ACS, and want to use MSAL instead.

**Comment by DavidBerger98** [comment]
Thank you for the quick answer!

The post call to https://accounts.accesscontrol.windows.net/{YourTenantId}/tokens/Oauth/2 gives me the following error:
`"AADSTS900192: Unable to determine the tenant identifier from the request. Client ID 'xxxx' does not specify a tenant realm."`

I double and triple checked if the Client and Tenant IDs were correct and tried registering another App with Azure AD.

And generally about the scopes: Do you know by chance how other add-ins solved this problem? Maybe have the scope on a specific "to print" folder? Or ask the admin to create a "printing" user that has very limited access to folders? Or something completely different?

**Comment by bcameron1231** [comment]
Is your tenantId, using {} for the guid, or without? Should be doing it without the brackets.

**Comment by DavidBerger98** [comment]
Yes, I tried it without the braces.

**Comment by DavidBerger98** [comment]
The error is complaining about the Client ID anyway and not the Tenant ID. Could the problem be that I am using Sharepoint Online and registered the Add-in via .../_layouts/15/AppRegNew.aspx?

**Comment by DavidBerger98** [comment]
Thank you for the answer and sorry for the late reply!

I ended up having to write "{Client ID of the Add-in}@{Tenant ID}" (with @ not &) as the "client_id" for the request.
I have to say the naming is a little confusing...

Now there's another error saying "AADSTS500012: Resource application name '00000003-0000-0ff1-ce00-000000000000/https://{sharepoint host}.com/{Tenant ID}' is not valid."
Couldn't find anything useful looking up the error code.

**Comment by DavidBerger98** [comment]
Okay, I found the issue: "resource" should be "00000003-0000-0ff1-ce00-000000000000/{sharepoint host WITHOUT https://}@{YourTenantId}".

Also the "grant_type" "authorization_code" is invalid and must be set to "client_credentials".

So the request as a whole would look like this:

POST https://accounts.accesscontrol.windows.net/{tenant_id}/tokens/Oauth/2
```
grant_type: client_credentials
code: {auth_code}
resource: 00000003-0000-0ff1-ce00-000000000000/{host_url}@{tenant_id}
client_id: {client_id}@{tenant_id}
client_secret: {client_secret}
redirect_uri: {redirect_uri}
```

host_url is without "https://" (e.g. contoso.sharepoint.com)
client_id is the ID of the registered add-in.
