### ISSUE TITLE
Delete Modern site using Rest api is not working

### ISSUE THREAD

**Issue by shashangmarchawala** [SharePoint/sp-dev-docs#7175]
Delete Modern site using Rest api is not working. Everytime below error is coming.  I am passing correct header, body

_Error message_ : **the parameter 'SiteId' in the request payload is not a valid parameter for the operation 'Delete'.**

I am using below given method for this.

**url: /_api/SPSiteManager/delete
method: POST
accept: application/json;odata.metadata=none
odata-version: 4.0
body:
{
  "SiteId":"d11e59ca-1465-424c-be90-c847ba849af5"
}**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b24cbb-892e-8e39-8a24-ad5997cae065
* Version Independent ID: b643463a-91b8-3230-e314-6522f35e5bd9
* Content: [Create Modern SharePoint Sites using REST](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest#feedback)
* Content Source: [docs/apis/site-creation-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/site-creation-rest.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
The parameter is `siteId`

With a lowercase **s**

**Comment by NR010** [comment]
Hi all, I am running into the same issue as @shashangmarchawala when following the official documentation. When I try the suggestion from @bcameron1231 the following error is generated:

 "status": 400,
  "message": "Cannot handle the data at position 10

Both messages only appear if I remove the odata-version statement in the header. If I leave that in, the error message is:

 "status": 400,
  "message": "Unexpected response from the service

**Comment by fowl2** [comment]
thanks for this, was banging my head against a wall! created #7292 to fix this
