### ISSUE TITLE
No Documentation on how to remove a SharePoint App Only registration

### ISSUE THREAD

**Issue by groogiam** [SharePoint/sp-dev-docs#7178]
Would it be possible to details about how to remove a registration to this page? Or at least have a link to this documentation on this page in the event it exists somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by michaelmaillot** [comment]
Hi @groogiam,

You can retrieve registered app permissions in the Site Collection App Permissions page `AppPrincipals.aspx` from the Site Collection where you've added permissions.

More info [here](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins#retrieve-add-in-registration-and-add-in-principal-information)

**Comment by groogiam** [comment]
Great thanks!
