### ISSUE TITLE
Icon set via "iconImageUrl" property generate wrong possition in toolbox on Safari

### ISSUE THREAD

**Issue by gjanblaszczyk** [SharePoint/sp-dev-docs#718]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When I set icon using "iconImageUrl" it should looks fine on all supported browsers.

#### Observed Behavior
Icon is not centered like other icons.
![screen shot 2017-07-11 at 2 38 06 pm](https://user-images.githubusercontent.com/5346546/28068998-20c442b4-6648-11e7-8733-82a7b6332d2d.png)

#### Steps to Reproduce
Try to customize webpart icon via "iconImageUrl" property and checks results on Safari browser.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
