### ISSUE TITLE
No support for Private Channel sites

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#7184]
Testing indicates that a Site Design/Template cannot be applied to a Private Channel site. Is this a true/intended limitation or an accidental byproduct of the deisgn/template being assiciated with a specific underlying site template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi, I am able to apply a custom Site Design to a Private Channel Team site, the Microsoft Template do not appear to show up.

Can you confirm the template works on other sites? What sort of errors are getting when trying to apply it?

**Comment by sparkitect** [comment]
@bcameron1231 In a Private Channel site, **both** the "From Microsoft" and "From your organization" tabs in the "Select a template" dialog are empty while in a normal Team site they show up and can be applied without issue.

I've even tried the PowerShell cmdlets and they do nothing (no output whatsoever).

How were you able to do it?

**Comment by bcameron1231** [comment]
I did it the same way you just mentioned. 

I created the private channel, navigated to the private channel site. The Microsoft Templates are empty (actually throw an error in dev tools), but my custom Site Designs were available to me to select from... 

In transparency, I don't know if they should or shouldn't be visible... but in my tenant they are...

**Comment by dewcatpaint1** [comment]
We have updated to allow site templates to be utilized on channel sites. You should begin to see these in your channel sites as well as be able to utilize PowerShell as well.
