### ISSUE TITLE
Column Types Reference?

### ISSUE THREAD

**Issue by QuSimone** [SharePoint/sp-dev-docs#7185]
![image](https://user-images.githubusercontent.com/72839029/126241762-c6abab38-8d97-478d-8eaa-78a3e41f2c1f.png)

I am working on custom JSON formatting for a SharePoint site. I am utilizing internal column types in the custom view. Is there anywhere for me to see the schema for these fields? For example, I can get the name of a Person column type by "[$Person.title"], but I found that randomly. How would I get the image associated? Is there some kind of reference page for this, or how are we supposed to know the internal fields?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi. You can go to List Settings, and click on the column you want. The internal name of the column will be displayed in the corresponding URL after the **&Field=** parameter.

**Comment by QuSimone** [comment]
Thanks. I have utilized that trick before to identify the internal name. However, this does not capture the internal fields of an internal name. Here's what I mean:

![image](https://user-images.githubusercontent.com/72839029/126582593-f4c84117-578f-4243-a7b8-99f957f1f4ef.png)
We have a field, 'Contact' which is an O365 user/group. The internal name is 'Contact'.

However, to access the Contacts name, you must reference 'Contact.title'. I found this by guessing semi-randomly. I am unsure how to get the Contact profile photo. I have tried 'Contact.image, Contact.picture, Contact.url' and various others. I would like a link to some sort of reference or some way to find the name of these fields without guessing.

**Comment by CallumCrowley** [comment]
This information can be found at the bottom of the [Use column formatting to customize SharePoint](https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#currentfield) article, under the section "@currentfield".

For example, the article provides a definition for the People object you're referring to:

`{
   "id": "122",
   "title": "Kalya Tucker",
   "email": "kaylat@contoso.com",
   "sip": "kaylat@contoso.com",
   "picture": "https://contoso.sharepoint.com/kaylat_contoso_com_MThumb.jpg?t=63576928822",
   "department":"Human Resources",
   "jobTitle":"HR Manager"
}`
