### ISSUE TITLE
Ribbon icon from classic custom action renders incorrectly

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#719]
#### Category
- [x] Bug

#### Expected or Desired Behavior
Icon images should show correct in modern views.

#### Observed Behavior
On the drop-down list for more actions a "classic" custom action has CSS setting the width/height to 16x16 pixels, without re-sizing the image like it does if the icon is shown on the ribbon.

![image](https://user-images.githubusercontent.com/51104/28107705-270c9256-66e9-11e7-8ecc-c18cfe5632e3.png)

By adding `background-size: cover` to the CSS (as is used when rendering on the ribbon), the icon is rendered correctly.

![image](https://user-images.githubusercontent.com/51104/28107744-5cd62834-66e9-11e7-9e78-714ea3bfae15.png)

#### Steps to Reproduce
Register a classic custom action with a 32x32 pixel icon on a list/library and see that it's not resized as expected in the more action drop-down.

**Comment by patmill** [comment]
Hey Mikael - sorry for the delay.  Just to confirm, as I think I need to send this off to a different team - this doesn't have anything to do with the preview of modern extensions, this is just using the existing custom actions?

**Comment by wobba** [comment]
@patmill correct, it has to do with how modern lists/libs render classic custom actions.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
