### ISSUE TITLE
SPFX ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by hubghs** [SharePoint/sp-dev-docs#7191]
I have updated machine with the latest version of Node.js LTS v14 with the below configurations. The latest recommended version is LTS v14.

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

node -v = v14.15.0, npm -v = 7.19.1

gulp -v
CLI version: 2.3.0
Local version: 3.9.1

I have updated the gulp Local version to 4.0.2.

Now getting invalid glob function because of {allowEmpty: true}

I am looking for gulpfile.js updated file

Steps to reproduce
https://docs.microsoft.com/en-us/answers/storage/attachments/114656-primordials.png
https://docs.microsoft.com/en-us/answers/storage/attachments/115053-gulp-build.png
https://docs.microsoft.com/en-us/answers/storage/attachments/115052-gulp-serve.pngv

**Comment by bcameron1231** [comment]
Hi, to confirm, you are running SPFx 1.12 and a solution targeting SharePoint Online?

**Comment by hubghs** [comment]
> Hi, to confirm, you are running SPFx 1.12 and a solution targeting SharePoint Online?

Target is SharePoint Online and @microsoft/generator-sharepoint@1.12.1

**Comment by hubghs** [comment]
> Hi, to confirm, you are running SPFx 1.12 and a solution targeting SharePoint Online?

Any update on this please.

**Comment by bcameron1231** [comment]
Hi, can you upgrade your gulp version to Gulp 4.

**Comment by patmill** [comment]
After updating gulp, if you create a new project, does the issue still exist?
Does the same issue happen with Node 12?
