### ISSUE TITLE
Use HTTPS for localhost?

### ISSUE THREAD

**Issue by rolandoldengarm** [SharePoint/sp-dev-docs#72]
To get workbench running, you need to manually enable mixed content loading, as O365 is HTTPS and localhost is HTTP.
If gulp would serve as HTTPS, we wouldn't have this issue? Can this be implemented?

**Comment by chakkaradeep** [comment]
@iclanton and I had talked about this before. Will try to dig more if this is possible and if not why.

**Comment by wictorwilen** [comment]
Ping me. I've done just that for my own framework.

**Comment by waldekmastykarz** [comment]
I got HTTPS to work on the SharePoint Framework:

![spfx-https](https://cloud.githubusercontent.com/assets/11164679/17970979/1f5a0db6-6ad9-11e6-9d81-22840f28e793.png)

- in node_modules/gulp-core-build-serve/lib/ServeTask.js added `https:true` to gulpConnect.server on line 39
- in ./temp/workbench.html changed all http:// urls to https://
- in ./temp/manifests.js changed all http:// urls to https://
- in node_modules/@microsoft/sp-client-preview/dist/sp-client-preview.js changed the URLs to https: in lines 10811 and 10812
- in node_modules/@microsoft/sp-module-loader/dist/sp-module-loader.js changed the URL to https in line 2195

On my dev machine (OS X) I got a warning that the certificate used was untrusted but could proceed anyway. I had SSL setup in the past so can't tell what else you would need to configure on a vanilla OS X or Windows machine.

**Comment by chakkaradeep** [comment]
How common of a setup is to create/manage SSH keys?

**Comment by StfBauer** [comment]
@chakkaradeep express web server, browser-sync create them on the fly. All you have to do is to flip a switch to use HTTPS.
Working 99% of my time with other generators in HTTPS. It doesn't hurt even when not needed ;)
Naturally does 'yo Office' too use HTTPS by default. It won't work without.

Except the small error message you get when it is self signed.

**Comment by waldekmastykarz** [comment]
Always using HTTPS since I'm always deploying to HTTPS. Makes it easy to catch any mix-mode errors dev-time.

**Comment by iclanton** [comment]
I'll look into this today. Sounds like a pretty straightforward fix.

**Comment by rolandoldengarm** [comment]
Nice :D This is awesome guys, to get feedback / fixes so quickly!

**Comment by nyn3x** [comment]
I just updated to Drop 2 and switched my local serving from HTTP to HTTPS - but how am I telling the workbench in O365 to pickup my local webpart via HTTPS?

**Comment by patmill** [comment]
@nyn3x - the workbench has been updated to check http and https. Once you hit your local host and accept the cert warning, you shouldn't need to do anything special in the SharePoint hosted workbench, it should "just work".

**Comment by nyn3x** [comment]
@patmill my bad. The browser denied access to the https site because of the untrusted self-signed certificate. Thus the fallback to http, which was displayed to me.

**Comment by getsetbro** [comment]
OSX hosts https files at "[sys-name].local:4321/" not "localhost:4321/". When workbench.aspx looks to "localhost:4321/" and does not find the files.

![image](https://cloud.githubusercontent.com/assets/442793/18682905/add6561c-7f33-11e6-873c-24df2f5ac35d.png)

**Comment by engmyahya** [comment]
#SPFX_Issues
I am using Windows 10 professional licensed edition, Mcafee antivirus 10.0.5 (disabled), I installed the following 

Your environment has been set up for using **Node.js 8.9.3 (x64) and npm.**

C:\Windows\System32>**npm -v**
**3.10.10**

C:\Windows\System32>**gulp -v**
**[18:26:07] CLI version 3.9.1**

C:\Windows\System32>**npm view @microsoft/generator-sharepoint version**
**1.4.0**

I created Web Part, using    yo @microsoft/sharepoint and execute gulp trust-dev-cert
and then execute gulp serve


I got the following 

**This site can’t provide a secure connection

localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR**

-----------------------  Please Help me urgently ----------------------



![image](https://user-images.githubusercontent.com/12251024/33797114-9de6fe90-dd1b-11e7-9a77-3c8374ae95e6.png)
