### ISSUE TITLE
Incorrect style for labels on modern pages add ":" as content after

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#720]
#### Category
- [x] Bug

#### Expected or Desired Behavior
If a label want's a ":" it should be added by the code, not as CSS from Office UI Fabric

#### Observed Behavior
On a modern page (or in a custom SPFx part) where `<label>` is used CSS adds a colon after the label text. By clicking "Send by email" on a modern page, you see two colons which is impacted by this:

![image](https://user-images.githubusercontent.com/51104/28114152-d1a9332a-66ff-11e7-9564-89a9a59a0ff8.png)

If you have a label with "required", then this will use the same CSS to add a red asterisk, overriding the colon.

#### Steps to Reproduce
* Navigate to a modern article page, click "Send by email"
* Create a SPFx webpart with a react <Label> control, and you will see an automatically added colon after the label text.

**Comment by mcmynn83** [comment]
This is the design of the product.  If you use a label we style it with a colon.

**Comment by wobba** [comment]
And if you set the label as required, colon and red star? Both use same css.
