### ISSUE TITLE
mgt-react/dist/es6/spfx has no exported member 'GroupType'.

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#7202]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I am updating a SPFx Web Part from mgt + mgt-react to mgt-spfx + mgt-react.

with mgt-react, I was using:
`import { GroupType, Login, PeoplePicker, Person, PersonType, TeamsChannelPicker } from '@microsoft/mgt-react';`

I changed it to:
`import { GroupType, Login, PeoplePicker, Person, PersonType, TeamsChannelPicker } from '@microsoft/mgt-react/dist/es6/spfx';`

Now I am getting errors because GroupType and PersonType are not exported members.

Am I missing something? It seems to me that for consistency, such objects could also be exported members of mgt-react/dist/es6/spfx . Currently I cannot follow this recommendation:
![image](https://user-images.githubusercontent.com/40323257/126883611-24541221-f3c4-42fb-95c1-3cc505671b68.png)

**Comment by patmill** [comment]
Can you look at the packages and see what is exported?  Did they change a name?  The library itself isn't something that the SPFx team builds / supports, so we aren't completely familiar with it.  @waldekmastykarz  - any ideas?

**Comment by waldekmastykarz** [comment]
@PathToSharePoint, if you look at https://docs.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx#react, you can see that only components are imported from `@microsoft/mgt-react/dist/es6/spfx`. Enum types are being pulled in from `@microsoft/mgt-spfx`. Could you check if that helps?

**Comment by PathToSharePoint** [comment]
@patmill @waldekmastykarz thanks for the replies. I understand the current structure, but I was curious why. Other libraries I know offer a single point of entry, and I thought that was considered a best practice.

I'll close this thread as mgt-spfx is not supported by this team.
