### ISSUE TITLE
Instructions to create app not working

### ISSUE THREAD

**Issue by petercranston** [SharePoint/sp-dev-docs#7205]
Hi, I'm trying to follow the instructions on this page for creating an app to use for authenticating my code to run against our sharepoint site. I have created the app from the appregnew.aspx page, however, when on the appinv.aspx page, the 'lookup' button does not auto-populate the remaining fields. Furthermore, clicking 'Create' does not presented the permission consent dialog (it seems to have no effect from what I can see).

I note the warning of ACS being retired, but I am struggling to understand the alternative approaches for app authentication from the links provided.

Are you able to advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by michaelmaillot** [comment]
Hi @petercranston, what is the purpose of your app if I may ask?

As Microsoft stated, the better approach regarding authentication in an app permission context is to use the Azure AD one.

But if the purpose is to work with the User Profile (write operations) , then the only option is using ACS. More info about limitations [here](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly#what-are-the-limitations-when-using-app-only).

When using the Azure AD App registration, you have to know how does your app will authenticate to SharePoint. An important info to get is that authentication to SharePoint only works with a certificate (not client id / secret).

About authentication, if your app is built on .NET Core, you have the [PnP Framework](https://github.com/pnp/pnpframework) library that handles many authentication flows, depending on you needs.

**Comment by bcameron1231** [comment]
If it's not populating Title,AppDomain and Redirect Url from AppInv, I suspect your Client ID may be wrong. Try to re-generate your App in AppRegNew. I'm not seeing this issue in any of my environments currently.
