### ISSUE TITLE
There is no dropdwon list shown for communication site provisioning

### ISSUE THREAD

**Issue by frankchen76** [SharePoint/sp-dev-docs#7207]
As recent site design and site script rolling out, There is no dropdwon list shown for communication site provisioning which allows the end user to select. what would be the approach to apply a custom site design and site script to a new communication site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
From the home page of a site, click the cog > Site Designs you should see a dropdown of site designs available in your tenant.

![image](https://user-images.githubusercontent.com/58050310/127173529-f4a0164b-8c71-440d-bcb9-e56a1e91128a.png)

Alternatively, you might see the new option to "Apply a site template" in the cog menu. Clicking this option displays a pop up window and you should see any Site Designs you've added to your tenant under the "From your organisation" tab. More information can be found here:

[Apply and customize SharePoint site templates](https://support.microsoft.com/office/apply-and-customize-sharepoint-site-templates-39382463-0e45-4d1b-be27-0e96aeec8398)

**Comment by dewcatpaint1** [comment]
With the change to Site Templates we have transitioned this over from the site designs drop down into using the Site Template gallery.  Please advise if this does not complete your scenario.
