### ISSUE TITLE
Getting the actual site URL if modern team site already exists

### ISSUE THREAD

**Issue by litwi1rm** [SharePoint/sp-dev-docs#7212]
Regarding the following section in the documentation: 

_The following would create a Microsoft 365 group and an associated "modern" team site with a URL of `https://[tenant].sharepoint.com/sites/mymodernteamsite`

HTTP
```
Copy
POST https://graph.microsoft.com/v1.0/groups
Content-type: application/json
Content-length: 200

{
  "description": "description",
  "displayName": "My modern team site",
  "groupTypes": [
    "Unified"
  ],
  "mailEnabled": true,
  "mailNickname": "mymodernteamsite",
  "securityEnabled": false
}
```

mailNickname determines the URL, however, I've noticed that if `https://[tenant].sharepoint.com/sites/mymodernteamsite` already exists it will create the site at `https://[tenant].sharepoint.com/sites/mymodernteamsite2` and there seems to be no way to know this via the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning 'modern' team sites programmatically](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
You can check the site URL via the group ID which is returned in the [response](https://docs.microsoft.com/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#response-1) using the Graph API call below:

`https://graph.microsoft.com/v1.0/groups/{site-id}/sites/root`

This returns the `webUrl`

More information can be found here:

[Access a group team site](https://docs.microsoft.com/graph/api/site-get?view=graph-rest-1.0&tabs=http#access-a-group-team-site)

**Comment by litwi1rm** [comment]
This is perfect thanks @CallumCrowley!
