### ISSUE TITLE
Error when using gulp serve

### ISSUE THREAD

**Issue by subwizzll** [SharePoint/sp-dev-docs#7214]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hi I am getting the following error after attempting to run "gulp serve"

I am new to SPFx and the node/npm technology as well.

Any feedback to help resolve this would be greatly appreciated!

Error: Cannot find module '@microsoft/sp-build-web'
Require stack:
- C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\sample-webpart-name\gulpfile.js   
- C:\Users\ME\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Users\ME\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\ME\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js
- C:\Users\ME\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js      
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)    
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\sample-webpart-name\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)    
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [       
    'C:\\Users\\ME\\Desktop\\SharePoint\\sp-dev-fx-webparts\\samples\\sample-webpart-name\\gulpfile.js',
    'C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\index.js',
    'C:\\Users\\ME\\AppData\\Roaming\\npm\\node_modules\\gulp\\bin\\gulp.js'
  ]
}

Here are my package versions:

node -v
v14.15.0

npm -v 
6.14.8

gulp -v
CLI version: 2.3.0
Local version: 4.0.2

npm ls -g --depth=0 @microsoft/generator-sharepoint
C:\Users\ME\AppData\Roaming\npm
`-- @microsoft/generator-sharepoint@1.12.1 

yo --version
4.2.0

### Steps to reproduce

1. Cloned the sp-dev-fx-webparts repo to my preferred directory and opened with VS Code.
2. In terminal: cd .\sp-dev-fx-webparts\samples\sample-folder-name
3. In terminal: npm install
         Which returns the following: [](https://github.com/subwizzll/logs/blob/main/npmInstallLog.txt)
               
4. In terminal: gulp serve

### Expected behavior

Workbench environment to launch in the browser...

**Comment by bcameron1231** [comment]
Hi. Try deleting your node_modules folder for the web part, and re-run npm install

**Comment by subwizzll** [comment]
@bcameron1231 Thank you for the suggestion however this did not work for me...

'@microsoft/sp-build-web' seemed to not be installed globally so I ran 'npm install @microsoft/sp-build-web -g' and still received the same error...

This is perplexing to me, because when following the tutorial 
@: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment 

and then the following tutorial @: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part 

gulp serve spins up the workbench without a hitch...

**Comment by bcameron1231** [comment]
hmm something is strange. So what do you see when you run npm install? Your original posts shows empty.

**Comment by subwizzll** [comment]
My apologies, I had meant to leave a link to a text file in the initial post.

Thank you for your help, here is the raw output:

`
> modern-calendar@1.0.2 preinstall C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar
> npx npm-force-resolutions

npx: installed 6 in 2.876s

> node-sass@4.12.0 install C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\node-sass        
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\ME\\Desktop\\SharePoint\\sp-dev-fx-webparts\\samples\\js-modern-calendar\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python38\python.EXE
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Program Files\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ME\\Desktop\\SharePoint\\sp-dev-fx-webparts\\samples\\js-modern-calendar\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar\node_modules\node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ME\AppData\Roaming\npm-cache\_logs\2021-07-31T00_57_24_084Z-debug.log
PS C:\Users\ME\Desktop\SharePoint\sp-dev-fx-webparts\samples\js-modern-calendar> `

**Comment by bcameron1231** [comment]
Thank you. To confirm, you are trying to use the JS-Modern-Calendar from the samples repository. Have you tried to do an upgrade to the solution, because from what I can tell, that solution is built on SPFx 1.11, which does not support node 14.

SPFx 1.11 requires node v10, gulp 3

**Comment by subwizzll** [comment]
Okay, I used nvm to roll back to node v10.19.0 and it works, thank you!

**Comment by bcameron1231** [comment]
Awesome. Glad it worked out!
