### ISSUE TITLE
Frustrated that these instructions don't work

### ISSUE THREAD

**Issue by DevelopMR** [SharePoint/sp-dev-docs#7216]
When using scripted installers they should work out of the box.  We shouldn't have to worry about 15 items being deprecated or about local/global concerns.  I don't want to spend 3 days figuring out otherwise useless information when I am trying to get up to speed with modern SharePoint development.

This is VERY frustrating.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by DevelopMR** [comment]
> When using scripted installers they should work out of the box. We shouldn't have to worry about 15 items being deprecated or about local/global concerns. I don't want to spend 3 days figuring out otherwise useless information when I am trying to get up to speed with modern SharePoint development.
> 
> This is VERY frustrating.
> 
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
> * Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
> * Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
> * Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
> * Product: **sharepoint**
> * Technology: **sharepoint-framework**
> * GitHub Login: @VesaJuvonen
> * Microsoft Alias: **vesaj**

OK, I got this thing working.  I had to remove a bunch of things but this might help others:

Had to uninstall a previous version of Python 3.9.6, and removed the Paths from System Environment variables.
Had to remove Chocalatey (deleted folder) and removed System Environment variables
Removed yeoman globally
Removed gulp globally AND a gulp cli version globally
removed Node and made sure to install **Node 14.15.0**

The instructions jump back and forth from a couple pages for Hello-world project, but I:
installed Node 14.15.0 w/ Chocolatey
As an Admin in a Powershell window ran:
**npm install gulp yo @microsoft/generator-sharepoint --global**
then cd to my project folder and ran:
**yo @microsoft/sharepoint**
then ran:
**gulp trust-dev-cert**
then ran:
**gulp serve**

Success!!  I would recommend starting your page with a fast version of those instructions in that order before expanding across several pages. Steps are easily missed by fools like me.

**Comment by patmill** [comment]
Glad you got it sorted out @DevelopMR - sorry you had frustrations.  Would it be best to preface the setup instructions with "these instructions start from a clean environment" or the like?  It's hard to cover any and all eventualities for what people have previously installed - particularly globaly.
