### ISSUE TITLE
Teams notifications: opening Viva URL works / works not alternating

### ISSUE THREAD

**Issue by Renevdo** [SharePoint/sp-dev-docs#7217]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

[ Windows ] Operating System
[ 10.22 ] Node version
[ 3.9.1 ] Gulp version

### Describe the bug / error

Expected or Desired Behavior
Clicking on a notification in Teams, opens the Viva (SharePoint) URL. Clicking on another notification, opens also the Viva URL.
The url to open is a Viva site, set in the TeamworkActivityTopic.WebUrl

Observed Behavior
Clicking on a notification works. Clicking on another notifications fails. This alternates exactly. Both URLs are working.
When it fails, we see a request to: https://tenant.sharepoint.com/_layouts/15/preload.aspx?portalsCache=true&env=TeamsWebView and the initiator is registerBeforeUnloadHandler:

![image](https://user-images.githubusercontent.com/7633914/127461990-987b0c76-481b-4333-8ee8-13e875cb48f7.png)

### Steps to reproduce

Create 2 or 3 Teams notifications with a WebUrl like this:

`string `tabUrl` = $"https://graph.microsoft.com/v1.0/users/{subscribedUser.UserId}/teamwork/installedApps/{subscribedUser.AppId}";
string encodedContext = Uri.EscapeDataString("{\"subEntityId\": \"" + _model.Url + "\"}");

var notification = new TeamworkActivityTopic
{
     Source = TeamworkActivityTopicSource.EntityUrl,
    Value = tabUrl,
     WebUrl = $"https://teams.microsoft.com/l/entity/{appid}/{tabId}?context={encodedContext}"
};`

The WebUrl is a reference to a static tab in Teams.
In the Teams manifest of our app, Viva is opened.
Url of Viva: https://tenant.sharepoint.com/_layouts/15/teamslogon.aspx?spfx=true&dest=https://tenant.sharepoint.com/sites/home?app=portals",

When clicking on the notification in Teams, and it doesn't work, we see a javascript call to registerBeforeUnloadHandler which does a _navigateToPreload. When this happens, the browser navigates to https://tenant.sharepoint.com/_layouts/15/preload.aspx?portalsCache=true&env=TeamsWebView and then it stops and nothing is displayed. When clicking on another notification, It works and navigates to the correct URL. This keeps alternating.

If we leave app=portals off the URL, it also keeps working!

### Expected behavior

Clicking on a notification in Teams, opens the Viva (SharePoint) URL. 
Clicking on another notification, opens also the Viva URL.
The url to open is a Viva site, set in the TeamworkActivityTopic.WebUrl

**Comment by OliverZeiser** [comment]
I can confirm there is something wrong with the preload.aspx. We are also seeing issues with it.
It can be reproduced very easy if you create a teams personal app with two tabs. One pointing to the **VIVA url (?app=portals)** and one tab pointing to any spfx component (something like this: **https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=https://{teamSiteDomain}/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=COMPONENTID%26forceLocale={locale}** )
Navigating between those two tabs will end with the same result. It stops with a spinning circle and nothing happens anymore.

**Comment by patmill** [comment]
Thanks for the heads up.  Forwarding the thread.

**Comment by soorajcodehub** [comment]
Hello, thanks for reposting the issue and the information. A fww questions: 
1. Can we get a video of the notification scenario>
2.  Where does this particular code: string _tabUrl` = $"https://graph.microsoft.com/v1.0/users/{subscribedUser.UserId}/teamwork/installedApps/{subscribedUser.AppId}";
string encodedContext = Uri.EscapeDataString("{"subEntityId": "" + _model.Url + ""}");

var notification = new TeamworkActivityTopic
{
Source = TeamworkActivityTopicSource.EntityUrl,
Value = tabUrl,
WebUrl = $"https://teams.microsoft.com/l/entity/{appid}/{tabId}?context={encodedContext}"
};`_

need to be executed from?
3. When you are on a viva tab and a notification comes in, does the page load in the same webview ( same tab) or does the team actually navigate to a different tab (since it seems the notification is pointing to a deepLink of a tab'

**Comment by Renevdo** [comment]
1. I asked to create a video on our side from our dev team.
2. This is the particular code to create a notification in Teams trough Graph with C#. For example in an Azure Function. This way we create just simple Teams notifications with the deeplink in it.
3. It navigates to the same webview, same tab, as we have only 1 tab defined in this application. So appid/tabid are always the same.

**Comment by Renevdo** [comment]
We created a video with the error occurring:
https://www.youtube.com/watch?v=KteyL-mdagM

**Comment by johnguy0** [comment]
@Renevdo Is this still repro'ing for you?
