### ISSUE TITLE
Issue with Scheduling Site Pages

### ISSUE THREAD

**Issue by avinashgit18** [SharePoint/sp-dev-docs#7224]
I am not able to schedule(for publishing) a page in production . I did this before , everything was fine but now i a not able to see the toggle button on & off  (also tried all browsers)
![issue](https://user-images.githubusercontent.com/88201538/127675176-9bcff9c2-49dc-49c3-a19f-95dda44288f1.PNG)
Up on checking , I noticed that column publish start date is missing in the content type we created . This content type has site page as parent content type . In QA , its working fine because that content type has that column.
Did any one had this issue of missing publish start date column in content type (coming from content type hub) in all the site collections ? Please advise or let me know for any other details. Thank You in advance.

**Comment by M365Bass** [comment]
Hello,

Are you able to confirm you’ve enabled scheduling on the pages library? See [link](https://support.microsoft.com/en-us/office/schedule-a-sharepoint-page-or-news-post-to-go-live-at-a-specific-time-4b81873c-9bbc-4307-b7ea-7b6662ff1af2) for details
