### ISSUE TITLE
Build your first Field Customizer extension article steps not working

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#723]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The Field Extension loads after being prompted to load the debug scripts.

#### Observed Behavior
The Field Extension never loads because the Load debug scripts prompt never appears.  The gulp server never shows a request made for the manifest file running on localhost.

Tested In Chrome, Edge, and IE11.

Tried to fix it by deleting <home directory>/.gcb-serve-data then running gulp trust-dev-cert.  That didn't work.

#### Steps to Reproduce
Follow the steps in the https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/building-simple-field-customizer#coding-your-field-customizer

**Comment by waldekmastykarz** [comment]
Are you trying to test the field customizer on a classic or modern site? Currently it seems that field customizers can only be tested in classic sites.

**Comment by TBag** [comment]
Tested on a classic site in an O365 developer tenancy.  Just spun up another dev tenancy and tried again and it worked.  Not sure why it did not work on the first dev tenancy but it works now so I'm closing this issue.
