### ISSUE TITLE
Field Customizer against a choice field doesn't fire onRenderCell

### ISSUE THREAD

**Issue by AkumaTen** [SharePoint/sp-dev-docs#7232]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hi there!
using SPFx v1.12.1 when you generate a field customizer and try to debug against a Choice field, onRenderCell never gets called. onInit works as expected.

When you change the field in the debug url pointing to single line of text or yes/no field, the event fires.

I'm testing this against AllItems.aspx of a 3 rows simple list with the default "Title" field and an added "Kind"  choice field.
Thanks!

### Steps to reproduce

1. setup a list with a choice field
2. create a field customizer with yo
3. just start the debugger against the choice field
4. set a breakpoint on onRenderCell and see that it never gets hit

### Expected behavior

field customizer fires onRenderCell as it does for single line of text or yes/no fields

**Comment by AkumaTen** [comment]
I just discovered that onRenderCell is called when the default "Choice Pill" column format is manually removed.
Does this mean that column formatting takes precedence over field customizer by design?

**Comment by patmill** [comment]
To repeat that back to you - you have custom formatting in the field, as well as a field customizer?

**Comment by AkumaTen** [comment]
yes I had. When you create a choice column, a "choice pill" json formatter is the default. Field customizer + json formatter have some odd behaviour. For example, you can hide column headers with json formatter and still have onRenderCell  firing, but if you add a rowFormatter in the json formatter, onRenderCell  is not called.
Furthermore, onRenderCell doesn't work with "gallery" view of the same list

**Comment by patmill** [comment]
Thanks for the additional information and feedback @AkumaTen .  I'll close this as working as expected, but I'll also send the feedback to the list formatting / field formatting / owners.
