### ISSUE TITLE
blank screen because of Cannot read property 'roundedCorner2' of undefined

### ISSUE THREAD

**Issue by carletto75** [SharePoint/sp-dev-docs#7243]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: all
- SPFx version: "@microsoft/sp-core-library": "1.10.0",
- Node.js version: "node": ">=0.10.0"

### Describe the bug / error

Same as issue https://github.com/SharePoint/sp-dev-docs/issues/3593
but starting yesterday 9/8/2021 it gives me error: Cannot read property 'roundedCorner2' of undefined
on the blank screen.

Seems that some backward compatibility is now broken.

### Steps to reproduce

Make blank project with dependencies as follows:
  "@fluentui/react": "^7.137.2",
    "@fullcalendar/daygrid": "^5.3.2",
    "@fullcalendar/interaction": "^5.3.1",
    "@fullcalendar/react": "^5.3.1",
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-odata-types": "^1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/polyfill-ie11": "^2.0.2",
    "@pnp/spfx-controls-react": "^2.0.0",
    "@pnp/spfx-property-controls": "^1.20.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/react-router-dom": "^5.1.6",
    "@types/webpack-env": "1.13.1",
    "moment": "^2.29.0",
    "moment-business-days": "^1.2.0",
    "office-ui-fabric-react": "7.157.1",
    "prop-types": "^15.7.2",
    "react": "16.8.5",
    "react-csv": "^2.0.3",
    "react-dom": "16.8.5",
    "react-router-dom": "^5.2.0",

Use at least a "DefaultButton" control.
Deploy in a real SP classic page

### Expected behavior

Webpart should render,
instead the blank screen is shown, with error:

Cannot read property 'roundedCorner2' of undefined

Same as issue https://github.com/SharePoint/sp-dev-docs/issues/3593
from 2019, but today

**Comment by patmill** [comment]
We are looking into this.  To confirm - this only happens on a classic page, correct?

**Comment by patmill** [comment]
Thanks @carletto75 - we have found the issue and are working on a solution.

**Comment by JonasBjerke89** [comment]
For us, it happens on a classic page, whenever you try to edit the properties of the SPFx webpart:
![image](https://user-images.githubusercontent.com/21952399/129690046-143fa733-ce72-43e9-84f8-3e58bea9e7a2.png)

The SPFx webpart is working on the classic page (for readers), but cannot edit the properties anymore. This is SPFx version 1.4.1.

**Comment by patmill** [comment]
This should be resolved now.  Please reopen if that is incorrect.

**Comment by JonasBjerke89** [comment]
Thanks - this is now resolved for our client.

**Comment by carletto75** [comment]
Resolved on my side too. Thanks.
