### ISSUE TITLE
openFilePreview (Teams SDK) not working for list attachments

### ISSUE THREAD

**Issue by manufz** [SharePoint/sp-dev-docs#7245]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.12.1 and 1.13.0-beta.15

### Describe the bug / error

If a link to a list attachment is passed to openFilePreview, a wrong url is generated (Error message:`This item might not exist or is no longer available.`)

### Steps to reproduce

```
this.context.sdks.microsoftTeams.teamsJs.openFilePreview({
  entityId: "test",
  title: "Test file",
  type: "pdf",
  objectUrl:"https://link_to_sharepoint_list_attachment.pdf"
});
```

### Expected behavior

List attachements can also be opened in Teams directly

**Comment by patmill** [comment]
To help sort this out, does the same thing happen in a "pure" teams app?  If you look at a network trace, is there a fetch for that file made that you can see?  Is the URL correct?  (You might need to view Teams on the web vs. desktop to see that network call)

**Comment by patmill** [comment]
So, two things here.  

1 - this appears to be a teams specific issue.  They have an issue list here - https://github.com/OfficeDev/microsoft-teams-library-js/issues

2 - I don't think that API is public (or supported / documented)
