### ISSUE TITLE
SPFX Auth problem in Teams desktop client

### ISSUE THREAD

**Issue by diabhoil** [SharePoint/sp-dev-docs#7248]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Teams desktop client
- SPFx version 1.12
- Node.js version 14.17.0

### Describe the bug / error

I have  a spfx webpart which tries to access an API secured by Azure AD. I am working with the "AadHttpClient". The webpart is working fine in any browser (like chrome, edge, ff). Even when included as tab in Teams. But when I open the same tab in the Teams desktop client the authentication fails.

We are having this problem on multiple tenants and it was working before. So we did not changed any code. It suddenly stopped working over night...

Error is:

> Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at t._getAuthTokenFromTeams (sp-pages-assembly_de-de_.js:1)
    at e._exchange1PTokenFor3P (chunk.adalauthcontext_none_.js:1)
    at e._getOboAuthToken (chunk.adalauthcontext_none_.js:1)
    at e._fetchAccessTokenSilent (chunk.adalauthcontext_none_.js:1)
    at e._fetchAccessToken (chunk.adalauthcontext_none_.js:1)
    at e._getAccessToken (chunk.adalauthcontext_none_.js:1)
    at e.getToken (chunk.adalauthcontext_none_.js:1)
    at e._getToken (chunk.aadTokenProvider_none_.js:1)
    at chunk.aadTokenProvider_none_.js:1

![image](https://user-images.githubusercontent.com/42711805/129358260-0e08c7e8-d50a-4557-9cd4-ed819c0b670e.png)

The code I used to check if it is a problem with the spfx version:
```context.aadHttpClientFactory
      .getClient('MY API ID')
      .then((client: AadHttpClient): void => {
        client
          .get('MY API URL', AadHttpClient.configurations.v1)
          .then((response: HttpClientResponse): Promise<any> => {
            return response.json();
          })
          .then((data: number[]): void => {
            console.log(data);
          });
      });```

### Steps to reproduce

1. Make a simple spfx webpart
2. Include my code from above and try to access any custom API which is secured by Azure (follow the instruction [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
3. Install the webpart in sharepoint
4. Add it to a SharePoint Page
5. Go to Teams, and add it as tab (in a team for example) with the "SharePoint"-App


### Expected behavior

There should not be an error message in the console logs and the access to the API should work without any problems.

**Comment by bcameron1231** [comment]
Hi. Please take a look at this post https://github.com/SharePoint/sp-dev-docs/issues/5320

I think you may be experiencing a similar behavior, where requesting tokens from the AADHttpClient from within Teams Desktop is not currently _implemented_. Fixes appear to have been rolling out (or planned to), but the MSFT team hasn't updated it yet.

**Comment by diabhoil** [comment]
Hey @bcameron1231 thx for the reply. I have seen this thread before and yes this might be kinda related since its about authentication in teams with custom apis.

Our workaround to this error was to just reload the page (_location.reload()_) and the issue was gone. Even that was not needed a while ago. There it was just working fine. No reload needed, no errors. Yes we had problems with mobile devices before...but not the desktop client.

Now it just looks broken. The __authTokenRequests_ member just does not exists on the object anymore. And well the methods like "getAuthTokenFromTeams" do not look like that it never was implemented. It looks like they rolled out stuff and just forget about this little peace. Thats why I wrote a new issue thread. Because this looks like a new bug to me. Maybe the result from the "new" stuff they are mentioned in the linked thread.

**Comment by VesaJuvonen** [comment]
Quick update on this - Fix should be enabled in production for Teams and SharePoint within upcoming days. This is indeed related on the same root cause as #5320

**Comment by diabhoil** [comment]
Quick update. Looks like there were some changes over the weekend? We tested on different tenants and environments today and it looks like the error is gone. Suddenly even my dummy webpart I wrote just for this purpose, which was not working on Friday, is working in Teams. The customer solutions are up and running again too. So I'll give it some days and then I am going to close the issue. 

Thx for the work and the update @VesaJuvonen !

**Comment by VesaJuvonen** [comment]
Thanks @diabhoil for sharing the latest from your side. We are indeed in progress of rolling this fix worldwide. As the rollout takes a while for being 100% out, we will update situation fully to be fixed when it's 100% released for everyone.

**Comment by diabhoil** [comment]
So this seems to work now/still. The error message from above never showed up again. 👍 

Thx to all and I'll close the issue now.
