### ISSUE TITLE
SPFx edit panel not opening on classic pages (globally)

### ISSUE THREAD

**Issue by Bitalus** [SharePoint/sp-dev-docs#7250]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Edit panel will not open on classic pages since today/yesterday by a couple of customers and our tenant.
Looks like a global issue?

react-dom-16-bundle error: Cannot read property 'roundedCorner2' of undefined.

### Steps to reproduce

1. Login to a classic sharepoint page
2. add a SPFx web part (version 1.4.1 - 1.7.1)
3. try to get it configured..

### Expected behavior

Edit panel will open to.

**Comment by patmill** [comment]
Thank you for reporting @Bitalus  - we've found the problem and are working on a solution.

**Comment by sergio-saavedra** [comment]
We have same issue on various production environments.
Is there any estimated time for this resolution?

Thanks in advance.

**Comment by patmill** [comment]
The fix started rolling on Friday, and should be across all farms by Wed.

**Comment by patmill** [comment]
This should be resolved now.

**Comment by Bitalus** [comment]
It is resolved, thank you!

**Comment by sergio-saavedra** [comment]
Yeah! It's working again.
Thanks!
