### ISSUE TITLE
Is it safe to upgrade the default packages on a new spfx webpart

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#7255]
I was wondering if after creating a new project, can I safely upgrade the packages below without issues? or will there be compatibility issues?

```
Package                             Current   Wanted   Latest  Location
@microsoft/rush-stack-compiler-3.7    0.2.3    0.2.3   0.6.47  
@types/react                        16.9.36  16.9.36  17.0.18  
@types/react-dom                     16.9.8   16.9.8   17.0.9  
@types/webpack-env                   1.13.1   1.13.1   1.16.2  
ajv                                   5.2.5    5.2.5    8.6.2
office-ui-fabric-react              7.156.0  7.156.0  7.174.0 
react                                16.9.0   16.9.0   17.0.2 
react-dom                            16.9.0   16.9.0   17.0.2
```

**Comment by patmill** [comment]
Assuming you are building for SPO:

Bumping versions of code that are used in the build should be fine, so
Bumping the rush-stack-compiler should be fine.
Bumping ajv should be fine (although I _think_ we've removed the dependency entirely in more recent / upcoming versions)
You shouldn't bump the version of react / react-dom beyond what shows up using the latest generator.  I _think_ that is 16.13.1
As long as you stick to version 7.x of office-ui-fabric-react, I believe you should be OK.  To be safe, I would currently use 7.172.2 if that is sufficient.  We bump our internal version regularly, but are currently at 1.172.2

**Comment by levalencia** [comment]
thanks Pat
