### ISSUE TITLE
How to show the attachment name using this format. 

### ISSUE THREAD

**Issue by sumitkute** [SharePoint/sp-dev-docs#7259]
Since the attachments column display name is now shown, is it possible to use this format to show the names. 
Can you please provide the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by michaelhan-1** [comment]
No, it is not available in Column Formatting. The attachment fields only returns a boolean whether attachments exists. It's not possible to display the name.

**Michael Han
Microsoft SharePoint Community Support**
