### ISSUE TITLE
Failed to load URL  https://publiccdn.sharepointonline.com

### ISSUE THREAD

**Issue by nsksaisaravana** [SharePoint/sp-dev-docs#7260]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - 92.0.4515.159
- SPFx version- 1.10.0
- Node.js version - 10.24.1
- etc

### Describe the bug / error

SPFX package has been successfully uploaded in the site collection apps catalog and try to browse in the chrome it is not loading but in my dev environment, it is working perfectly.

The same build I am trying to access in the Mozilla browser, is working fine.

After  some days, i tried to browse in the chrome browser and it is working fine. Again I am packaging with the new version and again it is not working  in the chrome browser and same is working in the Mozilla browser. 

### Steps to reproduce

1. Package and deploy in the site collection apps catalog
2. Browse in the chrome, will not work
3. Browse in the Mozilla, it will work

### Expected behavior

It should work in all browsers.

Chrome browser:

![image](https://user-images.githubusercontent.com/17681573/130162149-6b29ba79-d8b1-4bb6-b561-13ac2b7112f6.png)

Mozilla browser:

![image](https://user-images.githubusercontent.com/17681573/130162214-fda56346-2e4a-4cf7-b5cf-0f0b6f79036e.png)

**Comment by bcameron1231** [comment]
Any chance this is a caching issue? I've noticed when doing deployments some of the old code is trying to reload. Can you clear your cache and see if it fixes your issue?

**Comment by nsksaisaravana** [comment]
@bcameron1231 Thanks for your prompt reply. I have migrated SPFX 10.0.0 to SPFX 12.1.0 and it fixed this issue. CDN path has been changed (From temp to release) in version 12.1.0  and this caused this issue. I don't why Microsoft don't support this backward compatibility.
