### ISSUE TITLE
Translations Dropdown selector, causes javascript error when changing the language, causing some inconsistent behaviors in the webparts.

### ISSUE THREAD

**Issue by rumos-epc** [SharePoint/sp-dev-docs#7264]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome: Version 92.0.4515.159 (Official Build) (64-bit)
- Edge: Version 92.0.902.78 (Official build) (64-bit)
- Firefox: 78.13.0esr (32-bit)
- SPFx version: 1.12.1
- Node.js version: v14.17.3

### Describe the bug / error

When we change the language in the translations dropdown, the following javascript error  occurs:

**"Uncaught (in promise) Error: No callbackHandler found.
    at e.sendMessage (sp-pages-assembly_en-us_097c82d6ef0111f6d4cde8f3c1393862.js:70)"**
    
This causes some webparts in the page to render incorrectly.

If we change the language again, another error occurs:

**Uncaught TypeError: Cannot read property 'disabled' of undefined
    at sp-multilingual_en-us_a74a5c44c1abff0c1ec2.js:1**

The OOB text webpart for example, aligns the text in the center instead of the left align.
![image](https://user-images.githubusercontent.com/47569778/130220133-f75d78cb-3f23-4aa2-b4e6-b5dc2f30dffe.png)
![image](https://user-images.githubusercontent.com/47569778/130220249-93fef6d2-8fe6-480d-ab94-8c40c975d897.png)

If we make a full page reload with CTRL-F5 everything works accordingly.

### Steps to reproduce

1. Create a new communication site;
2. Create a new page;
3. Activate translations;
4. Translate the page created before;
5. Click on the translations dropdown and change the language;
![image](https://user-images.githubusercontent.com/47569778/130219476-0d129eeb-ac7a-4eee-ac30-b95b7d166d0c.png)

6. The javascript error appears in the console;
![image](https://user-images.githubusercontent.com/47569778/130219531-ba2f705f-c966-4d76-b34c-bc43398486a2.png)
![image](https://user-images.githubusercontent.com/47569778/130219597-dcbf98a6-9a4e-4337-9a68-5479ffd1b597.png)

### Expected behavior

After changing the language, no javascript errors should be generated and the page with all the webparts should render correctly.

**Comment by patmill** [comment]
Thanks for your feedback and information.  Because this is a product issue and not a developer issue, we will be closing this.  We have notified the appropriate product team.
