### ISSUE TITLE
Issue on sharepoint

### ISSUE THREAD

**Issue by ajaysri004** [SharePoint/sp-dev-docs#7265]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Want to remove /_layouts/15/ from the url in the sharepoint by default url.

I have try to activate / deactivate changes in minimal download strategy but still the issue is same.

I am able to get data on the 
https://website_url/sites/PnpReact/_api/web/lists/getByTitle('EmployeesList')/items?$top=2000&$select=Id%2CTitle

But not on the 
https://website_url/sites/PnpReact/_layouts/15/_api/web/lists/getByTitle('EmployeesList')/items?$top=2000&$select=Id%2CTitle

The browser goes on this url to fetch the data but I want to remove _layouts/15.

I have installed latest version of yo @microsoft/sharepoint gulp also . But I don't the issue are from these.
![Capture](https://user-images.githubusercontent.com/78900507/130246523-c4b1d85b-bad1-4c9b-98e9-218ff7d491e8.JPG)
![Capture](https://user-images.githubusercontent.com/78900507/130246564-75ac92ae-185d-4910-8bae-be36f7d1160b.JPG)

Help me to resolve in this so that I can proceed on learning process.

**Comment by bcameron1231** [comment]
Make sure you pass the correct url to the HTTPClient. 

I would advise using the page context object to get the Web URL and then append the "/_api/web/lists..." It looks like you are just trying to pass a relative url instead.

**Comment by ajaysri004** [comment]
> Make sure you pass the correct url to the HTTPClient.  ---  I didn't made any changes it is already written in launch.json
> 
> I would advise using the page context object to get the Web URL and then append the "/_api/web/lists..." It looks like you are just trying to pass a relative url instead. ---- No I am not passing any kind of retrieve url that how it is not meant.

**Comment by VesaJuvonen** [comment]
Hey @ajaysri004, can you check the guidance from @bcameron1231 and let us know the situation. Thx.

**Comment by ajaysri004** [comment]
Issue has been resolved by using older version of pnp
