### ISSUE TITLE
the sharepoint SDK links no longer exists

### ISSUE THREAD

**Issue by dannyray2805** [SharePoint/sp-dev-docs#7266]
The below hyperlinks are no longer valid or the page does not exist:
"SharePoint Server Client Components SDK" https://www.microsoft.com/search?q=SharePoint+Server+Client+Components+SDK
"SharePoint Online Client Components SDK" https://www.microsoft.com/search?q=SharePoint+Online+Client+Components+SDK%22

This article shows how to perform basic operations by using the .NET Framework object model, which is available as a redistributable package on the Microsoft Download Center (search for "SharePoint Server Client Components SDK" or "SharePoint Online Client Components SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Doc update to reference the NuGet package from NuGet gallery. These assemblies are no longer available from Microsoft Download center as installing assemblies to GAC did not work that well for developers with multiple different versions.
