### ISSUE TITLE
whoops, illegal rule inserted @-o-keyframes animation_5254g4

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#727]
Hi @waldekmastykarz 
Hope you are doing good.
All of a sudden we are facing the below issue which is stating:

**sp-classic-page-assembly_en-us_1b43b36….js:385 whoops, illegal rule inserted @-o-keyframes animation_5254g4{from{-webkit-transform:translate3d(-10px,0,0);transform:translate3d(-10px,0,0);}to{-webkit-transform:translate3d(0,0,0);transform:translate3d(0,0,0);}}
_insert @ sp-classic-page-assembly_en-us_1b43b36….js:385**

Do you have any idea on this .
Any help would be appreciated.

Many Many Thanks

**Comment by waldekmastykarz** [comment]
_sp-classic-page-assembly_en-us_1b43b36….js_ is a script provided with the SharePoint Framework runtime in Office 365. In which browser are you experiencing this issue? Do you have any other web parts on the page?

**Comment by vman** [comment]
I believe this is related to an underlying issue in Office UI Fabric and glamor. More details here: https://github.com/OfficeDev/office-ui-fabric-react/issues/1971

**Comment by sidjustsid** [comment]
@waldekmastykarz 
I am experiencing this in all the browsers . Even a default web part provided by SharePoint framework is showing this issue.

@vman : I am facing this issue in production as well.

**Comment by thomas-bak** [comment]
Getting this issue in the workbench in SPO but not locally. Any news on it?

**Comment by iclanton** [comment]
Yeah this is an issue with a recent OUIFR upgrade. We have a fix in-progress which will hopefully be released to SPO soon and released as a tooling change in an upcoming drop.

It's an annoying issue, but it's safe to ignore.

**Comment by johnfabian** [comment]
Is this fixed? I'm getting this with SPFX React onpremise or is this is only fixed for SPO?

**Comment by mwehnert** [comment]
Still experiencing the same as @johnfabian on SPFX Webparts deployed to SP Onprem 2016! Are there any news or suggestions what one could do?
