### ISSUE TITLE
Configure the list form in PNPTemplates

### ISSUE THREAD

**Issue by kmsrajan** [SharePoint/sp-dev-docs#7273]
[Enter feedback here]

This formating feature is really useful and help user to spot the metadata. Is it possible to include this formation JSON in PNPSite Template or PNPTenant Template?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-configuration.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Yes - you can included column formatting on the field definition of PnP template as that's a setting in the oob field element for SharePoint. You can see this formatting setting for example from following blog post - https://www.pkbullock.com/blog/2018/using-pnp-powershell-to-apply-modern-column-formatting/

Easiest way to do this is to export existing site or list with formatting on it, which will then export also the column formatting value.
