### ISSUE TITLE
Property pane won't open when running "gulp serve"

### ISSUE THREAD

**Issue by SharePickle** [SharePoint/sp-dev-docs#7276]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [x] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version v1.11.0
- Node.js version v10.23.0
- Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### Describe the bug / error

Property pane won't open for any web part on the page if I run "gulp serve" and open page with debug manifest query string `?debugManifestsFile=https://localhost:4321/temp/manifests.js&loadSPFX=true` 
Nothing happens, no errors or anything. Don't even have to add my web part on the page.
It only happens when SPFx version is 1.11.0, works fine with 1.12.x.

ps. Not opening programmatically either.

### Steps to reproduce

1. Create new SPFx web part v1.11.0 from yo template
2. Run gulp serve
3. Open any page with debug manifest `?debugManifestsFile=https://localhost:4321/temp/manifests.js&loadSPFX=true` 
4. Edit page
5. Try to open property pane (any webpart)
6. It won't open, nothing happens

### Expected behavior

Property pane opens

**Comment by bcameron1231** [comment]
Hi, I just created a 1.11 solution and I can't reproduce your issue.

Can you open up Dev Tools in your browser and check and see if there are any client side errors occurring when you try and open the panel.

**Comment by SharePickle** [comment]
This seems to be fixed for me, can't reproduce anymore.
