### ISSUE TITLE
validator is vulnerable to regular expression denial of service (ReDoS) attacks. A malicious user can pass a long URI to the `isDataURI()` function to cause a ReDoS attack.

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-docs#7278]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

├── @microsoft/rush-stack-compiler-3.7@0.2.3
├── @microsoft/sp-build-web@1.12.1
├── @microsoft/sp-core-library@1.12.1
├── @microsoft/sp-lodash-subset@1.12.1
├── @microsoft/sp-module-interfaces@1.12.1
├── @microsoft/sp-office-ui-fabric-core@1.12.1
├── @microsoft/sp-property-pane@1.12.1
├── @microsoft/sp-tslint-rules@1.12.1
├── @microsoft/sp-webpart-base@1.12.1
├── @microsoft/sp-webpart-workbench@1.12.1
├── @types/react-dom@16.9.8
├── @types/react@16.9.36
├── @types/webpack-env@1.13.1
├── ajv@5.2.5
├── gulp@4.0.2
├── office-ui-fabric-react@7.156.0
├── react-dom@16.9.0
└── react@16.9.0

### Describe the bug / error

In our company we use veracode to scan our code and this tool give us a summary report at the end with the vulnerabilities found on our source code or dependencies.

I have created a new SPFx webpart, empty! just the basic hello world, and even then the tool found one vulnerability.

Component: validator Version: 8.2.0 Regular Expression Denial Of Service (ReDoS): validator is vulnerable to regular expression denial of service (ReDoS) attacks. A malicious user can pass a long URI to the isDataURI() function to cause a ReDoS attack. Link: https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-7078/summary

When checking the dependency tree I found this:

├─┬ @microsoft/sp-build-web@1.12.1
│ └─┬ @microsoft/sp-build-core-tasks@1.12.1
│   └─┬ azure-storage@2.10.4
│     └── validator@9.4.1
└─┬ @microsoft/sp-module-interfaces@1.12.1
  └─┬ z-schema@3.18.4
    └── validator@8.2.0
If I understand correctly, I cant upgrade it myself because it may break the sp-module-interfaces.

Is there something I can do to update this package?

### Steps to reproduce

1. Create a new hello world app
2. Use veracode to scan the source code without importing new packages.
3.

### Expected behavior

No vulnerabilities in dependencies because newer versions dont have this vulnerability

**Comment by patmill** [comment]
Thanks - this will be fixed in the next release of the npm packages.
