### ISSUE TITLE
Length of time an item is checked out as a column

### ISSUE THREAD

**Issue by jodfie** [SharePoint/sp-dev-docs#7284]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Can anyone tell me if it's possible to have a column with the length of time a file has been checked out?

I am trying to develop for my dept a small "library" tracker for a physical book library. I created a file to represent the book and know as admins we can override if needed to check back in. I need to be able to track though how long a "book"(file) has been checked out.

**Comment by bcameron1231** [comment]
Unfortunately, I am not aware of any way of getting this information to be used in a view.

**Comment by shagra-ms** [comment]
Unfortunately, this is beyond the scope of `formatting`. I will close the issue.
