### ISSUE TITLE
SPFx development environment : Error - ENOTSUP unsupported engine for got@5.7.1 @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by nithincvpoyyil** [SharePoint/sp-dev-docs#7286]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Browser version : Chrome 92.x.x
- SPFx version - v1.11
- Node.js version - 10.13.0
- Gulp JS version - 3.9
- Yeoman version - 3.1.1
- OS - Windows 10 Enterprise - 64bit

### Describe the bug / error

Hi team,

I'm just setting up dev environment for my SPFX project. As per your [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment), I'm using SPFX v1.11 and Gulp V3, NodeJS 10.13.0 and Yeoman 3.1.1.

Also refered: https://www.voitanos.io/blog/sharepoint-framework-v1-12-deprecated/

I've successfully installed Gulp & Yeoman, however installation of  **@microsoft/generator-sharepoint** is giving me error as follows,

```bash
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} 
(current: {"node":"10.13.0","npm":"6.4.1"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"6.4.1","node":"10.13.0"}
```

### try to install of both versions, cleared the caches and uninstallation/reinstallation of gulp & yeoman
```bash
# also cleared the npm cache
npm clear cache --force 

# tried for both versions
npm install @microsoft/generator-sharepoint@1.11 --global
npm install @microsoft/generator-sharepoint --global
```
### Steps to reproduce

1. Install NodeJS 10.13.0
2. npm install gulp@3 yo@3 @microsoft/generator-sharepoint@1.11 --global

Ref : [MS documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

### Expected behavior

- Successful installation of SPFX dev environment

**Comment by nithincvpoyyil** [comment]
Hi @andrewconnell, this is just to notify you. thanks in advance - Nithin

**Comment by patmill** [comment]
First, if you are starting, it would be best to use SPFx 1.12.1 , node 12 and Gulp 4.  That will set you up for future updates.

Second, where is got coming from?  That version range looks strange (has to be less than node 7?)

**Comment by patmill** [comment]
Sorry - scratch those last statements.  It had been fixed recently and will be in the next drop of the framework (1.13).  The comments around "you should run 1.12.1" still apply however.

**Comment by nithincvpoyyil** [comment]
@patmill : Thank you for the input. When is the expected release date for SPFX 1.13? My new assignment is long-term one and need a stable version to start. Migrating to higher version will be a headache. what you reckon 1.11 or wait for 1.13? 

Also, I'm wondering why v1.11 using old got@5.7.x package, see the node engine requirement: `{"node":">=0.10.0 <7"}`

**Comment by patmill** [comment]
1.13 should be in a month or so.  In general though, the error around got shouldn't block anything.  Are you unable to build?

**Comment by KevinTCoughlin** [comment]
To clarify since the linked blog post is confusing: `1.12.0` was marked as deprecated on NPM. However, `1.12.1` is latest stable and NOT deprecated.

**Comment by nithincvpoyyil** [comment]
> To clarify since the linked blog post is confusing: `1.12.0` was marked as deprecated on NPM. However, `1.12.1` is latest stable and NOT deprecated.

Hi @KevinTCoughlin, thanks for the input. Yes, you're correct.  I just referred the[ release notes v1.12.0]( https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.12.0), and got confused.  I thought, it was mentioning about upcoming v1.13.  Currently, I'm trying to setup NodeJS 14.15.x + @microsoft-generator@1.12.1, still getting the same error. Please see the below comments  for more details.

![image](https://user-images.githubusercontent.com/5662018/131785624-9e5cea5b-db08-4257-a8ca-89847c0bfd1d.png)

**Comment by nithincvpoyyil** [comment]
> 1.13 should be in a month or so. In general though, the error around got shouldn't block anything. Are you unable to build?

@patmill : I was trying to install @microsoft/sharepoint-generator, but getting the error. Please see the screenshot below for more details.

**Comment by nithincvpoyyil** [comment]
Hi @KevinTCoughlin,@patmill, 

Based on Kevin's comment, I have tried with both NodeJS  v14.15.0 & v14.17.5(LTS) + v1.12.1 however, getting the same error. Please see the screenshots.


![Generator-sharepoint issue-node-14](https://user-images.githubusercontent.com/5662018/131800127-d8eb9eaa-0769-471d-bad7-7686a2160e22.jpg)

### OS information: 

![image](https://user-images.githubusercontent.com/5662018/131801014-b38829bd-cb22-4efe-ab0d-9516e698226e.png)



### Note:
Also tried in **MacOS**, everything working fine, all packages were successfully installed and able to create and run the project.

![Generator-sharepoint issue-Macbook](https://user-images.githubusercontent.com/5662018/131801535-fbb16bed-c8a9-4211-b7f1-eef6cb785985.jpg)

**Comment by patmill** [comment]
OK - thanks for the update.  This is (will be) fixed as well in the next drop of the framework.

**Comment by nithincvpoyyil** [comment]
👍🏽
