### ISSUE TITLE
This page is a little...sparse

### ISSUE THREAD

**Issue by joshtransient** [SharePoint/sp-dev-docs#7288]
Other than the note to "use the Viva Connections desktop model", there's nothing else on this page. I read this as "create a new Teams app package with the Viva Connections desktop script, but use the URL for your app". Is that what is meant to be communicated with this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
That was intentional as this page was referenced in numerous blog posts, videos and other locations before the Viva Connections was announced. Intention is simply to drive people to the right location where the latest guidance for embedding SharePoint portals to Teams is located.
