### ISSUE TITLE
Embed HTTP

### ISSUE THREAD

**Issue by YXGuan** [SharePoint/sp-dev-docs#7291]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hi there,

Is there a way to embed HTTP ( rather than HTTPS) on a SharePoint site?

Thanks.

**Comment by michaelhan-1** [comment]
It has nothing to do with Sharepoint.  It is related with browser security. SharePoint Online using https, when you try to embed http(iframe) on a sharepoitn online page, the browser will block it with a mixed content error. 

Reference: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Michael Han
Microsoft SharePoint Community Support**

**Comment by VesaJuvonen** [comment]
Closed as answered. Thanks @michaelhan-1 for the help here, highly appreciated.
