### ISSUE TITLE
Starting Oct 4, npm will become inoperable with the current SPFx dev environment (Node 14)

### ISSUE THREAD

**Issue by gitbrent** [SharePoint/sp-dev-docs#7297]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 93
- SPFx version: 1.12.1
- Node.js version: 14.x
- npm: 6.x

### Issue description

# Issue Summary
The current [SPFx Development Environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility) utilizes Node.js 14.x, which is not compatible with TLS 1.2.

Beginning October 4th, [npm will refuse connections from non-TLS 1.2 clients](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/).

This will render users unable to run `yo @microsoft/sharepoint` or to add additional libraries to their existing solutions (e.g.: `npm i @pnp/sp`).

# Guidance Requested
What does the team advise we do until Node 16.x is supported? Should we utilize an Node version switcher such as nvs?

![2021-09-03 09_06_37-Windows PowerShell](https://user-images.githubusercontent.com/7218970/132018852-1cd2fda1-6137-47c4-801d-19db38d5f396.png)

**Comment by patmill** [comment]
Hi @gitbrent - is it possible you have some configuration on your machine that is forcing plaintext?  We've tried on windows and mac, with various versions of node from 8 to 14, and ll of them are supporting TLS1.2

**Comment by gitbrent** [comment]
@patmill - thanks for looking into this so quickly, I have a relatively new Windows 11 machine that I installed the SPFx dev env onto, so it didn't occur to me that a setting specific to my install may be hampering TLS.

Let me go do some research...

**Comment by gitbrent** [comment]
Ugh, it was indeed my environment forcing the non-TLS 1.2 connection.

In case anyone else stumbles on this issue, I had created an `.npmrc` file last year when dealing with zscaler proxy issues that contained "registry=http://registry.npmjs.org/", which in-turn forced a plain-text connection.

Thanks @patmill -  and Vesa!

**Comment by VesaJuvonen** [comment]
Thanks @gitbrent for coming back on this. You got us scared for a while, but great that we got this sorted out before weekend. Thanks also for sharing the root cause of it with others - Sharing is caring 🙏

**Comment by gitbrent** [comment]
@VesaJuvonen - my sincere apologies for the giving the team such a fright on a Friday morning. I'll endeavor to do some more research next time...! 🤦
