### ISSUE TITLE
First list item gets hidden under header when an spfx extension is loaded.

### ISSUE THREAD

**Issue by vincepunkrock** [SharePoint/sp-dev-docs#7299]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome 92.0.4515.131
  - Brave Version 1.28.105 Chromium: 92.0.4515.131
  - Firefox 90.0.2
  - Edge Version 92.0.902.73
- SPFx version : 1.12.1
- Node.js version: v14.17.4
- etc

The site was created as a classic (as in not modern) SharePoint Site

### Describe the bug / error

Actual behavior:
The first item of the list gets hidden by the header. It happens when an SPFX extension is installed. Or as soon as it is loaded in debug mode using gulp serve. Note the the list is not scrolled. The first item simply gets hidden by the header.

![image](https://user-images.githubusercontent.com/9620524/132198247-9eb97dff-3913-41b8-ac9e-3c7973861a54.png)

### Steps to reproduce

1. add spfx extension command set to sharepoint site.

### Expected behavior

Expected behavior:
The list is displayed correctly when the spfx is not installed (or not loaded in debug mode).

![image](https://user-images.githubusercontent.com/9620524/132198272-2b48a071-4b79-4506-8b17-bd49ecb9caab.png)

I couldn't find any other issue mentioning this.
It's quite blocking.

**Comment by AJIXuMuK** [comment]
Hi @vincepunkrock!
Thank you for reporting this one!
Do you experience the same behavior with the default Command Set generated by Yeoman Generator?

**Comment by vincepunkrock** [comment]
@AJIXuMuK Sorry for the delay. I just tested the default Command Set generated by Yeoman Generator and it doesn't have the problem. I discovered that the problem comes from another package I installed (bootstrap), which  adds the following css:
`*,
*::before,
*::after {
  box-sizing: border-box;
}`

You can consider the problem solved and close this issue. Thank you for your time :)

**Comment by AJIXuMuK** [comment]
Thank you @vincepunkrock for confirming that!
