### ISSUE TITLE
Sharepoint Uservoice is Not active

### ISSUE THREAD

**Issue by pbartett** [SharePoint/sp-dev-docs#7301]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

The [Support and Feedback ](https://docs.microsoft.com/en-us/sharepoint/dev/support-feedback)pages ask you to use uservoice for feature requests. However the sharepoint uservoice page is inactive.

This needs to be updated

### Steps to reproduce

1.https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform

### Expected behavior

Able to log feature requests

**Comment by bcameron1231** [comment]
Hi, unfortunately this is not a bug. Microsoft is moving away from UserVoice for their standard feedback mechanism. Slowly all Microsoft UserVoices will be deactivated through the end of 2021

**Comment by VesaJuvonen** [comment]
New location is the Microsoft Feedback portal at https://aka.ms/feedback/sharepoint. All existing votes were transformed to the new location from the UserVoice.
