### ISSUE TITLE
"Sync To Teams" button is grayed out.

### ISSUE THREAD

**Issue by bryan-edcast** [SharePoint/sp-dev-docs#7302]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

now I am following this tutorial in order to deploy sharepoint solution. 
![Screen Shot 2021-09-07 at 2 29 27 PM](https://user-images.githubusercontent.com/88688387/132393609-12e6fff5-7b8e-483c-9c6c-c8d66f4461e9.png)
But as you can see from the above screenshot, "Sync to Teams" button is disabled.

I already tried with "isDomainIsolated": false.
![Screen Shot 2021-09-07 at 2 31 10 PM](https://user-images.githubusercontent.com/88688387/132393818-f045afea-822a-44d3-8392-a0421150718c.png)
![Screen Shot 2021-09-07 at 2 31 26 PM](https://user-images.githubusercontent.com/88688387/132393827-8a9d4800-0634-4577-b40f-e0209d471e63.png)

These are the screenshots of package-solution.json and webpart.manifest.json file.

**Comment by patmill** [comment]
Have you deployed the app to your app catalog (not just installed it)?

**Comment by bryan-edcast** [comment]
yes, I did

**Comment by patmill** [comment]
Oh, sorry.  One more thing.  Do you have sufficient permissions in Teams to upload apps?

**Comment by bryan-edcast** [comment]
Yes, I do.

**Comment by GrahamMcMynn** [comment]
@bryan-edcast - Under the "Tenant Deployed" field in the app catalog does it say "Yes"?

**Comment by bryan-edcast** [comment]
Where can I find "Tenant Deployed" field?

**Comment by GrahamMcMynn** [comment]
Sorry about that.  It should be on the main screen in the "Apps for SharePoint" in the app catalog:
![TenantDeployed](https://user-images.githubusercontent.com/16929083/132567624-f5423b24-0a87-439c-9354-f028da8f22ae.png)

**Comment by bryan-edcast** [comment]
[image: image.png]

**Comment by GrahamMcMynn** [comment]
That image didn't actually come through... was it Tenant Deployed?

**Comment by bryan-edcast** [comment]
Yes, it was.

**Comment by GrahamMcMynn** [comment]
Hi @bryan-edcast  - everything sounds like it is correct.  Could you send the app pacakge to grahamc @ microsoft.com?  I'm not sure what is wrong and that would be the easiest way for me to investigate.

**Comment by estruyf** [comment]
Got a similar issue with two developer tenants. The only difference is that I wanted to test out the `AdaptiveCardExtension`. All others details are the same.
