### ISSUE TITLE
SharePoint Online Search API different results between GET and POST queries

### ISSUE THREAD

**Issue by tato1967** [SharePoint/sp-dev-docs#7303]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Chrome  Version 93.0.4577.63 (Official Build) (64-bit)
Edge Version 93.0.961.38 (Official build) (64-bit)
Custom webpart updated to SPFX framework version 1.12.1
PnPJS library version 2.8.0
SharePoint Search Query Tool v2.8.8

### Describe the bug / error

Running a query against the POST endpoint, (i.e. .../_api/search/postquery), returns more results than it should.

I use a wildcard to search all the content and then use two managed properties, RefinableString02 and RefinableString06, to filter the results before they are returned to the webpart for further processing and rendering on the page.

These two managed properties map to two managed metadata fields from the SharePoint lists/libraries containing the searched items.

We expect that the only results being returned by the API are those where RefinableString02 or RefinableString06 are an EXACT match to the value being filtered on, instead we get all result where the refinable string managed properties CONTAIN the filtering value.

Unlike the POST endpoint if I use the GET endpoint the filtering is correctly applied and I get back only those results with and exact match.

### Steps to reproduce

1. Ensure that you have a SharePoint Online site collection
2. Add two columns to the SitePages library of type managed metadata.
3. Add a number of items into this library and then set the two metadata fields with the appropriate values.
4. Ensure that the content of the list/library is crawled by indexing the list/library or the whole site.
5. After some time has pass and the site contents have been crawled and indexed, run both: a get and a post query against the search API endpoints
6. Compare the results and check to see if those returned by the POST query have applied a CONTAINS type filtering instead of and EQUAL type filtering.

### Expected behavior

We expect that the only results being returned by the API are those where RefinableString02 or RefinableString06 are an EXACT match to the filtered on value.

**Comment by wobba** [comment]
@tato1967 Would be good if you could post your GET and POST queries to compare, and is it still an issue?
