### ISSUE TITLE
AcquireOBOToken tries to get token from "SharePoint Online Web Client Extensibility" but fails with UnauthorizedAccessException (SP page in MS Teams website tab)

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#7307]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: MS Teams Desktop Client
- SPFx version: 1.12.1
- Node.js version: 12.22.3

### Describe the bug / error

I have created an SPFx webpart which fetches data from a custom API, using AadHttpClient.
The webpart works fine in desktop, but fails in the MS Teams Desktop client.

The failing request goes to `Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=...&clientId='08e18876-6177-487e-b8b5-cf950c1e598c'`

Notice the App ID `08e18876-6177-487e-b8b5-cf950c1e598c`, which points to the `SharePoint Online Web Client Extensibility` enterprise application - whereas I expected AcquireOBOToken to request a token from `SharePoint Online Client Extensibility Web Application Principal` instead - as is the usual behavior in MS Teams desktop client.

The request to `AcquireOBOToken` fails with the following response:

```
{
  "odata.error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": {
      "lang": "en-US",
      "value": "Attempted to perform an unauthorized operation."
    }
  }
}
```

### Steps to reproduce

- Create a webpart calling a secure API using HTTPClient
- Add the webpart to a SharePoint page
- Create a _website_ tab in MS Teams pointing to the SharePoint page
- _Bonus: I also tried creating a tab pointing to the `teamslogon.aspx?dest=...` redirect page, and a 'SharePoint' tab, and a 'SharePoint Pages' tab - all with the same result_

### Expected behavior

I expect the call to `AcquireOBOToken.aspx` to return a valid JWT token, so the call with `AadHttpClient` can proceed

**Comment by patrikhellgren** [comment]
I am also seeing the exact same thing but with a Teams personal app hosting a SharePoint site page. It however seems a bit intermittent for us, some users see this all the time so they can't really use the webpart while others can use it for days until they get the issue and then they can just reload the page and everything starts working again.

For the users that it is working for and then suddenly stops working, I can see that the client id is first 03299117-02b0-47da-a053-fabf82cb3e81, then when it stops working it is 08e18876-6177-487e-b8b5-cf950c1e598c and then after a reload it goes back to being 03299117-02b0-47da-a053-fabf82cb3e81.

**Comment by NickSevens** [comment]
@lucabandMSFT can this be a side-effect of the MSAL v2 rollout?

**Comment by patmill** [comment]
We believe that the fix for this has now rolled to 100% of prod.  You should go to the api access page in the SharePoint Tenant Admin center first (you just need to hit the page).  Please let us know if you are still encountering issues.

**Comment by NickSevens** [comment]
@patmill the webpart now works when adding to a new page, but fails when adding a **document library** webpart on the same page. There seems to be some kind of conflict happening there...

**Comment by sbryois** [comment]
I do see a similar behavior on my end as well, with a slightly different initial setup. In my case, we have a SharePoint site added as a "Website" Teams tab in a Channel. On the site, we are using custom SPFx apps querying our own API.

As written in the previous replies, I also noticed a difference with the clientId being used in the request to AcquireOBOToken.
When it is using 08e18876-6177-487e-b8b5-cf950c1e598c, our SPFx apps cannot get the token as the request fails with a 403 HTTP error. When the clientId matches the one for SharePoint Online Client Extensibility Web Application Principal as found in AAD, it works fine.

As noticed by @NickSevens, I consistently get the incorrect clientId as soon as I browse to a page which host a OOTB document library WebPart. At that point, all calls will use the wrong ID. As long as I do not display one, I can display the SPFx apps without issues and get the token. Refreshing the Website tab usually helps until we open a page with the OOTB document library WebPart again.
Obviously, it works fine when the site is accessed from the browser.

I tried the suggestion to go to the API access page on the Admin center, but it did not seem to make any change (I did that a couple hours ago and it still behaves the same).

**Comment by lucabandMSFT** [comment]
Folks, thanks for reporting that.

before using the web part in Teams, was a global admin able to go to the API Access page in SPO Tenant Admin? that is a critical step to enable new functionalities. 

Thanks

**Comment by NickSevens** [comment]
@lucabandMSFT we did visit the API Access page (several times already). Is there something we can validate in the AAD apps, to see if the correct changes have been applied?

@sbryois thanks for confirming. "Glad" we're not the only ones having the issue :). Do you also have the same issue on a "SharePoint" teams tab (so not a "Website" tab)?

To summarize our issue:
- Webpart on "Website" & Personal App tab fails with HTTP403
- Webpart on "SharePoint" teams tab AadHttpClient's promise never resolves ; no call to AcquireOBOToken or target endpoint is fired. Seems to hang in a promise which happens earlier behind the scenes...

**Comment by lucabandMSFT** [comment]
@NickSevens , thanks. I want to be sure I understand the taxonomy here so please bear with me for a second: 
* Webpart on  web site & personal app fails with HTTP403: is that basically an SPFx component where supportedHost also contains TeamsPersonalApp ?
* Webpart on SharePoint teams tab: this is pinning a page that has an SPFx web part in Teams as a channel tab using the SharePoint Teams app, right?

assuming my assumptions above are correct,  in which of the following platforms you are seeing the issue surfacing?
* Teams Desktop rich client on Windows
* Teams Desktop rich client on MacOS 
* Teams Mobile on iOS
* Teams Mobile on Android

thanks again for your patience and help here.

**Comment by NickSevens** [comment]
@lucabandMSFT the personal app I tested is a SharePoint page loaded with TeamsLogon.aspx?spfx=true&dest=… url. 

Webpart in SP tab is indeed a page pinned as a channel tab, using either the SharePoint or SharePoint Page app in a Team. 

The 403 issue is the same on desktop (windows) and mobile (iOS). 
The channel tab issue (on a page without DocLib webpart) isn’t there on iOS. 

I don’t have access to Mac/Android clients, sorry.

**Comment by lucabandMSFT** [comment]
@NickSevens , thanks.

One (actually.. two) last questions here:
* (if you can do it): if you change the supportedHost of your web part to include "TeamsPersonalApp" and then sync it to Teams.. does that also presents the same issue? Or in that case works?
* IF the previous change still doesn't work, would be possible for you to share the solution?
Thanks again!

**Comment by NickSevens** [comment]
@lucabandMSFT I'll try to put something together, but probably will be after the weekend...

However: it'll most likely work as expected, since the webpart won't be loaded together with a _Document Library webpart_ then. Also, we have multiple other apps, running as a personal app (with and without TeamsPersonalApp), which all still work just fine.

**Comment by sbryois** [comment]
> 
> @sbryois thanks for confirming. "Glad" we're not the only ones having the issue :). Do you also have the same issue on a "SharePoint" teams tab (so not a "Website" tab)?

I just tried this option instead of the 'Website" tab and it would seem I face another issue as my component does not seem to display at all in this scenario. I do get an error in the console "resourceDisabled" thrown by the _getAuthToken function in sp-pages-assembly, but that is all. Not sure if it is related.
I am testing on Teams Desktop/Windows as, AFAIK, the "Website" channel tab does not show on Android.

I will test if adding TeamsTab and/or TeamsPersonalApp in the supportedHosts help in any way for me. If not, I will also try to recreate a new project from scratch to compare the behavior.

**Comment by NickSevens** [comment]
> I just tried this option instead of the 'Website" tab and it would seem I face another issue as my component does not seem to display at all in this scenario. I do get an error in the console "resourceDisabled" thrown by the _getAuthToken function in sp-pages-assembly, but that is all. Not sure if it is related.

I see the same console error indeed. I think there is a Teams Auth token not getting through to the app, somehow…

**Comment by sbryois** [comment]
After testing further, our SPFx component not loading at all when using the "SharePoint" tab is mostly an issue on our side. 

With that said, I did create a new SPFx WebPart using Yeoman and I tried to run the same code in there. I am getting the same behaviors when it comes to token acquisition.

Here are the basic steps I did.
**Using the desktop browser**
1- The SPFx WebPart is dropped on a page. I can see it getting a token.
2- I can navigate from homepage to the site page with the web part, the token is always received. 
3- I add a Document Library web part on the homepage
4- I can navigate from homepage to the site page with the web part, the token is always received.

**Using Teams Desktop App on Windows - Website Channel Tab**
5- I add the site homepage as a "Website" Teams channel tab
6- I can display the homepage as expected.
7- I navigate to the site page with the web part, the token is not received and generates an error saying "Attempted to perform an unauthorized operation.
8- I can refresh the channel tab as much as I want, every time I access the site page with the web part, the token fails.
9- **Using the desktop browser**, I now remove the Document Library from the home page
10- Now, every time I access the site page with the web part, the token is received as expected, even after tab reloads.

**Using Teams Desktop App on Windows - SharePoint Channel Tab**
11- I add the site homepage as a "SharePoint" Teams channel tab
12- From the homepage (with or without Document Library web part on it), I go to my site page with the web part on it
13- The token acquisition process seems to hang as no error is being shown and no token is being displayed either.

I have added the supportedHosts options for TeamsTab and TeamsPersonalApps, but they did not make any difference with this scenario. However I did not try to deploy/sync to Teams and use the web part as a "native" Teams app.

I have created a GitHub repo with the code I used to reproduce the issue. I have also added a video in the repo demonstrating the behavior I have in Teams and in Edge.
https://github.com/sbryois/teamstoken-issue-demo

AAD Application URI has been removed and I changed the webApiPermissionRequest resource name, but other than that it is pretty much the code base I used.

I hope it can be helpful to some extent.

**Comment by NickSevens** [comment]
@lucabandMSFT I'm seeing the exact same behavior as @sbryois 's (very detailed) analysis. Hope this helps to have a fix soon. :)

**Comment by NickSevens** [comment]
@lucabandMSFT is there anything we can share to our customers? Has the product team been made aware of the issue? Can it be reproduced? Has anything started on MS side to produce a fix for the issue?

**Comment by lucabandMSFT** [comment]
hey @NickSevens, looks like the "page pinning" scenario (both chat tab and personal app / pinned app) had a further code fix that was made and should be 100% rolled and enabled by next Tuesday WW. It might happen that your tenant is getting it before but, to be safe, I would wait until Tuesday morning Pacific Timezone and check again.

**Comment by NickSevens** [comment]
@lucabandMSFT first results seem good. Waiting for customer feedback. I'll confirm later when I know more.

**Comment by lucabandMSFT** [comment]
Excellent! Thanks a lot for the prompt feedback.

**Comment by NickSevens** [comment]
@lucabandMSFT the customer also confirmed the issue has been fixed. Thanks for the help in this.
