### ISSUE TITLE
NPM install failing

### ISSUE THREAD

**Issue by PowellT** [SharePoint/sp-dev-docs#7309]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version:  NA
- SPFx version: 1.12.1
- Node: v12.18.0

### Issue description

Running yo @microsoft/sharepoint  builds the scaffolding, but seems to fail on npm install bit.
Running npm install (--save-dev or not) fails also.
Running npm install --save-dev '@microsoft/sp-build-web' fails aswell
node_modules folder not built

Getting error like this:
npm ERR! notarget No matching version found for flatmap-stream@^0.1.0.

npm ERR! notarget In most cases you or one of your dependencies are requesting

npm ERR! notarget a package version that doesn't exist.

npm ERR! notarget

npm ERR! notarget It was specified as a dependency of 'event-stream'

**Comment by patmill** [comment]
I'm wondering if you have some old version of something kicking around, pinned, etc.  on a brand new 1.12.1 install, event-stream looks like this:

>npm list event-stream
1121@0.0.1 xxxxx\code\1121
`-- @microsoft/sp-build-web@1.12.1
  `-- @microsoft/gulp-core-build-serve@3.8.46
    `-- gulp-connect@5.5.0
      `-- event-stream@3.3.5
      
 and
>npm list flatmap-stream
1121@0.0.1 xxxxx\code\1121
`-- (empty)

**Comment by PowellT** [comment]
I cant do a npm list, as the node_modules folder doesnt get built out :(

**Comment by patmill** [comment]
If you take a new full directory structure, and don't have a customized .npmrc file / etc. does this still happen?  I've run the install in numerous versions, and I'm not getting any errors, and the flatmap-stream vulnerability was reported / removed more than 3 years ago.

**Comment by PowellT** [comment]
Thanks for the reply @patmill 
>If you take a new full directory structure
Yes, tried a few times.
> and don't have a customized .npmrc file / etc. 
That has got to be it.  My company uses it own artifact repo, instead of github, etc.
Something old there I imagine, ugh.
Would you happen to know what package might have used flatmap-stream in the past?  so I can track down it down and get it updated?  Any other tips appreciated :)

**Comment by patmill** [comment]
From your initial error, it looks like event-stream.  

npm ERR! notarget It was specified as a dependency of 'event-stream'

**Comment by PowellT** [comment]
Yes, you are right.  Sorry should have been more specific.   How can I find what uses event stream?

**Comment by patmill** [comment]
For 1.12.1, it's this chain:
xxxx\code\1121>npm list event-stream
1121@0.0.1 xxxx\code\1121
`-- @microsoft/sp-build-web@1.12.1
  `-- @microsoft/gulp-core-build-serve@3.8.46
    `-- gulp-connect@5.5.0
      `-- event-stream@3.3.5

for a much older build (1.4.1) it's this:
xxxx\code\2019_1100>npm list event-stream
2019-1100@0.0.1 xxxx\code\2019_1100
`-- @microsoft/sp-build-web@1.4.1
  +-- @microsoft/gulp-core-build-karma@4.3.6
  | `-- gulp-karma@0.0.5
  |   `-- event-stream@3.0.20
  `-- @microsoft/gulp-core-build-serve@3.1.14
    `-- gulp-connect@5.0.0
      `-- event-stream@3.3.5

**Comment by patmill** [comment]
closing now.
