### ISSUE TITLE
XMLHttpRequest send synchronous request

### ISSUE THREAD

**Issue by yungfu** [SharePoint/sp-dev-docs#7314]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

-- Edge 93, Firefox 92
-- O365 SharePoint Page

### Issue description

XMLHttpRequest synchronous requests on the main thread have been deprecated. Edge, Firefox and Chrome will log a warning message on console when send a synchronous request. But on O365 SharePoint page, the XMLHttpRequest sending a synchronous request worked well. I want to know whether the XMLHttpRequest synchronous request can be used?

**Comment by bcameron1231** [comment]
Deprecated doesn't mean unsupported, so you are free to use that... but I really would question whether you need it. You should look into handling your requests with promises for a more performant and better user experience.
