### ISSUE TITLE
`plusBeta` flag added to .yo-rc.json when scaffolding project using v1.13.0-beta.20

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#7315]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: N/A
- SPFx version: 1.13.0-beta.20
- Node.js version: 14
- etc

### Describe the bug / error

After scaffolding a React web part using generator 1.13.0-beta.20, in the .yo-rc.json file, the generator includes the `plusBeta: true` flag, even though the plusBeta switch wasn't used.

### Steps to reproduce

1. Scaffold a React web part using v1.13.0-beta.20 with all default values for yo prompts

### Expected behavior

No `plusBeta` flag in .yo-rc.json

**Comment by patmill** [comment]
Thanks @waldekmastykarz - the defaulting to beta in the beta builds is by design.  We need to clean up the --plusbeta flag use with the new beta model.
