### ISSUE TITLE
default value for `mpnId` is `Undefined-1.13.0-beta.20` in 1.13.0-beta.20

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#7316]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: N/A
- SPFx version: 1.13.0-beta.20
- Node.js version: 14
- etc

### Describe the bug / error

In a React web part scaffolded using 1.13.0-beta.20 in the package-solution.json file, the default value for mpnId is `Undefined-1.13.0-beta.20`.

### Steps to reproduce

1. Scaffold a new React web part using 1.13.0-beta.20 with all defaults for yo prompts

### Expected behavior

mpnId is empty like other properties in the developer section

**Comment by VesaJuvonen** [comment]
This is by design to match the version of the used Yeoman version.
