### ISSUE TITLE
SPFx authorization error in Teams

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#7318]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

browser version: Edge: Version 92.0.902.78, Chrome: Version 92.0.4515.159
SPFx version: 1.11
Node.js version: 10.16

### Describe the bug / error

@VesaJuvonen @GrahamMcMynn
The SPFX auth issue is back again. We have the same problem again on two tenants. The issue and the error messages are as the same as described here: [https://github.com/SharePoint/sp-dev-docs/issues/7275](url). 

![image](https://user-images.githubusercontent.com/13345587/132828758-282909e2-c55b-4b51-ae27-0dfa5bd62acb.png)

### Steps to reproduce

Try to add an SPFx app to the teams as a tab.  

### Expected behavior

We should able to add the SPFx apps to the teams without the auth. errors.

**Comment by harshdamaniahd** [comment]
Does it work in teams for ios?
my spfx app doesnt work in ios, but works in android, desktop and web
