### ISSUE TITLE
Cannot create a file in a folder containing single quotation mark (%27)

### ISSUE THREAD

**Issue by seanboss3** [SharePoint/sp-dev-docs#7320]
When creating a file in a folder containing a single quotation we get a Microsoft.SharePoint.Client.InvalidClientQueryException

Sample REST Post (using encoded values):
https://{{targetHost}}/_api/web/GetFolderByServerRelativePath(decodedUrl='Shared%20Documents/test%27')/Files/AddUsingPath(decodedurl='test6.pdf')

Note other values such as foldername: test%23 will work 
Response:
{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message": {
            "lang": "en-US",
            "value": "The expression \"web/GetFolderByServerRelativePath(decodedUrl='Shared Documents/test'')/Files/AddUsingPath(decodedurl='test6.pdf')\" is not valid."
        }
    }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e77701e1-868a-3768-b2ab-ce97ba41b408
* Version Independent ID: c18e9584-f323-926e-0cc2-7742d1a2736b
* Content: [Supporting % and # in files and folders with the ResourcePath API](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api#new-resourcepath-class)
* Content Source: [docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
You'll need to add another single quote to your folder name. So if your scenario requires a folder to have single quotes, you'll need to double them up in your URL.

e.g.
Instead of ('Shared Documents/test'') use ('Shared Documents/test''')

**Comment by seanboss3** [comment]
Excellent!

Posting a Shared Documents/test%27%27 correlated to folder test' on site thanks @bcameron1231 👍

**Comment by bcameron1231** [comment]
Happy to help.  Feel free to close this ticket. :)
