### ISSUE TITLE
XMLHttpRequest cannot load <AZURE_CDN_URL>. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<sharepoint_tenant_url>' is therefore not allowed access.

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#733]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Resource JavaScript file (localization) is correctly loaded from Azure CDN

#### Observed Behavior
SPFx is failing to load the file with errors:
XMLHttpRequest cannot load <AZURE_CDN_URL>. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<sharepoint_tenant_url>' is therefore not allowed access.

Fetch API cannot load <AZURE_CDN_URL>. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<sharepoint_tenant_url>' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

#### Steps to Reproduce
- create Command Set SPFx extension
- add SharePoint Definition and feature to activate the extensions ([from here](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api))
- deploy the extension to the Azure CDN
- install the extension to the SharePoint tenant
- add an app to the site
- go to any list

**NOTES:**
- cross-origin requests work fine in Client-Side Web Parts
- if you look at the Network tab in the browser you'll see that requested files are loaded as XHR requests

<img width="1662" alt="screen shot 2017-07-20 at 11 53 40 am" src="https://user-images.githubusercontent.com/17036219/28434013-bd12d26a-6d42-11e7-9bdf-ae8934e27fc8.png">

![screen shot 2017-07-20 at 11 55 15 am](https://user-images.githubusercontent.com/17036219/28434091-035d2572-6d43-11e7-8b19-b7be1f8b8b63.png)

![screen shot 2017-07-20 at 11 55 29 am](https://user-images.githubusercontent.com/17036219/28434101-0f74c1f8-6d43-11e7-9118-b8061a1a15f7.png)

**Comment by amishra0909** [comment]
Thanks for the feedback. The fix is being rolled out and it should be available in ~2 weeks. Please reopen the bug if the issue repros.

**Comment by Charan-Thota** [comment]
@amishra0909 Hi Abhishek, not sure if this is fixed. I am still getting this error when I use O365 private cdn.

![image](https://user-images.githubusercontent.com/26864248/29499512-aa2a86ca-8656-11e7-90eb-e75c4ad6de23.png)

XMLHttpRequest cannot load <O36_Private_CDN_URL>. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<sharepoint_tenant_url>' is therefore not allowed access.
