### ISSUE TITLE
Column linked with SPFx Field Customizer not rendering cell [intermittently] after first library paging operation

### ISSUE THREAD

**Issue by tedley63** [SharePoint/sp-dev-docs#7330]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Edge Version 93.0.961.47 (Official build) (64-bit)
- SPFx version 1.12.1
- Node.js version 14.17.6
- React /React-dom version 16.9
- Gulp version 4.0.2

### Describe the bug / error

Using a newly-scaffolded field customizer and make NO changes, the cell will render fine for the first page of entries on a document library (did not test on generic list), when the user pages, the cell will [intermittently] not render (onRenderCell is never called).  On some pages the cell will render and others is won't.. it appears to be all-or-nothing for any given page block..

### Steps to reproduce

1. Get latest spfx generator
2. Scaffold a new field-customizer project
3. Deploy to sharepoint online (put package in app catalog, create instance on test site and add column to a document lib)
4. Add several pages of items to the library
5. Refresh the page and scroll to include additional entries
6. Sometimes the customized column will render and sometimes it won't

### Expected behavior

I would expect the cell to be rendered regardless of page size and paged-scrolling.

**Comment by patmill** [comment]
Have you done any investigation into this? Any errors in the console?  Does your component get called?

**Comment by tedley63** [comment]
Yes, originally I was seeing it in one of our products and suspected it had something do with initialization maybe taking too long as we are looking items up in SharePoint, but once I eliminated almost all our specific code and it was still happening, I tried a newly-scaffolded project and had the same issue.  The onCellRender is not getting called when the issue happens and there are no errors logged in the browser console.  Sometimes it seems to be a timing issue with how quickly the paging happens after initial page load, but others time (more rarely) it doesn’t seem to matter.

As a side note, if we have two such solutions, each having a column in the library, both solutions behave exactly the same way..not rendering on the same rows.

Ted

**Comment by AJIXuMuK** [comment]
Hi @tedley63,

Could you please provide few more details?
You're using Field Customizer in Document Library - correct?
What type of column do you have with the Field Customizer applied?
Do you have any additional customizations applied to the document library?
How many items do you have in the doc library?
Did you try to repro it on any other document library or list?

Sorry for bombarding you with questions. But currently we were unable to reproduce the issue so trying to collect as much information as possible.

Thanks!

**Comment by tedley63** [comment]
Yes, it is being used in a generic Document library (template 101) with no other customizations. The custom column in a clean scaffolded project is of type Number, but it was originally noticed on both single-line and Multi-line Text columns. We have the page size on the library set to 30 and we have 40+ items in the list. It has been reproduced on multiple libraries, different site collections and different tenants.

Ted

**Comment by AJIXuMuK** [comment]
Thank you @tedley63 for the additional info!
I'd like to ask you few more things if you don't mind...
1. Do you experience the issues both when debugging the field customizer and when it's deployed?
2. Could you please try the attached project and see if it's failing as well. If not - could you please share with us the failing solution?

Thanks!

[issue-7330.zip](https://github.com/SharePoint/sp-dev-docs/files/7214188/issue-7330.zip)

**Comment by tedley63** [comment]
Sorry for the delay, been distracted.  I have not tried when debugging..  I will try the attached project today..

Ted

**Comment by tedley63** [comment]
Alex,

This solution doesn’t seem to be complete as its missing the field definition and its association to the customizer..

Ted

**Comment by AJIXuMuK** [comment]
Sorry @tedley63 - my bad.
Here is the updated zip.

[issue-7330.zip](https://github.com/SharePoint/sp-dev-docs/files/7252540/issue-7330.zip)

**Comment by tedley63** [comment]
Status update:  I’m now unable to duplicate with either your solution or mine.. until I add another of our field customizers to the library.. I have not focused on that customizer in a while so it is using an older version of SPFx libs and may be causing the issue.. I will continue by looking into that customizer to make sure it is not doing anything untoward.

Thanks for your time; I’ll repost as I continue working on it..
Ted
