### ISSUE TITLE
Safari with cross site tracking prevention enabled refreshes once when using a graph call

### ISSUE THREAD

**Issue by EldinHb** [SharePoint/sp-dev-docs#7332]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- latest for every browser
- 1.12.1
- 14.17.4

### Describe the bug / error

Safari (with cross site tracking prevention enabled) prevents implicit login flow that the MSGraphClient uses, making the browser refresh when you try to use the client. Eventually chromium will also do something similar as what Safari does and so Edge and Chrome will be affected in the near future as well. 

It looks like the issue is only on versions of msal below 2.0 (and in adal). https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas

I tested this on SharePoint online with a very barebones webpart I created: https://github.com/EldinHb/MSGraphClientSPFxIssue
<img width="1206" alt="Screenshot 2021-09-16 at 10 39 27" src="https://user-images.githubusercontent.com/8807015/133771192-c9f3b1eb-d3bf-40b9-8a4b-4b99534c6fff.png">

### Steps to reproduce

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph#use-the-msgraphclient-in-your-solution

Steps 1, 2 and 3 from that link should be sufficient. Or clone my demo webpart: https://github.com/EldinHb/MSGraphClientSPFxIssue

Last step: place the webpart on a sharepoint page and refresh the page. The page will refresh twice, once triggered by you and once triggered by the graph call. 

### Expected behavior

For Safari to not refresh when you use the MSGraphClient.

**Comment by patmill** [comment]
Yes - this is by design.  In order to work around the Safari ITP, we need to use the main window rather than a hidden iFrame.

**Comment by EldinHb** [comment]
Why is this by design? 

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas 

I read here that it's possible to authenticate with a different flow. 

Also, what is the plan when chromium gains the same feature and chrome and edge suffer from the same refresh?

**Comment by patmill** [comment]
Currently MSAL 2.0 does not work in our environment (there are multiple apps at play, and MSAL 2.0 does not handle this).  We are working together to come up with a solution, but at the moment, that solution does not exist.  As such, the solution to allow pages to work with ITP is a full page redirect.

**Comment by EldinHb** [comment]
Hi Pat, last question; do you have a roadmap or something we can track to keep an eye on when MSAL 2.0 will be integrated?

**Comment by patmill** [comment]
Nothing concrete.  Unfortunately, as I mentioned, MSAL 2.0 doesn't actually solve this problem.  We are looking at a variety of possible ways to improve the user experience while still allowing the auth to flow.
