### ISSUE TITLE
ClientSideAssets missing in the tenant app catalog

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#7338]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Tenant ID: e4adb445-89ea-4f65-9a90-b147d7fc768a

### Describe the bug / error

I've got an older dev tenant that for some reason is missing the ClientSideAssets doclib in the tenant app catalog. This leads to runtime errors when trying to use deployed web parts. What's the supported way to fix this?

### Steps to reproduce

1. In the tenant app catalog deploy an .sppkg
2. Add web part to the page
3. Error: failed to load file (ClientSideAssets doclib doesn't exist in the tenant app catalog)

### Expected behavior

Web part works as expected.

**Comment by VesaJuvonen** [comment]
Few additional questions for engineering to understand that situation

* What kind of tenant this is?
* When was the tenant created?
* Was the ClientSideAssets ever there?

It's pretty impossible to determine what's the root cause of this if it's only an issue in one tenant worldwide.

**Comment by waldekmastykarz** [comment]
1. It's a dev tenant from the dev program (using E3 licenses) created in 2014
2. The app catalog was created in 2014
3. I don't know if ClientSideAssets was ever there. Is there a way for me to test it?

**Comment by AJIXuMuK** [comment]
@waldekmastykarz could you please check if you can open the `/sites/<you_app_catalog>/ClientSideAssets/AllItems.aspx` in the browser?

**Comment by waldekmastykarz** [comment]
@AJIXuMuK nope, it's a 404

**Comment by patmill** [comment]
1 - I'm surprised that the package could even be deployed.  I'm assuming that this is a new webpart that you deployed recently.
2 - any chance someone deleted the library?  Can you check the recycle bin?
3 - The easiest way to unblock is going to be to just create the library manually.

**Comment by waldekmastykarz** [comment]
1. Yes, it's a new deployment
2. The recycle bin is empty
3. Understood. That's way easier than recreating the whole app catalog.
