### ISSUE TITLE
Field Customizer onRenderCell event.cellValue is undefined for Title (LinkTitle) column

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#734]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Field Customizer: `event.cellValue` in `onRenderCell` method contains Title text
#### Observed Behavior
Field Customizer: `event.cellValue` in `onRenderCell` method is `undefined`
#### Steps to Reproduce

- create Field Customizer
- apply Field Customizer to LinkTitle column
- check `event.cellValue` value in `onRenderCell` routine

Thanks for your contribution! Sharing is caring.

**Comment by lahuey** [comment]
Hi AJIXuMuK,

A code change has been made to resolve this issue. These changes should roll out to your production environment sometime in the next couple weeks.  If you are still seeing the problem after 3 weeks, please reopen this bug. Thanks!

**Comment by lahuey** [comment]
Please reopen this bug if you are able to repro the issue.

**Comment by AJIXuMuK** [comment]
@lahuey I can reproduce it right now.

**Comment by lahuey** [comment]
I verified that the fix has been checked in and should roll to production over the next couple weeks. You do not need to upgrade your SPFx packages in order to see the fix.

(If your issue is not resolved after a few weeks, please reopen this bug!)

**Comment by AJIXuMuK** [comment]
@lahuey the issue is still reproduced.
`event.cellValue` was changed to `event.fieldValue`.
And `event.fieldValue` is `undefined` for Title (LinkTitle) column

**Comment by ahackettms** [comment]
We made another fix. It should be available to customer on Oct. 24th. 

Please use field 'FileLeafRef' for the name/title field of document library.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
