### ISSUE TITLE
After removing the SPFX webpart from src folder and config.json, still appearing in toolbox to add

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7342]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version  - 1.12.1
- Node.js version -  v14.15.0

### Describe the bug / error

 have removed my web part from src folder and also made changes in the config.json file and deployed in my tenant but the removed webpart is still visible in the SharePoint page toolbox(i am able to add web part but it is giving file not found error )

I have tried another way like add hiddenFromToolbox with false in manifest.json but this is also not working.

Can anyone guide me on why webpart is visible on the page after removing from spfx solution?

### Steps to reproduce

1.  Deleted webpart folder from src folder
2. Deleted entries in config.json under bundles and localizedResources.
3. Did gulp clean, gulp bundle --ship, gulp package-solution --ship commands

### Expected behavior

1. Webpart should not be appeared in tool box

**Comment by patmill** [comment]
Did you remove the manifest.json file as well?
As a possible work around, if you delete the solution and reupload it, does the webpart still appear?

**Comment by DJoshi23** [comment]
What do I need to remove in the manifest.json file? 

Can you please elaborate

**Comment by patmill** [comment]
Sorry - I meant did you delete the manifest file entirely.  What does your source directory look like, and what webpart did you delete?

**Comment by DJoshi23** [comment]
Hi,

In my write-manifests.json I don't have anything please find the image below. In package-solution.json i am using "includeClientSideAssets": true 

![image](https://user-images.githubusercontent.com/86624727/135046957-32635417-89fe-4a2f-8194-06d8196c740e.png)

**Comment by patmill** [comment]
The actual webpart.manifest.json file is what I meant.

Can you show a picture of your src folder expanded?  I've run through these steps (create a solution with 2 parts, upload it, use one, delete the source code and config for 1 webpart, reupload + deploy, only see 1 part), so trying to see where you differ.

**Comment by DJoshi23** [comment]
Hi,

Please find below my src folder structure. Previously I have 4 webparts so I delete webpart 4  with using below steps:

1. Deleted webpart folder from src folder
2. Deleted entries in config.json under bundles and localizedResources.
3. Did gulp clean, gulp bundle --ship, gulp package-solution --ship commands

![image](https://user-images.githubusercontent.com/86624727/135226706-94844076-6270-441c-9573-c7a07787e312.png)

**Comment by patmill** [comment]
Let's check a few more things, because this is kind of strange.
 - If you run gulp clean before going through the build/bundle/package steps does it clear up?
 - Are you building --ship versions?
 - Do you have both a site collection app catalog and a tenant wide app catalog?
 - Did you redeploy the package that you uploaded?
 - Does it have tenant-wide deployment, or do you have to 'add an app' to the site to see it?
 - If you delete the package from the app catalog and empty the recycle bin, and re-add the solution, does that solve the problem?

**Comment by DJoshi23** [comment]
Please find my comment :

If you run gulp clean before going through the build/bundle/package steps does it clear up?
    --- Yes we are doing gulp clean before bundle/package and after doing gulp clean file some folder are deleting please find 
        below image : 1st image before gulp clean and 2nd one after gulp clean
![image](https://user-images.githubusercontent.com/86624727/135983931-d8adb935-6d48-43bc-9c45-c7b4cfccb684.png)

Are you building --ship versions?
   -----   yes I am using --ship for bundle and package-solution

Do you have both a site collection app catalog and a tenant wide app catalog?
    ------     No, for now, we have only tenant wide app catalog

Did you redeploy the package that you uploaded?
    ---- yes I have redeployed and replaced the existing package
    
Does it have tenant-wide deployment, or do you have to 'add an app' to the site to see it?
     ----  It's Tenant-wide deployment


If you delete the package from the app catalog and empty the recycle bin, and re-add the solution, does that solve the problem?
        --- I have tried above steps as well but it's not work for me

**Comment by patmill** [comment]
OK, next steps, because something strange is going on.

If you go to your app catalog and hit /lists/componentmanifests

you should see all components in the system.  Does your "phantom" webpart appear in the list of manifests?

**Comment by DJoshi23** [comment]
I have searched component Id in solution and I have found under release/manifest and ClientSideAssets.xml.rels files.
But how can I remove ids from the above Can you please guild me

**Comment by patmill** [comment]
That generally means that you didn't actually remove the component fully from your project.  Check the config.json file, and make sure that you actually deleted the folders and the manifest.json files of the components you removed.  You might also have an error in your build, and you aren't actually getting an updated package file - check the created / last modified dates of your .sppkg file (and even delete / recreate to be sure).

**Comment by DJoshi23** [comment]
Question:  Check the config.json file, and make sure that you actually deleted the folders and the manifest.json files of the components you removed
Answer:  I have deleted entries from config.json and deleted solution folder from **src/webpart** location

Question:  You might also have an error in your build, and you aren't actually getting an updated package file - check the created / last modified dates of your .sppkg file (and even delete/recreate to be sure).
Answer: I have checked there is no error in the gulp bundle and sppkg file created new

But still "phantom" webpart is appearing

**Comment by patmill** [comment]
Can you upload your project files some place (not the node modules folder though)

**Comment by DJoshi23** [comment]
unfortunately, this is a client project I cannot share the project files.

**Comment by patmill** [comment]
OK, unfortunately at this point I'm not sure how to help.  If you can make a simplified project we can take a look at it, but I think there is something wrong / incorrect with how you removed the project / uploaded the solution / removed the old solution / etc.  We haven't heard of anyone else having this issue.  Feel free to open a new issue if you have a scenario where we can dig in with more detail.
