### ISSUE TITLE
URL for Graph-API request gets corrupted by MSGraphClient

### ISSUE THREAD

**Issue by Martin-Leonhartsberger-Habau** [SharePoint/sp-dev-docs#7343]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft Edge Version 93.0.961.52 / Google Chrome 93.0.4577.82 / Firefox 92.0
- SPFx version 1.12.1
- Node.js version 14.17.6-x64
- React version 16.9.0

### Describe the bug / error

When using MSGraphClient, the URL I am providing in code is somewise truncated.
This does not occur on "simple" URLs like 
**'/me/manager'**, 
but every time when using 
**'/me?$expand=manager($levels=max;$select=id,displayName)&$select=id,displayName&$count=true'**

URL defined in Code:
![image](https://user-images.githubusercontent.com/66724076/134511913-11446048-a355-4c4e-a078-9e611d0f50c4.png)

URL fired by Browser:
![image](https://user-images.githubusercontent.com/66724076/134512274-d82f92b9-4007-4226-b65d-7b3508a654ae.png)

As you can see, there are some characters missing: **'=max;$select=id,displayName)'**

When I try this in Postman, it perfectly works out:
https://graph.microsoft.com/v1.0/me?$expand=manager($levels=max;$select=id,displayName)&$select=id,displayName&$count=true

### Steps to reproduce

I can reproduce this behavior by firing the request like shown in the screenshot (see description above).

### Expected behavior

The URL is used as defined in code.

**Comment by Martin-Leonhartsberger-Habau** [comment]
I got it working by escaping just the two '=' withing the brackets with '%3D':
**'/me?$expand=manager($levels%3Dmax;$select%3Did,displayName)&$select=id,displayName&$count=true'**

Is this common knowledge, that it has to be done this way, or is it indeed a bug?

**Comment by patmill** [comment]
In general, you should always URL encode your query string parameters.
