### ISSUE TITLE
Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.

### ISSUE THREAD

**Issue by aaphadnis** [SharePoint/sp-dev-docs#7356]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

import {
  SPHttpClient,
  SPHttpClientConfiguration, 
  SPHttpClientResponse,
  ISPHttpClientConfigurations
} from '@microsoft/sp-http';

return this.context.spHttpClient.get(this.context.pageContext.web.absoluteUrl + 
      "/_api/web/lists/GetByTitle('BirthdayList')/Items", SPHttpClient.configurations.v1)
      .then((response: SPHttpClientResponse) => 
      {
        return response.json;
      });

When I do gulp build I am getting this error - 
error TS2345: Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.

Here is my package.json -
{
  "name": "org-birthday",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  },
  "devDependencies": {
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }
}

### Steps to reproduce

1. Create project for SP 2019 on premise
2. Run npm install @microsoft/sp-http@1.4.0 --save
3. Add the above code to the web part ts file.
4. Run gulp build.

### Expected behavior

This should compile and allow me to call REST API.

**Comment by bcameron1231** [comment]
Hi, looks like you are installing @microsoft/sp-http@1.4.0 again? Curious for your reasoning for doing so.

Can you delete your node_modules folder, and just run **npm install** again.

**Comment by aaphadnis** [comment]
> Hi, looks like you are installing @microsoft/sp-http@1.4.0 again? Curious for your reasoning for doing so.
> Since the core-library was targeted to 1.4.0, I installed that version. Also I tried plain install to get latest version. Same issue. 
> Can you delete your node_modules folder, and just run **npm install** again.
I tried deleting node-modules and ran npm install - Same result.

**Comment by bcameron1231** [comment]
If you start a new solution and try it, do you have the same issues? You shouldn't have to do any additional installs after the yeoman template generation except npm install. The error is indicative of mismatched versions in your solution.

**Comment by AJIXuMuK** [comment]
Hi @aaphadnis,
Thank you for reporting the issue.
Please, do the next things to fix the issue:
1. Update all 1.4.0 dependencies in `package.json` to 1.4.1, including sp-http
2. delete node_modules and package-lock.json and run `npm i`

Another option is to install v1.4.1 of the generator - it works perfectly (just select SharePoint Online).

Unfortunately, we're getting rid of on-prem support in v1.13 of the generator.
So for future on-prem solutions I'd still recommend to use the generator@1.4.1


Please, let us know if the proposed solution works for you.

**Comment by AJIXuMuK** [comment]
Hi @aaphadnis,
Thank you for reporting the issue.

There are few options here to solve the issue.
### Use `--save-exact` when installing sp-http and version 1.4.1:
```
npm i --save --save-exact @microsoft/sp-http@1.4.1
```

### Modify package.json
You can use `npm i --save @microsoft/sp-http` and then modify `package.json` to replace `^` with `~`.
Then you will need to remove node_modules and `package-lock.json` and run `npm i`

Unfortunatelly, we're getting rid of on-prem version in the generator. So I would use one of these options.

Please, let us know if there are any further questions.

**Comment by patmill** [comment]
Looks like the version mismatch was the problem, and fixing all versions to 1.4.1 fixes the problem.  We'll update docs to make that clear as well.
