### ISSUE TITLE
A hash in the URL causes a loop when refreshing the page if the Service Worker adds `?sw=bypass`

### ISSUE THREAD

**Issue by michaelcoxon** [SharePoint/sp-dev-docs#7358]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Version 94.0.992.31 (Official build) (64-bit)
- 1.12.1
- Language English Australia

### Describe the bug / error

The service worker throws an exception when the CurrentCulture and the CurrentUICulture are different. This in turn causes the page to reload with `sw=bypass`. It then triggers the worker to remove the `sw=bypass` on reload, but if the URL has only 1 query parameter AND a hash it throws the same exception and gets stuck in a loop. 

### Steps to reproduce

1. Change language to English Australia
2. Open SharePoint to a page that is using the service worker/SPFx stuff
3. Add `#/` to the end of the URL 
4. Refresh the page a few times to get the `sw=bypass` to happen.

---

I can provide more info in a Teams meeting if required.

### Expected behavior

The CurrentCulture and the CurrentUICulture should not be different.

**Comment by LeonPienaar** [comment]
I can confirm the changing the region from Aus to US fixes the problem for now.

**Comment by patmill** [comment]
Thanks for letting us know.  We've found the issue and made a fix.  100% rollout should be within the next couple of weeks.

**Comment by patmill** [comment]
Yes, this is temporary.  A couple of fixes went in to address some issues, and wound up not playing nicely together, so we've disabled them for now, and an updated solution should be starting to go out next week, with full rollout the next week.

**Comment by patmill** [comment]
Sorry - missed closing this one.  The fix has been rolled out fully for a week or two now.
