### ISSUE TITLE
Issue with creating tabs in personal webpart

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7364]
Hi,

We can create tabs in personal app in microsoft teams. For eg we can add an spfx webpart in first tab, then a page etc... 
As recommended from docs ,and it worked before i used
For eg: 
https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=a28bc831-8925-4307-8618-97caebb326fd%26forceLocale={locale}
![image](https://user-images.githubusercontent.com/11780473/135636745-986a7371-ba65-470a-9543-2d503e22c630.png)

The problem is with {teamSiteDomain}, which is no longer working.

Also could be related to this : https://github.com/SharePoint/sp-dev-docs/issues/7311#issuecomment-929514708

Can someone provide guidance, on which the correct way to configure personal tabs in teams

**Comment by patmill** [comment]
So, a bit confused.  What exactly are you trying to do?  Are you trying to paste this URL into the app builder UI (vs. modifying the manifest file directly"?  What flow previously worked, and is now broken?  Also, I don't think that {teamSiteDomain} will work for a personal app, since there is no teamsite at play, but maybe it points to the users mysite...

**Comment by harshdamaniahd** [comment]
Trying to do this https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-configure-in-teams

I tried from app studio, I tried from teams developer app builder site, also I tried uploading app to teams directly by creating a manifest file manually today, and it doesn't allow me to upload. I will once again try tomorrow and update you on this.

**Comment by patmill** [comment]
OK.  I don't think app studio will work, but uploading an app should work.  If you get any sort of exception / error / etc. let us know.  I'll give it a try as well.

**Comment by harshdamaniahd** [comment]
Ok. I will once again try and share the manifest tomorrow. 
Thanks

**Comment by patmill** [comment]
Sorry - ignore my comment around the {teamSiteDomain} moniker.
