### ISSUE TITLE
load spfx & modern pages webparts on custom aspx page

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#737]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to load spfx webpart and all the list of webparts that modern pages has to offer in custom build aspx pages?

I created a custom .aspx page in a certain document library with no sharepoint masterpage dependencies and I would like to plug in or embed an spfx webpart without having to use iframe to sharepoint pages that supports webparts.

**Comment by mcmynn83** [comment]
Hi Jonathan,
We only support using SPFX webparts on either modern pages, or classic pages that support webparts.  

Thanks,
Graham
