### ISSUE TITLE
SPFx MSGraphClient sometimes uses different Service principal to authenticate

### ISSUE THREAD

**Issue by manufz** [SharePoint/sp-dev-docs#7372]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.12.1

### Describe the bug / error

When opening a SharePoint site with an embedded webpart sometimes _SharePoint Online Web Client Extensibility_ is used instead of _SharePoint Online Client Extensibility Web Application Principal_ for MSGraphClient calls.
If the site is opened in a new tab most of the time the first principal is used (which does not have the approved permissions). After a page refresh the correct service principal is (always) used.

The issue could only be reproduced on a site where _Dashboard (Preview) for Viva Connections_ webpart is also embedded.

We did visit the API access page in the Admin Center with a Global Admin. After that the hint "We're setting up access to Azure AD resources." was displayed, so the update should have been applied. Also the permissions disappeared after that as mentioned in another issue (https://github.com/SharePoint/sp-dev-docs/issues/7348).

### Steps to reproduce

.

### Expected behavior

MSGraphClient should always use SharePoint Online Client Extensibility Web Application Principal for Graph calls.

**Comment by patmill** [comment]
Clarification on this.  When you say "embedded webpart" what do you mean?  Do you mean an isolated part?

**Comment by manufz** [comment]
@lucabandMSFT yes the problem is that _SharePoint Online Web Client Extensibility_ does not have the required permissions to make the Graph calls so they fail with an error 403.

**Comment by lucabandMSFT** [comment]
@manufz, following up on this one: is the issue still happening?
