### ISSUE TITLE
ServerUnauthorizedAccessException trying to add UserCustomActions to newer site collections

### ISSUE THREAD

**Issue by cawillwe** [SharePoint/sp-dev-docs#7380]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- classic site collections

### Describe the bug / error

I've infrequently but successfully used code to add custom actions to document libraries on site collections in the past.
When I try the same code on libraries in site collections that I've created in the past few months, I'm now getting a ServerUnauthorizedAccessException, "Attempted to perform an unauthorized operation."

Is there a setting some place I need to update on these site collections to allow this?

### Steps to reproduce

From a console app, run a function such as below (taken from [here](https://sharepointmates.com/2017/06/30/custom-actions-using-csom-for-sharepoint-online/)):
```
public static void AddCustomAction()
        {
            try
            {
                string Pwd = "[yourpassword[";
                string UserName = "[yourusername]";
                string spsiteurl = "[yoururl]";
                var secure = new SecureString();
                foreach (char c in Pwd)
                {
                    secure.AppendChar(c);
                }
                using (var clientContext = new ClientContext(spsiteurl))
                {
                    clientContext.Credentials = new SharePointOnlineCredentials(UserName, secure);
                    var customlist = clientContext.Web.Lists.GetByTitle("SampleCustomList");
                    clientContext.Load(customlist);
                    clientContext.ExecuteQuery();
                    Microsoft.SharePoint.Client.UserCustomActionCollection collUserCustomAction = customlist.UserCustomActions;
                    UserCustomAction newcustomaAction = collUserCustomAction.Add();
                    newcustomaAction.Location = "EditControlBlock";
                    newcustomaAction.Sequence = 100;
                    newcustomaAction.Title = "Custom List ECB Menu";
                    newcustomaAction.Url = "javascript:alert('Custom List ECB custom Action')";
                    newcustomaAction.Update();
                    clientContext.ExecuteQuery(); // ERROR occurs here
                    Console.WriteLine("Custom List ECB Menu Created Successfully");
                }
            }
            catch (Exception ex)
            {

                Console.WriteLine( ex.Message.ToString());
            }
        }
```

### Expected behavior

Expect to not get an error.

**Comment by michaelhan-1** [comment]
This could be that custom script is disabled on your site. Try to enable it with the command` Set-SPOSite <SiteURL> -DenyAddAndCustomizePages 0`, check if it works for you.

More details are in this article: https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script
