### ISSUE TITLE
Unable to scaffold a new Adaptive Card Extension project. 

### ISSUE THREAD

**Issue by derhallim** [SharePoint/sp-dev-docs#7382]
Hello, 

I installed the latest version of SPFx using: 

npm i @microsoft/generator-sharepoint@next -g

Then I ran this: 

yo @microsoft/sharepoint

The steps didn't go as expected. Here's a screenshot of what I had: 
![image](https://user-images.githubusercontent.com/7239963/136314992-afa9e995-bdc8-47cb-8fd0-ab6e4499d4bc.png)

It asked me for: 
1- Solution name
2- Where I want to store the solution
3- If the solution would allow the tenant admin to deploy it to all sites
4- If the solution would requires permissions to APIs that are unique and not shared..
5- Type of client side component: I chose "Adaptive Card Extension" 

Then yoeman just generated the files for the project without installing anything, and showed this message: 
_No change to package.json was detected. No package manager install will be executed._

When running npm i, nothing happens. This is the content of package.json: 

![image](https://user-images.githubusercontent.com/7239963/136314831-120daae3-b749-4e98-b190-4f213112f97b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010f798c-ec19-8cc1-b9d3-84ca31cb6e62
* Version Independent ID: d76b36f9-620d-f82c-7122-7cd2a468dc6d
* Content: [Build your first SharePoint Adaptive Card Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension#feedback)
* Content Source: [docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by patmill** [comment]
Thanks.  As a workaround in the meantime, can you create your folder and create the solution from inside it?

**Comment by patmill** [comment]
This was fixed in the final 1.13 release.
