### ISSUE TITLE
Issue with get-pnptenantsite

### ISSUE THREAD

**Issue by suz7777** [SharePoint/sp-dev-docs#739]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We are running the command with about 200K users
Get-PnPTenantSite -Detailed -IncludeOneDriveSites

We would like to have the following:
* the command should work - see reproduce below
* we would like to be able to target only onedrive sites and/or group sites
* we would like the report to run quickly as per the GUI report in the admin console - that seems to run a similar query in about 2 min.
* we would like a report to show all onedrives / groups / sites created *after* date

#### Observed Behavior
The command ran for 24 hours and failed unexpectedly - we did not get an error message from the command.  Our logging was not able to capture the error output - it appeared to be a timeout of some form on the command.

#### Steps to Reproduce
Get-PnPTenantSite -Detailed -IncludeOneDriveSites
* use with 200K profiles and 10K groups and 2000 site collections

**Comment by mcmynn83** [comment]
@suz7777 - Can you please open this up on the PNP git hub site?  It should be SharePoint/Pnp.
