### ISSUE TITLE
Property 'spHttpClient' does not exist on type 'ApplicationCustomizerContext'

### ISSUE THREAD

**Issue by ayodejiayodele** [SharePoint/sp-dev-docs#7396]
In the first paragraph of [Connect to SharePoint API using the SPHttpClient](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-sharepoint#connect-to-sharepoint-api-using-the-sphttpclient), it was specified that SPHttpClient is available in the extension context. If you [create a new application customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension), this.context.spHttpClient is not a property, and based on the documentation, [ApplicationCustomizerContext](https://docs.microsoft.com/en-us/javascript/api/sp-application-base/applicationcustomizercontext?view=sp-typescript-latest) does not have this property. Please could you verify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec05dcfb-b91c-969d-0656-bc504f796599
* Version Independent ID: 1de9e72a-3c1f-ea80-ae1c-7721315b349a
* Content: [Connect to SharePoint APIs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/connect-to-sharepoint)
* Content Source: [docs/spfx/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by michaelhan-1** [comment]
The class [ApplicationCustomizerContext](https://docs.microsoft.com/en-us/javascript/api/sp-application-base/applicationcustomizercontext?view=sp-typescript-latest) extends [ExtensionContext](https://docs.microsoft.com/en-us/javascript/api/sp-extension-base/extensioncontext?view=sp-typescript-latest) class. And  [ExtensionContext](https://docs.microsoft.com/en-us/javascript/api/sp-extension-base/extensioncontext?view=sp-typescript-latest) class extends [BaseComponentContext](https://docs.microsoft.com/en-us/javascript/api/sp-component-base/basecomponentcontext?view=sp-typescript-latest), spHttpClient is one of properties of BaseComponentContext. 

Below is my test, we could use the property for ApplicationCustomizerContext 

![image](https://user-images.githubusercontent.com/69185043/136881801-4d5e0342-c0d1-479b-b7bf-5f4decaa32a5.png)

**Comment by ayodejiayodele** [comment]
I still have the same issue, below is my test. Am I missing something?

![image](https://user-images.githubusercontent.com/63050478/137063714-39352ba0-2b0b-4454-985b-49c2064a07ca.png)

**Comment by ayodejiayodele** [comment]
├── @microsoft/generator-sharepoint@1.12.1
├── @pnp/cli-microsoft365@3.13.0
├── gulp@4.0.2
├── npm-upgrade@3.0.0
├── npm@7.22.0
└── yo@4.3.0

**Comment by ayodejiayodele** [comment]
@patmill I finally found the issue. @microsoft/sp-component-base  was incomplete for some reason, missing the dist folder. Deleted and re-installed this package and fixed the problem. Many thanks.
