### ISSUE TITLE
SharePoint Color Palette Tool - broken link

### ISSUE THREAD

**Issue by danone1985** [SharePoint/sp-dev-docs#7399]
The link in Notes is broken:
https://www.microsoft.com/download/details.aspx?id=38182 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecfd641-4d66-1e34-8c32-1f59b53233d6
* Version Independent ID: 8627d0b0-94c0-f8fe-b753-b8e1411ead41
* Content: [Customizing 'modern' team sites](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-customize-sites.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Link removed.
