### ISSUE TITLE
Example of using 'OR'

### ISSUE THREAD

**Issue by JoVa99** [SharePoint/sp-dev-docs#7400]
Would like to see an example of using a condition to check if a value is 'this **or** that'. 

Can't get this to work right now:

=if(or([$Category] == 'Product Management', $Category] == 'Service Management'), 'true', 'false')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This should have resolved the question, but looking ack from @JoVa99  - thx @michaelhan-1 for the assistance.
