### ISSUE TITLE
PropertyPaneChoiceGroup not displaying correctly when loaded into SharePoint Online Dev Environment

### ISSUE THREAD

**Issue by neilhoff** [SharePoint/sp-dev-docs#741]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
![image](https://user-images.githubusercontent.com/1918319/28533808-177eba10-7064-11e7-8f20-d21487fe5e2a.png)

#### Observed Behavior
![image](https://user-images.githubusercontent.com/1918319/28533852-3bf9b354-7064-11e7-91dd-42a5f9df9442.png)

#### Steps to Reproduce

Create a PropertyPaneChoiceGroup. Open in local environment to see it correctly. Open in a SharePoint online Dev environment to see it displayed incorrectly.

#### Notes

If you look at dev tools you will notice that when the web part is loaded in SharePoint online display: flex  is added to this class:

![image](https://user-images.githubusercontent.com/1918319/28534068-010c9eea-7065-11e7-8926-248f5fdd4c23.png)

SharePoint local dev looks like this:

![image](https://user-images.githubusercontent.com/1918319/28534193-6a5b7254-7065-11e7-9efa-72190fb30d36.png)

**Comment by acksoft** [comment]
I am also see this issue.  Furthermore, in the SPO Hosted workbench, the options other than selected default cannot be selected by the user.

**Comment by srideshpande** [comment]
@neilhoff and @acksoft - are you guys still seeing this issue in the latest release? It should already be fixed.
 
Please let us know.

**Comment by neilhoff** [comment]
I do not see the issue anymore. Thank you!

**Comment by srideshpande** [comment]
Cool. Thanks for the update. I am closing the issue now.
