### ISSUE TITLE
SPFx v1.13 (rc1) - SPFx Log API not writing to console in hosted workbench

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#7413]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browsers:
  - Chrome: v94
  - CrEdge: v94
- SPFx: v1.13.0-rc1
- Node.js: v14.16.1

### Describe the bug / error

The `Log` API in SPFx isn't writing anything to the hosted workbench console. The native DOM `console.*()` API methods work fine.

### Steps to reproduce

Follow steps in this HOL exercise using SPFx v1.13.0-rc.1:
https://docs.microsoft.com/en-us/learn/modules/sharepoint-spfx-web-parts/7-exercise-api

### Summary:

1. create web part
1. update code to add the following

    ```ts
    import { Log } from '@microsoft/sp-core-library';
    ...
    // add to render method
    Log.info('HelloWorld', 'message', this.context.serviceScope);
    Log.warn('HelloWorld', 'WARNING message', this.context.serviceScope);
    Log.error('HelloWorld', new Error('Error message'), this.context.serviceScope);
    Log.verbose('HelloWorld', 'VERBOSE message', this.context.serviceScope);
    ```

1. run `gulp serve --norbowser`
1. open hosted workbench
1. open developer tools, **console** tab
1. add locally running web part to canvas
1. notice nothing written to console

### Expected behavior

Console messages appear using SPFx v1.13.0-rc.1 in hosted workbench as the following screenshot from SPFx v1.12.1 on local workbench:

![](https://docs.microsoft.com/en-us/learn/m365-developer/sharepoint-spfx-web-parts/media/07-web-part-03.png)

**Comment by andrewconnell** [comment]
Actually no... I don't see it working in the hosted workbench for 1.12.1 either. It was working in the local workbench in 1.12.1.

**Comment by rob-windsor** [comment]
I just tried with v1.11.0. The log entries show when the web part is in the local workbench, but they don't show when the web part is in the hosted workbench or when then web part had been deployed and is in running in a site page.

**Comment by patmill** [comment]
Yeah - that makes total sense.  I was puzzled by the 'it happens in 1.13 but not 1.12' as that should all be handled by the service, with nothing coming from the actual npm packages.  So, this is all "as expected".  The question I would have (since we're here) is what would you want?  I'll be honest, I haven't given this much thought since 1.0 came out years ago.

**Comment by patmill** [comment]
You and me both Rob :)  I went down the rabbit hole and wound up at the same doc.
