### ISSUE TITLE
Private CDN rewritten URLs in modern communication sites and REST API calls

### ISSUE THREAD

**Issue by mahmoudhhassan** [SharePoint/sp-dev-docs#7418]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

I started to see when calling REST API to get image properties in communications site the image now returns with private CDN URL when cdn is enabled. The problem now that the rewritten cdn urls for images always ends with “width=400” and that corrupt image quality.

API call example:
/_api/web/GetFileByServerRelativeUrl('" +clientSidePageRelativeUrl + "')/ListItemAllFields
Property Example: BannerImageUrl

URL Response:
https://privatecdn.sharepointonline.com/XXXXX/sites/XXXXXXX/SiteAssets/SitePages/Banner-test /XXXXX.jpg?_eat_=1634738032_8efaf33f15f657854e0ab2bb95736a99567d642323501bd26033ef36eba0c243&_oat_=1634738032_3d3c776d6543f4a061fe74829c1c679be6482a2da5da817a9180181b95326e07**&width=400**

Is this by design or a bug that will be fixed?

**Comment by mahmoudhhassan** [comment]
Hi @patmill,

Do we have any updates about this?! I disabled the Private CDN at my client and this fixed the issue for a couple of weeks and since last week we started to see even now with the Private CDN disabled the "PictureThumbnailURL" search managed property is returning now this URL containing the same "width=400" issue. What makes it more complex that this is not consistent behavior some time we get the correct URL and other times we get the below

You can find below a sample URL:
https://TenantName/_vti_bin/afdcache.ashx/authitem/sites/SiteName/SiteAssets/SitePages/PageName/ImageName?_oat_=1636783767_fe478fe6bc9a937504b11870ec67856370abbbe392238b67ad2cc5a8d01473cf&P1=1636712816&P2=-362945797&P3=1&P4=QLcuHyr3Vy%2fMmVWWdYeu7hTGurnMtRkX%2b80ly9bh3oF1GkUYmxPBPRdCiQmzwJ2Af6q764Vat94euikXu5%2fho%2b3BvlYHT8T%2fnV5mOiQNBSsITpb5nr2sk8bzMoE4fh4jeUNgMYnFy%2fONhu4BN6Rid07Mr2ynqXHIxMPWjx%2f35P5viqhYRU5Rq2psNquDm%2f14FFpVoe9RXP4Jm8mYQfuw2DAkK6TBYn1eDRA7EjN9RnNGMszhYuo4y6Bq8fUq9NxEpqvgLr1VFTg1l%2bl0PJ%2bgh%2f8c60PdwyDBPvJT1eX2bD7wATvhlQZdTZBGTGb0E%2fVcqZfBDzfZMLdBeSWVn1VqbQ%3d%3d&width=400

Adding @wobba maybe he knows something about this!

**Comment by patmill** [comment]
My understanding is that this is by design, and that the URL you get is what you should use to display the thumbnail.  Are you finding that the thumbnail image is incorrect?

**Comment by mahmoudhhassan** [comment]
@patmill Its correct but the problem with the quality of the thumbnail. As the url ends with “&width=400” this returns always a low quality version of the thumbnail

**Comment by wobba** [comment]
Replace 400 with something else. Remember an API can decide what to return. If you don't agree manipulate or call the thumbnail endpoint yourself. And 400px for a thumbnail which is the intended scenario is quite ok.

**Comment by mahmoudhhassan** [comment]
Ok, I think then the best way forward is to call the thumbnail endpoint as suggested by @wobba, thanks! Also closing this issue.
