### ISSUE TITLE
Request Enhanced Documentation for Enterprise Guidance

### ISSUE THREAD

**Issue by vball525** [SharePoint/sp-dev-docs#742]
#### Category
- [X] Question

Request to add more current information and guidance to the Enterprise Guidance documentation: https://dev.office.com/sharepoint/docs/spfx/enterprise-guidance

1. What are the up-time SLAs and % for SPFx itself and solutions built on top of it in Office 365?
2. What are the current ALM guidelines and recommended procedures for SPFx not future roadmap ones?
3. How does the ALM guidance differ between o365, hybrid, and on-prem?
4. Is there specific considerations and guidance for running SPFx solutions at a large scale?

**Comment by lucaband** [comment]
Thank you for your question. I will let @VesaJuvonen  to comment on the documentation update. in regards of your questions above:

1. Microsoft is committed to be compliant with the O365 SLA (https://technet.microsoft.com/en-us/library/office-365-service-level-agreement.aspx) for the applications (e.g. Pages or List and libraries, etc.) that contain the SPFx components, but not on the custom code. That is responsibility of the 3rd party developer

2. We are working on better ALM capabilities that will also impact our guidelines and documentation. In regards of the current capabilities, what is documented in the article you pointed out is what we have today ( @VesaJuvonen  to please comment on this one)

3. as we don't have hybrid and onPrem support (yet) this question currently doesn't apply.

4. I would say.. it depends on what the solution does. if the solution requires a Web API or an engine in the back there are scaling considerations to keep in mind. Being able to contact and upgrade the solution properly is also something that needs to be taken in consideration as we don't currently provide a marketplace story .
