### ISSUE TITLE
no uservoice

### ISSUE THREAD

**Issue by asumner** [SharePoint/sp-dev-docs#7426]
the link "This Product" is broken the aka.ms uservoice goes to a non existent uservoice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1654a603-da1f-b11b-fd2f-9aa20e9fac02
* Version Independent ID: e8453081-caea-ee38-137d-3cfe2c145f45
* Content: [SharePoint Migration Export (Asynchronous Metadata Read) API](https://docs.microsoft.com/en-us/sharepoint/dev/apis/export-amr-api)
* Content Source: [docs/apis/export-amr-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/export-amr-api.md)
* Product: **sharepoint**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by VesaJuvonen** [comment]
Link has been redirected to Microsoft feedback portal and is working now properly.
