### ISSUE TITLE
SPFx web part does not work in "meetingStage"

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#7427]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

The SPFx web part now work in the in meeting experience "sidePanel" (after the bug fixing) but the web parts still not working in "meetingStage". This part is also missing in the documentation. 
![image](https://user-images.githubusercontent.com/13345587/138462680-69e5970a-2a81-4774-bd9c-f8ac9e95d84e.png)

Is it a bug or does SPFx still not support "meetingStage"? If this not a bug and this is the expected outcome, then when we should expect this to work? 

@patmill : Thank you for the bug fixing for the in meeting experience. I just wanted to inform you also about this issue. 

### Steps to reproduce

1. Create a SPFx web part 
2. Deploy web part SharePoint and to the teams with the right manifest to support meeting environments.
3. Add web part to the meeting, join to the meeting, open app and then open the meeting stange. 

### Expected behavior

The web part should also work in meeting stage.

**Comment by canturan** [comment]
Hi @patmill, do you have any updates or estimation regarding the issue? 
Thank you!

**Comment by hohenp** [comment]
Hi, I have the same issue. Are there any news on it?
Thanks!

**Comment by lucabandMSFT** [comment]
Folks, thanks for the feedback here. We are actively working to address this scenario. Code fix is already in process but, because it requires an update to Teams client, it will take some time to roll out. 

We will provide updates here on the different stages of production roll.

**Comment by AJIXuMuK** [comment]
It should have been rolled out WW by now.
Please, open a new issue if you still experience any problems with meeting stage experience.
