### ISSUE TITLE
1.13.0 for "Create a subfolder with solution name" does not work

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#7429]
I tested 1.13.0 yesterday and when you ask for "Create a subfolder with solution name" the generator comes back quickly with a message "No change to package.json was detected. No package manager install will be executed." 
There is no code created and no npm instal run. 
I experienced this in the beta too. 
Maybe it is a Yeoman issue? I have the latest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e108ec8-f332-3ea4-8c84-42219d541e67
* Version Independent ID: cc79c8c8-60fd-51ca-2968-46936f496926
* Content: [SharePoint Framework v1.13 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.13)
* Content Source: [docs/spfx/release-1.13.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.13.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by patmill** [comment]
This will be handled in the upcoming 1.13.1 release

**Comment by Ofer-Gal** [comment]
Thanks
