### ISSUE TITLE
Property Pane Scroll Bar Bug when disableReactivePropertyChanges() is "true"

### ISSUE THREAD

**Issue by acksoft** [SharePoint/sp-dev-docs#743]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
To see and be able to interact with all property pane controls when the pane is open, regardless of:

- the number of properties in the pane
- the state of disableReactivePropertyChanges()
- the screen resolution of the user's browser

#### Observed Behavior
When **disableReactivePropertyChanges() returns false**, the scroll bar and display work as expected:
![proppanebug-1-ok](https://user-images.githubusercontent.com/13240477/28589936-192d8fcc-7135-11e7-8c4b-e5e2c78fcf25.JPG)

When **disableReactivePropertyChanges() returns true**, the last fields in the pane are (partially or completely) not visible or accessible to the user (that is, using the scroll bar does not expose them, they are hidden behind the "Apply" button):
![proppanebug-2-not-ok](https://user-images.githubusercontent.com/13240477/28590675-de0a55c6-7137-11e7-8bfe-a5a0d02523a5.JPG)

If I zoom out using the browser (Chrome) to about 67% (the point at which the property pane no longer needs the scroll bar), you can see that all of the controls are actually there and are now available to be used:
![proppanebug-3-not-ok-zoom67pct](https://user-images.githubusercontent.com/13240477/28590890-a40a1270-7138-11e7-901c-74bcda0ca1a8.JPG)

#### Steps to Reproduce
1. Create a new web part project
2. Add a large number of properties to the properties pane, enough so that displaying them all will require the property pane to scroll
3. Add the following code to your web part: `protected get disableReactivePropertyChanges(): boolean {     return true; } `
4. Test the web part in the SharePoint Workbench

**Comment by matthong** [comment]
We are having the same issue.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
