### ISSUE TITLE
Unable to disable NoScript on communication sites

### ISSUE THREAD

**Issue by dannyjessee** [SharePoint/sp-dev-docs#744]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Earlier this month (last verified on July 1), when new communication sites were created they had NoScript disabled by default (DenyAddAndCustomizePages = Disabled). As of July 22 (and still right now), not only are newly created communication sites NoScript sites (DenyAddAndCustomizePages = Enabled), but I am unable to disable NoScript the way I am still able to successfully disable it for newly created modern team sites. See error details in Observed Behavior section below.

#### Observed Behavior
When calling `Set-SPOSite [Site URL] -DenyAddAndCustomizePages 0`, I get the following error on communication sites (NOTE: this still works as expected to disable NoScript on new modern team sites):

```
PS C:\WINDOWS\system32> Set-SPOSite https://djsp.sharepoint.com/sites/comm -DenyAddAndCustomizePages 0
Set-SPOSite : SPOTenantSiteCollectionProvider::SetSiteProperties - Site https://djsp.sharepoint.com/sites/comm not
found in Grid, but TAPS_Sites_UseSharePoint flight in ONReverting to GM-based set-sposite (old) behavior for now
At line:1 char:1
+ Set-SPOSite https://djsp.sharepoint.com/sites/comm -DenyAddAndCustomi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetSi
   te
```

#### Steps to Reproduce
Create a new communication site and attempt to disable NoScript using the PowerShell cmdlet above in the SharePoint Online Management Shell. Note that this cmdlet still successfully disables NoScript for a new modern team site.

**Comment by dannyjessee** [comment]
A contributor on Tech Community pointed out some threads to me where others are having similar issues performing tasks unrelated to what I have posted above, but also using the `Set-SPOSite` cmdlet on communication sites. It is possible that the issue lies there rather than just the my specific issue:

[Error when running Set-SPOSite for new Community site](https://techcommunity.microsoft.com/t5/SharePoint/Error-when-running-Set-SPOSite-for-new-Community-site/td-p/85652)

[Anonymous Sharing not working with Communication sites](https://techcommunity.microsoft.com/t5/SharePoint/Anonymous-Sharing-not-working-with-Communication-sites/m-p/84966/thread-id/7898)

**Comment by mcmynn83** [comment]
@dannyjessee - thank you for your feedback, a fix has been made so you should be able to use Set-SPOSite on a communications site soon, the fix is currently rolling out.
