### ISSUE TITLE
Is there an equivalent for SPComponentLoader.loadComponentById to load SPFx webparts?

### ISSUE THREAD

**Issue by wspelt** [SharePoint/sp-dev-docs#7447]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

We've build a widget zone on a SharePoint home page.
It loads SharePoint SPFx webparts into a grid.
We're still using ClientSideWebPartManager to do this (only supported up to SP framework up to 1.4.1).
We call fetchWebPartManifests() followed by getManifests().
A call to _api/web/GetClientSideWebParts will result in all library and webpart manifests.
This call is a big call that takes around 10 seconds on a fast 3G mobile connection.

We've tried switching to SPComponentLoader.loadComponentById.
However this only seems to work for returning a true React.Component object.
If we pass a webpartId as a parameter and use it we get the following error: 
"Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '_isDisposed')"

SPComponentLoader.loadComponent, which takes a manifest, also doesn't seem to work with a regular SPFx webpart.

Is there any alternative for this?
Our main goal is to avoid the expensive getManifests call and load SPFx webparts by Id.

Any help would be much appreciated!

**Comment by wspelt** [comment]
Any progress/news on this?

**Comment by patmill** [comment]
Sorry @wspelt - this entire code flow (using the ClientSideWebPartManager) is internal and unsupported.

**Comment by wspelt** [comment]
@patmill Thanks for getting back on this and yes, we already heard that this call is internal and unsupported.
But it is the only option we've got now to create a generic widgetloader for SPFx webparts!
The main question is: **Is there any alternative for this?**
