### ISSUE TITLE
SPFX Solution Deployment in SharePoint online tenant level app catalog throws error - The package contains too many parts. Maximum: '1000'

### ISSUE THREAD

**Issue by tmax-siva** [SharePoint/sp-dev-docs#7449]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version -  **94.0.4606.81 (Official Build) (64-bit)**
- SPFx version - **1.11.0**
- Node.js version - **v10.22.0**
- gulp - **4.0.2**
- yo - **3.1.1**

### Describe the bug / error

I have an spfx solution with 53 web parts and 1 extension. When I did some changes in the code level, then I tried to redeploy the solution but unfortunately, the solution is not published successfully on the app catalog. It is showing the error like
**The package contains too many parts. Maximum: '1000'. Actual: '1002'.**
![error](https://user-images.githubusercontent.com/81231059/139133151-02e7d070-dd83-4fb3-b7cf-5bdee1abd976.png)

### Steps to reproduce

1. Deploy big solution file in sharepoint tenant-level app catalog
SharePoint

### Expected behavior

The expected behavior is **no errors** and successful deployment.

**Comment by patmill** [comment]
OK, that seems a bit strange.  If you look in the sharepoint/debug folder after running package-solution, how many guid-named folders exist in the solution/yoursolution.zip/ directory?  Also - if you clean then build, does the error still happen?

**Comment by patmill** [comment]
Also, unfortunately the word 'parts' in that error text is misleading.  Each relationship in the clientsideassets.xml.rels file counts towards that number, and each file referenced counts towards that limit.

You might be running into an actual limit.  Is there a requirement to have 40-50+ parts in a single solution?
