### ISSUE TITLE
SPFX Solution Deployment throws error: Contains the wrong number for the relationship. Expected value: '1'. Actual value: '0'.

### ISSUE THREAD

**Issue by dtduc91** [SharePoint/sp-dev-docs#7450]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 95.0.4638.54
- Sharepoint env:
    - Development environment:  Sharepoint for Microsoft 365 (Language: English)
    - Staging environment:  Sharepoint for Microsoft 365 (Language: Japanese)
- Node.js version: v14.17.0
- SPFx version & Package: 
```
"dependencies": {
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/decorators": "1.12.1",
    "@microsoft/sp-listview-extensibility": "1.12.1",
    "@microsoft/sp-dialog": "1.12.1",
    "@microsoft/sp-application-base": "1.12.1"
  },
  "devDependencies": {
    "@microsoft/microsoft-graph-types": "^2.6.0",
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~4.0.2"
  }
```

### Describe the bug / error

I'm trying to upload app to staging environment, but it's error though Dev environment still working perfect

Dev env:
![dev](https://user-images.githubusercontent.com/5917938/139178472-0277545c-fb88-4f1c-8ed3-a1fd6aa6a46a.png)

Staging env:
![staging](https://user-images.githubusercontent.com/5917938/139178497-260766e1-02d4-41ae-8bcc-94e0a1373774.png)

App error details:
```
このパッケージには、リレーションシップの種類 'http://schemas.microsoft.com/sharepoint/2012/app/relationships/package-manifest' のリレーションシップの誤った番号が含まれています。期待値: '1'。実際値: '0'。
```

### Steps to reproduce

1. Build an app with `--ship` argument
2. Deploy solution file in Sharepoint tenant-level app catalog on Stagging environment
3. Error occurred 

### Expected behavior

Solution still working perfect on Staging environment.

**Comment by patmill** [comment]
So, it looks like someone may have internally modified the package (there appears to be a zip as well as an spppkg).  Can you repro this with a straight forward solutions?

**Comment by dtduc91** [comment]
Dear @patmill It's absolute exactly. Firstly, I don't have enough permission to upload my extension on staging environment, so I was archive it by zip and send to another guy who have permission and OMG, he upload this zip file. 
I also don't know why Sharepoint not validate the file extension (with .sppkg) because he upload the file that have ".zip" extension. Hope Sharepoint will validate in the future
So, my issue has been resolved. Thank you (and all) so much

**Comment by patmill** [comment]
So, technically a zip file is the same as an sppkg file, but it can mean that it was modified outside the build system.  Glad you got it sorted out though.
