### ISSUE TITLE
Still facing issue

### ISSUE THREAD

**Issue by hubghs** [SharePoint/sp-dev-docs#7451]
So I was able to reproduce same errors during `gulp build` with the `npm-force-resolution` approach, but everything went fine with the first one described [here](https://pnp.github.io/pnpjs/SPFx-on-premises).

So what I can suggest you is to try this:

- From `package.json` file
    - remove the line `"preinstall": "npx npm-force-resolutions"`
    - remove the line `"resolutions": { "typescript": "3.6.4" }`
    - remove the lines `"npm-force-resolutions": "0.0.10"` and `"typescript": "^3.6.4"`
- Remove `package-lock.json` file
- Remove `node_modules` folder
- Run `npm install`
- Start from `3.` in the article mentioned above and follow it until `8.`
    - update `package-lock.json` to update TypeScript version
    - remove `node_modules` folder
    - run `npm install`

_Originally posted by @michaelmaillot in https://github.com/SharePoint/sp-dev-docs/issues/7199#issuecomment-891925892_

**Comment by hubghs** [comment]
Sorry for the incomplete info.


This is the continuation of the post (It is locked  now)  - https://github.com/SharePoint/sp-dev-docs/issues/7199
@michaelmaillot was helping me in this issue.

Details are

OS - Windows Server 2016
SharePoint Server 2019 - running other spfx projects without any issue.
I am working on a webpart.

node -v v10.13.0
npm -v
(node:15336) ExperimentalWarning: The fs.promises API is experimental
7.20.0
gulp -v
[12:15:06] CLI version 3.9.1
[12:15:06] Local version 3.9.1
npm ls -g --depth=0 @microsoft/generator-sharepoint
(node:15396) ExperimentalWarning: The fs.promises API is experimental
C:\Users\administrator.DevAD\AppData\Roaming\npm
└── @microsoft/generator-sharepoint@1.12.1
yo --version
3.1.0

**Comment by hubghs** [comment]
could you please unlock the below thread
https://github.com/SharePoint/sp-dev-docs/issues/7199

**Comment by patmill** [comment]
So, a) this appears to be a pnp specific build error, so taking the question to their issues list would be better.  Also - for on-prem, you need to use framework version 1.4.1, node 8, etc.  Here is the docs for on-prem https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support

**Comment by hubghs** [comment]
Can I get a feedback from @michaelmaillot ?
