### ISSUE TITLE
SharePoint Online Client Extensibility Web Application Principal has incorrect AppIdUri causing AadHttpClient to fail in MS Teams Desktop Client

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#7453]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- MS Teams desktop client

### Describe the bug / error

We noticed after the MSAL v2 update, calling AadHttpClient and MSGraphClient from **within MS Teams Desktop** client fails.

An error is returned by the call to `Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken`, causing the application to never receive an access token (a week ago, this error message was limited to `Resource not found`, now a more descriptive message seems to be sent).

```json
{
  "odata.error": {
    "code": "10009",
    "message": {
      "lang": "en-US",
      "value": "AADSTS500011: The resource principal named https://microsoft.spfx3rdparty.com was not found in the tenant named [...]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: a7f600a9-f4eb-4497-ad5f-53c1fcb62e00\r\nCorrelation ID: 7c86fd9f-f0d8-3000-648e-d75761838433\r\nTimestamp: 2021-10-28 09:28:45Z"
    }
  }
}
```

We investigated the behavior on different tenants (some working, some not), and came to the conclusion that on the **non-working** tenants, the **Application ID URI** was different from working tenants.

- **Working**: https://microsoft.spfx3rdparty.com
- **Non-working**: api://<tenant_id>/microsoft.spfx3rdparty.com

We tried navigating to the API Access page, even deleting the app and having it recreated, but without success.

What **did** work was changing the App ID URI to a wrong one (e.g. "microsoft.spfx3rdparty.com"), and **then** navigating to the API Access page. The App ID URI was then changed to https://microsoft.spfx3rdparty.com.
Calls to `AcquireOBOToken` (and `AadHttpClient`) then work as expected.

### Expected behavior

Either `AcquireOBOToken` to accept api://<tenant_id>/microsoft.spfx3rdparty.com as being correct, or the `SharePoint Online Client Extensibility Web Application Principal` to being setup with the correct App ID URI.

**Comment by GrahamMcMynn** [comment]
@NickSevens - could you reach out to me at GrahaMc at microsoft.com.  I'd like to discuss something going on with your tenant that we're not seeing and see if I can get you in a better state.

**Comment by giuleon** [comment]
> Hi @NickSevens - This was a regression that was rolled out and since been reverted. The issue is exactly as you said, that the endpoint URI changed and had a resolution error on the call to AcquireOboToken. If you visit the web api access page again in tenant admin the endpoint URI will revert back to the previous value and things will continue to work. We are deploying a fix for the new URI which will roll out in about 2 weeks. This issue affected the subset of customers who had to change rolled out to them and had visited the web api access page while the change was rolled out (and that regression was shut off on Oct 27th).

Thanks this solved our issue as well
