### ISSUE TITLE
Spfx provision list with ratings or likes enabled

### ISSUE THREAD

**Issue by DennisKuhn** [SharePoint/sp-dev-docs#7461]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.12.1
- Node.js version 14.17.2

### Issue description

Thanks for the great framework.
I able to deploy a list with custom content type, together with a Spfx webpart or extension.

I wonder how I could enable ratings or likes for the provisioned list?

It seems two steps are required:
1. extra site fields have to be referenced. Do I need to add them to my content type?
2. the property bag needs to have a key like _`Ratings_VotingExperience`_ with value `Likes` or `Ratings`

I can manually enable likes on at the provisioned list.

Any would is muchappreciated.

**Comment by patmill** [comment]
Unfortunately, you can not creating these field types using feature XML.  You may want to look into custom provisioning - https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-framework
