### ISSUE TITLE
Command Line Options Documentation Missing

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-docs#7464]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

For the generator-SPFx there was the documentation of the command line options: https://pnp.github.io/generator-spfx/#command-line-options. For the new generator however, I could not find counterpart documentation.

**Comment by VesaJuvonen** [comment]
thx @shurick81 - can you a bit clarify what you mean with the "new generator". 

Official SPFx generator command line documentation is at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator#use-available-command-line-options-for-the-generator

PnP SPFx generator extends this native oob generator coming from Microsoft.

Not sure what the "new generator" means in this context. Thanks for your input advance.

**Comment by shurick81** [comment]
Hi Vesa, thanks for your reply. Now I see the command line documentation so I am closing the issue. I did not know that PnP SPFx generator was an extension, but I thought it was an older version.
