### ISSUE TITLE
Application customizer does not appear straight away when added a list tab to a team, only after a new item has been added

### ISSUE THREAD

**Issue by CloudDesignBox** [SharePoint/sp-dev-docs#7473]
Hi @CloudDesignBox - it should be fixed by now. An application customizer should appear right away, not after adding a new item.

_Originally posted by @AJIXuMuK in https://github.com/SharePoint/sp-dev-docs/issues/6779#issuecomment-951226862_

This is still not fixed. The application customizer when adding a List tab in Teams does not show until a new item has been added to the list:

**Comment by CloudDesignBox** [comment]
I'm unable to open the previous issue as it is locked as completed. However i can see the issue is still there:

![image](https://user-images.githubusercontent.com/17725046/140037874-186e0b8e-5984-4183-b328-32b981db3c92.png)

After a new list item has been added, it loads the application customizer:
![image](https://user-images.githubusercontent.com/17725046/140038034-a467d11d-2e77-4258-8236-83f3ed4cbfcf.png)

**Comment by patmill** [comment]
The linked issue was reopened.  Closing this one.
