### ISSUE TITLE
.SPHttpClientConfiguration' is not assignable to parameter of type "import xxx .SPHttpClientConfiguration'" 

### ISSUE THREAD

**Issue by Crypthos** [SharePoint/sp-dev-docs#7479]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version firefox 93
- SPFx version 1.13.0
- Node.js version 14.17.0
package.json :
`
"@microsoft/sp-core-library": "1.13.0",
    "@microsoft/sp-lodash-subset": "1.13.0",
    "@microsoft/sp-office-ui-fabric-core": "1.13.0",
    "@microsoft/sp-property-pane": "1.13.0",
    "@microsoft/sp-webpart-base": "1.13.0",
    "@pnp/common": "2.10.0",
    "@pnp/odata": "2.10.0",
    "@pnp/sp": "2.10.0",
    "@pnp/sp-taxonomy": "1.3.11",
    "@pnp/spfx-controls-react": "3.4.1",
    "@pnp/spfx-property-controls": "3.2.0",
    "moment": "2.29.1",
    "office-ui-fabric-react": "7.174.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-image-crop": "9.0.4",
    "react-taxonomypicker": "0.0.45"

"devDependencies": {
    "@microsoft/rush-stack-compiler-3.7": "0.6.47",
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "@microsoft/sp-build-web": "1.13.0",
    "@microsoft/sp-module-interfaces": "1.13.0",
    "@microsoft/sp-tslint-rules": "1.13.0",
    "@types/react": "16.9.51",
    "@types/react-dom": "17.0.11",
    "@types/webpack-env": "^1.16.3",
    "ajv": "8.6.3",
    "gulp": "4.0.2",
    "tslint-microsoft-contrib": "6.2.0"
`

### Describe the bug / error

While updating to SPFX version 1.13.0 I run against te following SPHttpClient errors:
`
src/webparts/userProfileWizard/components/Fields/PeoplePickerField/PeoplePickerField.tsx(59,63): error TS2345: Argument of type 'import("C:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration' is not assignable to parameter of type 'import("C:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration'.

Property 'flags' is protected but type 'SPHttpClientConfiguration' is not a class derived from 'SPHttpClientConfiguration'.

src/webparts/userProfileWizard/dataProviders/SharePointUserProfileDataProvider.ts(77,75): error TS2345: Argument of type 'import("C:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration' is not assignable to parameter of type 'import("C:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration'.

Type 'Promise<import("c:/Users/<USER>/VSCProjects/Company Connect/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientResponse>' is not assignable to type 'Promise<import("c:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientResponse>'.
  Type 'import("c:/Users/<USER>/VSCProjects/<PRODUCT-NAME>/Errors/1.12.1/webpart-userprofilewizard/node_mod
`

### Steps to reproduce

1. delete node_module and package-lock
2. npm install  & npm dedupe
3. gulp build or gulp serve 
4.  hosted workbench opens ("https://companyname.sharepoint.com/_layouts/workbench.aspx")

### Expected behavior

I expect that the webpart should run and show its newly updated properties webpart

I think that the reason this is happing is as follows:
1. @microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration
2. @pnp/spfx-property-controls/node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClientConfiguration'

maybe because it sees 2 package libraries and it doesn't know which one to pick. but i'm not sure

**Comment by patmill** [comment]
Yes, you are correct - having two different versions at the same time is causing issues.  You can solve this in two ways.  1 - use the beta versions of the controls libraries (they are on 1.13), or 2 - use SPFx version 1.12.1
