### ISSUE TITLE
Using the SPFx generator with npx

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#748]
#### Category
- [X ] Question

I noticed recently that we can use npm@4.6.1 and npx to concurrently use multiple versions of the generator. 

More details in my post here: http://www.vrdmn.com/2017/07/simultaneously-run-multiple-versions-of.html

Can someone from the SPFx team give their thoughts on using this approach? Is there some scenario in which this approach would break?

So far, I have tested the generator and it all seems to work fine.

**Comment by manishgarg1** [comment]
Hi @vman , thanx a lot for the reference. We are aware of npx and are validating it internally. Hopefully we will have some guidance soon.

**Comment by nickpape-msft** [comment]
Hi @vman, there should not be any problem with using NPX alongside the SPFx Yeoman Generator. The Generator itself is simply a Yeoman script that just reads some information about your project (if it exists), and helps to scaffold new components, there is nothing particularly special going on in the background.

There isn't a known scenario where this would break, but if you find one, please open an issue.

I'm closing this one for now. Also, for informational purposes, we may end up releasing some documentation around this scenario.
