### ISSUE TITLE
Dead link on page

### ISSUE THREAD

**Issue by bickell988** [SharePoint/sp-dev-docs#7480]
There is a link on this page that is dead.   

Text "Change the look of your SharePoint site"

Link:  https://support.microsoft.com/en-us/office/change-the-look-of-your-sharepoint-site-06bbadc3-6b04-4a60-9d14-894f6a170818?ui=en-us&rs=en-us&ad=us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by ManuSquall** [comment]
The link seems to work well for me actually

**Comment by ManuSquall** [comment]
So this issue and #7481 can be safely closed i think @VesaJuvonen

**Comment by bickell988** [comment]
Yes.  Can be closed.

**Comment by VesaJuvonen** [comment]
Closing based on the comments.
