### ISSUE TITLE
Dead link in Note section

### ISSUE THREAD

**Issue by bickell988** [SharePoint/sp-dev-docs#7481]
There is a link that is dead on this page:

Text:  Learn more about the new site template experience

Link:  https://support.microsoft.com/office/apply-and-customize-sharepoint-site-templates-39382463-0e45-4d1b-be27-0e96aeec8398?ui=en-US&rs=en-US&ad=US
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site template and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by ManuSquall** [comment]
The link seems to work well for me actually

**Comment by VesaJuvonen** [comment]
Link seems to work, so closing this issue. Could have been a momentary issue at the support web site which has been resolved.
