### ISSUE TITLE
SP List Subscriptions - Cannot read properties of undefined (reading 'pageContext')

### ISSUE THREAD

**Issue by EMaarten** [SharePoint/sp-dev-docs#7482]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.13.0
- Node.js v14.15.0
- Windows 10
- Chrome 95.0.4638.69 (Official Build) (64-bit)

### Describe the bug / error

When trying to implement the SP List Notifications feature (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications) we receive the following error when running our web part:

ERROR:
Cannot read properties of undefined (reading 'pageContext')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'pageContext')
    at new e (https://localhost:4321/node_modules/@microsoft/sp-list-subscription/dist/sp-list-subscription_none_70a7940a139e666ffa48.js:2:77711)

### Steps to reproduce

1. Create an SPFx web part solution
2. Install the @microsoft/sp-list-subscription npm package
`npm install @microsoft/sp-list-subscription --save --save-exact`
3. Add the following code to your web part class file:

```
import { ListSubscriptionFactory, IListSubscription } from '@microsoft/sp-list-subscription';
import { Guid } from '@microsoft/sp-core-library';

...

  private _listSubscriptionFactory: ListSubscriptionFactory;
  private _listSubscription: IListSubscription;

  private createListSubscription(): void {
    this._listSubscriptionFactory = new ListSubscriptionFactory(this);
    this._listSubscription = this._listSubscriptionFactory.createSubscription({
      listId: Guid.parse(this.properties.listId),
      callbacks: {
        notification: this._loadDocuments.bind(this)
      }
    });
  }

  private _loadDocuments(): void {
    console.log("hello world");
  }

```

### Expected behavior

The "_loadDocuments" method should be called when something has been changed in the referred document library.

**Comment by patmill** [comment]
When do you call your private createListSubscription() method?

**Comment by patmill** [comment]
We're having a bit of trouble reproducing this as well.  Is there any chance you can break on the exception and see what the call stack is / where the object is throwing?

**Comment by EMaarten** [comment]
> When do you call your private createListSubscription() method?

I call this method in the constructor of the web part class.

**Comment by EMaarten** [comment]
@patmill you can close this one as I answered my question myself --> constructor... Thanks for the follow-up!
