### ISSUE TITLE
Google Analytics Updates Tags Not Compatible with Google Analytics Block in Sharepoint

### ISSUE THREAD

**Issue by cshenry13** [SharePoint/sp-dev-docs#7483]
The block of content in the SharePoint editor for Google Analytics only displays site with the old Google Analytics tags. It omits sites that have the newest version of the tag.

And, this was the only place I could find to provide this feedback. There isn't a feedback link on the SharePoint page anywhere, and the SharePoint troubleshooting resource feedback is broken.

**Comment by VesaJuvonen** [comment]
Hi @cshenry13, I'm not sure what the SharePoint editor for Google Analytics is, so we would need to have more context on here. What exactly is being used and how? What's the current outcome and what's the expectation?

**Comment by cshenry13** [comment]
I'll try to describe it better:

On the Sharepoint site, you can edit the layout and include other blocks. One of the block you can include was for Google Analytics. When we tried to include this Google Analytics block on the Sharepoint screen, it listed all of the Google Analytics properties that are still using the old Google Property Tag, but it didn't list any of the properties with the new universal GA tag.

**Comment by patmill** [comment]
It looks like this is using the connecter webparts (controls that ship with SharePoint).  Unfortunately, that is outside the scope of this issues list.  You will need to open a ticket with support.
