### ISSUE TITLE
SharePoint Framework interactivity with SharePoint multilingual pages

### ISSUE THREAD

**Issue by juliemturner** [SharePoint/sp-dev-docs#7488]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.13

### Issue description

Currently when you build a multilingual page in SharePoint and create translations all first party web parts honor the language of the page and override the user's current language preference. The SharePoint Framework for 3rd party developers has no straightforward way to accomplish this same thing. 

Ideally the context would include an additional property that would surface some of the hidden page properties for multilingual pages like `_SPTranslationLanguage` so that localization of the web part could work off that value in the cases where an SPFx web part is put on a multilingual page. For instance, if there was an additional property here something like `pageLanguage`. If in addition if there is a page language it could also affect localization like the currentUICultureName does, that would be even better. The long and the short of it is that it's very confusing to users, and nearly impossible to explain to them why 3rd party web parts on multilingual pages do not honor the translation language. There is obviously api calls we could make to get the data and then build a separate implementation of the localization to honor it but that's undesirable.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7570936/141129306-9d6ae484-9fb7-402e-b4da-ea4accace222.png)

**Comment by johnguy0** [comment]
Thank you for opening this issue. Closing since this is not an issue directly with SPFx, but we have opened a bug for the product team.
