### ISSUE TITLE
SPFX webpart is not working on custom page or workbench.aspx

### ISSUE THREAD

**Issue by nihar-s** [SharePoint/sp-dev-docs#749]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I expect to see by newly created webpart included in the webparts on my tenancy / workbench.

#### Observed Behavior
I am using the SPFX and I have created my webpart using SPFX and gulp serve is running on my development machine but when I try and test the web part on my tenancy I get this error message :
**Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.**

This works fine if I use my localhost.

#### Steps to Reproduce
I followed "Build Your First Webart (Hello world)" but changed the name of the webpart, the directory it was in etc to reflect the name of my webpart. 
type gulp trust-dev-cert followed by gulp serve.

If you navigate to your tenancy and _layouts/15/workbench.aspx you get the error message. (I am using Chrome)

I deleted <homedir>/.gcb-serve-data directory and ran gulp trust-dev-cert again.
But, Issue still exists.

**Comment by nihar-s** [comment]
After adding the webpart on page i get this:

Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "b390eb40-71ae-4bcb-9f3c-b6d9522fd9fc" (SpfxwpWebPart).
Original error: ***Failed to load URL 'https://localhost:4321/lib/webparts/spfxwp/loc/en-us.js' for resource 'spfxwpStrings' in component 'b390eb40-71ae-4bcb-9f3c-b6d9522fd9fc' (SpfxwpWebPart). There was a network problem.
Make sure that you have run 'gulp trust-dev-cert'.

***INNERERROR:
***Failed to load URL 'https://localhost:4321/lib/webparts/spfxwp/loc/en-us.js' for resource 'spfxwpStrings' in component 'b390eb40-71ae-4bcb-9f3c-b6d9522fd9fc' (SpfxwpWebPart). There was a network problem.
Make sure that you have run 'gulp trust-dev-cert'.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-webpart-workbench-assembly_en-us_a37a4a27f5994e5037999f08bfdc73e1.js:273:10483)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-webpart-workbench-assembly_en-us_a37a4a27f5994e5037999f08bfdc73e1.js:669:16704)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-webpart-workbench-assembly_en-us_a37a4a27f5994e5037999f08bfdc73e1.js:669:13917)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-webpart-workbench-assembly_en-us_a37a4a27f5994e5037999f08bfdc73e1.js:669:11726)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.008/sp-webpart-workbench-assembly_en-us_a37a4a27f5994e5037999f08bfdc73e1.js:669:110506
    at <anonymous>

**Comment by patmill** [comment]
So, that error normally indicates that your local server isn't reachable.  If you look at your gulp serve window, can you see if any requests are being made to it?  If you look at the developer console in your browser, are there requests to localhost failing?

Did you run gulp trust-dev-cert ?  Are there any inconsistencies between http and https?  Any warnings in your browser, etc?

**Comment by nihar-s** [comment]
Yes, my local server isn't reachable if gulp serve is not running.
Requests are being made on gulp serve (running) window and request to localhost are not failing. I did ran gulp trust-dev-cert. No warnings in browsers or any inconsistencies between http-https.

So, Does gulp serve has to be running for my app to work on SharePoint?

**Comment by patmill** [comment]
Yes, you need to run gulp serve if you are in development mode.  Ie, unless you have updated your manifest to point to a permanent host and uploaded your code to that host, you need to be running gulp serve.

**Comment by nihar-s** [comment]
Okay. Thanks.
