### ISSUE TITLE
How to create templates for SharePoint Online Modern Sites

### ISSUE THREAD

**Issue by OzmeisterO** [SharePoint/sp-dev-docs#7492]
[Enter feedback here]
Hi.  This page says that creating templates is not supported in SharePoint Online (modern sites).  Given most people should now be working with SharePoint Online modern sites, this would be the most useful information!  Could you add a cross-reference to how to do the equivalent for SharePoint Online modern sites please.

Thanks, Oz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5f465-6d87-5a7d-9b0a-7807da51d30b
* Version Independent ID: bc4f4c42-d5ba-a36a-1578-70103e14cde8
* Content: [Save, download, and upload a SharePoint site as a template](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template)
* Content Source: [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Thanks for this. Yes, you are right. We should link to the new functionality. 

In the meantime, if you need reference.

https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview
