### ISSUE TITLE
Vertical Section places Viva Dashboard at the bottom of the page in the SharePoint Mobile experience

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-docs#7493]
Microsft recommends the use of the vertical section for displaying the Viva Dashboard on the SharePoint home site for best results: https://docs.microsoft.com/en-us/sharepoint/create-dashboard#use-the-dashboard-web-part-for-viva-connections

Currently, the vertical section is displayed at the bottom of the responsive page design in the SharePoint mobile/app experience.  This is not the preferred user experience reported by clients.  When a dashboard web part is included in the vertical section, it is preferred to be displayed above the fold.

**Comment by VesaJuvonen** [comment]
Thanks for your input. This is currently by design from our design organization. I've bypassed the feedback to them, but there really is nothing more we can do around this through this issue list.
