### ISSUE TITLE
Want to use SharePoint Online SPFX Solution to SharePoint 2019 On Premises

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7498]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi everyone, 

I have one requirement to use Sharepoint online SPFX solution to Sharepoint 2019 On-Premises.

So currently I have an SPFX solution with v1.12.1  but in SharePoint 2019 On-premises only support the v1.4.1 . 

Can anyone advise that how I can downgrade the SPFX version and what will be impacted (any link)?

Thanks in advance

**Comment by VesaJuvonen** [comment]
There's unfortunately no easy solution for this requirement as there are so many differences on the solution dependencies between the 1.12.1 and 1.4 versions. Depending on the solution, you might need to even use completely different techniques, for example if the solution is using React in 1.12.1.

So no easy answers - best option would be most likely to start by creating a new solution targeted SP2019 and then manually copy the experience you have on the newer version. Any other option would cause much more complex dependency issues to solve and sort out...
