### ISSUE TITLE
Error when loading sp-loadash resource in 0365 workbench.aspx

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#75]
I have the workbench.aspx working from 0365 to my local host, but when the webpart is added to the page I receive the error below. The browser is Chrome and it is allowing mixed content.

![image](https://cloud.githubusercontent.com/assets/10567535/17955376/56c7e2f6-6a47-11e6-8fdb-7efb999c0dbe.png)

**Comment by waldekmastykarz** [comment]
Could it be you're using an older version of the Workbench? The references to lodash start with @ms which is pre-dev preview naming.

**Comment by SteveCurran** [comment]
Thanks Waldek, was not aware the bits had changed this much. So to keep up with the most recent bits without having to construct a whole new solution through yo, you would just do an npm update on the sp modules?

**Comment by waldekmastykarz** [comment]
Unfortunately not: dev preview modules use different naming so the best is to create a new project and retrofit your code into the new project, which requires very few changes.
