### ISSUE TITLE
How to apply Microsoft starter pack2 on SharePoint 2019? How will it impact?

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7500]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

-

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hi everyone, 

Can anyone guild me on how to apply Microsoft starter pack2 on SharePoint 2019? How will it impact?

Thanks in advance

**Comment by VesaJuvonen** [comment]
Unfortunately SharePoint Started Kit is not currently supported in on-premises as it's using newer SPFx version than what SP2019 supports. If you have any further questions on the Starter Kit, we recommend adding them to https://github.com/pnp/sp-starter-kit/issues
