### ISSUE TITLE
SPFx 1.13 does not support node v10 in the Release notes, But this page says otherwise

### ISSUE THREAD

**Issue by Zerg00s** [SharePoint/sp-dev-docs#7504]
[SharePoint Framework v1.13 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.13) mentiones:

> Node v10 is no longer supported. Supported node versions are v12 and v14.

But on this page, in the **SPFx development environment compatibility** table, node v10 is mentioned as supported for 1.13.0.

Unless the release note for SPFx v1.13 is wrong, cand we remove node v10 from the compability matrix from this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25459e4a-2488-302d-9906-cfacfdc4639a
* Version Independent ID: 339fbcec-873c-9c47-fd9c-cf5f505132ac
* Content: [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility?source=docs)
* Content Source: [docs/spfx/compatibility.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/compatibility.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
thx @Zerg00s, just updated and will be visible in docs within 30 min or so.
