### ISSUE TITLE
SPFx apps with Ms Graph does not working on the mobile MS Teams client Android

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7510]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

SPFX app containing MS Graph has stopped working again in android. It works in IOS.

### Steps to reproduce

Open the Teams app on the mobile client (Android)
Navigate to a SPFx personal app
The app won't load

### Expected behavior

The app should load

**Comment by Tanddant** [comment]
A fix I've used is the following:

Under your Azure AD find the "SharePoint Online Client Extensibility Web Application Principal" app registration and open it's manifest.

Under the "oauth2Permissions" property find the "id" and copy it:

```"oauth2Permissions": [
  {
    "adminConsentDescription": "Allow the application to access SharePoint Online Client Extensibility Web Application Principal on behalf of the signed-in user.",
    "adminConsentDisplayName": "Access SharePoint Online Client Extensibility Web Application Principal",
    "id": <COPY THIS GUID>,
    "isEnabled": true,
    "lang": null,
    "origin": "Application",
    "type": "User",
    "userConsentDescription": "Allow the application to access SharePoint Online Client Extensibility Web Application Principal on your behalf.",
    "userConsentDisplayName": "Access SharePoint Online Client Extensibility Web Application Principal",
    "value": "user_impersonation"
  }
```

Go to the "preAuthorizedApplications" and verify that the application with the "appId" "00000003-0000-0ff1-ce00-000000000000" has the GUID that we copied before.


```
"preAuthorizedApplications": [
    {
      "appId": <Random GUID>,
        "permissionIds": [
          <GUID that we copied from oauth2Permissions.id>
        ]
    },
    {
      "appId": <Random GUID>,
        "permissionIds": [
          <GUID that we copied from oauth2Permissions.id>
        ]
    },
    {
      "appId": "00000003-0000-0ff1-ce00-000000000000", // <--- THIS IS THE IMPORTANT ONE
        "permissionIds": [
          <GUID that we copied from oauth2Permissions.id>
        ]
    }
]
```

if that is the case remove the other registrations (keep a backup in notepad or something in case it breaks), you should now have the following:

```
"preAuthorizedApplications": [
    {
      "appId": "00000003-0000-0ff1-ce00-000000000000",
        "permissionIds": [
          <GUID that we copied from oauth2Permissions.id>
        ]
    }
]
```

Hit save and boom your SPFx solutions will work in teams.

**Comment by lucabandMSFT** [comment]
@Tanddant , what you described should automatically happen when you visit the API Access page in SPO tenant admin with an account that has both SPO Tenant admin and AAD Global admin roles. That page should do, beside other checks, what you described in AAD.

@harshdamaniahd , Can you please do the same (navigate to the API Access page in SPO tenant admin with an account that has both SPO Tenant admin and AAD Global admin roles) and see if that solves the issue?

**Comment by lucabandMSFT** [comment]
Just visiting the page with the right role is sufficient.

**Comment by harshdamaniahd** [comment]
> @Tanddant , what you described should automatically happen when you visit the API Access page in SPO tenant admin with an account that has both SPO Tenant admin and AAD Global admin roles. That page should do, beside other checks, what you described in AAD.
> 
> @harshdamaniahd , Can you please do the same (navigate to the API Access page in SPO tenant admin with an account that has both SPO Tenant admin and AAD Global admin roles) and see if that solves the issue?

I asked global admin to visit sharepoint api page and this still remain same

"preAuthorizedApplications": [
		{
			"appId": "random guid",
			"permissionIds": [
				<GUID that we copied from oauth2Permissions.id>
			]
		},
		{
			"appId": "random guid",
			"permissionIds": [
				<GUID that we copied from oauth2Permissions.id>
			]
		},
		{
			"appId": "00000003-0000-0ff1-ce00-000000000000",
			"permissionIds": [
				<GUID that we copied from oauth2Permissions.id>
			]
		}
	]

**Comment by harshdamaniahd** [comment]
For few users it is working 
and for some users i am getting this error
Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '{resource}'.

**Comment by lucabandMSFT** [comment]
Teams Mobile is currently experiencing some issues and the team is working to fix it. We are tracking progresses here: #7646
