### ISSUE TITLE
Recent JSON field change for approval status breaks conditional column formatting for approval status

### ISSUE THREAD

**Issue by JeffLacarte** [SharePoint/sp-dev-docs#7513]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Developer environment

Windows

### Describe the bug / error

With the recent changes from #6731 and #7494 the out of the box column formatting is broken. When you use the conditional formatting tools built into SharePoint the text of the Approval Status column changes to the enum value. I assume the JSON that is generated by this tool simply needs to be updated to reflect the changes from issue 6731.

Screenshot of turning conditional formatting on without having touched "advanced mode"
![built-in-formatting-tool](https://user-images.githubusercontent.com/55037028/141996801-e8e28eda-a789-47d5-a05d-58c5091dbb0a.png)

### Steps to reproduce

1. Create a new list
2. List Settings > Versioning Settings > Require Content Approval: Yes
3. Add an item to the new list
4. Select dropdown beside "Approval Status" select "Column Settings" > "Format this column"
5. Select "Conditional Formatting" from the menu with "Choose Column" set to Approval Status.

![approval col formatting issue](https://user-images.githubusercontent.com/55037028/141997160-e8b94ca4-f983-410f-8c05-b807da316fc7.gif)

### Expected behavior

When using the out of the box conditional column formatting for the Approval Status column I expected the column to retain the wording of the approval statuses: Approved | Pending | Rejected.

**Comment by JeffLacarte** [comment]
Hey guys: @shagra-ms @andrewconnell 

A number of us over at the SharePoint Tech Community have been affected by the recent changes for #7494. It took a while to figure out since the change just "showed up" in our tenant and broke existing JSON formatting. Just today we were alerted to this change here on GitHub. I'm fine with the change and it makes sense. However the tool used to create conditional formatting in SharePoint now displays the enum value instead of the text representing the status of the approval. For those who are not versed in JSON and SP JSON formatting, the out of the box tool is very handy to apply basic formatting rules. I'm sure it's a simple fix to update the JSON behind the scenes to use the new fields.

**Comment by shagra-ms** [comment]
Hi @JeffLacarte, thank you for reaching out and apologies for the pain our change has caused.

We have a local repro of the issue using the 'Conditional Formatting' JSON builder and are actively working on it.

Once the fix is rolled out, users will have to re-apply the formatting using the builder.

**Comment by workflowiq** [comment]
@shagra-ms @JeffLacarte , Hi, This has affected conditional formatting applied to other columns also using JSON. e.g. making a value or button visible based on the value in the Approval Status column. There is a lot of people who have a button or link to start a document or list item approval flow, that now doesn't work. Is there a workaround available we can implement? I have a lot of customers that this has affected.

**Comment by JeffLacarte** [comment]
@workflowiq 
> Hi, This has affected conditional formatting applied to other columns also using JSON. e.g. making a value in a column or button visible based on the value in the Approval Status column. There is a lot of people who have a button or link to start a document or list item approval flow, that now doesn't work. Is there a workaround available we can implement? I have a lot of customers that this has affected.

You likely used either @currentField or [$_ModerationStatus] in your JSON to retrieve the approval status and conditionally format against the "text" value of Approved | Rejected | Pending. Those fields now return the enum value and it lets you conditionally format if you've got multilingual sites. 

I see two ways you can fix your JSON formatting
1. replace @currentField or [$_ModerationStatus] with @currentField.displayValue or [$_ModerationStatus.displayValue] respectively. Those two options will return the text value of your approval status and let you compare against a literal text  value. 
**For example **
```
"operator": "==",
"operands": [
     "@currentField.displayValue",
     "Approved"
]
```
2. Keep @currentField or [$_ModerationStatus] and change what you are comparing against. Instead of comparing against "Approved", compare against 0, the enum value of Approved.
**For example**
```
"operator": "==",
"operands": [
     "@currentField",
     "0"
]
```

At the very least, you'll want to update the txtContent element to use @currentField.displayValue or [$_ModerationStatus.displayValue] so that the column displays the text values: `"txtContent": "@currentField.displayValue"`

**Comment by shagra-ms** [comment]
@JeffLacarte @workflowiq 

We have taken an update, which will give relief to all users. The update is rolling out now and shall be in your tenant in a few days. I will update the docs this week.

**Short summary** - we have enhanced the Approval Status column to support both type of comparison - localized value as well as the internal code.

**Samples** - 
_The following expressions evaluate to the output on the right, for when the status is `Pending`:_

```JS
  // reading field value
  "[$_ModerationStatus]" => "Pending"

  // obtaining the internal numeric value:
  "=Number([$_ModerationStatus])" => 2
  "=[$_ModerationStatus.numeric]" => 2

  // addition results in string concatenation:
  "='status:'+[$_ModerationStatus]" => 'status:Pending'

  // numeric comparisions
  "=([$_ModerationStatus] == 2)" => true
  "=([$_ModerationStatus] != 1)" => true

  // other comparators are rarely useful, for cases where you want might want to exclude Draft & Scheduled
  "=([$_ModerationStatus] < 3)" => true

  // localized string comparision, works only with one locale (en-us here)
  "=if( [$_ModerationStatus] == 'Pending', 'This Works too!', 'Nope!')" => 'This Works too!'
```

**Comment by JeffLacarte** [comment]
> @JeffLacarte @workflowiq
> 
> We have taken an update, which will give relief to all users. The update is rolling out now and shall be in your tenant in a few days. I will update the docs this week.
> 
> **Short summary** - we have enhanced the Approval Status column to support both type of comparison - localized value as well as the internal code.
> 
> **Samples** - _The following expressions evaluate to the output on the right, for when the status is `Pending`:_
> 
> ```js
>   // reading field value
>   "[$_ModerationStatus]" => "Pending"
> 
>   // obtaining the internal numeric value:
>   "=Number([$_ModerationStatus])" => 2
>   "=[$_ModerationStatus.numeric]" => 2
> 
>   // addition results in string concatenation:
>   "='status:'+[$_ModerationStatus]" => 'status:Pending'
> 
>   // numeric comparisions
>   "=([$_ModerationStatus] == 2)" => true
>   "=([$_ModerationStatus] != 1)" => true
> 
>   // other comparators are rarely useful, for cases where you want might want to exclude Draft & Scheduled
>   "=([$_ModerationStatus] < 3)" => true
> 
>   // localized string comparision, works only with one locale (en-us here)
>   "=if( [$_ModerationStatus] == 'Pending', 'This Works too!', 'Nope!')" => 'This Works too!'
> ```

Oh nice, that's great! @shagra-ms  thanks for not only working towards fixing this but also improving it :)

**Comment by shagra-ms** [comment]
The docs are now updated. Resolving this. @JeffLacarte please do let me know, if this doesn't work for you.
