### ISSUE TITLE
webpack warning prevents gulp bundle --ship to bundle the solution after upgrade to 1.12.1 SPFx version

### ISSUE THREAD

**Issue by mohammadamer** [SharePoint/sp-dev-docs#7515]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version : 1.12.1
- Node.js version : 14.17.0
- yo v4.3.0
- gulp v4.0.2
- react v16.9.0

### Describe the bug / error

I have been stumbling upon upgrading react calendar solution to SPFx 1.12.1 or 1.13.0
Webpack warning prevents gulp bundle --ship to bundle the solution after upgrade to 1.12.1 SPFx version

Solution code is a sample solution in SPFx [react-calendar](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar)

```
 Warning - [webpack] 'dist':
./node_modules/fbjs/lib/setImmediate.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* {project-path}\CalendarWebPart\node_modules\fbjs\lib\setImmediate.js
    Used by 1 module(s), i. e.
    {project-path}\CalendarWebPart\node_modules\draft-js\lib\editOnBeforeInput.js
* {project-path}\CalendarWebPart\node_modules\fbjs\lib\setimmediate.js
    Used by 2 module(s), i. e.
    {project-path}\CalendarWebPart\node_modules\fbjs\lib\setImmediate.js
 @ ./node_modules/fbjs/lib/setImmediate.js
 @ ./node_modules/draft-js/lib/editOnBeforeInput.js
 @ ./node_modules/draft-js/lib/DraftEditorEditHandler.js
 @ ./node_modules/draft-js/lib/DraftEditor.react.js
 @ ./node_modules/draft-js/lib/Draft.js
 @ ./lib/controls/Event/event.js
 @ ./lib/webparts/calendar/components/Calendar.js
 @ ./lib/webparts/calendar/CalendarWebPart.js
```

## Steps to reproduce
1. Upgrading SPFx sample [react-calendar](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-calendar) to SPFx 1.12.1 or 1.13.0
2. Build the sample solution
3. Bundle the solution, then you will get the warning issues mentioned before.

## Similar Issues in sp-dev-docs
1. [Webpack warning prevents gulp bundle -ship from working](https://github.com/SharePoint/sp-dev-docs/issues/2542)
2. [There are multiple modules with names that only differ in casing](https://github.com/SharePoint/sp-dev-docs/issues/4934)

## Similar Issues reported about fbjs and Webpack packages
1. [Multiple modules with names that only differ in casing (setImmediate)](https://github.com/facebook/fbjs/issues/234)

### Expected behavior

The expected behavior is to upgrade the SPFx version to be 1.12.1 or 1.13.0 successfully

**Comment by AJIXuMuK** [comment]
Thank you @mohammadamer for reporting this.
First thing to mention - the issue is not related to SPFx, it's an `draft-js`/`fbjs` issue.
Second - this is a warning, not an issue, and the solution is still bundled. You can check the results in `dist` folder.
If you want to remove the warning completely, you can either 
1. check webpack configuration and see if there are any settings to ignore case-semantic OS issues
2. load `draft-js` as external or non-amd module.
