### ISSUE TITLE
Manually Add Webpart From Site Contents in SP2019 Gives Error Something went wrong

### ISSUE THREAD

**Issue by asadshaikhcodes** [SharePoint/sp-dev-docs#7516]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.4.1
- Node.js version 8.x
- etc

### Describe the bug / error

At the time of scaffolding the SPFX 2019 on premise webpart I checked deploye on all tenant and my webpart gets deployed with no issues, however when it is unchecked and when I try to add manually on other site collection from Site Contents it gives error something went wrong.

### Steps to reproduce

1. Scaffold SPFX 2019 on premise with yeoman
2. uncheck deploye on all tenants
3. try to add from site contents

### Expected behavior

Webpart should get added in site collection

**Comment by patmill** [comment]
Can you explain what errors happened, etc?  There really isn't much to go on with this bug at the moment.
