### ISSUE TITLE
It looks like this is using the connecter webparts (controls that ship with SharePoint).  Unfortunately, that is outside the scope of this issues list.  You will need to open a ticket with support.

### ISSUE THREAD

**Issue by cshenry13** [SharePoint/sp-dev-docs#7518]
It looks like this is using the connecter webparts (controls that ship with SharePoint).  Unfortunately, that is outside the scope of this issues list.  You will need to open a ticket with support.

_Originally posted by @patmill in https://github.com/SharePoint/sp-dev-docs/issues/7483#issuecomment-970612710_

I accept that this is off-topic. However, none of the support options from within Sharepoint work. There is not a support link and the Microsoft support page wiki link is broken.

**Comment by bcameron1231** [comment]
Hi, as mentioned on the other thread, you would need to open a support ticket with Microsoft. Have you tried this method?

https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide

**Comment by cshenry13** [comment]
I have now, thank you
