### ISSUE TITLE
Build your first field-extension doesn't load anything!!

### ISSUE THREAD

**Issue by gurleen23** [SharePoint/sp-dev-docs#752]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [*] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The Field Extension loads after being prompted to load the debug scripts.

#### Observed Behavior
The Field Extension never loads because the Load debug scripts prompt never appears. The gulp server never shows a request made for the manifest file running on localhost.

Tested In Chrome, Edge, and IE11.
Tested on both classic and modern site.
Nothing is working

#### Steps to Reproduce
Follow steps here: https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/building-simple-field-customizer

**Comment by manishgarg1** [comment]
@pgonzal ?

**Comment by Jiannko** [comment]
Are you using  working using an  Office 365 developer tenant ?

**Comment by gurleen23** [comment]
Yes I am.

**Comment by gurleen23** [comment]
#701 
I followed the discussion on this post. I'm currently working on dev tenant.I also made changes as it has been referred in the Matt's post. But still I see nothing. Load debug scripts prompt never appears.

**Comment by VesaJuvonen** [comment]
Hi Gurleen, There have been some random issues with this preview capability. What site template are you using for this? - If you are using classic team site with modern list experience, it should be all good. If you are using modern group site, we've seen some issues. Can you confirm the site template used for the testing? thx.

**Comment by VesaJuvonen** [comment]
Hi Gurleen, there could be few things causing this issue in your case. First thing to check would be the dev-cert installation - so double checking that by executing ´gulp trust-dev-cert´ to ensure that calls towards your localhost are working fine.

Could you also double check the content in the developer tools with F12 and what's visible in the Console window, so that we would get additional insights on what's wrong in your case. Thx.

**Comment by gurleen23** [comment]
Thanks for the reply @VesaJuvonen!
So, I tried "gulp trust-dev-cert" at first and it executed as follows:
` C:\spfx\field-extension>gulp trust-dev-cert 
 Build target: DEBUG 
 [09:49:43] Using gulpfile C:\spfx\field-extension\gulpfile.js
 [09:49:43] Starting gulp 
[09:49:43] Starting 'trust-dev-cert'... 
 [09:49:43] Starting subtask 'trust-cert'... 
 [09:49:45] Finished subtask 'trust-cert' after 2.23 s
 [09:49:45] Finished 'trust-dev-cert' after 2.24 s  
[09:49:45] ==================[ Finished ]==================                                                             [09:49:46] Project field-extension version: 0.0.1
[09:49:46] Build tools version: 2.5.3
[09:49:46] Node version: v6.11.1
[09:49:46] Total duration: 1.1 min    `

Then after this I executed "gulp serve --nobrowser" and again after changing the URL of my list to debug the field customizer, I got no prompt for debug scripts and when check the content of the developer tools it gives me this:

![image](https://user-images.githubusercontent.com/19613374/28877337-12b8b29e-776a-11e7-94d1-3e52bf945a4c.png)

I don't know if this error has anything to do with field customizer extension.

**Comment by bcameron1231** [comment]
@gurleen23  make sure you are using a Developer Tenant, not a Developer Site Collection.

**Comment by gurleen23** [comment]
@bcameron1231 
Thanks!
I saw your blog post. It helped.

**Comment by portlandjk** [comment]
I resolved the problem by exiting from Classic experience.
