### ISSUE TITLE
Intermitted exception on old SPFx web part related on missing theme color definitions - breaking production scenarios

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-docs#7520]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
Version 95.0.1020.53 (Official build) (64-bit)
- SPFx version
1.12.1
- Node.js version
v14.16.1

### Describe the bug / error

Started seeing an intermittent error when loading a custom SPFx web part that is deployed for many months. 
The colour mentioned in the error is not explicitly used by the solution so this looks like an internal platform issue.

![image](https://user-images.githubusercontent.com/19577724/142617606-42a971bb-6649-40c2-bece-f752872778ad.png)

### Steps to reproduce

Not tried to reproduce with a new solution as this seems like an internal issue.

### Expected behavior

Not applicable

**Comment by anoopt** [comment]
Not sure if this is related - recently I noticed that if you have a theme handler function named `onThemeChanged` then that function is called before `onInit`. (Looks like `onThemeChanged` is an OOB SPFx function now? Not sure). 

So I had to change the theme handler's function name to something else other than `onThemeChanged`.

**Comment by AJIXuMuK** [comment]
Hello @anoopt - thank you for reporting this one.

Do you have any sample you can share with us to repro the issue?
Do you use PnP Controls or other libraries that could use `neutralLighterAlt`?

**Comment by joelfmrodrigues** [comment]
@AJIXuMuK it was me who reported it :)
I don't have a sample to repro the issue at the moment.
Good point, PnP controls are used so the issue could be there.
Also raised on Twitter and got this comment for reference: https://twitter.com/vesajuvonen/status/1461651762524397573

**Comment by joelfmrodrigues** [comment]
@anoopt just checked and there is no onThemeChanged handler function on the web part code

**Comment by AJIXuMuK** [comment]
Sorry @joelfmrodrigues - my bad. 
Just to move to the right direction: 
1. Do you use section background handling?
2. If yes - what's the handler name?
3. Is it happening on some specific site/page/Teams only?

We're working on themes improvements, so it definitely can be a regression 
Thanks!

**Comment by joelfmrodrigues** [comment]
I was unable to recreate this issue after posting it here...tried for a while, also clearing cache and private browsing but no luck
I have asked the client to let me know if they see it again and will update this thread if the issue persists

Thanks all!

**Comment by AJIXuMuK** [comment]
Hi @joelfmrodrigues,
Wanted to follow up and check if the issue has ever appeared again?

**Comment by joelfmrodrigues** [comment]
@AJIXuMuK thanks!
I have asked the client to report back if they have seen it again, but nothing was reported so far...Unfortunately, with this specific client, it could be that it never happened again or they simply did not report it...
Feel free to close the issue if no one else reported the same problem and if I have it reported again I will investigate further first.
Thanks a lot!

**Comment by AJIXuMuK** [comment]
Thanks @joelfmrodrigues for the confirmation!
