### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by LennartaeHoefer** [SharePoint/sp-dev-docs#7521]
The Link https://docs.microsoft.com/en-us/sharepoint/viva-connections on the page https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams leads to 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Thx @LennartaeHoefer, fixed now 🙏
