### ISSUE TITLE
Connect your webPart to Sharepoint does not work

### ISSUE THREAD

**Issue by AlperSL** [SharePoint/sp-dev-docs#7522]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I am going through the Sharepoint Framework Getting Started.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint

I am getting the following error at the end of the access to Sharepoint List section.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "f46d0c33-7ceb-4214-a31c-e664a0595ff1" (HelloWorldWebPart). Original error: Failed to load entry point from component "f46d0c33-7ceb-4214-a31c-e664a0595ff1" (HelloWorldWebPart). Original error: Error loading https://relative-path.invalid/@microsoft/sp-http as "@microsoft/sp-http" from https://component-id.invalid/f46d0c33-7ceb-4214-a31c-e664a0595ff1_0.0.1
	Unable to load script https://relative-path.invalid/@microsoft/sp-http

INNERERROR:
Failed to load entry point from component "f46d0c33-7ceb-4214-a31c-e664a0595ff1" (HelloWorldWebPart). Original error: Error loading https://relative-path.invalid/@microsoft/sp-http as "@microsoft/sp-http" from https://component-id.invalid/f46d0c33-7ceb-4214-a31c-e664a0595ff1_0.0.1
	Unable to load script https://relative-path.invalid/@microsoft/sp-http
CALLSTACK:
Error
    at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_82c0a4d9c2efef86e23c87cb96d18aca.js:2:111969)
    at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_82c0a4d9c2efef86e23c87cb96d18aca.js:68:9374)
    at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_82c0a4d9c2efef86e23c87cb96d18aca.js:68:46574)
    at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_82c0a4d9c2efef86e23c87cb96d18aca.js:68:42619)
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_0e72155ab8ba4215d52d.js:1:11895

### Steps to reproduce

1. Go through the Getting Started Section. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint. Add Retrieve list data section,
2. gulp serve and add WebPart
3. The above error is displayed.
Note that the previous section just worked fine. I was able to use the Context.

### Expected behavior

I was expecting to see the list to be rendered.

**Comment by bcameron1231** [comment]
Hi, unfortunately you haven't provided all of the details for the issue which makes it a bit more difficult for us to help diagnose the issues. 

1. Could you fill out the "Additional Environment Details"
2. Could you put the source up into GitHub for us to look at and review?
