### ISSUE TITLE
AdaptiveCardExtensionContext httpClient is not assignable to type @microsoft/sp-http HttpClient

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-docs#7525]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

[ Windows 10 Enterprise, iOS 14.8 ] Operating System
[ v14.18.1 ] Node version
[ 4.0.2 ] Gulp version
[ @1.13.0  ] SPFx Generator version

### Describe the bug / error

The AdaptiveCardExtensionContext.httpClient is not assignable to a @microsoft/sp-http HttpClient type since upgrading from:

    "@microsoft/sp-adaptive-card-extension-base": "1.13.0-beta.24",  ---->  "@microsoft/sp-adaptive-card-extension-base": "1.13.0",
    "@microsoft/sp-core-library": "1.13.0-beta.24", ----> "@microsoft/sp-core-library": "1.13.0",
    "@microsoft/sp-property-pane": "1.13.0-beta.24", ----> @microsoft/sp-property-pane": "1.13.0",

error message:

```
Type 'import("c:/Users/ajohnson/Repos/AAM/AAM%20%E2%80%93%20POWERhouse%20Intranet%20Modernization/apps/dashboard/node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http/dist/index-internal").HttpClient' is not assignable to type 'import("c:/Users/ajohnson/Repos/AAM/AAM%20%E2%80%93%20POWERhouse%20Intranet%20Modernization/apps/dashboard/node_modules/@microsoft/sp-http/dist/index-internal").HttpClient'.
  Types have separate declarations of a private property '_fetchProvider'.
```

### Steps to reproduce

Steps to reproduce:

1. Scaffold an ACE with 1.13.0 SPFx generator version

2. Attempt to assign AdaptiveCardExtensionContext.httpClient to HttpClient property

```
import { AdaptiveCardExtensionContext } from '@microsoft/sp-adaptive-card-extension-base';
import { HttpClient, IHttpClientOptions, HttpClientResponse } from '@microsoft/sp-http';

export class WeatherService {
    private LOG_SOURCE: string = "WeatherService";
    private _context: AdaptiveCardExtensionContext;
    private client: HttpClient;
    constructor(context: AdaptiveCardExtensionContext) { 
        this._context = context;
        this.client = this._context.httpClient;
    }
```

### Expected behavior

Expect to be able to use AdaptiveCardExtensionContext.httpClient with @microsoft/sp-http HttpClient.

**Comment by patmill** [comment]
Do you have a reference to the beta builds somewhere?

**Comment by johnguy0** [comment]
@Annie-Johnson can you try deleting your `node_modules` folder and then re-installing? It seems like your package manager has two different versions of `@microsoft/sp-http` installed and pulling from both, which is causing the type mismatch. 

`node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http/dist/index-internal`
`node_modules/@microsoft/sp-http/dist/index-internal`
