### ISSUE TITLE
Uncaught (in promise) undefined (sp-classic-page-assembly)

### ISSUE THREAD

**Issue by alex-buys-github** [SharePoint/sp-dev-docs#753]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The web part should load properly (along with other CEWB referencing Angular scripts) on classic publishing pages (in classic web sites) as it does on modern pages (the development environment).

#### Observed Behavior
The Angular CEWB web parts load properly and work as expected but the SPFx Angular web part doesn't load. The SPFx web part throws the following error:

![image](https://user-images.githubusercontent.com/26911544/28757560-d2aa520c-75d9-11e7-89b8-127cf6e22999.png)

Debug console has the following error:

![image](https://user-images.githubusercontent.com/26911544/28757579-2041709a-75da-11e7-8530-fd6c6b6fe80d.png)

#### Steps to Reproduce
Build a basic Angular SPFx web part - as per tutorial here [Angular ToDo Web Part](https://blog.mastykarz.nl/building-sharepoint-framework-client-side-web-parts-angular/)

Add a Content Editor web part that links to an Angular app (i.e. HTML page and JS script stored in SharePoint StyleLibrary).

Note, that we are not using office UI Fabric in SPFx web part and Angular is bundled with the app (not loaded from CDN).
I updated all the NPM dependencies as listed on the latest GA release wiki. The SPFx web part works perfectly on modern pages alongside other Angular SPFx web parts.
Lastly, we use requirejs to load a bunch of scripts (Angular being one of them as well as JQuery).

AngularJs v1.5.5 is being used for CEWB Angular web parts so I made sure that NPM version for SPFx is limited to 1.5.5. 

Any help will be appreciated.
Tags: #spfx #AngularJs #RequireJS 
[todo-webpart.zip](https://github.com/SharePoint/sp-dev-docs/files/1186036/todo-webpart.zip)
[package.zip](https://github.com/SharePoint/sp-dev-docs/files/1186037/package.zip)
[config.zip](https://github.com/SharePoint/sp-dev-docs/files/1186038/config.zip)

**Comment by alex-buys-github** [comment]
I think this could be an issue specific to us.  Upon further investigation, I found that moment.min.js (latest version) and jquery.validate.min.js (latest version) is causing the issue.  We bundle those along with several other scripts together and make use of requirejs to load this one monolithic bundled script.  The two scripts JQuery validate and momentjs together seem to break the SPFx web part (but oddly enough only on classic pages).

**Comment by alex-buys-github** [comment]
Closing the issue. Reopen if necessary

**Comment by sprider** [comment]
@alex-buys-github 

Did you resolve this issue for classic pages? I am facing the similar issue and i am using "moment" in my webpart.

**Comment by kmarwen** [comment]
I also facing same prob for any Jquery plugin
