### ISSUE TITLE
Missing Property office in package sp-webpart-base interface ISDKs

### ISSUE THREAD

**Issue by petkir** [SharePoint/sp-dev-docs#7535]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version edge current version
- SPFx version 1.13
- Node.js version V12
- Package "@microsoft/sp-webpart-base"

### Issue description

package "@microsoft/sp-webpart-base"
```
export declare interface ISDKs {
    microsoftTeams?: IMicrosoftTeams;
    /**
     * Contextual information about the current Office app. This object will only be defined if
     * a component is being hosted in an Office app.
     *
     * @remarks
     * For more information, please see:
     * {@link https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office}
     *
     * @beta
     */
    office?: IOffice;
}
```

Since Version 1.10.0-plusbeta  the context Property sdks has two properties

- this.context.sdks.microsoftTeams
- this.context.sdks.office

![Screenshot 2021-11-24 at 20 34 12](https://user-images.githubusercontent.com/13123689/143305411-779601dc-12ad-49ad-9980-a665db03b155.png)

in the package non plusbeta the context Property sdks have only one property

- this.context.sdks.microsoftTeams

![Screenshot 2021-11-24 at 20 34 51](https://user-images.githubusercontent.com/13123689/143305355-4d5adf34-6989-4a80-b538-6f08f8dbd8fb.png)

SPFx 1.13.0 and 1.13.1 have no plusbeta package(or I have not found it).
Will this Feature dropped?

**Comment by AJIXuMuK** [comment]
Hello @petkir,

Generally speaking, `office` sdk is deprecated.
It is still available in beta versions of the packages (you can `npm i` beta versions), but I would not recommend to use it.
