### ISSUE TITLE
ACE Teams Deep Link Not Navigating to Specific Tab

### ISSUE THREAD

**Issue by Ismael-Cruz** [SharePoint/sp-dev-docs#7536]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- Microsoft Edge Version 96.0.1054.34 (Official build) (64-bit)
- SPFx v1.13.1
- Node v14.18.0

### Describe the bug / error

While using the Deep Link to go to a specific tab in Teams (https://teams.microsoft.com/l/entity/AppId/EntityId) in an Adaptive Card Extension, it works fine from the Dashboard in the Mobile Teams App, but it does not work from the SharePoint Dashboard (it goes to Teams and the App specified in the link, but not to the Tab).

### Steps to reproduce

1. Use the External Link in the CardView (onCardSelection) specifying isTeamsDeepLink to True.
2. Clicking on the Card will redirect to Teams but not to the specified Tab in the URL of the Deep Link.

Example of link in method onCardSelection:
`{
    type: 'ExternalLink',
        parameters: {
            target: 'https://teams.microsoft.com/l/entity/<APP_ID>/<ENTITY_ID>',
            isTeamsDeepLink: true
    }
}`

### Expected behavior

On clicking it should redirect to the Teams App on the specified App (it already does) and to the specified Tab (currently it does not).

**Comment by patmill** [comment]
Thanks @Ismael-Cruz - this was fixed over the holidays and should roll out to production in a week or two.

**Comment by patmill** [comment]
This should be rolled WW now.
