### ISSUE TITLE
ACE QuickView Action Buttons with Deep Links not working on Mobile Teams Dashboard

### ISSUE THREAD

**Issue by Ismael-Cruz** [SharePoint/sp-dev-docs#7537]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- iOS Microsoft Teams App
- SPFx v1.13.1
- Node v14.18.0

### Describe the bug / error

If you add Buttons in the QuickView adaptive card with Deep Links, it opens the URL in the browser, it goes back to Teams app but stays in the QuickView where you clicked, it never navigates to that URL.

### Steps to reproduce

1. Add an Action.OpenURL in the QuickView adaptive card with a Teams Deep Link (i.e.: https://teams.microsoft.com/l/entity/APP_ID/ENTITY_ID).
2. When clicking on it, it will do the redirect cycle through the browser, but when going back to teams it will stay in the QuickView.

### Expected behavior

Best expected behavior:
- The link will go directly to the Deep Link URL without going through the browser.

Expected behavior for this issue:
- After redirecting through the browser it should go to the Deep Link URL instead of staying in the QuickView.

**Comment by patmill** [comment]
Thanks @Ismael-Cruz - looking into this.  This is a totally valid scenario.  Following up with the mobile app folks.
In the meantime, can you confirm that the target is an app that is installed on the users device, and that it is allowed on mobile.
Also - can you try and add the same app as a Teams Card and see if that executes a deep link correctly?

**Comment by Ismael-Cruz** [comment]
> Thanks @Ismael-Cruz - looking into this. This is a totally valid scenario. Following up with the mobile app folks. In the meantime, can you confirm that the target is an app that is installed on the users device, and that it is allowed on mobile. Also - can you try and add the same app as a Teams Card and see if that executes a deep link correctly?

I confirm that the app is installed on the users device. In fact, if I add the link while clicking on the CardView of the ACE (where you can specify the property "isTeamsDeepLink" to true, using the method "onCardSelection") it works fine, redirecting to the specific Tab in the selected App, and without redirecting through the browser.

I tested with a Teams Card and it executes the deep link properly. The problem seems to be exclusive to the QuickView in the Adaptive Card Extension.

As added information: I tried both with the ActionSet (both by Action.Submit and Action.OpenURL) and a hyperlink in the text.

**Comment by Ismael-Cruz** [comment]
**UPDATE**: After several more tests we found that the issue happens only in the Teams App for iOS, on Android it seems to work fine.
Tested in: 
- iOS 14.8.1 + Teams App Version 3.19.0
- iOS 15.1 + Teams App Version 3.20.0

**Comment by patmill** [comment]
Thanks for the additional info - that helps us.

**Comment by dennisjsyi** [comment]
Sorry for the late reply. We have identified the issue and will be creating a fix for it.

**Comment by harshdamaniahd** [comment]
Also, if we have an external link on the quickview (not a team deep link url) , it doesn't open inside the inbuilt browser. instead it opens outside teams, in browser @dennisjsyi

**Comment by dennisjsyi** [comment]
Hi @harshdamaniahd  it is expected external links open outside of teams. Here is the document https://learn.microsoft.com/en-us/viva/connections/use-the-link-card#considerations-for-the-navigation-experience.

I will look into teams deeplink navigation in quick view in the upcoming week and update you.

**Comment by dennisjsyi** [comment]
@Ismael-Cruz @harshdamaniahd I've tested in VCD deep link navigation that is configured to a quick view button. It is opening teams app in VCD and issue does not reproduce. Can you verify?

**Comment by harshdamaniahd** [comment]
Hi @dennisjsyi  , i am trying to open a sharepoint page inside quick view like this ? is this supported ? ..it works in desktop but not in mobile
https://teams.microsoft.com/l/stage/2a527703-1f6f-4559-a332-d8a7d288cd88/0?context= {"contentUrl":"https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","websiteUrl":"https://postennorge.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","name":"testn"}

**Comment by harshdamaniahd** [comment]
> * iOS 14.8.1 + Teams App Version 3.19.0
> * iOS 15.1 + Teams App Version 3.20.0
Do we have a fix here ?

**Comment by harshdamaniahd** [comment]
Thanks

**Comment by dennisjsyi** [comment]
@harshdamaniahd can you verify that the original issue of the bug is not reproducing?

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd can you verify that the original issue of the bug is not reproducing?

Yes i can confirm that it is working in ios , android, teams desktop, web

**Comment by dennisjsyi** [comment]
@harshdamaniahd Thanks for confirming.

On a related note, we are tracking `https://teams.microsoft.com/l/stage/2a527703-1f6f-4559-a332-d8a7d288cd88/0?context= {"contentUrl":"[https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","websiteUrl":"https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","name":"testn"}](https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx%22,%22websiteUrl%22:%22https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx%22,%22name%22:%22testn%22%7D)` deep link issue in IOS.

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd Thanks for confirming.
> 
> On a related note, we are tracking `https://teams.microsoft.com/l/stage/2a527703-1f6f-4559-a332-d8a7d288cd88/0?context= {"contentUrl":"[https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","websiteUrl":"https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx","name":"testn"}](https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx%22,%22websiteUrl%22:%22https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx%22,%22name%22:%22testn%22%7D)` deep link issue in IOS.

I have also tested in mac desktop and web ...and it works. but everytime it asks for to do this i.e download the sharepoint mobile app  
![image](https://user-images.githubusercontent.com/11780473/214512632-c99736b0-7c59-47ef-b64b-8207bfe5a9c0.png)

**Comment by frags51** [comment]
@harshdamaniahd , Thanks for reporting the issue. As a workaround for now, would it be possible for you to use direct link to the SharePoint page instead of a stageview deeplink? e.g. just set the URL to `https://test.sharepoint.com/teams/f1pilotusers/SitePages/Yo-yo.aspx`.

**Comment by harshdamaniahd** [comment]
then it will open outside teams. in a browser correct?

**Comment by frags51** [comment]
@harshdamaniahd From Viva Connections mobile, it will open within Viva Connections app. From teams desktop, it may open in browser outside of teams..

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd From Viva Connections mobile, it will open within Viva Connections mobile app. From teams desktop, it may open in browser outside of teams..

Was there anything pushed recently ?

Thanks, it did not work before . But now it works on ios and android. 

On ios, there is no back button
On Android , there is back button

**Comment by frags51** [comment]
> Thanks, it did not work before . But now it works on ios and android.

Ah, good to hear. We were tracking a fix - did you update your Teams app recently? 

Could you please paste screenshot of the About page from Viva Connections > Triple dot menu > About?, from both iOS and Android?

**Comment by harshdamaniahd** [comment]
In ios , it was not working. but now it works. @frags51 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11780473/215461677-57d69a89-24c8-42c5-8dde-f66dd5506ee9.png)


so when we open the sharepoint link, it behaves like this
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11780473/215461542-14487e3b-4793-4fb3-a2a1-b0c081f96ec5.png)


-----------------------------------------------------------------------------------------------------------------------------

on android there is some bug I believe.

when we open a sharepoint page either from quick view or from resources tab and that page contains a news webpart then if you click on a news , then the news opens , but you cant go back, the only option is to kill the app

**Comment by frags51** [comment]
@harshdamaniahd , I was looking for the about page from inside of Viva Connections, not the one that you pasted. i.e. this page: 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/25797471/215666152-bd186e39-ff9e-48fd-b809-e991d1c79cde.png">

It is accessible from the triple dot menu or gear icon on the header in Viva Connections app.

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd , I was looking for the about page from inside of Viva Connections, not the one that you pasted. i.e. this page: 
> 
> <img width="392" alt="image" src="https://user-images.githubusercontent.com/25797471/215666152-bd186e39-ff9e-48fd-b809-e991d1c79cde.png">
> 
> 
> 
> It is accessible from the triple dot menu or gear icon on the header in Viva Connections app.
From ios
![image](https://user-images.githubusercontent.com/11780473/215746556-73223ba1-d686-46d3-b1da-702c6d4ee582.png)

**Comment by harshdamaniahd** [comment]
> > @harshdamaniahd , I was looking for the about page from inside of Viva Connections, not the one that you pasted. i.e. this page: 
> > 
> > <img width="392" alt="image" src="https://user-images.githubusercontent.com/25797471/215666152-bd186e39-ff9e-48fd-b809-e991d1c79cde.png">
> > 
> > 
> > 
> > It is accessible from the triple dot menu or gear icon on the header in Viva Connections app.
> From ios
> ![image](https://user-images.githubusercontent.com/11780473/215746556-73223ba1-d686-46d3-b1da-702c6d4ee582.png)

For android
![image](https://user-images.githubusercontent.com/11780473/215752962-8043fc4d-fd9f-4019-a034-be99845e24dc.png)

**Comment by frags51** [comment]
Thanks @harshdamaniahd , please give me sometime to get this checked by the team.

**Comment by frags51** [comment]
@harshdamaniahd / @Ismael-Cruz Could you please confirm if you are still facing this issue? I believe it should have been fixed with the latest version of Teams app.
