### ISSUE TITLE
Card icon is not displayed in Viva Connections Mobile (Teams app)

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7539]
The fluent UI icon is displayed in the dashboard when using the desktop browser but not when using the Teams app on the phone.
It displays a cloud instead:

DESKTOP:
![image](https://user-images.githubusercontent.com/24438807/143584213-8e93a976-8f21-4523-a007-13a9e25af324.png)

MOBILE:
![image](https://user-images.githubusercontent.com/24438807/143584485-4379c336-f994-449f-b1b6-387681ecd04c.png)

CODE SAMPLE:
```
protected get iconProperty(): string {
	return 'AlertSolid';
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Version Independent ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Content: [Known issues for Adaptive Cards in Viva Connections Mobile](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/known-issues-adaptive-cards)
* Content Source: [docs/spfx/viva/known-issues-adaptive-cards.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/known-issues-adaptive-cards.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by patmill** [comment]
Currently only a subset of the fluent UI Icons are supported in the mobile app.  The current workaround is to include the icon itself in the solution vs. referencing it by name.  We will get a list of the supported icons published (although you can see what is supported by using the "URL Card" and viewing the icons from the picker.)
