### ISSUE TITLE
Different color for actions in Viva Connections Mobile (Teams app)

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7540]
I understand this is not really an issue as different hosts can render the cards in different ways but it would be great if the colors of the actions can be the same both the dashboard in the desktop browser and the dashboard in Teams app on the phone.

DESKTOP, uses primary color
![image](https://user-images.githubusercontent.com/24438807/143585311-4b7adbb7-30ee-4749-9ae7-da3d1e89a2b9.png)

MOBILE, uses secondary color
![image](https://user-images.githubusercontent.com/24438807/143585244-acaf3da3-5cb6-4226-bb58-5faa81516b51.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Version Independent ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Content: [Known issues for Adaptive Cards in Viva Connections Mobile](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/known-issues-adaptive-cards)
* Content Source: [docs/spfx/viva/known-issues-adaptive-cards.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/known-issues-adaptive-cards.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by patmill** [comment]
So, what you are probably seeing is that the default theme in SharePoint (in a webpage) is different than the default theme of Teams (mobile).  At this point in time, this is working as expected.  If the theme colors matched in teams and SharePoint, then they would match in desktop and mobile as well.
