### ISSUE TITLE
SVG images are not working in the QuickView card in Viva Connections Mobile (Teams app)

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7541]
The SVG images are being loaded correctly in the dashboard when using the desktop browser. They also work in the the dashboard in Teams app on the phone except when they are placed in the QuickView.

DESKTOP:
![image](https://user-images.githubusercontent.com/24438807/143597531-506a8d61-007a-41f5-893f-df45dee2ddd6.png)

MOBILE:
![image](https://user-images.githubusercontent.com/24438807/143598235-4c43bbdb-9c91-4590-a64c-2b8fe013ca20.png)

CODE SAMPLE:
 ```
 {
  type: "Column",
  width: "auto",
  items: [
    {
      type: "ActionSet",
      actions: [
        {
          type: "Action.Submit",
          iconUrl: require('../assets/ArrowIcon.svg'), //NOT working in Teams
          title: strings.ViewButton,
          style: "positive",
        }
      ]
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Version Independent ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Content: [Known issues for Adaptive Cards in Viva Connections Mobile](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/known-issues-adaptive-cards)
* Content Source: [docs/spfx/viva/known-issues-adaptive-cards.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/known-issues-adaptive-cards.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by Rafaelki** [comment]
Thank you @patmill . No, I don't have the CDN enabled in my tenant

**Comment by PooLP** [comment]
I have the same problem with a different implementation of SVG :

```ts
public get data(): IImageCardParameters {

const image = `data:image/svg+xml;utf8,
      <svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' version='1.1' width='100%' height='100%'>
        <g>
        <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
        </g>
      </svg>`;

const icon = `data:image/svg+xml;utf8,
      <svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' version='1.1' width='100%' height='100%'>
        <g>
        <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
        </g>
      </svg>`;

    return {
      primaryText: 'primary text',
      title: 'Shortcuts',
      imageUrl: image,
      iconProperty: icon
    };
  }
```

it's work in web browser and desktop app, but not in mobile app.

**Comment by Mikhail2k15** [comment]
@patmill looks like svg images are not working at all on **iOS** on Card View, Quick View. It doesn't matter whether it base64 embedded image or not.

**Comment by Zaidos9** [comment]
Full SVG support on mobile is in backlog and we are working on it. Please expect the next update in April.

**Comment by PooLP** [comment]
Hi @Zaidos9 , any news for this ? I have tested today, and the ACE with SVG do not appear anymore for me.
Why @anoopt have closed this unresolved bug ?

**Comment by anoopt** [comment]
@PooLP - this issue is still open.

Whereas a [related issue - Viva Connections - Multiple issue with images in Microsoft Teams](https://github.com/SharePoint/sp-dev-docs/issues/7785) is closed by Microsoft (not by me :) )

**Comment by PooLP** [comment]
ok, sorry.
I commented a little quickly and angry. The lack of responsiveness and transparency for resolving bugs is getting heavy. (ex : https://github.com/SharePoint/sp-dev-docs/issues/6477)

**Comment by AJIXuMuK** [comment]
@PooLP - I'm really sorry some issues are stuck for a long time.
We're doing our best to triage and update the issues regularly. But some of them may be cross-team/cross-org.
And that leads to a longer investigation/fix process.
We could reply "we're still looking into it" but I don't think it'll make the life easier.

**Comment by PooLP** [comment]
@AJIXuMuK, you don't need to apologize, MS engineers like you are also in an unpleasant position, but Microsoft will have to understand that it is annoying that a bug detected and checked can take several months or even years to be resolved and that the lack of communication does not help.

**Comment by PooLP** [comment]
@Zaidos9 @AJIXuMuK  any news ? it's not resolved for me.

**Comment by johnguy0** [comment]
@Zaidos9 Can you provide an update?

**Comment by alexc-MSFT** [comment]
Any update on this issue please? I have  Card Designer card with an SVG in the quick view which will not render on the mobile dashboard (iOS). Looks like it's been at least 6 months with no update. Is this support coming?

Thanks

**Comment by frags51** [comment]
@alexc-MSFT @anoopt @PooLP - This issue should have been fixed now. Could you please confirm if you are still seeing this behavior?

**Comment by PooLP** [comment]
Hi, After fast test, SVG image (link) work, but the base64 didn't work.

I will update my project to SPFx 1.17.2 to see if that fixes the problem.

**Comment by PooLP** [comment]
it's ok for me after update to SPFx 1.17.2 !
