### ISSUE TITLE
The index keyword is not working in Viva Connections Mobile (Teams app)

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7543]
We are using Advanced templating in some of our adaptive cards. This works well in the dashboard when using the desktop browser but some keywords are not being replaced in the dashboard in Teams app on the phone. 
See below the example with the {$index} keyword:

DESKTOP:
![image](https://user-images.githubusercontent.com/24438807/143599810-30a2db3e-1db3-48d8-851f-07932f248421.png)

MOBILE:
![image](https://user-images.githubusercontent.com/24438807/143600353-3f3e8289-f2bf-4fe3-909a-3fc960180a3d.png)

CODE SAMPLE
```
      body: [
        {
          type: "ColumnSet",
          $data: "${data}",
          separator: true,
          columns: [
            {
              type: "Column",
              width: "stretch",
              items: [
                {
                  type: "TextBlock",
                  weight: "Bolder",
                  text: "Item number {$index}",
                  wrap: true
                }
              ]
            }
          ]
        }
      ]

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Version Independent ID: 85245633-6fa2-0c62-7d63-17a6245a3da2
* Content: [Known issues for Adaptive Cards in Viva Connections Mobile](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/known-issues-adaptive-cards)
* Content Source: [docs/spfx/viva/known-issues-adaptive-cards.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/known-issues-adaptive-cards.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by patmill** [comment]
Hi @Rafaelki - Can you try updating your reference to be

`text: "Item number ${$index}"`

(note the extra $)

**Comment by Rafaelki** [comment]
@patmill thanks, that's work both on desktop and mobile teams app
