### ISSUE TITLE
Sharepoint 2019

### ISSUE THREAD

**Issue by mpamaral72** [SharePoint/sp-dev-docs#7545]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Are there any plans to update SPFX to Sharepoint 2019? Because the latest version only covers React 15 and was way behind.

**Comment by VesaJuvonen** [comment]
Platform team would love to do this, but unfortunately the supported SPFx version for SP2019 cannot be updated, unless all 1st party and oob UX would be updated across pages, lists and more. As that's not in plans to happen, supported SPFx version cannot be unfortunately updated.
