### ISSUE TITLE
List Formatting - setValue not taking ETag into consideration all the time

### ISSUE THREAD

**Issue by michelcarlo** [SharePoint/sp-dev-docs#7546]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

N/A

### Describe the bug / error

The new list formatting capability of setting values for customRowAction works really well, however it does not seem to take the ETag of the item into consideration all the time. A few times I get a conflict message like the one below if the action is done so quick:
<img width="246" alt="conflict" src="https://user-images.githubusercontent.com/20910957/144013946-368f1be5-b720-44e8-b4fc-5fc2618885b2.PNG">

But most of the time, what happens is like on the demo below. See user on the left side (Michel) likes and unlikes items below using the custom formatting button (2 likes + 2 dislikes), then user Carlos repeat the same actions on the same items after him (Right side). For the first item, the update done by Carlos overwrites the previous data, for the remaining ones it seems the updates for the rest of the list were fetched before the update.

https://user-images.githubusercontent.com/20910957/144015526-9f015c82-0dcb-418b-866e-e1daa7605949.mp4

### Steps to reproduce

1. Create two multi-person columns named Like and Dislike
2. Create two dummy columns to add the custom buttons, so you still see the values on the Like/Dislike columns
3. Add the two json templates for each related column:
[Like.json](https://github.com/michelcarlo/List-Formatting/blob/like-dislike-unique-reaction/column-samples/multi-person-like-or-dislike-unique-reaction/Like.json)
[Dislike.json](https://github.com/michelcarlo/List-Formatting/blob/like-dislike-unique-reaction/column-samples/multi-person-like-or-dislike-unique-reaction/Dislike.json)

Add a few items to the list.

Open the list with two users side by side on two different browser windows. Do some like / unlike actions with the first user, and quickly repeat the same with the second user. In this example, two likes, two dislikes. 

The first item will have the data overwritten by the second user.

### Expected behavior

Warn the user of a saving conflict if any (E.G. comparing the item's ETAG), and do not overwrite data.

**Comment by shagra-ms** [comment]
@michelcarlo We have taken a fix to address this and fix is rolled out to all tenants.

Please reopen if this still reproduces for you. Thanks for reporting this :)
