### ISSUE TITLE
SPFx Library is always included in package

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#7547]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version : 1.13.1
- Node.js version : 14.15

### Describe the bug / error

SPFx Library is always included in webpart package.

### Steps to reproduce

follow this documentation to create SPFx Lib/SPFx Webpart => https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial

- Create SPFx Library
- Create SPFx webpart
- Launch npm install for two project
- Create link on SPFx Library (npm link)
- add SPFX library in SPFx webpart package.json
- import and use the lib in code
- create link of lib (npm link mylib)
- bundle/package

I created two project for you with bundle-analyser ^^ =>
[testSPfx_library1.13.zip](https://github.com/SharePoint/sp-dev-docs/files/7624511/testSPfx_library1.13.zip)
[testSPfx1.13.zip](https://github.com/SharePoint/sp-dev-docs/files/7624512/testSPfx1.13.zip)

### Expected behavior

If you test with the projects I uploaded, after bundled, check temp/stats directory and see the result (see screenshot).

![Capture d’écran 2021-11-30 103356](https://user-images.githubusercontent.com/582733/144021920-09a4f54b-271b-4c8e-8dd3-83831ee098f6.png)

I have tested some tips, but SPFx Library is always included in webpart package.

Can someone test? thanks.

ps : on bundle-analyser interface check "Show content of concatenated modules (inaccurate)" and zoom.

**Comment by AJIXuMuK** [comment]
Hello @PooLP - thank you for reporting this!

Did you unlink the library before packaging the web part?
When you link it for debug purposes, you're technically adding a node module to your project. That will be bundled with the web part.

You need to unlink it first, and then add `dependencies` record to load the library from the app catalog.

**Comment by PooLP** [comment]
after retest, if i'm unlink the spfx library and leave the entry in package.json (`dependencies` node), `gulp bundle --ship` stop with error :

```
Error - [tsc] src/webparts/helloWorld/components/HelloWorld.tsx(5,33): error TS2307: Cannot find module 'test-s-pfx-library-1-13' or its corresponding type declarations.
```
it's a normal behavior, because the lib is no longer referenced.

Detail of my action with unlink :

on SPFx library =>

* `npm instal`
* `gulp build`
* `npm link`

on SPFx webpart =>

* `npm install`
* `npm link test-s-pfx-library-1-13`
=> modifiy code to import/use the lib
* `npm unlink  test-s-pfx-library-1-13`
* check package.json, the spfx lib is referenced in `dependencies` node
* `gulp bundle --ship` => error

but maybe I misunderstand :sweat_smile:

**Comment by AJIXuMuK** [comment]
Hi @PooLP - sorry, my bad. As this is a symlink you don't need to unlink it. 

I've tried to repro the issue with your sample and separately created sample, but I don't see the library to be included in the bundle:
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/17036219/144439751-377b330b-1eee-4c59-8ae0-f648dea6b890.png">

My steps (for your sample, after extracting).
**Library**
```
npm i
gulp bundle --ship
gulp package-solution --ship
npm link
```

**Web part**
_REMOVE LIBRARY DEPENDENCY FROM package.json_
```
npm i
npm link test-s-pfx-library-1-13
```

_ADD LIBRARY DEPENDENCY BACK TO package.json_

```
gulp bundle --ship
gulp package-solution --ship
```

Additionally, I checked the generated js files sizes and content - they don't contain the library code.

Could you please try on a clean solution (just unzip your own sample in a new directory)?

**Comment by PooLP** [comment]
thanks, it's work.

my mistake is :
* do not run only `gulp build` on spfx library, run gulp `bundle --ship` and `gulp package-solution --ship` before `npm link`
* on spfx webpart, is important to remove library dependency before `npm install`.

it's ok, but complicated for an implementation of continous integration script on azure devops or github.

do you know why Microsoft does not set up a spfx library declaration in the config.json or package-solution.json file?

ex :
"spfxLibrary": ["spfxLibraryName"],

**Comment by AJIXuMuK** [comment]
@PooLP - technically it is still a dependency.
If you create a corporate npm repo and publish this library in there, `npm i` will work correctly.
SPFx bundler will then take care of "externalizing" it during the bundling.

You can also check some [tips](https://n8d.at/tips-and-tricks-working-with-spfx-library-components) described by Stefan Bauer.

**Comment by PooLP** [comment]
it's work perfectly with corporate repo. thanks for tip.

it would be easier for the creation of the package to specify the use of a spfx library in the configuration files, the mechanics with the npm link or the tips by Stefan Bauer are not user friendly.

i created a pull request to specify that it is necessary to make a `gulp bundle --ship` and not only a `gulp build`, it's not clear in actual documentation ;)

https://github.com/SharePoint/sp-dev-docs/pull/7560/commits/044ae6e1dd08036545ddb64435884a81d7a92194

Thanks for your availability.

**Comment by PooLP** [comment]
In the end, it works randomly.
I try to use the spfx library on another webpart, I use the same steps describe, but the library is always included in package.
i do not understand, I will abandon the use of spfx library, this not stable.
