### ISSUE TITLE
CreateSiteColumn creates duplicate entrys with different internalName

### ISSUE THREAD

**Issue by fug4zi** [SharePoint/sp-dev-docs#7549]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

When i create a SiteColumn and the SiteColumn already exists, the SiteColum will be created with an different internal name like:
"internalName1"
"internalName12"
"internalName123" and so on

### Steps to reproduce

$content = '{
	"$schema": "schema.json",
	"actions": [
		{
			"_comment": "Site Colum will be created. When the Site Column exists it will create a new entry with different interalName as specified",
			"verb": "createSiteColumn",
			"fieldType": "Boolean",
			"internalName": "Anonyme_x0020_Freigabe",
			"displayName": "Anonyme Freigabe",
			"isRequired": false
		}
	],
	"bindata": {},
	"version": 1
}'
$site_script = Add-SPOSiteScript -Title "TestAddSiteColumn" -Content $content Add-SPOSiteDesign
-Title "Test CreateSiteColumn" -WebTemplate "64"
-SiteScripts $site_script.Id `
-Description "Test CreateSiteColumn"

### Expected behavior

CreateSiteColumn must look if the Column is already exists

It must create a SiteColumn with the exact internalName as specified.

**Comment by bcameron1231** [comment]
Hi, please make sure you provide an id attribute for your site column. This will ensure the field isn't created multiple times. You can find this information in the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#json-value-10).

![image](https://user-images.githubusercontent.com/7944457/144145088-424cc586-b59f-44f5-9bc3-75e40b8ad83f.png)

**Comment by fug4zi** [comment]
Thanks @bcameron1231

Is working fine now! This "id" fixed also bug https://github.com/SharePoint/sp-dev-docs/issues/7548
