### ISSUE TITLE
deploy to sharepoint using circleCI 

### ISSUE THREAD

**Issue by prathi1** [SharePoint/sp-dev-docs#7551]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,
Is it possible to deploy to SharePoint using circleCI so that Microsoft user accounts can access the content deployed in SharePoint.

thanks

**Comment by bcameron1231** [comment]
While I have never used CircleCi, I don't see why not. SharePoint Framework Supports ALM, so as long as you can authenticate and call the REST APIs from within CircleCi, this shouldn't be an issue.


https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest

**Comment by VesaJuvonen** [comment]
There should not be any reason why it would not work given that we have APIs for ALM operations.
