### ISSUE TITLE
"Unable to retrieve Client Secret" when loading a SPFX webpart in Teams Desktop Client

### ISSUE THREAD

**Issue by arheom** [SharePoint/sp-dev-docs#7557]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

"@microsoft/sp-core-library": "1.11.0",
"@microsoft/sp-http": "1.11.0",
 "@microsoft/sp-lodash-subset": "1.11.0",
"@microsoft/sp-office-ui-fabric-core": "1.11.0",
"@microsoft/sp-webpart-base": "1.11.0",

### Describe the bug / error

We developed few webparts, part of one of our products, and we have issues when loading them in some tenants in the Teams Desktop client. They work well on all tenants when loading in teams web, but in some tenants we get the following issue when loading them from the Teams Client app:

<tenant>/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27https://graph.microsoft.com%27&clientId=<clientId>

{
  "odata.error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": {
      "lang": "en-US",
      "value": "Unable to retrieve Client Secret"
    }
  }
}

Already checked the API management page, the SharePoint Online Client Extensibility Web Application Principal  app registration manifest and all seems to be fine, according to the related issues I found here when calling the AcquireOBOToken.

I will open also a ticket for one tenant, but was thinking might help others when having the same issue if will open here as well.

### Steps to reproduce

1. Start Teams Client
2. Open the teams app which render the SPFx web parts
3. Open the webparts with the issue
4. In Fiddler I am getting the above error.

### Expected behavior

Teams Desktop Client to load for all tenants the SPFx web parts as in the web client.

**Comment by patmill** [comment]
What does your app manifest / target for the app iFrame look like ?

**Comment by arheom** [comment]
Well, the manifest has the following settings for one app:
"requiresCustomScript": false,
  "supportsFullBleed": true,
  "supportedHosts": [
    "SharePointFullPage",
    "SharePointWebPart",
    "TeamsTab",
    "TeamsPersonalApp"
  ],

But, we have same issue with others as well with similar hosts. Not sure if I can export the exact teams app manifest deployed on a tenant (I dont know of any command), because I think it was generated when synced to teams.

The iframe loading the component has the src /_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=componentid%26forceLocale=en-gb

**Comment by patmill** [comment]
OK, the iFrame URL looks correct.  Can you check the network tab and see if there are errors there?

**Comment by arheom** [comment]
In the network tab, we only see this exception (Status Code: 403 Forbidden):
`{"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Unable to retrieve Client Secret"}}}`
which I already mentioned above. In the console, there are some followup issues, because of this original one.

Sometimes, when I open the devtools fast enough, I have seen this issue: 
![image](https://user-images.githubusercontent.com/11379520/145207096-7689db92-5c04-4808-ba98-23afe37ac276.png)
but I am unsure how I can refresh the app in teams and keep the devtools open in same time to track everything, so maybe I can see something in the network tab before.

**Comment by patmill** [comment]
Sorry for the delay @arheom .  Can you run the sync-to-teams flow again and see if that solves the issue?
