### ISSUE TITLE
Default SPFx v1.13.1 project recommends unnecessary & deprecated VSCode extension

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#7558]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.13.1
- Node.js v14

### Describe the bug / error

The default project created by the SPFx v1.13.1 (_and most older versions_) generator includes a recommendation, via the **./.vscode/extensions.json**, to install the [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome):

```json
{
  "recommendations": [
    "msjsdiag.debugger-for-chrome"
  ]
}
```

If the extension isn't installed, VS Code prompts you to install it:

![image](https://user-images.githubusercontent.com/2068657/144492077-f61759a1-125d-45c0-a482-113ed06c0b79.png)

But this extension is now deprecated and it's not recommended by Microsoft to install it, as specified in the extension's README & [page on the VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome):

> This extension has been deprecated as Visual Studio Code now has a bundled JavaScript Debugger that covers the same functionality. It is a debugger that debugs Node.js, Chrome, Edge, WebView2, VS Code extensions, and more. You can safely un-install this extension and you will still be able to have the functionality you need.

While this isn't a blocker or a bug, would be nice to get this extension suggestion removed from future generator releases.

### Steps to reproduce

1. ensure sure the extension isn't installed in VSCode
1. VSCode isn't running
1. create new SPFx project (pick anything for all questions)
1. open project in VSCode
1. observe above notification

### Expected behavior

New projects don't recommend installing deprecated/unnecessary extensions.

**Comment by AJIXuMuK** [comment]
1.14.0-beta.5 that contains the fix is out.
