### ISSUE TITLE
tslint warnings become error in ubuntu20(WSL) when gulp build

### ISSUE THREAD

**Issue by justin0522** [SharePoint/sp-dev-docs#7559]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version: 1.13.0
- Node.js version: 14.18.2
- npm version: 6.14.15
- gulp version: 4.0.2
- tslint version: 5.20.1
- ubuntu: 20.04 (WSL)

### Describe the bug / error

when run gulp build, warnings message in windows become error message as the following:

{
"endPosition": {
"character": 1,
"line": 3,
"position": 80
},
"failure": "Missing semicolon",
"fix": {
"innerStart": 80,
"innerLength": 0,
"innerText": ";"
},
"name": "/mas/src/common/EnvironmentInfo.ts",
"ruleName": "semicolon",
"ruleSeverity": "ERROR",
"startPosition": {
"character": 1,
"line": 3,
"position": 80
}
},

### Steps to reproduce

1. clone the code 
2. run gulp build

i try to fix this issue by changing the tslint.json 
- add  "defaultSeverity": "warning"
- add  "defaultSeverity": "off"
refer to this docs
https://palantir.github.io/tslint/usage/configuration/

doesn't work for me

### Expected behavior

gulp build finish without error

**Comment by patmill** [comment]
Are you running a ship build?

at any rate, you should be able to get this going by either
1 - Fix your error and put a semi-colon on the line
2 - Update your tslint.json file and remove the check

Personally, the default set of tstlint checks are pretty minimal and make for cleaner code.  I'd fix the error.

**Comment by justin0522** [comment]
I am a person in charge of CI/CD, I have told the developer to fix these issues.
For now, i just want to build a dev package. So I run the gulp bundle without ship.
Why the same tslint.json have different build result ?

**Comment by wictorwilen** [comment]
TSLint has had several issues related to warning/error differences in Windows vs Linux/MacOs. However, TSLint has been deprecated since 2019, so your only chance is to fix the errors.

**Comment by patmill** [comment]
The tooling team is looking into the next linting integration.  For now, you can fix the errors, or remove the checks.
