### ISSUE TITLE
Documentation page ysod and not redirecting

### ISSUE THREAD

**Issue by colejoseph** [SharePoint/sp-dev-docs#756]
General development documentation that should be found here: https://dev.office.com/sharepoint/docs/general-development/basic-uri-structure-and-path

Currently not found page and also not redirecting to mycustompage.htm

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Custom error page to be displayed if the view **basic-uri-structure-and-path** is unavailable

#### Observed Behavior
YSOD and looks like defaultRedirect not set up

#### Steps to Reproduce
Visit https://dev.office.com/sharepoint/docs/general-development/basic-uri-structure-and-pat

**Comment by VesaJuvonen** [comment]
Hi Cole, your first link works without any issues, but the second link is missing 'h'. So - documentation is found under the https://dev.office.com/sharepoint/docs/general-development/basic-uri-structure-and-path link. If there's, however, existing link somewhere pointing to link without 'h' in the end, we can absolutely fix it, if you can share the location. Not 100% if I got the issue right, but mentioned link works without any issues, so closing at least for now.

**Comment by colejoseph** [comment]
Seems to be fixed now. Thanks.
