### ISSUE TITLE
I need to build ace cards, so I installed spfx 1.13, but when I run yo generator, it keeps showing v1.12 

### ISSUE THREAD

**Issue by aaronzyAlpha** [SharePoint/sp-dev-docs#7562]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser: Edge
- SPFx version: v1.13.1
- Node.js version: v14.18.0
- npm version: 6.14.8

### Issue description

I want to build ace cards for viva connections, so I installed spfx v1.13.1, but whenever I run yo @microsoft/sharepoint, I see the client side generator is v1.12.1 and adaptive cards client side solution is not available on v1.12.1

![image](https://user-images.githubusercontent.com/45278392/144727605-ed8bdc54-a6bf-44f0-ab61-471d91eef3c5.png)

**Comment by aaronzyAlpha** [comment]
@andrewconnell please any help on this

**Comment by AJIXuMuK** [comment]
@aaronzyAlpha - could you please few things?
1. Do you use nvm or nvs? 
2. Could you check that you don't have local generator installed in the folder where you're trying to generate the solution?

**Comment by aaronzyAlpha** [comment]
Thanks for responding @AJIXuMuK 
1. Yes, I use nvm 
2. pardon me please, how can I check for this?

**Comment by AJIXuMuK** [comment]
@aaronzyAlpha do `npm ls` without -g parameter. 
Also, just try to uninstall and install the generator again.

**Comment by aaronzyAlpha** [comment]
Alright, I'll un & reinstall again, I'll let you know how it goes

**Comment by aaronzyAlpha** [comment]
@AJIXuMuK Same thing, now I try to uninstall the generator. 

See image below

![image](https://user-images.githubusercontent.com/45278392/145265383-cab54e30-a60b-4c41-a54d-4c14fe0d1ed2.png)

**Comment by aaronzyAlpha** [comment]
@AJIXuMuK However, When I go into the nodejs folder and run the generator, It will display 1.13.1, see image below

![image](https://user-images.githubusercontent.com/45278392/145269908-32ef944d-d9f6-4adb-8331-65977d2f329b.png)

**Comment by VesaJuvonen** [comment]
@aaronzyAlpha - this would imply that you have actually locally installed 1.12.1 to the root folder of the c disk... you confirm the assumption by checking if there's node_modules folder at c:\node_modules. This could have been accidental install at some point without the global switch. Can you check and confirm this status?

**Comment by aaronzyAlpha** [comment]
> @aaronzyAlpha - this would imply that you have actually locally installed 1.12.1 to the root folder of the c disk... you confirm the assumption by checking if there's node_modules folder at c:\node_modules. This could have been accidental install at some point without the global switch. Can you check and confirm this status?

@VesaJuvonen Thanks a lot Vesa helping out, and thanks a lot for your contribution in the spfx community! I wanna be like you when I grow up :D
I've checked my C: root, and I saw the node_modules folder there, [see screenshot below]. So, do i just delete the folder? or how do I go about it?

![image](https://user-images.githubusercontent.com/45278392/148927776-3ac9e03c-1f5d-4ef7-8b67-7cd674f9d0c2.png)

**Comment by AJIXuMuK** [comment]
@aaronzyAlpha - definitely delete `node_modules` in the root.

And I would not recommend running `yo @microsoft/sharepoint` in the root folder of the drive. If you do that and open the project in VS Code (or any other IDE) it will show you the whole C:\ structure as a part of the project.
And I assume there might be other issues too.
