### ISSUE TITLE
List Formatting - setValue in number fields using Division operator brings wrong results when the decimal separator in the language is a comma (E.G. : PT-BR)

### ISSUE THREAD

**Issue by michelcarlo** [SharePoint/sp-dev-docs#7563]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

List Formatting
Google Chrome 96.0.4664.45 - Tested in both English version and Brazilian Portuguese Version

### Describe the bug / error

When using the setValue operator on number fields and a division, we are getting wrong results when the SharePoint site locale is set up to a region where the decimal separator is a comma and not a dot. Checked with a community member that uses an Italian site and also did the tests myself in a site where the region is set up to be Brazilian Portuguese.
Tested this site in browsers where the default language is English and Brazilian Portuguese.

The results are messed up when the division output results in a number with decimal values as in the screenshot below. For integer results (column result), it is working fine. 
<img width="402" alt="Division Error" src="https://user-images.githubusercontent.com/20910957/144740288-2e3ef8ca-79a9-4096-a57c-2fde8060a78f.PNG">

Note also the last column where I am bringing the value calculated in real-time, the result is correct but the decimal separator is not adjusted to the site language ('Result-Calculated' column). Might this be the root cause of the issue? List formatting not getting the correct separator? 

### Steps to reproduce

1. Create a SharePoint site with default region/language settings to be Brazilian Portuguese
2. Create a SharePoint list with 4 number columns: Dividend, Divisor, Result,Result-Calculated
3. Apply the following JSON format to the title field:
`{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
    "elmType": "button",
    "customRowAction": {
      "action": "setValue",
      "actionInput": {
        "Result": "=[$Dividend]/[$Divisor]"
      }
    },
    "attributes": {
      "class": "ms-fontColor-themePrimary ms-fontColor-themeDarker--hover"
    },
    "style": {
      "border": "none",
      "background-color": "transparent",
      "cursor": "pointer"
    },
    "children": [
      {
        "elmType": "span",
        "attributes": {
          "iconName": "SkypeCircleCheck"
        },
        "style": {
          "padding-right": "6px"
        }
      },
      {
        "elmType": "span",
        "txtContent": "Divide!"
      }
    ]
  }`

4. Apply the following JSON to the Result-CalculatedField
`{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
    "elmType": "div",
    "style": {
      "box-sizing": "border-box",
      "padding": "0 2px"
    },
    "children": [
      {
        "elmType": "span",
        "style": {
          "line-height": "16px",
          "height": "14px"
        },
        "attributes": {
          "iconName": "",
          "class": ""
        }
      },
      {
        "elmType": "span",
        "style": {
          "overflow": "hidden",
          "text-overflow": "ellipsis",
          "padding": "0 3px"
        },
        "txtContent": "=[$Dividend]/[$Divisor]",
        "attributes": {
          "class": "sp-field-fontSizeSmall sp-css-color-LightGrayFont"
        }
      }
    ]
  }`

5. Add a few items to the list with the Dividend and Divisor values where the division result should return numbers with decimal values. Click the Divide button added on the title column on each of these items to run the set value action that brings the wrong results.

### Expected behavior

setValue action to write the correct number values on the columns.

**Comment by shagra-ms** [comment]
Thanks for reporting this. We will look into this.

**Comment by shagra-ms** [comment]
@michelcarlo Thanks for reporting this.

`setValue` now takes care of the current culture. Please do try it out and let us know if this still doesn't work for you.
