### ISSUE TITLE
Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.'. Error information is 'Extension failed to load for componentId .'.

### ISSUE THREAD

**Issue by pagetangalin** [SharePoint/sp-dev-docs#7564]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Version 96.0.4664.55
- SPFx version - 1.11.0
- Node.js version - 10.24.1

### Describe the bug / error

I am having an error in my project when deploying it in my tenant but this works while im on gulp serve.

I created a simple extension that would be rendered in the spTopPlaceholder of the page. i followed the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension) to create one. it's rendering and working locally while serving it but when i try to deploy it i get this error: 

`Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.75e06db2-212d-41f4-ad01-758e014c7b40'. Error information is 'Extension failed to load for componentId "75e06db2-212d-41f4-ad01-758e014c7b40".'.`

This i my code that inserts elements into the Placeholder element.

`if (!this._topPlaceholder) {
      this._topPlaceholder = this.context.placeholderProvider.tryCreateContent(
        PlaceholderName.Top,
        { onDispose: this._onDispose }
      );
  
      // The extension should not assume that the expected placeholder is available.
      if (!this._topPlaceholder) {
        console.error("The expected placeholder (Top) was not found.");
        return;
      }
  
      if (this.properties) {
        let topString: string = this.properties.Top;
        if (!topString) {
          topString = "(Top property was not defined.)";
        }
  
        if (this._topPlaceholder.domElement) {
          this._topPlaceholder.domElement.innerHTML = `
         code goes here`;
        }
      }
    }`

### Steps to reproduce

1.   create a sharepoint app customizer via the yeoman generator
2. deploy and install in a tenant 

### Expected behavior

extension should be rendered in the site where i deployed the application

**Comment by AJIXuMuK** [comment]
Hello @pagetangalin - could you please share your project so we could try to repro it?
Also 
- are you doing production deployment or debug (`gulp bundle --ship; gulp package-solution --ship`)?
- are you using tenant app catalog or site collection app catalog?

Also - is there any specific reason why you're on version 1.11 and not on the latest 1.13.1?

**Comment by paigeflourin** [comment]
hi @AJIXuMuK ,

- im doing gulp bundle --ship and gulp package-solution --ship
- when i tried to upgrade he spfx to 1.13.1, had some issues with my node sinc emy node is on 10.24.1 i tried to upgrade my node then gulp complained on "primordials" error. so stuck with 1.11.0 instead.

unfortunately this is a client project I cannot share the exact project that im doing, but i duplicated the project into my personal git and removed the confidentials files: https://github.com/paigeflourin/pocSP-Ext.git

**Comment by AJIXuMuK** [comment]
Hi @paigeflourin - after digging into code I see you're using `@microsoft/sp-http` module.
This module should be explicitly installed with `npm i --save @microsoft/sp-http` or `yarn add @microsoft/sp-http`. Don't forget to use appropriate version of the module (1.11.0 in your case).

The issue will be resolved as soon as you install the module.

**Comment by pagetangalin** [comment]
@AJIXuMuK  thanks so much yep that did the trick. i didn't know sp-http should be explicitly installed

**Comment by pagetangalin** [comment]
@AJIXuMuK  but i've noticed that it doesnt show up , (same error) for sitepages. for other pages (i.e site contents,s ite settings) it shows up.

**Comment by pagetangalin** [comment]
@AJIXuMuK i think it intermittently happens. I have updated my component to remove the Footer (Bottom placeholder) , deployed it then got this error again. i have already installed the sp-http. and checked the dependencies from package.json if they have been installed. and they were. 


![image](https://user-images.githubusercontent.com/76987229/146383324-5e5cd7eb-5709-433a-8211-2f4ee4c3b9eb.png)

**Comment by AJIXuMuK** [comment]
Hi @paigeflourin - please, check your other dependencies.
I was playing with the example you've shared, and the only issue there was sp-http module.
As soon as I installed it the application customizer worked on any type of page without issues.

But in your actual solution you also have some custom modules references:
```
"search-connector-ui": "taigers/search-connector-ui#IS-2460-implement-uaa-changes-for-omnitive-integration",
    "search-ner-ui": "taigers/search-ner-ui#master",
    "taiger-design-system": "taigers/design-system#develop"
```

so please, double-check these modules are bundled correctly.
