### ISSUE TITLE
About knockout.js option

### ISSUE THREAD

**Issue by bigsnowballhehe** [SharePoint/sp-dev-docs#7566]
[Enter feedback here]
there is no  knockout.js  could be select. just  no-framewrok or react.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b19eb96-192d-2d8b-8d4e-0de787f22093
* Version Independent ID: e2cbd2b2-8bb7-a95f-0768-15f1b045b4c4
* Content: [Use @pnp/sp (PnPJS) library with SharePoint Framework web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts#feedback)
* Content Source: [docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Thank you. Knockout support in scaffolding was removed in SPFx 1.11.

We should either update this post to not use Knockout, or specify a specific version for this post all together.

**Comment by VesaJuvonen** [comment]
Thanks @bigsnowballhehe and @bcameron1231 - we have removed now the doc from the table of content and will work on updated article sooner or later for this. In general article was not quite up to date, so thanks for pointing this out. Article as such was not removed as we are looking into update the same URL - for not breaking any existing references... when the new article is available.
