### ISSUE TITLE
Unnecessary "$" sign in the default SPFx 1.14 template

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/sp-dev-docs#7573]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version - `1.14.0-beta.4`
- Node.js version - `14.x`

### Describe the bug / error

The below picture describes the bug:

![image](https://user-images.githubusercontent.com/10658276/145392848-7f346b0f-70fd-4ddf-b51e-855bcbc95c84.png)

The default React template for `SPFx@1.14.0-beta.4` renders an unnecessary `$` sign. 

### Steps to reproduce

1. Scaffold a new React based webpart using  `SPFx@1.14.0-beta.4` 
2. `gulp serve`
3. Add the web part to a page and check out the extra `$` sign.

### Expected behavior

No extra `$` signs in the default React-based templates.

**Comment by AJIXuMuK** [comment]
Thank you @s-KaiNet - it has been fixed internally but didn't make it in this beta.
It will be shipped with the next update.

**Comment by AJIXuMuK** [comment]
1.14.0-beta.5 that contains the fix is out.
