### ISSUE TITLE
I've also encountered this problem + found a solution that worked for me:

### ISSUE THREAD

**Issue by jsabety** [SharePoint/sp-dev-docs#7575]
I've also encountered this problem + found a solution that worked for me:
> I am also experiencing this issue. Any update would be great. When I first created the solution, I was able to add the new webpart to a modern page. I made some changes, updated the package in the AppCatalog and tried adding to a new site I was working on and now it won't show up at all.
> 
> It does **NOT** appear when I go to "_api/web/GetClientSideWebParts" on the site I am working on.
> It does appear when I go to "/Lists/ComponentManifests/Allitems.aspx".

My solution (for an SPFx solution NOT deployed to the entire tenant in one go):
Step 1: (preferrably) remove the apps on the site collections where you installed them. Do it like this: from site contents, remove. As a site collection admin (or global admin), go to the recycle bin. There is an error indeed when attempting to remove it there. However, change the url: _layouts/15/RecycleBin.aspx to _layouts/15/AdminRecycleBin.aspx. There, remove the app. Also, go to the second stage recycle bin (_layouts/15/AdminRecycleBin.aspx?View=2) and remove it there. Now the app is completely removed from your site collection.

Step 2: remove the spfx app from the app catalog. Repeat the steps with the admin recycle bin to make sure this item is completely gone from the app catalog site collection.

Step 3: re-add your spfx package to the app catalog. I did not have to alter any ids to get it to work.

Step 4: re-add your app to the site collection where you want to add your web part.

Step 5: find your web part in the toolbox ! You can now also check the following endpoints to see your web part listed:
_api/web/GetClientSideWebParts
/Lists/ComponentManifests/Allitems.aspx

_Originally posted by @PieterHeemeryck in https://github.com/SharePoint/sp-dev-docs/issues/775#issuecomment-495615831_

**Comment by jsabety** [comment]
It is now 2021 and using the latest SPFX release with React and TailwindCSS, I have the same issue and hours of lost time trying to figure out why a solution that works perfectly on the hosted workbench fails repeatedly in a site collection app catalogue. It is not logical to have to delete things from the recycled bin, add description text etc and so on to get something to work. If you know these things are required in advance why put the onus on developers to go through umpteen steps, create support headaches and so on when it could be easily fixed at the source? We should be guaranteed that if a spfx solution is working on the hosted workbench it should work in production. And if not, at least provide some kind of easily accessible logging/developer tool that will tell us why something failed. I develop NextJS apps hosted on Vercel and it can happen from time to time that a local deployment works fine but on production some packages have issues due to the hosting environment. Vercel provides a nice log to show exactly where things have gone wrong. Unless I am unaware that such easy logging exists somewhere.

**Comment by AJIXuMuK** [comment]
Hi @jsabety - from you description it's not quite clear what exactly doesn't work for you.
The issue you're referencing has a long thread and history.
To your point with `description` - as mentioned in the issue, you will have a build time error if you remove it from the manifest.

If you had a webpart in the solution and then added an extension to it - you could have problems. But they should be fixed in SPFx 1.14.

If you have any other issues - please provide some details and clarification.
Thanks!
