### ISSUE TITLE
sp-field-severity - Incorrect Colours - SharePoint List

### ISSUE THREAD

**Issue by CoreyHunsberger** [SharePoint/sp-dev-docs#7576]
sp-field-severity-severeWarning & sp-field-severity-blocked appear to be using the same colour.

Left, SharePoint List, Right, Microsoft Documentation:
![image](https://user-images.githubusercontent.com/52454184/145492426-20909578-eba6-44a2-ac0a-028a1ed7e903.png)

Instant eyedropper shows the two colours as both being #FDE7E9.

severeWarning in the Microsoft Documentation shows as #FBD9CC and blocked shows as #FCAFD3

I am using Chromium Edge.

See post here: https://docs.microsoft.com/en-us/answers/questions/263642/column-formatting-not-working-correctly-sp-field-s.html?childToView=658271#answer-658271

**Comment by bcameron1231** [comment]
I'm having trouble reproducing the issue. These values can change depending on the theme applied to the site as well. Do you have a custom theme applied to your environment?

**Comment by CoreyHunsberger** [comment]
Everything on the list shows as the default sharepoint teal, but the theme does show the 'current selection' as just being black with black letters on a white background. (System admins do have a custom black bar along the very top with the company logo).

Changing the look to any of the default sharepoint themes does change the colours for the buttons, border lines, etc. But the two fields still show as the same colour for all of them. The bar at the very top with the company logo does not change (which I believe it is not supposed to).

The logic is correct with the formatting, as changing '--severeWarning' to '--warning' results in the expected yellow. Same with changing '--blocked'

This is the same in Chrome, Edge, & Internet Explorer. They are also the same colour when viewing from the Lists app in Teams.

I am applying these fields through additionalRowClass, the logic determines which field severity to use and the other properties are added on. So below is exactly what should be sent for formatting after logic (for the cancelled row):


{

  "$schema": https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json,

  "additionalRowClass": "sp-field-severity--severeWarning sp-field-fontSizeSmall sp-css-color-LightGrayFont ms-borderColor-themeDark"

}


Using only the above and removing the logic results in all rows being the '--blocked' colour, as expected.

I am formatting the entire row through the advanced designer in the "Format this view" option. I have not tested to see if the colours render differently when formatting only the column, I will have to try that on Monday.


Thank you,
Corey


________________________________

**Comment by shagra-ms** [comment]
I have a local repro. Looking into this.

**Comment by betrue-final-final** [comment]
These colors should have two versions, one for the dark themes and one for the rest, but for both, "Blocked" and "Severe warning have different colors. Here they are for light themes in the Fluent design file. Both seem to be using the hex values for "Blocked" in the bug.
![image](https://user-images.githubusercontent.com/20363037/175572037-34fa4983-f2b5-4d05-bb96-b1cef1666d1f.png)

**Comment by shagra-ms** [comment]
We have taken a fix to address this. Please do try it out @CoreyHunsberger .

Thanks @betrue-final-final for guidance. 🍻

**Comment by shagra-ms** [comment]
@CoreyHunsberger I have resolved this issue. Please reopen if this still persists for you.
