### ISSUE TITLE
PropertyPaneToggle "checked" option is being ignored

### ISSUE THREAD

**Issue by acksoft** [SharePoint/sp-dev-docs#758]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When "checked" option for a PropertyPaneToggle control is set to true, the control created in the property panel should be in and display in its "On" state.

#### Observed Behavior
When I add a toggle control to my property pane configuration, I set it's properties as directed:

`
PropertyPaneToggle('myTestToggle', {
                  checked: true,
                  label: "My Test Toggle",
                  key: "myTestToggle",
                  onText: "Toggle is On",
                  offText:"Toggle is Off"
                })`

But when I run the web part in the local workbench, this is the result:

![toggleoff](https://user-images.githubusercontent.com/13240477/28848451-cecf3d48-76c7-11e7-9935-c8ddc0e288c2.JPG)

#### Steps to Reproduce

1. Create a new web part with the yeoman generator
2. Add a toggle to the web part properties, and set the "checked" option of the toggle to true.
3. Test in the SharePoint Workbench

**Comment by srideshpande** [comment]
@acksoft - Thanks for raising the concern. I will take a look at it and keep you posted.

**Comment by srideshpande** [comment]
@acksoft - This issue is now resolved and will be available to you in the next release. I am closing this issue now, but feel free to re open it if you see this issue in the next release.

Thanks,
Srikanth
