### ISSUE TITLE
Role of update and get in custom Property Pane controls

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#7580]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

What is the point of `update` and `get` in the SharePoint Framework?
`import { update, get } from '@microsoft/sp-lodash-subset';`

The [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/build-custom-property-pane-controls) says that they "are required to work with Web Part properties". What is the difference with simply using the `this.properties` object?

Instead of `get`: 
`this.properties["PropertyName"]`

Instead of `update`:
`this.properties["PropertyName"] = newValue`

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @PathToSharePoint,
`update` and `get` allow you to work with nested properties.
For example, you want to get or set the property with path `list.title`. Your approach won't work, but the one with `update` and `get` - will.
