### ISSUE TITLE
SPFx navigatedEvent breaks with Site Navigation link to another site

### ISSUE THREAD

**Issue by sambetts** [SharePoint/sp-dev-docs#7583]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Edge 96.0.1054.53 + Chrome 96.0.4664.93 
- SPFx 1.13.1
- Node.js v14.17.3
- etc

### Describe the bug / error

If a different site is navigated to from the site nav menu, any app customizer loses it's context on page-nav to the new site. Amongst other things, navigatedEvent is no longer fired & the context remains null & unusable. 

This only occurs when the navigation to the other site is a "light" nav (client-side). 

The app customizer remains loaded & URL changes can be detected with a MutationObserver for example:

```
    // Watch manually for URL changes
    new MutationObserver(() => {
      const url = location.href;
      if (url !== this.lastUrl) {
        this.onUrlChange();
      }
    }).observe(document, { subtree: true, childList: true });
```

But the context is always null in the new site so you can't do anything. Assuming the extension is installed in the new site, a full F5 reload initialises the extension correctly again. 

I don't know if this is a design limitation due to passing outside the original site or a bug, but certainly there are no events or hooks I'm aware of to capture this eventuality except some kind of manual check:

```
  private onUrlChange() {
    // Wait a few seconds after URL change to see if normal SPFx event has fired
    setTimeout(async () => {

      // Hack: reload window to get a new context. No other way.
      if (this.lastUrl !== location.href) {
        console.warn('URL changed without SPFx event firing. Forcing full reload.', location.href);
        window.location.reload();
      }
    }, 3000);
  }
```

### Steps to reproduce

Create new communications site (or use existing).
Edit site nav links at the top of the page & insert a link to another site, with relative URL ("/sites/Site2" for example). Save.

Create new app customizer:
yo @microsoft/sharepoint
* SharePoint Online only (latest)
* Application Customizer

Code:

```
  private lastUrl: string = location.href;

  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    // Wire-up page-changed SPFx event
    this.context.application.navigatedEvent.add(this, this.logNavigatedEvent);

    // Watch manually for URL changes
    new MutationObserver(() => {
      const url = location.href;
      if (url !== this.lastUrl) {
        this.onUrlChange();
      }
    }).observe(document, { subtree: true, childList: true });

    return Promise.resolve();
  }

  private onUrlChange() {

    // Wait a few seconds after URL change to see if normal SPFx event has fired
    setTimeout(async () => {

      // Check to see if our normal event fires.
      if (this.lastUrl !== location.href) {
        Log.warn(LOG_SOURCE, 'NavBugApplicationCustomizer: URL changed without SPFx event firing. Huh.');
      }
    }, 3000);
  }
  private logNavigatedEvent(args: SPEventArgs) {
    Log.info(LOG_SOURCE, "logNavigatedEvent(): " + window.location.href);
  }
```

Build & package:
gulp bundle --ship
gulp package-solution --ship

Deploy to your comms site + other site the link points to. Once confirmed you see the 'logNavigatedEvent' in the console out in your comms site, click on your link created above to navigate to the other site.

### Expected behavior

If the extension is valid in the target site, I expect it to continue to work without needing to hard-refresh the page.

**Comment by AJIXuMuK** [comment]
Hello @sambetts - thank you for reporting this issue.

I've tried to repro it, but it's working correctly on my end.

For the test I've created 2 communication sites and links as described in the repro steps.
And I've tested the application customizer in 2 scenarios: tenant-wide deployment and site collection deployment (the same application customizer was added to both comm sites).

For the first scenario (tenant-wide) I see the navigated event fired and correct context.
For the second scenario the customizer is disposed and initialized each time I navigate (which makes sense as these are technically 2 different apps).

Here is the customizers I was using for tests.
[ac-nav.zip](https://github.com/SharePoint/sp-dev-docs/files/7706190/ac-nav.zip)

Could you please check it on your tenant?

Additional idea I have - you could have the second scenario in your tests, but didn't handle `onDispose` to remove event handler.
In that case you could have a memory leak, and an event that is handled by disposed application customizer (with disposed context).

**Comment by sambetts** [comment]
Hi Alex,

Thanks for getting back to me. So after digging some more, it turns out we're both right & wrong...

I noticed I was seeing "logNavigatedEvent" on the new site too, but weirdly also the same code complaining the URL wasn't updated. It turns out that for a light-navigation the SPFx extension is loaded twice, which we can see by inserting a random Guid into the outputs:

`  private randomId : Guid = Guid.newGuid();
`

...and then, our console statements:

`    console.info(this.randomId + "NavBugApplicationCustomizer: logNavigatedEvent(): " + location.href);
`

The result of this is something like this:

Move on the same site - all good:

```
ede82192-7aa5-4fc2-af75-12ed9eaef456 NavBugApplicationCustomizer: logNavigatedEvent(): https://m365x352268.sharepoint.com/sites/NavBug/SitePages/Forms/ByAuthor.aspx
ede82192-7aa5-4fc2-af75-12ed9eaef456 NavBugApplicationCustomizer: logNavigatedEvent(): https://m365x352268.sharepoint.com/sites/NavBug
```

Move to another site, and it gets interesting:
```
**fe714ce-f050-402d-b535-6d6d88c2af09** NavBugApplicationCustomizer: logNavigatedEvent(): https://m365x352268.sharepoint.com/sites/SPOInsightsModern
ede82192-7aa5-4fc2-af75-12ed9eaef456 NavBugApplicationCustomizer: URL changed without SPFx event firing. Huh.
```

So I guess it would make sense the app effectively loads again (and in fact does work), but the old app hangs around in a broken state it would seem.

**Comment by sambetts** [comment]
Yep, can confirm adding onDispose doesn't seem to affect the behaviour at all.

**Comment by AJIXuMuK** [comment]
@sambetts - could you please send me your sample and describe how exactly you install the application customizers on the sites: is it tenant-wide deployment, or Add an app on each site?
If you try the sample I've provided - does it work?

**Comment by jhholm** [comment]
I am actually running in to the same issue with SPFX 1.13.1. I think I had this same issue a few years back and just circumvented the issue by checking that is it an actual real navigation event or not (keeping a singleton variable that has the last page url from pagecontext).

In my test case I create 3 communication sites (e.g. testsite_0. testsite_1, testsite_2). Next I set the first site to be a hub site, and assign the two other sites under that hub. Then I create links in the hub navigation for all three sites and additionally a link to a news page within the first site. Thus my hub navigation has four links.

After that I create an application customizer that tracks navigation similarly via **this.context.application.navigatedEvent.add** event. The application customizer is not tenant wide deployed, and is activated manually on sites 0 and 1. The last site doesn't have the customizer activated.

Then for tracking the navigation I'm using the [Service locator pattern](https://docs.microsoft.com/en-us/javascript/api/sp-core-library/servicescope). After each navigatedEvent trigger I call my custom service that uses the pagecontext services legacypagecontext objects serverRequestPath variable and compare it to the last time the event was fired in the instance property. I also save the navigated path to a singleton variable within my service class just to be sure.

**My observations:**

1. The navigatedEvent is triggered only once when you load a page for the first time
2. The navigatedEvent is triggered only once when you navigate to a page within the same Site Collection
3. The navigatedEvent is triggered twice after navigating to another Site Collection where the application customizer is activated
4. If you're navigating to Site Collection that doesn't have the application customizer activated, you're not getting no navigatedEvent triggered at all
5. When navigating to a site that doesn't have the application customizer activated and navigating back to a site that has it, the navigatedEvent will trigger twice (you need to start navigating from a site that has it activated)
6. In the above example the service locator pattern will remember the first site url as the last navigated url
7. If you're navigating from a site that doesn't have the application customizer (and as the first page on a fresh tab) and navigate to a site that has the customizer, the navigatedEvent will trigger only once

I guess observation 6 makes sense, as I couldn't find a way to dispose the service and thus it is kept in memory until a full page reload.

I also tried **this.context.application.navigatedEvent.remove** to remove the event trigger, with no changes. I also noticed that the double triggering is done by the new instance of the application customizer, not the first one.

**Comment by jhholm** [comment]
As mentioned above, I can circumvent the issue by saving the current url in the service class and thus in the application logic not acting on the navigation if the url is the same. But there is this one extra case, if I start my navigation from site_0, then go to site_2 (that doesn't have the customizer) and navigate back to site_0, my service will think that I'm navigating from site_0 to site_0 twice (see observation 5).

**Comment by AJIXuMuK** [comment]
@jhholm  - can you share your code by any chance? or could you test the attached one to see if you see the nav event firing twice?
[ac-nav.zip](https://github.com/SharePoint/sp-dev-docs/files/7714125/ac-nav.zip)

**Comment by jhholm** [comment]
I can share mine later, but I need to clean customer specific stuff first. Though your attached one is pretty much the same, but simplified as I tried some extra hacking. Yours is also SPFx 1.14.0-beta. But all in all your solution works in similarly.

**Comment by jhholm** [comment]
Might be noteworthy, but I remember I had the same symptoms years back, but the tenant I'm currently testing is on Targeted release.

**Comment by AJIXuMuK** [comment]
@jhholm - thanks for all the details.
I can confirm the behavior you've described.
But I don't see why it's an error.
Even if the `navigatedEvent` is fired, it is fired from the correct application customizer with the correct context.

Could you please describe what exactly feels like an issue for you?

**Comment by jhholm** [comment]
I think it feels weird that it's fired twice in this situation when navigating from a site to a another site. It could make sense if the event would pass something in the **eventArgs** variable. It could make sense if I could handle the first event as "landing on a new site navigation event" and the second one as "the user is coming from this URL" navigation event. Now I just need to provide a work around on the idea that the event is fired twice and the second firing does not give any extra information really. I just don't see a usecase here for now and it just feels a bit off and quirky, but that could just be me. It would also be great if it would be possible to get an event on the application customizer when you're navigating away from the site, but I guess you can handle that on **onDispose** as the pageContext already has the new URL.

**Comment by jhholm** [comment]
And if I have the app customizer instantiated on an activated site and navigate to a site that doesn't have the customizer activated and navigate back to a site that has it activated I get the two events situation as mentioned in my observations. So in a way I see it as a quirk: "If the app customizer has already been instantiated and you're tracking navigatedEvents, you will always get two navigatedEvent triggers when changing a site and you just need to know that".

**Comment by sambetts** [comment]
For me the issue has been around tracking page hits; without extra checks I don't feel should be necessary, I'd be tracking x2 the hits just by crossing site on a partial page-load because both the old & new extension instances seem to execute.

**Comment by AJIXuMuK** [comment]
Let me check what we can do with the even firing twice.

**Comment by AJIXuMuK** [comment]
@sambetts - the fix has been done.
It will be available WW in few weeks.

**Comment by sambetts** [comment]
Awesome job; thanks all!
