### ISSUE TITLE
ClientSideComponentId and ClientSideComponentProperties are reset to default values on certain list columns

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#7584]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome: 96.0.4664.45
- SPFx version
  - 1.13.1
- Node.js version
  - 14.18.1

### Describe the bug / error

This issue seems to have started occurring tenant-wide a few hours ago.

This coincided with me making some changes to a SPFx package that I maintain, but I'm not sure if that somehow triggered this behavior, or whether that's pure coincidence, since I'm seeing the issue on sites and lists that my changes should have no effect on.

I am use the REST API to set the `ClientSideComponentId` and `ClientSideComponentProperties` values on certain list columns, to associate them with a list field customizer.

This has worked fine for more than a year, but as of today, I am seeing that these values are spontaneously going a back to their default values on two columns: those with internal name `LinkTitle` and `LinkTitleNoMenu`.

This doesn't happen immediately. The values I set seem to remain for about a minute, before resetting to their default values.

** Additional Information **

I am also observing this on columns that I haven't modified in weeks. Their `ClientSideComponentId` and `ClientSideComponentProperties` settings retained the same values all that time, but when I observe them now, without modifying them at all, they've been reset to their default values.

One possibly related issue is that if I set `ClientSideComponentId` and `ClientSideComponentProperties` on the `IssueID` column in an Issue Tracking list, the settings don't stick at all. They just stay at their default values.

### Steps to reproduce

1. Use the REST API to set the `ClientSideComponentId` and `ClientSideComponentProperties` values on the following columns in an ordinary list:
  a. Title
  b. LinkTitle
  c. LinkTitleNoMenu
2. Retrieve the columns' properties using the REST API
3. Observe that the values have been applied successfully
4. Wait about 2 minutes
5. Retrieve the columns' properties again and look at the `ClientSideComponentId` and `ClientSideComponentProperties` values again.

EXPECTED: They still have the specified values
ACTUAL: They have been reset to the defaults on the `LinkTitle` and `LinkTitleNoMenu` columns.

### Expected behavior

Columns should retain their `ClientSideComponentId` and `ClientSideComponentProperties` values after they have been set. They should not revert to default values.

**Comment by AJIXuMuK** [comment]
Hi @JLRishe - I'm unable to repro it.
I was playing with 2 different tenants for about an hour - the properties are there for `LinkTitle` and `LinkTitleNoMenu`.
Could you check it on another site collection and maybe another tenant?
Could you also try using M365 CLI or PnP PowerShell instead of REST API just to compare the behavior?

**Comment by JLRishe** [comment]
@AJIXuMuK

Thank you very much for your reply.

This seems to have gone back to normal for me over the past 24 hours. It seems like it was a temporary glitch.

I'm still finding that I'm unable to set the properties on `IssueID` columns (in Issue Tracking lists). Unlike what I saw with `LinkTitle` and `LinkTitleNoMenu`, the settings don't persist on `IssueID` columns at all, but simply aren't reflected. Is there some known limitation there?

**Comment by AJIXuMuK** [comment]
@JLRishe - yes, there are some columns you can't assign Field Customizer to. Sometimes it's not even a column limitation, but column + list type (for example, `LinkTitle` in Contacts list).

We definitely need to provide an article in the docs that describes these limitations.

**Comment by JLRishe** [comment]
@AJIXuMuK 

Ok, thank you for clarifying that. Given that this issue seems to have gone away, I'll go ahead and close this. Thank you again for your help.
