### ISSUE TITLE
SharePoint Search API result returns unexpected RowCount

### ISSUE THREAD

**Issue by wpo365** [SharePoint/sp-dev-docs#7586]
In my opinion the following is a bug related to SharePoint Search API

The following request

`https://%xyz%.sharepoint.com/_api/search/query?querytext='marco'&rowsperpage=10&rowlimit=200&clienttype='ContentSearchRegular'`

Gives a RowCount of 2 (PrimaryQueryResults > RelevantResults). However when I request results starting from row 1 (instead of 0 or with startRow ommited) with the following request

`https://%xyz%.sharepoint.com/_api/search/query?querytext='marco'&startrow=1&rowsperpage=10&rowlimit=200&clienttype='ContentSearchRegular'`

It gives me the expected RowCount of 10.

In both cases the TotalRows is the same around 24. 

Initially the first query worked fine (since 2017) and the unexpected RowCount (and thus the unexpected number of Rows in the corresponding Table) I only started noticing this week (but the issue may be older). Therefore I believe it may be related to an update by Microsoft. Curious to see if anyone else is experiencing the same thing!

PS What is odd is that for other queries with a different queryText e.g. 'sharepoint' I get immediately 10 rows of results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by wobba** [comment]
RowsPerPage is not really used. Use RowLimit and StartRow. Does that help?
