### ISSUE TITLE
[1.13.1] package-solution task changed so custom configuration doesn't work anymore - how to migrate from 1.12.1?

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#7589]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We have been developing a solution containing multiple webpart/extension solutions, which are packaged as an NPM package.
For our customers, we gather these NPM package into a single SPFx package, referencing those packages, joined together in a `yarn workspaces` project.

One of these packages contains an application customizer.

In order to include the `elements.xml  file from the NPM package in the containing solution, we made some configuration changes to the `gulp` config:
```
build.packageSolution._hasPrependedPaths = true;
build.packageSolution.taskConfig.paths.debugDir = path.join("sharepoint", "solution", "debug");
build.packageSolution.taskConfig.paths.sharepointAssetDir = ".";
```
This allows us to reference the `elements.xml` from the NPM package in `package-solution.json`:
```
"features": [
	{
		"title": "My Feature",
		"description": "Enables the client side components.",
		"id": "68c51136-4fbe-4849-afaa-8dc91989e493",
		"version": "1.1.0.0",
		"assets": {
			"elementManifests": ["../../node_modules/@dw-connect/appheader/sharepoint/assets/elements.xml"]
		}
	}
]
```

However, in SPFx 1.13.1 the `build.packageSolution` configuration part doesn't work anymore. The build tasks seem to have changed internally.

So my question: is there another way of configuring the same settings with the new build tasks in place?

**Comment by AJIXuMuK** [comment]
Hi @NickSevens,

There were some changes in the configuration and tasks.
First thing to mention, `_hasPrependedPaths` is a private field. It is not supposed to be directly reassigned.

For the `paths` configuration - why don't you use the `package-solution.json` file itself?
