### ISSUE TITLE
Share point item file ref letter case is inconsistent

### ISSUE THREAD

**Issue by whwang5566** [SharePoint/sp-dev-docs#7590]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

use share point RESTful API
https://xxx.sharepoint.com/sites/xxx/_api/Web/Lists(guid'{list_id}')/items({item_id})?$select=FileRef
the response FileRef letter case is inconsistent (and not correct)
ex:
FileRef = A/**b**/test.docx
but the real url is A/**B**/test.docx

It is not always happened,
or should use another API to get item url?

### Steps to reproduce

1. move folder to other sub-folder
2. check with https://xxx.sharepoint.com/sites/xxx/_api/Web/Lists(guid'{list_id}')/items({item_id})?$select=FileRef
3. the file ref letter case is inconsistent
(Steps are guess, because it is not always happen)

### Expected behavior

the response file ref for https://xxx.sharepoint.com/sites/xxx/_api/Web/Lists(guid'{list_id}')/items({item_id})?$select=FileRef should  letter case consistent

FileRef should be A/**B**/test.docx, not A/**b**/test.docx
and the real url is A/**B**/test.docx

**Comment by bcameron1231** [comment]
Hi. Sounds like a folder was changed from lowercase to uppercase after the file was already inside the folder. The FileRef property is keeping the original value.

**In any case, this isn't a big issue. URLs are not case sensitive.**

A/B/Test.docx is equivalent to A/b/Test.docx
a/b/Test.docx is equivalent to A/B/Test.docx
a/B/Test.docx is equivalent to A/b/Test.docx

The values are the same and case differences have no effect on getting access to the document.

**Comment by AJIXuMuK** [comment]
Yeah, I believe @bcameron1231 is right here.
And there is no issue in getting the file content.

@whwang5566 - is there any specific functionality (some requests, APIs) that not working with the result you get from `FileRef`?

**Comment by whwang5566** [comment]
Thanks @bcameron1231  and @AJIXuMuK !
I have noticed SharePoint is case insensitivity, but I develop an application use the FileRef for display item (file) path, so if the FileRef is not the latest value, it will display wrong path, so I want to know the right way to get latest and correct path.

Thanks for your help.

**Comment by bcameron1231** [comment]
@whwang5566 What do you mean by "wrong path". Yes, the file url has different casing, but you shouldn't have any problem accessing the files regardless of the case. I have tested this rigorously. 

Do you have an example of a url with different casing, which does not resolve the file? If so, can you share that with us, because I cannot replicate it.

**Comment by whwang5566** [comment]
@bcameron1231 , Sorry for not making it clear, "wrong path" is only mean has different casing, and I can still access the file with different casing, the problem only I want to display the FileRef, it may have different casing.

So I wonder there has any way to get same letter casing path? (always equal to real letter casing)
Thanks a lot.

**Comment by bcameron1231** [comment]
Right. Unfortunately, there is no way to change this behavior. The path is the same, and casing is irrelevant as casing is ignored. 

If you are displaying them and looking for consistency, I would just use your code to set them all to the same casing. Otherwise, there isn't anything to be done here.

**Comment by whwang5566** [comment]
@bcameron1231 Understand, Thanks for your help.
