### ISSUE TITLE
Raising the target in SPFx 1.14

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#7595]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

I am testing SPFx 1.14 beta, and I see that the target in tsconfig is still set to es5.

What is the reason for that? Now that IE is not supported anymore, can't we raise the default target? Or are there some circumstances that still require es5?

**Comment by patmill** [comment]
Yes, we need to stick with es5 for now.

**Comment by PathToSharePoint** [comment]
Thanks for the reply @patmill ! Could you elaborate on what is holding us back? I'd like to move to es6 for my Web Parts, to use more modern JavaScript that doesn't have a polyfill, and it seems to work in the tests so far. But I am concerned it might break something I am not seeing... yet.

**Comment by patmill** [comment]
Sure.  Let me leave this open for a while and update it.  I'm sort of on vacation at the moment, so it might be a little while.

**Comment by PathToSharePoint** [comment]
Let me post here my understanding after @VesaJuvonen 's reply on twitter:
_if I understand correctly, there are no limitations with the #SPFx toolchain itself, or the #Microsoft365 target apps (Outlook, Viva dashboard, etc.). Only IE11 is holding some tenants back._

**Comment by VesaJuvonen** [comment]
There are indeed no technical limitations on this in the SharePoint Framework toolchain, this limitation is coming from few exceptional tenants where IE11 is still supported. So even though officially we no longer support IE11, we are not fully off from that, so the decision was to avoid surprises with the default configuration due this.

**Comment by patmill** [comment]
Not too much to add to Vesa, except to say that while it will likely be straight forward to allow you to target ES6, the underlying framework will still be build with ES5.  Migrating the framework to ES6 will break all existing solutions, since the "compiled" code from an ES5 solution won't work against an ES6 framework.  However, an ES6 solution compiled against an ES5 framework does work.  It's on our backlog to come up with a solution that won't involve updating existing solutions, but it is not in our short term plans.
