### ISSUE TITLE
Javascript files not loading from PublicCdn

### ISSUE THREAD

**Issue by kkendapa** [SharePoint/sp-dev-docs#7597]
Hello,

We have 2 spfx webparts which were working for last 3 years but since 2 weeks the JS files won't load from the public cdn url on the page and the webpart errors out. This behavior is not consistent for all users, some don't have any issues, some have issues with one part, some have issues with other, sometimes all the webparts load for the same user and after sometime they won't. Error looks like this
SPLoaderError.loadComponentError]:

Failed to load component "e441bd14-0b49-469f-98bd-cd79eef492be" (DocumentQueryWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/xxxxxx.sharepoint.com/1756007103dcc3464b4d2c7d11fe37258a5857a5c99f740add88ebe757cee43a0d1cbd2b/solutions/property-sites-client-side-solution/1.4.4.0/propertysites-documentquerystrings_en-us_e3b51a645417a6a0867ecd1d5314b128.js'

Any insights why this happens?

**Comment by kkendapa** [comment]
Hello, commenting to check if any experts have any idea why this happens?

**Comment by patmill** [comment]
Out of curiosity, do you have this URL hard coded anywhere, or is it simply generated when you try and load the webpart?
Also, if you look at the network tab, what is the result code / error / etc. from the js load?

**Comment by kkendapa** [comment]
Hi Pat,

Thank you for the reply. I'm not developer for these webparts but I have the source code. I'm still not very good with spfx but when I went into the code and found that write-manifests.json file has the the cdn path hard coded this way.
{
  "cdnBasePath": "https://publiccdn.sharepointonline.com/xxxxx.sharepoint.com/1756007103dcc3464b4d2c7d11fe37258a5857a5c99f740add88ebe757cee43a0d1cbd2b/solutions/property-sites-client-side-solution/1.4.4.0"
}

Also in the network for the js which needs to be loaded I see this error.
{HttpStatus: "NotAcceptable",…}
ErrorCode: 406012
ErrorMessage: "Requested asset is not found or is not located in the Public CDN enabled location"
HttpStatus: "NotAcceptable"

**Comment by patmill** [comment]
OK, yes that will be a problem.  You want it to look like this:
  "cdnBasePath": ""

This will get replaced at runtime with the appropriate URL / if it is on the CDN / etc.

**Comment by patmill** [comment]
(sorry - small update above.  The 'path to CDN' wound up hidden in the markup.)

**Comment by kkendapa** [comment]
Thank you, will try that.
