### ISSUE TITLE
Search box not appearing in modern page Suite Bar in publishing site in SharePoint 2019 server

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7598]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi, 

I have created a modern page in my publishing site on SharePoint 2019 server.

I want to show the search bar the same as online sites. Please find the below images for your reference.

 Current Suite Bar design :
![image](https://user-images.githubusercontent.com/86624727/146495196-05d4ec6d-517f-44b6-a543-0551fd38523e.png)

Expected Suit Bar design:
![image](https://user-images.githubusercontent.com/86624727/146495266-52e1ebb6-227c-45e7-903b-a6f00d34e9ac.png)

Thank you in advance

**Comment by VesaJuvonen** [comment]
SharePoint Online is the latest and most up to date version of SharePoint services with weekly updates. Technically SharePoint 2019 is already three years behind of the evolution compared on the Online and is no longer even the latest on-premises version. Newest on-premises version is SharePoint Server Subscription edition which was released in 2021, but there's no changes on that related on this specific feature.

There's no way to provide matching experiences as in SharePoint Online in the SharePoint 2019 version as the features are not there.
