### ISSUE TITLE
Delete confirmation dialog does not close when deleting webpart from workbench.aspx

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#76]
When using the workfbench.aspx and there is an error loading the webpart, I delete the webpart and I am given a confirmation dialog. I choose yes, but the dialog does not close. Refresh the page and it has been deleted.

![image](https://cloud.githubusercontent.com/assets/10567535/17955478/263997aa-6a48-11e6-8cf5-53faaf53c0f9.png)

**Comment by patmill** [comment]
Thanks @SteveCurran .  This is covered under the following bug - https://github.com/SharePoint/sp-dev-docs/issues/13
