### ISSUE TITLE
Keeping Local Workbench use local packages instead of externals

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/sp-dev-docs#760]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Currently trying to get a hold of the "externals" functionnality of the SPFx and I am wondering if there is anyway to keep local packages when using the Local Workbench (so I can actually work while offline) and use the external packages (CDN) when I work using the Hosted Workbench or when the App is actually used through the App Catalog? 

Is there a way I could make any gulp command without the --ship option bundle everything (ignoring any external resource) and when I use --ship it just bundles based on the external packages, that would be lovely.

Any idea on how to make that happen ?

Thanks!

**Comment by sebastienlevert** [comment]
I've been thinking that I could use that to package based on conditionnal require. Does it make sense?

```
if (DEBUG) {
  require("zone.js");
} else {
  require("Zone");
}
```

Based on the target of the webpack build, I can target which one I want to bundle (local or the CDN-enabled version of my package). Any guidance on that?

Thanks!

**Comment by mcmynn83** [comment]
Thank you for the feedback.  This is a feature request (to allow bundling of all external dependencies).  When making a feature request please do so on http://uservoice.

**Comment by sebastienlevert** [comment]
Is that a feature request? I'm really just asking guidance on how we can load different modules based on the output type... If it's not part of the SPFx yet, then, yes, it becomes a feature request. But is there anyway to make it work that scenario in any way today? I would love to have a better local workbench development scenario and I am sure you can provide guidance on that as of today. Thanks!

**Comment by waldekmastykarz** [comment]
@sebastienlevert what if you had two config files: one with and one without externals. Using a custom gulp task setup as a dependency of the standard build task, you could rename the file that you want to use in the build process. That would allow you to keep your code as-is and only flip the config.
