### ISSUE TITLE
How to hide left navigation in modern page on publishing site on SharePoint 2019 server

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7600]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,

I want to hide the left navigation on the modern page on the publishing site on SharePoint 2019 server.

![image](https://user-images.githubusercontent.com/86624727/146520262-df796163-347c-436e-87ec-ac7545aa1d5e.png)

Thank you

**Comment by RaytheonXie-MSFT** [comment]
1.Please make sure disable "SharePoint Server Publishing Infrastructure" feature and "SharePoint Server Publishing" feature.
![image](https://user-images.githubusercontent.com/91254676/146858215-4d66fc56-dc8e-4853-aebf-30df826e5a14.png)
![image](https://user-images.githubusercontent.com/91254676/146858239-6fce1757-6c6d-4342-93d1-42cfdee4fb8d.png)
2.Navigation to Site Settings page >> click on (Look and Feel) Navigation Elements.
![image](https://user-images.githubusercontent.com/91254676/146858276-9edad146-dd93-408f-b25a-68eb6a387c98.png)
3.Un-check "Enable Quick Launch" option.
![image](https://user-images.githubusercontent.com/91254676/146858303-20dd9645-a6c4-48bb-997f-1f41093a8135.png)
4.Save.
![image](https://user-images.githubusercontent.com/91254676/146859128-aca6d8e4-9e22-4c2b-8805-3390ae981c36.png)

**Comment by VesaJuvonen** [comment]
Closing based on answer from @RaytheonXie-MSFT
