### ISSUE TITLE
The example is for SPFx version 1.1, not 1.4 (the 2019 version)

### ISSUE THREAD

**Issue by Anders-AndulfGames** [SharePoint/sp-dev-docs#7601]
Regarding the line: "If you're building SPFx v1.1 solutions, install the following specific versions of Gulp & Yeoman:". Ok, but this page is about SharePoint 2019 and SPFx version 1.4 (not 1.1). I have seen the compatibility list, but which version of Gulp and Yeoman should I use with 2019? There seems to be a lot of confusion on the web/stackoverflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae796d02-c060-77fd-6448-e1a0f6f149e1
* Version Independent ID: b85cb658-3b40-fd0c-8491-511c42a2d4b8
* Content: [SharePoint Framework development with SharePoint 2019](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support)
* Content Source: [docs/spfx/sharepoint-2019-support.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/sharepoint-2019-support.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This page has good mapping between the versions for providing the right combination - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility

For SP2019, you'd use the 1.4.1 version mapping.

**Comment by Anders-AndulfGames** [comment]
Wow, Vesa himself. Thank you for taking the time to answer my comments. I feel humbled.

You are right about the page which describes what version of Node.js and NPM we need to use with SPFx 1.4.1, but it does not answer which version of Gulp and Yeoman we must use. 

The problem is that the example of installing Gulp and Yeoman on the page is for SPFx v1.1 and not SPFx v1.4.1. Since the page is for SharePoint 2019 I think it should explain the 1.4.1 version.

**Comment by andrewconnell** [comment]
@VesaJuvonen Tend to agree with the OP... we could be a bit more clear about the specific versions of all dependencies for the on-prem scenarios better than we are today.

You cool with this? 🤷‍♂️

if so, we can label as a doc bug & assign to me.

**Comment by Anders-AndulfGames** [comment]
Thank you very much Andrew. Excellent update, and it finally works! Happy New SharePoint Year!

**Comment by andrewconnell** [comment]
![_](https://user-images.githubusercontent.com/2068657/147959755-55fc2469-29ca-4cfa-a8d8-cf6e331b7d21.gif)
