### ISSUE TITLE
MS Graph call fails from adaptive card extension when paired with Assigned Task card on initial load

### ISSUE THREAD

**Issue by cwparsons** [SharePoint/sp-dev-docs#7604]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Google Chrome v96
- SPFx v1.13.1 and v1.14.0-beta.4
- Node.js v14.15.5

### Describe the bug / error

When using the Viva Connections dashboard with the Assigned Tasks and a custom adaptive card extension that uses the MS Graph client, if the assigned task Graph call occurs first, the custom adaptive card extension's graph call will fail (403). This only occurs on first page load. On subsequent page loads, this works correctly.

### Steps to reproduce

1. Create, or download, an adaptive card extension that makes a Graph call. In this example, we'll use [PrimaryTextCard-Graph-UnreadEmails](https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-Graph-UnreadEmails).
2. Package and install the sppkg.
3. In the Viva Connections dashboard page, add the Assigned Tasks card and then the Unread Mails card (or a custom card). Republish the page.
4. To simulate a fresh load, open the browser development tools and go to Application > Storage > Clear all data. Then refresh the dashboard page.
5. Look at the Unread Mails (or custom card) and notice that it does not load.

<img width="1015" alt="Screen Shot 2021-12-17 at 10 41 58 AM" src="https://user-images.githubusercontent.com/786967/146592620-acc8c82a-6e0f-477b-b9ad-b360053e4ffb.png">

### Expected behavior

The Graph call should be called correctly and the adaptive card extension should fully load.

**Comment by patmill** [comment]
Thanks @cwparsons - looking into it.

**Comment by AJIXuMuK** [comment]
@cwparsons - sorry for really long silence here.
In the last year we made a lot of improvements related to the authentication in ACEs.
Could you please check if the issue is still present?

Thanks!
