### ISSUE TITLE
SharePoint Lookup Column value not showing out of sudden

### ISSUE THREAD

**Issue by DavidWong0094** [SharePoint/sp-dev-docs#7605]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 95.0.1020.44 
- M365 SharePoint

### Issue description

Hi, I am have created a SharePoint list that comprised of 4 lookup columns. The list have been working fine for the past few months. However, on yesterday, the list user reported there is issue with some of the lookup field, where 2 of the lookup field value didn't show.

I tried at the my end and its works fine, but the end user can't see the lookup value. The end sure have been with Add Items access since.

I also tried to create new lookup column with the same referencing list. But issue remain the same at the user end.

I hope not to redo the list as the list comprised of multiple months data it is also connected with Power automate.

How do I solve this? 

![image](https://user-images.githubusercontent.com/96324140/146627616-6d356460-3a4e-4b11-aabb-92c0f8e3812c.png)

**Comment by shagra-ms** [comment]
@DavidWong0094 I am not sure if this is a formatting related issue. Can you clarify if the issue repros only for Formatters are used?
CC: @AJIXuMuK
