### ISSUE TITLE
How long until the block is lifted?

### ISSUE THREAD

**Issue by eddiesmile** [SharePoint/sp-dev-docs#7607]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

There is no indication on when the block is lifted. We are waiting for a couple of days now and still nothing.
Can you say how long block stays?
Thank you

**Comment by AJIXuMuK** [comment]
@eddiesmile  - could you provide some details?
What block are you referencing to?

**Comment by eddiesmile** [comment]
Apologies,

I was reading this and that's where I tried to open a question: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#what-should-you-do-if-you-get-blocked-in-sharepoint-online

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#what-should-you-do-if-you-get-blocked-in-sharepoint-online>
Avoid getting throttled or blocked in SharePoint Online | Microsoft Docs<https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#what-should-you-do-if-you-get-blocked-in-sharepoint-online>
Find out about throttling in SharePoint Online, and learn how to avoid being throttled or blocked. Includes sample client-side object model (CSOM) and REST code you can use to make your task easier.
docs.microsoft.com
We can't migrate anymore because of the throtteling.
________________________________

**Comment by AJIXuMuK** [comment]
I assume you need to reach out to the contact listed in the notification, as mentioned in the docs:

> If we block your subscription, we will notify you of the block in the Office 365 Message Center. The message describes what caused the block, provides guidance on how to resolve the offending issue, and tells you who to contact to get the block removed.

Have you already done that?
