### ISSUE TITLE
How to use PnP webpart in SharePoint server 2019

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7608]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,

I want to use PnP webpart in SharePoint server 2019. Can someone guild me on that.

Thank in advance

**Comment by bcameron1231** [comment]
I'm sorry but there isn't enough information to provide any help. What PnP Web Part are you looking to use, as there are hundreds of samples.

**Comment by DJoshi23** [comment]
Hi, 

I am trying to use the below Microsoft starter pack 2 PNP web parts in SharePoint 2019.

![image](https://user-images.githubusercontent.com/86624727/147088204-f65632ea-05ad-4a4c-940b-bc1aa6e7d16f.png)

But it's a throwing error while adding the app to site content

![image](https://user-images.githubusercontent.com/86624727/147088410-0cf045ca-8e22-409f-9724-7d7ba6228c24.png)

Thank you in advance

**Comment by AJIXuMuK** [comment]
@bcameron1231 - could you please transfer the issue to the PnP Starter Kit repo?

**Comment by bcameron1231** [comment]
@AJIXuMuK Unfortunately, I don't have the access needed to do a transfer to the Starter Kit Repository.

**Comment by VesaJuvonen** [comment]
@DJoshi23, @AJIXuMuK and @bcameron1231 - we cannot move issues across organizations, so closing this in here. @DJoshi23 please open new issue at https://github.com/pnp/sp-starter-kit/issues so that the team can help with the questions. Thx.
