### ISSUE TITLE
Implement Modern News List View using Custom Spfx Solution SharePoint 2019 Server

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7609]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi, 

I am new to the SPFx solution I need to implement to modern news List View using SPFX custom Code.

Can I request any idea or any sample solution to refer to?
 

Thank you in advance

**Comment by bcameron1231** [comment]
Can you clarify? You are looking to build a Web Part that shows news?

My recommendation would be to go through all of the tutorials before starting. This will give you a good understanding of SPFx. (Use left navigation after to get to Web Part tutorials)

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview

Additionally, we have a lot of samples in the PnP Repository. If you search for News, there are a couple samples you can use for guidance.

https://pnp.github.io/sp-dev-fx-webparts/

**Comment by patmill** [comment]
You might want to look into the JSON field formatting as well.
