### ISSUE TITLE
Unable to connect-pnponline using kudu or azure webjobs

### ISSUE THREAD

**Issue by kaushalbcactus** [SharePoint/sp-dev-docs#7614]
I am unable to connect pnponline in azure environment.
I installed modules folder and referenced it using import statement but still getting error

The Win32 internal error "The handle is invalid" 0x6 
PS C:\home\Modules> occurred while setting character attributes for the console output buffer. 
Contact Microsoft Customer Support Services.
![image](https://user-images.githubusercontent.com/49706885/147616088-f30c2017-6c09-46c6-aeb2-fe58f922ccc2.png)

**Comment by VesaJuvonen** [comment]
As this is related on the PnP PowerShell and not on SharePoint dev topics directly, please open the issue at following location so that the right team can provide assistance for your question. Thx - https://github.com/pnp/powershell
