### ISSUE TITLE
Debugging Domain Isolated Web Parts 

### ISSUE THREAD

**Issue by tyh77** [SharePoint/sp-dev-docs#7615]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Referencing a previous thread: https://github.com/SharePoint/sp-dev-docs/issues/6471

I understand that a hosted workbench is required for using the SharePoint context, but does this mean for every "new" webApiPermission that is requested:

![image](https://user-images.githubusercontent.com/25734254/147624043-8d1696b4-82bb-4611-b647-24aa7569de98.png)

We must deploy a SPPKG to the site in order to have its permissions created by the SharePoint Admin center during upload?

It seems that if I modify my localhost version of the app to include new permissions, the app starts to have issues obtaining tokens via AadHttpClient.

Let's say, I'm making additions to a current domain-isolated web part to include more permissions, I must first deploy a packaged web part with said permissions before I can start locally testing my changes through hosted workbench

@andrewconnell would you be able to clarify on this?

**In fact, I haven't been able to locally debug domain isolated web parts. I consistently get the following error:**

```
Uncaught (in promise) InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID '<SharePoint-App-Registration-Id>' SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
```

**Comment by bcameron1231** [comment]
This is true. The Web Part must be uploaded to the App Catalog with said permissions and approved before you can use them.

**Comment by AJIXuMuK** [comment]
@bcameron1231 is right.

**Comment by tyh77** [comment]
Gotcha.

I'm able to deploy web parts with said new permissions - that's fine.

But is there a way to successfully debug localhost instance once permissions have been updated? My local instance is not able to fetch tokens via AadTokenProvider successfully. It keeps throwing the following:

> Uncaught (in promise) InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID '<SharePoint-App-Registration-Id>' SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.

No issues with deployed instance.

**Comment by bcameron1231** [comment]
Nope. You need to be running in an authenticated session. So you'd need to use the SP hosted workbench.
