### ISSUE TITLE
Dashboard for Viva Connections web part throws a 'Can't get this dashboard URL' error 

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-docs#7618]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version:  Chrome Version 81.0.4044.113 (Official Build) (64-bit)
- SPFx version: N/A  (OOTB Dashboard for Viva Connections web part)
- Node.js version: N/A

### Describe the bug / error

The Dashboard for Viva Connections web part is throwing an error:

ERROR:
Can't get this Dashboard URL. It may not be set up yet, or it may have been deleted.

CALL STACK:
Error: Can't get this Dashboard URL. It may not be set up yet, or it may have been deleted.
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/dashboard-webpart_en-us_0a0976b5cc110e3b25de.js:1:15363

![image](https://user-images.githubusercontent.com/28032142/147698651-268d6cb5-138a-408a-9708-0d533cfd32c3.png)

The site was registered as the home site and the Setup Viva Connections option was used to create the Dashboard.aspx page.  Cards were added to the page and the page was published.  Upon adding the Dashboard for Viva Connections web part to the vertical section in the home page the error was thrown.  

Setting a different site in the tenant as the home site and setting up Viva Connections on that site results in the same error for a page on that site, but then causes the dashboard web part to work on the original site (non-home).

***Note there is a vanity URL on this tenant, in this case team.cl****.com instead of cl****.sharepoint.com.

### Steps to reproduce

1. Register the site as the home site.
2. Setup Viva Connections.
3. Add cards to the Dashboard.aspx page and publish.
4.  Add the Dashboard for Viva Connections web part to a page on the home site.

### Expected behavior

The Dashboard web part displays the ACEs on the page.

**Comment by VesaJuvonen** [comment]
thx @Annie-Johnson - this is indeed most likely related on the vanity URL model which is quite rare and it might be that there's a regression on that side. Will start internal discussions on this right away, but there's no direct SLA for this channel.

As this is oob feature and not directly related on the development, would recommend opening up also a support case either using admin portal or with premier support (best option if available). Using official support channels have agreed SLA which will help on the resolution speed.

**Comment by Annie-Johnson** [comment]
Thanks @VesaJuvonen, I've opened a premier support case.  I appreciate your attention to this!

**Comment by VesaJuvonen** [comment]
Thanks @Annie-Johnson - given that this is a special case with the vanity URLs, let me close it from here to avoid any confusion in general. As you have the premier support case open, we'll certainly get this sorted out for your tenant using official support channels.
