### ISSUE TITLE
Command Set onInit is called twice 

### ISSUE THREAD

**Issue by hesperanca** [SharePoint/sp-dev-docs#7619]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFX version 1.4.1

### Describe the bug / error

OnInit called twice on Command set extensions with SPFX version 1.4.1. We make some an async call on this method so this is causing us a problem.

This issue was raised before (#1157) and it seems that it was fixed in a subsequent version of SPFX (after version 1.4.1) and closed. But what about developers creating solutions for on-prem SharePoint? 

We cannot use a version after version 1.4.1 so does this mean that we will have to learn to live with bugs like this? What is  Microsoft's strategy in fixing issues with version 1.4.1? Is version 1.4.1 still supported? If it is still supported why there haven't been any updates for almost 4 years?

### Steps to reproduce

As described in issue #1157 the steps to reproduce are:

1. create simple command set
2. add console.log('onInit'); in onInit
3. look at the console - onInit is presented twice.

### Expected behavior

OnInit method should only be called once.

**Comment by AJIXuMuK** [comment]
Hi @hesperanca,
Thank you for bringing this up.
Unfortunately, due to technical dependencies, we will not make any non-security related updated to SP2019.
So the issue will persist in this version of on-prem.
It potentially will be fixed at some point of time in SharePoint Server Subscription Edition. But no ETA for that, too.
