### ISSUE TITLE
Security updates or enterprise support for tools and libraries used by SPFx 

### ISSUE THREAD

**Issue by reshmee011** [SharePoint/sp-dev-docs#7621]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Latest Microsoft Edge
- SPFx version, 1.13.1
- Node.js version, LTS 14
- etc

### Issue description

We are starting our journey into SPFx development but reached a bottleneck with the node.js supported by the current SPFx 1.13.1 which is either LTS14 or LTS12 and are unable to get agreement from the internal security team to install LTS 14 because latest version of Node.js is available and we are still trying to justify in myriad ways to allow us to install NPM and Node.js. 
The outstanding concern is the SLA support in case of any security vulnerability is identified in any of the tool, e.g. gup, react.js, etc.. and how soon these can be patched ready to be deployed. 
We managed to find enterprise support for Gulp https://gulpjs.com/docs/en/support/for-enterprise/#enterprise-ready-open-source-softwaremanaged-for-you.

Are there any enterprise support to patch security vulnerabilities for Yeoman, React.js, Node.js , etc? 
We are interested to find out how other companies having Cyber Essentials Plus accreditation deal with the above scenario.

**Comment by patmill** [comment]
While we will be migrating to Node 16 in the future, the main request / question is outside the scope of this issues list.

**Comment by reshmee011** [comment]
@patmill : I understand that Node js will be upgraded soon to Node 16 for the latest SPFx version. However currently SPFx requires Node.js v12 or v14 , React v16.13.1 and Typescript v3.9 and wonder how security vulnerabilities found in the libraries/tools are addressed.

**Comment by patmill** [comment]
Vulnerabilities found in code that runs in the service (say, react) are fixed and rolled out.  React isn't actually in your bundle, it's externalized and provided by the framework at runtime.  Vulnerabilities in libraries that you consume would need to be patched / rebuilt / deployed by you.  We fix our toolchain to patch known vulnerabilities as well.
