### ISSUE TITLE
List formatting hideSelection property not working for groups

### ISSUE THREAD

**Issue by joaoferreira** [SharePoint/sp-dev-docs#7622]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari

### Describe the bug / error

The group selection is not getting hidden in a Microsoft Lists view formatting with the property hideSelection is defined to true.

### Steps to reproduce

1. Group a list by one of the columns  
2. Apply a custom view formatting and define the property "hideSelection"="true"
3. Hover the group name and you will see that the main selector for the group gets visible

### Expected behavior

The group selector should not be visible when the hideSelection is defined to true, despite being visible it doesn't do anything to the view.

**Comment by shagra-ms** [comment]
The build with the fix will roll out in upcoming weeks. Thanks!

**Comment by shagra-ms** [comment]
The fix is now rolled out. @joaoferreira let me know if this still doesn't work as expected. Thanks! :)
