### ISSUE TITLE
Modern site page content type is still sealed on existing sites

### ISSUE THREAD

**Issue by AlexRademeyer** [SharePoint/sp-dev-docs#7625]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

#1843 
Is this closed because it is solved? or just closed because you won't fix it?

### Steps to reproduce

In existing sites though it is still sealed and thus you can not really build solution that work on existing as well on new sites.

Are there any plans to change this? Is there a way to manually or programatically change this on existing sites?

### Expected behavior

In new sites the modern site page content type is not sealed anymore which is good for adding metadata to site pages and building custom solutions around this capability.

**Comment by VesaJuvonen** [comment]
There are no plans to do updates on the existing sites from Microsoft as that could cause issues with them... as there's no way to know if the content type is modified or not after the initial creation. You can however use APIs or UX to adjust this setting on existing sites as needed.
