### ISSUE TITLE
Thank you for reporting this issue. We will be triaging your incoming issue as soon as possible.

### ISSUE THREAD

**Issue by Afar01** [SharePoint/sp-dev-docs#7628]
Hellow everyone. I am new for Github community, I just signed up now. Please excuse me if this is not the right place to ask spfx questions. 
I Created spfx field customization with hyperlink in sp2019 server and sp online. when I tried to display on home page, the sp online works fine, but sp 2019 server cant display the field I customized at the home page. I just wonder if Microsoft can't support some features on SharePoint on premise. Again thanks

**Comment by VesaJuvonen** [comment]
There are significant differences between the supported features in the SharePoint Online and in on-premises. SharePoint 2019 is 3 years older version than what we have in the cloud, which evolves on the weekly basis. Other than that - it's hard to provide more detailed answer given the provided details.
