### ISSUE TITLE
Fail to load customizer for column: SPFxPercentage, error: Manifest not found for componentId 

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7629]
I think the documentation could benefit from additional clarification. 
The [Add the field definition to the solution package for deployment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#add-the-field-definition-to-the-solution-package-for-deployment) section states: "_Associate the Field Customizer to an existing field in the site. You can do this programmatically using the SharePoint REST or CSOM API, or by using the Feature Framework in of the SharePoint Framework solution package"_

What I'm missing is a clear statement that field customizers deployed as part of a feature, as described in the procedure, cannot be later applied to other, already existing fields if that original field is not displayed. 

To reproduce:
- Follow the [Build your first Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer)
- Deploy the solution as described in [Deploy the field to SharePoint Online and host JavaScript from local host](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#deploy-the-field-to-sharepoint-online-and-host-javascript-from-local-host)
- Apply the customizer to an already existing field, using  `Set-PnPField`
- Remove the SPFxPercentage field from the list

The customizer ceases to work, and the following message is displayed in the Console:
 `Fail to load customizer for column: Percentage2,
                      componentId: 7e7a4262-d02b-49bf-bfcb-e6ef1716aaef, error: Manifest not found for componentId "7e7a4262-d02b-49bf-bfcb-e6ef1716aaef". `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc14882-1021-df0e-73c1-95d049f091d7
* Version Independent ID: eda24750-4e60-f05c-a6bb-0cc017dfe9ed
* Content: [Build your first Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer)
* Content Source: [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
Hi @kkazala - thanks for reporting this one.
It shouldn't be the case: removing the field from the list (or from the site) doesn't impact the availability/deployment status of a Field Customizer.
Could you please provide few more details:
- Did you use tenant-wide deployment or no?
- If no - have you by any chance removed the app from the site?
- Have you by any chance removed the package from the app catalog?
- If you were debugging, could it be the case that you've stopped the local server?

**Comment by kkazala** [comment]
Hi @AJIXuMuK  
Thank you very much for looking into it. 
I tested it again and... I cannot reproduce the issue any more. Can't explain it, but for sure I did something wrong when testing

I'm sorry for taking your time for nothing =)
