### ISSUE TITLE
❓ Get list of items in current view for Extension Command Set

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#763]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Question
Is it possible to get a list of all items shown in the current list view displayed on the page?

#### Scenario
Consider a command set button in an item's context menu that should be shown under specific conditions based on the data of an item in the list. 

When an item's context menu is opened, you have access to all the *visible* columns in the view... but not the columns that aren't in the view.

If the column is not in the view, the command set will need to make a roundtrip via the SP REST API to get the data from the non-visible column every time the context menu is opened.

This can get quite chatty... and since `BaseListViewCommandSet<>.onRefreshCommand()` does not return a promise, the context menu will light up and commands may appear / disappear after the user has changed focus and the context menu has disappeared.

One workaround to this would be within the command set's `onInit()` to fetch the desired data for all items in the current view, cache it on the page, and then the `onRefreshCommand()` method can lookup the local cache. To do this, you need to figure out what items are on the page (*hence the title of the issue*) so you only get the data for those items, not all items on the page.

Asking to make sure I'm not missing something...

**Comment by bcameron1231** [comment]
I'd like to know the same thing! Looks like RowAccessor "row" is the visual representation of the item and seems to be the only way to get columns when in the view. Be interested in hearing best approach for this.

**Comment by mcmynn83** [comment]
We render the list items with a view query and do not have the data for columns that are not in the view.  Therefore, the only way to get this data is to query for it in a subsequent query.  This is by design for performance reasons (we don't want to grab data that typically is unused).
