### ISSUE TITLE
Retrieving Site Settings options programmatically in SPFX.

### ISSUE THREAD

**Issue by aadilwani** [SharePoint/sp-dev-docs#7631]
Is it possible to get this data programmatically in SPFX   ?

![image](https://user-images.githubusercontent.com/17984143/148433454-61365df5-0609-4149-aa1f-580f2496ec41.png)

**Comment by VesaJuvonen** [comment]
Is it possible to get the data around the links? - or is it possible to perform operations around those areas which are behind of the links. Links access is not supported. Behind of each of those settings there are tens or even hundreds of settings or operations... so some of the SharePoint site level operations can be performed using APIs, so cannot... it's hard to provide more specific answer given the scope of the question.
