### ISSUE TITLE
Bug with gulp serve + react-three-fiber

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#7635]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Chrome 96
- SPFx version : 1.13.1
- Node.js version : 14.16
- Windows version : 11

### Describe the bug / error

Hi,

I wanted to make my first example webpart for using threeJS / React-three-fiber (https://github.com/pmndrs/react-three-fiber).

I configured the webpart and started coding, but gulp serve do not work correctly, after launching debug mode on the browser, the browser blocks (infinite loop?).

Not finding the error, so I built the package to test a deployed version and it works.

I would need help because I don't see where the problem is.

If anyone could test on another environment (mac / linux) or if you have any idea, I am interested.

I have tested with and without fast-serve, i have the same result.
I have tested on another browser, i have the same result.

Packaged version for test
[spfx-react-threejs-sample.zip](https://github.com/SharePoint/sp-dev-docs/files/7828454/spfx-react-threejs-sample.zip)

gitHub repos
https://github.com/PooLP/spfx-react-threejs-sample

### Steps to reproduce

1. launch gulp serve
2. launch sharepoint for debug webpart
3. add the webpart

if  webpart block on add step, add the package on your app catalog, and add webpart in normal use (no debug) and launch debug after

### Expected behavior

it's my first exemple for PnP, i would like to finish it ^^

**Comment by patmill** [comment]
It would be good to provide more information.  Where is the infinite loop, what's the callstack, anything show up in the console, anything in the network trace, what have you done to debug and diagnose so far, etc.

**Comment by PooLP** [comment]
Where is the infinite loop => on first load, in debug mode (only sharepoint interface appear, browser block after)
what's the callstack => i can't verify, browser block
anything show up in the console => nothing, browser block
anything in the network trace => nothing, browser block

I have no solution for debugging, gulp serve blocks browser.

the only test that worked, is the packaged version work correctly, i have the problem only in debug mode.

is there a solution to put a debug mode on webpack / gulp task or trace before the first loading? fiddler, but what should i watch?

If i'm remove react-three-fiber elements, all work in debug, but is not a solution.

i'm use this lib on other projects without problem, but is not spfx projects.

**Comment by PooLP** [comment]
@patmill Unfortunately, I do not have more information to provide, the browser freeze before being able to do anything.

Could you test on your side? it may be my environment, even if I have no problem with all my other SPFx projects.

**Comment by patmill** [comment]
So in general, we don't investigate why random package isn't working.  If you can point out _why_ it's not working, we can look at fixing it.  That said, I took a look at your sample github project, and I'm puzzled by this line in your package.json file:

`"react-three-fiber": "5.x.x"`

That doesn't look like a valid reference.

**Comment by PooLP** [comment]
for "react-three-fiber": "5.x.x" this is another way to get the latest fixes for a specific version (5.x.x => ~5.0.0)
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

I think I have trouble making myself understood, my English is not very good.

I don't ask that we debug for me, but that we help me to find a solution to debug.

The problem only occurs in debug mode. All the code works once the package is created.

but in debug mode, the browser freezes before there is the slightest error or possibility of debugging on the browser side.

So I'm asking for help with:

* Check if other users on an environment other than Windows 11 encounter the problem to eliminate a platform problem
* Ideas so that I can trace the problem, because I don't know how I can debug a problem related to the debug mode of the SPFx

PS : react-three-fiber is not a little ramdom package (https://github.com/pmndrs/react-three-fiber) 2.6M of download.
I'm use version 5.x.x because it is compatible with typescript 3, newer versions must be compatible with Typescript 4, but SPFx is not compable whitout modification, it could have side effects for debugging. I will modify this when the debug problems are fixed.

**Comment by patmill** [comment]
That package isn't called react-three-fiber in npm (at least from what I see).  It is @react-three/fiber - https://www.npmjs.com/package/@react-three/fiber

**Comment by PooLP** [comment]
both works, react-three-fiber it's the old name. the problem does not come from here.

**Comment by patmill** [comment]
The problem seems to be that the ReactDebugCurrentFrame$1 variable is undefined, so the call to setCurrentFiber throws an exception.  In the exception handler, there is an infinite loop where it tries to set the Current Fiber (via resetCurrentFiber), which throws an exception because ReactDebugCurrentFrame is undefined, which triggers the exception handler.

You can debug this by running the workbench, popping open the picker, then setting "break on all exceptions".  The 1st exception has to do with trying to parse a version, then the frame errors start getting triggered.

Searching online for 'react-three-fiber ReactDebugCurrentFrame' returns this as the #1 hit - https://github.com/facebook/react/issues/14137

Reading through that, the workaround suggested is to set the NODE_ENV variable to production, not development.  Doing that resulted in a webpart showing two rotating red squares.

**Comment by PooLP** [comment]
Thanks @patmill.
I still have gaps on the debugging tools, thank you for helping me and finding a solution.
I have corrected repos with set the env mode on package.json sript line :
```
    "serve": "gulp clean && gulp bundle --custom-serve --max_old_space_size=4096 && cross-env NODE_ENV=production fast-serve",
```
This is while waiting for the react-reconciler lib to be fixed.
