### ISSUE TITLE
List Formatting - Using Emoji in padStart does not display correctly

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#7636]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft Edge version 96.0.1054.62

### Describe the bug / error

If I specify emoji in padStart, the characters will be garbled and will not be displayed correctly.

![image](https://user-images.githubusercontent.com/51254139/148537018-22d75dbb-5af7-46c5-a807-7e225541305d.png)

If you specify alphanumeric characters other than emoji, they will be displayed correctly.

![image](https://user-images.githubusercontent.com/51254139/148537216-5880f278-4265-4f9d-8e3e-6a969e822001.png)

### Steps to reproduce

1. Create a list.
2. Enter "Item" in the Title field
3. Set the following JSON for the Title column formatting
``` JSON
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "txtContent":"=padStart(@currentField , 9 , '🐣')",
  "style": {
    "font-size":"20px"
  }
}
``` 

### Expected behavior

Even when emoji are set, they are not garbled and are displayed correctly.

**Comment by shagra-ms** [comment]
Thanks for sharing this.

This is a bit tricky and not straight-forward as the emoji used is 2 Unicode characters -
![image](https://user-images.githubusercontent.com/37994247/148746630-0742b181-8c76-4de7-a9bb-d88caa33d533.png)

The behavior observed is what is currently expected in the case of multiple characters -
![image](https://user-images.githubusercontent.com/37994247/148746753-dd58c547-825a-4a74-b87d-546148ebdea8.png)

The JSON can be updated to make this work - 
```JSON
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "txtContent":"=padStart('', (9-indexOf(@currentField+'^','^'))*2, '🐣') + @currentField",
  "style": {
    "font-size":"20px"
  }
}
```
Logic: 
- Create prefix of emoji repeated _[required length] * [length of emoji]_ times
- Append `@currentField` to it

**Comment by tecchan1107** [comment]
@shagra-ms 
Thanks for the answer😆✨
I used the method you showed me and it worked fine!!
