### ISSUE TITLE
PowerShell example

### ISSUE THREAD

**Issue by LennartaeHoefer** [SharePoint/sp-dev-docs#7637]
Hi

I went through the site-footer doc and thought it's a bit confusing that the sample powershell shows how to disable the footer. 

Connect-PnPOnline -Url "<SiteURL>" –Credentials (Get-Credential) 
Set-PnPFooter -Enabled:$**false**

I think a better example would be to use the parameter variable $true to enable the footer. 

Best regards
:-) Lennart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://docs.microsoft.com/en-us/sharepoint/dev/features/site-footer)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/site-footer.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
As footer is enabled by default, we decided to show the default example with disabling it. Of course you can absolutely also have the Boolean value as True for then enabling it again. 

We just updated the doc to have the both options shown, so that there's no confusion on this.
