### ISSUE TITLE
Microsoft Teams Desktop Personal app not working with SPFX and GraphApi

### ISSUE THREAD

**Issue by XixiHuang333** [SharePoint/sp-dev-docs#7640]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I added a Personal Tab in MS Teams which references a SharePoint Webart with on it an SPFx webpart using @microsoft/microsoft-graph-client.

In the MS Teams Web Client on TEST and PROD the page loads as expected, and the @microsoft/microsoft-graph-client calls work. In the MS Teams Desktop client on TEST environment also work perfect.

However, in the MS Teams Desktop Client (on windows) on PROD environment the @microsoft/microsoft-graph-client does not work.

Looking in Fiddler, I can see the following happening (only on the dekstop client):

A call is made to https://o2fitcom.sharepoint.com/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%2758066c29-7a47-418b-9cb8-69adf68633b3%27&clientId=%2708e18876-6177-487e-b8b5-cf950c1e598c%27 with error result Failed to load resource: the server responded with a status of 403 ()

The call returns an HTTP 500 with message:

<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"> <m:code>-2147024891, System.UnauthorizedAccessException</m:code> <m:message xml:lang="en-US">Attempted to perform an unauthorized operation.</m:message> </m:error>

I already success make solution work on TEST but not in PROD, checked all the configuration and manifest are the same. All the configuration of permission in the SharePoint Online Client Extensibility Web Application Principal are granted.

similar issue:
https://stackoverflow.com/questions/59860729/spfx-webpart-in-msteams-desktop-client-throws-an-unauthorizedaccessexception
https://github.com/SharePoint/sp-dev-docs/issues/3923
https://github.com/SharePoint/sp-dev-docs/issues/5441

### Steps to reproduce

1. I added a Personal Tab in MS Teams which references a SharePoint Webart with on it an SPFx webpart using @microsoft/microsoft-graph-client.
2. In the MS Teams Web Client on TEST and PROD the page loads as expected, and the @microsoft/microsoft-graph-client calls work. In the MS Teams Desktop client on TEST environment also work perfect.

### Expected behavior

we expected it should work in Teams desktop client on PROD environment as well.

**Comment by ntdong1889** [comment]
I followed this guideline and face the problem above  
[](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)

**Comment by amalitabose** [comment]
I am also facing the issue, it was working till Friday (2 days ago).
Graph calls not working in teams desktop app using Spfx react.
Error is while getting token

https://m365x5xxxx7.sharepoint.com/sites/dev/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27https://graph.microsoft.com%27&clientId=%27xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx%27
![error](https://user-images.githubusercontent.com/57438154/148936399-96bb0818-8842-4862-95f1-24e2512db1e3.png)

**Comment by OliverZeiser** [comment]
We are also seeing this issue on our apps. Seems to be a general issue once again...

**Comment by GrahamMcMynn** [comment]
@amalitabose  - the issue you are seeing is unrelated to this thread.  Your tenant is new and we have issues with tenants created after early November 2021.  A principal is not provisioned correctly.  The fix for that is already rolling out and it will remediate the issue for all new tenants within about 2 weeks.

@XixiHuang333  - I'm sorry that you are seeing this issue.  Could you send the fiddler trace to grahamc at microsoft.com so I can take a look at the cause of your issue?

**Comment by XixiHuang333** [comment]
@GrahamMcMynn  Thanks for your help on this. Actually I help @ntdong1889 to raise the issue here. @ntdong1889  could you please help to send fiddler log here?

**Comment by ntdong1889** [comment]
[MSTeams Diagnostics Log 09_12_2021__14_15_28.zip](https://github.com/SharePoint/sp-dev-docs/files/7861373/MSTeams.Diagnostics.Log.09_12_2021__14_15_28.zip)
[FiddeLog.zip](https://github.com/SharePoint/sp-dev-docs/files/7861380/FiddeLog.zip)
Here :v

**Comment by GrahamMcMynn** [comment]
@XixiHuang333  / @ntdong1889  - Thanks for the information.  I've reached out to Xixi off of git hub to look into what is wrong.  The users do not have remote api access and therefore are blocked from making calls.  I am working with Xixi to determine what permissions you have given the users.

**Comment by XixiHuang333** [comment]
@ntdong1889  As Graham's guidance, could  you please check did this feature get enabled?
[Impact of deactivating the Limited-access user permission lockdown mode feature - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/472581/impact-of-deactivating-the-limited-access-user-per.html)

**Comment by ntdong1889** [comment]
![image](https://user-images.githubusercontent.com/97509402/149448163-d21926a8-6419-4650-9b59-26b286b3c112.png)

**Comment by GrahamMcMynn** [comment]
@ntdong1889 - When you enable this feature it prevents remote API's from being used.  Permissions for teams auth use remote API's in order to authenticate.  Having that feature active is not supported if you want SPFx apps in teams to authenticate correctly.  Is there a reason you have it active?

**Comment by ntdong1889** [comment]
> @ntdong1889 - When you enable this feature it prevents remote API's from being used. Permissions for teams auth use remote API's in order to authenticate. Having that feature active is not supported if you want SPFx apps in teams to authenticate correctly. Is there a reason you have it active?

Thank for your answer and support. I need to talk with SP Admin to discus about this.

**Comment by ArijitCloud** [comment]
I have been trying out SPFx and Graph api to create personal. I am seeing the issue in my mobile android device teams client as well. Can someone please confirm, if the issue is also impacting mobile device client as well?

**Comment by GrahamMcMynn** [comment]
Set the status of this to by design because the original bug was due to the limited access user permission setting.

@ArijitCloud  - there are other threads such as issue #7639 which are related to mobile.

**Comment by ntdong1889** [comment]
> Set the status of this to by design because the original bug was due to the limited access user permission setting.
> 
> @ArijitCloud - there are other threads such as issue #7639 which are related to mobile.

@GrahamMcMynn  I contacted with the SP admin and tried to deactivate Limited-access user permission lockdown mode feature but the issue still occurs. Do you have any ideas?

**Comment by GrahamMcMynn** [comment]
@ntdong1889 / @XixiHuang333 - if you are still experiencing an issue could you please send me a new trace?

**Comment by ntdong1889** [comment]
> @ntdong1889 / @XixiHuang333 - if you are still experiencing an issue could you please send me a new trace?
[Fiddler-20220125.zip](https://github.com/SharePoint/sp-dev-docs/files/7930084/Fiddler-20220125.zip)

I send you the fiddle. one for Teams App and one for Viva Connection

**Comment by lucabandMSFT** [comment]
hey @ntdong1889, can you please do the following to see if that resolves your issue?

- log in to Azure portal as a Global Administrator
- go to "App registrations"
- search for "SharePoint Online Client Extensibility Web Application Principal" object
- click there and select "Certificates and secrets"; you should end up in a UX like the following and you should have just one client secret
![image](https://user-images.githubusercontent.com/46542683/151042941-8cc138be-f0c6-4395-84c6-36c403d37d22.png)


at that point click on the trash can icon and delete that secret. Once you are done there. go back to SPO tenant admin and ensure you are both Global Admin AND SPO teantn admin. Then go to the "API Access" page: that will trigger generation of a new client secret (you can see that in the AAD portal after you visited the page in SPO tenant admin and refresh). 

This should solve the problem: if that's not the case please open a new GH issue so we can properly track the issue.
Thanks!

**Comment by ntdong1889** [comment]
> hey @ntdong1889, can you please do the following to see if that resolves your issue?
> 
> * log in to Azure portal as a Global Administrator
> * go to "App registrations"
> * search for "SharePoint Online Client Extensibility Web Application Principal" object
> * click there and select "Certificates and secrets"; you should end up in a UX like the following and you should have just one client secret
>   ![image](https://user-images.githubusercontent.com/46542683/151042941-8cc138be-f0c6-4395-84c6-36c403d37d22.png)
> 
> at that point click on the trash can icon and delete that secret. Once you are done there. go back to SPO tenant admin and ensure you are both Global Admin AND SPO teantn admin. Then go to the "API Access" page: that will trigger generation of a new client secret (you can see that in the AAD portal after you visited the page in SPO tenant admin and refresh).
> 
> This should solve the problem: if that's not the case please open a new GH issue so we can properly track the issue. Thanks!

I got this when try to access API Access Page
![image](https://user-images.githubusercontent.com/97509402/151144273-774be9cf-757d-4298-a098-91de53f3fd93.png)

**Comment by GrahamMcMynn** [comment]
Hi @ntdong1889  - sorry to do this to you again, do you mind sending me a trace of loading the web api permissions page?

**Comment by ntdong1889** [comment]
Hi @GrahamMcMynn here is the log. Thanks for all the support :)
I and another SP Admin have the same issue :(
[ApiAccessLog.zip](https://github.com/SharePoint/sp-dev-docs/files/7949332/ApiAccessLog.zip)
