### ISSUE TITLE
 SPFX package which gets deployed to SP online without any issue, but the same package isn't getting deployed to SharePoint Subscription Edition

### ISSUE THREAD

**Issue by aadilwani** [SharePoint/sp-dev-docs#7643]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have a SPFX package which gets deployed to SP online without any issue, but the same package isn't getting deployed to SharePoint Subscription Edition. Here is the error message MS.Utitlity.Event Error while uploading SPFx app

**Comment by AJIXuMuK** [comment]
Hi @aadilwani - what version of SPFx are you using?

**Comment by aadilwani** [comment]
+-- @microsoft/generator-sharepoint@1.13.1
+-- gulp-cli@2.3.0
+-- touch-cli@0.0.1
`-- yo@4.3.0

**Comment by VesaJuvonen** [comment]
@aadilwani  - SharePoint Subscription Edition only unfortunately supports SPFx 1.4.1 and older versions. It's based on the SharePoint Server 2019 code-base and the newer versions and capabilities which we have in the SharePoint Online are not available there.

This means that it's as expected for the 1.13.1 version packages not to work in there. 

Here's a great community blog post on this topic - https://www.voitanos.io/blog/definitive-guide-sharepoint-framework-sharepoint-server-subscription-edition/
