### ISSUE TITLE
Please add reference for the javascript option called out in the presentation (method 2)

### ISSUE THREAD

**Issue by EdAlexander** [SharePoint/sp-dev-docs#7644]
After looking through the presentation I created an spfx webpart project with Method 1 (deploy assets in spfx apppkg)... This method seems to be at odds with the way I wish to deploy the webpart as an app (full page).

I decided to try method 2 (JavaScript running from the webpart) and am hitting some walls... Failing to create list using 

  const listAddResult = await sp.web.lists.add("List Name", "list description here", 100, true, { OnQuickLaunch: true });

Is there a good reference for how to make this work some where?  Can that reference be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f8d79e-59f8-967b-3339-479c52be24c3
* Version Independent ID: 0bf6bc17-ac75-966a-cf48-69e1f6ced047
* Content: [Provision SharePoint assets with your solution package](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets)
* Content Source: [docs/spfx/toolchain/provision-sharepoint-assets.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/provision-sharepoint-assets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
When you install an app, no script is executed as part of the installation process. This page is simply saying you can use JS to create the assets your solution needs. However, you'll have to manually run that code. 

One approach I prefer to use is when your component loads (after installation), it checks for all the necessary dependencies (ie: "is the list present?"). If not, it displays a message saying the dependencies need to be created and provides a button to trigger this (something only a user with appropriate permissions can do).

Think if it like the image web part. You add it to the page and it has a UX that basically asks for you to pick an image. Once picked, it shows something else.
