### ISSUE TITLE
It's no longer possible to preview a WebPart in SharePoint WorkBench, when using percentage ch % in a PropertyPaneTextField

### ISSUE THREAD

**Issue by larrydk** [SharePoint/sp-dev-docs#7652]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
Edge: Version 97.0.1072.62 (Official build) (64-bit)
Chrome: Version 96.0.4664.110 (Official Build) (64-bit)
- SPFx version
SPFX: 1.13.1
- Node.js version
v14.15.0
- etc

This is an error, I've seen for quite some time, just didn't realize, what was causing it. :-)

### Describe the bug / error

In SharePoint Online WorkBench:
If you add a percentage (%) to a PropertyPaneTextField and click on Preview you get a completely blank page and the following error in the console:

Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
    at t.render (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:72)
    at Bo (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at No (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at ys (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at pc (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at uc (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at ac (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    at sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70
    at t.unstable_runWithPriority (sp-webpart-workbench-assembly_en-us_dcf07bb88ac1815785ca91904adc7629.js:70)
    
    If you then reload, you're back in edit mode and see your WebPart again, then click "Preview" and the error is back

### Steps to reproduce

1. Create a new project: 
- Yo @microsoft/sharepoint 
- Platform: SharePoint Online
- Type: WebPart
- Framework: React
2. NPM -i (if not already done so)
3. Update serve.json with a SharePoint Site
4. Run Gulp Serve
5. Add the WebPart on the WorkBench
6. Edit the WebPart  
7. Add a percentage ch % in the title and click preview
8. Then the blank page appears and the console contains the described error

### Expected behavior

I would expect the Workbench showing a preview of the WebPart as it used to do. 
It seems like an issue with the WorkBench only, since there's no problem using the percentage ch % - when the WebPart is deployed.

**Comment by AJIXuMuK** [comment]
Thank you @larrydk for reporting this one.
The fix has been done and should roll out WW in the next couple of weeks.

**Comment by larrydk** [comment]
Thank you very much @AJIXuMuK, that was fast :-)
