### ISSUE TITLE
Labelled as obsolete with no direction on upgrade method

### ISSUE THREAD

**Issue by SPDEVGUY** [SharePoint/sp-dev-docs#7655]
Field is marked obsolete with a hint on using a caml query but doesn't provide an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbd5f0e-7064-2666-fdf6-8e9211a94c89
* Version Independent ID: 7b605908-29c1-8886-9d85-f579df3d9db1
* Content: [SPList.GetDistinctFieldValues(SPField, Object\[,\]) Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.splist.getdistinctfieldvalues?view=sharepoint-server)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPList.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPList.xml)
* Product: **sharepoint**
* Technology: **sdk**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by VesaJuvonen** [comment]
Here's a good reference documentation on that server side operation - https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/use-spquery-to-query-a-list
