### ISSUE TITLE
Remote event receiver where I can download the uploaded document 

### ISSUE THREAD

**Issue by aadilwani** [SharePoint/sp-dev-docs#7657]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

In SPFx I want to have a remote event receiver which gets attached to a document library in SharePoint online and invokes a webhook/API. My requirement is whenever some document gets uploaded to the library it invokes the webhook and in the webhook I should be able to download the uploaded document, any idea how I can achieve this ?

**Comment by AJIXuMuK** [comment]
@aadilwani - I would start with [SharePoint Webhooks](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/get-started-webhooks) documentation that describes how to register a webhook for a list.
There is also a [tutorial](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation) on how to get access token and item changes in the webhook.
And just to be clear: it is not an SPFx app. Webhook is a web app hosted somewhere (for example, Azure).

Let me know if you need any clarification on that.

**Comment by aadilwani** [comment]
To be more specific, I want to know is it possible to get the uploaded file content within the webhook code. For example on Item Attachment Added event my webhook gets called, can I get that attachment in the webhook

**Comment by AJIXuMuK** [comment]
@aadilwani - you can use [REST API](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#working-with-files-by-using-rest) or maybe CSOM as well.
