### ISSUE TITLE
Error auth SPFX Webpart calling Azure API authenticated with APP Registration and external user (Redirects 3 times before get token)

### ISSUE THREAD

**Issue by marcmoraRAONA** [SharePoint/sp-dev-docs#7658]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFX v1.12.1 

### Describe the bug / error

I make a SPFX Webpart that calls API published on Azure with authentication configured by App Registration. I put all API permission configuration on package-solution.config:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/22834621/150000884-ad6659f2-a2b3-4584-9631-1df1a93b0454.png">
And to get token I use aadTokenProvederFactory :
<img width="532" alt="image" src="https://user-images.githubusercontent.com/22834621/150002655-4514e817-929a-47a5-9d6b-1f3961def852.png">

If I open sharepoint page with webpart with an normal licensed user, all goes fine.
But if I open sharepoint page with an external user, then strange behaviors occurs:

Page is opened, webpart is showed but cannot call API because get token fails and page is refreshed 3 times. After 3 refreshes , all goes fine and get token call finished successfully and API is called .

This behavior  only occurs with external users and authenticated API. If I disable authentication on API , all goes fine and no redirects occur.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22834621/149999105-047e9693-8b10-4e55-bc2f-364f0b427b66.png)

Someone can help me? 

### Steps to reproduce

1. Open page with webpart that calls Azure authenticated API
2. Page is refreshed
3. Page is refreshed
4. Page is refreshed
5. Page is opened and all goes fine.

### Expected behavior

Expected behavior is like a normal licensed user.

**Comment by lucabandMSFT** [comment]
hey @marcmoraRAONA, how did you register the Guest account in AAD and SharePoint? mind provide a snipped of the configuration from AAD portal if this is not a production tenant?

**Comment by marcmoraRAONA** [comment]
Really I only share site with external user, this user now can enter to the site and can use as a normal user except this behavior with authenticated API.

This is the user configuration on Azure AD: 
![image](https://user-images.githubusercontent.com/22834621/150090019-b47576f9-33e1-49bf-bbf1-e819d8a32bbd.png)

This is App Registration configuration:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/22834621/150090354-d327a828-8308-4cf3-a4fa-4699a2c8650d.png">

This is App Service (API) authentication configuration:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/22834621/150090754-38ac210d-d15c-4c59-b576-4e59e2e85143.png">

Thanks

**Comment by marcmoraRAONA** [comment]
Someone can help me? Someone can reproduce same situation?

**Comment by lucabandMSFT** [comment]
hey @marcmoraRAONA, sorry for my delay in answering. Here's what I did:

- created an SPFx app that access Microsoft Graph
- added a guest user in AAD
- gave access to the guest user to the Team site
- log in to guest user and confirm that everything was working.
I had no issue on that test.. which makes me thinking that the issue you are perceiving is on the custom API registration. Out of curiosity: if you make a call to Microsoft Graph only (I see in your snipped above you do register to graph scope too), do you experience same / similar issue? Or the issue is only when the code tries to get a token to access the custom API?
