### ISSUE TITLE
Viva connections - The title of the Adaptive card changes the property pane header

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7659]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.13

### Issue description

Would it be possible that the header of the property pane of an Adaptive card is fixed to the name that appears in the card picker? similar to what webparts do.

At the moment the property pane header displays the Card title, which is something that can be changed if we expose it as a property.

![image](https://user-images.githubusercontent.com/24438807/150123473-7bc228bd-09fe-4edc-b8b8-179f7b9c383d.png)
In the image above, it should say "[Fresh] alerts" in the property pane header

So I would like that the custom cards behave like the OOTB "Web link" card, where the property pane header shows the name of the card (Web link) and it doesn't change when the Card title is updated
![image](https://user-images.githubusercontent.com/24438807/150122529-a49ff242-fa44-4ca2-9345-a889f59f2e5f.png)
 
This way the users know what card did they choose from the card picker.

Thanks!

**Comment by micwilson911** [comment]
Hi [Rafaelki](https://github.com/Rafaelki),

Thank you for bringing this up! We realized that the default scaffolding was a bit confusing and fixed the scaffolding in newer SPFx releases. An alternative is  that you can remove the **public get title(): string { ... }** method within your **{file_name}AdaptiveCardExtension.ts file** and this will achieve the behavior that is seen on the Web link component. Hope this helps!
