### ISSUE TITLE
"loadComponent() returned an empty object" on Classic Pages

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#766]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior
SPFx client side web parts have stopped loading in our O365 production environment. No code changes have been made on our end. We get the following error in place of the web part:

***loadComponent() returned an empty object for component "5b805ab7-19e2-485a-b65a-f25cafc6ea4e" (HeaderWebPart)

These web parts are setup on classic SharePoint pages.

All of our O365 sites that use SPFx started behaving this way around noon Aug 7.

**Comment by patmill** [comment]
Hi @jaredbuttars - can you give any additional information?  If you look at the network tab in the browser debugger, are you seeing 404's anywhere?  If you look at the console, are there any errors / warnings listed?

**Comment by mpasarin** [comment]
Hi @jaredbuttars,
We were rolling out some changes in the framework that started causing this problem for a small subset of customers. Once we realized it was causing these problems we rolled back those changes.

**Comment by jaredbuttars** [comment]
If it helps at all, the issue was present in all browsers except Edge where there was no issue at all.
