### ISSUE TITLE
Single part app page webpart issues with Add Page Preview interface

### ISSUE THREAD

**Issue by RafalUrbanski** [SharePoint/sp-dev-docs#7663]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 97.0.4692.99
- SPFx version: 1.11.0
- Node.js version: v10.17.0
- framework: Vue

### Describe the bug / error

When I am adding new Single Part App Page, after selecting my app in modern 'Add Page' experience, render() method of my webpart is being called multiple times. Moreover, when I resize screen while preview is visible, error is being thrown:

Error details: Error: Error initializing application. Error: Error: [PageFieldData] Missing Required Property: (PageLayoutType)

![AppPartPagePreviewIssue](https://user-images.githubusercontent.com/29370511/150488623-fe929b11-6e62-410a-80c8-be5a79e7e120.gif)

Please notice how many times "Sintel BI render method has been called..." is being called in console.

### Steps to reproduce

Prerequisite: At least one custom spfx webpart that is of single part app webpart type
1.Go to home page of the modern site
2. Hit the 'New' -> 'Page' button
3. Select the 'Apps' tab
4. Select custom app tile

### Expected behavior

App is being loaded once and preview is shown in right side of the panel. Switching between different apps should work. Resizing window while showing preview should work.

**Comment by AJIXuMuK** [comment]
Thank you @RafalUrbanski for reporting the issue.
The "preview" is an actual web part, loaded in an iframe. That's why you can see multiple calls of `render` method when switching back and forth.
I will take a look at the failure while resizing the page.

**Comment by RafalUrbanski** [comment]
Thank you @AJIXuMuK 
One note - it is not the matter of switching back and forth  - every time preview is rendered, render method is called multiple times.

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - the changes have been made and will be rolled out WW in the next couple of weeks.
The failure has been fixed.

**Comment by RafalUrbanski** [comment]
@AJIXuMuK Thank you!
Could you please clarify whether both resize, and multiple rendering issues have been addressed?
Will I get notified when it is rolled out?

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - resize has been fixed.
For the multiple `render` calls - I've created a task in the backlog to look into it.

For the notifications - I will update this issue, but you can expect the functionality to arrive by February 13

**Comment by AJIXuMuK** [comment]
This should be rolled out WW by now

**Comment by RafalUrbanski** [comment]
Hi,

resize issue seems to be resolved.

What's the status of multiple render calls issue? I just checked it and it still is being called multiple times and it breaks the app preview while switching between different apps.

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - as mentioned,

> For the multiple render calls - I've created a task in the backlog to look into it.

It is not a high priority now.

**Comment by RafalUrbanski** [comment]
@AJIXuMuK thanks for the update. I do not have any way to track the progress of this backlog item and thus I had to ask.

If you find a moment, please reconsider priority of this task - even though the resize issue was a easily noticeable bug, it was something that user would experience rather rarely, while the multiple render issue seems to kill the app preview way more often and requires to implement workarounds in the code to avoid such a situation.
