### ISSUE TITLE
SPFX: onInit is called with wrong context.pageContext for CommandSet when navigating in a certain order

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#7665]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser: Edge Dev v99
- SPFx v1.10
- Node.js 10.24.1

### Describe the bug / error

**TLDR**: in _onInit_, _this.context.pageContext_ is not the current context, but the previous one (_.list.id_ is different to _.legacyPageContext.listId_ etc.), iff coming from a SitePage to a list view and then going to another list view, where both lists have the same extension.

I can persistently reproduce the following issue every time: 
If I enter from my site's Homepage (a normal SitePage with one standard built-in webpart on it) and switch to a list (via the side navigation) where a CommandSet list extension is activated (which gets initialized fine), and then switch to another list (again via the side navigation) where the same CommandSet list extension is activated, this one receives the wrong page context in its onInit call (the previous list, not the current list). 

If I however enter not via the start page but directly in any AllItems-view page, everything is fine - I can switch lists via the navigation and each of their extensions is initialized as it should with the correct page context. It appears that only coming from a Site page and only for the 2nd extension (and so on) this mechanism does not work (resp. no longer, I think this used to work not too long ago, but cannot be sure). @AJIXuMuK 

I found no related console output nor errors. 

### Steps to reproduce

1. Open a browser tab on a SharePoint site's Homepage (some SitePage with a standard built-in webpart on it)
2. Switch to a list (via the side navigation) where a CommandSet list extension is activated (this works and gets initialized)
3. Switch to another list (via the side navigation) where the same CommandSet list extension is activated (this receives an incorrect this.context.pageContext.list, the former, not the current)

In contrast, skipping step 1 and starting directly on a list view page does not show this behaviour. 

### Expected behavior

The expected behaviour is that no matter from where I end up coming to a list view, if an extension (CommandSet) is registered for the list, it should get initialized (onInit be called for each list once) properly (with the correct context information). 
This works in most cases, but not when opening a SitePage first, then going to an extended list, and then going to another such one. 
Unfortunately, without extensions getting activated properly, there is no point at all in using them. 
We are forced to work around the problem by inspecting the current URL to derive the actual context information.

**Comment by AJIXuMuK** [comment]
Hi @frevds - thank you for reporting this issue.
The fix has been done and will be rolled out WW in the next couple of weeks.

**Comment by frevds** [comment]
Thank you @AJIXuMuK, that was rapidly fast. Looking forward for it to roll out, closing ticket.
