### ISSUE TITLE
Broken Github links

### ISSUE THREAD

**Issue by stev3reed** [SharePoint/sp-dev-docs#7669]
The two links in this sentence point to resources on GitHub that don't appear to exist. I've tried searching GitHub for them and cannot find them so either the links are bad or they no longer exist.

![image](https://user-images.githubusercontent.com/7061659/150871157-8591f7be-2cd4-43b3-a689-4847f2c92a4b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b75396-5714-d2f5-8b9f-2a0a32dbce8c
* Version Independent ID: ec183ab1-43d9-0a58-8caf-8a3541f49528
* Content: [Cross-domain images in SharePoint provider-hosted add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins)
* Content Source: [docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
thx @stev3reed for submitting this issue. We have updated the doc with the fixed links.
