### ISSUE TITLE
 ERR_CERT_AUTHORITY_INVALID on LINUX when using online workbench

### ISSUE THREAD

**Issue by robpearmain** [SharePoint/sp-dev-docs#7672]
Hi.

I am experimenting installing SPFx on Ubuntu.  

I run gulp trust-dev-cert without any errors 

When I do gulp serve, and use Chromium, it gives me the normal "Make sure gulp serve is running" (It is).  

Investigating the console I get lots of net::ERR_BLOCKED_BY_CLIENT when trying to tunnel through to https://localhost:4321

I think the issue is the certificate produced is not being added like on WINDOWS or MACOS

I think it is something to do with having to install rushstack-serve.pem somewhere, as Linux does not auto install the certificate

Documentation seems lacking for running on linux

(Note local workbench worked fine with previous SPFx versions, but now we only have the online workbench, which is great but doesn't seem to work on LINUX

I acknowledge from the message below the info on pem, but there is no guidance anywhere on how to get this working.

![272300219_1357394278026693_5112117176711163767_n](https://user-images.githubusercontent.com/299240/151165149-8054c01f-bf5a-4208-a9b3-c76199df2724.jpg)

[)](url)

**Comment by bcameron1231** [comment]
Can you please follow this post, I believe it will help you solve your issue.

https://www.donkirkham.com/blog/spfx-dev-cert/

**Comment by AJIXuMuK** [comment]
@robpearmain - please, let us know if Don's post helps.
Thanks @bcameron1231 for looking into it.

**Comment by robpearmain** [comment]
> @robpearmain - please, let us know if Don's post helps.
> Thanks @bcameron1231 for looking into it.

I have found the generated PEM file, but I am not running under windows so I could do with some pointers where to copy the PEM file to once created please

**Comment by robpearmain** [comment]
> Can you please follow this post, I believe it will help you solve your issue.
> 
> https://www.donkirkham.com/blog/spfx-dev-cert/
> 
> Based on Don's post, on Linux, the cert gets created but you'll have to import the certificate to the Certificate Store yourself.

Please could you point me to information on how to import the PEM file to the Linux certificate store, this post seems to be for when running g under windows.

**Comment by bcameron1231** [comment]
In transparency, I'm not a linux person, so I don't know the answer to the question. A quick google search brought this up.

https://thomas-leister.de/en/how-to-import-ca-root-certificate/

**Comment by robpearmain** [comment]
Ah, this adds some more detail I have not seen before, adding them to the
cert stores for browsers.

I have definitely installed the root, so this makes sense why the browser
is still causing issues

I will test and let you know.

Thank you

Rob

**Comment by robpearmain** [comment]
> In transparency, I'm not a linux person, so I don't know the answer to the question. A quick google search brought this up.
> 
> 
> 
> https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> 

> 
> https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> 
> 

Fantastic, this works

So on Linux, after gulp trust-Dev-cert you need to find rushstack-serve.pem and follow the example to create rushstack-serve.crt

When updating certificates I added -f to force the update

Finally, I changed the bash script to reference rushstack-serve.pem and it added it to chrome

Now when I run gulp serve, no more security warnings and invalid certificates.

Fantastic, I will update Andrew Connell so he can add it to the docs

Thanks to all

**Comment by robpearmain** [comment]
Here is the problem and  solution in full:

PROBLEM: Linux browsers give a certificate error, even if you run gulp trust-dev-cert

TO REPEAT:

On Linux, when you type 

Gulp trust-dev-cert

It creates the rushstack-serve.pem file but does not auto install it to the root and browsers as it does on Windows and MacOS

THE SOLUTION:

Beau Cameron pointed me in the right direction to

https://thomas-leister.de/en/how-to-import-ca-root-certificate/

Please refer to that for more explanation on the info below

So, on Linux, when you run

Gulp trust-dev-cert

It creates in a hidden folder from the users folder two files

Rushstack-serve.key
Rushstack-serve.pem

In the hidden by default folder

 ~/.rushstack

In the terminal you need to navigate there

cd  ~/.rushstack

Then create a folder in the ca-certificates (Linux Trust store) shared folder for the certificate (I chose extra but not sure if the name is important)

sudo mkdir /usr/local/share/ca-certificates/extra

Copy the “.pem” file renaming it to “crt” extension:

sudo cp rushstack-serve.pem /usr/local/share/ca-certificates/extra/rushstack-serve.crt

Force linux to update its certificates (I found -f was needed, you may not need it unless it says 0 updated):

sudo update-ca-certificates -f

Then you need to add it to all the browsers (Cromium, Firefox etc)

To do this, run the following to install the “certutil” tool

sudo apt install libnss3-tools

Then create a “installspfx.sh” script file using nano

Sudo nano installspfx.sh

Paste the following, and then save and exist (ctrl+X I think)

# Start of script 

#!/bin/bash

### Script installs root.cert.pem to certificate trust store of applications using NSS
### (e.g. Firefox, Thunderbird, Chromium)
### Mozilla uses cert8, Chromium and Chrome use cert9

###
### Requirement: apt install libnss3-tools
###


###
### CA file to install (CUSTOMIZE!)
###

certfile="rushstack-serve.pem"
certname="SPFx rushstack-serve"


###
### For cert8 (legacy - DBM)
###

for certDB in $(find ~/ -name "cert8.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
done


###
### For cert9 (SQL)
###

for certDB in $(find ~/ -name "cert9.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
done

# (End of script)

Once saved, ensure it can run by typing

Sudo chmod +x installspfx.sh

Run it by typing

./installspfx.sh

All done.  When you type gulp serve, chromium and firefox have a trusted dev cert, and wont give any errors

So the references are

This thread: https://github.com/SharePoint/sp-dev-docs/issues/7672#issuecomment-1023580563

And 

This article:

https://thomas-leister.de/en/how-to-import-ca-root-certificate/

**Comment by bcameron1231** [comment]
Thank you for the full explanation of the solution. Much appreciated!
