### ISSUE TITLE
SPFX 1.13.1 - @microsoft/sp-core-library@1.13.1 missing lib 

### ISSUE THREAD

**Issue by timdhahn** [SharePoint/sp-dev-docs#7673]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.13.1
- Node v14.17.0
- @microsoft/sp-core-library@1.13.1

### Describe the bug / error

Following @estruyf guidelines on using @microsoft/sp-core-library utility functions (https://www.eliostruyf.com/utility-functions-install-extra-dependencies-sharepoint-framework/), I noticed the "lib" folder is missing.

![image](https://user-images.githubusercontent.com/7631802/151238267-bbf1cc02-4097-451a-ac35-f75059e324bc.png)

sp-core-library missing lib folder in node_modules
![image](https://user-images.githubusercontent.com/7631802/151238445-0d6413f8-b0ff-4a85-8b54-80a97008b5a0.png)

### Steps to reproduce

1. Create an spfx 1.13.1 project
2. npm install @microsoft/sp-core-library@1.13.1
3. Try to import from the lib folder 
`import { BrowserUtilities } from '@microsoft/sp-core-library/lib/BrowserUtilities';`

### Expected behavior

I was expecting the lib folder to be present to allow for named imports

![image](https://user-images.githubusercontent.com/7631802/151238063-d62b9dda-7b5f-4fd6-b9f4-96602bf81430.png)

**Comment by bcameron1231** [comment]
BrowserUtilities was moved to @microsoft/sp-core-library/lib-commonjs/BrowserUtilities

**Comment by AJIXuMuK** [comment]
@timdhahn @bcameron1231 - `BrowserUtilities` class is not a part of public API. So it can be changed, moved or disappear without a notice.
