### ISSUE TITLE
Just want a simple 

### ISSUE THREAD

**Issue by CarlWilliams** [SharePoint/sp-dev-docs#7674]
[Enter feedback here]
?? There's no manifest or anything like that on a sharepoint page. I just want a simple little icon beside my page's document library webpart title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e7009-0cb3-76ed-fdac-848af3d396b0
* Version Independent ID: 6e219143-e4b8-4fa0-0a1e-ea8fc3a7b4bd
* Content: [Configure web part icon](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/configure-web-part-icon)
* Content Source: [docs/spfx/web-parts/basics/configure-web-part-icon.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/configure-web-part-icon.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Adding an Icon next to a Document Library (out of the box) web part is not something that is available.
