### ISSUE TITLE
Unit Testing with Jest throws window.requestAnimationFrame TypeError for office ui component

### ISSUE THREAD

**Issue by v-prigunasek** [SharePoint/sp-dev-docs#7677]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version - 1.13.0
- Node.js version - 14.18.2
- React version - 17.0.2

### Describe the bug / error

Getting below error while running the unit test for Office UI fabric component.

Test suite failed to run

    TypeError: window.requestAnimationFrame is not a function

      at Stylesheet.Object.<anonymous>.Stylesheet._getStyleElement (node_modules/@uifabric/merge-styles/src/Stylesheet.ts:295:16)
      at Stylesheet.Object.<anonymous>.Stylesheet.insertRule (node_modules/@uifabric/merge-styles/src/Stylesheet.ts:227:65)
      at applyRegistration (node_modules/@uifabric/merge-styles/src/styleToClassName.ts:284:20)
      at Object.styleToClassName (node_modules/@uifabric/merge-styles/src/styleToClassName.ts:294:5)
      at mergeCss (node_modules/@uifabric/merge-styles/src/mergeStyles.ts:30:18)
      at Object.mergeStyles (node_modules/@uifabric/merge-styles/src/mergeStyles.ts:13:10)
      at Object.<anonymous> (node_modules/@uifabric/utilities/src/scroll.ts:9:33)

### Steps to reproduce

Test cases throw errors for components which are having other dependent packages like Fluent UI /Office fabric.

![image](https://user-images.githubusercontent.com/98514691/151318842-7226f510-7235-400c-89e2-b57a20083d8f.png)

![image](https://user-images.githubusercontent.com/98514691/151318858-d461348e-36a0-4a94-a310-7f0f5dfba4c0.png)

**package.json**
{
  "name": "partner-voice-site-survey",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "jest",
    "test:watch": "jest --watchAll"
  },
  "dependencies": {
    "@fluentui/react": "^8.35.2",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@microsoft/sp-office-ui-fabric-core": "1.12.1",
    "@microsoft/sp-property-pane": "1.12.1",
    "@microsoft/sp-webpart-base": "1.12.1",
    "@pnp/sp": "^2.8.0",
    "bootstrap": "^5.1.1",
    "fast-text-encoding": "^1.0.3",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-bootstrap": "^1.6.3",
    "react-csv": "^2.0.3",
    "react-dom": "16.9.0",
    "react-reactstrap-pagination": "^2.0.3",
    "react-router-dom": "^5.3.0",
    "reactstrap": "^8.10.0",
    "tslint-microsoft-contrib": "^6.2.0"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.8": "^0.4.47",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-webpart-workbench": "^1.12.1",
    "@types/enzyme": "3.10.9",
    "@types/enzyme-adapter-react-16": "1.0.6",
    "@types/jest": "27.0.2",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "@voitanos/jest-preset-spfx-react16": "^1.5.0",
    "ajv": "~5.2.2",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "gulp": "~4.0.2",
    "identity-obj-proxy": "3.0.0",
    "jest": "^27.2.4",
    "jest-junit": "12.3.0",
    "jsdom": "^17.0.0",
    "jsdom-global": "3.0.2",
    "react-test-renderer": "17.0.2",
    "ts-jest": "27.0.5",
    "tslint": "^6.1.3",
    "tslint-microsoft-contrib": "^6.2.0",
    "typescript": "^4.4.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest"
    },
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx|js)"
    ],
    "coverageDirectory": "<rootDir>/jest",
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/jest-config/file-mock.js",
      "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
    },
    "setupFilesAfterEnv": [
      "<rootDir>/jest-config/setupTests.ts"
    ]
  }
}

### Expected behavior

Unit test should pass without any error.

**Comment by KevinTCoughlin** [comment]
Is your test environment missing a mock for the browser API `window.requestAnimationFrame`?

**Comment by v-prigunasek** [comment]
Thanks for your response, Kevin. 
I'm trying to write a unit test for the sample react app and getting the below error for the office ui fabric component. I have tried adding raf/polyfil but that didnt fix the error.

 TypeError: window.requestAnimationFrame is not a function

      at Stylesheet.Object.<anonymous>.Stylesheet.insertRule (node_modules/@uifabric/merge-styles/src/Stylesheet.ts:227:65)
      at applyRegistration (node_modules/@uifabric/merge-styles/src/styleToClassName.ts:284:20)
      at Object.styleToClassName (node_modules/@uifabric/merge-styles/src/styleToClassName.ts:294:5)
      at mergeCss (node_modules/@uifabric/merge-styles/src/mergeStyles.ts:30:18)
      at Object.mergeStyles (node_modules/@uifabric/merge-styles/src/mergeStyles.ts:13:10)
      at Object.<anonymous> (node_modules/@uifabric/utilities/src/scroll.ts:9:33)

If I add  "testEnvironment": "jsdom" to the package.json file, am getting the below error.

Test environment found at "C:\Users\v-prigunasek\SP-JestEnzyme-Test-master\node_modules\jest-environment-jsdom\build\index.js" does not export 
a "getVmContext" method, which is mandatory from Jest 27. This method is a replacement for "runScript".

Please let me know if I'm missing anything in the configuration.

**Steps to replicate:**

_HelloWorld.tsx_

import * as React from 'react';
import styles from './HelloWorld.module.scss';
import { IHelloWorldProps } from './IHelloWorldProps';
import { escape } from '@microsoft/sp-lodash-subset';
import {
  DocumentCard,
  DocumentCardPreview,
  DocumentCardTitle,
  DocumentCardActivity,
  IDocumentCardPreviewProps
} from 'office-ui-fabric-react';

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
 
  public render(): JSX.Element {
    const previewProps: IDocumentCardPreviewProps = {
      previewImages: [
        {
          previewImageSrc: String(require('./document-preview.png')),
          iconSrc: String(require('./icon-ppt.png')),
          width: 318,
          height: 196,
          accentColor: '#ce4b1f'
        }
      ],
    };
  
    return (
      <div className={ styles.helloWorld } id="spfxTest">
      <div className={ styles.container }>
        <div className={ styles.row }>
          <div className={ styles.column }>
            <span className={ styles.title }>Welcome to SharePoint!</span>
            <p className={ styles.subTitle }>Customize SharePoint experiences using Web Parts.</p>
            <h1 className={styles.title}>SPFx Test webpart</h1>  
            <p className={ styles.description }>{escape(this.props.description)}</p>
            <a href="https://aka.ms/spfx" className={ styles.button }>
              <span className={ styles.label }>Learn more</span>
            </a>
          </div>
        </div>
      </div>
      <DocumentCard onClickHref='http://bing.com'>
        <DocumentCardPreview { ...previewProps } />
        <DocumentCardTitle title='Revenue stream proposal fiscal year 2016 version02.pptx' />
        <DocumentCardActivity
          activity='Created Feb 23, 2016'
          people={
            [
              { name: 'Kat Larrson', profileImageSrc: String(require('./avatar-kat.png')) }
            ]
          }
        />
      </DocumentCard>
      </div>      
    );
  }
}


_HelloWorld.test.ts_

import 'jsdom-global/register';
import * as React from 'react';  
import { configure, mount, ReactWrapper } from 'enzyme';  
import * as Adapter from 'enzyme-adapter-react-16';  
  
configure({ adapter: new Adapter() });  
  
import HelloWorld from '../components/HelloWorld';  
import { IHelloWorldProps } from '../components/IHelloWorldProps';  

  
describe('Enzyme basics', () => {  
  
  let reactComponent: ReactWrapper<IHelloWorldProps, {}>;  
  
  beforeEach(() => {  
  
    reactComponent = mount(React.createElement(  
        HelloWorld,  
      {  
        description: "SPFx Jest Test"  
      }  
    ));  
  });  
  
  afterEach(() => {  
    reactComponent.unmount();  
  });  
  
  it('should root web part element exists', () => {  
  
    // define the css selector  
    let cssSelector: string = '#spfxTest';  
  
    // find the element using css selector  
    const element = reactComponent.find(cssSelector);  
    expect(element.length).toBeGreaterThan(0);  
  });  
  
  it('should has the correct title', () => {  
    // Arrange  
    // define contains/like css selector  
    let cssSelector: string = 'h1';  
  
    // Act  
    // find the element using css selector  
    const text = reactComponent.find(cssSelector).text();  
  
    // Assert  
    expect(text).toBe("SPFx Test webpart");    
  });  
});

_package.json_

{
  "name": "jest-test",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "office-ui-fabric-react": "7.174.1",
    "@microsoft/sp-core-library": "1.13.0",
    "@microsoft/sp-property-pane": "1.13.0",
    "@microsoft/sp-webpart-base": "1.13.0",
    "@microsoft/sp-lodash-subset": "1.13.0",
    "@microsoft/sp-office-ui-fabric-core": "1.13.0"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "@microsoft/sp-build-web": "1.13.0",
    "@microsoft/sp-module-interfaces": "1.13.0",
    "@microsoft/sp-tslint-rules": "1.13.0",
    "@types/enzyme": "3.10.11",
    "@types/enzyme-adapter-react-16": "1.0.6",
    "@types/jest": "27.4.0",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "gulp": "~4.0.2",
    "identity-obj-proxy": "3.0.0",
    "jest": "27.4.7",
    "jest-junit": "13.0.0",
    "jsdom": "19.0.0",
    "jsdom-global": "3.0.2",
    "react-test-renderer": "16.13.1",
    "ts-jest": "27.1.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest"
    },
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx|js)"
    ],
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "cobertura"
    ],
    "coverageDirectory": "<rootDir>/jest",
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
    },
    "reporters": [
      "default",
      "jest-junit"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 100,
        "functions": 100,
        "lines": 100,
        "statements": 100
      }
    }
  },
  "jest-junit": {
    "output": "./jest/summary-jest-junit.xml" 
  }
}

**Comment by v-prigunasek** [comment]
Hi, Is there any workaround or fix for this error? Please update me on this.

**Comment by AJIXuMuK** [comment]
@v-prigunasek - just to confirm - have you check Andrew Connell's post on how to configure Jest in SPFx project: https://www.andrewconnell.com/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step/?
