### ISSUE TITLE
Field customizer doesn't load consistently when searching

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#7679]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version

Chrome: 97.0.4692.99
Firefox: 96.0.3

- SPFx version

1.13.1

- Node.js version

14.18.1

### Describe the bug / error

A customer who is using a field customizer I developed reported to me that the customizer was working fine when searching within a library until yesterday, but is no longer working today.

I have tried to reproduce the issue on my end, and what I've found in my environment is that the customizer works initially after searching, but if I refresh the page while the `&q=searchterm` is present in the URL, or if I navigate away from the page and use the Back button to return to it, etc, then the field customizer isn't applied to the list of results. <s>It may be the case that this is what's happening in my customer's environment as well, but I haven't had a chance to inquire further yet.</s> **Update:** After inquiring further with my customer, it seems that he is seeing the same behavior as I am.

### Steps to reproduce

1. Create or obtain a field customizer that has an observable effect on the field
   - I have created a minimal example in [this Github repo](https://github.com/JLRishe/minimal-field-customizer). There is a built .sppkg in the [`built`](https://github.com/JLRishe/minimal-field-customizer/tree/main/built) folder of the repo and the component ID is `36b70cbf-69a7-4d25-be9a-1ec2abad6c17`
2. Install it in your site
3. Create a document library
4. Apply the customizer to the library's LinkFilename column by setting its ClientSideComponentId (e.g. by using the REST API)
5. Upload a file to the library
6. View the library. Observe that the field customizer's changes are applied
7. Perform a search for the filename of the file you uploaded. Again observe that the changes are applied
8. Refresh the page

EXPECTED: The field customizer's changes are still applied
ACTUAL: The field renders with its default behavior, without the field customizer

9. Press the back button to go back to the All Items view

EXPECTED: The field customizer's changes are applied
ACTUAL: The field renders with its default behavior, without the field customizer

### Expected behavior

The field customizer should be rendered even when navigating to a search URL.

**Comment by AJIXuMuK** [comment]
@JLRishe - the fix has been done and will roll out WW in the next 2 weeks.

**Comment by JLRishe** [comment]
@AJIXuMuK Thank you very much for all your help!

**Comment by AJIXuMuK** [comment]
this should be rolled out ww by now

**Comment by AJIXuMuK** [comment]
@JLRishe - you are right. Seems like it's not fully fixed.
Looking.

**Comment by AJIXuMuK** [comment]
@JLRishe - additional fix has been done.
Unfortunately, you'll need to wait few more weeks to make it WW.

**Comment by JLRishe** [comment]
@AJIXuMuK Thank you! My customer and I have both confirmed that this is working now.
