### ISSUE TITLE
Broken Link on page "Host webs, add-in webs, and SharePoint components in SharePoint"

### ISSUE THREAD

**Issue by TobiasHeck** [SharePoint/sp-dev-docs#768]
Either the link [Accessing the add-in from the UI](https://dev.office.com/sharepoint/docs/sp-add-ins/important-aspects-of-the-sharepoint-add-in-architecture-and-development-landscape#AccessingApp) on the page [Host webs, add-in webs, and SharePoint components in SharePoint](https://dev.office.com/sharepoint/docs/sp-add-ins/host-webs-add-in-webs-and-sharepoint-components-in-sharepoint) should be edited to actually point to the correct URL, or better fix the typo in the URL of the page [Important aspects of the SharePoint Add-in architecture and development landscape](https://dev.office.com/sharepoint/docs/sp-add-ins/important-aspects-of-the-sharepoint-add-in-architecture-and-development-landscap), which is missing an "e" at the end.

By the way: Good work on the documentation and in general the Patterns & Practices initiative!

#### Category
- [ ] Question
- [X] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I would not expect an error page, when clicking on the [Accessing the add-in from the UI](https://dev.office.com/sharepoint/docs/sp-add-ins/important-aspects-of-the-sharepoint-add-in-architecture-and-development-landscape#AccessingApp) link on the page [Host webs, add-in webs, and SharePoint components in SharePoint](https://dev.office.com/sharepoint/docs/sp-add-ins/host-webs-add-in-webs-and-sharepoint-components-in-sharepoint) and would like to see the correct page [Important aspects of the SharePoint Add-in architecture and development landscape](https://dev.office.com/sharepoint/docs/sp-add-ins/important-aspects-of-the-sharepoint-add-in-architecture-and-development-landscap).

#### Observed Behavior
A "Document not Found" error is displayed, when clicking on the link.

#### Steps to Reproduce
Click on the link on the page.

**Comment by mcmynn83** [comment]
@VesaJuvonen - Could you follow up on the documentation request

**Comment by VesaJuvonen** [comment]
thx @TobiasHeck for the issue, appreciate your input. We have now fixed the links.
