### ISSUE TITLE
Theme colors do not load (immediately) on SP listpage or site contents page

### ISSUE THREAD

**Issue by Oshimani** [SharePoint/sp-dev-docs#7680]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 97.0.4692.99
- SPFx version 1.13.1/1.13.0
- Node.js version 14.18.1

### Describe the bug / error

When developing a search bar in the page header using an application customizer extension I noticed that spfx would not load the SharePoint provided theme when i navigate to a list or the site contents page. It would always use the default light blue theme.

But it applies the correct theme to components that render at a later point e.g. after a asynchonous fetch.
![list](https://user-images.githubusercontent.com/19518999/151548123-183678a9-25f8-4880-9484-5b5094d57e71.png)

On "normal" site pages everything is working as expected. (See below)
![page](https://user-images.githubusercontent.com/19518999/151548127-880b43d5-9f5c-4502-b209-15b7b3f02525.png)

### Steps to reproduce

1. Create SPFX Solution using `yo` (mine contains webparts and extensions)
2. Create an extension that uses Placeholder API to add a header to SP pages
```ts
this.context.placeholderProvider.tryCreateContent(PlaceholderName.Top)
```
3. Apply theme using `getTheme().palette.<desired_color>` to any element that is rendered immediately
```ts
import { Stack, getTheme } from '@microsoft/office-ui-fabric-react-bundle';
// Start react functional component
<Stack horizontalAlign="center" styles={{ root: {backgroundColor: getTheme().palette.themeDarkAlt}}}>
// more DOM elements
```
4. Look at the header background color on a page and a list. On a list page it will have the default theme and on a page it will be temed propperly
5. Add an asynchronous call and delay rendering of the themed elements in the header. See how it applies the corrent theme now.

### Expected behavior

The correct theme should be applied to SPFX solutions on all sites where they can be placed, including lists and the site contents page.

**Comment by AJIXuMuK** [comment]
Hi @Oshimani - the theme is loaded asynchronously, and it's completely fine if the `getTheme` method you mentioned returns "initial" theme.
I would recommend you to use `ThemeProvider` as described here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds#use-the-background-color-awareness-in-react-based-web-parts

**Comment by Oshimani** [comment]
@AJIXuMuK thank you for this hint.
I am sorry to tell you that this did not solve my problem. In fact this code produced confusing errors when I tried to copy it as is.
```ts
this.context.serviceScope.consume(ThemeProvider.serviceKey as any);
```
I had to add `as any` to this expression to get it past the typescript compiler.

Now for the next problem:
I importet `getTheme` from `@microsoft/office-ui-fabric-react-bundle`. It does not react to changes to the theme. However components from `office-ui-fabric-react` do update when I change the theme.

Can you tell me the difference between getTheme from `@microsoft/office-ui-fabric-react-bundle` and `office-ui-fabric-react` please?

Just to make clear: I have been using `getTheme` to access the selected theme in SharePoint for quite a while now. The only difference is, that I have an extension that will also be visible on lists and only here the problem shows.

I get quite confused with the different packages provided in spfx scaffolding project. There are multiple definitions for types like `ITheme`, `getTheme`, `ThemeProvider` just to name a few.
Is there a guide that describes in detail how and when to use which definition?

Thanks for your help so far!

**Comment by AJIXuMuK** [comment]
> Can you tell me the difference between getTheme from @microsoft/office-ui-fabric-react-bundle and office-ui-fabric-react please?

The only difference is version. `office-ui-fabric-react-bundle` is based on `office-ui-fabric-react` and provide as set of resources that are used on all SharePoint pages.
There might be difference in when exactly the module/library is loaded, and it _could_ affect the provided value.

> I am sorry to tell you that this did not solve my problem. In fact this code produced confusing errors when I tried to copy it as is.
I'm attaching a simple example of Application Customizer that is using `ThemeProvider` with no need for `any`.

> I get quite confused with the different packages provided in spfx scaffolding project. There are multiple definitions for types like ITheme, getTheme, ThemeProvider just to name a few.
Is there a guide that describes in detail how and when to use which definition?

I believe you use libraries like PnP React Controls or some other 3p modules.
These libraries can have references on older versions of SPFx. And if you `import` the type from a reference from this library - you can get a typing issue.
[ac-themes.zip](https://github.com/SharePoint/sp-dev-docs/files/7973456/ac-themes.zip)

Please, let me know if the explanation and the same resolve you issue.

**Comment by Oshimani** [comment]
Thanks for this example. I did some testing with it.
- It does work fine on site pages
- It does not work on list pages, there the following error occurs
![error](https://user-images.githubusercontent.com/19518999/151941468-385fe766-ae44-44ca-b2ed-036d5890ca21.png)

But refreshing the page after changing the theme makes it work for one refresh. There seems to be a race condition of some sort. Since the placeholder top and bottom features are available on list pages I think they should work just the same.

> I believe you use libraries like PnP React Controls or some other 3p modules.
These libraries can have references on older versions of SPFx. And if you import the type from a reference from this library - you can get a typing issue.

 I do not use any other UI-Components Library other than the preinstalled UI Fabric in this extension. However I use the PnP property pane controlls in a webpart that is part of this solution but I'm very careful to import components from `@microsoft/office-ui-fabric-react-bundle`

**Comment by AJIXuMuK** [comment]
Thanks @Oshimani for the additional info.
> It does not work on list pages, there the following error occurs
Yeah, it was more an example that you don't need to cast `serviceKey` to `any`. I haven't added any conditions or checks for `null`.
But, there was actually a bug with the initialization in some cases.
The needed changes were made and should be rolled out WW in the next couple of week.
After that you should be able to use `ThemeProvider` with no issues.

**Comment by AJIXuMuK** [comment]
this should be rolled out ww by now.
