### ISSUE TITLE
Issue with woff2 files not being supported

### ISSUE THREAD

**Issue by johnstuart1986** [SharePoint/sp-dev-docs#7686]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Im having an issue with woff2 files for a font package I downloaded where at first the woff2 file wasnt even being copied to the lib directory, but after fixing that with a copy-static-assets.json file, I am getting an error that says

./lib/webparts/weather/weathericons/font/weathericons-regular-webfont.woff2 1:4
Module parse failed: Unexpected character '' (1:4)

I found this other discussion that supposedly resolves the issue with a blog post from @StfBauer but the website is broken

https://github.com/SharePoint/sp-dev-docs/issues/1657

### Steps to reproduce

1) Have a woff2 font file
2) Have a css file that references it
3) Try to use gulp serve to load the project to workbench

### Expected behavior

The woff2 files to be bundled properly

**Comment by AJIXuMuK** [comment]
@johnstuart1986 - the blog is not broken anymore: https://n8d.at/how-to-bundle-and-use-custom-web-fonts-in-spfx-projects

There are some configurations/scenarios we don't support out of the box.
But, as mentioned in the post, you can configure Webpack/build to do the things you need.

Please, let us know if there are any issues with applying the approach Stefan has described in the blog.

**Comment by johnstuart1986** [comment]
I just double checked the blog post and it seems to be working now. It wasnt yesterday when i was looking for solutions to my problem.

Thanks though!
