### ISSUE TITLE
npm v7 support

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7688]
Is npm v7 supported already?

According to this [comment](https://github.com/s-KaiNet/spfx-fast-serve/issues/13#issuecomment-829612480), it is since SPFx 1.12. Could we get it confirmed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25459e4a-2488-302d-9906-cfacfdc4639a
* Version Independent ID: 339fbcec-873c-9c47-fd9c-cf5f505132ac
* Content: [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
* Content Source: [docs/spfx/compatibility.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/compatibility.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
The current versions of npm that are supported can be found in the Compatibility Matrix. The latest version 1.13.1 supports NPM v5,v6

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility

**Comment by kkazala** [comment]
thank you @bcameron1231  for the clarification
