### ISSUE TITLE
MS Clarity collecting data from all site collections

### ISSUE THREAD

**Issue by lonestarcz** [SharePoint/sp-dev-docs#7690]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.12.1

### Issue description

Hello,

I have developed an application customizer in SPFx, which register the MS Clarity JS into all pages in SPO.

The problem is, that if I access any site page, where this customizer is registered it works and tracks the data correctly, however if I use cross site link (in navigation) it still tracks the new site page (even if it is another site collection, where the customizer is not registered).

I found out, that if you refresh the page or use new tab it works correctly, however if you stay in the same tab, some JS objects are probably not updated and the MS Clarity JS is still registered.

I appreciate any help on this issue.

Thanks,
Milan

here is the code:

 public onInit(): Promise<void> {
    Logger.subscribe(new ConsoleListener());
    Logger.write(LOG_TEMPLATE(`Initialized ${strings.Title}`), LogLevel.Info);

    this.context.application.navigatedEvent.add(this, this._register);
    return Promise.resolve();
  }

  private _register(): Promise<void> {
    let trackingCode: string = this.properties.trackingCode;

    if (!trackingCode) {
      Logger.write(LOG_TEMPLATE("Tracking code not provided"), LogLevel.Warning);
    }
    else {
      //Inject Clarity
      let main = document.querySelector(".mainContent");

      var clarityScript = document.createElement("script");
      clarityScript.innerText = `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=document.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window, document.querySelector(".mainContent"), "clarity", "script", "${trackingCode}");`
      clarityScript.async = true;
      clarityScript.className="clarityScriptClass";
    
      main.appendChild(clarityScript);
    }

    return Promise.resolve();
  }

I am registering this customizer with custom action and scope is site.
the tracking code for MS Clarity is loaded from properties.

**Comment by AJIXuMuK** [comment]
@lonestarcz - I would suggest to use `onDisponse` in the customizer and unregister the script.
We use in-place navigation for many scenarios. So if you load some external page in the header for example, it will be there after nav.
