### ISSUE TITLE
npm deprecated  warnings - SharePoint Framework v1.13.1 

### ISSUE THREAD

**Issue by asith-w** [SharePoint/sp-dev-docs#7692]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version - SharePoint Framework v1.13.1 
- Node.js version -   v14.15.0
- etc

### Issue description

is it possible to fix npm warnings specially **chokidar** and **tslint**  while creating spfx extention/webparts ?
when I run **npm  install**  below warnings are showing for me 
```
npm WARN deprecated @types/anymatch@3.0.0: This is a stub types definition. anymatch provides its own type definitions, so you do not need this installed.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.1.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @opentelemetry/types@0.2.0: Package renamed to @opentelemetry/api, see https://github.com/open-telemetry/opentelemetry-js
npm WARN deprecated @angular/http@5.2.11: Package no longer supported. Use @angular/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
```
 
![image](https://user-images.githubusercontent.com/5784846/152537023-871152c7-ca21-4dc9-9fc1-e96453db3d22.png)

**Comment by AJIXuMuK** [comment]
Hi @asith-w - thank you for reaching out.
We do have plans to update the toolchain, specifically - move to eslint from tslint.
But the process is much more complicated than it seems.
You can check for [community articles](https://spblog.net/post/2020/12/22/sharepoint-framework-with-eslint) on how to use eslint with SPFx. In that case you can update the dependencies by yourself and remove the warnings (at least partially).

From our side - it is a work in progress.
