### ISSUE TITLE
AadHttpClient / MSGraphClient not working SharePoint Mobile App

### ISSUE THREAD

**Issue by bcameron1231** [SharePoint/sp-dev-docs#7694]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Issue is only happening in the SharePoint Mobile App. Works fine in all browsers, desktop and mobile.

### Describe the bug / error

I am using the aadHttpClient to access an Azure secured API (but have also noticed the Graph calls failing too) within the SharePoint Mobile app are not working. I get a generic error response "**Token request previously failed**" . Unfortunately, it's pretty difficult to debug the mobile app otherwise to figure out what the issue could be. 

Happy to take extra steps if you have any for me.

### Steps to reproduce

1. Create an SPFx Web part that uses the MSGraph Client or an aadHttpClient
2. Open the application in the SharePoint Mobile App
3. Web Parts will fail with error "Token request previously failed"

### Expected behavior

I expect the addHttpClient or msGraphClient to be able to be issued valid tokens to make calls to their respective endpoint.

**Comment by lucabandMSFT** [comment]
@bcameron1231 , can you check if the workaround mentioned on this issue solves your problem? #7646 

Keep in mind that you have to authenticate on SharePoint outside from the mobile app (any browser will work) in order to SharePoint Mobile to work.

**Comment by bcameron1231** [comment]
@lucabandMSFT  I did and it worked. Thank you.

**Comment by lucabandMSFT** [comment]
perfect, I'm going to close this issue then.
