### ISSUE TITLE
Question/Guidance : how to close QuickView on Button Submit Action.

### ISSUE THREAD

**Issue by siddharth-vaghasia** [SharePoint/sp-dev-docs#7695]
Need help in understanding how to close QuickView programmatically on submitting actions. Tried to use the quickViewNavigator.pop method though it is the only view opened in stack...  Still Quickview popup does not close until we click on the x mark?

` this.quickViewNavigator.pop();`

Replace is working fine... but what I was expecting is that the pop method should close the current Quickview on calling pop method, is the assumption correct... If so it is not happening and seems a bug. 

` this.quickViewNavigator.replace(SUBMITMESSAGE_REGISTRY_ID);`

SPFx version - 1.14.0-beta.4
 "@microsoft/sp-adaptive-card-extension-base": "1.14.0-beta.4",

Any help/insight is appreciated...!!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3f292b-a765-b991-94ed-2334a65e809f
* Version Independent ID: ca97f687-37d4-828d-1c15-c3f4b01f1446
* Content: [Advanced Quick View Functionality](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/advanced-quick-view-functionality)
* Content Source: [docs/spfx/viva/get-started/advanced-quick-view-functionality.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/get-started/advanced-quick-view-functionality.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by lucabandMSFT** [comment]
Hi @siddharth-vaghasia , did you look at the following documentation? https://docs.microsoft.com/en-us/javascript/api/sp-adaptive-card-extension-base/quickviewnavigator?view=sp-typescript-latest#@microsoft-sp-adaptive-card-extension-base-quickviewnavigator-close-member(1)

**Comment by siddharth-vaghasia** [comment]
@lucabandMSFT - thanks for the reply, and yes this worked...I think we should add this method to the actual usage documentation URL at... https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/viva/get-started/advanced-quick-view-functionality.md#viewnavigator

I am going to create PR for the same...

appreciate your help...
