### ISSUE TITLE
As a Admin we would need a PowerShell script to  prepare ACL and review the SharePoint sites on regular basis

### ISSUE THREAD

**Issue by Poooza** [SharePoint/sp-dev-docs#7697]
As a Admin we would need a PowerShell script to  prepare ACL  and review the sharepoint sites and the subsites on regular basis,
Kindly help

**Comment by VesaJuvonen** [comment]
@Poooza - can you be a bit more specific on the scenario and what are you trying to accomplish. Given the information you provided, there's simply not enough details on the objective and on your environment.

**Comment by Poooza** [comment]
> @Poooza - can you be a bit more specific on the scenario and what are you trying to accomplish. Given the information you provided, there's simply not enough details on the objective and on your environment.

Is there a way to get the users list who has the access to subfolders in an sharepoint site , need it for audit purpose

**Comment by Poooza** [comment]
> The more context details you can provide, the easier it is to help assist on issues. Any code you can provide and/or screenshots of the issue also help. The easier you can make it to reproduce the issue, the easier and quicker it is for someone to help you. Please refer to [How to Create Good Issues](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues), specifically [How to Create Good Issues: Include context](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Issues#include-context), in our wiki for more details.

How to get the users list who has the access to subfolders in an sharepoint site
