### ISSUE TITLE
Unable to load Field Customizer Extension 

### ISSUE THREAD

**Issue by Mukesh2085** [SharePoint/sp-dev-docs#7699]
Hello Everyone,

I was trying my first tutorial with Field Customizer using SPFx extension following instructions from below articles:

Content: [Build your first Field Customizer extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer)
Content Source: [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md)

I am receiving below error with Hello World setup

Fail to load customizer for column: ApplicationName,
                      componentId: 61c72fbb-2697-4669-a711-b53b9c47133f, error: Manifest not found for componentId "61c72fbb-2697-4669-a711-b53b9c47133f".

ApplicationName is the name of the list Column

I have followed below steps after running **yo @microsoft/sharepint command**:

- What is your solution name?: field-extension
- Will the components in the solution require permissions to access web APIs that are unique and not shared with other components in the tenant? (y/n) n
- Which type of client-side component to create?: Extension
- Which type of client-side extension to create? Field Customizer
- What is your Field Customizer name? HelloWorld
- What is your Field Customizer description? HelloWorld description
- Which framework would you like to use?: No JavaScript Framework
- 
After Extension is created I have made below changes to serve.json

{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "serveConfigurations": {
    "default": {
      "pageUrl": "https://contoso.sharepoint.com/sites/SPFx/Lists/Error%20Log/AllItems.aspx",
      "fieldCustomizers": {
        "ApplicationName": {
          "id": "61c72fbb-2697-4669-a711-b53b9c47133f",
          "properties": {
            "sampleText": "Value"
          }
        }
      }
    },
    "editField": {
      "pageUrl": "https://contoso.sharepoint.com/sites/SPFx/Lists/Error%20Log/AllItems.aspx",
      "fieldCustomizers": {
        "ApplicationName": {
          "id": "61c72fbb-2697-4669-a711-b53b9c47133f",
          "properties": {
            "sampleText": "Value"
          }
        }
      }
    }
  }
}

Current Node version: 10.23.0
npm version: 6.14.8
Gulp versions:
---------------------------
CLI version: 2.3.0
Local version: 3.9.1

Issue I am facing looks similar to one reported at below URL, But there is no fix mentioned in any of the comments:
 https://github.com/SharePoint/sp-dev-docs/issues/7629

Please let me know if further details are required regarding the setup steps.

Thank you in advance for looking into this.

Cheers,

Mukesh

**Comment by AJIXuMuK** [comment]
Hi @Mukesh2085 - most probably you just need to run `gulp trust-dev-cert`.
Also, what version of SPFx are you using?
You environment (node v10) is not the one we support in the latest versions.

**Comment by Mukesh2085** [comment]
Hello Alex,

Thank you for looking into this. Issue went away after I had deployed the package to app catalog, I was trying to  run it directly with Gulp Serve. I was still facing the issue with loading the code for debugging, But it started loading after I switched to another VM with same node setup.

Please consider this issue as closed.

Regards,

Mukesh
