### ISSUE TITLE
SPFX Webpart Throwing Multiple New Errors, Previously Working

### ISSUE THREAD

**Issue by katjones23** [SharePoint/sp-dev-docs#7702]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome version 98.0.4758.82, Edge version 98.0.1108.43
- SPFx version 1.12.1
- Node.js version 10.24.1

### Describe the bug / error

On Friday (Feb 4/22), my webpart was working as expected in SharePoint as well as in workbench; I believe it was working yesterday as well, but I did not access it.  Today (Feb 8/22), it does not load in workbench with only warnings in the console. 
 
![workbench](https://user-images.githubusercontent.com/53064219/153040234-18725bb8-a8ee-49d8-a1a5-6b0251990e42.png)
![workbenchConsole](https://user-images.githubusercontent.com/53064219/153040248-8a859092-6838-446e-8bae-1e1d4be0c5c3.png)

In our Staging site, it also does not load and includes errors in the console.  The errors start populating in the 'Site Pages' view, but are not always consistent.  Sometimes they show, sometimes only some show, sometimes none show.  

![stagingError1](https://user-images.githubusercontent.com/53064219/153040304-e790b7c2-0fbf-446d-8042-4fe2cfb1ccf1.png)
![stagingError2](https://user-images.githubusercontent.com/53064219/153040314-07a4c6d8-96a5-4f80-b3c5-09b2b27f8609.png)

I have not made any changes to the code since Friday.  Other webparts seem to be working as expected.

I also tested by running a sample project in the workbench, and the sample worked as expected.  The sample has mostly the same functionality as the actual webpart, except it does not make any calls to the SharePoint API.  All the packages are the same versions as the real project.

![packages](https://user-images.githubusercontent.com/53064219/153048243-6ec2314d-2d5f-4f27-a41a-37d92c61b4da.png)

### Steps to reproduce

Since I'm only seeing the issue with this one webpart, I am not sure the exact steps to reproduce.  Similar code without API is working, and other webparts that do include SharePoint API calls are working as well.  At this time, it appears attempting to run this one specific webpart in either workbench or a live site is the issue.

### Expected behavior

The webpart to display without issue.

**Comment by AJIXuMuK** [comment]
@katjones23 - as this is not happening with a brand new web part, I'd definitely look at configurations and custom code of your solution.
From the configuration standpoint, I see that you're using incorrect dependencies for `sp-build-web`, `sp-module-interfaces` and `sp-tslint-rules`. You should remove `^` to avoid installing the latest version instead of the needed one.

Another thing: I'm completely unfamiliar with `sp-pnp-js` library - what's that?

**Comment by katjones23** [comment]
@AJIXuMuK I believe `sp-pnp-js` may be an outdated PnP package that was copied as a reference to another project; it's not referenced in the code anywhere.  

I removed the `^` from the package names, but I had used npm shrinkwrap and double checked the package version before submitting this ticket.

Since the webpart was behaving as expected at the very latest as of Friday, and no changes have been made since then, I am wondering if there was a patch or anything made to SharePoint?  Unfortunately since none of the warnings or errors reference the custom code, I don't know where to look besides removing everything and adding it back line by line...everything in the config folder and package.json looks to be in order.

**Comment by AJIXuMuK** [comment]
@katjones23 - few questions: 
- are you using local or hosted workbench to test your solution?
- Can you share `serve.json` file content?
- When you see the errors on the Staging - are you seeing any custom requests to SharePoint in Network tab that are failing?
- Is the Staging environment enrolled in Target Release?

**Comment by katjones23** [comment]
> * are you using local or hosted workbench to test your solution?

Hosted workbench

> * Can you share `serve.json` file content?

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/core-build/serve.schema.json",
  "port": 4321,
  "https": true,
  "initialPage": "https://{company's sharepoint tenant}.sharepoint.com/_layouts/15/workbench.aspx",
  "api": {
    "port": 5432,
    "entryPath": "node_modules/@microsoft/sp-webpart-workbench/lib/api/"
  }
}
```

> * When you see the errors on the Staging - are you seeing any custom requests to SharePoint in Network tab that are failing?

The only thing that I see failing in the Network tab is "prompt.js", status '(canceled)' and initiated by playback.js:1
Everything initiated by my code returns status 200.

> * Is the Staging environment enrolled in Target Release?

It is not.

**Comment by AJIXuMuK** [comment]
Ok, so at least the web part is initialized and the custom code is running.

Are you using `displayLoadingIndicator` by any chance?
If you debug the code - is it trying to render the web part?

**Comment by katjones23** [comment]
We are not, but I added it in for testing in workbench.  It does hit the loading indicator in the .ts file, and when running debugger in VScode, I do hit the breakpoint for the render in the .tsx file.  The only error I'm seeing is this:

![image](https://user-images.githubusercontent.com/53064219/153075494-e7436cc5-0743-4e49-b5ae-fadb652d1cc4.png)

And workbench is stuck in this loop:

![image](https://user-images.githubusercontent.com/53064219/153075087-137c37bc-b956-45f8-ae8f-0ef7a106597d.png)

**Comment by katjones23** [comment]
@AJIXuMuK I figured out the issue: the code is currently set to just display an empty div if the length of data array is 0.  Since I didn't see any failed calls, I assumed the data was there, but in checking the list it comes from, it is currently empty.  Therefore, this was not a bug on the SPFX side.
