### ISSUE TITLE
Missing Application permission support for SharePoint ALM REST APIs

### ISSUE THREAD

**Issue by juliemturner** [SharePoint/sp-dev-docs#7709]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

N/A

### Issue description

In trying to implement CI/CD pipelines for SharePoint Framework solutions it appears that there is a security oversight from the perspective of the [ALM APIs](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest) and the fact that they are limited to delegated permissions only. 

Ideally you would want to implement a complete end to end pipeline for development, qa, staging, and production as an automated process through a CI/CD. With regards to the SharePoint framework to have that last step (of installing the package into the Site/Tenant App Catalog) you should be able to do so using application-level permissions with an app registration and proper authentication instead of using a username and password. Because it does not currently support it, the only workaround we have is to have a dedicated account that we then disable key security factors on (such as MFA) so that it can be used in this automated scenario. Although we can take steps to keep the password secure, this is often a barrier in organizations where security groups consider this too big a risk yet making this process manual has significant risks in and of itself.

Obviously I'm not sure how big of an effort this is but adding that ability feels like it would solve a lot of issues with the ALM story for the SharePoint Framework.

**Comment by GrahamMcMynn** [comment]
@juliemturner - as per other conversation off of github, you will need to use certficiate based auth in order to do this.
