### ISSUE TITLE
Issue with custom SPFx webparts calling Graph in MS Edge beta "Automatically sign in to sites with your current work..." setting

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#7711]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X ] 💥 Google Chrome
- [X ] 💥 FireFox
- [X ] 💥 Safari
- [X ] mobile (iOS/iPadOS)
- [X ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Version 100.0.1156.1 (Official build) dev (64-bit)
- SPFx version: 1.12.1
- Node.js version: 14.18.2

### Describe the bug / error

Custom SPFx webpart that are calling MS Graph API or a custom API secured by Azure AD are not working when browsing using MS Edge (dev/canary) versions with the new __"Automatically sign in to sites with your current work or school account"__:

![image](https://user-images.githubusercontent.com/9392197/153416438-94f0a64d-06d1-4e0b-9de3-c6d6a5974e0f.png)

Browser console errors:

![image](https://user-images.githubusercontent.com/9392197/153416504-47f466b5-95d0-4ffb-ad92-3a9282ccd26f.png)

If we disable the browser setting and clean cache, all works perfectly. Also works in non-beta MS Edge or when browsing InPrivate with beta/canary (makes sense, as InPrivate, the Automatic sign in is not fired.

### Steps to reproduce

1. Create an SPFx webpart that calls Graph API, and deploy it to your tenant
2. Open MS Edge beta/canary and ensure the setting "Automatically sign in to sites with your current work or school account" is enabled.
3. Add your custom webpart to any page

### Expected behavior

Webpart is loaded properly.

**Comment by luismanez** [comment]
hey @lucabandMSFT , thanks. Yeah, I can confirm both things. Besides, is happening in all tenants where we have installed our product, so pretty scared this browser setting goes to prod :)

Thanks again!

**Comment by luismanez** [comment]
Hi again @lucabandMSFT 

I can confirm the issue is easily reproduceable, you just need to create a “minimal” spfx webpart using Yeoman with the React option, and then just do any call to MS Graph or any custom API secured by AAD. Here is the code I placed in my webpart calling Graph:

https://gist.github.com/luismanez/af6b29f80a9421246c080168796982dc

Also, I think that I’ve __found the cause of the issue__. Fiddler to the rescue!. When the Edge beta setting "__Automatically sign in to sites with your current work or school account__" is __DISABLED__ and all works fine, I see a call to the AAD Authorize endpoint like:

```
https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
	?response_type=id_token%20token
	&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default%20openid%20profile
	&client_id=...
	&redirect_uri=https%3A%2F%2Fsambori.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx
	&state=eyJpZ...
	&nonce=874d3f78-e88a-485a-9ace-30e659de8c96
	&client_info=1
	&x-client-SKU=MSAL.JS
	&x-client-Ver=1.4.12
	&sid=bdd6117c-8...
	&client-request-id=c2ec6e5e-6fb0-4c8d-972a-aa77ea4d5444
	&prompt=none
	&response_mode=fragment
```

The response to this request, is 302, with a LOCATION header that looks like:

```
https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
	?response_type=id_token+token
	&scope=https%3a%2f%2fgraph.microsoft.com%2f.default+openid+profile
	&client_id=...
	&redirect_uri=https%3a%2f%2fsambori.sharepoint.com%2f_forms%2fspfxsinglesignon.aspx
	&state=eyJpZCI...
	&nonce=874d3f78-...
	&client_info=1
	&x-client-SKU=MSAL.JS
	&x-client-Ver=1.4.12
	&sid=bdd6117c...
	&client-request-id=c2ec6e5e-6fb0-4c8d-972a-aa77ea4d5444
	&prompt=none
	&response_mode=fragment
	&sso_nonce=AwABAAAAAA...
	&mscrid=c2ec6e...
```

Then, a request to that Location is sent (exactly GET request to that Location URL), and the response to that request, includes the AccessToken (as expected)

```
document.location.replace("https://{tenant}.sharepoint.com/_forms/spfxsinglesignon.aspx#access_token=eyJ0eXAiOiJKV1QiLCJ .....
```

Now, if you enable the setting (ensure you clean cache and re-open the browser), the first request-response is identical than when is working fine, however, when it does the second request, it has an extra __login_hint__ parameter:

```
https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize
	?response_type=id_token+token
	&scope=https%3a%2f%2fgraph.microsoft.com%2f.default+openid+profile
	&client_id=...
	&redirect_uri=https%3a%2f%2fsambori.sharepoint.com%2f_forms%2fspfxsinglesignon.aspx
	&state=eyJpZCI...
	&nonce=9e9f13b8-f...
	&client_info=1
	&x-client-SKU=MSAL.JS
	&x-client-Ver=1.4.12
	&sid=bdd6117c...
	&client-request-id=96455690-8cb7-46ff-bcd8-d28b36dc1df2
	&prompt=none
	&response_mode=fragment
	&sso_nonce=AwABAAAAAAACAOz...
	&mscrid=96455690-8cb7-46ff-bcd8-d28b36dc1df2
	&login_hint=admin%40tenant.onmicrosoft.com
```

In this case, the response is a big chunk of HTML (guess some error page), and I can see the following message in some JavaScript variable:

```
  AADSTS90138: Invalid ambiguous request. sid cannot be used with login_hint.
```

MSAL.js is unable to get the Token, so the call to MS Graph is not done.

My guess is that when the Edge beta setting is enabled, the browser intercepts some calls to the AAD Authorize endpoint, and “injects” the __login_hint__ parameter to make the “direct” login with the work account configured in the browser. However, the __login_hint__ is not compatible with the __SID__ param that is already added by __msal.js__

Seems clear to me. Please, let me know if you need any clarification (happy to have a call and show this to you, if that helps)

Thanks!

**Comment by lucabandMSFT** [comment]
just to provide an update here: we are in conversation with AAD and Edge team to understand the behavior and see where the problem is. We will provide further updates as soon as we get more details.

**Comment by lucabandMSFT** [comment]
Here're some additional news: looks like it's a misbehavior on Edge and the Edge team is pushing a fix in Edge canary. I will update the thread once again as soon as I know the Edge build number that contains the code change.

Stay tuned.. and thanks again for you help in catching those issues folks!

**Comment by lucabandMSFT** [comment]
Hey folks, latest from Edge team: The Canary 100.0.1168.0 will carry the fix.

@luismanez: let please us know when you have the opportunity to test it.

**Comment by luismanez** [comment]
Hey @lucabandMSFT , thanks. Unfortunately is still failing, although I can confirm now is doing a different request.

I´ve tested our product webparts that calls Graph or a custom API, and all are still failing.

I´ve tested a minimal SPFx webpart (v 1.14.0-rc.2) that just calls Graph (gist code posted in previous comment above) and also same issue.

This is what I see in the console:

![image](https://user-images.githubusercontent.com/9392197/154646208-a6e49cf7-e553-4d3c-ab60-6b702ab34ef9.png)

In Fiddler I see 2 requests to _login.microsoftonline.com_, both requests, are returning a 302 (moved) response.

If I grab the __location__ header of the first response, and place it directly into the browser, I get an Azure AD error page saying:

```
AADSTS9000411: The request is not properly formatted. The parameter 'login_hint' is duplicated.
```

and, yeah, in the browser address bar, I can see a URL with the _login_hint_ parameter repeated many times, with no value in all of them.

The second request, returns another 302 response, and here is the interesting part. If I grab the value of the __location__ header in the 302 response, and paste it directly to the browser (same tab where I was testing the spfx webpart), the browser redirects to the __spfxsinglesignon.aspx__ page, and I can see a perfectly valid Token in the fragment. However, that second response also contains some HTML code in the response body. It´s an _Object moved_ html like:

```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/authorize?response_type=id_token+token&amp;scope=97e52c24-4678-4416-b3bc-8a745c09af14%2f.default+openid+profile&amp;client_id={CLIENT_ID}&amp;redirect_uri=https%3a%2f%2fXXXXXXXX.sharepoint.com%2f_forms%2fspfxsinglesignon.aspx&amp;state=eyJpZCI6ImFkMTU4ZjE1LWQ0ZjAtNDNmOS04Yzg2LTE4NWExNDYwYzhiZSIsInRzIjoxNjQ1MTcxODk5LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&amp;nonce=68f8cc13-401e-475c-9f9a-67599b0f1814&amp;client_info=1&amp;x-client-SKU=MSAL.JS&amp;x-client-Ver=1.4.12&amp;sid=6ef565b8-0012-4125-a3a0-e67f107dddfb&amp;client-request-id=9816d659-7889-4ace-bdb1-f40e136b0d33&amp;prompt=none&amp;response_mode=fragment&amp;sso_nonce=AwABAAAAAAACAOz_BAD0_6v9HJR47R4JrYb0nozApjQCs_LQkRLm6xKLdywoPrH6_7iza9VSYjAZc_pEpcd5VR2LdVCKvsNMD-x4A_d_uc4gAA&amp;mscrid=9816d659-7889-4ace-bdb1-f40e136b0d33">here</a>.</h2>
</body></html>
```

If I grab the URL in the hyperlink object and paste it into the browser, I get another AAD error page saying the _client_id_ parameter is not present. I think the problem here is that the URL is encoded, and when paste it into the browser, is not able to decode it.

Hope it helps somehow.

Thanks.

**Comment by lucabandMSFT** [comment]
@luismanez, thanks. Edge team is working on a further fix.. I will communicate the build number once I have it.

**Comment by lucabandMSFT** [comment]
Hey folks, new day, new update: The Canary 100.0.1174.0 will carry the latest fix.

@luismanez: let please us know when you have the opportunity to test it.

Thanks for your help!

**Comment by luismanez** [comment]
Hi Luca,

I´ve opened MS Edge Canary and it has downloaded latest version. However, the Build number is not the one you mention (mine is 100.0.1169.0 and it says is up to date):

![image](https://user-images.githubusercontent.com/9392197/155346765-873efad7-bf47-46e6-8d5a-f0fe76472478.png)

Anyway, I´ve tested it in that new version, and same issue again. BTW, I´ve tried again to dissable the Setting, and then everything works as expected.

QUESTION: Would it help if I upload a repo with my minimal SPFx webpart, so the MS Edge team can test it? It´s really easy to create a new SPFx webpart and paste the code in my Gist to reproduce the issue.

I don´t know how can I help better. Will try to grab some Fiddler traces later.

Thanks.

**Comment by lucabandMSFT** [comment]
hey @luismanez, the fix is in the number I mentioned. Can you please check if the latest Canary build matches or it is higher than the number I provided and try again if the issue is resolved?

Thanks a lot for your help!

**Comment by luismanez** [comment]
Finally is fixed!!

I got this build today _Version 100.0.1176.0 (Official build) canary (64-bit)_ and is working fine with all my custom SPFx webparts calling any AAD Api / Graph.

Thanks to the teams involved, it´s been an interesting one! XD

**Comment by lucabandMSFT** [comment]
glad to hear that! thanks a lot for the engagement and the help here!!
