### ISSUE TITLE
Not able to create new action types for media and geolocation

### ISSUE THREAD

**Issue by anoopt** [SharePoint/sp-dev-docs#7714]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx version - 1.14 RC

## Not able to create new action types for media and geolocation

As per the [documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14?blog#new-action-types-for-media-and-geolocation) we should be able to create new action types for media and geolocation. However, those types (`VivaAction.ShowLocation`, `VivaAction.GetLocation` and `VivaAction.SelectMedia`) are not available to add in the code. Only the following shown are available.

![image](https://user-images.githubusercontent.com/9694225/153599644-da7e8876-714b-4ea8-a5ae-1ac8c4a05c64.png)

### Steps to reproduce

1. Create an SPFx ACE project of the type primary text card
2. In the QuickView.ts file try adding an action with a new type mentioned in the documentation

### Expected behavior

Should be able to see `VivaAction.ShowLocation`, `VivaAction.GetLocation` or `VivaAction.SelectMedia` as one of the type options for an action.

**Comment by lucabandMSFT** [comment]
thanks @anoopt. Looks like one of the flights is still rolling. I will update this issue mid next week when the code has reached 100% production.

**Comment by anoopt** [comment]
Thank you @lucabandMSFT

**Comment by lucabandMSFT** [comment]
Thanks @anoopt . I'm closing the issue as it is resolved now.
