### ISSUE TITLE
Dialog.alert() not working with SPFx v1.4.1 like described in #1381

### ISSUE THREAD

**Issue by Pronizius** [SharePoint/sp-dev-docs#7721]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge (98.0.1108.50), Chrome (97.0.4692.99), IE 11, Firefox (91.6.0esr)
- SPFx version: 1.4.1
- Node.js version: 10.24.1
- etc

### Describe the bug / error

Everything can be found in the closed issue [#1381](https://github.com/SharePoint/sp-dev-docs/issues/1381).

We are currently developing solutions for SharePoint Server Subscription Edition (only SPFx 1.4.1 supported), so we can not upgrade to a fix.

Was this problem ever fixed for 1.4.1, because On Premise we have no option to upgrade to a higher version and it is really hard and time consuming to develop when the solution must be each time deployed first.

Workarounds are not working (renaming URL Parameter loadSPFX to loadSpfx)

### Steps to reproduce

1. Create an On Premise Listview Command Set (SPFx 1.4.1)
2. gulp serve
3. The buttons do not display if Dialog.alert is used in the onExecute function. With plain javascript alert debug is working.

Like above everything can be found in [#1381](https://github.com/SharePoint/sp-dev-docs/issues/1381)

### Expected behavior

Buttons should show up and Dialog should work, like it does as soon as the solution is deployed, only in debug (gulp serve) it is not working.

**Comment by AJIXuMuK** [comment]
Hi @Pronizius - unfortunately, we're unable to fix previous versions.
So the fixes that were made are included either in the next release, or in the SharePoint Online (in that case hosted workbench).
If it doesn't work in the workbench only - I would recommend to install your debug solution on a single site collection (or local single farm installation) and test there.

**Comment by Pronizius** [comment]
I understand, can you confirm, that then I cannot use gulp serve and make changes in typescript without rebuilding and deploying the whole solution (sppkg file)?
Thank you

**Comment by AJIXuMuK** [comment]
@Pronizius - you should be able to deploy "debug" package, using
```bash
gulp bundle
gulp package
```

Then, you can deploy this package, run `gulp serve --nobrowser`, and this package will be loading files from your localhost.

**Comment by AJIXuMuK** [comment]
@Pronizius - yes, updated the comment, sorry.

> And what are the limitations, after what changes i must again call for gulp bundle and gulp package-solution? I.e. when I add files or change the json files etc.?

If you change any configuration files (`json` or `gulpfile.js`) or add some static assets.
If you modify code - it should serve the latest automatically.

**Comment by Pronizius** [comment]
@AJIXuMuK - Ok I understand, so the --nobrowser loads parts from the local package.
Thank you very much for your time, no need to apologies. You were very helpful!
