### ISSUE TITLE
Sharepoint online overrides jQuery

### ISSUE THREAD

**Issue by SwagiWagi** [SharePoint/sp-dev-docs#7727]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 98.0.4758.102
- SPFx version 1.13.1
- Node.js version 14.5.0
- etc

### Describe the bug / error

When including jQuery1.12.0, it looks like SharePoint overrides the $ and jQuery variables.

### Steps to reproduce

1. Create a new web part using the yeoman generator
2. Add the jQuery import
3. gulp serve
4. Test the variables in the console

### Expected behavior

Not to be overriden

**Comment by AJIXuMuK** [comment]
Hi @SwagiWagi - thanks for reporting this.
jQuery is included in the browser console by default. It is not something SharePoint adds.
So, nothing we can do here.

BTW, v1 of jQuery is really old. I would not recommend using it in any production environment. You need to update to v3.

**Comment by SwagiWagi** [comment]
Thanks for the answer @AJIXuMuK.
This is a big system written with jQuery v1 so unfortunately, I can't update it.
However, my main problem is that I can't manage to load bootstrap-select or any other functions of jquery, if I load jquery 1.12.0 on a standalone HTML file with bootstrap and bootstrap-select, there is no problem and I have all the functions, unlike on the teams, which I don't.
![image](https://user-images.githubusercontent.com/19839556/155879132-9e846b0d-2fc5-4265-8b66-221df10daefa.png)

**Comment by AJIXuMuK** [comment]
Well, I can only suggest to use no-conflict option when loading jQuery. 
But again - SharePoint code doesn't have a dependency on jQuery.
