### ISSUE TITLE
Would love a very very simple example for beginners to start from when customizing the gallery view

### ISSUE THREAD

**Issue by ttmarquardt** [SharePoint/sp-dev-docs#7728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0418afd-8cac-114b-dbfe-07010da2b86a
* Version Independent ID: d0418afd-8cac-114b-dbfe-07010da2b86a
* Content: [Format gallery view to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-gallery-formatting)
* Content Source: [docs/declarative-customization/view-gallery-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-gallery-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by shagra-ms** [comment]
Thanks @ttmarquardt for reaching out. Please do share more about what exactly you are looking for in a simple example. 

We currently have a [custom card](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-gallery-formatting#build-custom-cards) example, which demonstrates how a small gallery card can be created using multiple fields and formatter JSON.

Another way to get started is to use the Card Designer, and then switch to 'Advanced Mode' to customize the JSON.
![image](https://user-images.githubusercontent.com/37994247/157051578-ff40daf0-31c8-4093-a736-e71b1623773a.png)
![image](https://user-images.githubusercontent.com/37994247/157051786-0b0a9443-9c42-45b9-81b0-d2f670935568.png)

If you are looking to get comfortable with JSON formatter, I would recommend you try out [HTML to JSON tool](https://pnp.github.io/List-Formatting/tools/)
