### ISSUE TITLE
v1.14 of the SPFx Generator released today without Node 16 support

### ISSUE THREAD

**Issue by rslavey** [SharePoint/sp-dev-docs#7729]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Microsoft Edge Version 98.0.1108.55 (Official build) (64-bit)
- SPFx version: 1.14
- Node.js version: 16

### Issue description

Per https://github.com/SharePoint/sp-dev-docs/issues/7478, it was indicated that they would look into supporting node 16 in 1.14. As 1.14 was released today, still without node 16 support, I am wondering where this is on the roadmap. When will the SPFx generator support node 16?

**Comment by AJIXuMuK** [comment]
@rslavey - unfortunately, it takes longer than we expected for various reasons.
We will announce the support as soon as it will be baked in the SPFx.
