### ISSUE TITLE
Error in your helloworld code

### ISSUE THREAD

**Issue by tonydiep** [SharePoint/sp-dev-docs#7730]
this code does not build because test is not a property

          <p class="${ styles.description }">${escape(this.properties.test)}</p>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by tonydiep** [comment]
I see what's going on the Yeoman generator just got updated and your spfx tutorial is inconsistent. Some pages are based on the helloworld from the ld generator. Some pages are based on the new helloworld. This makes me question whether I should use spfx.

**Comment by VesaJuvonen** [comment]
Of course our documentation and tutorials should be up to date. We just released SharePoint Framework 1.14 with updated tutorials. We will renew the videos also within upcoming weeks to ensure that they are showing the updated experience, but there's no excuses for the code in the basic tutorials not working...

We'll jump on testing and validating this right now and fix any issues asap.
