### ISSUE TITLE
SPFx ACE : Value of "this.context.deviceContext" incorrect in Teams desktop

### ISSUE THREAD

**Issue by anoopt** [SharePoint/sp-dev-docs#7732]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams desktop app

### Describe the bug / error

While developing ACEs, we can get to know the device context using `this.context.deviceContext`.

The value of that should one of `WebView`, `Mobile` or `TeamsDesktop` based on where we access the ACE from.

This property gives the correct output when in browser (`WebView`) or in Teams mobile app (`Mobile`).

However, in Teams desktop app the value is `WebView` whereas, it should be `TeamsDesktop`.

![image](https://user-images.githubusercontent.com/9694225/154682131-8565b089-4603-4c69-adb8-c0f96dc998e6.png)

### Steps to reproduce

1. Create an ACE using SPFx
2. In the onInit method alert the property `this.context.deviceContext`
3. Open the ACE in Teams desktop app

### Expected behavior

In Teams desktop app the value of `this.context.deviceContext` should be `TeamsDesktop`.

**Comment by lucabandMSFT** [comment]
@anoopt , sorry for our delay in answering. We indeed had some issues in our code that was reporting incorrect information but that should now have been fixed. Can you please check and see if the issue still exists?

**Comment by anoopt** [comment]
Thank you @lucabandMSFT - Tested this with SPFx `1.15.0-beta.1`, the value is correct on the initial load however if you navigate to a different area in Teams and open the Viva connections app, the value shows as `WebView` again.

![2022-03-18_18-58-56](https://user-images.githubusercontent.com/9694225/159067578-6f4cad2a-4035-4cd9-a440-8ae175401b61.gif)

**Comment by lucabandMSFT** [comment]
Thanks you @anoopt , looking on the issue now. Also, one question. The "Viva Connections" app you are using is the one that comes out of the box from Teams app, right? it is **not** this one: https://docs.microsoft.com/en-us/sharepoint/viva-connections-desktop

**Comment by AJIXuMuK** [comment]
@anoopt - could you please reply to the Luca's question?
Thanks!

**Comment by anoopt** [comment]
Sorry for the delayed response yes, I am using the "Viva Connections" that comes out of the box from Teams app.

**Comment by lucabandMSFT** [comment]
@anoopt, thanks. And, to be clear, the issue is happening right now as well? Can you please confirm it?

**Comment by anoopt** [comment]
Sure @lucabandMSFT will test with the latest SPFx version and let you know.

**Comment by AJIXuMuK** [comment]
@anoopt - were you able to check if the issue is still repro-ed?

**Comment by anoopt** [comment]
Sorry for the delay in getting back. This can now be closed.
