### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by Clizarazu** [SharePoint/sp-dev-docs#7734]
I think the second paragraph should read as 
"The commands use CSOM and can work against ~~both~~ SharePoint Online ~~as~~ **and** SharePoint On-Premises."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f0bf18-5ece-8fac-f602-17500085ad26
* Version Independent ID: 087cf5a1-6c1e-1f19-b3c1-d1e661092fb3
* Content: [SharePoint Developer Community (SharePoint PnP) resources](https://docs.microsoft.com/en-us/sharepoint/dev/community/community)
* Content Source: [docs/community/community.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/community/community.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Closing as fixed - thx @bcameron1231 and @Clizarazu  👏
