### ISSUE TITLE
ACE, CardView/QuickView markdown support on mobile

### ISSUE THREAD

**Issue by Mikhail2k15** [SharePoint/sp-dev-docs#7735]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.13.1
- Node.js version
- etc

### Describe the bug / error

Looks like the tables, images in the markdown are not supported on mobile in a card view.

### Steps to reproduce

1. Install this sample https://github.com/pnp/sp-dev-fx-aces/blob/64c0313f8492532f846f7a3556dc9848c4fdff0e/samples/PrimaryTextCard-Covid-Indicator/src/cards/cardView/CardView.ts#L18
2. It will look great on Web, Desktop Teams client, but will not render on both mobile clients 

Session Id:385644e3-e250-4bc0-85e0-ce0032cff08e
Teams Build:1.076.2022032001
App Version:0.2.202202100137-release-vcm-FebT1
User Ring:general
SDK Version:0.9.0

### Expected behavior

![image](https://user-images.githubusercontent.com/11201670/154842122-bc2c67f7-d111-4294-a255-68bebf369d19.png)
ios/android
![image](https://user-images.githubusercontent.com/11201670/154842136-62e5bb20-96b4-49d9-92f1-9748ef930648.png)

A similar issue on QuickView is here https://github.com/pnp/sp-dev-fx-aces/issues/43

**Comment by Mikhail2k15** [comment]
Do we have the documentations which tags in markdown we do support on CardView and Quick View?

**Comment by lucabandMSFT** [comment]
hey @Mikhail2k15, this is currently unsupported. Cards only support specific card views and it looks like what you are trying to do is to create your own card view. While this might work in the web, that's not working on the Mobile as the mobile enforces the view itself.
