### ISSUE TITLE
Sample doesn't match tutorial

### ISSUE THREAD

**Issue by PathToSharePoint** [SharePoint/sp-dev-docs#7736]
Hello,

It seems to me that the tutorial was completely revamped recently, and the sample is not a proper match anymore. I did not touch the page as there might be a more appropriate sample I am not aware of. For the record, I am using a similar technique for a sample I am about to publish.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8fe85ee-ede7-1cac-d524-d448051dfc45
* Version Independent ID: 1ee793b9-d693-4967-988f-53c3657b5970
* Content: [Use cascading dropdowns in web part properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties)
* Content Source: [docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by PathToSharePoint** [comment]
While I'm on that page: the following line doesn't seem to reset the dropdown:
`this.properties.itemName = undefined;`

What I am using in my sample seems to work better:
`this.properties.itemName = "";`

**Comment by andrewconnell** [comment]
It was only updated to reflect the new templates included in SPFx v1.14: https://github.com/SharePoint/sp-dev-docs/commit/161eec33d62a8025cb333e1b946dacf2a66cea87#diff-129294ae3b89de8595a9cfc3fbd89e54e76bd30d1e7f688c2b055846382f9837

Looks like the same was changed to include things not directly related to the doc.

**Comment by PathToSharePoint** [comment]
oh I see what I missed. The sample includes both the old guidance (custom control) and the new one,. I didn't dig deep enough and stopped at the custom control file, which is now irrelevant for the guidance itself.

![image](https://user-images.githubusercontent.com/40323257/155174851-2a451d94-e7ed-4234-b2b2-7530faf11ddd.png)

How about the `selectedKey`? Isn't it a property that should be used to set the dropdown value when the Property Pane opens?

![image](https://user-images.githubusercontent.com/40323257/155175896-18d064e8-f312-406b-abb7-58a4b030182f.png)

**Comment by andrewconnell** [comment]
I'm going to close this issue, as there's nothing wrong with the docs from what I can see. The samples aren't kept current as much as the docs are. So... if there's an issue with the sample, then it should be filed on that repo.

**Comment by PathToSharePoint** [comment]
@andrewconnell to clarify, my second screenshot is from the docs, not from the samples.
