### ISSUE TITLE
Unit Testing with Jest throws an error related to the module @microsoft/sp-webpart-base

### ISSUE THREAD

**Issue by v-prigunasek** [SharePoint/sp-dev-docs#7737]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx version - 1.13.0
Node.js version - 14.18.2
React version - 17.0.2

### Describe the bug / error

Getting below error while running the unit test.

 FAIL  src/webparts/home/unit-tests/organization/NewOrganizationAssessment.test.tsx
  ● Test suite failed to run

    Cannot find module './core/BaseWebPartContext' from 'node_modules/@microsoft/sp-webpart-base/lib-commonjs/index.js'

    Require stack:
      node_modules/@microsoft/sp-webpart-base/lib-commonjs/index.js
      src/webparts/home/unit-tests/organization/NewOrganizationAssessment.test.tsx

      at Resolver.resolveModule (node_modules/jest/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@microsoft/sp-webpart-base/lib-commonjs/index.js:15:28)

### Steps to reproduce

Below are the configurations I have.

**package.json:**

{
  "name": "test-site-survey",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "jest",
    "preinstall": "npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions"
  },
  "dependencies": {
    "@fluentui/react": "^8.35.2",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@microsoft/sp-office-ui-fabric-core": "1.12.1",
    "@microsoft/sp-property-pane": "1.12.1",
    "@microsoft/sp-webpart-base": "1.12.1",
    "@pnp/sp": "^2.8.0",
    "@pnp/sp-commonjs": "^2.12.0",
    "bootstrap": "^5.1.1",
    "node-fetch": "^2.6.7",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-bootstrap": "^1.6.3",
    "react-csv": "^2.0.3",
    "react-dom": "16.9.0",
    "react-reactstrap-pagination": "^2.0.3",
    "react-router-dom": "^5.3.0",
    "reactstrap": "^8.10.0",
    "tslint-microsoft-contrib": "^6.2.0",
    "xlsx": "^0.17.4"
  },
  "resolutions": {
    "node-fetch": "2.6.7"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.8": "^0.4.47",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@types/enzyme": "3.10.11",
    "@types/enzyme-adapter-react-16": "1.0.6",
    "@types/enzyme-to-json": "1.5.4",
    "@types/jest": "27.4.0",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/react-test-renderer": "17.0.1",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "gulp": "~4.0.2",
    "identity-obj-proxy": "3.0.0",
    "jest": "26.6.3",
    "jest-junit": "13.0.0",
    "react-test-renderer": "17.0.2",
    "ts-jest": "26.5.5",
    "tslint": "^6.1.3",
    "tslint-microsoft-contrib": "^6.2.0",
    "typescript": "^4.4.3"
  },
  "jest": {
    "verbose": true,
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest"
    },
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx|js)"
    ],
    "coverageDirectory": "<rootDir>/jest",
    "collectCoverage": true,
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/jest-config/file-mock.js",
      "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1",
      "@fluentui/react/lib/(.*)$": "@fluentui/react/lib-commonjs/$1",
      "@pnp/sp$": "@pnp/sp-commonjs", 
      "@pnp/sp/(.*)$": "@pnp/sp-commonjs/$1"
    },
    "setupFilesAfterEnv": [
      "<rootDir>/jest-config/jest-setup.ts"
    ]
  }
}

**tsconfig.json**

{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-3.8/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule":true,
    "esModuleInterop": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env",
      "jest",
      "@types/jest"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection",
      "es2015.promise",
      "es2017"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"    
  ]
}

**Error occurs while instantiating the context object on the test component. (NewOrganizationAssessment.test.tsx)**

import React, { SetStateAction, useState } from 'react';
import { mount, ReactWrapper } from 'enzyme';
import NewOrganizationAssessment from '../../components/organization/NewOrganizationAssessment';
import {INewOrganizationAssessmentProps} from '../../components/organization/NewOrganizationAssessment';
import {WebPartContext } from "@microsoft/sp-webpart-base";

describe('Organization Component : New Organization Assessment', () => {
    let wrapper: ReactWrapper<INewOrganizationAssessmentProps, {}>;
    const useStateMock = jest.spyOn(React, 'useState');
    wrapper = mount(React.createElement(
        NewOrganizationAssessment, { context: **_new WebPartContext()_** }
    ));

I have also tried npm install jest @voitanos/jest-preset-spfx-react16 --save-dev but that didnt fix the error.

Tried updating different versions of spfx in package.json and getting different error for each version.
**For 1.11.0**
![image](https://user-images.githubusercontent.com/98514691/154933243-534c8e6c-d22c-447d-afa6-5cfeb6ac4f5b.png)

**For 1.13.0**
![image](https://user-images.githubusercontent.com/98514691/154933118-190e2e03-05ab-4c07-911a-e7eae01096a1.png)

Please let me know if I'm missing any configuration.

### Expected behavior

Tests should pass without any error

**Comment by zounasL** [comment]
Spfx is not very unit tests friendly. Try to mock the @microsoft/sp-webpart-base or maybe try to use  identity-obj-proxy for it.

**Comment by AJIXuMuK** [comment]
@v-prigunasek - thanks for reporting this issue.
I will try to be as descriptive as possible here.
For the xml module issue - you can solve it.
You will need a custom transformer, something like
```javascript
const path = require('path');

module.exports = {
  process(src, filename, config, options) {
    return `module.exports = ${JSON.stringify(path.basename(filename)) };`;
  },
};
```

and jest config:
```json
"moduleNameMapper": {
    "\\.resx$": "<rootDir>/resxTransformer.js"
  },
```

But it will not allow you to test though: call to the `WebPartContext` constructor will lead to imports of some internal modules that are not installed in the solution and are not available in the npm.
So, you can either mock the entire `@microsoft/sp-webpart-base` as @zounasL proposed, or you can mock the context object itself.

Hope this helps.
