### ISSUE TITLE
Can't get passed yo @microsoft/sharepoint. Failed with exit code1: npm install

### ISSUE THREAD

**Issue by aidab98** [SharePoint/sp-dev-docs#7738]
Hi everyone!

I'm still new in this; however, I am attempting to scaffold an adaptive card extension for Viva. 
I've installed all the requirements needed to start a new project. 
When I run the command yo @microsoft/sharepoint and after specifying the details, it ends with error.
I'm attaching the error and npm list -g --depth=0.
Please let me know what is the issue here.

├── @microsoft/generator-sharepoint@1.14.0
├── @pnp/cli-microsoft365@3.10.0
├── generator-botbuilder@4.15.0
├── gulp-cli@2.3.0
├── gulp@4.0.2
├── npm@7.19.0
├── windows-build-tools@5.2.2
└── yo@4.3.0

   create package.json
    force .yo-rc.json
   create config\package-solution.json
   create config\config.json
   create config\serve.json
   create tsconfig.json
   create .vscode\launch.json
   create .vscode\settings.json
   create config\deploy-azure-storage.json
   create config\write-manifests.json
   create src\index.ts
   create gulpfile.js
   create README.md
   create tslint.json
   create .gitignore
   create .npmignore
   create src\adaptiveCardExtensions\helloworld\quickView\template\QuickViewTemplate.json
   create src\adaptiveCardExtensions\helloworld\quickView\QuickView.ts
   create src\adaptiveCardExtensions\helloworld\HelloworldAdaptiveCardExtension.ts
   create src\adaptiveCardExtensions\helloworld\HelloworldPropertyPane.ts
   create src\adaptiveCardExtensions\helloworld\assets\MicrosoftLogo.png
   create src\adaptiveCardExtensions\helloworld\assets\SharePointLogo.svg
   create src\adaptiveCardExtensions\helloworld\loc\en-us.js
   create src\adaptiveCardExtensions\helloworld\loc\mystring.d.ts
   create src\adaptiveCardExtensions\helloworld\cardView\CardView.ts
   create src\adaptiveCardExtensions\helloworld\HelloworldAdaptiveCardExtension.manifest.json

Changes to package.json were detected.

Running npm install for you to install the required dependencies.
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: webpack@4.44.2
npm WARN node_modules/webpack
npm WARN   webpack@"~4.44.2" from @microsoft/sp-build-web@1.14.0
npm WARN   node_modules/@microsoft/sp-build-web
npm WARN     dev @microsoft/sp-build-web@"1.14.0" from the root project
npm WARN   7 more (@microsoft/gulp-core-build-webpack, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional webpack@"^5.35.1" from @rushstack/set-webpack-public-path-plugin@3.3.12
npm WARN node_modules/@rushstack/set-webpack-public-path-plugin
npm WARN   @rushstack/set-webpack-public-path-plugin@"3.3.12" from @microsoft/spfx-heft-plugins@1.14.0
npm WARN   node_modules/@microsoft/spfx-heft-plugins
npm WARN   1 more (@rushstack/localization-plugin)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: acorn@7.4.1
npm ERR! node_modules/acorn
npm ERR!   acorn@"^7.4.0" from espree@7.3.1
npm ERR!   node_modules/espree
npm ERR!     espree@"^7.3.0" from eslint@7.12.1
npm ERR!     node_modules/eslint
npm ERR!       eslint@"~7.12.1" from @microsoft/rush-stack-compiler-3.9@0.4.47
npm ERR!       node_modules/@microsoft/rush-stack-compiler-3.9
npm ERR!         dev @microsoft/rush-stack-compiler-3.9@"0.4.47" from the root project
npm ERR!       10 more (@rushstack/eslint-config, @rushstack/eslint-plugin, ...)
npm ERR!     espree@"^7.3.0" from @eslint/eslintrc@0.2.2
**Command failed with exit code 1: npm install**

**Comment by AJIXuMuK** [comment]
Few additional things to check:
- do you have any custom nmp repos configured (custom `.npmrc`)?
- we're not officially supporting npm v7 yet.

**Comment by aidab98** [comment]
My node version is v14.15.0.

I've installed al the requirements following the documentations. How do I know if I have custom npm repos configured? Which version of npm is supported, and how do I install another version of npm instead of v7?

Thank you.

**Comment by aidab98** [comment]
So I've installed npm v6 and now the scaffold is working. Thank you @AJIXuMuK for pointing out the version point.
