### ISSUE TITLE
SPFX Fabric Callout control, not rendering dynamic content.

### ISSUE THREAD

**Issue by pljfdi** [SharePoint/sp-dev-docs#774]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Using a Callout control from fabric with dynamic content. I expect the callout to display the dynamic content. 

#### Observed Behavior
Only static/compile time content is returned

#### Steps to Reproduce
Use a Callout  in a tsx and mix both static and dynamic content 
In the below snippet, the content of `words` (except the div) is never displayed.
If I use Words as part of my control (render) it works fine.
The rest of `wordMuncher` will be displayed fine.
```
        var words = <div>{_(this.state.foundWords).map(itm => {
                        return <div key={itm.Id}>
                            <CompoundButton id={itm.Id} onClick={this.OnWordClick} disabled={false}>
                                {itm.Value}
                            </CompoundButton>
                        </div>
                    })}</div>

        var wordMuncher = <div className="ms-Callout-inner">
            <div className="ms-Callout-content">
                <ul>
                    <li><h1>Static</h1></li>
                    <li>{words}</li>
                </ul>
            </div>
        </div>
        return wordMuncher;
```

**Comment by patmill** [comment]
I believe this is more of a question for OUIFR - https://github.com/OfficeDev/office-ui-fabric-react/issues.  If not, feel free to reopen the issue.
