### ISSUE TITLE
SharePoint Search Api doesn't always return canvas content field

### ISSUE THREAD

**Issue by zounasL** [SharePoint/sp-dev-docs#7741]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

The issue is related to the API and not the platform itself.

### Describe the bug / error

When calling **_api/search/postquery** endpoint it sometimes doesn't return page Canvas Content field ( null ). I believe there might be some kind of property indexing bug in SharePoint, because if i edit and republish the page it might start to return the Canvas content field in the response or other way around, It start to return empty canvas content for the pages where it previously returned it correctly. I am facing this issue in couple of our tenants.

Or another possible option for this might be that during endpoint call the api fails to crawl/bind the properties if it require heavier processing? I mean if i reduce amount of **"SelectProperties"** in the query it also might help to return the canvas content field, but this behaviour is very random.

Example POST query payload to **_api/search/postquery** 
```json
{
    "request": {
        "__metadata": {
            "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
        },
        "Querytext": "Path:https://{MyTenant}.sharepoint.com/sites/{MySite}/sitepages/{page}.aspx",
        "RowLimit": 10,
        "StartRow": 0,
        "ClientType": "ContentSearchRegular",
        "SelectProperties": {
            "results": [
                "ContentTypeId",
                "Title",
                "PictureThumbnailURL",
                "PromotedState",
                "CreatedBy",
                "LayoutWebpartsContentOWSHTML",
                "CanvasContent1OWSHTML"
            ]
        },
        "HitHighlightedProperties": {
            "results": []
        },
        "Properties": {
            "results": []
        },
        "RefinementFilters": {
            "results": []
        },
        "ReorderingRules": {
            "results": []
        },
        "SortList": {
            "results": []
        }
    }
}
```

What the Search Api is sometimes returning:
```json
{
    "__metadata": {
        "type": "SP.KeyValue"
    },
    "Key": "CanvasContent1OWSHTML",
    "Value": null,
    "ValueType": "Null"
}
```

### Steps to reproduce

1. Create a page in SharePoint
2. Call the **_api/search/postquery** and make sure you are adding **CanvasContent1OWSHTML** in the "SelectProperties" property. Example use Postman or SP Editor for this.
3. Check the response
4. Canvas Content value might not be returned 

### Expected behavior

Return HTML canvas content when requesting _**CanvasContent1OWSHTML**_ property

**Comment by bcameron1231** [comment]
Can you check your Search Schema managed properties? Last I checked, CanvasContent1OWSHTML doesn't have a crawled property mapped to it. Did you update this managed property to include the ows_CanvasContent1 crawled property?

**Comment by zounasL** [comment]
Unfortunately it didn't seems to help. Still it doesn't map correctly the Canvas content and often just return null value.

**Comment by zounasL** [comment]
Any info about this?

@AJIXuMuK

**Comment by wobba** [comment]
I largely recommend not to change mapping on OOB or automatically created managed properties. Even if the schema don't show a mapping, it doesn't mean it's not there for properties created by the system as this is a caching optimization.

**Comment by zounasL** [comment]
Yo @wobba 

Got a response from MS support and they are saying that the canvas content property will not be auto generated if page size is over 30 KB. Is it actually how this works and if so is there any workaround to this?

_"The automatically generated managed property "CanvasContent1OWSHTML" is only filled for pages that are smaller than 30 KB"_

**Comment by wobba** [comment]
You can read about limitation for managed properties at https://docs.microsoft.com/en-us/sharepoint/search-limits (not sure if they are updated).

Microsoft can decide on how to parse and store out of the box data/properties to optimize for search scenarios, and there's no real end-user search scenario which validates to load up the entire CanvasContent1. Switch API's and use SharePoint item API's instead to load the data.
