### ISSUE TITLE
SharePoint SP.Oauth.NativeClient endpoint limitation

### ISSUE THREAD

**Issue by zounasL** [SharePoint/sp-dev-docs#7743]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Platform: Android, iOS, Native client etc.

### Issue description

What i am trying to do is to get access token to SharePoint SP Oauth NativeClient resource. Even if i add all possible SP permission to the AD app it still can't generate token which have permission to call _api/SP.Oauth.NativeClient/Authenticate endpoint. Token is generated by using Oauth2 login flow.

What we are trying to accomplish is to have a seamless SSO type of functionality for a users in our application which use our own AD app.

I also tested with Teams/SP mobile app client ids and those were able to call that endpoint. Even if i replicated the permissions to my own AD app i still wasn't able to get the cookie. It always return 403 (Forbidden).

Is this endpoint artificially blocked or something? In theory it feels like that the SP has some kind of "allowed" client id list which it use to check will it allow to call this SP endpoint? If so, is there a way to add my own AD app id to this list so i can use the endpoint on my own tenant or any another option to get the spoidcrl cookie?

If this is blocked by design i would like to know what is the reason for this other than preventing SP connection from external applications? It seems that all of the MS native applications are using this method to get SP Online Active Authentication Cookie.

One workaround for this on mobile platforms is that during login i do double authentication to my AD app and one of the MS application which have permission to call this. How this work is that i open normal login flow in web view and do normal authentication to my AD app. After this i request another Oauth login flow in same web view for example Teams mobile app client id and get the access token which have permission to call the SP.OAuth.NativeClient endpoint. This method doesn't require double authentication because the web view already have the "ESTSAUTHPERSISTENT" cookie (or what ever cookie it need) which it use to authenticate me without any credentials. Although this method can be annoying and little bit hacky in some cases.

**Comment by lucabandMSFT** [comment]
hey @zounasL , thanks for reaching out.
What you are experience is right now by design: that is an internal API that we reserve for internal use. Currently that API can only be called by the following clients:
* Microsoft Teams Rich Client
* Microsoft Teams Mobile
* Microsoft SharePoint Mobile app

There are no current plans to extend the access to that API further; primarily because we are on a path to move out from cookie out in the future (no timeline confirmed yet) and we don't want 3rd party apps to take dependencies on a flow that's going to be removed.

Thanks
