### ISSUE TITLE
SPComponentLoader.loadComponentById() is not working and fails while reading isInternal property

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#7747]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Chrome 98.0.4758.102 (64bit)
- SPFx version: 1.9.1 & 1.10
- Node.js version: 10 
- gulp version: 3.9.1

### Describe the bug / error

SharePoint Framework Application Extension tries to load Library component using SPComponentLoader.loadComponentById(). It is failing to load the library component. We see the following error in the console: ![image](https://user-images.githubusercontent.com/12812202/155223008-a5769950-ea0a-48e3-9f0a-e18f9d300496.png)

This was working fine until last 2 days in our Tenant. It's not working any more. We cleared the cached and tested different machines. It's same result with same error. Could you please share your updates?

### Steps to reproduce

1. Try to load a library component by its id from another component (application extension in my case) using SPComponentLoader.loadComponentById(). 
2. When Application Extension loads, it fails immediately while loading library component.

### Expected behavior

Expected to load the library component using SPComponentLoader.loadComponentById() without issues.

**Comment by AJIXuMuK** [comment]
@arunakshi  - thanks for reporting this one!
Could you please provide some info:
- what type of component are you trying to load (web part, application customizer, something else)?
- Is your solution deployed to tenant or site collection app catalog?
- Is the solution globally deployed or added to some specific site collections?
- Could you check Network tab of the browser, find request to `_api/web/GetClientSideComponents` with your component id in the body and check the result? Do you see your component in there? What do you see in `Manifest` property?

**Comment by arunakshi** [comment]
@AJIXuMuK, please find my below reply and findings.

- We are trying to load a Fluent UI Panel react component in library component (from application customizer and webpart)
- Both the application customizer and library component are deployed in tenant app catalog
- Library component is deployed globally and application customizer added as app to site collections.
-  In the result of __api/web/GetClientSideComponents_ request, we see our component but the manifest is not loaded there. _Manifest_  property value is empty.

We have 3 library components deployed in our tenant. Having 2 normal Library components and one search library component. The current library component which is loading from application extension or webpart is not loading manifest. Other library components are loading without issues.

**Comment by AJIXuMuK** [comment]
Thanks @arunakshi!
Few more questions:
- could you please navigate to `/Lists/ComponentManifests` on your App Catalog site, find your library component in there and share manifest with us?
- Could you also share the tenant url, and correlation id of the GetClientSideComponents request?

Feel free to send this info to aterentiev-at-microsoft.com if you can't/don't want to share it publicly.

**Comment by arunakshi** [comment]
@AJIXuMuK, i will share the info to the given email. 

BTW I cannot find the correlation id of the request.can you please tell me exactly where I can find this.

**Comment by AJIXuMuK** [comment]
@arunakshi  - sorry for not providing the details right away.
Look for `request-id` response header.

```
request-id: 1a9a23a0-e018-0000-e038-89c3898c2b3c
```

**Comment by AJIXuMuK** [comment]
@arunakshi - thanks for sharing the info with us!
Seems like the library component **is not** globally deployed.

Could you please go to the Component Manifests list again, add "Skip Feature Deployment" column to the view, and check its value?
I assume it will be No, meaning you need to "Add an app" manually.

**Comment by arunakshi** [comment]
@AJIXuMuK,  checked it. Sorry, it was not globally deployed :( 

Updated the package for globally deployment. It is working now without issues. Thanksssss alot for your help!!!
