### ISSUE TITLE
Image Helper API not available in SPFx 1.14.0

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#7752]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.14.0
- Node.js version: 14.18.2 (I think is irrelevant for this issue)

### Describe the bug / error

I´ve followed the steps in the docs to use the new Image Helper API: https://docs.microsoft.com/en-gb/sharepoint/dev/spfx/image-helper-api
but when importing:

```ts
import { ImageHelper, IImageHelperRequest } from "@microsoft/sp-image-helper";
```
I´m getting the error:
> Module '"@microsoft/sp-image-helper"' has no exported member 'ImageHelper'.ts(2305)

When I see the source code of the package inside the __node_modules__ folder, I can see this in the package.json of the module, so it seems is using the latest 1.14.0 version:

![image](https://user-images.githubusercontent.com/9392197/155497565-08c78b65-bd7e-4383-80c4-6d268be0ba9c.png)

And in the __index-internal.d.ts__ I can see the required classes are excluded:

![image](https://user-images.githubusercontent.com/9392197/155497793-e41bcfb8-e5da-4f8b-bc10-d9e0f75c94e6.png)

If I go to the __index-internal-beta.d.ts__ I can see the expected classes:

![image](https://user-images.githubusercontent.com/9392197/155498032-7a42df4d-d12b-4aea-b12d-39b55e205045.png)

What am I doing wrong? I´m getting same results in Windows and WSL2. I´ve also tried to create a new SPFx project using the --plusbeta option, but not working either.

/cc @andrewconnell (apologies for the direct mention, but I watched your YouTube video when you´re using it)

Many thanks!

### Steps to reproduce

1. Create a new SPFx project using 1.14.0 version (currently the last one released)
2. Follow the steps here: https://docs.microsoft.com/en-gb/sharepoint/dev/spfx/image-helper-api
3. You will get an error when importing the classes

### Expected behavior

You don´t get the importing error and you can use the API in your SPFx webpart.

**Comment by andrewconnell** [comment]
My video/post was based on the RC release... appears the NPM package isn't reflecting this as a production package.

BTW, AFAIK, `--plusbeta` is no longer useful once SPFx switched to the more standards-based way of using the NPM labeled packages, specifically `@next`, that was adopted with SPFx v1.12.1

Ping @AJIXuMuK

**Comment by AJIXuMuK** [comment]
GA build doesn't contain beta API. You still need to use beta builds. 
We will soon release 1.15 beta to be the latest one to use.

**Comment by luismanez** [comment]
Thanks for confirm this @andrewconnell @AJIXuMuK . In my opinion, the docs should state this clearer, as in the official link it says:

![image](https://user-images.githubusercontent.com/9392197/155517794-6b018612-2a07-4d17-bb5b-3d9f62cafa54.png)

Which is not completely correct, as is not in GA.

Thanks again.

**Comment by luismanez** [comment]
In case anyone is interested, I can confirm that you can use the API with SPFx 1.14 GA, but installing the beta version of the _sp-image-helper_ package (the beta one, not working either with the 1.14.0-rc.2)

```
npm install @microsoft/sp-image-helper@1.14.0-beta.5
```

**Comment by andrewconnell** [comment]
@AJIXuMuK said: 
> GA build doesn't contain beta API. You still need to use beta builds.

OK... I'll update the docs when I have some spare time.

@luismanez FWIW, 1.14 RC2 did work... that's what I used to create the screenshots in the published docs.

**Comment by luismanez** [comment]
Thanks Andrew for the note about version 1.14.0-rc.2. To be honest, it didn´t work for me, so just tried the beta one and worked. Guess I did something wrong when removing _node_modules_ or whatever.

Thanks!
