### ISSUE TITLE
How to use url instead of client id?

### ISSUE THREAD

**Issue by kongmengfei** [SharePoint/sp-dev-docs#7755]
i notice that below code use a url instead of id.

```
export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {
  public render(): void {
    // ...

    this.context.aadHttpClientFactory
      .getClient('https://contoso.azurewebsites.net')
      .then((client: AadHttpClient): void => {
        client
          .get('https://contoso.azurewebsites.net/api/orders', AadHttpClient.configurations.v1)
          .then((response: HttpClientResponse): Promise<Order[]> => {
            return response.json();
          })
          .then((orders: Order[]): void => {
            // process data
          });
      });
  }

  // ...
}
````

![image](https://user-images.githubusercontent.com/57654821/155698964-bce7a096-db30-42a6-8afa-0b2970002c10.png)

how to get this kind of URL?  i do not want to use id.

thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by lucabandMSFT** [comment]
hey @kongmengfei, if you go to the AAD portal and you locate the app you want to call in the "App Registration" list and then look for its "Application ID URI" entry under "Expose an API" section for that app.

**Comment by kongmengfei** [comment]
> hey @kongmengfei, if you go to the AAD portal and you locate the app you want to call in the "App Registration" list and then look for its "Application ID URI" entry under "Expose an API" section for that app.

it's another kind of app id like below:

![image](https://user-images.githubusercontent.com/57654821/161176773-dc604bad-e9d9-43b4-85dd-f314903b6eb3.png)

this is basically the same as app id.
