### ISSUE TITLE
Implicit Flow Problem for Azure AD-secured APIs

### ISSUE THREAD

**Issue by frankmatull** [SharePoint/sp-dev-docs#7759]
From the the following docs page
[Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application)

It says:

> Client-side applications that are incapable of storing a secret, such as SharePoint Framework solutions, use a specific type of OAuth flow named [OAuth implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-dev-understanding-oauth2-implicit-grant).

It looks like Implicit Flow is required to securely access external APIs from an SPFx solution, but on the page that is linked to describing implicit flow it says:

> With the plans for [third party cookies to be removed from browsers](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas), **the implicit grant flow is no longer a suitable authentication method.**

Does this mean that this solution for securely connecting to Azure AD-secured APIs is not possible in SPFx solutions?  What are the alternatives if we need to securely access an external Azure AD-secured API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by lucabandMSFT** [comment]
SharePoint Framework uses, under the cover, MSAL.JS V1 which indeed still relies on OAuth2 implicit flow. We are doing work to move to MSAL.JS V2 that will use a different flow for auth initiated from non confidential clients (aka the browser). 
That will happen transparently for 3rd party developers and, most importantly, it will be backward compatible (what it means is that existing solutions that have been already deployed will automatically switch to the new flow _if they are using our native SharePoint Framework classes for accessing AAD tokens_.

The current approach is as secure as implicit flow has been (with MSAL V1 library).

@VesaJuvonen, feel free to add anything you think I missed here and I will let you evaluate how to handle this doc issue
