### ISSUE TITLE
Documents are not renderred correctly in Production

### ISSUE THREAD

**Issue by aaronmi** [SharePoint/sp-dev-docs#776]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Documents are rendered correctly as designed.

#### Observed Behavior
All the documents under SharePoint Framework (e.g. https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant) are not rendered currently in production. There's corrupted section at bottom of each page.

#### Steps to Reproduce
1. browser to https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant
2. scroll down to bottom of the page

![currupted-doc](https://user-images.githubusercontent.com/11667890/29196992-fbe5a7dc-7dec-11e7-97f7-829ecc3c9018.PNG)

**Comment by VesaJuvonen** [comment]
thx @aaronmi for reporting. Issue bypassed for the CMS owners - hopefully, will get fixed asap.

**Comment by VesaJuvonen** [comment]
thx @aaronmi for reporting this. Fixed now in the production CMS side.
