### ISSUE TITLE
AadHttpClient - Timeout / Retry Policy

### ISSUE THREAD

**Issue by jaxnz** [SharePoint/sp-dev-docs#7760]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

I have a question around the AadHttpClient. We send a post request to a custom Web API, which processes documents, and can take a long time to complete. I with the smaller requests it works fine, but on the larger requests I notice two things:

1.  The request times out returning a 503 - even though the server is still processing
2.  It retries the request once, so two requests are received at the server.

My question is, is it possible to set timeout limits with the http client and also set retry requests to 0?

**Comment by jaxnz** [comment]
Just to confirm, the client only retries after timeout occurs. But there is no retry request in the network traffic, so I assume this may be server related?

**Comment by jaxnz** [comment]
I have found someone with a similar issue, but they are able to configure the retry policy using the Volly Http Client:

https://stackoverflow.com/questions/26672015/web-api-controller-action-called-twice

My problem is I need the authenticated bearer token to authorise the function on the API, if the AadHttpClient retry policy can't be modified, then is it possible to get that token another way?

**Comment by jaxnz** [comment]
Any update?

**Comment by patmill** [comment]
You have full control over the headers, so if it can be set that way, you could try.  Additionally, the back end server (say Azure) can have their own timeouts that are not controllable by either side.

If you have an extremely long running server task, you'll probably need to take a different approach.  For example, the initial call can return a token that can be used to poll the service for a response when complete, you could use something like socket I/O to create a persistent channel, etc.
