### ISSUE TITLE
spfx initial theme for MS teams (onThemeChanged)

### ISSUE THREAD

**Issue by ikovshik** [SharePoint/sp-dev-docs#7761]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Google Chrome v 98.0.4758.102;
- SPFx version - 1.14.0;
- Node.js version - 14.18.0;
- Windows 10

### Issue description

I have the following case:
 - open MS teams website (https://teams.microsoft.com/);
 - open application in tab;
 - change current theme(default) to dark;
 - refresh page (press F5) or open a different tab and return to current.

In the scenario above after changing current theme from default to dark `onThemeChanged` is loading the correct colors for dark theme. But when we refreshing page our current theme still is dark but the `onThemeChanged` returns values for default theme. 

I've also tried to get theme from `window.__themeState__.theme` object, but looks like here stored colors only for default theme.

Are there other ways for getting the correct initial theme?

**Comment by AJIXuMuK** [comment]
@ikovshik - thank you for reporting this one.
It seems like a regression. We'll take a look.

**Comment by AJIXuMuK** [comment]
@ikovshik - do you happen to have any sample?
I've just created a brand new solution using SPFx v1.14.0. And it is working correctly.
`currentTheme` parameter in `onThemeChanged` event returns correct current theme, both when it's just got changed and after refresh/switching between tabs.

**Comment by ikovshik** [comment]
@AJIXuMuK 
I've added sample project where this issue can be reproduced - https://github.com/ikovshik/spfx-theme-issue-sample

**Comment by AJIXuMuK** [comment]
Thanks @ikovshik for the sample.
It appears that your web part is isolated. And currently we don't support isolated web parts in Teams.
For example, Sync to Teams button is greyed out for such apps.
So, the behavior may be completely incorrect (as example - there is no way to configure such a tab, you'll see the settings panel open after each refresh).
Could you please check if the issue is there for non-isolated web part?

Thanks!

**Comment by ikovshik** [comment]
@AJIXuMuK 
In non-isolated web part it works correctly.

Thank you!
