### ISSUE TITLE
SPFx v1.14.0: problem with Image Helper API

### ISSUE THREAD

**Issue by yhabersaat** [SharePoint/sp-dev-docs#7763]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.14.0
- Node.js v14.18.1

### Describe the bug / error

When I'm trying to import the Image Helper API documented [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/image-helper-api#use-the-image-helper-api), I'm getting the following errors with ImageHelper and IImageHelperRequest:
- error TS2305: Module '"../../../node_modules/@microsoft/sp-image-helper/dist/index-internal"' has no exported member 'ImageHelper'.
- error TS2305: Module '"../../../node_modules/@microsoft/sp-image-helper/dist/index-internal"' has no exported member 'IImageHelperRequest'.

![image](https://user-images.githubusercontent.com/15676985/156203605-34e37135-b5c4-4eaf-8053-b2fd93511484.png)
![image](https://user-images.githubusercontent.com/15676985/156206738-17ed92ce-55e8-4921-acc0-dff1a1580d7b.png)

### Steps to reproduce

1. npm install @microsoft/sp-image-helper
2. import { ImageHelper, IImageHelperRequest } from "@microsoft/sp-image-helper";
3. Run gulp build

### Expected behavior

The expected behavior is that I can import correctly this API and use it without any error in my solution.

**Comment by AJIXuMuK** [comment]
@yhabersaat - thanks for reporting this one.

Image Helper API is still in beta, so it is not part of the GA release. You need to use the latest 1.14 beta (beta.5).
Or wait until 1.15 beta that should be coming soon.
