### ISSUE TITLE
Serve Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#777]
Hello team,
We have downloaded a package and installed all the npm packages and updated all the versions of spfx with the latest one.
We are facing an issue when we are running the gulp serve.
Below is the screenshot:
![image](https://user-images.githubusercontent.com/26655462/29204176-200b6272-7e93-11e7-886c-29878926442c.png)

Any help would be highly appreciated.

Many Thanks

**Comment by mcmynn83** [comment]
Have you tried creating a new environment from scratch following the instructions?  We have not seen this issue reported by others.

**Comment by bcameron1231** [comment]
What version of node are you using?

**Comment by sidjustsid** [comment]
@bcameron1231  Node v-6.11.2

@mcmynn83  Yes we have created the environment right from the scratch.

**Comment by waldekmastykarz** [comment]
@sidjustsid what version of npm and SPFx are you using? What package are you trying to use in your project?

**Comment by mcmynn83** [comment]
@sidjustsid - since you are not responsive on this thread we are closing it.  If you still are having this problem please open a new thread so we can take a look at it when you update us with more information (if it's not a new thread MS won't be notified).
