### ISSUE TITLE
SPFx v1.14.0: Image Helper API, exception in btoa, string contains characters outside of the Latin1 range

### ISSUE THREAD

**Issue by dev-a11y** [SharePoint/sp-dev-docs#7771]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Google Chrome 98
- SPFx version: 1.14.0-beta.5
- Node.js version: v14.15.5

### Describe the bug / error

I was testing Image Helper API (great feature) on a set of images located on my SharePoint tenant. I was loading images using Search REST API and taking DocumentLink managed property as an image URL source. Everything was fine for some time but suddenly whole webpart disappeared. Please find error details and my code below:

'DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.'

![image](https://user-images.githubusercontent.com/59690753/156363459-34cdf5b0-310b-417b-91f5-192f7a410308.png)

![image](https://user-images.githubusercontent.com/59690753/156363480-7b50d1cb-3712-464b-8dbc-7e3894e448d8.png)

Here is a link that may explain the reason and help fix this issue:
[https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte)

### Steps to reproduce

1. Prepare code following [Image Helper API docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/image-helper-api)
2. Use it to display various images stored on SharePoint tenant
3. Webpart may disappear due to unhandled exception

### Expected behavior

Webpart should not disappear. Mentioned error in SPFx code should not be propagated to client code.

**Comment by AJIXuMuK** [comment]
Thanks @dev-a11y for reporting the issue.
It will be fixed in the next 1.15 beta release.

**Comment by patmill** [comment]
THis is in the 1.15 beta, which has been released
