### ISSUE TITLE
IOS Mobile ACE doesn't display Office Fabric Icons

### ISSUE THREAD

**Issue by dcashpeterson** [SharePoint/sp-dev-docs#7772]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Iphone 11 and 12 
IOS 15.1.1

### Describe the bug / error

When creating an ACE using the yeoman generator in the manifest a property is added for officeFabricIconFontName. When adding an office fabric icon name it displays the icon in the web dashboard but in the IOS Teams mobile app the icons don't display.
![2022-03-02_15-58-42](https://user-images.githubusercontent.com/45491456/156399685-23826732-148c-493d-b055-ff9393321a0d.png)
![IMG_0737](https://user-images.githubusercontent.com/45491456/156401501-95660ac6-5556-4f58-b052-a3194dd2b94b.jpg)

### Steps to reproduce

1. Use the generator to create a new ACE. Doesn't matter the template.
2. Open the manifest file and enter ShoppingCartSolid in the officeFabricIconFontName property 
3. Deploy app to app catalog and add to dashboard.
4. Open Dashboard on Teams App on IPhone (e.g IPhone 12)
5. View App - Icon should be broken

### Expected behavior

Icon should display the same in browser as in mobile app.

**Comment by Zaidos9** [comment]
@dcashpeterson 

Please try using `cart` to fix the issue.
<img width="103" alt="image" src="https://user-images.githubusercontent.com/72800429/158438446-4f9faf69-2100-441c-a553-ac336c5511c7.png">


Currently Icons only support a pre-defined set on mobile. The pre-defined set is visible in `Card designer`'s Icon picker.
Thank you for reporting. We will update the documentation with the list of pre-defined icons. 

<img width="332" alt="image" src="https://user-images.githubusercontent.com/72800429/158438924-c33fe83d-0e73-47d4-b5d8-d5943cd17c8e.png">

**Comment by dcashpeterson** [comment]
@Zaidos9 Thank you for the update. Changing it to use cart (or any of the other select icons) does fix the issue with the icon not being displayed in mobile however it introduces a new issue. If you create a new ACE and in the officeFabricIconFontName property you enter cart then in the ACE picker it doesn't show with any icon. It is just a blank space unless there is a corresponding Office Fabric UI Icon with that name and then it shows that instead of the desired icon.

This example uses ribbon for the icon name in the manifest
This is the ACE picker
![2022-03-16_10-01-31](https://user-images.githubusercontent.com/45491456/158565537-544f6a4b-cca7-4e19-b3e1-1bf25bbcb3f7.png)

This is the ACE rendered on the dashboard
![2022-03-16_10-01-51](https://user-images.githubusercontent.com/45491456/158565780-dfe9aa7b-61f6-446e-bd58-024c6d3e7039.png)

Here is the ACE picker with the officeFabricIconFontName in the manifest set to cart
![2022-03-16_09-50-55](https://user-images.githubusercontent.com/45491456/158563970-f4051231-6c48-445b-bd1d-22ba26a32633.png)

When the card displays on dashboard in the browser it displays fine
![2022-03-16_09-51-12](https://user-images.githubusercontent.com/45491456/158564147-6a35a074-4ca8-4b30-9ff4-f83a5197cb80.png)

In Teams Mobile IOS it displays fine
![IMG_0156](https://user-images.githubusercontent.com/45491456/158564466-8ea6884c-9073-4f5d-bc01-fb0390cc4e13.PNG)

**Comment by lucabandMSFT** [comment]
Folks, thanks for the feedback and sorry for the delay in answering. We have confirmed we have a discrepancy between the way mobile and web understand and parses valid icons. We are working to fix that.

**Comment by AJIXuMuK** [comment]
@dcashpeterson - could you please check if that's fixed on your end?

**Comment by dcashpeterson** [comment]
@AJIXuMuK I will give this a look soon. Thanks for the update.

**Comment by dcashpeterson** [comment]
@AJIXuMuK I took a look at this and it does not look fixed. I am using 1.17.1 and still when I use an Office Fabrics Icon ShoppingCartSolid it shows in the ACE picker in the UI, and on the dashboard page but in Teams mobile I get the no icon found. When I change to use cart I get nothing in the ACE picker but I can see the icons in both the web and mobile experience.

**Comment by AJIXuMuK** [comment]
@dcashpeterson Thanks Derek!

**Comment by AJIXuMuK** [comment]
We have provided an update to the documentation that describes how the iconography works for the ACEs: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/fluent-icons-limitations
