### ISSUE TITLE
SPFx : ACE : Mobile experience : Unable to input data on clicking image buttons

### ISSUE THREAD

**Issue by anoopt** [SharePoint/sp-dev-docs#7775]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx version - 1.14

### Describe the bug / error

In the mobile experience for ACEs, we are not able to get the data from input (any type) when the `selectAction` present in an `image` adaptive card element. This works fine in web / desktop version.

![image_button_input_text](https://user-images.githubusercontent.com/9694225/156424004-7287f125-b39a-4d70-aef9-effd99ac46c5.png)

The code for this issue can be found [here](https://github.com/anoopt/spfx-ace-image-button-text).

The `image` card element

```json
{
  "type": "Image",
  "spacing": "Padding",
  "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Search_Icon.svg/1024px-Search_Icon.svg.png",
  "width": "25px",
  "selectAction": {
    "type": "Action.Submit",
    "data": {
      "id": "ImageButton"
    }
  }
}
```

The `onAction` function

```ts
  public onAction(action: IActionArguments): void {
    if ((<ISubmitActionArguments>action).type !== 'Submit') {
      return;
    }

    const submitAction = <ISubmitActionArguments>action;
    const { comments } = submitAction.data; //Undefined in mobile when triggered from a submit action in the image element

    this.setState({
      actionData: `action data - **${JSON.stringify((<ISubmitActionArguments>action).data)}**`,
      actionDataComments: `${comments}`
    });
  }
```

### Steps to reproduce

1. Clone this [repo](https://github.com/anoopt/spfx-ace-image-button-text)
2. Add the package to app catalogue
3. Add the ACE
4. Open in mobile app
5. Enter some text in the comments text box
6. Click on the search button
7. The data in `onAction` function doesn't contain the text entered

### Expected behavior

Clicking on the `selectAction` present in an `image` adaptive card element should provide the data entered in the input elements so that it can be used for processing.

**Comment by mahesh58786** [comment]
@anoopt Can you please let me know if you got any workaround for this issue. Even we are facing the same issue.

**Comment by anoopt** [comment]
@mahesh58786 - Try a normal action with image instead of `Image` with `selectAction`.

You can see an example [here](https://github.com/pnp/sp-dev-fx-aces/blob/main/samples/ImageCard-OfficeLocations/src/adaptiveCardExtensions/officeLocations/quickView/template/QuickViewTemplate.json#L24).

**Comment by mahesh58786** [comment]
@anoopt We already did exactly the same. Thank you.

**Comment by anoopt** [comment]
Good to know that. Out of curiosity can you please let me know which version of SPFx did you use to develop the ACE?

**Comment by mahesh58786** [comment]
@anoopt We are using 1.14.

**Comment by frags51** [comment]
Hey @anoopt / @mahesh58786 - I believe this issue should have been fixed. Could you please try again?
