### ISSUE TITLE
Current selectedRows.length when using new listViewStateChangedEvent

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7783]
How do I get the number of currently selected rows using `ListViewStateChangedEventArgs`?

I want to rewrite the following code:
```
@override
public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
  const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
  if (compareOneCommand) {
    // This command should be hidden unless exactly one row is selected.
    compareOneCommand.visible = event.selectedRows.length === 1;
  }
}
```

In SPFx 1.14, we should use 
```
public onListViewUpdated_v2(args: ListViewStateChangedEventArgs): void{
 const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
  if (compareOneCommand) {
      compareOneCommand.disabled =  ???
    }
  }
```

But the `args.prevState` returns previous state, and the `args.stateChange` returns a number. 
Or is it still work in progress?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc2663ae-d624-c31c-e039-de1d5379ebb9
* Version Independent ID: dc2663ae-d624-c31c-e039-de1d5379ebb9
* Content: [SharePoint Framework v1.14 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14)
* Content Source: [docs/spfx/release-1.14.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/release-1.14.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by kkazala** [comment]
`this.context.listView.selectedRows.length``works:
```
public onListViewUpdated_v2(args: ListViewStateChangedEventArgs): void{
 const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
  if (compareOneCommand) {
      compareOneCommand.disabled =  this.context.listView.selectedRows.length == 0
    }
  }
```

But I'm leaving this issue open, because I'd like to know whether
- this is how we should check for the selected rows now, and
- what is the `args.stateChanges` for (or what is it planned for?)

**Comment by AJIXuMuK** [comment]
@kkazala - `this.context.listView.selectedRows.length` is the correct way to get the number of currently selected rows.

For the `args.StateChanges` - this is a bitwise enum you can use to analyze what changes were made.
