### ISSUE TITLE
(MSAL /SPFx) Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by wpo365** [SharePoint/sp-dev-docs#7788]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Latest
- SPFx version: Latest (1.13.x)
- Node.js version: In accordance with SPFx 1.13.x requirements

### Describe the bug / error

Starting today we see an increased number of token renewal errors (Token renewal failed due to timeout) in not one but multiple of our SPFx custom developments. The Intranet application is used by 30K users and at least 2K of these users experienced this error today (we catch all errors and write them to ApplicationInsights). Neither the SPFx app nor the custom dotnetcore backend have been updated in recent days. Therefore we assume the error may be the result of a global update to the SharePoint Online application.

What we noticed is that some of the users experiencing the error receive the following error "AADSTS90138: Invalid ambiguous request. sid cannot be used with login_hint" but I am not sure whether this is related.

We tried to clear the local and sessions storage as well as the local browser cache but nothing works. However, when we choose to "Surf as guest" in a new browser tab that same user can sign in to the application without any problem.

### Steps to reproduce

We do not know the steps to forcefully reproduce the error. We can only look at individual occurrences when users call the central service desk for support.

### Expected behavior

We expect that the tokens can be renewed without any issue.

**Comment by bcameron1231** [comment]
@wpo365  It may be worth checking with the AD team on the MSAL library and see if they have any thoughts. 

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues

**Comment by VesaJuvonen** [comment]
> @VesaJuvonen Does it bring anything if I escalate this by opening a Premium Support Ticket? Thank you in advance!

That will always speed up the planned actions, so absolutely welcome. I'll push this also internally.

**Comment by wpo365** [comment]
@VesaJuvonen We were able to move passed the token renewal timeout issue by disabling the (new) auto-signin feature of the Edge browser.

![image](https://user-images.githubusercontent.com/32041702/157291455-3158bd4e-8439-45d9-b07b-ce4c8645a4c3.png)

I do believe that therefore the issue should remain open because I cannot imagine that this is a desired outcome (that all users should opt-out of a the new auto-signin feature for SPFx applications that use an AadHttpClient or MsGraphClient to connect to various APIs.

**Comment by lucabandMSFT** [comment]
@wpo365, thanks. This is an issue that the Edge team already recognized and fixed in recent canary builds. Please look at issue #7711 to get additional information in regards of that.
