### ISSUE TITLE
Set a SharePoint Framework development environment - Supported Node.js version

### ISSUE THREAD

**Issue by rob-windsor** [SharePoint/sp-dev-docs#7792]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

n/a

### Issue description

In Set up your SharePoint Framework development environment (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment), there's a typo in the part that describes the supported Node.js versions.

The SharePoint Framework v1.14.1 is supported on the following Node.js versions

should be

The SharePoint Framework v1.14.0 is supported on the following Node.js versions

![2022-03-09_11-17-25](https://user-images.githubusercontent.com/5740654/157483663-a1e4e804-bcd3-40ed-9413-4433511f715c.png)

**Comment by PrasadKasireddy** [comment]
@rob-windsor  thanks for reporting the issue, document is updated correctly now - https://github.com/SharePoint/sp-dev-docs/pull/7802
