### ISSUE TITLE
listViewStateChangedEvent does not trigger for grouped list views 

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7794]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome: 99.0.4844.51 (Official Build) (64-bit)
  - Edge 99.0.4844.51 (Official Build) (64-bit)
- SPFx version: 1.14.0
- Node.js version: 14.15.0 

### Describe the bug / error

`listViewStateChangedEvent` is not invoked for **grouped** list views. 

 I have a newly created **ListView Command Set** solution. 
The **TestCommandSet.ts** is as follows:
```
//...
public onInit(): Promise<void> {
    console.log("------------- onInit -------------");
    Log.info(LOG_SOURCE, 'Initialized TestCommandSet');
    this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedv2);
    return Promise.resolve();
  }

  private onListViewUpdatedv2(eventArgs: ListViewStateChangedEventArgs) {
    console.log("------------- onListViewUpdatedv2 -------------");
  }
//...
```
I'm using the following **launch.json** for testing:
```
//...
    "configurations": [
        {
            "name": "Travel requests",
            "type": "chrome",
            "request": "launch",
            "url": "https://site-url/Lists/Travel%20requests/AllItems.aspx?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={\"component-id\":{\"location\":\"ClientSideExtension.ListViewCommandSet.CommandBar\"}}",
            "webRoot": "",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///../../../src/*": "/src/*",
                "webpack:///../../../../src/*": "/src/*",
                "webpack:///../../../../../src/*": "/src/*"
            },
            "runtimeArgs": [
                "--remote-debugging-port=9222"
            ]
        },
        {
            "name": "Travel Grouped Edge",
            "type": "msedge",
            "version": "dev",
            "request": "launch",
            "url": "https://site-url/Lists/Travel%20requests/GroupedbyApproved.aspx?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={\"component-id\":{\"location\":\"ClientSideExtension.ListViewCommandSet.CommandBar\"}}",
            "webRoot": "",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///../../../src/*": "/src/*",
                "webpack:///../../../../src/*": "/src/*",
                "webpack:///../../../../../src/*": "/src/*"
            },
            "runtimeArgs": [
                "--remote-debugging-port=9222",
                "-inprivate"
            ]
        },
        {
            "name": "Travel Grouped Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "https://site-url/Lists/Travel%20requests/GroupedbyApproved.aspx?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={\"component-id\":{\"location\":\"ClientSideExtension.ListViewCommandSet.CommandBar\"}}",
            "webRoot": "",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///../../../src/*": "/src/*",
                "webpack:///../../../../src/*": "/src/*",
                "webpack:///../../../../../src/*": "/src/*"
            },
            "runtimeArgs": [
                "--remote-debugging-port=9222"
            ]
        }
    ]
}
```

### Steps to reproduce

Assuming that you have a "Travel requests" list and a "GroupedbyApproved.aspx" grouped view:

This works:
1. run `gulp serve --nobrowser`
2. Run debug using "Travel requests" as defined above
3. Observe "------------- onInit -------------" printed out in the debug console
4. Select a list row
5. Observe "------------- onListViewUpdatedv2 -------------" printed out in the debug console
6. Stop Debugging

This doesn't work:
1. run `gulp serve --nobrowser`
2. Run debug using "Travel Grouped Edge" as defined above
3. Observe "------------- onInit -------------" printed out in the debug console
4. Select a list row
5. Nothing gets printed out. The `onListViewUpdatedv2` is not invoked
6. Click on the group name in the view to drill down to the filtered view. At this point, the list view is not grouped.
7. Observe  "------------- onListViewUpdatedv2 -------------" printed out in the debug console immediately
8. Select a row
9. Observe "------------- onListViewUpdatedv2 -------------" printed out in the debug console

### Expected behavior

The `onListViewUpdatedv2` should be invoked in all the cases described above, no matter if the list view is grouped or not

**Comment by AJIXuMuK** [comment]
The fixes should be rolled out to production by now
