### ISSUE TITLE
this.context.pageContext.list.serverRelativeUrl doesn't refresh

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7795]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome: 99.0.4844.51 (Official Build) (64-bit)
  - Edge 99.0.4844.51 (Official Build) (64-bit)
- SPFx version: 1.14.0
- Node.js version: 14.15.0

### Describe the bug / error

I have a _List View Command Set_ with a _Command_ that should only be visible for one specific list (e.g. _Travel Requests_).
In order to hide the Command in other lists, I need to check the content.

The `listViewStateChangedEvent` is not executed on first render, so I cannot use it to hide button. I'm therefore using `onInit()`
**TestCommandSet.ts**
```
//...
public onInit(): Promise<void> {
    console.log("------------- onInit -------------");
    console.log("this.context.pageContext.list.serverRelativeUrl: " + this.context.pageContext.list.serverRelativeUrl);
    console.log("this.context.listView.list: " + this.context.listView.list);
    console.log("this.context.listView.list.serverRelativeUrl: " + this.context.listView.list.serverRelativeUrl);

    Log.info(LOG_SOURCE, 'Initialized TestCommandSet');
    this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedv2);
    return Promise.resolve();
  }
//...
```

I have two problems here: 
- `this.context.listView.list` returns `undefined` when debugging
- After deploying the solution to the SPO site, the `this.context.pageContext.list.serverRelativeUrl` has correct list url when I select a list. However, after selecting another list from the QuickLaunch, the  `this.context.pageContext.list.serverRelativeUrl`  is not updated

### Steps to reproduce

1. Create two lists: "Travel requests" and "Recruitment tracker" in your SPO site. Make sure both lists are displayed in the Quick Launch
2. Deploy the _List View Command Set_ solution to the (site) Apps Catalog
3. Open the site (home page), open DevTools (F12)
4. Click on the  "Travel requests" in the left navigation, see the following output in the console: 
![image](https://user-images.githubusercontent.com/22429087/157602539-5708bd62-ea7b-455a-85d4-1fde625ea4e0.png)
6. Click on the  "Recruitment tracker" in the left navigation, see  the following output in the console:  
![image](https://user-images.githubusercontent.com/22429087/157602687-e2ba11d9-f332-445b-98cd-7fdfc46a2287.png)

I could use `this.context.listView.list.serverRelativeUrl` to detect the list context, but  `this.context.listView.list` returns `undefined` when debugging.

### Expected behavior

Would be great if both properties `this.context.pageContext.list.serverRelativeUrl` and `this.context.listView.list.serverRelativeUrl` returned _correct_ values when debugging and when deployed.

**Comment by AJIXuMuK** [comment]
should be rolled out ww by now
