### ISSUE TITLE
Can not find module '@microsoft/sp-module-loader'

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#78]
Trying to follow this article https://github.com/SharePoint/sp-dev-docs/wiki/jQueryUI-Accordion-WebPart

gulp serve giving the the following error : 

Can not find module '@microsoft/sp-module-loader'

No luck even after installing python again and created the webpart from starting. 

Also found another issue: unable to delete the files created by yo @microsoft/sharepoint due to long folder/file name

**Code:** 

import {
  BaseClientSideWebPart,
  IPropertyPaneSettings,
  IWebPartContext,
  PropertyPaneTextField
} from '@microsoft/sp-client-preview';

import styles from './JqWebpart.module.scss';

import * as strings from 'mystrings';
import { IJqWebpartWebPartProps } from './IJqWebpartWebPartProps';
import MyAccordionTemplate from './MyAccordionTemplate';

import * as myjQuery from 'jquery';
require('jqueryui');
import importableModuleLoader from '@microsoft/sp-module-loader';

export default class JqWebpartWebPart extends BaseClientSideWebPart<IJqWebpartWebPartProps> {

  public constructor(context: IWebPartContext) {
    super(context);
  }

  public render(): void {
    this.domElement.innerHTML = `
      <div class="${styles.jqWebpart}">
        <div class="${styles.container}">
          <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
            <div class="ms-Grid-col ms-u-lg10 ms-u-xl8 ms-u-xlPush2 ms-u-lgPush1">
              <span class="ms-font-xl ms-fontColor-white">Welcome to SharePoint!</span>
              <p class="ms-font-l ms-fontColor-white">Customize SharePoint experiences using Web Parts.</p>
              <p class="ms-font-l ms-fontColor-white">${this.properties.description}</p>
              <a href="https://github.com/SharePoint/sp-dev-docs/wiki" class="ms-Button ${styles.button}">
                <span class="ms-Button-label">Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>`;
  }

  protected get propertyPaneSettings(): IPropertyPaneSettings {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}

**Comment by sprider** [comment]
Installed everything once again to fix this issue and recreated the webpart project again.

**Comment by ejochens** [comment]
While in a Node shell, the VS Code Terminal, or Command Prompt/PowerShell: navigate to the project folder and use Node to install it.  `npm install @microsoft/sp-module-loader`
