### ISSUE TITLE
Hosting Extensions Office 365 CDN

### ISSUE THREAD

**Issue by gurleen23** [SharePoint/sp-dev-docs#780]
#### Category
- [*] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I 'm trying to build a field-customizer extension following the steps given [here](bad42dcf-bff9-4f22-9617-6ca96f0e29ae).
I'm able to make the extension work using debug scripts as well as by deploying it from localhost through app catalog. But, when I try to host my extension from CDN it won't work. I followed all the steps very carefully from [this site](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn) but nothing works.

I also tried getting all the CDN Origins from the PowerShell and it gives me the CDN folder I've been using to host my extension (configuration is also completed).
I don't know what are the possible errors in this case.

**Comment by gurleen23** [comment]
I checked my Developer tools to find out the errors, it looks like this:
![image](https://user-images.githubusercontent.com/19613374/29285797-be70d7f0-80fd-11e7-9b6f-f2cf18b73d59.png)

**Comment by waldekmastykarz** [comment]
Your error messages refer to missing component manifests. Could you verify that the .sppkg is deployed in the app catalog and either deployed globally or the app is installed in the particular site where you're testing the extension?

**Comment by bcameron1231** [comment]
@gurleen23 Also to what @waldekmastykarz says... If you verified the .sppkg is deployed to the app catalog, when you deploy, verify the URL (in the popup window) is pointed to your CDN location and not specifying localhost.

**Comment by gurleen23** [comment]
Thank You for the reply @waldekmastykarz  and @bcameron1231 .
I checked my app catalog and it looks like that my .spkkg is deployed correctly and it is pointing to my CDN location. 
At this point I'm gonna try to build my .sppkg again and follow the steps in the user guide again and see if it works.

**Comment by gurleen23** [comment]
So, I looked into various documents and then I tried tenant-scoped deployment given [here](https://dev.office.com/sharepoint/docs/spfx/tenant-scoped-deployment) and after building my package solution again. I was able to fix the issue. 

Thank You for the help @bcameron1231 and @waldekmastykarz

**Comment by waldekmastykarz** [comment]
Glad to hear you fixed it @gurleen23
