### ISSUE TITLE
Can't hide property moveTo and copyTo

### ISSUE THREAD

**Issue by tocri** [SharePoint/sp-dev-docs#7801]
Hi the team,

I tried to hide the button 'move to' and 'copy to but it seems not to be working.
I have no issue with others properties but i'm stuck with these 2.

I tried on many SP site and it's the same behavior. 
{
        "key": "copyTo",
        "hide": true
      }

Could you give try it on your side?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Version Independent ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Content: [Command bar customization syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting)
* Content Source: [docs/declarative-customization/view-commandbar-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-commandbar-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by shagra-ms** [comment]
@tocri We are unable to reproduce this issue locally. Can you please confirm if this still reproduces? 

Please do share complete JSON to help us reproduce and resolve this issue.

**Comment by tocri** [comment]
Hi the team,

It was a cache issue. Works perfectly. Thanls the team for your great job

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
