### ISSUE TITLE
SPFx Adaptive card quick view with mp3, mp4 media not working on mobile

### ISSUE THREAD

**Issue by spoCloud** [SharePoint/sp-dev-docs#7808]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

hi,

I have a simple ACE card.  The quick view has a media element on it. The template was copied from this page:

https://adaptivecards.io/explorer/Media.html

This quick view with the .mp4 video works on desktop Viva connections dashboard.  But on iphone and android phone, in the Teams app,  the quick view shows an error "Quick view is not available right now. Try again later, go back, or open the app"

I've also tried mp3 audios,  and got the same issue on mobile phones.   Is the media element supported on mobile?  

Not sure why this is happening

Thanks

**Comment by harshdamaniahd** [comment]
Is there any update?

**Comment by frags51** [comment]
hi @harshdamaniahd @petrplavec - this should have been resolved now. Could you please try it out?
