### ISSUE TITLE
 Sharepoint Search Results postquery throws an error when Binary Data type managed property is included in SelectProperties

### ISSUE THREAD

**Issue by natpdeee** [SharePoint/sp-dev-docs#7810]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

The issue is related to the API and not the platform itself.

### Describe the bug / error

Sharepoint Search postquery **(/_api/search/postquery)** throws an error when DocumentSummary or BasicScope is included in the SelectProperties property of a postquery request. 

It used to be working fine without any issues. I tried to put some random name in the SelectProperties and it still works, but anything that has a Binary Data type in the Managed Property will break. There are only two Binary Data types in the managed property, which is BasicScope and DocumentSummary. Including one of them in SelectProperties will break the postquery.

This happens recently and I can replicate this in multiple tenants. Some of our custom webparts rely on the postquery results to display some content and all of a sudden it stopped working around 1-2 weeks ago.

Example POST query payload to _api/search/postquery
```json
{
    "request": {
        "Querytext": "*", 
        "TrimDuplicates": false, 
        "ProcessBestBets": true, 
        "EnableQueryRules": true, 
        "ProcessPersonalFavorites": true, 
        "SelectProperties": {
            "results": ["BasicScope"]
        }, 
        "ClientType": "ContentSearchRegular"
    }
}
```
The response from the server was: 
 500 Internal Server Error
```json
{
    "error": {
        "code": "-1, Microsoft.Office.Server.Search.REST.SearchServiceException",
        "message": {
            "lang": "en-US",
            "value": "An unknown error occurred."
        }
    }
}
```

Removing DocumentSummary or BasicScope from the SelectProperties will make things work.
I tried mapping BasicScope and DocumentSummary to a crawled properties but it didn't work.

### Steps to reproduce

1. Use Postman / other network tool and create a Post request to <tenantname.sharepoint.com>/_api/search/postquery
2. Make sure that ```'SelectProperties':{'results':['BasicScope']}``` is included in the request
3. Check the Response

### Expected behavior

The post query will still work as it used to be and not throwing an error. Even querying property that doesn't exist is still ok and returns 200 OK.

**Comment by Namrata99sah** [comment]
Same issue is happening with us, but not able to find for which SelectedProperties. If I disable the Query Rules the issues is gone.

**Comment by wobba** [comment]
This should now be fixed.
