### ISSUE TITLE
this.raiseOnChange() performance

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7811]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome: 99.0.4844.51 (Official Build) (64-bit)
  - Edge 99.0.4844.51 (Official Build) (64-bit)
- SPFx version: 1.14.0
- Node.js version: 14.15.0

### Issue description

I want to use the `raiseOnChange` to refresh a list view whenever an item has been updated using my custom form. 
I've noticed that sometimes it takes almost a minute to refresh the list view. Considering that the SPO lists refresh periodically anyway, I wonder if the `raiseOnChange`  makes any difference. 

To test it, I created a ListView Command Set extension with "Refresh list" button that: 
- case 1): starts a timer,  invokes `this.raiseOnChange()`, ends the timer when the list view is refreshed
- case 2): starts a timer,  ~invokes `this.raiseOnChange()`~, ends the timer when the list view is refreshed 

I created a list with a few simple columns and two items. The view as no grouping, filtering or field customizers.
I opened the list in two browser windows. For each test, I executed the following steps:
- In window 1: edit the list in grid view and un/select a checkbox
- in window 2: click on "Refresh list" button and wait for the timer to print results

**HelloWorldCommandSet.ts (version 1)**
```
export default class HelloWorldCommandSet extends BaseListViewCommandSet<IHelloWorldCommandSetProperties> {

  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, 'Initialized HelloWorldCommandSet');
    this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedv2);

    return Promise.resolve();
  }

  public onListViewUpdatedv2(args: ListViewStateChangedEventArgs): void {
    console.timeEnd("raiseOnChange");
  }

  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
         console.log("Triggering list refresh");
         console.time("raiseOnChange");
         this.raiseOnChange();
        break;
      default:
        throw new Error('Unknown command');
    }
  }
}
```
The results:
![image](https://user-images.githubusercontent.com/22429087/158765796-7aff79b8-768f-4d33-92eb-f90c3a5ab121.png)

**HelloWorldCommandSet.ts (version 2)**
```
export default class HelloWorldCommandSet extends BaseListViewCommandSet<IHelloWorldCommandSetProperties> {

  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, 'Initialized HelloWorldCommandSet');
    this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedv2);

    return Promise.resolve();
  }

  public onListViewUpdatedv2(args: ListViewStateChangedEventArgs): void {
    console.timeEnd("waitforRefresh");
  }

  public onExecute(event: IListViewCommandSetExecuteEventParameters): void {
    switch (event.itemId) {
      case 'COMMAND_1':
        console.log("Waiting for list refresh");
        console.time("waitforRefresh");
        break;
      default:
        throw new Error('Unknown command');
    }
  }
}
```
The results:
![image](https://user-images.githubusercontent.com/22429087/158766931-feaa2933-5e0f-4dad-8c28-474d14c2ed4f.png)

Even though a sample of 5 items is not really a sample ;), I can't help but wondering if the `raiseOnChange` works the way I thought it works. 
The documentation clearly states: "Use this method to fire onChange event and initialize a reflow of the ListView.", so I thought I can use it to force list view refresh and see the updated results within seconds. 
Am I wrong here?

**Comment by AJIXuMuK** [comment]
@kkazala - thanks for reporting this one.
We most probably will need to update the documentation.
But `raiseOnChange` fires the reflow or reinvalidate of the current list view state. It **does not** enforce getting new data from the server.
The idea is to use `raiseOnChange` to update you command set, not the list view.

**Comment by kkazala** [comment]
@AJIXuMuK Thank you for your prompt reply =)
It's a bit of a bummer, that we don't have a way of refreshing list contents without reloading the whole page. 
Do you think we might get it one day? SPO does it natively, so perhaps it's a low hanging fruit?

**Comment by AJIXuMuK** [comment]
@kkazala - it is one of the requests in the [discussion](https://github.com/SharePoint/sp-dev-docs/discussions/7375) around command sets.
But it has not been planned yet.
