### ISSUE TITLE
deploy-azure-storage command always creates container with Pubic Acces Level of 'Private' instead of Blob.

### ISSUE THREAD

**Issue by mmol1** [SharePoint/sp-dev-docs#7827]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Versions used:

    SPFX: 1.13.1
    Node: v14.15.1
    npm: 7.24.0
    gulp: 4.0.2

### Describe the bug / error

We are using `deploy-azure-storage` to deploy files to a container, but each time we do this the Public Access Level is always set to 'Private'. Reverting back to 1.12.1 solves this issue.

`ContainerClient.create` has an optional options parameter of type `ContainerCreateOptions`, which exposes an `access` property of type `PublicAccessType`. This could be used to override the default value, but the function `ensureContainerExistsAsync` doesn't passes the parameter to `ContainerClient.create`.

### Steps to reproduce

1. Setup an azure storage account as you would normally
2. Fill in the fields in deploy-azure-storage.sjon and write-manifest.json as per the microsoft documentation.
3. bundle your solution
4. run gulp deploy-azure-storage
5. See containers Public Access Level

### Expected behavior

We expected that `gulp deploy-azure-storage` command would create the container with the Public Acces Level set to Blob.

**Comment by AJIXuMuK** [comment]
Thank you @mmol1 for reporting this one.
The issue has been addressed and will be included in the next beta release (> beta.6)

**Comment by AJIXuMuK** [comment]
this should be fixed in the latest SPFx beta/rc drop
