### ISSUE TITLE
Question - SPFx solution not visible in site level - how to investigate?

### ISSUE THREAD

**Issue by akashSharma2505** [SharePoint/sp-dev-docs#783]
Hi, I created an app in node js using "yo @microsoft/sharepoint". The app is successfully built, deployed and running on localhost. Then I packaged the app using "gulp package-solution" and upoaded the ".sppkg" file in sharepoint online app catalog. The app is successfully uploaded in app catalog but the app is not visible in other site collections. I am trying to add app using "add an app" option and then checking in "My organization apps". The app is not visible here. Can any one help me with this ?

#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After adding SPFx solution to app catalog, iit should be available for installation in site level.

#### Observed Behavior
SPFx solution is in the app catalog, but it's not visible in "add an app" capability

#### Steps to Reproduce
With my current SPFx solution - have installed that to app catalog, but it's not visible in the site level.

**Comment by VesaJuvonen** [comment]
Hi @akashSharma2505 - have formatted your submission now so that it's using the submission template. This most likely means that your package had an issue, so it's not exposed in the site level. Can you check the value of "Valid App Package" for the solution in app catalog? - if that's false, please click the "Unavailable Apps" link in the app catalog to see the actual description.

**Comment by estruyf** [comment]
@akashSharma2505 are you using the latest SharePoint generator version? The one which got the `skipFeatureDeployment` option? If so, when you enable the skipFeatureDeployment option your solution will automatically get deployed tenant-wide and the app is not visible under "My organization apps".

If you only want to deploy it to a specific site, best set this option to `false`.

**Comment by SPParseError** [comment]
Yes exactly, with the new ability to deploy globally in the tenant you don't see the app anymore on your site, even when trying to install new ones.

**Comment by VesaJuvonen** [comment]
Closing for now due no response from @akashSharma2505. Feel free to re-open provide additional details.

**Comment by berntrune** [comment]
Hi, I'm experincing the same @akashSharma2505 on a SharePoint 2016 server with feature pack 2 installed. I had it working for a while, but after updating the package it stopped working. I deleted the package and uploaded the previous version with the same result. The package is always valid.

**Comment by shaipetel** [comment]
Hey, just out of curiosity, did you build the package using:
> gulp package-solution

or
> gulp package-solution --ship

Also, did you first build it using
> gulp --ship

And did you set up a CDN and published the files there?

**Comment by berntrune** [comment]
Hey. I don't use --ship since I have sp2016 installed on my machine.

**Comment by shaipetel** [comment]
Hi @berntrune, if you don't use the --ship flag, do you have "gulp serve" running?

**Comment by berntrune** [comment]
Hi@shaipetel :)  Yes,I have Gulp serve running. Im using @microsoft/generator-sharepoint 1.0.2.

**Comment by shaipetel** [comment]
Haha, just checking... Well, I'm out of ideas.

**Comment by berntrune** [comment]
@shaipetel Thanks anyway :)  @akashSharma2505 , did you find a solution?

**Comment by mmsharepoint** [comment]
Just another option what could go wrong:
If you copy and paste from an existing solution and do not create a new GUID in manifest.json but already have a component with same GUID in your tenant the .sppkg will also not deploy. Unfortunately it does not raise an error on deploying even not when trying this again with PnP PowerShell for instance.
Creating a new GUID in my .manifest.json solved the problem.
Just in case anyone else faces this ...
Markus
