### ISSUE TITLE
SPFx Web Part Getting Started - Outdated YouTube Video

### ISSUE THREAD

**Issue by rob-windsor** [SharePoint/sp-dev-docs#7830]
The version of the SharePoint Framework (v1.10.0) used in the video embedded into the page referenced below page several versions behind the current version. At this point the video is more confusing than it is enlightening. I think the embedded video should either be removed or replaced.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by smchargue** [comment]
Boy, do I agree.  I'm still looking for the secret room where someone tells how you get one of the spfx-sample projects build.  I'm a developer with 30 years of experience, and all I've accomplished all day it to generate and endless sea of indecipherable npm install errors.

**Comment by VesaJuvonen** [comment]
Noted - on the roadmap to get updated @rob-windsor, pending on time.

**Comment by andrewconnell** [comment]
Believe this to be moot as the the video was refreshed after this issue was created.
