### ISSUE TITLE
SPFx Ext Field Customizer Hide/Show Based On List/Library "Edit Mode"

### ISSUE THREAD

**Issue by jared-leddy** [SharePoint/sp-dev-docs#7833]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: N/A
- SPFx version: v1.12, v1.13 or v1.14
- Node.js version: v14.x or v16.x
- etc

### Issue description

I'm working on an SPFx extension that needs to render a string in display mode, but when it's in edit mode it should render a dropdown select field. On a library, this would be the "edit in grid view". On a list, it would be "edit" (with the modal form) or with "edit in grid view".

How can you track the state of the list/library, and render the field accordingly?

**Comment by jared-leddy** [comment]
I did find the import module for display mode. This does capture the display mode effectively, but now the component doesn't render. The "view" mode is showing the text correctly, but the "edit" mode is not showing the dropdown.

```js
import { DisplayMode } from '@microsoft/sp-core-library';
```

Then it's used in a if function like this...
```js
// not in display read, meaning it's edit mode
if (!DisplayMode.Read) {
 // edit mode component
} else {
// display mode component
}
```

**Comment by AJIXuMuK** [comment]
@jared-leddy unfortunately Field Customizers are not supported in edit mode.
