### ISSUE TITLE
Supported Cross-Platform Functions for ACE QuickView

### ISSUE THREAD

**Issue by dcashpeterson** [SharePoint/sp-dev-docs#7834]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Chrome, Teams Mobile (IOS, Android)
- SPFx version - 1.14

### Issue description

Is there a documented list of the built in functions we can use with ACEs in the quick view? Some functions only work in the browser, some work in the browser and IOS, some work in browser, IOS, and Android etc. 

DATE and TIME work across all three
formatNumber works great in IOS and web but not in Android
formatDateTime works great in IOS and web but not Android
Where and Count work great in all three.

It would be great if we could point to a list of what functions are supported for ACE development.

**Comment by AJIXuMuK** [comment]
@dcashpeterson - we have aligned on the QuickView engine between all experiences using web (JavaScript) implementation as a core.
So all functions that work on web should now work on mobile.

Please, comment back if that's not the case on your side.
