### ISSUE TITLE
[$_ModerationStatus] and [$__ModerationStatus] do not behave as documented in some cases

### ISSUE THREAD

**Issue by aepstein** [SharePoint/sp-dev-docs#7837]
The documentation describes a [$_ModerationStatus] and [$__ModerationStatus] field I can use to get the moderation status text and numeric code respectively. I am using SharePoint online in the Government Community Cloud (GCC), and I am finding that it does not behave quite as described. [$_ModerationStatus] will return "Approved", "Pending", etc. as expected. However, I observe two deviations from described behavior:

- [$__ModerationStatus] and [$_ModerationStatus.numeric] do return a numeric value, but the value is always 0 even if the status is something other than "Approved".
- Number([$_ModerationStatus]) returns NaN, not the numeric status code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa6ae62-4dd8-3bdf-2f2c-f3f4a76e43b9
* Version Independent ID: 1aa6ae62-4dd8-3bdf-2f2c-f3f4a76e43b9
* Content: [Formatting syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference)
* Content Source: [docs/declarative-customization/formatting-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/formatting-syntax-reference.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by shagra-ms** [comment]
@aepstein Thanks for reporting this.

We haven't been able to reproduce this locally. Can you confirm that you see this issue only on GCC ? Can you also share a small sample JSON to reproduce this?
