### ISSUE TITLE
Does this also apply to custom CommandSets?

### ISSUE THREAD

**Issue by eduardpaul** [SharePoint/sp-dev-docs#7840]
Hi all, reading this documentation it is not clear if we can use this format to order custom CommandSets developed with SPFx. Could you please clarify this? I tried it on my tenant and it didn't work... I don't know if it's because I'm not using the right key. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Version Independent ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Content: [Command bar customization syntax reference](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting)
* Content Source: [docs/declarative-customization/view-commandbar-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-commandbar-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by eduardpaul** [comment]
Thank you @AJIXuMuK ! Is it possible to know if the product team is planning to extend this configuration to custom CommandSets? The truth is that it would be very useful to be able to order them (custom or not). 

Have a nice day!

**Comment by AJIXuMuK** [comment]
@eduardpaul - this is part of the feedback we're tracking here: https://github.com/SharePoint/sp-dev-docs/discussions/7375
For now there is no specific plan for it. And I can't guarantee there will be a good solution that covers both OOB and 3-party
