### ISSUE TITLE
onListViewUpdated event not fired for ContextMenu extensions on certain tenants

### ISSUE THREAD

**Issue by Terra-jin** [SharePoint/sp-dev-docs#7842]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome version 99.0.4844.84
- Edge version 99.0.1150.55
- SPFx version 1.11.0
- Node.js version 10.22.0

### Describe the bug / error

We have a solution containing several extensions, of which some at the CommandBar and some at the ContextMenu. The ones at the CommandBar function properly, but the ones on the ContextMenu are **not** shown on **some** tenants.

Debugging has shown that the onListViewUpdated event is not fired properly. On tenants where they do work, right-clicking on a document or clicking on the context menu button fires two onListViewUpdated events: one with an empty array of selectedRows and shortly thereafter one with the correct selectedRows. However, on other tenants, either both of these events are not fired, or only the first one (with the empty array) is fired, causing the extension to remain invisible.

What causes the onListViewUpdated events to (not) fire?

### Steps to reproduce

1. Install extension containing extensions at the ContextMenu
2. Right-click on the document, or click the ContextMenu button

### Expected behavior

The extension is visible

**Comment by Terra-jin** [comment]
Hi Alex,


We are planning to do so, but since it involves a lot of breaking changes we're looking for a more short-term solution.

**Comment by AJIXuMuK** [comment]
@Terra-jin let's try to localize the issue and try to fix it.
Could you check what the difference is between 2 tenants or sites where the behavior is correct and incorrect?
Next things could be helpful
1. Is it list or doc library in both cases or no?
2. How do you navigate to the list? If you do ctrl+f5 - will it change the behavior?
3. Any additional customizations on one of 2 tenants/lists?
4. Communication Site vs Teams site
5. `onListViewUpdated` is not called but the commands are still visible, correct?
6. How the command sets were registered in both cases?
7. Could you check a simple new command set to see if it's working or not?

**Comment by Terra-jin** [comment]
Hi Alex,


The problem turned out to be on our end. The solution which contains the problematic extension contains two other extensions, one of which lacked a catch statement in the promise returned in the onInit function. This apparently caused the other two extensions to not initialize properly.

On the tenant where it worked, the solution had already been fixed.

Thank for your help!
