### ISSUE TITLE
A blank item is showing in SharePoint Admin API Access as Approved and I cannot remove it.

### ISSUE THREAD

**Issue by pmatthews05** [SharePoint/sp-dev-docs#7843]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

This is relating to the web api permissions, which are for SPFX. I haven't included any SPFX details such as node, SPFX version etc, as it's not the actual SPFX that's causing the problem.

### Describe the bug / error

Within the SharePoint admin center for API Access I have an approved request, but its blank. https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement

![image](https://i.stack.imgur.com/2wmLC.png)

When attempting to remove the access, I just get an error message saying `We couldn't remove access. Try again`. Looking at the developer tools network trace, it's trying to call `https://graph.microsoft.com/beta/oAuth2Permissiongrants/GG_VIp-IzUmHAVimhaVSxpPbXnow3TBBvuqdXo8pT7A` which returns a status code of Bad Request - Permission being updated or deleted is not found.

I know this is tied to the App Registration/Enterprise Application "SharePoint Online Client Extensibility Web Application Principal". As I can see my expected permission showing
![image](https://i.stack.imgur.com/6QT7r.png)

When I try to view the permissions and user consented in the Enterprise application section, its unable to load the screen.
![image](https://i.stack.imgur.com/iEb1j.png)
The network trace for this page, is trying to call `https://main.iam.ad.ext.azure.com/api/EnterpriseApplications/22d56f18-889f-49cd-8701-58a685a552c6/ServicePrincipalPermissions?consentType=Admin&userObjectId=` which returns a 500 Internal Server Error - Object reference not set to an instance of an object"

### Steps to reproduce

In SharePoint.
1. Go to https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement - Here you can see on my tenant a blank entry.

In Azure
1. Go to portal.azure.com
2. Click Azure AD 
3. Select App Registrations -> All Applications
4. Type SharePoint in the search box and select "SharePoint Online Client Extensibility Web Application Principal"
5. On overview page, click Managed Application in local directory link.
6. Now on the Enterprise Application, under Security click Permissions 

### Expected behavior

- No empty Approved Requests in SharePoint Admin
- Can view all the permissions assigned in - SharePoint Online Client Extensibility Web Application - Enterprise Application

**Comment by lucabandMSFT** [comment]
mmmh. that seems a problem of the object in AAD for that specific tenantt @pmatthews05, do you have the right rights to remove entirely the object from AAD? if yes, please do that then navigate back to the API Access page in SharePoint. that will re-trigger application principal provisioning. Note that you will have to re-approve the permissions by going to the App catalog and re-reploy your package (there's an option for that in the app catalog itself).

**Comment by pmatthews05** [comment]
Hi @lucabandMSFT, I have deleted the "SharePoint Online Client Extensibility Web Application", and removed it from Deleted applications.

By going back to SharePoint Admin center - API Access, as you stated it has removed all the requests.

I have redeployed my single SPFX and everything is working as expected. 

Thank you so much! I will close this now.

**Comment by lucabandMSFT** [comment]
@pmatthews05 , super glad to hear that. Thanks a lot for the update!
