### ISSUE TITLE
command.disabled not always respected

### ISSUE THREAD

**Issue by kkazala** [SharePoint/sp-dev-docs#7845]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome: 99.0.4844.51 (Official Build) (64-bit)
  - Edge 99.0.4844.51 (Official Build) (64-bit)
- SPFx version: 1.14.0
- Node.js version: 14.15.0 

### Describe the bug / error

Thank you for fixing [#7795](https://github.com/SharePoint/sp-dev-docs/issues/7795)!

I now changed my CommandSet logic to:
- Show the command buttons only for the "Travel requests" list
- Disable the "Submit report"  by default
- Enable the  "Submit report" only if exactly one item is selected AND the "Submitted" == "No"

```
//onInit executes **CORRECTLY**
public onInit(): Promise<void> {
  const setCommandsState = (isVisible:boolean) => {
    const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
    if (compareOneCommand) {
      //Visible for registered lists, does not depend on selected item
      compareOneCommand.visible = isVisible;
    }
    const compareTwoCommand: Command = this.tryGetCommand('COMMAND_2');
    if (compareTwoCommand) {
      //Visible for registered lists, enabled if 1 item selected, so disable by default
      compareTwoCommand.visible = isVisible;
      compareTwoCommand.disabled = true;
    }
  }
  const getListUrl = (listUrl: string): string => {
    let result = listUrl.match(/Lists\/(?<ListName>.*)/);
    return result.groups["ListName"];
  }
  
  setCommandsState( registeredList.includes(getListUrl(this.context.listView.list.serverRelativeUrl)));
  this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedv2);
  return Promise.resolve();
}

public onListViewUpdatedv2(args: ListViewStateChangedEventArgs): void{

  const isSubmitEnabled= (this.context.listView.selectedRows.length == 1) && (this.context.listView.selectedRows[0].getValueByName("Submitted") == "No")
  console.log(`isSubmitEnabled: ${isSubmitEnabled}`)

  const compareTwoCommand: Command = this.tryGetCommand('COMMAND_2');
  compareTwoCommand.disabled = !isSubmitEnabled;
  this.raiseOnChange();

  console.log(`compareTwoCommand.disabled: ${compareTwoCommand.disabled}`)
  console.log("refresh")
}
```

When debugging, the 'COMMAND_2' button is not enabled/disabled when switching between two items with different Submitted values. 
I think that `this.raiseOnChange()` is not required for the `disabled` state (?). I called it anyway hoping it would fix the issue but it doesn't have any impact.

### TEST 1
1. Create new ListView CommandSet solution, keep the two default buttons
2. Update the _CommandSet.ts as presented above
3. Ensure that you have a "Submitted" (Yes/No) column in the list
4. Ensure you have two items in the list, one with Submitted=Yes and the other with Submitted=No 
5. Debug
6. Ensure that both buttons are visible, and button "COMMAND_1" is enabled, while **"COMMAND_2" is disabled**
7. In the list, select the item where **Submitted=No** 
8. Ensure that you get the following console output:
![image](https://user-images.githubusercontent.com/22429087/161009066-cbe8c8b3-4434-41c5-8f20-716fafe67a8e.png)
10. Ensure that the button  **"COMMAND_2 is enabled**
11. Select the item where **Submitted=Yes** 
12. Ensure that you get the following console output:
![image](https://user-images.githubusercontent.com/22429087/161009280-975d0beb-a8ca-4d46-aa7d-e906597f194f.png)
14.  The button  **"COMMAND_2 should be disabled** but it's still enabled

### TEST 2
Execute the above steps 1-10, and then
11. Click "outside" of the list to unselect the row
12. Ensure that you get the following console output:
![image](https://user-images.githubusercontent.com/22429087/161010045-3acd4868-dd2c-4d34-aedb-50687d56763b.png)
14. The button  **"COMMAND_2 should be disabled** but it's still enabled

### Expected behavior

In the step 14 in the tests described above, the COMMAND_2  button should be **disabled**

**Comment by AJIXuMuK** [comment]
Thanks @kkazala for reporting this one!
The fix has been done and will be rolled out in the next few weeks.
You will still need to call `raiseOnChange` if the property is modified out of `execute`.

**Comment by AJIXuMuK** [comment]
This should be rolled out WW by now.
