### ISSUE TITLE
How to track for changes in Display Mode

### ISSUE THREAD

**Issue by Tooyosi** [SharePoint/sp-dev-docs#7846]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - v99.0.4844.83
- SPFx version - v1.4.1
- Node.js version - v14
- etc

### Issue description

Is there a function to track for changes in displayMode? I noticed the onDisplayModeChanged of the BaseClientSideWebPart class is no longer triggered on display mode changes and i'll like to ask if there's an alternative for that.

Also, is there a lifecycle event that gets triggered when editing a second webpart? i.e When i'm editing a webpart and click on the edit icon of another webpart

**Comment by AJIXuMuK** [comment]
Hi @Tooyosi - thank you for reporting this one.
The approach of switching between display and edit modes has been changed internally.
Now the web part is disposed and re-created when display mode has been changed.
So, you can check `displayMode` property either in `render` or in `onInit` to run the logic for this or that mode.
