### ISSUE TITLE
Issues when using PeoplePicker in React Panel.

### ISSUE THREAD

**Issue by rameshmeghwal** [SharePoint/sp-dev-docs#7849]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

Your environment has been set up for using Node.js 10.19.0 (x64) and npm.
+-- @microsoft/generator-sharepoint@1.11.0
+-- gulp-cli@2.3.0
`-- yo@3.1.0

### Describe the bug / error

Hi,

I have bind sharepoint list item in DataTable and I make Title column clickable as a ActionButton for open React Panel (model popup).
When I am click on Title column  React Panel (model popup) is working properly. BUt when I have added "PeoplePicker" in React Panel (model popup) that time all DataTable hide. I am facing this issues
 TIA
Ramesh

### Steps to reproduce

Hi,

I have bind sharepoint list item in DataTable and I make Title column clickable as a ActionButton for open React Panel (model popup).
When I am click on Title column  React Panel (model popup) is working properly. BUt when I have added "PeoplePicker" in React Panel (model popup) that time all DataTable hide. I am facing this issues
 TIA

### Expected behavior

Hi,

I have bind sharepoint list item in DataTable and I make Title column clickable as a ActionButton for open React Panel (model popup).
When I am click on Title column  React Panel (model popup) is working properly. BUt when I have added "PeoplePicker" in React Panel (model popup) that time all DataTable hide. I am facing this issues
 TIA

**Comment by AJIXuMuK** [comment]
@rameshmeghwal - based on the description, this issue is not related to SPFx itself.
It is some issue in your custom code or libraries you're using.

I can only recommend debugging the panel rendering and operations you're performing at that moment
