### ISSUE TITLE
Sharepoint Webpart Documentation out of date

### ISSUE THREAD

**Issue by Ernests12LV** [SharePoint/sp-dev-docs#7850]
There is an issue with this .tsx code block it is outdated and doesn't work
also the picture in the next step does not represent the code correctly.

I also added my code when i paste it in vs code
![Screenshot 2022-04-04 163930](https://user-images.githubusercontent.com/64549597/161556638-a61f49e7-f006-4b87-bc02-675dcd878833.png)
![Screenshot 2022-04-04 163945](https://user-images.githubusercontent.com/64549597/161556644-acb80122-d5de-4d13-a04e-1adfd71228ab.png)
![Screenshot 2022-04-04 164234](https://user-images.githubusercontent.com/64549597/161557081-f4efd9b2-08e0-4d9d-9417-8a9ec4c40cfc.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This was indeed completely wrong - sorry for that and huge thanks for flagging things. We have now updated the web part tutorial series to be up to date and to be a bit more simplified getting started journey.
