### ISSUE TITLE
Implement SSO on button click for a third party application , which is already using azure ad to sign in

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7861]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,
I would like to know which is the correct method here and how to proceed.

1. I have a button which is SPFX webpart 
2. When the user clicks on a button , i want the user to have silent sign in to a third party application without a popup.
3. How can i implement this ?

**Comment by AJIXuMuK** [comment]
@harshdamaniahd - is that something you're looking for: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd - is that something you're looking for: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?

@AJIXuMuK hi, thanks.ya i thought using it but was not sure.
i am actually trying to do this.
i have a viva connection card, and one of the card is a third party website which authenticates using azur ad. 
the good part of viva connection card is that the website opens inside teams and user doesn't have to open a browser. but have to sign in every time.
is it possible to use spfx aadhttpclient and pass access token to this web application ? since we have already authenticated using tems and then aadhttpclient

**Comment by lucabandMSFT** [comment]
hey @harshdamaniahd, when you say "authenticate", what do you mean? do you need to call an API to consume data from within the card? Or do you need to navigate to a web site / app from there?
