### ISSUE TITLE
Unit testing with Jest throwing error in TeamsFx App 

### ISSUE THREAD

**Issue by v-ashrirao** [SharePoint/sp-dev-docs#7862]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Node.js version - 14.18.2
React version - 17.0.2

### Issue description

We have built an app using TeamxFx.
When we tried to write unit tests using JEST we are getting error.
Do we have some sample project to refer to for this?

**Comment by AJIXuMuK** [comment]
@v-ashrirao - as this is TeamsFx related, you need to create an issue here: https://github.com/OfficeDev/TeamsFx
