### ISSUE TITLE
Webpart and Extension in one solution / package - SPFx 1.4.1 - SharePoint 2019 / Subscription Editon

### ISSUE THREAD

**Issue by Pronizius** [SharePoint/sp-dev-docs#7863]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge (100.0.1185.29), Chrome (99.0.4844.84), IE 11
- SPFx version: 1.4.1
- Node.js version: 10.24.1

### Describe the bug / error

In SPFx 1.4.1 it is not possible to have a webpart and an extension (field customizer) in one solution and package.
After package and deployment only the extension is working.

It must be somehow connected to the package-solution.json.
If I remove all features (so the extension) only the webpart is working.

I also tried it with the componentId, which is also not working [http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2019/01/08/how-to-properly-add-an-application-customizer-to-an-existing-spfx-web-part-project.aspx?CommentPosted=true#commentmessage](http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2019/01/08/how-to-properly-add-an-application-customizer-to-an-existing-spfx-web-part-project.aspx?CommentPosted=true#commentmessage)

And I tried to create an own feature for the webpart. The feature is also showing up in the browser, but the webpart is still missing.

Is this a SPFx 1.4.1 bug? Is there no way to have an extension and a webpart in SPFx 1.4.1? Does it need to be two separate solutions?

### Steps to reproduce

1. yo @microsoft/sharepoint (add webpart SharePoint 2019, no javascript framework)
2. yo @microsoft/sharepoint (add extension - field customizer, no javascript framework)
3. package and deploy the solution

### Expected behavior

Both components  of the solution get published and are available.

**Comment by AJIXuMuK** [comment]
@Pronizius - thanks for reporting this one.
It **is** an issue and has been addressed for the latest versions of SPFx.
Unfortunately, for v1.4.1 you would need to update things manually.
You will need to modify `package-solution.json`.
You can also try to scaffold items in the opposite direction.

https://github.com/SharePoint/sp-dev-docs/issues/7725#issuecomment-1042998319

**Comment by Pronizius** [comment]
Hello @AJIXuMuK 
Thanks for your response, opposite direction, does not work either, it generates the same package-solution.json.
What is the correct package-solution.json? Can you give me an example with a webpart and an extension in one solution?
Like described above I tried with componentIds [here](http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2019/01/08/how-to-properly-add-an-application-customizer-to-an-existing-spfx-web-part-project.aspx?CommentPosted=true#commentmessage) but it still does not work either.
Looks like the only solution for 1.4.1 is to separate webparts and extensions. Can you confirm this?

**Comment by AJIXuMuK** [comment]
@Pronizius - yes, seems like you are correct.
Especially if you're using the solution for on-prem
I believe the approach you mentioned in your comment should still work for SharePoint Online.
But if you're developing for SP Online, I'd update to the latest version of SPFx.

**Comment by Pronizius** [comment]
@AJIXuMuK Thanks again for your time and information.
