### ISSUE TITLE
Any chance to have React 18 for spfx 1.15 ?

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#7864]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hi,
Any chance to have React 18 for spfx 1.15 ?
A lot of updated lib claims a Reat 17 for minimal version, it will become a problem in the coming weeks for the updates of SPFx projects, they may no longer correspond to the security criteria and the update policy of the companies.

**Comment by AJIXuMuK** [comment]
Hello @PooLP.
Unfortunately, we won't have it in SPFx 1.15.
But there are plans on that for the upcoming versions.

**Comment by PooLP** [comment]
Thanks for response.
