### ISSUE TITLE
Run locally installed sp generator by path fail

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [SharePoint/sp-dev-docs#7865]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.14.0
- Node.js version 12.19.0
- etc

### Describe the bug / error

Since yeoman supports to run local generator by path(https://github.com/yeoman/environment/issues/11), I'm trying to do that with @microsoft/generator-sharepoint. But it fails to find the solution generator.

### Steps to reproduce

1. npm install yo globally: npm install -g yo@4.3.0
2. npm install @microsoft/generator-sharepoint into a local folder, e.g. spfx/, npm install @microsoft/generator-sharepoint@1.14.0 --prefix ./spfx 
3. try to scaffold using 'yo .\spfx\node_modules\@microsoft\generator-sharepoint\lib\generators\app\index.js' but failed with following error:

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/73154171/161932442-bcc5e48a-418f-4a25-a49f-90d7b5bf1a01.png)

### Expected behavior

SPFx project scaffolded successfully

**Comment by KevinTCoughlin** [comment]
I'll see if this is something we can improve in our code. It looks like generator module resolution fails unless you invoke via absolute path from within the SPFx generator directory.

The below works FWIW

```shell
cd /Users/<alias>/dev/spfx/node_modules/@microsoft/generator-sharepoint/lib/generators/app/
yo /Users/<alias>/dev/spfx/node_modules/@microsoft/generator-sharepoint/lib/generators/app/index.js --skip-install true --component-type webpart --component-name helly03310941B --framework react --environment spo --skip-feature-deployment true --is-domain-isolated false
```

**Comment by HuihuiWu-Microsoft** [comment]
Thanks @KevinTCoughlin. I think that's because current directory is one of the paths that yo search for generators from. But in this way, we'll have to move the generated spfx  project to target folder after scaffolding.  It would be great if you can improve this and user can scaffold SPFx under any directory by passing generator path.

**Comment by KevinTCoughlin** [comment]
We believe we have a fix to support this residing in `utilities.ts`, the `compose` function should be written as:

```ts
export function compose(generator: string, base: BaseGenerator<any, any>, options: IBaseOptions): void {
  base.composeWith(require.resolve(`@microsoft/generator-sharepoint/lib/generators/${generator}`), options);
}
```

**Comment by HuihuiWu-Microsoft** [comment]
Great work! Thanks for your effort!

**Comment by KevinTCoughlin** [comment]
@HuihuiWu-Microsoft I tested on my local using latest release and this now works for me. Can you confirm?

```shell
 npm i @microsoft/generator-sharepoint@1.15.0-rc.0 --prefix ./spfx
 ```

**Comment by HuihuiWu-Microsoft** [comment]
Hi @KevinTCoughlin , I tested to run yeoman generator by path and works well for me! Thanks!
