### ISSUE TITLE
SPFx extensions js files 404 every now and then

### ISSUE THREAD

**Issue by EldinHb** [SharePoint/sp-dev-docs#7866]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [x] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- 99.0.4844.84 (Official Build) (64-bit) chrome version
- 1.13.1 spfx 
- 14.18.3 nodejs

### Describe the bug / error

In short: we are experiencing the exact same problem described in this issue: https://github.com/SharePoint/sp-dev-docs/issues/3802

Because the issue is locked I want to ask for an update on this issue through this matter. But a small recap: 

Sharepoint adds a GUID to our bundles, these are (likely?) used for caching purposes. Sharepoint randomly loads the right js file but with a wrong GUID. That file is gone and gives a 404 error. 

### Steps to reproduce

1. Occur generally on or just after a Thursday GMT + 2
2. Occurs for multiple tenants, but generally not all at the same time
3. Affect all SPFx Extensions (when it happens)
4. Does not affect SPFx Webparts
5. The JavaScript files appears to be from an older versions of the App Package (we have started a log to confirm this assumption)
7. When an error occurs, the SPFx Extension does not load
8. Opening the Browser Console shows a 404 for our extensions. Copy pasting the url to the browser gives a 404 as well. 
9. Remove the File name & extension from the URL will open the container folder
10. The file does not exist anymore. Other files with a different GUID have replaced the missing ones. 
11. Copy and past the JavaScript's URL into a browser window will also show a 404 error
12. Remove the File name & extension from the URL will open the container folder (no errors)
13. This may not be an SPFx Extension bug but rather an Office 365 update issue?

### Expected behavior

For Sharepoint to try and load the correct js files.

**Comment by AJIXuMuK** [comment]
@EldinHb - could you please try few things? 
- adding `?sw=bypass` on the page where you're experiencing the issue
- could you check if the solution is checked out or published in the app catalog?
- is it working if you do hard refresh (ctrl+f5) on the page?
- is it happening in any browser?
- Could you try to redeploy the latest version of the solution once again?

**Comment by EldinHb** [comment]
Thanks for your response @AJIXuMuK 

Refreshing "fixes" this issue. But it randomly comes back though and so far we cant really find a way to predict when it will happen or how to replicate it. 

Solution is not checked out. 
We have tested it on Chrome and Edge initially. One of our clients reports this happens on Safari as well. 
We deploy every 2 weeks and the issue has been happening for a couple months now. So redeploying doesnt fix this.

**Comment by AJIXuMuK** [comment]
Thank you @EldinHb for your responses!
What about `?sw=bypass`?

**Comment by EldinHb** [comment]
Seems like our client who experiences the issue is unavailable until may 2. I'll get back to you after may 2.
