### ISSUE TITLE
Docs on how to trigger an action programmatically on AdaptiveCard?

### ISSUE THREAD

**Issue by jean182** [SharePoint/sp-dev-docs#7867]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I want to know if there's any documentation on how to trigger actions, basically I want to request for the user location using the action type `VivaAction.GetLocation` and currently the only way is using a button, If I try to trigger it using the navigator it only returns the action object without the location, if I do the same using a button it returns the action object with the location so I'm confused here on how to do this programmatically and there's no documentation on how to do it.

**Comment by AJIXuMuK** [comment]
@jean182  - unfortunately, there is no way to programmatically fire the action in ACEs.
But thank you for the feedback.

We will be discussing it internally.
