### ISSUE TITLE
Web Part Property Pane is collapsing when changing field value in Accordion mode

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#787]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Property Pane groups should not collapse when changing field values

#### Observed Behavior
Groups collapse when changing field values

#### Steps to Reproduce

- scaffold the project
- set `displayGroupsAsAccordion: true` for Property Pane Page
- set `isCollapsed: true` for Property Pane group
- run your web part
- start editing web part
- expand the group in Property Pane
- close the Property Pane
- start editing web part again
- enter some text to the text box field
- the group will automatically collapse

**Comment by manishgarg1** [comment]
@srideshpande  ?

**Comment by srideshpande** [comment]
@AJIXuMuK - Thanks for raising the concern. I see that it is reproducible. A bug is created for the issue and will be resolved according to the priority.

Thanks again!

**Comment by mpasarin** [comment]
@AJIXuMuK this has been fixed in our codebase, expect 2-3 weeks for the fix to roll out everywhere.
I'm going to close the issue. Feel free to re-open if after 3 weeks you still have the same problem.
Thanks for reporting it!

**Comment by AJIXuMuK** [comment]
Awesome!
Thanks for the fix!
