### ISSUE TITLE
Since when Sharepoint has a maximum of 2,000 lists and libraries in a site collection? What will happen?

### ISSUE THREAD

**Issue by magonzalezm** [SharePoint/sp-dev-docs#7873]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I've read there is a maximum of 2000 lists and libraries in a site collection, this is in the Sharepoint documentation, at least since December 2021.

[https://docs.microsoft.com/es-es/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits](https://docs.microsoft.com/es-es/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)

But before this date, there was no limit, the documentation before december says:
"There is no limit to the number of document libraries you can have on a site."

I have verified that since 6th April, the sites that are surpassing this limit of 2000 libraries, when you create a library, an error jumps with this message:
Exception from HRESULT: 0x8107140D
**But even if this happens, the library is created.**

**So my question is:**
- is this true? The error happens because of the limit?
- what will happen in the future if the site oversteps the limit? Will create library/list be disabled? Or this error will continue happening.
- If the limit is overpassed, what will be the consequence in the support / "guarantee"? 
- If there are consequences, is there a difference between passing the limit before december 2021 (when it was changed the limit) or after this date?.
- Wouldn't it be better to create a type of suscription to overpass the limit of 2000 libraries?
- Could you please give more info in general?

Thx.

**Comment by bcameron1231** [comment]
While I don't have the exact answers for you. 2,000 has always been a number to be aware of. Documentation dating back over a decade has always recommended to keep lists to under 2,000 as the interface for enumerating lists/libraries does not perform well beyond 2000.

My two cents - While every requirement is different, if you have over 2,000 lists or libraries in a given site, it gives me a feeling of a larger problem in how your architecture was implemented. It may be time to re-think/architect what has been built in your environment.

I hope someone from Microsoft will be able to answer the questions you have though.

**Comment by AJIXuMuK** [comment]
@bcameron1231 - thank you for the answer. 
I completely agree with you. The docs always recommend to plan accordingly.

**Comment by magonzalezm** [comment]
The document recommendations have changed, as far as I know, they never mentioned this limit, on the contrary they specify:
"There is no limit to the number of document libraries you can have on a site."

At the end, it has to be with an error of service update to provide optimizations in Sharepoint, surely related with this 2000-list limitation, but they have rolled it back, for the moment:
https://admin.microsoft.com/#/servicehealth/advisories/:/alerts/SP358241

Literally:
April 15, 2022 7:44 PM
Title: Users may be unable to create new document libraries in site collections

User Impact: Users may be unable to create new document libraries in site collections.

More info: Creations through both the user interface and Client Side Object Model (CSOM) method are affected.

Current status: Our deployment of the fix is progressing as expected, and users will experience relief incrementally as it reaches their environment. We expect that this process will complete by our next update.

Scope of impact: This issue may potentially affect any of your users attempting to create new document libraries in site collections via the user interface or CSOM method.

Start time: Tuesday, March 29, 2022, 9:39 PM (7:39 PM UTC)

Root cause: A recent service update intended to provide general service optimizations inadvertently disabled a previous configuration change, causing available routing infrastructure to be limited when requesting new document library creation.
