### ISSUE TITLE
SPFx WebPart Periodically not rendering, and showing error "There was a network problem, This may be a problem with a HTTPS certificate. Make sure you have the right certificate"

### ISSUE THREAD

**Issue by anasnakawa** [SharePoint/sp-dev-docs#7878]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: latest Chrome/Edge
- SPFx version: 1.4.1
- Node.js version: 8.9.4

### Describe the bug / error

Since last Sunday, many of our customers started to experience the following attached error
Note that we didn't publish any new versions recently, nor we did any changes to our product files that are published on a CDN.

> There was a network problem, This may be a problem with a HTTPS certificate. Make sure you have the right certificate

Our product is an SPFx Web Part, and our files are hosted on AWS Cloudfront CDN, 
No changes have been made recently in either area.

![image](https://user-images.githubusercontent.com/559002/162516461-84180453-edc8-4e61-85e1-20be1ff1a674.png)

Notes:
* People who were experiencing this issue were asked to clear the browser cache, and to use another browser, and that didn't help to prevent the issue from happening again
* since last Sunday, also other Web Parts that we do not own here, are also failing for another reason, see the attached image:
![image](https://user-images.githubusercontent.com/559002/162521161-6816f02e-e28b-4a4b-a384-ce9bab142533.png)

I have seen on Service health on Office365 that there were multiple incidents this week happening on Exchange Online and Microsoft Teams, could there be any connection between those issues and the incidents?

What's causing this? and how can we resolve this?

### Steps to reproduce

No stable steps to reproduce, you open a page, you might get an error on the web part and you might get the web part rendering perfectly, unfortunately, that's it.

### Expected behavior

A web part should not through such error, and should render without issues.

**Comment by anasnakawa** [comment]
Any update on this, please? it's been already three days, the issue still present and affecting 900 live SharePoint sites on Office365

**Comment by AJIXuMuK** [comment]
@anasnakawa - thank you for reporting this one.
I would ask you to check few things:
1. Could you add `?sw=bypass` parameter when loading the page where you see the issue? Will that fix the issue or no?
2. Could you check the Network for the requests to the AWS? If the request is declined or errored on AWS side - we can't do anything here.
3. Do you know if the customer made any policy changes, including restricting access by ip addresses or something similar?

**Comment by anasnakawa** [comment]
Thanks, @AJIXuMuK for your response,
Checking with the client about this.
