### ISSUE TITLE
PeoplePicker Id Mismatch with Sharepoint

### ISSUE THREAD

**Issue by DiogoBolt** [SharePoint/sp-dev-docs#7879]
While using principalTypes={[15]} (All) I'm getting a weird behaviour.

The id's I'm getting from PeoplePicker does not match with my list ID's.

If I choose Adele Vance and save. PeoplePicker gives Adele vance id 12, however in my sharepoint list it's saved as an existing group with ID 12
![162011584-2ac615d7-b013-4675-b2b7-b7284483366f](https://user-images.githubusercontent.com/7535853/162696033-f941fa5a-6ace-44d7-8a2a-ab0b76c58f5f.jpg)
![162011440-7e001fd5-a546-4c3b-9727-237772b10d85](https://user-images.githubusercontent.com/7535853/162696019-97606822-1a5d-4bd6-bf4c-fd32e98c2b7f.jpg)

This is my PeoplePicker configs :

`PeoplePicker disabled={this.state.isInPreview || (this.currentMappings && this.currentMappings.get("TargetUsers") === "-No Mapping-")} personSelectionLimit={1000} context={this.props.context} titleText={this.props.strings.properties.targetUsers} placeholder={this.props.strings.properties.targetUsersplaceholder} groupName={""} // Leave this blank in case you want to filter from all users ensureUser={true} onChange={(e) => { let target: number[] = []; e.forEach((elem) => { target.push(parseInt(elem.id)); }); this.setState({ targetUsers: { results: target } }); }} principalTypes={[15]} defaultSelectedUsers={this.state.targeted} resolveDelay={500} `

Am I doing something wrong? or is there an Id mismatch between people picker and sharepoint?

**Comment by RoelVB** [comment]
Are you aware that user IDs are site specific?
For example, if you have a PeoplePicker on `/sites/siteA` selecting an user ID and fill it into a list on `/sites/siteB`, this will select a different user/group in the target.

**Comment by DiogoBolt** [comment]
Hello! 
Thank you for answering , You are correct, when I use PeoplePicker on the same site collection the id's don't mismatch... however something else also happens.

I have a security group (SG1) and if I edit my item and add SG1 in the peoplepicker it works, and saves in the list... however, next time I load the page , the SG1 group doesn't appear as "Selected" on the PeoplePicker.

![image](https://user-images.githubusercontent.com/7535853/162954220-0a955f74-95d3-475a-a502-197742d3e861.png)

![image](https://user-images.githubusercontent.com/7535853/162954443-00860943-46b9-4253-b9b6-18204607fa8c.png)

I can add it to the list via PeoplePicker, but after it's added , it doesn't appear on PeoplePicker (eventhough it's already on the list) .


Also... about the first issue... is there any work around or does the webpart needs to be on the same site collection as the list it consumes? 

Thank you so much for the help

**Comment by AJIXuMuK** [comment]
@DiogoBolt - are you talking about `PeoplePicker` from PnP Controls?
If yes - please, close this issue and open a new one in the appropriate repo:
- PnP React Controls: https://github.com/pnp/sp-dev-fx-controls-react
- PnP Property Controls: https://github.com/pnp/sp-dev-fx-property-controls
