### ISSUE TITLE
error:installing the developer certificate for use with SPFx development

### ISSUE THREAD

**Issue by Avenlele** [SharePoint/sp-dev-docs#788]
After I created a solution in node.js command prompt ,I want to install the developer certificate like this:
![default](https://user-images.githubusercontent.com/31207814/29515412-e281f510-869e-11e7-8945-5719a2996dfb.png)
it throw errors.
Please help me,thanks

**Comment by Avenlele** [comment]
@manishgarg1  
![1503368452 1](https://user-images.githubusercontent.com/31207814/29545894-96be2c04-8723-11e7-8843-6c6324e7dd56.jpg)

error still be here.
I found I created a solution by  "yo @microsoft/sharepoint"
![7](https://user-images.githubusercontent.com/31207814/29546037-74628a64-8724-11e7-8a18-23870e160fef.jpg)

There is no  “node_modules“ folder here .

**Comment by waldekmastykarz** [comment]
Before you can run this command, you need to run `npm install` in the current project folder. That will restore project's dependencies and create the node_modules folder with all required packages, including gulp.

**Comment by Avenlele** [comment]
@waldekmastykarz  yes I run it in my current project folder ，It works well， before，I installed them  global . thank you!

**Comment by waldekmastykarz** [comment]
You're welcome @Avenlele
