### ISSUE TITLE
Cannot sync with teams any solution with SPFx Version 1.14

### ISSUE THREAD

**Issue by jjsanchez88** [SharePoint/sp-dev-docs#7880]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.14
- Node.js version 14.17.6
- etc

### Describe the bug / error

When update any sppkg package to SharePoint App Catalog and click on Sync with teams button, always get error. I´m tenant admin and it occurs also with "helloworld" solution. 

We have tried with several packages, getting always same result. 

### Steps to reproduce

1. Generate new SPFx solution (type webpart)
2. Add webpart to solution
3. gulp bundle --ship
4. gulp package-solution --ship
![Untitled](https://user-images.githubusercontent.com/55842834/162715142-0045bb29-4e03-4b47-ae9f-7c064eaece4b.png)

### Expected behavior

Ok sync with teams.

**Comment by yukumura** [comment]
I have the same problem.
I tried removing the app from Teams, recreated a new SPPKG package and released it on the app catalog (flag checked regarding global deployment). Next I try to use the Sync To Teams button and get the following error:

![image](https://user-images.githubusercontent.com/6943411/162731101-8fb5dd4b-428d-4b8c-800c-eab2d8b28d30.png)

**Comment by AJIXuMuK** [comment]
@yukumura @jjsanchez88 - could you please check that again?
I just tested the Add to Teams thing on multiple tenants using default scaffolded solution with SPFx v1.14.0 - no issues.
If you still experience an issue - could you please share the `request-id` value of `SyncSolutionToTeams` request (you can find it in Response headers) and also the tenant url? You can send it to aterentiev@microsoft.com if you don't want to share it publicly.

**Comment by jjsanchez88** [comment]
Yeah, I have tried it again and (now) it works... But las few days it appeared broken using default scaffolded solution with versions 1.14, 1.13 and 1.11. 

We could close this issue because it appears to be a temporal issue...

Thanks a lot for your help!
