### ISSUE TITLE
OOTB Viva Connections Analytics

### ISSUE THREAD

**Issue by GowthamiKothapalli** [SharePoint/sp-dev-docs#7882]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi , Is there way to get  no of clicks (count) on out of the box Viva connections dashboard cards please .

Thanks.

**Comment by AJIXuMuK** [comment]
@GowthamiKothapalli - sorry for the long delay.
Unfortunately, there is no way to get this kind of analytics.

But this is a good feedback.
