### ISSUE TITLE
SharePoint Search: `SourceId` is being ignored (PnPJS)

### ISSUE THREAD

**Issue by JoshuwayMorris** [SharePoint/sp-dev-docs#7883]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- [@pnp/sp](https://pnp.github.io/pnpjs/): "^3.2.0"

### Describe the bug / error

I am using [PnPJS](https://pnp.github.io/pnpjs/sp/search/) to consume the SharePoint Graph/API. 

I have [posted an issue on PnPJS](https://github.com/pnp/pnpjs/issues/2210). However, it has been suggested that I also post the issue here, in case there has been a change in the API. Any help or light on the issue would be greatly appreciated.

After specifying `SourceId` as part of the [PnPJS Search](https://pnp.github.io/pnpjs/sp/search/) `ISearchQuery` interface, the results returned are not from the expected source. Instead, they default to the SharePoint Online default _"Local SharePoint Results"_.

Please find below a screenshot of the response object after executing the search. 

As you can see, the correct `SourceId` (403cc987-1997-4f4a-9271-0a3815e3d7b4) appears in the `_query` property.

However, the `SourceId` in the `_raw` property has defaulted to the SharePoint Online default _"Local SharePoint Results"_ 
 (8413cd39-2156-4e00-b54d-11efd9abdb89).

This implementation **was working**, and only **stopped working  in the last few days**, suggesting are potential change the API implementation?

Thank you!

<img width="2022" alt="Search Response" src="https://user-images.githubusercontent.com/48333553/162970434-fb1f4107-be50-4dea-975d-8d48f2fd8bf1.png">

### Steps to reproduce

Please find below a screenshot of the code executed. Please note, this code utilises [PnPJS](https://pnp.github.io/pnpjs/sp/search/) to make an API request.

```
// Populate search query
const searchQuery: ISearchQuery = {
    RowLimit: searchService.ItemsPerPage,
    SourceId: sourceId, // 403cc987-1997-4f4a-9271-0a3815e3d7b4
    SelectProperties: searchService.SelectProperties,
    SortList: searchService.SortList,
    TrimDuplicates: false,
    StartRow: request.Page * searchService.ItemsPerPage,
    Refiners: searchService.Refiners.join(','),
    RefinementFilters: request.RefinerTokens,
    RankingModelId: rankingModelId,
    EnableNicknames: true,
    EnablePhonetic: true,
    EnableInterleaving: true,
};

// Prepare query
const query = SearchQueryBuilder(querytext, searchQuery)

// Retrieve results
const results: SearchResults = await ConfigService.sp.search(query);
```

<img width="615" alt="Search Code" src="https://user-images.githubusercontent.com/48333553/162970636-bbb62d7e-e71a-49ed-a79e-9dfefecb88d6.png">

### Expected behavior

Search results should be returned from the source specified in the request (`SourceId: 403cc987-1997-4f4a-9271-0a3815e3d7b4`).

**Comment by AJIXuMuK** [comment]
@wobba - are you aware of any changes in that area?

**Comment by patrikhellgren** [comment]
@JoshuwayMorris @AJIXuMuK This seems to be an ongoing issue since some time. We have seen this in some different forms over the past couple of months and have had several support cases opened with Microsoft. They resolved it but it started appearing again, resolved it again, appeared again in another form but still result source related so there seems to be some general issues with result sources. It would be great if Microsoft could be made aware of that there are others seeing similar issues so that it once and for all could be resolved.

See microsoft-search/pnp-modern-search#2012 for more context.

**Comment by wobba** [comment]
I recommend logging it with Microsoft support.

**Comment by JoshuwayMorris** [comment]
Thank you all for your replies (@AJIXuMuK, @patrikhellgren, @wobba)

We logged the issue with Microsoft, but we have not received a reply yet. However, our services started working again as expected last week. So we can only assume that Microsoft resolved the issue on their end.

Therefore, I am going to close this issue, but thank you all for your help.
