### ISSUE TITLE
Configure sass task libfolder

### ISSUE THREAD

**Issue by magnusdanielson** [SharePoint/sp-dev-docs#7886]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: any
- SPFx version: 1.14
- Node.js version 14.18.1
- Windows 11
- VS Code

### Issue description

The sass-task in the build pipeline assumes the files are in the "lib"-folder. That is correct for a standard setup. In our case we need to do some pre typescript build tasks so the sass files will be located in another temporary folder.

If I change line 67 in node_modules\@microsoft\gulp-core-build-sass\lib\SassTask.js from
`cssOutputPath = path.join(this.buildConfig.libFolder, srcRelativePath);`
to
`cssOutputPath = path.join('mytempfolder', srcRelativePath);`
everything works as expected. 

It would be great if we could set that from configuration instead. We initiate the configuration with below call. It would be great if we could assign the libFolder in that call.

`    

    sass.default.mergeConfig({
      libFolder: 'mytempfolder', /* not allowed yet */
      preamble: '/* tslint:disable */',
      postamble: '/* tslint:enable */',
      sassMatch: ['src/**/*.scss', 'src/**/*.sass'],
      useCSSModules: false,
      warnOnCssInvalidPropertyName: true,
      dropCssFiles: true,
      warnOnNonCSSModules: true,
      // Cast is needed due to autoprefixer types mismatch due to workspace install in odsp-web
      autoprefixerOptions: {
        overrideBrowserslist: ['> 1%', 'ie >= 11']
      }
    });
`

**Comment by AJIXuMuK** [comment]
Hi @magnusdanielson - just to clarify: do you have `scss` files outside of lib only? or any other files too?
The config parameter can be used in other tasks to. So, if we even allow to set it, it most probably will break the build for you anyway.
I would include some "copy" task in your custom routine. I don't think we want to complicate the OOB tooling into monorepo scenarios too much

**Comment by magnusdanielson** [comment]
So I have all source file in /src folder. I have added a pre build gulp task that modifies the source files (.ts .html .css) so that they can be tsc compiled to a working Aurelia2 app. The destination of the gulp task i now "autemp". If I want to include the spfx sass modules they need to be compiled to the "autemp" folder before tsc. If that is done everything works perfectly.

Here is a repo of everything working, but you have to make the change to SassTask.js file as described above or comment out the 
`import styles from './HelloWorldWebPart.module.scss';`
and depending lines.

Most of the modifications are in the gulp.js file. Here is the repo I have been using, it is the gulp branch.

https://github.com/magnusdanielson/spfxau2/tree/gulp

Here are some info on Aurelia https://aurelia.io/

I have made the pnp yeoman generator for Aurelia1 but I would like to create a new one for coming Aurelia2. https://pnp.github.io/generator-spfx/howtos/aurelia/

**Comment by magnusdanielson** [comment]
I got it working. Thank you :)
