### ISSUE TITLE
microsoft/sp-dialog in property pane

### ISSUE THREAD

**Issue by ahu0** [SharePoint/sp-dev-docs#7889]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We use `@microsoft/sp-dialog` to create dialog.
```
export class TestDialog extends BaseDialog {
    public render(): void {
        // Insert the HTML
        this.domElement.innerHTML += htmlComponent;
    }

    public getConfig(): IDialogConfiguration {
        return {
            isBlocking: true,
        };
    }

    protected onAfterClose(): void {
        super.onAfterClose();
    }
}

export default class TestWebPart extends BaseClientSideWebPart<ITestWebPartProps> {
    public render(): void {
            const testDialog = new TestDialog();
            testDialog.show();
        }
```
 It works fine when we test it locally (`run `gulp serve`). However, it displays the dialog in the property pane after deploying it to the Sharepoint page. What can we do? Thank you!
![Screenshot from 2022-04-13 10-19-16](https://user-images.githubusercontent.com/97566473/163227076-1898a8ae-6a68-49cf-b847-d179088d39a5.png)
![Screenshot from 2022-04-13 10-09-12](https://user-images.githubusercontent.com/97566473/163227117-40c748ec-0951-411b-b848-1da4f59bb2ed.png)
.

### Steps to reproduce

1. Deploy the web part package to app catalog
2. Add the web part to a sharepoint page
3. Notice it displays the dialog in the property pane

### Expected behavior

Dialog is in the correct place.

**Comment by AJIXuMuK** [comment]
Thanks @ahu0 for reporting this one!
I assume you're using isolated web part, correct?

Also - could you please describe what you're trying to achieve with the dialog?

**Comment by ahu0** [comment]
Yes, we are building isolated web part. We need to implement a document picker dialog (Embed a document picker within an <iframe> in the dialog), and we also need a dialog to inform user that they need to set up app config. Speak of app config, does Sharepoint support an app config page? And is there a way to ask user to set up app config when they install the app in app store?

**Comment by AJIXuMuK** [comment]
@ahu0 - no, SPFx doesn't support any configuration page during sppkg deployment to the app catalog (if I understand you correctly).
For the web part - property pane is the correct way to configure it.

Usage of dialogs as well as panels is tricky in isolated web parts as the web part itself it an `iframe` and has limited real estate.

For the informing the user (I believe this is the scenario when call the dialog right in `render` and see it in the property pane) I would recommend using [Placeholder](https://pnp.github.io/sp-dev-fx-controls-react/controls/Placeholder/).
For the document picker - it should work fine as it is displayed based on some user interaction I believe. But again, if your web part is added, for example, in a column with small width - it will be trimmed.

Do the explanation and options make sense?

**Comment by ahu0** [comment]
Thanks for the recommendation of the `placeholder`, but we are not planning to use react. 
The document picker dialog has the same issue. Call the dialog in render, but see it in the property pane.

**Comment by AJIXuMuK** [comment]
@ahu0 - you can implement something similar to `placeholder` by yourself.
To be clear: for now there _will be_ such an issue with the dialogs if you call them directly in `render`, not as part of user interaction.
And unfortunately, it will not changed relatively soon.
We have a backlog item to overview dialogs and isolation but it is not a high priority for now.

**Comment by ahu0** [comment]
I see, thanks for the clarification!

**Comment by AJIXuMuK** [comment]
Hi @nhayeslucid,

As mentioned in the comment above:

> Usage of dialogs as well as panels is tricky in isolated web parts as the web part itself is an `iframe` and has limited real estate.

To clarify on that: isolated web part's code is running in a separate `iframe` loaded to the page. And all the components/controls you're rendering will "live" in the web part's `iframe` too, not on the page itself.
I totally understand your request to display the dialog on the page, but it would break isolation.
