### ISSUE TITLE
Tenant Wide Deployment of SharePoint Framework Extensions - Replace Screen Capture from Classic App Catalog

### ISSUE THREAD

**Issue by rob-windsor** [SharePoint/sp-dev-docs#7892]
The screen capture of the **Do you trust...** dialog should be replaced with a screen capture of the **Enable app** panel used in the modern app catalog. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e41df74-a651-cfa5-a538-9397e6793f52
* Version Independent ID: 9f272325-fdb3-68e3-634b-e7428128f75b
* Content: [Tenant Wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions)
* Content Source: [docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Looks like someone removed all the screenshots, so nothing to replace :-/

**Comment by rob-windsor** [comment]
The published version still has the screen capture. Is there an unpublished PR that removes it?

![image](https://user-images.githubusercontent.com/5740654/225900623-a231508d-09ad-4e40-8141-1d42181a45ff.png)

**Comment by andrewconnell** [comment]
My bad... I processed this issue way too fast. I'll get this fixed. Thanks for the follow up @rob-windsor
