### ISSUE TITLE
view-commandbar-formatting [Exit Grid View] button missing

### ISSUE THREAD

**Issue by teixeire** [SharePoint/sp-dev-docs#7895]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hello all,

I was using 'view-commandbar-formatting.md' and find out that the set up as below work well for when have not clicked the "edit Grid View" yet, means that we do not have the key button for 'exit grid view' to be set up, besides the button 'undo'.

"key": "editInGridView",
"text": "Massive Request",
"iconName": "EditTable",
"primary": true

![image](https://user-images.githubusercontent.com/83093714/164020646-dff9cf57-e0d1-468f-93d0-8de7433b03bd.png)
![image](https://user-images.githubusercontent.com/83093714/164020675-bd5562f3-e9af-4aa6-9733-e12a2b5fe1b0.png)

**Comment by shagra-ms** [comment]
A new command key `exitGridView` has been added.
