### ISSUE TITLE
view-commandbar-formatting

### ISSUE THREAD

**Issue by teixeire** [SharePoint/sp-dev-docs#7896]
### Discussed in https://github.com/SharePoint/sp-dev-docs/discussions/7877

<div type='discussions-op-text'>

<sup>Originally posted by **teixeire** April  8, 2022</sup>
Hello all,

I was using 'view-commandbar-formatting.md' and find out that the set up as below work well for when have not clicked the "edit Grid View" yet, means that we do not have the key button for 'exit grid view' to be set up, besides the button 'undo'.

"key": "editInGridView",
        "text": "Massive Request",
        "iconName": "EditTable",
        "primary": true

![image](https://user-images.githubusercontent.com/83093714/162470496-2933d2bf-bff2-49b0-8c6f-100ee300840c.png)
![image](https://user-images.githubusercontent.com/83093714/162470594-543b3cc1-1eb8-4c5e-8a24-df5dae18f780.png)

Does anyone has any solution or it would be a improvement ?</div>

**Comment by shagra-ms** [comment]
We have added a new key - `exitGridView` for the same. The fix is now rolled out to all tenants. 

Please reopen if this still doesn't work for you. Thanks for reporting this.
