### ISSUE TITLE
error TS2322: Type 'ServiceScope | ServiceScope' is not assignable to type 'ServiceScope'

### ISSUE THREAD

**Issue by khaledfarghaly** [SharePoint/sp-dev-docs#7897]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx 1.14.0
- Node.js 12.22.12
- studio code
-

### Describe the bug / error

I upgraded my SPFX project from 1.12.1 to 1.14.0

When I build the project. I got this error message 
 error TS2322: Type 'ServiceScope | ServiceScope' is not assignable to type 'ServiceScope'

and here is the list library that I use 
"@microsoft/sp-component-base","@microsoft/sp-core-library","@microsoft/sp-dynamic-data","@microsoft/sp-http","@microsoft/sp-loader","@microsoft/sp-lodash-subset","@microsoft/sp-page-context","@microsoft/sp-property-pane","@microsoft/sp-webpart-base","@pnp/common","@pnp/modern-search-extensibility"

### Steps to reproduce

1.get project spfx 1.12.1
2.upgrade to 1.14.0

### Expected behavior

service scop should be working

**Comment by AJIXuMuK** [comment]
Thank you @khaledfarghaly for reporting this one.
Could you provide a bit more info:
- The line of code where you're experiencing this issue
- The content `package.json`

Could you also try to remove `node_modules` folder and `package-lock.json` (or `yarn.lock`) and check if the error is still there?
