### ISSUE TITLE
Too many file created by yo @microsoft/sharepoint

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#79]
I noticed nearly 97,049 Files, 16,863 Folders created during the helloworld-webpart development. If i try to delete i am not able to delete the folder due to long folder/file names. Is is it a normal behavior? 

I am using a free tool to delete such files / folders.

**Comment by vman** [comment]
> Make sure you are running V3 of npm by running the following command
> 
> npm -g install npm@next

https://github.com/SharePoint/sp-dev-docs/wiki/Setup-your-machine

That should get rid of your long folder/file names issue and the size of your node_modules folder should be relatively smaller too.

**Comment by sprider** [comment]
Vardhaman,

I did this already but still i tried to reinstall everything again and found the following numbers which is good 
30,056 Files, 4,000 Folders

Deletion of root folder is still an issue.

**Comment by patmill** [comment]
This is effectively tracked here - https://github.com/SharePoint/sp-dev-docs/issues/59
