### ISSUE TITLE
Is their anyway to add extensions to a webpart?

### ISSUE THREAD

**Issue by gurleen23** [SharePoint/sp-dev-docs#790]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi, 
I know this might sound a bit weird. But, Is their anyway to add extensions to a webpart rather than adding it to a list or page?
So, I have been working on field extensions lately, it works perfectly fine on a list. But, when I try to add that list on a page in the form of list preview webpart, that list doesn't work anymore. So, Is there anyway to do this?

Thanks!

**Comment by mcmynn83** [comment]
No there is not at this time.
