### ISSUE TITLE
Modern pages: Collapsible section label is not searchable

### ISSUE THREAD

**Issue by salascz** [SharePoint/sp-dev-docs#7900]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hello,
collapsible section were introduced quite a long time ago. Unfortunately, label of such a section does not seem to be included in search index. Was it intended or is it a bug? - I would expect the same behaviour as for other headers (although its a different piece of code, I know...)

![image](https://user-images.githubusercontent.com/5662939/164168427-5be6a834-be28-471a-9b30-ded2f587fe95.png)

Thanks
Jiri

**Comment by AJIXuMuK** [comment]
Thank you @salascz for reporting this issue.
I have shared the concerns with the owning team.
But this issue will be closed as it is not a dev issue.
