### ISSUE TITLE
Markdown webpart doesn't process HTML

### ISSUE THREAD

**Issue by Cobest** [SharePoint/sp-dev-docs#7901]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### Describe the bug / error

In Sharepoint online, when creating the following table using the webpart 'Markdown', the HTML noted here as 'myHTML' is not parsed, although `<ul>` and `<il>` adquire in the Webpart text a different color and thus it seems it understands them.
As a result, confirmed by Microsoft Help Center, there is currently no way to create simple HTML in Sharepoint online, feature that was possible through '</> Embed' webpart in all previous Sharepoints.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
| MyHTML: `<ul><li>item1</li><li>item2</li></ul>`| See the list | from the first column|

### Steps to reproduce

1. Open Sharepoint online (www.xyz.sharepoint.com/sites/mySite)
2. Add webpart 'Markdown'
3. Add the following Markdown information:
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
| <ul><li>item1</li><li>item2</li></ul>| See the list | from the first column|
```

4. The 4rth row, first column should show 2 items in a list, however it shows instead a text. As a result, we can't make tables with two list items in the same cell.

### Expected behavior

Expected behavior as in Stackoverflow:
https://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table

**Comment by AJIXuMuK** [comment]
@Cobest - unfortunately we're not supporting HTML in Markdown web part.
And there are no plans for any changes in this area.
