### ISSUE TITLE
SPFX Tenant Wide Extension: Exclude/Disable extension for select sites

### ISSUE THREAD

**Issue by Anonimiss** [SharePoint/sp-dev-docs#7907]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have some tenant wide extensions that I would like to disable or remove from a handful of SharePoint sites.  Is this at all possible or is there a better recommended approach to achieving my need?

**Comment by AJIXuMuK** [comment]
@Anonimiss - unfortunately no.
You can either enable it globally, or site by site.
One of the options to achieve your goal could be some "config" list or file that you could read during `onInit` and make decision if the extension should be visible/active on this or that site.
