### ISSUE TITLE
/_layouts/15/userphoto.aspx has stopped working

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7909]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I have several webparts that display the current user picture.
/_layouts/15/userphoto.aspx is not returning the user photo anymore. The URL is redirected to **_vti_bin/afdcache.ashx/_userprofile/userphoto.jpg** and it displays a _ERROR 403: Time-Limited URL validation failed_.

### Steps to reproduce

1. In the Hello webpart and an img element with src https://[DOMAIN]/[SITE]/_layouts/15/userphoto.aspx?size=S&accountname=[USER ACCOUNT]
2. Check that the image is not rendered
3. Check that the image source is redictected to https://[DOMAIN]/_vti_bin/afdcache.ashx/_userprofile/userphoto.jpg?_oat_=[LONG TEXT HERE]&size=S&accountName=[USER ACCOUNT]
4. Note that an error is displayed when trying to open the image URL, saying ERROR 403: Time-Limited URL validation failed

### Expected behavior

The URL points to the user picture

**Comment by benjacernuda** [comment]
I have the same behavior in my tenant, It has started to happen today
