### ISSUE TITLE
Error in package-solution Gulp task if change the path to sppkg

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#791]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`gulp package-solution` runs without error after changing `zippedPackage` property in the config.
#### Observed Behavior
`gulp package-solution` fails with
```
Error - 'package-solution' sub task errored after 103 ms
 error is not a function
```

#### Steps to Reproduce

- scaffold the web part project
- go to config/package-solution.json
- "zippedPackage" property to contain subfolder like "/solution/release/hello-world.sppkg"
- run `gulp bundle`
- run `gulp package-solution`

**Comment by AJIXuMuK** [comment]
Actually, the error is 'No such file or directory'.
So the fix might be to check if subfolder exists and create it if not.
Also, it would be great to log the initial exception but not the 
```
Error - 'package-solution' sub task errored after 103 ms
 error is not a function
```

**Comment by nickpape-msft** [comment]
The experience here should definitely be better. I've update the package-solution task to ensure the subfolder exists before writing the solution. I didn't see the same `error is not a function` message as you, however. You will see these changes in the next release.

**Comment by AJIXuMuK** [comment]
Thanks @nickpape-msft for the update!
