### ISSUE TITLE
Deprecation of Classic SharePoint

### ISSUE THREAD

**Issue by WorTony** [SharePoint/sp-dev-docs#7913]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi,
I’m hearing / reading elsewhere that SharePoint classic has been deprecated so can you clarify whether the statement “We're not deprecating the "classic" experience; both "classic" and "modern" will coexist.” In the document https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations is correct?

If it’s not correct, can you update the document please.

Thanks

Tony Pounder
@WorTony

**Comment by AJIXuMuK** [comment]
Hello @WorTony,
The Classic SharePoint is not deprecated. And some features, like List Settings, is available in Classic only.
We strongly recommend to use Modern experience as the default one. But Classic is still there.
