### ISSUE TITLE
generator-sharepoint and spfx 1.15 beta 6 is broken on modern systems without python 2

### ISSUE THREAD

**Issue by ramzzzay** [SharePoint/sp-dev-docs#7920]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.15 beta 6
- Node.js version: v16.14.2 Mac m1 arm64
- zsh 5.8

### Describe the bug / error

`@microsoft/generator-sharepoint` and `spfx` 1.15 beta 6 are depends on `node-gyp -v v3.8.0` when compiling `node-sass` and problem is: it depends on `python2` that is obsolete **2 years ago** and have been removed from modern OS, for example, in my case -- macOS 12.3 m1.

`npm ERR! code 1
npm ERR! path /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /Users/ramzay/.nvm/versions/node/v16.14.2/bin/node /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/ramzay/.nvm/versions/node/v16.14.2/bin/node',
npm ERR! gyp verb cli   '/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.2 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/ramzay/.nvm/versions/node/v16.14.2/bin/node" "/Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/ramzay/Documents/tmp/spfx_preview_test/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1`

### Steps to reproduce

0. Mac m1 with macOS 12.3, `node -v v16.14.2`
1. npm install @microsoft/generator-sharepoint@next --global || or upgrade spfx project from 1.14 to 1.15 beta 6

### Expected behavior

Compile node-sass without errors by using modern `node-gyp` with python3 support and then installs `@microsoft/generator-sharepoint` and `spfx` 1.15 beta 6

**Comment by ramzzzay** [comment]
@AJIXuMuK happens :)

I'm awaiting spfx release with node v16 support to test, how it will improve (or not?🤣) build time on my m1 Mac without Rosetta 2 translation layer. :)

**Comment by AJIXuMuK** [comment]
@ramzzzay - yes, it's a part of updating to node 16.
We have some internal dependencies to resolve before we can make it happen for SPFx itself
