### ISSUE TITLE
Selected files from media action type are not returned

### ISSUE THREAD

**Issue by manufz** [SharePoint/sp-dev-docs#7921]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.15.0-beta.6

### Describe the bug / error

When using the [VivaAction.SelectMedia](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14?blog#new-action-types-for-media-and-geolocation)  action type in an ACE the selected files are not returned from the onAction method.

### Steps to reproduce

1. Add media action type to the adaptive card template
```
{
      "type": "VivaAction.SelectMedia",
      "id": "files",
      "parameters": {"mediaType": "MediaType.Image", "allowMultipleCapture": true, "maxSizePerFile" : 200000, "supportedFileFormats": ["jpg"]},
      "title": "${selectFileButton}"
}
```

2. Retrieve data via onAction method inside QuickView class
```
public onAction(action: IActionArguments): void {
    console.log(action);
}
```

3. The onAction method does not return any selected files.

### Expected behavior

Selected files should be returned among other (text) values.

**Comment by a1mery** [comment]
I'm having the same issue with 1.15.2

**Comment by AJIXuMuK** [comment]
@manufz @a1mery @dcashpeterson just checking - based on [tutorial](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/actions/media-upload/mediauploadtutorial#implement-the-onaction-function) you can use a specific typings for the arguments. I understand it should be returned anyway using `console.log`.
But want to double check if the issue is still there if you follow the tutorial.

**Comment by dcashpeterson** [comment]
@AJIXuMuK let me go through the tutorial with the latest build. Last time I checked the params were still not working but let me confirm.

**Comment by dcashpeterson** [comment]
@AJIXuMuK This is resolved.
