### ISSUE TITLE
Breaking change - Searching for NormUniqueId now requires {}

### ISSUE THREAD

**Issue by cawillwe** [SharePoint/sp-dev-docs#7926]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Microsoft Search

### Describe the bug / error

MS Search 'NormUniqueId' managed property value syntax has changed from 'GUID' to '{GUID}'.
All the queries that used old syntax stopped working.

We had been using NormUniqueId in this way due to the suggestion made  on this issue:

https://github.com/SharePoint/sp-dev-docs/issues/7160

### Steps to reproduce

Execute query to obtain result for an item. Observe the NormUniqueId property.

### Expected behavior

Support old syntax of the 'NormUniqueId' Managed Property in the search results. 

Example using rest API:

This does not return a result:
/_api/search/query?querytext=%27NormUniqueId:55555555-5555-5555-5555-555555555555%27&selectproperties=%27NormUniqueId%27&clienttype=%27ContentSearchRegular%27

This does:
/_api/search/query?querytext=%27NormUniqueId:**{**55555555-5555-5555-5555-555555555555**}**%27&selectproperties=%27NormUniqueId%27&clienttype=%27ContentSearchRegular%27

Twitter discussion: https://twitter.com/vesajuvonen/status/1519303753521938433

**Comment by natpdeee** [comment]
In addition, it seems like uniqueID in some tenants have brackets {} and some of them don't have.

Search Query Results from different tenants:
![image](https://user-images.githubusercontent.com/20945009/170400551-b28b79e4-8dee-49cb-b91c-651c2048acae.png)

**Comment by wobba** [comment]
@cawillwe can you retry, and ensure you use the schema casing of `NormUniqueID` on your query, as casing on properties can have an impact on how it works. I blogged briefly about casing at https://www.techmikael.com/2019/02/eh-ok-beware-of-casing-when-using.html, and seems to apply to more properties

**Comment by wobba** [comment]
This has been fixed.
