### ISSUE TITLE
Issue with Board View using custom List formatting "inlineEditField" and "columnFormatterReference" in "customCardProps"

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#7927]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

since all is json with pre defined properties not enviroment detail is needed.

### Describe the bug / error

When Power user have "**Board**" view and is formatting view with JSON and need to create a dialog "**customCardProps**" the following properties inside the customcard doesn't work (**cannot edit**) "**inlineEditField**" and "**columnFormatterReference**"  for a choice field doesn't appear with fields formatted just the raw data text.

Issue:
![image](https://user-images.githubusercontent.com/8522348/165692200-1975497f-4c92-44d4-8539-e9e910fd5853.png)

### Steps to reproduce

1. Create New Microsoft List.
2. Create support fields and choice field with multiple values and for each choice associate color formatting.
3. Create new View and select "**Board**"
4. Access to "**Format View**" and add custom json with property "**customCardProps**"
5. When formatting JSON inside "customCardProps" include  "**inlineEditField**" and "**columnFormatterReference**" options.
6. Save format and validate if options are working.

### Expected behavior

When user is using View "**Board**" and click in a custom view JSON format with "**customCardProps**" the options  "**inlineEditField**" and "**columnFormatterReference**" should work as image below:

![image](https://user-images.githubusercontent.com/8522348/165694077-ed2bc3a0-96a2-46d8-be0c-d916c6dffccb.png)

**Comment by aaclage** [comment]
@shagra-ms 
I would like to address you this issue regarding declarative JSON Microsoft List

**Comment by shagra-ms** [comment]
@aaclage Thanks for reporting this. Will check.

**Comment by aaclage** [comment]
Fixed with https://github.com/SharePoint/sp-dev-docs/issues/9614
