### ISSUE TITLE
KQL Search with HubSite scoping seems to be dropping results

### ISSUE THREAD

**Issue by jhholm** [SharePoint/sp-dev-docs#7928]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Not applicable, as this is a Rest API issue. Tested with both newest Chrome and Edge.

### Describe the bug / error

I've used to create SharePoint Result Sources that had hubsite search scopes with KQL. These were used in PnP Modern Search Web Parts. Some breaking change seems to have happened last week.

Looking at how M365 search handles KQL hubsite scoping, we can see the following query in the querymodification:
```
(DepartmentId:{HubSiteGuid} OR DepartmentId:HubSiteGuid OR RelatedHubSites:HubSiteGuid)
```
So it seems that M365 search is already searching against DepartmentId with and without {}. In general I've noticed that in my tenants the field still has {} in the GUID and using DepartmentId:GUID doesn't return any results at all.

As an example I've been using the following queries that have worked:
* **PromotedState:0 DepartmentId:"{HubSiteGuid}"** - List all content pages on hub with guid HubSiteGuid
* **PromotedState:2 DepartmentId:"{HubSiteGuid}"** - List all news pages on hub with guid HubSiteGuid
* **contentclass:STS_Site DepartmentId:"{HubSiteGuid}"** - List all sites on hub with guid HubSiteGuid

I've noticed that some results are dropping on some tenants. And on my developer tenant this week DepartmentId querying doesn't seem to work at all on newly indexed items.

Changing the KQL queries from **DepartmentId:"{HubSiteGuid}"** to **RelatedHubSites:"HubSiteGuid** seems to fix this issue and give a "more correcter" (sic) result set. We are not using associated hubs, so semantically the search is still ok. I've checked that results are still returning the correct DepartmentId, but the query is just not working as it should. Tested in four different tenants so far with the issue showing in three customer tenants. If no associated hubs are used, the search results should be the same.

### Steps to reproduce

Easiest to test with e.g. SP Editor Chrome or SharePoint Search Query Tool.

Select a hubsite you want to test. **The hubsite you are testing with should not have associated hubs, as semantically the "fixed search query" would also add the associated hubs to the search.** Get the HubSiteGuid to use in search with e.g. PnP Powershell or SP Editor chrome.

Good examples of search query tests:
1. PromotedState:0 DepartmentId:"{HubSiteGuid}"
2. PromotedState:2 DepartmentId:"{HubsiteGuid}"
3. contentclass:STS_Site DepartmentId:"{HubSiteGuid}"

Check the result counts (note possible duplicate results)

Test again by chainging DepartmentId to RelatedHubSites managed property
1. PromotedState:0 RelatedHubSites:"HubSiteGuid"
2. PromotedState:2 RelatedHubSites:"HubsiteGuid"
3. contentclass:STS_Site RelatedHubSites:"HubSiteGuid"

Check the result counts and see if they match the previous queries.

Out of 4 tested tenants I had different results on 3.

### Expected behavior

The search results returned should be the same in both cases.

**Comment by wobba** [comment]
This should now be resolved.
