### ISSUE TITLE
Blank page and missing app in webpart selection menue after adding spfx package to app-catalog and click on 'get update' it in sitecollection contents

### ISSUE THREAD

**Issue by RoSchoe** [SharePoint/sp-dev-docs#7929]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - jede
- SPFx version 1.14.0
- Node.js version 14.18.1
- pnpjs  2.5.0

"dependencies": {
    "@fluentui/react": "^8.67.0",
    "@microsoft/sp-core-library": "1.14.0",
    "@microsoft/sp-lodash-subset": "1.14.0",
    "@microsoft/sp-office-ui-fabric-core": "1.14.0",
    "@microsoft/sp-property-pane": "1.14.0",
    "@microsoft/sp-webpart-base": "1.14.0",
    "@pnp/graph": "^2.5.0",
    "@pnp/logging": "^2.4.0",
    "@pnp/sp": "^2.5.0",
    "@pnp/spfx-controls-react": "^3.7.2",
    "@pnp/spfx-property-controls": "^3.2.0",
    "office-ui-fabric-react": "7.174.1",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },

### Describe the bug / error

It is a little bit tricky, webpart is running fine on several tenants but shows blank page on other tenants after rollout to app-catalog.
If webpart was included  in a page before update it shows blank after update the app to the new version in site-contents of the sitecolleciton.
There is no information about any loading-error in console.
The webpart disappears from webparts-selection-menue of the page 

It seems to be a deployment bug from app catalog????

Webpart shows content if it is running with debug mode (from local).

### Steps to reproduce

1. Load WebPart (new Version to existing one) to App-Katalog
2. Update App in SiteCollection (Contents) "Get it"
3. WebPart shows blank -> and is missing in webpart selection menu of page

### Expected behavior

Deploy to app catolog, update in sitecollection contents -> all is running fine

**Comment by AJIXuMuK** [comment]
Hi @RoSchoe - thank you for reporting this issue.
Could you please share the content of `package-solution.json` file?
Thanks!

**Comment by RoSchoe** [comment]
seems to be like
https://github.com/SharePoint/sp-dev-docs/issues/1253

**Comment by RoSchoe** [comment]
Solution:
Delete App in App-Catalog. Delete it from Trash of App-Catalog.
Upload-App again -> all fine.

**Comment by AJIXuMuK** [comment]
@RoSchoe - could you please try increase the version of feature in `package-solution.json` when you're adding a new web part?
This one:
```bash
"features": [{
  "title": "profile-single-page Feature",
  "description": "The feature that activates elements of the profile-single-page solution.",
  "id": "12b5ded8-989a-4a24-8210-1a926e801dc3",
  "version": "1.0.1.5" // update me
}]
```
