### ISSUE TITLE
onDispose() not being called when web part is deleted

### ISSUE THREAD

**Issue by ayee-lucid** [SharePoint/sp-dev-docs#7933]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - 99.0.4844.74
- SPFx version - 1.13.1
- Node.js version - v14.18.3

### Describe the bug / error

I am trying to have some custom cleanup code be run when our web part is deleted. I have overridden the `onDispose` method, but when I delete the web part the cleanup code doesn't seem be executed. Here is the overridden method to reproduce:
```
protected onDispose(): void {
        console.log('Deleting web part');
        super.onDispose();
}
```

### Steps to reproduce

1. Use the code in the description to override the `onDispose` method
2. Create a new SharePoint page and create a new web part
3. Delete the web part
4. See that "Deleting web part" is not logged in the console

### Expected behavior

Custom clean up code in the `onDispose` method is executed. "Deleting web part" is logged to console.

**Comment by AJIXuMuK** [comment]
@ayee-lucid - thank you for reporting this one.
I've just tested the behavior on newly created project - and it seems fine.
I used v1.14.0, React template.

Could you please double check that it's still an issue? Maybe it was some glitch?
If it's still a repro - could you please share your solution (code) with me?

**Comment by ahu0** [comment]
It works locally, but it doesn't work after being deployed.

**Comment by AJIXuMuK** [comment]
@ahu0 - do you have an example and some specific steps?
I have tested the deployment as well, not only local version in workbench.

**Comment by nhayeslucid** [comment]
Here is what this is looking like on our end. We have that method @ayee-lucid wrote earlier. For some reason, the onDispose is only getting called when you first click "Edit Web Part" and then delete the web-part
![sharepoint-onDispose](https://user-images.githubusercontent.com/103464945/166554420-b912c026-0c52-478e-9108-a0f247e205c0.gif)

**Comment by AJIXuMuK** [comment]
Do you have an isolated web part?

**Comment by ahu0** [comment]
Yes

**Comment by AJIXuMuK** [comment]
@ahu0 - thank you for the information.
I will check this scenario.
But to be on the same page: isolated web part is an iframe. And when you delete it from the page, the whole iframe is removed.
Meaning all local client-side resources are automatically disposed.

**Comment by ahu0** [comment]
Thank you! When we delete a web part, we need to make a request to delete something in our database

**Comment by nhayeslucid** [comment]
Is there a different function that does what we are looking for instead of onDispose @AJIXuMuK?

**Comment by nhayeslucid** [comment]
That would awesome if you all could look into it, as it is a feature that would help our database management a bunch.
Thank you for your help @AJIXuMuK !

**Comment by AJIXuMuK** [comment]
Closing this issue as `onDispose` itself behaves as expected.
