### ISSUE TITLE
Sharepoint Online - external user

### ISSUE THREAD

**Issue by Kaztel** [SharePoint/sp-dev-docs#7934]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hello, I have some folders shared with users external to my organization. 
The external user cannot delete individual files but when they are 2 or more files.
The error message when trying to delete a file is the following: "Token request previously failed".
any idea of ​​solution
Thank you

![image](https://user-images.githubusercontent.com/104779183/166258132-93cb8eb2-c7ec-4828-a84c-435faf935d7c.png)

### Steps to reproduce

1. Shared folder
2. Delete file

### Expected behavior

Delete files

**Comment by CallumCrowley** [comment]
@Kaztel have you contacted Microsoft support regarding this?

**Comment by AJIXuMuK** [comment]
@Kaztel - that is not a dev issue. Please, reach out to Microsoft support channels.
