### ISSUE TITLE
German Translations not displayed in Microsoft Apps for Generic-List

### ISSUE THREAD

**Issue by Ladislav-Stupak** [SharePoint/sp-dev-docs#7937]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Dear Ladies and Gentlemen,

the SharePoint App Generic-List shall have also German translations for short and log description in App Store.

English Text will be displayed in both German and English selections:

https://appsource.microsoft.com/en-us/product/office/WA200004047
https://appsource.microsoft.com/de-de/product/office/WA200004047

Thank you for correction.

With best regards
Ladislav Stupak
https://www.stupak.ch/

**Comment by VesaJuvonen** [comment]
Translations can be provided as part of the partner center submissions, and they should be properly shown for the different regions in app source. If that's not the case, would see the right contact to repor the issue from the app source site. Our team in this GitHub repository cannot unfortunately fix any issues in app source side.
