### ISSUE TITLE
List Formatting - Replace function just replace first match

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#7938]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

JSON functions from microsoft documentation:
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference

### Describe the bug / error

The following error appear when Power user uses JSON function "replace" to replace repetitive word using format column.
Add following text in "single line of text or multiple line of text" Column:
**"test1 test2 test3 test4 test5"**

When function below is execute, only the **first Match is replaced**:
![image](https://user-images.githubusercontent.com/8522348/166956795-cac81a51-bc6a-440c-8adc-eb30d98c259d.png)

### Steps to reproduce

1. Create column of type "**single line of text or multiple line of text**"
2. Access to format column
3. include following command `"txtContent": "=replace(@currentField,'test','')"`

### Expected behavior

Or "**replace**" function should **replace all match words** or should exist "**replaceAll**" function to **replace all match words**

**Comment by PieterVandendriessche** [comment]
Is there any update on this issue? It's really annoying to have no function to replace all occurrences in the SP formatting.

**Comment by aaclage** [comment]
Hi @PieterVandendriessche 
Try:
```"txtContent": "=replaceAll('H-e-l-l-o W-o-r-l-d', '-', '')"```

**Comment by PieterVandendriessche** [comment]
Hi @aaclage 
Thanks for your answer. The replaceAll indeed works for the txtContent field. In my use case I am trying to get it working on the href attrinbute, see my use case below (with workaround):
`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "txtContent": "@currentField",
  "attributes": {
    "href": "=@currentWeb + '/Lists/MEMBRES/AllItems.aspx?FilterField1=EquipeFR&FilterValue1=' + replace(replace(replace(replace([$Title],'&','%26'),'&','%26'),'&','%26'),'&','%26') + '&FilterType1=Lookup'",
    "target": "_blank"
  }
}`

**Comment by aaclage** [comment]
Tested your code.
Unless did something wrong the replaceAll did the job correctly.

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "a",
  "txtContent": "@currentField",
  "attributes": {
    "href": "=@currentWeb + '/Lists/MEMBRES/AllItems.aspx?FilterField1=EquipeFR&FilterValue1=' + replaceAll([$Title],'&','%26') + '&FilterType1=Lookup'",
    "target": "_blank"
  }
}
```

**Comment by PieterVandendriessche** [comment]
@aaclage Ok thanks for that. Indeed it works for me now as well. Must have mixed up something in the syntax.
