### ISSUE TITLE
Cannot Install Yeoman: TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by amirmsai** [SharePoint/sp-dev-docs#7939]
Hi All, 
when i try to install SPFx (all Versions 1.11 => 1.14) and if i try to install Yeoman i receive this Error, any Idea ??

{ Error: Command failed: yo --version
C:\Users\Msai\AppData\Roaming\npm\node_modules\yo\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (C:\Users\Msai\AppData\Roaming\npm\node_modules\yo\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\fs.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Msai\AppData\Roaming\npm\node_modules\yo\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

    at makeError (C:\Users\Msai\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\Msai\AppData\Roaming\npm\node_modules\yo\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr:
   'C:\\Users\\Msai\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\npm-registry-fetch\\node_modules\\@npmcli\\fs\\lib\\fs.js:6\r\nconst fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>\r\n                      ^\r\n\r\nTypeError: Object.fromEntries is not a function\r\n    at Object.<anonymous> (C:\\Users\\Msai\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\npm-registry-fetch\\node_modules\\@npmcli\\fs\\lib\\fs.js:6:23)\r\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\r\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\r\n    at Module.load (internal/modules/cjs/loader.js:653:32)\r\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\r\n    at Module.require (internal/modules/cjs/loader.js:692:17)\r\n    at require (internal/modules/cjs/helpers.js:25:18)\r\n    at Object.<anonymous> (C:\\Users\\Msai\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\npm-registry-fetch\\node_modules\\@npmcli\\fs\\lib\\index.js:2:6)\r\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\r\n',
  failed: true,
  signal: null,
  cmd: 'yo --version',
  timedOut: false,
  killed: false }
× yo version

**Comment by AJIXuMuK** [comment]
Hi @amirmsai - thank you for reporting this one.
If that's a problem with installing Yeoman itself - please ask a question in appropriate [GitHub repo](https://github.com/yeoman/yo/issues).
If you have have a problem with SPFx generator - please reopen the issue.

**Comment by amirmsai** [comment]
@AJIXuMuK its a problem with SPFx generator.

**Comment by amirmsai** [comment]
reopen

**Comment by hubghs** [comment]
Any update on this issue ?

**Comment by hubghs** [comment]
The project in repo Node version is 10.24.1. npm is v6.14.12. Windows 11 OS

**Comment by AJIXuMuK** [comment]
@hubghs - thank you for the information.
According to [this documentation](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) node.js v10 is not support with the latest versions of SPFx.
Please, update node.js

**Comment by hubghs** [comment]
> 

I cannot install the new version because my team members are using v10

**Comment by AJIXuMuK** [comment]
@hubghs - in that case you should just use the older versions of SPFx.
But node.js v10 was deprecated and I would recommend updating the used version in your org.

**Comment by hubghs** [comment]
> @hubghs - in that case you should just use the older versions of SPFx. But node.js v10 was deprecated and I would recommend updating the used version in your org.

That is going to be a major change.  Node version is 10.24.1. npm is v6.14.12. I get the following error for Yo Installation
![yo-error](https://user-images.githubusercontent.com/81753478/168339988-be5a7f11-f4fe-42d4-8e68-1e189488254b.jpg)

**Comment by AJIXuMuK** [comment]
@hubghs - sorry, but as I [previously mentioned](https://github.com/SharePoint/sp-dev-docs/issues/7939#issuecomment-1119023417) we're not responsible for Yeoman.
