### ISSUE TITLE
Problem loading FabricMDL2Icons in Teams and SharePoint Online

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#7948]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [x] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: chrome v101
- SPFx version: -
- Node.js version: -
- etc

tested: `"@uifabric/icons: "^5.8.0"` and `"@uifabric/icons": "^7.6.3"`

### Describe the bug / error

When using FabricMDL2Icons, the URLs to the `.woff` files get changed in a Teams environment, causing the requests to fail.

In this case we load icons using `initializeIcons()` (no `baseUrl` given). In SharePoint, the URLs to the `.woff` files are correct. In teams, some of the `.woff` files are wrong, see this example:

```
# OK
https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabric-icons-5-f6547654.woff
https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabric-icons-2-b9379dbc.woff

# NOT OK
https://<tenant>.sharepoint.com/sites/<site>/_layouts/15/fabric-icons-9-c6162b42.woff
```

### Steps to reproduce

1. Create a react app/webpart using fluent icons
2. Use any icon specified in `fabric-icons-9.ts`, see https://github.com/microsoft/fluentui/blob/master/packages/font-icons-mdl2/src/fabric-icons-9.ts
3. Add the webpart to a SitePage within a Teamsite
4. Open the site in MS Teams
5. The font (`.woff`) shouldn't load, resulting in a broken icon:
![image](https://user-images.githubusercontent.com/9069888/167620192-b3b39372-8d14-43ba-bf9c-0853686ddb93.png)

### Expected behavior

I tried investigating why the URL isn't correct for particular `.woff` files (I identified neither `icons-9` nor `icons-16` are loaded). As a workaround I was able to add the baseUrl to the `initializeIcons` call. Could this be a breaking change from this commit? https://github.com/microsoft/fluentui/commit/f1ed2ba54d90c2a94df15198097648d130ba7006

**Comment by StfBauer** [comment]
You have to load the font manually on the page. SharePoint only supports the legacy Segoe UI MDL2 but not the latest font.

**Which is Segoe Fluent Icon Font:**
https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font

For now, I would recommend downgrading or making the font available on the page yourself.

**Comment by johannes-z** [comment]
The fonts/icons work fine in SharePoint. It only breaks when I open the page in MS Teams. Even then, it's not the font that's broken/old/legacy, but the URL is pointing to a non-existing file. 

The problem seems to be that the icon never gets registered in MS Teams, which causes the broken URL.

**Comment by StfBauer** [comment]
Thanx got you now. It might be related due to the fact that no web fonts were loaded in SPFx in Teams. It caused some troubles even with the Segoe UI

**Comment by AJIXuMuK** [comment]
@johannes-z - just to confirm: this is happening when you are using the SharePoint page in Teams, not web part as a tab, correct?

**Comment by johannes-z** [comment]
@AJIXuMuK It is an app that is added as teams tab (SPFx webpart), not personal app. So it's not a SharePoint page, it's an app installed in the teams channel.

**Comment by AJIXuMuK** [comment]
@johannes-z - I performed some tests and can't repro this issue.
I'm attaching test solution. Please, take a look.
Let mw know if it's working for you or not.
[fabric-icons.zip](https://github.com/SharePoint/sp-dev-docs/files/8827989/fabric-icons.zip)

**Comment by johannes-z** [comment]
Sorry, busy week. I'll try asap.

**Comment by johannes-z** [comment]
@AJIXuMuK Thanks for the repro. I wasn't able to reproduce the issue with your solution - so it must be an issue with my code.
