### ISSUE TITLE
SPFx web parts not running on IE11

### ISSUE THREAD

**Issue by khaledFares1993** [SharePoint/sp-dev-docs#795]
i got the this error when opening a page that contains SharePoint framework web part on IE browser ,it works fine on other browsers .
----------------------------------------------------------------------------------------------------------------
Sorry, something went wrong 
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details. 
Technical Details 
Error details: ReferenceError: 'console' is undefined 

Troubleshoot issues with Microsoft SharePoint Foundation. 

Correlation ID: 1efe119e-a021-4000-464b-c49bfb1c93c6 

Date and Time: 8/22/2017 11:08:42 PM 

--------------------------------------------------------------------------------

Go back to site  

any help please .
thanxx.

**Comment by bcameron1231** [comment]
Sounds like you are trying to write to the console using console.log or console.table (or similar). In IE, the console object is only instantiated when the developer tools are open (F12) as a means of debugging your application. You can remove the console reference in your webpart?

**Comment by khaledFares1993** [comment]
thanks for your replay ,
but i did not wrote any thing to console in my code,
if i opened developer tools debugger before open the page, the first error disappeared and i got the attached error in console log :


![untitled](https://user-images.githubusercontent.com/31277592/29654805-5cb139c6-88b7-11e7-8918-a8d673314f93.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
