### ISSUE TITLE
Connect-PnPOnline without granting Sites.FullControl.All permission

### ISSUE THREAD

**Issue by ilantom** [SharePoint/sp-dev-docs#7953]
Can I use Connect-PnPOnline without granting Sites.FullControl.All permission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
Yes, you can use the Sites.Selected permission instead and grant the app registration access to the required sites using Grant-PnPAzureADAppSitePermission
