### ISSUE TITLE
Typographical Error #2

### ISSUE THREAD

**Issue by moahnass** [SharePoint/sp-dev-docs#7957]
[Section: Add a project configuration file —> (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts#add-a-project-configuration-file)]

Issue: The word 'the', is typed as 'hte'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b19eb96-192d-2d8b-8d4e-0de787f22093
* Version Independent ID: e2cbd2b2-8bb7-a95f-0768-15f1b045b4c4
* Content: [Use @pnp/sp (PnPJS) library with SharePoint Framework web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts)
* Content Source: [docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Fixed now - thanks for the heads up.
