### ISSUE TITLE
JavaScript heap out of memory (again) in large projects when using Nodejs 14

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7959]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version
1.13.1
1.14.0

- Node.js version
14.19.0

- SO
ubuntu-20.04

### Describe the bug / error

In large projects, I often get this error in the pipeline (ubuntu-20.04):

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

I know this has been reported and fixed before (#3679 ) but it seems the error is happening again

Note that everything works fine with Nodejs 12 (which reached "end of life" in April) and started happening when we upgraded to Nodejs 14. It was happening with SPFx 1.13.1 (maybe related to #7691 ) and still with SPFx 1.14

### Steps to reproduce

Run gulp serve or gulp bundle --ship in a large project

### Expected behavior

The bundle completes without the JavaScript heap out of memory error

**Comment by AJIXuMuK** [comment]
@Rafaelki - that is possible.
We were not changing and build logic. Maybe node 14 works not optimal with older tooling that is still in use for SPFx build routine.
We're working updating that.

But still - could you please check the suggestions from the referenced issue and let us know if that work for you?

Thanks!

**Comment by Rafaelki** [comment]
Yes, adding `--max_old_space_size=8192` is working for us: we have not had any issues in the past few days since we added it.
Thanks @AJIXuMuK
