### ISSUE TITLE
Documentation missing for SPFx v1.14 ListViewAccessorStateChanges

### ISSUE THREAD

**Issue by NewGHUser4321** [SharePoint/sp-dev-docs#7968]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.14

### Issue description

In this [link](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14#list-view-state-changed-event), it says `(see ListViewAccessorStateChanges)`. But, could not find the documentation related to `ListViewAccessorStateChanges` anywhere.

**Comment by AJIXuMuK** [comment]
@NewGHUser4321 - thanks for reporting this one.
It has been fixed: https://docs.microsoft.com/en-us/javascript/api/sp-listview-extensibility/listviewaccessorstatechanges?view=sp-typescript-latest
