### ISSUE TITLE
On view change, eventArgs.stateChanges in the listViewStateChangedEvent event handler gives the value 22 instead of 2

### ISSUE THREAD

**Issue by NewGHUser4321** [SharePoint/sp-dev-docs#7969]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 101.0.4951.54 (Official Build) (64-bit)
- SPFx version: 1.14
- Node.js version: 14.17.0

### Describe the bug / error

When a list view is changed, `eventArgs.stateChanges` in the `listViewStateChangedEvent`'s event handler gives the value `22` instead of `2`

I have the following in my **ListView Command Set Extension**
```
//...
public onInit(): Promise<void> {
    this.context.listView.listViewStateChangedEvent.add(this, this.onListViewUpdatedNew);
    return Promise.resolve();
  }

  private onListViewUpdatedNew(eventArgs: ListViewStateChangedEventArgs) {
    console.log(eventArgs.stateChanges);
  }
//...
```

When I change the list view to something else, `eventArgs.stateChanges` gives me value `22` instead `2`.

In the `@microsoft\sp-listview-extensibility\dist\index-internal.d.ts` file we have the following for ListViewAccessorStateChanges
```
export declare enum ListViewAccessorStateChanges {
    None = 0,
    List = 1,
    View = 2,
    Columns = 4,
    SelectedRows = 8,
    Rows = 16,
    AppliedFilters = 32,
    Sort = 64,
    FolderInfo = 128
}
```
As you can see from the above code, when a view is changed on a list, `eventArgs.stateChanges` whose type is `ListViewAccessorStateChanges` should return value `2` but returning `22` which is not even in the `ListViewAccessorStateChanges ` enum from above.

### Steps to reproduce

1. Create a ListView Command Set Extension.
2. Update the `onInit()` and create a new event handler for `listViewStateChangedEvent` as shown above
3. Save changes and `gulp serve`
4. Change the list view on the list using the view dropdown in the command bar
5. Observe that the value printed in the console will be `22`

### Expected behavior

When a list view is changed, `eventArgs.stateChanges` in the `listViewStateChangedEvent`'s event handler should give the value `2` instead of `22`

**Comment by AJIXuMuK** [comment]
Hi @NewGHUser4321 - thank you for reporting this one.
This behavior is by design.
I assume your 2 views have different set of columns and different rows.
So the final change is `View | Columns | Rows`.
In your login you should check `eventArgs.stateChanges & ListViewAccessorStateChanges.View` to determine if the view has been changed.

**Comment by NewGHUser4321** [comment]
How do I determine if the view has been changed? 
I was trying to do this `if (eventArgs.stateChanges == ListViewAccessorStateChanges.View)` in the event handler before.
But, from your comments above, I can't do this as `eventArgs.stateChanges` value may not be equal to `ListViewAccessorStateChanges.View`.

**Comment by AJIXuMuK** [comment]
@NewGHUser4321 - please see my response above.
It's a bitwise enum. You condition should be `if (eventArgs.stateChanges & ListViewAccessorStateChanges.View)`

**Comment by NewGHUser4321** [comment]
@AJIXuMuK It worked thank you.
