### ISSUE TITLE
MultiValuedProfileProperty Method support for SPOL Standard Release Tenant  

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#797]
#### Category
- [ ] Question

We are trying to use the following method to update our user profile multi-value property using REST API. Could you please confirm if we can use this for Production?

Environment: SPOL Standard Release Tenant  
Endpoint: /_api/SP.UserProfiles.PeopleManager
Method: **SetMultiValuedProfileProperty**

I have confirmed that it is working in production SPOL tenant which is configured with Standard Release option. I just need your confirmation to explain my team.
 
Supporting Links
http://www.vrdmn.com/2016/06/sharepoint-online-write-user-profile.html
https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.userprofiles.peoplemanager_methods.aspx
https://blogs.msdn.microsoft.com/vesku/2014/11/07/sharepoint-user-profile-properties-now-writable-with-csom/ (Vesa Juvonen has a great post about it here)

**Comment by mcmynn83** [comment]
Please ask this question on PNP as this is a forum SPFX issues only.

**Comment by sprider** [comment]
@mcmynn83 

Basically it is not a PnP question. We just wanted to make sure the above said REST method is allowed in SPOL.
