### ISSUE TITLE
SPFX personal app not working in Teams in GCC tenant

### ISSUE THREAD

**Issue by v-saikirang** [SharePoint/sp-dev-docs#7972]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Deployed a SPFx web part to Teams in GCC as a personal app. When I click on the app in teams, the page displays a "_layouts’s server IP address could not be found". Deployed the same SPFx web part to a commercial tenant and works as expected in teams. I used the Teams web client in both cases. The same app works just fine when added to a Teams instead of personal app.

### Steps to reproduce

1) Create a brand new spfx web part project with yeoman. Enable tenant wide deployment and choose react as the framework.
2) Build and Package the web part with --ship flag
3) in a GCC tenant, upload the .sppkg file to the app catalog.
4) Make sure 'Make this solution available to all sites in the organization' is checked when you deploy it.
5) Sync to Teams
6) View App in Teams
7) Should see the error: "_layouts’s server IP address could not be found"                                     

### Expected behavior

Webpart should work when added as a personal app.

**Comment by AJIXuMuK** [comment]
Thank you @v-saikirang for reporting this one!
We were able to repro it and will be working on the fix.

**Comment by v-saikirang** [comment]
Hi @AJIXuMuK,

Thanks for the response. I will test this and let you know.

Thanks.

**Comment by v-saikirang** [comment]
Hi @AJIXuMuK,

I have verified and this seems to work now. Thanks.
