### ISSUE TITLE
SharePoint Web object properties are invalid

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#7973]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Some dev and production tenants.

### Describe the bug / error

Sites in the same hub have the same Web.Id property values. The values are **not** wrong in the Search Index but in the context->site object itself.
I add 2 screenshots from different webs to show WebId:
![image](https://user-images.githubusercontent.com/6162213/169278029-4bb04cee-cc1c-47df-a34a-3a71b9b500cf.png)
![image](https://user-images.githubusercontent.com/6162213/169278127-be3fb1a2-9646-463b-961e-8ad70bf417bf.png)

### Steps to reproduce

1. Add Highlighted News WP to the page
2. Set query to sth like: WebId:{<actual web id>} AND contentclass:STS_Site
3. Multiple results returned

OR 
1. Use SP Editor to check the WebId on sites in the hub and compare those

### Expected behavior

WebIds should be unique among sites in the hub.

**Comment by bcameron1231** [comment]
Web Id's are not actually unique. Try using a combination of the Site Id and the Web Id.

@wictorwilen has a good blog post on this. https://www.wictorwilen.se/blog/when-a-guid-is-not-really-unique-i-m-looking-at-you-sharepoint/

**Comment by siata13** [comment]
Then there is a bug in search that it treats those as duplicates.

**Comment by bcameron1231** [comment]
Very interesting. I unfortunately don't have an answer here in regards to this specific issue, maybe @wobba could provide some insight. In the meantime, turning off duplicates is probably the path forward for this specifically.

**Comment by wobba** [comment]
Trimduplicates should especially not be used for site objects, as you would trim way too many. This is due to how the hash values are generated.

And should not be used for any query in my opinion as I blogged in 2013 https://www.techmikael.com/2013/12/duplicate-trimming-in-sharepoint-2013.html

If you want to trim duplicate sites, you need to decide what the trim logic should be for a duplicate site and rather use a collapse spec.

**Comment by siata13** [comment]
Thanks for the recomendation.

**Comment by AJIXuMuK** [comment]
closing as answered.
