### ISSUE TITLE
Property folderInfo is undefined if folder is loaded directly 

### ISSUE THREAD

**Issue by barisbikmaz** [SharePoint/sp-dev-docs#7974]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.14.0
- Node.js version: 14.17.0

### Describe the bug / error

this.context.listView.folderInfo is undefined when the folder is loaded directly.

### Steps to reproduce

1. Create a List Command Set Extension
2. Deploy 
3. Open a document library folder directly e.g 
https://yourdomain.sharepoint.com/sites/spfx-test/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fspfx-test%2FShared%20Documents%2FSubFolder
5. output this.context.listView.folderInfo.folderPath e.g. onExecute
  ```
public async onExecute(event: IListViewCommandSetExecuteEventParameters) {
     console.log(this.context.listView.folderInfo)
     ....
  }
```
6. Observe that it is undefined.

Note: When you navigate to the subfolder within the document library the folderInfo property is not undefined and contains the folderPath property. 

### Expected behavior

this.context.listView.folderInfo should contain the folderPath property even when you load the folder directly in the browser.

This is important e.g. in Teams when you use the files tab and click on "Open in SharePoint". 
It will directly open a subfolder which contains the files of the current channel. In this case folderInfo is set to undefined and cannot be used.

**Comment by AJIXuMuK** [comment]
@barisbikmaz  - thank you for reporting this issue.
The fix has been done and will be rolled out in the next couple of weeks.

**Comment by AJIXuMuK** [comment]
this should be rolled out WW by now
