### ISSUE TITLE
SPFX webpart pointing to older versions files

### ISSUE THREAD

**Issue by JayHB1** [SharePoint/sp-dev-docs#7976]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

browser version
Google Chrome - Version 101.0.4951.67 (Official Build) (64-bit)
Microsoft Edge - Version 101.0.1210.47 (Official build) (64-bit)

SPFx version
1.12.1
Node.js version
14.15.1

### Issue description

SPFX web part is serving older version of files while doing normal refresh. It works fine when doing a hard reload. This problem appears again if another standard refresh is done.

**Comment by AJIXuMuK** [comment]
Hi @JayHB1 - thank you for reporting this one.
Are you using CDN to host the files (either Office 365 CDN or custom CDN)?
If you add `?sw=bypass` - will the error go away?

@demyren - fyi

**Comment by JayHB1** [comment]
I am using app catalog sites to render files.

**Comment by AJIXuMuK** [comment]
@JayHB1 - can you check if `?sw=bypass` removes the error?

Can you also check the Network in both situations (when correct and incorrect versions are loaded) and provide what files and from what location are loaded.
