### ISSUE TITLE
No longer able to load extensions in developer tenancy 

### ISSUE THREAD

**Issue by al-rosenthal** [SharePoint/sp-dev-docs#798]
#### Category
- [x] Bug

This will be a bit long winded but I've tried a few different things in an attempt to get this to work. 

A few days ago I started working on creating a spfx app by following the guides provided [here](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension) and was successful in creating the basic app, skipping the packaging steps for testing purposes. Recently though when going to test the app with the query string nothing happened. 

At first I assumed it was something I had done that caused problems that gulp didn't pick up as an error but as I scanned through my project I found no such problem. I tried undoing the latest changes I made thinking maybe I was trying to do something that just wasn't supported yet, but still nothing worked. 

After a few attempts at getting the project to work I thought maybe I should package my app together and doing so will actually load my project. After following the steps in the guide I was met with the same output, the app didn't load. So I then attempted to remove the app from the site collection to no avail, causing a lot of red in the console output.
![packaged deleted app](https://user-images.githubusercontent.com/12612801/29628051-1f504b90-87e9-11e7-8c44-a5e8a4467621.png)
![query string app](https://user-images.githubusercontent.com/12612801/29628053-209c45ee-87e9-11e7-982e-fa249cb596e9.png)

So my next thought was maybe my project was borked, so I created a new app following those same guides online and started testing on a new site collection to a similar result, the app doesn't load. The console output is below.
![fresh app console](https://user-images.githubusercontent.com/12612801/29627033-8f9a94fe-87e5-11e7-94ac-4b68b0eb89cb.png)

Elements.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">

    <CustomAction 
        Title="SPFxApplicationCustomizer"
        Location="ClientSideExtension.ApplicationCustomizer"
        ClientSideComponentId="383fdbe6-3ddb-496e-98f2-07a12d65874f"
        ClientSideComponentProperties="{&quot;Header&quot;:&quot;Header area of the page&quot;,&quot;Footer&quot;:&quot;Footer area in the page&quot;}">

    </CustomAction>

</Elements>
```

Guides that I followed 
[Build your first SharePoint Framework Extension (Hello World part 1)](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension)

I am not sure what to take as a next approach for getting past this, from the other issues tracked and looking through stackoverflow with the [spfx] tag no one else seems to be having this issue.

**Comment by bcameron1231** [comment]
When you deploy the application to the app catalog, do you see any error messages in the "App Package Error Message" Column?

**Comment by al-rosenthal** [comment]
Nope there was no error in the app catalog.

**Comment by bcameron1231** [comment]
Which guides have you been following? The Microsoft Dev Docs for creating your first extension? I've seen this error come up when there are issues with the elements.xml file.

**Comment by al-rosenthal** [comment]
Yup those are the guides I was following. I linked them, but I'll add them at the bottom of the page just in case. 

I'm not sure what kind of errors I could be getting from the elements.xml file, I'll add the contents of it, but I basically just copied what they had and replaced component id with the id in my manifest.json file.

**Comment by pdemro** [comment]
From what I can tell, OnRender is not being called as of yesterday for SpFx extensions.  This is on a Development tenant I just created, with generator-sharepoint v1.1.3

**Comment by thechriskent** [comment]
I'm seeing the `Invalid Location: Invalid location: ClientSideExtension.ApplicationCustomizer` when testing an Application Customizer on modern list view pages but not on regular modern pages.

**Comment by bcameron1231** [comment]
@al-rosenthal. Per this ticket #805 by @thechriskent. @VesaJuvonen let us know the placeholder names have changed in prep to get ready for RC. Yeoman Template is not updated yet.

**Comment by al-rosenthal** [comment]
Thanks for the responses guys! 

Seems like a hurry up and wait situation so I'll close this thread.
