### ISSUE TITLE
Taxonomy modern picker - add new terms to open term set

### ISSUE THREAD

**Issue by RubenHerrera86** [SharePoint/sp-dev-docs#7985]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.13
- Node.js version 12
- etc

### Issue description

Hello there,

I'm wondering if there is any functionality to add new terms to open term set in taxonomy modern picker, somehow simulating the enterprise keyword functionality. The enterprise keyword add a new term if does match with any at the moment the user press enter or tab key.

Kindly let us know.

**Comment by patrikhellgren** [comment]
@RubenHerrera86 This feature is at the moment not available out of the box but can be accomplished using the advanced example available [here](https://pnp.github.io/sp-dev-fx-controls-react/controls/ModernTaxonomyPicker/#advanced-example). You will not get exactly the same functionality with the inline input box but you could use your own input method like a dialog or a panel.

**Comment by AJIXuMuK** [comment]
This issue doesn't seem to be related to this repo as it either a UI request, or references PnP React Controls component.
