### ISSUE TITLE
App Source package validation throws error due to incorrect child element 'ShortDescription'

### ISSUE THREAD

**Issue by RafalUrbanski** [SharePoint/sp-dev-docs#7987]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.14
- Node.js version: 14.19.1

### Describe the bug / error

While updating spfx package in the App Source, I received following error:
`Package acceptance validation error: XML Schema Validation Error Error found during XML Schema validation. Error code: The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has invalid child element 'ShortDescription' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. List of possible elements expected: 'SupportedLocales, SupportPage, SupportedLanguages, UninstallingEventEndpoint, StartPage, InstalledEventEndpoint, UpgradedEventEndpoint, SettingsPage, WebTemplate' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'. Line: 1 Column: 634`
I have recently updated spfx toolchain from 1.11 to 1.14 and according to the migration guide, I added metadata section to the package-solution.json file. Metadata contains shortDescription and longDescription property. Due to that my AppManifest.xml contains such a properties as well, but it seems that validation process do not accept those properties. Am I doing something wrong?
To check if my package-solution.json files is correct, I generated brand new project using yeoman and metadata section containing shortDescription and longDescription property was there. Same properties appeared in AppManifest.xml file as well.

### Steps to reproduce

1. Package new version of the app
2. Upload file via Microsoft Partner Center
3. Wait for the error during the 'Analysing' step

### Expected behavior

App package is uploaded properly

**Comment by AJIXuMuK** [comment]
@RafalUrbanski  - could you please share the `package-solution.json`?

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - thank you for sharing.
The structure looks correct.
And I just checked a newly created project - it behaves correctly.

Could you please check if new simple solution works on the same tenant?
And also if your solution is working on other tenants?

**Comment by RafalUrbanski** [comment]
@AJIXuMuK I installed the newly created project on my tenant and it works just fine - I can add related webpart to the page.
Regarding my solution - before I uploaded it to the App Source, I installed my package on three existing tenants and one brand new tenant (it was a part of my testing process) and it works as expected on all of them.
May this be somehow caused by the fact that first version of the app that we published to the App Source, used older spfx version (1.11, while now we have 1.14)? Or may this be related to the fact that our solution is an app page?

**Comment by RafalUrbanski** [comment]
@AJIXuMuK FYI: First error that I received yesterday while updating package in the App Source was regarding AppIconPath child element (same kind of error that I reported, but different child element). I was able to solve this one by removing iconPath property from package-solution.json, but then I received the error regarding ShortDescription child element

**Comment by RafalUrbanski** [comment]
Hi, any updates on the matter? If it is not something that you could help us with, could you please tell me where should I raise a ticket?

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - we will be looking into it for sure.

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - sorry for the delay.
Just to clarify - when you're saying App Source, you mean upload to the Partner Center? Or App Catalog?
If App Catalog - are you using tenant app catalog or site collection app catalog?

**Comment by RafalUrbanski** [comment]
@AJIXuMuK I mean Partner Center

**Comment by AJIXuMuK** [comment]
@RafalUrbanski  -  this should be fixed and rolled out.
