### ISSUE TITLE
@microsoft/sp-image-helper has no exported member 'ImageHelper'

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#7991]
In SPFx 1.14, @microsoft/sp-image-helper has no exported member 'ImageHelper', in fact it is commented out:

`/* Excluded from this release type: ImageHelper */`

so probably this article needs to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7410a11-f0a4-f2c3-fed2-d9217b489f30
* Version Independent ID: f7410a11-f0a4-f2c3-fed2-d9217b489f30
* Content: [Image Helper API](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/image-helper-api)
* Content Source: [docs/spfx/image-helper-api.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/image-helper-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@Rafaelki - that is beta API. Beta API is not included in the main version release.
Article states that this is in beta, so no changes needed.

**Comment by Rafaelki** [comment]
Really sorry about that, I probably have missed the beta warning
