### ISSUE TITLE
Using SPFx, can we change default .zip file name when user downloads from SPO Documents Library?

### ISSUE THREAD

**Issue by NewGHUser4321** [SharePoint/sp-dev-docs#7994]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: SharePoint Online

### Issue description

When a user downloads multiple files from SPO Documents Library, the default file name for the zip file is `OneDrive_XXXXX`. Is there a option or a workaround in SPFx to change this default zip file name to custom one? 

Of course we can change browser settings in windows to ask where to save each file before downloading and then change the name of the zip file in the file explorer dialog. Looking for solution beyond this.

**Comment by AJIXuMuK** [comment]
@NewGHUser4321 - are you trying to customize out of the box behavior? or do you have a custom command set to implement download?

**Comment by AJIXuMuK** [comment]
@NewGHUser4321 - unfortunately, in that case there is nothing available.
You still could create a custom command set command and implement download logic by yourself.

**Comment by NewGHUser4321** [comment]
@AJIXuMuK - Thanks for confirming.
