### ISSUE TITLE
Please help with possible compatibility issue. 

### ISSUE THREAD

**Issue by roxyninja** [SharePoint/sp-dev-docs#7997]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Chrome 101.0.4951.67 Firefox 100.0.2
- SPFx version 1.14
- Node.js version originally 14.19.3 then uninstalled and installed 14.19.2 to see if that helped
- Python 3.10.4
- Gulp Cli 2.3.0
- npm 6.14.17
- yo 4.3.0
- generator-sharepoint 1.14.0
- git version 2.36.1.windows.1

- MS Visual Code 1.67.2, (VS Code says Node.js is 16.13.0 but when I use the command prompt 'npm node.js -v it reads 6.14.17 so I'm confused by that).
- Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

### Issue description

I am new at using samples for my work intranet I'm creating with SPO. I have followed many tutorials that Microsoft and Github provide and really appreciate all of the hand holding. I have been successful at deploying a few samples. With many of the webpart or extensions samples I sometimes get an error about Python2. Other webparts I get an error that "primordials is not defined". Obviously I'm doing something wrong.

I have a few questions:

1. Can anyone help with these errors? What do I need to do to fix them. Thank you in advance!

2. I have followed instructions developing my SPFx environment for v1.14. I'm not sure if the samples have to state they are compatible with v1.14. There are limited webparts and 1 extension available if searching by SPFx version. Can a sample or extention for SPFx 1.10 work with SPFx 1.14?

3. Can I use all Frameworks for my SPFx environment or do I need to do anything else to utilize specific ones?

4. I follow the instructions for each webpart or extension. The processes differ slightly and they are as followed, though I don't quite understand the differences:

A. (Deploy client-side web part Hello World Part 3 video) npm install, gulp serve, gulp bundle, gulp package-solution

B. (Instruction video to get started using samples by David Warner) npm install, gulp serve, gulp clean, gulp bundle --ship, gulp package --ship, gulp package-solution --ship

C. (Instructions from a sample) npm install, gulp build --ship, gulp bundle --ship

![react-application-breadcrumb1](https://user-images.githubusercontent.com/105945391/170789367-3e77443c-0264-47ee-9057-d522f5cdadf8.PNG)
![react-application-breadcrumb2](https://user-images.githubusercontent.com/105945391/170789368-c4e7a740-38b2-47e0-a0d2-c53a6919426f.PNG)
![react-application-breadcrumb3](https://user-images.githubusercontent.com/105945391/170789370-f5be6fab-5989-4777-9f33-72bbedc35c17.PNG)
![VS Code Capture](https://user-images.githubusercontent.com/105945391/170789371-ca6b789e-1aa1-49ea-b26b-bd64691856ae.PNG)
![react-tour-pnpjs1](https://user-images.githubusercontent.com/105945391/170789855-8d741f81-2e81-4f53-80fc-991f3c881313.PNG)
![react-tour-pnpjs2](https://user-images.githubusercontent.com/105945391/170789997-99991990-dc8c-4177-a1be-9a6df51feaa6.PNG)

**Comment by AJIXuMuK** [comment]
@roxyninja - you need Python v2 installed.
Usually for Windows machine it is done by installing `windows-build-tools` like `npm i -g windows-build-tools`.
You will need admin account for that.
Then probably, you will need to correctly change environment variables.

For the difference between `gulp bundle` and `gulp bundle --ship` (same for `gulp package-solution`) - the first one allows you to create a "debug" package that can be loaded to SharePoint. It means you will be able to run `gulp serve` and debug your solutions locally.
The latter (with `--serve` parameter) commands produce production-ready package.

Please, let me know if you still have any issues.
