### ISSUE TITLE
Vulnerability alerts introduced by node-fetch package

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [SharePoint/sp-dev-docs#7999]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version  v1.14.0
- Node.js version v12
- etc

### Describe the bug / error

The two packages(@microsoft/sp-property-pane@1.14.0 and @mcirosoft/sp-webpart-base@1.14.0) requires node-fetch@^1.0.1 via a transitive dependecy on isomorphic-fetch@2.2.1. So the latest possible version that can be installed is 1.7.3.

But there's vulnerability issue for package node-fetch with version <2.6.1 and the earliest fixed version is 2.6.7.

### Steps to reproduce

1. Scaffold SPFx project and have @microsoft/sp-property-pane@1.14.0 and @mcirosoft/sp-webpart-base@1.14.0 as dependency
2. the introduced version for node-fetch in package-lock.json is 1.7.3 which has vulnerability issue.
3.

### Expected behavior

Upgrade related dependency to newer version so we can have node-fetch package with >=2.6.1 version.

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
