### ISSUE TITLE
Logging API documentation needs to be updated to reference correct library

### ISSUE THREAD

**Issue by nissan** [SharePoint/sp-dev-docs#800]
#### Category
- [ x] Typo

For the [Logger API documentation page](https://github.com/SharePoint/sp-dev-docs/wiki/Working-with-the-Logging-API)

```
import{ Log } from '@microsoft/sp-client-base';
```

should be updated to be
```
import{ Log } from '@microsoft/sp-core-library';
```

**Comment by mcmynn83** [comment]
Thanks for pointing out the issue we have now fixed the documentation.
