### ISSUE TITLE
API Requests from SPFX Solution are missing from API permissions list in sharepoint admin after deploying it 

### ISSUE THREAD

**Issue by patrickblanc** [SharePoint/sp-dev-docs#8003]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Everything is written in the title. 

If I remove permissions on Azure AD for the "SharePoint Online Client Extensibility Web Application Principal" app registration , then remove my SharePoint application from tenant addin catalogs and install it again the permissions does not appear again the the list listing the pending permissions in the SharePoint administration center under advances -> Access to APIs.

![image](https://user-images.githubusercontent.com/70770642/171172192-33a78b90-f07b-4e98-a5c0-15e1022e6fc5.png)

We have noticed in the past that each time you install an app, then a new pending request appears in this Access to APIs page in the admininistration center of SharePoint... then all duplicates entries was gone, so I guess Microsoft did something to clean the list... but now if permissions have been remove in Azure AD directly, when reinstalling the package, the request to add again the permissions never appear in the list. This is a MAJOR problem, even if we can solve it manually by adding permissions in Azure AD. 

**I think the fix done by MS to remove duplicates entries in this list added a regression bug.** 

### Steps to reproduce

1. Remove permission in Azure AD for the SharePoint Online Client Extensibility Web Application Principal app registration
2. Remove application from tenant addin catalog
3. Add your SPFx application again
4. Go to SP admin center -> Advances -> Access to APIs
5. The pending permissions does not appear

### Expected behavior

The permissions list in SP admin center -> Advances -> Access to APIs should list the pending permissions if the permissions is not found in the azure app registration in Azure AD

**Comment by lucabandMSFT** [comment]
@patrickblanc, thanks. Can you please check in AAD if you removed the permissions on both the service and the application principal for the "SharePoint Online Client Extensibility Web Application Principal" object?

**Comment by lucabandMSFT** [comment]
@patrickblanc , sorry for my delay in responding. Two questions
* would be possible to have access to the tenant or is that a production tenant?
* if we cannot get access to the tenant, could you please navigate to the API Access page (I assume your account has access to the app catalog and it is also an AAD Global Admin), go in the browser dev tools and generate + send us the HAR file for the API Access page load?

Thanks!
