### ISSUE TITLE
Errors using MS Graph tutorial

### ISSUE THREAD

**Issue by BeamSlide** [SharePoint/sp-dev-docs#8011]
I have started learning the SharePoint Framework and followed all the _Getting started_ topics. 
Now I am on the _Use Microsoft Graph in your solution_ tutorial.

I am getting errors when executing `gulp bundle --ship`.

![image](https://user-images.githubusercontent.com/97518049/171821513-a413efc8-001f-4a9d-8d8d-cabd7cba413f.png)

I am also getting squiggly lines in VS Code for these properties.

![image](https://user-images.githubusercontent.com/97518049/171821815-62f4496e-41f5-4240-b320-85859ff557ac.png)

I am using Node v14.19.2 and NPM 6.14.17.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 642064a1-1971-d88b-6eeb-3bcde4333383
* Version Independent ID: 11fbb2ac-f682-e963-a07a-a28c9cb3d9d8
* Content: [Building SharePoint Framework solutions, which use Microsoft Graph](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-microsoft-graph-apis)
* Content Source: [docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@BeamSlide - check your `module.scss` file and what CSS classes you have in there.
`styles` object contains properties generated based on these classes.

**Comment by BeamSlide** [comment]
Thanks @AJIXuMuK. 

Seems like I am missing .container, .row, .column, .title, .subtitle and .description classes.

Do you know where I can get the definitions to these classes so I could manually add those? I thought the classes would be auto-generated just like the ones from the previous tutorials.

**Comment by AJIXuMuK** [comment]
@BeamSlide this tutorial is using old version of web part markup.
You don't need to copy the `domElement` from the signature and can just use the one that was scaffolded by the generator.

**Comment by BeamSlide** [comment]
I see. Understood.
Thanks again @AJIXuMuK.
