### ISSUE TITLE
Link invalid

### ISSUE THREAD

**Issue by LennartaeHoefer** [SharePoint/sp-dev-docs#8016]
https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-send-sp-http-request#use-json-light
The link in this chapter is invalid
https://www.microsoft.com/microsoft-365/blog/2014/08/13/json-light-support-rest-sharepoint-api-released/

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4415fd40-67a0-eb8a-fd6d-5f645eba87d9
* Version Independent ID: 798e816e-07a7-92dc-8fb3-9bf5b9d49105
* Content: [Working with the SharePoint Send HTTP Request flow action in Power Automate](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-send-sp-http-request)
* Content Source: [docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md)
* Service: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Confirmed current link works.

**Comment by andrewconnell** [comment]
Looks like it's an issue with the automatic locale resolution. MSFT docs aren't supposed to have locales in the URL, but apparently this page doesn't map to a German translation ("de-de"). I'll hardcode this to use EN-US... for now you can access it here: https://www.microsoft.com/en-us/microsoft-365/blog/2014/08/13/json-light-support-rest-sharepoint-api-released/
