### ISSUE TITLE
Failed on creating SharePointFx webpart on fetch data

### ISSUE THREAD

**Issue by ChrisGaoYang** [SharePoint/sp-dev-docs#802]
Detailed msg as below when I create Fx webpart with command "yo @microsoft/sharepoint", on the step of "fetch metadata from.........", is there anyway can fetch those metadata offline?

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--cache-min" "86400"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\chris.gao\AppData\Local\Temp\npm-49564-86968284\registry.npmjs.org\_40microsoft\sp-core-library\-\sp-core-library-1.1.0.tgz
npm ERR! Expected: 9197a8dc8d2c502fd087cc7e70e1540a723e8cfe
npm ERR! Actual:   c7c0cc06aa5d7ca7f9a48d66fa4b38304eaa92cc
npm ERR! From:     https://registry.npmjs.org/@microsoft/sp-core-library/-/sp-core-library-1.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by mcmynn83** [comment]
Can you try doing NPM install again.  You cannot do that offline because you need to download the packages.

**Comment by mcmynn83** [comment]
If you are still having this problem please open a new thread.

**Comment by ChrisGaoYang** [comment]
Still has error but create project successfully when I switch to Node.js 8.4.0
----
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\DotNet\\SPXWebPart01
\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext
=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\DotNet\SPXWebPart01\node_modules\node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'C:\DotNet\SPXWebPart01\
node_modules\sass-graph\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\DotNet\SPXWebPart
01\node_modules\sass-graph\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\DotNet\\
SPXWebPart01\\node_modules\\sass-graph\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\DotNet\\SPXWebPart01\\node_modules\\sass-graph\\node_modul
es' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris.gao\AppData\Roaming\npm-cache\_logs\2017-09-07T09_05
_48_579Z-debug.log

      _=+#####!
   ###########|       .----------------------------------------.
   ###/    (##|(@)    |            Congratulations!            |
   ###  ######|   \   |  Solution spx-web-part-01 is created.  |
   ###/   /###|   (@) |     Run gulp serve to play with it!    |
   #######  ##|   /   '----------------------------------------'
   ###     /##|(@)
   ###########|
      **=+####!

**Comment by waldekmastykarz** [comment]
Is there any specific reason you want to use Node.js v8? SharePoint Framework officially supports the LTS version which currently is v6.
