### ISSUE TITLE
App Catalog with modern UI doesn't ask for trust -> Updates don't work

### ISSUE THREAD

**Issue by BigEaseGueldi** [SharePoint/sp-dev-docs#806]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Once you upload a sppkg file to the app catalog, you should always be asked for the trust.

#### Observed Behavior
Works like it has always done with app catalog (more specific: "Apps for SharePoint" library) in classic design mode. But if you click on a "switch to modern" link, the generated cookie might lead to an app catalog in modern UI. There, you can still upload your sppkg file, but you will not be asked regarding your trust to full trust client side code.

You can then update the Web Part on your page, but the new version of the trusted code will not be pulled.

#### Steps to Reproduce
Find a "switch to modern" link, click on it, go to the app catalog, upload your solution.

**Comment by mcmynn83** [comment]
Thank you for pointing this out. The issue is understood and we are making a fix.  In the meantime if you clear your cookies and switch back to classic the issue will not repro.
