### ISSUE TITLE
SpFx List View Command Set commands get duplicated with Document Library Webpart

### ISSUE THREAD

**Issue by SPElantis** [SharePoint/sp-dev-docs#8068]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Gulp 4.0.2
Node 14.18.1
SpFx 1.14.0

### Describe the bug / error

When displaying a library using the Library Web Part the entries are duplicated (x2 in context menu, x3 in command bar).  This does not occur when directly in the library.
![image](https://user-images.githubusercontent.com/94828524/172684325-64431904-7fb4-4af7-8d13-0bd6983ca19c.png)
![image](https://user-images.githubusercontent.com/94828524/172684414-837c6b64-5b4f-42bf-81e9-fb324fee5911.png)

### Steps to reproduce

1. Create a extension with location="ClientSideExtension.ListViewCommandSet"
2. Make the command(s) visible when one item is selected
3. Deploy
4. Create a page with a Library Web part
5. Select an item to see the multiple entries

### Expected behavior

Multiple entries of the command will be shown as per the provided screenshots.

**Comment by SPElantis** [comment]
Hi Alex,

There are only 4 Apps deployed to this farm.  I have confirmed it is this single App by changing the labels on the actions and redeploying (all the instances changed to match).

ClientSideInstance.xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <ClientSideComponentInstance
        Title="NccToolbarConnector"
        Location="ClientSideExtension.ListViewCommandSet"
        ListTemplateId="101"
        Properties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}"
        ComponentId="8c265eb7-4d1a-43f0-b2e0-6d6a7fa9f56a" />
</Elements>

elements.xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
    <CustomAction
        Title="NccToolbarConnector"
        RegistrationId="101"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet"
        ClientSideComponentId="8c265eb7-4d1a-43f0-b2e0-6d6a7fa9f56a"
        ClientSideComponentProperties="{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;, &quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}">
    </CustomAction>
</Elements>

Thanks


Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by AJIXuMuK** [comment]
@SPElantis - is the solution deployed tenant wide or no?
Also, have you tried on another site collection? Does it behave the same way?

**Comment by SPElantis** [comment]
This solution is deployed tenant wide and acts the same across multiple site collections.

We also attempted to only deploy it specific sites (retracting it first) and found the same issue.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by SPElantis** [comment]
Hi Alex,

I just noticed something that may help diagnose this issue.

When first opening the library web-part (no documents selected) the actions don’t appear in the toolbar (as expected):
***@***.***

When selecting a document the actions appear, but duplicated:
***@***.***
Then when unselecting the document one of the set of actions disappears but one remains:
***@***.***

Clicking on the actions does not do anything but this is probably because of an additional check in the code to ensure something is selected.


When testing directly against the library (no web-part) the actions only appear once and are removed when unselecting the document as expected.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

From: Shaunce Presetsky
Sent: Monday, July 11, 2022 1:48 PM
To: SharePoint/sp-dev-docs ***@***.***>; SharePoint/sp-dev-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [SharePoint/sp-dev-docs] SpFx List View Command Set commands get duplicated with Document Library Webpart (Issue #8068)

This solution is deployed tenant wide and acts the same across multiple site collections.

We also attempted to only deploy it specific sites (retracting it first) and found the same issue.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by SPElantis** [comment]
Hi Alex,

I sent the sppkg file to the email listed below.  Please let me know if you don’t receive it.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by SPElantis** [comment]
Hi Alex,

I am attaching directly to this email and have also resent to ***@***.******@***.***>.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by SPElantis** [comment]
Hi Alex,

I resent to ***@***.******@***.***> and also replied and attached directly to the chain.  Hopefully you get one of these emails.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by AJIXuMuK** [comment]
@SPElantis - still nothing...

Just to confirm, the email is aterentiev at microsoft.com

**Comment by AJIXuMuK** [comment]
@SPElantis - I've created a private GH repo and added you as a collaborator in there.

**Comment by SPElantis** [comment]
Hi Alex,

I have uploaded the file to the git repository.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by AJIXuMuK** [comment]
Thanks @SPElantis!
Tested with your solution but still can't repro... :(
Let's try to figure out what's happening.
First of all, I want to double confirm you are using SharePoint Online and not on-prem/subscription edition, correct?

Second, when reloading the page, you should see these requests in the Network tab: `RenderListDataAsStream` and `CustomActionElements`.
Could you please check the responses for both requests and see if your solution is duplicated there? Maybe it has different id but the same set of buttons or something?

**Comment by SPElantis** [comment]
Hi Alex,

Yes, this is a SharePoint Online tenant (nccuat.sharepoint.com).

I only see one entry for “Run Report” and “Run Workflow” in the RenderListDataAsStream response.  I don’t see these at all in the CustomActionElements response but I do see two entries for NccToolbarConnector, I am assuming one for each entry.

Note: This only affect the Library Webpart.  The normal library display/view does not have this problem.

I uploaded the response information for the two requests as well as some supporting screenshots to the code sharing git you setup earlier.

Thanks

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by AJIXuMuK** [comment]
@SPElantis - from the response it is clear you have the customizer registered multiple times, even with different `Location` value.
Seems like on a doc library page we're doing a better job of filtering out the same registrations.
But the initial problem is still multiple registrations.
I'd check what you have in Tenant Wide Extensions list in you App Catalog site collection (`/sites/your-app-cat/Lists/TenantWideExtensions/AllItems.aspx`) and also if you have direct registration of the list command set in `CustomActions` of the list (`UserCustomActions` property).

**Comment by SPElantis** [comment]
Hi Alex,

I cleared out the duplicate entries in the TenantWideExtensions list and everything is good now.  Why is there no view/link to this list under the App management area, it would be very useful.  The duplicate entries from last year before I was a member of the project.

Thanks for your help.

Shaunce Presetsky
Elantis Solutions Inc.

Mobile: 780.903.8041 | Email: ***@***.******@***.***>

**Comment by AJIXuMuK** [comment]
@SPElantis 

> Why is there no view/link to this list under the App management area, it would be very useful

To not confuse admins with the details as in most cases this additional knowledge is not needed for them :)

Happy to hear the issue is resolved.
