### ISSUE TITLE
How to obtain Bearer access token in code?

### ISSUE THREAD

**Issue by MarioZagreb** [SharePoint/sp-dev-docs#8071]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have build a List View Command Set (command in a SP app bar of a particular SP doc lib) which reads selected file data and sends that file to a another system. That system does what it needs to do with the file and returns a NEW file back to my SP doc lib.

It does so with this URL:
/_api/web/lists/getbytitle('My List Name')/rootfolder/files/add(url='test.pdf',overwrite=true)?access_token=Bearer + userToken;

And here we have a problem with the token. How do I obtain that token so that third party software can upload that file to my SP?

I have used Postman to get the token from:
https://accounts.accesscontrol.windows.net/b732a64c-9b68-4fdb-8942-583fbbc6496c/tokens/OAuth/2

![image](https://user-images.githubusercontent.com/105245128/172698971-50e781ef-93f1-4988-9dec-756434878354.png)

And that works great!!

And this is the javascript code which I was planning to use:

$.ajax({
      type: 'POST',
      crossDomain: true,
      async: false,
      url: 'https://accounts.accesscontrol.windows.net/{tenant}/tokens/OAuth/2/',
      headers: {
          "content-type": "application/x-www-form-urlencoded"
      },
      data: {
          "grant_type": "client_credentials",
          "client_id": "aaaa",
          "client_secret": "aaaaa",
          "resource": "aaaa"
      },
      success: function(data) {
          
      },
      error: function(data, errorThrown, status) {
  
      }

But, of course, that does not work in my extension code, I get error "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.microsoftonline.com/..."
I am aware of that, I know that this cannot work.

Then, I tried to go with this:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow

but I get the same error with https://login.microsoftonline.com
I have tried to register the app with AAD, but I don't know which permisson I actually need or how to set that up.

How can I get access token (in my javascript code) so the third party can upload files to my doc lib?
Can it be done with pnp js somehow? 
Actually, what kind of token do I need?
Yes, many confusing questions, I appreciate any help :)

**Comment by AJIXuMuK** [comment]
@MarioZagreb - just to understand the scenario completely.
You have a command set and some back end app - is that correct?
Then, you want to acquire access token on SPFx and send it to your back end to do some operations?

**Comment by MarioZagreb** [comment]
Yes, that is correct

**Comment by AJIXuMuK** [comment]
@MarioZagreb - I think you may pass id token.
But you will need to register a separate AAD app for your back end and implement logic of exchanging id token to access token there.
Sending access token from SPFx _may_ work but it is incorrect and unsecure.

**Comment by MarioZagreb** [comment]
Yes, I thought you are going to say that :)

"May pass token" is good enough for me, but the problem for me is how do I get token in SPFx?

There are no useful instructions on how to do that. I did register a separated AAD app.
I tried following instructions from this page:
https://dzone.com/articles/getting-access-token-for-microsoft-graph-using-oau

but trying to get the token with
https://login.microsoftonline.com/<AAD_name>/oauth2/token
in SPFx doesn't work - I get same CORS error.

Can you recommend where can I read more on how to get token in SPFx?

**Comment by AJIXuMuK** [comment]
[This](https://ramin.expert/?p=373) seems like a good example of what you need.

**Comment by MarioZagreb** [comment]
@AJIXuMuK thanks, this is extremely helpful, but I am still missing some parts...

I can get MS Graph token with this code:
this.context.aadTokenProviderFactory.getTokenProvider()
    .then((provider) => { 
      console.log("GRAPH");
        return provider.getToken('https://graph.microsoft.com', false)
            .then((token) => {
                                 console.log(token);   
            }, (rejection) => {
                console.log(rejection);
            });
    })
    .catch((err) => {
        console.log("Failed to get token provider.");
    });
 
How do I exchange that token for a SP token?

**Comment by MarioZagreb** [comment]
Also, I tried to create AAD app and added following permissions to it:
![image](https://user-images.githubusercontent.com/105245128/173033671-92d57bd5-adf8-497f-b648-7b0bd3b1c0bc.png)

(almost all of them because I don't know which I actually need.

But, when I try to get the token for that from code I get following error:
The user or administrator has not consented to use the application with ID '<guid>' named 'SharePoint Online Client Extensibility Web Application Principal'

Code:
this.context.aadTokenProviderFactory.getTokenProvider()
    .then((provider) => {       
        return provider.getToken('<my app client id>', false)
            .then((token) => {
                console.log(token);
                    
            }, (rejection) => {
                console.log(rejection);
            });
    })
    .catch((err) => {
        console.log("Failed to get token provider.");
    });

**Comment by MarioZagreb** [comment]
@bcameron1231 thanks for the answer, but that isn't acceptale solution (since I am using third party software for uploading file back to SP).

I would like to use this URL 
/_api/web/lists/getbytitle('My List Name')/rootfolder/files/add(url='test.pdf',overwrite=true)?access_token=Bearer + userToken;

Is there a simple way to exchange graph token for SP token so We can work with SP API?

**Comment by AJIXuMuK** [comment]
@MarioZagreb - first of all, I would not send graph access token from SPFx to you back end app.
If someone intercepts such a message he will have to many permissions.

I'd do something like that:
1. "Expose API" from your AAD app. And use standard scopes like "user_impersonation" and "offline_access".
2. Get token for these scopes in your SPFx solution. You will need to include them in web api permissions request
3. send this token to your backend
4. Use this access token to exchange for SP access token (you AAD app should be consented for SharePoint permissions).
The code for #4 will look something like that:
```csharp
var client = ConfidentialClientApplicationBuilder.Create(AADAppId)
  .WithAuthority($"https://login.microsoftonline.com/{onmicrosoftTenantUrl}")
  .WithRedirectUri("https://some-redirect-uri")
  .WithClientSecret(AADAppSecret).Build();

var newTokens = await client.AcquireTokenOnBehalfOf(
  new string[] { $"https://{tenantUrl}/AllSites.Manage" }, // scopes for the new resource server
  new UserAssertion(
    commonAccessToken, // the original token obtained from SPFx web part
    "urn:ietf:params:oauth:grant-type:jwt-bearer")).ExecuteAsync().ConfigureAwait(false);

return newTokens.AccessToken;
```
