### ISSUE TITLE
SpFx Extensions Cannot be Deployed to new Dev Tenant

### ISSUE THREAD

**Issue by pdemro** [SharePoint/sp-dev-docs#808]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
It should be possible to deploy a vanilla "hello world" extension to the app catalog on a dev tenant

#### Observed Behavior
Created a dev tenant per instructions at https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant

Attempt to deploy a vanilla extension to the tenant produces the error: _The requested operation is part of an experimental feature that is not supported in the current environment._

#### Steps to Reproduce
**SharePoint**
Create a dev tenant per instructions at https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant
Create an app catalog

**Local**
Install nodejs LTM
npm install gulp yo @ microsoft/generator-sharepoint
yo @ microsoft/sharepoint
   - Select extension(preview) all other defaults
gulp build
gulp package-solution
drag/drop solution into app catalog

_The requested operation is part of an experimental feature that is not supported in the current environment._

**Comment by mcmynn83** [comment]
What is the URL of your tenant (we'd like to confirm it is a dev tenant).

**Comment by pdemro** [comment]
demro2.sharepoint.com

demro3.sharepoint.com

**Comment by mcmynn83** [comment]
Demro2 and Demro3 are NOT dev tenants.  What lead you to believe they were?  Just curious as I'm not seeing it in the backend and want to make sure there isn't some other issue.

**Comment by pdemro** [comment]
The reason I thought these were dev tenants is because I followed the instructions from the linked article [Set up your Office 365 tenant](https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant), completed the form at https://profile.microsoft.com/RegSysProfileCenter/wizardnp.aspx?wizid=7a6e3d71-b057-49cc-b2aa-158ff23432f3&lcid=1033&culture=en-us&dir=LTR, and finally signed up for the 30 day trial

Do you know if there is another way to create a dev tenant @mcmynn83 ?  It sounds like this might be an issue related to the documentation, or possibly an issue with the dev tenant provisioning process

**Comment by pdemro** [comment]
Here is a link to the complete process used to set up both of these tenants.  What step did I miss?

https://dev.office.com/devprogram.

**Comment by Fizzlenik** [comment]
Hi @pdemro, I went through the steps myself to verify and I also did not get a dev tenant on the other side.  It looks like we may have an issue either with the documentation or provisioning.  We'll follow up and figure out what's going wrong.  As far as I can tell there are no steps you could have missed.

**Comment by JeremyKelley** [comment]
Whoops, the curse of multiple account management.  "Fizzlenik" is me, so yes we're actually looking at it.  -Jeremy Kelley

**Comment by pdemro** [comment]
@JeremyKelley Where can I open a ticket to troubleshoot Dev Tenant provisioning?
