### ISSUE TITLE
Update Office UI Fabric React from 2.31.0 to currently 4.37.5

### ISSUE THREAD

**Issue by DennisKuhn** [SharePoint/sp-dev-docs#812]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The SharePoint libraries to be somewhat up to date, the documentation describes the used components.

#### Observed Behavior
Office-UI-Farbic react current version is `4.3.75`. The SharePoint scaffold builder `@microsoft/sharepoint` version `1.1.3` uses the following libraries:

    npm ls office-ui-fabric-react
        i-logger-webpart@0.3.0 D:\spfx\iLogger-webpart
        `-- @microsoft/sp-webpart-base@1.1.1
          `-- office-ui-fabric-react@2.31.0

The documentation at [dev.office.com/fabric#/components](https://dev.office.com/fabric#/components) is way ahead and only gives and ideahow to use the old version. Some components like `SpinButton` and `ComboBox` are missing entirely.

Are there any plans on updating the libraries?
Can I update the `Office-Ui-Fabric-React` library myself?
I am using the standard development set up with `Code`, and am deploying to Azure and running on a O365 hosted SharePoint sites.

I asked a similar question at https://github.com/OfficeDev/office-ui-fabric-react/issues/2600 last week, but didn't get a helpful reply yet.

**Comment by michel-weber** [comment]
As far as I know using anything newer than `4.26.0' of office-ui-fabric-react is not supported because it needs a version of TypeScript newer than 2.2.2 (which is bundled with SPFx).

We are trying to upgrade to 4.26.0.

We already know there are some recently introduced problems with @uifabric/utilities@4.10.3 which uses TypeScript >= 2.3 functionality.
We plan to downgrade the @uifabric/utilities by using npm shrinkwrap.

Also see this issue about TypeScript 2.4:
https://github.com/SharePoint/sp-dev-docs/issues/394#issuecomment-325423789

> The SPFx toolchain ships with a specific version of the TypeScript compiler. There are ways to override it (e.g. via TypeScriptConfiguration.setTypescriptCompiler() in your Gulpfile), however we generally recommend against that, because it will put you in an untested state. For small projects, the compiler doesn't matter that much, but for large code bases pretty much every single compiler upgrade causes some kind of regression or break (in our experience). The best workaround is to downgrade to a version of your typings that is compatible with your compiler. Since @types projects don't follow SemVer and specify their indirect dependencies using a wildcard, in some cases you may need to add an indirect dependency to your package.json file as well.

> **BTW our core toolchain already upgraded to TypeScript 2.4. This will ship in the next release of SPFx, which is right around the corner.**

**Comment by mcmynn83** [comment]
The new version was released today.

**Comment by DennisKuhn** [comment]
Thanks for the great explanation @michel-weber ... and thanks for the awesome news @mcmynn83  ... the upgrade shall begin :-)

    > npm update:
    +-- @microsoft/sp-build-web@1.2.0
    +-- @microsoft/sp-core-library@1.2.0
    +-- @microsoft/sp-module-interfaces@1.2.0
    +-- @microsoft/sp-webpart-base@1.2.0
    +-- @microsoft/sp-webpart-workbench@1.2.0
    `-- @types/react@15.0.38

    > npm ls office-ui-fabric-react
    `-- @microsoft/sp-webpart-base@1.2.0
      `-- office-ui-fabric-react@4.32.0

**Comment by jpalo** [comment]
Did it work for you @DennisKuhn? I'm running into sp-loader issues. Described it here #821, although that is a fresh yeoman repro.

**Comment by DennisKuhn** [comment]
It works for me, except some changes with CSS and some funny Checkbox behaviour. Oh seems I am too late and you resolved it. I hope it works now for you :-)
