### ISSUE TITLE
❓ Why are extension property interfaces in same file as extension, but not with web parts?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#815]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Consistency across project types

#### Observed Behavior
CSWP projects create the interface for public properties on the web part in it's own file and import that file into the CSWP's main TypeScript file.

But extensions, in the latest RC0 (generator v1.2.0) and previous dev preview, include them in the same file as the extension. 

Why? **For consistency sake, these interfaces should be in their own file just like CSWP's**

**Comment by mpasarin** [comment]
On the GA release for extensions you'll find that both extensions and web parts have the properties interface in the same file as the extension/web part.
We hope this will make it easier for developers.

**Comment by andrewconnell** [comment]
That's a disappointing direction.
