### ISSUE TITLE
--global should not be used with npm install @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by ShadowPic** [SharePoint/sp-dev-docs#8155]
[Enter feedback here]
my debugging has found that if you install the  @microsoft/generator-sharepoint with an option of --global it does not work.  if you install it with --save --save-exact it seems to work just fine.

This will burn a lot of hours for our customers if not resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@ShadowPic - could you provide some details of your environment as `npm i -g @microsoft/generator-sharepoint` definitely works.
