### ISSUE TITLE
Yeoman Sharepoint generator always creates Preview project

### ISSUE THREAD

**Issue by kspranesh** [SharePoint/sp-dev-docs#816]
#### Category
- [ ] Issue :  After installing latest Yo @microsoft generator when i try to create a project, even if i select the type of client side component as Webpart, the next option appears as Which type of Client side extension to create.

#### Steps to Reproduce
Please refer to the screenshot for the issue. I am selecting the component type as Webpart, the next option presented is with the component type as Extension.

![yo-issue](https://user-images.githubusercontent.com/12847736/29852806-2f7b9256-8d0a-11e7-9c4f-93bd0f1eff87.png)

The sharepoint generator version i have is 1.2.0

Please help!

Also, i need instructions to remove and uninstall the yeoman Sharepoint generator from my system to do clean install. I tried to execute npm -uninstall -g generator @microsoft/sharepoint@1.2.0 nothing happens.

**Comment by VesaJuvonen** [comment]
Hi @kspranesh,
we can't seem to reproduce the issue with the given information, so would double check following things.

**Ensure that you have uninstalled old package and reinstalled new version**
Uninstall old version by executing `npm uninstall --global @microsoft/generator-sharepoint`, which will clean up any old version of the generator. You can then double check all the installed packages globally by using `npm list -g --depth=0` to confirm that uninstallation has been completed. 

After this you can then simply install the latest package by executing `npm install -g @microsoft/generator-sharepoint`.

**Version details**
if this does not resolve your issue, we would need additional details to get your issue resolved, which would be following:

- What OS you're using?
- What's your Node version?
- What's your npm version?

This way we can potentially reproduce the issue, which is a prerequisite to get it resolved based on facts.

Thanks for the additional details advance.

**Comment by kspranesh** [comment]
Hi @VesaJuvonen 

Many thanks for looking into my request. I followed the steps you mentioned to ensure i have removed and re-installed latest version of sharepoint generator and verified that issue still persists. Please find attached are few screenshots from my testing. I am executing this on Windows 10 OS. 

![node versions](https://user-images.githubusercontent.com/12847736/29873074-07f1b62e-8d60-11e7-8955-90bbf1d2007f.png)
![yo-issue0](https://user-images.githubusercontent.com/12847736/29873075-07f2990e-8d60-11e7-8b32-0c0c076eda99.png)
![yo-issue1](https://user-images.githubusercontent.com/12847736/29873076-07f776e0-8d60-11e7-9e72-88547ca8dc15.png)
![yo-issue2](https://user-images.githubusercontent.com/12847736/29873077-07f85e20-8d60-11e7-87ad-e8abc4b18898.png)

Kindly let me know if you need any further details.

Regards,
Pranesh

**Comment by Pieter-Veenstra** [comment]
I'm seeing the same issue here.

**Comment by VesaJuvonen** [comment]
Can't reproduce with Win 10 so we would need more details around the setup what you're using.

What's your Node version? - node -v
What's your npm version? - npm -v

This helps on doing a repro for the issue.

**Comment by VesaJuvonen** [comment]
Hmm... I'm running exactly the same versions locally on my machine without any issues, tested with different console UIs as well. Let me test this with clean Win10 in Azure for trying to do repro.

**Comment by kspranesh** [comment]
Hi,

It worked for me 2 days back and when yesterday i tried to add new webpart to the same project i started seeing this issue. Later on i created an entirely new project to verify and this issue occurred even there.

Regards,
Pranesh
________________________________

**Comment by Pieter-Veenstra** [comment]
@VesaJuvonen , what is the best way to recognize if RC0 is used or an earlier version? Is the RC0 version still marked with all the Preview warnings?

**Comment by VesaJuvonen** [comment]
You can see this from the package.json of the outcome projects after the template is executed, but unless mistaken, in this case, you can't even execute the flow for some reason. This is a tough one since we can't reproduce it on a clean computer with matching version numbers.

**Comment by kspranesh** [comment]
Hi, I uninstalled everything including npm and re-installed everything from scratch and it seems to have resolved the issue. Thanks for your attention in this regard.
