### ISSUE TITLE
Page out of date - Instructions for referencing Excel UDF can't be followed.

### ISSUE THREAD

**Issue by dheine777** [SharePoint/sp-dev-docs#8162]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b71994b-2464-c923-9e4c-a45f961e466d
* Version Independent ID: 095cb3d8-93d8-d29d-7073-321b86509f12
* Content: [Step 1 Creating a Project and Adding a UDF Reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/step-1-creating-a-project-and-adding-a-udf-reference)
* Content Source: [docs/general-development/step-1-creating-a-project-and-adding-a-udf-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/step-1-creating-a-project-and-adding-a-udf-reference.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
No details on the issue, so closing.
