### ISSUE TITLE
Getting Invalid Location: ClientSideExtension.ApplicationCustomizer even after making changes based on latest release

### ISSUE THREAD

**Issue by thePaddyVP** [SharePoint/sp-dev-docs#817]
I am using the Application Customizer to add some content on the pages. I changed the code based on latest release of Sharepoint framework extensions. I am still getting Invalid Location: ClientSideExtension.ApplicationCustomizer. Is there anything i am missing? I updated the extensions using npm install -g @microsoft/generator-sharepoint.  #817

**Comment by VesaJuvonen** [comment]
Hi @thePaddyVP, this could mean that the extensions are not yet enabled in your tenant. Like with Dev Preview, extension RC will work within developer tenants and will be gradually extended to first release tenants within a day or two (just takes time to enable settings). 

To be able to understand what might go wrong in your case, we would need to understand at least the tenant type you're using and potentially also the site template where you are doing testing...  Thx for the additional details advance.

**Comment by thePaddyVP** [comment]
Hi @VesaJuvonen I am using a developer tenant with a team site template. Let me know if you need more details.

**Comment by OliverZeiser** [comment]
I was seeing the same issue in a developer tenant. But only when using the debug querry string parameter. Deploying to the app catalog worked.
After creating a new site, things have been working in the new site. So I am guessing, there are some dependencies left over in my old site that I have been using for testing version 1.1.0 before.

@thePaddyVP Try to create a new site and see if it works there.

**Comment by wictorwilen** [comment]
I experience similar issue I get the `Invalid location: ClientSideExtension.ApplicationCustomizer` error message in the console window - but the application customizer works as expected...

**Comment by AJIXuMuK** [comment]
Experienced the same. New site worked for me as well.

**Comment by AJIXuMuK** [comment]
Everything is so weird...
I'm getting `Invalid location: ClientSideExtension.ApplicationCustomizer` without any explanation if there is not `properties` parameter in debug url.
If I add `"properties":{}` then I'm first getting:
```
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.3a685093-7cf3-4e8f-9bd9-f1560ec66034'. Error information is '***Expecting a class that extends function t(){return null!==e&&e.apply(this,arguments)||this}.'.
    at listview-host-assembly_en-us_8faa48cbb0cd205bf7b5c7b0fd24d2ca.js:338
```
and then `Invalid location: ClientSideExtension.ApplicationCustomizer`

I'm on DEV tenant, brand new site collection.

**Comment by VesaJuvonen** [comment]
We had some issues with the first release tenant enabling and extensions, but all should be now up and running after GA last week. If there are any issues with this still, just let us know and we can re-open if needed. Will close for now.
