### ISSUE TITLE
Developer Site Option Missing

### ISSUE THREAD

**Issue by pgodwin** [SharePoint/sp-dev-docs#8177]
The documentation for this doesn't appear to have been updated for the latest version of the admin portal.

For example, site collections no longer exists, and developer-sites isn't a template option:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1046558/173475487-71f610bd-f886-445a-b067-ee8e6b5f7e7e.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b3a5c8-08fe-a0c9-c4df-9daaab5a649e
* Version Independent ID: c7e977b2-f2b5-685f-6e84-ce243305cf77
* Content: [Create a developer site on an existing Office 365 subscription](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription)
* Content Source: [docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md)
* Service: **sharepoint**
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
The steps are correct in the doc. You have to select the **Other Options** and then **More Templates** as the docs state. That will launch a new window with the **Create Site Collection** page.
