### ISSUE TITLE
SharePoint List flows with Power Automate - Manage run-only by List

### ISSUE THREAD

**Issue by teixeire** [SharePoint/sp-dev-docs#8180]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Power  @Automate

### Issue description

When providing access to run-only for a list in Power Automate, it is requested according to the documentation that a 'Edit' permission level is required, however, sometimes, people cannot have some functionalities available (as Delete) , even though they must me able to execute flow.

[Manage owners and users in your Microsoft list flows with Power Automate | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/manage-list-flows)
![image](https://user-images.githubusercontent.com/83093714/173571383-366d9571-7f8b-41e1-a01b-5a7780d9fff9.png)

So, my questions are:

**1.** Is this rule applied for ‘List Permission’ or ‘Site Permission’ inside ‘Edit’ permission level?
**2.** Which specific option allows user which have access to this list to run-only the flow? 
**3.** ..Or is it applied by the name of permission level – ‘Edit’? 

![image](https://user-images.githubusercontent.com/83093714/173571350-ad6b22fc-72b1-4d2f-92a6-5022c17713e5.png)
![image](https://user-images.githubusercontent.com/83093714/173571366-54a7dbcd-8809-4fc1-8d3e-d346b25db0eb.png)

**Comment by AJIXuMuK** [comment]
@teixeire - thanks for reporting this one!
Unfortunately, it is not a SharePoint Dev issue.
I would suggest you post it in Power Platform specific location: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity
