### ISSUE TITLE
SPFX Teams app blank screen when you open it for second time

### ISSUE THREAD

**Issue by Rtoribiog** [SharePoint/sp-dev-docs#8191]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

browser version Teams desktop App
SPFx version 1.13
Node.js version V 12.13
etc

### Describe the bug / error

When you load your custom sfpx teams app for second time after clicking in any other section in teams it doesn't load up and it shows white screen.

After digging in the developer tools i've seen this error

![image](https://user-images.githubusercontent.com/687795/173682050-fba6a913-c81b-42a0-96c1-ce01abf65a90.png)

### Steps to reproduce

You have a custom spfx teams app ,   you click on the app and it's loads fine

![loads](https://user-images.githubusercontent.com/687795/173681232-0c2b2d65-5f83-4a6b-9e8d-ee19ef555531.png)

Later you click in any option in the menu like calendar ,  teams chat

![otherfeature](https://user-images.githubusercontent.com/687795/173681347-52760cc2-6515-424e-8ff9-0fd7854b8b69.png)

You click in teams app again and then it show up white screen

![Error](https://user-images.githubusercontent.com/687795/173681731-85ccd8ac-0764-4c52-ad6c-c4d9de22b01d.png)

### Expected behavior

The app it works fine without taking in count where do you click or if you want to return to the app after doing any other action.

**Comment by Rtoribiog** [comment]
more information regarding the error

![image](https://user-images.githubusercontent.com/687795/173682348-1a6cae85-3cbb-4128-8b23-cc52ecfaaeaa.png)


We are using custom app manifest following this guideline

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions#developer-provided-microsoft-teams-app-manifest--package

Here the url under it  https://xxx.sharepoint.com/_layouts/15/teamslogon.aspx?spfx=true&dest=/SitePages/Viva-Home.aspx?app=portals

**Comment by AJIXuMuK** [comment]
Hi @Rtoribiog - thanks for reporting this one.
Could you please share your custom manifest either here or you can send it to me aterentiev@microsoft.com

**Comment by Rtoribiog** [comment]
you have it in the email.  Thanks

**Comment by AJIXuMuK** [comment]
Thank you @Rtoribiog!
I don't see `?app=portals` in your manifest.
Are you saying it is added when navigating back to the app?

Also, the manifest is not completely correct. As pointed out in the article you've mentioned, in `webApplicationInfo` you should set `resource` as `https://{teamSiteDomain}`, not the actual domain name.

Could you please also update the manifest and test it again?

Thanks!

**Comment by Rtoribiog** [comment]
hello @AJIXuMuK ,  sorry my fault,  i've sent you old version of the app.   Because all the things you mentioned were fixed some time ago.  I sent you current version by email again.  Thanks

**Comment by Rtoribiog** [comment]
hello @AJIXuMuK ,  have you seen anything that can be wrong or it's a bug as i'm thinking.  Adding also @GrahamMcMynn to the thread, maybe he knows what is going on.  Thanks

**Comment by AJIXuMuK** [comment]
Hey @Rtoribiog - we're looking into it and will update the thread as soon as have further details.

**Comment by AJIXuMuK** [comment]
@Rtoribiog - this has been fixed and will be rolled out WW in the next couple of weeks.

**Comment by Rtoribiog** [comment]
thanks so much

**Comment by Rtoribiog** [comment]
hello @AJIXuMuK , the deployment to teams app was released week ago. But still is not working properlly.  Now when you click again in the app open the browser of the url instead of open the app inside teams.

Attached screenshot with the problem , feel free to reach me for more info

![error](https://user-images.githubusercontent.com/687795/178929058-06e9372c-0d12-4c25-855f-8bbfc0e2ed9c.png)

**Comment by AJIXuMuK** [comment]
That seems to be a separate bug.
I will create a new one to track it properly.
