### ISSUE TITLE
Token renewal operation failed due to timeout on the tenant with recently updated tenant URL

### ISSUE THREAD

**Issue by sharepointalist** [SharePoint/sp-dev-docs#8192]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version - 1.13

### Describe the bug / error

Customer with the tenant with recently updated tenant URL (4 days ago) is experiencing issues with loading up SPFx web part. We are getting "ClientAuthError:Token renewal operation failed due to timeout" from spfxsiglesignon.aspx.

The issue was reproduced on multiple browsers and environments, including incognito mode. 

![Screen Shot 2022-06-14 at 11 42 09 AM copy](https://user-images.githubusercontent.com/19199802/173669474-bc0c3c12-b909-4df0-a10a-7f4891830b23.jpg)
 

### Steps to reproduce

1. Update tenant URL.
2. Load up SPFx web part
3. Authentication times outs

### Expected behavior

Authentication should go through succesfully.

**Comment by sharepointalist** [comment]
The issue goes away after reinstalling the app and visiting API page

**Comment by AJIXuMuK** [comment]
@sharepointalist - thanks for reporting this one!
Reinstalling is not needed but visiting API page is required.
We will update the [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name) article to point it out.
