### ISSUE TITLE
CSS icon image files will not load in workbench.aspx

### ISSUE THREAD

**Issue by SteveCurran** [SharePoint/sp-dev-docs#82]
I am testing my webpart on workbench.aspx  in Chrome allowing for mixed mode but the icons do not show up because there are no requests being made for the image files:

Example of css:
.k-loading-image {
  background-image: url('Office365/loading-image.gif');
}

![workbenchaspx_noicons](https://cloud.githubusercontent.com/assets/10567535/17985696/90d768fa-6adc-11e6-9a18-115416ca2bdd.PNG)

However, icons show up and image requests are made when using Workbench.html

![image](https://cloud.githubusercontent.com/assets/10567535/17985789/02ff5ee2-6add-11e6-85c0-a1458a40b7dc.png)

**Comment by patmill** [comment]
If you look at the network trace in Chrome, are you seeing any 404's?  If so, what does the full URL to them look like?

**Comment by SteveCurran** [comment]
Yes there are 404's. 
![image](https://cloud.githubusercontent.com/assets/10567535/17990848/19a8843a-6aff-11e6-8d10-185ad2fd2bb2.png)

**Comment by SteveCurran** [comment]
Any news on this?

**Comment by nickpape-msft** [comment]
@iclanton I believe this could be a WebPack public path issue, based on the URL above. This is an area we're actively looking to improve.. Can you ensure you have

```javascript
require('set-webpack-public-path!');
```

At the top of your WebPart.ts file?

**Comment by SteveCurran** [comment]
Thanks @nickpape-msft that fixed the problem.
