### ISSUE TITLE
Sharepoint Highlighted Content Web part truncation of title display

### ISSUE THREAD

**Issue by avinashgit18** [SharePoint/sp-dev-docs#8200]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

 Sharepoint Highlighted Content Webpart display :  It's truncating the title even when it's only one word long.  This makes it not readable. 

### Steps to reproduce

1.Add a out of the box highlighted content webpart 
2. Add title and check the display

### Expected behavior

It's truncating the title even when it's only one word long.  This makes it not readable. This should display the title correctly with out truncating

**Comment by AJIXuMuK** [comment]
Thanks @avinashgit18 for reporting this issue!
I've transferred it to the appropriate team and will be closing this one as this list is for dev-related issues.
