### ISSUE TITLE
SPFx 1.15 preview release - eslint version 7.12.1 instead of 8.7.0

### ISSUE THREAD

**Issue by MarkusLanger** [SharePoint/sp-dev-docs#8201]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Version 102.0.5005.115 (Official Build) (x86_64)
- SPFx version: 1.15.0-rc.0
- Node.js version: v14.19.3

### Describe the bug / error

The SPFx 1.15.0-rc.0 includes ESLint package version 8.7.0. When I run "gulp build" the ESLint version 7.12.1 is used. 
Why it is not the version 8.7.0 of eslint? 
I want to use the eslint-plugin-prettier but in the latest version this package needs at least ESLint 7.28.0 (https://github.com/prettier/eslint-plugin-prettier/blob/master/CHANGELOG.md#v400-2021-08-30) 

![image](https://user-images.githubusercontent.com/12131918/173839392-6ff0b06b-7726-437b-9b72-347700d77fbc.png)
![image](https://user-images.githubusercontent.com/12131918/173839434-f1916f14-e3c9-4ea3-b0d3-b4c3a5a8f521.png)

### Steps to reproduce

1. create new project with yo generator and SPFx 1.15.0-rc.0
2. npm install
3. gulp build
4. for the lint step version 7.12.1 is used

### Expected behavior

I would expect that ESLint version 8.7.0 is used for the lint step.

**Comment by AJIXuMuK** [comment]
@MarkusLanger - with the release of SPFx 1.15.0 we introduced support of `eslint` v8.7.0.
It is not exactly the fix of the issue as the dependency from `package.json` is still not respected.
But we've also created work item in internal backlog to address it completely.
