### ISSUE TITLE
Schema for client side WebPart manifest miss preconfiguredEntries.dataVersion

### ISSUE THREAD

**Issue by mgrosperrin** [SharePoint/sp-dev-docs#8204]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version: 1.14
- Node.js version: 12.13.1
- etc

### Describe the bug / error

The schema `https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#web-part-preconfigured-entries` does not contains the definition for the property `preconfigureEntries.dataVersion` (see https://github.com/SharePoint/sp-dev-docs/issues/8199#issuecomment-1156578769).
Based on the documentation https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#web-part-preconfigured-entries, this is a valid value.

### Steps to reproduce

1. Create a new SharePoint solution package
2. Add a new WebPart
3. Add the entry `dataVersion` in the `preconfiguredEntries`

### Expected behavior

The property should be discoverable (aka present in intellisense), and no error/warning should be shown.

**Comment by AJIXuMuK** [comment]
The documentation is invalid, not the schema.
