### ISSUE TITLE
yo @microsoft/sharepoint failing due to @microsoft/sp-loader@1.2.0~install: Failed to exec install script

### ISSUE THREAD

**Issue by jpalo** [SharePoint/sp-dev-docs#821]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

_First of all I feel like this is wrong place for this, but other issues appear to discuss similar topics, so please let me know if there is better forum for this question._

#### Expected or Desired Behavior
Currently `yo @microsoft/sharepoint` doesn't work due to issue with `@microsoft/sp-loader@1.2.0`.

#### Observed Behavior
At the end you get error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/sp-loader@1.2.0 install: `node npm-postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @microsoft/sp-loader@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jussi\AppData\Roaming\npm-cache\_logs\2017-08-30T11_01_11_168Z-debug.log
```
Log here:
[2017-08-30T11_01_11_168Z-debug.zip](https://github.com/SharePoint/sp-dev-docs/files/1263327/2017-08-30T11_01_11_168Z-debug.zip)

#### Steps to Reproduce
Create new folder, run `yo @microsoft/sharepoint` followed by
? What is your solution name? **tester**
? Where do you want to place the files? **Use the current folder**
? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites? **Yes**
? Which type of client-side component to create? **WebPart**
? What is your Web part name? **HelloWorld**
? What is your Web part description? **HelloWorld description**
? Which framework would you like to use? **No JavaScript framework** (also if you select **React**)

`npm outdated -g` shows everything is updated (except npm itself which is 4.6.1).

**Comment by iclanton** [comment]
Can you run `npm install --ignore-scripts` in the directory and then run `node node_modules/@microsoft/sp-loader/npm-postinstall.js` and post what that second command prints? I'm going to try to repro myself as well.

**Comment by iclanton** [comment]
I'm not seeing a repro, so I'd be interested in learning what the result of manually running the postinsall script is.

**Comment by jpalo** [comment]
Thank you, first one succeeds without errors, second one prints:
```
C:\temp\tester2\node_modules\@microsoft\sp-loader\npm-postinstall.js:3
const { fixNpmBundle } = require('./npm-postinstall-common');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by iclanton** [comment]
What version of node are you running? SPFx requires 6+. We currently recommend the LTS version (6.11.2).

**Comment by jpalo** [comment]
That was it, had 4.4.5, and after updating to 6.11.2 LTS, it worked. Must've been some change in SPFx 1.2.0 vs. earlier version as I hadn't run into this earlier.
