### ISSUE TITLE
Error when updating Taxonomy-Based Properties in UPS

### ISSUE THREAD

**Issue by LeopoldLerch** [SharePoint/sp-dev-docs#8210]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

I am using CSOM in order to update the User-Profile-Properties. I cannot tell the date, but since some weeks we cannot update Properties based on Taxonomy-Values, when the new Term is not already in the Termstore. This happens eg. for SPS-Location or the "Hobbies"-Property. Updating with values already existing in the Termset works. 

The exception is the Error-Message stating, that the current user does not have sufficient privileges. However, as mentioned, updating to already existing values works, and adding new Hobbies via Delve works also (with the same user). All other properties work also. Termsets are open for new values of course.

Also happens, when calling the REST-API via 
/_api/sp.userprofiles.peoplemanager/SetMultiValuedProfileProperty (which is the REST-aquivalent of CSOM).
So this seems to be not bound to a specific version of CSOM, but rather some issue in the receiving WebService from MS directly.

### Steps to reproduce

1. Connect with CSOM to Sharepoint-Online
2. Update  TaxonomyProperty (eg Hobbies, SPS-Location) with value, not already present in Termset

### Expected behavior

Update should work and new value added to Termset (as it was some time ago)

**Comment by LeopoldLerch** [comment]
Seems to have something to do with being authenticated via Oauth. Error message occurs when doing it against REST-Endpoint via oauth-Bearer, and when doing it via CSOM using AppOnly Authentication. 

However, it seems to work, when executed via CSOM while using SharepointOnlineCredentials-Authentication (with an Tenant-Admin). 

As this might be a workaround for my backend Service, it does not help on my frontend, where I want to update current User´s profile using current-Users Credentials/Oauth-Token

**Comment by bcameron1231** [comment]
I saw an issue like this popup for me a couple months ago. We used app-only and the REST API.  We had a process in place for about a year that was updating and adding term sets perfectly fine... when all of a sudden it stopped working. When we re-added our App Permission Request XML for the principal registration in ACS, everything started working again.

**Comment by LeopoldLerch** [comment]
Already did that, but did not help

**Comment by bcameron1231** [comment]
Can you confirm what your Permission XML was?

**Comment by LeopoldLerch** [comment]
it is 

`  <AppPermissionRequests AllowAppOnlyPolicy="true" >
    <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="Manage" />
  </AppPermissionRequests>`

however, as mentioned, it also happens using "normal" AAD-Oauth-Token of current user.

**Comment by bcameron1231** [comment]
Can you update your permissions to include the http://sharepoint/taxonomy as well? it appears to be missing from your App Permissions.

You can see that in Table 7 on this page
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint

**Comment by LeopoldLerch** [comment]
Can try this.
However, this will not help in the frontend part, where I set the properties with an Oauth-Token of the current User against the REST-API

**Comment by LeopoldLerch** [comment]
I changed the AppOnly Permissions now to

  <AppPermissionRequests AllowAppOnlyPolicy="true" >
    <AppPermissionRequest Scope=http://sharepoint/content/tenant Right="FullControl" />
    <AppPermissionRequest Scope=http://sharepoint/social/tenant Right="FullControl" />
    <AppPermissionRequest Scope=http://sharepoint/taxonomy Right="Write" />
  </AppPermissionRequests>

and added „TermStore.ReadWrite.All” to the Permissions of the AAD-Registered App. Now it seems to work for the Backend-Service using the AppOnly-Permissions as well as for the User on the Frontend using its own AAD-Token together with the AAD-Registered-App.

However, this was not necessary for the last 2 years. It seems that something changed at the services that urges the Oauth-Token  (in both use-cases) to explicitly include Termstore-Permissions when updating the UserProfile.
