### ISSUE TITLE
SharePoint Search is not persistent and not working!

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#8212]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We are having a strange issue since today morning. We have couple of Search webparts in our Home page which is an Hub site. The webparts are not loading results even with out of box handlebar templates. We tested the standard sharepoint search, the results are not persistent. Sometimes, results are empty. If we look into Network tab, we are receiving 500 error for /_api/search/postquery endpoint. Please refer the screenshot here: 
![image](https://user-images.githubusercontent.com/12812202/174747478-69f8436a-d636-48d6-b0a0-eae32b2df1bb.png)

### Steps to reproduce

1. We can reproduce this via PnP Modern search webpart immediately. If you add the webpart to a page, it fails immediately. 
2. If you search in standard SharePoint, resutls are empty sometime and sometimes we get results.

### Expected behavior

Search work normally without failing

**Comment by AJIXuMuK** [comment]
@arunakshi - is it still happening? Or maybe it was a temporary glitch?

**Comment by arunakshi** [comment]
@AJIXuMuK This issue was persisted for some regions of users until end of day. I don't see anymore the incident related to SharePoint Search in message center also. Hope this was a temporary glitch.

**Comment by spplante** [comment]
Search simply stopped working at all for me in my dev tenant. I create a brand new team, add a document to the default documents library, force crawl on site, force crawl on list, nothing gets crawled,  no result at all.

I also get a system error when trying to add a mapping in a RefinableString managed property through the search schema UI, looks like the search in general is broken?

**Comment by arunakshi** [comment]
@AJIXuMuK I was checking today morning. The same error occured again for me and it didn't occur for my colleague. We both are accessing the site from different regions. Is it fixed perminantely? Could you please verify.

**Comment by arunakshi** [comment]
Looks like this is resolved for us now.

**Comment by wobba** [comment]
Can confirm this is resolved.
