### ISSUE TITLE
SPFx in teams client "Unable to retrieve Client Secret"

### ISSUE THREAD

**Issue by kristofferarn** [SharePoint/sp-dev-docs#8213]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.13.1
- Node.js 14+
- Teams Client

### Issue description

We have created a SPFx teams app that uses Microsoft Graph endpoints that works in browser and fails in teams client. The error message is "Unable to retrieve Client Secret". When inspecting the Sharepoint App Principal in azure we notice that the auto generated client secret has been replaced with a custom secret. Is there anyway to fix this without deleting the App Principal?

View images for secret and app manifest.
![Manifest](https://user-images.githubusercontent.com/22076588/174752011-cfbd7c7f-aaa6-4f2e-b2b0-d1a4cedbef17.png)
![Secret](https://user-images.githubusercontent.com/22076588/174752014-b33da696-053e-41ab-85a3-6032e88e332d.png)

**Comment by AJIXuMuK** [comment]
@kristofferarn - thanks for reporting this one.
Could you please re-visit API Access page in SharePoint Admin Center?
@GrahamMcMynn - fyi.

**Comment by kristofferarn** [comment]
Hi @AJIXuMuK 
An attempt to fix the issue by visiting the API Access page with a global admin user has already been tried without success. 
Visiting the API page does not re-create the missing client secret unfortunately.

**Comment by GrahamMcMynn** [comment]
@kristofferarn  - would it be possible to send 2 network traces?  One when you load the API Access and another when your app loads in teams?  That would really help us diagnose what is wrong.  You can email it to grahamc at microsoft.com.

**Comment by kristofferarn** [comment]
Managed to solve the problem by deleting the existing secret and then visiting the API Permission page. A new secret was then generated and the app manifest updated with that secret.
