### ISSUE TITLE
gulp trust-dev-cert issues 

### ISSUE THREAD

**Issue by hassannaji399** [SharePoint/sp-dev-docs#8221]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc
- SharePoint framework

### Issue description

please I need help with this...

I am trying to use this command "gulp trust-dev-cert" to start with SharePoint but there is some issues i do not know how to solve them.
 😭  😭  😭  😭  😭  😭 PLEASE HELP!!!!!

C:\code>gulp trust-dev-cert
Build target: DEBUG
[11:42:21] Using gulpfile C:\code\gulpfile.js
[11:42:21] Starting 'trust-dev-cert'...
[11:42:21] Starting gulp
[11:42:21] Starting subtask 'trust-cert'...
[11:42:21] [trust-cert] Attempting to trust a development certificate. This self-signed certificate only points to localhost and will be stored in your local user profile to be used by other instances of debug-certificate-manager. If you do not consent to trust this certificate, click "NO" in the dialog.
[11:42:21] **Error - 'trust-cert' sub task errored after 159 ms
 The executable file was not found: "certutil"**
[11:42:21] **'trust-dev-cert' errored after 162 ms**
[11:42:21]
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

C:\code>

 😭  😭  😭  😭  😭  😭 PLEASE HELP!!!!!

**Comment by AJIXuMuK** [comment]
Hello @hassannaji399,
Could you please provide details of your environment and used SPFx version?
- Node.js version
- SPFx version
- Are you using Docker?

**Comment by hassannaji399** [comment]
hi @AJIXuMuK ,
I've installed all the dawn below using via cmd
node v14.19.1

+-- @microsoft/generator-sharepoint@1.15.0
+-- gulp-cli@2.3.0
`-- yo@4.3.0

and no I am not using Docker because I'm new to this... so yeah

**Comment by hassannaji399** [comment]
> Hello @hassannaji399, Could you please provide details of your environment and used SPFx version?
> 
> * Node.js version
> * SPFx version
> * Are you using Docker?
