### ISSUE TITLE
1.15 also support v16 Node, which isn't reflected in the table

### ISSUE THREAD

**Issue by fonbrauzen** [SharePoint/sp-dev-docs#8224]
1.15 also supports v16 Node, which isn't reflected in the table, but clearly written in 1.15 release notes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25459e4a-2488-302d-9906-cfacfdc4639a
* Version Independent ID: 339fbcec-873c-9c47-fd9c-cf5f505132ac
* Content: [SharePoint Framework development tools and libraries compatibility](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility)
* Content Source: [docs/spfx/compatibility.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/compatibility.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by milanholemans** [comment]
Has been fixed in #8217.
