### ISSUE TITLE
Why using alias in KQL does no give me results

### ISSUE THREAD

**Issue by FranBor** [SharePoint/sp-dev-docs#8225]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version:  103.0.5060.53 (Build ufficiale) (a 64 bit)
- Microsoft.SharePointOnline.CSOM: 16.1.21213.12000

### Issue description

I have a Number column with the internal name IdDocSet.
On the managed properties page I edited the property RefinableDecimal01 with alias IdDocSet and mapping ows_IdDocSet.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/19620644/175519124-7ce859cf-d3a5-4746-b47a-9ebdc0f4aae2.png">

Below is the piece of code I use for research

```
KeywordQuery keywordQuery = new KeywordQuery(context);
keywordQuery.QueryText = "path:https://{MyDocumentLibraryUrl} AND (ContentTypeId:0x0120D520* OR ContentTypeId:0x0101*)";

keywordQuery.CollapseSpecification = "IdDocSet";

keywordQuery.SelectProperties.Add("IdDocSet");

keywordQuery.SortList.Add("IdDocSet", SortDirection.Descending);

SearchExecutor searchExec = new SearchExecutor(context);
ClientResult<ResultTableCollection> resultTableColl = searchExec.ExecuteQuery(keywordQuery);
context.ExecuteQueryRetry();
```

When I run the code i get the error below:
```
  Microsoft.SharePoint.Client.ServerException: Search has encountered a problem that prevents results from being returned.  If the issue persists, please contact your administrator.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
```
If I run the same code using "RefinableDecimal01" instead of the "IdDocSet", it works fine.

I need to use the alias in my code, please help me.

**Comment by FranBor** [comment]
> ### What type of issue is this?
> Question
> 
> ### What SharePoint development model, framework, SDK or API is this about?
> SharePoint CSOM
> 
> ### Target SharePoint environment
> SharePoint Online
> 
> ### What browser(s) / client(s) have you tested
> * [ ]  💥 Internet Explorer
> * [ ]  💥 Microsoft Edge
> * [x]  💥 Google Chrome
> * [ ]  💥 FireFox
> * [ ]  💥 Safari
> * [ ]  mobile (iOS/iPadOS)
> * [ ]  mobile (Android)
> * [ ]  not applicable
> * [ ]  other (enter in the "Additional environment details" area below)
> 
> ### Additional environment details
> * browser version:  103.0.5060.53 (Build ufficiale) (a 64 bit)
> 
> ### Issue description
> I have a Number column with the internal name IdDocSet. On the managed properties page I edited the property RefinableDecimal01 with alias IdDocSet and mapping ows_IdDocSet.
> 
> <img alt="image" width="750" src="https://user-images.githubusercontent.com/19620644/175519124-7ce859cf-d3a5-4746-b47a-9ebdc0f4aae2.png">
> 
> Below is the piece of code I use for research
> 
> ```
> KeywordQuery keywordQuery = new KeywordQuery(context);
> keywordQuery.QueryText = "path:https://{MyDocumentLibraryUrl} AND (ContentTypeId:0x0120D520* OR ContentTypeId:0x0101*)";
> 
> keywordQuery.CollapseSpecification = "IdDocSet";
> 
> keywordQuery.SelectProperties.Add("IdDocSet");
> 
> keywordQuery.SortList.Add("IdDocSet", SortDirection.Descending);
> 
> SearchExecutor searchExec = new SearchExecutor(context);
> ClientResult<ResultTableCollection> resultTableColl = searchExec.ExecuteQuery(keywordQuery);
> context.ExecuteQueryRetry();
> ```
> 
> When I run the code i get the error below:
> 
> ```
>   Microsoft.SharePoint.Client.ServerException: Search has encountered a problem that prevents results from being returned.  If the issue persists, please contact your administrator.
>    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
>    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
>    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
> ```
> 
> If I run the same code using "RefinableDecimal01" instead of the "IdDocSet", it works fine.
> 
> I need to use the alias in my code, please help me.

**Comment by FranBor** [comment]
Any news

**Comment by wobba** [comment]
This seems to be resolved when I test. @FranBor can you re-test?

**Comment by wobba** [comment]
Resolved.
