### ISSUE TITLE
Deprecation of npm packages don't point to sucessor

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#8227]
Hi,

I can see in version 15 deprecations, but really I don't see any other option to  make things right. I should but I really don't have time to go to all calls.

Deprecated SPComponentLoader#getManifests due to runtime performance overhead.
Removed API from @microsoft/sp-http - MSGraphClientFactory.getClient()

So what should I use to accomplsih "Removed API from @microsoft/sp-http - MSGraphClientFactory.getClient()" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9312f48c-60ef-c8fc-0eed-0c5282c3a956
* Version Independent ID: 9312f48c-60ef-c8fc-0eed-0c5282c3a956
* Content: [SharePoint Framework v1.15 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.15)
* Content Source: [docs/spfx/release-1.15.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/release-1.15.md)
* Service: **sharepoint**
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
Hi @jtlivio - the same doc describes new API for using MS Graph SDK v3: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.15#microsoft-graph-javascript-sdk-v3-support
