### ISSUE TITLE
Dependency on old version of "@pnp/sp"

### ISSUE THREAD

**Issue by hesperanca** [SharePoint/sp-dev-docs#8231]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

@pnp/spfx-controls-react version 3.8.1

### Issue description

I've noticed that the latest version of the "@pnp/spfx-controls-react" library (version 3.8.1 at time of writing) has a dependency on version 2.5.0 of the "@pnp/sp" library. Are there any plans to upgrade the dependency a V3 version of the "@pnp/sp" library?

Many thanks,
Hugo

**Comment by AJIXuMuK** [comment]
As @bcameron1231 mentioned this issue list is specific to the first-party issues, not community libraries.
@hesperanca - feel free to open the issue in [PnP React Controls](https://github.com/pnp/sp-dev-fx-controls-react/issues) repo.

**Comment by hesperanca** [comment]
Thanks for coming back to me. I will raise it there.
