### ISSUE TITLE
SPFx 1.15 - ESLint - version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree

### ISSUE THREAD

**Issue by MarkusLanger** [SharePoint/sp-dev-docs#8236]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Version 103.0.5060.53
- SPFx version: 1.15 GA
- Node.js version: 16.15.1
- ESLint version: 8.18.0
- TypeScript version 4.7.4

### Describe the bug / error

When I run the eslint command `eslint src/* --ext js,ts,tsx` I get the following warning:

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

![image](https://user-images.githubusercontent.com/12131918/176113801-33726f12-389e-4111-aa94-316164c89c7a.png)

### Steps to reproduce

1. Create a new SPFx Project with version 1.15 GA
2. Install deps with `npm install`
3. Run ESLint with `eslint src/* --ext js,ts,tsx`

### Expected behavior

I would expect that ESLint runs without warning.

**Comment by MarkusLanger** [comment]
I have been using ESLint in my projects for a long time. That's why I have my own NPM script for it.

Looks like the higher version comes from "@rushstack/eslint-config".
![image](https://user-images.githubusercontent.com/12131918/176204557-7b95c98c-269f-4ea9-bbcc-db3ac1f7caa2.png)

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
