### ISSUE TITLE
Custom List Formatting, customCardProps cannot be selected after field text is changed and display

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#8237]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browsers 

### **Error Description:**
This issue appear using Custom List formatting and object customCardProps. 
Scenario have object that call "**customCardProps**" with object that update field using "**customRowAction**", after the **field text is update and display in the row of View**, when try to access object "**customCardProps**" and click again  _**this cannot be selected again and doesn't display dialog**_.

### **Image steps:** 
Where customCardProps lose capability to be selected again after field is changed
![ErrorinDialog](https://user-images.githubusercontent.com/8522348/176123686-bf501ab2-8f52-4dec-9572-a5413b30e276.gif)

### **Code sample:** 
Where customCardProps lose capability to be selected again after field is changed:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "hideColumnHeader": true,
  "hideSelection": true,
  "rowFormatter": {
    "elmType": "div",
    "style": {
      "cursor": "pointer"
    },
    "children": [
      {
        "elmType": "div",
        "txtContent": "click me",
        "customCardProps": {
          "openOnEvent": "click",
          "beakStyle": {},
          "isBeakVisible": true,
          "directionalHint": "topCenter",
          "formatter": {
            "elmType": "div",
            "children": [
              {
                "elmType": "div",
                "style": {
                  "cursor": "pointer"
                },
                "txtContent": "Click to update",
                "customRowAction": {
                  "action": "setValue",
                  "actionInput": {
                    "Title": "='Value1 to '+ if(Number(@now)%7==0,1,if(Number(@now)%7==1,2,if(Number(@now)%7==2,3,if(Number(@now)%7==3,4,if(Number(@now)%7==4,5,6)))) + ' set'"
                  }
                }
              }
            ]
          }
        }
      },
      {
        "elmType": "div",
        "style": {
          "padding": "0 10px 0 10px"
        },
        "txtContent": "[$Title]"
      }
    ]
  }
}
```

### Steps to reproduce

Scenario have object that call "customCardProps" with object that update field using "customRowAction", after the field text is update and display in the row of View, when try to access object "customCardProps" and click again this cannot be selected again and doesn't display dialog.

### Expected behavior

customCardProps should continue to be available/work after the field is updated in View.

**Comment by aaclage** [comment]
@shagra-ms 
I would like to address you this issue regarding declarative JSON Microsoft List

**Comment by shagra-ms** [comment]
I am able to repro this. Thanks for reporting @aaclage

**Comment by shagra-ms** [comment]
Thanks @aaclage for reporting this. The fix for this is now rolled out.

Please do try and let me know if this still doesn't work for you.

**Comment by aaclage** [comment]
Thank you @shagra-ms for your support on this topic.

Can confirm correction was made.
you are the greatest.
