### ISSUE TITLE
framework not stored when scaffold without parameters

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [SharePoint/sp-dev-docs#8246]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.15.0
- Node.js version 12.19.0
- etc

### Describe the bug / error

When run yeoman scaffold without framework parameter(yo @microsoft/sharepoint) and select when prompted, the config will not be stored in yo-rc.json. In this condition, scaffolding a second webpart will ask again the framework and I can create a webpart with different framework.
But when run yeoman scaffold with framework parameter(e.g yo @microsoft/sharepoint --componentType webpart --component-name firstwebpart --framework none --solutionname hellosolution), the config will be stored in yo-rc.json. In this condition, scaffolding a second webpart will not ask framework and I can not create a webpart with another framework.
I wonder what the expected behavior is.
Similar issue:  https://github.com/SharePoint/sp-dev-docs/issues/2967

### Steps to reproduce

1. Run `yo @microsoft/sharepoint`
2. select 'none' framework
3. Run `yo @microsoft/sharepoint` again and framework is asked and I can choose other frameworks like 'React'
4. Run `yo @microsoft/sharepoint --componentType webpart --component-name firstwebpart --framework none --solutionname hellosolution`
5. Run `yo @microsoft/sharepoint` again and framework is not asked and I can not scaffold webpart with other frameworks.

### Expected behavior

Actually I'm not sure what the expected behavior is. As a developer, I think asking user to select framework each time adding a webpart is more reasonable.

**Comment by AJIXuMuK** [comment]
@HuihuiWu-Microsoft - thank you for bringing up this question.
Yes, it is expected we have a bit different behavior for, let's call it interactive and automation scenarios.
For automation scenario (parameters) we store most of the configuration in the `.yo-rc.json` to simplify future creation/addition to the solution.
For "interactive" scenario we allow more flexibility.
