### ISSUE TITLE
SPFx 1.15 - Webpack 5.x -  webpack setup doesn't support for export * as ns syntax 

### ISSUE THREAD

**Issue by MarkusLanger** [SharePoint/sp-dev-docs#8248]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

browser version: Version 103.0.5060.53
SPFx version: 1.15 GA
Node.js version: 16.15.1
ESLint version: 8.18.0
TypeScript version 4.7.4
Webpack version: 5.73.0

### Describe the bug / error

In my SPFx project I use the package `css-tree`. With SPFx 1.14 it works fine. With SPFx 1.15 GA I get a wepack error. See also https://github.com/csstree/csstree/issues/189

Which webpack plugins/parser are used in SPFx 1.15? 
Where could the problem come from? 

```
[17:28:36] Error - [webpack] 'dist':
./node_modules/css-tree/lib/index.js 8:9
Module parse failed: Unexpected token (8:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { Lexer } from './lexer/Lexer.js';
| export { tokenTypes, tokenNames, TokenStream } from './tokenizer/index.js';
> export * as definitionSyntax from './definition-syntax/index.js';
| export { clone } from './utils/clone.js';
| export * from './utils/names.js';
 @ ./lib/webparts/helloWorld/components/HelloWorld.js 17:0-36 25:18-31 27:8-20 33:20-36
 @ ./lib/webparts/helloWorld/HelloWorldWebPart.js

```

![image](https://user-images.githubusercontent.com/12131918/176609931-10fd8330-4787-459f-8960-b96ce289b9e6.png)

### Steps to reproduce

1. clone repo https://github.com/MarkusLanger/css-tree-webpack-5
3. npm install
4. npm run package:prod

### Expected behavior

A package with a statement `export * as ns` should work with SPFx 1.15.

**Comment by s-KaiNet** [comment]
SPFx 1.15 (and SPFx 1.14 as well) uses webpack 4.44 to bundle sources. I've tried your repro in SPFx 1.14 and had the same error. It seems that something else was applied to your SPFx 1.14 build since on OOB SPFx 1.14 your sample doesn't work with exactly the same issue. 

The problem is in the javascript parser used by webpack, `acorn`, it supports `export * as ns` starting from version [7.2.0](https://github.com/acornjs/acorn/releases/tag/7.2.0), but `webpack@4.x` uses version `acorn@6.x`.

You can fix it by using import from esm build, which already contains compiled javascript, i.e.

```js
import * as csstree from 'css-tree/dist/csstree.esm';
```
In this case, you will lose type intellisense coming from `@types/css-tree`, but you can kind of "restore" it by applying the below trick:

```js
import * as ct from 'css-tree/dist/csstree.esm';
import { CssNode } from 'css-tree'; // this will work, because we import only type here

type CssTree = typeof import('css-tree');
const csstree: CssTree = ct;

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
    public render(): React.ReactElement<IHelloWorldProps> {
      console.log(csstree);
        // parse CSS to AST
        const ast: CssNode = csstree.parse('.example { world: "!" }');
		.....
    }
}

```

**Comment by MarkusLanger** [comment]
@s-KaiNet Thank you for your detailed information. That works for me. In my SPFx 1.14 project are several other modifications (ESLint, newer TypeScript, some other compilerOptions). This configuration seems to make it possible to import in a different way.
