### ISSUE TITLE
SPFX loading the old version, new version only loaded after ctr+f5

### ISSUE THREAD

**Issue by SuleymanA** [SharePoint/sp-dev-docs#8250]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome version: Version 102.0.5005.115
- SPFx version: 1.14
- Node.js version: 14.19.1

### Describe the bug / error

Since a few days updating the solution package doesn't reflect on the sites where the webparts are used. Updating the solution version and updating the solution on site level doesnt help. Hard refresh with ctr+f5 helps to load the new package but only in that cyle. When the page is reloaded the old solution is loaded again. Seems to be related to multiple issues reported earlier this year like: https://github.com/SharePoint/sp-dev-docs/issues/7664 

### Steps to reproduce

1. Create a SPFX webpart solutoin and publish it in the tenant app catalog
2. Add the webpart to a site
3. Update the webpart visually, solution version and publish again in tenant app catalog
4. Webpart is still showing the old version

### Expected behavior

Expect it to load the new version of the webpart.

**Comment by AJIXuMuK** [comment]
@SuleymanA - thanks for reporting the issue.
If you add `?sw=bypass` to the url - does it solve the issue?
