### ISSUE TITLE
SharePoint Template Design has limited actions

### ISSUE THREAD

**Issue by dietrichmeyer** [SharePoint/sp-dev-docs#8252]
[Enter feedback here]
Regarding the sentence on the page:  For a complete list of available actions and their parameters, see the [JSON schema](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema).

This sentence refers you the schema document which has all sorts of JSON actions specified in JSON, like creating tabs and add documents, but they really don't work yet.  Another document shows the rather limited actions that really work.  

This document should be very clear that JSON actions are limited right now.  I assume the JSON schema is more of a future direction document.

It used to be easily to create a site template.  Now you have to hand write lines and lines of JSON.  Is there an easier way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site template and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
Could you clarify which actions in the [JSON schema](https://developer.microsoft.com/json-schemas/sp/site-design-script-actions.schema.json) do not work?

All of these actions should work and I've never encountered an action listed in the schema not working.

You could investigate using [PnP provisioning](https://docs.microsoft.com/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine) but this is usually for more complex provisioning scenarios.
