### ISSUE TITLE
not able to install gulp

### ISSUE THREAD

**Issue by sadanand96** [SharePoint/sp-dev-docs#8253]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Getting below error when I am trying to install gulp. My node version is 14.19.1
PS C:\users\H6P> npm install gulp-cli --location=global
npm WARN saveError ENOENT: no such file or directory, open 'C:\users\H6P\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\users\H6P\package.json'
npm WARN H6P No description
npm WARN H6P No repository field.
npm WARN H6P No README data
npm WARN H6P No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@rushstack\typings-generator\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ gulp-cli@2.3.0
updated 1 package and audited 2907 packages in 31.696s

139 packages are looking for funding
  run `npm fund` for details

found 65 vulnerabilities (13 low, 22 moderate, 30 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by AJIXuMuK** [comment]
@sadanand96 - I'm not sure if `--location=global` works correctly with node v14.
I would recommend using `npm i -g`.

Closing this issue as it's not something we as a product team can fix.
