### ISSUE TITLE
Why does the Kql research give me the numerical values multiplied by 1000?

### ISSUE THREAD

**Issue by FranBor** [SharePoint/sp-dev-docs#8255]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 103.0.5060.53 (Build ufficiale) (a 64 bit)
- Microsoft.SharePointOnline.CSOM: 16.1.21213.12000

### Describe the bug / error

I have a Number column with the internal name IdDocSet.
On the managed properties page I edited the property RefinableDecimal01 with alias IdDocSet and mapping ows_IdDocSet.

[![enter image description here][1]][1]

Below is the piece of code I use for research

```
KeywordQuery keywordQuery = new KeywordQuery(context);
keywordQuery.QueryText = "path:https://{MyDocumentLibraryUrl} AND (ContentTypeId:0x0120D520* OR ContentTypeId:0x0101*)";

keywordQuery.CollapseSpecification = "IdDocSet";

keywordQuery.SelectProperties.Add("IdDocSet");

keywordQuery.SortList.Add("IdDocSet", SortDirection.Descending);

SearchExecutor searchExec = new SearchExecutor(context);
ClientResult<ResultTableCollection> resultTableColl = searchExec.ExecuteQuery(keywordQuery);
context.ExecuteQueryRetry();
```
I get the `ClientContext` with Azure app registration and the code below:

```
OfficeDevPnP.Core.AuthenticationManager().
                GetAzureADAppOnlyAuthenticatedContext(siteUrl, azApplicationId, azTenant, certificatePfxPath, certificatePassword);
```

When I run the code I get the truly value of IdDocSet multiplied by 1000

[![enter image description here][2]][2]

I need to use the alias in my code, please help me.

  [1]: https://i.stack.imgur.com/OeOWV.png
  [2]: https://i.stack.imgur.com/1tjfa.png

### Steps to reproduce

1. Create a SharePoint document library with a "IdDocSet" numeric column
2. On the managed properties page modify the property RefinableDecimal01 with alias IdDocSet and mapping ows_IdDocSet.
3. Create a new Azure App registration:
> - add a certificate
> - add the permission SharePoint Sites.FullControl.All

4. Run the described code

### Expected behavior

KQL search return  the truly value of IdDocSet multiplied by 1000

**Comment by wobba** [comment]
This seems to work as expected for me. Can you say something about how the number column in SP has been defined? I have number with auto decimals for my test, and all numbers come correct.

**Comment by wobba** [comment]
Fixed from the service side.
