### ISSUE TITLE
🙏 SPFx v1.15 - Please suppress unnecessary ESLint no-async-await rule

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8260]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: n/a
- SPFx version: v1.15
- Node.js version: v16

### Issue description

With the switch to ESLint, seems we're getting a LOT of new listing rules applied. One is entirely unnecessary: **@microsoft/spfx/no-async-await**.

This rule, defined in the **[@microsoft/eslint-plugin-spfx](https://www.npmjs.com/package/@microsoft/eslint-plugin-spfx)** package, throws a build warning if it finds the `async` keyword in the code, either in a method declaration or in an anon function declaration.

The rule states _Usage of "async" has overhead when using in older browsers._

**This is 100% unnecessary** because of the following reasons:

- We're writing TypeScript for SPFx projects. 
- The default config for the TSC is to generate ES5.
- The `async` & `await` keywords don't exist in ES5.
- The TSC transpiles these keywords down to the equivalent ES5 code
- Therefore `async` & `await` never exist in the resulting bundle
- If the keywords aren't in the bundle, they never get deployed, never get loaded, and thus **never touch the browser**.

**Therefore this rule is moot and is just misguiding developers to not use two very keywords for no good reason, under the guise of a 'best practice'.** 

To block this rule today, disable it in the **./.eslintrc.js** file like so:

```js
require('@rushstack/eslint-config/patch/modern-module-resolution');
module.exports = {
  extends: ['@microsoft/eslint-config-spfx/lib/profiles/default'],
  parserOptions: { tsconfigRootDir: __dirname },
  rules: {
    "@microsoft/spfx/no-async-await": "off"
  }
};
```

But, IMHO, this rule should be removed from the **@microsoft/eslint-plugin-spfx** package.

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
