### ISSUE TITLE
🐞 SPFx v1.15 - gulp clean doesn't remove the 'releases' folder

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8263]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.15
- Node.js v16

### Describe the bug / error

The task **gulp clean** removes all temp folders generated by a built, except the **releases** folder. The **releases** folder is missing in the configuration for the task within the **@microsoft/gulp-core-build** package, specifically in the task's file **./@microsoft/gulp-core-build/lib/tasks/CleanTask.js** ,lines 27 & 28:

```js
const { distFolder, libFolder, libAMDFolder, tempFolder } = this.buildConfig;
let cleanPaths = [distFolder, libFolder, tempFolder];
```

If the task **clean** is supposed to clean up files that shouldn't committed to source control, the **releases** folder should also be removed.

### Steps to reproduce

1. Create SPFx project with any type of component
1. Wait for **npm install** to complete
1. Build project once: **gulp build**
1. Clean project: **gulp clean**
1. Observe **releases** still present

### Expected behavior

Releases isn't present after running **gulp clean**

**Comment by AJIXuMuK** [comment]
Thanks @andrewconnell for reporting this one.
The fix has been done and will be included in the next release.

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
