### ISSUE TITLE
SPFx 1.15 - Form Customiser does not work in View History

### ISSUE THREAD

**Issue by ethanli83** [SharePoint/sp-dev-docs#8266]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

After I update the ContentType.DisplayFormClientSideComponentId and try to view an item in Version History, I got following error: 

"Sorry, something went wrong."
 
If I empty ContentType.DisplayFormClientSideComponentId, then the error goes away.

### Steps to reproduce

1. Create a Form customiser extension and deploy to a SharePoint site.
2. Create a new list.
3. Create a new item on the list.
4. Update the DisplayFormClientSideComponentId of the Item content type to the component id of the Form customiser component.
5. Open the Version History page by right click on the item then click on "Version  history"
6. Click on a version of the item.

### Expected behavior

The  Form customiser is displayed.

**Comment by AJIXuMuK** [comment]
Should be rolled out WW by now
