### ISSUE TITLE
SPFx v1.15 - Error when running Form Customizer solution with a specific configuration

### ISSUE THREAD

**Issue by yhabersaat** [SharePoint/sp-dev-docs#8267]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Windows 11
- Microsoft Edge 103.0.1264.44
- SPFx 1.15.0
- Node 14.18.1

### Describe the bug / error

I'm getting the error below when I'm running a Form Customizer solution with a specific configuration:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/15676985/177131237-102cc233-92db-4b4c-9239-4eefab252ec6.png">

Followed this documentation reference:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-form-customizer

### Steps to reproduce

1. Generate a brand new Form Customizer solution with the Yeoman generator for the SharePoint Framework.
2. Run gulp serve --config=basics_EditForm (change the configuration name).

### Expected behavior

Running this command should display the edit form for the item specified in the ID property.

**Comment by AJIXuMuK** [comment]
@yhabersaat - thank you for reporting this issue.
Just checking - do you have the item with this `ID` in the list?

I've tested the behavior and it works correctly if you have the item in the list.
And it correctly shows the error if there is no item.

**Comment by yhabersaat** [comment]
Hi @AJIXuMuK, my bad thank you for pointing the mistake. I confirm that everything is working as expected now! Sorry :-)
