### ISSUE TITLE
Office-ui-fabric-react version with drop 1.2

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#827]
#### Category
- [x] Question

The [SPFx docs](https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/office-ui-fabric-integration) says to take an explicit dependency on office-ui-fabric-react v2.x. Drop v1.2 comes with v4.32.0 after running the yeoman generator.

Does that mean for drop v1.2 we should take a dependency on v4.x?

**Comment by wobba** [comment]
Also, if you take a dependency on 2.x with drop 1.2, it won't build.

**Comment by DennisKuhn** [comment]
I think the docs are behind. Drop v1.2 works fine for me with office-ui-react 4.32. As it is the new package version, I would update my dependencies to that. I updated my project with `npm` and it went sweet. I created a new "HelloWorld" with `yo @microsoft/sharepoint` to compare dependencies and stuff.

**Comment by wobba** [comment]
I can make it work as well, but it's important to keep docs up to date with drops, especially when static linking is recommended together with adding an explicit version of UI fabric. Ideally I would like the old way, where I didn't have to bundle in UI fabric as it was pre-loaded with SPFx.

**Comment by mcmynn83** [comment]
@VesaJuvonen

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
