### ISSUE TITLE
SPFx 1.15 - Getting error when use form customiser to view existing list item in Classic mode

### ISSUE THREAD

**Issue by ethanli83** [SharePoint/sp-dev-docs#8272]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I'm getting an error below when I'm try to view an existing list item with form customiser in Classic mode.

![image](https://user-images.githubusercontent.com/4969207/177255255-0e88e857-e10d-44a4-87f6-94085167b6d9.png)

### Steps to reproduce

1. Create a Form customiser extension and deploy to a SharePoint site.
2. Create a new list.
3. Create a new item on the list.
4. Update the DisplayFormClientSideComponentId of the Item content type to the component id of the Form customiser component.
5. Switch to Classic mode.
6. Click on the item.

### Expected behavior

The form customiser shows up correctly

**Comment by ethanli83** [comment]
> @ethanli83 @AJIXuMuK
> 
> How do we do the following step? is it possible via PowerShell?
> 
> 1. Update the DisplayFormClientSideComponentId of the a content type to the component id of the Form customiser component.

I did it by a C# programming using CSOM, but  I think you can archive this by PowerShell. 

All you need to do is to update the ContentType.

**Comment by ejazhussain** [comment]
Thanks, @ethanli83 I have ended up writing similar code to update components Ids.

**Comment by AJIXuMuK** [comment]
@ethanli83 - the fix has been merged and will be rolled out WW in the next couple of weeks.

**Comment by ethanli83** [comment]
> @ethanli83 - the fix has been merged and will be rolled out WW in the next couple of weeks.

Thank you very much~

**Comment by AJIXuMuK** [comment]
Should be rolled out WW by now

**Comment by ethanli83** [comment]
hi @AJIXuMuK , what do you mean by `WW`? thanks.
