### ISSUE TITLE
InlineEditing doesn't work in Board View - opens right side Form

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#8274]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I don't know if was a change of architecture/support but **inlineEditField** is not allow to be used in Views "Board" as show below.

Image steps:
Where **inlineEditField** stopped working and opens dialog Form.
![InlineEditingDoesntwork](https://user-images.githubusercontent.com/8522348/177292617-ec49d7d7-7fbc-4fd9-bff0-5c5d501e8045.gif)

Sample code:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/board-formatting.schema.json",
  "hideSelection": false,
  "formatter": {
    "elmType": "div",
    "attributes": {
      "class": "sp-card-container sp-card-container-noPadding"
    },
    "children": [
      {
        "elmType": "div",
        "attributes": {
          "class": "ms-bgColor-white sp-css-borderColor-neutralLight sp-card-borderHighlight sp-card-subContainer sp-card-subContainer-borderRadius"
        },
        "children": [
          {
            "elmType": "div",
            "children": [
              {
                "elmType": "p",
                "attributes": {
                  "title": "[$Title]",
                  "class": "ms-fontColor-neutralPrimary sp-card-content sp-card-highlightedContent",
                  "role": "heading",
                  "aria-level": "3"
                },
                "inlineEditField": "[$Title]",
                "txtContent": "=if ([$Title] == '', '–', [$Title])"
              }
            ],
            "attributes": {
              "class": "sp-card-displayColumnContainer"
            }
          }
        ]
      }
    ]
  }
```

### Steps to reproduce

1. Create a Board View with Title field
2. Add formatted provided by sample
3. Click on Title to edit content

### Expected behavior

Users should be able to edit fields with **inlineEditField** formatting as documented.
[https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#inlineeditfield)

**Comment by aaclage** [comment]
@shagra-ms 
I would like to address you this issue regarding declarative JSON Microsoft List.

I don't know if was a change of architecture/support on inlineEditField using Board View.

**Comment by shagra-ms** [comment]
Thanks for reporting this @aaclage. We have a confirmed repro of this with us.
Will update when we have a fix for this rolling out.

**Comment by aaclage** [comment]
@shagra-ms Thank you for your support and sorry for finding issues... :P

**Comment by jphepp3** [comment]
I am experiencing the same issue.  Additionally, if I use a setValue action embedded into a customCardProp then the card will no longer refresh in real-time to show the change made by the setValue action.  For example, if I put a setValue action in a customCardProp to "Minimize Card" or "Maximize Card" when I push the setValue button, the item updates on the list but the card does not refresh in real time.  I can only see the change (e.g. maximized card or minimized card) by refreshing the page, moving the card to a new column, or by right clicking on the card.  Additionally, the "fly out menu" created by the customCardProp will no longer be available until the card is refreshed.
