### ISSUE TITLE
Solution with New Extension Added - Tenant Wide Extensions List Entry Not Added

### ISSUE THREAD

**Issue by anthonywhite** [SharePoint/sp-dev-docs#8275]
Scenario
An SPFx solution with one `ListViewCommandSet` extension is deployed to tenant app catalog. Two `ClientSideComponentInstance` entries are in the `ClientSideInstance.xml` file. Two corresponding entries appear in Tenant Wide Extensions List.

An update is made to the solution that adds another `ListViewCommandSet` extension and a single `ClientSideInstance.xml` entry. The `package-solution.xml` version is incremented. The new version is built and deployed by dragging and dropping over the previous version in the app catalog. **However no new entry appears in the Tenant Wide Extensions List for the new extension**.

Adding the TWE entry manually enables the new extension ok. Deleting the app from the catalog correctly removes all the TWE entries. Adding the solution back in after deleting correctly creates all the TWE entries.

The problem just seems to be with (not) processing an update to `ClientSideInstance.xml` file?

**Comment by AJIXuMuK** [comment]
Thanks @anthonywhite for bringing this up.
We're working on a fix to allow adding new extensions to the `ClientSideInstance.xml`.
To be clear, it will cover the scenario when you add new component in your solution and want to add this component registration to `ClientSideInstance.xml`.
If you want to modify existing entries, or add new registration for existing component, it will not work.

**Comment by anthonywhite** [comment]
Thanks @AJIXuMuK, I guess more complex scenarios such as you mention can be handled manually 👍

**Comment by AJIXuMuK** [comment]
@anthonywhite - the roll out should be finished by today.
