### ISSUE TITLE
New icons in production environments

### ISSUE THREAD

**Issue by Rafaelki** [SharePoint/sp-dev-docs#8279]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.14.1, 1.15

### Describe the bug / error

It seems that SharePoint is changing its icons from [Fluent UI](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#available-icons) to [segoe-fluent-icons-font](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font) overnight, or maybe I missed the announcement?

Our product uses SPFx and has been using icons from Fluent UI in production environments for a while now and suddenly these icons have changed. We are having many complaints from clients as this was unexpected. We didn't have the time to test the new icons and of course, there are many problems like StockDown and StockUp which seem to be the other way around. We use them in production environments to indicate the direction of the stock so imagine how confusing and frustrating this is.

![image](https://user-images.githubusercontent.com/24438807/177753726-deea60be-ca79-41fb-8fa4-dde8381cc6fb.png)

![image](https://user-images.githubusercontent.com/24438807/177753789-57e878d3-c880-4a75-b71b-f2558bdb61de.png)

### Steps to reproduce

Go to https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font and find StockDown and StockUp

- [ ] 

### Expected behavior

StockDown should point down
StockUp should point up

We expect more information on changes that are drastically changing the look and feel of SharePoint.

**Comment by dev-a11y** [comment]
This requires higher attention, our users are frustrated as well (we have same use case for these 2 icons).

We observed that on SPFx webpart instantiated on classic site collections we have old (correct) icons.
Seems like redesign happened on modern sites only, it is not visible on [Fluent UI Icons](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons) page either.
Do we have any control on which version of icons is used in our SPFx components?

A side note: we see our users focusing too much on 'Group' icon (based on comments they perceive it as below, it seems frustrating and annoying for most, on the left previous version):
![image](https://user-images.githubusercontent.com/59690753/178283000-2907a41b-c85b-4e50-876a-d0f3369621e0.png)

This may break the principle that interface elements should not receive more attention than is necessary for functional purposes.

**Comment by AJIXuMuK** [comment]
@Rafaelki - thank you for reporting this one.
It is definitely messed up on our side of the house.
We will be updating the font to fix that issue.
I would expect hotfix in the next couple of days.

**Comment by Rafaelki** [comment]
Thank you very much @AJIXuMuK 
Is there an estimated date we can tell our clients? My team needs to evaluate if it is worth creating a patch in our product (the share prices have high visibility in our product - it is in an app customizer at the top)

**Comment by AJIXuMuK** [comment]
@Rafaelki - the fix is merged and usually it takes around 2 weeks to roll out WW.

**Comment by Rafaelki** [comment]
Thank you @AJIXuMuK I can see the correct icons in my dev environment now and hopefully very soon in our client environments. Closing the issue.
