### ISSUE TITLE
Yeoman SharePoint Generator has different questions

### ISSUE THREAD

**Issue by StefH** [SharePoint/sp-dev-docs#8286]
The documentation describes:
- **What is your solution name?:** command-extension
- **Which baseline packages do you want to target for your component(s)?** SharePoint Online only (latest)
- **Which type of client-side component to create?:** Extension
- **Which type of client-side extension to create?** ListView Command Set
- **What is your Command Set name?** HelloWorld
- **What is your Command Set description?** HelloWorld description

But the questions asked are now (2022-08-07 with latest `@microsoft/sharepoint`) less:
- **What is your solution name?** command-extension
- **Which type of client-side component to create?** Extension
- **Which type of client-side extension to create?** ListView Command Set
- **What is your Command Set name?** HelloWorld

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
See: https://docs.microsoft.com/sharepoint/dev/spfx/yeoman-generator-for-spfx-intro#retired-generator-prompts
