### ISSUE TITLE
SPFx 1.15 listview extension issue

### ISSUE THREAD

**Issue by pothitos-baikas** [SharePoint/sp-dev-docs#8298]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version latest
- SPFx version 1.15
- Node.js version v16.16.0
- etc

### Describe the bug / error

Just tried to create a listview extension (commandset) and found out that the visibility of the button does not work as it used to (e.g. in 1.14). I do not believe that the substitution of the event (from 

onListViewUpdated to listViewStateChangedEvent) is to blame, instead it gives me the impression that the .visible property of the command, does not work in 1.15
 
No need to post a sample code: One may try it with the code that results from the scuffolding - simply run it, and experiment by selecting and de-selecting a document in a document library. The visibility state of the "COMMAND_1" is not normal
 
Anyone who has experienced this issue?

### Steps to reproduce

1. Create a new application customiser (commandset)
2. run "gulp serve"
3. select and de-select documents and watch the visibility of COMMAND_1

The behaviour is not consistent- the button on the ribbon, appears with 0 selected items and hides with a document selected

### Expected behavior

COMMAND_1 should be visible ONLY if one decument is selected

**Comment by andrewconnell** [comment]
Noticed the same thing... I found you need to tell SPFx that the view should be refreshed if you make changes to your buttons: `this.raiseOnChange();`

This is what I put in my course:

```ts
private _onListViewStateChanged = (args: ListViewStateChangedEventArgs): void => {

  // only update visibility of the selected rows changed
  if (args.stateChanges !== ListViewAccessorStateChanges.SelectedRows) {
    return;
  }

  // if exactly one / two items selected, show correct button
  const oneItemSelected: Command = this.tryGetCommand('ONE_ITEM_SELECTED');
  oneItemSelected.visible = this.context.listView.selectedRows!.length === 1;

  const twoItemSelected: Command = this.tryGetCommand('TWO_ITEM_SELECTED');
  twoItemSelected.visible = this.context.listView.selectedRows!.length > 1;

  // update command bars
  this.raiseOnChange();
}
```

**Comment by AJIXuMuK** [comment]
@andrewconnell is correct. To apply the changes right away you need to call `this.raiseOnChange()`.
Without this call the changes will be applied when the list will be repainted based on internal logic and user interactions.

We will uncomment this call by default to avoid confusion.

**Comment by acreff** [comment]
Thank you both. May I suggest that the scuffolding (in future versions) adds this code - inexperienced users (like me !!!) are expecting that the code produced should work without intevening manually.

Thanks again, I will give it a try and let you know

**Comment by andrewconnell** [comment]
> May I suggest that the scuffolding (in future versions) adds this code - inexperienced users (like me !!!) are expecting that the code produced should work without intevening manually.

It isn't just inexperienced users @acreff... seasoned ones too! 🤪

I've been using SPFx since before it was GA in 2017 and it stumped me when I was upgrading all the sample projects in my course two weeks ago. It's not an obvious behavior change from prior versions of SPFx.
