### ISSUE TITLE
Not able to deploy .spapp file to app catalog

### ISSUE THREAD

**Issue by rakheejain** [SharePoint/sp-dev-docs#83]
I'm able to run the webpart using SharePoint Workbench but when I try to deploy the .spapp file in App Catalog, the file is getting uploaded in the "Apps for SharePoint" library with no "Product ID". It is specified that the app package in "not valid". Please see the attached screenshot.

![new bitmap image](https://cloud.githubusercontent.com/assets/20062769/17996182/cd52b124-6b84-11e6-8651-e3123cc2f9e7.jpg)

**Comment by NikCharlebois** [comment]
I am getting the exact same behavior on my end. Not sure if my tenant is missing something or what.

**Comment by NikCharlebois** [comment]
@rakheejain can you confirm that you have registered for a Dev TENANT?

**Comment by NikCharlebois** [comment]
If you try with a Dev Tenant it works. Even if your normal tenant is on First Release it will not work. Need a Dev one absolutely

**Comment by patmill** [comment]
As an aside, we'll relax this requirement over time, but we think there will be a high rate of churn in the short term and we don't want your normal tenancy to wind up having strange after-effects.

**Comment by JasonDunbar** [comment]
Any way of speeding up being able to turn this on in our existing tenants instead of paying $100 USD or so for a developer tenant?

**Comment by ciphertxt** [comment]
You can sign up for a free one year developer subscription at [http://dev.office.com/devprogram](http://dev.office.com/devprogram).

**Comment by JasonDunbar** [comment]
That assumes you didn't already use up your one year tenant ;-)

**Comment by rakheejain** [comment]
@NikCharlebois 
Thanks for the quick reply.

Yeah I was trying to deploy .spapp file on first release tenant. I have now signed up for developer tenant and deployed this file and the deployment was successful

**Comment by suz7777** [comment]
Is it possible to activate on a first release tenant?
Suz
