### ISSUE TITLE
SPFx 1.15 Form Customizer not showing custom forms

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#8300]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser Version 103.0.1264.49 (Offizielles Build) (64-Bit)
- SPFx version 1.15.0
- Node.js version 14.15.0

### Describe the bug / error

The custom forms will not open. Still the default forms are associated to the list content type.
With PnP-Version 1.11.0, I can verify the settings:

![FCProps](https://user-images.githubusercontent.com/22025808/179032385-a3d9a003-89d3-43b1-b0a3-03925fa4e344.png)

They are OK, but still my custom forms are not showing up.

See also following [discussion](https://sharepoint.stackexchange.com/questions/302734/spfx-form-customizer-deployment)

### Steps to reproduce

1. Create a custom list, allow content types
2. Add Site Columns and a site content type
3. Attach site columns to the site content type
4. Attach the site content type to the list
5. Create a Form Customizer
6. Deploy the Extension to the app catalog of a specific site
7. Add the app
8. Associate the Component to the list content type, e.g. with PowerShell

`Import-Module PnP.PowerShell
$siteURL="https://contoso.sharepoint.com/sites/xxx"
Connect-PnPOnline -Url $siteURL -Interactive
$ContentTypeName="ZZZ"
$CTypes = Get-PnPContentType -List "List2"
foreach($contentType in $CTypes)
{
    if($contentType.Name -eq $ContentTypeName)
    {
        $contentType.DisplayFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
        $contentType.NewFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
        $contentType.EditFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
        $contentType.Update($false)
    }
}`

If you have configured "webApiPermissionRequests" in package-solution.json like this:

`"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "GroupMember.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },     
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      }
    ]`

Approve the API-Access at SharePoint-Admin-Site.
Navigate to the list, hit "New".
The default forms will open.

### Expected behavior

The custom forms should open.

**Comment by AJIXuMuK** [comment]
@EA12 - are you opening the forms from classic or modern mode?
if from the modern, under "default forms" you mean side panel is opened?

**Comment by EA12** [comment]
Yes, modern page and side panel

**Comment by EA12** [comment]
**New Finding:** I just noticed, that the values of the properties are not persisted.
I started a new PowerShell and determined the properties. They are all empty.
So it seems that PnP.PowerShell is not saving the properties. I will check the code and come back.

**Comment by EA12** [comment]
Microsoft.SharePoint.Client.dll
From class ContentType:

```
public string EditFormClientSideComponentId
{
	get
	{
		CheckUninitializedProperty("EditFormClientSideComponentId");
		return (string)base.ObjectData.Properties["EditFormClientSideComponentId"];
	}
	set
	{
		base.ObjectData.Properties["EditFormClientSideComponentId"] = value;
		if (base.Context != null)
		{
			base.Context.AddQuery(new ClientActionSetProperty(this, "EditFormClientSideComponentId", value));
		}
	}
}```


So, if the content type object has no context, the setting will not be persisted, but can be determined from the get method.
That is what I see.

So, my PowerShell code is partly wrong, or is may be PnP.PowerShell missing something (context?)?

$CTypes = Get-PnPContentType -List "List2"

foreach($contentType in $CTypes)
{
	if($contentType.Name -eq $ContentTypeName)
	{
		$contentType.DisplayFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
        $contentType.NewFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
        $contentType.EditFormClientSideComponentId = "50ebd4b2-04f4-42fb-af43-953e226179f0";
		$contentType.Update($false)
	}
}

**Comment by EA12** [comment]
I also asked the [PnP.Powershell Community](https://github.com/pnp/powershell/discussions/2158)
