### ISSUE TITLE
Error When Revisiting Custom Teams ?app=portals App

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#8301]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

browser version Teams desktop App
SPFx version 1.13
Node.js version V 12.13

### Describe the bug / error

When revisiting the custom personal app that is registered with `?app=portals` it opens a browser with incorrect url:
`_layouts/15/undefined&inPlaceNav=portals`

This issue is based on this comment: https://github.com/SharePoint/sp-dev-docs/issues/8191#issuecomment-1184108605

### Steps to reproduce

You have a custom spfx teams app , you click on the app and it's loads fine
![image](https://user-images.githubusercontent.com/17036219/179042826-efb02152-3434-40f3-8dd7-a7391eb8792c.png)

Later you click in any option in the menu like calendar , teams chat

![image](https://user-images.githubusercontent.com/17036219/179042864-d38603fd-cffa-40c6-949d-599d90c42e8e.png)
You click in teams app again and then it show up white screen

![image](https://user-images.githubusercontent.com/17036219/179042922-09e42294-5a2d-486c-8ed6-9aee3da974c9.png)

### Expected behavior

The app is opened normally.

**Comment by Rtoribiog** [comment]
hello @AJIXuMuK, do you think will be fixed in the next release?  do you know where will be the next teams release? Thanks

**Comment by AJIXuMuK** [comment]
@Rtoribiog - it has been merged and will be rolled out in the next couple of weeks.

**Comment by Rtoribiog** [comment]
thanks @AJIXuMuK  for the comments

**Comment by AJIXuMuK** [comment]
This should be rolled out WW by now.

**Comment by Rtoribiog** [comment]
Now it works as expected.  Thanks for addressing it @AJIXuMuK
