### ISSUE TITLE
SPFX apps on subsites

### ISSUE THREAD

**Issue by PowellT** [SharePoint/sp-dev-docs#8302]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx 1.12  but other versionjs 1.4.x  also giving same issue
~~Tried both app installed in tenant app catalog AND tried seperately with an app installed in a site collection~~
**Correction, this only seems to happen with apps in a site collection app catalog

### Issue description

if I have an app installed on a site, and then try to install the app on a subsite, I get
"A different version of this App is already installed with the same version number. You need to delete the app from the site and the site recycle bin to install this version."
~~*doesnt matter if app is in tenant app catalog or in a site collection app catalog~~
**Correction, this only seems to happen with apps in a site collection app catalog

I have seen mention of this ref https://github.com/SharePoint/sp-dev-docs/issues/580
But no real resolution. Besides "delete the app, Up the package version and redeploy"

Am I correct in saying that the version of an app can never be the same between top level site and subsite?

Sure sounds like it.  Which would be mental from a maintenance perspective.

Has anyone else figured out a way out of this site/subsite spfx app version hole?

**Comment by AJIXuMuK** [comment]
@PowellT - could you please share your solution with me? You can send it to aterentiev@microsoft.com.
I just tested the default scaffolded solution (web part) and able to add it separately to root site and sub site (the solution is added to site collection app catalog).

**Comment by CallumCrowley** [comment]
@PowellT Isn't the SPFx app installed on all subsites in the site collection when you install it at top level site?
