### ISSUE TITLE
🐞SPFx - Update serve.json's schema to include `serveConfigurations` for IntelliSense

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8309]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

All SPFx projects, but mostly an issue with SPFx extensions

### Describe the bug / error

The schema for **./config/serve.json**, `https://developer.microsoft.com/json-schemas/core-build/serve.schema.json`, is missing the section `serveConfigurations`.

This means developers won't get IntelliSense with included docs when editing this file. Can be resolved by fixed by updating the schema to include & doc up all the options for `serveConfigurations`.

![Screen Shot 2022-07-15 at 8 04 44 AM](https://user-images.githubusercontent.com/2068657/179219596-d05f88b5-89a9-412d-a219-1256200ba1f9.png)

### Steps to reproduce

1. Create new project
1. Use any type of component when prompted
1. Open said project in VSCode
1. Open **./config/serve.json**
1. Move mouse over `serveConfigurations` property and observe tooltip warning "Property serveConfigurations is not allowed"
1. Developer curses at VSCode and 😭 in solitude... kittens rush for safety to avoid being kicked by said developer

### Expected behavior

1. Create new project
1. Use any type of component when prompted
1. Open said project in VSCode
1. Open **./config/serve.json**
1. Observe IntelliSense when modifying values under the included `serveConfigurations`
1. The Microsoft engineer who took the time to update this file, on their way home from work to enjoy a good streaming movie, when picking up their take-out tacos 🌮, comes to find out someone paid it forward as thanks and now they enjoy free 🌮 for their contribution to developers across the globe.

**Comment by AJIXuMuK** [comment]
Thanks @andrewconnell - this will be fixed in the next release

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
