### ISSUE TITLE
Not clear if this is supported in all version or startign from a specific one.

### ISSUE THREAD

**Issue by AtefBellaaj** [SharePoint/sp-dev-docs#8313]
It is not specified if this applies to all spfx versions or not. Will this work on Sharepoint Servers (spfx 1.4.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0478b851-e0d2-0a30-3afa-34ca66bcb60b
* Version Independent ID: abc88d15-32c6-f019-1613-9c67630941d9
* Content: [Integrate web part properties with SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint)
* Content Source: [docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@AtefBellaaj - yes, properties lifecycle and metadata are the same for all versions of SPFx.
