### ISSUE TITLE
🐞 SPFx v1.15 Form customizer React template contains incorrect reference

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8314]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Node v16
- SPFx v1.15

### Describe the bug / error

Code comment for the interface declaration in a new SPFx React-based form customizer contains a reference to **field** customizer when should be **form** customizer.

This is only present in the React template... other templates are correct.

```ts
/**
 * If your field customizer uses the ClientSideComponentProperties JSON input,
 * it will be deserialized into the BaseExtension.properties object.
 * You can define an interface to describe it.
 */
export interface IHelloWorldFormCustomizerProperties {
...
```

### Steps to reproduce

1. Create project with **yo @Microsoft/sharepoint**
2. Select **Extention** as component type
3. Select **form customizer**
4. After project created, observe comment immediately preceding interface in main code file **./src/extensions/\*\*/\*FormCustomizer.ts**

### Expected behavior

Comment without typo

**Comment by AJIXuMuK** [comment]
Thanks @andrewconnell - this will be fixed in the next release.

**Comment by AJIXuMuK** [comment]
1.15.2 is out - this should be fixed
