### ISSUE TITLE
🐞SPFx v1.15 (regression #1690) - SPFx Web Part Manifest Points to 404 of Office UI Fabric Icons

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8315]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Regression of #1690...

The schema file for web part manifests **https://developer.microsoft.com/json-schemas/spfx/client-side-extension-manifest.schema.json** has reverted back to use an incorrect URL for the web part icon. Currently points to **http://o365icons.cloudapp.net/** when should point to **https://developer.microsoft.com/en-us/fabric#/styles/icons**

![Screen Shot 2022-07-18 at 5 53 45 AM](https://user-images.githubusercontent.com/2068657/179488314-25c17175-5d5e-4674-aa56-2ac2910fc8a7.png)

### Steps to reproduce

1. Create web part project with **yo @Microsoft/teams**
2. Open web part manifest
3. Observe IntelliSense tooltip points to invalidURL

### Expected behavior

The URL http://o365icons.cloudapp.net referenced on line 179 of the [client-side-web-part-manifest.schema.json](https://dev.office.com/json-schemas/spfx/client-side-web-part-manifest.schema.json) should point to: https://developer.microsoft.com/en-us/fabric#/styles/icons

**Comment by AJIXuMuK** [comment]
1.15.2 is out. This should be fixed
