### ISSUE TITLE
Partner Center app upgrade does not success, when a Legacy .APP file is upgraded using .SPPKG app

### ISSUE THREAD

**Issue by murtuzamj** [SharePoint/sp-dev-docs#8316]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Partner Center app submission

### Issue description

This is in the partner center,

I have a Legacy APP that is running fine with .app model.

Since everything is moving to SPFx we created a similar functionality SPFx app, with the Same APP ID
The partner center submission fails to recognize the update.
The app gets approved with the older .app package instead of the .SPPKG package

**Comment by AJIXuMuK** [comment]
@murtuzamj - I don't believe such a scenario is supported.
SPFx and Add in are 2 different apps.
So, I assume you will need to create a separate app registration for that and in your add-in just provide some notice for the customers to install new SPFx app.
