### ISSUE TITLE
🐞 SPFx schema - web part group names in manifest schema don't match SPO UX

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8320]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

n/a

### Describe the bug / error

The labels for web part categories/groups listed in the web part manifest schema (ref: https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json) no longer match what's in SPO... seems SPO changed?

The new group names aren't entirely obvious what they map to for the old names... so would be good to get the schema updated to reference the current & previous names. Or... update the schema to the current SPO names and I'll update the docs to indicate "SPO" and "on-prem/previous" group names.

### Steps to reproduce

Compare schema (https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json) to what's in SPO UX... they don't match.

### Expected behavior

Compare schema (https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json) to what's in SPO UX... they should match.

**Comment by AJIXuMuK** [comment]
The schema has been updated
