### ISSUE TITLE
SPFx localisation files not loading correctly for certain users

### ISSUE THREAD

**Issue by somethingly** [SharePoint/sp-dev-docs#8332]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.14.0
- Chrome 103

### Issue description

We have created some SPFx web parts and created localisation files for a number of languages, including French France (FR-FR | 1036) and French Canadian (FR-CA | 3084).

When we go to test this with a user who's language settings have been set to French (Canada), it appears to be loading the fr-fr file rather than the FR-CA:

![image](https://user-images.githubusercontent.com/5204930/180476458-c758acac-10d4-47ba-80ef-4c18bfff2ca3.png)

The fr-ca files have been published by the app:

![image](https://user-images.githubusercontent.com/5204930/180475542-9c3fc4b8-d430-491c-9ba6-f1bb44c68a04.png)

But the browser is requesting the FR-FR files: 

![image](https://user-images.githubusercontent.com/5204930/180476017-49424e22-5a2d-4b5c-9072-3795956ad561.png)

Within the _spPageContextInfo:

![image](https://user-images.githubusercontent.com/5204930/180476958-37bc270f-337c-4478-89f1-bfef52961b9c.png)

**Comment by AJIXuMuK** [comment]
@somethingly - localization logic in SharePoint is pretty complicated, and language settings are read from Site Collection and M365 User Profile.
But it seems like you're configuring language in Windows, not in M365.
Could you modify M365 user profile settings and see if it solves the issue?

**Comment by somethingly** [comment]
Hi @AJIXuMuK - the settings were updated within the M365 "My Account" area:

![image](https://user-images.githubusercontent.com/5204930/180816595-5ceb012e-18fe-4d7e-b1a5-7da0b94e5ce7.png)

**Comment by Rafaelki** [comment]
Same behavior here... It works for en-US and en-GB but not for es-ES and es-MX for Mexico, it always takes es-ES
![image](https://user-images.githubusercontent.com/24438807/180972787-ea57c40e-cfec-4027-b711-b9ccbbcd3454.png)

**Comment by AJIXuMuK** [comment]
Sorry @somethingly for messing things up.
Please, update **Office** profile for the user.
Unfortunately, it's not ideal but it is what it is. I even had a blogpost on the related topic back in the days: https://blog.aterentiev.com/outlook-sharepoint-events-time-zones-display-dates

You can use [these docs](https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7) to navigate to the correct settings.

Please, let me know it that works for you.

**Comment by somethingly** [comment]
Hi @AJIXuMuK, it looks like the key profile setting is "Locale" within the Office profile.

![image](https://user-images.githubusercontent.com/5204930/181741587-fb6ab65e-82d0-4d3f-9c61-a5bda603bf5f.png)

For SPFx to load the fr-ca files, this had to be set to French (Canada). If not then it would default to fr-fr, I guess based on the user's language.
