### ISSUE TITLE
SPFx 1.15 - Office Add-In is not working

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-docs#8333]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx - version 1.15.0
- Node.js - version 16.16.0

### Describe the bug / error

The office (webpart context - this.context.sdks.office) option is not available in SPFx Framework 1.15.

### Steps to reproduce

1. Create new solution by running 
`yo @microsoft/sharepoint --plusbeta`
2. Run `npm install @types/office-js`
3. Open webpart file “OutlookAddinWebPart.ts” and update the render method with this code. `this.context.sdks.office` identifies the outlook context.

Note: I also notice that --plusbeta is not reflected in the new solution. When I checked the package.json this is what i can see 
```
"dependencies": {
    "@microsoft/sp-core-library": "1.15.0",
    "@microsoft/sp-lodash-subset": "1.15.0",
    "@microsoft/sp-office-ui-fabric-core": "1.15.0",
    "@microsoft/sp-property-pane": "1.15.0",
    "@microsoft/sp-webpart-base": "1.15.0",
    "@types/office-js": "^1.0.267",
    "office-ui-fabric-react": "7.185.7",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.15.0",
    "@microsoft/eslint-plugin-spfx": "1.15.0",
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@microsoft/sp-build-web": "1.15.0",
    "@microsoft/sp-module-interfaces": "1.15.0",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2"
  }
```

### Expected behavior

The office (webpart context - this.context.sdks.office) option is available

**Comment by AJIXuMuK** [comment]
@muges01 - unfortunately, Office add-ins have never made it out of beta and were removed from the package completely.
