### ISSUE TITLE
Extensions: Application Customizer - Additional Placeholders Requested

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#8334]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

in 2017, @andrewconnell opened a ticket and a uservoice to ask for the possibility of having more placeholders, The last communication on the subject dates from 2019.

I have a lots of customers asking for features to extend the possibilities of SharePoint (Replacement of native nav bar/quicklaunch, add custom icon/panel on App Bar, add custom buttons to native header...). For some, i'm use a hack based on CSS, but it's not right way, there is too much maintenance ans instability.

Do you have information, Roadmap or release date (@AJIXuMuK , @VesaJuvonen) ?

UserVoice: https://feedbackportal.microsoft.com/feedback/idea/edf8f364-de1c-ec11-b6e7-0022481f8914
Original closed issue:https://github.com/SharePoint/sp-dev-docs/issues/625

Thanks.

**Comment by AJIXuMuK** [comment]
@PooLP - the discussion around App Customizer is not held in #7406. It also contains Andrew's feedback regarding new placeholders.
Also, just for information, there are discussions around Command Set (#7375) and Field Customizer (#7407)

For the roadmap - unfortunately, there is nothing to share as of now.
