### ISSUE TITLE
SPFX Webpart won't load.  "Your web part will not appear in the toolbox"

### ISSUE THREAD

**Issue by will73** [SharePoint/sp-dev-docs#8336]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

**My current environment:**
Microsoft Edge Version 103.0.1264.71 (Official build) (64-bit)
+-- @microsoft/generator-sharepoint@1.15.0
+-- gulp-cli@2.3.0
`-- yo@4.3.0
Node.js v16.16.0

### Issue description

I have tried every recommendation that I can find online and can't seem to get my webpart to load in the workbench.  I just get the follow message every time.

       **Warning
       Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.**

**and the debug console logs....**

       Failed to load resource: net::ERR_CONNECTION_CLOSED
       sp-webpart-workbench-assembly_en-us_4288ab7d3e81034305c1d213c0e2b2f1.js:71 
        
       Failed to load debug manifests: Error: Script error for: https://localhost:4321/temp/manifests.js
       http://requirejs.org/docs/errors.html#scripterror
       (anonymous) @ sp-webpart-workbench-assembly_en-us_4288ab7d3e81034305c1d213c0e2b2f1.js:71
       manifests.js:1
               
       Failed to load resource: net::ERR_EMPTY_RESPONSE
       VM28:8 
        
       Uncaught (in promise) Error: Script error for: http://localhost:4321/temp/manifests.js
       http://requirejs.org/docs/errors.html#scripterror
           at B (eval at e (sp-webpart-workbench-assembly_en-us_4288ab7d3e81034305c1d213c0e2b2f1.js:71:127530),               <anonymous>:8:252)
           at HTMLScriptElement.onScriptError (eval at e (sp-webpart-workbench-assembly_en-       us_4288ab7d3e81034305c1d213c0e2b2f1.js:71:127530), <anonymous>:30:244)_

**Things I have tried:**

- Uninstalled all npm packages and uninstalled Node.js.  Rebooted and reinstalled.
- Created a new project and ran:
     - npm install --save-dev
     - gulp trust-dev-cert
     - npm audit fix
     - npm cache clean --force
     - npm install --save-dev (again)
- I've updated my project to point to my tenant address in the serve.json file

### PLEASE HELP!! 
(I'm really missing SP Designer and the old content editor web parts!)

**Comment by AJIXuMuK** [comment]
Seems similar to #8258 
@will73 - just to try to unblock you - could you try to open https://localhost:4321/temp/manifests.js in a separate browser tab (it may ask you to proceed).
If you see the contents of the file - try to reload the workbench.

**Comment by will73** [comment]
Thanks for that suggestion.  Unfortunately I've tried that as well.  I just get an "ERR_CONNECTION_CLOSED" window.  Tried waiting for the tasks to load and also tried "gulp serve --nobrowser".  

Getting closer to the ledge here.  Any other suggestions please keep them coming!

**Comment by AJIXuMuK** [comment]
@will73 not sure MFA should affect the flow...
More possible is some security restrictions that are not happy with serving files from `localhost`.
I'd recommend trying the same with dev tenant.
In that case, at least, you can check if that's something on a machine level or tenant level config.
Also - could you please check Network tab of the browser and see what error is returned there.

**Comment by will73** [comment]
> @will73 not sure MFA should affect the flow... More possible is some security restrictions that are not happy with serving files from `localhost`. I'd recommend trying the same with dev tenant. In that case, at least, you can check if that's something on a machine level or tenant level config. Also - could you please check Network tab of the browser and see what error is returned there.

OK, I'll try to setup a dev tenant and test there.  Network tab just shows the same issue as the one I posted in the original description.  The manifests.js file is the only error when I try this in Edge.  Firefox continues to work, but I do notice that it stops working after a while and I have to restart gulp serve, but that I can live with as long as I can test.
 
![image](https://user-images.githubusercontent.com/38590480/181620939-66e000cc-7360-4aef-9a84-c9bdc3bfb415.png)

**Comment by will73** [comment]
Just wanted to add an updated to this.  I finally was able to resolve this and it was nothing to do with the setup.  My company uses something called Digital Guardian for security reasons.  It was acting as a proxy for my browsers and causing the issue.  They finally updated the configuration due to an unrelated issue and it resolved the issues I was seeing in my environment.
