### ISSUE TITLE
SPFx package auto-updating when not tenant deployed and version number is different.

### ISSUE THREAD

**Issue by c-eiser13** [SharePoint/sp-dev-docs#8339]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version: 1.14.0
- Node.js version: 14.9.0
- etc

### Issue description

Hello all, I'm moving a solution from site collection app catalog use to the tenant app catalog and I'm trying to fully understand if what I'm seeing is expected behavior or not. Here is my scenario:

1. I have an SPFx package deployed to tenant app catalog, it is NOT tenant deployed, and its app version is 1.17.0 (I am managing this in package-solution.json). 
2. I have 2 site collections where this app is installed (one is a "dev" site and one is a "prod" site) and if I go to site contents and view the details of the installed app, I can see the version is reporting 1.17.0 on both site collections.
3. Next, I go in and make a code change, bump the package-solution.json to 1.17.1 (technically 1.17.1.0 since it is 4 digits), and create a new build.
4. I go to the tenant app catalog and upload/overwrite the existing .sppkg and the version in the app catalog properly updates to 1.17.1, and again, I am not checking the box to deploy to all sites.
5. If I go to either of the site collections where this app is installed, I can instantly see the code changes I made in 1.17.1, but if I go to site contents and view the details of the app, it is reporting I have version 1.17.0 and there is a "Get it" option to get the latest 1.17.1 version.

My goal is to test the changes in the dev site collection by clicking get it and reviewing the changes there and once verified, going to the other site collection and pulling the latest version. I feel like it was working this way just a couple of weeks ago, and then something changed. I've tested this scenario in multiple tenants and the consuming site collections continue to see the latest code even though the app is reporting that it does not have the latest version and I have the option to click "Get it." Also, I am not using CDN, in case that makes any difference. I've also tested changing version to 2.x.x to see if that would make a difference and it did not.

When the version is different, what is the purpose of the Get it button if the updates are automatically pushed to the sites where the app is installed?

Appreciate any and all clarification!

**Comment by AJIXuMuK** [comment]
@c-eiser13 - the behavior you're seeing is expected.
Code changes are applied right away (technically, the manifest and code for your components live in app catalog site collection and served from there. If you upload new solution, the manifest and code files are updated and new versions are served).
app version (solution version) is needed when you deploy some assets with your solution. In that case when a user updates the version on a site you can do some "upgrade" actions to the assets.
