### ISSUE TITLE
Can you jump from this to the latest version

### ISSUE THREAD

**Issue by mcpsmith** [SharePoint/sp-dev-docs#8340]
One thing that is unclear is if incremental updates have to be made or if I can go straight from several versions ago (1.12) to latest (1.15)  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a226ed-cc0c-85fb-0313-c69ef2c9cd55
* Version Independent ID: 68a226ed-cc0c-85fb-0313-c69ef2c9cd55
* Content: [SharePoint Framework v1.13.1 release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.13.1)
* Content Source: [docs/spfx/release-1.13.1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/release-1.13.1.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
If you're talking about upgrading your existing solution versions to a newer one, yes you will need to make updates to your solution. Highly recommend using the Microsoft 365 CLI to help you with this. You can use the Project Upgrade command it will walk you through the steps needed to upgrade your solution.

https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/

**Comment by AJIXuMuK** [comment]
All as @bcameron1231 said!
You can definitely upgrade from 1.12 to 1.15. And you don't need to upgrade to 1.13 -> 1.14 -> 1.15.
You can go directly from 1.12 to 1.15.
