### ISSUE TITLE
SPFx webpart not loading on iOS device

### ISSUE THREAD

**Issue by pk-1990** [SharePoint/sp-dev-docs#8342]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version - 1.13.0
- Node.js version- -1 4.15.0

Other packages used for implementing Dependency Injection in SPFx project

Inversify - 5.1.1
reflect-metadata - 0.1.13

### Issue description

Issue is occurring only for iOS devices and it seems to be occurring because of inversify and reflect-metadata package. Not sure though.

--------------------------------------------------------------------------------------------------------------------------------------
Error while using public cdn:
![image](https://user-images.githubusercontent.com/98381817/181510318-e406bc69-a456-4405-b758-2fdff4747277.png)

-------------------------------------------------------------------------------------------------------------------------------------

Error after changing **includeClientSideAssets: false** and given site library path in **cdnBasePath**
![image](https://user-images.githubusercontent.com/98381817/181510819-b851fc04-1484-4e7e-9e7d-1d16f9771358.png)

---------------------------------------------------------------------------------------------------------------------------------------
Usage of packages in Service.ts file:
![image](https://user-images.githubusercontent.com/98381817/181511005-a9be8f3b-d918-4385-9ad3-7fa5bc94b439.png)

Webpart is loading fine in Desktop and Android device. Issue seems to be with Safari browser only.

**Comment by AJIXuMuK** [comment]
@pk-1990 - could you please try to deploy your solution on another tenant from scratch and see if the error is still there.
Also, could you share the solution with me? You can send it to aterentiev@microsoft.com

**Comment by kbeeveer46** [comment]
What version of @pnp/sp are you using? If you're using 3.0.0 through 3.4.0 there was a bug in all of those versions that wouldn't allow web parts to load in Safari because the library was using regex that Safari didn't support. I reported this bug and they fixed it in 3.4.1 [https://github.com/pnp/pnpjs/blob/version-3/CHANGELOG.md](https://github.com/pnp/pnpjs/blob/version-3/CHANGELOG.md)
