### ISSUE TITLE
Access SharePoint Online from external source

### ISSUE THREAD

**Issue by MarioZagreb** [SharePoint/sp-dev-docs#8343]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have a SharePoint Online and I have external software, let's call it SystemX.

SystemX needs to upload document to my SP doc lib. What is the right way?

Every single documentation on the web says to call this URL (with appropriate clientId and clientSecret):
https://accounts.accesscontrol.windows.net/tenant-url/tokens/OAuth/2

but is that the proper way of getting the access token, isn't this deprecated ?
 
I can't find the documentation for that anywhere...

EDIT:
Actually, I would like to avoid getting the token and client secret and all of that...

What I would like to do is this:
I just downloaded the app from the SharePoint store - DocuSign. The app asked me for permissions to write to my SP, users, etc.
I allowed.
App was installed and it installed menu items on document menu in doc library.
On click of that menu item, new tab was opened, my document was opened in that tab.
After the signing, new (signed) document was returned to my document library.

How can I achieve that scenario of returning the document from another web page (or some third party software) to sharepoint without the need for configuring clientId, clientSecret or getting the token???
I see that it is possible, but I don't know how

**Comment by CallumCrowley** [comment]
Have you considered using [Azure App-Only permissions to access SharePoint](https://docs.microsoft.com/sharepoint/dev/solution-guidance/security-apponly-azuread)? You can use that app registration to use the Microsoft Graph API or SharePoint REST API where the Graph doesn't have what you need.

**Comment by MarioZagreb** [comment]
@CallumCrowley thank you for quick response.
But, as I said in the EDIT part of the question, this is exactly what I am trying to avoid. I do not want to do anything in AAD.

My question how to I avoid AAD? This is the scenario I want to achieve:

I just downloaded the app from the SharePoint store - DocuSign. The app asked me for permissions to write to my SP, users, etc.
I allowed.
App was installed and it installed menu items on document menu in doc library.
On click of that menu item, new tab was opened, my document was opened in that tab.
After the signing, new (signed) document was returned to my document library.

How can I achieve that scenario of returning the document from another web page (or some third party software) to sharepoint without the need for configuring clientId, clientSecret or getting the token?

**Comment by CallumCrowley** [comment]
Yes but when you are logging in via DocuSign, it is still using an token to make the calls to SharePoint. That token is provided by Microsoft in the context of the user that just signed in.

You can either use [Azure AD app registration](https://docs.microsoft.com/sharepoint/dev/solution-guidance/security-apponly-azuread) to access SharePoint (recommended in most scenarios), [SharePoint App-Only (legacy)](https://docs.microsoft.com/sharepoint/dev/solution-guidance/security-apponly-azureacs) or the context of the current user. They all involve tokens because the API requests that the third party application makes need to be authenticated.

**Comment by AJIXuMuK** [comment]
@MarioZagreb - when DocuSign or any other ISV registers the application, they do create either an AAD app or client id/client secret for Add ins.
You just don't see it when you're installing the app but it still uses app registration, you allow the permissions and it's ready to go.

**Comment by MarioZagreb** [comment]
@CallumCrowley 
In both these scenarios (Azure AD app registrations or SharePointApp-Only) SP admin has to click on the SP (or Azure) and create the app (or clientId, clientSecret), right?
How to achieve this through app programatically, so that the app does that itself, not the SP admin?

**Comment by MarioZagreb** [comment]
> @MarioZagreb - when DocuSign or any other ISV registers the application, they do create either an AAD app or client id/client secret for Add ins. You just don't see it when you're installing the app but it still uses app registration, you allow the permissions and it's ready to go.

Yes, I know that, and my question is exactly that: "how does that app register the application, what API do I need to use to achieve that"?

**Comment by CallumCrowley** [comment]
@MarioZagreb Azure app registrations can be multitenant, so once you have created it, an admin of another tenant can grant that same app registration access to their tenant using by going to an admin consent URL that has the appropriate URL parameters. Once the app registration has access, the app can authenticate with the tenant and carry out whatever tasks it needs to. This is probably the simplest way for a client to grant tenant access to a third party application. Here is an example of the admin consent URL:

[Request the permissions from a directory admin](https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#request-the-permissions-from-a-directory-admin)

**Comment by MarioZagreb** [comment]
@CallumCrowley Thanks, that seems close enough, but still, DocuSign app didn't ask me to go to any URL, just asked me on the app install do I allow

**Comment by CallumCrowley** [comment]
@MarioZagreb I'm not familiar with DocuSign but they are likely either using Azure AD app-only or SharePoint app-only, both have been suggested here.

**Comment by MarioZagreb** [comment]
@CallumCrowley thank you very much for all your answers, I appreciate your help! I will try to develop solution based on your suggestions.

**Comment by AJIXuMuK** [comment]
@MarioZagreb - most probably (if it is add-in) they use this registration: https://docs.microsoft.com/en-us/office/dev/store/create-or-update-client-ids-and-secrets

So, the client id and client secret are registered in Partner Center. It allows the app to be "multi tenant".
But I wouldn't recommend dealing with SharePoint Add ins.

**Comment by MarioZagreb** [comment]
> @MarioZagreb - But I wouldn't recommend dealing with SharePoint Add ins.

Why not? Because they will be deprecated?

**Comment by CallumCrowley** [comment]
Microsoft recommend using the Azure AD app-only model:

"For new tenants, apps using an ACS app-only access token is disabled by default. **We recommend using the Azure AD app-only model which is modern and more secure.** But you can change the behavior by running ‘set-spotenant -DisableCustomAppAuthentication $false' (needs the latest SharePoint admin PowerShell)."

[Granting access using SharePoint App-Only](https://docs.microsoft.com/sharepoint/dev/solution-guidance/security-apponly-azureacs)

**Comment by AJIXuMuK** [comment]
@MarioZagreb - as @CallumCrowley said :)
