### ISSUE TITLE
let workbench have current list and current item in context

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#835]
can we get the workbench to have a current list and current item in the context. this would be helpful in developing webparts that serve as list Forms?

**Comment by bcameron1231** [comment]
@russgove While you cannot use local workbench for this, you can use your site workbench. Navigate to your site https://yoursite.sharepoint.com/sites/sitehaslist/_layouts/workbench.aspx

**Comment by bcameron1231** [comment]
@russgove  This would be pretty neat. At best, I suppose you could mock it using URL parameters and using your site workbench (/_layouts/workbench.aspx) instead of your local workbench, so you aren't completely stuck.

**Comment by russgove** [comment]
_layouts/workbench.aspx
<https://yoursite.sharepoint.com/sites/sitehaslist/_layouts/workbench.aspx>
does
not provide a list or item in the context.

**Comment by mcmynn83** [comment]
Please make this new feature request in user voice (https://sharepoint.uservoice.com/).

**Comment by russgove** [comment]
i created a user voice at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/31265701-let-us-configure-sp-page-context-settings-on-the-w
