### ISSUE TITLE
What's the least privileged permissions need to grant permissions to the newly created principal on sites operation

### ISSUE THREAD

**Issue by Jingshu923** [SharePoint/sp-dev-docs#8351]
[Enter feedback here]

We need operate with SharePoint site and we use app-only ACS authentication to do. Refer to your doc and want to confirm:
To grant permissions to the newly created principal via [https://contoso-admin.sharepoint.com/_layouts/15/appinv.aspx], what's the **least privileged** permissions? We can do it work by site owner before, but currently just site admin can work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
@Jingshu923 you can find this information in the [Add-in permissions in SharePoint](https://docs.microsoft.com/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint) documentation.

**Comment by Jingshu923** [comment]
Seems this doc can't help me. I want to know what the least privileged permission can grant add-in permission, not about granting which permission.
To grant permissions to the newly created principal via https://contoso-admin.sharepoint.com/_layouts/15/appinv.aspx, what's the least privileged permissions can do this grant?

**Comment by CallumCrowley** [comment]
You need [full control permissions to add an app from the SharePoint store](https://support.microsoft.com/office/add-an-app-to-a-site-ef9c0dbd-7fe1-4715-a1b0-fe3bc81317cb#ID0EDH=Newer_versions), so it's likely that the same applies in your situation:

"You must have Full Control permissions to add apps from the SharePoint Store. You already have this if you are a Site Owner."

**Comment by Jingshu923** [comment]
![image](https://user-images.githubusercontent.com/52914166/182985892-c6970cf5-46af-49ab-894b-b4dc7af801f6.png)
My "app" means using service principal to have permission on SharePoint, not "an app".
Do you know the least privileged permissions to do this as the picture show?

**Comment by CallumCrowley** [comment]
The user would need to be a SharePoint administrator, since the page above is part of the SharePoint admin center (https://**contoso-admin.sharepoint.com**/_layouts/15/appinv.aspx).

**Comment by Jingshu923** [comment]
Thanks. Could you help confirm this with developer since we can make it work before by using Owner permission. But can't work now. Are there any changes recently?

**Comment by CallumCrowley** [comment]
The page you're referring to app only creation page in admin center https://**contoso-admin.sharepoint.com**/_layouts/15/appinv.aspx have always been inaccessible to those who are not SharePoint administrators. You cannot access the [SharePoint admin center without being a SharePoint administrator](https://docs.microsoft.com/sharepoint/get-started-new-admin-center).

You might be referring to a site level app registration page e.g. https://mytenant.sharepoint.com/sites/mysite/_layouts/15/appinv.aspx
