### ISSUE TITLE
SharePoint Framework Tutorial Part 4 -  @typescript-eslint/no-floating-promises:

### ISSUE THREAD

**Issue by BlueSilver82** [SharePoint/sp-dev-docs#8354]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Build tools version:3.17.19
- Node.js version v14.15.0

### Describe the bug / error

When running gulp bundle --ship I received the below error

Warning - lint - src/webparts/helloWorld/HelloWorldWebPart.ts(60,5): error @typescript-eslint/no-floating-promises: Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be 
explicitly marked as ignored with the `void` operator.

I updated the below code from tutorial and seemed to resolve but may not be the correct way of doing it

**ORIGINAL**
  private _renderListAsync(): void {
    this._getListData()
      .then((response) => {
        this._renderList(response.value);
      });
  }

**UPDATED**
  private async _renderListAsync(): Promise<void> {
    await this._getListData()
      .then((response) => {
        this._renderList(response.value);
      });
  }

### Steps to reproduce

Run  gulp bundle --ship   at end of Part 4 tutorial

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn?WT.mc_id=m365-15744-cxa

### Expected behavior

No errors were expected

**Comment by AJIXuMuK** [comment]
@BlueSilver82 - if you're `await`ing the promise, you don't need to use `then`.
Your code should be like that:
```typescript
private async _renderListAsync(): Promise {
  const response = await this._getListData();
  this._renderList(response.value);
}
```
