### ISSUE TITLE
Viva Connections on Microsoft Teams Desktop App - Custom API calls in spfx webparts of home site are not working

### ISSUE THREAD

**Issue by Srpatil212** [SharePoint/sp-dev-docs#8355]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Windows Desktop App for teams

### Issue description

We are experiencing that custom API calls in spfx webparts which are added on sharepoint home site are not resolving in Viva Connections App in Windows Desktop client.
Sharepoint list calls in these spfx webparts are working fine and returning response in teams desktop client.
These api calls are being made to service endpoints using aadhttp client in spfx webparts.

Same api calls in spfx webparts are working fine when deployed as Personal app and Tab on Teams Desktop app.

Custom api calls in these webparts are working fine in Teams Web version Viva Connections. 

These were working till a month back. Issue has been observed recently. Is there any new configuration that needs to be done in viva connections configuration to get these working again.

**Comment by lucabandMSFT** [comment]
hey @Srpatil212 , thanks for reaching out. When you say "Viva Connections App in Windows Desktop Client" you mean "Viva Connections app in Teams Desktop on Windows"? Or something different?
IF that is the same thing, can you please explain how did you make it work this part: "Sharepoint list calls in these spfx webparts are working fine and returning response in teams desktop client."?
Thanks

**Comment by Srpatil212** [comment]
@lucabandMSFT Yes its Viva Connections app in Teams Desktop on Windows and Mac systems. 

We did not do anything explicitely to sharepoint list calls work. But the difference between sharepoint calls and custom API calls is that former is using Sphttpclient (which is working fine) and later is using Aadhttpclient (which is failing).

**Comment by lucabandMSFT** [comment]
@Srpatil212 , thanks

so.. to be clear on the current situation:
* reading SPList APIs, works everywhere
* reading custom API works in Teams desktop as Persona app / Teams tab for both Mac and Windows
* reading same custom API doesn't work as ACE in Teams Desktop (Mac and Windows).

did I recap correctly? If yes, is the code the same for #2 and #3? And what is the error you are experiencing?
Last, does reading custom API in an ACE when you access the dashboard in SharePoint Page (browser) works?

**Comment by Srpatil212** [comment]
@lucabandMSFT Bullet point 1 and 2 are correct.
Regarding point (3): The issue is not for ACEs but spfx webparts on sharepoint home site which have custom API calls are not working in Viva Connections teams desktop app. 
The issue is for sharepoint home site spfx webparts which shows up in desktop teams viva connections app. 
Also custom api calls in viva ACEs in dashboard webpart added on home site dont work. 
Have observed OOB Viva ACE for Assigned Tasks in dashboard webpart also keep in loading state in desktop viva connections app.
They work fine in viva connections app in teams desktop browser version.

Same code is added for all the cases.

**Comment by lucabandMSFT** [comment]
@Srpatil212, thanks. What is the error you are experiencing?
Would be possible for you to collect an HAR file from the Teams desktop for the scenario that doesn't work?
