### ISSUE TITLE
New/freshly scaffolded project/extension with old/existing id's (Upgrading extensions)

### ISSUE THREAD

**Issue by DmitriyVdE** [SharePoint/sp-dev-docs#8359]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 103.0.5060.134 & Edge 104.0.1293.47
- SPFx 1.14 & 1.15
- Node.js 14.19.1 & 16.15.1
- etc

### Describe the bug / error

We decided to upgrade our SPFx projects from 1.9 to 1.14 and more recently 1.15 since that just came out.
In stead of upgrading the dependencies in the existing projects we decided to create new projects and just port our code, and set the ID's to be the same as in the existing projects.
This works perfectly for webparts and does not cause any issues. The versions just get upgraded on existing installs and new sites have access to theses webparts.
For extensions though only sites that already had these extensions installed get updated to the new version, but when creating a new site, and adding the extension by 'adding and app' to the site, the extension doesn't get loaded and also does not show up in the list of manifests in the SPFx dev tools (ctrl + F12).

### Steps to reproduce

1. Create a project in SPFx 1.9
2. Install deps, write code, etc...
3. Install to app catalog (Don't deploy everywhere)
4. Add app to site
5. Create a new project in SPFx 1.15
6. Copy code, deps, etc...
7. Copy ID from yo.rc
8. Copy ID from src/manifest.json
9. Copy ID, zippedPackage (sppkg filename) & name from config/package-solution.json
10. Copy ID from config/serve.json for customActions
11. Build and deploy to app catalog
12. Create new site
13. Add extension to site
14. Extension does not get loaded
15. (Optional) Remove extension from first site
16. (Optional) Add extension to first site
17. (Optional) Extension does not get loaded

### Expected behavior

Added extensions should load to new and exiting sites (Where extension was removed and re-added).
Changing the ID's in above mentioned places to new ones and changing the filename and package names also does not work.
The extension is seen as a new solution, but when adding it to a site it still doesn't show up.
I have tried just creating a new clean solution with the default code (SPFx 1.15) and installing that does work.
I'm wondering if I'm missing some other config or anything else.
I haven't tried creating a new project and porting the code there, but this would not be a favorable solution since this would involve a lot of work to remove an install these on every customers tenant.

If you require any more info, feel free to ask for it.

Thank you.

**Comment by AJIXuMuK** [comment]
@DmitriyVdE - are you using "Add an app" for web parts too? Or web parts are tenant-wide deployed?
also - could you please share `package-solution.json` files?

**Comment by DmitriyVdE** [comment]
Update.

So apparently extensions also have a folder 'assets' within the 'root/sharepoint' folder which contains the 'ClientSideInstance.xml' and 'elements.xml' with other optional '.xml' files. I assumed these were automatically regenerated on every build, but apparently not. Updating the id's ('ComponentId' and 'ClientSideComponentId') within these files fixed my issue.

Now I have found that I have the same issue with my webparts not showing up in the toolbox to add them to a page. They are 'added' to the site though. I checked all ID's but apparently webparts don't have these previously mentioned files or even an 'assets' folder within the 'root/sharepoint' folder. Though, they do generate a few '.xml' files within the 'root/sharepoint/solution/debug' folder which do contain id's, but they seem random as I can't find where they come from or how they are generated. The 'AppManifest.xml' file does contain an existing id for the 'ProductID'.

**Comment by AJIXuMuK** [comment]
@DmitriyVdE - so in v1.9 you didn't have `features` in your `package-solution.json`, meaning they were generated during the packaging operation. And when the app was installed on the site - these features were activated.
Now, you're adding feature that is definitely not the same one as generated with your previous solution.
This feature will not be activated unless you do Add an app again.

try delete `features` property from the `package-solution.json`. It should generate the feature in the same way as in your old solution

**Comment by DmitriyVdE** [comment]
@AJIXuMuK - That fixed it! Thank you very much!

I do have to note that, in case there were issues with the newer version, no version can be installed on the (new) site and it should also be removed from both recycle bins. After adding it to the new site the webpart shows up in the toolbox.
