### ISSUE TITLE
SharePoint Designer: Lookup permission error not handled

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-docs#836]
![nestedlookupwf](https://user-images.githubusercontent.com/26794567/30109569-1c5c4b4a-9307-11e7-86d8-12d59c55d735.png)
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When assigning a variable a value from another list and matching that value with another lookup value from an additional list, where the current user does not have permissions, the workflow should report an error (i.e a 403 error to the list where the user does not have permissions)

#### Steps to Reproduce

1. Create a "Parent" list
2. Create "Lookup List 1"
3. Create "Lookup List 2"
4. Create lookup to "Parent List" in "Lookup List 1" (Title field)
5. Create lookup to "Lookup List 2" in "Parent List" (Title field)
6. Create workflow on Lookup List 1 and assign a variable a value from "Lookup List 2" matching where ID = Parent List lookup field to "Lookup List 2" (lookup Id) matching where ID = current item lookup field to "Parent List" (See attached image. RegionList=Lookup List 2, BaseList=ParentList, Current Item=Lookup List 1)

Permissions should be setup so that the initiator of the workflow does not have permissions on Lookup List 2.

It took a long time to track down this issue in our environment as no error was reported. In our environment, we have a parent list where a workflow creates tasks in an associated task list. Another workflow is then run on the task to update permissions based on a region that is set in the parent item. This region is a lookup to a list where groups are defined per region that the workflow on the task item must fetch. So the group is fetched from the region list, where the region matches the value in the parent item and the parent item is matched on a lookup to it in the task item. Hopefully along with the steps defined above, that is a clear enough description to say whether this is intended behavior or whether we are right in saying that this should be handled as an error.

Please request additional info if required. 

Thank you.

**Comment by bcameron1231** [comment]
Is there no error in the Workflow History list for this workflow?

**Comment by mcmynn83** [comment]
@HTEredrock  - If you would like help from the workflow team at Microsoft you will have to open up a support case so that it gets routed through the proper channels.  I asked a co-worker on the workflow team and he said the logic looks a little odd, but needs more info which will get queried for via a support ticket.  Sorry.

**Comment by HTEredrock** [comment]
@bcameron1231 nope no error in the workflow history

@mcmynn83, could you recommend the correct channel to log this as a support case? I tried to log it as a service request through the SharePoint admin centre and they pointed me here.
