### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by LindaCicero** [SharePoint/sp-dev-docs#8360]
Broken on this page: "You can find this sample with additional details here: [Conditional formatting based on choice field](https://github.com/SharePoint/sp-dev-list-formatting/tree/master/view-samples/text-conditional-format)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe434a7d-e85f-bdda-c481-cb05b4b19a73
* Version Independent ID: fe434a7d-e85f-bdda-c481-cb05b4b19a73
* Content: [Format list view to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-list-formatting)
* Content Source: [docs/declarative-customization/view-list-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/view-list-formatting.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
Seems as though this sample never made it in to master: [Conditional formatting based on choice field](https://github.com/pnp/List-Formatting/blob/5912c9797a3d1353364adab130d741b5e3aeeeed/view-samples/text-conditional-format/README.md)

**Comment by nanddeepn** [comment]
@thechriskent Can you please help here?

**Comment by thechriskent** [comment]
This sample was renamed to be less generic and more discoverable. It can be found here: https://github.com/pnp/list-formatting/tree/master/view-samples/status-rowclass

**Comment by nanddeepn** [comment]
Thank you @thechriskent ❤️
