### ISSUE TITLE
SP Workflow - Field is in another web

### ISSUE THREAD

**Issue by HTEredrock** [SharePoint/sp-dev-docs#837]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have a quick question regarding site column lookups being unusable in workflows. If it is possible to get data from another site using REST, then why do workflows not lookup the data in the same way?

I.e, with REST you can get the lookup Id from the current item (siteColumnNameId) and then use that Id to get the data from the actual list the site column is pulling data from. 

Currently you get a "field is in another web" error but surely you could resolve the address of the site column and fetch the value directly with the normal WF action?

**Comment by russgove** [comment]
Same thing with ;large lists. If it is possible to get data from large lists (>5000 items) using rest, then why do oob workflow action not use rest to retrieve the data?

**Comment by bcameron1231** [comment]
@russgove Relevant UserVoice. [https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/9065329-enable-support-for-lookup-columns-in-other-webs-in](url)

**Comment by mcmynn83** [comment]
The uservoice request that @bcameron1231  linked is the correct place for this new feature ask.  I am closing this issue.

**Comment by HTEredrock** [comment]
@russgove I could be wrong, but I think the normal workflow actions are using REST underneath, its just that they do not implement batch requests. But as you say, I don't really feel SharePoint Designer workflows are where their dev attention is currently. Even when we have Azure Logic Apps, SP Workflows will still be very much needed I feel.
