### ISSUE TITLE
Applying permissions on Form Customizer

### ISSUE THREAD

**Issue by legenam** [SharePoint/sp-dev-docs#8372]
After implementing Form customizer on a SharePoint Online list, I identified that any instance shouldn't be created in any site where component neet to be user. The serve.json is the only link between component and list.
How should it work for permissions? 
Currently, only admin or site collection owners can use it and I don't find any information about it for giving access to contributors?
How to solve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb30c104-ffec-93ac-93eb-2294317b4e4b
* Version Independent ID: bb30c104-ffec-93ac-93eb-2294317b4e4b
* Content: [Build your first Form customizer extension (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-form-customizer#feedback)
* Content Source: [docs/spfx/extensions/get-started/building-form-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-form-customizer.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@legenam - could you please describe you issue in more details?
What type of permissions are you referencing to? Who has access to the form or who can add the form customizer to the list/content type?

**Comment by legenam** [comment]
@AJIXuMuK After deploying the solution on a site collection app catalog, defining permissions on this app and to the list linked to this component, a user with Contributor role received an access denied error wehn clikc on New or when try to edit an item.
When SPListForm.aspx is loaded the user doesn't seems to have enough right permissions.

NB: The Form has been linked through PowerShell Script. The site collection owner does'nt receive any error message and everything works fine.

**Comment by legenam** [comment]
@AJIXuMuK The use is Visitor (Read-Only) on the site and has 'Collaborate' permission level on the list.

**Comment by AJIXuMuK** [comment]
Thank you @legenam for the additional details.
The fix has been done. It will take few weeks though to be rolled out WW.

**Comment by AJIXuMuK** [comment]
this should be rolled out
