### ISSUE TITLE
JSON sometimes is not applied to List calendar view

### ISSUE THREAD

**Issue by JohnMark8080** [SharePoint/sp-dev-docs#8373]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Microsoft Edge Version 104.0.1293.54 (Official build) (64-bit)
Firefox 103.0.2 (64-bit)
Chrome Version 104.0.5112.81 (Official Build) (64-bit)
Microsoft Teams Version 1.5.00.21618 (64-bit)-E. It was last updated on 8/15/2022.
Windows 10 Version 10.0.19044 Build 19044

Tried this with and without extensions/add-ons.

### Describe the bug / error

I created a SharePoint online list and created a calendar view. I added JSON for the calendar view. The formatting works as expected, but sometimes it doesn't shown up at all on the calendar view. If I close the page, clear the browser cache, and reload the page it usually works the first time. I created the list to be viewed via Teams and the JSON isn't applied there.

Looking at the browser debugger when the JSON is not applied, I see many errors that look like this "ProgramStatus was not found on the data object." with all the internal names listed. These errors do not occur when the JSON works. I have tried the latest versions of Edge and Firefox. Once this occurs, it seems to affect the other tabs in the same browser. And it can occur on a simple page refresh.

### Steps to reproduce

1. Load the calendar view
2. Refresh the page
![calendar without styling](https://user-images.githubusercontent.com/22012885/184996227-14815803-f001-42f8-aa97-f69cd9f201c8.png)

One other odd behavior is that this is the default view, but sometimes the old default view is displayed. Selecting the calendar view then usually works.

Here is the view JSON:
`{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/calendar-formatting.schema.json",
  "additionalEventClass": "=if([$Organization] =='MIT DC', if([$ProgramStatus] =='Confirmed', 'ms-bgColor-sharedRed20 ms-fontColor-white', 'ms-bgColor-yellow ms-fontColor-black'),if([$Organization] =='MIT Alumni Angels DC',if([$ProgramStatus] =='Confirmed', 'ms-bgColor-sharedGreen20 ms-fontColor-white', 'ms-bgColor-greenLight ms-fontColor-black'),if([$Organization] =='MIT', if([$ProgramStatus] =='Confirmed', 'ms-bgColor-neutralSecondary ms-fontColor-white', 'ms-bgColor-neutralTertiaryAlt ms-fontColor-black'),if([$Organization] =='MIT Alumni Association', if([$ProgramStatus] =='Confirmed', 'ms-bgColor-purple ms-fontColor-white', 'ms-bgColor-purpleLight ms-fontColor-black'),if([$OtherLocalAlumClub] =='Yes', if([$ProgramStatus] =='Confirmed', 'ms-bgColor-sharedCyan20 ms-fontColor-white', 'sp-css-backgroundColor-BgCyan ms-fontColor-black'),'')))))"
}`

### Expected behavior

This is usually what it looks like on the initial view.

![calendar with working styling](https://user-images.githubusercontent.com/22012885/184996216-105e8068-1e1a-4a2e-9892-5d7d8d9b064e.png)

**Comment by JohnMark8080** [comment]
More information: once it stops working, I can switch to a non-calendar view and back to the calendar view and the formatting is applied again.

**Comment by JohnMark8080** [comment]
Recreated the issue on a separate site (and computer, etc.). When using the default Title field/column in the JSON calendar view formatting, everything works as expected. Switching this to a choice field/column, recreates this problem.

This JSON works: 

    {
      "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/calendar-formatting.schema.json",
      "additionalEventClass": "=if([$Title] =='AAA', 'sp-css-color-WhiteFont sp-css-backgroundColor-BgBlue' , '')"
    }

This JSON exhibits the issues of losing the formatting that is properly shown only after switching views:

    {
      "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/calendar-formatting.schema.json",
      "additionalEventClass": "=if([$Category] =='Blue', 'sp-css-color-WhiteFont sp-css-backgroundColor-BgBlue' , '')"
    }

**Comment by JohnMark8080** [comment]
When adding this to a modern page and changing the views, I get this message when selecting to change the view to the calendar view, "Invalid calendar view. Fix errors below to continue." There are no obvious errors. Maybe this [post ](https://lists.handsontek.net/calendar-view/)is the solution?

**Comment by shagra-ms** [comment]
@JohnMark8080 Thanks for reporting these issues. I am summarizing the issues listed above as 2 unique issues - 
1. Error on switching to a Calendar View in the List Web Part
2. Formatting is not applied if the Field is not in View.


1 - I have a local repro, and I'll look into this.
2 - Formatting wouldn't automatically include the fields used in the JSON in the ViewFields. In order for this to work, I would recommend to go to classic view settings, and include the fields used in the formatter JSON in the ViewFields. This will fix the issue you are facing.

![image](https://user-images.githubusercontent.com/37994247/185368063-04d41d0e-69dd-4a33-9e4e-bc0d36b732a9.png)

Apart from this, would like to know the issues in which the Calendar as default view doesn't work for you. Would like to address those issues too, if you can share more details. Thanks :)

**Comment by JohnMark8080** [comment]
@shagra-ms That totally fixed the issue. Everything works as expected. Thank you.

**Comment by JohnMark8080** [comment]
@shagra-ms Your suggestion totally fixed my issue. Thank you. Everything is working as expected.
