### ISSUE TITLE
Explain how to add user app@sharepoint using the new TermStore admin page

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#8393]
This tip above here: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/elevated-privileges-in-sharepoint-add-ins#low-trust-authorization states:

> To allow to use app-only access for writing to Taxonomy Term Store, you'll need to explicitly add app@sharepoint identity as a Term Store Administrator in the Taxonomy Term Store administrative user interface. This grants the app-only identity needed permissions for write operations. You do not need to perform this step for read operations.

However, the classic TermStore page is being deprecated in September, and the new admin page, does NOT allow to add that app@sharepoint user (it´s not found).

We need a way to add that user, and the documentation should explain how.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01aedd19-0f11-fdb1-bc2c-50079184999e
* Version Independent ID: 98836ff6-bf4a-de93-e25f-77e8adabde96
* Content: [Elevated privileges](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/elevated-privileges-in-sharepoint-add-ins#low-trust-authorization)
* Content Source: [docs/solution-guidance/elevated-privileges-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/elevated-privileges-in-sharepoint-add-ins.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by mbice** [comment]
We would love to know what's happening with this as well as the "Site Collection Access" configuration, which I can only see on the classic term store page right now.

![image](https://user-images.githubusercontent.com/985283/187310222-98cd4cb3-ca51-496b-95a3-456d75997de0.png)

**Comment by luismanez** [comment]
I´ve been in touch with some Microsoft engineers, and now the app@sharepoint user is not needed anymore. I´ve tested it in my different Tenants and is working fine.

@mbice I suggest you open a separate issue with your question.

Thanks!
