### ISSUE TITLE
Can't add Client Web Part to Page

### ISSUE THREAD

**Issue by NikCharlebois** [SharePoint/sp-dev-docs#84]
After deploying the spapp to the catalog and installing the app on my site, I do see the client web part under the Custom web part category no problem. However, when trying to add the web part to my page, while connected as my tenant admin, I get the attached error.

"A Web Part or Web Form Control on this Page cannot be displayed or imported. You don't have Add and Customize Pages permissions required to perform this action."

I can add any other "server-side" web parts no problem.

**Comment by chakkaradeep** [comment]
This is because the site you are loading is probably the default site collection that was created which has NoScript enabled by default.

Can you manually create a new site collection, in that way, it will have NoScript disabled and you should be able to add your web part.

**Comment by NikCharlebois** [comment]
Thanks Chaks, that worked.
