### ISSUE TITLE
Error - [webpack] Error processing webpack stats: TypeError: Cannot read property 'toJson' of undefined v2.0

### ISSUE THREAD

**Issue by DimaIpatii** [SharePoint/sp-dev-docs#8403]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Google Chrome 104.0.5112.102
- SPFx version 1.14.0
- Node.js version 14.18.0

### Describe the bug / error

After creating new webpart and running it (or whatever else webpart) in dev server I've started to receive this errors:
![Error](https://user-images.githubusercontent.com/32913446/187382451-6fa5d1a8-3e5f-451d-a001-1e8b0381b5e5.png)

Later I've discovered that the error is thrown beacuse of **'react-pdf'** library I am using to create pdf files in other webparts I've created before and where haven't had any issue.

I've discovered from issue #7691 that the problem can have the roots inside the file WebpackTask.js coming from gulp-core-build-webpack, I after added additional check for **stats** and everything works well.

Before:
![Before](https://user-images.githubusercontent.com/32913446/187384985-a8059f1b-f136-4be3-bb9e-801f1933fc4f.png)

After:
![Solution](https://user-images.githubusercontent.com/32913446/187385016-acf509ff-f2e3-43f4-8165-b963c731a9f9.png)

### Steps to reproduce

1. Install new webpart;
2. Run gulp serve;

### Expected behavior

serve and bundle commands complete without error.

**Comment by AJIXuMuK** [comment]
@DimaIpatii I believe it behaves correctly.
The task doesn't fail but prints the error if any.

I'm not sure "swallowing" the errors is good.

**Comment by DimaIpatii** [comment]
@AJIXuMuK I've tried to console stats and it was undefined, so for that reason it throws this error.

**Comment by AJIXuMuK** [comment]
Right. But why do you think our engine should swallow it?
