### ISSUE TITLE
SPFx extensions are not rendered in Teams Files tab

### ISSUE THREAD

**Issue by FlorianLabranche** [SharePoint/sp-dev-docs#8405]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version : 1.14.0
- Node.js version : 14.19.3

### Describe the bug / error

SPFx extensions for document libraries (i.e. Field customizer, List view command set,...) deployed to SharePoint Team sites are not rendered on related Teams files tab.

This was fixed and rolled out (see #5438) but it doesn't work anymore.

**SharePoint:**
![image](https://user-images.githubusercontent.com/23434632/187482318-7667bb47-e54b-4c28-86fe-30a2c6678676.png)

**Teams:**
![image](https://user-images.githubusercontent.com/23434632/187483731-defe0d6f-930c-43c6-baa5-b972fbfb611b.png)

### Steps to reproduce

1. Create a ListViewCommandSet extension (basic template is fine)
2. Deploy to SharePoint
3. Install app on a Team Site (linked to an existing Team in Teams app)
4. Extension will show up in document library on SP (web) but not in Teams Files tab (app)

### Expected behavior

Extensions should render in Teams the same way as in SharePoint.

**Comment by FlorianLabranche** [comment]
@AJIXuMuK Maybe you have some informations about this ?

**Comment by AJIXuMuK** [comment]
@FlorianLabranche - unfortunately, we reverted the changes back due to multiple reasons.
We're working on a plan right now how to proceed.

**Comment by FlorianLabranche** [comment]
@AJIXuMuK - Bad luck on this one.
By any chance, do you have any visibility on when it might be available again ?

**Comment by AJIXuMuK** [comment]
@FlorianLabranche - unfortunately, no.

**Comment by AJIXuMuK** [comment]
Will be tracking it in #8450
