### ISSUE TITLE
Clarity on 8279?

### ISSUE THREAD

**Issue by brianpmccullough** [SharePoint/sp-dev-docs#8406]
Does the "fix" for 8279 mean that office-ui-fabric-react/lib/Icon and associated reference materials (such as https://uifabricicons.azurewebsites.net/), will be updated to the newer icons?  Or does it mean that SPO will be completely updated to use the older style icons?
cc/ @VesaJuvonen 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25cf16e-0169-4690-3143-b28fb8281f2b
* Version Independent ID: b25cf16e-0169-4690-3143-b28fb8281f2b
* Content: [SharePoint Framework v1.16 preview release notes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16)
* Content Source: [docs/spfx/release-1.16.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/release-1.16.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@brianpmccullough - #8279 was about specific issue where stock up and stock down icons were swapped.
This was fixed.

**Comment by brianpmccullough** [comment]
Oh, I am seeing issues/differences with a few others.  In particular Telemarketer, SetAction, etc.

**Comment by AJIXuMuK** [comment]
@brianpmccullough - what type of issues? Are you seeing incorrect icons? Or just missing icons?
If the second one - we're not aligned with the latest version of Fluent UI.
You can find the actual list of icons supported in SPFx here: https://uifabricicons.azurewebsites.net/
