### ISSUE TITLE
The Sharepoint recycle bin ignores my region settings, and displays date in American format

### ISSUE THREAD

**Issue by alan-graham-cov** [SharePoint/sp-dev-docs#8409]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc
Microsoft Edge
Version 104.0.1293.70 (Official build) (64-bit)

Firefox 103.0.2 (64 bit)

### Describe the bug / error

When I look at the recycle bin (normally in response to the email (Heads up! We noticed that you recently deleted a large number of files from your OneDrive), the recycle bin page displays all dates in the American format, even though Americans are the only people who use this format.
![image](https://user-images.githubusercontent.com/112611404/187852176-fe5da044-4224-40d1-82b5-f0e54be71dad.png)
![image](https://user-images.githubusercontent.com/112611404/187852300-c4ef30b1-1c3b-469d-8324-c579cc96e7f5.png)
![image](https://user-images.githubusercontent.com/112611404/187852526-7ab8e8f1-fb84-45f4-b5c7-637a93d0b55c.png)

### Steps to reproduce

1. Ensure you're using a region other than USA
2. Open the one drive recycle bin within sharepoint
3. Realise that it's not the 9th January, as reported

### Expected behavior

I expect to be told that it's the 1st of September

**Comment by AJIXuMuK** [comment]
@alan-graham-cov - sorry, but this issue list is for dev topics only.
I would recommend open a support request with Microsoft to be helped
