### ISSUE TITLE
Can't upload sppkg package instead of existing app published app in App store for SharePoint. URGENT

### ISSUE THREAD

**Issue by dleytner** [SharePoint/sp-dev-docs#8410]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Partner submission center

### Describe the bug / error

I have published app and we've built SPFX solution for this app and want to replace package form app to sppkg.
It accepts it if I create new app submission, but when I replace it in the store partner section it says Incomplete and can't be published.

### Steps to reproduce

see above

### Expected behavior

must be uploaded with Complete status.

**Comment by AJIXuMuK** [comment]
@dleytner - unfortunately, we don't support update from Add-in to SPFx solution (`app` to `sppkg`). 
You will need to create a separate app registration for your SPFx solution.

**Comment by dleytner** [comment]
Thank you Alex.
Is there a way to move all our existing ratings and reviews from old App to new one?

**Comment by AJIXuMuK** [comment]
@VesaJuvonen - do you know of such an option?
