### ISSUE TITLE
Unable to automatically update the internal links in webpart  using linkPropertyNames

### ISSUE THREAD

**Issue by Sally985** [SharePoint/sp-dev-docs#8411]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

When tried to update the internal links referred in Webpart propertypane using **linkPropertyNames** in webpart manifest is not working.
Here we are trying to mimic the behaviour of automatic links update in OOB webparts when a link gets updated due to path change or filename change.

Following code added in Manifest file,

{
  ..
  "supportedHosts": ["SharePointWebPart"],
  "supportsThemeVariants": true,
  "linkPropertyNames": ["Fixlinkup"],
  "preconfiguredEntries": [{
    "properties": {
      "Fixlinkup": "/sites/mysite/Pages/somePage"
    }
  }]
}

**Comment by AJIXuMuK** [comment]
@Sally985 - thanks for bringing this up.
Unfortunately, this property was deprecated a while ago and intentionally does nothing.
We do apologize it is not listed as deprecated anywhere in the docs or schema.

We will update the schema to mark it as deprecated.

**Comment by andrewconnell** [comment]
@AJIXuMuK - does this also apply to just that property, or to other similar properties, like `imageLinkPropertyNames`, `searchablePropertyNames`, & `requiredCapabilities`?

**Comment by AJIXuMuK** [comment]
@andrewconnell - it's applicable for `imageLinkPropertyNames`.
it is not applicable for `requiredCapabilities`
And I will need to investigate deeper for `searchablePropertyNames` :)

**Comment by nick-pape** [comment]
Wanted to followup that you can achieve this behavior via `propertiesMetadata` webpart property: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint
