### ISSUE TITLE
Fabric/Fluent Icon Issue

### ISSUE THREAD

**Issue by brianpmccullough** [SharePoint/sp-dev-docs#8420]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version : 1.15.0
- Node.js version : 16.x
- etc

### Describe the bug / error

In image attached, I use the SetAction icon.  Notice in the https://uifabricicons.azurewebsites.net/ site, that the icon lightning bolt is not filled in, but in my tenant it is.  Also notice that the font family in https://uifabricicons.azurewebsites.net/ is "FabricMDL2Icons", but in my tenant is "Fluent MDL2 Hybrid Icons".  I observe with other icons as well.

import { Icon } from 'office-ui-fabric-react/lib/Icon'

<a>
  <Icon iconName="SetAction" />
</a>

### Steps to reproduce

1. in my particular tenant, use SetAction icon (import { Icon } from 'office-ui-fabric-react/lib/Icon' in SPFx customization)
2. deploy customization
3.observe customization (see screenshot)

![image001 (2)](https://user-images.githubusercontent.com/8305245/188956907-66081a84-fccd-435c-b6ed-1909181dfe67.png)

### Expected behavior

Icons are consistent with those in https://uifabricicons.azurewebsites.net/

**Comment by AJIXuMuK** [comment]
@brianpmccullough - icons are _mostly_ consistent.
We know that currently the font has been updated and some icons may not be in sync with the provided url.
I would use this statement: if you select the icon from the URL - it will definitely work.
There might be additional icons that are already available in the service but not updated in the list.
We're working on syncing the lists.

**Comment by brianpmccullough** [comment]
@AJIXuMuK  - so I am confused.  there is work being done to update <Icon> to match what is published in the site: https://uifabricicons.azurewebsites.net/?  Or there is work being done to update the site with updated icons?

**Comment by AJIXuMuK** [comment]
@brianpmccullough - update what is published at https://uifabricicons.azurewebsites.net/
