### ISSUE TITLE
Large Result Sets Pagination documentation is to implement

### ISSUE THREAD

**Issue by PcardosoUnily** [SharePoint/sp-dev-docs#8426]
Regarding this article: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets

Issue 1: 
Currently the documentation specifies the SortList Property Name as "[DocId]".
However, when you actually retrieve the results the Property Key comes back as only "DocId".

This means we now have to sanitize sort property input. Please can you clarify if this is a typo, and if having SortList value of "DocId" would work as well?

Issue 2:
Also, the documentation has us sort Objects by "[DocId]" but then construct the query to filter by a separate property ("IndexDocId") with the value of "[DocId]".

Please can you clarify this is intended? It seems non-sensical to sort by Property A and use that value on a filter by Property B.
It makes it hard to create configurable SPS Queries as well and make this logic extensible to other properties.

For the record, getting the values from "IndexDocId" and using that in the filter by "IndexDocId" seems to work fine and return the same results.

Thank you.

![image](https://user-images.githubusercontent.com/108799775/189316700-45cdc3dc-b076-44b9-ac27-449414fce73b.png)
![image](https://user-images.githubusercontent.com/108799775/189316771-f5f41abe-c0a8-49f0-b17b-dbd5f0fcf35f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d82d79-2ecd-e278-a7e4-44ec8a7a5a90
* Version Independent ID: c2588f4f-c665-f863-79ca-26cd33ba9cf4
* Content: [Pagination for large result sets](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets)
* Content Source: [docs/general-development/pagination-for-large-result-sets.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/pagination-for-large-result-sets.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by pschneidermsft** [comment]
DocId and IndexDocId have the same values but are processed differently by the system.  The documentation is correctly telling you to use the last docid in the result set (the largest one you've retrieved so far) in the query as IndexDocId>*Largest docid* but to use [DocId] in the SortBy property.

**Comment by PcardosoUnily** [comment]
Thank you for the confirmation. A shame that the implementation is a bit janky, but I suppose if that's how it works then we have to make it work for us.
