### ISSUE TITLE
Tenant Wide Extensions list is not getting updated when I deploy a solution Tenant-Wide

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#8427]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hi, 
I have a list view command set that i want to deploy tenant wide. I  setup my clientsideinstance.xml properly and set "skipFeatureDeployment": true in the package-solution.json file.

When I deploy the app no entries are added to the Tenant Wide Extensions list.

To verify it is an issue, i downloaded the sample app at spfx-global-footer.sppkg](https://github.com/pnp/sp-dev-solutions/blob/master/solutions/global-footer/sharepoint/solution/spfx-global-footer.sppkg and deployed it Selecting the option to deploy it tenant wide. Again, No entry is created in my Tenant Wide Extensions list,.

This is a developer tenant, so i am sure its not a permissions issue

### Steps to reproduce

1. downloaded the sample app at spfx-global-footer.sppkg](https://github.com/pnp/sp-dev-solutions/blob/master/solutions/global-footer/sharepoint/solution/spfx-global-footer.sppkg 
2. Deploy it to you tenant app catalog and select the option to 'Make this solution available to all sites in the organization'
3. Check the Tenant wide extensions list. No entries are added

### Expected behavior

entries should be added to the tenant wide extensions list as noted in the video at https://www.youtube.com/watch?v=-TZdLGOemaY

**Comment by AJIXuMuK** [comment]
@russgove - I've just tested it on multiple tenants and it's working fine.
As soon as I enable the solution, I see it in the list.
I'm navigating there using this link:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/17036219/189377796-5edc7d34-536f-4aff-b7ab-9b14f78fa21d.png">

And I see the footer applied to the pages.
Could you please check on other tenants?
Also - are you using classic or modern UI to deploy the solution?

**Comment by russgove** [comment]
Hi, so i tried this on an older dev tenant of mine and it works fine. Its just a single tenant its not working on. I'm thinking there is some issue with my tenant wide extensions list there. Is there some way to troubleshoot this, or maybe recreate the tenant wide extensions list?

**Comment by russgove** [comment]
now it wont even let me add items manually to the list, arghh!

on that site i modified the Tenant wide extension list to be on the quicklaunch and modified the  default view to be soretd, grouped, etc...

Is that not allowed? did i break it?
