### ISSUE TITLE
Web part is not working in IE and Firefox 

### ISSUE THREAD

**Issue by AjitKSahu** [SharePoint/sp-dev-docs#843]
@waldekmastykarz  @patmill  @mcmynn83 

Hi Team,

I have created one SPFx web part using angular 2 which is working fine in chrome but while i am trying to access the same web part in IE and firefox its giving me the below error. Please find the below screenshot for your reference. Please suggest. Below is my package.json file data.

![image](https://user-images.githubusercontent.com/30690321/30198883-d04fdfae-948d-11e7-8f84-35b71e59bceb.png)

Package.json :
{
  "name": "rpt-resource",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "angular/common": "2.0.0-rc.5",
    "angular/compiler": "2.0.0-rc.5",
    "angular/core": "2.0.0-rc.5",
    "angular/forms": "0.3.0",
    "angular/http": "2.0.0-rc.1",
    "angular/platform-browser": "2.0.0-rc.5",
    "angular/platform-browser-dynamic": "2.0.0-rc.5",
    "angular/router": "3.0.0-rc.1",
    "angular/router-deprecated": "2.0.0-rc.2",
    "angular/upgrade": "2.0.0-rc.5",
    "microsoft/sp-core-library": "~1.1.0",
    "microsoft/sp-webpart-base": "~1.1.1",
    "types/webpack-env": ">=1.12.1 <1.14.0",
    "angular": "^1.6.5",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "highcharts": "^5.0.14",
    "moment": "^2.18.1",
    "ng-office-ui-fabric": "^0.15.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "sweetalert": "^1.1.3",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "microsoft/sp-build-web": "~1.1.0",
    "microsoft/sp-module-interfaces": "~1.1.0",
    "microsoft/sp-webpart-workbench": "~1.1.0",
    "types/chai": ">=3.4.34 <3.6.0",
    "types/jquery": "^2.0.48",
    types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "~3.9.1"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  }
}

Regards,
Ajit Sahu

**Comment by waldekmastykarz** [comment]
This is an Angular-specific issue. Like mentioned in the error, Zone.js has already been loaded. I suggest you compare your code with the Angular boilerplate for SPFx that Sebastien Levert has put together which could help you find the reason why your code is failing: http://www.sebastienlevert.com/2017/08/01/sharepoint-framework-and-angular-walkthrough-of-the-spfx-angular-boilerplate/

**Comment by mcmynn83** [comment]
@AjitKSahu - Is this issue resolved?

**Comment by mcmynn83** [comment]
No response, closing the issue.

**Comment by AjitKSahu** [comment]
@mcmynn83 - No its not yet resolved till now.
