### ISSUE TITLE
https://github.com/SharePoint/sp-dev-docs/issues/8340

### ISSUE THREAD

**Issue by mikezimm** [SharePoint/sp-dev-docs#8431]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### CLI for Microsoft 365 version
"v5.7.0"

### nodejs version
v14.17.6

### Describe the bug / error

I upgraded 3 projects from v1.11 to v1.14 using the CLI.  After upgrading I had issues finding them in the toolbox.

NOTE:  Two projects were complicated web parts so after having issues in both, I also created a newly scaffolded SPFx 1.11 Hello World web part and followed the same process.  It too had the same issue.

## This is what I did for the Hello World sample with the issue

I took note of each step and have a lot of screenshots so I will do all that in a reply to keep it clean.

I also documented the original 1.11 hello-world and tracked the upgrade to v1.14 in this repo:
https://github.com/mikezimm/native1.11

## This branch was the initial v1.11 build
https://github.com/mikezimm/native1.11/tree/v1.14-cli-upgrade-suggestions

- It includes the upgrade report md and also code tour.
- I tested via gulp and then deployed the package.
- I added it to a site and page to confirm it worked as expected.

## This branch was the same web part upgraded to v1.14 using the CLI:
https://github.com/mikezimm/native1.11/tree/v1.14-execute-cli-upgrade-instructions

- I tested via gulp and then deployed the package.
- I was never able to add it to a page though because it was not in the toolbox after installing on the page.

## In the past, whenever I upgraded web parts (mostly just internal versions, not SPFx versions), I just:
added to app catalog
waited a couple hours
web parts were automatically updated wherever I went.

There was never any issues or hassles, was very dependable

**Comment by mikezimm** [comment]
# I apologize if this is too much detail... but here are my notes:

## Part 1:  Create initial v1.11 web part from scratch:

## Created new github project to

- Build as 1.11 and then upgrade the same as other 2 projects
- https://github.com/mikezimm/native1.11.git

## Change to node 10

- nvm use 10.24.1

## Create new project

- yo @microsoft/bla bla, used all default settings
- gulped just fine
- installed in app catalog
- installed in site
-  https://mcclickster.sharepoint.com/sites/native1.11install/SitePages/Home.aspx
- pushed to master branch in github

## Upgrade from v1.11 to v1.14

- Change to node 14:  nvm use 14.17.6
- deleted package-lock and node_modules folder
- m365 spfx project upgrade --toVersion 1.14.0 -o tour
- m365 spfx project upgrade --toVersion 1.14.0 --output md > "upgrade-report-toV14.md"
- pushed upgrade files to branch v1.14 upgrade
- pushed branch to master

## Additional fixes

- Fixed a couple syntax errors, no comma, extra curly brace
- Error - [tslint] no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
- Just removed that rule per the instructions

## Tested

- Success gulp build
- Successfully gulp served
- Added v1.14 note to web part text
- Updated 4 versions to 0.0.2
- gulp clean, build, bundle --ship, package-solution --ship
- failed package-solution because metadata and features were at same level as solution
- Moved metadata and features into soultion object
- gulp clean, build, bundle --ship, package-solution --ship
- Successful package this time

## Results and screenshots to follow

**Comment by mikezimm** [comment]
## Deployed to app catalog

![image](https://user-images.githubusercontent.com/49648086/189570404-9cdbd9f3-bd71-4f9d-bcde-48ac1b2ef41c.png)

**Comment by mikezimm** [comment]
## Refreshed **previously installed page**
No issues, auto-upgraded

![image](https://user-images.githubusercontent.com/49648086/189570456-77f22bc3-e53c-4815-a0db-d3e7e8807d70.png)

## Added to new page in same Site
No issues, also was SPA

![image](https://user-images.githubusercontent.com/49648086/189571229-8da0c0e8-12c6-454b-9c16-aa32f4013cba.png)

![image](https://user-images.githubusercontent.com/49648086/189570607-ce85aa0d-90c6-4cfe-90f8-37ce26b1f7a8.png)

![image](https://user-images.githubusercontent.com/49648086/189570665-44c794c8-7a07-45b4-b45f-af9f082724fb.png)

**Comment by mikezimm** [comment]
## But when adding to NEW Site
Added to contents

![image](https://user-images.githubusercontent.com/49648086/189570852-b9d1b629-bfd4-4ea2-a713-5e15d3dc4f12.png)

## Not found in the toolbox in newly installed site

![image](https://user-images.githubusercontent.com/49648086/189571056-577968b0-6289-47d1-a947-be6fd49b8a1d.png)

## NOT visible as SPA in newly installed site

![image](https://user-images.githubusercontent.com/49648086/189570945-bb76dc8f-b91d-4f54-8973-f286f3d34c96.png)

**Comment by mikezimm** [comment]
## NOTE that all of the above was done on my dev tenant.

For my two production web parts, I didn't take any notes because I never had issues like this... but this is roughly what happened:

## Did the upgrade using same CLI and from SPFx v1.11 to SPFx 1.14.

- But I also updated 100's of files and made a lot of other changes so it was a lot messier.

## After doing the minimal upgrades plus the other changes

- I fully tested via gulp with no errors.
- I deployed in my dev tenant, and all seemed ok but to be honest, I didn't try installing on a new site because it was never an issue in the past.

## After deploying to Production tenant,
- I tried to add to a new site because I needed to use the recent changes in production.
- But was not able to find the web part in the toolbox.
- I did confirm it was installed in the site contents though.
- I tried uninstalling and reinstalling but no success.

## It gets worse from here...
Because this was on production tenant, I looked for some help from google.

Outside of references to the spfx web part setting 'hiddenFromToolbox', which was not set to true,

### I only found one other suggestion:
1. Delete from App Catalog,
2. Delete from First and Second Stage recycle bins
3. Re-deploy the package to the app catalog.

### I tried those steps but waited couple hours between 2 and 3.
This was the result:

- I was NOT able to see the web part ANYwhere, even where it was installed and working before.
- I was NOT able to see the web part in the toolbox (even where it was installed).

### After a few hours' time (in case the app catalog just needed time)
I went into the numerous site contents web part 'details' and found the 'Get it' button to get the upgrade.
As soon as I 'Got it', The web parts loaded the latest version.

But I had to physically go to EVERY site and manually upgrade the web part :(

**Comment by mikezimm** [comment]
## Final thoughts - possibly a bug with the feature id?

I'm wondering if it has something to do with the new 'feature' id in the package-solution.json.
The CLI recommended adding the 'feature' section with an id which was not in my 1.11 projects.
Does this feature id have anything to do with adding the solution/web part to new sites?

What is strange is that when I look at the site features page for a 1.11 project (shown below), the webpart id found in the webpart.manifest.json was the 'feature' id as shown on the site features page.

## This is a screenshot from my production 1.11 web part that was not upgraded
![image](https://user-images.githubusercontent.com/49648086/189577617-d5f58505-c039-4192-b7b6-2b465d3a8ef5.png)

##  This is a screenshot from my Test webpart mentioned in the 'Reproduce section above'
![image](https://user-images.githubusercontent.com/49648086/189577516-095a71de-f68a-47ad-a417-bfdc8c92b0bc.png)

BUT in a brand new built from scratch 1.14 web part, the 'id' on the site features page is the Id from the package-solution.json, NOT the web part id.

Hopefully someone who is a lot smarter can figure it out :)

**Comment by AJIXuMuK** [comment]
@mikezimm - could you take a look at this one: #8359 ?
I strongly believe you have the same situation.

**Comment by mikezimm** [comment]
> @mikezimm - could you take a look at this one: #8359 ? I strongly believe you have the same situation.

@AJIXuMuK , I appreciate the reply.

From reading that issue, I should:

- "_try delete features property from the package-solution.json. It should generate the feature in the same way as in your old solution_"
- Try packaging and deploying again.

Just want to be sure because since yesterday, I did some more testing documented in this post on the CLI issues list:
https://github.com/pnp/cli-microsoft365/issues/3665#issuecomment-1244545479

I think the only thing I did differently from what you were suggesting was that I had:
"features": [] in the package-solution.json. 
I didn't totally remove it.

I can try totally removing and let you know how it goes.  Hope it works :)

**Comment by mikezimm** [comment]
@AJIXuMuK ,
After completely removing the features object, **it finally upgraded as expected.**

I also tried one of my production web parts that had issues in dev tenant and it seemed to upgrade smoothly now as well.

Hopefully when I go back and fix the other two (where I completely deleted the version history in the app catalog), they go smoothly as well.

## As far as closing the issue:
Where do you think the root cause lies?  Is there something in the docs that needs to be adjusted or something in the CLI?

Thanks again for the assistance

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "native-1-11-client-side-solution",
    "id": "99428e30-347c-49a2-88d5-2873e1c91395",
    "version": "1.0.0.3",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": ""
    },
    "metadata": {
      "shortDescription": {
        "default": "native-1-11 description"
      },
      "longDescription": {
        "default": "native-1-11 description"
      },
      "screenshotPaths": [],
      "videoUrl": "",
      "categories": []
    } 
    // "features": [
    //   {
    //     "title": "native-1-11 Feature",
    //     "description": "The feature that activates elements of the native-1-11 solution.",
    //     "id": "15820e61-f26b-4f18-8572-03074a20fd0e",
    //     "version": "1.0.0.2"
    //   }
    // ]
  },
  "paths": {
    "zippedPackage": "solution/native-1-11.sppkg"
  }
}
```

**Comment by gallantdon** [comment]
I am experiencing the same issue. Additionally, I have added a new web part to the solution and that web part seems to be available if the features are in the Package-solution.json. When I remove the features I am able to see all of the web parts that were created before the upgrade. I upgraded from 1.12.0 to 1.14.0.

**Comment by mikezimm** [comment]
@gallantdon , I would be cautious and do a lot of testing in a Dev tenant.

Like at least test under the following conditions:
- Add on a new page in a site it was already installed on
- Test and see if it needs to be 'upgraded' in site contents
- Test web part before and after upgrade button is pressed on a site
- Add on site **where it was never installed**
- Make sure you can actually add the web part to the page (just being visible in Site Contents is not enough)

I now have two solutions that I have to **completely rebuild from scratch** because of this.... 

I think my breaking issue was that I published the upgraded solution to our app catalog...

Then afterwards, I discovered it was broken 'on some sites', I deleted it and re-added it to the catalog causing more issues. 

## For the broken solutions, this is the process I had to follow:

1. Create a new 1.15.2 yo project from scratch,
2. Create new web parts using yo (all new id's etc)
3. Then port over my old web part code into the new solution
4. Deal with 1000's of ESLint errors and warnings (even if the code worked before)
5. Add to app catalog

Then upgrade the old solution, add some kind of warning message asking people to replace all their old web parts, disable old web part from Toolbox.  Publish the upgrade to the old solution.  That can be a very ugly situation if you have no way to see where the web parts are installed or there are a lot of instances.

6. Add new solution to all sites where it was previously installed
7. Replace all the web parts with the one from the new solution
8. Once it's safe delete the old solution from the app catalog.

**Comment by gallantdon** [comment]
@mikezimm I copied a manifest from another web part in the solution, changed the last 3 characters of the ID and updated the strings to what they should be for the new web part. I have tested in 3 places so far with 100% success. Seems the issue is related to the ID or something else in the manifest that I can't find.

**Comment by mikezimm** [comment]
> @mikezimm I copied a manifest from another web part in the solution, changed the last 3 characters of the ID and updated the strings to what they should be for the new web part. I have tested in 3 places so far with 100% success. Seems the issue is related to the ID or something else in the manifest that I can't find.

@gallantdon , It's definitely related to the package-solution feature id(s) per all the previous discussions.  In the past, when the features section was not in the package-solution.json, SharePoint auto-created ids on the fly.  So all sites that had the solution installed prior to the update, had the auto-generate Ids.  Then if you add Ids in per the CLI, you are now adding your own Id to the updated package which is likely different than the one SharePoint randomly generated.... hence the issue.

In my case, I've spent way to many hours chasing ghosts with it working in some cases and not working in others (for the same web part/solution).  So if you are comfortable with your testing then glad to here it's working.

**Comment by AJIXuMuK** [comment]
The CLI will be updated to provide corrected instructions.
