### ISSUE TITLE
Missing part of the office theme in Microsoft Teams

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#8434]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Microsoft Teams (browser and the application).

### Describe the bug / error

After switching from Viva to other teams app and coming back, part of the office theme is not loaded which causes PnP controls to crash. At least 'roundedCorner2' is missing.
![image](https://user-images.githubusercontent.com/6162213/190365687-b09b3b33-930e-4da2-8410-38737889b25a.png)

https://user-images.githubusercontent.com/6162213/190365726-8ab275a5-217d-4268-b122-12f7c20b6f31.mp4

### Steps to reproduce

1. Open intranet in Viva
2. Switch to other app (e.g. chat)
3. Go back to Viva

### Expected behavior

The SPFx context and theme should be correctly initialized.

**Comment by AJIXuMuK** [comment]
@siata13 - thanks for reporting this one!
Few questions:
- do you have `initializeIcons` called somewhere in the root of the files (outside of any methods/classes)?
- Do you have code to apply theme directly in the controls?

**Comment by AJIXuMuK** [comment]
@siata13 - also if you have some test environment where we can repro it - please share it with me (aterentiev@microsoft.com)

**Comment by siata13** [comment]
@AJIXuMuK - sorry for late answer.
- I didn't find any code that calls `initializeIcons ` in our code. Not sure if it is used somewhere in PnP controls.
- There is no code that loads / applies the theme in the control
- The environment is a customers one and I do not have a direct access - what is super strange, it happens only in some tenants.

**Comment by AJIXuMuK** [comment]
@siata13 - am I correct that this is a custom "Viva" app (you've provided your own manifest).
Not out of the box app?

**Comment by siata13** [comment]
Will talk to the customer and come back to you with an answer.
Thanks!

**Comment by siata13** [comment]
In both cases it is rebranded Viva connections app.

**Comment by c-eiser13** [comment]
I'm having this same issue in my company tenant, dev tenant and in customer tenants. Our setup is, home site is configured for Viva connections, and the homesite has an app customizer that creates a navigation menu, and there are custom SPFx web parts on the page as well. When we go into teams and into viva connections, everything loads correctly and icons are visible. If I click on any option on left nav, chat for example, then click back into viva, the icons (Fluent UI) are gone, until I reload the page. I'm also not calling initializeIcons, or applying a theme to these controls in particular.

First load of Viva:
![image](https://user-images.githubusercontent.com/42096464/217857732-18ba6db4-1056-428e-a067-ea1886110a6d.png)

Click into chat, then back into Viva:
![image](https://user-images.githubusercontent.com/42096464/217857955-2ff76046-e62f-415a-9471-f1b0a75059ec.png)

This happens in both browser version of Teams and Desktop version. I can repro in a dev tenant as well if that helps troubleshoot.

**Comment by johnguy0** [comment]
Thank you for opening this issue. Closing since this is not an issue directly with SPFx, but we have opened a bug for the product team.
