### ISSUE TITLE
How to debug and step into code from dependencies

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/sp-dev-docs#8438]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Microsoft Edge 105.0.1343.33 64 Bits
- SPFx version : 1.15.2
- Node.js version : 16.17.0
- etc

### Issue description

I'm working on a large application that contains both SPFX project, Teams and Outlook addons and shared libraries.

The shared libraries are not SPFX libraries but standard typescript projects, packed using rollup (because of needs to support CSS modules, among other), because the libraries may be used outside SPFX project.

At run-time, everything works as expected in the SPFX project. The webpack bundler properly bundles the shared libraries into the SPFX output.

However, I didn't find a way to debug the SPFX project AND the libraries. The library emits ESM modules and source-maps, but the SFPX bundles does not understand it.
What I understand is that the webpack bundler will take the transpiled library and include it in the final bundle ignoring source-maps.

This results in the debugger, to have source-maps that map the JS code from the final bundle to the transpiled JS, not the TS.
There is actually two layers of transpilation/bundling.

This is very frustrating because large projects are hard to work with using SPFX.

Thanks for the help

**Comment by AJIXuMuK** [comment]
@stevebeauge - we don't load source maps from dependencies for performance reasons.
But you can [modify web pack config](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline) to load them.
It will probably lead to increased build time so I would do that based on some parameter.
