### ISSUE TITLE
link for NodeJS releases broken

### ISSUE THREAD

**Issue by bforsyt4** [SharePoint/sp-dev-docs#8441]
link for NodeJS releases is broken: https://nodejs.org/en/about/releases/
maybe link to?: https://nodejs.org/en/download/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
The link wasn't broken, and the doc was pointing to the about page, not the download page, which was intended. The text in the doc said "to learn more about LTS..." which is why it pointed to the about page. No change is required.
