### ISSUE TITLE
 Applying Field Customizer Leads to Empty Cells in Teams Files Tab

### ISSUE THREAD

**Issue by VelinGeorgiev** [SharePoint/sp-dev-docs#8450]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Firefox Latest
- SPFx version: 15
- Node.js version: 14.2

### Describe the bug / error

If you apply SPFx Field Customizer to any column in Documents Library, the column will have empty cells in Teams Files Tab:
SharePoint
![This is an image](https://user-images.githubusercontent.com/17036219/76339934-05db8b00-62b8-11ea-915c-d8a994f83ce2.png)

It's a duplicate of a closed one: https://github.com/SharePoint/sp-dev-docs/issues/5438

### Steps to reproduce

1. Follow the guide for creating a field customizer https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer
2. Deploy the field to Teams Site Document library
3. Add values to the Field
4. Open Microsoft Teams Files Tab
5. The Field Customizer is missing.

### Expected behavior

Field Customizer to work in the MS Teams Files Tab.
List Custom Action to work in the MS Teams Files Tab.

**Comment by AJIXuMuK** [comment]
@VelinGeorgiev - unfortunately, we needed to revert the changes. 
Working on a new plan for that.

**Comment by VelinGeorgiev** [comment]
Hey Alex (@AJIXuMuK), thanks for the quick reply! Would you mind sending a line of text here if you get any insights on this in the future? Appreciate it. Thanks!

**Comment by h3nn3** [comment]
Hello any updates on this problem ?

**Comment by AJIXuMuK** [comment]
@h3nn3 - no updates.
As mentioned before, we will update the thread as soon as there is any information

**Comment by PzKfWg** [comment]
Any hope that this might some day be solved? Customization of SharePoint document libraries should surely apply to Teams Files tab as well...

**Comment by AJIXuMuK** [comment]
Sorry for being silent.
The issue has been fixed but not in the way you probably expected.
In Teams the columns with Field Customizer applied will render using default renderer.
So, the user will not see empty cells but will not see SPFx customizations.

We have a backlog item to activate SPFx extension is lists/files in Teams.
But there is no ETA or even commitment on that.

**Comment by PzKfWg** [comment]
Thanks for the reply. My issue is about ListView Commands, so I suppose this is not activated and in the backlog?
