### ISSUE TITLE
Adding to the giant misunderstanding of what is Teams and what is Sharepoint

### ISSUE THREAD

**Issue by TTWill** [SharePoint/sp-dev-docs#8451]
Says on Google: [Tutorial: Build meeting apps for Microsoft Teams with SPFx](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-meeting-app)

No, this is about building a Sharepoint app and adding the SP page to teams, and there are already 50 tutorials about how to do that. What we ARE looking for, is how to build a Teams app - an app running inside Teams - utilizing SPFx, Graph or both, or rather: A modern version based on the modern ways of writing React app's.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: febc0dc5-5d17-c525-a31d-8f7a08d96dd9
* Version Independent ID: bb421dac-410c-4d7e-cb87-d785934b7ba7
* Content: [Tutorial: Build meeting apps for Microsoft Teams with SPFx](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-meeting-app)
* Content Source: [docs/spfx/build-for-teams-meeting-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/build-for-teams-meeting-app.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@TTWill - your statement is not completely valid.
You are creating a SharePoint Framework app (web part). By its nature it is hosted using SharePoint infrastructure.
But it is a valid Teams app with it's own manifest.
You're not adding some SharePoint page as a Teams app.

Yes. your web part is loaded from teamshostedapp.aspx. But you can compare it with your own SPA where you have some initial html page that loads needed scripts and renders you main component.

**Comment by TTWill** [comment]
> You are creating a SharePoint Framework app (web part)

Yes, that is indeed one way of doing it.

> By its nature it is hosted using SharePoint infrastructure.

I would like to challenge that idea.

Look at this sample here: https://github.com/OfficeDev/TeamsFx-Samples/tree/v1.0.0/todo-list-SPFx. I can run this sample and never shift focus away from Teams. It is not the most elegant way of working with a Teams application, but it surely beats uploading my application to Sharepoint before testing it inside Teams, or am I mistaken here?

My big wish for this is though to have Graph API access out-of-the-box inside a real teams-app WITHOUT needing SSO. We have only managed to create a version running SPFx using SSO access through an Azure application-registration for debugging, and then wrapping the component on a secondary application for publication within teams (as done within the sample I provided) - because our clients probably will grow tired of needing to login while using Teams.

Or maybe it's the nature of Sharepoint? That it's not supposed to be used as a database for regular Teams app's?

**Comment by TTWill** [comment]
I think after diving deeper into the nature of SPFx, I understand your prerogative. But try to understand my POV, when I first read this article, and didn't understand much of SPFx (yet), I saw "Build meeting apps for Microsoft Teams". I did not expect SPFx to demand the app to run inside Sharepoint.

The reason is, that creating app's in teams is normally fairly simple (Such as this example https://medium.com/swlh/building-a-ms-teams-app-using-react-fluentui-82a78b3a7de7). You can make changes, and see them a few seconds later at runtime like any other React application - it is when needing the Sharepoint part, things get complicated. When you are inside Teams, you will need an SSO access to debug the application.
