### ISSUE TITLE
Teams Tab which is connected to SharePoint Page containing an SPFx component which uses AadHttpclient fails with Token Expiry

### ISSUE THREAD

**Issue by wizneeraj** [SharePoint/sp-dev-docs#8452]
Hi Everyone,

We have a Teams Personal Tab which is connected to a SharePoint Page. This page contains an SPFx app which inturn uses AadHttpclient to contact Azure Function App. The setup works most of the time, however, we have a Conditional Access policy by which they need to relogin after 1 hour (for testing). 

Due to this, whenever they use the Teams Personal Tab, the SharePoint page loads fine, however the functionality which needs to connect to Azure Function App fails with the below error message.

AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-09-22T12:41:41.2700000Z and the maximum allowed lifetime for this request is 3600.

Teams doesn't seem to renew the token which it uses to call the Azure Function App.

**Comment by lucabandMSFT** [comment]
@wizneeraj , thanks. How did you create the Teams manifest? did you use SPO App Catalog "sync to Teams"? or it is a manual manifest? If it is the latter, can you please past here the manually created manifest?

Thanks!

**Comment by wizneeraj** [comment]
Thanks for the reply @lucabandMSFT . Please find below the web part manifest and the Teams Tab manifest as well.
**Web Part Manifest**
`{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx/client-side-web-part-manifest.schema.json",
  "id": "03b625b0-3bb2-4bf5-h65d-7cd982895102",
  "alias": "ProductRequestWebPart",
  "componentType": "WebPart",

  // The "*" signifies that the version should be taken from the package.json
  "version": "*",
  "manifestVersion": 2,

  // If true, the component can only be installed on sites where Custom Script is allowed.
  // Components that allow authors to embed arbitrary script code should set this to true.
  // https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f
  "requiresCustomScript": false,
  "supportedHosts": ["SharePointWebPart", "TeamsTab"],

  "preconfiguredEntries": [{
    "groupId": "5c03119e-3074-46fd-976b-c60198311f70", // Other
    "group": { "default": "Other" },
    "title": { "default": "Product Request" },
    "description": { "default": "Self-service Solution Product Request WebPart" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "Product Request"
    }
  }]
}`

**Teams Tab Manifest**

`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "version": "1.1.0",
  "manifestVersion": "1.9",
  "id": "44fe58ff-5bd8-4fdd-9710-122956a659c7",
  "packageName": "com.package.name",
  "name": {
    "short": "Request Portal",
    "full": "Request Portal"
  },
  "developer": {
    "name": "Some Company",
    "mpnId": "",
    "websiteUrl": "https://www.somecompany.com",
    "privacyUrl": "https://www.somecompany.com/privacy-statements",
    "termsOfUseUrl": "https://www.somecompany.com/terms-of-use"
  },
  "description": {
    "short": "Request Portal",
    "full": "Request Portal"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#ffffff",
  "staticTabs": [
    {
      "entityId": "efaf3049-445a-4420-96bc-be0f2d09b441",
      "name": "Collab Request",
      "contentUrl": "https://contoso.sharepoint.com/sites/requestportal/_layouts/15/teamslogon.aspx?spfx=true&dest=https%3A%2F%2Fcontoso.sharepoint.com%2Fsites%2Frequestportal",
      "websiteUrl": "https://contoso.sharepoint.com/sites/requestportal",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "b14b1afd-6975-4c75-996c-6c1d3ccea7bf",
      "name": "Modern Workplace Tool",
      "contentUrl": "https://contoso.sharepoint.com/sites/MWPT/_layouts/15/teamslogon.aspx?spfx=true&dest=https%3A%2F%2Fcontoso.sharepoint.com%2Fsites%2FMWPT",
      "websiteUrl": "https://contoso.sharepoint.com/sites/MWPT",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "about",
      "scopes": [
        "personal"
      ]
    }
  ],
  "validDomains": [
    "contoso.sharepoint.com"
  ],
  "webApplicationInfo": {
    "id": "00000003-0000-0ff1-ce00-000000000000",
    "resource": "https://contoso.sharepoint.com"
  }
}`

**Comment by lucabandMSFT** [comment]
@wizneeraj , thanks.

looks like the "webApplicationInfo" portion of the Teams manifest is not correct. Can you please change it following the guidelines on this article? https://learn.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions

Specifically for this part: 
 Important

in the Teams app manifest ensure you add the following entry:

JSON

Copy
"webApplicationInfo": {
"resource": "https://{teamSiteDomain}",
"id": "00000003-0000-0ff1-ce00-000000000000"
}
That is required to ensure any API call in the component will succeed from Microsoft Teams rich clients. teamSiteDomain will be the same tenant that the Teams client is using, this will not work cross-tenant/cross-domain so you cannot hardcode another domain in.

**Comment by wizneeraj** [comment]
@lucabandMSFT - This is the webapplicationinfo being used. I have used contoso.sharepoint.com as an example for posting this issue. In reality, I am using my teamSiteDomain for my tenant.

"webApplicationInfo": { "id": "00000003-0000-0ff1-ce00-000000000000", "resource": "https://contoso.sharepoint.com" } }

**Comment by lucabandMSFT** [comment]
@wizneeraj , thanks.

I want to be sure tho: you don't have to use your team site domain, but instead, you have to _literarily_ use the world "{teamsitedomain}" including the "{" brackets inside the manifest.

Is that what you are doing?

Thx,
Luca
