### ISSUE TITLE
SharePointFullPage loses expand button for users without edit permissions

### ISSUE THREAD

**Issue by IvanTheBearable** [SharePoint/sp-dev-docs#8458]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.14

### Describe the bug / error

For users with edit permission, a full page web part renders with a command bar containing an Edit button and an expand/collapse button. e.g.:

![Screen Shot 2022-09-27 at 8 21 11 AM](https://user-images.githubusercontent.com/459030/192362063-383df5c4-de48-4053-9aac-f2e0365ce7c3.png)

If the user has contribute or less permissions (i.e. does not have Edit) then the command bar is not rendered at all. So there is no way to hide the header and navigation.

### Steps to reproduce

1. Create a SharePointFullPage web part and page
2. View the page as a user with read-only permissions

### Expected behavior

I'd expect the command bar to render with just the expand/collapse button. e.g.:

![Screen Shot 2022-09-27 at 8 21 11 AM](https://user-images.githubusercontent.com/459030/192363355-a4d4593b-93ef-4c00-88aa-679659ee113b.png)

Now, an API to allow custom buttons to be added to that command bar would be awesome but that's out-of scope for this ticket.

**Comment by AJIXuMuK** [comment]
The fix has been made and will be available WW in the next couple of weeks.

**Comment by AJIXuMuK** [comment]
This should be rolled out to 100% by now
