### ISSUE TITLE
Application Customizer Top should really be at the Top

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#846]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [X] Additional article idea

#### Expected or Desired Behavior
When adding Office Fabric React Components to the new Application Customizer at the Top, the customizer should really be at the top and the css should not be influenced by parent DOM Elements.

#### Observed Behavior
Currently on modern pages there are global styles applied that change the look and feel of our application customizers, because the top control is nested in several DIVs that apply global decendent styles to the customizers. This happens for example, when using office ui fabric react controls.

#### Steps to Reproduce
Add a office ui fabric react command bar with buttons and Icons to an application customizer at the top and see that it renders wrong.
![top](https://user-images.githubusercontent.com/8672900/30246704-f1160eaa-9601-11e7-930a-7d3a27252883.PNG)
![top2](https://user-images.githubusercontent.com/8672900/30246706-f62f7d22-9601-11e7-8f11-d89a6bad68a7.PNG)
![top3](https://user-images.githubusercontent.com/8672900/30246707-fa633208-9601-11e7-8e8a-2b5c716c6c9c.PNG)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
