### ISSUE TITLE
JavaScript heap out of memory errors after upgrading spfx 1.10. -> 1.14 

### ISSUE THREAD

**Issue by tista-chatterjee** [SharePoint/sp-dev-docs#8462]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version  1.14x (current) before upgrade (1.10x)
- Node.js version  14.20.0(current) before upgrade (10.22.0)

### Describe the bug / error

Upgraded spfx from 1.10(node 10.22.0) to 1.14(node version - 14.20.0) and started seeing this in my project. I have successfully upgraded the webpart components and did not face any such issue. But for the spfx extensions we are not able to bundle it, it is throwing JavaScript heap out of memory error.

**Error on running gulp bundle --ship:**
[07:29:01] Error - [tslint] <--- Last few GCs --->
[4648:000001BF13A02360]    13153 ms: Scavenge 1284.5 (1317.5) -> 1284.5 (1317.5) MB, 131.1 / 0.0 ms  (average mu = 1.000
[07:29:01] Error - [tslint] , current mu = 1.000) allocation failure
[4648:000001BF13A02360]    16119 ms: Mark-sweep 1877.5 (1910.6) -> 1835.4 (1872.9) MB, 1033.1 / 0.1 ms  (+ 9.0 ms in 8 steps since start of marking, biggest step 1.5 ms, walltime since start of marking 7136 ms) (average mu = 0.930, current mu = 0.930) all
<--- JS stacktrace --->
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
[07:29:01] Error - [tslint] 1: 00007FF697A95E4F napi_wrap+133327
 2: 00007FF697A2F446 DSA_meth_get_fla
[07:29:01] Error - [tslint] gs+63062
 3: 00007FF697A302DD node::OnFatalError+301
 4: 00007FF6983141FE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6982F8FED v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6981A27EC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6981C739F v8::internal::Factory::NewUninitializedFixedArray+111
 8: 00007FF69808C4F0 v8::Object::GetIsolate+7280
 9: 00007FF697F15B27 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+170247
10: 00007FF69839F62D v8::internal::SetupIsolateDelegate::SetupHeap+474253
11: 000003E71B86B573

**Package.json**
{
  "name": "i-portal-policy-page-command-extension",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "^1.11.0",
    "@microsoft/sp-core-library": "^1.12.1",
    "@microsoft/sp-dialog": "^1.11.0",
    "@microsoft/sp-listview-extensibility": "^1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.14.0",
    "@pnp/sp": "^2.5.0",
    "@pnp/sp-commonjs": "^2.5.0",
    "exceljs": "^4.2.1",
    "lodash": "^4.17.21",
    "log4js": "^6.3.0",
    "office-ui-fabric-react": "^7.174.1",
    "pwc-rni-independenceportal-spo-library": "1.0.92",
    "sp-pnp-js": "^3.0.10",
    "xlsx": "^0.17.0"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "@microsoft/sp-build-web": "1.14.0",
    "@microsoft/sp-module-interfaces": "1.14.0",
    "@microsoft/sp-tslint-rules": "1.14.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "4.0.2"
  }
}

**tslint.json**
{
  "extends": "./node_modules/@microsoft/sp-tslint-rules/base-tslint.json",
  "rules": {
    "class-name": false,
    "export-name": false,
    "forin": false,
    "label-position": false,
    "member-access": true,
    "no-arg": false,
    "no-console": false,
    "no-construct": false,
    "no-duplicate-variable": true,
    "no-eval": false,
    "no-function-expression": true,
    "no-internal-module": true,
    "no-shadowed-variable": false,
    "no-switch-case-fall-through": true,
    "no-unnecessary-semicolons": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-with-statement": true,
    "semicolon": true,
    "trailing-comma": true,
    "typedef": false,
    "typedef-whitespace": false,
    "use-named-parameter": true,
    "variable-name": false,
    "whitespace": false,
    "no-reserved-keywords":true
  }
}

**tsconfig.json**
{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-3.9/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env"
    ],
    "lib": [
      "es6",
      "es5",
      "dom",
      "es2015.collection",
      "es2015.promise"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": []
}

However on running, gulp bundle --max_old_space_size=8192 --ship   
we are not getting the error anymore but is this route sustainable, that is our apprehension. Please help us with this problem

### Steps to reproduce

1.Upgraded spfx to 1.14x by running the command: **m365 spfx project upgrade --toVersion 1.14.0 --output md > "upgrade-report.md"**
2. deleted node modules,did gulp clean, npm install, gulp bundle --ship --> got the error

### Expected behavior

we expected the bundle to run successfully

**Comment by AJIXuMuK** [comment]
@tista-chatterjee - your `package.json` seems not completely right.
We recommend using **exact** versions of the packages.
In your case you have this:
```json
"@microsoft/decorators": "^1.11.0",
"@microsoft/sp-core-library": "^1.12.1",
"@microsoft/sp-dialog": "^1.11.0",
"@microsoft/sp-listview-extensibility": "^1.11.0",
"@microsoft/sp-office-ui-fabric-core": "^1.14.0",
```
It means that you will actually load 1.15.2.
But in `devDependencies` you have exact versions 1.14.0.
It leads to mismatch.

Please, double-check the upgrade steps generated by the CLI and modify your output.

Please, let us know if the error exists after the fixes.
