### ISSUE TITLE
SPFX full page application stops working when user updates the extension on the site level

### ISSUE THREAD

**Issue by RafalUrbanski** [SharePoint/sp-dev-docs#8463]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome: 105.0.5195.127
- SPFx version: 1.14.0
- Node.js version: 14.19.1

### Describe the bug / error

Some clients experience an issue with the SPFx full-page application update process. Our application is available in the store, from where clients install it. When installed, the app works perfectly. From time to time, we release an update, and then we query users to update the SPFx application in the tenant's app catalog (step 1 of the following guide https://sintelapps.com/product-help-sintel-bi/how-to-update/). As soon as the admin updates the app in the tenant app catalog, all app instances get updated (it is essential to mention that users get access to the updated app even though they have not updated the app on every site collection separately).
So far, everything is OK.
Some clients then decide to go to the Site Contents page -> Sintel BI app -> Show actions -> Details and click the Get it button (it is available as the newer version is available in the tenant app catalog). As soon as they do so, our full-page application stops working - whenever we open our custom page, the app does not load, and instead, white page is visible. What makes it impossible for us to fix is that the app doesn't start to load at all - Sintel BI js files are not injected. In addition, our custom full-page app is no longer available in the New -> Page -> Apps section (the apps section is missing as this was the only custom full-page app).
We verified that our app does not work only on those sites where the app has been updated on the site collection level - if the client has four different sites with our app installed and then updates the app through the Site Contents page only on one of those sites, the app will keep working on three other sites.
While investigating the issue, I noticed that whenever we open the New -> Page section from the home page of the SharePoint site, a call is being made to the '_api/SP.Publishing.SitePageService.GetAvailableFullPageApplications' endpoint. In the case of sites where the app keeps working, we get a response containing 17 entries, out of which one is related to our custom app. However, the same request executed from the 'broken site' (one where the app does not work) returns an empty array (entries for both custom apps and OOB apps are missing).
This behavior is not consistent across all the clients, but we have experienced it three times so far. Reinstalling the app within the tenant app catalog seems to fix the issue, but it cannot be applied everywhere, as some clients cannot freely install/uninstall apps on their tenants.

### Steps to reproduce

1. Install the Sintel BI app (from the Store) on a single site collection
2. Update the SPFx full page application within the tenant's app catalog (newer version than installed must be available)
3. 'Upgrade Store App' from the ribbon
4. Visit the site where the app is installed (it should work so far)
5. Go to the Site Contents page -> Sintel BI -> Details -> click the Get It button
6. The app no longer works

### Expected behavior

Whenever user updates the app through the Site Content's page, app works as usual

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - what changes to `package-solution.json` did you make between 2 versions: one initially installed and the one uploaded later?
Were you updating from SPFx <1.14 to SPFx >=1.14 using CLI?

**Comment by RafalUrbanski** [comment]
@AJIXuMuK Yes, we have updated SPFx version somewhere in between those two versions

**Comment by AJIXuMuK** [comment]
@RafalUrbanski - and I assume you've added `features` property into your `package-solution.json`.
Please, take a look at this issue: https://github.com/SharePoint/sp-dev-docs/issues/8359

**Comment by RafalUrbanski** [comment]
@AJIXuMuK I read the other article  and as far as I undestand, I should do one of those things:
- remove the features section from the package-solution.json and publish the app again
- keep the features section, but then I have to install the app again on that site ('This feature will not be activated unless you do Add an app again.')
Did I understand the second option correctly? If so, I did try to remove the app on the broken site, removed it from both recycle bins and even reactivated related feature manually, but nothing worked.

**Comment by RafalUrbanski** [comment]
@AJIXuMuK I performed few tests and it seems that removing features property is the only solution. Thank you very much for pointing this out!
As the features property causes the problem while upgrading, shouldn't CLI be updated to not add this property in some cases?
