### ISSUE TITLE
SharePoint rest api for Pages and events

### ISSUE THREAD

**Issue by jainshri** [SharePoint/sp-dev-docs#8464]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I am looking for rest apis to create Pages and events in sharepoint Online and oprem version , Could you please help me with the same. So far not able to get anything in the Documents for Pages

**Comment by bcameron1231** [comment]
Events can be created/modified using the standard SharePoint REST API or with Graph (in SPO)
https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest
https://learn.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0

Pages are a bit more complex. On-Premises, no API exists for working with pages. In SPO, AFAIK, I don't believe a SharePoint REST API exists directly. Microsoft Graph is working on a Page API, which is currently in Beta.
https://learn.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta
