### ISSUE TITLE
Request to clarify

### ISSUE THREAD

**Issue by NetrixDES** [SharePoint/sp-dev-docs#8469]
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#granted-permissions-apply-to-all-solutions - is this guidance only meant to apply to SpFx solutions that leverage default project settings, or does it apply to isolated web parts that request additional permissions as well? I would think just the former, but the way the documentation is currently worded implies the latter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47b09a1d-5520-82e2-64f5-7aaae817720a
* Version Independent ID: 0e3dcdc4-3a49-b4c7-f525-1c618cf5e21e
* Content: [Connect to Azure AD-secured APIs in SharePoint Framework solutions](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient)
* Content Source: [docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
It only applies to the first. Web Parts using a single Azure AD Application ("SharePoint Online Client Extensibility") for the permission you grant it. So any standard Web Part in your organization could re-use existing permissions that have been granted.

Isolated Web Parts actually create and use a completely separate Azure AD Application for that specific web part. See more information here https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts

Hope this helps.
