### ISSUE TITLE
SPFX Extension ListViewCommandSet - command title not translating based on locale

### ISSUE THREAD

**Issue by thaeddavid** [SharePoint/sp-dev-docs#8471]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- MS Edge browser - version 105.0.1343.53 
- SPFx version - "@microsoft/sp-core-library": "1.15.2"
- Node.js version - v16.16.0

### Describe the bug / error

I have created a custom ListViewCommandSet to add a new button to SharePoint Online Document Libraries. 

I am successfully using the localisation options to translate text within the Dialog prompt that gets displayed once the button is clicked.

However the actual text of the button does not switch when changing the locale that I'm using e.g. when I run:
gulp serve --locale=fr-ca

To set the translation for the button text, I have changed the manifest file to have both a default and locale set in the title property:
  "items": {
    "COMMAND_1": {
      "title": { "default": "Restore items", "fr-ca": "Restaurer les éléments" },
      "iconImageUrl": "data:image/png;base64,imagecodehere",
      "type": "command"
    }

The documentation doesn't mention if this works the same as SPFX web parts. Is this a bug with ListViewCommandSet or is it just not possible?

### Steps to reproduce

1. Create a ListView Command Set as per the documentation - https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api
2. Change manifest file to have a translated title e.g.  "title": { "default": "Restore items", "fr-ca": "Restaurer les éléments" }
3. gulp serve to that locale e.g. gulp serve --locale=fr-ca
4. Observe that the button text still shows the default option

### Expected behavior

Expected the manifest title property to have translation functionality.

**Comment by thaeddavid** [comment]
Has this been confirmed as a bug? I noticed the only change to this issue is that the tag "area:spfx" has been added, shouldn't this be "area:spfx-extensions"?

**Comment by AJIXuMuK** [comment]
@thaeddavid - sorry for the silence.
It is most probably a bug, but we had no change to dig into it yet.
For the ares: I would leave it to our team to specify needed areas.

**Comment by AJIXuMuK** [comment]
@thaeddavid - after reading it deeper I can say it's not a bug.
`--locale` parameter affects what localization strings from the package will be loaded.
If you want to apply localized title use `forceLocale=` query string parameter.

**Comment by thaeddavid** [comment]
@AJIXuMuK  I just tested this, and while all the out of the box list view commands get translated when using the forceLocale property, my custom button doesn't.  This also works fine for my custom SPFX web part titles, but not for list view commands from an SPFX Extension.

**Comment by AJIXuMuK** [comment]
@thaeddavid - I've also tested it before posting the response.
And it does work.
Maybe it's some kind of cache. Try to rebuild the solution, restart debugging session and force refresh the page.
<img width="241" alt="Screenshot 2022-11-02 at 9 20 40 AM" src="https://user-images.githubusercontent.com/17036219/199501001-c2ec91b6-ee0a-40ff-86f1-422f3ab90617.png">
<img width="342" alt="Screenshot 2022-11-02 at 9 23 48 AM" src="https://user-images.githubusercontent.com/17036219/199501004-18a42a49-360c-4913-a0ea-55f0425536a8.png">

**Comment by thaeddavid** [comment]
@AJIXuMuK Thanks so much for spending time on this and responding to my questions.

I had cleared my cache and confirmed this by changing some of the text in the button to see it change. 

In your screenshot, the main button text still says "Approve document" in English. The reason I bring this up is because most of the text in my extension is translating correctly (e.g. the popup text that gets shown when clicking on the button), but the actual button itself isn't being translated. I believe this text is driven from the manifest and not the locale files. Are your manifest translations working? If so it must be an issue with my code.

**Comment by AJIXuMuK** [comment]
@thaeddavid - "Approve Document" is from another command set that has no localized string :)
