### ISSUE TITLE
cannot add webpart to site

### ISSUE THREAD

**Issue by artxach** [SharePoint/sp-dev-docs#848]
Recently i got updated my config manifest to version 2.
After that when i `package-solution` and upload it to the _app catalog_, it is just added and not deployed(Deployed column value is - No). Also i don't get any trust window.

After that i want to to add the webpart to my site, but it is not available under _Apps from your organization_ . Also i don't see any _features_ in the web features.

**Comment by waldekmastykarz** [comment]
Does the column _Valid App Package_ for your package say _Yes_ and the _App Package Error Message_ column say _No errors_?

**Comment by artxach** [comment]
exactly. only _Deployed_ column shows _No_. 

I found the reason - when i upload the package within ## SharePoint Classic Experience view, everything works great - i get _Trust window_, and after trusting it gets ## deployed. But when i am in **Modern** view, it just uploads the package and **doesn't deploy** it.

**Comment by waldekmastykarz** [comment]
Right, this issue sounds very familiar, but perhaps should be made more explicit in the documentation. Good to hear you figured it out!
