### ISSUE TITLE
AAD Apponly when using SPO API like csom and REST

### ISSUE THREAD

**Issue by mustaqp** [SharePoint/sp-dev-docs#8480]
[Enter feedback here]
AAD Apponly for SPO APIs (REST, CSOM) only works with certificate and not with clientsecret. No-where in any of the MSDN Documentation, this is mentioned. If a note can be put in all the documentation related to Apponly AAD Apps. It will be greatly help our customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e082eb56-fafb-9ef7-fadb-e0b90f5369a9
* Version Independent ID: 0f1a3528-3615-5722-2352-a1ad4622c244
* Content: [Granting access via Azure AD App-Only](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)
* Content Source: [docs/solution-guidance/security-apponly-azuread.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azuread.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi, if you view the page that you linked... down at the bottom there is any FAQ which addresses this question. If you search for "_Can I use other means besides certificates for realizing app-only access for my Azure AD app_"

https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#can-i-use-other-means-besides-certificates-for-realizing-app-only-access-for-my-azure-ad-app
