### ISSUE TITLE
Functionality to add app in one place and access in all web

### ISSUE THREAD

**Issue by craghavendra21** [SharePoint/sp-dev-docs#849]
#### Category
- [x] Question

#### Expected or Desired Behavior
My clients want my SPFX web part in many sub sites. For this, I have to add the app to each subsite. Is there a way to add the SPFX web part app at the top level and I should be able to add web part of that app in all subsite. something like global access.

Please help me with this whether it is possible or not.

#### Observed Behavior
Need to add the SPFX Webpart App at each site or subsite where we need to access the web part.

**Comment by waldekmastykarz** [comment]
The latest version of the SharePoint Framework supports tenant-scoped deployment. You can find more information about it here: https://dev.office.com/sharepoint/docs/spfx/tenant-scoped-deployment. Would that be sufficient for your scenario?

**Comment by craghavendra21** [comment]
Hi, Thank you for the reply.
This look like it will work for me. But I was deploying my solution with CDN's path. My site collection library as CDN path. So In tenant-scoped deployment, how to manage the CDN's.
And I used to put the js and JSON files from temp/Deploy folders to CDN Folder. With tenant-scoped deployment, this step is removed? if not then how to do it? Please help me with this.
Thanks in advance.

**Comment by waldekmastykarz** [comment]
The deployment process is the same. The only difference is, that after deploying the .sppkg file to the App Catalog, your web parts automatically become available in all sites. Using the tenant-wide deployment, you no longer have to manually install the app with your web part on each site.

**Comment by russgove** [comment]
Also the sitecollecton app catalog should be coming sometime soon. The question is, if you deploy an app to the site collection app catalog, willl it be available in all sub sites. i imagine it would  looking forward to announcement at ignite!

**Comment by mcmynn83** [comment]
@russgove - when we eventually fix the site collection app catalog and release it, a "tenant wide" web part will be available in all sub sites and only on the site collection.

@craghavendra21 - You will have to use an external CDN for this scenario which is accessible by everyone for now.  We understand your feedback and we are looking into the best way to solve this problem for all SP users.
