### ISSUE TITLE
New page template selection styling

### ISSUE THREAD

**Issue by erkanch** [SharePoint/sp-dev-docs#8490]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Is there a supported way of styling the template options during new page creation? The current design looks good only for templates with very short names. Others cover the preview image.
![image](https://user-images.githubusercontent.com/55555837/194724629-bc861e6b-e1f8-4e75-9673-3d488142d578.png)

**Comment by VesaJuvonen** [comment]
There's unfortunately currently no control settings for this page and not aware of any plans in the future.
