### ISSUE TITLE
Excel API issues - Delays in response time

### ISSUE THREAD

**Issue by vaikuntha1** [SharePoint/sp-dev-docs#8499]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Issue description -

**Case 1 - Delay in POST call execution**

POST Call: https://graph.microsoft.com/v1.0/me/drive/items/{{workbookId}}/workbook/worksheets/{{worksheetId}}/{{range}}

Data sent - newdata1 newdata1 newdata1 newdata1

{
   "rowid": 7,
   "row1": "newdata1",
   "row2": "newdata1",
   "row3": "newdata1",
   "row4": "newdata1",
   "response.@odata.context": "https://graph.microsoft.com/v1.0/$metadata#workbookRange",
   "response.@odata.type": "#microsoft.graph.workbookRange",
   "[response.@odata.id](mailto:response.@odata.id)": "/users('vaikuntha%[40companyhub.com](http://40companyhub.com/)')/drive/items('94562A6AF1EA5058%21113')/workbook/worksheets(%27%7B00000000-0001-0000-0000-000000000000%7D%27)/range(address=%27A7:D7%27)",
   "response.address": "Sheet1!A7:D7",
   "response.addressLocal": "Sheet1!A7:D7",
   "response.columnCount": 4,
   "response.cellCount": 4,
   "response.columnHidden": false,
   "response.rowHidden": false,
   "response.numberFormat||": "General",
   "response.columnIndex": 0,
   "response.text||": "newdata1",
   "response.formulas||": "newdata1",
   "response.formulasLocal||": "newdata1",
   "response.formulasR1C1||": "newdata1",
   "response.hidden": false,
   "response.rowCount": 1,
   "response.rowIndex": 6,
   "response.valueTypes||": "String",
   "response.values||": "newdata1"
}

Data sent - newdata12 newdata12 newdata12 newdata12

 {
   "rowid": 7,
   "row1": "newdata12",
   "row2": "newdata12",
   "row3": "newdata12",
   "row4": "newdata12",
   "response.@odata.context": "https://graph.microsoft.com/v1.0/$metadata#workbookRange",
   "response.@odata.type": "#microsoft.graph.workbookRange",
   "[response.@odata.id](mailto:response.@odata.id)": "/users('vaikuntha%[40companyhub.com](http://40companyhub.com/)')/drive/items('94562A6AF1EA5058%21113')/workbook/worksheets(%27%7B00000000-0001-0000-0000-000000000000%7D%27)/range(address=%27A7:D7%27)",
   "response.address": "Sheet1!A7:D7",
   "response.addressLocal": "Sheet1!A7:D7",
   "response.columnCount": 4,
   "response.cellCount": 4,
   "response.columnHidden": false,
   "response.rowHidden": false,
   "response.numberFormat||": "General",
   "response.columnIndex": 0,
   "response.text||": "newdata12",
   "response.formulas||": "newdata12",
   "response.formulasLocal||": "newdata12",
   "response.formulasR1C1||": "newdata12",
   "response.hidden": false,
   "response.rowCount": 1,
   "response.rowIndex": 6,
   "response.valueTypes||": "String",
   "response.values||": "newdata12"
}

As you can see, both datasets have been added to the same row (row id-7). Based on our internal troubleshooting, it seems like this is caused because the data received by Excel is delayed, i.e. the data is received after a delay and hence values are overridden. Also, in the case of multiple requests (like 3–4 requests/second), the data is missed for some of the calls, or in some cases, the data gets overridden.

**Case 2 - Delay in GET call**

We are receiving data from the trigger with a huge delay which can be up to 30 minutes. Due to this, there have been cases of missed data while receiving the details.

Endpoint :
[https://graph.microsoft.com/v1.0/me/drive/items/{{workbookId}}/workbook/worksheets/{{worksheetId}}/usedRange?$select=text](https://graph.microsoft.com/v1.0/me/drive/items/%7B%7BworkbookId%7D%7D/workbook/worksheets/%7B%7BworksheetId%7D%7D/usedRange?$select=text)

### Steps to reproduce

1. For Case 1 describe above, You can send multiple requests within a second via API.
2. For Case 2 describe above, You can create multiple records within a second in Excel.

### Expected behavior

It should work smoothly without any delay and the bulk data sent (example 4 - 5 records) within a span of 1 second should not be missed or looked over by Excel.

**Comment by andrewconnell** [comment]
If this is an issue with the Excel API, and you're using MS Graph, then this is the wrong repo to post the issue. This is for SP development issues.

**Comment by AJIXuMuK** [comment]
not related to SP dev
