### ISSUE TITLE
Misleading Windows prerequisites in documentation

### ISSUE THREAD

**Issue by ronaldborman** [SharePoint/sp-dev-docs#85]
On the Wiki page 'Setup your machine' under 'If you are using a PC' it says:
"You need to install a couple more things - Visual Studio and Python".

Imho you only (have to) install part of Visual Studio, the Microsoft Visual C++ Build Tools. I suggest to rephrase this sentence, because a casual reader could conclude that Visual Studio as an IDE is a prerequisite.

**Comment by chakkaradeep** [comment]
I just verified and it says "If you are using Visual Studio"...

May be someone edited as I saw, not sure, but it is fixed :)

**Comment by ronaldborman** [comment]
The "If you are using Visual Studio" part was already there. But it is the earlier sentence "You need to install a couple more things - Visual Studio and Python" that causes confusion imo (if you put the emphasis on 'need to').

After you read the "if you are using Visual Studio" part, there is a contradiction ('need to...' <-> 'if you are using...'). Wouldn't it be better to change the first sentence to something like "You need to install a couple more things - Visual C++ Build Tools and Python"?

**Comment by chakkaradeep** [comment]
Thanks. I just left it to "You need to install the following". That is followed by windows-build-tools and then If you are using VS - I think it is better now (?).

**Comment by ronaldborman** [comment]
That will work also, I will close this issue. Thanks!

**Comment by ronaldborman** [comment]
That will work also. Thanks!
