### ISSUE TITLE
webApiPermissionRequests: Property `resource` does not map to a unique identifier within AAD

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-dev-docs#8501]
At the moment we are developing a multi-tenant application and are facing an issue with the current flow on how API Permissions can be requested. We created an app, e.g. "Fantastic SharePoint App" and the customer of ours has an app of his own with the same name: "Fantastic SharePoint App". We are not able to get the permission request to complete. Our App is not identified. It's just the customers app. 

We did some additional testing on our own tenant and did create multiple Apps with the same name. This will cause a total mess. The newest app will be picked. 

The documentation is unclear in this regards, as the documentation for a single tenant app states, that only the display of an app can be used. The display name of an app within AAD is not a unique element nor the key of the application. This will always cause an issue. See: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application

@andrewconnell did mention, that during the preview phase the ID was a valid option and got removed in favor of the display name. https://github.com/SharePoint/sp-dev-docs/issues/5026#issuecomment-566979002 

This section https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant#request-permissions-to-the-enterprise-api still provides the (supposedly no longer valid) information

>The value of the resource property refers to either the name or the ID of the Azure AD application used to secure the API.

What would be the best approach to have a unique identifier for the property `resource` and are there any changes planned? 

Contrarily to the permission request, the aadHttpClientFactory is initialized with either the URL or the GUID of the API. 

```typescript
this.context.aadHttpClientFactory
        .getClient('https://contoso-api.azurewebsites.net')
```

In this step a unique element is used...

cc: @VesaJuvonen 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ecbbb69a-f2dd-ed42-d887-14a72494000f
* Version Independent ID: 7e5c254a-fd12-0fc6-fc7d-61f4ef009226
* Content: [Consume multi-tenant enterprise APIs secured with Azure AD in SharePoint Framework](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by lucabandMSFT** [comment]
@andikrueger , thanks for your feedback.
Right now name is the only supported value for consuming AAD protected APIs. I've modified the article the ensure there's no more misunderstanding on the current behavior.

I will also track this as a potential request for future improvements on SharePoint Framework.
