### ISSUE TITLE
@microsoft/sp-page-context lib not published

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#8509]
### Target SharePoint environment

SharePoint Server Online
### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

The package `@microsoft/sp-page-context` specifies `"module": "lib/index.js"`, but `lib` is not published - it's probably ignored in `.npmignore`. See [@microsoft/sp-page-context](https://unpkg.com/browse/@microsoft/sp-page-context@1.16.0-beta.1/)

This breaking change happened between version `1.12.1` and `1.13.0`.

### Steps to reproduce

1. [@microsoft/sp-page-context](https://unpkg.com/browse/@microsoft/sp-page-context@1.16.0-beta.1/)
2. Check `package.json`
3. There is no `lib/index.js`

### Expected behavior

`lib` should be included for a valid `module` field.

**Comment by AJIXuMuK** [comment]
@johannes-z - `main` is specified as `lib-commonjs`, `typings` are from `dist`.
Why do you need `module`? We're not in publishing it for any other library as well.

**Comment by johannes-z** [comment]
We're bundling with `vite` which throws an error as it tries to resolve the `module` specified by `package.json`. If `lib` is not published, it should not be set in `module`.

**Comment by AJIXuMuK** [comment]
@johannes-z - `module` is not part of the official `package.json` schema. It is used by some engines to ES6 modules.
But SPFx is not using ES6 yet.
So this property should be ignored.
I suppose you should configure your bundling to treat SPFx modules as ES5 modules.

**Comment by iclanton** [comment]
> We're bundling with `vite` which throws an error as it tries to resolve the `module` specified by `package.json`. If `lib` is not published, it should not be set in `module`.

SPFx components should not be bundling other SPFx components. The loader provides them at runtime. We don't support bundling with Vite, and our supported Webpack configuration automatically externalizes other components.

Your solution is likely to break in the future if you bundle Microsoft-provided SPFx component libraries.
