### ISSUE TITLE
Error when deploying SPfx extension to First Release tenant

### ISSUE THREAD

**Issue by DeclanColman** [SharePoint/sp-dev-docs#851]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
According to [https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes---Extensions-RC-Drop-1.2](url)  I should now be able to deploy SPfx Extensions to our First Release Tenant.

#### Observed Behavior
I followed the tutorials and created a HelloWorld application extension. I tested it in debug mode, serving from localhost  and it worked just fine.
However, when I try to deploy this extension to the app catalog, I receive the following App Package error message : 

> The requested operation is part of an experimental feature that is not supported in the current environment

I have tried the 'First release for everyone' option last Thursday and waited until Friday afternoon for RC to take effect but I still got the same error when deploying. 
I then changed back to 'First Release for selected users' and waited a further 24 hours before attempting to deploy again but got the same message. 

Is there some other setting that we are missing here to enable SPfx extensions in RC?

Any help or guidance much appreciated. Thanks :)

**Comment by Brentless** [comment]
#847 May be related.  Things usually take a while to update, but I think SPFX is not quite ready for real tenants.  I dont get the error, but nothing I do can get extensions to work in our 'First release for everyone' tenant.

**Comment by DeclanColman** [comment]
Hey Brentless :) Yes I saw your issue and thought it may be related all right. I have switched between tenant wide and 'First Release for everyone' a few times and it seems to make no difference. When working with SPfx client side web parts in RC it would only work when in 'First Release for selected users', rather than tenant wide but for extensions it seems not to like either option.

**Comment by mmsharepoint** [comment]
I faced the exact same issue on a First Relese tenant which was first 'First Release for selected users'  and later I switched to 'First Release for everyone' and waited more than a weekend ...

What I did NOT check is:
Create a "Fresh" solution with Rel 1.2.0 (my was upgraded from 1.1.3).
I was wondering if I maybe missed something during the upgrade within my solution?
The test is on my list but maybe someone here already did that and can exclude that?

**Comment by Brentless** [comment]
I have, i wondered the same thing, but I was seeing the same problem with my previous version, and the same problem after doing the upgrade to the lastest, and starting fresh.

**Comment by DeclanColman** [comment]
Yes, I was also working with the latest version. It seems the problems are more widespread than I first thought. If anyone is reading this and has actually deployed an extension, it would be great to know :)
FYI I have no trouble debugging these extensions, they just wont deploy.

**Comment by mmsharepoint** [comment]
I did the check with a fresh solution in the meantime by myself. And the deployment worked no on a 'First Release for everyone'  tenant. It also worked now with my previous solution.
Unfortunately after enabling it on site collection level it does not run and I am figuring out why.
I saw this once on a DEV tenant, too, but there I figured out that I took the worng GUID for the ClientSideComponentID. This is not the case this time.
Anyway in App Catalog my extension is deployed correctly and I am not facing the above mentioned error anymore

**Comment by mcmynn83** [comment]
Thanks for your feedback and sorry for the problems.  We had issues with extensions for first release tenants at the start of this week which got fixed.  It is true that you have to have First Release for everyone in order to work with extensions.   Since your first release problem seems to be solved could you start a new thread with your issues about it not running after you enabled it on a site collection just to keep the two issues separate?  Thanks!

**Comment by seaSide974** [comment]
whats the status please ?

**Comment by seaSide974** [comment]
I have the header working when using debug url, then the app package deployed on first release / dev tenants do not show my header

**Comment by mcmynn83** [comment]
@seaSide974 - Sorry what is the status of what?  It sounds like you have a new issue, could you open a separate thread?
