### ISSUE TITLE
Forcing TypeScript is ridiculous

### ISSUE THREAD

**Issue by crtjr64** [SharePoint/sp-dev-docs#8514]
All of the JavaScript examples are in TypeScript with none for any other library to utilize preferred libraries such as Vuejs. This is a horrible waste of resources by Microsoft as usual
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@crtjr64 - TypeScript is not a library. It's a language. You can use [Vuejs](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/vuejs-todo-single-file-component).
