### ISSUE TITLE
After upgrade to MSGraphClientV3, "create team" response is undefined. Can't get headers. 

### ISSUE THREAD

**Issue by bva999** [SharePoint/sp-dev-docs#8515]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft Edge - 106.0.1370.47
- SPFx version - 1.15.2
- Node.js version - v14.18.3

### Describe the bug / error

After upgrade solution to 1.15.2 and upgrade to MSGraphClientV3. My code stopped working

### Steps to reproduce

```
public async createTeam(teamName: string, description: string, ownerEmail: string): Promise<ITeamCreateResult> {
    return new Promise<ITeamCreateResult>((resolve, reject) => {
      this._context.msGraphClientFactory.getClient('3').then((client: MSGraphClientV3): void => {
        client.api("/teams").post(
          {
            "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
            "visibility": "Private",
            "displayName": teamName,
            "description": description,
            members: [
              {
                "@odata.type": "#microsoft.graph.aadUserConversationMember",
                "user@odata.bind": `https://graph.microsoft.com/v1.0/users/${ownerEmail}`,
                "roles": ["owner"]
              }
            ]
          }, (error, response: any, rawResponse?: any) => {
            if (error) {
              console.log(error);
              reject(error);
            }
            console.log(response);
            console.log(rawResponse);
             client.api(rawResponse.headers.get("location")).get().then((addResult) => {
                   resolve({ id: team.id });       
            });
          });
      });
    });
}
```
`rawResponse` is `undefined`. This code worked before the upgrade

### Expected behavior

`rawResponse` is `undefined`. This code worked before the upgrade. But team is created.

**Comment by AJIXuMuK** [comment]
@bva999 - unfortunately, that is not something we control.
The parameters for the callback are returned by MS Graph SDK itself: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/9441382f7963fa782cd30a103af2632d7585e0a0/src/GraphResponseHandler.ts#L164

Here is the thread you can check out to get a raw response and headers: https://stackoverflow.com/questions/66435746/how-to-get-a-response-headers-using-microsoft-graph-api
