### ISSUE TITLE
SPFx 1.15 - Getting error when use form customiser to view/edit/new - in Australia East Region

### ISSUE THREAD

**Issue by harinvp** [SharePoint/sp-dev-docs#8516]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I deployed a Form customiser and associated component Id to the content type for new, edit and display. After that, getting the below error while trying to create a new item/edit an item/view an item.
![image](https://user-images.githubusercontent.com/25250424/197087127-e70599a0-e84a-4249-9212-08c8409d3316.png)

Before associating content type, the form works without any issues on debug mode (gulp serve). But after content type association, getting the same error in debug mode.

Looks like an issue with Form customiser in our region, which is Australia East.

I saw a similar issue reported with classic mode before(
https://github.com/SharePoint/sp-dev-docs/issues/8272). But this issue exists even in modern view.

Could you please have a look and help to get this fixed

### Steps to reproduce

1. Create a SharePoint List and associate a content type
2. Create a Form customiser extension and deploy to the SharePoint site.
3. Test the customiser in debug mode to see everything works alright
4. Update either or all of the NewFormClientSideComponentId ,  EditFormClientSideComponentId , DisplayFormClientSideComponentId  of the  content type to the component id of the Form customiser component.
5. Test the customiser in debug mode and it will not work
6. Check the New/Edit/Disp form of the list and it will not work.

### Expected behavior

The form loads up both at the list form level and in debug mode after associated to content type

**Comment by harinvp** [comment]
Updated screen shot with correlation ID
![image](https://user-images.githubusercontent.com/25250424/199877863-458ae4ca-8369-4b0d-a0de-10b7740e9547.png)

**Comment by AJIXuMuK** [comment]
Hello @harinvp,
Sorry for the long delay!

Could you provide more details?
I've just tested simple form customizer and it's working perfectly in Australia tenant. Both when deployed in production and debug modes.

Are you installing it to tenant app catalog or site collection app catalog?
Are you using it with list or document library?
Are there any properties assigned to the form customizer?
What approach are you using to set the properties of the content type?
