### ISSUE TITLE
SPFx Extension onInit Method not triggered on Site Contents pages any more

### ISSUE THREAD

**Issue by vladschiop** [SharePoint/sp-dev-docs#8520]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Lates Chrome version
- SPFx version: 1.4.1 
- Node.js version: 8.9.0

### Describe the bug / error

I have a product that includes a SPFx Extension that should run on all pages from a site collection.
Suddenly, the **onInit** method of the **BaseApplicationCustomizer** stopped triggering on Site Contents pages of any site Collection. On any other page, even system pages, the method is triggered as expected.

We are using SPFx 1.4.1, due to compatibility reasons with SP 2019.
The issue started on 16 Oct 2022, that was caught by our automated tests for the first time.
This is happening on the same version of our product which was working properly prior to 16 Oct 2022.

Any idea what could be causing this issue? 

### Steps to reproduce

1. A SPFx extension has been deployed on my site collection
2. I have a custom class that extends BaseApplicationCustomizer where I override the onInit method
3. Once I get to any SharePoint Page where the Extension has been installed, this onInit method will be triggered, hence I continue my logic
4. Since 16 October 2022, this method is not triggered anymore on Site Contents pages

### Expected behavior

The onInit method of the extension was triggering properly on Site Contents pages previously to 16 Oct 2022 properly on the same version of the product.

**Comment by AJIXuMuK** [comment]
will be tracked in #8550
