### ISSUE TITLE
Use Sites.Selected with delegated permissions

### ISSUE THREAD

**Issue by fedo911** [SharePoint/sp-dev-docs#8523]
Is there any reason why Sites.Selected is not available with delegated permissions but only with application permissions?
From our perspective, this would be highly desirable from a security standpoint. Maybe there is a different solution already that we don't see, so any hints will be welcome.

Use case: 
We have a C# desktop (tray) app that synchronizes contents from a single SharePoint site to the local machine. We need to use delegated permissions because some users are allowed to write, some others are only allowed to read. As the user will have access to more than this one site, the app will have the same. If a locally cached token gets stolen (we need to cache tokens because we can't keep asking the user for credentials all the time), an attacker would unnecessarily get access to a lot more than required by the app. This risk could be mitigated by combining Sites.Selected and delegated permissions.

**Comment by fedo911** [comment]
@CallumCrowley If I'm not mistaken with AllSites.Write would also give the app permissions to all sites the user has access to. From a security standpoint it would be much better, though, if the app had only access to the sites it needs access to (in our case a single site), not all sites the user has access to.

**Comment by CallumCrowley** [comment]
@fedo911 if that's the case, you would instead use the Sites.Selected app permission and configure the permission to only that one site. The purpose of Sites.Selected is to restrict app permissions to specific sites.

**Comment by fedo911** [comment]
@CallumCrowley I need both, though. I need to have users with different permissions (some may write, some others may only read), but all users should only ever get access to a single site though the app...

**Comment by CallumCrowley** [comment]
@fedo911 using Sites.Selected, the app would be carrying out requests for the user anyway? Wouldn't it be able to decide whether it should or shouldn't carry out the request based on the current user?

Using delegated permissions, I appreciate you wouldn't want the app to access other sites the user has access to but surely that is only a concern if an attacker has somehow breached the application's runtime? Is this the concern?

**Comment by fedo911** [comment]
The concern is indeed that someone might hijack the app or steal a token. It's an unlikely scenario, sure, but security doesn't go well with statistics, a single case can ruin it all.

**Comment by CallumCrowley** [comment]
@fedo911 fair enough, you might be better off adding a suggestion to the [Microsoft Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472).

Issues posted to this repo are mainly for issues with the documentation, though you may get an answer from a Microsoft representative.

**Comment by fedo911** [comment]
@CallumCrowley Added a suggestion to the Microsoft Feedback Portal:
https://feedbackportal.microsoft.com/feedback/idea/dc3b62e6-dc5e-ed11-a81b-000d3a7dd78c
