### ISSUE TITLE
Move To option is missing from the Site Pages library.

### ISSUE THREAD

**Issue by erkanch** [SharePoint/sp-dev-docs#8531]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Move To option is missing from a modern site's Site Pages library. There's no easy way of moving pages to a sub folder.

### Steps to reproduce

1. Create a sub folder in a modern communication site's Site Pages library. (Enable folders from advanced settings if not available)
2. Try to move a page to the sub folder.
3. Copy To is available but not Move To

### Expected behavior

Move To should be available per https://support.microsoft.com/en-us/office/move-or-copy-files-in-sharepoint-00e2f483-4df3-46be-a861-1f5f0c1a87bc

**Comment by AJIXuMuK** [comment]
@erkanch - the article you've referenced is for Document Libraries. Pages library has other content type and Move option is not available there by design: https://answers.microsoft.com/en-us/msoffice/forum/all/moving-pages-in-sharepoint-online-site-pages/a83ebb88-6ca6-4d00-87eb-e3e5be6ecb00

**Comment by erkanch** [comment]
Thanks @AJIXuMuK So, assume you have 3000 pages to manage as a content author. How do you organize the content? There should be an easier way to organize your pages.
