### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by Disc0veryX** [SharePoint/sp-dev-docs#8533]
The information about format of **ManagedPropertyMapping** is wrong. It's not `'property display name'{ property name}:' managed property'`, but `'<Current item property name>':'<Managed property name>'` now (see https://learn.microsoft.com/en-us/sharepoint/search/display-values-custom-managed-properties).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 090d5bd3-3b0f-0a8e-ff6d-be50d41032d3
* Version Independent ID: 451ae8b5-88de-1ded-b856-117022313e4d
* Content: [SharePoint Design Manager display templates](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-design-manager-display-templates#bk_scriptblock)
* Content Source: [docs/general-development/sharepoint-design-manager-display-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/sharepoint-design-manager-display-templates.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Are you saying it's not working anymore? 

Because this notation of using 'Display Name'{Localized Name}' has always been the format when you want to use localization. However it's not required if you don't need location.

**Comment by Disc0veryX** [comment]
Probably I misunderstood info from the article. Sorry to bother you. I'll close the issue.
