### ISSUE TITLE
Is there planned support for retrieving sharepoint listItem permissions via Graph? 

### ISSUE THREAD

**Issue by rick-scio** [SharePoint/sp-dev-docs#8536]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

With the Sharepoint REST API, we notice we can retrieve Sharepoint list items permission information (e.g. document library, site pages, etc.) via `/lists('%s')/items(%s)/roleassignments?$expand=Member,RoleDefinitionBindings`.

Graph API currently supports retrieving permissions for driveItem via `https://graph.microsoft.com/v1.0/drives/<drive_id>/lists/<list_id>/items/<item_id>/permissions`. Is there similar support possible for general listItems, e.g. for site pages, that will provide a behavior similar to `roleassignments/` endpoint? We were thinking of an endpoint similar to drive item permissions for sites, like `https://graph.microsoft.com/v1.0/sites/<site_id>/lists/<list_id>/items/<item_id>/permissions`, but this currently doesn't seem to exist.

**Comment by VesaJuvonen** [comment]
As we keep on including more and more of the CSOM/SharePoint REST APIs in the Microsoft Graph, this will most likely happen at some point, but there's no ETA for now which could be shared.
