### ISSUE TITLE
It is possible to download SPO list's attachment files in bulk by using PowerShell?

### ISSUE THREAD

**Issue by hiromiyoshinami** [SharePoint/sp-dev-docs#8537]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Windows PowerShell

### Issue description

It is possible to download SPO list's attachment files in bulk by using PowerShell?
If possible, please tell the PowerShell commands and related steps.

NOTE：
Microsoft Tech Support Dest mentions that "Get-PnPListItemAttachment" might be the command option.
Wondering to know the step-by-step process.

**Comment by VesaJuvonen** [comment]
That cmdlet seems like the rights one to use and indeed should be possible. We do not however have resources in this channel to provide exact PowerShell scripts for our customers and partners worldwide, so we cannot provide the full script for this. Would also check if you can find something similar from the Script Samples - http://aka.ms/script-samples. Can help you to solve the script.
