### ISSUE TITLE
Web part property updates causes child component to remount and lose state

### ISSUE THREAD

**Issue by JoelBool** [SharePoint/sp-dev-docs#8540]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version

Chrome  106.0.5249.91

- SPFx version

1.14.0

- Node.js version

v12.13.0

### Describe the bug / error

When editing a page and then editing a web part property, the **second** edit of the web part properties causes the web part child component to remount (loosing state of the component). Any further changes after this remount works as expected.

### Steps to reproduce

1. I created a very simply webpart just to show this issue using the yo @microsoft/sharepoint scaffolding. Available here https://github.com/JoelBool/RemountingWebpart
2. Serve the project
3. Edit a page. 
4. Add the webpart to the page (it's named 'Remounting')
5. Publish the page
6. Edit the page
7. Click the 'count' button in the webpart (basically it just increments a single number in state which is rendered above). Note that the number changes
8. Edit the web part properties and write one character into the description input. Note that the number stays the same
9. Continue and type another character. Note that the component remounts and that the state is lost (count set to 0)

If you can't reproduce it on the first try, try to repeat steps 5-9. I can reproduce it quite consistently and it's on the second property change that the reset happens. After that the reset doesn't happen again.

### Expected behavior

The state should not be lost on web part property update. I.e. the component should not remount

**Comment by AJIXuMuK** [comment]
@JoelBool - thanks for the detailed description.
I was able to repro it and will be working on it.

**Comment by AJIXuMuK** [comment]
Should be rolled out globally by now
