### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by licdar87** [SharePoint/sp-dev-docs#8551]
I believe this article needs to be updated, as the Connect-PnPOnline command is no longer recognized by the management console. It should be substituted with Connect-SPOService.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbe84d2b-fe47-958c-7d20-0499b4866158
* Version Independent ID: 559aec4d-6837-71a6-294e-4c74f1934302
* Content: [Add a Geolocation column to a list programmatically in SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint)
* Content Source: [docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi. The document is up-to-date.

The sample is connecting to the environment using [PnP PowerShell](https://github.com/pnp/powershell), not using the SPO Management Shell.  Connect-SPOService is the command for the native SharePoint Management Shell.

If you'd like to use this sample, you'd need to install PnP Powershell first. Please check out the documentation.

https://pnp.github.io/powershell/articles/installation.html

**Comment by licdar87** [comment]
> 

Ok, thanks for the clarification. I think I got misguided by step n.1 "Open the SharePoint Online Management Shell", right before the Connect-PnPOnline command example. Shouldn't it say "Open the Sharepoint PnP Powershell" instead?

**Comment by bcameron1231** [comment]
I think that's fair :) I'll make an update to say "Open PowerShell"

**Comment by licdar87** [comment]
Ok then, all is well so I think this can now be closed. Thanks again :)
