### ISSUE TITLE
SPFx Field Customizer - onInit executes multiple times when navigating between folders in same document library

### ISSUE THREAD

**Issue by SaadKnowIT** [SharePoint/sp-dev-docs#8552]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Versions:
- Microsoft Edge version: Version 107.0.1418.26 (Official build) (64-bit)
- Chrome version: Version 106.0.5249.119 (Official Build) (64-bit)
- SPFx version: 1.15.2
- Node.js version: 16.13.0 (64-bit)

### Describe the bug / error

I am developing an SPFx Extension Field Customizer that is supposed to run in an document library with many levels of folders and documents.

The problem i am having is that the "onInit" function is executed multiple times when navigating between the folders in the document library. I am executing an request to SharePoint through the PnPJs library from inside the onInit function.

On initial visit to the document library, this is the order of how the default function execute:
![image](https://user-images.githubusercontent.com/60182595/199739980-f578d118-46dc-448e-a434-96832a663afa.png)

If i decide to navigate in to one of these folders from this view, then this is the execution order of the default functions: 
![image](https://user-images.githubusercontent.com/60182595/199751422-d7106834-7680-4c8d-beac-ea96c7a812b6.png)

If i navigate back up to the root folder and then to a different folder (still one level down). Then this is the execution order of the default functions:
![image](https://user-images.githubusercontent.com/60182595/199753437-8fd6e14c-de5a-4810-b8d4-8fb354deec13.png)

If i right click on a document or a folder in the same view as above to open the object menu, it triggers the default functions again:
![image](https://user-images.githubusercontent.com/60182595/199755157-cb1b2715-233f-4ecd-a5b3-480ffc7f9134.png)

This behavior i explained above continues as i navigate to a new folder in the same document library. For every new folder i navigate to, the execution count for the onInit executions increase by one.

### Steps to reproduce

1. Create a new SPFx Extension - Field Customizer with React as a template using yo.
2. Add these for the console log outputs as show in my pictures above.
![image](https://user-images.githubusercontent.com/60182595/199757957-a2a2486c-1a7a-4a33-92db-4271b09e981a.png)

3. Add the column associated with your Field Customizer to a document library.
4. run gulp serve and test it against the document library.

### Expected behavior

I expect the oninit function to be executed only once for each navigation event made between the folders.

**Comment by SaadKnowIT** [comment]
@andrewconnell & @VesaJuvonen, do you guys have any insight into this?

**Comment by AJIXuMuK** [comment]
@SaadKnowIT - sorry for the silence.
I'm able to repro it and will be working on the fix.

**Comment by SaadKnowIT** [comment]
@AJIXuMuK - Glad to here that you are working on this. Waiting for your findings/results.

**Comment by AJIXuMuK** [comment]
@SaadKnowIT - the issue has been fixed and will be included in the next release.
To set the expectations: `onInit` will be called once per customizer/list.
It means that it may not be called if you navigate between 2 lists because the state of the list is cached and the customizer has been already initialized. Don't use this handler to handle navigation of any type.

**Comment by SaadKnowIT** [comment]
@AJIXuMuK, thanks for the reply and the fix. Will test it when it is released.

What am i supposed to use to handle navigation events (Navigating between folders) inside the same library/list or when navigating between different libraries/lists.

**Comment by AJIXuMuK** [comment]
this should be rolled out worldwide by now
