### ISSUE TITLE
gulp bundle --ship is not working

### ISSUE THREAD

**Issue by rbkharade** [SharePoint/sp-dev-docs#8554]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Microsoft Edge 107.0.1418.26 (Official build) (64-bit)
- SPFx version - 1.14.0
- Node.js version - 14.15.0
- etc

### Describe the bug / error

We have created SPFx solution with webparts and extension using SPFx 1.14.0. When we tried to bundle the package using gulp bundle --ship, we are getting below error.

Error - [webpack] 'dist':
./node_modules/readable-stream/lib/internal/validators.js 140:15
Module parse failed: Identifier directly after number (140:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   const min = positive ? 1 : 0 // 2 ** 32 === 4294967296
|
>   const max = 4_294_967_295
|
|   if (value < min || value > max) {
 @ ./node_modules/readable-stream/lib/internal/streams/pipeline.js 31:50-74
 @ ./node_modules/readable-stream/lib/stream/promises.js
 @ ./node_modules/readable-stream/lib/ours/browser.js
 @ ./node_modules/lzutf8/build/production/lzutf8.js
 @ ./lib/common/utilities/storage.js
 @ ./lib/store/Saga/WWCUCPWEBAPIHelper.js
 @ ./lib/store/Saga/index.js
 @ ./lib/store/Store.js
 @ ./lib/extensions/wwcucpExtension/container/index.js
 @ ./lib/extensions/wwcucpExtension/WwcucpExtensionApplicationCustomizer.js

### Steps to reproduce

1. Create SPFx solution with 1.14.0 and given node version
2. Add below file as package.json

`{
  "name": "wwc",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": "=12.13.0 || =14.15.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "jest",
    "lint:fix": "tslint -c tslint.json src/**/*.{ts,tsx} --fix --format verbose",
    "serve": "gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve",
    "test:coverage": "jest --env=jsdom --coverage --runInBand --watchAll=false",
    "format": "prettier --write src/**/*.{ts,tsx,scss,css,json}",
    "isready": "npm run format && npm run test:coverage && gulp build"
  },
  "jest-junit": {
    "output": "./jest/summary-jest-junit.xml"
  },
  "dependencies": {
    "@azure/msal-browser": "^2.25.0",
    "@fluentui/react": "^8.91.1",
    "@microsoft/applicationinsights-web": "^2.8.4",
    "@microsoft/decorators": "1.14.0",
    "@microsoft/sp-application-base": "1.14.0",
    "@microsoft/sp-core-library": "1.14.0",
    "@microsoft/sp-office-ui-fabric-core": "1.14.0",
    "@microsoft/sp-property-pane": "1.14.0",
    "@microsoft/sp-webpart-base": "1.14.0",
    "@microsoft/sp-component-base": "1.14.0",
    "@microsoft/sp-lodash-subset": "1.14.0",
    "@microsoft/sp-loader": "1.14.0",
    "@uifabric/react-cards": "^0.114.6",
    "@wwc/flights": "1.0.55",
    "applicationinsights-js": "^1.0.21",
    "bootstrap": "^5.1.3",
    "jquery": "^3.6.0",
    "lodash": "^4.17.21",
    "lzutf8": "^0.6.1",
    "office-ui-fabric-react": "^7.180.1",
    "react": "16.13.1",
    "react-beautiful-dnd": "^13.1.0",
    "react-bootstrap": "^1.6.5",
    "react-dom": "16.13.1",
    "react-redux": "^7.2.6",
    "react-router-dom": "^5.3.0",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.3.0",
    "sanitize-html": "^2.7.0",
    "@types/react": "^17.0.45",
    "node-fetch": "^2.6.7",
    "isomorphic-fetch": "3.0.0",
    "@types/react-router": "5.1.18"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.9": "^0.4.48",
    "@microsoft/sp-build-web": "^1.14.0",
    "@microsoft/sp-module-interfaces": "1.14.0",
    "@microsoft/sp-tslint-rules": "1.14.0",
    "@types/enzyme": "^3.10.10",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/es6-promise": "0.0.33",
    "@types/jest": "^26.0.24",
    "@types/lz-string": "^1.3.34",
    "@types/react-beautiful-dnd": "^13.1.2",
    "@types/react-dom": "16.9.8",
    "@types/react-redux": "^7.1.23",
    "@types/react-router-dom": "^5.3.3",
    "@types/redux": "^3.6.0",
    "@types/redux-thunk": "^2.1.0",
    "@types/webpack-env": "1.13.1",
    "ajv": "^8.11.0",
    "babel-jest": "^27.4.5",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.5",
    "gulp": "~4.0.2",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.5.1",
    "jest-junit": "^13.0.0",
    "prettier": "^2.6.0",
    "spfx-fast-serve-helpers": "1.14.5",
    "ts-jest": "^27.1.5",
    "tslint-react": "^5.0.0",
    "tslint-react-a11y": "^1.1.0",
    "webpack-bundle-analyzer": "^4.5.0"
  }
}
`

3. Do gulp clean
4. Run gulp bundle --ship

### Expected behavior

It should bundle successfully.

**Comment by AJIXuMuK** [comment]
@rbkharade - the bundle is failing in the package you're importing: `readable-stream`.
If you look at the [documentation](https://www.npmjs.com/package/readable-stream) of the package - you need to add custom webpack plugin to make it work.
Please check this doc to learn how to extend the out of the box configuration: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline
