### ISSUE TITLE
SPFX CommandSet not available in ListWebParts

### ISSUE THREAD

**Issue by Link631** [SharePoint/sp-dev-docs#8556]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

1. Create a new Project with current yeoman version of type CommandSet.
2. Provide an url to a listview.aspx in configs
3. run gulp serve

result: You can see the commands in the listview

### Steps to reproduce

1. Create a new Project with current yeoman version of type CommandSet.
2. Provide an url to a page in pages library where you have added multiple listviewWebparts
3. run gulp serve

Result -> the commands are not available

### Expected behavior

Commands should be available in List Webparts.

It is said, that this issue is fixed.
https://github.com/SharePoint/sp-dev-docs/issues/5707

But we can reproduce this in local dev environment with spfx version 15.

**Comment by AJIXuMuK** [comment]
@Link631 local debugging without installing and configuring command sets for the list is not available for the web parts.

You need to deploy your package, enable the command set for the list.
Then it will become visible in web parts with this list too.

**Comment by Link631** [comment]
Ah....Ok...thanks for the hint!...

regards!.
