### ISSUE TITLE
SdkVersion header is overwritten by SPFx for GraphClient

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#8561]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx v1.14.0

### Describe the bug / error

When specifying a custom 'SdkVersion' value it is overwritten by SPFx when the query is run. I expect the custom value to be passed as the header.

### Steps to reproduce

Using the following code

```typescript
const msGraphClientFactory = this.serviceScope.consume<MSGraphClientFactory>(MSGraphClientFactory.serviceKey);
        const msGraphClient = await msGraphClientFactory.getClient();
        const request = await msGraphClient.api(this._microsoftSearchUrl);
        const jsonResponse: IMicrosoftSearchResponse = await request.headers({ 'SdkVersion': 'pnpmodernsearch' }).post(searchQuery);
```

Header on the request is passed as `graph-js/1.7.2-spfx (featureUsage=6)`

### Expected behavior

I expect the value to be `pnpmodernsearch`. If I rename the header to `SdkVersion2` it is being passed.

**Comment by AJIXuMuK** [comment]
@wobba - this header is added by graph sdk, not SPFx: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/release/1.7.2-spfx/src/middleware/TelemetryHandler.ts

**Comment by wobba** [comment]
Thank you @AJIXuMuK .. I'll bring it up the correct place :)
