### ISSUE TITLE
@crtjr64 - TypeScript is not a library. It's a language. You can use [Vuejs](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/vuejs-todo-single-file-component).

### ISSUE THREAD

**Issue by crtjr64** [SharePoint/sp-dev-docs#8567]
@crtjr64 - TypeScript is not a library. It's a language. You can use [Vuejs](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/vuejs-todo-single-file-component).

_Originally posted by @AJIXuMuK in https://github.com/SharePoint/sp-dev-docs/issues/8514#issuecomment-1285380907_

**Comment by AJIXuMuK** [comment]
@crtjr64 - could you provide details what this issue is about?

**Comment by AJIXuMuK** [comment]
@crtjr64 - you are free to create your own generator for Vuejs/plain JS similarly it is done by PnP.
And you can definitely keep it up to date... and share with others.

Microsoft's stake is TypeScript and (optionally) React.
Vuejs usage/requests are pretty low to invest in including it into the Microsoft owned generator.
Same for JS - too little developers want to use plain JS.

**Comment by crtjr64** [comment]
I know what I am free to do young man but thanks for proving my point being that this was a huge waste of my time and Microsoft's part in it. Why even mention Vuejs in documentation as an option if there's no investment in it? I could have come to that conclusion days beforehand and spent that time working on my own generator instead of weeks later you giving me what's been painfully obvious these last several weeks after wasting days experimenting with various Microsoft recommended solutions and I completely disagree that too little developers use plain JS or Vuejs when, my entity a major university hospital system with one of the top trauma units is using it as well as a huge list of fortune 500 companies. While it may be true in your circle that few developers use these options the real world says TypeScript / React developers is much less than the other libraries and plain JS... 

Companies that use React: Airbnb, Discord, Instagram, DropBox, Walmart, Wix, Pintrest, Skype
Entities that use Vuejs: University of MD Hospital, Johns Hopkins Hospital, Netflix, Xiomi, Facebook, Nintendo, BMW, Apple, Google... oh wait... now I get it.... Apple? Google?

You can close this. I already built my generator... I don't think its that good, but it works for me so far.
