### ISSUE TITLE
Code in images?

### ISSUE THREAD

**Issue by davimack** [SharePoint/sp-dev-docs#8569]
[Enter feedback here]
This page instructs the user to insert JSON into a box.  The JSON presented is not in text, but is an image.  The user cannot copy the JSON, but must OCR it or retype it.  Code which isn't copyable defeats the point of presenting code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/view-formatting.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Can you clarify which area you can't copy? I don't see any where where it says to copy the JSON (i may be missing it). But the JSON that is in the photos, is the default value when you format the column, there would be no need to copy it as it already exists.

**Comment by davimack** [comment]
I apologize - this is probably a non-issue.  Yes, it's those boxes' content I was trying to copy, for whatever reason.  I'll go ahead and close as, on reflection, it's not a good issue to have raised.

**Comment by VesaJuvonen** [comment]
Closing as clarified 🚀
