### ISSUE TITLE
Field Customizer not rendering when refreshing a view

### ISSUE THREAD

**Issue by martinlingstuyl** [SharePoint/sp-dev-docs#8571]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment
Windows, Used WSL + Docker for the development.

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
107.0.1418.35 (Official build) (64-bit)

- SPFx version
1.15.2

- Node.js version
14.20.1

### Describe the bug / error

Similar to 
https://github.com/SharePoint/sp-dev-docs/issues/6892

Field Customizers are not always rendering in a scenario when you do not have the field customizer on the default view. Refreshing the browser does not fix the issue. Reopening the Library and switching to the correct view does fix the issue.

### Steps to reproduce

The Repro-path is as follows:

1. Create a new modern Teamsite.
2. Create a library named 'Test'.
3. Create a new column.
4. Create a basic Field Customizer and connect it to the new column using the ClientSideComponentId.
5. Hide the column on the default AllItems view.
6. Create a new view named Test and add the new column to the view.

Now you're all set to try it out.

1. Create a new Tab in your browser and navigate to your [siteurl]
2. Navigate to your 'Test' library and select the 'Test' view.

Result: The Field Customizer should render.

3. Now press F5

Result: the Field Customizer will **not** render. (The Field Customizer JavaScript file is not loaded)
Note the URL in your browser: it is something like this: `https://contoso.sharepoint.com/sites/projectx/Test/AllItems.aspx?viewId=<view-guid>` which is the default URL SharePoint constructs when switching from a default view.

4. Now rewrite your URL to the following and hit enter:
`https://contoso.sharepoint.com/sites/projectx/Test/Test.aspx`

Result: Now the Field Customizer will render again.

5. ...or click on the Test document library in your quick launch and re-select the Test view. The field customizer will now render as well.

### Expected behavior

The field customizer should be loaded

**Comment by anthonywhite** [comment]
Hi @martinlingstuyl we are seeing this issue as well. @AJIXuMuK shouldn't customizers also be loaded for any column that is in the `viewid` querystring, and not just the default view?

**Comment by AJIXuMuK** [comment]
@martinlingstuyl - wanted to check if that's got resolved for you

**Comment by martinlingstuyl** [comment]
Hi @AJIXuMuK, certainly, it's working like a glove now. Thanks! I'll close this issue.
