### ISSUE TITLE
How to brand SharePoint solutions (addins or spfx)

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/sp-dev-docs#8572]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

n/a

### Issue description

Our company is building solutions for SharePoint. Some are SharePoint addins (.app files), some are SPFX solutions (.sppkg).

I didn't found in the documentation how to brand solutions in app catalogs, especially in the *Add an application* page. Neither the classic nor the modern version.

Example of what I'd like to setup :
![image](https://user-images.githubusercontent.com/184604/201075077-3f6cbb6b-b996-45c6-bd9e-5c006aa1c6c6.png)
 
![image](https://user-images.githubusercontent.com/184604/201075273-47c08efb-1639-48c7-ab8d-06dbaa933994.png)

![image](https://user-images.githubusercontent.com/184604/201076935-637fd77a-9337-452e-9653-aeb927f108a7.png)

Also, in the site content page (once the application is added) :

![image](https://user-images.githubusercontent.com/184604/201075871-983e4058-1a8d-41fb-9191-2db3b96ae4f6.png)

In classic mode, I can set the application icon for sharepoint addins, but not for spfx solutions:

![image](https://user-images.githubusercontent.com/184604/201076378-f1b7fea9-9b3a-4010-8fe6-4dc13763c7fa.png)

Is it possible ? If yes, where can I found documentation ?

Side note : I don't know if it matters, but Addins are multi tenant addins. It's *not* published to the office store, but setup in the MS partner portal (requirement for multi tenant appid).

Everything (both .app and .sppkg) are deployed within site collection app catalogs

**Comment by AJIXuMuK** [comment]
@stevebeauge  - of course it is possible.
Here are 2 links that will help you:
https://thechriskent.com/2017/06/19/sharepoint-framework-app-icon/
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-checklist

**Comment by AJIXuMuK** [comment]
PnP Search is an SPFx solution. And two links above show how to set values in `package-solution.json`.
You don't need to upload anything.

For Add-ins there is a similar approach when you can provide needed information in app XML. No need to upload as well.

**Comment by stevebeauge** [comment]
> ... approach when you can provide needed information in app XML ...

This is this very specific part of missing info.

Only the installed app name and icon can be set. Not other catalog metadata (at least, I don't know how).

Nothing here : https://learn.microsoft.com/en-us/sharepoint/dev/schema/schema-map-sharepoint-add-in-manifest

**Comment by AJIXuMuK** [comment]
@stevebeauge - how's that related to PnP Search?

It's been a while since I worked on Add-ins.
Maybe you are correct and the rest of the metadata is populated when you add an app to the App Source based on your Partner Center profile.
