### ISSUE TITLE
SharePoint Theme Generator Tool webpage won't scroll (can't get to all options)

### ISSUE THREAD

**Issue by yasmeensk** [SharePoint/sp-dev-docs#8577]
Hi there, 

I'm trying to use the Theme Generator Tool but the webpage won't scroll down: https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html 

The only way I can see all the contents of the webpage is to zoom out. 

I've now tested the webpage url on a PC laptop with Chrome/Firefox + MacBook Air with Chrome/Safari + Android with Chrome + iPhone with Chrome and the webpage is not dynamic and won't scroll. 

Is there a way to fix this webpage (I can't see the webmaster contact details on the page) or perhaps a workaround? 

To see all the contents on the webpage I have to zoom out by 50% and I can't read the selections. I'm getting a headache from all the squinting. 

Thanks!
Yasmeen

<img width="829" alt="Screenshot 2022-11-11 161558" src="https://user-images.githubusercontent.com/118022148/201431949-cd2685c9-631b-4fbc-8b36-f1c6db7905a5.png">

![Screenshot 2022-11-11 161758](https://user-images.githubusercontent.com/118022148/201432303-f7995d85-c4ef-46ef-9fa0-dc8d5d0a4765.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c5279de-43c1-3a83-83ce-c1b34d25287d
* Version Independent ID: 7cda1751-170a-7bbd-6d71-33daf5168f68
* Content: [SharePoint site theming](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview)
* Content Source: [docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Sorry for the small delay on this one, but we have now fixed the experience. Thanks @yasmeensk on reporting the issue and @omarelanis  for the additional nudge 👍🙏🚀
