### ISSUE TITLE
Viva Connections Desktop App Issue: Custom API calls are failing

### ISSUE THREAD

**Issue by Srpatil212** [SharePoint/sp-dev-docs#8591]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Desktop App for Microsoft Teams

### Issue description

Following authentication calls in MS Teams Desktop client are failing while calling custom AD authenticated API calls.

https://tenant.sharepoint.com/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=resource id&clientId=SharePointOnlineClientExtensibilityWebApplicationPrincipalID

Error messages differ from time to time. Following have been observed:
1. AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'https://tenant.sharepoint.com/' and the expected audience is 'api://tenantid/microsoft.spfx3rdparty.com' or one of the Application Uris of this application with App ID (SharePoint Online Client Extensibility Web Application Principal). The downstream client must request a token for the expected audience (the application that made the OBO request) and this application should use that token as the assertion.\

2.One or more errors occurred.
3.Authentication Method is not allowed.

Please refer below screenshots for the same.

![image](https://user-images.githubusercontent.com/110666464/202454837-c9fa9c78-f97a-4112-9642-bf249ddd6239.png)
![image](https://user-images.githubusercontent.com/110666464/202454895-98906039-e203-4271-b7fa-9c03bcbabd2b.png)
![image](https://user-images.githubusercontent.com/110666464/202454944-234444b2-1d58-43c2-9a33-2877b77e6f7a.png)

**Comment by AJIXuMuK** [comment]
@Srpatil212 - are you using Sync to Teams to add the SPFx app to the Teams? or do you have a custom manifest?
If the latter - could you please share the manifest?

Thanks!

**Comment by Srpatil212** [comment]
@AJIXuMuK  Since this is Viva Connections app of Microsoft teams , we have just added the app in Teams. Our home site for sharepoint tenant has custom spfx webparts and in them we have api calls. 
Viva connections app is opening our sharepoint home site and the custom api calls in spfx webparts failing as mentioned above.

**Comment by AJIXuMuK** [comment]
@Srpatil212 could you please send the request id and request date?
You can find those in the request headers.

**Comment by Srpatil212** [comment]
I can share the request id and date with you separately. Please let me know your microsoft communication id.

**Comment by AJIXuMuK** [comment]
@Srpatil212 it's aterentiev@microsoft.com

**Comment by AJIXuMuK** [comment]
Marking as feedback needed as haven't heard anything back.
We also made some changes that can potentially fix this issue. 
These changes should be rolled out next week.
