### ISSUE TITLE
Where is a link to show how toi do this with MS Graph?

### ISSUE THREAD

**Issue by titchy** [SharePoint/sp-dev-docs#8592]
This page does the trick, but I have trawled MSGraph docs for weeks looking for how to do this the new way and can not find anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f8d79d1-a5b0-ccd6-6e65-4744851c6df2
* Version Independent ID: a41aed12-dcf0-93f9-c978-29738ffcb7b1
* Content: [Read or update user profile properties sample SharePoint Add-in](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/read-or-update-user-profile-properties-sample-app-for-sharepoint)
* Content Source: [docs/solution-guidance/Read-or-update-user-profile-properties-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Read-or-update-user-profile-properties-sample-app-for-SharePoint.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi! Have you checked out the Microsoft Graph User API?

https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http

**Comment by titchy** [comment]
Yes, I did look at that and it has no obvious way to modify Sharepoint custom attribute values. I am hoping I am missing something and that it is easy to do.

**Comment by bcameron1231** [comment]
AFAIK, I don't think you can use Graph to update those.

**Comment by AJIXuMuK** [comment]
@titchy - there are no MS Graph endpoints to do that. 
So, we can't update the docs :)
