### ISSUE TITLE
Fluent UI version included with SPFx 1.16+

### ISSUE THREAD

**Issue by SemperYak** [SharePoint/sp-dev-docs#8593]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

In the SPFx 1.16 preview [release notes](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16), the following is deprecated:

> Deprecated @microsoft/office-ui-fabric-react-bundle package. Use @fluentui/react instead

When installing SPFx preview version 1.16 (React framework), the Fluent UI version package included is 7.199.1. However, when you look at the [Fluent UI controls site](https://developer.microsoft.com/en-us/fluentui#/controls/web), the documentation for Fluent UI React 7 still uses the older import which is deprecated.

For instance, if you look at the Button component:

**Fluent UI React 7**
```
import { DefaultButton, PrimaryButton, Stack, IStackTokens } from 'office-ui-fabric-react';
```

**Fluent UI React 8**
```
import { Stack, IStackTokens } from '@fluentui/react';
import { DefaultButton, PrimaryButton } from '@fluentui/react/lib/Button';
```

Does that mean the official release of SPFx 1.16 (and moving forward) will include Fluent UI version 8, by default? Is it currently installing version 7 because this is still in preview?

Thank you!

**Comment by AJIXuMuK** [comment]
@SemperYak - SPFx 1.16 is not in preview.
It was released on November 15.
And it is based on Office UI Fabric React 7.
We will be updating to v8 in one of the upcoming releases.

**Comment by SemperYak** [comment]
> @SemperYak - SPFx 1.16 is not in preview.
> It was released on November 15.
> And it is based on Office UI Fabric React 7.
> We will be updating to v8 in one of the upcoming releases.

Oh, I didn't realize it was released. 😬  Thanks!

So the deprecated message about the older method of imports (as seen with Fluent UI 7) should be ignored for now, until Fluent UI 8 is packaged with a newer release? I imagine you need to ensure compatibility? 

Also, are we free to upgrade to a newer Fluent UI version with the caveat some features may not work? Or is it safer to stick to included version?

**Comment by AJIXuMuK** [comment]
@SemperYak - you may update to newer versions of Fluent UI.
We can't guarantee all will be working for sure.
But it should ;)
