### ISSUE TITLE
Missing essential items to complete the example

### ISSUE THREAD

**Issue by NL12143** [SharePoint/sp-dev-docs#8596]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Good example but it is missing 2 items: 

1. From the buil-in we miss a column in the library for approval status. Please make example 100%.   
2. What happens when user keep the document open when approving. It is LockOut, hence can the flow edit the status in that column? 

Thank you, RoelandC

**Comment by bcameron1231** [comment]
Hi! Can you please update your issue here and link to the documentation in question? I'm unsure which documentation you are referencing. 

Thanks!
