### ISSUE TITLE
Mismatched anonymous define() module: function () { 'use strict';

### ISSUE THREAD

**Issue by Ms-fernandes** [SharePoint/sp-dev-docs#8597]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 
- SPFx version 1.11.0
- Node.js version 10.22.1
- etc

### Describe the bug / error

Every webpart on sharepoint designed on spfx throwing below error.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Mismatched anonymous define() module: function () { 'use strict';

    var hookCallback;

    function hooks () {
        return hookCallback.apply(null, arguments);
    }
.............

### Steps to reproduce

any spfx webpart deployed on sharepoint

### Expected behavior

to display designed webpart

**Comment by AJIXuMuK** [comment]
@JJFranko @Ms-fernandes - could you provide additional details?
"Any web part in SharePoint" is too broad and we can't repro it.
Are you using classic publishing portals and classic pages (as mentioned the linked StackExchange issue)?
Do you have Public CDN enabled?
If you add `?sw=bypass` to the page url - does is solve the issue?

**Comment by JJFranko** [comment]
Will do my best to answer as I am not a SP developer and my SP Dev colleagues moved on to other positions prior to this issue popping up.

- Type of webpart:  Not sure, but looking into the package.json files for parts that intermittently fail, I see these (among others) in the dependencies:  sp-core-library versions 1.11.0 or 1.12.1 or 1.13.0 or 1.14.0.  All appear to be using react 16.8.5, office-ui-fabric-react 6.214.0; two use jquery, three do not use jquery but do include moment.
- I'm pretty sure we fall in the "classic" category- but if you can advise how to know for sure I can gather the info
- CDN: This message: `CDN improves performance by caching static assets closer to the browsers requesting them. Partner with your SharePoint administrator to set up and configure CDN to store static page assets.` shows up when I'm in site settings/AppCatalog, so I'm guessing that Public CDN is **not** enabled. 
- Adding `?sw=bypass` to the page URL does not resolve the issue.

**Comment by AJIXuMuK** [comment]
@JJFranko 

> I'm pretty sure we fall in the "classic" category- but if you can advise how to know for sure I can gather the info

could you please send a screenshot of the page?
Classic pages have "older" UI, similar to ones we had in on-prem versions (SP 2013, 2016).
Also, classic pages allow to have custom master pages. So, if you have highly customized look and feel - most probably it's a classic page.

**Comment by JJFranko** [comment]
In which case, then yes it is classic - we do have the "older" UI look & feel which the previous dev created to mirror our previous on-prem SP version.

**Comment by JJFranko** [comment]
If it helps, comparing the console.log when it renders vs when it fails, there is a difference in how errors are handled (somehow?).  
When the page ERRORS, I see this: 
`VM87:8 Uncaught (in promise) Error: Mismatched anonymous define() module: function () { 'use strict';`

But when it renders, I see this: 
`VM85:8 Uncaught Error: Mismatched anonymous define() module: function () { 'use strict';`

Looking further down in the log, I see where this comes into play.
ERROR:  
`   at B (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:8:252)
    at J (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:15:75)
    at Object.g [as require] (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:26:484)
    at requirejs (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:32:203)
    at e.config (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:32:247)
    at e.configLoadComponent (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:350783)
    at e._loadComponent (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:355011)
    at e.loadComponent (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:370674)
    at sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353814
    at new Promise (<anonymous>)`

RENDERS: 
`    at B (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:8:252)
    at J (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:15:75)
    at eval (eval at e (sp-classic-page-assembly_en-us_a42763779e0caa84802474537f1474a8.js:68:353036), <anonymous>:26:510)
    at arguments.<computed> (init.js:1:100472)`

I'm not sure if this is enough to point in the right direction or if there's more to include, but this caught my non-SPDev eye and thought it might be a place to get a foothold.

**Comment by JJFranko** [comment]
For what it's worth, when I go to the console, click on the sp-classic-page-assembly_en-us_....js file and view the code, it takes me to the `self.spModuleLoader = (function(){` ... after I pretty print the code in Chrome's dev tools it points to this subsection that is under the ` var W = function() {` and this is the specific sub-section of that function it drops me in:

                         e.prototype.loadComponent = function(e) {
                            var t = this;
                            return new Promise(function(n) {
                                var a = e.id
                                  , i = e.version
                                  , r = L.e.instance.tryGetComponent(a, i);
                                r || (r = t._loadComponentExecutor.loadComponent(e, 0),
                                L.e.instance.storeComponent(a, i, r)),
                                n(r)
                            }
                            )
                        }

**Comment by AJIXuMuK** [comment]
@JJFranko @Ms-fernandes - could you please create a clean site, add classic page there and add any of your failing web parts?
I'm unable to repro the issue on 2 completely different environments with multiple web parts.

**Comment by damienraju-aa** [comment]
I am also experiencing this issue when loading in a custom webpart on a classic site. Every now and then it will error and show error messages in the console similar to those posted before (error mismatch define etc.). It does load correctly on refresh, though in some instances multiple refreshes are required which isn't ideal. We are also using a custom master page template, and using the "solutions" from https://sharepoint.stackexchange.com/questions/304837/sharepoint-online-every-spfx-web-parts-get-this-error-something-went-wrong and https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module/23467090#23467090 did not resolve the issue. Loading the webpart on an empty page also causes the errors to appear in the console on some page reloads.
