### ISSUE TITLE
SPFx meeting apps: Is it possible to get the meeting details

### ISSUE THREAD

**Issue by canturan** [SharePoint/sp-dev-docs#8598]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Teams Client 1.5.00.31168 (64-bit)

### Issue description

I am trying to find out, if it is possible to get the meeting details when the SPFx app runs in the meeting (pre-meeting, in-meeting etc.)

I was testing the Teams SDK v2 but I am still getting the error message 1000: No permissions, even if I have assigned the OnlineMeetings.Read permissions to my application, which also what I expected. Because: According to the documentation, the getMeetingDetails API is available through Bot Services. The Meeting Details API must have a bot registration and bot ID, which we don't have in SPFx. 

This concludes my question: Is there any way to get the meeting details. This can be the start and end date of the meeting or can also be the event ID (Exchange), if there is any possibility. The Meeting ID on the Teams SDK is just a base64 encoded version of the chat ID of the Teams, that does not help very much. 

Every help is appreciated and thank you all in advance.

**Comment by AJIXuMuK** [comment]
@canturan - unfortunately, based on Teams guidelines, this information is available via bot only.
You can combine SPFx meeting app and bot in a single Teams App (with custom manifest.json) and get the information using the bot.
