### ISSUE TITLE
Issue with making extension work from CDN

### ISSUE THREAD

**Issue by thePaddyVP** [SharePoint/sp-dev-docs#860]
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I have an app customizer which needs to add a image to header based on certain conditions. I have it working in debug mode. I deployed the same via CDN by following the instructions specified in https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.

When I try to execute the custom action by loading the page it does not work. It only works when I run gulp serve -- nobrowser. I was expecting it to work with running gulp serve once it is deployed to CDN. Not sure if I am missing changing anything. Any help is much appreciated.

Thanks

**Comment by waldekmastykarz** [comment]
Have you built the SharePoint package with the `--ship` argument, like `gulp package-solution --ship`? Without the `--ship` argument, the generated package will use localhost as the script URL.

**Comment by salesky** [comment]
I'm having the same issues. In debug mode (with querystring in url) it works well but if I use CDN and --ship the code is not fired.

**Comment by mmsharepoint** [comment]
Check it out again, we had the same issue (I think) under #847 and for me it's running now since the extensions got GA

**Comment by salesky** [comment]
For me it's still not working. I tried to create a new extension and still OnInit is not beeing called. I also updated yeoman generator.

**Comment by salesky** [comment]
Today it started working on my tenant!
