### ISSUE TITLE
Team Tab SPFx app does not load in MS Teams for iPadOS

### ISSUE THREAD

**Issue by pheidler** [SharePoint/sp-dev-docs#8608]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.15.2
- Node.js version: 14.15.0
- iPadOS version: 16
- Teams version: 4.21.2

### Describe the bug / error

SPFx Teams Tab is stuck on loading page in Teams app for iPadOS. The same SPFx app is working in every other Teams environment, including:
- Web app
- Windows Teams app
- MacOS Teams app
- iOS Teams app
- Android Teams app

I'd like to provide more information as to why it isn't working, but I'm at a bit of a loss as to how to monitor any errors/failed network requests in the iPad environment. Please let me know if there's anything I can do to assist in this regard. Thanks!

### Steps to reproduce

1. Create SPFx Teams Tab app
2. Upload to App Catalog, Add to Teams
3. Add app to channel
4. App fails to load (stuck on "Loading <app name>...")

### Expected behavior

App loads successfully, as it does in each other environment.

**Comment by AJIXuMuK** [comment]
@pheidler - it seems like something specific to the logic of your app.
I have tested simple SPFx web part that is using MS graph to get current user info and everything is working fine on the iPad.
I would suggest adding some extra logging into your app to check what exactly is going on.
I'm also attaching the test app I was using for your reference.
[ipad-test.zip](https://github.com/SharePoint/sp-dev-docs/files/10114172/ipad-test.zip)

**Comment by pheidler** [comment]
@AJIXuMuK Thanks, the test app is working for me as well. I'll see if I can pinpoint the issue further on my end.

**Comment by pheidler** [comment]
Got it fixed. It was related to the following issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/544

Thanks for the help!
