### ISSUE TITLE
MS Clarity app on SharePoint inquiry

### ISSUE THREAD

**Issue by bahgael-sobky** [SharePoint/sp-dev-docs#8610]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Hello SharePoint team,

Our [Clarity app](https://appsource.microsoft.com/en-US/product/office/WA200004850?tab=Overview) is just published to the marketplace, thanks to your support. We have some questions regarding some changes we are planning to do as follows:
- How can we track the application installation rate? For example, the number of users who installed the application and the number of users who followed the installation guide/readme
- What is the user role required to add new apps to the SharePoint application/account?
- Regarding editing/changing the readme instructions of the application:
     - What is the process of editing the readme instructions of the application?
     - How can we edit the readme instructions?
     - Would this require releasing a new version?
     - Will the changes pass by another review cycle or it will be directly released?
     
Thanks in advance,
Bahga

**Comment by andrewconnell** [comment]
@bahgael-sobky said:

> * How can we track the application installation rate? For example, the number of users who installed the application and the number of users who followed the installation guide/readme

There's nothing provided that does this for you... you'd have to implement this with your own custom logic within the app how you see fit. There are no events raised when an app is installed.

> * What is the user role required to add new apps to the SharePoint application/account?

I believe it's site contributor & higher

> * Regarding editing/changing the readme instructions of the application:
>   
>   * What is the process of editing the readme instructions of the application?
>   * How can we edit the readme instructions?
>   * Would this require releasing a new version?
>   * Will the changes pass by another review cycle or it will be directly released?

These are all code updates to the component... you edit, version & resubmit the updated app which will go through a new review.
