### ISSUE TITLE
SPFx v1.14.2 default packages vulnerabilities

### ISSUE THREAD

**Issue by rbkharade** [SharePoint/sp-dev-docs#8613]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Chrome (Version 107.0.5304.107 (64-bit)) , Microsoft Edge(Version 107.0.1418.56(64-bit))
- SPFx version - 1.14.0 / 1.15.2
- Node.js version - 14.15.0
- etc

### Describe the bug / error

Observed high count of moderate and high vulnerabilities on packages

> yo @microsoft/sharepoint

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │  SharePoint Online SPFx  │
   `---------´   │  Yeoman Generator@1.15.2 │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

See https://aka.ms/spfx-yeoman-info for more information on how to use this generator.
Let's create a new SharePoint solution.
? What is your solution name? new-folder-2
? Which type of client-side component to create? WebPart
Add new Web part to solution new-folder-2.
? What is your Web part name? HelloWorld
? Which template would you like to use? React

**found 92 vulnerabilities (7 low, 43 moderate, 34 high, 8 critical)
  run `npm audit fix` to fix them, or `npm audit` for details**

Due to these vulnerabilities  Critial , High , Medium alerts are getting triggered on **Azure Devops Component Governance** level as well.

As suggested to run npm audit fix is also breaking spfx build and showing other type errors as well.

Please help us to resolve these vulnerabilities.

Thank you in advance.

### Steps to reproduce

1.Install 1.14.0/1.15.2 version of @microsoft/generator-sharepoint
2.Run yo @microsoft/sharepoint
3. Create a new webpart using react 

### Expected behavior

When running yo @microsoft/sharepoint, no high/critical vulnerabilities found on packages.

**Comment by AJIXuMuK** [comment]
@rbkharade - thanks for reporting that.
There are no runtime vulnerabilities we're aware of.
There could be vulnerabilities in packages used by build routine, but as those packages are not loaded as part of the solution we're not treating them as critical issues.
