### ISSUE TITLE
WebPart blanks on SPFx package update and can not be found on page

### ISSUE THREAD

**Issue by IllimarAtShareCloud** [SharePoint/sp-dev-docs#8630]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx 1.13.1 in SPO and its a tenant deployed app used across multiple sites.

package-solution
```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "Price Inquiries",
    "id": "13456fa2-5784-4d89-bc81-6b9fa1d22fa3",
    "version": "2.1.0.113",
    "iconPath": "img/ShareCloudAppIcon96x.png",
    "includeClientSideAssets": true,
    "isDomainIsolated": false,
    "developer": {
      "name": "ShareCloud OÜ",
      "websiteUrl": "https://sharecloud.ee",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": "xxxx"
    },
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.Send"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Mail.ReadWrite"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      }
    ],
    "features": [
      {
        "title": "Application Extension - Deployment of custom action.",
        "description": "Deploys a custom action with ClientSideComponentId association",
        "id": "e8c7a393-b4a2-448d-8130-17e3e28b1e56",
        "version": "1.0.0.0",
        "assets": {
          "elementManifests": [
            "elements.xml",
            "ClientSideInstance.xml"
          ]
        }
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/price-inquiries.sppkg"
  }
}
```

### Describe the bug / error

So I managed to blank one of the biggest WebParts for one of largest customers. Thankfully it happened when I was at ESPC22 and could find some sort of an explanation for our customer, but the issue I ran into basically stems from this one: 

https://github.com/SharePoint/sp-dev-docs/issues/7929

Now the explanation that the kind MS expert gave me... just does not make sense, because the timeline does not match... but it was good enough for our client.

However, here is how I managed to blank our biggest customers largest WebParts.

Background:
* SPFx 1.13.1 WebPart in production for a while and the client ordered a new major add-on before ESPC22, with was developed.

The update contained:
* New WebPart
* New Field Customizer
* New Command Set Customizer 

Blank Timeline:
* The update was deployed on the last working day before ESPC22 and as far as we knew was working as expected. 
* At some point the client noticed that one feature in the product was not working it did before (minor bug, let me know if you think it could be relavent)
* The bug was fixed and deployed on Wednesday
* The package was working on the Pre-Live site (with its own app catalog)
* Was deployed to tenant in the evening and I checked it one one of the Live sites (but not the problematic site)
* Thursday, the subsidiary of the client who uses the problematic site discovers that the pages are blank after we told them that the minor bug was fixed... fun.

Fix:
So as the above issue says, the only way to fix this is to delete app from the app catalog and re-install it and yes... I did try everything else before trying something this extreme on the client live tenant on something this crucial. 

Fix Notes:
* In a live production site that is being used actively and has its own app catalog this does not work... simply because you can't de-facto you can't access the site's second level recycle bin. However if the explanation the MS expert gave me is even close to the truth, then this should happen only in a tenant deployed app. (I will open a second issue about this.)
* IMPORTANT! - Once deleted and re-installed, make sure to update all the sites to the latest version of the app or they will not function as expected!

The issue as the MS Expert explained:
So as you can see in the **package-solution.json** I have the "features" filled. Namely he postulated that the SPFx version I had a bug that filled the array when it should not have when adding in a new WebPart and once deployed that will blank the package.

This explanation was good enough for our client, but I it just does not make sense it you look at the timeline. Namely the site that blanked was working with the minor bug version when ESPC22 started. The subsidiary who eventually blanked was the one that noticed the bug and reported it, but for them to report it they the package must have been deployed successfully before ESPC22.

### Steps to reproduce

Sry I am not 100% on this ATM

### Expected behavior

Update the package on SPO tenant app catalog and the WebPart should not blank

**Comment by AJIXuMuK** [comment]
@IllimarAtShareCloud
The explanation you received during ESPC can be absolutely correct.

In your case you have added extensions to the existing projects.
When you add an extension (and starting with 1.14 - any type of the component) it will add a new feature to the `features` list in the package-solution.json file.
As this feature doesn't have `componentIds` property it will collect all the components in the solution to be part of the feature.

As a result,
before adding the extension you had auto-generated feature for each web part with ID === id of the web part.
after adding the extension you have a new single feature with new ID that contains all the components.

In that case on SharePoint side you have a mismatch as the same component was part of one feature and then - another.
In your case the solution probably is to add componentIds to the new generated features, and include only extensions in there.
In that case all web parts should still have their own features.

You can check the features after running `gulp package-solution` in `sharepoint/debug` folder.

Let me know if that helps.

**Comment by IllimarAtShareCloud** [comment]
Amm... I ran the command in the folder, but I do not get what I got.

However, if I understand correctly the issue should be fixed in the latest SPFx that is out already. We where planning to simply update all of our packages to the latest version so we would not run into it again.

Could you please tell me in with SPFx version is safe to use. We usually keep our packages 1-2 versions behind the latest just in case.

**Comment by IllimarAtShareCloud** [comment]
ty for the info, ATM we can't update to 1.16.1 anyway because when we tested it we ran into this yesterday: 
https://github.com/SharePoint/sp-dev-docs/issues/8623

So we will simply stick with 1.13.1 and delete the tenant app before the update just to be safe.

**Comment by AJIXuMuK** [comment]
@IllimarAtShareCloud - yes, there is an issue in 1.16.1.
That's why we rolled back to 1.16.0 and will get back to 1.16.1 next week.
