### ISSUE TITLE
beta pages api returns "Operation not supported" error

### ISSUE THREAD

**Issue by wdamien** [SharePoint/sp-dev-docs#8636]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

React Native: v0.70.4 (ios and Android)
Postman: v10.5.2
MacOS 12.6

### Describe the bug / error

The beta Sharepoint /pages api (https://learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta) has stopped working for us (as of the morning of Dec 5, 2022).  We've been making the same API calls for years, but now we only get back a 400 `notSupported` error with this result:

```
{
    "error": {
        "code": "notSupported",
        "message": "Operation not supported",
        "innerError": {
            "date": "2022-12-06T19:19:04",
            "request-id": "866dd8a2-7cf1-4f55-b525-736842c97b8e",
            "client-request-id": "866dd8a2-7cf1-4f55-b525-736842c97b8e"
        }
    }
}
```

A sample GET call is: `https://graph.microsoft.com/beta/sites/<our_site_id>/pages?select=webUrl,id,title,lastModifiedDateTime`

From this post; https://devblogs.microsoft.com/microsoft365dev/announcing-the-new-sharepoint-pages-api-in-microsoft-graph/ it says the new beta API was going to roll out at the end of Nov, so the timing fits for this issue. It also says there will be breaking changes, but does not list what those change are.

Are there any updates we need to make to our Sharepoint site to work with the newly updated API?  Or are there updated docs for working with this api?

### Steps to reproduce

1. Make a REST get request to the /pages rest API 
2. API call fails

### Expected behavior

The API should load the pages from our SharePoint site.

**Comment by redlab-chris** [comment]
We get this error also for all endpoints of the new Pages API. But only in our M365 developer tenants (provided by Microsoft). In other test tenants we get unexpected / empty results of the new Pages API, see [this ticket](https://github.com/SharePoint/sp-dev-docs/issues/8644)

**Comment by kaffarell** [comment]
Hey, we get this error too. I found [this](https://developer.microsoft.com/en-us/graph/changelog/?search=sitePageData&filterBy=beta,Sites%20and%20lists) in the changelog. Could it be that the /pages endpoint has been removed?

**Comment by adamgronowski1** [comment]
I got this error too. Is this eventually going be fixed or are they just removing the /pages endpoint?

**Comment by wdamien** [comment]
According to public information from Microsoft they are committed to the pages api.

There's an announcement here: <https://devblogs.microsoft.com/microsoft365dev/announcing-the-new-sharepoint-pages-api-in-microsoft-graph/>
And even a video showing the new updates: <https://www.youtube.com/watch?v=8PLxh3RuNP0>

They just need to get whatever bug is affecting this latest beta fixed.

**Comment by adamgronowski1** [comment]
Great! Thanks for the update! I was concerned after kaffarell posted this changelog: https://developer.microsoft.com/en-us/graph/changelog/?filterBy=beta,Sites%20and%20lists&search=sitepagedata

I guess we'll just wait until it's fixed!

**Comment by BadgerCap** [comment]
The announcement mentions updates in 2 major areas (data model and page management capabilities with the list of core operations this enables).  It also mentions breaking changes, but I have not yet found where those are properly documented. 

The API reference page for "Get a page in a site" has an updated date of 12/8/2022.  This is the API call that is broken for us with "Operation not supported," but it clearly should still be supported according to the documentation.  Unless the documentation has not been fully updated yet, the "pages" endpoint has been removed in favor of another undocumented endpoint.

It would be good to get some kind of acknowledgement if this is a breaking bug (and a severe one at that) in the beta, or if it's a lack of updated documentation problem.

**Comment by redlab-chris** [comment]
Hi, seems like work is in progress..

The endpoints themselves seem to be working now but they return partial data. When I edit a page and add a new section, I get that data but not for existing/unmodified pages. Like for have many pages that I have that contain 1 section and 10 text web parts, none are returned. 

Can you please confirm that you are currently rolling out updates or is this a caching issue? Any transparancy on progress and ETA would be appreciated so our team can adjust the planning of their research using this API.

**Comment by divyachapan** [comment]
@wdamien  / @BadgerCap / @redlab-chris  : Can you check and confirm if this still repros for you? While our official "Beta roll out" announcement is delayed until Jan 2023 (due to several reasons), most of you should have the new beta API experience working.

**Comment by wdamien** [comment]
@divyachapan yes, for our organization the /pages api does load data now.  We do have a non blocking bug, thats probably a separate issue, but I'll mention it here anyways.  Attempting to load a page that contains a "Link" web part and expand its webParts, a 500 "generalException" error is returned.

Basically, sending this request for any page that has a Link web part, for example use; https://microsoft.com/ `https://graph.microsoft.com/beta/sites/<site-id>/pages/<page-id>?expand=webParts`

Returns:
```
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2022-12-22T15:33:24",
            "request-id": "e0f7f019-3d5e-40d2-8acf-d394b86551c6",
            "client-request-id": "e0f7f019-3d5e-40d2-8acf-d394b86551c6"
        }
    }
}
```

Other than that issue, everything else is working great for us.

**Comment by BadgerCap** [comment]
@divyachapan - I can confirm getting page content and expanding webParts is not working and not returning an error.

**Comment by BadgerCap** [comment]
@wdamien - I noticed that as well and it is documented as issue #8657

**Comment by redlab-chris** [comment]
Hi, I can confirm that most endpoints work as expected. Getting webparts is still not reliable though. For example expanding all pages in a site with webparts gives the error above for us. (maybe due to a link object but I cannot confirm that)

-> https://graph.microsoft.com/beta/sites/{site-id}/pages?expand=webParts
gives a "code": "generalException"
We will create seperate issues while testing the API in the coming period.

It would be appreciated when we are informed about major updates/downtime of this API @divyachapan so we can plan ahead with our team.

Looking forward to GA!

**Comment by divyachapan** [comment]
@redlab-chris : Absolutely. This issues list is where I intend to keep the audience informed. Thanks for the feedback!

**Comment by SjoerdV** [comment]
This worked for me:
`https://graph.microsoft.com/beta/sites/{sitesId}/pages/{sitePageId}?select=id,title&expand=webparts,canvaslayout`
also mentioned here: https://github.com/SharePoint/sp-dev-docs/issues/8636#issuecomment-1347258827 
Maybe @BadgerCap can confirm it working?

Writing an **update** of the webparts back to the page is a different matter, though. Can we also get a raw representation of the entire page in a format that is compatible with an update/put/patch? I will figure the json out myself then.

**Comment by SjoerdV** [comment]
> Try Append ‘?expand=canvasLayout’ to the URL to get the full page content

@divyachapan, For me that only returns the canvas properties and the horizontal+vertical sections, **without** the webparts... please advise 😉

**Comment by divyachapan** [comment]
Hi @SjoerdV : Would love to speak with you about this. Can you DM me in Twitter: https://twitter.com/dcpadur or in LinkedIn: https://www.linkedin.com/in/dcpadur/

**Comment by SjoerdV** [comment]
I'm so sorry, I forgot to deepdive the 'columns' node as well, so indeed the webparts are there. My bad.
canvasLayout > horizontalSections > columns> webparts

I would prefer to have the conversation where the action is, though. Great work on the Graph API.
