### ISSUE TITLE
Cannot import ES2020 module

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/sp-dev-docs#8638]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFX 1.16
Node 16.16.0

### Describe the bug / error

Trying to import a module that use the ES2020 format causes webpack to fail.

For example, trying to use latest radash (v9+), which is built as ES2020 module leads to errors:

````plain
Can't import the named export 'iterate' from non EcmaScript module (only default export is available)

.... long sequence of red lines ...

Module parse failed: Unexpected token (5:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const reduce = async (array, asyncReducer, initValue) => {
|   const initProvided = initValue !== void 0;
>   if (!initProvided && array?.length < 1) {
|     throw new Error("Cannot reduce empty array with no init value");
|   }
 @ ./node_modules/radash/dist/esm/index.mjs 2:0-94 2:0-94 2:0-94 2:0-94 2:0-94 2:0-94 2:0-94 2:0-94 2:0-94

````

I guess this is due the use of `array?.length` syntax in the emitted file.

Th previous major version of the library was producing a ES2019 module and was working perfectly.

### Steps to reproduce

1. using yeoman, bootstrap a new SPFX 1.16 project (type WebPart, using React)
2. Set "Repro" as name of the webpart
3. add radash as dependency `npm add radash@latest`
4. In the `ReproWebPart.ts` file add the top, just below the existing imports (code sample taken from the radash doc):

  ````
  import { alphabetical } from 'radash';
  const gods = [{
    name: 'Ra',
    power: 100
  }, {
    name: 'Zeus',
    power: 98
  }, {
    name: 'Loki',
    power: 72
  }, {
    name: 'Vishnu',
    power: 100
  }]
  
  alphabetical(gods, g => g.name) // => [Loki, Ra, Vishnu, Zeus]
  alphabetical(gods, g => g.name, 'desc') // => [Zeus, Vishnu, Ra, Loki]
  
  ````
5. run `gulp serve`
6. Open the workbench of some sharepoint site
   ==> the bundler **fails**

To see the difference: 

1. run `npm add radash@8.1.0`
2. `gulp serve` and open the workbench
3. This time, no error

### Expected behavior

SPFX project should be able to consume ES modules in recent versions.

**Comment by AJIXuMuK** [comment]
It is on TS4 but still there are other dependencies there.
This is in roadmap but not an issue.

**Comment by stevebeauge** [comment]
thanks for your reply

Any ETA ?
Any clue about which part is not compatible (playing with gulpfile.js is not an issue if needed) ?

thx

**Comment by AJIXuMuK** [comment]
@stevebeauge - unfortunately, no ETA.
There is a work in progress. But the changes are related to internal build tools.
Potentially, you can try externalize ES2020 modules. 
But not sure if it 100% helps.
