### ISSUE TITLE
Roles to install Clarity app on Sharepoint

### ISSUE THREAD

**Issue by bahgael-sobky** [SharePoint/sp-dev-docs#8641]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hello Sharepoint team,

Can you please guide me on whats the difference between the contributor role and site owner? Who has a higher privilege? and whats the role needed to install apps?

Thanks,
Bahga

**Comment by AJIXuMuK** [comment]
@bahgael-sobky - by default there is no "Contributor" role.
There is "Owner", "Member", and "Visitor".
You can see the roles and applied Permission levels by going to Site Settings -> Site Permissions.
If you want more details on each permission level, you can click on Permission Levels button in the ribbon on that page.

But your specific question about the apps is answered [here](https://learn.microsoft.com/en-us/sharepoint/administration/add-apps-for-sharepoint-to-a-sharepoint-site#add-apps-for-sharepoint-to-sharepoint-sites):

> Verify that the user account that is performing this procedure is a member of the site Owners group.
