### ISSUE TITLE
Teams web site tab with SharePoint site page doesn't load returning SDK initialization timed out error

### ISSUE THREAD

**Issue by patrikhellgren** [SharePoint/sp-dev-docs#8642]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams App team tab

### Describe the bug / error

We have for several years been using web site tabs in Teams to display SharePoint site pages with SPFx webparts/extensions but a few weeks ago this stopped working. All that is displayed when we go to one of those tabs now is the SharePoint logo and nothing else happens.
The reason that we need to use web site tabs instead of SharePoint tabs is that it is that Graph only supports creating web site tabs with configuration, SharePoint tabs is only supported to be created without configuration. Since we do alot of provisioning of the tabs this is a no-go for us.
SharePoint library pages with SPFx extensions can still be displayed using web site tabs, it only seem like site pages has the issue.

This happens in both Teams in the browser and in the Teams app.

We see this issue in multiple tenants.

We have also tried raising this issue with MS Support through the contact support panel in the admin console but they just said that we should use SharePoint tabs and doesn't seem to understand the real issue since it is more of a developer related one.

The following error is logged in the browser console when loading the tab:

Uncaught (in promise) Error: SDK initialization timed out.
    at e.exports.e.initialize (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:188078)
    at e._initialize (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:108609)
    at new e (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:108838)
    at e.getInstance (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:108923)
    at e.getTeamsV2SDKInitializer (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:114935)
    at e._getTeamsSDKInitializer (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:115131)
    at sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:122611
    at new Promise (<anonymous>)
    at e._setTeamsAppEntityIdLocalStorage (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:122579)
    at e.onBeforePageLoad (sp-teams-lib_en-us_aadf626ba98cc1a8678b.js:1:112723)

### Steps to reproduce

1.Create a SharePoint site page with som webparts on it
2.Create a Team and in the General channel create a new tab of type web site
3.Set the url of the web site tab to the url of the page created in 1
4.When going to this tab it will only display the SharePoint logo

### Expected behavior

The SharePoint site page should be displayed correctly.

**Comment by AJIXuMuK** [comment]
@patrikhellgren - unfortunately, I will tell you the same as MS Support.
Website app is not intended to load SP pages. It should be used for non opinionated websites.
We don't support such a scenario. It could work in some scenarios and don't work in others. It may also stop working in future.

From other side, the case with MS Graph is valid and I have started an internal conversation to allow static configuration for SharePoint App.
No promises here though.
