### ISSUE TITLE
New release of Graph Pages API does not return any Webparts

### ISSUE THREAD

**Issue by redlab-chris** [SharePoint/sp-dev-docs#8644]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

The Graph endpoint for getting Webparts for a SharePoint page always returns an empty array or a Bad Request - 400.
There are 3 methods of getting Webparts for a page as
https://learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta

1. Tested in Graph Explorer with different pages:
https://graph.microsoft.com/beta/sites/{site-id}/pages/{pageId}/webparts

This always return an empty array:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#sites('{site-id}')/pages('{page-id}')/webParts",
    "value": []
}

2. GET /sites/{sitesId}/pages/{sitePageId}/canvasLayout/verticalSection/webparts
The following endpoint just gives a "Bad Request - 400".

![image](https://user-images.githubusercontent.com/73823734/206857132-467d2864-5597-430b-adab-8b9cfc76942d.png)

3. GET sites/{sitesId}/pages/{sitePageId}/canvasLayout/horizontalSections/{horizontalSectionId }/columns/{horizontalSectionColumnId}/webparts

In order to use this endpoint I should first get the horizontalSectionId:
GET /sites/{sitesId}/pages/{sitePageId}/canvasLayout/horizontalSections
This also just gives a "Bad Request - 400".

So I cannot retrieve any information about the Webparts. Seems that these API's are not working yet? Any ETA?

### Steps to reproduce

1. Create a SharePoint page. Add 1 text block with text 'test' and set title to 'test graph page'
2. Log into Graph Explorer and use the list pages endpoint to get the Id of the just created page
https://graph.microsoft.com/beta/sites/{site-id}/pages
3. With the page id, run: https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}/webparts

### Expected behavior

Expected is to get 1 webpart for the text entered in the newly created page

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#sites('site')/pages('page')/webParts",
    "value": [ {EXPECTED WEBPART DATA} ]
}

**Comment by redlab-chris** [comment]
Hi, seems like you're fixing this API :-) 
I get some webpart data but not all of it. When I edit a page and add a new section, I get that data but not existing/unmodified pages. Can you please confirm that you are currently rolling out updates or is this a caching issue? I can do some further tests if that would help in my region. Let me know.. Other tenants still have the 'operation not supported' issue by the way. Is this a deliberate status in the meantime that updates are rolled out? Any ETA would be appreciated.

**Comment by BadgerCap** [comment]
@redlab-chris - Based on testing I've been doing with API as it's currently deployed, the endpoint format for retrieving the webParts collection might now be:

`https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}?expand=webParts`

It's still not 100% working, and I opened up a bug report #8657 about a specific issue I did see while working on breaking changes in this updated API.

**Comment by divyachapan** [comment]
@redlab-chris : Does this still repro? We were in the middle of code rollout and had some issues which we think have been resolved. Can you please check and confirm?
