### ISSUE TITLE
AppCustomizer doesn't support components

### ISSUE THREAD

**Issue by sallaadithya** [SharePoint/sp-dev-docs#8649]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.16.1
- Node.js version 16.18.1

### Describe the bug / error

I have created a new application customizer using SPFx v1.16.1, works fine with out any issue.
But when a component is introduced to replace the hard-coded html string, the application fails to run, it used to work in previous versions. 
I have followed the [article](https://social.technet.microsoft.com/wiki/contents/articles/52751.using-react-components-in-spfx-extension-application-customizer.aspx).

### Steps to reproduce

1. Make sure the SPFx version 1.16.1
2. Follow the [article](https://social.technet.microsoft.com/wiki/contents/articles/52751.using-react-components-in-spfx-extension-application-customizer.aspx)

### Expected behavior

The application should run without any issues though a custom component is used.

**Comment by AJIXuMuK** [comment]
@sallaadithya - could you specify what error are you experiencing?

**Comment by sallaadithya** [comment]
I have created a document to re-produce the issue, thanks it got re-produced.
[SPFxAppCustomizerError.docx](https://github.com/SharePoint/sp-dev-docs/files/10235007/SPFxAppCustomizerError.docx)

Please let me know if you need more information, happy to have a call if you want.

**Comment by AJIXuMuK** [comment]
@sallaadithya - have you added `react` and `react-dom` (and also typings) as dependencies to your solution?
You can check that by looking at `package.json` file.

**Comment by sallaadithya** [comment]
I created the solution as I used to do in previous versions. In short, when we create application customizer using yeoman, it never asks us to select 'react' framework.
To answer your question: NO, I have not added react as dev dependencies (as I never did in previous versions also) and there was no compile or runtime error when I created a custom component or on webpart.ts file.

My suggestion is to please create a vanilla App customizer, create a custom component, refer it in webpart file, I think you should able to re-produce the issue. If you have 1.15.2 SPFx version installed on any machine, please try the same steps, your application should work fine with out any issue.

**Comment by sallaadithya** [comment]
When trying to install react and react-dom, I encourted an issue.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/39057966/208078549-c88c6bb5-8490-46ae-b3ba-ad2275d114f7.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/39057966/208078731-f073c3f1-87a7-4a2b-bf27-7108ead0ec67.png">

**Comment by AJIXuMuK** [comment]
@sallaadithya - you have to install `react` and `react-dom` with version `17.0.1`.
You're trying to install `1.17.0`.

Major version 1 instead of 17

**Comment by sallaadithya** [comment]
Sorry, my bad, after installing the dependencies, application is working fine.
I ran the following command:
npm i react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact

Thanks for all the support.

Hope it helps someone!!
