### ISSUE TITLE
Calendar Formatting documentation is incomplete

### ISSUE THREAD

**Issue by calebmil** [SharePoint/sp-dev-docs#8651]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

As a first-time user of calendar view formatting, I attempted to recreate the steps outlined in the article https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-calendar-formatting but was unsuccessful implementing the steps as written.

**Problem**
When a new calendar view is created on a list, fields that are not available to be edited using the Modern Calendar view editor control are not included in the view definition (i.e. any fields other than title, start and end date are not added).  When a user who is new to modern view configuration tries to add the JSON to the advanced formatting of the view, the formatting interpreter cannot find the field name "PROJECT" in the view definition and defaults to the "no matching value found" use case.

** Solution **
Provide instructions in this article that tell the user to edit the new Calendar view through the List Settings page and add the "PROJECT" field to the list of fields to be displayed.  This will add the field to the view definition and make it available for the custom formatting interpreter to find the appropriate field to use in the formula.

**Comment by calebmil** [comment]
Happy to write this up if an admin wants to assign this issue to me.

**Comment by Fedes365** [comment]
Hi @calebmil, I tried to improve the article. Let me know if further changes are needed.

Alternatively, feel free to fork the sp-dev-docs repository and submit a change to be merged.

See you!

**Comment by calebmil** [comment]
@andrewconnell I took a look at the note about making sure that the PROJECT column already exists before creating the calendar view.  My experience was that the PROJECT column is consistently NOT added to the Calendar view whether it exists at the time of view creation or not.  The pointer to go to List Settings and add the column to the view through the Classic view editing interface is what solved my problems.

**Comment by andrewconnell** [comment]
@calebmil If there's an error with the docs, please create a new issue (feel free to reference this one).
