### ISSUE TITLE
SPFx webpart added in Site collection app catalog but says deployed No

### ISSUE THREAD

**Issue by itzkeshav** [SharePoint/sp-dev-docs#8654]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description
I am able to upload SPFx web part package to the App Catalog. But unlike my other SP online team sites, the Pop-up to deploy the app is not coming. Moreover the options for Apps in the app catalog ribbon Files Tab("View Details Page", "Manage Installed Apps", "Deploy") are also not there.

As per my testing, there is no problem in the app package as it is getting deployed in other site collection's app catalog and working fine.

Can anyone please point what's wrong with this scenario and how to resolve this?

<img width="925" alt="error" src="https://user-images.githubusercontent.com/50790789/207908694-253c70af-3e35-4c5a-94fb-e4c41aef31e4.png">

**Comment by AJIXuMuK** [comment]
@itzkeshav - your "Apps for SharePoint" list looks a bit weird to me.
It is missing "Apps" section in the ribbon completely.
Do you have appropriate permissions to work with apps?
Also - could you please check that the app catalog is still enabled for the site collection. Maybe it was enabled and then disabled.

**Comment by itzkeshav** [comment]
Hello, 
It was a permission issue. Tenant admin and SCA were able to publish app. Thank you!

**Comment by itzkeshav** [comment]
Hello,
It was a permission issue. Tenant admin and SCA were able to publish app. Thank you!
