### ISSUE TITLE
React MTG SPX component not showing all people in SPFX webpart  - SharePoint Online

### ISSUE THREAD

**Issue by teresahoes** [SharePoint/sp-dev-docs#8656]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Version 108.0.1462.46 (Official build) (64-bit)
- SPFx version - 1.13.0
- @microsoft/mgt-react:  2.5.2
-@microsoft/mgt-spfx:  2.5.2
- Node.js version - 16.x

### Issue description

Hello,

I am using the @microsoft/mgt-react/dist/es6/spfx component in a webpart on Sharepoint online. Searching does not find some people who are active members of the associated Active Directory. Here is component code in the webpart. 

              <PeoplePicker
                type={PersonType.person}
                selectionMode="single"
                selectionChanged={handleSupervisorChanged}
                selectedPeople={selectedPeople}
              />

My question is - how does the component determine who should show up when searching and what might cause people to NOT show up?

**Comment by teresahoes** [comment]
Im wondering if its excluding them because its a 'relevant' search

**Comment by AJIXuMuK** [comment]
@teresahoes - this question is related to MGT itself, not SharePoint Dev.
Please, ask this question in [MGT Repo](https://github.com/microsoftgraph/microsoft-graph-toolkit)
