### ISSUE TITLE
Beta API pages endpoint: Error when expanding webParts collection that contains a Link Web Part

### ISSUE THREAD

**Issue by BadgerCap** [SharePoint/sp-dev-docs#8657]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Tested using latest version of Insomnia.

### Describe the bug / error

In SharePoint Beta API, using the pages endpoint to retrieve Site Page content using the following URL:

`https://graph.microsoft.com/beta/sites/(siteGuid)/pages/(pageGuid)?expand=webParts`

If the page contains a Link WebPart, the following error is received:

`{
  "error": {
    "code": "generalException",
    "message": "General exception while processing",
    "innerError": {
...
    }
  }
}`

Removing the Link Web Part from the Site Page allows endpoint to return the requested page metadata and webParts collection.
Removing `?expand=webParts` and get having the endpoint just return the page metadata also works as expected. 

### Steps to reproduce

1. Create a Site Page in SharePoint Online that contains a Link Web Part
2. Call the SharePoint Beta API to retrieve the content after proper OAuth authentication
3. Result is a 500 Internal Server Error with message "General exception while processing"

### Expected behavior

Call to endpoint results in a 200 OK response with the page metadata and webParts collection expanded and containing all Web Parts.

**Comment by BadgerCap** [comment]
Likely related to #8636

**Comment by divyachapan** [comment]
@BadgerCap : This is related to the new API roll out, but we believe the new code rolled out may also have a bug resulting in this error above. That fix will start rolling out early/mid January after the holidays (and be world wide in Feb). I will keep this post updated when I have more to share

**Comment by divyachapan** [comment]
This issue has been resolved. Closing this out
