### ISSUE TITLE
Application customizers cannot find manifest off new build from 1.16.1

### ISSUE THREAD

**Issue by kmartindale** [SharePoint/sp-dev-docs#8660]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx 1.16.1 - new install 

### Describe the bug / error

Application customizers cannot find manifest off new build from 1.16.1 You'll see the initial dialog box from the new build after serve, but if you check the dev tools console you'll see the error below. It seems to get caught on the promise resolve in the onInit

Error Message:
`Failed to load component "80ff3a82-8833-4c84-81fd-de539415c7b2" (TopPlaceholderApplicationCustomizer). Original error: Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "17.0.2".`

Dependencies:
`"dependencies": {
    "tslib": "2.3.1",
    "@microsoft/sp-core-library": "1.16.1",
    "@microsoft/decorators": "1.16.1",
    "@microsoft/sp-dialog": "1.16.1",
    "@microsoft/sp-application-base": "1.16.1"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.16.1",
    "@microsoft/eslint-config-spfx": "1.16.1",
    "@microsoft/sp-build-web": "1.16.1",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "typescript": "4.5.5",
    "@microsoft/sp-module-interfaces": "1.16.1"
  }`

### Steps to reproduce

1. Setup Dev Environment with 1.16.1
2. Build new application customizer package
3. Gulp Serve - error located in dev tools console

### Expected behavior

That I serve and the application customizer loads as expected.

**Comment by sallaadithya** [comment]
I had the same issue, after having the dependencies installed, the error went away.

Please run the below command:
npm i react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact
