### ISSUE TITLE
Error loading debug manifests

### ISSUE THREAD

**Issue by ujavai2s** [SharePoint/sp-dev-docs#8666]
Hi
I have tried to implement this [tutorial](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx) .  But as soon as include, react-dom and react in ColorPickerDialog.tsx file, extension works no more and receive this message.
![image](https://user-images.githubusercontent.com/1612262/209834005-764b5772-953d-446e-99c2-902d1437fd5f.png)

My setup detail is 
![image](https://user-images.githubusercontent.com/1612262/209834133-7cb0f5ff-da49-4508-b701-bf0f24717cd2.png)

and node version is v16.18.1

Any feedback will be very helpful

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f02c0a61-69ec-736e-2f49-d36bfe6cdddf
* Version Independent ID: 2eda912c-ebc1-f287-9c1a-656364e59457
* Content: [Tutorial - Use custom dialog boxes with SharePoint Framework Extensions](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx)
* Content Source: [docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@ujavai2s - have you installed React and ReactDOM as dependencies to your project?
See this issue: https://github.com/SharePoint/sp-dev-docs/issues/8660
