### ISSUE TITLE
github - Column Graph format

### ISSUE THREAD

**Issue by rahmad010** [SharePoint/sp-dev-docs#8668]
Hi Community / Anoop
I am trying to repurpose formatting jason posted here - https://github.com/pnp/list-formatting/tree/master/view-samples/column-graph
I am working on creating dynamic column graph format out of my Microsoft list, wanting to see status of open position (list has a column named status that has different status including fulfilled, new, open, in-progress etc.) for different role types (Pm, developer etc.) by count or assignee. 
Reaching out to get your help in modifying existing jason to get the expected bar graph (than #views/blog).
Can you please suggest changes or share updated jason to achieve bar graph to show count of status type by role type OR count of status by value. 
Attaching the list for reference. 
![MS List](https://user-images.githubusercontent.com/121617360/209979241-ebfab204-688b-4e79-bd8c-178863e518f0.JPG)

**Comment by VesaJuvonen** [comment]
Any issue related on the community provided samples should be created on the specific repositories - in the case of this sample, the location would be https://github.com/pnp/List-Formatting/issues

This issue list is for the issues in the product and in the documentation
