### ISSUE TITLE
Command Set Extension: this.context.listView.columns is empty array

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#867]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
`this.context.listView.columns` in Command Set provides a list of list view's column
#### Observed Behavior
It WORKS well ONLY in Lists on DEV tenants
It DOESN'T work in document libraries on DEV tenants and First Release tenants
It DOESN'T work in Lists on First Release tenants

Under "doesn't work" I mean that `this.context.listView.columns` is always an empty array.

#### Steps to Reproduce

- scaffold command set
- add code to log columns value (`console.log(this.context.listView.columns`)
- debug the extension in lists and doc libraries on DEV and First Release tenants

**Comment by sharepointknight** [comment]
I have experienced the same behavior. My only change to what was reported is that in my test, it doesn't work on a custom list on my DEV tenant. I get the empty array for the listview.columns.

**Comment by ravinleague** [comment]
is there an update on this bug ?

**Comment by AJIXuMuK** [comment]
Hi @ravinleague ,
I would say that now it works but still with issues.
[Here](https://github.com/SharePoint/sp-dev-docs/issues/1242) is another bug related to the `this.context.listView.columns`

I would recommend to get view id from legacy page context or query string (if presented) and request fields using REST API or PnP JS

**Comment by AJIXuMuK** [comment]
Still can reproduce this one on Standard Release tenant.
On First Release I can repro #1242

**Comment by patmill** [comment]
This should be released WW now.
