### ISSUE TITLE
Application customizers don't work when adding office ui fabric react library as external library.

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#868]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Referencing Office UI Fabric React javascript library as externals in your spfx application customizer should work on all pages.

#### Observed Behavior
If you use office ui fabric react in your application customizer, e.g. Top Placeholder and referencing the library as externals in package.json the application customizer will not get loaded. If you bundle the react components from ui fabric into your application customizer it works just fine. But since the bundle size gets really big, it should be possible to reference it as external library in config.json.
This is not true on modern pages. It works there. But it does not work on modern recycle bin page, modern site content page, modern libraries or modern lists.

#### Steps to Reproduce
create an application customizer with latest 1.2.0 spfx release and use a office ui fabric react component. E.g. a Button. Clone the office ui fabric react repo and build an umd bundle and upload the ui fabric react library (4.32.0) to a cdn and reference it as external in your config.json instead of bundling it into your customizer. Use the loadSPFX querrystring to test your application customizer and try it on the modern site content page or modern recycle bin page.

**Comment by mpasarin** [comment]
Our guidance ( https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/office-ui-fabric-integration ) is that you statically link Office UI Fabric when building, and not use it from an external.

From the document itself:
Understanding this approach and its shortcomings:
* Components in your web part are locked to the version of Fabric React you used when you built the web part. They will not automatically evolve with the surrounding page. You will need to manually update your web part to adapt to newer versions of Fabric React.
* The page may be less performant as it may load more CSS, but it will be reliable.
* Static linking bloats up your web part bundle, but dynamic linking is too fragile considering future updates to be introduced in SharePoint Online. Static linking is the only approach that is officially supported when Office UI Fabric React is being used in SharePoint Framework solutions.
