### ISSUE TITLE
SharePoint Graph new Pages API: no webPart data returned for some sites

### ISSUE THREAD

**Issue by redlab-chris** [SharePoint/sp-dev-docs#8680]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

For some sites, the Graph endpoint that should return webpart data does return an empty array.

https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}?expand=webParts
or
https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}/webParts

returns:

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#sites({site})/pages({page})/webParts",
    "value": []
}

For other sites, the endpoint does return data.

### Steps to reproduce

1. This cannot be reproduced because it depends on the my site/page Id's.

### Expected behavior

All our sites return webpart data. This is probably due to code rollout but we are actively testing the API and it would be very appreciated (if you can control it) that our sites in our tenant do return webpart data.

Question: if you can enable this for all of our sites, please contact me on chris@isoplanner.app so I can give tenant & site Id's.

**Comment by divyachapan** [comment]
@redlab-chris : Can you try this again and let me know if you are still seeing this error?

**Comment by redlab-chris** [comment]
Yes still having this error for some sites. For those sites, we also get an error while expanding the webParts for all pages in the site using:
https://graph.microsoft.com/beta/sites/redlabapp.sharepoint.com,b2c6a78f-771a-4c4d-b681-47171dbc90e8,2a2f8caa-8baa-4c99-8133-feda60e2426c/pages?$expand=canvasLayout
or:
https://graph.microsoft.com/beta/sites/redlabapp.sharepoint.com,b2c6a78f-771a-4c4d-b681-47171dbc90e8,2a2f8caa-8baa-4c99-8133-feda60e2426c/pages?$expand=webParts

![image](https://user-images.githubusercontent.com/73823734/213504692-f3182696-1b38-4439-b8eb-e88ce1507dd8.png)

**Comment by redlab-chris** [comment]
Another but probably related thing is that we sometimes don't get an error but no webParts. For a single page:

https://graph.microsoft.com/beta/sites/365redlab.sharepoint.com,c006d14d-1e79-4dc1-9048-9ec48991f220,46067dc3-f26c-414e-a048-994708d6bfd1/pages/7f0c7ae3-7c86-46bd-bb66-e0f6e2e9f85a?expand=webParts

or for all pages in the site:

https://graph.microsoft.com/beta/sites/365redlab.sharepoint.com,c006d14d-1e79-4dc1-9048-9ec48991f220,46067dc3-f26c-414e-a048-994708d6bfd1/pages?expand=webParts

result fragment for webParts:
            "webParts": []

while the page has 1 text web part:

![image](https://user-images.githubusercontent.com/73823734/213514962-42733278-cff3-4505-aa2f-fc50d6b569cb.png)

**Comment by divyachapan** [comment]
Issue resolved. Closing thread
