### ISSUE TITLE
Permission Error with Form Customizer for new form

### ISSUE THREAD

**Issue by ThomasJuettner** [SharePoint/sp-dev-docs#8683]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- OS: Windows 10
- Browser: Microsoft Edge v108.0.1462.54
- Tooling: VSCode, SPFx v1.15.2
- Framework: Node.js v16.18.1
- SPFx Settings: Component type: Extension, Extension type: Form Customizer, Template React

### Describe the bug / error

**Background**
To display a Workflow scenario in SharePoint I implemented a "SPFx Form Customizer" to replace the SharePoint default form.
The SharePoint site uses a custom permission structure, where the visitors of the site would be allowed to create list items, but not edit them later (see Screenshots).

**Bug**
When the visitor tries to open the custom form through the "New" button or while trying to access it with a link ending with "/SPListForm.aspx?PageType=8" (with only the permission "Add items") they get the "Access denied" error message.

**Tests**
After further testing, the visitor can only open the new form after they get the "Edit Items" permission.
The default form allows this behaviour without the custom form, meaning they can create a list item but can't edit them after submitting.

Since the visitor technically should only be allowed to create items but not edit them in a later step, giving them the "Edit Items" permission would not be an ideal step.

In additional tests i checked if this error only occurs with the mission Permission "Edit Items". I gave the user all Permissions except that permission and the bug stayed the same.

When recreating this but with a blank new Form Customizer and running it locally, the same error happens.

**Screenshots**
Text is displayed in german, displayed the custom permission level with the selected (and intended) permissions
![image](https://user-images.githubusercontent.com/122095431/211016596-c5a6290a-d816-4bc6-b816-e4b407580cdb.png)
![image](https://user-images.githubusercontent.com/122095431/211016709-20649399-2449-48eb-806b-51267c8ece97.png)

### Steps to reproduce

1. Create an empty list on a SharePoint site
2. Replace the default form with a "SPFx Form Customizer" (either locally or adding it to the site)
3. Add a custom permission level to the SharePoint Site
4. Allow this permission level to have following permissions: "Add Item" (and any other necessary permissions)
5. Give a test-user the newly created permissions (via SharePoint-Group or in the list permissions directly)
6. Open the list and press the "New" button with the test-user

**Note**
If you add the "Edit Items" permission to the permission level you will be able to open the form

### Expected behavior

**What happens if you follow the steps**
The form cannot be accessed and instead the "Permission denied" page will be displayed.

**What i expected would happen**
The form would be displayed, and the user should be able to create a new item.

**Comment by AJIXuMuK** [comment]
this should be rolled out WW by now
