### ISSUE TITLE
SPFx webparts fail when showing older version in page history

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#8684]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Describe the bug / error

When showing an item from the version history of a page in SharePoint Online, our custom webparts don't load anymore, and they throw an error:

> ERROR:
> Cannot read properties of undefined (reading 'webPartTag')
> 
> CALL STACK:
> TypeError: Cannot read properties of undefined (reading 'webPartTag')
>     at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:1381319

### Steps to reproduce

- Create a SharePoint page.
- Add a custom SPFx webpart to the page
- Publish the page
- Edit the page, and republish
- Show the "old" version from the Version History

### Expected behavior

The webparts should be loaded properly when opening an older version from the page.

**Comment by NickSevens** [comment]
@AJIXuMuK is anyone looking into this? Or is there anything you might share time-wise?

**Comment by AJIXuMuK** [comment]
@NickSevens - sorry for the long delay.
I was trying to repro it multiple times and all seems to be working fine.

![image](https://user-images.githubusercontent.com/17036219/229233576-e3fdb59c-76b7-4b60-9cf8-a15ab3ad0729.png)


Could you please try repro it again? If that's still the case for you with the steps you provided above - is it possible to share the tenant/test account with me? You can use aterentiev@microsoft.com to share it.

**Comment by NickSevens** [comment]
@AJIXuMuK I've relayed the issue to my colleagues who are currently working for the customer. They will contact you and send you the necessary details.

**Comment by debeufk** [comment]
@AJIXuMuK I've provided you the details (via email) regarding the login to the customer's tenant. Thank you for your time regarding this issue.

**Comment by AJIXuMuK** [comment]
I was unable to repro it even on the shared tenant.
Closing for now.
