### ISSUE TITLE
Cannot read properties of undefined (reading 'id') in app customizer list view command set

### ISSUE THREAD

**Issue by arma78** [SharePoint/sp-dev-docs#8688]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

npm 9.2.0
node v16.15.0
gulp 
CLI version: 2.3.0
Local version: 4.0.2

 @pnp/cli-microsoft365@6.1.0
├── gulp-cli@2.3.0
├── gulp@4.0.2
├── npm@9.2.0
└── yo@4.3.1

 npm -v @microsoft/generator-sharepoint
9.2.0

### Describe the bug / error

After I locally tested app it works fine.
But in the dev tenant environment thru VM I am getting same error for all list view command set projects whenever I include components.(In this case my custom component that use import { BaseDialog,} from '@microsoft/sp-dialog';)

![image](https://user-images.githubusercontent.com/37850817/211540990-469509fc-a03e-41fb-bb41-5b8f90fa57bc.png)

![image](https://user-images.githubusercontent.com/37850817/211538570-88ae8570-1e12-4d79-ad5d-837f1fdbeef1.png)

Thank you in advance.

### Steps to reproduce

gulp serve

### Expected behavior

![image](https://user-images.githubusercontent.com/37850817/211541525-78adb96c-5d27-4a6f-a031-6cc2e8024658.png)

**Comment by AJIXuMuK** [comment]
@arma78 - have you added dependencies to `react` and `react-dom` and the typings as mentioned in #8649?

**Comment by arma78** [comment]
Thank you Alex Terentiev, that helped me to soleve the issue.
Cheers!
