### ISSUE TITLE
SPFX - PnP JS Core for SPFx On-Premise v1.0.2

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-docs#869]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I want to use PnP JS Core in SPFx **v1.0.2** React webpart for SP16 On-premise server .

- What is the version of pnp need to use and how to install it?
- What are the other options for accessing data in SP with this version(1.0.2)?

**Comment by mcmynn83** [comment]
@VesaJuvonen - Can you answer the version question?

REST and CSOM are both available on prem in the same way that it is available in SPO.

**Comment by patrick-rodgers** [comment]
@geogikk92 - please [see my response](https://github.com/SharePoint/PnP-JS-Core/issues/600) to your original issue.

**Comment by VesaJuvonen** [comment]
Resolved in the https://github.com/SharePoint/PnP-JS-Core/issues/600, so closing this one. All good and works.
