### ISSUE TITLE
Pages API Preview +  Graph PowerShell SDK V2 - are cmdlets available?

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#8691]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Using the Beta Pages API

### Issue description

I am trying to use the Graph Pages API Preview with Graph PowerShell SDK V2, is this supported?
Using "Microsoft.Graph 2.0.0 preview2" PowerShell Module

I am getting error the cmdlet isn't found but its available according another command, any ideas?

![image](https://user-images.githubusercontent.com/8781041/211680615-2c3d0273-dad7-4e5d-8d5c-e44223644a9b.png)

**Comment by divyachapan** [comment]
@pkbullock : Please see https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1742. 

We've just release 2.0.0-preview3, which has the webparts commands - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview3. The API was added to the public global CSDL metadata during the holiday freeze window after our last release of the year (12/20). We've now resumed our weekly deployment schedule.
