### ISSUE TITLE
Is TypeScript 4.9 supported in SPFx 1.16?

### ISSUE THREAD

**Issue by smolattack** [SharePoint/sp-dev-docs#8701]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

If so, how do I set it up. Rush-stack compiler seems to go up to v4.5 and no higher

**Comment by AJIXuMuK** [comment]
@smolattack - as you correctly mentioned, rush stack compiler supports v4.5, and SPFx is based on the same version as of now.
