### ISSUE TITLE
Microsoft Teams spfx webpart - error initializing application error cannot read properties of undefined (reading 'componentType')

### ISSUE THREAD

**Issue by amirmsai** [SharePoint/sp-dev-docs#8702]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version V16
- Node.js version v16.13.1
- SPFx for Teams used Teams Toolkit

### Issue description

Microsoft teams and SPFx 16
We are deploying spfx webpart to microsoft teams (in base of Teams Toolkit) and the site: https://learn.microsoft.com/de-de/microsoftteams/platform/sbs-gs-spfx?tabs=vscode%2Cviscode&tutorial-step=1
I receive this error: Fehlerdetails: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')
Any idea please ?
Best regards
Amir MSAI

**Comment by AJIXuMuK** [comment]
@amirmsai - could you provide details on when you're getting this error?
what is the call stack?

are you calling teams-js `initialize` in your code?

**Comment by amirmsai** [comment]
@AJIXuMuK  sorry i dont have any details to describe the error; in debug it working good, but if i install the solution in my Teams i receive this error 
![image](https://user-images.githubusercontent.com/44868971/213093281-52e81b77-d841-4a30-b64b-66f61db6b88d.png)

**Comment by AJIXuMuK** [comment]
@amirmsai - you should not call `initialize` by yourself.
We initialize the sdk for you. You just need to use the instance provided by web part's context (`this.context.sdks.microsoftTeams`).

**Comment by amirmsai** [comment]
Hi @AJIXuMuK  it's not working, i have the same error:  Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

**Comment by AJIXuMuK** [comment]
@amirmsai - could you share your code? You can send it to me directly using aterentiev@microsoft.com

**Comment by amirmsai** [comment]
@AJIXuMuK  E-mail has been sent
Thanks

**Comment by AJIXuMuK** [comment]
The solution, local debugging and deployment using both SPFx generator and Teams Toolkit work fine for me.

@amirmsai could you try to create a new solution from scratch and double-check your user has appropriate permissions to install apps both to SharePoint and Teams.
