### ISSUE TITLE
TypeScript 4.5.5 is over one year old. Could we have an update please?

### ISSUE THREAD

**Issue by smolattack** [SharePoint/sp-dev-docs#8715]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version1.16.1

### Issue description

A lot of modern npm packages can't be used in SPFx anymore because the bundled TypeScript version is too old. Is there a workaround for installing 4.9? When will SPFx support TS 4.9?

**Comment by AJIXuMuK** [comment]
@smolattack - we have TypeScript bump in our backlog

**Comment by smolattack** [comment]
@AJIXuMuK  v1.18 still uses 4.5.5. Are you sure de-prioritizing a Typescript version bump is the right call?

**Comment by lafe** [comment]
I saw that as well. I understand that supporting new features is an important part of updates, but this should not come at the expense of keeping the fundamentals at such old versions. SPFx is the only project I know of that encapsulates the whole build process in this way and it's a very frustrating experience...

**Comment by AJIXuMuK** [comment]
The version has been bumped in 1.18

**Comment by lafe** [comment]
> The version has been bumped in 1.18

That's not really an improvement - TypeScript 4.7 was [released](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/) in May 2022. Currently we have October 2023, so almost 1.5 years later...
