### ISSUE TITLE
Read Tenant wide Extensions - Component Properties

### ISSUE THREAD

**Issue by Nevinia210** [SharePoint/sp-dev-docs#8718]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version (1.15.2)
- Node.js version (16.15.0)
- etc

### Issue description

Is it possible to read Tenant Wide Extensions - component properties directly from spfx application customizer solution?
if yes, how? :)

**Comment by VesaJuvonen** [comment]
You can simply call `this.properties.[propertyname]` in the code as shown in the following tutorial - https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions

as long as you have the matching property names defined in the tenant wide extension list and in the component. When component loads based on the definition in the tenant wide deployment list, instance properties will be mapped based on the Component Properties values in the Tenant Wide Extensions list.

Example JSON in the Component Properties field in the list
``` JSON
{"tenantId":"", "defaultPath":"/library/documents", "isTenantWideDeployed":true}
```

This would assume that you have tenantId, defaultPath and isTenantWideDeployed properties in your SPFx component - as the component is instantiated runtime - those values in the list would be mapped for the instance.
