### ISSUE TITLE
SPFx teams tab activity notifications

### ISSUE THREAD

**Issue by SantanuPati** [SharePoint/sp-dev-docs#8719]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Getting error as “multiple teams application is linked with this Azure AAD app”.
What will be the solution for SPFx teams tab for activity notifications …as one AAD app can be linked with only one Teams app for sending activity notifications. So if we want to deploy multiple SPFx teams app in the same tenant with activity notifications what are the options

**Comment by AJIXuMuK** [comment]
@SantanuPati - I'm assuming you're using MS Graph to send the notifications.
Could you please add `teamsAppId: <guid-of-your-app>` to the body, where `<guid-of-your-app>` is the id of the custom teams application (if the manifest is auto-generated - it is the id of the web part from the web part manifest)?

It should bypass the error.
Please, let me know if that works.

**Comment by SantanuPati** [comment]
@AJIXuMuK  - Thank you very much for your quick response.

It did work for me. Although with a little bit of modification. It will be helpful if you can provide some light on this-  
First of all, yes, I am using MS Graph to send the notifications. And created the manifest using VS Code teams toolkit extension.

Although what I noticed here is, if we are mentioning the teamsAppId as <guid-of-your-app> (which gets auto generated in the teams manifest and in the teams Admin center this id shows as External app ID)- my app doesn't work. 
But when I change the id with the ID that shows in the Teams Admin center as APP ID(this id gets created after publishing the app by tenant admin- which developers are mostly not aware of) it starts working.

Am I missing something here or this is how it supposed to work?

Appreciate your clarification here.

**Comment by AJIXuMuK** [comment]
@SantanuPati - after additional internal conversations and investigation I can confirm that you should use the app Id from the Teams app catalog, not the id from the manifest.
To make the solution more generic, you can call [list teams apps](https://learn.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&tabs=http) endpoint first and get the app id from there.

**Comment by SantanuPati** [comment]
@AJIXuMuK - Thank you for the confirmation! The query can be closed.
