### ISSUE TITLE
ListView Command Set not available in Microsoft Teams File Tab

### ISSUE THREAD

**Issue by AmonHouston** [SharePoint/sp-dev-docs#8724]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

I have developed an SPFx ListView Command Extension that is avaliable in the edge browser via SharePoint but in the files tab of a team, it does not appear at all.

I have see previous mention on the bug reports in this github that the expected behavior is that this command is avaliable.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/34081746/214685787-14cb728e-100a-43d4-a5f5-d3245f2235ee.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/34081746/214685915-a8d8bccc-0d06-4442-a701-958d2cc7abe7.png">

### Steps to reproduce

1. Create Standard SPFx extension 
2. Update library code to 101 
3. Tenant deploy the application

### Expected behavior

The command to be available in both SharePoint Online and the Microsoft Teams File Tab.

**Comment by AJIXuMuK** [comment]
@AmonHouston - this is a known limitation.
We are tracking it in #8450
