### ISSUE TITLE
webpart/page is loaded twice in apppagehost.aspx

### ISSUE THREAD

**Issue by mdissel** [SharePoint/sp-dev-docs#8727]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.16.1

### Describe the bug / error

When the fullpage webpart is loaded via this url:
https://tenant.sharepoint.com/_layouts/15/apppagehost.aspx?componentId=[guid]

It seems that the page or webpart is loaded twice. The webpart is using async rendering, but we faced the same problem with sync rendering.

![image](https://user-images.githubusercontent.com/126084/214836191-336244ba-df05-4fe2-9b24-0533fd511cd5.png)

### Steps to reproduce

see above

### Expected behavior

Page/webpart should be loaded once, init/render on the webpart should be called once.

**Comment by AJIXuMuK** [comment]
@mdissel - are you seeing multiple requests in Network tab?

I can't repro it on my end - I see single instance in Sources and single request in Network.

**Comment by mdissel** [comment]
I've added some logging in the async onRender and async onInit.

this is in my manifest.json
    "supportsFullBleed": true,
    "supportedHosts": [
        "SharePointWebPart",
        "SharePointFullPage",
        "TeamsTab",
        "TeamsPersonalApp"
    ],
	"supportsThemeVariants": true,    


This is the console log when the fullpage webpart is added to a page:
![image](https://user-images.githubusercontent.com/126084/215056440-a7892e6e-9602-4107-b3fc-61fb8afab160.png)

This is the console log when the fullpage webpart is loaded via apppagehost.aspx
![image](https://user-images.githubusercontent.com/126084/215056790-64d9fff8-aacf-4a4b-be69-464df6f1d91e.png)

![image](https://user-images.githubusercontent.com/126084/215057061-17a4bf5b-e21a-4fd1-91f0-382dd6c1f5a9.png)

**Comment by johnguy0** [comment]
Thank you for reporting this issue. Since there is a workaround we are going to close this issue as won't fix.
