### ISSUE TITLE
Application Customizer Deployment doesn't work on First Release Tenants

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#873]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Application Customizer extension can be deployed to First Release Tenants
#### Observed Behavior
Application Customizer extension can't be deployed to First Release Tenants - it is not loading on the pages
#### Steps to Reproduce
- scaffold Application Customizer
- use steps from the [tutorial](https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint) to deploy Application Customizer
- it will work on DEV Tenant but won't work on First Release Tenant

**Comment by Brentless** [comment]
See #847

**Comment by AJIXuMuK** [comment]
@Brentless I have even commented in #847 
But thanks for pointing. I created this one to be the bug, not question.
