### ISSUE TITLE
how to hide a webpart completely when there are no items to display

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#8734]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I want to know in SPFX, how can we wide the webpart completely to remove white space when there is no content

**Comment by AJIXuMuK** [comment]
@harshdamaniahd - unfortunately, there is no way to remove the markup completely.
We have multiple wrappers around web parts in 1p markup that add paddings/margins.

But thank you for the feedback!
We will be discussing internally ability to hide a web part completely.
