### ISSUE TITLE
Missing details regarding how the dist/guid.manifest.json and temp/manifest.json are created. End goal is to use webpack 5.

### ISSUE THREAD

**Issue by magnusdanielson** [SharePoint/sp-dev-docs#8735]
The page describes that sp-build-core-tasks is used to 'packaging solutions and writing manifests', but no details regarding this is explained.

I have created a separate project that builds using webpack 5, that my project requires. It builds and bundles all files properly. If I just drop the output js files from my webpack 5 project to the dist folder in the regular spfx webpack 4 project, replacing the default files, everything works fine in the workbench.

I would like to reuse the gulp tasks that generate the dist/guid.manifest.json and temp/manifest.json files in my project. The end goal is to have only one project that builds and bundles spfx webparts with webpack 5. Is there any documentation on these gulp tasks?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 819a6029-5ccb-0a7b-8c59-a1ebeffca4cb
* Version Independent ID: 61b64d96-30a0-93d8-a0fd-6523e2dd5418
* Content: [SharePoint Framework toolchain](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/sharepoint-framework-toolchain)
* Content Source: [docs/spfx/toolchain/sharepoint-framework-toolchain.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/sharepoint-framework-toolchain.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@magnusdanielson - there is a lot of custom opinionated logic in the build pipeline.
And due to numerous reasons we're still using Webpack 4.
However, we're working on switching to Webpack 5.

But for now - you should not try to switching to Webpack 5.
