### ISSUE TITLE
Dialogs render as blank rectangle on second render after initially dismissed from a List View Command Set button (@microsoft/sp-dialog)

### ISSUE THREAD

**Issue by areestlc** [SharePoint/sp-dev-docs#8736]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.16.1
- Node.js version: 16.19.0

### Describe the bug / error

There appears to have been a SharePoint update that has broken sp-dialog functionality. The dialog box will show up OK on the first render, however after it is dismissed it will show as a blank white rectangle. There are no browser console errors to provide an explanation for what error is occuring. When the blank white rectangle is dismissed, the original dialog box is visible briefly during the fade out animation.

This does not seem to be related to an SPFx or sp-dialog version, as we are seeing this happening in multiple environments across different versions.

This is impacting the usability of our customer solutions, a prompt fix would be highly appreciated.

### Steps to reproduce

1. Use a custom Command Set button to render an extended BaseDialog class (from sp-dialog package)
2. Click the button to render the dialog initially
3. Dismiss the dialog
4. Click the button again and the dialog will render as a blank white rectangle

### Expected behavior

The dialog should be able to be rendered repeatedly after being dismissed.

**Comment by areestlc** [comment]
This was caused by attempting to use an external react & react-dom v17.0.2 package. React 17.0.2 is incompatible with SFPx v1.16.1 according to the docs.

Externalisation in gulpfiles.js:
```js
build.configureWebpack.mergeConfig({
  additionalConfiguration: (wpcfg) => {
    // remove externalization of react & react-dom
    wpcfg.externals = wpcfg.externals.filter((external) => {
      return external !== "react" && external !== "react-dom";
    });

    return wpcfg;
  },
});
```

Removing this and using react & react-dom v17.0.1 in package.json ended up being the fix.

**Comment by SumitJadon** [comment]
Works by degrading it to react & react-dom v17.0.1 in package.json ended up being the fix. Thanks Andress you are the saviour!!
