### ISSUE TITLE
PropertyPaneChoiceGroup preselection of option doesn't work!

### ISSUE THREAD

**Issue by nikdimitriadis** [SharePoint/sp-dev-docs#8741]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version = Chrome Version 109.0.5414.119
- SPFx version = 1.15.2
- Node.js version = 16.15.1
- etc

### Describe the bug / error

I try to preselect a property pane PropertyPaneChoiceGroup option. Even if i set the option to checked: true, the option isnt preselected in the webpart.
![Screenshot 2023-02-01 at 14 06 34](https://user-images.githubusercontent.com/91465889/216038235-0db8d228-dfe2-4e2e-8f61-949db56da3c4.png)

### Steps to reproduce

1. Create an spfx React webpart.
2. Define the PropertyPane like this: 
```
PropertyPaneChoiceGroup('TEST', {
	label: 'Choose tasks platform',
	options: [
		{ checked: true, key: 'planner', text: 'Microsoft Planner' },
		{ key: 'todo', text: 'Microsoft Todos' }
	]
})
```

### Expected behavior

Option is preselected in Propertypane when i insert the webpart in to the page. In my case it's not!

**Comment by heesungjang** [comment]
Hi @nikdimitriadis, did you manage to find a work around?

**Comment by nikdimitriadis** [comment]
Hi @heesungjang, no i didnt find anything.

**Comment by AJIXuMuK** [comment]
@nikdimitriadis - you should set the value of the web part's property associated with the choice group.
In that case the checked state will be correctly set based on that value.

For the default scenario you can set this value in web part's manifest.

**Comment by fatwreck** [comment]
While @AJIXuMuK is correct in pointing out you can set a default value via properties in the manifest, it still doesn't fix the _checked: boolean_ option.

options: [{
     **checked: true**, 
     key: 'planner',
}]

I got hung up on this today. 
It's still a bug and shouldn't be ignored.

**Comment by AJIXuMuK** [comment]
I meant - just use the property from web part's properties, not checked directly. 
I agree this is a bug. But most probably we will just deprecate the checked property
