### ISSUE TITLE
What is the meaning of supportedLocales in package-solution.json?

### ISSUE THREAD

**Issue by roberAlb** [SharePoint/sp-dev-docs#8745]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version : 1.15.2
- Node.js version: v14.21.1

### Issue description

We cannot find proper documentation about supportedLocales fields in the  package-solution.json file. We had it always empty and we didn't notice anything. So if we add that parameter in our product with the languages that we are supporting I'm not sure what is the impact that is going to have.

**Comment by bcameron1231** [comment]
SupportedLocales is good way to document the locales that your application supports. It shows up on the app details page. Checkout the latest blog by @hugoabernier where he briefly touches on it.

https://pnp.github.io/blog/post/spfx-21-professional-solutions-superb-solution-packages/#supportedlocales

**Comment by VesaJuvonen** [comment]
Closed as answered.
