### ISSUE TITLE
Removing existing webpart from project

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#875]
I have 2 webparts and I would like to remove a webpart from the project, how do I achieve this as deleting the reference apparently causing errors.
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by waldekmastykarz** [comment]
- `gulp clean`
- remove web part folder
- remove the bundle reference in `config.json`

That should do it

**Comment by jonathanhotono** [comment]
@waldekmastykarz thanks, that works :)

**Comment by waldekmastykarz** [comment]
@jonathanhotono Awesome! Thanks for confirming
