### ISSUE TITLE
how to get shared xls file difference between two version?

### ISSUE THREAD

**Issue by rajeev8620** [SharePoint/sp-dev-docs#8750]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

- I need to get all difference between shared xls file changes, if some one has modified the shared xls file in that case I need to list out all the changed what user has done in python. Please guide me how i can approach.

**Comment by StfBauer** [comment]
While you get the changes in the browser - https://support.microsoft.com/en-us/office/show-changes-that-were-made-in-a-workbook-978ceea7-bbf6-4337-bca7-22e7cc9892e8

There isn't a public API or documentation on how those changes were accumulated.

The browser shows you the endpoint Excel uses, but this doesn't make it an API that can be used.
