### ISSUE TITLE
Package will not load if importing from @microsoft/sp-dialog

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-docs#8752]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: latest
- SPFx version: 1.16.1
- Node.js version: 16
- typescript version: 4.5.5
- react 17.0.1
- react-dom 17
- removed @microsoft/office-ui-fabric-react-bundle package and used @fluentui/react 8.105.1

### Describe the bug / error

When you add the following code anywhere in the SPFx package:
```typescript
import { BaseDialog, IDialogConfiguration } from '@microsoft/sp-dialog';
```
and use that code in any way (so tree shaking doesn't remove it),
the SPFx package will not be loaded on the browser.
Instead you will get the following errors in the console:
- Could not load [library name] in require. Trying in system.js
- Could not load [library name] in require. Trying in system.js
- Uncaught (in promise) Error
  - Trace shows its coming from "e.buildLoadComponentError"

and the code in the SPFx package will not execute on the page.

### Steps to reproduce

for simplicity, this code doesn't do much except causes the project to blow up.

1. Create a ListViewCommandSet component
1. Add this code to the import:
> import { Dialog } from '@microsoft/sp-dialog';
1. add a new class at the end with a test dialog:
```typescript
export default class TestDialog extends BaseDialog {
    public render(): void {
        ReactDOM.render(<h1>hello world!</h1>, this.domElement);
    }

    public getConfig(): IDialogConfiguration {
        return { isBlocking: false };
    }

    protected onAfterClose(): void {
        super.onAfterClose();

        // Clean up the element for the next dialog
        ReactDOM.unmountComponentAtNode(this.domElement);
    }
}
```
4. In your command set onInit, add this code:
```typescript
console.log("my project init");
console.dir(TestDialog);
```

### Expected behavior

two messages would be written to the console.

**Comment by shaipetel** [comment]
The error message in console:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/6225881/217009680-dbebcddf-a3b2-4f8d-b389-8ff76a3b1ec4.png)

**Comment by AmonHouston** [comment]
Hi, I'm also running into this issue, but I'm not using the dialog library. 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/34081746/219202766-54220169-488d-4fa5-8abf-a315411c4afc.png">

**Comment by matteomessmer** [comment]
I'm also facing this issue

**Comment by MattDev93** [comment]
Ran into similair issue where Dialog would render once then show blank afterwards. 

Tried some different implementations and eventually updated our command set extension to use the FluentUI Dialog component:
`import { Dialog, DialogType } from 'office-ui-fabric-react/lib/Dialog';`

Based on the implementation here: 
https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-command-convert-to-pdf/src/extensions/pdfExport

**Comment by matteomessmer** [comment]
@MattDev93 it's not working for me

**Comment by matteomessmer** [comment]
Hi, could someone please verify this issue?

**Comment by matteomessmer** [comment]
@shaipetel were you able to solve this?

**Comment by AmonHouston** [comment]
I will say for me - I re-bundled and packaged my solution and then it decided to work. However I had already tried this numerous times before but it was the first time that day. So, it seems like it self-resolved or there was an issue on the MSFT server side that they fixed.

**Comment by paulcolucci** [comment]
it seems you need to explicitly install react and react-dom:

npm i react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact

**Comment by matteomessmer** [comment]
@paulcolucci I did install those versions and I think it may have worked.
Thank you

**Comment by AJIXuMuK** [comment]
We need to change the documentation for the usage of dialogs.
You need to explicitly install React as a dependency to create React components.
