### ISSUE TITLE
How to install PNP SharePoint online (office365)?

### ISSUE THREAD

**Issue by thamaraj85** [SharePoint/sp-dev-docs#8758]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

 How to install PnP on SharePoint online?
https://pnp.github.io/sp-dev-fx-webparts/gettingstarted/

### Issue description

 How to install PnP on SharePoint online?
https://pnp.github.io/sp-dev-fx-webparts/gettingstarted/

**Comment by thamaraj85** [comment]
Hi Beau,

Thanks for your reply, actually I want to know to install on the SharePoint online site?

Thanks,
Raj

________________________________

**Comment by bcameron1231** [comment]
Hi! You'll need to download the repository, and build / package the solutions. Then you can install them in SPO. 

Please check out the SPFx Documentation on Deploying Solutions.

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn
