### ISSUE TITLE
 SPHttpClientBatch missing in spfx 1.16.1 and 1.16.0-rc0?

### ISSUE THREAD

**Issue by marianmihaiu** [SharePoint/sp-dev-docs#8761]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Edge latest
- SPFx 1.16.1 with yo @microsoft/sharepoint --plusbeta
- SPFx 1.16.0-rc0 yo @microsoft/sharepoint --plusbeta
- Node.js 16.17.0
- etc

### Issue description

No matter which SPFX version I try: latest 1.16.1 or next 1.16.0-rc0 with optional --plusbeta to generate a new solution, I cannot use the SPHttpClientBatch in my code.
I get the message that it is not available in @microsoft/sp-http library when I try to import it.
Going into the node-modules to check the exported SPHttpClientBatch in sp-http module, it is also unavailable (or commented out).
Is this real? I guess we cannot use this batching option anymore in spfx?
Do you have an alternative option for making batch requests?

Thank you,

Marian

**Comment by AJIXuMuK** [comment]
@marianmihaiu - `SPHttpClientBatch` is a `beta` API. 
You should use `beta` versions of SPFx to get access to it.
`--plusbeta` flag has been deprecated a while ago.
Just use the latest available beta.

**NOTE: as this is a beta API we don't recommend using it in production**
