### ISSUE TITLE
SPFx 1.16.1 - Graph calls: Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.2. Store had [2.2.1]. Service worker version: undefined,DurableN1=true

### ISSUE THREAD

**Issue by AbhijeetT17** [SharePoint/sp-dev-docs#8765]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.16.1
- Node.js version 16.13.2
<img width="278" alt="image" src="https://user-images.githubusercontent.com/85282123/218352088-cd881d88-25c9-42a7-8e70-837b028b1267.png">

### Describe the bug / error

Recently updated the solution to SPFx 1.16.1 and all related dependencies.

Facing error when trying to call Graph api using graph client V3.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/85282123/218352175-6c7d7968-7e8f-40d9-bc09-0081c3853d31.png">

Previously, it was working with the older versions of SPFx with MSGraphClient (Not V3)

### Steps to reproduce

1. Use MS Graph client V3 to call api in spfx list view extension
2. Pass the api to make post call to update SP list using the graph client.
3. Observe error on both - workbench and list view extension.

### Expected behavior

Graph calls should go through using the graph client.

**Comment by AJIXuMuK** [comment]
There was a temporary regression that should be fixed by now.
@AbhijeetT17 - could you please check if it's still an issue for you?

thanks!
