### ISSUE TITLE
incorrect details on page

### ISSUE THREAD

**Issue by ag0059985** [SharePoint/sp-dev-docs#8766]
[Enter feedback here]
incorrect details on the page below pages
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16 
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16.1 
![image](https://user-images.githubusercontent.com/524177/218387208-553eeb93-f291-4051-8cdc-30b82f2daecf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b25cf16e-0169-4690-3143-b28fb8281f2b
* Version Independent ID: b25cf16e-0169-4690-3143-b28fb8281f2b
* Content: [SharePoint Framework v1.16 release notes](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16#install-the-latest-version)
* Content Source: [docs/spfx/release-1.16.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/release-1.16.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
thx @ag0059985 - fixed now - clearly a miss from our side.
