### ISSUE TITLE
Reusing or embedding a document library webpart in a provider hosted app

### ISSUE THREAD

**Issue by AnassKartit** [SharePoint/sp-dev-docs#877]
Hi,
Is it possible to integrate the document library webpart in a provider hosted app or using SPFX in a custom page? I need generic document library that can point to any document library in a site collection.

#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
 
Thanks

**Comment by mcmynn83** [comment]
@AnassKartit - Support for SPFX in non sharepoint hosted pages is not supported at this time.  If you would like to see a feature like this user voice is the best place to request new features.
