### ISSUE TITLE
Viva Connection within Teams hyperlinks to SharePoint double encoding space in 'Shared Documents'

### ISSUE THREAD

**Issue by swatmaps** [SharePoint/sp-dev-docs#8771]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Issue is within the Teams application using a skinned Viva Connections app (Version 1.0.13) as our intranet
- You have Microsoft Teams Version 1.6.00.1381 (64-bit). It was last updated on 2/3/2023
- Happening on all Windows 10/11 and Mac workstations
- Issue is not present in browser
- [edit] this is happening in the browser version of teams but not the browser version of sharepoint, to clarify the above point

### Describe the bug / error

- When clicking on hyperlinks within Teams (via Viva app) that are pointed at a Document Library that have a space in the name (such as 'Shared Documents') it will give the error `This item might not exist or is no longer available`
- This behavior is also present when navigating, again within Teams via Viva, to a SharePoint site homepage, and clicking to the default 'Documents' in the quick access menu
- If you click Documents again while on this error page it will render properly
- Running a Fiddler session shows that the url is double encoding the space as %2520
- This just started happening very recently

### Steps to reproduce

1. Install Viva Connections into Teams with a set homepage + global navigation enabled
2. Create a Team and create the associated SharePoint page
3. Navigate within this window to a team SharePoint page and try to click the default Documents link on the quick access menu
4. Alternatively make a web part on the Homepage Hub that has a hyperlink pointing to the default Document Library of the created SharePoint and it will give the error
5. This is also the case when linking to a folder via a share link in the same way - strangely enough linking directly to files works fine

### Expected behavior

Clicking these links will produce a request that looks like: 

`https://<company>.sharepoint.com/sites/<site>/_layouts/15/filebrowser.aspx?app=teamsfile&scenario=portals&fileBrowser={%22sdk%22:%221.0%22,%20%22entry%22:%20{%22sharePoint%22:{%22byPath%22:%20{%22folder%22:%20%22%2Fsites%2F<site>%2FShared%2520Documents%2F<folder>%2F<folder>%2F<folder>%22}}},%20%22leftNav%22:%20{%22preset%22:%22current-site%22}}`

and will not render the requested resource due to 404ing on the subsequent list calls - instead giving an error page described above

![image](https://user-images.githubusercontent.com/122498825/218930207-eff7403e-dc07-4a2e-ba8c-500c1814757c.png)

**Comment by nilang-shah** [comment]
We are also having exact same issue!

**Comment by warren-genpoint** [comment]
Same issue on our tenant and all of our client tenants.

**Comment by swatmaps** [comment]
This issue has been resolved - would it be possible to request a postmortem update or something on what the issue was so I can disclose it to shareholders @VesaJuvonen

**Comment by swatmaps** [comment]
actually this has regressed again @VesaJuvonen it was fixed but it's broken again

**Comment by VesaJuvonen** [comment]
This issue is being actively looked for and should be fixed soon. Sorry for the inconvenience.

**Comment by AJIXuMuK** [comment]
@swatmaps - I've tried to repro it but can't.
I've tested the next scenarios:
- opening Documents (Shared Documents) from global nav
- opening Documents from the top nav of the home site
- opening folder under documents from global nav and nav of the home site
- opening Documents lib of a Team site from global nav and nav of the home site
All is working correctly.

please, let me know if I missed any scenario.

**Comment by swatmaps** [comment]
it was fixed again by the time I got into the office this morning @AJIXuMuK

**Comment by AJIXuMuK** [comment]
@swatmaps - thank you for the confirmation. 
We had some roll backs and roll outs a the last two weeks. 
So this probably was a temporary regression. 
Please, feel free to reopen the issue if it appears again.
