### ISSUE TITLE
Microsoft Teams spfx webpart - error initializing application error cannot read properties of undefined (reading 'componentType') 

### ISSUE THREAD

**Issue by AstroNorman** [SharePoint/sp-dev-docs#8774]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version: 16.1
- Node.js version: 16.18.1
- etc

### Describe the bug / error

Receiving the same error as this issue reported 1 month ago:
https://github.com/SharePoint/sp-dev-docs/issues/8702#issue-1536948370

<img width="829" alt="console log" src="https://user-images.githubusercontent.com/106515086/219322940-ee64642b-8cd7-463a-a991-0dd768867f27.PNG">
<img width="399" alt="error 2" src="https://user-images.githubusercontent.com/106515086/219323392-992f9ff0-b7f3-4996-b744-828f01b1db82.PNG">

### Steps to reproduce

1. Git clone https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-fluentui-9
2. Create new 'SPFx Tab' project using Teams ToolKit
3. Copy paste all the files from _react-fluentui-9_ sample project to _SPFx_ folder generated by Teams Toolkit.
4. Change debug configuration -> Teams Workbench (Edge)
5. Click on Preview your Teams app

### Expected behavior

The app should be working on Microsoft Teams hosted workbench. 

Currently only works in Sharepoint hosted workbench

**Comment by AJIXuMuK** [comment]
thank you @AstroNorman for submitting the issue!
We will be looking into it.
Will update the issue as soon as we have any news.

**Comment by GnosisCode** [comment]
Any news on this ?

**Comment by AJIXuMuK** [comment]
@GnosisCode @AstroNorman - sorry for the delay.
We should get to it relatively soon

**Comment by ShaylinChetty** [comment]
Any updates on this issue?

**Comment by Wagnerah** [comment]
Any updates on this issue?

This issue don't let me going on in my custom solution for Microsoft Teams Multi Tab Personal App.

**Comment by AJIXuMuK** [comment]
Sorry for the delay...
A few questions.
Is it happening in any Teams client (web browser, Teams desktop, New Teams) or some specific client?
Can someone share the failing .sppkg with me? If not - could you share the correlation id from the error page and domain name?

Thanks!
