### ISSUE TITLE
Breakpoints in VSCode IDE not hit when debugging SPFx Field Customizer.

### ISSUE THREAD

**Issue by agaskelluk** [SharePoint/sp-dev-docs#8775]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome and Edge, latest versions.
- SPFx version 1.16.1
- Node.js version 14.18.0
- VSCode, latest version.

### Describe the bug / error

When debugging a SPFX **Field Customizer** Solution using VS Code, I cannot get the breakpoints to hit in the **IDE**. 

I am able to hit breakpoints using the dev tools in the browser. 

When I try to debug a SPFx **webPart** using VS Code, I **am* able to get the breakpoints to hit in the **IDE**.

### Steps to reproduce

1. vCreate Simple Hello World Field Customizer from the MS guidance [here](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer).
2. Create the test list in my tenant per the guidance.
3. Run gulp serve --nobrowser.
4. Put a breakpoint in the render method and debug from VSCode using this config in launch.json

`{ "name": "FieldCustomizer debug", "type": "chrome", "request": "launch", "url": "https://testtenant.sharepoint.com/Lists/Orders/AllItems.aspx?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&fieldCustomizers={"Percent":{"id":"myGUID","properties":{"prop1":"val1"}}}", "webRoot": "", "sourceMaps": true, "resolveSourceMapLocations": [ "${workspaceFolder}/", "!/node_modules/**" ], "sourceMapPathOverrides": { "webpack:///../../../src/": "/src/", "webpack:///../../../../src/": "/src/", "webpack:///../../../../../src/": "/src/" }, "runtimeArgs": [ "--remote-debugging-port=9222" ] }`

5. Observe the page with the field customizer is successfully rendered.

### Expected behavior

Breakpoint in the VSCode IDE should be hit. I should be able to step through the code in the VS Code IDE. The breakpoints are never hit.
If I go to the dev tools in the browser instance, locate the source code in the sources tab, I can add a breakpoint there and it is successfully hit. However my desired outcome was to be able to debug within VSCode. I have the same behaviour in both Edge and Chrome.

**Comment by AJIXuMuK** [comment]
@agaskelluk - you `launch` config differs from what we have scaffolded by default: `webRoot` is empty in your case and `sourceMapPathOverrides` has different values.

Please, use the configuration provided by the generator.
