### ISSUE TITLE
Application Customizer is sometimes not loading

### ISSUE THREAD

**Issue by diabhoil** [SharePoint/sp-dev-docs#8776]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version 110.0.1587.40
- SPFx version 1.16.1
- Node.js version 16.19.0

### Describe the bug / error

I deployed the application customizer to our tenant (deployed to all sites, skipFeatureDeployment = true) and all worked fine. But after a while we noticed that it is sometimes not loading. So I tried to find the error, but found that every now and then the scripts are not loaded at all.

There should be the script like in the screenshot under "Expceted behavior" but they are not loaded:
![image](https://user-images.githubusercontent.com/42711805/219371683-a8889ece-69a2-4bbf-8044-4dce65927c24.png)

So I dont know how to fix this and where to even start to search for the problem.

### Steps to reproduce

Dont know if it is reproducable because sometimes its working and sometimes not

### Expected behavior

The files should be loaded like this:
![image](https://user-images.githubusercontent.com/42711805/219371300-fcea6543-dd12-405d-ae05-b52b9d03f1bb.png)

**Comment by AJIXuMuK** [comment]
@diabhoil - does page refresh help?
Could you please also try to open dev tools -> Application -> Service Workers -> bypass for network?
