### ISSUE TITLE
SharePoint SPFX package's App Icon is not getting loaded during upload/deployment in app catalog.

### ISSUE THREAD

**Issue by poladiaraj** [SharePoint/sp-dev-docs#8783]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Microsoft Edge Version 110.0.1587.50
- SPFx version : 1.16.1
- Node.js version : 16.13.0

### Describe the bug / error

![image](https://user-images.githubusercontent.com/24682275/220348949-b7fff752-0ce0-4295-a8f7-2f64d990e2e3.png)

### Steps to reproduce

1. Use schema: "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json"
2. Set IconPath: <NameOfImageFile>.<ExtentionOfImageFile>
3. Build spfx package
4. Upload package to sharepoint app catalog.

### Expected behavior

Image set as App Icon in should be visible properly.

**Comment by AJIXuMuK** [comment]
@poladiaraj - are you experiencing the same issue with modern UI for app catalog?

**Comment by poladiaraj** [comment]
In modern UI behavior is slightly different. When we deploy/upload the package we see broken app icon. After deployment when we refresh the page, we are able to see app icon.

**Comment by nick-pape** [comment]
Hi @poladiaraj I tried to repro this and found something similar to the report:

On the modern page:
* Upload the SPPKG
* The app icon is broken (but the img tag is correct)
* If you choose not to enable, the icon never appears
* Once you enable the app, the icon appears

Image URL: `/sites/appcatalog/ClientSideAssets/c1b4bc9d-a5af-4cbd-b550-3671c7caaf90/ic_launcher.png`

On a legacy page:
* Upload the SPPKG
* The icon seems to sometimes appear, but sometimes not appear. (This may be from caching/my testing, as it does not appear most times)
* After deploying, the icon will start appearing on the modern page.

Image URL: `/_layouts/15/AppCatalogImage.ashx?ImageUrl=https%3A%2F%2Fa830edad9050849445i23030419%2Esharepoint%2Ecom%2Fsites%2Fappcatalog%2FClientSideAssets%2Fc1b4bc9d%2Da5af%2D4cbd%2Db550%2D3671c7caaf90%2Fic%5Flauncher%2Epng`

It seems like the App Icon image is not being uploaded until the SPPKG is actually deployed.
