### ISSUE TITLE
Viva Dashboard Web Part no longer supports section background color

### ISSUE THREAD

**Issue by Annie-Johnson** [SharePoint/sp-dev-docs#8785]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

The Viva dashboard web part is no longer supporting theme variants section background colors after a recent update.  

![image](https://user-images.githubusercontent.com/28032142/220374397-45825c1c-076c-4beb-8484-5c70845f2584.png)

### Steps to reproduce

1.  Existing deployed dashboard, worked previously, now white behind cards.

### Expected behavior

Viva Dashboard web part supports theme variants and has a transparent background when displaying on section background color.

**Comment by a1mery** [comment]
I can reproduce this issue.

**Comment by VesaJuvonen** [comment]
@Annie-Johnson  and @a1mery - We are working on getting this fixed. As this is however not a dev issue, we will close this from here. In general these kind of issues should be reported from the m365 admin UX as it's in the out of the box features. We cannot unfortunately route the input from here to the right channel, so it's better to report the issue from admin UX.
