### ISSUE TITLE
SPFX UI intermittently gets misaligned. 

### ISSUE THREAD

**Issue by poladiaraj** [SharePoint/sp-dev-docs#8787]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Microsoft Edge Version 110.0.1587.50
- SPFx version : 1.16.1
- Node.js version : 16.13.0

### Describe the bug / error

When the SharePoint App is opened in any Document Library, the UI is not rendering consistently at expected position. Intermittently the UI is rendering at Top Left corner of the site. This is happening after updating the package to SPFx version specified above.

Observed behavior (intermittent):
![SPO Misaligned](https://user-images.githubusercontent.com/24682275/220575209-5a93a1b9-a549-4ba7-8da5-7298efc2adc4.png)

Expected behavior:
![SPO Expected](https://user-images.githubusercontent.com/24682275/220575286-d8928b6e-0b8f-4f25-82d3-492235202182.png)

**NOTE**: Prior to updating the version to the aforementioned version, we never observed any misalignment.

### Steps to reproduce

1. Upload/Deploy SPFx app to catalog.
2. Add the application to site.
3. Owner of the Document Library can click on the "..." ellipsis button and invoke SPFx app.
4. Doing so intermittently results in misalignment.

### Expected behavior

![SPO Expected](https://user-images.githubusercontent.com/24682275/220576202-5e015219-f995-4c48-ba1f-87db1512fe98.png)

App UI should always render as displayed in attached screenshot.

**Comment by AJIXuMuK** [comment]
@poladiaraj - could you provide some details on the implementation of your app?
It seems you have some custom dialog/modal.
How's the target for this modal is specified?
