### ISSUE TITLE
SharePoint Graph Pages API: Internal Server error on PATCH canvaslayout

### ISSUE THREAD

**Issue by redlab-chris** [SharePoint/sp-dev-docs#8793]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Graph API responds with "Internal server error 500" on

https://graph.microsoft.com/beta/sites/365redlab.sharepoint.com,c006d14d-1e79-4dc1-9048-9ec48991f220,46067dc3-f26c-414e-a048-994708d6bfd1/pages/31d76036-bc22-41c5-afe3-e62ea9ecd479

with payload:

{
    "canvasLayout": {
        "horizontalSections": [
            {
                "id": "1",
                "layout": "oneColumn",
                "columns": [
                    {
                        "id": "1",
                        "webparts": [
                            {
                                "@odata.type": "#microsoft.graph.textWebPart",
                                "id": "de53338c-f4a3-4a5a-8314-111ac94717e3",
                                "innerHtml": "<p>some text</p>"
                            }
                        ]
                    }
                ]
            }
        ]
    }
}

### Steps to reproduce

1. open graph explorer
2. run the query 
3. with the payload

This does reproduce on this exact page

sites/365redlab.sharepoint.com,c006d14d-1e79-4dc1-9048-9ec48991f220,46067dc3-f26c-414e-a048-994708d6bfd1/pages/31d76036-bc22-41c5-afe3-e62ea9ecd479

and not for other pages in our tenant

![image](https://user-images.githubusercontent.com/73823734/221364403-c3ca1242-6e17-4c5c-8458-95e02fc73508.png)

### Expected behavior

The canvas layout of the page is updated

**Comment by kkgthb** [comment]
I, too, get 500 errors every time I try to submit a `PATCH` request whose only job is to update `canvasLayout`.

Here's the request body from an example of me trying to blow the content out of the water on a page that currently has 3 full-width horizontal sections _(#1, #2, & #3)_ and replace it with a page that just has 1 vertical section in it _(I am using the Graph Explorer to push through the request)_:

```json
{
  "@odata.type": "#microsoft.graph.sitePage",
  "canvasLayout": {
    "@odata.type": "#microsoft.graph.canvasLayout",
    "verticalSection": {
      "@odata.type": "#microsoft.graph.verticalSection",
      "emphasis": "none"
    }
  }
}
```

**Comment by divyachapan** [comment]
Issue resolved.
