### ISSUE TITLE
Declarative json call to svg files are supported?

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#8796]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

This is a direct question to @shagra-ms, 

There was situation that a provide elmType was not used as expected  and was blocked by MSFT because of security risk what is understandable. 
#8004 

I would like to validate with your team action using  "elmType" > "img"  that call "svg" files are valid from MSFT side.
Architecture process:
- SharePoint Library where the svg is stored.
- Create declarative json that call with following sample:
```
 {
        "elmType": "img",
        "style": {
          
        },
        "attributes": {
          "src": "[SharePoint Online url]/Folder/sample.svg"
        }
      }
```
- After this the content of the svg appear in the list. This option allow to use some of the svg properties "animateTransform" and off course not all properties for security reasons.

This process is ok from MSFT or will be internally validated and remove/pause in the future?

**Comment by aaclage** [comment]
Dear @shagra-ms, 

Any update on this question or I'm overthinking to much?

**Comment by StfBauer** [comment]
Have you tried a base64 encoded SVG as the source?
i guess the general concern on SVG in this regard is that it might contain a [script tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script), which could indeed be a security risk.

**Comment by aaclage** [comment]
@StfBauer I saw that SharePoint Online security policies is blocking script tag from svg and other properties. didn't try the encode64 but could give a try.

**Comment by aaclage** [comment]
@StfBauer My question is the fact when you upload a svg to SharePoint library and click on the svg, than you have the preview working "off course with some limitations". Base on this i assume you can call the svg from the sharepoint library just don't want to have any surprises and removal of options...
