### ISSUE TITLE
Error MSB4019 with node-gyp rebuild

### ISSUE THREAD

**Issue by ronaldborman** [SharePoint/sp-dev-docs#88]
After setting up my Windows 10 machine successfully according to the instructions in 'Setup your machine' I followed tutorial 1 but got the following error with node-gyp rebuild for the buffer-util and utf-validate modules:
error MSB4019: the imported project C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props was not found

According to https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md this occurs when older versions of Visual Studio or C++ Build tools were already installed (which was the case on my machine). The solution was to set the environment variable VCTargetsPath to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140 (or a similar path).

Perhaps this could be added to the 'Known Issues' Wiki page.

**Comment by nickpape-msft** [comment]
Known issue page updated. Thanks!
