### ISSUE TITLE
spfx extensions - ListView CommandSet not working on Modern Communication sites

### ISSUE THREAD

**Issue by luismanez** [SharePoint/sp-dev-docs#880]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
You can run a List Command Set extension on a Modern Communication site

#### Observed Behavior
The custom command set is not rendered anywhere.

Using Dev tools in Chrome, I can see the custom extension script is loaded fine, but is never executed. 

I´ve also tried to Disable the "DenyAddAndCustomizePages"

```PowerShell
Set-SPOSite [SITE_URL] -DenyAddAndCustomizePages 0
```
but didn´t work.

#### Steps to Reproduce
Create a Modern Communication site from the "SharePoint" page in Office 365
Create a new spfx extension project with the Yeoman template
Gulp serve --nobrowser
Navigate to any List/Document library and add the extension query string to load the custom script. The custom commands are not rendered anywhere.
Same steps in a Modern Team site work as expected...

Thanks.

**Comment by mpasarin** [comment]
Thank you @luismanez for your feedback. We have added support for Command Sets on Communication sites, and this will be rolled out within the week.
I'm going to close this issue, feel free to re-open if it's not working next week.

**Comment by luismanez** [comment]
Great news! Thanks a lot.
