### ISSUE TITLE
Is there any way to integrate with document library view of a Sharepoint website?

### ISSUE THREAD

**Issue by catmanjan** [SharePoint/sp-dev-docs#8801]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have been investigating what is actually possible as far as integrating with document libraries (the website you see when you go to the Documents tab of a site)

So far it seems like there is no way to do anything here, no way to integrate with our app to provide features to users

Is this correct?

**Comment by AJIXuMuK** [comment]
@catmanjan - you can use [SPFx Extensions](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions) to add custom header/footer to the page, add custom buttons to the command bar and context menu, override rendering of a column or edit/view/new form for the list item/document.
