### ISSUE TITLE
Issue with publishing SharePoint page

### ISSUE THREAD

**Issue by divyachapan** [SharePoint/sp-dev-docs#8806]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

In December when the SharePoint page creation endpoint became available I was able to create a page using [Create a new page in a SharePoint site - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta), and then immediately publish it using [sitePage: publish - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta).
This now seems to fail, with the error: "The resource has changed since the caller last read it; usually an eTag mismatch". I have tried adding delays, adding the eTag in the header, but nothing changes.
What's odd, is that if I copy the failed request (eg. https://graph.microsoft.com/beta/sites/m365x77791025.sharepoint.com,04283101-da0a-4091-93f6-2bffdd618aa4,bedf6ea7-4856-4654-ba8b-c4b9648783d9/pages/323f4cfc-c19d-4e81-ada8-c451b41b08af/publish) and run it using Graph Explorer - it works without issue.
 
I can see others are also experiencing this: [Follow-Up: Publish API fails after Site Created - Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/1165608/follow-up-publish-api-fails-after-site-created), however in this thread they are saying the publishing works despite the error - whereas I'm not seeing it publish successfully.

### Steps to reproduce

1. Create page via Graph API
2. Publish the page via graph API
3.

### Expected behavior

Page should be published or proper error should be thrown

**Comment by loryanstrant** [comment]
Very much keen to see this being resolved, as I was about to implement an automated multi-tenant SharePoint page publishing system to replace an existing system that uses Power Automate connectors for each tenant. :-)

**Comment by loryanstrant** [comment]
For more context, here's the workflow (the two steps I've marked out were only introduced yesterday while I was trying to work with the publish issue, and are not required normally):
![image](https://user-images.githubusercontent.com/51473494/222329013-a2603c87-2018-4836-828d-9dfbb7f0f4ac.png)

### The breakout of each step ###
**1. Create page** 
![image](https://user-images.githubusercontent.com/51473494/222329070-019e4a57-fa76-4839-824d-04c9f3b8a936.png)
![image](https://user-images.githubusercontent.com/51473494/222329117-3dc2a4ef-2a6d-4637-b022-c584a608db70.png)
![image](https://user-images.githubusercontent.com/51473494/222329139-72d7d0dc-2262-4143-99c9-780d25b0813c.png)

**2. Parse JSON**
![image](https://user-images.githubusercontent.com/51473494/222329181-c6a80996-1310-4af4-900f-5171df1804ba.png)
_Full breakout:_
`{
    "type": "object",
    "properties": {
        "@@odata.context": {
            "type": "string"
        },
        "@@odata.etag": {
            "type": "string"
        },
        "eTag": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "lastModifiedDateTime": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "webUrl": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "pageLayout": {
            "type": "string"
        },
        "thumbnailWebUrl": {
            "type": "string"
        },
        "promotionKind": {
            "type": "string"
        },
        "showComments": {
            "type": "boolean"
        },
        "showRecommendedPages": {
            "type": "boolean"
        },
        "createdBy": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "displayName": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "lastModifiedBy": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "displayName": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "parentReference": {
            "type": "object",
            "properties": {
                "siteId": {
                    "type": "string"
                }
            }
        },
        "contentType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "publishingState": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "reactions": {
            "type": "object",
            "properties": {}
        },
        "titleArea": {
            "type": "object",
            "properties": {
                "enableGradientEffect": {
                    "type": "boolean"
                },
                "imageWebUrl": {
                    "type": "string"
                },
                "layout": {
                    "type": "string"
                },
                "showAuthor": {
                    "type": "boolean"
                },
                "showPublishedDate": {
                    "type": "boolean"
                },
                "showTextBlockAboveTitle": {
                    "type": "boolean"
                },
                "textAboveTitle": {
                    "type": "string"
                },
                "textAlignment": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "authors@odata.type": {
                    "type": "string"
                },
                "authors": {
                    "type": "array"
                },
                "authorByline@odata.type": {
                    "type": "string"
                },
                "authorByline": {
                    "type": "array"
                },
                "imageSourceType": {
                    "type": "integer"
                },
                "serverProcessedContent": {
                    "type": "object",
                    "properties": {
                        "imageSources": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "key",
                                    "value"
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
}`

**3. Publish page**
(the eTag header was added yesterday while troubleshooting, but didn't make any difference)
![image](https://user-images.githubusercontent.com/51473494/222329422-ba545ef2-8c5a-4ac9-a99a-44bbe631994f.png)

**Comment by loryanstrant** [comment]
And the failure:
![image](https://user-images.githubusercontent.com/51473494/222329649-2abfb052-7bc1-44b9-b80a-171aff30c7d4.png)

**Comment by sangle7** [comment]
Hi @loryanstrant,could you please attach the failture body so I can take a look on it?(especially the request time, request-id). Many thanks!

**Comment by loryanstrant** [comment]
Here you are:
{
  "error": {
    "code": "resourceModified",
    "message": "The resource has changed since the caller last read it; usually an eTag mismatch",
    "innerError": {
      "date": "2023-02-28T23:58:21",
      "request-id": "43298b58-989d-498e-bb23-6600773b3a5d",
      "client-request-id": "43298b58-989d-498e-bb23-6600773b3a5d"
    }
  }
}

**Comment by sangle7** [comment]
several approach that might help:
1. could you please create an automation flow that only have one step to call the 'publish' API and see if it can work? (you can also create a workflow to 'create a page' seperately). If it works then you might want to increase your delays time. It might take several seconds to fully create a page.
2. can you help to take a look into the pages' history to confirm there's no one edit/update the page besides the automation flow?

**Comment by loryanstrant** [comment]
Thanks for the suggestions, but I've already done both of those.
I even had the delay up to 5 minutes with no effect.

I've also tried adding a get page action in there (after the 5 minute delay) to see if the eTag or any other data was different - it definitely isn't.

Have you been able to reproduce what I am attempting, but successfully?

**Comment by sangle7** [comment]
I did a few investigation and reproduced in power automate. 

I found this workflow works for me. Simply add a 'do until' block and retry once twice. Could you please try it out?

<img width="758" alt="image" src="https://user-images.githubusercontent.com/21354661/222470655-4dbc7cbd-5174-443c-a6ee-abcbdc3af719.png">

**Comment by loryanstrant** [comment]
OK, will do, thanks!
What did you put as the delay, and I'm curious - how many times did it attempt to publish until it worked?

**Comment by loryanstrant** [comment]
Confirmed that I have this working now, thank you!
Interestingly I only put a 1min delay into the "Do until", and on the second loop it worked.
Previous attempts I'd had (before the "Do until") had a 5min delay in there with no difference.

**Comment by divyachapan** [comment]
@loryanstrant : Can I close this issue?

**Comment by divyachapan** [comment]
Issue resolved
