### ISSUE TITLE
Suggestion - @microsoft/sharepoint - files being overwritten

### ISSUE THREAD

**Issue by NoralK** [SharePoint/sp-dev-docs#8821]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

npm package - @microsoft/sharepoint

### Issue description

when running yo @microsoft/sharepoint it is overwriting these file in the ```.vscode``` directory:

1. launch.json
2. settings.json

If files are being overwritten please either prompt if that is okay or make a backup of the file before overwriting.

Cheers

**Comment by AJIXuMuK** [comment]
Thank you @NoralK for submitting the issue.
We will be triaging it internally.

**Comment by AJIXuMuK** [comment]
@NoralK - could you please check the latest version of the generator?
The files in `.vscode` dir are not overwritten anymore.

**Comment by NoralK** [comment]
@AJIXuMuK Just tried a new to create a new react webpart.  The launch.json and settings.json were overwritten, as well as package.json which was not part of the OP.  The package.json was not merged either.

original package.json (complete):

```
{
  "dependencies": {
    "@microsoft/generator-sharepoint": "^1.17.2",
    "gulp-cli": "^2.3.0",
    "yo": "^4.3.1"
  }
}
```
I do not think the node version would matter but I am running v16.19.1-x64.

**Comment by AJIXuMuK** [comment]
@NoralK - you should not have these modules in the `package.json`. They should be installed globally.
Please, refer [these docs](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-development-toolchain-prerequisites)

Now, using 1.17.2 here is what I'm getting.
1. I'm creating a "Minimal" web part
2. Update `launch.json": change `type` from `msedge` to `chrome`
![image](https://github.com/SharePoint/sp-dev-docs/assets/17036219/8c269161-85f9-4730-9d57-616528a44a71)
3. Update package.json by installing any package. Let's say, `@pnp/sp`: `npm i --save @pnp/sp`
![image](https://github.com/SharePoint/sp-dev-docs/assets/17036219/9ffa9708-794b-4acd-9b0a-5c662a00efa2)
4. Now, I'm adding a "React" web part
5. `launch.json` didn't change
6. `package.json` has been updated but my changes are still there.

Please, verify your dev environment and version of SPFx you're actually using to scaffold the solution.

**Comment by NoralK** [comment]
Thank you  @AJIXuMuK - I put the yo, the generator and cli in an isolated area, I did not want to install globally or create a container - I know there are other ways to achieve this.

Yes, these original files, which has custom information, which are present before I run the generator, get overwritten - I tested this originally before the OP and again last night.

FYI - I am targeting SPFx v1.17.2, that is what the generator defaults to :)

Here is how to correctly reproduce this issue:

1. Create directory and change to it
2. Put existing custom launch.json and settings.json  in the .vscode directory
3. Open code
4. **Just for testing** - I installed  yo, the cli and the generator, which gave me that package.json above.  No - I do not have other versions installed globally
5. Run `yo @microsoft/sharepoint` in terminal - I selected a webpart and react, the other prompts I accepted the defaults
6. Open files in .vscode - they have been overwritten, same can be said about package.json file exists before running yo

Cheers

**Comment by AJIXuMuK** [comment]
@NoralK So, you're saying that you have existing non-spfx solution and try to scaffold spfx component into it, correct?

**Comment by NoralK** [comment]
No, I never said that.

**Comment by AJIXuMuK** [comment]
@NoralK 

> Create directory and change to it
Put existing custom launch.json and settings.json in the .vscode directory

Isn't that meaning that you have some pre-exisitng solution with `package.json` and `.vscode` dir before scaffolding the first SPFx solution in the folder?

I'm just trying to understand your use-case.
