### ISSUE TITLE
SharePoint Graph new Pages API -> invalidRequest: One of the provided arguments is not acceptable.

### ISSUE THREAD

**Issue by redlab-chris** [SharePoint/sp-dev-docs#8822]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

When getting some site pages using Graph API for example:

https://graph.microsoft.com/beta/sites/redlabapp.sharepoint.com,b2c6a78f-771a-4c4d-b681-47171dbc90e8,2a2f8caa-8baa-4c99-8133-feda60e2426c/pages/87aed7b2-87c8-4abb-bb4d-686985358e66?expand=webParts

An error occurs.

{
    "error": {
        "code": "invalidRequest",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "code": "badArgument",
            "date": "2023-03-14T15:34:47",
            "request-id": "09f17541-3530-4366-bcca-ef6244c2e959",
            "client-request-id": "e849d700-103d-dfff-04fa-a33837459ad6"
        }
    }
}

When I remove the query parameter "?expand=webParts", the returned result is correct.
I have no clue why this is happening on this specific page.

### Steps to reproduce

It is unclear how to create a page that produces this error. We get this error on 2 of 35 pages in our site.
Both pages only contain webparts of type Text. (Link webparts are known to produce this error, see https://github.com/SharePoint/sp-dev-docs/issues/8657)

This is the view of one of these pages.
![image](https://user-images.githubusercontent.com/73823734/225068534-3afd4af4-62fd-4d54-b2df-681f00997d63.png)
 
We are open to be contacted to further investigate in our tenant.

### Expected behavior

The web parts are expanded correctly.

**Comment by andrewconnell** [comment]
FWIW, this look like the wrong place for this question... this repo is for SharePoint development issues, but your question is about the Microsoft Graph. Suggest you post this question to the Microsoft Graph forums.

**Comment by sangle7** [comment]
Hi @redlab-chris , the request id expired. would you mind repro it and paste the new request id here? Thanks

**Comment by redlab-chris** [comment]
Hi I can reproduce the error:
https://graph.microsoft.com/beta/sites/redlabapp.sharepoint.com,b2c6a78f-771a-4c4d-b681-47171dbc90e8,2a2f8caa-8baa-4c99-8133-feda60e2426c/pages/87aed7b2-87c8-4abb-bb4d-686985358e66?expand=webParts

results in:

{
    "error": {
        "code": "invalidRequest",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "code": "badArgument",
            "date": "2023-05-16T21:10:37",
            "request-id": "49f333b3-9589-486a-86a6-32f9a7e60429",
            "client-request-id": "2673697f-eb19-a55d-01ba-e224097663d8"
        }
    }
}

**Comment by sangle7** [comment]
@redlab-chris thanks for the input. It appears that there are two web parts on your page with the same ID, which should not occur. Can you confirm if this is a recently created page or an existing one? Additionally, do you have any insights into how this page was created, such as through the user interface, API, or another framework?

Here are my suggestions:
1. You can attempt to edit the page and save it, as this may resolve the ID conflict.
2. If the issue persists, we can arrange a brief call to investigate the problem collaboratively.

**Comment by divyachapan** [comment]
@redlab-chris : Are you open to having a Teams meeting conversation about this?

**Comment by eric-millin** [comment]
@sangle7 @divyachapan I'm experiencing the same bug using the `Give @ Contoso` demo site.

```json
    "error": {
      "code": "invalidRequest",
      "message": "One of the provided arguments is not acceptable.",
      "innerError": {
        "code": "badArgument",
        "date": "2023-11-13T20:14:38",
        "request-id": "10060cf6-37b7-48fc-92df-376a7168d849",
        "client-request-id": "43640981-760a-43b8-b9e3-fb1df4e2ae2b"
      }
    }
```

**Comment by divyachapan** [comment]
Thanks for reporting this. We are looking into it.

**Comment by sangle7** [comment]
@eric-millin thanks for reporting this. It seems something is missing on your page. Could you check if you have write access to the page? If so, could you kindly try republishing the page through UX and give the request another shot? Thanks a bunch! 😊

**Comment by heinrich-ulbricht** [comment]
@sangle7 I experience the same issue when updating a text web part on a modern page.

To diagnose this further I cleared the page except for a text web part with the text "Test":
![image](https://github.com/SharePoint/sp-dev-docs/assets/3469970/6fedc2d3-58f6-4ad4-9c97-de871b242e39)

This is GET request for this page, showing the web part ID:

`GET /beta/sites/d212d10f-084f-47ea-9a71-a4ae6e6de98d/pages/f4ee3518-131d-4a54-ab01-5e1c3b3a0e0e/microsoft.graph.sitePage?$expand=canvasLayout`
![image](https://github.com/SharePoint/sp-dev-docs/assets/3469970/3d7e4003-f9c9-4edc-9355-4ff9395ab2fa)

And here is the [PATCH to modify](https://learn.microsoft.com/en-us/graph/api/webpart-update?view=graph-rest-beta) this text web part:

`PATCH /beta/sites/d212d10f-084f-47ea-9a71-a4ae6e6de98d/pages/f4ee3518-131d-4a54-ab01-5e1c3b3a0e0e/microsoft.graph.sitePage/webPart/9635dcb6-52d4-4ce3-aa5f-d93341c247ca`

(client-request-id: bae79a0a-4e47-47f5-9d49-f303d5ecbd9d)

The result is a `400 Bad Request`:
```
{
    "error": {
        "code": "invalidRequest",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "code": "badArgument",
            "date": "2024-01-02T21:14:46",
            "request-id": "fd35fee6-826f-432a-a4eb-310bf7f3018d",
            "client-request-id": "bae79a0a-4e47-47f5-9d49-f303d5ecbd9d"
        }
    }
}
```

Some context for the page in case it is relevant:
* it was created programmatically with CKEditor v4 version ("old" page)
* the content type was an extended standard content type
* the page has been edited manually in the browser to switch the content type back to standard,
* saving the page should've upgraded it to CKEditor v5 version
* the page _used_ to contain inline images and corresponding hidden web parts; all has been deleted manually

This is a blocker.
