### ISSUE TITLE
Hardware and Software requirements for SPFx development

### ISSUE THREAD

**Issue by pmeripe** [SharePoint/sp-dev-docs#8825]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Dear Support,

I would like to know the hardware (CPU, RAM size, etc..) and software requirements for SPFx framework development.

Thanks
Praveen Meripe

**Comment by bcameron1231** [comment]
There are no specific hardware requirements for SPFx development. Unlike previous SharePoint development, the needs of your machine are far less. SPFx Development is all client-side, meaning the code runs in your browser, which requires a much less powerful machine to actually do the development. You do have to run nodejs to support the development, but it's not too intensive on your machine in regard to CPU or Memory usage.

However, you should be able to make do with a 4GB RAM and any modern day CPU will suffice. I would say the greater emphasis is on the Hard Drive, and you will want plenty of space for developing your solutions.

**Comment by pmeripe** [comment]
@bcameron1231,  Thanks for your reply. 
How can we maintain the same SPFx configuration while changing the laptops? Because I am getting the new laptop and doubted my existing code would work or not in my new laptop.
Do you have any recommendations?

Thanks!

**Comment by bcameron1231** [comment]
You're existing code would work fine, so as long as you install the proper versions of node and such, as outlined by the SPFx Documentation.

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

**Comment by pmeripe** [comment]
Thanks @bcameron1231 . Is there any examples for latest pnpjs version. I am looking for List and Library add/read operations.

I am using below packages.

![image](https://user-images.githubusercontent.com/38794321/227651739-d142144e-8142-4ab5-8b75-75c738a2fe15.png)


Thanks

**Comment by bcameron1231** [comment]
I'd start with the samples in our getting started. 

https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework

We have documentation for PnPjs v3 with working with lists and items.

https://pnp.github.io/pnpjs/sp/lists/
https://pnp.github.io/pnpjs/sp/items/

Subsequently you could search the PnP Samples Repo and see if there are any samples using V3 (there should be)

https://pnp.github.io/sp-dev-fx-webparts/

**Comment by AJIXuMuK** [comment]
I believe @bcameron1231 has covered all the needed resources.
Thanks!
