### ISSUE TITLE
Text Input Column Formatting

### ISSUE THREAD

**Issue by cannibalflea** [SharePoint/sp-dev-docs#8826]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

I am wondering if there is a possibility to use json column formatting to add a text box to get user input for a particular column. I tried to use the following approach but it didn't work:

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "style": {
    "flex-directon": "row",
    "justify-content": "left",
    "align-items": "center",
    "flex-wrap": "nowrap"
  },
  "children": [
    {
      "elmType": "input",
      "type": "text"
    }
  ]
}
```

I am trying to build an approval workflow, but required a text input into one column before the approver can choose a button to approve the item. I am looking for "Edit in grid view" option but just for one of columns. Are there any work arounds to make this possible?

**Comment by aaclage** [comment]
Dear @cannibalflea 

Can recommend the following approach, 
List formatting already have some style that similar the text box. If you combine the style and the `inlineEditField` -> allow edit of field to replicate the text box. Sample below:

```
{
      "elmType": "div",
      "style": {
        "min-height": "30px",
        "min-width": "100px",
        "border": "1px solid black",
        "margin": "5px",
        "padding-left": "5px",
        "cursor": "pointer"
      },
      "attributes": {
        "class": "sp-css-backgroundColor-neutralLighterAlt"
      },
      "inlineEditField": "@currentField",
      "children": [
        {
          "elmType": "div",
          "style": {
            "padding": "5px"
          },
          "attributes": {
            "class": ""
          },
          "txtContent": "@currentField"
        }
      ]
    }
```

This type of question (designs and usage of List formatting functions ) can also be made in the [https://github.com/pnp/List-Formatting/](https://github.com/pnp/List-Formatting/) . This forum is used to described issues/bugs that need to be fixed.

**Comment by cannibalflea** [comment]
That is exactly what I was looking for. Appreciate the quick response and the note about posting to the PNP repo.
