### ISSUE TITLE
Graph API permissions for SPFx solution haven't been appeared in pending permissions in the Admin Center?

### ISSUE THREAD

**Issue by mohammadamer** [SharePoint/sp-dev-docs#8827]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.14.0
- Node.js version  v14.17.0

### Describe the bug / error

Graph API permissions for SPFx solution haven't been appeared in pending permissions in the Admin Center however it has been appeared in the development tenant.

### Steps to reproduce

1. Developed an SPFx extension then deployed it to (DEV tenant, QA, Prod)
2. After that added graph API permissions then deployed it again.
3. Graph Permissions have been appeared as pending in Dev tenant but haven't appeared in QA or Prod.

### Some Details
QA and Prod is the same tenant, but we use two different packages, One as a QA Package and another one as a Prod package.
But unfortunately, neither first nor second package Graph API permissions appeared in the central admin.

### Expected behavior

Excepted behavior is to see the Graph API permissions to appear as pending permissions, but it didn't appear.

**Comment by AJIXuMuK** [comment]
@mohammadamer - could you please check if the new permissions are listed in approved section?
The hypothesis here is the same permission scope has been requested and approved for some other SPFx solution that is installed on QA and PROD.
In that case there is no need for approval request.

**Comment by mohammadamer** [comment]
@AJIXuMuK 
It's not in the approved section.

Hmmm! I thought that it should be requested separately for each solution. Well, right now there are Graph API permissions that in the pending section some of them are the same onnes that I need in my package but with another package which was added by someone else.

Is that means because the same Graph API that I need are in pending for another solution my Graph API permissions didn't appear.

**Comment by AJIXuMuK** [comment]
@mohammadamer - yes. Permissions are shared across all spfx solutions installed.
