### ISSUE TITLE
SPFX SharePoint 2016 on-premise

### ISSUE THREAD

**Issue by RJSP** [SharePoint/sp-dev-docs#883]
I've installed Feature Pack 2 and developed simple SPFx webpart as per below..
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support

After installed SPFx package and received the following errors

**There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsClientSideSolution' attribute is not declared.' on line '1', position '243'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'StartPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '326'., Xml Validation Exception: 'The element 'App' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'AppPrincipal' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '339'.**

**Comment by nickpape-msft** [comment]
@mcmynn83

**Comment by mcmynn83** [comment]
@RJSP  - Could you send your package to my Microsoft alias grahamc so we can look into this problem?

**Comment by RJSP** [comment]
you can provide the email , will send

**Comment by mcmynn83** [comment]
grahamc at Microsoft.com.

**Comment by RJSP** [comment]
I Only sent .sppkg file, please let me know if you need any other files.

**Comment by mcmynn83** [comment]
I have tried this on the latest version of FP2 and the package you have sent does not repro the issue.  Please ensure you have the last bits where we have actually turned on the SPFX framework.

**Comment by RJSP** [comment]
Yes, Configuration database version:16.0.4588.1000

**Comment by mcmynn83** [comment]
When patching it was possible to miss updating a file.  We have fixed this in our March CU which shoudl mitigate this issue.

**Comment by KoenZomers** [comment]
As I'm getting questions on how to deal with this before the March 2018 CU, you have two options:

1. If building a new SharePoint 2016 farm:

Install the SharePoint 2016 RTM bits, do not apply any CU or apply a CU before Feature Pack 2 was introduced (August 2017 or earlier) and create the App Catalog site collection. Now install whatever CU you want, i.e. the January 2018 CU and you should be fine.

2. If having an existing SharePoint 2016 farm on a CU lower than September 2017:

If your SharePoint 2016 is not on any of these listed CUs yet, you can create the App Catalog site collection and then safely patch with one of the CU containing Feature Pack 2 (September 2017 or later). It should work fine then, although I haven't tested this scenario myself yet.

3. If having an existing SharePoint 2016 farm on a CU between September 2017 and February 2018:

If you have installed the September 2017, October 2017, November 2017, December 2017, January 2018 or February 2018 CU without having an App Catalog yet, you will have to wait for the March 2018 CU to come out to fix this issue. There's no supported way to get SPFx to work. Regular Add-In packages will work fine however.

**Comment by KoenZomers** [comment]
Just to add in case you would find this topic and are facing the same issue even after installing the March 2018 CU or later, ensure that after installing SharePoint 2016 RTM, you MUST do a psconfig before installing any SharePoint CU. After running psconfig, update your farm with the latest CU, run psconfig again and you should be good to go.
