### ISSUE TITLE
Not able to get migrate-from-jslink-to-spfx-extensions to load

### ISSUE THREAD

**Issue by mickeybnet** [SharePoint/sp-dev-docs#8833]
I followed the steps to setup my dev environment on [https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

Everything compiles fine. When I run `gulp serve --nobrowser` and open a browser and try to run the extension the `OnRenderCell` does not seem to be called. I cannot tell if the extension is being loaded or not. 

I saw comments from a few years ago that was saying this only worked on classic sites in a dev tenant. Is that still true? If so, how do I create a classic site vs. clicking the classic experience link?

node: 16.13.2
yo: 4.3.1
@microsoft/generator-sharepoint: 1.16.1

**Comment by mickeybnet** [comment]
It looks like the OnInit() is firing, but the OnRenderCell will not fire when the column type is "Choice". If I create a text field it will fire. Change the column type from a Choice to Text will also not work.

**Comment by AJIXuMuK** [comment]
@mickeybnet - that is a "by-design" behavior.  Custom formatting has a priority over SPFx Field Customizers
