### ISSUE TITLE
ES2020 & ES2022 Support Timeline?

### ISSUE THREAD

**Issue by RobertWoehr** [SharePoint/sp-dev-docs#8837]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Edge Version 108.0.1462.76 (Official build) (64-bit), Chrome Version 111.0.5563.110 (Official Build) (64-bit)
- SPFx version - 1.16.1
- Node.js version - 16.19.1
- Angular 15.2.4

### Issue description

The organization I work for is an Angular shop & we have several custom SPFx web parts w/ Angular Elements in SPO that work great up to Angular 13+, but not for later versions of Angular.  

import '../../../../TestAngular15/dist/test-angular15/main';

For example, attempting to import the "main.js" file from an Angular 15 project generates the following error:

[11:12:42] Starting subtask 'webpack'...
[11:12:43] Error - [webpack] 'dist':
../TestAngular15/dist/test-angular15/main.js 3370:29
Module parse failed: Unexpected token (3370:29)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|       this._platformLocation = _platformLocation;
|       this._removeListenerFns = [];
>       this._baseHref = href ?? this._platformLocation.getBaseHrefFromDOM() ?? (0,_angular_core__WEBPACK_IMPORTED_MODULE_0__.inject)(DOCUMENT).location?.origin ?? '';
|     }
|     /** @nodoc */
 @ ./lib/webparts/testSpFx16/TestSpFx16WebPart.js 22:0-60

**Angular 13+ Elements have the following tsconfig:**

"compilerOptions": {
  ...
  "target": "es2017",
  "module": "es2020",
  "lib": [
    "es2020",
    "dom"
  ]
}

**Angular 14+ Elements have the following tsconfig:**

"compilerOptions": {
  ...
  "target": "es2020",
  "module": "es2020",
  "lib": [
    "es2020",
    "dom"
  ]
}

**Angular 15+ Elements have the following tsconfig:**

"compilerOptions": {
  ...
  "target": "ES2022",
  "module": "ES2022",
  "useDefineForClassFields": false,
  "lib": [
    "ES2022",
    "dom"
  ]
}

**SPFx 1.16.1 web parts have the following tsconfig:**

"compilerOptions": {
  "target": "es5",
  "module": "esnext",
  ...
  "lib": [
    "es5",
    "dom",
    "es2015.collection",
    "es2015.promise"
  ]
}

I want to point out that is NOT an Angular or 3rd party issue as my question is related to:

[Cannot import ES2020 module #8638](https://github.com/SharePoint/sp-dev-docs/issues/8638)
&
[OOB Spfx version 1.13.1 break while using react-router-dom #7656](https://github.com/SharePoint/sp-dev-docs/issues/7656)

My question is, when will custom SPFx web parts support importing ES2020 & ES2022 compiled modules?

I would like to be able to keep our custom SPFx web parts as up-to-date as possible in order to take advantage of enhanced security, performance, & features as well as keep up with the pace of the organization as far as the latest internally used version of Angular, but the SPFx version is the driving force that dictates which versions of Angular can be imported for this case.

A delivery date on this functionality would be appreciated so that upgrade planning can be done on my side.

Temporary workarounds or pertinent info would also be appreciated.

Thanks,
Rob

**Comment by AJIXuMuK** [comment]
@RobertWoehr - unfortunately there is no dates for that.
It is in our backlog but not yet in active development.
