### ISSUE TITLE
WebPart loading old js-version

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#8838]
Hi all, 
I am referencing an older post as I cannot reopen the issue:

_Originally posted by @AJIXuMuK in https://github.com/SharePoint/sp-dev-docs/issues/3802#issuecomment-942362929_
            
Today, we stepped into the same issue.
After updating a package in a site collection app catalog, we see that the page is trying to load an old version of the webpart-file from the ClientSideAssets library. This file of course does not exist there. We double checked the entry from the ComponentManifests lists and everything is correct. If we hit F5, most of the time we get the error:

Failed to load resource: the server responded with a status of 404 ()

But sometimes the webpart is working and loading the right js-file.
As this is a production tenant, we cannot completly reinstall the package.

This bug was reported some years ago and still not fixed. Microsoft, please help!

With kind regards, Ronny

**Comment by AJIXuMuK** [comment]
@EA12 - could you please provide some extra details?
Do you have the same app installed on Tenant App Catalog and Site Collection App Catalog?
Are you using "skipFeatureDeployment" (tenant-wide deployment) or are you installing the app to the site with Add an app?
Does the new package has a new version or just updated scripts?

Thanks!
