### ISSUE TITLE
Can't install npm install -g @microsoft/generator-sharepoint on Windows Server

### ISSUE THREAD

**Issue by sonisick** [SharePoint/sp-dev-docs#884]
![microsoft generator error](https://user-images.githubusercontent.com/6710145/30968637-972f0ebe-a425-11e7-9370-2ac1ef89a08b.PNG)
![yo error](https://user-images.githubusercontent.com/6710145/30968646-a06dd834-a425-11e7-81b0-e9a0fcf9ad7e.PNG)

#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
Expected to install microsoft generator framework and use yo

#### Observed Behavior
Error messages capture in images
#### Steps to Reproduce
Just ran the command after install you with npm

**Comment by nickpape-msft** [comment]
Looks like we may have some issues with Powershell integration. Can you try running this via Command Prompt (cmd.exe) first to see if it mitigates the issue.

**Comment by nickpape-msft** [comment]
@sonisick Despite the large chunks of red text (which look like Powershell is interpreting the deprecation warnings being written to stderr as actual error), it looks like the generator was successfully installed.

Another thing you could do is append `2>&1 | Write-Host` to the commands you run in Powershell. This will redirect stderr to stdout so it does not show up in red with debugging information.
