### ISSUE TITLE
Could not retrieve Global Service Principal ID Error: Error: {}

### ISSUE THREAD

**Issue by Rhapsodist777** [SharePoint/sp-dev-docs#8843]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

I uploaded the PnP Search Webpart V4 to my SharePoint App catalog. When attempting to navigate to the API access page I ran into the following error:  Could not retrieve Global Service Principal ID Error: Error: {}

![API Access Error](https://user-images.githubusercontent.com/128991901/227789865-75ffbabd-0b91-42bd-8cf6-ea582bcb959c.png)

### Steps to reproduce

1. Download PnP Search Webpart v4 zip file 
2. Upload zip file into SharePoint app catalog
3. Approve request to enable app to be deployed on all sites. 

### Expected behavior

Should be able to go into the API Access page and either approve or deny requests.

**Comment by AJIXuMuK** [comment]
@Rhapsodist777 - is that the first time on the tenant when you're approving permissions?
Are you using Global Admin (not SharePoint Admin) for the operation?
If you go to Azure AD -> Enterprise Applications and remove Application Type as a filter - are you able to find these 2 apps:
- SharePoint Online Client Extensibility Web Application Principal
- SharePoint Online Client Extensibility Web Application Principal Helper
