### ISSUE TITLE
Page is reloaded when calling Graph API in private navigation mode in Chrome

### ISSUE THREAD

**Issue by mgrosperrin** [SharePoint/sp-dev-docs#8853]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [x] mobile (iOS/iPadOS)
- [x] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 111.0.5563.112, Android 13, iOS 16.3.1
- SPFx version: 1.16.1
- Node.js version: 16.14.2

### Describe the bug / error

When using private navigation mode in Chrome (it works in Edge & FireFox), when a call is made to MS Graph, the page is reloaded the first time it is displayed.
The page doesn't reload after its initial display (F5 does not trigger the issue again).

When using a guest account, there is one more reload.

### Steps to reproduce

1. Create a new WebPart projet with yeoman
2. Replace the method OnInit of the WebPart with the following code (inspired by https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#using-msgraphclientv3):
``` typescript
 protected async onInit(): Promise<void> {
    await this.context.msGraphClientFactory
      .getClient("3")
      .then((client: MSGraphClientV3) => {
        // From https://github.com/microsoftgraph/msgraph-sdk-javascript sample
        client
          .api("users")
          .version("v1.0")
          .select("displayName,mail,userPrincipalName")
          .get((err: string, res: string) => {
            if (err) {
              console.error(err);
            }
            console.log(res);
          });
      });
  }
``` 
3. Start the project (with `gulp serve --nobrowser`), create a page and add the WebPart.
4. With a Chrome in private navigation mode, browse to the page. The page reloads.

To reproduce, open a new tab in the private navigation Chrome instance and go to the page.

### Expected behavior

In step 4, the page should not reload.

**Comment by AJIXuMuK** [comment]
@mgrosperrin - this behavior is by design because 3p cookies are disabled in that case.
If you enable 3p cookie - everything should work without reload.
