### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by pmeripe** [SharePoint/sp-dev-docs#8855]
![image](https://user-images.githubusercontent.com/38794321/228332057-32d0c6c6-156b-4b1b-afcc-4857ee7386de.png)

**Comment by AJIXuMuK** [comment]
@pmeripe could you provide more details as described in the issue template?

**Comment by pmeripe** [comment]
@AJIXuMuK, the packages associated with the project.

Node: v14.21.3

![image](https://user-images.githubusercontent.com/38794321/229829810-cfa24157-11a1-4fbf-8168-02b2f9771d69.png)

**Comment by AJIXuMuK** [comment]
@pmeripe - the issue still doesn't contain information when the web part is failing.

However, it seems like there are issues with packages versions and also NodeJS.

Please take a look at the compatibility table: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility

So, if you've updated to 1.17.0 you need to use NodeJS v16 and also React v17, not v16.

The upgrade process is not as easy as just bumping the versions. 
I would check [CLI for Microsoft 365 spfx project upgrade](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/) command to correctly update your project to the latest version of the SPFx.
