### ISSUE TITLE
SPFx v1.16.1 - Form Customizer extension -  Error: The manifest for the form customizer component with id {..} was not found.

### ISSUE THREAD

**Issue by necik11** [SharePoint/sp-dev-docs#8860]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 Opera
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
  - Chrome 111.0.5563.147
- SPFx version
  - 1.16.1  
- Node.js version
  - v16.14.1

### Describe the bug / error

From [Build your first Form Customizer extension](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-form-customizer) 
I have create create project, change  attributes: "RootFolder" & "pageUrl".
After gulp serve, everything working fine.
But when i use this commands: (as i am used from previous version for webparts)
```
gulp bundle --ship
gulp package-solution --ship
```
and upload to app catalog:

Upload to appCatalog - 
![image](https://user-images.githubusercontent.com/25322303/228794861-eb578a31-3a2b-4586-80ab-baac5585a82b.png)

When i choose :  "Only enable this app" - i can see app in site content - 
![image](https://user-images.githubusercontent.com/25322303/228795132-41744d3a-8d43-49ef-98e0-b5af6e3b77e3.png)

When i choose :  "Enable this app and add it to all sites" - i cant see this package in app content.

But if I choose any option when calling newform I get an error:
![image](https://user-images.githubusercontent.com/25322303/228795656-23bea2a6-b878-4b6b-97aa-aaab63270326.png)

`Error details: Error: Error initializing application. Error: Error: Error preloading the page-based application. Error: Error: The manifest for the form customizer component with id {f667f915-5bf9-465b-b125-a94c00bf96eb} was not found.`

Script for update CT i have used PnP PowerShell similiar like this [Associate Form Customizer Extension with List or Libraries Form](**url**)

I have trying even[ run below command:](https://github.com/SharePoint/sp-dev-docs/issues/8660)
npm i react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact
Which help me run "Dialog" for  ListView Command Set extension in  this version of spfx...

I've done a dirty hack in the past and this would be a cool thing... if it worked as it should, thanks much for tips ! 👍 

### Steps to reproduce

1. yo @microsoft/sharepoint
2. enter enter..
3. change serve.config
4. gulp serve - works
5. gulp bundle --ship
6. gulp package-solution --ship
7. upload to appCatalog
8. change $Ct.NewFormClientSideComponentId  
9. Go Test List - New - and got error 

### Expected behavior

Redirect to SPListForm.aspx like when i use gulp serve.

**Comment by AJIXuMuK** [comment]
@necik11 - thank you for reporting the issue.
For the app visibility behavior - everything is correct. If you enable it on all sites from the app catalog the app will be served from the App Catalog itself, without any app visible in the site itself.

For the error - could you please confirm that `f667f915-5bf9-465b-b125-a94c00bf96eb` is the id of your form customizer? Do you have the same value in the manifest?

**Comment by necik11** [comment]
So for the app visibility behavior : 

- If i have package with webpart and **"enable it on all sites"** = I can use this webpart anywhere without adding the app to site. 

- If not - i must manualy add like site admin. 👍 
 
For the error: i was writting i use gulp serve and its working..if i had wrong componentId so then wouldnt work either?

![image](https://user-images.githubusercontent.com/25322303/228922894-37c580dc-11b9-466c-88dd-23af91906969.png)

![image](https://user-images.githubusercontent.com/25322303/228923047-a163ad1c-ed10-4c36-8bfd-7717e9a8a77a.png)
