### ISSUE TITLE
API to scope search to hub sites?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#887]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

On Ignite Hub Sites have been announced. And it is said that search will be scoped to all the sites that are associated with the hub.
Will there be an API to use the same scope in search queries? Something similar to `SPSite:site-url`?
@VesaJuvonen - cc-ing you on that :)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
