### ISSUE TITLE
🐞SPFx Web Part Manifest Published Schema Outdated (as of v1.17)

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8873]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome v111.0.5563.146
- SPFx v1.17
- Node.js v16.18.0

### Describe the bug / error

The currently published JSON schema for web part manifests is outdated according to changes in the SPFx v1.17 release.

According to the release notes, a new property `supportsSelfFrameingInTeams` was added to tell SPFx to render the web part within an `<iframe>` rather than a `<div>` as it usually is.

This makes it hard to know exactly where this should be placed (at the root or is it in the property collection?) and what values it expects (assume the default is `false`, but unclear).

### Steps to reproduce

- Create a new SPFx web part using SPFx v1.17
- Open web part manifest & try to add the `supportsSelfFrameingInTeams` property, notice it’s not listed
- Browse to the schema listed in the top of the file
- Search for `supportsSelfFrameingInTeams`, notice it’s not found

### Expected behavior

IntelliSense shows the property & schema has the property with a description listed.

**Comment by AJIXuMuK** [comment]
fixed
