### ISSUE TITLE
SPFx v1.17 - Web Part Top Actions - Don’t work in hosted workbench

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8874]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome v111.0.5563.146
- SPFx v1.17
- Node.js v16.18.0

### Issue description

Top actions seem only work on real SharePoint pages… they aren’t working in the hosted workbench.

Is this by design & expected?

If so, are there plans to update the hosted workbench to make this easier to develop.

**Comment by AJIXuMuK** [comment]
@andrewconnell - this is by design.
We are looking into workbench-related changes (not only for Top Actions).
But there is no any ETA on that.
