### ISSUE TITLE
🐞SPFx v1.17 - Generator Renamed to M365, but still shows SharePoint Logo

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8875]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome v111.0.5563.146
- SPFx v1.17
- Node.js v16.18.0

### Describe the bug / error

The Yeoman Generator for SharePoint has been renamed to “Microsoft 365”, but the ASCII logo at the end is still using the SharePoint Online logo.

### Steps to reproduce

- run **yo @microsoft/sharepoint**
- observe the Yeoman generator displays “Welcome to Microsoft 365. Let's create a new Microsoft 365 solution.“ instead of the previous “Welcome to SharePoint Online. Let's create a new SharePoint solution”
- pick any options to run the generator
- observe the closing logo of the confirmation shows the SharePoint logo in ASCII art

### Expected behavior

The closing logo of the confirmation shows the Microsoft 365 logo in ASCII art.

**Comment by AJIXuMuK** [comment]
@andrewconnell - thanks for reporting this one! 
We changed the wording but not the name of the generator - it is still SPFx Yeoman Generator.
And the correct brand icon for it is SharePoint logo.
