### ISSUE TITLE
🐞 SPFx v1.17 - ACE - Default QuickView uses old Adaptive Card schema

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#8878]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome v111.0.5563.146
- SPFx v1.17
- Node.js v16.18.0

### Describe the bug / error

The Yeoman Generator for SharePoint, when creating a new ACE, uses Adaptive Card schema v1.2 in the default QuickView card template that.

It should be set to the current supported version so experienced developers don’t need to do this for every project they create, and inexperienced developers don’t get confused by they can’t use some Adaptive Card features.

### Steps to reproduce

- run **yo @microsoft/sharepoint**
- create a new ACE component using any of the templates
- after creating the project, open the ./src/adaptiveCardextensions/{ACE_NAME}/quickView/template/*.json
- observe the `version` property is set to `1.2`

### Expected behavior

The version of the adaptive card schema should be set to the current supported version of the Adaptive Card schema for ACEs.

**Comment by AJIXuMuK** [comment]
1.17.1 is out.
