### ISSUE TITLE
ListViewCommandSet not loading after installation

### ISSUE THREAD

**Issue by praveenhooda** [SharePoint/sp-dev-docs#8879]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version:  1.16.1
- Node.js version: v16.18.1
- react: 17.0.1
- Package.json file details as below
 "engines": {
    "node": ">=16.13.0 <17.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fluentui/react": "^8.105.2",
    "@fluentui/react-hooks": "~7.16.4",
    "@microsoft/applicationinsights-react-js": "3.4.0",
    "@microsoft/applicationinsights-web": "~2.8.9",
    "@microsoft/decorators": "1.16.1",
    "@microsoft/load-themed-styles": "~2.0.20",
    "@microsoft/sp-core-library": "1.16.1",
    "@microsoft/sp-dialog": "^1.17.0",
    "@microsoft/sp-http": "^1.16.1",
    "@pnp/core": "^3.11.0",
    "@pnp/graph": "^3.12.1",
    "@pnp/logging": "^3.12.1",
    "@pnp/queryable": "^3.11.0",
    "@pnp/sp": "^3.12.1",
    "@pnp/spfx-controls-react": "3.12.0",
    "history": "~5.3.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.16.1",
    "@microsoft/eslint-plugin-spfx": "1.16.1",
    "@microsoft/rush-stack-compiler-4.5": "^0.3.0",
    "@microsoft/sp-build-web": "1.16.1",
    "@microsoft/sp-listview-extensibility": "1.16.1",
    "@microsoft/sp-module-interfaces": "1.16.1",
    "@types/lodash": "~4.14.184",
    "@types/react": "~17.0.8",
    "@types/react-dom": "~17.0.11",
    "@types/webpack-env": "1.15.2",
    "@typescript-eslint/parser": "~5.33.1",
    "ajv": "6.12.5",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "~4.0.2",
    "typescript": "~4.5.4"
  }

### Describe the bug / error

gulp serve loads the list view command set
On installing package on Sharepoint Online site the command set does not load

### Steps to reproduce

1. Create listview command set based on SPFx version:  1.16.1
2. On packaging and installing it the command does not load
3.

### Expected behavior

Command set needs to load

**Comment by AJIXuMuK** [comment]
@praveenhooda - how do you add it to the list or document library?
Are you using tenant-wide deployment or "Add an app" on the specific site?
What do you have in your `elements.xml` and `ClientSideInstance.xml` files?

Also, as a separate note, you need to use the same versions for all spfx-related packages.
`"@microsoft/sp-dialog": "^1.17.0",` is not correct - it should be 1.16.1 based on other packages you're using.
