### ISSUE TITLE
CSS 'border-bottom' overwritten/missing on .commandBarWrapper and 'Site Header'

### ISSUE THREAD

**Issue by DPCamino** [SharePoint/sp-dev-docs#8897]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Sometime in the last few months, I noticed bottom-borders on SPO site headers have been missing. This is OOTB without any site modification or SPFx webparts/extensions.

Initially when a site loads, you can see a bottom border on the Site Header and Command Bar section (split second). It then disappears. 

Looking into the developer console, while a bottom-border CSS property is set, there is an additional CSS rule overwriting the border property. I'm not sure why this was deliberately added. When you have headers with a white background and content on a white background, you don't have any separation between the header, command bar, and content below. It appears to be "floating" without any separation.

Here are the CSS properties:

### Site Header
```
div[data-sp-feature-tag="Site header host"] {
    border-bottom-style: none;
}

[data-sp-feature-tag="Site header host"] {
    border-bottom: 1px solid;
    border-color: #F0F0F0;
}
```

### Command Bar
Dynamic class name is added to .commandBarWrapper div
```
.commandBarWrapper {
    border-bottom: 1px solid;
    border-color: #F0F0F0;
}

.hs_ah_ada2ac09 {
    border-bottom-style: none!important;
}
```

### Steps to reproduce

1. Load any SPO site (Teams site, Communication site, etc) - OOTB
2. View header and command bar
3. Open Developer Console/Inspect to confirm CSS properties

### Expected behavior

Keep existing border-bottom or remove property that overwrites this property (not sure for the rationale why it was added in the first place).

Perhaps this was added to remove a border if a theme other than white or background color was applied, and there is enough contrast without? Not sure, but when the background is white and content is white all of these elements are "floating" on the page without separation.

**Comment by VesaJuvonen** [comment]
This seems like an oob feature issue - or if you are taking dependency on the styles, that's not technically supported. We will not guarantee that the CSS or the html structure will not have changes. Your specifically reported issue seems like a but in the oob rendering and not about the extensibility, so closing the issue.
