### ISSUE TITLE
🐞 Generator v1.3 missing peer dependency?

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#890]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
No errors reported after installing the v1.3 generator.

No errors when running `npm list -g --depth=0`

#### Observed Behavior

![image](https://user-images.githubusercontent.com/2068657/30999844-9e2648d8-a4a5-11e7-83ed-cac1a3fa882f.png)

![image](https://user-images.githubusercontent.com/2068657/30999883-d3a0248e-a4a5-11e7-8272-bb434ec9ec38.png)

**Comment by iclanton** [comment]
We're working on fixing this for the next drop. This shouldn't cause any problems with running the generator, though.

**Comment by andrewconnell** [comment]
Thanks, @iclanton ...

FYI - the process of closing an issue before it's really resolved is very odd with this team (not just this issue, but it's consistent across this org)... closed shouldn't indicate that it's been acknowledged/tracked in another bug tracking system and will be fixed in a future update. Closed uniformly indicates "issue resolved... no longer an issue".

**Comment by VesaJuvonen** [comment]
Let's close this when we actually have this fixed - like typically it's done. Reopened until the new drop is available for also others to know that this will be fixed... to avoid duplicates.

**Comment by andrewconnell** [comment]
Appears addressed in generator v1.3.4
