### ISSUE TITLE
How to make icons show as per the documentation for ITopActionsDropdownOption?

### ISSUE THREAD

**Issue by MatthewSammut** [SharePoint/sp-dev-docs#8904]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome - Version 112.0.5615.121 (Official Build) (64-bit)
- SPFx  - 1.17.1 
- Node.js - 16.3
- @microsoft/sp-top-actions": "1.17.1",
- "office-ui-fabric-react": "7.199.1",

### Issue description

I need to add dropdown options with icons as specified in the [documentation](https://learn.microsoft.com/en-us/javascript/api/sp-top-actions/itopactionsdropdownoption?view=sp-typescript-latest ). 

I tried to follow the structure as per the documentation and the typed object in the libraries:

![image](https://user-images.githubusercontent.com/16598563/232790127-b8f16acb-5fdc-4a00-b4a4-03fea0481c73.png)

![image](https://user-images.githubusercontent.com/16598563/232790193-4df53498-6cee-4245-9688-c00298303ed8.png)

The end result shows the dropdown options as expected, but without icons ->

![image](https://user-images.githubusercontent.com/16598563/232790422-9a0b07f9-bcee-4e57-9e0d-d605bf13dda8.png)

Debugging the component always seem to have hasIcons:false, and IconProps:undefined (even though they are specified): 

![image](https://user-images.githubusercontent.com/16598563/232791079-4fdcebbc-19e3-40d2-bad5-0b6aaa99a481.png)

What am I missing? Or is it a potential bug?

Finally, it would be helpful to have a more extensive example shown in the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/getting-started-with-top-actions#define-the-top-actions-dropdown-field).

**Comment by AJIXuMuK** [comment]
@MatthewSammut - thank you for reporting this issue!
It is definitely a bug and we'll be working on a fix.

**Comment by MatthewSammut** [comment]
Hi, thanks for working on this. 

Do you have an update? Would this fix be available as part of 1.17.2? Is there an estimated timeframe for when 1.17.2 will be available?

**Comment by AJIXuMuK** [comment]
@MatthewSammut - as this is a service-side fix, we won't need a new version of SPFx generator - the things will just start working when the fix is rolled out.
For the ETA - based on rollout cadence and when it's going to be fixed I would expect the changes worldwide in 3-4 weeks

**Comment by a1mery** [comment]
I've just tried to add icons on dropdown options, it works fine now ! Thanks 👍
