### ISSUE TITLE
Issue with SPFx 1.17.1 and MSGraphClientV3

### ISSUE THREAD

**Issue by a1mery** [SharePoint/sp-dev-docs#8909]
When I'm trying to use MSGraphClientV3 in a SPFx webpart (SPFx 1.17.1) I'm getting the following error:

`Argument of type '(client: MSGraphClientV3) => void' is not assignable to parameter of type '(value: MSGraphClientV3) => void | PromiseLike<void>'.
  Types of parameters 'client' and 'value' are incompatible.
    Type 'import("/home/ath-ubuntu/projects/react-graph-webpart-report/node_modules/@microsoft/sp-property-pane/node_modules/@microsoft/sp-http-msgraph/dist/index-internal").MSGraphClientV3' is not assignable to type 'import("/home/ath-ubuntu/projects/react-graph-webpart-report/node_modules/@microsoft/sp-http-msgraph/dist/index-internal").MSGraphClientV3'.
      Types have separate declarations of a private property '_createGraphClientInstance'.`

The same code was working fine with SPFx 1.16.1.

Thank you for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2381d26e-96c9-44de-8e4e-f70edc2db498
* Version Independent ID: f81cacee-a1cd-89dd-ee53-c84689c03917
* Content: [Use the MSGraphClientV3 to connect to Microsoft Graph](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph)
* Content Source: [docs/spfx/use-msgraph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-msgraph.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@a1mery - can you share your code?
Seems like not all the packages are updated to the needed version.

**Comment by a1mery** [comment]
Actually you were right ! 
I forgot to update the @microsoft/sp-http package.

Once updated, it works again !!

Thank you for your help @AJIXuMuK 👍
