### ISSUE TITLE
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by jtlivio** [SharePoint/sp-dev-docs#8914]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.17.1
- Node.js latest lts/gallium (16.20.0)
- WSL2
- NVM 0.38.0

### Issue description

When trying to `gulp serve` got this message. I'm not sure if it is related with the SPFx or WSL2

**Workarounds**

```bash
sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
sudo apt update
sudo apt upgrade
```

```powershell
Get-Service LxssManager | Restart-Service
```

**Error**

```bash
[21:09:46] [tsc] typescript version: 4.5.5
(node:641) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/jlivio/PNPDEV/Timeline/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:537:15)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:537:15)
    at Pipe.<anonymous> (net.js:686:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:130:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[21:09:48] Finished subtask 'copy-static-assets' after 2.57 s
```

In the index.ts

```ts
if (opts.wait) {
	return new Promise((resolve, reject) => {
		cp.once('error', reject);

		cp.once('close', code => {
			if (code > 0) {
				reject(new Error('Exited with code ' + code)); //HERE
				return;
			}

			resolve(cp);
		});
	});
}
```

**Comment by AJIXuMuK** [comment]
@jtlivio - node is unhappy with the promise not being processed with `.then().catch()`.

This has nothing to do with SPFx itself.

**Comment by jtlivio** [comment]
@AJIXuMuK Node.js is the JavaScript runtime environment for the SPFx, it's the core of the Chain, so in this case and since the incident is closed and your are saying is all good with SPFx, I'll open a ticket in Node and other for WSL2 in Microsoft, "it works in my machine, so docker was born". :) I'll let you know

Thank you 
Joao
