### ISSUE TITLE
Issue in building the SPFx app solution package

### ISSUE THREAD

**Issue by MounikaRamesh123** [SharePoint/sp-dev-docs#8917]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I am trying to build the SPFx app solution for one of the webparts(https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-accordion-section) in the package (https://github.com/pnp/sp-dev-fx-webparts). But, I am getting this error (Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor). Could anyone please help me in solving this?

**Comment by AJIXuMuK** [comment]
@MounikaRamesh123 - you should ask this question in the web part samples repo (where the sample lives).
Most probably your dev machine is based on more up to date version of SPFx than the one needed for the web part (1.10).

**Comment by MounikaRamesh123** [comment]
@AJIXuMuK - I am still facing the same issue even after changing the SPFx version
