### ISSUE TITLE
Unable to use Fluent UI Font Icons after SPFx 1.16.x in No-Framework web part

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#8921]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Edge Version 112.0.1722.58 (Official build) (64-bit)
- SPFx 1.17.1, 1.16.1, 1.16.0
- Node.js v16.19.1

### Describe the bug / error

I'm trying to use Fluent UI icons as I have done in the past. This involves running `initiatlizeIcons` and then using `getIconClassName`. Starting in 1.17.x you reference them from this location:

```TypeScript
import { initializeIcons } from '@fluentui/font-icons-mdl2';
import { getIconClassName } from '@fluentui/style-utilities';
```

In versions 1.15.2, 1.16, 1.16.1 you reference them from this location:

```TypeScript
import { initializeIcons } from '@uifabric/icons';
import { getIconClassName } from '@uifabric/styling';
```

This breaks the whole web part in any version past 1.15.2. Strangely, the error I receive depends on the tenant. In my standard work tenant, I get this error for SPFx 1.16, 1.16.1, and 1.17.1:
![image](https://user-images.githubusercontent.com/8364109/234336578-535bb1e6-8e87-4a08-864a-a11fe996f9a5.png)

In my development tenant (targeted release) I get this error (same versions):
![image](https://user-images.githubusercontent.com/8364109/234336869-f01f12ea-8896-4147-8916-0194c101c1f3.png)

I have generated these web parts using the No-Framework option and have added no additional dependencies.

The exact same code works just fine in SPFx 1.15.2.

**My Guess**

Based on the inclusion of the 17.0.2 version number in the first error message above, I'd guess this is an issue related to React. I'm not using React nor do I intend to for this web part.

There are some additional issues that seem to indicate this as well, for example #8795

### Steps to reproduce

1. Generate a project using SPFx 1.16 or higher
2. Add import statements `initializeIcons` as shown above (difference between versions)
3. Call `initializeIcons()`
4. Serve it up and observe the errors

Alternatively, I've got some really basic projects that demonstrate the issue in 1.16, 1.16.1 and show it working in 1.15.2 here: https://github.com/thechriskent/fabricissue

### Expected behavior

I expected things to work as they do in SPFx 1.15.2:

![image](https://user-images.githubusercontent.com/8364109/234341077-2e01f27a-4b55-43c8-b645-9739c4b7656d.png)

**Comment by AJIXuMuK** [comment]
@thechriskent - the problem here is the latest v7 versions of Fluent UI has a dependency on React v17 which is getting resolve to 17.0.2.
SPFx core is based on v17.0.1. So we can't resolve 17.0.1 and failing.
Quick fix here is to add direct dependency to React 17.0.1 similarly as it is done in React scaffolding template.
