### ISSUE TITLE
List web part dynamic filtering access from SPFx

### ISSUE THREAD

**Issue by johnnycardy** [SharePoint/sp-dev-docs#8932]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Dynamic filtering is available to connect two or more List web parts on a page. Selecting a row from one list will apply the value of a particular column as a filter to the other Lists on the page.

My question is - what do we know about the possibility of performing these filters from SPFx?

My use case is that someone selects a category within my web part, and all list items from that category are filtered elsewhere on the page.

I remember hearing somewhere that this capability would be opened up to SPFx but I can't find any evidence of that so I'm starting to doubt myself.

Thanks.

**Comment by AJIXuMuK** [comment]
@johnnycardy - unfortunately right now List and Doc Library web parts can communicate between each other only, there is no way for custom web parts to filter something.
We have the backlog item to enable it but no ETA.
