### ISSUE TITLE
Error after deployment Only "Cannot read properties of undefined (reading 'id')"

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#8934]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version latest
- SPFx version 1.17.1
- Node.js version  16.19.0
- etc

### Describe the bug / error

I made a new SPFx 1.17.1 react web part and it works fine in the workbench. 
after deploying, it shows error : `ERROR: Cannot read properties of undefined (reading 'id')`

```
CALL STACK:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3d3eb7503bf5891494467738f00140f9.js:70:747315
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3d3eb7503bf5891494467738f00140f9.js:70:747283)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3d3eb7503bf5891494467738f00140f9.js:70:749044
    at async Promise.all (index 0)
```

### Steps to reproduce

1. create a project with yo
2. add bunch of react component
3. code the functionality
4. test with the workbench
5. gulp clean --ship && gulp build --ship && gulp bundle --ship && gulp package-solution --ship
6. deploy the .sppkg 
7. add the web part to the site's apps
8. embed the web part

### Expected behavior

The web part should show the as same as in the workbench

Thank you

**Comment by AJIXuMuK** [comment]
@Ofer-Gal - thanks for reporting the issue.
Could you please share your package or code with us as I can't repro it on my end.

**Comment by Ofer-Gal** [comment]
It happened again with an upgraded to 1.17.1 webpart. 
I attached the package
