### ISSUE TITLE
Question re SPFx 1.12.1 and authentication (specifically, ADAL to MSAL)

### ISSUE THREAD

**Issue by tcattermole** [SharePoint/sp-dev-docs#8948]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx 1.12.1
node 14.17.0

### Issue description

I have a question re SPFx and authentication. I am currently in the middle of upgrading an SPFx solution from 1.10.0 to 1.12.1. The primary reason for doing this SPFx upgrade is of course because it is overdue and good practice. The other is prompted by the upcoming retirement/deprecation of ADAL in favor of MSAL. I will be honest up-front and state that authentication is not my strongest point. Looking under the hood of the AADHttpClient (which we use) in our current 1.10.0 project I see references to it using ADAL but a future upgrade to MSAL. Is this something implemented in the sp-http package required by 1.12.1? Or am I misunderstanding the nature of this migration from ADAL to MSAL (at least insofar as it affects SPFx solutions in SPO) and is it something handled in the "plumbing" by SPO and so entirely independent of the SPFx version used?

**Comment by AJIXuMuK** [comment]
@tcattermole - sorry for the really long delay.
Authentication part is implemented by the service. So we're in charge of what auth library is being used behind the scenes.
It does not directly depend on the version of SPFx you're using in the project.
