### ISSUE TITLE
Is it possible to replace the site logo based on certain conditions using Application Customizer?

### ISSUE THREAD

**Issue by thePaddyVP** [SharePoint/sp-dev-docs#895]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is it possible to replace the site logo based on certain conditions using Application Customizer?

#### Details
I am using Application Customizer and trying to change the site logo image. I am using REST calls to query the image url and using the below line of code on onInit() trying to change the src attribute of the logo. I am using jQuery to find the dom element of the image and trying to set the src attribute of that image. I can see that it is getting set but at the end it is again getting overwritten with the actual site logo. I was wondering is this possible to achieve?

$('.ms-siteLogo-actual img').attr('src', 'imageurl');

NOTE: I am trying to do it this way as the logo needs to change on different pages based on different criteria.

**Comment by mcmynn83** [comment]
Thanks for your feedback.  At this time it is not possible to do this.
