### ISSUE TITLE
Lint error occurred with "@typescript-eslint/no-extra-semi"

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [SharePoint/sp-dev-docs#8953]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version  Edge Version 113.0.1774.35 (Official build) (64-bit)
- SPFx version  1.16.1
- Node.js version  16.15.0
- etc

### Describe the bug / error

Lint error occurred when running gulp tasks(gulp serve/ gulp bundle) with SPFx v1.16.1

### Steps to reproduce

1. Install SPFx v1.16.1 globally 'npm install -g @microsoft/generator-sharepoint@1.16.1'
2. Scaffold SPFx project with 'yo @microsoft/sharepoint' and 'npm install' is automatically executed
3. Run 'gulp serve' or 'gulp bundle' and got following error
![image](https://user-images.githubusercontent.com/73154171/237029865-8f4a913a-f7de-410f-8089-b618a02c877a.png)

### Expected behavior

I should be able to run gulp tasks to debug or bundle package successfully.

**Comment by AJIXuMuK** [comment]
@HuihuiWu-Microsoft - could you please check if the issue still repro-es on the latest version of SPFx (1.17.1)?

**Comment by gavinbarron** [comment]
Just got this exact error on a totally clean install of `@microsoft/generator-sharepoint@1.16.1`
Not looking to use v1.17.2 yet as I need to validate a 1.16 usecase.

**Comment by gavinbarron** [comment]
FWIW as a hackish work-around I as able to get building by disabling a couple of rules in the .eslintrc file by adding these lines to the start of the rules object:
```json
      rules: {
        "@typescript-eslint/no-extra-semi": 0,
        "@typescript-eslint/no-empty-function" : 0,
```

**Comment by HuihuiWu-Microsoft** [comment]
Hi @AJIXuMuK , I tried SPFx v1.17.2 and doesn't have the issue. Will you fix the issue on v1.16.1 since some developers might still use the legacy version?

**Comment by Eiglimar** [comment]
@gavinbarron thx ma man! build success here doing that!

**Comment by AJIXuMuK** [comment]
@HuihuiWu-Microsoft - no. It doesn't work like that. All fixed appear as a new version. So if there even need for a fix it would be 1.17.x

**Comment by AJIXuMuK** [comment]
I can repro it on 1.16.1.
Seems like issue with some bumped dependency.
Although we won't fix 1.16.1 version as the problem doesn't exist in 1.17.2 (which is the latest one) we will look into the problem to avoid such thing in future.

**Comment by gavinbarron** [comment]
@Eiglimar just be aware that those two linting rules are now disabled and won't be shown in your editor or detected. Those two rules specifically are not a big deal, but just something to be aware of.

**Comment by HuihuiWu-Microsoft** [comment]
Thanks @AJIXuMuK!

**Comment by AJIXuMuK** [comment]
@HuihuiWu-Microsoft @gavinbarron @Eiglimar - just to provide another workaround: do `npm i --save-dev --save-exact eslint@8.28.0`
