### ISSUE TITLE
SPFx 1.17.2 webpart as a teams app. Save button disable while adding app in teams meeting

### ISSUE THREAD

**Issue by ashokghoghari** [SharePoint/sp-dev-docs#8957]
![image](https://github.com/SharePoint/sp-dev-docs/assets/14246157/2047d19c-e949-414e-bae2-cdfba3812cb8)

I am using SPFX 1.17.2 to create Teams Meeting Side Panel App. I have tried with and without creating manifest file in ./teams folder.
Also added below in webpart.manifest.json file
"supportedHosts": [
    "SharePointWebPart",
    "SharePointFullPage",
    "TeamsMeetingApp"
  ],

below is manifest file added in ./teams folder
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
  "manifestVersion": "1.16",
  "packageName": "{{SPFX_PACKAGE_NAME}}",
  "id": "{{SPFX_COMPONENT_ID}}",
  "version": "1.0",
  "developer": {
    "name": "Ashok Ghoghari",
    "websiteUrl": "",
    "privacyUrl": "",
    "termsOfUseUrl": "",
    "mpnId": ""
  },
  "name": {
    "short": "{{SPFX_COMPONENT_NAME}}",
    "full": "{{SPFX_COMPONENT_NAME}}"
  },
  "description": {
    "short": "{{SPFX_COMPONENT_SHORT_DESCRIPTION}}",
    "full": "{{SPFX_COMPONENT_LONG_DESCRIPTION}}"
  },
  "icons": {
    "outline": "{{SPFX_COMPONENT_ID}}_outline.png",
    "color": "{{SPFX_COMPONENT_ID}}_color.png"
  },
  "accentColor": "#ffffff",
  "configurableTabs": [
    {
      "configurationUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26componentId={{SPFX_COMPONENT_ID}}",
      "canUpdateConfiguration": true,
      "scopes": ["team", "groupchat"],
      "context": [
        "channelTab",
        "privateChatTab",
        "meetingSidePanel",
        "meetingDetailsTab",
        "meetingChatTab",
        "meetingStage",
      ]
    }
  ],
  "validDomains": [
    "*.microsoft.com",
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "resourceseng.blob.core.windows.net"
  ],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
}

**Comment by ashokghoghari** [comment]
Any update on this issue?

**Comment by AJIXuMuK** [comment]
@ashokghoghari - sorry for the long delay.
First of all, `TeamsMeetingApp` is invalid value for the supported hosts. You should use `TeamsTab` and `TeamsPersonalApp`.
Second, your teams manifest values for SPFX_COMPONENT_NAME and SPFX_COMPONENT_ID should be replaced with actual name and id of the web part.

**Comment by ashokghoghari** [comment]
![image](https://github.com/SharePoint/sp-dev-docs/assets/14246157/187370ae-13f2-477a-b6a0-22b47765faf5)
@AJIXuMuK ,
Thanks for your reply.

I was checking schema here and it is showing TeamsMeetingApp a valid value

**Comment by AJIXuMuK** [comment]
@ashokghoghari - so I've tested 2 approaches: 
- one when you have `TeamsMeetingApp` in the supported hosts and don't provide the custom manifest (as it is not needed)
- second with the custom manifest

Both are working for me without any issues.
I'm attaching the solutions here - could you please test it on your side?
[meeting-app-manifest.zip](https://github.com/SharePoint/sp-dev-docs/files/11636537/meeting-app-manifest.zip)
[meeting-app.zip](https://github.com/SharePoint/sp-dev-docs/files/11636538/meeting-app.zip)
