### ISSUE TITLE
Webparts missing from tool list when running gulp-serve after newly scaffolded webpart SPFX 1.15.2 / 1.16.0

### ISSUE THREAD

**Issue by SaltySweats** [SharePoint/sp-dev-docs#8963]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.15.2 / 1.16.0
- Node.js version 16.13.2

### Describe the bug / error

As of yesterday, newly scaffolded webparts do not appear in the tools list when serving locally using SPFX 1.15.2 and 1.16.0. Just to be sure this is reproduceable, you can simply create a new directory, scaffold a new webpart using **yo @microsoft/generator-sharepoint**, run **gulp serve**, and you will observe the webpart is not available for selection.

### Steps to reproduce

1. Create a new webpart via the yeoman generator named 'helloworld': yo @microsoft/generator-sharepoint
2. Run: gulp serve
3. Observe that your new webpart does not appear in the tool list
![image](https://github.com/SharePoint/sp-dev-docs/assets/36278490/4351198b-f27d-4494-88c9-8b84686bd2f5)

### Expected behavior

Webpart should be available for selection in the tools list.

**Comment by AJIXuMuK** [comment]
@SaltySweats are you seeing any errors in the console?
Like certificate issues for `localhost`?

**Comment by SaltySweats** [comment]
@AJIXuMuK Thanks for the reply, no errors in the console and the certificate is valid. I did try to delete all certificates and run gulp trust-dev-cert followed by the gulp serve just to ensure it was nothing related to the certificate. I can load the https://localhost:4321/temp/manifests.js fine in the browser.

**Comment by SaltySweats** [comment]
@AJIXuMuK One other note to mention, if I build the webpart and deploy it, the webpart is now available for selection with no issues.

**Comment by AJIXuMuK** [comment]
@SaltySweats - and to double-confirm - you're testing on the workbench, correct?

**Comment by SaltySweats** [comment]
@AJIXuMuK correct

**Comment by trillian74** [comment]
There is definitely work being done here by someone, but i'd be good to have a feedback from @VesaJuvonen or someone because there's alot of issues here that is connected.

Right now i cannot code and debug at the same time because the web parts keep disappearing:/ from workbench

**Comment by AJIXuMuK** [comment]
@SaltySweats - we made a fix.
Could you please test on your end?

Thanks!

**Comment by SaltySweats** [comment]
@AJIXuMuK Thanks so much! Things appear to be working as intended now. Much appreciated!

**Comment by SaltySweats** [comment]
@AJIXuMuK  out of curiosity, do you have a link to the fix?

**Comment by AJIXuMuK** [comment]
@SaltySweats - these are internal changes that I can't share publicly.
