### ISSUE TITLE
Webpart dont appear in workbench 1.16/1.17

### ISSUE THREAD

**Issue by lobba111** [SharePoint/sp-dev-docs#8967]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.17
- Node.js version 16.13.0
- etc

### Describe the bug / error

I have been working on a web part for the last couple of weeks, and everything has been working fine until 10/5/23. The problem I experience is that when I try to run my web part in the workbench, everything looks fine, but the web part doesn't appear. The workbench loads the manifest file on localhost:4321, but nothing loads in the workbench. Sometimes the web part appears, and I can load and run it one time, but then it crashes and disappears.
 

### Steps to reproduce

1. Scaffold a new or old project and try to run it 
2. Refrech workbeanch after load.
3.  😭😭😭😭😭😭😭😭

### Expected behavior

I cannot find the web part, or it appears for a little while and then disappears again.

**Comment by lobba111** [comment]
We did a workaround to get it to work. I packed and shipped the web part, and uploaded it to the app catalog on the site I was using. That made the problem go away.

**Comment by trillian74** [comment]
> We did a workaround to get it to work. I packed and shipped the web part, and uploaded it to the app catalog on the site I was using. That made the problem go away.

So, after that you made it appear in workbench, even after a code change and refresh of window? Can't see that solving the issue?

**Comment by AJIXuMuK** [comment]
Sorry for the regression.
It has been addressed. Locally served web parts and ACEs should be visible in the workbench toolbox again.

@lobba111  - could you please confirm on your end?

**Comment by lobba111** [comment]
@AJIXuMuK it seems to work again :)

**Comment by lobba111** [comment]
> > We did a workaround to get it to work. I packed and shipped the web part, and uploaded it to the app catalog on the site I was using. That made the problem go away.
> 
> So, after that you made it appear in workbench, even after a code change and refresh of window? Can't see that solving the issue?

yes :) nahh i was just as suprised
