### ISSUE TITLE
How to create an api connection instead username\password

### ISSUE THREAD

**Issue by zoomin-mis** [SharePoint/sp-dev-docs#8976]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We need to transfer files from our sharepoint to an sftp.
We want to do it using api instead of username and password.
+ we want specific folder to be shared with this api.

**Comment by VesaJuvonen** [comment]
You'd be using Microsoft Graph APIs for this. Connecting to the site using App permissions granted in Azure AD and then move the file using the APIs.
