### ISSUE TITLE
Error on build after create spfx webpart (spfx 1.17.2) - ESLint: 8.7.0 ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin"

### ISSUE THREAD

**Issue by lreome** [SharePoint/sp-dev-docs#8985]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version : 1.17.1
- Node.js version:16.13.0
+-- @microsoft/generator-sharepoint@1.17.2
+-- browser-sync@2.26.5
+-- gulp@4.0.2
`-- yo@4.3.1

### Describe the bug / error

Hello,

I created the new webpart spfx wich React.

just after creatind an spfx webpart, i run the gulp build / gulp serve command.

The following error is returned: 

Build target: DEBUG
[11:39:47] Using gulpfile C:\projet\new2\gulpfile.js
[11:39:47] Starting 'build'...
[11:39:47] Starting gulp
[11:39:47] Starting subtask 'pre-copy'...
[11:39:47] Finished subtask 'pre-copy' after 347 ms
[11:39:47] Starting subtask 'copy-static-assets'...
[11:39:47] Starting subtask 'sass'...
[11:39:48] Finished subtask 'sass' after 691 ms
[11:39:48] Starting subtask 'lint'...
[11:39:48] [lint] eslint version: 8.7.0
[11:39:48] Starting subtask 'tsc'...
[11:39:48] [tsc] typescript version: 4.5.5
[11:39:48] Finished subtask 'copy-static-assets' after 837 ms
[11:39:50] Error - [lint] Unexpected STDERR output from ESLint:
Oops! Something went wrong! :(
ESLint: 8.7.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "C:\projet\new2".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install @typescript-eslint/eslint-plugin@latest --save-dev
The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in ".eslintrc.js » @microsoft/eslint-config-spfx/lib/profiles/react » ./default".
If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

[11:39:50] Error - [lint]
[11:39:50] Finished subtask 'lint' after 1.56 s
[11:39:52] Finished subtask 'tsc' after 3.92 s
[11:39:52] Starting subtask 'post-copy'...
[11:39:52] Finished subtask 'post-copy' after 979 μs
[11:39:52] Finished 'build' after 5.09 s
[11:39:53] ==================[ Finished ]==================
Error - [lint] Unexpected STDERR output from ESLint:
Oops! Something went wrong! :(
ESLint: 8.7.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "C:/projet/new2".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install @typescript-eslint/eslint-plugin@latest --save-dev
The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in ".eslintrc.js » @microsoft/eslint-config-spfx/lib/profiles/react » ./default".
If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

Error - [lint]
[11:39:53] Project new-2 version:0.0.1
[11:39:53] Build tools version:3.17.20
[11:39:53] Node version:v16.13.0
[11:39:53] Total duration:18 s
[11:39:53] Task errors:2

### Steps to reproduce

1. Created a new application webpart react spfx 1.17.2
2. run gulp build
3.And eslint error is displayed

### Expected behavior

no error with eslint  when i created the projet

**Comment by AJIXuMuK** [comment]
@lreome - unfortunately I can't repro the issue.
Could you please try scaffolding a new fresh solution?
If the error persists - could you please share the scaffolded solution with me?

Thanks!

**Comment by ejazhussain** [comment]
I am getting the same issue. I have created a new SPFx project

SPFx version: 1.17.3
Node JS version: 16.0.3

## Error message: 

> Error - [lint] Unexpected STDERR output from ESLint:
Oops! Something went wrong! :(
ESLint: 8.7.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "C:\GitHub\spfx-solutions\spfx-dev-webparts\oc-tinymce-plugin".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install @typescript-eslint/eslint-plugin@latest --save-dev
The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in ".eslintrc.js » @microsoft/eslint-config-spfx/lib/profiles/react » ./default".
If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

**Comment by oppie85** [comment]
I was getting a similar error (also something involving eslint) using the 1.16.1 generator and after updating the yeoman generator to the newest version and scaffolding a project I'm getting the same errors as the other people in this thread.

I did get it to build succesfully again by manually installing the following packages:

npm install @typescript-eslint/eslint-plugin@latest --save-dev
npm install @rushstack/eslint-plugin@latest --save-dev
npm install @rushstack/eslint-plugin-security@latest --save-dev
npm install eslint-plugin-promise@latest --save-dev

Hopefully this helps to narrow down the issue or others to get their projects to work again

**Comment by lreome** [comment]
> @lreome - unfortunately I can't repro the issue. Could you please try scaffolding a new fresh solution? If the error persists - could you please share the scaffolded solution with me?
> 
> Thanks!

Hello,
the error persistst.
i share the projet witch you:
https://github.com/lreome/ProjetSpfx16.13.0.git

Thanks for you help

**Comment by lreome** [comment]
> > @lreome - unfortunately I can't repro the issue. Could you please try scaffolding a new fresh solution? If the error persists - could you please share the scaffolded solution with me?
> > Thanks!
> 
> Hello, the error persistst. i share the projet witch you: https://github.com/lreome/ProjetSpfx16.13.0.git
> 
> Thanks for you help

@AJIXuMuK

**Comment by AJIXuMuK** [comment]
@lreome - I can repro it on your test solution.
And that's weird - seems like `package-lock.json` doesn't have info for the eslint plugin as it should.
Few things that worked for me even with your solution:
- run `npm dedupe`
- manually delete `node_modules` and `package-lock.json` and run `npm i` again.

Please, let me know if that helps.

**Comment by lreome** [comment]
> @lreome - I can repro it on your test solution. And that's weird - seems like `package-lock.json` doesn't have info for the eslint plugin as it should. Few things that worked for me even with your solution:
> 
> * run `npm dedupe`
> * manually delete `node_modules` and `package-lock.json` and run `npm i` again.
> 
> Please, let me know if that helps.

Hello @AJIXuMuK ,

TThank you for your investigation.
the solution does not work I have run the command run npm dedupe and  manually delete node_modules and package-lock.json and run npm i again, i have same error.

====================== 1st solution  =========================
When i use the solutionfor @oppie85 install :
npm install @typescript-eslint/eslint-plugin@latest --save-dev
npm install @rushstack/eslint-plugin@latest --save-dev
npm install @rushstack/eslint-plugin-security@latest --save-dev
npm install eslint-plugin-promise@latest --save-dev

My solution run gulp build and  i not have no erro.

====================== 2 nd solution  =========================

I setup a new environnement wtich: Node.js version:16.13.2, my project is working fine.

configuration: 
- Node.js version:16.13.2
- @microsoft/generator-sharepoint@1.17.3
- npm@8.1.2
-  gulp@4.0.2
-  yo@4.3.1

Thanks for you help

**Comment by AJIXuMuK** [comment]
@lreome _maybe_ it's some internal problem of npm with the specific version or something.
Happy you're unblocked.

**Comment by lreome** [comment]
> @lreome _maybe_ it's some internal problem of npm with the specific version or something. Happy you're unblocked.

@AJIXuMuK  Thank :) !
