### ISSUE TITLE
Text colour not changing when PropertyPaneChoiceGroup options are disabled

### ISSUE THREAD

**Issue by fatwreck** [SharePoint/sp-dev-docs#9009]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Chrome 113.0.5672.92 (Official Build) (arm64)
- SPFx version : 1.16.1
- Node.js version : 16.18.0

### Describe the bug / error

The disabled state of an options group works fine but the option label text remains its original darker colour.

### Steps to reproduce

1. In a `PropertyPane.tsx` file, create a `PropertyPaneChoiceGroup` with a couple options
2. Add an icon and text property to the options within your options array of objects
3. Also, add a `disabled` property to each option object.
4. For example, if you make a `PropertyPaneToggle` like `PropertyPaneToggle(getPropertyName('testDisableToggle')`
5. Then in your `PropertyPaneChoiceGroup` you can make the disabled property `disabled: getProperty('testDisableToggle')`
6. By toggling your toggle, you'll enable and disable the choice group of options. They'll grey out, but their text will stay its original default dark colour.

### Expected behavior

For the option's label text to have a disabled-like state of reduced contrast.

**Comment by AJIXuMuK** [comment]
@fatwreck - do you have any theme customizations on the site you're testing?
I can't repro the issue on my end.
Enabled:
![image](https://github.com/SharePoint/sp-dev-docs/assets/17036219/c41bd04f-4054-437d-b128-92b7c26083fa)
Disabled:
![image](https://github.com/SharePoint/sp-dev-docs/assets/17036219/d2437dde-8eaf-4c0a-a019-a789e82b5864)

**Comment by fatwreck** [comment]
@AJIXuMuK Thanks for taking a look at it. 

I do have a theme enabled. Looking at the styling source, it looked like it was coming from Out of the box SP, but I may need to dig in further if you're unable to reproduce.

Thanks
