### ISSUE TITLE
Is it possible to use Office UI Fabric Icons for Command Set Extensions?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#901]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
Is it possible to use Office UI Fabric Icons or other font icons for Command Set Extensions?
If no - do you plan to add such possibility?

**Comment by mcmynn83** [comment]
Thanks for the feedback.  It is not currently possible to use Office UI Fabric Icons or other fonts for Command Set Extensions.  We are currently exploring possibilities around this area but do not have concrete plans at this time.
