### ISSUE TITLE
Placeholder {tenantDomain} is not replaced with SPFX_SERVE_TENANT_DOMAIN

### ISSUE THREAD

**Issue by DenisChimbor** [SharePoint/sp-dev-docs#9010]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.17.3
- Node.js version 16.20.0

### Describe the bug / error

When I run `gulp serve` the placeholder {tenantDomain} in serve.json is not replaced with SPFX_SERVE_TENANT_DOMAIN environment variable.

If I correctly understood the issue happens because placeholder case-sensitive.

In the file `SpfxServeTask.js` in the method `_getPlaceHolderDomainName` expression `placeHolderDomainName.includes(TENANT_DOMAIN_PLACEHOLDER)` retruns false because

 - `placeHolderDomainName` is https://**{tenantdomain}**/SitePages/myPage.aspx?...
 - but `TENANT_DOMAIN_PLACEHOLDER` is **{tenantDomain}** (different case).
  
 Placeholder is changed  from **{tenantDomain}** to **{tenantdomain}** in the method `_convertServeConfigurationToPageUrl`.

### Steps to reproduce

1. `$env:SPFX_SERVE_TENANT_DOMAIN = "mydomain.sharepoint.com"`
2. `gulp serve`

### Expected behavior

Placeholder {tenantDomain} is replaced with SPFX_SERVE_TENANT_DOMAIN environment variable value.

**Comment by AJIXuMuK** [comment]
@DenisChimbor - thanks for reporting the issue.
I've just tested it. (using 1.17.4) and I can't repro the issue: the default scaffolded solution is working as expected, the `{tenantDomain}` is replaced with the variable.

Do you have any extra customizations that can lead to such behavior?

**Comment by DenisChimbor** [comment]
@AJIXuMuK, thank you for the feedback!  I don't have any customizations. But I use spfx 1.17.3. I will try with 1.17.4.

**Comment by DenisChimbor** [comment]
@AJIXuMuK, I downloaded latest generator `npm install @microsoft/generator-sharepoint@latest --global` and just created a new project (v 1.17.4). Sorry, forgot to mention that I use application customizer. I still have the same issue.

After executing `gulp serve` it opens me _https://%7Btenantdomain%7D/SitePages/myPage.aspx?..._ Note, that  _tenantdomain_ contains lowercase letter "d".

I have the following gulp version:
```
gulp --version
CLI version: 2.3.0
Local version: 4.0.2
```

**Comment by AJIXuMuK** [comment]
@DenisChimbor - thanks for extra details!
I can repro it for Application Customizer and we will be working on a fix!

**Comment by AJIXuMuK** [comment]
fixed in 1.18.0-beta.3
