### ISSUE TITLE
Which is the right version?

### ISSUE THREAD

**Issue by jcoolsen** [SharePoint/sp-dev-docs#9023]
Just under the heading "Install Node.js" you write: "Install the most recent LTS version of [Node.js](https://www.nodejs.org/) v16." This is currently v16.20.0.

Then, a bit further down it says that the SharePoint Framework v1.17.1 supports Node.js v16 LTS (v16.13.x - v16.18.x, aka: Gallium).

So, would it be OK to use v16.20.0 or should we use v16.18.x?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by ElPrudi** [comment]
I use 16.20.0 and haven't encountered any problems. When you go to the package `@microsoft/sp-build-web` (the tool to build the projects via webpack) and it's `package.json` file, you can see that it supports:
```json
"engines": {
    "node": ">=12.13.0 < 13.0.0 || >=14.15.0 < 15.0.0 || >=16.13.0 < 17.0.0"
}
```

Same thing goes for any other sp build package.

**Comment by jcoolsen** [comment]
If it goes for all the spfx packages, then the latter text could perhaps be updated to 
  SharePoint Framework v1.17.1 supports Node.js v16 LTS (v16.13.x - v16.x).

**Comment by ElPrudi** [comment]
It does say this. Right above the red caution box.
"""
The SharePoint Framework v1.17.1 is supported on the following Node.js versions:

    Node.js v16 LTS (v16.13.x - v16.18.x, aka: Gallium)
"""

But it's still weird to me that it still says 1.17.1, considering 1.17.3 is the newest version.

**Comment by andrewconnell** [comment]
Fixing the doc... we shouldn't have that level of detail in our docs... this adds unnecessary burden to maintain the docs when that information is detailed on the Node.js site. Any version of Node v16 LTS will work. Refer to the Node.js site for what's covered in the v16 LTS range.

To directly answer your question, yes, v16.20.* is supported.
