### ISSUE TITLE
for me at least       {"Key": "export", "hide": "true"       }, is not hiding the Export button in the command bar at all.

### ISSUE THREAD

**Issue by VincentVanAgogo** [SharePoint/sp-dev-docs#9038]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Version Independent ID: 22dffaf9-de6c-5ec3-bd61-23b995c256ce
* Content: [Command bar customization syntax reference](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting)
* Content Source: [docs/declarative-customization/view-commandbar-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/view-commandbar-formatting.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by jakewarrington** [comment]
Hi @VincentVanAgogo

Your "Key" should be entirely lowercase.

Would you try with the following instead?

`{
  "key": "export",
  "hide": "true"
}`

This should fix your issue.
