### ISSUE TITLE
SharePoint Online - Provisioning Pages using Site Templates and Site Scripts

### ISSUE THREAD

**Issue by akshataggrwal** [SharePoint/sp-dev-docs#9040]
### Discussed in https://github.com/SharePoint/sp-dev-docs/discussions/9032

<div type='discussions-op-text'>

<sup>Originally posted by **akshataggrwal** June 22, 2023</sup>
I want to create pages in the "Site Pages" library within a SharePoint Online site using site templates. After reviewing the official documentation available at (https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema), I have been unable to locate any documented actions specifically related to creating pages in a "Site Pages" library.
<br>
However, I have observed that when applying the out-of-the-box site templates provided by Microsoft(reference image below), certain pages are automatically provisioned in the "Site Pages" library, and one of these pages is set as the site's home page.
 
<br />
I would like to understand potential approaches to achieve this and/or would like to understand how it is handled in OOB templates by Microsoft.
 </div>

**Comment by VesaJuvonen** [comment]
This is currently not unfortunately supported. Template team is looking into this in the future, but there's no ETA currently.

**Comment by brianpmccullough** [comment]
Per @VesaJuvonen via another channel:

Using code which is unfortunately not currently supported for customers and partners. There's work being done to support this in the future, but there's currently no ETA which can be shared.

As we release the Pages Graph API in production, we are one step closer for this.

https://twitter.com/vesajuvonen/status/1674390479138324480?t=d4uwroFcIoPhSM_dalJK3Q&s=03

**Comment by VesaJuvonen** [comment]
thx @brianpmccullough for sharing the message here. It's indeed an unfortunate situation, but there's some light on the tunnel - but not sure if that's train or ending.
