### ISSUE TITLE
After following tutorial "Build your first SharePoint client-side web part", but no "HelloWorld" web parts display in my SPO

### ISSUE THREAD

**Issue by dung-ngo** [SharePoint/sp-dev-docs#9044]
### What type of issue is this?

Documentation issue / typo

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Issue description

After following tutorial "Build your first SharePoint client-side web part", but no "HelloWorld" web parts display in my SPO
Please help me with this issue!

**Comment by ElPrudi** [comment]
1. `gulp serve`
2.  wait until the task "reload" is done
3. If nothing is shown: Open the web console > sources > find a source that is called "webpack"
4. If you can't find this source, you most likely have the wrong react version installed. Check the [compatibility matrix](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility) for the right version.

**Comment by VesaJuvonen** [comment]
Can you provide details on which versions you have installed on your machine. Template has placeholders for SPFx version, node version, npm version etc. We cannot determine the issue without these.

One common issue is also missing registration of the developer cert which is covered in the tutorials, so would double check that step.

**Comment by dung-ngo** [comment]
I've just figured out that I was using Brave browser with "Shields Up" -- it was blocking something that was required for this to work correctly. I tested on Microsoft Edge, and it works well.
I think this is not a big issue, but still want to leave a solution here in case someone need this.
Thanks @VesaJuvonen for your support!
