### ISSUE TITLE
I'm having problems understanding how to get rid of the eslint rule @microsoft/spfx/pair-react-dom-render-unmount

### ISSUE THREAD

**Issue by trillian74** [SharePoint/sp-dev-docs#9048]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- latest

### Issue description

I am getting three warnings about this rule and that i should do this to avoid memory leaks
`243:6  warning  Pair the render and unmount calls to avoid memory leaks  @microsoft/spfx/pair-react-dom-render-unmount
  257:4  warning  Pair the render and unmount calls to avoid memory leaks  @microsoft/spfx/pair-react-dom-render-unmount
  267:3  warning  Pair the render and unmount calls to avoid memory leaks  @microsoft/spfx/pair-react-dom-render-unmount`

the ondispose
`	protected onDispose(): void {
		ReactDom.unmountComponentAtNode(this.domElement);
	}`

and the render
`
public render(): void {
		if (
			this.displayMode === DisplayMode.Read &&
			this.properties.contractLibrary &&
			this.properties.connectedContractLibrary &&
			this.properties.ODCompany &&
			this.properties.filePickerResult &&
			this.properties.planId &&
			this.properties.groupId &&
			this.properties.people &&
			this.properties.people.length > 0 &&
			this.properties.storageId
		) {
			try {
				const api = new ContractApi(this.context.serviceScope, this.context, this.properties.contractLibrary, this.properties.connectedContractLibrary, this.properties.filePickerResult.fileAbsoluteUrl);
				api.configureApi(this.properties.environment).then(() => {
					const element: React.ReactElement<IContractStarterProps> = React.createElement(ContractStarter, {
						webpartProps: this.properties,
						api: api,
						context: this.context,
						serviceScope: this.context.serviceScope,
						admin: this.properties.people,
					});

					const elementRoot: React.ReactElement<RecoilRootProps> = React.createElement(RecoilRoot, {}, element);

					ReactDom.render(elementRoot, this.domElement);
				}).catch((error) => { console.error("configureApi", error); })
			} catch (error) {
				console.error(error);
			}
		} else {
			const placeholderElement: React.ReactElement<IPlaceholderProps> = React.createElement(Placeholder, {
				iconName: "Edit",
				iconText: "Configure your web part",
				description: "Please configure the web part.",
				buttonLabel: "Configure",
				onConfigure: this._onConfigure,
			});

			ReactDom.render(placeholderElement, this.domElement);
		}
	}`

How should i implement the mount and unmounting to get rid of these warnings?

**Comment by AJIXuMuK** [comment]
@trillian74 - if you want to actually address the warning (not silence) you could change your code to set element variable in `if...else` and then call `render` outside.
Something like:
```ts
let element: React.ReactElement;
if (someting) {
  element = React.createElement(...);
} else {
 element = React.createElement(...);
}
ReactDom.render
```

**Comment by trillian74** [comment]
I did that and i unmounted if the other was loaded 👍
