### ISSUE TITLE
Field customizers don't re-render after sorting or filtering

### ISSUE THREAD

**Issue by JLRishe** [SharePoint/sp-dev-docs#905]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After filtering or sorting a list or library, fields with field customizers should render the customized content.

#### Observed Behavior
After sorting on any field (customized or otherwise), columns using field customizers are blank.

#### Steps to Reproduce
1. Add a field customizer to any list 
2. Sort on any column

#### Observations
The browser console re-outputs"Add Spfx column adapter for ..." and "fieldCustomizers loaded" the first time I sort the view.
If I sort _again_ after that, these lines are not output and I get mixed results with the rendering. Sometimes the customized fields do render. Sometimes they only render in certain rows and not others.

**Comment by AJIXuMuK** [comment]
The same if you chage the view from drop down in right part of Command Bar

**Comment by VesaJuvonen** [comment]
Issue acknowledged and we are looking into getting this fixed asap. Thx for reporting.

**Comment by ahackettms** [comment]
This issue was just fixed and should reach customer by Oct 24th.

**Comment by iamrati** [comment]
@VesaJuvonen @ahackettms - I am facing issues with Sorting and Filtering other columns and my Field Customizer, sorting and filtering sometimes gives mixed results for rendering and sometimes doesn't renders at all.

**Comment by AJIXuMuK** [comment]
Can't repro.

**Comment by patmill** [comment]
This issue is quite old, and checking with the most recent build it looks like it is fixed.  IF that is not the case, let us know.  Thanks.
