### ISSUE TITLE
Error when trying to update the outdated NPM - npm ERR! 404 Not Found - GET https://registry.npmjs.org/eslint-config-spfx - Not found

### ISSUE THREAD

**Issue by berryst** [SharePoint/sp-dev-docs#9054]
I encountered error when trying to update the NPM 
_PS C:\Etc\SPFX\learning\LinkFormatterExtension> npm install eslint-config-spfx@1.17.4 --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/eslint-config-spfx - Not found
npm ERR! 404
npm ERR! 404  'eslint-config-spfx@1.17.4' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url._

I had to run the following command to overcome the error. 
npm config set registry http://registry.npmjs.org/

You might want to include the information on the page in case other people come across this issue.

Thank you!
Berry
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c43fab8f-85bf-e577-317b-a71dada5c865
* Version Independent ID: 4d041f90-2cc7-ed20-c007-d2a36f9c7c7b
* Content: [Update SharePoint Framework packages](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/update-latest-packages)
* Content Source: [docs/spfx/toolchain/update-latest-packages.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/update-latest-packages.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@berryst - I believe it should be `@microsoft/eslint-config-spfx`: https://www.npmjs.com/package/@microsoft/eslint-config-spfx
