### ISSUE TITLE
Can I get non localized numbers from RenderListDataAsStream?

### ISSUE THREAD

**Issue by gabbsmo** [SharePoint/sp-dev-docs#9058]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online
SharePoint Subscription Edition
SharePoint 2019

### Issue description

Date values will be localized when returned from RenderListDataAsStream (i.e. 1 000 for Swedish, and 1,000 for English US). I know that I can opt out of localization for dates using the datesInUTC parameter.

Is the something similar for numbers?

Localized dates makes parsing them to numbers very hard since return format can vary depending on browser settings. Ideally they would be JSON numbers.

**Comment by smolattack** [comment]
Number columns should have equivalent parsable floats versions along with the localized version. Just add a "." at the end of the field name. So if you have `myNumber` column in SP, `row.myNumber` will give you the localized number and `row["myNumber."]` should give you a string representation of a float.

**Comment by gabbsmo** [comment]
Thanks that works greata
