### ISSUE TITLE
Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.2. Store had [2.2.1]. Service worker version: (none),DurableN1=true

### ISSUE THREAD

**Issue by PetrHer** [SharePoint/sp-dev-docs#9059]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.16.1
- Node.js version 16.19.0

`  "dependencies": {
    "@microsoft/sp-core-library": "^1.16.1",
    "@microsoft/sp-lodash-subset": "1.16.1",
    "@microsoft/sp-office-ui-fabric-core": "1.16.1",
    "@microsoft/sp-property-pane": "1.16.1",
    "@microsoft/sp-webpart-base": "1.16.1",
    "@pnp/spfx-controls-react": "3.14.0",
    "@syncfusion/ej2-react-grids": "^19.3.44",
    "office-ui-fabric-react": "^7.199.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.16.1",
    "@microsoft/eslint-plugin-spfx": "1.16.1",
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@microsoft/sp-build-web": "1.16.1",
    "@microsoft/sp-module-interfaces": "1.16.1",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "spfx-fast-serve-helpers": "~1.16.1",
    "typescript": "4.5.5"
  }`

### Describe the bug / error

Started new SPFx 1.16.1 project.

Facing error (Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.2. Store had [2.2.1]. Service worker version: (none),DurableN1=true) when trying to initialize graph client V3.

`const client: MSGraphClientV3 = await this.webPartContext.msGraphClientFactory.getClient('3');`

### Steps to reproduce

I just tried to initialize client in new project

### Expected behavior

msGraphClientFactory should initialize the graph client.

**Comment by zaiby** [comment]
Have same issue with:

return props.ctx.msGraphClientFactory.getClientWithMiddleware("3", {
    middleware,
  });
  
  Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.3. Store had [3.0.2]. Service worker version: odsp-web-prod_2023-08-04.008,DurableN1=true

CALL STACK:
Error: Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.3. Store had [3.0.2]. Service worker version: odsp-web-prod_2023-08-04.008,DurableN1=true
    at e.getManifest (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:254245)
    at e.requestManifest (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:256030)
    at e._configureComponentResource (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:267717)
    at e.configLoadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:265948)
    at e._loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:270601)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_bd09bc5a339de3a30bb76aa5be53782a.js:78:271689

**Comment by AJIXuMuK** [comment]
@PetrHer @zaiby - SPFx currently supports MSGraph v3.0.2, not 3.0.3.
That's why you're seeing this issue.

You can always go to the generated `.yo-rc.json` file to check supported versions for MSGraph and MS Teams:
```json
 "sdksVersions": {
      "@microsoft/microsoft-graph-client": "3.0.2",
      "@microsoft/teams-js": "2.9.1"
    },
```

**Comment by zaiby** [comment]
> @PetrHer @zaiby - SPFx currently supports MSGraph v3.0.2, not 3.0.3. That's why you're seeing this issue.
> 
> You can always go to the generated `.yo-rc.json` file to check supported versions for MSGraph and MS Teams:
> 
> ```json
>  "sdksVersions": {
>       "@microsoft/microsoft-graph-client": "3.0.2",
>       "@microsoft/teams-js": "2.9.1"
>     },
> ```

Thanks for info :)
