### ISSUE TITLE
Loading a pages /webParts or /canvasLayout fails (beta)

### ISSUE THREAD

**Issue by wdamien** [SharePoint/sp-dev-docs#9067]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Chrome version: 114.0.5735.198 (Official Build) (arm64) 

### Describe the bug / error

When using the beta REST api to try and load the `webparts` for a list, a 404 error is returned with this message:

```
{
    "error": {
        "code": "itemNotFound",
        "message": "The property 'webParts' is null or does not exist",
        "innerError": {
            "date": "2023-07-10T17:28:46",
            "request-id": "68ec8a2a-4866-4dc3-a4dd-df6e210fa459",
            "client-request-id": "68ec8a2a-4866-4dc3-a4dd-df6e210fa459"
        }
    }
}
```

From our error logs it look like this started happening on July 9 when the previous `?expand=webParts` stopped working.

I'm following the docs found here: https://learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&tabs=http and both the `/webparts` and `/canvasLayout` endpoints don't load data and return the same 404 error.

### Steps to reproduce

1. Make a request to load the webparts for a given SP page: `GET: https://graph.microsoft.com/beta/sites/<site_id>/pages/<pageId>/webparts`
2. The provided 404 error is returned. 

### Expected behavior

The list of webParts is returned.

**Comment by divyachapan** [comment]
Apologies for the interruption. We are in the middle of an update to Pages Graph API. Some of the code roll out happened faster than documentation update. Please see https://github.com/SharePoint/sp-dev-docs/issues/9075

**Comment by wdamien** [comment]
Closing, since with the latest [documentation](https://learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta) update I was able to get webParts loading.
