### ISSUE TITLE
403 Forbidden -https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews

### ISSUE THREAD

**Issue by HarminderSethi** [SharePoint/sp-dev-docs#9068]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - 114.0.5735.199
- SPFx version - 1.16.1 & 1.17.3
- Node.js version 
- etc

### Describe the bug / error

While making call to https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews getting error 403 Forbidden. The required permissions are already added and approved as admin. This was working fine till last week and suddenly throwing forbidden error. It seems the bearer token is not valid. tried the same on graph explorer with same account and it is working. 
 ` "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "ServiceHealth.Read.All"
      }
    ],`

### Steps to reproduce

1. create SPFx webpart
2. add `    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "ServiceHealth.Read.All"
      }
    ],` in package-solution.json
3. make call to https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews using msGraphClientFactory (version3)

### Expected behavior

It should return the status 200 OK response code and a collection of [serviceHealth](https://learn.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0) objects in the response body

**Comment by AJIXuMuK** [comment]
@HarminderSethi - sorry for the delay.
Have you tried testing the solution on another tenant (for example, [Dev tenant](https://developer.microsoft.com/en-us/microsoft-365/dev-program)).

**Comment by HarminderSethi** [comment]
@AJIXuMuK yes on couple of dev tenants. Actually there is one SPFx [sample ](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-m365-services-health) which I published which is consuming https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews and it was working fine and suddenly I and other users started getting this 403 Forbidden error. 
I have also checked the permissions in the azure portal and all looks good.

**Comment by TysonP2** [comment]
I am facing the same issue. Nothing else has changed, all permissions are verified. Something in this Graph endpoint changed. @HarminderSethi, did you find any solution?

**Comment by TysonP2** [comment]
Extra role is now required on the delegated account. 

https://monitoringguys.com/2023/07/28/graph-api-healthoverviews-403-forbidden/

**Comment by HarminderSethi** [comment]
@TysonP2 my point if it is required, the documentation should be updated accodingly. and if it is true then I think there is no use of exposing the endpoints because no organization will give this role to all the users.

**Comment by AJIXuMuK** [comment]
@HarminderSethi OK, so it seems like (and @TysonP2 has already pointed it out) you need extra role for the user.
I totally agree it should be listed in the docs (or maybe it's a regression).
To figure it out - please use MS Graph support channels: https://developer.microsoft.com/en-us/graph/support
