### ISSUE TITLE
Theme provider does not work on Application customizer for custom Header/footer

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#9070]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : All
- SPFx version : 1.17.4
- Node.js version : 16.13
- etc

### Describe the bug / error

The  this.context.serviceScope.consume(ThemeProvider.serviceKey)  crash Application Customizer (custom Header or Footer)

### Steps to reproduce

1. Create Application customizer solution for custom header/footer
2. Instanciate this.context.serviceScope.consume(ThemeProvider.serviceKey)
3. See console error

![image](https://github.com/SharePoint/sp-dev-docs/assets/582733/1d747d3c-c31b-4f4c-91d6-9863e4454e3a)

### Expected behavior

Cleaned exemple of code

```typescript
// React
import * as React from 'react';
import * as ReactDOM from 'react-dom';

// SPFx
import {
  BaseApplicationCustomizer,
  PlaceholderContent,
  PlaceholderName
} from '@microsoft/sp-application-base';
import { override } from '@microsoft/decorators';
import { IReadonlyTheme, ThemeChangedEventArgs, ThemeProvider } from '@microsoft/sp-component-base';

//Component
import Header from '@src/extensions/Header/components/Header ';

export default class CnpFlashInfosAppApplicationCustomizer
  extends BaseApplicationCustomizer<{}> {

  private _topPlaceholder: PlaceholderContent | undefined;
  private _themeProvider: ThemeProvider;
  private _themeVariant: IReadonlyTheme;

  @override
  public async onInit(): Promise<void> {

    // Theme  
    this._themeProvider = this.context.serviceScope.consume(ThemeProvider.serviceKey); // Crash application customizer
    console.log(this._themeProvider.tryGetTheme());
    
    this._themeVariant = this._themeProvider.tryGetTheme();
    
    this._themeProvider.themeChangedEvent.add(
      this,
      this._handleThemeChangedEvent
    );     

    this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);

    return Promise.resolve();
  }

  private _renderPlaceHolders(): void {

    if (!this._topPlaceholder) {
      this._topPlaceholder = this.context.placeholderProvider.tryCreateContent(
        PlaceholderName.Top,
        { onDispose: this._onDispose }
      );
    }
    if (!this._topPlaceholder) {
      console.error('The expected placeholder (Top) was not found.');
      return;
    }

    if (this._topPlaceholder.domElement) {
      const elem: React.ReactElement<any> = React.createElement(Header);
      ReactDOM.render(elem, this._topPlaceholder.domElement);
    }

  }

  private _onDispose(): void {
    if (this._topPlaceholder && this._topPlaceholder.domElement) {
      ReactDOM.unmountComponentAtNode(this._topPlaceholder.domElement);
    }
  }

  private _handleThemeChangedEvent(args: ThemeChangedEventArgs): void {
    this._themeVariant = args.theme;
  }
}

```

it is important to be able to recover the theme to be able to use Fluent UI (cssInJs, themeProvider ...) correctly.

the (window as any).__themeState__.theme and Fluent UI CreateTheme is not a clean method

**Comment by AJIXuMuK** [comment]
@PooLP  thank you for reporting this one and sorry for the delay.
What is the error you're seeing when debugging the customizer?

I would recommend wrapping the call to `serviceScope.consume` with `serviceScope.whenFinished`.

**Comment by PooLP** [comment]
Hi @AJIXuMuK,
I have tested the same code now, and it works. I do not know why.
I close issue. Thanks.
