### ISSUE TITLE
https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}?expand=webParts gives error: "Could not find a property named 'webParts' on type 'oneDrive.baseSitePage'."

### ISSUE THREAD

**Issue by vikassharmaatl** [SharePoint/sp-dev-docs#9072]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

https://graph.microsoft.com/beta/sites/{site-id}/pages/{page-id}?expand=webParts gives error: "Could not find a property named 'webParts' on type 'oneDrive.baseSitePage'."

Worked till a day ago.

### Steps to reproduce

1. Navigate to Graph explorer
2. Enter the URL and fill in the params expected
3. Response gives the above error.

### Expected behavior

Webparts are returned.

**Comment by harperaaron** [comment]
### A high level description of how this was resolved:

**Cause:** The "expand=webparts" and "getPositionOfWebPart" parameters for the /pages/ endpoint were deprecated/modified. 
 
**The Fix:** Two new methods were discovered and used to replace the deprecated functionality. 

- …/pages/{pageID}/microsoft.graph.sitePage/webparts
    - [Get webPart - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta)

- …{pageID}/microsoft.graph.sitePage/webParts/{webpartID}/getPositionOfWebPart
    - [webPart: getPosition - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta)
