### ISSUE TITLE
Lookup column items will not load in form. This is a new issue in my list that has been bug-free for 2+ years

### ISSUE THREAD

**Issue by visually-basic** [SharePoint/sp-dev-docs#9077]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

NA

### Describe the bug / error

A user just reported - and I get the same - that when they attempt to complete a lookup field in one list, the items are not displayed and, therefore, are unable to choose a lookup item. This happens only in the form (in Edit or Edit All) it does not happen in grid view.

All other lookup columns within this list are not affected by this issue, even those looking up to the same list.

Screenshot of issue:
![image](https://github.com/SharePoint/sp-dev-docs/assets/61693028/5cf71f20-09e6-456e-89fb-1b0f15ffaae3)

Screenshot of lookup field without issue but looking at the same list:
![image](https://github.com/SharePoint/sp-dev-docs/assets/61693028/59d45974-dd0d-416d-933c-33f09c88e2a5)

### Steps to reproduce

1. Open sharepoint list
2. Open edit form for an item
3. Click on lookup field in form

### Expected behavior

I expect to see a dropdown box of items from the source list that I can search by typing into the lookup field. This does not happen.

Screenshot of expected behaviour from different lookup field but same lookup list:
![image](https://github.com/SharePoint/sp-dev-docs/assets/61693028/6283cf22-d659-4a7c-a0e4-fb06be718454)

**Comment by AJIXuMuK** [comment]
@visually-basic - this issues list is for dev-related issues.
For the product issues the customer should submit a Support ticket.
