### ISSUE TITLE
How form customizer  app register with the SharePoint site content type?

### ISSUE THREAD

**Issue by SudhirMuvva** [SharePoint/sp-dev-docs#9078]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version =  1.15.1
- Node.js version - v16.20.0
- etc

### Issue description

we have developed a form customizer  app in spfx. We want to register with the SharePoint site content type.
How can I associate a form customizer extension with a content type?

Power shell script : Connect-PnPOnline -Url $siteURL -Interactive
this line is giving error while run the script
Is there a method to do it through power shell if we don't have global/tenant admin access?
please suggest the approach to do this SharePoint online.

My Script:
[script.txt](https://github.com/SharePoint/sp-dev-docs/files/12066716/script.txt)

**Comment by AJIXuMuK** [comment]
@SudhirMuvva - as I mentioned, you need to submit issue to the PnP PowerShell repo if you're experiencing issues with the cmdlets.

**Comment by SudhirMuvva** [comment]
Please let me know the steps how to raise a ticket on PNP powershell?
