### ISSUE TITLE
Generated outline icon in SPFx solution doesn't satisfy Teams dev portal requirement

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [SharePoint/sp-dev-docs#9079]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version  Chrome Version 114.0.5735.199
- SPFx version  v1.17.4
- Node.js version  v16.17.0
- etc

### Describe the bug / error

Validation failed when importing app package using outline icon in Yeoman scaffolded SPFx solution.
![image](https://github.com/SharePoint/sp-dev-docs/assets/73154171/abb3a9ea-2134-4d35-a17a-eedeac6d2511)

### Steps to reproduce

1. Scaffold a SPFx solution with Yeoman generator
2. Add a Teams manifest file under teams folder
3.  Generate Teams app package with the manifest and color+outline icons scaffolded from Yeoman
4. Upload the Teams app package to Teams dev portal
5. The following error occurs indicating outline icon is not transparent
![image](https://github.com/SharePoint/sp-dev-docs/assets/73154171/abb3a9ea-2134-4d35-a17a-eedeac6d2511)

### Expected behavior

Upload Teams app package with outline icon scaffolded from Yeoman should succeed.

**Comment by AJIXuMuK** [comment]
fixed in 1.18.0-beta.3
