### ISSUE TITLE
RenderListDataAsStream & RenderExtendedListFormData suddenly failing due to Serialization Error

### ISSUE THREAD

**Issue by MortenGuldbaek** [SharePoint/sp-dev-docs#9082]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Version 114.0.5735.199 (Official Build) (64-bit)
- SPFx version 1.12.1
- Node.js version 14.15.5

### Describe the bug / error

We are using 'RenderListDataAsStream' and 'RenderExtendedListFormData' from SharePoint REST API for our extensions, for allowing users to edit and create list items.

Starting last week we have encountered that these endpoints return the following error:
```
{
    "error": {
        "code": "-1, System.InvalidOperationException",
        "message": {
            "lang": "en-US",
            "value": "Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property."
        }
    }
}
```

This happens for lists where we have 7 - 9 lookup fields configured so we should be well below the threshold for lookups (12 for SharePoint Online).

Bear in mind that these lists settings have not been changed for at least a year.

It is happening in three different tenants, but could be more due to holiday inactivity.

The following settings give us the error:

- A basic 'RenderExtendedListFormData' call, irregardless of options
- 'RenderListDataAsStream' with the following options: ClientFormSchema = 64

We of course validated our findings by comparing the built-in SharePoint edit form (Modern Experience) which also fails:
<img width="601" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/6163736/6e850231-9404-46e2-8603-4505d6491125">

### Steps to reproduce

1. Perform a REST call for the following endpoints on a list with 7-9 lookup fields:
A basic 'RenderExtendedListFormData' call, irregardless of options
A 'RenderListDataAsStream' with the following options: ClientFormSchema = 64

### Expected behavior

We expect the endpoints to return data as they did before they started failing end of last week

**Comment by AJIXuMuK** [comment]
@MortenGuldbaek - could you please specify where you're performing the REST request?
The screenshot doesn't look like SPFx application but it is marked as SPFx in the dev model.

**Comment by MortenGuldbaek** [comment]
Sure thing. 

The provided screenshot was just the built-in edit list item form in the modern experience, to show that it was not only our customizations that were failing.

We have a list view command set that enables editing list items in a React form where we have custom a validation flow.
This relies on 'RenderListDataAsStream', using the SPHttpClient from the SPFx list view context.

We got reports that this was failing late last week and could replicate on our own tenants this week.

Checking this morning I can see that our solution is now working as expected again, with no change from our side, but I'm still waiting for confirmation from our partners if they are experiencing the same.

**Comment by MortenGuldbaek** [comment]
We have confirmations from our partners that they do not encounter the bug anymore, so that's great.

Though I'm a bit hesitant on celebrating too early, not knowing what causes the issue.

@AJIXuMuK do you know what could have impacted the API?
