### ISSUE TITLE
SPFX Form Customizer - Is there a function to get the default rendering and just modify one field?

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-dev-docs#9086]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge 114.0.1823.82 (Official build) (64-bit)
- SPFx version: 1.17.4
- Node.js version: v14.19.3

### Issue description

Right now, I'm working on a SharePoint project with a challenging requirement. 

The project focusses on document management. There is one requirement to have a special field within the document library. This filed should become a Text-Input plus two numeric fields within the edit form. The list holds more than 20 other fields, that do not need to be modified.

AFAIK I cannot change the fields edit form with field customizers. That is why I'm looking into form customizers. Right now I'm wondering, if there is any default function available to render the other 20+ fields and just provide an "override" for the field in question. Is this possible or do I need to implement custom components for any other field as well?

**Comment by andikrueger** [comment]
I think a found a partial solution to my question in PNP dynamic forms. https://pnp.github.io/sp-dev-fx-controls-react/#getting-started

Now I need to figure out on how to change on field or disable on field to render a custom one.

**Comment by AJIXuMuK** [comment]
@andikrueger - there is no OOB function for that.
But yes - using PnP `DynamicForm` is a good solution. You can specify `fieldOverrides` property to provide your custom renderer for a specific field.
