### ISSUE TITLE
FieldCustomizer not working in 1.3.2

### ISSUE THREAD

**Issue by maliksahil** [SharePoint/sp-dev-docs#909]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
Using versions
 - generator-sharepoint 1.3.2
 - gulp 3.9.1
 - npm 4.6.1
 - yarn 1.1
 - yo 2.0.0

I create a simple project, accept all defaults, gulp serve --nobrowser, and I expect to see the field customizer to render. It doesn't seem to "kick in". 

I have recorded a video to repro the steps 
https://www.youtube.com/watch?v=xDb5W4qGGwM

#### Observed Behavior
I expected to see the percentage field update. But I see no changes.

#### Steps to Reproduce
I have recorded a video to repro the steps 
https://www.youtube.com/watch?v=xDb5W4qGGwM

**Comment by mpasarin** [comment]
Hi @maliksahil 
From the video I see that on the URL you treat the field name as "Percent", but in the column name is "Percentage". Could you double check whether you are using the same internal name?
If the string from the URL query parameter doesn't match with any column, this is the expected behavior.

**Comment by maliksahil** [comment]
That was it .. and I also had a bug in my JSON format. Working fine now in both classic and modern sites. Thanks for your help!
