### ISSUE TITLE
403 error despite being SP Collection Owner

### ISSUE THREAD

**Issue by uniproio** [SharePoint/sp-dev-docs#9090]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

**_When using the following script to look at existing folders and create a new one with 'todays date' and an incremental reference number I get a '403 error access not permitted' 
this script originates from a batch file which worked perfectly when SharePoint was accessed by users as a mapped drive.
Ideally once this script is working I would like to share it with select other users.
Thanks_**

Add-Type -Path "C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll"
Add-Type -Path "C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll"

Connect-SPOService -Url https://myCompanyName-admin.sharepoint.com 

# Site and authentication information
$siteUrl = "https://myCompanyName-admin.sharepoint.com"

# Create a new client context
$ctx = New-Object Microsoft.SharePoint.Client.ClientContext($siteUrl)

function Generate-Folder {
    $listName = "Shared Documents\IT Test"  # Replace with the name of your document library

    # Get the document library
    $list = $ctx.Web.Lists.GetByTitle($listName)
    $ctx.Load($list)

    # Generate folder name and increment
    $baseName = "Q" + (Get-Date).ToString("yyMMdd")
    $folderNum = 1
    $query = [Microsoft.SharePoint.Client.CamlQuery]::CreateAllItemsQuery()
    $items = $list.GetItems($query)
    $ctx.Load($items)
    $ctx.ExecuteQuery()

    if ($items.Count -gt 0) {
        $lastItem = $items | Sort-Object ID | Select-Object -Last 1
        $folderNum = [int]$lastItem["FileLeafRef"].Substring(1) + 1
    }

    $folderName = $baseName + ("{0:D3}" -f $folderNum)
    $folderDescription = Read-Host "Enter Project Description"

    # Create the folder
    $folderInfo = New-Object Microsoft.SharePoint.Client.FolderCreationInformation
    $folderInfo.Url = $folderName
    $folderInfo.UnderlyingObjectType = [Microsoft.SharePoint.Client.FileSystemObjectType]::Folder
    $folder = $list.RootFolder.Folders.Add($folderInfo)
    $folder.ListItemAllFields["Title"] = $folderDescription
    $folder.ListItemAllFields.Update()
    $ctx.ExecuteQuery()

    Write-Host "Folder created: $folderName - $folderDescription"
}

# Main menu loop
while ($true) {
    
    Write-Host "========== Q Number Generator =========="
    Write-Host "---------------------------------------"
    Write-Host "1. Generate Next Quote Folder"
    Write-Host "---------------------------------------"
    Write-Host "========== PRESS 'Q' TO QUIT =========="
    Write-Host ""

    $key = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown").Character

    if ($key -eq "1") {
        Generate-Folder
    }
    elseif ($key -eq "q" -or $key -eq "Q") {
        break
    }
    else {
        Write-Host "=========== INVALID INPUT ==========="
        Write-Host "---------------------------------------"
        Write-Host "Please select a number from the main menu [1] or select 'Q' to quit."
        Write-Host "---------------------------------------"
        Write-Host "====== PRESS ANY KEY TO CONTINUE ======"
        $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    }
}

Write-Host "============== THANK YOU =============="
Write-Host "---------------------------------------"
Write-Host "====== PRESS ANY KEY TO CONTINUE ======"

$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown").Character

**Comment by AJIXuMuK** [comment]
@uniproio - SharePoint Management Shell requires SharePoint Tenant Admin permissions as you are connecting to the Admin Center.

Consider looking into [PnP PowerShell](https://pnp.github.io/powershell/) or [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365/)

**Comment by uniproio** [comment]
Hi AJIXuMuK, 
I am the global administrator, and SharePoint Administrator, is the SharePoint Tenant Admin a separate role?  I cannot find it to add to my account, any help appreciated.
Thanks
