### ISSUE TITLE
How do you tie the selected list item to the command?

### ISSUE THREAD

**Issue by mkeysae2** [SharePoint/sp-dev-docs#9091]
This was a good overview, but it would have been good to show how to tie the selected list item back to the command.  For example, passing the list Item ID to the command to allow the developer to read or write data for the specific item.  Maybe I missed this.  Is this possible?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe70fcc7-45db-fa48-eb63-27c77d3efc8a
* Version Independent ID: faaa94f0-7660-d72c-401f-7ba76688b9ed
* Content: [Build your first ListView Command Set extension](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api)
* Content Source: [docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by AJIXuMuK** [comment]
@mkeysae2 in the default scaffolded code you have `_onListViewStateChanged` event:
```ts
private _onListViewStateChanged = (args: ListViewStateChangedEventArgs): void => {
    Log.info(LOG_SOURCE, 'List view state changed');

    const compareOneCommand: Command = this.tryGetCommand('COMMAND_1');
    if (compareOneCommand) {
      // This command should be hidden unless exactly one row is selected.
      compareOneCommand.visible = this.context.listView.selectedRows?.length === 1;
    }

    // TODO: Add your logic here

    // You should call this.raiseOnChage() to update the command bar
    this.raiseOnChange();
  }
```
The part you're interested in is this:
```ts
// This command should be hidden unless exactly one row is selected.
compareOneCommand.visible = this.context.listView.selectedRows?.length === 1;
```
You can access selected items using `this.context.listView.selectedRows`

Hope that helps.

**Comment by mkeysae2** [comment]
This looks good.  Thank you for the response!
