### ISSUE TITLE
Single Logut Not Working With Application using MSAL V2

### ISSUE THREAD

**Issue by kehsani2018** [SharePoint/sp-dev-docs#9094]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We are having issue making a Single Logout work correctly in SharePoint with OIDC applications using MSAL V2. We found about this issue recently since we started working with Azure support troubleshooting Single Logout issues that we were experiencing. According to Azure support Authentication Library V1 has been recently deprecated and recommendation is using MSAL V2 in OAUTH2/OIDC application. Our applications now are in compliance with MSAL V2. SharePoint seems to be using the deprecated version of Authentication Library. Azure support suggested to contact SharePoint support.

### Steps to reproduce

1.
2.
3.

### Expected behavior

When logout from application or SharePoint Single Logout should work

**Comment by AJIXuMuK** [comment]
@kehsani2018 - could you please describe your scenario a bit more?
What is "application" in your case?
@GrahamMcMynn @lucabandMSFT - fyi
