### ISSUE TITLE
The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program. 

### ISSUE THREAD

**Issue by t38jett** [SharePoint/sp-dev-docs#9095]
[Enter feedback here]
When I try following these instructions, I get the subject message:  "The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program."

With this issue happening immediately, it fully negates the usefulness of this presentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by StfBauer** [comment]
There is something wrong with your installation of node, yeoman or gulp.
I think this blog post might be helpful.
https://www.koskila.net/how-to-fix-yo-the-term-yo-is-not-recognized-as-the-name-of-a-cmdlet-function-script-file-or-operable-program-error/

**Comment by t38jett** [comment]
Thank you StfBauer, past that issue now for the next... now I'm getting "Trying to copy from a source that does not exist" and this is the console input/output; 

C:\code\webpart>yo @microsoft/sharepoint

     _-----_     ╭──────────────────────────╮
    |       |    │ Welcome to the Microsoft │
    |--(o)--|    │      365 SPFx Yeoman     │
   `---------´   │     Generator@1.17.4     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
´   `  |° ´ Y `

See https://aka.ms/spfx-yeoman-info for more information on how to use this generator.
Let's create a new Microsoft 365 solution.
? What is your solution name? MyFirstWebPart
? Which type of client-side component to create? WebPart
Add new Web part to solution my-first-web-part.
? What is your Web part name? HelloWorld
? Which template would you like to use? No framework

Error @microsoft/sharepoint

Trying to copy from a source that does not exist: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\NodeJs\node_modules\@microsoft\generator-sharepoint\lib\generators\solution\templates\base\.vscode\settings.json

**Comment by StfBauer** [comment]
So you use NodeJS from Visual Studio? In this case, I recommend doing a stand-alone installation of NodeJS on your machine and not using Visual Studio.

**Comment by AJIXuMuK** [comment]
Totally agree with @StfBauer - use NodeJS from the standalone installation (or nvm/nvs) instead of the one bundled into Visual Studio.

**Comment by t38jett** [comment]
That appears to have me fixed up.  Thank you gentlemen!
