### ISSUE TITLE
Getting a 500 error after renewing the client secret for the remote event receiver

### ISSUE THREAD

**Issue by 2ATCaroline** [SharePoint/sp-dev-docs#9103]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We made a custom remove event receiver based on the documentation and it was working well. Then the clientsecret expired and it's no longer working, even after creating a new secret and updating the configuration. In application insights I see a 500 error on the POST to AppEventReceiver.svc without any details.
We have created a new clientsecret and updated the configuration. We also added the old one to SecondaryClientSecret. If I retrieve the app registration with powershell I do see this has two expired certificates. Could this be the issue? One with Usage Sign and one with Usage Verify. Could this be the issue? 

### Steps to reproduce

1. Create a custom remote event receiver
2. Wait a year
3. Create a new secret with New-AzureADServicePrincipalPasswordCredential
4. Update the secret in the configuration
5. Get a 500 without any info :(

### Expected behavior

I expected the remote event receiver to work correctly after updating the ClientSecret in the config with the new app reg secret.

**Comment by 2ATCaroline** [comment]
When I debug through it it fails on line 114 on in the TokenHelper.cs at line:
tokenHandler.ValidateToken(contextTokenString, parameters, out Microsoft.IdentityModel.Tokens.SecurityToken securityToken);

I see that it received the right clientsecret from the config.
This is the exception that gets thrown:
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: 'IDX10501: Signature validation failed. Unable to match keys: 
kid: '[PII is hidden]', 
token: '[PII is hidden]'.'

**Comment by qianghuang94** [comment]
Please refer to latest discussion in https://github.com/SharePoint/sp-dev-docs/issues/9170

**Comment by 2ATCaroline** [comment]
We ended up rewriting the remote event receiver to: 
https://spblog.net/post/2021/09/14/how-to-use-remote-event-receivers-with-net-core-or-net-5-and-pnp-framework
