### ISSUE TITLE
provide "code ." earlier

### ISSUE THREAD

**Issue by rfulton-lf** [SharePoint/sp-dev-docs#9106]
In the section titled "Use your favorite code editor" it would be helpful if you included the part from "Use Visual Studio Code to explore the web part project structure" that provided the command "code ." as a way to open the current directory in VS Code

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Closing as duplicate for #9104
