### ISSUE TITLE
The line which declares listContainer could be assigned null 

### ISSUE THREAD

**Issue by Alex-Scott-NZ** [SharePoint/sp-dev-docs#9108]
The line:

const listContainer: Element = this.domElement.querySelector('#spListContainer');

should have the non-null assertion operator at the end as we know that '#spListContainer' will always be present:

const listContainer: Element = this.domElement.querySelector('#spListContainer')!;

Without the non-null assertion operator the code returns an error in VSCode 1.57.1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71e8ee66-fe7c-a46e-eeec-fb199962042c
* Version Independent ID: f78aef17-5aa2-8807-73d4-509faecbd153
* Content: [Connect your client-side web part to SharePoint (Hello World part 2)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint)
* Content Source: [docs/spfx/web-parts/get-started/connect-to-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/connect-to-sharepoint.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by codemonkeylikeyou** [comment]
How do you prevent Lint from throwing the no non-null exception when packaging?
