### ISSUE TITLE
Can we get correct List Id from context or somewhere else when a list is added as a WebPart on a custom page? Is #4238 still an issue in latest SPFx versions?

### ISSUE THREAD

**Issue by NewGHUser4321** [SharePoint/sp-dev-docs#9111]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.15
- Node.js version: 16.17.0

### Issue description

I'm having trouble getting the correct **list id** form context in a List View Command Set Extension when the list is added as a WebPart on a custom page. When researching, I came across this issue #4238 in which @andrewconnell says it may not be possible. Is this possible in latest SPFx versions? OR is this still an issue? Are there any work arounds to get the list id?

@andrewconnell Greatly appreciate if you could respond to this.

**Comment by andrewconnell** [comment]
The issue you referenced is from 2019... that's pretty old. The SPFx API has improved.

To your question, see:
https://www.voitanos.io/blog/sharepoint-framework-v1-14-whats-in-latest-update-of-spfx/#new-api-for-list-view-command-set-extensions---better-insight-into-list-view-events--state

**Comment by NewGHUser4321** [comment]
@andrewconnell This helped. Thank you.
