### ISSUE TITLE
[page] A type named 'microsoft.graph.sitePage' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.

### ISSUE THREAD

**Issue by TGiersberg** [SharePoint/sp-dev-docs#9112]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- PowerAutomate "Send http to SharePoint" Action

### Describe the bug / error

Trying to update site page content via Power Automate "Send http request to SharePoint" action, using [SharePoint Rest v2](https://learn.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph).

Calling 
```
PATCH https://{SharePoint_site_url}/_api/v2.0/sites/root/pages/{sitePageId}/microsoft.graph.sitePage
ContentType:application/json
{ 
"@odata.type": "#microsoft.graph.sitePage", 
"title":"Some title" 
}
```
gives error 
`{"error":{"code":"invalidRequest","innerError":{"code":"apiNotFound"},"message":"API not found"}}`. Same error has been reported for graph api at #9081, thus they are probably interconnected and SPO v2.0 doesn't use the updated model yet.

As a workaround I ran `PATCH https://graph.microsoft.com/beta/sites/{sitesId}/pages/{sitePageId}/microsoft.graph.sitePage?$whatif` which gave me the underlying SPO REST url `https://{SharePoint_site_url}/_api/v2.0/sites('{siteId}')/pages/{sitePageId}/oneDrive.page`. PATCH to that url gives error `{"error":{"code":"invalidRequest","message":"[page] A type named 'microsoft.graph.sitePage' could not be resolved by the model. When a model is available, each type name must resolve to a valid type."}}`

I have added `"@odata.type": "#microsoft.graph.sitePage"` to body but that didn't help.

### Steps to reproduce

1. Run below agains SharePoint Rest v2 to reproduce the "API not found" issue
```
PATCH https://{SharePoint_site_url}/_api/v2.0/sites/root/pages/{sitePageId}/microsoft.graph.sitePage
ContentType:application/json
{ 
"@odata.type": "#microsoft.graph.sitePage", 
"title":"Some title" 
}
```

### Expected behavior

`200 OK` and an update to the page title

**Comment by sangle7** [comment]
As I mentioned in the !22046. In SharePoint Rest API you chould change all the model name from 'microsoft.graph.sitePage' to 'oneDrive.page'

**Comment by TGiersberg** [comment]
AHA! Your hint made it work. I followed Graph api doc https://learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&tabs=http#request-body to include @odata.type=#microsoft.graph.sitePage in the body of my request (thinking SharePoint API is calling graph under the hood). Removing odata altogether and switching to `oneDrive.Page` worked successfully. For completeness, here's my successful call:

```
PATCH https://{SharePoint_site_url}/_api/v2.0/sites/root/pages/{sitePageId}/oneDrive.Page
ContentType:application/json
{ 
"title":"Some title" 
}
```

Thank you once more @sangle7 sorting this out, much appreciated.

**Comment by mikelimburg** [comment]
@TGiersberg Just a quick check.
Are you just updating the title? Or complete CanvasLayouts as well?
I noticed CanvasLayouts are no longer updated since the URI changes.

PATCH https://graph.microsoft.com/beta/sites/{_siteId}/pages/{_pageId}/microsoft.graph.sitePage

{
  "canvasLayout": {
    "horizontalSections": [
      {
        "columns": [
          {
            "id": "1",
            "webparts": [
              {
                "id": "{_id}",
                "innerHtml": "<p>请翻译一下！</p>",
                "@odata.type": "#microsoft.graph.textWebPart"
              }
            ],
            "width": "12"
          }
        ],
        "emphasis": "none",
        "id": "1",
        "layout": "oneColumn"
      }
    ]
  },
  "title": "请翻译"
}
