### ISSUE TITLE
"Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details." after deploying app

### ISSUE THREAD

**Issue by abhidas50** [SharePoint/sp-dev-docs#9118]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Hello,

I have added an SPFx app(Webpart component) to my SharePoint site and while adding webpart to my page I'm getting below error:

![image](https://github.com/SharePoint/sp-dev-docs/assets/25766100/96a70502-e3ee-44c7-bc89-1d7e0401cc89)

### Steps to reproduce

1.Create a Library component project with Yeoman utility.
2.Write bunch of code inside function
3.Run gulp bundle --ship 
4.Run npm link
5.Create a Webpart component project with Yeoman utility.
6.Run the command npm link [Library name created in prev step] to link your library.
7.Code the functionality
8.Test with the workbench
9.Run gulp bundle --ship && gulp package-solution --ship
10.Deploy the .sppkg file in app catalog
11.Add the web part to the site's apps
12.Embed the web part

### Expected behavior

The web part should show the as same as in the workbench

**Comment by AJIXuMuK** [comment]
@abhidas50 could you please share the `package.json` of the solution?
as described in the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial#how-to-deploy-and-consume-a-third-party-spfx-library-from-tenant-app-catalog) you should update the dependency to the library: instead of `npm link` (that links to the local folder basically) you should have a name and a version of the library component.
And the library should be deployed too (in tenant app catalog)

**Comment by abhidas50** [comment]
> @abhidas50 could you please share the `package.json` of the solution? as described in the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial#how-to-deploy-and-consume-a-third-party-spfx-library-from-tenant-app-catalog) you should update the dependency to the library: instead of `npm link` (that links to the local folder basically) you should have a name and a version of the library component. And the library should be deployed too (in tenant app catalog)

**Comment by abhidas50** [comment]
Hi,
Please find below code inside **package.json**:
{
  "name": "demomynewcustomlib",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.14.0",
    "@microsoft/sp-property-pane": "1.14.0",
    "@microsoft/sp-webpart-base": "1.14.0",
    "@microsoft/sp-lodash-subset": "1.14.0",
    "@microsoft/sp-office-ui-fabric-core": "1.14.0",
    "mynewcustomlib":"0.0.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.14.0",
    "@microsoft/sp-tslint-rules": "1.14.0",
    "@microsoft/sp-module-interfaces": "1.14.0",
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }
}

I have provided name and a version of the library component but no luck:-(

**Comment by AJIXuMuK** [comment]
@abhidas50 did you upload the library too?
Did you use tenant app catalog or site collection app catalog?

**Comment by abhidas50** [comment]
> @abhidas50 did you upload the library too? Did you use tenant app catalog or site collection app catalog?

I have uploaded in site collection app catalog

**Comment by AJIXuMuK** [comment]
@abhidas50 - could you please share a test solution with me?
