### ISSUE TITLE
BUG: gulp serve stops working when typescript compilation found an error. spfx1.3

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#912]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
gulp serve should be able to continue on working and recompiling the script if there are any changes even if it encountered errors on version spfx 1.3

#### Observed Behavior
gulp serve stops working when typescript compilation found an error.

#### Steps to Reproduce
simply make any changes in your ts/tsx files during gulp serve and gulp serve is not continuing to recompile the scripts once it encountered errors. I have to stop the gulp serve manually and restart it again.
![image](https://user-images.githubusercontent.com/6864547/31259090-d2d53cac-aa8f-11e7-8573-d0fd5936e34f.png)

**Comment by frankchen76** [comment]
Did you check [Gulp serve stops watching after compile error  #297](https://github.com/SharePoint/sp-dev-fx-webparts/issues/297) which might talk about the same thing?

**Comment by jonathanhotono** [comment]
Yes it's the same thing. Glad at least people noticed this issue and not sure whether microsoft takes notice about this.

**Comment by nickpape-msft** [comment]
Hello all, this issue will be fixed in the next release of SPFx. For now, you can bypass the error by disabling the toast. Simply update your gulpfile.js and add the following line of code before `build.initialize(gulp)`:

```
build.mergeConfig({
  showToast: false
});
```

I'm closing this issue, but feel free to re-open if you are still seeing issues in the 1.4.0 SPFx release.
