### ISSUE TITLE
Deploying updates with needing a new app package?

### ISSUE THREAD

**Issue by hazzinator1** [SharePoint/sp-dev-docs#9126]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We have a ListView Extension that we're planning to install in our customer's tenant app catalog. We have set it up with our own CDN deployment on Azure, rather than choosing to go with the JS files included in the package (i.e. includeClientSideAssets has been set to false). The rationale behind this was that we could then control what we uploaded to the CDN, so that if we wanted to deploy some new updates to the app without the customer needing to upload a new version of the app package we could.

I was quite frustrated to then find that every code change generates a new set of hash-named JS files e.g. my-app-abdi93jnfi244sa.js. Each app package is linked to a single hash-name, which means that if we make a small code change, we would then need the customer to upload the new version every single time. This seems unnecessary to me, as I was hoping we could only update the JS files on the CDN rather than needing a manual step on the customer's end. We could hypothetically rename every single new deployment to have the same name hash name, or only change the hash name when there's been a change to the files contained in the app package (can that even be done?). I was just wondering if this is a feasible solution? My understanding of how caching works with these JS files and service workers is patchy unfortunately so someone who knows a bit  more who could chime in would be much appreciated

**Comment by AJIXuMuK** [comment]
@hazzinator1 - you absolutely correctly described how the engine works right now.
Unfortunately, as of now, there is no specific property to disable adding hash to the filename.

There are 2 ways you can proceed:
1. You can customize the configuration/add custom tasks in `gulpfile.js` to achieve the goals. Here is the reference for the start: https://developer.microsoft.com/en-us/graph/support
2. You can implement the solution in such a way that the web part will be just and "entry point" to the solution. It will load all needed resources based on your logic for caching/versioning/etc. The code for the web part will not be changing so you won't need to redeploy it each time.

Hope that helps.

**Comment by hazzinator1** [comment]
@AJIXuMuK thanks for the reply! So I've done some reading on previous threads (https://github.com/pnp/sp-dev-fx-webparts/issues/246 and https://github.com/SharePoint/sp-dev-docs/issues/7022). It really does seem odd to me that for small fixes into production we'd be expected to ship out the webpart to all of our customers again. That could be a pretty large number. It's also unique among the Microsoft solutions we provide, as we have a Teams app that doesn't need anything of the sort (a static index.html just gets updated with the latest hash named JS files suffices i.e. cache busting). I guess something like that corresponds to option 2 in your list. I'm not sure if there's any way we can actually do cache busting in this case as any changes to the files imported within the new entry-point JS file would surely necessitate a new .sppkg to be built around those changed imports as well (e.g. changing the hash name of the import still counts as a code change to the build and would generate a new package).

It seems the big issue is around caching, so if I were to disable the hash names (which is possible, you can follow the workaround at http://kwizcom.blogspot.com/2017/10/removing-hash-from-spfx-bundle-file-name.html), we'd need to be a bit smarter with how we handle caching. As we're hosting the web part on the Azure CDN, if we were to set it's Cache-Control Max Age to a day, would that be sufficient to ensure that a user's web browser gets the latest webpart version a day after it's been released?

**Comment by demyren** [comment]
@AJIXuMuK @hazzinator1 Yes, max-age is respected by the service worker. Before serving a file from the service worker's cache storage, the max age is read along with the Date header on the response. If past max age, the cached file will be invalidated and re-fetched from its origin.

**Comment by hazzinator1** [comment]
Thanks for the info! Will take this up with the team and determine what the best option is for us.
