### ISSUE TITLE
Microsoft Search CSV connector (SharePoint datasource): Error while testing connection. Please check your connection string and try again.

### ISSUE THREAD

**Issue by Stivric** [SharePoint/sp-dev-docs#9127]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Google Chrome Version 115.0.5790.171
- SPFx version
- Node.js version
- etc

### Issue description

When setting up Microsoft Graph CSV Connector , the following is error is received: "Error while testing connection. Please check your connection string and try again"

I have successfully configured all items in this documentation but cannot get past auth settings in the connector.

<img width="549" alt="error log" src="https://github.com/SharePoint/sp-dev-docs/assets/141690428/4da343e9-0324-409c-ac8e-23aea03832bd">

**Comment by AJIXuMuK** [comment]
@Stivric - please, address the question to MS Graph team: https://developer.microsoft.com/en-us/graph/support
