### ISSUE TITLE
SPFx compatibility for Node.js (LTS) v18

### ISSUE THREAD

**Issue by matsla** [SharePoint/sp-dev-docs#9130]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Node.js LTS v16 will soon reach end of lifetime (maintenance) when will SPFx be compatibility with Node.js LTS v18?

**Comment by AJIXuMuK** [comment]
@matsla - this is one of our top priorities.
Unfortunately, we're a bit behind of schedule but working on the version bump.
