### ISSUE TITLE
Beta API pages endpoint: Update webparts not working if page contains stream classic video webpart

### ISSUE THREAD

**Issue by TGiersberg** [SharePoint/sp-dev-docs#9131]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Tested using PNP Powershell `Invoke-PnPSPRestMethod`

### Describe the bug / error

Trying to update a Text webpart. The target page contains one stream classic webpart and multiple text webparts.
Updating via SharePoint REST 2.0 api fails with error
`Invoke-PnPSPRestMethod: {"error":{"code":"generalException","message":"General exception while processing"}}`

### Steps to reproduce

```
Connect-PnPOnline -Url {site} -Interactive
$url = "/_api/v2.0/sites/root/pages/{pageId}/oneDrive.Page/webParts/{webPartId}"
$content = @"
{
    "@odata.type": "#oneDrive.textWebPart",
    "innerHtml":"<p>some text</p>"
    }
"@
Invoke-PnPSPRestMethod -Method Patch -Url $url  -ContentType "application/json" -Content $content
```
fails with error
`Invoke-PnPSPRestMethod: {"error":{"code":"generalException","message":"General exception while processing"}}`

Manually removing the stream classic webpart, then running steps above again updates the targeted webpart with new innerhtml.

### Expected behavior

Updating oneDrive.textWebPart should successfully update with new innerhtml, independent of the presence of stream classic webpart.

**Comment by sangle7** [comment]
Hey @TGiersberg, Thanks for raising this issue. Could you please repro and paste the response here? I need the request id and timestamp to access the logs.
