### ISSUE TITLE
Type 'null' is not assignable to type 'SPFI'

### ISSUE THREAD

**Issue by ThorstenProbstARAG** [SharePoint/sp-dev-docs#9143]
[Enter feedback here]

cannot get along with this tutorial and did not find any help.
So, what could cause this happening?
in the pnpjsConfig file the line 11 (var _sp: SPFI = null;) has the error "Type 'null' is not assignable to type 'SPFI'"
all the rest of project has no erro at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b19eb96-192d-2d8b-8d4e-0de787f22093
* Version Independent ID: e2cbd2b2-8bb7-a95f-0768-15f1b045b4c4
* Content: [Use @pnp/sp (PnPJS) library with SharePoint Framework web parts](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts)
* Content Source: [docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nick-pape** [comment]
Hi there,

This definitely seems like an issue in the tutorial. SPFx 1.17.4 began enabling strict null checks by default in newly created solutions. So this error message is correct, you cannot assign `null` to an `SPFI` type.

To fix this in your local solution, please change:

`var _sp: SPFI = null;`

to:

`var _sp: SPFI | null = null;`

I have created a PR to update the tutorial.
