### ISSUE TITLE
SharePoint CSOM - Current site is not a tenant administration site

### ISSUE THREAD

**Issue by n-zyma** [SharePoint/sp-dev-docs#9148]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft.SharePointOnline.CSOM 16.1.23912.12000

### Issue description

We use this code to iterate tenants site collections:

```
string url = $"https://{initialDomainName}-admin.sharepoint.com";
var context = new ClientContext(url);
context.ExecutingWebRequest += (s, e) =>
{
    string accessToken = GetAccessToken();
    e.WebRequestExecutor.RequestHeaders["Authorization"] = "Bearer " + accessToken;
};

var tenant = new Tenant(context);
SPOSitePropertiesEnumerable spp = tenant.GetSitePropertiesFromSharePoint("0", true);

context.Load(spp);
await context.ExecuteQueryAsync();
```

and it works correctly for almost all of our tenants, but for some of them we get this exception:

`Microsoft.SharePoint.Client.ServerException "Current site is not a tenant administration site."
`

We have Sites.Manage.All permissions for our app.

**Comment by nick-pape** [comment]
So, it is possible that the tenant administration site is not `.sharepoint.com`. For example, GCC tenants are `sharepoint.us`. Some sites may also be using vanity domains.

If possible for your scenario, maybe try logging the failing admin URL's and verifying via browser that they are in fact the correct admin url?
