### ISSUE TITLE
Custom color palette reverts to default after refresh page

### ISSUE THREAD

**Issue by vomos2020** [SharePoint/sp-dev-docs#9153]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

We use custom color palette for branding custom spfx web parts. We are facing an issue that after some time after refreshing setting in spfx webpart custom colors became reverting to default colors.
We checked on different tenants and this issue reproducing only on specific tenant not on all. 

We used Add-SPOTheme -Name "Custom theme" -Palette $palette -IsInverted $false  to deploy custom palette. 

### Steps to reproduce

1. Upload new color palette
2. Apply new color palette on Site collection. 
3. Click Save.  Result: colors applied to spfx webparts
4. Refresh the page. Result: color reverted to default values on all webparts

### Expected behavior

After applying new color palette color must change on all custom spfx webparts

**Comment by AJIXuMuK** [comment]
@vomos2020 - could you please provide more information on this issue?
- how do you use/apply the palette in your custom code?
- do out of the box web part respect the new palette when the custom SPFx web parts don't?
- could you please share the palette definition?

**Comment by vomos2020** [comment]
@AJIXuMuK hi, we use this in code
export const theme = window.__themeState__?.theme;
export const spTheme = {
  themePrimary: theme?.sb_themePrimary,
  themeSecondary: theme?.sb_themeSecondary,
  ...
};

**Comment by CallumCrowley** [comment]
@AJIXuMuK we've also noticed this bug on multiple tenants. We've uploaded a custom theme using [Add-SPOTheme](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/add-spotheme?view=sharepoint-ps) but the value for `neutralLighter` reverts to a default SharePoint colour (#F0F0F0) after a page refresh.

**Comment by AJIXuMuK** [comment]
@vomos2020 @sosandumsft - unfortunately we don't support custom properties in the theme (`sb_` prefixed ones in your case).
I would recommend having a mapping where based on the primary color of the theme you can grab all others from your custom code.

@CallumCrowley - the issue with neutral colors has been discussed [here](https://github.com/SharePoint/sp-dev-docs/issues/8870) and [here](https://github.com/SharePoint/sp-dev-docs/issues/8370)
