### ISSUE TITLE
Text Webparts: Automatic conversion of CK4 pages to CK5 pages screws up table formatting

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#9160]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome Version 116.0.5845.97 (Official Build) (64-bit)

### What's this about?

This report is about (automatically created) modern pages that are stored in the Site Pages library and that are showing tables with screwed up layout when going into edit mode.

### How are those tables created?

The pages in my case are created using the PnP Provisioning engine and contain a variety of content, and also tables.

### How does SharePoint render those pages in the browser? And what changed?

SharePoint uses the **CKEditor** to display its text web parts in the browser.

Up until recently the CKEditor version 4 (CK4) has been used. This seems to be slowly transitioning to version CKEditor version 5 (CK5). There have been changes to the [pnpcore](https://github.com/pnp/pnpcore/blob/cb4f31c3cb5918ac2f74be95b4635894ae32338b/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/RtePageSettings.cs#L8) repo as well (by @jansenbe), allowing to choose whether to create CK4 or CK5 pages.

Note: Looking at the HTML for tables there has been a change from using a `div` as wrapper element (in CK4) to using a `figure` as wrapper element (in CK5).

### How is the transition from CK4 to CK5 performed?

The question how pages are transitioned from version CK4 to CK5 [so far has been unanswered](https://github.com/pnp/pnpcore/discussions/1219), until today. I played with the page versions and noticed the following:

When a CK4 page is going into edit mode, the page flickers more than usual. **And after this flickering the tables are screwed up.** Digging into the network traffic shows that those pages were "upgraded" from CK4 to CK5.

### Proof of table screwage

I captured two videos, showing the effect.

Here is a CK4 page, with a table, entering edit mode:

https://github.com/SharePoint/sp-dev-docs/assets/3469970/6d136883-d94b-4463-927f-240cd740956d

Notice how the table looks in the end. This used to work properly with CK4.

To emphasize the effect, I reverted the page and throttled the browser to "fast 3g". Same page.

Here's the surprising result:

https://github.com/SharePoint/sp-dev-docs/assets/3469970/8fd8d25d-0bd3-400c-9198-54339c299c0d

After entering edit mode, you can see _something_ clearing the page. The table is there for a moment, then gone. Then reappears, formatted badly. But what happened then surprised me because in the last moment - the table snapped into place. So this is not the video restarting - it's the table making "plop" and looking good again. Not sure if my mouse movement over the table triggered something.

This is on a developer tenant.

**Edit**: After pressing F5 on the converted, saved page, the table looks like this:
![image](https://github.com/SharePoint/sp-dev-docs/assets/3469970/443b295e-2b70-43a8-a6e3-e31eb9a7e147)

### How to know those pages have been converted to CK5?

Looking at the network traffic there are calls to the SavePage endpoint. The payload carries the content version, which indicates CK5.

I double checked with pages on another tenant where pages live that have been created the same way as our page here. Those pages behaved well when being edited. The tables stayed put, no change. Looking at the network traffic showed that the content version for those pages stayed at 4, indicating CK4.

So there is a difference in behavior between tenants.

### Interpretation

I see (so far) well-behaved pages that get mangled when being transitioned from CK4 to CK5 format. Furthermore the videos above show that this might be a timing issue in the (JavaScript-based?) converter, since slowing down things created a well-behaved table on the CK5 page as well.

Note that "so far well-behaved" means that they could be edited properly without the tables being altered in such a way as seen in the videos.

I'd really like some input here.

### Steps to reproduce

The effort to reproduce this is quite high. I'd have to create a PnP PowerShell that provisions a page that behaves as shown. And you would have to use two tenants with different behaviors to show the regression. I can do that (well, the first part) but hope to get some input before on the issue, from somebody saying "yeah, we're still fiddling around".

**Edit:** I assume the HTML structure of the text web part might be helpful.

Here's the HTML copied from Chrome when displaying the table before being converted, in view mode:

```html
<div data-sp-feature-tag="Rich Text Editor" class="rte-webpart"
    data-sp-feature-instance-id="375a1cee-9ea0-4d7b-b9e4-8be977afdb85" dir="auto">
    <div data-automation-id="textBox"
        class="cke_editable rte--read rte--inline ckeditable_removeMargin highlightFocusFix rte-strong-fontWeight blockQuoteFont zeroSpacing cke_editable rteEmphasis root-146">
        <p></p>
        <div class="canvasRteResponsiveTable">
            <div class="tableLeftAlign tableWrapper">
                <table class="borderHeaderTableStyleNeutral" title="Table">
                    <tbody>
                        <tr>
                            <td style="width:12%;"><strong>First</strong></td>
                            <td style="width:84%;"><strong>Second (manually widened)</strong></td>
                            <td style="width:2%;"><strong>Third</strong></td>
                        </tr>
                        <tr>
                            <td style="width:12%;"><br></td>
                            <td style="width:84%;"><br></td>
                            <td style="width:2%;"><br></td>
                        </tr>
                        <tr>
                            <td style="width:12%;"><br></td>
                            <td style="width:84%;"><br></td>
                            <td style="width:2%;"><br></td>
                        </tr>
                        <tr>
                            <td style="width:12%;"><br></td>
                            <td style="width:84%;"><br></td>
                            <td style="width:2%;"><br></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <p></p>
    </div>
</div>
```

Here's the HTML copied from Chrome when displaying the table after being converted, in view mode, with table layout mangled:

```html
<div data-sp-feature-tag="Rich Text Editor" class="rte-webpart rte--ck5 rte--read-ck5"
    data-sp-feature-instance-id="375a1cee-9ea0-4d7b-b9e4-8be977afdb85" dir="auto">
    <div data-automation-id="textBox" class="ck-content rteEmphasis root-146">
        <p>&nbsp;</p>
        <figure class="table tableLeftAlign canvasRteResponsiveTable" style="width:98px;" title="Table">
            <table class="borderHeaderTableStyleNeutral ck-table-resized">
                <colgroup>
                    <col style="width:12.24%;">
                    <col style="width:85.72%;">
                    <col style="width:2.04%;">
                </colgroup>
                <tbody>
                    <tr>
                        <td><strong>First</strong></td>
                        <td><strong>Second (manually widened)</strong></td>
                        <td><strong>Third</strong></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </figure>
        <p>&nbsp;</p>
    </div>
</div>
```

**Edit edit**: looking at the `figure` - the `width:98px` does not seem right...

### Expected behavior

I expect the pages that worked well in CK4 mode (when being viewed, AND edited) to also behave well in CK5 mode.

My test was about tables. But who knows what else lurks there.

**Comment by heinrich-ulbricht** [comment]
Note: the `div`-based tables are created by the PnP modernization library as well, so modernized SharePoint on-prem pages _might_ be affected, too:

https://github.com/pnp/pnpcore/blob/cb4f31c3cb5918ac2f74be95b4635894ae32338b/src/sdk/PnP.Core.Transformation.SharePoint/Services/HtmlTransformator.cs#L296-L303

https://github.com/pnp/pnpcore/blob/cb4f31c3cb5918ac2f74be95b4635894ae32338b/src/sdk/PnP.Core.Transformation.SharePoint/MappingProviders/SharePointHtmlMappingProvider.cs#L241-L248

**Comment by nick-pape** [comment]
Hi @heinrich-ulbricht , we are currently aware of this issue and the product group is taking a look at it. It sounds like this is an issue with the CK5 upgrade, rather than PnP, per se, so this isn't necessarily the best place for this ticket. We appreciate the report, though.
