### ISSUE TITLE
ClientSideExtension.ListViewCommandSet.ContextMenu Debugging and order

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#9167]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version latest
- SPFx version 1.17.4
- Node.js version 16
 

### Issue description

I am new to writing extensions. I can't figure out 2 things: 
My code starts on a ClientSideExtension.ListViewCommandSet.ContextMenu and it shows the `Dialog.alert(...` fine.

1.  It does not hit the Breakpoints in VS code. What should I do to make it break in the code?
2. How can I bring the context menu item higher in the list? Now it is above the "Details"

Thank you.

**Comment by nick-pape** [comment]
Hi @Ofer-Gal,

For 1 - try taking a look at [this guide](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode) and see if it helps. Are you already following this guide and breakpoints aren't working?

For 2 - are you asking how to bring the context menu items before the "Details"? You can, of course, reorder them by editing the `items` array in the manifest, but there is not a way to get them to appear before the built-in commands.

**Comment by Ofer-Gal** [comment]
Thanks @nick-pape I replaced the workbench URL with the page I want to debug in with the query string added by SPFx and it worked.

I am sure users will complain it is not high enough in the list 😂
