### ISSUE TITLE
Webpart disappear from site when an updated spfx (v1.17.4) is deployed in Tenant App Catalog

### ISSUE THREAD

**Issue by Circlet-ND** [SharePoint/sp-dev-docs#9169]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFX v1.17.4

### Describe the bug / error

We updated one of our webpart to SPFX v1.17.4. and pushed it to the tenant app catalog. After it is updated and deployed, the app no longer appears in our sites and pages.

The app is used in multiple sites and now it disappears from all sites and pages. I can't even search for the app when I edit the page and search for the webparts from the + button. 

The only fix that seems to resolve this issue is to:
1. Go to Site Contents
2. Click on the 3 dots beside the App
3. Click Details
4. Click "Get it" under "There is a new version of this app. Get it now."

You will need to do this for every site collection that has the app.

### Steps to reproduce

1. Create an spfx project from previous version (1.16.x)
2. Deploy to tenant app catalog
3. Add that webpart to multiple sites
4. Update spfx to v1.17.4
5. Upload the updated spfx to tenant app catalog
6. Load the page

### Expected behavior

The webpart will disappear from the page. Please note that this issue only happen recently

**Comment by AJIXuMuK** [comment]
@Circlet-ND - it sounds like between the versions you have changed the `features` in `package-solution.json` file. Or you are manually updating from the version less than 1.14 as there were some changes how we generate the features.
Could you please: 
- provide the version you're updating from
- compare `package-solution.json` content before and after the update.

You can also check some of the closed issues here (for example, #7929)

**Comment by Circlet-ND** [comment]
@AJIXuMuK what happened was we removed the features from our package-solution.json file and published it via the Tenant App Catalog, and suddenly it disappeared from all sites, unless we go to the site and click "Get It" under "There is a new version of this app. Get it now." 

We clicked "Get It" for several sites just to test it and it works. We decided to update the package-solution.json and bring back the features. We deployed it to the tenant app catalog and now it appears in all sites, except for the ones we click "Get It". 

So I think it is all good for now? Apologies for the confusion

**Comment by AJIXuMuK** [comment]
@Circlet-ND - when you adding/removing features it may lead to issues as if there is no feature in the package-solution file - we will still generate one. In that case the IDs for the features will be different and it may lead to a situation when a web part is connected to 2 different features at the same time.
Probably the safest way from the current state is to delete and re-add the the app on the sites where you clicked "Get it" in your tests.

**Comment by Circlet-ND** [comment]
@AJIXuMuK Yup I can confirm deleting and readding the app works. Thank you for your help and the prompt response!
