### ISSUE TITLE
Top Navigation suddenly gone in multiple tenants for modern experience

### ISSUE THREAD

**Issue by sharepointalist** [SharePoint/sp-dev-docs#917]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Top Navigation should show up in modern experience

#### Observed Behavior
Top navigation is not present on modern pages (including site contents page). (have it in a few tenants). Classic mode works fine. Last time it was working well in modern experience on October 6, 2017.

#### Steps to Reproduce
Add navigation elements using /_layouts/15/AreaNavigationSettings.aspx page. Both Managed Navigation and Structural Navigation options will result in the same issue.

**Comment by sharepointalist** [comment]
And it is all with Publishing being active. Looks like it works well when Publishing is disabled

**Comment by sharepointalist** [comment]
When publishing is disabled (both web and site collection feature) - top navigation shows back up.

**Comment by michel-weber** [comment]
Is it the same experience in all browsers (Chrome, Firefox, Edge)?

**Comment by sharepointalist** [comment]
It was the same experience in Safari, IE and Chrome.
At this moment looks like it is back working on all the tenants, so we can probably close this bug for now.

With best regards,
Paul Shkurikhin | Managing Director | LinkedIn<https://www.linkedin.com/in/sharepointalist>
Sharepointalist<http://www.sharepointalist.com/> – Your Trusted SharePoint Vendor
Meet our team at European SharePoint Conference in Dublin, Ireland on November 13-16, 2017, booth 20.
Gold Microsoft Partner | SharePoint | Office 365 | Azure | Dynamics
Mobile +1 (310) 614 4980

**Comment by mcmynn83** [comment]
@sharepointalist - we rolled back a change and have fixed the issue.  Please let us know if it comes up again.
