### ISSUE TITLE
Unable to create document from custom content type, using document template

### ISSUE THREAD

**Issue by CallumCrowley** [SharePoint/sp-dev-docs#9171]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

If we create a content type in the Content Type Gallery and specify a document template URL, the content type cannot be used to create a new document in a library using the "New" menu (after pulling the content type in to the libary). The users have read access to the document template.

When selecting the content type from the "New" menu, a tab is opened and then immediately closed. Upon inspection, the following error is found in the console:

![image](https://github.com/SharePoint/sp-dev-docs/assets/58050310/435ae748-0703-4439-ae9b-e18fb632ce7a)

![image](https://github.com/SharePoint/sp-dev-docs/assets/58050310/6224af11-8685-4ed3-8e1b-a360b1f37a26)

![chrome_0TObEjJOVM](https://github.com/SharePoint/sp-dev-docs/assets/58050310/c0ac2789-f2fe-4b4d-8f4f-175f2ab75183)

The document template is stored in a different site, to the site in which the content type is being used e.g.

Template URL: /sites/Templates/Shared Documents/Short document template.dotx
Library: /sites/Testteam/Shared Documents

The content type is pulled from the Content Type Gallery, with the document template URL property already filled in.

This also occurs if you [upload the document template to the content type within the Content Type Gallery](https://learn.microsoft.com/en-us/sharepoint/create-customize-content-type#associate-a-document-template-with-a-content-type) and then pull that content type down to the site. This leads to a synchronisation error which can be found in the Content type publishing error log:

![image](https://github.com/SharePoint/sp-dev-docs/assets/58050310/543de1c7-0b1d-4a21-8a48-6dbb0499b780)

When using the "New" menu it seems that the GetListUsingPath API call, is unable to handle a server relative URL that refers to a document template in another SharePoint site.

The alternative of uploading the document template to the content type via the gallery, doesn't seem to work because the file is not synchronised to sites when the content type is pulled down.

### Steps to reproduce

1. Create a custom content type in the Content Type Gallery, inheriting from the Document content type.
2. Open the content type in the Gallery and click Settings and then Advanced settings
3. Enter a URL of document template stored in a SharePoint site in your tenant. Ensure that you have access to this site and document template.
4. Navigate to a library in a separate site to where your template is stored.
5. Click the "+Add column", scroll to the bottom and click "Add a content type", then click Next.
6. Choose the content type you created in step 1 and apply.
7. Use the New menu and attempt to create a document using the content type.

### Expected behavior

After clicking the content type from the "New" menu, a new document will be created using the document template for that content type.

**Comment by nick-pape** [comment]
Thank you for your submission. As explained in our wiki ([Issue List: What doesn't belong in the issue list](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#what-doesnt-belong-in-the-issue-list)), this issue list is for SharePoint developer/development issues. All capability question/discussion questions, or topics related to SharePoint administration & end-user topics should be reported through the support user interface available in the tenant admin settings. You can also have a discussion and ask questions at the [SharePoint TechCommunity](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint) forum. You can learn more about this in our wiki: [type:invalid-not-dev-issue](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List-Labels#typeinvalid-not-dev-issue)
