### ISSUE TITLE
PnP PowerShell options for SharePoint Subscription Edition?

### ISSUE THREAD

**Issue by Richter79** [SharePoint/sp-dev-docs#9176]
Of course PnP is an open-source solutions, and MS does not officially support it, but is there any statement of using PnP PowerShell in a SharePoint SE environment?

SharePoint SharePointPnPPowerShell2019 seems to work based on some user feedbacks, but for how long since it is not  maintained and intended for use with SP2019.
Due to bigger changes in updates (e.g. the SPFx version), I guess there could be changes, so that even basic operations would not any more in the future?

PnP.PowerShell is definitely only working for SharePoint online:
https://github.com/pnp/powershell/discussions/3147#discussioncomment-6306163

At least a hint, in the documentation, that for SharePoint SE there is and will be no version would help clarify the situation!
Even when it would be dissatisfying, when all scripts for SP2013 to SP2019 could/should not be used any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b81c61e2-fab8-9bd4-3b25-a542b02324cd
* Version Independent ID: 69a0a7fd-b209-2f9a-8c3d-010783df2c4c
* Content: [PnP provisioning engine and the Core library](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-engine-and-the-core-library?source=docs)
* Content Source: [docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
SharePointPnPPowerShell2019 does indeed work with the subscription edition as the subscription edition API surface and features are an evolution of SharePoint 2019. This means that any existing feature which has not been changed should be fine to be used in subscription edition - as the API surface has remained the same.

There's no specific date or timeline when the PnP PowerShell 2019 version would stop working in subscription edition - it's more on when some new features are introduced which break the existing API surface. PnP PowerShell is a community led project and highly dependent on the voluntary work done by our community members. The support for the on-premises was dropped simply as there was not enough volunteers to keep this open-source project moving.

From Microsoft perspective PnP PowerShell does use the supported APIs under the covers, but there's no direct support from Microsoft for these areas - as ownership is on the open-source community side. For anything which is not supported in subscription edition with PnP PowerShell, there is out of the box server side PowerShell. This works a bit differently and requires however admin permissions, so they are not really comparable, but there's no matching remote PowerShell model for the Subscription edition or even for SharePoint Online directly from Microsoft side.

**Comment by VesaJuvonen** [comment]
and yes - we should update the documentation referenced in this issue, but the core question has been answered, so closing for now. Any specific questions related on the PnP projects should be routed to the PnP organization repositories where an active community can provide the latest.
