### ISSUE TITLE
SPHttpClientBatch POST-call for updateItem not working

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#918]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

I am trying to update an item with SPHttpClientBatch request and I am getting the following error message: 

1dc
--batchresponse_35904622-8aeb-4664-b343-4978381ea2c6
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8

{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"Unable to read data. The end of input stream is encountered."}}
--batchresponse_35904622-8aeb-4664-b343-4978381ea2c6--

0

my request looks like this from Fiddler:

--batch_55be2aa4-fc17-4570-b663-b2d8a88efd8e
Content-type: application/http
Content-Transfer-Encoding: binary

POST https://tenant.sharepoint.com/sites/subsite/_api/Lists/GetByTitle('Site%20Pages')/Items(44) HTTP/1.1
accept: application/json;odata=verbose
content-type: application/json;odata=verbose
if-match: *
x-http-method: MERGE
--batch_55be2aa4-fc17-4570-b663-b2d8a88efd8e--

I read that there a bug back in June and the issue is also closed but I am still getting this error. Is this bug is resolved or it is yet to be resolved? Can anyone please tell me. 

Thanking you.

**Comment by mcmynn83** [comment]
@arunakshi  - Could you include the post body that you are trying to update with so we can try to determine what the issue is?  Also, if possible could you include the sprequestguid for the POST to SharePoint (it will be in the response header of the 400 you are receiving).

**Comment by arunakshi** [comment]
@mcmynn83 - thank you for your reply. I tried with fetch and PATCH as X-HTTP-Method and I can update the item with some field values but it is not working for Taxonomyfield values and multi-people picker fields. 

Here is my request:
 this._spHttpClient.fetch(itemUpdatedUrl,
                SPHttpClient.configurations.v1,
                {
                    body: JSON.stringify(body),
                    method: "PATCH",
                    headers: {
                        'X-HTTP-Method': 'PATCH',
                        'IF-MATCH': eTag
                    }                   
                }
            )
            .then(response => response.json())

The following is my post body: 

This Request BODY is only for People Picker field update:
{"articleDate":"2017-10-30T23:00:00.000Z","articleContactsId":{"results":[";#31"]}}

I am not sure if this is the sprequestguid for the POST request or not, I have a guid in my request, did you mean this?
--batch_c38d47f9-9fc1-4ce9-944b-abfdf4df1104--

The response for this request: 
{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"An unexpected 'StartObject' node was found for property named 'ImArticleContactsId' when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}

When I change the field type single value field then its working without problem: 

The following is my request for Taxonomy field value update:

{"articleDate":"2017-10-30T23:00:00.000Z","organisationalScope":{"TermGuid":"b119ed84-b25c-436c-b7ce-7f2bc9fbda1c","WssId":4,"Label":"HR"}}

--batch_459f0417-50a7-4d94-b824-461f30c6a53f--

and the response for this request is :14f
--batchresponse_0a09942d-3698-457b-bfec-4b8758868f65
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 204 No Content
CONTENT-TYPE: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
ETAG: "540"


--batchresponse_0a09942d-3698-457b-bfec-4b8758868f65--

It will not update the taxonomy field. 

I tried without wssId and correct wssId for that term also and it is always the same response.

**Comment by pgonzal** [comment]
Could you provide complete repro steps that will work on an out-of-box SharePoint site?  Alternatively, if you could provide a complete fiddler trace, that might work as well.  (Note that Fiddler archives include credential information, so don't post it publicly unless it's using a throwaway account.)

Most likely something is wrong with how you're constructing your query.

Also, if you can repro this without `SPHttpClientBatch`, that would be interesting.  `SPHttpClientBatch` is still in "preview" mode and is not officially supported yet for production projects.

**Comment by arunakshi** [comment]
@pgonzal, thank you very much for you reply. I changed my code to use JSOM from my webparts. I do not have that code now and also the Fiddler sample. I will close this for now.
