### ISSUE TITLE
Is there a way to switch the theme in SPFx on-the-fly?

### ISSUE THREAD

**Issue by nils-a** [SharePoint/sp-dev-docs#9187]
This is probably more a question than a real issue:

The described theming works for SPFx solutions in SharePoint, as well as Teams.
Now, in Teams the theme can be switched at runtime from e.g. from "light" to dark.

Every element in Teams switches its color automatically when this happens. SPFx components that were themed in the described way, however, do not. One has to open a different UI in Teams (i.e. another tab) and then come back to the UI containing the SPFx component to "re-theme" the component.

While the SPFx API provides a way to detect the theme change using `this.context.sdks.microsoftTeams.app.registerOnThemeChangeHandler`, I could not find a way to make the computed css styles "re-compute".

Is there a way in SPFx to switch the theme "on the fly"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7a0e56-b781-1779-9bcf-bb688892a0f0
* Version Independent ID: a3ccd2c0-b0c0-84bc-ffd2-41bdaddede56
* Content: [Use theme colors in your SharePoint Framework customizations](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations)
* Content Source: [docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-theme-colors-in-your-customizations.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nils-a** [comment]
It seems, the [`EnhancedThemeProvider`](https://pnp.github.io/sp-dev-fx-controls-react/controls/EnhancedThemeProvider/) is the answer.

I'll try to add a section (or at least a link somewhere) to the docs in the coming days.

**Comment by nils-a** [comment]
@AJIXuMuK fair enough. My only "problem" is that at some point the docs mention the ability to deploy SPFx to SharePoint and Teams and on some other point the docs mention the ability to switch the theme.

Nowhere in the docs is mentioned that "Alas, this does not work in teams. Sorry. 🤷"

But, since you closed the issue, it feels like having this information publicly available is not desired.

**Comment by AJIXuMuK** [comment]
@nils-a - just to be clear. I'm not saying we don't support Teams.
We do support. But you need a refresh to update the underlying SharePoint theme.
However, in the default scaffolded solution for web part we're showcasing how to make dynamic update if you need it.
