### ISSUE TITLE
Cannot find module 'combokeys'

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#92]
When I want to make use of the ModuleLoader, I get the following errors during build:

```
Error - typescript - node_modules\@microsoft\sp-module-loader\lib\SPModuleLoader.d.ts(1,28): error TS2307: Cannot find module 'combokeys'.
Error - typescript - node_modules\@microsoft\sp-module-loader\lib\importableSpModuleLoader.d.ts(1,28): error TS2307: Cannot find module 'combokeys'.
```

Already tried removing the individual modules (combokeys and sp-module-loader) and a full re-install (removed the complete node_modules folder). 

The combokeys module is installed. Visual Studio Code doesn't give any errors about the module.

**Comment by chakkaradeep** [comment]
Can you install combokeys package and try again?

npm i combokeys --save-dev

**Comment by chakkaradeep** [comment]
Oh sorry, it's the typings:

tsd install combokeys --save

**Comment by estruyf** [comment]
@chakkaradeep tried that already, but it didn't solve the issue.
![snip_20160827191445](https://cloud.githubusercontent.com/assets/2900833/18028943/991df4fc-6c8a-11e6-93a1-0a390490e781.png)

**Comment by estruyf** [comment]
Completly rebuild everything from scratch and that solved it. Don't know what caused it.

**Comment by tobiaswest83** [comment]
This is happening for me on existing and new projects, using latest release of the framework, `tsd install combokeys --savedev` does the trick as a workaround.
