### ISSUE TITLE
Limitation of the site footer for mobile devices

### ISSUE THREAD

**Issue by kefujino** [SharePoint/sp-dev-docs#9202]
The following article states that the site footer doesn't appear on mobile devices. 

https://learn.microsoft.com/en-us/sharepoint/dev/features/site-footer
> Footers don't appear in sites on mobile devices or apps.

It is correct on my smartphone (Android) with Edge browser. On the other hand, if I use tablet devices (iPad mini and iPad Pro), a footer appears. Is it a limitation that depends on the screen size rather than the limitation of the mobile device? If yes, could you please specify that on devices with large screens, such as tablets, the footer may be displayed?

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfa53a2-c6f9-40f8-fea4-915f98d3eada
* Version Independent ID: d4078ea1-a095-a1c4-1c65-fb19ef9d9003
* Content: [Overview of the SharePoint Site footer](https://learn.microsoft.com/en-us/sharepoint/dev/features/site-footer)
* Content Source: [docs/features/site-footer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/features/site-footer.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nick-pape** [comment]
The check is rather complex and is primarily done based off of user agent strings. Would you be able to share the user agent string for the tablet devices?
