### ISSUE TITLE
Property 'flags' is protected but type 'SPHttpClientConfiguration' is not a class derived from 'SPHttpClientConfiguration'.

### ISSUE THREAD

**Issue by lhdeveloper** [SharePoint/sp-dev-docs#9206]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.17.2
- Node.js version v14.19.3

### Describe the bug / error

This error started happening all of a sudden.
When I try to run the gulp bundle in my application I get the message below:

Property 'flags' is protected but type 'SPHttpClientConfiguration' is not a class derived from 'SPHttpClientConfiguration'.

I've already tried upgrading and downgrading the Node version, imagining that it could be an incompatibility issue, but to no avail.

### Steps to reproduce

execute gulp bundle or gulp bundle --ship

### Expected behavior

run the application bundle without any problems.
It was working normally and for some reason it stopped working.

There was no dependency update or anything like that.

**Comment by nick-pape** [comment]
This definitely sounds like an issue with incompatible dependencies. Can you share the output of `npm list @microsoft/sp-http` ?

**Comment by andrewconnell** [comment]
[Node.js v14 support was dropped in SPFx v1.16+](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16#remove-nodejs-v12-and-v14-support)... suggest you upgrade to Node.js v16, nuke your **node_moduels** & **package_lock.json** file, then rerun **npm install**. Then try again to ensure you're in a supported scenario first if you're using SPFx v1.17.2.
