### ISSUE TITLE
PATCH using Pages API, General exception while processing

### ISSUE THREAD

**Issue by kachihro** [SharePoint/sp-dev-docs#9208]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

Graph API via PowerAutomate
Trialling within Graph Explorer

### Describe the bug / error

I'm having trouble with patching a WebPart for a specific page - it's the HOME page for a site.

The same body/payload works OK for a different page - different GUID for page, and webPart (of course).
The only error is 'general exception while processing'.

Is there any reason why it would work on ONE page - but not another ??

### Steps to reproduce

Using via Graph Explorer ;
https://graph.microsoft.com/beta/sites/c49a204c-eb6c-4d16-885c-a7743c4324c3/pages/07214de7-f7d3-4bc5-b6b1-474d9f98ab4d/microsoft.graph.sitepage/webparts/852e7aff-3d7f-41d1-8d12-eafd2e021df1

BODY for 'http patch' ;

{
    "webPartType": "7f718435-ee4d-431c-bdbf-9c4ff326f46e",
    "data": {
        "properties": {
            "layout": 1,
            "persons": [
                {
                    "id": "i:0#.f|membership|personName@tenant.com.au"
                }
            ]
        },
        "serverProcessedContent": {
            "searchablePlainTexts": [
                {
                    "key": "title",
                    "value": "Project Manager"
                }
            ]
        }
    },
    "@odata.type": "#microsoft.graph.standardWebPart"
}

*** This works OK for 1 page in the same site - but not for another page !!??

2.
3.

### Expected behavior

OK - 200 response - not 500 error

{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2023-09-13T09:05:14",
            "request-id": "ad99b130-9d96-4984-85b0-5a9bada31bb8",
            "client-request-id": "961af9b1-d95c-48a2-9eb1-b535d814ca2d"
        }
    }
}

**Comment by Yadong1106** [comment]
Hi, does this problem still exist? I remember that we have fixed this problem.  We have already tested it, and this issue did not occur. If it has been solved, could you please help us close this? Thank you.
