### ISSUE TITLE
Term Store

### ISSUE THREAD

**Issue by SakshiAdlakha** [SharePoint/sp-dev-docs#9214]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SharePoint Online term store issue

### Issue description

Hi All, I am trying to create the term set with the defined GUID we have on SharePoint 2013 on our SharePoint online QA tenant for migration purpose but when I am using the defined Guid then it is throwing error 'New-PnPTermSet: TermStoreEx:Failed to read from or write to database. Refresh and try again. ' and is not creating the term sets. I updated the last 2 digits of the term set guid and the term set got created. Also in case I delete the term set from the SharePoint and try to update again then also it worked, not sure why it is not working for the defined IDs which I have from SharePoint 2013 site. Attaching screenshot for reference.

**Comment by nick-pape** [comment]
Hi there, looks like you are using PnP Powershell cmdlets for this task, would you mind refiling the ticket at:
https://github.com/pnp/powershell/

This repository is mainly focused on developer issues with respect to SPFx, Add-Ins, API's, etc.
