### ISSUE TITLE
Command Set localization does not work

### ISSUE THREAD

**Issue by martinlingstuyl** [SharePoint/sp-dev-docs#922]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When pointing the **id** property on the Command item object in the Command Set manifest to a localized string, the Command Set should use the localized string as button text. It should use the correct resource if a resource is available for that locale.

#### Observed Behavior
The Command Set does not use the localized string of the correct resource, it uses the default localization resource instead. (en-US)

#### Steps to Reproduce
1. Create a Command Set extension with the name CommandSetTest
2. in the manifest json file, swap the default property with the following id property: `"id": "$CommandSetTestCommandSetStrings:CommandSetTestCommandSetStrings.Command1;"`
as in the screenshot:
![image](https://user-images.githubusercontent.com/5267487/31442124-ab3dcd26-ae95-11e7-993e-e7a716c0fb61.png)
3. Add a resource file to the loc directory, for example: a nl-nl.js file with dutch values.
4. Run gulp serve --nobrowser
5. Check the temp/manifests.json file. It should contain the localization keys and values:
![image](https://user-images.githubusercontent.com/5267487/31442550-155cd836-ae97-11e7-8243-136bcf151764.png)

6. Debug the extension on a SharePoint site in the targeted language. It will show the default en-US text:
![image](https://user-images.githubusercontent.com/5267487/31442595-39d66cc2-ae97-11e7-9151-cbc15bbbd71c.png)

#### Origin of the issue:
In the file named **listview-host-assembly-[locale]_[hash].js** the Commands list is loaded from the spfx extension manifest. Unfortunately, while the manifest file contains the right keys and values, the default property is used to instantiate the Commands array:
![image](https://user-images.githubusercontent.com/5267487/31442669-6a620428-ae97-11e7-9796-3f47c23fb6bd.png)

**Comment by qz2017** [comment]
The fix is included in the next patch release. Thanks for reporting it.

**Comment by paulewert** [comment]
At Ignite 2017, I thought I saw an example of grouped commands, but I haven't been able to find any information on it and would have to spend hours going combing through the videos of the sessions I attended. It would appear from the code snippet provided by @martinlingstuyl that this would not be supported. Sure would be nice if it was. Anyone else know?

**Comment by martinlingstuyl** [comment]
What do you kwam my grouped commands? Like submenu’s?

**Comment by martinlingstuyl** [comment]
You could file it under a new issue though, that’s probably better. If you do mean submenu’s: that’s certainly not something I came across, though that doesn’t mean it isn’t possible. Nice feature it would be though!
I’ll close this issue down now.

**Comment by cwdata** [comment]
@martinlingstuyl Does this work for you now?
I'm experiencing the exact same issue that you have described here. Can anyone confirm that this patch has been installed in the meantime?

**Comment by martinlingstuyl** [comment]
Cannot confirm that it works, no. But I didn't have time to check thoroughly.

**Comment by cwdata** [comment]
In case anyone else stumbles upon this thread - I found another solution for this issue.
It is less efficient but very easy to use. You could set the title in the onListViewUpdated eventhandler:
```
@override
public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void {
    const command1: Command = this.tryGetCommand('COMMAND_1');
    command1.title = strings.Command1Title;
}
```
Like any other access to the strings class it will at runtime set the title with the matching language from the string resource.

**Comment by diabhoil** [comment]
I am still having this issue with german translations (SPFX 1.8). The manifest will ignore the translations and just show the default value.

@cwdata  answer will work, but that is just a work around.

**Comment by fonbrauzen** [comment]
> I am still having this issue with german translations (SPFX 1.8). The manifest will ignore the translations and just show the default value.
> 
> @cwdata answer will work, but that is just a work around.

The same thing on SP FX 1.10, according to [manual for web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts) should be used gulp serve --locale=de-DE, but despite I have both localized values in manifest and /loc/*.js files, without overwriting like was described by @cwdata, they're ignored from both places
