### ISSUE TITLE
URL with react hash router is not highlighted properly

### ISSUE THREAD

**Issue by christianteh** [SharePoint/sp-dev-docs#9220]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 15
- Node.js version 14

### Describe the bug / error

Adding multiple links to SharePoint navigation to directly access components through hash router ( for example default.aspx#/Order, default.aspx#/Invoice) will result in incorrect link being highlighted (compositeLinkIsSelected)

 

### Steps to reproduce

Add multiple URLs with hash on the same page:
default.aspx#/Order
default.aspx#/Invoice
default.aspx#/Report

go to default.aspx#/Order , the navigation will highlight default.aspx#/Report link

### Expected behavior

compositeLinkIsSelected is applied to correct link

**Comment by nick-pape** [comment]
Hi there, thanks for this report. Can you share more information about what you are doing here, e.g. where these links are being configured?
