### ISSUE TITLE
AAD Token can’t be validated on some tenants

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-docs#9223]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Linux

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : Edge, Chrome, Safari latest
- SPFx version: 1.13.0
- Node.js version: 14

### Describe the bug / error

We are using the AAD token that is generated by SharePoint Online Client extensibilty helper app in our SPFx code.

We send this code to our backend system. For the past 2 days, we are now unable to validate it for some tenants. 

It works fine for some tenants. The code suddenly started throwing this token invalid error.

### Steps to reproduce

The code to generate/retrieve the token is fairly standard SPFx way which is as below:

```
import { ServiceKey, ServiceScope } from '@microsoft/sp-core-library'
import { AadTokenProviderFactory } from '@microsoft/sp-http'

export class SB {
  public static serviceKey = ServiceKey.create<SB>(
    'SB',
    SB
  )

  constructor(private serviceScope: ServiceScope) { }

  public getAuthenticationToken = async (): Promise<string | undefined> => {
    try {
      const aadTokenProviderFactory = this.serviceScope.consume(AadTokenProviderFactory.serviceKey)
      const tokenProvider = await aadTokenProviderFactory.getTokenProvider()
      const accessToken = await tokenProvider.getToken(`https://${window.location.host}`, true)
      return accessToken
    } catch (err) {
      console.error(`[SB.getAuthenticationToken]: ${err}`)
      return undefined
    }
  }
}

```

The code works fine. 
However, suddenly since the past 2 days, there has been some change in the token retrieved.

The "newer" tokens now contains a `nonce` claim. This is only in some tenants not all and started around 11 PM CET.

So, in our backend where we validate the token , this started failing as we didn't expect this.

The backend where we validate the token is written in Kotlin. 

The SPFx webpart where we have this code is based on SPFx 1.13.0 , so the change has happened/is happening in Azure AD side I suspect

### Expected behavior

It turns out the JWT tokens containing a nonce field in the header cannot be verified as-is but the nonce value needs to be SHA-256 hashed, then URL-safe Base64-encoded and put back into the header instead of the previous `nonce`. Then the RS256 signature verification succeeds properly.

@VesaJuvonen  - as discussed opening the bug here, feel free to close it whenever you want since it is now resolved by a code change that we did.

Reference - https://xsreality.medium.com/making-azure-ad-oidc-compliant-5734b70c43ff and https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609

<img width="554" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/8832018/53a04744-3f0a-481f-bfb9-935252a4af82">

**Comment by Philluxx** [comment]
We could observe exactly the same behaviour. In some of our customer clients, a nonce claim was returned in the JWT header (not in the payload, where one would actually expect this).

This caused the JWT validation to fail. Other tools also reported an invalid token (e.g. jwt.io).

Since we also validate SharePoint tokens on our site, all tokens were rejected for the affected tenants. As a workaround, we have deactivated our validation of SharePoint tokens.

However, the nonce claim is now no longer returned for the affected tenants, which indicates that a rollback has taken place on the part of Microsoft?

I couldn't find any other information about a potential update, but this behaviour has led to very big problems on our side and with our customers.

**Comment by VesaJuvonen** [comment]
This issue has been mitigated earlier today and the impacted feature/piece of code is rolled back. Would love to get a confirmation from you both @gautamdsheth  and @Philluxx  if possible on the situation from your side.

This was caused a faulty piece of code which was not making the right assumptions in a specific underlaying feature. There's work done now internally to ensure that as the new feature will be rolling again - the impacted code is no longer there.

Thank you both for reporting this - as it helps enormously on detecting the issues and to understand the scale of the issues.

**Comment by Philluxx** [comment]
Hey @VesaJuvonen we can confirm that in the affected tenants the delivered JWTs no longer contain the "nonce" entry in the header. This means that a signature check is now successful again. Thank you very much for your information. It helps us with the subsequent evaluation of the situation.

Thanks again!

**Comment by gautamdsheth** [comment]
hi @VesaJuvonen , can confirm that the token doesn't contain `nonce` anymore. Thanks for acknowledging 🙏😊

**Comment by lucabandMSFT** [comment]
Everyone,
Although the nonce has been temporarily removed from the token, our plan is to start adding it back very soon (meaning in the next few weeks).
These changes in the SharePoint token are driven by new security improvements that we constantly introduce to ensure that our service is always up to date and has the latest and best possible security capabilities in place to protect from attacks that are constantly increasing all around internet. 
Introduction of nonce is just one of those improvements. In the future, you will see more and more hardening in the way we handle tokens and, generally speaking, artefacts from SharePoint used by SharePoint.

And that is the important part here: that token is supposed to be used by SharePoint from the client. It is not supposed to be sent to any different clients and be used there (to access SharePoint data or anything else).

If you need a proof of user authenticity on a middle tier, the right way to do that is to use the On Behalf Of flow as described here: [Microsoft identity platform and OAuth2.0 On-Behalf-Of flow - Microsoft Entra | Microsoft Learn](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow).
That would mean register an API in the middle tier so the client can ask for a token to access that middle tier FROM SharePoint (SPFx in this case), which can have very limited to no permission to the middle tier itself. Then, pass that token to the middle tier and initiate OBO flow there.

I’m going to close this GH issue.
