### ISSUE TITLE
Users retrieving different versions of the solution after an update for a certain time

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#9226]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SPFx
- > 1.16.1

Browsers
- Edge beta: 116.0.5845.187
- Chrome: 117.0.5938.92

### Describe the bug / error

For a while now, we have been experiencing issues when updating a solution on the app catalog and users retrieving older versions of the solution. 

Some users instantly retrieve the new version, while others are left with the older version for hours.

Example - User 1

<img width="786" alt="Xnapper-2023-09-22-16 29 21" src="https://github.com/SharePoint/sp-dev-docs/assets/2900833/e999b404-096c-40b1-a011-6fb06b9594cd">

Example - User 2

<img width="1057" alt="Xnapper-2023-09-22-16 30 18" src="https://github.com/SharePoint/sp-dev-docs/assets/2900833/dd32e458-c2c8-4d8d-85f8-597c64501ac1">

As you noticed, the two IDs are different for the loaded files. It happens at random, meaning that user 1 can retrieve the other file all of a sudden and, on the next refresh the old file.

It happens both with the CDN and without it.

### Steps to reproduce

1. Create a SPFx
2. Bundle and package it
3. Upload it to SP
4. Test it out on a page
5. Do an update and package it
6. Upload it and see if the issue occurs

### Expected behavior

Once the solution has been updated in the app catalog, I would like the files are updated for all instances at once.

**Comment by AJIXuMuK** [comment]
@estruyf - could you please share correlationId for both working and non working requests? Also would be nice if you could share the tenant url.

**Comment by estruyf** [comment]
Hi @AJIXuMuK thank you for looking into it.

It is happening on various tenants, but using the following to reproduce it: **involvstaging**

## User 1
Loads file: `involv-property-tagger-application-customizer_f34c797ce1f86115b22c.js`
Request ID: `112adea0-8009-7000-5793-73c9ab2b33be`

## User 2

Loads file: `involv-property-tagger-application-customizer_a572ffd5e169babd1eb7.js`
Request ID: `53f2dca0-80e8-7000-4fbb-f225cdb08663`

![Screenshot 2023-09-26 at 09 47 02](https://github.com/SharePoint/sp-dev-docs/assets/2900833/5876ef3e-12ed-424c-90c4-b00c6bb4f647)

Here is a video of a couple of refreshes where it loads the old file at the last refresh. This is what happens randomly. 

https://github.com/SharePoint/sp-dev-docs/assets/2900833/4cdc55c0-cc61-4e3f-acb2-acd218da9464

Also, when updating the files, the customer mentioned that the localization strings file could not be retrieved.

![Screenshot 2023-09-26 at 09 40 36](https://github.com/SharePoint/sp-dev-docs/assets/2900833/d2ace0b1-5a04-4a6b-8aee-859dff64663f)

**Comment by Ryan365Apps** [comment]
This started happening today for us and has occurred for several tenants for one of our SPFX web parts. I'm able to see specific files that are being requested, so I am manually creating those files and deploying them to our CDN. This is an effective workaround for now. I'm assuming these are older copies of the current js file or control strings file (seen both missing in some cases) but I don't know for sure.

**Comment by Ryan365Apps** [comment]
This is still a significant problem. We are seeing the localized strings files being affected across multiple customer tenants as well as the main solution files.
I'm really concerned about how this is going to impact future deployments. What is happening here?

**Comment by estruyf** [comment]
It is getting worse as it seems to take longer to provide the right files.

**Comment by AJIXuMuK** [comment]
@estruyf - sorry for the delay. 
Thanks for sharing the correlation ids. 
We're working on checking what's going on.

**Comment by AJIXuMuK** [comment]
@estruyf - could you also send the correlation Ids for the page load itself (both working and not working).
I need this because that's where the component's manifest with loader config is stored.

Thanks!

**Comment by estruyf** [comment]
Working page:

```
Request-Id: 26b6e2a0-40f9-7000-5793-7961136fdd89
```

Failing page:

```
Request-Id: 23b6e2a0-f036-7000-5793-7bff3c6faf6b
```

**Comment by AJIXuMuK** [comment]
Update: we have found the reason for the behavior.
There were some additional fixes needed that are still rolling out.
The issue should be fixed by end of the next week.

**Comment by AJIXuMuK** [comment]
The fix has rolled out worldwide
