### ISSUE TITLE
SPFX webpart loading the previous (older) version, instead of latest deployed version

### ISSUE THREAD

**Issue by hora** [SharePoint/sp-dev-docs#9228]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Browser versions
  - Chrome: 116.0.5845.179 (Official Build) (arm64)
  - Firefox: 117.0
- SPFx version: 1.16.0
- Node.js version: 16.13.2

## Context:

 - I am running a React app as a webpart
 - I am packaging a build using `gulp`, and deploying it in SharePoint under Apps for SharePoint
 - I log the version of the app in the console

## The problem

Twice now I've faced a strange issue when deploying a new build: when refreshing the app, I sometimes get the latest deployed version, other times I get the previously-deployed version. After a while (several days?) the problem seems to go away (or, at least no users have complained of seeing older versions).

If I get the older version and I try a hard refresh, the web part doesn't load my React app, instead I see the following error message directly in SharePoint:

![Screenshot 2023-09-19 at 10 09 47 AM](https://github.com/SharePoint/sp-dev-docs/assets/83366/40d42ba7-2621-41e8-8565-5ba95b187115)

## What I've tried

- What seemed to work last week, but did not work this week: Unregister Service Workers associated with the application, as well as clearing all site data
- Hard refreshes, emptying cache
- I tried redeploying, but that did not fix the issue either

### Steps to reproduce

1. Create a web part that points to a SPFX solution.
2. Create a new SPFX solution and publish it.
2. Browse to the app and check the version.
3. Refresh and check the version again.
4. May need to refresh multiple times.
5. After some refreshes I see the latest version (correct), other times I see an older version (incorrect).

### Expected behavior

I expect to always see the latest deployed SPFX solution.

**Comment by hora** [comment]
This seems to be related to #9226 , or maybe the same issue?

**Comment by AndhikaR** [comment]
Any update? happening to me as well and doing everything you listed

**Comment by mbice** [comment]
This feels like a similar issue to one we experienced last year #7664. Today, we noticed an issue where library components being loaded up using SPComponentLoader are loading up cached versions from other site collections, even if it's not installed on the site collection currently being browsed. Figuring it might be related to this issue..

e.g. 

1. Code running in an extension loads up a library component (installed in a site collection app catalog) using SPComponentLoader.
2. Navigate to a site collection where that library component is not even deployed.
3. Extension (which is installed in tenant app catalog) attempts to load it via SPComponentLoader and does NOT load the library component on a hard reload (not cached). This is expected.
4. Reload the page (cached) and the extension finds the library component from the previous site collection where it was installed and it loads up.

Feels like something in the cache allows the library component to be discovered on site collections where it's not even deployed/installed.

**Comment by kbeeveer46** [comment]
I submitted a ticket about this recently which has a lot of comments. I've dealt with it for 2+ years and pretty much given up and accepted that any time we publish to the tenant app catalog people won't start seeing the new version until the next day. I'm my tests, my SharePoint site was even loading apps that were 4 versions old.

https://github.com/SharePoint/sp-dev-docs/issues/8915

**Comment by hora** [comment]
Thanks @nbgyxi - the last time I saw the issue was the day I opened this ticket. That's not to say it's fixed, I just haven't deployed in the meantime.

**Comment by AndhikaR** [comment]
just deploy something today and the issue come again, sw=bypass cant fix this

**Comment by kbeeveer46** [comment]
We just uploaded a new version to our tenant and it's been 45 minutes and I still can't see the new version on any sites. Clearing cache, hard refresh, sw=bypass, trying a different computer, nothing helps... I don't understand why this isn't a big priority. We have 400 sites that are basically useless until the new version loads. Our clients are not happy.

**Comment by hora** [comment]
@kbeeveer46  - i am not planning a deploy this week, but i will also reply to @AJIXuMuK with the requested info when i can. if you have that info available to share, that would be appreciated!

**Comment by AJIXuMuK** [comment]
Update: we have found the reason for the behavior.
There were some additional fixes needed that are still rolling out.
The issue should be fixed by end of the next week.

**Comment by kbeeveer46** [comment]
Thank you. I'll keep an eye on in for our next release in 3 weeks. I didn't see your message in time to help with your last comment. All our sites are working fine now since enough time has passed. Sorry for being so frustrated. Sometimes we can't release in the middle of the night and the caching issues cause chaos when we have to release in the middle of the day.

Our application is fairly new so we make API changes almost every sprint to support new features. Any caching issues on the front end basically stop all sites from working if they all rely on an API that was changed.

**Comment by mbice** [comment]
@AJIXuMuK we are seeing an odd cache-based issue with SPComponentLoader and library components and I'm wondering if it could be related to this bug (and hopefully addressed by fixes rolling out).

We have an extension that runs globally on a tenant and it is configured to load library components **only if they are deployed into the current site collection app catalog**. When a page is cold-loaded (no cache) on a site collection where the library components are not deployed, SPComponentLoader correctly doesn't find them and they do not initialize. If we reload the page so it's a cached load, it will find the previously loaded instances of those library components from whichever site collection was last visited (where the lib components were actually deployed). It's as-if they are being put into cache and then loaded up anywhere else, even if they are not deployed there.

Thoughts?

**Comment by AJIXuMuK** [comment]
@mbice - it sounds unrelated. It sounds more like a client-side cache than manifests cache.

**Comment by mbice** [comment]
@AJIXuMuK I will do some more digging, but it looks like it's related to manifest retrieval (feels similar to this bug a while back https://github.com/SharePoint/sp-dev-docs/issues/7664). A quick trace of the code and what I'm seeing is that in the fetchManifests() function on fresh page load (no cache) it can't find any matching manifest for the library component (as expected because it's not in that site's app catalog).

![image](https://github.com/SharePoint/sp-dev-docs/assets/985283/b106cb1c-70a8-40a2-96dd-609573c3bf82)

Upon page reload the call to /_api/web/GetClientSideComponents has a different result payload and it includes a TON of additional manifests, including one for the library component that is from another site collection.

So for some reason the call to /GetClientSideComponents changes on cache vs no-cache load.

If you still believe it's not related to this particular manifest caching issue then perhaps I should open a new issue?

Thanks!

**Comment by kbeeveer46** [comment]
We just did another prod/tenant app catalog release and did not experience any caching issues this time. Every site we tested after release showed the new version immediately.

**Comment by hora** [comment]
We've done a couple of deployments the last week and we didn't see any problems either – it's looking like the issue is fixed! Thank you!
