### ISSUE TITLE
Teams Multitab -> Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

### ISSUE THREAD

**Issue by Wagnerah** [SharePoint/sp-dev-docs#9236]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.18
- Node.js 16.16
- Chrome v106.0.5249.62

### Describe the bug / error

I have been following the "Creating multi-tab Microsoft Teams personal app with SharePoint Framework" [YouTube tutorial](https://www.youtube.com/watch?v=IGBKOreRu3M) from the Microsoft 365 Community channel and the tutorial on the [Docs](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions#developer-provided-microsoft-teams-app-manifest--package) and have run into the issue that the webparts deployed for the teams tabs aren't loading.

Giving me the following errors depending on the browser:
Chrome: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

This is my Teams APP Manifest.json:

{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "manifestVersion": "1.16",
    "packageName": "Concierge Cronos",
    "id": "c3c4b2f7-f6b8-4de9-b7e4-f924583cef3c",
    "version": "1.0.0",
    "developer": {
        "name": "Wagner Murilo Iaschitzki",
        "websiteUrl": "https://www.example.com.br",
        "privacyUrl": "https://www.example.com.br",
        "termsOfUseUrl": "https://www.example.com.br"
    },
    "icons": {
        "color": "8ec29e61-9c68-49b4-b73b-60891cda820e_color.png",
        "outline": "8ec29e61-9c68-49b4-b73b-60891cda820e_outline.png"
    },
    "name": {
        "short": "Concierge Cronos",
        "full": "Concierge Cronos"
    },
    "description": {
        "short": "Gerencie o seu dia de trabalho sem sair do Teams!",
        "full": "Gerencie o seu dia de trabalho sem sair do Teams!"
    },
    "accentColor": "#004578",
    "staticTabs": [{
            "entityId": "100001",
            "name": "Meu Dashboard",
            "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={8ec29e61-9c68-49b4-b73b-60891cda820e}%26forceLocale={locale}",
            "websiteUrl": "https://www.example.com.br",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "100002",
            "name": "Meu RH",
            "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={d9038403-0336-488f-8a5e-bd3bd9318398}%26forceLocale={locale}",
            "websiteUrl": "https://www.example.com.br",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "100003",
            "name": "Configurações",
            "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId={e02a3abc-82f0-4cff-bdca-f50bb96a414d}%26forceLocale={locale}",
            "websiteUrl": "https://www.example.com.br",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "{teamsitedomain}",
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "spoprod-a.akamaihd.net",
        "resourceseng.blob.core.windows.net"
    ],
    "webApplicationInfo": {
        "resource": "https://{teamSiteDomain}",
        "id": "00000003-0000-0ff1-ce00-000000000000"
    }
}

### Steps to reproduce

1. Generate a SPFx project with the yeoman generator
2. Set up to basic webparts to use for the test
3. Follow either tutorial to deploy the app into teams

### Expected behavior

The webparts load successfully in the teams personal app tabs

**Comment by Wagnerah** [comment]
I have a complement, in my Teams App, when i change between tabs an error is raised in developer tools, as follow:

![image](https://github.com/SharePoint/sp-dev-docs/assets/48843844/c8472ffe-44f0-40fd-9055-840e3e653d7f)

**Comment by nick-pape** [comment]
Hi there, apologies for delay. Would you be able to provide more information here? The error above seems to be related to angular.

Would you be able to get a screenshot/callstack of the: `Chrome: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')` error?

Lastly, would it be possible to provide more specific repro steps and/or a minimal repro repo that we can investigate?
