### ISSUE TITLE
Something went wrong on deployed, but working normally on local workbench

### ISSUE THREAD

**Issue by AndhikaR** [SharePoint/sp-dev-docs#9237]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
Google Chrome 116.0.5
- SPFx version
1.17.4
- Node.js version
16.20.3
- etc
Package json
{
  "name": "projectname-sharepoint-frontend",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=16.13.0 <17.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "tslib": "2.3.1",
    "@microsoft/sp-core-library": "1.17.4",
    "@microsoft/sp-component-base": "1.17.4",
    "@microsoft/sp-property-pane": "1.17.4",
    "@microsoft/sp-webpart-base": "1.17.4",
    "@microsoft/sp-lodash-subset": "1.17.4",
    "@microsoft/sp-office-ui-fabric-core": "1.17.4"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.5.0",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.17.4",
    "@microsoft/eslint-config-spfx": "1.17.4",
    "@microsoft/sp-build-web": "1.17.4",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "gulp": "4.0.2",
    "typescript": "4.5.5",
    "@microsoft/sp-module-interfaces": "1.17.4",
    "@fluentui/react": "^7.199.1"
  }
}

### Describe the bug / error

Loaded component showing something went wrong, when first time uploading it works normally, when i updated the version it behave like this, but on local workbench, the webpart works well
<img width="1346" alt="Screenshot 2023-09-26 at 09 45 20" src="https://github.com/SharePoint/sp-dev-docs/assets/16699426/db1f3bc0-24b5-4dca-b6b4-96fb6625149a">

### Steps to reproduce

1.Deploy sppkg on apps for sharepoint
2.Adding webpart to the page
3.Error showup

### Expected behavior

Error something went wrong etc

**Comment by nick-pape** [comment]
Hi there, would it be possible to look in the console log to see if any errors are being written?

It looks like this is an issue within the script that is being uploaded. Would it be possible to share a minimal repro repo for this issue?
