### ISSUE TITLE
Invalid paths to JSON schema files

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#924]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The `./.vscode/settings.json` file refers to valid JSON schema files.

#### Observed Behavior
The `./.vscode/settings.json` file specifies invalid paths to JSON schema files.

#### Steps to Reproduce
Using the SPFx generator v1.3.2:

Create a new onprem project (default values for all prompts):
- open the `./.vscode/settings.json` file
- the file refers to `./node_modules/@microsoft/sp-build-core-tasks/lib/configJson/schemas/config-v1.schema.json`, which doesn't exist. Instead it should be pointing to: `./node_modules/@microsoft/sp-build-web/lib/schemas/config.schema.json`

Create new online project (default values for all prompts):
- open the `./.vscode/settings.json` file
- the file refers to:
  - `./node_modules/@microsoft/sp-build-core-tasks/lib/configJson/schemas/config-v1.schema.json` instead of `./node_modules/@microsoft/sp-build-core-tasks/lib/configJson/schemas/config.1.0.schema.json` (different file name)
  - `/node_modules/@microsoft/sp-build-core-tasks/lib/copyStaticAssets/copy-static-assets.schema.json` which doesn't exist

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
