### ISSUE TITLE
Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer error that occurs randomly.

### ISSUE THREAD

**Issue by mohammadamer** [SharePoint/sp-dev-docs#9242]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 117.0.2045.41 (Official build) (64-bit)
- SPFx version: 1.14.0
- Node.js version: v14.17.0

### Describe the bug / error

The extension idea is to render components in the SharePoint Online Search Page. One of the components, is a custom breadcrumb component that has a dropdown menu to switch between the SharePoint intranet hub sites. By switching between hubs, we change the search URL to search for the same keyword in the selected hub site.

It works fine however randomly it raises error in the browser console:
Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer. Error information is 'w.render is not a function'.
The error is occurring randomly when using the new rendered component (switching between hubs to search different hubs) by the SPFx extension.

Note: Sometime reloading the page helps to get the estension working again and rendering the components properly.

**Errors screenshots:**
Uncaught (in promise) Error: Failed to create application customizer 'ClientSideExtension.ApplicationCustomizer.12345678-1234-1234-1234-12345678'. Error information is '**w.render** is not a function'.

customized-search-application-customizer_e80b452eb94107361745.js:2  An error occurred in addSearchPageMainHeader: TypeError: **hn.render** is not a function.

![image](https://github.com/SharePoint/sp-dev-docs/assets/19314043/4205d931-c694-4479-9a2a-54bd9d445025)

**Uncaught (in promise) TypeError: hn.render is not a function.**
![image](https://github.com/SharePoint/sp-dev-docs/assets/19314043/8c3c430b-6a98-4a4f-b2ec-e98bb28a110f)

**An error occurred in addSearchResultCount: TypeError: hn.render is not a function.**
![image](https://github.com/SharePoint/sp-dev-docs/assets/19314043/db87f9aa-3a41-4595-a037-6f43aad08d58)

**Uncaught (in promise) TypeError: hn.render is not a function.**
![image](https://github.com/SharePoint/sp-dev-docs/assets/19314043/3520b3b7-0714-4c0e-8fe9-0a8ba17c3aee)

### Steps to reproduce

1. The errors occur randomly after switching multiple times between hubs to search different hubs for the same keywork.
2. The steps to reproduce could be by rendering a component that would enable you to change the search URL to search different hub sites in the SharePoint online search page.

### Expected behavior

The expected behavior is to have the extension working properly without getting random errors.

**Comment by nick-pape** [comment]
Is the error happening in your code or in PnP library code (or SPFx code -- doesn't appear to be SPFx)?

**Comment by mohammadamer** [comment]
Hi Nick,

Yes, I'm still having the same issue and I don't have any ideas what could be done to fix the issue.
The source code should not be shared as you know it's my organization source code.

Regarding minimal repo, it not easy as the issue has been raised after my big change to implement the latest requirements and before my changes, I didn't get such issue.

**Comment by mohammadamer** [comment]
Hi Nick,

You can close this issue as it turned out that another SPFx extension is causing this issue.
Thanks for helping.
