### ISSUE TITLE
ERROR in Cannot read properties of undefined (reading 'getFirstToken')

### ISSUE THREAD

**Issue by jeanfgagnon** [SharePoint/sp-dev-docs#9245]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

windows 10

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version Version 117.0.5938.92 (Official Build) (32-bit)
- SPFx version  1.18
- Node.js version 18.18
- spfx-fast-serve-helpers:  ~1.18.1,

### Describe the bug / error

npm run serve works
gulp serve works 

Problem arise when I save a .tsx file and I have this error message:

i ｢wdm｣: Compiling...
× ｢wdm｣: Time: 205ms
Entrypoint sp-qms-doc-web-part = sp-qms-doc-web-part.js

ERROR in Cannot read properties of undefined (reading 'getFirstToken')
Occurred while linting C:\Local\Dev\SPFx\sp-qms-doc\src\webparts\spQmsDoc\components\Customizer.tsx:45
i ｢wdm｣: Failed to compile.
No issues found.

Immediatly after this I go on a .ts which export an interface, hit ctrl-s on this unchanged file and voila, it works.

Issue occured when I pulled an old branches which has a lot of conflicts.  Conflicts were all fixed.  

I've also installed a full .zip backup taken before the branch merge and even this version now has the same problem.  It looks like is something global in my machine that is broken.
[package - json.txt](https://github.com/SharePoint/sp-dev-docs/files/12740907/package.-.json.txt)

### Steps to reproduce

1.  I don't know how to reproduce the glitches chain, otherwise I would just backtrack a bit until error is gone.
2.
3.

### Expected behavior

No error and workbench containing web-part should just reload with updated code

**Comment by nick-pape** [comment]
Unfortunately, this seems to be a limitation of the file change watching utility. In the future, it might be best to restart serve after doing a merge.

Also do you have custom build steps? `wdm`?

**Comment by jeanfgagnon** [comment]
Hi

No custom build steps.  I've fixed the problem by redoing my package.json with version from a working web-parts. Anyhow, some dependencies went south.
Thx
