### ISSUE TITLE
Unable to load JSOM files using SPComponentLoader in SPFX Application Customizer 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#925]
#### Category
- [ ] Question

I am trying to load the JSOM files in SharePoint Framework extension using SPComponentLoader but I am getting the below error : 

Any idea? 

Error: **Unknown error when loading module "https://mytenant.sharepoint.com/sites/dev/_layouts/15/init.js"**

![snip20171012_2](https://user-images.githubusercontent.com/21008316/31509142-144df614-af46-11e7-9222-5efda475a792.png)

**Note**: The external reference and require approach works.

**Comment by sprider** [comment]
@waldekmastykarz Any suggestions?

**Comment by russgove** [comment]
Have you tried this:
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md

**Comment by thomblweed** [comment]
I am experiencing the same issue. For a site level Application Customizer, following the **Imperative** approach from the guidance, only works when viewing pages and not when viewing lists.  The external **Declarative** approach resolves it but it is not ideal.

**Comment by waldekmastykarz** [comment]
@sprider Have you tried using the same approach in a web part? Just trying to determine if this has to do with the component type (Application Customizer) or the specific version of the SharePoint Framework.

**Comment by sprider** [comment]
@waldekmastykarz It is working in WebParts but not with Application Customizer. As @thomblweed mentioned, I am using Declarative approach to resolve this.

**Comment by waldekmastykarz** [comment]
@sprider the problem with the declarative approach is, that it breaks on classic pages where JSOM is already present. Being able to load it imperatively is required whenever you want your web part to work on both classic and modern pages.

**Comment by sprider** [comment]
Sure @waldekmastykarz. Thank you.

**Comment by Saulius-Laurinaitis** [comment]
Hi  @waldekmastykarz , I have tried with both: extension and web part in one page and it works correctly using SPComponentLoader, but it does not work in modern pages like Site Contents or list view (but works on custom modern site page), and I'm getting exception:
Uncaught (in promise) Error: Unknown error when loading module "/_layouts/15/init.js"
    at e._requireLoadForDifferentVersion (listview-host-assembly_en-us_215dd0d4594aa258debfba42f5d70c95.js:281)
    at e._handleRequireJsError (listview-host-assembly_en-us_215dd0d4594aa258debfba42f5d70c95.js:281)
    at b.errback (listview-host-assembly_en-us_215dd0d4594aa258debfba42f5d70c95.js:281)
    at require-951f856e.js:1
    at require-951f856e.js:1
    at each (require-951f856e.js:1)
    at b.emit (require-951f856e.js:1)
    at require-951f856e.js:1
    at each (require-951f856e.js:1)
    at c (require-951f856e.js:1)

**Comment by Saulius-Laurinaitis** [comment]
I have actually resolved with very strange fix - adding catch, looks like files are loaded by OOTB modern pages:

         `SPComponentLoader.loadScript('/_layouts/15/init.js', {
            globalExportsName: '$_global_init'
          }).catch((error) => {
            
          }).then((): Promise<{}> => {
            return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
              globalExportsName: 'Sys'
            });
          }).catch((error) => {
            
          }).then((): Promise<{}> => {
            return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
              globalExportsName: 'SP'
            });
          }).catch((error) => {
            
          }).then((): Promise<{}> => {
            return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
              globalExportsName: 'SP'
            });
          }).catch((error) => {
            
          })`

**Comment by DaniCorretja** [comment]
I'm getting exactly the same error than @Saulius-Laurinaitis but for some reason your fix (adding catch) is not working for me. Any other suggestions? Thanks!

**Comment by thomblweed** [comment]
Just to reiterate @DaniCorretja, I have tried adding catch also with no luck.

**Comment by Saulius-Laurinaitis** [comment]
Tthis is what I actually have and I'm only running my code after this promise resolve.

var scriptPromise = new Promise((resolve, reject) => {
            Stars.Const.spScriptPromise = SPComponentLoader.loadScript('/_layouts/15/init.js', {
              globalExportsName: '$_global_init'
            }).catch((error) => {
            }).then((): Promise<{}> => {
              return SPComponentLoader.loadScript('/_layouts/15/MicrosoftAjax.js', {
                globalExportsName: 'Sys'
              });
            }).catch((error) => {
            }).then((): Promise<{}> => {
              return SPComponentLoader.loadScript('/_layouts/15/SP.Runtime.js', {
                globalExportsName: 'SP'
              });
            }).catch((error) => {
            }).then((): Promise<{}> => {
              return SPComponentLoader.loadScript('/_layouts/15/SP.js', {
                globalExportsName: 'SP'
              });
            }).catch((error) => {
            }).then(() => {
              resolve();
            });
          });

**Comment by knalbandianbrightgrove** [comment]
@waldekmastykarz 

Hi, any updates? I'm facing to similar issue.

1. Deployed extension solution
2. Run serve nobrowser

Got https://www.screencast.com/t/8JqO4kgZK errors in console 404 to get `microsoft/sp-loader.js`

Please advise

**Comment by harshdamaniahd** [comment]
For resolving the above issue on both classic and modern page , which includes ribbon not editable
is ..
I have created two functions , one loads taxonomy and other loads other scripts like sp.js and sp.runtime js
 public loadSPTaxonomy() {
    return new Promise((resolve, reject) => {
      SPComponentLoader.loadScript("/_layouts/15/sp.taxonomy.js", {
        globalExportsName: "SP.Taxonomy"
      }).catch(error => {});
    });
  }
  public loadSPDependencies() {
    return new Promise((resolve, reject) => {
      SPComponentLoader.loadScript("/_layouts/15/init.js", {
        globalExportsName: "$_global_init"
      })
        .catch(error => {})
        .then((): Promise<{}> => {
          return SPComponentLoader.loadScript("/_layouts/15/MicrosoftAjax.js", {
            globalExportsName: "Sys"
          });
        })
        .catch(error => {})
        .then((): Promise<{}> => {
          return SPComponentLoader.loadScript("/_layouts/15/SP.Runtime.js", {
            globalExportsName: "SP"
          });
        })
        .catch(error => {})
        .then((): Promise<{}> => {
          return SPComponentLoader.loadScript("/_layouts/15/SP.js", {
            globalExportsName: "SP"
          });
        })
        .catch(error => {})
        .then((): Promise<{}> => {
          return SPComponentLoader.loadScript("/_layouts/15/sp.taxonomy.js", {
            globalExportsName: "SP.Taxonomy"
          });
        })
        .catch(error => {})
        .then(() => {
          resolve();
        });
    });
  }

Now when calling the function 
///Modern Page
    if (document.getElementById("MSOLayout_InDesignMode") == null) {
      this.loadSPDependencies().then(() => {
        this.loadCurrentUserInfo();
      });
    } else {
      //Classic Page
      if (document.getElementById("MSOLayout_InDesignMode")["value"] !== "1") {
        this.loadSPDependencies().then(() => {
   ///do other stuff
        });
      } else {
        this.loadSPTaxonomy().then(() => {
          //do whatever u wnat
        });
      }
    }
  }

Thus depending on type of page and mode of page , the above code works.


But still  i noticed one issue in classic page , the files sp.js and sp.runtime js are loaded twice.
This will hamper performance.
Any thing on this issue ?

**Comment by jsnl85** [comment]
Great find @saulius-laurinatis

**Comment by jsnl85** [comment]
Would it make sense to include a {TenantDomainName} token for this to work with the config.json file?

```
"externals": {
  "sp-init":{"path":"{TenantDomainName}/_layouts/15/init.js","globalName":"$_global_init"},
  "microsoft-ajax":{"path":"{TenantDomainName}/_layouts/15/MicrosoftAjax.js","globalName":"Sys","globalDependencies":["sp-init"]},
  "sp-runtime":{"path":"{TenantDomainName}/_layouts/15/SP.Runtime.js","globalName":"SP","globalDependencies":["microsoft-ajax"]},
  "sharepoint":{"path":"{TenantDomainName}/_layouts/15/SP.js","globalName":"SP","globalDependencies":["sp-runtime"]}
}

```

**Comment by andrewconnell** [comment]
Because this issue has been around for a long time & there have been multiple updates to SPFx since then, can you please confirm if it's still an open issue and if so, share some updated details on the SPFx version you've tested it in? I'm unable to repro with latest SPFx (v1.7.1)

**Comment by Saulius-Laurinaitis** [comment]
No issues on 1.7.0 as well
