### ISSUE TITLE
Personal App Crashes getting MSGraphClientV3

### ISSUE THREAD

**Issue by tpalacino** [SharePoint/sp-dev-docs#9266]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- [x] Legacy Teams thick client
- [x] New Teams thick client

### Describe the bug / error

Personal App attempts to get a MSGraphClientV3 from the webpart context and the app crashes. 

https://github.com/SharePoint/sp-dev-docs/assets/5368015/224a893c-9f8d-4924-a177-b367ad0c6bed

### Steps to reproduce

1. Create a new SharePoint Framework webpart
2. Configured it for Teams [according to the documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions)
3. Add code the utilizes the `MSGraphClientV3`
4. Build, bundle, & package the webpart
5. Upload the package to the SharePoint app catalog
6. Enable the app (make sure to "Add to Teams" is checked in this step
7. Run the app in the new Teams thick client experience

### Expected behavior

The `MSGraphClientV3` should be retrieved and the Graph call should be successful.

**Comment by nick-pape** [comment]
Error from the video:
<img width="543" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/5674316/46f432ce-70ca-4a90-8a31-50a28639b3ca">

**Comment by lucabandMSFT** [comment]
Providing an update here: We discovered a bug in New Teams and we are working on a fix. We hope the fix should be rolled out in the next two weeks. We will provide an update here as soon as we know the fix is available.

Unfortunately, in the main time, the only option is to temporarily revert back using Legacy Teams client.

**Comment by tpalacino** [comment]
> Providing an update here: We discovered a bug in New Teams and we are working on a fix. We hope the fix should be rolled out in the next two weeks. We will provide an update here as soon as we know the fix is available.
> 
> 
> 
> Unfortunately, in the main time, the only option is to temporarily revert back using Legacy Teams client. 

We actually discovered the issue as we were preparing to submit an app to AppSource. Definitely looking forward to the fix so we can enable it for teams and publish an update.

Thanks for the update.

**Comment by tpalacino** [comment]
@lucabandMSFT Is there any update you can provide here?

**Comment by tpalacino** [comment]
@lucabandMSFT I updated Teams today and this is no longer an issue.

<img width="339" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/5368015/e62f46a0-1424-42a9-975c-d0963fbaf58c">

**Comment by tpalacino** [comment]
https://github.com/SharePoint/sp-dev-docs/assets/5368015/13800b75-ae41-4f65-a1e4-9760418b1e27
