### ISSUE TITLE
CommandBar button is only usable after an explicit page reload (identical to #6290): The value for "domElement" must not be undefined

### ISSUE THREAD

**Issue by NinjaSciurus** [SharePoint/sp-dev-docs#9268]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

SharePoint Framework version: 1.4.1
Node.js version: 10.17.0
Google Chrom version: 117.0.5938.150
Microsoft Edge version: 119.0.2151.2

### Describe the bug / error

We have implemented several CommandBar buttons, packaged as a single ListViewCommandSet extension. They all inherit from the base class BaseDialog to display a custom dialog. Since about Oct 9 2023, if you visit one of our sites / doc libs and click on one of the buttons, the corresponding dialog does not open. Instead a message appears on the browser console:

listview-host-assembly_en-us_4eaecaa5e24a01d8756e667b8bb41ba0.js:3  Uncaught (in promise) Error: The value for "domElement" must not be undefined
    at e.isNotNullOrUndefined (listview-host-assembly_en-us_4eaecaa5e24a01d8756e667b8bb41ba0.js:3:183747)
    at e.get (listview-host-assembly_en-us_4eaecaa5e24a01d8756e667b8bb41ba0.js:74:530446)
    at new e (sp-dialog_none_a126ebbd6f28c7c7cb2e.js:1:38336)
    at Function.get (sp-dialog_none_a126ebbd6f28c7c7cb2e.js:1:38711)
    at e.show (sp-dialog_none_a126ebbd6f28c7c7cb2e.js:1:8347)
    at t.<anonymous> (dms-list-view-command-set_1e04919bbd80ba989615bb6010592e77.js:26:50566)
    at dms-list-view-command-set_1e04919bbd80ba989615bb6010592e77.js:26:38666
    at Object.next (dms-list-view-command-set_1e04919bbd80ba989615bb6010592e77.js:26:38771)
    at dms-list-view-command-set_1e04919bbd80ba989615bb6010592e77.js:26:37715
    at new Promise (<anonymous>)

Only a refresh of the page solves this - but loading the page twice is not an option for our customers.

### Steps to reproduce

Basically the same as in #6290.

Here is one of our simpler dialogs:
```typescript
import { BaseDialog, Dialog } from "@microsoft/sp-dialog";
import { override } from "@microsoft/decorators";
import {
    DefaultButton,
    PrimaryButton,
    DialogFooter,
    DialogContent,
    Spinner,
    autobind
} from 'office-ui-fabric-react';
import * as ReactDOM from "react-dom";
import * as React from "react";
import * as strings from 'GlobalSolutionStrings';
import ErrorDialog from "./ErrorDialog";
import OkCancelDialogContent from "./OkCancelDialogContent";
import { executeRequest } from "../../ApiRequests/ApiRequestExecutor";
import { HttpClientResponse } from '@microsoft/sp-http';
import { IClientSideComponentProperties } from "../../Models/IClientSideComponentProperties";
import { ExtensionContext } from '@microsoft/sp-extension-base';
import { IFindusResult } from "../../Models/IFindusResult";
import * as dialogStrings from 'DMSListViewCommandSetStrings';

export default abstract class OkCancelDialog extends BaseDialog {
    protected _cloudServiceBaseUrl: string;
    protected _cloudServiceClientId: string;
    protected _title: string;
    protected _okButtonText: string;
    protected _cancelButtonText: string;
    protected _errorClosesMainDialog: boolean;
    protected _showSpinner: boolean;
    protected _showError: boolean;
    protected _errorMessage: string;
    protected _errorObject: any;
    protected _contentComponent: OkCancelDialogContent;
    protected _reloadPageAfterOk: boolean;

    constructor(title: string, okButtonText: string, cancelButtonText?: string,  errorClosesMainDialog: boolean = true, reloadPageAfterOk: boolean = true) {
        super();
        this._title = title;
        this._okButtonText = okButtonText;
        this._cancelButtonText = cancelButtonText || strings.CancelButtonText;
        this._errorClosesMainDialog = errorClosesMainDialog;
        this._reloadPageAfterOk = reloadPageAfterOk;
    }

    /**
     * Put your submit code here. A spinner is shown while the promise is not yet resolved (or errors out).
     */
    protected abstract submit(): Promise<void>;

    /***
     * Action on Cancel Button click
     */
    @autobind
    protected cancel(): void {
        this.close();
    }

    protected abstract renderContent(): JSX.Element;

    @autobind
    protected renderErrorContent(error?: any): JSX.Element {
        let lines: string[] = [];

        lines.push(strings.UnexpectedErrorText);
        if (error) {
            if (typeof (error) === 'string') {
                const errorAsString = error as string;
                lines.push(...errorAsString.split('\n'));
            }
            else if (error instanceof Array) {
                lines.push(...error);
            }
        }

        if (lines.length === 1 && this._errorMessage) {
            lines.push(...this._errorMessage.split('\n'));
        }
        return (
            <div>
                {lines.map(line => <p>{line}</p>)}
            </div>
        )
    }

    @autobind
    protected renderAdditionalButtons(showSpinner: boolean): JSX.Element {
        return null;
    }

    @autobind
    protected async onErrorDialogClose(): Promise<void> {
        if (this._errorClosesMainDialog) {
            this.close();
        }
    }

    @autobind
    protected showErrorMessage(error?): void {
        if (this._contentComponent) {
            this._contentComponent.showError(() => this.renderErrorContent(error));
        }
        else {
            this._showError = true;
            this._errorObject = error;
        }
    }

    @autobind
    protected async okButtonClick(): Promise<void> {
        await this.submit()
            .then(() => {
                this.close();
                if(this._reloadPageAfterOk){
                    window.location.reload();
                }
            })
            .catch(error => {
                this.showErrorMessage(error);
            });
    }

    @override
    protected onAfterClose(): void {
        super.onAfterClose();
        // Clean up the element for the next dialog
        ReactDOM.unmountComponentAtNode(this.domElement);
    }

    @override
    public render(): void {
        if (this._showError) {
            //error occured before content could be rendered
            ReactDOM.render(

                <ErrorDialog
                    title={strings.ErrorDialogDefaultTitle}
                    content={() => this.renderErrorContent(this._errorObject)}
                    closeAction={this.close}
                    isSecondary={false}
                />
                , this.domElement
            );
        }
        else {
            ReactDOM.render(
                <OkCancelDialogContent
                    title={this._title}
                    okButtonText={this._okButtonText}
                    cancelButtonText={this._cancelButtonText}
                    submit={this.okButtonClick}
                    cancel={this.cancel}
                    content={this.renderContent}
                    additionalButtons={this.renderAdditionalButtons}
                    onErrorDialogClose={this.onErrorDialogClose}
                    ref={c => this._contentComponent = c}
                />
                , this.domElement
            );
        }
    }

    protected async issueApiRequest(url: string, payload: any, context: ExtensionContext, options: IClientSideComponentProperties) {
        const response: HttpClientResponse = await executeRequest(url, payload, context, options);

        if (!response.ok)
        {
            if (response.headers.get("Content-Type") === "application/json; charset=utf-8") {
                const findusResult: IFindusResult = await response.json();

                if (findusResult) {
                    this._errorMessage = `Findus error code: ${findusResult.ErrorCode} - ${localize(findusResult)}`;
                }
            }
            else {
                this._errorMessage = 'Status code ' + response.status;
            }
        }
        else if ((response as any).redirected && response.url.includes('?ErrorText='))
            this._errorMessage = decodeURIComponent(response.url.substring(response.url.indexOf('?ErrorText=') + 11));
        else
            this._errorMessage = undefined;

        if (this._errorMessage) {
            throw this._errorMessage;
        }
    }
}

function localize(findusResult: IFindusResult): string {
  let result: string;

  switch (findusResult.ErrorCode) {
    case 10000:
      result = dialogStrings.Archive.FolderIsEmptyText;
      break;
    case 10001:
      result = dialogStrings.Archive.FolderContainsTooBigFiles;
      for (const detail of findusResult.ResultDetails) {
          result += '\n ● ' + detail.Context;
      }
      break;
    default:
      result = findusResult.Message;
      for (const detail of findusResult.ResultDetails) {
          result += '\n ● ' + detail.Message + ': ' + detail.Context;
      }
      break;
  }

  return result;
}
```

This is our `package.json`:

```json
{
  "name": "quick-navigation",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "~1.4.0",
    "@microsoft/sp-application-base": "~1.4.0",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-dialog": "~1.4.0",
    "@microsoft/sp-listview-extensibility": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@pnp/common": "^1.0.1",
    "@pnp/logging": "^1.0.1",
    "@pnp/odata": "^1.0.1",
    "@pnp/sp": "^1.0.1",
    "@pnp/spfx-controls-react": "1.19.0",
    "@pnp/spfx-property-controls": "1.19.0",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1",
    "jsoncrush": "^1.1.6",
    "react-input-mask": "^2.0.4",
    "react-masked-text": "0.4.1",
    "react-native-text-input-mask": "^2.0.0",
    "react-text-mask": "^5.4.3"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/microsoft-ajax": "0.0.35",
    "@types/mocha": "2.2.38",
    "@types/sharepoint": "^2016.1.8",
    "ajv": "~5.2.2",
    "css-loader": "^3.2.0",
    "gulp": "~3.9.1",
    "raw-loader": "^4.0.2",
    "sp-pnp-js": "^3.0.4",
    "style-loader": "^1.0.0",
    "terser-webpack-plugin-legacy": "1.2.3",
    "webpack-merge": "4.2.1"
  }
}
```

### Expected behavior

I would expected the dialog to show instead of an exception.

**Comment by AJIXuMuK** [comment]
Thank you @NinjaSciurus for reporting it.
Sound like a regression - will be looking into it.

**Comment by AJIXuMuK** [comment]
@NinjaSciurus - I am unable to repro the issue with the simple test (attaching it for your reference).
[dialog-1-4-1.zip](https://github.com/SharePoint/sp-dev-docs/files/12897793/dialog-1-4-1.zip)
Could you please check if this solution is working on your end and check if there are differences with your solution?

Also, independently of the issue, I'd recommend to explicitly include React, ReactDom and office-ui-fabric-react packages as depedencies of your project.
Currently you're using shadow dependencies that can work unexpectedly.

**Comment by NinjaSciurus** [comment]
@AJIXuMuK Thank you for investigating. I will check the simple test first thing when I am back in the office on monday morning.

**Comment by NinjaSciurus** [comment]
@AJIXuMuK Here is our current status:

We found out that the error probability increases when you navigate into a subfolder of the current doc lib (our setup does not contain lists, our solution only runs on doc libs). This might be because only a partial page refresh happens and the `domElement` (selector is `div[data-sp-placeholder="DialogContainer"]`) might not be loaded correctly anymore. Still, we are not able to reproduce the issue in 100% of our tests but often enough so that it bothers our customer.

I followed your advice and explicitely included `react`, `react-dom` and `office-ui-fabric-react` in our project (for anyone finding this: a v1.4.1 SPFx solution needs `react` v15.6.2, `react-dom` v15.6.2 and `office-ui-fabric-react` v5.21). Please note that we never fiddled around with the content of the `package.json` manually and the original list was created by `yeoman` on initial project creation - to be fair, this was done years ago, so the explicit inclusions might have been missing then and could be fixed now (I did not check with a current version of `yeoman`). Interestingly, the simple test solution you uploaded also does not include the packages explicitely so I am unsure if this should be changed in `yeoman` or it is just a recommendation when things don't work in very special cases. Anyway, after building and deploying the new version, I have a really hard time to reproduce the issue - it might already be fixed and we need to test it now extensively.

I also deployed the simple test solution - it works fine (the button icon urls result in a HTTP 404 but that's irrelevant to this case). The main difference is that it's meant for lists and our solution works only on doc libs (`CustomAction.RegistrationId = 101`).

So I am a little unsure were we stand. I will test the updated solution thoroughly now and respond here if I find anything suspicious. For now, the issue seems to be fixed. Thank you for your help!

**Comment by AJIXuMuK** [comment]
Thank you @NinjaSciurus for all the information provided.

> Interestingly, the simple test solution you uploaded also does not include the packages explicitely

I did it for a purpose to align with your current solution as much as possible.

I will keep it open for a week or so if you find something else to share. 
Hopefully, you're unblocked!

**Comment by NinjaSciurus** [comment]
We haven't heard any further complaints from our customer - adding the react dependencies explicitely did indeed resolve the issue. Thanks again!
