### ISSUE TITLE
officeaddin folder missing after running command npm install @types/office-js --save-dev

### ISSUE THREAD

**Issue by rituranjan2002** [SharePoint/sp-dev-docs#9269]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
├──@microsoft/generator-sharepoint@1.18.0
├── bower@1.8.14
├── create-react-app@5.0.1
├── generator-office@1.9.7
├── gulp-cli@2.3.0
├── gulp@4.0.2
├── npm@9.7.1
├── touch-cli@0.0.1
├── yo@4.3.1
├── node js version: 18.18

### Describe the bug / error

unable to see officeAddin folder in spfx webpart created for outlook add-in

### Steps to reproduce

1.open visual studio code
2. Select project folder
3. open command prompt and run below command to setup environment "create environment npm install gulp-cli yo @microsoft/generator-sharepoint --global"
4.create spfx project "yo @microsoft/sharepoint --plusbeta"
5.install office "npm install @types/office-js --save-dev"

### Expected behavior

after step 4 :"npm install @types/office-js --save-dev" I  should see "officeAddin" folder in our project

**Comment by nick-pape** [comment]
Hi there, would you mind pointing to which documentation describes these steps.

Typically simply npm installing something will generally not add an additional folder to your package (other than in node_modules).
