### ISSUE TITLE
onPropertyPaneFieldChanged not triggered for custom property pane fields

### ISSUE THREAD

**Issue by ejazhussain** [SharePoint/sp-dev-docs#9283]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- **browser version**
Microsoft Edge - Version 118.0.2088.46 (Official build) (64-bit)
- **SPFx version**
1.16.1
- **Node.js version**
- 16.18.1
- etc

### Describe the bug / error

The **onPropertyPaneFieldChanged** function is not triggered for custom property pane fields. This means that developers cannot use this function to respond to changes in custom property pane fields.

### Steps to reproduce

1. Create a web part with a custom property pane field.
2. Add a handler for the **onPropertyPaneFieldChanged** event.
3. Change the value of the custom property pane field.

### Expected behavior

The **onPropertyPaneFieldChanged** event handler should be triggered on change of all the property pane fields out of the box or the custom property pane fields

**Comment by nick-pape** [comment]
Hi there, is this issue occurring with all custom property pane fields? 

Did you set the property pane to be non-reactive? If so, that function won't be called until the pane is closed: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/integrate-with-property-pane#handle-field-changes

**Comment by ejazhussain** [comment]
Hi @nick-pape I am going to do some tests tomorrow with different custom property panes, For example, custom property controls, PnP SPFx property control etc and out of the box one.

I will provide the feedback after my tests

**Comment by ejazhussain** [comment]
Hi @nick-pape, 

I have tried with both reactive and non-reactive property pane mode. As an example, I have created the following SPFx web part with a custom property pane [Async Dropdown Control]. 

https://github.com/ejazhussain/spfx-projects/tree/main/webparts/o365c-property-controls

Let me know if you need anything else from me

**Comment by nick-pape** [comment]
This may be an issue with PnP. Can you re-file this ticket there?

When defining a custom property pane field, the `changeCallback` parameter of `onRender` must be called on update. It looks like these components, e.g. `PropertyPaneAsyncDropdown` only specify a custom `onPropertyChange`, so you would need to manually call `onPropertyPaneFieldChanged` from there (after directly updating the property bag).

---

For this to be automatic, the custom component's `onRender` function needs to accept `changeCallback` from SPFx, and call it when it detects some sort of change in the cutom field:

https://github.com/ejazhussain/spfx-projects/blob/main/webparts/o365c-property-controls/src/common/controls/PropertyPaneAsyncDropdown/PropertyPaneAsyncDropdown.ts#L50C3-L50C46

e.g.
```
onRender: (
      domElementToMountTo: HTMLElement,
      context?: unknown,
      changeCallback?: (targetProperty?: string, newValue?: unknown) => void
    ) => {
```
