### ISSUE TITLE
Viva Card incorrect styles in Teams

### ISSUE THREAD

**Issue by SharePickle** [SharePoint/sp-dev-docs#9284]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams Dashboard
- SPFx version 1.18.0
- Node.js version 18

### Describe the bug / error

Viva Card in Teams Dashboard looks weird on mobile.
This happened before, not sure what and how to fix it.
Also not sure how to reproduce this consistently. Sometimes another updates solves it.
Card cache is disabled.

![image](https://github.com/SharePoint/sp-dev-docs/assets/32567749/28261a2e-6e99-4886-936e-1e72f45805f8)

### Steps to reproduce

1. Create SPFx Viva Card
2. Upload and install
3. Open Teams Dashboard on your phone

### Expected behavior

Styles should not be broken.

**Comment by SharePickle** [comment]
I can reproduce it by changing action type to
```ts
IExecuteCardAction
 { type: 'Execute' }
```

**Comment by nick-pape** [comment]
The issue here is that the button is blue and not picking up the dark theme?

This only happens with Execute action type? Does it happen with others, e.g. OpenUrl?

**Comment by SharePickle** [comment]
@nick-pape yes, correct. Other work fine.

**Comment by nick-pape** [comment]
Arte you able to provide a sample repository / SPFx component that reproduces this? I was having trouble reproducing it as well.
