### ISSUE TITLE
The graph api doesn't work when get tag in US Government High environment

### ISSUE THREAD

**Issue by jacobli12138** [SharePoint/sp-dev-docs#9290]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

other (enter in the "Additional environment details" area below)

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Graph v1.0
- Postman

### Describe the bug / error

The graph api doesn't work when get tag using app profile token in US Government High environment
App profile permision:
![app profile permission](https://github.com/SharePoint/sp-dev-docs/assets/148856632/e2649b7b-0a2a-4e72-a836-761d52b91394)
Response:
![response](https://github.com/SharePoint/sp-dev-docs/assets/148856632/a2274041-f6d2-4f0c-93c1-2a42704488f2)
If use service account delegate token, the issue can not reproduce

### Steps to reproduce

1. Get app profile token
2. Get tag using app profile token in US Government High environment
3. Return "BadGateway" error code

### Expected behavior

Return tag information

**Comment by nick-pape** [comment]
Hi there, looks like you are getting a bad gateway. As far as I can tell the `tags` api is only available under the `beta` API version. Can you try a base url of:

`https://graph.microsoft.us/beta/Teams/......./tags` ?
