### ISSUE TITLE
SPFX AadTokenProvider does not bring Roles when authenticating against API Hosted on Azure AD

### ISSUE THREAD

**Issue by danielcostalvt** [SharePoint/sp-dev-docs#9291]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

I have the following code on my web part:

```
`import { AadHttpClient, AadHttpClientFactory, AadTokenProviderFactory } from '@microsoft/sp-http';
const factory: AadHttpClientFactory = this.context.aadHttpClientFactory;
const client: AadHttpClient = await factory.getClient(AppSettings.clientId);
const tokenProviderFactory: AadTokenProviderFactory = this.context.aadTokenProviderFactory;
const tokenProvider = await tokenProviderFactory.getTokenProvider();
let token = null;
try {
  // Request the "roles" claim in the access token
  token = await tokenProvider.getToken(AppSettings.clientId);
} catch (e) {
  console.log(e);
} 
````

however, the returned token does not contain the custom permissions this app has on azure It has some app roles where we include the users and I'd like for them to be returned when callign the api as claims to facilitate role management App roles example on the app manifest:
`
"appRoles": [
        {
            "allowedMemberTypes": [
                "User"
            ],
            "description": "Viewers group",
            "displayName": "Viewers",
            "id": "225ba58e-cd21-43df-b25b-d60cd2c8e4f5",
            "isEnabled": true,
            "lang": null,
            "origin": "Application",
            "value": "Viewers.Group"
        },`

What am I missing here?

**Comment by nick-pape** [comment]
Hi there, are you cracking the token open? Generally they should not be parsed.

Have you tried making a request with this token? What response are you getting back from AAD?
