### ISSUE TITLE
broken node.js releases link

### ISSUE THREAD

**Issue by lordBrightLord** [SharePoint/sp-dev-docs#9296]
should be https://nodejs.org/en/download/releases but it is https://nodejs.org/en/about/releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nick-pape** [comment]
Thanks for bringing this up. I've opened a PR to fix the link.

**Comment by lordBrightLord** [comment]
Thanks,  but the link in the blue bootstrap alert is still broken
