### ISSUE TITLE
Turn on More Accessible Mode?

### ISSUE THREAD

**Issue by tombraman** [SharePoint/sp-dev-docs#9300]
I followed the instructions regarding turning on "more accessible mode" but was never able to find a link with that verbiage. It's not in the modern published Site Page that I looked at. Is "more accessible mode" for those who create/maintain Web pages? Or for users who visit/read Web pages? Is the "more accessible mode" link available in specific content types/document templates, or any? In either case, please provide thorough step by step instructions that work. This is especially critical considering that we are talking about optimizing accessibility. That I can't fully understand the instructions suggests that others may not be able to as well, preventing me (and possibly others) from doing our best to insure accessibililty. Thank you. - tom

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c9d3502-840f-c659-6474-de421b0c8013
* Version Independent ID: 7724a443-6396-acc7-d460-94fc2c968644
* Content: [Optimize SharePoint site accessibility](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/optimize-sharepoint-site-accessibility)
* Content Source: [docs/general-development/optimize-sharepoint-site-accessibility.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/optimize-sharepoint-site-accessibility.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nick-pape** [comment]
Hi there, this is correct, the "more accessible mode" is only available on legacy pages, but not on modern sharepoint pages. This feature was intended for readers of the page to use in cases where there were issues with regular screenreader applications. Other than that, for developer scenarios, I'd encourage you to take a look at https://learn.microsoft.com/en-us/sharepoint/dev/design/accessibility for some tips around accessibility with SPFx web parts. Also, in general, we do strive to make all our applications accessible, if you do notice issues with accessibility in out-of-the-box SharePoint experiences I'd encourage you to file UserVoice or other feedback. Hope this helps answer the question.
-Nick
