### ISSUE TITLE
Firefox's enhance tracking protection and Safari's cross-site tracking causes SharePoint sites to reload 10x on initial page load

### ISSUE THREAD

**Issue by kbeeveer46** [SharePoint/sp-dev-docs#9301]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [X] 💥 FireFox
- [X] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

We have many API calls on the home page of our SharePoint sites. When viewing a site using Safari and Firefox it reloads the page for every single API call. This means the page could reload 10 times. From what I understand, this is a "workaround" Microsoft put in place to get around browsers that block third party cookies. This has been in place for several years. When can we expect a permanent solution for this so we don't have to explain to our clients why their sites reload a bunch of times each time they visit it?

If you're reading this and experiencing the same issue here's a great article from 2021 that explains the issue and "hack/workaround" that causes the page to reload for every single API call https://www.blimped.nl/spfx-authentication-and-third-party-cookies/

**Comment by nick-pape** [comment]
Hi there,

Yes, we are aware of this. Also, most browsers are in place to have all 3rd party cookies blocked by the end of next year. We are actively taking steps right now to revamp the authentication flow to be compliant with 3rd party cookies and not require full page refreshes / auth flow. While I can't give a specific timeline, these changes should be rolled out everywhere by the middle of next year.
