### ISSUE TITLE
board-formatting.schema.json

### ISSUE THREAD

**Issue by JianniJ** [SharePoint/sp-dev-docs#9312]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33dfff5b-2b9e-94c7-ffa2-73719f49fb20
* Version Independent ID: 33dfff5b-2b9e-94c7-ffa2-73719f49fb20
* Content: [Format board view to customize SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-board-formatting)
* Content Source: [docs/declarative-customization/view-board-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/view-board-formatting.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by nick-pape** [comment]
Can you provide details of the issue here>
