### ISSUE TITLE
Gulp failed with error when running spfx webpart using azure pipeline

### ISSUE THREAD

**Issue by shawdowalker** [SharePoint/sp-dev-docs#9313]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Chrome  118.0.5993.118
- SPFx 1.17.2
- Node.js 16.20.1
- etc

### Describe the bug / error

I'm trying to deploy an spfx webpart automatically using Azure Pipelines, but when ever the build reaches the gulp script I get this error "##[error]gulp failed with error: The process '/usr/local/bin/gulp' failed with exit code 1"

This is the script I'm running:
`trigger:  
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0 
    displayName: 'Use Node 16.x'
    inputs:
      versionSpec: '16.x'

  - task: Npm@1
    displayName: 'Npm install packages'
    inputs:
      workingDir: '.'
    
  - task: Gulp@0
    displayName: 'Execute bundle gulp task'
    inputs:
      gulpFile: ./gulpfile.js
      targets: bundle
      arguments: '--ship'

  - task: Gulp@0
    displayName: 'Execute package-solution gulp task'
    inputs:
      targets: 'package-solution'
      arguments: '--ship'  

  - task: CopyFiles@2
    displayName: "Copy sppkg-file to artifact staging directory"
    inputs:
      Contents: |
        sharepoint/**/*.sppkg
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish staged artifacts"
    inputs:
      artifactName: "drop"`

can anyone help please?

### Steps to reproduce

1.Deploy the webpart into azure repos
2. Create a new pipeline with the script provided above 
3.Run the pipeline

### Expected behavior

The first 2 steps/script run successfully and then an error is shown once it reaches the gulp bundle script

**Comment by nick-pape** [comment]
Are you able to post the entire build log?

**Comment by shawdowalker** [comment]
> Are you able to post the entire build log?

No please just the first 2 tasks
