### ISSUE TITLE
Command Set not added

### ISSUE THREAD

**Issue by AndreasNorefalk** [SharePoint/sp-dev-docs#932]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Have created a command set extension that works fine on our dev tenant but not on another non-dev tenant. It targets a document libraries (RegistrationId 101). What could be wrong? Could it be that the spfx extension functionality hasn't rolled out to the non-dev tenant yet?

#### Observed Behavior

**Developer tenant:**

Javascript file loaded and onInit() function gets triggered. Command set working. Following messages displayed in console:

- Initialized ClientSideExtensionHelper
- Defined clientSidePlaceholders: DialogContainer,Top,Bottom
- Client-side host application loaded on SPO app
- Added 1 custom actions to RibbonList
- Added 1 custom actions to RibbonDoc
- Finished loading extensions for all custom actions

**Other non-dev tenant:**

Javascript file loaded but onInit() function doesn't get triggered. No 'Added...' message in console. No error messages displayed about the command set. The command set isn't available. Following messages displayed in console:

- Initialized ClientSideExtensionHelper
- Defined clientSidePlaceholders: DialogContainer,Top,Bottom
- Client-side host application loaded on SPO app

**Comment by AndreasNorefalk** [comment]
I've installed the command set on another non-dev tenant where it's working as expected. 

On the non-dev tenant where it isn't working the example command set from [Build your first ListView Command Set extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api) isn't working either. I can see that the custom action is returned from the _api/web/GetList(@a1)/CustomActionElements request and that the javascript file is loaded, but the command set buttons never appear in the UI.

Any ideas on what the problem might be? Is it possible that the GA release of extensions isn't available in the tenant or that it's blocked somehow? Is there a way to check this without adding an actual app/extension?

**Comment by AndersGEriksson** [comment]
If no one has an answer to the issue is there a prefered way to get support for this (maybe this is not the Place)?

**Comment by AndersGEriksson** [comment]
After Reading Another issue it is clear that this is because of undocumented limitations for command sets in modern lists/libraries in a Classic site that has publishing (https://github.com/SharePoint/sp-dev-docs/issues/945). Tested this and it works if you create a normal team-site but not if you try and use it on a publishing site. This issue can be closed and the other thread used instead.
