### ISSUE TITLE
SPFX ListViewCommandSet Buttons

### ISSUE THREAD

**Issue by warren-genpoint** [SharePoint/sp-dev-docs#9324]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint Add-ins

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Has anyone had this issue before.  We created some custom buttons ListViewCommandSet for a SharePoint list, which has been in production for over a year, and they used to render fine, but recently something has changed, and the buttons no longer render or do sort of render as seemingly defaulting to "Open in SharePoint.

This only happens when the users open the list within TEAMS, when running in native SharePoint Online, there is no issue.

SharePoint (Expected)
![image](https://github.com/SharePoint/sp-dev-docs/assets/27190729/9b770283-d44d-4e8b-b766-0468a3cb9d89)

Teams (Unexpected)
![image](https://github.com/SharePoint/sp-dev-docs/assets/27190729/a0ffaab5-1f83-4c9e-9d98-0cba9dc3b2eb)

**Comment by nick-pape** [comment]
Hi there, are the command sets not rendered in teams behind the `...` ellipses?

I think `Open in SharePoint` would be a built-in command, not the custom command.

**Comment by warren-genpoint** [comment]
> Hi there, are the command sets not rendered in teams behind the `...` ellipses?
> 
> I think `Open in SharePoint` would be a built-in command, not the custom command.

Hi - no, zero render, even behind the ...

**Comment by warren-genpoint** [comment]
Seems MS have fixed this silently :-)  All good.
