### ISSUE TITLE
A warning in the article states that the SharePoint Add-In model is going to be depricated, but does not state that CSOM is going to be deprecated. Are those terms synonymous? If not, is CSOM also going to be deprecated?

### ISSUE THREAD

**Issue by byronbennett** [SharePoint/sp-dev-docs#9351]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Service: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
There is no plans currently to depreciate CSOM - CSOM API surface is not the synonym for add-in model and will keep on being supported without any deprecation or end of life dates for now. We do recommend using Microsoft Graph APIs where suitable and keep on adding new APIs on that side. CSOM API surface is for example used by the SharePoint Online PowerShell module and there are no plans to deprecate these currently, so the add-in model deprecation will not impact these.
