### ISSUE TITLE
THIS PAGE TOTALLY SUCKS!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by dougweinberg** [SharePoint/sp-dev-docs#9370]
MICROSOFT DOESN NOT PROVIDE ANY EXAMPLES OF ARIA 
MIOCROSOFT SUCKS SUCKS SUCKS SUCKS IN DOCUMATATION AND PROVIDING WORKING EXAMPLES
I HATE THIS SOFTWARE COMPANY
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa6ae62-4dd8-3bdf-2f2c-f3f4a76e43b9
* Version Independent ID: 1aa6ae62-4dd8-3bdf-2f2c-f3f4a76e43b9
* Content: [Formatting syntax reference](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference)
* Content Source: [docs/declarative-customization/formatting-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/formatting-syntax-reference.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Unfortunately it's hard to provide any actual feedback or help with this kind of message. Providing a bit more details on what you are trying to achieve would give us an option to help or how you'd like us to improve the documentation. Since this does not however have needed details, closing it.
