### ISSUE TITLE
Adding a Group to a Site DOES change external sharing and exposes internal content :-(

### ISSUE THREAD

**Issue by kasperbolarsen** [SharePoint/sp-dev-docs#9386]
Hi Vesa,

I helped a customer groupifying 2000+ classic SharePoint Site Collections, and approx 80% did have "Only people in your organization" in the Sharing option.

After groupying the sites they had "New and existing guests" :-(

So I wonder what is correct, the article is correct and the groupify code is misbehaving, or the article is wrong?

How to test:
Create a new STS#0 orSTS#3 site, set the sharing to "Only people in your org" in the Admin center
Go to the site, select "Connect to new Microsoft 365 Group"
Go to the Admin center, check the sharing settings

Cheers

/Kasper

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f65999b-52d3-52dd-9bf6-559b2ec28817
* Version Independent ID: 919b0add-acbb-628e-7a7d-19b09a3d1f22
* Content: [External sharing after Microsoft 365 group connection](https://learn.microsoft.com/en-us/sharepoint/dev/transform/modernize-connect-to-office365-group-externalsharing)
* Content Source: [docs/transform/modernize-connect-to-office365-group-externalsharing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-connect-to-office365-group-externalsharing.md)
* Service: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by kasperbolarsen** [comment]
Just for Info: Vesa Juvonen has updated the documentation. The question remains: is it as per requirements that the Groupify code overwrites the Site Collection sharing setting? Are there additional documentation/articles out there getting this wrong?

**Comment by VesaJuvonen** [comment]
@kasperbolarsen  - we are checking this now from the owning feature crew and hopefully will have a definite answer soon. Thanks for flagging this.
