### ISSUE TITLE
Missing steps in the Lab Instructions

### ISSUE THREAD

**Issue by mgreasly** [SharePoint/sp-dev-docs#9394]
The lab jumps straight to Creating a Container in SPE (SharePoint Embedded) and says to use the Entra Client ID previously generated. But there's no instructions for that (either previously or following).

The web app and client instructions following instruct to navigate to the project folders already created. But there's no instructions on the page regarding creating/scaffolding the initial project - eg. for the front end we're straight into the npm install for the required packages but what/how was the initial project files created? Guessing at CRA for that? Backend is presumably an asp.net app?

It looks like there's a couple of the intial setup steps are missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Version Independent ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Content: [Hands on Lab - Setup & configure the SharePoint Embedded environment and web app project](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-03-hol)
* Content Source: [docs/embedded/mslearn/m02-03-hol.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/embedded/mslearn/m02-03-hol.md)
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by SimonSimCity** [comment]
Seems to be a duplicate of #9398

**Comment by mgreasly** [comment]
Yes, we've raised the same issue - the documentation isn't complete (or clear) here. Can close this and just track in 9398.
