### ISSUE TITLE
Adaptive Card Extension 1.18.2 Custom Property Controls Not Working

### ISSUE THREAD

**Issue by c-eiser13** [SharePoint/sp-dev-docs#9399]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: 120.0.6099.71
- SPFx version: 1.18.2
- Node.js version: 18.17.1
- etc

### Describe the bug / error

I've created a new 1.18.2 ACE and installed the latest version of @pnp/spfx-property-controls@3.15.1, and when including any control from this project in the property pane, the property pane is blank and the following error is logged in the console: TypeError: Cannot read properties of undefined (reading 'isInternal')

![image](https://github.com/SharePoint/sp-dev-docs/assets/42096464/a3736b6c-2edf-43ba-8f5d-25daf597097a)

![image](https://github.com/SharePoint/sp-dev-docs/assets/42096464/3a47a050-3844-4c8c-9b80-6d602d3bb91d)

I do not believe this is related to the controls in @pnp/spfx-property-controls. I added a custom property pane control that I created and use in a 1.18.2 web part project, and this property control generates the same error in the console.

I've also bundled and deployed this solution and I get the same error when using in the dashboard, so does not seem to be tied to the workbench.

The only property controls that work are those coming from @microsoft/sp-property-pane.

### Steps to reproduce

1. Scaffold a new 1.18.2 ACE
2. Install @pnp/spfx-property-controls@3.15.1
3. Use PropertyFieldMultiSelect in property pane, load workbench and attempt to edit the web part.

### Expected behavior

Custom property controls render when editing properties of an ACE.

**Comment by nick-pape** [comment]
Please re-file this ticket in the PnP Github, as it appears specific to PnP controls:

https://github.com/pnp/sp-dev-fx-property-controls

**Comment by c-eiser13** [comment]
@nick-pape thanks for your reply. I'm also able to repro this issue with a basic custom property pane control that I created and has no ties to the PnP reusable prop controls. This control works properly in a 1.18.2 web part project, it only fails in an ACE. This control simply renders a FluentUI text box that does icon selection. This control also produces the TypeError: Cannot read properties of undefined (reading 'isInternal') error. The only controls that do not produce this error are those coming from @microsoft/sp-property-pane
