### ISSUE TITLE
The setup process for SharePoint Embedded is not detailled

### ISSUE THREAD

**Issue by hervedorierai3** [SharePoint/sp-dev-docs#9406]
I'm new in SharePoint Embedded.
I'm following the Hands on Lab, and I had issues before be able to create my first container. I think that there are mission informations about the setup process such as : 
- The Azure Subscription must be linked with Syntex https://admin.microsoft.com/Adminportal/Home?#/featureexplorer/csi/ContentUnderstanding
- We need a SPA redirection URL
- The EntraID application must be consented

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Version Independent ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Content: [Hands on Lab - Setup & configure the SharePoint Embedded environment and web app project](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-03-hol?source=recommendations)
* Content Source: [docs/embedded/mslearn/m02-03-hol.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/embedded/mslearn/m02-03-hol.md)
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
These docs are now moved to the new location, so closing this from here - to avoid confusion. 

Valid finding and good feedback - will bypass to the owning team.
