### ISSUE TITLE
Variable name in the 'Add project global settings and constants' section

### ISSUE THREAD

**Issue by hervedorierai3** [SharePoint/sp-dev-docs#9408]
There is no CLIENT_DOMAIN constant in the  './.env' and './src/common/constants.ts'  files.
I assumed that is the CLIENT_SERVER_URL ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Version Independent ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Content: [Hands on Lab - Setup & configure the SharePoint Embedded environment and web app project](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-03-hol?source=recommendations)
* Content Source: [docs/embedded/mslearn/m02-03-hol.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/embedded/mslearn/m02-03-hol.md)
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
These docs are now moved to the new location, so closing this from here - to avoid confusion. 

Valid finding and good feedback - will bypass to the owning team.
