### ISSUE TITLE
SPLoaderError.LoadComponent error

### ISSUE THREAD

**Issue by NewJ123** [SharePoint/sp-dev-docs#941]
#### Category
- [ ] Bug

#### Expected or Desired Behavior
Gulp-serve loads the webpart in workbench 

#### Observed Behavior
Webpart doesn't load, workbench keeps loading spinner gif 

Refer attached screenshot of the error, same code was working a couple of days ago. 
![spfxwebparterror](https://user-images.githubusercontent.com/32855769/31640658-db363d00-b29c-11e7-8614-d2843008963b.PNG)

**Comment by waldekmastykarz** [comment]
This is a generic error, that can be caused by something wrong with your code. Have you checked the browser console to see if there are any errors?

**Comment by NaveenJ123** [comment]
This code was working few days ago and all of a sudden getting this error. There is absolutely no change in code.

**Comment by waldekmastykarz** [comment]
@NewJ123 are you using a lockfile in your project? If not, it could be as well one of the underlying dependencies having changed. Without any details, it's impossible to tell what's wrong.

**Comment by mpasarin** [comment]
Hi @NewJ123 , there are a few things we could try to scope the problem.
* Can you try with the local workbench? When running `gulp serve` the local workbench should open. The callstack that I'm seeing in the screenshot refers to the SPO workbench.
If it works in the local workbench, there might be a problem in the SharePoint side with a recent update.
* Do you see your script being downloaded? You can check that from the network tab in the F12 dev tools.
If you can't see it, there may be a problem with either the manifest or accessing the URL.
* If the script is downloaded, can you put a breakpoint in your script? Is it getting executed?
If we reach that point, the most probable cause is a problem within the script.
* Do you get any error in the browser console? There may be some relevant information there.

**Comment by NewJ123** [comment]
Thanks @mpasarin , yes it works in local workbench, i found similar issue reported here: https://techcommunity.microsoft.com/t5/SharePoint-Developer/Something-went-wrong-error-SPFX-React-Script-Editor/td-p/93929 and if i remove below external reference of sp-pnp-js from config file it starts working:
"externals": {
    "sp-pnp-js": "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.2/pnp.min.js"
  },

**Comment by NewJ123** [comment]
This was caused by SPFx update in the tenant, i worked with the IT to rollback the update which fixed the issue. Appreciate your help here.
