### ISSUE TITLE
Unable to get the property values of the images in the Image column

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9411]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

At some point, the images in the Image field started getting saved from SiteAssets to the Attachments of the item. 
![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/a2bd02dd-8188-4f77-abea-1479f7518435)

According to [the documentation](https://learn.microsoft.com/sharepoint/dev/declarative-customization/formatting-syntax-reference), it is mentioned that values for the image field properties such as fileName, Id, and serverRelativeUrl can be retrieved.
![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/56a251e6-1949-4fc1-9104-11e47e2f54d8)

However, I've encountered an issue where I can retrieve the fileName of the image stored in the item's Attachments, but not the other properties like id, serverRelativeUrl, or serverUrl. I can successfully retrieve id, serverRelativeUrl, and serverUrl values for images stored in SiteAssets.

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/2a78d6cd-8a3b-4e19-bf36-4c29d833f168)

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/fc1dc446-7264-4b9f-a767-bf0787a8aa75)

Is this a bug and will it be possible to get property values other than fileName in the future? Or will it not be possible to get property values other than fileName in the future?

### Steps to reproduce

1. Create a list
2. Create an image column whose internal column name is `Image`
3. Create an item that includes an image in the image column
4. Create a single line text column
5. Apply the following Sample Code to the column formatting created in step 4

<details>
<summary>Sample Code (Click to open/close) </summary>

``` json 
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "div",
      "style": {
        "display": "flex",
        "flex-direction": "column"
      },
      "children": [
        {
          "elmType": "div",
          "children": [
            {
              "elmType": "span",
              "txtContent": "fileName: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.fileName]"
            }
          ]
        },
        {
          "elmType": "div",
          "style": {
            "color": "red"
          },
          "children": [
            {
              "elmType": "span",
              "txtContent": "id: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.id]"
            }
          ]
        },
        {
          "elmType": "div",
          "children": [
            {
              "elmType": "span",
              "txtContent": "serverRelativeUrl: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.serverRelativeUrl]"
            }
          ]
        },
        {
          "elmType": "div",
          "style": {
            "color": "red"
          },
          "children": [
            {
              "elmType": "span",
              "txtContent": "serverUrl: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.serverUrl]"
            }
          ]
        },
        {
          "elmType": "div",
          "children": [
            {
              "elmType": "span",
              "txtContent": "thumbnailRenderer.spItemUrl: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.thumbnailRenderer.spItemUrl]"
            }
          ]
        },
        {
          "elmType": "div",
          "style": {
            "color": "red"
          },
          "children": [
            {
              "elmType": "span",
              "txtContent": "thumbnailRenderer.fileVersion: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.thumbnailRenderer.fileVersion]"
            }
          ]
        },
        {
          "elmType": "div",
          "children": [
            {
              "elmType": "span",
              "txtContent": "thumbnailRenderer.sponsorToken: "
            },
            {
              "elmType": "span",
              "txtContent": "[$Image.thumbnailRenderer.sponsorToken]"
            }
          ]
        }
      ]
    }
  ]
}
``` 

</details>

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/7e1bc6b8-af33-4e7d-90b7-cf99a773d65a)

### Expected behavior

The property values of images stored in the item's Attachments can also be retrieved.

**Comment by tmax-siva** [comment]
Hi tecchan,
Am also facing similar issues in recent days.
I've posted my question in different place as well.

https://learn.microsoft.com/en-us/answers/questions/1463565/sharepoint-online-list-image-column-is-not-returni

you can also take a look from this URL.

**Comment by remar27** [comment]
We're encountering the same issue, which we only began noticing this week. Due to these recent "undocumented" changes, our product has stopped functioning. It's unable to locate the image anymore since it's stored in item attachments and there is no longer image server relative URL available...

**Comment by tmax-siva** [comment]
Any update on this issue? Due to this issue, many of our production solutions were stopped working. We need a quick support on this guys.
Thanks in advance.

**Comment by tmax-siva** [comment]
You can find the solution for this issue here

https://learn.microsoft.com/en-us/answers/questions/1463565/sharepoint-online-list-image-column-is-not-returni

**Comment by tecchan1107** [comment]
Thanks for letting me know!

However, I consider it a bug if it doesn't work as per [the written documentation](https://learn.microsoft.com/sharepoint/dev/declarative-customization/column-formatting) , no matter where it is stored. Also, disabling attachments is very risky because it will delete all attachments.

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/766d6b5e-b7be-4dd3-a17b-0dc4ce14e3e5)
