### ISSUE TITLE
SharePoint Embedded - Unable to create  new container using New-SPOContainerType command

### ISSUE THREAD

**Issue by ravikadri** [SharePoint/sp-dev-docs#9417]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version - Chrome V120.0.6099.71 
- Node.js version V18.19.0
- SPO management shell  version 16.0.24322.12000
-

### Describe the bug / error

I am trying to set up a new  SharePoint Embedded feature in my E3 Dev tenant. But I get the below error when I try to create the container. when I run the below command, I get the billing error.

New-SPOContainerType -ContainerTypeName "FirstContainerType" -OwningApplicationId "App ID" -AzureSubscriptionId $dummyGuid -ResourceGroup "Dummy" -Region "Dummy"

**Error message: 
_New-SPOContainerType : Container type creation failed as we failed to establish a billing relationship. Error:
{"error":{"code":"SubscriptionNotFound","message":"The subscription 'f61aaa6f**' could not be found."}}._**

I have E3( Developer tenant) associated with $150 Azure subscription.  I am following the article below. 
https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m01-05-hol#prerequisites

![RaviChandra_0-1703100638798](https://github.com/SharePoint/sp-dev-docs/assets/104390320/cf43445d-1c75-42d0-be26-61ac23332c21)
 

### Steps to reproduce

1. Enable the SharePoint Embedded admin center
2. Create an AAD app and grant the permissions mentioned as per the document
3. Create client secrets and certs and upload them to the AAD app created.
4. Install the latest SPO management shell
5. Create the container type using ps1 and the PowerShell window throws the error mentioned.

Referred article: https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m01-05-hol#prerequisites
the 

### Expected behavior

New-SPOContainerType  should create a new container. As of now, it throws below error.

"New-SPOContainerType : Container type creation failed as we failed to establish a billing relationship. Error:
{"error":{"code":"SubscriptionNotFound","message":"The subscription 'f61aaa6f**' could not be found."}}."

**Comment by andrewconnell** [comment]
When you run the command, I see you're using dummy values... 

- Is the `$dummyGuid` actually YOUR valid Azure subscription ID?
- The `-ResourceGroup` & `-Region` should be real values, not dummy values

If you want to try out a container type in a developer experience, you should use the flag `-TrialContainerType` instead of dummy values. REF 👉 https://learn.microsoft.com/en-us/sharepoint/dev/embedded/concepts/admin-exp/dev-admin#creation-of-container-types

**Comment by andrewconnell** [comment]
Good catch... fixing that now. I fixed that elsewhere, but not in this page. Thanks!
