### ISSUE TITLE
Changing modern page Author and Editor (via list item) is not reflected on the page's Author end ModifiedBy values

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-docs#9428]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

PnP.Core 1.10
.NET 6

### Describe the bug / error

(Note: first reported the behavior on [Twitter](https://x.com/h_ulbricht/status/1741938333607973109?s=20) and Vesa directed my here.)

When updating Author and Editor of a modern SharePoint page (via its **list item**), the updated values don't seem to be reflected in the `Author` and `ModifiedBy` properties of the page file retrieved by `GetFileByServerRelativeUrlAsync`.

Looking at the response via Fiddler shows the discrepancy:

![image](https://github.com/SharePoint/sp-dev-docs/assets/3469970/ba211d96-b5a9-4e56-af2a-b40708d5b0b5)

**Important note: updating Author and Editor from an end-user perspective DID WORK and can be seen in the browser when looking in the Site Pages library! It's just this API here that is (partially) returning the old values.**

### Steps to reproduce

1. In the browser, sign in to SharePoint Online as Alice ("alice@contoso.onmicrosoft.com")
2. Navigate to test site A
3. Disable minor versions on the Site Pages library (or updating Author/Editor won't work)
4. Create a modern page "alice.aspx" - this is our test page
5. Set up a console application that uses PnP.Core
6. Create a PnPContext `pnpCtx` for site A
7. Have a second account "bob@contoso.onmicrosoft.com" handy

Run this code:

```csharp
var bob = await pnpCtx.Web.EnsureUserAsync("bob@contoso.onmicrosoft.com");
var pageFile = (await pnpCtx.Web.GetPagesAsync("alice.aspx").ConfigureAwait(false)).FirstOrDefault();
var listItem = pageFile.PageListItem;
listItem["Author"] = new PnP.Core.Model.SharePoint.FieldUserValue(bob);
listItem["Editor"] = new PnP.Core.Model.SharePoint.FieldUserValue(bob);
await listItem.UpdateOverwriteVersionAsync();

// now look in the browser - the **Created by** and **Modified by** of the page should've changed from Alice to Bob

// now read the same page again and expect to see Bob there everywhere

var pageFile2 = await pnpCtx
    .Web
    .GetFileByServerRelativeUrlAsync(
    new Uri(pnpCtx.Uri.ToString() + "/SitePages/alice.aspx").AbsolutePath,
    p => p.UniqueId,
    p => p.Author,
    p => p.ModifiedBy,
    p => p.ListItemAllFields)
    .ConfigureAwait(false);

// now look at pageFile2.Author and pageFile2.ModifiedBy - they are still Alice, but should be Bob
```

### Expected behavior

I expect the page returned by `GetFileByServerRelativeUrlAsync` in above repro to return Bob as `Author` and Editor (`ModifiedBy`) of the page, not Alice.

**Comment by VesaJuvonen** [comment]
thx @heinrich-ulbricht for reporting this. Seems that you are using indeed normal CSOM/REST APIs to modify the pages item. Will share this forward with the engineering and we'll see what we can do here and where the issue is. This will is still slow, but trying to get things moving. Thx for sharing the finding.
