### ISSUE TITLE
SPFx webpart issue in Custom Master Page

### ISSUE THREAD

**Issue by JayakumarB** [SharePoint/sp-dev-docs#943]
I'm getting below error when I add the SPFx app Webpart in Sharepoint Online page with custom master page.

Uncaught Error: Multiple anonymous defines in module https://component-id.invalid/597e7384-2f7a-47bc-95c5-5cb62d43b058_0.0.1/hfHomePageStrings at l.eval [as reduceRegister_] (eval at (sp-classic-page-assembly_en-us_b80981cd18dbc8ee3c3917c9b8f6494e.js:471), :5:14395) at HTMLScriptElement.m (eval at (sp-classic-page-assembly_en-us_b80981cd18dbc8ee3c3917c9b8f6494e.js:471), :5:72)

**Comment by waldekmastykarz** [comment]
Could it be that one of the customizations included in the Master Page interferes with your web part?

**Comment by VesaJuvonen** [comment]
@JayakumarB - Like Waldek pointed out - most likely cause for this is that some customization in the custom master page is overlapping with the SPFx. We can't really investigate or provide input for this issue unless we can create reproduce steps - to analyze what exactly goes wrong. Issue could be in versions of React/Angular/whatever library being referenced or in numerous other locations. Without additional details, we can only speculate what goes wrong.

**Comment by JayakumarB** [comment]
Thank you, I didn't change anything in the script code instead I just replaced the script order. Previously the custom scripts were loaded in body tag at the  bottom now reordered the scripts and loaded in the head tag itself. Issue resolved now.
