### ISSUE TITLE
Framing of sentence for PowerShell installation module

### ISSUE THREAD

**Issue by wizneeraj** [SharePoint/sp-dev-docs#9430]
[Enter feedback here]
After the instruction of enabling SharePoint Embedded, the next line discusses about the SharePoint PowerShell Module. But, it is not mentioned explicitly about SharePoint PowerShell Module and directly instructs to Upgrade or Install. Please check the highlighted section in the below screenshot.

![Screenshot 2024-01-02 135841](https://github.com/SharePoint/sp-dev-docs/assets/19283398/fefcf48e-4700-4cfd-a9d1-73c974724031)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Version Independent ID: b469eb4a-8a12-a1c2-aa28-052e4e8a3eeb
* Content: [Hands on Lab - Setup & configure the SharePoint Embedded environment and web app project](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-03-hol)
* Content Source: [docs/embedded/mslearn/m02-03-hol.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/embedded/mslearn/m02-03-hol.md)
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
These docs are now moved to the new location, so closing this from here - to avoid confusion. 

Valid finding and good feedback - will bypass to the owning team.
