### ISSUE TITLE
SharePoint wont respect it's own Connection: close header

### ISSUE THREAD

**Issue by bararchy** [SharePoint/sp-dev-docs#944]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When the server sends back `Connection: close` HTTP header, it should not allow for further communication with the server on the same socket

#### Observed Behavior
Sending a specific payload to the server (HTTP POST form) and getting back an HTTP response (400 the request is badly formed) (this is expected as it was a fuzzing session), the server return a `Connection: close` header, sending additional data to the socket is working, even doing `select` on the sending socket shows the socket is writable and readable and the other side has not closed the connection, this can take up to 5 minutes before the status of the socket changes.  

#### Steps to Reproduce
I used a simple Ruby script to open a raw socket to the server, and send the request from a file (attached)  

![screen](https://sc-cdn.scaleengine.net/i/cb5c63edf9a7ea8e4e5fb81bc69d4013.png)

the file contains an HTTP request to the path `/sites/test` which is the root of the application site (it's basically a txt file).  
[7z](https://www.dropbox.com/s/wsn0chsgqnz61ui/raw.7z?dl=0)  
[zip](https://www.dropbox.com/s/egdatclwdamnpxf/raw.zip?dl=0)

Sending it to the site emulate the relevant fuzzed HTTP request which recreates this weird socket issue.

**Comment by lucaband** [comment]
@VesaJuvonen, mind taking a loom at this please?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
