### ISSUE TITLE
Can we add manually other app catalogs webparts in same teams app?

### ISSUE THREAD

**Issue by paraggin** [SharePoint/sp-dev-docs#9443]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
![294817102-840789c4-701a-4cba-a5e9-4ea43450ad45](https://github.com/SharePoint/sp-dev-docs/assets/107133664/0983fbb3-740b-4f6c-baaf-ebaa8eb9a326)

- SPFx version
- Node.js version
- etc

### Issue description

I have successfully published an app on Teams, which currently features four tabs.
Now, I'd like to add a new tab from existing app catalog webpart directly from the Teams app. For more celeries check attached snapshot.

**Comment by VesaJuvonen** [comment]
Yes - You can create the package manually and define details for the package. See the options at https://learn.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions

**Comment by paraggin** [comment]
> Yes - You can create the package manually and define details for the package. See the options at https://learn.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions

Although this isn't precisely my primary concern, is it possible to integrate previously created web parts (Already published on the app catalog) into a single team app using any Teams' functionalities such as tabs, etc?
