### ISSUE TITLE
Article suggests node.js v18. Is this outdated information?

### ISSUE THREAD

**Issue by willvarner** [SharePoint/sp-dev-docs#9446]
Pretty much the title. The current LTS of node.js is v20 but this article asks for v18. Just looking for clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
Nope, it's correct. Current SPFx (v1.18.2) only supports Node.js v18.

**Comment by smolattack** [comment]
And if you think that's bad
https://github.com/SharePoint/sp-dev-docs/issues/9263
