### ISSUE TITLE
Field Customizer extension AND ListView Command Set extension fail in a classic site which has modern being used for libs and lists

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#945]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

The code works as described in
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api 
or
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

ListViewCommands and Field customisers don't work in classic sites even when lists and libraries are using Modern

#### Steps to Reproduce

- Create a SP Publishing site collection using the Publishing template

- Add document library

- Follow steps in https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

- Nothing happens in the page

- Repeating the above with a Group site works just fine with the same code.

**Comment by lucaband** [comment]
Currently list and library extensions only work for Modern Team Sites. We are doing work to expand the supported templates but the fact that they don't work on Publishing Sites is it known issue. 
Working on that.. leaving this issue open so I can communicate updates.

**Comment by AndersGEriksson** [comment]
These kind of limitations should be clearly documented, i cannot find any information about this in the documentation at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions. Huge problem that we cannot use these extensions on publishing sites with modern lists and libraries.

Is it the Publishing infrastructure feature or the web feature that breaks the extensions or a combination of both?

**Comment by VesaJuvonen** [comment]
Documentation updated with this additional note. Thanks for the suggestion - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions. We'll update this issue as it will get resolved and will remove the additional note on the documentation page. Thx for reporting.

**Comment by VesaJuvonen** [comment]
Thanks, @weshackett for opening this while back. The issue has been now internally fixed and it will be rolling out to worldwide production relatively soon. We'll update this thread and close the issue when it's fully rolled out.

**Comment by VesaJuvonen** [comment]
As this fix has been rolled out worldwide, closing this issue.

**Comment by amac44** [comment]
Does that mean the note that's still there in the docs is no longer needed? "There is a known bug with list and library extension support in the classic experiences. These only work currently in context of modern team sites, also known as group associated team sites. Work is being done to address this issue."
