### ISSUE TITLE
Sharepoint Embedded: Cannot get list of containers in SPA

### ISSUE THREAD

**Issue by SimonSimCity** [SharePoint/sp-dev-docs#9453]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

After following both the tutorials, currently available for Sharepoint Embedded (Postman, followed by SPA), I wasn't able to get a list of containers in my SPA (https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-05-hol#test-listing-and-selecting-containers).

In the network-tab of the developer tools, I found that the POST-request to `https://login.microsoftonline.com/common/oauth2/v2.0/token` returns with an error:

> AADSTS500011: The resource principal named api://<_client-id_> was not found in the tenant named <_tenant-id_>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

While researching about this error, I came across this stack-overflow question (https://stackoverflow.com/questions/76704063/getting-error-aadsts500011-the-resource-principal-named-was-not-found-in-t) where I don't know whether this is related to the issue I'm facing.

At least, when I follow this advise, and set up an application uri `api://d893eb9d-a843-4ef2-8202-5f32bc593f49` on which I created a role, called `Container.Manage`, after which I went again into the "API Permissions" section and once more granted all permissions available there (ignoring the error message I received `Claim is invalid: 40dc41bc-0f7e-42ff-89bd-d9516947e474 does not exist on resource application 00000003-0000-0000-c000-000000000000.`), I was able to list the containers. Creating containers also worked, which I tried right after.

Following the guide further, I was not able to list the files of the container, created via Postman - only of the container created via the web interface (https://learn.microsoft.com/en-us/sharepoint/dev/embedded/mslearn/m02-07-hol#test-the-rendering-of-listing-the-contents-of-a-container) - but out of the manual, I should be able to. In Postman, I can see them both, and when I query them to see their internal data, nothing seems to be different there.

What am I doing wrong here? Has this something to do with the way I fixed the first error I was encountering? Is there any additional information I can acquire which can help me looking further into this?

**Comment by SimonSimCity** [comment]
@andrewconnell Thanks very much for providing the video and article.

You've closed my PRs here, but I could see, that the article you've published on your website has the same issues I wanted to fix in the walkthrough here. At least yields to #9447, #9448 and #9449.

**Comment by andrewconnell** [comment]
WRT my article, I did see one improvement you made to splitting the access token from the `authorization` header (which I've updated... will take time to get past caching), but the other issues don't apply as best I can tell.

**Comment by SimonSimCity** [comment]
@andrewconnell I'll let you know my thoughts via mail 😊

I'll subscribe to the issue - this is closed, as I now know how to proceed. Would be good if the new material also includes those things. I'll let you know whether it worked when its online.

**Comment by andrewconnell** [comment]
@SimonSimCity said..
> Would be good if the new material also includes those things.

It is... publishing to MS Learning is just a more involved process than making updates to these docs. (IOW, takes a bit more time for the bits to flow through the various branches/reviews/approvals) ;)
