### ISSUE TITLE
Elements.xml created only for the first extension in the project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#946]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
A separate elements.xml file gets created for every extension added to the project.

#### Observed Behavior
Elements.xml file is created only for the first extension added to the project. When adding more extensions, scaffolding the elements.xml file for these extensions is skipped.

#### Steps to Reproduce
Using generator v1.3.2:
- create new online project
- disallow tenant-wide deployment so that elements.xml files get created
- add an extension
- confirm that elements.xml file is created
- add another extension
- 💥 no elements.xml file for the newly added extension is created

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
