### ISSUE TITLE
SitePage content canvasLayout and webParts request returns General Exception for some pages

### ISSUE THREAD

**Issue by GillesJ** [SharePoint/sp-dev-docs#9465]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

About 35% of all sitepages in our site fail while most are succesful. For those that fail the beta Graph API beta sitepage endpoint returns a `General Exception` when attempting to get the contents of a sitepage.

We compared the sitepage setup, webparts, and configuration of failed and successful pages but could find no immediate difference in the sitepage properties or contents between sitepages that work and those that fail.

Following [the beta sitepage and webpart documentation](https://learn.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta), we attempted the following URI formats:

1. GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage?expand=canvasLayout`:
results in `{'error': {'code': 'generalException', 'innerError': {'client-request-id': 'aa5...08', 'date': '2024-01-17T09:46:26', 'request-id': 'aa5...08'}, 'message': 'General exception while processing'}}`
3. GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage/webparts`
results in `{'error': {'code': 'generalException', 'innerError': {'client-request-id': '0550..13', 'date': '2024-01-17T09:46:30', 'request-id': '05...f13'}, 'message': 'General exception while processing'}}`
4. GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage?expand=webParts`
results in  `{'error': {'code': 'generalException', 'innerError': {'client-request-id': '9c6...10', 'date': '2024-01-17T10:01:56', 'request-id': '9c...10'}, 'message': 'General exception while processing'}}`

Getting the sitepage metadata always works for all pages:
GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage`

### Steps to reproduce

1. Make a request to load the canvasLayout for a given SP page:
GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage?expand=canvasLayout`
1. Make a request to load the webparts for a given SP page: 
GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage/webparts`
or
GET `https://graph.microsoft.com/beta/sites/{site_id}/pages/{page_id}/microsoft.graph.sitePage?expand=webParts`

3. The provided General Exception error is returned in about 35% of pages, in 65% it will succeed and return the contents.

### Expected behavior

The canvasLayout or list of webparts is returned.

**Comment by GillesJ** [comment]
Update: we can retrieve the missing pages with the Sharepy python package (which I believe is just requests-based webscraping).
So our current flow is to use GraphAPI calls with a Sharepy-fallback for failed/empty content requests.

**Comment by HiteshRepo** [comment]
Hi @GillesJ 
Just wanted to confirm, if this page is the `home.aspx` of site named `Give @ Contoso`? Because I am facing similar issue only for this one page (but getting 400 Bad Request) and I found someone else getting same issue for same site [here](https://github.com/SharePoint/sp-dev-docs/issues/8822#issuecomment-1809014018).

**Comment by AlexFilipovici** [comment]
hi @VesaJuvonen, do you know if there is any update on this issue? @ghost user seems to be deleted, I'm just checking if someone looks into this topic since it's affecting one of our organizations ongoing initiatives... Thanks!

**Comment by Yadong1106** [comment]
Hi, does this problem still exist? I remember that we have fixed this problem. I have tested it myself and did not encounter it. If it has been solved, could you please help us close this problem?

**Comment by AlexFilipovici** [comment]
Thanks for following up. Microsoft informed us that we should test the
bugfix after 2nd week of June.

**Comment by Yadong1106** [comment]
Sure, If you don't find any problems in your test, please help us close this. Thanks~

**Comment by wuodar** [comment]
Hi,

I'm currently developing "data puller" that makes request to sharepoint list items & site pages and download it's content.
For one of sites, I'm getting following error:

```
ODataError(message=None, response_status_code=400, response_headers=Headers({'cache-control': 'no-store, no-cache', 'content-type': 'application/json', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'strict-transport-security': 'max-age=31536000', 'request-id': 'cee20a12-60f8-4460-873a-3cce262cb94d', 'client-request-id': '904d9f1c-7f42-44f6-bd91-772c4c481d31', 'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"4","ScaleUnit":"001","RoleInstance":"FR2PEPF000001E9"}}', 'date': 'Tue, 25 Jun 2024 07:39:38 GMT'}), additional_data={}, error=MainError(additional_data={}, code='invalidRequest', details=None, inner_error=InnerError(additional_data={'code': 'badArgument'}, client_request_id='904d9f1c-7f42-44f6-bd91-772c4c481d31', date=DateTime(2024, 6, 25, 7, 39, 38, tzinfo=Timezone('UTC')), odata_type=None, request_id='cee20a12-60f8-4460-873a-3cce262cb94d'), message='One of the provided arguments is not acceptable.', target=None))
```

I think it might be related to this issue.
