### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by FoundryFounder** [SharePoint/sp-dev-docs#9467]
The "SharePoint Team Blog: Show off your style with SharePoint theming" link at the bottom of this page is broken/dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24696dfe-b4a5-b16e-f75a-702584f44304
* Version Independent ID: ebfe05bb-4726-c1c9-25ac-ca9b252d0708
* Content: [Deploy a custom theme in SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-a-custom-theme-in-sharepoint)
* Content Source: [docs/general-development/how-to-deploy-a-custom-theme-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-deploy-a-custom-theme-in-sharepoint.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
thx - removed from the page as link is broken.
