### ISSUE TITLE
Incorrect project upgrade information. It upgrades to the latest instead of the intended version. 

### ISSUE THREAD

**Issue by gretchunkim** [SharePoint/sp-dev-docs#9469]
Incorrect project upgrade information listed.
Using  the following will not upgrade project from 18 to 18.1 but to the latest (marked in red in the snapshot).  
The  verbiage will apply to all the previous version except for documentation for the latest version upgrade.   This instruction will cause intended project upgrade for users following the instruction. 

![IncorrectUpgradeInstruction](https://github.com/SharePoint/sp-dev-docs/assets/8564035/c1345875-9b7d-46d6-960b-03fbd12cde9a.pg)

```
Install the latest version
Install the latest release of the SharePoint Framework (SPFx) by including the @latest tag:
npm install @microsoft/generator-sharepoint@latest --global
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86d7ab3d-eae8-8540-be76-a3a0c5a03b21
* Version Independent ID: 86d7ab3d-eae8-8540-be76-a3a0c5a03b21
* Content: [SharePoint Framework v1.18.1 release notes](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.18.1)
* Content Source: [docs/spfx/release-1.18.1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/release-1.18.1.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
doc fixed and updated. Thx for the issue.
