### ISSUE TITLE
How can I return a sharepoint webpart into the chat from Teams Conversation bot in Teams App?

### ISSUE THREAD

**Issue by paraggin** [SharePoint/sp-dev-docs#9480]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

![299251210-6a07317f-e4b1-461e-95a4-545338ab0f16](https://github.com/SharePoint/sp-dev-docs/assets/107133664/92051522-4d76-4160-88cb-91f14045ceba)

I would like to display existing web parts within a Teams conversation chatbot. Could you please confirm if this is possible? If it is, could you provide a comprehensive guide on how to integrate web parts into my conversation chatbot?

**Comment by VesaJuvonen** [comment]
This is not currently possible. Teams bots support adaptive cards, but do not support other client side implementations, like SPFx.
