### ISSUE TITLE
Additional property on context: Full login name inc claims markup

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#95]
Can we have the 'context.pageContext.user' object extended with the full login name (including the claims markup)

**Comment by vman** [comment]
This is absolutely necessary. Especially for calls to the User Profile REST API which needs the full login name of the user. 

Currently there is an object which stores this: `spClientSidePageContext.user.LoginName` but ideally this should be in the `context.pageContext.user` object.

**Comment by patmill** [comment]
Closing old issue.  The property is available here - context.pageContext.user.loginName
