### ISSUE TITLE
No complete source code available?

### ISSUE THREAD

**Issue by ericrrichards** [SharePoint/sp-dev-docs#9510]
If there is a link to the complete source code of this example, I can't find it.
These snippets that only show one function or part of a function and not the whole file are less helpful.
Especially when the example is as far out of date as this one is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4f4088-693d-ba29-ddbf-797f9499389e
* Version Independent ID: aa0efa43-034a-8b34-593b-04c5109526ec
* Content: [Get started with SharePoint webhooks](https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/get-started-webhooks)
* Content Source: [docs/apis/webhooks/get-started-webhooks.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/webhooks/get-started-webhooks.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
Here's few web hook samples from while back - https://github.com/pnp/sp-dev-samples/tree/master/Samples

Should be helpful on getting things moving.
