### ISSUE TITLE
Auth error after adding isolated web part to the page

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#9511]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Edge:Dev 123.0.2380.1
- SPFx 1.18.2
- Node 18.19.0

### Describe the bug / error

After adding an isolated web part to the page, I'm getting the following error:

<img width="676" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/11164679/a54e785b-d072-4d60-8bf3-8e7c978cc1e7">

### Steps to reproduce

1. Create a new SPFx solution with a web part (no framework)
2. In config/package-solution.json change isDomainIsolated to true
3. Package and deploy
4. Add the web part to the page (same issue occurs in workbench) > error

### Expected behavior

Isolated web parts work

**Comment by lucabandMSFT** [comment]
@waldekmastykarz, thanks for the feedback. I want to be sure on the flow here: this is not an existing isolated components that was added to a page, instead it's a new isolated component that also was added to a page; is that correct?

Assuming that is the case, that is the behavior now. every *new* isolated component (where *new* == a new component added to the app catalog) can take up to 24 hours to register the new entry in AAD. Causing that error that you are experiencing at runtime.

**Comment by waldekmastykarz** [comment]
Correct, it's a brand new isolated web part that was just deployed to the app catalog that's failing. If this behavior is by design, it would be helpful to include it in the docs.

**Comment by lucabandMSFT** [comment]
@waldekmastykarz thank you. Documentation has been updated.
