### ISSUE TITLE
View List Formatting - When selecting item makes tab on custom style 

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9525]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- json

### Describe the bug / error

When adding a custom View List formatting the style moves when selected a item as shown in the image below:
![TabOnSelect](https://github.com/SharePoint/sp-dev-docs/assets/8522348/e58b7adc-f114-493f-8e5e-c0f67be6bcd3)

### Steps to reproduce

1. Access to Custom List and add item with text on title
2. Create a Custom View and select "Format current View > Click advanced mode"
3. Include json below:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
 "hideSelection": true,
  "rowFormatter": {
    "elmType": "div",
    "style": {
      "cursor": "pointer"
    },
    "children": [
      {
        "elmType": "div",
        "style": {
          "font-size": "16px"
        },
        "txtContent": "[$Title]"
      }
    ]
  }
}
```
4. select item on List and custom style makes a tab to the right.

### Expected behavior

When item is select it's expected that custom style should not jump/move and stay in area that was selected.

**Comment by dborchers-gc** [comment]
Please fix this ASAP we are using many json-formatted lists in our company and have many problems here

@shagra-ms do you have any infomations about a coming schema-update or any fix for this?

**Comment by aaclage** [comment]
Dear Mr. @shagra-ms, 

I want to inform that the error described before is not happening.

Thank you for your support.
