### ISSUE TITLE
Microsoft Graph Toolkit 4 + SPFx1.18

### ISSUE THREAD

**Issue by akshataggrwal** [SharePoint/sp-dev-docs#9538]
As per my understanding from the documentation(https://learn.microsoft.com/en-us/graph/toolkit/get-started/build-a-sharepoint-web-part?tabs=react#configure-webpack), to integrate MGT 4 with SPFx 1.18, additional dependencies on Babel are required, along with modifications to the gulp file for transpiling lit packages. 

This necessity stems from the fact that the SPFx toolchain continues to use webpack 4. I'm curious to know if there are any plans to upgrade SPFx to leverage Webpack 5 in near future, potentially eliminating the need for these extra dependencies and configurations?

Thanks!
_Originally posted by @akshataggrwal in https://github.com/SharePoint/sp-dev-docs/discussions/9537_

**Comment by s-KaiNet** [comment]
SPFx 1.19 [will have](https://devblogs.microsoft.com/microsoft365dev/public-preview-of-sharepoint-framework-1-19-first-release-of-upcoming-features/) Webpack 5 support.
