### ISSUE TITLE
AADHttpClient awaiting forever

### ISSUE THREAD

**Issue by SharePickle** [SharePoint/sp-dev-docs#9553]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Teams (Viva Connections)
- SPFx version: v1.18.0
- SP release: targeted release

### Describe the bug / error

In Teams Viva Connections on mobile phone (both Android and iOS) anything related to `AadHttpClient` is not working and forever waiting on `getToken` method. This includes `MSGraphClientV3`. For example trying to get anything from Graph API will just be sitting there stuck forever.

No errors in console, no failed network requests, just nothing.

See sample code below:
```ts
 const aadHttpClient = await context.aadHttpClientFactory
  .getClient('https://graph.microsoft.com'); // this resolves fine
 const response = await aadHttpClient
  .get(`https://graph.microsoft.com/v1.0/me`, AadHttpClient.configurations.v1); // <== never resolves
```

**IMPORTANT**:
I'm able to reproduce this outside of Teams (Windows 11 Desktop) using this page (you have to deploy and install an Application Customizer on your site, this page is blank and only loads extensions) `https://<tenant>.sharepoint.com/_layouts/15/preload.aspx?mbypass=1&env=WebView`
If you remove `WebView` argument then it starts to work without any issues.

While debugging, this bit seems to be never resolving and saving forever pending promise in tokens cache:

![image](https://github.com/SharePoint/sp-dev-docs/assets/32567749/babdf92a-3408-477d-9a5a-f1e067fc95ad)

### Steps to reproduce 1 (Teams + Mobile phone)

1. Open Teams Viva Connections on Mobile phone (iOS or Andriod)
2. Try any web part that talks to Graph API
3. It's stuck forever and never resolves (not even rejects).

### Steps to reproduce 2 (Browser + Desktop)

1. Open page `https://<tenant>.sharepoint.com/_layouts/15/preload.aspx?mbypass=1&env=WebView`
2. Try any extension that talks to Graph API (it has to be an extension to be able to load on this page)
3. It's stuck forever and never resolves (not even rejects).

### Expected behavior

Graph token succesfully retrieved and Graph API request succeeds.

**Comment by lucabandMSFT** [comment]
@SharePickle, let's follow up offline. one thing thou: the way you reproed it in the web is wrong and will always fail: when you add env=webView it is a signal for us that we are embedded in Teams. That's where we try to get the token from Teams and not MSAL. in the browser, we are not in Teams so we will always stuck forever.

**Comment by SharePickle** [comment]
@lucabandMSFT hello, could you please keep the ticket open? Teams issue still not resolved, even if my WebView steps are invalid.
Also, how is it possible to debug Teams Viva Connections on Mobile phone, do you guys have any tutorials? I could only find guides on how to test Teams Tab, but not Viva Connections page.

**Comment by sharepointalist** [comment]
Looks like we have similar issue with any web part using Graph API in SharePoint app and in Teams app (through Viva Connections). Reported by customer and reproduced in multiple tenants.
