### ISSUE TITLE
SPE: Documentation does not make it clear how & what permissions can be granted to applications

### ISSUE THREAD

**Issue by arenk** [SharePoint/sp-dev-docs#9566]
The documentation makes several references to **AppID-ContainerTypeID pairs** regarding permissions (see section Authorization in the referenced document below). In the same section, an example also mentions **App1 has Create, Read, and Write permissions to ContainerType1; and...**.

However, there is no information on what permissions can be granted to applications and how that works. I played around with the **Register ContainerType** request in the provided [Postman collection](https://github.com/microsoft/SharePoint-Embedded-Samples/tree/main) and assume one can just add an additional app while registering the ContainerType (see request body below). The values "create", "read" & "write" are accepted, however it's not possible to e.g. see the contents in a drive even with this set of permissions (using Microsoft Graph) - it only works with permission "full".

The following questions should be answered in the documentation:
1. How can permissions to additional Entra applications be granted?
2. What kind of permissions do exist and what impact do they have?
3. In general, what options exist to restrict access of (non-owning) applications to Containers in an App-Only authentication scenario (similar to Sites.Selected in SharePoint) for both
- scope of permissions in general (e.g. only read-write content, but not create containers)
- container restrictions (e.g. only allow to read contents in containers with specified IDs)

Again, this all refers to App-only authentication scenarios.

Also, I couldn't find any documentation for the endpoint used to register ContainerTypes (_api/v2.1/storageContainerTypes/{{ContainerTypeId}}/applicationPermissions).

Example of an accepted request body to register a container type with an additional application:
```
{
  "value": [
    {
      "appId": "{{OwningAppId}}",
      "delegated": ["full"],
      "appOnly": ["full"]
    },
    {
      "appId": "{{MyAdditionalAppID}}",
      "delegated": ["create", "read", "write"],
      "appOnly": ["create", "read", "write"]
    }
  ]
}

```

---
#### Document Details - Authentication

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e995b4e-3fb1-8bcf-6407-80ace48d8913
* Version Independent ID: 5e995b4e-3fb1-8bcf-6407-80ace48d8913
* Content: [Authentication and Authorization with SharePoint Embedded](https://learn.microsoft.com/en-us/sharepoint/dev/embedded/concepts/app-concepts/auth)
* Content Source: [docs/embedded/concepts/app-concepts/auth.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/embedded/concepts/app-concepts/auth.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by arenk** [comment]
Just in case someone might have the same question, at least the following permissions exist (besides full and none)

- **create, read, write, delete** - seem to be container-related, i.e. endpoints `beta/storage/fileStorage/containers/...`
- **readContent, writeContent** - seem to be file-related, i.e. endpoints `v1.0/drives/...`

**Comment by andrewconnell** [comment]
@arenk You can see a list of the options in the docs: https://learn.microsoft.com/sharepoint/dev/embedded/concepts/app-concepts/register-api-documentation#container-type-permissions
