### ISSUE TITLE
Did SPFx 1.20.1 accidently get released? Some packages are saying that's the latest version now but not all SPFx packages

### ISSUE THREAD

**Issue by kbeeveer46** [SharePoint/sp-dev-docs#9570]
### What type of issue is this?

Question

### Issue description

npm outdated is showing a new version. There is no mention of 1.20.1 in the releases page https://learn.microsoft.com/en-us/sharepoint/dev/spfx/roadmap

![image](https://github.com/SharePoint/sp-dev-docs/assets/12972554/0377407d-128a-426e-ab2e-5b830bcca428)

**Comment by datyin** [comment]
And also just for info, importing css is broken on this version (1.20.1) of @microsoft/sp-build-web.

**Comment by stevebeauge** [comment]
Sounds very promising when it will be officially and actually released : https://www.npmjs.com/package/@microsoft/sp-build-web?activeTab=code 

Webpack is now webpack 5 ! Maybe we will at least get rid of this prehistoric webpack 4
