### ISSUE TITLE
Adaptive Cards Control - Input.ChoiceSet - Issue

### ISSUE THREAD

**Issue by akshataggrwal** [SharePoint/sp-dev-docs#9581]
### Discussed in https://github.com/SharePoint/sp-dev-docs/discussions/9578

<div type='discussions-op-text'>

<sup>Originally posted by **akshataggrwal** March 15, 2024</sup>
Hello @AJIXuMuK ,

I'm currently working on an adaptive card extension for Viva Connections and encountering an issue with the 'Input.Choiceset' control with style set to 'filtered' in Quick View(adaptive card version 1.5). While it displays only a certain number of items (in my case, 513 items whereas total items are 780), and typing in something reveals results beyond those 513 items.

I am also seeing the same behavior in the adaptive card designer. I have attached the sample json that can be referenced to replicate it in the designer. https://adaptivecards.io/designer/.

Thanks!</div>

**Comment by AJIXuMuK** [comment]
@akshataggrwal - if you are experiencing the same in AC designer - it means the issue is in Adaptive Cards, not SPFx or ACEs. Unfortunately, out team doesn't own AC. 
I would recommend to file a bug for AC team.

**Comment by akshataggrwal** [comment]
Thanks @AJIXuMuK for your response. 

Also to confirm my understanding, dynamic typeahead search in [Input.ChoiceSet](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/dynamic-search) is not yet supported in Adaptive Card Extensions (ACEs) because it's a feature introduced in Adaptive Card version 1.6, is that correct?
