### ISSUE TITLE
DynamicForm - how can I set a hidden field value on item form?

### ISSUE THREAD

**Issue by devspfx** [SharePoint/sp-dev-docs#9587]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

3.17 version

### Issue description

Iti is possible to set value of a hidden/not hidden field before the item is created (on new form)?

**Comment by aaclage** [comment]
Dear Mr @devspfx 

By the version reference and name of control believe your are referencing the following project. https://github.com/pnp/sp-dev-fx-controls-react

Can recommend review documentation https://pnp.github.io/sp-dev-fx-controls-react/controls/DynamicForm/#implementation
There are multiple Properties, maybe "onBeforeSubmit" could help you.

**Comment by devspfx** [comment]
I viewed the documentation. It is possible to get the form data on the beforesubmit function?
