### ISSUE TITLE
List Formatting - Style issue using inlineEditField with field type Choice 

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9617]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Dear Mr. @shagra-ms,

I would like to report the following issue using inlineEditField with choice field that width **doesn't fits the size to display the options**, but **size defined in List formatting json**. when using sharepoint page with inlineEditField. 
When using SharePoint Page inlineEditField choice field display correctly where all options are visible.
Below sample of the error:
![ErrorListFormattingStyle](https://github.com/SharePoint/sp-dev-docs/assets/8522348/af916ebe-a09e-49ea-b0b8-f621097fceb0)

### Steps to reproduce

1. Create List
2. Add Field "Tags" and add multiple options
3. Access to view and include List formatting json below
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "hideColumnHeader": true,
  "hideSelection": true,
  "rowFormatter": {
    "elmType": "div",
    "children": [
      {
        "elmType": "div",
        "style": {
          "padding": "20px",
          "width": "10px"
        },
        "txtContent": "[$Tags]",
        "inlineEditField": "[$Tags]"
      }
    ]
  }
}
```
4. Click on "Tags" field and dropdown option doesn't resize width but assume the with defined in json style.
5. Create SharePoint Page and add WebPart List with associated View.
6. Click on "Tags" field and dropdown option does resize width that all choice options are displayed.

### Expected behavior

It's expected when apply List formatting json with option inlineEditField  + choice field, the options should display to be selected even when defined in json the width of field.

**Comment by shagra-ms** [comment]
@aaclage we are currently looking into this.

**Comment by aaclage** [comment]
Dear @shagra-ms @arkogupta,

Here my feedback on current issue:
1- "**Style issue using inlineEditField on choice field**" was fixed. 

Thank you for your support and going to close ticket, 
A L
