### ISSUE TITLE
❓🐞 Extension Command Set Button Images Don't Render

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#962]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Image should render beside by button when referenced in manifest as an absolute URL to acceptable image.

#### Observed Behavior
No image rendered

#### Steps to Reproduce
Created a command set button with the following manifest signature... no image is rendered. However, the image is being requested as confirmed in browser's dev tools, but it's not added to UX

```json
"ALWAYS_ON": {
  "title": { "default": "Always On" },
  "iconImageUrl": "https://vtnscdn.azureedge.net/assets/logos/logo-voitanos-icononly-16x16.png",
  "type": "command"
}
```

It is a valid image: 
![](https://vtnscdn.azureedge.net/assets/logos/logo-voitanos-icononly-16x16.png)

Tried multiple sizes too... 50x50 doesn't render either
![](https://vtnscdn.azureedge.net/assets/logos/logo-voitanos-icononly-50x50.png)

**Comment by GrumpyWookie** [comment]
This works for me - but a URL within the same tenant - as opposed to public (CDN)

**Comment by waldekmastykarz** [comment]
@andrewconnell have you deployed your command to the context menu or the command bar?

**Comment by mcmynn83** [comment]
@andrewconnell - Is this issue resolved or are you still having this problem?

**Comment by VesaJuvonen** [comment]
@andrewconnell - any input on Graham's question. If I got this right, the issue is either now resolved or the issue only occurs with public CDN referenced images. Getting this confirmed would help us a lot. "I don't know" is also fine answer. Thx.

**Comment by andrewconnell** [comment]
@VesaJuvonen & @mcmynn83 ... my bad, didn't see a notice that there was activity on this thread until today. I can confirm the issue is resolved.

**Comment by VesaJuvonen** [comment]
thx for following up. No worries - so many moving things. Trust me - I get that.
