### ISSUE TITLE
What defines the "newer" version of the Microsoft Lists App?

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9620]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

[This document](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference) states that the `embed` of `customRowAction` can only be used with the "newer" version of the Microsoft Lists App. Is there a way to determine if the Microsoft Lists App currently being used is the "newer" version?

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/edeb82b0-85c0-4247-af4f-2fbc14b78bde)

**Comment by arkogupta** [comment]
@tecchan1107 Yes that's correct. The view tabs on the top should be a good enough indicator of the "new" UI.

**Comment by tecchan1107** [comment]
Thanks for the answer @arkogupta !
