### ISSUE TITLE
SPFx webparts icons not rendered

### ISSUE THREAD

**Issue by roberAlb** [SharePoint/sp-dev-docs#9630]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [X] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- 1.18.2
- 18.9.1
- etc

### Describe the bug / error

Some SPFx web part icons are not rendered property, they were working fine one week ago. We are using the property iconImageUrl with an image in base64 format.

### Steps to reproduce

1. We have some web parts deployed into the tenant
2. Opening the toolbox to add a new one we can see some of them without the image
3. It's happening in all environments

### Expected behavior

As the base64 image is correct we expect to see it as the webpart icon

**Comment by roberAlb** [comment]
@StfBauer this is the html for a webpart where the icon is not displayed

![image](https://github.com/SharePoint/sp-dev-docs/assets/50910751/68a8509b-9794-4576-aeaa-8143706dc4ec)

This is the webpart without the icon

![image](https://github.com/SharePoint/sp-dev-docs/assets/50910751/e6f023c0-9587-4dee-937e-09bce7c64371)

**Comment by SharePickle** [comment]
Bump, this bug affects icons at random. Two people looking at the same web part gallery can see different icons missing.

**Comment by magarma** [comment]
It's affecting all tenants we have checked, and it's random... some icons work in some tenants, but the same ones don't work in others.

**Comment by mbice** [comment]
We're seeing the same thing happen on several tenants. Some icons loading and not others - varies from tenant to tenant.

**Comment by sinnitesh** [comment]
I am also facing this issue in all of our client's environments

**Comment by roberAlb** [comment]
This has been solved in all environments that we have checked

**Comment by mbice** [comment]
> This has been solved in all environments that we have checked

Same here - we can no longer reproduce this issue.

**Comment by roberAlb** [comment]
Closing it as was already fixed

**Comment by vvolodin** [comment]
Doesn't work for me on all environments and it got my submission returned with a "must fix".

**Comment by vvolodin** [comment]
After experimenting a bit it seems like a value from `officeFabricIconFontName` started overriding the icon from `iconImageUrl`. It wasn't behaving like this a week ago.
