### ISSUE TITLE
Applying Field Customizer Leads to Empty Cells in Teams Files Tab

### ISSUE THREAD

**Issue by yvesrosius** [SharePoint/sp-dev-docs#9642]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Follow up on same question in https://github.com/SharePoint/sp-dev-docs/issues/8450

Is there an update on this? Can we follow this backlog item?

![image](https://github.com/SharePoint/sp-dev-docs/assets/58165765/f68e9cf1-1159-4004-9f5a-670ad4c899f8)

**Comment by AJIXuMuK** [comment]
@yvesrosius - unfortunately, no updates.
For now SPFx extensions work inside SharePoint only, not Teams.

**Comment by AJIXuMuK** [comment]
@hohenp - unfortunately no news.
