### ISSUE TITLE
Change field properties created with createSiteColumn verb

### ISSUE THREAD

**Issue by vishalshitole** [SharePoint/sp-dev-docs#9652]
As mentioned in the documentation, one could create **Note** field using `createSiteColumn` verb. How does one change it's type from **Plain Text** to **Rich Text** or **Enhanced Rich Text**? Is it possible with the `createSiteColumn` verb at all?

Similarly for DateTime field. How to change its type from **DateOnly** to **DateAndTime**?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68267476-ee8d-7b95-446b-711ddb683da2
* Version Independent ID: aa099b9d-48db-5513-11c7-32c49a27e5be
* Content: [Site template JSON schema](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#define-a-new-site-column)
* Content Source: [docs/declarative-customization/site-design-json-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-json-schema.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by mkm17** [comment]
Hi @vishalshitole, I'm not sure if this information would be useful, but for more complex scenarios, you can utilize `createSiteColumnXml` option.

 the DateTime example, and take note of the setting Format='DateTime':
```json
       {
          "verb": "addSPFieldXml",
          "schemaXml": "<Field DisplayName=\"DateTime\" FriendlyDisplayFormat=\"Relative\" Format=\"DateTime\" IsModern=\"TRUE\" Name=\"DateTime\" Title=\"DateTime\" Type=\"DateTime\" ID=\"{5fad18d8-0333-4776-a11b-bc0e670e32f2}\" StaticName=\"DateTime\"><Default>[today]</Default></Field>"
        }
```

 the Note example, and take note of the settings RichText='True' and RichTextMode="FullHtml" : 
       
```json 
       {
          "verb": "addSPFieldXml",
          "schemaXml": "<Field AppendOnly=\"FALSE\" DisplayName=\"MultiLine\" Format=\"Dropdown\" IsModern=\"TRUE\" IsolateStyles=\"TRUE\" Name=\"MultiLine\" RichText=\"TRUE\" RichTextMode=\"FullHtml\" Title=\"MultiLine\" Type=\"Note\" ID=\"{c52341cb-be85-4779-80cd-742319acebe4}\" StaticName=\"MultiLine\" />"
        }
```

**Comment by vishalshitole** [comment]
Hi @mkm17 Thanks for your response.

I was able to utilize the `createSiteColumnXml` verb for my use case. However, I wanted to know if those kind of updates are possible with `createSiteColumn` verb, and whether I am missing anything in the documentation.

**Comment by mkm17** [comment]
Hi @vishalshitole, Maybe someone can confirm, but as I can see, the documentation states to use `createSiteColumnXml` for more complex cases:

![image](https://github.com/SharePoint/sp-dev-docs/assets/17220108/27d93fc5-9c49-4afd-a767-f293c17da244)

There are no other properties listed for `createSiteColumn` besides: `fieldType`, `internalName:`, `displayName`, `isRequired`, `id`,
`group`, `enforceUnique`,
