### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by cmathis94** [SharePoint/sp-dev-docs#9657]
Found a typo in the path at this section of the site: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries#add-web-part-properties

You will find the typo at section 3 of "Add Web Part Properties" at the path. It currently has this as the path **./src/webparts/gallery/IGalleryWebPartProps.ts** when I believe it should say **../src/webparts/gallery/GalleryWebPart.ts**. I only removed the "I" and "Props" in the IGalleryWebPartProps.ts. That's just what I see in the folder stucture. 

![image](https://github.com/SharePoint/sp-dev-docs/assets/94585153/322acfab-9822-488b-ad16-8f5306dbb5a7)

![image](https://github.com/SharePoint/sp-dev-docs/assets/94585153/654a5caf-e600-487d-9fc1-1fef9acb05b6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3043faa1-f278-c483-17f4-e1af81d9b097
* Version Independent ID: df4b13b3-4c12-0592-7f29-f54075807c3b
* Content: [Simplify adding web parts with preconfigured entries](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries)
* Content Source: [docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by mkm17** [comment]
Hi @cmathis94 it looks like the path in the documentation is incorrect. The props file should be found in ./src/webparts/gallery/**components**/IGalleryWebPartProps.ts.

Here is my example with the 'HelloWorld' webpart name.
![image](https://github.com/SharePoint/sp-dev-docs/assets/17220108/2ac28f7c-1b03-4c3c-adda-57fc88bed1b3)

**Comment by andrewconnell** [comment]
Thanks for the PR... this is how older projects were structured (separating the interface into a separate file), so the docs were just a little out of date.
