### ISSUE TITLE
SharePoint JSON list formatting not pulling data from list item.

### ISSUE THREAD

**Issue by Nashmeyah** [SharePoint/sp-dev-docs#9658]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
-JSON

### Describe the bug / error

I have formatted the SharePoint Gallery view and I am trying to display the name of the user that enters the list item. I have used the Created By field that is in the SharePoint list and i have also used the Author kay value that is displayed in Power Automate and it will not work. The other fields work successfully, i have also created a new SharePoint column to use and even that does not display the value.

<img width="664" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/22226683/7b152357-9935-4e65-ae58-f0dc4a935f7c">

<img width="677" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/22226683/a2c828bb-3d3e-4f6e-ac22-cdd6ff5b7831">

### Steps to reproduce

1.I created a new div with a new field.
2.I created a new column and tried to use it instead.
3.Within the same div, I tried other Variables such as (title) and it displayed the information successfully.

### Expected behavior

The field value would display the information I am trying to pull.

**Comment by Fedes365** [comment]
@Nashmeyah 

A basic question: is that column [$CreatedBy] included in that gallery view? Have you checked from the list settings user interface?

**Comment by Nashmeyah** [comment]
<img width="385" alt="image" src="https://github.com/SharePoint/sp-dev-docs/assets/22226683/f2fefd15-20ef-49a9-94d3-bc9c68d12a2c">
Is this what you are meaning? @Fedes365

**Comment by Fedes365** [comment]
@Nashmeyah

I'm checking right now in a demo list. Can you try with [$CreatedBy.title] or [$Author.title] in you JSON?

**Comment by Nashmeyah** [comment]
OMG that worked! I tried that millions of times i have no idea why it did not work before!!! Thank you so much I have broken my head several times trying to figure this out. 

BTW, [$CreatedBy.title] did not work but [$Author.title] did in fact.
I also tried  [$CreatedBy.displayValue] and it also did not work.

I also created another SharePoint list item (Client Name) and added it to the display and that value worked with $ClientName.displayValue

**Comment by Fedes365** [comment]
@Nashmeyah 

When it comes to people fields (also the OOTB ones like Author etc.) you need to specify some properties, such as title, email, department ecc.

Reference (scroll down to People field): https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#currentfield

**Comment by Nashmeyah** [comment]
Thank you very much!
