### ISSUE TITLE
List Formatting: Callout is not displayed when `@currentField` is set to `src` in `embed` action

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9671]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

If I set [@currentField](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#currentfield) to the `src` of the [embed](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#customrowaction) action, the callout will not be displayed. If the internal name of the column is set, the callout will be displayed.

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/9e680129-3e21-4027-b440-878d888f2460)

https://github.com/SharePoint/sp-dev-docs/assets/51254139/921a2d3d-aec3-485b-87fd-e82675247289

### Steps to reproduce

1. Create a `YouTube` column (column internal name: YouTube, column type: single line of text) in the list
2. Set the URL for embedding in the created column

    ![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/13fe8bcc-4fa2-4db7-abc9-c95595afdffb)

   YouTube video used for verification: https://www.youtube.com/watch?v=MHopBnmhPzg
   URL for embedding: https://www.youtube.com/embed/MHopBnmhPzg?si=sYT8Tpmn6dv5Sc1e

3. Set the following JSON to the formatting of the created `YouTube` column

<details>

<summary>Code using the internal name of the column</summary>

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "div",
      "style": {
        "cursor": "pointer",
        "border-radius": "7px",
        "padding": "5px 10px",
        "display": "=if(@currentField,'flex','none')",
        "align-items": "center"
      },
      "attributes": {
        "class": "ms-fontSize-s ms-fontColor-white ms-bgColor-themePrimary ms-bgColor-themeTertiary--hover"
      },
      "customRowAction": {
        "action": "embed",
        "actionInput": {
          "src": "[$YouTube]",
          "width": "640",
          "height": "360"
        }
      },
      "children": [
        {
          "elmType": "span",
          "style": {
            "margin-right": "5px"
          },
          "attributes": {
            "iconName": "MSNVideosSolid"
          }
        },
        {
          "elmType": "span",
          "txtContent": "Watch YouTube"
        }
      ]
    }
  ]
}
```

</details>  

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/c21ff18b-6b1b-447a-9d61-ead5fdda3569)

4. Change YouTube column formatting created to the following JSON

<details>

<summary>JSON using @currentField</summary>

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "div",
      "style": {
        "cursor": "pointer",
        "border-radius": "7px",
        "padding": "5px 10px",
        "display": "=if(@currentField,'flex','none')",
        "align-items": "center"
      },
      "attributes": {
        "class": "ms-fontSize-s ms-fontColor-white ms-bgColor-themePrimary ms-bgColor-themeTertiary--hover"
      },
      "customRowAction": {
        "action": "embed",
        "actionInput": {
          "src": "@currentField",
          "width": "640",
          "height": "360"
        }
      },
      "children": [
        {
          "elmType": "span",
          "style": {
            "margin-right": "5px"
          },
          "attributes": {
            "iconName": "MSNVideosSolid"
          }
        },
        {
          "elmType": "span",
          "txtContent": "Watch YouTube"
        }
      ]
    }
  ]
}
```

</details>

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/5dc370ff-e93b-42e7-868c-7fa83f52a61b)

### Expected behavior

Callouts are displayed even if `@currentField` is used.

**Comment by arkogupta** [comment]
@tecchan1107 Thanks for reporting the bug. We'll take up the fix soon. Will update on the timelines.

**Comment by tecchan1107** [comment]
Hi @arkogupta .
I checked today and it displays embedded without any problem using `@currentField`! Thanks for the fix!!!🙇‍♂️
![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/c4f8576a-1f13-4ba6-9ee6-874b20346cf7)

I will close this issue now that the issue has been resolved.

P.S.
I create issues related to List Formatting in this repository as soon as I find them. If possible, we would appreciate it if you could respond to it.
https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+is%3Aopen+List+Formatting

I think the following issue in particular has a significant impact.
https://github.com/pnp/List-Formatting/issues/812
