### ISSUE TITLE
SPFx gulp serve issue

### ISSUE THREAD

**Issue by JayakumarB** [SharePoint/sp-dev-docs#968]
When i run the gulp serve the sub tasks are not completed, i'm not getting any error/warnings at the end it simply breaks the execution, please find below screenshot.

![image](https://user-images.githubusercontent.com/11646986/31758605-c79ca50a-b4cb-11e7-824d-355af71bc9c1.png)

**Comment by waldekmastykarz** [comment]
Could you try running `gulp bundle --verbose` and see if you get any more information?

**Comment by iclanton** [comment]
I'm not seeing any failures. Does the `write-manifests` task just never complete and fail silently?

The `--verbose` output would be helpful.

**Comment by JayakumarB** [comment]
I'm not sure why such problem raised, i just run gulp clean, gulp build, then at last gulp serve fixed my issue.
