### ISSUE TITLE
minor typo and tooling suggestion

### ISSUE THREAD

**Issue by Adam-it** [SharePoint/sp-dev-docs#9684]
## 👀

at the very top shouldn't this be `SPFx`?  👇

![image](https://github.com/SharePoint/sp-dev-docs/assets/58668583/c5167b59-102d-478c-aabf-f255fc2f1e48)

I think one `already` is enough here 👇

![image](https://github.com/SharePoint/sp-dev-docs/assets/58668583/f50e797c-d990-4087-8551-4ae44363259f)

in the optional tooling

![image](https://github.com/SharePoint/sp-dev-docs/assets/58668583/61c9b7e8-4efc-4557-8882-994ab78c3a6f)

- the postman link goes to 404
- I would add Teams Toolkit VS Code extension 
- I would add SharePoint Framework Toolkit VS Code extension

## 🙋‍♂️

If possible I am more than happy to open a PR with those changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/set-up-your-development-environment.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
PR's welcomed on docs ;)

**Comment by Adam-it** [comment]
Will do 👍
