### ISSUE TITLE
Unable to get all tenant properties

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#969]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Be able to list all tenant properties configured on the app catalog using PowerShell.

#### Observed Behavior
Currently using PowerShell, you can only retrieve the details for a specific tenant property, but you cannot get the list of all tenant properties.

#### Steps to Reproduce
n/a

**Comment by mcmynn83** [comment]
@waldekmastykarz - Thank you for your feedback, this is actually a feature request.  The right place to ask for new features is user voice.  This one in particular is already in the works though.  However, I am going to close this issue as this is the wrong forum for feature requests.
