### ISSUE TITLE
Additional property on context: User's Tenant Id

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#97]
Can we get the Office 365 tenancy Id (the Guid that the Graph would recognise).

This is super useful in the following scenarios.
- Telemetry
- Extranet scenarios in B2B so you know where the user originates
- Using the MS Graph once it comes

**Comment by wictorwilen** [comment]
In what scenarios are the users tenant id and sites tenant id (#98)  different?

**Comment by weshackett** [comment]
If the user is an 'extranet' user is B2B then they must have come from another tenant. I'm not sure MS Graph makes this available like this though.

**Comment by patmill** [comment]
So the problem here is that pulling some user info into the context object is expensive.  If we happen to have it already on the server, then it is cheap, but if we have to contact AD to get the information (which this one falls under), then it will slow down the request on the server a fair chunk.
