### ISSUE TITLE
Can I select default Documents as the list? 

### ISSUE THREAD

**Issue by WaldoKing** [SharePoint/sp-dev-docs#9706]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Good day 

Thank you in advanced for the assistance. 
On this guide: https://learn.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your-first-flow

Point 5 states: 
`Using the dropdowns, verify the connection information (SharePoint Site Address and SharePoint **List Name**) is accurate to ensure it uses your credentials.`

Sharepoint site chosen with no problem. But I am not sure what the 'List' is? 
![image](https://github.com/SharePoint/sp-dev-docs/assets/137397874/b66d121a-bdce-43fc-b571-1ba5ce2bd4ce)
A blank test did not work. 

I saw I could create a list, but that creates a separate document library, and I was to query my main document folder. 
![image](https://github.com/SharePoint/sp-dev-docs/assets/137397874/9cea1c3a-d313-429d-bf74-3889b8745b72)
Selecting the blank list I made also, states "invalid connection" 

Could someone please elaborate on what this list needs to be? 

Kind regards 
Waldo

**Comment by mkm17** [comment]
Hi @WaldoKing, As I can see in the example, there is a `When a new item is created` trigger used, which allows you to choose one from a **list** created on a site.
![image](https://github.com/SharePoint/sp-dev-docs/assets/17220108/c2d50119-b183-453c-a204-636d4825982e)

If you would like to use a **Document** library, you should use a different trigger, for example, `When a file is created (properties only)`

![image](https://github.com/SharePoint/sp-dev-docs/assets/17220108/d2b3ce07-129a-4cda-bfe9-70cf3c03cc53)


I hope that this information will be helpful.

**Comment by WaldoKing** [comment]
@mkm17 You are the best! that is 100% the answer. Thank you very much.
