### ISSUE TITLE
List view formatting: Some commandBarProps keys not working in MS lists (only Sharepoint list)

### ISSUE THREAD

**Issue by elsiegit** [SharePoint/sp-dev-docs#9711]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Tested in edge and chrome

### Describe the bug / error

When using commandBarProps in view formatting JSON the "export": "hide" and "new": "Create" (for custom text on new button) are not working in new Microsoft list URL but are behaving as expected in traditional SharePoint list URL

Also there is no key available to hide the new 'Forms' button from the command bar.

**NOT working URL:** https://xxx.sharepoint.com/sites/xxx/Lists/xxx/Cal.aspx?viewid=0e35b3b2-69af-48e6-83b1-2d6bfa468578&env=WebViewList

**CORRECTLY working URL:** https://xxx.sharepoint.com/sites/xxx/Lists/xxx/1%20Create%20CPI.aspx

![image](https://github.com/SharePoint/sp-dev-docs/assets/170233084/bb67b68b-9bdb-46bd-864e-d2a48d70ab61)
![image](https://github.com/SharePoint/sp-dev-docs/assets/170233084/47303428-58d3-41bb-b3a7-92e0688a8213)

### Steps to reproduce

 "commandBarProps": {
    "commands": [
      {
        "key": "editInGridView",
        "hide": true
      },
      {
        "key": "copyLink",
        "hide": true
      },
      {
        "key": "alertMe",
        "hide": true
      },
      {
        "key": "manageAlert",
        "hide": true
      },
      {
        "key": "comment",
        "hide": false
      },
      {
        "key": "share",
        "hide": true
      },
      {
        "key": "automate",
        "hide": true
      },
      {
        "key": "integrate",
        "hide": true
      },
      {
        "key": "export",
        "hide": true
      },
      {
        "key": "exportCSV",
        "hide": true
      },
      {
        "key": "exportExcel",
        "hide": true
      },
      {
        "key": "new",
        "text": "Create"
      }
    ]
  }

### Expected behavior

I expected the formatting to be effective in MS lists as well as SharePoint lists
I expected there to be a key available to hide the new Forms button

**Comment by daviduber1** [comment]
This is also problematic for our organisation. @elsiegit, were you able to find any workarounds for this?

**Comment by elsiegit** [comment]
> This is also problematic for our organisation. @elsiegit, were you able to find any workarounds for this?

I've not heard anything back unfortunately. MS lists is extremely buggy, it's hard to win over colleagues given all the issues, MS need to take a look at airtable!

**Comment by jgupta-msft** [comment]
@elsiegit : Sorry for responding later here. I hope this issue has been fixed for you. Please let me know if you are still facing any issue.

**Comment by elsiegit** [comment]
I'm not sure, is there now a key for hiding the new forms button via commandBarProps?

> @elsiegit : Sorry for responding late here. I hope this issue has been fixed for you. Please let me know if you are still facing any issue.

**Comment by jgupta-msft** [comment]
hi @elsiegit : Yes, the key is "manageForms". It is updated in documentation: https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting

**Comment by elsiegit** [comment]
> hi @elsiegit : Yes, the key is "manageForms". It is updated in documentation: https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting

Thank you
