### ISSUE TITLE
Add StorageQuotas Endpoint to documentation

### ISSUE THREAD

**Issue by weyCC81** [SharePoint/sp-dev-docs#9721]
Please add the StorageQuotas Endpoint to the "SharePoint API index" documentation:

API | SP.Object/Enumeration (sp.js) | REST Endpoint
-- | -- | --
StorageQuotas | SP.UsageInfo.storage <https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245691(v=office.15)> | <https://contoso-admin.sharepoint.com/_api/StorageQuotas()?api-version=1.3.2>

More:
> ObjectType_: Microsoft.Online.SharePoint.TenantAdministration.Tenant
> StorageQuota":10075648
> [TenantPropertyNames.StorageQuota](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn174786(v=office.15))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94956608-25b4-0605-f43d-d161ebdde905
* Version Independent ID: 5a5b71db-be77-2ac8-7b9f-82f13961d4fa
* Content: [SharePoint .NET Server, CSOM, JSOM, and REST API index](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index#sharepoint-api-index)
* Content Source: [docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md)
* Service: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by mkm17** [comment]
Hi @weyCC81, it looks like some of the SharePoint REST API endpoints are missing. Thanks for sharing!

**Comment by mkm17** [comment]
To match the current list in the documentation, the following row can be added.

| **UsageInfo** **SPUsageInfo**                                                                       | [SP.UsageInfo.storage property (sp.js)](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245691(v=office.15))                  | `…/_api/site/usage`                                                                                                                                                            |
