### ISSUE TITLE
SharePoint Online Search REST API parameter sortlist is causing an error

### ISSUE THREAD

**Issue by mcgeeky** [SharePoint/sp-dev-docs#9728]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Starting 30th May, reports have come in from customers that a search query is no longer working in our app. I have isolated the issue to the sortlist parameter of the SharePoint search API (https://learn.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets)

The error received when running the query is <m:error xmlns:m= http://schemas.microsoft.com/ado/2007/08/dataservices/metadata><m:code>-1, Microsoft.Office.Server.Search.REST.SearchServiceException</m:code>

So far the issue has been reported in EU tenants.

### Steps to reproduce

1. Open your browser and navigate to SharePoint
2. Enter the following query but changing "YOURDOMAIN" to your SharePoint Online tenant

https://YOURDOMAIN.sharepoint.com/_api/search/query?querytext='contentclass:STS_Site+(WebTemplate:GROUP OR WebTemplate:TEAMCHANNEL)'&sortlist='[docid]:ascending'

3. An error message should show in the browser
4. Now run the following query that does not have the sortlist parameter, again changing YOURDOMAIN to your SharePoint Online domain:

https://YOURDOMAIN.sharepoint.com/_api/search/query?querytext='contentclass:STS_Site+(WebTemplate:GROUP OR WebTemplate:TEAMCHANNEL)'

5. The query should succeed and show XML query results

### Expected behavior

The query should show XML search results sorted by docid

**Comment by mcgeeky** [comment]
The Search API has been broken in SharePoint Online when using the sortlist parameter. This has been working for years and then breaks on 30th May. I expect a regression issue/breaking change has been introduced by Microsoft in to SharePoint Online. Can I get a response from Microsoft on this as it is affecting more organisations as the change is rolled out to more tenants globally?

**Comment by mcgeeky** [comment]
Accidentally closed it. Reopening it :)

**Comment by mcgeeky** [comment]
@AlexFilipovici Yes that is the experience we have had reported too. Within the same tenant, some users experience the issue whilst other users do not. This is consistent with the way in which Microsoft roll out changes to subsets of users/subset of servers in a cluster.

**Comment by mcgeeky** [comment]
Further commentary on this. The sortlist parameter works with [docid] when the square brackets are removed i.e. `sortlist='docid:ascending'` works where `sortlist='[docid]:ascending'` does not. This is a breaking change. Documentation on the use of docid clearly shows that it is to be used [with square brackets](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets).

This is from the documentation for [docid] usage as of 2024-06-04:

`GET http://{site_url}/_api/search/query?querytext='sharepoint'&amp;sortlist='[docid]:ascending'`

This change in the API behaviour has led to broken functionality and impact on end users. Microsoft team: can you please comment on this?

**Comment by mcgeeky** [comment]
Here is further evidence from the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets) that docid is to be enclosed in square brackets.

<img width="631" alt="Screenshot 2024-06-04 143329" src="https://github.com/SharePoint/sp-dev-docs/assets/58444997/0e3933fa-00c3-469f-b3de-73ffc226652e">

Microsoft: are you going to revert the breaking change?

**Comment by AlexFilipovici** [comment]
> Further commentary on this. The sortlist parameter works with [docid] when the square brackets are removed i.e. `sortlist='docid:ascending'` works where `sortlist='[docid]:ascending'` does not. This is a breaking change. Documentation on the use of docid clearly shows that it is to be used [with square brackets](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/pagination-for-large-result-sets).
> 
> This is from the documentation for [docid] usage as of 2024-06-04:
> 
> `GET http://{site_url}/_api/search/query?querytext='sharepoint'&amp;sortlist='[docid]:ascending'`
> 
> This change in the API behaviour has led to broken functionality and impact on end users. Microsoft team: can you please comment on this?

I also tried that yesterday and noticed that there's no error, but I didn't have time / resources to test if the results are similar with the results returned before the breaking change.

**Comment by mcgeeky** [comment]
> I also tried that yesterday and noticed that there's no error, but I didn't have time / resources to test if the results are similar with the results returned before the breaking change.

Yes that it what concerns me; is the behaviour the same as docid without square brackets and [docid] with square brackets? It is not clear. Microsoft really need to comment on this.

**Comment by mcgeeky** [comment]
@VesaJuvonen FYI

**Comment by AlexFilipovici** [comment]
@mcgeeky we have an open MS ticket. They recommended to remove the brackets, which we did and redeployed. That alone did not fix it.

**docid is case-sensitive** too, after the change.

**docid** or **docId** work as expected, **DocId** throws the same exception.

**Comment by mcgeeky** [comment]
@AlexFilipovici Thanks for sharing your feedback. Where did you open the ticket in the Microsoft 365 tenant portal?

Whilst their recommendation will work, it is not acceptable behaviour from Microsoft to arbitrarily change a public API un-announced caused downtime and aggravation for their own userbase. What is stopping the same team that made this change from making another un-announced change? The breaking change needs to be rolled back. @VesaJuvonen can you comment on this? Changing public APIs for a cloud-based service without prior announcement and without also updating documentation is unacceptable.

**Comment by mcgeeky** [comment]
> **docid** or **docId** work as expected, **DocId** throws the same exception.

And yet more confusion as the documentation shows that DocId is valid:

<img width="620" alt="Screenshot 2024-06-06 095607" src="https://github.com/SharePoint/sp-dev-docs/assets/58444997/cfc64452-16bf-4258-86f0-c6daac0c7c4c">

Microsoft need to explain why they have arbitrarily changed and broken the API behaviour for search.

**Comment by vishalshitole** [comment]
I am also facing this issue with one of my tenant. Search query does not work if I include SortList property, but works if I remove it from the query. This was not the case a week ago.

Moreover, I am using PnP JS, and not the REST API directly. Which puts me in the weird situation of not being able to remove the square brackets while making the request. :-(

**Comment by mcgeeky** [comment]
@vishalshitole thanks for alerting me, I confirm the same too :) That's great news the breaking change has been rolled back.

**Comment by AlexFilipovici** [comment]
> **Update**: The search query with the SortList property is now WORKING for me as it did before
> 
> How about you? @mcgeeky @AlexFilipovici

I can also confirm, it's working.
