### ISSUE TITLE
List Formatting: Clicking on a child element of the `a` element does not open the linked site in the newer? Microsoft Lists

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9753]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

In the newer? Microsoft Lists, clicking on a child element of the `a` element does not open the linked site.

![newer](https://github.com/SharePoint/sp-dev-docs/assets/51254139/e2324c50-93ae-47d8-b8c4-f975a6a593be)

In the older? Microsoft Lists, clicking on a child of the `a` element opens the linked site.

![older](https://github.com/SharePoint/sp-dev-docs/assets/51254139/5baf324c-7205-47ac-b02d-74af46525bbc)

### Steps to reproduce

1. Create a list
2. Create some items
3. Format the view with the following JSON

<details>
<summary>JSON of view formatting</summary>

``` json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "hideSelection": true,
  "hideColumnHeader": true,
  "rowFormatter": {
    "elmType": "div",
    "children": [
      {
        "elmType": "div",
        "style": {
          "font-size": "20px"
        },
        "children": [
          {
            "elmType": "div",
            "txtContent": "↓ a element"
          },
          {
            "elmType": "a",
            "style": {
              "display": "flex",
              "justify-content": "center",
              "align-items": "center",
              "width": "500px",
              "height": "300px",
              "margin": "10px"
            },
            "attributes": {
              "href": "https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference",
              "target": "_blank",
              "class": "ms-bgColor-communicationTint20 ms-bgColor-communicationTint10--hover"
            },
            "children": [
              {
                "elmType": "div",
                "style": {
                  "display": "flex",
                  "justify-content": "center",
                  "align-items": "center",
                  "width": "50%",
                  "height": "50%"
                },
                "attributes": {
                  "class": "ms-bgColor-sharedOrange10 ms-bgColor-sharedOrange20--hover"
                },
                "children": [
                  {
                    "elmType": "span",
                    "attributes": {
                      "iconName": "Link"
                    }
                  },
                  {
                    "elmType": "span",
                    "txtContent": "child element"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}
```
</details>

4. Click on the parent or child element of the displayed link

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/85730738-ac12-4fdb-9e60-709771531b60)

### Expected behavior

Clicking on a child element of the a element opens the linked site.

**Comment by tecchan1107** [comment]
Perhaps this is occurring only in the list view. In the gallery view, this phenomenon did not occur.

**Comment by patrikhellgren** [comment]
I have been seeing the same thing the last week or so.

Using this json to display a button in a column that links to another page:

```json
{
    "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
    "elmType": "div",
    "children": [
        {
            "elmType": "a",
            "attributes": {
                "class": "ms-fontColor-themePrimary ms-fontColor-themeDarker--hover",
                "href": "='https://contoso.sharepoint.com/sites/TestSite1/Lists/TestList1/AllItems.aspx?FilterField1=field1&FilterType1=Lookup&viewid=fb0fb875%2D5e69%2D4ef1%2Da68d%2D919bc53d1f44&FilterValue1=' + [$Title]"
            },
            "style": {
                "border": "none",
                "background-color": "transparent",
                "cursor": "pointer",
                "font-size": "12px"
            },
            "children": [
                {
                    "elmType": "span",
                    "attributes": {
                        "iconName": "FullHistory",
                        "title": "Show history"
                    },
                    "style": {
                        "padding-right": "6px"
                    }
                }
            ]
        }
    ]
}
```

This was working a week or so ago but had stopped working sometime during this last week.

Changing it to the following got it working again so my feeling is the same as yours that without child elements it seems to be working.

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "div",
  "children": [
    {
      "elmType": "a",
      "attributes": {
        "class": "ms-fontColor-themePrimary ms-fontColor-themeDarker--hover",
        "iconName": "FullHistory",
        "title": "Show history",
        "href": "='https://arcticfalls.sharepoint.com/sites/Egenkontroller-dev/Lists/Utfrda%20Egenkontroller/AllItems.aspx?FilterField1=afacObjectLookup&FilterType1=Lookup&viewid=fb0fb875%2D5e69%2D4ef1%2Da68d%2D919bc53d1f33&FilterValue1=' + [$Title]"
      },
      "style": {
        "text-decoration": "none",
        "border": "none",
        "background-color": "transparent",
        "padding-left": "15px",
        "padding-right": "6px",
        "cursor": "pointer",
        "font-size": "12px"
      }
    }
  ]
}
```

**Comment by ian-custom365** [comment]
Agree this is an issue and has been an issue for weeks - every tenant - and every user once the List App interface is deployed to SharePoint Lists it breaks any hyperlinked image field.  Such as this one - which simply links to SPO Sites.

![image](https://github.com/SharePoint/sp-dev-docs/assets/172779259/fbf7a86b-b6f0-4b94-9f3d-bbe7c7853033)

**Comment by tecchan1107** [comment]
I just checked and this problem has been resolved!

![sample](https://github.com/user-attachments/assets/fbdcb19e-92d9-43d4-a750-56bfb758e0e1)

I also had no problems with the column formatting links.

![sample](https://github.com/user-attachments/assets/fb2b5e49-c933-4cb8-8bb3-708204a74c62)

I will close this issue as I believe the problem has been resolved.

Thanks for the fix @shagra-ms @arkogupta 🙇‍♂️!!

**Comment by tecchan1107** [comment]
I will mentions this to both of you who have had reactions on this thread and let you know.
@Tanddant @Fedes365

**Comment by Tanddant** [comment]
Tagging @AlexanderHenkel cause I know he had some issues with this as well, but it seems to be working on my end

**Comment by AlexanderHenkel** [comment]
I can confirm that my formatted fields are working again, as intended

**Comment by Tanddant** [comment]
The issue is back on some of my tenants now 🙃

**Comment by tecchan1107** [comment]
Thanks for letting us know, Dan! This issue has recurred in my environment...😔😔😔
I will reopen this Issue.

**Comment by tecchan1107** [comment]
I checked today and was able to open the link!

![sample](https://github.com/user-attachments/assets/2a601c70-0209-4b21-b753-d0684d0104c2)

Therefore, I am closing this issue.
