### ISSUE TITLE
List Formatting: Group header cannot be clicked even when setting `defaultClick` to `headerFormatter` in `groupProps` in the newer? Microsoft Lists

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9756]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

In the newer? Microsoft Lists, I cannot click on the group header even though I set `defaultClick` to `headerFormatter` in `groupProps`.

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/f6c4c262-7e6d-40d1-b212-8b71aebe19a5)

![newer](https://github.com/SharePoint/sp-dev-docs/assets/51254139/b3dfd5d1-cbbb-4795-8e97-fb5c549bdac0)

In the older? Microsoft Lists, clicking on a group header with defaultClick set would display a view filtered by the value of that group header.

![older](https://github.com/SharePoint/sp-dev-docs/assets/51254139/3ee4d569-7729-4815-b8af-f65bc0c8b56a)[](url)

### Steps to reproduce

1. Create a list
2. Create a choice column
3. Create some items
4. Grouping by choice column created in 2.
5. Set the following JSON in the view formatting

<details>
<summary>Sample Code</summary>

``` json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "groupProps": {
    "headerFormatter": {
      "elmType": "div",
      "style": {
        "font-size": "16px",
        "cursor": "pointer",
        "padding": "5px 10px",
        "border-radius": "5px"
      },
      "customRowAction": {
        "action": "defaultClick"
      },
      "attributes": {
        "class": "ms-bgColor-themeLighter ms-bgColor-themePrimary--hover ms-fontColor-white--hover"
      },
      "children": [
        {
          "elmType": "span",
          "txtContent": "@group.fieldData.displayValue"
        },
        {
          "elmType": "span",
          "style": {
            "margin-left": "5px"
          },
          "txtContent": "=' ('+@group.count+')'"
        }
      ]
    }
  }
}
``` 

</details>

### Expected behavior

Clicking on a group header with `defaultClick` set will display a view filtered by the value of the group header, similar to the older Microsoft Lists

**Comment by z3019494** [comment]
My view formatting has been completely wrecked by the new UI.

![image](https://github.com/user-attachments/assets/862c03be-f657-4dda-8dcd-62fd08026741)

Inside the PWA:
![image](https://github.com/user-attachments/assets/65494847-cc1e-4cdf-b682-2f1bdfc3729d)

**Comment by arkogupta** [comment]
@tecchan1107 In the newer version after we made a fix, now you don't need to add the "defaultClick" action to be able to trigger the default click. The default actions are still passed through even when group header formatter is applied. We are working on a fix  to support custom actions on group formatter and will update you soon. Thanks for reporting this!

**Comment by influential-eliot** [comment]
So ... sorry to ask, but ... does that mean that it *should* work, or that it shouldn't, @arkogupta ?
> @tecchan1107 In the newer version after we made a fix, now you don't need to add the "defaultClick" action to be able to trigger the default click. Could you try removing it and clicking on the group header again? The default actions are still passed through even when group header formatter is applied. We are working on a fix to support custom actions on group formatter and will update you soon. Thanks for reporting this!

**Comment by arkogupta** [comment]
@influential-eliot As of now, if you remove the part in the JSON which has `customRowAction` with `defaultClick` as the action, clicking on the group header should filter the view. Could you please verify that once in your tenant?
As for having the same behavior _with_ the `customRowAction`, that will reach soon so that you don't have to modify your CF JSON.

**Comment by tecchan1107** [comment]
Thanks for letting me know and for the fix @arkogupta 🙏✨️
Removing `defaultClick` resulted in a filtered view!

![sample](https://github.com/user-attachments/assets/28cb1976-1be4-40e3-8d9f-dfdb61fa45d8)

In the above video, I used the following code:

<details>

<summary>Sample Code</summary>

``` json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "groupProps": {
    "headerFormatter": {
      "elmType": "div",
      "style": {
        "font-size": "16px",
        "cursor": "pointer",
        "padding": "5px 10px",
        "border-radius": "5px"
      },
      "attributes": {
        "class": "ms-bgColor-themeLighter ms-bgColor-themePrimary--hover ms-fontColor-white--hover"
      },
      "children": [
        {
          "elmType": "span",
          "txtContent": "@group.fieldData.displayValue"
        },
        {
          "elmType": "span",
          "style": {
            "margin-left": "5px"
          },
          "txtContent": "=' ('+@group.count+')'"
        }
      ]
    }
  }
}
```

</details>

May I ask one more thing if possible? Conversely, is it possible to prevent a filtered view from being displayed?

**Comment by influential-eliot** [comment]
Hi, @arkogupta ... I think as @tecchan1107 is showing ... that is still not a 'fixed' view.

The intent is simple, tapping '`Choice 1 (3)`' in this image should make the results below it 'accordian' up and out of view, but not affect those beneath the '`Choice 2 (3)`' and '`Choice 3 (3)`' options.
![tecchan1107's image](https://private-user-images.githubusercontent.com/51254139/356464988-28cb1976-1be4-40e3-8d9f-dfdb61fa45d8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA5MzAsIm5iZiI6MTcyMzE5MDYzMCwicGF0aCI6Ii81MTI1NDEzOS8zNTY0NjQ5ODgtMjhjYjE5NzYtMWJlNC00MGUzLThkOWYtZGZkYjYxZmE0NWQ4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZmM2MGIxMTY0MDE1YjM3N2ZmZjQxODM3YmE3NDQwYjIzMjQ3YTg1ZGYzYzE2ZmYyZWU3M2NkMzI4OTJjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QgtBQLRBgXJpBfeCLBeK-dzFoyPqsKQs3OmPc3r-A0k)

If this is not the case, then I think that my suggestion should be unlinked from this, as this I am purely talking clear and obvious UX/UI functionality that we should be able to (_and possibly previously were_) affect using the JSON view formatting. You tap the word, it performs the same action as the chevron to the left of it.

**Comment by arkogupta** [comment]
@tecchan1107 @influential-eliot So in our older version, due to some limitations overriding the group header using custom formatting completely changed its behavior (including its default actions like clicking to filter it), and hence we needed to use the "defaultClick" action to be able to get that behavior back.
We currently support the `defaultClick` out of the box even when the group header has been rendered using custom formatter. Wanted this feedback from you as experienced users - 
Which one of both cases do you think is more intuitive? The older pattern or the new one?(There is one bug which will be fixed soon in which adding the defaultClick action is preventing the actions)

**Comment by influential-eliot** [comment]
@arkogupta ... unfortunately from this response it's hard to understand right now.

I will have to try it again. I'll come back when I have.

**Comment by z3019494** [comment]
> My view formatting has been completely wrecked by the new UI.
> 
> ![image](https://private-user-images.githubusercontent.com/60587625/356121012-862c03be-f657-4dda-8dcd-62fd08026741.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjU5MDAsIm5iZiI6MTcyMzI2NTYwMCwicGF0aCI6Ii82MDU4NzYyNS8zNTYxMjEwMTItODYyYzAzYmUtZjY1Ny00ZGRhLThkY2QtNjJmZDA4MDI2NzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Zjk1NTNiOTA2NGQzODA3MzFhYjQzZGRjNWQ3ZjA1YmMxZjMyM2ZlYjE1OWY2M2JkZTAxNDc5Nzg5MGY1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HmcMajqvjn5V0CnV5IbOcF_CxXY_loX18ns3J4gawf0)
> 
> Inside the PWA: ![image](https://private-user-images.githubusercontent.com/60587625/356122012-65494847-cc1e-4cdf-b682-2f1bdfc3729d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjU5MDAsIm5iZiI6MTcyMzI2NTYwMCwicGF0aCI6Ii82MDU4NzYyNS8zNTYxMjIwMTItNjU0OTQ4NDctY2MxZS00Y2RmLWI2ODItMmYxYmRmYzM3MjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZTRmYWY2NjAwOWQ0MjU0ZWY2Y2Y3NmZjNWFlZWY2NmFhMjJiZWM0MmUyNjU3MzA1MDRiNjc5YTFkODhhNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WT-peSa1AH9YaJmQNgGYcQZ2dnm4SFCM8VB5MbHnqDw)

@tecchan1107 - do you think I should raise a new issue for this, or keep it in this issue?

**Comment by XueSheng-GIT** [comment]
> Which one of both cases do you think is more intuitive? The older pattern or the new one?(There is one bug which will be fixed soon in which adding the defaultClick action is preventing the actions)

@arkogupta from a user point of I would expect that the default behaviour of groupProps/headerFormatter is the same as in the regular view (click on a header to filter). An additional customRowAction would make sense to add additional/different behaviour (like the mentioned unfold/collapse).

What's really missing at the moment is the possibility to format the header in case of two grouped columns (which is currently the limit). It should be possible to format the "outter" group (1st level) differently than the "inner" group (2nd level). You can only workaround that by checking for the column name but then you can only use this custom format for a really specific usecase.

It would also be good to have something like `isSelected` or `isCollapsed` available to be able to highlight groups you are working in.

Does it make sense to create additional issues regarding the missing features? Or will it be a "not planned" anyways?

**Comment by tecchan1107** [comment]
> @tecchan1107 - do you think I should raise a new issue for this, or keep it in this issue?

@z3019494 
I believe your issue is a different problem from this one, so I think it would be better to create a new issue!

**Comment by tecchan1107** [comment]
> Which one of both cases do you think is more intuitive? The older pattern or the new one?(There is one bug which will be fixed soon in which adding the defaultClick action is preventing the actions)

@arkogupta 
I guess it is a matter of familiarity, but I find the old pattern more intuitive and easier to understand.

Also, I'm curious whether it's necessary to set `defaultClick` when formatting columns that already have default behaviors, such as the Title column, using a new pattern.

For example, I think if `defaultClick` is not needed for formatting a group column but is required for the Title column, this inconsistency in specifying default behaviors could cause confusion during coding.

**Comment by XueSheng-GIT** [comment]
> @arkogupta Was there any update in the meantime? Lately filtering items was working as explained by you ([#9756 (comment)](https://github.com/SharePoint/sp-dev-docs/issues/9756#issuecomment-2275762001)). Since yesterday filtering does not work anymore by clicking on a group header. Adding `customRowAction` with `defaultClick` does not seem to work either.

I double checked again and adding `defaultClick` seems to work now. Maybe I had a typo when trying yesterday.

<details>
<summary>Example of initial report</summary>

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "groupProps": {
    "headerFormatter": {
      "elmType": "div",
      "style": {
        "font-size": "16px",
        "cursor": "pointer",
        "padding": "5px 10px",
        "border-radius": "5px"
      },
      "customRowAction": {
        "action": "defaultClick"
      },
      "attributes": {
        "class": "ms-bgColor-themeLighter ms-bgColor-themePrimary--hover ms-fontColor-white--hover"
      },
      "children": [
        {
          "elmType": "span",
          "txtContent": "@group.fieldData.displayValue"
        },
        {
          "elmType": "span",
          "style": {
            "margin-left": "5px"
          },
          "txtContent": "=' ('+@group.count+')'"
        }
      ]
    }
  }
}
```

</details>

@arkogupta I would appriciate if you could explain/confirm if this is now the intended behaviour and whether there are alternative options for `defaultClick`.
Thanks a lot for taking care of our issues!

**Comment by arkogupta** [comment]
Thank you all! Marking the issue as closed now.

**Comment by tecchan1107** [comment]
I just checked and the filtered view appears when I add a `default` action as before! Thanks for the notice and the fix @arkogupta !

![sample](https://github.com/user-attachments/assets/f2cbcd9e-bc51-480d-ba2b-40d8a40a3063)

I will close this issue.
