### ISSUE TITLE
List Formatting: Question about embeddable sites using the `embed` action

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9766]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

When using the `embed` action, you can embed and display a site specified in the `src` attribute's URL. 

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/c3a559b4-9d6b-42a2-b6be-a9f670cc2bd4)

However, there are sites that can and cannot be embedded. For example, you can embed https://www.youtube.com/embed/pwnW68PN2sU?si=rzigqVDQSCHTi0pB, but you cannot embed https://www.youtube.com/watch?v=pwnW68PN2sU. 

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/52446666-fe21-4760-a472-e0c80424c52b)

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/f1cddcfb-c330-4678-ab7f-bd7957ece7a8)

Is this determination based on the value of the [X-Frame-Options](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Frame-Options) property of the site specified in the `src` attribute?

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/1b278b4f-e33f-4e95-86c6-fef7d9ea9e3a)

**Comment by XueSheng-GIT** [comment]
@tecchan1107 did add those sites you want to add to the "white list"?
https://go.microsoft.com/fwlink/p/?linkid=2258033

**Comment by tecchan1107** [comment]
> did add those sites you want to add to the "white list"?

Yes! Currently, I can display embedded sites, and I would like to know the conditions or settings of sites that can display embedded sites!

**Comment by tecchan1107** [comment]
> did add those sites you want to add to the "white list"?

Yes, I did! However, some sites cannot display embedded. (I assume that these sites that cannot be embedded are those that do not have the X-Frame-Options property set. But this is only my guess. I would like to know this exact information if possible!).

**Comment by arkogupta** [comment]
@tecchan1107 That's a good question. Think of the "src" property same as the "src" attribute you'd give to an <iframe> element. The X-Frame-Options being set or not depends on the source and it is not something we control as part of the list/JSON. Hope that helps!

**Comment by tecchan1107** [comment]
I understand! Thank you for your responses as always @arkogupta !
