### ISSUE TITLE
SPFx List View Command Set with custom dialog boxes not rendering

### ISSUE THREAD

**Issue by RBo08F** [SharePoint/sp-dev-docs#9776]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Edge 126.0.2592.68
- SPFx version: 1.19.0
- Node.js version: v18.20.3
- etc

### Issue description

I have the same issue as described at https://github.com/SharePoint/sp-dev-docs/issues/8968, but with the new version.

The command set works, but after adding and using(!) the custom dialog based on `BaseDialog` the command the button disappears. If I remove the initialization of the custom dialog and replace this part with a `Dialog.alert` the button is back again.

For testing I followed the guide: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx.

The dependencies I modified similar to the advice in the old post (but with the current versions):
`"dependencies": {
    "@fluentui/react": "^7.204.0",
    "@microsoft/decorators": "1.19.0",
    "@microsoft/sp-core-library": "1.19.0",
    "@microsoft/sp-dialog": "1.19.0",
    "@microsoft/sp-listview-extensibility": "1.19.0",
    "office-ui-fabric-react": "^7.204.0",
    "tslib": "2.3.1",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.20.1",
    "@microsoft/eslint-plugin-spfx": "1.20.1",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.20.1",
    "@microsoft/sp-module-interfaces": "1.20.1",
    "@rushstack/eslint-config": "2.5.1",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "gulp": "4.0.2",
    "typescript": "4.7.4",
    "@types/react": "17.0.80",
    "@types/react-dom": "17.0.25"
  }`

Any advice would be nice.

**Comment by harshdamaniahd** [comment]
I am also having the same issue

**Comment by CodeABao** [comment]
same issues

**Comment by Christian1140** [comment]
Does anyone have a solution for this problem?

**Comment by MattNolan** [comment]
Same issue here - is there any solution?

**Comment by Christian1140** [comment]
I found a solution für this problem.
1. Using react 17.0.2 is not a good idea, because not supported. So I downgraded with:
`npm install react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact`

1. Using `office-ui-fabric-react` as used in the Microsoft tutorial is deprecated. So I changed my code to use `fluentui/react` instead.

**Comment by RBo08F** [comment]
> I found a solution for this problem.
> 
> 1. Using react 17.0.2 is not a good idea, because not supported. So I downgraded with:
>    `npm install react@17.0.1 react-dom@17.0.1 @types/react@17.0.45 @types/react-dom@17.0.17 --save-exact`
> 2. Using `office-ui-fabric-react` as used in the Microsoft tutorial is deprecated. So I changed my code to use `fluentui/react` instead.
> 
> Now the buttons are visible and my custom dialog opens.

Works :)
