### ISSUE TITLE
Webpack issue in SPFx

### ISSUE THREAD

**Issue by JayakumarB** [SharePoint/sp-dev-docs#979]
I'm receiving this error from yesterday while building SPFx package, i don't find any webpack config to do the settings, how to fix this issue ?

Starting subtask 'webpack'...
(node:22760) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils

**Comment by andrewconnell** [comment]
This isn't an error... look at the message. It clearly says `DeprecationWarning`... 

You can safely ignore this... nothing for us to do, that's something for MSFT to deal with.

**Comment by iclanton** [comment]
This is something we've been aware of for a while, but because nothing is actually broken, we haven't prioritized addressing it. If it starts to cause problems, we'll certainly take a look at it immediately.

**Comment by nickpape-msft** [comment]
This is an issue in a second level dependency we are using. Essentially, one of our dependencies is accessing a function that someone else deprecated in a patch release (c'est la vie with Semantic Versioning). One way to fix this would be to pin "loader-utils" back (probably to `0.1.16`), by adding a specific version to your package.json.

We ended up fixing this in late November, so the next release will not have this issue.

**Comment by nickpape-msft** [comment]
This appears to be fixed in latest release.
