### ISSUE TITLE
Additional property on context: Site's Tenant Id

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#98]
Can we get the Office 365 tenancy Id (the Guid that the Graph would recognise).

This is super useful in the following scenarios.
- Telemetry
- Extranet scenarios in B2B so you know where the user originates
- Using the MS Graph once it comes

**Comment by patmill** [comment]
If you wait long enough, we listen :)  .  This is actually available now on the context.  Both the SiteSubscriptionId and the AADTenantID.  For now, you need to look at the LegacyContext property.
