### ISSUE TITLE
List view formatting: usage of commandBarProps hides "Details" in context menu (MS lists view in Sharepoint list)

### ISSUE THREAD

**Issue by XueSheng-GIT** [SharePoint/sp-dev-docs#9809]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Chrome 126 (but it seems not to be browser related issue)

### Describe the bug / error

If [commandBarProps ](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting) are added the to the json list view, it is not possible to access the details pane anymore (button to access hides within context menu).

Context menu of a list item (**without** commendBarProps defined):
"Details" available!
![Details entry available](https://github.com/user-attachments/assets/922ad546-ad97-4ed0-9a2f-11fb77ec1771)

Context menu of a list item (**with** commendBarProps defined):
"Details" **not** available!
![Details entry missing](https://github.com/user-attachments/assets/b3bbb148-ab82-4a03-bf04-d753070d11cc)

According to the official documentation (linked above) there's no key available to control the details pane. **But, adding the commandBarProps should not affect unrelated items.**

### Steps to reproduce

1. Open SharePoint List (new MS List View)
2. Apply following json to view:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
  "commandBarProps": {
    "commands": [
      {
        "key": "edit",
        "hide": "false"
      }
    ]
  }
}
```
4. Reload page and open the context menu of one list item.

### Expected behavior

"Details" should be available in context menu to open the details pane on the right side of the list.
Instead the entry "Details" is not available.

Maybe somehow related: https://github.com/SharePoint/sp-dev-docs/issues/9711

**Comment by tpodugu-ms** [comment]
@XueSheng-GIT Thanks for reporting the issue. Issue is fixed and will be available in production in 2 weeks.

**Comment by XueSheng-GIT** [comment]
Selection of `Details` is now available again in in our production environment. Thus, I'm closing this issue.
Thanks for taking care @tpodugu-ms.
