### ISSUE TITLE
Link column in SharePoint list not opening/working

### ISSUE THREAD

**Issue by Zakchap2020** [SharePoint/sp-dev-docs#9822]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Intermittent issue with SharePoint link columns, when click the value in the link column it no longer directs the user to that url instead it does nothing

### Steps to reproduce

1. Create/find a column type of link 
2. Add/find an existing value
3. Click it
4. Sometimes it does work so try refreshing a few times to recreate

### Expected behavior

Clicking the link value won't direct you to the url

**Comment by Zakchap2020** [comment]
Works for some users and not others but is not static seems to intermittently happen to all users in the tenant

**Comment by rmillener** [comment]
We're also seeing this in the new list experience with the following error:

Uncaught Error: The "context" object cannot be used because it has been disposed.

**Comment by Zakchap2020** [comment]
Seems like this issue is now fixed
