### ISSUE TITLE
 Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.

### ISSUE THREAD

**Issue by sohotra** [SharePoint/sp-dev-docs#983]
#### Category
- [1 ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I'm getting this error, still new to the whole front-end development, so I'm not sure where exactly this is occurring. The error comes up when I run the _gulp package-solution --ship_ command, no issues when I run the _gulp build --ship_

I did go through the config.json file which looks OK, compared it with another webpart that is working without any issues.

#### Steps to Reproduce
Don't think you can reproduce this, it's not the framework, it's just me.

**Comment by sohotra** [comment]
Sorry, as dumb as it sounds, looks like all I had to do was:

gulp clean
gulp build
gulp bundle --ship
gulp package-solution --ship

**Comment by lhoff** [comment]
This isn't your fault -- Microsoft needs to edit their exception message so that it actually mentions the bundle step. Otherwise, the error message is misleading.
