### ISSUE TITLE
expanding/collapsing of grouped SharePoint view causes information to become not visible

### ISSUE THREAD

**Issue by MSFT-klpinhac** [SharePoint/sp-dev-docs#9839]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browsers have been up-to-date in July 2024 ( i will provide the browser-versions later on )

### Describe the bug / error

The display of a SharePoint-List with a FAQ has been customized using the JSON available at: 
https://github.com/pnp/list-formatting/tree/master/view-samples/faq-accordion

If a user is expanding / collapsing multiple entries inside the grouped SharePoint view, some entries of the List / FAQ are "lost" ( i.e. the question / title is no longer displayed ).  

### Steps to reproduce

There is no definitive way to reproduce this issue, but the quicker the categories are expanded / collapsed, the higher the chance the title is no longer displayed.
![Screenshot 2024-07-19 101808](https://github.com/user-attachments/assets/e1934a34-d470-4b95-81d9-f9cdb2ed69ff)
The "lost" information will be displayed after a reload the SharePoint List in the webbrowser. 

### Expected behavior

it would be great if all of the information would be displayed no matter how quick a user is expanding / collapsing entries inside the SharePoint view

**Comment by arkogupta** [comment]
@MSFT-klpinhac What is the field on which the view is grouped? Do you have multiple "Title" fields?
Also, could you please add `"debugMode": true` to the root of the formatter part of the JSON? https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#debugmode
And see if there is some error logged ?

**Comment by MSFT-klpinhac** [comment]
Here is the code used for the customized view:
```
				{
				   "$schema": " https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
				   "hideSelection": true,
				   "hideColumnHeader": true,
				   "hideListHeader": true,
				   "groupProps": {
				       "headerFormatter": {
				           "elmType": "div",
				           "attributes": {
				               "class": "sp-row-card"
				           },
				           "style": {
				               "color": "black",
				               "background-color": "#FAF9F9",
				               "flex-grow": "1",
				               "display": "flex",
				               "flex-direction": "row",
				               "box-sizing": "border-box",
				               "padding": "4px 8px 5px 8px",
				               "border-radius": "6px",
				               "align-items": "center",
				               "flex-wrap": "nowrap",
				               "overflow": "auto",
				               "margin": "1px 4px 4px 1px",
				               "min-width": "400px"
				           },
				           "children": [
				               {
				                   "elmType": "img",
				                   "style": {
				                       "max-width": "24px",
				                       "max-height": "24px",
				                       "margin-top": "2px",
				                      "border-radius": "2px"
				                   }
				               },
				               {
				                   "elmType": "div",
				                   "children": [
				                       {
				                          "elmType": "span",
				                           "style": {
				                              "padding": "5px 5px 5px 5px",
				                              "display": "=if(@group.columnDisplayName == 'Category', 'inherit', 'none')",
				                              "font-weight": "500",
				                              "font-size": "15px"
				                           },
				                          "txtContent": "='Category: ' + @group.fieldData.lookupValue"
				                       },
				                       {
				                          "elmType": "span",
				                           "style": {
				                              "padding": "5px 5px 5px 25px",
				                              "display": "=if(@group.columnDisplayName == 'Title', 'inherit', 'none')",
				                              "font-weight": "500",
				                              "font-size": "15px"
				                           },
				                          "txtContent": "='Question: ' + @group.fieldData.displayValue"
				                       }
				                   ]
				               },
				               {
				                   "elmType": "div",
				                   "children": [
				                       {
				                          "elmType": "div",
				                           "style": {
				                              "display": "flex",
				                              "flex-direction": "column",
				                              "justify-content": "center"
				                           }
				                       }
				                   ]
				               }
				           ]
				       }
				   },
				   "rowFormatter": {
				       "elmType": "div",
				       "attributes": {
				           "class": "ms-bgColor-themeLighterAlt"
				       },
				       "style": {
				           "justify-content": "start",
				           "color": "ms-fontColor-Primary",
				           "display": "flex",
				           "padding": "1px 8px 5px 20px",
				           "border-radius": "6px",
				           "max-width": "905px",
				           "margin": "1px 4px 4px 120px"
				       },
				       "children": [
				           {
				               "elmType": "div",
				               "style": {
				                   "text-align": "left",
				                   "font-weight": "400",
				                   "font-size": "15px"
				               },
				               "children": [
				                   {
				                       "elmType": "span",
				                       "style": {
				                          "margin-top": "8px",
				                          "padding-left": "1px",
				                           "color": "green"
				                       },
				                       "attributes": {
				                           "class": "ms-fontSize-m",
				                          "iconName": "Lightbulb"
				                       }
				                   },
				                   {
				                       "elmType": "span",
				                       "attributes": {
				                           "class": "sp-row-listPadding"
				                       },
				                       "txtContent": "Answer",
				                       "style": {
				                          "font-weight": "500",
				                           "color": "green",
				                          "padding-left": "4px"
				                       }
				                   },
				                   {
				                       "elmType": "div",
				                       "attributes": {
				                           "class": "sp-row-listPadding"
				                       },
				                       "txtContent": "[$Answer]",
				                       "style": {
				                          "flex-grow": "1",
				                          "display": "flex",
				                          "flex-direction": "column",
				                          "flex-wrap": "nowrap",
				                          "align-items": "left",
				                          "max-width": "900px",
				                          "min-width": "205px",
				                          "margin-top": "8px",
				                          "margin-bottom": "8px"
				                       }
				                   },
				                   {
				                       "elmType": "a",
				                       "txtContent": "='open link: ' + [$Weblink]",
				                       "attributes": {
				                           "target": "_blank",
				                           "href": "[$Weblink]"
				                       },
				                       "style": {
				                          "display": "=if([$Weblink] != '', 'block', 'none')"
				                       }
				                   }
				               ]
				           }
				       ]
				   },
				   "commandBarProps": {
				       "commands": [
				           {
				               "key": "new",
				               "hide": true
				           },
				           {
				               "key": "edit",
				               "hide": true
				           },
				           {
				               "key": "copyLink",
				               "hide": true
				           },
				           {
				               "key": "comment",
				               "hide": true
				           },
				           {
				               "key": "upload",
				               "hide": true
				           },
				           {
				               "key": "delete",
				               "hide": true
				           },
				           {
				               "key": "sync",
				               "hide": true
				           },
				           {
				               "key": "addShortcut",
				               "hide": true
				           },
				           {
				               "key": "undo",
				               "hide": true
				           },
				           {
				               "key": "share",
				               "hide": true
				           },
				           {
				               "key": "export",
				               "hide": true
				           },
				           {
				               "key": "automate",
				               "hide": true
				           },
				           {
				               "key": "integrate",
				               "hide": true
				           },
				           {
				               "key": "versionHistory",
				               "hide": true
				           },
				           {
				               "key": "manageForms",
				               "hide": true
				           },
				           {
				               "key": "editInGridView",
				               "hide": true
				           },
				           {
				               "key": "pinToQuickAccess",
				               "hide": true
				           }
				       ]
				   }
}
```

The view is grouped by "Category" and "Title"
![Screenshot 2024-08-14 102401](https://github.com/user-attachments/assets/0f07f774-a3f4-4099-9db2-84d947459a64)

**Comment by MSFT-klpinhac** [comment]
in Microsoft Edge Version 127.0.2651.98 (Official build) (64-bit), adding `"debugMode": true` does not seem to make a difference - the following errors are shown in the console of the Browser
<img width="305" alt="Screenshot 2024-08-14 102647" src="https://github.com/user-attachments/assets/0d74d42e-9200-4dae-bf39-4094cd7dc137">

You should be able to reproduce the issue by expanding a category, expanding a title, expand a category above the expanded title  and collapse that category again - that should lead to the described "loss" of data

**Comment by MSFT-klpinhac** [comment]
oh, i thought a repro should be easy - there are no lookup or hyperlink fields in the list, here's a screenshot of the fields in the SharePoint List:
![image (3)](https://github.com/user-attachments/assets/8f0869f1-3b17-443e-8036-0b8295e64dcd)

**Comment by arkogupta** [comment]
@MSFT-klpinhac Could you please share the above in case the issue still repros ?

**Comment by MSFT-klpinhac** [comment]
you can use the same Excel-sheet as in https://github.com/SharePoint/sp-dev-docs/issues/9901#issuecomment-2360527902 
and use this JSON to format another view:
  `{
    "$schema": " https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
    "hideSelection": true,
    "hideColumnHeader": true,
    "hideListHeader": true,
    "groupProps": {
      "headerFormatter": {
        "elmType": "div",
        "attributes": {
          "class": "sp-row-card"
        },
        "style": {
          "color": "black",
          "background-color": "#FAF9F9",
          "flex-grow": "1",
          "display": "flex",
          "flex-direction": "row",
          "box-sizing": "border-box",
          "padding": "4px 8px 5px 8px",
          "border-radius": "6px",
          "align-items": "center",
          "flex-wrap": "nowrap",
          "overflow": "auto",
          "margin": "1px 4px 4px 1px",
          "min-width": "400px"
        },
        "children": [
          {
            "elmType": "img",
            "style": {
              "max-width": "24px",
              "max-height": "24px",
              "margin-top": "2px",
              "border-radius": "2px"
            }
          },
          {
            "elmType": "div",
            "children": [
              {
                "elmType": "span",
                "style": {
                  "padding": "5px 5px 5px 5px",
                  "display": "=if(@group.columnDisplayName == 'pubDate', 'inherit', 'none')",
                  "font-weight": "500",
                  "font-size": "15px"
                },
                "txtContent": "='pubDate: ' + @group.fieldData.lookupValue"
              },
              {
                "elmType": "span",
                "style": {
                  "padding": "5px 5px 5px 25px",
                  "display": "=if(@group.columnDisplayName == 'Title', 'inherit', 'none')",
                  "font-weight": "500",
                  "font-size": "15px"
                },
                "txtContent": "='Title: ' + @group.fieldData.displayValue"
              }
            ]
          },
          {
            "elmType": "div",
            "children": [
              {
                "elmType": "div",
                "style": {
                  "display": "flex",
                  "flex-direction": "column",
                  "justify-content": "center"
                }
              }
            ]
          }
        ]
      }
    },
    "rowFormatter": {
      "elmType": "div",
      "attributes": {
        "class": "ms-bgColor-themeLighterAlt"
      },
      "style": {
        "justify-content": "start",
        "color": "ms-fontColor-Primary",
        "display": "flex",
        "padding": "1px 8px 5px 20px",
        "border-radius": "6px",
        "max-width": "905px",
        "margin": "1px 4px 4px 120px"
      },
      "children": [
        {
          "elmType": "div",
          "style": {
            "text-align": "left",
            "font-weight": "400",
            "font-size": "15px"
          },
          "children": [
            {
              "elmType": "span",
              "style": {
                "margin-top": "8px",
                "padding-left": "1px",
                "color": "green"
              },
              "attributes": {
                "class": "ms-fontSize-m",
                "iconName": "Lightbulb"
              }
            },
            {
              "elmType": "span",
              "attributes": {
                "class": "sp-row-listPadding"
              },
              "txtContent": "Description",
              "style": {
                "font-weight": "500",
                "color": "green",
                "padding-left": "4px"
              }
            },
            {
              "elmType": "div",
              "attributes": {
                "class": "sp-row-listPadding"
              },
              "txtContent": "[$Description]",
              "style": {
                "flex-grow": "1",
                "display": "flex",
                "flex-direction": "column",
                "flex-wrap": "nowrap",
                "align-items": "left",
                "max-width": "900px",
                "min-width": "205px",
                "margin-top": "8px",
                "margin-bottom": "8px"
              }
            },
            {
              "elmType": "a",
              "txtContent": "='open link: ' + [$Link]",
              "attributes": {
                "target": "_blank",
                "href": "[$Link]"
              },
              "style": {
                "display": "=if([$Link] != '', 'block', 'none')"
              }
            }
          ]
        }
      ]
    },
    "commandBarProps": {
      "commands": [
        {
          "key": "new",
          "hide": true
        },
        {
          "key": "edit",
          "hide": true
        },
        {
          "key": "copyLink",
          "hide": true
        },
        {
          "key": "comment",
          "hide": true
        },
        {
          "key": "upload",
          "hide": true
        },
        {
          "key": "delete",
          "hide": true
        },
        {
          "key": "sync",
          "hide": true
        },
        {
          "key": "addShortcut",
          "hide": true
        },
        {
          "key": "undo",
          "hide": true
        },
        {
          "key": "share",
          "hide": true
        },
        {
          "key": "export",
          "hide": true
        },
        {
          "key": "automate",
          "hide": true
        },
        {
          "key": "integrate",
          "hide": true
        },
        {
          "key": "versionHistory",
          "hide": true
        },
        {
          "key": "manageForms",
          "hide": true
        },
        {
          "key": "editInGridView",
          "hide": true
        },
        {
          "key": "pinToQuickAccess",
          "hide": true
        }
      ]
    }
  }`

**Comment by arkogupta** [comment]
@MSFT-klpinhac Let me know if you and the customer can still reproduce this problem. If yes please help us replicate it, thanks!
