### ISSUE TITLE
App Hub Application Stopped Working,  it was deployed to Teams in February 2024 when it worked flawlessly untill July 2024

### ISSUE THREAD

**Issue by BrucedeMink** [SharePoint/sp-dev-docs#9843]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

VS Code, 
 - Node : 16.20.2
 - NVM : 1.1.12
 - Build tools version: 3.18.1
SPFx, 
Teams Toolkit, 
 - Project app-hub version:0.0.2
SharePoint Online

### Describe the bug / error

The app rendered the SharePoint list with the use of  TypeScript/JavaScript/jQuery, into a graphical representation of the list of linkages logged in the SharePoint List.
 
![image](https://github.com/user-attachments/assets/adba870d-0bb9-461b-a1ab-ff5b9cf3455a)

This was working perfectly until the first week of July and since then it has stopped rendering the links and looks like this.
 
![image](https://github.com/user-attachments/assets/155d4520-b3a9-4282-8192-5dfa3dc46473)

Sorry, something went wrong
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
TECHNICAL DETAILS
Error details: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')
[Troubleshoot issues with Microsoft SharePoint Foundation.](javascript:HelpWindowKey('WSSEndUser_troubleshooting'))
Correlation ID: 564d43a1-c08c-9000-a2f1-704aad0a5276
Date and Time: 8/5/2024 6:09:19 AM
The warning indicates that there is an issue connecting to the SharePoint resource. I have opened the web version of Teams to investigate further, in the developer's tools I found the following.
Errors: 
 
![image](https://github.com/user-attachments/assets/80ffb830-949a-4767-90f0-581f40391cbf)

Warnings:
 
![image](https://github.com/user-attachments/assets/86fd007e-d952-4654-bd8b-8c7a77d9469d)

Information: 
 
![image](https://github.com/user-attachments/assets/8beeaff8-3480-452d-b32c-bde8c67e9ba9)

There are authorized connections using tokens being displayed.
Which makes me question the connections being made to the SharePoint site to retrieve the data.
There are 3 errors from Precompiled-web-work…js, flowed by a 403 error which is a connection to graph.microsoft.com which I assume is a denial of connection to the SharePoint API, which I use in the TypeScript code:
 
![image](https://github.com/user-attachments/assets/c1d3f5d3-616b-405a-804c-74f91a6ba92e)

The next error Refused to compile or instantiate Web Assembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-R+g9VdMVCZC/eeynejoLZg==' 'report-sample' 'self' https://statics.teams.cdn.office.net/
Details a Policy instructing the denial of connection followed by 4 SharePoint JSON [Object Object] validation error because the code is returning a blank key: value pair array.

Assuming that a further “handshake” was required (either an access token or initiation using SSO) I tried to re-authenticate and tokenize the SharePoint connection request, this failed due to a CORS violation and late finding out that it was not required and a simple spHttpClient request would suffice to facilitate the REST API. However other people are having a 403 connection error to SharePoint Lists

### Steps to reproduce

The  Production App
1) Click on Icon
2) page would have loaded
3) Error loads

The Dev 
1) Click On Environment local.
2) Same error page loads.

if you open Terminal and run gulp serve
the images in the application load

### Expected behavior

The App is meant to look like this:
![image](https://github.com/user-attachments/assets/6a4e46d3-058f-41f5-bc04-3ba5a7f86515)

**Comment by BrucedeMink** [comment]
> ### Target SharePoint environment
> SharePoint Online
> 
> ### What SharePoint development model, framework, SDK or API is this about?
> 💥 SharePoint Framework
> 
> ### Developer environment
> Windows
> 
> ### What browser(s) / client(s) have you tested
> * [ ]  💥 Internet Explorer
> * [x]  💥 Microsoft Edge
> * [x]  💥 Google Chrome
> * [x]  💥 FireFox
> * [ ]  💥 Safari
> * [ ]  mobile (iOS/iPadOS)
> * [ ]  mobile (Android)
> * [ ]  not applicable
> * [ ]  other (enter in the "Additional environment details" area below)
> 
> ### Additional environment details
> VS Code,
> 
> * Node : 16.20.2
> * NVM : 1.1.12
> * Build tools version: 3.18.1
>   SPFx,
>   Teams Toolkit,
> * Project app-hub version:0.0.2
>   SharePoint Online
> 
> ### Describe the bug / error
> The app rendered the SharePoint list with the use of TypeScript/JavaScript/jQuery, into a graphical representation of the list of linkages logged in the SharePoint List.
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446121-adba870d-0bb9-461b-a1ab-ff5b9cf3455a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MTIxLWFkYmE4NzBkLTBiYjktNDYxYi1hMWFiLWZmNWI5Y2YzNDU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDYyNWE2MzI5MjBlNTU3Yjk3NjM0YzE5N2RiNTlkMWNlNWEyMmQ1Y2I4NWUxOGVmMmNmMjk4MmQwY2NlYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZokuSood6RrPO2xznC1koQCfxBYenSTOjwWcbm4Gi0)
> 
> This was working perfectly until the first week of July and since then it has stopped rendering the links and looks like this.
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446163-155d4520-b3a9-4282-8192-5dfa3dc46473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MTYzLTE1NWQ0NTIwLWIzYTktNDI4Mi04MTkyLTVkZmEzZGM0NjQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDg4OTYzNjFjMTRhNDc0YjUyMzFkNDZkNGIyYzMxYTdlOWVmNTE2MWM5M2JhNTdjNTQyYTU1MWQwZTBjMmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TUrm_cLobROi6rPgrc_BLVy4Xbs49TXGHRp33A1kM0k)
> 
> Sorry, something went wrong Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details. TECHNICAL DETAILS Error details: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType') Troubleshoot issues with Microsoft SharePoint Foundation. Correlation ID: 564d43a1-c08c-9000-a2f1-704aad0a5276 Date and Time: 8/5/2024 6:09:19 AM The warning indicates that there is an issue connecting to the SharePoint resource. I have opened the web version of Teams to investigate further, in the developer's tools I found the following. Errors:
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446239-80ffb830-949a-4767-90f0-581f40391cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MjM5LTgwZmZiODMwLTk0OWEtNDc2Ny05MGYwLTU4MWY0MDM5MWNiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjk2ZjZjZDc2ZDM0OGQ4N2MzMTIzMTEyZTNmMzlhOTdjYTBhMDMxYmMyN2ZjM2RiNjg2OWNhMTlkNTdiNzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B72DRg8foFQ68edpdzJnKNP4F8rIYNlgPEEYi69v6IU)
> 
> Warnings:
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446267-86fd007e-d952-4654-bd8b-8c7a77d9469d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MjY3LTg2ZmQwMDdlLWQ5NTItNDY1NC1iZDhiLThjN2E3N2Q5NDY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTY4NjNjYjkxYmNiZGM4Mzc1MGI4MWI1M2UyYmUzZGE3MzJlYTAwYTVkNWNiMzJiNWIyODg0ZTcwZjJlMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KETvQm9MQs6VfR0Wk1Cr2w7ZSbUvCb7TxHeFVGmd8Po)
> 
> Information:
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446301-8beeaff8-3480-452d-b32c-bde8c67e9ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MzAxLThiZWVhZmY4LTM0ODAtNDUyZC1iMzJjLWJkZThjNjdlOWJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2ExNjhkYzZiMDU3YTlhYmI2YmI3OGNmZjBmMWMxNTlmYjZlYjY2ZGRkNTJhMzhlNTA4ZDU0MDRkMTBkMWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yK2q3QCak6SCBk1kZBVqvm2z8_N0d_D8GL5FromzKqk)
> 
> There are authorized connections using tokens being displayed. Which makes me question the connections being made to the SharePoint site to retrieve the data. There are 3 errors from Precompiled-web-work…js, flowed by a 403 error which is a connection to graph.microsoft.com which I assume is a denial of connection to the SharePoint API, which I use in the TypeScript code:
> 
> ![image](https://private-user-images.githubusercontent.com/159413850/355446349-c1d3f5d3-616b-405a-804c-74f91a6ba92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ2MzQ5LWMxZDNmNWQzLTYxNmItNDA1YS04MDRjLTc0ZjkxYTZiYTkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDk0YjJlMWNjNGZlN2FkMDNmMDgxYzJlNGJhYWUxM2E0NzYxMDliMmQxMzhmNmExMzhlYmQzNDA0M2YxNDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-mRMaya9A-J1kfx_owEdQlimWU-0BGBEILXHTYfXvWo)
> 
> The next error Refused to compile or instantiate Web Assembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-R+g9VdMVCZC/eeynejoLZg==' 'report-sample' 'self' https://statics.teams.cdn.office.net/ Details a Policy instructing the denial of connection followed by 4 SharePoint JSON [Object Object] validation error because the code is returning a blank key: value pair array.
> 
> Assuming that a further “handshake” was required (either an access token or initiation using SSO) I tried to re-authenticate and tokenize the SharePoint connection request, this failed due to a CORS violation and late finding out that it was not required and a simple spHttpClient request would suffice to facilitate the REST API. However other people are having a 403 connection error to SharePoint Lists
> 
> ### Steps to reproduce
> The Production App
> 
> 1. Click on Icon
> 2. page would have loaded
> 3. Error loads
> 
> The Dev
> 
> 1. Click On Environment local.
> 2. Same error page loads.
> 
> if you open Terminal and run gulp serve the images in the application load
> 
> ### Expected behavior
> The App is meant to look like this: ![image](https://private-user-images.githubusercontent.com/159413850/355449982-6a4e46d3-058f-41f5-bc04-3ba5a7f86515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDgyMzksIm5iZiI6MTcyMjk0NzkzOSwicGF0aCI6Ii8xNTk0MTM4NTAvMzU1NDQ5OTgyLTZhNGU0NmQzLTA1OGYtNDFmNS1iYzA0LTNiYTVhN2Y4NjUxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMjM4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmFlNTVkMzEwYzg1MTJlOWY3MWNjMDZlOTg5NThhMGFkMmUwNjFkNjBjN2M4NjI5ODVkOTc1MDQzYzk3NGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AQdpTbWjdWtLlyDZRkUQ2FRiodzmAQH70bT1PFMqymw)

**Comment by VesaJuvonen** [comment]
Issue has been resolved. Seems that the issue was caused by SPFx package which was not activated at the tenant level for the Teams experience to pick it up.
