### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/sp-dev-docs#985]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
As of today a SPFx webpart stopped working because of a manifest file not found.

#### Observed Behavior
This webpart is working fine when running from `gulp serve`, but after deploying it shows:
```
TECHNICAL DETAILS
***ERROR MESSAGE:
***Failed to load component ce22fa3c-0872-47b7-b69b-22320e3b9e6f.
Original error: ***Manifest not found for component id 0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d and version 15.4.2.
```

This occurs in Sharepoint online.

The (first release) tenant with this issue is loading SPFx from `https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-10-13.002`. I couldn't find any other tenant with this version, I've checked two other first release tenants and they use an older version `sp-client-prod_2017-10-06.008`. Those tentants don't have this issue with the webpart.

**Comment by RoelVB** [comment]
Solved this issue by generating a new SPFx webpart en copying all the old code in there (even the app id's).
So all the code is exactly the same, but for some reason it works.

**Comment by jusper-dk** [comment]
The same issue! My web part worked fine for months and now our customers are getting the error:
Original error: ***Manifest not found for component id "0d910c1c-13b9-4e1c-9aa4-b008c5e42d7d" and version "0.14.8".

**Comment by waldekmastykarz** [comment]
@jusper-dk could it be that you're using a pre-release version of the SharePoint Framework in your web part?
