### ISSUE TITLE
SPFX V 1.19.0 Install Error missing version mismatch package.json file?: No matching version found for @microsoft/spfx-heft-plugins@1.20.1-tool-dev.126

### ISSUE THREAD

**Issue by React365-Chris** [SharePoint/sp-dev-docs#9850]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

When installing v1.19.0 I get an non passable error on my machine. Its looking for a missing package.

No matching version found for @microsoft/spfx-heft-plugins@1.20.1-tool-dev.126

I can see that 1.20.1 is on NPM but am not sure how to solve this issue? 

### Steps to reproduce

1. npm install @microsoft/generator-sharepoint@latest --global
2.
3.

### Expected behavior

Install w/success

**Comment by VesaJuvonen** [comment]
Hi @React365-Chris,
we had a small moment in time yesterday when the packages were unfortunately broken - due to a configuration error in internal package handling. Situation has been however now resolved and if you try to install the Yeoman generator again - it should work as expected.

**Please confirm that things are good from your side**. Sorry for the inconvenience this caused.

**Comment by React365-Chris** [comment]
Hi @VesaJuvonen 

Thank you for looking into this. As of this morning I am able to install the latest version on my dev machine. 

I still see the teams toolkit thrown an error when it tries to install 1.19.0 in the ttk directory when adding a SPFX web part to an existing solution. TTK does not recognize 1.19.0 was installed on my system but it is there when I npm list. Will keep digging.
