### ISSUE TITLE
Add instructions on replacing {tenantDomain}

### ISSUE THREAD

**Issue by darrenw-npi** [SharePoint/sp-dev-docs#9859]
This page doesn't seem to say anywhere that you need to replace `{tenantDomain}` in `serve.json` with your own Sharepoint domain name. This causes confusion when you first run `gulp serve` as it doesn't open the correct web page. This could cause Developers (especially the beginners who are the likely target audience for this document) to be put off Sharepoint development.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
You aren't supposed to update it... you use the environment variable to let the gulp serve process set it: 

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.17
https://www.voitanos.io/blog/set-spfx-hosted-workbench-test-site/

**Comment by darrenw-npi** [comment]
> You aren't supposed to update it... you use the environment variable to let the gulp serve process set it:

Oh right! Thanks for explaining that. The setup article https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment probably needs updating then

**Comment by darrenw-npi** [comment]
Accidentally closed this. I'll submit a new PR for that

**Comment by andrewconnell** [comment]
When I saw your PR & issue, I went looking & was surprised it wasn't in the setup... so I already too care of it in #9867

I'm going to reclose this.

**Comment by darrenw-npi** [comment]
Out of interest the warning message when you run `gulp serve` says "Warning - [spfx-serve] Placeholder {tenantDomain} was found in server.json but OS variable SPFX_SERVE_TENANT_DOMAIN is not set. Either set the environment variable or update the serve.json initial page url."

I'm guessing it gives the option of updating **serve.json** in case you work with mutliple tenant domains? - like a freelancer might do for example. Also note that there is a typo as it references **server.json** instead of **serve.json** near the start of the sentence.

**Comment by andrewconnell** [comment]
Sure... you can change **serve.json** if you want to, but this would get checked into source control. This way, each developer on a team can have their own unique dev environment without having to update the repo..
