### ISSUE TITLE
_api/SP.APIHubConnector no docs for QueryOptions, and has no $select support

### ISSUE THREAD

**Issue by johnnliu** [SharePoint/sp-dev-docs#987]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I've been following a bug in a Flow connector that has lead me back to SharePoint Team.  The Flow connector has problems (both trigger and action) on cross site lookup fields.

Increasingly I see people hurling abuse at the teams complaining the connector doesn't work - it's quite broken for months.  Get List Item essentially is broken if the list has even one cross site lookup.  This is broken both for the Trigger as well as any lookup Action.

The documentation points to this CSOM method, but there's no details about what parameters are accepted for QueryOptions

https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.client.apihubconnector.getlistitems.aspx

#### Desired Outcome

1. QueryOptions documented - is $select possible?  Doesn't seem to work
2. Support $select and then we can chase the Flow team to implement it in the action.  This can allow us to ignore columns to make the action work.

#### Observed Behavior

But it seems the error comes from a SharePoint connector, here: 

https://contoso.sharepoint.com/intranet/_api/SP.APIHubConnector.GetListItems(listName='0475bf8e-98be-41d1-848f-a2668f17b5d3',queryOptions=@q)?@q='$orderby=Title $top=5'

> Microsoft.SharePoint.SPException
> The field 'CrossSiteListField' is not supported in query. The lookup list is in another web.

I hoped we could specify the $select query options - then the users can choose to skip the lookup column, or just pull back the lookup/id via $expand without trying to resolve the cross site list.  But $select doesn't seem to have any effect.

https://contoso.sharepoint.com/intranet/_api/SP.APIHubConnector.GetListItems(listName='0475bf8e-98be-41d1-848f-a2668f17b5d3',queryOptions=@q)?@q='$select=Title,Id $orderby=Title $top=5'

#### Steps to Reproduce

1. In a root site - create a site column that's a lookup to a list on the rootweb.
2. In a sub site - add site column to a list in the subsite
3. Call sub site list via SP.APIHubConnector.GetListItems

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
