### ISSUE TITLE
List Formatting - Issue clicking in Board View using customCardProps "click" opens Edit item Form

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9884]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version

### Describe the bug / error

Dear Mr. @shagra-ms, @tpodugu-ms, @arkogupta,
I would like to report the following issue and inconsistent behavior Board View with declarative action customCardProps "Click":

When using the declarative customCardProps "Click" in Board View, the Edit Form appear with combination of customCardProps. 
- Expected behavior is when **customCardProps click is made the Edit Form dialog should not appear**.

![ErrorListFormattingClickBoard](https://github.com/user-attachments/assets/485fb594-52b9-4af2-abae-b299de83a149)

### Steps to reproduce

1. Add Board View
2. Add Title and description Column
3. Include following View Formatting for Card and click on button to see behavior.
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/board-formatting.schema.json",
  "hideSelection": false,
  "formatter": {
    "elmType": "div",
    "attributes": {
      "class": "sp-card-container sp-card-container-noPadding"
    },
    "children": [
      {
        "elmType": "button",
        "style": {
          "margin": "10px",
          "padding": "20px"
        },
        "txtContent": "Click here",
        "customCardProps": {
          "openOnEvent": "click",
          "formatter": {
            "elmType": "div",
            "style": {
              "padding": "20px"
            },
            "children": [
              {
                "elmType": "div",
                "style": {
                  "padding": "10px"
                },
                "children": [
                  {
                    "elmType": "div",
                    "style": {
                      "padding": "10px",
                      "font-size": "20px",
                      "border": "1px solid black",
                      "cursor": "pointer"
                    },
                    "attributes": {
                      "iconName": "WavingHand"
                    },
                    "txtContent": "Click me to open 2 dialog",
                    "customCardProps": {
                      "openOnEvent": "click",
                      "formatter": {
                        "elmType": "div",
                        "children": [
                          {
                            "elmType": "div",
                            "style": {
                              "padding": "10px",
                              "font-size": "20px",
                              "border": "1px solid black",
                              "cursor": "pointer"
                            },
                            "attributes": {
                              "iconName": "WavingHand"
                            },
                            "txtContent": "Click me again",
                            "customRowAction": {
                              "action": "setValue",
                              "actionInput": {
                                "Title": "=Number(@now)"
                              }
                            }
                          }
                        ]
                      }
                    }
                  },
                  {
                    "elmType": "div",
                    "style": {
                      "padding": "10px",
                      "font-size": "15px",
                      "font-weight": "bold"
                    },
                    "txtContent": "Title:"
                  },
                  {
                    "elmType": "div",
                    "style": {
                      "padding": "10px"
                    },
                    "txtContent": "[$Title]"
                  },
                  {
                    "elmType": "div",
                    "style": {
                      "padding": "10px",
                      "font-size": "15px",
                      "font-weight": "bold"
                    },
                    "txtContent": "Description:"
                  },
                  {
                    "elmType": "div",
                    "style": {
                      "padding": "10px"
                    },
                    "txtContent": "[$Description]",
                    "inlineEditField": "[$Description]"
                  }
                ]
              }
            ]
          }
        }
      }
    ]
  }
}
```

### Expected behavior

When using the declarative customCardProps "Click" in Board View, the Edit Form appear with combination of customCardProps. 
- Expected behavior is when **customCardProps click is made the Edit Form dialog should not appear**.

**Comment by aaclage** [comment]
@tpodugu-ms, @arkogupta, for your consideration.

**Comment by Fedes365** [comment]
@aaclage bug confirmed on my tenant too.

**Comment by aaclage** [comment]
Dear Mr. @tpodugu-ms, @arkogupta, 

Any update on this topic?

**Comment by jgupta-msft** [comment]
Thanks for bringing to attention. Actively investigating all these issues reported on GitHub, expect update soon.

**Comment by arkogupta** [comment]
@aaclage This has been fixed. Fix should reach your tenant by the week of 14th October.

**Comment by aaclage** [comment]
@arkogupta
I will wait/test and then close after confirmation.

 Thank you for the update and support.

**Comment by aaclage** [comment]
@arkogupta Test and is working as expected. 

Thank you for your support.

**Comment by aaclage** [comment]
Dear @arkogupta,@jgupta-msft

I use the following base as described here and issue returns, looks like a roolback or something. 
Should create new ticket or should keep this one?
