### ISSUE TITLE
Additional property on context: User first release participation flag

### ISSUE THREAD

**Issue by weshackett** [SharePoint/sp-dev-docs#99]
Can we have an indication if the user is receiving the First Release experience for Office 365. I would like to be able to have a web part which can do different things according to the viewing user enrolment in FR.

**Comment by patmill** [comment]
Closing non-issue entries.  If you still need this, can you open a request in user-voice ( https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/ ) ?
