### ISSUE TITLE
unit test cases spfx with sinon 

### ISSUE THREAD

**Issue by deploymentvsureshk** [SharePoint/sp-dev-docs#990]
I am using one external javascript mentioned in the spfx config.json file. I have created the d.ts file for the same. 
Unit test cases if failing saying cannot find the module. 

Please advise.

Regards
Vishal gupta

**Comment by qz2017** [comment]
Can you please post the exact error message to give us more details?

**Comment by qz2017** [comment]
Closing the issue due to no response. BTW, SPFx does not support unit test yet.
