### ISSUE TITLE
Forms-customizer opens in a new TAB

### ISSUE THREAD

**Issue by EA12** [SharePoint/sp-dev-docs#9904]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Version 128.0.2739.42 (Offizielles Build) (64-Bit)
- SPFx version 1.19.0 & also in 1.18.2
- Node.js version: 18.19.0

### Describe the bug / error

Today, suddenly creating a new list item in a custom list, opens the Form in a new Browser-TAB which will not close after saving.
It was working today morning!
We have several Applications in production, running with Forms-Customizer which do not work now.
It looks like it has to do with the new List-Design. Forms-Customizer running in the old Design are working and do not open in a new TAB.

Hopefully, you can fix that quickly.

### Steps to reproduce

1. Create a Forms-Customizer (SPFX)
2. Attach the Customizer with PS
3. Create a new list-Item

### Expected behavior

Should not open in a new TAB and can be saved.

**Comment by EA12** [comment]
Hi,

even Lists which had the old List-Design are having now (since today morning) the new Design and the Forms-Customizer are not working anymore! - but that is different for some users.

Please help, a lot of our Applications and Processes stopped working because of this!

**Comment by spmattw** [comment]
Hi, we face the same issue as of this morning in all our own and customer tenants (even in standard release!)
Also custom command bar actions for selected items are not loading. This is business critical in some of our solutions.

Can you please make sure to load the old modern UI again asap as long as the new one is not working properly?
Why do we have a first release option if you release not well tested stuff to production tenants directly?!

Thanks for fixing.
Kind regards
@VesaJuvonen

**Comment by EA12** [comment]
I opened a Ticket: 2409041410000557 and have a discussion in some minutes. let's see what they say...

**Comment by EA12** [comment]
My Meeting with MS is over. They understand that this is critical and will discuss it in Development- and Global-Team today.
Hopefully they fix it, soon or even rollback the latest update. I will keep you informed.

**Comment by spmattw** [comment]
Awesome, thanks @EA12

**Comment by adriangoszczynski** [comment]
Same here. But funny story is that we reported the issue to MS a few weeks ago. For some users it showed UI from MS List. For those users workarounds mentioned in thread https://github.com/SharePoint/sp-dev-docs/issues/9514#issuecomment-2328680668 helped. But as of today those workarounds don't help and the issue has also become critical.

What I found, that if you change default form of the list to Power Apps, list will open in previous UI. But in our case this is not a real workaround.

**Comment by EA12** [comment]
I am still in discussion with MS. currently the issue is in discussion with 3rd level Agents. i provived all the details, screenshots and even recordings. They will come back to me, later that day....

**Comment by EA12** [comment]
Their answer: Issue is OOB for our support as it falls under developer support. 
As we get no help here, I will open a ticket with Premier/Unified Support.

@VesaJuvonen : Can you help? - This is so frustrating...

**Comment by spmattw** [comment]
Thanks Microsoft for rolling everything back. Please, in the future just roll out in first release tenants and give us the possibility to test and keep opening custom forms in the panel or the dialog.

**Comment by EA12** [comment]
Phew, that was really tiring again. No transparency whatsoever for roll-outs of this type, no feedback despite open tickets - Unfortunately, we have known this for years and that is what makes it so exhausting overall. I can also confirm that it is now working again. - Get well soon!

**Comment by EA12** [comment]
Rolling back the update helped to solve the issue

**Comment by adriangoszczynski** [comment]
> Thanks Microsoft for rolling everything back. Please, in the future just roll out in first release tenants and give us the possibility to test and keep opening custom forms in the panel or the dialog.

It was rollout in first release in March I think. People reported already issues that time. But looks like, there is something wrong at Microsoft, that thay didn't care about that.
