### ISSUE TITLE
"Content Shifting" with custom AplicationCustomizer - How to Control the rendering in mordern experience

### ISSUE THREAD

**Issue by ltouro** [SharePoint/sp-dev-docs#991]
#### Category
- [X] Question

#### Expected or Desired Behavior

After creating a custom ApplicationCustomizer, the page is rendered with the custom elements added through ApplicationCustomizer.

#### Observed Behavior

After creating a custom ApplicationCustomizer, the page is rendered as-is (default) and custom elements are added or changed (shortly) after the page is loaded, creating the "content shifting" visual effect.

#### Question

Is there any documented way to get around this effect?

For instance,:

* It is possible to guarantee that a custom Stylesheet is loaded before the initial render of page, in order to avoid "content shifting"? Is SPComponentLoader the way to go?

* It is possible to guarantee that a custom Component is loaded and ready before the initial render of modern experience page, in order to avoid "content shifting"?

* It is possible to provide/control a "global" loading display, until all componentes are ready?

**Comment by manishgarg1** [comment]
Hi @ltouro, thank you for reporting this issue. This behavior is currently by design for application customizers. We first load the application code and then the custom code. 

That said, we would like to understand your scenario a bit better. Do you know the exact size of the space you need such that we can pre-allocate a placeholder to avoid jumpiness? Can that information be provided in the manifest of the customizer?

**Comment by ltouro** [comment]
@manishgarg1 specifying an area in the manifest will remedy some of these cases for sure, but I think this is not the most comprehensive solution (for instance, dynamic component heights or pure style changes issues -- like color and fonts).

What about have one or more stylesheets loaded at the "head" section of the page? This would allow the user to have a proper "loading screen" or put the required styles right in there. Is this possible already, by any means? 

In my case, defering the initial page render is better than showing a content and then modifying it.

**Comment by manishgarg1** [comment]
Hi @ltouro, we are still looking at this. No decision on the final design yet. Since this is a feature request, I would urge you to open a request on UserVoice also (http://aka.ms/sp-dev-uservoice). That will help us prioritize this against the other stack of work we have. Thanx for the patience.

**Comment by ltouro** [comment]
@manishgarg1 Thank you for the feedback! Glad to hear you guys are looking into this. I added the feature request for the "Styles in HEAD section" solution, as I did not found any existing request for this. 

If there is a specific issue to track this discussion here in GitHub, please point me to it. I would love to follow it.
