### ISSUE TITLE
Setting an empty value for a field throws error

### ISSUE THREAD

**Issue by sch-alib** [SharePoint/sp-dev-docs#9913]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

The latest splistwebpack files seems to be throwing an error when I try to (re)set an empty value for a field is list/lib item

![image](https://github.com/user-attachments/assets/e54f9158-8478-47ad-80f3-e1511b86846f)
![image](https://github.com/user-attachments/assets/7f7d2266-cf5f-441f-aeb2-8fb6d936b66f)

### Steps to reproduce

1.Edit a list item that has a (single line text) field, that has an existing data in the field
2.Delete all characters from the field value (empty string)
3.Press tab key, or just try to save the item

### Expected behavior

Depending of the type of field, for example if its a single line of text that does not require a value, an empty string should be set successfully

**Comment by michaelmaillot** [comment]
Hi,

I confirm I can repro same issue on several environments.

**Comment by sch-alib** [comment]
This issue seems to have been fixed with the latest splistwebpack version

![image](https://github.com/user-attachments/assets/fa88d76c-3a63-4578-864e-c91bf8910e69)

**Comment by michaelmaillot** [comment]
Yes, I confirm it's also working from my side.
