### ISSUE TITLE
DatesInUtc parameter of RenderListDataAsStream not working

### ISSUE THREAD

**Issue by gabbsmo** [SharePoint/sp-dev-docs#9916]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint CSOM

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

The `RenderListDataAsStream` API has a parameter `DatesInUtc`. When it is true, it indicates that any DateTime values in the Caml query is in universal time. However, since today or earlier, it no longer seem to work. For the same query, I need to set the site's time zone to UTC to get any results.

### Steps to reproduce

1. Set time zone in regional settings to Stockholm
2. Create a file with the value 2024-07-07 for the field TestDate
3. Call RenderListDataAsStream with the following parameters and CAML query:

```
RenderListDataParameters
{
    ViewXml = viewXml,
    DatesInUtc = true,
    RenderOptions = RenderListDataOptions.ListData,
    RenderURLFieldInJSON = true
}
```

```
<View Scope='Recursive'>
    <Query>
        <Where>
            <Eq>
                <FieldRef Name='TestDate' />
                <Value IncludeTimeValue='TRUE' Type='DateTime'>2024-07-06T22:00:00Z</Value>
            </Eq>
        </Where>
        <OrderBy UseIndexForOrderBy='FALSE' Override='FALSE'>
            <FieldRef Name='Modified' Ascending='False' />
        </OrderBy>
    </Query>
    <ViewFields>
        <FieldRef Name='ContentTypeId' />
        <FieldRef Name='Modified' />
        <FieldRef Name='FileLeafRef' />
        <FieldRef Name='File_x0020_Type' />
        <FieldRef Name='Title' />
        <FieldRef Name='TestChoice' />
        <FieldRef Name='TestNumber' />
        <FieldRef Name='TestDate' />
        <FieldRef Name='TestMmd' />
        <FieldRef Name='TestMmdMulti' />
        <FieldRef Name='TestPeopleMultiple' />
        <FieldRef Name='TestNote' />
        <FieldRef Name='TestBoolean' />
        <FieldRef Name='Editor' />
        <FieldRef Name='FileDirRef' />
        <FieldRef Name='File_x0020_Size' />
        <FieldRef Name='CheckoutUser' />
        <FieldRef Name='CheckedOutUserId' />
        <FieldRef Name='ContentType' />
        <FieldRef Name='ContentTypeId' />
        <FieldRef Name='Editor' />
        <FieldRef Name='File_x0020_Size' />
        <FieldRef Name='File_x0020_Type' />
        <FieldRef Name='FileRef' />
        <FieldRef Name='FileLeafRef' />
        <FieldRef Name='HTML_x0020_File_x0020_Type' />
        <FieldRef Name='Modified' />
        <FieldRef Name='_UIVersionString' />
        <FieldRef Name='_CheckinComment' />
    </ViewFields>
    <RowLimit Paged='TRUE'>50</RowLimit>
</View>
```

5. Notice there are no results
6. Change time zone to UTC
7. Try again
8. Notice that there are results

### Expected behavior

When using the DatesInUtc parameter, passing DateTime values in UTC, and there are matching items I expect them in the result, regardless of regional settings.

**Comment by highfly117** [comment]
we are having similar issues in power automate when doing renderlistasdatastream it only returning 1 value when there should be 40ish, similar thing happens when we create a custom view and filter on the same thing we only get one value returned

**Comment by gabbsmo** [comment]
I am relieved to hear that I am not alone.

**Comment by gabbsmo** [comment]
Adding the attribute `StorageTZ='TRUE'` to date values seem to help. I could swear this was not necessary before.

Working example:
`<Value StorageTZ='TRUE' IncludeTimeValue='TRUE' Type='DateTime'>2024-07-06T22:00:00Z</Value>`
