### ISSUE TITLE
List Formatting - Datetime picker dialog "inlineEditField" is not overlay when using Board View

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9926]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version

### Describe the bug / error

When using declarative formatting in Board View card that include date picker inlineEditField it's identify that calendar dialog box is not overlay and hide behind the bucket.

![CalendarPicker](https://github.com/user-attachments/assets/0fbdb3c3-6c75-4daa-abfe-66e75a06191c)

### Steps to reproduce

1. Create Sample List
2. Create Column "StartDate" with type "Date and Time"
3. Create Board View 
4. Customize card with following json 

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/board-formatting.schema.json",
  "hideSelection": false,
  "formatter": {
    "elmType": "div",
    "attributes": {
      "class": "sp-card-container sp-card-container-noPadding"
    },
    "children": [
      {
        "elmType": "div",
        "style": {
          "width": "100px",
          "margin": "10px",
          "padding-left": "120px"
        },
        "children": [
          {
            "elmType": "div",
            "txtContent": "[$StartDate]",
            "inlineEditField": "[$StartDate]"
          }
        ]
      }
    ]
  }
}
```

### Expected behavior

It's expected when using "inlineEditField" and select  "Date and Time" that calendar dialog is overlay and not hide in bucket when using Board View. 

![CalendarPicker](https://github.com/user-attachments/assets/5f94a555-70ba-4cc0-86b9-70253d2bbdff)

@tpodugu-ms, @arkogupta, @jgupta-msft for your consideration.

**Comment by tpodugu-ms** [comment]
@aaclage Thank you for bringing this to our attention. We will provide an update on this soon.

**Comment by aaclage** [comment]
Dear @tpodugu-ms,
I tested on my sandboxes and issue doesn't appear. 

I will close ticket and thank you for your support on this topic.
