### ISSUE TITLE
List - Multiple Drag and Drop card in Board View is not working

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9934]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Microsoft List is releasing the capability to make drag and drop and multiple drag and drop in List View, but multiple drag and drop in List Board is not available.  Since List View has the feature I assume this option should be available in Board View.  Don't know if this is a bug or expected behavior?!
![MultipleBoardDragDrop](https://github.com/user-attachments/assets/717e6ebd-57c0-4142-9cc6-6a1dd5473379)

### Steps to reproduce

1. Create List
2. Add Fields
3. Create multiple items
4. Add Board View with bucked field
5. Check 2 cards and try to drag and drop on other bucket, only one moves.

### Expected behavior

Since List View has the feature of multiple item drag and drop,  I assume this option should be available in Board View.  Don't know if this is a bug or expected behavior?!
![MultipleBoardDragDrop](https://github.com/user-attachments/assets/717e6ebd-57c0-4142-9cc6-6a1dd5473379)

**Comment by aaclage** [comment]
@tpodugu-ms, @arkogupta, @jgupta-msft for your consideration. I don't know if this expected behavior and if is under your umbrella of support tasks.

Thank you for your support.

**Comment by arkogupta** [comment]
@aaclage Thanks for pointing this out. This is not supported in board view yet and we do have this in our backlog.

**Comment by aaclage** [comment]
@arkogupta Thank you for your input. I will close the ticket since is not on scope of current deliver features.
