### ISSUE TITLE
SPFX Property panel UI - Title issue

### ISSUE THREAD

**Issue by matthong** [SharePoint/sp-dev-docs#994]
![wpwithlongname](https://user-images.githubusercontent.com/12601555/32077620-0e46a09a-ba72-11e7-9cbf-d82df493850e.JPG)
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
The property pane should be able to display its title in a nice way, even if the Web Part has a long name.

#### Observed Behavior
The title of the property pane is wrapped if the Web Part name is long. 

#### Steps to Reproduce
Simply create a HelloWorld Web Part, then change the "title" attribute in the manifest file to a long name. Run the workbench, add and edit the Web Part, you will see the title of the property pane is wrapped to multiple lines, the 1st line is displayed correctly, but you can only see the top of the 2nd one.

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by dgaeta** [comment]
@matthong Thanks for your feedback! We have made this change and it will be rolled soon.
