### ISSUE TITLE
Yeoman Sharepoint generator offers me to create new solution, but project is aleady exists

### ISSUE THREAD

**Issue by azabr** [SharePoint/sp-dev-docs#995]
#### Category

- [x] Bug

I have project with 3 web parts, and i want to add field extension in current project, i run yo command:

`yo @microsoft/sharepoint`,

 but he offers me to create new Solution, why??

<img width="628" alt="2017-10-27 11 27 15" src="https://user-images.githubusercontent.com/16599420/32094831-d0012b50-bb09-11e7-95ec-cbd7dd81c7de.png">

Here folder with solution:

<img width="201" alt="2017-10-27 11 30 34" src="https://user-images.githubusercontent.com/16599420/32095019-598b9554-bb0a-11e7-9308-51665a01070b.png">

Please help!

**Comment by waldekmastykarz** [comment]
Could you double check if you have the `.yo-rc.json` file that is used to identify an existing solution? Could it be that it hasn't been copied/committed to source control by accident? Could you verify if you have correct behavior when creating a new project?

**Comment by azabr** [comment]
`.yo-rc.json` file is absent in my project

when i create new project `.yo-rc.json` file appears.

can i somehow generate or create this file in my current project?

**Comment by waldekmastykarz** [comment]
You could grab one from a new project. Just be sure it's created using the same version of the generator as your existing project.

**Comment by mpasarin** [comment]
Closing this issue as it's been resolved by @waldekmastykarz
