### ISSUE TITLE
List view formatting (gallery): wrong size of customCardProps (MS lists view in Sharepoint list)

### ISSUE THREAD

**Issue by XueSheng-GIT** [SharePoint/sp-dev-docs#9955]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Chrome 129

vti_extenderversion:SR|16.0.0.25318

### Describe the bug / error

Size of custom cards ([customCardProps](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference#customcardprops)) is wrong if used in gallery view in new list experience.
This is a regression as this was not the case for the previous SharePoint list experience.

Following view sample can be used as reference: [view-samples/praise-cards](https://github.com/pnp/List-Formatting/tree/master/view-samples/praise-cards)

Custom card has the same size as the main card (300x400). Although, this size was not defined within customCardProps.

![Screenshot 2024-10-07 102640_customCardProps (wrong size)](https://github.com/user-attachments/assets/5b5d4bd7-bd1d-4536-a90a-3bd1195d0e79)

Definition of main card size:

![Screenshot 2024-10-07 102454_view-formatting](https://github.com/user-attachments/assets/7d1d1abf-c32d-473a-886d-b96dddeaade9)

Definition of customCardProps has no influence on the size of the custom card.

![Screenshot 2024-10-07 102454_view-formatting (customCardProps)](https://github.com/user-attachments/assets/bce14fe8-0fba-4327-8e8f-d2fdebf6c345)

### Steps to reproduce

1. Create a new list
2. Add columns according to [view-samples/praise-cards](https://github.com/pnp/List-Formatting/tree/master/view-samples/praise-cards)
3. Add a new gallery view
4. Add json syntax according to [view-samples/praise-cards](https://github.com/pnp/List-Formatting/tree/master/view-samples/praise-cards)
5. Add a new list item with dummy data
6. Move mouse over the "heart" icon to show custom card

### Expected behavior

Size of custom card shall be as defined within customCardProps. This is how it's supposed to look according to the formatting sample:

![Screenshot 2024-10-07 103309_column-formatting-sample](https://github.com/user-attachments/assets/3a2947f1-89f8-41af-b22c-5dcf03670527)

**Comment by tpodugu-ms** [comment]
@XueSheng-GIT Thanks for reporting this. I will check with the team and update on this.

**Comment by deepamajhi** [comment]
@XueSheng-GIT The fix is done. It will be on prod around 12th November.

**Comment by XueSheng-GIT** [comment]
Seems to be fixed now. @deepamajhi thanks for taking care!
