### ISSUE TITLE
Updated Guidance around SharePoint Web Service Identification and Throttling (https://aka.ms/spserviceidentity)

### ISSUE THREAD

**Issue by zplume** [SharePoint/sp-dev-docs#996]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

1. The guidance contains this statement about AppID/AppTitle:
> If you have created an application, recommendation is to register and use AppID and AppTitle – This will ensure the best overall experience and best path for any future issue resolution. Include also the User Agent string information as defined in following step.

What is meant by 'use' the appID and appTitle? Is this referring to accessing SharePoint using SharePoint/Azure AD app registration (rather than using .NET CSOM with credentials or JavaScript running on a SharePoint page with no app registration)?

What about SPFx web parts that access SharePoint using REST (including pnp-js-core) or JSOM? 

2. When is it appropriate to use ISV vs NONISV?
Should 3rd party developers extending SharePoint on behalf of a client use NONISV?

3. The guidance contains this statement about JavaScript libraries:
> If you are building your own JavaScript libraries, which are used to call SharePoint Online APIs, make sure that you include the User Agent information to your http request and potentially register your web application also as an Application, where suitable.

It's not possible to set the user agent for http requests sent from a browser.
Is this referring to node.js build tooling/server applications/Azure Functions?

4. Are there any plans to update CSOM to make setting the UserAgent simpler?
Perhaps a userAgent string parameter added to a new ClientContext constructor?

Thanks!

CC: @VesaJuvonen

**Comment by paulryan** [comment]
Yes, it is not clear how this affects JS application especially those running in the context of a SharePoint page.

**Comment by mcmynn83** [comment]
When running an SPFX solution the requests are run as the user.  There is no appID or appTitle that you can decorate your requests with.  That documentation about throttling is targeting users who are using 2013 apps.

**Comment by CameronDwyer** [comment]
I'm trying to understand this guidance in respect to a standalone application (UWP, WinForms, console etc) accessing SharePoint via .Net CSOM, there is no registered App in Azure. I'm assuming this needs to be unique so that some throttling rules can identify the traffic and treat it differently? how do we go about creating this unique code and letting Microsoft know about it? CC: @VesaJuvonen
