### ISSUE TITLE
SPFx Application Customizer not working on Classic experience

### ISSUE THREAD

**Issue by cardinalpipkin** [SharePoint/sp-dev-docs#9960]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SharePoint Online
- browser version: Version 129.0.2792.79 (Official build) (64-bit)
- SPFx version:  "@microsoft/sp-core-library": "1.19.0",
- Node.js version v16.20.2

### Describe the bug / error

The extension is an Application customizer which is designed to hide the Export to Excel button on any list in a site collection for both modern and classic views. It hides it on any list in Modern view but if I switch to classic the extension is no longer "triggering"?
I have a repeated setInterval which runs the function every 5 seconds, so I know when the extension is working or not.

### Steps to reproduce

1. Create SPFx Application Customizer
2. Make sure to set the serve.json with the site you want to debug against
3. run gulp serve

### Expected behavior

It should hide the Export to Excel button on the classic experience on a SharePoint Online list.

**Comment by andrewconnell** [comment]
That's by design... all SPFx extensions require the modern experience - they do not work in the classic experience.

Refer to the 2nd paragraph on the [overview page](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions):

> **SPFx Extensions enable you to extend the SharePoint user experience within modern pages and document libraries**, while using the familiar SPFx tools and libraries for client-side development. Specifically, the SPFx includes four extension types: ...

I added the bold emphasis. If you want to do the same thing in a classic experience, you need to use the `ScriptLink` or delegate controls.

**Comment by cardinalpipkin** [comment]
Thanks Andrew, next time I will read the manual. Can you provide a link to some ScriptLink or delegate controls documentation or advice or do I have to make another ticket?

**Comment by andrewconnell** [comment]
- https://learn.microsoft.com/en-us/sharepoint/dev/schema/delegate-controls
- https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms462217
- https://learn.microsoft.com/en-us/sharepoint/dev/schema/customaction-element

Keep in mind this is all **very old tech**, dating back to SharePoint 2007. You're going to have limited success using it in newer versions of SharePoint (ie: SharePoint Online).
