### ISSUE TITLE
Why are all the buttons in the dialog in the SPFx list view command set missing?

### ISSUE THREAD

**Issue by Haiqi-Wu** [SharePoint/sp-dev-docs#9964]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [x] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version  1.19.0
- Node.js version 18.20.4
- etc

### Describe the bug / error

The buttons in the Dialog used in the deployed SPFx ListView Command Set have disappeared!
![image](https://github.com/user-attachments/assets/331e87f3-8d69-40a2-b468-3996ef2e9750)
While it still exists in the DOM, it's not visible anymore, what did Microsoft update that affected it? It was visible a week ago.

https://github.com/user-attachments/assets/c9ae9dcf-bac7-411f-8162-d7929fbe721f

### Steps to reproduce

Just follow the tutorial document and deploy it to the SPO. 

### Expected behavior

The Dialog should show the button.

**Comment by Haiqi-Wu** [comment]
The background color, text color, borders, etc. are all set to transparent.

**Comment by Haiqi-Wu** [comment]
![image](https://github.com/user-attachments/assets/fd287629-5b05-4a3e-99bf-d54e03491971)
The css variables used seem to have disappeared.

**Comment by Haiqi-Wu** [comment]
Anyone else facing the same situation?

**Comment by natalieethell** [comment]
Thanks for reporting - this looks like an issue with the FluentUI upgrade for the Primary Button. I've opened a bug with the partner team working on those updates.

**Comment by psao** [comment]
> Anyone else facing the same situation?

Yes, we are also facing this issue. Did you get any resolution?

**Comment by ymyqwe** [comment]
This bug has already been fixed. This changes should be rolled out in a couple of weeks.

**Comment by psao** [comment]
> This bug has already been fixed. This changes should be rolled out in a couple of weeks.

Thanks for the update. Another query - What might be the reason for issue occurring in one environment while the same code is working fine in another environment?

**Comment by qinxd99** [comment]
感谢您的答复。这是一个很好玩的游戏，我玩了很多年。有一个需要改进的地方，就是游戏的进度无法保存在云端，每次重新安装系统都需要从头开始。
________________________________
发件人: psao ***@***.***>
发送时间: 2024年10月21日 19:33
收件人: SharePoint/sp-dev-docs ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [SharePoint/sp-dev-docs] Why are all the buttons in the dialog in the SPFx list view command set missing? (Issue #9964)


This bug has already been fixed. This changes should be rolled out in a couple of weeks.

Thanks for the update. Another query - What might be the reason for issue occurring in one environment while the same code is working fine in another environment?

―

**Comment by Haiqi-Wu** [comment]
It seems the changes had been rolled out.
