### ISSUE TITLE
Size of required sp javascript files is too big

### ISSUE THREAD

**Issue by bpkennedy** [SharePoint/sp-dev-docs#997]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I would expect that the framework would be a reasonably optimized size for browser resource loading.

#### Observed Behavior
* office-ui-fabric-react-bundle.js = 1.7MB
* sp-webpart-workbench_en-us.js = 1.4MB
* sp-loader-assembly_en-us.js = 1.2MB
* sp-application-base.js = ~740KB
* sp-webpart-base_en-us.js = ~230KB

This just seems like a huge amount of code - is all this really necessary?  If it's not necessary for the majority of use cases, is there some way to start with a basic/reduced capability file(s) and add on modularly as needed?  Do these files only load while developing or also get included in the final compiled thing that go to the tenant?  Just trying to understand.  Most popular front-end frameworks are substantially smaller in size than this.

#### Steps to Reproduce
Generate project per the Getting Started docs.

**Comment by manishgarg1** [comment]
Hi @bpkennedy,

thank you for reporting the issue. The scripts that you see in the test project are non-tree-shaken, non-minified, non-gzipped debug scripts. We put debug scripts on purpose. The idea is that third party developers should be able to debug through issues easily. When you load a real sharepoint page in a production tenant, the size of scripts loaded is much smaller. Further we are spending a lot of energy in modularizing the scripts, code splitting and other possible options available to us to make pages load fast. Performance is critically important and are and will be working hard to keep improving it. I hope this should answer your query. Please do feel free to activate the issue in case the response is not satisfactory.
