### ISSUE TITLE
List Formatting - View Formatting: About whitespace displayed below the row  

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9971]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

Whenever I format a view, there is now a whitespace below the row. I don't believe there was ever this whitespace before. Is this a specification change? Or is it a bug?

![image](https://github.com/user-attachments/assets/77838f7e-faba-48cd-a25a-88ecd8b1242e)

![image](https://github.com/user-attachments/assets/1e734d2a-d24c-4095-8fdb-9d851771f0cd)

**Comment by tpodugu-ms** [comment]
@tecchan1107 Thank you for reporting this. Could you please share the formatter JSON?

**Comment by tecchan1107** [comment]
I believe that previously, if hideSelection was set to true and hideColumnHeader was set to true, this whitespace would not have been displayed.

**Comment by tpodugu-ms** [comment]
@tecchan1107 Thank you for the inputs. Issue is fixed and will be available in prod in 2-3 weeks.

**Comment by tecchan1107** [comment]
I just checked and it was fixed! Thanks for the fix @tpodugu-ms !

![image](https://github.com/user-attachments/assets/776c8a5b-31df-4fd0-8519-2e1b42266941)
