### ISSUE TITLE
List Formatting: When an `a` element is set as a child of a `div` element with `setValue` configured, `setValue` stops working

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9988]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

In order to investigate the count of link clicks, the `a` element was placed in the child element of the `div` element with `setValue`. Previously, the `setValue` worked and counted up, but it no longer works.

![sample](https://github.com/user-attachments/assets/ee4a766f-e964-4993-963c-0a7aa8f2fde1)

Is this a bug? Or is it a specification?

### Steps to reproduce

1. Create a list
2. Create a hyperlink column with any column name
3. Create a number column with internal name `ClickCount`
4. Apply the following JSON to the hyperlink column created in 2.

<details>

<summary>Column Formatting JSON</summary>

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
  "elmType": "div",
  "style": {
    "display": "=if(@currentField == '' , 'none' , '')"
  },
  "children": [
    {
      "elmType": "div",
      "customRowAction": {
        "action": "setValue",
        "actionInput": {
          "ClickCount": "= [$ClickCount] + 1"
        }
      },
      "children": [
        {
          "elmType": "a",
          "style": {
            "text-decoration": "none",
            "padding": "5px 10px 5px 10px",
            "font-weight": "bold",
            "border-radius": "5px",
            "font-size": "13px",
            "white-space": "nowrap"
          },
          "txtContent": "@currentField.desc",
          "attributes": {
            "href": "@currentField",
            "target": "_blank",
            "class": "ms-fontColor-themePrimary ms-bgColor-themeLighter ms-fontColor-white--hover ms-bgColor-themePrimary--hover"
          }
        }
      ]
    }
  ]
}
```

</details>

### Expected behavior

When I click on the link, the link opens and `setValue` works as before.

![screenshot](https://github.com/user-attachments/assets/9842cacd-e4aa-4dab-89df-10cd9dd8877f)

(The above video was retrieved from [hyperlink-click-count](https://github.com/pnp/List-Formatting/tree/master/column-samples/hyperlink-click-count).)

**Comment by tecchan1107** [comment]
When I set the same JSON as now in the document library, `setValue` worked and `ClickCount` counted up.

![sample](https://github.com/user-attachments/assets/f2d36036-6e63-4ddb-b587-49d0a1790527)

**Comment by tpodugu-ms** [comment]
@tecchan1107 Thanks for reporting the issue. It is fixed and should be in prod in 2-3 weeks.

**Comment by myNCA-2024** [comment]
@tpodugu-ms 
@VesaJuvonen 
Hello!
I am also experiencing this issue in my environment and I am seeking a resolution.
You mentioned that the fix would take 2-3 weeks, so I would like to check the current status of the progress.

**Comment by tpodugu-ms** [comment]
@VesaJuvonen @myNCA-2024 Fix will reach to prod 100% in 1-2 days.

**Comment by tecchan1107** [comment]
I checked today and this issue has been fixed!

![sample](https://github.com/user-attachments/assets/d7be1b7d-8f59-4fad-9ac4-a5ea4a6c644e)

@tpodugu-ms 
Thank you for your help and fixing this issue!
