### ISSUE TITLE
Theming of spfx webparts does not work in classic pages anymore

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#999]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Theming according to this article (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations) should work in classic and in modern pages when building SPFX webparts.

#### Observed Behavior
In classic pages, theming seems to be broken. I can see the __themeState__ variable still in modern pages, but in classic pages it is not there anymore. In some classic sites it seems to be called __themeStateClassic__ now. Either way, theming is broken now. I am seeing this on tenants with first release enabled. In tenants without first release it is still working at the moment.

#### Steps to Reproduce
Create a sample spfx webpart as mentioned here https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations and test it. Theming is broken in classic. This also includes office-ui-fabric and office-ui-fabric-react.

**Comment by OliverZeiser** [comment]
Now with spfx 1.3.4 out, it is even easier to test, since the out of the box sample webpart is themed allready. Create a new solution, run gulp bundle and gulp package-solution and deploy it to sharepoint. Test it on a modern page and on a classic site. Theming will work on modern pages only....

**Comment by OliverZeiser** [comment]
Any updates on this one? The issue seems to be mostly related to IE. The package @microsoft/load-themed-styles seems to load styles different when using IE and since classic is still using <meta http-equiv="X-UA-Compatible" content="IE=10"> things go wrong. When putting IE in Edge mode we can get it working by manually calling loadTheme from @uifabric/styling. Also in other browsers of course. But with IE I could not find any workaround so far.

**Comment by garrytrinder** [comment]
I am also noticing this issue and as far as I can see this is an issue with SharePoint Framework not the UI Fabric Components.

I am able to reproduce the issue on a Classic Web Part Page, if I load the page with no SPFX web parts, I can inspect and see the `__themeState__` variable and see the themes stored in the `themes` object.

![image](https://user-images.githubusercontent.com/11563347/39554040-7994def4-4e68-11e8-9ce0-efaa33d7336f.png)

From what I can gather, the `__themeState__` variable is populated when `https://spoprod-a.akamaihd.net/files/odsp-next-prod_2018-04-20-sts_20180425.001/require-951f856e.js` is loaded and resolved. The script is referenced in the JS script block (#spOnePageContext) at the foot of the ASPX page.

![image](https://user-images.githubusercontent.com/11563347/39554024-6497d902-4e68-11e8-9fc7-44360636a850.png)

If I add Classic Web Parts to the page, such as List Views, everything works as normal still. This is until however I add an SPFX web part to the page. 

Reloading the page and inspecting the `__themeState__` variable, you can see that the `theme` object is `undefined` and also a function `loadStyles` is now missing.

![image](https://user-images.githubusercontent.com/11563347/39554154-1c6a1d10-4e69-11e8-8410-7c5756fa5a95.png)

Further more, after adding the SPFX web part to the page, the script block at the foot of the page does not appear to complete successfully, as I was unable to hit the same breakpoint (line 825) which was shown in the previous screenshot, something seems to go wrong after line 819.

![image](https://user-images.githubusercontent.com/11563347/39554377-54286346-4e6a-11e8-9cea-0a611ff79e06.png)

No errors are thrown in the console in relation to the SPFX web part, but it is noticeable that the script does not load and that there is a big difference in the scripts loaded with or without an SPFX web part being present.

Scripts loaded WITH SPFX web part on page
![image](https://user-images.githubusercontent.com/11563347/39554438-b95631c6-4e6a-11e8-8c98-306980b8a0f9.png)

Scripts loaded WITHOUT SPFX web part on page
![image](https://user-images.githubusercontent.com/11563347/39554477-e828f038-4e6a-11e8-9f27-2c20bde74c25.png)

**Comment by garrytrinder** [comment]
Just noticed that when the SPFX web part is on the Classic page, @Microsoft/load-theme-styles is not loaded by require.

**Comment by srvsoni** [comment]
Do we have any update on this?

**Comment by Dangerous-Mind** [comment]
Any news or workaround on this issue?

**Comment by IngressoDev** [comment]
Push

This bug still exists and it seems that there is no workaround

**Comment by patmill** [comment]
We have fixed this, and it will be rolling to production over the next couple of weeks.

**Comment by patmill** [comment]
This should be WW now.
